### PR TITLE
ESQL: Fix incorrectly optimized fork with nullify unmapped_fields

### LINKED ISSUE #142762: ESQL: incorrectly optimized fork with nullify unmapped_fields
### Description

```
SET unmapped_fields="nullify";
from employees
| FORK  (where foo != 84) (where true) 
| WHERE _fork == "fork1" 
| DROP _fork 
| eval y = coalesce(bar, baz) 
```

```
                "type": "illegal_state_exception",
                "reason": "Found 1 problem\nline 9:3: Plan [Filter[_fork{r}#8044 == fork1[KEYWORD]]] optimized incorrectly due to missing references [_fork{r}#8044]",
                "stack_trace": "org.elasticsearch.ElasticsearchException$1: Found 1 problem\nline 9:3: Plan [Filter[_fork{r}#8044 == fork1[KEYWORD]]] optimized incorrectly due to missing references [_fork{r}#8044]
```

### PR DESCRIPTION
**Pull request by kanoshiou**
This PR fixes a bug where `Fork.withSubPlans()` incorrectly reassigned new `NameId`s to its output attributes, breaking references in the upper plan. This issue specifically manifests when using `FORK` alongside the `SET unmapped_fields="nullify"` mode.

By design, a `FORK` assigns new `NameId`s to its output attributes via `refreshOutput()` to decouple them from the internal branches. This isolation is necessary to prevent unintended side effects during plan optimizations, such as aggressive constant folding leaking across branches. 

However, the previous implementation unconditionally re-minted these `NameId`s every time `withSubPlans()` was called. Because of this, any node sitting above the `FORK` (like `EVAL` or `STATS`) that already held a reference to the initial `NameId`s would suddenly point to a nonexistent ID. Downstream analysis rules would then fail to resolve these orphaned references, causing the plan execution to fail with an *"optimized incorrectly due to missing references"* error.

Fixes #142762

### CODE REVIEW

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
@astefan, I can not reproduce the failure, and it seems not related to this PR.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java [hunk 1]
```diff
@@ -89,6 +90,22 @@ private static LogicalPlan resolve(LogicalPlan plan, boolean load) {
...
+        for (LogicalPlan child : plan.children()) {
+            for (Attribute attr : child.output()) {
+                childOutputNames.add(attr.name());
+            }
+        }
+        unresolved.removeIf(ua -> childOutputNames.contains(ua.name()));
+
+        if (unresolved.isEmpty()) {
+            return plan;
+        }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java]: Thanks, I agree that this is the right solution!

And I'm super sorry I didn't notice this earlier @astefan . Bug 2 from the PR description is indeed the same problem that @idegtiarenko fixed in https://github.com/elastic/elasticsearch/pull/142300, and you two ended up implementing the very same solution.

The silver lining is that we very much agree on the solution. The added tests in this PR are great, too, as they highlight different queries where `ImplicitCasting` can introduce an intermediate step between `ResolveRefs` and `ResolveUnmapped`.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 2]
```diff
@@ -665,3 +665,93 @@ TS "k8s" | STATS max_bytes=max(to_long(network.total_bytes_in)) BY cluster = doe
 max_bytes:long | cluster:null
 10797          | null
 ;
+
+
+forkWithRowAndUnmappedKeep
+required_capability: optional_fields_nullify_tech_preview
+required_capability: fork_v9
+required_capability: fix_fork_unmapped_nullify
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec]: nit: I think we need `fork_v9` to exclude this from `CsvTests`, but we should only require 1 of `optional_fields_nullify_tech_preview` and `fix_fork_unmapped_nullify`, no?

Also applies below.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 3]
```diff
@@ -2262,6 +2262,17 @@ public enum Cap {
...
         FIX_FULL_TEXT_FUNCTIONS_ON_RENAMED_FIELDS,
 
+        /**
+         * Fixes two independent analysis bugs in {@code FORK} with {@code unmapped_fields="nullify"}.
+         * Bug 1: {@code Fork.withSubPlans()} was reassigning new {@code NameId}s to all output attributes,
+         * breaking references from upper plan nodes.
+         * Bug 2: After {@code ImplicitCasting} runs, the plan may remain unresolved because it requires a
+         * subsequent {@code ResolveRefs} pass to fully resolve. However, {@code ResolveUnmapped} runs before
+         * that second {@code ResolveRefs} pass and mistakenly treats those still-unresolved attributes as
+         * user-introduced unmapped fields, incorrectly nullifying valid references.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: nit: unfortunately, this got stale. Bug 2 is already fixed.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 4]
```diff
@@ -2262,6 +2262,17 @@ public enum Cap {
          */
         FIX_FULL_TEXT_FUNCTIONS_ON_RENAMED_FIELDS,
 
+        /**
+         * Fixes two independent analysis bugs in {@code FORK} with {@code unmapped_fields="nullify"}.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: super nit: references to the to-be-closed issues (https://github.com/elastic/elasticsearch/issues/142762
and https://github.com/elastic/elasticsearch/issues/142543) are always nice in capabilities.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/core/expression/Expressions.java [hunk 5]
```diff
@@ -32,19 +34,24 @@ public static List<Attribute> asAttributes(List<? extends NamedExpression> named
...
 
     /**
-     * @return a list of {@link ReferenceAttribute}s corresponding to the given named expressions.
-     * <p>
-     * The returned ReferenceAttributes will have new {@link NameId}s, also in the case the input contains ReferenceAttributes.
+     * Converts named expressions to {@link ReferenceAttribute}s, preserving {@link NameId}s for attributes whose name
+     * matches one in {@code existingOutput}. Genuinely new attributes get fresh NameIds.
      */
-    public static List<Attribute> toReferenceAttributes(List<? extends NamedExpression> named) {
+    public static List<Attribute> toReferenceAttributes(List<? extends NamedExpression> named, List<Attribute> existingOutput) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/core/expression/Expressions.java]: nit: method name doesn't really say what this does, now. Maybe `toReferenceAttributesPreservingIds`?

**Review by alex-spies — APPROVED** [review]
Thanks a lot @kanoshiou and @astefan !

The fix for Bug 2 was independently discovered by @idegtiarenko while fixing https://github.com/elastic/elasticsearch/issues/141870. Apologies that I didn't spot that we're fixing the same issue in both PRs.

The fix for Bug 1 (keeping name ids for existing fork attributes while refreshing) looks super good to me. Thanks a lot!

**Comment by astefan** [comment]
buildkite test this

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Fork.java [hunk 6]
```diff
@@ -105,13 +105,11 @@ public Fork replaceSubPlansAndOutput(List<LogicalPlan> subPlans, List<Attribute>
...
 
     public Fork refreshOutput() {
-        // We don't want to keep the same attributes that are outputted by the FORK branches.
-        // Keeping the same attributes can have unintended side effects when applying optimizations like constant folding.
         return new Fork(source(), children(), refreshedOutput());
     }
 
     protected List<Attribute> refreshedOutput() {
-        return toReferenceAttributes(outputUnion(children()));
+        return toReferenceAttributesPreservingIds(outputUnion(children()), this.output());
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Fork.java:112]: Hmm, this no longer refreshes the IDs. Meaning that some assumptions are either broken, or they were incorrect to have, or they're no longer valid (in the meantime).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Fork.java [hunk 7]
```diff
@@ -105,13 +105,11 @@ public Fork replaceSubPlansAndOutput(List<LogicalPlan> subPlans, List<Attribute>
     }
 
     public Fork refreshOutput() {
-        // We don't want to keep the same attributes that are outputted by the FORK branches.
-        // Keeping the same attributes can have unintended side effects when applying optimizations like constant folding.
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Fork.java:109]: This shouldn't be removed. The attribute IDs from within the branches are not kept / reused atop Fork.

**Review by bpintea — APPROVED** [review]
Left a note. But if the CI is happy, LGTM.
Also, would update the PR description:

> Because NameId equality drives attribute identity across the whole plan tree

That's not quite correct -- see [comment](https://github.com/elastic/elasticsearch/pull/143030/changes#r2923963371).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Fork.java (hunk 6 above)
Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Fork.java:112]: @bpintea can you expand on this, please? What use cases would this impact/break/change? (are we missing tests?)

**Comment by kanoshiou** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/144200)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
