### PR TITLE
Fix Two Races that Lead to Stuck Snapshots

### LINKED ISSUE #32348: Snapshot stuck in half-deleted state
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: [discovery-ec2 6.2.4, repository-s3 6.2.4]

**JVM version** (`java -version`): 1.8.0_161

**OS version** (`uname -a` if on a Unix-like system): `Linux ip-10-4-0-82 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

9 days ago, I deleted a snapshot from an S3 repository. Elasticsearch logged that the snapshot was successfully deleted. When I try to get a list of snapshots from this repository that would include the deleted snapshot, I get a `snapshot_missing_exception`. When I try to delete this snapshot again, I get an error message notifying me that another snapshot is currently being deleted. (As far as I can tell, no other snapshot in this repository is currently being deleted.)

**Steps to reproduce**:

Unable to reproduce intentionally.

**Provide logs (if relevant)**:

    [2018-07-16T00:19:26,752][INFO ][o.e.s.SnapshotsService ] [prod-es-master-0bcee31972c150cea] snapshot [d3ac96df71f141df956b0fddc8618b2e_backup:d3ac96df71f141df956b0fddc8618b2e-2018-07-13__18787545/2eEFokOTTKuHFEjJQ8K85g] deleted

---

    [2018-07-25T00:57:32,749][WARN ][r.suppressed             ] path: /_snapshot/d3ac96df71f141df956b0fddc8618b2e_backup/d3ac96df71f141df956b0fddc8618b2e-2018-07-13__18787545, params: {pretty=, repository=d3ac96df71f141df956b0fddc8618b2e_backup, snapshot=d3ac96df71f141df956b0fddc8618b2e-2018-07-13__18787545}
    org.elasticsearch.transport.RemoteTransportException: [prod-es-master-0bcee31972c150cea][10.4.1.79:9300][cluster:admin/snapshot/delete]
    Caused by: org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException: [d3ac96df71f141df956b0fddc8618b2e_backup:d3ac96df71f141df956b0fddc8618b2e-2018-07-13__18787545/2eEFokOTTKuHFEjJQ8K85g] cannot delete - another snapshot is currently being deleted
        at org.elasticsearch.snapshots.SnapshotsService$6.execute(SnapshotsService.java:1121) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[elasticsearch-6.2.4.jar:6.2.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

---

    [2018-07-25T01:40:59,466][WARN ][r.suppressed             ] path: _snapshot/d3ac96df71f141df956b0fddc8618b2e_backup/_all, params: {repository=d3ac96df71f141df956b0fddc8618b2e_backup, snapshot=_all}
    org.elasticsearch.transport.RemoteTransportException: [prod-es-master-0bcee31972c150cea][10.4.1.79:9300][cluster:admin/snapshot/get]
    Caused by: org.elasticsearch.snapshots.SnapshotException: [d3ac96df71f141df956b0fddc8618b2e_backup:d3ac96df71f141df956b0fddc8618b2e-2018-07-13__18787545/2eEFokOTTKuHFEjJQ8K85g] Snapshot could not be read
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:197) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:136) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:167) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4.jar:6.2.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
    Caused by: org.elasticsearch.snapshots.SnapshotMissingException: [d3ac96df71f141df956b0fddc8618b2e_backup:d3ac96df71f141df956b0fddc8618b2e-2018-07-13__18787545/2eEFokOTTKuHFEjJQ8K85g] is missing
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:493) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:191) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:136) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:167) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4.jar:6.2.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]
    Caused by: java.nio.file.NoSuchFileException: Blob object [snap-2eEFokOTTKuHFEjJQ8K85g.dat] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 904A7EC118E731BD; S3 Extended Request ID: iXkuSkq30rKoAgAWzfvsW/sSiUSGrQ2IOx2LgqQ0DeqFF8xLXyvp4h3rsYiToYu9tMtgGHRSbpA=)
        at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:90) ~[?:?]
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:103) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:89) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:491) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:191) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:136) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:167) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.4.jar:6.2.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.4.jar:6.2.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]

### PR DESCRIPTION
**Pull request by original-brownbear**
* Fixes two broken spots:
    1. Master failover while deleting a snapshot that has no shards will get stuck if the new master finds the 0-shard snapshot in `INIT` when deleting
    2. Aborted shards that were never seen in `INIT` state by the `SnapshotsShardService` will not be notified as failed, leading to the snapshot staying in `ABORTED` state and never getting deleted with one or more shards stuck in `ABORTED` state
* Tried to make fixes as short as possible so we can backport to `6.x` with the least amount of risk
* Significantly extended test infrastructure to reproduce the above two issues
  * Two new test runs:
      1. Reproducing the effects of node disconnects/restarts in isolation
      2. Reproducing the effects of disconnects/restarts in parallel with shard relocations and deletes
* Relates #32265 
* Closes #32348

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java [hunk 1]
```diff
@@ -246,9 +326,133 @@ public void testConcurrentSnapshotCreateAndDelete() {
...
+                                                            .execute(ActionListener.wrap(() -> {
+                                                                testClusterNodes.randomDataNodeSafe().client.admin().cluster()
+                                                                    .deleteSnapshot(
+                                                                        new DeleteSnapshotRequest(repoName, snapshotName), noopListener());
+                                                                createdSnapshot.set(true);
+                                                            }));
+                                                        scheduleNow(
+                                                            () -> testClusterNodes.randomMasterNodeSafe().client.admin().cluster().reroute(
+                                                                new ClusterRerouteRequest().add(
+                                                                    new AllocateEmptyPrimaryAllocationCommand(
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java]: Poor man's primary relocation simulation until we have non-blocking recoveries.

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java [hunk 2]
```diff
@@ -598,10 +971,17 @@ public void start(ClusterState initialState) {
                     @Override
                     public void connectToNodes(DiscoveryNodes discoveryNodes) {
                         // override this method as it does blocking calls
+                        boolean callSuper = true;
                         for (final DiscoveryNode node : discoveryNodes) {
-                            transportService.connectToNode(node);
+                            try {
+                                transportService.connectToNode(node);
+                            } catch (Exception e) {
+                                callSuper = false;
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java]: We have to bail here if a connect fails, otherwise will block while trying to reconnect.

File: test/framework/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java [hunk 3]
```diff
@@ -254,8 +256,10 @@ public String toString() {
         }
     }
 
-    private NamedWriteableRegistry writeableRegistry() {
-        return new NamedWriteableRegistry(ClusterModule.getNamedWriteables());
+    public static NamedWriteableRegistry writeableRegistry() {
```
Comment (original-brownbear) [inline test/framework/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java]: We need the named writables from `NetworkModule` for the force empty primary allocation calls added to the tests.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 4]
```diff
@@ -295,6 +294,15 @@ private void processIndexShardSnapshots(ClusterChangedEvent event) {
                                 }
                             }
                         }
+                    } else {
+                        final ImmutableOpenMap<ShardId, ShardSnapshotStatus> clusterStateShards = entry.shards();
+                        for (ObjectObjectCursor<ShardId, ShardSnapshotStatus> curr : clusterStateShards) {
+                            if (curr.value.state() == State.ABORTED) {
+                                // due to CS batching we might have missed the INIT state and straight went into ABORTED
+                                // notify master that abort has completed by moving to FAILED
+                                notifyFailedSnapshotShard(entry.snapshot(), curr.key, localNodeId, curr.value.reason());
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: I'm a little worried that we might be overloading the master by resending this again and again (assume that master is under load processing a lot of pending tasks and we keep resending this on each cluster state update). We'll probably need something along the lines of ShardStateAction.remoteFailedShardsCache`

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 5]
```diff
@@ -1197,7 +1197,11 @@ public ClusterState execute(ClusterState currentState) throws Exception {
                     if (state == State.INIT) {
                         // snapshot is still initializing, mark it as aborted
                         shards = snapshotEntry.shards();
-
+                        if (shards.isEmpty()) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: will this not always be empty in case of INIT state?

File: test/framework/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java (hunk 3 above)
Comment (ywelsch) [reply test/framework/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java]: Instead of statically collecting them here, let's make this a protected method, lift it to MockTransport and override it in SnapshotsServiceTests

**Review by ywelsch — CHANGES_REQUESTED** [review]
Thanks for this PR. I've left some initial comments, will look at the tests later.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Removed `if` and added `assert` in https://github.com/elastic/elasticsearch/pull/37686/commits/bc450e851d0ebc70c277a4a167e0b5c1449f57cf :)

File: test/framework/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java (hunk 3 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java]: Done in https://github.com/elastic/elasticsearch/pull/37686/commits/803003f92f3d2a448719c2dbd04cd51256e9bb44 :)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: Added cache in https://github.com/elastic/elasticsearch/pull/37686/commits/808c99a1c13caa64578ff351474e150815b81c01

**Comment by original-brownbear** [comment]
@ywelsch thanks for taking a look, fixed the initial points you made now.

**Comment by original-brownbear** [comment]
Jenkins run Gradle build tests 1

**Comment by original-brownbear** [comment]
@elasticmachine run Gradle build tests 1

**Comment by original-brownbear** [comment]
Jenkins run gradle build test 1

**Comment by original-brownbear** [comment]
Jenkins test this

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/MockSinglePrioritizingExecutor.java [hunk 6]
```diff
@@ -53,6 +53,12 @@ protected void afterExecute(Runnable r, Throwable t) {
         throw new KillWorkerError();
     }
 
+    // Override awaitTermination to not get blocked on termination condition
+    @Override
+    public boolean awaitTermination(long timeout, TimeUnit unit) {
+        return true;
```
Comment (ywelsch) [inline test/framework/src/main/java/org/elasticsearch/cluster/coordination/MockSinglePrioritizingExecutor.java]: return false here? Because we have not necessarily terminated all tasks.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 7]
```diff
@@ -295,11 +301,29 @@ private void processIndexShardSnapshots(ClusterChangedEvent event) {
                                 }
                             }
                         }
+                    } else {
+                        final ImmutableOpenMap<ShardId, ShardSnapshotStatus> clusterStateShards = entry.shards();
+                        final Snapshot snapshot = entry.snapshot();
+                        final Set<ShardId> cachedFailedShards = remoteFailedShardsCache.getOrDefault(snapshot, Collections.emptySet());
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: I'm confused a bit by how the cache here works (in particular the clean-up). Maybe extract the caching infrastructure in ShardStateAction (in a separate PR), and just reuse that?

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java [hunk 8]
```diff
@@ -199,6 +214,76 @@ public void testSuccessfulSnapshot() {
...
+                            }))));
+
+        runUntil(() -> {
+            final Optional<TestClusterNode> randomMaster = testClusterNodes.randomMasterNode();
+            if (randomMaster.isPresent()) {
+                final SnapshotsInProgress snapshotsInProgress = randomMaster.get().clusterService.state().custom(SnapshotsInProgress.TYPE);
+                return snapshotsInProgress != null && snapshotsInProgress.entries().isEmpty();
+            }
+            return false;
+        }, TimeUnit.MINUTES.toMillis(20L));
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java]: that's quite a long time. How long does this test typically take?

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java (hunk 1 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java]: what a hack :)

**Review by ywelsch — CHANGES_REQUESTED** [review]

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/MockSinglePrioritizingExecutor.java (hunk 6 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/cluster/coordination/MockSinglePrioritizingExecutor.java]: Yea, both are kinda wrong but returning `false` seems like at least it's not hiding anything -> changed in https://github.com/elastic/elasticsearch/pull/37686/commits/1366efc8d83d17394f426e3969bfab3de4c251d1

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java (hunk 8 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SnapshotsServiceTests.java]: Ran a few k iterations and couldn't get a run to exceed `5s` => dropped it to 1 minute (just to be safe) in https://github.com/elastic/elasticsearch/pull/37686/commits/326cd5648d7b47d09abc2a360740d4d48c52d3d4

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java (hunk 7 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: I tried to make it work analogous to the way we handle org.elasticsearch.snapshots.SnapshotShardsService#shardSnapshots (rebuild the correct map from what the state seen in this method and replace the instance), but yea it's confusing => drying this up against the logic in `ShardStateAction` sounds good imo :)

**Comment by original-brownbear** [comment]
@ywelsch all points addressed :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
@ywelsch hold off on reviewing this one please, it seems the changes here cause a test instability in the `SharedClusterSnapshotRestoreIT`, looking into that now.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
Jenkins run elasticsearch-ci/default-distro

**Comment by ywelsch** [comment]
This is currently blocked on #37870 being completed first

**Comment by original-brownbear** [comment]
@ywelsch #37870 was merged and I made us of it here now (added its use for all state updates instead of creating a special case, hope that's ok?).
This should be good for another review :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by ywelsch — CHANGES_REQUESTED** [review]
A few smaller comments, looking good o.w.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 9]
```diff
@@ -515,12 +530,28 @@ void notifyFailedSnapshotShard(final Snapshot snapshot, final ShardId shardId, f
...
+                                reqListener.onResponse(null);
+                            }
+
+                            @Override
+                            public void handleException(TransportException exp) {
+                                reqListener.onFailure(exp);
+                            }
+                        });
+                } catch (Exception e) {
+                    logger.warn(() -> new ParameterizedMessage("[{}] [{}] failed to update snapshot state", snapshot, status), e);
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: Yea, looked into this. This is never hit, the transport logic catches everything (basically just the disconnected exception) and passes it to the listener => moved the logging to the listener since this is just dead code imo.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 10]
```diff
@@ -515,12 +530,28 @@ void notifyFailedSnapshotShard(final Snapshot snapshot, final ShardId shardId, f
...
     void sendSnapshotShardUpdate(final Snapshot snapshot, final ShardId shardId, final ShardSnapshotStatus status) {
-        try {
-            UpdateIndexShardSnapshotStatusRequest request = new UpdateIndexShardSnapshotStatusRequest(snapshot, shardId, status);
-            transportService.sendRequest(transportService.getLocalNode(), UPDATE_SNAPSHOT_STATUS_ACTION_NAME, request, INSTANCE_SAME);
-        } catch (Exception e) {
-            logger.warn(() -> new ParameterizedMessage("[{}] [{}] failed to update snapshot state", snapshot, status), e);
-        }
+        remoteFailedRequestDeduplicator.executeOnce(
+            new UpdateIndexShardSnapshotStatusRequest(snapshot, shardId, status),
+            ActionListener.noop(),
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: Makes sense thanks :) Removed it from production code. (kept it in the tests though like it was before, I think logging in these tests is probably just noise and if there's an issue we can reproduce it step by step anyway?)

**Comment by original-brownbear** [comment]
@ywelsch thanks for taking a look, addressed the comments => should be good for another review :)

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@ywelsch thanks!

**Comment by ywelsch** [comment]
Is this backported? If so, remove backport label?

**Comment by original-brownbear** [comment]
@ywelsch no, unfortunately, it is not.

I cannot backport these tests and I didn't yet have time to finish writing 6.x compatible tests for this scenario.
We have two options here I guess:
* Backport without tests
* Wait for tests, which I was planning to write over the weekend or Monday

**Comment by ywelsch** [comment]
ok, let's do the tests next week and then backport. I had forgotten about the fact that this is not a straightforward backport and thought you might have missed to remove the label :)
