### PR TITLE
Fix PerFieldFormatSupplier mistake

### LINKED ISSUE #133875: [CI] LogsIndexingIT testShrink failing
**Build Scans:**
- [elasticsearch-periodic #10386 / release-tests](https://gradle-enterprise.elastic.co/s/lvg4axkou7pzg)
- [elasticsearch-pull-request #89226 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/ax4bdw5qlrofg)
- [elasticsearch-pull-request #89180 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/q3izxxswxlnsa)
- [elasticsearch-periodic #10380 / release-tests](https://gradle-enterprise.elastic.co/s/qvinwqvvzghfq)
- [elasticsearch-periodic #10374 / release-tests](https://gradle-enterprise.elastic.co/s/cahqvzbvw5sfy)
- [elasticsearch-periodic-java-ea #8 / release-tests](https://gradle-enterprise.elastic.co/s/lmq7bbiqvb5zk)
- [elasticsearch-periodic #10362 / release-tests](https://gradle-enterprise.elastic.co/s/usod4gmsiih3a)
- [elasticsearch-periodic #10356 / release-tests](https://gradle-enterprise.elastic.co/s/kumcldznvdtuk)
- [elasticsearch-periodic #10350 / release-tests](https://gradle-enterprise.elastic.co/s/srz7perzoljcu)
- [elasticsearch-periodic-java-ea #7 / release-tests](https://gradle-enterprise.elastic.co/s/mdnmx5y55ftzw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:logsdb:internalClusterTest" --tests "org.elasticsearch.xpack.logsdb.LogsIndexingIT.testShrink" -Dtests.seed=5658630F3615790B -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=fr-DZ -Dtests.timezone=Etc/GMT+7 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.logsdb.LogsIndexingIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testShrink'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: [1] shard failures
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testShrink
- [main] 9 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart2_release-tests
- [main] 11 failures in test testShrink (4.0% fail rate in 272 executions)
- [main] 9 failures in step release-tests (100.0% fail rate in 9 executions)
- [main] 2 failures in step checkpart2_release-tests (100.0% fail rate in 2 executions)
- [main] 7 failures in pipeline elasticsearch-periodic (87.5% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (3.1% fail rate in 65 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-java-ea (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #133993: [CI] LogsIndexingIT testRouteOnSortFields failing
**Build Scans:**
- [elasticsearch-periodic #10406 / release-tests](https://gradle-enterprise.elastic.co/s/xonccfoi66kpc)
- [elasticsearch-pull-request #89180 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/q3izxxswxlnsa)
- [elasticsearch-periodic #10380 / release-tests](https://gradle-enterprise.elastic.co/s/qvinwqvvzghfq)
- [elasticsearch-periodic #10374 / release-tests](https://gradle-enterprise.elastic.co/s/cahqvzbvw5sfy)
- [elasticsearch-periodic #10362 / release-tests](https://gradle-enterprise.elastic.co/s/usod4gmsiih3a)
- [elasticsearch-periodic-java-ea #7 / release-tests](https://gradle-enterprise.elastic.co/s/mdnmx5y55ftzw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:logsdb:internalClusterTest" --tests "org.elasticsearch.xpack.logsdb.LogsIndexingIT.testRouteOnSortFields" -Dtests.seed=38CF8253343C4B7 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=br-FR -Dtests.timezone=Pacific/Tongatapu -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.logsdb.LogsIndexingIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRouteOnSortFields'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeAwait: CountDownLatch did not reach zero within the timeout
```

**Issue Reasons:**
- [main] 6 failures in test testRouteOnSortFields (1.3% fail rate in 461 executions)
- [main] 5 failures in step release-tests (41.7% fail rate in 12 executions)
- [main] 4 failures in pipeline elasticsearch-periodic (40.0% fail rate in 10 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by martijnvg**
Correctly use seqno_field_use_tsdb_doc_values_format feature flag to ensure _seq_no doesn't get excluded.

Marking as non-issue as this would only be a bug in a released stateful release.

Closes #133875
Closes #133993

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/codec/PerFieldFormatSupplier.java [hunk 1]
```diff
@@ -126,13 +146,7 @@ boolean useTSDBDocValuesFormat(final String field) {
     }
 
     private boolean excludeFields(String fieldName) {
-        // TODO: should we just allow all fields to use tsdb doc values codec?
-        // Avoid using tsdb codec for fields like _seq_no, _primary_term.
-        // But _tsid and _ts_routing_hash should always use the tsdb codec.
-        return fieldName.startsWith("_")
-            && fieldName.equals("_tsid") == false
-            && fieldName.equals("_ts_routing_hash") == false
-            && (SEQNO_FIELD_USE_TSDB_DOC_VALUES_FORMAT.isEnabled() && fieldName.equals(SeqNoFieldMapper.NAME) == false);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/codec/PerFieldFormatSupplier.java:135]: Checking whether feature flag is enabled and whether seqno should not be excluded can't be expressed this way. Because if feature flag is disabled this then results in the field not being excluded.

**Review by dnhatn — APPROVED** [review]
LGTM, thanks Martijn!

File: server/src/main/java/org/elasticsearch/index/codec/PerFieldFormatSupplier.java [hunk 2]
```diff
@@ -27,15 +27,37 @@
...
+        // TODO: should we just allow all fields to use tsdb doc values codec?
+        // Avoid using tsdb codec for fields like _seq_no, _primary_term.
+        // But _tsid and _ts_routing_hash should always use the tsdb codec.
+        Set<String> includeMetaField = new HashSet<>(3);
+        includeMetaField.add(TimeSeriesIdFieldMapper.NAME);
+        includeMetaField.add(TimeSeriesRoutingHashFieldMapper.NAME);
+        if (SEQNO_FIELD_USE_TSDB_DOC_VALUES_FORMAT.isEnabled()) {
+            includeMetaField.add(SeqNoFieldMapper.NAME);
+        }
+        // Don't include _recovery_source_size and _recovery_source since their values can be filtered out in
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/codec/PerFieldFormatSupplier.java]: This comment is off?

**Review by kkrik-es — APPROVED** [review]

**Comment by martijnvg** [comment]
argh but jobs fail with: 

```
* What went wrong:
Execution failed for task ':build-tools:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/opt/buildkite-agent/builds/bk-agent-prod-gcp-1756883074995710979/elastic/elasticsearch-pull-request/build-tools/build/tmp/javadoc/javadoc.options'
```

Not sure why.
