### PR TITLE
Prevent closing wrong search contexts in compute service

### LINKED ISSUE #127188: [CI] DataNodeRequestSenderIT testSearchWhileRelocating failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8212 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/6b4zhgduta3a6)
- [elasticsearch-periodic-platform-support #8212 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/wr63co5k6fxqc)
- [elasticsearch-periodic-platform-support #8212 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/yyfjtqph3lxa4)
- [elasticsearch-periodic #8190 / openjdk23_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/ok6tfloe3itsa)
- [elasticsearch-pull-request #71455 / part-3](https://gradle-enterprise.elastic.co/s/45g7qmekmlbag)
- [elasticsearch-periodic-platform-support #8206 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/snqqljwoz3isg)
- [elasticsearch-periodic #8184 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/c7rtottjdkwhq)
- [elasticsearch-periodic-platform-support #8206 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/fysaq3pxdlqhm)
- [elasticsearch-periodic-platform-support #8206 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/2qkqdeafs65re)
- [elasticsearch-periodic-platform-support #8206 / windows-2019_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/pstif4peicqsy)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderIT.testSearchWhileRelocating" -Dtests.seed=FD00611462CF8FCD -Dtests.locale=vai -Dtests.timezone=America/Asuncion -Druntime.java=24
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSearchWhileRelocating),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a value greater than <3L>
     but: <3L> was equal to <3L>
```

**Issue Reasons:**
- [8.19] 39 failures in test testSearchWhileRelocating (15.4% fail rate in 253 executions)
- [8.19] 5 failures in step rocky-8_platform-support-unix (62.5% fail rate in 8 executions)
- [8.19] 3 failures in step sles-15_platform-support-unix (37.5% fail rate in 8 executions)
- [8.19] 2 failures in step openjdk23_checkpart3_java-matrix (25.0% fail rate in 8 executions)
- [8.19] 2 failures in step debian-11_platform-support-unix (33.3% fail rate in 6 executions)
- [8.19] 2 failures in step rhel-7_platform-support-unix (28.6% fail rate in 7 executions)
- [8.19] 2 failures in step ubuntu-2204_platform-support-unix (33.3% fail rate in 6 executions)
- [8.19] 2 failures in step single-processor-node-tests (33.3% fail rate in 6 executions)
- [8.19] 3 failures in step debian-12_platform-support-unix (50.0% fail rate in 6 executions)
- [8.19] 8 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 8 executions)
- [8.19] 5 failures in pipeline elasticsearch-periodic (62.5% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
The search context variable should be inside the loop, not outside; otherwise, it may close the previous search context when the target shard is unavailable, potentially leaving search contexts without references. This bug was introduced in unreleased versions (9.1 and 8.19). I think we need to refactor DataNodeComputeHandler to allow writing unit tests for these cases easier, but `testSearchWhileRelocating` should cover this issue.

Closes #127188

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeComputeHandler.java [hunk 1]
```diff
@@ -342,15 +342,16 @@ private void acquireSearchContexts(
...
                     } catch (Exception e) {
                         if (addShardLevelFailure(shard.shardId(), e)) {
                             IOUtils.close(context);
+                            continue;
                         } else {
                             IOUtils.closeWhileHandlingException(context, () -> IOUtils.close(searchContexts));
                             throw e;
                         }
                     }
+                    searchContexts.add(context);
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeComputeHandler.java:354]: NIT: I believe it is a bit more readable if context is added in the end of the try block as this emphasizes it is only added when operation is completely successful. Otherwise it looks like a null could be added to a collection sometimes.

**Review by idegtiarenko — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
Very sneaky. I'd have written it inside the loop every time so I super wouldn't see this.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeComputeHandler.java (hunk 1 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeComputeHandler.java]: Sure, I've updated this in https://github.com/elastic/elasticsearch/pull/128222/commits/6a8994700a678330dfa7dfd672d0e2417da81152

**Comment by dnhatn** [comment]
@idegtiarenko @nik9000 Thanks for the discussion and reviews :)
