### PR TITLE
Remove obsolete resolving logic from TRA

### LINKED ISSUE #20279: TRA waits when an index doesn't exist but fails immediately when shard is not found
TransportReplicationAction currently has an inconsistency in how it deals with requests that refer to things that don't exist (which is different than not available).

1) When an index is not found in the cluster state, we go into a retry loop where we wait for the index to appear.
2) When a request comes in for a shard that doesn't exists (i.e., the shard id is higher than the number of shards ) we fail immediately - as it will never appear.

This is surprising and we should fix it.

In my opinion we should:
1) Require ReplicationRequests to have a complete ShardId when they get to the reroute phase in TRA.
2) Fail immediately when that shard id can not be resolved.
3) Change TransportIndexAction and similar write actions to resolve the incoming requests and set their proper shard id (with index uuid). If they need to create the index, they can go ahead, but then it's up to them to also wait until the current (data) node, knows about the index that was just created. We can have a shared utility method for this on `AutoCreateIndex`.

### PR DESCRIPTION
**Pull request by ywelsch**
This stems from a time where index requests were directly forwarded to TransportReplicationAction. Nowadays they are wrapped in a BulkShardRequest, and this logic is obsolete.

In contrast to prior PR (#49647), this PR also fixes (see b3697cc) a situation where the previous index expression logic had an interesting side effect. For bulk requests (which had resolveIndex = false), the reroute phase was waiting for the index to appear in case where it was not present, and for all other replication requests (resolveIndex = true) it would right away throw an IndexNotFoundException while resolving the name and exit. With #49647, every replication request was now waiting for the index to appear, which was problematic when the given index had just been deleted (e.g. deleting a follower index while it's still receiving requests from the leader, where these requests would now wait up to a minute for the index to appear). This PR now adds b3697cc on top of that prior PR to make sure to reestablish some of the prior behavior where the reroute phase waits for the bulk request for the index to appear. That logic was in place to ensure that when an index was created and not all nodes had learned about it yet, that the bulk would not fail somewhere in the reroute phase. This is now only restricted to the situation where the current node has an older cluster state than the one that coordinated the bulk request (which checks that the index is present). This also means that when an index is deleted, we will no longer unnecessarily wait up to the timeout for the index o appear, and instead fail the request.

Closes #20279

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 1]
```diff
@@ -658,23 +641,47 @@ protected void doRun() {
...
+                    // if the wait for active shard count has not been set in the request,
+                    // resolve it from the index settings
+                    request.waitForActiveShards(indexMetaData.getWaitForActiveShards());
+                }
                 assert request.waitForActiveShards() != ActiveShardCount.DEFAULT :
                     "request waitForActiveShards must be set in resolveRequest";
 
                 final ShardRouting primary = primary(state);
-                if (retryIfUnavailable(state, primary)) {
+                if (primary == null || primary.active() == false) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Since you inlined it here you can delete delete `retryIfUnavailable` (or revert the inlining ... though I like it better in-line I think :)).

File: server/src/test/java/org/elasticsearch/action/bulk/BulkIntegrationIT.java [hunk 2]
```diff
@@ -156,4 +165,39 @@ private void createSamplePipeline(String pipelineId) throws IOException, Executi
...
+                }
+            });
+            threads[i].start();
+        }
+        ensureGreen(index);
+        assertBusy(() -> assertThat(docID.get(), greaterThanOrEqualTo(1)));
+        assertAcked(client().admin().indices().prepareDelete(index));
+        stopped.set(true);
+        for (Thread thread : threads) {
+            thread.join(10000); // only wait 10 seconds here
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/action/bulk/BulkIntegrationIT.java]: Maybe just make it `30s` ... 10s for this kind of thing alway seems like it could randomly fail, maybe not as likely anymore but why take the risk? Also, maybe make it relative to `org.elasticsearch.action.support.replication.ReplicationRequest#DEFAULT_TIMEOUT` to make the intent of the test clearer clearer?

**Review by original-brownbear — APPROVED** [review]
Just random cosmetic points, LGTM :)

File: server/src/test/java/org/elasticsearch/action/bulk/BulkIntegrationIT.java [hunk 3]
```diff
@@ -156,4 +165,39 @@ private void createSamplePipeline(String pipelineId) throws IOException, Executi
...
+            if (thread.isAlive()) {
+                throw new IllegalStateException("indexing should have terminated");
```
Comment (dnhatn) [inline server/src/test/java/org/elasticsearch/action/bulk/BulkIntegrationIT.java]: nit: maybe use assertFalse?

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by ywelsch** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix
