### PR TITLE
Re-enable and fix the EsqlRestValidationIT test

### LINKED ISSUE #128543: EsqlRestValidationIT fails
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v8.19.0#oldToNew" -Dtests.class="org.elasticsearch.xpack.esql.ccq.EsqlRestValidationIT" 
```

@smalyshev Can you please take a look? I think this started failing after backporting https://github.com/elastic/elasticsearch/pull/128533. Thanks!

### PR DESCRIPTION
**Pull request by smalyshev**
This test seems to be unintentionally disabled in 9.x branch. 

Fixes https://github.com/elastic/elasticsearch/issues/128543

### CODE REVIEW

File: x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/EsqlRestValidationIT.java [hunk 1]
```diff
@@ -81,8 +81,29 @@ private RestClient remoteClusterClient() throws IOException {
...
+        super.testAlias();
+    }
+
+    @Override
+    public void testExistentIndexWithoutWildcard() throws IOException {
+        assumeFalse("expecting skip_unavailable to be false", isSkipUnavailable());
+        super.testExistentIndexWithoutWildcard();
+    }
+
+    private static boolean checkVersion(Version version) {
```
Comment (dnhatn) [inline x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/EsqlRestValidationIT.java:100]: Can we inline this method? The method name does not match its semantics.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Stas!

File: x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/EsqlRestValidationIT.java (hunk 1 above)
Comment (smalyshev) [reply x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/EsqlRestValidationIT.java:100]: Sure, can do
