### PR TITLE
Fix SearchService.createContext exception handling

### LINKED ISSUE #45378: SearchService.createSearchContext() can leak a searcher
In SearchService.java line 632 we call indexShard.acquireSearcher(), and then pass this searcher to a new DefaultSearchContext which takes ownership.  However, if there is an error when creating this search context, the searcher will never be released.

### PR DESCRIPTION
**Pull request by henningandersen**
An exception from the DefaultSearchContext constructor could leak a
searcher, causing future issues like shard lock obtained failures. The
underlying cause of the exception in the constructor has been fixed, but
as a safety precaution we also fix the exception handling in
createContext.

Closes #45378

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 1]
```diff
@@ -641,6 +642,9 @@ private DefaultSearchContext createSearchContext(ShardSearchRequest request, Tim
         } finally {
             if (success == false) {
                 IOUtils.closeWhileHandlingException(searchContext);
+                if (searchContext == null) {
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: Maybe add a comment here explaining why we're doing this in such a verbose way?

**Review by romseygeek — APPROVED** [review]
Looks good - I think it's worth adding a comment to make sure somebody doesn't come and streamline it in future, but no need for another review.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: ++, done in 2ebfc6cb33434cf0005780348d01089a4376ee77
