### PR TITLE
Wait for relocations during the first mixed round in SnapshotBasedRecoveryIT

### LINKED ISSUE #80939: [CI] SnapshotBasedRecoveryIT testSnapshotBasedRecovery failing
**Build scan**:

https://gradle-enterprise.elastic.co/s/jduqowizzdlzg

**Repro line**:

`gradlew ':qa:rolling-upgrade:v7.16.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.SnapshotBasedRecoveryIT" -Dtests.method="testSnapshotBasedRecovery" -Dtests.seed=3C3FC5FDBBCA3766 -Dtests.bwc=true -Dtests.locale=en-MT -Dtests.timezone=America/Thule -Druntime.java=17`

**Reproduces locally?**:

No

**Applicable branches**:

Master

**Failure history**:

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.upgrades.SnapshotBasedRecoveryIT&tests.sortField=FAILED&tests.test=testSnapshotBasedRecovery&tests.unstableOnly=true

**Failure excerpt**:

```
ava.lang.AssertionError: timed out waiting for green state for index [snapshot_based_recovery] cluster state
...
```

### PR DESCRIPTION
**Pull request by fcofdez**
This commits adds additional logging in order to debug the test failures

Closes #80939

### CODE REVIEW

File: qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/SnapshotBasedRecoveryIT.java [hunk 1]
```diff
@@ -87,6 +90,7 @@ public void testSnapshotBasedRecovery() throws Exception {
                     // That is an issue only for the first mixed round.
                     // In that case we exclude the upgraded node from the shard allocation and cancel the shard to force moving
                     // the primary to a node in the old version, this allows adding replicas in the first mixed round.
+                    logger.info("--> Primary node in first mixed round {} / {}", primaryNodeId, primaryNodeVersion);
```
Comment (fcofdez) [inline qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/SnapshotBasedRecoveryIT.java:93]: I think rebalance can kick in after this check, I'm not sure if there's another way to fix this other than disabling the rebalancing during this test.

**Review by henningandersen — COMMENTED** [review]
I left a comment on another direction, though I could be persuaded to accept the current form too.

File: qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/SnapshotBasedRecoveryIT.java (hunk 1 above)
Comment (fcofdez) [reply qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/SnapshotBasedRecoveryIT.java:89]: > It seems there is some leniency in the excluded node setting above though. I think we could strengthen that instead in following ways:

Yes, that seems to be the case, since the first upgraded node is restarted, meaning that if the primary was located in  that node, the replica is promoted. But it seems like sometimes the primary moves back to the upgraded node. I've pushed the changes that you suggested. Let's see if that helps.

**Review by henningandersen — APPROVED** [review]
LGTM.
