### PR TITLE
SQL: Implement scripting inside aggs

### LINKED ISSUE #29980: SQL: Support Expressions inside Aggregate Functions
*Original comment by @gingerwizard:*

Example:

`SELECT AVG(population/number_of_owner_occupied_units) FROM morgages_mapped WHERE state_abbr = 'CA'`

This should be achievable by a bucket script agg.  This currently fails with:

```
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Does not know how to convert argument Div[] for function Avg[]"
      }
    ],
    "type": "sql_illegal_argument_exception",
    "reason": "Does not know how to convert argument Div[] for function Avg[]"
  },
  "status": 500
}
```
This potentially unlocks a can of worms so its a placeholder only for discussion.

### LINKED ISSUE #36865: SQL: improve aggregations' handling of more complex formulas
At the moment, aggregations/groupings like MAX, AVG, MIN are able to deal with one field as parameter, but things like `AVG((salary + 10)/experience)` are also possible in an AVG aggregation in Elasticsearch through the use of a script.

If one tries to use `AVG` with something more than a simple field as parameter, the following is being returned back:

```
sql> select AVG(salary + 1) from test_emp;                                                                                                                                
Server error [Server encountered an error [Does not know how to convert argument Add[] for function Avg[]]. [SqlIllegalArgumentException[Does not know how to convert argu
ment Add[] for function Avg[]]                                                                                                                                            
        at org.elasticsearch.xpack.sql.planner.QueryTranslator.field(QueryTranslator.java:438)                                                                            
        at org.elasticsearch.xpack.sql.planner.QueryTranslator$Avgs.toAgg(QueryTranslator.java:799)                                                                       
        at org.elasticsearch.xpack.sql.planner.QueryTranslator$Avgs.toAgg(QueryTranslator.java:795)                                                                       
        at org.elasticsearch.xpack.sql.planner.QueryTranslator$SingleValueAggTranslator.asAgg(QueryTranslator.java:883)                                                   
```

In general aggregations cannot be applied on top of any scalar function, another example:
```
SELECT gender AS g, SUM(ABS(emp_no)) AS "sum"
FROM test_emp
GROUP BY 1;
```

This was reported via our forum [here](https://discuss.elastic.co/t/please-help-with-elasticsearch-sql-error-does-not-know-how-to-convert-argument-div-for-function-max/161308).

### LINKED ISSUE #37271: SQL: add support for scripted metrics aggregations
`SELECT MAX(IF(<condition>,<value1>,<value2>)) FROM test` is not currently supported in ES-SQL, but such a query is possible in Elasticsearch through the use of scripts.
For example:

```
{
	"size":0,
    "aggs" : {
        "prices" : {
            "sum" : {
                "script" : {
                    "source": "if (doc['price'].size()>0) {if (doc.decider.value>0) return doc.price.value; else return 0;} else return 0;"
                }
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by matriv**
Implement the use of scalar functions inside aggregate functions.
This allows for complex expressions inside aggregations, with or without
GROUBY as well as with or without a HAVING clause. e.g.:

```
SELECT MAX(CASE WHEN a IS NULL then -1 ELSE abs(a * 10) + 1 END) AS max, b
FROM test
GROUP BY b
HAVING MAX(CASE WHEN a IS NULL then -1 ELSE abs(a * 10) + 1 END) > 5
```

Scalar functions are still not allowed for `KURTOSIS` and `SKEWNESS` as
this is currently not implemented on the Elasticsearch side.

Fixes: #29980
Fixes: #36865
Fixes: #37271

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 1]
```diff
@@ -523,10 +524,19 @@ public QueryTranslation translate(Expression exp, boolean onAggs, TranslatorHand
...
+                }
             } else {
-                return new FilterExistsAgg(id, field(c));
+                ScriptTemplate scriptTemplate = ((Function) c.field()).asScript();
+                if (c.distinct()) {
+                    return new CardinalityAgg(id, scriptTemplate);
+                } else {
+                    return new FilterExistsAgg(id, scriptTemplate);
+                }
             }
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:540]: So this code becomes:
```java
Object argument = asFieldOrLiteralOrScript(c.field());

           if (c.distinct()) {
                    return new CardinalityAgg(id, argument);
                } else {
                    return new FilterExistsAgg(id, argument);
                }
```

**Review by costin — COMMENTED** [review]
Left one comment

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 2]
```diff
@@ -240,15 +236,11 @@ static String nameOf(Expression e) {
...
-        if (e instanceof DateTimeFunction) {
-            return ((DateTimeFunction) e).dateTimeFormat();
-        }
-        return null;
-    }
-
     static String field(AggregateFunction af) {
         Expression arg = af.field();
+        if (arg.foldable()) {
+            return String.valueOf(((Literal) arg).value());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:242]: `String.valueOf(arg.fold())`
There's rarely a reason to cast to a `Literal`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 3]
```diff
@@ -258,23 +250,35 @@ static String field(AggregateFunction af) {
...
+        }
         throw new SqlIllegalArgumentException("Does not know how to convert argument {} for function {}", e.nodeString(), af.nodeString());
     }
 
+    private static boolean isFieldOrLiteral(AggregateFunction af) {
+        return af.field().foldable() || af.field() instanceof FieldAttribute;
+    }
+
+    private static Object getFieldOrLiteralOrScript(AggregateFunction af) {
+        if (isFieldOrLiteral(af)) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:275]: `return  isFieldOrLiteral(af) ?  field(af) : ((ScalarFunction) af.field()).asScript()`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 4]
```diff
@@ -258,23 +250,35 @@ static String field(AggregateFunction af) {
...
+            return ((ScalarFunction) e).asScript();
+        }
         throw new SqlIllegalArgumentException("Does not know how to convert argument {} for function {}", e.nodeString(), af.nodeString());
     }
 
+    private static boolean isFieldOrLiteral(AggregateFunction af) {
+        return af.field().foldable() || af.field() instanceof FieldAttribute;
+    }
+
+    private static Object getFieldOrLiteralOrScript(AggregateFunction af) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:274]: get prefix is for getter - use something like `toField..` or `asField..`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 5]
```diff
@@ -258,23 +250,35 @@ static String field(AggregateFunction af) {
...
         }
-        if (arg instanceof Literal) {
-            return String.valueOf(((Literal) arg).value());
-        }
         throw new SqlIllegalArgumentException("Does not know how to convert argument {} for function {}", arg.nodeString(),
                                               af.nodeString());
     }
 
-    private static String topAggsField(AggregateFunction af, Expression e) {
+    private static Object topAggsFieldOrScript(AggregateFunction af, Expression e) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:257]: This can be moved under the TopHit agg class

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 3 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:275]: The logic from `topAggsFieldOrScript` and this method is similar and should be reused - I like the instanceof check for Scalar instead of the direct cast; a bit verbose but safe.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java [hunk 6]
```diff
@@ -17,10 +20,19 @@
 
     private final String id;
     private final String fieldName;
+    private final ScriptTemplate scriptTemplate;
 
-    Agg(String id, String fieldName) {
+    Agg(String id, Object fieldOrScript) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java:25]: Thinking a bit more about this, a better solution might be creating a simple DTO specific for Agg that can hold either a String or a ScriptTemplate.
That one would handle the hashCode, equals, etc.
Further more maybe extend it to accept behavior by accepting a `ValuesSourceAggregationBuilder` and internally call either `field` or `script` based on its content.
```suggestion
    Agg(String id, AggTarget target) {
       this.target = target;
    }
    ...
    class AggTarget {
        private final String fieldName;
        private final ScriptTemplate script;
        
        ...
        
        ValuesSourceAggregationBuilder with(ValuesSourceAggregationBuilder aggBuilder) {
            if (field != null) {
                 aggBuilder.field(field);
             }
             else {
                 aggBuilder.script(scriptTemplate.asScript());
              }
        }
    }
```

This would improve `LeafAgg` which would improve `toBuilder` and call `AggTarget` so that subclasses would only have to create the `ValueSourceAggregationBuilder`. In fact we could just declare them as a method reference for a string:

```java
public abstract class LeafAgg extends Agg {

    LeafAgg(String id, AggTarget target) {
        super(id, target);
    }

    ValuesSourceAggregationBuilder builder() {
         return aggBuilder.apply(id()).with(aggTarget);
    }

    protected abstract Function<String, ValuesSourceAggregationBuilder> aggBuilder();
```

so that subclasses would now look like:
```java

public class CardinalityAgg extends LeafAgg {

    public CardinalityAgg(String id, AggTarget aggTarget) {
        super(id, aggTarget);
    }

    @Override
    ValuesSourceAggregationBuilder aggBuilder() {
        return AggregationBuilders::cardinality;
    }
}
```

**Review by costin — APPROVED** [review]
Looks good.
Left some comments regarding testing and potentially improvements in the agg hierarchy- if they are unclear, we can address that through a different PR.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec [hunk 7]
```diff
@@ -899,3 +899,156 @@ SELECT gender, MAD(salary) AS mad FROM test_emp GROUP BY gender HAVING mad > 100
 null           |10789.0        
 F              |12719.0         
 ;
+
+
+// aggregates with scalars
+aggregateFunctionsWithScalars
```
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec:905]: > Can you please add a couple of tests where the aggs with scalars are inside having?
There is already: https://github.com/elastic/elasticsearch/pull/55241/files/b8bc29f350f24b22bde8b9096a95d4273dd822fe#diff-002044c6b4e1de5a6960847971f85532R986

> Even better have scalars over aggs over scalars inside Having.
I will one with scalars also on top of the agg function.

> Also another that sorts by an aggregation with an internal scalar.
I have already: https://github.com/elastic/elasticsearch/pull/55241/files/b8bc29f350f24b22bde8b9096a95d4273dd822fe#diff-002044c6b4e1de5a6960847971f85532R960

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 5 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:257]: Consolidated into one method.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec (hunk 7 above)
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec:905]: >I have already:
I was thinking of a test with the agg declared just inside the order and not referencing an already declared aggregation.

**Review by costin — APPROVED** [review]

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java (hunk 6 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java]: Thx @costin, It's cleaner this way!

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java [hunk 8]
```diff
@@ -19,37 +16,25 @@
...
-    public ScriptTemplate scriptTemplate() {
-        return scriptTemplate;
+    public AggTarget target() {
+        return target;
     }
 
     @Override
     public int hashCode() {
-        return Objects.hash(id, fieldName, scriptTemplate);
+        return Objects.hash(id) + target.hashCode();
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java:37]: `Objects.hash(id, target)`

**Review by costin — APPROVED** [review]
👍

File: docs/reference/sql/functions/aggs.asciidoc [hunk 9]
```diff
@@ -397,6 +397,16 @@ https://en.wikipedia.org/wiki/Kurtosis[Quantify] the shape of the distribution o
 include-tagged::{sql-specs}/docs/docs.csv-spec[aggKurtosis]
 --------------------------------------------------
 
+[NOTE]
+====
+`KURTOSIS` cannot be used on top of scalar functions but only directly on a field. So, for example, the following is
+not allowed and an error is returned:
+[source, sql]
+---------------------------------------
+ SELECT KURTOSIS(salary), gender FROM emp GROUP BY gender
```
Comment (astefan) [inline docs/reference/sql/functions/aggs.asciidoc:406]: Reading the NOTE I would have expected to see "KURTOSIS ... on top of scalar functions" but I'm seeing KURTOSIS applied on a field.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/LeafAgg.java [hunk 10]
```diff
@@ -6,12 +6,18 @@
...
-    LeafAgg(String id, String fieldName) {
-        super(id, fieldName);
+    LeafAgg(String id, AggTarget target) {
+        super(id, target);
     }
 
     abstract AggregationBuilder toBuilder();
+
+    @SuppressWarnings("rawtypes")
+    protected ValuesSourceAggregationBuilder addFieldOrScript(ValuesSourceAggregationBuilder builder) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/LeafAgg.java:20]: The name is leaking implementation details - why not `addTarget()`?

**Review by costin — APPROVED** [review]
`AggSource` conveys better the intent than `AggTarget`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/LeafAgg.java (hunk 10 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/LeafAgg.java:20]: Yep, forgot to rename that, thx.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec [hunk 11]
```diff
@@ -899,3 +899,196 @@ SELECT gender, MAD(salary) AS mad FROM test_emp GROUP BY gender HAVING mad > 100
...
+       max        |    gender
+------------------+---------------
+155409.30000000002|F
+151745.40000000002|M
+132335.1          |null
+;
+
+aggregatesWithScalarsAndGroupByOrderByAggWithoutProjection
+schema::gender:s
+SELECT gender FROM test_emp GROUP BY gender ORDER BY MAX(salary % 100) DESC;
```
Comment (astefan) [inline x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec:975]: Please, add `MAX(salary % 100)` to the result.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec [hunk 12]
```diff
@@ -899,3 +899,196 @@ SELECT gender, MAD(salary) AS mad FROM test_emp GROUP BY gender HAVING mad > 100
...
+VAR_POP(CASE WHEN (salary - 20) % 1000 > 200 THEN (salary * 1.2) - 1234 ELSE (salary - 20) * 0.93 END) AS "var_pop",
+gender FROM test_emp
+GROUP BY gender ORDER BY gender;
+
+    stddev_pop    |   sum_of_squares    |      var_pop       |    gender
+------------------+---------------------+--------------------+---------------
+18601.965319409886|3.4461553130896095E10|3.460331137445282E8 |null
+17811.071545718776|1.2151168881502939E11|3.1723426960671306E8|F
+15904.093950318531|1.699198993070239E11 |2.529402043805585E8 |M
+;
```
Comment (astefan) [inline x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec:1094]: I like the complexities of these tests, but the queries are too complex for me to assess that the example is relevant :-). I trust that you checked the numbers against the data and made sure everything is ok.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 13]
```diff
@@ -535,104 +528,122 @@ protected LeafAgg toAgg(String id, Count c) {
...
     static class MatrixStatsAggs extends CompoundAggTranslator<MatrixStats> {
 
         @Override
         protected LeafAgg toAgg(String id, MatrixStats m) {
-            return new MatrixStatsAgg(id, singletonList(field(m)));
+            if (isFieldOrLiteral(m.field())) {
+                return new MatrixStatsAgg(id, singletonList(field(m, m.field())));
+            }
+            throw new SqlIllegalArgumentException(
+                "Cannot use scalar functions or operators: [{}] in matrix stats " + "aggregate functions [KURTOSIS] and [SKEWNESS]",
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:620]: Can this error message be improved?
- why is it mentioning matrix stats, isn't this an implementation detail?
- not a biggie and can be left as is, but can the message be more targeted to the exact aggregate function? (mention only KURTOSIS or SKEWNESS)

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java [hunk 14]
```diff
@@ -16,24 +16,25 @@
...
 
     private final String id;
-    private final String fieldName;
+    private final AggTarget target;
 
-    Agg(String id, String fieldName) {
+    Agg(String id, AggTarget target) {
         this.id = id;
-        this.fieldName = fieldName;
+        Objects.requireNonNull(target, "AggTarget must not be null");
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Agg.java:23]: You could move this call as the first in the constructor, no?

**Review by astefan — APPROVED** [review]
LGTM. This PR will make a lot of users happy.
Left few minor comments.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec (hunk 11 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec:975]: This is a special case, requested by @costin, ORDER BY without having it in the projection.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec (hunk 12 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec:1094]: I've tested all the queries against PostgreSQL and the results are not always the same but very similar (double-rounding diffs).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 13 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java:620]: > * why is it mentioning matrix stats, isn't this an implementation detail?

Yep, I can remove that.

> * not a biggie and can be left as is, but can the message be more targeted to the exact aggregate function? (mention only KURTOSIS or SKEWNESS)

Not really, I've tried it,  because we don't have the original function anymore here, only `MatrixStats`. I was considering checking that earlier on the functions themselves, but then `resolveType()` didn't seem to me a good place to add such a verification, since it's regarding the DataType and not if the arg is field or function.

File: docs/reference/sql/functions/aggs.asciidoc [hunk 15]
```diff
@@ -397,6 +397,16 @@ https://en.wikipedia.org/wiki/Kurtosis[Quantify] the shape of the distribution o
 include-tagged::{sql-specs}/docs/docs.csv-spec[aggKurtosis]
```
Comment (costin) [inline docs/reference/sql/functions/aggs.asciidoc:397]: I think it's worth adding examples in the docs (either a dedicated one or for most aggregations) that shows aggregations alongside a scalar function as it might not be obvious, especially for existing users.

This would also address @astefan point of having a test that can be easily be verified.

**Review by bpintea — APPROVED** [review]
Looks great!

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 13 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: This is better handled in the verifier by checking that `Kurtosis` & co (namely `MatrixStatsEnclosed`) don't have a scalar expression as argument.
Further more I would add an issue to extend the aggregation to support scripts not just fields.

Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: Created issue: #55344
