### PR TITLE
Don't allow nodes with missing custom meta data to join cluster

### LINKED ISSUE #13445: Better logging for when license plugin is missing from a node
Because the license plugin updates the cluster state, any node without the license plugin fails to join the cluster. However because the default logging is INFO the messages about failing to join the cluster state don't show up on either the master node or the node without the license. On the client node which was trying to join all I saw was after setting discovery to TRACE:

[2015-09-09 16:43:36,224][DEBUG][discovery.zen ] [phl-head-03] no master node is set, despite of join request completing. retrying pings.

There should be more information logged at INFO without having to enable DEBUG logging at both the master and the node which fails to join the cluster due to the missing license plugin. This was on Elasticsearch 1.7.1.

### PR DESCRIPTION
**Pull request by areek**
Currently, when some nodes in a cluster are missing plugins with custom metadata, the nodes silently fail while trying to deserialize the unknown custom metadata on the first cluster state update. Ideally, the node should fail hard and make it obvious why it failed. 

This PR treats node with missing custom metadata same as a node with version incompatibility. When a node with missing custom metadata tries to join a cluster, the master detects it and the node fails to join the cluster. 

closes #13445

### CODE REVIEW

**Comment by areek** [comment]
would like to know your thoughts on this, @imotov & @bleskes.

File: core/src/main/java/org/elasticsearch/cluster/service/InternalClusterService.java [hunk 1]
```diff
@@ -189,6 +189,13 @@ public DiscoveryNode localNode() {
     }
 
     @Override
+    public List<String> localCustomMetaDataTypes() {
+        List<String> customMetaDataList = new ArrayList<>(MetaData.customPrototypes.keySet());
```
Comment (areek) [inline core/src/main/java/org/elasticsearch/cluster/service/InternalClusterService.java]: Any better way to grab registered custom metadata than this?

Comment (imotov) [inline core/src/main/java/org/elasticsearch/cluster/service/InternalClusterService.java]: I think relying on order of elements in the list is brittle. I think representing this list as a set might be a more reliable solution.

**Comment by imotov** [comment]
Custom data types can be added on three levels - cluster state level, metadata level and index metadata level. This PR only handles metadata level. I think we should handle all three level

**Comment by areek** [comment]
Thanks for having a look, @imotov! I updated the PR to use the node join validation request (thanks @bleskes for the tip!) to attempt to  deserialize master's cluster state. Now, if the joining node has missing custom data types on any level, the deserialization will fail. The join failure is logged as an ISE hinting missing plugins on the joining node.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 2]
```diff
@@ -824,8 +824,7 @@ public static void validateStateIsFromCurrentMaster(ESLogger logger, DiscoveryNo
         }
     }
 
-    void handleJoinRequest(final DiscoveryNode node, final MembershipAction.JoinCallback callback) {
-
+    void handleJoinRequest(final DiscoveryNode node, final ClusterState state, final MembershipAction.JoinCallback callback) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: why can't we sample the state here - no need for the extra param, right?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 3]
```diff
@@ -847,7 +846,12 @@ void handleJoinRequest(final DiscoveryNode node, final MembershipAction.JoinCall
 
             // validate the join request, will throw a failure if it fails, which will get back to the
             // node calling the join request
-            membership.sendValidateJoinRequestBlocking(node, joinTimeout);
+            try {
+                membership.sendValidateJoinRequestBlocking(node, state, joinTimeout);
+            } catch (Throwable e) {
+                callback.onFailure(new IllegalStateException("Can't handle join request from node [" + node + "], probable cause missing plugins", ExceptionsHelper.unwrapCause(e)));
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: can we change the message to what it is? "failure why sending a validation request to node" . The plugin part can better go in the type resolution (i.e., lookupPrototypeSafe ) ?

Comment (areek) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I changed the message as suggested in https://github.com/areek/elasticsearch/commit/3cc23f001c9345f666740b2deacb5033cf7b9a58

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 2 above)
Comment (areek) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: We can but passing the cluster state as param makes this easily testable. Initially, I tried writing a test with two nodes, one having a custom plugin and another none, but the testing framework makes it tricky. any ideas on how to test this functionality, if we just sample the state instead of passing it as a param?

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: oh. sorry. I'm missed the usage in the test. All good.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 4]
```diff
@@ -847,7 +846,12 @@ void handleJoinRequest(final DiscoveryNode node, final MembershipAction.JoinCall
 
             // validate the join request, will throw a failure if it fails, which will get back to the
             // node calling the join request
-            membership.sendValidateJoinRequestBlocking(node, joinTimeout);
+            try {
+                membership.sendValidateJoinRequestBlocking(node, state, joinTimeout);
+            } catch (Throwable e) {
+                callback.onFailure(new IllegalStateException("failure when sending a validation request to node", ExceptionsHelper.unwrapCause(e)));
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: why do we need to unwrap the cause?

File: core/src/main/java/org/elasticsearch/cluster/ClusterState.java [hunk 5]
```diff
@@ -129,7 +129,7 @@ public static void registerPrototype(String type, Custom proto) {
         @SuppressWarnings("unchecked")
         T proto = (T)customPrototypes.get(type);
         if (proto == null) {
-            throw new IllegalArgumentException("No custom state prototype registered for type [" + type + "]");
+            throw new IllegalArgumentException("No custom state prototype registered for type [" + type + "], probable cause missing plugins");
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/ClusterState.java]: you're the english master - but "probable cause missing plugins" ?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 4 above)
Comment (areek) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Now we use the original cause

File: core/src/main/java/org/elasticsearch/cluster/ClusterState.java (hunk 5 above)
Comment (areek) [inline core/src/main/java/org/elasticsearch/cluster/ClusterState.java]: changed it to "node likely missing plugins"

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 6]
```diff
@@ -847,7 +846,12 @@ void handleJoinRequest(final DiscoveryNode node, final MembershipAction.JoinCall
 
             // validate the join request, will throw a failure if it fails, which will get back to the
             // node calling the join request
-            membership.sendValidateJoinRequestBlocking(node, joinTimeout);
+            try {
+                membership.sendValidateJoinRequestBlocking(node, state, joinTimeout);
+            } catch (Throwable e) {
+                callback.onFailure(new IllegalStateException("failure when sending a validation request to node", e));
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: can we log a warn here - "failed to validate incoming join request from node [{}]" ? I think this should be visible.

**Comment by bleskes** [comment]
LGTM. Left one minor request but no need for another review. Also, I think this can go into 2.2, no?

**Comment by areek** [comment]
Thanks @bleskes for the review, back ported to 2.x in https://github.com/elastic/elasticsearch/commit/8ab3ca8a87310ca0e60da16f80680748d273ee5a
