### PR TITLE
EQL: Change default indices options

### LINKED ISSUE #62986: EQL: `allow_no_indices` behavior
Currently EQL requires at least one index to match in order to validate the query. However just like [search](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-search.html#search-search-api-query-params), the `allow_no_indices` option is permitted which leads to confusing behavior since it can be true, yet EQL will throw an exception:
```
### A 

GET foo*/_search
# success

GET foo*/_eql/search
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo*]",


### B

GET foo/_search?ignore_unavailable=true
# success

GET foo/_eql/search?ignore_unavailable=true
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "index_not_found_exception",
# "reason" : "no such index [[foo]]",


### C 

GET foo/_search
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo]",

GET foo/_eql/search
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "mapping_exception",
# "reason" : "Unknown index [foo]",

### D 

GET foo*/_search?allow_no_indices=false
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo*]",

GET foo*/_eql/search?allow_no_indices=false
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo*]",

GET foo*/_eql/search?allow_no_indices=true
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "mapping_exception",
# "reason" : "Unknown index [*,-*]"
```

Considering the similarities to the search API, EQL should either provide a similar behavior or not accept this parameter.

### PR DESCRIPTION
**Pull request by costin**
Ignore by default unavailable indices (same as ES) and verify that
allowNoIndices is set to false since at least one index is required
for validating the query.

Fix #62986

### CODE REVIEW

File: x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java [hunk 1]
```diff
@@ -89,8 +89,8 @@ private void testCase(String user, String other) throws Exception {
         }
         ResponseException exc = expectThrows(ResponseException.class,
             () -> submitAsyncEqlSearch("index-" + other, "*", TimeValue.timeValueSeconds(10), user));
-        assertThat(exc.getResponse().getStatusLine().getStatusCode(), equalTo(403));
-        assertThat(exc.getMessage(), containsString("unauthorized"));
+        assertThat(exc.getResponse().getStatusLine().getStatusCode(), equalTo(404));
+        //assertThat(exc.getMessage(), containsString("unauthorized"));
```
Comment (costin) [inline x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java:93]: @imotov not sure why this fails now... Essentially by changing the index option `ignoreUnavailable` from `false` to `true` the 403/unauthorized became a 404...

**Review by matriv — COMMENTED** [review]
So this means that if you only include non existing indices we don't fail?
Can we have a test for that?

**Review by astefan — COMMENTED** [review]
I think you need to make the same change in rest high level client corresponding EqlSearchRequest class.

File: x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java (hunk 1 above)
Comment (imotov) [reply x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java:93]: I think it is because we ignore unavailable indices and ended up with no indices at all, which leads to 404.

File: x-pack/plugin/eql/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/eql/10_basic.yml [hunk 2]
```diff
@@ -83,6 +83,20 @@ setup:
   - match: {hits.sequences.1.events.0._id: "2"}
   - match: {hits.sequences.1.events.1._id: "3"}
 
+---
+"Execute EQL sequence by default ignores unavailable indices"
```
Comment (imotov) [inline x-pack/plugin/eql/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/eql/10_basic.yml:87]: missing `:` at the end

File: x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java:93]: And previously we did not ignore them but because we couldn't get access to them to verify their existence we got the 403...Make sense.

File: client/rest-high-level/src/main/java/org/elasticsearch/client/eql/EqlSearchRequest.java [hunk 3]
```diff
@@ -34,7 +34,7 @@
 public class EqlSearchRequest implements Validatable, ToXContentObject {
 
     private String[] indices;
-    private IndicesOptions indicesOptions = IndicesOptions.fromOptions(false, false, true, false);
+    private IndicesOptions indicesOptions = IndicesOptions.fromOptions(true, false, true, false);
```
Comment (costin) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/eql/EqlSearchRequest.java:37]: @astefan the change inside EQL high-level rest client.

File: x-pack/plugin/eql/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/eql/10_basic.yml [hunk 4]
```diff
@@ -83,6 +83,20 @@ setup:
...
+  - do:
+      eql.search:
+        index: eql_test,non_existing
```
Comment (costin) [inline x-pack/plugin/eql/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/eql/10_basic.yml:90]: @matriv the integration test against non-existing indices

**Review by bpintea — APPROVED** [review]
lgtm

File: x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java (hunk 1 above)
Comment (matriv) [inline x-pack/plugin/eql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/eql/AsyncEqlSecurityIT.java:93]: Should we remove it then?

File: x-pack/plugin/eql/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/eql/10_basic.yml (hunk 4 above)
Comment (matriv) [reply x-pack/plugin/eql/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/eql/10_basic.yml:90]: I meant to query against only unavailable indices, just for completeness.

**Review by matriv — APPROVED** [review]
LGTM, left 2 comments.

**Review by astefan — APPROVED** [review]
LGTM
