### PR TITLE
Prevent concurrent access to local breaker in rerank

### LINKED ISSUE #127051: [CI] EsqlSpecIT test {rerank.Reranker before a limit ASYNC} failing
**Build Scans:**
- [elasticsearch-intake #22059 / part3](https://gradle-enterprise.elastic.co/s/ofxz7mtzvpbni)
- [elasticsearch-pull-request #67937 / part-3](https://gradle-enterprise.elastic.co/s/23zzz56yr7hwe)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker before a limit ASYNC}" -Dtests.seed=326C64CD068ECB8 -Dtests.locale=uz-Cyrl -Dtests.timezone=Europe/Bratislava -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20before%20a%20limit%20ASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.net.ConnectException: Connection refused
```

**Issue Reasons:**
- [main] 2 failures in test test {rerank.Reranker before a limit ASYNC} (0.3% fail rate in 618 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #127638: [CI] EsqlSpecIT test {rerank.Reranker using another sort order ASYNC} failing
**Build Scans:**
- [elasticsearch-intake #22558 / part3](https://gradle-enterprise.elastic.co/s/sjbbvkqmnkhxc)
- [elasticsearch-pull-request #70081 / part-3](https://gradle-enterprise.elastic.co/s/f2uqh3hh7qkli)
- [elasticsearch-pull-request #70060 / part-3](https://gradle-enterprise.elastic.co/s/nvygs56uaqmfm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker using another sort order ASYNC}" -Dtests.seed=188EE70F617AA567 -Dtests.locale=pcm -Dtests.timezone=Asia/Muscat -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20using%20another%20sort%20order%20ASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:38591], URI [/_query/async/FmFyV1hDX1JiUXI2d2hUNTl4NWRqbkEcSzZGMkJoNHlTQjJYUGFDcXBqY21qZzo3MjMxMQ==?pretty=true&error_trace=true], status line [HTTP/1.1 502 Bad Gateway]
{
  "error" : {
    "root_cause" : [
      {
        "type" : "node_disconnected_exception",
        "reason" : "[test-cluster-0][127.0.0.1:36449][indices:data/read/async_search/delete] disconnected",
        "stack_trace" : "org.elasticsearch.transport.NodeDisconnectedException: [test-cluster-0][127.0.0.1:36449][indices:data/read/async_search/delete] disconnected\n"
      }
    ],
    "type" : "node_disconnected_exception",
    "reason" : "[test-cluster-0][127.0.0.1:36449][indices:data/read/async_search/delete] disconnected",
    "stack_trace" : "org.elasticsearch.transport.NodeDisconnectedException: [test-cluster-0][127.0.0.1:36449][indices:data/read/async_search/delete] disconnected\n"
  },
  "status" : 502
}

```

**Issue Reasons:**
- [main] 3 failures in test test {rerank.Reranker using another sort order ASYNC} (1.2% fail rate in 249 executions)
- [main] 2 failures in step part-3 (2.1% fail rate in 94 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.2% fail rate in 93 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
When an async operator receives a response, we can't create new blocks on the responding thread because multiple threads may adjust the local breaker simultaneously, leading to a data race. To address this, we can either use the global breaker or delay block creation in getOutput. While using the global block factory is simpler, I prefer the second option to use the local breaker when possible. Therefore, I opted to keep the results in the queue and create new blocks in getOutput. Our tests didn't catch this issue because: (1) only one block is created in the test, and (2) there is no delay when simulating the inference service.

Closes #127638
Closes #127051

### CODE REVIEW

**Review by ivancea — APPROVED** [review]
LGTM 👀

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java [hunk 1]
```diff
@@ -77,6 +79,19 @@ public final void testSimpleLargeInput() {
...
     }
 
+    /**
+     * Test with a local breaker
+     */
+    public final void testWithLocalBreaker() {
+        BlockFactory blockFactory = blockFactory();
+        final int overReservedBytes = between(0, 1024 * 1024);
+        final int maxOverReservedBytes = between(overReservedBytes, 1024 * 1024);
+        var localBreaker = new LocalCircuitBreaker(blockFactory.breaker(), overReservedBytes, maxOverReservedBytes);
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java:89]: Should we wrap this in something that `assert`s that we're on the same thread every time?

Comment (dnhatn) [reply x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java]: ++ I pushed https://github.com/elastic/elasticsearch/pull/128162/commits/ce545830587ed9623878ec2c502ab6cffa7425e7.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/inference/RerankOperator.java [hunk 2]
```diff
@@ -85,20 +86,16 @@ public RerankOperator(
...
-
+        listener = listener.delegateResponse((l, e) -> {
+            releasePageOnAnyThread(inputPage);
+            l.onFailure(e);
+        });
         try {
-            inferenceRunner.doInference(
-                buildInferenceRequest(inputPage),
-                ActionListener.wrap(
-                    inferenceResponse -> outputListener.onResponse(buildOutput(inputPage, inferenceResponse)),
```
[the remark this answers is not in the document]
Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/inference/RerankOperator.java:96]: - We use the global breaker not local breaker for reading blocks from an input stream.
- I have added assertions in https://github.com/elastic/elasticsearch/commit/ce545830587ed9623878ec2c502ab6cffa7425e7, which should consistently detect such misuse.
