### PR TITLE
Unit test for very large percentile aggs

### LINKED ISSUE #19528: percentiles aggregation return anomaly value when hits too large
**Elasticsearch version**:
1.7.3
**JVM version**:
1.7
**OS version**:
CentOS6.5
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.ingest more than 3 billon event into the index.
 2.send a percentiles aggregation for those event
 3.retry the query for severy times

**Provide logs (if relevant)**:
the right result:
image
and the error result:
image

### PR DESCRIPTION
**Pull request by not-napoleon**
This ports in a unit test for #19528 (which is really just the unit test @colings86 submitted to the upstream library last year, retouched for our randomized testing framework).  As far as I can tell, this issue has been fixed since we migrated to t-digest 3.2, and this test should just pass.  My recommendation is to include the test in our suite for regression testing, and close #19528

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateTests.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+            digest.add(randomDouble(), count);
+        }
+        assertEquals(1000 + 10L * (1 << 29), digest.size());
+        assertTrue(digest.size() > 2 * Integer.MAX_VALUE);
+        final double[] quantiles = new double[] { 0, 0.1, 0.5, 0.9, 1, randomDouble()};
+        Arrays.sort(quantiles);
+        double prev = Double.NEGATIVE_INFINITY;
+        for (double q : quantiles) {
+            final double v = digest.quantile(q);
+            System.out.println("q=" + q + ", v=" + v);
```
Comment (polyfractal) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateTests.java]: Probably better to use a logger instead of printing directly to console.  Logged under `debug` or `trace` I would guess?

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateTests.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
+package org.elasticsearch.search.aggregations.metrics;
+
+import org.elasticsearch.test.ESTestCase;
+import org.junit.Test;
+
+import java.util.Arrays;
+
+public class TDigestStateTests extends ESTestCase {
+    @Test
```
Comment (polyfractal) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateTests.java]: Doesn't really matter, but I don't think you need the test annotation here.  I believe our tests are setup to just run anything that starts with `"test"`.  (Looks like this is just a carry-over from how the TDigest library tests things)

**Review by polyfractal — APPROVED** [review]
Left a few style comments but otherwise LGTM!  

I didn't really review the actual test logic since it's a port and I'm assuming Colin knew what he was doing at the time :)
