### PR TITLE
Fix ReloadingDatabasesWhilePerformingGeoLookupsIT

### LINKED ISSUE #69980: [CI] ReloadingDatabasesWhilePerformingGeoLookupsIT#test() failure
**Build scan**: https://gradle-enterprise.elastic.co/s/3wd2py7tycbjm

**Repro line**: `./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test" -Dtests.seed=1327A9992993281D -Dtests.security.manager=true -Dtests.locale=es-GT -Dtests.timezone=Indian/Chagos -Druntime.java=11`

**Reproduces locally?**: Yes (when running with `-Dtests.iters=1024`, the test seed is irrelevant, it is a timing issue)

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT&tests.sortField=FAILED&tests.test=test&tests.unstableOnly=true

**Failure excerpt**: 

```

java.lang.AssertionError: |  
-- | --
  | Expected: null |  
  | but: was <java.lang.AssertionError> |  

  |   | at __randomizedtesting.SeedInfo.seed([1327A9992993281D:9B739643876F45E5]:0) |  
-- | -- | -- | --
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.ingest.geoip.ReloadingDatabasesWhilePerformingGeoLookupsIT.test(ReloadingDatabasesWhilePerformingGeoLookupsIT.java:142)


```

### PR DESCRIPTION
**Pull request by martijnvg**
Wait for ingest threads to stop using the DatabaseReaderLazyLoader, so the during the next run the db update thread doesn't try to remove the db again (because the file hasn't yet been deleted).

Also delete tmp dirs this test create at the end of the test, so that when repeating this test many times, this test doesn't accumulate many directories with database files.

Closes #69980

### CODE REVIEW

File: modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/ReloadingDatabasesWhilePerformingGeoLookupsIT.java [hunk 1]
```diff
@@ -146,13 +158,14 @@ public void test() throws Exception {
         for (DatabaseReaderLazyLoader lazyLoader : databaseRegistry.getAllDatabases()) {
             assertThat(lazyLoader.current(), equalTo(0));
         }
+        // Avoid accumulating many temp dirs while running with -Dtests.iters=X
+        IOUtils.rm(geoIpModulesDir, geoIpConfigDir, geoIpTmpDir);
```
Comment (probakowski) [inline modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/ReloadingDatabasesWhilePerformingGeoLookupsIT.java:162]: +100 for that, I clogged up my disk running this test with `tests.iters`

**Review by probakowski — APPROVED** [review]
LGTM, thanks @martijnvg for fixing this

File: modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/ReloadingDatabasesWhilePerformingGeoLookupsIT.java (hunk 1 above)
Comment (martijnvg) [reply modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/ReloadingDatabasesWhilePerformingGeoLookupsIT.java:162]: same here :)
