### PR TITLE
[ML] handle broken setup with state alias being an index

### LINKED ISSUE #58482: [ML] Job fail to start with "Invalid alias name [.ml-state-write] ..."
**Affected version**: 7.7 -

**Problem**

`.ml-state-write` is supposed to be an index alias, however by accident it can become an index. If `.ml-state-write` is a concrete index instead of an alias, starting a job can fail due to index rollover introduced in #52356.

The reason for `.ml-state-write` being an index instead of an alias is explained in #57645

**Mitigation**

- if you are ok with re-creating ML models you can delete `.ml-state-write`
- if you want to preserve state:
	- reindex `.ml-state-write` to `.ml-state`:

```
#---
# reindex
# - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html
#---
POST _reindex
{
"source": {
"index": ".ml-state-write",
"size": 100
},
"dest": {
"index": ".ml-state"
}
}
```

After the _successful_ reindex, delete the old index and create an alias:

```
#---
# delete .ml-state-write
#---
DELETE /.ml-state-write
#---
# create alias
# - https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html
#---
POST /_aliases
{
"actions" : [
{ "add" : { "index" : ".ml-state", "alias" : ".ml-state-write" } }
]
}
```

Now you should be able to start the jobs.

**Solution**

The issues #57645 and #55267 discuss solutions for preventing the `.ml-state-write` index. This will solve the root cause of this issue.

For users that have an `.ml-state-write` index by mistake, this won't help. Because reindex is an expensive operation it's _not_ an option to reindex in the back.

2 possible improvements I can think of:

**A: improve log message**

The log message isn't very descriptive and does not help for finding a solution quickly. We can improve the message (concrete wording to be discussed): "Expected [.ml-state-write] to be an alias but it is an index, can't start the job. Please reindex [.ml-state-write] to [.ml-state]". It's not possible to write full instructions in a log message, but given the message is part of this, users should find this.

~**B: do not use ILM if ml-state-write is an index**~

~We could be lenient and simply fall back to the old non-ILM way. We added ILM for a reason, that's why this solution is questionable, however, we talk about `7.x`. For upgrading to `8.0` we can require using an update tool and reindex as part of migrating to `8`, so eventually the state index will be managed. This solution requires that a `.ml-state-write` index does not cause problems in other parts of the code.~

### PR DESCRIPTION
**Pull request by hendrikmuhs**
.ml-state-write is supposed to be an index alias, however by accident it can become an index. If 
.ml-state-write is a concrete index instead of an alias ML stops working. This change improves error
handling by setting the job to failed and properly log and audit the problem. The user still has to
manually fix the problem. This change should lead to a quicker resolution of the problem.

fixes #58482

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
**Before**

Opening a job took "forever" in the UI and seems to be stuck. The log contains some low-level error message:

```
[2020-07-03T11:36:22,878][WARN ][o.e.p.AllocatedPersistentTask] [hendrik-p1] task job-url_scanning failed with an exception
org.elasticsearch.indices.InvalidAliasNameException: Invalid alias name [.ml-state-write], an index exists with the same name as the alias
```

Note, the log might not be easily retrievable for a user.

**After**

image

image

Log example:

```
[2020-07-03T11:36:22,845][ERROR][o.e.x.m.j.p.a.AutodetectProcessManager] [hendrik-p1] [url_scanning] Detected a problem with your setup of machine learning, the state index alias [.ml-state-write] exists as index but must be an alias.
org.elasticsearch.indices.InvalidAliasNameException: Invalid alias name [.ml-state-write], an index exists with the same name as the alias
        at org.elasticsearch.cluster.metadata.AliasValidator.validateAlias(AliasValidator.java:93) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.MetadataIndexAliasesService.lambda$applyAliasActions$2(MetadataIndexAliasesService.java:137) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.AliasAction$Add.apply(AliasAction.java:130) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at 
...
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java [hunk 1]
```diff
@@ -426,7 +427,19 @@ protected void doRun() {
                     e -> closeHandler.accept(e, true)
                 ));
             },
-            e -> closeHandler.accept(e, true));
+            e -> {
+                if (ExceptionsHelper.unwrapCause(e) instanceof InvalidAliasNameException) {
+                    String msg = "Detected a problem with your setup of machine learning, the state index alias ["
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java:432]: Might be best not to say "your" in the error, as the problem could be due to a bug and users might take offence that we're blaming them for it.

```suggestion
                    String msg = "Detected a problem with the internal machine learning data: the state index alias ["
```

**Review by droberts195 — APPROVED** [review]
LGTM, but I made a suggestion regarding the error message
