### PR TITLE
ESQL: fix non-null value being returned for unsupported data types in ValueSources

### LINKED ISSUE #100048: [ES|QL] Sort returns a bug when the table has unsupportef fields
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

Sorting fails sometimes with the error

```
No TopN sorting encoder for type UNSUPPORTED
```

### Steps to Reproduce

Playing with ES|QL I tried to run the following query

`from logstash-* | sort extension.keyword`

This returns the error

```
No TopN sorting encoder for type UNSUPPORTED
```

If I run the query:

`from logstash-*  | keep extension.keyword | sort extension.keyword`

the data return successfully.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by astefan**
Refine (and fix) all cases where an unsupported data type field's values are returned from ValueSources.
Improve unsupported data types handling in TopN by catching non-null values encoding/decoding attempts for unsupported data types.

Fixes https://github.com/elastic/elasticsearch/issues/100048

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValueSources.java [hunk 1]
```diff
@@ -69,6 +69,18 @@ public static List<ValueSourceInfo> sources(
                 sources.add(new ValueSourceInfo(new NullValueSourceType(), new NullValueSource(), elementType, ctx.getIndexReader()));
                 continue; // the field does not exist in this context
             }
+            if (asUnsupportedSource) {
+                sources.add(
+                    new ValueSourceInfo(
+                        new UnsupportedValueSourceType(fieldType.typeName()),
+                        new UnsupportedValueSource(null),
```
Comment (astefan) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValueSources.java:76]: This is the actual fix where instead of using `null` as original source argument, the actual source was still in use.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 2]
```diff
@@ -380,6 +380,8 @@ private PhysicalOperation planTopN(TopNExec topNExec, LocalExecutionPlannerConte
                 case "version" -> TopNEncoder.VERSION;
                 case "boolean", "null", "byte", "short", "integer", "long", "double", "float", "half_float", "datetime", "date_period",
                     "time_duration", "object", "nested", "scaled_float", "unsigned_long", "_doc" -> TopNEncoder.DEFAULT_SORTABLE;
+                // unsupported fields are encoded as BytesRef, we'll use the same encoder; all values should be null at this point
+                case "unsupported" -> TopNEncoder.UNSUPPORTED;
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:384]: This is a form of double-checking that non-null values are not reaching TopN for unsupported data types.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValueSources.java [hunk 3]
```diff
@@ -99,19 +111,7 @@ public static List<ValueSourceInfo> sources(
             var fieldContext = new FieldContext(fieldName, fieldData, fieldType);
             var vsType = fieldData.getValuesSourceType();
             var vs = vsType.getField(fieldContext, null);
-
-            if (asUnsupportedSource) {
```
Comment (astefan) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValueSources.java:103]: This was moved earlier in the method because there is no need for all the checks before it, if we know that the data type of the field is definitely an unsupported one.

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks @astefan!

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValueSources.java (hunk 1 above)
Comment (ChrisHegarty) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValueSources.java:76]: Thanks for explicitly calling this out `vs` -> `null`.  It would be easy to miss in review.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java (hunk 2 above)
Comment (ChrisHegarty) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:384]: 👍

**Review by ChrisHegarty — APPROVED** [review]
LGTM
