### PR TITLE
Tweak copy_to handling in synthetic _source to account for nested objects

### LINKED ISSUE #120831: [CI] StandardVersusLogsIndexModeRandomDataChallengeRestIT testEsqlSource failing
**Build Scans:**
- [elasticsearch-periodic #6006 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/xapky6jgfbiuk)
- [elasticsearch-periodic-platform-support #5995 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/bhvnur7ck33na)
- [elasticsearch-periodic-platform-support #5995 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/bnlrax3m32txg)
- [elasticsearch-periodic-platform-support #5995 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/qzzbrkj3jhmt4)
- [elasticsearch-periodic #6006 / openjdk23_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/psmmt5yugkoqu)
- [elasticsearch-periodic #6006 / graalvm-ce17_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/w7srxwvz2vjdq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:logsdb:javaRestTest" --tests "org.elasticsearch.xpack.logsdb.qa.StandardVersusLogsIndexModeRandomDataChallengeRestIT.testEsqlSource" -Dtests.seed=6C57DD0486AE54B5 -Dtests.locale=en-PK -Dtests.timezone=Etc/GMT -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.logsdb.qa.StandardVersusLogsIndexModeRandomDataChallengeRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEsqlSource),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Source matching failed at document id [0]. Source documents don't match for field [yjOTNlEeY.MdaxkeBZK.RNUrtXs]: Error [Lists do not match when ignoring sort order, actual: [1.0, 0.5572748, 0.27104914, 0.13549805, 0.101490855, 0.24916041, 0.8397343, 0.84317076, 0.32944965, 0.8132014], expected: [0.5572748, 0.27104914, 0.13552392, 0.101490855, 0.24916041, 0.9998697, 0.8397343, 0.84317076, 0.32944965, 0.8132014]] actual mappings [{"_doc":{"properties":{"AcX":{"doc_values":true,"index":false,"scaling_factor":100.5,"store":false,"type":"scaled_float"},"VKIboihC":{"doc_values":false,"index":true,"store":true,"synthetic_source_keep":"none","type":"unsigned_long"},"ZwiGr":{"doc_values":false,"index":true,"store":true,"synthetic_source_keep":"all","type":"long"},"host.name":{"type":"keyword"},"ib":{"doc_values":false,"index":true,"store":true,"type":"half_float"},"kUTreamGb":{"doc_values":true,"index":false,"store":false,"type":"integer"},"memory_usage_bytes":{"type":
[truncated]
```

**Issue Reasons:**
- [8.x] 6 failures in test testEsqlSource (3.4% fail rate in 177 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lkts**
Closes #120831.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/IgnoredSourceFieldMapper.java [hunk 1]
```diff
@@ -161,33 +161,7 @@ public void postParse(DocumentParserContext context) {
...
-                ObjectMapper parent = context.parent().findParentMapper(copyToField);
-                if (parent == null) {
-                    // There are scenarios when this can happen:
-                    // 1. all values of the field that is the source of copy_to are null
-                    // 2. copy_to points at a field inside a disabled object
-                    // 3. copy_to points at dynamic field which is not yet applied to mapping, we will process it properly on re-parse.
-                    continue;
-                }
-                int offset = parent.isRoot() ? 0 : parent.fullPath().length() + 1;
-                mutableList.add(new IgnoredSourceFieldMapper.NameValue(copyToField, offset, XContentDataHelper.voidValue(), context.doc()));
```
Comment (lkts) [inline server/src/main/java/org/elasticsearch/index/mapper/IgnoredSourceFieldMapper.java:185]: The problem is this call to `context.doc()`. This is a root document and not a correct nested document.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java [hunk 2]
```diff
@@ -706,6 +706,26 @@ public LuceneDocument doc() {
...
+            ObjectMapper parent = root().findParentMapper(copyToField);
+            // There are scenarios when this is false:
+            // 1. all values of the field that is the source of copy_to are null
+            // 2. copy_to points at a field inside a disabled object
+            // 3. copy_to points at dynamic field which is not yet applied to mapping, we will process it properly after the dynamic update
+            if (parent != null) {
+                int offset = parent.isRoot() ? 0 : parent.fullPath().length() + 1;
+                ignoredFieldValues.add(new IgnoredSourceFieldMapper.NameValue(copyToField, offset, XContentDataHelper.voidValue(), doc));
+            }
+        }
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:727]: I think `getCopyToFields` is not called any more? If so, remove it - and maybe inline `markFieldAsCopyTo` here and remove it.

**Review by kkrik-es — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 2 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:727]: Not related to this change, but also `cloneWithRecordedSource(...)` is not used.

**Review by martijnvg — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 2 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:727]: `markFieldAsCopyTo` is done after parsing and i don't know if this is important. I won't experiment.
