### PR TITLE
ESQL: Account for an exception being thrown when building a BytesRefArrayBlock

### LINKED ISSUE #99472: ESQL: issue using coalesce and to_ip functions
### Description

Using the following test data

```
{
  "mappings": {
    "properties": {
      "emp_no": {
        "type": "long"
      },
      "name": {
        "type": "keyword"
      },
      "job": {
        "type": "text",
        "fields": {
          "raw1": {
            "type": "keyword"
          },
          "raw2": {
            "type": "keyword",
            "ignore_above": 11
          }
        }
      },
      "tag": {
        "type": "text"
      }
    }
  }
}
```

```
{ "index": { } }
{ "emp_no": 10, "name": "Jenny", "job": "IT Director", "ip1": "127.0", "ip2": ".0.1" }
{ "index": { } }
{ "emp_no": 20, "name": "John", "job": "Payroll Specialist", "ip1": "127.0", "ip2": "0.1" }
{ "index": { } }
{ "emp_no": 30, "name": "John", "job": "Payroll Specialist" }
```

This query `FROM test | eval x1 = concat(ip1, ip2), x2 = coalesce(x1, \"255.255.255.255\"), x3 = to_ip(x2)` fails with 

```
"type": "verification_exception",
"reason": "Found 1 problem\nline 1:90: Unknown column [x2], did you mean [x1]?"
```

And this other one `FROM test | eval x1 = concat(ip1, ip2), x2 = coalesce(concat(ip1, ip2), \"255.255.255.255\"), x3 = to_ip(x2)` fails differently

```
        "type": "illegal_argument_exception",
        "reason": "Failed trying to format bytes as IP address.  Possibly caused by a mapping mismatch",
        "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "32 > 0"
        }
```

I believe none of them should fail given the test data.

### PR DESCRIPTION
**Pull request by astefan**
Account for an exception being thrown when building a BytesRefArrayBlock by registering an empty BytesRef in the BytesRefArray, rather than doing nothing and confusing the BytesRefArray content.

Fixes https://github.com/elastic/elasticsearch/issues/99472.

### CODE REVIEW

File: x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/ConvertEvaluatorImplementer.java [hunk 1]
```diff
@@ -166,6 +166,9 @@ private MethodSpec evalVector() {
                 }
                 builder.endControlFlow();
                 builder.addStatement("nullsMask.set(p)");
+                if (resultType.equals(BYTES_REF)) {
+                    builder.addStatement("values.append(org.elasticsearch.compute.data.BytesRefBlockBuilder.NULL_VALUE)");
+                }
```
Comment (astefan) [inline x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/ConvertEvaluatorImplementer.java:171]: This is the actual bug fix.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java [hunk 2]
```diff
@@ -327,7 +327,7 @@ protected static List<TestCaseSupplier> anyNullIsNull(boolean entirelyNullPreser
                         oc.evaluatorToString,
                         oc.expectedType,
                         nullValue(),
-                        oc.getExpectedWarnings(),
+                        null,
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java:330]: Because the warnings were just copied when the `null` parameter testcase was generated, instead of just checking the `null` value is returned, the warnings were also checked and the tests failed where in fact there were no warnings expected.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIPTests.java [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+            suppliers.add(new TestCaseSupplier(supplier.name(), List.of(supplier.type()), () -> {
+                BytesRef value = (BytesRef) supplier.supplier().get();
+                TestCaseSupplier.TypedData typed = new TestCaseSupplier.TypedData(value, supplier.type(), "value");
+                TestCaseSupplier.TestCase testCase = new TestCaseSupplier.TestCase(
+                    List.of(typed),
+                    stringEvaluator,
+                    DataTypes.IP,
+                    equalTo(null)
+                ).withWarning("Line -1:-1: evaluation of [] failed, treating result as null. Only first 20 failures recorded.")
+                    .withWarning("java.lang.IllegalArgumentException: '" + value.utf8ToString() + "' is not an IP string literal.");
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIPTests.java:56]: These warnings ended up failing the null parameter tests I mentioned [above](https://github.com/elastic/elasticsearch/pull/99726/files#r1332253400).

**Comment by astefan** [comment]
@elasticsearchmachine update branch

**Comment by astefan** [comment]
@elasticmachine update branch

**Comment by astefan** [comment]
This is, also, fixing https://github.com/elastic/elasticsearch/issues/99475.

**Comment by astefan** [comment]
> This is, also, fixing #99475.

Actually that bug doesn't reproduce anymore. Without this fix and, also, without https://github.com/elastic/elasticsearch/pull/99685.

File: x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/ConvertEvaluatorImplementer.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/ConvertEvaluatorImplementer.java:171]: I suggest something like
```
builder.addStatement("values.append($T.NULL_VALUE)", BYTES_REF_BLOCK_BUILDER);
```
which'll automatically import `BytesRefBlockBuilder` if it isn't in and leave the package off. It's just a tiny thing though.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIPTests.java (hunk 3 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIPTests.java:56]: :+1:

**Review by nik9000 — APPROVED** [review]

**Comment by astefan** [comment]
@elasticmachine update branch

File: x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/ConvertEvaluatorImplementer.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/ConvertEvaluatorImplementer.java]: Thank you @nik9000. I was looking for a way to have this import done somehow.
