### PR TITLE
SQL: Implement binary format support for SQL clear cursor

### LINKED ISSUE #53359: SQL: the closing endpoint rejects the binary format parameter
Providing the `binary_format` to a closing request results in a failure `x_content_parse_exception: [-1:4034] [indices:data/read/sql/close_cursor] unknown field [binary_format]`

### PR DESCRIPTION
**Pull request by luigidellaquila**
- support binary_format parameter on _sql/close
- make cursor close response consistent with the query protocol
  (ie. in ODBC/JDBC/CLI return CBOR response for cursor close - as for query)

Fixes #53359

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/SqlClearCursorRequest.java [hunk 1]
```diff
@@ -14,16 +14,22 @@
 public class SqlClearCursorRequest extends AbstractSqlRequest {
 
     private final String cursor;
+    private final boolean binaryCommunication;
 
-    public SqlClearCursorRequest(String cursor, RequestInfo requestInfo) {
+    public SqlClearCursorRequest(String cursor, RequestInfo requestInfo, boolean binaryMode) {
```
Comment (Luegg) [inline x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/SqlClearCursorRequest.java:19]:
```suggestion
    public SqlClearCursorRequest(String cursor, RequestInfo requestInfo, boolean binaryCommunication) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+
+public class SqlClearCursorResponseListener extends RestResponseListener<SqlClearCursorResponse> {
+
+    RestRequest request;
+    private final MediaType mediaType;
+
+    protected SqlClearCursorResponseListener(RestChannel channel, RestRequest request, SqlClearCursorRequest sqlRequest) {
+        super(channel);
+        this.request = request;
+        this.mediaType = SqlMediaTypeParser.getResponseMediaType(request, sqlRequest);
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:30]: Maybe `getResponseMediaType` could return an `XContentType` instead of the `assert` below?

**Review by Luegg — COMMENTED** [review]
I've left some comments but I don't understand the motivation behind the change. The JDBC driver and CLI seem to work as is (but 👍 for adding `JdbcCloseCursorIT`) and the `binary_format` parameter is not documented anywhere.

Also, out of curiosity, I couldn't find much information about `binary_format`. Why is this a flag instead of using `Accept` for the content negotiation?

Maybe @bpintea do you have more background?

**Comment by luigidellaquila** [comment]
Thank you very much for the comments @Luegg 
I'm also in doubt of misinterpreting #53359, probably @bpintea can shed some light.
JDBC and CLI work fine already indeed, this fix just adds a little bit of consistency (ie. ask for binary, get CBOR), but I agree with you that it's not strictly necessary.

**Comment by bpintea** [comment]
> I don't understand the motivation behind the change.

As noted in PR's description, the motivation is to "make cursor close response consistent": currently, CBOR is used by default, both for requests and responses. The drivers indicate the need for a CBOR answer with the `binary_format` body attribute. This indication works currently throughout the SQL API, except for the `_sql/close` endpoint. In this case the driver's can not ask for CBOR answer (since the request would fail, #53359).

> The JDBC driver and CLI seem to work as is 

They either "work" inconsistently (in respect to the body format), or leave cursors unclosed.

> the binary_format parameter is not documented anywhere.

This has been by choice, I believe.

> Why is this a flag instead of using Accept for the content negotiation?

No longer sure either, might have been to keep the format unchangeable to (HTTP) proxies. #48261 has a few comments around, but not on this question.

**Comment by Luegg** [comment]
Thanks for the elaborations 👍  Consistency itself also makes sense of course, but I was unsure wether there was something else.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java [hunk 3]
```diff
@@ -104,6 +106,26 @@ public void testNoFormat() {
...
+        );
+        assertEquals(
+            XContentType.CBOR,
+            getResponseMediaType(reqWithAccept("application/whatever"), createClearCursorInstance(true, Mode.JDBC))
+        );
+        assertEquals(
+            XContentType.CBOR,
+            getResponseMediaType(reqWithAccept("application/json"), createClearCursorInstance(true, Mode.ODBC))
+        );
+        assertEquals(XContentType.CBOR, getResponseMediaType(reqWithAccept("application/json"), createClearCursorInstance(true, Mode.CLI)));
```
Comment (bpintea) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java:126]: Might be worth adding another test showing that for non-drivers the CBOR is not enforced, when no binary format is provided.

File: x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/SqlClearCursorRequest.java [hunk 4]
```diff
@@ -14,16 +14,22 @@
...
         super(requestInfo);
         this.cursor = cursor;
+        this.binaryCommunication = binaryMode;
     }
 
     public String getCursor() {
         return cursor;
     }
 
+    public boolean isBinaryCommunication() {
```
Comment (bpintea) [inline x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/SqlClearCursorRequest.java:29]:
```suggestion
    public boolean binaryCommunication() {
```

to keep in in sync with action's version.

File: x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/TestSqlClearCursorRequest.java [hunk 5]
```diff
@@ -33,7 +33,8 @@ public TestSqlClearCursorRequest(RequestInfo requestInfo, String cursor) {
     public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
         org.elasticsearch.xpack.sql.proto.SqlClearCursorRequest protoInstance = new org.elasticsearch.xpack.sql.proto.SqlClearCursorRequest(
             this.getCursor(),
-            this.requestInfo()
+            this.requestInfo(),
+            false
```
Comment (bpintea) [inline x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/TestSqlClearCursorRequest.java:37]: Do the tests require an always `false` value, or could it be random boolean?

File: x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/SqlRequestParsersTests.java [hunk 6]
```diff
@@ -62,7 +62,8 @@ public void testClearCursorRequestParser() throws IOException {
               "cursor": "whatever",
               "mode": "%s",
               "client_id": "bla",
-              "version": "1.2.3"
+              "version": "1.2.3",
+              "binary_format": true
```
Comment (bpintea) [inline x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/SqlRequestParsersTests.java:66]: Shouldn't the binary format be subsequently tested?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+    }
+
+    @Override
+    public RestResponse buildResponse(SqlClearCursorResponse response) throws Exception {
+        assert mediaType instanceof XContentType;
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:35]: Indeed, this could actually be checked (and tested), instead of an assert: one could still send an Accept with a CSV value or something that wouldn't make sense?

**Review by bpintea — COMMENTED** [review]
Looks good, left a few more notes.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:30]: Probably the best thing here is to also support text formats (see SqlResponseListener)

File: x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/TestSqlClearCursorRequest.java (hunk 5 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/TestSqlClearCursorRequest.java:37]: That was my first implementation, I had to revert it since the tests create multiple instances of this stub request and then compare them; if they are different (ie. randomised), the tests fail. A refactor is a bit complex here, and would impact multiple completely unrelated test cases

File: x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+        try (Connection connection = createConnection(connectionProperties())) {
+            try (Statement statement = connection.createStatement()) {
+                statement.setFetchSize(1);
+                ResultSet results = statement.executeQuery(" SELECT name FROM library");
+                assertTrue(results.next());
+                results.close(); // force sending a cursor close since more pages are available
+                assertTrue(results.isClosed());
+            }
+        }
+    }
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java:31]: Done

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:34]: I added support for the text option (same as SqlResponseListener). 
It's returning nothing though, just a RestStatus.OK. Not sure if there is something more meaningful we can return.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java:126]: Done

**Comment by luigidellaquila** [comment]
Added a new batch of changes that addresses all the comments.

File: x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (bpintea) [reply x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java:31]: > exhausted result set cases

The intention might have been to have all the results consumed, then close the cursor.

File: x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+
+    public void testCloseEmpyCursor() throws SQLException, IOException {
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java:33]: Wondering if something like `testCloseNoCursor` or `testCloseMissingCursor` might be more fitting, since the cursor isn't actually present, but empty.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:34]: An alternative would be to simply not support text formats here.
The precedent being the `/translate` endpoint, that (rightfully) has no logic for this and will simply return XContent formats, even if text is required (and maybe surprisingly, not complained about).
The reasoning for it being that this works for the successful case only. In case of failure, this will either return a XContent message, even if text is required (for instance, the cursor is invalid/damaged), or an empty message for failure (ex.: the cursor has already expired), since the `response.succeeded` isn't conveyed (I guess this could be text encoded (`succeeded|true/false`, `succeeded,true/false`, but seems an overkill IMO).

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java [hunk 10]
```diff
@@ -43,9 +48,11 @@
         PARSER.declareString(optionalConstructorArg(), MODE);
         PARSER.declareString(optionalConstructorArg(), CLIENT_ID);
         PARSER.declareString(optionalConstructorArg(), VERSION);
+        PARSER.declareBoolean(SqlClearCursorRequest::binaryCommunication, BINARY_FORMAT);
```
Comment (costin) [inline x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java:51]: Declaring this field mandatory (instead of optional), breaks backwards compatibility for clients that do not set this parameter.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:34]: Similar comment to @bpintea and use the initial approach of `RestToXContentListener` just passing the proper XContent (CBOR) if the binary communication is set.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParser.java [hunk 11]
```diff
@@ -48,6 +49,19 @@ public static MediaType getResponseMediaType(RestRequest request, SqlQueryReques
         return mediaTypeFromHeaders(request);
     }
 
+    /*
+     * see getResponseMediaType(RestRequest, SqlQueryRequest)
+     */
+    public static MediaType getResponseMediaType(RestRequest request, SqlClearCursorRequest sqlRequest) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParser.java:55]: This shouldn't be necessary, see my previous comment.

**Review by costin — CHANGES_REQUESTED** [review]
No need to extend the logic beyond CBOR (binary) and XContent.
Please include also a test/set of backwards compatibility tests to check the proper interaction between old clients (that do NOT set the backwards compatibility flag) with the current code.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java (hunk 10 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java:51]: Not sure I got it, maybe I'm misinterpreting some logic here. 
Isn't it optional already? (see also test https://github.com/elastic/elasticsearch/pull/84230/files#diff-7d14bc9a0a5fb5167a3d7eea6b457ea14324136f334a33df4417ec5f78fefb84R89-R102 )

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+            }
+            results.close();
+            assertTrue(results.isClosed());
+        }
+    }
+
+    public void testCloseNoCursor() throws SQLException, IOException {
+        index("library", "1", builder -> { builder.field("name", "foo"); });
+        index("library", "2", builder -> { builder.field("name", "bar"); });
+        index("library", "3", builder -> { builder.field("name", "baz"); });
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java:50]: I guess this test could work with an empty index, but otoh, if using index data, it might make sense to extract the indexing into a function, to reduce the duplication. The doc id could optionally be left out.

File: x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java [hunk 13]
```diff
@@ -0,0 +1,59 @@
...
+
+        try (Connection connection = createConnection(connectionProperties()); Statement statement = connection.createStatement()) {
+            statement.setFetchSize(1);
+            ResultSet results = statement.executeQuery(" SELECT name FROM library");
+            for (int i = 0; i < 3; i++) {
+                assertTrue(results.next());
+            }
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java:41]: An end assertion could check that there's no more data.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java [hunk 14]
```diff
@@ -0,0 +1,47 @@
...
+    private final XContentType responseType;
+
+    protected SqlClearCursorResponseListener(RestChannel channel, RestRequest request, SqlClearCursorRequest sqlRequest) {
+        super(channel);
+        this.request = request;
+        if (Boolean.TRUE.equals(sqlRequest.binaryCommunication())) {
+            responseType = XContentType.CBOR;
+        } else {
+            responseType = XContentType.JSON;
+        }
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:35]: I think we'll still want to keep the binary enforcement consistent with the query endpoint and return CBOR if Mode#isDriver() and the binary format is not explicitly disabled.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java [hunk 15]
```diff
@@ -132,4 +133,11 @@ protected SqlQueryRequest createTestInstance(boolean binaryCommunication, Mode m
             TimeValue.parseTimeValue(randomTimeValue(), null, "test")
         ).binaryCommunication(binaryCommunication);
     }
+
+    protected SqlClearCursorRequest createClearCursorInstance(boolean binaryCommunication, Mode mode) {
```
Comment (bpintea) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java:137]: Is this still in use?

Comment (luigidellaquila) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/SqlMediaTypeParserTests.java:137]: Removing it

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java (hunk 10 above)
Comment (costin) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java:51]: I read the above as having `constructorArg()` in a similar style to the previous declaration.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlClearCursorAction.java [hunk 16]
```diff
@@ -40,7 +39,11 @@ protected RestChannelConsumer prepareRequest(RestRequest request, NodeClient cli
             sqlRequest = SqlClearCursorRequest.fromXContent(parser);
         }
 
-        return channel -> client.executeLocally(SqlClearCursorAction.INSTANCE, sqlRequest, new RestToXContentListener<>(channel));
+        return channel -> client.executeLocally(
+            SqlClearCursorAction.INSTANCE,
+            sqlRequest,
+            new SqlClearCursorResponseListener(channel, request, sqlRequest)
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlClearCursorAction.java:45]: Please use an anonymous class for sending the response:

```
return channel -> client.executeLocally(SqlClearCursorAction.INSTANCE, sqlRequest, new RestToXContentListener<>(channel) {

    @Override
    public RestResponse buildResponse(SqlClearCursorResponse response) throws Exception {
// no need for filtering
       Boolean binaryRequest = response.binaryRequest;
       XContentType type = Boolean.TRUE.equals(binaryRequest) || (binaryRequest == null && Mode.isDriver(sqlRequest.mode())) ? CBOR : JSON;
        XContentBuilder builder = channel.newBuilder(request.getXContentType(), responseType, false);
        response.toXContent(builder, request);
		return new BytesRestResponse(RestStatus.OK, builder);
    }
}
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java [hunk 17]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    @Override
+    public RestResponse buildResponse(SqlClearCursorResponse response) throws Exception {
+        XContentBuilder builder = channel.newBuilder(request.getXContentType(), responseType, true);
+        response.toXContent(builder, request);
+        BytesRestResponse restResponse = new BytesRestResponse(RestStatus.OK, builder);
+        restResponse.addHeader(HEADER_NAME_TOOK_NANOS, Long.toString(System.nanoTime() - startNanos));
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:45]: This whole class can be sneaked in by using an anonymous class instead. 
Also why specify the took header? That's not something ES responses have outside the payload.

**Review by costin — CHANGES_REQUESTED** [review]
Left comments.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java (hunk 17 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlClearCursorResponseListener.java:45]: I saw it was present in SqlResponseListener, but probably in this case it's overkill. I'll remove it.

**Review by bpintea — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java [hunk 18]
```diff
@@ -0,0 +1,47 @@
...
+import java.sql.Statement;
+
+public abstract class CloseCursorTestCase extends JdbcIntegrationTestCase {
+
+    public void testCloseCursor() throws SQLException, IOException {
+        index("library", "1", builder -> { builder.field("name", "foo"); });
+        index("library", "2", builder -> { builder.field("name", "bar"); });
+        index("library", "3", builder -> { builder.field("name", "baz"); });
+
+        try (Connection connection = createConnection(connectionProperties())) {
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java]: JdbcCloseCursorIT already runs BWC tests with old drivers

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java [hunk 19]
```diff
@@ -43,9 +48,11 @@
...
     }
 
     private String cursor;
+    private Boolean binaryCommunication = BINARY_COMMUNICATION;
```
Comment (astefan) [inline x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java:55]: Sorry, another question: why `Boolean` and not `boolean`?

**Review by astefan — CHANGES_REQUESTED** [review]
Good work so far.  I've left some questions mostly looking for explanations on why a specific approach has been considered.
Also, please, have a look at `JdbcHttpClientRequestTests` where the binary comm is checked for a query request. I think the same should happen for a query close request.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java:55]: Good point, checking

Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java:55]: Same as for `SqlQueryRequest`, I'm using the default value (ie. `CoreProtocol.BINARY_COMMUNICATION`) that is Boolean and today is NULL.

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by costin — APPROVED** [review]
LGTM

**Review by astefan — CHANGES_REQUESTED** [review]
You need to adjust `SqlClearCursorRequestTests` to account for the new component.
`mutateInstance` should probably look something like this

```
    protected TestSqlClearCursorRequest mutateInstance(TestSqlClearCursorRequest instance) throws IOException {
        @SuppressWarnings("unchecked")
        Consumer<TestSqlClearCursorRequest> mutator = randomFrom(
            request -> request.requestInfo(randomValueOtherThan(request.requestInfo(), this::randomRequestInfo)),
            request -> request.setCursor(randomValueOtherThan(request.getCursor(), SqlQueryResponseTests::randomStringCursor)),
            request -> request.binaryCommunication(randomValueOtherThan(request.binaryCommunication(), () -> randomBoolean()))
        );
        TestSqlClearCursorRequest newRequest = new TestSqlClearCursorRequest(instance.requestInfo(), instance.getCursor());
        newRequest.binaryCommunication(instance.binaryCommunication());
        mutator.accept(newRequest);
        return newRequest;
    }
```

`createTestInstance()` should also consider a random value for `binaryCommunication`.

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by astefan — APPROVED** [review]
LGTM

**Review by Luegg — APPROVED** [review]
