### PR TITLE
PromQL: fix binary operator selector filter locality

### LINKED ISSUE #142596: PromQL: Implement vector matching
https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching

### PR DESCRIPTION
**Pull request by sidosera**
Summary:

PromQL binary operands are independent vector expressions. Each side may use different selectors, for example:

```promql
sum by (cluster)(errors{service="foo"}) / on(cluster) sum by (cluster)(requests{service="bar"})
```

Current translation merges selector filters from both sides into one global `AND` condition. This is incorrect and can collapse valid queries to empty results, i.e. 

```
LocalRelation[[...,  step], EMPTY]
```

This diff makes selector filters operand-local and preserves them through binary composition and aggregate folding.

Test plan:

```
 ./gradlew :x-pack:plugin:esql:test --tests  'org.elasticsearch.xpack.esql.optimizer.promql.*'
```

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/promql/PromqlPlanSelectorTests.java [hunk 1]
```diff
@@ -180,4 +182,52 @@ public void testGroupByAllWithinSeriesAggregate() {
...
+        assertThat(lots.stream().filter(AggregateFunction::hasFilter).count(), equalTo(2L));
+        assertNoGlobalSelectorFilter(plan);
+    }
+
+    public void testBinaryOpSelectorOnOneSideOnly() {
+        var plan = planPromql("PROMQL index=k8s step=1m ratio=(sum(network.bytes_in{pod=\"p1\"}) / sum(network.bytes_in))");
+        var lots = collectInnerLastOverTimes(plan);
+        assertThat(lots.stream().filter(AggregateFunction::hasFilter).count(), equalTo(1L));
+        assertThat(lots.stream().filter(s -> s.hasFilter() == false).count(), equalTo(1L));
+        assertNoGlobalSelectorFilter(plan);
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/promql/PromqlPlanSelectorTests.java]: Should we still push the filter down to the source in this case?

**Review by dnhatn — COMMENTED** [review]
I've left a question, but the fix looks good. Thanks @sidosera

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/promql/PromqlPlanSelectorTests.java (hunk 1 above)
Comment (sidosera) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/promql/PromqlPlanSelectorTests.java]: We can’t really do that since both sides of the binary operator read from the same source. If we push `pod=p1` down, it’ll end up filtering data for the right side too, which we don’t want.

Comment (sidosera) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/promql/PromqlPlanSelectorTests.java]: UPD: Added test for unary operator filter push down.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @sidosera
