### PR TITLE
[Test] Use generic for GlobalCheckpoingSyncAction

### LINKED ISSUE #134088: [CI] ClusterInfoServiceIT testMaxQueueLatenciesInClusterInfo failing
**Build Scans:**
- [elasticsearch-periodic #10466 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/j4xssbdj3cetg)
- [elasticsearch-periodic #10436 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/4ykucyykslozy)
- [elasticsearch-periodic-platform-support #10421 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/6xnylecrhk7l6)
- [elasticsearch-periodic-platform-support #10421 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/eythkfekqiqvm)
- [elasticsearch-pull-request #89327 / part-1](https://gradle-enterprise.elastic.co/s/yrdau4y3quioe)
- [elasticsearch-intake #27818 / part1](https://gradle-enterprise.elastic.co/s/cooqdjhnd4alc)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.ClusterInfoServiceIT.testMaxQueueLatenciesInClusterInfo" -Dtests.seed=14C0ED9EF970F45D -Dtests.locale=kkj-Latn-CM -Dtests.timezone=GMT0 -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.ClusterInfoServiceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMaxQueueLatenciesInClusterInfo'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0.0F>
     but: was <0.014456825F>
```

**Issue Reasons:**
- [main] 6 failures in test testMaxQueueLatenciesInClusterInfo (0.9% fail rate in 661 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (18.2% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Redirect the GlobalCheckpoingSyncAction to the generic threadpool so that we have precise control over the write threadpool for load and latency assertions.

Resolves: #134088

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java [hunk 1]
```diff
@@ -496,28 +515,6 @@ public void testMaxQueueLatenciesInClusterInfo() throws Exception {
...
-
-                    @Override
-                    public void accept(long globalCheckpoint, Exception e) {
-                        assertNull(e); // should have no error
-                        logger.info("--> shard [{}] global checkpoint updated to {}", indexShard.shardId().id(), globalCheckpoint);
-                        checkpointsSyncLatch.countDown();
-                    }
-                }, TimeValue.THIRTY_SECONDS);
-            }
-            safeAwait(checkpointsSyncLatch);
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:519]: This is the previous attempt for fixing the issue. Unfortunately it does not work because:
1. The listener is called when the task is still running on the `write` threadpool. There is no guarantee on when the task completely finishes its lifecycle, i.e. going through the `afterExecute` phase. 
2. A earlier checkpoint update action can sometimes see the latest in-memory value and update to it. When this happens, the listener is called while later checkpoint update actions are still queued. The later actions will basically be noop. This is fine for checkpoint update. But it breaks our test assumption.

I tried different ways to determine when the sync actions are completely off the thread pool but didn't manage to find a solution. Therefore, I went with redirecting them to a different threadpool. Hence this PR.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java [hunk 2]
```diff
@@ -431,7 +430,27 @@ public void testMaxQueueLatenciesInClusterInfo() throws Exception {
...
+                new RequestHandlerRegistry<>(
+                    GlobalCheckpointSyncAction.ACTION_NAME + "[p]",
+                    in -> null, // no need to deserialize the request since it's local
+                    mockTransportService.getTaskManager(),
+                    originalRegistry.getHandler(),
+                    mockTransportService.getThreadPool().executor(ThreadPool.Names.GENERIC),
+                    true,
+                    true
+                )
+            );
```
Comment (nicktindall) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:453]: Is it possible we're fixing the wrong problem here, i.e. if the test is sensitive to other things happening in the write pool, is it likely to flap any time someone does some new work on the write pool? Perhaps we could instead isolate the thing we're measuring, or change the assertion somehow?

Comment (ywangd) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:453]: I think it is not very feasible to "isolate the thing we're measuring" at a single thread pool level. The alternative is `assertBusy`. But based on the original [discussion](https://github.com/elastic/elasticsearch/pull/132675#discussion_r2269992479), the preference is to avoid it and be explicit about the other activities. Therefore, I would consider it somewhat a "feature" if it fails in future for new "write" activities, as in we should be aware of exactly what's going on with the write thread pool since every action matters in production.

**Review by nicktindall — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch
