### PR TITLE
Fix http read timeout test by releasing response

### LINKED ISSUE #41794: [CI] HttpReadWriteHandlerTests.testSuccessfulDecodeHttpRequest LEAK
HttpReadWriteHandlerTests.testSuccessfulDecodeHttpRequest failed on my PR build here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/13279/testReport/org.elasticsearch.http.nio/HttpReadWriteHandlerTests/testSuccessfulDecodeHttpRequest/

This reproduces easily by running test class in IntelliJ until failure (just running the method alone is not enough). Somehow every 19th run fails (but not on the same test), probably GC related (no evidence for that statement).

```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.AdvancedLeakAwareByteBuf.nioBuffers(AdvancedLeakAwareByteBuf.java:724)
	org.elasticsearch.http.nio.NettyAdaptor$1.write(NettyAdaptor.java:58)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:721)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:713)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:796)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:706)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:721)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:713)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:796)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:706)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
	io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:721)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:713)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:796)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:706)
	org.elasticsearch.http.nio.NioHttpPipeliningHandler.write(NioHttpPipeliningHandler.java:71)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:721)
```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This fixes #41794. Currently the read timeout test queues up responses
in the netty pipeline. These responses are immediately returned in the
write call, but they are not released. This commit releases the
responses. This will cause the leak detector to quit throwing
exceptions.

### CODE REVIEW

File: plugins/transport-nio/src/test/java/org/elasticsearch/http/nio/HttpReadWriteHandlerTests.java [hunk 1]
```diff
@@ -361,20 +352,30 @@ public void testReadTimeout() throws IOException {
...
+        HttpWriteOperation writeOperation2 = new HttpWriteOperation(context, emptyGetResponse(2), mock(BiConsumer.class));
+        ((ChannelPromise) handler.writeToBytes(writeOperation2).get(0).getListener()).setSuccess();
 
         taskScheduler.pollTask(timeValue.getNanos() + 7).run();
         // No reads and no inflight requests, close
         verify(transport, times(1)).onException(eq(channel), any(HttpReadTimeoutException.class));
         assertNull(taskScheduler.pollTask(timeValue.getNanos() + 9));
     }
 
+    private NioHttpResponse emptyGetResponse(int sequenceNumber) {
```
Comment (original-brownbear) [inline plugins/transport-nio/src/test/java/org/elasticsearch/http/nio/HttpReadWriteHandlerTests.java]: NIT: I guess this method could be `static`?

**Review by original-brownbear — APPROVED** [review]
LGTM (assuming CI is green :))
