### PR TITLE
[ML] Fix bug in inference stats persister for when feature reset is called

### LINKED ISSUE #77182: [CI] TestFeatureLicenseTrackingIT testFeatureTrackingInferenceModelPipeline failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/jzuycanbghb4c/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.TestFeatureLicenseTrackingIT/testFeatureTrackingInferenceModelPipeline

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.TestFeatureLicenseTrackingIT.testFeatureTrackingInferenceModelPipeline" -Dtests.seed=97E92D7B6941E903 -Dtests.locale=fr-CH -Dtests.timezone=Africa/Douala -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.TestFeatureLicenseTrackingIT&tests.test=testFeatureTrackingInferenceModelPipeline

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=74, name=elasticsearch[node_s_0][ml_utility][T#2], state=RUNNABLE, group=TGRP-TestFeatureLicenseTrackingIT]

  at __randomizedtesting.SeedInfo.seed([97E92D7B6941E903:9F9EA15B692AEE67]:0)

  Caused by: org.elasticsearch.common.util.CancellableThreads$ExecutionCancelledException: Reset mode has been enabled

    at __randomizedtesting.SeedInfo.seed([97E92D7B6941E903]:0)
    at org.elasticsearch.xpack.ml.utils.persistence.ResultsPersisterService.lambda$new$0(ResultsPersisterService.java:117)
    at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:531)
    at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:521)
    at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:489)
    at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:421)
    at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by benwtrent**
The test failure originates from an unhandled exception being thrown in the `ml_utility` threadpool.

This exception was thrown by the results persister service, I found a place where the exception thrown was not ultimately handled. 

closes #77182

### CODE REVIEW

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-2

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/annotations/AnnotationPersister.java [hunk 1]
```diff
@@ -58,12 +60,12 @@ public AnnotationPersister(ResultsPersisterService resultsPersisterService) {
      * @param annotation annotation to be persisted
      * @return tuple of the form (annotation id, annotation object)
      */
-    public Tuple<String, Annotation> persistAnnotation(@Nullable String annotationId, Annotation annotation) {
+    public Optional<Tuple<String, Annotation>> persistAnnotation(@Nullable String annotationId, Annotation annotation) {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/annotations/AnnotationPersister.java:63]: I think it's nice to let this throw an exception (as it was) and for the caller to decide what to do with it.

I have the impression that the reason you preferred to change `executeRequest` to catch exceptions was to avoid having to wrap this method with `try-catch` twice in `DatafeedJob`. See there for a suggestion.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java [hunk 2]
```diff
@@ -248,11 +248,16 @@ private void checkForMissingDataIfNecessary() {
                 }
 
                 if (lastDataCheckAnnotationWithId == null) {
-                    lastDataCheckAnnotationWithId = annotationPersister.persistAnnotation(null, annotation);
+                    Optional<Tuple<String, Annotation>> maybeAnnotation = annotationPersister.persistAnnotation(null, annotation);
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java:251]: This `if` block can be simplified so that there is a single call to `persistAnnotation`.

It can be:

```
String annotationId = null;
if (lastDataCheckAnnotationWithId != null) {
  annotationId = lastDataCheckAnnotationWithId.v1();
  Annotation updatedAnnotation = updateAnnotation(annotation);
}
try {
  lastDataCheckAnnotationWithId = annotationPersister.persistAnnotation(annotationId, annotation);
} catch (ElasticsearchException e) {
  ...
}
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/annotations/AnnotationPersister.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/annotations/AnnotationPersister.java:63]: I suppose this can continue to throw, I am very tempted to make the results persister throw a checked exception...

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch
