### PR TITLE
Don't suppress AlreadyClosedException

### LINKED ISSUE #19861: InternalEngine should not catch AlreadyClosedException
There is a lot of exception catching/masking of ACE by InternalEngine, this is **really bad** and will lead to even crashes of the JVM.

Here is an example of what I mean: https://github.com/elastic/elasticsearch/blob/f6aeb35ce8244f4e60cb827cccb42a359f3a2862/core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L564-L566

```
} catch (AlreadyClosedException e) {
            ensureOpen();                                 // possibly masks ACE by another exception!
            maybeFailEngine("refresh", e);                // definitely swallows ACE!
}
```

Please, do not catch this exception! It should only happen in truly exceptional circumstances, such as a bug in the code, and so on. Perhaps it should be treated similar to Error by elasticsearch.

### PR DESCRIPTION
**Pull request by mikemccand**
Catching  and suppressing `AlreadyClosedException` from Lucene is dangerous because it can mean there is a bug in ES since ES should normally guard against invoking Lucene classes after they were closed.

I reviewed the cases where we catch `AlreadyClosedException` from Lucene and removed the ones that I believe are not needed, or improved comments explaining why ACE is OK in that case.

I think (@s1monw can you confirm?) that holding the engine's `readLock` means IW will not be closed, except if disaster strikes (`failEngine`) at which point I think it's fine to see the original ACE in the logs?

Closes #19861

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/engine/EngineSearcher.java [hunk 1]
```diff
@@ -59,9 +59,10 @@ public void close() {
         } catch (IOException e) {
             throw new IllegalStateException("Cannot close", e);
         } catch (AlreadyClosedException e) {
-                /* this one can happen if we already closed the
-                 * underlying store / directory and we call into the
-                 * IndexWriter to free up pending files. */
+            /* This can happen in a race condition: since we don't hold the engine's readLock (preventing it from closing) while
+             * holding this searcher, while closing just now, it's possible that we concurrently close the engine's IndexWriter and ES's
+             * store, and since closing Lucene's DirectoryReader tries to delete pending files it had held open, we can hit
+             * AlreadyClosedException from Lucene's Directory */
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/engine/EngineSearcher.java]: I'm not sure I buy the above explanation ;)  Lucene's `DirectoryReader` itself already ignores `ACE` when trying to reclaim the pending deleted files.  So I'm tempted to remove this catch clause ...

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 2]
```diff
@@ -561,9 +561,6 @@ public void refresh(String source) throws EngineException {
         try (ReleasableLock lock = readLock.acquire()) {
             ensureOpen();
             searcherManager.maybeRefreshBlocking();
-        } catch (AlreadyClosedException e) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Do we still need to catch this and then immediately rethrow otherwise it will get eaten by the general catch block below?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 3]
```diff
@@ -609,9 +606,6 @@ public void writeIndexingBuffer() throws EngineException {
                              new ByteSizeValue(indexingBufferBytes), new ByteSizeValue(versionMapBytes));
                 indexWriter.flush();
             }
-        } catch (AlreadyClosedException e) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Same comment here as above: do we still need to catch this and then immediately rethrow otherwise it will get eaten by the general catch block below?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 4]
```diff
@@ -961,11 +956,7 @@ protected final void closeNoLock(String reason) {
...
                 // no need to commit in this case!, we snapshot before we close the shard, so translog and all sync'ed
                 logger.trace("rollback indexWriter");
-                try {
-                    indexWriter.rollback();
-                } catch (AlreadyClosedException e) {
-                    // ignore
-                }
+                indexWriter.rollback();
                 logger.trace("rollback indexWriter done");
             } catch (Exception e) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: This catch blow will now swallow an `AlreadyClosedException`!

File: core/src/main/java/org/elasticsearch/index/engine/ShadowEngine.java [hunk 5]
```diff
@@ -190,8 +189,6 @@ public void refresh(String source) throws EngineException {
         try (ReleasableLock lock = readLock.acquire()) {
             ensureOpen();
             searcherManager.maybeRefreshBlocking();
-        } catch (AlreadyClosedException e) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/ShadowEngine.java]: Same comment here: do we still need to catch this and then immediately rethrow otherwise it will get eaten by the general catch block below?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 2 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Also, note that this refresh call can come from, for example, `InternalEngine#writeIndexingBuffer` from `IndexShard#writeIndexingBuffer` which has a general catch block which will swallow the `AlreadyClosedException`!

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 6]
```diff
@@ -561,9 +561,6 @@ public void refresh(String source) throws EngineException {
         try (ReleasableLock lock = readLock.acquire()) {
             ensureOpen();
             searcherManager.maybeRefreshBlocking();
-        } catch (AlreadyClosedException e) {
-            ensureOpen();
-            maybeFailEngine("refresh", e);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Shouldn't we still be failing the engine here?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 7]
```diff
@@ -609,9 +606,6 @@ public void writeIndexingBuffer() throws EngineException {
                              new ByteSizeValue(indexingBufferBytes), new ByteSizeValue(versionMapBytes));
                 indexWriter.flush();
             }
-        } catch (AlreadyClosedException e) {
-            ensureOpen();
-            maybeFailEngine("writeIndexingBuffer", e);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Same question: shouldn't we still be failing the engine here?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 4 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I don't think `IW.rollback` throws `AlreadyClosedException`.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Okay!

**Comment by mikemccand** [comment]
@jasontedor thank you for the feedback; I pushed new changes.

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 8]
```diff
@@ -914,6 +916,7 @@ protected final void writerSegmentStats(SegmentsStats stats) {
 
     @Override
     public long getIndexBufferRAMBytesUsed() {
+        // We don't guard w/ readLock here, so we could throw AlreadyClosedException
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Does this need to caught and wrapped then?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 9]
```diff
@@ -562,8 +562,9 @@ public void refresh(String source) throws EngineException {
             ensureOpen();
             searcherManager.maybeRefreshBlocking();
         } catch (AlreadyClosedException e) {
-            ensureOpen();
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I'm curious about the removal of the `ensureOpen` calls; can you explain?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 8 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Well, where `IndexShard` calls this method, it expects/handles the `AlreadyClosedException` (`handleRefreshException` in `IndexShard.java`), and an ACE thrown from here can happen under normal usage (does not necessarily mean there's a bug).

`super`'s javadocs also state that it can throw `AlreadyClosedException`.

We could alternatively acquire the `readLock`, in this method (and re-throw to `AssertionError`), but that's somewhat scary since `writeLock` can be held for quite some time, blocking `IndexingMemoryController` from polling the shards when one engine is flushing.

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 9 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: `ensureOpen()` can throw its own exception, masking the (unexpected) `AlreadyClosedException` we just hit.  Also, except for disaster (failing engine), we should never have hit an `AlreadyClosedException` because the engine was closed in that try block since we hold the `readLock`.  I think?

File: core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java [hunk 10]
```diff
@@ -71,7 +72,17 @@ static boolean isFatalUncaught(Throwable e) {
     }
 
     private static boolean isFatalCause(Throwable cause) {
-        return cause instanceof Error;
+        // We wrap AlreadyClosedException in AssertionError when we re-throw to ensure catch clauses don't suppress it, but we should not
+        // halt the JVM for that case:
+        return cause instanceof Error && isWrappedAlreadyClosedException(cause) == false;
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java]: why?

Please, let it halt the jvm. the jvm will halt in a much nastier way if we do not resolve the bugs around this :)

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 4 above)
Comment (uschindler) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Ähm, it could?

File: core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java (hunk 10 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java]: OK I'll revert the changes here.  It is true that at defaults (`MMapDirectory`) we are already playing with fire on hitting an `AlreadyClosedException`.

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 4 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I didn't think it would?  It's not supposed to?  If it does I think it's a Lucene bug?  We have this comment in `IndexWriter.rollback`:

```
    // don't call ensureOpen here: this acts like "close()" in closeable.
```

File: core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java (hunk 10 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java]: I'm not sure I agree, do we really need to be potentially failing or removing from the in-sync replica set all the *other* shards on this node in this situation?

Comment (rmuir) [inline core/src/main/java/org/elasticsearch/bootstrap/ElasticsearchUncaughtExceptionHandler.java]: dude. its going to crash the jvm if we do not find the cause of this bug!

**Comment by s1monw** [comment]
thanks mike for cleaning this up. We need to be very careful since EngineClosedException has a special meaning in replication that we use to retry documents so we should ensure that we suppress ACE when the engine is closed or also add ACE to the list of exceptions that trigger a retry?

I also wonder about the SearcherManager contract a bit. It seems like we are closing things in the right order SM first then rollback the writer. so from my perspective hitting ACE on SM is always safe? if not that's a problem in SM or RM? I am not sure if IW protects the caller from this or if there are any concurrency issues but SM should be safe to be called at any time?

**Comment by mikemccand** [comment]
I unassigned myself here and on #19861: I don't think I'm qualified to improve the exception handling here.

I had a chat with @s1monw about all the scary complexities; I think someone who better understands the locking / concurrency in the engine, and what the different exceptions mean to the distributed layer, etc., needs to tackle this.

> I also wonder about the SearcherManager contract a bit. 

I'll look into this.

**Comment by s1monw** [comment]
> I unassigned myself here and on #19861: I don't think I'm qualified to improve the exception handling here.

I don't think so. It's something we have to solve, I can only encourage you to go and fix it. As long as we do the right thing in the indexing path I think we are fine?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 9 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: this is the code that I mean, is it ok to concurrently close SM and  call SM#maybeRefreshBlocking? if so we can ignore the ACE if ensureOpen throws an exception so I thin the code is good?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 11]
```diff
@@ -961,11 +964,7 @@ protected final void closeNoLock(String reason) {
                 }
                 // no need to commit in this case!, we snapshot before we close the shard, so translog and all sync'ed
                 logger.trace("rollback indexWriter");
-                try {
-                    indexWriter.rollback();
-                } catch (AlreadyClosedException e) {
-                    // ignore
-                }
+                indexWriter.rollback();
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: if we hit a merge exception in multiple threads we can call this multiple times? Why is it not ok to swallow this? do we need more assertions here or commments?

File: core/src/main/java/org/elasticsearch/index/engine/ShadowEngine.java [hunk 12]
```diff
@@ -191,7 +191,8 @@ public void refresh(String source) throws EngineException {
             ensureOpen();
             searcherManager.maybeRefreshBlocking();
         } catch (AlreadyClosedException e) {
-            ensureOpen();
+            // This means there's a bug somewhere: don't suppress it
+            throw new AssertionError(e);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/engine/ShadowEngine.java]: this one in the shadow engine shouldn't happen indeed

**Comment by s1monw** [comment]
@mikemccand I pushed new changes

**Comment by mikemccand** [comment]
LGTM, thanks @s1monw

**Comment by s1monw** [comment]
@mikemccand I had to add another special case for forceMerge can you take another look

**Comment by mikemccand** [comment]
LGTM, thanks @s1monw
