### PR TITLE
SQL: handle MIN and MAX functions on dates in Painless scripts

### LINKED ISSUE #57581: SQL: datetime related scripts for aggregates and groupings broken
Following the refactoring that created the QL project, a minor change to how the scripts used in aggregates and grouping are created introduced a bug affecting `HAVING` filtering for functions that return a datetime data type. For example, `SELECT gender, MIN(birth_date) FROM test_emp GROUP BY gender HAVING min(birth_date) < NOW()` is translated into

```
            "aggregations": {
                "ad3fe3c3": {
                    "min": {
                        "field": "birth_date"
                    }
                },
                "having.ad3fe3c3": {
                    "bucket_selector": {
                        "buckets_path": {
                            "a0": "ad3fe3c3"
                        },
                        "script": {
                            "source": "InternalQlScriptUtils.nullSafeFilter(InternalQlScriptUtils.lt(params.a0,InternalSqlScriptUtils.asDateTime(params.v0)))",
                            "lang": "painless",
                            "params": {
                                "v0": "2020-06-03T06:02:14.475Z"
                            }
                        },
                        "gap_policy": "skip"
                    }
                }
            }
```

the issue being `InternalQlScriptUtils.lt(params.a0,InternalSqlScriptUtils.asDateTime(params.v0))` where `params.a0` is not converted in a date time, just like `params.v0` is. The correct script should have been `InternalQlScriptUtils.lt(InternalSqlScriptUtils.asDateTime(params.a0),InternalSqlScriptUtils.asDateTime(params.v0))`.

This is affecting all aggregate functions that deal with datetime parameters, not only `MIN` exemplified in this issue.

### PR DESCRIPTION
**Pull request by astefan**
MIN and MAX aggregate functions on date fields natively generate a number which, when used in Painless scripts, should be converted to a date/datetime. This used to work in the past, but was broken in more recent versions. Not having tests for this type of query didn't help either. This PR re-adds the date/datetime conversion back in aggregate scripts and adds tests. The solution is not ideal, but until the SQL specific scripts handling in QL is not made pluggable, the current approach is a quick fix.

Fixes https://github.com/elastic/elasticsearch/issues/57581.

### CODE REVIEW

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/function/scalar/ScalarFunction.java [hunk 1]
```diff
@@ -108,19 +109,28 @@ protected ScriptTemplate scriptWithScalar(ScalarFunction scalar) {
...
     
     protected ScriptTemplate scriptWithAggregate(AggregateFunction aggregate) {
-        String template = "{}";
+        String template = basicTemplate(aggregate);
         return new ScriptTemplate(processScript(template),
                 paramsBuilder().agg(aggregate).build(),
                 dataType());
     }
 
     protected ScriptTemplate scriptWithGrouping(GroupingFunction grouping) {
```
Comment (matriv) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/function/scalar/ScalarFunction.java:118]: Shouldn't we remove this method as currently there is no such case that a groupingfunction (actually histogram) results into a script?

**Review by matriv — APPROVED** [review]
LGTM. left a comment

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/function/scalar/ScalarFunction.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/function/scalar/ScalarFunction.java:118]: Chose to keep it there since, before the bug was introduced, the code was using `asDateTime` for grouping functions, as well.

Comment (matriv) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/function/scalar/ScalarFunction.java:118]: Would you mind adding a comment then, please, to avoid pursuing it again in the future?

**Review by costin — APPROVED** [review]
LGTM.

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix-windows

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/f1de99e2a6fbf3806c4f2b6b809738aa8faa2d75
7.x (7.9.0): https://github.com/elastic/elasticsearch/commit/3cc816694687c0204469b8dd26435bf4f2bf645d
7.8 (7.8.1): https://github.com/elastic/elasticsearch/commit/cbcf19758f20d59984488c04e1aaa1b5a0a755e3
