### PR TITLE
Check that scripts produce correct json in render template action

### LINKED ISSUE #101477: Inconsistent handling of invalid rendered JSON in search template APIs
### Elasticsearch Version

8.10.4

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Cloud

### Problem Description

The [search template API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template-api.html) and [render search template API](https://www.elastic.co/guide/en/elasticsearch/reference/current/render-search-template-api.html) handle invalid rendered JSON differently.

The search template API (correctly) returns a `400` response, while the render search template API returns a`500` response. This is due to the fact that the render search template API implementation [returns early from the convert method](https://github.com/elastic/elasticsearch/blob/3ce905b75432e36648ae013a3580b1f12537cae9/modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/TransportSearchTemplateAction.java#L108), skipping the code that would throw `XContentParseException`.

### Steps to Reproduce

1. Create a search template that will render invalid JSON:

```
PUT _scripts/test-search-template
{
  "script": {
    "lang": "mustache",
    "source": """
    {
      "query": {
        "multi_match": {
          "query": "{{query_string}}",
          "fields": [{{#text_fields}}"{{name}}^{{boost}}"{{/text_fields}}]
        }
      },
      "from": "{{from}}",
      "size": "{{size}}"
    }
    """,
    "params": {
      "query_string": "My query string"
    }
  }
}
```

2. Use the search template API to run a query:

```
GET my-index/_search/template
{
  "id": "test-search-template",
  "params": {
    "text_fields": [
      {"name": "title", "boost": 10},
      {"name": "description", "boost": 5}
    ],
    "from": 0,
    "size": 10
  }
}
```

Observe the `400` response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": """[6:33] Unexpected character ('"' (code 34)): was expecting comma to separate Array entries
 at [Source: (String)"
    {
      "query": {
        "multi_match": {
          "query": "",
          "fields": ["title^10""description^5"]
        }
      },
      "from": "0",
      "size": "10"
    }
    "; line: 6, column: 33]"""
      }
    ],
    "type": "x_content_parse_exception",
    "reason": """[6:33] Unexpected character ('"' (code 34)): was expecting comma to separate Array entries
 at [Source: (String)"
    {
      "query": {
        "multi_match": {
          "query": "",
          "fields": ["title^10""description^5"]
        }
      },
      "from": "0",
      "size": "10"
    }
    "; line: 6, column: 33]""",
    "caused_by": {
      "type": "json_parse_exception",
      "reason": """Unexpected character ('"' (code 34)): was expecting comma to separate Array entries
 at [Source: (String)"
    {
      "query": {
        "multi_match": {
          "query": "",
          "fields": ["title^10""description^5"]
        }
      },
      "from": "0",
      "size": "10"
    }
    "; line: 6, column: 33]"""
    }
  },
  "status": 400
}
```

3. Use the render search template API to render the search template:

```
POST _render/template
{
  "id": "test-search-template",
  "params": {
    "text_fields": [
      {"name": "title", "boost": 10},
      {"name": "description", "boost": 5}
    ],
    "from": 0,
    "size": 10
  }
}
```

Observe the `500` response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": """Unexpected character ('"' (code 34)): was expecting comma to separate Array entries
 at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 6, column: 33]"""
      }
    ],
    "type": "json_parse_exception",
    "reason": """Unexpected character ('"' (code 34)): was expecting comma to separate Array entries
 at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 6, column: 33]""",
    "suppressed": [
      {
        "type": "illegal_state_exception",
        "reason": "Failed to close the XContentBuilder",
        "caused_by": {
          "type": "i_o_exception",
          "reason": "Unclosed object or array found"
        }
      }
    ]
  },
  "status": 500
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by romseygeek**
If a mustache script that outputs badly-formed json is referred to in a render
template request, then the error returned will be a 500 server error, rather than
a 400 json parsing error.  This is because rendering templates skips json parsing,
and so the error ends up being caught in the REST layer instead.

This commit changes the template rendering logic to always parse the output of
the script, catching json errors higher in the stack and allowing us to return 
the correct status code.  This also means that errors are correctly detected and
returned as part of multi search template requests.

Fixes #101477

### CODE REVIEW

File: modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/MultiSearchTemplateIT.java [hunk 1]
```diff
@@ -175,10 +176,9 @@ public void testBasic() throws Exception {
         assertThat(response4.getFailure().getMessage(), equalTo("no such index [unknown]"));
 
         MultiSearchTemplateResponse.Item response5 = response.getResponses()[4];
-        assertThat(response5.isFailure(), is(false));
-        SearchTemplateResponse searchTemplateResponse5 = response5.getResponse();
-        assertThat(searchTemplateResponse5.hasResponse(), is(false));
-        assertThat(searchTemplateResponse5.getSource().utf8ToString(), equalTo("{\"query\":{\"terms\":{\"group\":[1,2,3,]}}}"));
+        assertThat(response5.isFailure(), is(true));
```
Comment (romseygeek) [inline modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/MultiSearchTemplateIT.java:179]: This looks like a BWC break, but in fact this request would always throw an error via a REST request because the RestToXContentListener would try and parse things, but this test goes via the internal client which doesn't do any json parsing.

Comment (cbuescher) [reply modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/MultiSearchTemplateIT.java:179]: ack

File: modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/SearchTemplateIT.java [hunk 2]
```diff
@@ -189,6 +191,64 @@ public void testIndexedTemplateClient() throws Exception {
         assertNull(getResponse.getSource());
     }
 
+    public void testBadTemplate() {
```
Comment (cbuescher) [inline modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/SearchTemplateIT.java:194]: small nit: could you add a short description of this test for future audiences, i.e. what is wrong with the template and why it should fail? Also that we test that both the simulate/non-simulate options return the same error.

**Review by cbuescher — APPROVED** [review]
LGTM, I left a small suggestion about commenting the test

File: modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/SearchTemplateIT.java [hunk 3]
```diff
@@ -189,6 +191,69 @@ public void testIndexedTemplateClient() throws Exception {
...
+            "text_fields",
+            List.of(Map.of("name", "title", "boost", 10), Map.of("name", "description", "boost", 2)),
+            "from",
+            0,
+            "size",
+            0
+        );
+
+        {
+            ParsingException e = expectThrows(ParsingException.class, () -> {
```
Comment (Mikep86) [inline modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/SearchTemplateIT.java:232]: This test appears to be passing, but for the wrong reason. The message from the exception thrown is:

```
org.elasticsearch.common.ParsingException: Unknown key for a START_OBJECT in [script].
```

Which reads like it's not even able to parse the script. Shouldn't the exception thrown here be `XContentParseException`?

Comment (romseygeek) [reply modules/lang-mustache/src/internalClusterTest/java/org/elasticsearch/script/mustache/SearchTemplateIT.java:232]: Oh, that's a good spot.  Interestingly, the test did fail without the fix, but it looks as though I'm not testing the specific scenario mentioned in the original issue.  I'll try and tidy up in a follow-up
