### PR TITLE
ESQL: Fix ReplaceAliasingEvalWithProject in case of shadowing

### LINKED ISSUE #137019: ESQL: bug in ReplaceAliasingEvalWithProject: optimized incorrectly due to missing references
Once more! Straight from the generative tests (already shrunk):
```
row vKBRQmBiqSe = 1
| eval  HqAogEZW = RAZdNDZEWAnqxF,  kfkZrDpdlGhS = vKBRQmBiqSe, vKBRQmBiqSe = 4191264652016276724
| enrich languages_policy on HqAogEZW
| rename language_name as message
```

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/137019

### CODE REVIEW

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java [hunk 1]
```diff
@@ -230,6 +232,19 @@ public static GreaterThanOrEqual greaterThanOrEqualOf(Expression left, Expressio
         return new GreaterThanOrEqual(EMPTY, left, right, ESTestCase.randomZone());
     }
 
+    public static FieldAttribute findFieldAttribute(LogicalPlan plan, String name) {
+        Holder<FieldAttribute> result = new Holder<>();
+        plan.forEachDown(EsRelation.class, relation -> {
+            for (Attribute attr : relation.output()) {
+                if (attr.name().equals(name)) {
+                    result.set((FieldAttribute) attr);
```
Comment (bpintea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:253]: Should we throw if multiple are found? Just to make the testing less "exciting", in case this method ends up being used a plan with multiple sources.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java [hunk 2]
```diff
@@ -53,47 +57,63 @@ public LogicalPlan apply(LogicalPlan logicalPlan) {
...
+                // The field may shadow one of the attributes that we will need to correctly perform the subsequent projection.
+                // If so, rename it in the eval!
+                if (namesRequiredForProjectionAliases.contains(field.name())) {
+                    Alias newField = new Alias(field.source(), locallyUniqueTemporaryName(field.name()), field.child(), null, true);
+                    Alias reRenamedField = new Alias(field.source(), field.name(), newField.toAttribute(), field.id(), field.synthetic());
+                    projectionAliases.put(field.toAttribute(), reRenamedField);
+                    // the renaming also needs to be propagated to eval fields to the right
+                    renamesToPropagate.put(field.toAttribute(), newField.toAttribute());
+
+                    field = newField;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java]: Optional: for legibility, I'd reflow this into an `if () {} else if () {} else {}`, rather than reuse the `field` var.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java [hunk 3]
```diff
@@ -53,47 +57,63 @@ public LogicalPlan apply(LogicalPlan logicalPlan) {
...
+        Set<String> namesRequiredForProjectionAliases = new HashSet<>();
 
-        List<Alias> keptFields = new ArrayList<>();
+        List<Alias> newEvalFields = new ArrayList<>();
 
         var fields = eval.fields();
         for (int i = 0, size = fields.size(); i < size; i++) {
             Alias field = fields.get(i);
-            Expression child = field.child();
             var attribute = field.toAttribute();
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java]: Let's move this in the "basic renaming" branch.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java [hunk 4]
```diff
@@ -53,47 +57,63 @@ public LogicalPlan apply(LogicalPlan logicalPlan) {
...
+        AttributeMap.Builder<NamedExpression> projectionAliases = AttributeMap.builder();
+        // The names of attributes that are required to perform the aliases in a subsequent projection - if the next eval field
+        // shadows one of these names, the subsequent projection won't work, so we need to perform a temporary rename.
+        Set<String> namesRequiredForProjectionAliases = new HashSet<>();
 
-        List<Alias> keptFields = new ArrayList<>();
+        List<Alias> newEvalFields = new ArrayList<>();
 
         var fields = eval.fields();
         for (int i = 0, size = fields.size(); i < size; i++) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java]: Optional, but since changing this method "sufficiently"...: `'for' loop can be replaced with enhanced 'for'`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java [hunk 5]
```diff
@@ -53,47 +57,63 @@ public LogicalPlan apply(LogicalPlan logicalPlan) {
...
             Alias field = fields.get(i);
-            Expression child = field.child();
             var attribute = field.toAttribute();
-            // put the aliases in a separate map to separate the underlying resolve from other aliases
-            if (child instanceof Attribute) {
-                basicAliasesBuilder.put(attribute, child);
-                basicAliasSourcesBuilder.put(attribute, field);
+            // propagate all previous aliases into the current field
+            field = (Alias) field.transformUp(e -> renamesToPropagate.build().resolve(e, e));
+            Expression child = field.child();
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java:76]: Optional: can be inlined.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java [hunk 6]
```diff
@@ -0,0 +1,242 @@
...
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.alias;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.as;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.assertEqualsIgnoringIds;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.findFieldAttribute;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.mul;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.of;
+import static org.hamcrest.Matchers.startsWith;
+
+public class ReplaceAliasingEvalWithProjectTests extends AbstractLogicalPlanOptimizerTests {
+    /**
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:30]:
```suggestion
    /*
```

To avoid this default rendering (and since it's not really javadoc :) ):
Screenshot 2025-10-24 at 15 07 49

**Review by bpintea — APPROVED** [review]
Thanks, interesting it didn't surface earlier.
I've only left style optional notes.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java [hunk 7]
```diff
@@ -0,0 +1,242 @@
...
+     *   \_Limit[1000[INTEGER],false,false]
+     *     \_EsRelation[test][_meta_field{f}#24, emp_no{f}#18, first_name{f}#19, ..]
+     */
+    public void testSimple() {
+        // Rule only kicks in if there's a Project or Aggregate above, so we add a KEEP *
+        var plan = plan("""
+            from test
+            | KEEP emp_no, salary
+            | EVAL emp_no2 = emp_no, salary2 = 2*salary, emp_no3 = emp_no2, salary3 = 3*salary2
+            | KEEP *
```
Comment (julian-elastic) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:44]: Can you please add a case where there is a separate eval after that does something similar?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java [hunk 8]
```diff
@@ -0,0 +1,242 @@
...
+     *   \_Limit[1000[INTEGER],false,false]
+     *     \_EsRelation[test][_meta_field{f}#24, emp_no{f}#18, first_name{f}#19, ..]
+     */
+    public void testNonAliasShadowingAliasedAttribute() {
+        // Rule only kicks in if there's a Project or Aggregate above, so we add a KEEP *
+        var plan = plan(randomFrom("""
+            from test
+            | KEEP emp_no, salary
+            | EVAL emp_no2 = emp_no, emp_no = 2*salary, emp_no3 = emp_no2, salary3 = 2*emp_no
+            | KEEP *
```
Comment (julian-elastic) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:233]: Can you please add a test case with lookup join where emp_no can come from both the main index and the lookup index?

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java (hunk 1 above)
Comment (julian-elastic) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:253]: I think the multiple case will likely happen in case of lookup join if the name is both in the main index and the lookup index. We should test this

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java [hunk 9]
```diff
@@ -0,0 +1,242 @@
...
+     * \_Eval[[salary{f}#25 * 2[INTEGER] AS salary2#6, salary2{r}#6 * 3[INTEGER] AS $$salary2$temp_name$31#32,
+     *  $$salary2$temp_name$31{r$}#32 * 4[INTEGER] AS salary3#15]]
+     *   \_Limit[1000[INTEGER],false,false]
+     *     \_EsRelation[test][_meta_field{f}#26, emp_no{f}#20, first_name{f}#21, ..]
+     */
+    public void testAliasForShadowedNonAlias() {
+        // Rule only kicks in if there's a Project or Aggregate above, so we add a KEEP *
+        var plan = plan("""
+            from test
+            | KEEP salary
```
Comment (julian-elastic) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:467]: If you don't have it already, can you please add a test with a LOOP of evals to make sure the logic does not get in an infinite loop? e.g
row a = 1
eval b = a, a = b, b = a, a = b, b = a, a = b

 row a = 1
eval b = a, c = b, a = c

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java [hunk 10]
```diff
@@ -0,0 +1,242 @@
...
+     * EsqlProject[[salary{f}#22, salary2{r}#6, salary2{r}#6 AS aliased_salary2#9, salary3{r}#12, salary2{r}#6 AS twice_aliased_salary2#15]]
+     * \_Eval[[salary{f}#22 * 2[INTEGER] AS salary2#6, salary2{r}#6 * 3[INTEGER] AS salary3#12]]
+     *   \_Limit[1000[INTEGER],false,false]
+     *     \_EsRelation[test][_meta_field{f}#23, emp_no{f}#17, first_name{f}#18, ..]
+     */
+    public void testAliasForNonAlias() {
+        // Rule only kicks in if there's a Project or Aggregate above, so we add a KEEP *
+        var plan = plan("""
+            from test
+            | KEEP salary
```
Comment (julian-elastic) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:430]: Can we throw in some renames in the mix?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java [hunk 11]
```diff
@@ -0,0 +1,242 @@
...
+    /**
+     * EsqlProject[[salary{f}#25, salary2{r}#6 AS aliased_salary2#9, $$salary2$temp_name$31{r$}#32 AS salary2#12, salary3{r}#15,
+     *  salary3{r}#15 AS salary4#18]]
+     * \_Eval[[salary{f}#25 * 2[INTEGER] AS salary2#6, salary2{r}#6 * 3[INTEGER] AS $$salary2$temp_name$31#32,
+     *  $$salary2$temp_name$31{r$}#32 * 4[INTEGER] AS salary3#15]]
+     *   \_Limit[1000[INTEGER],false,false]
+     *     \_EsRelation[test][_meta_field{f}#26, emp_no{f}#20, first_name{f}#21, ..]
+     */
+    public void testAliasForShadowedNonAlias() {
+        // Rule only kicks in if there's a Project or Aggregate above, so we add a KEEP *
```
Comment (julian-elastic) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:464]: It seems the rule is also turned on by aggregate. Can we have at least one aggregate example?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java [hunk 12]
```diff
@@ -20,7 +20,11 @@
...
 
 import java.util.ArrayList;
+import java.util.HashSet;
 import java.util.List;
+import java.util.Set;
+
+import static org.elasticsearch.xpack.esql.optimizer.rules.logical.TemporaryNameUtils.locallyUniqueTemporaryName;
 
 /**
  * Replace aliasing evals (eval x=a) with a projection which can be further combined / simplified.
```
Comment (julian-elastic) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java:30]: Why do we require project on top? It seems we are missing a lot of optimization opportunities. 
e.g. maybe we will duplicate a billion doc field many times for this ES|QL? I tested with logical planning, not sure if we have rules later to handle this. 
```
from test
| EVAL salary = salary+1, salary = salary +1, salary = salary +1
```

```
Eval[[salary{f}#17 + 1[INTEGER] AS salary#5, salary{r}#5 + 1[INTEGER] AS salary#8, salary{r}#8 + 1[INTEGER] AS sala
ry#11]]
\_Limit[1000[INTEGER],false,false]
  \_EsRelation[test][_meta_field{f}#18, emp_no{f}#12, first_name{f}#13, ..]
```

Comment (julian-elastic) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java:30]: The example above should be optimized to just this, no project needed
```
from test
| EVAL salary = salary+3
```

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java:30]: This rule doesn't propagate shadowed, internal columns from an eval. We could do that! But I don't think we do.
I expect this is what you'd want this to become?

```
from test
| EVAL salary = ((salary+1)+1)+1
```
(Which should be simplified by some other rule to `salary+3`, I think.)

> Why do we require project on top?

Great question! That rule is super old, and I don't recall why we don't trigger it always. My hunch is that we wanted it mostly to combine the aliases from the eval with downstream projections. But we could profit from propagating the aliases more generally.

That said, on its own, there is no performance difference between a simple alias in an eval vs. in a projection. Both are cheap! They just incRef the underlying block. (Unless that block is sent over the wire. But that could also be tackled on the serialization level.)

**Review by julian-elastic — APPROVED** [review]
This rule is pretty complicated, I feel like it tries to do too much at the same time and the same function. I wonder if we can refactor  it somehow, e.g. have a method that does just the aliasing, have a method that does just the renaming, have a method that builds the final output. The changes themselves seem correct. Also added some testing recommendations in the comments.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java (hunk 12 above)
Comment (julian-elastic) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java:30]: Yes, I would expect us to get to salary = ((salary+1)+1)+1 and then fold the constants in evals eventually. You don't have to address it in this PR, it seems like a bigger change

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:253]: Sure, let's throw :) Increases re-usability of this test util.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java]: I realized this is also used in the shadowing branch, but as `field.child()`, d'oh. I think I'll just leave this here but make sure to actually use it in more than 1 branch :D

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java (hunk 6 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProjectTests.java:30]: We're so inconsistent with this across test files :D

I'll go with a `<pre>{@code`, so it actually renders nicely.

**Comment by alex-spies** [comment]
> I wonder if we can refactor it somehow, e.g. have a method that does just the aliasing, have a method that does just the renaming, have a method that builds the final output.

I think a multi-pass approach could be easier to read, but would likely take another day to refactor :/ Conceptually, we could ignore shadowing in a first pass and just turn the Eval into a `EVAL | PROJECT` (with potentially broken dependencies between the two commands), based just on the original Eval's output, where the Project has all the renames baked in. And then, in a second pass, we could check which attributes that the Project still needs are shadowed by the Eval, and thus need to be renamed in the Eval (and, accordingly, referred to differently by the Project).

It's still complex though :/ The root problem is that our optimizer rules need to deal with shadowing in the first place, because our name conflict resolution still is always taken into account in LogicalPlans, not only during the initial resolution.

If you see a nicer way that'd work, feel free to go for it! For now, I just need this to be correct so that I can unmute the generative tests again.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java (hunk 12 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceAliasingEvalWithProject.java:30]: There's a separate approach to this optimizer rule, which would inline all eval expressions in a first step, and then can very simply extract any simple renames into a project.

This would side step all the shadowing shenanigans and would address your [comment below](https://github.com/elastic/elasticsearch/pull/137025#pullrequestreview-3377856549).

It would have interesting behavior because, in a way, it'd do the opposite of extracting common expressions in EVALs, which we may want to implement in the future. E.g. `EVAL x = to_lower(y), z1 = length(x), z2 = starts_with("foo", x)` - this eval re-uses `x` and inlining it into `z1` and `z2` would make us re-compute it unnecessarily. OTOH, this would allow for simplifications like simplifying `salary = salary+1, salary = salary +1, salary = salary +1` into `salary+3`.

I'm not sure we want to jump on this right now, but maybe it'll become useful in the future, or if we find that our eval expressions bottleneck queries and need to be optimized better.

**Comment by alex-spies** [comment]
Thanks for the reviews @bpintea and @julian-elastic !

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/137316)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/137318)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
