### PR TITLE
Harden periodically check to avoid endless flush loop

### LINKED ISSUE #29097: Elasticsearch 6.2.2 nodes crash after reaching ulimit setting
Hi,

We're experiencing a critical production issue in elasticsearch 6.2.2 related to open_file_descriptors. The cluster is an exact replica (as much as possible) of a 5.2.2 cluster, and documents are indexed into both clusters in parallel.
While the indexing performance of the new cluster seems to be at least as good as the 5.2.2 cluster, the new nodes open_file_descriptors is reaching record-breaking levels (especially when compared to v5.2.2).

**Elasticsearch version**
6.2.2

**Plugins installed**:
ingest-attachment
ingest-geoip
mapper-murmur3
mapper-size
repository-azure
repository-gcs
repository-s3

**JVM version**:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version**:
Linux 4.13.0-1011-azure #14-Ubuntu SMP 2018 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

All machines have ulimit of 65536, as recommended by the official documentation.
All nodes on the v5.2.2 cluster have up to 4,500 open_file_descripors, while the new v6.2.2 nodes are divided: some have up to 4,500 open_file_descriptors, while others consistently open more and more file descriptors until reaching the limit and crashing with java.nio.file.FileSystemException: Too many open files -

> [WARN ][o.e.c.a.s.ShardStateAction] [prod-elasticsearch-master-002] [newlogs_20180315-01][0] received shard failed for shard id [[newlogs_20180315-01][0]], allocation id [G8NGOPNHRNuqNKYKzfiPcg], primary term [0], message [shard failure, reason [already closed by tragic event on the translog]], failure [FileSystemException[/mnt/nodes/0/indices/nIgarkzwRwe0DmT-nmLhvg/0/translog/translog.ckp: Too many open files]]
java.nio.file.FileSystemException: /mnt/nodes/0/indices/nIgarkzwRwe0DmT-nmLhvg/0/translog/translog.ckp: Too many open files
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:287) ~[?:1.8.0_151]
        at java.nio.channels.FileChannel.open(FileChannel.java:335) ~[?:1.8.0_151]
        at org.elasticsearch.index.translog.Checkpoint.write(Checkpoint.java:179) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.translog.TranslogWriter.writeCheckpoint(TranslogWriter.java:419) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.translog.TranslogWriter.syncUpTo(TranslogWriter.java:362) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.translog.Translog.ensureSynced(Translog.java:699) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.translog.Translog.ensureSynced(Translog.java:724) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard$3.write(IndexShard.java:2336) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.processList(AsyncIOProcessor.java:107) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.drainAndProcess(AsyncIOProcessor.java:99) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:82) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.sync(IndexShard.java:2358) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportWriteAction$AsyncAfterWriteAction.run(TransportWriteAction.java:362) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.<init>(TransportWriteAction.java:160) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:133) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:110) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:72) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1034) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1012) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:103) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:359) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:299) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:975) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:972) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2220) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:984) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:98) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:320) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:295) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:282) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

After this exception, some of the nodes throw many exceptions and reduce the number of open file descriptors. Other times they just crash. The issue repeats itself with interleaving nodes.

**Steps to reproduce**:
None yet. This is a production-scale issue, so it is not easy to reproduce.

I'd be happy to provide additional details, whatever is needed.

Thanks!

### PR DESCRIPTION
**Pull request by dnhatn**
In #28350, we fixed an endless flushing loop which may happen on replicas by tightening the relation between the flush action and the periodically flush condition.

1. The periodically flush condition is enabled only if it is disabled after a flush.

2. If the periodically flush condition is enabled then a flush will actually happen regardless of Lucene state.

(1) and (2) guarantee a flushing loop will be terminated. Sadly, the condition 1 can be violated in edge cases as we used two different algorithms to evaluate the current and future uncommitted translog size.

- We use method `uncommittedSizeInBytes` to calculate current uncommitted size. It is the sum of translogs whose generation at least the minGen (determined by a given seqno). We pick a continuous range of translogs since the minGen to evaluate the current uncommitted size.

- We use method `sizeOfGensAboveSeqNoInBytes` to calculate the future uncommitted size. It is the sum of translogs whose maxSeqNo at least the given seqNo. Here we don't pick a range but select translog one by one.

Suppose we have 3 translogs `gen1={#1,#2}, gen2={}, gen3={#3} and seqno=#1`, `uncommittedSizeInBytes` is the sum of gen1, gen2, and gen3 while `sizeOfGensAboveSeqNoInBytes` is the sum of gen1 and gen3. Gen2 is excluded because its maxSeqno is still -1.

This commit removes both `sizeOfGensAboveSeqNoInBytes` and  `uncommittedSizeInBytes` methods, then enforces an engine to use only `sizeInBytesByMinGen` method to evaluate the periodically flush condition.

Closes #29097
Relates ##28350

### CODE REVIEW

**Review by bleskes — CHANGES_REQUESTED** [review]
This is a great catch. The source of this is Too-Many-Ways-To-Do-The-Same-Thing and I don't think we quite removed it. I.e., the translog still exposes different methods that do slightly different things and it's highly likely this will happen again. This is caused by the attempt to transition into a sequence numbers based translog recovery related API. I don't think it will happen soon and I don't feel happy with leaving the hybrid state as is (we can do a full transition when and if we're ready).  

I suggest removing the translog's uncommittedOps and uncommittedBytes and only expose the sizeInBytesByMinGen and a new equivalent totalOpsByMinGen. The engine will  have to do the sequence number juggling using the getMinGenerationForSeqNo method. The API will feel less friendly but at least the logic is not spread out in multiple methods. 

I also think we can have a stronger test - set the flush threshold to something smallish and the randomly index and flush (both based on a periodic check and just because). After each flush we should check that shouldPeriodicallyFlush returns false.  

WDYT?

**Comment by dnhatn** [comment]
@bleskes 
> I suggest removing the translog's uncommittedOps and uncommittedBytes and only expose the sizeInBytesByMinGen and a new equivalent totalOpsByMinGen.

Yes, I will definitely give this a try.
> I also think we can have a stronger test - set the flush threshold to something smallish and the randomly index and flush (both based on a periodic check and just because). After each flush we should check that shouldPeriodicallyFlush returns false.

Ok, I will add a new test for this.

**Comment by dnhatn** [comment]
@bleskes I've removed both uncommittedOps and uncommittedBytes methods from translog and added a stress test for shouldPeriodicallyFlush. This test was failed around 25% without the patch. Please have a look, thank you!

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -1383,19 +1384,20 @@ final boolean tryRenewSyncCommit() {
...
-         * the `uncommittedSize` of the current commit. This method is to maintain translog only,
-         * thus the IndexWriter#hasUncommittedChanges condition is not considered.
+         * We should only flush ony if the shouldPeriodicallyFlush condition can become false after flushing.
+         * This condition will change if the new commit points to the later translog generation than the current commit's.
+         * This method is to maintain translog only, thus the IndexWriter#hasUncommittedChanges condition is not considered.
          */
-        final long uncommittedSizeOfNewCommit = translog.sizeOfGensAboveSeqNoInBytes(localCheckpointTracker.getCheckpoint() + 1);
-        return uncommittedSizeOfNewCommit < uncommittedSizeOfCurrentCommit;
+        final long translogGenerationOfNewCommit =
+            translog.getMinGenerationForSeqNo(localCheckpointTracker.getCheckpoint() + 1, false).translogFileGeneration;
```
Comment (bleskes) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I'm not happy with the extra boolean flag to include / exclude the current generation as a fall back. It's too subtle an error prone. How about doing the following (I think you had it in the passed and we moved away from it towards the uncommittedX api - sorry for that):
1) If the min gen for the local checkpoint + 1 is > current committed gen , return true.
2) If the min gen is equal to the *current* translog gen, the current gen is not empty  (using `totalOperationsByMinGen`) and the local checkpoint is equal to the max seq#, return true.

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 2]
```diff
@@ -4252,39 +4257,113 @@ public void testCleanupCommitsWhenReleaseSnapshot() throws Exception {
...
+                try {
+                    if (rarely() || engine.getTranslog().shouldRollGeneration()) {
+                        engine.rollTranslogGeneration();
+                    }
+                    if (engine.shouldPeriodicallyFlush()) {
+                        engine.flush();
+                        assertThat(engine.shouldPeriodicallyFlush(), equalTo(false));
+                    }
+                } catch (EngineException ex) {
+                    // This happened because the test may have opened too many files (max 2048 fds on test)
```
Comment (bleskes) [inline server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: this is no good :) maybe change the retention policy to clean up?

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 3]
```diff
@@ -4252,39 +4257,113 @@ public void testCleanupCommitsWhenReleaseSnapshot() throws Exception {
...
+        final long generationThreshold = randomLongBetween(1000, 5000);
+        final IndexSettings indexSettings = engine.config().getIndexSettings();
+        final IndexMetaData indexMetaData = IndexMetaData.builder(indexSettings.getIndexMetaData())
+            .settings(Settings.builder().put(indexSettings.getSettings())
+                .put(IndexSettings.INDEX_TRANSLOG_GENERATION_THRESHOLD_SIZE_SETTING.getKey(), generationThreshold + "b")
+                .put(IndexSettings.INDEX_TRANSLOG_FLUSH_THRESHOLD_SIZE_SETTING.getKey(), flushThreshold + "b")).build();
+        indexSettings.updateIndexMetaData(indexMetaData);
+        engine.onSettingsChanged();
+        final int iterations = scaledRandomIntBetween(100, 1000);
+        final List<Long> pendingSeqNo = new ArrayList<>();
```
Comment (bleskes) [inline server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: maybe instead of pendingSeqNo, randomg take a seq# from the range (localCheckpoint:localCheckpoint+5] ?

**Review by bleskes — CHANGES_REQUESTED** [review]
Thanks @dnhatn . I think this is the right approach. Test looks much better. I left more comments.

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java (hunk 3 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: Boaz, thanks for this hint. This change makes the test failed more than 50% without the patch and also fixed the file descriptor issue.

**Comment by dnhatn** [comment]
@bleskes I've addressed your comments. Can you have another look? Thank you!

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 4]
```diff
@@ -1383,19 +1384,21 @@ final boolean tryRenewSyncCommit() {
...
-        if (uncommittedSizeOfCurrentCommit < flushThreshold) {
+        if (translog.sizeInBytesByMinGen(translogGenerationOfLastCommit) < flushThreshold) {
             return false;
         }
         /*
-         * We should only flush ony if the shouldFlush condition can become false after flushing.
-         * This condition will change if the `uncommittedSize` of the new commit is smaller than
-         * the `uncommittedSize` of the current commit. This method is to maintain translog only,
-         * thus the IndexWriter#hasUncommittedChanges condition is not considered.
+         * We should only flush ony if the shouldFlush condition can become false after flushing. This condition will change if:
```
Comment (bleskes) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: nit - we flush also it will reduce the size of uncommitted gens but strictly speaking it doesn't mean it will be below the threshold

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 5]
```diff
@@ -1383,19 +1384,21 @@ final boolean tryRenewSyncCommit() {
...
+         * 1. The new commit points to the later generation the last commit's.
+         * 2. The local checkpoint equals to max_seqno. This makes the new commit point to the newly rolled translog generation.
+         * This method is to maintain translog only, thus the IndexWriter#hasUncommittedChanges condition is not considered.
          */
-        final long uncommittedSizeOfNewCommit = translog.sizeOfGensAboveSeqNoInBytes(localCheckpointTracker.getCheckpoint() + 1);
-        return uncommittedSizeOfNewCommit < uncommittedSizeOfCurrentCommit;
+        final long translogGenerationOfNewCommit =
+            translog.getMinGenerationForSeqNo(localCheckpointTracker.getCheckpoint() + 1).translogFileGeneration;
+        return translogGenerationOfLastCommit < translogGenerationOfNewCommit
```
Comment (bleskes) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: can you add a comment that if `translogGenerationOfLastCommit== translogGenerationOfNewCommit` and `localCheckpointTracker.getCheckpoint() == localCheckpointTracker.getMaxSeqNo()` we know that the last generation *must* contain operation as it's size is above the threshold and the threshold is guaranteed to be higher than an empty translog gen by the setting validation. Therefore, flushing will improve things. This is tricky to figure out (which is why I didn't like this approach originally).

Comment (bleskes) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: PS - as far as I can tell this can *only* happen if the translog generation file size limit is close or above to the flush threshold and we can end up here if one indexes faster then it takes to roll generations. If that's true, can you add this to the comment? This just too subtle but I can't see how to avoid it.

File: server/src/main/java/org/elasticsearch/index/translog/Translog.java [hunk 6]
```diff
@@ -358,24 +358,17 @@ public long getMinFileGeneration() {
...
-    public int uncommittedOperations() {
-        return totalOperations(deletionPolicy.getTranslogGenerationOfLastCommit());
-    }
-
-    /**
-     * Returns the size in bytes of the translog files that aren't committed to lucene.
-     */
-    public long uncommittedSizeInBytes() {
-        return sizeInBytesByMinGen(deletionPolicy.getTranslogGenerationOfLastCommit());
+    public long uncommittedGeneration() {
```
Comment (bleskes) [inline server/src/main/java/org/elasticsearch/index/translog/Translog.java]: can this be removed (preferably) or made package private for testing? I don't want production code to use this - it just adds circular dependencies.

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 7]
```diff
@@ -4252,39 +4257,80 @@ public void testCleanupCommitsWhenReleaseSnapshot() throws Exception {
...
+                .put(IndexSettings.INDEX_TRANSLOG_FLUSH_THRESHOLD_SIZE_SETTING.getKey(), flushThreshold + "b")).build();
+        indexSettings.updateIndexMetaData(indexMetaData);
+        engine.onSettingsChanged();
+        final int numOps = scaledRandomIntBetween(100, 10_000);
+        for (int i = 0; i < numOps; i++) {
+            final long localCheckPoint = engine.getLocalCheckpointTracker().getCheckpoint();
+            final long seqno = randomLongBetween(Math.max(0, localCheckPoint), localCheckPoint + 5);
+            final ParsedDocument doc = testParsedDocument(Long.toString(seqno), null, testDocumentWithTextField(), SOURCE, null);
+            engine.index(replicaIndexForDoc(doc, 1L, seqno, false));
+            if (rarely() || engine.getTranslog().shouldRollGeneration()) {
```
Comment (bleskes) [inline server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: can we sometimes skip rolling generations ? (we should not rely on rolling always happening in the test)

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 8]
```diff
@@ -4252,39 +4257,80 @@ public void testCleanupCommitsWhenReleaseSnapshot() throws Exception {
...
+                engine.rollTranslogGeneration();
+            }
+            if (engine.shouldPeriodicallyFlush()) {
```
Comment (bleskes) [inline server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: can we sometime flush anyway? people may force flush manually and we want to make sure all works

**Review by bleskes — APPROVED** [review]
Thx @dnhatn . I left some nits. Code looks good.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 5 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I've updated the comment.

File: server/src/main/java/org/elasticsearch/index/translog/Translog.java (hunk 6 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/translog/Translog.java]: I've removed this from `Translog` and moved this to `TestTranslog`.

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java (hunk 8 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: Done.

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java (hunk 7 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: Done

**Comment by dnhatn** [comment]
@bleskes Can you take another look?

File: server/src/main/java/org/elasticsearch/index/translog/Translog.java (hunk 6 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/translog/Translog.java]: Finally, I prefer using translog stats :). All removed.

**Comment by dnhatn** [comment]
> PS - as far as I can tell this can only happen if the translog generation file size limit is close or above to the flush threshold and we can end up here if one indexes faster then it takes to roll generations. If that's true, can you add this to the comment? This just too subtle but I can't see how to avoid it.

We can avoid if the default generation is not a factor of the flush threshold (eg. adding an empty translog + N * generations != flush). WDYT?

**Comment by bleskes** [comment]
> We can avoid if the default generation is not a factor of the flush threshold (eg. adding an empty translog + N * generations != flush). WDYT?

I'm not sure I follow. Can you please unpack this?

**Comment by dnhatn** [comment]
@bleskes What happened may be slightly different from your statement. I think an endless loop may have occurred when the uncommitted size is close to the flush threshold, the current generation is also close to the generation threshold, and a faster operation rolls a new generation, then a slower gets into an endless loop. If this is the case, the size of N translog files and an empty translog satisfies these conditions:

- Size of N translog files <= the flush threshold
- Size of N translog files + an empty translog file > the flush threshold

Assuming that there was no manual flush, these conditions should not be satisfied if the generation size is not a factor of the flush threshold.

**Comment by dnhatn** [comment]
Discussed with Boaz on another channel. The last comment is not valid as it's based on the old code while Boaz's on the new code. I've updated comment in https://github.com/elastic/elasticsearch/pull/29125/commits/42402417bd6ae1b39533571bb4256167feeb17f0.
