### PR TITLE
correct behaviour of ContentPath::remove()

### LINKED ISSUE #98327: Wrong behaviour in `ContentPath` while calling `remove()`
`ContentPath` class maintains a variable `index` that has the next available index to write path to. In fact to add a path we did `path[index++] = name;` so we write at index position and increment it afterwards. To remove last path we are doing `path[index--] = null;` this would set to null the next available index position (that is already null) and later subtract 1 from index. This was masked by the fact that when retrieving a path we loop from 0 up until `i < index`, therefore masking the fact that there could have being 'removed' but not null path existing at `index`.

_Originally posted by @piergm in https://github.com/elastic/elasticsearch/pull/97972#discussion_r1287055169_

### PR DESCRIPTION
**Pull request by piergm**
The variable `index` in `ContentPath` contains the next available index
to write a String into an array. The `remove()` function has being 
corrected to `path[--index] = null` in order to remove the last added 
String.
Before it was `path[index--] = null` that was assigning null to the next
available index (that was already null) and afterwards subtracting the 
variable.
This was masked by the fact that when retrieving a path we loop from 0 
up until `i < index`, therefore masking the fact that there could have
 being 'removed' but not null path existing at `path[index]`.

 
closes #98327

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java [hunk 1]
```diff
@@ -24,6 +24,11 @@ public ContentPath() {
         this.sb = new StringBuilder();
     }
 
+    protected String[] getPath() {
+        // used for testing
```
Comment (piergm) [inline server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java:28]: I added this method because I think making the code testable is better than using hacks (Reflection).
But I am open to discuss on this!

File: server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+        assertEquals(path[2], "baz");
+    }
+
+    public void testRemovePath() {
+        ContentPath contentPath = new ContentPath();
+        contentPath.add("foo");
+        String[] path = contentPath.getPath();
+        assertEquals(path[0], "foo");
+        contentPath.remove();
+        assertNull(path[0]);
```
Comment (piergm) [inline server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java:32]: This test would fail without the change in the `remove()` method.

**Review by piergm — COMMENTED** [review]
Some context for reviewers!

File: server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java (hunk 1 above)
Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java:28]: It doesn't have to be `protected` but 'pkg-private' is acceptable.

File: server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    }
+
+    public void testRemovePathException() {
+        ContentPath contentPath = new ContentPath();
+        contentPath.add("foo");
+        contentPath.remove();
+        expectThrows(IndexOutOfBoundsException.class, () -> contentPath.remove());
+    }
+
+    public void testExpandpath() {
```
Comment (benwtrent) [inline server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java:42]: I don't think we should have this test. It sort of relies on an internal implementation detail of how we expand the internal array at a given length.

This test should ensure that the `10` is correctly added to the path, that `path.pathAsText` is correct, and ` contentPath.length()` is correct.

File: server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+import org.elasticsearch.test.ESTestCase;
+
+public class ContentPathTests extends ESTestCase {
+
+    public void testAddPath() {
+        ContentPath contentPath = new ContentPath();
+        contentPath.add("foo");
+        contentPath.add("bar");
+        contentPath.add("baz");
+        String[] path = contentPath.getPath();
```
Comment (benwtrent) [inline server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java:20]: I would prefer that all these tests that call `.getPath()` instead call `.pathAsText()`

The only exception would be `public void testRemovePath() {` that it check for `null` AND that it calls `.pathAsText()`

**Review by benwtrent — COMMENTED** [review]
Some minor comments. I think this is a good change.

File: server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java (hunk 3 above)
Comment (piergm) [reply server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java]: Done! Thanks for the feedback!

File: server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java (hunk 4 above)
Comment (piergm) [reply server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java]: You are right, good catch! I changed all the affected tests. 
Thanks for the review!

File: server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+    }
+
+    public void testPathAsTextAfterRemoveAndMoreAdd() {
+        ContentPath contentPath = new ContentPath();
+        contentPath.add("foo");
+        contentPath.add("bar");
+        contentPath.remove();
+        contentPath.add("baz");
+        assertEquals("foo.baz.qux", contentPath.pathAsText("qux"));
+    }
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/ContentPathTests.java:102]: Thanks for adding these tests! Looks like a good place to add future tests around dotted field name support that auto-flattening requires with #97972 .

**Review by javanna — APPROVED** [review]
LGTM
