### PR TITLE
Stabilize CancellableTasksIT#testRemoveBanParentsOnDisconnect

### LINKED ISSUE #131562: [CI] CancellableTasksIT testRemoveBanParentsOnDisconnect failing
**Build Scans:**
- [elasticsearch-periodic #9447 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/sgxt3dlidwequ)
- [elasticsearch-pull-request #81235 / part-1](https://gradle-enterprise.elastic.co/s/sw4svocepsvei)
- [elasticsearch-intake #25601 / part1](https://gradle-enterprise.elastic.co/s/erzefp46yflbu)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testRemoveBanParentsOnDisconnect" -Dtests.seed=D7A101AA69F3B6D6 -Dtests.locale=wo-SN -Dtests.timezone=America/Grand_Turk -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRemoveBanParentsOnDisconnect'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 3 failures in test testRemoveBanParentsOnDisconnect (0.5% fail rate in 640 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DiannaHohensee**
Ensure that the cluster has a stably elected master node
when the test completes so that the post-test tear-down
check for cluster state consistency across nodes can
succeed.

Closes #131562

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksIT.java [hunk 1]
```diff
@@ -363,6 +363,10 @@ public void testRemoveBanParentsOnDisconnect() throws Exception {
             allowEntireRequest(rootRequest);
             cancelFuture.actionGet();
             ensureBansAndCancellationsConsistency();
+            // This method will call the cluster health API with wait_for_tasks set to Priority#LANGUID. This will ensure that all tasks
```
Comment (joshua-adams-1) [inline server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksIT.java:366]: Did you run this test X times to verify this indeed fixes any race conditions? (Only that since we've unmuted the test, it would be silly if it failed again in two days)

**Review by joshua-adams-1 — APPROVED** [review]
LGTM!

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksIT.java (hunk 1 above)
Comment (DiannaHohensee) [reply server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksIT.java:366]: Thanks for checking. I realize that the context isn't all there in the git issue: some of the discussion occurred [in slack](https://elastic.slack.com/archives/C06FU3FRUAW/p1752875357895739).

I just went ahead and ran it successfully locally on my machine a dozen or so times. It's hard to confirm, since failures usually occur under stressed concurrency conditions.
