### PR TITLE
ESQL: Preserve intermediate aggregation output in local relation

### LINKED ISSUE #100807: ESQL: null layout on ECS schema with WHERE + STATS
Using an [ECS dataset](https://www.elastic.co/guide/en/ecs/current/ecs-file.html), a query like

```
from logs* 
| where user.name is not null
| stats filecount = min(file.size) by host.name
```

in some cases fails with NullPointerExcaption

image (2)

### PR DESCRIPTION
**Pull request by costin**
Data nodes can fold a plan (typically for missing fields) to an empty, local relationship as a logical optimization.
However the context, such as whether the output is an aggregation or not gets lost which is problematic during physical execution since the upstream aggregation expects the intermediate states while the aggregation returns the final ones.

Consider the query: from index | where field is not null | stats c = count()

On shards where the field in the filter does not exist, the filter gets nullified which folds the whole _local_ plan to a LocalRelation returning c as 0.
However the data node should return the intermediate aggregation states (count and seen) - otherwise the query fails with an internal error (NPE) since the expected channel by the exchange is not found.

Fix #100807

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 1]
```diff
@@ -346,10 +348,36 @@ private PhysicalOperation planExchange(ExchangeExec exchangeExec, LocalExecution
     private PhysicalOperation planExchangeSink(ExchangeSinkExec exchangeSink, LocalExecutionPlannerContext context) {
         Objects.requireNonNull(exchangeSinkHandler, "ExchangeSinkHandler wasn't provided");
         var child = exchangeSink.child();
+        // see https://github.com/elastic/elasticsearch/issues/100807 - handle case where the plan has been fully minimized
+        // to a local relation and the aggregate intermediate data erased. For this scenario, match the output the exchange output
+        // with that of the local relation
+
+        if (child instanceof LocalSourceExec localExec) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:355]: The core of this PR

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java [hunk 2]
```diff
@@ -1220,6 +1219,34 @@ public void testUnsupportedTypesOrdinalGrouping() {
...
+        );
+        assertAcked(
+            client().admin()
+                .indices()
+                .prepareCreate("index-2")
+                .setSettings(Settings.builder().put("index.routing.allocation.require._name", node2))
+                .setMapping("field_2", "type=integer")
+        );
+        try (
+            var resp = run("from index-1,index-2 | where field_1 is not null | stats c = count(*), c1 = count(field_1), m = min(field_1)")
```
Comment (costin) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java:1240]: This test fails because the final min aggregation expects the local aggregation to return an int. Instead it returns null since the field is missing.
This causes the following failure:
```
  2> REPRODUCE WITH: gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.EsqlActionIT.testStatsNestFields" -Dtests.seed=B786427DD46396B2 -Dtests.locale=sk-SK -Dtests.timezone=America/Argentina/ComodRivadavia -Druntime.java=17
  2> java.lang.NullPointerException: Cannot invoke "org.elasticsearch.compute.data.IntVector.getPositionCount()" because "min" is null
        at __randomizedtesting.SeedInfo.seed([B786427DD46396B2:E62DFB5E322E8A9D]:0)
        at org.elasticsearch.compute.aggregation.MinIntAggregatorFunction.addIntermediateInput(MinIntAggregatorFunction.java:99)
        at org.elasticsearch.compute.aggregation.Aggregator.processPage(Aggregator.java:40)
        at org.elasticsearch.compute.operator.AggregationOperator.addInput(AggregationOperator.java:79)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:191)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:129)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:285)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

@nik9000 am I missing something? Looks to me that intermediate nulls are not handled inside ungrouped aggs but they are inside grouped ones.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 3]
```diff
@@ -501,18 +503,26 @@ protected LogicalPlan rule(UnaryPlan plan) {
...
         private static LocalSupplier aggsFromEmpty(List<? extends NamedExpression> aggs) {
-            var result = new ArrayList<>(aggs.size());
+            Block[] blocks = new Block[aggs.size()];
+            var blockFactory = BlockFactory.getNonBreakingInstance();
+            int i = 0;
             for (var agg : aggs) {
                 // there needs to be an alias
                 if (agg instanceof Alias a && a.child() instanceof AggregateFunction aggFunc) {
-                    result.add(aggFunc instanceof Count ? 0L : null);
+                    Object value = aggFunc instanceof Count count && (count.foldable() == false || count.fold() != null) ? 0L : null;
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:512]: When does foldable == false and fold() != null ?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 4]
```diff
@@ -346,10 +348,36 @@ private PhysicalOperation planExchange(ExchangeExec exchangeExec, LocalExecution
...
+            var output = exchangeSink.output();
+            var localOutput = localExec.output();
+            if (output.equals(localOutput) == false) {
+                // the outputs are going to be similar except for the bool "seen" flags which are added in
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:359]: Incomplete comment

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java [hunk 5]
```diff
@@ -1884,6 +1915,17 @@ private PhysicalPlan optimizedPlan(PhysicalPlan plan, SearchStats searchStats) {
             return EstimatesRowSize.estimateRowSize(fragment.estimatedRowSize(), localPlan);
         });
 
+        // handle local reduction alignment
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java:1918]: This block of code is identical to the one in [LocalPhysicalPlanOptimizerTests.java](https://github.com/elastic/elasticsearch/pull/100866/files#diff-89f6975cd4e2ea37809dd0ccdcc513c4814f5362b503cd1f6f6a492fffeaaa3f).

**Review by astefan — APPROVED** [review]
LGTM with some small comments.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java:1240]: Raised https://github.com/elastic/elasticsearch/issues/100928

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 3 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:512]: The condition is looking for count(1) but not count(null) which should return null. Thus NOT, count(field)
