### PR TITLE
[ML] Relocating job should not fail if blocked on revert

### LINKED ISSUE #75377: [ML] Anomaly detection job stuck with `revert` block
Found in 7.14.0

**Description of the problem including expected versus actual behavior**:
This bug has been observed after a rolling upgrade from `7.13.4` to `7.14.0`. 

Summary of the situation post-upgrade:
* Job was interrupted by a rolling cluster upgrade while it was still processing historical data 
* ML upgrade mode was enabled before upgrading and disabled after for each node in the cluster
* No job state persisted
* Job ended up blocked with `revert`
* Task described in the `revert` block does not exist
* Job state is `closed`

The only way to recover from this state is to manually revert to the model snapshot with ID `empty`, which will remove the block from the job.

**Steps to reproduce**:
 1. Run an anomaly detection job that takes a long time to process historical data
 2. Disable replica shard allocation & enable ML upgrade mode
 3. Upgrade the node
 4. Enable replica shard allocation & disable ML upgrade mode
 5. Wait for cluster to recover
 6. Notice that anomaly detection job is `closed`, blocked by `revert` and no state is persisted.

⚠️ _Very low reproduction rate_

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
When a job is relocating to a new node it is possible that
it will revert to its current model snapshot in order to
resume gracefully. When the revert action starts, the job
will be marked as blocked on `revert`. If the job then gets
relocated to yet another node, it will try to perform
revert a second time. If the previous revert task is still
running, revert will fail and so will the job too.

Note that this is the behaviour when the master node is
on a version prior to 7.14. From 7.14 onwards, the job
will reset instead of revert to its current snapshot and
that should work without issues as the reset API waits
for existing reset task to complete.

This commit attempts to fix the behavior by making the
revert API wait for existing revert tasks to complete
when the `force` flag is set. During job relocation,
the revert action is called with `force`. If a revert
task exists, it should now wait for it to complete before
attempting a new revert. But as the previous revert task
should now be completed, the job should no longer be blocked.

Fixes #75377

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java [hunk 1]
```diff
@@ -176,6 +176,13 @@ private void isBlocked(Job job, ActionListener<Boolean> listener) {
             // in order to complete and eventually unblock the job.
             GetTaskRequest getTaskRequest = new GetTaskRequest();
             getTaskRequest.setTaskId(job.getBlocked().getTaskId());
+
+            // If the request is forced, we will also wait for the existing task to finish
+            // to give a chance to this request to be executed without returning an error.
+            // This is particularly useful when a relocating job is calling revert.
+            getTaskRequest.setWaitForCompletion(request.isForce());
+            getTaskRequest.setTimeout(request.masterNodeTimeout());
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java:184]: I think this timeout needs to be longer _if_ we are waiting for completion.  We revert with `delete_intervening_results=true`, and that could take a very long time if there are lots of results.  Maybe the timeout could be `MachineLearningField.STATE_PERSIST_RESTORE_TIMEOUT`.

But if we are not waiting for completion then the default timeout should be fine.

**Review by droberts195 — COMMENTED** [review]
I think there is a related problem if a job is in the middle of resetting on a node that gets upgraded during a rolling upgrade, because the rolling upgrade happened while it was running but before it had persisted any state.

In https://github.com/elastic/elasticsearch/blob/dc61a72c9e273ac348422c92ff5bac5da02bd604/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportResetJobAction.java#L101-L102

we are assuming that waiting for the existing task to complete will mean the reset is complete.  But if the existing task has already completed despite the reset block being applied then that probably means the node running the reset task was killed during the reset.  In this case we should do the reset again.  Maybe my reasoning is flawed, and even if it isn't I am happy to leave this aspect for a followup PR, as the problem we've actually observed for real is the revert case that this PR fixes.

I also have one small observation about this PR.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java:184]: We do set the timeout to a large value. In `OpenJobPersistentTaskExecutor.revertToCurrentSnapshot` we set:

```
RevertModelSnapshotAction.Request request = new RevertModelSnapshotAction.Request(jobId,
    jobSnapshotId == null ? ModelSnapshot.EMPTY_SNAPSHOT_ID : jobSnapshotId);
request.setForce(true);
request.setDeleteInterveningResults(true);
request.masterNodeTimeout(PERSISTENT_TASK_MASTER_NODE_TIMEOUT);
```

**Comment by dimitris-athanasiou** [comment]
> But if the existing task has already completed despite the reset block being applied then that probably means the node running the reset task was killed during the reset. In this case we should do the reset again.

I think this is indeed a scenario we should address. I'll try to tackle it in a separate PR.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java:184]: Oh, I see, it's copying the long timeout from the original request to the wait for completion.

I think that's quite unintuitive though, because usually master node timeout is different to just "timeout".

Maybe you can at least add a comment explaining what's going on here: if the revert comes directly from an end user then the master node timeout is likely to be 30 seconds and if it comes from the persistent task executor then will be several days.  So we get the behaviour we want but not in a particular obvious or natural way.

Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportRevertModelSnapshotAction.java:184]: Ah, I see the confusion with master and non-master timeout. Let me see if I can make sense of that.

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Review by droberts195 — APPROVED** [review]
LGTM
