### PR TITLE
Group field caps response by index mapping hash

### LINKED ISSUE #78665: Field caps against many remote clusters consumes substantial heap
**Elasticsearch version** (`bin/elasticsearch --version`): Seen in 7.14.0 but `master` looks affected still

**Plugins installed**: []

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

When running field caps for CCS we broadcast a request to every remote cluster, collect all the responses, and then start to merge them together. We have users with 150+ large remote clusters, and one such user reported a single field caps request which ended up consuming 10+GB of heap with the un-merged responses. It doesn't take many of them to reliably cause their CCS cluster to experience OOMs.

Can we merge the results from remote clusters incrementally, and limit the number of remote cluster requests in flight?

**Steps to reproduce**:

1. Add a few hundred remote clusters each with several hundred indices containing ~1000 fields.
2. Request field caps against all the remote clusters at once.

**Provide logs (if relevant)**:

Link from the internal case will appear below.

### LINKED ISSUE #82879: Merge field caps responses on each node?
We'd like to look into merging field caps responses on each node, to prevent the coordinator from doing all merging. This will help reduce latency and memory when the field caps request includes many shards.

As part of this work, we can see if we could detect when two indices share the same mappings, and in that case skip over the shards with mappings we've already collected. This can help in the case of time-based indices, where most indices may have the same mappings.

This is a spin-off from https://github.com/elastic/elasticsearch/issues/76509#issuecomment-906005419 to capture unresolved work.

### PR DESCRIPTION
**Pull request by dnhatn**
This commit utilizes the index mapping hash to share the fields-caps for indices with the same index mapping to reduce the memory usage and the size of transport messages.

Closes #78665 
Closes #82879

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-2

**Comment by jtibshirani** [comment]
Thanks @dnhatn ! I'll review soon. Am I understanding right that you don't think we should do anything beyond this for remote clusters (https://github.com/elastic/elasticsearch/issues/78665)? For example, we will not try to fully reduce the response on the remote cluster, combining all mappings across indices.

**Comment by dnhatn** [comment]
> I'll review soon. 

Thank you, no worries! It's not urgent.

> Am I understanding right that you don't think we should do anything beyond this for remote clusters (https://github.com/elastic/elasticsearch/issues/78665)? For example, we will not try to fully reduce the response on the remote cluster, combining all mappings across indices.

That's correct. I think this is good enough now. We compact responses from each cluster and between them on the coordinating node.

**Review by jtibshirani — COMMENTED** [review]
I had one high-level question -- instead of what we do in this PR, would it be possible to detect duplicate mappings on the field caps coordinator, before sending all the node/ shard requests? Could this let us avoid sending duplicate requests in the first place, and keep the response merging logic simple?

**Comment by dnhatn** [comment]
Yes, we can apply your suggestion in RequestDispatcher for requests without `indexFilter`. However, we still need the deduplication optimization for cross-clusters requests or requests with `indexFilter`.

**Comment by dnhatn** [comment]
@jtibshirani I can make your suggestion in a follow-up.

**Comment by jtibshirani** [comment]
I see, I forgot that this wouldn't work with `indexFilter`. I think it still works with CCS though, the coordinator on the remote cluster would just apply the same optimization? Sounds good to discuss in a follow-up.

**Comment by dnhatn** [comment]
> I think it still works with CCS though, the coordinator on the remote cluster would just apply the same optimization?

Yes, that's correct, but we still have to deduplicate the response when sending it back to the local cluster.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java [hunk 1]
```diff
@@ -9,34 +9,113 @@
...
+    public void writeTo(StreamOutput out) throws IOException {
+        out.writeString(indexName);
+        out.writeMap(responseMap, StreamOutput::writeString, (valueOut, fc) -> fc.writeTo(valueOut));
+        out.writeBoolean(canMatch);
+        if (out.getVersion().onOrAfter(MAPPING_HASH_VERSION)) {
+            out.writeOptionalString(indexMappingHash);
+        }
+    }
+
+    private record GroupByMappingHash(List<String> indices, String indexMappingHash, Map<String, IndexFieldCapabilities> responseMap)
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java:70]: It seems like this logic belongs more in `FieldCapabilitiesNodeResponse` than here, since it's a serialization choice that the node response makes to cut down on duplicate data.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 2]
```diff
@@ -112,6 +113,16 @@ protected void doExecute(Task task, FieldCapabilitiesRequest request, final Acti
         checkIndexBlocks(clusterState, concreteIndices);
 
         final Map<String, FieldCapabilitiesIndexResponse> indexResponses = Collections.synchronizedMap(new HashMap<>());
+        final Map<String, Map<String, IndexFieldCapabilities>> indexMappingHashToResponses = Collections.synchronizedMap(new HashMap<>());
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:116]: It'd be great to add a comment explaining why we are using this shared map, it wasn't totally clear to me at first.

**Review by jtibshirani — COMMENTED** [review]
This is looking good to me, I left a few small comments. I also wondered if we could use the mapping hashes in `TransportFieldCapabilitiesAction#merge` to avoid merging merging in the same information twice.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:117]: I added a comment in
https://github.com/elastic/elasticsearch/pull/83494/commits/96abec0f5ab9da9823e7184767d0d07c0cc151ac.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java:70]: They should be here as we also use them in [FieldCapabilitiesResponse](https://github.com/dnhatn/elasticsearch/blob/edef31b36e0f876afc3261f701172ac5f025ddc5/server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesResponse.java#L144) to compact cross-cluster responses.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 3]
```diff
@@ -347,6 +360,7 @@ public void messageReceived(FieldCapabilitiesNodeRequest request, TransportChann
                 final Map<String, List<ShardId>> groupedShardIds = request.shardIds()
                     .stream()
                     .collect(Collectors.groupingBy(ShardId::getIndexName));
+                final Map<String, Map<String, IndexFieldCapabilities>> indexMappingHashToResponses = new HashMap<>();
```
[the remark this answers is not in the document]
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java]: Ok, I adjusted this in https://github.com/elastic/elasticsearch/pull/83494/commits/8477939d611ef8eff6de1bf64b7760dc3917f2c0.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 4]
```diff
@@ -112,6 +113,16 @@ protected void doExecute(Task task, FieldCapabilitiesRequest request, final Acti
         checkIndexBlocks(clusterState, concreteIndices);
 
         final Map<String, FieldCapabilitiesIndexResponse> indexResponses = Collections.synchronizedMap(new HashMap<>());
+        final Map<String, Map<String, IndexFieldCapabilities>> indexMappingHashToResponses = Collections.synchronizedMap(new HashMap<>());
+        final Consumer<FieldCapabilitiesIndexResponse> handleIndexResponse = resp -> {
+            if (resp.canMatch() && resp.getIndexMappingHash() != null) {
```
[the remark this answers is not in the document]
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:119]: Unfortunately, we can't assert it. Responses from old nodes don't have index mapping hashes. Also, for indices that don't have index mapping ready yet. See https://github.com/elastic/elasticsearch/blob/c182b0037908663992791a19b01746202b6fe1f1/server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java#L852-L855

**Comment by dnhatn** [comment]
@jtibshirani Thanks for reviewing. I think I've addressed your comments.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java (hunk 1 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java:70]: Okay, then tiny comment but maybe we can move the test to a new class `FieldCapabilitiesIndexResponseTests`.

**Comment by dnhatn** [comment]
> I also wondered if we could use the mapping hashes in TransportFieldCapabilitiesAction#merge to avoid merging merging in the same information twice.

I was looking at this while working on https://github.com/elastic/elasticsearch/pull/83704. It's bit complex as we sort indices for each type in the final response. I can explore it again in a follow-up.

**Review by jtibshirani — APPROVED** [review]
Sounds good to look into the `merge` optimization in a follow-up. This looks good to me. I know @javanna was hoping to take a look too when he had time.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java:70]: +1, will do.

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java:70]: I pushed https://github.com/elastic/elasticsearch/pull/83494/commits/84fd377a1e0727e55377ed686a0c2e5bf694d8a8. Thanks Julie!

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-1

**Comment by dnhatn** [comment]
@jtibshirani Thanks for your review.

**Comment by javanna** [comment]
> I know @javanna was hoping to take a look too when he had time.

Took me a while, but I ended up diving into this :) I think it's a great improvement. One question I have is whether we think we have enough test coverage around the changes we made to the serialization here. I see a different path depending on whether the mapping hash is available, starting from the version that supports it, and I wonder if we should have more tests to cover what happens when nodes with multiple versions that may or may not provide the mapping hash are involved. The logic seems more complex than a simple "serialize the field or not depending on the stream version" hence I get anxious.

**Comment by dnhatn** [comment]
@javanna Thanks for looking. I think we have good coverage with the newly added [test](https://github.com/elastic/elasticsearch/pull/83494/files#diff-40dc29ffbf7838ae2bc852418106954675c5a81a0e17f77773acb661673207f3R33) where we randomly generate index responses with and without mapping hashes and serialize with old and new versions.

**Comment by dnhatn** [comment]
@javanna I am working on some BWC tests for field caps. I will open a PR when they are ready.
