### PR TITLE
Fix StoredFieldsSpec#merge(...) issue

### LINKED ISSUE #138188: ES|QL: METADATA _source doesn't work with text fields
Testing on main:

When I create a basic template like this:
```
PUT _index_template/my-template
{
  "index_patterns": [
    "my-test"
  ],
  "priority": 100,
  "data_stream": {},
  "template": {
    "settings": {
      "sort": {
        "field": [
          "@timestamp"
        ],
        "order": [
          "asc"
        ]
      }
    },
    "mappings": {
      "dynamic": false,
      "properties": {
        "foo": {
          "type": "text"
        }
      }
    }
  }
}
```

and then index a doc:

```
POST my-test/_doc
{
    "@timestamp": "2026",
    "baz": "dasd"
}
```

Then querying with metadata _source doesn't return the source, just an empty object:

```
POST _query
{
  "query": """
    FROM my-test METADATA _source
    """
}
```

returns

```
{
  "took": 5,
  "is_partial": false,
  "documents_found": 1,
  "values_loaded": 2,
  "columns": [
    {
      "name": "@timestamp",
      "type": "date"
    },
    {
      "name": "foo",
      "type": "text"
    },
    {
      "name": "_source",
      "type": "_source"
    }
  ],
  "values": [
    [
      "2026-01-01T00:00:00.000Z",
      null,
      {}
    ]
  ]
}
```

I don't know what's going on, I tested around a bit and it looks like the fact that it's a text field is triggering this - if it's a keyword field it works as expected.

_source is returned completely normal when using `_search`

### PR DESCRIPTION
**Pull request by martijnvg**
If StoredFieldsSpec requires source and has no sourcePaths, then it requires the whole source. For example, in case of `SourceFieldBlockLoader`. When merging StoredFieldsSpec then omit the sourcePaths of the other StoredFieldsSpec.

Closes #138188

(a non released issue)

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java [hunk 1]
```diff
@@ -82,9 +82,17 @@ public StoredFieldsSpec merge(StoredFieldsSpec other) {
             mergedSourcePaths = new HashSet<>(this.sourcePaths);
             mergedSourcePaths.addAll(other.sourcePaths);
         } else if (this.sourcePaths.isEmpty() == false) {
-            mergedSourcePaths = this.sourcePaths;
+            if (other.requiresSource) {
```
Comment (quackaplop) [inline server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java]: Ah! So our intuition was right - every time we apply the filter, we are stripping down the rest of the source. The fix is to always keep the source if it's been asked for

Comment (quackaplop) [reply server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java]: As a side note, there seems to be quite a bit of boiler plate in this method, with some repeated outcomes. Do we want to shove them into separate tiny inlinable functions?

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml [hunk 2]
```diff
@@ -210,3 +210,35 @@ setup:
...
   }}
+
+---
+"source meta field and dynamic false":
+  - do:
+      indices.create:
+        index: my-index2
+        body:
+          mappings:
+            dynamic: false
```
Comment (quackaplop) [inline x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml:224]: Is this important? The `dynamic` I mean

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml [hunk 3]
```diff
@@ -210,3 +210,35 @@ setup:
...
+      bulk:
+        index: my-index2
+        refresh: true
+        body:
+          - { "index": { } }
+          - { "baz": "dasd" }
+  - do:
+      esql.query:
+        body:
+          query: 'FROM my-index2 METADATA _source | LIMIT 10'
```
Comment (quackaplop) [inline x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml:239]: Not to be annoying, but are we testing here with what we actually want to be testing?

Here we seem to have an index with a single text field, so even if we had not fixed the bug, I think this still would've worked, right - we would've stripped the source of everything but the field, which doesn't actually change the _source.

Feels like we need the mapping with at least one another field, and the query that reads the entire source and the text field. We should be testing that the filtered out field is still returned in source

This thing - https://github.com/elastic/elasticsearch/issues/138188 - has the correctly shaped example I think.

**Comment by quackaplop** [comment]
Also on the `(a non released issue)` - this has been out in Serverless all this time, so sadly customers have been exposed to this. I don't know if it's changing much in terms of the path forward though

File: server/src/test/java/org/elasticsearch/search/fetch/StoredFieldsSpecTests.java [hunk 4]
```diff
@@ -120,7 +120,7 @@ public void testMergeSourcePaths() {
 
         spec = spec.merge(
             new StoredFieldsSpec(
-                true,
+                false,
```
Comment (quackaplop) [inline server/src/test/java/org/elasticsearch/search/fetch/StoredFieldsSpecTests.java]: So this may be silly question, but it seems like we very much changed the meaning of this test, right? The way I read this, we changed `requiresSource` to false, which - in some sense - triggers the "pre-bug" behavior. This makes sense.
Should we add a mirror test with this flag set to true?

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml (hunk 3 above)
Comment (martijnvg) [reply x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml:239]: > Here we seem to have an index with a single text field, so even if we had not fixed the bug, I think this still would've worked, right - we would've stripped the source of everything but the field, which doesn't actually change the _source.

Without the fix to `StoredFieldSpec` this test fails. 

I can add a `@timestamp` field, but that doesn't change the outcome of the test.

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml (hunk 2 above)
Comment (martijnvg) [reply x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml:224]: For the query being tested here, yes. Otherwise the test wouldn't fail.
The `FROM my-index2 METADATA _source | LIMIT 10` requests all mapped fields, but because `baz` isn't mapped without the fix to StoredFieldSpec, we would filter it out. If the `baz` field was mapped, the stored field spec of the other column would include it in the final stored field spec.

File: server/src/test/java/org/elasticsearch/search/fetch/StoredFieldsSpecTests.java (hunk 4 above)
Comment (martijnvg) [reply server/src/test/java/org/elasticsearch/search/fetch/StoredFieldsSpecTests.java]: The test just walks through a few scenarios and I just appended the scenario that triggered the bug. I can add a dedicated unit test for the bug here.

File: server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java]: Let me see if that actually makes to code cleaner.

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml (hunk 3 above)
Comment (martijnvg) [reply x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/140_metadata.yml:239]: I added another test here that shows that `dynamic: false` isn't required to run into the bug. Just excluding the field that is in source is sufficient to reproduce the bug. 

The problem is inherent to stored field spec filtering, which didn't take into account that en empty source path means the full source is needed. Which is the case for `SourceFieldBlockLoader`.

File: server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java [hunk 5]
```diff
@@ -114,6 +104,29 @@ public StoredFieldsSpec merge(StoredFieldsSpec other) {
         );
     }
 
+    private Set<String> mergeSourcePaths(StoredFieldsSpec other) {
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/search/fetch/StoredFieldsSpec.java:111]: `Set.of()` here indicates no source filtering and so we should be returning the full source, right?  Maybe add something to the top-level javadoc to make that clearer.

**Review by romseygeek — APPROVED** [review]
LGTM

**Review by jordan-powers — APPROVED** [review]
LGTM, thanks Martijn!
