### PR TITLE
ESQL: Fix null comparison type checking

### LINKED ISSUE #140460: ESQL: NULL type not working with binary comparisons
Reproducer:

```
ROW x = null, y = "foo" | WHERE x == y

{"error":{"root_cause":[{"type":"verification_exception","reason":"Found 1 problem\nline 1:33: first argument of [x == y] is [null] so second argument must also be [null] but was [keyword]"}],"type":"verification_exception","reason":"Found 1 problem\nline 1:33: first argument of [x == y] is [null] so second argument must also be [null] but was [keyword]"},"status":400}%   
```

Generally, our functions and operators take the `NULL` data type just fine, so we're being inconsistent here.

### PR DESCRIPTION
**Pull request by kanoshiou**
This PR fixes an issue where comparing `null` with other types incorrectly produced a type incompatibility error. 

For example, `ROW x = null, y = 1 | WHERE x == y` would fail with a type error instead of correctly evaluating to `null`. Null should be compatible with any type and evaluate to null at runtime, matching the behavior of `EsqlBinaryComparison.checkCompatibility`.

Fixes #140460

### CODE REVIEW

**Comment by astefan** [comment]
buildkite test this

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 1]
```diff
@@ -241,12 +242,10 @@ private static List<BiConsumer<LogicalPlan, Failures>> planCheckers(LogicalPlan
     private static void checkOperationsOnUnsignedLong(LogicalPlan p, Failures failures) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:254]: I suggest the following change to this method (simplified and with a better comment):

```
    /**
     * This validates only the negation operator, the rest of the validation is performed in
     * {@link org.elasticsearch.xpack.esql.analysis.Verifier#validateBinaryComparison(BinaryComparison)}
     * and
     * {@link org.elasticsearch.xpack.esql.expression.predicate.operator.comparison.EsqlBinaryComparison#areTypesCompatible(DataType, DataType)}
     */
    private static void checkOperationsOnUnsignedLong(LogicalPlan p, Failures failures) {
        p.forEachExpression(Neg.class, neg -> {
            Failure f = validateUnsignedLongNegation(neg);
            if (f != null) {
                failures.add(f);
            }
        });
    }
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 2]
```diff
@@ -360,18 +359,25 @@ public XPackLicenseState licenseState() {
...
+        return fail(bc, formatIncompatibleTypesMessage(bc.left().dataType(), bc.right().dataType(), bc.sourceText()));
+    }
+
+    /**
+     * Check that the left operand of a binary comparison is of an allowed type.
+     * This validates that the comparison operation is supported for the given data types.
+     *
+     * @return a Failure if the left operand type is not allowed, null otherwise
+     */
+    private static Failure checkBinaryComparisonTypes(BinaryComparison bc) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java]: Change the name of this method accordingly, since now it looks only at the left side of a binary comparison.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 3]
```diff
@@ -399,50 +405,6 @@ public static Failure validateBinaryComparison(BinaryComparison bc) {
...
-                bc.sourceText(),
-                bc.left().dataType().typeName(),
-                bc.left().dataType().typeName(),
-                bc.right().dataType().typeName()
-            );
-        }
-        return null;
-    }
-
-    /** Ensure that UNSIGNED_LONG types are not implicitly converted when used in arithmetic binary operator, as this cannot be done since:
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:430]: Save this comment somewhere, since it's valuable information regarding unsigned_long types compatibility.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 4]
```diff
@@ -859,6 +859,48 @@ public void testUnsignedLongNegation() {
         );
     }
 
+    /**
+     * Test that null comparisons are valid and don't produce type incompatibility errors.
+     * Null should be compatible with any type in binary comparisons.
+     */
+    public void testNullComparisonValidation() {
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:866]: Consider adding tests comparing `unsigned_long` with `null` as well.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/null.csv-spec [hunk 5]
```diff
@@ -216,3 +216,148 @@ emp_no:integer | first_name:keyword | last_name:keyword
 10021          | Ramzi              | Erde
 10022          | Shahaf             | Famili
 ;
+
+###############################################
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/null.csv-spec:220]: Add more complex tests that get a `null` from an operation for example.
`row x = null, y = 1, z = 2 | eval t = x + 1 > z`

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 6]
```diff
@@ -873,11 +915,6 @@ public void testWrongInputParam() {
             "1:19: first argument of [emp_no == ?] is [numeric] so second argument must also be [numeric] but was [keyword]",
             error("from test | where emp_no == ?", "foo")
         );
-
-        assertEquals(
-            "1:19: first argument of [emp_no == ?] is [numeric] so second argument must also be [numeric] but was [null]",
-            error("from test | where emp_no == ?", new Object[] { null })
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:879]: Don't remove this query entirely, but move it to the method above and validate that a param `null` is still being passed correctly.

**Review by astefan — COMMENTED** [review]
I think the fix is ok, but it needs more refining before merge:
- in `In:242` the comment is no longer accurate. That specific method has been removed.
- check any csv-spec tests that we have for `unsigned_long`, `null` and `in`. If we don't have  any, please add some. I would start with `unsigned_long.csv-spec`.
- same ask as the previous one, but for tests that use `null` in boolean logical operations, for example `from ul_logs | eval x = null OR bytes_in > null` or `from ul_logs | eval x = null or bytes_in > 2::unsigned_long`

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unsigned_long.csv-spec [hunk 7]
```diff
@@ -205,3 +205,252 @@ v:ul
...
+required_capability: fix_null_comparison_type_check
+
+FROM ul_logs | WHERE bytes_in == null | KEEP id, bytes_in | SORT id | LIMIT 5
+;
+
+id:integer | bytes_in:ul
+;
+
+
+# unsigned_long field not equal to null with WHERE (null rows filtered out)
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unsigned_long.csv-spec]: This filters out all rows not only "null rows".

**Comment by kanoshiou** [comment]
Thanks for the patches, @astefan.

Actually, this removal doesn't address these failures. `":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {csv-spec:unsigned_long.UnsignedLongInWithNull}"` would still fail. Issue #139262 is currently tracking the "missing warning" problem. 

I previously ran `EsqlSpecIT` but skipped `CsvTests`,  and now I believe adding the necessary regex escape characters (\\) should resolve the current failures.

But I am not quite sure if  `AssertWarnings.AllowedRegexes#assertWarnings` is doing the right job because it is skipped if there are no warnings.

**Comment by kanoshiou** [comment]
Thanks for the guidance, @astefan.

The Javadocs were really helpful and cleared up my confusion about the inconsistent test results. I’ve updated the test to match your suggestion. Since there appear to be other non-deterministic tests as well, I’d be happy to address those in a separate PR if you'd like.

**Review by astefan — APPROVED** [review]
LGTM
