### PR TITLE
Fix Concurrent Snapshot Repository Corruption from Operations Queued after Failing Operations

### LINKED ISSUE #75598: Aborting a Snapshot Queued after a Finalizing Snapshot is Broken
There is a bug in the concurrent snapshot logic where the following situation involving three concurrent snapshots and a snapshot delete is broken and may lead to writing corrupted repository metadata:

1. Start 3 snapshots for the same two indices
2. Abort the one in the middle before after the first snapshot finishes on the data node (as far as writing to the repository goes) but before the index gets out of the queued state for the second snapshot
3. third snapshot is moved started once the middling snapshot completes to `FAILED` state but has `null` for the shard generation for shards in the shared index

This is a fairly unlikely scenario to run into since the abort must be timed just right, but it's somewhat more likely if the second snapshot has a larger diff with the first snapshot (so writing the files takes longer ... though even in this scenario the CS with hte abort has to be applied on the data node right after finishing the last file).
=> fixing this asap but probably not before next week

### PR DESCRIPTION
**Pull request by original-brownbear**
The node executing a shard level operation would in many cases communicate `null` for the shard state update,
leading to follow-up operations incorrectly assuming an empty shard snapshot directory and starting from scratch.

This change fixes the logic on the side of the node executing the shard level operation and reproduces the issue in one case. The exact case in the linked issue is very hard to reproduce unfortunately because it required very specific timing that our test infra currently does easily enable). This should also be fixed in the master node logic (to make the code more obviously correct and fix mixed-version clusters better) but I'd like to delay that and do it in #75501 because of how tricky (as in lots of confusing code for clones and snapshots and so on) it would be to figure out the correct generation from the cluster-state without that refactoring.

closes #75598

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java [hunk 1]
```diff
@@ -256,6 +256,10 @@ public static void blockDataNode(String repository, String nodeName) {
         AbstractSnapshotIntegTestCase.<MockRepository>getRepositoryOnNode(repository, nodeName).blockOnDataFiles();
     }
 
+    public static void blockAndFailDataNode(String repository, String nodeName) {
```
Comment (original-brownbear) [inline test/framework/src/main/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java:259]: The fact that we didn't have this logic revealed an unfortunate lack of test coverage. We have a number of tests that simulate data-node failure but they're all based on blocking the data-node via the existing block-and-wait and then shutting down the blocked data nodes which triggers a very different code path on master.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -741,7 +741,12 @@ private void runReadyClone(
                         new ShardSnapshotUpdate(
                             target,
                             repoShardId,
-                            new ShardSnapshotStatus(localNodeId, ShardState.FAILED, "failed to clone shard snapshot", null)
+                            new ShardSnapshotStatus(
+                                localNodeId,
+                                ShardState.FAILED,
+                                "failed to clone shard snapshot",
+                                shardStatusBefore.generation()
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:748]: Can we shift some of the `@Nullable` annotations and associated assertions around in `ShardSnapshotStatus`? With this change I think we might still receive a null generation over the wire from an older version, but we shouldn't be creating them afresh any more?

**Review by DaveCTurner — COMMENTED** [review]
Nice catch, I asked for some slightly tighter assertions if possible.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:748]: In fact we ought to change the wire format so it's no longer an `OptionalString`. I'm ok with not doing that here, it'll make the backport that much harder, a follow up is fine.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:748]: We would in fact still create them for pre-7.6 state machine operation (still a thing if there's an old snapshot in your repo) and we don't have access to the snapshot version in these constructors. In these `null` means (figure out the numeric generation yourself which would happen to a queued operation if e.g. the first operation for a shard in the CS fails).

Let me see what I can do about this though :)

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:748]: Bad news here I'm afraid. I had to remove the assertion since it didn't hold up but it's also really hard to assert this elsewhere due to the BwC situation.
If it's ok with you I think I'd rather look for a cleaner way of asserting this stuff once #75501 has landed (or actually as part of incorporating this into that change) and just assert that we're not doing any illegal changes to `SnapshotsInProgress` like this any longer (much easier if we don't have to hack around translating `ShardId` and `RepoShardId` all over the place)?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:748]: Sure, thanks for looking. Blasted BwC, always spoiling the fun.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!
