### PR TITLE
[ES|QL] Fix broken CSV tests for text embedding

### LINKED ISSUE #136090: [CI] EsqlSpecIT test {csv-spec:text-embedding.Text_embedding with multiple knn queries in fork} failing
**Build Scans:**
- [elasticsearch-intake #29683 / part3](https://gradle-enterprise.elastic.co/s/yc7suuefgflxi)
- [elasticsearch-pull-request #97172 / part-3](https://gradle-enterprise.elastic.co/s/kdxymtu326v2s)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:text-embedding.Text_embedding with multiple knn queries in fork}" -Dtests.seed=A15BE902DF8D340F -Dtests.locale=ca-IT -Dtests.timezone=Australia/LHI -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Atext-embedding.Text_embedding%20with%20multiple%20knn%20queries%20in%20fork%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.apache.http.ConnectionClosedException: Connection is closed
```

**Issue Reasons:**
- [main] 2 failures in test test {csv-spec:text-embedding.Text_embedding with multiple knn queries in fork} (6.3% fail rate in 32 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #136142: [CI] GenerativeForkIT test {csv-spec:text-embedding.Text_embedding with knn (inline) on semantic_text_dense_field} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11050 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/vmko3l7jbvaqs)
- [elasticsearch-pull-request #97171 / part-3](https://gradle-enterprise.elastic.co/s/xfrbj4cywgeue)
- [elasticsearch-pull-request #97150 / part-3](https://gradle-enterprise.elastic.co/s/qc5dwbn3lw6tu)
- [elasticsearch-pull-request #97150 / part-3](https://gradle-enterprise.elastic.co/s/55tn4u2th64y6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.GenerativeForkIT" -Dtests.method="test {csv-spec:text-embedding.Text_embedding with knn (inline) on semantic_text_dense_field}" -Dtests.seed=F6349C4B3C4ACF40 -Dtests.locale=lo -Dtests.timezone=Asia/Tehran -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.GenerativeForkIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Atext-embedding.Text_embedding%20with%20knn%20(inline)%20on%20semantic_text_dense_field%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.apache.http.ConnectionClosedException: Connection is closed
```

**Issue Reasons:**
- [main] 4 failures in test test {csv-spec:text-embedding.Text_embedding with knn (inline) on semantic_text_dense_field} (3.0% fail rate in 134 executions)
- [main] 3 failures in step part-3 (4.3% fail rate in 69 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.9% fail rate in 68 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by afoucret**
Fix bug in CSV tests when several function embedding are present in the same plan.

Fixes #136142
Fixes #136108
Fixes #136090
Fixes #136234

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/inference/InferenceFunctionEvaluator.java [hunk 1]
```diff
@@ -123,26 +123,28 @@ public CircuitBreakerStats stats(String name) {
...
+                        Page output = inferenceOperator.getOutput();
+
                         if (output == null) {
                             l.onFailure(new IllegalStateException("Expected output page from inference operator"));
                             return;
                         }
 
+                        output.allowPassingToDifferentDriver();
+                        l = ActionListener.releaseBefore(output, l);
+
```
Comment (afoucret) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/inference/InferenceFunctionEvaluator.java:137]: ℹ️ Better handling of the output page release. Now automatically called when the listener is called.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/inference/InferenceFunctionEvaluatorTests.java [hunk 2]
```diff
@@ -62,7 +68,23 @@ public void testFoldTextEmbeddingFunction() throws Exception {
         // Create a mock operator that returns a result
         Operator operator = mock(Operator.class);
 
-        Float[] embedding = randomArray(1, 100, Float[]::new, ESTestCase::randomFloat);
+        float[] embedding = randomEmbedding(between(1, 100));
```
Comment (afoucret) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/inference/InferenceFunctionEvaluatorTests.java:71]: Made the tests really asynchronous (more reallistic)

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/text-embedding.csv-spec [hunk 3]
```diff
@@ -69,6 +69,25 @@ live long and prosper
 all we have to decide is what to do with the time that is given to us
 ;
 
+text_embedding with multiple knn queries
```
Comment (afoucret) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/text-embedding.csv-spec:72]: ℹ️ Added another case with multiple TEXT_EMBEDDING in the same plan

**Review by carlosdelest — APPROVED** [review]
