### PR TITLE
Fix testSnapshotRelocatingPrimary to Actually Run Relocations

### LINKED ISSUE #46276: SharedClusterSnapshotRestoreIT.testSnapshotRelocatingPrimary has broken assert
Tests in `SharedClusterSnapshotRestoreIT` call the helper `waitForRelocationsToStart`, which on current `master` calls `awaitBusy`. When I swap this for `assertBusy`, which requires the provided assertion to pass, `testSnapshotRelocatingPrimary` fails because no shards begin relocating. I noticed this during PR #45794.

cc @original-brownbear

### PR DESCRIPTION
**Pull request by original-brownbear**
Without replicas we won't actually get any relocations
going when removing the node constraints in this test.
Adjusted the code to force relocations by forbidding
nodes that hold primaries instead.
Also, fixed the timeouts and asserted that we actually
get relocations.

Fixes #46276

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 1]
```diff
@@ -2218,8 +2218,13 @@ public void testSnapshotRelocatingPrimary() throws Exception {
                         .put("compress", randomBoolean())
                         .put("chunk_size", randomIntBetween(100, 1000), ByteSizeUnit.BYTES)));
 
-        // Create index on 1 nodes and make sure each node has a primary by setting no replicas
-        assertAcked(prepareCreate("test-idx", 1, Settings.builder().put("number_of_replicas", 0)));
+        internalCluster().ensureAtLeastNumDataNodes(2);
+        // Create index on two nodes and make sure each node has a primary by setting no replicas
+        assertAcked(prepareCreate("test-idx", 2, Settings.builder()
+            .put(SETTING_NUMBER_OF_REPLICAS, 0)
+            .put(SETTING_NUMBER_OF_SHARDS, 2)));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Before this change I think we had up to 10 shards and therefore would have had more relocations (mod bugs ofc). I think we only get one relocation here. Can we have more shards just in case that helps hit something?

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 2]
```diff
@@ -2229,11 +2234,11 @@ public void testSnapshotRelocatingPrimary() throws Exception {
         assertThat(client.prepareSearch("test-idx").setSize(0).get().getHits().getTotalHits().value, equalTo(100L));
 
         logger.info("--> start relocations");
-        allowNodes("test-idx", internalCluster().numDataNodes());
+        allowNodes("test-idx", 1);
 
         logger.info("--> wait for relocations to start");
 
-        waitForRelocationsToStart("test-idx", TimeValue.timeValueMillis(300));
+        assertTrue(waitForRelocationsToStart("test-idx", TimeValue.timeValueMinutes(1)));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: I think you could profitably inline `waitForRelocationsToStart` (it's only used here) and convert it to an `assertBusy`.

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 3]
```diff
@@ -2218,8 +2218,13 @@ public void testSnapshotRelocatingPrimary() throws Exception {
                         .put("compress", randomBoolean())
                         .put("chunk_size", randomIntBetween(100, 1000), ByteSizeUnit.BYTES)));
 
-        // Create index on 1 nodes and make sure each node has a primary by setting no replicas
-        assertAcked(prepareCreate("test-idx", 1, Settings.builder().put("number_of_replicas", 0)));
+        internalCluster().ensureAtLeastNumDataNodes(2);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: `prepareCreate` already does this I think

**Review by DaveCTurner — COMMENTED** [review]
I asked for a few tiny changes, but this is otherwise fine with me.

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Right it does -> removed, thanks :)

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Yea, inlined it :)

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Sure, made it use between 2 and 10 shards now

**Comment by original-brownbear** [comment]
Thanks @DaveCTurner addressed your asks

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Review by tlrx — APPROVED** [review]
LGTM 2

**Comment by original-brownbear** [comment]
Thanks @DaveCTurner and @tlrx!
