### PR TITLE
Expand the minimum utc timestamp used in fetching timezone transitions

### LINKED ISSUE #73995: Reproducible Failure in org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding
On current master I'm running into this:

```
 ./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding" -Dtests.seed=75EA10B45683EE61 -Dtests.locale=id -Dtests.timezone=PRT -Druntime.java=16
```

fails as:

```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.0.2
  OS Info               : Linux 5.11.0-18-generic (amd64)
  JDK Version           : 16 (Oracle)
  JAVA_HOME             : /usr/lib/jvm/jdk-16
  Random Testing Seed   : 75EA10B45683EE61
  In FIPS 140 mode      : false
=======================================

> Task :server:test
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding" -Dtests.seed=75EA10B45683EE61 -Dtests.locale=id -Dtests.timezone=PRT -Druntime.java=16

org.elasticsearch.common.RoundingTests > testRandomTimeUnitRounding FAILED
    java.lang.AssertionError: Expected [Rounding[DAY_OF_MONTH in Canada/Newfoundland]] to round [1991-10-28T02:46:41.527Z] to [1991-10-27T02:30:00Z] but instead rounded to [1991-10-27T03:30:00Z]
        at __randomizedtesting.SeedInfo.seed([75EA10B45683EE61:697BF1694B23F476]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.common.RoundingTests.assertUnitRoundingSameAsJavaUtilTimeImplementation(RoundingTests.java:269)
        at org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding(RoundingTests.java:231)


Suite: Test class org.elasticsearch.common.RoundingTests
  1> [2021-06-10T05:35:38,752][INFO ][o.e.c.RoundingTests      ] [testRandomTimeUnitRounding] before test
  1> [2021-06-10T05:35:39,263][INFO ][o.e.c.RoundingTests      ] [testRandomTimeUnitRounding] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding" -Dtests.seed=75EA10B45683EE61 -Dtests.locale=id -Dtests.timezone=PRT -Druntime.java=16
  2> java.lang.AssertionError: Expected [Rounding[DAY_OF_MONTH in Canada/Newfoundland]] to round [1991-10-28T02:46:41.527Z] to [1991-10-27T02:30:00Z] but instead rounded to [1991-10-27T03:30:00Z]
        at __randomizedtesting.SeedInfo.seed([75EA10B45683EE61:697BF1694B23F476]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.common.RoundingTests.assertUnitRoundingSameAsJavaUtilTimeImplementation(RoundingTests.java:269)
        at org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding(RoundingTests.java:231)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.common.RoundingTests_75EA10B45683EE61-004
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=id, timezone=PRT
  2> NOTE: Linux 5.11.0-18-generic amd64/AdoptOpenJDK 16.0.1 (64-bit)/cpus=48,threads=1,free=523306880,total=536870912
  2> NOTE: All tests run in this JVM: [RoundingTests]

Tests with failures:
 - org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding

1 test completed, 1 failed

```

### PR DESCRIPTION
**Pull request by pgomulka**
when rounding UTC timestamps we convert a timestamp from UTC to local, round this to closest midnight, then we convert back to UTC.
This means, that for a timestamp close to a DST we need to make sure we collected a transition that will be needed when converting back to UTC. 
To do this, we decrease the minUtcMillis by 2* unit to sure that the additional transition that could affect the timestamp is also fetched and the correct minimum is used in further lookups

closes https://github.com/elastic/elasticsearch/issues/73995

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/Rounding.java [hunk 1]
```diff
@@ -515,6 +516,7 @@ public Prepared prepare(long minUtcMillis, long maxUtcMillis) {
         }
 
         private TimeUnitPreparedRounding prepareOffsetOrJavaTimeRounding(long minUtcMillis, long maxUtcMillis) {
+//            long minLookup = minUtcMillis - 2*unit.extraLocalOffsetLookup();
```
Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/common/Rounding.java:519]: in fact, this could be enough

**Comment by pgomulka** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/common/Rounding.java (hunk 1 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/Rounding.java:518]: I think because this approach is more clear we should go with it.
The perfomance should not be affected because we only increase this by one unit and we use binary search anyway

File: server/src/test/java/org/elasticsearch/common/RoundingTests.java [hunk 2]
```diff
@@ -232,6 +232,21 @@ public void testRandomTimeUnitRounding() {
...
+     * This test chooses a date in the middle of the transition, so that we can test
+     * if the transition which is before the minLookup, but still should be applied
+     * is not skipped
+     */
+    public void testRoundingAroundDST() {
+        Rounding.DateTimeUnit unit = Rounding.DateTimeUnit.DAY_OF_MONTH;
+        ZoneId tz = ZoneId.of("Canada/Newfoundland");
+        long minLookup = 688618001000L; // 1991-10-28T02:46:41.527Z
+        long maxLookup = 688618001001L; // +1sec
+        // there is a Transition[Overlap at 1991-10-27T00:01-02:30 to -03:30] ”
```
Comment (pgomulka) [inline server/src/test/java/org/elasticsearch/common/RoundingTests.java:245]: note this tricky 00:01. so if we convert: 
1991-10-28T02:46:41.527Z -> 1991-10-17 23:11:48 -03:30 Canada/Newfoundland
then we round to DAY_OF_MONTH
1991-10-27 00:00:00 -**02**:30 Canada/Newfoundland

Previously it would not work because we only included transition for timestamps 1unit before the minUtcMillis
//            long minLookup = minUtcMillis - 2*unit.extraLocalOffsetLookup();
So for 1991-10-28T02:46:41.527Z it would be 1991-10-**27T02**:46:41.527Z

which means we would miss the relevant transition 1991-10-**27T00**:01-02:30 to -03:30

**Comment by nik9000** [comment]
> closes #75584

I think that is a link to this PR.

File: server/src/main/java/org/elasticsearch/common/Rounding.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/common/Rounding.java:518]: I think this'd be fine because I think it *might* find an extra DST boundary and that's it. Often it won't find any extra boundaries. We don't even use the time transition boundaries in the fastest case - that case preculcuates all the transitions using the unmodified bounds.

I think it's worth a long comment, but I think it's fine.

**Comment by pgomulka** [comment]
I modified the PR to only use the simplest solution (decreasing the minUtcMillis by 2*unit)

The more exact solution where the `collectTransitions` method  is modified  is abandoned

**Review by nik9000 — APPROVED** [review]
