### PR TITLE
[ML-DataFrame] fix starting a batch data frame after stopping at runtime 

### LINKED ISSUE #45339: [DataFrame] batch dataframe transform fails to start after it stopped at runtime
Repro:
 - create a batch data frame transform with sufficient amount of data
 - start it
 - stop it before it can finish, progress should be between 0 and 1
 - try to start it again

-> fails with NPE, see stack trace below

regression introduced in #44219

The issue also applies to continuous data frames, however only during the bootstrap phase until checkpoint 1 has been reached.

stacktrace from 8.0, also applies to 7.3
```
[2019-08-08T14:45:39,802][INFO ][o.e.x.d.t.DataFrameTransformTask] [xyz] Updating state for data frame transform [fq1405] to [{"task_state":"started","indexer_state":"stopped","position":{"indexer_position":{"@timestamp":1549675260000,"airline":"KLM"}},"checkpoint":0,"progress":{"total_docs":86274,"docs_remaining":50410,"percent_complete":41.56988200384821}}]
[2019-08-08T14:45:39,878][INFO ][o.e.x.d.t.DataFrameTransformPersistentTasksExecutor] [xyz] Successfully completed and scheduled task in node operation
[2019-08-08T14:45:39,887][WARN ][o.e.x.d.t.DataFrameTransformTask] [xyzl] Data frame transform [fq1405] encountered an exception:
java.lang.NullPointerException: null
at org.elasticsearch.xpack.dataframe.transforms.DataFrameIndexer.determineRunStateAtStart(DataFrameIndexer.java:488) ~[data-frame-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.dataframe.transforms.DataFrameIndexer.onStart(DataFrameIndexer.java:159) [data-frame-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformTask$ClientDataFrameIndexer.lambda$onStart$3(DataFrameTransformTask.java:633) [data-frame-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformTask$ClientDataFrameIndexer.onStart(DataFrameTransformTask.java:663) [data-frame-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
fix loading of next checkpoint after data frame transform has been stopped/started within one run

closes #45339 

The logic introduced in #44219 wrongly assumed no next checkpoint if no checkpoint has not been created yet. The fix properly loads the next checkpoint.

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/transforms/DataFrameTransformState.java [hunk 1]
```diff
@@ -151,15 +151,6 @@ public DataFrameTransformProgress getProgress() {
         return progress;
     }
 
-    /**
-     * Get the in-progress checkpoint
-     *
-     * @return checkpoint in progress or 0 if task/indexer is not active
-     */
-    public long getInProgressCheckpoint() {
-        return indexerState.equals(IndexerState.INDEXING) ? checkpoint + 1L : 0;
```
Comment (hendrikmuhs) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/transforms/DataFrameTransformState.java]: gone for good, next checkpoint is not dependent on the indexer state.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformPersistentTasksExecutor.java [hunk 2]
```diff
@@ -200,9 +204,9 @@ protected void nodeOperation(AllocatedPersistentTask task, @Nullable DataFrameTr
                 final long lastCheckpoint = stateHolder.get().getCheckpoint();
 
                 if (lastCheckpoint == 0) {
-                    logger.trace("[{}] No checkpoint found, starting the task", transformId);
-                    startTask(buildTask, indexerBuilder, lastCheckpoint, startTaskListener);
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformPersistentTasksExecutor.java]: this is the main fix: we started the task without loading the next checkpoint when last checkpoint is 0,

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformPersistentTasksExecutor.java [hunk 3]
```diff
@@ -145,11 +145,19 @@ protected void nodeOperation(AllocatedPersistentTask task, @Nullable DataFrameTr
         // <5> load next checkpoint
         ActionListener<DataFrameTransformCheckpoint> getTransformNextCheckpointListener = ActionListener.wrap(
                 nextCheckpoint -> {
-                    indexerBuilder.setNextCheckpoint(nextCheckpoint);
+
+                    if (nextCheckpoint.isEmpty()) {
+                        // corner case which should not happen ;-)
+                        // reset the position to force a full re-run with checkpoint creation
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformPersistentTasksExecutor.java]: `getTransformCheckpoint` always returns a checkpoint object: in case it does not find a document in the internal index, it returns an empty object.

(the comment is misleading, I will re-phrase)

**Review by benwtrent — APPROVED** [review]

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
