### PR TITLE
[ML] Make model snapshot upgrade autoscaling friendly

### LINKED ISSUE #81012: [ML] upgrade model snapshot is not autoscaling-friendly
Steps to reproduce: 
1. In a 7.6 cloud cluster, create and start a machine learning AD job. 
2. After job finished and stopped, upgrade the job to 7.16
3. Enable the autoscaling
4. Wait several minutes, and make sure there is no jobs running and no ml node in the plan (because of autoscaling ON)
5. In kibana, go to upgrade assistant, you should see warning about obsolete minimum version of model snapshot
6. In dev tools, fire an upgrade snapshot request: `POST _ml/anomaly_detectors/<job>/model_snapshots/<snapshot id>/_upgrade` 

Observed:
an error message says: `Could not open job because no ML nodes with sufficient capacity were found`. Also,  no ml node is provisioned after several minutes waiting.

Expected:
Upgrade model snapshot should be autoscaling-aware, ml node should be provisioned.

### PR DESCRIPTION
**Pull request by droberts195**
Model snapshot upgrade was not taking autoscaling into account
when doing node assignment.

Fixes #81012

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/NativeMemoryCapacity.java [hunk 1]
```diff
@@ -55,32 +55,49 @@ NativeMemoryCapacity merge(NativeMemoryCapacity nativeMemoryCapacity) {
...
+        // necessarily what "auto" will imply after scaling. Because the JVM occupies a
+        // smaller proportion of memory the bigger the node, the memory percent might be
+        // higher than we calculate here, potentially resulting in a bigger ML tier than
+        // required. The effect is most pronounced when the minimum node size is small and
+        // the minimum tier size is a lot bigger. For example, if the minimum node size is
+        // 1GB and the total native ML memory requirement for the tier is 32GB then the memory
+        // percent will be 41%, implying a minimum ML tier size of 78GB. But in reality a
+        // single 64GB ML node would have an auto memory percent of 90%, and 90% of 64GB is
+        // plenty big enough for the 32GB of ML native memory required.
+        // TODO: improve this in the next refactoring
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/NativeMemoryCapacity.java:83]: Fixing this isn't what this PR is primarily about, but I noticed it while debugging the new test, so thought it worth documenting.  The way all our sliding scales interact is very complex.  We should refactor this once the formula for node size to JVM size is reversible.

To be more accurate this method also needs to know the maximum ML node size and the principle that Cloud always scales up before scaling out.  Maximum ML node size is not currently reliably set.  But work is in progress to make it accurate, and this will take effect no later than the delegation of the JVM heap size to Elasticsearch.

So in the next refactor all the prerequisites will be in place to make this better.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicate.java [hunk 2]
```diff
@@ -11,6 +11,7 @@
 import org.elasticsearch.ElasticsearchException;
 import org.elasticsearch.persistent.PersistentTasksCustomMetadata;
 import org.elasticsearch.xpack.core.ml.job.snapshot.upgrade.SnapshotUpgradeState;
+import org.elasticsearch.xpack.core.ml.job.snapshot.upgrade.SnapshotUpgradeTaskParams;
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicate.java:14]:
```suggestion
```
Unnecessary?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/MlMemoryTracker.java [hunk 3]
```diff
@@ -411,29 +427,31 @@ public void refresh(PersistentTasksCustomMetadata persistentTasks, ActionListene
...
-            iterateAnomalyDetectorJobTasks(mlAnomalyDetectorJobTasks.iterator(), refreshDataFrameAnalyticsJobs);
+            Set<String> mlAnomalyDetectorJobTasks = Stream.concat(
+                persistentTasks.tasks()
+                    .stream()
+                    .filter(task -> MlTasks.JOB_TASK_NAME.equals(task.getTaskName()))
+                    .map(task -> MlTasks.jobId(task.getId())),
+                persistentTasks.tasks()
+                    .stream()
+                    .filter(task -> MlTasks.JOB_SNAPSHOT_UPGRADE_TASK_NAME.equals(task.getTaskName()))
+                    .map(task -> MlTasks.jobAndSnapshotId(task.getId()).v1())
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/MlMemoryTracker.java:438]: Why can't you cast the task.getParams() to `SnapshotUpgradeTaskParams` and grab the job ID that way?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlTasks.java [hunk 4]
```diff
@@ -88,6 +89,20 @@ public static String snapshotUpgradeTaskId(String jobId, String snapshotId) {
         return JOB_SNAPSHOT_UPGRADE_TASK_ID_PREFIX + jobId + "-" + snapshotId;
     }
 
+    public static Tuple<String, String> jobAndSnapshotId(String snapshotUpgradeTaskId) {
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlTasks.java:92]: I don't think this is necessary as the place that uses it has access to the persistent task params.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicateTests.java [hunk 5]
```diff
@@ -12,6 +12,7 @@
 import org.elasticsearch.test.ESTestCase;
 import org.elasticsearch.xpack.core.ml.MlTasks;
 import org.elasticsearch.xpack.core.ml.job.snapshot.upgrade.SnapshotUpgradeState;
+import org.elasticsearch.xpack.core.ml.job.snapshot.upgrade.SnapshotUpgradeTaskParams;
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicateTests.java:15]:
```suggestion
```
Unnecessary?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicate.java (hunk 2 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicate.java:14]: I moved `SnapshotUpgradeTaskParams` into the `core` plugin so that it's accessible to `MlTasksTests`.  It used to be in the same package as `SnapshotUpgradePredicate` so could be used without importing but now it's not.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/MlMemoryTracker.java (hunk 3 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/MlMemoryTracker.java:438]: Good idea.  It's a better way to do it for all the types of tasks.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicateTests.java (hunk 5 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/snapshot/upgrader/SnapshotUpgradePredicateTests.java:15]: It is used in this file.  It used to be in the same package but isn't now.

**Review by benwtrent — APPROVED** [review]
