### PR TITLE
ESQL: Fix `INLINE STATS GROUP BY null` being incorrectly pruned

### LINKED ISSUE #139887: ESQL: INLINE STATS null grouping/joining
### Description

There's a difference between how `STATS` behaves compared to `INLINE STATS` caused by `null` grouping/joining that we should look into:
```
ROW x = 1
| STATS c = COUNT(*) BY n = null
| KEEP c, n
| LIMIT 1
```
yields:
```
       c       |       n       
---------------+---------------
1              |null           
```

However,
```
ROW x = 1
| INLINE STATS c = COUNT(*) BY n = null
| KEEP c, n
| LIMIT 1
```
yields:
```
       c       |       n       
---------------+---------------
null           |null           
```

### PR DESCRIPTION
**Pull request by kanoshiou**
This PR fixes the issue where `INLINE STATS GROUP BY null` was being incorrectly pruned by `PruneLeftJoinOnNullMatchingField`.

Fixes #139887

## Problem
For query:
```
FROM employees
| INLINE STATS c = COUNT(*) BY n = null
| KEEP c, n
| LIMIT 3
```
During `LogicalPlanOptimizer`:
```
Limit[3[INTEGER],false,false]
\_EsqlProject[[c{r}#2, n{r}#4]]
  \_InlineJoin[LEFT,[n{r}#4],[n{r}#4]]
    |_Eval[[null[NULL] AS n#4]]
    | \_EsRelation[employees][<no-fields>{r$}#7]
    \_Aggregate[[n{r}#4],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS c#2, n{r}#4]]
      \_StubRelation[[<no-fields>{r$}#7, n{r}#4]]
```
The following join node:
```
InlineJoin[LEFT,[n{r}#4],[n{r}#4]]
|_Eval[[null[NULL] AS n#4]]
| \_EsRelation[employees][<no-fields>{r$}#7]
\_Aggregate[[n{r}#4],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS c#2, n{r}#4]]
  \_StubRelation[[<no-fields>{r$}#7, n{r}#4]]
```
should NOT have `PruneLeftJoinOnNullMatchingField` applied, because the right side is an `Aggregate` (originating from `INLINE STATS`). Since `STATS` supports `GROUP BY null`, the join key being null is a valid use case. Pruning this join would incorrectly eliminate the aggregation results, changing the query semantics.

During `LocalLogicalPlanOptimizer`:
```
ProjectExec[[c{r}#2, n{r}#4]]
\_LimitExec[3[INTEGER],null]
  \_ExchangeExec[[c{r}#2, n{r}#4],false]
    \_FragmentExec[filter=null, estimatedRowSize=0, reducer=[], fragment=[<>
Project[[c{r}#2, n{r}#4]]
\_Limit[3[INTEGER],false,false]
  \_InlineJoin[LEFT,[n{r}#4],[n{r}#4]]
    |_Eval[[null[NULL] AS n#4]]
    | \_EsRelation[employees][<no-fields>{r$}#7]
    \_LocalRelation[[c{r}#2, n{r}#4],Page{blocks=[LongVectorBlock[vector=ConstantLongVector[positions=1, value=100]], ConstantNullBlock[positions=1]]}]<>]]
```
The following join node:
```
InlineJoin[LEFT,[n{r}#4],[n{r}#4]]
|_Eval[[null[NULL] AS n#4]]
| \_EsRelation[employees][<no-fields>{r$}#7]
\_LocalRelation[[c{r}#2, n{r}#4],Page{blocks=[LongVectorBlock[vector=ConstantLongVector[positions=1, value=100]], ConstantNullBlock[positions=1]]}]
```
should NOT have `PruneLeftJoinOnNullMatchingField` applied, because the right side is a `LocalRelation` (the `Aggregate` was optimized into a `LocalRelation` containing the pre-computed aggregation results). Pruning this join when the join key is null would discard the valid aggregation results stored in the `LocalRelation`, incorrectly producing null values instead of the expected count.

## Solution
The fix ensures that `PruneLeftJoinOnNullMatchingField` only applies to `LOOKUP JOIN` nodes, where `join.right()` is an `EsRelation`. For `INLINE STATS` joins, the right side can be:

 - `Aggregate` (before optimization), or
 - `LocalRelation` (after the aggregate is optimized)

By checking `join.right() instanceof EsRelation`, we correctly skip the pruning optimization for `INLINE STATS` joins, preserving the expected query results when grouping by null.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/PruneLeftJoinOnNullMatchingField.java [hunk 1]
```diff
@@ -36,7 +37,12 @@ public PruneLeftJoinOnNullMatchingField() {
     @Override
     protected LogicalPlan rule(Join join, LogicalOptimizerContext ctx) {
         LogicalPlan plan = join;
-        if (join.config().type() == LEFT) { // other types will have different replacement logic
+        // Other join types will have different replacement logic.
+        // This rule only applies to LOOKUP JOIN (where join.right() is EsRelation). For INLINE STATS, the right
+        // side can be Aggregate or LocalRelation (when optimized), and the join key is always the grouping. Since
+        // STATS supports GROUP BY null, pruning the join when the join key (grouping) is null would incorrectly
+        // change the query results.
+        if (join.config().type() == LEFT && join.right() instanceof EsRelation) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/PruneLeftJoinOnNullMatchingField.java]: @kanoshiou thank you for adding the code comment here.
If this line is essential to this bug's fix, I feel that the check about the type of the join (lookup, inline) should be stronger than `instanceof EsRelation`. Why not `join instanceof LookupJoin` or `join instaceof InlineStats == false`?

Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/PruneLeftJoinOnNullMatchingField.java]: You're absolutely right! `instanceof InlineJoin == false` is more precise than my original `instanceof EsRelation` check. Updated in https://github.com/elastic/elasticsearch/pull/140027/commits/71f07f06dacba776c17bdd5b729f71e076cdc68d - thanks for catching this!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 2]
```diff
@@ -1885,7 +1885,7 @@ public enum Cap {
         METADATA_TIER_FIELD(Build.current().isSnapshot()),
         /**
          * Fix folding of coalesce function
-         * https://github.com/elastic/elasticsearch/issues/139887
+         * https://github.com/elastic/elasticsearch/issues/139344
          */
         FIX_FOLD_COALESCE,
```
Comment (kanoshiou) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:1891]: I believe @luigidellaquila referenced the wrong issue. https://github.com/elastic/elasticsearch/pull/140028#issue-3767870713

**Review by astefan — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
buildkite test this

**Comment by astefan** [comment]
CC @bpintea on the test failure above:
```
REPRODUCE WITH: ./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v9.3.0#javaRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT" -Dtests.method="test {csv-spec:unmapped-nullify.InlinestatsCount}" -Dtests.seed=48F92E2B2C099573 -Dtests.bwc=true -Dtests.locale=blo-Latn-BJ -Dtests.timezone=Indian/Mahe -Druntime.java=25
--
 
MixedClusterEsqlSpecIT > test {csv-spec:unmapped-nullify.InlinestatsCount} FAILED
java.lang.AssertionError:
Data mismatch:
row 0 column 2:a list containing
row 0 column 2:0: expected <1L> but was "null"
Actual:
x:integer \| does_not_exist:null \| c:long \| s:double \| d:null
1         \| null                \| null   \| null     \| null
 
Expected:
x:integer \| does_not_exist:null \| c:long \| s:double \| d:null
1         \| null                \| 1      \| null     \| null
at __randomizedtesting.SeedInfo.seed([48F92E2B2C099573:C0AD11F182F5F88B]:0)
at org.junit.Assert.fail(Assert.java:89)
at org.elasticsearch.xpack.esql.CsvAssert.dataFailure(CsvAssert.java:317)
at org.elasticsearch.xpack.esql.CsvAssert.assertData(CsvAssert.java:271)
at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.assertResults(EsqlSpecTestCase.java:423)
at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.doTest(EsqlSpecTestCase.java:379)
at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.doTest(EsqlSpecTestCase.java:344)
at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.test(EsqlSpecTestCase.java:229)
```

**Comment by kanoshiou** [comment]
@astefan My bad, I missed adding the new capability to this test. I’ll update the branch once the CI finishes, just in case any other tests fail.

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
Thanks @astefan.

Regarding the failed test in [elasticsearch-ci/part-4](https://buildkite.com/elastic/elasticsearch-pull-request/builds/115427#019bdb6b-da6e-4fe0-a09a-139b7cf262a8), I’m unable to reproduce it locally, which suggests it might be an issue specific to the CI runner. Let's see how this run goes.

**Comment by kanoshiou** [comment]
Thanks for following up and for the effort you put into this PR, @astefan!

Just a friendly reminder to merge this whenever you're ready, as this PR isn't tagged with `auto-merge-without-approval`.

**Comment by astefan** [comment]
@kanoshiou thank you for the reminder. I want also @bpintea's opinion on this PR as he's the original author of `null` pruning, that's the main reason I didn't yet merge this PR. Thank you for your patience and understanding.

**Review by bpintea — APPROVED** [review]
Thanks for the fix, LGTM.

Looking at the code, these following cases are covered too, but for good measure, do you think you could please add two more tests, more for future proofing than this change check:
* one where we have another grouping key, that's `null` (like `BY c = null, d = null`)
* one where we have another grouping key, that's not null (like `BY c = null, emp_no`)

**Comment by kanoshiou** [comment]
Thank you for the review, @bpintea! I’ve added the tests you suggested. 😊

**Comment by bpintea** [comment]
buildkite test this
