### PR TITLE
Execute actions under permit in primary mode only

### LINKED ISSUE #41686: [CI] IndexShard.assertPrimaryMode error in :x-pack:qa:rolling-upgrade-multi-cluster
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+bwc-tests/334/console

`Execution failed for task ':x-pack:qa:rolling-upgrade-multi-cluster:v6.7.0#leader#oneThirdUpgradedTestCluster#wait'.` 

The node was taken down by the assertion  
```
Caused by: java.lang.AssertionError: shard [logs-20200101][0], node[CvprUfVxSxazBWFEnwpJ0g], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=2q9Hz_lnTtqVS07KFe0Wjw], unassigned_info[[reason=NODE_LEFT], at[2019-04-30T11:58:34.033Z], delayed=true, details[node_left [CvprUfVxSxazBWFEnwpJ0g]], allocation_status[fetching_shard_data]] is not a primary shard in primary mode
|    	at org.elasticsearch.index.shard.IndexShard.assertPrimaryMode(IndexShard.java:1632) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:2030) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:248) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:222) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:115) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:110) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:273) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:240) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2561) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:109) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:65) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:296) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:289) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1087) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1046) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:932) ~[elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) [elasticsearch-6.7.2-SNAPSHOT.jar:6.7.2-SNAPSHOT]
|    	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|    	... 22 more
```

Possibly related to #36783 although the stack trace is different

### PR DESCRIPTION
**Pull request by jasontedor**
Today when executing an action on a primary shard under permit, we do not enforce that the shard is in primary mode before executing the action. This commit addresses this by wrapping actions to be executed under permit in a check that the shard is in primary mode before executing the action.

Relates #40386
Closes #41686

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 1]
```diff
@@ -307,10 +307,18 @@ protected void doRun() throws Exception {
...
-                releasable -> runWithPrimaryShardReference(new PrimaryShardReference(indexShard, releasable)),
-                this::onFailure
-            ));
+            acquirePrimaryOperationPermit(
+                    indexShard,
+                    primaryRequest.getRequest(),
+                    ActionListener.wrap(
+                            releasable -> runWithPrimaryShardReference(new PrimaryShardReference(indexShard, releasable)),
+                            e -> {
+                                if (e instanceof IllegalStateException && e.getMessage().equals("shard is not in primary mode")) {
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Maybe this should become a dedicated exception?

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: +1 to a dedicated exception.

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 2]
```diff
@@ -2507,7 +2506,27 @@ public void acquireAllPrimaryOperationsPermits(final ActionListener<Releasable>
         verifyNotClosed();
         assert shardRouting.primary() : "acquireAllPrimaryOperationsPermits should only be called on primary shard: " + shardRouting;
 
-        asyncBlockOperations(onPermitAcquired, timeout.duration(), timeout.timeUnit());
+        asyncBlockOperations(wrapPrimaryOperationPermitListener(onPermitAcquired), timeout.duration(), timeout.timeUnit());
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: This change verifies the primary mode after acquiring permits. I think we should verify the primary mode before acquiring permits?

**Review by dnhatn — COMMENTED** [review]
I left a comment but this looks good.

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 2 above)
Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: We have to verify after otherwise our check could be invalidated by the time that we acquire the permit.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java (hunk 1 above)
Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: I pushed 799f73119c04d3f56d2b6d8c152583e11c7e4dc3.

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: ok, I missed the relocation situation. Thanks for the explanation.

Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: No problem. 😄 

LGTM to you then?

**Review by dnhatn — APPROVED** [review]
LGTM
