### PR TITLE
SQL: Compress Cursors

### LINKED ISSUE #83284: Cursor header can grow very large for /_sql?format=txt endpoint
### Elasticsearch Version

7.16

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Docker image

### Problem Description

It seems that cursor header in `_sql?format=txt` endpoint response can grow very large, so large that it hits a limit in `curl`.

### Steps to Reproduce

* Create a mapping with 20k fields for index `test`.
* Run:
```
curl -X GET "localhost:9200/_sql?format=txt" -H 'Content-Type: application/json' -d'
{
  "query": "DESC test"
}
'
```
* Observe `curl` failing with:
```
curl: (27) Rejected 131055 bytes header (max is 102400)!
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by Luegg**
Partially addresses #83284

It looks like compressing cursors is a low hanging fruit to address issues around cursor size that seems to pay off pretty nicely (thanks @costin for the pointer). This is especially relevant for queries using the `ListCursor` (e.g. `SHOW COLUMNS` or queries sorting on aggregated columns) but might also benefit queries that store `SearchSourceBuilder` in the cursor.

Some anecdata for the potential savings in cursor size with `big` being an index with 1000 long fields `field1`, `field2`, ...:

| Request | Cursor size before | after | % |
|---------|--------------------|-----|----|
| `http post "localhost:9200/_sql?format=txt" query="SHOW COLUMNS IN big" fetch_size=1` | 34528b | 3208b | 9% |
| `http post "localhost:9200/_sql?format=csv" query="SHOW COLUMNS IN big" fetch_size=1` | 34508b | 3188b | 9% |
| `http post "localhost:9200/_sql?format=txt" query="SHOW COLUMNS IN test_emp" fetch_size=1` | 720b | 336b | 47% |
| `http post "localhost:9200/_sql?format=txt" query="SELECT emp_no, COUNT(*) FROM test_emp GROUP BY 1 ORDER BY 2" fetch_size=1` | 2672b | 352b | 13% |
| `http post "localhost:9201/_sql?format=csv" query="select max(languages), gender from test_emp group by 2" fetch_size=1` | 268b | 224b | 84% |

The format only has an impact on cursor size for the `txt` format. Hence, I'd also expect similar savings for the binary protocols.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM with the comment that the compression should be applied only if the payload is high enough; as you pointed out in the samples (thanks for that) for small sizes, there's little advantage.
For example, apply compression only if the input is higher than say 1K or 2K bytes as any savings under this threshold are not going to make much of a difference and avoid overhead when dealing with small payloads.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java [hunk 1]
```diff
@@ -1433,6 +1436,19 @@ public void testAsyncTextPaginated() throws IOException, InterruptedException {
...
+        String doc = IntStream.range(0, 1000)
+            .mapToObj(i -> String.format(Locale.ROOT, "\"field%d\": %d", i, i))
+            .collect(Collectors.joining(","));
+        index("{" + doc + "}");
+
+        String mode = randomMode();
+        Map<String, Object> resp = toMap(runSql(query("SHOW COLUMNS FROM " + indexPattern("test")).fetchSize(1).mode(mode)), mode);
+
+        // without compression, the cursor is at least <avg. fieldname length> * 1000 bytes (in fact it is ~35kb)
+        assertThat(resp.get("cursor").toString().length(), lessThan(5000));
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java:1449]: Would a decompression check (i.e. no exception thrown) or some `COMPRESSOR.isCompressed()` make sense here?

**Review by bpintea — APPROVED** [review]
LGTM.

**Comment by Luegg** [comment]
I've had a look at Costin's suggestion about compressing only cursors above a certain threshold. There seems to be a small overhead when compressing cursors indeed. I've set up a small benchmark to compare cursor serialization when compressed vs. uncompressed to get a feeling for it and the difference seems like to be in the order of 20us (on my machine):
```
Benchmark                        (compress)  (cursorName)  Mode  Cnt   Score    Error  Units
CursorBenchmark.serializeCursor        true        scroll  avgt    5  22.842 ±  3.354  us/op
CursorBenchmark.serializeCursor        true           agg  avgt    5  18.272 ±  3.249  us/op
CursorBenchmark.serializeCursor        true          list  avgt    5  99.570 ± 46.860  us/op
CursorBenchmark.serializeCursor       false        scroll  avgt    5   7.159 ±  2.639  us/op
CursorBenchmark.serializeCursor       false           agg  avgt    5   3.454 ±  1.230  us/op
CursorBenchmark.serializeCursor       false          list  avgt    5  75.924 ±  8.445  us/op
```
Compared to a best case end2end latency of maybe 2ms that's probably somewhat significant. But the conditional compression comes with some added complexity.

Additionally, I've realized that the version should not be compressed in any case to make sure old ES nodes can produce nice error message when encountering a compressed cursor.

@astefan @bpintea @costin given the larger changes you might want to have another look.

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java:1449]: I also think that would be helpful but unfortunately not too trivial to implement because the wire format is now a bit more intricate than just a compressed byte array encoded in base64.

**Comment by costin** [comment]
👍 for reading compression based on versioning. 
The extra complexity is significant - I proposed the variant of applying the compression right before sending as it makes things simpler at the expense of more memory.
Another alternative is to always compress things regardless of size - this saves the complexity and avoid the extra memory at the expense of wasted CPU for small payloads which overall might be a wash.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/common/io/SqlStreamOutput.java [hunk 2]
```diff
@@ -8,35 +8,95 @@
...
+/**
+ * Output stream for writing SQL cursors. The output is compressed if it would become larger than {@code compressionThreshold}
+ * bytes otherwise (see {@code DEFAULT_COMPRESSION_THRESHOLD}).
+ *
+ * The wire format is {@code version compressedFlag [payload | compressedPayload]}.
+ */
+public class SqlStreamOutput extends StreamOutput {
+
+    public static final byte HEADER_UNCOMPRESSED = 0;
+    public static final byte HEADER_COMPRESSED = 1;
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/common/io/SqlStreamOutput.java:30]: Since you're not using a cookie, wouldn't a boolean suffice in this case? It's also serialize to a byte.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/common/io/SqlStreamInput.java [hunk 3]
```diff
@@ -8,37 +8,51 @@
...
  * SQL-specific stream extension for {@link StreamInput} used for deserializing
  * SQL components, especially on the client-side.
  */
 public class SqlStreamInput extends NamedWriteableAwareStreamInput {
 
-    private final ZoneId zoneId;
+    public static SqlStreamInput fromString(String base64encoded, NamedWriteableRegistry namedWriteableRegistry, Version version)
+        throws IOException {
+        byte[] bytes = Base64.getDecoder().decode(base64encoded);
+        StreamInput in = new InputStreamStreamInput(new ByteArrayInputStream(bytes));
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/common/io/SqlStreamInput.java:35]: wouldn't (the previous) `StreamInput.wrap(bytes)` suffice here?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/common/io/SqlStreamOutput.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/common/io/SqlStreamOutput.java:30]: 🤦 yes, that can be simpler indeed 👍

**Comment by Luegg** [comment]
👍 I would also lean towards the simpler option of always compressing. The latest commit https://github.com/elastic/elasticsearch/pull/83591/commits/722263c3880dfea5fc6aab9a1e81458e93c36315 illustrates the differences in complexity compared to the conditional compression. Besides the more straightforward implementation, it also saves some memory and CPU overhead when compressing large cursors. Since we don't have good data to make an informed decision about what a good compression threshold could be, we can as well go forward with the simpler approach.

**Review by costin — APPROVED** [review]
LGTM
