### PR TITLE
ESQL: continue resolving attributes for Eval

### LINKED ISSUE #99576: ESQL: more than two EVAL expressions using previous new evaluations will fail
### Description

`FROM test | eval x1 = pow(emp_no, 1), x2 = pow(x1, 1), x3 = pow(x2, 2)`

or

`FROM test | eval x1 = substring(ip1, 3), x2 = substring(x1, 2), x3 = substring(x2, 2)`

or

`FROM test | eval x1 = concat(ip1, ip2), x2 = concat(x1, "--"), x3 = concat(x2, "**")`

will fail with 

```
                "type": "verification_exception",
                "reason": "Found 1 problem\nline 1:65: Unknown column [x2], did you mean [x1]?"
```

Spawned from https://github.com/elastic/elasticsearch/issues/99472

### PR DESCRIPTION
**Pull request by astefan**
The code for attempting to resolve unresolved attributes was prematurely stopped when one attributes was deemed unresolvable disallowing chained evaluation expressions in the same `eval` command. This small change makes the attributes resolution continue until all expressions are visited.
Fixes https://github.com/elastic/elasticsearch/issues/99576

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -323,13 +323,17 @@ protected LogicalPlan doRule(LogicalPlan plan) {
...
 
-            return plan.transformExpressionsUp(UnresolvedAttribute.class, ua -> resolveAttribute(ua, childrenOutput));
+            return plan.transformExpressionsUp(UnresolvedAttribute.class, ua -> maybeResolveAttribute(ua, childrenOutput));
         }
 
-        private Attribute resolveAttribute(UnresolvedAttribute ua, List<Attribute> childrenOutput) {
+        private Attribute maybeResolveAttribute(UnresolvedAttribute ua, List<Attribute> childrenOutput) {
             if (ua.customMessage()) {
                 return ua;
             }
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:332]: In essence, skip this part (quickly returning from resolving an Attribute) and let `eval` have another chance at resolving expressions that use attributes from previous `eval` expressions.

**Review by costin — APPROVED** [review]
Noice!
