### PR TITLE
Periodically check the available memory when fetching search hits source

### LINKED ISSUE #89656: Add circuit breaker to prevent OOM searching very large docs
### Description

Presume an index contains docs with a single text field. The values of that field can be arbitrarily huge docs. There can easily come a point where doing a simple search against that index and requesting an appropriate `size` of docs in a single response can OOM the node.

Could there be a circuit breaker that prevents the node from OOM?

**Steps to reproduce:**
- a dataset which the message field in some documents have the length larger than 700,000. (please contact @wwang500 for datasets)
- run below query:
```
GET <test_dataset>/_search
{
  "size": 1000,
  "query": { 
    "range": {
      "message_length": {
        "gte": 700000
      }
    }
  }
}
```

**Observed:**
Node will turn unhealthy and restart due to OOM.

### PR DESCRIPTION
**Pull request by andreidan**
When fetching documents, sometimes we need to load the 
entire source of search hits. Document sources can be large, 
and with support for up to 10k hits per search request, this creates 
a significant untracked memory load on Elasticsearch that can 
potentially cause out-of-memory errors.

This PR adds memory checking for hits source in the fetch phase.
We check with the parent (the real memory) circuit breaker every 
1MiB of loaded source and when fetching the last document of every
segment. This gives the real memory breaker a chance to interrupt 
running operations when we're running low on memory, and prevent 
potential OOMs. 

The amount of local accounting to buffer is controlled by the 
`search.memory_accounting_buffer_size` dynamic setting and defaults to
`1MiB`.

Fixes #89656

### CODE REVIEW

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/action/EnrichShardMultiSearchAction.java [hunk 1]
```diff
@@ -259,8 +261,11 @@ protected MultiSearchResponse shardOperation(Request request, ShardId shardId) t
                             }
                             return context.getFieldType(field);
                         });
-                        final SearchHit hit = new SearchHit(scoreDoc.doc, visitor.id());
-                        hit.sourceRef(filterSource(fetchSourceContext, visitor.source()));
+                        final SearchHit hit = new SearchHit(scoreDoc.doc, visitor.id(), breaker);
```
Comment (andreidan) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/action/EnrichShardMultiSearchAction.java:264]: Adding accounting here is option and we can do it in a follow-up. 
Added to get more data points from the IT infrastructure.

**Comment by andreidan** [comment]
Restarting CI due to https://github.com/elastic/elasticsearch/issues/121927

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by andreidan** [comment]
Current failure is https://github.com/elastic/elasticsearch/issues/122153
Restarting tests

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Comment by andreidan** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        this.bytes = bytes;
+        this.breaker = breaker;
+    }
+
+    public static MemoryAccountingBytesRefCounted create(CircuitBreaker breaker) {
+        return new MemoryAccountingBytesRefCounted(0, breaker);
+    }
+
+    public void account(int bytes, String label) {
+        breaker.addEstimateBytesAndMaybeBreak(bytes, label);
```
Comment (drempapis) [inline server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:34]: Is it valid to add this code under a `try-finally`? If the method `addEstimateBytesAndMaybeBreak` throws a `CircuitBreakingException,` the counter will not be updated. I'm unsure if we still need to count for such a case.

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+    private MemoryAccountingBytesRefCounted(int bytes, CircuitBreaker breaker) {
+        this.bytes = bytes;
+        this.breaker = breaker;
+    }
+
+    public static MemoryAccountingBytesRefCounted create(CircuitBreaker breaker) {
+        return new MemoryAccountingBytesRefCounted(0, breaker);
+    }
+
+    public void account(int bytes, String label) {
```
[the remark this answers is not in the document]
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:33]: We use the length of a the source `byte[]` as the amount of memory to record. The underlying circuit breaker uses an `AtomicLong` to sum up these ints so I think we're good here ? 
The reason I went for an int here is to avoid the widening of `byte[].length` to a long and then storing fewer bytes in heap as part of this ref counted object (it'll be one per search hit so it adds up quite quickly)

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java (hunk 2 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:34]: We want the `CircuitBreakingException` to bubble up to stop the operation that tripped the breaker.

File: server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java [hunk 4]
```diff
@@ -2927,6 +2933,84 @@ public void testSlicingBehaviourForParallelCollection() throws Exception {
         }
     }
 
+    public void testFetchPhaseAccountsForSourceMemoryUsage() throws Exception {
```
Comment (drempapis) [inline server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java:2936]: This is a nice test for reference

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 5]
```diff
@@ -274,6 +274,18 @@ public class SearchService extends AbstractLifecycleComponent implements IndexEv
         Property.NodeScope
     );
 
+    /**
+     * The size of the buffer used for memory accounting.
+     * This buffer is used to locally track the memory accummulate during the executiong of
+     * a search request before submitting the accumulated value to the circuit breaker.
+     */
+    public static final Setting<ByteSizeValue> MEMORY_ACCOUNTING_BUFFER_SIZE = Setting.byteSizeSetting(
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:282]: Does it make sense to make this configurable? We're adding a lot of surface area for something that is supposed to be a stopgap solution and in any case, this one feels like something we should be able to set to a useful value based on heap size and search thread-count?
Also, the value seems to me should be far higher than 32kb? If I had to guess, I'd instinctively go for something like ~1M?
So for e.g. a 8 core => 12 threads node (which I think would have 4 or 8G heap in most of our setups?) we'd move in chunks of 0.25% of total heap or less. That seems reasonable and makes the inherent fairness issue of a breaker based solution less bad?

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 6]
```diff
@@ -310,6 +323,8 @@ public class SearchService extends AbstractLifecycleComponent implements IndexEv
 
     private volatile boolean enableRewriteAggsToFilterByFilter;
 
+    private volatile ByteSizeValue memoryAccountingBufferSize;
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:326]: Whether or not we make this constant, why not make it a `long` and save all those to byte conversions?

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java [hunk 7]
```diff
@@ -86,6 +90,7 @@ private static class Collectors {
         this.subSearchContext = subSearchContext;
         this.topDocsCollectors = new LongObjectPagedHashMap<>(1, bigArrays);
         this.fetchProfiles = context.profiling() ? new ArrayList<>() : null;
+        this.memAccountingBufferSize = context.getClusterSettings().get(SearchService.MEMORY_ACCOUNTING_BUFFER_SIZE).getBytes();
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:93]: Another point about the settings, parsing is costly :) I we go for a setting lets store the value outright instead of parsing settings on the hot path?

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 8]
```diff
@@ -369,8 +470,8 @@ private static HitContext prepareNestedHitContext(
         assert nestedIdentity != null;
         Source nestedSource = nestedIdentity.extractSource(rootSource);
 
-        SearchHit hit = new SearchHit(topDocId, rootId, nestedIdentity);
-        return new HitContext(hit, subReaderContext, nestedInfo.doc(), childFieldLoader.storedFields(), nestedSource, rankDoc);
+        SearchHit nestedHit = new SearchHit(topDocId, rootId, nestedIdentity);
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:473]: NIT: unnecessary rename noise :)

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 9]
```diff
@@ -278,44 +329,94 @@ private static HitContext prepareNonNestedHitContext(
...
 
-    private static Supplier<Source> lazyStoredSourceLoader(Profiler profiler, LeafReaderContext ctx, int doc) {
+    private static Supplier<Source> lazyStoredSourceLoader(
+        Profiler profiler,
+        LeafReaderContext ctx,
+        int doc,
+        MemoryAccountingBytesRefCounted memAccountingRefCounted,
+        boolean submitToCB,
+        Consumer<Integer> memoryUsageAccumulator,
+        Supplier<Integer> accumulatedBytesInLeaf
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:407]: I guess we want these generic interfaces for testing, but maybe at least combine all the memory accounting stuff into a single interface and thus parameter? We're now adding 4 parameters to a 3 parameter method, just for the accounting :) Plus, we really don't want to box the ints here anyway :)

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+package org.elasticsearch.common;
+
+import org.elasticsearch.common.breaker.CircuitBreaker;
+import org.elasticsearch.core.AbstractRefCounted;
+
+/**
+ * A ref counted object that accounts for memory usage in bytes and releases the
+ * accounted memory from the circuit breaker when the reference count reaches zero.
+ */
+public final class MemoryAccountingBytesRefCounted extends AbstractRefCounted {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:19]: Bit of a general question here on the safety of this:

We have a mutable `int` field that is not thread safe, but a thread-safe ref-count.
Can we add some comments on how we know that we have a proper barrier/ordering/happens-before-edge/etc. between the `account` calls and the eventual `closeInternal`?

**Review by original-brownbear — COMMENTED** [review]
I left a couple suggestions/requests for simplification.
Generally speaking though I think this is very much going in the right direction :) Just a few details to discuss maybe :) Thanks!

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 11]
```diff
@@ -404,6 +419,10 @@ private void setEnableQueryPhaseParallelCollection(boolean enableQueryPhaseParal
         this.enableQueryPhaseParallelCollection = enableQueryPhaseParallelCollection;
     }
 
+    private void setMemoryAccountingBufferSize(ByteSizeValue memoryAccountingBufferSize) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:422]: Just a general comment :D I see this pattern of a single use via method-ref named method for setting listeners. Why not just inline this stuff to a lambda, save 3 lines and let the compiler add the one off method? :)

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 5 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:282]: >Also, the value seems to me should be far higher than 32kb? If I had to guess, I'd instinctively go for something like ~1M?

I think a setting makes sense precisely to accommodate for these kind of guesses in production for various workloads / hardware configurations. 

I'm happy to go with 1M default (the higher the value the less granularity we have when accounting memory, but 1M doesn't sound too bad) 
@javanna any strong opinions here?

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 6 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:326]: Yep good shout.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:282]: Sure if we don't feel comfortable with making a guess here, lets make it configurable (though I do have a hard time seeing the practicality I must say). Also, this isn't really a per-cluster thing? It's more of a node setting since it depends on the size of a node?

As far as granularity goes, you want as little granularity as you can get away with. Take my example from a couple days ago:

Say you have a budget of 2M but can survive allocating 2.5M and 3 threads each wanting to load 1M during fetch, all of them running in  parallel with at least some overlap.
If your granularity is 1b, then it is almost guaranteed that all of them will get to somewhere around 2/3 of what they're doing and they all fail. Under pressure we degrade into a completely broken state and waste lots of memory only to eventually throw 429.
If your granularity is set to 0.5M then you actually never exceed what you can survive and at least 1 thread will be able to finish its task.
But also, if you go to 1M you might OOM :)

=> seems to me the math here is rather easy. We need to leave a considerable safety margin anyway because the accounting super super approximate and we should leverage the fact that it is so approximate because that's an unchangable fact today anyway?

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 9 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:407]: >maybe at least combine all the memory accounting stuff into a single interface and thus parameter?

We're accumulating locally on every hit and reading what's accumulated at a different time. So we need two things here.
Dropped the boxing of ints. Great shout - had forgotten about the primitive supplier/consumers

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java (hunk 10 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:19]: Oh it's not safe like this:) Changed it to an AtomicInteger - we write it and read it once every buffer size, but from different threads.

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java (hunk 7 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:93]: Hm, is this on the hot path - not familiar with aggs but I'd imagine this is at most once / search request?

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 8 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:474]: I think it clarifies (for me at least) which hit we're dealing with.

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java (hunk 10 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:21]: Wait but aren't all updates to the value confined to a single thread? All we need is the final update to show up at the point of closing?
+ weren't we just worried about the size of this thing, `AtomicInteger` makes it quite a bit heavier?

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 9 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]: But why can't all of this be a single object? (we can create multiple instances, though I'd imagine we'd still only have one per thread?
Adding 4 parameters seems like a massive increase in complexity, that's all :)

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]: Oh, I actually might have a way to unify these

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java (hunk 10 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:21]: >All we need is the final update to show up at the point of closing?
Yes, this is what we need. Oh, volatile int would be cheaper here! 

>weren't we just worried about the size of this thing, AtomicInteger makes it quite a bit heavier?
Yes. but we're doing it once/batch now (as opposed to for every hit)

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:21]: What do you think if we change `account` to 
```
public void setBytesAndAccount(int bytes, String label) {
        breaker.addEstimateBytesAndMaybeBreak(bytes, label);
        this.bytes = bytes;
}
```
and have the instance `this.bytes` a `volatile int` ?

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 5 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:282]: >As far as granularity goes, you want as little granularity as you can get away with. 

That's exactly right, which is why I think having it configurable is important. 

>If your granularity is set to 0.5M then you actually never exceed what you can survive and at least 1 thread will be able to finish its task.
But also, if you go to 1M you might OOM :)

This kind of change is what I envision if we get a hardware profile + workload where the margin of 1MiB is not good enough. 

>Also, this isn't really a per-cluster thing? 

This is a good question. Having it a dynamic settings helps with operations (avoiding involved node restarts whilst maintaining HA) whilst local values can still be configured in `elasticsearch.yml` to help with cases where the clusters are non-homogeneous.

File: server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java (hunk 10 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/common/MemoryAccountingBytesRefCounted.java:19]: Sketched it here https://github.com/elastic/elasticsearch/pull/121920/commits/f366e7f0d7729a21bed0f680f185b533b1d30b35

**Comment by andreidan** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java (hunk 7 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java]: Moved this to the `AggregationContext`

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 12]
```diff
@@ -416,4 +513,52 @@ public String toString() {
...
+         * fetch phase.
+         */
+        public void account(int bytes, String label) {
+            this.bytes += bytes;
+            breaker.addEstimateBytesAndMaybeBreak(bytes, label);
+        }
+
+        @Override
+        protected void closeInternal() {
+            breaker.addWithoutBreaking(-bytes);
```
[the remark this answers is not in the document]
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:561]: That's a good question. The closeInternal invariant is that it's called once when the ref count is decremented to zero (and once a ref count is zero it's seen as closed, so it can't bounce up to > 0 again). I think this invariant gives us the safety we need here.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 13]
```diff
@@ -172,7 +203,10 @@ protected SearchHit nextDoc(int doc) throws IOException {
                     ctx,
                     leafSourceLoader,
                     leafIdLoader,
-                    rankDocs == null ? null : rankDocs.get(doc)
+                    rankDocs == null ? null : rankDocs.get(doc),
+                    circuitBreaker,
+                    enoughBytesOrLastDocInLeaf,
+                    this::accumulateLocally
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:209]: Why do we have to be so tricky here? Why not leave the hit context preparation as is and simply do the accounting below after the fetch processors have done their work? That gives us a much cleaner accounting in case of filtering as well while making this change a lot simpler?

**Review by original-brownbear — COMMENTED** [review]
One question/suggestion maybe I'm misunderstanding something :)

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 13 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:209]: We need to hook in the accounting math in the cases where we lazily load the source https://github.com/elastic/elasticsearch/pull/121920/files#diff-e05d7cea3ce24b7a468186919b40a9647ff7c3390a4434a2e36e3302d77ca4bbR397

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:209]: Yes but after the fetch processors ran we don't even escape the `HitContext`, we're definitely done with the source there one way or another?

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:209]: How would you set the memory ref counted thing on the hit _after_ it was created in this case?

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java [hunk 14]
```diff
@@ -196,7 +197,12 @@ public InternalAggregation buildAggregation(long owningBucketOrdinal) throws IOE
         for (int i = 0; i < topDocs.scoreDocs.length; i++) {
             docIdsToLoad[i] = topDocs.scoreDocs[i].doc;
         }
-        FetchSearchResult fetchResult = runFetchPhase(subSearchContext, docIdsToLoad);
+        FetchSearchResult fetchResult = runFetchPhase(
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:200]: Does it even make any sense to do the accounting here? We literally only account while accumulating the response, then we create the top hits result which moves the hits to `unpooled` and release the breaker count again without saving a single byte of heap? Seems like pointless overhead?

**Review by original-brownbear — COMMENTED** [review]
Let's talk about the top hits first :) I think the conversation on the iterator depends on it quite a bit. I left a question there.

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java (hunk 14 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:200]: >We literally only account while accumulating the response

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:200]: Yea but the releasing of the refcounted happens right after accumulating the heap usage, so we literally do the breaker release at peak heap usage, making the whole exercise somewhat redundant?

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:200]: >Sure we may break while going up

I believe this is a valid use case though (parallel collections leading to OOM is something we saw)

**Comment by andreidan** [comment]
@original-brownbear great idea to use the real memory breaker like we do in aggs. Implemented it - I need to add a test but that's all left here I believe. Thanks for the help here !

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 15]
```diff
@@ -162,6 +169,18 @@ protected SearchHit nextDoc(int doc) throws IOException {
                 if (context.isCancelled()) {
                     throw new TaskCancelledException("cancelled");
                 }
+                ++processedDocs;
+                // indicates if we should check with the parent circuit breaker (the real memory breaker) if we have enough memory to
+                // continue the fetch phase.
+                // we do so whenever one of the following is true:
+                // 1. we have accumulated at least the size of the memory accounting buffer
+                // 2. we have reached the last document in the leaf
+                boolean enoughBytesOrLastDocInLeaf = (accumulatedBytesInLeaf >= context.memAccountingBufferSize())
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:178]: NIT: two redundant sets of brackets here :) also maybe just inline the `boolean`, with all the text documentation the variable name real doesn't add anything ?

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 16]
```diff
@@ -162,6 +169,18 @@ protected SearchHit nextDoc(int doc) throws IOException {
...
+                    || (processedDocs == docsInLeaf);
+                if (enoughBytesOrLastDocInLeaf) {
+                    context.circuitBreaker().addEstimateBytesAndMaybeBreak(0, "fetch source");
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:181]: I wonder: should we just make this call an implementation detail of the context?
i.e. just have a `void checkBreaker()` call like we do in aggs? Makes it a little easier to remove the real memory breaker surgically down the line :) That's why the API is the way it is in aggs as well I think.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 17]
```diff
@@ -226,7 +251,7 @@ List<FetchSubPhaseProcessor> getProcessors(SearchShardTarget target, FetchContex
         }
     }
 
-    private static HitContext prepareHitContext(
+    private HitContext prepareHitContext(
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:254]: This can stay static or are my eyes playing tricks on me? :)

**Review by original-brownbear — COMMENTED** [review]
Nice :) Thanks Andrei! One suggestion, but either way I'm happy with this. Thanks for all the discussions around this!

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 17 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:254]: No no, great catch :) 
POC-ing side effect

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 16 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:179]: I thought about it initially. The condition we have here is more specific to fetch phase and how we accumulate / segment (vs the aggs where it's easy to generically bake in the `checkBreaker` method) 

We could still do something similar here I think, if we have a `checkBreaker` that takes a `BooleanPredicate` so callers can indicate when to hit the breaker?

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]: Made this work https://github.com/elastic/elasticsearch/pull/121920/commits/06dcb68127721dd9333e2b1429355439e13e1b40

**Comment by andreidan** [comment]
Thanks for the iterations here @original-brownbear 

Added unit tests and updated the PR description. I think this is now ready if you'd like to have another look.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 18]
```diff
@@ -162,6 +169,12 @@ protected SearchHit nextDoc(int doc) throws IOException {
                 if (context.isCancelled()) {
                     throw new TaskCancelledException("cancelled");
                 }
+                ++processedDocs;
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:172]: We could potentially not check the breaker when finishing collecting from a segment and rely on other parallel fetch operations running in the system to check the real memory breaker. 

If we decide to carry on as it is now and **check at the end of a segment** this has the potentially unwanted (or perhaps it is wanted?) side effect of checking once / segment even if the source is never requested.

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:172]: Made this change in https://github.com/elastic/elasticsearch/pull/121920/commits/abacdb16d580ba2eb0b11ca75546df50da420fb6 but let me know what you think @original-brownbear

File: server/src/main/java/org/elasticsearch/search/SearchHit.java [hunk 19]
```diff
@@ -293,6 +292,7 @@ public static SearchHit unpooled(int docId, String id) {
     }
 
     public static SearchHit unpooled(int nestedTopDocId, String id, NestedIdentity nestedIdentity) {
+        // always referenced search hits do NOT call #deallocate
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/search/SearchHit.java:295]: This might seem as noise but it helped me when making sense of the pool/unpool stuff so thought maybe it's useful to future spelunkers.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:282]: I think we should give this a lower bound of 1M actually and maybe and upper bound of 32M and default it to the G1GC region size. If you think about it, checking at a finer granularity than the TLAB size really makes no sense whatsoever. Likewise, going way above the granularity makes like sense as well.
We can't really default the setting to the TLAB size cleanly I think if we make it a cluster setting so I think 1M might be an ok default since that's often our region size?
But since OpenJDK doesn't allow a lower value for the region size we probably shouldn't either.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 18 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:172]: Hmm as a I pointed out above, any check at a higher rate than the TLAB region size is probably not a good idea. 
But now that you're asking :) Why do we even bother wit the per-leaf cost and reset the counts on a per-leaf basis. If we just don't reset on a new segment this problem goes away and the behavior is generally less affected by index geometry as well which is always nice?

**Review by original-brownbear — COMMENTED** [review]
Looks just fine thanks Andrei! Maybe have a short chat on the setting bounds and the per-segment logic but other than that I think we're good to go here :)

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 20]
```diff
@@ -291,7 +302,7 @@ private static HitContext prepareNonNestedHitContext(
             Source source = Source.lazy(lazyStoredSourceLoader(profiler, subReaderContext, subDocId));
             return new HitContext(hit, subReaderContext, subDocId, Map.of(), source, rankDoc);
         } else {
-            SearchHit hit = new SearchHit(docId, id);
+            SearchHit hit = new SearchHit(docId, id, null);
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:305]: NIT: Why inline the overload here? Was this intentional?

**Review by original-brownbear — APPROVED** [review]
LGTM :)

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 18 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]: As discussed, moved to per fetch phase accounting as inter segment concurrency is not available in the fetch phase. 
Added minimum size of 1MiB for the buffer and no upper limit (configuring a large value could enable us to disable the feature completely)

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 20 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]: It's from back in the complicated-solution times. Dropped it. Thanks !

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 21]
```diff
@@ -274,6 +274,20 @@ public class SearchService extends AbstractLifecycleComponent implements IndexEv
         Property.NodeScope
     );
 
+    /**
+     * The size of the buffer used for memory accounting.
+     * This buffer is used to locally track the memory accummulate during the executiong of
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:279]: the memory *accumulated* ?

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 22]
```diff
@@ -129,7 +130,7 @@ private SearchHits buildSearchHits(SearchContext context, int[] docIdsToLoad, Pr
         StoredFieldLoader storedFieldLoader = profiler.storedFields(StoredFieldLoader.fromSpec(storedFieldsSpec));
         IdLoader idLoader = context.newIdLoader();
         boolean requiresSource = storedFieldsSpec.requiresSource();
-
+        final int[] accumulatedBytesInLeaf = new int[1];
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:133]: out of curiosity: why an array of ints with length 1, and what do we mean by "leaf" in the name?

File: server/src/main/java/org/elasticsearch/search/internal/SearchContext.java [hunk 23]
```diff
@@ -369,6 +370,31 @@ public Query rewrittenQuery() {
...
 
+    /**
+     * The circuit breaker used to account for the search operation.
+     */
+    public abstract CircuitBreaker circuitBreaker();
+
+    /**
+     * Return the amount of memory to buffer locally before accounting for it in the breaker.
+     */
+    public abstract long memAccountingBufferSize();
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:381]: is it necessary to add these two new methods to SearchContext? I am not quite following where they are used, are they needed mostly for testing purposes or is there more to it?

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:381]: I guess what I am wondering is if we could make them perhaps arguments of the following method instead, or something along those lines, just to decrease the blast radius of this change.

**Review by javanna — COMMENTED** [review]
Left a couple of nits, they can also be resolved as a follow-up, not urgent.
