### PR TITLE
Split regular histograms from date histograms.

### LINKED ISSUE #4847: Histogram aggregations: support decimal intervals
Fork of #3810 and #3799. Decimal intervals would be useful for certain data types such as currencies, temperatures, lengths ...

### LINKED ISSUE #8082: Histogram bucketing negative values incorrectly
I've been trying to make sense of Elasticssearch histogram aggregations the last couple of days. And I've found that they don't work as expected, or even advertised.

Lets say i want to aggregate like so:

    "aggregations": {
      "sea_water_temperature": {
        "histogram": {
          "field": "sea_water_temperature",
          "interval": 3
        }
      }
    }

Response buckets looks fine at first glance, but when trying to query for documents within the bounds of a bucket I don't get the same document count as the bucket suggested. E.g.

    "filter": {
      "range": {
        "sea_water_temperature": {
          "lt": 0,
          "gte": -3
        }
      }
    }

This could give x results while the bucket "-3" had a doc_count of y. This seems to only be an issue for negative bucket keys.

In the docs for histogram it states that the bucket key for a given value is:

    rem = value % interval
    if (rem < 0) {
      rem += interval
    }
    bucket_key = value - rem

However I tried a term aggregation with that as a value script:

    "aggregations": {
      "sea_water_temperature": {
        "terms": {
          "field": "sea_water_temperature",
          "script": "rem = _value % interval; rem = rem < 0 ? rem + interval : rem; _value - rem",
          "params": {
            "interval": 3
          }
        }
      }
    }

That gives me the same kind of bucketing as histogram does but now my filter queries actually match the doc_counts of the buckets(!). Why isn't histogram working as described? or am I missing something?

### PR DESCRIPTION
**Pull request by jpountz**
Currently both aggregations really share the same implementation. This commit
splits the implementations so that regular histograms can support decimal
intervals/offsets and compute correct buckets for negative decimal values.

However the response API is still the same. So for intance both regular
histograms and date histograms will produce an
`org.elasticsearch.search.aggregations.bucket.histogram.Histogram`
aggregation.

The optimization to compute an identifier of the rounded value and the
rounded value itself has been removed since it was only used by regular
histograms, which now do the rounding themselves instead of relying on the
Rounding abstraction.

Closes #8082
Closes #4847

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java [hunk 1]
```diff
@@ -52,6 +51,8 @@ protected DateHistogramAggregationBuilder createFactory(String aggregationName,
             factory.interval((Long) interval);
         } else if (interval instanceof DateHistogramInterval) {
             factory.dateHistogramInterval((DateHistogramInterval) interval);
+        } else {
+            throw new AssertionError();
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: I think it is a bit strange to throw an AssertionError when assertions might not be enabled? Maybe just throw and IllegalArgumentException or a RuntimeException or ElasticsearchException or something?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java [hunk 2]
```diff
@@ -9,7 +9,7 @@
  *
  *    http://www.apache.org/licenses/LICENSE-2.0
  *
- * Unless required by applicable law or agreed to in writing,
+ * Unless required by applicHistogramAggregationBuilderle law or agreed to in writing,
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: Stray copy and paste?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java [hunk 3]
```diff
@@ -27,40 +27,64 @@
...
-    /**
-     * Read from a stream.
-     */
     public DateHistogramAggregationBuilder(StreamInput in) throws IOException {
-        super(in, InternalDateHistogram.HISTOGRAM_FACTORY);
+        super(in, InternalDateHistogram.TYPE, ValuesSourceType.NUMERIC, ValueType.DATE);
+        interval = in.readLong();
         dateHistogramInterval = in.readOptionalWriteable(DateHistogramInterval::new);
+        offset = in.readLong();
+        if (in.readBoolean()) {
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: `readOptionalWriteable`? I love making these methods shorter so they are easier to scan visually.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java [hunk 4]
```diff
@@ -88,40 +121,61 @@ protected static long parseStringOffset(String offset) {
...
+        if (extendedBounds != null) {
+            extendedBounds.toXContent(builder, params);
+        }
+
         return builder;
     }
 
     @Override
+    public String getWriteableName() {
+        return InternalDateHistogram.TYPE.name();
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: I think `InternalDateHistogram.NAME` would be a bit better. Now that type isn't used for serialization I'd like to remove it entirely one day.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java [hunk 5]
```diff
@@ -62,21 +63,85 @@ protected DateHistogramAggregationBuilder createFactory(String aggregationName,
...
-        InternalOrder order = (InternalOrder) otherOptions.get(HistogramAggregator.ORDER_FIELD);
+        InternalOrder order = (InternalOrder) otherOptions.get(Histogram.ORDER_FIELD);
         if (order != null) {
             factory.order(order);
         }
         return factory;
     }
 
+    @Override
+    protected boolean token(String aggregationName, String currentFieldName, Token token, XContentParser parser,
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: Man this feels like a mess compared to ObjectParser. We can't do anything about it in the middle of this PR though. Just makes me sad.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/Histogram.java [hunk 6]
```diff
@@ -40,46 +48,56 @@
...
     abstract class Order implements ToXContent {
 
-        public static final Order KEY_ASC = new InternalOrder((byte) 1, "_key", true, new Comparator<InternalHistogram.Bucket>() {
+        private static int compareKey(Histogram.Bucket b1, Histogram.Bucket b2) {
+            if (b1 instanceof InternalHistogram.Bucket) {
+                return Double.compare(((InternalHistogram.Bucket) b1).key, ((InternalHistogram.Bucket) b2).key);
+            } else if (b1 instanceof InternalDateHistogram.Bucket) {
+                return Long.compare(((InternalDateHistogram.Bucket) b1).key, ((InternalDateHistogram.Bucket) b2).key);
+            } else {
+                throw new AssertionError("Unexpected impl: " + b1.getClass());
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/Histogram.java]: Can you throw something else? It just makes me uncomfortable to throw AssertionError.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java [hunk 7]
```diff
@@ -21,38 +21,137 @@
...
+    private double maxBound = Double.MIN_VALUE;
+
     public HistogramAggregationBuilder(String name) {
-        super(name, InternalHistogram.HISTOGRAM_FACTORY);
+        super(name, InternalHistogram.TYPE, ValuesSourceType.NUMERIC, ValueType.DOUBLE);
     }
 
-    /**
-     * Read from a stream.
-     */
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java]: Why remove it? I was adding them because I thought it was nice to mark the constructors for anyone unfamiliar with Elasticsearch. It'd help them get their bearings.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogram.java [hunk 8]
```diff
@@ -56,53 +91,363 @@ public String getKeyAsString() {
...
+        EmptyBucketInfo(Rounding rounding, InternalAggregations subAggregations, ExtendedBounds bounds) {
+            this.rounding = rounding;
+            this.subAggregations = subAggregations;
+            this.bounds = bounds;
+        }
+
+        EmptyBucketInfo(StreamInput in) throws IOException {
+            rounding = Rounding.Streams.read(in);
+            subAggregations = InternalAggregations.readAggregations(in);
+            if (in.readBoolean()) {
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogram.java]: `readOptionalWriteable` again?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogram.java [hunk 9]
```diff
@@ -56,53 +91,363 @@ public String getKeyAsString() {
...
+
+    /**
+     * Stream from a stream.
+     */
+    public InternalDateHistogram(StreamInput in) throws IOException {
+        super(in);
+        order = InternalOrder.Streams.readOrder(in);
+        minDocCount = in.readVLong();
+        if (minDocCount == 0) {
+            emptyBucketInfo = new EmptyBucketInfo(in);
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogram.java]: `readOtionalWriteable` again?

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogram.java]: Er, well, it doesn't work like that. Ignore.

File: core/src/main/java/org/elasticsearch/search/aggregations/pipeline/cumulativesum/CumulativeSumPipelineAggregator.java [hunk 10]
```diff
@@ -68,23 +70,22 @@ public String getWriteableName() {
 
     @Override
     public InternalAggregation reduce(InternalAggregation aggregation, ReduceContext reduceContext) {
-        InternalHistogram histo = (InternalHistogram) aggregation;
-        List<? extends InternalHistogram.Bucket> buckets = histo.getBuckets();
-        InternalHistogram.Factory<? extends InternalHistogram.Bucket> factory = histo.getFactory();
+        MultiBucketsAggregation histo = (MultiBucketsAggregation) aggregation;
+        List<? extends Bucket> buckets = histo.getBuckets();
+        HistogramFactory factory = (HistogramFactory) histo;
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/pipeline/cumulativesum/CumulativeSumPipelineAggregator.java]: Nice.

File: core/src/test/java/org/elasticsearch/search/aggregations/pipeline/AvgBucketIT.java [hunk 11]
```diff
@@ -95,7 +94,7 @@ public void setupSuiteScopeCluster() throws Exception {
     public void testDocCountTopLevel() throws Exception {
         SearchResponse response = client().prepareSearch("idx")
                 .addAggregation(histogram("histo").field(SINGLE_VALUED_FIELD_NAME).interval(interval)
-                        .extendedBounds(new ExtendedBounds((long) minRandomValue, (long) maxRandomValue)))
+                        .extendedBounds((long) minRandomValue, (long) maxRandomValue))
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/search/aggregations/pipeline/AvgBucketIT.java]: I think you can drop the `(long)`s because these are `double`s now.

File: docs/reference/aggregations/bucket/histogram-aggregation.asciidoc [hunk 12]
```diff
@@ -11,19 +11,10 @@ To make this more formal, here is the rounding function that is used:
...
+bucket_key = Math.floor((value - offset) / interval) * interval + offset
 --------------------------------------------------
 
-From the rounding function above it can be seen that the intervals themselves **must** be integers.
-
-WARNING: Currently, values are cast to integers before being bucketed, which
-might cause negative floating-point values to fall into the wrong bucket. For
-instance, `-4.5` with an interval of `2` would be cast to `-4`, and so would
-end up in the `-4 <= val < -2` bucket instead of the `-6 <= val < -4` bucket.
+The `interval` must be a positive decimal, while the `offset` must be a decimal in `[0 - interval[`.
```
Comment (nik9000) [inline docs/reference/aggregations/bucket/histogram-aggregation.asciidoc]: bad end bracket.

**Comment by nik9000** [comment]
I left a bunch of minor stuff. I love that InternalHistogram.Factory is going. And the new factory is well documented.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 1 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: We seem to be using this exception in a number of places already. I like that this is an error and not an exception as it means there is an error in the code rather than on the user end, and should not be caught?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java (hunk 2 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: indeed :)

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java (hunk 7 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java]: agreed, it was not intentional and was probably lost while moving code

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 5 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: agreed, I wanted to avoid creating potential issues by changing serialization logic (this code was just moved) but I agree we should move to ObjectParser

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 1 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: Feel free to tell me I'm totally wrong - but do we feel confident enough that a mistake here (in code) is a good enough reason to cause the [node to restart](https://github.com/elastic/elasticsearch/pull/19272) ? I'm worried about endless restarts, where a single mistake on a specific API can cause problems on an entire node.

File: docs/reference/aggregations/bucket/histogram-aggregation.asciidoc (hunk 12 above)
Comment (jpountz) [inline docs/reference/aggregations/bucket/histogram-aggregation.asciidoc]: I wanted to denote the fact that the bound is half open, would you do it otherwise?

**Comment by jpountz** [comment]
Thanks @nik9000 for having a look to this huge PR! Why don't you like AssertionError? I actually like it for branches that should never get visited, as a way to mean that an invariant has been violated and that the code is buggy. Also the fact that it is an error and not an exception makes it less likely to be swallowed since errors are not supposed to be caught. Finally we seem to already have a number of places where we already use assertion errors.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 1 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: This is a good point, I am not sure. On the one hand, this is indeed a specific API and restarting is unlikely to fix anything, but on the other hand this is the same for stack overflows are memory leaks?

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: >  for stack overflows are memory leaks?

I'm not sure what you mean? can you unpack those examples?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AbstractHistogramBuilder.java [hunk 13]
```diff
@@ -21,86 +21,50 @@
...
 import org.elasticsearch.search.aggregations.support.ValuesSourceType;
 
 import java.io.IOException;
 import java.util.Objects;
 
-public abstract class AbstractHistogramBuilder<AB extends AbstractHistogramBuilder<AB>>
+// only exists to share some code between the two histogram builders
+// don't make it public
+abstract class AbstractHistogramBuilder<AB extends AbstractHistogramBuilder<AB>>
         extends ValuesSourceAggregationBuilder<ValuesSource.Numeric, AB> {
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AbstractHistogramBuilder.java]: ok, but since its abstract can we still document what its doing? Does it really require the insane generic typing?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java [hunk 14]
```diff
@@ -0,0 +1,147 @@
...
+import org.elasticsearch.search.aggregations.support.AggregationContext;
+import org.elasticsearch.search.aggregations.support.ValuesSource;
+
+import java.io.IOException;
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+import java.util.Map;
+
+class DateHistogramAggregator extends BucketsAggregator {
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java]: this new file is missing some kind of explanation about what it does...

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java [hunk 15]
```diff
@@ -30,15 +34,10 @@
 /**
  *
  */
-public class DateHistogramParser extends HistogramParser {
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: Can we fix this broken comment? Maybe we need something to fail the build, for files that contain this:

```
/**
 *
 */
```

What causes this? Is it Intellij?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java [hunk 16]
```diff
@@ -21,38 +21,140 @@
...
+    }
+
+    public HistogramAggregationBuilder interval(double interval) {
+        if (interval <= 0) {
+            throw new IllegalArgumentException("[interval] must be >0 for histogram aggregation [" + name + "]");
+        }
+        this.interval = interval;
+        return this;
+    }
+
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java]: This is a big antipattern: here we have two methods, both named interval(), just with different signatures. One is actually a getter, whereas the other changes state!

But you have no idea reading source code, what is going on, e.g. its just a method and you have to follow the source code to figure out what is happening. 

 Please change to getInterval() and setInterval() [there are other instances of these in these files, obviously those should be fixed, too]

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramFactory.java [hunk 17]
```diff
@@ -0,0 +1,39 @@
...
+public interface HistogramFactory {
+
+    Number getKey(MultiBucketsAggregation.Bucket bucket);
+
+    Number nextKey(Number key);
+
+    InternalAggregation createAggregation(List<MultiBucketsAggregation.Bucket> buckets);
+
+    MultiBucketsAggregation.Bucket createBucket(Number key, long docCount, InternalAggregations aggregations);
+
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramFactory.java]: can we doc the new methods here too, since they are on an interface, they represent a contract.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 1 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: I think if you throw a subclass of RuntimeException here it'll get bubbled back to the user and we'll get a bug report if it shows up. AssertionError's problem is that catching it and forwarding it around properly gets us dangerously close to catching OOMs. We probably could make an exception for catching AssertionError but I'm not sure it is worth it when we can just throw a RuntimeException of some sort instead.

Also it just feels weird to throw an assertion error from outside of assertions! Its icky 😨

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 5 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: Yeah. It can and should wait.

File: docs/reference/aggregations/bucket/histogram-aggregation.asciidoc (hunk 12 above)
Comment (nik9000) [inline docs/reference/aggregations/bucket/histogram-aggregation.asciidoc]: I've never seen the `[0, interval[` notation before! I had no idea it was in an [ISO standard](https://en.wikipedia.org/wiki/ISO_31-11)! I used a wikipedia link because the standard is paywalled I think... That standard was superceded by [ISO 80000-2](http://www.ise.ncsu.edu/jwilson/files/mathsigns.pdf). That link is to a scan.... Anyway, it says to use the `[0, interval)` notation but that the `[0, interval[` notation "is also used".

Now that I've done the 20 minutes of research I think you can use whatever you want. I learned the `[0, interval)` notation in school and thought that the backwards `[` on the end was a typo. Some folks will think that too but they too will learn something new that day!

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 1 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: For the record, the JVM code itself seems to be using AssertionError for impossible branches.

>> for stack overflows are memory leaks?
>
>I'm not sure what you mean? can you unpack those examples?

I mean that a specific API could trigger eg. a StackOverflowError, which will cause the node to shut down even though it does not prevent normal operations of the node otherwise.

**Comment by jpountz** [comment]
I pushed more commits to address comments. The only one I did not address is the naming convention for setters since we use it in all aggregations and it would probably need to be a bigger discussion.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java (hunk 1 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramParser.java]: > For the record, the JVM code itself seems to be using AssertionError for impossible branches.

Weird. I can live with it but it is weird.

**Comment by nik9000** [comment]
LGTM.

**Comment by jpountz** [comment]
Thanks @nik9000 !
