### PR TITLE
Fix ClusterInfoServiceIT#testMaxQueueLatenciesInClusterInfo

### LINKED ISSUE #134500: [CI] ClusterInfoServiceIT testMaxQueueLatenciesInClusterInfo failing
**Build Scans:**
- [elasticsearch-intake #28243 / part1](https://gradle-enterprise.elastic.co/s/w6cafbcsabxtk)
- [elasticsearch-pull-request #90683 / part-1](https://gradle-enterprise.elastic.co/s/alkbxobljwypw)
- [elasticsearch-periodic-platform-support #10469 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/jupo66xfte4qw)
- [elasticsearch-periodic #10466 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/j4xssbdj3cetg)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.ClusterInfoServiceIT.testMaxQueueLatenciesInClusterInfo" -Dtests.seed=5D578E06CE0A1182 -Dtests.locale=mgh-Latn-MZ -Dtests.timezone=Asia/Nicosia -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.ClusterInfoServiceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMaxQueueLatenciesInClusterInfo'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0.0F>
     but: was <0.1454265F>
```

**Issue Reasons:**
- [main] 4 failures in test testMaxQueueLatenciesInClusterInfo (0.5% fail rate in 887 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
It's not a beautiful fix, but it seems to work

Closes: #134500

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java [hunk 1]
```diff
@@ -514,6 +514,8 @@ public void testMaxQueueLatenciesInClusterInfo() throws Exception {
                 threadsToJoin[i].join();
             }
             Arrays.stream(threadsToJoin).forEach(thread -> assertFalse(thread.isAlive()));
+            // Wait for the write executor to go idle
+            assertBusy(() -> assertThat(trackingWriteExecutor.getActiveCount(), equalTo(0)));
```
Comment (nicktindall) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:522]: I don't know if this could still have a very rare race condition where we get a zero inbetween the tasks being executed, but given that the write pool defaults to # of cores, it seems unlikely we'd go to 0 active, then to non-zero again as we drain the queue.

I'm not sure if there's a more satisfying approach to knowing when the work is all done.

Comment (joshua-adams-1) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:522]: Should we add this as a comment and then link the existing test failure in case the test fails again in X weeks for the reason mentioned above?

**Review by joshua-adams-1 — APPROVED** [review]
LGTM - I'm a ++ for adding a comment to expedite future debugging, but that doesn't need a separate review

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java (hunk 1 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:522]: Done in https://github.com/elastic/elasticsearch/pull/136461/commits/2ec69958b4f2996f332f09d3fd8f4f03cff10124

**Review by ywangd — APPROVED** [review]
LGTM

Two minor comments for you to pick and choose
1. Since we now have to use `assertBusy`, maybe it is more straightforward to use that for things that we want to observe, e.g. `MaxQueueLatencyInQueueMillis`, instead of asserting a secondary effect like the active thread count?
2. I think the previous "fix" (https://github.com/elastic/elasticsearch/pull/134180) is no longer necessary and can be reverted?

**Comment by nicktindall** [comment]
> 1. Since we now have to use `assertBusy`, maybe it is more straightforward to use that for things that we want to observe, e.g. `MaxQueueLatencyInQueueMillis`, instead of asserting a secondary effect like the active thread count?

It's a good point. The only thing I wonder is, because the polling is destructive and represents activity since last time we polled,  polling in a tight loop with `assertBusy` would probably yield zeros relatively quickly just because no tasks completed between this and the last poll. By polling on the thread pool, which is non destructive we're waiting for the tasks to finish and asserting that metric pipeline is working correctly when that occurs? if that makes sense? I just think due to the destructive nature of the metric reads, we'd risk a "false negative" by using `assertBusy` directly on the metrics.

I'd love it if the metric reads weren't destructive and there was no "observer effect" instead, but that doesn't seem high priority at the moment.

> 2. I think the previous "fix" (#134180) is no longer necessary and can be reverted?

I'll take a look.

**Comment by ywangd** [comment]
> polling is destructive

We do peek from the head of the queue and this part should not be destructive, right? Unless the task is not even queued when the polling happens. But in that case, `getActiveCount` may also have a chance to return false positive?

Btw, if we keep checkpoint sync action running on the generic thread, we should be certain that all "write-related" tasks are submitted to the thread pool when the indexing requests return.

**Comment by nicktindall** [comment]
> We do peek from the head of the queue and this part should not be destructive, right? Unless the task is not even queued when the polling happens.

If we assert busy on`peekMaxQueueLatencyInQueueMillis` going to zero, it will finish as soon as the queue is empty I think? we want to block until all the jobs have completed and run `afterExecute`.

> But in that case, `getActiveCount` may also have a chance to return false positive?

I think there's a chance this can still happen, hence the comment. But because there's > 1 thread in the pool, it would seem for `getActiveCount` to go to zero before the queue was drained, you'd need all the running tasks to finish at precisely the same moment? (I didn't look too deep on how this is tracked)

> Btw, if we keep checkpoint sync action running on the generic thread, we should be certain that all "write-related" tasks are submitted to the thread pool when the indexing requests return.

I noticed a test failure fairly quickly when I reverted it. I think it's a necessary part of the fix. (Edit, confirmed, it breaks the test when it's in there)

**Comment by ywangd** [comment]
Ah ok thanks for explaining. I think what you have here is good. 👍
