### PR TITLE
Fix AbstractClient#execute Listener Leak

### LINKED ISSUE #65405: Monitoring indices fails
**Elasticsearch version:** Version: 7.10.0, Build: default/deb/51e9d6f22758d0374a0f3f5c6e8f3a7997850f96/2020-11-09T21:30:33.964949Z, JVM: 15.0.1

**JVM version** : openjdk 11.0.9 2020-10-20

**OS version** (`uname -a` if on a Unix-like system): Linux esnode1-rza 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Opening Kibana and try to view Management -> Stack Monitoring ->Indices fails and leads to a lot of entries in the elasticsearch logs since change from legacy monitoring to monitoring with metricbeat (7.9.1)

**Steps to reproduce**:

    Change elasticsearch monitoring to metricbeat
    In Kibana go to page Management -> Stack Monitoring ->Indices
    Wait...

After some time I get a lot of entries in the elasticsearch logs (on several nodes)

Expected behavior: Show an overview of the indices

**Provide logs (if relevant)**:

Output of one elasticsearch log:
2020-11-23T07:40:17,219][WARN ][o.e.t.InboundHandler ] [node-2-a] handling inbound transport message [InboundMessage{Header{3377158}{7.10.0}{33130325}{false}{false}{false}{false}{NO_ACTION_NAME_FOR_RESPONSES}}] took [7750ms] which is above the warn threshold of [5000ms]
[2020-11-23T07:41:49,122][INFO ][o.e.m.j.JvmGcMonitorService] [node-2-a] [gc][243275] overhead, spent [339ms] collecting in the last [1s]
[2020-11-23T07:41:55,957][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-2-a] uncaught exception in thread [elasticsearch[node-2-a][search][T#393]]
org.elasticsearch.tasks.TaskCancelledException: The parent task was cancelled, shouldn't start any child tasks
at org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.registerChildNode(TaskManager.java:522) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.tasks.TaskManager.registerChildNode(TaskManager.java:213) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.TransportAction.registerChildNode(TransportAction.java:56) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:75) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:412) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:545) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.TransportMultiSearchAction.executeSearch(TransportMultiSearchAction.java:149) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:172) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.TransportMultiSearchAction$1.onFailure(TransportMultiSearchAction.java:157) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:98) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.ActionListener$5.onFailure(ActionListener.java:258) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:594) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:568) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:100) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.10.0.jar:7.10.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
last message repeated about 80-100 times...

**Any additional context:**
Sometimes the nodes get disconnected from cluster then. One time I had to do a full restart of the cluster.
Cluster has three nodes, 972 indices, 1944 Shards, 12 TB Data

### PR DESCRIPTION
**Pull request by original-brownbear**
This was observed in #65405 due to trying to locally execute a
task whose parent was already cancelled but is a general issue.

We should not throw from APIs that consume a listener as this may
like in this case leak the listener in that case.
Rather than fixing the specific case of #65405 this fixes the
abstract client overall to avoid other such leaks.

Closes #65405

NOTE: This isn't the greatest possible fix because it will double-trigger the `listener` if the exception was thrown by resolving the listener itself. We could work around this by using a separate listener to pass to `doExecute` but then again this still holds the potential for memory leaks and we'll have to fix all upstream code (which currently, like e.g. rest actions wraps in a `catch (Exception)` as a last ditch effort to not leak things as well).
I think this may be fine for now, fixes a known memory leak and prevents unexpected leaks elsewhere (I'm not so worried about double releasing any resources through this since we wrap those in `RunOnce` and `ReleaseOnce` wherever possible anyway since `org.elasticsearch.action.support.TransportAction.RequestFilterChain#proceed` does the same `try-catch` for all exceptions on the same listeners).

### CODE REVIEW

**Comment by original-brownbear** [comment]
@henningandersen adding you here since we talked about "this" issue quite a bit before. Sorry for essentially adding another problematic spot here, but let me know what you think (as an alternative I could also just fix the specific leak in #65405 for now by handling the exception upstream and we can think about a general solution at some other time).

File: server/src/main/java/org/elasticsearch/client/node/NodeClient.java [hunk 1]
```diff
@@ -91,7 +97,22 @@ void doExecute(ActionType<Response> action, Request request, ActionListener<Resp
                 Response extends ActionResponse
             > Task executeLocally(ActionType<Response> action, Request request, ActionListener<Response> listener) {
         return taskManager.registerAndExecute("transport", transportAction(action), request,
-            (t, r) -> listener.onResponse(r), (t, e) -> listener.onFailure(e));
+                (t, r) -> {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/client/node/NodeClient.java:100]: At least in tests, this ensures no double invocation of the listener with the new `try-catch`
I suppose technically speaking it would be nice to do the same for the override below that uses a `TaskListener` but I chose not to for now since as you can see this already required fixing up a number of spots that relied on the listener's `onResponse` throwing and handling exceptions upstream.

File: server/src/main/java/org/elasticsearch/client/node/NodeClient.java [hunk 2]
```diff
@@ -79,7 +79,13 @@ public void close() {
     public <Request extends ActionRequest, Response extends ActionResponse>
     void doExecute(ActionType<Response> action, Request request, ActionListener<Response> listener) {
         // Discard the task because the Client interface doesn't use it.
-        executeLocally(action, request, listener);
+        try {
+            executeLocally(action, request, listener);
+        } catch (Exception e) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/client/node/NodeClient.java:84]: I think without further refactoring of the signature of `registerAndExecute` and this is about as low as we can go on the stack in terms of passing these exceptions to the listener directly. Otherwise we'll have to adjust a non-trivial number of spots that make use of the returned `Task` from that method.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java [hunk 3]
```diff
@@ -124,7 +124,12 @@ public void run() {
         client.admin().indices().getIndex(getIndexRequest, new ActionListener<>() {
             @Override
             public void onResponse(GetIndexResponse getIndexResponse) {
-                validateMappings(getIndexResponse);
+                try {
+                    validateMappings(getIndexResponse);
```
Comment (original-brownbear) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java:128]: Obvious spot where we have a non-`wrap` listener and this would just bubble up all the way if the request is executed locally on `SAME`.

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java [hunk 4]
```diff
@@ -88,32 +88,43 @@ protected void masterOperation(Task task, final ResizeRequest resizeRequest, fin
...
+        final IndexMetadata sourceMetadata = state.metadata().index(sourceIndex);
+        if (sourceMetadata == null) {
+            listener.onFailure(new IndexNotFoundException(sourceIndex));
+            return;
+        }
+
         IndicesStatsRequestBuilder statsRequestBuilder = client.admin().indices().prepareStats(sourceIndex).clear().setDocs(true);
         IndicesStatsRequest statsRequest = statsRequestBuilder.request();
         statsRequest.setParentTask(clusterService.localNode().getId(), task.getId());
+        // TODO: only fetch indices stats for shrink type resize requests and move request validation (outside of doc counts) to before
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java:101]: Failing the listener on a missing index isn't strictly necessary here because I added the `try-catch` around `prepareCreateIndexRequest` anyway but I figured it more nicely motivates this `TODO` and follow-up cleanup to the logic here that previously relied on the exceptions just bubbling up all the way.

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/RestSubmitAsyncSearchActionTests.java [hunk 5]
```diff
@@ -88,7 +89,7 @@ public void testParameters() throws Exception {
             assertThat(request, instanceOf(SubmitAsyncSearchRequest.class));
             assertThat(valueAccessor.apply((SubmitAsyncSearchRequest) request), equalTo(expectedValue));
             executeCalled.set(true);
-            return null;
+            return new AsyncSearchResponse("", randomBoolean(), randomBoolean(), 0L, 0L);
```
Comment (original-brownbear) [inline x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/RestSubmitAsyncSearchActionTests.java:92]: This was pretty dirty to begin with. Without this change and the change in the test verifying client we would always throw an NPE in the background (form trying to serialize a `null` response)  but that would never fail any tests.
With the new assertions that wasn't possible anymore so I had to fix this up here.

File: server/src/main/java/org/elasticsearch/client/node/NodeClient.java [hunk 6]
```diff
@@ -79,7 +79,13 @@ public void close() {
...
+            // #executeLocally returns the task and throws RuntimeException if it fails to register the task so we forward them to listener
+            // since this API does not concern itself with the specifics of the task handling
+            listener.onFailure(e);
+        }
     }
 
     /**
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/client/node/NodeClient.java:91]: I think we should add a comment to javadoc here and in the other `executeLocally` that they can throw `TaskCancelledException`?

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/client/node/NodeClient.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/client/node/NodeClient.java:84]: I think we can't just catch that exception here since we also have the case of `org.elasticsearch.tasks.TaskManager#register` throwing `IllegalArgumentException` at least (that actually does reproduce in a test even). Also, technically speaking the in-line task cancellation in `org.elasticsearch.tasks.TaskManager#registerCancellableTask` could throw any exception if the parent is banned already so I figured I'd just catch all the things here for now?

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java:101]: Fair point this is slightly broken to begin with I guess. I'll drop that part of the TODO, I still think it'd be valid to avoid fetching the shard stats needlessly.

File: server/src/main/java/org/elasticsearch/client/node/NodeClient.java (hunk 6 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/client/node/NodeClient.java:91]: ++

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2 (unrelated watcher)

**Comment by original-brownbear** [comment]
@henningandersen so for now I got by with constraining the catch by doing the following fixes:

* https://github.com/elastic/elasticsearch/pull/65415/commits/526777087b04ec4a63ead3accdefb2178f224deb (catch the exception we throw on an uninitialized client or if an action is missing by catching `IllegalStateException` (the change in ex. type here is just a revert of a prior attempt at fixing this by just using `IllegalArgumentException` sine we already catch that but I threw that approach out), fix watcher bug in serializing exceptions https://github.com/elastic/elasticsearch/pull/65415/commits/adf535de770cf3519fbc04ceed522f48ed628138 and fix CCR bug that had an exception bubble up all the way in https://github.com/elastic/elasticsearch/pull/65415/commits/7be5d1c445dd62a1f2282f49cd738c42b97dc2b2)

wdyt? Good to go with this one or should be tread more carefully maybe and fix these issue separately in follow-ups and keep catching `Exception` initially maybe? (especially thinking about the `7.10` backport here)

**Review by henningandersen — APPROVED** [review]
LGTM.

I think the behavior without assertions is similar to catching exceptions more broadly in `doExecute`? So I think we should just leave it as is.

**Comment by original-brownbear** [comment]
Thanks Henning!

> I think the behavior without assertions is similar to catching exceptions more broadly in doExecute? So I think we should just leave it as is.

++ yea I wasn't really worried about the production behavior. More about introducing a series of test failures that will then necessitate more changes to `7.10.x` but in hindsight that's probably not too big of an issue and it's good to track things down :)
