### PR TITLE
Fix decimal point parsing for date_optional_time

### LINKED ISSUE #43730: strict_date_optional_time does not support "," as separator for fractions
**Elasticsearch version** (`bin/elasticsearch --version`): 
7.2.0

**Plugins installed**: []

**JVM version** (`java -version`): 
Bundled JDK

**OS version** (`uname -a` if on a Unix-like system): 
Red Hat 7.6 3.10.0-957.12.1.el7.x86_64

**Description of the problem including expected versus actual behavior**:
strict_date_optional_time does not support "," as separator for fractions but ISO 8601 says that "," and "." should both be accepted.
Furthermore the ESJsonLayout also uses "," as separator which causes mapping exceptions when elasticsearch logs are indexed.
https://github.com/elastic/elasticsearch/blob/508c38a450a48279bd160c6b8fb2d6703eaf1105/server/src/main/java/org/elasticsearch/common/logging/ESJsonLayout.java#L63

**Steps to reproduce**:
1. Create Mapping:

```
{
  "order": 10,
  "index_patterns": [
    "date-test"
  ],
  "mappings": {
    "properties": {
      "time": {
        "format": "strict_date_optional_time||epoch_millis",
        "type": "date",
        "doc_values": true
      }
    }
  },
  "aliases": {}
}
```
2. Create Document in date-test Index with "," as separator:
```
POST date-test/_doc
{
  "time": "2019-06-28T08:30:39,104+0200"
}
```
3. Indexing fails with mapper_parsing_exception:

> failed to parse date field [2019-06-28T08:30:39,104+0200] with format [strict_date_optional_time||epoch_millis]

4. Replace "," with "." and try to index:
```
POST date-test/_doc
{
  "time": "2019-06-28T08:30:39.104+0200"
}
```
5. Document is indexed successfully

### PR DESCRIPTION
**Pull request by pgomulka**
Joda allowed for `date_optional_time` and `strict_date_optional_time`  a decimal point to be `.` dot or `,` comma
For our java.time implementation we should also extend this for `strict_date_optional_time-nanos`
the approach to fix this is the same as in `iso8601` parser
closes #43730

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java [hunk 1]
```diff
@@ -139,6 +143,10 @@
         .appendFraction(NANO_OF_SECOND, 3, 9, true)
         .optionalEnd()
         .optionalStart()
+        .appendLiteral(",")
+        .appendFraction(NANO_OF_SECOND, 1, 9, false)
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: the above has the digits minimum as this is a strict date? Do the same here?

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java [hunk 2]
```diff
@@ -38,6 +38,21 @@
 
 public class JavaJodaTimeDuellingTests extends ESTestCase {
 
+    //these parsers should allow both ',' and '.' as a decimal point
+    public void testDecimalPointParsing(){
+        assertSameDate("2001-01-01T00:00:00.123Z", "strict_date_optional_time");
```
Comment (spinscale) [inline server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: I think parsing of a date like `2001-01-01T00:00:00.456,123Z` should not work because the nanos have already been parsed. Just want to be sure here.

**Review by spinscale — APPROVED** [review]
two minor nits, LGTM otherwise

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java (hunk 2 above)
Comment (pgomulka) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: fair point, the fix allows that atm

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java (hunk 1 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: will fix

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java (hunk 2 above)
Comment (spinscale) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: are you sure? I havent tested this, but this might throw an exception because of parsing the same type twice.

Comment (pgomulka) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: from the test I tried it was not failing. 
sadly java.time does not have the append method on a builder with multiple parsers
https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormatterBuilder.html#append-org.joda.time.format.DateTimePrinter-org.joda.time.format.DateTimeParser:A-

https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatterBuilder.html#append-java.time.format.DateTimeFormatter-

Comment (pgomulka) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: actually it fails when the value is different, like in your example 
`2001-01-01T00:00:00.456,123Z`
but will pass for
`2001-01-01T00:00:00.123,123Z`

**Comment by pgomulka** [comment]
@elasticsearch update branch

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
ok to test

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java (hunk 2 above)
Comment (pgomulka) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: just to give more explanation. This pattern will pass because of the logic in 
  DateTimeParseContext that won't raise an error when na value for the field is set twice but with the same value
```
int setParsedField(TemporalField field, long value, int errorPos, int successPos) {
        Objects.requireNonNull(field, "field");
        Long old = currentParsed().fieldValues.put(field, value);
        return (old != null && old.longValue() != value) ? ~errorPos : successPos;
    }
```

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
There are some other formats that use `.appendFraction(NANO_OF_SECOND, x, y, true)` that haven't been changed so far in this PR:

* `HOUR_MINUTE_SECOND_MILLIS_FORMATTER`
* `HOUR_MINUTE_SECOND_FRACTION_FORMATTER`
* `TIME_PREFIX`
* `DATE_TIME_FORMATTER`
* `ORDINAL_DATE_TIME_FORMATTER_BASE`

Would these have accepted both comma and dot in Joda?  If so, should they also be changed?

**Comment by pgomulka** [comment]
@droberts195 thanks for having a second look. I scan through the formatters and I think they all support only dot. We could consider relaxing them to accept comma as well, but I think we might as well stick with what was supported in Joda for now

`HOUR_MINUTE_SECOND_MILLIS_FORMATTER` used in `hour_minute_second_millis` was using `HH:mm:ss.SSS` pattern in Joda

`HOUR_MINUTE_SECOND_FRACTION_FORMATTER ` used in date_hour_minute_second_fraction was using `yyyy-MM-dd'T'HH:mm:ss.SSS` in Joda

`TIME_PREFIX ` used in `week_date_time` -> `xxxx-'W'ww-e'T'HH:mm:ss.SSSZZ` , `time` -> `HH:mm:ss.SSSZZ` , `t_time` ->`'T'HH:mm:ss.SSSZZ` 

`DATE_TIME_FORMATTER` used in `date_time` -> `yyyy-MM-dd'T'HH:mm:ss.SSSZZ` `ordinal_date_time`-> `yyyy-DDD'T'HH:mm:ss.SSSZZ` `basic_date_time`->`yyyyMMdd'T'HHmmss.SSSZ`  

ORDINAL_DATE_TIME_FORMATTER_BASE  used in `ordinal_date_time`->`yyyy-DDD'T'HH:mm:ss.SSSZZ` `strict_ordinal_date_time`->`yyyy-DDD'T'HH:mm:ss.SSSZZ`

**Comment by droberts195** [comment]
> we might as well stick with what was supported in Joda for now

Yes, definitely.  If 7.x does what 6.x did for those formats then we're good.  Thanks for rechecking those.
