### PR TITLE
Fix ClassCastException with MV_EXPAND on missing field

### LINKED ISSUE #109974: ES|QL: ClassCastException - Literal cannot be cast to NamedExpression  during local planning
The problem happened on a very wide index pattern, where most likely some nodes are executing an `MV_EXPAN` on an attribute that does not exist on the local shards.

The local planner is running [ReplaceMissingFieldWithNull](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java#L170) optimization and probably replacing the target of MV_EXPAND with a `Literal`, but MV_EXPAND defines it as `NamedExpression`.

Happens with the following queries:

```
FROM logs*
| MV_EXPAND tags
| sort tags
| LIMIT 1
```

```
FROM logs*
| MV_EXPAND tags
| WHERE tags == \"auditd-log\"
| LIMIT 1
```

For this second query, in my specific case it fails with some specific limits (eg. `LIMIT 10`) but not with higher limits (eg. `LIMIT 1000`)

```
java.lang.ClassCastException: class org.elasticsearch.xpack.esql.core.expression.Literal cannot be cast to class org.elasticsearch.xpack.esql.core.expression.NamedExpression (org.elasticsearch.xpack.esql.core.expression.Literal and org.elasticsearch.xpack.esql.core.expression.NamedExpression are in unnamed module of loader java.net.FactoryURLClassLoader @3ebc6d8b)
	at org.elasticsearch.xpack.esql.core.tree.NodeInfo$4.innerTransform(NodeInfo.java:146)
	at org.elasticsearch.xpack.esql.core.tree.NodeInfo.transform(NodeInfo.java:60)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformNodeProps(Node.java:260)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformPropertiesOnly(Node.java:240)
	at org.elasticsearch.xpack.esql.core.plan.QueryPlan.transformExpressionsOnlyUp(QueryPlan.java:91)
	at org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizer$ReplaceMissingFieldWithNull.missingToNull(LocalLogicalPlanOptimizer.java:168)
	at org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizer$ReplaceMissingFieldWithNull.lambda$apply$0(LocalLogicalPlanOptimizer.java:123)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:192)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$10(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformChildren(Node.java:211)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$10(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformChildren(Node.java:211)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$10(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformChildren(Node.java:211)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:190)
	at org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizer$ReplaceMissingFieldWithNull.apply(LocalLogicalPlanOptimizer.java:123)
	at org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizer$ReplaceMissingFieldWithNull.apply(LocalLogicalPlanOptimizer.java:119)
	at org.elasticsearch.xpack.esql.core.rule.ParameterizedRuleExecutor.lambda$transform$0(ParameterizedRuleExecutor.java:29)
	at org.elasticsearch.xpack.esql.core.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:88)
	at org.elasticsearch.xpack.esql.core.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:167)
	at org.elasticsearch.xpack.esql.core.rule.RuleExecutor.execute(RuleExecutor.java:136)
	at org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizer.localOptimize(LocalLogicalPlanOptimizer.java:98)
	at org.elasticsearch.xpack.esql.planner.PlannerUtils.lambda$localPlan$7(PlannerUtils.java:157)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$11(Node.java:198)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:192)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$10(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformChildren(Node.java:211)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:190)
	at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:198)
	at org.elasticsearch.xpack.esql.planner.PlannerUtils.localPlan(PlannerUtils.java:155)
	at org.elasticsearch.xpack.esql.planner.PlannerUtils.localPlan(PlannerUtils.java:144)
	at org.elasticsearch.xpack.esql.planner.PlannerUtils.localPlan(PlannerUtils.java:137)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:428)
	at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestExecutor.lambda$runBatch$2(ComputeService.java:653)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:248)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:57)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:54)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$acquireSearchContexts$23(ComputeService.java:511)
	at org.elasticsearch.base@8.15.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
	at org.elasticsearch.base@8.15.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.acquireSearchContexts(ComputeService.java:524)
	at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestExecutor.runBatch(ComputeService.java:650)
	at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestExecutor.onBatchCompleted(ComputeService.java:667)
	at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestExecutor.lambda$runBatch$1(ComputeService.java:657)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:248)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:269)
	at org.elasticsearch.compute.operator.DriverRunner$1.done(DriverRunner.java:84)
	at org.elasticsearch.compute.operator.DriverRunner$1.onResponse(DriverRunner.java:46)
	at org.elasticsearch.compute.operator.DriverRunner$1.onResponse(DriverRunner.java:43)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:248)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportResponseHandler$1.handleResponse(TransportResponseHandler.java:53)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportResponseHandler$Empty.handleResponse(TransportResponseHandler.java:43)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportResponseHandler$Empty.handleResponse(TransportResponseHandler.java:35)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1757)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1480)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1577)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1557)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/109974

`LocalLogicalPlanOptimizer.ReplaceMissingFieldWithNull` tries to replace missing fields (ie. fields that are not present on the mappings of local node) with a NULL literal.
This is not possible for MvExpand, because the target is a `NamedExpression` (and `Literal` is not). This caused `ClassCastException`.

This PR fixes the problem using a null `Alias` in this specific case.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java [hunk 1]
```diff
@@ -162,6 +163,15 @@ else if (plan instanceof Project project) {
...
+                // https://github.com/elastic/elasticsearch/issues/109974
+                // Unfortunately we cannot remove the MvExpand right away, or we'll lose the output field (layout problems)
+                // TODO but this could be a follow-up optimization
+                plan = plan.transformExpressionsOnlyUp(
+                    FieldAttribute.class,
+                    f -> stats.exists(f.qualifiedName()) ? f : new Alias(f.source(), f.name(), null, Literal.of(f, null), f.id())
+                );
             }
             // otherwise transform fields in place
             else {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:177]: Ehm, isn't the default case here just asking for trouble? We're replacing field attributes by literals; that's only safe to do further down in the expression tree (if at all). I wonder if we rather shouldn't optimize at all in these cases; or maybe have a version of `transformExpressionsOnlyUp` that never applies to the top-level expression. (Although that would still be unsafe in general, but could be acceptable here.)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java [hunk 2]
```diff
@@ -162,6 +163,15 @@ else if (plan instanceof Project project) {
...
                     plan = new Project(project.source(), plan, newProjections);
                 }
+            } else if (plan instanceof MvExpand) {
+                // We cannot replace the target (NamedExpression) with a Literal
+                // https://github.com/elastic/elasticsearch/issues/109974
+                // Unfortunately we cannot remove the MvExpand right away, or we'll lose the output field (layout problems)
+                // TODO but this could be a follow-up optimization
+                plan = plan.transformExpressionsOnlyUp(
+                    FieldAttribute.class,
+                    f -> stats.exists(f.qualifiedName()) ? f : new Alias(f.source(), f.name(), null, Literal.of(f, null), f.id())
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:173]: Hm, rather than replacing the expression but keeping the MV_EXPAND, wouldn't it be cleaner to replace the MV_EXPAND by an EVAL? That might profit better from our `EVAL` optimizations, pruning rules, etc. (if they're applied after this - didn't check.) or at least be easy to understand what to expect from.

E.g.
```
FROM idx
| MV_EXPAND field

becomes (if field is missing)

FROM idx
| EVAL field = null
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java [hunk 3]
```diff
@@ -181,6 +183,37 @@ public void testMissingFieldInSort() {
...
+     * \_Limit[1000[INTEGER]]
+     *   \_MvExpand[last_name{f}#9,last_name{r}#15]
+     *     \_Limit[1000[INTEGER]]
+     *       \_EsRelation[test][_meta_field{f}#11, emp_no{f}#5, first_name{f}#6, ge..]
+     */
+    public void testMissingFieldInMvExpand() {
+        var plan = plan("""
+              from test
+            | mv_expand last_name
+            | keep first_name
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java:198]: I think this should be
```
| keep last_name
```

This may (in the future) make this test fail (for the wrong reasons): `last_name` is irrelevant and may be pruned.

**Review by alex-spies — APPROVED** [review]
Thanks Luigi, nice catch!

I have some minor remarks, but this LGTM!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:177]: That's a reasonable concern, probably we should not optimize at all

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:173]: I considered it as a follow-up. 
I didn't do it with this PR because it can be slightly tricky and I wanted to treat it as an optimization rather than a fix.
In particular, in the example you propose, `field` represents two different things:
- for MV_EXPAND it's the target; the output will have the same name but a different ID
- for EVAL it's a completely new field, that will need mask the previous one and have the same ID as the output for MV_EXPAND.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:174]: OK, I removed the optimization for now

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:174]: Oh, you mean the final `else`. Yes, that's fragile and could lead to more similar failures when we add new commands.

I didn't change it because it's needed to trigger a few more downstream optimizations, see all the `LocalLogicalPlanOptimizerTests.testMissingField*` tests, and because it's relatively safe with current feature set.

It's worth remembering that it's dangerous though, I'll open an issue so that we can revisit it.

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:174]: https://github.com/elastic/elasticsearch/issues/110150

**Comment by astefan** [comment]
Please, hold on on merging this PR.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by luigidellaquila** [comment]
Thanks folks! Merging

**Comment by luigidellaquila** [comment]
Manual backport https://github.com/elastic/elasticsearch/pull/110264
