### PR TITLE
ESQL: Catch parsing exception

### LINKED ISSUE #119025: Server error while parsing ESQL query
### Elasticsearch Version

9.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

The following error was observed. Unfortunately the query that leads to this is not known (the author was experimenting and does not remember what it was), it is possible that it is an invalid query. In that case this error should not be a server error but a client error.

```
java.util.EmptyStackException
at org.antlr.v4.runtime.Lexer.popMode(Lexer.java:192)
at org.antlr.v4.runtime.atn.LexerPopModeAction.execute(LexerPopModeAction.java:58)
at org.antlr.v4.runtime.atn.LexerActionExecutor.execute(LexerActionExecutor.java:168)
at org.antlr.v4.runtime.atn.LexerATNSimulator.accept(LexerATNSimulator.java:366)
at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:299)
at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
at org.elasticsearch.xpack.esql.parser.EsqlParser$ParametrizedTokenSource.nextToken(EsqlParser.java:169)
at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:136)
at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:515)
at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:371)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.booleanExpression(EsqlBaseParser.java:912)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.whereCommand(EsqlBaseParser.java:695)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.processingCommand(EsqlBaseParser.java:547)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.query(EsqlBaseParser.java:347)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.singleStatement(EsqlBaseParser.java:230)
at org.elasticsearch.xpack.esql.parser.EsqlParser.invokeParser(EsqlParser.java:100)
at org.elasticsearch.xpack.esql.parser.EsqlParser.createStatement(EsqlParser.java:63)
at org.elasticsearch.xpack.esql.session.EsqlSession.parse(EsqlSession.java:269)
at org.elasticsearch.xpack.esql.session.EsqlSession.execute(EsqlSession.java:154)
at org.elasticsearch.xpack.esql.execution.PlanExecutor.esql(PlanExecutor.java:80)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.innerExecute(TransportEsqlQueryAction.java:186)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$execute$1(TransportEsqlQueryAction.java:156)
at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:452)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.execute(TransportEsqlQueryAction.java:156)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.execute(TransportEsqlQueryAction.java:56)
at org.elasticsearch.xpack.esql.core.async.AsyncTaskManagementService.asyncExecute(AsyncTaskManagementService.java:188)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.doExecuteForked(TransportEsqlQueryAction.java:140)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$doExecute$0(TransportEsqlQueryAction.java:132)
at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
```

### Steps to Reproduce

N/A

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by costin**
When an invalid popMode occurs (due to an invalid query), ANTLR throws
 an out-of-channel exception, bypassing the existing checks.
This PR extends the checks and properly reports the error back to the
 user

Fix #119025

### CODE REVIEW

**Review by fang-xing-esql — APPROVED** [review]
LGTM!

**Comment by costin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/124972)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/124973)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/124974)|
|✅|8.17|[](https://github.com/elastic/elasticsearch/pull/124975)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by costin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/124976)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by costin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/124980)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by costin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/124981)|
|✅|8.17|[](https://github.com/elastic/elasticsearch/pull/124982)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by costin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/124983)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java [hunk 1]
```diff
@@ -153,6 +154,9 @@ private <T> T invokeParser(
             return result.apply(new AstBuilder(new ExpressionBuilder.ParsingContext(params, metrics)), tree);
         } catch (StackOverflowError e) {
             throw new ParsingException("ESQL statement is too large, causing stack overflow when generating the parsing tree: [{}]", query);
+            // likely thrown by an invalid popMode (such as extra closing parenthesis)
+        } catch (EmptyStackException ese) {
+            throw new ParsingException("Invalid query [{}]", query);
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java:159]: Unfortunately exception is very generic and does not bring any details on position, 
however I wonder if we could make any assumptions as for what went wrong here? 

It might be frustrating to see message like this for not too complex query like:
```
                stats
                min = min(a),
                max = max(a)) WHERE (a % 3 > 10 OR a / 2 > 100),
                avg = avg(a) WHERE a / 2 > 100
                BY a
```
note `max(a))`.

We know this could be caused by extra `)` or `]`. I wonder if we should attempt to count them in here to highlight this could be an issue?
