### PR TITLE
Fix early termination of search request with sort optimization

### LINKED ISSUE #72661: Index sorting causes illegal_state_exception
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12

**Plugins installed**: [analysis-stempel]

**JVM version** (`java -version`): built-in version

**OS version** (`uname -a` if on a Unix-like system): `Linux hostname 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Expected index sorting to speed up AND conjunctions and not to raise illegal_state_exception.

**Steps to reproduce**:

Used index structure:
```json
{
  "index_name": {
    "mappings": {
      "dynamic": "false",
      "properties": {
        "brand_id": { "type": "keyword" },
        "category_id": { "type": "keyword" },
        "status_id": { "type": "keyword" },
        "user_id": { "type": "keyword" },
        "price": { "type": "scaled_float", "scaling_factor": 100.0 },
        "created_at": { "type": "date" }
      }
    },
    "settings": {
      "index": {
        "number_of_shards": 3,
        "refresh_interval": "1h",
        "sort": {
          "field": ["category_id", "brand_id", "status_id", "created_at"],
          "order": ["asc", "asc", "asc", "desc"]
        }
      }
    }
  }
}
```

Search query:
```json
{
  "_source": false,
  "size": 24,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "category_id": 197
          }
        },
        {
          "term": {
            "brand_id": 51
          }
        },
        {
          "term": {
            "status_id": 2
          }
        },
        {
          "range": {
            "price": {
              "gte": 2.0,
              "lte": 5.0
            }
          }
        }
      ],
      "must_not": {
        "terms": {
          "user_id": [12345]
        }
      }
    }
  },
  "sort": {
    "created_at": "desc"
  }
}
```

And then the raised exception:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "topDocs already consumed"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "index_name",
        "node": "lx9S3vwES4y2n2xa-PFyUw",
        "reason": {
          "type": "illegal_state_exception",
          "reason": "topDocs already consumed"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "topDocs already consumed",
      "caused_by": {
        "type": "illegal_state_exception",
        "reason": "topDocs already consumed"
      }
    }
  },
  "status": 500
}
```

- Index contains about 100M documents and weighs about 10GiB
- Peaks to 12.000 search requests per minute

This was an experiment to improve search query performance and I assumed that [index sorting](https://www.elastic.co/blog/index-sorting-elasticsearch-6-0) would speed up AND conjuctions given that my query is fairly simple. However, I've had mixed results. Some queries ran faster and others started raising illegal_state_exception exceptions. I've tried changing number_of_shards, sorting criteria but the problem persisted. It got worse when I tried putting everything into 1 shard and would raise an exception on every 2nd request.

### PR DESCRIPTION
**Pull request by jimczi**
The query phase applies an optimization when sorting by a numeric field.
This optimization doesn't handle early termination correctly when `timeout`
and/or `terminate_after` are used. An IAE exception is thrown at the shard
level when the timeout is reached.
This commit fixes the bug, early terminated exceptions are correctly caught
and the result is computed from the documents that the shard was able to collect
before the termination.

Closes #72661

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/query/QueryPhase.java [hunk 1]
```diff
@@ -387,17 +391,37 @@ private static boolean searchWithCollectorManager(SearchContext searchContext, C
...
+        TopFieldDocs mergedTopDocs = sharedManager.reduce(collectors);
+        // Lucene sets shards indexes during merging of topDocs from different collectors
+        // We need to reset shard index; ES will set shard index later during reduce stage
+        for (ScoreDoc scoreDoc : mergedTopDocs.scoreDocs) {
+            scoreDoc.shardIndex = -1;
+        }
+        if (totalHits != null) { // we have already precalculated totalHits for the whole index
+            mergedTopDocs = new TopFieldDocs(totalHits, mergedTopDocs.scoreDocs, mergedTopDocs.fields);
         }
+        queryResult.topDocs(new TopDocsAndMaxScore(mergedTopDocs, Float.NaN), sortAndFormats.formats);
```
Comment (mayya-sharipova) [inline server/src/main/java/org/elasticsearch/search/query/QueryPhase.java:424]: Great fix! Looks like `topDocs` were never set if `TimeExceededException` or `EarlyTerminationException` was raised.

File: server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java [hunk 2]
```diff
@@ -130,7 +130,7 @@ public ShardSearchRequest(ShardId shardId,
                               long nowInMillis,
                               AliasFilter aliasFilter) {
         this(OriginalIndices.NONE, shardId, -1, -1, SearchType.QUERY_THEN_FETCH, null, null,
-            aliasFilter, 1.0f, false, null, nowInMillis, null, null, null);
+            aliasFilter, 1.0f, true, null, nowInMillis, null, null, null);
```
Comment (mayya-sharipova) [inline server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java:133]: What's the reason of setting `allowPartialSearchResults` to `true` here?

I've checked and this constructor besides tests is used only in validate, explain and field capabilities actions.  I guess it is fine to return partial results here.

File: server/src/test/java/org/elasticsearch/search/query/QueryPhaseTests.java [hunk 3]
```diff
@@ -749,6 +748,37 @@ public void testNumericLongOrDateSortOptimization() throws Exception {
             assertEquals(numDocs, totalHits.value);
         }
 
+        {
+            // 7. Test a sort with terminate after
```
Comment (mayya-sharipova) [inline server/src/test/java/org/elasticsearch/search/query/QueryPhaseTests.java:752]: Nice tests!

**Review by mayya-sharipova — APPROVED** [review]
@jimczi Thanks Jim! Great fix!

File: server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java (hunk 2 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java:133]: Because the default value is true so it should be reflected here too.
