### PR TITLE
Fix TextFieldMapper Retaining a Reference to its Builder

### LINKED ISSUE #73845: Reduce memory footprint of TextFieldMapper
Having a larger number of mapped fields consumes quite a bit of heap memory. TextFieldMapper holds onto its builder object,  which results in a simple field definition to easily hold onto 7KB of heap memory. This means that on a small node (1GB heap), 20k fields (e.g. 20 indices with 1000 fields each) can result in 150MB of memory being used purely for the mappings.

Relates https://github.com/elastic/elasticsearch/pull/63269

### PR DESCRIPTION
**Pull request by original-brownbear**
Fixes the text field mapper and the analyzers class that also retained parameter references that go really heavy.
Makes `TextFieldMapper` take ~200b for the text fields in the beats mapping, compared to ~5kb per instance before.

closes #73845

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 1]
```diff
@@ -1003,23 +1030,24 @@ protected void doXContentBody(XContentBuilder builder, Params params) throws IOE
         // this is a pain, but we have to do this to maintain BWC
         boolean includeDefaults = params.paramAsBoolean("include_defaults", false);
         builder.field("type", contentType());
-        this.builder.index.toXContent(builder, includeDefaults);
-        this.builder.store.toXContent(builder, includeDefaults);
+        final Builder b = (Builder) getMergeBuilder();
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1033]: Not the nicest approach to this I guess, but it should create the correct serialization as far as I understand?

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Alan!
