### PR TITLE
[Transform] fix transform failure for configs with no field parameter 

### LINKED ISSUE #67333: [Transform] transform fails with "specified fields can't be null or empty"
found by @szabosteve 

**Affected versions:** 7.9.3 -

The transform fails calling `_preview` or on `_start` with the error message: `specified fields can't be null or empty`. This happens for transforms that don't use any `field` parameter in either `group_by` or `aggregation`, e.g. because in `group_by`/`aggregation` only scripts are used or a `filter` aggregation without a child aggregation (for a full example see below).

**Mitigation:**

Create the destination index, before starting the transform yourself, e.g. `PUT myindex`.

**or** 

Add an aggregation that uses a `field` into your config, e.g:

```
    "aggregations": {
      "count": {
        "value_count": {
          "field": "my_grouping_field"
        }
      },
```

**Solution:**

The bug is a regression of #62945. In a special case transform tries to retrieve field capabilities for 0 fields, which is not allowed. 

full failure example:

```
POST _transform/_preview
{
  "source": {
    "index": [
      "kibana_sample_data_logs"
    ]
  },
  "pivot": {
    "group_by": {
      "agent": {
        "terms": {
          "script": {
            "source": """String agent = doc['agent.keyword'].value;
            if (agent.contains("MSIE")) {
              return "internet explorer";
            } else if (agent.contains("AppleWebKit")) {
              return "safari";
            } else if (agent.contains('Firefox')) {
              return "firefox";
            } else { return agent }""",
            "lang": "painless"
          }
        }
      }
    },
    "aggregations": {
      "200": {
        "filter": {
          "term": {
            "response": "200"
          }
        }
      },
      "404": {
        "filter": {
          "term": {
            "response": "404"
          }
        }
      },
      "503": {
        "filter": {
          "term": {
            "response": "503"
          }
        }
      }
    }
  }
}
```

Error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "specified fields can't be null or empty"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "specified fields can't be null or empty"
  },
  "status" : 400
}
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
avoid illegal argument exception when fields is empty, which is a valid case

fixes #67333

### CODE REVIEW

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtilTests.java [hunk 1]
```diff
@@ -71,4 +87,114 @@ public void testConvertToIntegerTypeIfNeeded() {
...
+                    assertNotNull(mappings);
+                    assertEquals(2, mappings.size());
+                    assertEquals("long", mappings.get("field-1"));
+                    assertEquals("long", mappings.get("field-2"));
+                }
+            );
+        }
+    }
+
+    private class FieldCapsMockClient extends NoOpClient {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtilTests.java:146]: `static`?

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtilTests.java [hunk 2]
```diff
@@ -71,4 +87,114 @@ public void testConvertToIntegerTypeIfNeeded() {
...
+        @Override
+        protected <Request extends ActionRequest, Response extends ActionResponse> void doExecute(
+            ActionType<Response> action,
+            Request request,
+            ActionListener<Response> listener
+        ) {
+            if (request instanceof FieldCapabilitiesRequest) {
+                FieldCapabilitiesRequest fieldCapsRequest = (FieldCapabilitiesRequest) request;
+                Map<String, Map<String, FieldCapabilities>> responseMap = new HashMap<>();
+                for (String field : ((FieldCapabilitiesRequest) request).fields()) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtilTests.java:161]:
```suggestion
                for (String field : fieldCapsRequest.fields()) {
```
