### PR TITLE
Require and preserve content type for filtered rest requests 

### LINKED ISSUE #84784: NPE when auditing REST requests with filtered fields
When auditing is configured to `emit_request_body` for REST requests, it results into NullPointerException while trying to auditing the request body. 

A minimal reproduction:
```
// Audit log configuration

xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.emit_request_body: true
xpack.security.audit.logfile.events.include: _all

// Create a User
PUT _security/user/foo
{"password":"password","roles":["superuser"]}
```

The above results into a 401 error with `null_pointer_exception` as its `caused_by`.

The problem is likely caused by #79814 which refactored how `RestRequest` is instantiated from another `RestRequest`. The new code does not set `xContentType` which means it is `null` and is rejected by `XContentHelper#converToJson`:
https://github.com/elastic/elasticsearch/blob/987a83b93ef0f705dbdc5837c5a71c88f579a191/server/src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java#L310-L312

### PR DESCRIPTION
**Pull request by albertzaharovits**
`RestRequest#getXContentType` cannot normally be `null` for a request with
a non-empty request body, or the rest controll will reject the request, see eg
`RestControllerTests#testUnknownContentWithContentStream`.
This PR fixes sloppy behavior where the `RestRequestFilter` cleared the
`xContentType` field of the filtered request.

Fixes https://github.com/elastic/elasticsearch/issues/84784

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java [hunk 1]
```diff
@@ -123,10 +123,14 @@ private RestRequest(
         this.requestId = requestId;
     }
 
-    protected RestRequest(RestRequest other) {
+    // public for test
```
Comment (tvernum) [inline server/src/main/java/org/elasticsearch/rest/RestRequest.java:126]: I think it would be preferable to use an anonymous class in `RestRequestFilterTests` and keep this constructor `protected`

File: server/src/test/java/org/elasticsearch/rest/RestControllerTests.java [hunk 2]
```diff
@@ -393,10 +396,13 @@ public void testDispatchDoesNotRequireContentTypeForRequestsWithoutContent() {
...
         String content = randomAlphaOfLength((int) Math.round(BREAKER_LIMIT.getBytes() / inFlightRequestsBreaker.getOverhead()));
-        FakeRestRequest fakeRestRequest = new FakeRestRequest.Builder(NamedXContentRegistry.EMPTY).withContent(
-            new BytesArray(content),
-            null
-        ).withPath("/foo").withHeaders(Collections.singletonMap("Content-Type", Collections.singletonList("text/plain"))).build();
+        RestRequest fakeRestRequest = new FakeRestRequest.Builder(NamedXContentRegistry.EMPTY).withContent(new BytesArray(content), null)
+            .withPath("/foo")
+            .withHeaders(Collections.singletonMap("Content-Type", Collections.singletonList("text/plain")))
+            .build();
+        if (randomBoolean()) {
```
Comment (pgomulka) [inline server/src/test/java/org/elasticsearch/rest/RestControllerTests.java:403]: I wonder if it is better to have separate tests that only focus on this copying constructor and content type being null?

**Review by pgomulka — APPROVED** [review]
LGTM, 
I left one question but it looks good either way

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java (hunk 1 above)
Comment (albertzaharovits) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java]: Nice hint, thanks!
This trick for circumventing protected member access on public classes is not something I think about, I admit. Looks preferable indeed, I'll keep it in mind further.

Comment (albertzaharovits) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java]: 3d23eff

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/part-1
