### PR TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/watcher/example-watches/example-watch-clusterstatus/line_137} failing - (#115809)

### LINKED ISSUE #115809: [CI] DocsClientYamlTestSuiteIT test {yaml=reference/watcher/example-watches/example-watch-clusterstatus/line_137} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4594 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/giwccsqfhdv3o)
- [elasticsearch-pull-request #38383 / part-1](https://gradle-enterprise.elastic.co/s/22ob6xifrxg4q)

**Reproduction Line:**
```
./gradlew ":docs:yamlRestTest" --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/watcher/example-watches/example-watch-clusterstatus/line_137}" -Dtests.seed=451EC8FFC95CB241 -Dtests.locale=pa -Dtests.timezone=America/Yellowknife -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3Dreference%2Fwatcher%2Fexample-watches%2Fexample-watch-clusterstatus%2Fline_137%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [DELETE], host [http://[::1]:39035], URI [*,-.ds-ilm-history-*,-.ds-.slm-history-*,-.ds-.watcher-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.triggered_watches], but in a future major version, direct access to system indices will be prevented by default]
{"acknowledged":true}
```

**Issue Reasons:**
- [main] 2 failures in test test {yaml=reference/watcher/example-watches/example-watch-clusterstatus/line_137} (0.3% fail rate in 632 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116884: [CI] DocsClientYamlTestSuiteIT test {yaml=reference/rest-api/watcher/put-watch/line_120} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4867 / sles-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/34refx7grz27m)
- [elasticsearch-periodic-platform-support #4764 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/5gzvly4fkhp7y)

**Reproduction Line:**
```
./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/rest-api/watcher/put-watch/line_120}" -Dtests.seed=B9283981C75EF538 -Dtests.locale=en-BS -Dtests.timezone=Asia/Yerevan -Druntime.java=22
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3Dreference%2Frest-api%2Fwatcher%2Fput-watch%2Fline_120%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [DELETE], host [http://[::1]:43119], URI [*,-.ds-ilm-history-*,-.ds-.slm-history-*,-.ds-.watcher-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.triggered_watches], but in a future major version, direct access to system indices will be prevented by default]
{"acknowledged":true}
```

**Issue Reasons:**
- [8.15] 2 failures in test test {yaml=reference/rest-api/watcher/put-watch/line_120} (0.3% fail rate in 647 executions)
- [8.15] 2 failures in pipeline elasticsearch-periodic-platform-support (9.5% fail rate in 21 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lukewhiting**
Sometimes a watch can run during a YAML test, creating some history indices. During test cleanup these get deleted but can throw a warning if these systems indices exist and have been deleted.

This patch introduces code to swallow (but log) system index access warnings during YAML test cluster cleanup.

Fixes #115809
Fixes #116884

### CODE REVIEW

**Comment by nielsbauman** [comment]
Don't forget to remove the entries from `muted-tests.yml`.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -1131,6 +1135,19 @@ protected static void wipeAllIndices(boolean preserveSecurityIndices) throws IOE
             }
             final Request deleteRequest = new Request("DELETE", Strings.collectionToCommaDelimitedString(indexPatterns));
             deleteRequest.addParameter("expand_wildcards", "open,closed,hidden");
+
+            // If system index warning, ignore but log
+            deleteRequest.setOptions(RequestOptions.DEFAULT.toBuilder().setWarningsHandler(warnings -> {
```
Comment (nielsbauman) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1140]: I know we talked about this yesterday in the team meeting, but I don't remember if we talked about excluding the `triggered-watches` data stream from this DELETE request. Is that not an option?

Comment (lukewhiting) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1140]: I don't remember discussing that but I was a bit hesitant to do that as I _think_ there's logic that reads that index and may affect the execution / retrieval of watches if it's left over between tests.

Perhaps @masseyke can weigh in here if he thinks it's safe to keep between tests?

**Comment by lukewhiting** [comment]
> Don't forget to remove the entries from `muted-tests.yml`.

🤦🏻‍♂️ Yep totally forgot...

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (lukewhiting) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1123]: Did a bit more digging and yes `.triggered-watches` hanging around between tests does affect watch execution (see https://github.com/elastic/elasticsearch/blob/8efd08b019b9160f5e703520c6ce3b6a9f92cfbd/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/execution/TriggeredWatchStore.java#L121) so I think it's best we tidy it up.

@nielsbauman Are you happy with that conclusion?

**Review by nielsbauman — APPROVED** [review]
Thanks for investigating, @lukewhiting! This LGTM, but I think it makes sense if @masseyke also has a quick look anyway - since this is concerning watcher.

**Review by masseyke — APPROVED** [review]
I think it seems reasonable. It's worth pinging @smalyshev since we're kind of expanding the fix he just did in https://github.com/elastic/elasticsearch/pull/117301.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -1112,7 +1116,22 @@ protected static void wipeAllIndices(boolean preserveSecurityIndices) throws IOE
...
             final Request deleteRequest = new Request("DELETE", Strings.collectionToCommaDelimitedString(indexPatterns));
             deleteRequest.addParameter("expand_wildcards", "open,closed,hidden");
-            deleteRequest.setOptions(deleteRequest.getOptions().toBuilder().setWarningsHandler(ignoreAsyncSearchWarning()).build());
+
+            // If system index warning, ignore but log
+            // See: https://github.com/elastic/elasticsearch/issues/117099
+            // and: https://github.com/elastic/elasticsearch/issues/115809
+            deleteRequest.setOptions(RequestOptions.DEFAULT.toBuilder().setWarningsHandler(warnings -> {
+                for (String warning : warnings) {
+                    if (warning.startsWith("this request accesses system indices:")) {
```
Comment (smalyshev) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1125]: I wonder if shutting down warnings about *all* system indexes is going a bit too far here. Maybe having an list of allowed ones would be better? Also, maybe there's a way to clean up that before we get here? For async unfortunately there isn't since it can be created by multiple APIs which don't have cleanup functions right now, but not sure what the status with watches.

Comment (lukewhiting) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1125]: Thanks for taking a look @smalyshev! To follow up your points:

> I wonder if shutting down warnings about all system indexes is going a bit too far here

I did wonder that too but I also was struggling to think when failing the test due to a warning on cleanup would be helpful information... The request succeeded and the index is deleted, the warning is a known side effect of what we are doing here so this just feels like noise...

> Maybe having an list of allowed ones would be better?

That's possible but difficult in our case. `.triggered-watches` is a data stream (I think? Or at least ILM managed) so the actual index name in the error will change over time. We could do some pattern matching on the warning text but that starts to feel quite fragile...

> maybe there's a way to clean up that before we get here? For async unfortunately there isn't

Alas this is one of those async cases... Watches can run in the background between tests and cause this index to appear and need cleaning up at any time.


I'm happy to add some more complex pattern matching to this but I would be interested to know the problem it would be solving (Not saying there isn't one, More likely I'm just to new here to spot it yet 😃).

Comment (lukewhiting) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1125]: Reply by @smalyshev via DM:

```19:29
Stas Malyshev

Two notes there: 1. I'd like to keep the warnings handler code separate if possible, code with multiple levels of lambdas nested into each other is kinda hard to read, imho

2. Even if .triggered-watches is a data stream, we still could scan the list and use startsWith to check for specific warnings, not? If it's too hard though then I think it's ok to ignore all system indices there probably```

Comment (lukewhiting) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I have moved the warning handler to it's own method to stop the nested lambdas.

The problem with checking which index threw the warning is that it's part way through the warning message so there would need to be code to extract it, then do the starts with.

I feel that with the fragility of such string parsing code (Especially when we have no guarantees on the future consistency of that warning message) and the probability of other indices cropping up in the future that need ignoring, IT's best to just deal with this once and be done with it.

That said, if anyone can come up with a downside to muting all warnings during this cleanup, I'm happy to do a u-turn and get that ignore list function in place.

**Review by smalyshev — APPROVED** [review]

**Comment by smalyshev** [comment]
The tag `v6.8.18` looks weird though - did you mean 8.18?
