### PR TITLE
Account for simulated utilization threshold in WriteLoadConstraintDeciderIT

### LINKED ISSUE #133857: [CI] WriteLoadConstraintDeciderIT testHighNodeWriteLoadPreventsNewShardAllocation failing
**Build Scans:**
- [elasticsearch-intake #27742 / part1](https://gradle-enterprise.elastic.co/s/sz4rszmymyvoc)
- [elasticsearch-pull-request #89032 / part-1](https://gradle-enterprise.elastic.co/s/fvvg63nnl4ina)
- [elasticsearch-pull-request #89028 / part-1](https://gradle-enterprise.elastic.co/s/lrutdiezndkhg)
- [elasticsearch-intake #27741 / part1](https://gradle-enterprise.elastic.co/s/6kjiij6ibdgmi)
- [elasticsearch-pull-request #89024 / part-1](https://gradle-enterprise.elastic.co/s/sdxofz67oocko)
- [elasticsearch-pull-request #89023 / part-1](https://gradle-enterprise.elastic.co/s/u7mqxcebq3x3s)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.routing.allocation.decider.WriteLoadConstraintDeciderIT.testHighNodeWriteLoadPreventsNewShardAllocation" -Dtests.seed=15D5DF8195D36D11 -Dtests.locale=hi -Dtests.timezone=Asia/Srednekolymsk -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.routing.allocation.decider.WriteLoadConstraintDeciderIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testHighNodeWriteLoadPreventsNewShardAllocation'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 2 consecutive failures in step part1
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 6 failures in test testHighNodeWriteLoadPreventsNewShardAllocation (66.7% fail rate in 9 executions)
- [main] 2 failures in step part1 (100.0% fail rate in 2 executions)
- [main] 4 failures in step part-1 (57.1% fail rate in 7 executions)
- [main] 2 failures in pipeline elasticsearch-intake (100.0% fail rate in 2 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (57.1% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
Occasionally the `WriteLoadConstraintDecider` would prevent shards moving to node 2 because those moves would exceed the utilisation threshold

I ran the test with all the extremes and it still works (i.e. `randomUtilizationThresholdPercent = 50`, `numberOfWritePoolThreads = 10`, `shardWriteLoad = 0.2`, `randomNumberOfShards = 20`) 

Resolves: #133857

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java [hunk 1]
```diff
@@ -68,6 +68,8 @@ protected Collection<Class<? extends Plugin>> getMockPlugins() {
      */
     public void testHighNodeWriteLoadPreventsNewShardAllocation() {
         int randomUtilizationThresholdPercent = randomIntBetween(50, 100);
+        int numberOfWritePoolThreads = randomIntBetween(10, 20);
+        double shardWriteLoad = randomDoubleBetween(0.0, 0.2, true);
```
Comment (nicktindall) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: Would probably be a lot easier to reason about if shard write loads were zero (then there would be no risk of the decider preventing the movement because it would overload the target), but also less realistic.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java [hunk 2]
```diff
@@ -68,6 +68,8 @@ protected Collection<Class<? extends Plugin>> getMockPlugins() {
      */
     public void testHighNodeWriteLoadPreventsNewShardAllocation() {
         int randomUtilizationThresholdPercent = randomIntBetween(50, 100);
+        int numberOfWritePoolThreads = randomIntBetween(10, 20);
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: I think the lower bound of the randomization should be 2 since that's a realistic setup.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java [hunk 3]
```diff
@@ -154,19 +160,19 @@ public void testHighNodeWriteLoadPreventsNewShardAllocation() {
...
-            0.5f,
+            numberOfWritePoolThreads,
+            randomIntBetween(0, maxUtilizationPercent) / 100f,
             0
         );
         final NodeUsageStatsForThreadPools thirdNodeHotSpottingNodeStats = createNodeUsageStatsForThreadPools(
             thirdDiscoveryNode,
-            2,
+            numberOfWritePoolThreads,
             randomUtilizationThresholdPercent + 1 / 100,
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: Should this be `randomIntBetween(0, maxUtilizationPercent) / 100f,` as well?

**Review by ywangd — COMMENTED** [review]
Some minor comments

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java (hunk 3 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: No, the test works by
1. Create an index while `cluster.routing.allocation.exclude._name = "secondDataNode, thirdDataNode"` (all shards are assigned to `firstDataNode`)
2. Mock the `TransportNodeUsageStatsForThreadPoolsAction` on the three data nodes such that the first and second nodes report being under the utilisation threshold, and the third node reports being over the utilisation threshold.
     - Also mock the shard write load responses (random between 0 and something, I don't think this is critical to the test)
4. Refresh cluster info
5. Update `cluster.routing.allocation.exclude._name = "firstDataNode"`
6. Wait to see all the shards relocated to `secondDataNode` because first is excluded, and third is over the utilisation threshold.

So we have to have it over the threshold here.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java [hunk 4]
```diff
@@ -115,7 +117,11 @@ public void testHighNodeWriteLoadPreventsNewShardAllocation() {
         );
 
         String indexName = randomIdentifier();
-        int randomNumberOfShards = randomIntBetween(15, 40); // Pick a high number of shards, so it is clear assignment is not accidental.
+        int randomNumberOfShards = randomIntBetween(10, 20); // Pick a high number of shards, so it is clear assignment is not accidental.
+
+        // Calculate the maximum utilization a node can report while still being able to accept all relocating shards
+        double additionalLoadFromAllShards = (shardWriteLoad * randomNumberOfShards) / numberOfWritePoolThreads;
```
Comment (DiannaHohensee) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: Could you make this a method helper in this test file -- takes total shard write load, number of threads, returns needed overheard?

I lean towards making this sort of calculation a static method on the `ShardMovementWriteLoadSimulator`, because it's fragile to simulator calculation changes, but of more immediately interest is we will likely repeat this calculation for future testing.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java (hunk 1 above)
Comment (DiannaHohensee) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: The only constraint for the shard write load in this test is that it is [greater than zero](https://github.com/elastic/elasticsearch/blob/de98e5d71badf3b407a018a87bccba2c4191136f/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDecider.java#L46-L51) so that the WriteLoadDecider considers it. So we could use a very small shard write load. I didn't originally realize the simulator factor when writing this test, clearly :) So I just picked a random value.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java (hunk 2 above)
Comment (DiannaHohensee) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: Lowering the thread count might result in the shards being unable to fit on a single node, I expect. Not sure how much we care about realism. We could lower the shardWriteLoad to 0.001, to remove that concern -- and give the threshold randomization a bigger range of values.

**Review by DiannaHohensee — APPROVED** [review]
Thanks for diagnosing and fixing this, Nick! I left a few cosmetic requests, but lgtm.

Could you change the commit message to something like "Account for simulated utilization threshold in WriteLoadConstraintDeciderIT" ? Fix is very vague.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java (hunk 2 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: Fixed in ba15f8fd19d026cb4e09badbd4b9007dc064cea3

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java (hunk 1 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: Ahh of course... I changed `lowerInclusive` to `false` in ba15f8fd19d026cb4e09badbd4b9007dc064cea3 to ensure we don't get zeros

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java (hunk 4 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/decider/WriteLoadConstraintDeciderIT.java]: It's a bit basic, but I added it here. Perhaps having a name for it makes it clearer what's going on 946469e88237b0c10a699733abbda40db637fc83
