### PR TITLE
Fix reindex test failing in release builds

### LINKED ISSUE #143545: [CI] ReindexRemoteIT testGetReindexDescriptionStripsRemoteInfoSensitiveFields failing
**Build Scans:**
- [elasticsearch-periodic #11953 / release-tests](https://gradle-enterprise.elastic.co/s/6bqyx43rzcsrm)
- [elasticsearch-periodic #11953 / release-tests](https://gradle-enterprise.elastic.co/s/pcid73yeg6zzu)

**Reproduction Line:**
```
./gradlew ":modules:reindex-management:javaRestTest" --tests "org.elasticsearch.reindex.management.ReindexRemoteIT.testGetReindexDescriptionStripsRemoteInfoSensitiveFields" -Dtests.seed=7105844267E61324 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=bn -Dtests.timezone=Pacific/Noumea -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reindex.management.ReindexRemoteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGetReindexDescriptionStripsRemoteInfoSensitiveFields'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:32929], URI [/_reindex/iXnLv8WhSF2lV_8n4-YBlg:49?wait_for_completion=true], status line [HTTP/1.1 400 Bad Request]
{"error":"no handler found for uri [/_reindex/iXnLv8WhSF2lV_8n4-YBlg:49?wait_for_completion=true] and method [GET]"}
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 failures in test testGetReindexDescriptionStripsRemoteInfoSensitiveFields (3.6% fail rate in 56 executions)
- [main] 2 failures in step release-tests (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by szybia**
- Tested locally test is skipped if i hardcode `REINDEX_RESILIENCE_ENABLED = false`

Closes #143545

### CODE REVIEW

File: modules/reindex-management/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexRemoteIT.java [hunk 1]
```diff
@@ -46,6 +47,10 @@ private String getRemoteHost() throws Exception {
     }
 
     public void testGetReindexDescriptionStripsRemoteInfoSensitiveFields() throws Exception {
+        assumeTrue(
+            "reindex resilience endpoints available",
+            clusterHasCapability("GET", "/_reindex/{task_id}", List.of(), List.of("reindex_management_api")).orElse(false)
```
Comment (joshua-adams-1) [inline modules/reindex-management/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexRemoteIT.java:52]: What does this do?

Comment (szybia) [reply modules/reindex-management/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexRemoteIT.java:52]: it uses the REST capabilities API to check that a clusters endpoint has a capability

same thing that yaml REST tests do, [for example](https://github.com/szybia/elasticsearch/blob/8d51a8af0d8886dec46971b6b4bdf7fee4a77c60/modules/reindex-management/src/yamlRestTest/resources/rest-api-spec/test/reindex/10_get_reindex.yml#L1-L8)

so if the feature flag is disabled, the endpoint is never registered, and capabilities will return false

just for completion, AFAIK if anything here doesn't match up (different verb, different endpoint, or the endpoint exists but doesn't have the capability), this will return false

Comment (szybia) [reply modules/reindex-management/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexRemoteIT.java:52]: you can read more about capabilities [here](https://github.com/szybia/elasticsearch/blob/4a8d2bb04865bd5b62dc893ceeb21cc37f5b3a1c/docs/internal/Versioning.md?plain=1#L334)

**Review by joshua-adams-1 — APPROVED** [review]
LGTM! Thanks for fixing this
