### PR TITLE
SQL: Properly handle indices with no/empty mapping

### LINKED ISSUE #46757: SQL: empty index causes incorrect mapping error
When running a query against an empty index the following error is thrown:
```
[SqlIllegalArgumentException[Incorrect merging of mappings (likely due to a bug) - expect 1 but found [0]]
                at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.mergedMappings(IndexResolver.java:343)
                at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:277)
                at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
                at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:89)
                at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:144)
                at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:138)
```

While it is a corner-case, this needs to be better handled.

### PR DESCRIPTION
**Pull request by costin**
When encountering only indices with empty mapping, the IndexResolver
throws an exception as it expects to find at least one entry.
This commit fixes this case so that an empty mapping is returned.

Fix #46757

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java [hunk 1]
```diff
@@ -470,7 +471,7 @@ public void resolveAsSeparateMappings(String indexWildcard, String javaRegex, bo
             String fieldName = entry.getKey();
             Map<String, FieldCapabilities> types = entry.getValue();
 
-            // ignore size added by the mapper plugin
+            // ignore size added by the mapper plugin or indices with no mapping
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: Why "indices with no mapping" would be applicable to this condition? (the `_size` field, when enabled, will be added even if the mapping doesn't have any explicitly defined fields).

**Review by astefan — APPROVED** [review]
LGTM. Left one comment.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: You're right - the location of the comment is incorrect.
