### PR TITLE
Move query builder caching check to dedicated tests

### LINKED ISSUE #43200: Add dedicated Q.B. cache tests instead of generic testing in AbstractQueryTestCase#testToQuery
In relation to occasional failures like #43112 and while looking into a fix in #43199 I had some discussions
about if its really a good idea to test the caching behaviour of all query builders in general in 
`AbstractQueryTestCase#testToQuery` like we currently do. Doing this for all kinds of randomized query builder
parametrizations requires sometimes non-trivial edge-case handling in either the query builder generation code
or the utility code that codifies assumtions about whether this particular configuration of a builder should be cached
or not (currently implemented on a test-by-test basis by overwriting isCachable()). 

This has two drawbacks: 

- the "isCachable()" code can get quite complex even if the non-caching case is the exception
- we might only rarely check the context cacheable flag because we only run into those cases accidentally

Instead we should probably remove the cache-flag checks from `AbstractQueryTestCase#testToQuery` and add dedicated,
more controlled tests for the query builders that need them.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently `AbstractQueryTestCase#testToQuery` checks the search context cachable
flag. This is a bit fragile due to the high randomization of query builders
performed by this general test. Also we might only rarely check the
"interesting" cases because they rarely get generated when fully randomizing the
query builder.

This change moved the general checks out ot #testToQuery and instead adds
dedicated cache tests for those query builders that exhibit something other than
the default behaviour.

Closes #43200

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/query/MoreLikeThisQueryBuilderTests.java [hunk 1]
```diff
@@ -363,9 +363,26 @@ public void testItemFromXContent() throws IOException {
...
+    public void testCacheability() throws IOException {
+        MoreLikeThisQueryBuilder queryBuilder = createTestQueryBuilder();
+        boolean isCacheable = queryBuilder.likeItems().length == 0; // items are always fetched
+        QueryShardContext context = createShardContext();
+        QueryBuilder rewriteQuery = rewriteQuery(queryBuilder, new QueryShardContext(context));
+        assertNotNull(rewriteQuery.toQuery(context));
+        assertEquals("query should " + (isCacheable ? "" : "not") + " be cacheable: " + queryBuilder.toString(), isCacheable,
+                context.isCacheable());
+
+        // specifically trigger the two where query is cacheable
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/query/MoreLikeThisQueryBuilderTests.java]: Can you also add one that should not be cacheable (queryBuilder.likeItems().length > 0) ?

File: server/src/test/java/org/elasticsearch/index/query/TermsSetQueryBuilderTests.java [hunk 2]
```diff
@@ -110,10 +110,34 @@ protected void doAssertLuceneQuery(TermsSetQueryBuilder queryBuilder, Query quer
...
+        TermsSetQueryBuilder queryBuilder = createTestQueryBuilder();
+        boolean isCacheable = queryBuilder.getMinimumShouldMatchField() != null ||
                 (queryBuilder.getMinimumShouldMatchScript() != null && queryBuilder.getValues().isEmpty());
+        QueryShardContext context = createShardContext();
+        rewriteQuery(queryBuilder, new QueryShardContext(context));
+        assertNotNull(queryBuilder.doToQuery(context));
+        assertEquals("query should " + (isCacheable ? "" : "not") + " be cacheable: " + queryBuilder.toString(), isCacheable,
+                context.isCacheable());
+
+        // specifically trigger the two cases where query is cacheable
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/query/TermsSetQueryBuilderTests.java]: Same here, we should have a test that checks non-cacheable queries explicitly.

**Review by jimczi — COMMENTED** [review]
I left some minor comments but the change looks good. We could maybe add a dedicated test for range queries since they can also disable caching if they contains `now` and target a `date` field ?

**Comment by cbuescher** [comment]
@jimczi thanks, added the two requested tests

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by cbuescher** [comment]
@jimczi I also added the dedicated test for range queries that you requested, this should be ready for another review now.

**Comment by cbuescher** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java [hunk 3]
```diff
@@ -601,4 +601,28 @@ public void testTypeField() throws IOException {
...
+    public void testCacheability() throws IOException {
+        RangeQueryBuilder queryBuilder = createTestQueryBuilder();
+        QueryShardContext context = createShardContext();
+        QueryBuilder rewriteQuery = rewriteQuery(queryBuilder, new QueryShardContext(context));
+        assertNotNull(rewriteQuery.toQuery(context));
+        assertTrue("query should be cacheable: " + queryBuilder.toString(), context.isCacheable());
+
+        // queries on date fields using "now" should not be cached
+        queryBuilder = new RangeQueryBuilder(randomFrom(DATE_FIELD_NAME, DATE_RANGE_FIELD_NAME, DATE_ALIAS_FIELD_NAME));
+        Instant now = Instant.now();
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java]: We don't use the current time to create the `QueryShardContext` in the AbstractBuilderTestCase:
https://github.com/elastic/elasticsearch/blob/29992cff67d4e4d1c105daf66aa8f27329d669c0/test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java#L160
Since we disallow a `from` value that is after the `to` value I think you can use a range query that search for data before `now` (so only set the `to`) ?

**Review by jimczi — APPROVED** [review]
I left one comment, LGTM otherwise

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by cbuescher** [comment]
Thanks Jim, merged to master and 7.x
