### PR TITLE
Fix non-deterministic behaviour in ModelLoadingServiceTests

### LINKED ISSUE #54986: [CI] ModelLoadingServiceTests.testMaxCachedLimitReached failing
This test started failing occasionally a couple of days ago starting around April 6th on `master`. Didn't reproduce for me locally though.

```
org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests > testMaxCachedLimitReached FAILED
    Wanted but not invoked:
    trainedModelStatsService.queueStats(
        <custom argument matcher>
    );
    -> at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:207)
    Actually, there were zero interactions with this mock.
        at __randomizedtesting.SeedInfo.seed([7E2A38F2A7D31844:A34E4080900F1C49]:0)
        at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:207)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached" -Dtests.seed=7E2A38F2A7D31844 -Dtests.security.manager=true -Dtests.locale=zh-Hant-HK -Dtests.timezone=America/Marigot -Dcompiler.java=14
```

https://gradle-enterprise.elastic.co/s/jgxusxpctpphs/tests/7bifs6bt3pimq-zvg6hwacrq4zu

### PR DESCRIPTION
**Pull request by davidkyle**
`ModelLoadingServiceTests::testMaxCachedLimitReached` is testing models get evicted from the cache when the total size of all the models is too large for the cache. There is some non-deterministic behaviour when the models are first loaded as it it known what order they are loaded in and therefore which will be evicted by a later load. This change adjusts the assertions to account for that uncertainty.  

I believe the non-deterministic behaviour comes from a loss of ordering going from a list of IDs to a set. Model loading is mocked so there shouldn't be a race there.  

Closes #54986

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/loadingservice/ModelLoadingService.java [hunk 1]
```diff
@@ -353,9 +353,9 @@ private void auditIfNecessary(String modelId, MessageSupplier msg) {
             logger.trace(() -> new ParameterizedMessage("[{}] {}", modelId, msg.get().getFormattedMessage()));
             return;
         }
-        auditor.warning(modelId, msg.get().getFormattedMessage());
+        auditor.info(modelId, msg.get().getFormattedMessage());
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/loadingservice/ModelLoadingService.java:356]: A model being evicted from the cache is a routine event and not a warning level event. I would prefer this to be debug as it really is a non-issue (the model will be reloaded if required) but there is very little insight into the internals of the cache (which models are loaded etc). Once we have a model management system this should be debug or trace.

I'm raising here for discussion before I forget but I'd be happy to revert the change for this PR

**Review by benwtrent — APPROVED** [review]
Ran the tests locally 1000s of times with this patch and passes 100% ✅ 

:shipit:
