### PR TITLE
Fix NPE in MlMemoryAutoscalingDecider

### LINKED ISSUE #116384: [ML] Autoscaling issue when context.currentCapacity()  is `null`
### Elasticsearch Version

7.17.24

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

In [MlMemoryAutoscalingDecider.java](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlMemoryAutoscalingDecider.java#L260-L263):
```
                MlMemoryAutoscalingCapacity capacity = ensureScaleDown(
                    result,
                    MlMemoryAutoscalingCapacity.from(context.currentCapacity()).build()
                );
```
the call context.currentCapacity() may result in null (see [JavaDoc](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/capacity/AutoscalingDeciderContext.java#L24-L27))

```
    /**
     * Return current capacity of nodes governed by the policy. Can be null if the capacity of some nodes is unavailable. If a decider
     * relies on this value and gets a null current capacity, it should return a result with a null requiredCapacity (undecided).
     */
    AutoscalingCapacity currentCapacity();
```

However MlMemoryAutoscalingCapacity.from(null) crashes.

### Steps to Reproduce

N/A

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes: https://github.com/elastic/elasticsearch/issues/116384

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlMemoryAutoscalingDecider.java [hunk 1]
```diff
@@ -259,7 +259,7 @@ public MlMemoryAutoscalingCapacity scale(
             .map(result -> {
                 MlMemoryAutoscalingCapacity capacity = ensureScaleDown(
                     result,
-                    MlMemoryAutoscalingCapacity.from(context.currentCapacity()).build()
+                    context.currentCapacity() == null ? null : MlMemoryAutoscalingCapacity.from(context.currentCapacity()).build()
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlMemoryAutoscalingDecider.java:262]: - `context.currentCapacity()` can be `null`, see [JavaDoc](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/capacity/AutoscalingDeciderContext.java#L24-L27).
- `MlMemoryAutoscalingCapacity.from(null)` gives null pointer exception
- `ensureScaleDown(..., null) = null`

**Review by davidkyle — APPROVED** [review]
LGTM
