### PR TITLE
Teach reindex to retry on search failures

### LINKED ISSUE #18059: Reindex API dedicated pool?
I'm using the reindex api to create a daily new index, that's optimised to only contain certain docs etc.
There are crons running every hour that could increase the amount of searches and if the reindex is running in the meanwhile it would abort whenever the search thread pool capacity is reached : 

```
	curl -XPOST "http://elastic26:9200/_reindex?wait_for_completion=true" -d '
			 {
			    "conflicts": "proceed",
				"source" : {
					"index": "prod_users_v5",
					"type": "person",
					"query" : { "constant_score" : { "query" : { "bool" : { "filter" : [ { "term" : { "accountstatus" : "active" } }, { "range" : { "lastlogindate" : { "gte" : "2015-04-29 02:00", "lte" : "2016-04-29 02:00" } } }, { "range" : { "birthdate" : { "gte" : "1989-04-29", "lte" : "1993-04-29" } } } ] } } } }
				},
				"dest": {
					"index": "prod_users_v1611902_last_year",
					"op_type" : "create"
				}
			}' 2>/dev/null
```
```
{"took":984897,"timed_out":false,"total":2451467,"updated":0,"created":730574,"batches":7315,"version_conflicts":926,"noops":0,"retries":0,"failures":[{"shard":-1,"index":null,"reason":{"type":"es_rejected_execution_exception","reason":"rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@4f66670b on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5eab79c7[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1351110446]]
```

resulting in a "semi completed" state at the end, 
I know it's not good to have a full search queue.. but I rather have a few searches failing then a reindex process that aborts, 
can't there be dedicated queue for reindex?

### PR DESCRIPTION
**Pull request by nik9000**
This uses the same backoff policy we use for bulk and just retries until the request isn't rejected.

Closes #18059

### CODE REVIEW

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByScrollRequestBuilder.java [hunk 1]
```diff
@@ -108,6 +108,23 @@ public Self consistency(WriteConsistencyLevel consistency) {
     }
 
     /**
+     * Initial delay after a rejection before retrying a bulk request. With the default maxRetries the total backoff for retrying rejections
+     * is about one minute per bulk request. Once the entire bulk request is successful the retry counter resets.
+     */
+    public Self setRetryBackoffInitialTime(TimeValue retryBackoffInitialTime) {
```
Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByScrollRequestBuilder.java]: These weren't properly exposed by the builder.

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkIndexByScrollRequestBuilder.java [hunk 2]
```diff
@@ -26,12 +26,11 @@
 
 public abstract class AbstractBulkIndexByScrollRequestBuilder<
                 Request extends AbstractBulkIndexByScrollRequest<Request>,
-                Response extends BulkIndexByScrollResponse,
```
Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkIndexByScrollRequestBuilder.java]: This `Response` isn't required any more!

**Comment by nik9000** [comment]
@tlrx, want to have a look?

**Comment by nik9000** [comment]
Or @dakrone !

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java [hunk 3]
```diff
@@ -488,11 +476,56 @@ public TimeValue next() {
...
+            }
+
+            @Override
+            protected void doRun() throws Exception {
+                action.accept(this);
+            }
+
+            @Override
+            public void onFailure(Throwable e) {
+                logger.warn("Retrying {}", e, action);
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: In the case of a large number of rejections, is this going to make the logs too verbose?

Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: Also I think this should be moved into the below `if` statement so we don't log if we're not retrying?

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java [hunk 4]
```diff
@@ -488,11 +476,56 @@ public TimeValue next() {
...
+                    threadPool.schedule(retries.next(), ThreadPool.Names.SAME, this);
+                    task.countSearchRetry();
+                    return;
+                }
+                finishHim(e);
+            }
+
+            private boolean causedByRejection(Throwable e) {
+                while (e != null) {
+                    if (e instanceof EsRejectedExecutionException) {
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: We have code in `ExceptionsHelper` for this (`unwrapCause` I believe)

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java [hunk 5]
```diff
@@ -488,11 +476,56 @@ public TimeValue next() {
...
+                action.accept(this);
+            }
+
+            @Override
+            public void onFailure(Throwable e) {
+                logger.warn("Retrying {}", e, action);
+                if (causedByRejection(e) && retries.hasNext()) {
+                    threadPool.schedule(retries.next(), ThreadPool.Names.SAME, this);
+                    task.countSearchRetry();
+                    return;
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: I think it'd be cleaner to put the `finishHim(e);` into an `else` statement than to return early in this logic

**Comment by dakrone** [comment]
Left a couple of comments but otherwise looks good!

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java [hunk 6]
```diff
@@ -208,7 +215,8 @@ public XContentBuilder innerXContent(XContentBuilder builder, Params params)
             builder.field("batches", batches);
             builder.field("version_conflicts", versionConflicts);
             builder.field("noops", noops);
-            builder.field("retries", retries);
+            builder.field("bulk_retries", bulkRetries);
+            builder.field("search_retries", searchRetries);
```
Comment (tlrx) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java]: What about :
```json
"retries": {
  "bulk": 0,
  "search": 0,
}
```

Note: I tend to like JSON inner objects since clients and parsers can skip whole objects while parsing...

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java (hunk 4 above)
Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: I tried that one and it didn't unwrap through `SearchPhaseExecutionException` or `ReduceSearchPhaseException`. But `ExceptionsHelper.unwrap` seems to do it!

**Comment by nik9000** [comment]
@dakrone and @tlrx I pushed a few more commits to address some comments and try and tighten up RetryTests.

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java [hunk 7]
```diff
@@ -488,11 +477,52 @@ public TimeValue next() {
...
+
+            @Override
+            public void onFailure(Throwable e) {
+                if (ExceptionsHelper.unwrap(e, EsRejectedExecutionException.class) != null) {
+                    if (retries.hasNext()) {
+                        logger.trace("Retrying rejected search.", e);
+                        threadPool.schedule(retries.next(), ThreadPool.Names.SAME, this);
+                        task.countSearchRetry();
+                    } else {
+                        logger.warn("Giving up on search because we retries {} time without success.", e, retries);
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: It's super minor, but our log standardization is usually all lowercase

Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: Also, `s/retries/retried/`

Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: and I think we should leave periods out of log messages too

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java [hunk 8]
```diff
@@ -488,11 +477,52 @@ public TimeValue next() {
...
+            @Override
+            protected void doRun() throws Exception {
+                action.accept(this);
+            }
+
+            @Override
+            public void onFailure(Throwable e) {
+                if (ExceptionsHelper.unwrap(e, EsRejectedExecutionException.class) != null) {
+                    if (retries.hasNext()) {
+                        logger.trace("Retrying rejected search.", e);
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: Same here with period and lowercase

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java [hunk 9]
```diff
@@ -488,11 +477,52 @@ public TimeValue next() {
...
+                        threadPool.schedule(retries.next(), ThreadPool.Names.SAME, this);
+                        task.countSearchRetry();
+                    } else {
+                        logger.warn("Giving up on search because we retries {} time without success.", e, retries);
+                        finishHim(e);
+                    }
+                } else {
+                    logger.warn("Giving up on search because it failed with a non-retryable exception.", e);
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkByScrollAction.java]: Same here

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java [hunk 10]
```diff
@@ -208,7 +215,11 @@ public XContentBuilder innerXContent(XContentBuilder builder, Params params)
             builder.field("batches", batches);
             builder.field("version_conflicts", versionConflicts);
             builder.field("noops", noops);
-            builder.field("retries", retries);
+            builder.startObject("retries"); {
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java]: This is a breaking change now so this PR needs to be marked as "breaking" and a note added to the migration guide

**Comment by dakrone** [comment]
Left a few more comments, code looks good though

**Comment by tlrx** [comment]
Besides @dakrone comments, LGTM

**Comment by nik9000** [comment]
@dakrone and @tlrx: I pushed the logging fixes and breaking changes docs.

**Comment by dakrone** [comment]
still LGTM

**Comment by nik9000** [comment]
Cool. I'll squash a merge then!
