### PR TITLE
Abort pending deletion on IndicesService stop

### LINKED ISSUE #121716: [CI] TSDBPassthroughIndexingIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6637 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ppxqfx7mm7w4a)
- [elasticsearch-periodic-platform-support #6630 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/gjj6qbxqqvsr4)
- [elasticsearch-periodic-platform-support #6630 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/p3vvkttwmgidk)
- [elasticsearch-periodic-platform-support #6623 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/o3epflqytucta)
- [elasticsearch-periodic-platform-support #6623 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/zvh6c6bbgemg4)
- [elasticsearch-periodic-platform-support #6616 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/llauohirl5dea)
- [elasticsearch-periodic-platform-support #6504 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mwocgb6lw427k)
- [elasticsearch-periodic-platform-support #6504 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kkbet6sfzamzw)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.TSDBPassthroughIndexingIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.datastreams.TSDBPassthroughIndexingIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 3 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [8.x] 3 consecutive failures in step windows-2019_checkpart1_platform-support-windows
- [8.x] 8 failures in class org.elasticsearch.datastreams.TSDBPassthroughIndexingIT (1.0% fail rate in 779 executions)
- [8.x] 4 failures in step windows-2022_checkpart1_platform-support-windows (66.7% fail rate in 6 executions)
- [8.x] 4 failures in step windows-2019_checkpart1_platform-support-windows (80.0% fail rate in 5 executions)
- [8.x] 5 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121717: [CI] DedicatedClusterSnapshotRestoreIT testRestoreShrinkIndex failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6588 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mql7om56lxohu)
- [elasticsearch-periodic-platform-support #6567 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/vl2zs4cbkrrhm)
- [elasticsearch-periodic-platform-support #6553 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/7gcak6qyeutgk)
- [elasticsearch-periodic-platform-support #6532 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ufdejyooobb52)
- [elasticsearch-periodic-platform-support #6518 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/44z2tnnrk64e2)
- [elasticsearch-periodic-platform-support #6441 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/o2uwgxk7i5tbo)

**Reproduction Line:**
```
gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testRestoreShrinkIndex" -Dtests.seed=F6FDAA05ED542B2A -Dtests.locale=os -Dtests.timezone=Pacific/Auckland -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRestoreShrinkIndex),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
```

**Issue Reasons:**
- [8.x] 6 failures in test testRestoreShrinkIndex (0.7% fail rate in 862 executions)
- [8.x] 4 failures in step windows-2022_checkpart1_platform-support-windows (22.2% fail rate in 18 executions)
- [8.x] 2 failures in step windows-2019_checkpart1_platform-support-windows (12.5% fail rate in 16 executions)
- [8.x] 6 failures in pipeline elasticsearch-periodic-platform-support (27.3% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122119: [CI] ReactiveStorageIT testScaleWhileShrinking failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6415 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/4fp2kqwhvymsq)
- [elasticsearch-pull-request #56408 / part-2-fips](https://gradle-enterprise.elastic.co/s/ovctsq62crnu6)
- [elasticsearch-pull-request #56408 / part-2](https://gradle-enterprise.elastic.co/s/y7d5adplb4eui)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:autoscaling:internalClusterTest" --tests "org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageIT.testScaleWhileShrinking" -Dtests.seed=A8072C4149FB3248 -Dtests.locale=lg-UG -Dtests.timezone=America/Boa_Vista -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testScaleWhileShrinking),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
```

**Issue Reasons:**
- [main] 3 failures in test testScaleWhileShrinking (0.4% fail rate in 761 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
When IndicesService is closed, the pending deletion may still be in progress due to indices removed before IndicesService gets closed. If the deletion stucks for some reason, it can stall the node shutdown. This PR aborts the pending deletion more promptly by not retry after IndicesService is stopped.

Resolves: #121717
Resolves: #121716 
Resolves: #122119

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/IndicesService.java [hunk 1]
```diff
@@ -1440,7 +1440,7 @@ public void processPendingDeletes(Index index, IndexSettings indexSettings, Time
                         sleepTime = Math.min(maxSleepTimeMs, sleepTime * 2); // increase the sleep time gradually
                         logger.debug("{} schedule pending delete retry after {} ms", index, sleepTime);
                     }
-                } while ((System.nanoTime() - startTimeNS) < timeout.nanos());
+                } while ((System.nanoTime() - startTimeNS) < timeout.nanos() && lifecycle.closed() == false);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/IndicesService.java:1443]: I think we want to abort on stop, no need to wait until fully closed?

```suggestion
                } while ((System.nanoTime() - startTimeNS) < timeout.nanos() && lifecycle.started());
```

**Review by DaveCTurner — COMMENTED** [review]
Ah no I think we need a little more than this ideally, we need to abort the `Thread.sleep(sleepTime);` promptly too cos that could be many seconds of waiting. I'd suggest making it a timed wait on a `CountDownLatch(1)` instead of a bare `Thread.sleep()`.

**Comment by ywangd** [comment]
Thanks for the review, David. I pushed 2228f89187705662dbcc6bb5e36915a3946252ea based on your suggestion.

File: server/src/main/java/org/elasticsearch/indices/IndicesService.java [hunk 2]
```diff
@@ -1436,11 +1438,13 @@ public void processPendingDeletes(Index index, IndexSettings indexSettings, Time
                     }
                     if (remove.isEmpty() == false) {
                         logger.warn("{} still pending deletes present for shards {} - retrying", index, remove.toString());
-                        Thread.sleep(sleepTime);
+                        if (stopLatch.await(sleepTime, TimeUnit.MILLISECONDS)) {
+                            break;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/IndicesService.java:1442]: Maybe log here too?

File: server/src/main/java/org/elasticsearch/indices/IndicesService.java [hunk 3]
```diff
@@ -1436,11 +1438,13 @@ public void processPendingDeletes(Index index, IndexSettings indexSettings, Time
...
+                        }
                         sleepTime = Math.min(maxSleepTimeMs, sleepTime * 2); // increase the sleep time gradually
                         logger.debug("{} schedule pending delete retry after {} ms", index, sleepTime);
                     }
-                } while ((System.nanoTime() - startTimeNS) < timeout.nanos());
+                } while ((System.nanoTime() - startTimeNS) < timeout.nanos() && lifecycle.started());
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/IndicesService.java:1447]: Do we need this change now? Not really massively important, it just means that the logging is a little incorrect if we're stopped exactly between the `stopLatch.await()` timing out and getting to this check.

**Review by DaveCTurner — COMMENTED** [review]
Looks good, a couple of comments on logging only.

File: server/src/main/java/org/elasticsearch/indices/IndicesService.java (hunk 2 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/indices/IndicesService.java:1452]: Added logging in 71146a264a9595289cd1fce66c49ae9f829882f2

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/123668)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/123669)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
