### PR TITLE
ESQL: support metric tsdb fields while querying index patterns

### LINKED ISSUE #100144: ESQL: using time-series index and non-time-series index results in wrong typed counter field
### Description

Two indices:

**test1**
```
{
    "settings": {
        "routing_path": "event.dataset",
        "index": {
            "mode": "time_series"
        }
    },
    "mappings": {
        "properties": {
            "@timestamp": {
                "type": "date"
            },
            "bytes_counter": {
                "type": "long",
                "time_series_metric": "counter"
            },
            "event": {
                "properties": {
                    "dataset": {
                        "type": "keyword",
                        "time_series_dimension": true
                    }
                }
            }
        }
    }
}
```

with data

```
{ "index": { } }
{ "bytes":123,"@timestamp":123456789, "event.dataset":"x" }
```

**test2**
```
{
    "mappings": {
      "properties": {
        "bytes_counter": {
          "type": "long"
        }
      }
    }
}
```

with no data.

Running `from test* | limit 0` results in 

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Field type [counter] is not supported"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Field type [counter] is not supported"
    },
    "status": 400
}
```

Running `from test* | limit 0` results in

```
{
    "columns": [
        {
            "name": "@timestamp",
            "type": "date"
        },
        {
            "name": "bytes",
            "type": "long"
        },
        {
            "name": "bytes_counter",
            "type": "long"
        },
        {
            "name": "event.dataset",
            "type": "keyword"
        }
    ],
    "values": []
}
```

**Notice above `bytes_counter` as `long`**. Running `from test1 | limit 0` results in

```
{
    "columns": [
        {
            "name": "@timestamp",
            "type": "date"
        },
        {
            "name": "bytes",
            "type": "long"
        },
        {
            "name": "bytes_counter",
            "type": "unsupported"
        },
        {
            "name": "event.dataset",
            "type": "keyword"
        }
    ],
    "values": []
}
```
**Notice now the `bytes_counter` is unsupported**.
In a nutshell, `bytes_counter` is mapped as `long` in both indices, but the additional meta information about test1 variant is that this field is a time series `counter` field which is unsupported. When loading values, the source operator complains that the field is unsupported.

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/100144

### CODE REVIEW

**Comment by astefan** [comment]
The PR does the following:
- adds the missing logic for handling `metric` type of field_caps logic when the same field exists in multiple "places"
- adds a specific exception message (which is different than the one QL is used to) for this type of mapping conflict. The reason is that the field_caps response has an entirely different structure for time series fields mismatches
- adds tests to EQL and SQL to make sure the logic stays untouched there and the special metrics fields handling happens only in ESQL

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 1]
```diff
@@ -57,12 +59,45 @@
...
 
 import static org.elasticsearch.index.query.QueryBuilders.boolQuery;
+import static org.elasticsearch.xpack.ql.index.IndexResolver.UNMAPPED;
 import static org.elasticsearch.xpack.ql.util.ActionListeners.map;
 import static org.elasticsearch.xpack.ql.util.StringUtils.WILDCARD;
 
 public class EsqlSession {
 
     private static final Logger LOGGER = LogManager.getLogger(EsqlSession.class);
+    public static final BiFunction<String, Map<String, FieldCapabilities>, InvalidMappedField> SPECIFIC_VALIDITY_VERIFIER = (
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:69]: I think this might be more clear as a static method and then you do a `EsqlSession::specificValidity` or something.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 2]
```diff
@@ -57,12 +59,45 @@
...
+        if (hasMetricConflicts) {
+            StringBuilder errorMessage = new StringBuilder();
+            errorMessage.append(
+                "mapped as different metric types in indices: ["
+                    + String.join(", ", types.get(metricConflictsTypeName).metricConflictsIndices())
+                    + "]"
+            );
+            return new InvalidMappedField(name, errorMessage.toString());
+        }
+        return null;
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:99]: Suggest a small change in readability around the code flow to avoid having two return statements:
```
InvalidMappedField result = null;

if (hasMetricConflicts) {
 ....
result = new InvalidMappedField()
}
return results;
```
or promote the errorMessage above the if then do:
`return errorMessage != null  ? new InvalidMappedField(name, errorMessage.toString()) : null);`

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java [hunk 3]
```diff
@@ -326,7 +326,9 @@ public void resolveAsMergedMapping(
         FieldCapabilitiesRequest fieldRequest = createFieldCapsRequest(indexWildcard, fieldNames, indicesOptions, runtimeMappings);
         client.fieldCaps(
             fieldRequest,
-            listener.delegateFailureAndWrap((l, response) -> l.onResponse(mergedMappings(typeRegistry, indexWildcard, response)))
+            listener.delegateFailureAndWrap(
+                (l, response) -> l.onResponse(mergedMappings(typeRegistry, indexWildcard, response, (s, cap) -> null))
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:330]: Now that the PR is in place, you can override the method to allow the old method signature (without a validity specified) to minimize the amount of noise.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java [hunk 4]
```diff
@@ -338,19 +340,23 @@ public void resolveAsMergedMapping(
         Set<String> fieldNames,
         boolean includeFrozen,
         Map<String, Object> runtimeMappings,
-        ActionListener<IndexResolution> listener
+        ActionListener<IndexResolution> listener,
+        BiFunction<String, Map<String, FieldCapabilities>, InvalidMappedField> specificValidityVerifier
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:344]: See my previous comment.

**Review by costin — APPROVED** [review]
LGTM!

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java (hunk 3 above)
Comment (astefan) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:330]: I had mixed feelings about this approach, as I find it harder to determine what are the method's true capabilities. Plus `IndexResolver` is so cluttered with lots of methods that do slightly different things in slightly different scenarios and have the same name.

Comment (astefan) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:330]: I'll leave it as is. Those class' methods are confusing enough.

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 5]
```diff
@@ -281,4 +284,36 @@ public void optimizedPhysicalPlan(LogicalPlan logicalPlan, ActionListener<Physic
...
+                }
+            }
+        }
+
+        InvalidMappedField result = null;
+        if (hasMetricConflicts) {
+            StringBuilder errorMessage = new StringBuilder();
+            errorMessage.append(
+                "mapped as different metric types in indices: ["
+                    + String.join(", ", types.get(metricConflictsTypeName).metricConflictsIndices())
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:312]: this can either be just a string, or append instead of adding strings.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 6]
```diff
@@ -281,4 +284,36 @@ public void optimizedPhysicalPlan(LogicalPlan logicalPlan, ActionListener<Physic
...
+        String metricConflictsTypeName = null;
+        boolean hasMetricConflicts = false;
+
+        if (hasTypeConflicts == false) {
+            for (Map.Entry<String, FieldCapabilities> type : types.entrySet()) {
+                if (UNMAPPED.equals(type.getKey())) {
+                    continue;
+                }
+                if (type.getValue().metricConflictsIndices() != null && type.getValue().metricConflictsIndices().length > 0) {
+                    hasMetricConflicts = true;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:300]: i'd find it slightly easier to read if the `InvalidMappedField` would be built here.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java [hunk 7]
```diff
@@ -339,28 +339,49 @@ public void resolveAsMergedMapping(
...
+            )
         );
     }
 
     public static IndexResolution mergedMappings(
         DataTypeRegistry typeRegistry,
         String indexPattern,
-        FieldCapabilitiesResponse fieldCapsResponse
+        FieldCapabilitiesResponse fieldCapsResponse,
+        BiFunction<String, Map<String, FieldCapabilities>, InvalidMappedField> specificValidityVerifier
```
Comment (bpintea) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:370]: `extraVerifier` would be enough, but `specificValidityVerifier` works too.

**Review by bpintea — APPROVED** [review]
Lgtm, left just nits.

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by astefan** [comment]
@elasticmachine update branch
