### PR TITLE
GET aliases should 404 if aliases are missing

### LINKED ISSUE #24644: HEAD /index/_alias/ always returns 200 OK even alias is not set
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version**: java version "1.8.0_131"

**OS version**: Debian 3.16.39-1+deb8u2

**Description of the problem including expected versus actual behavior**:

Making a HEAD request on an existing index to check the existance of a given alias always returns 200 OK, even if the alias doesn't exist (for that index).

I expect a 404 status like in previous versions of ES.

**Steps to reproduce**:

 1. create an index (i.e. foo_index)
 2. `curl -I -XHEAD 'localhost:9200/foo_index/_alias/nonexisting_alias'`

```
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 2
```

### PR DESCRIPTION
**Pull request by jasontedor**
Previously the HEAD and GET aliases endpoints were misaligned in behavior. The HEAD verb would 404 if any aliases are missing while the GET verb would not if any aliases existed. When HEAD was aligned with GET, this broke the previous usage of HEAD to serve as an existence check for aliases. It is the behavior of GET that is problematic here though, if any alias is missing the request should 404. This commit addresses this by modifying the behavior of GET to behave in this way. This fixes the behavior for HEAD to also 404 when aliases are missing.

Closes #24644

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java [hunk 1]
```diff
@@ -80,41 +86,68 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
...
-                    } else {
-                        final String message = String.format(Locale.ROOT, "alias [%s] missing", toNamesString(getAliasesRequest.aliases()));
-                        builder.startObject();
-                        {
-                            builder.field("error", message);
-                            builder.field("status", RestStatus.NOT_FOUND.getStatus());
+                final ImmutableOpenMap<String, List<AliasMetaData>> aliasMap = response.getAliases();
+
+                final Set<String> aliasNames = new HashSet<>();
+                for (final ObjectObjectCursor<String, List<AliasMetaData>> cursor : aliasMap) {
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: You can probably use `aliasMap.values()` since you don't need the key for anything right? I don't think it's necessarily any better though, so either way is fine.

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java [hunk 2]
```diff
@@ -80,41 +86,68 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
...
+                }
+                difference.removeAll(matches);
+
+                final RestStatus status;
+                builder.startObject();
+                {
+                    if (!difference.isEmpty()) {
+                        status = RestStatus.NOT_FOUND;
+                        final String message;
+                        if (difference.size() == 1) {
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: I think we should have a consistent message regardless of the number of aliases, I know it's bad form for people to write tests against error messages, but that doesn't mean people don't. So, I think we should stick with just `aliases [foo] missing`. What do you think? (I'm only +0 on the change)

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java [hunk 3]
```diff
@@ -80,41 +86,68 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
...
+                            message = String.format(Locale.ROOT, "alias [%s] missing", toNamesString(difference.iterator().next()));
+                        } else {
+                            message = String.format(Locale.ROOT, "aliases [%s] missing", toNamesString(difference.toArray(new String[0])));
+                        }
+                        builder.field("error", message);
+                        builder.field("status", RestStatus.NOT_FOUND.getStatus());
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: could be `status.getStatus()` in the event we change the local variable above.

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java [hunk 4]
```diff
@@ -80,41 +86,68 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
...
-                    {
-                        for (final ObjectObjectCursor<String, List<AliasMetaData>> entry : response.getAliases()) {
-                            builder.startObject(entry.key);
+                }
+                difference.removeAll(matches);
+
+                final RestStatus status;
+                builder.startObject();
+                {
+                    if (!difference.isEmpty()) {
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: We can remove the `!` if we reverse this if statement, so

```java
if (difference.isEmpty()) {
    status = RestStatus.OK;
} else {
    ... the error stuff ...
}

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java [hunk 5]
```diff
@@ -80,41 +86,68 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
...
+                        status = RestStatus.NOT_FOUND;
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: Personally I think we should return `RestStatus.PARTIAL_CONTENT` (206) in the event that requested aliases were requested and *some* were found while some were not, but it sounds like this ship has already sailed as far as what to return.

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_alias/10_basic.yml [hunk 6]
```diff
@@ -1,5 +1,8 @@
 ---
 "Basic test for delete alias":
+  - skip:
+      version: " - 5.99.99"
```
Comment (dakrone) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_alias/10_basic.yml]: I think this should be `5.4.99`, since this will be backported, correct?

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml [hunk 7]
```diff
@@ -166,25 +165,51 @@ setup:
 
 
 ---
-"Non-existent alias on an existing index returns an empty body":
+"Non-existent alias on an existing index returns 404":
+  - skip:
+      version: " - 5.99.99"
```
Comment (dakrone) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml]: Same here about version

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml [hunk 8]
```diff
@@ -166,25 +165,51 @@ setup:
...
 
-  - match: { '': {}}
+  - match: { 'status': 404}
+  - match: { 'error': 'alias [non-existent] missing' }
 
 ---
-"Existent and non-existent alias returns just the existing":
+"Existent and non-existent alias returns 404 and the existing alias":
+  - skip:
+      version: " - 5.99.99"
```
Comment (dakrone) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml]: Same here for version

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml [hunk 9]
```diff
@@ -166,25 +165,51 @@ setup:
...
-  - match: {test_index.aliases.test_alias: {}}
-  - is_false: test_index.aliases.non-existent
+  - match: { 'status': 404 }
+  - match: { 'error': 'alias [non-existent] missing' }
+  - match: { test_index.aliases.test_alias: { } }
+
+---
+"Existent and non-existent aliases returns 404 and the existing alias":
+  - skip:
+      version: " - 5.99.99"
```
Comment (dakrone) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml]: And same here for version

**Review by dakrone — CHANGES_REQUESTED** [review]
I left some comments, almost all of them are not major, but I think the skip version should allow testing on 5.5 since this will be backported.

**Comment by jasontedor** [comment]
> I think the skip version should allow testing on 5.5 since this will be backported.

@dakrone I don't think this is how we should do things because then this branch can never get to green until this is backported to 5.x. Instead:
 - develop on master with a skip for 5.x
 - backport to 5.x, changing the skip to 5.4.99
 - push a separate change to change the skip on master to 5.4.99

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml (hunk 9 above)
Comment (jasontedor) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml]: I disagree, see my top-level comment.

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml (hunk 8 above)
Comment (jasontedor) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml]: I disagree, see my top-level comment.

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml (hunk 7 above)
Comment (jasontedor) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_alias/10_basic.yml]: I disagree, see my top-level comment.

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_alias/10_basic.yml (hunk 6 above)
Comment (jasontedor) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_alias/10_basic.yml]: I disagree, see my top-level comment.

**Comment by dakrone** [comment]
> I don't think this is how we should do things because then this branch can never get to green until this is backported to 5.x.

Alright, as long as it is changed during the backport, I just don't want us to forget it!

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java (hunk 2 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: I disagree that it's bad form, and I have a test for both cases. It's a pet peeve of mine to see messages like "error(s) were encountered while processing"; the information to determine whether "an error was encountered while processing" or "errors were encountered while processing" should be provided is available, the programmer just needs to write some simple code to give a correct error message.

Why do you think it should be consistent instead of correct in every case?

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: Okay.

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java (hunk 4 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: Okay.

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java (hunk 5 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: 206 is wrong, it's for range requests only. Also, 2xx is often not seen as an error client side while 4xx is.

**Comment by jasontedor** [comment]
@dakrone I've responded to your comments, thanks for the suggestions so I pushed some commits too.

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java (hunk 2 above)
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: > Why do you think it should be consistent instead of correct in every case?

As I mentioned above, mostly for users wrapping ES in their own application, anyone that wants to "wrap" this error needs to change parsing `aliases [.*] missing` to `alias(es)? [.*] missing`, which will not be obvious to an end user unless they hit the endpoint with both single and mulitple aliases. I would expect someone who wanted to wrap ES to hit the endpoint, see the error, and then write something that wrapped that error in a prettier way for their application, not realizing that the error may change depending on the cardinality of the aliases.

Like I said above though, I'm only +0 on it, if you don't agree we don't have to change it.

**Review by dakrone — APPROVED** [review]
LGTM

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java (hunk 2 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetAliasesAction.java]: @dakrone Yeah I'm not sure about that concern since I do not think we offer any guarantees on these error messages.

**Comment by jasontedor** [comment]
Thanks @dakrone.
 - master: e03c4938c5f1176bd4c6b6d2aa1aa1bd48245ace
 - 5.x backport: 299e4d4321b85b4d69acde74604139e1e86a1fa7
 - modifying skips on master to accommodate 5.x backport: 5a0b159cb70a30e93ba3a8cfe6917c1acfa468eb

**Comment by m1kola** [comment]
Thanks for fixing it.

Am I right in thinking that it will not be released in the 5.4 branch and users should avoid using all 5.4.* versions if their applications rely on 404 for missing indexes (in other words, just upgrade from 5.3 to 5.5)?

**Comment by jasontedor** [comment]
> Thanks for fixing it.

You're very welcome, and sorry for the issue in the first place.

> Am I right in thinking that it will not be released in the 5.4 branch and users should avoid using all 5.4.* versions if their applications rely on 404 for missing indexes (in other words, just upgrade from 5.3 to 5.5)?

That's all correct.

**Comment by jasontedor** [comment]
@m1kola Also, would you be able to test [6.0.0-alpha2](https://www.elastic.co/downloads/past-releases/elasticsearch-6-0-0-alpha2) and ensure that it has the behavior that you're looking for? I've tested it with your reproduction and I think it does, but I would rather be safe than sorry while we have time to change this for 5.5.0.

**Comment by m1kola** [comment]
@jasontedor thanks for the explanation.

> I've tested it with your reproduction and I think it does

I think it should be ok, but I'll double check it on Friday (let me know if you want me to come back with feedback earlier).

**Comment by jasontedor** [comment]
> I think it should be ok, but I'll double check it on Friday (let me know if you want me to come back with feedback earlier).

Thank you. Friday will be fine.

**Comment by m1kola** [comment]
Hi @jasontedor. I'm afraid [6.0.0-alpha2](https://www.elastic.co/downloads/past-releases/elasticsearch-6-0-0-alpha2) gives the same results: it returns 200 in case when an index exsists, but an alias doesn't exist.

Are you sure that the 6.0.0-alpha2 includes this PR?

**Comment by jasontedor** [comment]
I thought so, let me double check.

**Comment by jasontedor** [comment]
It does not, I'm so very sorry for the mistake that led to a waste of your time. There's a [snapshot for 5.5.0](https://snapshots.elastic.co/downloads/elastic/elasticsearch-5.5.0-SNAPSHOT.tar.gz) that does contain the change.

**Comment by jasontedor** [comment]
It does not, I'm so very sorry for the mistake that led to a waste of your time. There's a [snapshot for 5.5.0](https://snapshots.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0-SNAPSHOT.tar.gz) that does contain the change.

**Comment by m1kola** [comment]
No worries at all. I'm happy to help :)

The snapshot for 5.5.0 works great for me. Thank you for the fix!

**Comment by jasontedor** [comment]
Okay, I'm so glad to hear that. You're welcome.
