### PR TITLE
[Watcher] Improved error messages for CronEvalTool

### LINKED ISSUE #32735: Watcher: croneval tool prints error on valid one time expression
Using the `croneval` CLI tool, this spits an error to a perfectly valid one-time cron expression (tested on 6.3.2)

```
./bin/elasticsearch-croneval "0 3 23 8 9 ? 2019"
Valid!
Now is [Thu, 9 Aug 2018 07:54:34]
Here are the next 10 times this cron expression will trigger:
1.	Mon, 9 Sep 2019 01:03:00
ERROR: 2.	 Could not compute future times since [Mon, 9 Sep 2019 01:03:00] (perhaps the cron expression only points to times in the past?)
```

Instead of printing an error, we should just print the first line and exit and be good, as a one time cron expression is perfectly fine.

### PR DESCRIPTION
**Pull request by lipsill**
CronEvalTool prints an error only for cron expressions that result in
no coming time events.

If a cron expression results in less than the specified `-count`
(default 10) time events, the CronEvalTool prints all the coming
times and displays no error message.

Fixes #32735

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java [hunk 1]
```diff
@@ -57,18 +58,25 @@ void execute(Terminal terminal, String expression, int count) throws Exception {
...
+                if (i == 0) {
+                    throw new UserException(ExitCodes.OK, "Could not compute future times since ["
+                            + formatter.print(prevTime) + "] " + "(perhaps the cron expression only points to times in the past?)");
+                }
+                break;
             }
-            terminal.println((i+1) + ".\t" + formatter.print(time));
+            times.add((i + 1) + ".\t" + formatter.print(time));
         }
+        terminal.println((i == count ? "Here are the next " : "There are ") + i + " times this cron expression will trigger:");
```
Comment (spinscale) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java]: I don't think we need this special handling here (introducing state that requires following by filling up the list). Just adding the additional if-statement plus break should be sufficient.

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java [hunk 2]
```diff
@@ -20,4 +24,28 @@ public void testParse() throws Exception {
         String output = execute(countOption, Integer.toString(count), "0 0 0 1-6 * ?");
         assertTrue(output, output.contains("Here are the next " + count + " times this cron expression will trigger"));
     }
+
+    public void testGetNextValidTimes() throws Exception {
+        {
```
Comment (spinscale) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java]: for readability, just put `final int year = ZonedDateTime.now(ZoneOffset.UTC).getYear() + 1;` at the top of the test and use that one maybe?

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java [hunk 3]
```diff
@@ -20,4 +24,28 @@ public void testParse() throws Exception {
...
+            String output = execute(
+                    "0 3 23 8 9 ? " + (Calendar.getInstance(TimeZone.getTimeZone("UTC"), Locale.ROOT).get(Calendar.YEAR) + 1));
+            assertTrue(output, output.contains("There are 1 times this cron expression will trigger:"));
```
Comment (spinscale) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java]: can you replace `assertTrue/assertFalse` with 

```
assertThat(output, containsString("FoObar"));
assertThat(output, not(containsString("ERROR")));
```

This way the assertion will return something helpful instead of just being true or false in order to ease debugging.

**Review by spinscale — CHANGES_REQUESTED** [review]
Thanks a bunch for tackling this! I left some comments to simplify the code and make the tests more readable. 

Would be awesome if you could take a further look, but I am happy to take over if you do not want to!

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java (hunk 1 above)
Comment (lipsill) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java]: I made the change as originally the following results were printed by the cli tool:
`0 0 0 1-6 * ?` resulted in
```
Valid!
Now is [Wed, 15 Aug 2018 11:28:34]
Here are the next 10 times this cron expression will trigger:
1.	Sat, 1 Sep 2018 02:00:00
2.	Sun, 2 Sep 2018 02:00:00
3.	Mon, 3 Sep 2018 02:00:00
4.	Tue, 4 Sep 2018 02:00:00
5.	Wed, 5 Sep 2018 02:00:00
6.	Thu, 6 Sep 2018 02:00:00
7.	Mon, 1 Oct 2018 02:00:00
8.	Tue, 2 Oct 2018 02:00:00
9.	Wed, 3 Oct 2018 02:00:00
10.	Thu, 4 Oct 2018 02:00:00
```
And a one time cron, such as `0 3 23 8 9 ? 2019` resulted in
```
Valid!
Now is [Wed, 15 Aug 2018 11:29:37]
Here are the next 10 times this cron expression will trigger:
1.	Mon, 9 Sep 2019 01:03:00
```
I found it is a little bit confusing that in this case the message was `Here are the next 10 time` and only a single one was printed, hence I tried to clarify the message.

I will revert the change.

**Comment by lipsill** [comment]
@spinscale thanks for the feedback! I just pushed the changes. Can you have another look?

**Comment by spinscale** [comment]
@elasticmachine test this please

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java [hunk 4]
```diff
@@ -5,21 +5,22 @@
...
 import org.elasticsearch.cli.Terminal;
+import org.elasticsearch.cli.UserException;
 import org.elasticsearch.xpack.core.scheduler.Cron;
 import org.joda.time.DateTime;
 import org.joda.time.DateTimeZone;
 import org.joda.time.format.DateTimeFormat;
 import org.joda.time.format.DateTimeFormatter;
 
+import java.util.Arrays;
+import java.util.List;
```
Comment (spinscale) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java]: in order to keep the diff small, can you keep the imports as is?

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java [hunk 5]
```diff
@@ -18,6 +25,29 @@ public void testParse() throws Exception {
         String countOption = randomBoolean() ? "-c" : "--count";
         int count = randomIntBetween(1, 100);
         String output = execute(countOption, Integer.toString(count), "0 0 0 1-6 * ?");
-        assertTrue(output, output.contains("Here are the next " + count + " times this cron expression will trigger"));
+        assertThat(output, containsString("Here are the next " + count + " times this cron expression will trigger"));
+    }
+
+    public void testGetNextValidTimes() throws Exception {
+        {
+            final int nextYear = Calendar.getInstance(TimeZone.getTimeZone("UTC"), Locale.ROOT).get(Calendar.YEAR) + 1;
```
Comment (spinscale) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalToolTests.java]: for readability, just put `final int year = ZonedDateTime.now(ZoneOffset.UTC).getYear() + 1;` at the top of the test and use that one maybe?

**Review by spinscale — CHANGES_REQUESTED** [review]
left two super minor things I'd like to fix, but apart from that it's good. let's see what CI has to say!

**Comment by lipsill** [comment]
@spinscale I hope I addressed your latest comments.
Thanks for kicking a complete CI ;)

**Comment by spinscale** [comment]
@elasticmachine test this please

**Comment by lipsill** [comment]
Hm... the second CI run finished with an error that I cannot reproduce locally. I actually doubt that the test failure is caused by the changes in this PR. 
@spinscale can you have a look when you have a chance? Thanks!

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Review by spinscale — APPROVED** [review]

**Comment by spinscale** [comment]
once CI passes, I'll merge this. Thanks a lot for helping!

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Comment by spinscale** [comment]
may I ask you to merge the master branch into yours one more time, so we can trigger CI and see if it passes? Thanks a ton!

**Comment by lipsill** [comment]
@spinscale done! Let's see if this helps ;)

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Comment by spinscale** [comment]
thanks again, I have merged the PR into the master and 6.x branch

**Comment by lipsill** [comment]
Thanks @spinscale :)
