### PR TITLE
[ML] Preserve zero-allocation trained-model deployments in cluster state during ML-node shutdown rebalances

### LINKED ISSUE #146806: [ML] Zero-allocation trained-model deployments are silently dropped from cluster state during ML node shutdown, producing persistent 404 Unable to find model deployment task
When a trained-model deployment is scaled to zero allocations (e.g. via adaptive allocations with `min_number_of_allocations: 0`), a subsequent ML-node shutdown/replacement can cause the deployment's `TrainedModelAssignment` to be **silently and irrecoverably removed from cluster state** — with no `STOPPING` transition, no audit log, and no recovery path. From that moment on, every inference request against the affected inference endpoint returns:

```
NotFoundError(404, 'status_exception',
  'Unable to find model deployment task [<model-id>] please stop and start the deployment or try again momentarily')
```

until the inference endpoint is manually deleted and recreated.

The root cause is a defensive branch in `TrainedModelAssignmentClusterService.setShuttingDownNodeRoutesToStopping` whose re-admission criterion (the deployment must have at least one `STARTED`/`STARTING` route to a shutting-down node) is **impossible** for a scaled-to-zero deployment to satisfy, so whenever the rebalancer's builder doesn't already contain the deployment (e.g. due to a `NotMasterException`, planner exception, or stale/partial state), the deployment is silently deleted.

This bug also has a secondary observability problem: the 404 itself is thrown without any server-side log, making it very hard to detect across the fleet.

## Environment

- **Elasticsearch version:** all ES versions with adaptive allocations.

## Inference endpoint configuration (customer)

```json
{
  "inference_id": ".elser-2-elasticsearch",
  "task_type": "sparse_embedding",
  "service": "elasticsearch",
  "service_settings": {
    "num_threads": 1,
    "model_id": ".elser_model_2_linux-x86_64",
    "adaptive_allocations": {
      "enabled": true,
      "min_number_of_allocations": 0,
      "max_number_of_allocations": 32
    }
  }
}
```

## Steps to reproduce (conceptual)

1. Create a trained-model deployment with `adaptive_allocations.enabled=true`, `min_number_of_allocations=0`.
2. Let the deployment idle long enough for adaptive allocations to scale it down to zero. At this point cluster state contains a `TrainedModelAssignment` with `numberOfAllocations=0`, empty `nodeRoutingTable`, `state=STARTED`.
3. Trigger an ML node replacement (shutdown metadata set on the current ML node, new ML node added). In serverless this happens routinely during deploy/rollout.
4. During the rebalance, induce any condition that causes the rebalancer's builder not to round-trip the zero-allocation deployment. Observed triggers:
   - A `NotMasterException` while applying the cluster-state update (master change during rebalance).
   - Exceptions in the planner path (e.g. memory-accounting `IllegalArgumentException`, OJAlgo failures).
   - Stale `currentMetadata` from a prior aborted rebalance.
5. Observe that the zero-allocation deployment is no longer present in `TrainedModelAssignmentMetadata`.
6. Any inference call against the endpoint returns `404 Unable to find model deployment task` indefinitely.

## Observed behavior

- **Client-visible:** every request to the endpoint returns `404 Unable to find model deployment task [<model-id>]`. Persistent until the endpoint is deleted and recreated.
- **Cluster state:** the `TrainedModelAssignment` for the deployment is missing. Other deployments for the same model (`<model-id>_search`, `<model-id>_ingest`) are unaffected if they had routed allocations during the shutdown.
- **Logs on the master:** no message indicating the deletion. Only `"failed to rebalance models"` (warn) if the rebalance aborted.
- **Logs on ML nodes:** no `"Stopping deployment, reason [deployment assignment no longer exists]"` for the lost deployment, because there was no local process to stop (it was scaled to zero).
- **Logs on coordinating nodes (later):** `"[<deployment>] assignment was null while waiting to scale up"` appears when inference requests hit the missing assignment (from `InferenceWaitForAllocation`).

## Expected behavior

A trained-model deployment that existed before an ML node shutdown must not be lost as a side effect of that shutdown. Either:

- it should remain with its existing state (scaled to zero is a valid steady state and does not need any "drain" action), or
- if for some reason it must be transitioned to `STOPPING`, that transition should actually be applied to cluster state and logged, not silently discarded.

### 1. Where the assignment is deleted

`TrainedModelAssignmentClusterService.setShuttingDownNodeRoutesToStopping` is called after the rebalancer produces its `TrainedModelAssignmentMetadata.Builder`. It iterates over the assignments that existed before the rebalance and, for any assignment missing from the new builder, constructs a local "STOPPING" replacement — but **only re-admits the replacement if the deployment had an active route to a shutting-down node**:

```java
// x-pack/plugin/ml/.../TrainedModelAssignmentClusterService.java (current main)
for (TrainedModelAssignment existingAssignment : currentMetadata.allAssignments().values()) {
    boolean foundShuttingDownNodeForAssignment = false;

    String existingDeploymentId = existingAssignment.getDeploymentId();
    TrainedModelAssignment.Builder assignmentBuilder = builder.hasModelDeployment(existingDeploymentId)
        ? builder.getAssignment(existingDeploymentId)
        : TrainedModelAssignment.Builder.fromAssignment(existingAssignment)
            // "anomaly" branch — the assignment existed before rebalance but is absent from builder
            .stopAssignment(NODES_CHANGED_REASON)
            .clearNodeRoutingTable();

    for (String nodeId : shuttingDownNodeIds) {
        if (existingAssignment.isRoutedToNode(nodeId)
            && existingAssignment.getNodeRoutingTable().get(nodeId).getState()
                .isAnyOf(RoutingState.STARTED, RoutingState.STARTING)) {
            foundShuttingDownNodeForAssignment = true;
            assignmentBuilder.addOrOverwriteRoutingEntry(nodeId, createShuttingDownRoute(...));
        }
    }

    // Bug: if the deployment had no routes at all (scaled to zero), it is dropped here.
    if (foundShuttingDownNodeForAssignment) {
        builder.addOrOverwriteAssignment(existingDeploymentId, assignmentBuilder);
    }
}
```

For a scaled-to-zero deployment `existingAssignment.getNodeRoutingTable()` is empty, so `foundShuttingDownNodeForAssignment` stays `false`, `assignmentBuilder` is never added to `builder`, and the deployment disappears from the next cluster state.

### 2. How the "anomaly" precondition is reached

Normal planning does preserve zero-allocation deployments. I verified each layer:

- `TrainedModelAssignmentRebalancer.buildAssignmentsFromPlan` iterates `assignmentPlan.deployments()` and calls `addNewAssignment` for every deployment, including zero-allocation ones.
- `AssignmentPlanner` splits deployments into non-zero and zero sets and calls `bestPlan.withZeroAllocationDeployments(deploymentsWithZeroAllocations)` before returning.
- `ZoneAwareAssignmentPlanner.swapOriginalDeploymentsInPlan` / `AssignmentPlan.Builder` re-inject all original deployments as keys, even if per-zone LP filtering dropped them.

So in the happy path the zero-allocation deployment arrives in `setShuttingDownNodeRoutesToStopping` via `builder.hasModelDeployment(id) == true`, and the bug branch is not taken.

The bug branch is reached when the rebalancer output doesn't include the deployment, which happens when:

- `rebalanceAssignments` throws and the failure path only logs `logger.warn("failed to rebalance models", e)` — observed as `NotMasterException` on 2026-04-15 in the reported incident.
- The planner itself throws (e.g. `IllegalArgumentException "not enough memory on node"` in `AssignmentPlan.Builder.accountMemory`, OJAlgo solver errors).
- The rebalance starts from a cluster state produced by an earlier aborted rebalance or mixed-version upgrade where the deployment was already missing.

Once the precondition is reached, the defensive branch in `setShuttingDownNodeRoutesToStopping` is the last line of defense — and it has the wrong criterion for zero-allocation deployments.

### 3. Why it is effectively invisible

- The deletion itself is unlogged.
- The resulting 404 is thrown without any server-side logging:

```java
// TransportInferTrainedModelDeploymentAction.java
} else if (tasks.isEmpty()) {
    throw new ElasticsearchStatusException(
        "Unable to find model deployment task [{}] please stop and start the deployment or try again momentarily",
        RestStatus.NOT_FOUND,
        request.getId()
    );
}
```

- `ASSIGNMENT_NO_LONGER_EXISTS` / `"Stopping deployment, reason [deployment assignment no longer exists]"` fires on ML nodes only when a native process exists to stop — which by definition it doesn't for scaled-to-zero.
- The only cross-fleet signal today is `"assignment was null while waiting to scale up"` (INFO) in `InferenceWaitForAllocation`, which fires on the coordinating node per inference request against a missing assignment.

## Evidence (from reported incidents)

- According to logs on 2026-04-15 and 2026-04-17:
  - ML node `rfd8b` marked shutting down; `.elser_model_2_linux-x86_64` (unsuffixed) briefly STARTED then STOPPED and never appeared in logs again.
  - Master change during the window on 2026-04-15 produced `NotMasterException` during rebalance (`failed to rebalance models`).
  - On 2026-04-17, multiple `"[<id>] assignment was null while waiting to scale up"` messages from `InferenceWaitForAllocation` against the same deployment id.
  - Sibling deployments `<model-id>_search` and `<model-id>_ingest` survived — they had STARTED routes to the shutting-down node and hit the correct branch.

## Suggested fix

Both fixes are localized to `TrainedModelAssignmentClusterService.setShuttingDownNodeRoutesToStopping`. Either one is sufficient; implementing both is safest.

### Fix A (minimal) — always re-admit the anomaly replacement

Remove the `foundShuttingDownNodeForAssignment` guard at the bottom and always write `assignmentBuilder` back to `builder` when the "anomaly" branch was taken. A scaled-to-zero deployment will then appear as `STOPPING` in the next cluster state instead of being deleted. While technically still wrong (we shouldn't be transitioning a scaled-to-zero deployment to STOPPING at all), this is strictly better than silent deletion and is a one-line change.

### Fix B (preferred) — short-circuit on empty routing

At the top of the per-assignment loop, short-circuit deployments with `existingAssignment.getNodeRoutingTable().isEmpty()`: copy them into `builder` as-is if missing, or leave the rebalancer's version untouched if already present. These deployments have no draining work to do and should never be dropped.

```java
if (existingAssignment.getNodeRoutingTable().isEmpty()) {
    if (builder.hasModelDeployment(existingDeploymentId) == false) {
        builder.addOrOverwriteAssignment(
            existingDeploymentId,
            TrainedModelAssignment.Builder.fromAssignment(existingAssignment)
        );
    }
    continue;
}
```

### Fix C (observability, independent of A/B)

- In `TransportInferTrainedModelDeploymentAction`, log the 404 at `WARN` with the deployment id before throwing, so the error becomes searchable in cluster logs.
- In `setShuttingDownNodeRoutesToStopping`, log at `WARN` any time the "anomaly" branch fires, including the deployment id and the reason the rebalancer builder didn't contain it. This is the signal we needed across the fleet and currently don't have.
- In `rebalanceAssignments` onFailure, log the specific failure type (`NotMasterException` vs. planner exception) at `WARN` with the deployment ids still in cluster state, so we can correlate.

## Recovery
The inference endpoint is not permanently broken: invoking `POST _ml/trained_models/<model_id>/deployment/_start` with the correct `deployment_id` recreates the `TrainedModelAssignment` in cluster state and restores inference. Equivalently, deleting and recreating the inference endpoint via `DELETE _inference/<id>` + `PUT _inference/<id>` restores service. 

However:
- Recovery is strictly manual; nothing in the ML layer detects a dangling inference endpoint and auto-recreates the assignment.
- The message "Unable to find model deployment task [...] please stop and start the deployment" is the codebase's own advice, but in this failure mode `_stop` errors out because there is no assignment to stop — only `_start` is needed.

## Workaround for affected users

Updating the deployment as setting the `min_number_of_allocations` to 1 will make the deployments completely unaffected by the bug :

1. If the endpoint is already broken, delete and recreate it first (creation will be clamped to `min=0`, which is unavoidable on the create path).
2. Immediately apply the update so adaptive allocations no longer scales to zero:

```http
POST _inference/sparse_embedding/.elser-2-elasticsearch/_update
{
  "service_settings": {
    "adaptive_allocations": {
      "enabled": true,
      "min_number_of_allocations": 1,
      "max_number_of_allocations": 32
    }
  }
}
```

or, equivalently, via the ML API directly:

```http
POST _ml/trained_models/.elser_model_2_linux-x86_64/deployment/_update
{
  "adaptive_allocations": {
    "enabled": true,
    "min_number_of_allocations": 1,
    "max_number_of_allocations": 32
  }
}
```

### PR DESCRIPTION
**Pull request by valeriy42**
When an ML node is marked for shutdown, `TrainedModelAssignmentClusterService` triggers a rebalance and then calls `setShuttingDownNodeRoutesToStopping` to transition affected routes to `STOPPING`. A latent bug in that method caused it to silently drop any assignment that (a) was present in the pre-rebalance cluster state and (b) had an empty routing table, which is the exact shape of a deployment scaled to zero by adaptive allocations with `min_number_of_allocations = 0`. 

The root cause was a guard variable `foundShuttingDownNodeForAssignment` that prevented a locally-constructed assignment builder from ever being written back into the metadata builder when no shutting-down routes existed, resulting in the assignment vanishing from cluster state entirely and subsequent inference requests receiving a 404 "Unable to find model deployment task" with no recovery path.

The fix restructures `setShuttingDownNodeRoutesToStopping` around the boolean `wasDroppedByRebalancer`, which is `true` whenever an assignment exists in the pre-rebalance metadata but is absent from the rebalancer's output builder. Zero-allocation deployments with an empty routing table are now fast-pathed: if they were dropped by the rebalancer they are carried forward verbatim with a `WARN` log; if they are already in the builder they are left untouched. Assignments with non-empty routing that were dropped by the rebalancer are transitioned to `STOPPING` as before and are now always written back, rather than conditionally skipped. A defensive `assert` at the end of the method enforces the postcondition that no assignment present before the rebalance may be absent afterward. 

There is one edge case that is not cleanly covered: the implementation still loses the routing entries that point to healthy nodes. The native processes on those healthy nodes do not receive a `STOPPING` route, so they are not drained gracefully via the normal `TrainedModelAssignmentNodeService` stopping-route flow, leaving them orphaned until the node itself restarts or reconciles. I added a counter metric to track if this case actually happens in production. 

Fixes #146806

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportInferTrainedModelDeploymentAction.java [hunk 1]
```diff
@@ -39,6 +42,16 @@ public class TransportInferTrainedModelDeploymentAction extends TransportTasksAc
     InferTrainedModelDeploymentAction.Response,
     InferTrainedModelDeploymentAction.Response> {
 
+    private static final Logger logger = LogManager.getLogger(TransportInferTrainedModelDeploymentAction.class);
+
+    // Deployment IDs for which a missing deployment signals an operational issue, not client error
+    // (e.g., default ELSER deployments).
+    private static final Set<String> DEPLOYMENT_IDS_WORTH_WARNING_ON_MISSING_TASK = Set.of(
+        ".elser_model_2_linux-x86_64",
+        ".elser_model_2_linux-x86_64_search",
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportInferTrainedModelDeploymentAction.java:51]: instead of this hardcoded list, isn't it better to use something like deployment ID starts with any of
`ElasticsearchInternalService` -> `defaultConfigs` -> `inferenceEntityId`

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 2]
```diff
@@ -79,12 +81,28 @@ public class TrainedModelAssignmentClusterService implements ClusterStateListene
...
+     * <p>
+     * In this case {@link #setShuttingDownNodeRoutesToStopping} preserves the assignment as {@code STOPPING} with an
+     * empty routing table to avoid silently losing it from cluster state. However, the healthy-node routes are
+     * discarded rather than transitioned to {@code STOPPING}, so the native processes on those nodes do not receive
+     * a drain signal and may become orphaned until the next reconciliation. This counter lets us observe whether
+     * this situation is occurring in production so we can decide whether a more invasive fix (transitioning the
+     * healthy routes themselves to {@code STOPPING}) is warranted.
+     */
+    public static final String ASSIGNMENT_DROPPED_WITH_UNDRAINED_ROUTES_COUNTER =
+        "es.ml.trained_model_assignment.dropped_with_undrained_routes.count";
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:97]: Isn't the logging enough? I'm a bit hesitant to add such counters for debugging.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 3]
```diff
@@ -653,63 +696,133 @@ private TrainedModelAssignmentMetadata.Builder rebalanceAssignments(
...
-            TrainedModelAssignment.Builder assignmentBuilder = builder.hasModelDeployment(existingAssignment.getDeploymentId())
-                ? builder.getAssignment(existingDeploymentId)
-                : TrainedModelAssignment.Builder.fromAssignment(existingAssignment)
+
+            boolean wasDroppedByRebalancer = builder.hasModelDeployment(existingDeploymentId) == false;
+            // Fast path for zero-allocation deployments: nothing to drain, nothing to stop.
+            // If the rebalancer already has the deployment, leave its version untouched.
+            // Otherwise carry the existing assignment forward unchanged so it is never silently lost.
+            if (existingAssignment.getNodeRoutingTable().isEmpty()) {
+                if (wasDroppedByRebalancer) {
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:726]: This looks strange. To me it looks like there's a bug in the balancer that causes this to happen, and here we compensate for that bug. Shouldn't we fix the rebalancer instead? Or am I missing something?

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterServiceTests.java [hunk 4]
```diff
@@ -1965,6 +1972,163 @@ public void testSetShuttingDownNodeRoutesToStopping_GivenAssignmentDoesNotExist_
         assertThat(assignment.getReason().get(), is("nodes changed"));
     }
 
+    public void testSetShuttingDownNodeRoutesToStopping_GivenZeroAllocationAssignmentMissingFromBuilder_ItIsPreserved() {
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterServiceTests.java:1975]: Would it be possible to create an integration test, testing the correct behavior.

So something like:
- spin up one node version a zero-allocation deployment
- spin up another node
- shut down first node
- assert that zero-allocation deployment is still there
- do inference request
- assert that it works

Please also check that without these changes, this scenario fails

**Review by jan-elastic — COMMENTED** [review]
Generally LGTM, but this assignment logic is just too complicated.

I've left a couple of comments / requests.

I'll give it some more thought and will revisit later again (probably tomorrow)

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportInferTrainedModelDeploymentAction.java (hunk 1 above)
Comment (valeriy42) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportInferTrainedModelDeploymentAction.java]: I replaced the hardcoded set with request.getId().startsWith("."). All system-registered deployments (default ELSER, E5, rerank via ElasticsearchInternalService) use a .-prefixed ID by convention, so this covers all current and future cases. I don't want to introduce the dependency on `ElasticsearchInternalService` as it would invert the dependency flow.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java (hunk 2 above)
Comment (valeriy42) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java]: Agreed. I removed the metric.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java (hunk 3 above)
Comment (valeriy42) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:686]: I looked for a bug in the  TrainedModelAssignmentRebalancer and couldn't didn't find one. On the happy path it correctly emits zero-allocation deployments in its output. The bug I **could** find was in the caller, setShuttingDownNodeRoutesToStopping: it iterates over the pre-rebalance metadata and only writes an assignment back into the builder when it finds a route pointing at a shutting-down node. A zero-allocation deployment has no routes, so nothing is written back, and the assignment is silently dropped from cluster state.

Since we couldn't identify a concrete rebalancer code path that drops the assignment, the fix is defensive by design: if an assignment existed before rebalance but is absent from the rebalancer output, log a WARN message that contains all required information to investigate the root cause of the bug.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterServiceTests.java (hunk 4 above)
Comment (valeriy42) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterServiceTests.java:1969]: If I ingest a zero allocation assignment that is missing from the builder, it's equivalent to a unit test, which I already have. The faulty behavior is likely to a timing issue or a race condition, but I cannot create an IT that would reproduce it reliably. 

As I capture the information required to investigate the issue in the warning message, it will provide data to create such IT in the future.

**Comment by valeriy42** [comment]
@coderabbitai review this

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 5]
```diff
@@ -186,7 +186,22 @@ public void clusterChanged(ClusterChangedEvent event) {
...
                     ),
-                    e -> logger.warn("failed to rebalance models", e)
+                    e -> {
+                        List<String> deploymentIdsBeforeRebalance = TrainedModelAssignmentMetadata.fromState(event.state())
+                            .allAssignments()
+                            .keySet()
+                            .stream()
+                            .toList();
+                        logger.warn(
+                            () -> format(
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java]: why `logger.warn(() -> format(...))`?

just `logger.warn("...", ...)` does the same here, right?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 6]
```diff
@@ -653,7 +668,7 @@ private TrainedModelAssignmentMetadata.Builder rebalanceAssignments(
         return rebalanced;
     }
 
-    // Default for testing
+    // Default for testing (no metric recording)
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java]: leftover comment

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 7]
```diff
@@ -664,52 +679,107 @@ static TrainedModelAssignmentMetadata.Builder setShuttingDownNodeRoutesToStoppin
...
         return builder;
     }
 
+    private static void warnAssignmentDroppedByRebalancer(
+        String deploymentId,
+        TrainedModelAssignment preRebalanceAssignment,
+        Set<String> shuttingDownNodeIds,
+        TrainedModelAssignmentMetadata.Builder rebalancerOutput
+    ) {
+        logger.warn(
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java]: I think this should be an error instead of a warning. WDYT?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 8]
```diff
@@ -664,52 +679,107 @@ static TrainedModelAssignmentMetadata.Builder setShuttingDownNodeRoutesToStoppin
...
+    }
+
+    /**
+     * For each node in {@code shuttingDownNodeIds} that has an active ({@link RoutingState#STARTING} or
+     * {@link RoutingState#STARTED}) route in {@code existingAssignment}, converts that route to a
+     * {@link RoutingState#STOPPING} route and writes it into {@code assignmentBuilder}.
+     *
+     * @return {@code true} if at least one route to a shutting-down node was found and transitioned
+     */
+    private static boolean applyShuttingDownRoutes(
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java]: This return value isn't used, right? Let's remove it.

**Review by jan-elastic — APPROVED** [review]
LGTM as far as I can tell.
