### PR TITLE
ILM Explain: valid JSON on truncated step info

### LINKED ISSUE #135458: ILM Explain API truncated `previous_step_info` breaks JSON
### Elasticsearch Version

8.19.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

linux

### Problem Description

When `previous_step_info` is truncated, it seems it is missing a `"}` at the end, which breaks JSON parsing.

e.g.
```json
"previous_step_info":{"type":"exception","reason":"<REMOVED>... (28 chars truncated),"phase_execution":
```

### Steps to Reproduce

Not clear, need to investigate further, but assuming you need to cause an exception in an ILM stage, and then when it get's carried over it'll return invalid JSON on subsequent `explain` calls.

relevant code/links:
1. https://github.com/elastic/elasticsearch/pull/125814
2. https://github.com/elastic/elasticsearch/blob/85f7fa92cb1edeb1f42167718942a15baf183a72/server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java#L290-L299
3. https://github.com/elastic/elasticsearch/blob/cda26693ca9ffb165f88533f2f0117959d1534d7/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java#L90-L96

from a quick glance, my first avenue of investigation would be the other invocation of `truncateWithExplanation` not having this hack of adding the `"}`

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by szybia**
Fix invalid JSON in `_ilm/explain` where `previous_step_info` is missing `"}` at the end, if it was truncated

Closes #135458

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java [hunk 1]
```diff
@@ -30,11 +31,11 @@ public void testTruncatingStepInfo() {
         assertThat(custom.get("step_info"), equalTo(state.stepInfo()));
         String longStepInfo = randomAlphanumericOfLength(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH + 100);
         LifecycleExecutionState newState = LifecycleExecutionState.builder(state).setStepInfo(longStepInfo).build();
-        // Length includes the post suffix
-        assertThat(newState.stepInfo().length(), equalTo(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH + 25));
+        // Length includes the post suffix (`... (X chars truncated)`)
+        assertThat(newState.stepInfo().length(), equalTo(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH + 26));
```
Comment (szybia) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java]: my change does:
```
<chars>... (100 chars truncated)
->
<chars>... (98 chars truncated)"}
```

so in terms of chars it's `added_characters_at_end + one_less_digit_chars = 2 + -1 = 1`, so we add one here

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java [hunk 2]
```diff
@@ -287,15 +287,16 @@ public Map<String, String> asMap() {
...
 
-    public static String truncateWithExplanation(String input) {
-        if (input != null && input.length() > MAXIMUM_STEP_INFO_STRING_LENGTH) {
-            return Strings.cleanTruncate(input, MAXIMUM_STEP_INFO_STRING_LENGTH)
-                + "... ("
-                + (input.length() - MAXIMUM_STEP_INFO_STRING_LENGTH)
-                + " chars truncated)";
-        } else {
-            return input;
+    public static String potentiallyTruncateLongJsonWithExplanation(String json) {
```
Comment (szybia) [inline server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java:299]: - from scanning code paths, stepInfo passed into here is always JSON/toxcontent
  * if i'm mistaken and it's not json, a valid string is still returned
  * if it is json, but it's a different format (i.e. if the assumption that all we need at the end is `"}` doesn't hold up), we'll still output invalid JSON with current code, so this is a quick-fix to fix linked bug already spotted, maybe we'll need some larger overhaul in future if we spot more issues because this is quite flaky... might leave a comment depending on what reviewers think, or an assertion to only check tests 🤔🤔 
- long func name but i like to be descriptive

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java [hunk 3]
```diff
@@ -145,6 +146,38 @@ public void testGetCurrentStepKey() {
         assertNull(error6.getMessage());
     }
 
+    public void testPotentiallyTruncateLongJsonWithExplanationNotTruncated() {
+        // +2 because with the JSON ending in `"}`, we'll add it back anyway so it's a NOP
+        final String input = randomAlphaOfLengthBetween(0, LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH + 2);
```
Comment (szybia) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java]: ran all tests with 10k iterations and looks good

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java [hunk 4]
```diff
@@ -87,13 +87,7 @@ public static ILMHistoryItem failure(
...
         Objects.requireNonNull(error, "ILM failures require an attached exception");
         String fullErrorString = exceptionToString(error);
-        String truncatedErrorString = LifecycleExecutionState.truncateWithExplanation(fullErrorString);
-        if (truncatedErrorString.equals(fullErrorString) == false) {
-            // Append a closing quote and closing brace to attempt to make it valid JSON.
-            // There is no requirement that it actually be valid JSON, so this is
-            // best-effort, but does not cause problems if it is still invalid.
-            truncatedErrorString += "\"}";
-        }
+        String truncatedErrorString = LifecycleExecutionState.potentiallyTruncateLongJsonWithExplanation(fullErrorString);
```
Comment (szybia) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java:90]: same functionality

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java [hunk 5]
```diff
@@ -87,13 +87,7 @@ public static ILMHistoryItem failure(
     ) {
         Objects.requireNonNull(error, "ILM failures require an attached exception");
         String fullErrorString = exceptionToString(error);
-        String truncatedErrorString = LifecycleExecutionState.truncateWithExplanation(fullErrorString);
-        if (truncatedErrorString.equals(fullErrorString) == false) {
-            // Append a closing quote and closing brace to attempt to make it valid JSON.
-            // There is no requirement that it actually be valid JSON, so this is
-            // best-effort, but does not cause problems if it is still invalid.
```
Comment (prdoyle) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java:94]: FWIW I'd recommend keeping some of this comment explaining that the correctness of this algorithm isn't critical.

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java [hunk 6]
```diff
@@ -287,15 +287,16 @@ public Map<String, String> asMap() {
...
+        if (json == null) {
+            return null;
         }
+        // Avoid no-op truncations: we must append `"}` (2 chars) to the end to keep JSON valid
+        if (json.length() <= MAXIMUM_STEP_INFO_STRING_LENGTH + 2) {
+            return json;
+        }
+        final int actuallyRemovedCharacters = json.length() - MAXIMUM_STEP_INFO_STRING_LENGTH - 2;
+        return Strings.cleanTruncate(json, MAXIMUM_STEP_INFO_STRING_LENGTH) + "... (" + actuallyRemovedCharacters + " chars truncated)\"}";
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: Do we actually care about the 2 extra chars? This truncation is just a way to avoid very long strings/json; it doesn't actually care about being exactly `MAXIMUM_STEP_INFO_STRING_LENGTH`. Couldn't we just leave the `2` out and slightly simplify this method?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java (hunk 5 above)
Comment (nielsbauman) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java:94]: Thanks for sharing your input, @prdoyle. This removed comment only applies to this place (ILM history) but not the other place (API). We could leave the comment here, but since the "algorithm" is correct now, I don't see much value in keeping the comment. Or am I missing something?

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java [hunk 7]
```diff
@@ -145,6 +146,38 @@ public void testGetCurrentStepKey() {
...
+    public void testPotentiallyTruncateLongJsonWithExplanationOneCharTruncated() {
+        final String jsonBaseFormat = "{\"key\": \"%s\"}";
+        final int baseLength = Strings.format(jsonBaseFormat, "").length();
+        final String value = randomAlphanumericOfLength(
+            // +3 because +1 and +2 are no-ops, they will truncate the end of JSON `"}` and then add it back,
+            // so we need another char to truncate.
+            LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH - baseLength + 3
+        );
+        final String input = Strings.format(jsonBaseFormat, value);
+        final String expectedOutput = Strings.format(jsonBaseFormat, value.substring(0, value.length() - 1) + "... (1 chars truncated)");
```
[the remark this answers is not in the document]
Comment (szybia) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java]: wouldn't exactly call this pressing, although i could do `char(s)` to be fully english'ized

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java (hunk 5 above)
Comment (szybia) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryItem.java:94]: my 2 cents is that
- the functionality in this place is the same as before, so code comment is still relevant here
- i'm not sure whether worth leaving here, i have carried over the knowledge in this code comment into the function though, since i can see Patrick's point, but i can leave some of this comment where it currently is if people deem it worthy

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java (hunk 6 above)
Comment (szybia) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: thanks for the review!

thought more about the function and simplified things a bit, and left comments there that should directly answer your Q about the `2`

but if i've missed your point please let me know here 🙏

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java [hunk 8]
```diff
@@ -217,6 +225,84 @@ public void testGetIndexLifecycleExplainResponse_rolloverOnlyIfHasDocuments_adds
...
+
+        final String longReasonMessage = "a".repeat(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH);
+        final String errorJsonWhichWillBeTruncated = Strings.toString((builder, params) -> {
+            ElasticsearchException.generateThrowableXContent(
+                builder,
+                ToXContent.EMPTY_PARAMS,
+                new IllegalArgumentException(longReasonMessage)
+            );
+            return builder;
+        });
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java]: Small nit, but I think we can make this slightly more compact like so:
```suggestion
        final final String errorJsonWhichWillBeTruncated = Strings.toString(new ElasticsearchException(new IllegalArgumentException(longReasonMessage)));
```

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java [hunk 9]
```diff
@@ -217,6 +225,84 @@ public void testGetIndexLifecycleExplainResponse_rolloverOnlyIfHasDocuments_adds
...
+        // Simulate transition to next step where previous_step_info is copied
+        final LifecycleExecutionState stateWithPreviousStepInfo = LifecycleExecutionState.builder(stateWithTruncatedStepInfo)
+            .setPreviousStepInfo(stateWithTruncatedStepInfo.stepInfo())
+            .setStepInfo(null)
+            .build();
+
+        final IndexMetadata indexMetadata = IndexMetadata.builder(indexName)
+            .settings(settings(IndexVersion.current()).put(LifecycleSettings.LIFECYCLE_NAME, policyName))
+            .numberOfShards(1)
+            .numberOfReplicas(0)
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java]: Another tiny stylistic nit:
```suggestion
            .settings(indexSettings(IndexVersion.current(), 1, 0).put(LifecycleSettings.LIFECYCLE_NAME, policyName))
```

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java [hunk 10]
```diff
@@ -217,6 +225,84 @@ public void testGetIndexLifecycleExplainResponse_rolloverOnlyIfHasDocuments_adds
         assertThat(rolloverAction.getConditions().getMinDocs(), is(1L));
     }
 
+    public void testPreviousStepInfoTruncationDoesNotBreakExplainJson() throws Exception {
+        final String policyName = "policy";
+        final String indexName = "index";
+
+        final String longReasonMessage = "a".repeat(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH);
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java]: Nit, any reason we can't just do
```suggestion
        final String longReasonMessage = randomAlphanumericOfLength(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH);
```
here too?

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java [hunk 11]
```diff
@@ -217,6 +225,84 @@ public void testGetIndexLifecycleExplainResponse_rolloverOnlyIfHasDocuments_adds
         assertThat(rolloverAction.getConditions().getMinDocs(), is(1L));
     }
 
+    public void testPreviousStepInfoTruncationDoesNotBreakExplainJson() throws Exception {
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java]: I'm not sure how I feel about this test. I assume your main goal of this test is to verify that not just `step_info` is truncated (as we verify in `LifecycleExecutionStateTests`), but also `previous_step_info` is truncated? Slight tangent: I am personally a fan of putting a non-obvious goal/intent of a test in the JavaDoc. If this test fails in the future (or we change behavior), it can be hard to extract the intent of a test just by looking at the code. Sometimes inline comments help, but a JavaDoc helps a lot in my experience.

If my assumption regarding your intent behind this test is correct, then I'm not sure this test really achieves that - but I do like the idea of validating that. Since we truncate the JSON in `.setStepInfo(errorJsonWhichWillBeTruncated)` (which some other tests already cover), this test essentially verifies that retrieving that string and putting it in the previous step info (`.setPreviousStepInfo(stateWithTruncatedStepInfo.stepInfo())`) still results in the same truncated string. It's not necessarily wrong, but I don't think it really adds any value. Instead, what I do think would be valuable is trying to get some integration test coverage on this. If we can think of a way to get a truncated step info in an integration test (likely an internal cluster test), we can check both the step info and previous step info fields. Additionally, we can easily include the JSON serialization verification there that you're doing explicitly here, which I think is very valuable.

I quickly played around with the `ExplainLifecycleIT.testStepInfoPreservedOnAutoRetry` integration test, and I think a (admittedly hacky) way of getting a truncated step info is by simply making the rollover alias name in the index template very long, like so:
```diff
diff --git a/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java b/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java
index 90ca9bf7929..ed2d826e904 100644
--- a/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java
+++ b/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java
@@ -299,7 +299,7 @@ public class ExplainLifecycleIT extends IlmESRestTestCase {
             }
             """;
         Formatter formatter = new Formatter(Locale.ROOT);
-        templateRequest.setJsonEntity(formatter.format(templateBodyTemplate, aliasName, policyName, aliasName).toString());
+        templateRequest.setJsonEntity(formatter.format(templateBodyTemplate, aliasName, policyName, randomAlphanumericOfLength(5000)).toString());
 
         assertOK(client().performRequest(templateRequest));
 
```
That actually makes that test fail already because it's trying to parse the JSON from the API. I assume your changes would make the test pass - or at least not fail on the JSON parsing.

That would then also hopefully allow us to verify the truncation on the previous step info.

Let me know what you think!

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java [hunk 12]
```diff
@@ -287,15 +287,23 @@ public Map<String, String> asMap() {
...
+        assert json.startsWith("{\"") && json.endsWith("\"}") : "expected more specific JSON format";
+        // we'll now do our best to truncate the JSON and have the result be valid JSON.
+        // a long input JSON should generally only be possible with an exception turned into JSON that's well-formatted.
+        // if we fail to produce valid JSON, we might return invalid JSON in REST API in niche cases, so this isn't catastrophic.
+        final int removedChars = json.length() - MAXIMUM_STEP_INFO_STRING_LENGTH;
+        // -2 to truncate characters within the JSON (before `"}`, which we add back in, so wouldn't actually be truncating anything),
+        // and to avoid invalid JSON if we truncate one character (result would be `"... (1 chars truncated)"}`,
+        // this adds a dangling double-quote).
+        // we don't aim to arrive at a string of exactly MAXIMUM_STEP_INFO_STRING_LENGTH, that's just the condition to apply truncation.
+        return Strings.cleanTruncate(json, MAXIMUM_STEP_INFO_STRING_LENGTH - 2) + "... (" + removedChars + " chars truncated)\"}";
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: This explanation didn't really help me much in understanding why we need the `- 2`; I had to read your tests to understand. IIRC, you're subtracting extra characters in case we only subtract one character, which would result in `some truncated test "... (1 chars truncated)"}`, where that first `"` would still cause JSON errors, right? But then why do we need to subtract 2 instead of just one? Also, instead of checking for `json.length() <= MAXIMUM_STEP_INFO_STRING_LENGTH`, couldn't we just do `json.length() <= MAXIMUM_STEP_INFO_STRING_LENGTH + 1` to avoid truncating only one char?

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java (hunk 11 above)
Comment (szybia) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java]: that's a great idea!

i should've flagged that i couldn't think of an idea on how to reproduce this error, so went with a "weaker" approach of simulating the error

hopefully i understood your point and my test looks good

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java (hunk 12 above)
Comment (szybia) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: you're nearly there!

i believe the part you're missing is that the `- 2` is **also** for correctness/accuracy because we're removing and then adding the `"}` back in:

i'll drop an example, but if i'm still not making sense then maybe checkout my branch and remove the `- 2` and run the `testPotentiallyTruncateLongJsonWithExplanationTwoCharsTruncated` test and see the result

example:
- if we have a JSON that is + 2 over the limit, let's say as an example JSON ending in `XYZ"}`
- without `- 2` here we will get `XYZ... (2 chars truncated)"}`, this doesn't "make sense" because we remove the `"}` just to add it back in, so we're not actually removing it
- with the `- 2` we get `X... (2 chars truncated)"}`, the explanation here is right

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java (hunk 8 above)
Comment (szybia) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportExplainLifecycleActionTests.java]: removed test so this is no longer applicable

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java [hunk 13]
```diff
@@ -287,15 +287,27 @@ public Map<String, String> asMap() {
...
-        }
+    public static String potentiallyTruncateLongJsonWithExplanation(String json) {
+        if (json == null) {
+            return null;
+        }
+        final boolean jsonWithinLimit = json.length() <= MAXIMUM_STEP_INFO_STRING_LENGTH;
+        final boolean jsonAlreadyTruncated = json.endsWith("chars truncated)\"}");
+        // already-truncated JSON will always be over the limit, since we add the extra `chars truncated` explanation at the end.
+        // hence another check to not 1) double-truncate needlessly 2) lose information (we'll truncate current number of truncated chars)
+        if (jsonWithinLimit || jsonAlreadyTruncated) {
```
Comment (szybia) [inline server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: re. point 2): after adding the test suggested by Niels, realized this func is called multiple times on a single stepInfo, if that's truncated at the start, we will truncate twice, meaning we will blow away the explanation of number of truncated chars, and replace this with incorrect number of truncated chars, but the string will still be truncated

if neither my code comment, nor this comment explains it well, then you're free to checkout the branch, remove the ` || jsonAlreadyTruncated`, and run the `testTruncatedPreviousStepInfoDoesNotBreakExplainJson` test

we get an invalid number of truncated chars, because we've truncated more in reality
```
... (27 chars truncated)}
```

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java [hunk 14]
```diff
@@ -321,6 +320,65 @@ public void testStepInfoPreservedOnAutoRetry() throws Exception {
         }, 30, TimeUnit.SECONDS);
     }
 
+    public void testTruncatedPreviousStepInfoDoesNotBreakExplainJson() throws Exception {
+        final String policyName = "policy-" + randomAlphaOfLength(5).toLowerCase(Locale.ROOT);
+
+        final Request createPolice = new Request("PUT", "_ilm/policy/" + policyName);
```
[the remark this answers is not in the document]
Comment (szybia) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java]: gonna wait to see if Niels has any extra feedback before pushing...

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java (hunk 12 above)
Comment (szybia) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: (just for solidarity, i am showing my empathy by saying my changes are surprisingly complex for what we're doing..., you could even say over-engineered, i'd love to hear any alternative approaches i haven't considered, or relaxing `correctness` here which will lead to cleaner code)

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java (hunk 13 above)
Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: What if we remove `("... (" + removedChars + " chars truncated)\"}").length()` number characters instead of just 2? There's a cyclic dependency there because that length depends on the number of digits you need to represent `removedChars`, but I think we can get away with just making it an approximation rather than an exact number of characters.

That would make the method idempotent, because we ensure that the resulting string is `<= MAXIMUM_STEP_INFO_STRING_LENGTH`, therefore no-opping any future calls of the method on the resulting string. Additionally, that would allow us to drop the `- 2`, because we'll always be truncating more than 2 characters to fit our appended string into it.

I think that would simplify some things, but I haven't actually tried/experimented whether that would work. What do you think?

Comment (szybia) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: hmmm, i think i'm roughly following... although sorry, i do think i'd need to see some code to confidently say i understand your suggestion before responding 🙏 

but having a guess i do slightly struggle to see how this would be simpler than what i have (now that might be because i wrote it and i understand it!), but would be great if you could cook up something simpler

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: This is what I had in mind:
```java
    /**
     * Truncates a potentially long JSON string to ensure it does not exceed {@link #MAXIMUM_STEP_INFO_STRING_LENGTH}. If truncation
     * occurs, an explanation suffix is appended to the truncated string indicating <i>approximately</i> how many characters were removed.
     * @param json the JSON string to potentially truncate
     * @return the original JSON string if its length is within the limit, otherwise a truncated version with an explanation suffix - in
     * correct JSON format
     */
    public static String potentiallyTruncateLongJsonWithExplanation(String json) {
        if (json == null || json.length() <= MAXIMUM_STEP_INFO_STRING_LENGTH) {
            return json;
        }
        // How many characters we _say_ we deleted.
        final int allegedNumberOfCharsTruncated = json.length() - MAXIMUM_STEP_INFO_STRING_LENGTH;
        // The string we append to the truncated string.
        final String truncationString = "... (~" + allegedNumberOfCharsTruncated + " chars truncated)\"}";
        // To ensure that the resulting string is always <= the max, we also need to remove the length of our suffix.
        // This means that the actual number of characters removed is `truncationString.length()` more than we say it is.
        return Strings.cleanTruncate(json, MAXIMUM_STEP_INFO_STRING_LENGTH - truncationString.length()) + truncationString;
    }
```
I hope that my comments make it clear what my intention is, but let me know if you have questions, and let me know what you think of course. I think this makes the method significantly easier, trading off some accuracy which we don't really care about in this case (IMO).

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: Ah, I forgot to add a comment that this method is guaranteed to return a string <= the max, making it idempotent. We should add a test for the latter, and perhaps even an assertion inside the method to verify that our returned result is always <= the max.

Comment (szybia) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java]: nice one! that makes sense

i guess would be nice to be accurate but i agree that given the over-complexity (in a non-important area) that comes along with it i like your approach

pushed up changes, i tweaked a few things around like var names and extra comments but hope it's good

thanks for iterating with me patiently!

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java [hunk 15]
```diff
@@ -28,13 +32,18 @@ public void testTruncatingStepInfo() {
...
+        assertThat(newState.stepInfo().length(), equalTo(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH));
         assertThat(
-            newState.stepInfo().substring(LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH, 1049),
-            equalTo("... (100 chars truncated)")
+            newState.stepInfo()
+                .substring(
+                    LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH - 28,
+                    LifecycleExecutionState.MAXIMUM_STEP_INFO_STRING_LENGTH
+                ),
+            equalTo("... (~111 chars truncated)\"}")
```
Comment (nielsbauman) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java]: We could also do
```suggestion
            newState.stepInfo(),
            endsWith("... (~111 chars truncated)\"}")
```

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java [hunk 16]
```diff
@@ -145,6 +154,56 @@ public void testGetCurrentStepKey() {
         assertNull(error6.getMessage());
     }
 
+    public void testPotentiallyTruncateLongJsonWithExplanationNotTruncated() {
```
Comment (nielsbauman) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java]: Can you add one-sentence explanations to these tests to explain what they test exactly? Especially the ones below have pretty minor differences so it's hard to tell what each one is testing exactly?

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java [hunk 17]
```diff
@@ -321,6 +320,65 @@ public void testStepInfoPreservedOnAutoRetry() throws Exception {
         }, 30, TimeUnit.SECONDS);
     }
 
+    public void testTruncatedPreviousStepInfoDoesNotBreakExplainJson() throws Exception {
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:336]: Can you also add an explanation here? Since this test is a bit bigger, perhaps we need a bit more than one sentence.

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java [hunk 18]
```diff
@@ -287,15 +287,29 @@ public Map<String, String> asMap() {
...
-            return Strings.cleanTruncate(input, MAXIMUM_STEP_INFO_STRING_LENGTH)
-                + "... ("
-                + (input.length() - MAXIMUM_STEP_INFO_STRING_LENGTH)
-                + " chars truncated)";
-        } else {
-            return input;
-        }
+    /**
+     * Truncates a potentially long JSON string to ensure it does not exceed {@link #MAXIMUM_STEP_INFO_STRING_LENGTH}. If truncation
+     * occurs, an explanation suffix is appended to the truncated string indicating <i>approximately</i> how many characters were removed.
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java:292]: One more nit: perhaps we can also include one sentence on why we're fine with this approximation instead of a more accurate (but complex) number. What do you think?

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java (hunk 17 above)
Comment (szybia) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:336]: explanations/comments should be added 🚀 

let me know whether you'd like to see any wording adjustments

File: server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java (hunk 18 above)
Comment (szybia) [reply server/src/main/java/org/elasticsearch/cluster/metadata/LifecycleExecutionState.java:292]: left a comment saying we prefer code simplicity

but lmk whether you would also like reasons stated (idempotency, etc.); or whether i missed your point entirely

**Review by nielsbauman — APPROVED** [review]
LGTM! Thanks a lot for the work and the iterations! 🚀
