### PR TITLE
[ML] allow unran/incomplete forecasts to be deleted for stopped/failed jobs

### LINKED ISSUE #56419: [ML] Force closing an ML job can leave unfinished forecast jobs behind
**Affected versions**:  6.1 - 

**Problem**

When a ml job is force closed the native process gets terminated without waiting for unfinished forecasts. These forecasts end as `started` or in progress but will never finish. This is only a reporting problem, there are no hanging processes or tasks.

**Mitigation**

Delete using the UI or the [API](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-delete-forecast.html)

**Fix discussion**

A force close should cleanup queued forecasts or mark them as failed.

### PR DESCRIPTION
**Pull request by benwtrent**
If a job is NOT opened, forecasts should be able to be deleted, no matter their state.

This also fixes a bug with expanding forecast IDs. We should check for wildcard `*` and `_all` when expanding the ids

closes https://github.com/elastic/elasticsearch/issues/56419

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastActionTests.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+            try {
+                TransportDeleteForecastAction.validateForecastState(
+                    forecastRequestStats,
+                    randomFrom(JobState.values()),
+                    randomAlphaOfLength(10)
+                );
+            } catch (Exception ex) {
+                fail("Should not have thrown: " + ex.getMessage());
+            }
```
Comment (droberts195) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastActionTests.java:39]: You could just replace this with a comment that the test is that no exception is thrown.  JUnit will fail tests that throw exceptions, and we'll still get the stack trace.  Catching and calling `fail` will actually lose the stack trace of any completely unexpected exception that happens to get thrown.

Same on lines 58-60.

**Review by droberts195 — APPROVED** [review]
LGTM, but there is one non-standard aspect to the tests that ought to be changed before merging
