### PR TITLE
The root object mapper should support updating `numeric_detection`, `date_detection` and `dynamic_date_formats`.

### LINKED ISSUE #20111: adding `date_detection: false` to an existing _type returns `"acknowledged": true`, but does not get added.
**Elasticsearch version**: 2.3.5
**JVM version**:
```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```
**Description of the problem including expected versus actual behavior**:
adding `date_detection: false` to an existing _type returns `"acknowledged": true`, but does not actually get added.

**Steps to reproduce**:
```
POST test2
PUT test2/_mapping/test
{
  "properties": {
    "date": {
      "type": "string"
    }
  }
}
POST test2/test
{ "date": "2014-01-01" }

PUT test2/_mapping/test
{
  "date_detection": false
}
GET test2/_mapping
```

### PR DESCRIPTION
**Pull request by jpountz**
If they are specified by a mapping update, these properties are currently
ignored. This commit also fixes the handling of `dynamic_templates` so that it
is possible to remove templates (and so that it works more similarly to all
other mapping properties).

Closes #20111

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 1]
```diff
@@ -300,9 +300,6 @@ protected static void parseProperties(ObjectMapper.Builder objBuilder, Map<Strin
 
         }
 
-        protected Builder createBuilder(String name) {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: thank you! :)

**Comment by rjernst** [comment]
LGTM

**Comment by jpountz** [comment]
Thanks @rjernst
