### PR TITLE
Json parsing exceptions should not cause 500 errors

### LINKED ISSUE #111542: Malformed Json can lead to 500 errors
### Elasticsearch Version

8.14.3

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin 22.6.0 Darwin Kernel Version 22.6.0: Mon Jun 24 01:22:14 PDT 2024; root:xnu-8796.141.3.706.2~1/RELEASE_ARM64_T6000 arm64 

### Problem Description

When I send incomplete Json request bodies (like `{` ) to ES, it bubbles up the resulting JsonEOFException as an XContentEOFException and I get a 500 error on the client side. I believe this should be a 400 instead.

### Steps to Reproduce

Install ES 8.14.3 locally,

```
curl localhost:9200/_search -H "Content-Type: application/json" -d '{'
```

Response:

```
{
    "error": {
        "root_cause": [
            {
                "type": "x_content_e_o_f_exception",
                "reason": "com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (byte[])\"{\"; line: 1, column: 1])\n at [Source: (byte[])\"{\"; line: 1, column: 2]"
            }
        ],
        "type": "x_content_e_o_f_exception",
        "reason": "com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (byte[])\"{\"; line: 1, column: 1])\n at [Source: (byte[])\"{\"; line: 1, column: 2]",
        "caused_by": {
            "type": "json_e_o_f_exception",
            "reason": "Unexpected end-of-input: expected close marker for Object (start marker at [Source: (byte[])\"{\"; line: 1, column: 1])\n at [Source: (byte[])\"{\"; line: 1, column: 2]"
        }
    },
    "status": 500
}
```

### Logs (if relevant)

[2024-08-02T11:54:38,145][WARN ][r.suppressed             ] [xxx] path: /_search, params: {}, status: 500org.elasticsearch.xcontent.XContentEOFException: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (byte[])"{"; line: 1, column: 1])
 at [Source: (byte[])"{"; line: 1, column: 2]
	at org.elasticsearch.xcontent.impl@8.14.3/org.elasticsearch.xcontent.provider.json.JsonXContentParser.nextToken(JsonXContentParser.java:60)
	at org.elasticsearch.server@8.14.3/org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1298)
	at org.elasticsearch.server@8.14.3/org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1259)
	at org.elasticsearch.server@8.14.3/org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:181)
	at org.elasticsearch.server@8.14.3/org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$1(RestSearchAction.java:120)

### PR DESCRIPTION
**Pull request by cbuescher**
Currently we wrap JsonEOFException from advancing the json parser into our own XContentEOFException, but this has the drawback that is results in 500 errors on the client side. Instead this should be 400 errors. We should throw XContentParseException instead like we e.g. already to in the "nextFieldName" method or elsewhere in JsonXContentParser.

Closes #111542

### CODE REVIEW

**Comment by cbuescher** [comment]
tagging @elastic/es-core-infra for awareness and you own general xcontent issues, but we found this while looking into 500s from the "_search" endpoint, so also tagging search foundations.

**Comment by cbuescher** [comment]
I ended up removing the whole XContentEOFException, the only place we differentiate based on the cause of an XContentParseException seems to be the warning in the BulkRequestParser that is going to be removed anyway.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkRequestParser.java [hunk 1]
```diff
@@ -421,12 +421,22 @@ private static void checkBulkActionIsProperlyClosed(XContentParser parser) throw
...
-        } catch (XContentEOFException ignore) {
-            warnBulkActionNotProperlyClosed(
-                "A bulk action wasn't closed properly with the closing brace. Malformed objects are currently accepted but will be "
-                    + "rejected in a future version."
-            );
-            return;
+        } catch (XContentParseException e) {
+            Throwable cause = e.getCause();
+            if (cause != null) {
+                String exName = cause.getClass().getName();
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkRequestParser.java:427]: This workaround was necessary because we don't seem to have JsonEOFException on the classpath here. The class name is readable at runtime though it seems.

**Comment by dnhatn** [comment]
We can also throw IllegalStateException while parsing XContent.

```
java.lang.IllegalStateException: Can't get text on a START_ARRAY at 1:30
	at org.elasticsearch.xcontent.impl@8.16.0/org.elasticsearch.xcontent.provider.json.JsonXContentParser.throwOnNoText(JsonXContentParser.java:113)
	at org.elasticsearch.xcontent.impl@8.16.0/org.elasticsearch.xcontent.provider.json.JsonXContentParser.text(JsonXContentParser.java:107)
	at org.elasticsearch.xcontent.impl@8.16.0/org.elasticsearch.xcontent.provider.json.JsonXContentParser.objectText(JsonXContentParser.java:139)
	at org.elasticsearch.xcontent@8.16.0/org.elasticsearch.xcontent.FilterXContentParser.objectText(FilterXContentParser.java:114)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.MatchQueryBuilder.fromXContent(MatchQueryBuilder.java:549)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.search.SearchModule.lambda$registerQuery$23(SearchModule.java:1279)
	at org.elasticsearch.xcontent@8.16.0/org.elasticsearch.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:148)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.AbstractQueryBuilder$1.namedObject(AbstractQueryBuilder.java:402)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:436)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.AbstractQueryBuilder.parseTopLevelQuery(AbstractQueryBuilder.java:410)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1417)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1298)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:181)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$1(RestSearchAction.java:120)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.rest.RestRequest.withContentOrSourceParamParserOrNull(RestRequest.java:544)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.rest.action.search.RestSearchAction.prepareRequest(RestSearchAction.java:119)
```

File: server/src/main/java/org/elasticsearch/action/bulk/BulkRequestParser.java (hunk 1 above)
Comment (rjernst) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkRequestParser.java:427]: You should not assume JsonEOFException exists, jackson is intentionally hidden, it is an implementation detail of xcontent.

**Comment by dnhatn** [comment]
Another error

```
com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (byte[])\"
{
  \"query\": {
    \"query_string\": {
      \"query\": \"KAFFE TRINA JUMPR Celestial Blue
xtra Small\"
    }
  }
}\"; line: 5, column: 50]
\tat com.fasterxml.jackson.core@2.15.0/com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
\tat com.fasterxml.jackson.core@2.15.0/com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:750)
\tat com.fasterxml.jackson.core@2.15.0/com.fasterxml.jackson.core.base.ParserBase._throwUnquotedSpace(ParserBase.java:1374)
\tat com.fasterxml.jackson.core@2.15.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2631)
\tat com.fasterxml.jackson.core@2.15.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2560)
\tat com.fasterxml.jackson.core@2.15.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:335)
\tat org.elasticsearch.xcontent.impl@8.16.0/org.elasticsearch.xcontent.provider.json.JsonXContentParser.text(JsonXContentParser.java:109)
\tat org.elasticsearch.xcontent@8.16.0/org.elasticsearch.xcontent.FilterXContentParser.text(FilterXContentParser.java:94)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.QueryStringQueryBuilder.fromXContent(QueryStringQueryBuilder.java:690)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.search.SearchModule.lambda$registerQuery$23(SearchModule.java:1279)
\tat org.elasticsearch.xcontent@8.16.0/org.elasticsearch.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:148)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.AbstractQueryBuilder$1.namedObject(AbstractQueryBuilder.java:402)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.AbstractQueryBuilder.parseInnerQueryBuilder(AbstractQueryBuilder.java:436)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.index.query.AbstractQueryBuilder.parseTopLevelQuery(AbstractQueryBuilder.java:410)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1417)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1298)
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:181)
```

**Comment by cbuescher** [comment]
@rjernst thanks for the review, I changed the base class of XContentEOFException as suggested. This should be ready for another review now.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@rjernst thanks a lot, merging
