### PR TITLE
SQL: fix URI path being lost in case of hosted ES scenario

### LINKED ISSUE #44721: SQL JDBC and CLI fails when ES hosted under path
**Describe the feature**:

**Elasticsearch version** : v6.8.0

**Plugins installed**: [mapper_size]

**JVM version** : openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

**OS version** : SQL client on Windows 10

**Description of the problem including expected versus actual behavior**:

The SQL JDBC documentation states the following URL syntax is valid. 

`jdbc:es://[[http|https]://]*[host[:port]]*/[prefix]*<[?[option=value]&]*`

With "Prefix (empty by default). Typically used when hosting Elasticsearch under a certain path. Optional."

When ES is hosted under a different path, the JDBC driver ignores the path and attempts to connect to the / root with a GET /?error_trace.

**Steps to reproduce**:

ES is running happily behind Nginx, on the path "es_rest" (reverse proxied to localhost:9200). When I configure the JDBC path `jdbc:es://https://myhost.example.com:443/es_rest/`, the driver ignores /es_rest/ and attempts to connect to `jdbc:es://https://myhost.example.com:443/`.

### PR DESCRIPTION
**Pull request by astefan**
`URI.resolve()` method doesn't work as we intended it to work and when an URI of the form `http://localhost:8080/custom_path/` is being used (common in reverse proxy scenarios), the `resolve("/_sql")` (very common path resolve) call will strip the `custom_path` from the URI and just put `/_sql` instead. Whereas the desired behavior should be appending the additional segment to the existent URI and creating the `http://localhost:8080/custom_path/_sql` URI.

This PR fixes https://github.com/elastic/elasticsearch/issues/44721.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/UriUtils.java [hunk 1]
```diff
@@ -76,4 +76,30 @@ public static URI removeQuery(URI uri, String connectionString, URI defaultURI)
...
+            path = "/";
+        }
+
+        if (path.charAt(path.length() - 1) == '/') {
+            concatenatedPath = path + cleanSegment;
+        } else {
+            concatenatedPath = path + "/" + cleanSegment;
+        }
+        try {
+            return new URI(uri.getScheme(), uri.getUserInfo(), uri.getHost(), uri.getPort(), concatenatedPath,
```
Comment (matriv) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/UriUtils.java]: Why not using new `URI(concatenatedPath)` ?

**Review by matriv — APPROVED** [review]
LGTM

For completeness I would add a test with null `segment` and tests with null and empty `uri`.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/UriUtils.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/UriUtils.java]: Because `concatenatedPath` is only the `uri.getPath()` section of the initial URI. If one has `http://localhost:9200/es_rest/` path is `/es_rest/`. And this method's purpose is to add a new segment to the already existent path: `http://localhost:9200/es_rest/` + `/_sql` for example.
