### PR TITLE
[Transform] handle pit index not found error

### LINKED ISSUE #81252: [Transform] Transform fails with task encountered irrecoverable failure: org.elasticsearch.index.IndexNotFoundException
**Affected version**: 7.15-
**Fixed with**: TBD

Transform can fail with an `IndexNotFoundException` if you use transform on a data stream, index pattern or alias that covers _multiple indices_ and you use index lifecycle management to delete old indices. In the case a transform updates documents while an index gets deleted by index lifecycle management the transform might fail.

This error is a regression introduced in 7.15, details below. Transform can be used together with index lifecycle management on source indices. 

**Mitigation**

Until a fix is available you have 3 options:

 - stay on an older version or don't upgrade to a version >= 7.15 until a fix is available
 - don't use ILM to delete old data or ensure transform isn't running when ILM deletes an index
 - watch and restart transform after a failure:

```
POST _transform/{job_id}/_stop?force=true&wait_for_completion=true
POST _transform/{job_id}/_start
```

You need `force=true` for jobs that are in failed state.
`wait_for_completion=true` waits until the transform has really stopped, otherwise it might not be stopped if you call _start right after - within nanoseconds - in a script.
You can use a `_stats` call to find out if a transform is in failed state.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
Do not fail the transform if pit search fails with index not found as a result of an index that got deleted via ILM, if that index is part of a search that selects indices using a wildcard, e.g. `logs-*`. If pit search fails, the search is retried using search without a pit
context. The 2nd search might fail if the source targets an explicit index. In addition the usage of the pit API can not be disabled by transform.

fixes #81252
relates #81256

### CODE REVIEW

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/SettingsConfig.java [hunk 1]
```diff
@@ -215,8 +241,23 @@ public Builder setAlignCheckpoints(Boolean alignCheckpoints) {
             return this;
         }
 
+        /**
+         * Whether the point in time API should be used for search.
+         * Point in time is a more resource friendly way to query. It is used per default. In case of problems
```
Comment (przemekwitek) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/SettingsConfig.java:246]:
```suggestion
         * Point in time is a more resource friendly way to query. It is used by default. In case of problems
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java [hunk 2]
```diff
@@ -128,6 +156,14 @@ public Integer getAlignCheckpointsForUpdate() {
         return alignCheckpoints;
     }
 
+    public Boolean getUsePit() {
+        return usePit != null ? (usePit > 0) || (usePit == DEFAULT_USE_PIT) : null;
+    }
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java:161]: Why are we allowing `null` here on the server side? Either it is using `pit` or not.

I initially thought "oh this is for bwc", but you specifically set `this.usePit = DEFAULT_USE_PIT` when the supplied value is `null`.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java [hunk 3]
```diff
@@ -172,6 +211,9 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
         if (alignCheckpoints != null && (alignCheckpoints.equals(DEFAULT_ALIGN_CHECKPOINTS) == false)) {
             builder.field(TransformField.ALIGN_CHECKPOINTS.getPreferredName(), alignCheckpoints > 0 ? true : false);
         }
+        if (usePit != null && (usePit.equals(DEFAULT_USE_PIT) == false)) {
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java:214]: This is probably a larger conversation but:
> // do not write default values

Seems like a bad idea as a whole. This means we have to consider older transforms automatically (and unexpectedly) changing their behavior between versions. 

But, I suppose that is a larger idea outside of this PR. To me, being explicit makes more sense.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 4]
```diff
@@ -111,6 +113,19 @@
 
         // TODO: move into context constructor
         context.setShouldStopAtCheckpoint(shouldStopAtCheckpoint);
+
+        if (transformConfig.getSettings().getUsePit() != null) {
+            disablePit = transformConfig.getSettings().getUsePit() == false;
+        }
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:119]: `getUsePit()` should know about the default value and not return a boxed boolean.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 5]
```diff
@@ -111,6 +113,19 @@
...
+    }
+
+    @Override
+    public void applyNewSettings(SettingsConfig newSettings) {
+        if (newSettings.getUsePit() != null) {
+            disablePit = newSettings.getUsePit() == false;
+        }
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:126]: same here

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java [hunk 6]
```diff
@@ -286,6 +290,92 @@ public void testPitInjectionIfPitNotSupported() throws InterruptedException {
...
+                    Collections.emptyMap(),
+                    Instant.now().toEpochMilli()
+                ),
+                new SeqNoPrimaryTermAndIndex(1, 1, TransformInternalIndexConstants.LATEST_INDEX_NAME),
+                mock(TransformContext.class),
+                false
+            );
+
+            this.<SearchResponse>assertAsync(listener -> indexer.doNextSearch(0, listener), response -> {
+                if (pitEnabled) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java:333]: I'm wondering if this is too complicated for a test.
We could get rid of conditional statements if we fixed the scenario: pit is first enabled and then disabled.

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java [hunk 7]
```diff
@@ -286,6 +290,92 @@ public void testPitInjectionIfPitNotSupported() throws InterruptedException {
...
+            SearchRequest searchRequest = new SearchRequest("deleted-index");
+            searchRequest.source().pointInTimeBuilder(new PointInTimeBuilder("the_pit_id"));
+            Tuple<String, SearchRequest> namedSearchRequest = new Tuple<>("test-handle-pit-index-not-found", searchRequest);
+            this.<SearchResponse>assertAsync(listener -> indexer.doSearch(namedSearchRequest, listener), response -> {
+                // if the pit got deleted, we know it retried
+                assertNull(response.pointInTimeId());
+            });
+        }
+
+        // simulate a deleted index that is essential, search must fail(after a retry without pit)
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java:366]:
```suggestion
        // simulate a deleted index that is essential, search must fail (after a retry without pit)
```

**Review by przemekwitek — APPROVED** [review]

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java:161]: From what I can tell, the only time to allow `null` is on an update. And update never calls `getUsePit()`.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java (hunk 3 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java:214]: ^ Just a passing thought, I know this won't get adjusted in this PR as we want consistency with how settings are handled.

Comment (hendrikmuhs) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java:214]: for pit we are not changing the default. If we decide to change it: yes we need to ensure the behavior works according to the version the transform has been created. Fortunately this is not the case for pit.

But we have changed defaults and e.g. introduced `dates_as_epoch_millis` and `align_checkpoints`. They work by checking the version in addition to the setting, so e.g. for version < 7.11  `dates_as_epoch_millis` is `true`, after 7.11 it is `false`. Note  `dates_as_epoch_millis` does not exist < 7.11

Update has another component: When it rewrites the config it checks the version and e.g. rewrites a 7.11 transform to a current transform, but sets the setting accordingly.

This works actually. We currently have a tiny glitch for `align_checkpoints`, but that fix is in the makings.

Nevertheless this fits to your other comment: settings are returned as Boolean and can be `null`, so the `null` check has to happen on the implementation.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java (hunk 4 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:119]: /CC @przemekwitek WDYT? 

I think with requiring a default, the issue with `align_checkpoints` would not have happened, right?

Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:119]: `boolean getUsePit(boolean default)`

If we are going to keep them boxed, Java already has a way to handle this with `Optional`. 

So

```
Optional<Boolean> getUsePit()
```
```
getUsePit().orElse(true)
```
For epoch millis
```
getDatesAsEpochMillis().orElse(version.before(Version.V_7_11_0))
```

**Review by benwtrent — APPROVED** [review]
