### PR TITLE
SQL: Fix query translation of GroupBy with Having

### LINKED ISSUE #33520: SQL: translate API doesn't generate the correct query
The SQL query itself returns results and doesn't throw any exceptions, but the ES query `translate` API is generating for the same SQL query doesn't work.

Example: `select avg("salary"), day("hire_date") from "test_emp" group by day("hire_date") having avg("salary") >50000` works from CLI and returns results:

```
sql> select avg("salary"), day("hire_date") from "test_emp" group by day("hire_date") having avg("salary") >50000;
   AVG(salary)    |DAY_OF_MONTH(hire_date [UTC])
------------------+-----------------------------
56518.5           |3
51396.0           |7
67490.0           |10
54515.0           |12
68547.0           |16
52973.5           |17
59202.28571428572 |18
51378.75          |19
61805.0           |28
62958.333333333336|30
```

But the `translate` API returns the following:

```
{
    "size": 0,
    "_source": false,
    "stored_fields": "_none_",
    "aggregations": {
        "groupby": {
            "composite": {
                "size": 1000,
                "sources": [
                    {
                        "493": {
                            "terms": {
                                "script": {
                                    "source": "InternalSqlScriptUtils.dateTimeChrono(doc[params.v0].value.millis, params.v1, params.v2)",
                                    "lang": "painless",
                                    "params": {
                                        "v0": "hire_date",
                                        "v1": "UTC",
                                        "v2": "DAY_OF_MONTH"
                                    }
                                },
                                "missing_bucket": true,
                                "value_type": "number",
                                "order": "asc"
                            }
                        }
                    }
                ]
            },
            "aggregations": {
                "494": {
                    "avg": {
                        "field": "salary"
                    }
                },
                "497": {
                    "bucket_selector": {
                        "buckets_path": {
                            "a0": "497"
                        },
                        "script": {
                            "source": "params.a0 > params.v0",
                            "lang": "painless",
                            "params": {
                                "v0": 50000
                            }
                        },
                        "gap_policy": "skip"
                    }
                }
            }
        }
    }
}
```

The issue is at `bucket_selector`'s `buckets_path` - it generates a loop. And running the query generated by the `translate` API logs this exception:

```
[elasticsearch] org.elasticsearch.transport.RemoteTransportException: [node-0][127.0.0.1:9300][indices:data/read/search[phase/query]]
[elasticsearch] Caused by: java.lang.IllegalArgumentException: Cyclical dependency found with pipeline aggregator [464]
[elasticsearch]         at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.resolvePipelineAggregatorOrder(AggregatorFactories.java:362) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.resolvePipelineAggregatorOrder(AggregatorFactories.java:410) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.resolvePipelineAggregatorOrder(AggregatorFactories.java:351) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:324) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.search.aggregations.AggregatorFactory.<init>(AggregatorFactory.java:187) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregationFactory.<init>(CompositeAggregationFactory.java:40) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by matriv**
Two issues are resolved:
1. The `value_type` should be long or double in case of numeric.
2. The key label for the aggregate filter (having) was duplicate of an aggr key.

Fixes: #33520

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM.

So why did the query worked? Was the Java API more lenient then the translate, which caused serialization which on reload caused extra validation?

**Comment by matriv** [comment]
@costin Yep the query works because it skips the Xcontent validations that take place when the query is posted through the HTTP _search API.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/GroupByScriptKey.java [hunk 1]
```diff
@@ -39,8 +39,12 @@ public TermsValuesSourceBuilder asValueSource() {
                 .order(direction().asOrder())
                 .missingBucket(true);
 
-        if (script.outputType().isNumeric()) {
-            builder.valueType(ValueType.NUMBER);
+        if (script.outputType().isInteger) {
+            builder.valueType(ValueType.LONG);
+        } else if (script().outputType().isRational) {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/GroupByScriptKey.java]: Why here accessing the `script` via the public method, and for the other values checks directly the field?

**Review by astefan — APPROVED** [review]
Left one minor comment. LGTM otherwise.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/GroupByScriptKey.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/GroupByScriptKey.java]: no reason :-), will change, thx!

**Comment by matriv** [comment]
Backported to `6.x` with 5ddd512702a535bfd066c2482a8b149a3cd446b1
