### PR TITLE
Fix release tests after merging geogrid types

### LINKED ISSUE #133886: [CI] VerifierTests testChangePoint_keySortable failing
**Build Scans:**
- [elasticsearch-periodic #10362 / release-tests](https://gradle-enterprise.elastic.co/s/usod4gmsiih3a)
- [elasticsearch-periodic #10356 / release-tests](https://gradle-enterprise.elastic.co/s/kumcldznvdtuk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.analysis.VerifierTests.testChangePoint_keySortable" -Dtests.seed=505693D976285BD2 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=hr-HR -Dtests.timezone=Europe/Kirov -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.analysis.VerifierTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testChangePoint_keySortable'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected VerificationException but got org.elasticsearch.xpack.esql.core.QlIllegalArgumentException: Cannot find function by class class org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToGeohash
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 failures in test testChangePoint_keySortable (2.1% fail rate in 95 executions)
- [main] 2 failures in step release-tests (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #133887: [CI] VerifierTests testChangePoint_valueNumeric failing
**Build Scans:**
- [elasticsearch-periodic #10362 / release-tests](https://gradle-enterprise.elastic.co/s/usod4gmsiih3a)
- [elasticsearch-periodic #10356 / release-tests](https://gradle-enterprise.elastic.co/s/kumcldznvdtuk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.analysis.VerifierTests.testChangePoint_keySortable" -Dtests.seed=505693D976285BD2 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=hr-HR -Dtests.timezone=Europe/Kirov -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.analysis.VerifierTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testChangePoint_valueNumeric'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected VerificationException but got org.elasticsearch.xpack.esql.core.QlIllegalArgumentException: Cannot find function by class class org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToGeohash
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 failures in test testChangePoint_valueNumeric (2.1% fail rate in 95 executions)
- [main] 2 failures in step release-tests (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #133888: [CI] VerifierTests testSpatialSort failing
**Build Scans:**
- [elasticsearch-periodic #10362 / release-tests](https://gradle-enterprise.elastic.co/s/usod4gmsiih3a)
- [elasticsearch-periodic #10356 / release-tests](https://gradle-enterprise.elastic.co/s/kumcldznvdtuk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.analysis.VerifierTests.testChangePoint_keySortable" -Dtests.seed=505693D976285BD2 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=hr-HR -Dtests.timezone=Europe/Kirov -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.analysis.VerifierTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSpatialSort'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected VerificationException but got org.elasticsearch.xpack.esql.core.QlIllegalArgumentException: Cannot find function by class class org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToGeohash
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 failures in test testSpatialSort (2.1% fail rate in 95 executions)
- [main] 2 failures in step release-tests (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #133889: [CI] ParsingTests testInlineCast failing
**Build Scans:**
- [elasticsearch-periodic #10386 / release-tests](https://gradle-enterprise.elastic.co/s/lvg4axkou7pzg)
- [elasticsearch-periodic #10380 / release-tests](https://gradle-enterprise.elastic.co/s/qvinwqvvzghfq)
- [elasticsearch-periodic #10374 / release-tests](https://gradle-enterprise.elastic.co/s/cahqvzbvw5sfy)
- [elasticsearch-periodic #10368 / release-tests](https://gradle-enterprise.elastic.co/s/fdv45rxbn4oxq)
- [elasticsearch-periodic-java-ea #8 / release-tests](https://gradle-enterprise.elastic.co/s/lmq7bbiqvb5zk)
- [elasticsearch-periodic #10362 / release-tests](https://gradle-enterprise.elastic.co/s/usod4gmsiih3a)
- [elasticsearch-periodic #10356 / release-tests](https://gradle-enterprise.elastic.co/s/kumcldznvdtuk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.analysis.ParsingTests.testInlineCast" -Dtests.seed=5658630F3615790B -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ks-Deva-IN -Dtests.timezone=Europe/Minsk -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.analysis.ParsingTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testInlineCast'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.core.QlIllegalArgumentException: Cannot find function by class class org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToGeohash
```

**Issue Reasons:**
- [main] 7 consecutive failures in step release-tests
- [main] 7 failures in test testInlineCast (3.3% fail rate in 213 executions)
- [main] 7 failures in step release-tests (100.0% fail rate in 7 executions)
- [main] 6 failures in pipeline elasticsearch-periodic (100.0% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by craigtaverner**
The PR at https://github.com/elastic/elasticsearch/pull/129581 did not carefully check that all tests also work as release tests. This lead to some CI failures, which we are fixing here.

Fixes #133886
Fixes #133887
Fixes #133888
Fixes #133889

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/ParsingTests.java [hunk 1]
```diff
@@ -93,6 +94,10 @@ public void testInlineCast() throws IOException {
             report.humanReadable(true).prettyPrint();
             report.startObject();
             List<String> namesAndAliases = new ArrayList<>(DataType.namesAndAliases());
+            if (Build.current().isSnapshot() == false) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/ParsingTests.java]: I'd replace this by a check for the specific capability. Otherwise, it's easy to forget to change this piece of code once that geotiles get enabled permanently.

Also applies to the other test fixes.

**Review by alex-spies — APPROVED** [review]
Looks good, thanks! I have one comment that I think should be taken care of before merging, but please proceed at your own discretion.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/ParsingTests.java (hunk 1 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/ParsingTests.java]: Done
