### PR TITLE
EQL: cover head/tail commands edge cases and data types coverage

### LINKED ISSUE #101724: EQL: Head and tail fail to gracefully deal with invalid values
### Description

A query like `any where true | head 2147483648` fails with `class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')`.

While one like `any where true | head 2147483640 + 8` fails with `"type": "arithmetic_exception", "reason": "integer overflow"`.

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/101724

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine update branch

File: x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/LogicalPlanTests.java [hunk 1]
```diff
@@ -227,6 +230,28 @@ public void testSamplePlan() {
         assertEquals("host", key.name());
     }
 
+    public void testFoldedHeadTailValidValue() {
+        String limit = randomFrom(" head ", " tail ");
+        // explicitly set this as long to force a LONG literal as the limit
+        String longValue = String.valueOf((long) Integer.MAX_VALUE + 1L);
```
Comment (alex-spies) [inline x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/parser/LogicalPlanTests.java:236]: super-duper nit: could replace the `1L` by a random value.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java [hunk 2]
```diff
@@ -531,6 +545,11 @@ private Expression pipeIntArgument(Source source, String pipeName, List<BooleanE
             );
         }
 
+        if (expression.dataType() != INTEGER && expression.dataType() != SHORT && expression.dataType() != BYTE) {
+            // 2147483650 - 4 will yield an integer (Integer.MAX_VALUE - 1) but the expression itself (SUB) will be of type LONG
+            // and this type will be used when being folded later on
+            return new Literal(expression.source(), value.intValue(), INTEGER);
+        }
         return expression;
```
Comment (alex-spies) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:553]: question: could we replace this by
```suggestion
        return new Literal(expression.source(), value.intValue(), expression.dataType());
```
to leverage the fact that we already folded the expression?

**Review by alex-spies — APPROVED** [review]
Not an EQL expert atm, but this LGTM!

**Review by luigidellaquila — APPROVED** [review]
LGTM

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java [hunk 3]
```diff
@@ -521,8 +524,19 @@ private Expression onlyOnePipeArgument(Source source, String pipeName, List<Bool
...
         Expression expression = onlyOnePipeArgument(source, pipeName, exps);
+        boolean foldableInt = expression.dataType().isInteger() && expression.foldable();
+        boolean foldingError = false;
+        Number value = null;
+
+        if (foldableInt) {
+            try {
+                value = (Number) expression.fold();
+            } catch (ArithmeticException ae) {
+                foldingError = true;
```
Comment (bpintea) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:535]: Should we simply check `value` against `null` later, rather then setting a flag here, in case folding yields a `null` w/o an exception?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java [hunk 4]
```diff
@@ -521,8 +524,19 @@ private Expression onlyOnePipeArgument(Source source, String pipeName, List<Bool
...
+            }
+        }
 
-        if (expression.dataType().isInteger() == false || expression.foldable() == false || (int) expression.fold() < 0) {
+        if (foldableInt == false || foldingError || value.intValue() != value.longValue() || value.intValue() < 0) {
```
Comment (bpintea) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:539]: Optional:
```
} else if (<value checks, knowing `foldableInt` is `false`>) {
```

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java [hunk 5]
```diff
@@ -531,6 +545,11 @@ private Expression pipeIntArgument(Source source, String pipeName, List<BooleanE
             );
         }
 
+        if (expression.dataType() != INTEGER && expression.dataType() != SHORT && expression.dataType() != BYTE) {
```
Comment (bpintea) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:548]: Do we need to keep the SHORT/BYTE type around? We have value that is a non-negative int here.
```suggestion
        if (expression.dataType() != INTEGER) {
```

**Review by bpintea — APPROVED** [review]
I've raised some minor questions, otherwise it LGTM.
However, wondering if we couldn't answer the issues [here](https://github.com/elastic/elasticsearch/pull/100918/files#r1380530774) now (but can remain for later too).

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:553]: `expression.dataType()` can be something different than INTEGER. See https://github.com/elastic/elasticsearch/pull/101859/files#diff-123105fcd0030e62f4100ab1424e1e978bcffa93eb64169867557eb3136c0fe1R549

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java (hunk 5 above)
Comment (astefan) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:548]: This is, in practice, true (I don't see a way in which a foldable literal other than INTEGER can reach this line), but the contract of the code here is about `expression.dataType().isInteger()` which covers all integer-like data types. I'll keep it as is, maybe at some point we'll add some casting functions (very not likely, but still).

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java (hunk 4 above)
Comment (astefan) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:539]: I'll keep it as is, I find it less cluttered.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java (hunk 3 above)
Comment (astefan) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:535]: Yes. Providing a `null` as a value to `head` or `tail` still breaks the "positive integer" restriction.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java]: I've changed it to always return an INTEGER Literal, since we already folded the value.
But this is not entirely correct, because the folding itself should be dealt with in the Optimizer.ConstantFolding rule. But there are situations (`head number("123")`) where the function itself (`number`) hasn't been resolved yet in order to be folded.
