### PR TITLE
Don't count metadata fields towards index.mapping.total_fields.limit

### LINKED ISSUE #24096: Doc: Clarify count for index.mapping.total_fields.limit
https://www.elastic.co/guide/en/elasticsearch/reference/5.3/mapping.html#mapping-limit-settings

>index.mapping.total_fields.limit
The maximum number of fields in an index. The default value is 1000.

Currently, documentation simply says `index.mapping.total_fields.limit` is the max number of fields in an index.  For end users who are looking at the mappings api output and doing a count for validation, they will notice that ES will return a limit exception before the perceived # of fields hit 1000.  

This is because `index.mapping.total_fields.limit` includes the count of [meta](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/mapping-fields.html) fields and most of these will not show up in the mappings api output.  It will be nice to clarify this in the documentation, similar to how we do clarify that index.mapping.depth.limit counts also the root level as 1 level.

### PR DESCRIPTION
**Pull request by cbuescher**
The maximum number of fields per index is limited to 1000 by default by the
`index.mapping.total_fields.limit` setting to prevent accidental mapping
explosions due to too many fields. Currently all metadata fields also count
towards this limit, which can lead to some confusion when using lower limits.
It is not obvious for users that they cannot actually add as many fields as
are specified by the limit in this case.

This change takes the number of metadata fields out of the field count that we
check against the field limit. It also adds tests that check that we can add
fields up to the specified limit, but throw an exception for any additional field added.

Closes #24096

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 1]
```diff
@@ -281,22 +286,20 @@ public void testTotalFieldsLimitWithFieldAlias() throws Throwable {
             .endObject()
         .endObject().endObject());
 
-        DocumentMapper documentMapper = createIndex("test1").mapperService()
-            .merge("type", new CompressedXContent(mapping), MergeReason.MAPPING_UPDATE);
+        int numberOfFieldIncludingAlias = 2;
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java]: (small comment) `numberOfField` -> `numberOfFields`

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 2]
```diff
@@ -281,22 +286,20 @@ public void testTotalFieldsLimitWithFieldAlias() throws Throwable {
...
+        createIndex("test1", Settings.builder()
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java]: Thanks for improving this test!

**Review by jtibshirani — COMMENTED** [review]
It looks good to me, just one comment for your consideration. As part of this change, it would be nice to update the documentation for the setting (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-limit-settings), as the behavior is not obvious in general. In addition to the issue around metadata fields, it wasn't clear to me that object mappings would be included until I read the code.

I'm guessing we don't need an upgrade note, since the enforcement of the setting is now more lenient than before.

**Review by jtibshirani — APPROVED** [review]
