### PR TITLE
Fix failure for validate API on a terms query

### LINKED ISSUE #29033: Validate API fails when validating Terms query
**Elasticsearch version**: 6.2.2

**Plugins installed**: -

**JVM version**: 1.8.0_161

**OS version** : docker image

**Description of the problem including expected versus actual behavior**:

The validate API is failing when attempting to validate a valid [terms query](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-terms-query.html). The following error message is shown:

> nested: IllegalStateException[async actions are left after rewrite];; java.lang.IllegalStateException: async actions are left after rewrite

**Steps to reproduce**:

```
PUT twitter
{}
```
```
PUT twitter/_mapping/_doc
{
  "properties": {
    "user": { "type": "integer" },
    "followers": { "type": "integer" }
  }
}
```
```
POST twitter/_validate/query?explain=true
{
  "query": {
    "terms": {
      "user": {
        "index": "twitter",
        "type": "_doc",
        "id": "2",
        "path": "followers"
      }
    }
  }
```

**Provide logs (if relevant)**:

Response from the validate API:
```
{
  "valid": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "explanations": [
    {
      "index": "twitter",
      "valid": false,
      "error": """
[twitter/v460ppW7Q6SMXFcqf1Q5SA] QueryShardException[failed to create query: {
  "terms" : {
    "user" : {
      "index" : "twitter",
      "type" : "_doc",
      "id" : "2",
      "path" : "followers"
    },
    "boost" : 1.0
  }
}]; nested: IllegalStateException[async actions are left after rewrite];; java.lang.IllegalStateException: async actions are left after rewrite
"""
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by pcsanwald**
Fixes #29033, currently WIP as I need to fix a few integration tests. As @colings86 described on the issue, we're missing a step for terms queries, we need to rewrite the query on the coordinating node.

Steps to reproduce (and confirm fix)

1. Run a local server: `./gradlew server`

2. create index `curl -XPUT 'localhost:9200/twitter' -H 'Content-Type: application/json' -d'{}'`

3. add mapping `curl -XPUT 'localhost:9200/twitter/_mapping/_doc' -H 'Content-Type: application/json' -d'{ "properties": { "user": { "type": "integer" }, "followers": { "type": "integer" } } }'`

4. run a validate request on a terms query: `curl -XPOST 'localhost:9200/twitter/_validate/query?explain=true' -H 'Content-Type: application/json' -d'{ "query": { "terms": { "user": { "index": "twitter", "type": "_doc", "id": "2", "path": "followers" } } } }'`

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java [hunk 1]
```diff
@@ -39,21 +45,24 @@
...
 import org.elasticsearch.threadpool.ThreadPool;
+import org.elasticsearch.transport.RemoteClusterAware;
 import org.elasticsearch.transport.TransportService;
 
 import java.io.IOException;
-import java.util.ArrayList;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: This will fail `precommit`.

File: server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java [hunk 2]
```diff
@@ -39,21 +45,24 @@
...
 import org.elasticsearch.index.query.QueryShardException;
+import org.elasticsearch.index.query.Rewriteable;
 import org.elasticsearch.search.SearchService;
+import org.elasticsearch.search.builder.SearchSourceBuilder;
 import org.elasticsearch.search.internal.AliasFilter;
 import org.elasticsearch.search.internal.SearchContext;
 import org.elasticsearch.search.internal.ShardSearchLocalRequest;
 import org.elasticsearch.tasks.Task;
 import org.elasticsearch.threadpool.ThreadPool;
+import org.elasticsearch.transport.RemoteClusterAware;
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: I see a lot of unnecessary imports here.

**Review by jasontedor — COMMENTED** [review]
I left some comments.

File: server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java [hunk 3]
```diff
@@ -71,7 +73,37 @@ public TransportValidateQueryAction(Settings settings, ThreadPool threadPool, Cl
     @Override
     protected void doExecute(Task task, ValidateQueryRequest request, ActionListener<ValidateQueryResponse> listener) {
         request.nowInMillis = System.currentTimeMillis();
-        super.doExecute(task, request, listener);
+        LongSupplier timeProvider = () -> request.nowInMillis;
+        ActionListener<org.elasticsearch.index.query.QueryBuilder> rewriteListener = ActionListener.wrap(rewrittenQuery -> {
+            request.query(rewrittenQuery);
+            super.doExecute(task, request, listener);
+        }, ex -> {
```
Comment (pcsanwald) [inline server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: I added this section (with advice from @imotov) to address a deficiency in the code uncovered by one of our integration tests, `org.elasticsearch.validate.SimpleValidateQueryIT.testExplainValidateQueryTwoNodes`, which tests an error case. Because originally I was propagating the listener's `onError` method, an XContent exception was being thrown by the server, rather than wrapped in a response that wraps the error according to our conventions (yay, integration tests!).

My "fix" raises a few questions about what the right response looks like, given this context.

**Comment by pcsanwald** [comment]
Added some integration test fixes, and my own comments about those fixes; I could use some advice on the best way to handle this error in the right way at the point in execution where it's occurring (on the coordinating node, so there are no shards involved yet in the query).

File: server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java [hunk 4]
```diff
@@ -71,7 +73,37 @@ public TransportValidateQueryAction(Settings settings, ThreadPool threadPool, Cl
...
+            List<QueryExplanation> explanations = new ArrayList<>();
```
Comment (pcsanwald) [inline server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: Soooo, @colings86 and I just discussed this and we arrived at what we feel is a better solution: use a new object, CoordinatingNodeRewriteError (or some TBD name) and add it as optional to the `ValidateQueryResponse`, which addresses the concerns I had about shoehorning this error into QueryExplanation which is really written to describe shard level operations.

Since this is a new, albeit optional thing, I'll also:

- [ ] Update documentation to reflect change and make it clear that this new explanation and List<QueryExplanation> are mutually exclusive in the response
- [ ] Check with Luca that high level REST client will serialize/de-serialize, I'll add code/tests for this if necessary
- [ ] include version checking in serialization to ensure backwards compatibility

Since Colin is on holiday next week, I'll annoy @jpountz for a review in his absence.

Comment (jpountz) [reply server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: If you don't mind, Colin is much more familiar than I am with this, can it wait?

**Comment by pcsanwald** [comment]
@jpountz happy to wait

**Review by colings86 — COMMENTED** [review]
@pcsanwald I left some comments

File: server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java [hunk 5]
```diff
@@ -71,7 +75,41 @@ public TransportValidateQueryAction(Settings settings, ThreadPool threadPool, Cl
...
+            super.doExecute(task, request, listener);
+        },
+            ex -> {
+            if (ex instanceof IndexNotFoundException ||
+                ex instanceof IndexClosedException) {
+                listener.onFailure(ex);
+            }
+            List<QueryExplanation> explanations = new ArrayList<>();
+            // TODO[PCS]: given that we can have multiple indices, what's the best way to include
+            // these in a query explanation?
```
[the remark this answers is not in the document]
Comment (colings86) [reply server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: I think this TODO can be removed now?

File: server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/QueryExplanation.java [hunk 6]
```diff
@@ -88,7 +92,11 @@ public void readFrom(StreamInput in) throws IOException {
 
     @Override
     public void writeTo(StreamOutput out) throws IOException {
-        out.writeString(index);
+        if (out.getVersion().onOrAfter(Version.V_7_0_0_alpha1)) {
+            out.writeOptionalString(index);
+        } else {
+            out.writeString(index);
+        }
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/action/admin/indices/validate/query/QueryExplanation.java]: I think that we should back port this fix to 6.4. These version checks are fine to leave here for now but when you back port you will need to change them to `Version.V_6_4_0` in the back ported commit on the 6.x branch an then after that add a new commit to the master branch to change these checks to `Version.V_6_4_0` on master too. This process avoids getting CI failures before you've had a chance to back port the commit to 6.x.

File: server/src/main/java/org/elasticsearch/index/query/Rewriteable.java [hunk 7]
```diff
@@ -111,7 +113,7 @@
                 }
             }
             rewriteResponse.onResponse(builder);
-        } catch (IOException ex) {
+        } catch (IOException|XContentParseException|ParsingException ex) {
```
[the remark this answers is not in the document]
Comment (colings86) [reply server/src/main/java/org/elasticsearch/index/query/Rewriteable.java]: Reminder about this comment in case you missed it before?

**Review by colings86 — COMMENTED** [review]
@pcsanwald I think this is close, I left a couple of comments but they should be quick fixes. I also left a comment on the version checks and how they will need to be dealt with through back-porting to 6.x. I'm happy to walk through this process in more detail with you if you would like.

**Comment by pcsanwald** [comment]
@elasticmachine please test this

**Comment by pcsanwald** [comment]
@elasticmachine test this please

**Review by colings86 — APPROVED** [review]
LGTM
