### PR TITLE
ES|QL: reduce memory footprint for MvAppendTests with shapes

### LINKED ISSUE #109409: [CI] MvAppendTests testEvaluateBlockWithoutNulls {TestCase=<cartesian_shape>, <cartesian_shape>} failing
**Build Scans:**
- [elasticsearch-periodic #3030 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/kspmf5tnfasba)
- [elasticsearch-pull-request #21515 / part-3](https://gradle-enterprise.elastic.co/s/4yfw7myjrplly)
- [elasticsearch-pull-request #21509 / part-3](https://gradle-enterprise.elastic.co/s/esrcdz2zlez5m)
- [elasticsearch-periodic-platform-support #2993 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/pfhes247y2coe)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvAppendTests.testEvaluateBlockWithoutNulls {TestCase=<cartesian_shape>, <cartesian_shape>}" -Dtests.seed=B4578B401A674D28 -Dtests.locale=es-UY -Dtests.timezone=SystemV/AST4 -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testEvaluateBlockWithoutNulls%20%7BTestCase%3D%3Ccartesian_shape%3E%2C%20%3Ccartesian_shape%3E%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvAppendTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Test data is too large to fit in the memory
```

**Mute Reasons:**
- [main] 4 failures in test testEvaluateBlockWithoutNulls {TestCase=<cartesian_shape>, <cartesian_shape>} (3.1% fail rate)
- [main] 3.1% failure rate in test testEvaluateBlockWithoutNulls {TestCase=<cartesian_shape>, <cartesian_shape>} (3.1% fail rate)

**Note:**
This issue was created using new, in-development muting automation. Please mind any issues.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixing MvAppendTests CB exceptions by generating smaller geometries: the test generates a lot of documents and the CB is too small for multiple big shapes.

Fixes https://github.com/elastic/elasticsearch/issues/109409

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-5

**Review by craigtaverner — APPROVED** [review]
This seems OK, although I can think of possibly other ways of doing this more directly. Since the issue is total memory of the random geometry, we could use a `ESTestCase.randomValueOtherThanMany` with a predicate that measures the geometry size. The current solution reduces the likelihood of large collections, but does not directly measure or limit the total size.

**Comment by luigidellaquila** [comment]
Thanks @craigtaverner, I refactored the tests following your suggestions, now it looks much better

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvAppendTests.java [hunk 1]
```diff
@@ -235,8 +247,25 @@ private static void bytesRefs(List<TestCaseSupplier> suppliers) {
         }));
 
         suppliers.add(new TestCaseSupplier(List.of(DataType.GEO_SHAPE, DataType.GEO_SHAPE), () -> {
-            List<Object> field1 = randomList(1, 5, () -> new BytesRef(GEO.asWkt(GeometryTestUtils.randomGeometry(randomBoolean()))));
-            List<Object> field2 = randomList(1, 5, () -> new BytesRef(GEO.asWkt(GeometryTestUtils.randomGeometry(randomBoolean()))));
+            GeometryPointCountVisitor pointCounter = new GeometryPointCountVisitor();
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvAppendTests.java:250]: It would be nice to move this to a utility class for use in other tests.

Comment (craigtaverner) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvAppendTests.java:250]: It would be nice to move this to a utility class for use in other tests.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvAppendTests.java [hunk 2]
```diff
@@ -293,4 +339,65 @@ private static void nulls(List<TestCaseSupplier> suppliers) {
             );
         }));
     }
+
+    public static class GeometryPointCountVisitor implements GeometryVisitor<Integer, RuntimeException> {
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvAppendTests.java:343]: It would be nice to move this to a utility class for use in other tests.

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvAppendTests.java:343]: https://github.com/elastic/elasticsearch/pull/109837
