### PR TITLE
No longer add illegal content type option to stored search templates

### LINKED ISSUE #24227: "POST’ing Search Template as REST API causes Elastic to fail on start"
> I POST an search template using REST API, and it works as excepted.
> But when I restart the es after  registering the template, it throws an exception.
Origin question [Link](https://discuss.elastic.co/t/posting-search-template-as-rest-api-causes-elastic-to-fail-on-start/82552)  https://discuss.elastic.co/t/posting-search-template-as-rest-api-causes-elastic-to-fail-on-start/82552

I am also getting the same exception.

### PR DESCRIPTION
**Pull request by colings86**
When parsing StoredSearchScript we were adding a Content type option that was forbidden (by a check that threw an exception) by the parser thats used to parse the template when we read it from the cluster state. This was stopping Elastisearch from starting after stored search templates had been added.

This change no longer adds the content type option to the StoredScriptSource object when parsing from the put search template request.  This is safe because the StoredScriptSource content is always JSON when its stored in the cluster state since we do a conversion to JSON before this point.

Also removes the check for the content type in the options when parsing StoredScriptSource so users who already have stored scripts can start Elasticsearch.

Closes #24227

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/script/StoredScriptSource.java [hunk 1]
```diff
@@ -266,8 +262,7 @@ public static StoredScriptSource parse(String lang, BytesReference content, XCon
                         //this is really for search templates, that need to be converted to json format
                         try (XContentBuilder builder = XContentFactory.jsonBuilder()) {
                             builder.copyCurrentStructure(parser);
-                            return new StoredScriptSource(lang, builder.string(),
-                                Collections.singletonMap(Script.CONTENT_TYPE_OPTION, XContentType.JSON.mediaType()));
+                            return new StoredScriptSource(lang, builder.string(), Collections.emptyMap());
```
Comment (jdconrad) [inline core/src/main/java/org/elasticsearch/script/StoredScriptSource.java]: Since the check is being removed, maybe it makes sense to continue to store this with the content-type set to JSON?  This works now because of the default in the mustache engine.

**Review by jdconrad — APPROVED** [review]
LGTM!  Thank you for looking into this issue and fixing it!  Left one minor comment.

**Review by nik9000 — APPROVED** [review]
I think it'd be nice to have an upgrade test that creates templates but I think this gets the job done and we can build that test later.

File: core/src/test/java/org/elasticsearch/script/StoredScriptSourceTests.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+            template.startObject();
+            template.startObject("query");
+            template.startObject("match");
+            template.field("title", "{{query_string}}");
+            template.endObject();
+            template.endObject();
+            template.endObject();
+            Map<String, String> options = new HashMap<>();
+            if (randomBoolean()) {
+                options.put(Script.CONTENT_TYPE_OPTION, xContentType.mediaType());
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/script/StoredScriptSourceTests.java]: Maybe add a comment here about how we don't really like the content_type option but we have to support it for 5.3.0 and 5.3.1?

File: core/src/main/java/org/elasticsearch/script/StoredScriptSource.java (hunk 1 above)
Comment (colings86) [inline core/src/main/java/org/elasticsearch/script/StoredScriptSource.java]: I think we should not store the content type so we can add the check back in a later version?

Comment (javanna) [inline core/src/main/java/org/elasticsearch/script/StoredScriptSource.java]: I think that we should have different code-paths for when we validate user inputs and when we parse stuff from cluster state. We should not fail if we set the content-type ourselves, but only if it was set by users, I guess. In that case we wouldn't have to remove the check in `setOptions`, if it was only performed for user input. Yet, I am not too familiar with this validation check and I cannot tell how important it is, nor when it was introduced.

Side note: the reason why removing the content-type from the options map doesn't affect the parsing side of things seems to be that json is the default mime type anyways, so it didn't need to be set to json explicitly, see https://github.com/elastic/elasticsearch/blob/master/modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/CustomMustacheFactory.java#L79 .

Comment (jdconrad) [inline core/src/main/java/org/elasticsearch/script/StoredScriptSource.java]: I agree with @javanna that we should ultimately have different paths for user input and loading cluster state, but I think that can be done in a follow up PR.

I added the ability add compiler options because it may be needed for Painless in the future and there was already a single option there for templates anyway so it made sense to encapsulate it.  Content-type is reserved internally for templates only, so this check was preventing non-template scripts from specifying content-type.  The search template API never allows options to be input anyway so it's not a problem there.  Removal of this check should be safe for now since scripting languages at worst will ignore compiler options or in the case of Painless see an unrecognized option and fail at compile time.

Comment (javanna) [inline core/src/main/java/org/elasticsearch/script/StoredScriptSource.java]: ok I am totally fine with removing the check for now and reintroducing it later once we have two different code-paths.

**Review by javanna — APPROVED** [review]

**Comment by colings86** [comment]
I'm away from my laptop now so unless anyone else can/wants to merge and back port this PR I'll do it first thing Monday morning.

**Comment by nik9000** [comment]
> I'm away from my laptop now so unless anyone else can/wants to merge and back port this PR I'll do it first thing Monday morning.

I've kicked off a test run of this and #24258 locally. If it passes I'll merge and start the backport dance. But I'm going to be in and out all day so it probably won't be until tomorrow when I finish it.

**Comment by nik9000** [comment]
All backported.

**Comment by colings86** [comment]
@nik9000 thanks very much for doing this
