### PR TITLE
Reindex-from-remote: Validate basic auth params

### LINKED ISSUE #135925: Wrong/missing error when supplying username but not password or vice versa for reindex-from-remote
### Elasticsearch Version

Latest

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

If you send a reindex-from-remote request and you specify `source.remote.username` but omit the `password`, you get a 500 response with an error message reporting a null pointer exception. This should be a 400 with a description of the user error. (If assertions are enabled, an assertion kills the node instead.)

If you include the `password` but not the `username`, you'll get a 401 with an error message reporting missing credentials (assuming that the remote cluster requires authentication — if it doesn't, it will succeed). This should also ideally be a 400, though this is less important since at least we're getting a 4**.

The cause is that (a) we fail to catch these invalid requests during request validation, and (b) the `Reindexer` code checks for a non-null username to decide whether to trigger the basic auth pathway, which dereferences the password without checking: https://github.com/elastic/elasticsearch/blob/745c5c39d66c3e1938d8c176d9075245f3467569/modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java#L171-L179

The simple fix is to add the missing request validation. Consideration will need to be given to the backwards compatibility policy. This definitely seems justified for the `username` but no `password` case where we get a 500; more thought may be needed for the vice versa case where we get a 401.

### Steps to Reproduce

To reproduce the 500 response:

1. Start an ES cluster with `reindex.remote.whitelist` set to `localhost:9200` (or the host and port of your chosen target cluster). If running locally, also disable assertions, e.g. with

```
./gradlew run -Dtests.es.reindex.remote.whitelist=localhost:9200 -Dtests.jvm.argline="-da -dsa"
```

2. Send a request with `username` but no `password`, and your chose host and port:

```
POST /_reindex
{
  "source": {
    "remote": {
      "host": "http://localhost:9200",
      "username": "me"
    },
    "index": "my-remote-index"
  },
  "dest": {
    "index": "my-copied-index"
  }
}
```

3. Observe the following response:
```
{
  "error" : {
    "root_cause" : [
      {
       	"type" : "null_pointer_exception",
	"reason" : "Cannot invoke \"org.elasticsearch.common.settings.SecureStr\
ing.toString()\" because the return value of \"org.elasticsearch.index.reindex.\
RemoteInfo.getPassword()\" is null"
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : "Cannot invoke \"org.elasticsearch.common.settings.SecureString.\
toString()\" because the return value of \"org.elasticsearch.index.reindex.Remo\
teInfo.getPassword()\" is null"
  },
  "status" : 500
}
```

If you change the request to include a `password` but omit the `username`, you'll get this instead:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "status_exception",
        "reason" : "body={\"error\":{\"root_cause\":[{\"type\":\"security_excep\
tion\",\"reason\":\"missing authentication credentials for REST request [/]\",\\
"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\", charset=\\\"UT\
F-8\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"missing a\
uthentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\
\":[\"Basic realm=\\\"security\\\", charset=\\\"UTF-8\\\"\",\"ApiKey\"]}},\"sta\
tus\":401}"
      }
    ],
    "type" : "status_exception",
    "reason" : "body={\"error\":{\"root_cause\":[{\"type\":\"security_exception\
\",\"reason\":\"missing authentication credentials for REST request [/]\",\"hea\
der\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\", charset=\\\"UTF-8\\
\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"missing authe\
ntication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\
\"Basic realm=\\\"security\\\", charset=\\\"UTF-8\\\"\",\"ApiKey\"]}},\"status\\
":401}",
    "caused_by" : {
      "type" : "response_exception",
      "reason" : "method [GET], host [http://localhost:9200], URI [/], status l\
ine [HTTP/1.1 401 Unauthorized]\n{\"error\":{\"root_cause\":[{\"type\":\"securi\
ty_exception\",\"reason\":\"missing authentication credentials for REST request\
 [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\", charse\
t=\\\"UTF-8\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"m\
issing authentication credentials for REST request [/]\",\"header\":{\"WWW-Auth\
enticate\":[\"Basic realm=\\\"security\\\", charset=\\\"UTF-8\\\"\",\"ApiKey\"]\
}},\"status\":401}"
    }
  },
  "status" : 401
}
```

### Logs (if relevant)

```
[2025-10-03T12:46:48,364][WARN ][r.suppressed             ] [runTask-0] path: /_reindex, params: {pretty=true}, status: 500 java.lang.NullPointerException: Cannot invoke "org.elasticsearch.common.settings.SecureString.toString()" because the return value of "org.elasticsearch.index.reindex.RemoteInfo.getPassword()" is null
        at org.elasticsearch.reindex.Reindexer.lambda$buildRestClient$4(Reindexer.java:174)
        at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:344)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:74)
        at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:288)
        at org.elasticsearch.reindex.Reindexer.buildRestClient(Reindexer.java:196)
        at org.elasticsearch.reindex.Reindexer$AsyncIndexBySearchAction.buildScrollableResultSource(Reindexer.java:275)
        at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.<init>(AbstractAsyncBulkByScrollAction.java:178)
        at org.elasticsearch.reindex.Reindexer$AsyncIndexBySearchAction.<init>(Reindexer.java:232)
        at org.elasticsearch.reindex.Reindexer.lambda$execute$1(Reindexer.java:138)
        at org.elasticsearch.reindex.BulkByScrollParallelizationHelper.executeSlicedAction(BulkByScrollParallelizationHelper.java:97)
        at org.elasticsearch.reindex.Reindexer.execute(Reindexer.java:118)
        at org.elasticsearch.reindex.TransportReindexAction.lambda$doExecute$0(TransportReindexAction.java:114)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:233)
        at org.elasticsearch.reindex.BulkByScrollParallelizationHelper.initTaskState(BulkByScrollParallelizationHelper.java:129)
        at org.elasticsearch.reindex.Reindexer.initTask(Reindexer.java:112)
        at org.elasticsearch.reindex.TransportReindexAction.doExecute(TransportReindexAction.java:111)
        at org.elasticsearch.reindex.TransportReindexAction.doExecute(TransportReindexAction.java:37)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:135)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:54)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.MappedActionFilters$MappedFilterChain.proceed(MappedActionFilters.java:71)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.MappedActionFilters.apply(MappedActionFilters.java:49)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$4(SecurityActionFilter.java:182)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:233)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:673)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:644)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$14(AuthorizationService.java:541)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1064)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1030)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:406)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:326)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:222)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:180)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:538)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:452)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:339)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(RBACEngine.java:176)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$4(CompositeRolesStore.java:217)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$6(CompositeRolesStore.java:236)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.xcore@9.3.0-SNAPSHOT/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$0(RoleReferenceIntersection.java:49)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:57)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.buildRoleFromRoleReference(CompositeRolesStore.java:268)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$5(CompositeRolesStore.java:235)
        at org.elasticsearch.xcore@9.3.0-SNAPSHOT/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$1(RoleReferenceIntersection.java:53)
        at java.base/java.util.ImmutableCollections$List12.forEach(ImmutableCollections.java:681)
        at org.elasticsearch.xcore@9.3.0-SNAPSHOT/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.buildRole(RoleReferenceIntersection.java:53)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(CompositeRolesStore.java:234)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:210)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:172)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:355)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$5(SecurityActionFilter.java:178)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:111)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticate(AuthenticatorChain.java:105)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:274)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:178)

        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:174)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:131)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction.handleExecution(TransportAction.java:96)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:59)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:222)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:107)
        at org.elasticsearch.reindex.AbstractBaseReindexRestHandler.lambda$doPrepareRequest$0(AbstractBaseReindexRestHandler.java:53)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:143)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:486)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:480)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:105)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$0(SecurityRestFilter.java:90)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$3(SecondaryAuthenticator.java:99)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:109)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:90)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$2(SecurityRestFilter.java:80)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:96)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:480)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController.lambda$maybeAggregateAndDispatchRequest$4(RestController.java:404)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestContentAggregator$AggregationChunkHandler.onNext(RestContentAggregator.java:78)
        at org.elasticsearch.transport.netty4@9.3.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream.handleNettyContent(Netty4HttpRequestBodyStream.java:87)
        at org.elasticsearch.transport.netty4@9.3.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:146)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler@4.1.126.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
        at io.netty.handler@4.1.126.Final/io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:847)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.transport@4.1.126.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
        at io.netty.common@4.1.126.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1474)

[2025-10-03T12:49:55,218][WARN ][r.suppressed             ] [runTask-0] path: /_reindex, params: {pretty=true}, status: 500 java.lang.NullPointerException: Cannot invoke "org.elasticsearch.common.settings.SecureString.toString()" because the return value of "org.elasticsearch.index.reindex.RemoteInfo.getPassword()" is null
        at org.elasticsearch.reindex.Reindexer.lambda$buildRestClient$4(Reindexer.java:174)
        at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:344)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:74)
        at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:288)
        at org.elasticsearch.reindex.Reindexer.buildRestClient(Reindexer.java:196)
        at org.elasticsearch.reindex.Reindexer$AsyncIndexBySearchAction.buildScrollableResultSource(Reindexer.java:275)
        at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.<init>(AbstractAsyncBulkByScrollAction.java:178)
        at org.elasticsearch.reindex.Reindexer$AsyncIndexBySearchAction.<init>(Reindexer.java:232)
        at org.elasticsearch.reindex.Reindexer.lambda$execute$1(Reindexer.java:138)
        at org.elasticsearch.reindex.BulkByScrollParallelizationHelper.executeSlicedAction(BulkByScrollParallelizationHelper.java:97)
        at org.elasticsearch.reindex.Reindexer.execute(Reindexer.java:118)
        at org.elasticsearch.reindex.TransportReindexAction.lambda$doExecute$0(TransportReindexAction.java:114)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:233)
        at org.elasticsearch.reindex.BulkByScrollParallelizationHelper.initTaskState(BulkByScrollParallelizationHelper.java:129)
        at org.elasticsearch.reindex.Reindexer.initTask(Reindexer.java:112)
        at org.elasticsearch.reindex.TransportReindexAction.doExecute(TransportReindexAction.java:111)
        at org.elasticsearch.reindex.TransportReindexAction.doExecute(TransportReindexAction.java:37)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:135)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:54)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.MappedActionFilters$MappedFilterChain.proceed(MappedActionFilters.java:71)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.MappedActionFilters.apply(MappedActionFilters.java:49)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$4(SecurityActionFilter.java:182)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:233)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:673)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:644)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$14(AuthorizationService.java:541)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1064)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1030)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:406)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:326)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:222)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:180)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:538)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:452)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:339)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(RBACEngine.java:176)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$4(CompositeRolesStore.java:217)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$6(CompositeRolesStore.java:236)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.xcore@9.3.0-SNAPSHOT/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$0(RoleReferenceIntersection.java:49)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:57)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.buildRoleFromRoleReference(CompositeRolesStore.java:268)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$5(CompositeRolesStore.java:235)
        at org.elasticsearch.xcore@9.3.0-SNAPSHOT/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$1(RoleReferenceIntersection.java:53)
        at java.base/java.util.ImmutableCollections$List12.forEach(ImmutableCollections.java:681)
        at org.elasticsearch.xcore@9.3.0-SNAPSHOT/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.buildRole(RoleReferenceIntersection.java:53)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(CompositeRolesStore.java:234)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:210)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:172)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:355)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$5(SecurityActionFilter.java:178)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:111)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticate(AuthenticatorChain.java:105)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:274)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:178)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:174)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:131)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction.handleExecution(TransportAction.java:96)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:59)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:222)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:107)
        at org.elasticsearch.reindex.AbstractBaseReindexRestHandler.lambda$doPrepareRequest$0(AbstractBaseReindexRestHandler.java:53)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:143)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:486)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:480)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:105)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$0(SecurityRestFilter.java:90)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$3(SecondaryAuthenticator.java:99)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:109)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:90)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$2(SecurityRestFilter.java:80)
        at org.elasticsearch.security@9.3.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:96)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:480)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestController.lambda$maybeAggregateAndDispatchRequest$4(RestController.java:404)
        at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.rest.RestContentAggregator$AggregationChunkHandler.onNext(RestContentAggregator.java:78)
        at org.elasticsearch.transport.netty4@9.3.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream.handleNettyContent(Netty4HttpRequestBodyStream.java:87)
        at org.elasticsearch.transport.netty4@9.3.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:146)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler@4.1.126.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
        at io.netty.handler@4.1.126.Final/io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:847)
        at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.transport@4.1.126.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.common@4.1.126.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
        at io.netty.common@4.1.126.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1474)
```

### PR DESCRIPTION
**Pull request by PeteGillinElastic**
This fixes a bug in the reindex API where it did not correctly validate the request parameters for authenticating with a remote source using basic auth. These require both username and password, and providing only one or the other is a user error.

1. Prior to this change, a reindex request which set `source.remote.username` but not `source.remote.password` would result in a response with HTTP status code 500 (Internal Server Error). This will now result in a response with HTTP status code 400 (Bad Request).

2. Prior to this change, a reindex request which set `source.remote.password` but not `source.remote.username` would normally result in a response with HTTP status code 401 (Unuauthorized). (If the remote cluster does not require authentication, or if an API key or some other form of authentication is provided, the request would succeed, with the password silently ignored.) This will now result in a response with HTTP status code 400 (Bad Request).

The new behaviour more correctly indicates to the user that there is an error in their request.

Closes #135925

### CODE REVIEW

**Review by seanzatzdev — APPROVED** [review]
lgtm, thanks

File: server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java [hunk 1]
```diff
@@ -116,6 +116,12 @@ public ActionRequestValidationException validate() {
             if (getSlices() == AbstractBulkByScrollRequest.AUTO_SLICES || getSlices() > 1) {
                 e = addValidationError("reindex from remote sources doesn't support slices > 1 but was [" + getSlices() + "]", e);
             }
+            if (getRemoteInfo().getUsername() != null && getRemoteInfo().getPassword() == null) {
```
Comment (szybia) [inline server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java:119]: nit: should we add yaml rest tests to make sure this returns a 400?

sounds nice for baking in the expected functionality for BwC too

**Review by szybia — APPROVED** [review]
lgtm!

left a nice-to-have, but i don't think it's that important so not blocking

File: server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java (hunk 1 above)
Comment (PeteGillinElastic) [reply server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java:119]: I'm inclined not to include an integration test when we have a good unit test. I think we have a high confidence that this method returning a validation exception will return a 400 from other tests. (To be honest, I'd prefer _not_ to spend time suppressing any failing mixed-cluster tests or whathaveyou...)

Do you feel strongly about this?

Comment (szybia) [reply server/src/main/java/org/elasticsearch/index/reindex/ReindexRequest.java:119]: nope, sgtm!
