### PR TITLE
Security: upgrade unboundid ldapsdk to 4.0.8

### LINKED ISSUE #33175: UnboundID SDK catches throwable and rewraps hiding a fatal error
As with some other libraries used in our codebase, the unboundid ldap sdk catches throwable in places and re-wraps what could be a potentially fatal error in an LDAPException:

https://github.com/pingidentity/ldapsdk/blob/0eac394a077323485b850a90e55f926bc035023f/src/com/unboundid/ldap/sdk/LDAPConnectionPool.java#L1623-L1675

We should raise an issue with the upstream library to ask that they stop catching throwable or at least rethrow properly. In the interim we should use `ExceptionsHelper#maybeError` with these exceptions so that we can properly die if an unrecoverable error is being hidden.

### PR DESCRIPTION
**Pull request by jaymode**
This commit upgrades the unboundid ldapsdk to version 4.0.8. The
primary driver for upgrading is a fix that prevents this library from
rewrapping Error instances that would normally bubble up to the
UncaughtExceptionHandler and terminate the JVM. Other notable changes
include some fixes related to connection handling in the library's
connection pool implementation.

Closes #33175

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jkakavas** [comment]
LGTM, there are a number of things changed in between 3.2.0 and 4.0.8 but I [went through them](https://github.com/pingidentity/ldapsdk/releases) and couldn't identify something that seems problematic or raises concerns.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackPlugin.java [hunk 1]
```diff
@@ -102,6 +102,7 @@
                 public Void run() {
                     try {
                         Class.forName("com.unboundid.util.Debug");
+                        Class.forName("com.unboundid.ldap.sdk.LDAPConnectionOptions");
```
Comment (jaymode) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackPlugin.java]: I opened https://github.com/pingidentity/ldapsdk/issues/51 with the upstream library for this. Ideally we'll be able to remove this hack in the future.
