### PR TITLE
ESQL: Fix case-insensitive test generation with Unicodes

### LINKED ISSUE #128705: [CI] RLikeTests testEvaluateInManyThreads {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8508 / ubuntu-2004-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/cdekxn4vntfai)
- [elasticsearch-pull-request #73158 / part-3-fips](https://gradle-enterprise.elastic.co/s/unrn27cw7ik34)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testEvaluateInManyThreads {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=731649474F4E8B64 -Dtests.locale=nb -Dtests.timezone=America/Santiago -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluateInManyThreads%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluateInManyThreads {TestCase=100 random code points matches self case insensitive with text} (1.4% fail rate in 140 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128706: [CI] RLikeTests testEvaluateInManyThreads {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8508 / ubuntu-2004-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/cdekxn4vntfai)
- [elasticsearch-pull-request #73158 / part-3-fips](https://gradle-enterprise.elastic.co/s/unrn27cw7ik34)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testEvaluateInManyThreads {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=731649474F4E8B64 -Dtests.locale=nb -Dtests.timezone=America/Santiago -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluateInManyThreads%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluateInManyThreads {TestCase=100 random code points matches self case insensitive with keyword} (1.4% fail rate in 140 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128710: [CI] RLikeTests testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8520 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/cii6ibvuyv5qa)
- [elasticsearch-intake #23400 / part3](https://gradle-enterprise.elastic.co/s/d6i73apanv6k2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=34B676B7B379FD9A -Dtests.locale=ms-SG -Dtests.timezone=Pacific/Rarotonga -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCrankyEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} (1.2% fail rate in 165 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128711: [CI] RLikeTests testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8520 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/cii6ibvuyv5qa)
- [elasticsearch-intake #23400 / part3](https://gradle-enterprise.elastic.co/s/d6i73apanv6k2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=34B676B7B379FD9A -Dtests.locale=ms-SG -Dtests.timezone=Pacific/Rarotonga -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCrankyEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} (1.2% fail rate in 165 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128712: [CI] WildcardLikeTests testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8520 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/cii6ibvuyv5qa)
- [elasticsearch-intake #23400 / part3](https://gradle-enterprise.elastic.co/s/d6i73apanv6k2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests.testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=34B676B7B379FD9A -Dtests.locale=se-NO -Dtests.timezone=America/Iqaluit -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCrankyEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} (1.2% fail rate in 165 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128713: [CI] WildcardLikeTests testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8520 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/cii6ibvuyv5qa)
- [elasticsearch-intake #23400 / part3](https://gradle-enterprise.elastic.co/s/d6i73apanv6k2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests.testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=34B676B7B379FD9A -Dtests.locale=se-NO -Dtests.timezone=America/Iqaluit -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCrankyEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testCrankyEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} (1.2% fail rate in 165 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128714: [CI] WildcardLikeTests testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-intake #23434 / part3](https://gradle-enterprise.elastic.co/s/6fcsfnoonpfla)
- [elasticsearch-periodic-platform-support #8496 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gk6crhexjjqay)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests.testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=D085B8A0A9CA9797 -Dtests.locale=ar-OM -Dtests.timezone=America/Juneau -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} (1.2% fail rate in 171 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128715: [CI] WildcardLikeTests testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-intake #23434 / part3](https://gradle-enterprise.elastic.co/s/6fcsfnoonpfla)
- [elasticsearch-periodic-platform-support #8496 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gk6crhexjjqay)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests.testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=D085B8A0A9CA9797 -Dtests.locale=ar-OM -Dtests.timezone=America/Juneau -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} (1.2% fail rate in 171 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128716: [CI] RLikeTests testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-intake #23434 / part3](https://gradle-enterprise.elastic.co/s/6fcsfnoonpfla)
- [elasticsearch-periodic-platform-support #8496 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gk6crhexjjqay)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword}" -Dtests.seed=D085B8A0A9CA9797 -Dtests.locale=xog-UG -Dtests.timezone=America/Rio_Branco -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword} (1.2% fail rate in 171 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128717: [CI] RLikeTests testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-intake #23434 / part3](https://gradle-enterprise.elastic.co/s/6fcsfnoonpfla)
- [elasticsearch-periodic-platform-support #8496 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gk6crhexjjqay)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with keyword}" -Dtests.seed=D085B8A0A9CA9797 -Dtests.locale=xog-UG -Dtests.timezone=America/Rio_Branco -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluateBlockWithNulls%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluateBlockWithNulls {TestCase=100 random code points matches self case insensitive with text} (1.2% fail rate in 171 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128789: [CI] WildcardLikeTests testEvaluate {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-periodic #8539 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/v2xhox37vwpz4)
- [elasticsearch-periodic #8497 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/vd6ayn7tzxqkg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests.testEvaluate {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=F9E38A02FF6B1B3C -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=bs-Latn -Dtests.timezone=Etc/Greenwich -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluate%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluate {TestCase=100 random code points matches self case insensitive with text} (0.6% fail rate in 348 executions)
- [main] 2 failures in step single-processor-node-tests (25.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128790: [CI] WildcardLikeTests testEvaluate {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-periodic #8539 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/v2xhox37vwpz4)
- [elasticsearch-periodic #8497 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/vd6ayn7tzxqkg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests.testEvaluate {TestCase=100 random code points matches self case insensitive with text}" -Dtests.seed=F9E38A02FF6B1B3C -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=bs-Latn -Dtests.timezone=Etc/Greenwich -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.WildcardLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluate%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluate {TestCase=100 random code points matches self case insensitive with keyword} (0.6% fail rate in 348 executions)
- [main] 2 failures in step single-processor-node-tests (25.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128791: [CI] RLikeTests testEvaluate {TestCase=100 random code points matches self case insensitive with keyword} failing
**Build Scans:**
- [elasticsearch-periodic #8539 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/v2xhox37vwpz4)
- [elasticsearch-periodic #8497 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/vd6ayn7tzxqkg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testEvaluate {TestCase=100 random code points matches self case insensitive with keyword}" -Dtests.seed=F9E38A02FF6B1B3C -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=ms -Dtests.timezone=America/El_Salvador -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluate%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20keyword%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluate {TestCase=100 random code points matches self case insensitive with keyword} (0.6% fail rate in 347 executions)
- [main] 2 failures in step single-processor-node-tests (25.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #128792: [CI] RLikeTests testEvaluate {TestCase=100 random code points matches self case insensitive with text} failing
**Build Scans:**
- [elasticsearch-periodic #8539 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/v2xhox37vwpz4)
- [elasticsearch-periodic #8497 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/vd6ayn7tzxqkg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests.testEvaluate {TestCase=100 random code points matches self case insensitive with keyword}" -Dtests.seed=F9E38A02FF6B1B3C -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=ms -Dtests.timezone=America/El_Salvador -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.string.RLikeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEvaluate%20%7BTestCase%3D100%20random%20code%20points%20matches%20self%20case%20insensitive%20with%20text%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testEvaluate {TestCase=100 random code points matches self case insensitive with text} (0.6% fail rate in 347 executions)
- [main] 2 failures in step single-processor-node-tests (25.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by bpintea**
This excludes from testing the strings containing Unicode chars that change length when changing case.

Closes #128705
Closes #128706
Closes #128710
Closes #128711
Closes #128712
Closes #128713
Closes #128714
Closes #128715
Closes #128716
Closes #128717
Closes #128789
Closes #128790
Closes #128791
Closes #128792

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/RLikeTests.java [hunk 1]
```diff
@@ -94,8 +94,15 @@ private static void casesForString(
             return new TextAndPattern(text, escapeString.apply(text));
         }, true);
         cases(cases, title + " matches self case insensitive", () -> {
-            String text = textSupplier.get();
-            return new TextAndPattern(randomCasing(text), escapeString.apply(text));
+            // RegExp doesn't support case-insensitive matching for Unicodes whose length changes when the case changes.
+            // Example: a case-insensitive ES regexp query for the pattern `weiß` won't match the value `WEISS` (but will match `WEIß`).
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/RLikeTests.java:98]: The example is super useful, thank you!

**Review by alex-spies — APPROVED** [review]

**Comment by bpintea** [comment]
Thanks Alex!
