### PR TITLE
Wrap ResponseException in AssertionError in ILM/CCR tests

### LINKED ISSUE #48461: [CI] org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot fails sporadically
## Example build failure

https://gradle-enterprise.elastic.co/s/s7pg5vmuahasi

## Reproduction line

Does **not** reproduce locally

```
./gradlew ':x-pack:plugin:ilm:qa:multi-cluster:follow-clusterRunner' --tests "org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot" \
  -Dtests.seed=15F5BEF4F0C61ABF \
  -Dtests.security.manager=true \
  -Dtests.locale=de-AT \
  -Dtests.timezone=PST \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
 1> [2019-10-24T03:33:26,008][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testCCRUnfollowDuringSnapshot] initializing REST clients against [http://[::1]:35835, http://127.0.0.1:33321]
13:33:58   1> [2019-10-24T03:33:30,691][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testCCRUnfollowDuringSnapshot] --> starting unfollow
13:33:58   1> [2019-10-24T03:33:32,465][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testCCRUnfollowDuringSnapshot] after test
13:33:58   2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-cluster:follow-clusterRunner' --tests "org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot" -Dtests.seed=15F5BEF4F0C61ABF -Dtests.security.manager=true -Dtests.locale=de-AT -Dtests.timezone=PST -Dcompiler.java=12 -Druntime.java=8
13:33:58   2> org.elasticsearch.client.ResponseException: method [HEAD], host [http://127.0.0.1:33321], URI [/unfollow-test-index/_doc/1], status line [HTTP/1.1 503 Service Unavailable]
13:33:58         at __randomizedtesting.SeedInfo.seed([15F5BEF4F0C61ABF:DFD8AE805887E1C]:0)
13:33:58         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
13:33:58         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
13:33:58         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:267)
13:33:58         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
13:33:58         at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.assertDocumentExists(CCRIndexLifecycleIT.java:753)
13:33:58         at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.lambda$testCCRUnfollowDuringSnapshot$3(CCRIndexLifecycleIT.java:166)
13:33:58         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:881)
13:33:58         at org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT.testCCRUnfollowDuringSnapshot(CCRIndexLifecycleIT.java:158)
13:33:58   1> [2019-10-24T03:33:32,611][INFO ][o.e.x.i.CCRIndexLifecycleIT] [testAliasReplicatedOnShrink] before test```

## Frequency

Happened [9 times so far](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%20%22org.elasticsearch.xpack.ilm.CCRIndexLifecycleIT%22%20AND%20test:%20%22testCCRUnfollowDuringSnapshot%22'),sort:!(time,desc))) in `master` and `7.x` since September 17th 2019

### PR DESCRIPTION
**Pull request by AthenaEryma**
When checking for the existence of a document in the ILM/CCR integration
tests, `assertDocumentExists` makes an HTTP request and checks the
response code. However, if the repsonse code is not successful, the call
will throw a `ResponseException`. `assertDocumentExists` is often called
inside an `assertBusy`, and replacing the `ResponseException` with an
`AssertionError` will allow the `assertBusy` to retry.

In particular, this fixes an issue with `testCCRUnfollowDuringSnapshot`
where the index in question may still be closed when the document is
requested.

This should fix https://github.com/elastic/elasticsearch/issues/48461

### CODE REVIEW

File: x-pack/plugin/ilm/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ilm/CCRIndexLifecycleIT.java [hunk 1]
```diff
@@ -746,10 +746,19 @@ private static Object getIndexSetting(RestClient client, String index, String se
...
-        assertThat(response.getStatusLine().getStatusCode(), equalTo(200));
+        Response response;
+        try {
+            response = client.performRequest(request);
+            if (response.getStatusLine().getStatusCode() != 200) {
+                logger.error(EntityUtils.toString(response.getEntity()));
+                fail("HTTP response code expected to be [200] but was [" + response.getStatusLine().getStatusCode() + "]");
+            }
+        } catch (ResponseException ex) {
+            logger.error(EntityUtils.toString(ex.getResponse().getEntity()));
```
Comment (dakrone) [inline x-pack/plugin/ilm/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ilm/CCRIndexLifecycleIT.java]: Maybe also include the stacktrace just in case?

```suggestion
            logger.error(EntityUtils.toString(ex.getResponse().getEntity()), ex);
```

**Review by dakrone — APPROVED** [review]
LGTM, left one comment

File: x-pack/plugin/ilm/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ilm/CCRIndexLifecycleIT.java (hunk 1 above)
Comment (gwbrown) [reply x-pack/plugin/ilm/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ilm/CCRIndexLifecycleIT.java]: Good thought! Done.
