### PR TITLE
[ILM] Fix downsample to skip already downsampled indices

### LINKED ISSUE #102249: Downsample action can attempt to downsample on the same interval and delete data
### Elasticsearch Version

8.10, 8.11, 8.12

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

When an ILM policy is created we don't allow the same donwsample action (same interval) to be configured in subsequent phases. 

This can be achieved though by updating the ILM policy by removing it from the hot phase and configuring it with the same `fixed_interval` in the warm phase. 

This can cause some in-flight indices that were downsampled in hot to now be downsampled in warm for the same interval. 
ILM will go through the warm/downsample action, skip the downsample operation (as the source index is donwsampled already) and delete the source index. This leads to data loss. 

The exact use case is “update the next phase to contain the downsample action from the previous phase, whilst the managed index is waiting to enter the next phase”.

### Steps to Reproduce

```
PUT _ilm/policy/ds-experiment-policy
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_age": "5m",
            "max_primary_shard_size": "10gb"
          },
          "downsample": {
            "fixed_interval": "1m"
          }
        }
      },
      "warm": {
        "min_age": "10m",
        "actions": {
        }
      }
    }
  }
}

POST my-ds-experiment/_rollover


PUT _component_template/ds-experiment-component
{
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "ds-experiment-policy"
        },
        "look_ahead_time": "4m",
        "codec": "best_compression"
      }
    },
    "mappings": {
      "runtime": {},
      "properties": {
        "@timestamp": {
          "format": "strict_date_optional_time_nanos",
          "type": "date_nanos"
        },
        "networkName": {
          "time_series_dimension": true,
          "type": "keyword"
        }
      }
    }
  }
}

PUT _index_template/my-ds-experiment-template
{
  "index_patterns": [
    "my-ds-experiment*"
  ],
  "template": {
    "settings": {
      "index": {
        "mode": "time_series",
        "routing_path": [
          "networkName"
        ]
      }
    }
  },
  "composed_of": [
    "ds-experiment-component"
  ],
  "data_stream": {
    "allow_custom_routing": false,
    "hidden": false
  }
}

PUT _data_stream/my-ds-experiment

PUT my-ds-experiment/_bulk
{ "create":{ } }
{ "@timestamp": "<replace with current timestamp>", "networkName":  "test1"}

// update policy while index has been already created
PUT _ilm/policy/ds-experiment-policy
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_age": "5m",
            "max_primary_shard_size": "10gb"
          }
        }
      },
      "warm": {
        "min_age": "10m",
        "actions": {
          "downsample": {
            "fixed_interval": "1m"
          }
        }
      }
    }
  }
}

// when index is moved to warm and downsampling happens, it will be deleted
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by andreidan**
This fixes a bug in ILM where if an ILM policy is updated such that the next phase (e.g. warm) contains the downsample action from the previous phase (e.g. hot), whilst the managed index is waiting to enter the next phase (e.g. warm), if the managed index was already downsampled in hot it would get deleted in the warm phase.

Fixes https://github.com/elastic/elasticsearch/issues/102249

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/DownsampleAction.java [hunk 1]
```diff
@@ -155,7 +160,30 @@ public List<Step> toSteps(Client client, String phase, StepKey nextStepKey) {
...
+                        // is another downsample action configured in the next phase, it'll be able to proceed successfully
+                        logger.warn(
+                            "index [{}] as part of policy [{}] cannot be downsampled at interval [{}] in phase [{}] because it has"
+                                + " the name of the target downsample index and is itself not a downsampled index. Skipping the downsample "
+                                + "action.",
+                            index.getName(),
+                            indexMetadata.getLifecyclePolicyName(),
+                            fixedInterval,
+                            phase
+                        );
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/DownsampleAction.java:181]: I don't understand, why do we only log this warning if the status is unknown, if the status is successful we still skip this downsample, but we don't log about it. Shouldn't we log in all cases then?

Comment (andreidan) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/DownsampleAction.java:181]: If the status is successful we don't log anything because this action (even as a no-op) has achieve its goal - the index is downsampled at the desired /configured interval. 

If the index has the shape of a downsample index, but it is not (i.e. status is UNKNOWN) we're skipping this action without achieving its goal - i.e. the data is not downsampled. We're logging the warning that we haven't executed downsampling.

Comment (dakrone) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/DownsampleAction.java:181]: That makes sense, thanks for the explanation

**Review by dakrone — APPROVED** [review]
LGTM, thanks for fixing this Andrei

**Review by martijnvg — COMMENTED** [review]
LGTM - Thanks Andrei for fixing this!
