### PR TITLE
Search - new flag: allow_partial_search_results

### LINKED ISSUE #27435: New query flag: allow_partial_results with default set to false.
There are various reasons today why a search could fail to produce all of the required results:

1) A failure to execute within a `timeout` associated with the search
2) Missing shards (ie a red index)
3) Failed shards - e.g. an error parsing the query

Until now elasticsearch has  attempted to to return partial results under these circumstances and report the partial status in flags in the search response e.g. `timed_out:true`. 
Sadly, today we expect most client applications will pay little attention to these flags and present partial results to clients with no indication that the results are incomplete.

This issue proposes we fix this by providing a new cluster level setting called `default_allow_partial_results` flag which is set to false and will throw an error to the client application in the event of any of the above 3 conditions. This can be overridden in individual search requests using a `allow_partial_results` flag.

### PR DESCRIPTION
**Pull request by markharwood**
Allow searches to fail if they are missing results eg from a timeout or a failure to execute on at least one shard. The allow_partial_search_results flag is a new parameter on search headers and a cluster-level setting controls default behaviour of searches where no preference is passed in the request. In future versions we will change the cluster default setting to throw errors instead of returning partial results.

Closes #27435

### CODE REVIEW

**Comment by markharwood** [comment]
jenkins test this

**Comment by markharwood** [comment]
jenkins test this

File: server/src/main/java/org/elasticsearch/action/search/SearchRequest.java [hunk 1]
```diff
@@ -305,6 +309,20 @@ public SearchRequest requestCache(Boolean requestCache) {
     public Boolean requestCache() {
         return this.requestCache;
     }
+    
+    /**
+     * Sets if this request should allow partial results. By default (not set, or null,
+     * will default to the cluster level setting if partial results are accepted or not).
+     */
+    public SearchRequest allowPartialSearchResults(Boolean allowPartialSearchResults) {
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/action/search/SearchRequest.java]: I think we should make this accept a `boolean`

File: server/src/main/java/org/elasticsearch/action/search/SearchRequestBuilder.java [hunk 2]
```diff
@@ -488,6 +488,16 @@ public SearchRequestBuilder setRequestCache(Boolean requestCache) {
         request.requestCache(requestCache);
         return this;
     }
+    
+
+    /**
+     * Sets if this request should allow partial results. By default (not set, or null,
+     * will default to the cluster level setting if partial results are accepted or not).
+     */
+    public SearchRequestBuilder setAllowPartialSearchResults(Boolean allowPartialSearchResults) {
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/action/search/SearchRequestBuilder.java]: I think we should make this a `boolean`

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 3]
```diff
@@ -133,6 +133,8 @@
     public static final TimeValue NO_TIMEOUT = timeValueMillis(-1);
     public static final Setting<TimeValue> DEFAULT_SEARCH_TIMEOUT_SETTING =
         Setting.timeSetting("search.default_search_timeout", NO_TIMEOUT, Property.Dynamic, Property.NodeScope);
+    public static final Setting<Boolean> DEFAULT_ALLOW_PARTIAL_SEARCH_RESULTS =
+            Setting.boolSetting("search.default_allow_partial_results", true, Property.Dynamic, Property.NodeScope);
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: The problem with this being node scope is that we could potentially have different values on different nodes (if the user sets this in `elasticsearch.yml`) which could cause unexpected behaviour. The same is actually already true for the default timeout above but I wonder if we should raise this in an issue?

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 4]
```diff
@@ -216,6 +225,14 @@ private void setDefaultSearchTimeout(TimeValue defaultSearchTimeout) {
         this.defaultSearchTimeout = defaultSearchTimeout;
     }
 
+    private void setDefaultAllowPartialSearchResults(Boolean defaultAllowPartialSearchResults) {
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: We should be able to make this a `boolean`? since there is always a value returned even if the user has not set it themselves?

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 3 above)
Comment (colings86) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: Also, see my comment against the documentation about whether we should make this default to false in this PR to make the backport straightforward and then change the default in a follow up

File: server/src/main/java/org/elasticsearch/search/internal/ShardSearchLocalRequest.java [hunk 5]
```diff
@@ -73,6 +73,7 @@
     private SearchSourceBuilder source;
     private Boolean requestCache;
     private long nowInMillis;
+    private Boolean allowPartialSearchResults;
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/internal/ShardSearchLocalRequest.java]: I wonder if we could resolve the value to true or false earlier (by consulting the cluster setting), for example could we maybe resolve this value in the TransportSearch action so the value is resolved on the coordinating node and consistent for all shard requests? Then this could be a `boolean`?

File: server/src/main/java/org/elasticsearch/search/query/QueryPhase.java [hunk 6]
```diff
@@ -265,6 +265,11 @@ static boolean execute(SearchContext searchContext,
                 searcher.search(query, queryCollector);
             } catch (TimeExceededException e) {
                 assert timeoutSet : "TimeExceededException thrown even though timeout wasn't set";
+                
+                if (!searchContext.request().allowPartialSearchResults()) {
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/query/QueryPhase.java]: nit: I think the code style is to avoid negating using `!X` and prefer `X == false` so its harder to miss the negation

**Review by colings86 — CHANGES_REQUESTED** [review]
@markharwood I left some comments, I have not looked at the bulk of the test changes in this round but will do in the next round of review

File: docs/reference/search/request-body.asciidoc [hunk 7]
```diff
@@ -86,6 +86,12 @@ And here is a sample response:
     aggregations and suggestions (no top hits returned).
     See <<shard-request-cache>>.
 
+`allow_partial_search_results`::
+
+    Set to `true` to allow partial results in the case of timeouts
+    or partial failures. Defaults to false, meaning any one failure
```
[the remark this answers is not in the document]
Comment (markharwood) [reply docs/reference/search/request-body.asciidoc]: This *is* a PR for 6.x which means the docs are wrong here - default is true meaning partial results are allowed. We will be forward-porting and changing the default to false.

File: server/src/main/java/org/elasticsearch/action/search/SearchRequest.java (hunk 1 above)
Comment (markharwood) [reply server/src/main/java/org/elasticsearch/action/search/SearchRequest.java]: Do we not need a Boolean to understand when an explicit choice hasn't been made by the client? It's when the value is null that we substitute for the cluster-level default.

Comment (markharwood) [reply server/src/main/java/org/elasticsearch/action/search/SearchRequest.java]: ah - or did you know this and just mean to make the setters take a bool and keep the getters returning Boolean?

Comment (colings86) [reply server/src/main/java/org/elasticsearch/action/search/SearchRequest.java]: yes I meant just the setters

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 3 above)
Comment (markharwood) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: Not sure there is a "Property.ClusterScope"? All cluster-level settings I see (e.g.  RecoverySettings.INDICES_RECOVERY_MAX_BYTES_PER_SEC_SETTING ) come defined with Property.NodeScope.

Comment (colings86) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: NO unfortunately there is no `Property.ClusterScope` so I think it makes it more important to have the setting resolved on the coordinating node so that all shards use the same value.

File: server/src/main/java/org/elasticsearch/search/internal/ShardSearchLocalRequest.java (hunk 5 above)
Comment (markharwood) [reply server/src/main/java/org/elasticsearch/search/internal/ShardSearchLocalRequest.java]: I have code in the TransportSearchAction.executeSearch that resolves the setting but not all tests transits this section of code.  Consequently I was seeing NPEs from some tests when an unresolved `null` SearchRequest Boolean was being assigned to a `boolean` as a deeper part of query execution. I changed the failing tests to explicitly set SearchRequest.allowPartialSearchResults but it felt like a hack addressing the symptoms rather than the cause. Perhaps there should be a more explicit query preparation stage where user-supplied requests are augmented by any cluster-level options e.g. SearchRequest.fillInMissingParamsWithDefaults(Settings).

**Comment by markharwood** [comment]
Ready for another review when you have time, @colings86

File: server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java [hunk 8]
```diff
@@ -146,7 +146,20 @@ public final void run() throws IOException {
...
+            assert request.allowPartialSearchResults() != null : "SearchRequest missing setting for allowPartialSearchResults";
+            if (request.allowPartialSearchResults() == false) {
+                // Fail-fast verification of all shards being available
+                for (int index = 0; index < shardsIts.size(); index++) {
+                    final SearchShardIterator shardRoutings = shardsIts.get(index);
+                    if (shardRoutings.size() == 0) {
+                        //Status red - shard is missing all copies and would produce partial results for an index search
+                        final String msg = "Search rejected due to missing shard "+ shardRoutings.shardId() +
+                                ". Consider using `allow_partial_search_results` setting to bypass this error.";
+                        throw new SearchPhaseExecutionException(getName(), msg, null, ShardSearchFailure.EMPTY_ARRAY);
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java]: I wonder if we should gather the missing shards and report all the shards that were unavailable rather than just the first?

**Review by colings86 — APPROVED** [review]
LGTM, I left a comment about reporting all the missing shards rather than just the first but happy for you to merge if you agree with that change
