### PR TITLE
[Transform] fix potential deadlock when using stop_at_checkpoint

### LINKED ISSUE #75846: [CI] TransformIT testStopWaitForCheckpoint failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/q6kyadnnxpljg/tests/:x-pack:plugin:transform:qa:multi-node-tests:javaRestTest/org.elasticsearch.xpack.transform.integration.TransformIT/testStopWaitForCheckpoint

**Reproduction line:**
`./gradlew ':x-pack:plugin:transform:qa:multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformIT.testStopWaitForCheckpoint" -Dtests.seed=545D076A9340F142 -Dtests.locale=id -Dtests.timezone=Australia/Victoria -Druntime.java=8`

**Applicable branches:**
7.13, 7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.transform.integration.TransformIT&tests.test=testStopWaitForCheckpoint

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=status_exception, reason=Failed to update transform task [transform-wait-for-checkpoint] state value should_stop_at_checkpoint from [true] to [true]]

  at __randomizedtesting.SeedInfo.seed([545D076A9340F142:29882B015FD41B74]:0)
  at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
  at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
  at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
  at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
  at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
  at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1606)
  at org.elasticsearch.client.TransformClient.stopTransform(TransformClient.java:308)
  at org.elasticsearch.xpack.transform.integration.TransformIntegTestCase.stopTransform(TransformIntegTestCase.java:145)
  at org.elasticsearch.xpack.transform.integration.TransformIT.testStopWaitForCheckpoint(TransformIT.java:302)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
When `_stop` gets called with `stop_at_checkpoint=true` and at the same time a transform got triggered internally or externally a race condition could lead to a deadlock of `5s`. The change fixes the situation where 2 lock objects could lock one another.

fixes #75846

### CODE REVIEW

**Review by benwtrent — COMMENTED** [review]
It might be good to bump test logging up to debug? I am wondering if this will really fix the issue.

The listener would have gotten an error when trying to wait for stop at checkpoint on a timeout. So, I am not sure increasing the timeout here fixes it. Did the logs in the issue show that the stop call failed?

It seems like race condition where the task is removed from cluster state before its previous state is fully

**Comment by hendrikmuhs** [comment]
> It might be good to bump test logging up to debug?

It is already on debug. 

> I am wondering if this will really fix the issue.

It does not fix the issue (this PR _relates_ only to the issue)

> 
> The listener would have gotten an error when trying to wait for stop at checkpoint on a timeout. So, I am not sure increasing the timeout here fixes it. Did the logs in the issue show that the stop call failed?

yes:
```
[2021-08-02T05:07:00,126][ERROR][o.e.x.t.t.TransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] Timed out (5s) waiting for transform state to be stored.
```

Of course, this could also be a race condition where the listener is not called. If the problem appears again with the `10s` timeout it is unlikely a timeout again, but a race.

> 
> It seems like race condition where the task is removed from cluster state before its previous state is fully

This PR does _not_ fix #75846, I am still investigating. I see a new task created before the old one has been completely removed. But this happens after the timeout or race condition above.

I hope to get more info when it happens again, the `cause` in stop was missing. Next time we should get the full stack trace.

**Review by benwtrent — APPROVED** [review]
Cool, didn't know the test was already on debug :)

++

**Comment by hendrikmuhs** [comment]
as for the race, I think here is one:

```
[2021-08-02T05:06:55,168][DEBUG][o.e.x.t.t.ClientTransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] Updated state document from [{seqNo=9,primaryTerm=1,index=.transform-internal-007}] to [{seqNo=10,primaryTerm=1,index=.transform-internal-007}]
[2021-08-02T05:07:00,126][ERROR][o.e.x.t.t.TransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] Timed out (5s) waiting for transform state to be stored.
```

It's suspicious that the time between the 2 log lines is roughly `5s`. I see a `synchronized` method and a countdown latch, this sounds like a deadly mixture. But I still don't see the issue, will add more debug logging.

**Comment by benwtrent** [comment]
@hendrikmuhs I am wondering if we will see that delay be `10s` after this PR :D. I think there is a thread dead-lock there. The fact that its SOO close to 5 seconds is very suspicious.

**Comment by hendrikmuhs** [comment]
Found it:

| Thread 1 (transport of stop)                   | Thread 2 (task/scheduler)                        |
|------------------------------------------------|--------------------------------------------------|
| **(s)** task->stop_at_checkpoint               |                                                  |
|                                                | **(s)** task->triggered() (**lock A**)           |
| **(s)** indexer->save_state (**lock B**)       |                                                  |
|                                                | **(s)** indexer->triggered (**wait for lock B**) |
| **(s)** task->shutdown() (**wait for lock A**) |                                                  |
|                                                |                                                  |
| _timeout_ (**unlock B**)                       |                                                  |
|                                                | **(s)** indexer->triggered (**lock B**)          |


The problem are 2 locks of the task and the indexer that can lock one another. 

Interesting is the `task->stop_at_checkpoint` which is `synchronous` but as it moves the execution of
the thread:

```
        // move the call to the generic thread pool, so we do not block the network thread
        getThreadPool().executor(ThreadPool.Names.GENERIC)
            .execute(() -> { getIndexer().setStopAtCheckpoint(shouldStopAtCheckpoint, shouldStopAtCheckpointListener); });
```

However, this unlocks the _task_ (lock A) and therefore allows the trigger originating from the scheduler to acquire the lock.

**Comment by hendrikmuhs** [comment]
I incorporated the new findings ans inspected all code paths where the indexer thread gets locked 1st and 2nd the task. With that change:

 - all calls either lock the task or the indexer
 - if it's required to lock both, it locks the task 1st and the indexer 2nd
 	- it might call task->indexer->task, however as locks are re-entrant, that's not a problem

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java [hunk 1]
```diff
@@ -244,24 +244,28 @@ protected void taskOperation(Request request, TransformTask transformTask, Actio
...
-            },
-                e -> listener.onFailure(
-                    new ElasticsearchStatusException(
-                        "Failed to update transform task [{}] state value should_stop_at_checkpoint from [{}] to [{}]",
-                        RestStatus.CONFLICT,
-                        transformTask.getTransformId(),
-                        transformTask.getState().shouldStopAtNextCheckpoint(),
-                        request.isWaitForCheckpoint()
+            // move the call to the generic thread pool, so we do not block the network thread
+            threadPool.executor(ThreadPool.Names.GENERIC).execute(() -> {
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java:248]: the thread switch is the only change, otherwise the code below is unchanged.

By moving the thread switch, the `transformTask.setShouldStopAtCheckpoint` call does not unlock the class lock of the task.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 2]
```diff
@@ -374,10 +272,6 @@ private void doSaveState(TransformState state, ActionListener<Void> listener) {
             seqNoPrimaryTermAndIndex,
             ActionListener.wrap(r -> {
                 updateSeqNoPrimaryTermAndIndex(seqNoPrimaryTermAndIndex, r);
-                // for auto stop shutdown the task
-                if (state.getTaskState().equals(TransformTaskState.STOPPED)) {
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:378]: this is now wrapped in `persistStateWithAutoStop`

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 3]
```diff
@@ -639,6 +643,119 @@ protected void onAbort() {
         context.shutdown();
     }
 
+    @Override
+    protected void doSaveState(IndexerState indexerState, TransformIndexerPosition position, Runnable next) {
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:647]: this method has been moved from ClientTransformIndexer without changes

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 4]
```diff
@@ -639,6 +643,119 @@ protected void onAbort() {
...
+            } catch (Exception onFailureException) {
+                String msg = LoggerMessageFormat.format("[{}] failed notifying saveState listeners, ignoring.", getJobId());
+                logger.warn(msg, onFailureException);
+            } finally {
+                next.run();
+            }
+        }));
+    }
+
+    private void persistStateWithAutoStop(TransformState state, ActionListener<Void> listener) {
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:751]: to fix the deadlock we don't initiate the shutdown in this place.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 5]
```diff
@@ -691,14 +807,37 @@ private synchronized boolean addSetStopAtCheckpointListener(
...
+            );
 
             // because save state is async we need to block the call until state is persisted, so that the job can not
             // be triggered (ensured by synchronized)
             CountDownLatch latch = new CountDownLatch(1);
-            logger.debug("[{}] persisiting stop at checkpoint", getJobId());
+            logger.debug("[{}] persisting stop at checkpoint", getJobId());
 
-            doSaveState(IndexerState.STARTED, getPosition(), () -> { latch.countDown(); });
+            persistState(newTransformState, ActionListener.wrap(() -> latch.countDown()));
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:840]: instead of calling `doSaveState` we call persist, which simplifies a lot, because `doSaveState` makes a lot of other checks that aren't necessary for this case.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 6]
```diff
@@ -709,6 +848,12 @@ private synchronized boolean addSetStopAtCheckpointListener(
                     )
                 );
             }
+
+            // stop the transform if the decision was to stop it above
+            if (newtaskState.equals(TransformTaskState.STOPPED)) {
+                context.shutdown();
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:854]: the shutdown now happens in the thread that locked the task and the indexer. shutdown locks the task once more.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java [hunk 7]
```diff
@@ -311,9 +313,12 @@ public synchronized void setShouldStopAtCheckpoint(
             return;
         }
 
-        // move the call to the generic thread pool, so we do not block the network thread
-        getThreadPool().executor(ThreadPool.Names.GENERIC)
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:315]: this is the origin of the deadlock, by moving to another thread we unlocked the task (this method is `synchronized`).

**Review by benwtrent — APPROVED** [review]
moving the persistence + stop into the top level action and not calling `doSaveState` will probably address the issue.

I would like to have this PR running in CI for a bit to catch anything else lingering for sure but I think it looks ok.
