### PR TITLE
Primary shard allocator observes limits in forcing allocation

### LINKED ISSUE #19446: Improve index-allocation retry limitation for primary shards
https://github.com/elastic/elasticsearch/pull/18467 was intended to limit how many times shard allocation was attempted before giving up, instead of constantly retrying. eg if an analyzer requires a local synonyms file, which is missing, then we should stop trying until the situation is resolved.

Unfortunately it doesn't work for unassigned primary shards because of the way allocation works today. For instance, a primary shard might be sitting on a disk which is over the high watermark, or it may have allocation filtering which prevents it from being allocated to the node where it already exists.  Today, we just go ahead and try to assign the primary regardless of the allocation deciders (which means that we also don't limit retries to 5).

Instead, we could add extra logic to the appropriate deciders to say "always return `YES` if the shard in question is a primary which already exists on this node".  The decision returned would be `YES`, but the explanation provided by the reroute or cluster allocation explain could include the reason this decider was ignored.

/cc @ywelsch @dakrone @s1monw 

Related to https://github.com/elastic/elasticsearch/issues/18321

### PR DESCRIPTION
**Pull request by abeyad**
Previously, during primary shards allocation of shards
with prior allocation IDs, if all nodes returned a
NO decision for allocation (e.g. the settings blocked
allocation on that node), we would chose one of those
nodes and force the primary shard to be allocated to it.

However, this meant that primary shard allocation
would not adhere to the decision of the MaxRetryAllocationDecider,
which would lead to attempting to allocate a shard
which has failed N number of times already (presumably
due to some configuration issue).

This commit solves this issue by introducing the
notion of force allocating a primary shard to a node
and each decider implementation must implement whether
this is allowed or not. In the case of MaxRetryAllocationDecider,
it just forwards the request to canAllocate.

Closes #19446

### CODE REVIEW

**Comment by abeyad** [comment]
@ywelsch FYI, initial pass on this, would welcome your feedback.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java [hunk 1]
```diff
@@ -98,4 +98,16 @@ public Decision canAllocate(RoutingNode node, RoutingAllocation allocation) {
...
+    /**
+     * Returns a {@link Decision} whether the given primary shard can be
+     * forcibly allocated on the given node. This method should only be called
+     * on nodes for which previous allocations exist for the primary shard.
+     * The default is {@link Decision#YES}.
+     */
+    public Decision canForceAllocatePrimary(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
+        assert shardRouting.primary() : "must not call canForceAllocatePrimary on a non-primary shard routing [" +
+                                            shardRouting.shardId() + "]";
+        return Decision.YES;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java]: this means that throttling is just ignored.
Assume scenario where FilterAllocationDecider says NO and ThrottlingAllocationDecider says THROTTLE. The implementation here would just forcefully allocate the shard, ignoring the throttling.

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java [hunk 2]
```diff
@@ -268,7 +290,9 @@ private boolean isEnoughVersionBasedAllocationsFound(IndexMetaData indexMetaData
     /**
      * Split the list of node shard states into groups yes/no/throttle based on allocation deciders
      */
-    private NodesToAllocate buildNodesToAllocate(ShardRouting shard, RoutingAllocation allocation, List<NodeGatewayStartedShards> nodeShardStates) {
+    private NodesToAllocate buildNodesToAllocate(RoutingAllocation allocation,
+                                                 List<NodeGatewayStartedShards> nodeShardStates,
+                                                 Function<RoutingNode, Decision> decisionFunction) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: we could alternatively just pass a boolean `forceAllocate` instead of the decisionFunction.

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java [hunk 3]
```diff
@@ -154,17 +154,39 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
                 logger.debug("[{}][{}]: allocating [{}] to [{}] on primary allocation", shard.index(), shard.id(), shard, nodeShardState.getNode());
                 changed = true;
                 unassignedIterator.initialize(nodeShardState.getNode().getId(), nodeShardState.allocationId(), ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE);
             } else if (nodesToAllocate.throttleNodeShards.isEmpty() == true && nodesToAllocate.noNodeShards.isEmpty() == false) {
-                NodeGatewayStartedShards nodeShardState = nodesToAllocate.noNodeShards.get(0);
-                logger.debug("[{}][{}]: forcing allocating [{}] to [{}] on primary allocation", shard.index(), shard.id(), shard, nodeShardState.getNode());
-                changed = true;
-                unassignedIterator.initialize(nodeShardState.getNode().getId(), nodeShardState.allocationId(), ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE);
+                // We have zero nodes for which a decision of yes or throttle was given, so
+                // instead of iterating forcing allocation of the shard to one of the "no" nodes,
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: once this PR is in, there is no point in commenting about what should NOT be done ;-) I would just write: "All nodes with shard copies returned NO decision, check if primary shard can be forced to one of the nodes".

**Comment by abeyad** [comment]
@ywelsch I pushed https://github.com/elastic/elasticsearch/pull/19811/commits/397e374e6f3cb01353fbea8b8380806085935aa9 to address your feedback

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java [hunk 4]
```diff
@@ -98,4 +98,21 @@ public Decision canAllocate(RoutingNode node, RoutingAllocation allocation) {
     public Decision canRebalance(RoutingAllocation allocation) {
         return Decision.ALWAYS;
     }
+
+    /**
+     * Returns a {@link Decision} whether the given primary shard can be
+     * forcibly allocated on the given node. This method should only be called
+     * on nodes for which previous allocations exist for the primary shard.
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java]: "This method should only be called on nodes for which previous allocations exist for the primary shard." should be more like "This method should only be called for unassigned primary shards where the node has a shard copy on disk."
Can you also assert `shardRouting.unassigned()` ?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java [hunk 5]
```diff
@@ -196,4 +196,29 @@ public Decision canRebalance(RoutingAllocation allocation) {
         }
         return ret;
     }
+
+    @Override
+    public Decision canForceAllocatePrimary(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
+        assert shardRouting.primary() : "must not call canForceAllocatePrimary on a non-primary shard routing [" +
+                                            shardRouting.shardId() + "]";
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java]: put shardRouting there, not only shardId (i.e. remove .shardId()).

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java]: similar as for `canAllocate`, I think we should keep the condition

```
if (allocation.shouldIgnoreShardForNode(shardRouting.shardId(), node.nodeId())) {
            return Decision.NO;
}
```

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java [hunk 6]
```diff
@@ -154,17 +154,34 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
-                logger.debug("[{}][{}]: forcing allocating [{}] to [{}] on primary allocation", shard.index(), shard.id(), shard, nodeShardState.getNode());
-                changed = true;
-                unassignedIterator.initialize(nodeShardState.getNode().getId(), nodeShardState.allocationId(), ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE);
+                // All nodes with shard copies returned NO decision, check if primary shard can be forced to one of the nodes
+                final NodesToAllocate nodesToForceAllocate = buildNodesToAllocate(
+                    allocation, nodeShardsResult.orderedAllocationCandidates, shard, true
+                );
+                if (nodesToForceAllocate.yesNodeShards.isEmpty() == false) {
+                    NodeGatewayStartedShards nodeShardState = nodesToForceAllocate.yesNodeShards.get(0);
+                    logger.debug("[{}][{}]: force allocating [{}] to [{}] on primary allocation",
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: I would change the message to read `[{}][{}]: allocating [{}] to [{}] on forced primary allocation`

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java [hunk 7]
```diff
@@ -154,17 +154,34 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
+                                 shard.index(), shard.id(), shard, nodeShardState.getNode());
+                    changed = true;
+                    unassignedIterator.initialize(nodeShardState.getNode().getId(), nodeShardState.allocationId(),
+                                                  ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE);
+                } else if (nodesToForceAllocate.throttleNodeShards.isEmpty() == false) {
+                    logger.debug("[{}][{}]: force throttling allocation [{}] to [{}] on primary allocation",
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: same as above, I would change message to `[{}][{}]: throttling allocation [{}] to [{}] on forced primary allocation`

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java [hunk 8]
```diff
@@ -154,17 +154,34 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
+                                 shard.index(), shard.id(), shard, nodesToForceAllocate.throttleNodeShards);
+                    changed |= unassignedIterator.removeAndIgnore(AllocationStatus.DECIDERS_THROTTLED);
+                } else {
+                    logger.debug("[{}][{}]: primary allocation denied [{}]", shard.index(), shard.id(), shard);
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: `[{}][{}]: forced primary allocation denied [{}]`

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/MaxRetryAllocationDeciderTests.java [hunk 9]
```diff
@@ -208,4 +213,45 @@ public void testFailedAllocation() {
         assertEquals(routingTable.index("idx").shard(0).shards().get(0).state(), INITIALIZING);
         assertEquals(routingTable.index("idx").shard(0).shards().get(0).unassignedInfo().getMessage(), "ZOOOMG");
     }
+
+    /**
+     * Tests that {@link MaxRetryAllocationDecider#canForceAllocatePrimary(ShardRouting, RoutingNode, RoutingAllocation)} adheres
+     * to the maximum retry count and returns a NO decision if the maximum number of retries is exceeded.
+     */
+    public void testCanForceAllocatePrimary() {
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/MaxRetryAllocationDeciderTests.java]: If you just want to check that `canForceAllocatePrimary` adheres to the maximum retry count, isn't it simpler to extend the existing test `testFailedAllocation` and 
do a simple check there? Such a check can be made by selecting the unassigned shard in the routing table and doing 
```
assertEquals(Decision.NO, new MaxRetryAllocationDecider(Settings.EMPTY).canForceAllocatePrimary(shardRouting, null, new RoutingAllocation(null, null, clusterState, null, 0, false)))
```

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java [hunk 10]
```diff
@@ -193,6 +199,52 @@ public void testFoundAllocationAndAllocating() {
...
+            new TestAllocateDecision(Decision.NO), new ForcePrimaryDecider(Decision.YES)
+        });
+        RoutingAllocation allocation = routingAllocationWithOnePrimaryNoReplicas(deciders, false, Version.CURRENT, "allocId1");
+        boolean changed = testAllocator.allocateUnassigned(allocation);
+        assertTrue(changed);
+        assertTrue(allocation.routingNodes().unassigned().ignored().isEmpty());
+        assertEquals(allocation.routingNodes().shardsWithState(ShardRoutingState.INITIALIZING).size(), 1);
+        assertEquals(allocation.routingNodes().shardsWithState(ShardRoutingState.INITIALIZING).get(0).currentNodeId(), node1.getId());
+
+        // tests that we do not force allocate the primary when at least one decider returns NO or THROTTLE for canForceAllocatePrimary
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: can we have different test methods here for the different parts that are test here?

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java [hunk 11]
```diff
@@ -193,6 +199,52 @@ public void testFoundAllocationAndAllocating() {
...
+        assertTrue(changed);
+        List<ShardRouting> ignored = allocation.routingNodes().unassigned().ignored();
+        assertEquals(ignored.size(), 1);
+        assertEquals(ignored.get(0).unassignedInfo().getLastAllocationStatus(),
+            forceDecisionNo ? AllocationStatus.DECIDERS_NO : AllocationStatus.DECIDERS_THROTTLED);
+        assertTrue(allocation.routingNodes().shardsWithState(ShardRoutingState.INITIALIZING).isEmpty());
+
+        // tests that we do not force allocate the primary when at least one decider's decision is to THROTTLE
+        deciders = new AllocationDeciders(Settings.EMPTY, new AllocationDecider[] {
+            new TestAllocateDecision(Decision.THROTTLE), new ForcePrimaryDecider(Decision.YES)
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: is this really testing the right thing? This test does not seem to call `canForceAllocatePrimary` as `TestAllocateDecision` returns THROTTLE and not NO for `canAllocate`.

**Comment by ywelsch** [comment]
@abeyad I've left some comments. Can you also check if there are tests that `FilterAllocationDecider` and other deciders are indeed allowing force-allocating primaries?

I would also like to see some docs where we can explain the implemented behavior. This could be useful to understand why primary shards are / are not allocated.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java (hunk 4 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java]: Done

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java (hunk 5 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java]: Done, good catch

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java (hunk 6 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: Done

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/MaxRetryAllocationDeciderTests.java (hunk 9 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/MaxRetryAllocationDeciderTests.java]: I removed this test and put the canForceAllocatePrimary checks in `testFailedAllocation`

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java (hunk 10 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: done

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java (hunk 11 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: Yes, because the `ForcePrimaryDecider` here returns `NO` for its canAllocate decision.  As we discussed, its still a bit confusing, so I explicitly added the canAllocate decision as another constructor argument to `ForcePrimaryDecider` and added comments to explain whats happening.

**Comment by abeyad** [comment]
@ywelsch I pushed https://github.com/elastic/elasticsearch/pull/19811/commits/9e47cd14abc3ff03bac4c32616a6b2b2e502f8ce, which addresses your review comments, and adds `PrimaryAllocationIT` test that covers filter allocation decider force allocating primaries.

As we discussed, I augmented the `PrimaryShardAllocator` with some more javadocs to explain the behavior.  Docs explaining shard allocation in general (including primary shard allocation) will come in a separate PR.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java [hunk 12]
```diff
@@ -98,4 +98,15 @@ public Decision canAllocate(RoutingNode node, RoutingAllocation allocation) {
...
+
+    /**
+     * Returns a {@link Decision} whether the given primary shard can be
+     * forcibly allocated on the given node. This method should only be called
+     * for unassigned primary shards where the node has a shard copy on disk.
+     */
+    public Decision canForceAllocatePrimary(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
+        assert shardRouting.primary() : "must not call canForceAllocatePrimary on a non-primary shard " + shardRouting;
+        assert shardRouting.unassigned() : "must not call canForceAllocatePrimary on an assigned shard " + shardRouting;
+        return Decision.YES; // by default, a decider will allow force allocation of the primary
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java]: I think I prefer the way it was before with the default being 

```
decision = canAllocate(...)
if (decision == Decision.NO) {
    decision = Decision.single(Type.YES, "force override of " + decision.label, ...)
}
```

This keeps the override logic out of `AllocationDeciders`.

File: test/framework/src/main/java/org/elasticsearch/test/ESAllocationTestCase.java [hunk 13]
```diff
@@ -196,6 +196,32 @@ public Decision canAllocate(RoutingNode node, RoutingAllocation allocation) {
         }
     }
 
+    /**
+     * A decider class that allows controlling the decision on both allocating (AllocationDecider#canAllocate)
+     * and force allocating (AllocationDecider#canForceAllocatePrimary) a primary shard.
+     */
+    protected static class ForcePrimaryDecider extends TestAllocateDecision {
```
Comment (ywelsch) [inline test/framework/src/main/java/org/elasticsearch/test/ESAllocationTestCase.java]: Instead of having this class, it might be more readable to just have two methods in `PrimaryShardAllocatorTests`:

```
AllocationDecider getNoDeciderThatThrottlesForceAllocate() {
   return new TestAllocateDecision(Decision.NO) {
       @Override
       public Decision canForceAllocatePrimary(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
            return Decision.THROTTLE;
       }
   };
}

AllocationDecider getNoDeciderThatAllowsForceAllocate() {
     ... return YES;

}
```

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java (hunk 12 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java]: My concern with your suggestion (which was the initial approach) is that for any decider that overrides `canForceAllocatePrimary`, it is easy for it to forget to take into account the decision of `canAllocate`.  That's why I figured it would be better to put the invocation of `canAllocate` in `AllocationDeciders`, then if the decision is `NO` (as opposed to throttle, for example), then call the deciders `canForceAllocatePrimary` implementation.  The only downside to this that I can think of is that its rigid in that no `canForceAllocatePrimary` method would be able to override a non-NO `canAllocate` decision - but I don't see any reason why we would want that?

**Comment by abeyad** [comment]
@ywelsch I pushed https://github.com/elastic/elasticsearch/pull/19811/commits/9446267af3b1b938ebbfb0ff39916c9d9186009e to remove `ForcePrimaryDecider` in favor of anonymous class creation that extends `TestAllocateDecision`

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java (hunk 12 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecider.java]: I pushed 5c25b15c7a33ffa6b9e0965f30694f3f13bcd82a to address this

**Comment by abeyad** [comment]
@elasticmachine retest this please

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/MaxRetryAllocationDecider.java [hunk 14]
```diff
@@ -80,4 +80,12 @@ public Decision canAllocate(ShardRouting shardRouting, RoutingAllocation allocat
     public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
         return canAllocate(shardRouting, allocation);
     }
+
+    @Override
+    public Decision canForceAllocatePrimary(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
+        assert shardRouting.primary() : "must not call canForceAllocatePrimary on a non-primary shard [" + shardRouting.shardId() + "]";
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/MaxRetryAllocationDecider.java]: print `shardRouting`, not only `shardRouting.shardId()`.

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java [hunk 15]
```diff
@@ -154,17 +166,37 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
                 changed = true;
                 unassignedIterator.initialize(nodeShardState.getNode().getId(), nodeShardState.allocationId(), ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE);
             } else if (nodesToAllocate.throttleNodeShards.isEmpty() == true && nodesToAllocate.noNodeShards.isEmpty() == false) {
-                NodeGatewayStartedShards nodeShardState = nodesToAllocate.noNodeShards.get(0);
-                logger.debug("[{}][{}]: forcing allocating [{}] to [{}] on primary allocation", shard.index(), shard.id(), shard, nodeShardState.getNode());
-                changed = true;
-                unassignedIterator.initialize(nodeShardState.getNode().getId(), nodeShardState.allocationId(), ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE);
+                // The deciders returned a NO decision for all nodes with shard copies, so we check if primary shard
+                // can be force-allocated to one of the nodes, despite getting a NO decision for allocation. The decision
+                // to force allocate a primary to a node comes from AllocationDeciders#canForceAllocatePrimary, which calls
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: this is not strictly true anymore with the last change? update docs here.

File: core/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java [hunk 16]
```diff
@@ -219,4 +220,33 @@ public void testNotWaitForQuorumCopies() throws Exception {
...
+     * a NO decision to allocate.
+     */
+    public void testForceAllocatePrimaryOnNoDecision() throws Exception {
+        logger.info("--> starting 1 node");
+        final String node = internalCluster().startNodeAsync().get();
+        logger.info("--> creating index with 1 primary and 0 replicas");
+        final String indexName = "test-idx";
+        assertAcked(client().admin().indices()
+                        .prepareCreate(indexName)
+                        .setWaitForActiveShards(ActiveShardCount.ALL)
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: we get this for free with 0 replicas, no need to add this.

File: core/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java [hunk 17]
```diff
@@ -219,4 +220,33 @@ public void testNotWaitForQuorumCopies() throws Exception {
...
+        logger.info("--> update the settings to prevent allocation to the data node");
+        assertTrue(client().admin().indices().prepareUpdateSettings(indexName)
+                       .setSettings(Settings.builder().put(IndexMetaData.INDEX_ROUTING_EXCLUDE_GROUP_SETTING.getKey() + "_name", node))
+                       .get()
+                       .isAcknowledged());
+        logger.info("--> full cluster restart");
+        internalCluster().fullRestart();
+        logger.info("--> checking that the primary shard is force allocated to the data node despite being blocked by the exclude filter");
+        ensureYellow(indexName);
+        assertEquals(1, internalCluster().clusterService(internalCluster().getMasterName())
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: why explictly use master node? just make a proper client request (`client.admin().cluster().prepareState().get()...`)

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java [hunk 18]
```diff
@@ -193,6 +198,74 @@ public void testFoundAllocationAndAllocating() {
...
+     * Tests that when the nodes with prior copies of the given shard all return a decision of NO, but
+     * {@link AllocationDecider#canForceAllocatePrimary(ShardRouting, RoutingNode, RoutingAllocation)}
+     * returns a YES decision for at least one of those NO nodes, then we force allocate to one of them
+     */
+    public void testForceAllocatePrimary() {
+        testAllocator.addData(node1, ShardStateMetaData.NO_VERSION, "allocId1", randomBoolean());
+        AllocationDeciders deciders = new AllocationDeciders(Settings.EMPTY, new AllocationDecider[] {
+            // since both deciders here return a NO decision for allocating a shard,
+            // the allocator will see if it can force assign the primary, where the decision will be YES
+            new TestAllocateDecision(Decision.NO), getNoDeciderThatAllowsForceAllocate()
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: does it make sense to replace `new TestAllocateDecision(Decision.NO)` by `new TestAllocateDecision(randomBoolean() ? Decision.YES : Decision.NO)`.

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java [hunk 19]
```diff
@@ -193,6 +198,74 @@ public void testFoundAllocationAndAllocating() {
...
+    }
+
+    /**
+     * Tests that when the nodes with prior copies of the given shard return a THROTTLE decision,
+     * then we do not force allocate to that node but instead throttle.
+     */
+    public void testDontForceAllocateOnThrottleDecision() {
+        testAllocator.addData(node1, ShardStateMetaData.NO_VERSION, "allocId1", randomBoolean());
+        AllocationDeciders deciders = new AllocationDeciders(Settings.EMPTY, new AllocationDecider[] {
+            // since both deciders here return a NO decision for allocating a shard,
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: this comment is not true here.

File: core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java [hunk 20]
```diff
@@ -573,6 +647,36 @@ private void assertClusterHealthStatus(RoutingAllocation allocation, ClusterHeal
...
+        return new TestAllocateDecision(Decision.NO) {
+            @Override
+            public Decision canForceAllocatePrimary(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
+                assert shardRouting.primary() : "cannot force allocate a non-primary shard " + shardRouting;
+                return Decision.THROTTLE;
+            }
+        };
+    }
+
+    private AllocationDecider getNoDeciderThatDeniesForceAllocate() {
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java]: we can have three methods here, but all of them could just share their code by calling a common method `getNoDeciderWithForceAllocate(Decision)`

**Comment by ywelsch** [comment]
@abeyad Left minor comments about docs/tests, change looks good o.w.

File: core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java (hunk 15 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/gateway/PrimaryShardAllocator.java]: I think the comment is a bit confusing in general so I'll remove it since the behavior is clear from the javadocs for `canForceAllocatePrimary`

**Comment by abeyad** [comment]
@ywelsch I pushed 5b536be443abb2aaf5a389cbd3066c6811c685ca

**Comment by ywelsch** [comment]
LGTM. Thanks @abeyad!

**Comment by abeyad** [comment]
Thanks for the review @ywelsch !
