### PR TITLE
Reset failed allocation counter before executing routing commands

### LINKED ISSUE #39546: Reset max_retries counter before executing routing commands
We respect allocation deciders, including the `MaxRetryAllocationDecider`, when executing reroute commands. If you specify `?retry_failed=true` then the retry counter is reset, but not until after trying to execute the reroute commands. This means that if an allocation has repeatedly failed, but you want to take control and assign a shard to a particular node to work around the repeated failures, you cannot just do this:

```
POST /_cluster/reroute?retry_failed=true
{
  "commands": [
    {
      "allocate_replica": {
        "index": "blahblah",
        "shard": 2,
        "node": "node-4"
      }
    }
  ]
}
```

~The command is rejected by the `MaxRetryAllocationDecider`, then the retry counter is reset, then Elasticsearch tries in vain to allocate the shard to a node of its choosing, hitting the retry limit again.~ Correction: The command is rejected by the `MaxRetryAllocationDecider` which stops the whole reroute process.

The workaround today is:

- disable allocation
- reset the retry counter with a bare `POST /_cluster/reroute?retry_failed=true`
- execute the desired reroute command with another call to `POST /_cluster/reroute`
- re-enable allocation

I think we should reset the retry counter before executing the reroute commands here:

https://github.com/elastic/elasticsearch/blob/4ca241b78a80f92d5443caf6c943243b166515f5/server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java#L338-L348

cf https://discuss.elastic.co/t/shard-allocation-says-max-retry-but-fails-to-allocate-on-retry-failed-true/170396

### PR DESCRIPTION
**Pull request by vigyasharma**
Reset failed allocation counter before executing allocation commands.

Fixes #39546

### CODE REVIEW

**Comment by vigyasharma** [comment]
@DaveCTurner Apologies for multiple pings, please review changes on this PR instead of #41050

**Comment by DaveCTurner** [comment]
I pushed a commit to fix a couple of formatting nits. @elasticmachine ok to test

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+        MetaData metaData = MetaData.builder().put(IndexMetaData.builder(INDEX_NAME)
+            .settings(settings(Version.CURRENT)).numberOfShards(1).numberOfReplicas(1)).build();
+        RoutingTable routingTable = RoutingTable.builder().addAsNew(metaData.index(INDEX_NAME)).build();
+        clusterState = ClusterState.builder(ClusterName.DEFAULT).metaData(metaData).routingTable(routingTable)
+            .nodes(DiscoveryNodes.builder().add(newNode("node1")).add(newNode("node2"))).build();
+        strategy = createAllocationService(Settings.EMPTY);
+    }
+
+    private ShardRouting getPrimary() {
+        for (ShardRouting shard : clusterState.getRoutingTable().allShards()) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java]: Suggest:

```suggestion
        return clusterState.getRoutingTable().index(INDEX_NAME).shard(0).primaryShard();
```

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+            if (shard.getIndexName().equals(INDEX_NAME) && shard.primary()) {
+                return shard;
+            }
+        }
+        throw new IllegalArgumentException("No primary found for index: " + INDEX_NAME);
+    }
+
+    private ShardRouting getReplica() {
+        for (ShardRouting shard : clusterState.getRoutingTable().allShards()) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java]: Suggest:

```suggestion
        return clusterState.getRoutingTable().index(INDEX_NAME).shard(0).replicaShards().get(0);
```

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+    public void testRetryFailedResetForAllocationCommands() {
+        final int retries = MaxRetryAllocationDecider.SETTING_ALLOCATION_MAX_RETRY.get(Settings.EMPTY);
+        clusterState = strategy.reroute(clusterState, "initial allocation");
+        clusterState = strategy.applyStartedShards(clusterState, Collections.singletonList(getPrimary()));
+
+        // Exhaust all replica allocation attempts with shard failures
+        for (int i = 0; i < retries; i++) {
+            List<FailedShard> failedShards = Collections.singletonList(
+                new FailedShard(getReplica(), "failing-shard::attempt-" + i,
+                    new UnsupportedOperationException(), randomBoolean()));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java]: Suggest this so that the exception that's logged by the test is obviously expected:

```suggestion
                    new ElasticsearchException("simulated"), randomBoolean()));
```

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+            clusterState = strategy.applyFailedShards(clusterState, failedShards);
+            clusterState = strategy.reroute(clusterState, "allocation retry attempt-" + i);
+        }
+
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/RetryFailedAllocationTests.java]: Suggest asserting that we have tripped the max-retries limit here:

```suggestion
        assertThat("replica should not be assigned", getReplica().state(), equalTo(ShardRoutingState.UNASSIGNED));
        assertThat("reroute should be a no-op", strategy.reroute(clusterState, "test"), sameInstance(clusterState));

```

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Implementation LGTM, I suggested some small changes to the test.

**Comment by vigyasharma** [comment]
Thanks for reviewing @DaveCTurner. Made suggested changes.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/2
