### PR TITLE
Adjust translog operation assertions for synthetic source

### LINKED ISSUE #119191: [CI] SmokeTestMultiNodeClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic #5599 / release-tests](https://gradle-enterprise.elastic.co/s/v4elhy6ncdpzk)
- [elasticsearch-pull-request #48177 / part-1](https://gradle-enterprise.elastic.co/s/lyosxi4aps2ro)
- [elasticsearch-periodic-platform-support #5488 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/hwykli6uosa4o)

**Reproduction Line:**
```
./gradlew ":qa:smoke-test-multinode:yamlRestTest" --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=search/310_match_bool_prefix/operator}" -Dtests.seed=D46E9853C786049F -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=az -Dtests.timezone=ECT -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: Failure at [search/310_match_bool_prefix:6]: Connection refused
```

**Issue Reasons:**
- [main] 3 failures in class org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT (0.8% fail rate in 382 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
When synthetic sources are used in peer recoveries, the translog operations via peer recoveries may differ from those created through replication. This change relaxes the translog operation assertion to account for synthetic source, allowing these operations to be considered equivalent.

Closes #119191

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+
+import java.io.IOException;
+import java.util.Objects;
+
+/**
+ *
+ * A utility class to assert that translog operations with the same sequence number
+ * in the same generation are either identical or equivalent when synthetic sources are used.
+ */
+public abstract class TranslogOperationAsserter {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:25]: Should there be a dedicated unit test class for `TranslogOperationAsserter`?

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+                return false;
+            }
+        };
+    }
+
+    static Translog.Index synthesizeSource(EngineConfig engineConfig, Translog.Index op) throws IOException {
+        final ShardId shardId = engineConfig.getShardId();
+        MappingLookup mappingLookup = engineConfig.getMapperService().mappingLookup();
+        DocumentParser documentParser = engineConfig.getMapperService().documentParser();
+        try (var reader = new TranslogDirectoryReader(shardId, op, mappingLookup, documentParser, engineConfig, () -> {})) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:53]: nice, I was wondering whether opening a translog as a Lucene index was possible. This is direction I was thinking as well 👍

**Review by martijnvg — APPROVED** [review]
LGTM from my side. I think distributed team should review this as well.

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+                )
+            ) {
+                final Translog.Operation normalized = snapshot.next();
+                assert normalized != null : "expected one operation; got zero";
+                return (Translog.Index) normalized;
+            }
+        }
+    }
+
+    boolean sameIndexOperation(Translog.Index o1, Translog.Index o2) throws IOException {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:82]: I wonder if we should move this to `Translog.Index` to increase the chances of maintaining it in case a field is ever added?

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+        // TODO: We haven't had timestamp for Index operations in Lucene yet, we need to loosen this check without timestamp.
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:83]: This todo confuses me a little. I notice the auto-gen-timestamp is not included, I assume because we do not hold it in lucene, which is fair. But then what is the todo about?

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+        long generation,
+        Translog.Operation newOp,
+        Translog.Operation prvOp,
+        Exception prevFailure
+    ) throws IOException {
+        final boolean sameOp;
+        if (newOp instanceof final Translog.Index o2 && prvOp instanceof final Translog.Index o1) {
+            sameOp = sameIndexOperation(o1, o2);
+        } else if (newOp instanceof final Translog.Delete o1 && prvOp instanceof final Translog.Delete o2) {
+            sameOp = Objects.equals(o1.id(), o2.id())
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:103]: Can we use `o1.equals(o2)` instead here? At least I did not spot the difference.

Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:103]: (I see now that it is copied, but still makes sense I think).

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 2 above)
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:53]: It is ok, but as an optional nit, I found `engineConfig` quite a big pass of information to the reader - since it only needs the analyzer and code IIUC. It confused me for a short while, thinking it needed more access. I'd prefer to pass the two specific params, but consider this optional given that it piggy-backs on existing work and the extension here is for assertions only.

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:25]: ++, seems complicated enough to have some minimal validation.

File: server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 6]
```diff
@@ -276,38 +281,7 @@ private synchronized boolean assertNoSeqNumberConflict(long seqNo, BytesReferenc
...
-                            + "], with different data. "
-                            + "prvOp ["
-                            + prvOp
-                            + "], newOp ["
-                            + newOp
-                            + "]",
-                        previous.v2()
-                    );
-                }
+                assert operationAsserter.assertSameOperations(seqNo, generation, newOp, prvOp, previous.v2());
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java:284]: I wonder if we should change `assertSameOperations` to just return a boolean and then add the message here instead, avoiding to pass a few params to `assertSameOperations`? Something like:

```suggestion
                assert operationAsserter.sameOperations(newOp, prvOp) : new AssertionError(
                        "seqNo ["
                            + seqNo
                            + "] was processed twice in generation ["
                            + generation
                            + "], with different data. "
                            + "prvOp ["
                            + prvOp
                            + "], newOp ["
                            + newOp
                            + "]",
                        previous.v2()
                    );
```

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java:27]: ++ I added tests and used this new asserter in EngineTestCase: https://github.com/elastic/elasticsearch/pull/119330/commits/e923fe61c8b0b8d4dc6c7bdd6f64b92449c41ea5

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 3 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java]: Yes, I added `equalsWithoutAutoGeneratedTimestamp` to Translog.Index

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 4 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java]: I copied this TODO. I have removed it.

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 5 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java]: Fixed.

File: server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java (hunk 6 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: ++ see https://github.com/elastic/elasticsearch/pull/119330/commits/cc259d21ce9d53cae70168bb92803e54529b8a6c

File: server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogOperationAsserter.java]: I've kept the EngineConfig parameter unchanged because we also need MapperService and Codec.

**Comment by dnhatn** [comment]
@martijnvg @henningandersen Thanks for reviewing!
