### PR TITLE
[Transform] add support for top metrics

### LINKED ISSUE #52236: Transform support for top_metrics
#51155 is adding a `top_metrics` aggregation which is similar to `top_hits` but trades flexibility for memory consumption and a little speed. This tracks transform's usage of it, as requested by [this](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationsTests.java#L94-L101) exception message.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
add support for the stats and top metrics aggregation in transform. With this change it became easier
to add more multi value aggregations to transform

Limitations: 
 - only the 1st element of top_metrics gets consumed by transform[*].
 - all values of stats will be mapped to `double` if mapping deduction is used, including `count`, `sum`, `min`, `max`

fixes #52236
relates #51925

Docs preview: https://elasticsearch_71850.docs-preview.app.elstc.co/diff

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java [hunk 1]
```diff
@@ -75,11 +75,11 @@ protected MultiValue(StreamInput in) throws IOException {
...
         }
 
+        @Override
         public abstract double value(String name);
 
-        public String valueAsString(String name) {
-            return format.format(value(name)).toString();
-        }
+        @Override
+        public abstract String valueAsString(String name);
```
Comment (hendrikmuhs) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java:82]: this change wasn't strictly necessary, however it seems cleaner to me to _force_ every implementation to think about it.

The alternative is to keep the old version, but only overwrite it in TopMetrics

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/NumericMetricsAggregation.java [hunk 2]
```diff
@@ -40,5 +40,12 @@
          */
         double value(String name);
 
+        /**
+         * Return the result of 1 value by name as string
+         *
+         * @param name of the value
+         * @return the value as string
+         */
+        String valueAsString(String name);
```
Comment (hendrikmuhs) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/NumericMetricsAggregation.java:49]: `InternalNumericsMetricAggregation.MultiValue` already had this method, so all I needed is exposing it, however note that SingleValue calls it `getValueAsString`.

Let me know, if I should rename to `getValueAsString` to have a more consistent naming.

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java:82]: Could you link me to what that'd look like? Maybe make the change on top of this PR and push it to another branch or something? Just somewhere where I can see it. I think maybe we should stop `top_metrics` from extending `InternalNumericMetricsAggregation.MultiValue`. Like you said somewhere else - it ain't really numeric any more.

File: x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/InternalTopMetrics.java [hunk 3]
```diff
@@ -169,9 +169,31 @@ public double value(String name) {
...
+        if (index < 0) {
+            throw new IllegalArgumentException("unknown metric [" + name + "]");
+        }
+        if (topMetrics.isEmpty()) {
+            return "";
+        }
+        assert topMetrics.size() == 1 : "property paths should only resolve against top metrics with size == 1.";
+
+        MetricValue value = topMetrics.get(0).metricValues.get(index);
+        return value.getValue().format(value.getFormat());
```
Comment (hendrikmuhs) [inline x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/InternalTopMetrics.java:196]: ^ @nik9000 This is what I need to override. Of course this will work _without_ the change in `InternalNumericMetricsAggregation.java` (the former default would take the double and call to string on it)

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java (hunk 1 above)
Comment (hendrikmuhs) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalNumericMetricsAggregation.java:82]: I marked it in the PR, fixing `top_metrics` to not extend `InternalNumericMetricsAggregation.MultiValue` would be the alternative of course. However sounds like a larger re-factoring to me. If that's what you are aiming for, I suggest to revert the above and go with the smaller change for now.

**Comment by hendrikmuhs** [comment]
I rebased this PR after #71738 got merged. 

> I think maybe we should stop top_metrics from extending InternalNumericMetricsAggregation.MultiValue. Like you said somewhere else - it ain't really numeric any more.

I created a new branch to explore this idea, see #71903. It is a nice cleanup and would make a lot of changes in this PR unnecessary.

**Comment by hendrikmuhs** [comment]
After re-factorings of aggregations have been moved into another PR (https://github.com/elastic/elasticsearch/pull/71903, merged) this PR only touches transform code.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java [hunk 4]
```diff
@@ -185,15 +208,43 @@ public static String resolveTargetMapping(String aggregationType, String sourceT
...
+        // does the agg specify output field names
+        Optional<Set<String>> outputFieldNames = agg.getOutputFieldNames();
+        if (outputFieldNames.isPresent()) {
+            return new Tuple<>(
+                outputFieldNames.get()
+                    .stream()
+                    .collect(
+                        Collectors.toMap(
+                            outputField -> agg.getName() + "." + outputField,
+                            outputField -> { return outputField; },
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java:227]:
```suggestion
                            Function.identity(),
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java [hunk 5]
```diff
@@ -259,6 +269,44 @@ public Object value(Aggregation agg, Map<String, String> fieldTypeMap, String lo
...
+        }
+    }
+
+    static class NumericMultiValueAggExtractor implements AggValueExtractor {
+        @Override
+        public Object value(Aggregation agg, Map<String, String> fieldTypeMap, String lookupFieldPrefix) {
+            MultiValue aggregation = (MultiValue) agg;
+            Map<String, Object> extracted = new HashMap<>();
+
+            String fieldLookupPrefix = (lookupFieldPrefix.isEmpty() ? agg.getName() : lookupFieldPrefix + "." + agg.getName()) + ".";
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java:296]: It seems weird that the `false` path adds a `"."` at the end but the `true` path doesn't. Sees like if prefix fields are empty we would end up with `statsvalue` vs `stats.value`

**Review by benwtrent — COMMENTED** [review]
Overall, great change. Its fantastic that we can reuse this dot delimited formatting for aggs. Shows that we have a nice framework design.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java (hunk 5 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java:296]: `"."` is always added, it is `(e ? t : f) + "."` - hard to read, I know.

Good point actually, I think only top_metrics at the root (not counting the composite agg) are tested, I will add another test where top_metric is a sub-agg of e.g. a filter.

Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java:296]: ah, sneaky `(..)` :D

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java [hunk 6]
```diff
@@ -185,15 +208,43 @@ public static String resolveTargetMapping(String aggregationType, String sourceT
...
                 Arrays.stream(percentilesAgg.percentiles())
                     .mapToObj(OutputFieldNameConverter::fromDouble)
-                    .collect(Collectors.toMap(p -> agg.getName() + "." + p, p -> { return agg.getType(); }, (p1, p2) -> p1))
+                    .collect(
+                        Collectors.toMap(p -> percentilesAgg.getName() + "." + p, p -> { return percentilesAgg.getType(); }, (p1, p2) -> p1)
+                    )
+            );
+        }
+
+        // Note: order is important
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java:217]: Could you clarify which "order" do you have in mind, i.e. order of *what* is important?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java [hunk 7]
```diff
@@ -185,15 +208,43 @@ public static String resolveTargetMapping(String aggregationType, String sourceT
...
+                            outputField -> { return outputField; },
+                            (v1, v2) -> v1
+                        )
+                    ),
+                outputFieldNames.get()
+                    .stream()
+                    .collect(
+                        Collectors.toMap(
+                            outputField -> agg.getName() + "." + outputField,
+                            outputField -> { return agg.getType(); },
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java:236]:
```suggestion
                            outputField -> agg.getType(),
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java (hunk 4 above)
Comment (przemekwitek) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/TransformAggregations.java:227]: Or just:
```
outputField -> outputField,
```
as it can be even more readable.

**Review by przemekwitek — APPROVED** [review]
LGTM
