### PR TITLE
Return 0 for negative "free" and "total" memory reported by the OS

### LINKED ISSUE #42157: Negative used memory causes IllegalArgumentException in _cat/nodes
The following build failed trying to report a negative number of bytes returned from `OsStats.Mem#getUsed()`:

https://scans.gradle.com/s/hvu55m4ctmbd6/console-log?task=:qa:mixed-cluster:v7.2.0%23mixedClusterTestRunner#L675

This was in `:qa:mixed-cluster:v7.2.0#mixedClusterTestRunner`, and the stack trace looked as follows:

```
  1> [2019-05-15T12:28:35,981][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=cat.nodes/10_basic/Test cat nodes output] before test
  1> [2019-05-15T12:28:36,001][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "error" : {
  1>         "root_cause" : [
  1>           {
  1>             "type" : "illegal_argument_exception",
  1>             "reason" : "Values less than -1 bytes are not supported: -366415872b",
  1>             "stack_trace" : "[Values less than -1 bytes are not supported: -366415872b]; nested: IllegalArgumentException[Values less than -1 bytes are not supported: -366415872b];
  1>  at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639)
  1>  at org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:567)
  1>  at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)
  1>  at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
  1>  at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)
  1>  at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)
  1>  at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:49)
  1>  at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
  1>  at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:238)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:215)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:142)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:193)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:183)
  1>  at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)
  1>  at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)
  1>  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>  at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)
  1>  at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)
  1>  at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141)
  1>  at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)
  1>  at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660)
  1>  at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  1>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
  1>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  1>  at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  1>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
  1>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  1>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
  1>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)
  1>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)
  1>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
  1>  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
  1>  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  1>  at java.base/java.lang.Thread.run(Thread.java:834)
  1> Caused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -366415872b
  1>  at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)
  1>  at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)
  1>  at org.elasticsearch.monitor.os.OsStats$Mem.getUsed(OsStats.java:252)
  1>  at org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:305)
  1>  at org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)
  1>  at org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)
  1>  at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)
  1>  at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)
  1>  ... 40 more
  1> "
  1>           }
  1>         ],
  1>         "type" : "illegal_argument_exception",
  1>         "reason" : "Values less than -1 bytes are not supported: -366415872b",
  1>         "stack_trace" : "java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -366415872b
  1>  at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)
  1>  at org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)
  1>  at org.elasticsearch.monitor.os.OsStats$Mem.getUsed(OsStats.java:252)
  1>  at org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:305)
  1>  at org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)
  1>  at org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)
  1>  at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)
  1>  at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)
  1>  at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
  1>  at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:238)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:215)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:142)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:193)
  1>  at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:183)
  1>  at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)
  1>  at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)
  1>  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>  at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)
  1>  at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)
  1>  at org.elasticsearch.transport.InboundHan  1> dler.messageReceived(InboundHandler.java:141)
  1>  at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)
  1>  at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660)
  1>  at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  1>  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
  1>  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  1>  at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
  1>  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
  1>  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
  1>  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
  1>  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  1>  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
  1>  at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)
  1>  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)
  1>  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
  1>  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
  1>  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  1>  at java.base/java.lang.Thread.run(Thread.java:834)
  1> "
  1>       },
  1>       "status" : 400
  1>     }
  1>   }
  1> }]
  1> [2019-05-15T12:28:36,030][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=cat.nodes/10_basic/Test cat nodes output] after test
  2> REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v7.2.0#mixedClusterTestRunner --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=cat.nodes/10_basic/Test cat nodes output}" -Dtests.seed=3246BE5B867D1D1C -Dtests.security.manager=true -Dtests.locale=ckb-IR -Dtests.timezone=America/Argentina/Mendoza -Dcompiler.java=12 -Druntime.java=11
  2> java.lang.AssertionError: Failure at [cat.nodes/10_basic:4]: expected [2xx] status code but api [cat.nodes] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -366415872b","stack_trace":"[Values less than -1 bytes are not supported: -366415872b]; nested: IllegalArgumentException[Values less than -1 bytes are not supported: -366415872b];\n\tat org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639)\n\tat org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:567)\n\tat org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)\n\tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)\n\tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)\n\tat org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)\n\tat org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:49)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:238)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:215)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:142)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:193)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:183)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)\n\tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -366415872b\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)\n\tat org.elasticsearch.monitor.os.OsStats$Mem.getUsed(OsStats.java:252)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:305)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)\n\tat org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)\n\tat org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)\n\t... 40 more\n"}],"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -366415872b","stack_trace":"java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -366415872b\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)\n\tat org.elasticsearch.monitor.os.OsStats$Mem.getUsed(OsStats.java:252)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:305)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)\n\tat org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)\n\tat org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:238)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:215)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:142)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:193)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:183)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)\n\tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"status":400}]
        Caused by:
        java.lang.AssertionError: expected [2xx] status code but api [cat.nodes] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -366415872b","stack_trace":"[Values less than -1 bytes are not supported: -366415872b]; nested: IllegalArgumentException[Values less than -1 bytes are not supported: -366415872b];\n\tat org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639)\n\tat org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:567)\n\tat org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)\n\tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)\n\tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)\n\tat org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)\n\tat org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:49)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:238)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:215)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:142)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:193)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:183)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)\n\tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -366415872b\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)\n\tat org.elasticsearch.monitor.os.OsStats$Mem.getUsed(OsStats.java:252)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:305)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)\n\tat org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)\n\tat org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)\n\t... 40 more\n"}],"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -366415872b","stack_trace":"java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -366415872b\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)\n\tat org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)\n\tat org.elasticsearch.monitor.os.OsStats$Mem.getUsed(OsStats.java:252)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:305)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)\n\tat org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)\n\tat org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)\n\tat org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)\n\tat org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:238)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:215)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:142)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:193)\n\tat org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:183)\n\tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)\n\tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)\n\tat org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216)\n\tat org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141)\n\tat org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)\n\tat org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660)\n\tat org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"status":400}]
```

### PR DESCRIPTION
**Pull request by dakrone**
We've had a situation where the MX bean reported negative values for the
free memory of the OS, in those rare cases we want to return a value of
0 rather than blowing up later down the pipeline.

In the event that there is a serialization or creation error with regard
to memory use, this adds asserts so the failure will occur as soon as
possible and give us a better location for investigation.

Resolves #42157

### CODE REVIEW

**Comment by jasontedor** [comment]
Under what circumstances did this happen. I see it was on Linux 3.16.0-8-amd64, a Debian kernel. Did we did into the JDK source to understand what happened, is this a JDK bug, an OS bug, or has our world view been shattered? Are we working around something that is fixed on modern kernels? I don’t like these band-aids without understanding their source. And if we commit the band-aid our code should have a comment telling the story of this investigation, for future passersby.

**Comment by dakrone** [comment]
It's possible for this native method to return -1, for Apple, and AIX systems:

```c
JNIEXPORT jlong JNICALL
Java_com_sun_management_internal_OperatingSystemImpl_getFreePhysicalMemorySize0
  (JNIEnv *env, jobject mbean)
{
#ifdef __APPLE__
    mach_msg_type_number_t count;
    vm_statistics_data_t vm_stats;
    kern_return_t res;

    count = HOST_VM_INFO_COUNT;
    res = host_statistics(mach_host_self(), HOST_VM_INFO, (host_info_t)&vm_stats, &count);
    if (res != KERN_SUCCESS) {
        throw_internal_error(env, "host_statistics failed");
        return -1; // <<< --- HERE
    }
    return (jlong)vm_stats.free_count * page_size;
#elif defined(_ALLBSD_SOURCE)
    /*
     * XXBSDL no way to do it in FreeBSD
     */
    // throw_internal_error(env, "unimplemented in FreeBSD")
    return (128 * MB);
#elif defined(_AIX)
    perfstat_memory_total_t memory_info;
    if (-1 != perfstat_memory_total(NULL, &memory_info, sizeof(perfstat_memory_total_t), 1)) {
        return (jlong)(memory_info.real_free * 4L * 1024L);
    }
    return -1; // <<< --- HERE
#else // solaris / linux
    jlong num_avail_physical_pages = sysconf(_SC_AVPHYS_PAGES);
    return (num_avail_physical_pages * page_size);
#endif
}
```

I'm unable able to determine exactly how it overflowed in Linux, however, the manpage for `sysconf` does specify:

```
_SC_PHYS_PAGES
The number of pages of physical memory.  Note that it is possible for the product of this value and the value of  _SC_PAGESIZE  to  over‐flow.
```

Additionally:

```
The return value of sysconf() is one of the following:
*  On error, -1 is returned and errno is set to indicate the cause of the error (for example, EINVAL, indicating that name is invalid).
```

Meaning that if the `sysconf` call for `_SC_AVPHYS_PAGES` were to fail, it could return -1 and multiply that value by the `page_size`, returning a negative free memory amount. Additionally, `_SC_AVPHYS_PAGES_` is also considered not to be a standard option: `"These values also exist, but may not be standard."` (for the `_SC_`-prefixed options).

```
*  If name corresponds to an option ... -1 is returned if the option is not supported.
```

I also checked the linux kernel 3.16.x source code, HPUX would return -1 for the available physical pages (it doesn't support that option).


```c
int hpux_sysconf(int which)
{
	switch (which) {
	case _SC_CPU_VERSION:
		return CPU_PA_RISC1_1;
	case _SC_OPEN_MAX:
		return INT_MAX;
	default:
		return -EINVAL;
	}
}
```

In GNU's libc, the `sysconf` implementation (the "hidden" implementation, which I admit I definitely do not understand), can return -1 for the `__get_phys_pages` method which is called by the `sysconf` implementation (it appears that it sends it off to the linux `sysinfo` call):

```c
long int
__get_phys_pages (void)
{
  /* We have no general way to determine this value.  */
  __set_errno (ENOSYS);
  return -1;
}
libc_hidden_def (__get_phys_pages)
weak_alias (__get_phys_pages, get_phys_pages)
```

The `sysinfo` call can return a negative value on non-SMP kernels (which I don't think we have much of any more?):

```c
static inline unsigned long global_page_state(enum zone_stat_item item)
{
	long x = atomic_long_read(&vm_stat[item]);
#ifdef CONFIG_SMP
	if (x < 0)
		x = 0;
#endif
	return x;
}
```

I know that we don't support AIX or HPUX, but given that it's possible for an OS not to support these flags (Apple failing to return host statistics for instance, or Linux running a non-standard libc (I didn't check whether musl libc could return negative values)), I think we should be extra cautious about what values we get from the OS and be safe about returning 0 when negative values are returned.

If, as might be possible, it's a serialization issue or construction issue, the extra asserts will help us narrow that down as well, since it addresses it from the `Mem` object construction side rather than the OS bean side.

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine elasticsearch-ci/1

**Comment by jakelandis** [comment]
added team discuss to further discuss if we should merge this now Lee has figured out exactly how this can happen.

**Comment by jakelandis** [comment]
Discussed this today and came away with the following points:
* It is possible that a supported distribution's kernel could emit a negative value
* It is known that some unsupported distribution's can emit a negative value
* For unsupported distribution's if there are low friction, low/no maintenance fixes to better enable Elasticsearch to allow it work, we should accept those changes. 

We will proceed with this issue and thanks @dakrone for the deep dive into how this is possible.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningTests.java [hunk 1]
```diff
@@ -97,8 +97,8 @@ public void testNoAttributes_givenClash() {
 
     public void testMachineMemory_givenStatsFailure() throws IOException {
         OsStats stats = mock(OsStats.class);
-        when(stats.getMem()).thenReturn(new OsStats.Mem(-1, -1));
-        assertEquals(-1L, MachineLearning.machineMemoryFromStats(stats));
+        when(stats.getMem()).thenReturn(new OsStats.Mem(0, 0));
+        assertEquals(0L, MachineLearning.machineMemoryFromStats(stats));
```
Comment (droberts195) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningTests.java]: I think a corresponding change of `mem < 0` to `mem <= 0` should also be made in the `MachineLearning.machineMemoryFromStats()` method, on lines 804 and 805 of `MachineLearning.java`.

**Comment by jakelandis** [comment]
LGTM pending @droberts195 [comment](https://github.com/elastic/elasticsearch/pull/42725#discussion_r293449809).

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningTests.java (hunk 1 above)
Comment (dakrone) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningTests.java]: I've updated that also, thanks for the heads up!

**Review by droberts195 — APPROVED** [review]
Thanks for making the extra change

**Comment by jasontedor** [comment]
@dakrone Thank you *so* much for diving into this, that’s the kind of analysis we need for changes like this. One request though, can we transfer some of the analysis into a comment in the code for future passersby?

**Comment by dakrone** [comment]
@jasontedor certainly, I'll add a comment where we get back the value from the bean

File: server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java [hunk 2]
```diff
@@ -42,6 +42,23 @@
...
+ * The {@link OsProbe} class retrieves information about the physical and swap size of the machine
+ * memory, as well as the system load average and cpu load.
+ *
+ * In some exceptional cases, it's possible the underlying native method used by
+ * {@link #getFreePhysicalMemorySize()} and {@link #getTotalPhysicalMemorySize()} can return a
+ * negative value. Because of this, we prevent those methods from returning negative values,
+ * returning 0 instead.
+ *
+ * The OS can report a negative number in a number of cases:
+ * - Non-supported OSes (HP-UX, AIX, OSX after failing to initialize host statistics
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java]: This is slightly misleading since we support macOS (the official name of the OS).

Comment (dakrone) [reply server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java]: I updated the wording to make it clearer, thanks

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by taf2** [comment]
We are seeing this issue now on es 7.5.2 running Amazon Linux 2.


```
[ct@ip-10-55-31-96 ~]# curl localhost:9200/_cat/nodes
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -2b"}],"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -2b"},"status":400}[root@ip-10-55-31-96 ~]#
[ct@ip-10-55-31-96 ~]# uname -a
Linux ip-10-55-31-96.ec2.internal 4.14.152-127.182.amzn2.x86_64 #1 SMP Thu Nov 14 17:32:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[ct@ip-10-55-31-96 ~]#
```
```
[ct@ip-10-55-31-96 ~]# curl localhost:9200
{
  "name" : "es7d-23",
  "cluster_name" : "es7",
  "cluster_uuid" : "UJ-qxUlHROCBIZ9pFGagHw",
  "version" : {
    "number" : "7.5.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "8bec50e1e0ad29dad5653712cf3bb580cd1afcdf",
    "build_date" : "2020-01-15T12:11:52.313576Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[ct@ip-10-55-31-96 ~]#
```

**Comment by jamshid** [comment]
I'm seeing this error on a 5-node Elasticsearch 7.5.2 on centos 7.8.2003. Any idea if I should file a new issue or if it will be fixed by an upgrade or is it a sign of misconfiguration? This is upgraded from ES 6.8 and I just deleted a large index. I guess I'll try a reboot.

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -108b","stack_trace":"[Values less than -1 bytes are not supported: -108b]; nested: IllegalArgumentException[Values less than -1 bytes are not supported: -108b];
	 org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644)
	 org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:57
...
Caused by: java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -108b
	 org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)
	 org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)
	 org.elasticsearch.index.cache.query.QueryCacheStats.getMemorySize(QueryCacheStats.java:73)
	 org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:341)
	 org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)
	 org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:102)
	 org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)
	 org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)
\t... 23 more
"}],"type":"illegal_argument_exception","reason":"Values less than -1 bytes are not supported: -108b","stack_trace":"java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -108b
	 org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:72)
	 org.elasticsearch.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:67)
	 org.elasticsearch.index.cache.query.QueryCacheStats.getMemorySize(QueryCacheStats.java:73)
	 org.elasticsearch.rest.action.cat.RestNodesAction.buildTable(RestNodesAction.java:341)
	 org.elasticsearch.rest.action.cat.RestNodesAction$1$1$1.buildResponse(RestNodesAction.java:105)
...
```

**Comment by RicardoGralhoz** [comment]
I also saw this issue on  a 13-node cluster with **Elasticsearch v7.8.1**, Ubuntu 18.04.2 LTS, OpenJDK 64-Bit v11.0.3, using G1GC, with 32GiB of memory, setting 16GB for JVM heap, IHOP 30% and reserving 25%. Upgraded from 7.1.0, but then deleted old data. Fixed on restart. I'm, opening a new topic on the forum, will reference it here later.

```
cat cluster_stats.json 

Bad Request. Rejected
{
  "error" : { 
    "root_cause" : [ 
      {   
        "type" : "illegal_argument_exception",
        "reason" : "Values less than -1 bytes are not supported: -9223372036787056125b"
      }   
    ],  
    "type" : "illegal_argument_exception",
    "reason" : "Values less than -1 bytes are not supported: -9223372036787056125b",
    "suppressed" : [ 
      {   
        "type" : "illegal_state_exception",
        "reason" : "Failed to close the XContentBuilder",
        "caused_by" : { 
          "type" : "i_o_exception",
          "reason" : "Unclosed object or array found"
        }
      }   
    ]   
  },  
  "status" : 400 
}
```

**Comment by ash-darin** [comment]
This misses the handling of swap data and there are a few instances where "total" is returned instead of "free" or "adjustedfree". I have created a PR to address this. #138573
