### PR TITLE
Remove deprecation warnings to prepare for Gradle 5 (sourceSets.main.output.classesDirs)

### LINKED ISSUE #30354: Build produces Gradle deprecation warnings for sourceSets.main.output.classesDirs
Here's one Example, but there are others throughout the build:

`./gradlew x-pack:plugin:monitoring:build --dry-run -Dorg.gradle.warning.mode=all --warning-mode=all --stacktrace`

```
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
	at org.gradle.api.internal.tasks.DefaultSourceSetOutput.getClassesDir(DefaultSourceSetOutput.java:81)
	at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getClassesDir(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.metaclass.MultipleSetterProperty.getProperty(MultipleSetterProperty.java:49)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
	at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at org.elasticsearch.gradle.precommit.NamingConventionsTask$_closure1.doCall(NamingConventionsTask.groovy:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.gradle.api.specs.internal.ClosureSpec.isSatisfiedBy(ClosureSpec.java:32)
	at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### PR DESCRIPTION
**Pull request by alpar-t**
Gradle replaced `project.sourceSets.main.output.classesDir` of type
`File` with `project.sourceSets.main.output.classesDirs` of type
`FileCollection`
(see [SourceSetOutput](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/tasks/SourceSetOutput.java))
Build output is now stored on a per language folder.

There are a few places where we use that, here's these and how it's
fixed:

- Randomized Test execution
    - look in all test folders ( pass the multi dir configuration to the
    ant runner )
    - DRY the task configuration by introducing `basedOn` for
      `RandomizedTestingTask` DSL
- Extend the naming convention test to support passing in multiple
  directories
- Fix the standalon test plugin, the dires were not passed trough,
  checked with a debuger and the statement had no affect due to a
  missing `=`.

Closes  #30354

### CODE REVIEW

**Comment by dadoonet** [comment]
Related to #27250.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy [hunk 1]
```diff
@@ -81,11 +80,18 @@ public class NamingConventionsTask extends LoggedExec {
         inputs.files(classpath)
         description = "Tests that test classes aren't misnamed or misplaced"
         executable = new File(project.runtimeJavaHome, 'bin/java')
-        if (false == checkForTestsInMain) {
+
+        def dirsToUse = (checkForTestsInMain ?
+            project.sourceSets.main.output.classesDirs :
+            project.sourceSets.test.output.classesDirs)
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: I don't think we can check these here, this would still be during configuration? Certainly not the existence of them in the filter below.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy [hunk 2]
```diff
@@ -95,6 +97,17 @@ class RandomizedTestingTask extends DefaultTask {
         listenersConfig.listeners.add(new TestReportLogger(logger: logger, config: testLoggingConfig))
     }
 
+    void basedOn(RandomizedTestingTask other) {
+        configure(BuildPlugin.commonTestConfig(project))
```
Comment (rjernst) [inline buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: BuildPlugin should not be referred to here. The intention has always been to move the randomized testing gradle code (notice this is in a different java package than the rest of the buildSrc code) back upstream with randomized testing itself. See https://github.com/randomizedtesting/gradle-randomized-testing-plugin where I made some snapshots when first working on migrating the build to gradle, but was not able to cleanup and document it enough to release on its own.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy [hunk 3]
```diff
@@ -95,6 +97,17 @@ class RandomizedTestingTask extends DefaultTask {
...
+        classpath = other.classpath;
+        testClassesDirs = other.testClassesDirs;
```
Comment (rjernst) [inline buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: I think all the users of this could just be converted to use this line? I don't think we need to or should overly abstract this "shared code". For example, it would be better to make internalClusterTest task added by an additional gradle plugin to reduce duplication there.

**Review by rjernst — CHANGES_REQUESTED** [review]
Thanks for starting on this! I've left some comments. More generally, I see a lot of unrelated changes here. Things like reformatting or restructuring should generally go in separate PRs to ease reviewing.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy (hunk 1 above)
Comment (atorok) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: This works because the FileCollection is a live collection, this the checks are actually only executed lather.
I'm changing this anyhow, as  I discovered that we should not pick up non Java tests anyhow, because those don't adhere to the naming conventions.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy (hunk 2 above)
Comment (atorok) [reply buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: I  moved it back to the Gradle script.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingPlugin.groovy [hunk 4]
```diff
@@ -44,24 +44,24 @@ class RandomizedTestingPlugin implements Plugin<Project> {
         }
     }
 
-    static void replaceTestTask(TaskContainer tasks) {
+    static void replaceTestTask(Project project) {
+        def tasks = project.tasks
```
[the remark this answers is not in the document]
Comment (atorok) [reply buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingPlugin.groovy]: fixed

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy (hunk 3 above)
Comment (atorok) [reply buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: I did change just the line everywhere during development, and decided to take the extra step to refactor it as I felt it's too detailed and does not convey intent well enough, every time I encountered it I had to carefully check to make sure none of the configuration is missing or slightly different. I do agree that a plugin as you suggest would be even better,  but this is a step that will make that a bit easier to implement.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy [hunk 5]
```diff
@@ -211,7 +224,7 @@ class RandomizedTestingTask extends DefaultTask {
 
         DefaultLogger listener = null
         ByteArrayOutputStream antLoggingBuffer = null
-        if (logger.isInfoEnabled() == false) {
+        if (!logger.isInfoEnabled()) {
```
[the remark this answers is not in the document]
Comment (atorok) [reply buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: fixed

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy [hunk 6]
```diff
@@ -211,7 +223,7 @@ class RandomizedTestingTask extends DefaultTask {
 
         DefaultLogger listener = null
         ByteArrayOutputStream antLoggingBuffer = null
-        if (logger.isInfoEnabled() == false) {
+        if (false == logger.isInfoEnabled()) {
```
Comment (rjernst) [inline buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: I still see lots of arbitrary syntactical changes like this. Every extra line of output makes something that must be looked at. Without these minor changes, I think this PR would only be a dozen lines or so and would be very quick to review.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy [hunk 7]
```diff
@@ -95,6 +97,16 @@ class RandomizedTestingTask extends DefaultTask {
         listenersConfig.listeners.add(new TestReportLogger(logger: logger, config: testLoggingConfig))
     }
 
+    void basedOn(RandomizedTestingTask other) {
```
Comment (rjernst) [inline buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: I really would like to not have this. It makes many assumptions (eg that that `check` should depend on this). Can we please keep this change only to updating testClassesDirs and look at ways to deduplicate internClusterTest in a separate issue?

**Review by rjernst — COMMENTED** [review]
I left a few more comments

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy (hunk 7 above)
Comment (atorok) [reply buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: Removed it. I have a better understanding of why this was not a good idea now, and why this would be better handled in it's own PR.  There are multiple ways to manage tests, deal with unit and integrations tests etc ( there's an `additionalTests` extension that is similar to what `basedOn` did ).  It might also be worth setting up a different source path for integration tests then we could auto wire that to check and offer a clear DSL for defining new tests that are possibly  a subset of the existing unit or integration with additional system properties.

File: buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy (hunk 6 above)
Comment (atorok) [reply buildSrc/src/main/groovy/com/carrotsearch/gradle/junit4/RandomizedTestingTask.groovy]: I don't have a problem omitting them if that's the consensus, my take on it is that the cost of making and reviewing these is worthwhile if they improve the readability of the code, as it eventually pays off.

**Comment by atorok** [comment]
build this please

**Comment by atorok** [comment]
test this please

**Comment by atorok** [comment]
test this please

**Comment by atorok** [comment]
test this please

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy [hunk 8]
```diff
@@ -66,7 +65,7 @@ public class NamingConventionsTask extends LoggedExec {
     @Input
     boolean checkForTestsInMain = false;
 
-    public NamingConventionsTask() {
+    NamingConventionsTask() {
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: Please add back the `public`. As I mentioned before, a goal here is to keep these files as close as possible to java so buildSrc can be converted completely to java (hopefully someday soon).

File: buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java [hunk 9]
```diff
@@ -70,18 +72,21 @@ public static void main(String[] args) throws IOException {
...
                     fail("unsupported argument '" + arg + "'");
             }
         }
 
         NamingConventionsCheck check = new NamingConventionsCheck(testClass, integTestClass);
-        if (checkMainClasses) {
-            check.checkMain(rootPath);
-        } else {
-            check.checkTests(rootPath, skipIntegTestsInDisguise);
+        for (String rootDir : rootPathList.split(Pattern.quote(File.pathSeparator))) {
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java]: This seems inconsistent with the gradle code. There, a single dir is currently passed in. But here it looks like the path of that dir is split into its elements but then each read as a dir...

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy [hunk 10]
```diff
@@ -111,16 +111,27 @@ public class NamingConventionsTask extends LoggedExec {
...
+
+    File getJavaClassesDir() {
+        FileCollection classesDirs = (checkForTestsInMain ?
+                project.sourceSets.main.output.classesDirs :
+                project.sourceSets.test.output.classesDirs)
+        if (classesDirs.isEmpty()) { return null }
+        // see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html the deprecated property
+        // classesDir is the first in the FileCollection. There seems to be no other way to refer to the Java output dir
+        // We can't run the check against all classes as Groovy tests don't adhere to naming conventions.
+        return classesDirs[0]
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: Why don't we change the java code to work on multiple directories? Then you can just pass in all the classesDirs as multiple arguments.

**Review by rjernst — CHANGES_REQUESTED** [review]

File: buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java (hunk 9 above)
Comment (rjernst) [reply buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java]: I don't think we should do that. Each project should be checkable on its own. Combining all the sources into one task means to run precommit on a project requires running this one large task that looks at all test classes.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy (hunk 8 above)
Comment (rjernst) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: Kotlin was not around when we switched to gradle. We have tried sticking to java for multiple reasons:
* Expertise on Elasticsearch is usually in java
* I have seen numerous reports of double digit performance gains in configuration time from switching gradle plugins to java

Remember we are only talking about buildSrc here. The build.gradle files are still groovy. I am not averse to them being Kotlin, but I would want to see a significant advantage to that work, as we have now spent over 2 years with developers learning how to write groovy in gradle DSL.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy (hunk 10 above)
Comment (rjernst) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: Where do we have have groovy tests? How do we know the ordering would always result in the java classes dir coming first?

Comment (atorok) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: we have groovy  `./buildSrc/src/test/groovy/`. It's an odd that the Gradle API does not offer a more explicit way to get the java specific dirs, and choose to document that it will always be first here: 
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html 
It mentions the following for the deprectaed `File classesDir`  property:
```
Default with java plugin:
First directory from classesDirs
```

Comment (rjernst) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: While that deprecated property may document that fact, there would be nothing preventing gradle from changing the order once that property is removed. There are only 2 groovy tests. I think we can update their names to follow the naming convention?

Comment (atorok) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/NamingConventionsTask.groovy]: @rjernst I updated the task to pass along all dirs, but also added a new input to be able to bypass that and be specific of the  directory. Adding the Groovy tests is trickier because of the inheritance check but we'll be ok, since the build tools that have a hard coded path now are self tests, so if the test would change the test would fail.

**Comment by atorok** [comment]
I wasn't really happy about this solution as I realized that it makes it hard to add java tests to the `buildSrc` which would be a big no-no. I decided to get rid of the self test in favor of a proper integration test with gradles testkit. As part of the change I also converted some files to Java using automated IDE tools to better prove the point of java test - java class and updated the Groovy tests to

**Comment by atorok** [comment]
test this please

**Comment by atorok** [comment]
test this please

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionProperties.java [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+import java.io.IOException;
+import java.io.InputStream;
+import java.util.HashMap;
+import java.util.Map;
+import java.util.Properties;
+
+/**
+ * Accessor for shared dependency versions used by elasticsearch, namely the elasticsearch and lucene versions.
+ */
+public class VersionProperties {
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionProperties.java]: It appears this is being moved to a java file, but it is still under `src/main/groovy`?

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/LoggedExec.java [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+
+import java.io.ByteArrayOutputStream;
+import java.io.IOException;
+import java.io.UnsupportedEncodingException;
+import java.util.stream.Collectors;
+
+/**
+ * A wrapper around gradle's Exec task to capture output and log on error.
+ */
+public class LoggedExec extends Exec {
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/LoggedExec.java]: This appears to be moved to a java file, but still exists under `src/main/groovy`?

File: buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java [hunk 13]
```diff
@@ -63,59 +59,61 @@ public static void main(String[] args) throws IOException {
...
         if (skipIntegTestsInDisguise == false) {
-            assertNoViolations(
-                    "Subclasses of " + check.integTestClass.getSimpleName() + " should end with IT as they are integration tests",
-                    check.integTestsInDisguise);
+            exitCode += countAndPrintViolations("Subclasses of " + check.integTestClass.getSimpleName() +
+                        " should end with IT as they are integration tests",
+                    check.integTestsInDisguise
+                );
         }
+        System.exit(exitCode);
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java]: I don't think we should call System.exit. Instead, throw a GradleException with a message indicating there were violations.

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy [hunk 14]
```diff
@@ -16,6 +20,7 @@ class VersionCollectionTest extends GroovyTestCase {
    * branched from Major-1.x At the time of this writing 6.2 is unreleased and 6.3 is the 6.x branch. This test simulates the behavior
    * from 7.0 perspective, or master at the time of this writing.
    */
+  @Test
```
Comment (rjernst) [inline buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy]: I think this will be confusing to start having @Test in gradle tests, when we do not have them in the rest of the tests (and it is unclear how this would work when we run this as a normal `elasticsearch.build` as the `build-tools` project that uses randomized runner). We should be able to annotate the test with a junit3 compatible selector like randomized runner does?

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/doc/RestTestsFromSnippetsTaskTest.groovy [hunk 15]
```diff
@@ -19,32 +19,46 @@
...
 package org.elasticsearch.gradle.doc
 
-import org.elasticsearch.gradle.doc.SnippetsTask.Snippet
+import org.elasticsearch.gradle.GradleUnitTestCase
 import org.gradle.api.InvalidUserDataException
+import org.junit.Rule
+import org.junit.Test
+import org.junit.rules.ExpectedException
+
+import static org.junit.Assert.*
```
Comment (rjernst) [inline buildSrc/src/test/groovy/org/elasticsearch/gradle/doc/RestTestsFromSnippetsTaskTest.groovy]: Please do not use wildcard imports. We disallowed them in the rest of the codebase.

**Review by rjernst — COMMENTED** [review]
This is looking closer, but I have a few more comments.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionProperties.java (hunk 11 above)
Comment (atorok) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionProperties.java]: Yes. That is because the Groovy compiler knows how to deal with this and delegate these files to the Java compiler. The reason these can't move to `src/main/java` (yet) us that they make use of Groovy classes that are not on the cp  when pure java is compiled. Moving those Groovy classes to Java creates a ripple effect, so my thinking is that we can have java files in the groovy source set until we have critical mass, eventually removing the groovy source set. It's easier and less risky than converting to Java at once.

File: buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java (hunk 13 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/test/NamingConventionsCheck.java]: This uses an exit code since we don't call into this code directly, but run it like a cli utility.

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/doc/RestTestsFromSnippetsTaskTest.groovy (hunk 15 above)
Comment (atorok) [reply buildSrc/src/test/groovy/org/elasticsearch/gradle/doc/RestTestsFromSnippetsTaskTest.groovy]: I fixed my IDE setting some time ago, this must pre-date that. Fixed now.

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy (hunk 14 above)
Comment (atorok) [reply buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy]: We could inherit from TestCase but we loose `@Rule` and probably `@Before`, `@After` etc. 
The rest of the code supports both `@Test` and methods starting with `test`, but this is implemented in `@RunWith(RandomizedRunner.class)`, `@TestMethodProviders` is _not_ a junit4 annotation, the junit3 compatible selector is part of lucene test, so while it's possible to bring that in as a dependency it seems a bit odd. The other possibility is to duplicate that one filter class.

Comment (rjernst) [reply buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy]: I would duplicate the class if necessary. Having @Test in some parts of our code would be very confusing.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionProperties.java (hunk 11 above)
Comment (rjernst) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionProperties.java]: This sounds like a great plan!

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy (hunk 14 above)
Comment (atorok) [reply buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy]: done

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy [hunk 16]
```diff
@@ -1,6 +1,11 @@
 package org.elasticsearch.gradle
 
-class VersionCollectionTest extends GroovyTestCase {
+import org.elasticsearch.gradle.test.GradleUnitTestCase
+import org.junit.Test
+
+import static org.junit.Assert.*
```
Comment (rjernst) [inline buildSrc/src/test/groovy/org/elasticsearch/gradle/VersionCollectionTests.groovy]: Still have a wildcard import

File: buildSrc/src/test/groovy/org/elasticsearch/gradle/doc/RestTestFromSnippetsTaskTests.groovy [hunk 17]
```diff
@@ -19,31 +19,42 @@
...
 
-import static org.elasticsearch.gradle.doc.RestTestsFromSnippetsTask.shouldAddShardFailureCheck
+import org.elasticsearch.gradle.test.GradleUnitTestCase
+import org.gradle.api.InvalidUserDataException
+import org.junit.Rule
+import org.junit.rules.ExpectedException
+
 import static org.elasticsearch.gradle.doc.RestTestsFromSnippetsTask.replaceBlockQuote
+import static org.elasticsearch.gradle.doc.RestTestsFromSnippetsTask.shouldAddShardFailureCheck
+import static org.junit.Assert.*
```
Comment (rjernst) [inline buildSrc/src/test/groovy/org/elasticsearch/gradle/doc/RestTestFromSnippetsTaskTests.groovy]: Still have a wildcard import

File: buildSrc/src/test/java/org/elasticsearch/gradle/test/BaseTestCase.java [hunk 18]
```diff
@@ -0,0 +1,32 @@
...
+import com.carrotsearch.randomizedtesting.RandomizedRunner;
+import com.carrotsearch.randomizedtesting.annotations.TestMethodProviders;
+import org.junit.runner.RunWith;
+
+@RunWith(RandomizedRunner.class)
+@TestMethodProviders({
+    JUnit4MethodProvider.class,
+    JUnit3MethodProvider.class
+})
+public abstract class BaseTestCase {
```
Comment (rjernst) [inline buildSrc/src/test/java/org/elasticsearch/gradle/test/BaseTestCase.java]: You can make this extend from `Assert` to not have to import the common methods used like assertEquals

File: buildSrc/src/test/java/org/elasticsearch/gradle/test/GradleUnitTestCase.java [hunk 19]
```diff
@@ -0,0 +1,14 @@
...
+import com.carrotsearch.randomizedtesting.RandomizedRunner;
+import com.carrotsearch.randomizedtesting.annotations.TestMethodProviders;
+import org.junit.runner.RunWith;
+
+@RunWith(RandomizedRunner.class)
+@TestMethodProviders({
+    JUnit4MethodProvider.class,
+    JUnit3MethodProvider.class
+})
+public abstract class GradleUnitTestCase extends BaseTestCase  {
```
Comment (rjernst) [inline buildSrc/src/test/java/org/elasticsearch/gradle/test/GradleUnitTestCase.java]: Why have this and BaseTestCase? I think just having one of these would be fine?

**Review by rjernst — APPROVED** [review]
LGTM, a few last comments.

File: buildSrc/src/test/java/org/elasticsearch/gradle/test/GradleUnitTestCase.java (hunk 19 above)
Comment (atorok) [reply buildSrc/src/test/java/org/elasticsearch/gradle/test/GradleUnitTestCase.java]: An integration test is not a unit test, so I didn't initially want them to inherit from each-other, but would have to extend the name checker to be able to deal with it.

File: buildSrc/src/test/java/org/elasticsearch/gradle/test/BaseTestCase.java (hunk 18 above)
Comment (atorok) [reply buildSrc/src/test/java/org/elasticsearch/gradle/test/BaseTestCase.java]: I'll fix these, thanks, I finally figured out  where these are coming from, it's in the template for test classes.
