### PR TITLE
ES|QL: fix quoting in generative tests

### LINKED ISSUE #140859: [CI] GenerativeIT test failing
**Build Scans:**
- [elasticsearch-periodic #11750 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/275i5znkk2koy)
- [elasticsearch-periodic-platform-support #11718 / windows-2025_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/4xl2hnmcp6s2g)
- [elasticsearch-periodic #11745 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/c6tey4gbbt7ni)
- [elasticsearch-periodic-platform-support #11713 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/vbaylk76bajhi)
- [elasticsearch-periodic-platform-support #11703 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/4uvnx25dhhabm)
- [elasticsearch-intake #33259 / part3](https://gradle-enterprise.elastic.co/s/7f6ie5qvopoxu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.GenerativeIT.test" -Dtests.seed=75E01E56046E1B2E -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=ln-AO -Dtests.timezone=Pacific/Apia -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.GenerativeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: query: from countries_bbox,ages | dissect id "%{ocYeoKbB} %{BzAWavOZsi} %{ZTGlakGMSFQW}" | keep `ZTGlakGMSFQW`, `id`, `description`, `BzAWavOZsi`, *d, id | enrich languages_policy on description | keep `language_name`, `id`, id | rename `id` AS language_name | enrich languages_policy on language_name | grok language_name "%{WORD:MmcxruooVD} %{WORD:language_name}"| rename language_name as message | lookup join message_types_lookup on message | enrich languages_policy on message | stats  WDDrThgCTWpO = count(language_name), `message` = count_distinct(type), type = count_distinct(MmcxruooVD), message = count(*), type = count_distinct(type) by language_name
exception: method [POST], host [http://[::1]:40895], URI [/_query?pretty=true&error_trace=true], status line [HTTP/1.1 500 Internal Server Error]
Warnings: [No limit defined, adding default limit of [1000], Line 1:556: Field 'type' shadowed by field at line 1:611, Line 1:522: Field 'message' shadowed by field a
[truncated]
```

**Issue Reasons:**
- [9.1] 6 failures in test test (4.5% fail rate in 132 executions)
- [9.1] 2 failures in pipeline elasticsearch-periodic (40.0% fail rate in 5 executions)
- [9.1] 3 failures in pipeline elasticsearch-periodic-platform-support (60.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by luigidellaquila**
In EsqlQueryGenerator, quoting/unquoting was inconsistent.
The main problem was that when it extracted the output columns, it also tried to normalize field names by applying quoting (if needed).
This created a lot of confusion downstream, because command generators often don't use a field as is, but do manipulations (eg. adding wildcards), so they had to quote/unquote, and it resulted in duplicated and scattered quoting logic.

The main changes here are:
1. Output columns will now contain raw field names (no quoting here)
2. All the helper methods that return a random field, also apply quoting if needed (except from `randomRawName()` of course) 
3. Generators that get random fields from the helper methods (see 2), will have quoting for free.
4. Generators that explicitly use raw fields, will also take care of quoting if needed. 

Fixes: https://github.com/elastic/elasticsearch/issues/140859

### CODE REVIEW

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java [hunk 1]
```diff
@@ -546,12 +570,15 @@ public static boolean fieldCanBeUsed(Column field) {
             || field.originalTypes().stream().anyMatch(x -> x.contains("vector"))) == false;
     }
 
+    public static String quote(String rawName) {
+        return "`" + rawName.replace("`", "``") + "`";
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java]: This now also takes inner backticks into consideration

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java [hunk 2]
```diff
@@ -546,12 +570,15 @@ public static boolean fieldCanBeUsed(Column field) {
             || field.originalTypes().stream().anyMatch(x -> x.contains("vector"))) == false;
     }
 
+    public static String quote(String rawName) {
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java:574]: May I suggest reusing the code we already have in `IdentifierBuilder.quoteIdString`?
Maybe move `quoteIdString` from `IdentifierBuilder` to `ParserUtils` class, make it `public` and use it for generative testing as well.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java [hunk 3]
```diff
@@ -546,12 +570,15 @@ public static boolean fieldCanBeUsed(Column field) {
...
+        return "`" + rawName.replace("`", "``") + "`";
+    }
+
     public static String unquote(String colName) {
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java:578]: Same here with `IdentifierBuilder.unquoteIdString`

**Review by astefan — COMMENTED** [review]
LGTM. Left one minor comment regarding code re-use, which would also imply correctness since the same logic is used by our own parser.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java:578]: Thanks @astefan, I refactored the code to use (un)quoteIdString.

I'm leaving the old `quote`/`unquote` methods as a wrapper just because `unquote` has some additional logic, but having consistency on quoting, and depending on the original logic from the parser is a big advantage in terms of stability.

**Review by astefan — APPROVED** [review]
LGTM. Sorry, it was great since yesterday, I forgot to change the default option from the review.
