### PR TITLE
Fix race condition when resolving new location for multiple shards at once

### LINKED ISSUE #128082: [CI] DataNodeRequestSenderTests testRetryOnlyMovedShards failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8290 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/mpkhg5lrwzjx6)
- [elasticsearch-periodic-platform-support #8224 / ubuntu-2004-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/3cvsuh36ewi4k)
- [elasticsearch-periodic-platform-support #8218 / windows-2019_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/3k7ssbarwl7xs)
- [elasticsearch-periodic-platform-support #8176 / ubuntu-2004-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/xumd4thkmxmn6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderTests.testRetryOnlyMovedShards" -Dtests.seed=B4179AA2A470F433 -Dtests.locale=pis-SB -Dtests.timezone=Eire -Druntime.java=24
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRetryOnlyMovedShards),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <2>
     but: was <1>
```

**Issue Reasons:**
- [8.19] 4 failures in test testRetryOnlyMovedShards (0.6% fail rate in 637 executions)
- [8.19] 2 failures in step ubuntu-2004-aarch64_checkpart3_platform-support-arm (10.0% fail rate in 20 executions)
- [8.19] 4 failures in pipeline elasticsearch-periodic-platform-support (20.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by idegtiarenko**
This fixes the race condition when retrying resolving multiple moved shards at once.
Please see inline comments for more details.

Related to: #127188
Closes: #128082

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 1]
```diff
@@ -204,7 +203,8 @@ private void trySendingRequestsForPendingShards(TargetShards targetShards, Compu
                         }
                     }
                     for (ShardId shardId : pendingShardIds) {
-                        if (targetShards.getShard(shardId).remainingNodes.isEmpty()) {
+                        if (targetShards.getShard(shardId).remainingNodes.isEmpty()
+                            && (isRetryableFailure(shardFailures.get(shardId)) == false || pendingRetries.contains(shardId))) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:207]: It was previously possible that between executing line 195 and line 206 one of the data nodes returns with NoSuchShard exception and add a new `pendingShardId`. As a result such shard might still not have `remainingNodes` nodes to query. This change supposed to detect such situations and delay such resolution to the next round.

This was detected by `testSearchWhileRelocating` integration test that is fairly slow and expensive so I added `testRetryMultipleMovedShards` unit test that made it much easier to reproduce.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks for fixing this.
