### PR TITLE
Fix OOM in AbstractXContentParser

### LINKED ISSUE #15338: OutOfMemoryError[Java heap space] when executing update with bad fields
Hi!
Running elasticsearch 2.1.0 I encountered weird behavior when trying to execute update. Tried to execute this query:
```
POST my-index/my-type/my_id/_update
{"doc": {"my_field_name": "blabla"}, "doc_as_upsert": true, "fields": "_source"}
```
and got **OutOfMemoryError\[Java heap space\]** (it took Elasticsearch a few seconds to answer).

As I understand it, the format of the query above is wrong. The value of "fields" should be list, not string (indeed when correcting the query the update worked fine). In a case like that I would expect to get some kind of an error indicating my request is not valid but It seems like some internal error have happen in elasticsearch and resulted in OutOfMemoryError.

This is the stack trace:
`java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2219)
        at java.util.ArrayList.grow(ArrayList.java:242)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:216)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:208)
        at java.util.ArrayList.add(ArrayList.java:440)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:290)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:253)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.list(AbstractXContentParser.java:218)
        at org.elasticsearch.action.update.UpdateRequest.source(UpdateRequest.java:672)
        at org.elasticsearch.rest.action.update.RestUpdateAction.handleRequest(RestUpdateAction.java:101)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
`

### PR DESCRIPTION
**Pull request by tlrx**
closes #15338

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java [hunk 1]
```diff
@@ -289,7 +289,7 @@ public BytesRef utf8BytesOrNull() throws IOException {
             token = parser.nextToken();
         }
         ArrayList<Object> list = new ArrayList<>();
-        for (; token != XContentParser.Token.END_ARRAY; token = parser.nextToken()) {
+        for (; token != null && token.isValue(); token = parser.nextToken()) {
             list.add(readValue(parser, mapFactory, token));
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: Do we ever read lists of objects with this?

File: core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java [hunk 2]
```diff
@@ -289,7 +289,7 @@ public BytesRef utf8BytesOrNull() throws IOException {
             token = parser.nextToken();
         }
         ArrayList<Object> list = new ArrayList<>();
-        for (; token != XContentParser.Token.END_ARRAY; token = parser.nextToken()) {
+        for (; token != null && token.isValue(); token = parser.nextToken()) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: maybe this should be `token != null && (token.isValue() || token == VALUE_NULL)`?

**Comment by tlrx** [comment]
@nik9000 @jpountz thanks for your reviews. Actually I've been too quick in submitting the fix and forgot to commit the other part in `UpdateRequest`.

I also updated the `for` loop condition to stop once the parser is fully consumed.

File: core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java (hunk 1 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: Yes, the condition `token != null && token.isValue()` is not enough, we need to consume all the parser and stop when we hit the end of the array or the end of the parent's object.

File: core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java (hunk 2 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: See previous comment

File: core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java [hunk 3]
```diff
@@ -289,7 +289,7 @@ public BytesRef utf8BytesOrNull() throws IOException {
             token = parser.nextToken();
         }
         ArrayList<Object> list = new ArrayList<>();
-        for (; token != XContentParser.Token.END_ARRAY; token = parser.nextToken()) {
+        for (; token != null && token != XContentParser.Token.END_ARRAY && token != XContentParser.Token.END_OBJECT; token = parser.nextToken()) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: why do we need to check for END_OBJECT?

File: core/src/test/java/org/elasticsearch/common/xcontent/XContentParserTests.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+        sources.put("{\"foo\": [\"bar\"]}", 1);
+        sources.put("{\"foo\": [\"bar\",\"baz\"]}", 2);
+        sources.put("{\"foo\": [{\"bar\":1},{\"baz\":2},{\"qux\":3}]}", 3);
+        sources.put("{\"foo\": [1]}", 1);
+        sources.put("{\"foo\": [1,2]}", 2);
+        // Less common but possible usage
+        sources.put("{\"foo\": \"bar\"}", 1);
+        sources.put("{\"foo\": 1}", 1);
+        sources.put("{\"foo\": {\"bar\":\"baz\"}}", 1);
+        sources.put("{\"foo\": [{},{},{},{}]}", 4);
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/common/xcontent/XContentParserTests.java]: Can you test with eg. `{"foo": 1, "bar": 2}`? I'm afraid calling parser.list() on foo might return [1,2] given how it's implemented?

File: core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java (hunk 3 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: It is a small safeguard in case some code tries to read a list but only a value is available. `list()` and `readList()` methods should only be called when parsing an array but who knows.

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java]: could we throw an exception instead then?

**Comment by clintongormley** [comment]
@tlrx are you coming back to this one?

File: core/src/test/java/org/elasticsearch/common/xcontent/XContentParserTests.java [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+        assertThat(readList("{\"foo\": [{\"bar\":1},{\"baz\":2},{\"qux\":3}]}"), hasSize(3));
+        assertThat(readList("{\"foo\": null}"), hasItem(nullValue()));
+        assertThat(readList("{\"foo\": []}"), hasSize(0));
+        assertThat(readList("{\"foo\": [1]}"), hasItem(1));
+        assertThat(readList("{\"foo\": [1,2]}"), hasItems(1, 2));
+
+        // Less common but possible usage
+        assertThat(readList("{\"foo\": \"bar\"}"), hasItem("bar"));
+        assertThat(readList("{\"foo\": 1}"), hasItem(1));
+        assertThat(readList("{\"foo\": 1, \"bar\": 2}"), hasItem(1));
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/common/xcontent/XContentParserTests.java]: it will also contain '2' in that case right? this feels wrong, doesn't it?

**Comment by jpountz** [comment]
I am good with merging the change as it fixes the OOM issue but I think we need a follow-up PR in order to make list parsing less lenient. For instance it feels wrong to me that we consume tokens until the next END_ARRAY without ensuring that we had a START_ARRAY in the first place.

**Comment by tlrx** [comment]
Thanks @jpountz 

> For instance it feels wrong to me that we consume tokens until the next END_ARRAY without ensuring that we had a START_ARRAY in the first place.

I agree and I think this is the only way to correctly fix this issue... I updated the code according to your comment.

**Comment by jpountz** [comment]
LGTM!
