### PR TITLE
Fix fields API for geo_point fields inside other arrays

### LINKED ISSUE #99781: fields option not returning values with an array of objects
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

21.6.0 Darwin Kernel Version 21.6.0: Thu Jul  6 22:18:26 PDT 2023; root:xnu-8020.240.18.702.13~1/RELEASE_X86_64 x86_64

### Problem Description

fields option is not returning values with an array of objects. See example in "Steps to Reproduce"

### Steps to Reproduce

```
PUT test
{}

PUT test/_mapping
{
  "properties": {
    "results": {
      "properties": {
        "value": {
          "type": "geo_point"
        }
      }
    }
  }
}

PUT test/_doc/1
{
  "results": [
    {
      "value": [
        {
          "lat": 0,
          "lon": 0
        }
      ]
    }
  ]
}


POST /test*/_search
{
  "_source": false,
  "fields": [
    "results.value"
  ]
}
```

In the response, notice how fields is not populated and no value is returned

```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_id": "1",
        "_score": 1
      }
    ]
  }
}
```

I would expect to get a response like 
```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_id": "1",
        "_score": 1,
        "fields": {
          "results.value": [
            {
              "coordinates": [
                0,
                0
              ],
              "type": "Point"
            }
          ]
        }
      }
    ]
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by cbuescher**
The fields API currently doesn't work for geopoint arrays inside outer objects
that again are expressed as multi-values arrays. The reason is that upon
extracting the leaf values from source (i.e via Source#extractValue) we
accumulate intermediate array structures as additinal lists in the source value
we then try to parse. For other field types, especially those that use
SourceValueFetcher, this doesn't matter because we have a list-flattening step
in SourceValueFetcher#fetchValues, but for geo_point types the parser cannot
deal with the additional list levels. This change modifies the source extraction
so that we avoid nesting to many list structures inside each other, which I
believe currently is wrong but is masked by the list deduplication mentioned
above.

Closes https://github.com/elastic/elasticsearch/issues/99781

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java [hunk 1]
```diff
@@ -195,7 +195,18 @@ private static Object extractValue(String[] pathElements, int index, Object curr
...
+                    // accumulate intermediate array structures
+                    if (listValue instanceof List<?> list) {
+                        if (index == pathElements.length) {
+                            newList.add(list);
+                        } else {
+                            newList.addAll(list);
+                        }
+                    } else {
+                        newList.add(listValue);
+                    }
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java:209]: Can we add something to `XContentMapValuesTests` that exercises this?

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java [hunk 2]
```diff
@@ -394,6 +394,165 @@ public void testArrayValueMappers() throws IOException {
         assertThat(field.getValues().size(), equalTo(2));
     }
 
+    public void testGeopointArrayInObject() throws IOException {
+        MapperService mapperService = createMapperService();
+        {
+            XContentBuilder source = XContentFactory.jsonBuilder()
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java:400]: There's a `fetchFields` method that takes a String rather than an XContentBuilder, so I think it's worth changing these to use multiline strings?  They're just so much easier to read.

**Review by romseygeek — COMMENTED** [review]
Thanks @cbuescher, I left a couple of comments

File: server/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java (hunk 1 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java:209]: Sure, I didn't see that particular test class but it makes much sense to do more in-depth testing there then.

**Comment by cbuescher** [comment]
@romseygeek thanks for the review, I made the changes to the tests you suggested.

File: server/src/main/java/org/elasticsearch/index/mapper/AbstractGeometryFieldMapper.java [hunk 3]
```diff
@@ -116,6 +116,7 @@ public final Query termQuery(Object value, SearchExecutionContext context) {
         public ValueFetcher valueFetcher(SearchExecutionContext context, String format) {
             Function<List<T>, List<Object>> formatter = getFormatter(format != null ? format : GeometryFormatterFactory.GEOJSON);
             return new ArraySourceValueFetcher(name(), context) {
+
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/AbstractGeometryFieldMapper.java:119]: nit: extra line

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java [hunk 4]
```diff
@@ -394,6 +394,176 @@ public void testArrayValueMappers() throws IOException {
...
+            assertPoint((Map<?, ?>) values.get(1), 41.0, 2.1);
+        }
+    }
+
+    private void assertPoint(Map<?, ?> pointMap, double lat, double lon) {
+        assertEquals("Point", pointMap.get("type"));
+        assertEquals(List.of(lon, lat), pointMap.get("coordinates"));
+    }
+
+    public void testDensevectorInObject() throws IOException {
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java:461]:
```suggestion
    public void testDenseVectorInObject() throws IOException {
```

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java [hunk 5]
```diff
@@ -394,6 +394,176 @@ public void testArrayValueMappers() throws IOException {
...
+                ]
+            }
+            """;
+
+        fields = fetchFields(mapperService, source, fieldAndFormatList("object.field", null, false));
+        assertThat(fields.size(), equalTo(1));
+
+        field = fields.get("object.field");
+        assertNotNull(field);
+        assertThat(field.getValues().size(), equalTo(3));
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java:564]:
```suggestion
        assertThat(field.getValues(), containsInAnyOrder("foo", "bar", "baz");
```

**Review by romseygeek — APPROVED** [review]
Couple of nits, LGTM otherwise.  Thanks!

**Comment by andrewkcarter** [comment]
Thank you @cbuescher.
