### PR TITLE
ESQL: Make equals include ids for Alias, TypedAttribute

### LINKED ISSUE #131509: ES|QL: IllegalStateException with RENAME x AS y, y AS x
On CSV test dataset

```
from airports_not_indexed 
| drop `city_location`, country, city, ab*, `type`, city_location 
| eval  location = null, fJkoOJwx = -1, `scalerank` = "a", OZucUvNbqb = 900014945 
| rename fJkoOJwx AS OZucUvNbqb, `name` AS FXIrumceg, `scalerank` AS `OZucUvNbqb` 
| drop `FXIrumceg`, FXIrumceg 
| sort OZucUvNbqb DESC 
| mv_expand OZucUvNbqb 
| grok OZucUvNbqb "%{WORD:location} %{WORD:sTyuHhEoGUsq} %{WORD:OZucUvNbqb}" 
| sort sTyuHhEoGUsq 
| sort OZucUvNbqb DESC
| rename OZucUvNbqb as message 
| lookup join message_types_lookup on message 
| limit 14037 
| enrich languages_policy on type 
| sort language_name DESC 
| mv_expand `type` 
| rename `type` AS EhWPxhBDo, sTyuHhEoGUsq AS `EhWPxhBDo`, `message` AS `fKlJNGHdRX`
| rename fKlJNGHdRX as message 
| lookup join message_types_lookup on message
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_state_exception",
                "reason": "Found 1 problem\nline 1:774: Plan [Join[LEFT,[message{r}#57],[message{r}#57],[message{f}#70]]] optimized incorrectly due to missing references from left hand side [message{r}#57]"
            }
        ],
        "type": "illegal_state_exception",
        "reason": "Found 1 problem\nline 1:774: Plan [Join[LEFT,[message{r}#57],[message{r}#57],[message{f}#70]]] optimized incorrectly due to missing references from left hand side [message{r}#57]"
    },
    "status": 500
}
```

See https://github.com/elastic/elasticsearch/issues/131508

### LINKED ISSUE #132634: ESQL: double LOOKUP JOIN/ENRICH on the same policy + STATS VALUES returns wrong values
Bug found on current main, not yet confirmed whether it was present in earlier versions.

Local reproducer:
```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/enrich_idx/_doc" -XPOST -d '{
  "x":1, "y":11
}'

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/enrich_idx/_doc" -XPOST -d '{
  "x":2, "y":22
}'

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_enrich/policy/my-policy" -XPUT -d'
{                
  "match": {
    "indices": "enrich_idx",
    "match_field": "x",    
    "enrich_fields": ["y"]       
  }
}'

curl -u elastic-admin:elastic-password -H "Content-Type: application/json" "127.0.0.1:9200/_enrich/policy/my-policy/_execute?wait_for_completion=true" -XPOST

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{
  "query": "row a = 1, b = 2 | enrich my-policy on a with ay = y | enrich my-policy on b with by = y | stats count(*), avalues = values(ay), bvalues = values(`by`)"
}'
   count(*)    |    avalues    |    bvalues    
---------------+---------------+---------------
1              |11             |11    
```
The last `bvalues` entry should be `22`, not `11` - `bvalues` somehow uses the value from the first `ENRICH`, not from the second `ENRICH`, contrary to how `bvalues` is defined.

Without the `STATS` command, the query provides correct results. Also, first plugging the enrich fields into another expression and using that in `VALUES` seems to work correctly:
```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{
  "query": "row a = 1, b = 2 | enrich my-policy on a with ay = y | enrich my-policy on b with by = y | eval ay = ay::keyword, `by` = `by`::keyword | stats count(*), avalues = values(ay), bvalues = values(`by`)"
}'
   count(*)    |    avalues    |    bvalues    
---------------+---------------+---------------
1              |11             |22  
```

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/131509
Fix https://github.com/elastic/elasticsearch/issues/132634

Make `Attribute#equals` and `Alias#equals` respect the `NameId`s, so that plan transformations that happen to replace an attribute/alias by one that only differs by id, we still actually update the plan rather than keeping the old plan object.

This requires a bunch of boilerplate-y test updates. I'll point to the non-boilerplate changes in comments below.

### CODE REVIEW

**Review by alex-spies — COMMENTED** [review]
We probably also want to update the hashCode implementations, although this will mostly lead to a reduction of collisions.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Alias.java
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Alias.java:1]: The changes to Alias, Attribute and the other classes inside the `expression` package are non-boilerplate-y and deserve deep review.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/enrich.csv-spec
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/enrich.csv-spec:1]: The added spec tests correspond to the bugs this fixes.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failure.java [hunk 1]
```diff
@@ -51,6 +58,16 @@ public boolean equals(Object obj) {
...
+
+        // When deduplicating failures, it's important to ignore the NameIds of UnresolvedAttributes.
+        // Otherwise, two failures will be emitted to the user for e.g.
+        // `FROM test | STATS max(unknown) by unknown` because the two `unknown` attributes will have differentNameIds - even though they
+        // clearly refer to the same problem.
+        if (node instanceof UnresolvedAttribute ua
+            && other.node instanceof UnresolvedAttribute otherUa
+            && ua.getClass() == otherUa.getClass()) {
+            return ua.nonSemanticEquals(otherUa);
+        }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failure.java:68]: This is not a boilerplate change. The old behavior is intentionally kept intact for the Failure class (otherwise, we genuinely fail a test).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failures.java [hunk 2]
```diff
@@ -7,16 +7,16 @@
...
+import java.util.Set;
 
 /**
- * Glorified list for managing {@link Failure}s.
+ * Glorified set for managing {@link Failure}s.
  */
 public class Failures {
 
-    private final Collection<Failure> failures;
+    private final Set<Failure> failures;
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failures.java:19]: Small cleanup

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/UnsupportedAttribute.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/UnsupportedAttribute.java:1]: Non-boilerplate changes in here.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/AliasTests.java [hunk 3]
```diff
@@ -7,24 +7,16 @@
...
 import org.elasticsearch.xpack.esql.expression.function.ReferenceAttributeTests;
-import org.elasticsearch.xpack.esql.io.stream.PlanStreamInput;
-import org.elasticsearch.xpack.esql.io.stream.PlanStreamOutput;
 
 import java.io.IOException;
 
-import static org.hamcrest.Matchers.equalTo;
-
-public class AliasTests extends AbstractWireTestCase<Alias> {
+public class AliasTests extends AbstractExpressionSerializationTests<Alias> {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/AliasTests.java]: I cleaned up some of the serialization tests.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plan/AbstractNodeSerializationTests.java [hunk 4]
```diff
@@ -57,7 +59,12 @@ protected T copyInstance(T instance, TransportVersion version) throws IOExceptio
             getNamedWriteableRegistry(),
             (out, v) -> new PlanStreamOutput(out, configuration()).writeNamedWriteable(v),
             in -> {
-                PlanStreamInput pin = new PlanStreamInput(in, in.namedWriteableRegistry(), configuration());
+                PlanStreamInput pin = new PlanStreamInput(
+                    in,
+                    in.namedWriteableRegistry(),
+                    configuration(),
+                    new SerializationTestUtils.TestNameIdMapper()
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plan/AbstractNodeSerializationTests.java:66]: This ensures we correctly check the name ids in serialization tests, but don't have to patch them up in every equality check; instead, we deserialize ids to the original ones in tests.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:1]: Non-boilerplate changes in here: matchers that ignore ids so that tests don't become crazy to write.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Alias.java [hunk 5]
```diff
@@ -147,4 +152,20 @@ public String nodeString() {
...
+
+    @Override
+    @SuppressWarnings("checkstyle:EqualsHashCode")// equals is implemented in parent. See innerEquals instead
+    public int hashCode() {
+        return Objects.hash(super.hashCode(), id());
+    }
+
+    /**
+     * Compared to e.g. {@link UnresolvedAttribute}, the id is part of equality for Alias because the {@link ReferenceAttribute} created
+     * by {@link #toAttribute()} uses it.
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Alias.java]:
```suggestion
     * The id is part of equality for Alias because the {@link ReferenceAttribute} created
     * by {@link #toAttribute()} uses it.
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 6]
```diff
@@ -1593,7 +1593,16 @@ public enum Cap {
          * Fix management of plans with no columns
          * https://github.com/elastic/elasticsearch/issues/120272
          */
-        FIX_NO_COLUMNS;
+        FIX_NO_COLUMNS,
+
+        /**
+         * Fix attribute equality to respect the name id of the attribute.
+         */
+        ATTRIBUTE_EQUALS_RESPECTS_NAME_ID,
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:1543]: Move this up, we should avoid adding capabilities to the end of the enum.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 7]
```diff
@@ -1994,13 +1994,15 @@ private Expression createIfDoesNotAlreadyExist(
                 resolvedField,
                 true
             );
-            int existingIndex = unionFieldAttributes.indexOf(unionFieldAttribute);
+            var nonSemanticUnionFieldAttribute = unionFieldAttribute.ignoreId();
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1995]: Interesting idea!

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/EmptyAttribute.java [hunk 8]
```diff
@@ -78,13 +79,22 @@ protected NodeInfo<? extends Expression> info() {
...
     @Override
-    @SuppressWarnings("checkstyle:EqualsHashCode")// equals is implemented in parent. See innerEquals instead
-    public int hashCode() {
+    public int nonSemanticHashCode() {
         return EmptyAttribute.class.hashCode();
     }
 
     @Override
-    protected boolean innerEquals(Object o) {
+    public boolean nonSemanticEquals(Attribute o) {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/EmptyAttribute.java]: Shouldn't this be `return o instanceof EmptyAttribute;`?

I know it's used only in two places now, and both have a check on the class, but it's error prone, and it violates the contract defined for Attribute.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequest.java [hunk 9]
```diff
@@ -87,7 +94,10 @@ final class DataNodeRequest extends AbstractTransportRequest implements IndicesR
         this.clusterAlias = in.readString();
         this.shardIds = in.readCollectionAsList(ShardId::new);
         this.aliasFilters = in.readMap(Index::new, AliasFilter::readFrom);
-        this.plan = new PlanStreamInput(in, in.namedWriteableRegistry(), configuration).readNamedWriteable(PhysicalPlan.class);
+        PlanStreamInput pin = idMapper == null
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequest.java]: Ternary could move into constructor parameter, more concise.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 10]
```diff
@@ -152,24 +201,50 @@ public int semanticHash() {
...
         return clone(Source.EMPTY, qualifier(), name(), dataType(), nullability, id(), synthetic());
     }
 
+    /**
+     * Compares all fields except the id. Useful when looking for attributes that are the same except for their origin, or when we create
+     * new attributes based on existing ones and want to avoid duplicates.
+     * <p>
+     * Does not perform the usual instance and class equality checks, those are already done in {@link NamedExpression#equals(Object)}
+     */
+    public boolean nonSemanticEquals(Attribute other) {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: I'd really like to have a better name for this method, maybe just `equalsIgnoringIds()`, but there could definitely be better alternatives.
That "non-semantic" doesn't really clarify the meaning of the method.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 11]
```diff
@@ -152,24 +201,50 @@ public int semanticHash() {
...
+     */
+    public int nonSemanticHashCode() {
+        return Objects.hash(super.hashCode(), qualifier, nullability);
+    }
+
+    /**
+     * Inheritors should generally only override {@link #nonSemanticHashCode()}.
+     */
     @Override
     @SuppressWarnings("checkstyle:EqualsHashCode")// equals is implemented in parent. See innerEquals instead
```
Comment (luigidellaquila) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: I wonder if it would make sense to have an `innerHashCode()` and maintain the symmetry.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 12]
```diff
@@ -152,24 +201,50 @@ public int semanticHash() {
...
+     * Because the name alone is not sufficient to identify an attribute (two different relations can have the same attribute name),
+     * we also have an id that is used in equality checks and hashing.
+     * <p>
+     * Inheritors should generally only override {@link #nonSemanticEquals(Attribute)}.
+     */
     @Override
     protected boolean innerEquals(Object o) {
         var other = (Attribute) o;
-        return super.innerEquals(other) && Objects.equals(qualifier, other.qualifier) && Objects.equals(nullability, other.nullability);
+        return semanticEquals(other) && nonSemanticEquals(other);
```
Comment (luigidellaquila) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Is this really needed?

I expected something like

```
    @Override
    protected boolean innerEquals(Object o) {
        var other = (Attribute) o;
        return other.id().equals(id()) && nonSemanticEquals(other);
    }
```

IMHO `semanticEquals()` should be kept completely separated from all this, and used only in specific rules to do expression manipulation.

Comment (luigidellaquila) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Thinking more (but I could be wrong, I haven't tested it), can't we just get rid of this `innerEquals()`, replace it with `equalsIgnoringIds()` in NamedExpression, and extend `equals()/hashCode()` here? It would make things much easier to follow.

**Review by luigidellaquila — COMMENTED** [review]
Thanks @alex-spies, I left a first round of comments.
My main concern is on the proliferation of equality methods (we have _four_ now!), but the general approach seems correct

**Review by luigidellaquila — COMMENTED** [review]
Thanks @alex-spies, I left a first round of comments.
My main concern is on the proliferation of equality methods (we have _four_ now!), but the general approach seems correct

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 13]
```diff
@@ -32,6 +32,55 @@
  * The rest are not as they are not part of the projection and thus are not part of the derived table.
  */
 public abstract class Attribute extends NamedExpression {
+    /**
+     * A wrapper class where equality of the contained attribute ignores the {@link Attribute#id()}. Useful when we want to create new
+     * attributes and want to avoid duplicates - we can create a set of {@link NonSemanticAttribute}s.
+     */
+    public class NonSemanticAttribute {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Is it intentionally not static? Also could it be a record to simplify construction and have a free toString while still having custom equals and hash code?

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 14]
```diff
@@ -32,6 +32,55 @@
  * The rest are not as they are not part of the projection and thus are not part of the derived table.
  */
 public abstract class Attribute extends NamedExpression {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java:41]: The attribute hierarchy is getting scarier for me.
This is probably outside of this change
I wonder if it is worth converting it to a flat record with a type field and a number of factories?

Something like:
```
Attribute.EMPTY
Attribute.unresolved(..)
Attribute.unsupported(..)
Attribute.metadata(..)
Attribute.field(..)
...
```

this will have the super set of all fields needed for everything but will be much easier to check equality and type (opposed to instanceof). Updating serialization accordingly might be a chllenge.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java (hunk 6 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:1543]: Folks are adding caps at the end all the time; to get some kind of consistency, we can either have a dummy capability at the end and tell folks "no cap below this, pls!" (which they'll hopefully respect); or we can go with this attempt here, where I'm instructing folks to just add caps with commas (no semicolon on the last cap) to minimize merge conflicts.

This currently goes with the latter; not sure which is better, but in any case, the convention needs to be written out in a comment at least (which this PR does).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequest.java (hunk 9 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequest.java]: I'll move the ternary into the `PlanStreamInput` constructor so that the assignment of the name id mapper is closer to where it matters and this code here can just pass the `idMapper` to the `PlanStreamInput` c'tor. I hope that's in line with what you had in mind :)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:1543]: FWIW, I like this solution. Having caps in order makes sense to understand what was created first, and it will make our life easier when we decide to prune some of them.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 15]
```diff
@@ -32,6 +32,55 @@
...
+     * A wrapper class where equality of the contained attribute ignores the {@link Attribute#id()}. Useful when we want to create new
+     * attributes and want to avoid duplicates - we can create a set of {@link NonSemanticAttribute}s.
+     */
+    public class NonSemanticAttribute {
+        private Attribute attribute;
+
+        public NonSemanticAttribute(Attribute attribute) {
+            if (attribute == null) {
+                throw new IllegalStateException("Attribute inside NonSemanticAttribute cannot be null");
+            }
```
Comment (bpintea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: `Check.notNull(attribute)` could be of use.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 16]
```diff
@@ -32,6 +32,55 @@
...
+            if (o == null || getClass() != o.getClass()) {
+                return false;
+            }
+
+            Attribute otherAttribute = ((NonSemanticAttribute) o).attribute;
+
+            if (attribute == otherAttribute) {
+                return true;
+            }
+            if (otherAttribute == null || attribute.getClass() != otherAttribute.getClass()) {
```
Comment (bpintea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Can `otherAttribute` be null?

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/NameId.java [hunk 17]
```diff
@@ -31,6 +31,14 @@ public NameId() {
         this.id = COUNTER.incrementAndGet();
     }
 
+    /**
+     * Absolutely only intended for tests, esp. to deal with serialization. Never use in production as it breaks the
```
Comment (bpintea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/NameId.java:35]: Could be mark as `@Deprecated`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failure.java [hunk 18]
```diff
@@ -51,6 +58,16 @@ public boolean equals(Object obj) {
         }
 
         Failure other = (Failure) obj;
+
+        // When deduplicating failures, it's important to ignore the NameIds of UnresolvedAttributes.
+        // Otherwise, two failures will be emitted to the user for e.g.
+        // `FROM test | STATS max(unknown) by unknown` because the two `unknown` attributes will have differentNameIds - even though they
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failure.java:64]: I'm not sure if we want this deduplication. I'd find it useful in a large query where I update the name of a field to be listed where there are old instances. "Usually" compilers list all instances (javac does it).

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 19]
```diff
@@ -32,6 +32,55 @@
  * The rest are not as they are not part of the projection and thus are not part of the derived table.
  */
 public abstract class Attribute extends NamedExpression {
+    /**
+     * A wrapper class where equality of the contained attribute ignores the {@link Attribute#id()}. Useful when we want to create new
+     * attributes and want to avoid duplicates - we can create a set of {@link NonSemanticAttribute}s.
+     */
+    public class NonSemanticAttribute {
+        private Attribute attribute;
```
Comment (bpintea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: "Field 'attribute' may be 'final'", but I guess Ievgen's suggestion for a record is probably better.

Comment (bpintea) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: In any case, this class isn't really an attribute: since the class isn't static, should it rather be a `NonSemanticWrapper`?

**Review by bpintea — COMMENTED** [review]
Had a first stab and left some coments.

But generally I'd echo other's comments about the hierarchy. The construct with `equals` / `innerEquals` / `semanticEquals` and `nonSemanticEquals` is a bit tricky to follow & maintain.
I'm a bit surprised that flipping `Alias` and `Attribute`'s hierarchy from excluding the `NameId` field's value in `equals` & `hash` to including it doesn't break more things. But since this is the case, could the refactoring not be simplified by simply adjusting the `equals` & `hash` to be "ordinary" (i.e. just consider all the members) and then have `semanticEquals` and/or `equals` & co be overridden where needed? (Possibly as low as the NamedExpression?)

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 20]
```diff
@@ -32,6 +32,55 @@
  * The rest are not as they are not part of the projection and thus are not part of the derived table.
  */
 public abstract class Attribute extends NamedExpression {
+    /**
+     * A wrapper class where equality of the contained attribute ignores the {@link Attribute#id()}. Useful when we want to create new
```
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java:43]: Maybe a more non-QL-developer oriented Javadoc would help some more?
Something around the wording "semantic"/(exact) "identity": what "semantic" means in the context of an Attribute for example and what non-semantic means (it sucks that I _think_ we cannot rename Attribute to something else that "pairs" with NonSemanticAttribute; I can't think of a better name for `NonSemanticAttribute` either).
I am mentioning this because in your current description you say "want to avoid duplicates"; I think it would be better worded as "want to avoid semantically-equivalent copies". "Duplication" goes back to the definition of `equals`.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 21]
```diff
@@ -32,6 +32,55 @@
...
+     * attributes and want to avoid duplicates - we can create a set of {@link NonSemanticAttribute}s.
+     */
+    public class NonSemanticAttribute {
+        private Attribute attribute;
+
+        public NonSemanticAttribute(Attribute attribute) {
```
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: How about making the contructor `private` and only accessible via `ignoreId()` and maybe give it a better(?) name to this method - `nonSemanticAttribute()`.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 12 above)
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Because we introduce this notion of different `equals` methods for Attributes where the only difference is the `id` equality being considered or not, can we enforce this aspect in generic test that scans all `Attribute` sub-classes (similar to what `EsqlNodeSubclassTests` does and checks that `semanticEquals` + `id().equals(other.id())` is the same as `nonSemanticEquals()`?

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Expression.java [hunk 22]
```diff
@@ -180,10 +180,26 @@ protected Expression canonicalize() {
         return replaceChildrenSameSize(canonicalChildren);
     }
 
+    /**
+     * Whether this expression means the same as {@code other}, even if they are not exactly equal.
+     * For example, {@code a + b} and {@code b + a} are not equal, but they are semantically equal.
+     * <p>
+     * If two expressions are equal, they are also semantically equal, but the reverse is generally not true.
```
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Expression.java:187]: A part of this Javadoc should also be used in `Attribute`'s Javadoc. My 2c.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/UnresolvedAttribute.java [hunk 23]
```diff
@@ -116,6 +112,12 @@ protected Attribute clone(
         return this;
     }
 
+    // Cannot just use the super method because that requires a data type.
+    @Override
+    public UnresolvedAttribute withId(NameId id) {
```
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/UnresolvedAttribute.java:122]: Is this `withId` really needed (I know it existed before in other classes)?
I searched the code and found two major uses:
- `withId(new NameId())`
- `withId(some_other_id)` in Tests.

If possible, and if I'm not missing something, the second use could be limited to tests only, and using the `withId(new NameId())` should in fact be a constructor call.

**Review by astefan — COMMENTED** [review]
It's looking good @alex-spies. Thank you for being patient and going through so many tricky changes.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/EmptyAttribute.java (hunk 8 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/EmptyAttribute.java]: I made this public, so the instanceof check makes sense. (Previously, you'd never call this directly, so just returning true was more okay.)

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 13 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Thanks, I think I wanted it to be non-static and then changed my mind :D turned into a record.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 14 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java:41]: Hm, maybe that's possible, but will mess with many `instanceOf` checks that we rely on. Let's consider this for another time.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 12 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Ended up getting rid of `equalsIgnoringIds`; instead, solved this inside `NamedExpression` by giving the equals/hashCode implementations an `ignoreId` parameter. That should hopefully be clearer now.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 15 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: C'tor was removed and replaced by a method on `Attribute`, instead, which ensures non-nullity.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 16 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Good point! Currently this has been replaced by a call to `Attribute#equals`, though (with `ignoreIds = true`), so this comment no longer applies.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failure.java (hunk 18 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/common/Failure.java:64]: Our verification stops at the first command that doesn't resolve, so we would have to do more than just use stricter equality to achieve what you describe. In practice, ignoring IDs here only really applies to edge-case-y `STATS` queries, I think. Arguably, it'd be more correct to partially resolve them by ensuring that both `unknown`s in `STATS max(unknown) BY unknown` have the same id, which is in line with your comment.

But we can revisit this in the future, to not increase this PR's for now. At least it's explicit now and using the stricter notion of equality is an easy change.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 19 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: `NonSemanticWrapper` it is!

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 21 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Done!

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 19 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Ok, `IdIgnoringWrapper`, because Andrei pointed out that "semantic" is not a clear-cut term for new ESQL hackers.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 20 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java:43]: Good point. I tried to clarify a bit better and with less QL-y words; also renamed to the more straight-forward `IdIgnoringWrapper`.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 12 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: I simplified the notion of `equals`, so that there's only an `innerEquals` to override, rather than `semanticEquals` + `nonSemanticEquals` (and their confusing relationship to `innerEquals`).

However, there's still behavior to test; I'll see to it that the tests for named expressions check that equality that ignores the id is correct.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/UnresolvedAttribute.java (hunk 23 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/UnresolvedAttribute.java:122]: We have `with...` methods for most of the elements that comprise an attribute. I think they are useful, but if we want to get rid of them, we should remove all of them or none, and probably in another PR to keep the scope contained.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java (hunk 12 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java]: Tests (updated and) added

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!

**Review by astefan — APPROVED** [review]
LGTM. Awesome!

**Review by bpintea — APPROVED** [review]
👏

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/136950)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
