### PR TITLE
ingest: support default pipeline through an alias

### LINKED ISSUE #35817: [Ingest] default_pipeline is not working when the index is referred by its alias
**Elasticsearch version** : 6.5.0

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

1. Create a pipeline that will modify `_index` field of the index.
```
PUT _ingest/pipeline/index_routing
{
    "description" : "route document to proper index and shard",
    "processors" : [
      {
        "date_index_name" : {
          "field" : "posted_date",
          "date_formats" : [
            "ISO8601"
          ],
          "date_rounding" : "y",
          "index_name_format" : "yyyy",
          "index_name_prefix" : "search-"
        }
      }
    ]
}
```
2. Create a index with default_pipeline
```
PUT test_index
{
  "settings": {
    "default_pipeline": "plurk-index-routing"
  },
  "aliases": {
    "my_index_alias": {}
  }
}
```
3. Create destination index
```
PUT search-2018
{}
```
4. Index something
```
PUT my_index_alias/_doc/first_doc
{
  "posted_date": "2018-01-01T00:00:00"
}
```

Then we can find that the document has been indexed into `test_index` instead of `search-2018`.

### PR DESCRIPTION
**Pull request by jakelandis**
This commit allows writes that go through an alias to use the default 
pipeline defined on the backing index.

Fixes #35817

### CODE REVIEW

**Comment by original-brownbear** [comment]
@jakelandis seems there is some checkstyle issue here

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 1]
```diff
@@ -203,13 +205,22 @@ private void executeIngestAndBulk(Task task, final BulkRequest bulkRequest, fina
         final ActionListener<BulkResponse> listener, final AtomicArray<BulkItemResponse> responses,
         Map<String, IndexNotFoundException> indicesThatCannotBeCreated) {
         boolean hasIndexRequestsWithPipelines = false;
-        ImmutableOpenMap<String, IndexMetaData> indicesMetaData = clusterService.state().getMetaData().indices();
+        final ClusterState state = clusterService.state();
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: NIT: You can shorten the logic a little by caching the metadata `clusterService.state().getMetaData()` instead of getting it from the state twice.

**Review by original-brownbear — COMMENTED** [review]
One nit, otherwise looks ok except for the broken checkstyle

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java (hunk 1 above)
Comment (jakelandis) [reply server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: done.

**Comment by jakelandis** [comment]
@original-brownbear - thanks for the review! checkstyle and nit fixed on https://github.com/elastic/elasticsearch/pull/36231/commits/045395659cdc14decd591facf50c63073accfffd

**Review by original-brownbear — APPROVED** [review]
LGTM :)

**Comment by jakelandis** [comment]
@elasticmachine run the gradle build tests 2
