### PR TITLE
Fix SnapshotBasedIndexRecoveryIT#testNodeDisconnectsDoNotOverAccountRecoveredBytes

### LINKED ISSUE #90665: [CI] SnapshotBasedIndexRecoveryIT testNodeDisconnectsDoNotOverAccountRecoveredBytes failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/n2rdnntuvhw64/tests/:x-pack:plugin:snapshot-based-recoveries:internalClusterTest/org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT/testNodeDisconnectsDoNotOverAccountRecoveredBytes

**Reproduction line:**
`./gradlew ':x-pack:plugin:snapshot-based-recoveries:internalClusterTest' --tests "org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT.testNodeDisconnectsDoNotOverAccountRecoveredBytes" -Dtests.seed=2725E4BEF73A48D3 -Dtests.locale=sr-Latn -Dtests.timezone=Turkey -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.SnapshotBasedIndexRecoveryIT&tests.test=testNodeDisconnectsDoNotOverAccountRecoveredBytes

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([2725E4BEF73A48D3]:0)

```

### PR DESCRIPTION
**Pull request by fcofdez**
The clock used to check for timeouts does not provide enough granularity, and sometimes the RESTORE_FILE_FROM_SNAPSHOT is retried while the test expects to fail right away. 

This commit configures the nodes with a timeout of 0, effectively configuring it to avoid retrying 
recovery requests.

Closes #90665

### CODE REVIEW

File: x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java [hunk 1]
```diff
@@ -1255,7 +1256,10 @@ public void testRecoveryRetryKeepsTheGrantedSnapshotFileDownloadPermit() throws
         );
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/90665")
+    @TestLogging(
```
Comment (kingherc) [inline x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java:1259]: Is this just in case that another error re-appears and we'd like to check the trace log?

Comment (fcofdez) [reply x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java:1259]: Yes, I'm 99% sure that this should fix the issue, but in case the error happens again we would have more information to fix it.

Comment (kingherc) [reply x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java:1259]: I wonder if it will produce much more unnecessary output that we'll needlessly keep. Do you think it'd be a good idea to make a issue/reminder to remove this after a couple of months of no problems?

**Review by kingherc — APPROVED** [review]
LGTM. Made one comment on the necessity of keeping the trace logs in the future if they will not be needed anymore.

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Review by henningandersen — APPROVED** [review]
LGTM2.

I wonder if it is better to drop the logging now and add it in case it should reappear? Given your 99% certainty that seems like the right thing to do.
