### PR TITLE
[TESTS] Disable specific locales for RestrictedTrustManagerTest

### LINKED ISSUE #33081: [CI] RestrictedTrustManagerTests fails
```
05:21:48   1> [2561-08-23T01:21:48,454][INFO ][o.e.x.c.s.RestrictedTrustManagerTests] [testTrustsExplicitCertificateName] after test
05:21:48 FAILURE 0.02s J3 | RestrictedTrustManagerTests.testTrustsExplicitCertificateName <<< FAILURES!
05:21:48    > Throwable #1: java.lang.AssertionError: 
05:21:48    > Expected: matches pattern .* does not match the trusted names \[.*\Qnode1.cluster2.elasticsearch\E.*
05:21:48    >      but: was "PKIX path validation failed: java.security.cert.CertPathValidatorException: Could not validate certificate: certificate expired on 20450904132213GMT+00:00"
05:21:48    > 	at __randomizedtesting.SeedInfo.seed([ABE170715C771857:FEEF70CFF99E93A2]:0)
05:21:48    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
05:21:48    > 	at org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests.assertNotValid(RestrictedTrustManagerTests.java:175)
05:21:48    > 	at org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests.assertNotTrusted(RestrictedTrustManagerTests.java:166)
05:21:48    > 	at org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests.assertSingleClusterIsTrusted(RestrictedTrustManagerTests.java:148)
05:21:48    > 	at org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests.testTrustsExplicitCertificateName(RestrictedTrustManagerTests.java:99)
05:21:48    > 	at java.lang.Thread.run(Thread.java:748)
05:21:48   1> [2561-08-23T01:21:48,455][INFO ][o.e.x.c.s.RestrictedTrustManagerTests] [testThatDelegateTrustManagerIsRespected] before test
05:21:48   1> [2561-08-23T01:21:48,479][INFO ][o.e.x.c.s.RestrictedTrustManagerTests] [testThatDelegateTrustManagerIsRespected] after test
05:21:48 FAILURE 0.03s J3 | RestrictedTrustManagerTests.testThatDelegateTrustManagerIsRespected <<< FAILURES!
05:21:48    > Throwable #1: java.lang.AssertionError: Certificate CN=n6.c2 is not trusted - sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Could not validate certificate: certificate expired on 20450904132214GMT+00:00
05:21:48    > 	at __randomizedtesting.SeedInfo.seed([ABE170715C771857:6D94743E9D2E3D3C]:0)
05:21:48    > 	at org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests.assertTrusted(RestrictedTrustManagerTests.java:160)
05:21:48    > 	at org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests.testThatDelegateTrustManagerIsRespected(RestrictedTrustManagerTests.java:133)
05:21:48    > 	at java.lang.Thread.run(Thread.java:748)
05:21:48 Completed [161/187] on J3 in 0.15s, 4 tests, 4 failures <<< FAILURES!
```

logs:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/255/console

steps to reproduce
```
./gradlew :x-pack:plugin:core:test -Dtests.seed=ABE170715C771857 -Dtests.class=org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests -Dtests.method="testTrustWithRegexCertificateName" -Dtests.security.manager=true -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=America/Dominica -Dcompiler.java=10 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password

 ./gradlew :x-pack:plugin:core:test -Dtests.seed=ABE170715C771857 -Dtests.class=org.elasticsearch.xpack.core.ssl.RestrictedTrustManagerTests -Dtests.method="testThatDelegateTrustManagerIsRespected" -Dtests.security.manager=true -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=America/Dominica -Dcompiler.java=10 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
```

I was not able to reproduce it locally.

### PR DESCRIPTION
**Pull request by jkakavas**
Disable specific Thai and Japanese locales as Certificate expiration
validation fails due to the date parsing of BouncyCastle (that manifests
in a FIPS 140 JVM as this is the only place we use BouncyCastle).
Added the locale switching logic here instead of subclassing
ESTestCase as these are the only tests that fail for that local and
JVM combination.

Resolves #33081

### CODE REVIEW

**Comment by jkakavas** [comment]
Thanks @bizybot , I've updated the original issue with the anaysis and the link to the bug report upstream

**Comment by jkakavas** [comment]
jenkins please test this

**Comment by jkakavas** [comment]
jenkins test this please

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/RestrictedTrustManagerTests.java [hunk 1]
```diff
@@ -40,6 +46,34 @@
...
+            restoreLocale = Locale.getDefault();
+            Locale.setDefault(Locale.ENGLISH);
+        }
+    }
+
+    private static boolean isUnusableLocale() {
+        return inFipsJvm() && (Locale.getDefault().toLanguageTag().equals("th-TH")
+            || Locale.getDefault().toLanguageTag().equals("ja-JP-u-ca-japanese-x-lvariant-JP")
+            || Locale.getDefault().toLanguageTag().equals("th-TH-u-nu-thai-x-lvariant-TH"));
+    }
```
Comment (tvernum) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/RestrictedTrustManagerTests.java]: Those are _very_ specific. I trust you've done the analysis and that's exactly what we need?

**Review by tvernum — APPROVED** [review]
LGTM, but I did leave a question.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/RestrictedTrustManagerTests.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/RestrictedTrustManagerTests.java]: Yes, see https://github.com/elastic/elasticsearch/issues/33081 and https://github.com/bcgit/bc-java/issues/405

**Comment by jkakavas** [comment]
@bizybot do you have any additional concerns, or should I go ahead and merge this ?

**Review by bizybot — APPROVED** [review]
Thank you. LGTM.
