### PR TITLE
Subclass NIOFSDirectory instead of using FileSwitchDirectory

### LINKED ISSUE #37111: [CI] IndexShardIT.testShardHasMemoryBufferOnTranslogRecover failure
This reproduces on master:
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=9EC7D98FCA15BCE6 \
  -Dtests.class=org.elasticsearch.index.shard.IndexShardIT \
  -Dtests.method="testShardHasMemoryBufferOnTranslogRecover" \
  -Dtests.security.manager=true \
  -Dtests.locale=sv \
  -Dtests.timezone=Pacific/Auckland \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

The resulting error is:
```
ERROR   4.25s | IndexShardIT.testShardHasMemoryBufferOnTranslogRecover <<< FAILURES!
   > Throwable #1: [test/rCQ777wBRcmIfm1spp2jiA][[test][0]] IndexShardRecoveryException[failed to recover from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: NoSuchFileException[file "_0.cfs" is already pending delete];
   >    at __randomizedtesting.SeedInfo.seed([9EC7D98FCA15BCE6:42E398DA205C6200]:0)
   >    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:429)
   >    at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95)
   >    at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302)
   >    at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93)
   >    at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1657)
   >    at org.elasticsearch.index.shard.IndexShardIT.recoverShard(IndexShardIT.java:636)
   >    at org.elasticsearch.index.shard.IndexShardIT.testShardHasMemoryBufferOnTranslogRecover(IndexShardIT.java:560)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
   > Caused by: [test/rCQ777wBRcmIfm1spp2jiA][[test][0]] EngineCreationFailureException[failed to create engine]; nested: NoSuchFileException[file "_0.cfs" is already pending delete];
   >    at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:204)
   >    at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:165)
   >    at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
   >    at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1418)
   >    at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1372)
   >    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:424)
   >    ... 42 more
   > Caused by: java.nio.file.NoSuchFileException: file "_0.cfs" is already pending delete
   >    at org.apache.lucene.store.FSDirectory.deleteFile(FSDirectory.java:338)
   >    at org.apache.lucene.store.FileSwitchDirectory.deleteFile(FileSwitchDirectory.java:151)
   >    at org.apache.lucene.store.FilterDirectory.deleteFile(FilterDirectory.java:63)
   >    at org.elasticsearch.index.store.ByteSizeCachingDirectory.deleteFile(ByteSizeCachingDirectory.java:175)
   >    at org.apache.lucene.store.FilterDirectory.deleteFile(FilterDirectory.java:63)
   >    at org.elasticsearch.index.store.Store$StoreDirectory.deleteFile(Store.java:721)
   >    at org.elasticsearch.index.store.Store$StoreDirectory.deleteFile(Store.java:726)
   >    at org.apache.lucene.store.LockValidatingDirectoryWrapper.deleteFile(LockValidatingDirectoryWrapper.java:38)
   >    at org.apache.lucene.index.IndexFileDeleter.deleteFile(IndexFileDeleter.java:696)
   >    at org.apache.lucene.index.IndexFileDeleter.deleteFiles(IndexFileDeleter.java:690)
   >    at org.apache.lucene.index.IndexFileDeleter.<init>(IndexFileDeleter.java:238)
   >    at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:898)
   >    at org.elasticsearch.index.engine.InternalEngine$AssertingIndexWriter.<init>(InternalEngine.java:2580)
   >    at org.elasticsearch.index.engine.InternalEngine.createWriter(InternalEngine.java:2107)
   >    at org.elasticsearch.index.engine.InternalEngine.createWriter(InternalEngine.java:2097)
   >    at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199)
   >    ... 47 more
```

`FileSwitchDirectory` makes me think this is related to the addition of `hybridfs`, especially given that this only started failing yesterday afternoon, after #36668 was merged.

### PR DESCRIPTION
**Pull request by s1monw**
We don't want two FSDirectories manage pending deletes separately
and optimze file listing. This confuses IndexWriter and causes exceptions
when files are deleted twice but are pending for deletion. This change
move to using a NIOFS subclass that only delegates to MMAP for opening files
all metadata and pending deletes are managed on top.

Closes #37111
Relates to #36668

### CODE REVIEW

**Comment by s1monw** [comment]
@danielmitterdorfer can you include this if you backport #36668

File: server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java [hunk 1]
```diff
@@ -97,11 +92,31 @@ protected Directory newFSDirectory(Path location, LockFactory lockFactory) throw
                 // Use Lucene defaults
                 final FSDirectory primaryDirectory = FSDirectory.open(location, lockFactory);
                 if (primaryDirectory instanceof MMapDirectory) {
-                    return new FileSwitchDirectory(PRIMARY_EXTENSIONS, primaryDirectory, new NIOFSDirectory(location, lockFactory), true) {
+                    return new NIOFSDirectory(location, lockFactory) {
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java]: I think changing the class here requires also to change the assertion in `IndexStoreTests#assertHybridDirectory()`?

File: server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java [hunk 2]
```diff
@@ -97,11 +92,31 @@ protected Directory newFSDirectory(Path location, LockFactory lockFactory) throw
...
+                        public IndexInput openInput(String name, IOContext context) throws IOException {
+                            String extension = FileSwitchDirectory.getExtension(name);
+                            switch(extension) {
+                                // We are mmapping norms, docvalues as well as term dictionaries, all other files are served through NIOFS
+                                // this provides good random access performance and does not lead to page cache thrashing.
+                                case "nvd":
+                                case "dvd":
+                                case "tim":
+                                    ensureOpen();
+                                    ensureCanRead(name);
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java]: As far as I could see these checks are performed by `MMapDirectory#openInput()` as well so they're done twice now?

**Review by danielmitterdorfer — COMMENTED** [review]
Thanks for the fix. I left some comments.

**Comment by danielmitterdorfer** [comment]
> @danielmitterdorfer can you include this if you backport #36668

The change is already has already been backported in #37067 but I can take care of backporting this PR here to 6.x.

File: server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java (hunk 2 above)
Comment (s1monw) [reply server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java]: no we need to do these check on the outer directory since the inner doesn't know about hte pending deletes.

**Comment by s1monw** [comment]
@danielmitterdorfer I pushed changes

File: server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java [hunk 3]
```diff
@@ -139,4 +128,44 @@ private static Directory setPreload(Directory directory, Path location, LockFact
         }
         return directory;
     }
+
+    final static class HybridDirectory extends NIOFSDirectory {
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java]: Nit: the convention in our code base seems to be `static final` instead of `final static`.

**Review by danielmitterdorfer — APPROVED** [review]
I left a nit but apart from that LGTM. No need for another round. Thanks!

**Review by jpountz — APPROVED** [review]
Fishy!
