### PR TITLE
ESQL: Fix EsqlNodeSubclassTests

### LINKED ISSUE #114845: ESQL: deprecated private constructor affect EsqlNodeSubclass tests
### Description

As part of the https://github.com/elastic/elasticsearch/pull/110581, the previous longest constructors for ReferenceAttribute, MetadataAttribute and FieldAttribute were made private while still being used internally in nodeInfo methods.
This results in failures in EsqlSubclassNodeTests, as the number of parameters returned is higher than those found in the public constructor.
This was discovered in #113735 which added a few [workarounds](https://github.com/elastic/elasticsearch/pull/113735/files?diff=unified#diff-f922f9261ac69c0ef9e0225e433d4b771f9956423ff20bfc2a93839217458786R171
) that are suboptimal.

### PR DESCRIPTION
**Pull request by alex-spies**
- Fix https://github.com/elastic/elasticsearch/issues/114845
- **More importantly!** Fix EsqlNodeSubclassTests _so that they also test the Node subclasses in esql.core._

Due to a subtle mistake when copying the ql project into esql.core, the EsqlNodeSubclassTests did not run on subclasses in esql.core _at all_. This adds a fix to EsqlNodeSubclassTests.subclassesOf.

The classes ReferenceAttribute, FieldAttribute and MetadataAttribute did not respect the contract for Node.info because their info method did not use the longest public constructor - this is https://github.com/elastic/elasticsearch/issues/114845. This is fixed here as well.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/tree/EsqlNodeSubclassTests.java [hunk 1]
```diff
@@ -736,7 +729,7 @@ public static <T> Set<Class<? extends T>> subclassesOf(Class<T> clazz, Predicate
             // NIO FileSystem API is not used since it trips the SecurityManager
             // https://bugs.openjdk.java.net/browse/JDK-8160798
             // so iterate the jar "by hand"
-            if (path.endsWith(".jar") && path.contains("x-pack-ql")) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/tree/EsqlNodeSubclassTests.java:739]: This prevented the `esql.core` classes from being tested and allowed the contract breaches to slip through.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java [hunk 2]
```diff
@@ -174,18 +174,7 @@ public String getWriteableName() {
...
-            parentName,
-            name(),
-            dataType(),
-            field,
-            (String) null,
-            nullable(),
-            id(),
-            synthetic()
-        );
+        return NodeInfo.create(this, FieldAttribute::new, parentName, name(), field, nullable(), id(), synthetic());
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:177]: Neither the data type nor the qualifier are needed - the longest public c'tor doesn't use them and the `info` method shouldn't, either.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/MetadataAttribute.java [hunk 3]
```diff
@@ -147,26 +147,7 @@ protected String label() {
...
-            ),
-            name(),
-            dataType(),
-            (String) null,
-            nullable(),
-            id(),
-            synthetic(),
-            searchable
-        );
+        return NodeInfo.create(this, MetadataAttribute::new, name(), dataType(), nullable(), id(), synthetic(), searchable);
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/MetadataAttribute.java:150]: Removed just the qualifier that was always `null`. Same for `ReferenceAttribute`.

**Review by nik9000 — APPROVED** [review]
