### PR TITLE
Extend the date rounding logic to be conditional 

### LINKED ISSUE #58986: Unable to parse certain dates due to AM/PM issues
**Elasticsearch version**: 7.6+

**Description of the problem including expected versus actual behavior**:

I am not entirely sure what exactly the problem is, but there is some parsing logic with rounding dates up that causes parsing exceptions that do not look like they should be parsing exceptions.

I've written a unit test in `JavaDateMathParserTests.java` that reproduces the believed issue:

```
    public void testInvalidAMPM() {
        DateFormatter formatter = DateFormatter.forPattern("MM/dd/yyyy hh:mm a");
        DateMathParser parser = formatter.toDateMathParser();
        String date = "04/30/2020 05:48 PM";
        parser.parse(date, () -> 0, false, ZoneId.systemDefault());

        ElasticsearchParseException exception = expectThrows(ElasticsearchParseException.class,
            () -> parser.parse(date, () -> 0, true, ZoneId.systemDefault()));
    }
```

when `roundUpProperty` is set to true, parsing fails.

**Steps to reproduce**:

```
PUT my_index
{
  "mappings": {
      "properties": {
        "date": {
          "type": "date",
          "ignore_malformed" : false,
          "format" : "MM/dd/yyyy hh:mm a z"
        }
      }
    }
}

PUT my_index/_doc/1
{
  "date": "04/02/2020 07:48 AM CST"
}

GET my_index/_search
{
  "query": {
		"range": {
			"date": {
				"gte": "04/01/2020 07:48 AM CST",
				"lte": "04/20/2020 05:48 PM CST"
			}
		}
  }
}
```

might be related to #46654 cc @pgomulka

### LINKED ISSUE #89096: Bug in JavaDateFormatter when using DOY
### Elasticsearch Version

7.10.2

### Installed Plugins

_No response_

### Java Version

1.8

### OS Version

CentOS

### Problem Description

When defining a mapping that has a field that uses DOY format, data gets indexed correctly However, we run into issues when using the rounding parser. See steps below for a test case.

We believe the issue is related to this section of code:

https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java#L48-L59

### Steps to Reproduce

```
DELETE /test-doy-date

PUT /test-doy-date
{
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date",
        "format": "yyyy-DDD'T'HH:mm:ss.SSS||yyyy-DDD'T'HH:mm:ss.SSSX||yyyy-DDD'T'HH:mm:ss.n||yyyy-DDD'T'HH:mm:ss.nX||strict_date_optional_time||epoch_millis"
      }
    }
  }
}

POST _bulk
{ "index" : { "_index" : "test-doy-date", "_id" : "1" } }
{ "timestamp" : "2022-104T14:08:30.100" }
{ "index" : { "_index" : "test-doy-date", "_id" : "2" } }
{ "timestamp" : "2022-104T14:08:30.540Z" }
{ "index" : { "_index" : "test-doy-date", "_id" : "3" } }
{ "timestamp" : "2022-104T14:08:31.100111" }
{ "index" : { "_index" : "test-doy-date", "_id" : "4" } }
{ "timestamp" : "2022-104T14:08:31.234567Z" }

GET /test-doy-date/_search

GET /test-doy-date/_search
{
  "query": {
    "bool": {
      "filter": {
        "range": {
          "timestamp": {
            "gte": "2022-104T14:08:30.293",
            "lte": "2022-104T14:08:31.355",
            "format": "yyyy-DDD'T'HH:mm:ss.SSS"
          }
        }
      }
    }
  }
}
```

All steps complete without error except for the range filter, which outputs:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS]: [failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS]]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test-doy-date",
        "node" : "8QwQl8a5SvWteKZqObjW5g",
        "reason" : {
          "type" : "parse_exception",
          "reason" : "failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS]: [failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS]]",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS]",
            "caused_by" : {
              "type" : "date_time_parse_exception",
              "reason" : "date_time_parse_exception: Text '2022-104T14:08:31.355' could not be parsed: Conflict found: Field DayOfYear 1 differs from DayOfYear 104 derived from 2022-01-01",
              "caused_by" : {
                "type" : "date_time_exception",
                "reason" : "date_time_exception: Conflict found: Field DayOfYear 1 differs from DayOfYear 104 derived from 2022-01-01"
              }
            }
          }
        }
      }
    ]
  },
  "status" : 400
}
```

If we omit the explicit format in the filter, we instead get

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS||yyyy-DDD'T'HH:mm:ss.SSSX||yyyy-DDD'T'HH:mm:ss.n||yyyy-DDD'T'HH:mm:ss.nX||strict_date_optional_time||epoch_millis]: [failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS||yyyy-DDD'T'HH:mm:ss.SSSX||yyyy-DDD'T'HH:mm:ss.n||yyyy-DDD'T'HH:mm:ss.nX||strict_date_optional_time||epoch_millis]]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test-doy-date",
        "node" : "MB7SIp_pSrSComH5XlvIPQ",
        "reason" : {
          "type" : "parse_exception",
          "reason" : "failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS||yyyy-DDD'T'HH:mm:ss.SSSX||yyyy-DDD'T'HH:mm:ss.n||yyyy-DDD'T'HH:mm:ss.nX||strict_date_optional_time||epoch_millis]: [failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS||yyyy-DDD'T'HH:mm:ss.SSSX||yyyy-DDD'T'HH:mm:ss.n||yyyy-DDD'T'HH:mm:ss.nX||strict_date_optional_time||epoch_millis]]",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "failed to parse date field [2022-104T14:08:31.355] with format [yyyy-DDD'T'HH:mm:ss.SSS||yyyy-DDD'T'HH:mm:ss.SSSX||yyyy-DDD'T'HH:mm:ss.n||yyyy-DDD'T'HH:mm:ss.nX||strict_date_optional_time||epoch_millis]",
            "caused_by" : {
              "type" : "date_time_parse_exception",
              "reason" : "Failed to parse with all enclosed parsers"
            }
          }
        }
      }
    ]
  },
  "status" : 400
}
```

If we change `lte` to `lt` in the filter, we get a valid response:

```
{
  "took" : 9,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "test-doy-date",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 0.0,
        "_source" : {
          "timestamp" : "2022-104T14:08:31.100111"
        }
      },
      {
        "_index" : "test-doy-date",
        "_type" : "_doc",
        "_id" : "4",
        "_score" : 0.0,
        "_source" : {
          "timestamp" : "2022-104T14:08:31.234567Z"
        }
      },
      {
        "_index" : "test-doy-date",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 0.0,
        "_source" : {
          "timestamp" : "2022-104T14:08:30.540Z"
        }
      }
    ]
  }
}
```

If we use a custom format in the field mapping that does **not** use DOY, everything works fine.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by pgomulka**
Date rounding logic should take into account the fields that will be
parsed be a parser. If a parser has a DayOfYear field, the rounding logic
should not try to default DayOfMonth as it will conflict with DayOfYear

However the DateTimeFormatter does not have a public method to return
information of fields that will be parsed. The hacky workaround is
to rely on toString() implementation that will return a field info when
it was defined with textual pattern.

This commits introduced conditional logic for DayOfYear, ClockHourOfAMPM and HourOfAmPM

closes https://github.com/elastic/elasticsearch/issues/89096
closes https://github.com/elastic/elasticsearch/issues/58986

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 1]
```diff
@@ -22,10 +22,43 @@
...
+    * <code>
+    *  Value(MonthOfYear,2)'/'Value(DayOfMonth,2)'/'Value(YearOfEra,4,19,EXCEEDS_PAD)'
+    * 'Value(ClockHourOfAmPm,2)':'Value(MinuteOfHour,2)' 'Text(AmPmOfDay,SHORT)
+    * </code>
+    * and ChronoField.CLOCK_HOUR_OF_AMPM would have toString() ClockHourOfAmPm
+    * this allows the rounding logic to default CLOCK_HOUR_OF_AMPM field instead of HOUR_OF_DAY
+    * without this logic, the rounding would result in a conflict as HOUR_OF_DAY would be missing, but CLOCK_HOUR_OF_AMPM would be provided
+    */
+    private static final BiConsumer<DateTimeFormatterBuilder, DateTimeFormatter> DEFAULT_ROUND_UP = (builder, parser) -> {
+        if (parser.toString().contains(ChronoField.DAY_OF_YEAR.toString())) {
```
Comment (grcevski) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java:43]: Just a small comment here, since we might call this frequently enough and we don't know the cost of parser.toString(), do you mind extracting the parsed value into a local for the if conditionals?

**Review by grcevski — APPROVED** [review]
LGTM! I left one small remark about potential performance issue.

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 1 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java:43]: good idea

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by pgomulka** [comment]
I just realised that we possibly want to add a week based year defaulting too. So that we support `YYYY'W'ww[e]` ([ ] means parse optional day of week). It might be a bit artificial though, because I don't think `[]` syntax is commonly used (I might be mistaken..) and we don't have a named formatter with `day of week` within `startOptional/endOptional` 

assuming `[]` is rare and thus the only optional fields that could conflict are month of year and day of month, this logic could be simplified to just 
```
 if(parserAsString.contains(ChronoField.MONTH_OF_YEAR.toString()) ){
          builder.parseDefaulting(ChronoField.MONTH_OF_YEAR, 1L);
      }
      if(parserAsString.contains(ChronoField.DAY_OF_MONTH.toString()) ){
          builder.parseDefaulting(ChronoField.DAY_OF_MONTH, 1L);
      }
```
let me know what you think

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by grcevski** [comment]
> I just realised that we possibly want to add a week based year defaulting too. So that we support `YYYY'W'ww[e]` ([ ] means parse optional day of week). It might be a bit artificial though, because I don't think `[]` syntax is commonly used (I might be mistaken..) and we don't have a named formatter with `day of week` within `startOptional/endOptional`
> 
> assuming `[]` is rare and thus the only optional fields that could conflict are month of year and day of month, this logic could be simplified to just
> 
> ```
>  if(parserAsString.contains(ChronoField.MONTH_OF_YEAR.toString()) ){
>           builder.parseDefaulting(ChronoField.MONTH_OF_YEAR, 1L);
>       }
>       if(parserAsString.contains(ChronoField.DAY_OF_MONTH.toString()) ){
>           builder.parseDefaulting(ChronoField.DAY_OF_MONTH, 1L);
>       }
> ```
> 
> let me know what you think

I think that's a fair assumption. We don't have to make this more complicated at this point. I'd just put a comment that we don't handle the 'optional day of week' format, but adding day of month and month of year sound great!

**Comment by grcevski** [comment]
Since we are backporting to 7.17, can we please backport to 8.4.1 too, it's the current release.
