### PR TITLE
Fix DenseVectorFieldIndexTypeUpdateIT test

### LINKED ISSUE #132113: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=hnsw updateType=int4_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26231 / part1](https://gradle-enterprise.elastic.co/s/xnz4h5bmuravi)
- [elasticsearch-intake #26218 / part1](https://gradle-enterprise.elastic.co/s/iffzql2rdr7vs)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=int4_hnsw}" -Dtests.seed=9F21AB615CDED12D -Dtests.locale=pt-MO -Dtests.timezone=Asia/Damascus -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dhnsw%20updateType%3Dint4_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 4 hits but 5 was expected.  Total shards: 5 Successful shards: 5 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=hnsw updateType=int4_hnsw} (3.0% fail rate in 66 executions)
- [main] 2 failures in step part1 (10.5% fail rate in 19 executions)
- [main] 2 failures in pipeline elasticsearch-intake (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132115: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26232 / part1](https://gradle-enterprise.elastic.co/s/ozr7tgl4woavq)
- [elasticsearch-pull-request #83363 / part-1](https://gradle-enterprise.elastic.co/s/l55j6fnmqv4f2)
- [elasticsearch-pull-request #83343 / part-1](https://gradle-enterprise.elastic.co/s/skuzekybudm32)
- [elasticsearch-pull-request #83321 / part-1](https://gradle-enterprise.elastic.co/s/3bpjt2kmd32hy)
- [elasticsearch-pull-request #83312 / part-1](https://gradle-enterprise.elastic.co/s/mby47wugeiate)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk}" -Dtests.seed=F601CC0A5537300A -Dtests.locale=es-BZ -Dtests.timezone=Africa/Juba -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dhnsw%20updateType%3Dbbq_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 4 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 5 failures in test testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_hnsw} (7.4% fail rate in 68 executions)
- [main] 4 failures in step part-1 (8.3% fail rate in 48 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (8.5% fail rate in 47 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132116: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_flat updateType=int8_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26232 / part1](https://gradle-enterprise.elastic.co/s/ozr7tgl4woavq)
- [elasticsearch-intake #26204 / part1](https://gradle-enterprise.elastic.co/s/l5fgczx2ow4kk)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk}" -Dtests.seed=F601CC0A5537300A -Dtests.locale=es-BZ -Dtests.timezone=Africa/Juba -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_flat%20updateType%3Dint8_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 4 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int8_flat updateType=int8_hnsw} (2.9% fail rate in 68 executions)
- [main] 2 failures in step part1 (10.0% fail rate in 20 executions)
- [main] 2 failures in pipeline elasticsearch-intake (10.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132117: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=int8_hnsw} failing
**Build Scans:**
- [elasticsearch-pull-request #83399 / part-1](https://gradle-enterprise.elastic.co/s/enlqgdxanpyqq)
- [elasticsearch-intake #26235 / part1](https://gradle-enterprise.elastic.co/s/7pbb5tgnzmwek)
- [elasticsearch-intake #26192 / part1](https://gradle-enterprise.elastic.co/s/wluge4baulkwu)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_flat updateType=int8_hnsw}" -Dtests.seed=16D9B23857287FD8 -Dtests.locale=sc-IT -Dtests.timezone=NST -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dint8_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 6 hits but 8 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=int8_hnsw}
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=int8_hnsw} (4.3% fail rate in 70 executions)
- [main] 2 failures in step part1 (9.5% fail rate in 21 executions)
- [main] 2 failures in pipeline elasticsearch-intake (9.5% fail rate in 21 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132119: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=flat updateType=hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26239 / part1](https://gradle-enterprise.elastic.co/s/brpjtdh4rln6k)
- [elasticsearch-pull-request #83363 / part-1](https://gradle-enterprise.elastic.co/s/l55j6fnmqv4f2)
- [elasticsearch-pull-request #83347 / part-1](https://gradle-enterprise.elastic.co/s/573h4kfjnikfs)
- [elasticsearch-intake #26204 / part1](https://gradle-enterprise.elastic.co/s/l5fgczx2ow4kk)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=hnsw}" -Dtests.seed=FAB689F077978CBF -Dtests.locale=ar-SD -Dtests.timezone=Etc/GMT+5 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dflat%20updateType%3Dhnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 0 hits but 2 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 4 failures in test testDenseVectorMappingUpdate {initialType=flat updateType=hnsw} (5.4% fail rate in 74 executions)
- [main] 2 failures in step part1 (8.3% fail rate in 24 executions)
- [main] 2 failures in step part-1 (4.0% fail rate in 50 executions)
- [main] 2 failures in pipeline elasticsearch-intake (8.3% fail rate in 24 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (4.1% fail rate in 49 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132120: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=flat updateType=bbq_flat} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9689 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/stpxkdfq2dgwi)
- [elasticsearch-intake #26239 / part1](https://gradle-enterprise.elastic.co/s/brpjtdh4rln6k)
- [elasticsearch-pull-request #83300 / part-1](https://gradle-enterprise.elastic.co/s/qnza5fv3m3njq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=bbq_flat}" -Dtests.seed=FBAFE137FAD42590 -Dtests.locale=za-CN -Dtests.timezone=NZ -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dflat%20updateType%3Dbbq_flat%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 4 hits but 5 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=flat updateType=bbq_flat} (3.5% fail rate in 85 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132121: [CI] DenseVectorFieldIndexTypeUpdateIT class failing
**Build Scans:**
- [elasticsearch-periodic #9692 / release-tests](https://gradle-enterprise.elastic.co/s/x74j32zewiqly)
- [elasticsearch-pull-request #83565 / part-1](https://gradle-enterprise.elastic.co/s/x3whwd4kaduyo)
- [elasticsearch-pull-request #83567 / part-1](https://gradle-enterprise.elastic.co/s/f5bflwtfvkyfy)
- [elasticsearch-periodic-platform-support #9703 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/jwrehtkxoxjto)
- [elasticsearch-periodic-platform-support #9703 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/262dy3jppjrxo)
- [elasticsearch-intake #26285 / part1](https://gradle-enterprise.elastic.co/s/ip4uuk76rkz6k)
- [elasticsearch-pull-request #83523 / part-1-fips](https://gradle-enterprise.elastic.co/s/b2b6hgljj4t7m)
- [elasticsearch-pull-request #83541 / part-1](https://gradle-enterprise.elastic.co/s/ujo2tpyxppk4a)
- [elasticsearch-pull-request #83523 / part-1-fips](https://gradle-enterprise.elastic.co/s/3k47t27km5346)
- [elasticsearch-pull-request #83522 / part-1](https://gradle-enterprise.elastic.co/s/wlzw4r73qofs6)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk}" -Dtests.seed=64B8B80FE5A1527E -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=rwk-TZ -Dtests.timezone=America/Rio_Branco -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Unknown vector index options type [bbq_disk] for field [vector]
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 2 consecutive failures in step part-1
- [main] 2 consecutive failures in pipeline elasticsearch-pull-request
- [main] 78 failures in class org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT (30.7% fail rate in 254 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 23 failures in step part1 (33.8% fail rate in 68 executions)
- [main] 40 failures in step part-1 (32.5% fail rate in 123 executions)
- [main] 3 failures in step part-1-fips (37.5% fail rate in 8 executions)
- [main] 3 failures in pipeline elasticsearch-periodic (100.0% fail rate in 3 executions)
- [main] 23 failures in pipeline elasticsearch-intake (33.8% fail rate in 68 executions)
- [main] 41 failures in pipeline elasticsearch-pull-request (34.5% fail rate in 119 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132122: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9689 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/uvdnvzltegs5m)
- [elasticsearch-intake #26204 / part1](https://gradle-enterprise.elastic.co/s/l5fgczx2ow4kk)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=int4_hnsw}" -Dtests.seed=893146EAC25E6795 -Dtests.locale=be-TARASK -Dtests.timezone=Etc/GMT-8 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_flat%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 1 hits but 5 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_disk} (2.4% fail rate in 84 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132125: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_flat updateType=int4_flat} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9689 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/du5xycvjqw47g)
- [elasticsearch-pull-request #83409 / part-1](https://gradle-enterprise.elastic.co/s/gwmcp4jk5zn3y)
- [elasticsearch-pull-request #83290 / part-1](https://gradle-enterprise.elastic.co/s/2v3qaq7srmudy)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int8_flat updateType=int4_flat}" -Dtests.seed=EF38FFBA2705EF8 -Dtests.locale=pl-Latn-PL -Dtests.timezone=Etc/Zulu -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_flat%20updateType%3Dint4_flat%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 2 hits but 4 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=int8_flat updateType=int4_flat} (3.4% fail rate in 88 executions)
- [main] 2 failures in step part-1 (3.6% fail rate in 56 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (3.6% fail rate in 55 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132126: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=flat updateType=int8_hnsw} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9689 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/xt2v65dlzycqa)
- [elasticsearch-pull-request #83409 / part-1](https://gradle-enterprise.elastic.co/s/gwmcp4jk5zn3y)
- [elasticsearch-pull-request #83357 / part-1](https://gradle-enterprise.elastic.co/s/dhpur3ptcyoca)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=int8_hnsw}" -Dtests.seed=4213EC83CD7C633 -Dtests.locale=mai -Dtests.timezone=America/Inuvik -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dflat%20updateType%3Dint8_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 5 hits but 8 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=flat updateType=int8_hnsw} (3.4% fail rate in 89 executions)
- [main] 2 failures in step part-1 (3.6% fail rate in 56 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (3.6% fail rate in 55 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132127: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=bbq_disk updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-periodic #9678 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/gervg72n7b4hm)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)
- [elasticsearch-pull-request #83387 / part-1](https://gradle-enterprise.elastic.co/s/nueuwwpe25ajc)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=bbq_disk updateType=bbq_disk}" -Dtests.seed=15C47F807CA756A -Dtests.locale=ar-ER -Dtests.timezone=Pacific/Funafuti -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dbbq_disk%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 6 hits but 8 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=bbq_disk updateType=bbq_disk} (3.3% fail rate in 91 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132130: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=flat updateType=bbq_disk #2} failing
**Build Scans:**
- [elasticsearch-intake #26247 / part1](https://gradle-enterprise.elastic.co/s/xznviewcsov3o)
- [elasticsearch-intake #26245 / part1](https://gradle-enterprise.elastic.co/s/ixcibhm2sthum)
- [elasticsearch-intake #26242 / part1](https://gradle-enterprise.elastic.co/s/tf34ltzc6rybm)
- [elasticsearch-pull-request #83312 / part-1](https://gradle-enterprise.elastic.co/s/mby47wugeiate)
- [elasticsearch-pull-request #83299 / part-1](https://gradle-enterprise.elastic.co/s/7apv5nwzec3kq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=bbq_disk #2}" -Dtests.seed=794C8D576D552DAA -Dtests.locale=ka-GE -Dtests.timezone=US/Hawaii -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dflat%20updateType%3Dbbq_disk%20%232%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 5 hits but 7 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 consecutive failures in step part1
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 5 failures in test testDenseVectorMappingUpdate {initialType=flat updateType=bbq_disk #2} (4.9% fail rate in 103 executions)
- [main] 3 failures in step part1 (8.8% fail rate in 34 executions)
- [main] 2 failures in step part-1 (3.3% fail rate in 60 executions)
- [main] 3 failures in pipeline elasticsearch-intake (8.8% fail rate in 34 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (3.4% fail rate in 59 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132132: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_flat} failing
**Build Scans:**
- [elasticsearch-intake #26244 / part1](https://gradle-enterprise.elastic.co/s/d5jxxvsoz4c4c)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)
- [elasticsearch-pull-request #83353 / part-1](https://gradle-enterprise.elastic.co/s/r7kegrdbbmu5c)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_flat}" -Dtests.seed=69E6498A142EC9BB -Dtests.locale=jmc-Latn-TZ -Dtests.timezone=Africa/Khartoum -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dbbq_flat%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 7 hits but 8 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_flat} (3.0% fail rate in 100 executions)
- [main] 2 failures in step part1 (6.3% fail rate in 32 executions)
- [main] 2 failures in pipeline elasticsearch-intake (6.3% fail rate in 32 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132133: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_hnsw updateType=int4_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26245 / part1](https://gradle-enterprise.elastic.co/s/ixcibhm2sthum)
- [elasticsearch-pull-request #83409 / part-1](https://gradle-enterprise.elastic.co/s/gwmcp4jk5zn3y)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=bbq_disk #2}" -Dtests.seed=CC26A65EA21437E5 -Dtests.locale=kab-DZ -Dtests.timezone=America/Yellowknife -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_hnsw%20updateType%3Dint4_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 1 hits but 2 was expected.  Total shards: 4 Successful shards: 4 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int8_hnsw updateType=int4_hnsw} (2.0% fail rate in 102 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132134: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=bbq_flat updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-intake #26246 / part1](https://gradle-enterprise.elastic.co/s/inzhlahncz76w)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-pull-request #83404 / part-1](https://gradle-enterprise.elastic.co/s/oxdwixdc2d4ai)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=bbq_flat updateType=bbq_disk}" -Dtests.seed=CE3562A1F94508F3 -Dtests.locale=rof-TZ -Dtests.timezone=Indian/Maldives -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dbbq_flat%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 5 hits but 6 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=bbq_flat updateType=bbq_disk} (2.9% fail rate in 105 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132140: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=int4_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26255 / part1](https://gradle-enterprise.elastic.co/s/spldxjo3jem7s)
- [elasticsearch-intake #26257 / part1](https://gradle-enterprise.elastic.co/s/uur34h2j6uqxs)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_flat updateType=int4_hnsw}" -Dtests.seed=B5022211F1D1A1 -Dtests.locale=ff-Latn-MR -Dtests.timezone=Indian/Maldives -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dint4_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 1 hits but 2 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=int4_hnsw}
- [main] 2 consecutive failures in step part1
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=int4_hnsw} (1.6% fail rate in 123 executions)
- [main] 2 failures in step part1 (4.5% fail rate in 44 executions)
- [main] 2 failures in pipeline elasticsearch-intake (4.5% fail rate in 44 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132141: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26258 / part1](https://gradle-enterprise.elastic.co/s/wgtkldcxoana2)
- [elasticsearch-pull-request #83358 / part-1](https://gradle-enterprise.elastic.co/s/3hfyt77o6rqo4)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_hnsw}" -Dtests.seed=6B25125BA03AC4EA -Dtests.locale=nso-Latn-ZA -Dtests.timezone=Etc/GMT+0 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_flat%20updateType%3Dbbq_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 8 hits but 9 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_hnsw} (1.5% fail rate in 135 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132149: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=flat updateType=int4_hnsw} failing
**Build Scans:**
- [elasticsearch-periodic #9685 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/f5jc26fdqkp74)
- [elasticsearch-pull-request #83418 / part-1](https://gradle-enterprise.elastic.co/s/uis7qxntmznpo)
- [elasticsearch-periodic-platform-support #9689 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/uvdnvzltegs5m)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=int4_hnsw}" -Dtests.seed=751CB9F01F4F0D0B -Dtests.locale=fr-PM -Dtests.timezone=Asia/Damascus -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dflat%20updateType%3Dint4_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 4 hits but 7 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=flat updateType=int4_hnsw} (1.8% fail rate in 166 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132150: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=hnsw} failing
**Build Scans:**
- [elasticsearch-periodic #9685 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/f5jc26fdqkp74)
- [elasticsearch-intake #26218 / part1](https://gradle-enterprise.elastic.co/s/iffzql2rdr7vs)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=flat updateType=int4_hnsw}" -Dtests.seed=751CB9F01F4F0D0B -Dtests.locale=fr-PM -Dtests.timezone=Asia/Damascus -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dhnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 4 hits but 7 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=hnsw} (1.2% fail rate in 166 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132151: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_flat} failing
**Build Scans:**
- [elasticsearch-intake #26266 / part1](https://gradle-enterprise.elastic.co/s/ki3nrl3l3yfps)
- [elasticsearch-pull-request #83405 / part-1](https://gradle-enterprise.elastic.co/s/2aqlle7vinndc)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_flat}" -Dtests.seed=6AC5F67EF86041B6 -Dtests.locale=sr-Cyrl -Dtests.timezone=Africa/Kigali -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_flat%20updateType%3Dbbq_flat%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 1 hits but 2 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_flat} (1.1% fail rate in 175 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132152: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=bbq_hnsw updateType=bbq_disk #2} failing
**Build Scans:**
- [elasticsearch-intake #26266 / part1](https://gradle-enterprise.elastic.co/s/ki3nrl3l3yfps)
- [elasticsearch-pull-request #83409 / part-1](https://gradle-enterprise.elastic.co/s/gwmcp4jk5zn3y)
- [elasticsearch-pull-request #83347 / part-1](https://gradle-enterprise.elastic.co/s/573h4kfjnikfs)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int8_flat updateType=bbq_flat}" -Dtests.seed=6AC5F67EF86041B6 -Dtests.locale=sr-Cyrl -Dtests.timezone=Africa/Kigali -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dbbq_hnsw%20updateType%3Dbbq_disk%20%232%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 1 hits but 2 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=bbq_hnsw updateType=bbq_disk #2} (1.7% fail rate in 173 executions)
- [main] 2 failures in step part-1 (2.4% fail rate in 85 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.4% fail rate in 84 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132164: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=hnsw updateType=int8_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26275 / part1](https://gradle-enterprise.elastic.co/s/ccysjv5xchlos)
- [elasticsearch-pull-request #83428 / part-1](https://gradle-enterprise.elastic.co/s/c7vkjcaukrxru)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=int8_hnsw}" -Dtests.seed=A692943A26BFA4B7 -Dtests.locale=et-Latn-EE -Dtests.timezone=US/Central -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dhnsw%20updateType%3Dint8_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 4 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 failures in test testDenseVectorMappingUpdate {initialType=hnsw updateType=int8_hnsw} (1.4% fail rate in 214 executions)
- [main] 2 failures in step part1 (3.3% fail rate in 60 executions)
- [main] 2 failures in pipeline elasticsearch-intake (3.3% fail rate in 60 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132165: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-intake #26275 / part1](https://gradle-enterprise.elastic.co/s/ccysjv5xchlos)
- [elasticsearch-periodic #9685 / release-tests](https://gradle-enterprise.elastic.co/s/vndahjuqfqipe)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-pull-request #83409 / part-1](https://gradle-enterprise.elastic.co/s/gwmcp4jk5zn3y)
- [elasticsearch-intake #26232 / part1](https://gradle-enterprise.elastic.co/s/ozr7tgl4woavq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=int8_hnsw}" -Dtests.seed=A692943A26BFA4B7 -Dtests.locale=et-Latn-EE -Dtests.timezone=US/Central -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_hnsw%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 4 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 5 failures in test testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk} (2.3% fail rate in 214 executions)
- [main] 2 failures in step part1 (3.3% fail rate in 60 executions)
- [main] 2 failures in step release-tests (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-intake (3.3% fail rate in 60 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132188: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=bbq_hnsw updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9703 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/262dy3jppjrxo)
- [elasticsearch-periodic #9685 / release-tests](https://gradle-enterprise.elastic.co/s/vndahjuqfqipe)
- [elasticsearch-pull-request #83454 / part-1](https://gradle-enterprise.elastic.co/s/toiwbqkv5hl64)
- [elasticsearch-pull-request #83444 / part-1](https://gradle-enterprise.elastic.co/s/fjaq7cle5mday)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-pull-request #83357 / part-1](https://gradle-enterprise.elastic.co/s/dhpur3ptcyoca)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=bbq_hnsw updateType=bbq_disk}" -Dtests.seed=2304DED0AC9EABAA -Dtests.locale=ar-IQ -Dtests.timezone=America/Rainy_River -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dbbq_hnsw%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 2 hits but 3 was expected.  Total shards: 5 Successful shards: 5 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 6 failures in test testDenseVectorMappingUpdate {initialType=bbq_hnsw updateType=bbq_disk} (2.5% fail rate in 242 executions)
- [main] 3 failures in step part-1 (2.5% fail rate in 120 executions)
- [main] 2 failures in step release-tests (100.0% fail rate in 2 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 116 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132211: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_hnsw} failing
**Build Scans:**
- [elasticsearch-intake #26311 / part1](https://gradle-enterprise.elastic.co/s/muekmha5a53o6)
- [elasticsearch-pull-request #83444 / part-1](https://gradle-enterprise.elastic.co/s/fjaq7cle5mday)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_hnsw}" -Dtests.seed=F5F1C998346DDD52 -Dtests.locale=af-ZA -Dtests.timezone=Africa/Brazzaville -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_hnsw%20updateType%3Dbbq_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 4 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_hnsw} (0.7% fail rate in 280 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132214: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int8_hnsw updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-intake #26313 / part1](https://gradle-enterprise.elastic.co/s/luwyfsoxl7ifu)
- [elasticsearch-intake #26307 / part1](https://gradle-enterprise.elastic.co/s/xhesk6oll2xx4)
- [elasticsearch-periodic #9692 / release-tests](https://gradle-enterprise.elastic.co/s/x74j32zewiqly)
- [elasticsearch-pull-request #83565 / part-1](https://gradle-enterprise.elastic.co/s/x3whwd4kaduyo)
- [elasticsearch-periodic #9685 / release-tests](https://gradle-enterprise.elastic.co/s/vndahjuqfqipe)
- [elasticsearch-pull-request #83429 / part-1](https://gradle-enterprise.elastic.co/s/4lovlh2wstks6)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int8_hnsw updateType=bbq_disk}" -Dtests.seed=96703D16930A3B90 -Dtests.locale=sw-CD -Dtests.timezone=Africa/Douala -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint8_hnsw%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 4 hits but 5 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 8 failures in test testDenseVectorMappingUpdate {initialType=int8_hnsw updateType=bbq_disk} (2.8% fail rate in 281 executions)
- [main] 3 failures in step part1 (4.7% fail rate in 64 executions)
- [main] 2 failures in step part-1 (1.5% fail rate in 130 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 3 failures in pipeline elasticsearch-intake (4.7% fail rate in 64 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.6% fail rate in 127 executions)
- [main] 3 failures in pipeline elasticsearch-periodic (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132219: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_hnsw} failing
**Build Scans:**
- [elasticsearch-periodic #9699 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/webjcxfmxozde)
- [elasticsearch-intake #26308 / part1](https://gradle-enterprise.elastic.co/s/327lkot3cw52m)
- [elasticsearch-pull-request #83592 / part-1](https://gradle-enterprise.elastic.co/s/u6poaxb5hcbte)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)
- [elasticsearch-pull-request #83407 / part-1](https://gradle-enterprise.elastic.co/s/cuk3d4mij6e7s)
- [elasticsearch-pull-request #83378 / part-1](https://gradle-enterprise.elastic.co/s/iqdb3l3xjb6pa)
- [elasticsearch-pull-request #83347 / part-1](https://gradle-enterprise.elastic.co/s/573h4kfjnikfs)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_hnsw}" -Dtests.seed=59EB8F01B44AFA67 -Dtests.locale=en-HK -Dtests.timezone=Europe/Warsaw -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dbbq_hnsw%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 6 hits but 7 was expected.  Total shards: 2 Successful shards: 2 & 0 shard failures:
```

**Issue Reasons:**
- [main] 7 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_hnsw} (2.2% fail rate in 321 executions)
- [main] 4 failures in step part-1 (2.5% fail rate in 158 executions)
- [main] 2 failures in step part1 (2.7% fail rate in 75 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 154 executions)
- [main] 2 failures in pipeline elasticsearch-intake (2.7% fail rate in 75 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132220: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-periodic #9699 / release-tests](https://gradle-enterprise.elastic.co/s/ogk5rmlwjhjje)
- [elasticsearch-periodic #9692 / release-tests](https://gradle-enterprise.elastic.co/s/x74j32zewiqly)
- [elasticsearch-periodic #9685 / release-tests](https://gradle-enterprise.elastic.co/s/vndahjuqfqipe)
- [elasticsearch-pull-request #83425 / part-1](https://gradle-enterprise.elastic.co/s/zws6esy5nusj2)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-pull-request #83399 / part-1](https://gradle-enterprise.elastic.co/s/enlqgdxanpyqq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk}" -Dtests.seed=293C8BFC7AC71A3F -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=nqo-GN -Dtests.timezone=Pacific/Efate -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dhnsw%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Unknown vector index options type [bbq_disk] for field [vector]
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 6 failures in test testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk} (2.1% fail rate in 289 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 2 failures in step part-1 (1.5% fail rate in 134 executions)
- [main] 4 failures in pipeline elasticsearch-periodic (100.0% fail rate in 4 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 131 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132221: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-periodic #9699 / release-tests](https://gradle-enterprise.elastic.co/s/ogk5rmlwjhjje)
- [elasticsearch-pull-request #83615 / part-1](https://gradle-enterprise.elastic.co/s/bzahbq67s6nty)
- [elasticsearch-periodic #9692 / release-tests](https://gradle-enterprise.elastic.co/s/x74j32zewiqly)
- [elasticsearch-pull-request #83541 / part-1](https://gradle-enterprise.elastic.co/s/ujo2tpyxppk4a)
- [elasticsearch-periodic #9685 / release-tests](https://gradle-enterprise.elastic.co/s/vndahjuqfqipe)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-pull-request #83409 / part-1](https://gradle-enterprise.elastic.co/s/gwmcp4jk5zn3y)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk}" -Dtests.seed=293C8BFC7AC71A3F -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=nqo-GN -Dtests.timezone=Pacific/Efate -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Unknown vector index options type [bbq_disk] for field [vector]
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 8 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_disk} (2.9% fail rate in 278 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 3 failures in step part-1 (2.3% fail rate in 128 executions)
- [main] 4 failures in pipeline elasticsearch-periodic (100.0% fail rate in 4 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.4% fail rate in 125 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132222: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=flat updateType=bbq_disk} failing
**Build Scans:**
- [elasticsearch-periodic #9699 / release-tests](https://gradle-enterprise.elastic.co/s/ogk5rmlwjhjje)
- [elasticsearch-periodic #9692 / release-tests](https://gradle-enterprise.elastic.co/s/x74j32zewiqly)
- [elasticsearch-pull-request #83491 / part-1](https://gradle-enterprise.elastic.co/s/hzq4w4g5dylv6)
- [elasticsearch-periodic #9685 / release-tests](https://gradle-enterprise.elastic.co/s/vndahjuqfqipe)
- [elasticsearch-pull-request #83454 / part-1-fips](https://gradle-enterprise.elastic.co/s/e7m3kgrizvkh2)
- [elasticsearch-periodic #9678 / release-tests](https://gradle-enterprise.elastic.co/s/l2623ujvu6pek)
- [elasticsearch-intake #26241 / part1](https://gradle-enterprise.elastic.co/s/a76w4ag5o6v7s)
- [elasticsearch-pull-request #83405 / part-1](https://gradle-enterprise.elastic.co/s/2aqlle7vinndc)
- [elasticsearch-pull-request #83374 / part-1](https://gradle-enterprise.elastic.co/s/7pnakag3e26cu)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk}" -Dtests.seed=293C8BFC7AC71A3F -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=nqo-GN -Dtests.timezone=Pacific/Efate -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dflat%20updateType%3Dbbq_disk%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Unknown vector index options type [bbq_disk] for field [vector]
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 9 failures in test testDenseVectorMappingUpdate {initialType=flat updateType=bbq_disk} (2.9% fail rate in 307 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 3 failures in step part-1 (2.1% fail rate in 144 executions)
- [main] 4 failures in pipeline elasticsearch-periodic (100.0% fail rate in 4 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (2.8% fail rate in 141 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132228: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk #2} failing
**Build Scans:**
- [elasticsearch-intake #26328 / part1](https://gradle-enterprise.elastic.co/s/4odhw32abs6qi)
- [elasticsearch-pull-request #83600 / part-1](https://gradle-enterprise.elastic.co/s/m3otk2y6tnito)
- [elasticsearch-pull-request #83523 / part-1-fips](https://gradle-enterprise.elastic.co/s/3k47t27km5346)
- [elasticsearch-pull-request #83522 / part-1](https://gradle-enterprise.elastic.co/s/wlzw4r73qofs6)
- [elasticsearch-intake #26272 / part1](https://gradle-enterprise.elastic.co/s/dpvgt2bxvs2kq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk #2}" -Dtests.seed=82E33956C71AB401 -Dtests.locale=ckb -Dtests.timezone=Australia/South -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_hnsw%20updateType%3Dbbq_disk%20%232%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 4 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 5 failures in test testDenseVectorMappingUpdate {initialType=int4_hnsw updateType=bbq_disk #2} (1.9% fail rate in 257 executions)
- [main] 2 failures in step part1 (3.4% fail rate in 58 executions)
- [main] 2 failures in step part-1 (1.7% fail rate in 120 executions)
- [main] 2 failures in pipeline elasticsearch-intake (3.4% fail rate in 58 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 117 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132234: [CI] DenseVectorFieldIndexTypeUpdateIT testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_disk #2} failing
**Build Scans:**
- [elasticsearch-periodic #9706 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/p2xai52jvyfmm)
- [elasticsearch-pull-request #83491 / part-1](https://gradle-enterprise.elastic.co/s/hzq4w4g5dylv6)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_disk #2}" -Dtests.seed=FA78E93FD14B8837 -Dtests.locale=zh-TW -Dtests.timezone=America/Araguaina -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDenseVectorMappingUpdate%20%7BinitialType%3Dint4_flat%20updateType%3Dbbq_disk%20%232%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 5 hits but 6 was expected.  Total shards: 3 Successful shards: 3 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testDenseVectorMappingUpdate {initialType=int4_flat updateType=bbq_disk #2} (0.8% fail rate in 258 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by carlosdelest**
Docs indexation didn't wait for the index request to return, which caused doc count to fail in some instances.

Closes quite a few issues, as this is a parameterized test that checks all combinations of index upgrades.

Closes #132165
Closes #132164
Closes #132152
Closes #132151
Closes #132150
Closes #132149
Closes #132141
Closes #132140
Closes #132134
Closes #132133
Closes #132132
Closes #132130
Closes #132127
Closes #132126
Closes #132125
Closes #132124
Closes #132123
Closes #132122
Closes #132121
Closes #132120
Closes #132119
Closes #132117
Closes #132116
Closes #132115
Closes #132113
Closes #132112
Closes #132234
Closes #132228
Closes #132222
Closes #132221
Closes #132220
Closes #132219
Closes #132214
Closes #132213
Closes #132211
Closes #132189
Closes #132188

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java [hunk 1]
```diff
@@ -119,28 +124,26 @@ public void testDenseVectorMappingUpdate() throws Exception {
...
-        client.prepareRefresh(INDEX_NAME).get();
+        indicesClient.prepareFlush(INDEX_NAME).get();
+        indicesClient.prepareRefresh(INDEX_NAME).get();
 
         // Search to ensure all documents are present
         int expectedDocs = docsBefore + docsAfter;
-        assertNoFailuresAndResponse(client().prepareSearch(INDEX_NAME).setSize(expectedDocs + 10), response -> {
+
+        // Count query
+        assertNoFailuresAndResponse(client().prepareSearch(INDEX_NAME).setSize(0).setTrackTotalHits(true).setSize(expectedDocs), response -> {
```
Comment (carlosdelest) [inline server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java]: Added a count query as well as a knn query to ensure results are consistent

File: server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java [hunk 2]
```diff
@@ -168,9 +171,10 @@ private static void createFieldMapping(int dimensions, String type, XContentBuil
         builder.endObject();
     }
 
-    private void indexDoc(int id) throws IOException {
+    private void indexDoc(int id) throws ExecutionException, InterruptedException {
         Float[] vector = randomArray(dimensions, dimensions, Float[]::new, () -> randomFloatBetween(-1, 1, true));
-        IndexRequest req = prepareIndex(INDEX_NAME).setSource(VECTOR_FIELD, vector).setId(Integer.toString(id)).request();
-        client().index(req);
```
Comment (carlosdelest) [inline server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java:174]: 🤦

**Review by john-wagster — APPROVED** [review]
lgtm insane number of issues created ha
