### PR TITLE
ESQL: Fix block randomization on circuit breaking tests

### LINKED ISSUE #127833: [CI] FilteredGroupingAggregatorFunctionTests testSimpleCircuitBreaking failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8082 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/eozdniwao7mxo)
- [elasticsearch-periodic-platform-support #8082 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/usbykfywlpdma)
- [elasticsearch-periodic-platform-support #8082 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/uo2uyy7bfjg4u)
- [elasticsearch-pull-request #70878 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/76vdab3ra65uw)
- [elasticsearch-pull-request #70874 / part-3](https://gradle-enterprise.elastic.co/s/idnjyhvgc4hdk)
- [elasticsearch-pull-request #70865 / part-3](https://gradle-enterprise.elastic.co/s/p75t5mrmdscns)
- [elasticsearch-pull-request #70834 / part-3](https://gradle-enterprise.elastic.co/s/5ixbm6j6vfn5k)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.aggregation.FilteredGroupingAggregatorFunctionTests.testSimpleCircuitBreaking" -Dtests.seed=40865A7C7F748006 -Dtests.locale=de-DE -Dtests.timezone=Pacific/Ponape -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.aggregation.FilteredGroupingAggregatorFunctionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSimpleCircuitBreaking),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalArgumentException: expected runnable to break under a limit of 130.2kb bytes
```

**Issue Reasons:**
- [main] 7 failures in test testSimpleCircuitBreaking (2.9% fail rate in 242 executions)
- [main] 3 failures in step part-3 (2.9% fail rate in 102 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (4.0% fail rate in 100 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/127833

A Block type randomization was added here (https://github.com/elastic/elasticsearch/pull/127582/commits/32588b56bf87f87c432a4f61576559461ee5a838) to test different code paths based on the specific agg groupIds block type.

Now, a circuit breaking test fails sometimes, as it expects memory usage to be exact and deterministic, and the randomization may choose a more or less optimum path, changing the memory usage.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/GroupingAggregatorFunctionTestCase.java [hunk 1]
```diff
@@ -108,13 +110,41 @@ private Operator.OperatorFactory simpleWithMode(
...
+     * </p>
+     * <p>
+     *     Explicitly linking {@link org.elasticsearch.compute.test.OperatorTestCase#testSimpleCircuitBreaking} as
+     *     this method looks for it based on its name, so any modification there should be updated here!
+     * </p>
+     */
+    private boolean shouldRandomizeBlocks() {
+        return Arrays.stream(Thread.currentThread().getStackTrace())
+            .noneMatch(
+                e -> e.getClassName().equals(OperatorTestCase.class.getName()) && e.getMethodName().equals("testSimpleCircuitBreaking")
```
Comment (ivancea) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/GroupingAggregatorFunctionTestCase.java:146]: I wish we had C#'s `nameof()` to make this more robust. But I think adding that link in the javadoc is the only _simple_ option we have (?)

**Review by nik9000 — COMMENTED** [review]
I'd really prefer to do this with a function parameter. It's an extra parameter in a zillion places, but it feels more honest.

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/AnyOperatorTestCase.java [hunk 2]
```diff
@@ -32,11 +32,27 @@
...
  */
 public abstract class AnyOperatorTestCase extends ComputeTestCase {
+    /**
+     * @param requiresDeterministicFactory
+     *          True if the returned {@link Operator.OperatorFactory} should always generate an identical deterministic operator.
+     *          That is, for two different calls, both operators should do "exactly" the same.
+     */
+    protected record SimpleOptions(boolean requiresDeterministicFactory) {
+        public static final SimpleOptions DEFAULT = new SimpleOptions(false);
+    }
```
Comment (ivancea) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/AnyOperatorTestCase.java:42]: Created this structure instead of just a boolean as it's:
- Easier to understand from callers
- Extendable (Not a big concern now, but the first point makes more sense to me)

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/AnyOperatorTestCase.java [hunk 3]
```diff
@@ -32,11 +32,27 @@
...
      * The operator configured a "simple" or basic way, used for smoke testing
      * descriptions, {@link CircuitBreaker}s, and scatter/gather.
      */
-    protected abstract Operator.OperatorFactory simple();
+    protected abstract Operator.OperatorFactory simple(SimpleOptions options);
+
+    /**
+     * Calls {@link #simple(SimpleOptions)} with the default options.
+     */
+    protected final Operator.OperatorFactory simple() {
```
Comment (ivancea) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/AnyOperatorTestCase.java:53]: Added those methods to keep changes at a minimum

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java [hunk 4]
```diff
@@ -98,7 +98,7 @@ protected ByteSizeValue enoughMemoryForSimple() {
      */
     public final void testSimpleCircuitBreaking() {
         ByteSizeValue memoryLimitForSimple = enoughMemoryForSimple();
-        Operator.OperatorFactory simple = simple();
+        Operator.OperatorFactory simple = simple(new SimpleOptions(true));
```
Comment (ivancea) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java:101]: And this is the method actually using the new param

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/AnyOperatorTestCase.java (hunk 2 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/AnyOperatorTestCase.java:42]: :+1:

**Review by nik9000 — APPROVED** [review]
