### PR TITLE
#104233 Allow Watcher Node Allocation Settings

### LINKED ISSUE #104233: Cannot update watcher index settings to set `index.routing.allocation.include.role` as described in the docs
### Problem Description

Our [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/how-watcher-works.html#watch-execution ) says that you can run watcher only on specific nodes by doing this:
```
PUT .watches/_settings
{
  "index.routing.allocation.include.role": "watcher"
}
```
However, in 8.0 `.watches` became a system index so you get this error if you try that:
```
"error" : {
"root_cause" : [
{
"type" : "illegal_state_exception",
"reason" : "Cannot override settings on system indices: [.watches*] -> [index.routing.allocation.include.role]"
}
],
"type" : "illegal_state_exception",
"reason" : "Cannot override settings on system indices: [.watches*] -> [index.routing.allocation.include.role]"
},
"status" : 500
}
```
We need to either fix this feature or remove it (its documentation anyway). A possible fix would be to add `index.routing.allocation.include.role`, `index.routing.allocation.exclude.role`, and `index.routing.allocation.require.role` to the list of valid properties for the `/_watcher/settings` API.

### PR DESCRIPTION
**Pull request by lukewhiting**
Fixes #104233

This PR allows the `PUT _watcher/settings` endpoint to accept shard allocation settings while also adding restrictions to prevent users modifying or removing the `index.routing.allocation.include._tier_preference` setting on the `.watches` index. It also modifies the `GET _watcher/settings` to show the newly allowed settings.

By controlling shard allocation, You also control which nodes in the cluster actually execute watches. The relevant documentation is also updated to show this new way of adjusting which nodes Watcher runs on.

I chose this approach over removing the reference in the documentation as that felt like a breaking change / removal of previous functionality.

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/transport/actions/put/UpdateWatcherSettingsAction.java [hunk 1]
```diff
@@ -34,6 +34,16 @@ public class UpdateWatcherSettingsAction extends ActionType<AcknowledgedResponse
         IndexMetadata.SETTING_AUTO_EXPAND_REPLICAS
     );
 
+    public static final Set<String> ALLOWED_SETTINGS_PREFIXES = Set.of(
+        IndexMetadata.INDEX_ROUTING_EXCLUDE_GROUP_PREFIX,
+        IndexMetadata.INDEX_ROUTING_INCLUDE_GROUP_PREFIX,
+        IndexMetadata.INDEX_ROUTING_REQUIRE_GROUP_PREFIX
+    );
+
+    public static final Set<String> EXPLICITLY_DENIED_SETTINGS = Set.of(
```
Comment (masseyke) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/transport/actions/put/UpdateWatcherSettingsAction.java:43]: I assume you're denying this one because we always want the .watches shards in the hot tier? That makes me wonder what other possible values there are for these afix settings, and if we ought to just explicitly allow the `index.routing.allocation.exclude.role`, `index.routing.allocation.include.role`, and `index.routing.allocation.require.role` ones and disallow anything else to avoid causing some unforeseen problems. You've probably looked at all these settings more than I have -- what do you think?

Comment (lukewhiting) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/transport/actions/put/UpdateWatcherSettingsAction.java:43]: So I based this restriction on what the default setting for the `.watcher` index are. I assumed we put it in the hot tier for good reason so locked off the ability to change that.

Locking down the `index.routing.allocation.*.*` settings further is difficult. `index.routing.allocation.include.role` isn't actually a setting as such but a convention for a wildcard setting. Anything after `index.routing.allocation.include.` is assumed to be an arbitrary node attribute hence my leaving it as allowing any setting with that prefix as we have no way of knowing what attributes the end user might have set on their nodes and how they would like to use those for scheduling watches. 

For instance `index.routing.allocation.include.sandwich_filling=turkey` is a valid setting for this if the user chose to use a bread based node attributes scheme to group their cluster members :-)

**Review by masseyke — APPROVED** [review]
LGTM!

**Comment by herrBez** [comment]
Should we also update the documentation https://www.elastic.co/guide/en/elasticsearch/reference/8.x/watcher-api-update-settings.html ?

**Comment by lukewhiting** [comment]
@herrBez The documentation has now been updated and will go live with the next release :-)
