### PR TITLE
Address test issue in QueryPhaseTimeoutTests

### LINKED ISSUE #124140: [CI] QueryPhaseTimeoutTests testScorerTimeoutPoints failing
**Build Scans:**
- [elasticsearch-intake #19479 / part1](https://gradle-enterprise.elastic.co/s/b233quyczq3am)
- [elasticsearch-periodic-platform-support #6780 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/4hu2zg7gk4qmm)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.query.QueryPhaseTimeoutTests.testScorerTimeoutPoints" -Dtests.seed=FC34D732AE5ADC5A -Dtests.locale=und -Dtests.timezone=Europe/Madrid -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.query.QueryPhaseTimeoutTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testScorerTimeoutPoints),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<2048> but was:<2399>
```

**Issue Reasons:**
- [main] 2 failures in test testScorerTimeoutPoints (0.9% fail rate in 213 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by javanna**
The test that is verifying timeout handling when pulling a scorer supplier is going to always score the entire segment. The test needs to be adjusted accordingly. While at it, I added docs and clarified the tests a bit, as well as added a couple new tests that cover for timeout handling when retrieving a scorer from the scorer supplier.

Closes #124140

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java [hunk 1]
```diff
@@ -125,27 +125,35 @@ private static ContextIndexSearcher newContextSearcher(IndexReader reader) throw
...
-    public void testScorerTimeoutTerms() throws IOException {
+    /**
+     * Test that a timeout is appropriately handled when the directory reader raises it while loading terms enum
+     * as the scorer supplier is requested.
+     */
+    public void testScorerSupplierTimeoutTerms() throws IOException {
         assumeTrue("Test requires more than one segment", reader.leaves().size() > 1);
         int size = randomBoolean() ? 0 : randomIntBetween(100, 500);
-        scorerTimeoutTest(size, context -> {
+        scorerSupplierTimeoutTest(size, context -> {
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java:135]: I've been reading TimeoutQuery and MatchAllWeight defined in this test class but I'm still not sure how the function passed in triggers the timeout. At least that's what I'm supposing its doing given its name. Maybe its possible to explain this for future readers somehow?

**Review by cbuescher — COMMENTED** [review]
Thanks for looking into this test. I took a first pass and left mostly questions and suggestions to maybe improve some documentation as I find this test hard to understand. 
Another question because I saw the backport labels: from investigating the issue in https://github.com/elastic/elasticsearch/issues/124140 I thought we might have introduced a change somewhere with Lucene 10.1, but now it sounds like the test assumptions might have been wrong even before that? Why does the repro line from the issue then clearly reproduce the failure after the Lucene 10.1 update but not before, do you have any theory on that? Or am I missunderstanding something?

**Comment by javanna** [comment]
>  I thought we might have introduced a change somewhere with Lucene 10.1, but now it sounds like the test assumptions might have been wrong even before that? Why does the repro line from the issue then clearly reproduce the failure after the Lucene 10.1 update but not before, do you have any theory on that? Or am I missunderstanding something?

Correct, this has been a bug in this test since day 1. I am not sure why it has not reproduced earlier to be honest. I don't see anything that has changed with Lucene 10.0 or 10.1, but the fact a certain seed does not reproduce across Lucene 10 and Lucene 9.12 is not shocking, because the sequence of calls to randomize things certainly changed in LuceneTestCase.

File: server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java (hunk 1 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java:135]: I thought the new javadocs would help explaining this. 

> Test that a timeout is appropriately handled when the (exitable) directory reader raises it while loading terms enum as the scorer is retrieved from the scorer supplier.

The idea of these tests is that a timeout can be raised from different places: either because we wrap the bulk scorer with a cancellable one, or via the exitable directory reader that wraps the original reader. Because a timeout can be raised from different places, it's easy to miss and to forget handling the corresponding exception. The reason why the timeout is thrown is because we flip shouldTimeout in the search context. I am adding a bit more comments.

File: server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java [hunk 2]
```diff
@@ -190,6 +200,95 @@ public ScorerSupplier scorerSupplier(LeafReaderContext context) throws IOExcepti
...
+            public Weight createWeight(IndexSearcher searcher, ScoreMode scoreMode, float boost) {
+                return new MatchAllWeight(this, boost, scoreMode) {
+                    boolean firstSegment = true;
+
+                    @Override
+                    public ScorerSupplier scorerSupplier(LeafReaderContext context) throws IOException {
+                        ScorerSupplier scorerSupplier = super.scorerSupplier(context);
+                        return new ScorerSupplier() {
+                            @Override
+                            public Scorer get(long leadCost) throws IOException {
```
[the remark this answers is not in the document]
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java:268]: can you make a suggestion? I am not sure what I can do to clarify this.

[the remark this answers is not in the document]
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/query/QueryPhaseTimeoutTests.java:268]: I thought this was made clear by the javadocs already:

> as the scorer is retrieved from the scorer supplier

as opposed to 

> as the scorer supplier is requested

methods are also named that way to suggest the difference around pulling the supplier as opposed to getting the scorer from the supplier. I totally see that this is tricky.

File: muted-tests.yml [hunk 3]
```diff
@@ -330,12 +330,9 @@ tests:
...
   issue: https://github.com/elastic/elasticsearch/issues/120814
-- class: org.elasticsearch.search.query.QueryPhaseTimeoutTests
-  method: testScorerTimeoutPoints
-  issue: https://github.com/elastic/elasticsearch/issues/124140
-- class: org.elasticsearch.search.query.QueryPhaseTimeoutTests
-  method: testScorerTimeoutTerms
-  issue: https://github.com/elastic/elasticsearch/issues/124141
+- class: org.elasticsearch.compute.data.BlockMultiValuedTests
+  method: testToMask {elementType=BOOLEAN nullAllowed=true}
+  issue: https://github.com/elastic/elasticsearch/issues/124165
```
Comment (javanna) [inline muted-tests.yml:335]: This was caused by a bad merge, I fixed that directly on main with https://github.com/elastic/elasticsearch/commit/dfe2b249a09ac5563d639ffaba2888d2ed4248ec

**Comment by javanna** [comment]
> Correct, this has been a bug in this test since day 1. I am not sure why it has not reproduced earlier to be honest. I don't see anything that has changed with Lucene 10.0 or 10.1, but the fact that a certain seed does not reproduce across Lucene 10 and Lucene 9.12 is not shocking, because the sequence of calls to randomize things certainly changed in LuceneTestCase.

Mystery solved, it's the test has changed with the Lucene 10 upgrade, see https://github.com/elastic/elasticsearch/commit/88b351698ee55b98cff3a7a06602ca45e322b971#diff-ff445eb9c0ccebe705452387b4f946dd3675db92b1ec513e4a6c2da9e17e67bd from the lucene_snapshot branch. The test was not previously testing timeouts when the scorer supplier is retrieved for each leaf context, but rather when the bulk scorer or the scorer were. It's only the former that needs a different assertion. That means this fix does not need backporting.

**Comment by cbuescher** [comment]
>  I addressed your comments, I went ahead and merged this
Yes, thanks for adding some more comments, appreciate it.
