### PR TITLE
Make GetInferenceFieldsAction an Indices Action

### LINKED ISSUE #140193: Semantic search CCS when ccs_minimize_roundtrips=false is broken in real-world deployments
### Elasticsearch Version

9.3

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

Semantic search CCS when `ccs_minimize_roundtrips=false` is broken in real-world deployments. Executing a CCS search request with `ccs_minimize_roundtrips=false` against a `semantic_text` field returns this error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Internal user [_xpack] should not be used for cross cluster requests"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Internal user [_xpack] should not be used for cross cluster requests"
  },
  "status": 400
}
```

### Steps to Reproduce

1. Create two clusters in ECH
2. Connect the two clusters ([docs](https://www.elastic.co/docs/deploy-manage/remote-clusters/ec-remote-cluster-same-ess))
3. Create indices in both clusters that use `semantic_text` fields and add some test docs to them
4. Run a search request that queries a remote index using `ccs_minimize_roundtrips=false`:

```
GET local-index,remote-cluster:remote-index/_search?ccs_minimize_roundtrips=false
{
    "query": {
        "semantic": {
            "field": "semantic_field",
            "query": "foo"
        }
    }
}
```

### Logs (if relevant)

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Internal user [_xpack] should not be used for cross cluster requests",
        "stack_trace": """org.elasticsearch.ElasticsearchException$1: Internal user [_xpack] should not be used for cross cluster requests
	at org.elasticsearch.server@9.3.0/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:797)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:711)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestResponse.build(RestResponse.java:202)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:161)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:122)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:54)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.action.RestCancellableNodeClient$1.onFailure(RestCancellableNodeClient.java:97)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:234)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:360)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:40)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteContext$1.onFailure(QueryRewriteContext.java:492)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:40)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1524)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendWithUser(SecurityServerTransportInterceptor.java:248)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.lambda$sendRequestInner$1(SecurityServerTransportInterceptor.java:193)
	at org.elasticsearch.xcore@9.3.0/org.elasticsearch.xpack.core.security.SecurityContext.executeAsInternalUser(SecurityContext.java:172)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authz.AuthorizationUtils.switchUserBasedOnActionOriginAndExecute(AuthorizationUtils.java:172)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendRequestInner(SecurityServerTransportInterceptor.java:189)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$1.sendRequest(SecurityServerTransportInterceptor.java:156)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:889)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.RemoteClusterAwareClient.execute(RemoteClusterAwareClient.java:44)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.RemoteClusterClient.lambda$execute$0(RemoteClusterClient.java:34)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:423)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:239)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:197)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.RemoteClusterAwareClient.getConnection(RemoteClusterAwareClient.java:81)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.RemoteClusterClient.execute(RemoteClusterClient.java:32)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.InferenceQueryUtils$RemoteInferenceInfoAsyncAction.lambda$execute$1(InferenceQueryUtils.java:690)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:423)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:239)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:197)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.RemoteClusterAwareClient.getConnection(RemoteClusterAwareClient.java:81)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.InferenceQueryUtils$RemoteInferenceInfoAsyncAction.lambda$execute$2(InferenceQueryUtils.java:679)
	at org.elasticsearch.xcore@9.3.0/org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:224)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.InferenceQueryUtils$RemoteInferenceInfoAsyncAction.execute(InferenceQueryUtils.java:678)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteRemoteAsyncAction.execute(QueryRewriteRemoteAsyncAction.java:46)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteAsyncAction.execute(QueryRewriteAsyncAction.java:41)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteContext.executeAsyncActions(QueryRewriteContext.java:507)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:103)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:664)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:349)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:137)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:135)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:54)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.MappedActionFilters$MappedFilterChain.proceed(MappedActionFilters.java:71)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.MappedActionFilters.apply(MappedActionFilters.java:49)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$6(SecurityActionFilter.java:202)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:233)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:423)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:239)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:197)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:200)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:134)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction.handleExecution(TransportAction.java:96)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:59)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:216)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:107)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.action.RestCancellableNodeClient.doExecute(RestCancellableNodeClient.java:82)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:160)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$2(RestSearchAction.java:139)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:143)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:472)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:466)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:105)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$0(SecurityRestFilter.java:90)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$3(SecondaryAuthenticator.java:99)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:109)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:90)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$2(SecurityRestFilter.java:80)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:96)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:466)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController.lambda$maybeAggregateAndDispatchRequest$4(RestController.java:404)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestContentAggregator$AggregationChunkHandler.onNext(RestContentAggregator.java:78)
	at org.elasticsearch.transport.netty4@9.3.0/org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream.handleNettyContent(Netty4HttpRequestBodyStream.java:87)
	at org.elasticsearch.transport.netty4@9.3.0/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:146)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler@4.1.130.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler@4.1.130.Final/io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:847)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.transport@4.1.130.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.common@4.1.130.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.IllegalArgumentException: Internal user [_xpack] should not be used for cross cluster requests
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.CrossClusterAccessTransportInterceptor$1.illegalArgumentExceptionWithDebugLog(CrossClusterAccessTransportInterceptor.java:336)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.CrossClusterAccessTransportInterceptor$1.sendWithCrossClusterAccessHeaders(CrossClusterAccessTransportInterceptor.java:214)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.CrossClusterAccessTransportInterceptor$1.sendRequest(CrossClusterAccessTransportInterceptor.java:151)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendWithUser(SecurityServerTransportInterceptor.java:246)
	... 86 more
"""
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Internal user [_xpack] should not be used for cross cluster requests",
    "stack_trace": """java.lang.IllegalArgumentException: Internal user [_xpack] should not be used for cross cluster requests
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.CrossClusterAccessTransportInterceptor$1.illegalArgumentExceptionWithDebugLog(CrossClusterAccessTransportInterceptor.java:336)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.CrossClusterAccessTransportInterceptor$1.sendWithCrossClusterAccessHeaders(CrossClusterAccessTransportInterceptor.java:214)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.CrossClusterAccessTransportInterceptor$1.sendRequest(CrossClusterAccessTransportInterceptor.java:151)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendWithUser(SecurityServerTransportInterceptor.java:246)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.lambda$sendRequestInner$1(SecurityServerTransportInterceptor.java:193)
	at org.elasticsearch.xcore@9.3.0/org.elasticsearch.xpack.core.security.SecurityContext.executeAsInternalUser(SecurityContext.java:172)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authz.AuthorizationUtils.switchUserBasedOnActionOriginAndExecute(AuthorizationUtils.java:172)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendRequestInner(SecurityServerTransportInterceptor.java:189)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$1.sendRequest(SecurityServerTransportInterceptor.java:156)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:889)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.RemoteClusterAwareClient.execute(RemoteClusterAwareClient.java:44)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.RemoteClusterClient.lambda$execute$0(RemoteClusterClient.java:34)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:423)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:239)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:197)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.RemoteClusterAwareClient.getConnection(RemoteClusterAwareClient.java:81)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.RemoteClusterClient.execute(RemoteClusterClient.java:32)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.InferenceQueryUtils$RemoteInferenceInfoAsyncAction.lambda$execute$1(InferenceQueryUtils.java:690)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:423)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:239)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:197)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.RemoteClusterAwareClient.getConnection(RemoteClusterAwareClient.java:81)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.InferenceQueryUtils$RemoteInferenceInfoAsyncAction.lambda$execute$2(InferenceQueryUtils.java:679)
	at org.elasticsearch.xcore@9.3.0/org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:224)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.InferenceQueryUtils$RemoteInferenceInfoAsyncAction.execute(InferenceQueryUtils.java:678)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteRemoteAsyncAction.execute(QueryRewriteRemoteAsyncAction.java:46)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteAsyncAction.execute(QueryRewriteAsyncAction.java:41)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteContext.executeAsyncActions(QueryRewriteContext.java:507)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:103)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:664)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:349)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:137)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:135)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:54)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.MappedActionFilters$MappedFilterChain.proceed(MappedActionFilters.java:71)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.MappedActionFilters.apply(MappedActionFilters.java:49)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$6(SecurityActionFilter.java:202)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:233)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:423)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:239)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:197)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:200)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:134)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction.handleExecution(TransportAction.java:96)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:59)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:216)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:107)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.action.RestCancellableNodeClient.doExecute(RestCancellableNodeClient.java:82)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:160)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$2(RestSearchAction.java:139)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:143)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:472)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:466)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:105)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$0(SecurityRestFilter.java:90)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$3(SecondaryAuthenticator.java:99)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:109)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:90)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$2(SecurityRestFilter.java:80)
	at org.elasticsearch.security@9.3.0/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:96)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:466)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestController.lambda$maybeAggregateAndDispatchRequest$4(RestController.java:404)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.rest.RestContentAggregator$AggregationChunkHandler.onNext(RestContentAggregator.java:78)
	at org.elasticsearch.transport.netty4@9.3.0/org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream.handleNettyContent(Netty4HttpRequestBodyStream.java:87)
	at org.elasticsearch.transport.netty4@9.3.0/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:146)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler@4.1.130.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler@4.1.130.Final/io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:847)
	at io.netty.transport@4.1.130.Final/io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.transport@4.1.130.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.common@4.1.130.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.common@4.1.130.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1474)
"""
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by Mikep86**
Makes `GetInferenceFieldsAction` an indices action dependent on the indices `read` permission. This allows the action to be executed by users with read access to the indices queried.

Fixes https://github.com/elastic/elasticsearch/issues/140193

### CODE REVIEW

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Review by jimczi — APPROVED** [review]
LGTM

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java [hunk 1]
```diff
@@ -12,6 +12,7 @@
 import org.elasticsearch.action.ActionRequestValidationException;
```
Comment (n1v0lg) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java:12]: Lets rename to `InternalGetInferenceFieldsAction` or similar to signify that it's an internal-only action.

**Comment by Mikep86** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java [hunk 2]
```diff
@@ -172,11 +187,12 @@ public boolean useDefaultFields() {
             return useDefaultFields;
         }
 
-        public String getQuery() {
+        public String query() {
             return query;
         }
```
Comment (n1v0lg) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java:193]: We also need `allowRemoteIndices` and `includeDataStreams` overridden to return true, I think

**Comment by Mikep86** [comment]
@elasticmachine update branch

File: docs/changelog/140399.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+pr: 140399
+summary: Make GetInferenceFieldsAction an Indices Action
+area: Search
+type: bug
```
Comment (n1v0lg) [inline docs/changelog/140399.yaml]: Since this is not actually impacting production and thus isn't impacting customers, I don't think we should label this a `bug`. Otherwise it will show up in user-facing change logs and create the impression that something in some ES 9.x version was actually broken.

**Review by n1v0lg — APPROVED** [review]
LGTM. Note: I only reviewed the privilege change, REST IT, and `GetInferenceFieldsAction` code. 

@Mikep86 I'd love to this discuss with the team tomorrow EMEA morning -- could you hold off merging until then?

File: docs/changelog/140399.yaml (hunk 3 above)
Comment (Mikep86) [reply docs/changelog/140399.yaml]: I can re-label this PR as `>non-issue` to remove the changelog entry

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java (hunk 2 above)
Comment (Mikep86) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java:193]: Good callout about `includeDataStreams`!

We actually want `allowRemoteIndices` to be `false` though. This is an action that is always executed on a remote cluster (in production, at least). The indices defined in the request are not prefixed with `<remote_cluster_alias>:`, because they will be resolved on the remote cluster, making that information redundant.

Another way to think of it is that this is an action that will be executed entirely on one remote cluster, and thus the index names are resolved relative to that cluster. From that perspective, the index names are local to the individual cluster and thus not remote.

We enforce this in `TransportGetInferenceFieldsAction`: https://github.com/Mikep86/elasticsearch/blob/7606f5c23d7bd680d3b7057364a056fb7a0d6eb8/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceFieldsAction.java#L97-L100

Comment (Mikep86) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java:193]: Done in a962a8ef

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java (hunk 1 above)
Comment (Mikep86) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceFieldsInternalAction.java:12]: Done in 84214d3d

**Comment by Mikep86** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/140674)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
