### PR TITLE
Avoid eagerly loading StoredFieldsReader in fetch phase

### LINKED ISSUE #82777: Performance degradation for new HitContext constructor when only pulling docvalues
**Elasticsearch version** (`bin/elasticsearch --version`): `7.14.2`

**Plugins installed**: []

**JVM version** (`java -version`): `openjdk version "16" 2021-03-16`

**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**:
In my production environment, I pull only docvalues from es cluster by setting `_source=false` and `stored_fields=_none_` in scroll query for SQL query computed in my own SQL query engine(like presto). In my scenario, the CPU is the performance bottleneck. 
In 7.14.2 es version, #65292 PR will cause each `HitContext`(one doc) to initialize the `FieldsIndexReader` called in `setSegmentAndDocument()` function at least once, and the FieldsIndexReader is not actually used, resulting in a `performance drop` of about `30%`(in my case) compared to 7.10.1 es version. The analysis results of async-profiler are shown in the following figure. 
7.14.2
image
7.10.1
image

**Steps to reproduce**:
In my environment, there is 25 es data nodes (32C64G,3TB disk), 3 es master node;  and there is 20  nodes(16C32G) in my SQL query engine(like presto).

But the problem can be reproduced by following steps. 

 1. create a 7.14.2 es cluster (can only one data node)
 2. create a index
 `PUT test_column
{
  "mappings" : {
      "_meta" : {
        "vers" : "v4"
      },
      "date_detection" : false,
      "numeric_detection" : false,
      "properties" : {
        "__TIMESTAMP__" : {
          "type" : "long"
        },
        "http_param" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword"
            }
          },
          "analyzer" : "keyword"
        },
        "request_id" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword"
            }
          },
          "analyzer" : "keyword"
        },
        "time" : {
          "type" : "text",
          "fields" : {
            "raw" : {
              "type" : "keyword"
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "number_of_replicas" : "0",
        "number_of_shards" : "1"
    }
  }
}`
 3. insert 1 billion logs to the index test_column
 4. scroll search 
 `POST test_column/_search?scroll=1h&preference=_shards:0
{
    "size": 10000,
    "timeout": "55s",
    "query": {
      "match_all":{}
    },
    "_source": false,
    "stored_fields": "_none_",
    "docvalue_fields": [
        {
            "field": "http_param.raw"
        },
        {
            "field": "request_id.raw"
        },
        {
            "field": "time.raw"
        }
    ],
    "sort": [
        {
            "_doc": {
                "order": "asc"
            }
        }
    ]
}`
then scroll 
`POST _search/scroll?scroll=1min
{
    "scroll_id" : "xxx"
}`

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by jtibshirani**
Every time we create a hit document, we create a new SourceLookup and call
setSegmentAndDocument. This in turn creates a new StoredFieldsReader, which is
pretty expensive. In scenarios where you are retrieving a lot of hits, this can
add significant overhead. Prior to version 7.11, we did not create a new
SourceLookup per hit, so this is a performance regression.

This PR updates setSegmentAndDocument to avoid eagerly creating a
new StoredFieldsReader (through StoredFieldsReader#getMergeInstance).

Closes #82777.

### CODE REVIEW

**Comment by jtibshirani** [comment]
Some notes:
* An alternative would be to introduce `SourceLookup#setDoc`, which sets the document without the leaf reader context. This felt less solid, and I wanted to avoid touching the `HitContext` -- source handling in the fetch phase is very complex and doesn't have strong test coverage!
* This gives more motivation for adding fetch benchmarks (https://github.com/elastic/elasticsearch/issues/82777). I'm also guessing that EQL tests might have caught it, which didn't exist back in 7.11.

File: libs/core/src/main/java/org/elasticsearch/core/MemoizedSupplier.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+ * 2.0 and the Server Side Public License, v 1; you may not use this file except
+ * in compliance with, at your election, the Elastic License 2.0 or the Server
+ * Side Public License, v 1.
+ */
+
+package org.elasticsearch.core;
+
+import java.util.function.Supplier;
+
+public class MemoizedSupplier<T> implements Supplier<T> {
```
Comment (jtibshirani) [inline libs/core/src/main/java/org/elasticsearch/core/MemoizedSupplier.java:13]: I restored this class, which was only very recently deleted because it was unused.

File: server/src/main/java/org/elasticsearch/search/lookup/SourceLookup.java [hunk 2]
```diff
@@ -104,19 +107,23 @@ public int docId() {
...
-                // get better sequential access.
-                fieldReader = lf.getSequentialStoredFieldsReader()::visitDocument;
+
+            // All the docs to fetch are adjacent but Lucene stored fields are optimized
+            // for random access and don't optimize for sequential access - except for merging.
+            // So we do a little hack here and pretend we're going to do merges in order to
+            // get better sequential access.
+            if (context.reader() instanceof SequentialStoredFieldsLeafReader lf) {
+                // Avoid eagerly loading the stored fields reader, since this can be expensive
+                Supplier<StoredFieldsReader> supplier = new MemoizedSupplier<>(lf::getSequentialStoredFieldsReader);
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/search/lookup/SourceLookup.java:125]: The main issue is that `getSequentialStoredFieldsReader` calls `StoredFieldsReader#getMergeInstance`, which creates a new stored fields reader. I wonder if this could be optimized in Lucene too to avoid recreating it every time 🤔

Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/search/lookup/SourceLookup.java:125]: The main issue is that `getSequentialStoredFieldsReader` calls `StoredFieldsReader#getMergeInstance`, which creates a new stored fields reader. I wonder if this could be optimized in Lucene to avoid recreating it every time 🤔

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/search/lookup/SourceLookup.java:125]: I think ideally we'd like to push as much of this up into Lucene as possible, as it is all hacks at the moment and if anything changes in how stored fields are merged then we are in trouble.

**Review by romseygeek — APPROVED** [review]
LGTM

**Review by ywelsch — APPROVED** [review]
LGTM. Thanks @jtibshirani.

**Comment by jtibshirani** [comment]
Thanks for the reviews! I forgot to link the original issue: #82777.

**Comment by jtibshirani** [comment]
@elasticmachine ok to test
