### PR TITLE
Make `-0` compare less than `+0` consistently.

### LINKED ISSUE #22167: Handling of 0.0 and -0.0 in range (lt and gt) queries has changed from 2.4.3 > 5.1.1
**Elasticsearch version**: 5.1.1

**JVM version**: 1.8.0_111

**OS version**: CentOS 6.8

**Description of the problem including expected versus actual behavior**:
When there are 2 documents, 1 with value 0.0 and the other with value -0.0, ES 5.1.1 no longer returns the documents when a range query is execute with either gt -0.0 or lt 0.0. Where as ES 2.4.3 would return the document with value 0.0 for gt -0.0 and return the document with value -0.0 for lt 0.0.

lte and gte do work correctly, lte 0.0 and gte -0.0 return both documents

**Steps to reproduce**:
1. `curl -XPUT localhost:9200/double-test?pretty -d '{ "mappings": { "double-values": { "properties": { "number": { "type": "double" }}}}}'`
```json
{
  "acknowledged" : true,
  "shards_acknowledged" : true
}
```
2. `curl -XPOST localhost:9200/double-testing/double-values?pretty -d '{ "number": 0.0 }'`
```json
{
  "_index" : "double-testing",
  "_type" : "double-values",
  "_id" : "AVj9f_B77DB0gWTRwMi9",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}
```
3. `curl -XPOST localhost:9200/double-testing/double-values?pretty -d '{ "number": -0.0 }'`
```json 
{
  "_index" : "double-testing",
  "_type" : "double-values",
  "_id" : "AVj9f_087DB0gWTRwMi-",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "created" : true
}
```
4. `curl localhost:9200/double-testing/double-values/_search?pretty`
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "double-testing",
        "_type" : "double-values",
        "_id" : "AVj9f_B77DB0gWTRwMi9",
        "_score" : 1.0,
        "_source" : {
          "number" : -0.0
        }
      },
      {
        "_index" : "double-testing",
        "_type" : "double-values",
        "_id" : "AVj9f_087DB0gWTRwMi-",
        "_score" : 1.0,
        "_source" : {
          "number" : 0.0
        }
      }
    ]
  }
}
```
5. `curl localhost:9200/double-testing/double-values/_search?pretty -d '{ "query": { "range": { "number": { "lt": 0.0 }}}}'`
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```
6. `curl localhost:9200/double-testing/double-values/_search?pretty -d '{ "query": { "range": { "number": { "lte": 0.0 }}}}'`
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "double-testing",
        "_type" : "double-values",
        "_id" : "AVj9f_B77DB0gWTRwMi9",
        "_score" : 1.0,
        "_source" : {
          "number" : -0.0
        }
      },
      {
        "_index" : "double-testing",
        "_type" : "double-values",
        "_id" : "AVj9f_087DB0gWTRwMi-",
        "_score" : 1.0,
        "_source" : {
          "number" : 0.0
        }
      }
    ]
  }
}
```
7. `curl localhost:9200/double-testing/double-values/_search?pretty -d '{ "query": { "range": { "number": { "gt": -0.0 }}}}'`
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```
8. `curl localhost:9200/double-testing/double-values/_search?pretty -d '{ "query": { "range": { "number": { "gte": -0.0 }}}}'`
```json
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "double-testing",
        "_type" : "double-values",
        "_id" : "AVj9f_B77DB0gWTRwMi9",
        "_score" : 1.0,
        "_source" : {
          "number" : -0.0
        }
      },
      {
        "_index" : "double-testing",
        "_type" : "double-values",
        "_id" : "AVj9f_087DB0gWTRwMi-",
        "_score" : 1.0,
        "_source" : {
          "number" : 0.0
        }
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by jpountz**
Our `float`/`double` fields generally assume that `-0` compares less than `+0`,
except when bounds are exclusive: an exclusive lower bound on `-0` excludes
`+0` and an exclusive upper bound on `+0` excludes `-0`.

Closes #22167

### CODE REVIEW

**Comment by jpountz** [comment]
@elasticmachine retest this please

File: core/src/test/java/org/elasticsearch/index/mapper/NumberFieldTypeTests.java [hunk 1]
```diff
@@ -149,4 +149,20 @@ public void testHalfFloatRange() throws IOException {
...
+        assertEquals(
+                NumberType.DOUBLE.rangeQuery("field", null, -0d, true, true),
+                NumberType.DOUBLE.rangeQuery("field", null, +0d, true, false));
+        assertEquals(
+                NumberType.FLOAT.rangeQuery("field", null, -0f, true, true),
+                NumberType.FLOAT.rangeQuery("field", null, +0f, true, false));
+        assertEquals(
+                NumberType.HALF_FLOAT.rangeQuery("field", null, -0f, true, true),
+                NumberType.HALF_FLOAT.rangeQuery("field", null, +0f, true, false));
+
```
Comment (jimczi) [inline core/src/test/java/org/elasticsearch/index/mapper/NumberFieldTypeTests.java]: You should also test `nextUp(-0f)` ?:
````
assertEquals(
            NumberFieldMapper.NumberType.DOUBLE.rangeQuery("field", -0f, null, false, false),
            NumberFieldMapper.NumberType.DOUBLE.rangeQuery("field", +0f, null, true, false));
````

**Review by jimczi — APPROVED** [review]
I left comment regarding the tests
LGTM otherwise
