### PR TITLE
ESQL: allow `null` in date math

### LINKED ISSUE #103085: [ES|QL] Null handling in date math
Date math involving nulls fails type resolution.  It looks to me like this happens because we get into `DateTimeArithmeticOperation#resolveType` with one of the types being `null`.  This is different than, for example, `double + null`, which does not end up with a `null` type for the `null` value, presumably because there's only one type it could be.  `datetime + null`, on the other hand, could be either `datetime + period` or `datetime + duration`.  Both of those have `datetime` as the result, but it gets worse with `period + null`, which could have either a `period` or a `datetime`, depending on the type of the `null`

Currently, we expect (and enforce through testing) that expressions involving nulls should still be able to resolve their types.  For now, I'll disable the null checks for adding datetimes, which is unfortunately a somewhat manual process.  Essentially, to enable these tests, add the `anyNullIsNull` call to the test case generation *after* the date cases are in the supplier list.

Relates to https://github.com/elastic/elasticsearch/pull/102830

### PR DESCRIPTION
**Pull request by bpintea**
This fixes `null`'s handling in date math. So far the `null` (of type `NULL`) has been rejected by the type resolution. This is now allowed through, leading to a `null` result, inline with the other types.

Fixes #103085.

### CODE REVIEW

**Comment by bpintea** [comment]
@elasticsearchmachine run elasticsearch-ci elasticsearch-ci/8.12.0 / bwc-snapshots elasticsearch-ci/bwc-snapshots

**Comment by bpintea** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Comment by bpintea** [comment]
@elasticsearchmachine merge upstream

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/type/DataTypes.java [hunk 1]
```diff
@@ -177,6 +177,10 @@ public static boolean isDateTime(DataType type) {
         return type == DATETIME;
     }
 
+    public static boolean isNullOrDateTime(DataType type) {
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/type/DataTypes.java:180]: Since there's already EsqlDataTypes I would remove this method.
Zooming out a bit having both isType and isNullOrType is confusing ? if the null check is so common, why not do it in a generic way instead of having different method variants.

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/type/DataTypes.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/type/DataTypes.java]: 👍 
There's also `isNullOrNumeric()`, so i kept the style, but in fact this method's no longer needed, so I removed it.
