### PR TITLE
Prohibit restoring a data stream alias with a conflicting write data stream

### LINKED ISSUE #80976: Snapshot restore requests allow you to restore alias with write data stream, even if the alias already has a write data stream
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 8.1.0-SNAPSHOT, Build: default/tar/e38cadb5283feeea06f09d555dbe47fb1d5e8b39/2021-11-22T22:35:22.825882Z, JVM: 17.0.1

**OS version** (`uname -a` if on a Unix-like system):
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

I expect ES to reject snapshot restore requests that restore an alias with a write data stream if that alias already exists and has another write data stream. However, ES currently accepts these requests. It appears that the alias uses the restored write data stream, which may be unexpected and confusing to users.

This is likely related to https://github.com/elastic/elasticsearch/issues/80972.

**Steps to reproduce**:

1. Register a snapshot repository

```
PUT /_snapshot/my_repository
{
  "type": "fs",
  "settings": {
    "location": "my_backup_location"
  }
}
```

2. Create the `logs-my_app-default` data stream.

```
POST logs-my_app-default/_doc
{
  "@timestamp": "2099-05-06T16:21:15.000Z"
}
```

3. Add the `logs` alias to the data stream and set it as the write data stream.

```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "logs-my_app-default",
        "alias": "logs",
        "is_write_index": true
      }
    }
  ]
}
```

4. Create a snapshot containing the data stream. This also backs up its alias.

```
PUT _snapshot/my_repository/my_snapshot?wait_for_completion=true
```

5. Delete the data stream.

```
DELETE _data_stream/logs-my_app-default
```

6. Create another data stream, `logs-my_other_app-default`, and add it as the write data stream to the `logs` alias.

```
POST logs-my_other_app-default/_doc
{
  "@timestamp": "2099-05-07T16:21:15.000Z"
}

POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "logs-my_other_app-default",
        "alias": "logs",
        "is_write_index": true
      }
    }
  ]
}
```

7. Restore the `logs-my_app-default` data stream and its aliases from the snapshot.

```
POST /_snapshot/my_repository/my_snapshot/_restore?wait_for_completion=true
{
  "indices": "logs-my_app-default",
  "include_aliases": true
}
```

I expected this to return an error like `alias [logs] has more than one write index [logs-my_other_app-default,logs-my_app-default]`. This occurs for index aliases in a similar situation. However, the request was accepted.

When you check the `logs` alias, the restored `logs-my_app-default` data stream
is the current write data stream:

```
GET _alias/logs
```

Returns:

```
{
  "logs-my_other_app-default" : {
    "aliases" : {
      "logs" : { }
    }
  },
  "logs-my_app-default" : {
    "aliases" : {
      "logs" : {
        "is_write_index" : true
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by martijnvg**
Prohibit restoring a data stream alias if its write data stream conflicts with
the write data stream of an existing data stream alias.

Currently, the write data stream of data stream alias in the snapshot is ignored and
the write data stream of the data stream alias currently active in the cluster
is always picked.

In order to resolve this properly, I've merged the `merge(...)` and `renameDataStreams(...)` 
methods into a `restore(...)` method, which merges a data stream and does renaming at
the same time. This should be ok, since renaming can only be done as part of restoring.
More importantly, this allows to validate whether an existing alias and 
an alias from a snapshot to not have conflicting write data streams while at the same time
allowing that a write data stream to be renamed (because data streams got renamed).

Closes #80976

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java [hunk 1]
```diff
@@ -221,38 +221,60 @@ public DataStreamAlias intersect(Predicate<String> filter) {
...
+                            + "] and write data stream of other ["
+                            + previous.getWriteDataStream()
+                            + "] are different"
+                    );
+                }
+            } else if (writeDataStream == null && previous.getWriteDataStream() != null) {
+                if (mergedDataStreams.contains(previous.getWriteDataStream())) {
+                    writeDataStream = previous.getWriteDataStream();
+                }
+                // else throw error?
```
Comment (danhermann) [inline server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java:273]: Does the case referenced by this comment need to be handled? I don't know how an alias would get into the state where it didn't have its write data stream, but it does seem like we shouldn't just fall through in that case.

Comment (danhermann) [reply server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java:273]: Also, do we need to handle the case where this instance has a write data stream and the `previous` instance does not have a write data stream?

**Review by danhermann — COMMENTED** [review]
I left a couple clarifying questions below.

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java:273]: > Does the case referenced by this comment need to be handled? I don't know how an alias would get into the state where it didn't have its write data stream, but it does seem like we shouldn't just fall through in that case.

Previously we were also not handling this, this is why I added the comment here. I think we should handle it and throw an IllegalStateException if this happens.

> Also, do we need to handle the case where this instance has a write data stream and the previous instance does not have a write data stream?

We kind of handle this via an assertion in the constructor in `DataStreamAlias`. If we would handle this via a normal exception then I think it shouldn't be handled here but the mentioned constructor.

Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamAlias.java]: I don't think it is possible to get into the state whether the write data stream of `previous` instance doesn't exist in `mergedDataStreams` set:
* Defining a data stream alias with a write data stream that does't exist in the list of data streams isn't possible. Mainly because when defining a write data stream then this is done via `is_write_index` boolean flag from the update aliases api and templates. Also there is the assertion in `DataStreamAlias` class' constructor. 
* The `mergedDataStreams` set is based on the data streams of both `this` and `previous` instances.

I've turned this into an assertion in the latest commit that I've pushed.

**Comment by danhermann** [comment]
Thanks, @martijnvg. LGTM.
