### PR TITLE
[Ingest] split string into ArrayList so it can be appended to

### LINKED ISSUE #16109: [Ingest] SplitProcessor does not interoperate well
After a split processor sets a list value, it is of type `Arrays$ArrayList`, and the underlying `add` that is inherited is from `AbstractList` which does not support `add(Object o)`.

here is a sample pipeline that leads to the processor interoperability issue

```json
{
  "pipeline": {
    "processors": [
      {
        "set": {
          "processor_tag": "processor_1",
          "field": "flags",
          "value": "new|hot|super|fun|interesting"
        }
      },
      {
        "split": {
          "processor_tag": "processor_2",
          "field": "flags",
          "separator": "\\|"
        }
      },
      {
        "append": {
          "processor_tag": "processor_3",
          "field": "flags",
          "value": [
            "additional_flag"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {}
    }
  ]
}
```

here is a test to help recreate this:

```java
public void testAppend() throws Exception {
        TemplateService templateService = TestTemplateService.instance();

        Map setConfig = new HashMap<>();
        setConfig.put("field", "flags");
        setConfig.put("value", "new|hot|super|fun|interesting");
        Processor p1 = (new SetProcessor.Factory(templateService)).create(setConfig);

        Map splitConfig = new HashMap<>();
        splitConfig.put("field", "flags");
        splitConfig.put("separator", "\\|");
        Processor p2 = (new SplitProcessor.Factory()).create(splitConfig);

        Map appendConfig = new HashMap<>();
        appendConfig.put("field", "flags");
        appendConfig.put("value", Collections.singletonList("additional_flag"));
        Processor p3 = (new AppendProcessor.Factory(templateService)).create(appendConfig);

        CompoundProcessor compoundProcessor = new CompoundProcessor(p1, p2, p3);

        IngestDocument ingestDocument = new IngestDocument(new HashMap<>(), new HashMap<>());
        compoundProcessor.execute(ingestDocument);
}
```

exception thrown:

```
java.lang.UnsupportedOperationException
	at __randomizedtesting.SeedInfo.seed([73BE8BBD9217E836:9B6A3F6987AE9240]:0)
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.elasticsearch.ingest.core.IngestDocument$$Lambda$1/1854908422.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.elasticsearch.ingest.core.IngestDocument.appendValues(IngestDocument.java:415)
	at org.elasticsearch.ingest.core.IngestDocument.appendValues(IngestDocument.java:407)
	at org.elasticsearch.ingest.core.IngestDocument.setFieldValue(IngestDocument.java:358)
	at org.elasticsearch.ingest.core.IngestDocument.appendFieldValue(IngestDocument.java:264)
	at org.elasticsearch.ingest.core.IngestDocument.appendFieldValue(IngestDocument.java:281)
	at org.elasticsearch.ingest.processor.AppendProcessor.execute(AppendProcessor.java:60)
	at org.elasticsearch.ingest.core.CompoundProcessor.execute(CompoundProcessor.java:73)
```

thanks to @BigFunger for reporting this!

### PR DESCRIPTION
**Pull request by talevy**
Fixes #16109.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java [hunk 1]
```diff
@@ -60,7 +62,9 @@ public void execute(IngestDocument document) {
         if (oldVal == null) {
             throw new IllegalArgumentException("field [" + field + "] is null, cannot split.");
         }
-        document.setFieldValue(field, Arrays.asList(oldVal.split(separator)));
+        @SuppressWarnings("unchecked")
+        List<String> splitList = new ArrayList<>(Arrays.asList(oldVal.split(separator)));
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java]: creating two ArrayLists may not be the best thing to do. Lets do this instead:

```
List<String> splitList = new ArrayList<>();
Collections.addAll(splitList, oldVal.split(separator));
```

**Comment by javanna** [comment]
left a comment, LGTM otherwise. Good catch, I wonder if other processors have the same problem, will double check.

**Comment by javanna** [comment]
I quickly double checked, seems to me that only the geoip processor might have the same processor as it uses `Arrays.asList` for the location array. It will not be possible to add anything to that array, less of a problem compared to split but we should change that I think.

**Comment by s1monw** [comment]
this is likely the most inefficient way to do this that I can think of? If we wanna support that level of analysis why don't we use analyzers? Or if we really need to do this add support for `Appendable.java` and put it in a StringBuilder?

File: core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java (hunk 1 above)
Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java]: noted

**Comment by s1monw** [comment]
> this is likely the most inefficient way to do this that I can think of? If we wanna support that level of analysis why don't we use analyzers? Or if we really need to do this add support for Appendable.java and put it in a StringBuilder?

I guess that is what we have to deal with - nevermind

File: core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java [hunk 2]
```diff
@@ -60,7 +63,9 @@ public void execute(IngestDocument document) {
         if (oldVal == null) {
             throw new IllegalArgumentException("field [" + field + "] is null, cannot split.");
         }
-        document.setFieldValue(field, Arrays.asList(oldVal.split(separator)));
+        List<String> splitList = new ArrayList<>();
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java]: maybe `List<String> splitList = new ArrayList<>(oldVal.split(separator));` that way we use the right size for that array list?

Comment (javanna) [inline core/src/main/java/org/elasticsearch/ingest/processor/SplitProcessor.java]: you mean providing the size of the array I guess? cause I don't see a constructor that accepts an array in ArrayList.

File: core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java [hunk 3]
```diff
@@ -108,4 +114,30 @@ public void testSingleProcessorWithNestedFailures() throws Exception {
         assertThat(processorToFail.getInvokedCounter(), equalTo(1));
         assertThat(lastProcessor.getInvokedCounter(), equalTo(1));
     }
+
+    public void testSetSplitAppend() throws Exception {
+        TemplateService templateService = TestTemplateService.instance();
```
Comment (martijnvg) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: It feels to me that this test should move to `SplitProcessorTests`? I see that we need to create two processors, but that is also okay in `SplitProcessorTests`?

Comment (talevy) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: wasn't sure whether we should create other processors within the `SplitProcessorTests`. then yes, this can be moved there

**Comment by martijnvg** [comment]
LGTM
