### PR TITLE
[ML] Initialize backing indices before running integration test

### LINKED ISSUE #117208: [CI] DefaultEndPointsIT testMultipleInferencesTriggeringDownloadAndDeploy failing
**Build Scans:**
- [elasticsearch-intake #30570 / part2](https://gradle-enterprise.elastic.co/s/gdavlpndt3zyi)
- [elasticsearch-intake #30569 / part2](https://gradle-enterprise.elastic.co/s/vtfzw5cnqttl4)
- [elasticsearch-pull-request #101022 / part-2](https://gradle-enterprise.elastic.co/s/pyjfp4yhowcvm)
- [elasticsearch-pull-request #101021 / part-2](https://gradle-enterprise.elastic.co/s/b656xgt7krruw)
- [elasticsearch-pull-request #101015 / part-2](https://gradle-enterprise.elastic.co/s/rmqlzlueiurrs)
- [elasticsearch-pull-request #101012 / part-2](https://gradle-enterprise.elastic.co/s/phfhnnj3wmuxi)
- [elasticsearch-pull-request #100995 / part-2](https://gradle-enterprise.elastic.co/s/utufxrej5eche)
- [elasticsearch-pull-request #100992 / part-2](https://gradle-enterprise.elastic.co/s/gonxpo7ksh4bs)
- [elasticsearch-pull-request #100973 / part-2](https://gradle-enterprise.elastic.co/s/pffjm2a2dkfui)
- [elasticsearch-pull-request #100961 / part-2](https://gradle-enterprise.elastic.co/s/w2yynkky2j5aa)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:qa:inference-service-tests:javaRestTest" --tests "org.elasticsearch.xpack.inference.DefaultEndPointsIT.testMultipleInferencesTriggeringDownloadAndDeploy" -Dtests.seed=BA33C76A56DA53F8 -Dtests.locale=ks-IN -Dtests.timezone=Asia/Dubai -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.DefaultEndPointsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMultipleInferencesTriggeringDownloadAndDeploy'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: [org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:33287], URI [_inference/.elser-2-elasticsearch?timeout=120s], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"no_shard_available_action_exception","reason":null}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":".ml-inference-000005","node":null,"reason":{"type":"no_shard_available_action_exception","reason":null}}]},"status":503}]
Expected: an empty collection
     but: <[org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:33287], URI [_inference/.elser-2-elasticsearch?timeout=120s], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"no_shard_available_action_exception","reason":null}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"sha
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testMultipleInferencesTriggeringDownloadAndDeploy
- [main] 2 consecutive failures in step part2
- [main] 2 consecutive failures in step part-2
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 2 consecutive failures in pipeline elasticsearch-pull-request
- [main] 14 failures in test testMultipleInferencesTriggeringDownloadAndDeploy (19.2% fail rate in 73 executions)
- [main] 2 failures in step part2 (16.7% fail rate in 12 executions)
- [main] 12 failures in step part-2 (21.1% fail rate in 57 executions)
- [main] 2 failures in pipeline elasticsearch-intake (16.7% fail rate in 12 executions)
- [main] 11 failures in pipeline elasticsearch-pull-request (20.8% fail rate in 53 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jonathan-buttner**
This PR addresses this issue: https://github.com/elastic/elasticsearch/issues/117208

The test is trying to download and deploy the elser model and it is also persisting an inference endpoint while doing that.

This fix tries to force the backing indices to be created by persisting a model before we try executing multiple elser requests.

### CODE REVIEW

File: x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/DefaultEndPointsIT.java [hunk 1]
```diff
@@ -194,7 +194,11 @@ private static void assertDefaultChunkingSettings(Map<String, Object> modelConfi
         );
     }
 
-    public void testMultipleInferencesTriggeringDownloadAndDeploy() throws InterruptedException {
+    public void testMultipleInferencesTriggeringDownloadAndDeploy() throws InterruptedException, IOException {
+        // Creating an inference endpoint to force the backing indices to be created to reduce the likelihood of the test failing
+        // because it's trying to interact with the indices while they're being created.
+        putModel("initial-model", mockCompletionServiceModelConfig(TaskType.SPARSE_EMBEDDING, "streaming_completion_test_service"));
```
Comment (DonalEvans) [inline x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/DefaultEndPointsIT.java]: If you delete this endpoint right after creating it, will the backing indices still exist? If so, it would be cleaner to create then delete the endpoint so that you don't need to account for an extra endpoint hanging around in other tests.

Comment (jonathan-buttner) [reply x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/DefaultEndPointsIT.java]: Yeah I'll give that a shot 👍

**Review by DonalEvans — APPROVED** [review]
