### PR TITLE
Fix reused/recovered bytes for files that are only partially recovered from cache

### LINKED ISSUE #95970: [CI] SearchableSnapshotsIntegTests testCreateAndRestoreSearchableSnapshot failing
This failed on my PR but it also failed on main
https://gradle-enterprise.elastic.co/s/f7u3hmmpeq4ea/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests/testCreateAndRestoreSearchableSnapshot?top-execution=1

**Build scan:**
https://gradle-enterprise.elastic.co/s/tmgmqv3w6wqbi/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests/testCreateAndRestoreSearchableSnapshot

**Reproduction line:**
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=F254F4CE380F344 -Dtests.locale=ko -Dtests.timezone=Pacific/Tahiti -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests&tests.test=testCreateAndRestoreSearchableSnapshot

**Failure excerpt:**
```
java.lang.AssertionError: {
  "id" : 0,
  "type" : "SNAPSHOT",
  "stage" : "DONE",
  "primary" : true,
  "start_time" : "2023-05-10T02:44:59.350Z",
  "start_time_in_millis" : 1683686699350,
  "stop_time" : "2023-05-10T02:44:59.494Z",
  "stop_time_in_millis" : 1683686699494,
  "total_time" : "144ms",
  "total_time_in_millis" : 144,
  "source" : {
    "repository" : "WXIUlVPqla",
    "snapshot" : "ztjlngbijj",
    "version" : "8.9.0",
    "index" : "bzgoilgdco",
    "restoreUUID" : "_no_api_"
  },
  "target" : {
    "id" : "j9x9FzydQdGKjmyyhRU_AA",
    "host" : "127.0.0.1",
    "transport_address" : "127.0.0.1:26622",
    "ip" : "127.0.0.1",
    "name" : "node_s1"
  },
  "index" : {
    "size" : {
      "total" : "56.9kb",
      "total_in_bytes" : 58266,
      "reused" : "1kb",
      "reused_in_bytes" : 1080,
      "recovered" : "55.4kb",
      "recovered_in_bytes" : 56798,
      "recovered_from_snapshot" : "55.4kb",
      "recovered_from_snapshot_in_bytes" : 56798,
      "percent" : "99.3%"
    },
    "files" : {
      "total" : 7,
      "reused" : 3,
      "recovered" : 3,
      "percent" : "75.0%"
    },
    "total_time" : "122ms",
    "total_time_in_millis" : 122,
    "source_throttle_time" : "-1",
    "source_throttle_time_in_millis" : 0,
    "target_throttle_time" : "-1",
    "target_throttle_time_in_millis" : 0
  },
  "translog" : {
    "recovered" : 0,
    "total" : 0,
    "percent" : "100.0%",
    "total_on_start" : 0,
    "total_time" : "33ms",
    "total_time_in_millis" : 33
  },
  "verify_index" : {
    "check_index_time" : "0s",
    "check_index_time_in_millis" : 0,
    "total_time" : "0s",
    "total_time_in_millis" : 0
  }
}
Expected: <4>
     but: was <3>

  at __randomizedtesting.SeedInfo.seed([F254F4CE380F344:854638377017A2F7]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.searchablesnapshots.BaseSearchableSnapshotsIntegTestCase.lambda$assertRecoveryStats$2(BaseSearchableSnapshotsIntegTestCase.java:330)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1158)
  at org.elasticsearch.xpack.searchablesnapshots.BaseSearchableSnapshotsIntegTestCase.assertRecoveryStats(BaseSearchableSnapshotsIntegTestCase.java:323)
  at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot(SearchableSnapshotsIntegTests.java:293)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### LINKED ISSUE #95994: [CI] SearchableSnapshotRecoveryStateIntegrationTests testRecoveryStateRecoveredBytesMatchPhysicalCacheState failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/w3y6276h3es4g/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.recovery.SearchableSnapshotRecoveryStateIntegrationTests/testRecoveryStateRecoveredBytesMatchPhysicalCacheState

**Reproduction line:**
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.recovery.SearchableSnapshotRecoveryStateIntegrationTests.testRecoveryStateRecoveredBytesMatchPhysicalCacheState" -Dtests.seed=37CF1F75CEB7D168 -Dtests.locale=el-CY -Dtests.timezone=America/Indiana/Petersburg -Druntime.java=20
```

**Applicable branches:**
8.8

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.recovery.SearchableSnapshotRecoveryStateIntegrationTests&tests.test=testRecoveryStateRecoveredBytesMatchPhysicalCacheState

**Failure excerpt:**
```
java.lang.AssertionError: Physical cache size doesn't match with recovery state data
Expected: <9744L>
     but: was <10768L>

  at __randomizedtesting.SeedInfo.seed([37CF1F75CEB7D168:792DC5E477402C60]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.searchablesnapshots.recovery.SearchableSnapshotRecoveryStateIntegrationTests.testRecoveryStateRecoveredBytesMatchPhysicalCacheState(SearchableSnapshotRecoveryStateIntegrationTests.java:106)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by tlrx**
Before #95891 a file was considered as reused in recovery if 
it was fully cached in the cold persistent cache. Otherwise 
the full file length was reported as recovered from the 
blob store during prewarming.

While working on #95891 I changed the 
CachedBlobContainerIndexInput.prefetchPart() 
method to be more precise on the number of bytes that were 
effectively read from the blob store during prewarming.

But this obviously broke some tests (#95970) because a file 
cannot be partially recovered from disk and from remote. This 
change restores the previous behavior with one adjustment: 
the file is considered as reused if the prewarm method 
effectively prefetched 0 bytes.

Closes #95970
Closes #95994

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/SearchableSnapshotDirectory.java [hunk 1]
```diff
@@ -506,10 +506,13 @@ private void prewarmCache(ActionListener<Void> listener, Supplier<Boolean> cance
 
                     final AtomicLong prefetchedBytes = new AtomicLong(0L);
                     try (var fileListener = new RefCountingListener(ActionListener.runBefore(completionListener.acquire().map(v -> {
-                        if (prefetchedBytes.get() == 0L) {
+                        // we can't report a file as being partially recovered from disk and partially from the blob store, but this is
+                        // something that can happen for fully mounted searchable snapshots. So we make a choice here: if less than 50%
+                        // of the file is prewarmed from the blob store then it is marked as reused from cache.
+                        if ((prefetchedBytes.get() / (double) file.length()) < 0.5d) {
```
Comment (idegtiarenko) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/SearchableSnapshotDirectory.java:512]: Is there a chance this could break for a very small segment files?
I am thinking about example where 1/3 parts were in disk already and we only downloaded 2/3.

I wonder if we should consider changins `boolean reused` to `long reused` in `FileDetail` and consider a file fully recovered when `recovered < length && reused + recovered == length`?

Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/SearchableSnapshotDirectory.java:512]: I'm not sure to understand why it would break for small files? We're comparing the number of bytes prewarmed with the total file length so the number of parts do not really matter. Also, most small files are likely to be either fully prewarmed or fully reused.

> I wonder if we should consider changins `boolean reused` to `long reused` in `FileDetail` and consider a file fully recovered when `recovered < length && reused + recovered == length`?

We could but this is a larger change that I don't think is really worth doing since it only makes sense for cold cache.

Comment (idegtiarenko) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/SearchableSnapshotDirectory.java:512]: I am trying to understand if there is something that guarantee that the following would not happen:
* 2/3 are already cached locally and would not be downloaded
* 1/3 is downloaded updating a stats so that it expects something would complete download before reporting it as finished.

**Comment by idegtiarenko** [comment]
Is it worth adding an assertion somewhere around 
https://github.com/elastic/elasticsearch/blob/bb3ef551b484b3f9c68b3a60affbfadfff05c552/x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/SearchableSnapshotDirectory.java#L477
that would verify that for each index for each FileDetail we have `assert reused ^ recovered == length` (possibly in a separate pr)?

**Comment by tlrx** [comment]
@elasticmachine run test please

**Comment by tlrx** [comment]
@elasticmachine retest this please

**Comment by tlrx** [comment]
Thanks @idegtiarenko for your feedback. I reworked this change to revert to the previous behavior.

> Is it worth adding an assertion somewhere around [..] that would verify that for each index for each FileDetail we have assert reused ^ recovered == length (possibly in a separate pr)?

I suppose we can yes. We don't have must assertions around recovery file details but I can add one as a follow up.

**Review by idegtiarenko — APPROVED** [review]

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by tlrx** [comment]
Thanks Ievgen!
