### PR TITLE
Warn on not enough masters during election

### LINKED ISSUE #8362: Elastic should log what's the expected number of nodes to elect master, when it fails
In https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java#L1037 Elastic logs that it was not possible to elect master from active nodes. Since min_number of nodes is a transient value - its current value should be logged here as well, to understand how many was ussing

### PR DESCRIPTION
**Pull request by pickypg**
This changes the trace level logging to warn, and adds the needed number to the message as well.

My fear is that it may get noisy, but this is an issue that you want to be noisy.

Closes #8362

### CODE REVIEW

**Comment by dakrone** [comment]
@pickypg this probably needs a rebase now that the log4j2 stuff is in, right?

**Comment by clintongormley** [comment]
@pickypg want to rebase and get this in?

**Comment by pickypg** [comment]
@clintongormley Done

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 1]
```diff
@@ -571,7 +572,11 @@ public String toString() {
 
             final BatchResult.Builder<Task> resultBuilder = BatchResult.<Task>builder().successes(tasks);
             if (!electMasterService.hasEnoughMasterNodes(remainingNodesClusterState.nodes())) {
-                return resultBuilder.build(rejoin.apply(remainingNodesClusterState, "not enough master nodes"));
+                final int masterNodes = electMasterService.countMasterNodes(remainingNodesClusterState.nodes());
+                final String message =
+                    LoggerMessageFormat.format("not enough master nodes [{}], but needed [{}]",
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: this can be confusing - maybe "not enough master nodes (has [{}], needed [{}])"?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 2]
```diff
@@ -922,7 +927,7 @@ private DiscoveryNode findMaster() {
                 return winner.getNode();
             } else {
                 // if we don't have enough master nodes, we bail, because there are not enough master to elect from
-                logger.trace("not enough master nodes [{}]", masterCandidates);
+                logger.warn("not enough master nodes [{}], but needed [{}]", masterCandidates, electMaster.minimumMasterNodes());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: since we promote this to first class message, I think we should make it more user friendly. how about "not enough master nodes discovered during pinging (found [{}], needed [{}]), pinging again" ?

**Review by bleskes — APPROVED** [review]
LGTM. Left two nits.

**Comment by dakrone** [comment]
@pickypg are you going to *pick* (hah, get it?) this back up?

**Comment by pickypg** [comment]
@dakrone Yeah, I'll rebase and make changes today.

**Comment by pickypg** [comment]
@dakrone / @bleskes rebased on master and finally updated

**Comment by pickypg** [comment]
5.x/5.5: 23ff820
5.4: edee015
