### PR TITLE
Force rollover on write to true when data stream indices list is empty

### LINKED ISSUE #133176: Failure store fails to initialize on data streams from prior cluster versions
During the cluster upgrade process, any existing data streams from a previous cluster will receive default failure store state when deserialized. This default failure store state that is defined in the serialization code is invalid for normal failure store function in that it sets the failure store's `rollover_on_write` flag to be `false` and defaults the failure store indices list to be an empty list. The `rollover_on_write` flag is used to excuse this empty failure index list in several validation steps, and is relied upon to correctly initialize the failure store on its first use.

When deserializing a data stream that has no failure store state, a new state with no indices and `rollover_on_write` set to `true` should be created instead.

### Work around
In the event that a data stream is upgraded and does not have `rollover_on_write` set to true for its empty failure store, a new failure store index must be transplanted into the affected data stream to initialize its state.

```javascript
// Create a new data stream which we will use to create a donor failure index.
PUT _index_template/donor-template
{
  "index_patterns": ["donor-datastream"],
  "data_stream": {},
  "template": {
    "data_stream_options": {
      "failure_store": {
        "enabled": true
      }
    }
  }
}
PUT _data_stream/donor-datastream

// Rollover the donor data stream twice to create a donor failure index that we will remove and a write index that will stay behind
POST donor-datastream::failures/_rollover
POST donor-datastream::failures/_rollover

// Remove the donor failure index from the first data stream, and add it to the affected data stream's failure indices.
POST _data_stream/_modify
{
  "actions": [
    {
      "remove_backing_index": {
        "index": ".fs-donor-datastream-2025.08.19-000002",
        "data_stream": "donor-datastream",
        "failure_store": true
      }
    },
    {
      "add_backing_index": {
        "index": ".fs-donor-datastream-2025.08.19-000002",
        "data_stream": "affected-data-stream",
        "failure_store": true
      }
    }
  ]
}

// Rollover the affected data stream to ensure it is correctly initialized
POST logs-okta.system-default::failures/_rollover

// Delete the donor data stream and its template to clean up
DELETE _data_stream/donor-datastream
DELETE _index_template/donor-template
```

### PR DESCRIPTION
**Pull request by jbaiera**
If a data stream indices list is ever empty, then it cannot accept any write traffic. This is a state that is not allowed in the normal backing indices, but as we add more index sets to a data stream that are lazily created like failure store, this property should not only reflect any state that was marked via a lazy rollover API call, but also be forced on when no indices exist so that they may be initialized on first write.

An upgrade test is present to ensure that failure store indices created on versions from before their support are able to be enabled and used.

Fixes #133176

### CODE REVIEW

File: qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+        indexRequest.setJsonEntity(docBody.replace("$now", formatInstant(Instant.now())));
+        Response response = null;
+        try {
+            response = client().performRequest(indexRequest);
+        } catch (ResponseException re) {
+            response = re.getResponse();
+        }
+        assertNotNull(response);
+        System.out.println(response);
+        System.out.println(responseAsMap(response));
```
Comment (samxbr) [inline qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java]: Remove these print?

File: qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+            dataStreams = getDataStream(dataStreamName);
+            assertThat(ObjectPath.evaluate(dataStreams, "data_streams"), hasSize(1));
+            assertThat(ObjectPath.evaluate(dataStreams, "data_streams.0.name"), equalTo(dataStreamName));
+            assertThat(ObjectPath.evaluate(dataStreams, "data_streams.0.failure_store"), notNullValue());
+            assertThat(ObjectPath.evaluate(dataStreams, "data_streams.0.failure_store.enabled"), equalTo(true));
+            assertThat(ObjectPath.evaluate(dataStreams, "data_streams.0.failure_store.indices"), is(not(empty())));
+            assertThat(ObjectPath.evaluate(dataStreams, "data_streams.0.failure_store.rollover_on_write"), equalTo(false));
+
+            String failureIndexName = ObjectPath.evaluate(dataStreams, "data_streams.0.failure_store.indices.0.index_name");
+            assertThat(failureIndexName, dataStreamIndexEqualTo(dataStreamName, 2, true));
```
Comment (samxbr) [inline qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java:178]: Previously there's no failure store backing index, and we rollover once, curious why is it generation 2 instead of 1?

**Comment by jbaiera** [comment]
CI is failing because rollover on write is forced true on any data stream index set which is empty, but this is not allowed because data streams created for CCR may not have rollover on write enabled. As such, I have a fix coming in which should simply update the default places in deserialization that we set the flag and make them default to true on an empty index list.

Edit: Applied in d07c763 and e2025f6

File: qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java (hunk 2 above)
Comment (jbaiera) [reply qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java:178]: The generation is universal across all indices created under the data stream. When we create the data stream, the generation is at 1. When the failure store is created, either from the rollover operation or due to initializing on the first write, the generation is increased (to 2) and used for the failure index name.

File: qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java (hunk 1 above)
Comment (jbaiera) [reply qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java]: AH yeah, my crude debugging skills have been exposed!

File: qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java (hunk 2 above)
Comment (samxbr) [reply qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/FailureStoreUpgradeIT.java:178]: I see, thanks for the explanation!

**Review by masseyke — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java [hunk 3]
```diff
@@ -214,7 +214,7 @@ public DataStream(
             lifecycle,
             dataStreamOptions,
             new DataStreamIndices(BACKING_INDEX_PREFIX, List.copyOf(indices), rolloverOnWrite, autoShardingEvent),
-            new DataStreamIndices(FAILURE_STORE_PREFIX, List.copyOf(failureIndices), false, null)
+            new DataStreamIndices(FAILURE_STORE_PREFIX, List.copyOf(failureIndices), failureIndices.isEmpty(), null)
```
Comment (samxbr) [inline server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java]: ~Is the reason we force `rolloverOnWrite` as a param to the next constructor here instead other constructor to bypass the CCR error you mentioned? If so I find it a little subtle to read, but I am not sure how to do it more explicitly.~
Disregard this, I think I mis-read the constructor arguments, there are too many of them

**Review by samxbr — APPROVED** [review]
LGTM

**Comment by jbaiera** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/133406)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/133407)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
