### PR TITLE
Simplify Unicast Zen Ping

### LINKED ISSUE #19370: Thread leak in TribeNode when a cluster is offline
**Elasticsearch version**:  2.3.4
**JVM version**: 1.8.0_91
**OS version**: RedHat 6.5

We are using the TribeNode feature to enable search across a number of geographically distributed ElasticSearch clusters.  Occasionally when we take one of these clusters completely offline, we find that our TribeNode hits the following exception:

```
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
        at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
        at org.elasticsearch.threadpool.ThreadPool$ThreadedRunnable.run(ThreadPool.java:676)
        at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:640)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

This exception is thrown because of thread exhaustion due to the TribeNode creating a new thread every couple of seconds.  Below is the stack trace of the leaked threads:

```
java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
       java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
       java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
       java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
       java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
       java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
       org.elasticsearch.common.util.concurrent.KeyedLock.acquire(KeyedLock.java:75)
       org.elasticsearch.transport.netty.NettyTransport.disconnectFromNode(NettyTransport.java:1063)
       org.elasticsearch.transport.TransportService.disconnectFromNode(TransportService.java:274)
       org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2$1.doRun(UnicastZenPing.java:258)
       org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       java.lang.Thread.run(Thread.java:745)
```

**Steps to reproduce**:
 Create TribeNode configuration where one cluster is offline.   Its not enough that the processes are shutdown and the machine is online, the nodes specified in the discovery.zen.ping.unicast.hosts for the offline cluster must be offline and not respond to ping/connection attempts.    Here is a simple configuration I was able to use to reproduce the problem.

```

---
cluster.name: "thread-leak-test"
node.name: "thread-leak-node"
http.port: "9201"
http.host: "127.0.0.1"
tribe:
  online-cluster:
    cluster.name: "online-cluster"
    discovery.zen.ping.unicast.hosts:
    - "localhost"
  offline-cluster:
    cluster.name: "offline-cluster"
    discovery.zen.ping.unicast.hosts:
    - "10.10.10.10"
```

Start the Tribe node.   Observe that the number of threads continue to grow unbounded (`ps -m <pid> | wc -l`) until the OutOfMemoryError: unable to create new native thread exceptions are thrown.

This issue appears similar to the problem described in #8057.

### LINKED ISSUE #21739: FileBasedDiscovery causes connections on every ping round
Currently `UnicastHostsProvider#buildDynamicNodes` is called multiple times during the pinging rounds. Once on start, one more after 1.5 seconds (by default) and last time at the end (3s by default).  My guess is that this done in an attempt to get the latest information possible when connect to EC2 / GCE/ Azure's API. This does have a nasty side effect on the FileBasedUnicastHostsProvider, which currently reads it's file on ever call. The file reading is not a problem on it's own as it is just as fast as an EC2 call. The problem part is that each read generates nodes with new node ids, meaning that UnicastZenPing will setup new connections with each of these rounds. 

I see two relatively easy ways of solving it:
1) Call `buildDynamicNodes` once at the beginning of each round (might be the simplest).
2) Add an "onStartPing" method to `UnicastHostsProvider` which is guaranteed to be called at the beginning of each pinging round. `FileBasedDiscovery` can read the file contents in that method.

### PR DESCRIPTION
**Pull request by bleskes**
The `UnicastZenPing` shows it's age and is the result of many small changes. The current state of affairs is confusing and is hard to reason about. This PR cleans it up (while following the same original intentions). Highlights of the changes are:

1) Clear 3 round flow - no interleaving of scheduling.
2) The previous implementation did a best effort attempt to wait for ongoing pings to be sent and completed. The pings were guaranteed to complete because each used the total ping duration as a timeout. This did make it hard to reason about the total ping duration and the flow of the code. All of this is removed now and ping should just complete within the given duration or not be counted (note that it was very handy for testing, but I move the needed sync logic to the test).
3) Because of (2) the pinging scheduling changed a bit, to give a chance for the last round to complete. We now ping at the beginning, 1/3 and 2/3 of the duration.
4) To offset for (3) a bit, incoming ping requests are now added to on going ping collections.
5) UnicastZenPing never establishes full blown connections (but does reuse them if there). Relates to #22120
6) Discovery host providers are only used once per pinging round. Closes #21739
7) Usage of the ability to open a connection without connecting to a node ( #22194 ) and shorter connection timeouts helps with connections piling up. Closes #19370
8) Beefed up testing and sped them up.
9) removed light profile from production code

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/discovery/zen/ElectMasterService.java [hunk 1]
```diff
@@ -24,7 +24,6 @@
 import org.elasticsearch.cluster.ClusterState;
 import org.elasticsearch.cluster.node.DiscoveryNode;
 import org.elasticsearch.common.component.AbstractComponent;
-import org.elasticsearch.common.inject.Inject;
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/ElectMasterService.java]: 💥

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 2]
```diff
@@ -266,106 +263,104 @@ public void clearTemporalResponses() {
...
+            seedNodes = resolveHostsLists(
                 unicastZenPingExecutorService,
                 logger,
                 configuredHosts,
                 limitPortCounts,
                 transportService,
-                () -> UNICAST_NODE_PREFIX + unicastNodeIdGenerator.incrementAndGet() + "#",
+                UNICAST_NODE_PREFIX,
                 resolveTimeout);
         } catch (InterruptedException e) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: please restore the interrupt status here?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 3]
```diff
@@ -266,106 +263,104 @@ public void clearTemporalResponses() {
...
+            seedNodes.add(masterNode.value);
+        }
+
+        final PingingRound pingingRound = new PingingRound(pingingRoundIdGenerator.incrementAndGet(), seedNodes, resultsConsumer,
+            nodes.getLocalNode(), ConnectionProfile.getLightProfileWithTimeout(requestDuration, requestDuration));
+        activePingingRounds.put(pingingRound.id(), pingingRound);
+        final AbstractRunnable pingSender = new AbstractRunnable() {
+            @Override
+            public void onFailure(Exception e) {
+                if (e instanceof AlreadyClosedException) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: maybe `(e instanceof AlreadyClosedException) == false`?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 4]
```diff
@@ -377,154 +372,173 @@ public boolean isClosed() {
             return this.closed.get();
         }
 
-        public PingCollection pingCollection() {
-            return pingCollection;
+        public List<DiscoveryNode> getSeedNodes() {
+            checkIfClosed();
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: we call it `ensureOpen` everywhere can we do the same here?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 5]
```diff
@@ -377,154 +372,173 @@ public boolean isClosed() {
...
+            return tempConnections.get(address);
+        }
+
+        private void checkIfClosed() {
+            if (isClosed()) {
+                throw new AlreadyClosedException("pinging round [" + id + "] is finished");
+            }
+        }
+
+        public synchronized Connection addConnectionIfNeeded(TransportAddress address, Connection newConnection) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: hmm that looks weird. Can we maybe use a `KeyedLock` when we open the connections with IP and port or something like this?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 6]
```diff
@@ -377,154 +372,173 @@ public boolean isClosed() {
...
+                tempConnections.put(address, newConnection);
+                return newConnection;
+            } else {
+                IOUtils.closeWhileHandlingException(newConnection);
+                return existing;
+            }
+        }
+
+        public void addPingResponseToCollection(PingResponse pingResponse) {
+            if (pingResponse.node().equals(localNode) == false) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: use `localNode.equals(incomingObject)` we know that `localnode` is non-null

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 7]
```diff
@@ -377,154 +372,173 @@ public boolean isClosed() {
...
+        }).collect(Collectors.toSet());
 
-        // add all possible master nodes that were active in the last known cluster configuration
-        for (ObjectCursor<DiscoveryNode> masterNode : discoNodes.getMasterNodes().values()) {
-            nodesToPingSet.add(masterNode.value);
-        }
+        // dedup by address
+        final Map<TransportAddress, DiscoveryNode> uniqueNodesByAddress =
+            Stream.concat(pingingRound.getSeedNodes().stream(), nodesFromResponses.stream())
+                .collect(Collectors.toMap(DiscoveryNode::getAddress, n -> n, (n1, n2) -> n1));
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: if you wanna be more explicit you can use `Function::identity` to make sure it's not a typo

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 8]
```diff
@@ -377,154 +372,173 @@ public boolean isClosed() {
...
+        submitToExecutor(new AbstractRunnable() {
+            @Override
+            protected void doRun() throws Exception {
+                Connection connection = null;
+                if (transportService.nodeConnected(node)) {
+                    try {
+                        // concurrency can still cause disconnects
+                        connection = transportService.getConnection(node);
+                    } catch (NodeNotConnectedException e) {
+                        // meh
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: maybe log this?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 9]
```diff
@@ -377,154 +372,173 @@ public boolean isClosed() {
...
-                            logger.warn(
-                                (Supplier<?>) () -> new ParameterizedMessage(
-                                    "[{}] failed send ping to {}", sendPingsHandler.id(), finalNodeToSend), e);
-                        } finally {
-                            if (!success) {
-                                latch.countDown();
-                            }
+
+                if (connection == null) {
+                    logger.trace("[{}] connecting (light) to {}", pingingRound.id(), node);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: do we need this trace log here and if so can we fix it to say `temporarily` or something like this

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 10]
```diff
@@ -538,50 +552,34 @@ public String executor() {
...
-                                logger.warn("received ping response {} with no matching handler id [{}]", pingResponse, response.id);
-                            }
-                        } else {
-                            sendPingsHandler.pingCollection().addPing(pingResponse);
-                        }
-                    }
-                } finally {
-                    latch.countDown();
+                logger.trace("[{}] received response from {}: {}", pingingRound.id(), node, Arrays.toString(response.pingResponses));
+                if (pingingRound.isClosed() == false) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: just flip it then you don't need to negate

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 11]
```diff
@@ -538,50 +552,34 @@ public String executor() {
...
-                                // Only log when we're not closing the node. Having no send ping handler is then expected
-                                logger.warn("received ping response {} with no matching handler id [{}]", pingResponse, response.id);
-                            }
-                        } else {
-                            sendPingsHandler.pingCollection().addPing(pingResponse);
-                        }
-                    }
-                } finally {
-                    latch.countDown();
+                logger.trace("[{}] received response from {}: {}", pingingRound.id(), node, Arrays.toString(response.pingResponses));
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: if you keep the trace maybe use a logging guard here?

File: core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java [hunk 12]
```diff
@@ -38,13 +39,22 @@
...
-            TransportRequestOptions.Type.STATE))), 1, null, null);
+    public static final ConnectionProfile LIGHT_PROFILE = getLightProfileWithTimeout(null, null);
+
+    /**
+     * Builds a light connection profile that shares a single connection across all
+     * types, using the given timeouts
+     */
+    public static ConnectionProfile getLightProfileWithTimeout(@Nullable TimeValue connectTimeout,
+                                                               @Nullable TimeValue handshakeTimeout) {
+        return new ConnectionProfile(
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java]: I wonder if we should do this. I think we should move the `LIGHT_PROFILE` into tests somewhere and then require every special use to build it's own. The problem I have here is that the `getLightProfileWithTimeout` shares one connection across all uses. I think in the case of ping we should only use 1 connection for `PING` and 0 for the others. that will cause an exception if it's used in a wrong context. makes sense?

File: core/src/main/java/org/elasticsearch/transport/TransportService.java [hunk 13]
```diff
@@ -329,32 +328,6 @@ public void connectToNode(final DiscoveryNode node, ConnectionProfile connection
...
-     * target node mismatches the local cluster name and
-     * {@code checkClusterName} is {@code true}.
-     *
-     * @param node             the node to connect to
-     * @param handshakeTimeout handshake timeout
-     * @return the connected node
-     * @throws ConnectTransportException if the connection failed
-     * @throws IllegalStateException if the handshake failed
-     */
-    public DiscoveryNode connectToNodeAndHandshake(
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/transport/TransportService.java]: ++

**Review by s1monw — CHANGES_REQUESTED** [review]
looks great, much simpler! I left a bunch of comments.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 2 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: this is how it was and we do throw an exception, thus processing the interrupt?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 5 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: yeah, I wanted to have the simplest construct as it was a rare collision. With the latest code I actually think it's impossible (I dedup on addresses and the connection are private to the pinging round). Will remove.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 6 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: +++ (although it's not optional on the wire)

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 7 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: the compiler can't figure out the implied types with the identity. I changed it to be more verbose so it won't look like a typo

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 8 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: sure

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 9 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: I adapted the log message

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 11 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: sure thing, will add.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 10 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: sure

File: core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java (hunk 12 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/transport/ConnectionProfile.java]: I tried to implement your suggestion and I think it looks good. will push shortly.

**Comment by bleskes** [comment]
@s1monw I pushed more commits addressing your feedback. Let me know what you think.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 5 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: turns out we do need this protection or something similar. I took another approach, which I think you'd like better.

File: core/src/test/java/org/elasticsearch/discovery/zen/UnicastZenPingTests.java [hunk 14]
```diff
@@ -82,13 +90,13 @@
...
 import static org.hamcrest.Matchers.empty;
 import static org.hamcrest.Matchers.equalTo;
-import static org.hamcrest.Matchers.greaterThan;
 import static org.hamcrest.Matchers.hasSize;
 import static org.mockito.Matchers.eq;
 import static org.mockito.Mockito.mock;
 import static org.mockito.Mockito.verify;
 import static org.mockito.Mockito.verifyNoMoreInteractions;
 
+@TestLogging("org.elasticsearch.transport:TRACE,org.elasticsearch.discovery.zen:TRACE")
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/discovery/zen/UnicastZenPingTests.java]: This logging was initially added to just `testSimplePings` to chase a race. The race has not reproduced since adding this logging. I think that we should drop the logging and and then address if the race comes back since you've changed how these things are handled.

Comment (bleskes) [inline core/src/test/java/org/elasticsearch/discovery/zen/UnicastZenPingTests.java]: removed.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 15]
```diff
@@ -373,34 +376,43 @@ public boolean isClosed() {
...
             return seedNodes;
         }
 
-        public synchronized Connection getConnection(TransportAddress address) {
-            checkIfClosed();
-            return tempConnections.get(address);
+        public Connection getOrConnect(DiscoveryNode node) throws IOException {
+            Connection result;
+            try (Releasable ignore = connectionLock.acquire(node.getAddress())) {
+                result = tempConnections.get(node.getAddress());
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: maybe use `computeIfAbsent()`?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 16]
```diff
@@ -447,7 +460,7 @@ protected void sendPings(final TimeValue timeout, final PingingRound pingingRoun
         // dedup by address
         final Map<TransportAddress, DiscoveryNode> uniqueNodesByAddress =
             Stream.concat(pingingRound.getSeedNodes().stream(), nodesFromResponses.stream())
-                .collect(Collectors.toMap(DiscoveryNode::getAddress, n -> n, (n1, n2) -> n1));
+                .collect(Collectors.toMap(DiscoveryNode::getAddress, node -> node, (n1, n2) -> n1));
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: you didn't like `Function.identity()` ?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 17]
```diff
@@ -553,10 +553,12 @@ public String executor() {
...
                 logger.trace("[{}] received response from {}: {}", pingingRound.id(), node, Arrays.toString(response.pingResponses));
-                if (pingingRound.isClosed() == false) {
-                    Arrays.asList(response.pingResponses).forEach(pingingRound::addPingResponseToCollection);
+                if (pingingRound.isClosed()) {
+                    if (logger.isTraceEnabled()) {
+                        logger.trace("[{}] skipping received response from {}. already closed", pingingRound.id(), node);
+                    }
                 } else {
-                    logger.trace("[{}] skipping received response from {}. already closed", pingingRound.id(), node);
+                    Arrays.asList(response.pingResponses).forEach(pingingRound::addPingResponseToCollection);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: `Arrays.asStream(response.pingResponses)` would not materialize it

**Review by s1monw — APPROVED** [review]
left some minors LGTM otherwise

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 16 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: I did but I used it wrong (as a function reference). Using it right works of course .. zzzz

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 15 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: the problem is the IOException that can be thrown while making a connection.

**Comment by bleskes** [comment]
thx @s1monw. I'll wait a day before backporting

**Comment by bleskes** [comment]
this is now backported to 5.x as well.
