### PR TITLE
Fix memory tracking of ES|QL sample agg

### LINKED ISSUE #128024: [CI] SampleDoubleAggregatorFunctionTests testSimpleWithCranky failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8166 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/7a4lpr7g4kk7m)
- [elasticsearch-intake #22865 / part3](https://gradle-enterprise.elastic.co/s/ag2lqf4uxgr7m)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.aggregation.SampleDoubleAggregatorFunctionTests.testSimpleWithCranky" -Dtests.seed=9F9E98E0B4889D1F -Dtests.locale=sv-FI -Dtests.timezone=CET -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.aggregation.SampleDoubleAggregatorFunctionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSimpleWithCranky),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected no used bytes for driver, found: 1552
```

**Issue Reasons:**
- [main] 2 failures in test testSimpleWithCranky (0.6% fail rate in 339 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes https://github.com/elastic/elasticsearch/issues/128024

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/X-SampleAggregator.java.st [hunk 1]
```diff
@@ -97,7 +97,10 @@ class Sample$Type$Aggregator {
             return block;
         }
         BytesRefBlock bytesRefBlock = (BytesRefBlock) block;
-        try ($Type$Block.Builder $type$Block = driverContext.blockFactory().new$Type$BlockBuilder(bytesRefBlock.getPositionCount())) {
+        try (
+            block;
```
Comment (ivancea) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/X-SampleAggregator.java.st:101]: Nit: What about moving the cast inside the try? So we avoid this extra `block;`. Not much of an improvement, but I think it makes the intent a bit clearer ("Now we'll consume this block, which is a BytesRefBlock"), and we use both variables from here on

**Review by ivancea — APPROVED** [review]
Good catch! LGTM!

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/X-SampleAggregator.java.st (hunk 1 above)
Comment (jan-elastic) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/X-SampleAggregator.java.st:101]: SGTM

Maybe it's slightly obscure that handles closing the original block.

Anyway, it also conveniently solves my spotless/autogen issue (see the autocommit). Depending the the strlen of the type (`Int` or `BytesRef`), this block should go on 1 or 2 lines right now.
