### PR TITLE
Fix IpScriptFieldType CI - #106900

### LINKED ISSUE #106900: [CI] IpScriptFieldTypeTests testTermsQuery failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/7s3fa3w2vwm6y/tests/:server:test/org.elasticsearch.index.mapper.IpScriptFieldTypeTests/testTermsQuery

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.mapper.IpScriptFieldTypeTests.testTermsQuery" -Dtests.seed=64D75D3A249568E5 -Dtests.locale=el-GR -Dtests.timezone=America/Curacao -Druntime.java=22
```

**Applicable branches:**
main, 8.13

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.index.mapper.IpScriptFieldTypeTests#testTermsQuery`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTermsQuery'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.index.mapper.IpScriptFieldTypeTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <2>
     but: was <1>

  at __randomizedtesting.SeedInfo.seed([64D75D3A249568E5:A5DDC8688199D68A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2147)
  at org.elasticsearch.index.mapper.IpScriptFieldTypeTests.testTermsQuery(IpScriptFieldTypeTests.java:239)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

### PR DESCRIPTION
**Pull request by carlosdelest**
I've been tracing the problems with these tests (as the [first attempt I made](https://github.com/elastic/elasticsearch/pull/107066) was unrelated to the actual bug).

I discovered that the actual problem was that the `BytesRefHash` for `terms` in the `IpScriptFieldTermsQuery` was not finding terms that were actually there.

The seed that was used to reproduce this failure was triggering multiple slices for performing the search. As `BytesRefHash` is not a threadsafe class, that made me think about some kind of synchronization issue with the underlying `BytesRefHash` structure for the `IpScriptFieldTermsQuery`

Adding a `synchronized` block to the `terms` on access removed the problem. I've tried to reproduce the issue with > 90k iterations of the tests and have been unable to reproduce it.

Closes #106900

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java [hunk 1]
```diff
@@ -26,9 +26,11 @@ public IpScriptFieldTermsQuery(Script script, IpFieldScript.LeafFactory leafFact
 
     @Override
     protected boolean matches(BytesRef[] values, int count) {
-        for (int i = 0; i < count; i++) {
-            if (terms.find(values[i]) >= 0) {
-                return true;
+        synchronized (terms) {
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: OK, I recognize this issue now. It seems like something similar here: https://github.com/elastic/elasticsearch/pull/106678/files

I think this is because we are searching multiple segments in parallel. But why are we seeing weird failures here but not in `IpScriptFieldTermQuery`? 

@javanna you might be interested here.

Comment (carlosdelest) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: > I think this is because we are searching multiple segments in parallel

It definitely looks like it. Would this PR be the proper way of fixing this issue, or should we look into something different?

> But why are we seeing weird failures here but not in IpScriptFieldTermQuery?

`IpScriptFieldTermQuery` does use a `BytesRef` instead of a `BytesRefHash`, checking the value directly instead of using the hash. So this is thread safe as opposed to using the `BytesRefHash` from multiple threads.

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: I don't think the issue is the `BytesRefHash` looking at how its used, we construct one new `BytesRefHash`, statically setting all the terms that will match and then pass it in. We don't reuse buffers or anything. 

Do you see something where we are adjusting that bytes ref hash? Or is the internal hash mutated due to find checks?

Comment (carlosdelest) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: Yes, this puzzled me for a while as well. I think the problem is located [here](https://github.com/elastic/elasticsearch/blob/aee3a253dd8f5c40be9d3b1686b8c7889556a2f3/server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java#L139) - `spare` is a class attribute that is being (re)used for performing the `find` operation.

This aligns with the `find` operation being nondeterministic in my tests, and thus being unable to find values that were in the hash.

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: Oh wow, `spare` is indeed a huge issue. What on Earth!!!

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: I wonder if we should just use Lucenes BytesRefHash here instead of using ours which from what I can tell is only useful if we are actually using BigArrays for reuse, and here, we are not.

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: I think the lock here is indeed frustrating. Another option is extending `BytesRefHash` that allows to return a "readonly" threadsafe version where `find` is only satisfied so that we can use a `BytesRefHash.getFinder` and each `finder` has its own `spare` and it relies on the original bytes ref hash.

Comment (carlosdelest) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: I like the idea of making a threadsafe version of `BytesRefHash`. I guess the main goal of `spare` is avoiding repeated allocations for it.

> Another option is extending BytesRefHash that allows to return a "readonly" threadsafe version where find is only satisfied so that we can use a BytesRefHash.getFinder and each finder has its own spare and it relies on the original bytes ref hash.

How would we create a separate finder for each thread that is accessing the query `matches` method?

What do you think about using a `ThreadLocal `variable for holding `spare` instances in a threadsafe version of `BytesRefHash`?

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:29]: @carlosdelest I would override the `createTwoPhaseIterator` method. For `BytesRefHash` I would create a method that returns a inner class `BytesRefHash.Finder` or something that uses its own `spare` when searching the parent `BytesRefHash` class and then use that `Finder` inside the `createTwoPhaseIterator` that calls `matches`.

**Comment by carlosdelest** [comment]
I've pushed an updated version that uses a custom method for `BytesRefHash`, and overrides some methods. I don't like the result, as I have to deal with re-overriding some methods from parent classes in an ugly way, but so far this is what I can think of. Happy to hear some suggestions for this to be smoother.

File: server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java [hunk 2]
```diff
@@ -147,6 +151,15 @@ public long find(BytesRef key) {
...
     }
 
+    /**
+     * Allows finding a key in the hash in a thread safe manner, by providing an intermediate
+     * BytesRef reference to storing intermediate results. As long as each thread provides
+     * its own intermediate instance, this method is thread safe.
+     */
+    public long threadSafeFind(BytesRef key, BytesRef intermediate) {
+        return find(key, key.hashCode(), intermediate);
+    }
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java:161]: I was thinking something like this:
```
    private long threadSafeFind(BytesRef key, BytesRef intermediate) {
        return find(key, key.hashCode(), intermediate);
    }
    
    public Finder newFinder() {
        return new Finder();
    }

    public class Finder {
        private final BytesRef intermediate = new BytesRef();

        public long find(BytesRef key) {
            return threadSafeFind(key, intermediate);
        }
    }
```

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java [hunk 3]
```diff
@@ -16,24 +18,51 @@
...
+            if (terms.threadSafeFind(values[i], intermediate) >= 0) {
                 return true;
             }
         }
         return false;
     }
 
+    @Override
+    protected boolean matches(IpFieldScript scriptContext, int docId) {
+        throw new UnsupportedOperationException("Need to use matches(IpFieldScript, int, BytesRef) instead");
```
Comment (carlosdelest) [inline server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:42]: I find this super ugly to do - we're extending a class, but oh wait, this method is not the right one to use 😢 . And we're no longer extending from  `AbstractIpScriptFieldQuery` like our pals, but `AbstractIpScriptFieldQuery` because otherwise we can't redefine `matches`...

I'm trying to find a better way for this, but so far I'm out of better ideas 🤷

File: server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java (hunk 2 above)
Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java:161]: I don't think that is so bad. I think we should still inherit from `AbstractIpScriptFieldQuery`

Then:
```
 @Override
    protected final boolean matches(BytesRef[] values, int count) {
        throw new UnsupportedOperationException("should not be called, use createTwoPhaseIterator instead");
    }
```

``` @Override
    protected final TwoPhaseIterator createTwoPhaseIterator(IpFieldScript scriptContext, DocIdSetIterator approximation) {
```

For the twophase iterator

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java (hunk 3 above)
Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:42]: I think this is OK, its not so bad. The bad part is that BytesRefHash uses a friggin' piece of state for `find`, I mean, what on earth.

File: server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java (hunk 2 above)
Comment (carlosdelest) [reply server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java]: I see - I'm trying that. I'll add some tests for the new Find class to ensure it is thread safe.

File: server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java [hunk 4]
```diff
@@ -129,14 +129,18 @@ public BytesRef get(long id, BytesRef dest) {
         return bytesRefs.get(id, dest);
     }
 
+    public long find(BytesRef key, int code) {
+        return find(key, code, spare);
+    }
+
     /**
      * Get the id associated with <code>key</code>
      */
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java:138]: This comment should be on the above public method

File: server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java [hunk 5]
```diff
@@ -236,4 +249,19 @@ public long ramBytesUsed() {
         return BASE_RAM_BYTES_USED + bytesRefs.ramBytesUsed() + ids.ramBytesUsed() + hashes.ramBytesUsed() + spare.bytes.length;
     }
 
+    public Finder newFinder() {
+        return new Finder();
+    }
+
+    /**
+     * Returns a finder class that can be used to find keys in the hash in a thread-safe manner
+     */
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java:258]: seems like the comment should be on the method?

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java [hunk 6]
```diff
@@ -16,6 +18,8 @@
 
 import java.util.Objects;
 
+import static org.elasticsearch.search.runtime.AbstractIpScriptFieldQuery.decode;
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:21]: Don't think this is needed?

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java [hunk 7]
```diff
@@ -24,16 +28,42 @@ public IpScriptFieldTermsQuery(Script script, IpFieldScript.LeafFactory leafFact
...
+
+    boolean matches(IpFieldScript scriptContext, int docId, BytesRefHash.Finder finder) {
+        scriptContext.runForDoc(docId);
+        return matches(scriptContext.values(), scriptContext.count(), finder);
+    }
+
+    protected final TwoPhaseIterator createTwoPhaseIterator(IpFieldScript scriptContext, DocIdSetIterator approximation) {
+        return new TwoPhaseIterator(approximation) {
+            private final BytesRef bytesRef = new BytesRef();
+
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:53]: This is unused now

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java [hunk 8]
```diff
@@ -24,16 +28,42 @@ public IpScriptFieldTermsQuery(Script script, IpFieldScript.LeafFactory leafFact
...
+            @Override
+            public boolean matches() {
+                // We need to use a thread safe finder, as this can be called from multiple threads
+                return IpScriptFieldTermsQuery.this.matches(scriptContext, approximation.docID(), terms.newFinder());
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:57]: I think we should a single `Finder` per `TwoPhaseIterator`. So instead of passing in `newFinder()` here, we can have a `private final BytesRefHash.Finder finder = terms.newFinder();`

And pass that in to the matches method.

**Review by benwtrent — COMMENTED** [review]
Looking good, some minor things

File: server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java [hunk 9]
```diff
@@ -24,16 +28,42 @@ public IpScriptFieldTermsQuery(Script script, IpFieldScript.LeafFactory leafFact
...
-            if (terms.find(values[i]) >= 0) {
+            if (finder.find(values[i]) >= 0) {
                 return true;
             }
         }
         return false;
     }
 
+    @Override
+    protected boolean matches(BytesRef[] values, int count) {
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/runtime/IpScriptFieldTermsQuery.java:41]: this should be `final`

File: server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java (hunk 5 above)
Comment (carlosdelest) [reply server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java]: Yep! 💯

**Review by benwtrent — APPROVED** [review]
