### PR TITLE
ESQL: Support date and time intervals as input params

### LINKED ISSUE #99570: ESQL: Improve parsing of query parameters
### Description

The parsing of params in parameterized ES|QL queries appears to be inconsistent with the parsing of non-parameterized ES|QL queries. Some examples on current main:

- ```
  {"query": "row a = 1 | eval x = now() + ?", "params": [{"type":"time_duration", "value":"5 hour"}]}
  ```
  results in the following exception:
  ```
  "type":"parsing_exception","reason":"line 1:23: Cannot cast value [5 hour] of type [KEYWORD] to parameter type [TIME_DURATION]"}],"type":"parsing_exception","reason":"line 1:23: Cannot cast value [5 hour] of type [KEYWORD] to parameter type [TIME_DURATION]"
  ```
- ```
  {"query": "row a = 1 | eval x = now() + ?", "params": ["1 week"]}
  ```
  results in
  ```
  "type":"verification_exception","reason":"Found 1 problem\nline 1:22: [+] has arguments with incompatible types [DATETIME] and [KEYWORD]"
  ```
- ```
  "query": "row a = 1 | eval x = now() + ? week", "params": [1]
  ```
  results in
  ```
  "type":"parsing_exception","reason":"line 1:32: extraneous input 'week' expecting <EOF>"}],"type":"parsing_exception","reason":"line 1:32: extraneous input 'week' expecting <EOF>"
  ```

All the queries work fine if the `?` is manually substituted with the given parameter.

The first two indicate that the parsing of query parameters is not consistent with our normal parsing, type resolution and verification pipeline.

According to @astefan , `version` is affected in a similar way.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/99570

Add support for DATE_PERIOD and TYPE_DURATION values as input parameters, eg.

```
{
   "query": "row a = 1 | eval x = now() + ?", 
   "params": [{"type":"time_duration", "value":"5 hours"}]
}
```

The values have to be passed as strings and then will be converted to the appropriate type.

The original issue also pointed to similar problems for Version type, so the PR also includes a test for this case.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypeConverter.java [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+        return null;
+    }
+
+    public static TemporalAmount parseTemporalAmount(Object val, DataType expectedType) {
+        String str = String.valueOf(val);
+        if (str == null) {
+            return null;
+        }
+        str = str.trim().replaceAll("\\s+", " ");
+        String[] split = str.split(" ");
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypeConverter.java:64]: Replace the regext with a more hand-on/low-level approach just to be safe as some generated queries might be large yet due to typos might get picked here.
The advantage is that if the more than 2 entries are found, the code can bail out instead of parsing the whole string.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypeConverter.java [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+        if (split.length == 2) {
+            TemporalAmount result = ExpressionBuilder.parseTemporalAmout(Integer.parseInt(split[0]), split[1], Source.EMPTY);
+            if (EsqlDataTypes.DATE_PERIOD == expectedType && result instanceof Period
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypeConverter.java:67]: Add a validation error here along side a test case for when the date_period type is specified but a time duration is used instead - something along the lines of did you mean ? or "Param has declared type X but found type Y,"

**Review by costin — APPROVED** [review]
Left a few comments around parsing - LGTM

**Comment by luigidellaquila** [comment]
@elasticmachine update branch
