### PR TITLE
Abort snapshots on a node that leaves the cluster

### LINKED ISSUE #20876: [bug report]LockObtainFailedException throws under presure
**Elasticsearch version**:
2.1
**Plugins installed**: []
delete-by-query
elasticsearch-analysis-ik
repository-hdfs
**JVM version**:
8u60
**OS version**:
CentOS release 6.6 (Final)
**Description of the problem including expected versus actual behavior**:
one of the data node keep throw below exception:
[2016-10-12 11:34:04,769][WARN ][cluster.action.shard     ] [XXXX] [indexName][2] received shard failed for [indexName][2], node[rckOYj-DT42QNoH9CCEBJQ], relocating [v2zayugFQnuMiGu-hS1vXg], [R], v[7091], s[INI
TIALIZING], a[id=bkpcEq2qTXaPEKHl9tOunQ, rId=xeJJijQCRyaJPcSgQa7eGg], expected_shard_size[22462872851], indexUUID [sOKz0tW9Sw-u137Swoevsw], message [failed to create shard], failure [ElasticsearchException[failed to create shard]; nested: LockObtainF
ailedException[Can't lock shard [indexName][2], timed out after 5000ms]; ]
[indexName][[indexName][2]] ElasticsearchException[failed to create shard]; nested: LockObtainFailedException[Can't lock shard [indexName][2], timed out after 5000ms];
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:389)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:650)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:550)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:179)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.store.LockObtainFailedException: Can't lock shard [indexName][2], timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:565)
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:493)
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:307)
        ... 9 more
**Steps to reproduce**:(not very presious, I haven't reproduced it yet)
 1. give cluster a lot presure and one node out of cluster
 2. then remove presure and after a while, the node come back and try to recover some shard, it keeps throw below exception

### PR DESCRIPTION
**Pull request by abeyad**
Previously, if a node left the cluster (for example, due to a long GC),
during a snapshot, the master node would mark the snapshot as failed, but
the node itself could continue snapshotting the data on its shards to the
repository.  If the node rejoins the cluster, the master may assign it to
hold the replica shard (where it held the primary before getting kicked off
the cluster).  The initialization of the replica shard would repeatedly fail
with a ShardLockObtainFailedException until the snapshot thread finally
finishes and relinquishes the lock on the Store.

This commit resolves the situation by ensuring that when a shard is removed
from a node (such as when a node rejoins the cluster and realizes it no longer
holds the active shard copy), any snapshotting of the removed shards is aborted.
In the scenario above, when the node rejoins the cluster, it will see in the cluster 
state that the node no longer holds the primary shard, so `IndicesClusterStateService`
will remove the shard, thereby causing any snapshots of that shard to be aborted.

Closes #20876

### CODE REVIEW

**Review by ywelsch — COMMENTED** [review]
I wonder if the better change would be to treat aborting snapshots in the same way as we abort outgoing peer recoveries of a primary: by registering an `IndexEventListener` listening for `beforeIndexShardClosed` and cancelling recoveries / abort ongoing snapshots at that time. This ensures that snapshots are aborted whenever we close the shard, simplifying the logic here. WDYT?

File: core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java [hunk 1]
```diff
@@ -402,6 +402,10 @@ public String toString() {
         for (DiscoveryNode node : this) {
             sb.append(node).append(',');
         }
+        if (sb.length() > 1) {
```
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java]: done

**Comment by abeyad** [comment]
@ywelsch the PR has been updated to use the `beforeIndexShardClosed` callback, the test has been made much more lightweight (doesn't use network disruptions to simulate the shard removal situation), and the PR description has been updated to reflect the new approach.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 2]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
...
+            }
+        }, 10, TimeUnit.SECONDS);
+
+        // Pick a node with a primary shard and remove the shard from the node
+        ClusterState clusterState = internalCluster().clusterService(internalCluster().getMasterName()).state();
+        IndexRoutingTable indexRoutingTable = clusterState.getRoutingTable().index(index);
+        String nodeWithPrimary = clusterState.nodes().get(indexRoutingTable.shard(0).primaryShard().currentNodeId()).getName();
+        assertNotNull("should be at least one node with a primary shard", nodeWithPrimary);
+        IndicesService indicesService = internalCluster().getInstance(IndicesService.class, nodeWithPrimary);
+        indicesService.deleteIndex(resolveIndex(index), "trigger shard removal");
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: removeIndex might be good enough here.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 3]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
...
+
+        // make sure snapshot is aborted
+        assertBusy(() -> {
+            SnapshotsInProgress snapshotsInProgress =
+                client.admin().cluster().prepareState().get().getState().custom(SnapshotsInProgress.TYPE);
+            if (snapshotsInProgress != null && snapshotsInProgress.entries().size() > 0) {
+                assertEquals(State.SUCCESS, snapshotsInProgress.entries().get(0).state());
+            }
+        }, 10, TimeUnit.SECONDS);
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: assertBusy uses by default 10 seconds, no need to specify it here again

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 4]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
...
+        final int numDocs = 100;
+        final String repo = "test-repo";
+        final String index = "test-idx";
+        final String snapshot = "test-snap";
+
+        assertAcked(prepareCreate(index, 1,
+            Settings.builder().put("number_of_shards", numPrimaries).put("number_of_replicas", numReplicas)));
+
+        logger.info("--> indexing some data");
+        Client client = client();
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: why not use a random client every time?

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 5]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
...
+        assertNotNull("should be at least one node with a primary shard", nodeWithPrimary);
+        IndicesService indicesService = internalCluster().getInstance(IndicesService.class, nodeWithPrimary);
+        indicesService.deleteIndex(resolveIndex(index), "trigger shard removal");
+
+        // make sure snapshot is aborted
+        assertBusy(() -> {
+            SnapshotsInProgress snapshotsInProgress =
+                client.admin().cluster().prepareState().get().getState().custom(SnapshotsInProgress.TYPE);
+            if (snapshotsInProgress != null && snapshotsInProgress.entries().size() > 0) {
+                assertEquals(State.SUCCESS, snapshotsInProgress.entries().get(0).state());
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: I think this will succeed even without the change in this PR? I'm not sure what is exactly tested here.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 6]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
         waitForCompletion(repositoryName, inProgressSnapshot, TimeValue.timeValueSeconds(60));
     }
 
+    /**
+     * This test ensures that if a node that holds a primary that is being snapshotted leaves the cluster,
+     * when it returns, the node aborts the snapshotting on the now removed shard.
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: the description does not match what the test does.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 7]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
...
+
+        logger.info("--> snapshot");
+        client.admin().cluster().prepareCreateSnapshot(repo, snapshot)
+            .setWaitForCompletion(false)
+            .execute();
+
+        logger.info("--> waiting for snapshot to be in progress on all nodes");
+        assertBusy(() -> {
+            for (String node : internalCluster().nodesInclude(index)) {
+                final Client nodeClient = client(node);
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: why use this particular client?

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 8]
```diff
@@ -2490,4 +2493,80 @@ public void testGetSnapshotsRequest() throws Exception {
...
+                assertEquals(snapshot, snapshotsInProgress.entries().get(0).snapshot().getSnapshotId().getName());
+                ImmutableOpenMap<ShardId, SnapshotsInProgress.ShardSnapshotStatus> shards = snapshotsInProgress.entries().get(0).shards();
+                assertEquals(numPrimaries, shards.size());
+                for (ObjectObjectCursor<ShardId, ShardSnapshotStatus> cursor : shards) {
+                    assertEquals(SnapshotsInProgress.State.INIT, cursor.value.state());
+                }
+            }
+        }, 10, TimeUnit.SECONDS);
+
+        // Pick a node with a primary shard and remove the shard from the node
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Pick node with THE primary shard

**Review by ywelsch — CHANGES_REQUESTED** [review]
The change is good but the test needs a bit more work (I'm not sure it's testing the right thing).

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 6 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: fixed

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 4 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: done

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 7 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: I made a mistake here, this only ensures the snapshot cluster state update has reached master, so I changed it to use `internalCluster().clusterService(node).state()` instead, to ensure each node knows that the snapshot is in progress.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 5 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Without the change here, the snapshot forever stalls and the test times out, because the snapshot was never aborted.  This asserts that we abort the snapshot, bringing the snapshotting to a successful conclusion.

**Comment by abeyad** [comment]
@ywelsch I pushed https://github.com/elastic/elasticsearch/pull/21084/commits/651bdbfbaacae6d6d391eb1823dc0c2eb1945767 that I think improves the test a lot.  Instead of the throttling, it uses the mock repository with blocks, then unblocks after removing the shard, triggering the snapshot abort.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 9]
```diff
@@ -2514,59 +2512,54 @@ public void testSnapshotCanceledOnRemovedShard() throws Exception {
...
 
-        // make sure snapshot is aborted
+        logger.info("--> unblocking blocked node [{}]", blockedNode);
+        unblockNode(repo, blockedNode);
+
+        logger.info("--> waiting for snapshot to complete");
+        waitForCompletion(repo, snapshot, TimeValue.timeValueSeconds(10));
+
+        // make sure snapshot is aborted and the aborted shard was marked as failed
         assertBusy(() -> {
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: no assertBusy needed with `waitForCompletion` above?

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 10]
```diff
@@ -2514,59 +2512,54 @@ public void testSnapshotCanceledOnRemovedShard() throws Exception {
...
-            SnapshotsInProgress snapshotsInProgress =
-                client.admin().cluster().prepareState().get().getState().custom(SnapshotsInProgress.TYPE);
-            if (snapshotsInProgress != null && snapshotsInProgress.entries().size() > 0) {
-                assertEquals(State.SUCCESS, snapshotsInProgress.entries().get(0).state());
-            }
-        }, 10, TimeUnit.SECONDS);
+            List<SnapshotInfo> snapshotInfos = client().admin().cluster().prepareGetSnapshots(repo).setSnapshots(snapshot).get().getSnapshots();
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: waitForCompletion returns SnapshotInfo

**Review by ywelsch — APPROVED** [review]
LGTM. I left two small suggestions. Thanks @abeyad

**Comment by abeyad** [comment]
I pushed abd71f5897315e6a7ba53bbfe45964ecfbfcd22f that uses `SnapshotInfo` returned from `waitForCompletion`.  Thanks for the review @ywelsch !

**Comment by abeyad** [comment]
5.x commit: 1d278d26f68e9cb9545290dbe00f8ff9cba6e768

**Comment by ywelsch** [comment]
5.0 commit: 22ee78c
