### PR TITLE
ESQL: Fix repeated rows in LOOKUP JOIN with a lookup index in the FROM

### LINKED ISSUE #118852: ESQL lookup join with lookup index results in duplicate set of rows.
Performing a lookup join between 2 distinct lookup indices results in duplicated set of rows in result set:
```
~ ᐅ curl -XPOST "${ES_URL}/_query?format=txt" -H 'Content-Type: application/json' -d'{"query": "FROM languages"}'
     code      | code.keyword  |   language    |language.keyword
---------------+---------------+---------------+----------------
en             |en             |English        |English         
es             |es             |Spanish        |Spanish         
fr             |fr             |French         |French          
~ ᐅ curl -XPOST "${ES_URL}/_query?format=txt" -H 'Content-Type: application/json' -d'{"query": "FROM countries"}'
     code      | code.keyword  |   countries   |countries.keyword
---------------+---------------+---------------+-----------------
en             |en             |England        |England          
es             |es             |Spain          |Spain            
fr             |fr             |France         |France           
~ ᐅ curl -XPOST "${ES_URL}/_query?format=txt" -H 'Content-Type: application/json' -d'{"query": "FROM countries | LOOKUP JOIN languages ON code"}'
     code      |   countries   |countries.keyword| code.keyword  |   language    |language.keyword
---------------+---------------+-----------------+---------------+---------------+----------------
en             |null           |null             |en             |English        |English         
es             |null           |null             |es             |Spanish        |Spanish         
fr             |null           |null             |fr             |French         |French          
en             |England        |England          |en             |English        |English         
es             |Spain          |Spain            |es             |Spanish        |Spanish         
fr             |France         |France           |fr             |French         |French    
```

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/118852

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java [hunk 1]
```diff
@@ -139,16 +121,41 @@ public static String[] planOriginalIndices(PhysicalPlan plan) {
...
-    private static void addOriginalIndexIfNotLookup(Set<String> indices, EsIndex index) {
-        if (index.indexNameWithModes().get(index.name()) != IndexMode.LOOKUP) {
-            indices.addAll(asList(Strings.commaDelimitedListToStringArray(index.name())));
+    /**
+     * Iterates over the plan and applies the action to each {@link EsRelation} node.
+     * <p>
+     *     This method ignores the right side of joins.
+     * </p>
+     */
+    private static void forEachFromRelation(PhysicalPlan plan, Consumer<EsRelation> action) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:134]: Extracted the `planConcreteIndices()` code here, and fixed it by adding the `node instanceof Join` check.
Looks like the Join was outside the fragment in the tests I used for the original PR, but it was inside for this case.

**Review by craigtaverner — APPROVED** [review]
LGTM
