### PR TITLE
Skip eager reconciliation for empty routing table

### LINKED ISSUE #115885: [CI] MinimumMasterNodesIT testThreeNodesNoMasterBlock failing
**Build Scans:**
- [elasticsearch-periodic #4635 / graalvm-ce17_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/hjqr3mebq5ko4)
- [elasticsearch-periodic #4554 / openjdk17_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/ljkf2wpeyfumu)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.MinimumMasterNodesIT.testThreeNodesNoMasterBlock" -Dtests.seed=EF57077E0B9558F1 -Dtests.locale=fr-NC -Dtests.timezone=America/St_Vincent -Druntime.java=17
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.MinimumMasterNodesIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testThreeNodesNoMasterBlock),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.x] 2 failures in test testThreeNodesNoMasterBlock (0.3% fail rate in 598 executions)
- [8.x] 2 failures in pipeline elasticsearch-periodic (11.8% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
No need to start the eager reconciliation when the routing table is empty. An empty routing table means either the cluster has no shards or the state has not recovered. The eager reconciliation is not necessary in both cases.

Resolves: #115885

### CODE REVIEW

**Review by nicktindall — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java [hunk 1]
```diff
@@ -206,6 +206,12 @@ public void allocate(RoutingAllocation allocation, ActionListener<Void> listener
         assert MasterService.assertMasterUpdateOrTestThread() : Thread.currentThread().getName();
         assert allocation.ignoreDisable() == false;
 
+        if (allocation.routingTable().indicesRouting().isEmpty()) {
+            logger.debug("No allocation needed for empty routing table");
+            listener.onResponse(null);
+            return;
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java:212]: I am wondering about a case when we create and then delete index.
Would it (1) remove it from the desired balance and (2) reconcile the cluster cluster state to unallocate it?

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java:212]: Sorry for my ignorance in this area. Do we need (2)? Deleting an index [removes](https://github.com/elastic/elasticsearch/blob/c1c59eb41d6864c3c4d95b01629ad6b72525e9a4/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java#L192) it from the routingTable. So we would have computed an empty desiredBalance which is then [short-circuited](https://github.com/elastic/elasticsearch/blob/c1c59eb41d6864c3c4d95b01629ad6b72525e9a4/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconciler.java#L135-L138) in Reconciler. It does _not_ seem to do anything actually useful. If we want the empty desiredBalance, we can also directly set it here? 

The need for fixing the test failure is to handle state-not-recovered and empty routingTable is a proxy to it since we don't have access to cluster state at this point. Therefore I chose to check for empty routingTable as it seems safe to me. But please let me know if there are consequences that I am not aware of.

Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java:212]: Yeah, you are correct about removing an index (it will also be picked by https://github.com/elastic/elasticsearch/blob/a59c182f9f7e9d1bf3d6eecbc0e44f24ff91d053/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java#L300).

I think it is worth setting empty desired balance here for completeness (for example to make sure we do not report deleted indices in desired balance related apis).

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java]: On a second thought, I changed it to skip only the [eager reconcile](https://github.com/elastic/elasticsearch/blob/4e17c61d39c64f2522d8ed6245c9c43d41a0dad0/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java#L219) call which is the cause for the CI failure. This change brought the impact down to minimal since it relies on the existing code flow to update DesiredBalance and the subsequent reconcile (should be short-circuited as we discussed). This works better because we avoid mutating `DesiredBalance` in places other than the single-threaded computation and during master failover, i.e. less racy.

Please see 44d22ddb0892f4fbaadbc9056fc1c8f8a06f2ec0

**Comment by ywangd** [comment]
@elasticmachine update branch

**Review by nicktindall — APPROVED** [review]
LGTM, and much simpler.

Do we care about the fact we can over-write `currentDesiredBalance` still? perhaps it's worth leaving an indication that that can occur incase someone comes across it later?

That was a few days of learnings for us.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java (hunk 1 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java]: @idegtiarenko I am going to merge this PR since I'd like to close the CI failure issue before the iteration closes. Happy to take any post-merge comment. Thanks!

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java]: Sorry, forgot to mention that I asked @nicktindall to review the latest change and he has approved it.
