### PR TITLE
[CCR] Data streams: order follower backing indices by original name

### LINKED ISSUE #90820: CCR can incorrectly reorder data stream backing indices
Data streams maintain a list of backing indices. The last index in the list is considered the "write" index which is afforded a number of protections to keep it from being deleted or incorrectly changed underneath the stream.

Each time CCR creates a new follower index that belongs to a replicated data stream, [the follow API performs a sort operation](https://github.com/elastic/elasticsearch/blob/248918f142b870b18fd5168a3210947e6550d3df/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java#L339) on the replicated data stream's backing index list. This is to keep older backing indices that are being followed from incorrectly replacing the latest backing index, which should logically be the write index.

The problem with this consistency model is that it assumes the backing indices are always sortable such that the youngest index is last lexicographically. In the case that the follower cluster has an ILM policy that replaces a replicated data stream's backing indices with mounted searchable snapshots, the resulting names will be prefixed with `restored-` or `partial-` which will always sort later than the regular data stream prefix of `.ds-`.

If an index mounted as a searchable snapshot is incorrectly "sorted" to the back of the backing index list, it can make the resulting index impossible to delete until another searchable snapshot of a younger backing index is created and a new follower is created to re-sort the list and free the older index from the incorrectly assumed write index position.

Example: Assuming the following data stream `data-test`. The follower cluster is setup with an auto follow pattern that follows indices named `.ds-data-test*`. An ILM policy that converts aging indices to searchable snapshots and then deletes them after a time is present on both clusters.

Initial state, a replicated data stream with three backing indices:
Leader:  `[.ds-data-test-01, .ds-data-test-02, .ds-data-test-03]`
Follower:  `[.ds-data-test-01, .ds-data-test-02, .ds-data-test-03]`

ILM converts oldest index (01) to a mounted searchable snapshot:
Leader:  `[restored-.ds-data-test-01, .ds-data-test-02, .ds-data-test-03]`
Follower:  `[restored-.ds-data-test-01, .ds-data-test-02, .ds-data-test-03]`

ILM rolls over the data stream on the leader. A new write index (04) is created on the leader and replicated to the follower, triggering the sort bug:
Leader:  `[restored-.ds-data-test-01, .ds-data-test-02, .ds-data-test-03, .ds-data-test-04]`
Follower:  `[.ds-data-test-02, .ds-data-test-03, .ds-data-test-04, restored-.ds-data-test-01]`

Eventually, when ILM goes to delete the oldest index (01), it cannot on the follower cluster because the oldest index was sorted to the last position in the array and is considered the data stream's write index:
Leader:  `[.ds-data-test-02, .ds-data-test-03, .ds-data-test-04]`
Follower:  `[.ds-data-test-02, .ds-data-test-03, .ds-data-test-04, restored-.ds-data-test-01]` // STUCK

ILM will continue looping trying to delete the index (01) until the next oldest index (02) becomes a searchable snapshot...
Leader:  `[restored-.ds-data-test-02, .ds-data-test-03, .ds-data-test-04]`
Follower:  `[restored-.ds-data-test-02, .ds-data-test-03, .ds-data-test-04, restored-.ds-data-test-01]` // Still Stuck

... and another rollover happens so that the next oldest (02) is sorted to the end:
Leader:  `[restored-.ds-data-test-02, .ds-data-test-03, .ds-data-test-04, .ds-data-test-05]`
Follower:  `[.ds-data-test-03, .ds-data-test-04, .ds-data-test-05, restored-.ds-data-test-02]` // Old index-01 finally deleted.

### PR DESCRIPTION
**Pull request by andreidan**
This adds a test to simulate the case when the follower data stream has an early generation shrunken backing index and the leader data stream is rolled over.
Currently the rolled over backing index (the new leader write index) will end up not being the leader index in the follower data stream, and even more, the shrunken index will be ordered as the write index in the follower data stream.

This attempts to mitigate this a bit by sorting the follower backing indices by the original names (ignoring any characters before the standardised `.ds-` prefix).

Note: I appreciate we might want to employ a longer-term fix where we potentially replicate the generation together with the index? 

Fixes #90820

### CODE REVIEW

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java [hunk 1]
```diff
@@ -358,8 +361,16 @@ static DataStream updateLocalDataStream(
...
-                // (string sorting works because of the naming backing index naming scheme)
-                backingIndices.sort(Index.COMPARE_BY_NAME);
+                // Not all backing indices follow the data stream backing indices naming convention (e.g. some might start with
+                // "restored-" if they're mounted indices, "shrink-" if they were shrunk, or miscellaneously named indices could be added
+                // to the data stream using the modify data stream API) so we check to see if the backing index prefix is present and
+                // when present we sort by the backing index name by trimming (for sorting purposes only) everything before the {@link
+                // BACKING_INDEX_PREFIX}. If the index name doesn't contain the {@link BACKING_INDEX_PREFIX} we use the full index name as
+                // is for sorting.
+                backingIndices.sort(Comparator.comparing(o -> {
+                    int backingPrefixPosition = o.getName().indexOf(BACKING_INDEX_PREFIX);
```
Comment (jbaiera) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java:371]: For the quick fix, I think it might be safer if we split the backing index names into two buckets: a bucket of index names that start with the `.ds-` prefix and a bucket for everything else. Then we can sort the contents of each bucket, placing the sorted `.ds-` prefixed indices at the end of the list of indices.

Maybe something like 
```java
Comparator.comparing((Index o) -> o.getName().startsWith(BACKING_INDEX_PREFIX) ? 1 : -1)
                    .thenComparing(Index.COMPARE_BY_NAME);
```

**Review by jbaiera — COMMENTED** [review]
Test looks great, thanks for adding it!

I think the sort logic is still operating on an unsafe assumption that an index can only be part of a data stream if its name contains the initial index name made by rolling over a data stream. If a random index were to be added to the data stream via the modify data stream API then this consistency issue could still happen.

Since a write index can only be made by the data stream being created by template or being rolled over, it's guaranteed to be prefixed with the backing index prefix, so we can assume those indices are the likeliest candidates for the write index. If there are none, we can (hopefully) gracefully fall back to the next likely candidates where are the non prefixed indices?

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java (hunk 1 above)
Comment (jbaiera) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java:371]: > ... it's guaranteed to be prefixed with the backing index prefix ...

Hmm, maybe still not entirely "guaranteed"... Perhaps we could continue with the check you have already but still partition them first?

```java
backingIndices.sort(Comparator.comparing((Index o) -> o.getName().contains(BACKING_INDEX_PREFIX) ? 1 : -1)
  .thenComparing((Index o) -> {
      int backingPrefixPosition = o.getName().indexOf(BACKING_INDEX_PREFIX);
      return backingPrefixPosition > -1 ? o.getName().substring(backingPrefixPosition) : o.getName();
  }));
```

Comment (andreidan) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java]: Great idea ++

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java [hunk 2]
```diff
@@ -46,16 +46,36 @@
...
+     * the local data stream.
+     * The backing indices usually contain `.ds-` (they usually start with this prefix, but not always as shrunk indices will have the
+     * `shrink-` prefix for e.g.) but given the `modify data stream API` any index name can be a backing index.
+     * For this reason this comparator groups the indices that don't contain `.ds-` in the lower generations, and the ones that do
+     * contain `.ds-` are ordered by the original (provided) backing index name - the name starting with `.ds-`.
+     * The goal is to make sure the prefixed (usually read-only - shrink-, restored-, partial-) backing indices do not end up being the
+     * write index of the local data stream.
+     */
+    private static final Comparator<Index> LOCAL_DATA_STREAM_INDICES_COMPARATOR = Comparator.comparing(
+        (Index o) -> o.getName().contains(BACKING_INDEX_PREFIX) ? 1 : -1
```
Comment (jbaiera) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java:73]: One last refinement I thought of is the unlikely edge case that there is a `.ds-` prefixed backing index in the data stream that might have been moved over from a different data stream. Maybe we should parameterize this comparator instance with the data stream name and use it in the partition step: 

```
private String partitionByIndexBaseName = BACKING_INDEX_PREFIX + dataStreamName;
...
o.getName().contains(partitionByIndexBaseName)
```
instead of just using the `BACKING_INDEX_PREFIX` to partition indices? It's a very unlikely edge case but I think it seals things up pretty well while we think about a better long term fix than sorting by index name.

**Comment by andreidan** [comment]
@elasticsearchmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM! Thanks for the iterations!

**Review by martijnvg — APPROVED** [review]
LGTM for this fix.

> I appreciate we might want to employ a longer-term fix where we potentially replicate the generation together with the index?

I wished we made write index a separate property of a data stream instead of a convention that the last index is the list of backing indices is the write index. #90820 shows how fragile this is. Maybe this can be considered in as a followup change? (downside is that only new versions can take advantage of this...)

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
Thanks @martijnvg I'll open a `>feature`

**Comment by andreidan** [comment]
Opened https://github.com/elastic/elasticsearch/issues/90991 to follow up
