### PR TITLE
Fix ILM history index settings

### LINKED ISSUE #61863: ILM history rollover missing alias
I've encountered a problem with the rollover of the ilm history index: 
```
[2020-09-02T18:11:43,428][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-follow-shard-tasks"}] to [{"phase":"hot","action":"unfollow","name":"pause-follower-index"}] in policy [ilm-history-ilm-policy]
[2020-09-02T18:11:43,485][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [auditbeat-7.9.0-2020.09.02-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-follow-shard-tasks"}] to [{"phase":"hot","action":"unfollow","name":"pause-follower-index"}] in policy [auditbeat]
[2020-09-02T18:11:43,554][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"pause-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"close-follower-index"}] in policy [ilm-history-ilm-policy]
[2020-09-02T18:11:43,610][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [auditbeat-7.9.0-2020.09.02-000001] from [{"phase":"hot","action":"unfollow","name":"pause-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"close-follower-index"}] in policy [auditbeat]
[2020-09-02T18:11:43,656][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"close-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] in policy [ilm-history-ilm-policy]
[2020-09-02T18:11:43,708][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [auditbeat-7.9.0-2020.09.02-000001] from [{"phase":"hot","action":"unfollow","name":"close-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] in policy [auditbeat]
[2020-09-02T18:11:43,757][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] in policy [ilm-history-ilm-policy]
[2020-09-02T18:11:43,804][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [auditbeat-7.9.0-2020.09.02-000001] from [{"phase":"hot","action":"unfollow","name":"unfollow-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] in policy [auditbeat]
[2020-09-02T18:11:43,858][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] in policy [ilm-history-ilm-policy]
[2020-09-02T18:11:43,912][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [auditbeat-7.9.0-2020.09.02-000001] from [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] in policy [auditbeat]
[2020-09-02T18:11:43,963][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [ilm-history-ilm-policy]
[2020-09-02T18:11:44,028][INFO ][o.e.x.i.IndexLifecycleTransition] [ElasticMBP.local] moving index [auditbeat-7.9.0-2020.09.02-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [auditbeat]
[2020-09-02T18:21:43,436][ERROR][o.e.x.i.IndexLifecycleRunner] [ElasticMBP.local] policy [ilm-history-ilm-policy] for index [ilm-history-3-000001] failed on step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}]. Moving to ERROR step
java.lang.IllegalArgumentException: setting [index.lifecycle.rollover_alias] for index [ilm-history-3-000001] is empty or not defined
        at org.elasticsearch.xpack.core.ilm.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:65) [x-pack-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:174) [x-pack-ilm-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:327) [x-pack-ilm-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:265) [x-pack-ilm-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:183) [x-pack-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:211) [x-pack-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```
while simply using an audit beat which I believe just triggered its own rollover.

@andreidan suggested this was introduced in https://github.com/elastic/elasticsearch/pull/61457

### PR DESCRIPTION
**Pull request by probakowski**
This change fixed settings accidentally changed in #61457, this fixes ability of ILM history index to rollover.
It also adds test to make sure we can't hit this kind of bug in the future.

Closes #61863

### CODE REVIEW

File: x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+        RolloverResponse rolloverResponse = client().admin().indices().prepareRolloverIndex(ILMHistoryStore.ILM_HISTORY_ALIAS).get();
+        String secondIndex = ILMHistoryStore.ILM_HISTORY_INDEX_PREFIX + "000002";
+        assertTrue(rolloverResponse.isAcknowledged());
+        assertThat(rolloverResponse.getNewIndex(), is(secondIndex));
+
+        GetIndexResponse getIndexResponse = client().admin().indices().prepareGetIndex().setIndices(secondIndex).get();
+        assertThat(getIndexResponse.getIndices(), arrayContaining(secondIndex));
+
+        //wait for all history items to index to avoid waiting for timeout in ILMHistoryStore beforeBulk
+        Thread.sleep(6000);
```
Comment (andreidan) [inline x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java:90]: why would `beforeBulk` timeout? would removing the policy from the `test` index and/or stopping ILM solve the issue of outstanding ilm-history entries? (we're manually rolling over the `ilm-history` alias so ILM is only needed to trigger the creation of the first history index)

Comment (probakowski) [reply x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java]: I've changed it, I stop ILM to reduce amount of history items to index and I wait for the ones that are created. It should be better than explicit wait. WDYT?

File: x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+                fail(e.getMessage());
+            }
+        });
+
+        assertTrue(client().execute(StopILMAction.INSTANCE, new StopILMRequest()).actionGet().isAcknowledged());
+
+        //wait for all history items to index to avoid waiting for timeout in ILMHistoryStore beforeBulk
+        assertBusy(() -> {
+            SearchResponse search = client().prepareSearch(firstIndex).setQuery(matchQuery("index", firstIndex)).setSize(0).get();
+            assertThat(search.getHits().getTotalHits().value, greaterThan(0L));
```
Comment (andreidan) [inline x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java:93]: should we avoid the randomisation of the ILM policy and use an empty hot phase only ILM policy? that way we can assert exactly how many items must be inserted before moving on with the test tear down. I _think_ there might be another race condition possible otherwise as the stop ILM call is not a hard stop but has to be detected and depending on what step we're in we might execute more steps (see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleService.java#L133 )

**Review by andreidan — COMMENTED** [review]
Thanks for fixing this @probakowski 

I think it's nearly done, just one more note on the test as I think it might yield some flakiness

File: x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java (hunk 2 above)
Comment (probakowski) [reply x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMHistoryTests.java]: You may be right there is still flakiness there. I've simplified policy, wait for exact number of messages to be indexed and wait for ILM to be stopped

**Comment by probakowski** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
LGTM, thanks for iterating on this Przemko
