### PR TITLE
Wait for all Rec. to Stop on Node Close

### LINKED ISSUE #45956: CI UpdateShardAllocationSettingsIT.testUpdateSameHostSetting failure
The `UpdateShardAllocationSettingsIT.testUpdateSameHostSetting` test failed in:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora-29&&immutable/226/console

It did not reproduce locally with the command:
```
./gradlew :server:integTest \
--tests "org.elasticsearch.cluster.routing.allocation.decider.UpdateShardAllocationSettingsIT.testUpdateSameHostSetting" \
-Dtests.seed=58E6AE995D30C037 \
-Dtests.security.manager=true \
-Dtests.locale=zh-SG \
-Dtests.timezone=SystemV/CST6 \
-Dcompiler.java=12 \
-Druntime.java=11
```

It failed with:
```
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
	at __randomizedtesting.SeedInfo.seed([58E6AE995D30C037:1612DD2EB1BB20A2]:0)
	at org.elasticsearch.node.Node.awaitClose(Node.java:895)
	at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:948)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:104)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:86)
	at org.elasticsearch.test.InternalTestCluster.close(InternalTestCluster.java:803)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:549)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:1966)
```
and
```
1> [2019-08-26T00:19:50,844][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_t0] [idx/Ppy6SgGdRsqN9GUNjGB7NQ] deleting index
  1> [2019-08-26T00:19:50,890][WARN ][o.e.i.IndicesService     ] [node_t1] [idx/Ppy6SgGdRsqN9GUNjGB7NQ] failed to delete index
  1> org.elasticsearch.env.ShardLockObtainFailedException: [idx][0]: obtaining shard lock timed out after 0ms, previous lock details: [shard creation] trying to lock for [deleting index directory]
  1> 	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:860) ~[main/:?]
  1> 	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:775) ~[main/:?]
  1> 	at org.elasticsearch.env.NodeEnvironment.lockAllForIndex(NodeEnvironment.java:718) ~[main/:?]
  1> 	at org.elasticsearch.env.NodeEnvironment.deleteIndexDirectorySafe(NodeEnvironment.java:670) ~[main/:?]
  1> 	at org.elasticsearch.indices.IndicesService.deleteIndexStoreIfDeletionAllowed(IndicesService.java:800) [main/:?]
  1> 	at org.elasticsearch.indices.IndicesService.deleteIndexStore(IndicesService.java:787) [main/:?]
  1> 	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:691) [main/:?]
  1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:375) [main/:?]
  1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:241) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:508) [main/:?]
  1> 	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:505) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:482) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:432) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:176) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* This issue is in the `RecoverySourceHandler#acquireStore`. If we submit the store release to the generic threadpool while it is getting shut down we never complete the futue we wait on (in the generic pool as well) and fail to ever release the store potentially (see David's explanation in https://github.com/elastic/elasticsearch/issues/45956#issuecomment-526106651)
* Fixed by waiting for all recoveries to end on node close so that we aways have a healthy thread pool here
   * The alternative of fixing this via the `ThreadPool` isn't really viable. If the pool is shut down it's shut down. We can make that visible maybe but it seems wrong when we use waiting for a clean state before stopping in other compontents as well. Also, the generic pool is specifically documented as quietly swallowing executions when shut down.
* In theory there is still a deadlock spot left here that seems practically close to impossible though (I added a TODO for it regardless).
* Closes #45956

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java [hunk 1]
```diff
@@ -74,6 +77,19 @@ public PeerRecoverySourceService(TransportService transportService, IndicesServi
             new StartRecoveryTransportRequestHandler());
     }
 
+    @Override
+    protected void doStart() {
+    }
+
+    @Override
+    protected void doStop() {
+        ongoingRecoveries.awaitEmpty();
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: Does this awaitEmpty block a node from closing? Should we just cancel all ongoing recoveries?

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 2]
```diff
@@ -402,13 +402,14 @@ private Releasable acquireStore(Store store) {
...
             final PlainActionFuture<Void> future = new PlainActionFuture<>();
-            threadPool.generic().execute(new ActionRunnable<>(future) {
-                @Override
-                protected void doRun() {
-                    store.decRef();
-                    listener.onResponse(null);
-                }
-            });
+            assert threadPool.generic().isShutdown() == false;
+            // TODO: We shouldn't use the generic thread pool here as we already execute this from the generic pool.
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: @henningandersen Maybe we need to revisit the original solution (in https://github.com/elastic/elasticsearch/pull/45409) to avoid forking here.

**Review by dnhatn — COMMENTED** [review]
Thanks, Armin. I am sure this change will stabilize CI. However, we don't answer to your question (i.e., the actual change causes these failures). I left a comment.

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java (hunk 2 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: Yes, I agree to that. I think the best path is to make closing the resources async (except the one in the outer exception handler) such that we notify the recovery-response listener after completion of closing resources (we sometimes notify first and then close).

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: @dnhatn it was my understanding that we already do cancel all ongoing recoveries when shutting down the indices service (that's what happens in practice at the moment it seems) => I didn't think I need to take any action here.

> Does this awaitEmpty block a node from closing? 

Yes, but see above. I think this is fine. In the end, if the recoveries aren't properly stopped we will eventually interrupt this wait in the test cluster code and throw an exception so this won't silently cause trouble in the future either.

**Comment by original-brownbear** [comment]
Thanks @dnhatn! Yea, this is only fixes the tests. Unfortunately, I think my TODO is very valid and we should address it. The patter of waiting for a future for a task on the same pool will just deadlock eventually in theory and we shouldn't do that.

Though imo, with the recoveries not being (and becoming even more) async it's not the worst idea even in isolation to wait for all of them to have stopped at some point during node shutdown. We do that kind of wait in other spots to ensure that we don't stop the threadpool before stopping e.g. the transport service fully and I think here it also just gets us cleaner shutdown behavior.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java [hunk 3]
```diff
@@ -157,6 +183,22 @@ synchronized void cancel(IndexShard shard, String reason) {
             }
         }
 
+        void awaitEmpty() {
+            assert lifecycle.stoppedOrClosed();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: Can we be sure that no new recoveries may start after this method has returned?

**Review by DaveCTurner — COMMENTED** [review]
I am very much +1 to stopping all recoveries at an earlier point of node shutdown. It was surprising to me to discover that we weren't already doing so.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java [hunk 4]
```diff
@@ -118,8 +134,11 @@ final int numberOfOngoingRecoveries() {
     }
 
     final class OngoingRecoveries {
+
         private final Map<IndexShard, ShardRecoveryContext> ongoingRecoveries = new HashMap<>();
 
+        private List<ActionListener<Void>> emptyListeners = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: Right, that was an oversight `null` is just fine here. Added the annotation now :)

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: The indices services close before this one so it should be fine. I added an assertion about the state of the peer recovery source service before adding a recovery though to make sure :)

**Comment by original-brownbear** [comment]
@DaveCTurner addressed your comments :)

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java [hunk 5]
```diff
@@ -118,9 +134,14 @@ final int numberOfOngoingRecoveries() {
...
 
     final class OngoingRecoveries {
+
         private final Map<IndexShard, ShardRecoveryContext> ongoingRecoveries = new HashMap<>();
 
+        @Nullable
+        private List<ActionListener<Void>> emptyListeners;
+
         synchronized RecoverySourceHandler addNewRecovery(StartRecoveryRequest request, IndexShard shard) {
+            assert lifecycle.started();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: :+1:

**Review by DaveCTurner — COMMENTED** [review]
LGTM, once [this thread](https://github.com/elastic/elasticsearch/pull/46178/files#r319791216) is resolved.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @original-brownbear. I will address the forking issue.

**Comment by original-brownbear** [comment]
Thanks @dnhatn !

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java (hunk 5 above)
Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: When such an assertion fails, we don't have context about why the assertion failed (only that `lifecycle.started()` is not true). When we write assertions like this, it is nice to provide more context, for example: `assert lifecycle.started() : lifecycle.state()` which would display the `toString` value of `lifecycle.state()` when the assertion trips, giving us more context about the failure.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java (hunk 3 above)
Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java]: Similarly to my earlier [comment](https://github.com/elastic/elasticsearch/pull/46178/files#r321236268), which is a general comment about code assertions, it would be nice to have more context here in case this assertion ever fails.
