### PR TITLE
Lazy resolve unicast hosts

### LINKED ISSUE #14441: Unicast hostname failing to resolve blocks cluster from starting
Hi folks,

there seems to be a regression from **1.7.3** to **2.0.0** regarding the `gateway.recover_after_time` setting.

``` bash
docker run --name="elasticsearch" -p 9200:9200 -p 9300:9300 -e "SERVICE_ID=$hostname" -e "SERVICE_NAME=elasticsearch" elasticsearch:2.0.0 -Des.index.number_of_shards=3 -Des.index.number_of_replicas=2 -Des.gateway.recover_after_nodes=2 -Des.gateway.expected_nodes=3 -Des.gateway.recover_after_time=5m -Des.discovery.zen.ping.multicast.enabled=false -Des.discovery.zen.ping.unicast.hosts="01.elasticsearch,02.elasticsearch,03.elasticsearch" -Des.cluster.name="logging-test" -Des.network.publish_host="${PUBLIC_IP}"
```

I run Elasticsearch on three nodes (Docker hosts). The DNS names are not immediatly available. In **1.7.3** the cluster stabilizes after a couple of minutes. In **2.0.0** the container crashes directly.

``` java
Exception in thread "main" java.lang.IllegalArgumentException: Failed to resolve address for [02.elasticsearch]
Likely root cause: java.net.UnknownHostException: 02.elasticsearch: unknown error
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
at java.net.InetAddress.getAllByName(InetAddress.java:1192)
at java.net.InetAddress.getAllByName(InetAddress.java:1126)
at org.elasticsearch.transport.netty.NettyTransport.parse(NettyTransport.java:668)
at org.elasticsearch.transport.netty.NettyTransport.addressesFromString(NettyTransport.java:620)
at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:398)
at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.<init>(UnicastZenPing.java:141)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at <<<guice>>>
at org.elasticsearch.node.Node.<init>(Node.java:198)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

### LINKED ISSUE #16412: Don't cache resolved hostnames forever
Today we use InetAddress to represent IP addresses.  InetAddress handles the work of resolving hostnames from DNS and from the local `hosts` file.  

With the security manager enabled, successful hostname lookups are cached forever to prevent spoofing attacks. I don't know if this behaviour was different before the security manager was enabled, but it seems unlikely given issues such as https://github.com/elastic/elasticsearch/issues/10337 and https://github.com/elastic/elasticsearch/issues/14441.

It would be a useful improvement to be able to specify unicast hosts as hostnames which are looked up from DNS or hosts, then if the IP addresses change and the node need to reconnect to the cluster, it can just do a fresh lookup to gather the current IPs.  Similar logic would help the clients.

If we make this change, it should be configurable (otherwise we're introducing the chance for spoofing) and we should consider the impact on hostname verification of ssl certs.

Testing this change would be hard...

### PR DESCRIPTION
**Pull request by jasontedor**
Today we eagerly resolve unicast hosts. This means that if DNS changes,
we will never find the host at the new address. Moreover, a single host
failng to resolve causes startup to abort. This commit introduces lazy
resolution of unicast hosts. If a DNS entry changes, there is an
opportunity for the host to be discovered. Note that under the Java
security manager, there is a default positive cache of infinity for
resolved hosts; this means that if a user does want to operate in an
environment where DNS can change, they must adjust
networkaddress.cache.ttl in their security policy. And if a host fails
to resolve, we warn log the hostname but continue pinging other
configured hosts.

When doing DNS resolutions for unicast hostnames, we wait until the DNS
lookups timeout. This appears to be forty-five seconds on modern JVMs,
and it is not configurable. If we do these serially, the cluster can be
blocked during ping for a lengthy period of time. This commit introduces
doing the DNS lookups in parallel on the generic thread pool, and adds a
user-configurable timeout for these lookups.

Closes #14441, closes #16412

### CODE REVIEW

**Comment by jasontedor** [comment]
@bleskes @s1monw I think this is ready for review; would you take a look?

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 1]
```diff
@@ -132,59 +146,154 @@ public UnicastZenPing(Settings settings, ThreadPool threadPool, TransportService
...
+        Objects.requireNonNull(idGenerator);
+        Objects.requireNonNull(resolveTimeout);
+        if (resolveTimeout.nanos() <= 0) {
+            throw new IllegalArgumentException("resolve timeout must be positive but was [" + resolveTimeout + "]");
+        }
+        // create tasks to submit to the executor service; we will wait up to resolveTimeout for these tasks to complete
+        final List<Callable<ResolvedHostname>> callables =
+            hosts.stream().map(hn -> lookup(hn, transportService, limitPortCounts)).collect(Collectors.toList());
+        final List<Future<ResolvedHostname>> futures =
+            threadPool.generic().invokeAll(callables, resolveTimeout.nanos(), TimeUnit.NANOSECONDS);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: We might decide this is okay, but one question is whether these lookups should be throttled at all as right now it is just spamming the generic thread pool.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 2]
```diff
@@ -114,13 +126,15 @@
 
     private final Map<Integer, SendPingsHandler> receivedResponses = newConcurrentMap();
 
-    // a list of temporal responses a node will return for a request (holds requests from other configuredTargetNodes)
+    // a list of temporal responses a node will return for a request (holds requests from other configuredHosts)
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: nit: it's just other nodes - we are pinged by any node in the previous cluster.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 1 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: I wonder whether we should use `unicastConnectExecutor` for this and keep it contained (and throttled).

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 3]
```diff
@@ -132,59 +146,158 @@ public UnicastZenPing(Settings settings, ThreadPool threadPool, TransportService
...
+                    } else {
+                        final String message = "failed to resolve host [" + hostname + "]";
+                        logger.warn(message, resolvedHostname.failure());
+                    }
+                } catch (final ExecutionException e) {
+                    final String message = "failed to resolve host [" + hostname + "]";
+                    logger.warn(message, e);
+                }
+            } else {
+                logger.warn("timed out resolving host [{}]", hostname);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: nit: can we add the timeout value here.

**Review by bleskes — CHANGES_REQUESTED** [review]
I looked at the code and left some minor comments. I have some concerns with the approach because it now delays ping to the extent of the host resolve timeouts, regardless of the incoming ping timeout. I wonder if we should use something like `SingleObjectCache` to do this refreshes in the background.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: The reason I went with this approach is since this method is also used by the file-based unicast hosts provider so it would need its own executor and we do not have a close method for plugins to allow this executor be shutdown.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 2 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: I pushed 4868321727293ea3edf11dd6b3aabe6b3d75387c.

**Comment by jasontedor** [comment]
> I looked at the code and left some minor comments. I have some concerns with the approach because it now delays ping to the extent of the host resolve timeouts, regardless of the incoming ping timeout.

The timeout can be set low (and maybe the default timeout should be set lower). The DNS entries are cached indefinitely (by the JVM) unless someone changes the security settings, so this is only an issue for users that have changing DNS entries and have changed the DNS cache TTL.

> I wonder if we should use something like `SingleObjectCache` to do this refreshes in the background.

I'm not sure, if someone loses their cluster because DNS changes now they have to wait for the cache TTL to expire and for a background refresh to complete before their cluster can reform.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java (hunk 1 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: Actually plugins can implement `Closeable` and they will be closed when the node shuts down.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: Oh, I was looking for it on the `Plugins` base class, but I see we do close a plugin if it implements `java.io.Closeable`. I think this should be made more clear and opened #21669.

**Comment by jasontedor** [comment]
@bleskes I pushed a28dc6e8a3963962464cf090c7d621b718a61f35 and have now responded to all your feedback, including our discussion in another channel where we have agreed to keep the current approach.

File: core/src/test/java/org/elasticsearch/discovery/zen/UnicastZenPingTests.java [hunk 4]
```diff
@@ -34,53 +35,121 @@
...
-        int endPort = startPort + 10;
-        Settings settings = Settings.builder()
-            .put("cluster.name", "test")
-            .put(TransportSettings.PORT.getKey(), startPort + "-" + endPort).build();
-
-        Settings settingsMismatch = Settings.builder().put(settings)
-            .put("cluster.name", "mismatch")
-            .put(TransportSettings.PORT.getKey(), startPort + "-" + endPort).build();
+        // use ephemeral ports
+        final Settings settings = Settings.builder().put("cluster.name", "test").put(TransportSettings.PORT.getKey(), 0).build();
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/discovery/zen/UnicastZenPingTests.java]: 👍

**Review by bleskes — APPROVED** [review]
LGTM. I left q regarding a potential simplification. I also really like the test change.

For posterity - the reason we opted to go with resolve-on-ping rather and than resolve-in-thebackground is that in FileDiscoveryPlugin we also do dns resolve on ping. Changing that will need a big change but without it we felt there is no need to go on a heroic effort to not delays pings on a slow dns. We may revisit in the future.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 5]
```diff
@@ -222,25 +339,38 @@ public void clearTemporalResponses() {
 
     @Override
     public void ping(final PingListener listener, final TimeValue duration) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: can we add some docs about what falls under duration?

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: I pushed 156a49b87c88e60b6ff31fd747f0648b532e1d6d.

File: core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java [hunk 6]
```diff
@@ -132,62 +146,165 @@ public UnicastZenPing(Settings settings, ThreadPool threadPool, TransportService
...
      */
-    public static List<DiscoveryNode> resolveDiscoveryNodes(final String host, final int limitPortCounts,
-                                                            final TransportService transportService, final Supplier<String> idGenerator) {
-        List<DiscoveryNode> discoveryNodes = new ArrayList<>();
-        try {
-            TransportAddress[] addresses = transportService.addressesFromString(host, limitPortCounts);
-            for (TransportAddress address : addresses) {
-                discoveryNodes.add(new DiscoveryNode(idGenerator.get(), address, emptyMap(), emptySet(),
-                                                        Version.CURRENT.minimumCompatibilityVersion()));
+    public static List<DiscoveryNode> resolveDiscoveryNodes(
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java]: Thanks. I pushed e2fc5a2d944f7641987bc79941e7f731dad8fc39.

**Comment by jasontedor** [comment]
Thanks @bleskes.
