### PR TITLE
Disallow unmapped_fields="load" with full-text search/MATCH

### LINKED ISSUE #141927: ESQL: unmapped_fields="load" not working with `MATCH`
While it's logical that we cannot run a full-text search on an unmapped field, maybe we should fail queries with `unmapped_fields="load"` rather than just returning an empty set.

To repro, unmap the `version` field from the `apps` index
```
{
    "dynamic" :  false,
    "properties" : {
        "id" : {
            "type" : "integer"
        },
        "name" : {
            "type" : "keyword"
        }
    }
}
```
and run this altered version of `match-operator.testMatchVersionFieldAsString`:
```
testMatchVersionFieldAsString
required_capability: match_operator_colon
required_capability: match_additional_types

from apps 
| where version:"2.1" 
| keep name, version;

name:keyword | version:keyword
bbbbb        | 2.1
;


Expected more data but no more entries found after [0]
Data mismatch:

Actual:
name:keyword | version:keyword

Expected:
name:keyword | version:keyword
bbbbb   
```

### PR DESCRIPTION
**Pull request by shmuelhanoch**
- Fail at analysis instead of returning empty results. 

- Add unit test testUnmappedFieldsLoadWithMatchOperatorFails in AnalyzerUnmappedTests.

Closes https://github.com/elastic/elasticsearch/issues/141927

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java [hunk 1]
```diff
@@ -3300,6 +3300,17 @@ private static String setUnmappedLoad(String query) {
         return "SET unmapped_fields=\"load\"; " + query;
     }
 
+    /**
+     * Reproducer for #141927: with unmapped_fields=load, full-text search (match operator) must fail at analysis
+     * instead of returning empty results.
+     */
+    public void testUnmappedFieldsLoadWithMatchOperatorFails() {
```
Comment (mouhc1ne) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java]: Could we add few more tests here? Not necessarily more test functions, because we can `verificationFailure(...)` many times within the same function and pass many queries, I'd suspect there is a good number of interesting cases we want covered.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 2]
```diff
@@ -272,7 +273,23 @@ public Analyzer(AnalyzerContext context, Verifier verifier) {
...
-        return verify(execute(plan), gatherPreAnalysisMetrics(plan, partialMetrics));
+        LogicalPlan analyzed = execute(plan);
+        if (context().unmappedResolution() == UnmappedResolution.LOAD) {
+            List<FullTextFunction> fullTextFunctions = new ArrayList<>();
+            analyzed.forEachExpressionDown(FullTextFunction.class, fullTextFunctions::add);
+            if (fullTextFunctions.isEmpty() == false) {
+                throw new VerificationException(
+                    List.of(
+                        Failure.fail(
+                            fullTextFunctions.get(0),
```
Comment (mouhc1ne) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Looks like only the first function gets reported. But also, is finding a full-text function anywhere in query necessary and sufficient to reject it? Or do we want the reject only if they're applied to the unmapped field?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 3]
```diff
@@ -272,7 +273,23 @@ public Analyzer(AnalyzerContext context, Verifier verifier) {
 
     public LogicalPlan analyze(LogicalPlan plan) {
         BitSet partialMetrics = new BitSet(FeatureMetric.values().length);
-        return verify(execute(plan), gatherPreAnalysisMetrics(plan, partialMetrics));
+        LogicalPlan analyzed = execute(plan);
+        if (context().unmappedResolution() == UnmappedResolution.LOAD) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: This is not the best place to add an additional verification. `Analyzer#analyze` is a pretty high-level method which has a simple workflow:
1. analyze
2. verify and gather usage data
We should keep it this way and not add low-level verifications to high-level execution logic.

We have 2 typical places for verifications that come to mind:
- inside `Verifier#verify` (there's a section marked with `Concrete verifications`)
- inside functions and commands themselves by implementing PostAnalysisPlanVerificationAware and PostAnalysisVerificationAware.

Now, neither of these places have access to the query settings. We _could_ plug the query settings in there, and in fact it might become required anyway.

However, I think there's a simpler way.

We could add a verification step inside `Verifier#verify` which checks for the presence of full-text functions _in case that the `load` setting had any effect on the query plan_.  More specifically, `load` will place `FieldAttribute` instances into the `EsRelation` which contain a `PotentiallyUnmappedKeywordEsField`. Such an attribute is thus marked as "will try to load from `_source` during execution". If we find any such field attribute in an EsRelation, we know that `load` was used, we _do_ try to load some fields from `_source`, and we can thus fail the query if it contains disallowed functions or commands.

This also means that we should add positive tests for queries where `load` _did not have any effect_ (because all fields in the query were, in fact, mapped), because full-text functions will not be forbidden in such queries.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java [hunk 4]
```diff
@@ -3300,6 +3300,17 @@ private static String setUnmappedLoad(String query) {
...
+        verificationFailure(
+            setUnmappedLoad("FROM test | WHERE first_name:\"foo\" | KEEP first_name"),
+            "unmapped_fields=\"load\" is not allowed with full-text search"
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java]: This is insufficient coverage to guard against regressions. Mimicking a naive developer whose ignorant about `load`, I could easily change the production code and allow full text functions other than `MATCH`, thus re-introducing the problem which this PR is solving. This test wouldn't fail at all if I went and re-enabled support for, say, `QSTR` or `KNN` or `MATCH_PHRASE`, ...

Minimally, I'd have the test run a query with each of the full text functions that we forbid to ensure correct behavior going forward.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java [hunk 5]
```diff
@@ -3300,6 +3300,17 @@ private static String setUnmappedLoad(String query) {
         return "SET unmapped_fields=\"load\"; " + query;
     }
 
+    /**
+     * Reproducer for #141927: with unmapped_fields=load, full-text search (match operator) must fail at analysis
+     * instead of returning empty results.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java]: Appreciate the comment pointing to the issue!

super nit: I opened https://github.com/elastic/elasticsearch/issues/144121 to explain that we plan to increase support for full-text functions. We could link to it as well so that future-us knows that the test will need changes in the future.

**Review by alex-spies — CHANGES_REQUESTED** [review]
Thanks @shmuelhanoch ! This gets the job done, but I'd like to increase test coverage and would also like to place the new verification into a slightly more appropriate place before merging. I added details below :)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Only rejecting if applied to an unmapped field would certainly be _better_, but I wouldn't go there for now.

There's FTFs like `KQL` which can refer to an unmapped field inside the query string, as in `WHERE KQL("author: Faulkner")` (taken straight from our docs). `author` might be unmapped and it's not fully clear how we should behave then.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Update: https://github.com/elastic/elasticsearch/pull/144115 adds a new section inside `Verifier#verify` where we disallow not-yet allowed commands. I think we can wait on https://github.com/elastic/elasticsearch/pull/144115 and move this PR's new validation next to it.

This is a little simpler than my original suggestion in that it will keep this PR's logic: disallow full-text functions _if the query uses `SET unmapped_fields="load"`_. No need to check `EsRelation`s for the presence of `PotentiallyUnmappedKeywordEsField`s in `FieldAttribute`s.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java (hunk 1 above)
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java]: Done, I added one for each forbidden full-text function.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java (hunk 5 above)
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java]: Linked #144121 in the test Javadoc!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 2 above)
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Change to report every full-text function in the plan.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 3 above)
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: OK, I moved the  check to  a `Verifier#verify`.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java (hunk 4 above)
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java]: Done, I added one for each forbidden full-text function (as also for Mouhcine first comment).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:119]: Here's the existing check by Andrei.

I suggest we add another helper method `checkLoadModeDisallowedFunctions` and call it here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 6]
```diff
@@ -137,6 +145,19 @@ Collection<Failure> verify(LogicalPlan plan, BitSet partialMetrics, UnmappedReso
             checkLimitBy(p, failures);
         });
 
+        // Disallow full-text search when unmapped_fields=load. We do not restrict to "only when the FTF
+        // is applied to an unmapped field" because FTFs like KQL can reference unmapped fields inside the
+        // query string (e.g. KQL("author: Faulkner")), and the desired behavior there is unclear.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java]: ++, thanks for commenting with the reason for the code here. I think this will help future us (and others!) understand the choices we made.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 7]
```diff
@@ -137,6 +145,19 @@ Collection<Failure> verify(LogicalPlan plan, BitSet partialMetrics, UnmappedReso
...
+        if (unmappedResolution == UnmappedResolution.LOAD) {
+            List<FullTextFunction> fullTextFunctions = new ArrayList<>();
+            plan.forEachExpressionDown(FullTextFunction.class, fullTextFunctions::add);
+            if (fullTextFunctions.isEmpty() == false) {
+                String message = "unmapped_fields=\"load\" is not allowed with full-text search (MATCH, match operator `:`, "
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java]: Rather than mentioning `MATCH` specifically in the error message, why don't we tell the user which full-text function they used?

Ideally, our tests should also assert that the right full text function was mentioned in the error message.

When reporting user input in error messages, we typically enclose it in brackets, like so:

```
unmapped_fields="load" does not support full-text search function [KQL]; use "fail" or "nullify"
```
except that the `KQL` needs to be replaced by the actual function that was used.

**Review by alex-spies — COMMENTED** [review]
Almost there! I have only few final comments and, once addressed, this certainly LGTM!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:119]: OK, extracted into `checkLoadModeDisallowedFunctions` here

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java (hunk 7 above)
Comment (shmuelhanoch) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java]: Sure, I fixed this to show the actual function name and check it in the tests

**Review by alex-spies — APPROVED** [review]
LGTM! Thanks @shmuelhanoch !

**Review by mouhc1ne — APPROVED** [review]
