### PR TITLE
Fix NPE on Stale Index in IndicesService

### LINKED ISSUE #38845: DedicatedClusterSnapshotRestoreIT#testRestoreShrinkIndex fails
Possibly relates #38256, at least this is the same test that still seems to be failing in latest `master` (cacf81a1cf3dff62c16c56736fef034e73a8f219).

The actual issue seems to be here:

```
  1> java.lang.NullPointerException: null
  1>    at org.elasticsearch.common.settings.IndexScopedSettings.<init>(IndexScopedSettings.java:187) ~[main/:?]
  1>    at org.elasticsearch.common.settings.IndexScopedSettings.copy(IndexScopedSettings.java:191) ~[main/:?]
  1>    at org.elasticsearch.index.IndexSettings.<init>(IndexSettings.java:434) ~[main/:?]
  1>    at org.elasticsearch.index.IndexSettings.<init>(IndexSettings.java:423) ~[main/:?]
  1>    at org.elasticsearch.indices.IndicesService.buildIndexSettings(IndicesService.java:940) ~[main/:?]
  1>    at org.elasticsearch.indices.IndicesService.verifyIndexIsDeleted(IndicesService.java:882) ~[main/:?]
  1>    at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:338) ~[main/:?]
  1>    at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:258) ~[main/:?]
  1>    at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:472) ~[main/:?]
  1>    at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
  1>    at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:470) ~[main/:?]
  1>    at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:459) ~[main/:?]
  1>    at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:413) [main/:?]
  1>    at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:164) [main/:?]
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [main/:?]
  1>    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [main/:?]
  1>    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [main/:?]
  1>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1>    at java.lang.Thread.run(Thread.java:834) [?:?]
```

The trouble being, I think, that there's a race in which the index directory exists without any metadata, so we get a `null` here rather than an exception:

https://github.com/elastic/elasticsearch/blob/cacf81a1cf3dff62c16c56736fef034e73a8f219/server/src/main/java/org/elasticsearch/indices/IndicesService.java#L876

I think we should throw something there rather than passing `null` to `buildIndexSettings(metaData);` a few lines further down.

### PR DESCRIPTION
**Pull request by original-brownbear**
* We should treat a `null` return for the metadata as equal to an error and break out 
  * Added the check at this level even though it required nested `throw` because adding it further downstream would impact other functionality
* We should probably still try and find a cleaner solution that doesn't cause us to have to retry file deletions when deleting eventually, but this should stabilize things for now (was able to reproduce and confirm the fix for #38845 manually) 
* Closes #38845

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/IndicesService.java [hunk 1]
```diff
@@ -874,6 +874,9 @@ public IndexMetaData verifyIndexIsDeleted(final Index index, final ClusterState
             final IndexMetaData metaData;
             try {
                 metaData = metaStateService.loadIndexState(index);
+                if (metaData == null) {
+                    throw new IllegalStateException("Index state does not exist.");
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/indices/IndicesService.java]: I wonder if we should just ignore it instead of throwing exception here and therefore logging a warning.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/indices/IndicesService.java]: makes sense removing the warning :)

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/indices/IndicesService.java]: done

**Comment by talevy** [comment]
I see the original issue failing in 7.0, so I added that version label to this PR

**Review by ywelsch — APPROVED** [review]

**Comment by ywelsch** [comment]
@original-brownbear after seeing more reports of this, I think we should backport this one to 6.7

**Comment by original-brownbear** [comment]
@ywelsch sounds good, will back port shortly :)
