### PR TITLE
[ML] Fix error on data frame analytics using a dest index without mappings

### LINKED ISSUE #60457: [ML] Data Frame Analytics fails when destination index exists but has no mappings
**Elasticsearch version**: 7.8.0
**Description of the problem including expected versus actual behavior**:
Data frame analytics jobs fails when the destination index exists. But the documentation says:
"If the destination index exists, it is used as is. You can therefore set up the destination index in advance with custom settings and mappings."

**Steps to reproduce**:
Run in Dev Tools Console

POST test-source-index-a2/_doc
{"value1": 1, "target": 1}

POST test-source-index-a2/_doc
{"value1": 2, "target": 4}

POST test-source-index-a2/_doc
{"value1": 3, "target": 9}

PUT test-dest-index-a2

PUT _ml/data_frame/analytics/test-dfa-job-a2
{
  "description": "",
  "source": {
    "index": "test-source-index-a2"
  },
  "dest": {
    "index": "test-dest-index-a2"
  },
  "analyzed_fields": {
    "excludes": []
  },
  "analysis": {
    "regression": {
      "dependent_variable": "target"
    }
  },
  "model_memory_limit": "20mb"
}

POST _ml/data_frame/analytics/test-dfa-job-a2/_start

-> Kibana Machine Learning / Data Frame Analytics shows status "failed"

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
…t mappings

This commit fixes a failure to update the mappings of the destination index
of a data frame analytics job during startup. The failure only occurs in `7.x`.
In particular, the bug occurs when the destination index contains no mappings
at all. The code used to assume there will at least be mappings for the single
type in the dest index. This assumption doesn't hold. The fix checks whether
the mappings are empty and if so creates an empty map for the `_doc` type.

Closes #60457

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DestinationIndex.java [hunk 1]
```diff
@@ -303,6 +308,18 @@ public static void updateMappingsToDestIndex(Client client,
         getFieldCapsForRequiredFields(client, config, fieldCapabilitiesListener);
     }
 
+    private static ImmutableOpenMap<String, MappingMetadata> createEmptyMappings() {
+        MappingMetadata singleDocEmptyMetadata;
+        try {
+            singleDocEmptyMetadata = new MappingMetadata(MapperService.SINGLE_MAPPING_NAME, Collections.emptyMap());
+        } catch (IOException e) {
+            throw new IllegalStateException("we should never fail to create empty mapping_metadata");
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DestinationIndex.java:316]:
```suggestion
            // we should never fail to create empty mapping_metadata
            throw new IllegalStateException("failed to create empty mapping_metadata");
```
Since this exception MAY (though should never) be written to a log read by the user.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DestinationIndex.java [hunk 2]
```diff
@@ -303,6 +308,18 @@ public static void updateMappingsToDestIndex(Client client,
...
+        }
+        return ImmutableOpenMap.<String, MappingMetadata>builder()
+            .fPut(MapperService.SINGLE_MAPPING_NAME, singleDocEmptyMetadata)
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DestinationIndex.java:319]: `MapperService.SINGLE_MAPPING_NAME` and inside

`singleDocEmptyMetadata = new MappingMetadata(MapperService.SINGLE_MAPPING_NAME, Collections.emptyMap());` 

???

Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DestinationIndex.java:319]: Yes, it looks weird but this is how it's structured in `7.x`. The map contains the type (`_doc`) as a key and the value is a `MappingMetadata` object which also has the type.

**Review by benwtrent — APPROVED** [review]
