### PR TITLE
Filter empty lines from "docker ls" response

### LINKED ISSUE #51998: [CI] DockerTests.test010Install failed multiple times
The test fails regularly on CI, mostly on `7.6` and `7.x` branches but also on `master`.

The failure on 7.6 is:
```
> Task :qa:os:destructiveDistroTest.default-docker
 org.elasticsearch.packaging.test.DockerTests > test010Install FAILED
     java.lang.RuntimeException: Command was not successful: [bash -c docker run --detach --env discovery.type=single-node --publish 9200:9200 --publish 9300:9300 elasticsearch:test]
        result: exitCode = [125] stdout = [] stderr = [Unable to find image 'elasticsearch:test' locally
     docker: Error response from daemon: manifest for elasticsearch:test not found: manifest unknown: manifest unknown.
    See 'docker run --help'.]
         at __randomizedtesting.SeedInfo.seed([AEB3DBE026C1E285:8AEC7B73446CBDDD]:0)
         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:135)
         at org.elasticsearch.packaging.util.Shell.run(Shell.java:77)
         at org.elasticsearch.packaging.util.Docker.executeDockerRun(Docker.java:162)
         at org.elasticsearch.packaging.util.Docker.runContainer(Docker.java:104)
         at org.elasticsearch.packaging.util.Docker.runContainer(Docker.java:92)
         at org.elasticsearch.packaging.test.DockerTests.setupTest(DockerTests.java:106)
```

Build scan for 7.6: https://gradle-enterprise.elastic.co/s/2rzg3s5wfa3oo

On master the error is a bit different:
```
java.lang.RuntimeException: Command was not successful: [bash -c docker exec --user elasticsearch:root --tty b2f88432b9f5dc03f3d36aed59761bc5b99eac1867480feb4415e401e073a0cf /usr/share/elasticsearch/bin/elasticsearch-keystore create]
   result: exitCode = [126] stdout = [OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown] stderr = []
```

Build scan for master: https://gradle-enterprise.elastic.co/s/tisfc272vhzxo

### PR DESCRIPTION
**Pull request by williamrandolph**
In order to cut down on test time, our docker/vagrant tests build the
docker image outside of the vagrant VM. When we get around to launching
the Vagrant VM, we mount that already-built docker image to a known
location. At that point, we need to load the docker image. But we only
want to load it once. As we're running tests, we use "docker ls" to
check whether the local image is loaded for use. Empty output from the
particular ls invocation means no image is loaded.

There was a bug in how we checked this. In Java, splitting an empty
string will yield an array containing one empty string. So when we're
counting the output from the docker ls command, we need to filter out
empty lines in order to proceed to loading the image for docker tests.

This isn't an issue in master because there we use a Java-13-only method
that doesn't have this problem.

This will fix some long-failing tests for the 7.x and 7.6 branches.

Closes #51998

### CODE REVIEW

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java [hunk 1]
```diff
@@ -76,7 +77,11 @@
      * @param distribution details about the docker image to potentially load.
      */
     public static void ensureImageIsLoaded(Distribution distribution) {
-        final long count = sh.run("docker image ls --format '{{.Repository}}' " + distribution.flavor.name).stdout.split("\n").length;
+        Shell.Result result = sh.run("docker image ls --format '{{.Repository}}' " + distribution.flavor.name);
+
+        final long count = Arrays.stream(result.stdout.split("\n"))
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: Figured I'd add the token "this could be simpler" comment 😉 

```
return Arrays.stream(result.stdout.split("\n"))
                .map(String::trim)
                .noneMatch(String::isEmpty);
```

Comment (williamrandolph) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: I'll break up the complicated filter, but I think I'll keep the `count` approach.

**Comment by williamrandolph** [comment]
The failures here ought to be addressed by #51498.

**Review by pugnascotia — APPROVED** [review]

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by williamrandolph** [comment]
Backport is here: https://github.com/elastic/elasticsearch/pull/52373
