### PR TITLE
Propagating nested inner_hits to the parent compound retriever

### LINKED ISSUE #116397: Missing inner_hits from the top-level results in a compound retriever
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

When using a compound retriever, any `inner_hits` defined in its sub-retrievers are not propagated to the top-level retriever and are not part of the final results. 

### Steps to Reproduce

E.g. using `inner_hits` on a `semantic` query: 
```
POST retrievers_example/_search
{
    "retriever": {
        "rrf": {
            "retrievers": [
                {
                    "standard": {
                        "query": {
                            "nested": {
                                "path": "inference_field.inference.chunks",
                                "query": {
                                    "sparse_vector": {
                                        "field": "inference_field.inference.chunks.embeddings",
                                        "inference_id": "my-elser-endpoint",
                                        "query": "some query text"
                                    }
                                },
                                "inner_hits": {
                                    "size": 2,
                                    "name": "inference_chunks",
                                    "_source": [
                                        "inference_field.inference.chunks.text"
                                    ]
                                }
                            }
                        }
                    }
                },
                {
                    "standard": {
                        "query": {
                            "match_all": { } 
                        }
                    }
                }
            ],
            "rank_window_size": 10,
            "rank_constant": 1
        }
    }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by pmpailis**
In this PR we update the `RankDocsQueryBuilder` so that any inner hits that were requested as part of any sub-retriever are propagated to the top-level compound retriever, and that (as an optimization) `inner_hit` computation is disabled for anything but the top-level retriever.

Closes https://github.com/elastic/elasticsearch/issues/116397

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/retriever/RankDocsRetrieverBuilder.java [hunk 1]
```diff
@@ -141,6 +141,9 @@ public void extractToSearchSourceBuilder(SearchSourceBuilder searchSourceBuilder
         if (searchSourceBuilder.size() + searchSourceBuilder.from() > rankDocResults.length) {
             searchSourceBuilder.size(Math.max(0, rankDocResults.length - searchSourceBuilder.from()));
         }
+        if (compoundUsed) {
```
Comment (pmpailis) [inline server/src/main/java/org/elasticsearch/search/retriever/RankDocsRetrieverBuilder.java:144]: Another approach would be to wrap this in a new `AbstractQueryBuilder` that would just override the `extractInnerHitBuilders` to be a no-op and would delegate everything else to the current instance.

File: x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml [hunk 2]
```diff
@@ -960,3 +966,55 @@ setup:
...
+                    }
+                  }
+                },
+                {
+                  standard: {
+                    query: {
+                      match_all: { }
+                    }
+                  }
+                }
```
Comment (benwtrent) [inline x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:1007]: we need to see how inner hits are scored even when when there are inner hits provided in multiple retrievers. What do we do when there are inner hits set for knn and inner hits set for a regular query? How do we unify?

Comment (pmpailis) [reply x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:1046]: Updated the test to account for this. As things stand, we would have 2 separate entries for each retriever, one for each `inner_hit` specified (with null/empty entries if the field is not present). 
One thing to note is that if we're computing `inner_hits` for the same nested field, we have to provide custom names otherwise we'll throw an error of having duplicate inner hits.

File: server/src/main/java/org/elasticsearch/index/query/RankDocsQueryBuilder.java [hunk 3]
```diff
@@ -55,6 +53,17 @@ public RankDocsQueryBuilder(StreamInput in) throws IOException {
         }
     }
 
+    @Override
+    protected void extractInnerHitBuilders(Map<String, InnerHitContextBuilder> innerHits) {
+        if (queryBuilders != null) {
+            for (QueryBuilder query : queryBuilders) {
+                if (query instanceof AbstractQueryBuilder) {
+                    ((AbstractQueryBuilder<?>) query).extractInnerHitBuilders(innerHits);
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/query/RankDocsQueryBuilder.java:61]: Should this be:
```suggestion
                if (query instanceof AbstractQueryBuilder clause) {
                    InnerHitContextBuilder.extractInnerHits(clause, innerHits);
```
?

File: server/src/main/java/org/elasticsearch/search/retriever/CompoundRetrieverBuilder.java [hunk 4]
```diff
@@ -254,6 +254,7 @@ protected SearchSourceBuilder createSearchSourceBuilder(PointInTimeBuilder pit,
         }
         sortBuilders.add(new FieldSortBuilder(FieldSortBuilder.SHARD_DOC_FIELD_NAME));
         sourceBuilder.sort(sortBuilders);
+        sourceBuilder.skipInnerHits(true);
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/retriever/CompoundRetrieverBuilder.java:257]: Should we rely on the fact that the compound retriever will always set this? I mean why do we need to set this on the knn and standard retriever too? 
We should also ensure that implementations of the `CompoundRetrieverBuilder` calls `super.createSourceBuilder` first if they want to modify the source builder. `TextSimilarityRankRetrieverBuilder` does it own thing and already diverged (missing the shard id sort and now this new skip inner hits).

**Review by jimczi — COMMENTED** [review]
Thanks @pmpailis , I left some comments.

File: x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:1046]: @pmpailis yeah, custom names is sort of expected, but rrf should be able to provide names by default, since the passed retrievers are in an array, their order is guaranteed, so, we should be able to name them automatically for folks. 


We also need to consider what it means to merge the final inner_hits view, e.g. combining the inner hits themselves via rrf for a given doc to indicate the best individual inner hit.

File: server/src/main/java/org/elasticsearch/index/query/RankDocsQueryBuilder.java (hunk 3 above)
Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/index/query/RankDocsQueryBuilder.java:61]: The `InnerHitContextBuilder#extractInnerHits` calls the `extractInnerHitBuilder` method on the `AbstractQueryBuilder` and throws if a different instance type is passed, so, IIUC, seems equivalent . 

Can refactor however to directly call the ` InnerHitContextBuilder.extractInnerHits` as suggested, which also removes the need to check instance type here and throw if needed, as we'd normally do.

File: server/src/main/java/org/elasticsearch/search/retriever/CompoundRetrieverBuilder.java (hunk 4 above)
Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/search/retriever/CompoundRetrieverBuilder.java:257]: That's a fair point! Will update to ensure that the parent `createSourceBuilder` will always be called, and remove the checks from the individual retrievers.

File: x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml (hunk 2 above)
Comment (pmpailis) [reply x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:1046]: > so, we should be able to name them automatically for folks.

The name is currently extracted from a `InnerHitBuilder` member in the appropriate query builders (e.g. `HasParentQueryBuilder` , `NestedQueryBuilder` , etc). Should we apply some custom logic to act iff the underlying queries are any of the above types? 

> combining the inner hits themselves via rrf for a given doc to indicate the best individual inner hit.

So give the option to  apply `rrf` to the different inner hits rankings to provide a (locally) global ranking? That would be interesting! Do you think though that this should be tracked as part of this PR or would it be something to discuss and handle separately?

File: server/src/main/java/org/elasticsearch/index/query/RankDocsQueryBuilder.java (hunk 3 above)
Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/index/query/RankDocsQueryBuilder.java]: Updated.

File: server/src/main/java/org/elasticsearch/search/retriever/CompoundRetrieverBuilder.java (hunk 4 above)
Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/search/retriever/CompoundRetrieverBuilder.java:257]: Updated.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java [hunk 5]
```diff
@@ -40,7 +40,7 @@ public InnerHitsPhase(FetchPhase fetchPhase) {
 
     @Override
     public FetchSubPhaseProcessor getProcessor(FetchContext searchContext) {
-        if (searchContext.innerHits() == null || searchContext.innerHits().getInnerHits().isEmpty()) {
+        if (searchContext.skipInnerHits() || searchContext.innerHits() == null || searchContext.innerHits().getInnerHits().isEmpty()) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java:43]: It might be more straightforward to skip inner hits in the query parsing, here:https://github.com/elastic/elasticsearch/blob/09146792256211b47549e162af5177309b4c3107/server/src/main/java/org/elasticsearch/search/SearchService.java#L1288 and here https://github.com/elastic/elasticsearch/blob/09146792256211b47549e162af5177309b4c3107/server/src/main/java/org/elasticsearch/search/SearchService.java#L1292

This way we don't need to propagate the info in the search context.

Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java:43]: That's a nice suggestion, thanks @jimczi ! Will update accordingly.  Only minor comment that I have is that we would now have multiple places of control instead of just one, on the inner hits phase itself.

File: x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:1046]: > Should we apply some custom logic to act iff the underlying queries are any of the above types?

I am saying, users forgetting to put a _name will be exceptionally common and if we can help them by automatically naming things, it would be very nice :). But this can be done in a follow up PR.

> Do you think though that this should be tracked as part of this PR or would it be something to discuss and handle separately?

Something separate for now. I would expect it to be a new inner hits option that is only available for rrf or something.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java (hunk 5 above)
Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java]: Updated in https://github.com/elastic/elasticsearch/pull/116408/commits/167605f89afd26b3deefdcb8647707fcf0c20e38

**Comment by pmpailis** [comment]
@elasticmachine update branch

File: x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml [hunk 6]
```diff
@@ -960,3 +980,87 @@ setup:
   - length: { hits.hits : 1 }
 
   - match: { hits.hits.0._id: "1" }
+
+---
+"rrf retriever with inner_hits for sub-retriever":
```
Comment (jimczi) [inline x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:985]: Should we skip the BWC tests here?

**Review by jimczi — APPROVED** [review]
LGTM

File: x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml (hunk 6 above)
Comment (pmpailis) [reply x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/rrf/700_rrf_retriever_search_api_compatibility.yml:985]: Added a new capability in https://github.com/elastic/elasticsearch/pull/116408/commits/1172be3fd1d2463a784157b3f2dcca0fd7e12929

**Comment by pmpailis** [comment]
@elasticmachine update branch
