### PR TITLE
Make RestHighLevelClient's Request class public

### LINKED ISSUE #26455: RestHighLevelClient cannot be sub classed outside of the `org.elasticsearch.client` package.
**Elasticsearch High Level REST Client version** 5.6.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:

`RestHighLevelClient` javadoc states that

> Can be sub-classed to expose additional client methods that make use of endpoints added to Elasticsearch through plugins, or to add support for custom response sections, again added to Elasticsearch through plugins.

I would expect to be able to call all the protected methods if I am sub-classing from another package, but actually I currently need access to the `Request` class in order to do so.

I am not willing to write my extension code in `org.elasticsearch.client` package in order to be able to extend it. The public/protected API should be sufficient to do so in my own package.

**Steps to reproduce**:
There are two test cases that shows that `RestHighLevelClient` can be extended (`RestHighLevelClientExtTests` and `CustomRestHighLevelClientTests`), but the subclasses (`RestHighLevelClientExt` and `CustomRestClient`) are defined in the same package as `RestHighLevelClient`, if you move them in another package they no longer compile.

### PR DESCRIPTION
**Pull request by tlrx**
`Request` class is currently package protected, making it difficult for
the users to extend the `RestHighLevelClient` and to use its protected
methods to execute requests. This commit makes the `Request` class public
and changes few methods of `RestHighLevelClient` to be protected.

closes #26455

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Review by cbuescher — APPROVED** [review]
Thanks, LGTM

File: client/rest-high-level/src/test/java/org/elasticsearch/client/RequestTests.java [hunk 1]
```diff
@@ -77,20 +79,42 @@
 
 public class RequestTests extends ESTestCase {
 
+    public void testConstructor() throws Exception {
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/RequestTests.java]: can we also test the visibility of the class and its constructor by checking their modifiers?

**Comment by tlrx** [comment]
Thanks all for your reviews!

@javanna I just added tests for what your requested. Can you please have another look?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/extension/CustomRestHighLevelClientTests.java [hunk 2]
```diff
@@ -17,19 +17,17 @@
  * under the License.
  */
 
-package org.elasticsearch.client;
+package org.elasticsearch.client.extension;
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/extension/CustomRestHighLevelClientTests.java]: sorry I didn't notice this before, but why changing the package here? It would be nice to be able to test everything we need with reflection, rather than changing package... unless there's another reason why this was done.

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/extension/CustomRestHighLevelClientTests.java]: No other reason, just to make it more obvious that ` CustomRestClient` extends the high level rest client while being located in a different package.

Comment (rjernst) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/extension/CustomRestHighLevelClientTests.java]: Please let's not make an arbitrary (and inconsistent) change like that. We do not use "extension" packages anywhere else.

**Comment by tlrx** [comment]
@javanna I updated the code and remove the ` extension`  package. Do you want to have another look?

**Review by javanna — APPROVED** [review]
LGTM thanks @tlrx

**Comment by tlrx** [comment]
elasticsearch-ci retest this please
