### PR TITLE
Use alias name from rollover request to query indices stats

### LINKED ISSUE #40771: Rollover action fails when user has index privilege only on alias
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.2

**Description of the problem including expected versus actual behavior**:
Rollover action fails with unauthorized access when the user does 
not have access to concrete index but only to alias.

In `TransportRolloverAction` before doing rollover we resolve
source index name (write index) from the alias in the rollover request..
Before evaluating the conditions and executing rollover action, we
retrieve stats, but to do so we used the source index name
resolved from the alias instead of what is in the request.
https://github.com/elastic/elasticsearch/blob/fcc715818fc1b9b13c5b76c8c7b86e5b5ed2f42e/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java#L111-L123
**Expected behavior:**
The rollover action should succeed.

**Actual behavior:**
Fails with 
```
action [indices:monitor/stats] is unauthorized for user [ufoo]
```

**Steps to reproduce**:
- Create an index with alias
```
PUT /foo-index-00001 '{ "aliases" : { "foo_alias" : {} } }'
```
- Create a user with a role
```
PUT /_xpack/security/user/ufoo '{ "password": "foobar", "roles" : [ "foo_role" ]  }'

PUT /_xpack/security/role/foo_role '{ "cluster": [ "all" ], "indices": [ { "names": ["foo_alias"], "privileges": ["all"] } ] }'
```
- Index some documents using created user (`ufoo`)
```
POST /foo_alias/_doc '{ "field" : "foo" }'
POST /foo_alias/_doc '{ "field" : "foo" }'
```
- try rollover
```
POST /foo_alias/_rollover '{ "conditions": { "max_docs": 1 } }'
```

### PR DESCRIPTION
**Pull request by bizybot**
In `TransportRolloverAction` before doing rollover we resolve
source index name (write index) from the alias in the rollover request.
Before evaluating the conditions and executing rollover action, we
retrieve stats, but to do so we used the source index name
resolved from the alias instead of alias from the index.
This fails when the user is assigned a role with index privilege on the
alias instead of the concrete index. This commit fixes this by using
the alias from the request.

Closes #40771

### CODE REVIEW

**Review by albertzaharovits — APPROVED** [review]
I am game with the main code change.
I would love if you'd add an `IntegTest` so that we don't catch authorization errors in Rest tests...

However, I think we should make the Rollover action use the client for index and alias creation. WDYT?

**Comment by albertzaharovits** [comment]
Ah, I'm sorry, I mean `createIndexService.createIndex` to be replaced with `client.indices().create()` . I think the user of the rollup action should necessitate the create index privilege, at least this is my perception of the authorization with "action granularity".
This is a discussion suggestion for an issue as a follow-up, not to be addressed here.

**Comment by tvernum** [comment]
@talevy Are you able to review the (1 line) change to the transport action? It looks like you were the last person to make actual functional changes to that action, and I'd appreciate a review from someone who knows that code better than we do.

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java [hunk 1]
```diff
@@ -120,7 +120,7 @@ protected void masterOperation(final RolloverRequest rolloverRequest, final Clus
         final String rolloverIndexName = indexNameExpressionResolver.resolveDateMathExpression(unresolvedName);
         MetaDataCreateIndexService.validateIndexName(rolloverIndexName, state); // will fail if the index already exists
         checkNoDuplicatedAliasInIndexTemplate(metaData, rolloverIndexName, rolloverRequest.getAlias());
-        client.admin().indices().prepareStats(sourceIndexName).clear().setDocs(true).execute(
+        client.admin().indices().prepareStats(rolloverRequest.getAlias()).clear().setDocs(true).execute(
```
Comment (talevy) [inline server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java]: I will have to check, but I'm not sure this is the same thing.

will stats for shards of all the matched read-aliases be returned in this case? For example,
If the alias points to multiple indices, then we may be checking stats of indices that are of no 
concern to us.

File: x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+        name: [ "write_manage_alias" ]
+        ignore: 404
+
+  - do:
+      indices.delete:
+        index: [ "logs-000001" ]
+        ignore: 404
+
+---
+"Test rollover, index via write alias of index":
```
Comment (talevy) [inline x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml]: can we add a test that has an alias that references multiple indices, where one of them is the write index.

**Review by talevy — COMMENTED** [review]
I still need to test my comments, but I figure sending this out earlier is better. let me know if 
what I said makes sense!

**Review by talevy — CHANGES_REQUESTED** [review]
I just ran this check to assert my theory:

```
PUT alpha
{
  "aliases": {
    "my_alias": {
      "is_write_index": true
    }
  }
}

PUT beta
{
  "aliases": {
    "my_alias": {
      "is_write_index": false
    }
  }
}

PUT alpha/_doc/1?refresh
{
  "foo": "bar"
}

PUT beta/_doc/1?refresh
{
  "foo": "bar"
}

POST /my_alias/_rollover/new_index?dry_run
{
  "conditions": {
    "max_docs":  2
  }
}
```

this returns an incorrect rollover evaluation (the write index "alpha" only has one document):

```
{
  "acknowledged" : false,
  "shards_acknowledged" : false,
  "old_index" : "alpha",
  "new_index" : "new_index",
  "rolled_over" : false,
  "dry_run" : true,
  "conditions" : {
    "[max_docs: 2]" : true
  }
}
```

I think the additional change that would make this work would be this:

```diff
@@ -249,7 +249,7 @@ public class TransportRolloverAction extends TransportMasterNodeAction<RolloverR
 
     static Map<String, Boolean> evaluateConditions(final Collection<Condition<?>> conditions, final IndexMetaData metaData,
                                                     final IndicesStatsResponse statsResponse) {
-        return evaluateConditions(conditions, statsResponse.getPrimaries().getDocs(), metaData);
+        return evaluateConditions(conditions, statsResponse.getIndex(metaData.getIndex().getName()).getPrimaries().getDocs(), metaData);
     }
```

The issue is that the code was looking at the total DocStats of all the indices returned in the stats-response. This change should make it so that we are looking at the sourceIndex only. The non-docstats condition (index age) is done on the correct IndexMetaData of the sourceIndex, so this should not be a problem.

File: x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml (hunk 2 above)
Comment (talevy) [reply x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml]: I take back this recommendation. This check should be done in the original rollover tests. security is unrelated

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java (hunk 1 above)
Comment (talevy) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java]: update: this does have semantic differences given how the stats response is interpreted. Looks like a solution to correct this exists (in separate review comment)

Comment (bizybot) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java]: Thank you @tvernum, @talevy! This is indeed a problem.

Your suggestion does fix the problem, but is there any performance hit we should be concerned of? (As we ask for stats using alias it is going to check for all the indices it points to)

I could not find a way to restrict stats request to write only index, I assume we do not have that capability. Do you think we should consider adding it if there is indeed a performance hit?

File: x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml (hunk 2 above)
Comment (bizybot) [reply x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/31_rollover_using_alias.yml]: I have added the test in the RolloverIT, Thank you.

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java (hunk 1 above)
Comment (talevy) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java]: That is a good question. Although it is unfortunate that we are collecting stats on potentially a lot of indices/shards, I am not sure performance is of the upmost importance for this API. This API is a management api that already takes a while due to allocation lag, etc. 

It is good to note that this stats call would potentially hit hundreds of indices, assuming a user has daily rollover indices with ILM, but the API is designed to handle this in general, so it feels safe to do this internally here.

**Review by talevy — COMMENTED** [review]
Changes to Rollover look good to me. I'm not against 
getting another opinion regarding my comments around 
performance concerns.

Due to the difficulty of controlling time for the additional test in RolloverIT, 
what do you think of moving these additional tests as unit tests 
in `TransportRolloverActionTests`. That way we can control the 
state of the indices such that only the write-index meets the 
relevant criteria (max_age, max_docs, max_size).

**Review by talevy — APPROVED** [review]
LGTM

**Review by tvernum — APPROVED** [review]
LGTM
