### PR TITLE
Use query circuit breaker for wildcard/regexp determinization

### LINKED ISSUE #145128: OOM during regex query construction
We saw a Serverless project (small, 1GB heap) OOM as a result of a regex query on March 26 (Lucene 10.4).

The heap dump showed a large HashMap of org.apache.lucene.util.automaton.FrozenIntSet in org.apache.lucene.util.automaton.Automaton$Builder.

I think this relates to the followup mentioned in https://github.com/elastic/elasticsearch/pull/142150 - OOM during DFA construction. What do you think @drempapis?

Hot threads captured via the search task watchdog show search threads doing the following shortly before the crash:
```
    app/org.apache.lucene.core@10.4.0/org.apache.lucene.util.automaton.Operations.determinize(Operations.java:737)
    app/org.apache.lucene.core@10.4.0/org.apache.lucene.search.RegexpQuery.toAutomaton(RegexpQuery.java:191)
    app/org.apache.lucene.core@10.4.0/org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:176)
    app/org.apache.lucene.core@10.4.0/org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:143)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.mapper.StringFieldType.regexpQuery(StringFieldType.java:207)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.search.QueryStringQueryParser.getRegexpQuerySingle(QueryStringQueryParser.java:764)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.search.QueryStringQueryParser.getRegexpQuery(QueryStringQueryParser.java:741)
    app/org.apache.lucene.queryparser@10.4.0/org.apache.lucene.queryparser.classic.QueryParserBase.handleBareTokenQuery(QueryParserBase.java:819)
    app/org.apache.lucene.queryparser@10.4.0/org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:492)
    app/org.apache.lucene.queryparser@10.4.0/org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:364)
    app/org.apache.lucene.queryparser@10.4.0/org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:249)
    app/org.apache.lucene.queryparser@10.4.0/org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:221)
    app/org.apache.lucene.queryparser@10.4.0/org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:137)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.search.QueryStringQueryParser.parse(QueryStringQueryParser.java:842)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:946)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.query.LeafQueryBuilder.doToQuery(LeafQueryBuilder.java:37)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:136)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:123)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.index.query.SearchExecutionContext.toQuery(SearchExecutionContext.java:560)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.search.SearchService.parseSource(SearchService.java:1724)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.search.SearchService.createContext(SearchService.java:1474)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:916)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$9(SearchService.java:757)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.search.SearchService$$Lambda/0x0000000051fd3788.get(Unknown Source)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:79)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:76)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1114)
    app/org.elasticsearch.server@9.4.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
    java.base@25.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
    java.base@25.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
    java.base@25.0.2/java.lang.Thread.runWith(Thread.java:1487)
    java.base@25.0.2/java.lang.Thread.run(Thread.java:1474)
```

### PR DESCRIPTION
**Pull request by drempapis**
Closes: #145128

### Problem

When Lucene converts a pattern (wildcard or regexp) into a query, it builds an NFA (non-deterministic finite automaton), then calls `Operations.determinize()` to convert it to a DFA. Determinization uses the powerset construction, which can cause exponential blowup in the number of DFA states for patterns like `*a*b*c*d*e*f*`. 

Lucene has a CPU-based work limit (`TooComplexToDeterminizeException`), but that doesn't bound memory,  the JVM can OOM long before the work limit is hit.

### Solution: CircuitBreakingOperations.determinize

The core of this PR is a new class `CircuitBreakingOperations` that provides a forked version of Lucene's `Operations.determinize`. The implementation  keeps Lucene’s determinization logic intact, but adds circuit-breaker-aware memory checks during construction.

- Accepts CircuitBreaker + label parameters.
- If the breaker is null, it directly delegates to Lucene `Operations.determinize` (same behavior).
- Tracks newly created DFA states and, every **fixed** interval (64 states), reserves estimated memory on the breaker (~200 bytes/state estimate).
- Uses try/finally to release temporary reserved bytes, even on exceptions.
- Still keeps Lucene’s normal workLimit / `TooComplexToDeterminizeException` logic.

The changes in this class against the original are the following
```
@@
-public static Automaton determinize(Automaton a, int workLimit) {
+public static Automaton determinize(Automaton a, int workLimit,
+    @Nullable CircuitBreaker circuitBreaker, String label) {

+  if (circuitBreaker == null) {
+    return Operations.determinize(a, workLimit);
+  }

   if (a.isDeterministic()) { return a; }
   if (a.getNumStates() <= 1) { return a; }

   long effortLimit = workLimit * (long) 10;

+  int newStatesCreated = 0;
+  long totalReserved = 0;

   try {
     while (worklist.size() > 0) {
       for (int i = 0; i < points.count; i++) {

         worklist.add(p);
         b.setAccept(q, accCount > 0);
         newstate.put(p, q);

+        newStatesCreated++;
+        if (newStatesCreated % CB_CHECK_INTERVAL == 0) {
+          long estimatedNewBytes =
+              CB_CHECK_INTERVAL * ESTIMATED_BYTES_PER_STATE;
+          circuitBreaker.addEstimateBytesAndMaybeBreak(
+              estimatedNewBytes, label);
+          totalReserved += estimatedNewBytes;
+        }
       }
     }
   } finally {
+    if (totalReserved > 0) {
+      circuitBreaker.addWithoutBreaking(-totalReserved);
+    }
   }

   Automaton result = b.finish();
   assert result.isDeterministic();
   return result;
}
```

There are heuristic alternatives that avoid forking Lucene, but this PR takes the most precise approach.

As a follow-up, I propose contributing an API extension to Lucene that adds a progress callback to `Operations.determinize`, for example:
```
public static Automaton determinize(
    Automaton a,
    int workLimit,
    LongConsumer memoryProgressCallback
) { ... }
```

The caller (ES) could then pass a callback such as `bytes -> circuitBreaker.addEstimateBytesAndMaybeBreak(bytes, label)` during determinization.

This would be the cleanest long-term solution and would let us remove the fork entirely, though it depends on Lucene’s acceptance and release timeline.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/lucene/util/automaton/CircuitBreakingOperations.java [hunk 1]
```diff
@@ -0,0 +1,461 @@
...
+     *                       to {@code Operations.determinize}
+     * @param label          descriptive label for circuit breaker error messages
+     * @return the determinized automaton
+     * @throws TooComplexToDeterminizeException if effort exceeds {@code workLimit}
+     * @throws org.elasticsearch.common.breaker.CircuitBreakingException if the breaker trips
+     */
+    public static Automaton determinize(Automaton a, int workLimit, @Nullable CircuitBreaker circuitBreaker, String label) {
+        if (circuitBreaker == null) {
+            return Operations.determinize(a, workLimit);
+        }
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/lucene/util/automaton/CircuitBreakingOperations.java]: If we are already checking up stream, I say switch this to an assert and make this a required non-nullable right?

**Review by benwtrent — COMMENTED** [review]
This mostly makes sense to me. 

I would like to know @iverase 's opinion, he has played around in this area to optimize and make things cheaper in the past.

File: server/src/main/java/org/elasticsearch/lucene/util/automaton/CircuitBreakingOperations.java (hunk 1 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/lucene/util/automaton/CircuitBreakingOperations.java]: Updated

**Review by benwtrent — APPROVED** [review]
I think this makes sense to me. @iverase if you have a different opinion.

**Review by iverase — APPROVED** [review]
Make sense to me too
