### PR TITLE
Extract `AbstractGeoIpDownloader` for shared concurrency logic

### LINKED ISSUE #130681: [CI] IngestGeoIpClientYamlTestSuiteIT test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with geopoint mapping (both missing and including location)} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9206 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/ljjvyagzkvges)
- [elasticsearch-periodic-platform-support #9171 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/bnvrxwgqk54r6)

**Reproduction Line:**
```
./gradlew ":modules:ingest-geoip:yamlRestCompatTest" --tests "org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT.test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with geopoint mapping (both missing and including location)}" -Dtests.seed=50220DE895215C4 -Dtests.locale=dje -Dtests.timezone=SystemV/PST8 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3Dingest_geoip%2F20_geoip_processor%2FTest%20geoip%20processor%20with%20geopoint%20mapping%20(both%20missing%20and%20including%20location)%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <4>
     but: was <3>
```

**Issue Reasons:**
- [main] 2 failures in test test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with geopoint mapping (both missing and including location)} (1.1% fail rate in 187 executions)
- [main] 2 failures in step ubuntu-2404-aarch64_checkrestcompat_platform-support-arm (33.3% fail rate in 6 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (33.3% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #133597: [CI] IngestGeoIpClientMultiProjectYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10299 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/g4atwtwestikk)
- [elasticsearch-periodic-platform-support #10275 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/sias4hroknvzg)
- [elasticsearch-periodic-platform-support #10200 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/mcusfi3k5kbwo)
- [elasticsearch-periodic-platform-support #10179 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/k73vkl3n6reh4)
- [elasticsearch-periodic-platform-support #10172 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/gydlx65glbtyo)

**Reproduction Line:**
```
./gradlew ":modules:ingest-geoip:qa:multi-project:yamlRestTest" --tests "org.elasticsearch.ingest.geoip.IngestGeoIpClientMultiProjectYamlTestSuiteIT.test {yaml=ingest_geoip/10_basic/ingest-geoip installed}" -Dtests.seed=D506A3813E81FCEB -Dtests.locale=en-SD -Dtests.timezone=Asia/Dushanbe -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.geoip.IngestGeoIpClientMultiProjectYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.ingest.geoip.IngestGeoIpClientMultiProjectYamlTestSuiteIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: iterable with items ["GeoLite2-City.mmdb", "GeoLite2-Country.mmdb", "GeoLite2-ASN.mmdb", "MyCustomGeoLite2-City.mmdb"] in any order
     but: no item matches: "MyCustomGeoLite2-City.mmdb" in ["GeoLite2-ASN.mmdb", "GeoLite2-City.mmdb", "GeoLite2-Country.mmdb"]
```

**Issue Reasons:**
- [main] 5 failures in class org.elasticsearch.ingest.geoip.IngestGeoIpClientMultiProjectYamlTestSuiteIT (0.6% fail rate in 854 executions)
- [main] 2 failures in step almalinux-8-aarch64_checkpart1_platform-support-arm (10.5% fail rate in 19 executions)
- [main] 3 failures in step ubuntu-2404-aarch64_checkpart1_platform-support-arm (15.0% fail rate in 20 executions)
- [main] 5 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135132: [CI] IngestGeoIpClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10817 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/osigft6pt7s24)
- [elasticsearch-pull-request #95011 / rest-compatibility](https://gradle-enterprise.elastic.co/s/ms5z7drabuysu)
- [elasticsearch-pull-request #94961 / rest-compatibility](https://gradle-enterprise.elastic.co/s/aijpkcd3qmxao)
- [elasticsearch-periodic-platform-support #10811 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/nnijrujyejozu)
- [elasticsearch-periodic-java-ea #33 / checkrestcompat_ubuntu-2404](https://gradle-enterprise.elastic.co/s/3lvh7sk5zrkze)
- [elasticsearch-periodic-platform-support #10793 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/yp5xvcu6s2udk)
- [elasticsearch-periodic-platform-support #10787 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/bmsaxyjpun2jc)
- [elasticsearch-pull-request #94434 / rest-compatibility](https://gradle-enterprise.elastic.co/s/g44jgyccbh4sg)
- [elasticsearch-periodic-platform-support #10775 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/mgvh2iak74acs)

**Reproduction Line:**
```
./gradlew ":modules:ingest-geoip:yamlRestCompatTest" --tests "org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT.test {yaml=ingest_geoip/30_geoip_stats/Test geoip stats}" -Dtests.seed=561BE732C8350EFE -Dtests.locale=sc-Latn-IT -Dtests.timezone=America/St_Kitts -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: iterable with items ["GeoLite2-City.mmdb", "GeoLite2-Country.mmdb", "GeoLite2-ASN.mmdb", "MyCustomGeoLite2-City.mmdb"] in any order
     but: no item matches: "GeoLite2-Country.mmdb" in ["MyCustomGeoLite2-City.mmdb", "GeoLite2-ASN.mmdb", "GeoLite2-City.mmdb"]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step ubuntu-2404-aarch64_checkrestcompat_platform-support-arm
- [main] 9 failures in class org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT (0.9% fail rate in 993 executions)
- [main] 3 failures in step rest-compatibility (1.0% fail rate in 313 executions)
- [main] 5 failures in step ubuntu-2404-aarch64_checkrestcompat_platform-support-arm (62.5% fail rate in 8 executions)
- [main] 5 failures in pipeline elasticsearch-periodic-platform-support (62.5% fail rate in 8 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 323 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135158: [CI] IngestGeoIpClientYamlTestSuiteIT test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with list} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10739 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/rm3lsh5mkbzve)
- [elasticsearch-periodic-platform-support #10721 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/pbe4mxoef6hgi)

**Reproduction Line:**
```
./gradlew ":modules:ingest-geoip:yamlRestCompatTest" --tests "org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT.test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with list}" -Dtests.seed=9B5F2FB369AE999A -Dtests.locale=to-TO -Dtests.timezone=Etc/GMT+10 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Byaml%3Dingest_geoip%2F20_geoip_processor%2FTest%20geoip%20processor%20with%20list%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <4>
     but: was <3>
```

**Issue Reasons:**
- [main] 2 failures in test test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with list} (1.3% fail rate in 159 executions)
- [main] 2 failures in step ubuntu-2404-aarch64_checkrestcompat_platform-support-arm (50.0% fail rate in 4 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
In #134223, we modified the concurrency design of the `EnterpriseGeoIpDownloader`. Before that, both `EnterpriseGeoIpDownloader` and `GeoIpDownloader` shared the exact same concurrency implementation. In this PR, we move the improved concurrency design of `EnterpriseGeoIpDownloader` to `AbstractGeoIpDownloader` and make `GeoIpDownloader` extend this class as well. This way, both classes are aligned on the concurrency implementation and will both benefit from any future improvements/modifications.

There is likely more logic in these two classes that can be moved to the abstract class, but I'm leaving that for future work, to keep the scope of this PR limited to the concurrency improvements.

Incidentally, I am optimistic that this will resolve the following test failures. I've been running the GeoIP YAML test suites for thousands of iterations on `main`, but haven't been able to reproduce the failures at all. The reported failure messages are almost exactly the same as the one in #126124, which was addressed by #134223. Therefore, I'm closing these issues for now.
Closes #130681
Closes #133597
Closes #135132
Closes #135158

### CODE REVIEW

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+import org.elasticsearch.tasks.TaskId;
+import org.elasticsearch.threadpool.Scheduler;
+import org.elasticsearch.threadpool.ThreadPool;
+
+import java.util.Map;
+import java.util.concurrent.atomic.AtomicInteger;
+import java.util.function.Supplier;
+
+/**
+ * Abstract base class for GeoIP downloaders that download GeoIP databases.
```
Comment (szybia) [inline modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java]: nit/learning: idk what the ES convention is (and whether there is any), but do we typically indicate something is thread-safe?

i don't see the usual `@ThreadSafe` annotation, thoughts on:

```suggestion
 * Abstract thread-safe base class for GeoIP downloaders that download GeoIP databases.
```

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+            // If queuedRuns is still > 0, then a run was requested while we were running, so we need to run again.
+            if (queuedRuns.addAndGet(-currentQueueSize) > 0) {
+                logger.debug("Downloader on demand requested again while running, scheduling another run");
+                threadPool.generic().submit(this::runOnDemand);
+            }
+        }
+    }
+
+    /**
+     * Download, update, and clean up GeoIP databases as required by the GeoIP processors in the cluster.
```
Comment (szybia) [inline modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java:153]: nit: might be nice to know without scanning code

```suggestion
     * Download, update, and clean up GeoIP databases as required by the GeoIP processors in the cluster.
     * Guaranteed to not be called concurrently.
```

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderTaskExecutor.java [hunk 3]
```diff
@@ -153,7 +153,7 @@ private void setEagerDownload(Boolean eagerDownload) {
             this.eagerDownload = eagerDownload;
             GeoIpDownloader currentDownloader = getTask(ProjectId.DEFAULT);
             if (currentDownloader != null && Objects.equals(eagerDownload, Boolean.TRUE)) {
-                currentDownloader.requestReschedule();
+                currentDownloader.requestRunOnDemand();
```
Comment (szybia) [inline modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderTaskExecutor.java:156]: can you help me understand why not `restartPeriodicRun` here and on line 268? 🙏 

seems to me like if we run downloader now, why not cancel and push back periodic run too

my guess is it's simpler so don't update periodic run more often than we need to?

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java [hunk 4]
```diff
@@ -0,0 +1,166 @@
+/*
```
Comment (szybia) [inline modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java:1]: is `>non-issue` the right label for this PR? it would be if we were just updating `EnterpriseGeoIpDownloader` but we're changing the other one too

i'd think `>bug` here, no? 🤔

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java (hunk 1 above)
Comment (nielsbauman) [reply modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java]: I don't think there is much of a convention there. I at least don't remember seeing it before in ES, but that doesn't prove much. I am not opposed to your suggestion, thanks.

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderTaskExecutor.java (hunk 3 above)
Comment (nielsbauman) [reply modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderTaskExecutor.java:156]: > my guess is it's simpler so don't update periodic run more often than we need to?

Yep, that's pretty much it. I only call `restartPeriodicRun` when the task starts (i.e. in `nodeOperation`) or when the poll interval changes. Otherwise, we just care about running the downloader ASAP.

You're right in that it is reasonable to push back the periodic run because we're already running the downloader right now, but the cost savings are minimal, so I prefer to keep it simple. Let me know if you have other thoughts or opinions.

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java (hunk 4 above)
Comment (nielsbauman) [reply modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/AbstractGeoIpDownloader.java:1]: Hmm yeah I was on the fence about that. I guess you're right; `>bug` makes more sense. I just need to update the changelog after the bot adds it, as the current PR title isn't very helpful as a changelog.

**Review by szybia — APPROVED** [review]
👏

File: docs/changelog/137660.yaml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+pr: 137660
+summary: Improve concurrency design of `GeoIpDownloader`
+area: Ingest Node
+type: bug
+issues:
```
Comment (joegallo) [inline docs/changelog/137660.yaml:5]: You love to see it. 😄

**Comment by joegallo** [comment]
I added a trivial commit to tweak a poorly worded assert (I fall upon my sword, it was me and Keith a year ago).

Other than that:

**Review by joegallo — APPROVED** [review]
Great work, ship it!

**Comment by nielsbauman** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/137780)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/137781)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
