### PR TITLE
Restore API: Fix file settings handling

### LINKED ISSUE #122429: Cluster readiness service stops after global snapshot restore
### Elasticsearch Version

8.15.2

### Installed Plugins

_No response_

### Java Version

OpenJDK 64-Bit Server VM (build 22.0.1+8-16)

### OS Version

Linux 6.6.56+ x86_64

### Problem Description

In https://github.com/elastic/elasticsearch/pull/84375 a new readiness service was introduced that allows a simple tcp check. We've been using this service successfully for some time as a Kubernetes readiness probe endpoint.

As of Elasticsearch 8.14+ the readiness check condition was modified in https://github.com/elastic/elasticsearch/pull/106437 to also check for `fileSettingsApplied` and not just `masterElected`.

Since this change if you restore a snapshot with `include_global_state: true` the readiness service will shut down and all your nodes will become unready. You will see the following log messages:

```
{"type": "ElasticSearch", "timestamp": "2025-02-03T15:30:06,500Z", "level": "INFO", "component": "o.e.r.ReadinessService", "cluster.name": "test-cluster", "node.name": "test-data-1, "message": "readiness change: masterElected=true" }
{"type": "ElasticSearch", "timestamp": "2025-02-03T15:30:06,502Z", "level": "INFO", "component": "o.e.r.ReadinessService", "cluster.name": "test-cluster", "node.name": "test-data-1, "message": "readiness service up and running on 0.0.0.0:9399" }
{"type": "ElasticSearch", "timestamp": "2025-02-03T15:32:29,127Z", "level": "INFO", "component": "o.e.r.ReadinessService", "cluster.name": "test-cluster", "node.name": "test-data-1", "message": "readiness change: fileSettingsApplied=false", "cluster.uuid": "REDACTED", "node.id": "REDACTED  }
{"type": "ElasticSearch", "timestamp": "2025-02-03T15:32:29,128Z", "level": "INFO", "component": "o.e.r.ReadinessService", "cluster.name": "test-cluster", "node.name": "test-data-1" "message": "stopping readiness service on channel /0.0.0.0:9399", "cluster.uuid": "REDACTED", "node.id": "REDACTED"  }
```

The cluster will NOT recover by itself until you manually force a master re-election by restarting the existing master. After that you will see:

```
{"type": "ElasticSearch", "timestamp": "2025-02-03T17:09:51,808Z", "level": "INFO", "component": "o.e.r.ReadinessService", "cluster.name": "test-cluster", "node.name": "test-data-1", "message": "readiness change: masterElected=false", "cluster.uuid": "REDACTED", "node.id": "REDACTED"  }
{"type": "ElasticSearch", "timestamp": "2025-02-03T17:09:52,349Z", "level": "INFO", "component": "o.e.r.ReadinessService", "cluster.name": "test-cluster", "node.name": "test-data-1", "message": "readiness change: masterElected=true", "cluster.uuid": "REDACTED", "node.id": "REDACTED"  }
```

The workaround appears to be providing an empty operator setting.json file on each node's disk:

```
{
  "metadata": {
      "version": "1",
      "compatibility": "8.4.0"
  },
  "state": {
      "cluster_settings": {}
  }
}
```

If this file is present, the problem will not occur. I believe this may be due to the file's presence forcing a different code path in `handleSnapshotRestore` (see https://github.com/elastic/elasticsearch/pull/89321/files#diff-5a2c0417a5b4bdbcc6873fc853db7a8c531b47536bd41b84e20bb6c7b21ad6d9R160).

It is unexpected that doing a global snapshot restore breaks the readiness service. If you are using the readiness service in a Kubernetes environment your cluster may become entirely unreachable causing downtime.

### Steps to Reproduce

1. Create a new ES 8.15.2 cluster.
2. Take a snapshot.
3. Restore the snapshot with `include_global_state: true`
4. At this point the readiness service shuts down on all nodes and will not come back until you re-elect a master (e.g. by forcefully restarting the master node).

### Logs (if relevant)

See issue description.

### PR DESCRIPTION
**Pull request by mamazzol**
When restoring a snapshot including global state, do not remove the reserved state, but initialise an empty one. This prevents the readiness service from crashing.
Also, initialising an empty state now correctly removes pre-existing reserved state settings and file settings.

Fixes #122429

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/SnapshotsAndFileSettingsIT.java [hunk 1]
```diff
@@ -164,8 +172,8 @@ public void testRestoreWithRemovedFileSettings() throws Exception {
             getSettingsResponse.persistentSettings().get(InternalClusterInfoService.INTERNAL_CLUSTER_INFO_TIMEOUT_SETTING.getKey()),
             equalTo("25s")
         );
-        // We didn't remove the setting set by file settings, we simply removed the reserved (operator) section.
-        assertThat(getSettingsResponse.persistentSettings().get("indices.recovery.max_bytes_per_sec"), equalTo("50mb"));
+        // File setting were re-set as the file was absent, this trumps the snapshot restore.
```
Comment (mamazzol) [inline server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/SnapshotsAndFileSettingsIT.java:175]: If I restore a snapshot that has reserved settings in a cluster that has no file settings: 
1. Should the restore process take precedence and apply the previous settings in a way where they don't get overwritten by the absence of the file being processed. 
2. Should the absence of the file take precedence as the setup of this cluster and therefore discard any reserved setting saved in the snapshot.

I went with number 2 but this can be up for discussion.

Comment (prdoyle) [reply server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/SnapshotsAndFileSettingsIT.java:175]: I agree that 2 is the only way to keep this coherent. Restoring to a state that's impossible to reach any other way is of dubious value. If we wanted to restore the file settings along with the snapshot, and therefore preserve the reserved state, we ought to do so.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 2]
```diff
@@ -1969,6 +1969,7 @@ private void restartNode(NodeAndClient nodeAndClient, RestartCallback callback)
         if (callback.validateClusterForming() || excludedNodeIds.isEmpty() == false) {
             // we have to validate cluster size to ensure that the restarted node has rejoined the cluster if it was master-eligible;
             validateClusterFormed();
+            callback.onClusterFormed();
```
Comment (prdoyle) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: This seems like such a good idea that it's hard to believe we don't have something like this already.

File: server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java [hunk 3]
```diff
@@ -322,6 +324,71 @@ public void testReservedStatePersistsOnRestart() throws Exception {
...
+                assertFalse("File should still be absent after restart", Files.exists(watchedFile));
+
+                logger.info("--> verify reserved state is cleared when missing file is processed at startup");
+                final ClusterStateResponse clusterStateResponse = clusterAdmin().state(new ClusterStateRequest(TEST_REQUEST_TIMEOUT))
+                    .actionGet();
+                ReservedStateMetadata reservedState = clusterStateResponse.getState()
+                    .metadata()
+                    .reservedStateMetadata()
+                    .get(FileSettingsService.NAMESPACE);
+                assertThat(reservedState, notNullValue());
```
Comment (mark-vieira) [inline server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java]: Is there any possibility of a race condition here? Since reserved state is process async, is there a possibility that the "clearing" hasn't been finished before we assert on it here?

**Review by prdoyle — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/reservedstate/service/FileSettingsServiceTests.java [hunk 4]
```diff
@@ -455,7 +454,7 @@ public void testHandleSnapshotRestoreClearsMetadata() throws Exception {
         Metadata.Builder metadata = Metadata.builder(state.metadata());
         fileSettingsService.handleSnapshotRestore(state, ClusterState.builder(state), metadata, ProjectId.DEFAULT);
 
-        assertThat(metadata.build().reservedStateMetadata(), anEmptyMap());
+        verify(controller).initEmpty(FileSettingsService.NAMESPACE, ActionListener.noop());
```
Comment (mark-vieira) [inline server/src/test/java/org/elasticsearch/reservedstate/service/FileSettingsServiceTests.java:457]: Why would we change this assertion here? We want to assert that the resultant metadata is empty right? Not that some particular method was called. This seems more fragile.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 5]
```diff
@@ -2527,6 +2528,11 @@ public boolean clearData(String nodeName) {
         public boolean validateClusterForming() {
             return true;
         }
+
+        /**
+         * Executed when the cluster is formed, if {@link #validateClusterForming()} returns true
+         */
+        public void onClusterFormed() throws Exception {}
```
Comment (mark-vieira) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I don't think this callback is necessary. The `restart()` methods block until the cluster is formed (assume `validateClusterForming` returns `true`). If you need to verify something after cluster formation this can just be done immediately after the call to restart.

**Review by mark-vieira — CHANGES_REQUESTED** [review]

File: server/src/test/java/org/elasticsearch/reservedstate/service/FileSettingsServiceTests.java (hunk 4 above)
Comment (mamazzol) [reply server/src/test/java/org/elasticsearch/reservedstate/service/FileSettingsServiceTests.java:457]: I changed it because the metadata are not emptied anymore as part of that specific method call. My understanding is that they will eventually be cleared when the clusterstate update will be processed.

Comment (mark-vieira) [reply server/src/test/java/org/elasticsearch/reservedstate/service/FileSettingsServiceTests.java:457]: Ah, I see. Yeah, this isn't ideal IMO but probably fine enough.

File: server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java (hunk 3 above)
Comment (prdoyle) [reply server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java]: &lt;sigh> We're overdue for a straightforward, sanctioned way to wait for various things to be done. Eventual consistency sucks for testing (and for users, but that's another topic). I suppose a callback on a `CountdownLatch` or similar could do it, though it somewhat sucks to have to rediscover this for each test.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 5 above)
Comment (prdoyle) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: (Cool, good to know!)

File: server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java (hunk 3 above)
Comment (prdoyle) [reply server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java]: (Also the `CountdownLatch` technique only works if your callback is _only_ called at the appropriate time. Since "exactly once" semantics are sometimes hard to implement in systems, they often settle for "at least once", and then the callback can occasionally have extra bonus calls, which can make the `CountdownLatch` technique flaky in various ways.)

Comment (mamazzol) [reply server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java]: I tried adding the CountdownLatch technique present in other parts of this test class, but I wasn't able to find the sweet spot to make it work. The fact that the file processing happens right at startup means I cannot bind the listener before or after the restart as that is too early or too late.

I added the assertBusy as a way of handling it but I am happy to evaluate different ways if this is not good enough.

**Review by mark-vieira — APPROVED** [review]

**Comment by mamazzol** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/137878)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
