### PR TITLE
Fixed quote_field_suffix in query_string

### LINKED ISSUE #29324: Query String Query with quote_field_suffix not using the quote_field_suffix field to search
**Elasticsearch version**
6.2.3

**Plugins installed**: []
X-Pack

**JVM version** (`java -version`):
1.8.0_162

**Description of the problem including expected versus actual behavior**:

Query string query with `quote_field_suffix` not using the correct field for search.  Simple query string query seems to work correctly.  Also, this works fine in version 5.6 and 6.0 alpha 2

**Steps to reproduce**:

```
PUT testindex
{
  "settings": {
    "analysis": {
      "analyzer": {
        "english_exact": {
          "tokenizer": "standard",
          "filter": [
            "lowercase"
          ]
        }
      }
    },
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "type": {
      "properties": {
        "body": {
          "type": "text",
          "analyzer": "english",
          "fields": {
            "exact": {
              "type": "text",
              "analyzer": "english_exact"
            }
          }
        }
      }
    }
  }
}

PUT testindex/type/1
{
  "body": "Ski resort"
}

PUT testindex/type/2
{
  "body": "A pair of skis"
}

PUT testindex/type/3
{
  "body": "ski boots"
}

POST testindex/_refresh

GET testindex/_search                               <-- works fine 
{
  "query": {
    "simple_query_string": {
      "fields": [ "body" ],
      "quote_field_suffix": ".exact",
      "query": "\"ski boot\""
    }
  }
}

GET testindex/_search
{
  "query": {
    "query_string": {
      "fields": [ "body" ],
      "quote_field_suffix": ".exact",
      "query": "\"ski boot\""
    }
  }
}

GET testindex/_validate/query?rewrite 
{
  "query": {
    "query_string": {
      "fields": [ "body" ],
      "quote_field_suffix": ".exact",
      "query": "\"ski boot\""
    }
  }
}
```

The result of the rewrite seems to drop the `exact` multi-field.

### PR DESCRIPTION
**Pull request by jimczi**
This change fixes the handling of the `quote_field_suffix` option on `query_string`
 query. The expansion was not applied to default fields query.

Closes #29324

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java [hunk 1]
```diff
@@ -264,6 +265,16 @@ private Query applyBoost(Query q, Float boost) {
             // Filters unsupported fields if a pattern is requested
             // Filters metadata fields if all fields are requested
             return resolveMappingField(context, field, 1.0f, !allFields, !multiFields, quoted ? quoteFieldSuffix : null);
+        } else if (quoted && quoteFieldSuffix != null) {
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java]: When looking at how the field suffix is handled in SimpleQueryStringQuery#newPhraseQuery I saw there is a helper called  QueryParserHelper.resolveMappingFields which might be reused here. At least the new unit tests pass when using that helper. It does a little more than the code here, so I'm not sure if that would be a good idea though.

**Review by cbuescher — COMMENTED** [review]
@jimczi I took a look and found some helper that might be reusable. It does a few more things, so I'm not sure if it good to reuse it though. Would like to hear your opinion.

File: server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java]: Good call, I pushed https://github.com/elastic/elasticsearch/pull/29332/commits/0abf44c2e0dded87f69b1fdf67dc7820f13cb433

Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java]: Thanks, thats what I tried locally. I wasn't sure it works in this case though because it also seems to resolve some regex patterns around wildcards etc... and I thought maybe this isn't wanted here, but glad it can be reused.

**Review by cbuescher — APPROVED** [review]
LGTM

**Review by jpountz — APPROVED** [review]
