### PR TITLE
Fix test reproducability in AbstractBuilderTestCase setup

### LINKED ISSUE #32400: [Tests] AbstractBuilderTestCase reproducibility is broken
Rest extending AbstractBuilderTestCase (essential all Query- and AggregationBuilder unit test) are not reproducible with the info that we log on test failure. The random values generated in each test method change depending on whether the method is run separately (e.g. with -Dtest.method) or the whole test suite is run. This happens even when fixing the full seed and not just the master seed.

To demonstrate this, add the following test method to e.g. RangeQueryBuilderTests:

```
    public void testRandomness() {
        assertEquals(-7481642973173394925L, randomLong());
    }
```

The whole test suite passes with `97B45898EB8C54FC` as the master seed:
```
./gradlew :server:test -Dtests.seed=97B45898EB8C54FC -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests
```

However, only running with `-Dtests.method="testRandomness"`, this fails with a different random long value than expected:
```
./gradlew :server:test -Dtests.seed=97B45898EB8C54FC -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests -Dtests.method="testRandomness"
```
```
   > Throwable #1: java.lang.AssertionError: expected:<-7481642973173394925> but was:<-6611281964877420649>
   >    at __randomizedtesting.SeedInfo.seed([97B45898EB8C54FC:F0156D024791DA56]:0)
```

Using the full seed as reported above when running the full suite works, so this passes:
```
./gradlew :server:test -Dtests.seed=97B45898EB8C54FC:F0156D024791DA56  -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests
```

But fails when using the REPRODUCE log line that includes the "-Dtests.method" parameter:
```
./gradlew :server:test -Dtests.seed=97B45898EB8C54FC:F0156D024791DA56 \
 -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests -Dtests.method="testRandomness"
```

### PR DESCRIPTION
**Pull request by cbuescher**
Currently AbstractBuilderTestCase generates certain random values in its
`beforeTest()` method annotated with @Before only the first time that a test
method in the suite is run. This changes the values of subsequent random values
and has the effect that when running single methods from a test suite with
"-Dtests.method=*", the random values it sees are different from when the same
test method is run as part of the whole test suite. This makes it harder to use
the reproduction lines logged on failure.

This changes the above method so that `beforeTest` will do the same call to the
random value source each time a test method is run, so reproduction by running
just one method is possible again.

Closes #32400

### CODE REVIEW

**Review by jimczi — COMMENTED** [review]
Good catch @cbuescher , I left a comment

File: test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java [hunk 1]
```diff
@@ -231,8 +233,13 @@ public static void afterClass() throws Exception {
 
     @Before
     public void beforeTest() throws IOException {
+        // the two following ranomized parameters are drawn every run, even though we use them in
+        // creating ServiceHolder just once. The other times are necessary so that further random
+        // generation stays the same for all test that is run, otherwise reproducability breaks
+        Settings indexSettings = createTestIndexSettings();
+        long now = randomNonNegativeLong();
```
[the remark this answers is not in the document]
Comment (cbuescher) [reply test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java]: Good point, I will change this for `now`, I don't think we need different values for now for different test cases. For `indexVersionCreated` I find this to be more difficult. We have at least three tests (ParentIdQueryBuilderTests, HasChildQueryBuilderTests, HasParentQueryBuilderTests) overwriting createTestIndexSettings to create a specialized version setting (it seems to be restricted to CURRENT). I'm not sure we can use this mechanism of overwriting default versions in specific tests if the call this in a static context in BeforeClass. I might have missed something though, let me know what you think.

**Comment by cbuescher** [comment]
@jimczi thanks for the review, I updated the PR by adressing one of your suggestions, left a question for the other. Let me know what you think about it.

File: test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java [hunk 2]
```diff
@@ -196,12 +198,17 @@ public static void afterClass() throws Exception {
 
     @Before
     public void beforeTest() throws IOException {
+        // the two following ranomized parameters are drawn every run, even though we use them in
+        // creating ServiceHolder just once. The other times are necessary so that further random
+        // generation stays the same for all test that is run, otherwise reproducability breaks
+        Settings indexSettings = createTestIndexSettings();
```
Comment (javanna) [inline test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java]: The proposed fix is ok, but I wonder if the following wouldn't be better:

```
    @Before
    public void beforeTest() throws Exception {
        if (serviceHolder == null) {
            assert serviceHolderWithNoType == null;
            long masterSeed = SeedUtils.parseSeed(RandomizedTest.getContext().getRunnerSeedAsString());
            RandomizedTest.getContext().runWithPrivateRandomness(masterSeed, (Callable<Void>) () -> {
                serviceHolder = new ServiceHolder(nodeSettings, indexSettings(), getPlugins(), AbstractBuilderTestCase.this, true);
                serviceHolderWithNoType = new ServiceHolder(nodeSettings, indexSettings(), getPlugins(), AbstractBuilderTestCase.this, false);
                return null;
            });
        }
        serviceHolder.clientInvocationHandler.delegate = this;
        serviceHolderWithNoType.clientInvocationHandler.delegate = this;
    }
```

The idea is to execute this conditional initialization step under the suite randomness rather than the method randomness. If we don't want to parse the suite seed back from a string we could also generate our own suite seed, the important bit is that we generate it in the beforeClass which is executed under the suite randomness (master seed). I find that this way what we are doing is clearer. The proposed fix is good but can easily be reverted by mistake by just moving lines around.

**Comment by javanna** [comment]
I left one comment, I think it would also be good to add a test for this but it's quite tricky to do and I don't have a good idea around that. I had a quick look at some of our base test classes to see where we do similar things (conditionally initialize static variables in before methods, and generate random values as part of such init methods) and I  think that `ESClientYamlSuiteTestCase` and `ESRestTestCase` have the same issue.

File: test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java (hunk 2 above)
Comment (cbuescher) [reply test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java]: Great suggestion, I added this.

**Comment by cbuescher** [comment]
@javanna thanks for the suggestion, I added it in another commit, together with some comment summing up the resoning for it so we don't forget why we are doing this here. Can you take another look?

File: test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java [hunk 3]
```diff
@@ -173,15 +175,19 @@ protected static String createUniqueRandomName() {
...
         // we have to prefer CURRENT since with the range of versions we support it's rather unlikely to get the current actually.
-        indexVersionCreated = randomBoolean() ? Version.CURRENT
+        Version indexVersionCreated = randomBoolean() ? Version.CURRENT
                 : VersionUtils.randomVersionBetween(random(), Version.V_6_0_0, Version.CURRENT);
         return Settings.builder()
             .put(IndexMetaData.SETTING_VERSION_CREATED, indexVersionCreated)
             .build();
     }
 
+    protected IndexSettings indexSettings() {
```
Comment (javanna) [inline test/framework/src/main/java/org/elasticsearch/test/AbstractBuilderTestCase.java]: could this be static?

**Review by javanna — APPROVED** [review]
LGTM thanks @cbuescher !

**Review by jimczi — APPROVED** [review]
