### PR TITLE
Limit number of suppressed S3 deletion errors

### LINKED ISSUE #123354: Limit number of suppressed S3 deletion errors
When issuing blob deletions to S3, there is no limit to the number of errors that we accumulate while [deletions](https://github.com/elastic/elasticsearch/blob/12fcdd8633f03159a8f1505d2f828ed0bba06709/modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java#L377) are ongoing. The combination of large snapshot clean ups which would issue many such calls, and all deletions and their retries failing e.g. due to some setup issue, could lead to a huge amount of memory usage and potentially OOMing the node. It is not clear how severe the same issue can be in other object stores, since it might depend a bit on the error responses that the SDK returns and how large it is, but theoretically this could still happen there too. We should limit the suppressed errors we keep while issuing deletes as I do not think there is any value in recording all of these in the exception (I'm not even sure they are preserved).

### PR DESCRIPTION
**Pull request by pxsalehi**
We've seen this being an issue on 7.x although can happen on all 
versions (I'm pretty sure this PR doesn't cleanly back-port to 7.x though).

Closes https://github.com/elastic/elasticsearch/issues/123354

### CODE REVIEW

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java [hunk 1]
```diff
@@ -69,6 +69,8 @@ class S3BlobStore implements BlobStore {
      */
     static final int MAX_BULK_DELETES = 1000;
 
+    static final int MAX_DELETE_EXCEPTIONS = 10;
```
Comment (pxsalehi) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:72]: I've picked this randomly more or less. Not sure what it should be. I'm not sure having more than this is useful.

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java [hunk 2]
```diff
@@ -340,6 +342,8 @@ public BlobContainer blobContainer(BlobPath path) {
         return new S3BlobContainer(path, this);
     }
 
+    record DeletionExceptions(Exception exception, int count) {}
```
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:345]: TIL `Throwable#getSuppressed` is doing quite a bit more than just retrieving an array of exceptions. Still, this seems rather more complicated (and involves unnecessary allocations) vs just counting the exceptions in a separate `AtomicInteger`. We don't even need atomicity either, we could just have a class with two mutable fields to keep track of the suppression depth.

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java [hunk 3]
```diff
@@ -1073,6 +1083,38 @@ interface FailingHandlerFactory {
...
+                exchange.close();
+            } else {
+                fail("expected only deletions");
+            }
+        });
+        try {
+            var maxNoOfDeletions = 2 * S3BlobStore.MAX_DELETE_EXCEPTIONS;
+            var blobs = randomList(1, maxNoOfDeletions * maxBulkDeleteSize, ESTestCase::randomIdentifier);
+            blobContainer.deleteBlobsIgnoringIfNotExists(randomPurpose(), blobs.iterator());
+            fail("deletion should not succeed");
```
Comment (DaveCTurner) [inline modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:1112]: I'd prefer an `expectThrows` here (around just the `deleteBlobsIgnoringIfNotExists` call)

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (pxsalehi) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java]: sure see https://github.com/elastic/elasticsearch/pull/123630/commits/6b85c33f207adc773fa6802ec80c295e9b310809.

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java (hunk 3 above)
Comment (pxsalehi) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java]: also done in https://github.com/elastic/elasticsearch/pull/123630/commits/6b85c33f207adc773fa6802ec80c295e9b310809.

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java (hunk 1 above)
Comment (DaveCTurner) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:71]: :+1: fine by me

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java [hunk 4]
```diff
@@ -340,6 +341,18 @@ public BlobContainer blobContainer(BlobPath path) {
         return new S3BlobContainer(path, this);
     }
 
+    private static class DeletionExceptions {
+        private Exception exception = null;
```
Comment (DaveCTurner) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:345]: May as well be package-private since we access it from outside this class.

```suggestion
        Exception exception = null;
```

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java [hunk 5]
```diff
@@ -162,6 +163,16 @@ protected BlobContainer createBlobContainer(
...
+    ) {
+        return createBlobContainer(maxRetries, readTimeout, disableChunkedEncoding, bufferSize, null);
+    }
+
+    protected BlobContainer createBlobContainer(
+        final @Nullable Integer maxRetries,
+        final @Nullable TimeValue readTimeout,
+        final @Nullable Boolean disableChunkedEncoding,
+        final @Nullable ByteSizeValue bufferSize,
+        final @Nullable Integer maxBulkDeletes
```
Comment (DaveCTurner) [inline modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:175]: I'd rather just have the one method rather than having to work out which variant is being called (and what the implied default params) are in each case. I know it adds a bunch of noise here but it'll be better in the long run.

**Review by DaveCTurner — COMMENTED** [review]
Production code looks good, just one more thing about the new `createBlobContainer` override. I could be persuaded if you feel strongly about it.

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java (hunk 5 above)
Comment (pxsalehi) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:175]: yeah, mostly because of the noise and the fact that this way of passing these arguments is terrible to extend. Speaking of the long-run, how about replacing these with a parameter object?

Comment (DaveCTurner) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:175]: Some kind of builder would seem in order here, but maybe that can be deferred to a followup. Or do that first, reducing the noise in this PR. But either way, let's not have two methods that do almost the same thing.

Comment (pxsalehi) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:166]: https://github.com/elastic/elasticsearch/pull/123630/commits/6662a8b8802e870ce5c141606c778a06a7e6ecb6

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by pxsalehi** [comment]
`:qa:rolling-upgrade-legacy:v9.1.0#oldClusterTest` is failing. Not sure even what that is, and can't find anything besides some gradle error in the build log. I'll merge main into this to pull in a few gradle/build related commits.

**Comment by ywangd** [comment]
post-merge LGTM

I raised #123953 as a minor improvement for the relevant log message.

**Comment by pxsalehi** [comment]
Backporting to 7.17 seems a bit ugly. The code is too different and some settings the test relies on don't exit there. I'm gonna skip it. If you'd like to have anyway, let me know.
