### PR TITLE
Linearizability checker memory reduction

### LINKED ISSUE #39437: CoordinatorTests.testDiscoveryUsesNodesFromLastClusterState fails on CI
The test `CoordinatorTests testDiscoveryUsesNodesFromLastClusterState` failed on CI today with an OOM:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2262/consoleFull

It reproduces locally using:
```
./gradlew :server:unitTest \
  -Dtests.seed=B59E6E6C9C7ABB73 \
  -Dtests.class=org.elasticsearch.cluster.coordination.CoordinatorTests \
  -Dtests.method="testDiscoveryUsesNodesFromLastClusterState" \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=Pacific/Ponape \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Build stats shows that it does not fail recently.

<details>
  1> [2019-02-27T18:34:42,070][INFO ][o.e.c.c.CoordinatorTests ] [testDiscoveryUsesNodesFromLastClusterState] after test
ERROR    120s J7 | CoordinatorTests.testDiscoveryUsesNodesFromLastClusterState <<< FAILURES!
   > Throwable #1: java.lang.OutOfMemoryError: GC overhead limit exceeded
   > 	at __randomizedtesting.SeedInfo.seed([B59E6E6C9C7ABB73:D3835B0AE155B36C]:0)
   > 	at java.util.Optional.of(Optional.java:108)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests$2.nextState(CoordinatorTests.java:2197)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker.isLinearizable(LinearizabilityChecker.java:228)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker.lambda$isLinearizable$0(LinearizabilityChecker.java:213)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker$$Lambda$3610/1501875111.test(Unknown Source)
   > 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
   > 	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1649)
   > 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
   > 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
   > 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
   > 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
   > 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
   > 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
   > 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
   > 	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
   > 	at org.elasticsearch.cluster.coordination.LinearizabilityChecker.isLinearizable(LinearizabilityChecker.java:213)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests$Cluster.stabilise(CoordinatorTests.java:1445)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests$Cluster.stabilise(CoordinatorTests.java:1369)
   > 	at org.elasticsearch.cluster.coordination.CoordinatorTests.testDiscoveryUsesNodesFromLastClusterState(CoordinatorTests.java:1081)
</details>

cc @DaveCTurner

### PR DESCRIPTION
**Pull request by henningandersen**
The cache used in linearizability checker now uses approximately 6x less
memory by changing the cache from a set of (bits, state) tuples into a
map from bits -> { state }.

Each combination of states is kept once only, building on the
assumption that the number of state permutations is small compared to
the number of bits permutations. For those histories that are difficult
to check we will have many bits combinations that use the same state
permutations.

We end up now using approximately 15 bytes per entry compared to 101
bytes before, ie. a 6x improvement, allowing us to linearizability check
significantly longer histories.

Re-enabled linearizability checker in CoordinatorTests, hoping above
ensures we no longer un out of memory.

Resolves #39437

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java [hunk 1]
```diff
@@ -373,4 +374,81 @@ void unlift() {
...
+            Set<Object> objects = smallMap.get(bits);
+            if (objects == null) {
+                objects = uniquePermutation(Collections.singleton(state));
+            } else {
+                if (objects.contains(state)) {
+                    return false;
+                }
+                objects = add(objects, state);
+            }
+            smallMap.put(bits, objects);
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java]: we can avoid an extra lookup here in case `smallMap.get(bits) != null` by using the `indexOf`, `indexGet` and `indexReplace` methods on the `LongObjectHashMap`.

File: server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java [hunk 2]
```diff
@@ -373,4 +374,81 @@ void unlift() {
...
+            return true;
+        }
+
+        private boolean addLarge(Object state, FixedBitSet bitSet) {
+            return largeMap.computeIfAbsent(state, k -> new HashSet<>()).add(bitSet);
+        }
+
+        private Set<Object> add(Set<Object> objects, Object state) {
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java]: let's inline this method, it's only used once. Also this allows to move the call to `uniquePermutation` to the end of `addSmall` and allows inlining `uniquePermutation` as well.

**Review by ywelsch — APPROVED** [review]
Looks great. I've left two minor comments

File: server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java (hunk 1 above)
Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java]: Fixed in 7853ddfcd5b675f0cc8c85a308b96f0588c381c7

File: server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java (hunk 2 above)
Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java]: Fixed in 7853ddfcd5b675f0cc8c85a308b96f0588c381c7
