### PR TITLE
[ML] reduce the logging spam for the ml initializer for annotation index creation

### LINKED ISSUE #65217: [ML] ML Initialisation Service should detect non-retryable errors
As an example `MlInitializationService` will create the `.ml-annotations-6` index and `.ml-annotations-write` alias if they does not exist but if an accidental write to the alias has created a concrete index this will error:
```
[ERROR][o.e.x.m.MlInitializationService] [HOST] Error creating ML annotations index or aliases
org.elasticsearch.indices.InvalidAliasNameException: Invalid alias name [.ml-annotations-write], an index exists with the same name as the alias
```

Unfortunately this message along with a stack trace will be logged on cluster change events creating a lot of log spam.

In this case the error is non-recoverable, the service should notice this and not retry either until `.ml-annotations-write` does not exist anymore or a new master node is elected at which point the new master has not noticed the error previously and will try.

### PR DESCRIPTION
**Pull request by benwtrent**
It is possible that the annotation index is in an unsupported state. Consequently, the same exception is thrown whenever the MlInitializationService attempts to create the index.

Logging all those failures at the `error` level doesn't make sense. This commit only logs the first seen (of duplicate errors) as `error` and the rest of `debug`.

Whenever the error changes, it is logged.

closes https://github.com/elastic/elasticsearch/issues/65217

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlInitializationService.java [hunk 1]
```diff
@@ -143,8 +144,13 @@ public void clusterChanged(ClusterChangedEvent event) {
                 event.state(),
                 MasterNodeRequest.DEFAULT_MASTER_NODE_TIMEOUT,
                 ActionListener.wrap(r -> isIndexCreationInProgress.set(false), e -> {
+                    if (e.getMessage().equals(previousException)) {
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlInitializationService.java:147]: Note: A bit fancier (but atomic and a bit shorter) way of writing this would be:

```
AtomicReference<String> previousException = new AtomicReference<>();
if (e.getMessage().equals(previousException.getAndSet(e.getMessage()))) {
  logger.debug(...);
} else {
  logger.error(...);
}
```

**Review by przemekwitek — APPROVED** [review]
LGTM
