### PR TITLE
[ML][Transforms] fixing stop on changes check bug

### LINKED ISSUE #45610: Tests from DataFrameGetAndGetStatsIT fail
## Example build failure
https://gradle-enterprise.elastic.co/s/gmrc7h7t4cu7w/tests/failed

## Reproduction line 
does not reproduce locally
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner --tests "org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT.testGetAndGetStats" -Dtests.seed=48708D28F42AAB77 -Dtests.security.manager=true -Dtests.locale=bez -Dtests.timezone=Etc/GMT+12 -Dcompiler.java=12 -Druntime.java=11
```

## Example relevant log:
```
org.elasticsearch.client.ResponseException: 
method [POST], host [http://[::1]:33841], URI [/_data_frame/transforms/pivot_continuous/_stop?wait_for_completion=true&force=false], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Timed out when waiting for persistent tasks after 30s"}],"type":"illegal_state_exception","reason":"Timed out when waiting for persistent tasks after 30s"},"status":500}
Close stacktrace
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:253)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:231)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205)
at org.elasticsearch.xpack.dataframe.integration.DataFrameRestTestCase.stopDataFrameTransform(DataFrameRestTestCase.java:247)
at org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT.testGetAndGetStats(DataFrameGetAndGetStatsIT.java:151)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:834)
[2019-08-15T01:27:42,625][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] before test
[2019-08-15T01:27:42,639][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] initializing REST clients against [http://[::1]:33841, http://127.0.0.1:44149]
[2019-08-15T01:28:43,904][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] There are still tasks running after this test that might break subsequent tests [data_frame/transforms[c]].
[2019-08-15T01:28:43,905][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] after test
```

## Frequency
Frequent in the last few days

### PR DESCRIPTION
**Pull request by benwtrent**
To avoid thread lock scenarios (which periodically occurred and caused havoc), we wait to determine if there are changes until `onStart` is called. This method is called when the indexer is set to `INDEXING`, and if no changes are found it calls back to the `AsyncTwoPhaseIndexer` who just sets transitions the state to the "next state".

Normally this just quickly toggles the indexer between `INDEXING` and `STARTED`.

But, between that check and the call back to the `AsyncTwoPhaseIndexer`, `stop` was called. Since the indexer was set to `INDEXING` at the time, it was transitioned to `STOPPING` and `doSaveState` was never called with the indexer set to `STOPPED`. 

To fix this we need call `doSaveState` if `AsyncTwoPhaseIndexer` transitions between `STOPPING -> STOPPED` when we don't find any changes.

If we DID discover changes, its ok as eventually `checkState` is called and transitions it to `STOPPED` with a call against `doSaveState`. 

Flagging as `non-issue` as the PR that introduced this change https://github.com/elastic/elasticsearch/pull/45511 was not backported to 7.3

closes #45610

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java [hunk 1]
```diff
@@ -158,7 +158,13 @@ public synchronized boolean maybeTriggerAsyncJob(long now) {
                         if (r) {
                             nextSearch(ActionListener.wrap(this::onSearchResponse, this::finishWithSearchFailure));
                         } else {
-                            finishAndSetState();
+                            // If our state is INDEXING then transition to STARTED
+                            // Calling checkState here covers the scenarios when
+                            // the indexer was aborted or set to STOPPING between `onStart` being called
+                            // and this branch being executed
+                            if (checkState(getState())) {
```
Comment (jimczi) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java]: I don't understand why we need this check since `finishAndSetState` checks the current state and choose the appropriate transition. Is the issue that `finishAndSetState` doesn't save the state ? Should we change the code to:
`doSaveState(finishAndSetState(), getPosition(), () -> {})` ?

**Review by jimczi — COMMENTED** [review]
I left one question

**Review by hendrikmuhs — APPROVED** [review]
LGTM

I support backporting this change to `7.4` as a stuck API is a good reason.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java]: @jimczi I updated this, please take a second look. 

There is definitely a race condition here that is painful. The issue with calling a `doSaveState` always is that the implementer does not know if the transition was from `STOPPING -> STOPPED` or `STOPPED -> STOPPED`. Or if the indexer was aborted (in which case we probably don't want to save the state.

**Comment by benwtrent** [comment]
@hendrikmuhs I agree on backporting to 7.4.

**Comment by benwtrent** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java [hunk 2]
```diff
@@ -158,7 +158,13 @@ public synchronized boolean maybeTriggerAsyncJob(long now) {
                         if (r) {
                             nextSearch(ActionListener.wrap(this::onSearchResponse, this::finishWithSearchFailure));
                         } else {
-                            finishAndSetState();
+                            // If we transition to `STOPPED` this means the previous state was `STOPPING`.
+                            // This is because we are guaranteed to originally been in an INDEXING state if `stop` is called.
+                            // Treat this like a `checkState` call that is transitioning to a STOPPED state.
+                            if (finishAndSetState() == IndexerState.STOPPED) {
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java]: @jimczi @hendrikmuhs after more thought and discussion, this seems like the simpliest and least intrusive change. 

- If `finishAndSetState() == ABORTING`, that means `onAbort` was called internally, nothing else needs to be done and just exit
- If `finishAndSetState() == STARTED`, that means it transitioned from `INDEXING` and should just exit
- If `finishAndSetState() == STOPPED`, that means it transitioned from `STOPPING` and should treat it like a normal stop and call the `doSaveState` logic from `checkState`

The indexer should NEVER be in the `STARTED` state when this branch is called. If it is, that means the child class did something unsupported and it should allow `finishAndSetState()` to throw.

Comment (jimczi) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java]: I still fail to understand why this is an issue, the code path if the indexation is over is https://github.com/elastic/elasticsearch/pull/46162/files#diff-01a4ee37232ad8becca8990702ebb4f0L355
Why can't we do the same here, e.g.: 
````
onFinish(ActionListener.wrap(
                        r -> doSaveState(finishAndSetState(), position.get(), () -> {}),
                        e -> doSaveState(finishAndSetState(), position.get(), () -> {})));
````
?
IMO there is a bug currently because `onFinish` is never call in this branch and `finishAndSetState` can call onAbort or onStop before we call onFinish again. It looks like this disrepancy was added in https://github.com/elastic/elasticsearch/pull/45511  so we should ensure that we don't call onFinish if onAbort or onStop was already called.

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java]: @jimczi you are right. All this special handling is due to a problem in our child class not in the `AsyncTwoPhaseIndexer`. I will change it to `onFinish` as that unifies the call flow.

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/2
