### PR TITLE
SQL: Fix metric aggs on date/time to not return double

### LINKED ISSUE #39492: SQL: MIN and MAX could work better with date fields
At the moment, MIN and MAX for a `date` field will return a double value. This is because Elastisearch's own  `stats` aggregation computes the values and returns them as `double`.

```
sql> select min(birth_date), max(birth_date) from test_emp;
min(birth_date)|max(birth_date)
---------------+---------------
-5.631552E11   |-1.575936E11
```

We could improve this behavior by automatically CASTing the `double` value returned to a `long` and then to a `date`.

### LINKED ISSUE #40376: SQL: Metric aggs on date fields return double
```SELECT YEAR(MAX(date)) FROM test```

throws ClassCastException.

### PR DESCRIPTION
**Pull request by matriv**
Previously metric aggregations on date fields would return a double
which caused errors when trying to apply scalar functions on top, e.g.:
```
SELECT YEAR(MAX(date)) FROM test
```

Fixes: #40376 
Fixes: #39492

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/extractor/MetricAggExtractor.java [hunk 1]
```diff
@@ -83,20 +97,33 @@ public Object extract(Bucket bucket) {
...
             // COUNT(expr) and COUNT(ALL expr) uses this type of aggregation to account for non-null values only
             return ((InternalFilter) agg).getDocCount();
         }
 
         Object v = agg.getProperty(property);
-        return innerKey != null && v instanceof Map ? ((Map<?, ?>) v).get(innerKey) : v;
+        return tryExtractDateTime(innerKey != null && v instanceof Map ? ((Map<?, ?>) v).get(innerKey) : v);
+    }
+
+    private Object tryExtractDateTime(Object object) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/extractor/MetricAggExtractor.java]: `handleDateTime/maybeDateTime` sounds better.

**Review by costin — APPROVED** [review]
Good catch. LGTM!
Yet another instance of session information...

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/extractor/MetricAggExtractor.java [hunk 2]
```diff
@@ -30,24 +32,32 @@
...
     private final String innerKey;
+    private final boolean isDateTimeBased;
+    private final ZoneId zoneId;
 
-    public MetricAggExtractor(String name, String property, String innerKey) {
+    public MetricAggExtractor(String name, String property, String innerKey, ZoneId zoneId, boolean isDateTimeBased) {
         this.name = name;
         this.property = property;
         this.innerKey = innerKey;
+        this. isDateTimeBased =isDateTimeBased;
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/extractor/MetricAggExtractor.java]: Weird spacing.

File: x-pack/plugin/sql/qa/src/main/resources/agg.sql-spec [hunk 3]
```diff
@@ -279,6 +279,8 @@ aggMinWithAlias
 SELECT gender g, MIN(emp_no) m FROM "test_emp" GROUP BY g ORDER BY gender;
 aggMinOnDateTime
 SELECT gender, MIN(birth_date) m FROM "test_emp" GROUP BY gender ORDER BY gender;
```
Comment (astefan) [inline x-pack/plugin/sql/qa/src/main/resources/agg.sql-spec]: If this test here wasn't complaining before, this means that our SQL spec test case infrastructure isn't actually comparing an actual date type of data, right? Otherwise, the test would have failed.
If so, I would like to see a test with `MIN(date_field)` in CSV spec test case infra, if possible. I have seen the unit test that compares the metric agg key with an actual date (`assertEquals(DateUtils.asDateTime((long) innerValue , zoneId), extractor.extract(bucket));`) but I believe our tests would be more complete if there would be an integration test as well (CSV-spec in this case).

**Review by astefan — COMMENTED** [review]
I know it's merged already, but left two comments.
