### PR TITLE
Fix needsScore computation in GlobalOrdCardinalityAggregator

### LINKED ISSUE #112975: Nested terms and cardinality aggregation causes scoring exception
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux 3acef6594579 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 22:39:36 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Problem Description

Under specific conditions I am hitting a runtime_exception when using some specific aggregations. Namely, a terms and cardinality aggregation inside a terms aggregation inside a nested aggregation. See the reproduction steps below.

The error is:
```
{
  "error": {
    "root_cause": [
      {
        "type": "runtime_exception",
        "reason": "score for different docid, nesting an aggregation under a children aggregation and terms aggregation with collect mode breadth_first isn't possible"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "my_index",
        "node": "i6xLcTXyT1SrJ5LhtKyUjg",
        "reason": {
          "type": "runtime_exception",
          "reason": "score for different docid, nesting an aggregation under a children aggregation and terms aggregation with collect mode breadth_first isn't possible"
        }
      }
    ],
    "caused_by": {
      "type": "runtime_exception",
      "reason": "score for different docid, nesting an aggregation under a children aggregation and terms aggregation with collect mode breadth_first isn't possible",
      "caused_by": {
        "type": "runtime_exception",
        "reason": "score for different docid, nesting an aggregation under a children aggregation and terms aggregation with collect mode breadth_first isn't possible"
      }
    }
  },
  "status": 500
}
```

### Steps to Reproduce

```http
PUT http://localhost:9200/my_index
Content-Type: application/json

{
    "mappings": {
        "properties": {
            "tags": {
                "type": "nested",
                "properties": {
                    "key": {
                        "type": "keyword"
                    },
                    "value": {
                        "type": "keyword"
                    }
                }
            }
        }
    }
}

### create doc
POST http://localhost:9200/my_index/_doc
Content-Type: application/json

{
    "tags": [
        {
            "key": "state",
            "value": "texas"
        }
    ]
}

### create another doc
POST http://localhost:9200/my_index/_doc
Content-Type: application/json

{
    "tags": [
        {
            "key": "state",
            "value": "utah"
        }
    ]
}

### create third doc
POST http://localhost:9200/my_index/_doc
Content-Type: application/json

{
    "tags": [
        {
            "key": "state",
            "value": "texas"
        }
    ]
}

### query (which produces an error)
POST http://localhost:9200/my_index/_search
Content-Type: application/json

{
    "aggregations": {
        "tags": {
            "nested": {
                "path": "tags"
            },
            "aggregations": {
                "keys": {
                    "terms": {
                        "field": "tags.key",
                        "execution_hint": "map"
                    },
                    "aggregations": {
                        "values": {
                            "terms": {
                                "field": "tags.value"
                            }
                        },
                        "value_count": {
                            "cardinality": {
                                "field": "tags.value"
                            }
                        }
                    }
                }
            }
        }
    },
    "size": 0
}


### delete index
DELETE http://localhost:9200/my_index
```

I can work around this by adding `execution_hint: direct` to the `cardinality` aggregation, but from reading the code this appears to be a bug since the MultiBucketCollector is defaulting to ScoreMode.COMPLETE even though the sub-aggregations do not need any scoring ([here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/aggregations/MultiBucketCollector.java#L144)).

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by iverase**
When adding dynamic pruning for GlobalOrdCardinalityAggregator, it was introduced a bug on how we compute needsScore as it does not take into account if the cardinality has parent, so in that cases it might return the wrong answer. This commit fixes that.

fixes https://github.com/elastic/elasticsearch/issues/112975

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/GlobalOrdCardinalityAggregator.java [hunk 1]
```diff
@@ -93,7 +93,10 @@ public GlobalOrdCardinalityAggregator(
 
     @Override
     public ScoreMode scoreMode() {
-        if (field != null && valuesSource.needsScores() == false && maxOrd <= MAX_FIELD_CARDINALITY_FOR_DYNAMIC_PRUNING) {
+        if (this.parent == null
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/GlobalOrdCardinalityAggregator.java:96]: Ok. I understand this now. It took some reading.

The problem is that we were claiming to only need `TOP_DOCS` in this branch because we thought we were going to take the dynamic pruning approach. But we *can't* take that approach because we have a parent. And if we're not taking that approach we have to be `COMPLETE` or `COMPLETE_NO_SCORES`. And being wrong here doesn't matter a lot of the time - but in `nested`, it does.

**Review by nik9000 — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/GlobalOrdCardinalityAggregator.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/GlobalOrdCardinalityAggregator.java:96]: For the sake of the next reader, can you leave a comment saying that this has to line up with the dynamic pruning branch?

Comment (iverase) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/GlobalOrdCardinalityAggregator.java:98]: Perfect explanation. Added.
