### PR TITLE
Fix serialization bug in painless execute api request

### LINKED ISSUE #36050: Scripting: Execute Painless API fails when communicating across nodes
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Start two elasticsearch, one named `first`, one named `second`. The `first` one should be the where you connect kibana to, to make sure this works (just start it as the first one, so it will bind to port 9200)

```
 ./elasticsearch-6.5.1/bin/elasticsearch -Enode.name=first
 ./elasticsearch-6.5.1/bin/elasticsearch -Enode.name=second
```

Open Kibana, run this in console

```
DELETE my-index

PUT /my-index
{
  "settings": {
    "index.routing.allocation.include._name": "first",
    "index.number_of_shards": 1,
    "index.number_of_replicas": 0
  },
  "mappings": {
    "_doc": {
      "properties": {
        "field": {
          "type": "keyword"
        }
      }
    }
  }
}

# all shards assigned on first node
GET _cat/shards/my-index

# this works
POST /_scripts/painless/_execute
{
  "script": {
    "source": "doc['field'].value.length() <= params.max_length",
    "params": {
      "max_length": 4
    }
  },
  "context": "filter",
  "context_setup": {
    "index": "my-index",
    "document": {
      "field": "four"
    }
  }
}

# move index to second node
PUT /my-index/_settings
{
  "settings": {
    "index.routing.allocation.include._name": "second"
  }
}

# all shards assigned on second node
GET _cat/shards/my-index

# NPE baby!
POST /_scripts/painless/_execute
{
  "script": {
    "source": "doc['field'].value.length() <= params.max_length",
    "params": {
      "max_length": 4
    }
  },
  "context": "filter",
  "context_setup": {
    "index": "my-index",
    "document": {
      "field": "four"
    }
  }
}
```

The NPE is the following

```
[2018-11-29T14:00:49,023][WARN ][r.suppressed             ] [first] path: /_scripts/painless/_execute, params: {pretty=}
org.elasticsearch.transport.RemoteTransportException: [second][127.0.0.1:9301][cluster:admin/scripts/painless/execute[s]]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.elasticsearch.index.mapper.SourceToParse.<init>(SourceToParse.java:56) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.mapper.SourceToParse.source(SourceToParse.java:32) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.prepareRamIndex(PainlessExecuteAction.java:597) ~[?:?]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.innerShardOperation(PainlessExecuteAction.java:547) ~[?:?]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.shardOperation(PainlessExecuteAction.java:536) ~[?:?]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.shardOperation(PainlessExecuteAction.java:475) ~[?:?]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:112) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.5.1.jar:6.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

### PR DESCRIPTION
**Pull request by martijnvg**
The `xContentType` was incorrectly serialized:
`xContentType.mediaTypeWithoutParameters()` was used to serialize, but
`xContentType.mediaType()` was used to de-serialize.

Also the serialization test class did not test `ContextSetup` well,
this was due to limitation in serialization test base class. Changed the
test class to manually test xcontent serialization, so that for both binary
and xcontent serialization tests, the `ContextSetup` is properly tested.

Closes #36050

### CODE REVIEW

File: modules/lang-painless/src/main/java/org/elasticsearch/painless/PainlessExecuteAction.java [hunk 1]
```diff
@@ -218,19 +218,20 @@ public boolean equals(Object o) {
...
-                return Objects.hash(index, document, query);
+                return Objects.hash(index, document, query, xContentType);
             }
 
             @Override
             public void writeTo(StreamOutput out) throws IOException {
                 out.writeOptionalString(index);
                 out.writeOptionalBytesReference(document);
-                out.writeOptionalString(xContentType != null ? xContentType.mediaType(): null);
+                out.writeOptionalString(xContentType != null ? xContentType.mediaTypeWithoutParameters(): null);
```
Comment (martijnvg) [inline modules/lang-painless/src/main/java/org/elasticsearch/painless/PainlessExecuteAction.java]: This line fixes the bug reported in #36050. The rest of this change is to improve the painless execute api request serialization.

**Review by rjernst — APPROVED** [review]
LGTM

File: modules/lang-painless/src/main/java/org/elasticsearch/painless/PainlessExecuteAction.java [hunk 2]
```diff
@@ -347,11 +348,13 @@ public void writeTo(StreamOutput out) throws IOException {
         // For testing only:
         @Override
         public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
+            builder.startObject();
```
Comment (codebrain) [inline modules/lang-painless/src/main/java/org/elasticsearch/painless/PainlessExecuteAction.java]: Hi @martijnvg - I am checking if this structural change impacts any of the public-facing REST API endpoints and therefore if the .NET client needs changing. I see this method is marked as `// For testing only` - but I wanted to double check with yourself first.

Thanks!

Comment (codebrain) [reply modules/lang-painless/src/main/java/org/elasticsearch/painless/PainlessExecuteAction.java]: Does not affect client response format, this is used for testing only.
