### PR TITLE
Do not set data paths on no local storage required

### LINKED ISSUE #27572: Security policy always uses 'path.data' even when node.data:false
I have a client node installed via apt-get install and configured as such:

```
node.master: false
node.data: false
node.ingest: false
```

When I try to run it (`sudo service elasticsearch start`) I'm getting the following exception in the logs:

```
[2017-11-28T19:36:06,220][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: Unable to access 'path.data' (/usr/share/elasticsearch/data)
        at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:287) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:242) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.configure(Security.java:120) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.0.0.jar:6.0.0]
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_151]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:401) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.0.0.jar:6.0.0]
        ... 12 more
[2017-11-28T19:36:06,247][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [my-cluster-client000000] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.data' (/usr/share/elasticsearch/data)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:134) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.0.0.jar:6.0.0]
Caused by: java.lang.IllegalStateException: Unable to access 'path.data' (/usr/share/elasticsearch/data)
        at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:287) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:242) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.configure(Security.java:120) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.0.jar:6.0.0]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_151]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_151]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:401) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:287) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:242) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Security.configure(Security.java:120) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.0.jar:6.0.0]
        ... 6 more
```

Why is `path.data` being used? and why hasn't the installer handle permissions for this folder (`/usr/share/elasticsearch` is set as root:root)?

Easily reproducible using https://github.com/synhershko/elasticsearch-cloud-deploy/tree/es6 (I hit this with Azure but shouldn't matter). Note the installation scripts in ./packer and the userdata script in ./templates

### PR DESCRIPTION
**Pull request by jasontedor**
Today when configuring the data paths for the environment, we set data paths to either the specified path.data or default to data relative to the Elasticsearch home. Yet if node.local_storage is false, data paths do not even make sense. In this case, we should reject if path.data is set, and instead of defaulting data paths to data relative to home, we should set this to empty paths. This commit does this.

Closes #27572

### CODE REVIEW

**Comment by jasontedor** [comment]
@bleskes Since this relates to node local storage, can I ask that you review this as well?

**Review by bleskes — APPROVED** [review]
LGTM. Good catch.

File: core/src/main/java/org/elasticsearch/env/Environment.java [hunk 1]
```diff
@@ -103,30 +107,39 @@ public Environment(final Settings settings, final Path configPath) {
...
+                dataWithClusterFiles = new Path[]{homeFile.resolve("data").resolve(clusterName.value())};
             }
         } else {
-            dataFiles = new Path[]{homeFile.resolve("data")};
-            dataWithClusterFiles = new Path[]{homeFile.resolve("data").resolve(clusterName.value())};
+            if (dataPaths.isEmpty()) {
+                dataFiles = dataWithClusterFiles = EMPTY_PATH_ARRAY;
+            } else {
+                final String paths = String.join(",", dataPaths);
+                throw new IllegalStateException("node does not require local storage yet path.data is set to [" + paths + "]");
```
Comment (synhershko) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: this seems to aggressive no? if no local storage is required maybe it's just better to ignore paths altogether. In scripted deployments this could be kind of a frustrating gotcha in my experience. Maybe it's better to just keep or if it affects methods downstream maybe just set to empty and log a warning instead?

**Comment by synhershko** [comment]
Thanks @jasontedor for this! left a minor comment about the behavior of when path.data is set but not really required, both approaches seem fine by me though.

File: core/src/main/java/org/elasticsearch/env/Environment.java (hunk 1 above)
Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/env/Environment.java]: We simply abhor allowing this kind of confusion. If a user is setting `path.data` and `node.local_storage` to false then there is a disconnect because one setting is saying store data here and the other is saying do not store data. Rather, we it to be clear: no local storage is required, so where to store data should not be set.

Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/env/Environment.java]: > In scripted deployments this could be kind of a frustrating gotcha in my experience. 

I don't understand this comment? In a scripted environment a user would already be scripting to set `node.local_storage` to `false` (it's not the default) so why wouldn't they also script to ensure `path.data` is not set if that's what we are going to require. Fix the script once and then it's good?

Comment (synhershko) [reply core/src/main/java/org/elasticsearch/env/Environment.java]: Isn't `node.local_storage` required / beneficial on client-only nodes for maintaining cluster state?

Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/env/Environment.java]: Yes, but that does not negate either of my points.
