### PR TITLE
Fields API to allow fetching values when _source is disabled

### LINKED ISSUE #87072: Runtime fields and _source disabled
### Elasticsearch Version

8.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Ubuntu 20.04.4 LTS

### Problem Description

Currently when using runtime fields it is not possible to search using `fields` when the index has `_source` disabled.

It will fail with `Unable to retrieve the requested [fields] since _source is disabled in the mappings for index [example-disabled]` even if `_source` isn't being used in a runtime field. Steps below.

Ideally this would fail only if the runtime field referenced `_source` fields.

Usecase is that certain logging platforms configure Elasticsearch indices with `_source` disabled (even though this is not recommended) and `store: true` for fields. Having more flexibility in using runtime fields in this instance would make migrations easier.

### Steps to Reproduce

Create indices with `_source` enabled or disabled.

```
PUT example-enabled
{
  "mappings": {
    "_source": {
      "enabled": true
    }, 
    "runtime": {
      "age": {
        "type": "long",
        "script": {
          "source": "emit(1)"
        }
      }
    }
  }
}

PUT example-disabled
{
  "mappings": {
    "_source": {
      "enabled": false
    }, 
    "runtime": {
      "age": {
        "type": "long",
        "script": {
          "source": "emit(1)"
        }
      }
    }
  }
}

PUT example-disabled/_doc/1
{}

PUT example-enabled/_doc/1
{}
```

Search over both indices:

```
GET example-*/_search
{
  "fields": [
    "age"
  ]
}
```

Response

```
{
  "took" : 459,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 1,
    "failures" : [
      {
        "shard" : 0,
        "index" : "example-disabled",
        "node" : "fNuQNb81QsC6Yb0jAnUATw",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "Unable to retrieve the requested [fields] since _source is disabled in the mappings for index [example-disabled]"
        }
      }
    ]
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "example-enabled",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : { },
        "fields" : {
          "age" : [
            1
          ]
        }
      }
    ]
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by javanna**
Back when we introduced the fields parameter to the search API, it could only fetch values from _source, hence
the corresponding sub-fetch phase fails early whenever _source is disabled. Today though runtime fields can
be retrieved from a separate value fetcher that reads from fielddata, and metadata fields can be retrieved
from stored fields. These two scenarios currently throw an unnecessary error whenever _source is disabled.

This commit removes the check for disabled _source, so that runtime fields and metadata fields can be retrieved even when _source is disabled. Fields that need to be loaded from _source are simply skipped whenever _source is disabled, similar to when a field is not found in _source.

Closes #87072

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM.  Feels a lot like the work I started on in #85348 and #85185 but that stalled out. I'm happy to see this in though.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhase.java [hunk 1]
```diff
@@ -31,15 +32,6 @@ public FetchSubPhaseProcessor getProcessor(FetchContext fetchContext) {
...
 
-        if (fetchContext.getSearchExecutionContext().isSourceEnabled() == false) {
-            throw new IllegalArgumentException(
-                "Unable to retrieve the requested [fields] since _source is disabled "
-                    + "in the mappings for index ["
-                    + fetchContext.getIndexName()
-                    + "]"
-            );
-        }
-
```
[the remark this answers is not in the document]
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhase.java:42]: Yeah, it misuses it. I'm mostly ok with it because all they really want is the doc id. But there is a lot of baggage here. A cleaner interface could be much nicer.

**Comment by javanna** [comment]
> Feels a lot like the work I started on in https://github.com/elastic/elasticsearch/pull/85348 and https://github.com/elastic/elasticsearch/pull/85185 but that stalled out. I'm happy to see this in though.

Yes, I did verify that you also had a similar fix in your PRs. It feels good that this goes in separately, and I will revive discussions on fetching from doc_values and possibly from stored fields too.

**Review by sethmlarson — APPROVED** [review]
LGTM from an API perspective

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhase.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhase.java:42]: It'd be great to clean up this interface a bit. I don't think we had concrete ideas, would be happy to discuss in a follow-up.

**Review by jtibshirani — COMMENTED** [review]
Thanks for fixing this issue!

Stepping back, I'm not sure how helpful this check is in practice. For example it doesn't cover the case where a field has been excluded from _source (but _source is not entirely disabled). Maybe it could also be annoying if you specify `"fields": "*"` (as an analogy to `"_source": true`), just wanting all fields possible, but then we fail the request?

**Comment by javanna** [comment]
> I'm not sure how helpful this check is in practice

I think I agree. It would be better to return what we can retrieve instead of failing the whole request, yet silently failing to fetch does not sound like a good idea either, or should we consider doing that?

**Comment by jtibshirani** [comment]
Right, I was suggesting that we remove the check altogether. I think it's already documented that if you don't have `_source` enabled (on non-runtime fields) then the fields will be missing from the response. I can see arguments both ways, but to me this approach feels the simplest and most flexible.

**Comment by javanna** [comment]
@jtibshirani I removed the check for _source disabled, and fixed failing tests here and there. Could you have another look please?

File: server/src/main/java/org/elasticsearch/index/mapper/ArraySourceValueFetcher.java [hunk 2]
```diff
@@ -38,7 +39,7 @@ public ArraySourceValueFetcher(String fieldName, SearchExecutionContext context)
      * @param nullValue A optional substitute value if the _source value is 'null'.
      */
     public ArraySourceValueFetcher(String fieldName, SearchExecutionContext context, Object nullValue) {
-        this.sourcePaths = context.sourcePath(fieldName);
+        this.sourcePaths = context.isSourceEnabled() ? context.sourcePath(fieldName) : Collections.emptySet();
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/ArraySourceValueFetcher.java:42]: Could you explain the motivation for these checks `context.isSourceEnabled()`? Is it a small optimization to avoid extra work?

I saw that `FieldFetcherTests#testFetchFromSourceWithSourceDisabled` can fail without this check, but it seems like the test logic just needs to be adapted to not pass a null or empty `SourceLookup`?

**Review by jtibshirani — COMMENTED** [review]
Thanks! I left one last comment.

File: server/src/main/java/org/elasticsearch/index/mapper/ArraySourceValueFetcher.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ArraySourceValueFetcher.java:42]: yes the check helps the new test work without providing a source lookup, but mostly I was annoyed that we do extra work when we can avoid it: why call sourcePath and iterate over what it returns when we already know that we have no _source?> And why even require a non-null SourceLookup in that case? Also, the way the test is currently setup, if I provide a non null _source, fields are going to be retrieved from it no matter whether source is disabled or not, because source is not retrieved from the index but rather provided manually to the fetch method.

I guess I took a shortcut to avoid having to deal with all of the above in this PR but I'd expect things to change once SearchLookup is no longer the only required argument. With this in mind this change did not feel so bad after all.

**Review by jtibshirani — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/ArraySourceValueFetcher.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ArraySourceValueFetcher.java:42]: ++ thanks I will keep this in mind
