### PR TITLE
Verify repository before cluster update

### LINKED ISSUE #107840: PUT /_snapshot/{repository} with invalid repository configuration returns an error response but still successfully changes the config
### Description

In a support case, it was possible to set invalid config (missing S3 required `settings` fields) despite the API request returning a 500 error. We should at least verify the expected request fields, and perhaps verify connection with the remote repository can be made successfully, before setting new repository config in the cluster state.

```
PUT _snapshot/found-snapshots
{
  "type": "s3",
  "settings": {
    "compress": false
  }
}
```

- response

```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_verification_exception",
        "reason": "[found-snapshots] path  is not accessible on master node"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[found-snapshots] path  is not accessible on master node",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unable to upload object [tests-kdwUK-MWR-mwL1Bhev2agA/master.dat] using a single upload",
      "caused_by": {
        "type": "sdk_client_exception",
        "reason": "Failed to connect to service endpoint: ",
        "caused_by": {
          "type": "connect_exception",
          "reason": "Connection refused"
        }
      }
    }
  },
  "status": 500
}
```
`GET _snapshot/found-snapshots` sends this response. 
```
{
  "found-snapshots": {
    "type": "s3",
    "settings": {
      "compress": "false"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by mhl-b**
This PR addresses issue when we can create "invalid" repository and persist it
in cluster state. Even thou we return error to caller, repository stays there.

Add repository verification only on master node before cluster update.
Refactored registerRepository code with SubscribableListener to display order
of listener calls. 

fixes #107840

### CODE REVIEW

**Comment by mhl-b** [comment]
Some integ tests in s3 and gcp are failing on new verification call. I assume they worked before because we updated cluster cluster first and repository was there, not verified. 

I'm looking how to fix this.

**Review by DaveCTurner — COMMENTED** [review]
Overall direction looks good but this PR is combining too many independent changes which makes it harder to review and also means that if it happens to introduce a bug then a `git bisect` won't pin down the problem very precisely.

Could we break out the test suite improvements and merge that change first, and separate out the cosmetic variable renaming in `MasterService` too? That way we'll be left with a PR that just does the behaviour change.

**Comment by ywangd** [comment]
+1 to David's suggestion. I assume this PR is meant to fix #107840? If so, can we make it clear in the description, i.e. replaces `related` with something like `fixes` so that we get GitHub to associate them?

File: server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java [hunk 1]
```diff
@@ -58,21 +62,37 @@
...
+            threadPool.shutdownNow();
+            threadPool = null;
+        }
+    }
+
+    @After
+    void stopServices() {
+        clusterService.stop();
+        repositoriesService.stop();
+    }
```
Comment (idegtiarenko) [inline server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java:90]: Please consider reusing `super.tearDown()` similarly to `setUp()`.

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 2]
```diff
@@ -2145,6 +2153,85 @@ public static <T> T safeAwait(SubscribableListener<T> listener) {
...
+    }
+
+    /**
+     * Waits for listener to complete with {@value #AWAIT_LISTENER_TIMEOUT} sec timeout.
+     * Can be used when you expect a failure of async operation.
+     *
+     * @return result of listener onFailure
+     * @throws AssertionError if listener completed successfully, or thread interrupted, or timed out
+     */
+    public static <T> Exception safeAwaitFailure(SubscribableListener<T> listener) {
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2199]: This approach introduces quite a lot of machinery for catching a failure like this, I suspect we can do the same thing by composing (mostly) existing utilities, plus the one introduced in https://github.com/elastic/elasticsearch/pull/108547.

**Comment by mhl-b** [comment]
@DaveCTurner @ywangd 

> Could we break out the test suite improvements and merge that change first

I will create separate PR for the test suite improvements, will keep this one open for behaviour change.

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java (hunk 2 above)
Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2199]: I couldnt figure out how to avoid try/catch without changing safeAwait. In safeAwait we throw all exceptions(listener and timeout) as AssertException, then I need another try/catch in safeAwaitFaliure to unwrap AssertException. It saves few lines of code, but not obviously better.

Using `assertNoFailureListener` in awaitFailure still requires try/catch from above. Do you have a suggestion how to compose existing methods?

My thinking about composition is changing `safeAwait` to return a tuple of (Response, Failure), and then have `safeAwaitResponse`/`safeAwaitFailure` related methods. Names and meaning are composed accordingly.

```java
record ListenerResult<T>(T response, Exception failure){}

public static <T> ListenerResult<T> safeAwait(SubscribableListener<T> listener) {
    try {
        final var future = new PlainActionFuture<T>();
        listener.addListener(future);
        final var response = future.get(timeout, timeUnit);
        return new ListenerResult(response, null);
    } catch (ExecutionException e) {
        return new ListenerResult(null, e.getCause());
    } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        throw new AssertionError("safeAwait: interrupted waiting for SubscribableListener", e);
    } catch (TimeoutException e) {
        throw new AssertionError("safeAwait: listener was not completed within the timeout", e);
    }
}

public static <T> T safeAwaitResponse(SubscribableListener<T> listener) {
    final var result = safeAwait(listener);
    assertNull(result.failure);
    assertNotNull(result.response);
    return result.response;
}

public static <T> T safeAwaitFailure(SubscribableListener<T> listener) {
    final var result = safeAwait(listener);
    assertNull(result.response);
    assertNotNull(result.failure);
    return result.failure;
}

```

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2199]: Or even this, more type safety, like rust enums. "Switch" statement on sealed interface enforce exhaustive check on branches at compile time.

```java
    sealed interface ListenerResult<T> permits ListenerResponse, ListenerFailure {};

    record ListenerResponse<T>(T response) implements ListenerResult<T> {}

    record ListenerFailure(Throwable failure) implements ListenerResult {}

    public static <T> ListenerResult<T> safeAwait(SubscribableListener<T> listener) {
        try {
            final var future = new PlainActionFuture<T>();
            listener.addListener(future);
            final var response = future.get(timeout, timeUnit);
            return new ListenerResponse<>(response);
        } catch (ExecutionException e) {
            return new ListenerFailure(e.getCause());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new AssertionError("safeAwait: interrupted waiting for SubscribableListener", e);
        } catch (TimeoutException e) {
            throw new AssertionError("safeAwait: listener was not completed within the timeout", e);
        }
    }

    public static <T> T safeAwaitResponse(SubscribableListener<T> listener) {
        final var result = safeAwait1(listener);
        switch (result) {
            case ListenerFailure listenerFailure -> {
                throw new AssertionError(listenerFailure.failure);
            }
            case ListenerResponse<T> listenerResponse -> {
                return listenerResponse.response;
            }
        }
    }

    public static <T> Throwable safeAwaitFailure(SubscribableListener<T> listener) {
        final var result = safeAwait1(listener);
        switch (result) {
            case ListenerFailure listenerFailure -> {
                return listenerFailure.failure;
            }
            case ListenerResponse<T> listenerResponse -> {
                throw new AssertionError("must fail");
            }
        }
    }

```

Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2199]: This all still seems rather overcomplicated, I think we can write the test something like this:

```
    public void testRegisterThrowsVerificationFailureBeforeClusterUpdate() {
        final var req = new PutRepositoryRequest("verify-fail-repo");
        req.type(VerifyFailRepository.TYPE);
        final var exception = safeAwait(
            SubscribableListener.<Exception>newForked(
                l -> repositoriesService.registerRepository(req, ActionTestUtils.assertNoSuccessListener(l::onResponse))
            )
        );
        assertThat(exception, isA(RepositoryVerificationException.class));
        assertEquals(0, repositoriesService.getRepositories().size()); // assert cluster is not updated
    }
```

Maybe there's a utility to be extracted there but I don't think we need all this extra code unless I'm missing something?

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2199]: That works, probably personal preference. I would prefer shorter meaningful methods like awaitFailure/awaitResponse. It's easier to show intention of the code.

```java
        final var exception = safeAwait(
            SubscribableListener.<Exception>newForked(
                l -> repositoriesService.registerRepository(req, ActionTestUtils.assertNoSuccessListener(l::onResponse))
            )
        );
```

I would prefer less callback-y. My body is still adjusting to callbacks, there are changes on molecular level :D

```java
final var listener = new SubscribableListener<AcknowledgedResponse>();
repositoriesService.registerRepository(req, listener);
final var failure = safeAwaitFailure(listener);
assertThat(exception, isA(RepositoryVerificationException.class));
```

File: server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java [hunk 3]
```diff
@@ -170,26 +170,54 @@ public void registerRepository(final PutRepositoryRequest request, final ActionL
...
+            doVerifyStep.addListener(new ActionListener<>() {
+                @Override
+                public void onResponse(List<DiscoveryNode> ignored) {
+                    verifiedStep.onResponse(true);
+                }
+
+                @Override
+                public void onFailure(Exception verificationException) {
+                    final var unregisterRequest = new DeleteRepositoryRequest().name(request.name());
+                    unregisterRepository(unregisterRequest, new ActionListener<>() {
```
Comment (mhl-b) [inline server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:202]: not every validation should unregister repository, I see random tests fail, looking into that

**Comment by mhl-b** [comment]
@DaveCTurner @idegtiarenko 
After try and err with enhancing validation I decided to change approach. I updated PR description and code. WDYT.

**Review by DaveCTurner — DISMISSED** [review]
I don't think this works unfortunately, at least not reliably enough. The `unregisterRepository` step may fail if, for instance, there's a master failover in the meantime, or something starts a snapshot operation in between the register and unregister steps. We need to do at least some kind of verification before adding the repo metadata to the cluster state.

**Comment by ywangd** [comment]
In addition to @DaveCTurner's comment, I think this approach also means we will delete an existing repository if the update request has some invalid settings in it. Feels like a pretty big risk to do so.

**Comment by DaveCTurner** [comment]
oof yeah that too!

**Comment by mhl-b** [comment]
Alright, back to verification :)

**Comment by mhl-b** [comment]
@DaveCTurner @ywangd 
updated PR, using pre-publish verification now, found and fixed complaining tests

File: server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java [hunk 4]
```diff
@@ -144,111 +145,114 @@ public RepositoriesService(
...
-        final ListenableFuture<Boolean> publicationStep = new ListenableFuture<>(); // Boolean==changed.
+        // Aggregated result of two asynchronous operations when the cluster acknowledged and state changed
+        record RegisterRepositoryTaskResult(AcknowledgedResponse ackResponse, boolean changed) {}
+
+        SubscribableListener
 
-        if (request.verify()) {
+            .<Void>newForked(validationStep -> {
+                if (request.verify()) {
+                    validatePutRepositoryRequest(request, validationStep);
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:173]: Can we have this done together with `validateRepositoryCanBeCreated`? I think it feels nature that pre-cluster-state-update validation/verification is done in one place. Also seems to be wasteful to create the repository twice. 

While I appreciate that `SubscribableListener` generally makes code easier to read, can we keep it separate from this PR? If we move this step into `validateRepositoryCanBeCreated`, I think we don't need to touch the code here at all in this PR which would make it much easier to review. We can always have a follow-up which will be pure-refactoring for introucing `SubscribableListener`.

**Review by ywangd — COMMENTED** [review]
I left a comment. Thanks!

File: server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java (hunk 4 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:173]: `validateRepositoryCanBeCreated` method is used in other places, I would rather remove it from here. But it breaks unrelated tests. I can try to chase these down in this PR, or following PR.

About SubscribableListener, I found without little refactor it looks worse. May be diff will be a bit prettier, but final code not. I can do "ugly" change and then refactor in another PR if its a preferable way.

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:173]: > About SubscribableListener, I found without little refactor it looks worse. May be diff will be a bit prettier, but final code not. I can do "ugly" change and then refactor in another PR if its a preferable way.

I think it is better to keep functional change and style change separate unless it is very trivial. If somehow we need to revert the functional change, it is also much cleaner if they are separate. This likely won't happen for this PR. But it feels like a overall good principle. 

> validateRepositoryCanBeCreated method is used in other places

In that case, we don't have to literally move the new code into it. It can sit besides it as a new method. My main point is to _not_ touch the below steps of listeners in this PR.

Let's hear what @DaveCTurner has to say about this before changing anything. Thanks!

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:173]: Btw, the `SubscribableListener` change does _not_ have to come _after_ this PR. It would be total reasonable to have a separate PR just for that and merge it before proceeding here. My main point is to have them separate, order is not important.

Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:173]: You are absolutely right about splitting it apart, I talked with David before about it, but got tunnel-visioned chasing down test failures and forgot about it. I rethink what I said before, and I believe all of it can be addressed.

I created PR with non functional change - #108788

I have some thoughts how to organize `validateRepositoryCanBeCreated` better, will update this PR after refactoring merged.

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:173]: Awesome. That was my main gripe :) Thanks for splitting it out. 👍

Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java]: updated PR with refactoring included

File: server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java [hunk 5]
```diff
@@ -353,6 +350,35 @@ public void validateRepositoryCanBeCreated(final PutRepositoryRequest request) {
...
+                            repository.verify(token, clusterService.localNode());
+                            repository.endVerification(token);
+                        }
+                        resultListener.onResponse(null);
+                    } catch (Exception e) {
+                        resultListener.onFailure(e);
+                    } finally {
+                        closeRepository(repository);
+                    }
+                });
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:372]: It's generally best to avoid submitting a bare `Runnable` to threadpool executors, because they don't handle rejection very well. In this particular case it'd be ok since (a) `SNAPSHOT` doesn't reject anything (today) and (b) the whole thing is in a try/catch block anyway, but still these things are easy to miss in future changes in this area. `AbstractRunnable` is always a better choice:

```suggestion
                threadPool.executor(ThreadPool.Names.SNAPSHOT)
                    .execute(ActionRunnable.run(ActionListener.runBefore(resultListener, () -> closeRepository(repository)), () -> {
                        final var token = repository.startVerification();
                        if (token != null) {
                            repository.verify(token, clusterService.localNode());
                            repository.endVerification(token);
                        }
                    }));
```

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 6]
```diff
@@ -2178,6 +2179,12 @@ public static <T> T safeGet(Future<T> future) {
         }
     }
 
+    public static <T> Exception safeAwaitFailure(SubscribableListener<T> listener) {
+        return safeAwait(SubscribableListener.newForked(exceptionListener -> {
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2183]: Nit: unnecessary `{...}`, can just be an expression lambda

```suggestion
        return safeAwait(SubscribableListener.newForked(exceptionListener -> 
```

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 7]
```diff
@@ -2178,6 +2179,12 @@ public static <T> T safeGet(Future<T> future) {
         }
     }
 
+    public static <T> Exception safeAwaitFailure(SubscribableListener<T> listener) {
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2182]: Since we don't use the generic type param `T` anywhere we can just use a wildcard instead:

```suggestion
    public static Exception safeAwaitFailure(SubscribableListener<?> listener) {
```

**Review by DaveCTurner — COMMENTED** [review]
Looks good to go except a couple of superficial points, see below.

File: server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java (hunk 5 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java:372]: neat

File: server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java [hunk 8]
```diff
@@ -181,6 +173,26 @@ public void testRegisterRejectsInvalidRepositoryNames() {
         }
     }
 
+    public void testPutRepositoryVerificationFails() {
```
Comment (ywangd) [inline server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java:176]: Is it possible to also have a test that starts with an existing repository and demostrate a failed update (due to verfication) request does not change the existing repo?

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java [hunk 9]
```diff
@@ -91,8 +91,13 @@ protected Settings repositorySettings(String repoName) {
...
     }
 
+    /**
+     * Create a repository without verification, assuming the repository is perfectly valid.
+     * If the repository can be invalid, use another method
+     * {@link ESBlobStoreRepositoryIntegTestCase#createRepository(String repoName, boolean verify)}
+     */
     protected final String createRepository(final String name) {
-        return createRepository(name, true);
+        return createRepository(name, false);
```
Comment (ywangd) [inline test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java:100]: Why is this change necessary? Is it because we will reject invalid repo earlier with this change and we still want some invalid repo to be created in tests? Sounds like an exceptional use case. Are there many such usages? If not, I feel it might be better for clarity to have a separate method such as `createRepositoryWithoutVerification` for them. The following method `String createRepository(final String name, final boolean verify)` is only used here and probably can be dropped.

File: server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java (hunk 5 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java]: The try-catch block may not be necessary since we are calling this method in a `SubscribableListener#newForked` which does its own try-catch. That said, I am not too fussed with the additional try-catch. It helps reasoning when just reading this single method.

File: server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java (hunk 8 above)
Comment (mhl-b) [reply server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java:176]: yeah, sure

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java (hunk 9 above)
Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java:100]: There are several tests that dont rely on verification, repository creation is a part of the setup but no assertions done. In some tests we create a snapshot thread pool with single thread, new verification code also uses snapshot thread and it causes test to hang. My understanding it happens when we intentionally block some repository calls though mocks. At least thats what I was able to reproduce with debugger.

Also not all tests I was able to catch locally, some of them fail only on CI. Even not on my GCP instance.

I can try to refactor with `createRepositoryWithoutVerification` for clarity.

Comment (ywangd) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java:100]: > In some tests we create a snapshot thread pool with single thread, new verification code also uses snapshot thread and it causes test to hang. 

The existing code also performs verification in the snapshot thread pool after the repo is added to the cluster state. So it is not immediately clear to me why the new verficiation step would hang?

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java:100]: Let me reproduce these and post details here.

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java]: I might mess up a bit here, this change is not related to hanging tests. 

Another diff in this PR addresses hanging test:
`RepositoriesIT -> testRepositoryConflict`
```java

        blockMasterOnWriteIndexFile(repo);
        logger.info("--> start deletion of snapshot");
        ActionFuture<AcknowledgedResponse> future = clusterAdmin().prepareDeleteSnapshot(repo, snapshot1).execute();
        logger.info("--> waiting for block to kick in on node [{}]", blockedNode);
        waitForBlock(blockedNode, repo);

        ...

        logger.info("--> try updating the repository, should fail because the deletion of the snapshot is in progress");
        RepositoryConflictException e2 = expectThrows(
            RepositoryConflictException.class,
            clusterAdmin().preparePutRepository(repo)
                .setVerify(true) // >>> will hang on verification
                .setType("mock")
                .setSettings(Settings.builder().put("location", randomRepoPath()))
        );

        ...

        logger.info("--> unblocking blocked node [{}]", blockedNode);
        unblockNode(repo, blockedNode); // >>> release thread here
```

So here we use thread pool with single thread that is busy with snapshot deletion, then we issue another call to repository service and it hangs on verification. Test unblocks node after.

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESBlobStoreRepositoryIntegTestCase.java]: This change related to metrics. We have tests that verify we have exact Repository metrics - get/put/list across nodes. But with new change master node will have few more, and there are several tests fail. Not consistently thou.

https://gradle-enterprise.elastic.co/s/w4amqdgguyipy

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/RepositoriesIT.java [hunk 10]
```diff
@@ -302,7 +302,10 @@ public void testRepositoryConflict() throws Exception {
         logger.info("--> try updating the repository, should fail because the deletion of the snapshot is in progress");
         RepositoryConflictException e2 = expectThrows(
             RepositoryConflictException.class,
-            clusterAdmin().preparePutRepository(repo).setType("mock").setSettings(Settings.builder().put("location", randomRepoPath()))
+            clusterAdmin().preparePutRepository(repo)
+                .setVerify(false)
```
Comment (mhl-b) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/RepositoriesIT.java:306]: will deadlock on snapshot thread pool, we are running with single thread which is busy at the moment

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java [hunk 11]
```diff
@@ -181,7 +181,7 @@ public final void testSnapshotWithLargeSegmentFiles() throws Exception {
     }
 
     public void testRequestStats() throws Exception {
-        final String repository = createRepository(randomRepositoryName());
+        final String repository = createRepository(randomRepositoryName(), false);
```
Comment (mhl-b) [inline test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java:184]: Additional verification adds few more invocations on master node, failing all related tests in s3/gcp/azure.
Here test asserts that we have exact metrics across all nodes.

File: server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java (hunk 8 above)
Comment (mhl-b) [reply server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java:176]: added new test `testPutRepositoryVerificationFailsOnExisting`

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/RepositoriesIT.java (hunk 10 above)
Comment (ywangd) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/RepositoriesIT.java:306]: Can we have this comment in the code please?

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 12]
```diff
@@ -2178,6 +2179,14 @@ public static <T> T safeGet(Future<T> future) {
         }
     }
 
+    public static Exception safeAwaitFailure(SubscribableListener<?> listener) {
```
Comment (ywangd) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:2182]: Nit: I think we can have a variant of this method that takes `PlainActionFuture` in a future PR.

**Review by ywangd — APPROVED** [review]
LGTM 

Thanks for the iterations. I suggest we add comments into places where we explicity set `verify` to `false` for repository creation so it is easier for future readers to see why.
