### PR TITLE
[Transform] Cleanup and simplify reading transform settings

### LINKED ISSUE #106008: [Transform] Code related to reading settings is hard to understand
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

There is `SettingsConfig` class which is responsible for reading/writing transform settings.
Throughout the code, the settings are accessed using `SettingsConfig` class' accessor methods and the defaults are applied at the point of usage.
We should remove the code duplication and apply defaults in one place. Also, looking at the accessor method calls it should be easy to understand if the particular settings is enabled or disabled.

### Steps to Reproduce

This is a refactoring issue.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR makes a refactoring in the way transform settings are fetched.
It introduces `TransformEffectiveSettings` class which applies the default, making it easier to consume settings in the rest of the codebase.

Additionally, this PR:
- replaces usage of default constructor `new SettingsConfig()` with a static field `SettingsConfig.EMPTY`
- makes most of the accessors in the `SettingsConfig` class `private` or `package-private`

Fixes https://github.com/elastic/elasticsearch/issues/106008

### CODE REVIEW

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java [hunk 1]
```diff
@@ -309,7 +310,7 @@ public void testDisablePit() throws InterruptedException {
         }
         TransformConfig config = configBuilder.build();
 
-        boolean pitEnabled = config.getSettings().getUsePit() == null || config.getSettings().getUsePit();
+        boolean pitEnabled = TransformEffectiveSettings.isPitDisabled(config.getSettings()) == false;
```
Comment (prwhelan) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java:313]: Did we want both a `TransformEffectiveSettings.isPitDisabled` and `TransformEffectiveSettings.isPitEnabled` so that we don't have to do the `== false` outside of the `TransformEffectiveSettings`?

**Review by prwhelan — APPROVED** [review]

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexerTests.java:313]: I had this idea too but I dropped it because this test case is the **only** place which uses negation.
All the production code always checks if the PIT is **disabled**.
