### PR TITLE
Increment Request Before Serializing it in OutboundHandler

### LINKED ISSUE #74253: [CI] CreateIndexIT trips assertion in ReleasableBytesReference
This caused the test to timeout but I'm not sure it's specific to CreateIndexIT itself, it seems that there may be a missing incRef() somewhere in recovery?

**Build scan:**
https://gradle-enterprise.elastic.co/s/tt2vkhr34d3oe/tests/:server:internalClusterTest/org.elasticsearch.action.admin.indices.create.CreateIndexIT/classMethod

**Reproduction line:**
`null`

**Applicable branches:**
7.13

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.indices.create.CreateIndexIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).

  at __randomizedtesting.SeedInfo.seed([1DB9635AB22FB757]:0)

```

### PR DESCRIPTION
**Pull request by original-brownbear**
If there are outside ways by which a request can be decremented (e.g.
due to cancelling a recovery concurrently) we may run into a situation where
we try to send a `refcount == 0` request. We have to avoid this by incrementing
a request before serializing and decrementing after it returns to make sure we
don't corrupt the request bytes while they're being serialized
or sent over the wire.

Closes #74253

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/transport/OutboundHandler.java [hunk 1]
```diff
@@ -68,8 +68,14 @@ void sendRequest(final DiscoveryNode node, final TcpChannel channel, final long
         Version version = Version.min(this.version, channelVersion);
         OutboundMessage.Request message =
             new OutboundMessage.Request(threadPool.getThreadContext(), request, version, action, requestId, isHandshake, compressRequest);
-        ActionListener<Void> listener = ActionListener.wrap(() ->
-            messageListener.onRequestSent(node, requestId, action, request, options));
+        request.incRef();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/transport/OutboundHandler.java:71]: Hmm, I think this bug is really in the recovery code tho, we're completing the overall listener before all the messages have gone, which is kinda lazy. It's ok in this specific case because we don't hold any other resources, but in general I worry that this change might hide different use-after-release bugs.

If this call to `incRef()` fails then IMO the caller is at fault, we should fail tests that hit this. Obtaining another ref to be safe here (and throwing an `AlreadyClosedException` if not) seems like a good backup protection in production tho, but I think we should actually be deliberately lazy in the recovery code so we don't obscure any other use-after-release bugs:

```diff
diff --git a/server/src/main/java/org/elasticsearch/indices/recovery/RemoteRecoveryTargetHandler.java b/server/src/main/java/org/elasticsearch/indices/recovery/RemoteRecoveryTargetHandler.java
index db3147c52c2..a1f89da448a 100644
--- a/server/src/main/java/org/elasticsearch/indices/recovery/RemoteRecoveryTargetHandler.java
+++ b/server/src/main/java/org/elasticsearch/indices/recovery/RemoteRecoveryTargetHandler.java
@@ -10,6 +10,7 @@ package org.elasticsearch.indices.recovery;

 import org.apache.logging.log4j.LogManager;
 import org.apache.logging.log4j.Logger;
+import org.apache.lucene.store.AlreadyClosedException;
 import org.apache.lucene.store.RateLimiter;
 import org.elasticsearch.ElasticsearchException;
 import org.elasticsearch.ExceptionsHelper;
@@ -243,8 +244,19 @@ public class RemoteRecoveryTargetHandler implements RecoveryTargetHandler {

             @Override
             public void tryAction(ActionListener<T> listener) {
-                transportService.sendRequest(targetNode, action, request, options,
-                    new ActionListenerResponseHandler<>(listener, reader, ThreadPool.Names.GENERIC));
+                if (request.tryIncRef()) {
+                    transportService.sendRequest(
+                        targetNode,
+                        action,
+                        request,
+                        options,
+                        new ActionListenerResponseHandler<>(
+                            ActionListener.runBefore(listener, request::decRef),
+                            reader,
+                            ThreadPool.Names.GENERIC));
+                } else {
+                    listener.onFailure(new AlreadyClosedException("already closed"));
+                }
             }

             @Override
```

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/OutboundHandler.java]: ++ this makes sense, adjusted the recovery code with the above and made the network side trip an assertion if the request has been released already now.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/OutboundHandler.java]: ah no this won't unfortunately, retries will break with this change. Hold off here, I'll see what I can do about this

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/OutboundHandler.java]: nevermind urgh https://github.com/elastic/elasticsearch/pull/74256/commits/9c51a0c2260fb7a34fbf4851d623a02d0718658d ...  :)

File: server/src/main/java/org/elasticsearch/transport/BytesTransportRequest.java [hunk 2]
```diff
@@ -67,7 +67,7 @@ public void incRef() {
 
     @Override
     public boolean tryIncRef() {
-        return bytes.decRef();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/transport/BytesTransportRequest.java:70]: wut?!

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!
