### PR TITLE
SQL: Fix serialization of JDBC prep statement date/time params

### LINKED ISSUE #56084: SQL: JDBC error when setting date related query params
```
@Test
public void testEsJdbcPreparedStatetement() {
    try (Connection connection = DriverManager.getConnection("jdbc:es://localhost:9200/", "elastic", "elastic")) {

        try(PreparedStatement preparedStatement = connection.prepareStatement("SELECT emp_no FROM test_emp WHERE birth_date = ?")) {

            java.sql.Date ts = new java.sql.Date(1510348539123L);
            preparedStatement.setObject(1, ts);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    System.out.println(resultSet.getInt(1));
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
```

results in:
```
java.lang.IllegalArgumentException: cannot write time value xcontent for unknown value of type class java.util.Date

	at org.elasticsearch.common.xcontent.XContentBuilder.timeValue(XContentBuilder.java:751)
	at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:815)
	at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:804)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:789)
	at org.elasticsearch.xpack.sql.proto.SqlTypedParamValue.toXContent(SqlTypedParamValue.java:50)
	at org.elasticsearch.xpack.sql.proto.SqlQueryRequest.toXContent(SqlQueryRequest.java:186)
	at org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:148)
	at org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:101)
	at org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:81)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:69)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:60)
	at PostgresJdbcTest.testEsJdbcPreparedStatetement(PostgresJdbcTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1011)
		at org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:144)
		... 28 more
	Caused by: java.io.IOException: Unclosed object or array found
		at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:469)
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1009)
		... 29 more
```

### PR DESCRIPTION
**Pull request by matriv**
The Date/Time related query params of a JDBC prepared statement
serialized using java.util.Date. The rules for serializing
`java.util.Date` objects though reside in
`XContentElasticsearchExtension` which is not available in the
jdbc jar as this class is in `server` module. Therefore, a
custom extension of the `XContentBuilderExtension` iface has been
added to the jdbc module/jar.

Moreover the sql's `qa` project had as dependency the `sql-action`
module which depends on `server` so the `XContentBuilderExtension`
was available for the integ tests hiding the real problem.

Fixes: #56084

### CODE REVIEW

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java [hunk 1]
```diff
@@ -32,10 +47,23 @@ public void testSupportedTypes() throws Exception {
...
+        java.util.Date utilDateVal = new java.util.Date(millis);
+        LocalDateTime localDateTimeVal = LocalDateTime.ofInstant(Instant.ofEpochMilli(millis), UTC);
 
         try (Connection connection = esJdbc()) {
-            try (PreparedStatement statement = connection.prepareStatement(
-                    "SELECT ?, ?, ?, ?, ?, ?, ?, ?, ?, ?")) {
+            StringJoiner sql = new StringJoiner(",", "SELECT ", "");
+            for (int i = 0; i < 19; i++) {
+                sql.add("?");
+            }
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java:65]: 👍

File: x-pack/plugin/sql/qa/build.gradle [hunk 2]
```diff
@@ -9,7 +9,7 @@ dependencies {
   // JDBC testing dependencies
   compile project(path: xpackModule('sql:jdbc'))
 
-  compile project(path: xpackModule('sql:sql-action'))
+//  compile project(path: xpackModule('sql:sql-action'))
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/build.gradle:12]: Did you want to eventually remove this?

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java [hunk 3]
```diff
@@ -207,4 +301,28 @@ public void testSingleParameterMultipleTypes() throws Exception {
...
+    }
+
+    private static long testMillis(long randomMillis, int i) {
+        long millis = randomMillis;
+        if (i == 1) {
+            millis -= 1;
+        } else if (i == 3) {
+            millis += 1;
+        }
+        return millis;
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java:326]: Just a more concise alternative suggestion: `return randomMillis - 2 + i` (tho not perfectly equivalent).

**Review by bpintea — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/build.gradle (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/build.gradle:12]: Yep, thx!

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcPreparedStatement.java [hunk 4]
```diff
@@ -381,12 +384,9 @@ private void setObject(int parameterIndex, Object x, EsType dataType, String typ
...
                 } else if (x instanceof Date) {
                     dateToSet = new java.util.Date(((Date) x).getTime());
-                } else if (x instanceof LocalDateTime){
+                } else if (x instanceof LocalDateTime) {
                     LocalDateTime ldt = (LocalDateTime) x;
-                    Calendar cal = getDefaultCalendar();
-                    cal.set(ldt.getYear(), ldt.getMonthValue() - 1, ldt.getDayOfMonth(), ldt.getHour(), ldt.getMinute(), ldt.getSecond());
-
-                    dateToSet = cal.getTime();
+                    dateToSet = new java.util.Date(ldt.toInstant(UTC).toEpochMilli());
```
Comment (costin) [inline x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcPreparedStatement.java:389]: 👍

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/XContentSqlExtension.java [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+import org.elasticsearch.common.xcontent.XContentBuilder;
+import org.elasticsearch.common.xcontent.XContentBuilderExtension;
+
+import java.util.Collections;
+import java.util.Date;
+import java.util.Map;
+import java.util.function.Function;
+
+/**
+ * SPI extensions for Elasticsearch-specific classes (like the Lucene or Joda
```
Comment (costin) [inline x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/XContentSqlExtension.java:18]: The javadoc is out of place.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java [hunk 6]
```diff
@@ -66,13 +103,70 @@ public void testSupportedTypes() throws Exception {
...
+                    assertEquals(new Timestamp(calendarVal.getTimeInMillis()), results.getObject(17));
+                    assertEquals(timestampVal, results.getObject(18));
+                    assertEquals(timestampVal, results.getObject(19));
+                    assertFalse(results.next());
+                }
+            }
+        }
+    }
+
+    public void testDateTime() throws IOException, SQLException {
```
Comment (costin) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java:121]: Can you please break this method down into 3 different tests? This way if one of them breaks, it will be easier to identify the test that did it.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java [hunk 7]
```diff
@@ -66,13 +103,70 @@ public void testSupportedTypes() throws Exception {
...
                 }
             }
         }
     }
 
-    public void testOutOfRangeBigDecimal() throws Exception {
+    public void testOutOfRangeBigDecimal() throws SQLException {
         try (Connection connection = esJdbc()) {
             try (PreparedStatement statement = connection.prepareStatement("SELECT ?")) {
                 BigDecimal tooLarge = BigDecimal.valueOf(Double.MAX_VALUE).add(BigDecimal.ONE);
```
Comment (costin) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java:172]: The exception change for this method and the rest are noise likely introduced by IDE changes.
I'm not a fan since it implies the author does not know the type of exception used - it's more valuable to do that in a separate step instead of a regular basis.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java [hunk 8]
```diff
@@ -207,4 +301,22 @@ public void testSingleParameterMultipleTypes() throws Exception {
             return result;
         }
     }
+
+    private static long convertFromCalendarToUTC(long value, Calendar cal) {
```
Comment (costin) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/PreparedStatementTestCase.java:305]: Is this something used somewhere else that could be moved into a DateUtils/TestUtils of sorts?

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/XContentSqlExtension.java (hunk 5 above)
Comment (matriv) [reply x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/XContentSqlExtension.java:18]: Oops,  just copy paste from the original class, will fix.

**Review by astefan — APPROVED** [review]
LGTM
