### PR TITLE
Restrict the index authorization checks in PIT search

### LINKED ISSUE #99684: EQL sequence queries open PIT against indices not included in search request
### Elasticsearch Version

8.11

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux 5.3.0-64-generic

### Problem Description

EQL search requests with sequence queries open a PIT internally, but the PIT includes indices that were not part of the EQL search request. The final results are correct because the searches include a `terms` filter on the `_index` field that limits the returned results to the correct indices, however, performance suffers when there are many indices in the system. Performance is noticeably worse when some indices are on frozen nodes and get included in the PIT despite not being included in the original search request. In this case frozen node CPU usage spikes even when the EQL search request from the user does not include any frozen indices in the request.

Since the indices in the PIT are not respecting the list of indices from the search request, users have no means to tune and prevent EQL sequence searches from impacting their frozen nodes.

### Steps to Reproduce

Script to create 2 indices, then query `test_eql_sequence_pit` with an EQL sequence in a loop:
```
#!/bin/sh

ES=http://elastic:changeme@localhost:9200
ESIDX=test_eql_sequence_pit
ESIDX_UNRELATED=test_unrelated_index

curl -s -XDELETE $ES/$ESIDX >/dev/null

curl -s -XPUT $ES/$ESIDX?pretty=true -H 'Content-Type: application/json' -d '{
    "settings": {}
}'

curl -s -XPUT $ES/$ESIDX_UNRELATED?pretty=true -H 'Content-Type: application/json' -d '{
    "settings": {}
}'

curl -s -XPOST $ES/$ESIDX/_mapping?pretty=true -H 'Content-Type: application/json' -d '{
    "properties": {
        "@timestamp": {
            "type": "date"
        }
    }
}'

for i in {1..100}
do
echo "$i"
curl -s -XPOST $ES/$ESIDX/_bulk?pretty=true\&refresh=true -H 'Content-Type: application/json' -d \
'{"index": {}}
{"@timestamp": "1695149097000"}
{"index": {}}
{"@timestamp": "1695149097001"}
{"index": {}}
{"@timestamp": "1695149097002"}
{"index": {}}
{"@timestamp": "1695149097003"}
{"index": {}}
{"@timestamp": "1695149097004"}
{"index": {}}
{"@timestamp": "1695149097005"}
{"index": {}}
{"@timestamp": "1695149097006"}
{"index": {}}
{"@timestamp": "1695149097007"}
'>/dev/null
done

for (( ; ; ))
do
curl -s -XPOST $ES/$ESIDX/_eql/search -H 'Content-Type: application/json' -d \
'{
  "size": 100,
  "query":"sequence [any where true][any where true][any where true][any where true][any where true][any where true][any where true][any where true]"
}
'>/dev/null

done
```

While the first script is running, fetch active tasks with this second script:
```
#!/bin/sh

ES=http://elastic:changeme@localhost:9200
ESIDX=test_eql_sequence_pit

curl -s -XGET "$ES/_tasks?actions=*search&detailed=true"
```

Example response:
```
{
  "nodes": {
    "8MqMka6cR1KWtajIGSmW3A": {
      "name": "marshall-X570-AORUS-PRO-WIFI",
      "transport_address": "127.0.0.1:9300",
      "host": "127.0.0.1",
      "ip": "127.0.0.1:9300",
      "roles": [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "attributes": {
        "ml.machine_memory": "33683869696",
        "transform.config_version": "10.0.0",
        "xpack.installed": "true",
        "ml.config_version": "10.0.0",
        "ml.max_jvm_size": "1610612736",
        "ml.allocated_processors_double": "24.0",
        "ml.allocated_processors": "24"
      },
      "tasks": {
        "8MqMka6cR1KWtajIGSmW3A:3727": {
          "node": "8MqMka6cR1KWtajIGSmW3A",
          "id": 3727,
          "type": "transport",
          "action": "indices:data/read/search",
          "description": "indices[test_unrelated_index,test_eql_sequence_pit], search_type[QUERY_THEN_FETCH], source[{\"size\":1000,\"timeout\":\"30s\",\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"time_zone\":\"UTC\",\"format\":\"epoch_millis\",\"boost\":1.0}}},{\"term\":{\"_index\":{\"value\":\"test_eql_sequence_pit\"}}}],\"boost\":1.0}},\"_source\":false,\"fields\":[{\"field\":\"@timestamp\",\"format\":\"epoch_millis\"}],\"sort\":[{\"@timestamp\":{\"order\":\"desc\",\"missing\":\"_last\",\"unmapped_type\":\"date\"}}],\"track_total_hits\":-1,\"pit\":{\"id\":\"6-aGBAEVdGVzdF9lcWxfc2VxdWVuY2VfcGl0FnRuOU42aGVlVHdLcWc2ay0wRjZFcXcAFjhNcU1rYTZjUjFLV3RhaklHU21XM0EAAAAAAAAAAHAWYURhZ0N4MzRSckstM0NpanE2SFRDUQABFnRuOU42aGVlVHdLcWc2ay0wRjZFcXcAAA==\"}}]",
          "start_time_in_millis": 1695163108456,
          "running_time_in_nanos": 5185143,
          "cancellable": true,
          "cancelled": false,
          "parent_task_id": "8MqMka6cR1KWtajIGSmW3A:3722",
          "headers": {}
        }
      }
    }
  }
}
```
The task description shows a query going to both indices even though the EQL search request is made to `test_eql_sequence_pit` specifically with no wildcards.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jimczi**
Search requests executed against a PIT do not have to set the target indices explicitly. Instead the list of targeted index is extracted from the PIT id directly. When executed against the search rest layer, the indices of the PIT are copied in the search request in order to fullfill the authorization check when security is enabled. However, this crucial copy operation is omitted when the search request is internally executed from a node within the cluster. Consequently, the authorization check ends up evaluating the request against all indices accessible to the user. To address this performance issue, the proposed change ensures this copy occurs explicitly within the security layer. This modification restricts the authorization check to indices that are part of the PIT, mitigating the performance bug. It is essential to note that even in the presence of this bug, the request does not route to all indices; only those present in the PIT are queried. Furthermore, this issue is not a security vulnerability, as the authorization check continues to limit the list of accessible indices to those permitted for the user.

Closes #99684

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java [hunk 1]
```diff
@@ -469,6 +472,26 @@ private void authorizeAction(
...
+                var indices = SearchContextId.decodeIndices(searchRequest.pointInTimeBuilder().getEncodedId());
+                if (searchRequest.indices().length > 0 && Arrays.equals(searchRequest.indices(), indices) == false) {
+                    IllegalArgumentException cause = new IllegalArgumentException(
+                        "indices defined in the [pit] don't match the request's indices"
+                    );
+                    auditTrail.accessDenied(requestId, authentication, action, request, authzInfo);
+                    listener.onFailure(actionDenied(authentication, authzInfo, action, request, cause));
+                    return;
+                }
+                searchRequest.indices(indices);
```
Comment (javanna) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java:492]: do we still need to replace the indices or could we just perform the authorization and leave the indices empty? I am thinking that it could be good to enforce that a search request with a pit never specifies indices, but this would break that assumption.

**Review by javanna — COMMENTED** [review]
left a question, this seems like a good direction to me

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java (hunk 1 above)
Comment (jimczi) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java]: ++, we don't need to replace the indices I agree. I pushed [89853df](https://github.com/elastic/elasticsearch/pull/103152/commits/89853df0447c35e3cc5620f6edd82de1f05c809e) to resolve the indices directly from the PIT. I also removed the copy in the rest action (this is not needed now since the security layer knows where to look) and moved the request validation to the transport implementation

Comment (javanna) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java]: I was going to say, you may get some test failures from places that do set the indices. I think for instance ML transform does that.

File: test/framework/src/main/java/org/elasticsearch/test/client/RandomizingClient.java [hunk 2]
```diff
@@ -84,4 +87,18 @@ public Client in() {
...
+        RandomizedSearchRequestBuilder(ElasticsearchClient client) {
+            super(client);
+        }
+
+        @Override
+        public SearchRequestBuilder setPointInTime(PointInTimeBuilder pointInTimeBuilder) {
+            if (defaultPreference != null) {
+                setPreference(null);
+            }
+            return super.setPointInTime(pointInTimeBuilder);
```
Comment (javanna) [inline test/framework/src/main/java/org/elasticsearch/test/client/RandomizingClient.java:99]: I guess we should also override setPreference to make sure it throws if point in time is already set, otherwise we rely on order in which the methods are called?

Comment (jimczi) [reply test/framework/src/main/java/org/elasticsearch/test/client/RandomizingClient.java:99]: I am just checking the default preference here since it is set by the `RandomizingClient` ctr. If a test using this client sets the preference explicitly an error will be thrown during the execution indicating to the author of the test that preference shouldn't be used in this context.

Comment (javanna) [reply test/framework/src/main/java/org/elasticsearch/test/client/RandomizingClient.java:99]: oh right!

**Comment by jimczi** [comment]
The PR is ready for another round of review. I did some changes on the transform indexer too, @hendrikmuhs could you take a look?

**Comment by jimczi** [comment]
The PR is ready for another round of review @javanna . @przemekwitek can you take a look at the changes I made to the transform indexer?

**Review by javanna — APPROVED** [review]
LGTM, great work

**Comment by javanna** [comment]
@jimczi do you think this would be safe to backport?

**Comment by jimczi** [comment]
@javanna I think it's relatively safe but the impact on performance should be minimal so I am not sure if it's needed. The fix is really about reporting the targeted indices correctly so that the tasks and other expert APIs don't expose it wrongly.
