### PR TITLE
Validate index and cluster privilege names when creating a role

### LINKED ISSUE #29703: Add validation to privilege names in roles API
*Original comment by @ppf2:*

I have a feeling that we may already have this on the roadmap and it's just not in the first iteration of the API.  Filing to track progress since this will likely come up in the future.  Currently, there is no validation on the values of the privileges set when creating roles.  So it's possible for users to have a typo on the privilege names and the role will still get added/accepted by the API.

```
{
  "indices": [
    {
      "names": [ "test",".kibana" ],
      "privileges": [ "al" ]
    }
  ]
}
```

```
{
  "role": {
    "created": true
  }
}
```

It will be nice if we can validate this and throw back and exception (or maybe even include the list of allowable values for privileges in the exception, etc..).

### PR DESCRIPTION
**Pull request by bizybot**
This commit adds validation so a role cannot be created with
invalid index or cluster privilege name.

Closes #29703

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequest.java [hunk 1]
```diff
@@ -67,6 +70,24 @@ public ActionRequestValidationException validate() {
...
+                } catch (IllegalArgumentException ile) {
+                    validationException = addValidationError(ile.getMessage(), validationException);
+                }
+            }
+        }
+        if (indicesPrivileges != null) {
+            for (RoleDescriptor.IndicesPrivileges idp : indicesPrivileges) {
+                try {
+                    IndexPrivilege.get(Set.of(idp.getPrivileges()));
+                } catch(IllegalArgumentException ile) {
```
Comment (tvernum) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequest.java]:
```suggestion
                } catch (IllegalArgumentException ile) {
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java [hunk 2]
```diff
@@ -156,6 +160,7 @@ public static NamedClusterPrivilege resolve(String name) {
         if (fixedPrivilege != null) {
             return fixedPrivilege;
         }
+        logger.error("failed to resolve cluster privilege [" + name + "].");
```
Comment (tvernum) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java]: I don't think this message is as helpful as it could be.
What do we expect someone to do if they read this? Why is it an `ERROR` ?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/IndexPrivilege.java [hunk 3]
```diff
@@ -139,6 +142,7 @@ private static IndexPrivilege resolve(Set<String> name) {
                 } else if (indexPrivilege != null) {
                     automata.add(indexPrivilege.automaton);
                 } else {
+                    logger.error("failed to resolve index privilege [" + part + "].");
```
Comment (tvernum) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/IndexPrivilege.java]: as above

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java [hunk 4]
```diff
@@ -38,6 +38,42 @@
 
 public class PutRoleRequestTests extends ESTestCase {
 
+    public void testValidationErrorWithUnknownClusterPrivilegeName() {
+        final PutRoleRequest request = new PutRoleRequest();
+        request.name(randomAlphaOfLengthBetween(4, 9));
+        String unknownClusterPrivilegeName = randomAlphaOfLengthBetween(7, 9);
```
Comment (tvernum) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java]: What happens if this randomly generates a real name?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequest.java (hunk 1 above)
Comment (bizybot) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequest.java]: Done, Thank you.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java (hunk 4 above)
Comment (bizybot) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java]: Fixed the string for unknown privilege name to remove randomness.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java (hunk 2 above)
Comment (bizybot) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java]: Yes, I updated the error message to the same as the exception message to be more actionable. Thank you. I added it as an error as it is a failure condition and we would not be handling it. It could be a warning, but when doing authorization checks for an already saved role with invalid privilege (upgraded server) it will fail and we would want something like error log so someone looking at the logs its evident. Do you think it should be at other level?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java [hunk 5]
```diff
@@ -160,11 +160,12 @@ public static NamedClusterPrivilege resolve(String name) {
...
             return fixedPrivilege;
         }
-        logger.error("failed to resolve cluster privilege [" + name + "].");
-        throw new IllegalArgumentException("unknown cluster privilege [" + name + "]. a privilege must be either " +
+        String errorMessage = "unknown cluster privilege [" + name + "]. a privilege must be either " +
             "one of the predefined cluster privilege names [" +
             Strings.collectionToCommaDelimitedString(VALUES.keySet()) + "] or a pattern over one of the available " +
-            "cluster actions");
+            "cluster actions";
+        logger.error(errorMessage);
```
Comment (tvernum) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java]: I don't think this should be an error.
We would typically not log _anything_ for problems that are also reported in the Rest Response.
If there's a strong argument for doing so here, then it should be `warning` or lower, but I would suggest it's just a debug - the server admin doesn't need to care about this, the person submiting the request does.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java [hunk 6]
```diff
@@ -41,7 +41,7 @@
     public void testValidationErrorWithUnknownClusterPrivilegeName() {
         final PutRoleRequest request = new PutRoleRequest();
         request.name(randomAlphaOfLengthBetween(4, 9));
-        String unknownClusterPrivilegeName = randomAlphaOfLengthBetween(7, 9);
+        String unknownClusterPrivilegeName = "-unknown-";
```
Comment (tvernum) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java]:
```suggestion
        String unknownClusterPrivilegeName = "unknown_" + randomAlphaOfLengthBetween(3, 9);
```
Random was good, plain alpha was good, it just had a chance of doing the wrong thing.
I don't think a leading `-` is good because that's not representative of a real typo.

Comment (bizybot) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequestTests.java]: agreed updated this as suggested, Thank you.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java (hunk 5 above)
Comment (bizybot) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java]: changed it to debug, the message will be available during debugging. Thank you.

**Review by tvernum — APPROVED** [review]

**Review by jkakavas — APPROVED** [review]
LGTM
