### PR TITLE
Replace failing PolicyStepsRegistry sanity check assert with a test

### LINKED ISSUE #84979: [CI] ChangePolicyforIndexIT.testChangePolicyForIndex
### CI Link

https://gradle-enterprise.elastic.co/s/yp56iltyyinha

### Repro line

./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.testChangePolicyForIndex" -Dtests.seed=8825024EAE3089DD -Dtests.locale=en-PH -Dtests.timezone=Asia/Karachi -Druntime.java=16

### Does it reproduce?

No

### Applicable branches

7.17 (probably all 8+)

### Failure history

_No response_

### Failure excerpt

This is rather concerning
```
java.lang.AssertionError: policy step registry cache failed sanity check
	at org.elasticsearch.xpack.ilm.PolicyStepsRegistry.getStep(PolicyStepsRegistry.java:378) ~[?:?]
	at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.getCurrentStep(IndexLifecycleRunner.java:108) ~[?:?]
	at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPolicyAfterStateChange(IndexLifecycleRunner.java:430) ~[?:?]
	at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:416) ~[?:?]
	at org.elasticsearch.xpack.ilm.IndexLifecycleService.clusterChanged(IndexLifecycleService.java:319) ~[?:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:573) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:559) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:519) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:56) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) ~[elasticsearch-7.17.2-SNAPSHOT.jar:7.17.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[2022-03-15T09:34:09.657115416Z] [BUILD] Stopping node
```

### LINKED ISSUE #85036: [CI] org.elasticsearch.xpack.ilm.TimeseriesMoveToStepIT.testMoveToRolloverStep fails
### CI Link

https://gradle-enterprise.elastic.co/s/deqtxspnhxyva

### Repro line

./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.TimeseriesMoveToStepIT.testMoveToRolloverStep" -Dtests.seed=81FF6263145E4101 -Dtests.locale=es-ES -Dtests.timezone=America/Godthab -Druntime.java=8

### Does it reproduce?

No

### Applicable branches

7.17

### Failure history

Failed two times in the last 30 days, all very recent: https://gradle-enterprise.elastic.co/s/yp56iltyyinha

### Failure excerpt

The tests `TimeseriesMoveToStepIT.testMoveToRolloverStep` and `TimeseriesMoveToStepIT.testMoveToAllocateStep` both failed. 

I'm not sure what is the root cause but this is maybe interesting:

```
» [2022-03-16T10:55:00,346][ERROR][o.e.ExceptionsHelper     ] [javaRestTest-0] fatal error
»  	at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:287)
»  	at java.util.Optional.ifPresent(Optional.java:159)
»  	at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:277)
»  	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:229)
»  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
»  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
»  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
»  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
»  	at java.lang.Thread.run(Thread.java:748)
» [2022-03-16T10:55:00,347][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [javaRestTest-0] fatal error in thread [Thread-4], exiting
»  java.lang.AssertionError: policy step registry cache failed sanity check
»  	at org.elasticsearch.xpack.ilm.PolicyStepsRegistry.getStep(PolicyStepsRegistry.java:378) ~[?:?]
»  	at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.getCurrentStep(IndexLifecycleRunner.java:108) ~[?:?]
»  	at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:173) ~[?:?]
»  	at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:418) ~[?:?]
»  	at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:349) ~[?:?]
»  	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:186) ~[?:?]
»  	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:220) ~[?:?]
»  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
»  	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
»  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_301]
»  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_301]
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
»  	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
»   ↓ last 40 non err
```

As well as :

```
"action":"init","step":"ERROR","step_time":"1647428098374"},"error_details":"{\"type\":\"initialize_policy_exception\",\"reason\":\"unable to initialize policy [policy-zZOnT] for index [retryinit-20xx-01-10]\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"index name [retryinit-20xx-01-10] does not match pattern 
```

The test `ShrinkActionIT.testShrinkDuringSnapshot` also failed but I suspect it is more a consequence of the other failures.

### LINKED ISSUE #85075: [CI] ILMMultiNodeIT testShrinkOnTiers failing
Started failing in this way about 10 days ago (3-7-22). Seems to be affecting 7.17 and 8.1 branches.

**Build scan:**
https://gradle-enterprise.elastic.co/s/kg23spzlawfu6/tests/:x-pack:plugin:ilm:internalClusterTest/org.elasticsearch.xpack.ilm.ILMMultiNodeIT/testShrinkOnTiers

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:internalClusterTest' --tests "org.elasticsearch.xpack.ilm.ILMMultiNodeIT.testShrinkOnTiers" -Dtests.seed=F8EDA3E765E3F9DC -Dtests.locale=fr-LU -Dtests.timezone=Etc/GMT-6 -Druntime.java=11`

**Applicable branches:**
7.17, 8.1

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.ILMMultiNodeIT&tests.test=testShrinkOnTiers

**Failure excerpt:**
```
java.lang.AssertionError: Unable to find an ilm explain output for the shrunk index of myindex

  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertNotNull(Assert.java:712)
  at org.elasticsearch.xpack.ilm.ILMMultiNodeIT.lambda$testShrinkOnTiers$0(ILMMultiNodeIT.java:154)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1142)
  at org.elasticsearch.xpack.ilm.ILMMultiNodeIT.testShrinkOnTiers(ILMMultiNodeIT.java:137)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:829)

```

### LINKED ISSUE #85175: [CI] DataTiersMigrationsTests testUserOptsOutOfTierMigration failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/aodpvg6m2oba4/tests/:x-pack:plugin:ilm:internalClusterTest/org.elasticsearch.xpack.ilm.DataTiersMigrationsTests/testUserOptsOutOfTierMigration

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:internalClusterTest' --tests "org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.testUserOptsOutOfTierMigration" -Dtests.seed=D3FF350541188AFA -Dtests.locale=ar-IQ -Dtests.timezone=Asia/Famagusta -Druntime.java=18`

**Applicable branches:**
8.1

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.DataTiersMigrationsTests&tests.test=testUserOptsOutOfTierMigration

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is "warm"
     but: was "new"

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testUserOptsOutOfTierMigration$3(DataTiersMigrationsTests.java:192)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1070)
  at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.testUserOptsOutOfTierMigration(DataTiersMigrationsTests.java:187)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by joegallo**
Follow up to #84588, which was itself a follow up to #82316

I wanted this assert in there out of an abundance of caution, but indeed the other change in #84588 to `PolicyStepsRegistryTests` was a fair test of the intended behavior change on that PR.

This PR moves the stress test to actual test code. I've run it with `-Dtests.iters=10000` and it's fine (with the assert remaining it fails the sanity check (returning `null` rather than the expected step) in the neighborhood of 20% of the time as measured with `-Dtests.iters=100`). The test takes about a tenth of a second to run on a warmed up jvm on my box.

Closes #84979 
Closes #85036 
Closes #85075 
Closes #85175

### CODE REVIEW

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java [hunk 1]
```diff
@@ -465,4 +467,71 @@ public void testUpdatePolicyButNoPhaseChangeIndexStepsDontChange() throws Except
...
+            // test a variety of getStep calls with random actions and steps
+            for (int i = 0; i < scaledRandomIntBetween(100, 1000); i++) {
+                LifecycleAction action = randomValueOtherThan(MigrateAction.DISABLED, () -> randomFrom(phase.getActions().values()));
+                Step step = randomFrom(action.toSteps(client, phaseName, MOCK_STEP_KEY, null));
+                Step actualStep = registry.getStep(indexMetadata, step.getKey());
+                assertThat(actualStep.getKey(), equalTo(step.getKey()));
+            }
+        } finally {
+            // tell the other thread we're finished
+            done.set(true);
```
Comment (dakrone) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java:534]: Super minor nit, but in the event this is the very last test run in a suite (or it's just run by itself), it's possible our thread leak detector will complain since we aren't doing a `thread.join()` on the thread we spawn before to wait for it to be completely done. Do you think we should add that?

**Review by dakrone — APPROVED** [review]
LGTM, thanks for fixing this Joe

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java (hunk 1 above)
Comment (joegallo) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java:534]: Sure thing, I'll get that in.

Comment (joegallo) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java:535]: 0b4e18c247a3dc8c93f85957df7cb3eb58ad7189

**Comment by joegallo** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by joegallo** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java [hunk 2]
```diff
@@ -465,4 +467,73 @@ public void testUpdatePolicyButNoPhaseChangeIndexStepsDontChange() throws Except
...
+
+        PolicyStepsRegistry registry = new PolicyStepsRegistry(REGISTRY, client, null);
+        registry.update(meta);
+
+        // test a variety of getStep calls with random actions and steps
+        for (int i = 0; i < scaledRandomIntBetween(100, 1000); i++) {
+            LifecycleAction action = randomValueOtherThan(MigrateAction.DISABLED, () -> randomFrom(phase.getActions().values()));
+            Step step = randomFrom(action.toSteps(client, phaseName, MOCK_STEP_KEY, null));
+            Step actualStep = registry.getStep(indexMetadata, step.getKey());
+            assertThat(actualStep.getKey(), equalTo(step.getKey()));
```
Comment (andreidan) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java:506]: I'm a bit confused as to what this tests. There'll be a new step added, by-passing the cache, on every iteration - I'm quite confused specifically as we don't have any steps defined/registered before, yet we do setup some metadatas (both IndexMetadata and IndexLifecycleMetadata). Apologies if I'm missing something very obvious but could we document the intent here? (I'm _guessing_ we want to populate the cache? )

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Joe

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java (hunk 2 above)
Comment (joegallo) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistryTests.java:506]: Fair enough -- I spent a bit of time stressing over this exact point. It's a little bit tricky, I don't think you're missing something obvious. I'll add some comments and let's see where that gets us.
