### PR TITLE
Fix Get Snapshots Request Cancellation with ignore_unavailable=true

### LINKED ISSUE #77980: Cancelling retrieval of multiple `SnapshotInfo` does not always complete the task
**Elasticsearch version** (`bin/elasticsearch --version`): `master`, `7.14.1`

**Description of the problem including expected versus actual behavior**:

If the retrieval of multiple `SnapshotInfo` blobs is cancelled (e.g. you make a get-snapshots call and then close the connection) then we clear the queue and call `context.onFailure` here:

https://github.com/elastic/elasticsearch/blob/c0a967e952fcc9ad3b107509aa3e96179ba455d3/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L1516-L1520

However the context will only complete the outer listener once it's received `snapshotIds.size()` notifications (unless `abortOnFailure` is set) so by clearing the queue we leak the task.

FWIW we also log at `WARN` for every worker that encounters an exception, including cancellation. Cancellation is to be expected, we shouldn't log anything above `DEBUG`.

### PR DESCRIPTION
**Pull request by original-brownbear**
Short-circuit the failure method when cancelled just like in the fail fast case.
Also, remove the special case handling that asserts but swallows exceptions in production
for when ignoring unavailable to not swallow the task cancellation exception.

closes #77980

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 1]
```diff
@@ -443,18 +439,7 @@ private void snapshots(
                 ignoreUnavailable == false,
                 task::isCancelled,
                 (context, snapshotInfo) -> snapshotInfos.add(snapshotInfo),
-                ignoreUnavailable ? ActionListener.runAfter(new ActionListener<>() {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:446]: This was a weird listener wrapping to begin with, just to have the assertion.

**Comment by DaveCTurner** [comment]
Could we fix the logging too?

**Comment by original-brownbear** [comment]
> Could we fix the logging too?

It should be fixed with this change, since we short-circuit the same way we do for the fail-fast case we shouldn't be logging anything in the `GetSnapshotInfoContext` and the logging in the transport action is also gone with this change. Did I miss a spot?

**Review by DaveCTurner — APPROVED** [review]
Ah so we are. LGTM then.

**Comment by original-brownbear** [comment]
Thanks David!
