### PR TITLE
Make (read|write)NamedWriteable public

### LINKED ISSUE #17682: Proposal: make StreamInput#readNamedWriteable and StreamOutput#readNamedWriteable public
Now that we have NamedWriteable we keep finding things that had little implementations of it like `AllocationCommand`s and aggregation's streams. Each time we convert those to a named writeable we create new methods in StreamInput and StreamOutput to write those objects. The methods are really simple, like:
```java
    public SuggestionBuilder<?> readSuggestion() throws IOException {
        return readNamedWriteable(SuggestionBuilder.class);
    }
```

So, why do we make these methods rather than just use `readNamedWriteable` directly? I mean, now `readNamedWriteable` is protected so we **can't**. But why not just make it public?

The argument for keeping it protected is that it forces us to be intentional about each new named writable. You can't make a new type of NamedWriteable in a plugin because you'd have to modify StreamInput and StreamOutput.

The argument for making it public is that we can drop all of the `readFooBar` methods and StreamInput and StreamOutput no longer need to know about all of the classes that they are reading.

So let's discuss! Regardless of the outcome this issue will be closed by a PR - either one that makes the methods public or one that adds some javadoc summarizing the outcome of the conversation.

### PR DESCRIPTION
**Pull request by nik9000**
- Make (read|write)NamedWriteable public
- Remove some of the lesser used readXYZ/writeXYZ methods
- Deprecate all remaining readXYZ/writeXYZ methods

I believe it is safe to remove all of the remaining readXYZ/writeXYZ method because the only release that contained them was 5.0.0-alpha1 but that'd make the PR too large. readQuery/writeQuery is very common. The others are rare, but there are too many of them.

Closes #17682

### CODE REVIEW

**Comment by nik9000** [comment]
Any of @jpountz @ywelsch @cbuescher @javanna around still and want to have a look?

File: core/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java [hunk 1]
```diff
@@ -725,100 +721,88 @@ public DateTimeZone readOptionalTimeZone() throws IOException {
...
-     */
-    public QueryBuilder<?> readQuery() throws IOException {
-        return readNamedWriteable(QueryBuilder.class);
-    }
-
-    /**
-     * Reads an optional {@link QueryBuilder}.
-     */
-    public QueryBuilder<?> readOptionalQuery() throws IOException {
+    public <C extends NamedWriteable<?>> C readOptionalNamedWriteable(Class<C> categoryClass) throws IOException {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java]: mark return type as Nullable?

File: core/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java [hunk 2]
```diff
@@ -687,68 +683,55 @@ public void writeThrowable(Throwable throwable) throws IOException {
...
-
-    /**
-     * Writes a {@link QueryBuilder} to the current stream
-     */
-    public void writeQuery(QueryBuilder<?> queryBuilder) throws IOException {
-        writeNamedWriteable(queryBuilder);
-    }
-
-    /**
      * Write an optional {@link QueryBuilder} to the stream.
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java]: javadoc out of date -> should be NamedWriteable instead of QueryBuilder

**Comment by ywelsch** [comment]
Left two minor comments. I would prefer we remove all of the remaining readXYZ/writeXYZ from StreamInput/Output before 5.0.0-beta. Can be done in a follow-up PR though. Also, if people prefer the readQuery(), writeQuery()-style methods, they can still be added as static methods to the respective class (QueryBuilder). For example:

```
public static readQuery(StreamInput in) {
    return in.readNamedWriteable(QueryBuilder.class);
}

...
```

**Comment by ywelsch** [comment]
Forgot to say. Once comments addressed, feel free to push. Thanks @nik9000.

**Comment by nik9000** [comment]
Thanks for reviewing @ywelsch ! I'll clean up and push in a bit!

**Comment by nik9000** [comment]
Thanks again for the review @ywelsch! I've pushed!
