### PR TITLE
Fixed NPEs caused by requests without content.

### LINKED ISSUE #24701: Bulk index operation w/o body throws NPE
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): Windows 7 x64

**Description of the problem including expected versus actual behavior**:
When calling the _bulk API to index multiple documents, and not using an actual POST body, the server prints a stacktrace of a NullPointerException and responds with a 'null_pointer_exception' error in the response body.
It is clear that this was a bad request, since the actual data which should be indexed, was missing. But it should not result in a NPE but maybe rather a HTTP Bad Request response code. One could even argue that a bulk index without any data is like a bulk index with 0 data, so it could also be regarded a valid call just without any updated documents.

**Steps to reproduce**:
- Download elasticsearch zip from https://www.elastic.co/downloads/elasticsearch
- Extract the zip somewhere
- execute bin/elasticsearch.bat
- use a HTTP client to create an index via POST localhost:9200/exampleindex
- use a HTTP client to call a bulk index operation via POST localhost:9200/exampleindex/all/_bulk but without a POST body

**Provide logs (if relevant)**:
The following exception stacktrace is printed in the log upon calling the last POST request above:
```
java.lang.NullPointerException: null
        at org.elasticsearch.action.bulk.BulkRequest.add(BulkRequest.java:318) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.rest.action.document.RestBulkAction.prepareRequest(RestBulkAction.java:89) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:64) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:260) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:199) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:504) [transport-netty4-5.4.0.jar:5.4.0]
        at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:72) [transport-netty4-5.4.0.jar:5.4.0]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.9.Final.jar:4.1.9.Final]
```

### PR DESCRIPTION
**Pull request by qwerty4030**
Fixed NPEs caused by requests without content.
REST handlers that require a body will throw an an `ElasticsearchParseException` "request body required".
REST handlers that require a body OR source param will throw an `ElasticsearchParseException` "request body or source parameter is required".
Replaced asserts in `BulkRequest` parsing code with a more descriptive `IllegalArgumentException` if the line contains an empty object.

Before this fix all the following requests threw confusing exceptions:
```
POST _bulk
POST _search/template/test
POST _scripts/test
POST _mapping/test
POST test-index/test-type
response:
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}

POST _template/test
response:
{

  "error": {
    "root_cause": [
      {
        "type": "not_x_content_exception",
        "reason": "Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"
      }
    ],
    "type": "not_x_content_exception",
    "reason": "Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"
  },
  "status": 500
}

POST _bulk
{}
response (note strange null in reason):
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Malformed action/metadata line [1], expected START_OBJECT or END_OBJECT but found [null]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Malformed action/metadata line [1], expected START_OBJECT or END_OBJECT but found [null]"
  },
  "status": 400
}
```

After this fix, requests that require a body will throw this exception:
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "request body required"
      }
    ],
    "type": "parse_exception",
    "reason": "request body required"
  },
  "status": 400
}
```

After this fix, requests require a body or `source` param:
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "request body or source parameter is required"
      }
    ],
    "type": "parse_exception",
    "reason": "request body or source parameter is required"
  },
  "status": 400
}
```
Fixed confusing `_bulk` response:
```
POST _bulk
{}
response:
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Malformed action/metadata line [1], expected FIELD_NAME but found [END_OBJECT]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Malformed action/metadata line [1], expected FIELD_NAME but found [END_OBJECT]"
  },
  "status": 400
}
```

Closes #24701

### CODE REVIEW

**Comment by qwerty4030** [comment]
@jaymode Do you mind taking a look at this? I noticed you made some changes recently related to content type in #23146. I'm not sure this is the best solution; seems like there should be better way to reject requests at a higher level when there is no content (but it's required). Thanks!

Also I did not add tests for the missing content scenarios. Should this be tested with the REST tests or Java integration tests?

**Review by jasontedor — CHANGES_REQUESTED** [review]
I left one comment, but it applies throughout the change. Additionally, I think that REST tests need to be added for all of these changes.

**Comment by jaymode** [comment]
> I think that we should still blow up here, just not with an NPE?

I agree. This change may get larger but it would be great to have a general purpose way to do this. Thinking out loud:

* Make `request#content` throw an exception when there is no content
* Add new method to the `RestHandler` interface, something like `requiresContentOrSource`. This one is tricky because some rest handlers allow the content to be specified as the source parameter when it is a GET request with a body, so a simple boolean is not sufficient as not everything will support the source parameter.
* Remove direct uses of `RestRequest#content` and always use `RestRequest#contentOrSourceParamParser` and similar methods, which would need to be updated to ensure we have methods that throw when a body/source param is required etc. I do not think we'll be able to remove all of these methods as sometimes we just pass on the bytes directly.

I think all of these options have flaws, but hopefully this helps generate some other ideas about how to handle this.

File: core/src/main/java/org/elasticsearch/rest/action/document/RestBulkAction.java [hunk 1]
```diff
@@ -86,8 +86,10 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
         }
         bulkRequest.timeout(request.paramAsTime("timeout", BulkShardRequest.DEFAULT_TIMEOUT));
         bulkRequest.setRefreshPolicy(request.param("refresh"));
-        bulkRequest.add(request.content(), defaultIndex, defaultType, defaultRouting, defaultFields,
-            defaultFetchSourceContext, defaultPipeline, null, allowExplicitIndex, request.getXContentType());
+        if(request.hasContent()) {
+            bulkRequest.add(request.content(), defaultIndex, defaultType, defaultRouting, defaultFields,
+                defaultFetchSourceContext, defaultPipeline, null, allowExplicitIndex, request.getXContentType());
+        }
```
Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/rest/action/document/RestBulkAction.java]: I followed the pattern used in a few other places. e.g. [RestCreateIndexAction#L44-L46](https://github.com/elastic/elasticsearch/blob/7420bda8ed8a992b36ec6bd1b8b8c11b8b20db44/core/src/main/java/org/elasticsearch/rest/action/admin/indices/RestCreateIndexAction.java#L44-L46).
Instead of failing in `RestHandler.prepareRequest` a validation exception will be thrown from `ActionRequest.validate()` if request content is missing but required.
Would an approach similar to [RestDeleteByQueryAction.java#L51-L53](https://github.com/elastic/elasticsearch/blob/2e48fb8294a924bc3742419fe80e4a29fdfa0f54/modules/reindex/src/main/java/org/elasticsearch/index/reindex/RestDeleteByQueryAction.java#L51-L53) be better for cases when request content is required?

**Comment by qwerty4030** [comment]
@jaymode I like your first suggestion: 

> Make `request#content` throw an exception when there is no content

If content is required this method will be called like it was before this PR and throw an exception if content is missing.
If content is optional the call can be placed inside `if(request.hasContent()) {}`

Let me know if that sounds good to you and I'll revert the changes in this PR and update the `RestRequest#content` method to `throw new ElasticsearchParseException("Body required");` similar to `RestRequest#contentOrSourceParamParser`.

While I was looking at the code I noticed `RestRequest#contentOrSourceParam` does not throw an exception if content and source are missing. I traced one usage to `RestMultiSearchAction#parseMultiLineRequest` and it results in an validation exception:
```
POST _msearch
response:
{
  "error": {
    "root_cause": [
      {
        "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: no requests added;"
      }
    ],
    "type": "action_request_validation_exception",
    "reason": "Validation Failed: 1: no requests added;"
  },
  "status": 400
}
```
Should the requests that use this method fail earlier (while parsing) as well?

**Comment by jaymode** [comment]
@qwerty4030 I apologize for the delay here. 

> If content is required this method will be called like it was before this PR and throw an exception if content is missing.
If content is optional the call can be placed inside if(request.hasContent()) {}

This sounds good to me.

> While I was looking at the code I noticed RestRequest#contentOrSourceParam does not throw an exception if content and source are missing. I traced one usage to RestMultiSearchAction#parseMultiLineRequest and it results in an validation exception:

I think we should probably try to get rid of this behavior and just rely on the behavior you described above (throw exception if content is missing).

**Comment by qwerty4030** [comment]
@jaymode Pushed new changes. I had to create a new `RestRequest#requiredContent()` method since `content()` was `abstract` and I didn't want to mess with the implementations. Also this way we can just call `content()` if its optional or `requiredContent()` if its not (IMO better than having to wrap it in an `if(request.hasContent())`.

I was unable to add REST tests because the internal test runner validates the request using the api spec, which requires a body for these requests. Should I look into adding some kind of override or try adding integration/unit tests instread? Thanks!

**Comment by jasontedor** [comment]
This sounds like a good scenario for an `ESRestTestCase`.

**Comment by qwerty4030** [comment]
@jasontedor Looks like I spoke too soon. I discovered that you can do a `raw` REST call:
```
---
"missing body":
  - do:
      catch: /request body required/
      raw:
        method: POST
        path: _bulk
```
Would you prefer that?

Another idea I had was to somehow use the REST API spec to automatically test all requests that require a body.

**Comment by jasontedor** [comment]
> Would you prefer that?

The REST tests (the YAML-based ones) are preferred because then the other language clients benefit from them too.

> Another idea I had was to somehow use the REST API spec to automatically test all requests that require a body.

I'd rather that we not get fancy here, there are other consumers of the REST tests.

**Comment by qwerty4030** [comment]
@jasontedor Pushed updates to the REST tests and cleaned up some `RestHandler`s to use the changes in `RestRequest` to throw an exception when content is missing.

File: core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java [hunk 2]
```diff
@@ -300,10 +300,16 @@ public BulkRequest add(BytesReference data, @Nullable String defaultIndex, @Null
                 if (token == null) {
                     continue;
                 }
-                assert token == XContentParser.Token.START_OBJECT;
+                if(token != XContentParser.Token.START_OBJECT) {
```
Comment (jaymode) [inline core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: Please use a space between the `if` and `(`. Also, I think it would be good to use `XContentParserUtils#ensureExpectedToken` or `XContentParserUtils#ensureFieldName`

File: core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java [hunk 3]
```diff
@@ -300,10 +300,16 @@ public BulkRequest add(BytesReference data, @Nullable String defaultIndex, @Null
...
+                    throw new IllegalArgumentException("Malformed action/metadata line [" + line + "], expected "
+                        + XContentParser.Token.START_OBJECT + " but found [" + token + "]");
+                }
                 // Move to FIELD_NAME, that's the action
                 token = parser.nextToken();
-                assert token == XContentParser.Token.FIELD_NAME;
+                if(token != XContentParser.Token.FIELD_NAME) {
```
Comment (jaymode) [inline core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: I think it would be good to use `XContentParserUtils#ensureExpectedToken` or `XContentParserUtils#ensureFieldName`

File: core/src/main/java/org/elasticsearch/rest/RestRequest.java [hunk 4]
```diff
@@ -137,6 +137,18 @@ public final String path() {
     public abstract BytesReference content();
 
     /**
+     * @return content of the request body or throw an exception if the body or content type is missing
+     */
+    public final BytesReference requiredContent() {
+        if(hasContent() == false) {
```
Comment (jaymode) [inline core/src/main/java/org/elasticsearch/rest/RestRequest.java]: space between `if` and `(`

File: core/src/main/java/org/elasticsearch/rest/RestRequest.java [hunk 5]
```diff
@@ -390,28 +393,26 @@ public final void withContentOrSourceParamParserOrNull(CheckedConsumer<XContentP
...
         String typeParam = param("source_content_type");
-        if (source != null && typeParam != null) {
-            BytesArray bytes = new BytesArray(source);
-            final XContentType xContentType = parseContentType(Collections.singletonList(typeParam));
-            if (xContentType == null) {
-                throw new IllegalStateException("Unknown value for source_content_type [" + typeParam + "]");
-            }
-            return new Tuple<>(xContentType, bytes);
+        if (source == null || typeParam == null) {
+            throw new IllegalStateException("source and source_content_type param required");
```
Comment (jaymode) [inline core/src/main/java/org/elasticsearch/rest/RestRequest.java]: Change "param required" to "parameters are required"

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java [hunk 6]
```diff
@@ -57,18 +57,17 @@ protected void parseInternalRequest(Request internal, RestRequest restRequest,
...
-             * withContentOrSourceParamParserOrNull will close it for us but if it isn't then we should close it. Technically close on
-             * the generated parser probably is a noop but we should do the accounting just in case. It doesn't hurt to close twice but it
-             * really hurts not to close if by some miracle we have to. */
-            try {
-                RestSearchAction.parseSearchRequest(searchRequest, restRequest, searchRequestParser);
-            } finally {
-                IOUtils.close(searchRequestParser);
-            }
-        });
+        XContentParser parser = restRequest.contentOrSourceParamParser();
```
Comment (jaymode) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java]: use a try-with resources for the parser value

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java [hunk 7]
```diff
@@ -57,18 +57,17 @@ protected void parseInternalRequest(Request internal, RestRequest restRequest,
...
+        parser = extractRequestSpecificFieldsAndReturnSearchCompatibleParser(parser, bodyConsumers);
```
Comment (jaymode) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java]: use a different variable

**Review by jaymode — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java (hunk 3 above)
Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: I tried to use these methods but the `ParsingException` they throw has the wrong line number due to `BulkRequest#add` creating a new `XContentParser` for each action.

Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: On potential fix it to catch the `ParsingException` and rethrow a new  `ParsingException` with the correct line number.

**Comment by qwerty4030** [comment]
@jaymode Pushed changes to address all your comments except the one about using `XContentParserUtils#ensureExpectedToken` (see my comment above). Thanks!

**Comment by qwerty4030** [comment]
@jasontedor @jaymode Hey guys, are there any other changes you would like me to make? Thanks.

**Comment by jasontedor** [comment]
This branch is not up to date with master, can you merge it in and resolve conflicts? Also @jaymode is on vacation this, and we are going to need his eyes on this next week before it can be pulled.

**Comment by qwerty4030** [comment]
Sounds good. I'll merge master a bit later this week to catch any future conflicts.

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java [hunk 8]
```diff
@@ -83,6 +83,9 @@ protected void parseInternalRequest(Request internal, RestRequest restRequest,
      */
     private XContentParser extractRequestSpecificFields(RestRequest restRequest,
                                                         Map<String, Consumer<Object>> bodyConsumers) throws IOException {
+        if(restRequest.hasContentOrSourceParam() == false) {
```
Comment (qwerty4030) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java]: Jumped the gun on cleaning up this class: turns out that `update_by_query` allows an empty body so we need to make sure this method does not throw an exception is the request body or source param is missing.

**Comment by qwerty4030** [comment]
Merged master and disabled the new REST tests for BWC tests.

**Comment by qwerty4030** [comment]
@jaymode Let me know when you'll have time to take another look. Thanks.

**Comment by qwerty4030** [comment]
Merged latest master to resolve conflicts and ran `gradle check` successfully.
@jaymode Please take a look when you have a chance.

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java [hunk 9]
```diff
@@ -89,12 +79,13 @@ protected void parseInternalRequest(Request internal, RestRequest restRequest,
      * should get better when SearchRequest has full ObjectParser support
      * then we can delegate and stuff.
      */
-    private XContentParser extractRequestSpecificFieldsAndReturnSearchCompatibleParser(XContentParser parser,
-                                      Map<String, Consumer<Object>> bodyConsumers) throws IOException {
-        if (parser == null) {
-            return parser;
+    private XContentParser extractRequestSpecificFields(RestRequest restRequest,
+                                                        Map<String, Consumer<Object>> bodyConsumers) throws IOException {
+        if(restRequest.hasContentOrSourceParam() == false) {
```
Comment (jaymode) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java]: can you add a space between the `if` and `(`

File: core/src/test/java/org/elasticsearch/action/bulk/BulkRequestTests.java [hunk 10]
```diff
@@ -177,6 +177,31 @@ public void testSimpleBulk10() throws Exception {
         assertThat(bulkRequest.numberOfActions(), equalTo(9));
     }
 
+    public void testBulkEmptyObject() throws Exception {
+        String bulkIndexAction = "{ \"index\":{\"_index\":\"test\",\"_type\":\"type1\",\"_id\":\"1\"} }\r\n";
+        String bulkIndexSource = "{ \"field1\" : \"value1\" }\r\n";
+        String emptyObject = "{}\r\n";
+        StringBuilder bulk = new StringBuilder();
+        int emptyLine;
+        if(randomBoolean()) {
```
Comment (jaymode) [inline core/src/test/java/org/elasticsearch/action/bulk/BulkRequestTests.java]: space between `if` and `(`

**Review by jaymode — CHANGES_REQUESTED** [review]
left two style comments, but otherwise I think this is ready to get in after fixing those and merging master again. @jasontedor do you want to take another look as well?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by qwerty4030** [comment]
Squashed all commits and rebased on latest master. `grade check` successful.

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java (hunk 9 above)
Comment (qwerty4030) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBulkByQueryRestHandler.java]: done in 08d1749

File: core/src/test/java/org/elasticsearch/action/bulk/BulkRequestTests.java (hunk 10 above)
Comment (qwerty4030) [inline core/src/test/java/org/elasticsearch/action/bulk/BulkRequestTests.java]: done in 08d1749

**Comment by jaymode** [comment]
jenkins please test this

**Comment by jaymode** [comment]
Thanks @qwerty4030 for the iteration and the contribution. I'll merge this to master and look into backporting to 5.x as well.

**Comment by jaymode** [comment]
Pushed 4ad47d204d20af87457267103fb81f9011696bfe for 5.x

**Comment by qwerty4030** [comment]
@jaymode Thanks for the review. Question: do we need to do something different for backport REST tests because they should pass for latest 5.X, but not for versions <= 5.4?

**Comment by jaymode** [comment]
@qwerty4030 I took care of it during the backport by changing the skip version to `5.4.99`. I'll also update the tests on master shortly to use that for the skip version
