### PR TITLE
Ensure that .watcher-history-11* template is in installed prior to use

### LINKED ISSUE #56732: Watcher history may not have the correct mappings after an upgrade to 7.0.0
7.0.0 introduces a new version (`11`) of the Watcher history index template. This index template may not get installed prior to Watcher writing to the .watcher-history* index. This may happen due to some new behavior that requires the all the nodes to be on 7.7.0 before installing the new version (`11`) of index template. [1] This likely isn't a concern to most users since the .watcher-history index is esentially a just a log of the watches that have run and is generally only used for troubleshooting and this will likely go unoticed. Further, since Watcher uses a daily index and upgrades usually don't span multiple days the next day's index should have the correct mappings. 

This will most likely only be noticed for large watches where the single record of it's execution can exceed the total field of 1000. `failure [java.lang.IllegalArgumentException: Limit of total fields [1000] in index [.watcher-history-11-2020.05.13] has been exceeded]` 

Once an index is created you can not retroactivley apply an index template, so the suggested workaround to this to copy the exiting version (`10`) and install it as version `11`, then delete that day's .watcher-history index. Once the upgrade is complete delete the installed `11` template and Watcher will auto install the real `11` template. Or, you can just ignore the error in the logs for that day, it is pretty harmless since it is effectily a failure to log what happened. However, the error logs can get quite noisy if lots of Watches are running past the 1000 field limit. 

[1]
[WatcherIndexTemplateRegistry](https://github.com/elastic/elasticsearch/blob/7.7/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java#L74) as of https://github.com/elastic/elasticsearch/pull/52962.

### PR DESCRIPTION
**Pull request by jakelandis**
[WatcherIndexTemplateRegistry](https://github.com/elastic/elasticsearch/blob/7.7/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java#L74)
as of https://github.com/elastic/elasticsearch/pull/52962 requires all nodes
to be on 7.7.0 before it allows the version 11 index template to be installed.

While in a mixed cluster, nothing prevents Watcher from running on the new
host before the all of the nodes are on 7.7.0. This will result in the
.watcher-history-11* index without the proper mappings. Without the proper
mapping a single document (for a large watch) can exceed the default 1000 field
limit and cause error to show in the logs.

This commit ensures the same logic for writing to the index is applied as for
installing the template. In a mixed cluster, the `10` index template will continue
to be written. Only once all of nodes are on 7.7.0+ will the `11` index template
be installed and used.

Note - this PR targets 7.x and will be back ported to 7.7.next. This conditional
installation of the template is not present in master.

closes #56732

### CODE REVIEW

**Comment by jakelandis** [comment]
@gwbrown - mind taking a look at this one? It touches some of the areas I know you are familiar with.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java [hunk 1]
```diff
@@ -154,7 +154,7 @@ private void addTemplatesIfMissing(ClusterState state) {
             if (creationCheck.compareAndSet(false, true)) {
                 IndexTemplateMetadata currentTemplate = state.metadata().getTemplates().get(templateName);
                 if (Objects.isNull(currentTemplate)) {
-                    logger.debug("adding index template [{}] for [{}], because it doesn't exist", templateName, getOrigin());
+                    logger.info("adding index template [{}] for [{}], because it doesn't exist", templateName, getOrigin());
```
Comment (jakelandis) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:157]: I bumped this up to info to better match the `upgrading index template` message. The adding of the template gets logged on the master node (at info level) but having this at `info` level helps to make the upgrade/add consistent.

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/history/HistoryStoreTests.java [hunk 2]
```diff
@@ -105,14 +120,21 @@ public void testPut() throws Exception {
     }
 
     public void testIndexNameGeneration() {
-        String indexTemplateVersion = Integer.toString(INDEX_TEMPLATE_VERSION);
-        assertThat(getHistoryIndexNameForTime(Instant.ofEpochMilli((long) 0).atZone(ZoneOffset.UTC)),
-            equalTo(".watcher-history-"+ indexTemplateVersion +"-1970.01.01"));
-        assertThat(getHistoryIndexNameForTime(Instant.ofEpochMilli(100000000000L).atZone(ZoneOffset.UTC)),
+        String indexTemplateVersion;
+        if (randomBoolean()) {
```
Comment (gwbrown) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/history/HistoryStoreTests.java:124]: Why don't we about we extract this boolean to a parameter and always run both, rather than randomizing? This is a unit test, so it should be too expensive to do so, and that way the suite is guaranteed to catch breakage in a single test run.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/history/HistoryStore.java [hunk 3]
```diff
@@ -31,17 +32,19 @@
     private static final Logger logger = LogManager.getLogger(HistoryStore.class);
 
     private final BulkProcessor bulkProcessor;
+    private final ClusterService clusterService;
 
-    public HistoryStore(BulkProcessor bulkProcessor) {
+    public HistoryStore(BulkProcessor bulkProcessor, ClusterService clusterService) {
```
Comment (gwbrown) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/history/HistoryStore.java:37]: Do you think it might be better to change this to a `Supplier<ClusterState>` so that it's clearer that we just need to access the current `ClusterState`? That would let us simplify the mocking a bit and make it clearer that we're not e.g. adding listeners here.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java [hunk 4]
```diff
@@ -623,14 +623,14 @@ static void validAutoCreateIndex(Settings settings, Logger logger) {
...
-        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(5)));
-        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(6)));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now, clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusDays(1), clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(1), clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(2), clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(3), clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(4), clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(5), clusterService.state()));
+        indices.add(HistoryStoreField.getHistoryIndexNameForTime(now.plusMonths(6), clusterService.state()));
```
Comment (gwbrown) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java:633]: We should get the state once and pass the same state to each check, to ensure the behavior is consistent if the state changes out from under us.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java [hunk 5]
```diff
@@ -259,6 +255,10 @@ public Watcher(final Settings settings) {
                                                NodeEnvironment nodeEnvironment, NamedWriteableRegistry namedWriteableRegistry,
                                                IndexNameExpressionResolver expressionResolver,
                                                Supplier<RepositoriesService> repositoriesServiceSupplier) {
+        if (enabled && transportClient == false) {
+            validAutoCreateIndex(settings, logger, clusterService);
+        }
```
Comment (gwbrown) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java:260]: Just double checking: This doesn't result in different behavior, right? Just makes the failure occur (if it occurs) at a different time during node startup.

(also, my assumption is that this moved because at the time the constructor is called we don't have a cluster state yet, correct?)

**Review by AthenaEryma — COMMENTED** [review]
Good catch. Thanks for the fix and apologies for the breakage. Left a few relatively minor comments, but this looks like a good fix.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java (hunk 5 above)
Comment (jakelandis) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java:260]: correct, same behavior and moved to allow access the the cluster state.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/history/HistoryStore.java (hunk 3 above)
Comment (jakelandis) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/history/HistoryStore.java]: [done](https://github.com/elastic/elasticsearch/pull/56734/commits/123453ccfff325b6fa364944dd19a37bc7e789c2)

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/history/HistoryStoreTests.java (hunk 2 above)
Comment (jakelandis) [reply x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/history/HistoryStoreTests.java]: [done](https://github.com/elastic/elasticsearch/pull/56734/commits/123453ccfff325b6fa364944dd19a37bc7e789c2)

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java (hunk 4 above)
Comment (jakelandis) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/Watcher.java]: [done](https://github.com/elastic/elasticsearch/pull/56734/commits/123453ccfff325b6fa364944dd19a37bc7e789c2)

**Comment by jakelandis** [comment]
@gwbrown thanks for the review, should be ready for another look - changes implemented on https://github.com/elastic/elasticsearch/pull/56734/commits/123453ccfff325b6fa364944dd19a37bc7e789c2

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
Test failures look related to attempting to read cluster state too early..

**Comment by jakelandis** [comment]
Had to remove the conditional logic for the `validAutoCreateIndex` method. This relevant parts of this method only emits a warning if the auto_create_index setting is too restrictive to create daily indices for the next 6 months. For this case, it is fine (possibly even more correct) to always assume the latest version of the index name.  Changes on https://github.com/elastic/elasticsearch/pull/56734/commits/7a8006806fcb03b60544804986fb5f9d856c6f34

**Review by AthenaEryma — APPROVED** [review]
LGTM, thanks! I agree that only checking the "newest" index name pattern is probably fine, it's very much a best-effort check anyway.
