### PR TITLE
[Test] Fix IndicesClientDocumentationIT

### LINKED ISSUE #27754: [CI] MigrationDocumentationIT#testClusterHealth failed
This test has been failed recently but I could not reproduce it locally.

```
 gradle :client:rest-high-level:integTestRunner \
  -Dtests.seed=A72A1EF88C187DAB \
  -Dtests.class=org.elasticsearch.client.documentation.MigrationDocumentationIT \
  -Dtests.method="testClusterHealth" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:+AggressiveOpts" \
  -Dtests.locale=fr \
  -Dtests.timezone=Europe/Isle_of_Man
```

Some instances:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/526/console

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/406/console

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/525/console

Log: [testClusterHealth.txt](https://github.com/elastic/elasticsearch/files/1548097/testClusterHealth.txt)

### PR DESCRIPTION
**Pull request by tlrx**
The last operation executed in `IndicesClientDocumentationIT.testCreate()`
 is an asynchronous index creation. Because nothing waits for its
 completion, on slow machines the index can sometimes be created after
 the `testCreate()` test is finished and it can fail the following test.

This pull request adds some `assertBusy` loops in order to wait for the 
completion of async operations.

 Closes #27754

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java [hunk 1]
```diff
@@ -188,6 +216,13 @@ public void onFailure(Exception e) {
                 }
             });
             // end::create-index-execute-async
+
```
Comment (dnhatn) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java]: Can we use CountDownLatch instead of assertBusy?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java [hunk 2]
```diff
@@ -188,6 +216,13 @@ public void onFailure(Exception e) {
...
+            assertBusy(() -> {
+                // TODO Use Indices Exist API instead once it exists
```
Comment (dnhatn) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java]: Can we CountDownLatch instead of assertBusy

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java]: I don't think we can because the CountDownLatch will appear in the documentation (everything between `// tag::foo` and `// end::foo` is copied in the documentation)

Comment (dnhatn) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java]: Ah, ok.

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by tlrx** [comment]
Thanks @dnhatn !
