### PR TITLE
ESQL: unmapped_fields="load" 500 error for index patterns usage

### LINKED ISSUE #145555: ESQL: unmapped_fields="load" 500 error for index patterns usage
### Description

There is this query:

```
SET unmapped_fields="load";
from sample_dat* 
 | FORK 
          (where  NOT byte_length(message) < 11)
          (where true)
```

That results in a 500 error

```
                "type": "illegal_state_exception",
                "reason": "Multiple index patterns should be disabled with unmapped fields"
```

But, if I am doing

```
from sample_data
 | FORK 
          (where  NOT byte_length(message) < 11)
          (where true)
```

I get

```
FORK is not supported with unmapped_fields=\"load\"
```

The first error message being a 500 seems to indicate that we didn't expect to reach that part of code. We should have a clearer error message instead and one that shouldn't be a 500, **if indeed we do not support patterns**, or is the fact that there are multiple indices covered by a pattern?

Also, this one works `SET unmapped_fields="load"; from sample_dat* | WHERE client_ip::string != "foo"` which seems to indicate that we **do support unmapped_fields="load"** with index patterns.

---

Unrelated, or maybe it is, the following query results in

```
argument of [byte_length(event_duration)] must be [string], found value [event_duration] type [long]
```

```
SET unmapped_fields="load";
from sample_dat* 
 | FORK 
          (where  NOT byte_length(event_duration) < 11)
          (where true)
```

But it should complain about `FORK` usage, as well. Or, primarily, complain about `FORK`.

### PR DESCRIPTION
**Pull request by mouhc1ne**
- Throw a `VerificationException`(400 error) from the Analyzer instead of `IllegalStateException`(500) when querying multiple index patterns.
- Add yaml tests for `unmapped_fields=load` and `FORK`
- Add new capability

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -2425,6 +2425,12 @@ public enum Cap {
          */
         USER_AGENT_COMMAND,
 
+        /**
+         * Fix for 500 error when querying multiple indices with {@code unmapped_fields="load"}.
+         * See https://github.com/elastic/elasticsearch/issues/145555
+         */
+        FIX_UNMAPPED_LOAD_MULTI_INDEX_PATTERN
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: nit: can you prefix this with `OPTIONAL_FIELDS_...` and move it next to `OPTIONAL_FIELDS_V5`?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 2]
```diff
@@ -1274,9 +1273,7 @@ private static LogicalPlan resolvePartiallyMapped(LogicalPlan plan, AnalyzerCont
                     throw new IllegalStateException("Unmapped fields with empty index resolutions.");
                 }
                 if (indexResolutions.size() > 1) {
-                    throw new IllegalStateException(
-                        Strings.format("Multiple index patterns should be disabled with unmapped fields", indexResolutions)
-                    );
+                    throw new VerificationException("Multiple index patterns are not supported with unmapped_fields=\"load\"");
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Question: do we end up with a better error message if we just _don't throw_ here?

The problem should be caught right after, no?

Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Error message is not ideal as it spills ESQL internals that users cannot really act on. In all the new yaml tests, only 1 index pattern was supplied.

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: I want to point out a _slightly_ (correctness/code pattern) aspect here (vs. the "better error message" aspect): a forced VerificationException throw in Analyzer without the Verifier doing it is not quite how the Analyzer - Verifier relationship should be :-).

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: And yes, it should be caught in the Verifier and handled there by the FORK and Views restrictions check. Now, what the reality actually is, we'll see :-).

Comment (mouhc1ne) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: If we let it slip from `Analyzer`, `Verifier` will catch it and flag along any other VerificationExceptions, if any.

Comment (mouhc1ne) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: The updated version of the YAML test (2 of them specifically) show this.

**Review by alex-spies — APPROVED** [review]
LGTM, thank you!

**Review by astefan — APPROVED** [review]
LGTM
