### PR TITLE
EQL: Fix management of PIT close failures after successful query

### LINKED ISSUE #146187: EqlCcsRollingUpgradeIT failing
### CI Link

https://gradle-enterprise.elastic.co/s/e7v4h7g46lcqe

### Repro line

`./gradlew ":x-pack:plugin:eql:qa:ccs-rolling-upgrade:v9.4.0#oldClusterTest" -Dtests.class="org.elasticsearch.xpack.eql.qa.ccs_rolling_upgrade.EqlCcsRollingUpgradeIT" -Dtests.method="testSequences" -Dtests.seed=F04C3EEA27AFD8DC -Dtests.bwc=true -Dtests.locale=en-AS -Dtests.timezone=Etc/GMT+12 -Druntime.java=25`

### Does it reproduce?

Yes

### Applicable branches

weiedly seems to mostly reproduce in PRs

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1776149999999&search.startTimeMin=1775458800000&search.timeZoneId=America%2FVancouver&tests.container=org.elasticsearch.xpack.eql.qa.ccs_rolling_upgrade.EqlCcsRollingUpgradeIT&tests.test=testSequences#

### Failure excerpt

See https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1776149999999&search.startTimeMin=1775458800000&search.timeZoneId=America%2FVancouver&tests.container=org.elasticsearch.xpack.eql.qa.ccs_rolling_upgrade.EqlCcsRollingUpgradeIT&tests.test=testSequences#. It seems to have started once 9.4 branch was created. Strangely enough it doesn't seem to reproduce on main but it is present across multiple PRs.

A node crashes during the test with:
```
[2026-04-13T20:26:26,132][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v9.4.0-local-0] fatal error in thread [elasticsearch[v9.4.0-local-0][search][T#3]], exiting
java.lang.AssertionError: java.lang.AssertionError: [org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener/org.elasticsearch.tasks.TaskManager$1{org.elasticsearch.rest.action.RestCancellableNodeClient$1@2ac9806f}{CancellableTask{Task{id=610, type='transport', action='indices:data/read/eql', description='indices[test_bwc_search_states_index,remote_cluster:test_bwc_search_states_remote_index], sequence [any where f == 2] [any where f == 36] ', parentTask=unset, startTime=1776111955690, headers={}, startTimeNanos=331719749862}, reason='http channel [Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:37773, remoteAddress=/[0:0:0:0:0:0:0:1]:47568}] closed', isCancelled=true}}/org.elasticsearch.action.support.TransportAction$$Lambda/0x000000007c7823a0@2c18da4a]
	at org.elasticsearch.action.ActionListener$3.assertFirstRun(ActionListener.java:423) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:441) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:282) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.eql.execution.PlanExecutor.lambda$eql$0(PlanExecutor.java:80) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:282) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:442) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:235) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:360) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:442) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.TransportClosePointInTimeAction$1.onFailure(TransportClosePointInTimeAction.java:96) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.transport.RemoteClusterService.collectNodes(RemoteClusterService.java:463) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.TransportClosePointInTimeAction.closeContexts(TransportClosePointInTimeAction.java:84) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.TransportClosePointInTimeAction.doExecute(TransportClosePointInTimeAction.java:59) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.TransportClosePointInTimeAction.doExecute(TransportClosePointInTimeAction.java:34) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:135) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:54) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.MappedActionFilters$MappedFilterChain.proceed(MappedActionFilters.java:71) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.MappedActionFilters.apply(MappedActionFilters.java:49) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.TransportAction.handleExecution(TransportAction.java:96) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:59) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:217) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:107) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:85) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:160) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:57) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.ParentTaskAssigningClient.doExecute(ParentTaskAssigningClient.java:66) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:160) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.eql.execution.search.PITAwareQueryClient.close(PITAwareQueryClient.java:160) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.lambda$execute$1(TumblingWindow.java:164) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:314) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:432) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.doPayload(TumblingWindow.java:761) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.lambda$payload$16(TumblingWindow.java:752) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.checkMissingEvents(TumblingWindow.java:225) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.payload(TumblingWindow.java:752) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.completeBaseCriterion(TumblingWindow.java:504) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.baseCriterion(TumblingWindow.java:440) ~[?:?]
	at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.lambda$advance$6(TumblingWindow.java:382) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.eql.execution.search.RuntimeUtils.lambda$searchLogListener$0(RuntimeUtils.java:73) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.eql.execution.search.PITAwareQueryClient.lambda$pitListener$3(PITAwareQueryClient.java:127) ~[?:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:274) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:432) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:223) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:217) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:350) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:432) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.TransportSearchAction$SearchTelemetryListener.onResponse(TransportSearchAction.java:2652) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.TransportSearchAction$SearchTelemetryListener.onResponse(TransportSearchAction.java:2575) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:350) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:432) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:405) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:612) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.sendSearchResponse(SearchQueryThenFetchAsyncAction.java:84) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchLookupFieldsPhase.sendResponse(FetchLookupFieldsPhase.java:147) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:81) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:391) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:385) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:185) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:70) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:391) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:385) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:274) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRunFetch$1(FetchSearchPhase.java:142) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:41) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:60) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:231) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase.executeFetch(FetchSearchPhase.java:245) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase.innerRunFetch(FetchSearchPhase.java:162) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:118) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:83) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1114) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[?:?]
	at java.lang.Thread.run(Thread.java:1474) ~[?:?]
Caused by: java.lang.AssertionError: [org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener/org.elasticsearch.tasks.TaskManager$1{org.elasticsearch.rest.action.RestCancellableNodeClient$1@2ac9806f}{CancellableTask{Task{id=610, type='transport', action='indices:data/read/eql', description='indices[test_bwc_search_states_index,remote_cluster:test_bwc_search_states_remote_index], sequence [any where f == 2] [any where f == 36] ', parentTask=unset, startTime=1776111955690, headers={}, startTimeNanos=331719749862}, reason='http channel [Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:37773, remoteAddress=/[0:0:0:0:0:0:0:1]:47568}] closed', isCancelled=true}}/org.elasticsearch.action.support.TransportAction$$Lambda/0x000000007c7823a0@2c18da4a]
	... 102 more
Caused by: org.elasticsearch.ElasticsearchException: executed already
	at org.elasticsearch.action.ActionListener$3.assertFirstRun(ActionListener.java:422) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:430) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.eql.plugin.TransportEqlSearchAction.lambda$operation$2(TransportEqlSearchAction.java:281) ~[?:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:274) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:274) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:312) ~[elasticsearch-9.5.0-SNAPSHOT.jar:?]
	... 49 more

```

### LINKED ISSUE #146263: [CI] EqlCcsRollingUpgradeIT testSequences failing
**Build Scans:**
- [elasticsearch-intake #37491 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/64x5fal55lhso)
- [elasticsearch-pull-request #137077 / 9.4.0_part_5_bwc-snapshots](https://gradle-enterprise.elastic.co/s/hoah2vc5omile)
- [elasticsearch-pull-request #137077 / 9.4.0_part_5_bwc-snapshots](https://gradle-enterprise.elastic.co/s/qvmwrfjoyawdc)
- [elasticsearch-intake #37490 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/xsjjiikldeia6)
- [elasticsearch-intake #37488 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ocywpkowey6uu)
- [elasticsearch-pull-request #137071 / 9.4.0_part_4_bwc-snapshots](https://gradle-enterprise.elastic.co/s/x4qonlmkaaln2)
- [elasticsearch-pull-request #137062 / 9.4.0_part_5_bwc-snapshots](https://gradle-enterprise.elastic.co/s/wpzwidyqxqrg4)
- [elasticsearch-pull-request #137061 / 9.4.0_part_4_bwc-snapshots](https://gradle-enterprise.elastic.co/s/3okj5xn4vdhng)
- [elasticsearch-pull-request #137066 / 9.4.0_part_4_bwc-snapshots](https://gradle-enterprise.elastic.co/s/jtkzvrnwynjdq)
- [elasticsearch-pull-request #137055 / 9.4.0_part_4_bwc-snapshots](https://gradle-enterprise.elastic.co/s/opil3ntj3kq7i)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:eql:qa:ccs-rolling-upgrade:v9.4.0#oldClusterTest" -Dtests.class="org.elasticsearch.xpack.eql.qa.ccs_rolling_upgrade.EqlCcsRollingUpgradeIT" -Dtests.method="testSequences" -Dtests.seed=CA18E5E015A91D40 -Dtests.bwc=true -Dtests.locale=nso-Latn-ZA -Dtests.timezone=Europe/Bucharest -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.eql.qa.ccs_rolling_upgrade.EqlCcsRollingUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSequences'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.io.UncheckedIOException: java.net.SocketTimeoutException: 30 000 milliseconds timeout on connection http-outgoing-5 [ACTIVE]
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testSequences
- [main] 1 consecutive failures in step 9.4.0_bwc-snapshots
- [main] 2 consecutive failures in step 9.4.0_part_5_bwc-snapshots
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 1 consecutive failures in pipeline elasticsearch-pull-request
- [main] 30 failures in test testSequences (3.0% fail rate in 1000 executions)
- [main] 3 failures in step 9.4.0_bwc-snapshots (50.0% fail rate in 6 executions)
- [main] 13 failures in step 9.4.0_part_5_bwc-snapshots (40.6% fail rate in 32 executions)
- [main] 14 failures in step 9.4.0_part_4_bwc-snapshots (42.4% fail rate in 33 executions)
- [main] 3 failures in pipeline elasticsearch-intake (50.0% fail rate in 6 executions)
- [main] 14 failures in pipeline elasticsearch-pull-request (50.0% fail rate in 28 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/146187
Fixes: https://github.com/elastic/elasticsearch/issues/146263

Better PIT close failure handling after a successful sequence/sample query execution.

When the query is executed successfully, the listener is notified with `onSuccess()`, that cleans up the session and closes PIT. 
At this point, in case of PIT close failure, the `onFailure()` got propagated to the listener (again), that tripped [the assertion](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/ActionListener.java#L441) because it was already executed.
There is not much we can do at this point, so we'll just log the failure.

We got a similar case in the past, see https://github.com/elastic/elasticsearch/pull/124918

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sample/SampleIterator.java [hunk 1]
```diff
@@ -118,7 +118,8 @@ public void execute(ActionListener<Payload> listener) {
             stack.clear();
             samples.clear();
             clearCircuitBreaker();
-            client.close(listener.delegateFailure((l, r) -> {}));
+            // The outer listener has already been invoked by runAfter; a close-PIT failure must not propagate to it.
+            client.close(ActionListener.wrap(r -> {}, e -> log.warn("Failed to close PIT", e)));
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sample/SampleIterator.java:122]:
```suggestion
            client.close(ActionListener.wrap(r -> {}, e -> log.warn("Failed to close PIT after sample query", e)));
```

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sequence/TumblingWindow.java [hunk 2]
```diff
@@ -161,7 +161,8 @@ public void execute(ActionListener<Payload> listener) {
         // clear the memory at the end of the algorithm
         tumbleWindow(matcher.firstPositiveStage, runAfter(listener, () -> {
             matcher.clear();
-            client.close(listener.delegateFailure((l, r) -> {}));
+            // The outer listener has already been invoked by runAfter; a close-PIT failure must not propagate to it.
+            client.close(ActionListener.wrap(r -> {}, e -> log.warn("Failed to close PIT", e)));
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/sequence/TumblingWindow.java:165]:
```suggestion
            client.close(ActionListener.wrap(r -> {}, e -> log.warn("Failed to close PIT after sequence query", e)));
```

**Review by astefan — APPROVED** [review]
LGTM. Left two optional suggestions regarding the actual WARN messages.
One more suggestion for testing completeness: would be great to add a test for the double-failure scenario (query fails AND close fails). The old code would have called `listener.onFailure()` twice in this case too. Consider adding a test where `query()` calls `l.onFailure(...)` and `close()` also calls `closed.onFailure(...)`, asserting `failures == 1`.
