### PR TITLE
Relax restrictions on filesystem size reporting in DiskUsage

### LINKED ISSUE #9249: Elastic search 1.4.2 data path issue
I am using UNC path to store the data eg: \pc1\data.
This works perfect in version 1.3.4 but after I upgrade it to 1.3.7 or 1.4.2 it started give me error

Below is the error log

[2015-01-12 16:03:33,087][INFO ][node ] [master1] version[1.3.7], pid[7068], build[3042293/2014-12-16T13:59:32Z]
[2015-01-12 16:03:33,087][INFO ][node ] [master1] initializing ...
[2015-01-12 16:03:33,102][INFO ][plugins ] [master1] loaded [], sites []
[2015-01-12 16:03:36,249][INFO ][node ] [master1] initialized
[2015-01-12 16:03:36,249][INFO ][node ] [master1] starting ...
[2015-01-12 16:03:36,514][INFO ][transport ] [master1] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.2.101:9300]}
[2015-01-12 16:03:36,795][INFO ][discovery ] [master1] local1/xBx3MDWZT--1dKhACi3KSA
[2015-01-12 16:03:39,844][INFO ][cluster.service ] [master1] new_master [master1][xBx3MDWZT--1dKhACi3KSA][dell13][inet[/192.168.2.101:9300]]{master=true}, reason: zen-disco-join (elected_as_master)
[2015-01-12 16:03:39,901][INFO ][http ] [master1] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.2.101:9200]}
[2015-01-12 16:03:39,901][INFO ][node ] [master1] started
[2015-01-12 16:03:39,964][INFO ][gateway ] [master1] recovered [0] indices into cluster_state
[2015-01-12 16:04:09,878][DEBUG][action.admin.cluster.node.stats] [master1] failed to execute on node [xBx3MDWZT--1dKhACi3KSA]
java.lang.IllegalStateException: Free bytes [-1] cannot be less than 0 or greater than total bytes [-1]
at org.elasticsearch.cluster.DiskUsage.(DiskUsage.java:32)
at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:279)
at org.elasticsearch.cluster.InternalClusterInfoService$ClusterInfoUpdateJob$1.onResponse(InternalClusterInfoService.java:260)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.finishHim(TransportNodesOperationAction.java:221)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.onOperation(TransportNodesOperationAction.java:196)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.access$900(TransportNodesOperationAction.java:96)
at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$2.run(TransportNodesOperationAction.java:140)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

### PR DESCRIPTION
**Pull request by dakrone**
Apparently some filesystems such as ZFS and occasionally NTFS can report
filesystem usages that are negative, or above the maximum total size of
the filesystem. This relaxes the constraints on `DiskUsage` so that an
exception is not thrown.

If 0 is passed as the totalBytes, 1 is used to avoid a division-by-zero
error.

Fixes #9249
Relates to #9260

### CODE REVIEW

**Comment by dakrone** [comment]
@bleskes I changed this based on our conversation, I think for now the best thing is to not change any of the settings, and program around the divide-by-zero for percentages.

I think logging the invalid values will move to #8686

File: src/main/java/org/elasticsearch/cluster/DiskUsage.java [hunk 1]
```diff
@@ -31,20 +31,30 @@
     final long totalBytes;
     final long freeBytes;
 
+    /**
+     * Create a new DiskUsage, if {@code totalBytes} is 0, 1 is used to avoid
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/cluster/DiskUsage.java]: I think this comment is no longer true?

File: src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java [hunk 2]
```diff
@@ -519,6 +519,9 @@ public Decision canRemain(ShardRouting shardRouting, RoutingNode node, RoutingAl
      * @return DiskUsage representing given node using the average disk usage
      */
     public DiskUsage averageUsage(RoutingNode node, Map<String, DiskUsage> usages) {
+        if (usages.size() == 0) {
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java]: I believe there is no test for this. Might be worth while adding.

File: src/test/java/org/elasticsearch/cluster/DiskUsageTests.java [hunk 3]
```diff
@@ -34,6 +34,23 @@ public void diskUsageCalcTest() {
         assertThat(du.getUsedBytes(), equalTo(60L));
         assertThat(du.getTotalBytes(), equalTo(100L));
 
+        DiskUsage du2 = new DiskUsage("node1", "n1", 100, 101);
```
Comment (bleskes) [inline src/test/java/org/elasticsearch/cluster/DiskUsageTests.java]: maybe add a comment about why we do these weird tests?

File: src/main/java/org/elasticsearch/cluster/DiskUsage.java [hunk 4]
```diff
@@ -31,20 +31,30 @@
...
+    }
+
+    public String getNodeName() {
+        return nodeName;
     }
 
     public double getFreeDiskAsPercentage() {
-        double freePct = 100.0 * ((double)freeBytes / totalBytes);
-        return freePct;
+        if (totalBytes == 0) {
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/cluster/DiskUsage.java]: maybe add a comment why we interpret totalBytes =0 as all free?

**Comment by bleskes** [comment]
LGTM. Left some cosmetic comments , mostly around comments to explain the edge cases this covers.
