### PR TITLE
[ES|QL] Create Range in PushFiltersToSource for qualified pushable filters on the same field

### LINKED ISSUE #108525: [CI] LogicalPlanOptimizerTests testSimplifyComparisonArithmeticWithDisjunction failing
I haven't investigated this one yet.  There are several other issues around how this optimization works, and it's possible fixing one of them will fix this test.

**Build scan:**
https://gradle-enterprise.elastic.co/s/zn7kv6lwmdrow/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests/testSimplifyComparisonArithmeticWithDisjunction

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests.testSimplifyComparisonArithmeticWithDisjunction" -Dtests.seed=A8AF70E4F3429963 -Dtests.locale=zh-TW -Dtests.timezone=Asia/Chungking -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests#testSimplifyComparisonArithmeticWithDisjunction`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testSimplifyComparisonArithmeticWithDisjunction'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: Expected filter condition to be a binary comparison but found [12 * (-integer - 5) >= -120 OR integer < 5]

  at __randomizedtesting.SeedInfo.seed([A8AF70E4F3429963:7A91B4839C45DBAE]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.assertTrue(Assert.java:42)
  at org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests.extractPlannedBinaryComparison(LogicalPlanOptimizerTests.java:4405)
  at org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests.extractPlannedBinaryComparison(LogicalPlanOptimizerTests.java:4397)
  at org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests.doTestSimplifyComparisonArithmetics(LogicalPlanOptimizerTests.java:4418)
  at org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests.testSimplifyComparisonArithmeticWithDisjunction(LogicalPlanOptimizerTests.java:4512)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
This is a follow up PR to #110548.

`CombineBinaryComparisons` was added without Range by #110548. 

The original `CombineBinaryComparisons` in `SQL` can create a `Range` expression from `>`, `>=`, `<` and `<=` that are on the same fields. However, as `Range` is not a `supported` operator in `ES|QL` yet, adding `Range` in the logical plan may break BWC #111255, as nodes on older versions don't know about this new internal operator.

This PR creates `Range` in the local physical plan rule `PushFiltersToSource` in stead, and it only happens to predicates that can be pushed down into the ES query, so that the the `>`, `>=`, `<` and `<=` predicates on the same field  can be combined and pushed down, and less predicates are pushed down into ES query.

### CODE REVIEW

**Comment by fang-xing-esql** [comment]
Close this for now, we can revisit when we want to add Range as an external operator.

**Comment by astefan** [comment]
Could you, please, update this PR with latest from `main`? It has, I think, unnecessary code (CombineBinaryComparisons for example). Thanks

**Comment by fang-xing-esql** [comment]
> Could you, please, update this PR with latest from `main`? It has, I think, unnecessary code (CombineBinaryComparisons for example). Thanks

Done, thanks for reminding!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java [hunk 1]
```diff
@@ -67,14 +69,22 @@
 import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.versionToString;
 
 public final class EsqlExpressionTranslators {
+
+    public static Object valueOf(Expression e) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java:73]: Should we use `org.elasticsearch.xpack.esql.core.expression.Foldables.valueOf`?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizer.java [hunk 2]
```diff
@@ -276,6 +284,81 @@ protected PhysicalPlan rule(FilterExec filterExec, LocalPhysicalOptimizerContext
...
+                } else {
+                    others.add(e);
+                }
+            });
+
+            for (int i = 0, step = 1; i < bcs.size() - 1; i += step, step = 1) {
+                BinaryComparison main = bcs.get(i);
+                if (main.right().foldable() == false) {
+                    continue;
+                }
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizer.java:305]: should this check (and the similar one below) be moved into the way `bcs` list is built above? Those with non-foldable right()s won't be combined.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java [hunk 3]
```diff
@@ -453,12 +463,91 @@ private static Query translate(In in, TranslatorHandler handler) {
...
+                if (lower instanceof ZonedDateTime || lower instanceof OffsetTime) {
+                    lower = formatter.format((TemporalAccessor) lower);
+                }
+                if (upper instanceof ZonedDateTime || upper instanceof OffsetTime) {
+                    upper = formatter.format((TemporalAccessor) upper);
+                }
+                format = formatter.pattern();
+            }
+
+            if (DataType.isDateTime(r.value().dataType())
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java:505]: This might be lifted code, but even then it might be good to extract `r.value().dataType()` into a var, for better readability.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:1]: Hmm, I guess we didn't have any teste mixing inequalities including the limit. (like `> && <=` or the other way around). Might be good to cover that too.

**Review by bpintea — APPROVED** [review]
Left some notes, but LGTM otherwise.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java:73]: Yeah, I'm surprised that we have more than one valuesOf :-), one is enough, will call `Foldables`.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:1]: We have < f <, <= f <=, we don't have <= f <, < f <= yet, will add them.

**Review by alex-spies — COMMENTED** [review]
Since we now push down some queries very differently to Lucene, can we add an integration test that runs a query where we expect a range query to be pushed down, and parameterize that so that all kinds of generated range queries and all applicable data types are tested?

That's a bit paranoid, but the unit tests don't guard against a translated query being rejected by Lucene (for whatever reason - maybe there are weird interactions with SingleValueQuery or other things we didn't take into account).

**Review by astefan — COMMENTED** [review]
Explore the use cases where different timezones and different formats are used in either the indexed values, the Literal values or both. Add tests for these.

**Comment by fang-xing-esql** [comment]
> Since we now push down some queries very differently to Lucene, can we add an integration test that runs a query where we expect a range query to be pushed down, and parameterize that so that all kinds of generated range queries and all applicable data types are tested?
> 
> That's a bit paranoid, but the unit tests don't guard against a translated query being rejected by Lucene (for whatever reason - maybe there are weird interactions with SingleValueQuery or other things we didn't take into account).

We have some CsvTests(30ish, perhaps half of them are in bucket, and half spread out in other files) that have a variety of data types with <, <=, >=, >, if the `RangQuery` generated are wrong, they fail at single-node check.

**Comment by alex-spies** [comment]
> > Since we now push down some queries very differently to Lucene, can we add an integration test that runs a query where we expect a range query to be pushed down, and parameterize that so that all kinds of generated range queries and all applicable data types are tested?
> > That's a bit paranoid, but the unit tests don't guard against a translated query being rejected by Lucene (for whatever reason - maybe there are weird interactions with SingleValueQuery or other things we didn't take into account).
> 
> We have some CsvTests(30ish, perhaps half of them are in bucket, and the other half spread out in other files) that have a variety of data types with <, <=, >=, >, if the `RangQuery`s generated are wrong, they fail at single-node check.

The tests in `bucket.csv-spec` only include date time ranges. I went over `ip.csv-spec` and didn't find any ip range in a `WHERE` clause, and similarly for `unsigned-long.csv-spec`, so I think at least `ip` and `unsigned_long` aren't integration tested. `version.csv-spec` has one range ` WHERE version >= to_ver("1.10") AND version <= to_ver("5.2.9")` but the code for versions has two cases, one for `Version` type literals and one for `BytesRef`, which I also cannot find tests for (ok, for the last one another test case in the `QueryTranslatorTests` is maybe more appropriate). Additionally, the tests in `bucket.csv-spec` use a dataset that only has single values, so there's no test that guarantees that the SingleValueQuery is working correctly in conjunction with the range queries we send to Lucene.

I realize this is a bit paranoid, but I would be more confident if we had a single integration test that exercised all supported data types (that includes non-ESQL types like `byte`, which we widen to `integer`) and maybe included some multivalues in the data set.

When I was working on edge cases with binary comparisons in Lucene, I added [RestEsqlTestCase.testOutOfRangeComparisons](https://github.com/elastic/elasticsearch/blob/9185056efe15eb1d06a3de04548cf40c904c2f50/x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java#L371), so there's already a little bit of infrastructure in place to create documents of different (supported) data types.

**Comment by astefan** [comment]
Agree with @alex-spies here on the "paranoid" aspect. Let's have more tests, if we have good ideas for test coverage. We lack many scenarios with different data types, with these suggestions we are progressing a little towards completeness.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java [hunk 4]
```diff
@@ -453,12 +457,90 @@ private static Query translate(In in, TranslatorHandler handler) {
...
+            Object upper = valueOf(r.upper());
+            String format = null;
+
+            // for a date constant comparison, we need to use a format for the date, to make sure that the format is the same
+            // no matter the timezone provided by the user
+            DateFormatter formatter = null;
+            if (lower instanceof ZonedDateTime || upper instanceof ZonedDateTime) {
+                formatter = DEFAULT_DATE_TIME_FORMATTER;
+            } else if (lower instanceof OffsetTime || upper instanceof OffsetTime) {
+                formatter = HOUR_MINUTE_SECOND;
```
[the remark this answers is not in the document]
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsqlExpressionTranslators.java:484]: > I think ESQL always encodes datetimes as longs
> I still think the code in lines 481-497 is dead and doesn't apply to ESQL.

👍

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizer.java [hunk 5]
```diff
@@ -277,6 +285,79 @@ protected PhysicalPlan rule(FilterExec filterExec, LocalPhysicalOptimizerContext
...
+                        others.add(e);
+                    }
+                } else {
+                    others.add(e);
+                }
+            });
+
+            for (int i = 0, step = 1; i < bcs.size() - 1; i += step, step = 1) {
+                BinaryComparison main = bcs.get(i);
+                for (int j = i + 1; j < bcs.size(); j++) {
```
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizer.java:308]: Yeah, logical planner can combine redundant <, <=, > and >=.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java [hunk 6]
```diff
@@ -102,54 +103,77 @@ public void testBinaryComparisons() {
...
+            FROM test | WHERE 10 < integer OR integer <= 12""", matchesRegex("""
+            .*should.*""" + """
+            esql_single_value":\\{"field":"integer".*"range":\\{"integer":\\{"gt":10,.*""" + """
+            esql_single_value":\\{"field":"integer".*"range":\\{"integer":\\{"lte":12.*"""));
+
+        assertQueryTranslation("""
+            FROM test | WHERE 10 <= integer OR integer <= 12""", matchesRegex("""
+            .*should.*""" + """
+            esql_single_value":\\{"field":"integer".*"range":\\{"integer":\\{"gte":10,.*""" + """
+            esql_single_value":\\{"field":"integer".*"range":\\{"integer":\\{"lte":12.*"""));
```
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:129]: Right, we don't have a rule to prune this kind of predicates as of now, could be a candidate for the future.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java [hunk 7]
```diff
@@ -102,54 +103,77 @@ public void testBinaryComparisons() {
...
+
+        // ANDs
+        assertQueryTranslation("""
+            FROM test | WHERE 10 < integer AND integer < 12""", containsString("""
+            "esql_single_value":{"field":"integer","next":{"range":{"integer":{"gt":10,"lt":12,"time_zone":"Z","boost":1.0}}}"""));
```
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:134]: This is left here just in case we want to support timezone in the future.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java [hunk 8]
```diff
@@ -102,54 +103,77 @@ public void testBinaryComparisons() {
...
+            "esql_single_value":{"field":"unsigned_long","next":{"range":{"unsigned_long":{"gt":2147483648,\
+            "lt":2147483650,"time_zone":"Z","boost":1.0}}}"""));
+
+        assertQueryTranslation(
+            """
+                FROM test | WHERE 2147483648::unsigned_long <= unsigned_long AND unsigned_long <= 2147483650::unsigned_long""",
+            containsString("""
+                "esql_single_value":{"field":"unsigned_long","next":{"range":{"unsigned_long":{"gte":2147483648,\
+                "lte":2147483650,"time_zone":"Z","boost":1.0}}}""")
+        );
```
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:177]: `CombineBinaryComparisonsTests` covers a lot of similar scenarios, I'll add some more complicated test cases in `QueryTranslatorTests`.

**Comment by fang-xing-esql** [comment]
> > > Since we now push down some queries very differently to Lucene, can we add an integration test that runs a query where we expect a range query to be pushed down, and parameterize that so that all kinds of generated range queries and all applicable data types are tested?
> > > That's a bit paranoid, but the unit tests don't guard against a translated query being rejected by Lucene (for whatever reason - maybe there are weird interactions with SingleValueQuery or other things we didn't take into account).
> > 
> > 
> > We have some CsvTests(30ish, perhaps half of them are in bucket, and the other half spread out in other files) that have a variety of data types with <, <=, >=, >, if the `RangQuery`s generated are wrong, they fail at single-node check.
> 
> The tests in `bucket.csv-spec` only include date time ranges. I went over `ip.csv-spec` and didn't find any ip range in a `WHERE` clause, and similarly for `unsigned-long.csv-spec`, so I think at least `ip` and `unsigned_long` aren't integration tested. `version.csv-spec` has one range ` WHERE version >= to_ver("1.10") AND version <= to_ver("5.2.9")` but the code for versions has two cases, one for `Version` type literals and one for `BytesRef`, which I also cannot find tests for (ok, for the last one another test case in the `QueryTranslatorTests` is maybe more appropriate). Additionally, the tests in `bucket.csv-spec` use a dataset that only has single values, so there's no test that guarantees that the SingleValueQuery is working correctly in conjunction with the range queries we send to Lucene.
> 
> I realize this is a bit paranoid, but I would be more confident if we had a single integration test that exercised all supported data types (that includes non-ESQL types like `byte`, which we widen to `integer`) and maybe included some multivalues in the data set.
> 
> When I was working on edge cases with binary comparisons in Lucene, I added [RestEsqlTestCase.testOutOfRangeComparisons](https://github.com/elastic/elasticsearch/blob/9185056efe15eb1d06a3de04548cf40c904c2f50/x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java#L371), so there's already a little bit of infrastructure in place to create documents of different (supported) data types.

Thanks for double checking😃! I'll add tests in each `csv-spec` if it is missing, and also add it into `RestEsqlTestCase`.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:134]: That's not wrong, but the time zone is not relevant to the integer range that this is testing, no?

Anyway, that should probably be an optional nitpick if anything.

[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/planner/QueryTranslatorTests.java:134]: I didn't catch that first time I looked at the comment. That's a good point.

**Review by astefan — COMMENTED** [review]
Thank you for adding more tests.
One is missing though. And I really don't think this is an edge case, there are many users who use custom date formats and timezones are omnipresent.

To give you a concrete example:
- mapping using

```
            "date": {
                "type": "date",
                "format": "dd-MM-yyyy-MM-dd HH:mm Z"
            },
            "date2": {
                "type": "date"
            }
```

```
{"index":{"_index":"test"}}
{"date":"12-01-1981-01-12 15:00 +0000", "date2":"2000"}
{"index":{"_index":"test"}}
{"date":"31-12-1999-12-31 23:59 +0300"}
{"index":{"_index":"test"}}
{"date":"31-12-1999-12-31 23:59 -0300"}
```

And a simple query like `from test | where date > "2000" or date2 >= "2000"`.
I _think_ this one can be an yaml test...

**Comment by fang-xing-esql** [comment]
> omnipresent

Thanks for sharing the example @astefan! I was looking for existing tests with different datetime formats, that I can borrow and add, but I didn't have luck finding any yet, perhaps I didn't look at the right place. I'll add the two you suggested.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java [hunk 9]
```diff
@@ -440,6 +440,38 @@ public void testOutOfRangeComparisons() throws IOException {
...
+        String predicate = "{}" + upperBound + "{} and {}" + lowerBound + "{} and {} != {}";
+
+        List<String> predicates = List.of(
+            format(null, predicate, "integer", NUM_SINGLE_VALUE_ROWS + 1, "integer", -1, "integer", -1),
+            format(null, predicate, "long", NUM_SINGLE_VALUE_ROWS + 1, "long", -1, "long", -1),
+            format(null, predicate, "double", NUM_SINGLE_VALUE_ROWS + 1.0, "double", -1.0, "double", -1),
+            format(null, predicate, "date", "\"9999-12-31\"", "date", "\"1001-01-01\"", "date", "\"1000-01-01\""),
+            format(null, predicate, "keyword", "\"l\"", "keyword", "\"j\"", "keyword", "\"a\""),
+            format(null, predicate, "ip", "\"128.0.0.0\"", "ip", "\"126.0.0.0\"", "ip", "\"129.0.0.0\""),
+            format(null, predicate, "version", "\"2\"", "version", "\"1\"", "version", "\"0\"")
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:459]: nit: there's other data types we could easily include, like byte, short, scaled float, half float, float, unsigned long. C.f. [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-limitations.html) for the (officially) supported types.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java [hunk 10]
```diff
@@ -440,6 +440,38 @@ public void testOutOfRangeComparisons() throws IOException {
         }
     }
 
+    public void testInternalRange() throws IOException {
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:443]: nit: maybe a comment to explain what we need this test for?

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java [hunk 11]
```diff
@@ -440,6 +440,38 @@ public void testOutOfRangeComparisons() throws IOException {
...
+        final int NUM_SINGLE_VALUE_ROWS = 100;
+        bulkLoadTestData(NUM_SINGLE_VALUE_ROWS);
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:445]: Suggestion: the test only creates single values, and the predicates are all trivial (i.e. we expect the filter to not filter out anything). I think it'd be more interesting if there was a couple of multivalued elements as well, and the predicate e.g. was true for something like half of them?

`testOutOfRangeComparisons` additionally creates some documents with MVs and nulls, which we could steal here.

**Review by alex-spies — APPROVED** [review]
Looks good to me! Thanks for the iterations @fang-xing-esql 

I only have a minor suggestion for making the integration test a bit more robust, and I think Andrei's suggestion is very valid about an IT with different date formatting.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java (hunk 11 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:447]: MVs and nulls are added.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java (hunk 9 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java]: More types are added.

**Comment by fang-xing-esql** [comment]
Thanks to @alex-spies and @astefan for reviewing! I think all of the comments are addresses, please just let me know if there is any missing.

**Review by astefan — APPROVED** [review]
Thank you @fang-xing-esql for addressing all the tests reviews, I know it's tedious and some tests might seem too much, but I believe in this way we start covering more and more mappings and use cases variations that are currently missing from ES|QL.

LGTM

**Review by alex-spies — APPROVED** [review]
This is great @fang-xing-esql , thank you for nicely polishing this and helping with our paranoia re. testing, haha :)
