### PR TITLE
[Transform] Reduce task match load

### LINKED ISSUE #139252: TransportGetTransformStatsAction can eat a transport thread, causing cluster instability
### Elasticsearch Version

_any_

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

Transform stats does a fair bit of work just sitting in `direct` executor. This is not good. Depending on the scale of the cluster, if multiple users call the stats call for transforms, it could disconnect node from a cluster.

We should:

1. Make this way way cheaper, only consider transform tasks (do filtering directly in tasks request, not after gathering all tasks on the node) and be careful about ginormous strings being created and concatenated
2. Consider moving this off of direct executor.

Some additional notes:

> This is 100% a bug that needs reporting to the transform (ML?) folks. We seem to be looping over all tasks, filtering them by description (not even filtering by action first??). Building the description of a single search task might not be too costly but isn't exactly free either, and building a description of them all could be very expensive, and even worse I'm pretty sure no search tasks could possibly have a matching description anyway. Moreover this is all happening on the transport_worker for no good reason and needs to be moved elsewhere as a matter of some urgency.

### Steps to Reproduce

Many nodes, many transforms == no fun for the cluster.

### Logs (if relevant)

Here are some hot threads from an example where this caused node disconnection:
```
:::
   Hot threads at 2025-12-03T11:34:21.188Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:
   
   100.7% [cpu=100.7%, idle=0.0%] (503.4ms out of 500ms) cpu usage by thread 'elasticsearch[instance-0000000385][transport_worker][T#15]'
     9/10 snapshots sharing following 110 elements
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.MultiSearchRequest$1.getDescription(MultiSearchRequest.java:398)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.lambda$match$0(GetTransformStatsAction.java:91)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request$$Lambda/0x000000003d7919b0.test(Unknown Source)
       java.base@24/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
       java.base@24/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
       java.base@24/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
       java.base@24/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
       java.base@24/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
       java.base@24/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
       java.base@24/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
       java.base@24/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:672)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.match(GetTransformStatsAction.java:91)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:229)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:209)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:264)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:258)
       org.elasticsearch.security@8.18.4/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       org.elasticsearch.security@8.18.4/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$2.onResponse(SecurityServerTransportInterceptor.java:616)
       org.elasticsearch.security@8.18.4/
[...]

unique snapshot
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.lambda$match$0(GetTransformStatsAction.java:91)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request$$Lambda/0x000000003d7919b0.test(Unknown Source)
       java.base@24/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
       java.base@24/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
       java.base@24/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
       java.base@24/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
       java.base@24/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
       java.base@24/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
       java.base@24/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
       java.base@24/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:672)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.match(GetTransformStatsAction.java:91)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:229)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:209)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:264)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:258)
       org.elasticsearch.security@8.18.4/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       org.elasticsearch.security@8.18.4/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$2.onResponse(SecurityServerTransportInterceptor.java:616)
       org.elasticsearch.security@8.18.4/
[...]

   100.7% [cpu=100.7%, idle=0.0%] (503.4ms out of 500ms) cpu usage by thread 'elasticsearch[instance-0000000385][transport_worker][T#22]'
     6/10 snapshots sharing following 117 elements
       java.base@24/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:247)
       java.base@24/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:591)
       java.base@24/java.lang.StringBuilder.append(StringBuilder.java:179)
       java.base@24/java.lang.StringBuilder.append(StringBuilder.java:173)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.common.Strings.arrayToDelimitedString(Strings.java:627)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchRequest.buildDescription(SearchRequest.java:777)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchRequest$$Lambda/0x000000003d084e68.get(Unknown Source)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchTask.getDescription(SearchTask.java:41)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.lambda$match$0(GetTransformStatsAction.java:91)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request$$Lambda/0x000000003d7919b0.test(Unknown Source)
       java.base@24/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
       java.base@24/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
       java.base@24/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
       java.base@24/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
       java.base@24/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
       java.base@24/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
       java.base@24/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
       java.base@24/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:672)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.match(GetTransformStatsAction.java:91)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:229)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:209)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:264)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:258)
       org.elasticsearch.security@8.18.4/
[...]

    4/10 snapshots sharing following 111 elements
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchRequest$$Lambda/0x000000003d084e68.get(Unknown Source)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchTask.getDescription(SearchTask.java:41)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.lambda$match$0(    4/10 snapshots sharing following 111 elements
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchRequest$$Lambda/0x000000003d084e68.get(Unknown Source)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.search.SearchTask.getDescription(SearchTask.java:41)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.lambda$match$0(GetTransformStatsAction.java:91)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request$$Lambda/0x000000003d7919b0.test(Unknown Source)
       java.base@24/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
       java.base@24/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
       java.base@24/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
       java.base@24/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
       java.base@24/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
       java.base@24/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
       java.base@24/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
       java.base@24/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:672)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.match(GetTransformStatsAction.java:91)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:229)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:209)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:264)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:258)
       org.elasticsearch.security@8.18.4/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579))
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request$$Lambda/0x000000003d7919b0.test(Unknown Source)
       java.base@24/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
       java.base@24/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
       java.base@24/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
       java.base@24/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
       java.base@24/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
       java.base@24/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
       java.base@24/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
       java.base@24/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
       java.base@24/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:672)
       org.elasticsearch.xcore@8.18.4/org.elasticsearch.xpack.core.transform.action.GetTransformStatsAction$Request.match(GetTransformStatsAction.java:91)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:229)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction.processTasks(TransportTasksAction.java:209)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:264)
       app/org.elasticsearch.server@8.18.4/org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:258)
       org.elasticsearch.security@8.18.4/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579)
[...]
```

### PR DESCRIPTION
**Pull request by prwhelan**
Move `TransportGetTransformStatsAction` to the management threadpool, and match `Task` based on java type first before comparing the description to prevent iterating over a large abount of transform ids for tasks that are not `TransformTask`.

Resolve #139252

-----------------------

This pattern copies what we had done for [GetJobsStatsAction](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetJobsStatsAction.java#L114)

If you commit this change before I return, please change the commit message to say `management threadpool` instead of `generic threadpool` please and thank you :)

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PutTransformAction.java [hunk 1]
```diff
@@ -165,4 +166,19 @@ public Task createTask(long id, String type, String action, TaskId parentTaskId,
         }
     }
 
+    public interface TransformTaskMatcher {
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PutTransformAction.java]: Why is this interface part of `PutTransformAction`? 

It seems like it equally belongs to all `*TransformAction` classes. I would pull it into its own file.

Comment (jan-elastic) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PutTransformAction.java]: Better question: why does this interface exist?

Anywhere where it's used like:
```
return PutTransformAction.TransformTaskMatcher.match(task, id);
```
you could easily instead do:
```
return task instanceof TransformTask transformTask && transFormTask.getTransformId().equals(id);
```

I think that's much cleaner.

Comment (jan-elastic) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PutTransformAction.java]: Oh wait, TransformTask is not available here due to packaging...

Comment (jan-elastic) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PutTransformAction.java]: I took to liberty to refactor a bit. The new implementation doesn't use string concatenation at all anymore. Let me know what you think.

**Review by jan-elastic — APPROVED** [review]
LGTM, but I've refactored a bit myself. Let me know what you think

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java [hunk 2]
```diff
@@ -672,4 +678,14 @@ private static Collection<PersistentTask<?>> findTransformTasks(Predicate<Persis
         }
         return pTasksMeta.findTasks(TransformTaskParams.NAME, predicate);
     }
+
+    @Override
+    public boolean match(String transformId) {
+        return Objects.equals(transform.getId(), transformId);
```
Comment (dan-rubinstein) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: We were previously checking if the `transformId` does not equal null. Why do we no longer need this check? Is there a case where the `transformId` and `transform.getId()` could both be null where this would return true but would previously return false?

This applies for both match functions.

Comment (dan-rubinstein) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: Just clarifying, we were previously checking whether the `transform.getDescription()` equals `TransformField.PERSISTENT_TASK_DESCRIPTION_PREFIX + transformId`. Are there any odd cases where the new check on transform ID would yield a different result? For example is there any reason why the description would have a transform ID that doesn't correspond to the transform's overall Id or includes it in a different form than `TransformField.PERSISTENT_TASK_DESCRIPTION_PREFIX + transformId`?

This applies for both match functions.

Comment (darius-vil) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: I was wondering the same, but looks like that prefix is enforced during TransformTask creation and as far as I can see it's the only way of creating a TransformTask: 
https://github.com/elastic/elasticsearch/blob/1f6311b1bfbb76eddd52e29fe929109683afeddc/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java#L90

So every TransformTask had that prefix anyway, meaning that extra prefix check after we check the type was redundant.

Comment (jan-elastic) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: The description is always `TransformField.PERSISTENT_TASK_DESCRIPTION_PREFIX + transform.getId()`, see
https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java#L90

Comment (dan-rubinstein) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: Yeah I only see it being set on creation in this one place, I just want to confirm we aren't somehow updating it elsewhere throughout the lifecycle of the transform? I don't believe so but maybe Jan can confirm this.

Comment (jan-elastic) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: A valid transform should always have non-null ID, see:
https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/utils/TransformStrings.java#L31

**Review by dan-rubinstein — APPROVED** [review]

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java (hunk 2 above)
Comment (darius-vil) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:684]: The description itself is `final` and I don't see any more changes to the description in TranformTask's parent constructors, it's just passed up all the way to the final fields, so I think we're safe here :)
