### PR TITLE
[ML] Refactor AutodetectMemoryLimitIT to use memory limit constants and improve model size assertions

### LINKED ISSUE #132310: [CI] AutodetectMemoryLimitIT testTooManyByAndOverFields failing
**Build Scans:**
- [elasticsearch-intake #26388 / part4](https://gradle-enterprise.elastic.co/s/xxfsfaql4aqt4)
- [elasticsearch-pull-request #83938 / part-4](https://gradle-enterprise.elastic.co/s/iwlagkovtqa4o)
- [elasticsearch-pull-request #83936 / part-4](https://gradle-enterprise.elastic.co/s/dkfw6rlr55y5g)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.AutodetectMemoryLimitIT.testTooManyByAndOverFields" -Dtests.seed=BB788BF0FC032CFB -Dtests.locale=ne-IN -Dtests.timezone=Chile/EasterIsland -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.AutodetectMemoryLimitIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTooManyByAndOverFields'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a value less than <72000000L>
     but: <72384512L> was greater than <72000000L>
```

**Issue Reasons:**
- [main] 3 failures in test testTooManyByAndOverFields (1.9% fail rate in 160 executions)
- [main] 2 failures in step part-4 (2.6% fail rate in 76 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 76 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132611: [CI] AutodetectMemoryLimitIT testTooManyPartitions failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9899 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/3im3cig6xzzn6)
- [elasticsearch-periodic-platform-support #9815 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/otvx7o3jwyebs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.AutodetectMemoryLimitIT.testTooManyPartitions" -Dtests.seed=F37F913239C5DEB6 -Dtests.locale=dsb-Latn-DE -Dtests.timezone=America/Anchorage -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.AutodetectMemoryLimitIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTooManyPartitions'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a value less than <50300000L>
     but: <50470912L> was greater than <50300000L>
```

**Issue Reasons:**
- [main] 2 failures in test testTooManyPartitions (0.3% fail rate in 617 executions)
- [main] 2 failures in step rocky-8_platform-support-unix (15.4% fail rate in 13 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by valeriy42**
Previously, the upper bound for model memory checks was set in absolute terms, which is not easy to understand and is brittle. I adjusted the assertions to ensure that the memory usage does not exceed 5% of the memory limit. Additionally, on Linux, we now report the process size (see #131981), which includes approximately 20 MB of native code overhead. I made handling this overhead more explicit. 

More details:
- Removed muted tests for `testManyDistinctOverFields` and `testTooManyByAndOverFields`.
- Introduced constants for memory limits in `AutodetectMemoryLimitIT`.
- Updated assertions to check effective model size against calculated limits.

Closes #132308
Closes #132310
Closes #132611

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 1]
```diff
@@ -34,12 +36,15 @@
...
 
+    private static final long PROCESS_OVERHEAD_BYTES = ByteSizeValue.ofMb(20).getBytes();
+
     @After
     public void cleanUpTest() {
         cleanUp();
     }
 
     public void testTooManyPartitions() throws Exception {
+        long memoryLimit = 30L;
```
Comment (jan-elastic) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: Could you rename this to `memoryLimitMb`? (everywhere)

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 2]
```diff
@@ -78,15 +83,22 @@ public void testTooManyPartitions() throws Exception {
         // Assert we haven't violated the limit too much
         GetJobsStatsAction.Response.JobStats jobStats = getJobStats(job.getId()).get(0);
         ModelSizeStats modelSizeStats = jobStats.getModelSizeStats();
-        assertThat(modelSizeStats.getModelBytes(), lessThan(50300000L));
-        assertThat(modelSizeStats.getModelBytes(), greaterThan(24000000L));
+
+        assertThat(
+            getEffectiveModelSize(modelSizeStats.getModelBytes()),
+            allOf(
+                greaterThan(ByteSizeValue.ofMb(memoryLimit).getBytes() * 0.15),
```
Comment (jan-elastic) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: Why such a low 15%?

The model is supposed to hit either the soft or hard limit, so I imagine the minimum should be a lot more.

Comment (jan-elastic) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: same for testTooManyByAndOverFields

**Review by jan-elastic — APPROVED** [review]
Generally look good. Some small comments.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java (hunk 1 above)
Comment (valeriy42) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: Renamed in aceba644

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java (hunk 2 above)
Comment (valeriy42) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: You are right. Actually, IMO, the lower bound test doesn't make any sense since we check for `hard_limit` and `soft_limit`  in the following step. Hence, I removed the lower bound assertion in aceba6441288b43018d9410e9f54c156fcc52009 to simplify the code.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 3]
```diff
@@ -26,20 +27,22 @@
...
 import static org.hamcrest.Matchers.equalTo;
-import static org.hamcrest.Matchers.greaterThan;
 import static org.hamcrest.Matchers.lessThan;
 
 /**
  * A set of tests that ensure we comply to the model memory limit
  */
 public class AutodetectMemoryLimitIT extends MlNativeAutodetectIntegTestCase {
 
+    private static final long PROCESS_OVERHEAD_BYTES = ByteSizeValue.ofMb(20).getBytes();
```
Comment (DonalEvans) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: Where is this value coming from?

Comment (valeriy42) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: This value is estimated empirically. I used a small, simple anomaly detection job with a trivial model to establish the lower bound on the process memory usage.

Comment (DonalEvans) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: Would it be helpful to add a comment explaining that? If there's a risk of that value changing at some point in the future, it would be good to know what needs to be do to recalculate and update it.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 4]
```diff
@@ -225,12 +229,12 @@ public void testManyDistinctOverFields() throws Exception {
         // Assert we haven't violated the limit too much
         GetJobsStatsAction.Response.JobStats jobStats = getJobStats(job.getId()).get(0);
         ModelSizeStats modelSizeStats = jobStats.getModelSizeStats();
-        assertThat(modelSizeStats.getModelBytes(), lessThan(120500000L));
-        assertThat(modelSizeStats.getModelBytes(), greaterThan(70000000L));
+        assertThat(getEffectiveModelSize(modelSizeStats.getModelBytes()), lessThan(ByteSizeValue.ofMb(memoryLimitMb).getBytes() * 1.05));
         assertThat(modelSizeStats.getMemoryStatus(), equalTo(ModelSizeStats.MemoryStatus.HARD_LIMIT));
```
Comment (valeriy42) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java:225]: The reporting of memory usage is different on different plattforms: on Linux and Windows we report actual process memory usage, while on MacOS this information is not available and hence we report estimated memory usage. This makes the test for a specific memory limit brittle. To improve robustness, I only check that the job is in the `hard_limit` state.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 5]
```diff
@@ -176,12 +180,12 @@ public void testTooManyByAndOverFields() throws Exception {
         // Assert we haven't violated the limit too much
         GetJobsStatsAction.Response.JobStats jobStats = getJobStats(job.getId()).get(0);
         ModelSizeStats modelSizeStats = jobStats.getModelSizeStats();
-        assertThat(modelSizeStats.getModelBytes(), lessThan(72000000L));
-        assertThat(modelSizeStats.getModelBytes(), greaterThan(24000000L));
+        assertThat(getEffectiveModelSize(modelSizeStats.getModelBytes()), lessThan(ByteSizeValue.ofMb(memoryLimitMb).getBytes() * 1.05));
         assertThat(modelSizeStats.getMemoryStatus(), equalTo(ModelSizeStats.MemoryStatus.HARD_LIMIT));
```
Comment (valeriy42) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java:177]: Only check if the job is in `hard_limit` state to increase test robustness on different plattforms

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 6]
```diff
@@ -78,15 +81,16 @@ public void testTooManyPartitions() throws Exception {
         // Assert we haven't violated the limit too much
         GetJobsStatsAction.Response.JobStats jobStats = getJobStats(job.getId()).get(0);
         ModelSizeStats modelSizeStats = jobStats.getModelSizeStats();
-        assertThat(modelSizeStats.getModelBytes(), lessThan(50300000L));
-        assertThat(modelSizeStats.getModelBytes(), greaterThan(24000000L));
+
+        assertThat(getEffectiveModelSize(modelSizeStats.getModelBytes()), lessThan(ByteSizeValue.ofMb(memoryLimitMb).getBytes() * 1.05));
         assertThat(
```
Comment (valeriy42) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java:81]: Only check for `hard_limit` to increase test robustness.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java [hunk 7]
```diff
@@ -125,12 +129,12 @@ public void testTooManyByFields() throws Exception {
         // Assert we haven't violated the limit too much
         GetJobsStatsAction.Response.JobStats jobStats = getJobStats(job.getId()).get(0);
         ModelSizeStats modelSizeStats = jobStats.getModelSizeStats();
-        assertThat(modelSizeStats.getModelBytes(), lessThan(45000000L));
-        assertThat(modelSizeStats.getModelBytes(), greaterThan(25000000L));
+        assertThat(getEffectiveModelSize(modelSizeStats.getModelBytes()), lessThan(ByteSizeValue.ofMb(memoryLimitMb).getBytes() * 1.05));
         assertThat(modelSizeStats.getMemoryStatus(), equalTo(ModelSizeStats.MemoryStatus.HARD_LIMIT));
```
Comment (valeriy42) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java:127]: Only check `hard_limit` for robustness.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java (hunk 3 above)
Comment (valeriy42) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/AutodetectMemoryLimitIT.java]: On the second though, checking if the autodetect process has a specific memory overhead make these tests unnecessary brittle. I removed it and only kept checking for `hard_limit`. In ml-cpp we have unit tests to ensure there are no memory leaks.
