### PR TITLE
Make FunctionScore work on unmapped field with `missing` parameter

### LINKED ISSUE #10948: Function score query fails with field_value_factor on not (yet) existing field
Hi,

My ES function score query contains several different functions based on a set of different fields. I'm having problems with field_value_factor on not existing fields. 
I'm not sure if that's expected behavior or a bug in ES. 
On the elasticsearch Google group, nobody had an idea, so any help is appreciated.

A minimal example on how to reproduce the problem:

Example document:
```
curl -XPOST "http://localhost:9200/blog/page/1?pretty" -d '
{
  "author": "tobias",
  "content": "Great",
  "views": 1
}'
```

A search request, that boosts based on the function score looks like that:
```
curl -XPOST "http://localhost:9200/blog/_search" -d '
{
  "query": {
    "function_score": {
      "functions": [
        {
          "field_value_factor": {
            "field": "views",
            "modifier": "log2p"
          }
        }
      ]
    }
  }
}'
```

Everything is fine until this point.
When I change the "field" param to "likes", the requests fails:
```
curl -XPOST "http://localhost:9200/blog/_search" -d '
{
  "query": {
    "function_score": {
      "functions": [
        {
          "field_value_factor": {
            "field": "likes",
            "modifier": "log2p"
          }
        }
      ]
    }
  }
}'
```
-> ``` ElasticsearchException[Unable to find a field mapper for field [likes]```

"likes" doesn't exist yet in the "page" document type, but it might exist in the future. Or there could be another type "page2", where the "likes" field exists, and I need to query both "page" and "page2" in 1 request.

What I tried, is to put an exist filter beforehand, however, the error remains the same.
```
curl -XPOST "http://localhost:9200/blog/_search" -d '
{
    "query": {
        "function_score": {
            "functions": [
                {
                    "filter": {
                        "exists": {
                            "field": "likes"
                        }
                    },
                    "field_value_factor": {
                        "field": "likes"
                    }
                }
            ]
        }
    }
}'
```
-> ```ElasticsearchException[Unable to find a field mapper for field [likes]```

Is this a bug or expected bahavior?
I would expect ES to just skip the function, in case the "exists" filter evaluates to False or the field doesn't exist. 

The error originates from ```FieldValueFactorFunctionParser.java``` (line 89), in ```FieldValueFactorFunctionParser.parse ```. 
Is there really a need to check for the existence of all fields during parsing? 

With other function types, there is no problem, so apparently this parsing is not performed. E.g. the following works without an error:
```
curl -XPOST "http://localhost:9200/blog/_search" -d '
{
  "query": {
    "function_score": {
      "functions": [
        {
            "filter": {
                "range": {"likes": {"from": 1}}
            }, 
            "weight": 1.5
        }
      ]
    }
  }
}'
```

Any ideas?

Please let me know, if you need further information.

Best regards,
Tobias

### PR DESCRIPTION
**Pull request by andrestc**
#10948: FunctionScore wont raise an exception if the field is not mapped and the user provided an 'missing' value.

P.S: Will greatly appreciate any feedback regarding my code, today is my first day trying to help the elasticsearch community. Thanks!

Closes #10948

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/lucene/search/function/FieldValueFactorFunction.java [hunk 1]
```diff
@@ -54,13 +54,24 @@ public FieldValueFactorFunction(String field, float boostFactor, Modifier modifi
 
     @Override
     public LeafScoreFunction getLeafScoreFunction(LeafReaderContext ctx) {
-        final SortedNumericDoubleValues values = this.indexFieldData.load(ctx).getDoubleValues();
+        final SortedNumericDoubleValues values;
+        if(indexFieldData == null) {
+            values = null;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/lucene/search/function/FieldValueFactorFunction.java]: can you do `values = FieldData. emptySortedNumericDoubles();` instead so that the LeafScoreFunction doesn't have to care about nulls?

**Comment by jpountz** [comment]
@andrestc I left a minor comment but otherwise I like the change.

**Comment by andrestc** [comment]
@jpountz There it is! Thanks for the feedback.

File: core/src/main/java/org/elasticsearch/common/lucene/search/function/FieldValueFactorFunction.java [hunk 2]
```diff
@@ -54,7 +55,13 @@ public FieldValueFactorFunction(String field, float boostFactor, Modifier modifi
 
     @Override
     public LeafScoreFunction getLeafScoreFunction(LeafReaderContext ctx) {
-        final SortedNumericDoubleValues values = this.indexFieldData.load(ctx).getDoubleValues();
+        final SortedNumericDoubleValues values;
+        if(indexFieldData == null) {
+            values = FieldData.emptySortedNumericDoubles(0);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/lucene/search/function/FieldValueFactorFunction.java]: you should pass ctx.reader().maxDoc() instead of 0 for things to work properly

**Comment by andrestc** [comment]
@jpountz Just pushed the change. Thanks

**Comment by jpountz** [comment]
Thanks @andrestc. I will merge next week when I'm back from traveling unless someone beats me to it.
