### PR TITLE
ESQL: Fix intermittently failing PowTest.testEvaluate {TestCase=pow(integer, double)}

### LINKED ISSUE #100915: [CI] PowTests testEvaluate {TestCase=pow(integer, double)} failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/e7hv5njjwerc2/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.expression.function.scalar.math.PowTests/testEvaluate%20%7BTestCase=pow(integer,%20double)%7D
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.math.PowTests.testEvaluate {TestCase=pow(integer, double)}" -Dtests.seed=7E2002F0042C5793 -Dtests.locale=mt-MT -Dtests.timezone=America/Bahia_Banderas -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.expression.function.scalar.math.PowTests&tests.test=testEvaluate%20%7BTestCase%3Dpow(integer,%20double)%7D
**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: not <Infinity>
     but: was <Infinity>

  at __randomizedtesting.SeedInfo.seed([7E2002F0042C5793:548D5D2CD86347C8]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.testEvaluate(AbstractFunctionTestCase.java:223)
  at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.testEvaluate(AbstractFunctionTestCase.java:191)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

...

  1> [2023-10-16T09:21:34,551][INFO ][o.e.x.e.e.f.s.m.PowTests ] [suite] Writing function types:
  1> [%header.monospaced.styled,format=dsv,separator=|]
  1> |===
  1> base | exponent | result
  1> integer | double | double
  1> |===

  1> [2023-10-16T09:21:34,750][INFO ][o.e.x.e.e.f.s.m.PowTests ] [suite] Writing function signature
  2> NOTE: leaving temporary files on disk at: /Users/chegar/git/elasticsearch/x-pack/plugin/esql/build/testrun/test/temp/org.elasticsearch.xpack.esql.expression.function.scalar.math.PowTests_7E2002F0042C5793-001
  2> java.lang.AssertionError: expected:<[double, integer, long]> but was:<[integer]>
        at __randomizedtesting.SeedInfo.seed([7E2002F0042C5793]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.testFunctionInfo(AbstractFunctionTestCase.java:514)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:909)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  ...

```

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit updates an incorrect PowTest scenario that depends on what randomisation input is generated.

Currently, the framework asserts that POSITIVE_INFINITY is never the expected result of an evaluate scenario, but POSITIVE_INFINITY is the exact expected result that is generated for a particular scenario. The randomisation bounds for the scenario allows a base of `0` and a negative exponent, which always results in POSITIVE_INFINITY. The fix here is to adjust the bounds for base to ensure that it is always >= 1.

closes #100915

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/PowTests.java [hunk 1]
```diff
@@ -185,8 +185,8 @@ public static Iterable<Object[]> parameters() {
                 )
             ),
             new TestCaseSupplier("pow(integer, double)", () -> {
-                // Negative numbers to a non-integer power are NaN
-                int base = randomIntBetween(0, 1000);
+                // Positive numbers to a non-integer power
+                int base = randomIntBetween(1, 1000);
```
Comment (ChrisHegarty) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/PowTests.java:189]: @not-napoleon @craigtaverner I could have interpreted the expectation of this scenario incorrectly. If so, then what is the intent, as the previous comment and code seem misaligned.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java [hunk 2]
```diff
@@ -220,7 +220,9 @@ private void testEvaluate(boolean readFloating) {
             }
         }
         assertThat(result, not(equalTo(Double.NaN)));
+        assert testCase.getMatcher().matches(Double.POSITIVE_INFINITY) == false;
         assertThat(result, not(equalTo(Double.POSITIVE_INFINITY)));
+        assert testCase.getMatcher().matches(Double.NEGATIVE_INFINITY) == false;
```
Comment (ChrisHegarty) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java:225]: These test-level assertions are not strictly necessary, but ensure that the testCase has not generated an unexpected matcher.

**Review by not-napoleon — APPROVED** [review]
I think this is fine for now. I have on my TODO list reworking Pow so it always returns a double, and will have to rewrite a bunch of tests then (also to use the new type coverage tools Nik added), but this fixes an immediate problem and is a tiny change, so I'm +1 on it.
