### PR TITLE
Fix not Recognizing Disabled Object Mapper

### LINKED ISSUE #39456: Allows to create indexed fields when setting enabled to false to the object field
**Elasticsearch version** (`bin/elasticsearch --version`):

~~~
Version: Tested 6.0 and 6.6
~~~

**Plugins installed**: none

**JVM version** (`java -version`):
~~~
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
~~~

**OS version** (`uname -a` if on a Unix-like system):

~~~
Darwin x.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
~~~

**Description of the problem including expected versus actual behavior**:
ES updates the mapping creating indexed fields where one should not when setting enabled to false property to the object field.

**Steps to reproduce**:

~~~
PUT my_index
{
 "mappings": {
   "_doc": {
     "properties": {
       "name": {
         "enabled": false
       }
     }
   }
 }
}

#the field is enabled - which is NOT the expected value
PUT my_index/_doc/1
{
 "name.first": "john"
}

GET my_index/_mapping
# response
{
  "my_index" : {
    "mappings" : {
      "_doc" : {
        "properties" : {
          "name" : {
            "enabled" : false,
            "properties" : {
              "first" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


DELETE my_index

PUT my_index
{
 "mappings": {
   "_doc": {
     "properties": {
       "name": {
         "enabled": false
       }
     }
   }
 }
}

#the field is not enabled - which is the expected value
PUT my_index/_doc/1
{
 "name": {
   "first": "john"
 }
}

GET my_index/_mapping
# response
{
  "my_index" : {
    "mappings" : {
      "_doc" : {
        "properties" : {
          "name" : {
            "type" : "object",
            "enabled" : false
          }
        }
      }
    }
  }
}
~~~

### PR DESCRIPTION
**Pull request by TommyWind**
* Fixes not finding disabled object mapper when using dotted field name
notation
* Closes #39456

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java [hunk 1]
```diff
@@ -79,6 +79,22 @@ public void testFieldDisabled() throws Exception {
         assertNotNull(doc.rootDoc().getField(IdFieldMapper.NAME));
     }
 
+    public void testDotsWithFieldDisabled() throws IOException {
+        DocumentMapperParser mapperParser = createIndex("test").mapperService().documentMapperParser();
+        String mapping = Strings.toString(jsonBuilder().startObject().startObject("type").startObject("properties")
+            .startObject("foo").field("enabled", false).endObject()
+            .endObject().endObject().endObject());
+        DocumentMapper mapper = mapperParser.parse("type", new CompressedXContent(mapping));
+        BytesReference bytes = BytesReference.bytes(jsonBuilder()
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java]: It would be great to test some other types as fields as well, such as array fields, since they go through a different parsing code path than simple values.

**Review by jtibshirani — COMMENTED** [review]
Hi @TommyWind, thank you for the PR! It’s great that it is a very focused change and that it's unit tested.

While I think this fix does work with the way parsing is currently structured, to me it is non-obvious and maybe fragile. The method contract for `getMapper` is to return the mapper for the given field, or null if no such mapper is defined. But after this change, the method might sometimes return a parent object mapper that lies on the field path. We then rely on `parseObjectOrField` always being called shortly after `getMapper`, so we can check if the returned object mapper is enabled.

I think it would be clearer to omit the change to `getMapper`, and instead create a separate method that iterates through each path segment and returns whether any object mapper is disabled. If there is a disabled mapper, then we can immediately skip further parsing for that field.

**Comment by TommyWind** [comment]
Thanks @jtibshirani for the review. :)

I added a few more test cases and changed the approach to check for disabled mappers higher up the stack. Take a look when you have some time. :) I hope this is what you had in mind.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 2]
```diff
@@ -561,35 +582,33 @@ private static void parseArray(ParseContext context, ObjectMapper parentMapper,
...
         XContentParser parser = context.parser();
         XContentParser.Token token;
+        final String[] paths = splitAndValidatePath(lastFieldName);
         while ((token = parser.nextToken()) != XContentParser.Token.END_ARRAY) {
             if (token == XContentParser.Token.START_OBJECT) {
-                parseObject(context, mapper, lastFieldName);
+                parseObject(context, mapper, lastFieldName, paths);
             } else if (token == XContentParser.Token.START_ARRAY) {
-                parseArray(context, mapper, lastFieldName);
-            } else if (token == XContentParser.Token.FIELD_NAME) {
```
Comment (TommyWind) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: This statement is impossible to reach, there shouldn't be a field name as a direct child of an array ever? Removed it so the logic for keeping the paths array is a little simpler to follow.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 3]
```diff
@@ -82,6 +82,20 @@ ParsedDocument parseDocument(SourceToParse source, MetadataFieldMapper[] metadat
         return parsedDocument(source, context, createDynamicUpdate(mapping, docMapper, context.getDynamicMappers()));
     }
 
+    private static boolean isDisabled(ObjectMapper objectMapper, String[] subfields) {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: Small comment, but I think `containsDisabledObjectMapper` would be clearer.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 4]
```diff
@@ -386,24 +400,31 @@ static void parseObjectOrNested(ParseContext context, ObjectMapper mapper) throw
...
-                parseArray(context, mapper, currentFieldName);
-            } else if (token == XContentParser.Token.FIELD_NAME) {
+            if (token == XContentParser.Token.FIELD_NAME) {
                 currentFieldName = parser.currentName();
+                paths = splitAndValidatePath(currentFieldName);
                 if (MapperService.isMetadataField(context.path().pathAsText(currentFieldName))) {
                     throw new MapperParsingException("Field [" + currentFieldName + "] is a metadata field and cannot be added inside"
                         + " a document. Use the index API request parameters.");
                 }
+            } else if (isDisabled(mapper, paths)) {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: This existing method is structured in a fairly confusing way, but given the way it's structured, I think it'd be clearer to check this as part of the 'field name' block: 

```
if (token == XContentParser.Token.FIELD_NAME) {
    currentFieldName = parser.currentName();
    paths = splitAndValidatePath(currentFieldName);
    if (MapperService.isMetadataField(context.path().pathAsText(currentFieldName))) {
        throw new MapperParsingException("Field [" + currentFieldName + "] is a metadata field and cannot be added inside"
            + " a document. Use the index API request parameters.");
        } else if (isDisabled(mapper, paths)) {
            parser.nextToken();
            parser.skipChildren();
        }
    }
} else if ...
```

**Review by jtibshirani — COMMENTED** [review]
I like the new approach, and thanks for adding those additional tests. I'll kick off a full CI build now.

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by TommyWind** [comment]
@jtibshirani thanks for another round :) I pushed the changes you suggested.

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Review by jtibshirani — COMMENTED** [review]
This looks good to me. Before merging I'm hoping someone else from @elastic/es-search could take a quick look as well, in case I am missing anything.

**Review by jpountz — APPROVED** [review]
The change looks good to me as well. Good catch @TommyWind !

**Comment by jtibshirani** [comment]
Great, I will merge and backport to the right branches.

**Comment by TommyWind** [comment]
Thanks @jtibshirani and @jpountz :)
