### PR TITLE
Fix threshold frequency computation in Suggesters

### LINKED ISSUE #34282: Phrase Suggester: Suggesting on very frequent words can cause request failures
I have a stack trace that looks like:

```
Caused by: java.lang.IllegalArgumentException: Fractional absolute document frequencies are not allowed
    at org.apache.lucene.search.spell.DirectSpellChecker.setThresholdFrequency(DirectSpellChecker.java:182)
    at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.drawCandidates(DirectCandidateGenerator.java:131)
    at org.elasticsearch.search.suggest.phrase.MultiCandidateGeneratorWrapper.drawCandidates(MultiCandidateGeneratorWrapper.java:52)
```

I do not have and cannot get the index that causes this failure. But it looks to me like the failure is caused by this series of events:
1. `DirectCandidateGenerator#thresholdFrequency` spits out a frequency that is bigger than `Integer.MAX_VALUE`. This looks to be possible using the default configuration for common words like "the" when the corpus is a couple of million documents and each document is large, like, say, as big as a wikipedia page.
2. We call `DirectSpellChecker#setThresholdFrequency` with that number. The JVM helpfully casts the `long` returned by step 1 into a `float`, losing precision but keeping the magnitude of the number largely intact.
3. Lucene attempts to validate that the `float` is either less than 0 or a whole number. The "is it a whole number" check looks like `thresholdFrequency != (int) thresholdFrequency`. That will consider floats that don't fit into `int`s as not whole numbers. Most of the time, anyway.

There is a work around: set `"suggest_mode": "always"`. We'll skip the math and just pick 0 for the frequency. Which is both less than one and whole number so Lucene is quite happy with it.

It looks like we should either clamp the value to `Integer.MAX_VALUE` in Elasticsearch or Lucene should use something else to check for fractional numbers.

### PR DESCRIPTION
**Pull request by jimczi**
The `term` and `phrase` suggesters have different options to filter candidates
based on their frequencies. The `popular` mode for instance filters candidate
terms that occur in less docs than the original term. However when we compute this threshold
we use the total term frequency of a term instead of the document frequency. This is not inline
with the actual filtering which is always based on the document frequency. This change fixes
this discrepancy and clarifies the meaning of the different frequencies in use in the suggesters.
It also ensures that the threshold doesn't overflow the maximum allowed value (Integer.MAX_VALUE).

Closes #34282

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java [hunk 1]
```diff
@@ -268,8 +268,8 @@ Integer maxInspections() {
      * frequencies. If an value higher than 1 is specified then fractional
      * can not be specified. Defaults to {@code 0.01}.
      * <p>
-     * This can be used to exclude high frequency terms from being
-     * suggested. High frequency terms are usually spelled correctly on top
+     * This can be used to exclude high totalTermFrequency terms from being
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java]: This might to a bit overzealous copy and replace.

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/WordScorer.java [hunk 2]
```diff
@@ -62,7 +62,8 @@ public WordScorer(IndexReader reader, Terms terms, String field, double realWord
         // division by zero, by scoreUnigram.
         final long nTerms = terms.size();
         this.numTerms = nTerms == -1 ? reader.maxDoc() : nTerms;
-        this.termsEnum = new FreqTermsEnum(reader, field, !useTotalTermFreq, useTotalTermFreq, null, BigArrays.NON_RECYCLING_INSTANCE); // non recycling for now
+        this.termsEnum = new FreqTermsEnum(reader, field, !useTotalTermFreq, useTotalTermFreq, null,
+            BigArrays.NON_RECYCLING_INSTANCE); // non recycling for now
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/suggest/phrase/WordScorer.java]: That is an old comment!

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGenerator.java [hunk 3]
```diff
@@ -171,28 +189,29 @@ public void nextToken() throws IOException {
...
+    private double score(TermStats termStats, double errorScore, long dictionarySize) {
+        return errorScore * (((double)termStats.totalTermFreq + 1) / ((double)dictionarySize +1));
     }
 
-    protected long thresholdFrequency(long termFrequency, long dictionarySize) {
-        if (termFrequency > 0) {
-            return max(0, round(termFrequency * (log10(termFrequency - frequencyPlateau) * (1.0 / log10(LOG_BASE))) + 1));
+    protected int thresholdTermFrequency(int docFreq) {
+        if (docFreq > 0) {
+            return (int) min(
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGenerator.java]: I'd love to have a test that calls this with big numbers and validates that it returns Integer.MAX_VALUE.

**Review by nik9000 — COMMENTED** [review]
Thanks for fixing the problem! I don't really know the if it is ok to make this change in 6.x though because it is kind of a breaking change to the "popular" suggest_mode.

For what it is worth I find that the phrase suggester make much better suggestions when you use the "always" suggest_mode.

**Comment by jimczi** [comment]
>  I don't really know the if it is ok to make this change in 6.x though because it is kind of a breaking change to the "popular" suggest_mode.

Yes I know, a bug is a feature ;). We can merge the switch to `docFreq` in master and only backport the protection against overflow in 6x, WDYT @nik9000 ?

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGenerator.java (hunk 3 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGenerator.java]: I'll add one

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java]: oups, thanks I'll fix

**Comment by nik9000** [comment]
>  We can merge the switch to `docFreq` in master and only backport the protection against overflow in 6x, WDYT @nik9000 ?

Sounds good to me! Could you add a breaking change note for this then?

**Comment by jimczi** [comment]
Done and I'll open a separate pr for 6.x

**Comment by jimczi** [comment]
I just realized that I forgot to push the breaking change [note](https://github.com/elastic/elasticsearch/pull/34312/commits/a16ba99c3ac7bd62ae4c056267c9b3b209cd35d2). @nik9000 can you take another look when you have time ?

**Review by nik9000 — APPROVED** [review]
LGTM
