### PR TITLE
Avoid port-scan in testThatTransportClientCanConnect

### LINKED ISSUE #108627: [CI] Netty4TransportMultiPortIntegrationIT testThatTransportClientCanConnect failing
Seems to happen only on 7.17 and windows-2016

**Build scan:**
https://gradle-enterprise.elastic.co/s/76ongcrk2ajce/tests/:modules:transport-netty4:internalClusterTest/org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT/testThatTransportClientCanConnect

**Reproduction line:**
```
gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT.testThatTransportClientCanConnect" -Dtests.seed=137E95DDC3A21473 -Dtests.locale=ar-TN -Dtests.timezone=Etc/UTC -Druntime.java=21
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT#testThatTransportClientCanConnect`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testThatTransportClientCanConnect'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([137E95DDC3A21473]:0)

```

### LINKED ISSUE #109400: [CI] Netty4TransportMultiPortIntegrationIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3004 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mqhb6aq33zvbs)
- [elasticsearch-periodic-platform-support #3000 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/qh6momvssruvq)
- [elasticsearch-periodic-platform-support #2996 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/r7xfnrtogupga)
- [elasticsearch-periodic-platform-support #2984 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/3de3jf26cbzsc)
- [elasticsearch-periodic-platform-support #2972 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/wnvzwh2iqnofs)
- [elasticsearch-periodic-platform-support #2968 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/yxlmktogllhn6)
- [elasticsearch-periodic-platform-support #2952 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/wb2ebhpepc2wm)
- [elasticsearch-periodic-platform-support #2940 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/uih6y6xwqszvu)

**Reproduction Line:**
```
gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT" -Dtests.seed=3088CA3B5E3D5EB7 -Dtests.locale=sr-CS -Dtests.timezone=Atlantic/South_Georgia -Druntime.java=22
```

**Applicable branches:**
7.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
null
```

**Mute Reasons:**
- [7.17] 8 consecutive failures in step windows-2016_checkpart1_platform-support-windows (100.0% fail rate)
- [7.17] 8 failures in class org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT (0.9% fail rate)
- [7.17] 8 failures in step windows-2016_checkpart1_platform-support-windows (100.0% fail rate)
- [7.17] 8 failures in pipeline elasticsearch-periodic-platform-support (36.4% fail rate)

**Note:**
This issue was created using new, in-development muting automation. Please mind any issues.

### PR DESCRIPTION
**Pull request by DaveCTurner**
300 concurrent connection attempts, each with a 30s timeout, will take
way longer than is reasonable in a test. With this commit we connect
directly to addresses to which we know nodes are bound.

Closes #108627
Closes #109400

### CODE REVIEW

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java [hunk 1]
```diff
@@ -64,17 +66,28 @@ protected Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
...
+                for (final TransportAddress transportAddress : transport.boundAddress().boundAddresses()) {
+                    addresses.add(transportAddress);
+                }
+                for (final BoundTransportAddress profileAddresses : transport.profileBoundAddresses().values()) {
+                    for (final TransportAddress transportAddress : profileAddresses.boundAddresses()) {
+                        addresses.add(transportAddress);
+                    }
+                }
             }
+            logger.info("--> all addresses: {}", addresses);
```
Comment (DiannaHohensee) [inline modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java:87]: Is there any expectation for a minimum number of addresses that have been collected? Wondering if there's a sanity check that we are in fact testing some number of addresses.

**Review by DiannaHohensee — COMMENTED** [review]
This seems to make sense.. `Netty4Plugin.getTransports` creates a `Netty4Transport`, which I think is the `Transport` type you're grabbing from each node. Then the implication seems to be that `Transport` holds all the addresses on which a node listens?

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java (hunk 1 above)
Comment (DaveCTurner) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java:87]: Yes every node must bind to at least one transport address, otherwise it wouldn't be able to join a cluster.

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java [hunk 2]
```diff
@@ -64,17 +66,28 @@ protected Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
...
+            final TransportAddress[] targetAddresses = randomNonEmptySubsetOf(addresses).toArray(new TransportAddress[0]);
+            logger.info("--> target addresses: {}", Arrays.toString(targetAddresses));
+            transportClient.addTransportAddresses(targetAddresses);
             ClusterHealthResponse response = transportClient.admin().cluster().prepareHealth().get();
```
Comment (DiannaHohensee) [inline modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java:91]: Is the idea here that prepareHealth broadcasts to all nodes / transport addresses? Are we tricking the TransportClient into thinking that each address is a different node? I see `transportClient.addTransportAddresses` eventually ends up [creating a list of DiscoveryNodes](https://github.com/elastic/elasticsearch/blob/d38e4b028f4a9784bb74de339ac1b877e2dbea6f/server/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L188-L199).

Comment (DaveCTurner) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java:91]: No, the `TransportClient` ultimately chooses just one address to which to send the request.

**Review by arteam — APPROVED** [review]
LGTM
