### PR TITLE
ESQL: Ensure non-zero row size in `EstimatesRowSize`

### LINKED ISSUE #121535: ES|QL "ROW a=null | SORT a" crashes with AssertionError
### Elasticsearch Version

9.0.0

### Installed Plugins

_No response_

### Java Version

n/a

### OS Version

n/a

### Problem Description

Executing the ES|QL command
```
ROW a=null | SORT a
```
crashes on main with the following assertion error:
```
[2025-02-03T15:33:10,801][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#1]], exiting java.lang.AssertionError: estimated row size [0] wasn't set
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planTopN(LocalExecutionPlanner.java:362)
(...)
```

Note: this doesn't occur in production, because assertions are disabled.

### Steps to Reproduce

spin up ES, Kibana, go to discover, ES|QL mode, enter "ROW a=null | SORT a"

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by kanoshiou**
Remove the assertion of `rowSize` in `planTopN`, because in `LocalExecutionPlannerContext.pageSize(Integer)`, there is already a check for `estimatedRowSize` to ensure it is not null and not zero.

Closes #121535

### CODE REVIEW

**Comment by kanoshiou** [comment]
I think the query `ROW a=null | SORT a` should return correctly, instead of throwing an exception. However, since the `DataType` of `a` is `NULL` and its `estimatedSize` is 0, the query does not pass the checker. Perhaps changing the `estimatedSize` of `NULL` to a non-zero value (such as 1) could solve this problem, but I am unsure if there would be any side effects.

**Review by dnhatn — COMMENTED** [review]
@kanoshiou Thank you for looking into it. I think we should not remove this assertion, but ensure that at least one byte is returned in `EstimatesRowSize#consumeAllFields`. Can you also add the query `ROW a=null | SORT a` to EsqlActionIT?

**Comment by kanoshiou** [comment]
Thank you for reviewing, @dnhatn! The assertion has been restored, and I've added the test you specified. Please review when you have the time.😊

**Review by nik9000 — APPROVED** [review]
Looks good to me.

**Comment by dnhatn** [comment]
test this please

**Review by dnhatn — APPROVED** [review]
Great investigation. Thanks @kanoshiou!

**Comment by dnhatn** [comment]
@kanoshiou  There is another issue with FragmentExec. Would you mind moving the new logic to `TopNExec#estimateRowSize` instead? I will address the FragmentExec issue later. However, if you're interested in fixing it, feel free to give it a try.

CI failure: https://gradle-enterprise.elastic.co/s/4p6fd4lzayp66

**Comment by dnhatn** [comment]
And this query too `row a = null | STATS BY a`

**Comment by kanoshiou** [comment]
Thanks for reviewing @nik9000 @dnhatn, and I‘m happy to help to resolve the new issue!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/AggregateExec.java [hunk 1]
```diff
@@ -136,6 +136,7 @@ public Integer estimatedRowSize() {
     public PhysicalPlan estimateRowSize(State state) {
         state.add(false, aggregates);  // The groupings are contained within the aggregates
         int size = state.consumeAllFields(true);
+        size = size == 0 ? 1 : size;
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/AggregateExec.java:139]: nit: maybe use`size = Math.max(size, 1);`?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/TopNExec.java [hunk 2]
```diff
@@ -101,6 +101,7 @@ public PhysicalPlan estimateRowSize(State state) {
         final boolean needsSortedDocIds = output.stream().anyMatch(a -> a.dataType() == DataType.DOC_DATA_TYPE);
         state.add(needsSortedDocIds, output);
         int size = state.consumeAllFields(true);
+        size = size == 0 ? 1 : size;
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/TopNExec.java:104]: nit: maybe use`size = Math.max(size, 1);`?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/AggregateExec.java (hunk 1 above)
Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/AggregateExec.java:139]: Yes, the `max` function seems more explicit.

**Comment by kanoshiou** [comment]
Thank you for your review, @dnhatn! But I have no idea what's wrong with `FragmentExec` because I don't have access to the content in the link you posted above, so any additional information would be very helpful. However, I was able to review the test failure run by Buildkite, and I have tested the failed `PhysicalPlanOptimizerTests` on my machine.

**Comment by dnhatn** [comment]
test this please

**Comment by dnhatn** [comment]
@kanoshiou Thanks for your contribution.

**Comment by dnhatn** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/123959)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
