### PR TITLE
Do not override named S3 client credentials

### LINKED ISSUE #33769: Deprecated credentials overwrite client settings in all configured repository clients
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.x

**Plugins installed**: [discovery-file, found-elasticsearch, repository-s3]

**JVM version** (`java -version`): 1.8.0_144; 25.144-b01;

**OS version** (`uname -a` if on a Unix-like system):Linux 4.4.0-1048-aws #57-Ubuntu SMP

**Description of the problem including expected versus actual behavior**:
Configuring a s3 repository that uses deprecated credentials specified directly in the repository client settings overwrites the credentials in all repository clients. 

Expected behaviour would be that the legacy credentials are only used to populate the settings object that corresponds to the repository/client that actually specified them.

**Steps to reproduce**:

 1. configure a s3 repository (`repository 1`) that [uses secure credentials](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-client.html) and a non-default client name
 2. verify that this repository works 
 3. configure a second repository using the default client name and deprecated credentials specified directly in the request creating the repository e.g. 

```
"repository-2": {
    "type": "s3",
    "settings": {
      "bucket": "bucket-name",
      "access_key": "your-access-key",
      "secret_key": "your-secret-key"
    }
  }
```
4. verify that the `repository 2` works
5. find that access to `repository 1`  is now denied

**Additional information**:

`POST _nodes/reload_secure_settings` is a workaround which restores the secure credentials for `repository 1`  but "breaks" `repository 2` in the process.

Screenshot of a heap dump I took from the cluster, see the legacy credentials being propagated into both settings objects
screen shot 2018-09-17 at 15 05 57

Looking at the s3 repository plugin code the deprecated credentials seem to be propagated into every S3ClientSettings object when the S3 repository object holding the legacy credentials is constructed: 
https://github.com/elastic/elasticsearch/blob/4108722052707c4d9acc1b211e6fd2f77885dcc2/plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java#L163-L174

Called here with on settings retrieved from the S3Service object:
https://github.com/elastic/elasticsearch/blob/b1bf643e41b2bf2bc1360887b4768836c9159214/plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java#L251-L254

### PR DESCRIPTION
**Pull request by jasontedor**
In cases when mixed secure S3 client credentials and insecure S3 client credentials were used (that is, those defined on the repository), we were overriding the credentials from the repository using insecure settings to all the repositories. This commit fixes this by not mixing up repositories that use insecure settings with those that use secure settings.

Closes #33769

### CODE REVIEW

**Review by albertzaharovits — APPROVED** [review]
nice! LGTM

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java [hunk 1]
```diff
@@ -224,25 +211,37 @@ static AWSCredentials loadCredentials(Settings settings, String clientName) {
...
+                    getConfigValue(settings, clientName, MAX_RETRIES_SETTING),
+                    getConfigValue(settings, clientName, USE_THROTTLE_RETRIES_SETTING)
             );
         }
     }
 
+    static S3ClientSettings getClientSettings(final RepositoryMetaData metadata, final AWSCredentials credentials) {
+        final Settings.Builder builder = Settings.builder();
+        for (final String key : metadata.settings().keySet()) {
+            builder.put(PREFIX + "dummy" + "." + key, metadata.settings().get(key));
```
Comment (tlrx) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java]: Nit: can we use something different than `dummy`? Like "deprecated" or "provided_credentials"

**Review by tlrx — APPROVED** [review]
LGTM, I left some very minor comments. Feel free to apply them or not.

And thanks for fixing this!

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java [hunk 2]
```diff
@@ -200,21 +201,40 @@
 
         this.storageClass = STORAGE_CLASS_SETTING.get(metadata.settings());
         this.cannedACL = CANNED_ACL_SETTING.get(metadata.settings());
+
+        if (CLIENT_NAME.exists(metadata.settings()) && S3ClientSettings.checkDeprecatedCredentials(metadata.settings())) {
+            logger.warn("ignoring use of named client [" + metadata.name() + "] as insecure credentials were specified");
```
Comment (tlrx) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java]: Thanks for adding this warning. Since ` metadata.name() ` refers to the repository name, we could maybe change this to: "ignoring use of named client for repository ["

Comment (jasontedor) [reply plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java]: I pushed 730e07c9383f026bb10cb5b4ba056b9011add0a7.

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java (hunk 1 above)
Comment (jasontedor) [reply plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java]: I pushed 01b5e95c1d59f4aa738bff3e8f9ab535f16b46a5.

**Comment by jasontedor** [comment]
Thanks for reviewing @albertzaharovits and @tlrx.
