### PR TITLE
[Test] ClientYamlSuiteRestApiParser parses specs without path parts

### LINKED ISSUE #31649: Test: ClientYamlSuiteRestApiParser cannot parse test specs without parts that require a body
The api json file parser seems to not correctly parse spec files that do not have any path parameters but have the `body` field set and required.

This test (added in `ClientYamlSuiteRestApiParserTests`) fails

```java
    public void testRequiredBodyWithoutUrlParts() throws Exception {
        String spec = "{\n" +
            "  \"count\": {\n" +
            "    \"documentation\": \"whatever\",\n" +
            "    \"methods\": [ \"GET\", \"POST\" ],\n" +
            "    \"url\": {\n" +
            "      \"path\": \"/whatever\",\n" +
            "      \"paths\": [ \"/whatever\" ]\n" +
            "    },\n" +
            "    \"body\": {\n" +
            "      \"description\" : \"whatever\",\n" +
            "      \"required\" : true\n" +
            "    }\n" +
            "  }\n" +
            "}";
        parser = createParser(YamlXContent.yamlXContent, spec);
        ClientYamlSuiteRestApi restApi = new ClientYamlSuiteRestApiParser().parse("count.json", parser);

        assertThat(restApi, notNullValue());
    }
```

fails with

```

java.lang.AssertionError: Expected [END_OBJECT] but was [null]

	at __randomizedtesting.SeedInfo.seed([ED4984B513DDA0D0:BDED9C135058595]:0)
	at org.elasticsearch.test.rest.yaml.restspec.ClientYamlSuiteRestApiParser.parse(ClientYamlSuiteRestApiParser.java:155)
	at org.elasticsearch.test.rest.yaml.restspec.ClientYamlSuiteRestApiParserTests.testRequiredBodyWithoutUrlParts(ClientYamlSuiteRestApiParserTests.java:110)
```

### PR DESCRIPTION
**Pull request by lipsill**
Previously ClientYamlSuiteRestApiParser threw an exception when an api
spec contained neither path parts nor url parameter sections.

Fixes #31649

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java [hunk 1]
```diff
@@ -108,13 +107,6 @@ public ClientYamlSuiteRestApi parse(String location, XContentParser parser) thro
                                 restApi.addParam(param, PARAMETER_PARSER.parse(parser, null).isRequired());
                             }
                         }
-
-                        if (parser.currentToken() == XContentParser.Token.START_OBJECT) {
-                            innerLevel++;
-                        }
-                        if (parser.currentToken() == XContentParser.Token.END_OBJECT) {
-                            innerLevel--;
-                        }
```
Comment (javanna) [inline test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java]: what happens with this fix if you have something like:

```
    "url" : {
        "parts" : {
        },
        "path" : "my_path"
    }
```

Does the path get parsed?

Comment (javanna) [reply test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java]: I am not sure that this behaviour is correct though, so I would fix that and add a test that makes sure the behaviour for this scenario is correct. Do you see what I mean?

Comment (lipsill) [reply test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java]: >I am not sure that this behaviour is correct though

@javanna What you mean by *this behaviour*?
Currently the following api spec is parsed without a problem.
```
{
  "test": {
    "documentation": "whatever",
    "methods": [ "GET", "POST" ],
    "url": {
      "parts": {},
      "path": "/my_path"
    },
    "body": {
      "description" : "whatever",
      "required" : true
    }
  }
}
```
Or do you mean that the `path` needs to be validated as a string, although it will not be stored in the api spec.

TBH I find the usage of `innerLevel` (especially when combined with object parser) confusing and, as raised by the issue, unreliable and order dependent.

Comment (javanna) [reply test/framework/src/main/java/org/elasticsearch/test/rest/yaml/restspec/ClientYamlSuiteRestApiParser.java]: You are right, I forgot that `path` is ignored anyways, and I misread the parsing code thinking that the inner parsers would not consume the inner end object, and then we could end up exiting the loop before reading the whole container object. All good , I think your change is good, I will trigger tests.

**Comment by javanna** [comment]
test this please

**Comment by javanna** [comment]
hi @lipsill the test failures are unrelated to your changes, would you be able to merge master in, so I can run tests again?

**Comment by lipsill** [comment]
@javanna thanks for the ping. I had a look yesterday but did not see a commit addressing the bwc version issue I saw in the CI ...
I just merged. Can you give this one a try again;)

**Comment by javanna** [comment]
retest this please

**Review by javanna — APPROVED** [review]
LGTM thanks @lipsill !
