### PR TITLE
ES|QL: fix DataNodeRequestSenderTests.testLimitConcurrentNodes

### LINKED ISSUE #139935: [CI] DataNodeRequestSenderTests testLimitConcurrentNodes failed
### CI Link

https://gradle-enterprise.elastic.co/s/u5pu6chk3lu72/tests/task/:x-pack:plugin:esql:test/details/org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderTests/testLimitConcurrentNodes?top-execution=1

### Repro line

`./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderTests.testLimitConcurrentNodes" -Dtests.seed=1053EA2845BB1589 -Dtests.locale=ca-AD -Dtests.timezone=Europe/Luxembourg -Druntime.java=25	`

### Does it reproduce?

No

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

    java.lang.AssertionError: 
    Expected: <2>
         but: was <1>

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixing a race condition in `DataNodeRequestSenderTests.testLimitConcurrentNodes`

In the very unlikely case that the requests are executed sequentially (ie. that they never overlap), `concurrentRequests` is incremented to 1 and then immediately decremented to 0, so `maxConcurrentRequests` will be 1 at most.

What we really want to test here is that we never exceed the maximum number of concurrent requests, so we can relax the assertion a bit.

~~I'm also adding another test that forces the execution of at least N requests concurrently.~~

I'm refactoring the test a bit, adding some constraints that force requests to pile up

Fixes: https://github.com/elastic/elasticsearch/issues/139935

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderTests.java [hunk 1]
```diff
@@ -344,6 +346,53 @@ public void testLimitConcurrentNodes() {
...
+                var priorMax = maxConcurrentRequests.get();
+                var newMax = Math.max(priorMax, concurrentRequests.get());
+                if (newMax <= priorMax || maxConcurrentRequests.compareAndSet(priorMax, newMax)) {
+                    break;
+                }
+            }
+
+            sent.add(nodeRequest(node, shardIds));
+            runWithDelay(() -> {
+                while (maxConcurrentRequests.get() < concurrency) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderTests.java]: Most of this test is identical to the previous one. Which part is changed? Only this while? Can you add some comment to better understand what it's doing differently?

**Review by ivancea — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderTests.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderTests.java]: Thanks @ivancea 

> Which part is changed? Only this while?

Yes, the only difference is that in the second test I force the requests to pile up to make sure I reach the max concurrency.

I refactored the code a bit, making it a single test with a randomized condition that tests the two scenarios, and I added a few comments. Now it should be more clear for future readers (including me 😄 )

**Review by cimequinox — APPROVED** [review]
This addresses the concurrency issue as described.

Although outside the scope of this fix, I think the while loop computing `maxConcurrentRequest` around 332-338 could be more simply expressed using [getAndAccumulate()](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicInteger.html#getAndAccumulate-int-java.util.function.IntBinaryOperator- ).

e.g. something like `maxConcurrentRequests.getAndAccumulate(concurrentRequests.get(), Math::max)`
