### PR TITLE
Unmute 52_esql_insist_operator_synthetic_source.yml

### LINKED ISSUE #130506: [CI] LogsdbTestSuiteIT test {yaml=/52_esql_insist_operator_synthetic_source/FROM with INSIST_🐔and LIMIT 1} failing
**Build Scans:**
- [elasticsearch-periodic #9108 / release-tests](https://gradle-enterprise.elastic.co/s/34jdbkgls4tl4)
- [elasticsearch-pull-request #78512 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/xuvscb24bqlac)
- [elasticsearch-periodic #9087 / release-tests](https://gradle-enterprise.elastic.co/s/hyexxb6y3gmvg)
- [elasticsearch-pull-request #78493 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/5lyjryecfkbqc)
- [elasticsearch-pull-request #78424 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/inyn5jskzttte)
- [elasticsearch-periodic #9080 / release-tests](https://gradle-enterprise.elastic.co/s/hquhm6khfx4n2)
- [elasticsearch-periodic #9071 / release-tests](https://gradle-enterprise.elastic.co/s/r2unr6inwzuti)
- [elasticsearch-pull-request #77930 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/jfufm3d6wfp3q)
- [elasticsearch-pull-request #77926 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/yfeuazdn2x64y)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:logsdb:yamlRestTest" --tests "org.elasticsearch.xpack.logsdb.LogsdbTestSuiteIT.test {yaml=/52_esql_insist_operator_synthetic_source/FROM with INSIST_🐔and LIMIT 1}" -Dtests.seed=91BA2C31017F9516 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=pa-IN -Dtests.timezone=America/Menominee -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.logsdb.LogsdbTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3D%2F52_esql_insist_operator_synthetic_source%2FFROM%20with%20INSIST_%F0%9F%90%94and%20LIMIT%201%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [/52_esql_insist_operator_synthetic_source:59]: expected [2xx] status code but api [esql.query] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parsing_exception","reason":"line 1:17: mismatched input 'INSIST_\uD83D\uDC14' expecting {'change_point', 'enrich', 'completion', 'dissect', 'eval', 'grok', 'limit', 'sample', 'sort', 'stats', 'where', 'fork', 'lookup', 'mv_expand', 'drop', 'keep', 'rename'}","stack_trace":"org.elasticsearch.xpack.esql.parser.ParsingException: line 1:17: mismatched input 'INSIST_\uD83D\uDC14' expecting {'change_point', 'enrich', 'completion', 'dissect', 'eval', 'grok', 'limit', 'sample', 'sort', 'stats', 'where', 'fork', 'lookup', 'mv_expand', 'drop', 'keep', 'rename'}\n\tat org.elasticsearch.xpack.esql.parser.EsqlParser$1.syntaxError(EsqlParser.java:198)\n\tat org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)\n\tat org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)\n
[truncated]
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 5 consecutive failures in step checkpart2_release-tests
- [main] 9 failures in test test {yaml=/52_esql_insist_operator_synthetic_source/FROM with INSIST_🐔and LIMIT 1} (1.0% fail rate in 876 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 5 failures in step checkpart2_release-tests (100.0% fail rate in 5 executions)
- [main] 4 failures in pipeline elasticsearch-periodic (22.2% fail rate in 18 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 341 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130507: [CI] LogsdbTestSuiteIT test {yaml=/52_esql_insist_operator_synthetic_source/FROM with INSIST_🐔} failing
**Build Scans:**
- [elasticsearch-periodic #9108 / release-tests](https://gradle-enterprise.elastic.co/s/34jdbkgls4tl4)
- [elasticsearch-pull-request #78512 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/xuvscb24bqlac)
- [elasticsearch-periodic #9087 / release-tests](https://gradle-enterprise.elastic.co/s/hyexxb6y3gmvg)
- [elasticsearch-pull-request #78493 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/5lyjryecfkbqc)
- [elasticsearch-pull-request #78424 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/inyn5jskzttte)
- [elasticsearch-periodic #9080 / release-tests](https://gradle-enterprise.elastic.co/s/hquhm6khfx4n2)
- [elasticsearch-periodic #9071 / release-tests](https://gradle-enterprise.elastic.co/s/r2unr6inwzuti)
- [elasticsearch-pull-request #77930 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/jfufm3d6wfp3q)
- [elasticsearch-pull-request #77926 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/yfeuazdn2x64y)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:logsdb:yamlRestTest" --tests "org.elasticsearch.xpack.logsdb.LogsdbTestSuiteIT.test {yaml=/52_esql_insist_operator_synthetic_source/FROM with INSIST_🐔and LIMIT 1}" -Dtests.seed=91BA2C31017F9516 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=pa-IN -Dtests.timezone=America/Menominee -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.logsdb.LogsdbTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3D%2F52_esql_insist_operator_synthetic_source%2FFROM%20with%20INSIST_%F0%9F%90%94%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [/52_esql_insist_operator_synthetic_source:59]: expected [2xx] status code but api [esql.query] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parsing_exception","reason":"line 1:17: mismatched input 'INSIST_\uD83D\uDC14' expecting {'change_point', 'enrich', 'completion', 'dissect', 'eval', 'grok', 'limit', 'sample', 'sort', 'stats', 'where', 'fork', 'lookup', 'mv_expand', 'drop', 'keep', 'rename'}","stack_trace":"org.elasticsearch.xpack.esql.parser.ParsingException: line 1:17: mismatched input 'INSIST_\uD83D\uDC14' expecting {'change_point', 'enrich', 'completion', 'dissect', 'eval', 'grok', 'limit', 'sample', 'sort', 'stats', 'where', 'fork', 'lookup', 'mv_expand', 'drop', 'keep', 'rename'}\n\tat org.elasticsearch.xpack.esql.parser.EsqlParser$1.syntaxError(EsqlParser.java:198)\n\tat org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)\n\tat org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)\n
[truncated]
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 5 consecutive failures in step checkpart2_release-tests
- [main] 9 failures in test test {yaml=/52_esql_insist_operator_synthetic_source/FROM with INSIST_🐔} (1.0% fail rate in 876 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 5 failures in step checkpart2_release-tests (100.0% fail rate in 5 executions)
- [main] 4 failures in pipeline elasticsearch-periodic (22.2% fail rate in 18 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 341 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by martijnvg**
and ensure this yaml test suite isn't run if build is not snapshot.

Closes #130506
Closes #130507

### CODE REVIEW

File: x-pack/plugin/logsdb/src/yamlRestTest/java/org/elasticsearch/xpack/logsdb/LogsdbTestSuiteIT.java [hunk 1]
```diff
@@ -43,7 +47,19 @@ public LogsdbTestSuiteIT(@Name("yaml") ClientYamlTestCandidate testCandidate) {
 
     @ParametersFactory
     public static Iterable<Object[]> parameters() throws Exception {
-        return ESClientYamlSuiteTestCase.createParameters();
+        // Filter out 52_esql_insist_operator_synthetic_source.yml suite is build is not snapshot:
```
Comment (kkrik-es) [inline x-pack/plugin/logsdb/src/yamlRestTest/java/org/elasticsearch/xpack/logsdb/LogsdbTestSuiteIT.java]:
```suggestion
        // Filter out 52_esql_insist_operator_synthetic_source.yml suite for snapshot builds:
```

**Review by kkrik-es — APPROVED** [review]
