### PR TITLE
Fix realtime get of nested fields with synthetic source

### LINKED ISSUE #119553: [CI] LuceneSyntheticSourceChangesSnapshotTests testSkipNonRootOfNestedDocuments failing
**Build Scans:**
- [elasticsearch-intake #15248 / part1](https://gradle-enterprise.elastic.co/s/nzuqgdn5rkiau)
- [elasticsearch-pull-request #48870 / part-1](https://gradle-enterprise.elastic.co/s/fobutq4mrgib4)
- [elasticsearch-pull-request #48857 / part-1](https://gradle-enterprise.elastic.co/s/plxdccnd2vqsw)
- [elasticsearch-intake #15235 / part1](https://gradle-enterprise.elastic.co/s/o63oshstftozq)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.index.engine.LuceneSyntheticSourceChangesSnapshotTests.testSkipNonRootOfNestedDocuments" -Dtests.seed=C3E2020686E3DF0C -Dtests.locale=ses-ML -Dtests.timezone=Australia/Perth -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.engine.LuceneSyntheticSourceChangesSnapshotTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSkipNonRootOfNestedDocuments),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: luceneOp=Index{id='12', seqNo=10, primaryTerm=1213813268035527811, version=10, autoGeneratedIdTimestamp=-1} != translogOp=Index{id='12', seqNo=10, primaryTerm=1213813268035527811, version=10, autoGeneratedIdTimestamp=-1}
```

**Issue Reasons:**
- [8.x] 4 failures in test testSkipNonRootOfNestedDocuments (3.1% fail rate in 129 executions)
- [8.x] 2 failures in step part1 (50.0% fail rate in 4 executions)
- [8.x] 2 failures in step part-1 (40.0% fail rate in 5 executions)
- [8.x] 2 failures in pipeline elasticsearch-intake (50.0% fail rate in 4 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (40.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
Today, for get-from-translog operations, we only need to reindex the root document into an in-memory Lucene, as the `_source` is stored in the root document and is sufficient. However, synthesizing the source for nested fields requires both the root document and its child documents. This causes realtime-get operations (as well as update and update-by-query operations) to miss nested fields.

Another issue is that the translog operation is reindexed lazily during get-from-translog operations. As a result, two realtime-get operations can return slightly different outputs: one reading from the translog and the other from Lucene.

This change resolves both issues. However, addressing the second issue can degrade the performance of realtime-get and update operations. If slight inconsistencies are acceptable, the translog operation should be reindexed lazily instead.

Closes #119553

### CODE REVIEW

**Comment by dnhatn** [comment]
test this please

File: server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java [hunk 1]
```diff
@@ -159,20 +191,55 @@ static DirectoryReader createInMemoryReader(
...
         ).setCodec(engineConfig.getCodec());
         try (IndexWriter writer = new IndexWriter(directory, writeConfig)) {
-            writer.addDocument(parsedDocs.rootDoc());
+            final int numDocs;
+            if (rootDocOnly) {
+                numDocs = 1;
+                writer.addDocument(parsedDocs.rootDoc());
+            } else {
+                numDocs = parsedDocs.docs().size();
+                writer.addDocuments(parsedDocs.docs());
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:200]: I am not 100% sure I understand why this is necessary for synthetic source and not for regular source, perhaps you can help me out?

File: server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java [hunk 2]
```diff
@@ -76,21 +80,48 @@
...
         EngineConfig engineConfig,
         Runnable onSegmentCreated
     ) throws IOException {
-        this(new TranslogLeafReader(shardId, operation, mappingLookup, documentParser, engineConfig, onSegmentCreated));
+        final Directory directory = new ByteBuffersDirectory();
+        boolean success = false;
+        try {
+            final LeafReader leafReader;
+            // When using synthetic source, the translog operation must always be reindexed into an in-memory Lucene to ensure consistent
+            // output for realtime-get operations. However, this can degrade the performance of realtime-get and update operations.
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:98]: The inconsistencies would those purely be white-space and field order or also actual content like order in arrays etc?

I *think* this is ok, synthetic source and heavy real-time GET / update use cases are probably rare, but I'd like to understand the tradeoff more deeply.

If it is only white-space and field order, could we sort that instead and how difficult would that be? Not asking to implement that now, more about knowing our backdoor in case we need this.

**Review by henningandersen — COMMENTED** [review]
Thanks Nhat, left a few clarifying questions.

File: server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:98]: Yes, the inconsistencies also include removing duplicate values in an array and returning a single value as an object instead of an array. For example:

```
{ 
	"f": ["v"]
}
```

becomes

```
{
	"f": "v"
}
```

Or:

```
{
	"f": ["v1", "v1", "v2"]
}
```

becomes

```
{
	"f": ["v1", "v2"]
}
```

File: server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:200]: Synthesizing the source of nested fields requires both the root document and its child documents, whereas the stored source only requires the root document: https://github.com/elastic/elasticsearch/blob/12e86b1cd05202cdc080ed1ad74438c041d531de/server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java#L466

Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:200]: Thanks. I wonder about the field fetch support that is in the GET API, but I suppose it is restricted to not be able to access nested objects in any way?

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:200]: > I wonder about the field fetch support that is in the GET API, but I suppose it is restricted to not be able to access nested objects in any way?

I don't think including stored fields of nested (child) documents works today. Looks like the root docid is used in `ShardGetService#innerGetFetch(...)`.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Backported to 8.18 in https://github.com/elastic/elasticsearch/pull/120247
