### PR TITLE
Extend field stats to report searchable/aggregatable fields

### LINKED ISSUE #17750: Extend field stats to include type, searchable, aggregatable
After much discussion in https://github.com/elastic/elasticsearch/issues/15728 we have agreed to make the following changes to the field stats API:

* `?fields` will accept wildcards, so that it can match all fields
* field stats will return the field `type`, and whether it is searchable (`index ==true`) and aggregatable (`doc_values==true || (index==true && fielddata==true))`

When `?level=cluster` (the default), fields with the same name are collapsed into a single entry unless the fields have a different `type`, in which case the whole request returns an exception. This collapsing process should change as follows:

* An entry should be returned for fields with conflicting `type`, but with an `error` key which describes the error.
* `searchable` and `aggregatable` are collapsed to `true` if any of the instances of that field are searchable or aggregatable.

/cc @rashidkpc @spalger @jpountz @martijnvg

### PR DESCRIPTION
**Pull request by jimczi**
- Add isSearchable and isAggregatable (collapsed to true if any of the instances of that field are searchable or aggregatable).
- Accept wildcards in field names.
- Add a section named conflicts for fields with the same name but with incompatible types (instead of throwing an exception).

This closes #17750

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/fieldstats/FieldStats.java [hunk 1]
```diff
@@ -224,352 +240,392 @@ protected void toInnerXContent(XContentBuilder builder) throws IOException {
...
 
     private final static class Fields {
-
         final static String MAX_DOC = new String("max_doc");
         final static String DOC_COUNT = new String("doc_count");
         final static String DENSITY = new String("density");
         final static String SUM_DOC_FREQ = new String("sum_doc_freq");
         final static String SUM_TOTAL_TERM_FREQ = new String("sum_total_term_freq");
+        final static String IS_SEARCHABLE = new String("is_searchable");
+        final static String IS_AGGREGATABLE = new String("is_aggregatable");
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/fieldstats/FieldStats.java]: should it be just `searchable`/`aggregatable` (without the `is_` prefix) as suggested in the original issue?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/fieldstats/FieldStats.java]: on the other hand I would agree to keep isSearchable/isAggregatable in the Java API

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java [hunk 2]
```diff
@@ -315,6 +315,25 @@ protected BytesRef indexedValueForSearch(Object value) {
...
+    }
+
+    /** Returns true if the field is aggregatable.
+     *
+     */
+    public boolean isAggregatable() {
+        try {
+            fielddataBuilder();
+            return true;
+        } catch (Exception e) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: maybe only catch `IllegalStateException` to avoid hiding bugs?

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java [hunk 3]
```diff
@@ -315,6 +315,25 @@ protected BytesRef indexedValueForSearch(Object value) {
         return BytesRefs.toBytesRef(value);
     }
 
+    /** Returns true if the field is searchable.
+     *
+     */
+    public boolean isSearchable() {
+        return indexOptions() != IndexOptions.NONE;
+    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: can you make those two methods protected? they seem to be only called from MappedFieldType.stats?

File: core/src/main/java/org/elasticsearch/index/mapper/core/DateFieldMapper.java [hunk 4]
```diff
@@ -394,17 +394,21 @@ public long parseToMilliseconds(Object value, boolean roundUp,
...
-            long size = PointValues.size(reader, field);
-            if (size == 0) {
-                return null;
+            long size;
+            try {
+                size = PointValues.size(reader, field);
+                if (size == 0) {
+                    return new FieldStats.Date(reader.maxDoc(), isSearchable(), isAggregatable(), dateTimeFormatter());
+                }
+            } catch (Exception e) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/core/DateFieldMapper.java]: I am a bit worried about this but on the other hand I don't think this change should be put on hold until the bug is fixed. Maybe we should remove the catch block and mark failing tests with `@AwaitsFix` and a link to https://issues.apache.org/jira/browse/LUCENE-7257 ?

**Comment by jpountz** [comment]
I left some comments but I think this is close!

File: core/src/main/java/org/elasticsearch/index/mapper/core/DateFieldMapper.java (hunk 4 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/index/mapper/core/DateFieldMapper.java]: done in https://github.com/elastic/elasticsearch/pull/17980/commits/574493ccb05cd854c2ed3fcc6385bb361c7630d0

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 3 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: Unfortunately I can't, this is used by the inner NumberType in NumberFieldMapper.

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 2 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: I've changed the exception in fielddataBuilder and failIfNoDocValues. Depending on the type, they were using an IllegalStateException or an IllegalArgumentException. I've changed this behavior and now they always use an IllegalArgumentException which is mapped on an http error 400 when they are thrown during a request.

File: core/src/main/java/org/elasticsearch/action/fieldstats/FieldStats.java (hunk 1 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/action/fieldstats/FieldStats.java]: Done in https://github.com/elastic/elasticsearch/pull/17980/commits/49cd8a47d6bbed62a4e0e3594eba55cce16fd058

**Comment by jimferenczi** [comment]
Thanks @jpountz I've pushed another commit.

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 3 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: maybe we can change the signature of NumberFieldMapper.NumberType.fieldStats to take the two booleans as an argument?

**Comment by jpountz** [comment]
I left another comment regarding the visibility of these new isSearchable/isAggregatable methods. Otherwise it looks good to me.

**Comment by jimferenczi** [comment]
Thanks @jpountz
I've change the visibility of the new methods in MappedFieldType. 
Merged https://github.com/elastic/elasticsearch/commit/f600c4ab9c4a575a269287bb5aaa22d828c56496
