### PR TITLE
Fix metadata _size when it comes to stored fields extraction

### LINKED ISSUE #94468: Mapper-Size Plugin Does Not Work on 8.6.2
### Elasticsearch Version

8.6.2

### Installed Plugins

mapper-size

### Java Version

_bundled_

### OS Version

3.10.0-1160.83.1.el7.x86_64

### Problem Description

Elastic mapper-size plugin fails on version 8.6.2 with updated templates for global, index, and component (both custom and managed).  It does work in 8.5.0

### Steps to Reproduce

Enable plugin, enable _size field, ingest data
image
image
image
image

**Works in 8.5.0 though!**
image

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by benwtrent**
Corrects weird regression introduced in: https://github.com/elastic/elasticsearch/pull/91269

Previous to that change, getting `_size` worked when using `storedFields`. However, that change now detects if a field type declares itself as `stored`. Even though `_size` is stored, it didn't declare itself as such. 

This change fixes that.

closes https://github.com/elastic/elasticsearch/issues/94468

### CODE REVIEW

File: plugins/mapper-size/src/main/java/org/elasticsearch/index/mapper/size/SizeFieldMapper.java [hunk 1]
```diff
@@ -50,7 +51,7 @@ public SizeFieldMapper build() {
 
     private static class SizeFieldType extends NumberFieldType {
         SizeFieldType() {
-            super(NAME, NumberType.INTEGER);
+            super(NAME, NumberType.INTEGER, true, true, true, false, null, Collections.emptyMap(), null, false, null, null);
```
Comment (benwtrent) [inline plugins/mapper-size/src/main/java/org/elasticsearch/index/mapper/size/SizeFieldMapper.java:54]: @romseygeek the specific change is here: https://github.com/elastic/elasticsearch/blob/547c8327b22b395293d02354e6c85d1f46995374/server/src/main/java/org/elasticsearch/search/fetch/subphase/StoredFieldsPhase.java#L80

Previously, stored fields addition didn't actually check the field type, but you added it. 

It seems correct to me to only add stored fields that are stored...but, I am not sure. It is technically a behavior change.

**Review by romseygeek — APPROVED** [review]
Good catch.  I think it's worth as a follow-up adding a test to MapperTestCase that explicitly checks that `isStored()` gives the right answer - I will open a PR.

**Comment by benwtrent** [comment]
@elasticmachine update branch
