### PR TITLE
Complete all transport handlers at shutdown

### LINKED ISSUE #84948: LEAK resource not cleaned up RelocationIT testRelocationEstablishedPeerRecoveryRetentionLeases
### CI Link

https://gradle-enterprise.elastic.co/s/coilrchnhdicw

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.recovery.RelocationIT.testRelocationEstablishedPeerRecoveryRetentionLeases" -Dtests.seed=48DD4597C7EC8FF7 -Dtests.locale=es-PA -Dtests.timezone=Europe/Bucharest -Druntime.java=17	

### Does it reproduce?

No

### Applicable branches

master

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.recovery.RelocationIT&tests.sortField=FAILED&tests.test=testRelocationEstablishedPeerRecoveryRetentionLeases&tests.unstableOnly=true

### Failure excerpt

  1> [2022-03-14T13:43:38,122][INFO ][o.e.r.RelocationIT       ] [testRelocationEstablishedPeerRecoveryRetentionLeases] [RelocationIT#testRelocationEstablishedPeerRecoveryRetentionLeases]: cleaned up after test
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.recovery.RelocationIT.testRelocationEstablishedPeerRecoveryRetentionLeases" -Dtests.seed=48DD4597C7EC8FF7 -Dtests.locale=es-PA -Dtests.timezone=Europe/Bucharest -Druntime.java=17
  2> java.lang.AssertionError: 
    Expected: an empty collection
         but: <[LEAK: resource was not cleaned up before it was garbage-collected.
    Recent access records: 
    Created at:
    	org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:32)
    	org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:72)
    	org.elasticsearch.transport.BytesRefRecycler.obtain(BytesRefRecycler.java:27)
    	org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput.ensureCapacityFromPosition(RecyclerBytesStreamOutput.java:211)
    	org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput.ensureCapacity(RecyclerBytesStreamOutput.java:202)
    	org.elasticsearch.common.io.stream.RecyclerBytesStreamOutput.writeBytes(RecyclerBytesStreamOutput.java:77)
    	org.elasticsearch.common.io.Streams$FlushOnCloseOutputStream.writeBytes(Streams.java:274)
    	org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:482)
    	java.base/java.io.OutputStream.write(OutputStream.java:127)
    	org.elasticsearch.common.compress.DeflateCompressor.threadLocalOutputStream(DeflateCompressor.java:179)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler.serializeDiffClusterState(PublicationTransportHandler.java:266)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler$PublicationContext.lambda$buildDiffAndSerializeStates$2(PublicationTransportHandler.java:329)
    	java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler$PublicationContext.buildDiffAndSerializeStates(PublicationTransportHandler.java:327)
    	org.elasticsearch.cluster.coordination.PublicationTransportHandler.newPublicationContext(PublicationTransportHandler.java:213)
    	org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:1368)
    	org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:416)
    	org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:309)
    	org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:153)
    	org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:114)
    	org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:170)
    	org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717)
    	org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260)
    	org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
    	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	java.base/java.lang.Thread.run(Thread.java:833)]>
        at __randomizedtesting.SeedInfo.seed([48DD4597C7EC8FF7:886D486B4E0323C8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:639)
        at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:427)
        at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:833)
  1> [2022-03-14T13:43:38,149][INFO ][o.e.r.RelocationIT       ] [testIndexSearchAndRelocateConcurrently] before test
  1> [2022-03-14T13:43:38,149][INFO ][o.e.r.RelocationIT       ] [testIndexSearchAndRelocateConcurrently] [RelocationIT#testIndexSearchAndRelocateConcurrently]: setting up test
  1> [2022-03-14T13:43:38,150][INFO ][o.e.t.InternalTestCluster] [testIndexSearchAndRelocateConcurrently] Setup InternalTestCluster [TEST-TEST_WORKER_VM=[471]-CLUSTER_SEED=[-2805428162336455921]-HASH=[1322FA3E367]-cluster] with seed [D9111DF33D0F030F] using [0] dedicated masters, [0] (data) nodes and [0] coord only nodes (master nodes are [auto-managed])

### PR DESCRIPTION
**Pull request by DaveCTurner**
Transport handlers may hold resources that need to be released, so we
must complete them all to avoid leaks. Also, the completion of a handler
may fork onto a different threadpool. Today we fork using a plain
`Runnable` in various places, but this means that the completion may be
rejected if the threadpool queue is full or the executor is shutting
down. This commit changes the behaviour to force execution even if the
queue is full, and to ensure that all handlers' completions are enqueued
with their respective executors before stopping the threadpool.

Closes #84948

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Labelling this `>test` because AFAICT today we don't appear to use any thread pools with bounded queues here so the only possibility of a leak is at shutdown and that doesn't really matter in production since we're shutting down anyway.

**Comment by DaveCTurner** [comment]
On reflection I don't really like this solution. We should be able to fully close down the transport service (including completing any pending handlers) before stopping any thread pools, avoiding the need to complete handlers on `SAME` at all. The trouble appears to be that we remove handlers from the map before queueing up their completion so we aren't waiting for these. I suspect it's ok for remote responses because the acquire-handler-and-enqueue-complete flow happens on a transport thread and we wait for these threads to finish when shutting the transport service down, but that's not the case for direct responses which therefore might race against shutdown. Maybe we need a little bit of extra ref-counting to track these things.

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

File: server/src/main/java/org/elasticsearch/transport/TransportService.java [hunk 1]
```diff
@@ -1389,16 +1409,23 @@ public String getProfileName() {
         @Override
         public void sendResponse(TransportResponse response) throws IOException {
             service.onResponseSent(requestId, action, response);
-            final TransportResponseHandler<?> handler = service.responseHandlers.onResponseReceived(requestId, service);
-            // ignore if its null, the service logs it
-            if (handler != null) {
+            try (var shutdownBlock = service.pendingDirectHandlers.withRef()) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/transport/TransportService.java:1412]: I'm struggling with how this would work in case of a handler running on the generic pool. We increment the pending handlers here, then enqueue the task on the generic queue and then decrement.
Wouldn't we still complete the stop of the transport service now before that task has been executed and potentially just quietly kill the generic pool without ever running our `ForkingResponseHandlerRunnable`? If it's enqueued and `shutdown` is called on that queue, I don't think there's anything that notifies our task of the fact that it will never run?
Wouldn't we have to push the decrementing of the ref on `shutdownBlock` to the generic pool in this example to actually be 100% safe?

**Review by original-brownbear — COMMENTED** [review]
Thanks David, sorry this took me a little to get my head around. One question only basically, looks great in general.

File: server/src/main/java/org/elasticsearch/transport/TransportService.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/transport/TransportService.java:1412]: My thinking is that it's enough to enqueue everything, we don't have to wait for them all to execute, because we start the shutdown by calling `ThreadPool#shutdown()` which should drain the threadpool queue first. It's true that this doesn't properly guarantee that everything executes (we call `shutdownNow()` after 10s regardless) but in practice this only matters for tests which should be cleaning everything up in good time anyway.

I suppose we could assert that `shutdownNow()` returns an empty list in most tests to be more explicit about that. Not sure I want to do that here tho.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/TransportService.java:1412]: > I suppose we could assert that shutdownNow() returns an empty list in most tests to be more explicit about that. Not sure I want to do that here tho.

Right ... that's what we actually want in a follow-up. I'm 95% sure that will trip here and there ...

**Review by original-brownbear — APPROVED** [review]
LGTM, makes sense to me thanks David! :)

File: server/src/main/java/org/elasticsearch/transport/TransportService.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/transport/TransportService.java:1412]: Ah I checked and it looks like we almost have this already. We throw an `AssertionError` if graceful shutdown fails in `ESSingleNodeTestCase` already but apparently only an `IOException` in `ESIntegTestCase`. I think that would result in test failures already but for the avoidance of doubt I opened https://github.com/elastic/elasticsearch/pull/85238 to make this a proper assertion.
