### PR TITLE
ESQL - Include thread names in profile output

### LINKED ISSUE #123053: ESQL: Capture running thread in `status`
### Description

While working on an ESQL mystery on a slow cluster @dnhatn and I were thinking it'd be really nice if the `status` that comes back from ESQL includes the name of the last thread that was running it. That'd be useful to correlate with `hot_threads`. Without that we have to look at the stack trace and compare with the `Operator` status and make an educated guess. That's usually ok, but less guessing in an emergency is better.

### PR DESCRIPTION
**Pull request by not-napoleon**
Resolves https://github.com/elastic/elasticsearch/issues/123053

This adds the thread name to the driver sleep profile output.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/DriverSleeps.java [hunk 1]
```diff
@@ -31,18 +31,28 @@
 public record DriverSleeps(Map<String, Long> counts, List<Sleep> first, List<Sleep> last) implements Writeable, ToXContentObject {
     /**
      * A record of a time the driver slept.
-     * @param reason The reason the driver slept
-     * @param sleep Millis since epoch when the driver slept
-     * @param wake Millis since epoch when the driver woke, or 0 if it is currently sleeping
+     *
+     * @param reason     The reason the driver slept
+     * @param threadName
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/DriverSleeps.java:36]: Fill this one in?

**Review by nik9000 — APPROVED** [review]
