### PR TITLE
ESQL: median, count and count_distinct over constants

### LINKED ISSUE #104900: ESQL: Inconsistent/buggy behavior for stats with null expression
Given an index `testidx` with, let's say, 5 documents in it, `from testidx | STATS some_agg_function(null)` behaves differently for different aggregations:

- `from testidx | STATS count(null)` returns the number of documents (like `count(*)`).
- `from testidx | STATS avg(null)` returns a row containing `null` for every document.
- `from testidx | STATS max(null)` returns a 500 (`{"type":"esql_illegal_argument_exception","reason":"unknown agg: class org.elasticsearch.xpack.ql.expression.Literal: null"}`)

### LINKED ISSUE #105248: ESQL: COUNT([1,2,3]) sometimes same as COUNT(*)
Correct, expected behavior for some queries:
```
row x = 1 | eval y = [1,2,3] | stats count(y), count([1,2,3]) by x

   count(y)    |count([1,2,3]) |       x       
---------------+---------------+---------------
3              |3              |1
```

For others, it seems like `count([1,2,3])` is treated as `count(*)`:
```
row x = 1 | stats count([1,2,3]) by x

count([1,2,3]) |       x       
---------------+---------------
1              |1
```
The behavior is the same for the two queries, resp., if we use `from some_idx` instead of `row`.

### PR DESCRIPTION
**Pull request by alex-spies**
Second batch of aggregations over constants for https://github.com/elastic/elasticsearch/issues/100634 . Makes `COUNT(constant)` consistent and adds `MEDIAN(const)` and `COUNT_DISTINCT(const)`.

- Fix https://github.com/elastic/elasticsearch/issues/105248 .
- Fix https://github.com/elastic/elasticsearch/issues/104900 .
- Fix wrong stats pushdown when multiple `COUNT` aggs are in the same `STATS`, e.g. for `FROM testidx | STATS s1 = count(1), rows = count(*)`

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -370,42 +370,17 @@ public void testAnotherCountAllWithFilter() {
...
 
-    /**
-     * Expected
-     * ProjectExec[[c{r}#3, c{r}#3 AS call, c_literal{r}#7]]
-     * \_LimitExec[1000[INTEGER]]
-     *   \_AggregateExec[[],[COUNT([2a][KEYWORD]) AS c, COUNT(1[INTEGER]) AS c_literal],FINAL,null]
-     *     \_ExchangeExec[[count{r}#18, seen{r}#19, count{r}#20, seen{r}#21],true]
-     *       \_EsStatsQueryExec[test], stats[Stat[name=*, type=COUNT, query=null], Stat[name=*, type=COUNT, query=null]]],
-     *         query[{"esql_single_value":{"field":"emp_no","next":{"range":{"emp_no":{"gt":10010,"boost":1.0}}},
-     *         "source":"emp_no > 10010@2:9"}}][count{r}#23, seen{r}#24, count{r}#25, seen{r}#26], limit[],
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java:381]: `| stats c = count(), call = count(*), c_literal = count(1)`  produced an `EsStatsQueryExec` that wasn't plannable by the LocalExecutionPlanner (`EsStatsQuery currently supports only one field statistic`).

I think a way to properly fix this is:
- normalize count(*), count(1), count(), count("foobar") all to count(*) as part of surrogate substitution
- deduplicate the counts - this requires refactoring `SubstituteExpressions` as its deduplication doesn't currently work well enough for this approach, and there's overlap with the deduplication happening in `ReplaceStatsAggExpressionWithEval`.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec [hunk 2]
```diff
@@ -1552,6 +1576,54 @@ s2point1:d | s_mv:i | languages:i
...
+2.1        | 0.5    | null
+;
+
+countDistinctOfConst#[skip:-8.13.99,reason:supported in 8.14]
+FROM employees
+| STATS s1 = count_distinct(1), s_mv = count_distinct([-1, 0, 3, 1, -1, 3]), s_null = count_distinct(null), s_param = count_distinct([-1, 0, 3, 1, -1, 3], 5) 
+;
+
+s1:l | s_mv:l | s_null:l | s_param:l
+1    | 4      | 0        | 4
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:1609]: s_mv = s_param looks weird.

Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:1609]: > s_mv = s_param looks weird.

The second/optional argument(precision), tricked me,  before knowing the count_distinct is approximate count distinct. It is irrelevant to the issue this PR addresses though. 

Some databases offers two ways to count distinct, perhaps we can consider later:
count(distinct <column>): this is an exact count, which may perform slow on large dataset
approximate_count_distinct function: this is an estimation.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java [hunk 3]
```diff
@@ -87,4 +93,30 @@ public Nullability nullable() {
...
+                    // return new Count(s, new Literal(s, StringUtils.WILDCARD, DataTypes.KEYWORD));
+                    return null;
+                }
+            }
+
+            // COUNT(const) is equivalent to MV_COUNT(const)*COUNT(*) if const is not null; otherwise COUNT(const) == 0.
+            return new Mul(
+                s,
+                new Coalesce(s, new MvCount(s, field), List.of(new Literal(s, 0, DataTypes.INTEGER))),
+                new Count(s, new Literal(s, StringUtils.WILDCARD, DataTypes.KEYWORD))
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java:116]: Elsewhere in the code we use the convention of Count(1) - let's apply that here as well.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java:381]: Once the count normalization happens, the deduplication should kick in (since all counts will be the same) and this type of query should work.
The critical bit here is normalization so count(*), count(1), count(), count(*) and count(1+1+2) all fold back to the same expression of count(1).

**Review by costin — APPROVED** [review]
Looks good over all. Since count(null) is problematic it makes sense to extract that piece of code and backport it to 8.14 as a bug fix.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java [hunk 4]
```diff
@@ -87,4 +93,30 @@ public Nullability nullable() {
...
         return EsqlTypeResolutions.isExact(field(), sourceText(), DEFAULT);
     }
+
+    @Override
+    public Expression surrogate() {
+        var s = source();
+        var field = field();
+
+        if (field.foldable()) {
+            if (field instanceof Literal l) {
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java:103]: Would love to just fold, but folding here is not safe unless we check if this will fold to `null`, first. That would require duplicating logic from `FoldNull`, though, which I'd prefer to avoid.

(Our evaluators cannot deal with null literals in general, and folding here results in the following exception when running e.g. `count(to_double(null))`:
```
illegal data type [null]
org.elasticsearch.xpack.esql.EsqlIllegalArgumentException: illegal data type [null]
	at __randomizedtesting.SeedInfo.seed([DBCF40F13A40EC92:539B7F2B94BC816A]:0)
	at org.elasticsearch.xpack.esql.CsvTests.stats.Asdf(stats.csv-spec:1708)
	at org.elasticsearch.xpack.esql.EsqlIllegalArgumentException.illegalDataType(EsqlIllegalArgumentException.java:43)
	at org.elasticsearch.xpack.esql.EsqlIllegalArgumentException.illegalDataType(EsqlIllegalArgumentException.java:39)
	at org.elasticsearch.xpack.esql.expression.function.scalar.convert.AbstractConvertFunction.evaluator(AbstractConvertFunction.java:65)
	at org.elasticsearch.xpack.esql.expression.function.scalar.convert.AbstractConvertFunction.toEvaluator(AbstractConvertFunction.java:105)
	at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper.fold(EvaluatorMapper.java:48)
	at org.elasticsearch.xpack.esql.expression.function.scalar.EsqlScalarFunction.fold(EsqlScalarFunction.java:30)
```
)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java:116]: Hm, I tried to look for other places where `Count(1)` is used, but couldn't verify this (for ESQL at least).

Parsing `count()` results in `new Count(source, "*", KEYWORD)`, we also use the same in `Sum.surrogate()` and the (currently disabled) `NormalizeAggregate` used to replace all `count(literal)` by `count(*)` as well.

For consistency, I'd like to stick to `count(*)` here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java:103]: Consider the rare case of count(1+1) - there might be count(1+null). This can be moved to a separate issue though to not block this one.

[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java:103]: It makes sense to add more tests to account for these cases where an expression is evaluated, esp. to `null`. I'll do that in another PR, as this one should be backported to 8.14 as soon as possible.

These cases are covered in this PR, it's just that they result in an extra eval+projection.

```
| STATS count(1+null)
```

becomes something equivalent to

```
| STATS x = count(*)
| EVAL `count(1+null)` = COALESCE(MV_COUNT(1+null), 0) * x
| KEEP `count(1+null)`
```

which after folding becomes a multiplication of `count(*)` with 0. If we wanted to, we could further optimize this case to avoid the `count(*)` as well.

[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Count.java:103]: Opened a PR with additional tests: https://github.com/elastic/elasticsearch/pull/107888
