### PR TITLE
Resolve/cluster handles IllegalArgumentException 'Unable to open connection'

### LINKED ISSUE #105489: [CI] ResolveClusterIT testClusterResolveDisconnectedAndErrorScenarios failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/waabwweardowk/tests/:server:internalClusterTest/org.elasticsearch.indices.cluster.ResolveClusterIT/testClusterResolveDisconnectedAndErrorScenarios

**Reproduction line:**
```
gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.cluster.ResolveClusterIT.testClusterResolveDisconnectedAndErrorScenarios" -Dtests.seed=2C3D776867410172 -Dtests.locale=es-MX -Dtests.timezone=Antarctica/DumontDUrville -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.indices.cluster.ResolveClusterIT#testClusterResolveDisconnectedAndErrorScenarios`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testClusterResolveDisconnectedAndErrorScenarios'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.indices.cluster.ResolveClusterIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: expected null, but was:<java.lang.IllegalStateException: Unable to open any connections to remote cluster [remote1]>

  at __randomizedtesting.SeedInfo.seed([2C3D776867410172:AFA3A5953C0174CA]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failNotNull(Assert.java:756)
  at org.junit.Assert.assertNull(Assert.java:738)
  at org.junit.Assert.assertNull(Assert.java:748)
  at org.elasticsearch.indices.cluster.ResolveClusterIT.testClusterResolveDisconnectedAndErrorScenarios(ResolveClusterIT.java:602)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by quux00**
Resolve/cluster should handle IllegalArgumentException 'Unable to open connection'
as connected=false and not display error. Scenario caught in failing IT test.

Fixes https://github.com/elastic/elasticsearch/issues/105489

### CODE REVIEW

**Review by kingherc — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterAction.java [hunk 1]
```diff
@@ -253,6 +253,9 @@ private boolean notConnectedError(Exception e) {
         if (e instanceof ConnectTransportException || e instanceof NoSuchRemoteClusterException) {
             return true;
         }
+        if (e instanceof IllegalStateException && e.getMessage().contains("Unable to open any connections")) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterAction.java:256]: having to compare the message to define the behaviour is really delicate. Are there other illegal state that are thrown? Do we need a different exception? I think we should look for a better way to do this.

**Comment by javanna** [comment]
This looks like a potential bug and we should mark it as such and backport the fix?

File: server/src/main/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterAction.java (hunk 1 above)
Comment (quux00) [reply server/src/main/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterAction.java:256]: That would take some discussion with the distributed team as who knows what other code depends on that model. If they change the error message, then this test will break and we can change it. And even if we don't, the issue is not serious (see below).

> This looks like a potential bug and we should mark it as such and backport the fix?

We could, but it's not serious. It's a cosmetic issue at best. The difference in behavior between before and after is whether an error message is included in addition to saying connected=false.

Here's the result now:

```
{
  "remote1": {
    "connected": false,
    "skip_unavailable": false,
  }
}
```

Here's the result without the additional handler added in this PR:

```
{
  "remote1": {
    "connected": false,
    "skip_unavailable": false,
    "error": "Unable to open any connections to [remote1]"
  }
}
```

The handlers I added to the code was to avoid putting error messages around connectivity, because `connected: false` is all the user really needs to see. If an unexpected error occurs, I default to `connected: false` to be safe and display the error message.
