### PR TITLE
EQL: make allow_no_indices true by default

### LINKED ISSUE #62986: EQL: `allow_no_indices` behavior
Currently EQL requires at least one index to match in order to validate the query. However just like [search](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-search.html#search-search-api-query-params), the `allow_no_indices` option is permitted which leads to confusing behavior since it can be true, yet EQL will throw an exception:
```
### A 

GET foo*/_search
# success

GET foo*/_eql/search
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo*]",


### B

GET foo/_search?ignore_unavailable=true
# success

GET foo/_eql/search?ignore_unavailable=true
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "index_not_found_exception",
# "reason" : "no such index [[foo]]",


### C 

GET foo/_search
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo]",

GET foo/_eql/search
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "mapping_exception",
# "reason" : "Unknown index [foo]",

### D 

GET foo*/_search?allow_no_indices=false
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo*]",

GET foo*/_eql/search?allow_no_indices=false
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "index_not_found_exception",
# "reason" : "no such index [foo*]",

GET foo*/_eql/search?allow_no_indices=true
{
  "size": 0,
  "query": "process where 1 == 1"
}
# "type" : "mapping_exception",
# "reason" : "Unknown index [*,-*]"
```

Considering the similarities to the search API, EQL should either provide a similar behavior or not accept this parameter.

### PR DESCRIPTION
**Pull request by astefan**
`allow_no_indices` is now `true` by default and, as before, can be set in the `_eql` request as a parameter. Irrespective of `allow_no_indices` value, throw verification_exception when there is no index validated from the provided patterns. If `allow_no_indices` is `false` and there is a pattern that results in a no index being returned, the Elasticsearch's mapping_exception is thrown.

Fixes https://github.com/elastic/elasticsearch/issues/62986.

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/PreAnalyzer.java [hunk 1]
```diff
@@ -6,16 +6,28 @@
...
 public class PreAnalyzer {
 
     public LogicalPlan preAnalyze(LogicalPlan plan, IndexResolution indices) {
+        EsIndex esIndex = null;
+        // wrap a potential index_not_found_exception with a VerificationException (expected by client)
+        try {
+            esIndex = indices.get();
+        } catch (MappingException me) {
+            throw new VerificationException(Collections.singletonList(Failure.fail(plan, me.getMessage())));
+        }
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/PreAnalyzer.java:28]: Use `indices.isValid` instead to check if the index is valid and if it's not, call toString() on it which returns the message instead of the index name.
Potentially pass the listener in the method to call `onFailure` with the failure instead of throwing it.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/session/EqlSession.java [hunk 2]
```diff
@@ -100,7 +100,7 @@ public void analyzedPlan(LogicalPlan parsed, ActionListener<LogicalPlan> listene
             listener.onFailure(new TaskCancelledException("cancelled"));
             return;
         }
-        indexResolver.resolveAsMergedMapping(indexWildcard, null, configuration.includeFrozen(), configuration.filter(),
+        indexResolver.resolveAsMergedMapping(indexWildcard, null, configuration.indicesOptions(), configuration.filter(),
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/session/EqlSession.java:103]: 👍

**Review by costin — APPROVED** [review]
Left a minor comment but LGTM otherwise.

**Comment by rylnd** [comment]
While this looks to be the behavior that we want, I'm wondering whether `allow_no_indices` is the correct option, here. This was discussed previously in https://github.com/elastic/elasticsearch/issues/62986#issuecomment-702897372 and I believe https://github.com/elastic/elasticsearch/issues/63295 captures the logical conclusion of that discussion.

Again, this is a blocker for EQL detections so I'm happy with any solution, but I wanted to re-raise the question since it had been raised previously.

**Comment by costin** [comment]
We think this solves it.In ES `allow_no_indices` is true by default while in ES it is not. The issue with index options is that they are applied *per* index not per request so:
`GET auditbeat-*,foo*/_eql/search` means `auditbeat-*` and `foo*` are checked in isolation: the former exists, the latter does not.
By using the default options, that is `allow_no_indices` to be true, ES will match auditbeat, ignore foo and then call us. Previously that did not happen since the index resolution was happening before EQL was triggered.
We still need to do validation in case of `GET foo*/_eql/search` as `allow_no_indices` is true and thus no mapping is found...
Hth,
