### PR TITLE
Fixes bug preventing script sort working on top_hits aggregation

### LINKED ISSUE #21022: script scoring in top hits aggregation produces IllegalArgumentException
_Note: Source is https://discuss.elastic.co/t/es-5-0-rc1-sorting-by-script-prevent-cachability-are-disabled-problem/63298_

**Elasticsearch version**: 5.0.0-rc1

**Plugins installed**: None

**JVM version**: 1.8.0_102

**OS version**: Mac OS X 15.6.0

**Description of the problem including expected versus actual behavior**:

Consider the following query:

```json
GET /_search
{
   "stored_fields": [
      "_type",
      "_id"
   ],
   "query": {
      "bool": {
         "must": [
            {
               "match_all": {}
            }
         ],
         "filter": [
            {
               "range": {
                  "echeance_max": {
                     "gte": "0"
                  }
               }
            }
         ]
      }
   },
   "aggs": {
      "par_types": {
         "terms": {
            "field": "type"
         },
         "aggs": {
            "lesplus_proches": {
               "top_hits": {
                  "sort": [
                     {
                        "_script": {
                           "type": "number",
                           "script": {
                              "lang": "painless",
                              "inline": "floor(abs((doc['altitude'].value)-search_altitude)/10)",
                              "params": {
                                 "search_altitude": 200
                              }
                           },
                           "order": "asc"
                        }
                     },
                     {
                        "geodistance": {
                           "geoloc": {
                              "lat": 39.9173,
                              "lon": 116.386
                           },
                           "order": "asc",
                           "unit": "km"
                        }
                     }
                  ],
                  "size": 1
               }
            }
         }
      }
   }
}
```

This produces:

```json
{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "features that prevent cachability are disabled on this context"
         }
      ]
   }
}
```

### PR DESCRIPTION
**Pull request by colings86**
Previous to this change any request using a script sort in a top_hits
aggregation would fail because the compilation of the script happened
after the QueryShardContext was frozen (after we had worked out if the
request is cachable).

This change moves the calling of build() on the SortBuilder to the
TopHitsAggregationBuilder which means that the script in the script_sort
will be compiled before we decide whether to cache the request and freeze
the context.

Closes #21022

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

File: core/src/test/java/org/elasticsearch/search/aggregations/metrics/TopHitsIT.java [hunk 1]
```diff
@@ -1020,6 +1021,18 @@ public void testDontCacheScripts() throws Exception {
         assertThat(client().admin().indices().prepareStats("cache_test_idx").setRequestCache(true).get().getTotal().getRequestCache()
                 .getMissCount(), equalTo(0L));
 
+        // Test that a request using a script sort does not get cached
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/search/aggregations/metrics/TopHitsIT.java]: any chance we can get this as a rest test?

Comment (colings86) [inline core/src/test/java/org/elasticsearch/search/aggregations/metrics/TopHitsIT.java]: Unfortunately not as the rest tests do not install the modules so you can't currently tests scripts in rest tests
