### PR TITLE
Testing: Add test rule to repeat tests on binding exceptions

### LINKED ISSUE #9010: [CI failure] NettyTransportMultiPortTests Address already in use
The test fails because it tries to bind to a port which is already in use:

```
Caused by: java.net.BindException: Address already in use
    [...sun.*]
    org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
    org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
    org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
```

See: 
http://build-us-00.elasticsearch.org/job/es_core_1x_strong/1799/testReport/junit/junit.framework/TestSuite/org_elasticsearch_transport_netty_NettyTransportMultiPortTests/

### PR DESCRIPTION
**Pull request by spinscale**
Due to the possibility of ports being already used when choosing a
random port, it makes sense to simply repeat a unit test upon a bind
exception.

This commit adds a junit rule, which does exactly this and does not
require you to change the test code and add loops.

Closes #9010

### CODE REVIEW

File: src/test/java/org/elasticsearch/transport/netty/RepeatOnBindExceptionRule.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+     *
+     * @param logger the es logger from the test class
+     * @param retryCount number of amounts to try a single test before failing
+     */
+    public RepeatOnBindExceptionRule(ESLogger logger, int retryCount) {
+        this.logger = logger;
+        this.retryCount = retryCount;
+    }
+
+    public Statement apply(final Statement base, Description description) {
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/transport/netty/RepeatOnBindExceptionRule.java]: `@Override`?

File: src/test/java/org/elasticsearch/transport/netty/RepeatOnBindExceptionRule.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+            public void evaluate() throws Throwable {
+                Throwable caughtThrowable = null;
+
+                for (int i = 0; i < retryCount; i++) {
+                    try {
+                        base.evaluate();
+                        return;
+                    } catch (BindTransportException t) {
+                        caughtThrowable = t;
+                        logger.info("Bind exception happened happened, rerunning the test", t);
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/transport/netty/RepeatOnBindExceptionRule.java]: just one `happened`? Also, nit, but maybe use `occurred`?

**Comment by rjernst** [comment]
LGTM, just a couple minor comments.

File: src/test/java/org/elasticsearch/transport/netty/RepeatOnBindExceptionRule.java [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+            public void evaluate() throws Throwable {
+                Throwable caughtThrowable = null;
+
+                for (int i = 0; i < retryCount; i++) {
+                    try {
+                        base.evaluate();
+                        return;
+                    } catch (BindTransportException t) {
+                        caughtThrowable = t;
+                        logger.info("Bind exception occured, rerunning the test after [{}] failures", t, i+1);
```
Comment (javanna) [inline src/test/java/org/elasticsearch/transport/netty/RepeatOnBindExceptionRule.java]: occurred with 2 Rs :)
