### PR TITLE
Fix handling indexed envelopes crossing the dateline in mvt API

### LINKED ISSUE #91060: Envelopes crossing the dateline are not handled properly in vector tiles API
Adding the following envelope to an index:

```
DELETE shape

PUT shape/
{
  "mappings": {
    "properties": {
      "geoLocationBox": {"type": "geo_shape"}
    }
  }
}

POST shape/_doc
{
  "geoLocationBox": {
    "type": "envelope",
    "coordinates": [
      [
        10.0,
        10.0
      ],
      [
        -10.0,
        -10.0
      ]
    ]
  }
}
```

If we try to plot it using vector tiles it gives the wrong bounding box as it should cross the dateline:

image

### PR DESCRIPTION
**Pull request by iverase**
This PR makes sure an envelope crossing the dateline generates a mutipolygon when creating a mvt feature so it is render properly.

fixes https://github.com/elastic/elasticsearch/issues/91060

### CODE REVIEW

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java [hunk 1]
```diff
@@ -150,7 +150,61 @@ private Geometry normalize(Geometry geometry) {
         }
     }
 
-    public void testFetchSourceValueDateLine() throws IOException {
+    public void testFetchSourcePolygonDateLine() throws IOException {
+        assertFetchSourceGeometry(
+            "POLYGON((170 -10, -170 -10, -170 10, 170 10, 170 -10))",
+            "MULTIPOLYGON (((180.0 -10.0, 180.0 10.0, 170.0 10.0, 170.0 -10.0, 180.0 -10.0)),"
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java:156]: I'm curious why the polygon test has a single polygon split to a multipolygon by the function:

    fetchSourceValue(mapper, sourceValue, "wkt")

But the BBOX is not split by the same function in the envelope test?

Perhaps this is not part of this PR, since this PR focuses on MVT, and the MVT call:

    fetchSourceValue(mapper, sourceValue, "mvt(0/0/0@4096)")

Does seem to split both the polygon and the envelope.

**Review by craigtaverner — APPROVED** [review]
LGTM, although I did have one question.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java [hunk 2]
```diff
@@ -161,38 +215,12 @@ public void testFetchSourceValueDateLine() throws IOException {
...
 
-        String mvtPolygonDateLine = "MULTIPOLYGON (((180.0 -10.0, 180.0 10.0, 170.0 10.0, 170.0 -10.0, 180.0 -10.0)),"
-            + "((-180.0 10.0, -180.0 -10.0, -170.0 -10.0, -170.0 10.0, -180.0 10.0)))";
+        assertEquals(List.of(jsonValue), fetchSourceValue(mapper, sourceValue, null));
+        assertEquals(List.of(wktValue), fetchSourceValue(mapper, sourceValue, "wkt"));
 
-        List<?> mvtExpected = fetchSourceValue(mapper, mvtPolygonDateLine, "mvt(0/0/0@256)");
-        List<?> mvt = fetchSourceValue(mapper, sourceValue, "mvt(0/0/0@256)");
+        List<?> mvtExpected = fetchSourceValue(mapper, mvtEquivalentAsWKT, "mvt(0/0/0@4096)");
+        List<?> mvt = fetchSourceValue(mapper, sourceValue, "mvt(0/0/0@4096)");
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java:223]: The tests still pass with the original `@256`, what was the reason for changing to `@4096`? I presume it was just to match the default value?

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java (hunk 1 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java:156]: I thought about the same. The didn't like the options I had to return a split geometry. Either return a multipolygon which didn't feel right for an input envelope, or a geometry collection containing two envelopes which I did not like it either.

Therefore I decided to return it unchanged. We can visit it later if it dies not feel right.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java (hunk 2 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java]: that's weird, I changed it so the extent is random.
