### PR TITLE
Normalize malformed aggregate_double_metric

### LINKED ISSUE #90572: `aggregate_metric_double` stores it's subfields in `_ignore`
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

When you configure an `aggregate_metric_double` with `ignore_malformed: true` and send a malformed value we create an `_ignored` field with three values, `field.value_count`, `field.min`, and `field.max`. This is the only top "composite" field that creates `_ignored` values for its children. Things like shape only create `field` in `_ignored`. Is there a good reason for `aggregate_metric_double` to be different?

### Steps to Reproduce

see above

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nik9000**
This makes `ignore_malformed` for `aggregate_double_metric` save just the top level field name into the meta `_ignored` field, like every other field. It does so by pulling part of the parsing logic back from it's delegate numeric fields. Now it uses the delegates to parse the value and to save the values, but not to handle malformed values. Instead, it handles malformed values itself on the top level.

Doing this made it fairly simple to solve two other issues:
* `ignore_malformed` had to remove non-malformed values that had previously been added to the document. Now we only save the values after all have been parsed.
* When we validate some of the values we use to have to dig them out of the document using inefficient code that was written mostly for testing. Now that we're saving the values before adding them to the document it's easy enough to validate from that list instead which amounts to a single array access.

Closes #90572

### CODE REVIEW

File: x-pack/plugin/mapper-aggregate-metric/src/test/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapperTests.java [hunk 1]
```diff
@@ -209,23 +204,6 @@ public void testValueCountDouble() throws Exception {
...
-            MapperParsingException.class,
-            () -> mapper.parse(
-                source(b -> b.startObject("field").field("min", 10.0).field("max", 50.0).field("value_count", 77.33).endObject())
-            )
-        );
-        assertThat(
-            e.getCause().getMessage(),
-            containsString("failed to parse field [field.value_count] of type [integer] in document with id '1'.")
-        );
-    }
```
Comment (nik9000) [inline x-pack/plugin/mapper-aggregate-metric/src/test/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapperTests.java:227]: This is tested as part of the `exampleMalformedValues`.

File: server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java [hunk 2]
```diff
@@ -1693,23 +1693,21 @@ protected void parseCreateField(DocumentParserContext context) throws IOExceptio
      * @throws IllegalArgumentException if there was an error parsing the value from the json
      * @throws IOException if there was any other IO error
      */
-    private static Number value(XContentParser parser, NumberType numberType, Number nullValue, boolean coerce)
-        throws IllegalArgumentException, IOException {
-
+    public Number value(XContentParser parser) throws IllegalArgumentException, IOException {
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java:1696]: This'll need javadoc if we want to keep it. It's sort of leaky, but I've done worse. It's for a good cause.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java [hunk 3]
```diff
@@ -601,84 +610,66 @@ protected void parseCreateField(DocumentParserContext context) throws IOExceptio
...
+                if (metricsParsed.containsKey(m) == false) {
+                    throw new IllegalArgumentException(
+                        "Aggregate metric field [" + mappedFieldType.name() + "] must contain all metrics " + metrics
+                    );
+                }
+            }
+            // Check that there aren't any duplicates already parsed
+            for (Metric m : metricsParsed.keySet()) {
+                NumberFieldMapper delegateFieldMapper = metricFieldMappers.get(m);
+                if (context.doc().getByKey(delegateFieldMapper.fieldType().name()) != null) {
```
Comment (csoulios) [inline x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:646]: Method `Document.onlyAddKey()` was supposed to check for duplicate fields in the doc. I think this method is called from `NumferFieldMapper.indexValue()`. In this case the duplicates check is performed twice.

**Review by csoulios — COMMENTED** [review]
I think the big dilemma here is if we want to expose the parse/index methods of the `NumberFieldMapper`  class. I don't see why not to.

I have left some small comments.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java (hunk 3 above)
Comment (nik9000) [reply x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:646]: Yeah. I suppose I don't need to check this. It's just passing the right exception message back. I *think* don't need to check this because a duplicate will fail with the first key every time - because we don't index unless all keys are present. That's what I did above.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java [hunk 4]
```diff
@@ -601,84 +610,66 @@ protected void parseCreateField(DocumentParserContext context) throws IOExceptio
...
+            Number valueCount = metricsParsed.get(Metric.value_count);
+            if (valueCount != null && valueCount.intValue() < 0) {
                 throw new IllegalArgumentException(
-                    "Aggregate metric field [" + mappedFieldType.name() + "] must contain all metrics " + metrics.toString()
+                    "Aggregate metric [" + Metric.value_count + "] of field [" + mappedFieldType.name() + "] cannot be a negative number"
                 );
             }
+
+            // Check if all required metrics have been parsed.
+            for (Metric m : metrics) {
```
[the remark this answers is not in the document]
Comment (nik9000) [reply x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:636]: :+1:

File: server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java (hunk 2 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java:1696]: Maybe @romseygeek should have a look here too.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java [hunk 5]
```diff
@@ -582,6 +579,18 @@ protected void parseCreateField(DocumentParserContext context) throws IOExceptio
...
+
+                @Override
+                public void accept(IllegalArgumentException e) throws IOException {
+                    if (ignoreMalformed && context.parser().currentToken().isValue()) {
+
+                    }
+                    someMalformedValues = true;
+                }
+            }
+            MalformedHandler onMalformed = new MalformedHandler();
```
[the remark this answers is not in the document]
Comment (nik9000) [reply x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:593]: Uh..... Its been a while since I wrote this and I can't find it. Maybe it's a leftover of another attempt. I'll get back to you.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java [hunk 6]
```diff
@@ -601,84 +610,66 @@ protected void parseCreateField(DocumentParserContext context) throws IOExceptio
...
-            } else {
-                // Rethrow exception as is. It is going to be caught and nested in a MapperParsingException
-                // by its FieldMapper.MappedFieldType#parse()
-                throw e;
+                context.addIgnoredField(name());
+                context.path().remove();
+                return;
             }
+            // Rethrow exception as is. It is going to be caught and nested in a MapperParsingException
+            // by its FieldMapper.MappedFieldType#parse()
```
Comment (romseygeek) [inline x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:667]: Just `FieldMapper#parse` I think?

File: server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java (hunk 2 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java:1696]: Yep fine by me.

**Review by romseygeek — COMMENTED** [review]
This makes sense to me, happy to have another look when @csoulios 's feedback has been addressed.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java (hunk 3 above)
Comment (nik9000) [reply x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:646]: I think this method deserves another visit because I see us constantly doing a test like this one to get a better error message. I'd like to smooth it a bit in a follow up if that's ok
.

File: x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java (hunk 6 above)
Comment (romseygeek) [reply x-pack/plugin/mapper-aggregate-metric/src/main/java/org/elasticsearch/xpack/aggregatemetric/mapper/AggregateDoubleMetricFieldMapper.java:652]: This comment still applies

**Review by romseygeek — APPROVED** [review]
One nit in a comment, LGTM otherwise

**Review by csoulios — APPROVED** [review]
LGTM!
