### PR TITLE
Re-throw ResponseException as AssertionError in BasicLicenseUpgradeIT

### LINKED ISSUE #64578: [CI] Failure in org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic
```
./gradlew ':x-pack:qa:rolling-upgrade-basic:v7.9.4#oldClusterTest' --tests "org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic" -Dtests.seed=5B22100B1FCA9959 -Dtests.security.manager=true -Dtests.locale=hr-HR -Dtests.timezone=Africa/Algiers -Druntime.java=8
```

failed in https://gradle-enterprise.elastic.co/s/7n4cfvbfcywl6/console-log?anchor=12279 with

```

org.elasticsearch.upgrades.BasicLicenseUpgradeIT > testOldAndMixedClusterHaveActiveBasic FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:42229], URI [/_license], status line [HTTP/1.1 404 Not Found] |  
  | { } |  
  | at __randomizedtesting.SeedInfo.seed([5B22100B1FCA9959:78F3B9C5F9CAB7D8]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:318) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262) |  
  | at org.elasticsearch.upgrades.BasicLicenseUpgradeIT.checkBasicLicense(BasicLicenseUpgradeIT.java:27) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:991) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:976) |  
  | at org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic(BasicLicenseUpgradeIT.java:17)
```

Does not reproduce locally.

### PR DESCRIPTION
**Pull request by fcofdez**
It's possible that in a slow machine the cluster state updates
take a while to be applied, the license information is published
with NORMAL priority, meaning that it can take a while for the
License information to become available. This can lead to race
conditions. In order to wait until the license information is
available, the tests use assertBusy, but assertBusy only retries
if an AssertionException is raised, for that reason we use the 
`ignore` parameter in the http client and later check that the
response was correct, meaning that the check can be retried
if the license information is not ready yet.

Closes #64578

### CODE REVIEW

File: x-pack/qa/rolling-upgrade-basic/src/test/java/org/elasticsearch/upgrades/BasicLicenseUpgradeIT.java [hunk 1]
```diff
@@ -24,20 +25,30 @@ public void testNewClusterHasActiveNonExpiringBasic() throws Exception {
 
     @SuppressWarnings("unchecked")
     private void checkBasicLicense() throws Exception {
-        Response licenseResponse = client().performRequest(new Request("GET", "/_license"));
-        Map<String, Object> licenseResponseMap = entityAsMap(licenseResponse);
-        Map<String, Object> licenseMap = (Map<String, Object>) licenseResponseMap.get("license");
-        assertEquals("basic", licenseMap.get("type"));
-        assertEquals("active", licenseMap.get("status"));
+        try {
```
Comment (DaveCTurner) [inline x-pack/qa/rolling-upgrade-basic/src/test/java/org/elasticsearch/upgrades/BasicLicenseUpgradeIT.java:28]: Does this work as an alternative? This way it only retries on a 404:

```
        final Request request = new Request("GET", "/_license");
        request.addParameter("ignore", "404");
        Response licenseResponse = client().performRequest(request);
        assertOK(licenseResponse);
```

Comment (fcofdez) [reply x-pack/qa/rolling-upgrade-basic/src/test/java/org/elasticsearch/upgrades/BasicLicenseUpgradeIT.java]: I didn't know about the `ignore` parameter, that looks much better 👍

**Review by DaveCTurner — APPROVED** [review]
LGTM

File: x-pack/qa/rolling-upgrade-basic/src/test/java/org/elasticsearch/upgrades/BasicLicenseUpgradeIT.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/qa/rolling-upgrade-basic/src/test/java/org/elasticsearch/upgrades/BasicLicenseUpgradeIT.java]: Full disclosure: nor did I until just now :grin:
