### PR TITLE
Remove option to configure custom config file via CONF_FILE or -Des.default.conf

### LINKED ISSUE #5329: CONF_FILE in /etc/sysconfig not used by startup script on RedHat
I'm facing a issue with node default parameters in the system configuration file (/etc/sysconfig/elasticsearch) on a RedHat Linux installation : the 
definition of the node configuration file is ignored by the standard startup script.

Environment:
- Redhat Linux RHEL 6.2
- Elasticsearch 1.0.1 (elasticsearch-1.0.1-1.noarch.rpm)

### Problems:

1) custom config file defined in /etc/sysconfig is ignored

The file /etc/sysconfig/elasticsearch contains default parameters used by the startup script /etc/init.d/elasticsearch to intialize the node. The parameter CONF_FILE, as its name suggests, contains the name of the configuration file. By default, it is defined like this:
    
```
    # Elasticsearch configuration file (elasticsearch.yml)
    CONF_FILE=/etc/elasticsearch/elasticsearch.yml 
```

If this value is changed to another location, the node will start but the new configuration will be ignored.
   
2) relative config file in /etc/sysconfig prevents node startup
  
In file /etc/sysconfig/elasticsearch, another parameter named CONF_DIR defines the Elasticsearch configuration directory, where other config files like logging.yml will be found:
    
```
    # Elasticsearch conf directory
    CONF_DIR=/etc/elasticsearch
```

According to the CONF_FILE comment, it should be possible to give a relative file name (elasticsearch.yml), but it does not work, the node will not start using standard service command.

### How to reproduce:

0) prerequisites

- install elasticsearch-1.0.1-1.noarch.rpm on a RedHat/Centos system
- create a new configuration file called foobar.yml in /etc/elasticsearch with specific parameters, for example the cluster name:
    
    ```
    cluster.name: foobar
    ```
          
1) custom config file
      
- edit file /etc/sysconfig/elasticsearch and change the CONF_FILE value to the new configuration file:
    
    ``` 
    CONF_FILE=/etc/elasticsearch/foobar.yml
    ```
          
- start the server using the service command:
    
    ```
    service elasticsearch start
    ```
        
- check the cluster name using the REST API:
    
    ``` 
    curl http://localhost:9200/_nodes?pretty=true
    ```
         
- the cluster name is still the default "elasticsearch", new configuration file was not used.    

2) relative standard config file

- edit file /etc/sysconfig/elasticsearch and change the CONF_FILE value to a relative name of an existing file in the CONF_DIR directory:
    
    ```
    CONF_FILE=elasticsearch.yml
    ```
        
- start the server using the service command:
    
    ```
    service elasticsearch start
    ```
        
- the startup fails with exit code 6 (configuration file not found), however the file $CONF_DIR/$CONF_FILE exits !      

### Workaround:

In file /etc/sysconfig/elasticsearch, pass the config file in the Java options : 
  
```
    ES_JAVA_OPTS="-Des.config=/etc/elasticsearch/foobar.yml"
```
    
If the config argument is not absolute (foobar.yml), the file will be searched in the $CONF_DIR directory during Elasticsearch startup (Java code). But it's not very clean, because :
  
- you can't use CONF_FILE in JAVA_OPTS, because it's defined later in the sysconfig file
- you still need an absolute CONF_FILE, because it's existence is directly checked in the init.d script    
- you'll have to remember that CONF_FILE is not really used by the node...

### How to solve:

1) in /etc/init.d/elasticsearch, line 88, in the daemon launch command line, define the es.config property using the $CONF_FILE variable :
  
```
    daemon --user $ES_USER --pidfile $pidfile $exec -p $pidfile -d \
        -Des.default.path.home=$ES_HOME \
        -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR \
        -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR \
        -Des.config=$CONF_FILE
```
    
(maybe es.default.config would be better than es.config ?)
    
This way, the configuration specified in the sysconfig file is really used by the node (solves problem n°1).  
    
2) in /etc/init.d/elasticsearch, line 68, replace the current configuration file existence test :
  
```
    [ -f $CONF_FILE ] || exit 6        # line 68
```

by this one:

```
    [ -f $CONF_FILE ] || [ -f $CONF_DIR/$CONF_FILE ] || exit 6
```

This test reproduce better the one made in the Java code (first check for an absolute configuration file, then for a relative one in the configuration directory, then in the classpath, else fail). Now, the configuration file can be absolute or relative, it works without surprise (solves problem n°2).

What do you think ?

### LINKED ISSUE #13715: Drop support for CONF_FILE
Right now you can configure Elasticsearch to read its configuration from either a `CONF_FILE` or a `CONF_DIR` but the `CONF_FILE` directive isn't consistently implemented because its default (`$CONF_DIR/elasticsearch.yml`) is finicky to get right.

So lets remove it in the spirit of simplification. See discussion about it in #13687 for more.

### PR DESCRIPTION
**Pull request by brwe**
It is rarely used and was not consistently handled by different distributions anyway.
This commit also adds a test for specifying CONF_DIR when installing plugins and
starting elasticsearch.

relates to #12712  and #12954
closes #5329
closes #13715

Would be great if someone with a windows machine could test the bat file, I unfortunately can't.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java [hunk 1]
```diff
@@ -85,24 +85,6 @@ public static Environment prepareEnvironment(Settings input, Terminal terminal)
...
-            if (Strings.hasText(System.getProperty("es.config"))) {
-                loadFromEnv = false;
-                output.loadFromPath(environment.configFile().resolve(System.getProperty("es.config")));
-            }
-            if (Strings.hasText(System.getProperty("elasticsearch.config"))) {
-                loadFromEnv = false;
-                output.loadFromPath(environment.configFile().resolve(System.getProperty("elasticsearch.config")));
-            }
-        }
         if (loadFromEnv) {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java]: I think the local `loadFromEnv` and be removed?

File: distribution/src/main/resources/bin/service.bat [hunk 2]
```diff
@@ -207,4 +207,8 @@ set /a conv=%conv% * 1024
 set "%~2=%conv%"
 goto:eof
 
+:conffileset
+echo CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in config folder and cannot be renamed.
```
Comment (rjernst) [inline distribution/src/main/resources/bin/service.bat]: in config -> in the config

File: distribution/src/main/resources/bin/plugin [hunk 3]
```diff
@@ -59,6 +53,12 @@ if [ -n "$ES_ENV_FILE" ]; then
   fi
 fi
 
+# CONF_FILE setting was removed
+if [ ! -z "$CONF_FILE" ]; then
+    echo "CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in config folder and cannot be renamed."
```
Comment (rjernst) [inline distribution/src/main/resources/bin/plugin]: in config folder -> in the config directory

Note I suggest directory here instead of folder, since this is a nix script

File: distribution/src/main/resources/bin/elasticsearch-systemd-pre-exec [hunk 4]
```diff
@@ -0,0 +1,7 @@
+#!/bin/sh
+
```
Comment (rjernst) [inline distribution/src/main/resources/bin/elasticsearch-systemd-pre-exec]: in config folder -> in the config directory

File: distribution/src/main/resources/bin/elasticsearch [hunk 5]
```diff
@@ -42,10 +42,25 @@
 # Be aware that you will be entirely responsible for populating the needed
 # environment variables.
 
-
 # Maven will replace the project.name with elasticsearch below. If that
 # hasn't been done, we assume that this is not a packaged version and the
 # user has forgotten to run Maven to create a package.
+
+if [ `echo $@ | grep -c "es.default.conf" ` -gt 0 ]; then
+  echo "es.default.conf setting is no longer supported. elasticsearch.yml must be placed in config folder and cannot be renamed."
```
Comment (rjernst) [inline distribution/src/main/resources/bin/elasticsearch]: in config folder -> in the config directory

Comment (rjernst) [inline distribution/src/main/resources/bin/elasticsearch]: Ditto other places in this file.

File: distribution/rpm/src/main/packaging/init.d/elasticsearch [hunk 6]
```diff
@@ -49,6 +49,12 @@ if [ -f "$ES_ENV_FILE" ]; then
     . "$ES_ENV_FILE"
 fi
 
+# CONF_FILE setting was removed
+if [ ! -z "$CONF_FILE" ]; then
+    echo "CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in config folder and cannot be renamed."
```
Comment (rjernst) [inline distribution/rpm/src/main/packaging/init.d/elasticsearch]: in config folder -> in the config directory

File: distribution/deb/src/main/packaging/init.d/elasticsearch [hunk 7]
```diff
@@ -93,10 +90,16 @@ if [ -f "$DEFAULT" ]; then
 	. "$DEFAULT"
 fi
 
+# CONF_FILE setting was removed
+if [ ! -z "$CONF_FILE" ]; then
```
Comment (rjernst) [inline distribution/deb/src/main/packaging/init.d/elasticsearch]: in config folder -> in the config directory

**Comment by rjernst** [comment]
LGTM, I left a couple very minor comments.

File: qa/vagrant/src/test/resources/packaging/scripts/plugin_test_cases.bash [hunk 8]
```diff
@@ -83,6 +83,56 @@ else
...
+    [ $status = 1 ]
+    CONF_FILE="$ESCONFIG/elasticsearch.yml" run sudo -E -u $ESPLUGIN_COMMAND_USER "$ESHOME/bin/plugin" remove jvm-example
+    echo "status is $status"
+    [ $status = 1 ]
+}
+
+@test "[$GROUP] start elasticsearch with a custom CONFIG_FILE and check failure" {
+    local CONF_FILE="$ESCONFIG/elasticsearch.yml"
+
+    if is_dpkg ; then
```
Comment (nik9000) [inline qa/vagrant/src/test/resources/packaging/scripts/plugin_test_cases.bash]: No space here I think.

File: qa/vagrant/src/test/resources/packaging/scripts/plugin_test_cases.bash [hunk 9]
```diff
@@ -83,6 +83,56 @@ else
...
+        echo "CONF_FILE=$CONF_FILE" >> /etc/default/elasticsearch;
+    elif is_rpm; then
+        echo "CONF_FILE=$CONF_FILE" >> /etc/sysconfig/elasticsearch;
+    fi
+
+    if [ -f "/tmp/elasticsearch/bin/elasticsearch" ]; then
```
Comment (nik9000) [inline qa/vagrant/src/test/resources/packaging/scripts/plugin_test_cases.bash]: This part feels similar to start_elasticsearch_service in packaging_test_utils.bash - can you share any more code here?

**Comment by nik9000** [comment]
I also left some pretty minor comments.

**Comment by electrical** [comment]
Where does the systemd pre-exec file come from ?

**Comment by brwe** [comment]
@nik9000 @rjernst thanks for the review! addressed all comments.
@electrical I added the file to check if CONF_FILE was defined and not start elasticsearch if so. I don't know systemd too well so if there is another way to have this check before we start elasticsearch I'd be happy to change that.

**Comment by brwe** [comment]
Chatted with @spinscale who wanted the check for `-Des` params to be moved from bin/elasticsearch script to Bootstrap. I added a commit for that too. I [reordered logging conf initialization](https://github.com/elastic/elasticsearch/pull/13772/files#diff-40fe9ad3b9a0769a26fe81051263be3dR240) so that we get a proper message, not sure though if this is problematic?

**Comment by brwe** [comment]
@rjernst or @nik9000 or @spinscale  can you take another look?

**Comment by brwe** [comment]
Forgot to add that I tried out the service.bat on windows now too. Thanks @dliappis for the help!

**Comment by nik9000** [comment]
LGTM

File: qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash [hunk 10]
```diff
@@ -239,18 +239,62 @@ clean_before_test() {
...
+        run service elasticsearch status
+        [ "$status" -eq 0 ]
+    fi
+}
+
+# Start elasticsearch
+# $1 expected status code
+# $2 additional command line args
+run_elasticsearch_service() {
+    # Set the CONF_DIR setting in case we start as a service
```
Comment (nik9000) [inline qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash]: I'd probably save $1 and $2 to named variables because they can get confusing lower down.

File: qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash [hunk 11]
```diff
@@ -239,18 +239,62 @@ clean_before_test() {
...
         # to tick along
-        sudo -u elasticsearch bash <<BASH
+        run sudo -u elasticsearch bash <<BASH
 # If jayatana is installed then we try to use it. Elasticsearch should ignore it even when we try.
 # If it doesn't ignore it then Elasticsearch will fail to start because of security errors.
 # This line is attempting to emulate the on login behavior of /usr/share/upstart/sessions/jayatana.conf
 [ -f /usr/share/java/jayatanaag.jar ] && export JAVA_TOOL_OPTIONS="-javaagent:/usr/share/java/jayatanaag.jar"
 # And now we can start Elasticsearch normally, in the background (-d) and with a pidfile (-p).
-/tmp/elasticsearch/bin/elasticsearch -d -p /tmp/elasticsearch/elasticsearch.pid
+timeout 60s /tmp/elasticsearch/bin/elasticsearch $BACKGROUND -p /tmp/elasticsearch/elasticsearch.pid -Des.path.conf="$CONF_DIR" $2
```
Comment (nik9000) [inline qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash]: The timeout feels funky when we are backgrounding elasticsearch. Maybe don't use it there?

File: qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash [hunk 12]
```diff
@@ -262,31 +306,11 @@ BASH
...
-        run systemctl is-active elasticsearch.service
-        [ "$status" -eq 0 ]
-
-        run systemctl status elasticsearch.service
-        [ "$status" -eq 0 ]
-
-    elif is_sysvinit; then
-        run service elasticsearch status
-        [ "$status" -eq 0 ]
+        [ "$status" -eq $1 ]
```
Comment (nik9000) [inline qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash]: This would be clearer is `$1` were `$expected_status` or something.

**Comment by brwe** [comment]
@nik9000 addressed all comments. I made the timeout now dependent on if we run in background or not but my bash is that of a 3 year old so if you have any suggestion to improve readability don't hold back.

**Comment by nik9000** [comment]
LGTM

**Comment by bstascavage** [comment]
This was actually a feature we used and this required me to re-architecture our cluster deployment.  I have no idea why, in 2015, you would remove the ability to specify a config file, and instead for the user to have a config file be a specific filename.  Obviously the damage is done, but I would dispute the claim that it is 'It is rarely used'
