### PR TITLE
Fix update_by_query's default size parameter

### LINKED ISSUE #26761: _update_by_query's default size accidentally changed to 1000
**Describe the feature**:  `scroll_size` seems to be ignored in my request

**Elasticsearch version** (`bin/elasticsearch --version`):  6.0.0-beta2

**Plugins installed**: []

**JVM version** (`java -version`): JDK 8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

No matter what value I set for `scroll_size`, the following request only updates 1,000 documents:
```
POST crimes/_update_by_query?scroll_size=4000
{
  "query" : {
    "match": {
      "area.ward": "6"
    }
  },
  "script" : {
    "source" : "ctx._source.area.ward=10"
  }
}
```
Here is the response I get:
```
{
  "took": 112,
  "timed_out": false,
  "total": 1000,
  "updated": 1000,
  "deleted": 0,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": []
}
```

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by nik9000**
We were accidentally defaulting it to the scroll size.
Untwists some of the tricks that we play with parsing
so that the size is no longer scrambled.

Closes #26761

### CODE REVIEW

**Comment by nik9000** [comment]
I've tagged @cbuescher to review this because I *think* this came from a refactoring that he was involved with. Though I admit my memory is pretty hazy.

I added both an integration test for the behavior and unit tests for the parsing because I really don't want this to happen again.

File: core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java [hunk 1]
```diff
@@ -74,7 +75,7 @@ public String getName() {
     public RestChannelConsumer prepareRequest(final RestRequest request, final NodeClient client) throws IOException {
         SearchRequest searchRequest = new SearchRequest();
         request.withContentOrSourceParamParserOrNull(parser ->
-            parseSearchRequest(searchRequest, request, parser));
+            parseSearchRequest(searchRequest, request, parser, size -> searchRequest.source().size(size)));
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java]: can this be `searchReqeust.source()::size`

**Review by s1monw — APPROVED** [review]
LGTM

File: core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java (hunk 1 above)
Comment (nik9000) [reply core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java]: I read your comment and though "of course it can" and implemented it and everything failed. I then remembered why I wrote it this way in the first place: `search.source()` is null at this time.

Comment (s1monw) [reply core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java]: oh hmm but it might be null later too no? should we protect against that?

Comment (nik9000) [reply core/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java]: I can't be null later but I admit to it being weird. I'll leave a comment explaining.
