### PR TITLE
Lucene with Java 1.9 doesn't support unmap in MMapDirectory until Lucene 6.4.0

### LINKED ISSUE #22495: Tests: LuceneTests are failing on Java9
Seems that `LuceneTests.testMMapHackSupported` fails regularly on Java 9 right now, independent from the ES version

```
REPRODUCE WITH: gradle :core:test -Dtests.seed=ECC3BC902EFF7263 -Dtests.class=org.elasticsearch.common.lucene.LuceneTests -Dtests.method="testMMapHackSupported" -Dtests.security.manager=true -Dtests.jvm.argline="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED" -Dtests.locale=mas-KE -Dtests.timezone=Zulu
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.1+java9-periodic/540/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+java9-periodic/1324/console

### PR DESCRIPTION
**Pull request by mikemccand**
The Java APIs for unmapping are changing, and Lucene 6.4.0 will support it correctly, so until then we need an assume in this test case.

See https://issues.apache.org/jira/browse/LUCENE-6989 for details.

Closes #22495

### CODE REVIEW

**Comment by mikemccand** [comment]
This PR is against 5.0 branch ... I'll also port to 5.1 branch, but 5.x (5.2) does not need this since it's using a Lucene 6.4.x snapshot release that has the fixes from https://issues.apache.org/jira/browse/LUCENE-6989

**Review by nik9000 — APPROVED** [review]

**Comment by s1monw** [comment]
LGTM2

**Comment by uschindler** [comment]
Stupid question: Why not use `Constants.JRE_IS_MINIMUM_JAVA9 '

This is important because Java 9's spec version starts with 9, not 1.9! Are you sure your patch works?

File: core/src/test/java/org/elasticsearch/common/lucene/LuceneTests.java [hunk 1]
```diff
@@ -405,6 +406,7 @@ public void testAsSequentialAccessBits() throws Exception {
      */
     public void testMMapHackSupported() throws Exception {
         // add assume's here if needed for certain platforms, but we should know if it does not work.
+        assumeTrue("Lucene 6.3.0 doesn't support unmap with Java 9", Constants.JVM_SPEC_VERSION.startsWith("1.9") == false);
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/lucene/LuceneTests.java]: We use `assumeFalse(Constants.JRE_IS_MINIMUM_JAVA9);` elsewhere`, I don't think this is right since the version string no longer has the leading `1.`.

**Comment by mikemccand** [comment]
Ooh, good point: I will switch to `Constants.JRE_IS_MINIMUM_JAVA9` constant instead!

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by mikemccand** [comment]
> Are you sure your patch works?

It did not before :)  Now it does: I tested on 1.9-ea+151 with the crazy gradle options: `gradle '-Dtests.jvm.argline=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED' test -Dtests.class=org.elasticsearch.common.lucene.LuceneTests`

Thanks for the feedback!

**Comment by uschindler** [comment]
Like in Lucene we are waiting for Groovy 2.4.8 😶😣. This fixes the Gradle problems, too. You just have to replace and rename the groovy jar file in your Gradle installation. The vote is ongoing...
