### PR TITLE
Fix scroll contexts counter in SearchService

### LINKED ISSUE #56202: Elasticsearch queries with scroll stopped working
Elasticsearch version: 7.6.2
Plugins installed: -
JVM version: shipped with ES (openjdk version "13.0.2" 2020-01-14)
OS: Centos 7 (kernel 3.10.0-862.14.4.el7.x86_64)

Bug description:
   Queries with 'scroll' feature stopped working even on very small indices and with v.high value for search.max_open_scroll_context (5000000). Getting error 500 'Trying to create too many scroll contexts' even if node stats doesn't show any open contexts or "scroll current".

Steps to reproduce:
   No idea unfortunately. But it started when several heavy searches using scroll were running at the end of month. Initially it worked well but then it stopped and doesn't work anymore for any index/query. 

[ES_BUG_DEBUG.txt](https://github.com/elastic/elasticsearch/files/4581044/ES_BUG_DEBUG.txt)

### PR DESCRIPTION
**Pull request by dnhatn**
Unfortunately, the backport of #53449 to 6.8 and 7.6.2 weren't correct. The scroll context counter can be negative even become `Integer.MAX_VALUE` after handling many search requests. This bug causes two issues:

- Disable the limit of open scroll contexts when the counter is negative
- Prevent opening new scroll contexts when the counter is greater than the limit of open scroll contexts

This bug was already fixed in 7.7 and later. I will add the assertions in this PR to 7.x and master.

Kudos to @jerryjune for this finding.

Closes #56202

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 1]
```diff
@@ -1023,6 +1028,13 @@ public int getActiveContexts() {
         return this.activeContexts.size();
     }
 
+    /**
+     * Returns the number of opening scroll contexts.
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:1032]:
```suggestion
     * Returns the number of scroll contexts opened on the node
```

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks Jim!
