### PR TITLE
Simplify and Fix Synchronization in InternalTestCluster

### LINKED ISSUE #37275: [CI] multiple tests started failing with NoNodeAvailableException
Seems to be triggered by the first test to run for the class. 

## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/170/console

## Reproduction line 
does not reproduce locally
```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=7030014DD5B5A0EB \
  -Dtests.class=org.elasticsearch.xpack.security.authc.TokenAuthIntegTests \
  -Dtests.method="testRefreshAsDifferentUser" \
  -Dtests.security.manager=true \
  -Dtests.locale=th \
  -Dtests.timezone=Pacific/Apia \
  -Dcompiler.java=12 \
  -Druntime.java=8

```

## Example relevant log:
```
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{tZDl3ofZSsybqfW_cz1-iw}{127.0.0.1}{127.0.0.1:35230}]]
	at __randomizedtesting.SeedInfo.seed([7030014DD5B5A0EB:E8D192FF96C2C519]:0)
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:351)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:249)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:386)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1217)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:113)
	at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:142)
	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:79)
	at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:378)
	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
	at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:386)
	at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2217)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

## Frequency
Up to 5 times per day.

### LINKED ISSUE #37345: CI: test failure PrimaryAllocationIT.testForceStaleReplicaToBePromotedToPrimaryOnWrongNode
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1198/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu&&virtual/174/console

## Reproduction line 
does not reproduce locally
```
/gradlew :server:integTest -Dtests.seed=ED29DBC5949B19E9 -Dtests.class=org.elasticsearch.cluster.routing.PrimaryAllocationIT -Dtests.method="testForceStaleReplicaToBePromotedToPrimaryOnWrongNode" -Dtests.security.manager=true -Dtests.locale=cs -Dtests.timezone=Europe/Kaliningrad -Dcompiler.java=11 -Druntime.java=8
```

## Example relevant log:
```
10:28:30 ERROR   4.30s J3 | PrimaryAllocationIT.testForceStaleReplicaToBePromotedToPrimaryOnWrongNode <<< FAILURES!
10:28:30    > Throwable #1: java.lang.NullPointerException
10:28:30    > 	at __randomizedtesting.SeedInfo.seed([ED29DBC5949B19E9:D46FFB23117F3451]:0)
10:28:30    > 	at org.elasticsearch.cluster.routing.PrimaryAllocationIT.testForceStaleReplicaToBePromotedToPrimaryOnWrongNode(PrimaryAllocationIT.java:282)
10:28:30    > 	at java.lang.Thread.run(Thread.java:748)
```

## Frequency
up to 8-9 a day.

Possibly related to: #35497

### LINKED ISSUE #37965: [CI] HotThreadsIT.testHotThreadsDontFail failure on master
Logs: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/211/console

REPRODUCE WITH:
```
/gradlew :server:integTest \
  -Dtests.seed=233C30BFCE2B7117 \
  -Dtests.class=org.elasticsearch.action.admin.HotThreadsIT \
  -Dtests.method="testHotThreadsDontFail" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-MX \
  -Dtests.timezone=Asia/Yerevan \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Couldn't reproduce locally (100+ iterations)

```
  1> [2019-01-29T15:44:34,933][INFO ][o.e.c.c.Coordinator      ] [node_s1] setting initial configuration to VotingConfiguration{FOMFnLR6RaC0dEzMnFkJ1A,saAXE5n_SbeS_kPuGtZ9eQ,{bootstrap-placeholder}-node_s2}
  1> [2019-01-29T15:44:35,350][INFO ][o.e.c.s.MasterService    ] [node_s1] elected-as-master ([2] nodes joined)[{node_s0}{FOMFnLR6RaC0dEzMnFkJ1A}{6t1ue7wmTM626qcAoGXuVw}{127.0.0.1}{127.0.0.1:35907} elect leader, {node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], node-join[{node_s2}{2TYkOhZXTt-QaPNJgYFNsw}{DbhzCUXTR7SBzAU85okUDQ}{127.0.0.1}{127.0.0.1:41242} join existing leader], term: 1, version: 1, reason: master node changed {previous [], current [{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}]}, added {{node_s0}{FOMFnLR6RaC0dEzMnFkJ1A}{6t1ue7wmTM626qcAoGXuVw}{127.0.0.1}{127.0.0.1:35907},{node_s2}{2TYkOhZXTt-QaPNJgYFNsw}{DbhzCUXTR7SBzAU85okUDQ}{127.0.0.1}{127.0.0.1:41242},}
  1> [2019-01-29T15:44:35,492][INFO ][o.e.c.s.ClusterApplierService] [node_s0] master node changed {previous [], current [{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}]}, added {{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437},{node_s2}{2TYkOhZXTt-QaPNJgYFNsw}{DbhzCUXTR7SBzAU85okUDQ}{127.0.0.1}{127.0.0.1:41242},}, term: 1, version: 1, reason: ApplyCommitRequest{term=1, version=1, sourceNode={node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}}
  2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=233C30BFCE2B7117 -Dtests.class=org.elasticsearch.action.admin.HotThreadsIT -Dtests.method="testHotThreadsDontFail" -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=Asia/Yerevan -Dcompiler.java=11 -Druntime.java=8
  1> [2019-01-29T15:44:35,494][INFO ][o.e.c.s.ClusterApplierService] [node_s2] master node changed {previous [], current [{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}]}, added {{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437},{node_s0}{FOMFnLR6RaC0dEzMnFkJ1A}{6t1ue7wmTM626qcAoGXuVw}{127.0.0.1}{127.0.0.1:35907},}, term: 1, version: 1, reason: ApplyCommitRequest{term=1, version=1, sourceNode={node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}}
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/centos/server/build/testrun/integTest/J3/temp/org.elasticsearch.action.admin.HotThreadsIT_233C30BFCE2B7117-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {field1.keyword=PostingsFormat(name=Asserting), field1=PostingsFormat(name=Asserting), _id=PostingsFormat(name=Asserting)}, docValues:{field1.keyword=DocValuesFormat(name=Lucene70), _seq_no=DocValuesFormat(name=Lucene70), _primary_term=DocValuesFormat(name=Lucene70), _version=DocValuesFormat(name=Lucene70)}, maxPointsInLeafNode=128, maxMBSortInHeap=5.534645509088748, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@7769dd0e), locale=es-MX, timezone=Asia/Yerevan
  2> NOTE: Linux 2.6.32-754.10.1.el6.x86_64 amd64/Oracle Corporation 1.8.0_202 (64-bit)/cpus=16,threads=1,free=465545688,total=513802240
  1> [2019-01-29T15:44:35,497][INFO ][o.e.n.Node               ] [integ_1] started
  2> NOTE: All tests run in this JVM: [HotThreadsIT]
  1> [2019-01-29T15:44:35,497][INFO ][o.e.n.Node               ] [integ_3] started
  1> [2019-01-29T15:44:35,504][INFO ][o.e.c.s.ClusterApplierService] [node_s1] master node changed {previous [], current [{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}]}, added {{node_s0}{FOMFnLR6RaC0dEzMnFkJ1A}{6t1ue7wmTM626qcAoGXuVw}{127.0.0.1}{127.0.0.1:35907},{node_s2}{2TYkOhZXTt-QaPNJgYFNsw}{DbhzCUXTR7SBzAU85okUDQ}{127.0.0.1}{127.0.0.1:41242},}, term: 1, version: 1, reason: Publication{term=1, version=1}
  1> [2019-01-29T15:44:35,516][INFO ][o.e.n.Node               ] [integ_2] started
  1> [2019-01-29T15:44:35,544][INFO ][o.e.c.s.MasterService    ] [node_s1] node-join[{node_sc3}{aV_f9mFyTOWlZhplwSEfxQ}{qceQ1ZilTLikPSqFG3IJ4w}{127.0.0.1}{127.0.0.1:45343} join existing leader], term: 1, version: 2, reason: added {{node_sc3}{aV_f9mFyTOWlZhplwSEfxQ}{qceQ1ZilTLikPSqFG3IJ4w}{127.0.0.1}{127.0.0.1:45343},}
  1> [2019-01-29T15:44:35,578][INFO ][o.e.c.s.ClusterApplierService] [node_s2] added {{node_sc3}{aV_f9mFyTOWlZhplwSEfxQ}{qceQ1ZilTLikPSqFG3IJ4w}{127.0.0.1}{127.0.0.1:45343},}, term: 1, version: 2, reason: ApplyCommitRequest{term=1, version=2, sourceNode={node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}}
  1> [2019-01-29T15:44:35,578][INFO ][o.e.c.s.ClusterApplierService] [node_sc3] master node changed {previous [], current [{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}]}, added {{node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437},{node_s0}{FOMFnLR6RaC0dEzMnFkJ1A}{6t1ue7wmTM626qcAoGXuVw}{127.0.0.1}{127.0.0.1:35907},{node_s2}{2TYkOhZXTt-QaPNJgYFNsw}{DbhzCUXTR7SBzAU85okUDQ}{127.0.0.1}{127.0.0.1:41242},}, term: 1, version: 2, reason: ApplyCommitRequest{term=1, version=2, sourceNode={node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}}
  1> [2019-01-29T15:44:35,579][INFO ][o.e.n.Node               ] [integ_4] started
  1> [2019-01-29T15:44:35,580][INFO ][o.e.c.s.ClusterApplierService] [node_s0] added {{node_sc3}{aV_f9mFyTOWlZhplwSEfxQ}{qceQ1ZilTLikPSqFG3IJ4w}{127.0.0.1}{127.0.0.1:45343},}, term: 1, version: 2, reason: ApplyCommitRequest{term=1, version=2, sourceNode={node_s1}{saAXE5n_SbeS_kPuGtZ9eQ}{IlVsI13pT3m97zB9kigMBw}{127.0.0.1}{127.0.0.1:43437}}
  1> [2019-01-29T15:44:35,633][INFO ][o.e.c.s.ClusterApplierService] [node_s1] added {{node_sc3}{aV_f9mFyTOWlZhplwSEfxQ}{qceQ1ZilTLikPSqFG3IJ4w}{127.0.0.1}{127.0.0.1:45343},}, term: 1, version: 2, reason: Publication{term=1, version=2}
  1> [2019-01-29T15:44:35,750][INFO ][o.e.g.GatewayService     ] [node_s1] recovered [0] indices into cluster_state
  1> [2019-01-29T15:44:36,331][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s1] adding template [random_index_template] for index patterns [*]
  1> [2019-01-29T15:44:36,402][INFO ][o.e.a.a.HotThreadsIT     ] [testHotThreadsDontFail] [HotThreadsIT#testHotThreadsDontFail]: all set up test
  1> [2019-01-29T15:44:36,416][INFO ][o.e.a.a.HotThreadsIT     ] [testHotThreadsDontFail] using custom data_path for index: [HudQrFRmGG]
  1> [2019-01-29T15:44:36,455][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s1] [test] creating index, cause [api], templates [random_index_template], shards [6]/[1], mappings []
  1> [2019-01-29T15:44:37,806][INFO ][o.e.a.a.HotThreadsIT     ] [testHotThreadsDontFail] Index [3] docs async: [true] bulk: [false]
  1> [2019-01-29T15:44:38,270][INFO ][o.e.c.r.a.AllocationService] [node_s1] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][5], [test][1], [test][0], [test][3], [test][2]] ...]).
  1> [2019-01-29T15:44:38,427][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/Xna3aYPaSLezRRHL3OvARQ] create_mapping [type1]
  1> [2019-01-29T15:44:40,095][INFO ][o.e.p.PluginsService     ] [testHotThreadsDontFail] no modules loaded
  1> [2019-01-29T15:44:40,095][INFO ][o.e.p.PluginsService     ] [testHotThreadsDontFail] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
  1> [2019-01-29T15:44:40,318][INFO ][o.e.p.PluginsService     ] [testHotThreadsDontFail] no modules loaded
  1> [2019-01-29T15:44:40,318][INFO ][o.e.p.PluginsService     ] [testHotThreadsDontFail] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
  1> [2019-01-29T15:45:10,475][INFO ][o.e.a.a.HotThreadsIT     ] [testHotThreadsDontFail] [HotThreadsIT#testHotThreadsDontFail]: cleaning up after test
  1> [2019-01-29T15:45:10,487][WARN ][o.e.t.OutboundHandler    ] [node_s1] send message failed [channel: NioSocketChannel{localAddress=/127.0.0.1:43437, remoteAddress=/127.0.0.1:57414}]
  1> java.io.IOException: Connection reset by peer
  1> 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
  1> 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:?]
  1> 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:?]
  1> 	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[?:?]
  1> 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:?]
  1> 	at org.elasticsearch.nio.SocketChannelContext.flushToChannel(SocketChannelContext.java:336) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.BytesChannelContext.singleFlush(BytesChannelContext.java:87) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.BytesChannelContext.flushChannel(BytesChannelContext.java:59) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.EventHandler.handleWrite(EventHandler.java:139) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.handleWrite(NioSelector.java:390) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.writeToChannel(NioSelector.java:339) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.SocketChannelContext.sendMessage(SocketChannelContext.java:143) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.nio.MockNioTransport$MockSocketChannel.sendMessage(MockNioTransport.java:314) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.OutboundHandler.internalSendMessage(OutboundHandler.java:80) ~[main/:?]
  1> 	at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:70) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:737) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.lambda$new$1(TcpTransport.java:162) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportHandshaker.handleHandshake(TransportHandshaker.java:98) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1018) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:921) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:752) ~[main/:?]
  1> 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:779) ~[main/:?]
  1> 	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:241) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:213) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:47) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:398) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) ~[elasticsearch-nio-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
  1> [2019-01-29T15:45:10,495][WARN ][o.e.t.TransportService   ] [node_s1] Received response for a request that has timed out, sent [30076ms] ago, timed out [0ms] ago, action [internal:coordination/fault_detection/follower_check], node [{node_s0}{FOMFnLR6RaC0dEzMnFkJ1A}{6t1ue7wmTM626qcAoGXuVw}{127.0.0.1}{127.0.0.1:35907}], id [146]
  1> [2019-01-29T15:45:10,655][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_s1] [test/Xna3aYPaSLezRRHL3OvARQ] deleting index
  1> [2019-01-29T15:45:11,051][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s1] removing template [random_index_template]
  1> [2019-01-29T15:45:11,084][INFO ][o.e.p.PluginsService     ] [testHotThreadsDontFail] no modules loaded
  1> [2019-01-29T15:45:11,085][INFO ][o.e.p.PluginsService     ] [testHotThreadsDontFail] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
  1> [2019-01-29T15:45:11,176][INFO ][o.e.a.a.HotThreadsIT     ] [testHotThreadsDontFail] [HotThreadsIT#testHotThreadsDontFail]: cleaned up after test
  1> [2019-01-29T15:45:11,177][INFO ][o.e.a.a.HotThreadsIT     ] [testHotThreadsDontFail] after test
ERROR   44.7s J3 | HotThreadsIT.testHotThreadsDontFail <<< FAILURES!
   > Throwable #1: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{EF_FcOpLTPeZQ_LUVd5MNA}{127.0.0.1}{127.0.0.1:43437}]]
   > 	at __randomizedtesting.SeedInfo.seed([233C30BFCE2B7117:71D6155E6A3F7E85]:0)
   > 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:351)
   > 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:249)
   > 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
   > 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:386)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
   > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
   > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
   > 	at org.elasticsearch.action.admin.HotThreadsIT.testHotThreadsDontFail(HotThreadsIT.java:125)
   > 	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* Remove unnecessary `synchronized` statements
  * Add some asserts in their place where useful
* Make `Predicate`s constants where possible
* Cleanup some stream usage
* Make unsafe public methods `synchronized`
* Make fields `final` where possible
* Fix possible races from concurrent access to `nodes` (we were using it in the unicast hosts file builder without any sync!)
   * Make `nodes` synchronized as the docs claim already
   * Synchronize for bulk operations on it when not synchronized on `this` or make a copy where possible to avoid the lock on `this`
* Closes #37965 
* Closes #37275 
* Closes #37345

### CODE REVIEW

**Comment by original-brownbear** [comment]
@DaveCTurner found a bunch more possible races here than hit #39118, not sure if you want to review this or I should find someone else? :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 1]
```diff
@@ -2140,16 +2139,12 @@ public synchronized String startNode(Settings settings) {
         return startNodes(numNodes, settings1);
     }
 
-    public synchronized List<String> startDataOnlyNodes(int numNodes) {
-        return startDataOnlyNodes(numNodes, Settings.EMPTY);
-    }
-
-    public synchronized List<String> startDataOnlyNodes(int numNodes, Settings settings) {
+    public List<String> startDataOnlyNodes(int numNodes) {
         Settings settings1 = Settings.builder()
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: nit: Also rename `settings1` to settings.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 2]
```diff
@@ -2245,7 +2240,7 @@ public void clearDisruptionScheme() {
         clearDisruptionScheme(true);
     }
 
-    public void clearDisruptionScheme(boolean ensureHealthyCluster) {
+    public synchronized void clearDisruptionScheme(boolean ensureHealthyCluster) {
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: This method can wait for a healthy cluster. I think having the entire method synchronized while waiting for the cluster to become healthy could potentially lead to deadlocks?

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 3]
```diff
@@ -2492,7 +2448,7 @@ public void ensureEstimatedStats() {
     }
 
     @Override
-    public void assertAfterTest() throws IOException {
+    public synchronized void assertAfterTest() throws IOException {
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: This method accesses the cluster and holding the monitor while doing so could potentially lead to deadlocks?

**Review by henningandersen — COMMENTED** [review]
Thanks for looking into this @original-brownbear .

I am inclined to think that making nodes immutable and creating a new map when adding/removing from the map is a better approach. Especially getClients() is problematic, but also the way we currently rely on the `InternalTestCluster` monitor ensuring `nodes` is not changed when reading from `nodes`. Having it as an immutable map makes it easy and cheap to ensure consistent snapshots for the map. Also, it is then obvious that anything accessing `nodes` will never block.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 4]
```diff
@@ -826,21 +827,19 @@ public synchronized Client client(String nodeName) {
...
-        return null; // can't happen
+        throw new AssertionError("No node found with name: [" + nodeName + "]");
     }
 
 
     /**
      * Returns a "smart" node client to a random node in the cluster
      */
-    public synchronized Client smartClient() {
+    public Client smartClient() {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Wops you're right, thanks for spotting that!

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 5]
```diff
@@ -1371,6 +1385,12 @@ public void assertConsistentHistoryBetweenTranslogAndLuceneIndex() throws IOExce
         }
     }
 
+    private NavigableMap<String, NodeAndClient> currentNodes() {
+        synchronized (nodes) {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Yea, let's do that. We really only have 3 spots where we mutate the map anyway :) On it

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 6]
```diff
@@ -1515,26 +1520,24 @@ public ClusterService clusterService() {
...
     /**
      * Returns an Iterable to all instances for the given class &gt;T&lt; across all nodes in the cluster.
      */
-    public synchronized <T> Iterable<T> getInstances(Class<T> clazz) {
-        List<T> instances = new ArrayList<>(nodes.size());
-        for (NodeAndClient nodeAndClient : nodes.values()) {
-            instances.add(getInstanceFromNode(clazz, nodeAndClient.node));
+    public <T> Iterable<T> getInstances(Class<T> clazz) {
+        synchronized (nodes) {
+            return nodes.values().stream().map(node -> getInstanceFromNode(clazz, node.node)).collect(Collectors.toList());
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: It should be pretty quick since it's just a lookup on the DI map, but yea this is gonna resolve itself by moving to the immutable map for `nodes` :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 2 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Good question ..., I couldn't find a possible dead-lock in the implementations of our disruptions from a quick look over them.
My thinking would maybe be this:
If we don't synchronize here, we allow manipulating the cluster while we "wait for healthy" which could lead to some pretty hard to debug issues. Also, we really don't want to manipulate anything about the cluster while this method is in progress.
=> If we create some unforeseen deadlock here, I'd probably rather try to fix the implementation of the disruption to prevent the deadlock, then allow concurrent modification of the cluster while we clear the disruption?

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 3 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I think this should never run in parallel with other operations modifying the cluster and should not modify the cluster itself => Since we should only do reads on the state of cluster I think we won't dead-lock here ever and it's a lot easier to reason about a series of asserts when you at least have the guarantee that the cluster doesn't change between them isn't it?

**Comment by original-brownbear** [comment]
@henningandersen moved to an immutable `nodes` now as you suggested and answered the points that aren't automatically addressed by that. => This should be good for another review :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 7]
```diff
@@ -1242,13 +1254,13 @@ public synchronized void validateClusterFormed(String viaNode) {
...
     @Override
-    public synchronized void afterTest() throws IOException {
+    public synchronized void afterTest() {
         wipePendingDataDirectories();
         randomlyResetClients(); /* reset all clients - each test gets its own client based on the Random instance created above. */
     }
 
     @Override
-    public void beforeIndexDeletion() throws Exception {
+    public synchronized void beforeIndexDeletion() throws Exception {
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I think synchronized here is now unnecessary?

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 8]
```diff
@@ -1262,6 +1274,7 @@ public void beforeIndexDeletion() throws Exception {
     }
 
     private void assertSameSyncIdSameDocs() {
+        assert Thread.holdsLock(this);
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I think the assert* methods no longer need the lock to be safe?

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 9]
```diff
@@ -1355,9 +1370,8 @@ private void assertNoSnapshottedIndexCommit() throws Exception {
      * Asserts that the document history in Lucene index is consistent with Translog's on every index shard of the cluster.
      * This assertion might be expensive, thus we prefer not to execute on every test but only interesting tests.
      */
-    public void assertConsistentHistoryBetweenTranslogAndLuceneIndex() throws IOException {
-        final Collection<NodeAndClient> nodesAndClients = nodes.values();
-        for (NodeAndClient nodeAndClient : nodesAndClients) {
+    public synchronized void assertConsistentHistoryBetweenTranslogAndLuceneIndex() throws IOException {
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I think synchronized here is now unnecessary?

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 10]
```diff
@@ -1723,7 +1720,9 @@ private synchronized void stopNodesAndClients(Collection<NodeAndClient> nodeAndC
 
         for (NodeAndClient nodeAndClient: nodeAndClients) {
             removeDisruptionSchemeFromNode(nodeAndClient);
-            NodeAndClient previous = nodes.remove(nodeAndClient.name);
+            final NavigableMap<String, NodeAndClient> newNodes = new TreeMap<>(nodes);
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: This is duplicated at least once, I think we should refactor it into a method.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 2 above)
Comment (henningandersen) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: If there is any chance of manipulations during this phase, I would rather guard against manipulating the cluster explicitly by adding this intermediate closing (or stopped) state.

Do we not risk something like what you described in #39118. If the disruption prevented the result from returning, the callback could be called at this time. If that in turn calls any of the synchronized methods it could potentially deadlock if we have to create a new connection while becoming healthy?

At a minimum I think we should add a comment why the synchronized is there.

**Review by henningandersen — COMMENTED** [review]
`getClients` still has an issue (also prior to this PR) in that when you call next() it also calls `NodeAndClient.client()`, which lazily builds the client. I think this mandates solving that part of the problem using an explicit monitor (does it have to be the InternalTestCluster monitor to be safe wrt closing?) in NodeAndClient?

In turn I think this would remove the need for several of the client accessor methods to be synchronized (including smartClient).

Also (nit), `getClients()` does not need to be synchronized.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 11]
```diff
@@ -197,8 +206,8 @@
     static final int DEFAULT_MIN_NUM_CLIENT_NODES = 0;
     static final int DEFAULT_MAX_NUM_CLIENT_NODES = 1;
 
-    /* sorted map to make traverse order reproducible, concurrent since we do checks on it not within a sync block */
-    private final NavigableMap<String, NodeAndClient> nodes = new TreeMap<>();
+    /* sorted map to make traverse order reproducible.*/
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: What do you mean? There isn't really a special intention behind the deterministic traversal order other than that it causes the same test seed to always e.g. restart the same node if you restart a random node and such.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 7 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: My motivation was to prevent any changes from happening concurrently between the individual assertions in this method, but I guess you could argue that that would simply indicate a bug with the tests.
=> I'll drop the synchronization here :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 9 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Right dropping it :)

**Comment by original-brownbear** [comment]
> `getClients` still has an issue (also prior to this PR) in that when you call next() it also calls `NodeAndClient.client()`, which lazily builds the client. I think this mandates solving that part of the problem using an explicit monitor (does it have to be the InternalTestCluster monitor to be safe wrt closing?) in NodeAndClient?

I think for now let's sync on the `InternalTestCluster` yea, though we could look into a different way of syncing the `close` here next I guess.

> In turn I think this would remove the need for several of the client accessor methods to be synchronized (including smartClient).

:tada: true :)

**Comment by original-brownbear** [comment]
> If that in turn calls any of the synchronized methods it could potentially deadlock if we have to create a new connection while becoming healthy?

Not really I think because we're still on the same thread. The `ServiceDisruptionScheme#stopDisrupting` would have to create that new connection/client on a separate thread. Currently, we don't do that and I'm not sure we should start fixing this kind of thing. It will always be questionable to manipulate the cluster concurrently (even if we get it safe concurrency wise, the tests just become so hard to interpret).
I'll add a comment for now :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 10 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: done :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 2 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I added a comment for now. But I'm starting to think we're attacking this from the wrong angle to some degree. It seems like methods like this one (and a few others we now discussed) are currently only called from the main JUnit thread. Why, instead of worrying endlessly about how we sync. things like e.g. clearing the disruption while closing and such not just assert that we're on the main JUnit thread and simply not allow manipulating the cluster from elsewhere. We currently don't seem to be doing that and I don't see a good reason to start doing that kind of thing either (+ if someone needs this kind of thing down the line, they're free to add it as needed). 
IMO, that would make calls to e.g. `InternalTestCluster#restartRandomDataNode(org.elasticsearch.test.InternalTestCluster.RestartCallback)` a lot easier to follow/debug.
WDYT?

**Comment by original-brownbear** [comment]
@henningandersen Thanks for all the finds! All points addressed again I think :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (henningandersen) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I meant the intended use of the `nodes` field, ie. copy-on-write and reads are consistent as long as you read the field once only.

[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Ah sure :) Added 2 lines on that.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
BwC checker seems to just fail because BwC tests are disabled right now

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 12]
```diff
@@ -898,17 +894,19 @@ public boolean isMasterEligible() {
...
 
         Client client(Random random) {
-            if (closed.get()) {
-                throw new RuntimeException("already closed");
-            }
-            double nextDouble = random.nextDouble();
-            if (nextDouble < transportClientRatio) {
-                if (logger.isTraceEnabled()) {
-                    logger.trace("Using transport client for node [{}] sniff: [{}]", node.settings().get("node.name"), false);
+            synchronized (InternalTestCluster.this) {
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: I think the synchronized block and closed check should be moved to getOrBuildNodeClient and getOrBuildTransportClient. That way it also covers nodeClient() and transportClient() methods. I think calling `InternalTestCluster.masterClient` is unsafe in current form.

**Review by henningandersen — COMMENTED** [review]
Thanks @original-brownbear , I left just a few comments otherwise looking good.

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java (hunk 12 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Done :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 13]
```diff
@@ -1824,6 +1811,13 @@ private void restartNode(NodeAndClient nodeAndClient, RestartCallback callback)
         }
     }
 
+    private NodeAndClient removeNode(NodeAndClient nodeAndClient) {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Added the assert :)

File: test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java [hunk 14]
```diff
@@ -897,17 +892,19 @@ public boolean isMasterEligible() {
...
         Client client(Random random) {
-            if (closed.get()) {
-                throw new RuntimeException("already closed");
-            }
-            double nextDouble = random.nextDouble();
-            if (nextDouble < transportClientRatio) {
-                if (logger.isTraceEnabled()) {
-                    logger.trace("Using transport client for node [{}] sniff: [{}]", node.settings().get("node.name"), false);
+            synchronized (InternalTestCluster.this) {
+                if (closed.get()) {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java]: Added the assert :)

**Comment by original-brownbear** [comment]
@henningandersen thanks! all addressed I think :)

**Review by henningandersen — APPROVED** [review]
LGTM.

Thanks @original-brownbear

**Comment by original-brownbear** [comment]
@henningandersen thanks for the great review :)

**Comment by ywelsch** [comment]
Should this be backported to 7.0 (and possibly earlier) to avoid test failures?

**Comment by original-brownbear** [comment]
@ywelsch yea definitely! (sorry for forgetting that), I'll back port to 7.0 and will look into how tricky it is to get this into `6.7` (I remember that wasn't totally straight forward when I last checked)

**Comment by original-brownbear** [comment]
back ported to 7.0 in https://github.com/elastic/elasticsearch/pull/40013

**Comment by original-brownbear** [comment]
@ywelsch back porting this to `6.7` is somewhat complex and I think not necessary since 6.7 uses the blocking mock networking which isn't hit by the issue(s) that motivated this PR  in the first place.
