### PR TITLE
[CI] Adding continuous testing for ECS dynamic templates

### LINKED ISSUE #96713: [CI] Add ECS-mappings compatibility tests
https://github.com/elastic/elasticsearch/pull/96171 added dynamic templates that cover all ECS mappings.
Those were enhanced by https://github.com/elastic/elasticsearch/pull/96712 to be applicable with `subobjects: false` as well.

@P1llus wrote a [test](https://github.com/P1llus/testecs) that scans [ECS mapping artifact](https://github.com/elastic/ecs/blob/462b9e5ba80a38d48e5a4a5e14d65726956e512d/usage-example/generated/ecs/ecs_flat.yml#L4), creates a document with all ECS-matching fields, indexes it and verifies that all mappings are as expected.

We want to add this to CI so that it runs on a weekly basis, thus tests regressions in our ECS templates as well as notifying us when ECS gets updated in such a way that requires modification of the dynamic templates.

cc @felixbarny @ruflin

### PR DESCRIPTION
**Pull request by eyalkoren**
Closes #96713 

All three tests cases are covered:
- [x] a test document containing all ECS fields with random values in flattened form
- [x] a test document containing all ECS fields with random values in flattened form and index is set with `subobjects: false`
- [x] a test document containing all ECS fields with random values in nested/object form

In addition, I added verification that all ECS multi-field definitions are covered by the ECS dynamic templates (revealing two that actually were not).

@felixbarny @ruflin see if you agree with [my comment](https://github.com/elastic/elasticsearch/pull/97901/files#diff-5de719b6a576263ffb32a9a7a1754078f91b12abf0d4fe7141faeb7a91e6b66dR365-R367) about not failing if we create multi-field mapping even for fields of which ECS definition does not enforce such. 
For example, we define a multi-field mapping for the [`*.name`](https://github.com/elastic/elasticsearch/blob/1a254c2f08a54ca4ef4dac6760934f78ebff3b62/x-pack/plugin/core/template-resources/src/main/resources/ecs-dynamic-mappings.json#L115) pattern. If you look into the [ECS definitions](https://github.com/elastic/ecs/blob/main/generated/ecs/ecs_flat.yml), you will find that many `*.name` have multi-field mappings, while many others don't. Trying to be very accurate will result with many more dynamic templates.

@P1llus I assigned you as a reviewer because I think you were waiting for this in order to start migrating some ECS mappings to rely on the builtin dynamic templates.

### CODE REVIEW

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 1]
```diff
@@ -127,33 +138,61 @@ private static void prepareEcsDefinitions() throws IOException {
...
+            Assert.assertEquals(HttpStatus.SC_CREATED, response.getStatusLine().getStatusCode());
+        }
+
+        Request getMappingRequest = new Request("GET", "/" + indexName + "/_mapping");
+        // noinspection resource
+        Response response = ESRestTestCase.client().performRequest(getMappingRequest);
+        Assert.assertEquals(response.getStatusLine().getStatusCode(), HttpStatus.SC_OK);
+        Map<String, Object> mappingResponse;
+        try (
+            XContentParser parser = XContentFactory.xContent(XContentType.JSON)
```
Comment (rjernst) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:186]: A parser for json can be constructed as follows:

```
XContentParser parser = createParser(JsonXContent.jsonXContent, response.getEntity().getContent());
```

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 2]
```diff
@@ -127,33 +138,61 @@ private static void prepareEcsDefinitions() throws IOException {
...
+        }
+        // ensureGreen(indexName);
 
         Map<String, Object> flattenedFieldsMap = new HashMap<>();
         for (Map.Entry<String, Map<String, Object>> fieldEntry : ecsFlatFieldDefinitions.entrySet()) {
             String fieldName = fieldEntry.getKey();
             Map<String, Object> fieldDefinitions = fieldEntry.getValue();
             String type = (String) fieldDefinitions.get("type");
-            assertNotNull(
+            Assert.assertNotNull(
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:164]: Sure, those were added automatically by the IDE when I moved the file around to try placing it in different source-sets (where dependencies are different)

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 3]
```diff
@@ -56,62 +58,71 @@ public class EcsDynamicTemplatesIT extends ESIntegTestCase {
...
             ECS_DYNAMIC_TEMPLATES_FILE,
             Integer.toString(1),
-            TEMPLATE_VERSION_VARIABLE,
+            StackTemplateRegistry.TEMPLATE_VERSION_VARIABLE,
             Collections.emptyMap()
         );
-        ObjectMapper jsonObjectMapper = new ObjectMapper();
-        Map<?, ?> ecsDynamicTemplatesRaw = jsonObjectMapper.readValue(rawEcsComponentTemplate, Map.class);
+        Map<String, Object> ecsDynamicTemplatesRaw;
+        try (
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:75]: It's a try-with-resource usage, since the parser is `Closeable`

[the remark this answers is not in the document]
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:75]: The automatic formatting broke it into these lines, which makes it not so clear. I'll find a better way to make it more visible

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 4]
```diff
@@ -7,41 +7,43 @@
...
 import static org.hamcrest.Matchers.instanceOf;
 
 @SuppressWarnings("unchecked")
-@ESTestCase.WithoutSecurityManager
-@ESIntegTestCase.SuiteScopeTestCase
-public class EcsDynamicTemplatesIT extends ESIntegTestCase {
+public class EcsDynamicTemplatesIT extends ESRestTestCase {
+
+    @ClassRule
+    public static ElasticsearchCluster cluster = ElasticsearchCluster.local().module("mapper-extras").module("wildcard").build();
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:46]: I actually did that and the IDE changed it to be this way, I need to check why

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 5]
```diff
@@ -127,33 +138,61 @@ private static void prepareEcsDefinitions() throws IOException {
...
-        IndexResponse indexResponse = index("test-flattened-fields", "1", flattenedFieldsMap);
-        assertEquals(indexResponse.getResult(), DocWriteResponse.Result.CREATED);
 
-        GetMappingsResponse mappingsResponse = indicesAdmin().prepareGetMappings("test-flattened-fields").get();
-        assertThat(mappingsResponse.mappings().size(), equalTo(1));
-        Map<String, Object> mappings = mappingsResponse.mappings().entrySet().iterator().next().getValue().getSourceAsMap();
-        assertTrue(mappings.containsKey("properties"));
+        try (XContentBuilder bodyBuilder = JsonXContent.contentBuilder()) {
+            Request indexRequest = new Request("POST", "/" + indexName + "/_doc");
+            indexRequest.setJsonEntity(Strings.toString(bodyBuilder.map(flattenedFieldsMap)));
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:174]: I am not sure what I am missing here- this specific `Strings.toString(XContentBuilder)` overload seems to be a convenience method to do pretty much what you describe. 
Were you looking at other `Strings.toString()` overloads that eventually use the one I am using here?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 1 above)
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:186]: I cannot use it from a static context though...

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:47]: So the reason this gets change when I run this through my IDE's Gradle integration is that it applies spotless, that actually enforces it to be in a single line, probably because this line is <140 characters

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (rjernst) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:175]: Strings.toString will create an entirely other xcontent builder and copy this xcontent builder. But that isn't necessary, the one you created already has an in memory buffer that can be convert to a string as I described.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 1 above)
Comment (rjernst) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:187]: Why do you need a static context? This seems to be in a non-static test?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 6]
```diff
@@ -0,0 +1,400 @@
...
+        assertThat(errorMessage, mappings, instanceOf(Map.class));
+        Object dynamicTemplates = ((Map<?, ?>) mappings).get("mappings");
+        assertNotNull(errorMessage, dynamicTemplates);
+        assertThat(errorMessage, dynamicTemplates, instanceOf(Map.class));
+        assertEquals(errorMessage, 1, ((Map<?, ?>) dynamicTemplates).size());
+        assertTrue(errorMessage, ((Map<?, ?>) dynamicTemplates).containsKey("dynamic_templates"));
+        ecsDynamicTemplates = (Map<String, Object>) dynamicTemplates;
+    }
+
+    @SuppressForbidden(reason = "Opening socket connection to read ECS definitions from ECS GitHub repo")
```
Comment (eyalkoren) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: Note for reviewer: what would be the right way to download a file from GitHub? For now, I just used `@SuppressForbidden` to be able to test

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (rjernst) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java]: Looking at his again I see this version of Strings.toString will in fact use that internal byte buffer, so this looks fine as is.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 7]
```diff
@@ -0,0 +1,400 @@
...
+    @ClassRule
+    public static ElasticsearchCluster cluster = ElasticsearchCluster.local().module("mapper-extras").module("wildcard").build();
+
+    // The dynamic templates we test against
+    public static final String ECS_DYNAMIC_TEMPLATES_FILE = "/ecs-dynamic-mappings.json";
+
+    // The current ECS state (branch main) as a containing all fields in flattened form
+    private static final String ECS_FLAT_FILE_URL = "https://raw.githubusercontent.com/elastic/ecs/main/generated/ecs/ecs_flat.yml";
+
+    private static final Set<String> OMIT_FIELD_TYPES = Set.of("object", "flattened", "nested");
```
Comment (felixbarny) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:61]: I get why we omit `nested` mappings, but why do we omit `flattened` as well?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 8]
```diff
@@ -0,0 +1,400 @@
...
+            String type = (String) fieldDefinitions.get("type");
+            assertNotNull(
+                String.format(Locale.ENGLISH, "Can't find type for field '%s' in %s file", flattenedFieldName, ECS_DYNAMIC_TEMPLATES_FILE),
+                type
+            );
+            Object testValue = generateTestValue(type);
+            if (flattened) {
+                testFieldsMap.put(flattenedFieldName, testValue);
+            } else {
+                Map<String, Object> currentFiled = testFieldsMap;
```
Comment (felixbarny) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:213]:
```suggestion
                Map<String, Object> currentField = testFieldsMap;
```

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 9]
```diff
@@ -0,0 +1,400 @@
...
+            .forEach(field -> logger.error("ECS field '{}' is not covered by the current ECS dynamic templates", field));
+        shallowMultiFieldMapCopy.keySet().forEach(field -> {
+            int lastDotIndex = field.lastIndexOf('.');
+            String parentField = field.substring(0, lastDotIndex);
+            String subfield = field.substring(lastDotIndex + 1);
+            logger.error("ECS field '{}' is expected to have a multi-field mapping with subfield '{}'", parentField, subfield);
+        });
+        fieldToWrongMappingType.forEach((fieldName, actualMappingType) -> {
+            String ecsExpectedType = (String) ecsFlatFieldDefinitions.get(fieldName).get("type");
+            logger.error(
```
Comment (felixbarny) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:380]: Either the assertions or the error logs should contain some hints on how to fix the situation. Something like change ecs-dynamic-mappings.json and add a dynamic template to map field {} to type {}.

File: x-pack/plugin/core/template-resources/src/main/resources/ecs-dynamic-mappings.json [hunk 10]
```diff
@@ -114,7 +114,9 @@
               "*.executable",
               "*.name",
               "*.working_directory",
-              "*.full_name"
+              "*.full_name",
```
Comment (felixbarny) [inline x-pack/plugin/core/template-resources/src/main/resources/ecs-dynamic-mappings.json:117]: A nit and somewhat unrelated to this PR: you could make the dynamic template a bit more compact by merging `ecs_path_match_keyword_and_match_only_text` and `ecs_match_keyword_and_match_only_text` because both are doing a `path_match` now, after https://github.com/elastic/elasticsearch/pull/96712.

**Review by felixbarny — APPROVED** [review]
> @felixbarny @ruflin see if you agree with [my comment](https://github.com/elastic/elasticsearch/pull/97901/files#diff-5de719b6a576263ffb32a9a7a1754078f91b12abf0d4fe7141faeb7a91e6b66dR365-R367) about not failing if we create multi-field mapping even for fields of which ECS definition does not enforce such.
For example, we define a multi-field mapping for the [*.name](https://github.com/elastic/elasticsearch/blob/1a254c2f08a54ca4ef4dac6760934f78ebff3b62/x-pack/plugin/core/template-resources/src/main/resources/ecs-dynamic-mappings.json#L115) pattern. If you look into the [ECS definitions](https://github.com/elastic/ecs/blob/main/generated/ecs/ecs_flat.yml), you will find that many *.name have multi-field mappings, while many others don't. Trying to be very accurate will result with many more dynamic templates.

Seems like erring on the side of always creating a `match_only_text` subfield, even for cases where ECS only defines a `keyword` field for `*.name` fields.

I think that's fine. While on the one hand, this creates a bit more indexing overhead than strictly required, it brings a nice consistency via the naming convention `*.name` so that users know they can always do a full text search on fields ending with `*.name`.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 7 above)
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:61]: Good point! I relied on [testecs](https://github.com/elastic/testecs/blob/e4b0837b03d9a63ba6e71f5eb715065fc9050770/ecs.py#L49) on this one, but we should test our [`flattened` type dynamic template](https://github.com/elastic/elasticsearch/blob/735329e1108a085ef36734872244e925cc196a01/x-pack/plugin/core/template-resources/src/main/resources/ecs-dynamic-mappings.json#L177C10-L188) as well!

I will add it to the test, but the test value will always be nested under the flattened fields, otherwise this can't work with `subobjects: false`, where the field names are evaluated as root level, which means they cannot be matched against a `path_match`.

Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:61]: @P1llus why wasn't it tested originally? Do you see any reason not to test it here?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 11]
```diff
@@ -0,0 +1,416 @@
...
+public class EcsDynamicTemplatesIT extends ESRestTestCase {
+
+    @ClassRule
+    public static ElasticsearchCluster cluster = ElasticsearchCluster.local().module("mapper-extras").module("wildcard").build();
+
+    // The dynamic templates we test against
+    public static final String ECS_DYNAMIC_TEMPLATES_FILE = "ecs-dynamic-mappings.json";
+
+    // The current ECS state (branch main) containing all fields in flattened form
+    private static final String ECS_FLAT_FILE_URL = "https://raw.githubusercontent.com/elastic/ecs/main/generated/ecs/ecs_flat.yml";
```
Comment (eyalkoren) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:59]: @rjernst noted that the problem with fetching from main means that once an ECS change breaks this test, all PRs will fail until we get the dynamic templates (or the test) fixed. @mark-vieira raised a similar [concern](https://github.com/elastic/elasticsearch/issues/96713#issuecomment-1603760192).
I see why relying on main is problematic, but I am not sure what the alternative is. 

If we fetch the `ecs_flat.yml` file from a version branch, for example, it means that we can only capture ECS mismatches after it was already released, which implies that we will ship at least one version with dynamic templates mismatching the ECS of the same version (could be more if we rely on manually updating the used version branch and we fail to do that frequently enough).

I think that a state where `ecs-dynamic-mappings.json` doesn't fully cover ECS should be viewed as a bug. Relying on main provides a good way to ensure that we always release both in sync.

#96713 originally proposed that these tests will run **periodically** but I got advices to add them as yet another test in the suite. Maybe we need to reconsider periodic testing of this?

Any proposals or feedback on that are very welcome.

**Comment by ruflin** [comment]
> I think that's fine. While on the one hand, this creates a bit more indexing overhead than strictly required, it brings a nice consistency via the naming convention *.name so that users know they can always do a full text search on fields ending with *.name.

I'm not a fan of the ECS multi fields but I agree we should be consistent. Do we have an understand on how much the overhead on storage is? I guess hard to tell? Assuming a user would want to disable this, I assume they could overwrite it in `@custom` and only have the keyword?

**Comment by eyalkoren** [comment]
> Do we have an understand on how much the overhead on storage is? I guess hard to tell? 

I can't say anything clever about the actual overhead, only that since the default mapping for strings in Elasticsearch is multi-field, then I assume it is at least acceptable. We are only extending ECS a bit here 🙂 

> Assuming a user would want to disable this, I assume they could overwrite it in @custom and only have the keyword?

Exactly! And since we added `logs@custom` [before](https://github.com/elastic/elasticsearch/blob/62bebfd9d6b8dc7f7534ad81c9c7abb0391676be/x-pack/plugin/core/template-resources/src/main/resources/logs-template.json#L8) the ECS dynamic templates, any path or pattern coming from it will take precedence.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 12]
```diff
@@ -0,0 +1,416 @@
...
+        while (iterator.hasNext()) {
+            Map.Entry<String, Map<String, Object>> entry = iterator.next();
+            Map<String, Object> definitions = entry.getValue();
+            String type = (String) definitions.get("type");
+            if (OMIT_FIELD_TYPES.contains(type)) {
+                iterator.remove();
+            } else if ("bool".equals(type)) {
+                // for some reason, 'container.security_context.privileged' has a type "bool" in ECS definitions so we are standardizing
+                definitions.put("type", "boolean");
+            }
```
Comment (eyalkoren) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:147]: NOTE: this is here in order to handle a single field that was [added recently](https://github.com/elastic/ecs/pull/2219/files#diff-d11ef5cbccc15e12cd888cf21575f47d4293a14f81b9fdf03f631e9cd171d391R125), probably by mistake and should be removed after this is fixed.

Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:147]: Waiting for https://github.com/elastic/ecs/pull/2246 to be merged before I can remove this workaround.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java [hunk 13]
```diff
@@ -0,0 +1,416 @@
...
+            case "constant_keyword" -> {
+                return "test";
+            }
+            case "date" -> {
+                return DateFormatter.forPattern("strict_date_optional_time").formatMillis(System.currentTimeMillis());
+            }
+            case "ip" -> {
+                return NetworkAddress.format(randomIp(true));
+            }
+            case "boolean", "bool" -> {
```
Comment (eyalkoren) [inline x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:281]: TODO: remove `bool` once https://github.com/elastic/ecs/pull/2246 is merged

**Comment by eyalkoren** [comment]
@rjernst @mark-vieira would you be able to review or assign someone to review this PR?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 6 above)
Comment (mark-vieira) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: The better way is probably to declare a custom ivy repo in the build script and have Gradle download it so that' it is cached rather than downloading on every test execution.

Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: Thanks for the proposal! 
Since it is a single file that we download, is adding a dependency on the full repo indeed preferable? What I meant to ask is whether relying on TLS for this single file download good enough.
I am not familiar enough with Ivy- does it require specifying a version of the target repo? If so- this won't address what we need, which is to see ECS changes as soon as they are made. 

If you still think we should replace this, please provide an example that I can use as reference.

Comment (mark-vieira) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: You can more or less hard-code the URL in the repo definition. Here's an example we use for [downloading github releases](https://github.com/elastic/elasticsearch/blob/cc2a711b2de2800a34bc34bcc89a4b101485ab37/distribution/docker/build.gradle#L31), but you can adapt it to just download a raw file easily. The placeholders here are for maven artifact ids that look like `[org]:[module]:[revision]`.

Comment (felixbarny) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: I'm not sure if that would translate well to this case, though, as we're downloading a file from main, not from a particular version. Therefore, caching would be difficult, too, unless GitHub supports conditional GETs. But I guess what we could do is to simply download the file in via gradle instead of within the unit test. Something similar to `file("${project.buildDir}/ecs-dynamic-mappings.json") << "https://raw.githubusercontent.com/elastic/ecs/main/generated/ecs/ecs_flat.yml".toUrl().text`.

However, that doesn't have many benefits over just downloading the file directly from the unit test itself, except from not having to apply the `@SuppressForbidden` annotation.

Comment (mark-vieira) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: We can follow up here. You can set a cache invalidation strategy in the build so it'll redownload but we can attack this at a later time.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 11 above)
Comment (mark-vieira) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:59]: We should have any changes to ECS run these tests so we can avoid this scenario as much as possible. Testing this unilaterally means that any breakages or disruptions are on the Elasticsearch side and that's not ideal. In theory, if every change on either end runs these tests, this scenario should never happen.

Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:59]: Can you assist with setting this up? 
Alternatively, it may be much simpler to run this test daily/weekly. Should be good enough in order to catch inconsistencies soon enough after they are made to ECS main without affecting any other CI run in Elasticsearch.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 6 above)
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: So for the time being, are we good with the current approach?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 11 above)
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:59]: @mark-vieira how should we proceed with this? Would scheduled daily/weekly builds work?

Comment (mark-vieira) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:59]: Where does CI for ECS live currently?

Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:59]: I am not familiar with ECS CI, maybe @ebeahan can assist with that.
This is open for quite some time, what would you say is the best way forward?

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 7 above)
Comment (P1llus) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java]: @eyalkoren No real reason, it was simply that the initial script I made was not meant to cover all usecases, and flattened support was not really in the scope at that point.
It should indeed be tested though.

**Review by P1llus — APPROVED** [review]
I think the current review comments covers anything I would have added already. I see there was the discussion around multi-fields for .name, which was indeed something annoying for me when testing this out earlier, I did create an issue a long time ago in the ECS repo, but nothing really came of it.
I don't think the concept of multi-fields itself adds overhead, but text fields itself adds alot of overhead for sure, so if we had to choose, I rather not have them be multi-field but that decision is not up to me :) 
Anything else seems LGTM.

File: x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java (hunk 6 above)
Comment (eyalkoren) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: @mark-vieira can I mark this one as resolved? Are you OK with this simple HTTPS file download from GitHub?

Comment (mark-vieira) [reply x-pack/plugin/stack/src/javaRestTest/java/org/elasticsearch/xpack/stack/EcsDynamicTemplatesIT.java:107]: Yes, that's fine.

**Comment by breskeby** [comment]
I've added a daily ci job with notifications to slack (#es-delivery) and email (logs-plus@elastic.co)
