### PR TITLE
Flush old indices on primary promotion and relocation

### LINKED ISSUE #27536: Translog Operations with no sequence numbers fail recoveries after a rolling upgrading to 6.0
During a rolling upgrade shards on 6.0 nodes should be able to work with operations with no sequence numbers when the primary is still on a 5.6 node. After the primary is on a 6.0 node, it will start generating sequence numbers for all shard copies. To simplify the number of edge cases we have to deal with we have designed the code to only make the transition in one direction - i.e., once a shard moves to the sequence numbers universe, it will never go back to operated in a non sequence numbers universe. We also added protections in place to verify it doesn't happen.

Sadly, a rolling upgrade can lead to a situation that triggers those protections and fail the recoveries. Here is a typical exception line:

> Recovery failed from {bos1-es3}{JR9qqMjEQF6c22eGZqIAcw}{izoNnZpWTsyt5_xxymVDbg}{192.168.8.152}{192.168.8.152:9300}{ml.max_open_jobs=10, ml.enabled=true} into {bos1-es1}{tBZdi1W_TRa16getb8eNlA}{picaUSZyS7K34rTVpJvu1Q}{192.168.8.150}{192.168.8.150:9300}{ml.max_open_jobs=10, ml.enabled=true}]; nested: RemoteTransportException[[bos1-es3][192.168.8.152:9300][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[2] phase2 failed]; nested: RemoteTransportException[[bos1-es1][192.168.8.150:9300][internal:index/shard/recovery/translog_ops]]; nested: TranslogException[Failed to write operation [Index{id='AV_HS9TBPU9Vhf7shs_U', type='px-web-server', seqNo=-2, primaryTerm=0}]]; nested: IllegalArgumentException[sequence number must be assigned];

This can happen in the following scenario:
1) A replica is on a 6.0 node while the primary is on 5.6 while indexing is going on.
2) The replica inserts operations with no seq# to it's translog
3) The primary goes down (planned or not) and the replica becomes a new primary.
4)  The primary comes back (or another shard) and starts recovery.  While recovery is ongoing, indexing operations come in.
5)  The recovering replica opens up its engine and processes the new indexing operations, switching to seq# mode.
6) The old operations from the translogs are replayed and since they have no seq #s in them the assumptions are violated and the recovery failed. 

This problem is made worse by the fact that we now ship all the translogs to create a replica that adheres to the translog retention policy.

To work around it, people can reduce their translog retention policy to 0 (`index.translog.retention.size`) and then flush the primary shard. This should clean up the old ops from the translog. After that (and setting `index.translog.retention.size` back to null) you can run a reroute command with retry_failed flag : `POST /_cluster/reroute?retry_failed=true`. 

I'm still evaluating possible solutions. Based on the complexity we can decide which version the solution should go to. It's also an open question why our tests didn't catch this.

### PR DESCRIPTION
**Pull request by bleskes**
During a recovery the target shard may process both new indexing operations and old ones concurrently. When the primary is on a 6.0 node, the new indexing operations are guaranteed to have sequence numbers but we don't have that guarantee for the old operations as they may come from a period when the primary was on a pre 6.0 node. Have this mixture of old and new is something we do not support and it triggers exceptions.

This PR adds a flush on primary promotion and primary relocations to make sure that any recoveries from a primary on a 6.0 will be guaranteed to only need operations with sequence numbers. A recovery from store already flushes when we start the engine if there were any ops in the translog.

With this extra flushes in place we can now actively filter out operations that have no sequence numbers during recovery. Since filtering out operations is risky, I have opted to harden the logic in the recovery source handler to verify that all operations in the required sequence number range (from the local checkpoint in the commit onwards) are not missed. This comes at an extra complexity for this PR but I think it's worth it.

Finally I added two tests that reproduce the problems.

Closes #27536 

PS. I still need to add unit tests but since there's some time pressure on this one I think we can start reviewing.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 1]
```diff
@@ -511,17 +525,25 @@ public void finalizeRecovery(final long targetLocalCheckpoint) {
...
+            "requiredSeqNoRangeStart " + requiredSeqNoRangeStart + " is larger than endingSeqNo" + endingSeqNo;
+        assert startingSeqNo <= requiredSeqNoRangeStart :
+            "startingSeqNo " + startingSeqNo + " is larger than requiredSeqNoRangeStart " + requiredSeqNoRangeStart;
         int ops = 0;
         long size = 0;
         int skippedOps = 0;
         int totalSentOps = 0;
         final AtomicLong targetLocalCheckpoint = new AtomicLong(SequenceNumbers.UNASSIGNED_SEQ_NO);
         final List<Translog.Operation> operations = new ArrayList<>();
+        final LocalCheckpointTracker requiredOpsTracker = new LocalCheckpointTracker(endingSeqNo, requiredSeqNoRangeStart - 1);
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: If `endingSeqNo` is exclusive, then this should probably be `endingSeqNo - 1`. I know that it does not really matter as we only use the `markSeqNoAsCompleted` method, we might as well initialize this to 
`new LocalCheckpointTracker(requiredSeqNoRangeStart - 1, requiredSeqNoRangeStart - 1)`, but yeah, let's use inclusive bounds for `endingSeqNo` ;-)

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 2]
```diff
@@ -567,6 +587,12 @@ protected SendSnapshotResult sendSnapshot(final long startingSeqNo, final Transl
             cancellableThreads.executeIO(sendBatch);
         }
 
+        if (requiredOpsTracker.getCheckpoint() < endingSeqNo - 1) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: again having to use -1 here, easier to have endingSeqNo be inclusive.

File: qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/10_basic.yml [hunk 3]
```diff
@@ -7,6 +7,7 @@
         # wait for long enough that we give delayed unassigned shards to stop being delayed
         timeout: 70s
         level: shards
+        index: test_index, index_with_replicas, multi_type_index
```
Comment (ywelsch) [inline qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/10_basic.yml]: why do we need to wait here? Why not directly in the corresponding tests? This makes for example the RecoveryIT test dependent on a specific yml file, which is ugly IMO.

**Review by ywelsch — CHANGES_REQUESTED** [review]
Overall change LGTM, I've made some suggestions around code structure though.

File: qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/10_basic.yml (hunk 3 above)
Comment (ywelsch) [reply qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/10_basic.yml]: I misread, ignore this comment.

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 4]
```diff
@@ -148,23 +148,28 @@ public RecoveryResponse recoverToTarget() throws IOException {
...
-                // on the target
-                startingSeqNo = SequenceNumbers.UNASSIGNED_SEQ_NO;
-
+                // we set this to 0 to create a translog roughly according to the retention policy
+                // on the target. Note that it will still filter out legacy operations with no sequence numbers
+                startingSeqNo = 0;
+                // but we must have everything above the local checkpoint in the commit
+                requiredSeqNoRangeStart =
+                    Long.parseLong(phase1Snapshot.getIndexCommit().getUserData().get(SequenceNumbers.LOCAL_CHECKPOINT_KEY)) + 1;
+                assert requiredSeqNoRangeStart >= 0 :
```
[the remark this answers is not in the document]
Comment (bleskes) [reply core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: sure

**Comment by bleskes** [comment]
thx @ywelsch . I addressed your feedback. can you take another look?

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 5]
```diff
@@ -487,15 +493,26 @@ public void updateShardState(final ShardRouting newRouting,
...
+                                 * replaying the translog and marking any operations there are completed.
                                  */
-                                getEngine().rollTranslogGeneration();
-                                getEngine().restoreLocalCheckpointFromTranslog();
-                                getEngine().fillSeqNoGaps(newPrimaryTerm);
-                                getEngine().seqNoService().updateLocalCheckpointForShard(currentRouting.allocationId().getId(),
+                                final Engine engine = getEngine();
+                                engine.restoreLocalCheckpointFromTranslog();
+                                if (indexSettings.getIndexVersionCreated().onOrBefore(Version.V_6_0_0_alpha1)) {
+                                    // an index that was created before sequence numbers were introduce may contain operations in its
```
Comment (dnhatn) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: nit: introduce -> introduce*d*

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 6]
```diff
@@ -434,22 +442,25 @@ void prepareTargetForTranslog(final int totalTranslogOps) throws IOException {
      *
      * @param startingSeqNo the sequence number to start recovery from, or {@link SequenceNumbers#UNASSIGNED_SEQ_NO} if all
      *                      ops should be sent
+     * @param requiredSeqNoRangeStart the lower sequence number of the required range (ending with endingSeqNo)
```
Comment (dnhatn) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: nit: we may need to reformat this javadocs

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 7]
```diff
@@ -511,17 +522,25 @@ public void finalizeRecovery(final long targetLocalCheckpoint) {
      * Operations are bulked into a single request depending on an operation count limit or size-in-bytes limit.
      *
      * @param startingSeqNo the sequence number for which only operations with a sequence number greater than this will be sent
-     * @param snapshot      the translog snapshot to replay operations from
-     * @return the local checkpoint on the target and the total number of operations sent
+     * @param requiredSeqNoRangeStart the lower sequence number of the required range
```
Comment (dnhatn) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: nit: we may need to reformat this javadocs

**Comment by dnhatn** [comment]
LGTM; However, I mainly learnt how you fixed the problem and comments from Yannick.

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 8]
```diff
@@ -567,6 +584,12 @@ protected SendSnapshotResult sendSnapshot(final long startingSeqNo, final Transl
             cancellableThreads.executeIO(sendBatch);
         }
 
+        if (requiredOpsTracker.getCheckpoint() < endingSeqNo) {
+            throw new IllegalStateException("translog replay failed to covered required sequence numbers" +
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: covered -> cover

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java [hunk 9]
```diff
@@ -181,29 +186,74 @@ public void testSendSnapshotSendsOps() throws IOException {
             operations.add(new Translog.Index(index, new Engine.IndexResult(1, i - initialNumberOfDocs, true)));
         }
         operations.add(null);
-        final long startingSeqNo = randomBoolean() ? SequenceNumbers.UNASSIGNED_SEQ_NO : randomIntBetween(0, 16);
-        RecoverySourceHandler.SendSnapshotResult result = handler.sendSnapshot(startingSeqNo, new Translog.Snapshot() {
-            @Override
-            public void close() {
+        final long startingSeqNo = randomIntBetween(0, numberOfDocsWithValidSequenceNumbers - 1);
+        final long requiredStartingSeqNo = randomIntBetween((int) startingSeqNo, numberOfDocsWithValidSequenceNumbers - 1);
+        final long endingSeqNo = randomIntBetween((int) requiredStartingSeqNo, numberOfDocsWithValidSequenceNumbers - 1);
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: It can start from `requiredStartingSeqNo - 1`?

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java [hunk 10]
```diff
@@ -181,29 +186,74 @@ public void testSendSnapshotSendsOps() throws IOException {
...
+        // todo add proper tests
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: is this proper enough now?

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java [hunk 11]
```diff
@@ -181,29 +186,74 @@ public void testSendSnapshotSendsOps() throws IOException {
...
+            assertThat(shippedOps.size(), equalTo(expectedOps));
+            for (int i = 0; i < shippedOps.size(); i++) {
+                assertThat(shippedOps.get(i), equalTo(operations.get(i + (int) startingSeqNo + initialNumberOfDocs)));
             }
-        });
-        if (startingSeqNo == SequenceNumbers.UNASSIGNED_SEQ_NO) {
-            assertThat(result.totalOperations, equalTo(initialNumberOfDocs + numberOfDocsWithValidSequenceNumbers));
         } else {
-            assertThat(result.totalOperations, equalTo(Math.toIntExact(numberOfDocsWithValidSequenceNumbers - startingSeqNo)));
+            verify(recoveryTarget, never()).indexTranslogOperations(null, 0);
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: I think this does not verify the right thing. You check that it's never called with the arguments null and 0, whereas you want to check that it's never called with any arguments.

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java [hunk 12]
```diff
@@ -181,29 +186,74 @@ public void testSendSnapshotSendsOps() throws IOException {
...
+                            return operations.size() - 1 - opsToSkip.size();
+                        }
+
+                        @Override
+                        public Translog.Operation next() throws IOException {
+                            Translog.Operation op;
+                            do {
+                                op = operations.get(counter++);
+                            }
+                            while (op != null && opsToSkip.contains(op));
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: formatting nit: can you move the `while` behind the closing bracket `}`, not in a new line?

**Review by ywelsch — APPROVED** [review]
LGTM, left some minor nits

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java (hunk 9 above)
Comment (bleskes) [reply core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: yes.

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java (hunk 10 above)
Comment (bleskes) [reply core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: :)

File: core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java (hunk 11 above)
Comment (bleskes) [reply core/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java]: good catch. Thanks.

**Comment by bleskes** [comment]
Thanks @ywelsch @dnhatn . I'm chasing some failures on my CI. Will push once I looked at those and CI here finishes as well.

**Comment by bleskes** [comment]
@ywelsch I run into another edge case. Can you please take another look at the last few commits?

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java [hunk 13]
```diff
@@ -583,6 +587,28 @@ public void testSingleDoc() throws IOException {
         assertThat(toStr(client().performRequest("GET", docLocation)), containsString(doc));
     }
 
+    /**
+     * Tests that a single empty shard index is correctly recovered. Empty shards are often an edge case.
+     */
+    public void testEmptyShard() throws IOException {
+        final String index = "test_empty_hard";
```
Comment (ywelsch) [inline qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: hard -> shard

**Review by ywelsch — APPROVED** [review]

**Review by ywelsch — APPROVED** [review]
LGTM. Thanks @bleskes

**Comment by bleskes** [comment]
Thanks @ywelsch & @dnhatn
