### PR TITLE
Auto-generated TLS files under fixed config path

### LINKED ISSUE #81057: Adjust naming for TLS autoconfiguration directory and artifacts
We currently use a directory name like `tls_auto_config_<timestamp>` for the directory where we store the auto-generated TLS key/certificate material. This was intentional and has certain benefits but we decided that it's complicating the getting started experience and our documentation. Moreover, we are using longer descriptive names for keystores (`http_keystore_local_node.p12` and `http_keystore_local_node.p12` ) and we decided that it might be less confusing for users if we use shorter names such as `http.p12` and `transport.p12`. 

Our generated material should look like: 

```
config/
├── tls_auto_config
│   ├── http_ca.crt
│   ├── http.p12
│   └── transport.p12
```

### PR DESCRIPTION
**Pull request by albertzaharovits**
We (mostly I) were initially advocating for the auto-generated files to use unique names (the name containing a timestamp particle), in order to avoid that subsequent invocations of the config step conflict with itself.
Moreover, I was wishing that these files will not have to be handled directly by admins (that the enrollment process was to be used).

However, experience proved us otherwise, admins have to manipulate these files, and unique configuration names are hard to deal with in scripts and docs, so this PR is all about using a fixed name for all the generated files.

_Labeling as a bug fix because the feedback is that it very negatively impacts usabilty._

Closes https://github.com/elastic/elasticsearch/issues/81057

### CODE REVIEW

**Comment by jkakavas** [comment]
I’ll do a proper pass when this is ready but I wanted to raise that we have decided to change the name of the files to be simply transport.p12 and http.p12 and I know Fabio is keen on having the name of the dir be simply ‘certs’ . Does it make sense to cover these in this PR too ?

**Comment by albertzaharovits** [comment]
> I’ll do a proper pass when this is ready but I wanted to raise that we have decided to change the name of the files to be simply transport.p12 and http.p12 in the previous project meeting and I know Fabio is keen on having the name of the dir be simply ‘certs’ . Does it make sense to cover these in this PR too ?

Okay, will make those renamings verbatim, I forgot about those.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 1]
```diff
@@ -483,14 +511,14 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
                 transportKeystore.load(null);
                 // the PKCS12 keystore and the contained private key use the same password
                 transportKeystore.setKeyEntry(
-                    TRANSPORT_AUTOGENERATED_KEY_ALIAS,
+                    "transport",
```
Comment (albertzaharovits) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:514]: Hopefully the change in keystore entry name is not botering anyone.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 2]
```diff
@@ -549,6 +573,76 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
             }
         }
 
+        try {
+            // all certs and keys have been generated in the temp certs dir, therefore:
+            // 1. backup (move) any previously existing tls certs dir (this backup is NOT removed when auto-conf finishes)
+            if (Files.exists(env.configFile().resolve(TLS_GENERATED_CERTS_DIR_NAME))) {
```
Comment (albertzaharovits) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:579]: If it happens that there's already a `certs` dir present, we back it up and never remove it.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 3]
```diff
@@ -549,6 +573,76 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
...
+                t.addSuppressed(ex);
+            }
+            try {
+                deleteDirectory(tempGeneratedTlsCertsDir);
+            } catch (Exception ex) {
+                t.addSuppressed(ex);
+            }
+            throw t;
+        }
+
```
Comment (albertzaharovits) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:645]: At this point the keystore and the certs dir are all set. What's left is to update the yml file.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 2 above)
Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:579]: I don't have anything against doing this for sure, but the only way to get here is if we :

- have a certs directory 
- no configuration in elasticsearch.yml
- no entries in the keystore

so  I don't expect this happening that much , right ?

**Review by jkakavas — APPROVED** [review]
LGTM

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 2 above)
Comment (albertzaharovits) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:579]: Right, it is a corner case that the admin had such a config directory while the the yml and keystore files are clean. Not a reason strong enough to prevent auto-configuration.
