### PR TITLE
Use the system index descriptor in the snapshot blob cache cleanup task

### LINKED ISSUE #120518: Clean up of the `.snapshot-blob-cache*` index not working on an upgraded 8.x cluster
### Elasticsearch Version

8.x

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

If a 7.x cluster has the `.snapshot-blob-cache*` system index (used for caching header/footer values of Lucene files when mounting searchable snapshot indices), and it is upgrade to 8.x, the clean up of the entries of this index doesn't seem to work anymore. These clean ups are done automatically periodically e.g. when the relevant searchable snapshot indices are removed (and after a configurable period). Deletion also doesn't seem to work if one would create new searchable snapshot indices (which write to this system index) and remove them. In other words, after upgrade the `.snapshot-blob-cache*` system index seems to only grow.

As a work-around, you can remove the `.snapshot-blob-cache*` system index (which requires `[delete_index,manage,all]` privileges). Note that this work-around essentially wipes the cache (which is what this system index is).

### Steps to Reproduce

1. Start a 7.x node.
2. create an index, take a snapshot and remove the index.
3. Mount the index as a partially mounted searchable snapshot.
4. Upgrade to 8.x.
5. Remove the searchable snapshot index.
6. The `.snapshot-blob-cache*` index is not cleaned up after the configured retention period and periodic clean up interval.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by pxsalehi**
Clean up of the `.snapshot-blob-cache*` system index is done only on the node that hosts the primary of the shard 0 of that index. When the index is migrated as part of an upgrade test e.g. v7 -> v8, the index is reindexed to a new index `.snapshot-blob-cache-reindexed-for-9`. The code scheduling this clean up task is not able to locate the shard and would never trigger a clean up after the upgrade. This change uses the system index descriptor to find the matching shard and would work for future versions too.

Closes https://github.com/elastic/elasticsearch/issues/120518

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java [hunk 1]
```diff
@@ -311,6 +315,46 @@ public void testPeriodicMaintenance() throws Exception {
...
+            refreshSystemIndex(true);
+            assertHitCount(systemClient().prepareSearch(SNAPSHOT_BLOB_CACHE_INDEX).setSize(0), 0L);
+        });
+    }
+
+    /**
+     *  Mimics migration of the {@link SearchableSnapshots#SNAPSHOT_BLOB_CACHE_INDEX} as done in
+     *  {@link org.elasticsearch.upgrades.SystemIndexMigrator}, where the index is re-indexed, and replaced by an alias.
+     */
+    private void migrateTheSystemIndex() {
```
Comment (pxsalehi) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java:344]: I did have a quick look at `SystemIndexMigrator` hoping I could trigger this migration step by creating/running such a migrator. But that doesn't seem straight-forward and it would still be mimicking a proper upgrade test which is what is missing here. Considering the lack of automated upgrade tests that include the migration steps is a bigger issue and not addressed currently, I kept the test here short just trying to reindex/alias/remove, which is what the migrator is doing.

I have also manually verified this by creating/mounting a searchable snapshot index in 7.x, and upgrading to 8.x (with migration) and then 9.x and removing the searchable snapshot index in 9.x which cleans up the migrated snapshot blob cache index.

Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java:344]: So we have no actual upgrade tests that run system index migrations? That indeed sounds problematic and something we should ensure happens (but fine outside this PR, for another team too I think).

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/BlobStoreCacheMaintenanceService.java [hunk 2]
```diff
@@ -242,16 +242,20 @@ private synchronized void stopPeriodicTask() {
...
 
-    @Nullable
-    private ShardRouting systemIndexPrimaryShard(final ClusterState state) {
-        final IndexMetadata indexMetadata = state.metadata().index(systemIndexName);
-        if (indexMetadata != null) {
-            final IndexRoutingTable indexRoutingTable = state.routingTable().index(indexMetadata.getIndex());
-            if (indexRoutingTable != null) {
-                return indexRoutingTable.shard(0).primaryShard();
+    private boolean systemIndexPrimaryShardActiveAndAssignedToLocalNode(final ClusterState state) {
+        for (IndexMetadata indexMetadata : state.metadata()) {
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/BlobStoreCacheMaintenanceService.java:246]: Can we use `getMatchingIndices` instead and then assert that it has <= 1 results? I think that simplifies the code here too.

**Review by henningandersen — APPROVED** [review]
LGTM.

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java (hunk 1 above)
Comment (pxsalehi) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java:344]: My understanding is that we don't have that. which is why we resorted to manual testing in the first place. I can follow up and ask around, and create a follow up issue or PR if it turns out to be possible.

Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java:344]: In #121517 Christoph reused the upgrade tests we made for N-2 support in order to test the upgrade of the `async-search` system index.

Comment (pxsalehi) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheMaintenanceIntegTests.java:344]: Thanks. I'll look into that. back then I asked core/infra about v7->v8->v9 and they mentioned there is currently no option. But this could be partially useful.
