### PR TITLE
Fix to tdigest implicit eval

### LINKED ISSUE #140670: Histogram to TDigest cast doesn't work in TS mode
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

Converting a histogram to tdigest in a stats command fails with a validation exception, while doing the same conversion as a separate eval works correctly.

### Steps to Reproduce

```
PUT /test
{
	"settings": {
		"mode": "time_series",
		"routing_path": "host"
	},
	
	"mappings": {
		"properties": {
			"@timestamp" : {
				"type": "date"
			},
			"host": {
				"type": "keyword",
				"time_series_dimension": true
			},
			"hist": {
				"type": "histogram"
			},
			"hist_metric": {
				"type": "histogram",
				"time_series_metric": "histogram"
			}
		}
	}
}

POST /test/_doc
{
	"@timestamp": "2026-01-14T00:01:02",
	"host": "foo",
	"hist":{"values": [1, 2], "counts":[13, 17]},
	"hist_metric":{"values": [1, 2], "counts":[13, 17]}
}


// This fails showing the error
POST /_query?format=txt
{
	"query": "TS test | STATS AVG(to_tdigest(hist_metric))"
}

// This query, which should be equivalent to the above query, works
POST /_query?format=txt
{
	"query": "TS test | EVAL td = to_tdigest(hist_metric) | STATS AVG(td)"
}
```

The error message from the failure:
```{
  "error": {
    "root_cause": [
      {
        "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:32: argument of [implicit time-series aggregation function (HistogramMergeOverTime) for hist_metric] must be [exponential_histogram or tdigest], found value [hist_metric] type [histogram]; to aggregate non-numeric fields, use the FROM command instead of the TS command"
      }
    ],
    "type": "verification_exception",
    "reason": "Found 1 problem\nline 1:32: argument of [implicit time-series aggregation function (HistogramMergeOverTime) for hist_metric] must be [exponential_histogram or tdigest], found value [hist_metric] type [histogram]; to aggregate non-numeric fields, use the FROM command instead of the TS command"
  },
  "status": 400
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by not-napoleon**
Fixes https://github.com/elastic/elasticsearch/issues/140670

This addresses the linked bug, but it's not at all clear to me that the solution is correct.  I'm pushing this up as a draft to discuss.  If we agree that this is the right way to fix it, I can write some more tests for it and get the PR merged.

Also, it turns out we didn't have any TS mode CSV tests for histogram data.  I've added a new CSV data source and one test for that case.  We need to replicate all the other tests in TS mode too, I think.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java [hunk 1]
```diff
@@ -69,6 +70,12 @@ private static Expression addDefaultInnerAggs(Expression expression, Expression
                 case AggregateFunction af -> af.withField(addDefaultInnerAggs(af.field(), timestamp, changed));
                 // avoid modifying filter conditions, just the delegate
                 case FilteredExpression filtered -> filtered.withDelegate(addDefaultInnerAggs(filtered.delegate(), timestamp, changed));
+
+                case AbstractConvertFunction convertFunction -> {
```
Comment (JonasKunz) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: Is `AbstractConvertFunction` or `ConvertFunction` the right type here?
We should probably use the same identification mechanism which is also used to identify the "conversion functions" for union types?

However, I think we should make sure that the inner expression is in fact (a) a field or (b) another conversion function.

E.g. we don't want `TO_LONG(foo + 1.5)` to be translated to `last_over_time(TO_LONG(foo + 1.5))` in my opinion.

Comment (felixbarny) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: Something like this might work:

```java
case ConvertFunction convert when convert.allMatch(e -> e instanceof ConvertFunction || e instanceof TypedAttribute)
```

(I know `allMatch` doesn't exist, yet. But it should be a straightforward and uncontroversial addition.)

**Review by felixbarny — COMMENTED** [review]
Please also test convert functions on non-histogram fields and also nested convert functions.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java (hunk 1 above)
Comment (not-napoleon) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: We could check for exactly `ToTdigest` there; since there are few scalar operations available on histograms, that should be safer.

Comment (JonasKunz) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: But I think we want it to actually work with all conversion functions, so that e.g. union types remain useable.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/histogram.csv-spec [hunk 2]
```diff
@@ -60,6 +60,48 @@ min:double | max:double | p90:double | sum:double  | avg:double
 
 // -----------------------------------------
 
+Core supported t-digest aggs on histogram field, without grouping (TS mode)
```
Comment (not-napoleon) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/histogram.csv-spec:63]: We should add more TS mode tests here, but this is kind of the minimum to fix this specific bug.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java [hunk 3]
```diff
@@ -69,6 +72,13 @@ private static Expression addDefaultInnerAggs(Expression expression, Expression
                 case AggregateFunction af -> af.withField(addDefaultInnerAggs(af.field(), timestamp, changed));
                 // avoid modifying filter conditions, just the delegate
                 case FilteredExpression filtered -> filtered.withDelegate(addDefaultInnerAggs(filtered.delegate(), timestamp, changed));
+                case AbstractConvertFunction convert when convert.allMatch(
```
Comment (not-napoleon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: Note - we have to use `AbstractConvertFunction` here, not the `ConvertFunction` interface, so we have a node instance to call `allMatch` on.  This will be a problem for union types, since `ToIp` does not extend from `AbstractConvertFunction`.  I propose we open an issue for that and solve it separately, as it didn't work before this change either.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/core/tree/Node.java [hunk 4]
```diff
@@ -167,6 +167,17 @@ public boolean anyMatch(Predicate<? super T> predicate) {
...
 
+    /**
+     * Traverse the plan tree from the current node to the leaves, checking the given
+     * predicate.  This function will short circuit and return early if it is able to.
+     *
+     * @param predicate condition to check against all nodes
+     * @return true iff the given predicate is true for all nodes
+     */
+    public boolean allMatch(Predicate<? super T> predicate) {
+        return anyMatch(Predicate.not(predicate)) == false;
```
Comment (not-napoleon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/core/tree/Node.java:179]: @alex-spies I discussed this briefly with you, but tagging you here in case you want to see the implementation.

**Comment by not-napoleon** [comment]
Okay, BWC tests are failing trying to load the histogram time series data, because the histogram metric type did not exist prior to 9.3.  This probably needs some way to gate loading that data set for older versions; `CsvTestsDataLoader#availableDataSetsForEs` does something similar, might be able to use that but I need to look a little deeper at it.  Also that method is a mess, and needs to be refactored badly.  I'll try to kludge together something tomorrow to get BWC happy here, and we should plan to clean up this mess soon.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java (hunk 3 above)
Comment (felixbarny) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: You can still use `ConvertFunction` and then call `expr.allMatch(...`

**Review by felixbarny — APPROVED** [review]

**Review by JonasKunz — APPROVED** [review]
LGTM after applying Felix' suggestion.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java (hunk 3 above)
Comment (not-napoleon) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: oh, neat! Thanks. I haven't done much with the pattern matching switch expressions, I appreciate the tips.
