### PR TITLE
ESQL: Preserve emit size in AdaptiveBlockHash

### LINKED ISSUE #147361: [CI] BlockHashRandomizedTests test {forcePackedHash=false groups=2 maxValuesPerPosition=3} failing
**Build Scans:**
- [elasticsearch-pull-request #140035 / part-3](https://gradle-enterprise.elastic.co/s/5hrvpebnpkjmo)
- [elasticsearch-pull-request #140035 / part-3 retry #1](https://gradle-enterprise.elastic.co/s/hqruujukqj5wc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.aggregation.blockhash.BlockHashRandomizedTests.test {forcePackedHash=false groups=2 maxValuesPerPosition=3 dups=0 allowedTypes=[Ordinals[dictionarySize=10], Basic[elementType=BOOLEAN], Basic[elementType=INT], Basic[elementType=LONG], Basic[elementType=DOUBLE], Basic[elementType=NULL], Basic[elementType=BYTES_REF]]}" -Dtests.seed=FDB32FD7C462EB41 -Dtests.locale=gsw-CH -Dtests.timezone=Asia/Dushanbe -Druntime.java=26
```

The `dups=2` variant fails with the same seed.

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.aggregation.blockhash.BlockHashRandomizedTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(),title:'Test',type:optionsListControl)))))

Reports of many failures of this test in the last day.

**Failure Message:**
```
java.lang.AssertionError:
Expected: a value less than or equal to <100>
     but: <275> was greater than <100>
	at BlockHashRandomizedTests.lambda$test$1(BlockHashRandomizedTests.java:196)
```

The `dups=2` variant produced `<303> was greater than <100>` at the same line.

**Issue Reasons:**
- [main] Both `dups=0` and `dups=2` variants fail in the same run under the `forcePackedHash=false groups=2 maxValuesPerPosition=3` parameter combination.
- Failure persisted across the `part-3 retry #1` smart-retry, ruling out an ambient flake in that build.
- The assertion at `BlockHashRandomizedTests.java:196` (`ordsAndKeys.ords().getTotalValueCount() <= emitBatchSize`, where `emitBatchSize=100`) is violated by a `PackedValuesBlockHash` chunk emitting 275–303 values. Leading suspect is the recent `PackedValuesBlockHash` chunking refactor in #144434 ("ESQL: Aggs build subsets of keys"), which touched this exact code path.
- Prior closed issue #137021 (Oct 2025) reported a near-identical failure on `BlockHashRandomizedTests` with matching `groups=2` + `Ordinals[dictionarySize=10]` shape.

### PR DESCRIPTION
**Pull request by nik9000**
I've also expanded the test so we're more likely to hit it. And made it a bit faster.

Closes #147361

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashRandomizedTests.java [hunk 1]
```diff
@@ -224,6 +234,45 @@ private void test(BlockFactory blockFactory) {
...
+     * Pick a position count that keeps {@link Oracle} from growing too large.
+     * {@link Oracle#add} builds the full cross-product of values across all
+     * groups per position — up to {@code maxValuesPerPosition^groups} combinations —
+     * and large element sizes (e.g. {@code BYTES_REF}) multiply the cost, so we
+     * scale down using {@link #elementSize(ElementType)}.
+     */
+    private int randomPositionsPerPage(boolean trackGroupIds, int pageCount, List<ElementType> elementTypes) {
+        long maxCombosPerPosition = (long) Math.pow(maxValuesPerPosition, groups);
+        long totalElementSize = elementTypes.stream().mapToLong(BlockHashRandomizedTests::elementSize).sum();
+        System.err.println("totalElementSize " + totalElementSize);
```
Comment (dnhatn) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashRandomizedTests.java]: leftover

**Review by dnhatn — APPROVED** [review]
Thanks Nik!

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashRandomizedTests.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashRandomizedTests.java]: boooooo.  println.
