### PR TITLE
Limit user to single concurrent auth per realm

### LINKED ISSUE #30355: Limit number of concurrent authentication requests when the cache expires
Many of our realms extend CachingUsernamePasswordRealm which maintains a local (per node) cache of users and credentials so that we do not need to do a lookup on the underlying datastore for every request.

This is particularly important when the datastore is external, e.g. an LDAP directory. If the cache was not there we would need to do an LDAP bind (and potentially also group/metadata lookups) for every REST request.

This cache has a per-entry expiry, where an entry is a "user". That means that when the cache entry for a user expires, all authentication requests for that user will lookup the original datasource until the cache is populated again (when the first authentication succeeds).

Additionally, various other factors can cause a cache entry to be evicted (e.g. we invalidate on incorrect password so that we can check for an updated password in the datastore, and there is an API to clear the cache by realm/user).

Consequently, for a single user on a single node, there is a period where we do not make requests to the datastore, and then a short period where we make potentially multiple requests.

e.g. If somone has a number of beats running on various source systems, and those beats connect directly to Elasticsearch using a single user defined in LDAP, then every 30 minutes or so, every one of those beats could trigger an LDAP bind causing cyclic spikes in load on the LDAP server.

This behaviour is problematic, but the solution is not obvious.

- We can limit the impact of this through connection pooling (and have done so), but this doesn't reduce the total number of requests to the LDAP directory, it just flattens & stretches the spikes as that there are less simultaneous requests, but no change in the total number of requests.

- We could implement a "cache loader" approach, where only 1 task can be attempting to load a cache entry for a given key. That is, if we find that the cache does not have an entry for a specific user, then we perform a lookup on the original datasource, and any other lookups for that same user will wait for the first lookup to complete.  
This sort of concurrency behaviour is difficult to do well and can easily be a source of subtle bugs, particularly as we need the "wait for cache to populate" to be asynchronous.

- An alternative that I have a prototype for, is to simply limit the number of concurrent authentication requests that a single realm can perform simulatenously (with a BlockingQueue to hold pending requests). This limit is global and does not care about the identity of the authenticating user. It sits before the cache, so the first _N_ requests will execute and populate the cache as needed, and then subsequent requests will be released from the queue and find the cache is ready and the relevant user entries are populated.  
This works quite well when a realm is authenticating a small number of distinct users, but those users perform multiple simultaneous requests to Elasticsearch. When there are multiple users involved, it can also help, but the result is very similar to using a connection pool.

### PR DESCRIPTION
**Pull request by jaymode**
This commit reworks the way our realms perform caching in order to
limit each principal to a single ongoing authentication per realm. In
other words, this means that multiple requests made by the same user
will not trigger more that one authentication attempt at a time if no
entry has been stored in the cache. If an entry is present in our
cache, there is no restriction on the number of concurrent
authentications performed for this user.

This change enables us to limit the load we place on an external system
like an LDAP server and also preserve resources such as CPU on
expensive operations such as BCrypt authentication.

Closes #30355

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java [hunk 1]
```diff
@@ -78,74 +83,90 @@ public final void authenticate(AuthenticationToken authToken, ActionListener<Aut
...
+    private void handleResult(ListenableFuture<Tuple<AuthenticationResult, UserWithHash>> future, boolean createdAndStartedFuture,
+                              UsernamePasswordToken token, Tuple<AuthenticationResult, UserWithHash> result,
+                              ActionListener<AuthenticationResult> listener) {
+        final AuthenticationResult authResult = result.v1();
+        if (authResult == null) {
+            // this was from a lookup; clear and redo
+            cache.invalidate(token.principal(), future);
+            authenticateWithCache(token, listener);
+        } else if (authResult.isAuthenticated()) {
+            if (createdAndStartedFuture) {
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java]: The use of `createdAndStartedFuture` here worries me.
We need to handle the two cases (directly authenticated vs loaded from cache) differently, but this variable is a couple of steps removed from that and I fear that something like a race condition somewhere in the cache could mean that this is `true`, but the user was not actually authenticated with the credentials from `token`.

Perhaps we could set an `AtomicReference` to `User` in the listener for `doAuthenticate` and check whether the `User` being pulled from the cache matches. Then were no longer testing "did we create the future" but "did we actually authenticate _this_ User object".

e.g.
```
 doAuthenticate(token, ActionListener.wrap(result -> {
                    if (result.isAuthenticated()) {
                        final User user = result.getUser();
                        authenticatedUser.set(user);
```
``` 
       final boolean wasAuthenticatedWithThisToken = tuple.v2() == authenticatedUser.get();
       handleResult(future, wasAuthenticatedWithThisToken, token, tuple, listener);
```

**Review by tvernum — COMMENTED** [review]
I like the approach, but I have a suggested change.

**Comment by jaymode** [comment]
@tvernum thanks for the suggestion. I implemented the suggestion slightly differently. Let me know what you think.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by albertzaharovits** [comment]
I have pushed e888467d0a7af4115789d08e and 935c6c740c3d1a4d150d9bcc819c54e to fix a minor test bug:
```
diff --git a/server/src/test/java/org/elasticsearch/common/cache/CacheTests.java b/server/src/test/java/org/elasticsearch/common/cache/CacheTests.java
index 3b183cce40b..a2e47e6c60f 100644
--- a/server/src/test/java/org/elasticsearch/common/cache/CacheTests.java
+++ b/server/src/test/java/org/elasticsearch/common/cache/CacheTests.java
@@ -471,7 +471,7 @@ public class CacheTests extends ESTestCase {
                     keys.add(key);
                 } else {
                     // invalidate with incorrect value
-                    cache.invalidate(key, Integer.toString(key * randomIntBetween(2, 10)));
+                    cache.invalidate(key, Integer.toString(key + randomIntBetween(2, 10)));
                 }
             }
         }
@@ -506,7 +506,7 @@ public class CacheTests extends ESTestCase {
                     invalidated.add(i);
                 } else {
                     // invalidate with incorrect value
-                    cache.invalidate(i, Integer.toString(i * randomIntBetween(2, 10)));
+                    cache.invalidate(i, Integer.toString(i + randomIntBetween(2, 10)));
                 }
             }
         }
```
if `i` is `0` the value is correct and invalidation is expected.
Sample error:
```
./gradlew :server:test -Dtests.seed=824E15A422DDC053 -Dtests.class=org.elasticsearch.common.cache.CacheTests -Dtests.method="testNotificationOnInvalidateWithValue { seed=[824E15A422DDC053:5A13A8665810B577]}" -Dtests.security.manager=true -Dtests.locale=es-CU -Dtests.timezone=Arctic/Longyearbyen
FAILURE 0.02s | CacheTests.testNotificationOnInvalidateWithValue { seed=[824E15A422DDC053:5A13A8665810B577]} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<[0, 5155, 4680, 2665, 3114, 4237, 5134, 1138, 2674, 179, 116, 4215, 5656, 154, 1338, 2236, 2941, 5885, 2974, 4414]> but was:<[5155, 4680, 2665, 3114, 4237, 5134, 1138, 2674, 179, 116, 4215, 5656, 154, 1338, 2236, 2941, 5885, 2974, 4414]>
   >    at __randomizedtesting.SeedInfo.seed([824E15A422DDC053:5A13A8665810B577]:0)
   >    at org.elasticsearch.common.cache.CacheTests.testNotificationOnInvalidateWithValue(CacheTests.java:513)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by jaymode** [comment]
thanks @albertzaharovits

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java [hunk 2]
```diff
@@ -78,74 +85,95 @@ public final void authenticate(AuthenticationToken authToken, ActionListener<Aut
...
-                if (result.isAuthenticated()) {
-                    final User user = result.getUser();
-                    logger.debug("cached user came from a lookup and could not be used for authentication. " +
-                            "realm [{}] authenticated user [{}] with roles [{}]", name(), token.principal(), user.roles());
+
+            future.addListener(ActionListener.wrap(tuple -> {
+                if (tuple != null) {
+                    final UserWithHash userWithHash = tuple.v2();
+                    final boolean performedAuthentication = createdAndStartedFuture.get() && userWithHash != null &&
+                        tuple.v2().user == authenticatedUser.get();
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java]: @jaymode I think `tuple.v2().user == authenticatedUser.get()` is redundant (or there's a deeper reasoning that eludes me). Can you please clarify why this check is necessary?

Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java]: @albertzaharovits

This was introduced in response to my feedback above

- https://github.com/elastic/elasticsearch/pull/30794#discussion_r190140798

Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java]: That link doesn't seem to work correctly.
It's the 3rd comment in my review above.

Comment (albertzaharovits) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java]: Thanks @tvernum . I understand, it's always better to test for the actual thing, if you can, instead of a surrogate. 
But as it makes you feel surer on the whole it makes me feel less of. The whole seems too gnarly: `handleResult` has both `createdAndStartedFuture` and `performedAuthentication` as params.
Then, I think we can do without `createdAndStartedFuture`.
I will open a nimble refactor non-issue on this.

Comment (albertzaharovits) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/CachingUsernamePasswordRealm.java]: @tvernum I am going to concede on this one, for now 😭 .
I could not find a satisfactory refactoring such that the current behavior is maintained over all branches. Specifically I was looking to minimize `authenticationResult.isAuthenticated()` checks, as well as to split the listener into two types, one for the thread going for the network call and the other for the stalled threads. In the end I got a huge branching monster no better that the present one.
😢
