### PR TITLE
Fail and close translog hard if writing to disk fails

### LINKED ISSUE #15333: Failure to recover shards after disk is full
Today, the disk got full and ElasticSearch is not able to go back again. Isn't there a built-in system that prevents such failures. I agree that we should be monitoring the hard space and not let this happen in first place, but some times things happen.

My setup is a single node at present. Using ES 2.1.0, which was supposed to have this fix.

I don't see a clear way to recover the node. A post at https://t37.net/how-to-fix-your-elasticsearch-cluster-stuck-in-initializing-shards-mode.html seemed to help, but still few indices got corrupted and I have no way to recovering them.

At the end, I ended up deleted the indices, but that's not the way it should be. Such things must be taken care of ultimately. But this is clearly a bug with ES 2.1.0

### PR DESCRIPTION
**Pull request by s1monw**
Today we are super lenient (how could I missed that for f**k sake) with failing
/ closing the translog writer when we hit an exception. It's actually worse, we allow
to further write to it and don't care what has been already written to disk and what hasn't.
We keep the buffer in memory and try to write it again on the next operation.

When we hit a disk-full expcetion due to for instance a big merge we are likely adding document to the
translog but fail to write them to disk. Once the merge failed and freed up it's diskspace (note this is
a small window when concurrently indexing and failing the shard due to out of space exceptions) we will
allow in-flight operations to add to the translog and then once we fail the shard fsync it. These operations
are written to disk and fsynced which is fine but the previous buffer flush might have written some bytes
to disk which are not corrupting the translog. That wouldn't be an issue if we prevented the fsync.

Closes #15333

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java [hunk 1]
```diff
@@ -48,13 +48,17 @@ public BufferingTranslogWriter(ShardId shardId, long generation, ChannelReferenc
...
                 // we use the channel to write, since on windows, writing to the RAF might not be reflected
                 // when reading through the channel
-                data.writeTo(channel);
+                try {
+                    data.writeTo(channel);
+                } catch (Throwable ex) {
+                    closeWithTragicEvent(ex);
+                    throw ex;
+                }
                 writtenOffset += data.length();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: we need to increment the operationCounter here as well (probably means our tests are not strong enough to catch docs that are bigger then the buffer..)

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java [hunk 2]
```diff
@@ -107,15 +119,24 @@ public void sync() throws IOException {
             return;
         }
         synchronized (this) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: might as well synchonize the method now

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java [hunk 3]
```diff
@@ -107,15 +119,24 @@ public void sync() throws IOException {
...
+            ensureOpen();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: unless under lock, I don't think this buys us much(and we check in the flush method)?. we increment the channel reference here, so that might be enough as well.

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java [hunk 4]
```diff
@@ -107,15 +119,24 @@ public void sync() throws IOException {
...
                     flush();
-                    lastSyncedOffset = totalOffset;
+                    offsetToSync = totalOffset;
                 }
                 // we can do this outside of the write lock but we have to protect from
                 // concurrent syncs
-                checkpoint(lastSyncedOffset, operationCounter, channelReference);
+                try {
+                    ensureOpen();
+                    checkpoint(offsetToSync, operationCounter, channelReference);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: should we move this to the write lock? I'm worried now we will write  an offsetToSync that is not correlated to the operation counter.

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 5]
```diff
@@ -147,6 +167,7 @@ public void sync() throws IOException {
         // check if we really need to sync here...
         if (syncNeeded()) {
             try (ReleasableLock lock = writeLock.acquire()) {
+                ensureOpen();
                 lastSyncedOffset = writtenOffset;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: only set this after the checkpoint was written?

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 6]
```diff
@@ -54,6 +55,8 @@
     protected volatile int operationCounter;
     /* the offset in bytes written to the file */
     protected volatile long writtenOffset;
+    protected volatile Throwable tragicEvent;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: can we add some java docs about this?

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 7]
```diff
@@ -1279,4 +1283,108 @@ public void run() {
...
+                        FileChannel channel = factory.open(file);
+                        return new FilterFileChannel(channel) {
+
+                            @Override
+                            public int write(ByteBuffer src) throws IOException {
+                                if (failWrite.get()) {
+                                    throw new IOException("boom");
+                                }
+                                if (simulateDiskFull.get()) {
+                                    if (src.limit() > 1) {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: nice!

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 8]
```diff
@@ -1279,4 +1283,108 @@ public void run() {
...
+                locations.add(translog.add(new Translog.Index("test", "" + opsSynced, Integer.toString(opsSynced).getBytes(Charset.forName("UTF-8")))));
+                opsAdded++;
+                translog.sync();
+                opsSynced++;
+            } catch (IOException ex) {
+                failed = true;
+                assertEquals("no space left on device", ex.getMessage());
+            } catch (Exception ex) {
+                failed = true;
+                assertTrue(ex.toString(), ex.getMessage().startsWith("Failed to write operation"));
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: one does this one happen?

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java (hunk 3 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: I added a comment why this is there

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 9]
```diff
@@ -1279,4 +1283,108 @@ public void run() {
...
+             }
+            simulateDiskFull.set(randomBoolean());
+        }
+        simulateDiskFull.set(false);
+        if (randomBoolean()) {
+            try {
+                locations.add(translog.add(new Translog.Index("test", "" + opsSynced, Integer.toString(opsSynced).getBytes(Charset.forName("UTF-8")))));
+                opsSynced++;
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: we shouldn't be here, right? knowing that we failed before, we should have a tragic exception in the queue? feels like I miss something.

Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: also, shouldn't this be opsAdded?

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java (hunk 8 above)
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: we catch IOExceptions in #add but not in sync I will add a comment

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java (hunk 9 above)
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: yeah we wont' get there - leftover

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 10]
```diff
@@ -1279,4 +1284,125 @@ public void run() {
...
+            try {
+                locations.add(translog.add(new Translog.Index("test", "" + opsSynced, Integer.toString(opsSynced).getBytes(Charset.forName("UTF-8")))));
+                opsAdded++;
+                translog.sync();
+                opsSynced++;
+            } catch (IOException ex) {
+                failed = true;
+                assertEquals("no space left on device", ex.getMessage());
+            } catch (TranslogException ex) {
+                // we catch IOExceptions in Translog#add -- that's how we got here
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: in that case can look at the cause and it should have no space left on device, right?

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 11]
```diff
@@ -782,9 +782,13 @@ protected boolean maybeFailEngine(String source, Throwable t) {
             // but we are double-checking it's failed and closed
             if (indexWriter.isOpen() == false && indexWriter.getTragicException() != null) {
                 failEngine("already closed by tragic event", indexWriter.getTragicException());
+            } else if (translog.isOpen() == false && translog.getTragicException() != null) {
+                failEngine("already closed by tragic event", translog.getTragicException());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: can we say this was a translog tragic event?

**Comment by bleskes** [comment]
LGTM. Great catch.

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 12]
```diff
@@ -118,6 +128,18 @@ public static Type fromString(String type) {
         }
     }
 
+    protected final void closeWithTragicEvent(Throwable throwable) throws IOException {
+        try (ReleasableLock lock = writeLock.acquire()) {
+            if (throwable != null) {
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: Is the incoming throwable really allowed to be null sometimes?  Seems dangerous because then we could close ourselves here but `.getTragicException()` would return null, as if no tragedy occurred?

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 13]
```diff
@@ -143,12 +170,15 @@ public void updateBufferSize(int bufferSize) throws TranslogException {
...
+    public synchronized void sync() throws IOException { // synchronized to ensure only one sync happens a time
         // check if we really need to sync here...
         if (syncNeeded()) {
             try (ReleasableLock lock = writeLock.acquire()) {
-                lastSyncedOffset = writtenOffset;
-                checkpoint(lastSyncedOffset, operationCounter, channelReference);
+                ensureOpen();
+                final long offset = writtenOffset;
+                final int opsCount = operationCounter;
+                checkpoint(offset, opsCount, channelReference);
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: Why do we need to assign to local `offset` and `opsCount` here?  Since we hold the write lock, `writtenOffset` cannot change between the call to `checkpoint` and when we assign it to `lastSyncedOffset`?

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 14]
```diff
@@ -1279,4 +1284,122 @@ public void run() {
...
+                            public int write(ByteBuffer src) throws IOException {
+                                if (simulateDiskFull.get()) {
+                                    if (src.limit() > 1) {
+                                        final int pos = src.position();
+                                        final int limit = src.limit();
+                                        src.limit(limit / 2);
+                                        super.write(src);
+                                        src.position(pos);
+                                        src.limit(limit);
+                                        throw new IOException("no space left on device");
```
Comment (mikemccand) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: Can we change the message to make it clear it's "faked" by this test?  Or maybe just use Lucene's `FakeIOException`?  (Just for future sanity when debugging test failures...).

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java (hunk 13 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: I just did this for consistency with the other impls.

File: core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java (hunk 14 above)
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: sure thing

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java [hunk 15]
```diff
@@ -102,20 +114,28 @@ public boolean syncNeeded() {
...
+                    offsetToSync = totalOffset;
+                    opsCounter = operationCounter;
                 }
                 // we can do this outside of the write lock but we have to protect from
                 // concurrent syncs
-                checkpoint(lastSyncedOffset, operationCounter, channelReference);
+                try {
+                    ensureOpen(); // just for kicks - the checkpoint happens or not either way
+                    checkpoint(offsetToSync, opsCounter, channelReference);
+                } catch (IOException ex) {
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: Hmm should we catch `Throwable` instead of `IOException` like we do in the other tragic cases...?  But I guess then we'd need to exclude `AlreadyClosedException` (that's not tragic)?

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java (hunk 12 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: oh hmm that's a leftover - good catch

**Comment by s1monw** [comment]
@mikemccand @bleskes pushed a new commit

**Comment by bleskes** [comment]
last change LGTM

File: core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java (hunk 13 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: Hmm that's no good, we should fix the other impls too.  Code that looks like it's doing something important for a reason, but in fact is pointless, is dangerous :)  Or is it not pointless?

**Comment by mikemccand** [comment]
LGTM, thanks @s1monw!

**Comment by s1monw** [comment]
I let CI run on this before backporting

**Comment by s1monw** [comment]
pushed to 
* 2.x in https://github.com/elastic/elasticsearch/commit/b3e5518c4b8920e3223a9a6f714ce395b2c20ca2
* 2.1 in https://github.com/elastic/elasticsearch/commit/d51ecc9f0702552eeabe97a5faea65b9a46296c6
* 2.0 in https://github.com/elastic/elasticsearch/commit/aeee579a752ce50eb7ef8dd925dabd619e328dee
