### PR TITLE
Threadpool merge executor does not block aborted merges

### LINKED ISSUE #129335: [CI] ReactiveStorageIT testScaleDuringSplitOrClone failing
**Build Scans:**
- [elasticsearch-periodic #8779 / openjdk21_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/2xsnthrcghsi4)
- [elasticsearch-periodic #8743 / graalvm-ce17_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/6xpf45z65or5i)
- [elasticsearch-pull-request #74672 / part-2](https://gradle-enterprise.elastic.co/s/i7ainbgynt2gk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:autoscaling:internalClusterTest" --tests "org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageIT.testScaleDuringSplitOrClone" -Dtests.seed=3D7A1A66F2013ACD -Dtests.locale=mzn-Arab-IR -Dtests.timezone=Asia/Tomsk -Druntime.java=21
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testScaleDuringSplitOrClone),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
```

**Issue Reasons:**
- [8.19] 3 failures in test testScaleDuringSplitOrClone (0.4% fail rate in 764 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic (10.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by albertzaharovits**
This PR addresses a bug where aborted merges are blocked if there's insufficient disk space.

Previously, the merge disk space estimation did not consider if the operation has been aborted when/while it was enqueued for execution. Consequently, aborted merges, for e.g. when closing a shard, were blocked if their disk space estimation was exceeding the available disk space threshold. In this case, the shard close operation would itself block.

This fix estimates a disk space budget of `0` for aborted merges, and it periodically checks if any enqueued merge tasks have been aborted (more generally, it checks if the budget estimate for any merge tasks has changed, and reorders the queue if so). This way aborted merges are prioritized and are never blocked.

Closes https://github.com/elastic/elasticsearch/issues/129335

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorService.java [hunk 1]
```diff
@@ -632,16 +630,41 @@ void updateBudget(long availableBudget) {
             lock.lock();
             try {
                 this.availableBudget = availableBudget;
-                // update the per-element budget (these are all the elements that are using any budget)
+                // updates the budget of enqueued elements (and possibly reorders the priority queue)
+                updateBudgetOfEnqueuedElementsAndReorderQueue();
+                // update the budget of dequeued, but still in-use elements (these are the elements that are consuming budget)
                 unreleasedBudgetPerElement.replaceAll((e, v) -> budgetFunction.applyAsLong(e.element()));
```
Comment (albertzaharovits) [inline server/src/main/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorService.java:640]: This change will also adjust the budget of **running** merges that have been aborted to `0`. That's a bit optimistic, but I find the alternative implementation convoluted, and it's probably counter-intuitive to estimate `0` for to-be-run merges but not for already-running ones.

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MergeWithLowDiskSpaceIT.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+            .put(super.nodeSettings(nodeOrdinal, otherSettings))
+            // only the threadpool-based merge scheduler has the capability to block merges when disk space is insufficient
+            .put(ThreadPoolMergeScheduler.USE_THREAD_POOL_MERGE_SCHEDULER_SETTING.getKey(), true)
+            // the default of "5s" slows down testing
+            .put(ThreadPoolMergeExecutorService.INDICES_MERGE_DISK_CHECK_INTERVAL_SETTING.getKey(), "100ms")
+            .put(ThreadPoolMergeExecutorService.INDICES_MERGE_DISK_HIGH_WATERMARK_SETTING.getKey(), MERGE_DISK_HIGH_WATERMARK_BYTES + "b")
+            .build();
+    }
+
+    public void testShardCloseWhenDiskSpaceInsufficient() {
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/MergeWithLowDiskSpaceIT.java]: It is not clear to me what this verifies? AFAICS, there is no merge at the end of the test and thus it may not verify anything?

**Review by henningandersen — APPROVED** [review]
LGTM.

We should preferably add specific testing, either before or after merging.

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MergeWithLowDiskSpaceIT.java (hunk 2 above)
Comment (albertzaharovits) [reply server/src/internalClusterTest/java/org/elasticsearch/index/engine/MergeWithLowDiskSpaceIT.java]: Yeah, the test was not ready when you looked at it, it was still WIP, sorry for not being clear.

It is now ready and it tests that we can close a shard (an index) with enqueued merges that are blocked due to insufficient disk space. The merges will be aborted, which should unblock and prioritize them in the queue.

**Comment by albertzaharovits** [comment]
> We should preferably add specific testing, either before or after merging.

In the end, I've added 2 tests here:
 * `MergeWithLowDiskSpaceIT.testShardCloseWhenDiskSpaceInsufficient`
 * `ThreadPoolMergeExecutorServiceDiskSpaceTests.testEnqueuedMergeTasksAreUnblockedWhenEstimatedMergeSizeChanges`

There's decent coverage, I think.

**Comment by albertzaharovits** [comment]
(labeling as a `>non-issue` rather than a `>bug` because the problem was caught before it was released)
