### PR TITLE
Serialize top-level pipeline aggs as part of InternalAggregations

### LINKED ISSUE #40059: CCS: sibling pipeline aggregations don't work when minimizing roundtrips
**Elasticsearch version** (`bin/elasticsearch --version`): latest master snapshot (hash: `8839a72`)

**Plugins installed**: []

**JVM version** (`java -version`): `java version "11.0.1" 2018-10-16 LTS`

**OS version** (`uname -a` if on a Unix-like system): `Darwin Kernel Version 18.2.0`

**Description of the problem including expected versus actual behavior**:

When performing a CCS search request, an error occurs if there is a pipeline aggregation in the query.

The exact error is:
```
   │      java.lang.UnsupportedOperationException: Not supported
   │      	at org.elasticsearch.search.aggregations.pipeline.InternalSimpleValue.doReduce(InternalSimpleValue.java:80) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
   │      	at org.elasticsearch.search.aggregations.pipeline.InternalSimpleValue.doReduce(InternalSimpleValue.java:34) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
   │      	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:135) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
   │      	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:90) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
   │      	at org.elasticsearch.action.search.SearchResponseMerger.getMergedResponse(SearchResponseMerger.java:193) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
   │      	at org.elasticsearch.action.search.TransportSearchAction$3.createFinalResponse(TransportSearchAction.java:389) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
   │      	at org.elasticsearch.action.search.TransportSearchAction$3.createFinalResponse(TransportSearchAction.java:379) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Steps to reproduce**:

1. Start two ES instances, ensuring they have unique `cluster.name`s
2. Bulk index documents into both:
```
POST _bulk
{ "index": { "_index": "sales" } }
{ "price": 10, "payment_type": "credit_card" }
{ "index": { "_index": "sales" } }
{ "price": 20, "payment_type": "cash" }
```
3. Configure one ES instance to talk to the other through CCS
```
POST _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "other": {
          "seeds": [
            "{other_es_instance_address}"
          ]
        }
      }
    }
  }
}
```
4. Perform a CCS search that uses a pipeline aggregations from the same ES instance
```
POST *:sales,sales/_search
{
  "size": 0,
  "aggs": {
    "sales_per_type": {
      "terms": {
        "field": "payment_type.keyword"
      },
      "aggs": {
        "sales": {
          "sum": {
            "field": "price"
          }
        }
      }
    },
    "max_per_type": {
      "max_bucket": {
        "buckets_path": "sales_per_type>sales"
      }
    }
  }
}
```

It's worth noting that the same query does not incur an error when used in either of these contexts:
`POST sales/_search`
`POST *:sales/_search`

The error only occurs when doing them together: `POST *:sales,sales/_search`.

It's also worth noting that the query does not incur an error when you remove the pipeline aggregation:
```
POST *:sales,sales/_search
{
  "size": 0,
  "aggs": {
    "sales_per_type": {
      "terms": {
        "field": "payment_type.keyword"
      },
      "aggs": {
        "sales": {
          "sum": {
            "field": "price"
          }
        }
      }
    }
  }
}
```

This is currently **BREAKING** the Kibana Stack Monitoring app, as we run these sorts of pipeline aggregations which are currently broken with CCS enabled.

The work done [in this PR](https://github.com/elastic/elasticsearch/pull/37000) *might* be related to this, as the description seems like it touches the code around this

### PR DESCRIPTION
**Pull request by javanna**
We currently convert pipeline aggregators to their corresponding
InternalAggregation instance as part of the final reduction phase.
They arrive to the coordinating node as part of QuerySearchResult
objects fom the shards and, despite we may incrementally reduce
aggs (hence we may have some non-final reduce and the final
one later) all the reduction phases happen on the same node.

With CCS minimizing roundtrips though, each cluster performs its
own non-final reduction, and then serializes the results back to
the CCS coordinating node which will perform the final coordination.
This breaks the assumptions made up until now around reductions
happening all on the same node.

With #40101 we have made sure that top-level pipeline aggs are not
reduced as part of the non-final reduction. The next step is to make
sure that they don't get lost, meaning that each coordinating node
needs to send them back to the CCS coordinating node as part of
the top-level `InternalAggregations` object.

Closes #40059

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java [hunk 1]
```diff
@@ -60,18 +64,42 @@ public InternalAggregations(List<InternalAggregation> aggregations) {
     }
 
     /**
-     * Reduces the given list of aggregations
+     * Constructs a new aggregation providing its {@link InternalAggregation}s and {@link SiblingPipelineAggregator}s
+     */
+    public InternalAggregations(List<InternalAggregation> aggregations, List<SiblingPipelineAggregator> topLevelPipelineAggregators) {
+        super(aggregations);
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java]: The other ctr could call this one with: `this(aggregations, Collections.emptyList())` ensuring that the `topLevelPipelineAggregators` list is never `null` ?

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java [hunk 2]
```diff
@@ -121,11 +148,27 @@ public void readFrom(StreamInput in) throws IOException {
...
+        }
     }
 
     @Override
     @SuppressWarnings("unchecked")
     public void writeTo(StreamOutput out) throws IOException {
         out.writeNamedWriteableList((List<InternalAggregation>)aggregations);
+        //TODO update version after backport
+        if (out.getVersion().onOrAfter(Version.V_8_0_0)) {
+            if (topLevelPipelineAggregators == null) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java]: can we rely on an empty list if the aggregations are completely reduced ? This way we don't need the boolean and can call the write list directly.

File: server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+                    } else {
+                        assertNull(deserialized.getTopLevelPipelineAggregators());
+                    }
+                }
+            }
+        }
+    }
+
+    //TODO update version and rename after backport
+    public void testSerializationFromPre_8_0_0() throws IOException {
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java]: I understand the intent of this test and I know that we have similar tests elsewhere but I think it should be moved to a rest test or omitted if we are confident that the existing rest tests are enough to test the bwc serialization. This test checks an internal class that we are allowed to change in a minor release (even a patch release) so I don't think we should use a static representation of the serialization that we'll need to change every time we make a modification to the serialization.

**Review by jimczi — APPROVED** [review]
I left some minor comments but the change looks good to me. I wonder if we could, as a follow up, merge the pipeline aggregators and the internal aggregations in `QuerySearchResult`, might be tricky to handle bwc though so def not in the scope of this pr.

File: server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java (hunk 3 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java]: I think that yaml tests are overkill for this matter, as they are integration tests and take much longer to run. After the backport, this static version is the binary representation of how we serialized the object prior to 6.7.0, which I am pretty sure we will not change. I can add a comment.

Comment (jimczi) [reply server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java]: > I think that yaml tests are overkill for this matter, as they are integration tests and take much longer to run. 

They are overkilled if we write them only to test serialization but since we have some ccs rest tests already it shouldn't be too costly to add one that checks the support for pipeline aggregations. I also agree that we will probably not change the serialization of this class in 6.7.x but my point was more about the general idea of adding serialized bytes from a previous version in a unit test.

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java]: yes, I initially did not do it but I just realized that I can. I was worried about cases with CCS where we receive from e.g. 6.6 and then write the same object to e.g. 7.x. I just need to set the list to an empty one in that case too which removes the need for the list to be nullable 100%.

File: server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java (hunk 3 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java]: I plan to do integration tests for this scenario as part of #40038 , I wanted to add coverage there for the the field collapsing bug as well. I prefer the new java test over the yaml ones personally. But our current CCS integration test don't run against multiple versions, while this unit test makes sure that we can read something that was written from e.g. 6.6 compared to simulating that by calling readFrom on master and setting the version to 6.6. Do you see what I mean? Or am I missing something?

**Comment by javanna** [comment]
> I wonder if we could, as a follow up, merge the pipeline aggregators and the internal aggregations in QuerySearchResult, might be tricky to handle bwc though so def not in the scope of this pr.

yes that is also my goal, we might be able to do this in master and 7.x, indeed bwc is tricky especially for CCS which spans multiple versions. I will work on this as a followup.

File: server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java (hunk 3 above)
Comment (jimczi) [reply server/src/test/java/org/elasticsearch/search/aggregations/InternalAggregationsTests.java]: I understand the intent but I forgot that we don't run the bwc tests in every module, let's leave it like this for now and we can discuss further in #40038

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java]: I added to my TODO list to convert this class to Writeable.
