### PR TITLE
Fail engine if hit document failure on replicas

### LINKED ISSUE #40435: [CI] SearchWithRandomExceptionsIT timeout
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/481/

Does not reproduce
```
./gradlew :server:integTest \
  -Dtests.seed=DC4EDCAF00008763 \
  -Dtests.class=org.elasticsearch.search.basic.SearchWithRandomExceptionsIT \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

```
02:38:57 HEARTBEAT J3 PID(64280@elasticsearch-ci-immutable-ubuntu-1404-1553564409042061385): 2019-03-26T02:38:57, stalled for 1192s at: SearchWithRandomExceptionsIT.testRandomExceptions
02:39:14   2> 三月 26, 2019 3:19:07 上午 com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
02:39:14 Suite: org.elasticsearch.search.basic.SearchWithRandomExceptionsIT
02:39:14   2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s0][write][T#2],5,TGRP-SearchWithRandomExceptionsIT]
02:39:14   1> [2019-03-26T03:19:04,943][INFO ][o.e.s.b.SearchWithRandomExceptionsIT] [testRandomExceptions] before test
# ...
2> WARNING: Suite execution timed out: org.elasticsearch.search.basic.SearchWithRandomExceptionsIT
```
[481-console.txt.gz](https://github.com/elastic/elasticsearch/files/3006450/481-console.txt.gz)

### PR DESCRIPTION
**Pull request by dnhatn**
An indexing on a replica should never fail after it was successfully indexed on a primary. Hence, we should fail an engine if we hit any failure (document level or tragic failure) when processing an indexing on a replica.

Relates #43228
Closes #40435 (see https://github.com/elastic/elasticsearch/issues/40435#issuecomment-509877214).

### CODE REVIEW

**Review by ywelsch — CHANGES_REQUESTED** [review]
This is a tricky PR. We want to make sure we're not recording an operation as failed in the translog when we fail to add it to Lucene on a replica. Instead, we let the failure bubble up to the primary so that it can fail the replica. We could also consider this as a fatal failure, and directly fail the shard once indexing into Lucene fails.
The case we also need to consider is when we replay from the translog to Lucene on recovery from store. Should we then also fail the primary if we fail to replay the operation? This could mean that the primary is unrecoverable, e.g. because of some incompatibility introduced during an upgrade. If we're lenient there, however, it brings the risk of primary and replica going out of sync (if we let the replica locally recover up to global checkpoint). Perhaps we could allow a way for the shard to be recovered with a force command, which changes the history uuid. I think we need a more comprehensive plan here.

**Comment by dnhatn** [comment]
@ywelsch I've updated this PR to proceed with operations on replicas only. Can you please take a look? Thank you!

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -1055,7 +1059,7 @@ private IndexResult indexIntoLucene(Index index, IndexingStrategy plan)
             }
             return new IndexResult(plan.versionForIndexing, index.primaryTerm(), index.seqNo(), plan.currentNotFoundOrDeleted);
         } catch (Exception ex) {
-            if (indexWriter.getTragicException() == null) {
+            if ( treatDocumentFailureAsTragicError(index) == false && indexWriter.getTragicException() == null) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: should we treat `AlreadyClosedException` specially here as well (same as when we index deletion or noop tombstone).

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 2]
```diff
@@ -929,7 +929,11 @@ public IndexResult index(Index index) throws IOException {
             }
         } catch (RuntimeException | IOException e) {
             try {
-                maybeFailEngine("index", e);
+                if (treatDocumentFailureAsTragicError(index)) {
+                    failEngine("index", e);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: can we add more info about document into the "reason" string?

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I pushed https://github.com/elastic/elasticsearch/pull/43523/commits/8725216747348bf96a3ac628bf0d89212fca2723

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: We should not have a special treatment for AlreadyClosedException here. If the engine was failed and closed by other thread, it's perfectly fine to bubble up to the AlreadyClosedException. In fact, we should bubble up AlreadyClosedException so we can [detect](https://github.com/elastic/elasticsearch/blob/4af1649aa8696c0e384fbc4414616368ed51355b/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L1997-L2000) situations where the engine does not have a buggy state.

However, we probably should call `maybeFailEngine` instead of `failEngine` if the exception is AlreadyClosedEngine to avoid unnecessary [warning log](https://github.com/elastic/elasticsearch/blob/399d53e5c03ae4157d9ba107d01fbecfed758972/server/src/main/java/org/elasticsearch/index/engine/Engine.java#L1157-L1162) if the engine was failed already.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 2 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I meant some info about the document itself, i.e. the id of the document (This could help in figuring out why the given failure happened)

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I think we should not try to wrap AlreadyClosedException into an IndexResult as we might possibly write it to the translog during closing.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I added more info in https://github.com/elastic/elasticsearch/pull/43523/commits/c6325268009cc909bf1fadd92ca020f60a42efff.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: ++. Fixed in https://github.com/elastic/elasticsearch/pull/43523/commits/c6325268009cc909bf1fadd92ca020f60a42efff.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 3]
```diff
@@ -1076,6 +1081,15 @@ private IndexResult indexIntoLucene(Index index, IndexingStrategy plan)
         }
     }
 
+    /**
+     * Whether we should treat any document failure as tragic error.
+     * If we hit any failure while processing an indexing on a replica, we should treat that error as tragic and fail the engine.
+     * However, we prefer to fail a request individually (instead of a shard) if we hit a document failure on the primary.
+     */
+    private boolean treatDocumentFailureAsTragicError(Index index) {
+        return index.origin() == Operation.Origin.REPLICA;
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: add TODO here that we want to also investigate this for other origins.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Unrelated failure. @elasticmachine  run elasticsearch-ci/2

**Comment by dnhatn** [comment]
Thanks @ywelsch.
