### PR TITLE
Don't use bitset cache for children filters.

### LINKED ISSUE #10629: Elasticsearch inner_hits query does not return second nested field in object field
Hi All

Please refer to issue <a href="https://github.com/elastic/elasticsearch/issues/10334">10334</a> that was marked as fixed in the latest release (1.5.1). I have tested this today and it still doesnt work correctly. The ArrayOutOfBoundsException is gone, however I now get incorrect data back.  Only the first entry is returned regardless of which entry has matched the search request.

To Replicate: Setup the same template and data as in issue <a href="https://github.com/elastic/elasticsearch/issues/10334">10334</a>:

<pre><code>curl -XPOST 'http://localhost:9200/twitter'

curl -XPOST 'http://localhost:9200/twitter/_mapping/tweet' -d '
{
    "tweet": {
        "properties": {
            "comments": {
                "properties": {
                    "messages": {
                        "type": "nested",
                        "properties": {
                            "message": {
                                "type" : "string", 
                                "index": "not_analyzed"
                            }   
                        }
                    } 
                }
            }
        }
    }
}'

curl -XPOST 'http://localhost:9200/twitter/tweet' -d '
{
    "comments": {
        "messages": [
            {"message": "Nice website"},
            {"message": "Worst ever"}
        ]
    }
}'

</code></pre>

Now search for the message "Worst ever"

<pre><code>
curl -XGET 'http://localhost:9200/twitter/tweet/_search?pretty' -d '
{
    "query": {
        "nested": {
            "path": "comments.messages",
            "query": {
                "match": {"comments.messages.message": "Worst ever"}
            },
            "inner_hits" : {}
        }
    }
}'
</code></pre>

The following gets returned:

<pre><code>
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.4054651,
    "hits" : [ {
      "_index" : "twitter",
      "_type" : "tweet",
      "_id" : "AUzCMIjnYDWhRGHuJRhC",
      "_score" : 1.4054651,
      "_source":
{
    "comments": {
        "messages": [
            {"message": "Nice website"},
            {"message": "Worst ever"}
        ]
    }
},
      "inner_hits" : {
        "comments.messages" : {
          "hits" : {
            "total" : 1,
            "max_score" : 1.4054651,
            "hits" : [ {
              "_index" : "twitter",
              "_type" : "tweet",
              "_id" : "AUzCMIjnYDWhRGHuJRhC",
              "_nested" : {
                "field" : "comments",
                "offset" : 0,
                "_nested" : {
                  "field" : "messages",
                  "offset" : 0
                }
              },
              "_score" : 1.4054651,
              "_source":{"message":"Nice website"}
            } ]
          }
        }
      }
    } ]
  }
}
</code></pre>

This is clearly the incorrect inner hit. As discussed previously with martijnvg a workaround is if I change the object field in my mapping to be nested as well, like this:

<pre><code>
curl -XPOST 'http://localhost:9200/twitter/_mapping/tweet' -d '
{
    "tweet": {
        "properties": {
            "comments": {
                "type": "nested",
                "properties": {
                    "messages": {
                        "type": "nested",
                        "properties": {
                            "message": {
                                "type" : "string", 
                                "index": "not_analyzed"
                            }   
                        }
                    } 
                }
            }
        }
    }
}'
</code></pre>

however doing so results in a larger memory footprint which is undesirable. Also note the use case in #10334 in my second post on the issue that explains why I only need a normal object field containing nested fields.

### PR DESCRIPTION
**Pull request by martijnvg**
Only parent filters should use bitset filter cache, to avoid memory being wasted.

Closes #10662 
Closes #10629

### CODE REVIEW

File: src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java [hunk 1]
```diff
@@ -558,15 +533,20 @@ public ParsedDocument parse(SourceToParse source, @Nullable ParseListener listen
...
                 continue;
             }
 
-            BitDocIdSet nestedTypeBitSet = cache.getBitDocIdSetFilter(objectMapper.nestedTypeFilter()).getDocIdSet(context);
-            if (nestedTypeBitSet != null && nestedTypeBitSet.bits().get(nestedDocId)) {
+            Filter filter = sc.filterCache().cache(objectMapper.nestedTypeFilter(), null, sc.queryParserService().autoFilterCachePolicy());
+            if (filter == null) {
+                continue;
+            }
+            DocIdSet nestedTypeSet = filter.getDocIdSet(context, context.reader().getLiveDocs());
```
Comment (rmuir) [inline src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: Do we really need to pass livedocs?

Comment (martijnvg) [inline src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: it just felt safe to do this... but I don't we need to, because nested docs can't be modified on their own. Their life cycle depends on the parent doc.

Comment (rmuir) [inline src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: I think its a little confusing, since we explicitly didn't pass bits before. IMO we should just have a code comment

Comment (martijnvg) [inline src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: I added a comment regarding this.

File: src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java [hunk 2]
```diff
@@ -558,15 +533,22 @@ public ParsedDocument parse(SourceToParse source, @Nullable ParseListener listen
...
 
-            BitDocIdSet nestedTypeBitSet = cache.getBitDocIdSetFilter(objectMapper.nestedTypeFilter()).getDocIdSet(context);
-            if (nestedTypeBitSet != null && nestedTypeBitSet.bits().get(nestedDocId)) {
+            Filter filter = sc.filterCache().cache(objectMapper.nestedTypeFilter(), null, sc.queryParserService().autoFilterCachePolicy());
+            if (filter == null) {
+                continue;
+            }
+            // We can pass down 'null' as acceptedDocs, because nestedDocId is a doc to be fetched and
+            // therefor is guaranteed to be a live doc.
+            DocIdSet nestedTypeSet = filter.getDocIdSet(context, null);
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: Filter.getDocIdSet can return null, can you check that nestedTypeSet is not null?

Comment (jpountz) [inline src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: Also the iterator.

**Comment by jpountz** [comment]
LGTM

**Comment by jpountz** [comment]
I just left a comment about some missing null checks.
