### PR TITLE
Fixes terms error count for multiple reduce phases

### LINKED ISSUE #23286: Fix terms agg error calculation if shared results are reduced incrementally.
During #23253 an issue raised with the terms aggs error calculation. Details are attached to the test case [here](https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/search/aggregations/bucket/TermsDocCountErrorIT.java#L72)

I need help with this from either @jpountz and / or @colings86

### PR DESCRIPTION
**Pull request by colings86**
Previously when multiple reduces occured for the terms aggregation we would add up the errors for the aggregations but would not take into account the errors that had already been calculated for the previous reduce phases.

This change corrects that by adding the previously created errors to the new error value.

Closes #23286

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/TermsDocCountErrorIT.java [hunk 1]
```diff
@@ -88,7 +87,7 @@ public static Client client() {
                  */
                 @Override
                 public SearchRequestBuilder prepareSearch(String... indices) {
-                    return this.in.prepareSearch(indices).setReduceUpTo(512);
+                    return this.in.prepareSearch(indices);
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/TermsDocCountErrorIT.java]: I think you can remove this entire client() method?

**Review by s1monw — APPROVED** [review]
I have no idea if that is a good fix but if the test passes LGTM

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java [hunk 2]
```diff
@@ -227,6 +226,8 @@ public InternalAggregation doReduce(List<InternalAggregation> aggregations, Redu
                 thisAggDocCountError = 0;
             } else if (InternalOrder.isCountDesc(this.order)) {
                 thisAggDocCountError = terms.getBucketsInternal().get(terms.getBucketsInternal().size() - 1).docCount;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java]: This line does not look correct to me: what if the `terms` aggregation already has an error? And what if the {size-1}-th terms has some error too?

**Comment by colings86** [comment]
I think this fix will work but I still need to test it properly

**Comment by colings86** [comment]
@jpountz This should now be ready for review again

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java [hunk 3]
```diff
@@ -226,7 +225,15 @@ public InternalAggregation doReduce(List<InternalAggregation> aggregations, Redu
             if (terms.getBucketsInternal().size() < getShardSize() || InternalOrder.isTermOrder(order)) {
                 thisAggDocCountError = 0;
             } else if (InternalOrder.isCountDesc(this.order)) {
-                thisAggDocCountError = terms.getBucketsInternal().get(terms.getBucketsInternal().size() - 1).docCount;
+                if (terms.getDocCountError() > 0) {
+                    // If there is an existing docCountError for this agg then
+                    // use this as the error for this aggregation
+                    thisAggDocCountError = terms.getDocCountError();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java]: maybe we should better name this variable (or add comments) to reflect that it is about the error that this particular agg might introduce for the global results? Right now it looks like it is about the error for this particular agg, so it feels wrong to not use `terms.getDocCountError()` all the time.

**Review by jpountz — COMMENTED** [review]
I think this is correct. I noticed you did not change the logic around per-term errors, is the current logic correct in the case of multiple reduce phases too?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java (hunk 3 above)
Comment (colings86) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java]: Would `newAggDocCountError` be clearer here since we are working out the error for the new reduced agg?

**Comment by colings86** [comment]
> I noticed you did not change the logic around per-term errors, is the current logic correct in the case of multiple reduce phases too?

yes it should be, and this should be tested by the other methods in `TermsDocCountErrorIT` since they randomise the number of shards and the threshold for reduces. The reason the per-term error logic hasn't changed is that the per term error is calculated from combining the overall agg errors which encompass the information each term requires to determine what error to apply if the term was not returned form the shard. The logic for this was already incremental

**Review by jpountz — APPROVED** [review]
LGTM
