### PR TITLE
Fix _only_nodes preferences

### LINKED ISSUE #12546: _only_nodes against a node attribute not shuffling requests between nodes
Reproducible using 1.7.1 and 5.0 Alpha 2.
https://gist.github.com/ppf2/a5a04d94cc7e0fc3859e

Not sure if `_only_nodes:pod:A` is the right way to specify the value, but it certainly complains about _only_nodes:bogus_name:A and _only_nodes:pod:bogus_value.  So far, not seeing it shuffle between the nodes sharing the same node attribute.

### LINKED ISSUE #12700: Multiple node spec does not work with _only_nodes search preference
Have 4 nodes, 3 are sharing the node attribute B, and 1 is using the node attribute A.

Per node specification (https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.html#cluster-nodes), the following works: 

The following returns 3 nodes:

```
curl -XGET "http://localhost:9200/_nodes/pod:B?pretty"
```

The following returns 1 node:
```
curl -XGET "http://localhost:9200/_nodes/pod:A?pretty"
```

The following returns 4 nodes:

```
curl -XGET "http://localhost:9200/_nodes/pod:B,pod:A?pretty"
```

However, the `_only_nodes` specification for search preference does not work (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html#search-request-preference):

```
curl -XGET "http://localhost:9200/only_node_test/_search?preference=_only_nodes:pod:B,pod:A"

{
   "error": "IllegalArgumentException[No data node with critera [pod:B,pod:A] found]",
   "status": 500
}
```

What is the right syntax for the argument to use multiple node attributes as part of _only_nodes search preference?

### PR DESCRIPTION
**Pull request by jimczi**
- Handle multiple attributes/names (coma separated): _only_nodes:a,b,c
- Shuffle the nodes that match the preferences.

Fix #12546
Fix #12700

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM thanks for fixing this

File: core/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java [hunk 1]
```diff
@@ -331,42 +332,45 @@ public ShardIterator replicaFirstActiveInitializingShardsIt() {
...
         }
-        for (ShardRouting shardRouting : allInitializingShards) {
+        for (ShardRouting shardRouting : shuffler.shuffle(allInitializingShards, seed)) {
             if (selectedNodes.contains(shardRouting.currentNodeId())) {
                 ordered.add(shardRouting);
             }
         }
         if (ordered.isEmpty()) {
-            throw new IllegalArgumentException("No data node with criteria [" + nodeAttribute + "] found");
+            throw new IllegalArgumentException("\"No data nodes with critera(s) " +
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java]: There's an extra escaped quote here?

File: core/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java [hunk 2]
```diff
@@ -178,7 +178,7 @@ private ShardIterator preferenceActiveShardIterator(IndexShardRoutingTable index
                     return indexShard.onlyNodeActiveInitializingShardsIt(nodeId);
                 case ONLY_NODES:
                     String nodeAttribute = preference.substring(Preference.ONLY_NODES.type().length() + 1);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java]: Should this local variable be renamed `nodeAttributes`?

File: core/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java]: Nit: `No` -> `no`.

**Comment by jasontedor** [comment]
I left a few minor comments, otherwise LGTM. Fire at will.

**Comment by jimferenczi** [comment]
Thanks @jasontedor @s1monw
