### PR TITLE
[ML] Ensure feature importance is not empty in RegressionIT

### LINKED ISSUE #59413: RegressionIT testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/5fxzmspwrij5s

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows" \
  -Dtests.seed=50E4467094AC6573 \
  -Dtests.security.manager=true \
  -Dtests.locale=th \
  -Dtests.timezone=SystemV/MST7MDT \
  -Druntime.java=8
```

**Reproduces locally?**:
Nope

**Applicable branches**:
Master, 7.x

**Failure history**:
Not the first time

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,class,stacktrace,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RegressionIT),sort:!(time,desc))

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: a collection with size a value greater than <0>
     but: collection size <0> was equal to <0>
	at __randomizedtesting.SeedInfo.seed([50E4467094AC6573:44F0E3F9D85A697A]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ml.integration.RegressionIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows(RegressionIT.java:105)
```

### LINKED ISSUE #59664: RegressionIT.testWithDatastream fails on 7.9 branch
**Build scan**:
https://gradle-enterprise.elastic.co/s/7j3rvve56jzss

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testWithDatastream" -Dtests.seed=DB5C0242FF9869CB -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=Pacific/Fakaofo -Druntime.java=8	
```

**Reproduces locally?**:
Nope

**Applicable branches**:
7.9

**Failure history**:
Failed 12 times in the last week: https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.xpack.ml.integration.RegressionIT&tests.sortField=FAILED&tests.test=testWithDatastream&tests.unstableOnly=true
**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testWithDatastream FAILED
    java.lang.AssertionError: 
    Expected: a collection with size a value greater than <0>
         but: collection size <0> was equal to <0>
        at __randomizedtesting.SeedInfo.seed([DB5C0242FF9869CB:A3B7DE539925F385]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
```

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
This commit addresses the possibility that feature importance
is empty for the row with values 2, 20, 20. The reason this may
happen is because those rows' values are the average of the
other two and the model computes feature importance is close to
zero for that reason.

The test adjusts the values in a way that no row has values
that are the average of the other rows.

Fixes #59413
Fixes #59664

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java [hunk 1]
```diff
@@ -61,9 +60,14 @@
     private static final String NUMERICAL_FEATURE_FIELD = "feature";
     private static final String DISCRETE_NUMERICAL_FEATURE_FIELD = "discrete-feature";
     static final String DEPENDENT_VARIABLE_FIELD = "variable";
-    private static final List<Double> NUMERICAL_FEATURE_VALUES = List.of(1.0, 2.0, 3.0);
-    private static final List<Long> DISCRETE_NUMERICAL_FEATURE_VALUES = List.of(10L, 20L, 30L);
-    private static final List<Double> DEPENDENT_VARIABLE_VALUES = List.of(10.0, 20.0, 30.0);
+
+    // It's important that the values here do not work in a way where
+    // one of the feature is the average of the other features as it may
+    // result to empty feature importance and we want to assert it gets
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:66]:
```suggestion
    // result in empty feature importance and we want to assert it gets
```

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java [hunk 2]
```diff
@@ -61,9 +60,14 @@
...
+    // written out correctly.
+    private static final List<Double> NUMERICAL_FEATURE_VALUES = List.of(5.0, 2.0, 3.0);
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:68]: Just double-checking: is it ok that one feature is the sum of the other two (5 = 2 + 3) or could it also cause a problem?

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java (hunk 2 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:68]: @valeriy42 What do you think?

Comment (valeriy42) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:68]: @przemekwitek this list defines the same feature (e.g. `x_1`) in three different rows. Rows are considered independently and therefore this is absolutely fine.  What you would like to avoid for this test is that one of the target values is the average of all three target values (previously we unfortunately had 20 == (10+20+30)/3 ).

What you probably also might have in mind is that different features in one row should be preferably linearly independen (e.g. x_1 = a* x_2 + b* x_3). This might lead to a problem but we use some techniques so that we don't have problem with linear dependency.

Comment (przemekwitek) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:68]: Thanks for explanation @valeriy42 !
