### PR TITLE
Attempt to clean up index before remote transfer

### LINKED ISSUE #104473: Clean up extra/temp files before file-based recovery
If a node crashes part-way through a recovery then it may leave some temp files on disk. A subsequent recovery attempt will eventually clean up any unnecessary files but that cleanup happens towards the end of the recovery process, after making a new copy of the shard on disk, and it's possible that there may not be space for all this data because of the space wasted on old temp files.

Today one of the preparatory steps on a recovery target is to replay any safe operations from the local translog and then flush to make a new safe commit, which happens before we even start to copy any data from the recovery source. After successfully making that new safe commit I think it'd be reasonable to do another cleanup step to discard anything that isn't referenced from that commit, which would include any temporary files from a previous recovery. I suspect we might also be able to clean some things up before replaying the local translog.

### PR DESCRIPTION
**Pull request by bcully**
If a node crashes during recovery, it may leave temporary files behind that can consume disk space, which may be needed to complete recovery. So we attempt to clean up the index before transferring files from a recovery source. We first attempt to call the store's `cleanupAndVerify` method, which removes anything not referenced by the latest local commit. If that fails, because the local index isn't in a state to produce a local commit, then we fall back to removing temporary files by name.

Closes #104473

### CODE REVIEW

**Comment by bcully** [comment]
I'm doing this as part of onboarding, and don't really have any idea what I'm doing yet. Any kind of feedback is welcome.

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java [hunk 1]
```diff
@@ -104,18 +105,43 @@ public void testCancelRecoveryAndResume() throws Exception {
...
+                            // verify on the second recovery attempt that the garbage has been removed before we fetch files again #104473
+                            var shardId = ((RecoveryFilesInfoRequest) request).shardId();
+                            var shardPath = unluckyIndices.indexService(shardId.getIndex())
+                                .getShard(shardId.getId())
+                                .shardPath()
+                                .resolveIndex();
+                            logger.info("checking for garbage at {}", shardPath.resolve("recovery.garbage"));
+                            assertFalse(
+                                "garbage file should have been cleaned before file transmission",
+                                Files.exists(shardPath.resolve("garbage"))
```
Comment (idegtiarenko) [inline server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:143]: I believe this checks for a wrong file, not the one created earlier (`recovery.garbage` vs `garbage`).
It would be nice to extract its name as variable earlier in the code and possibly randomize the file name.

Comment (bcully) [reply server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:143]: Whoops! Sounds good, I'll randomly generate some during round 1 and verify that they are all gone before transfer in round 2.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java [hunk 2]
```diff
@@ -397,6 +397,32 @@ record StartRecoveryRequestToSend(StartRecoveryRequest startRecoveryRequest, Str
...
+                    store.incRef();
+                    try {
+                        store.cleanupAndVerify("cleanup before peer recovery", indexShard.snapshotStoreMetadata());
+                    } catch (IOException e) {
+                        // if we can't read a snapshot, then we don't have enough intact data locally to create one.
+                        // Make an attempt to clean up temporary files from the previous run. We could also just delete
+                        // everything in the directory but in that case we might want to be a little more thoughtful about
+                        // the exact exception triggered here. Corrupt indices might be recoverable without a full transfer, for
+                        // example.
+                        logger.info("cleanup before peer recovery failed on shard [{}]; exception: [{}]", indexShard.shardId(), e);
```
Comment (Tim-Brooks) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:414]: logger.info(() -> format("cleanup before peer recovery failed on shard [%s]", indexShard.shardId()), e);

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java [hunk 3]
```diff
@@ -397,6 +397,32 @@ record StartRecoveryRequestToSend(StartRecoveryRequest startRecoveryRequest, Str
...
+                        try {
+                            recoveryTarget.cleanTempFiles();
+                        } catch (IOException ie) {
+                            // log and ignore. Recovery gets another chance to clean up after file transfer.
+                            logger.warn("temporary file cleanup failed on shard [{}]; exception: [{}]", indexShard.shardId(), ie);
```
Comment (Tim-Brooks) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:419]: logger.warn(() -> format("temporary file cleanup failed on shard [%s]", indexShard.shardId()), ie);

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 2 above)
Comment (Tim-Brooks) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:414]: We prefer to use the logger method which takes the exception. Also, `Supplier` is an option. But you can also pass `formatted string` directly. It's extremely common to use supplier for trace/debug logs which are normally disabled. Since warn, error, and info are normally enabled I don't think it makes a huge difference.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java [hunk 4]
```diff
@@ -397,6 +397,32 @@ record StartRecoveryRequestToSend(StartRecoveryRequest startRecoveryRequest, Str
...
                     indexShard.recoverLocallyUpToGlobalCheckpoint(ActionListener.assertOnce(l));
                 })
+                // peer recovery can consume a lot of disk space, so it's worth cleaning up locally ahead of the attempt
+                // operation runs only if the previous operation succeeded, and returns the previous operation's result.
+                // Failures at this stage aren't fatal, we can attempt to recover and then clean up again at the end. #104473
+                .andThenApply(startingSeqNo -> {
+                    Store store = indexShard.store();
+                    store.incRef();
+                    try {
+                        store.cleanupAndVerify("cleanup before peer recovery", indexShard.snapshotStoreMetadata());
```
Comment (Tim-Brooks) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:407]: This wraps some IOExceptions in `throw new IllegalStateException("Can't delete " + existingFile + " - cleanup failed", ex);`. Is that something we should be catching and handling?

Comment (Tim-Brooks) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:407]:
```java
 catch (IOException ex) {
                    if (existingFile.startsWith(IndexFileNames.SEGMENTS) || existingFile.startsWith(CORRUPTED_MARKER_NAME_PREFIX)) {
                        // TODO do we need to also fail this if we can't delete the pending commit file?
                        // if one of those files can't be deleted we better fail the cleanup otherwise we might leave an old commit
                        // point around?
                        throw new IllegalStateException("Can't delete " + existingFile + " - cleanup failed", ex);
                    }
                    logger.debug(() -> "failed to delete file [" + existingFile + "]", ex);
                    // ignore, we don't really care, will get deleted later on
                }
```

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java [hunk 5]
```diff
@@ -102,20 +104,50 @@ public void testCancelRecoveryAndResume() throws Exception {
...
+        // Cleanup helps prevent recovery from failing due to lack of space from garbage left over from a previous
+        // recovery that crashed during file transmission. #104473
+        // We can't look for the presence of the recovery temp files themselves because they are automatically
+        // cleaned up on clean shutdown by MultiFileWriter.
+        final String GARBAGE_PREFIX = "recovery.garbage.";
+
         final CountDownLatch latch = new CountDownLatch(1);
         final AtomicBoolean truncate = new AtomicBoolean(true);
+        IndicesService unluckyIndices = internalCluster().getInstance(IndicesService.class, unluckyNode);
         for (NodeStats dataNode : dataNodeStats) {
```
Comment (Tim-Brooks) [inline server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:117]: I'm pretty sure we can get ride of this and just add the send behavior from primary -> unlucky

**Review by Tim-Brooks — COMMENTED** [review]
A couple comments. I think we'll need @DaveCTurner to verify that this high level design is what he had in mind.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 2 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:414]: I see. I was trying to be consistent with the [neighboring code](https://github.com/elastic/elasticsearch/blob/d6f8de22d697cd4db7a6f0eb179d6835867e9d35/server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java#L364) but I can see that it is [in](https://github.com/elastic/elasticsearch/blob/d6f8de22d697cd4db7a6f0eb179d6835867e9d35/server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java#L261) [flux](https://github.com/elastic/elasticsearch/blob/d6f8de22d697cd4db7a6f0eb179d6835867e9d35/server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java#L256) and will use the lambda form, and not eagerly stringify the exception.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 4 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:407]: My thinking was that this same method gets called a little later, where it does do some [more complicated decision making](https://github.com/elastic/elasticsearch/blob/d6f8de22d697cd4db7a6f0eb179d6835867e9d35/server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java#L539) around exceptions. We could replicate some of that logic here, which could save some transfer work if a recovery is doomed for file system reasons, but my first instinct was to avoid adding new failure modes to recovery, and that replicating or refactoring the handling logic wasn't worth it for this case, which I wouldn't expect to be common enough to need optimization.

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java (hunk 5 above)
Comment (bcully) [reply server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:117]: I'm not following this. I was using this to get the shard path on disk where I could scribble junk files and then check they were removed. It did seem a little indirect - is there a nicer way?

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java [hunk 6]
```diff
@@ -102,20 +104,50 @@ public void testCancelRecoveryAndResume() throws Exception {
...
             MockTransportService.getInstance(dataNode.getNode().getName())
                 .addSendBehavior(
-                    internalCluster().getInstance(TransportService.class, unluckyNode.getNode().getName()),
+                    internalCluster().getInstance(TransportService.class, unluckyNode),
                     (connection, requestId, action, request, options) -> {
                         if (action.equals(PeerRecoveryTargetService.Actions.FILE_CHUNK)) {
                             RecoveryFileChunkRequest req = (RecoveryFileChunkRequest) request;
                             logger.info("file chunk [{}] lastChunk: {}", req, req.lastChunk());
                             if ((req.name().endsWith("cfs") || req.name().endsWith("fdt")) && req.lastChunk() && truncate.get()) {
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:125]: I'm wondering why we write a garbage file only under these conditions. Could we write the garbage file always, say on receipt of the first `FILE_CHUNK` message?

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java [hunk 7]
```diff
@@ -397,6 +397,32 @@ record StartRecoveryRequestToSend(StartRecoveryRequest startRecoveryRequest, Str
...
+                    } catch (IOException e) {
+                        // if we can't read a snapshot, then we don't have enough intact data locally to create one.
+                        // Make an attempt to clean up temporary files from the previous run. We could also just delete
+                        // everything in the directory but in that case we might want to be a little more thoughtful about
+                        // the exact exception triggered here. Corrupt indices might be recoverable without a full transfer, for
+                        // example.
+                        logger.info(() -> format("cleanup before peer recovery failed on shard [{}]", indexShard.shardId()), e);
+                        try {
+                            recoveryTarget.cleanTempFiles();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:416]: should we hold a ref to `recoveryTarget` for this call?

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java [hunk 8]
```diff
@@ -397,6 +397,32 @@ record StartRecoveryRequestToSend(StartRecoveryRequest startRecoveryRequest, Str
...
                 })
+                // peer recovery can consume a lot of disk space, so it's worth cleaning up locally ahead of the attempt
+                // operation runs only if the previous operation succeeded, and returns the previous operation's result.
+                // Failures at this stage aren't fatal, we can attempt to recover and then clean up again at the end. #104473
+                .andThenApply(startingSeqNo -> {
+                    Store store = indexShard.store();
+                    store.incRef();
+                    try {
+                        store.cleanupAndVerify("cleanup before peer recovery", indexShard.snapshotStoreMetadata());
+                    } catch (IOException e) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:408]: I think I might prefer to restrict this `catch` just to exceptions from `indexShard.snapshotStoreMetadata()` rather than from `cleanupAndVerify()` too. If `cleanupAndVerify()` fails then that seems like it maybe should be fatal?

Also could we use `org.elasticsearch.index.store.Store.MetadataSnapshot#EMPTY` to represent the snapshot if we cannot get a proper `MetadataSnapshot`? Any file re-use during recovery is going to require a valid `MetadataSnapshot`, so failing here means that the directory contents are of no further use.

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java [hunk 9]
```diff
@@ -102,20 +104,50 @@ public void testCancelRecoveryAndResume() throws Exception {
...
+                                var shardPath = unluckyIndices.indexService(shardId.getIndex())
+                                    .getShard(shardId.getId())
+                                    .shardPath()
+                                    .resolveIndex();
+                                final var garbagePath = Files.createTempFile(shardPath, GARBAGE_PREFIX, null);
+                                logger.info("writing garbage at: {}", garbagePath);
                                 latch.countDown();
                                 throw new RuntimeException("Caused some truncated files for fun and profit");
                             }
+                        } else if (action.equals(PeerRecoveryTargetService.Actions.FILES_INFO) && truncate.get() == false) {
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:136]: Do we need to check `truncate.get() == false` in this condition? I think that's there so that we only run this check on the second recovery, but sometimes we're going to get here before setting `truncate` to `false`, and there should be no garbage files on the first recovery either right?

**Review by DaveCTurner — COMMENTED** [review]
Trickier than I expected :) I left a few comments.

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java (hunk 9 above)
Comment (bcully) [reply server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:136]: That's true. I think we're going to pass through this phase for most shards before we write the garbage into place, but it is harmless to assert that the index starts out clean. I'll remove the guard.

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java (hunk 6 above)
Comment (bcully) [reply server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:125]: We could. I think we just need a little extra bookkeeping so that we create garbage once per shard rather than once per test or once per chunk. Wasn't sure it was worth it - the filter here seemed like a reasonable proxy. But I can add the explicit bookkeeping if you prefer.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 8 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:408]: Tim made a similar comment, to which I replied above. There is some logic in `cleanFiles` that inspects the exception generated by the block containing `cleanupAndVerify` and does a deeper clean in some cases. Looking at it again, I think it's not just an optimization. We'd probably need to replicate that to avoid having to worry about corrupt directories that we can never make forward progress on because we never get a chance to deep clean them.

Is it always true that the files are useless if we can't get a metadata snapshot? I had been thinking that for instance we might have transferred a bunch of data files previously but not the root segment file. In that case, after transferring the segment file we could reuse the data files already transferred?

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 7 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:416]: probably yes, I'll add that.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 8 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:408]: > Is it always true that the files are useless if we can't get a metadata snapshot?

Yes I think so, we treat a failure as if the store is empty, see how we compute `metadataSnapshot` in `org.elasticsearch.indices.recovery.PeerRecoveryTargetService#getStartRecoveryRequest` and then use this data (alone) to compute the collection of files to recover in the implementations of `org.elasticsearch.indices.recovery.plan.RecoveryPlannerService#computeRecoveryPlan`.

I mean you're right, in principle we could work harder to determine which exact files we do/don't have and avoid a little extra data transfer sometimes. But we don't: this is already on a failure path, and not a particularly well-trodden one, so there's no need for heroic optimizations.

File: server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/recovery/TruncatedRecoveryIT.java:125]: Yeah I'd rather we were explicit here, otherwise future-me is going to wonder what's special about these particular `FILE_CHUNK` messages.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 8 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:408]: I thought a bit more about this and am inclined to use `Store.MetadataSnapshot#EMPTY` when `snapshotStoreMetadata()` throws. Interestingly, when I tried it, I found that `store.cleanupAndVerify` appears to throw on an empty directory, [here](https://github.com/elastic/elasticsearch/blob/8efd08b019b9160f5e703520c6ce3b6a9f92cfbd/server/src/main/java/org/elasticsearch/index/store/Store.java#L699):

```
...
Caused by: java.io.FileNotFoundException: no segments* file found in store(ByteSizeCachingDirectory(ElasticsearchMockDirectoryWrapper(NIOFSDirectory@/Users/brendan/dev/elasticsearch/server/build/testrun/internalClusterTest/temp/org.elasticsearch.recovery.TruncatedRecoveryIT_31340047D7FA1434-001/tempDir-002/node_t4/indices/QuuB7D0wSki7rj5uryRXWQ/4/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@b7a4d9))): files: [write.lock]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:801)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:757)
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:535)
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:519)
	at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:116)
	at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:224)
	at org.elasticsearch.index.store.Store$MetadataSnapshot.loadFromIndexCommit(Store.java:822)
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:298)
	at org.elasticsearch.index.store.Store.getMetadata(Store.java:263)
	at org.elasticsearch.index.store.Store.cleanupAndVerify(Store.java:699)
...
```

Given the name of the variable being assigned here is `metadataOrEmpty` it seems like it might be a bug, and we just haven't tested against an empty snapshot. If you agree, I'll attempt to fix that and go with this approach of falling back to `Empty`.

Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:408]: https://github.com/elastic/elasticsearch/pull/116059 adds support for empty stores to `Store#cleanupAndVerify`

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 4 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java]: I had actually misread this comment - I now see your point was that IllegalStateExceptions were escaping here and could fail recovery before we had a chance to pull, which might fix the problem.

I think the errors here (delete failure) are not likely to be repaired by the peer, so we might as well bail out here and save some potentially expensive transfer for a likely doomed recovery attempt. The verification step also throws some IllegalStateExceptions, which I also think are an abnormal condition (cleanup is supposed to reconcile the directory with the provided snapshot) that needs investigation.

I've taken David's suggestion and treated the directory as having an empty snapshot (which will cause cleanup to remove everything), which I think makes cleanup more robust to partially transferred indices (at the cost of potentially retransmitting some files).

I could go either way on that, I don't really have a sense for how much extra work that could create in practice.

File: server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java (hunk 8 above)
Comment (bcully) [reply server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java:407]: after making `cleanupAndVerify` handle an empty snapshot, I've taken your suggestion and treated the directory as having an empty snapshot if we fail to load one.

**Comment by bcully** [comment]
@Tim-Brooks @DaveCTurner gentle reminder for a rereview, thanks!

**Comment by bcully** [comment]
@elasticmachine update branch

**Review by Tim-Brooks — APPROVED** [review]
LGTM
