### PR TITLE
Fix ST_DISTANCE handling of invalid geometry literals that fold to null

### LINKED ISSUE #138594: NullPointerException when planning makeGeometryFromLiteralValue
### Elasticsearch Version

Serverless

### Installed Plugins

n/a

### Java Version

_bundled_

### OS Version

-

### Problem Description

We were alerted to some NPEs with the attached stack trace. I was not able to isolate the query that triggered these. 

### Steps to Reproduce

I was not able to reproduce the problem.

### Logs (if relevant)

```
java.lang.NullPointerException: Cannot invoke \"Object.getClass()\" because \"value\" is null
	at org.elasticsearch.xpack.esql.expression.function.scalar.spatial.SpatialRelatesUtils.makeGeometryFromLiteralValue(SpatialRelatesUtils.java:213)
	at org.elasticsearch.xpack.esql.expression.function.scalar.spatial.SpatialRelatesUtils.makeGeometryFromLiteral(SpatialRelatesUtils.java:189)
	at org.elasticsearch.xpack.esql.expression.function.scalar.spatial.StDistance.fold(StDistance.java:286)
	at org.elasticsearch.xpack.esql.core.expression.Literal.of(Literal.java:201)
	at org.elasticsearch.xpack.esql.optimizer.rules.RuleUtils.lambda$foldableReferences$1(RuleUtils.java:100)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$forEachUp$1(Node.java:129)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachUp(Node.java:122)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachUp(Node.java:127)
	at org.elasticsearch.xpack.esql.plan.QueryPlan.lambda$forEachExpressionUp$21(QueryPlan.java:207)
	at org.elasticsearch.xpack.esql.plan.QueryPlan.doForEachExpression(QueryPlan.java:213)
	at org.elasticsearch.xpack.esql.plan.QueryPlan.doForEachExpression(QueryPlan.java:216)
	at org.elasticsearch.xpack.esql.plan.QueryPlan.lambda$forEachExpressionUp$22(QueryPlan.java:207)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachProperty(Node.java:151)
	at org.elasticsearch.xpack.esql.core.tree.Node.lambda$forEachPropertyUp$3(Node.java:143)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachUp(Node.java:122)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachUp(Node.java:120)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachUp(Node.java:120)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachUp(Node.java:120)
	at org.elasticsearch.xpack.esql.core.tree.Node.forEachPropertyUp(Node.java:143)
	at org.elasticsearch.xpack.esql.plan.QueryPlan.forEachExpressionUp(QueryPlan.java:207)
	at org.elasticsearch.xpack.esql.optimizer.rules.RuleUtils.foldableReferences(RuleUtils.java:91)
	at org.elasticsearch.xpack.esql.optimizer.rules.logical.PropagateEvalFoldables.apply(PropagateEvalFoldables.java:28)
	at org.elasticsearch.xpack.esql.optimizer.rules.logical.PropagateEvalFoldables.apply(PropagateEvalFoldables.java:24)
	at org.elasticsearch.xpack.esql.rule.ParameterizedRuleExecutor.lambda$transform$0(ParameterizedRuleExecutor.java:29)
	at org.elasticsearch.xpack.esql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:111)
	at org.elasticsearch.xpack.esql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:190)
	at org.elasticsearch.xpack.esql.rule.RuleExecutor.execute(RuleExecutor.java:159)
	at org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizer.optimize(LogicalPlanOptimizer.java:120)
	at org.elasticsearch.xpack.esql.session.EsqlSession.optimizedPlan(EsqlSession.java:951)
	at org.elasticsearch.xpack.esql.session.EsqlSession$1.lambda$onResponse$1(EsqlSession.java:243)
etc
```

### PR DESCRIPTION
**Pull request by craigtaverner**
Occasionally on serverless we see a NullPointerException in parsing a geometry literal within ST_DISTANCE functions. This turned out to be hard to reproduce since we cannot see the original query causing this problem. It has been reported in https://github.com/elastic/elasticsearch/issues/138594, including a full stack track confirming that it occurs during planning, while folding literals.

It turned out to be reproducible with a query like:

```
ROW point = MV_SLICE(["POINT(0)"], 0, 0)::geo_point
| EVAL distance = ST_DISTANCE(point, point)
```

Here the WKT is invalid, and the fold over the MV_SLICE would return literal `null` values, since the inner TO_GEOPOINT function was throwing exceptions (since the WKT was invalid). It turned out that MvSlice was using EvaluatorMapper.fold for folding the children, which returns literal java `null` values, and any function using these values needs to also handle literal nulls. So, `fold()` is expected to explicitly return null values when input is null, and the implementation of fold in StDistance did not do this.

This PR now covers all descendents of BinarySpatialFunction:
* ST_DISTANCE
* ST_INTERSECTS
* ST_DISJOINT
* ST_CONTAINS
* ST_WITHIN

Fixes #138594

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java [hunk 1]
```diff
@@ -209,9 +209,8 @@ private static Geometry makeGeometryFromLiteralValue(Object value, DataType data
             }
             return new GeometryCollection<>(geometries);
         } else {
-            throw new IllegalArgumentException(
-                "Unsupported combination of literal [" + value.getClass().getSimpleName() + "] of type [" + dataType + "]"
-            );
+            var objType = (value == null ? "null" : value.getClass().getSimpleName());
+            throw new IllegalArgumentException("Unsupported combination of literal [" + objType + "] of type [" + dataType + "]");
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java]: Isn't there a difference between the Java `null` value, and an object of type `null` (i.e., ESQL's `NULL`)? Or is the former the way we represent the latter in this case?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java:1]: Got to reproduce this with:
```
ROW x = MV_SLICE(["1"], 0, 0)::geo_point
| EVAL y = st_distance(x, x)
```

I had to add that MV_SLICE part, that ends up being null, but probably avoids some other null folding rules

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java (hunk 1 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java]: Yes, the java null should never appear here, which is why I've been unable to reproduce this. I think the actual bug lies elsewhere and is creating this java null during the fold operation, somewhere in another function.

Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java]: So it seems my st_distance.fold function was not correctly following null folding rules. We need explicit support for nulls here, and I've changed this code to return null instead of throwing an exception.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesUtils.java:1]: Thanks Ivan, that helped me track down and fix the real bug. It appears that fold needs to explicitly handle nulls. The default implementation of fold in EvaluatorMapper returns a raw java null, and all overriding implementations appear to need to do that too.

**Review by GalLalouche — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialWithin.java [hunk 2]
```diff
@@ -132,16 +128,8 @@ protected NodeInfo<? extends Expression> info() {
...
-            GeometryDocValueReader docValueReader = asGeometryDocValueReader(ctx, crsType(), left());
-            Component2D component2D = asLuceneComponent2D(ctx, crsType(), right());
-            return (crsType() == SpatialCrsType.GEO)
-                ? GEO.geometryRelatesGeometry(docValueReader, component2D)
-                : CARTESIAN.geometryRelatesGeometry(docValueReader, component2D);
-        } catch (IOException e) {
-            throw new IllegalArgumentException("Failed to fold constant fields: " + e.getMessage(), e);
-        }
+    protected SpatialRelations getSpatialRelations() {
+        return (crsType() == SpatialCrsType.GEO) ? GEO : CARTESIAN;
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialWithin.java]: Redundant parens.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java [hunk 3]
```diff
@@ -86,6 +89,40 @@ public DataType dataType() {
...
+    public Object fold(FoldContext ctx) {
+        try {
+            if (this.spatialTypeResolver.supportsGrid) {
+                if (DataType.isGeoGrid(left().dataType())) {
+                    return foldGeoGrid(ctx, right(), left(), left().dataType());
+                } else if (DataType.isGeoGrid(right().dataType())) {
+                    return foldGeoGrid(ctx, left(), right(), right().dataType());
+                }
+            }
+            GeometryDocValueReader docValueReader = asGeometryDocValueReader(ctx, crsType(), left());
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:116]: FWIW, you could shave a few cycles if you early exit here when `docValuesReader` is already `null` (though IIUC folding is done during planning so is probably not on the hot path).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialDisjoint.java [hunk 4]
```diff
@@ -147,26 +141,8 @@ protected NodeInfo<? extends Expression> info() {
...
-        } catch (IOException e) {
-            throw new IllegalArgumentException("Failed to fold constant fields: " + e.getMessage(), e);
-        }
-    }
-
-    private Object foldGeoGrid(FoldContext ctx, Expression spatialExp, Expression gridExp, DataType gridType) throws IOException {
-        long gridId = (Long) valueOf(ctx, gridExp);
-        return GEO.compareGeometryAndGrid(makeGeometryFromLiteral(ctx, spatialExp), gridId, gridType);
+    protected SpatialRelations getSpatialRelations() {
+        return (crsType() == SpatialCrsType.GEO) ? GEO : CARTESIAN;
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialDisjoint.java]: Redundant parens

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialIntersects.java [hunk 5]
```diff
@@ -149,26 +143,8 @@ protected NodeInfo<? extends Expression> info() {
...
-        } catch (IOException e) {
-            throw new IllegalArgumentException("Failed to fold constant fields: " + e.getMessage(), e);
-        }
-    }
-
-    private Object foldGeoGrid(FoldContext ctx, Expression spatialExp, Expression gridExp, DataType gridType) throws IOException {
-        long gridId = (Long) valueOf(ctx, gridExp);
-        return GEO.compareGeometryAndGrid(makeGeometryFromLiteral(ctx, spatialExp), gridId, gridType);
+    protected SpatialRelations getSpatialRelations() {
+        return (crsType() == SpatialCrsType.GEO) ? GEO : CARTESIAN;
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialIntersects.java]: Redundant parens.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java [hunk 6]
```diff
@@ -86,6 +89,40 @@ public DataType dataType() {
         return DataType.BOOLEAN;
     }
 
+    /** Spatial relates functions always use Lucene GeometryDocValueReader and Component2D instead of geometries */
+    protected Object fold(Geometry leftGeom, Geometry rightGeom) {
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:94]: Missing a `@Override`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java [hunk 7]
```diff
@@ -217,17 +215,8 @@ protected NodeInfo<? extends Expression> info() {
...
-            Geometry rightGeom = makeGeometryFromLiteral(ctx, right());
-            Component2D[] components = asLuceneComponent2Ds(crsType(), rightGeom);
-            return (crsType() == SpatialCrsType.GEO)
-                ? GEO.geometryRelatesGeometries(docValueReader, components)
-                : CARTESIAN.geometryRelatesGeometries(docValueReader, components);
-        } catch (IOException e) {
-            throw new IllegalArgumentException("Failed to fold constant fields: " + e.getMessage(), e);
-        }
+    protected SpatialRelations getSpatialRelations() {
+        return (crsType() == SpatialCrsType.GEO) ? GEO : CARTESIAN;
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java]: Redundant parens.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/BinarySpatialFunction.java [hunk 8]
```diff
@@ -96,6 +98,18 @@ public void writeTo(StreamOutput out) throws IOException {
         // The CRS type is re-resolved from the combination of left and right fields, and also not necessary to serialize
     }
 
+    protected abstract Object fold(Geometry leftGeom, Geometry rightGeom);
+
+    @Override
+    public Object fold(FoldContext ctx) {
+        var leftGeom = makeGeometryFromLiteral(ctx, left());
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/BinarySpatialFunction.java:105]: FWIW, you could shave a few cycles if you early exit here when `leftGeom` is already `null` (though IIUC folding is done during planning so is probably not on the hot path).

**Review by GalLalouche — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java (hunk 3 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:116]: Yes, not on the hot path. I think the code is simpler with a single `if`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialWithin.java (hunk 2 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialWithin.java]: I find this kind of ternary expression easier to read when the condition is within parentheses. But your point is valid, I've been using parenthesis so long I started thinking they were required...

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/BinarySpatialFunction.java (hunk 8 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/BinarySpatialFunction.java:105]: I'll stick with a single `if` for simplicity.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java (hunk 7 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java]: Done

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java (hunk 6 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:94]: Done

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialIntersects.java (hunk 5 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialIntersects.java]: Done

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialDisjoint.java (hunk 4 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialDisjoint.java]: Done

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialWithin.java (hunk 2 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialWithin.java]: So I did this anyway, since the expression is so simple.

**Comment by craigtaverner** [comment]
Manual backport in https://github.com/elastic/elasticsearch/pull/140265
