### PR TITLE
ESQL: Unmute and fix missing cabability in SubstituteRoundToTests

### LINKED ISSUE #138601: [CI] SubstituteRoundToTests testSubqueryWithCountStarAndDateTrunc {default} failing
**Build Scans:**
- [elasticsearch-periodic #11495 / release-tests](https://gradle-enterprise.elastic.co/s/i6q74unarhjxo)
- [elasticsearch-pull-request #105982 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/mw6c332poi7su)
- [elasticsearch-pull-request #105979 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/ffzzhozdnvu4c)
- [elasticsearch-pull-request #105968 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/hfwjgsrhbltnk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.rules.physical.local.SubstituteRoundToTests.testSubqueryWithCountStarAndDateTrunc {default}" -Dtests.seed=CA1572EF7FE8197A -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=en-MW -Dtests.timezone=US/Aleutian -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.rules.physical.local.SubstituteRoundToTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSubqueryWithCountStarAndDateTrunc%20%7Bdefault%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.parser.ParsingException: line 1:12: no viable alternative at input '('
```

**Issue Reasons:**
- [main] 3 consecutive failures in step checkpart3_release-tests
- [main] 4 failures in test testSubqueryWithCountStarAndDateTrunc {default} (12.1% fail rate in 33 executions)
- [main] 3 failures in step checkpart3_release-tests (100.0% fail rate in 3 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (16.7% fail rate in 18 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by GalLalouche**
Add missing capability to test added in #138023.
Resolves: #138601.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToTests.java [hunk 1]
```diff
@@ -859,6 +860,7 @@ public void testForkWithStatsCountStarDateTrunc() {
     }
 
     public void testSubqueryWithCountStarAndDateTrunc() {
+        assumeTrue("requires metrics command", EsqlCapabilities.Cap.SUBQUERY_IN_FROM_COMMAND.isEnabled());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToTests.java]: Was that meant to say "requires subqueries" or so? There's no metrics command here.

**Review by alex-spies — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToTests.java (hunk 1 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToTests.java]: Ah yes, bad copy paste 😅
