### PR TITLE
Sort the values of a legacy histogram during downsampling

### LINKED ISSUE #139382: [CI] DownsampleIT testAggregateMethod failing
**Build Scans:**
- [elasticsearch-intake #32242 / part2](https://gradle-enterprise.elastic.co/s/w672exmkwmrs4)
- [elasticsearch-pull-request #109257 / part-2](https://gradle-enterprise.elastic.co/s/fpgm2naysjtl2)
- [elasticsearch-pull-request #108346 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/dhq4sjszarpzq)
- [elasticsearch-pull-request #108275 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/krebgobd45xos)
- [elasticsearch-pull-request #108263 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/yvq7kfzxxn3my)
- [elasticsearch-pull-request #108244 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/wiro5rajtbbjg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:downsample:internalClusterTest" --tests "org.elasticsearch.xpack.downsample.DownsampleIT.testAggregateMethod" -Dtests.seed=DA6CF6555B348C1 -Dtests.locale=agq -Dtests.timezone=America/Thunder_Bay -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.downsample.DownsampleIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAggregateMethod'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchException: downsample task [downsample-downsample-5m-.ds-metrics-foo-2025.12.11-000001-0-5m] failed
```

**Issue Reasons:**
- [main] 6 failures in test testAggregateMethod (0.7% fail rate in 907 executions)
- [main] 4 failures in step checkpart2_release-tests (40.0% fail rate in 10 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 588 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by gmarouli**
When indexing legacy histograms in elasticsearch we require that their values are sorted. 

When downsampling is using the aggregate method, it merges the histograms to a single one and indexes it in the target index. We noticed that some merging algorithms do not guarantee that the centroids will be sorted. 

This PR adds code that sorts the centroids before they are indexed to the target index to avoid indexing failures.

Fixes #139382

### CODE REVIEW

File: x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TDigestHistogramFieldProducer.java [hunk 1]
```diff
@@ -80,13 +80,13 @@ public void reset() {
...
+                List<Centroid> sortedCentroids = new ArrayList<>(tDigestState.centroidCount());
                 while (centroids.hasNext()) {
-                    Centroid centroid = centroids.next();
-                    values.add(centroid.mean());
-                    counts.add(centroid.count());
+                    sortedCentroids.add(centroids.next());
                 }
+                sortedCentroids.sort(Centroid::compareTo);
+                double[] values = sortedCentroids.stream().mapToDouble(Centroid::mean).toArray();
+                long[] counts = sortedCentroids.stream().mapToLong(Centroid::count).toArray();
```
Comment (kkrik-es) [inline x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TDigestHistogramFieldProducer.java]: Nit: consider replacing streams with a loop, iirc streams are inefficient and downsampling is cpu intensive.

**Review by kkrik-es — APPROVED** [review]
