### PR TITLE
Throw exception when trying to write map with null keys

### LINKED ISSUE #14346: XContent Builder doesn't check for null keys in maps. It should raise an exception
There should be a null check in https://github.com/elastic/elasticsearch/blob/148265bd164cd5a614cd020fb480d5974f523d81/core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java#L1237

It should probably raise a unique exception in this event. We encountered this in Logstash with some users running custom plugins.

Jackson also does not perform a null check, leading to a confusing NPE in some Jackson codes.

### PR DESCRIPTION
**Pull request by javanna**
Throw exception when trying to write map with null keys in XContentBuilder, otherwise jackson will break and return a cryptic error message.

Closes #14346

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java [hunk 1]
```diff
@@ -22,30 +22,15 @@
...
-import org.elasticsearch.common.io.FastCharArrayWriter;
 import org.elasticsearch.common.io.PathUtils;
 import org.elasticsearch.common.io.stream.BytesStreamOutput;
-import org.elasticsearch.common.xcontent.XContentBuilder;
-import org.elasticsearch.common.xcontent.XContentBuilderString;
-import org.elasticsearch.common.xcontent.XContentFactory;
-import org.elasticsearch.common.xcontent.XContentGenerator;
-import org.elasticsearch.common.xcontent.XContentParser;
-import org.elasticsearch.common.xcontent.XContentType;
+import org.elasticsearch.common.xcontent.*;
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java]: can you undo this change given that we will soon ban wildcard imports? #15395

File: core/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java [hunk 2]
```diff
@@ -22,30 +22,15 @@
...
-import java.util.Arrays;
-import java.util.Calendar;
-import java.util.Date;
-import java.util.GregorianCalendar;
-import java.util.HashMap;
-import java.util.List;
-import java.util.Locale;
-import java.util.Map;
-import java.util.TimeZone;
+import java.util.*;
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java]: undo wildcard import?

**Comment by jpountz** [comment]
LGTM

File: core/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java (hunk 1 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/common/xcontent/builder/XContentBuilderTests.java]: ok I had missed all that discussion.

**Comment by andrewvc** [comment]
Thanks @javanna !!!
