### PR TITLE
Datafeed jobs it wait for task cancel

### LINKED ISSUE #120088: [CI] DatafeedJobsIT class failing
**Build Scans:**
- [elasticsearch-periodic #5840 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/fs352qwgvvhwi)
- [elasticsearch-periodic #5840 / openjdk17_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/uvdfdrnjmlu5k)
- [elasticsearch-intake #15678 / part4](https://gradle-enterprise.elastic.co/s/524ijkbq5xbp2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testDatafeedTimingStats_QueryDelayUpdated_TimingStatsNotReset" -Dtests.seed=24632FEF31F2C900 -Dtests.locale=ar-IL -Dtests.timezone=Europe/Warsaw -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.tasks.TaskCancelledException: task cancelled before starting [by user request]
```

**Issue Reasons:**
- [8.x] 3 failures in class org.elasticsearch.xpack.ml.integration.DatafeedJobsIT (2.0% fail rate in 147 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jan-elastic**
closes: #120088 #120102 #120103 #120104 #120120 #120121 #120122 #120152 #120153 #120154 #120160 #120161 #120166 #120167 #120169

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/DatafeedJobsIT.java [hunk 1]
```diff
@@ -85,7 +85,9 @@ public void cleanup() {
         // Race conditions between closing and killing tasks in these tests,
         // sometimes result in lingering persistent tasks (such as "_close"),
         // which cause subsequent tests to fail.
-        client().execute(TransportCancelTasksAction.TYPE, new CancelTasksRequest());
+        CancelTasksRequest cancelTasksRequest = new CancelTasksRequest();
+        cancelTasksRequest.setWaitForCompletion(true);
```
Comment (jan-elastic) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/DatafeedJobsIT.java:89]: Without this waiting, tasks of subsequent tests sometimes get cancelled (race condition).

**Review by davidkyle — APPROVED** [review]
LGTM
