### PR TITLE
HLRC: Fix strict setting exception handling

### LINKED ISSUE #37090: Deprecation warnings break the high-level client in strict mode
When the high-level client uses a low-level client that fails on deprecation warnings, that breaks the high-level client quite badly. The low-level client throws a `ResponseException` which is caught by the high-level client which tries to parse the response body as if it was an error, although it most likely was not. Instead of signaling the deprecation warnings clearly, the high-level client ends up breaking with:

```
   > Throwable #1: ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [PUT], host [http://[::1]:33451], URI [/dev_product/product/test.com%2F48923AQ3?timeout=1m], status line [HTTP/1.1 201 Created]
   > Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
   > ¿f_indexkdev_producte_typegproductc_idqtest.com/48923AQ3h_versionfresultgcreatedg_shards¿etotaljsuccessfulffailedÿg_seq_nom_primary_termÿ]; nested: ResponseException[method [PUT], host [http://[::1]:33451], URI [/dev_product/product/test.com%2F48923AQ3?timeout=1m], status line [HTTP/1.1 201 Created]
   > Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
   > ¿f_indexkdev_producte_typegproductc_idqtest.com/48923AQ3h_versionfresultgcreatedg_shards¿etotaljsuccessfulffailedÿg_seq_nom_primary_termÿ];
   >    at __randomizedtesting.SeedInfo.seed([CE50F89A4C8ADC37:26EE63FC8DB7EE6D]:0)
   >    at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1681)
   >    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1442)
   >    at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1399)
   >    at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1369)
   >    at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:817)
   >    at org.elasticsearch.client.CrudIT.testWeirdId(CrudIT.java:1379)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
   >    Suppressed: ParsingException[Failed to parse object: expecting field with name [error] but found [_index]]
   >            at org.elasticsearch.common.xcontent.XContentParserUtils.ensureFieldName(XContentParserUtils.java:50)
   >            at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:587)
   >            at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169)
   >            at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1701)
   >            at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1677)
   >            ... 41 more
   > Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:33451], URI [/dev_product/product/test.com%2F48923AQ3?timeout=1m], status line [HTTP/1.1 201 Created]
   > Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
   > ¿f_indexkdev_producte_typegproductc_idqtest.com/48923AQ3h_versionfresultgcreatedg_shards¿etotaljsuccessfulffailedÿg_seq_nom_primary_termÿ
   >    at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:690)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
   >    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1429)
   >    ... 40 more
   > Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:33451], URI [/dev_product/product/test.com%2F48923AQ3?timeout=1m], status line [HTTP/1.1 201 Created]
   > Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
   > ¿f_indexkdev_producte_typegproductc_idqtest.com/48923AQ3h_versionfresultgcreatedg_shards¿etotaljsuccessfulffailedÿg_seq_nom_primary_termÿ
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:304)
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:294)
   >    at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
   >    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
   >    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   >    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   >    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   >    ... 1 more
```

The cause of the failure does contain the deprecation warnings, but it is not so obvious that they did cause the exception to be thrown. The problem here is that a ResponseException gets thrown based on a response that returned OK status code, and no additional exception message is provided to signal what the problem was. The response itself does not necessarily tell the reason of the failure. That same response would not cause any exception with strict deprecation disabled. I believe we should use a different exception for deprecation warnings.

### PR DESCRIPTION
**Pull request by hub-cap**
The LLRC's exception handling for strict mode was previously throwing an
exception the HLRC assumed was an error response. This is not the case
if the result is valid in strict mode, as it will return the proper
response wrapped in an exception with warnings. This commit fixes the
HLRC such that it no longer spews if it encounters a strict LLRC
response.

Closes #37090

### CODE REVIEW

**Comment by hub-cap** [comment]
@elasticmachine please run gradle build tests 1

File: client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java [hunk 1]
```diff
@@ -1671,15 +1671,19 @@ protected final ElasticsearchStatusException parseResponseException(ResponseExce
         Response response = responseException.getResponse();
         HttpEntity entity = response.getEntity();
         ElasticsearchStatusException elasticsearchException;
-        if (entity == null) {
+        RestStatus restStatus = RestStatus.fromCode(response.getStatusLine().getStatusCode());
+
+        if (responseException instanceof WarningFailureException) {
+            elasticsearchException = new ElasticsearchStatusException("Warnings/Deprecations caused response to fail", restStatus,
+                responseException);
```
Comment (javanna) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: I find using ElasticsearchStatusException almost as weird as using ResponseException. That is because such exceptions are meant for error status codes, while warnings can come back with any response.

I would prefer if we could have a separate catch for the warnings case, with a different exception that does not extend `ResponseException`. Maybe we could add a new exception to the low-level client that does not extend ResponseException, and let the high-level client bubble it up as-is? Not sure what I may be missing that prevents us from going down this route...

Comment (javanna) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: you are right Nik, probably we do not even need a catch for the new exception, just let it bubble up.

Comment (hub-cap) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: The only reason I used the existing `ElasticsearchStatusException` was because that is what was thrown before. If you take a look at https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java#L1670, it is the method that sync/async both call when a `ResponseException` is thrown from the LLRC. Im not sure there is a ton of value wrapping either of these in `ElasticsearchStatusException`. I think removing this would be a breaking change tho?

Comment (hub-cap) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: and to @nik9000 point, if we just throw another exception, it works great for sync, but for async it throws the following

```
UncategorizedExecutionException[Failed execution
]; nested: ExecutionException[org.elasticsearch.client.DeprecationException
```

That said, ofc we can make it do whatever we want. Id still lean toward 1) doing nothing different and still throwing a `ElasticsearchStatusException`, or 2) unwrapping both the `ResponseException` and `WarningFailureException` and throwing them w/o the `ElasticsearchStatusException` (breaking?)

Comment (nik9000) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: > UncategorizedExecutionException

We can handle that IIRC. Catch and rethrow pretty much.

I think with a feature this new that is *likely* pretty rare to use we can probably get away with a breaking change here if the result is cleaner.

Comment (hub-cap) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: >  likely pretty rare to use

`strictDeprecationMode` defaults to false, so we are def in agreement that its not likely used. Id be ok with throwing this different, but I think that removing the `ElasticsearchStatusException` wrapped from the `ResponseException` thrown would be a bad breaking change.

Comment (nik9000) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: >  I think that removing the `ElasticsearchStatusException` wrapped from the `ResponseException` thrown would be a bad breaking change.

I think that one has been around much longer, yeah. But i'm just going from memory. We could throw a special deprecation exception instead, right?

Comment (hub-cap) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: yea this is what the code does as is, even with it being child of ResponseException, its just currently wrapped in a `ElasticsearchStatusException` as well.

Comment (hub-cap) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: @javanna Id like your opinion on whether to break the current functionality, which is to always return an `ElasticsearchStatusException` unless its a random exception we dont know about. Ill gladly throw the `WarningFailureException` w/o wrapping it, just want to make sure thats the correct thing to do WRT compatibility. I think @nik9000 says he is ok with it, correct @nik9000 	?

Comment (javanna) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java]: I am fine too with rethrowing WarningFailureException as-is.

**Comment by hub-cap** [comment]
@javanna @nik9000 Now we have a nice throw (see below) from the async code, with one caveat. The async code uses [this from server](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/util/concurrent/FutureUtils.java#L88) which expects any exception to be either an `ElasticsearchException` or a `RuntimeException`. I decided to make `WarningFailureException` extend `RuntimeException` so it would not wrap it here.

```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:9200], URI [/index/type/id?timeout=1m], status line [HTTP/1.1 201 Created]
Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
---
_index: "index"
_type: "type"
_id: "id"
_version: 1
result: "created"
_shards:
  total: 2
  successful: 1
  failed: 0
_seq_no: 0
_primary_term: 1
```

Id love another quick look.

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/1

File: client/rest/src/main/java/org/elasticsearch/client/ResponseException.java [hunk 2]
```diff
@@ -30,7 +30,7 @@
  * Exception thrown when an elasticsearch node responds to a request with a status code that indicates an error.
  * Holds the response that was returned.
  */
-public final class ResponseException extends IOException {
+public class ResponseException extends IOException {
```
Comment (javanna) [inline client/rest/src/main/java/org/elasticsearch/client/ResponseException.java]: I think that these changes to ResponseException are no longer needed?

File: client/rest/src/main/java/org/elasticsearch/client/WarningFailureException.java [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+/**
+ * This exception is used to indicate that one or more {@link Response#getWarnings()} exist
+ * and is typically used when the {@link RestClient} is set to fail by setting
+ * {@link RestClientBuilder#setStrictDeprecationMode(boolean)} to `true`.
+ */
+// This class extends RuntimeException in order to deal with wrapping that is done in FutureUtils on exception.
+// if the exception is not of type ElasticsearchException or RuntimeException it will be wrapped in a UncategorizedExecutionException
+public class WarningFailureException extends RuntimeException {
+
+    private Response response;
```
Comment (javanna) [inline client/rest/src/main/java/org/elasticsearch/client/WarningFailureException.java]: make it final?

**Review by javanna — APPROVED** [review]
LGTM

File: client/rest/src/main/java/org/elasticsearch/client/ResponseException.java (hunk 2 above)
Comment (hub-cap) [reply client/rest/src/main/java/org/elasticsearch/client/ResponseException.java]: doh, good call!

**Comment by romseygeek** [comment]
I think this is causing (non-reproducible) failures in FullClusterRestartIT, specifically here: https://github.com/elastic/elasticsearch/blob/b889221f75048bebbc7084bf3b3f341eac30e34c/qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java#L1057

The test is anticipating a ResponseException, but it will now get a WarningFailureException instead and so won't catch it.
