### PR TITLE
`detect_noop` now understands `null` as a valid value

### LINKED ISSUE #11208: detect_noop doesn't work with null values
The `detect_noop` flag doesn't work if a field contains a `null` value:

    PUT t/t/1
    {
      "foo": "baz",
      "bar": "baz"
    }

This update request always returns the same version:

    POST t/t/1/_update
    {
      "doc": {
        "foo": "baz",
        "bar": "baz"
      },
      "detect_noop": true
    }

While this one always returns a new version:
    
    POST t/t/1/_update
    {
      "doc": {
        "foo": "baz",
        "bar": null
      },
      "detect_noop": true
    }

### PR DESCRIPTION
**Pull request by nik9000**
If the source contrains a null value for a field then detect_noop should
consider setting it to null again to be a noop.

Closes #11208

### CODE REVIEW

File: src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java [hunk 1]
```diff
@@ -260,11 +260,11 @@ public static boolean update(Map<String, Object> source, Map<String, Object> cha
             if (modified) {
                 continue;
             }
-            if (!checkUpdatesAreUnequal || old == null) {
+            if (!checkUpdatesAreUnequal) {
                 modified = true;
                 continue;
             }
-            modified = !old.equals(changesEntry.getValue());
+            modified = old == null ? changesEntry.getValue() != null : !old.equals(changesEntry.getValue());
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java]: maybe this could be simplified to `modified = !java.util.Objects.equal(old, changesEntry.getValue())`?

**Comment by jpountz** [comment]
This looks good to me, I'll merge it tomorrow if nobody else has objections.

File: src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java (hunk 1 above)
Comment (nik9000) [inline src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java]: Yeah. I forget about that one.

**Comment by nik9000** [comment]
Updated based on your comment. I can squash the changes if you want.

**Comment by jpountz** [comment]
That would be great. :-)

**Comment by nik9000** [comment]
Squashed.
