### PR TITLE
Inner hits and ignore unmapped

### LINKED ISSUE #21620: NullPointerException caused by multiple indices search w/ nested, inner_hits
**Elasticsearch version**: 5.0.0, 5.0.1

**Plugins installed**: [Kibana]

**JVM version**: 1.8.0_92

**OS version**: Elastic.co Cloud (5.0.0) / OS X El Capitan (5.0.1)

**Description of the problem including expected versus actual behavior**:

Requesting `nested` query on multiple indices with `inner_hits` and `ignore_unmapped: true` causes a NullPointerException on indices which do not have the desired `nested` property. 

It shows correct `hits.total` while not returning all the matched document(s) in `hits.hits`.

**Steps to reproduce**:

I've successfully reproduced the behavior using two indices while only one of them having the nested property.

```sh
curl -XDELETE localhost:9200/people
curl -XPUT -d '{
  "mappings": {
    "employee": {
      "properties": {
        "companyId": { "type": "string" }
      }
    }
  }
}' localhost:9200/people

curl -XDELETE localhost:9200/things
curl -XPUT -d '{
  "mappings": {
    "product": {
      "properties": {
        "companyId": { "type": "string" },
        "parts": { "type": "nested", "properties": { "companyId": { "type": "string" } } }
      }
    }
  }
}' localhost:9200/things

curl -XPUT -d '{ "companyId": "foo" }' localhost:9200/people/employee/1
curl -XPUT -d '{ "companyId": "foo", "parts": [{ "companyId": "foo" }] }' localhost:9200/things/product/1

sleep 1

# Fails
curl -d '{
  "query": {
    "bool": {
      "should": [
        {
          "nested": {
            "path": "parts",
            "query": { "term": { "parts.companyId": "foo" } },
            "ignore_unmapped": true,
            "inner_hits": {}
          }
        },
        {
          "term": {
            "companyId": "foo"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}' localhost:9200/people,things/_search

# Succeeds
curl -d '{
  "query": {
    "bool": {
      "should": [
        {
          "nested": {
            "path": "parts",
            "query": { "term": { "parts.companyId": "foo" } },
            "ignore_unmapped": true
          }
        },
        {
          "term": {
            "companyId": "foo"
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}' localhost:9200/people,things/_search
```

The failing request responds with the body:

```json
{
  "took": 31,
  "timed_out": false,
  "_shards": {
    "total": 10,
    "successful": 9,
    "failed": 1,
    "failures": [
      {
        "shard": 3,
        "index": "people",
        "node": "LuRj8eynRU-s1Wfvn9VELw",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "hits": {
    "total": 2,
    "max_score": 0.5753642,
    "hits": [
      {
        "_index": "things",
        "_type": "product",
        "_id": "1",
        "_score": 0.5753642,
        "_source": {
          "companyId": "foo",
          "parts": [
            {
              "companyId": "foo"
            }
          ]
        },
        "inner_hits": {
          "parts": {
            "hits": {
              "total": 1,
              "max_score": 0.2876821,
              "hits": [
                {
                  "_nested": {
                    "field": "parts",
                    "offset": 0
                  },
                  "_score": 0.2876821,
                  "_source": {
                    "companyId": "foo"
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}
```

**Provide logs (if relevant)**:

```
[2016-11-17T20:40:33,561][DEBUG][o.e.a.s.TransportSearchAction] [LuRj8ey] [12] Failed to execute fetch phase
org.elasticsearch.transport.RemoteTransportException: [LuRj8ey][127.0.0.1:9300][indices:data/read/search[phase/fetch/id]]
Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.fetch.subphase.InnerHitsContext$NestedInnerHits.topDocs(InnerHitsContext.java:135) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.search.fetch.subphase.InnerHitsFetchSubPhase.hitExecute(InnerHitsFetchSubPhase.java:55) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:161) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:474) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$13(SearchTransportService.java:311) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) [elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

Thanks.

### PR DESCRIPTION
**Pull request by martijnvg**
Don't inline inner hits if the query the inner hits is inlined into can't resolve mappings and ignore_unmapped has been set to true.

Closes #21620

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java [hunk 1]
```diff
@@ -289,6 +301,15 @@ public InnerHitBuilder setName(String name) {
...
     }
 
+    public boolean isIgnoreUnmapped() {
+        return ignoreUnmapped;
+    }
+
+    public InnerHitBuilder setIgnoreUnmapped(boolean ignoreUnmapped) {
+        this.ignoreUnmapped = ignoreUnmapped;
+        return this;
+    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: please add javadocs

**Review by jpountz — APPROVED** [review]
LGTM, please just see the 2 comments about javadocs.

**Review by jpountz — APPROVED** [review]
LGTM
