### PR TITLE
[test] Fix `RetrySearchIntegTests`

### LINKED ISSUE #118374: [CI] RetrySearchIntegTests testSearcherId failing
**Build Scans:**
- [elasticsearch-intake #14193 / part2](https://gradle-enterprise.elastic.co/s/inmbga3kbychi)
- [elasticsearch-periodic #5192 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/spmfeqofu4daq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:searchable-snapshots:internalClusterTest" --tests "org.elasticsearch.xpack.searchablesnapshots.RetrySearchIntegTests.testSearcherId" -Dtests.seed=2D014B35EDD84E1A -Dtests.locale=khq-ML -Dtests.timezone=America/Bahia -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.searchablesnapshots.RetrySearchIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSearcherId),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Index{id='ikwvcefrwf/IeNIPsAERJOJOfGufulU3g/eK5O4Up4T4O23QZSG-2S0A/1/_0.cfe/@0', seqNo=1, primaryTerm=2, version=1, autoGeneratedIdTimestamp=-1}
Expected: <4L>
     but: was <2L>
```

**Issue Reasons:**
- [main] 2 failures in test testSearcherId (0.2% fail rate in 967 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120442: [CI] RetrySearchIntegTests testRetryPointInTime failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5915 / ubuntu-2004-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/7k6jwnarutqw6)
- [elasticsearch-periodic-platform-support #5885 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/szep5mtxj4llo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:searchable-snapshots:internalClusterTest" --tests "org.elasticsearch.xpack.searchablesnapshots.RetrySearchIntegTests.testRetryPointInTime" -Dtests.seed=C580C4B98B7DFD07 -Dtests.locale=pl-Latn-PL -Dtests.timezone=Asia/Atyrau -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.searchablesnapshots.RetrySearchIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRetryPointInTime),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Index{id='qvlkceyjrv/Zx-K-8ubTEK3xYdPBJwMvw/CoEEI9wxTsChmDvD2kDyxg/0/_4.cfe/@0', seqNo=3, primaryTerm=1, version=2, autoGeneratedIdTimestamp=-1}
Expected: <3L>
     but: was <1L>
```

**Issue Reasons:**
- [8.x] 2 failures in test testRetryPointInTime (1.0% fail rate in 201 executions)
- [8.x] 2 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by arteam**
Don't simultaneously restart multiple nodes in a cluster. It causes data races when multiple primaries are trying to mark the `[[.snapshot-blob-cache][0]]` shard as stale.

```
org.elasticsearch.cluster.action.shard.ShardStateAction$NoLongerPrimaryShardException: primary term [2] did not match current primary term [4]
	at org.elasticsearch.cluster.action.shard.ShardStateAction$ShardFailedClusterStateTaskExecutor.execute(ShardStateAction.java:355) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1075) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1038) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:245) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1691) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:452) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1688) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1283) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:452) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1262) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-8.18.0-SNAPSHOT.jar:8.18.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

Resolve #118374
Resolve #120442

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/RetrySearchIntegTests.java [hunk 1]
```diff
@@ -87,10 +87,8 @@ public void testSearcherId() throws Exception {
             }
         }
 
-        for (String allocatedNode : allocatedNodes) {
-            if (randomBoolean()) {
-                internalCluster().restartNode(allocatedNode);
-            }
+        if (randomBoolean()) {
+            internalCluster().restartNode(randomFrom(allocatedNodes));
         }
```
Comment (ywangd) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/RetrySearchIntegTests.java:92]: Can we retain the possibility for restarting all nodes by adding ensureGreen after each restart?

**Review by ywangd — COMMENTED** [review]
I wonder whether it is worthwhile to fix the assertion in `assertConsistentHistoryBetweenTranslogAndLuceneIndex` to account for this edge case? Restarting nodes is something we do quite a bit in tests. So it seems reasonable to account for that. Otherwise it could fail for some other tests in future?

I am no expert on translog and lucene operations. Feel free to let me know whether the suggestion makes any sense. The change does make sense as a localised fix (to the best of my knowledge). But I am curious whether it could be more universal.

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/RetrySearchIntegTests.java (hunk 1 above)
Comment (arteam) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/RetrySearchIntegTests.java:92]: Yeah, that was one options that I considered. I'm not sure whether it matters for the test if restart one or multiple nodes, since we just check that the search id and PIT are retained during node restarts, but I will update it to keep the original semantics of the test

Comment (arteam) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/RetrySearchIntegTests.java]: ad8369bbd48e818e3d782e81170122b381efa9e2

**Comment by arteam** [comment]
@ywangd I'm not sure why can fix `assertConsistentHistoryBetweenTranslogAndLuceneIndex` because the failure is essentialy a missed failing operation on a replica shard due to a race. I think we just have to ensure that the we restart nodes step by step.

**Review by ywangd — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
> I'm not sure we can fix assertConsistentHistoryBetweenTranslogAndLuceneIndex because the failure is essentialy a missed failing operation on a replica shard due to a race. I think we just have to ensure that the we restart nodes step by step.

Thanks Artem. I am good with the proposed fix. What I suggested earlier may not be viable. I am no expert on translog. Bottom line is that we can evaluate it again if similar issue happens elsewhere (if at all).
