### PR TITLE
Fix flakiness in testRetryPolicy

### LINKED ISSUE #70594: [CI] ILMDocumentationIT testRetryPolicy failing
This has failed a handful of times already today.

**Build scan**:
https://gradle-enterprise.elastic.co/s/ne2ro3wktkcue/tests/:client:rest-high-level:integTest/org.elasticsearch.client.documentation.ILMDocumentationIT/testRetryPolicy

**Reproduction line:**
`REPRODUCE WITH: ./gradlew ':client:rest-high-level:integTest' --tests "org.elasticsearch.client.documentation.ILMDocumentationIT.testRetryPolicy" -Dtests.seed=6A1F346303BDA41A -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=Asia/Yerevan -Druntime.java=8`

**Applicable branches:**
master, 7.x

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.documentation.ILMDocumentationIT&tests.test=testRetryPolicy

**Failure excerpt:**
```
  org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=cannot retry an action for an index [my_index] that has not encountered an error when running a Lifecycle Policy]

  at __randomizedtesting.SeedInfo.seed([6A1F346303BDA41A:1BDA29CE55151F48]:0)
  at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
  at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
  at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
  at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
  at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
  at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1606)
  at org.elasticsearch.client.IndexLifecycleClient.retryLifecyclePolicy(IndexLifecycleClient.java:336)
  at org.elasticsearch.client.documentation.ILMDocumentationIT.testRetryPolicy(ILMDocumentationIT.java:635)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by andreidan**
Retrying a retryable step when the ILM loop is configured to `1s` (as we do in 
the integration tests) is a recipe for flakiness - as ILM keeps moving a failed
step from `ERROR` back into the failed step for it to be retried, and the retry
step API fails if executed when ILM is not in the `ERROR` step.

This makes the documentation integration test more lenient.

Fixes #70594

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java [hunk 1]
```diff
@@ -631,16 +631,22 @@ public void testRetryPolicy() throws Exception {
...
+            // tag::ilm-retry-lifecycle-policy-response
+            boolean acknowledged = response.isAcknowledged(); // <1>
+            // end::ilm-retry-lifecycle-policy-response
 
-        assertTrue(acknowledged);
+            assertTrue(acknowledged);
+        } catch (ElasticsearchException e) {
+            // the retry API might fail as the shrink action steps are retryable (so if the retry API reaches ES when ILM is retrying the
+            // failed `shrink` step, the retry API will fail)
+            // as this code is more for illustrative purposes in the docs we'll allow it
```
Comment (dakrone) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java:648]: Is there any way we can check the message or something else here? I don't want us to accidentally miss a bug in `retryLifecyclePolicy` that is unrelated because we swallowed the exception

Comment (andreidan) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java]: Great point. Pushed a fix to assert the message. Thanks Lee

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM!
