### PR TITLE
Correctly list blobs in Azure Storage to prevent snapshot corruption and do not unnecessarily duplicate Lucene segments in Azure Storage

### LINKED ISSUE #51: Restore snapshot leaves shards unassigned and with CorruptIndexException
I opened an issue (https://github.com/elasticsearch/elasticsearch/issues/9275) but maybe it's more a problem on this plugin side. I'm using Azure blob storage for the snapshots without any special configuration.
When restoring a snapshot, shards are left unassigned and the logs have CorruptIndexException as mentioned in the referenced issue.

### LINKED ISSUE #99: AzureStorageServiceImpl does not retrieve blob metadata from Azure Storage
The `AzureStorageServiceImpl.listBlobsByPrefix` method does not fetch the blob attributes from Azure Storage. This is known behavior in the `CloudBlobContainer.getBlockBlobReference` in the Azure API. This leads to blob metadata returned by the `AzureStorageServiceImpl.listBlobsByPrefix` to report the blob as having length zero. This causes an issue in the snapshot layer in the Elasticsearch; namely, blob length is one piece of metadata (of several) used to compare if Lucene segments that the snapshot layer is about to write to already exist in the storage layer.

This issue will not cause snapshot corruption, but it does lead to an unnecessary use of space in the storage layer.

### PR DESCRIPTION
**Pull request by jasontedor**
This commit addresses an issue that was leading to snapshot corruption for snapshots stored as blobs in Azure Storage.

The underlying issue is that in cases when multiple snapshots of an index were taken and persisted into Azure Storage, snapshots subsequent to the first would repeatedly overwrite the snapshot files. This issue does render useless all snapshots except the final snapshot.

The root cause of this is due to String concatenation involving null. In particular, to list all of the blobs in a snapshot directory in Azure the code would use the method `listBlobsByPrefix` where the prefix is `null`. In the `listBlobsByPrefix` method, the path `keyPath + prefix` is constructed. However, per [5.1.11](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.11), [5.4](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.4) and [15.18.1](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.18.1) of the Java Language Specification, the reference null is first converted to the string `"null"` before performing the concatenation. This leads to no blobs being returned and therefore the snapshot mechanism would operate as if it were writing the first snapshot of the index. The fix is simply to check if prefix is null and handle the concatenation accordingly.

Upon fixing this issue so that subsequent snapshots would no longer overwrite earlier snapshots, it was discovered that the snapshot metadata returned by the `listBlobsByPrefix` method was not sufficient for the snapshot layer to detect whether or not the Lucene segments had already been copied to the Azure storage layer in an earlier snapshot. This led the snapshot layer to unnecessarily duplicate these Lucene segments in Azure Storage.

The root cause of this is due to known behavior in the `CloudBlobContainer.getBlockBlobReference` method in the Azure API. Namely, this method does not fetch blob attributes from Azure. As such, the lengths of all the blobs appeared to the snapshot layer to be of length zero and therefore they would compare as not equal to any new blobs that the snapshot layer is going to persist. To remediate this, the method `CloudBlockBlob.downloadAttributes` must be invoked. This will fetch the attributes from Azure Storage so that a proper comparison of the blobs can be performed.

Closes elastic/elasticsearch-cloud-azure#51, closes elastic/elasticsearch-cloud-azure#99

### CODE REVIEW

File: plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 1]
```diff
@@ -175,12 +175,14 @@ public OutputStream getOutputStream(String container, String blob) throws URISyn
...
-            for (ListBlobItem blobItem : blob_container.listBlobs(keyPath + prefix)) {
+            for (ListBlobItem blobItem : blob_container.listBlobs(keyPath + (prefix == null ? "" : prefix))) {
                 URI uri = blobItem.getUri();
                 logger.trace("blob url [{}]", uri);
-                String blobpath = uri.getPath().substring(container.length() + 1);
-                BlobProperties properties = blob_container.getBlockBlobReference(blobpath).getProperties();
-                String name = blobpath.substring(keyPath.length() + 1);
+                String blobPath = uri.getPath().substring(1 + container.length() + 1);
+                CloudBlockBlob blob = blob_container.getBlockBlobReference(blobPath);
+                blob.downloadAttributes();
```
Comment (tlrx) [inline plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: Can you add of short comment here? Something like `// force the Azure client to download the attributes (and length) of the blob`

File: plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 2]
```diff
@@ -175,12 +175,14 @@ public OutputStream getOutputStream(String container, String blob) throws URISyn
...
         CloudBlobContainer blob_container = client.getContainerReference(container);
         if (blob_container.exists()) {
-            for (ListBlobItem blobItem : blob_container.listBlobs(keyPath + prefix)) {
+            for (ListBlobItem blobItem : blob_container.listBlobs(keyPath + (prefix == null ? "" : prefix))) {
                 URI uri = blobItem.getUri();
                 logger.trace("blob url [{}]", uri);
-                String blobpath = uri.getPath().substring(container.length() + 1);
-                BlobProperties properties = blob_container.getBlockBlobReference(blobpath).getProperties();
-                String name = blobpath.substring(keyPath.length() + 1);
+                String blobPath = uri.getPath().substring(1 + container.length() + 1);
```
Comment (tlrx) [inline plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: We now have +2 instead of +1. Is it intentional? If so, can you add a comment to understand why `1 + .. + 1` is needed?

File: plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 3]
```diff
@@ -175,12 +175,14 @@ public OutputStream getOutputStream(String container, String blob) throws URISyn
 
         CloudBlobContainer blob_container = client.getContainerReference(container);
```
Comment (tlrx) [inline plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: Since we are modifying this code, can we change `blob_container` -> `blobContainer`?

File: plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java (hunk 2 above)
Comment (jasontedor) [inline plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: Yes, it's intentional. The `uri.getPath()` returns something that looks like `/container/keyPath`. Taking `uri.getPath().substring(container.length() + 1)` gives `/keyPath` and that leading `/` confuses Azure because it ultimately gets appended to the storage URI. An extra `1 + ` removes that additional `/` so that the correct URI is constructed.

I will add a comment. Thanks @tlrx!

File: plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java (hunk 1 above)
Comment (jasontedor) [inline plugins/cloud-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: Yes, I will do that. Thanks @tlrx!

**Comment by tlrx** [comment]
I left some minor comments and great work @jasontedor! 

I'm wondering if we can add a test that creates multiple snapshots and checks that we don't snapshot everything for each snapshots (using the Snapshot status API and check the number of files / total size of each snapshot)?

**Comment by jasontedor** [comment]
Thanks @tlrx for the quick review! I pushed two commits to address your comments.
