### PR TITLE
ES|QL: better validation for GROK patterns

### LINKED ISSUE #110533: ESQL: GROK with multiple attributes of different type gives index out of bounds
```
FROM employees
| KEEP last_name
| WHERE last_name == "Facello"
| EVAL name = concat("1 ", last_name)
| GROK name "%{NUMBER:foo} %{WORD:foo}"
;
```

leads to

```

Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at __randomizedtesting.SeedInfo.seed([731D50ED4AE74575:FB496F37E41B288D]:0)
	at org.elasticsearch.xpack.esql.CsvTests.grok.ShadowingInternal(grok.csv-spec:65)
	at org.elasticsearch.xpack.esql.evaluator.command.GrokEvaluatorExtracter.<init>(GrokEvaluatorExtracter.java:65)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.lambda$planGrok$5(LocalExecutionPlanner.java:455)
	at org.elasticsearch.compute.operator.ColumnExtractOperator$Factory.get(ColumnExtractOperator.java:30)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner$PhysicalOperation.lambda$operators$0(LocalExecutionPlanner.java:690)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner$PhysicalOperation.operators(LocalExecutionPlanner.java:690)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner$DriverSupplier.apply(LocalExecutionPlanner.java:787)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner$LocalExecutionPlan.createDrivers(LocalExecutionPlanner.java:844)
	at org.elasticsearch.xpack.esql.CsvTests.executePlan(CsvTests.java:438)
...
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Validate GROK patterns that contain multiple attributes with the same name and different types, eg. 

```
%{NUMBER:foo} %{WORD:foo}
```

Fixes https://github.com/elastic/elasticsearch/issues/110533

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java [hunk 1]
```diff
@@ -147,11 +147,27 @@ public PlanFactory visitEvalCommand(EsqlBaseParser.EvalCommandContext ctx) {
...
 
+    private void validateGrokPattern(Grok.Parser grokParser, String pattern) {
+        Map<String, DataType> definedAttributes = new HashMap<>();
+        for (Attribute field : grokParser.extractedFields()) {
+            String name = field.name();
+            DataType type = field.dataType();
+            DataType prev = definedAttributes.put(name, type);
+            if (prev != null) {
+                throw new ParsingException(
+                    "Invalid GROK pattern [" + pattern + "]: the attribute [" + name + "] is defined multiple times with different types"
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:165]: [A quick skim over comment] With EVAL we allow overwriting a field, irrespective of its type. Same with GROK(), when overriding input (i.e. already existing) fields. 
Wouldn't it make sense to allow this overriding, generally (i.e. even if different types)? Or, otherwise, reject overriding even if of the same type?

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:165]: Unfortunately the problem is more subtle here: for the calculation we rely on `org.elasticsearch.grok.Grok`, that is an ingest component, so we have limited control on how we parse the patterns and how we collect results.

Today we supports patterns like `%{WORD:foo} %{WORD:foo}` (attribute defined twice, same type) because GROK just returns a multi-value. Changing this behavior (ie. rejecting this pattern entirely or returning only one value) would be a breaking change. 

We could try to support some kind of override in case of different types, but I'm not sure it would be coherent with the behavior described above.

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:165]: This PR could be a temporary fix (a `ValidationException` is definitely better than an `IndexOutOfBoundException`) while we discuss and maybe implement a working alternative.

Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:165]: Nit/bikeshed: The error message could name the two types we encountered.

**Review by alex-spies — APPROVED** [review]
LGTM. I prefer adding this validation now; if we end up considering to change GROKs behavior by e.g. defaulting to the rightmost attribute in case of name collisions, we can still provide better error messages for now to be helpful to the user.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java [hunk 2]
```diff
@@ -147,11 +147,27 @@ public PlanFactory visitEvalCommand(EsqlBaseParser.EvalCommandContext ctx) {
...
     }
 
+    private void validateGrokPattern(Grok.Parser grokParser, String pattern) {
+        Map<String, DataType> definedAttributes = new HashMap<>();
+        for (Attribute field : grokParser.extractedFields()) {
+            String name = field.name();
+            DataType type = field.dataType();
+            DataType prev = definedAttributes.put(name, type);
+            if (prev != null) {
+                throw new ParsingException(
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:164]: Use an enhanced version of the constructor where the source is provided as well. As it is now, the error message looks like this `line -1:0: Invalid GROK pattern [%{NUMBER:foo} %{WORD:foo}]: the attribute [foo] is defined multiple times with different types` with an emphasis on `line -1:0` which is not really user friendly.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 3]
```diff
@@ -758,15 +758,26 @@ public void testDissectPattern() {
...
+
+        cmd = processingCommand("grok a \"%{WORD:foo} %{WORD:foo}\"");
+        assertEquals(Grok.class, cmd.getClass());
+        grok = (Grok) cmd;
+        assertEquals("%{WORD:foo} %{WORD:foo}", grok.parser().pattern());
+        assertEquals(List.of(referenceAttribute("foo", KEYWORD)), grok.extractedFields());
+
+        expectError(
+            "row a = \"foo bar\" | GROK a \"%{NUMBER:foo} %{WORD:foo}\"",
+            "Invalid GROK pattern [%{NUMBER:foo} %{WORD:foo}]: the attribute [foo] is defined multiple times with different types"
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:779]: Test the full error message here to also validate the `line:column` numbers.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java [hunk 4]
```diff
@@ -147,11 +147,27 @@ public PlanFactory visitEvalCommand(EsqlBaseParser.EvalCommandContext ctx) {
     public PlanFactory visitGrokCommand(EsqlBaseParser.GrokCommandContext ctx) {
         return p -> {
             String pattern = visitString(ctx.string()).fold().toString();
-            Grok result = new Grok(source(ctx), p, expression(ctx.primaryExpression()), Grok.pattern(source(ctx), pattern));
+            Grok.Parser grokParser = Grok.pattern(source(ctx), pattern);
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:150]: Define `source(ctx)` as variable and reuse it.

**Review by astefan — APPROVED** [review]
LGTM after the raised items are addressed.

Left three comments.
Also, please test the exact query that showed the error in the first place.

**Comment by luigidellaquila** [comment]
Ah, a conflict on the Capabilities for sure. I'll have to manually backport it
