### PR TITLE
Fix toString of class SnapshotStatus (#26851)

### LINKED ISSUE #26851: SnapshotStatus.toString() always returns a error message
The method `toString` of class `SnapshotStatus` always got a error message:
`{ "error" : "Can not start an object, expecting field name (context: Object)"}`. 

The `toString`:

https://github.com/elastic/elasticsearch/blob/dbea83a1d017bd85ba4e9cdf7e910ce5be7b0610/core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java#L162

The `startObject()` of `builder` called twice because it will be called in the start of `toXContent()`.

### PR DESCRIPTION
**Pull request by liketic**
Fixes #26851

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java [hunk 1]
```diff
@@ -162,9 +161,7 @@ public static SnapshotStatus readSnapshotStatus(StreamInput in) throws IOExcepti
     public String toString() {
         try {
             XContentBuilder builder = XContentFactory.jsonBuilder().prettyPrint();
-            builder.startObject();
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: There's utility method that could replace all of this in `org.elasticsearch.common.String`. I think `toString(ToXContent toXContent, boolean pretty, boolean human)` can replace all of this methods code.

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @liketic, I left a short suggestion about making the toString() method shorter.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java (hunk 1 above)
Comment (liketic) [reply core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: Thanks for reviewing this.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java [hunk 2]
```diff
@@ -160,15 +159,7 @@ public static SnapshotStatus readSnapshotStatus(StreamInput in) throws IOExcepti
...
-        try {
-            XContentBuilder builder = XContentFactory.jsonBuilder().prettyPrint();
-            builder.startObject();
-            toXContent(builder, EMPTY_PARAMS);
-            builder.endObject();
-            return builder.string();
-        } catch (IOException e) {
-            return "{ \"error\" : \"" + e.getMessage() + "\"}";
-        }
+        return Strings.toString(this, true, true);
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: Since the original toString() method only used the `pretty` printing option but not the 'human` option, could we keep that the same?

Comment (liketic) [reply core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: Make sense. Thanks.

**Review by cbuescher — APPROVED** [review]
@liketic looks good to me now, thanks again for picking this up. I will merge this to master and the 6.1 branch.

**Comment by cbuescher** [comment]
@elasticmachine test this please

File: core/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatusTests.java [hunk 3]
```diff
@@ -0,0 +1,89 @@
+package org.elasticsearch.action.admin.cluster.snapshots.status;
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatusTests.java]: The CI tests just complained about missing license headers for this new test file. Can you please copy over the header comments from any existing test to this one? Sorry I missed this during review.

**Comment by cbuescher** [comment]
@liketic sorry I missed it before, can you add our standard license headers to the new test file?

**Comment by cbuescher** [comment]
@elasticmachine  Test this please

**Review by cbuescher — CHANGES_REQUESTED** [review]
The new SnapshotStatusTests is still failing. Depending on which shardStage is picked, the output is different. Could you update the test to fix this? I think the randomization of the shardStage is a thing we want to keep.

**Comment by cbuescher** [comment]
@liketic thanks, I'll start another CI run
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by liketic** [comment]
No idea about why the testing is still failed... I can get success in my laptop but only sometimes...

**Comment by cbuescher** [comment]
@liketic those failures look unrelated, however I'd like to have a clean build before merging this. Sometimes its the commit you branched from, would you mind rebasing this PR or merging in master again so we can see if we get a clean CI run?

**Comment by liketic** [comment]
@cbuescher Rebase done.

**Comment by cbuescher** [comment]
@elasticmachine lets test this again, shall we?

**Review by cbuescher — APPROVED** [review]

**Comment by cbuescher** [comment]
@liketic finally a good test run, I merged this to master and 6.1. Thanks for this PR.

**Comment by liketic** [comment]
@cbuescher finally, we got it... Thanks for your patient.
