### PR TITLE
Snapshot : azure module - accelerate the listing of files (used in delete snapshot)

### LINKED ISSUE #25424: Issue on deleting ES Snapshot with Azure plugin
Hi,

I have issues to delete snapshot on a repository managed with Azure plugin : 
* Our configuration is the following : 
   = ElasticSearch version : 5.4.1 (via https://artifacts.elastic.co/packages/5.x/yum)
   = Plugins installed : x-pack, repository-azure
   = JVM version : Openjdk 1.8.0.121 (RPM : java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64)
   = OS Version : Centos 7.3 / Linux xxx 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   =  Point to note : We use the Azure plugin but we are not in the Azure infrastructure

**Description of the problem including expected versus actual behavior**:

Expected behaviour : 
* Possibility to delete more than one snapshot from Azure repository 
Actual Behaviour: 
* The DELETE Request never ends up
* When you ask the status of the Snapshot, you take a 404 snapshot_missing_exception
* When you try to delete an other snapshot, you get a 503 concurrent_snapshot_execution_exception

**Steps to reproduce**:

I always achieve to reproduce it on my test environnement (happens first on production) : 
1)  curl -v -X DELETE http://X.Y.Z.T:9200/_snapshot/testbackups-azure/snapshot_XXX . The request hangs up
2) In the same time, on the second terminal , curl -v http://X.Y.Z.T:9200/_snapshot/testbackups-azure/snapshot_XXX. You get 
{"error":{"root_cause":[{"type":"snapshot_missing_exception","reason":"[testbackups-azure:snapshot_XXX] is missing"}],"type":"snapshot_missing_exception","reason":"[testbackups-azure:snapshot_XXX] is missing"},"status":404}
3) On the second terminal, ask for curl -v -X DELETE http://X.Y.Z.T:9200/_snapshot/testbackups-azure/snapshot_YYY (a different Snapshot this time).
{"error":{"root_cause":[{"type":"concurrent_snapshot_execution_exception","reason":"[testbackups-azure:snapshot_YYY/ZZZ] cannot delete - another snapshot is currently being deleted"}],"type":"concurrent_snapshot_execution_exception","reason":"[testbackups-azure:snapshot_YYY/ZZZ] cannot delete - another snapshot is currently being deleted"},"status":503}

When I do a rolling restart of the cluster ES, it come back to normal and the first snapshot (XXX in our case) is no more present and it is possible to delete an snapshot.

### PR DESCRIPTION
**Pull request by etiennecarriere**
Close #25424 . 

Current behaviour of the Listing of a container in azure plugin : 
* List all the blob
* For each blob, request the medata of blob
=> it is ineffective as we have N+1 requests for N blobs 

Proposed behaviour
* List all blob and retrieving the metadata in the same request

### CODE REVIEW

**Comment by etiennecarriere** [comment]
@karmi , My company signed a CLA ("A company wanting its employees to contribute") with my Github account in the annex ". Do I have to sign an other one (" An individual contributing under an existing company contributor agreement") ?

File: plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 1]
```diff
@@ -280,33 +279,27 @@ public OutputStream getOutputStream(String account, LocationMode mode, String co
 
         logger.debug("listing container [{}], keyPath [{}], prefix [{}]", container, keyPath, prefix);
         MapBuilder<String, BlobMetaData> blobsBuilder = MapBuilder.newMapBuilder();
+        EnumSet<BlobListingDetails> enumBlobListingDetails = EnumSet.of(BlobListingDetails.METADATA);
         CloudBlobClient client = this.getSelectedClient(account, mode);
         CloudBlobContainer blobContainer = client.getContainerReference(container);
-
-        SocketAccess.doPrivilegedVoidException(() -> {
```
Comment (rjernst) [inline plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: This doPrivileged needs to stay.

File: plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 2]
```diff
@@ -280,33 +279,27 @@ public OutputStream getOutputStream(String account, LocationMode mode, String co
...
-                    blobsBuilder.put(name, new PlainBlobMetaData(name, properties.getLength()));
+        if (blobContainer.exists()) {
+            for (ListBlobItem blobItem : blobContainer.listBlobs(keyPath + (prefix == null ? "" : prefix),false,enumBlobListingDetails,null,null)) {
+                URI uri = blobItem.getUri();
+                logger.trace("blob url [{}]", uri);
+
+                // uri.getPath is of the form /container/keyPath.* and we want to strip off the /container/
+                // this requires 1 + container.length() + 1, with each 1 corresponding to one of the /
+                String blobPath = uri.getPath().substring(1 + container.length() + 1);
+                if (!(blobItem instanceof CloudBlockBlob)){
```
Comment (rjernst) [inline plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: I don't think we need this check, it should be an error if we don't get back CloudBlockBlob (which is what we expect for all keys here). I think it can be a hard assert.

File: plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 3]
```diff
@@ -280,33 +279,27 @@ public OutputStream getOutputStream(String account, LocationMode mode, String co
...
-                    // fetch the blob attributes from Azure (getBlockBlobReference does not do this)
-                    // this is needed to retrieve the blob length (among other metadata) from Azure Storage
-                    blob.downloadAttributes();
-
-                    BlobProperties properties = blob.getProperties();
-                    String name = blobPath.substring(keyPath.length());
-                    logger.trace("blob url [{}], name [{}], size [{}]", uri, name, properties.getLength());
-                    blobsBuilder.put(name, new PlainBlobMetaData(name, properties.getLength()));
+        if (blobContainer.exists()) {
+            for (ListBlobItem blobItem : blobContainer.listBlobs(keyPath + (prefix == null ? "" : prefix),false,enumBlobListingDetails,null,null)) {
```
Comment (rjernst) [inline plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: nit: please use spaces after the commas

Also, check the length of this line, it looks close to the 140 char limit

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java [hunk 4]
```diff
@@ -70,20 +70,16 @@ private String getRepositoryPath() {
...
 
     public static String getContainerName() {
-        String testName = "snapshot-itest-".concat(RandomizedTest.getContext().getRunnerSeedAsString().toLowerCase(Locale.ROOT));
+        /* Have a different name per test so that there is no possible race condition. As the long can be negative,
+         * there mustn't be an hyphen between the 2 concat numbers
+         * (can't have 2 consecutives hypens on Azure containers)
+         */
+        String testName = "snapshot-itest-"
+            .concat(RandomizedTest.getContext().getRunnerSeedAsString().toLowerCase(Locale.ROOT))
+            .concat(new Long(RandomizedTest.getContext().getRandom().nextLong()).toString());
```
Comment (rjernst) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java]: This can simply be `randomLong()`. However, I don't think this will work because  the cleanup in `wipeAzureRepositories()` would then not know about the generated name. If these need to be unique, then this method needs to stash the generated name so that the repository can be cleaned up after the test.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java [hunk 5]
```diff
@@ -70,20 +70,16 @@ private String getRepositoryPath() {
...
         return testName.contains(" ") ? Strings.split(testName, " ")[0] : testName;
     }
 
-    @Override
-    public Settings indexSettings() {
```
Comment (rjernst) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java]: I don't think these should be removed, but if they should, then please explain why.

**Review by rjernst — COMMENTED** [review]
Thanks for the PR! I left some comments. In general it looks like the idea is to call a different listBlobs impl which can return all the metadata of the keys along with the key itself. Can you please update the description to explain that?

**Comment by rjernst** [comment]
@etiennecarriere Regarding the CLA, I believe you need to associate your github profile with the company signed CLA. If you follow the link to the CLA, I think that is the second option `An individual contributing under an existing company contributor agreement`.

File: plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java (hunk 2 above)
Comment (Etienne-Carriere) [inline plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: I agree it is the assumption on the previous version of code but I prefer to be defensive : if the azure storage container has been modified by an outside component, it could have other type of blob (Append/Page) so I propose ignoring it and put a warning.

Comment (abeyad) [inline plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: I am +1 on what @rjernst said - silently ignoring is not the way to go here, very few read log messages, its more important to fail hard if something changed that alters our underlying assumptions of what object type is returned there.

**Comment by karmi** [comment]
Hi @etiennecarriere, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/25710.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by Etienne-Carriere** [comment]
@rjernst, @abeyad , I applied your comments for the code on the "main" class so the gradle check / test works. 
On the tests, I had to modify 2 weeks ago in order to have functional integration tests. Unfortunately, I don't achieve to reproduce them today even on master without my modifications.

**Comment by Etienne-Carriere** [comment]
@karmi, is the issue with my individual CLA or my enterprise CLA ? Is it possible to contact you in private (at your e-mail) to understand the issue ?

**Comment by etiennecarriere** [comment]
@rjernst, @abeyad , I applied your comments for the code on the "main" class so the gradle check / test works.
On the tests, I had to modify 2 weeks ago in order to have functional integration tests. Unfortunately, I don't achieve to reproduce them today even on master without my modifications.

**Comment by etiennecarriere** [comment]
@karmi, my fault, I commited the corrections with my personal account and not my professional account.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java (hunk 5 above)
Comment (etiennecarriere) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java]: After reflexion, ok to keep it but we have to add the MockFSIndexStore.TestPlugin so that the configuration variable are known. If we don't have, we have random error as MockFSIndexStore.TestPlugin is added randomly in ESIntegTestCase superclass

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java (hunk 4 above)
Comment (etiennecarriere) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java]: you are right : I rollback as it will not work in wipeAzureRepository .

**Comment by karmi** [comment]
@Etienne-Carriere, the check is now green, thanks for fixing the e-mail problem!

File: plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java [hunk 6]
```diff
@@ -280,33 +279,26 @@ public OutputStream getOutputStream(String account, LocationMode mode, String co
...
         logger.debug("listing container [{}], keyPath [{}], prefix [{}]", container, keyPath, prefix);
         MapBuilder<String, BlobMetaData> blobsBuilder = MapBuilder.newMapBuilder();
+        EnumSet<BlobListingDetails> enumBlobListingDetails = EnumSet.of(BlobListingDetails.METADATA);
         CloudBlobClient client = this.getSelectedClient(account, mode);
         CloudBlobContainer blobContainer = client.getContainerReference(container);
-
         SocketAccess.doPrivilegedVoidException(() -> {
             if (blobContainer.exists()) {
-                for (ListBlobItem blobItem : blobContainer.listBlobs(keyPath + (prefix == null ? "" : prefix))) {
+                for (ListBlobItem blobItem : blobContainer.listBlobs(keyPath + (prefix==null ? "" : prefix),false,
```
Comment (rjernst) [inline plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/storage/AzureStorageServiceImpl.java]: nit: please keep the spacing around `==` and between arguments (after `,`)

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java [hunk 7]
```diff
@@ -64,13 +70,24 @@
...
+
     private String getRepositoryPath() {
         String testName = "it-" + getTestName();
         return testName.contains(" ") ? Strings.split(testName, " ")[0] : testName;
     }
 
     public static String getContainerName() {
-        String testName = "snapshot-itest-".concat(RandomizedTest.getContext().getRunnerSeedAsString().toLowerCase(Locale.ROOT));
+        /* Have a different name per test so that there is no possible race condition. As the long can be negative,
+         * there mustn't be an hyphen between the 2 concat numbers
```
Comment (rjernst) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java]: typo: an -> a, concat -> concatenated

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java [hunk 8]
```diff
@@ -64,13 +70,24 @@
...
+         * (can't have 2 consecutives hypens on Azure containers)
```
Comment (rjernst) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreTests.java]: typo: hypens -> hyphens

**Review by rjernst — CHANGES_REQUESTED** [review]
@Etienne-Carriere Thanks for the updates and sorry for the delay in reviewing again. I left a couple more minor comments. If you can address them, I will merge this.

**Comment by etiennecarriere** [comment]
Changes made. For the resolution of the conflicts, I don't know what is the Elasticsearch method : 
* Use the github resolver (as I have done)
* Made a rebase then force push to the branch (I prepared it on my local repo).

**Comment by rjernst** [comment]
@elasticmachine test this please

**Review by rjernst — APPROVED** [review]

**Comment by rjernst** [comment]
Thanks @Etienne-Carriere, I will get this merged once CI completes.

**Comment by rjernst** [comment]
@Etienne-Carriere This branch no longer compiles against master. Can you bring it up to date? I think the ctor for azure impl has been changed.

**Comment by etiennecarriere** [comment]
I change the API call . I made the following tests : 
gradle assemble on the root directory : OK
gradle check on the plugins/repository-azure : OK

but the gradle check the root directory failed on an error that seems not to be linked with this PR.

**Comment by rjernst** [comment]
@elasticmachine please test this

**Comment by etiennecarriere** [comment]
@rjernst , do you need additionnals elements to validate the commit ?

**Review by rjernst — APPROVED** [review]
LGTM. Thanks for your patience @Etienne-Carriere
