### PR TITLE
ESQL: Fix DateDiff flaky test configuration

### LINKED ISSUE #138772: [CI] DateDiffTests class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11475 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/diok7tkagftlw)
- [elasticsearch-pull-request #106616 / part-3](https://gradle-enterprise.elastic.co/s/7lyt7237zkiyw)
- [elasticsearch-pull-request #106616 / part-3](https://gradle-enterprise.elastic.co/s/qola3dahtjoce)
- [elasticsearch-pull-request #106600 / part-3](https://gradle-enterprise.elastic.co/s/74j3ellyauqvg)
- [elasticsearch-pull-request #106555 / part-3](https://gradle-enterprise.elastic.co/s/a6drrf35mlnhg)
- [elasticsearch-intake #31705 / part3](https://gradle-enterprise.elastic.co/s/ppadxulz5cqpa)
- [elasticsearch-pull-request #106491 / part-3](https://gradle-enterprise.elastic.co/s/vn7s2tpuqg5yi)
- [elasticsearch-pull-request #106463 / part-3](https://gradle-enterprise.elastic.co/s/iojws7f4uxdio)
- [elasticsearch-intake #31678 / part3](https://gradle-enterprise.elastic.co/s/phgfqel6hnnli)
- [elasticsearch-pull-request #106381 / part-3](https://gradle-enterprise.elastic.co/s/n5dlrdblru3s6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.date.DateDiffTests.testSerializationOfSimple {TestCase=DateDiff(n<TEXT>, null, 2023-12-04T10:15:00Z<MILLIS>, 2024-12-04T10:15:01Z<MILLIS>) == 527040 null in 2}" -Dtests.seed=DDB972F924F891FB -Dtests.locale=mni-IN -Dtests.timezone=Europe/Malta -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.scalar.date.DateDiffTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.date.DateDiffTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.core.QlIllegalArgumentException: location [@1:1] and length [6] overrun query size [4]
```

**Issue Reasons:**
- [main] 72 failures in class org.elasticsearch.xpack.esql.expression.function.scalar.date.DateDiffTests (12.5% fail rate in 574 executions)
- [main] 46 failures in step part-3 (12.6% fail rate in 366 executions)
- [main] 13 failures in step part3 (18.3% fail rate in 71 executions)
- [main] 2 failures in step openjdk21_checkpart3_java-fips-matrix (40.0% fail rate in 5 executions)
- [main] 2 failures in step openjdk21_checkpart3_java-matrix (40.0% fail rate in 5 executions)
- [main] 2 failures in step release-tests (50.0% fail rate in 4 executions)
- [main] 40 failures in pipeline elasticsearch-pull-request (11.3% fail rate in 353 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (40.0% fail rate in 5 executions)
- [main] 13 failures in pipeline elasticsearch-intake (18.3% fail rate in 71 executions)
- [main] 3 failures in pipeline elasticsearch-periodic (50.0% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/138772

The randomConfiguration() function generates a random query text unless it receives a explicit one. That random query makes the Source deserialization fail.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateDiffTests.java [hunk 1]
```diff
@@ -152,7 +152,7 @@ private static List<TestCaseSupplier> makeSuppliers(
         Instant endTimestamp = Instant.parse(endTimestampString);
 
         Supplier<Configuration> configurationSupplier = () -> timezone == null
-            ? randomConfiguration()
+            ? randomConfiguration(TEST_SOURCE.text())
             : configurationForTimezone(ZoneId.of(timezone));
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateDiffTests.java:156]: FWIW this works because it comes from the `AbstractConfigurationFunctionTestCase`, which already knows which source to use, while the other is a generic utils function

**Review by julian-elastic — APPROVED** [review]
Looks good. Alternatively, you can also consider fixing randomConfiguration() to generate a query of at least the expected length for the source generated.

**Comment by ivancea** [comment]
> Looks good. Alternatively, you can also consider fixing randomConfiguration() to generate a query of at least the expected length for the source generated.

That function makes it fully randomized, query included. This caught some errors in the past.
But I added that extra override to pass the query, for cases like this
