### PR TITLE
[ML] fix bug in model snapshot upgrader where task never exits

### LINKED ISSUE #69276: [CI] MlJobSnapshotUpgradeIT.testSnapshotUpgrader
**Build scan**:

https://gradle-enterprise.elastic.co/s/eudgfems3awkq

**Repro line**:

```shell
./gradlew ':x-pack:qa:rolling-upgrade:v7.12.0#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT" -Dtests.method="testSnapshotUpgrader" -Dtests.seed=97DF6D86FBC6515D -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=en-CA -Dtests.timezone=Africa/Nouakchott -Druntime.java=8
```

**Reproduces locally?**:

No

**Applicable branches**:

`7.x`

**Failure history**:

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT&tests.sortField=FAILED&tests.test=testSnapshotUpgrader&tests.unstableOnly=true

**Failure excerpt**:

```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=status_exception, reason=Cannot upgrade job [ml-snapshots-upgrade-job] snapshot [1613739961] as there is currently a snapshot for this job being upgraded]
```

### PR DESCRIPTION
**Pull request by benwtrent**
It is possible that the model snapshot upgrader task is never fully shutdown.

This could occur in the following two scenarios:

 - The task state is failed being set to failed (we should kill the task in that situation)
 - The executor doesn't fire in time to initiate the shutdown before we shutdown the executor. This is caused by a race condition between scheduling the shutdown and closing the executor.

To the user, the failure looks like the REST request NEVER returning. In tests, it looks like:

```
13:10:20     ElasticsearchStatusException[Elasticsearch exception [type=status_exception, reason=Cannot upgrade job [ml-snapshots-upgrade-job] snapshot [1613739961] as there is currently a snapshot for this job being upgraded]]
```
As the request is spuriously retried and thus fails as the previous task never shutdown.

closes https://github.com/elastic/elasticsearch/issues/69276

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java [hunk 1]
```diff
@@ -358,30 +362,46 @@ private void checkResultsProcessorIsAlive() {
...
                 } finally {
                     onFinish.accept(e);
                 }
+                logger.debug("[{}] [{}] connection for upgrade has been closed, process is shutdown", jobId, snapshotId);
             });
-            autodetectWorkerExecutor.shutdown();
-            stateStreamer.cancel();
+            try {
+                future.get();
+                autodetectWorkerExecutor.shutdown();
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java:394]: This is the key here. Previously, it COULD be that `shutdown` is processed in the window between looking for something in the queue and checking if its closed.

This ensures that the `shutdown` request task is handled before closing the executor

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java [hunk 2]
```diff
@@ -105,7 +108,7 @@ void start() {
             params,
             autodetectExecutorService,
             (reason) -> {
-                setTaskToFailed(reason, ActionListener.wrap(t -> {}, f -> {}));
+                setTaskToFailed(reason, ActionListener.wrap(t -> {}, task::markAsFailed));
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java:111]: This is not the source of the bug shown by the test results, but it is definitely one that could occur in a strange scenario. Its best to kill the task all together if setting it to failed failed.

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java:111]: `failed` is a state that exists on the persistent task entry in the persistent tasks metadata.  If the whole task is set to failed then that whole entry in the persistent tasks metadata is removed.  So there's no point updating it to have a status of `failed`, then removing it altogether.  We should do one or the other.

For datafeeds there is no `failed` state - if they fail their persistent tasks metadata entry is removed which implies a `stopped` state.

For anomaly detection jobs the idea behind the `failed` state was that it was a way to keep the persistent tasks metadata entry while recording the failure.  This was done because then the `reason` in the persistent tasks metadata entry can record more information about _why_ the task failed and which node it failed on.  This is really useful stuff to know when the likely cause of failure is something that went wrong with a native process.  Not so useful if everything's in Java land (which is the datafeed case).

In the equivalent place for anomaly detection jobs we set the persistent task state to `failed` but keep the persistent task: https://github.com/elastic/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java#L685

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java:111]: > So there's no point updating it to have a status of failed, then removing it altogether. We should do one or the other.

This particular case is when we failed to set the persistent task state to failed. Consequently, it would still indicate its running even though it isn't. That is why I closed it (removing from cluster state) when it failed to set failed.

I can look into refactoring setting to failed vs. not existing at all, but I am not sure we want to do that along with this particular bug fix.

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/JobModelSnapshotUpgrader.java:111]: Sorry, I misread the line.  Yes, what you have is fine, and `markAsFailed` will log the exception that meant we couldn't set the task state to failed.

**Review by droberts195 — APPROVED** [review]
LGTM
