### PR TITLE
[Transform] Fail checkpoint on missing clusters

### LINKED ISSUE #104533: `DefaultCheckpointProviderTests#testHandlingShardFailures` doesn't work
`DefaultCheckpointProviderTests#testHandlingShardFailures` ends with a `latch.await(10, TimeUnit.SECONDS);` but that doesn't check that the latch has been counted down. In fact it isn't counted down, this test always waits for 10s before timing out and passing. I'm pretty sure it needs attention, either fixing with a `safeAwait(latch)`, or perhaps just removing if it's no longer relevant.

### LINKED ISSUE #106790: [Transform] Malformed remote cluster causes checkpointing to hang
### Elasticsearch Version

8.12.2

### Installed Plugins

_No response_

### Java Version

17.0.10

### OS Version

22.04.1-Ubuntu

### Problem Description

https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java#L116

When `remoteClusterResolver.resolve(transformConfig.getSource().getIndex())` returns no results, the `ActionListener<Map<String, long[]>> listener` is never called, causing the Transform to be started but stuck in `indexing`.

Any subsequent call to the `stats` API will cause the API call to timeout and the transport task to hang indefinitely.

### Steps to Reproduce

- spin up cluster
- add `Sample Web Logs` sample data
- create a working transform:
```
PUT _transform/last-log-from-clientip
{
  "source": {
    "index": [
      "kibana_sample_data_logs"
    ]
  },
  "latest": {
    "unique_key": [ 
      "clientip"
    ],
    "sort": "timestamp" 
  },
  "frequency": "1m", 
  "dest": {
    "index": "last-log-from-clientip"
  },
  "sync": { 
    "time": {
      "field": "timestamp",
      "delay": "60s"
    }
  },
  "retention_policy": { 
    "time": {
      "field": "timestamp",
      "max_age": "30d"
    }
  },
  "settings": {
    "max_page_search_size": 500
  }
}
```
- create a failing transform:
```
PUT _transform/last-log-from-clientip-failed
{
  "source": {
    "index": [
      "*:blah"
    ]
  },
  "latest": {
    "unique_key": [ 
      "clientip"
    ],
    "sort": "timestamp" 
  },
  "frequency": "1m", 
  "dest": {
    "index": "last-log-from-clientip-failed"
  },
  "sync": { 
    "time": {
      "field": "timestamp",
      "delay": "60s"
    }
  },
  "retention_policy": { 
    "time": {
      "field": "timestamp",
      "max_age": "30d"
    }
  },
  "settings": {
    "max_page_search_size": 500
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by prwhelan**
When there are no remote or local clusters for a given source index, we call the listener's `onFailure` method with a `CheckpointException`. A running transform will fail and retry, eventually moving into an unhealthy and failed state.  Any call to the stats API will note the checkpoint failure and return.

This fixes a timeout issue calling the Transform stats API and prevents the Transform from being stuck in indexing.

Fix #106790
Fix #104533

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java [hunk 1]
```diff
@@ -116,6 +116,11 @@ protected void getIndexCheckpoints(TimeValue timeout, ActionListener<Map<String,
             ResolvedIndices resolvedIndexes = remoteClusterResolver.resolve(transformConfig.getSource().getIndex());
             ActionListener<Map<String, long[]>> groupedListener = listener;
 
+            if (resolvedIndexes.numClusters() == 0) {
+                var indices = String.join(",", transformConfig.getSource().getIndex());
+                listener.onFailure(new CheckpointException("No clusters exist for [{}]", indices));
+            }
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java:122]: Should we `return;` here to prevent the rest of the code from being executed?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java [hunk 2]
```diff
@@ -234,10 +239,7 @@ private static void getCheckpointsFromOneClusterV2(
         );
         ActionListener<GetCheckpointAction.Response> checkpointListener;
         if (RemoteClusterService.LOCAL_CLUSTER_GROUP_KEY.equals(cluster)) {
-            checkpointListener = ActionListener.wrap(
-                checkpointResponse -> listener.onResponse(checkpointResponse.getCheckpoints()),
-                listener::onFailure
-            );
+            checkpointListener = listener.delegateFailure((l, r) -> l.onResponse(r.getCheckpoints()));
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java:242]: Would it make sense to keep using the more descriptive name (`checkpointResponse`) rather than `r`?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java [hunk 3]
```diff
@@ -401,12 +403,12 @@ public void getCheckpointingInfo(
 
         long timestamp = clock.millis();
 
-        getIndexCheckpoints(timeout, ActionListener.wrap(checkpointsByIndex -> {
-            TransformCheckpoint sourceCheckpoint = new TransformCheckpoint(transformConfig.getId(), timestamp, -1L, checkpointsByIndex, 0L);
+        getIndexCheckpoints(timeout, listener.delegateFailure((l, r) -> {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java:406]: Would it make sense to keep using the more descriptive name (`checkpointsByIndex`) rather than `r`?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java (hunk 2 above)
Comment (prwhelan) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java:242]: Yes, though I replaced this with `listener.safeMap(GetCheckpointAction.Response::getCheckpoints)` since it will do the `l.onResponse` for us

**Review by przemekwitek — APPROVED** [review]
LGTM
