### PR TITLE
Keep snapshot restore state and routing table in sync

### LINKED ISSUE #19774: Restoring a snapshot can leave cluster state in broken state
After a failed restore, the restore state in the cluster state is not properly cleaned up, blocking future restores from starting. Only a full cluster restart cleans the restore state.

Source: https://discuss.elastic.co/t/cannot-restore-snapshot-process-already-running/56746
Environment: 10 node cluster / elasticsearch 2.3.4 / Debian Jessie / NFS repository type

The cluster state shows that there are indices (e.g. index-a) which exist in snapshot state but don’t exist in metadata. Then there are indices (e.g. index-b) that are marked as INIT in snapshot state but shard routings are all marked as STARTED.

Excerpts from the anonymized cluster state:

```
  "restore" : {
    "snapshots" : [ {
      "snapshot" : "backup",
      "repository" : "backup",
      "state" : "STARTED",
      "indices" : [ "index-a", "index-b", ... ],
      "shards" : [  {
        "index" : "index-a",
        "shard" : 0,
        "state" : "SUCCESS"
      }, {
        "index" : "index-a",
        "shard" : 1,
        "state" : "FAILURE"
      }, ...

     ..., {
        "index" : "index-b",
        "shard" : 0,
        "state" : "INIT"
      }, {
        "index" : "index-b",
        "shard" : 1,
        "state" : "INIT"
      }, {
        "index" : "index-b",
        "shard" : 2,
        "state" : "SUCCESS"
      },

```

there is no indexmetadata/shardroutings for index-a in the cluster state but for index-b:

IndexMetaData:

```
      ...,
      "index-b" : {
        "state" : "open",
        "settings" : {
          "index" : {
            "creation_date" : "...",
            ...
          }
        },
        "mappings" : {
          ...
        },
        "aliases" : ...
      },
```

and

ShardRoutings:

```
      ...,
      "index-b" : {
        "shards" : {
          "2" : [ {
            "state" : "STARTED",
            "primary" : false,
            "node" : "HHYUOZZ7TqeapIamJeYU8w",
            "relocating_node" : null,
            "shard" : 2,
            "index" : "index-b",
            "version" : 47,
            "allocation_id" : {
              "id" : "2GELW1i0S7i8KPf_moWugg"
            }
          }, {
            "state" : "STARTED",
            "primary" : true,
            "node" : "r-kHLyr8Q3SlTt6ToVlq1A",
            "relocating_node" : null,
            "shard" : 2,
            "index" : "index-b",
            "version" : 47,
            "allocation_id" : {
              "id" : "S_O2zIM_ShG9g1oNCfeVew"
            }
          }, {
            "state" : "STARTED",
            "primary" : false,
            "node" : "_7WX9LH2TYyHEMykc-1s9w",
            "relocating_node" : null,
            "shard" : 2,
            "index" : "index-b",
            "version" : 47,
            "allocation_id" : {
              "id" : "-61Vup2mSnOrRKG2GfrY5Q"
            }
          } ],
          "1" : [ {
            "state" : "STARTED",
            "primary" : true,
            "node" : "vfw5y4jDTh-tiI2Gqc5fyA",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "index-b",
            "version" : 45,
            "allocation_id" : {
              "id" : "N4mQmap3TfGZWVsD8B7f3Q"
            }
          }, {
            "state" : "STARTED",
            "primary" : false,
            "node" : "HHYUOZZ7TqeapIamJeYU8w",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "index-b",
            "version" : 45,
            "allocation_id" : {
              "id" : "6EJtCi5uR8aRzDcow69yQQ"
            }
          }, {
            "state" : "STARTED",
            "primary" : false,
            "node" : "6IFVYG3ZT7iS0CZR6hhUsw",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "index-b",
            "version" : 45,
            "allocation_id" : {
              "id" : "ufHda_oUQ6qm5jHSV50Crw"
            }
          } ],
          "0" : [ {
            "state" : "STARTED",
            "primary" : false,
            "node" : "h6XBV034RL-psP0qXW9vmw",
            "relocating_node" : null,
            "shard" : 0,
            "index" : "index-b",
            "version" : 60,
            "allocation_id" : {
              "id" : "9QFXNtkqQYCkYfJ_HJ7mbA"
            }
          }, {
            "state" : "STARTED",
            "primary" : true,
            "node" : "lm1ClSoQT561rp7xvgmFbg",
            "relocating_node" : null,
            "shard" : 0,
            "index" : "index-b",
            "version" : 60,
            "allocation_id" : {
              "id" : "YrCTXmZ6RVm07a7d5UYPVg"
            }
          }, {
            "state" : "STARTED",
            "primary" : false,
            "node" : "xmuJY7BYRO6893-XTpTnTQ",
            "relocating_node" : null,
            "shard" : 0,
            "index" : "index-b",
            "version" : 60,
            "allocation_id" : {
              "id" : "x2u628VdSHS3p8vl9e7ufA"
            }
          } ]
        }
      }, ...
```

### PR DESCRIPTION
**Pull request by ywelsch**
The snapshot restore state tracks information about shards being restored from a snapshot in the cluster state. For example it records if a shard has been successfully restored or if restoring it was not possible due to a corruption of the snapshot. Recording these events is usually based on changes to the shard routing table, i.e., when a shard is started after a successful restore or failed after an unsuccessful one. As of now, there were two communication channels to transmit recovery failure / success to update the routing table and the restore state. This lead to issues where a shard was failed but the restore state was not updated due to connection issues between data and master node. In some rare situations, this lead to an issue where the restore state could not be properly cleaned up anymore by the master, making it impossible to start new restore operations. The following change updates routing table and restore state in the same cluster state update so that both always stay in sync. It also eliminates the extra communication channel for restore operations and uses the standard cluster state listener mechanism to update restore listener upon successful completion of a snapshot restore.

Closes #19774

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 1]
```diff
@@ -513,168 +514,199 @@ public RestoreInfo getRestoreInfo() {
...
 
-                if (request.processed) {
-                    return currentState;
+        @Override
+        public void shardFailed(ShardRouting failedShard, UnassignedInfo unassignedInfo) {
+            if (failedShard.primary() && failedShard.initializing()) {
+                RecoverySource recoverySource = failedShard.recoverySource();
+                if (recoverySource.getType() == RecoverySource.Type.SNAPSHOT) {
+                    Snapshot snapshot = ((SnapshotRecoverySource) recoverySource).snapshot();
+                    if (Lucene.isCorruptionException(unassignedInfo.getFailure().getCause())) {
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/RestoreService.java]: Could you add a comment explaining why we only fail in case of lucene corruption?

**Review by imotov — APPROVED** [review]
Left a couple of minor comments. Otherwise, LGTM.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java [hunk 2]
```diff
@@ -94,17 +96,21 @@ public ClusterState applyStartedShards(ClusterState clusterState, List<ShardRout
...
-    protected ClusterState buildResultAndLogHealthChange(ClusterState oldState, RoutingAllocation allocation, String reason,
-                                                   RoutingExplanations explanations) {
         RoutingTable oldRoutingTable = oldState.routingTable();
         RoutingNodes newRoutingNodes = allocation.routingNodes();
         final RoutingTable newRoutingTable = new RoutingTable.Builder().updateNodes(oldRoutingTable.version(), newRoutingNodes).build();
         MetaData newMetaData = allocation.updateMetaDataWithRoutingChanges(newRoutingTable);
         assert newRoutingTable.validate(newMetaData); // validates the routing table is coherent with the cluster state metadata
-        final ClusterState newState = ClusterState.builder(oldState).routingTable(newRoutingTable).metaData(newMetaData).build();
+        final RestoreInProgress restoreInProgress = allocation.custom(RestoreInProgress.TYPE);
+        RestoreInProgress updatedRestoreInProgress = allocation.updateRestoreInfoWithRoutingChanges(restoreInProgress);
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java]: agree

File: core/src/main/java/org/elasticsearch/snapshots/RestoreService.java (hunk 1 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/RestoreService.java]: sure

**Comment by ywelsch** [comment]
thanks for the review @imotov

**Comment by ILMostro** [comment]
Is there any hope of this being backported to 1.7 version?

**Comment by jasontedor** [comment]
No, sorry, 1.7 is end-of-life.
