### PR TITLE
ESQL: Improve error message for ( and [

### LINKED ISSUE #124145: [ES|QL] restore better syntax error messages
### Description

https://github.com/elastic/elasticsearch/commit/21845ad7a18821ccd80927211285308bb3eb8038 resulted in some negative changes to our syntax error messages.

The top priority is `row var = 1 not in`
- used to result in `mismatched input '<EOF>' expecting '('`
- but now says `mismatched input '<EOF>' expecting LP`

Image

(the lexer lost the literal name for LP, so it just gives the symbolic name... this won't be obvious to a user).

Also, an incorrect command name generates an error with a missing element in the list

`from index | project `
- used to result in mismatched input 'PROJECT' expecting {'dissect', 'drop', 'enrich', 'eval', 'grok', 'keep', 'limit', 'mv_expand', 'rename', 'sort', 'stats', 'where', 'lookup'}
- but now says mismatched input 'PROJECT' expecting {, 'enrich', 'dissect', 'eval', 'grok', 'limit', 'sort', 'stats', 'where', 'lookup', 'mv_expand', 'drop', 'keep', 'rename'}

Could we restore the original behavior in these cases? Particularly, the parentheses.

### PR DESCRIPTION
**Pull request by costin**
Due to recent grammar changes made ( token to no longer be reported by
 its text rather by his internal token name. Due to the use of pushMode,
 the symbol is not treated as a literal rather as a symbol.
To address this, the parser listener looks at the error message and
 changes the message before returning it to the user.

Fix #124145
Relates #123085 #121948

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java [hunk 1]
```diff
@@ -141,11 +145,17 @@ public void syntaxError(
...
             RecognitionException e
         ) {
-            if (recognizer instanceof EsqlBaseParser parser && parser.isDevVersion() == false) {
-                Matcher m = REPLACE_DEV.matcher(message);
-                message = m.replaceAll(StringUtils.EMPTY);
+            if (recognizer instanceof EsqlBaseParser parser) {
+                Matcher m = REPLACE_LP.matcher(message);
+                message = m.replaceAll(BEFORE_REPLACEMENT + "(" + AFTER_REPLACEMENT);
+                m = REPLACE_LEFT_BRACKET.matcher(message);
+                message = m.replaceAll(BEFORE_REPLACEMENT + "[" + AFTER_REPLACEMENT);
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java:152]: Is there a chance we could introduce corresponding tokens to the mode back?

I think it is a bit better to generate correct message from antlr when possible rather than rewrite it in our code.
This also introduces a string usage of the token names outside of the grammar and one more place to update if that is ever changed or renamed.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 2]
```diff
@@ -3109,6 +3109,15 @@ public void testFieldNamesAsCommands() throws Exception {
         }
     }
 
+    // [ and ( are used to trigger a double mode causing their symbol name (instead of text) to be used in error reporting
+    // this test checks that their are properly replaced in the error message
+    public void testPreserveParanthesis() {
+        // test for (
+        expectError("row a = 1 not in", "line 1:17: mismatched input '<EOF>' expecting '('");
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3116]: Should this be `row a = 1 | where a not in`?

Comment (ChrisHegarty) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3116]: I was hoping, when I seen the title of this PR, that it would help with the "rogue" closing paren also #119025. But it doesn't, e.g. ```row a = 1 not in]``` or ```FROM test | eval x = [1, 2, 3]]``` .
```
java.util.EmptyStackException
  at org.antlr.v4.runtime.Lexer.popMode(Lexer.java:192)
  at org.antlr.v4.runtime.atn.LexerPopModeAction.execute(LexerPopModeAction.java:58)
  at org.antlr.v4.runtime.atn.LexerActionExecutor.execute(LexerActionExecutor.java:168)
...
```  
I only mention it since the use of modes, and the limitations of handling errors in ANTLR, are related, which might influence the course of action here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java [hunk 3]
```diff
@@ -131,6 +131,10 @@ public void exitFunctionExpression(EsqlBaseParser.FunctionExpressionContext ctx)
     private static final BaseErrorListener ERROR_LISTENER = new BaseErrorListener() {
         // replace entries that start with <comma?><space?>DEV_<space?>
         private final Pattern REPLACE_DEV = Pattern.compile(",*\\s*DEV_\\w+\\s*");
+        private final String BEFORE_REGEX = "([\\s,]*)", AFTER_REGEX = "([\\s,]|$)";
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java:134]: I think `BEFORE_REGEX` is a bit too broad because it matches an empty string. So any future tokens ending in `lp` would match, too - like, if we introduced a `HELP` command.

Should this maybe be `(^|[\\s,]+)`?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java [hunk 4]
```diff
@@ -131,6 +131,10 @@ public void exitFunctionExpression(EsqlBaseParser.FunctionExpressionContext ctx)
...
+        private final String BEFORE_REPLACEMENT = "$1'", AFTER_REPLACEMENT = "'$2";
+        private final Pattern REPLACE_LP = Pattern.compile(BEFORE_REGEX + "LP" + AFTER_REGEX);
+        private final Pattern REPLACE_LEFT_BRACKET = Pattern.compile(BEFORE_REGEX + "OPENING_BRACKET" + AFTER_REGEX);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java:137]: For symmetry, shouldn't we also replace the token for right parens, and for the closing bracket?

Similarly, shouldn't we have a test for `.. | WHERE a in ("foo", ` and an analogous test for `]`?

**Review by alex-spies — COMMENTED** [review]
Like Ievgen, I think a solution based on regexes will be more brittle than somehow going back to when the parser/lexer referred to parens/brackets by their native symbols; but I didn't investigate how feasible that would be, so this is fine IMO.

I think we should at the very least be symmetric, however, and not specialize to opening brackets; the error messages for their closing counterparts at least need tests (and probably an analogous fix).

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3116]: > Should this be row a = 1 | where a not in?
1. not really because row points to a value expression which is a bool expression. As the error indicates
2. I've added another test for it just in case.

Comment (costin) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3116]: > I was hoping, when I seen the title of this PR

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java (hunk 4 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java:137]: > For symmetry, shouldn't we also replace the token for right parens, and for the closing bracket?

No because those are not lexed as symbols and are still kept as tokens (I _think_ because they simply pop the stack instead pushing twice to a new mode).

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/EsqlParser.java:137]: Thanks for the explanation!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 5]
```diff
@@ -3114,8 +3114,13 @@ public void testFieldNamesAsCommands() throws Exception {
     public void testPreserveParanthesis() {
         // test for (
         expectError("row a = 1 not in", "line 1:17: mismatched input '<EOF>' expecting '('");
+        expectError("row a = 1 | where a not in", "line 1:27: mismatched input '<EOF>' expecting '('");
+        expectError("row a = 1 | where a not in (1", "line 1:30: mismatched input '<EOF>' expecting {',', ')'}");
+        expectError("row a = 1 | where a not in [1", "line 1:28: missing '(' at '['");
+        expectError("row a = 1 | where a not in 123", "line 1:28: missing '(' at '123'");
         // test for [
         expectError("explain", "line 1:8: mismatched input '<EOF>' expecting '['");
+        expectError("explain ]", "line 1:9: token recognition error at: ']'");
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3123]: This is nice but we don't cover the case  of expecting a `]` and raising an error message that may call this `RIGHT_BRACKET` of `]`.

I'll push a small test case for this.

**Review by alex-spies — COMMENTED** [review]
One last minor comment (which I'll take care of myself) and this can be merged as a temporary hack until we find a better solution from my perspective.

**Review by alex-spies — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java (hunk 2 above)
Comment (ChrisHegarty) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3116]: > P.S. that should be a separate PR, since it needs backporting to the 8.x line vs this one that is targeting only 8.x.

 ... this one that is targeting only ~8.x~ 9.x.    Ah, yes, of course. Let's keep that separate then.

**Review by ChrisHegarty — APPROVED** [review]
This is an incremental improvement over the existing behaviour. LGTM.

**Comment by costin** [comment]
Letting the comment here for the record - I couldn't find a way to change the symbol to lexer through the grammar and instead modified the underlying `Vocabulary`, the class ANTLR uses to get the display name for the token.
While it is available as the interface, its underlying implementation is statically initialized based on the constants resulting from the grammar however it does expose its underlying string arrays which I've been able to hook into per the comments.
Obviously this is language specific - no idea how easy it would be to replicate it elsewhere.
The upside is in the future, new symbols can be added by just adding them to the replacement map.
