### PR TITLE
Fix FieldDataTermsFilter.equals.

### LINKED ISSUE #11779: Incorrect casting in FielddataTermsFilter equality
Hi Adrien,

it looks like there is a small bug in the `equals` method implementation that has been introduced by #10728. Each subclass tries to cast to `BytesFieldDataFilter` the object passed as parameter to the equals method, instead of trying to cast to their own class. For example, the `LongsFieldDataFilter#equals` method should contain
```
return terms.equals(((LongsFieldDataFilter) obj).terms);
``` 
and not
```
return terms.equals(((BytesFieldDataFilter) obj).terms);
```

### PR DESCRIPTION
**Pull request by jpountz**
DoublesFieldDataFilter and LongsFieldDataFilter were performing casts against
the wrong class.

Close #11779

### CODE REVIEW

File: src/test/java/org/elasticsearch/index/search/FieldDataTermsFilterTests.java [hunk 1]
```diff
@@ -247,6 +255,10 @@ public void testDoubles() throws Exception {
 
         hFilter = FieldDataTermsFilter.newDoubles(getFieldData(lngMapper), hTerms);
         assertNull(hFilter.getDocIdSet(reader.getContext(), reader.getLiveDocs()));
+
+        assertEquals(
+                FieldDataTermsFilter.newDoubles(getFieldData(lngMapper), hTerms),
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/index/search/FieldDataTermsFilterTests.java]: Should this be `getFieldData(dblMapper)`?

**Comment by rjernst** [comment]
LGTM. One small test question.

File: src/test/java/org/elasticsearch/index/search/FieldDataTermsFilterTests.java (hunk 1 above)
Comment (jpountz) [inline src/test/java/org/elasticsearch/index/search/FieldDataTermsFilterTests.java]: indeed, it's better. It doesn't change the equality test but makes more sense!
