### PR TITLE
Set mappings when creating indices in SuggestSearchIT

### LINKED ISSUE #39315: SuggestSearchIT.testEmpty failure in CI
Failed in master for the first time today, does not reproduce

```
java.lang.AssertionError: [shard [[4C1bk--TT7KuHqh-NWQx9g][test][1]], reason [RemoteTransportException[[node_s0][127.0.0.1:36557][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[no mapping found for field [text]]; ], cause [java.lang.IllegalArgumentException: no mapping found for field [text]
	at org.elasticsearch.search.suggest.SuggestionBuilder.populateCommonFields(SuggestionBuilder.java:307)
	at org.elasticsearch.search.suggest.term.TermSuggestionBuilder.build(TermSuggestionBuilder.java:448)
	at org.elasticsearch.search.suggest.SuggestBuilder.build(SuggestBuilder.java:175)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:808)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:607)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:582)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:385)
```

Reproduce line:
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=7E73F9B87A524CD5 \
  -Dtests.class=org.elasticsearch.search.suggest.SuggestSearchIT \
  -Dtests.method="testEmpty" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SA \
  -Dtests.timezone=America/Louisville \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Log:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1711/console

### PR DESCRIPTION
**Pull request by dakrone**
These tests don't test dynamic mapping, so they can use preset mappings. This
removes the possibility they may fail due to the mapping not being available
since mapping updates are asynchronous.

Resolves #39315

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java [hunk 1]
```diff
@@ -83,7 +83,7 @@
 
     // see #3196
     public void testSuggestAcrossMultipleIndices() throws IOException {
-        createIndex("test");
+        prepareCreate("test").addMapping("type1", "text", "type=text").get();
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java]: It might be nice to use `assertAcked` when creating indices, as we do in other places.

**Review by jtibshirani — APPROVED** [review]
Thanks @dakrone for this fix!

File: server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java (hunk 1 above)
Comment (dakrone) [reply server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java]: Good idea, I'll do that.
