### PR TITLE
Fix testCreateAndRestoreSearchableSnapshot

### LINKED ISSUE #55126: [CI] SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot failing
This looks to be a newly added test suite which has been regularly failing. There are actually two different failure messages for this test, but they're likely related so I'll put them both here.

The first *did not* reproduce for me:
https://gradle-enterprise.elastic.co/s/bp7bfzinzgj7a/tests/inzjkvfxeeuik-jku4cqj6y3o3c
```
org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests > testCreateAndRestoreSearchableSnapshot FAILED
    java.lang.AssertionError: Expecting stats to exist for at least 1 Lucene file
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at __randomizedtesting.SeedInfo.seed([82B6C95CFDFA75FC:8D5BE276E6D244F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.assertSearchableSnapshotStats(SearchableSnapshotsIntegTests.java:267)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot(SearchableSnapshotsIntegTests.java:160)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=82B6C95CFDFA75FC -Dtests.security.manager=true -Dtests.locale=zh-SG -Dtests.timezone=America/Knox_IN -Dcompiler.java=14
```

This one did in fact reproduce locally:
https://gradle-enterprise.elastic.co/s/4yuveowg6tzsw/tests/inzjkvfxeeuik-jku4cqj6y3o3c
```
org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests > testCreateAndRestoreSearchableSnapshot FAILED
    java.lang.AssertionError: Expected at least 1 cache read or write for _0.cfe of shard [amgquvzumi][4], node[y3zUJ5IeSn6pvfhh2OLNtw], [P], s[STARTED], a[id=ihYKI2haQcGYlxPQSu0HoQ]
    Expected: a value greater than <0L>
         but: <0L> was equal to <0L>
        at __randomizedtesting.SeedInfo.seed([592E3670FA883540:D34D410B691F64F3]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.assertSearchableSnapshotStats(SearchableSnapshotsIntegTests.java:298)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot(SearchableSnapshotsIntegTests.java:160)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=592E3670FA883540 -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=Asia/Beirut -Dcompiler.java=14
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Fixes a couple of related failures in SearchableSnapshotsIntegTests.

Firstly, we were not correctly accounting for the case where the cache was so
small that some/all files were read directly; fixed this by only asserting that
the cache is definitely used if the corresponding node has a cache that's large
enough to hold the whole index.

Secondly, we were not permitting shards to be completely empty, which might be
the case (rarely) if there were not many documents indexed and the distribution
of IDs was a bit unlucky; fixed this by asserting that we get stats for at
least one file for the whole index, rather than for each shard separately.

Closes #55126

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/searchablesnapshots/SearchableSnapshotShardStats.java [hunk 1]
```diff
@@ -77,6 +77,7 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
             builder.field("index_uuid", getIndexId().getId());
             builder.startObject("shard");
             {
+                builder.field("id", shardRouting.shardId());
```
Comment (DaveCTurner) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/searchablesnapshots/SearchableSnapshotShardStats.java:80]: Kinda unrelated change, but this was useful for debugging.

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/BaseSearchableSnapshotsIntegTestCase.java [hunk 2]
```diff
@@ -55,7 +55,9 @@ protected Settings nodeSettings(int nodeOrdinal) {
             builder.put(
                 CacheService.SNAPSHOT_CACHE_SIZE_SETTING.getKey(),
                 rarely()
-                    ? new ByteSizeValue(randomIntBetween(0, 10), ByteSizeUnit.KB)
+                    ? randomBoolean()
+                        ? new ByteSizeValue(randomIntBetween(0, 10), ByteSizeUnit.KB)
+                        : new ByteSizeValue(randomIntBetween(0, 1000), ByteSizeUnit.BYTES)
```
Comment (DaveCTurner) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/BaseSearchableSnapshotsIntegTestCase.java:60]: Prior to this change the smallest nonzero cache size was 1kB which was typically larger than many of the files seen in this test, so I thought this might improve coverage a bit.

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java [hunk 3]
```diff
@@ -261,11 +265,33 @@ private void assertSearchableSnapshotStats(String indexName, boolean cacheEnable
...
+        for (ObjectCursor<DiscoveryNode> nodeCursor : client().admin()
+            .cluster()
+            .prepareState()
+            .clear()
+            .setNodes(true)
+            .get()
+            .getState()
+            .nodes()
+            .getDataNodes()
+            .values()) {
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java:283]: :mask:

**Review by tlrx — APPROVED** [review]
LGTM, thanks David
