### PR TITLE
Take the node id into account when creating geoip tmp dir.

### LINKED ISSUE #69972: [CI] GeoIpDownloaderIT#testUseGeoIpProcessorWithDownloadedDBs() failure
**Build scan**: https://gradle-enterprise.elastic.co/s/ryzeqrltqakyc

**Repro line**: `./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testUseGeoIpProcessorWithDownloadedDBs" -Dtests.seed=5F0FC6BC560EA228 -Dtests.security.manager=true -Dtests.locale=hu -Dtests.timezone=America/Sitka -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**: https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Amsterdam&tests.container=org.elasticsearch.ingest.geoip.GeoIpDownloaderIT&tests.sortField=FAILED&tests.test=testUseGeoIpProcessorWithDownloadedDBs&tests.unstableOnly=true

**Failure excerpt**:

```

  | java.lang.AssertionError: |  
-- | -- | --
  | Expected: iterable with items [a string ending with "GeoLite2-City.mmdb", a string ending with "GeoLite2-Country.mmdb", a string ending with "GeoLite2-ASN.mmdb"] in any order |  
  | but: no item matches: a string ending with "GeoLite2-City.mmdb", a string ending with "GeoLite2-Country.mmdb", a string ending with "GeoLite2-ASN.mmdb" in [] |  

  |   | at __randomizedtesting.SeedInfo.seed([5F0FC6BC560EA228:1C5735FF891C853F]:0) |  
-- | -- | -- | --
  |   | •••
  |   | at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.lambda$testUseGeoIpProcessorWithDownloadedDBs$3(GeoIpDownloaderIT.java:241) |  
  |   | •••
  |   | at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testUseGeoIpProcessorWithDownloadedDBs(GeoIpDownloaderIT.java:237)


```

### PR DESCRIPTION
**Pull request by martijnvg**
This change adjust where the geoip tmp directory is created
to avoid issues when running multiple nodes on the same machine.

In the java tmp dir, a 'geoip-databases' directory is created and
directly under this directory a directory with the node id as name is created.
This allows safely running multiple nodes on the same machine (this
happens mainly during tests).

Closes #69972
Relates to #68920

### CODE REVIEW

File: modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderIT.java [hunk 1]
```diff
@@ -233,12 +233,22 @@ public void testUseGeoIpProcessorWithDownloadedDBs() throws Exception {
...
                 assertThat(Files.exists(geoipTmpDir), is(true));
                 return geoipTmpDir;
+            }).flatMap(path -> {
+                try {
+                    return Files.list(path);
+                } catch (IOException e) {
+                    throw new UncheckedIOException(e);
+                }
+            }).filter(path -> {
+                return StreamSupport.stream(clusterService().state().nodes().getDataNodes().values().spliterator(), false)
```
Comment (probakowski) [inline modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderIT.java:248]: Maybe extract data nodes ids to local variable?
```java
Set<String> ids = StreamSupport.stream(clusterService().state().nodes().getDataNodes().values().spliterator(), false)
    .map(c -> c.value.getId())
    .collect(Collectors.toSet());
final List<Path> geoipTmpDirs = ...
    }).filter(path -> ids.contains(path.getFileName().toString()))
```

**Review by probakowski — APPROVED** [review]
LGTM, thanks @martijnvg! I left 1 minor suggestion
