### PR TITLE
[8.19] Backport: Move HDFS-repo YAML to Rest tests

### LINKED ISSUE #145633: [CI] SecureHdfsRepositoryAnalysisRestIT class failing
**Build Scans:**
- [elasticsearch-intake #36989 / part2](https://gradle-enterprise.elastic.co/s/oxug3vgyo4jf4)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.blobstore.testkit.analyze.SecureHdfsRepositoryAnalysisRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.repositories.blobstore.testkit.analyze.SecureHdfsRepositoryAnalysisRestIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.19] 1 consecutive failures in class org.elasticsearch.repositories.blobstore.testkit.analyze.SecureHdfsRepositoryAnalysisRestIT
- [8.19] 1 consecutive failures in step part2
- [8.19] 1 consecutive failures in pipeline elasticsearch-intake

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by michalborek**
Backporting #140142 to use random port for HDFS.

Closes #145633

### CODE REVIEW

**Comment by inespot** [comment]
If my understanding is correct, the HDFS test fix PR originally targeted `9.4` (which is why this issue appeared again on an older release). 
But the PRs that surfaced this failure, eg : https://github.com/elastic/elasticsearch/pull/145751, also backported to `9.2` and `9.3` on top of the `8.19` branch that created the open issue. 
Based on the current release schedule, I think we also at least wanna backport this test fix to `9.3`, to prevent this flake from happening again on future backports?

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java [hunk 1]
```diff
@@ -109,7 +108,7 @@ public static void ensureNoCleanupInProgress(
     public static void ensureNotReadOnly(final ClusterState currentState, final String repositoryName) {
         final var repositoryMetadata = RepositoriesMetadata.get(currentState).repository(repositoryName);
         if (RepositoriesService.isReadOnly(repositoryMetadata.settings())) {
-            throw new RepositoryException(repositoryMetadata.name(), "repository is readonly");
+            throw new IllegalArgumentException("[" + repositoryMetadata.name() + "] repository is readonly");
```
Comment (inespot) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java:111]: The RepositoryException -> IllegalArgumentException change (here and in `SnapshotsService`) is the only part that has me a little sus since it is user-visible (if my understanding is correct) and may change how errors surface to clients. I am not certain we want that on a patch release. 
Maybe @tlrx will have more opinions on this, but I wonder if we are ok with changing client status code on patch releases?
If not, we could keep the original exception type in the backport and only adjust the tests to expect `RepositoryException`.

**Review by inespot — COMMENTED** [review]
Just one question!
Do we also know if backports can in any way affect the upstream serverless repository?

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java (hunk 1 above)
Comment (michalborek) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java:111]: Yeah, IIRC without this change the test was failing.

Comment (michalborek) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java:111]: On the other hand, the same was introduced to the main branch, so maybe it just had negligible impact on the users.

**Comment by michalborek** [comment]
> If my understanding is correct, the HDFS test fix PR originally targeted `9.4` (which is why this issue appeared again on an older release). But the PRs that surfaced this failure, eg : #145751, also backported to `9.2` and `9.3` on top of the `8.19` branch that created the open issue. Based on the current release schedule, I think we also at least wanna backport this test fix to `9.3`, to prevent this flake from happening again on future backports?

Good spot @inespot. I can prepare a backport for 9.3 older releases (this would be separate PRs, though).

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java (hunk 1 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java:111]: I think that very few users are likely to be affected by the change of the HTTP response code due to changing the type of exception. But returning a 5xx instead of 4xx has been considered as a bug in the original PR, so it should be the same on other branches too.

It means that this backport PR should be labeled as `>bug` too with a clear message on the changelog. Alternatively, we could backport the exception type change first as `bug` and then the test changes.

Comment (tlrx) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java:111]: I'm good with that too.

Comment (michalborek) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsServiceUtils.java:111]: the bugfix extracted from this backport https://github.com/elastic/elasticsearch/pull/146147  - I'll rebase this PR after merge

**Review by tlrx — APPROVED** [review]
LGTM - Please update the description to mention that https://github.com/elastic/elasticsearch/pull/140200 was backported separately. 

Will you also port this to 9.3?

**Comment by michalborek** [comment]
> Will you also port this to 9.3?

Yes, I'll port it to 9.3 and 9.2.
