### PR TITLE
Prevent direct upgrade of indices from 6.8 to 8.0

### LINKED ISSUE #81326: Recovering from 8.0 upgrade failure due to unmigrated 6.x indices
The Stack Management team removed the system index migration feature from Upgrade Assistant in 7.16 (https://github.com/elastic/kibana/pull/119798). During upgrade testing, @LeeDr discovered that users who upgrade from 6.8 to 7.16 will use Upgrade Assistant to prepare their deployment for upgrade, skipping the system indices migration step. It's reasonable to assume that some portion of these users might believe that they can upgrade to 8.0 at this point, unaware that we expect them to upgrade to 7.17 first.

After upgrading to 8.0, Elasticsearch will fail to start for these users because of the unmigrated 6.8 system indices. This startup failure occurs after ES has updated the keystore to be 8.x compatible. A user who attempts to fix this problem by downgrading to 7.16 will be blocked from doing so due to keystore incompatibility with 7.x (this is my assumption and needs verification). The user is now stuck, unable to complete their upgrade.

We have many users still on 6.x and prior, increasing the risk of users encountering this scenario. @DaveCTurner suggested we file this issue as an 8.0 blocker.

Some solutions suggested by David:
* Run some checks before doing the reorg
* Revert the reorg later on
* Provide some tool support for reverting it

CC @elastic/kibana-stack-management

### PR DESCRIPTION
**Pull request by grcevski**
This PR adds a check that relies on 7.17 calculating the overall index age
metadata from the existing indices we have. Once we have the oldest index
age computed, we add a check to prevent upgrades to 8.0 with any indices
that are older than 7.0.

Closes  #81326

### CODE REVIEW

**Comment by grcevski** [comment]
Still a draft because I need to figure out how to test this, other than the manual testing I did.

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java [hunk 1]
```diff
@@ -470,6 +491,50 @@ private static boolean upgradeLegacyNodeFolders(Logger logger, Settings settings
...
+
+        PersistedClusterStateService persistedClusterStateService = new PersistedClusterStateService(
+            paths,
+            metadata.nodeId(),
+            xContentRegistry,
+            new ClusterSettings(settings, ClusterSettings.BUILT_IN_CLUSTER_SETTINGS),
+            () -> TimeValue.nsecToMSec(System.nanoTime())
+        );
+
+        PersistedClusterStateService.OnDiskState onDiskState = persistedClusterStateService.loadBestOnDiskState();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:520]: I think this is too early in the node's lifecycle for loading the cluster state (that's why you had to create your own `NamedXContentRegistry`). Instead we should record the oldest index version in `NodeMetadata`, which means adding an entry to the `userData` attached to the Lucene commit for the cluster state.

**Comment by grcevski** [comment]
BWC are expected to fail.

**Comment by grcevski** [comment]
Disabling bwc tests until the change is backported to 7.17 and 8.0. Otherwise all upgrade tests fail because we expect to see metadata there.

**Comment by grcevski** [comment]
7.17 PR backport can be found here https://github.com/elastic/elasticsearch/pull/82771. The backport can't be direct because the 7 source is sufficiently different, and the actual 7.17 logic is not the same because we don't do the compatibility check there, we only compute the oldest index version.

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java [hunk 2]
```diff
@@ -470,6 +473,38 @@ private static boolean upgradeLegacyNodeFolders(Logger logger, Settings settings
...
+     * from older versions can cause irreversible changes if allowed.
+     * @param logger
+     * @param nodePaths
+     * @throws IOException
+     */
+    static void checkForIndexCompatibility(Logger logger, NodePath... nodePaths) throws IOException {
+        final Path[] paths = Arrays.stream(nodePaths).map(np -> np.path).toArray(Path[]::new);
+        NodeMetadata metadata = PersistedClusterStateService.nodeMetadata(paths);
+
+        // We are upgrading the cluster, but we didn't find any previous metadata. Possibly corrupted state.
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:487]: Since we've confirmed by this point that we're really doing an upgrade and not just starting a new node, I think we should bail out with an exception rather than just assuming everything is ok.

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java [hunk 3]
```diff
@@ -470,6 +473,38 @@ private static boolean upgradeLegacyNodeFolders(Logger logger, Settings settings
...
+        logger.info("oldest index version recorded in NodeMetadata {}", metadata.oldestIndexVersion());
+
+        if (metadata.oldestIndexVersion().before(Version.CURRENT.minimumIndexCompatibilityVersion())) {
+            throw new IllegalStateException(
+                "cannot upgrade node because incompatible indices created with version ["
+                    + metadata.oldestIndexVersion()
+                    + "] exist, while the minimum compatible index version is ["
+                    + Version.CURRENT.minimumIndexCompatibilityVersion()
+                    + "]. "
+                    + "Upgrade your older indices by booting version ["
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:501]: Might be helpful?

```suggestion
                    + "Upgrade your older indices by reindexing them in version ["
```

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java [hunk 4]
```diff
@@ -551,12 +586,14 @@ private static NodeMetadata loadNodeMetadata(Settings settings, Logger logger, N
             final NodeMetadata legacyMetadata = NodeMetadata.FORMAT.loadLatestState(logger, NamedXContentRegistry.EMPTY, paths);
             if (legacyMetadata == null) {
                 assert nodeIds.isEmpty() : nodeIds;
-                metadata = new NodeMetadata(generateNodeId(settings), Version.CURRENT);
+                // If we couldn't find legacy metadata, we set the latest index version to this version
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:589]: Maybe mention that in this case we're starting a new empty node so no indices to worry about.

File: server/src/main/java/org/elasticsearch/env/NodeMetadata.java [hunk 5]
```diff
@@ -145,8 +167,13 @@ public NodeMetadata build() {
             if (this.previousNodeVersion == null) {
                 previousNodeVersion = nodeVersion;
             }
+            if (this.oldestIndexVersion == null) {
+                oldestIndexVersion = Version.V_EMPTY;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/env/NodeMetadata.java:171]: This is only used in the legacy format which we shouldn't really be reading here, but I think this means that the index compatibility check will fail before the node version check happens, so the error will say that there are some ancient indices rather than that the previous node version is too old. I wonder if it would be better to check the index version in `NodeMetadata#upgradeToCurrentVersion` and just call that in both places so we have consistent checks.

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 6]
```diff
@@ -130,7 +131,7 @@
     public static final String LAST_PAGE_FIELD_NAME = "last_page";
     public static final int IS_LAST_PAGE = 1;
     public static final int IS_NOT_LAST_PAGE = 0;
-    private static final int COMMIT_DATA_SIZE = 4;
+    private static final int COMMIT_DATA_SIZE = 5;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:134]: We assert when loading the data that the commit's `userData` has this many entries, which will fail in upgrades from a 4-entry to a 5-entry commit I think.

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 7]
```diff
@@ -304,6 +306,9 @@ public static NodeMetadata nodeMetadata(Path... dataPaths) throws IOException {
                     } else if (nodeId == null) {
                         nodeId = thisNodeId;
                         version = Version.fromId(Integer.parseInt(userData.get(NODE_VERSION_KEY)));
+                        if (userData.containsKey(OLDEST_INDEX_VERSION_KEY)) {
+                            oldestIndexVersion = Version.fromId(Integer.parseInt(userData.get(OLDEST_INDEX_VERSION_KEY)));
+                        }
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:311]: Should we set `oldestIndexVersion` back to `Version.V_EMPTY` here if the key is missing? Otherwise we end up returning a `NodeMetadata` that never really existed. Super-rare case I know...

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 8]
```diff
@@ -672,14 +677,15 @@ void startWrite() {
             indexWriter.getConfig().setMergePolicy(NO_MERGE_POLICY);
         }
 
-        void prepareCommit(String nodeId, long currentTerm, long lastAcceptedVersion) throws IOException {
+        void prepareCommit(String nodeId, long currentTerm, long lastAcceptedVersion, int oldestIndexVersion) throws IOException {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:680]: Nit: could we keep this as a `Version` as long as possible?

```suggestion
        void prepareCommit(String nodeId, long currentTerm, long lastAcceptedVersion, Version oldestIndexVersion) throws IOException {
```

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 9]
```diff
@@ -971,23 +977,24 @@ private WriterStats addMetadata(Metadata metadata) throws IOException {
             return new WriterStats(true, metadata.indices().size(), 0);
         }
 
-        public void writeIncrementalTermUpdateAndCommit(long currentTerm, long lastAcceptedVersion) throws IOException {
+        public void writeIncrementalTermUpdateAndCommit(long currentTerm, long lastAcceptedVersion, int oldestIndexVersion)
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:980]: Similarly here:

```suggestion
        public void writeIncrementalTermUpdateAndCommit(long currentTerm, long lastAcceptedVersion, Version oldestIndexVersion)
```

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java [hunk 10]
```diff
@@ -878,6 +878,44 @@ public void testFindMappingsWithFilters() throws IOException {
...
+        Throwable ex = expectThrows(
+            IllegalArgumentException.class,
+            () -> buildIndicesWithVersions(new Version[] { Version.V_7_0_0, Version.V_EMPTY, Version.fromId(Version.CURRENT.id + 1) })
+                .build()
+        );
+
+        assertEquals("[index.version.created] is not present in the index settings for index with UUID [null]", ex.getMessage());
+    }
+
+    private Metadata.Builder buildIndicesWithVersions(Version[] indexVersions) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:900]: Think varargs makes the call sites a bit nicer:

```suggestion
    private Metadata.Builder buildIndicesWithVersions(Version... indexVersions) {
```

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java [hunk 11]
```diff
@@ -878,6 +878,44 @@ public void testFindMappingsWithFilters() throws IOException {
...
+
+        final List<Index> indices = new ArrayList<>();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:902]: Seems unused?

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java [hunk 12]
```diff
@@ -878,6 +878,44 @@ public void testFindMappingsWithFilters() throws IOException {
...
+        int lastIndexNum = randomIntBetween(9, 50);
+        Metadata.Builder b = Metadata.builder();
+        for (int k = 0; k < indexVersions.length; k++) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:905]: Think you can use a foreach here?

```suggestion
        for (Version indexVersion : indexVersions) {
```

File: server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java [hunk 13]
```diff
@@ -523,6 +538,66 @@ public void testBlocksDowngradeToVersionWithMultipleNodesInDataPath() throws IOE
...
+            // Simulate empty old index version, attempting to upgrade before 7.17
+            removeOldestIndexVersion(env.nodeDataPaths());
+
+            ex = expectThrows(
+                IllegalStateException.class,
+                "Must fail the check on index that's too old",
+                () -> checkForIndexCompatibility(logger, env.nodePaths())
+            );
+
+            assertThat(ex.getMessage(), startsWith("cannot upgrade node because incompatible indices created with version"));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java:596]: Aha yeah this is what I meant in a previous comment - we should report this as the node version being too old rather than mentioning `V_EMPTY`.

File: server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java [hunk 14]
```diff
@@ -603,4 +678,62 @@ public NodeEnvironment newNodeEnvironment(String[] dataPaths, String sharedDataP
...
+            final Path indexPath = dataPath.resolve(METADATA_DIRECTORY_NAME);
+            if (Files.exists(indexPath)) {
+                try (DirectoryReader reader = DirectoryReader.open(new NIOFSDirectory(dataPath.resolve(METADATA_DIRECTORY_NAME)))) {
+                    final Map<String, String> userData = reader.getIndexCommit().getUserData();
+
+                    final IndexWriterConfig indexWriterConfig = new IndexWriterConfig(new KeywordAnalyzer());
+                    indexWriterConfig.setOpenMode(IndexWriterConfig.OpenMode.APPEND);
+                    indexWriterConfig.setCommitOnClose(false);
+                    indexWriterConfig.setRAMBufferSizeMB(1.0);
+                    indexWriterConfig.setMergeScheduler(new SerialMergeScheduler());
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java:693]: I think the defaults are fine for our purposes here, no need to adjust them like this.

File: server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java [hunk 15]
```diff
@@ -603,4 +678,62 @@ public NodeEnvironment newNodeEnvironment(String[] dataPaths, String sharedDataP
...
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java:722]: Likewise here.

File: server/src/test/java/org/elasticsearch/env/NodeMetadataTests.java [hunk 16]
```diff
@@ -34,22 +34,34 @@ private Version randomVersion() {
...
+                final Tuple<NodeMetadata, Long> nodeMetadataLongTuple = NodeMetadata.FORMAT.loadLatestStateWithGeneration(
+                    logger,
+                    xContentRegistry(),
+                    tempDir
+                );
+                assertThat(nodeMetadataLongTuple.v2(), equalTo(generation));
+                return nodeMetadataLongTuple.v1();
+            },
+            nodeMetadata -> {
+                if (randomBoolean()) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/env/NodeMetadataTests.java:50]: Could we have a third branch which mutates the new field and leaves the other two fields alone, to verify that `equals()` does compare the new field too?

File: server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java [hunk 17]
```diff
@@ -1462,6 +1463,50 @@ public void testDeleteAllPaths() throws IOException {
...
+        final Path[] dataPaths2 = createDataPaths();
+        final Path[] combinedPaths = Stream.concat(Arrays.stream(dataPaths1), Arrays.stream(dataPaths2)).toArray(Path[]::new);
+
+        Version oldVersion = Version.fromId(Version.CURRENT.minimumIndexCompatibilityVersion().id - 1);
+
+        final Version[] indexVersions = new Version[] { oldVersion, Version.CURRENT, Version.fromId(Version.CURRENT.id + 1) };
+        final List<Index> indices = new ArrayList<>();
+        int lastIndexNum = randomIntBetween(9, 50);
+        Metadata.Builder b = Metadata.builder();
+        for (int k = 0; k < indexVersions.length; k++) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java:1477]: nit: foreach

```suggestion
        for (Version indexVersion : indexVersions) {
```

File: server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java [hunk 18]
```diff
@@ -1462,6 +1463,50 @@ public void testDeleteAllPaths() throws IOException {
...
 
+    public void testOldestIndexVersionIsCorrectlySerialized() throws IOException {
+        final Path[] dataPaths1 = createDataPaths();
+        final Path[] dataPaths2 = createDataPaths();
+        final Path[] combinedPaths = Stream.concat(Arrays.stream(dataPaths1), Arrays.stream(dataPaths2)).toArray(Path[]::new);
+
+        Version oldVersion = Version.fromId(Version.CURRENT.minimumIndexCompatibilityVersion().id - 1);
+
+        final Version[] indexVersions = new Version[] { oldVersion, Version.CURRENT, Version.fromId(Version.CURRENT.id + 1) };
+        final List<Index> indices = new ArrayList<>();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java:1474]: nit: effectively unused

**Review by DaveCTurner — COMMENTED** [review]
Looks good @grcevski, I left some minor comments/suggestions

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java (hunk 2 above)
Comment (grcevski) [reply server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:487]: OK, sounds good.

File: server/src/main/java/org/elasticsearch/env/NodeMetadata.java (hunk 5 above)
Comment (grcevski) [reply server/src/main/java/org/elasticsearch/env/NodeMetadata.java:171]: Yes exactly. I was testing direct to 8 upgrade from 6.8 and this showed up. Right now it says you have indices from version 0.0.0, which does the job but isn't the best. Good suggestion, I'll extract the upgrade/downgrade check on the metadata in a separate method and call that ahead.

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java (hunk 7 above)
Comment (grcevski) [reply server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:311]: Good catch, it's safest to do it!

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java (hunk 11 above)
Comment (grcevski) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:902]: Yeah, thanks for catching it. Left over from me writing the test.

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java [hunk 19]
```diff
@@ -388,6 +390,12 @@ private static boolean upgradeLegacyNodeFolders(Logger logger, Settings settings
             throw new IllegalStateException(message, e);
         }
 
+        try {
+            checkForIndexCompatibility(logger, legacyNodeLock.getNodePaths());
+        } finally {
+            legacyNodeLock.close();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:396]: I think we should only release the `legacyNodeLock` on failure - on success we need to keep hold of it until the end of this method.

We could move the `checkForIndexCompatibility` call within the next `try` block right?

**Review by DaveCTurner — COMMENTED** [review]
Looks good except for one tiny thing...

File: server/src/main/java/org/elasticsearch/env/NodeEnvironment.java (hunk 19 above)
Comment (grcevski) [reply server/src/main/java/org/elasticsearch/env/NodeEnvironment.java:396]: Ah good point, I was fixing a bug and you are right, I release it too soon.

**Review by DaveCTurner — APPROVED** [review]
LGTM
