### PR TITLE
Fix to release system resource after reading JKWSet file

### LINKED ISSUE #44942: [TEST] SecurityRealmSettingsTests failing on Windows
Build scan: https://scans.gradle.com/s/o3smubtjyn4gu

Relevant output:

```
org.elasticsearch.xpack.security.authc.SecurityRealmSettingsTests > classMethod FAILED
    java.io.IOException: Could not remove the following files (in the order of attempts):
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.2+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.security.authc.SecurityRealmSettingsTests_E46537D453124597-001\jwkset-005json: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.2+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.security.authc.SecurityRealmSettingsTests_E46537D453124597-001\jwkset-005json: The process cannot access the file because it is being used by another process.

       C:\Users\jenkins\workspace\elastic+elasticsearch+7.2+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.security.authc.SecurityRealmSettingsTests_E46537D453124597-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.2+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.security.authc.SecurityRealmSettingsTests_E46537D453124597-001
```

### PR DESCRIPTION
**Pull request by bizybot**
When we load a JSON Web Key (`JWKSet`) from the specified
file using `JWKSet.load` it internally uses [`IOUtils.readFileToString`](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/src/main/java/com/nimbusds/jose/util/IOUtils.java)
but the opened `FileInputStream` is never closed after usage.
https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/342

This commit reads the file and parses the `JWKSet` from the string.

This also fixes an issue wherein if the underlying file changed,
for every change event it would add another file watcher. The
change is to only add the file watcher at the start.

Closes #44942

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java [hunk 1]
```diff
@@ -317,7 +317,10 @@ private void validateAccessToken(AccessToken accessToken, JWT idToken) {
     @SuppressForbidden(reason = "uses toFile")
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: I don't think we need this `@SuppressForbidden` any more

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java [hunk 2]
```diff
@@ -317,7 +317,10 @@ private void validateAccessToken(AccessToken accessToken, JWT idToken) {
...
     private JWKSet readJwkSetFromFile(String jwkSetPath) throws IOException, ParseException {
         final Path path = realmConfig.env().configFile().resolve(jwkSetPath);
-        return JWKSet.load(path.toFile());
+        // avoid using JWKSet.loadFile() as it does not close FileInputStream internally
+        String jwkSet = new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: Why not `Files.readString()` ?

Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: its introduced in 11

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java (hunk 1 above)
Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: oh yes, will remove it. Thank you.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java (hunk 2 above)
Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: And? `master` depends on Java 12.

Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: oh yes, just realised I first fixed it on 7.x where the issue was reported and then moved to the master, sorry for the noise, fixed this and will change it when backporting. Thanks.

**Review by jkakavas — APPROVED** [review]
LGTM, thanks Yogesh

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java [hunk 3]
```diff
@@ -314,10 +313,12 @@ private void validateAccessToken(AccessToken accessToken, JWT idToken) {
...
      * @throws IOException    if the file cannot be read
      */
-    @SuppressForbidden(reason = "uses toFile")
     private JWKSet readJwkSetFromFile(String jwkSetPath) throws IOException, ParseException {
         final Path path = realmConfig.env().configFile().resolve(jwkSetPath);
-        return JWKSet.load(path.toFile());
+        // avoid using JWKSet.loadFile() as it does not close FileInputStream internally
+        String jwkSet = Files.readString(path, StandardCharsets.UTF_8);
+        return JWKSet.parse(jwkSet);
+
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java]: Nit: Blank line

**Review by tvernum — APPROVED** [review]
