### PR TITLE
Fix bwc tests failure to extract

### LINKED ISSUE #39441: :qa:full-cluster-restart bwc tests fails to extract 6.0 archive
Today the bwc tests failed several times on the 7.0 / 7.x branches, all with the same error:

```
Execution failed for task ':qa:full-cluster-restart:v6.0.0#oldClusterTestCluster#node0.extract'.
Could not expand ZIP '/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/dnm/elasticsearch/6.0.0/8aa6c56edf30cebae13846ce5d774bfec06fed81/elasticsearch-6.0.0.tar.gz'.
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/84/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+default-distro-bwc-tests/61/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc-tests/78/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/85/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/85/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+default-distro-bwc-tests/62/consoleFull

### PR DESCRIPTION
**Pull request by alpar-t**
Also fix a wait condition for older versions uncovered after the failure to extract was fixed

Closes #39441 #39751

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -292,7 +292,10 @@ protected HttpHost buildHttpHost(String host, int port) {
     @After
     public final void cleanUpCluster() throws Exception {
         if (preserveClusterUponCompletion() == false) {
-            ensureNoInitializingShards();
+            if (nodeVersions.stream().filter(version -> version.before(Version.V_6_2_0)).findAny().isPresent() == false) {
```
Comment (mark-vieira) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I think we can simplify `.filter().findAny().isPresent() == false` to just `.noneMatch()`

**Review by mark-vieira — APPROVED** [review]

**Comment by mark-vieira** [comment]
One small comment. Otherwise LGTM :+1:
