### PR TITLE
Fix RefreshListenerTests testDisallowAddListeners

### LINKED ISSUE #79689: RefreshListenerTests.testDisallowAddListeners failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/omdv4p4i5ccke/console-log?task=:server:test

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.index.shard.RefreshListenersTests.testDisallowAddListeners" -Dtests.seed=54B75B708A7005A4 -Dtests.locale=fr-CA -Dtests.timezone=America/Eirunepe -Druntime.java=11
```

**Reproduces locally?**: yes

**Applicable branches**: master, 7.16

**Failure excerpt**:
```
java.lang.AssertionError
  | at __randomizedtesting.SeedInfo.seed([54B75B708A7005A4:B44F81E20D49CA0D]:0) |  
  | at org.junit.Assert.fail(Assert.java:86) |  
  | at org.junit.Assert.assertTrue(Assert.java:41) |  
  | at org.junit.Assert.assertFalse(Assert.java:64) |  
  | at org.junit.Assert.assertFalse(Assert.java:74) |  
  | at org.elasticsearch.index.shard.RefreshListenersTests.testDisallowAddListeners(RefreshListenersTests.java:486)
```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
A recent change to RefreshListeners introduced new functionality
sequence number listeners. This change broke a test when the max allowed
listeners are randomly set to 2. This commit resolves it by checking
whether a new listener is allowed and asserting appropriately.

Closes #79689.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/shard/RefreshListenersTests.java [hunk 1]
```diff
@@ -503,8 +502,19 @@ public void testDisallowAddListeners() throws Exception {
...
 
         assertFalse(listeners.addOrNotify(index("1").getTranslogLocation(), new TestLocationListener()));
-        assertFalse(listeners.addOrNotify(index("1").getSeqNo(), new TestSeqNoListener()));
-        assertEquals(3, listeners.pendingCount());
+        final int expectedPending;
+        if (listeners.pendingCount() == maxListeners) {
+            // Rejected
+            TestSeqNoListener rejected = new TestSeqNoListener();
+            assertTrue(listeners.addOrNotify(index("1").getSeqNo(), rejected));
+            assertNotNull(rejected.error);
```
Comment (idegtiarenko) [inline server/src/test/java/org/elasticsearch/index/shard/RefreshListenersTests.java:510]: Just for my understanding, should `rejected.error` be also asserted in the other branch?

**Review by henningandersen — APPROVED** [review]
LGTM.
