### PR TITLE
ES|QL: Fix BytesRef2BlockHash

### LINKED ISSUE #130644: ESQL: Wrong STATS result in case of many distinct groups of 2 fields
`STATS COUNT() BY field1, field2` can produce wrong results if the cardinality of `field1` and `field2` is very large.

Steps to repro:
1.  create files to bulk ingest

```
for i in {1..10}; do
  for j in {1..100000}; do                                                                                                             
    echo "{\"index\": {\"_index\": \"test2\"}}" >> bulk$i.ndjson
    echo "{\"field\": \"$i\", \"otherfield\": \"$j\", \"concat\": \"$i$j\"}" >> bulk$i.ndjson
  done
done
```

Note how the `concat` field is just the concatenation of the `i` and `j` counters.

2. run ES locally via gradle, but increase heap size

```
./gradlew run -Dtests.es.logger.org.elasticsearch.xpack.esql=TRACE -Dtests.jvm.argline="-Xmx16000M"
```

3. bulk ingest

```
for i in {1..10}; do
  curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test2/_bulk?refresh" -XPOST --data-binary @bulk$i.ndjson
done
```

4. run queries

```
curl -u elastic:password -X POST 'localhost:9200/_query?format=txt' -H 'Content-Type: application/json' '-d
{                                                                                                                                      
  "query": "from test2 | stats count() by concat.keyword, otherfield.keyword| where concat.keyword == \"11\""}
'

empty!

    count()    |concat.keyword |otherfield.keyword
---------------+---------------+------------------

Correct if we filter before!
curl -u elastic:password -X POST 'localhost:9200/_query?format=txt' -H 'Content-Type: application/json' '-d
{
  "query": "from test2 | where concat.keyword == \"11\" | stats count() by concat.keyword, otherfield.keyword"}
'
    count()    |concat.keyword |otherfield.keyword
---------------+---------------+------------------
1              |11             |1 
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fix retrieval of keys in BytesRef2BlockHash

Fixes: https://github.com/elastic/elasticsearch/issues/130644

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java [hunk 1]
```diff
@@ -1232,6 +1235,190 @@ public void testLongNull() {
...
+            } finally {
+                Releasables.close(keys);
+            }
+        } finally {
+            Releasables.close(output);
+            page.releaseBlocks();
+        }
+    }
+
+    public void test2BytesRefs() {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1317]: This is the same test we had for BytesRef3BlockHash

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java [hunk 2]
```diff
@@ -1326,7 +1513,7 @@ public void close() {
                     fail("hashes should not close AddInput");
                 }
             });
-            assertThat(output1.size(), equalTo(output1.size()));
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1329]: A typo probably

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java [hunk 3]
```diff
@@ -1232,6 +1235,190 @@ public void testLongNull() {
...
+                BytesRef scratch = new BytesRef();
+                StringBuilder builder = new StringBuilder();
+                for (int i = 0; i < totalPositions; i++) {
+                    builder.setLength(0);
+                    builder.append(BytesRefs.toString(block0.getBytesRef(i, scratch)));
+                    builder.append("#");
+                    builder.append(BytesRefs.toString(block1.getBytesRef(i, scratch)));
+                    distinctKeys.add(builder.toString());
+                }
+                assertThat(distinctKeys.size(), equalTo(totalPositions));
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1307]: Revert the fix and you'll see a failure here

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java [hunk 4]
```diff
@@ -1232,6 +1235,190 @@ public void testLongNull() {
         }, blockFactory.newLongArrayVector(values, values.length).asBlock(), blockFactory.newConstantNullBlock(values.length));
     }
 
+    public void test2BytesRefsKeys() {
```
Comment (alex-spies) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java]: nit: maybe a more descriptive name? Like `test2BytesRefsHighCardinalityKey` or so?

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java [hunk 5]
```diff
@@ -1232,6 +1235,190 @@ public void testLongNull() {
...
+        }
+        record Output(int offset, IntBlock block, IntVector vector) implements Releasable {
+            @Override
+            public void close() {
+                Releasables.close(block, vector);
+            }
+        }
+        List<Output> output = new ArrayList<>();
+
+        try (BlockHash hash1 = new BytesRef2BlockHash(blockFactory, 0, 1, totalPositions);) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1267]: Can we randomize which key has high cardinality? It looks like this test only stuffs the high cardinality key into the first position, which repros the bug, but in principle the other position might have the same problem (if we implemented things differently).

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java [hunk 6]
```diff
@@ -145,7 +145,7 @@ public Block[] getKeys() {
         try {
             try (BytesRefBlock.Builder b1 = blockFactory.newBytesRefBlockBuilder(positions)) {
                 for (int i = 0; i < positions; i++) {
-                    int k1 = (int) (finalHash.get(i) & 0xffffL);
+                    int k1 = (int) (finalHash.get(i) & 0xffffffffL);
                     if (k1 == 0) {
```
Comment (bpintea) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: Shouldn't this (and below) be `if (k <= 0)` { ?

**Review by alex-spies — APPROVED** [review]
Looks good, only a minor remark from me. Thanks @luigidellaquila !

It'd be good if @nik9000 could also give this a look as he's way more familiar with the block hashes than me.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java (hunk 6 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: It can't be `0` because we grab the low bits. Right? I haven't had enough coffee for bit math.

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java (hunk 4 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java]: :+1: on `HighCardinality`.

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java (hunk 5 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1267]: :+1:

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java (hunk 4 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java]: This is java. Lean into the memes about long method names....

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java [hunk 7]
```diff
@@ -1232,6 +1235,190 @@ public void testLongNull() {
...
+            BytesRefBlock.Builder builder2 = blockFactory.newBytesRefBlockBuilder(totalPositions);
+        ) {
+            for (int i = 0; i < positions1; i++) {
+                for (int p = 0; p < positions2; p++) {
+                    builder1.appendBytesRef(new BytesRef("abcdef" + i));
+                    builder2.appendBytesRef(new BytesRef("abcdef" + p));
+                }
+            }
+            page = new Page(builder1.build(), builder2.build());
+        }
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1258]: Do we want this all in one page? I know the `BlockHash` needs it in memory. And we build that `HashMap` with it in memory below. But maybe we make `Page`s of a reasonable size here? 

Meh. I guess it's only like 9mb. Probably not worth changing it unless you need to go bigger.

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java (hunk 6 above)
Comment (bpintea) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: Could the `finalHash.get(i)` not return smth like `0xe0000000L` (or some other value with the 32nd bit set)?
The `hash1.hash.get()` method seems to expect a non-negative argument. It might all be safe, it just stood out to me since we're truncating a long.

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java (hunk 7 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/aggregation/blockhash/BlockHashTests.java:1258]: Yeah, it's small enough, and it reproduced the problem pretty consistently, so I guess it's not worth the effort and complication.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: These are always positive, they are generated by [BytesRefBlockHash](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/compute/src/main/generated-src/org/elasticsearch/compute/aggregation/blockhash/BytesRefBlockHash.java#L90), see [hashOrdToGroupNullReserved](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BlockHash.java#L252)

Comment (luigidellaquila) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: I guess one of the implicit assumptions is that a block hash will never have more than 2B positions. If it does, we'll need a larger data structure anyway I guess.

Comment (bpintea) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: > These are always positive

To make sure: `0xe0000000L` is a positive long. But `(int) (0xe0000000L & 0xffffffffL)` is a negative int.

> I guess one of the implicit assumptions is that a block hash will never have more than 2B positions.

Yeh, this is why I was thinking that this might still be safe. 👍 (At least if these are positions.)

Comment (alex-spies) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: I think @nik9000 should probably comment here as well - and whatever we end up with should probably become a Java comment here, that's too many assumptions for my head to infer, at least when skimming the file :D

Comment (luigidellaquila) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: @nik9000 any additional observations on this?

Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/aggregation/blockhash/BytesRef2BlockHash.java:151]: Y'all are right - we need positive integers from the hash. We're using the one from core which allows `long` - but we do intend to use only `int`. It's for sure worth a comment.

**Review by nik9000 — APPROVED** [review]

**Review by bpintea — APPROVED** [review]

**Comment by luigidellaquila** [comment]
Needs manual backport, working on it now

**Comment by luigidellaquila** [comment]
Manual backports:
- https://github.com/elastic/elasticsearch/pull/130907
- https://github.com/elastic/elasticsearch/pull/130918
