### PR TITLE
SQL: Remove exceptions from Analyzer

### LINKED ISSUE #38208: SQL: Remove exception throwing from Analyzer
Currently, there's still a rule that uses exceptions in case of problem - while this achieves the goal, the correct way is to let the Verifier collect all issues and report them in one go.
Additionally the same rule produces an incorrect message:
```
sql> select gender as g, min(salary) as min, max(salary) as max from test_emp group by 1 order by 2, 3, 2, 4 desc limit 3;
Bad request [line 1:103: Invalid %d specified in OrderBy (valid range is [1, %d])]
```

Which needs fixing.

### PR DESCRIPTION
**Pull request by costin**
Instead of throwing an exception, use an unresolved attribute to pass
the message to the Verifier.
Additionally improve the parser to save the extended source for the
Aggregate and OrderBy.

Close #38208

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 1]
```diff
@@ -524,7 +525,11 @@ protected LogicalPlan rule(LogicalPlan plan) {
                                     order.nullsPosition()));
                         }
                         else {
-                            throw new AnalysisException(order, "Invalid %d specified in OrderBy (valid range is [1, %d])", ordinal, max);
+                            // report error
+                            String message = LoggerMessageFormat.format("Invalid ordinal [{}] specified in [{}] (valid range is [1, {}])",
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java]: Minor: you can statically import and remove the `LoggerMessageFormat` qualifier.

**Review by matriv — APPROVED** [review]
LGTM. Nice fix!
