### PR TITLE
Ensures cleanup of temporary index-* generational blobs during snapshotting

### LINKED ISSUE #21462: Snapshots continuously failing with blob [pending-index-293] already exists, cannot overwrite
Got a 5.0.0-cluster logging this and failing to take snapshots. It should probably overwrite or gracefully handle the fact that he file exists.

```
[2016-11-10T13:04:33,885][WARN ][org.elasticsearch.snapshots.SnapshotsService] [found-snapshots:scheduled-1478783056-instance-0000000006/BWJzkt8QS6WPFBT8D5Ox4w] failed to finalize snapshot
org.elasticsearch.repositories.RepositoryException: [found-snapshots] failed to update snapshot in repository
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.finalizeSnapshot(BlobStoreRepository.java:544) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:878) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:444) [elasticsearch-5.0.0.jar:5.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.nio.file.FileAlreadyExistsException: blob [pending-index-293] already exists, cannot overwrite
	at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.writeBlob(S3BlobContainer.java:105) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeAtomic(BlobStoreRepository.java:872) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeIndexGen(BlobStoreRepository.java:782) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.finalizeSnapshot(BlobStoreRepository.java:540) ~[elasticsearch-5.0.0.jar:5.0.0]
	... 5 more
```

### PR DESCRIPTION
**Pull request by abeyad**
This PR ensures pending `index-*` blobs are deleted when snapshotting.  The
`index-*` blobs are generational files that maintain the snapshots
in the repository.  To write these atomically, we first write a
`pending-index-*` blob, then move it to `index-*`, which also deletes
`pending-index-*` in case its not a file-system level move (e.g.
S3 repositories) .  For example, to write the 5th generation of the
index blob for the repository, we would first write the bytes to
`pending-index-5` and then move `pending-index-5` to `index-5`.  It is
possible that we fail after writing `pending-index-5`, but before
moving it to `index-5` or deleting `pending-index-5`.  In this case,
we will have a dangling `pending-index-5` blob laying around.  Since
snapshot number 5 would have failed, the next snapshot assumes a generation
number of 5, so it tries to write to `index-5`, which first tries to
write to `pending-index-5` before moving the blob to `index-5`.  Since
`pending-index-5` is leftover from the previous failure, the snapshot
fails as it cannot overwrite this blob.

This commit solves the problem by first, adding a UUID to the
`pending-index-*` blobs, and secondly, strengthen the logic around
failure to write the `index-*` generational blob to ensure pending
files are deleted on cleanup.

Closes #21462

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 1]
```diff
@@ -867,16 +867,23 @@ private long listBlobsToGetLatestIndexId() throws IOException {
     }
 
     private void writeAtomic(final String blobName, final BytesReference bytesRef) throws IOException {
-        final String tempBlobName = "pending-" + blobName;
+        final String tempBlobName = "pending-" + UUIDs.randomBase64UUID() + "-" + blobName;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I wonder if it's nicer to append the random uuid.

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 2]
```diff
@@ -867,16 +867,23 @@ private long listBlobsToGetLatestIndexId() throws IOException {
...
-            throw ex;
+            IOException exceptionToThrow = ex;
+            try {
+                snapshotsBlobContainer.deleteBlob(tempBlobName);
+            } catch (NoSuchFileException e) {
+                // the temp file does not exist, so writeBlob probably failed above,
+                // exceptionToThrow will capture this and be thrown at the end
+            } catch (IOException e) {
+                if (exceptionToThrow == null) {
+                    exceptionToThrow = e;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: `exceptionToThrow` can never be null?
Maybe it's easier to just do the `ex.addSuppressed(...)`?

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 3]
```diff
@@ -867,16 +867,23 @@ private long listBlobsToGetLatestIndexId() throws IOException {
...
-        try {
             snapshotsBlobContainer.move(tempBlobName, blobName);
         } catch (IOException ex) {
-            // Move failed - try cleaning up
-            snapshotsBlobContainer.deleteBlob(tempBlobName);
-            throw ex;
+            IOException exceptionToThrow = ex;
+            try {
+                snapshotsBlobContainer.deleteBlob(tempBlobName);
+            } catch (NoSuchFileException e) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I don't think we should special-case this. Depending on underlying blobcontainer, a different exception might be thrown.

**Review by ywelsch — CHANGES_REQUESTED** [review]
Is it possible to add tests that show that the issue is fixed?

**Comment by abeyad** [comment]
retest this please

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 1 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Sure, done

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 3 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Its part of the contract of the `BlobContainer` to throw a `NoSuchFileException` if the blob doesn't exist on calling `deleteBlob`, and we changed all implementations to adhere to this contract.  That said, you are right, I went through two iterations of this, and now the only way we get to this block is if an exception was thrown, in which case we don't care about the nature of the exception here.  Same with below

**Comment by abeyad** [comment]
@ywelsch I pushed some commits that add a test and addresses your feedback

File: core/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java [hunk 4]
```diff
@@ -105,8 +105,11 @@
     Map<String, BlobMetaData> listBlobsByPrefix(String blobNamePrefix) throws IOException;
 
     /**
-     * Atomically renames the source blob into the target blob.  If the source blob does not exist or the
-     * target blob already exists, an exception is thrown.
+     * Renames the source blob into the target blob.  If the source blob does not exist or the
+     * target blob already exists, an exception is thrown.  Atomicity of the move operation is
+     * can only be guaranteed on an implementation-by-implementation basis.  The only current
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java]: is can

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 5]
```diff
@@ -867,15 +867,16 @@ private long listBlobsToGetLatestIndexId() throws IOException {
...
+        final String tempBlobName = "pending-" + blobName + "-" + UUIDs.randomBase64UUID();
         try (InputStream stream = bytesRef.streamInput()) {
             snapshotsBlobContainer.writeBlob(tempBlobName, stream, bytesRef.length());
-        }
-        try {
             snapshotsBlobContainer.move(tempBlobName, blobName);
         } catch (IOException ex) {
-            // Move failed - try cleaning up
-            snapshotsBlobContainer.deleteBlob(tempBlobName);
+            try {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: maybe readd comment here (temp file creation or move failed - clean up)

File: core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java [hunk 6]
```diff
@@ -321,14 +321,21 @@ public void deleteBlob(String blobName) throws IOException {
 
             @Override
             public void move(String sourceBlob, String targetBlob) throws IOException {
+                // simulate a non-atomic move, since many blob container implementations
+                // will not have an atomic move, and we should be able to handle that
                 maybeIOExceptionOrBlock(targetBlob);
-                super.move(sourceBlob, targetBlob);
+                super.writeBlob(targetBlob, readBlob(sourceBlob), 0L);
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java]: `super.readBlock` instead of `readBlock` to prevent double `maybeIOExceptionOrBlock`.

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 7]
```diff
@@ -2672,4 +2672,53 @@ public void testSnapshotCanceledOnRemovedShard() throws Exception {
         assertEquals("IndexShardSnapshotFailedException[Aborted]", snapshotInfo.shardFailures().get(0).reason());
     }
 
+    public void testSnapshotSucceedsAfterSnapshotFailure() throws Exception {
+        logger.info("--> creating repository");
+        final Path repoPath = randomRepoPath();
+        assertAcked(client().admin().cluster().preparePutRepository("test-repo").setType("mock").setVerify(false).setSettings(
+                Settings.builder().put("location", repoPath).put("random_control_io_exception_rate", 0.2)));
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: maybe add some randomization to the random_control_io_exception_rate?

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 8]
```diff
@@ -2672,4 +2672,53 @@ public void testSnapshotCanceledOnRemovedShard() throws Exception {
...
+                    .setIndices("test-idx")
+                    .get();
+            if (createSnapshotResponse.getSnapshotInfo().totalShards() != createSnapshotResponse.getSnapshotInfo().successfulShards()) {
+                assertThat(getFailureCount("test-repo"), greaterThan(0L));
+                assertThat(createSnapshotResponse.getSnapshotInfo().shardFailures().size(), greaterThan(0));
+                for (SnapshotShardFailure shardFailure : createSnapshotResponse.getSnapshotInfo().shardFailures()) {
+                    assertThat(shardFailure.reason(), containsString("Random IOException"));
+                }
+            }
+        } catch (Exception ex) {
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: can we catch a more specific exception type? IOException with the `Random IOException` string?

**Review by ywelsch — APPROVED** [review]
left minor comments (easy to fix). LGTM

File: core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java (hunk 6 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java]: good catch

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 8 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: The issue here is that either `SnapshotCreationException` or `RepositoryException` can be thrown, but what we can do here is ensure the stack trace has the `Random IOException` in the nested stack trace.

**Comment by abeyad** [comment]
@ywelsch I pushed a commit to address your latest feedback.  Thanks for reviewing!

**Comment by abeyad** [comment]
5.x commit: 6966fa5df46d04d97cc146cdf78f66ed687e6dbe
5.0 commit: a00b58864b77ef5b6140bbfd9bb6fccba665484f

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 8 above)
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: can be specified as `catch (SnapshotCreationException | RepositoryException ex)` in Java ;-)

File: core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java [hunk 9]
```diff
@@ -321,14 +321,20 @@ public void deleteBlob(String blobName) throws IOException {
 
             @Override
             public void move(String sourceBlob, String targetBlob) throws IOException {
+                // simulate a non-atomic move, since many blob container implementations
+                // will not have an atomic move, and we should be able to handle that
                 maybeIOExceptionOrBlock(targetBlob);
-                super.move(sourceBlob, targetBlob);
+                super.writeBlob(targetBlob, super.readBlob(sourceBlob), 0L);
+                super.deleteBlob(sourceBlob);
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java]: sorry, forgot to add here that we could randomize between atomic and non-atomic move.

Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java]: I pushed adb7aaded4ee9cfe19dd59781b3d85e570df9a57 to randomize between atomic and non-atomic
