### PR TITLE
Return correct term statistics when a field is not found in a shard

### LINKED ISSUE #21906: Bug in _termvectors with artificial document?
I am using the `_termvectors` API with an artificial document, and I hit an inconsistent behavior, depending on which shard the request hits. Below I attach reproducing steps, but let me first explain what I do: I create an index with two shards and index one document with one field and the value "one one". When I request the term vectors of that document with `term_statistics`, I get `ttf=2` as expected. At this point I know that one shard contains the document, and the other shard has no documents at all.

When I submit a `_termvectors` request with an artificial document with the field `text:one`, then if the request hits the shard that holds the indexed document, I get back `ttf=2` which is expected. But if it hits the shard without any documents, it returns `ttf=1` which is confusing.

More so, if I send an artificial document with the field `text:two` (NOTE: two does not exist in any of the shards!), then the response is similar -- if the query hits the shard without any documents, it returns `ttf=1`, while if it hits the shard with the one indexed document, it does not return `ttf` at all (which is expected).

Here are the steps to reproduce:

**Create the index**
```curl -XPUT 'localhost:9200/tv_bug' -d'
{
  "mappings": {
    "doc": {
      "properties": {
        "text" : {
          "type": "text"
        }
      }
    }
  },
  "settings" : {
    "index" : {
      "number_of_shards" : 2,
      "number_of_replicas" : 0
    }
  }
}'
```

**Index one document**
```
curl -XPUT 'http://localhost:9200/tv_bug/doc/1?pretty=true' -d '{
  "text" : "one one"
}'
```

**Verify the document exists in one shard**
```
curl -XGET 'http://localhost:9200/tv_bug/doc/_search?preference=_shards:0&pretty=true'
curl -XGET 'http://localhost:9200/tv_bug/doc/_search?preference=_shards:1&pretty=true'
```
One of those requests will return 0 hits, the other 1 (in my case shard 0 did not return the hit)

**Get the Term Vectors of that one document**
```
curl -XGET 'http://localhost:9200/tv_bug/doc/1/_termvectors?pretty=true' -d '{
  "fields": ["text"],
  "term_statistics" : true
}'
```

**Get the TV of 'one' using an artificial document**

***From shard 0***
```
curl -XGET 'http://localhost:9200/tv_bug/doc/_termvectors?preference=_shards:0&pretty=true' -d '{
  "term_statistics" : true,
  "doc" : {
    "text" : "one"
  }
}'
```

***From shard 1***
```
curl -XGET 'http://localhost:9200/tv_bug/doc/_termvectors?preference=_shards:1&pretty=true' -d '{
  "term_statistics" : true,
  "doc" : {
    "text" : "one"
  }
}'
```

In my case, shard 0 returns `ttf=1` and shard 1 returns `ttf=2` (expected). Also, if you send the word "two" instead, you will see that shard 1 does not return `ttf` at all (expected), but shard 0 returns `ttf=1`.

BTW, and this may be a different bug report, when I send the TV requests with the `preference` parameter, I sometimes receive this error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[C-N1Zbn][127.0.0.1:9300][indices:data/read/tv[s]]"
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}
```

Submitting the request multiple times eventually succeeds.

### PR DESCRIPTION
**Pull request by shaie**
If you ask for the term vectors of an artificial document with
term_statistics=true, but a shard does not have any terms of the doc's
field(s), it returns the doc's term vectors values as the shard-level
term statistics. This commit fixes that to return 0 for ttf and also
field-level aggregated statistics.

This closes #21906

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/termvectors/TermVectorsWriter.java [hunk 1]
```diff
@@ -292,4 +292,30 @@ private void writePotentiallyNegativeVLong(long value) throws IOException {
...
+        @Override public long getSumDocFreq() throws IOException { return 0; }
+        @Override public int getDocCount() throws IOException { return 0; }
+        @Override public boolean hasFreqs() { return false; }
+        @Override public boolean hasOffsets() { return false; }
+        @Override public boolean hasPositions() { return false; }
+        @Override public boolean hasPayloads() { return false; }
+    };
+
+    /** Implements an empty {@link TermsEnum}. */
+    private static final TermsEnum EMPTY_TERMS_ENUM = new TermsEnum() {
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/action/termvectors/TermVectorsWriter.java]: I think you can use Lucene's `TermsEnum.EMPTY` here?

File: core/src/test/java/org/elasticsearch/action/termvectors/GetTermVectorsIT.java [hunk 2]
```diff
@@ -848,6 +848,16 @@ public void testArtificialNoDoc() throws IOException {
                 .get();
         assertThat(resp.isExists(), equalTo(true));
         checkBrownFoxTermVector(resp.getFields(), "field1", false);
+
+        // Since the index is empty, all of artificial document's "term_statistics" should be 0/absent
+        Terms terms = resp.getFields().terms("field1");
+        assertEquals("sumDocFreq should be 0 for a non-existing field!", 0, terms.getSumDocFreq());
+        assertEquals("sumTotalTermFreq should be 0 for a non-existing field!", 0, terms.getSumTotalTermFreq());
+        TermsEnum termsEnum = terms.iterator(); // we're guaranteed to receive terms for that field
+        while (termsEnum.next() != null) {
```
Comment (mikemccand) [inline core/src/test/java/org/elasticsearch/action/termvectors/GetTermVectorsIT.java]: Hmm how come this iterator even returns any terms?

**Review by mikemccand — APPROVED** [review]
This LGTM; I just left one question about the test.

File: core/src/test/java/org/elasticsearch/action/termvectors/GetTermVectorsIT.java (hunk 2 above)
Comment (mikemccand) [inline core/src/test/java/org/elasticsearch/action/termvectors/GetTermVectorsIT.java]: OK thanks @shaie that makes sense ... I'll merge.

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
LGTM 2 @mikemccand i kicked off a build for this I can pull it in once it passes

**Comment by s1monw** [comment]
Thanks @shaie I backported this to all v5 branches too

**Comment by shaie** [comment]
Thanks @s1monw. For future contributions, is this something I should have done (backporting to branches)?

**Comment by s1monw** [comment]
@shaie no we usually do the backporting it's pretty straight forward most of the time, thanks!
