### PR TITLE
Force Connect Test: Fix flaky test caused by unreliable remote cluster stalling

### LINKED ISSUE #131656: [CI] RemoteSearchForceConnectTimeoutIT testTimeoutSetting failing
**Build Scans:**
- [elasticsearch-intake #25937 / part1](https://gradle-enterprise.elastic.co/s/zhqpguowr5m4u)
- [elasticsearch-pull-request #82271 / part-1](https://gradle-enterprise.elastic.co/s/ggqzgbn6nv2xq)
- [elasticsearch-periodic-platform-support #9521 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/6hckhuvofdzpk)
- [elasticsearch-periodic #9510 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/dmtaitbx74bsu)
- [elasticsearch-periodic #9510 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/yprg5zzyq3ia4)
- [elasticsearch-periodic #9510 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/c6k6uzdh2jxnm)
- [elasticsearch-periodic-platform-support #9521 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/aa6jnpp2p33yc)
- [elasticsearch-periodic-platform-support #9521 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/mpn2kx6v7ujjw)
- [elasticsearch-periodic-platform-support #9521 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/wy7l7lzeat6du)
- [elasticsearch-pull-request #81994 / part-1](https://gradle-enterprise.elastic.co/s/k66toah7n77y4)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indices.cluster.RemoteSearchForceConnectTimeoutIT.testTimeoutSetting" -Dtests.seed=9568DF993389FEDF -Dtests.locale=szl-PL -Dtests.timezone=America/Grand_Turk -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indices.cluster.RemoteSearchForceConnectTimeoutIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTimeoutSetting'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <1>
     but: was <0>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testTimeoutSetting
- [main] 12 failures in test testTimeoutSetting (24.0% fail rate in 50 executions)
- [main] 2 failures in step part1 (33.3% fail rate in 6 executions)
- [main] 3 failures in step part-1 (16.7% fail rate in 18 executions)
- [main] 2 failures in pipeline elasticsearch-intake (33.3% fail rate in 6 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (18.8% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by pawankartik-elastic**
I was able to reproduce the flaky-ness and the changes in this PR seem to have fixed the flaky-ness.

Without these changes = failures seen when running the tests for multiple iterations.
With these changes = no failures when running the tests for multiple iterations (100+ iterations).

Hopefully, fixes #131656 and #132179.

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/indices/cluster/FieldCapsForceConnectTimeoutIT.java [hunk 1]
```diff
@@ -73,21 +73,23 @@ protected Map<String, Boolean> skipUnavailableForRemoteClusters() {
...
-                cluster(LINKED_CLUSTER_1).getInstance(TransportService.class, (String) null),
-                ((transport, discoveryNode, profile, listener) -> {
+        for (String localNodeName : cluster(LOCAL_CLUSTER).getNodeNames()) {
+            MockTransportService localMts = (MockTransportService) cluster(LOCAL_CLUSTER).getInstance(
+                TransportService.class,
+                localNodeName
+            );
+            for (String remoteNodeName : cluster(LINKED_CLUSTER_1).getNodeNames()) {
+                TransportService remoteTs = cluster(LINKED_CLUSTER_1).getInstance(TransportService.class, remoteNodeName);
+                localMts.addConnectBehavior(remoteTs, ((transport, discoveryNode, profile, listener) -> {
```
Comment (drempapis) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/cluster/FieldCapsForceConnectTimeoutIT.java:83]: If I understand well, the updated code blocks all remote targets per local node, making the timeout behavior-assertions reliable.

**Review by drempapis — APPROVED** [review]
LGTM! Thank you Pawan
