### PR TITLE
[ML] fixes testWatchdog test verifying matcher is interrupted on timeout

### LINKED ISSUE #48861: [CI] TimeoutCheckerTests.testWatchdog failing regularly
TimeoutCheckerTests.testWatchdog has been failing regularly on master and 7.x for the last few days.

master example: https://gradle-enterprise.elastic.co/s/vcaxvky7vonu6
7.x example: https://gradle-enterprise.elastic.co/s/d5bttww4yctky

The error is:

```
04:39:58 org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests > testWatchdog FAILED
04:39:58     Wanted but not invoked:
04:39:58     matcher.interrupt();
04:39:58     -> at org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.lambda$testWatchdog$2(TimeoutCheckerTests.java:72)
04:39:58     Actually, there were zero interactions with this mock.
04:39:58         at __randomizedtesting.SeedInfo.seed([4BA94B8F714382E0:E9C403A9D4A4ABA6]:0)
04:39:58         at org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.lambda$testWatchdog$2(TimeoutCheckerTests.java:72)
04:39:58         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:867)
04:39:58         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:840)
04:39:58         at org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.testWatchdog(TimeoutCheckerTests.java:71)
```

This didn't reproduce locally on master using:

```
./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.testWatchdog" \
  -Dtests.seed=4BA94B8F714382E0 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=ECT \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

It is probably a side effect of #48346.

### PR DESCRIPTION
**Pull request by benwtrent**
Constructing the timout checker FIRST and THEN registering the watcher allows the test to have a race condition.

The timeout value could be reached BEFORE the matcher is added. To prevent the matcher never being interrupted, a new `timedOut` value is added to the watcher thread entry. Then when a new matcher is registered, if the thread was previously timedout, we interrupt the matcher immediately.

closes https://github.com/elastic/elasticsearch/issues/48861

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
I think the problem you've identified could affect the production code as well as the test code.  But you've fixed the test by introducing a new code path that works well for the test.  So the production code is left with a flaw while the test starts working.

It seems like a solution that should work both for testing and production is to say that if a matcher is registered after a timeout then it's instantly interrupted, i.e. change:

```
        @Override
        public void register(Matcher matcher) {
            WatchDogEntry value = registry.get(Thread.currentThread());
            if (value != null) {
                boolean wasFalse = value.registered.compareAndSet(false, true);
                assert wasFalse;
                value.matchers.add(matcher);
            }
        }
```

to something like:

```
        @Override
        public void register(Matcher matcher) {
            WatchDogEntry value = registry.get(Thread.currentThread());
            if (value != null) {
                synchronized (TimeoutChecker.this) {
                    boolean wasFalse = value.registered.compareAndSet(false, true);
                    assert wasFalse;
                    value.matchers.add(matcher);
                    if (TimeoutChecker.this.timeoutExceeded) {
                        matcher.interrupt();
                    }
                }
            }
        }
```

Then the test can stay more-or-less as it was, but the timeout should be a random value between 10 and 500 to increase the chance of testing both code paths.

What do you think?

**Comment by benwtrent** [comment]
> It seems like a solution that should work both for testing and production is to say that if a matcher is registered after a timeout then it's instantly interrupted,

Definitely! I will make the change

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample-windows

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimeoutChecker.java [hunk 1]
```diff
@@ -143,6 +141,9 @@ public void register(Matcher matcher) {
                 boolean wasFalse = value.registered.compareAndSet(false, true);
                 assert wasFalse;
                 value.matchers.add(matcher);
+                if (value.isTimedOut()) {
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimeoutChecker.java:144]: Doing this check unsynchronized means there's a chance for the matcher to be interrupted twice.

I know you have worked around this in the test by using `atLeastOnce()`, but it leaves the question of what a real Joni `Matcher` does if interrupted twice.

So I think that either you need to investigate what happens if a real Joni `Matcher` is interrupted twice, or (probably simpler) put this bit in a `synchronized` block so that it cannot run while `interruptLongRunningThreadIfRegistered` is part way through.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/filestructurefinder/TimeoutCheckerTests.java [hunk 2]
```diff
@@ -59,21 +60,19 @@ public void testCheckTimeoutExceeded() throws Exception {
...
-
+            final TimeoutChecker.TimeoutCheckerWatchdog watchdog = (TimeoutChecker.TimeoutCheckerWatchdog) TimeoutChecker.watchdog;
             Matcher matcher = mock(Matcher.class);
-            TimeoutChecker.watchdog.register(matcher);
+            watchdog.register(matcher);
             assertThat(watchdog.registry.get(Thread.currentThread()).matchers.size(), equalTo(1));
             try {
                 assertBusy(() -> {
-                    verify(matcher).interrupt();
+                    verify(matcher, atLeastOnce()).interrupt();
```
Comment (droberts195) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/filestructurefinder/TimeoutCheckerTests.java:72]: It would be nice to get rid of the `atLeastOnce` and have the watchdog ensure it's exactly once, because otherwise it opens the question of what happens to a real Joni `Matcher`.

**Review by droberts195 — APPROVED** [review]
LGTM
