### PR TITLE
Make persistent task cluster service test more stable

### LINKED ISSUE #76337: [CI] PersistentTasksClusterServiceTests testReassignOnlyOnce failing
Test fails periodically - https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.persistent.PersistentTasksClusterServiceTests&tests.sortField=FAILED&tests.test=testReassignOnlyOnce&tests.unstableOnly=true

**Build scan:**
https://gradle-enterprise.elastic.co/s/oplmfm45lwzws/tests/:server:test/org.elasticsearch.persistent.PersistentTasksClusterServiceTests/testReassignOnlyOnce

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.persistent.PersistentTasksClusterServiceTests.testReassignOnlyOnce" -Dtests.seed=30AD981ED9A4583E -Dtests.locale=ar-QA -Dtests.timezone=Antarctica/Vostok -Druntime.java=16 -Dtests.fips.enabled=true`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.persistent.PersistentTasksClusterServiceTests&tests.test=testReassignOnlyOnce

**Failure excerpt:**
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
clusterService.submitStateUpdateTask(
    "reassign persistent tasks",
    <any>
);
Wanted 2 times:
-> at org.elasticsearch.persistent.PersistentTasksClusterServiceTests.lambda$testReassignOnlyOnce$15(PersistentTasksClusterServiceTests.java:686)
But was 3 times. Undesired invocation:
-> at org.elasticsearch.persistent.PersistentTasksClusterService.reassignPersistentTasks(PersistentTasksClusterService.java:362)

  at __randomizedtesting.SeedInfo.seed([30AD981ED9A4583E:4297546793FE2066]:0)
  at org.elasticsearch.persistent.PersistentTasksClusterServiceTests.lambda$testReassignOnlyOnce$15(PersistentTasksClusterServiceTests.java:686)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:977)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:950)
  at org.elasticsearch.persistent.PersistentTasksClusterServiceTests.testReassignOnlyOnce(PersistentTasksClusterServiceTests.java:686)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

### PR DESCRIPTION
**Pull request by benwtrent**
Previously, it was possible to have:

 - both threads start
 - One sits in the submit update task
 - The other has not even scheduled to run yet
 - Latch counts down
 - Thread 1 finishes, allowing another submit task
 - Thread 2 now gets scheduled and ran and submits a cluster update request

Fixes #76337

### CODE REVIEW

**Comment by benwtrent** [comment]
I have incorporated this test fix in both backports: 

https://github.com/elastic/elasticsearch/pull/76314
https://github.com/elastic/elasticsearch/pull/76315

**Review by arteam — APPROVED** [review]
LGTM! I think it totally makes sense to start the 2nd thread only after first has been submitted

File: server/src/test/java/org/elasticsearch/persistent/PersistentTasksClusterServiceTests.java [hunk 1]
```diff
@@ -670,15 +670,15 @@ public void testReassignOnlyOnce() throws Exception {
         Thread t2 = new Thread(service::reassignPersistentTasks);
         try {
             t1.start();
-            t2.start();
             // Make sure we have at least one reassign check before we count down the latch
             assertBusy(
                 () -> verify(recheckTestClusterService, atLeastOnce()).submitStateUpdateTask(eq("reassign persistent tasks"), any())
```
Comment (droberts195) [inline server/src/test/java/org/elasticsearch/persistent/PersistentTasksClusterServiceTests.java:675]: Should this now be exactly once instead of at least once?  If not, please add a comment to say why there might be more than one.

**Review by droberts195 — APPROVED** [review]
LGTM2, although it would be good if you could bring the comments up to date so future maintainers don't get confused

File: server/src/test/java/org/elasticsearch/persistent/PersistentTasksClusterServiceTests.java (hunk 1 above)
Comment (benwtrent) [reply server/src/test/java/org/elasticsearch/persistent/PersistentTasksClusterServiceTests.java:675]: @droberts195 the `atLeastOnce` is because these `verify` checks are also present after the test has ran. If I did `1` time only, the test would fail because there is a valid execution later (when both have finished executing making sure the atomicboolean is unset).

**Comment by henningandersen** [comment]
I think this needs a backport to 7.x too?

**Comment by benwtrent** [comment]
@henningandersen the original backports of the first PR included this fix.
