### PR TITLE
ES|QL: Fix KQL/QSTR with unmapped fields in NULLIFY mode

### LINKED ISSUE #142959: ESQL: QSTR function after SORT stops being allowed when using STATS(unmapped_field)
### Description

```
SET unmapped_fields="nullify";
 from airports
| sort city
| where qstr("country:test")
| stats min(unmapped_field_baz)
```

results in 

```
[QSTR] function cannot be used after SORT",
                "stack_trace": "org.elasticsearch.xpack.esql.VerificationException: Found 1 problem
line 5:3: [QSTR] function cannot be used after SORT
at org.elasticsearch.xpack.esql.analysis.Analyzer.verify(Analyzer.java:280)
at org.elasticsearch.xpack.esql.analysis.Analyzer.analyze(Analyzer.java:274)
```

If `stats` is on an existent field, then things are resulting in an error.
Quickly checking the code at `FullTextFunction.checkFullTextQueryFunctionForCondition` a `SORT` command should be ok before QSTR command under unrelated conditions. But the query above should be ok for QSTR usage.

### LINKED ISSUE #142968: ES|QL: verification_exception "[KQL] function cannot be used after WHERE" when EVAL references unmapped fields with SET unmapped_fields="NULLIFY"
### Description

When using `SET unmapped_fields="NULLIFY"` in combination with `KQL()` and an `EVAL` that references a field not mapped in the matched indices, ES|QL returns a `verification_exception`:

```
[KQL] function cannot be used after WHERE
```

The `KQL()` function is correctly placed in the first `WHERE` directly after `FROM`.

### Steps to reproduce

The following query fails, `duration` is not mapped in `traces-apm.rum*` indices:

```esql
SET unmapped_fields="NULLIFY"; FROM traces-apm.rum*
  | WHERE KQL("service.name:*")
  | WHERE TO_STRING(processor.event) == "transaction" OR processor.event IS NULL
  | EVAL duration_ms_otel = ROUND(duration) / 1000 / 1000
  | STATS AVG(duration_ms_otel) BY BUCKET(@timestamp, 100, ?_tstart, ?_tend)
```

Replacing `duration` with `span.duration.us` (which IS mapped in the same indices) makes it work:

```esql
SET unmapped_fields="NULLIFY"; FROM traces-apm.rum*
  | WHERE KQL("service.name:*")
  | WHERE TO_STRING(processor.event) == "transaction" OR processor.event IS NULL
  | EVAL duration_ms_ecs = ROUND(span.duration.us) / 1000 / 1000
  | STATS AVG(duration_ms_ecs) BY BUCKET(@timestamp, 100, ?_tstart, ?_tend)
```

Image

### Expected behavior

Both queries should execute successfully. `SET unmapped_fields="NULLIFY"` should resolve the unmapped field as `null` in `EVAL` without affecting the validation of `KQL()` placement.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixing full text functions (KQL, QSTR) usage in queries with `unmapped_fields=NULLIFY`.

When using `SET unmapped_fields="nullify"`, KQL and QSTR functions would fail validation due to`Eval` nodes added right after `EsRelation`.

Here we propose a different approach: instead of adding an EVAL, we add unmapped fields directly to `EsRelation`'s output with `DataType.NULL`. 
`ReplaceFieldWithConstantOrNull` (local planner) rule will replace them with null literals anyway.

This should be fine, this is the same thing we do with non-existing fields locally (with index patterns). 
And it's conceptually the same thing we do with LOAD strategy.

For non-FROM queries (eg. ROW) we still fall back to adding an EVAL.

I also evaluated two other solutions, but they don't seem to work:
- make the fulltext functions validation more fine-grained, eg. allowing EVALs with all NULL values before KQL. It's fragile, users would be able to add an `EVAL non_existing = null` manually, and it would be hard to distinguish.
- add the EVAL right before the unsupported fields are used (rather than right after FROM): it doesn't work in all cases, eg. we'd have to consider KEEP/DROP and other commands that mask the non-existing fields. It's fragile and complicated.

Fixes: https://github.com/elastic/elasticsearch/issues/142968
Fixes: https://github.com/elastic/elasticsearch/issues/142959

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java [hunk 1]
```diff
@@ -97,19 +99,53 @@ private static LogicalPlan resolve(LogicalPlan plan, boolean load) {
...
+                return esr;
+            }
+            List<FieldAttribute> fieldsToNullify = fieldsToNullify(unresolved, Expressions.names(esr.output()));
+            return fieldsToNullify.isEmpty() ? esr : esr.withAttributes(combine(esr.output(), fieldsToNullify));
+        });
+
+        // For non-EsRelation sources (Row, LocalRelation): insert Eval nodes with null assignments
+        // This handles cases like: ROW x = 1 | EVAL y = unmapped_field
+        transformed = transformed.transformUp(
+            n -> n instanceof UnaryPlan unary && unary.child() instanceof LeafPlan leaf && (leaf instanceof EsRelation == false),
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java]: Nit: no need for ( )

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java [hunk 2]
```diff
@@ -222,6 +259,24 @@ private static LogicalPlan evalUnresolvedAtopNary(LogicalPlan nAry, List<Alias>
...
 
+    /**
+     * Inserts an Eval atop each child of the given {@code nAry}, if the child is a non-EsRelation LeafPlan.
+     * EsRelation sources are handled separately by adding fields to their output.
+     */
+    private static LogicalPlan evalUnresolvedAtopNaryNonEsRelation(LogicalPlan nAry, List<Alias> nullAliases) {
+        List<LogicalPlan> newChildren = new ArrayList<>(nAry.children().size());
+        boolean changed = false;
+        for (var child : nAry.children()) {
+            if (child instanceof LeafPlan source && (source instanceof EsRelation == false)) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java]: Also here, ( ) are redundant.

**Review by bpintea — APPROVED** [review]
LGTM.
Left two nits, but not worth going through CI if these will be the only left things.
I think I kind of like this solution better. 👍
