### PR TITLE
SQL: Perform lazy evaluation of mismatched mappings

### LINKED ISSUE #35659: SQL: Perform lazy evaluation of mismatched mappings
Especially in the logging case, it is common to have mappings with some inconsistencies yet these fields are never used in the result, e.g.:
```sql
SELECT longitude, latitude, dateTime 
FROM "mike_location*"
ORDER BY dateTime
LIMIT 1
```
returns

> Unexpected error from Elasticsearch: [verification_exception] Found 1 problem(s) line 2:6: [mike_location*] points to indices with incompatible mappings; field [previous_location] is mapped in [2] different ways: [object] in [mike_location], [geo_point] in [mike_location-v2]

While the message is correct, note that the problematic fields are not used.
Such queries should be allowed since the problematic fields are never used and thus can be safely ignored.

### PR DESCRIPTION
**Pull request by costin**
Move away from performing eager, fail-fast validation of mismatched
 mapping to a lazy evaluation based on the fields actually used in the
 query. This allows queries to run on the parts of the indices that
 "work" which is not just convenient but also a necessity for large
 mappings (like logging) where alignment is hard/impossible to achieve.

Fix #35659

Note this PR picked up uses #35675 until it gets merged into master (see the first commit) - it's the second commit which is relevant.

### CODE REVIEW

**Comment by costin** [comment]
retest this please

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/InvalidMappedField.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    @Override
+    public int hashCode() {
+        return Objects.hash(super.hashCode(), errorMessage);
+    }
+
+    @Override
+    public boolean equals(Object obj) {
+        if (super.equals(obj)) {
+            InvalidMappedField other = (InvalidMappedField) obj;
+            return Objects.equals(errorMessage, other.errorMessage);
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/InvalidMappedField.java]: Minor, but If the objects are equal (`this == other`) we don't need to check, on the other hand might be ugly to implement completely the super.equals here.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java [hunk 2]
```diff
@@ -280,44 +290,79 @@ static IndexResolution mergedMapping(String indexPattern, Map<String, Map<String
...
+            fieldName = fieldName.substring(dot + 1);
+            EsField parent = flattedMapping.get(parentName);
+            if (parent == null) {
+                Map<String, FieldCapabilities> map = globalCaps.get(parentName);
+                if (map == null) {
+                    throw new SqlIllegalArgumentException("Cannot find field {}; this is likely a bug", parentName);
+                }
+                FieldCapabilities parentCap = map.values().iterator().next();
+                parent = createField(parentName, globalCaps, hierarchicalMapping, flattedMapping,
+                        s -> createField(s, parentCap.getType(), new TreeMap<>(), parentCap.isAggregatable()));
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: maybe I'm overlooking something, but why do you need a new TreeMap here, Collections.emptyMap() won't work?

**Review by matriv — COMMENTED** [review]
Looks good, left 2 comments.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/InvalidMappedField.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/InvalidMappedField.java]: Right, that's why the call to the equals above.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: The map is used for the properties of the parent; a treeMap is used since the children need to be sorted out alphabetically. The field caps does not return fields in order anymore and thus this needs to be maintained internally.
`emptyMap` is still used for fields that do not have children but the call above is for a parent (which by definition has).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java [hunk 3]
```diff
@@ -280,44 +290,79 @@ static IndexResolution mergedMapping(String indexPattern, Map<String, Map<String
...
-                    return IndexResolution.invalid(errorMessage.toString());
-                }
-                
-                FieldCapabilities fieldCap = types.values().iterator().next();
-                // validate search/agg-able
-                if (fieldCap.isAggregatable() && fieldCap.nonAggregatableIndices() != null) {
-                    errorMessage.append("[" + indexPattern + "] points to indices with incompatible mappings: ");
-                    errorMessage.append("field [" + name + "] is aggregateable except in ");
-                    errorMessage.append(Arrays.toString(fieldCap.nonAggregatableIndices()));
+                    errorMessage.insert(0, "mapped as [" + types.size() + "] incompatible types: ");
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: I understand the need to use `types.size()` as it can be of large values when multiple indices are resolved and used in a query, but would you consider at least for smaller size values - like 1,2,3 - to use the word instead? (`one`, `two`, `three`)

**Review by astefan — APPROVED** [review]
LGTM. Left one (more cosmetic) comment.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java (hunk 3 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: How would that work? First 1 should never appear so it's about 2, 3 (or whatever limit) and the rest.
This means the message can be "mapped as [three] incompatible types" vs "mapped as [5] incompatible types" since we don't have any utility to convert the numbers into words.
Further more words are never used instead of numbers in any error message that I can think of plus it decreases the readability of the message imo - `[5]` is shorter and more concise than `[five]` which arguably should not have the `[`, `]` around.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: got it, thx!

**Review by matriv — APPROVED** [review]
LGTM

**Comment by rashidkpc** [comment]
Wooooooooo
