### PR TITLE
[ML] fix race condition with job snapshot upgrade and feature reset

### LINKED ISSUE #84709: [CI] XPackRestIT test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot} failing
It's timing out in feature reset.  This implies we should be more brutal about killing in-progress model snapshot upgrades in feature reset.  There's no point waiting for them to complete gracefully when we're resetting ML to empty.

**Build scan:**
https://gradle-enterprise.elastic.co/s/eagejrwl4tbqg/tests/:x-pack:plugin:yamlRestTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=ml%2Fupgrade_job_snapshot%2FTest%20existing%20but%20corrupt%20snapshot%7D

**Reproduction line:**
`./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot}" -Dtests.seed=E303315D855D1857 -Dtests.locale=es-EC -Dtests.timezone=Asia/Urumqi -Druntime.java=17`

**Applicable branches:**
8.1

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Dml/upgrade_job_snapshot/Test%20existing%20but%20corrupt%20snapshot%7D

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:41815], URI [/_features/_reset], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"timeout_exception","reason":"Timed out waiting for completion of [org.elasticsearch.xpack.ml.job.snapshot.upgrader.SnapshotUpgradeTask@7e68ad0d]"}],"type":"failed_node_exception","reason":"Failed node [6kCknKSqQE-fAlVRXhtMVQ]","node_id":"6kCknKSqQE-fAlVRXhtMVQ","caused_by":{"type":"timeout_exception","reason":"Timed out waiting for completion of [org.elasticsearch.xpack.ml.job.snapshot.upgrader.SnapshotUpgradeTask@7e68ad0d]"}},"status":500}

  at __randomizedtesting.SeedInfo.seed([E303315D855D1857:6B570E872BA175AF]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:346)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:312)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:287)
  at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.resetFeatures(MlRestTestStateCleaner.java:36)
  at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.clearMlState(AbstractXPackRestTest.java:131)
  at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.cleanup(AbstractXPackRestTest.java:115)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by benwtrent**
This addresses a race condition in feature reset && model snapshot upgrade.

It is possible that feature reset is called soon after the task is assigned, meaning the persistent task is cancelled before the model snapshot upgrader is set on the task. 

This means that the task could continue executing even after being cancelled as nothing else checks if the feature is being reset or if the task has been cancelled.

closes https://github.com/elastic/elasticsearch/issues/84709

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java [hunk 1]
```diff
@@ -500,6 +511,17 @@ protected void doRun() {
...
+                            closeHandler.accept(
+                                new ElasticsearchStatusException(
+                                    "cancelling model upgrade for snapshot [{}] for job [{}] due to feature reset",
+                                    RestStatus.NOT_FOUND,
+                                    jobId,
+                                    snapshotId
+                                )
+                            );
+                            return;
+                        }
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java:524]: I think this should be more like the `nodeDying` case above, where it returns `null` to the close handler.

Returning an exception here will cause a warning to be logged in the calling code.  We should probably go even further than the `nodeDying` case, and not log it at all (or log at trace level), because if the reset had happened just a second later then all its work would have been silently wiped out by the feature reset.  Also, returning an exception here causes a notification message to be indexed.  Since that's async that might be the next subtle race condition, or even if we're protecting against notification logging messing up feature reset it's still pointless work that's immediately undone.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java [hunk 2]
```diff
@@ -480,6 +480,17 @@ public void upgradeSnapshot(SnapshotUpgradeTask task, Consumer<Exception> closeH
...
+                if (resetInProgress) {
+                    closeHandler.accept(
+                        new ElasticsearchStatusException(
+                            "cancelling model upgrade for snapshot [{}] for job [{}] due to feature reset",
+                            RestStatus.NOT_FOUND,
+                            jobId,
+                            snapshotId
+                        )
+                    );
+                    return;
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java:492]: Like the other case, we should return `null` to the close handler here, and not log anything at all (or log at trace level).  A feature reset means it's totally expected for nothing related to ML to exist afterwards, and anything in progress to have been cancelled without verbose commentary.

**Review by droberts195 — COMMENTED** [review]
I think you've closed the loopholes, but please adjust the close handler arguments to avoid log spam.

**Review by droberts195 — APPROVED** [review]
LGTM
