### PR TITLE
Fix bug in point in time response

### LINKED ISSUE #131026: Open PIT swaps skipped & failed _shards results
### Elasticsearch Version

9.1.0-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

Open PIT request returns the number of failed shards in the "skipped" field and the number of skipped shards in the "failed" field.

Looks like the bug has been in place since partial search was added to PIT (https://github.com/elastic/elasticsearch/pull/111516).

I believe the fix is just to pass values in the correct order here: https://github.com/elastic/elasticsearch/blob/8bcb0c4c652a9e102a0831ea1ebad7d73a18d78e/server/src/main/java/org/elasticsearch/action/search/OpenPointInTimeResponse.java#L62
https://github.com/elastic/elasticsearch/blob/8bcb0c4c652a9e102a0831ea1ebad7d73a18d78e/server/src/main/java/org/elasticsearch/rest/action/RestActions.java#L80-L88
Though we also clearly need to fill a gap in testing.

### Steps to Reproduce

1. Start a 2 node cluster
2. Put an index with 2 shards
```
PUT /test
{
    "settings": {
        "index": {
            "number_of_shards": 2,
            "number_of_replicas": 0
        }
    }
}
```
3. Stop one of the nodes (therefore making a shard unavailable).
4. Open a PIT allowing partial search results
```
POST /test/_pit?keep_alive=1m&allow_partial_search_results=true
-> {
  "id": "...",
  "_shards": {
    "total": 2,
    "successful": 1,
    "skipped": 1,
    "failed": 0
  }
}
```
There should be 1 shard failed, not 1 skipped. For instance, a normal search gives:
```
GET /test/_search
-> {
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 2,
    "successful": 1,
    "skipped": 0,
    "failed": 1,
    "failures": [
      {
        "shard": 1,
        "index": "test",
        "node": null,
        "reason": {
          "type": "no_shard_available_action_exception",
          "reason": null
        }
      }
    ]
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by benchaplin**
Resolves https://github.com/elastic/elasticsearch/issues/131026.

The failed and skipped parameters are swapped.

See: https://github.com/elastic/elasticsearch/blob/8bcb0c4c652a9e102a0831ea1ebad7d73a18d78e/server/src/main/java/org/elasticsearch/rest/action/RestActions.java#L80-L88

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/search/OpenPointInTimeResponseTests.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+        BytesReference actual;
+        try (XContentBuilder builder = XContentBuilder.builder(XContentType.JSON.xContent())) {
+            OpenPointInTimeResponse response = new OpenPointInTimeResponse(pointInTimeId, 11, 8, 2, 1);
+            response.toXContent(builder, ToXContent.EMPTY_PARAMS);
+            actual = BytesReference.bytes(builder);
+        }
+
+        String encodedId = Base64.getUrlEncoder().encodeToString(BytesReference.toBytes(pointInTimeId));
+        BytesReference expected = new BytesArray(String.format("""
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/action/search/OpenPointInTimeResponseTests.java]: Just to save you clicking through to the CI failures: 
Forbidden method invocation: java.lang.String#format(java.lang.String,java.lang.Object[]) [Uses default locale]	
  in org.elasticsearch.action.search.OpenPointInTimeResponseTests (OpenPointInTimeResponseTests.java:43)
  
I always forget to add the locale as well.

**Review by cbuescher — APPROVED** [review]
LGTM, thanks a lot for adding the test here as well.

File: server/src/test/java/org/elasticsearch/action/search/OpenPointInTimeResponseTests.java (hunk 1 above)
Comment (benchaplin) [reply server/src/test/java/org/elasticsearch/action/search/OpenPointInTimeResponseTests.java]: Ah thank you!
