### PR TITLE
Fix FullClusterRestartIT#testSnapshotRestore

### LINKED ISSUE #38603: FullClusterRestartIT#testSnapshotRestore failure
Actual failure:

```
 Throwable #1: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:33469], URI [/_template/test_template?include_type_name=true], status line [HTTP/1.1 400 Bad Request]
   > Warnings: [[types removal] Specifying include_type_name in put index template requests is deprecated. The parameter will be removed in the next major version
```

In the `FullClusterRestartIT#testSnapshotRestore` test, against a 7.0.0 node, the type of a index template is no longer included in the put index api's request body. Also `include_type_name` appears to be set, but the put index template api still fails with the fact that `_doc` is missing.

```
  1> [2019-02-08T10:01:24,279][INFO ][o.e.u.FullClusterRestartIT] [testSnapshotRestore] before test
  1> [2019-02-08T10:01:24,458][INFO ][o.e.u.FullClusterRestartIT] [testSnapshotRestore] initializing REST clients against [http://[::1]:33469, http://[::1]:40831]
  1> [2019-02-08T10:01:25,030][WARN ][o.e.c.RestClient         ] [testSnapshotRestore] request [GET http://[::1]:33469/info/doc/testsnapshotrestore_count?filter_path=_source] returned 1 warnings: [299 Elasticsearch-7.1.0-SNAPSHOT-Unknown "[types removal] Specifying types in document get requests is deprecated, use the /{index}/_doc/{id} endpoint instead."]
  1> [2019-02-08T10:01:25,196][WARN ][o.e.c.RestClient         ] [testSnapshotRestore] request [PUT http://[::1]:33469/_template/test_template?include_type_name=true] returned 1 warnings: [299 Elasticsearch-7.1.0-SNAPSHOT-Unknown "[types removal] Specifying include_type_name in put index template requests is deprecated. The parameter will be removed in the next major version."]
  1> [2019-02-08T10:01:25,260][INFO ][o.e.u.FullClusterRestartIT] [testSnapshotRestore] after test
  2> REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.6.1#upgradedClusterTestRunner -Dtests.seed=ACCA8891B511EDB8 -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT -Dtests.method="testSnapshotRestore" -Dtests.security.manager=true -Dtests.locale=pt -Dtests.timezone=America/Danmarkshavn -Dcompiler.java=11 -Druntime.java=8
ERROR   1.03s | FullClusterRestartIT.testSnapshotRestore <<< FAILURES!
   > Throwable #1: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:33469], URI [/_template/test_template?include_type_name=true], status line [HTTP/1.1 400 Bad Request]
   > Warnings: [[types removal] Specifying include_type_name in put index template requests is deprecated. The parameter will be removed in the next major version.]
   > {"error":{"root_cause":[{"type":"invalid_type_name_exception","reason":"mapping type name [_source] can't start with '_' unless it is called [_doc]"}],"type":"invalid_type_name_exception","reason":"mapping type name [_source] can't start with '_' unless it is called [_doc]"},"status":400}
   >    at __randomizedtesting.SeedInfo.seed([ACCA8891B511EDB8:93AF62687FACEAC7]:0)
   >    at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
   >    at org.elasticsearch.upgrades.FullClusterRestartIT.testSnapshotRestore(FullClusterRestartIT.java:918)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/mvg/dev/projects/elasticsearch/7.x/qa/full-cluster-restart/build/testrun/v6.6.1#upgradedClusterTestRunner/J0/temp/org.elasticsearch.upgrades.FullClusterRestartIT_ACCA8891B511EDB8-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1610, maxMBSortInHeap=7.0941513110225145, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@739ed0f6), locale=pt, timezone=America/Danmarkshavn
  2> NOTE: Linux 4.15.0-45-generic amd64/Oracle Corporation 1.8.0_202 (64-bit)/cpus=12,threads=1,free=453279984,total=514850816
  2> NOTE: All tests run in this JVM: [FullClusterRestartIT]
Completed [1/1] in 2.55s, 1 test, 1 error <<< FAILURES!
```

### PR DESCRIPTION
**Pull request by cbuescher**
This test failed on 7.1 when running full cluster restart tests against pre-7.0
clusters (e.g. 6.6 clusters). The fix includes adding the "include_type_name"
parameter to the template requests only if the template uses types (if we are
testing restarts from pre-7 verions) and fixed the expected type in the
templates after the cluster restart (custom type names like "doc" which are
still possible e.g. in 6.6 are converted to "_doc" on post-7 clusters).

Closes #38603

### CODE REVIEW

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java [hunk 1]
```diff
@@ -911,7 +913,7 @@ public void testSnapshotRestore() throws IOException {
 
         // In 7.0, type names are no longer expected by default in put index template requests.
         // We therefore use the deprecated typed APIs when running against the current version, but testing with a pre-7 version
-        if (isRunningAgainstOldCluster() == false && getOldClusterVersion().major < 7) {
+        if (isRunningAgainstOldCluster() == false && templateUsesTypes) {
```
Comment (jtibshirani) [inline qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Is this just a refactor, or is this a necessary part of the fix as well? I'm having some trouble understanding.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java [hunk 2]
```diff
@@ -939,9 +941,10 @@ public void testSnapshotRestore() throws IOException {
         createSnapshot.setJsonEntity("{\"indices\": \"" + index + "\"}");
         client().performRequest(createSnapshot);
 
-        checkSnapshot("old_snap", count, getOldClusterVersion());
+        checkSnapshot("old_snap", count, oldClusterVersion, type);
         if (false == isRunningAgainstOldCluster()) {
-            checkSnapshot("new_snap", count, Version.CURRENT);
+            // we always expect the "_doc" type on 7.x clusters, even if the original pre-6.7 clusters type was "doc"
```
Comment (jtibshirani) [inline qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: I'm a little confused about this statement -- if a template is added with a custom type name, then on 7.x we should still return that custom type name if `include_type_name=true`. Would you be able to explain this fix in a bit more detail?

**Review by jtibshirani — COMMENTED** [review]
Thanks @cbuescher for working on fixing this. I left a couple questions to make sure I understand the approach.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java (hunk 1 above)
Comment (cbuescher) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Yes, just a refactor to make the whole version juggling easier to read. I introduced the flag earlier if the type is added to the template. I had some trouble understanding the code without it and found it worth being explicit here.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java (hunk 2 above)
Comment (cbuescher) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: This is the case when we are using "doc" in the old cluster (will e.g. happen on full restart from 6.6, see setType()). This part of the check creates a new snapshot on a _new_ cluster (>7.0) and has the "doc" in the template. To me it seems this gets converted in this case to "_doc" internally, so this is what we need to check. I will try to make the comment clearer here.

**Comment by cbuescher** [comment]
@jtibshirani thanks, I hope I was able to answer you questions and updated the comment a bit. Hope this is okay now.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java (hunk 1 above)
Comment (jtibshirani) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: 👍

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java (hunk 2 above)
Comment (jtibshirani) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: > To me it seems this gets converted in this case to "_doc" internally, so this is what we need to check.

I'm not sure why the custom type would get converted to `_doc` internally, I'm not aware of anywhere we would do that. I'll take some time to step through this test to try to understand what could be happening.

Comment (cbuescher) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: It doesn't get converted. But we (need to) use a typeless template when putting it on a "new" cluster, because we cannot add a custom type name on >7.0 anymore. See Line 881, (isRunningAgainstAncientCluster will be false here when we are running agains 7.0 or later versions).

**Comment by cbuescher** [comment]
@cbuescher I understand your confusion, I left a short explanation, let me know if I should elaborate on the comment further. I'm glad these edge cases are gone again on master.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java (hunk 2 above)
Comment (cbuescher) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Sorry, I didn't make this part clear after my last update. I don't think the comment in the code talks about "converting" but I certainly do im my above comment. Sorry if this was confusing, I didn't read the test that well back then.

Comment (jtibshirani) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: No problem, I think I now understand the intention of the test. I wonder if we could take the following simpler approach: https://github.com/jtibshirani/elasticsearch/commit/58dfb06729c9316933a543430119cce779b1a06e. I think the approach to handling 6.x versions in this was changed when we cut the 7.0 branch, but we never ended up removing these lines, which were part of the older approach.

Comment (cbuescher) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Good idea, I pushed an other commit.

**Comment by cbuescher** [comment]
@jtibshirani thanks, I pushed another commit with your latest suggestion so this is ready for a final look.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java [hunk 3]
```diff
@@ -859,11 +858,12 @@ public void testSnapshotRestore() throws IOException {
         // Stick a routing attribute into to cluster settings so we can see it after the restore
         Request addRoutingSettings = new Request("PUT", "/_cluster/settings");
         addRoutingSettings.setJsonEntity(
-                    "{\"persistent\": {\"cluster.routing.allocation.exclude.test_attr\": \"" + getOldClusterVersion() + "\"}}");
+                    "{\"persistent\": {\"cluster.routing.allocation.exclude.test_attr\": \"" + oldClusterVersion + "\"}}");
         client().performRequest(addRoutingSettings);
 
         // Stick a template into the cluster so we can see it after the restore
         XContentBuilder templateBuilder = JsonXContent.contentBuilder().startObject();
+        boolean templateUsesTypes = false;
```
Comment (jtibshirani) [inline qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: I think we can remove this variable, as it's now unused.

**Review by jtibshirani — APPROVED** [review]
Looks good to me.

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java (hunk 3 above)
Comment (cbuescher) [reply qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Gone.
