### PR TITLE
Prevent histogram from allocating tons of buckets

### LINKED ISSUE #71744: Histogram aggregation run with very small interval crashes Elasticsearch
**Elasticsearch version** 8.0.0-SNAPSHOT

Histogram aggregation run using a very small `interval` (found when using `e-10` and lower) crashes Elasticsearch.

For example, with documents added to an index created with the following mappings:

```
PUT /histogram_test
{
  "mappings": {
    "properties" : {
      "name" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
      "approval" : {
        "type" : "long"
      }
  }
}
```

And index 3 documents:
```
PUT /histogram_test/_doc/1?pretty
{
  "name" : "Pete",
  "approval": 87
}

PUT /histogram_test/_doc/2?pretty
{
  "name" : "William",
  "approval": 87
}

PUT /histogram_test/_doc/3?pretty
{
  "name" : "Sue",
  "approval": 88
}
```

Then try using the `histogram` aggregation with increasingly small `interval` values:

`"interval":5e-2` : returns results correctly
```
GET histogram_test/_search
{
   "query":{
      "match_all":{
         
      }
   },
   "aggs":{
            "1185244739_histogram":{
               "histogram":{
                  "field":"approval",
                  "interval":5e-2
               }
            }
         },
   "size":3
}
```

`"interval":5e-7` : returns sensible error:
```
{
  "error" : {
    "root_cause" : [ ],
    "type" : "search_phase_execution_exception",
    "reason" : "",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "too_many_buckets_exception",
      "reason" : "Trying to create too many buckets. Must be less than or equal to: [65536] but was [2000001]. This limit can be set by changing the [search.max_buckets] cluster level setting.",
      "max_buckets" : 65536
    }
  },
  "status" : 503
}
```

However when the interval is dropped to `"interval":5e-10`, Elasticsearch crashes with the following error:
```
Heap dump file created [1532782746 bytes in 4.312 secs]
[2021-04-15T14:08:29,995][INFO ][o.e.i.b.HierarchyCircuitBreakerService] [DESKTOP-3EDNC1M] attempting to trigger G1GC due to high heap usage [1021478296]
[2021-04-15T14:08:29,995][INFO ][o.e.i.b.HierarchyCircuitBreakerService] [DESKTOP-3EDNC1M] GC did not bring memory usage down, before [1021478296], after [1026921016], allocations [1], duration [0]
[2021-04-15T14:08:29,995][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [DESKTOP-3EDNC1M] fatal error in thread [elasticsearch[DESKTOP-3EDNC1M][search][T#4]], exiting
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3480) ~[?:?]
        at java.util.ArrayList.grow(ArrayList.java:237) ~[?:?]
        at java.util.ArrayList.grow(ArrayList.java:244) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:486) ~[?:?]
        at java.util.ArrayList$ListItr.add(ArrayList.java:1068) ~[?:?]
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.addEmptyBuckets(InternalHistogram.java:379) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.reduce(InternalHistogram.java:399) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:154) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:103) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:480) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:468) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.QueryPhaseResultConsumer.reduce(QueryPhaseResultConsumer.java:131) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:98) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:84) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
fatal error in thread [elasticsearch[DESKTOP-3EDNC1M][search][T#4]], exiting
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3480)
        at java.base/java.util.ArrayList.grow(ArrayList.java:237)
        at java.base/java.util.ArrayList.grow(ArrayList.java:244)
        at java.base/java.util.ArrayList.add(ArrayList.java:486)
        at java.base/java.util.ArrayList$ListItr.add(ArrayList.java:1068)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.addEmptyBuckets(InternalHistogram.java:379)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.reduce(InternalHistogram.java:399)
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:154)
        at org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:103)
        at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:480)
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:468)
        at org.elasticsearch.action.search.QueryPhaseResultConsumer.reduce(QueryPhaseResultConsumer.java:131)
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:98)
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:84)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

Ran into this issue with the data frame analytics results page in the ML Kibana plugin, which uses the `histogram` aggregation to plot histograms of the values of fields in the results data grid.

### PR DESCRIPTION
**Pull request by nik9000**
This prevents the `histogram` aggregation from allocating tons of empty
buckets when you set the `interval` to something tiny. Instead, we
reject the request. We're not in a place where we can aggregate over
huge ranges with tiny intervals, but we should fail gracefully when you
ask us to do so rather than OOM.

Closes #71744

### CODE REVIEW

**Comment by nik9000** [comment]
I suspect a similar bug hits `date_histogram`. But I can't be sure. If we like this solution here I can check it out for `date_histogram` as well.

**Comment by nik9000** [comment]
run elasticsearch-ci/2

**Comment by nik9000** [comment]
run elasticsearch-ci/2

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java [hunk 1]
```diff
@@ -347,56 +348,75 @@ private double round(double key) {
...
+            public void accept(double key) {
+                size++;
+                if (size >= 10000) {
+                    reduceContext.consumeBucketsAndMaybeBreak(size);
+                    size = 0;
+                }
+            }
+        }
+        Counter counter = new Counter();
+        iterateEmptyBuckets(list, list.listIterator(), counter);
```
Comment (not-napoleon) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java:364]: If I followed this correctly, this pass doesn't actually allocate the buckets, it just runs the maybe break check based on how many buckets we would allocate, and the call on line 371 does the actual allocation.  Presuming I followed that correctly, I think it's worth leaving a comment to that effect.  That seems to be the core of this fix, and it'd be good to remember why we're doing it this way.

**Review by not-napoleon — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java:364]: I'm happy to do that.

@imotov I'd love to hear from you too on this PR. To get two green check marks on this one.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java [hunk 2]
```diff
@@ -347,56 +348,75 @@ private double round(double key) {
...
 
     private void addEmptyBuckets(List<Bucket> list, ReduceContext reduceContext) {
-        ListIterator<Bucket> iter = list.listIterator();
+        class Counter implements DoubleConsumer {
+            private int size = list.size();
+
+            @Override
+            public void accept(double key) {
+                size++;
+                if (size >= 10000) {
```
Comment (imotov) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java:357]: I think this constant really needs an origin story, otherwise it makes the reader to wonder where it came from and if it is really meaningful. I wonder if it would make more sense to do something like DEFAULT_MAX_BUCKETS/10 with a brief explanation why this should work?

**Review by imotov — APPROVED** [review]
LGTM. Left a minor suggestion

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java (hunk 2 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalHistogram.java:357]: That should work, yeah. I'll leave a nice comment. We could just keep adding and never call the method but that'd make failures slow. An origin story it is!
