### PR TITLE
Fix InternalAutoDateHistogram reproducible failure

### LINKED ISSUE #32215: [CI] InternalAutoDateHistogramTests#testReduceRandom reproducable failure
Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/6700/console

Reproducable locally with this seed:
```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=6345BDE5AED7493F \
  -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests \
  -Dtests.method="testReduceRandom" \
  -Dtests.security.manager=true \
  -Dtests.locale=lv \
  -Dtests.timezone=HST
```

Error:
```
java.lang.AssertionError: expected:<{1532036050000=59, 1532036051000=58, 1532036052000=3, 1532036053000=71, 1532036054000=20, 1532036055000=48, 1532036110000=100, 1532036170000=49, 1532036230000=92}> but was:<{1532036050000=259, 1532036080000=0, 1532036110000=100, 1532036140000=0, 1532036170000=49, 1532036200000=0, 1532036230000=92}>
	at __randomizedtesting.SeedInfo.seed([6345BDE5AED7493F:A37811F4888AD069]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:107)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:45)
	at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
```

Other seeds seem to be okay, so I don't think the test needs to be muted right away.

### PR DESCRIPTION
**Pull request by pcsanwald**
Closes #32215. This PR addresses two issues:

1. Reproducible test failure outlined by @DaveCTurner in #32215:

```
./gradlew :server:test -Dtests.seed=55C6AF1793E2275B -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=en-IN -Dtests.timezone=Pacific/Chuuk
```

The problem here was a mistake in setting up the expected results: I had originally written the test setup to start with the _smallest_ possible `innerInterval` and try the larger ones, but the approach in the reduce method is to try the largest and step down. I've updated the logic to reflect this and run the test with `-Dtests.iters=200` to convince myself this won't cause a further failure.

2. In the course of tracking down the first problem, I've noticed what I believe is an actual bug in the auto interval implementation: instead of using the `maximumInnerInterval` of the _current_ rounding, we use the index of the initial rounding passed in.

To fix this, I've updated the logic and added a test case that fails using the old code path, and passes with the modified code path.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 1]
```diff
@@ -77,6 +79,22 @@ protected InternalAutoDateHistogram createTestInstance(String name,
         return new InternalAutoDateHistogram(name, buckets, targetBuckets, bucketInfo, format, pipelineAggregators, metaData);
     }
 
+    public void testGetAppropriateRounding() {
+        RoundingInfo[] roundings = new RoundingInfo[6];
+        DateTimeZone timeZone = DateTimeZone.UTC;
+        roundings[0] = new RoundingInfo(createRounding(DateTimeUnit.SECOND_OF_MINUTE, timeZone),
+            1000L, 1000);
```
Comment (pcsanwald) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: using a large innerInterval for the first rounding used by the function is important to trigger the problematic code path

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 2]
```diff
@@ -77,6 +79,22 @@ protected InternalAutoDateHistogram createTestInstance(String name,
...
+        roundings[1] = new RoundingInfo(createRounding(DateTimeUnit.MINUTES_OF_HOUR, timeZone),
+            60 * 1000L, 1, 5, 10, 30);
+        roundings[2] = new RoundingInfo(createRounding(DateTimeUnit.HOUR_OF_DAY, timeZone),
+            60 * 60 * 1000L, 1, 3, 12);
+
+        OffsetDateTime timestamp = Instant.parse("2018-01-01T00:00:01.000Z").atOffset(ZoneOffset.UTC);
+        int result = InternalAutoDateHistogram.getAppropriateRounding(timestamp.toEpochSecond()*1000,
+            timestamp.plusDays(1).toEpochSecond()*1000, 0, roundings, 25);
```
Comment (pcsanwald) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: we've also gotta start with an index that we know won't be used: to trigger the code path, the function needs to iterate past the first rounding.

**Comment by DaveCTurner** [comment]
On repeated runs I still see failures. For instance a run of 1000 iterations yielded this:

```
  Gradle Version        : 4.9
  OS Info               : Mac OS X 10.13.6 (x86_64)
  JDK Version (gradle)  : Oracle Corporation 10 [Java HotSpot(TM) 64-Bit Server VM 10+46]
  JAVA_HOME (gradle)    : /Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home
  JDK Version (compile) : Oracle Corporation 10 [Java HotSpot(TM) 64-Bit Server VM 10+46]
  JAVA_HOME (compile)   : /Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home
  JDK Version (runtime) : Oracle Corporation 1.8.0_144 [Java HotSpot(TM) 64-Bit Server VM 25.144-b01]
  JAVA_HOME (runtime)   : /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
  Random Testing Seed   : 6A6B58FA134BCB5D
...
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=21F8DDAAB657B52A -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.method="testReduceRandom { seed=[21F8DDAAB657B52A:D3C6326F8CF6C4B0]}" -Dtests.security.manager=true -Dtests.locale=zh-HK -Dtests.timezone=Indian/Mahe
FAILURE 0.01s | InternalAutoDateHistogramTests.testReduceRandom { seed=[21F8DDAAB657B52A:D3C6326F8CF6C4B0]} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<{1533765180000=53, 1533766980000=0, 1533768780000=3, 1533770580000=0, 1533772380000=2}> but was:<{1533762000000=53, 1533765600000=3, 1533769200000=2}>
   >  at __randomizedtesting.SeedInfo.seed([21F8DDAAB657B52A:D3C6326F8CF6C4B0]:0)
   >  at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:157)
   >  at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:45)
   >  at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:264)
   >  at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /Users/davidturner/src/elasticsearch-master/server/build/testrun/test/J0/temp/org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests_21F8DDAAB657B52A-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=191, maxMBSortInHeap=7.887615016643835, sim=RandomSimilarity(queryNorm=false): {}, locale=zh-HK, timezone=Indian/Mahe
  2> NOTE: Mac OS X 10.13.6 x86_64/Oracle Corporation 1.8.0_144 (64-bit)/cpus=8,threads=1,free=466868936,total=522190848
  2> NOTE: All tests run in this JVM: [InternalAutoDateHistogramTests]
```

I can reproduce this on the command line:

```
./gradlew :server:test -Dtests.seed=21F8DDAAB657B52A -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=zh-HK -Dtests.timezone=Indian/Mahe -Dtests.iters=1000
```

However I haven't been able to get this single case to reproduce.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 3]
```diff
@@ -28,17 +29,18 @@
...
-import java.util.ArrayList;
-import java.util.Collections;
-import java.util.HashMap;
-import java.util.List;
-import java.util.Map;
-import java.util.TreeMap;
+import java.time.Instant;
+import java.time.OffsetDateTime;
+import java.time.ZoneOffset;
+import java.util.*;
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: Jenkins is not amused. There's a setting in IntelliJ to avoid wildcard imports (at least until it hits an unreasonable number, I use 9999) and probably in other IDEs too.

**Comment by pcsanwald** [comment]
@DaveCTurner thanks for the review, I'll track down the failure. once more into the breach! :)

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 4]
```diff
@@ -77,6 +84,22 @@ protected InternalAutoDateHistogram createTestInstance(String name,
         return new InternalAutoDateHistogram(name, buckets, targetBuckets, bucketInfo, format, pipelineAggregators, metaData);
     }
 
+    public void testGetAppropriateRounding() {
```
Comment (colings86) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: This test seems to be testing a specific scenario rather than testing the method in general. Could we maybe make the name reflect this so its not assumed that its testing the method in general? Would it also be helpful to add a comment/javaDoc which explains the scenario it is testing?

**Review by colings86 — COMMENTED** [review]
I left a minor comment but I think the change looks good. I haven't approved the PR only because it looks like there is another failure that is being looked into as well here.

**Comment by pcsanwald** [comment]
I was able to reproduce the problem @DaveCTurner found reliably by adding the `@Seed("D3C6326F8CF6C4B0")` annotation to `InternalAggregationTestCase.testReduceRandom` and am pushing a fix to address.

**Comment by pcsanwald** [comment]
@DaveCTurner @colings86 this is ready (fingers crossed) for final review: I reproduced the failures and believe I have addressed them, and have run a bunch of `-Dtests.iters=1000` locally to convince myself this is reliable.

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java [hunk 5]
```diff
@@ -229,6 +230,7 @@ protected T createUnmappedInstance(String name,
         return createTestInstance(name, pipelineAggregators, metaData);
     }
 
+    @Seed("ED2D551807CFA25B")
```
Comment (colings86) [inline test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java]: I'm not sure you intend to commit this?

**Review by colings86 — APPROVED** [review]
The changes look good but it seems you left the `@Seed` annotation on the test which need to be removed but I also think it would be worth running a battery of test runs again to make sure there aren't more bugs lurking when the seed is removed. Assuming that battery of tests passes this LGTM

**Comment by DaveCTurner** [comment]
Removing the `@Seed` annotation, I still get failures:

```
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=E98A8421B3EA8CE8 -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.method="testReduceRandom { seed=[E98A8421B3EA8CE8:7264D28AC74663]}" -Dtests.security.manager=true -Dtests.locale=vo-001 -Dtests.timezone=Africa/Harare
FAILURE 0.00s | InternalAutoDateHistogramTests.testReduceRandom { seed=[E98A8421B3EA8CE8:7264D28AC74663]} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<{1533895200000=117}> but was:<{1533895200000=27, 1533906000000=90}>
   >    at __randomizedtesting.SeedInfo.seed([E98A8421B3EA8CE8:7264D28AC74663]:0)
   >    at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:168)
   >    at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:50)
   >    at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:264)
   >    at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by DaveCTurner** [comment]
If it helps, my preferred way to run lots of iterations of tests like this is the following:

```
date | tee pass-times.log; while ./gradlew --console=plain :server:test -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.iters=10000 2>&1 > testoutput.log; do date | tee -a pass-times.log; done
```

This runs the tests until they fail, capturing the log output, and tries different timezones and locales (which I guess to be important here) in a way that a single `./gradlew` run cannot.

**Comment by pcsanwald** [comment]
I've used @DaveCTurner's command as a test, and after running a bunch of local iterations, I believe this PR is ready for re-review. This proved quite tricky to get correct!

**Review by colings86 — APPROVED** [review]
LGTM. Thanks for beasting the tests @DaveCTurner and @pcsanwald

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogram.java [hunk 6]
```diff
@@ -480,7 +480,7 @@ private int getAppropriateRounding(long minKey, long maxKey, int roundingIdx,
                 currentKey = currentRounding.nextRoundingValue(currentKey);
             }
             currentRoundingIdx++;
-        } while (requiredBuckets > (targetBuckets * roundings[roundingIdx].getMaximumInnerInterval())
+            } while (requiredBuckets > (targetBuckets * roundings[currentRoundingIdx-1].getMaximumInnerInterval())
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogram.java]: Whitespace nit: indentation looks wrong, and spaces around the `-` sign?

**Review by DaveCTurner — APPROVED** [review]
LGTM - one nit about whitespace
