### PR TITLE
Fix AutoIntervalDateHistogram.testReduce random failures

### LINKED ISSUE #32215: [CI] InternalAutoDateHistogramTests#testReduceRandom reproducable failure
Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/6700/console

Reproducable locally with this seed:
```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=6345BDE5AED7493F \
  -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests \
  -Dtests.method="testReduceRandom" \
  -Dtests.security.manager=true \
  -Dtests.locale=lv \
  -Dtests.timezone=HST
```

Error:
```
java.lang.AssertionError: expected:<{1532036050000=59, 1532036051000=58, 1532036052000=3, 1532036053000=71, 1532036054000=20, 1532036055000=48, 1532036110000=100, 1532036170000=49, 1532036230000=92}> but was:<{1532036050000=259, 1532036080000=0, 1532036110000=100, 1532036140000=0, 1532036170000=49, 1532036200000=0, 1532036230000=92}>
	at __randomizedtesting.SeedInfo.seed([6345BDE5AED7493F:A37811F4888AD069]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:107)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:45)
	at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
```

Other seeds seem to be okay, so I don't think the test needs to be muted right away.

### PR DESCRIPTION
**Pull request by pcsanwald**
Closes #32215. Couple of bugs were uncovered during investigation:

1. `RoundingsInfo` were inconsistent between the test and implementation. To fix this, I refactored the tests to fetch roundings from the implementation.

2. In generating the expected result, the test was not correctly respecting innerIntervals in rounding. Since re-using the logic from the `AutoDateHistogramAggregator` is a fairly large refactor, I've replicated some of the logic in the `testReduce` method.

Can be reproduced using steps in #32215, I also tested a number of times with different seeds to convince myself I didn't break other things.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java [hunk 1]
```diff
@@ -63,6 +64,29 @@
         PARSER.declareInt(AutoDateHistogramAggregationBuilder::setNumBuckets, NUM_BUCKETS_FIELD);
     }
 
+    /**
+     *
+     * Build roundings, computed dynamically as roundings are time zone dependent.
+     * The current implementation probably should not be invoked in a tight loop.
+     * @return Array of RoundingInfo
+     */
+    RoundingInfo[] buildRoundings() {
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java]: Another thing we could do here (to avoid having to create an instance of the builder in the `InternalAutoDateHistogramTests`) is to make the signature here: `static RoundingInfo[] buildRoundings(DateTimeZone)` and then pass the time zone into it the method both in `innerBuild()` and in `InternalAutoDateHistogramTests`. We will also need to make `createRounding(DateTimeUnit, DateTimeZone)` static as well but thats fine I think.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 2]
```diff
@@ -51,14 +49,9 @@
...
-        roundingInfos = new RoundingInfo[6];
-        roundingInfos[0] = new RoundingInfo(Rounding.builder(DateTimeUnit.SECOND_OF_MINUTE).build(), 1, 5, 10, 30);
-        roundingInfos[1] = new RoundingInfo(Rounding.builder(DateTimeUnit.MINUTES_OF_HOUR).build(), 1, 5, 10, 30);
-        roundingInfos[2] = new RoundingInfo(Rounding.builder(DateTimeUnit.HOUR_OF_DAY).build(), 1, 3, 12);
-        roundingInfos[3] = new RoundingInfo(Rounding.builder(DateTimeUnit.DAY_OF_MONTH).build(), 1, 7);
-        roundingInfos[4] = new RoundingInfo(Rounding.builder(DateTimeUnit.MONTH_OF_YEAR).build(), 1, 3);
-        roundingInfos[5] = new RoundingInfo(Rounding.builder(DateTimeUnit.YEAR_OF_CENTURY).build(), 1, 10, 20, 50, 100);
+        AutoDateHistogramAggregationBuilder aggregationBuilder = new AutoDateHistogramAggregationBuilder("_name");
+        // TODO[PCS]: timezone set automagically here?
+        roundingInfos = aggregationBuilder.buildRoundings();
```
Comment (colings86) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: I'm actually not sure how the time zone would be picked up here which makes me think that its not being used currently and we are testing with only UTC at the moment so we probably need to fix that but we could do that in a follow up PR and just pass in UTC to create the roundings for this PR. I also think we need to create the roundings in `createTestInstance()` since because that method should be randomising the time zone the roundings may be different for each instance.

Comment (colings86) [reply server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: Looking at `InternalDateHistogramTeests` we don't seem to randomise the time zone there either which is probably why it was missed here. Not randomising the time zone there is less of a problem because the time zone is not used directly in `InternalDateHistogram`

**Review by colings86 — COMMENTED** [review]
@pcsanwald I left a few more comment but I think its close

**Comment by pcsanwald** [comment]
@colings86 I believe I've addressed your comments, this is ready for re-review.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 3]
```diff
@@ -49,16 +49,16 @@
...
-        // TODO[PCS]: timezone set automagically here?
-        roundingInfos = aggregationBuilder.buildRoundings();
     }
 
     @Override
     protected InternalAutoDateHistogram createTestInstance(String name,
                                                        List<PipelineAggregator> pipelineAggregators,
                                                        Map<String, Object> metaData,
                                                        InternalAggregations aggregations) {
+        AutoDateHistogramAggregationBuilder aggregationBuilder = new AutoDateHistogramAggregationBuilder("_name");
```
Comment (colings86) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: I don't think we need to create a builder here anymore. These tests don't currently set the time zone in the builder anyway so `aggregationBuilder.timeZone()` will always be `null` which implicitly means the time zone will be treated as UTC. As mentioned before we should add a test that does set the time zone to test its treated correctly but that doesn't need to be part of this PR so I think we can remove this line and just pass in `null` below?

**Review by colings86 — APPROVED** [review]
@pcsanwald I left one last small comment but otherwise this LGTM once the build passes

**Comment by colings86** [comment]
jenkins test this please

**Comment by colings86** [comment]
@pcsanwald I set off another build as the failure seemed to be with building artifacts for the bwc version and seems to be a transient failure to me

**Comment by pcsanwald** [comment]
@elasticmachine please test this

**Comment by pcsanwald** [comment]
@elasticmachine test this please

**Comment by pcsanwald** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
Just as FYI: We had a test failing on 6.x (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/1214/console) so I just wanted to ensure this gets backported to 6.x as well.

**Comment by pcsanwald** [comment]
@danielmitterdorfer I will backport today! had a few intermittent failures on this branch yesterday, hence the delay in merging.
