### PR TITLE
[Transform] Delete indices after test

### LINKED ISSUE #128577: [CI] TransformGetCheckpointIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8458 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/qzkfxltgnewlc)
- [elasticsearch-periodic-platform-support #8446 / windows-2019_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/ryuyjep6xn5zi)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.transform.checkpoint.TransformGetCheckpointIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.transform.checkpoint.TransformGetCheckpointIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.19] 2 failures in class org.elasticsearch.xpack.transform.checkpoint.TransformGetCheckpointIT (1.7% fail rate in 117 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by prwhelan**
The tests sometimes pass and then fail to clean up the indices indirectly, so they will now directly delete the indices they created for the test.

Fix #128577

### CODE REVIEW

File: x-pack/plugin/transform/src/internalClusterTest/java/org/elasticsearch/xpack/transform/checkpoint/TransformGetCheckpointIT.java [hunk 1]
```diff
@@ -98,25 +101,28 @@ public void testGetCheckpoint() throws Exception {
                 .filter(i -> i.getShardRouting().primary())
                 .sorted(Comparator.comparingInt(value -> value.getShardRouting().id()))
                 .mapToLong(s -> s.getSeqNoStats().getGlobalCheckpoint())
+                .filter(Objects::nonNull)
                 .sum(),
             checkpointSum
         );
+        deleteIndices(indices);
```
Comment (jonathan-buttner) [inline x-pack/plugin/transform/src/internalClusterTest/java/org/elasticsearch/xpack/transform/checkpoint/TransformGetCheckpointIT.java:108]: If the test fails will the `deleteIndices` still be called? Would it make sense to move these to an `After` method. I guess not all tests need to delete the indices, but maybe we could just ignore a failure on a delete attempt in that situation and always try to delete the indices.

**Review by jonathan-buttner — APPROVED** [review]
