### PR TITLE
[ML] Fixing inference stats race condition

### LINKED ISSUE #54786: [CI] InferenceIngestIT.testPipelineIngest occasionally fails
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/614/console

Build scan: https://gradle-enterprise.elastic.co/s/q4hcgpbmvcn3g

Failure:

```
java.lang.AssertionError: 

Expected: a string containing "\"inference_count\":10"
     but: was "{"count":1,"trained_model_stats":[{"model_id":"test_classification","pipeline_count":0,"inference_stats":{"failure_count":0,"inference_count":11,"missing_all_fields_count":0,"time_stamp":-9223372036854775808}}]}"

at __randomizedtesting.SeedInfo.seed([3274046E5719A7DD:90289258A5A9409E]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.InferenceIngestIT.lambda$testPipelineIngest$0(InferenceIngestIT.java:135)
``` 

Reproduce with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.InferenceIngestIT.testPipelineIngest" -Dtests.seed=3274046E5719A7DD -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=Asia/Jayapura -Dcompiler.java=13
```

I couldn't reproduce locally.

### PR DESCRIPTION
**Pull request by benwtrent**
`updateAndGet` could actually call the internal method more than once on contention.
If I read the JavaDocs, it says:
```* @param updateFunction a side-effect-free function```
So, it could be getting multiple updates on contention, thus having a race condition where stats are double counted.

To fix, I am going to use a `ReadWriteLock`. The `LongAdder` objects allows fast thread safe writes in high contention environments. These can be protected by the `ReadWriteLock::readLock`.

When stats are persisted, I need to call reset on all these adders. This is NOT thread safe if additions are taking place concurrently. So, I am going to protect with `ReadWriteLock::writeLock`.

This should prevent race conditions while allowing high (ish) throughput in the highly contention paths in inference.

I did some simple throughput tests and this change is not significantly slower and is simpler to grok (IMO).

closes  https://github.com/elastic/elasticsearch/issues/54786

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java [hunk 1]
```diff
@@ -226,24 +234,67 @@ public Accumulator merge(InferenceStats otherStats) {
...
+                readWriteLock.readLock().lock();
+                this.failureCountAccumulator.increment();
+                return this;
+            } finally {
+                readWriteLock.readLock().unlock();
+            }
         }
 
-        public InferenceStats currentStats() {
+        private InferenceStats currentStats() {
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java:266]: There is only one place where this method is called so I think it could be inlined there.

**Comment by benwtrent** [comment]
AGH!

I am doing something dumb somewhere:

```
java.lang.AssertionError: 
Expected: a string containing "\"inference_count\":10"
     but: was "{"count":1,"trained_model_stats":[{"model_id":"test_classification","pipeline_count":0,"inference_stats":{"failure_count":0,"inference_count":13,"missing_all_fields_count":0,"timestamp":1586877827960}}]}"
```

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java [hunk 2]
```diff
@@ -226,22 +234,52 @@ public Accumulator merge(InferenceStats otherStats) {
...
+        /**
+         * Thread safe.
+         *
+         * Returns the current stats and resets the values of all the counters.
+         * @return The current stats
+         */
+        public InferenceStats currentStatsAndReset() {
+            readWriteLock.writeLock().lock();
+            try {
+                InferenceStats stats = currentStats(Instant.now());
```
Comment (davidkyle) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java:275]: nit: make `public InferenceStats currentStats(Instant timeStamp)` private as it is only called here and not protected by the lock otherwise

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java [hunk 3]
```diff
@@ -44,16 +46,19 @@
 
     private static final String BASIC_AUTH_VALUE_SUPER_USER =
         basicAuthHeaderValue("x_pack_rest_user", SecuritySettingsSourceField.TEST_PASSWORD_SECURE_STRING);
+    private List<String> createdModels = new ArrayList<>();
 
     @Before
     public void createBothModels() throws Exception {
-        Request request = new Request("PUT", "_ml/inference/test_classification");
```
Comment (davidkyle) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java:50]: nit: rename method `createBothModels()`  -> `setLogging()` or `setup()` as no longer creating models here

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/AnalyticsProcessManager.java [hunk 4]
```diff
@@ -267,10 +266,6 @@ private void writeHeaderRecord(DataFrameDataExtractor dataExtractor, AnalyticsPr
         process.writeRecord(headerRecord);
     }
 
-    private void indexDataCounts(DataCounts dataCounts) {
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/AnalyticsProcessManager.java:270]: 👍

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java [hunk 5]
```diff
@@ -97,11 +103,26 @@ public void beforeStop() {
...
+            }
+            return;
+        }
         statsQueue.compute(InferenceStats.docId(stats.getModelId(), stats.getNodeId()),
             (k, previousStats) -> previousStats == null ?
                 stats :
                 InferenceStats.accumulator(stats).merge(previousStats).currentStats(stats.getTimeStamp()));
+        if (flush) {
+            threadPool.executor(MachineLearning.UTILITY_THREAD_POOL_NAME).execute(this::updateStats);
+        }
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:125]:
```suggestion
        if (stats.hasStats()) {        
            statsQueue.compute(InferenceStats.docId(stats.getModelId(), stats.getNodeId()),
                (k, previousStats) -> previousStats == null ?
                    stats :
                    InferenceStats.accumulator(stats).merge(previousStats).currentStats(stats.getTimeStamp()));
        }        
        if (flush) {
            threadPool.executor(MachineLearning.UTILITY_THREAD_POOL_NAME).execute(this::updateStats);
        }
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java [hunk 6]
```diff
@@ -97,11 +103,26 @@ public void beforeStop() {
...
+    /**
+     * Queues the stats for storing.
+     * @param stats The stats to store or increment
+     * @param flush When `true`, this indicates that stats should be written as soon as possible.
+     *              If `false`, stats are not persisted until the next periodic persistence action.
+     */
+    public void queueStats(InferenceStats stats, boolean flush) {
+        if (stats.hasStats() == false) {
+            if (flush) {
+                threadPool.executor(MachineLearning.UTILITY_THREAD_POOL_NAME).execute(this::updateStats);
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:115]: 2 threads could be calling this method at the same time, one invoked here and the other from the the scheduler. Is that safe? Both threads will be iterating and removing entries from the map, maybe use an iterator on the entrySet

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:115]: It should be safe. I make a copy of the entry set and iterate removals. If the key does not exist, it would return `null`. So, only one of the two threads would end up having the update.

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java (hunk 3 above)
Comment (benwtrent) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java:50]: yep yep!

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java:275]: It is called in the stats persister when merging stats. 

I will add a comment about it not being thread safe.

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/InferenceStats.java:275]: Actually, it is thread safe and it is used in the stats service.

getting the `longValue` without resetting is perfectly safe. Its guaranteed to get the latest count on the stats. 

And since where it is used, no more updates are occurring, it should be safe.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java (hunk 6 above)
Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:115]: More verbose reply. 

The iteration code is here:
```
Set<String> keys = new HashSet<>(statsQueue.keySet());
for(String k : keys) {
    InferenceStats inferenceStats = statsQueue.remove(k);
    if (inferenceStats != null) {
        stats.add(inferenceStats);
    }
}
```
This gets the latest known view of the keySet and makes a copy. This way if keys are added AFTER the remove, it does not double count the stats (I think the keySet view is updated when keys are added...so I opted to not use it directly in iteration).

concurrent map `remove` is thread safe. So if one thread removes an item from the hashmap, the other thread won't see it and get `null`. So, it won't add it to its request payload.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/loadingservice/LocalModelTests.java [hunk 7]
```diff
@@ -273,7 +274,7 @@ public void testInferPersistsStatsAfterNumberOfCalls() throws Exception {
             public boolean matches(Object o) {
                 return ((InferenceStats)o).getInferenceCount() == 99L;
             }
-        }));
+        }),anyBoolean());
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/loadingservice/LocalModelTests.java:277]:
```suggestion
        }), anyBoolean());
```

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java [hunk 8]
```diff
@@ -64,19 +68,33 @@ protected Settings restClientSettings() {
...
+            "    }" +
+            "}");
+        client().performRequest(loggingSettings);
         ESRestTestCase.waitForPendingTasks(adminClient());
-        client().performRequest(new Request("DELETE", "_ml/inference/test_classification"));
-        client().performRequest(new Request("DELETE", "_ml/inference/test_regression"));
     }
 
     public void testPathologicalPipelineCreationAndDeletion() throws Exception {
+        String classificationModelId = "test_pathalogical_classification";
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java:85]: s/pathalogical/pathological/

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java [hunk 9]
```diff
@@ -153,12 +175,47 @@ void updateStats() {
...
+        }
         resultsPersisterService.bulkIndexWithRetry(bulkRequest,
             stats.stream().map(InferenceStats::getModelId).collect(Collectors.joining(",")),
             () -> stopped == false,
             (msg) -> {});
     }
 
+    private static boolean verifyIndicesPrimaryShardsAreActive(ClusterState clusterState, IndexNameExpressionResolver expressionResolver) {
+        String[] indices = expressionResolver.concreteIndexNames(clusterState,
+            new IndicesOptions(
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:189]: I think you could replace it with `IndicesOptions.LENIENT_EXPAND_OPEN_HIDDEN`

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java (hunk 6 above)
Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java]: 👍 it was the double removal I was worried about

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java [hunk 10]
```diff
@@ -94,13 +112,29 @@ public void testPathologicalPipelineCreationAndDeletion() throws Exception {
...
         assertThat(EntityUtils.toString(searchResponse.getEntity()), containsString("\"value\":10"));
+        assertBusy(() -> {
+            try {
+                Response statsResponse = client().performRequest(new Request("GET",
+                    "_ml/inference/" + classificationModelId + "/_stats"));
+                assertThat(EntityUtils.toString(statsResponse.getEntity()), containsString("\"inference_count\":10"));
+                statsResponse = client().performRequest(new Request("GET", "_ml/inference/" + regressionModelId + "/_stats"));
+                assertThat(EntityUtils.toString(statsResponse.getEntity()), containsString("\"inference_count\":10"));
+            } catch (ResponseException ex) {
+                //this could just mean shard failures.
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java:123]: Shouldn't this "catch" clause call "Assert.fail()"?
If it doesn't I think the whole block won't be retried when the `ResponseException` happens...

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
