### PR TITLE
Fix reindex with transport client

### LINKED ISSUE #19979: Reindex cancel and status don't work via transport client
We recently moved the registration of named writeables to pull approach. The task status named writeables were left out of this refactoring and should be migrated as well. As a result, transport client doesn't see the `BulkByScrollTask.Status` as its registration happens in `NetworkModule` after the transport client pulled all the named writeables during its initialization.

I guess we want to create a TaskPlugin interface like we have done with SearchPlugin, ActionPlugin etc.

### PR DESCRIPTION
**Pull request by nik9000**
Fixes reindex's status requests through the transport client and reworks `ListTasksResponse` so its `toString` isn't breaky with the transport client.

Reworks #19773
Closes #19979

### CODE REVIEW

**Comment by nik9000** [comment]
@dadoonet, the bulk of this reworks some changes you made because they didn't play well with the transport client. Can you have a look?

**Comment by nik9000** [comment]
Looks like @dadoonet can't review it for a while. So, anyone else want it?

**Comment by nik9000** [comment]
@elasticmachine, retest this

**Comment by nik9000** [comment]
Test failure is caused by the branch point, not the change itself.

**Comment by nik9000** [comment]
> Test failure is caused by the branch point, not the change itself.

Rebased. That should help.

File: core/src/test/java/org/elasticsearch/common/network/NetworkModuleTests.java [hunk 1]
```diff
@@ -41,11 +33,12 @@
 import org.elasticsearch.rest.RestChannel;
 import org.elasticsearch.rest.RestRequest;
 import org.elasticsearch.rest.action.cat.AbstractCatAction;
-import org.elasticsearch.tasks.Task;
 import org.elasticsearch.test.transport.AssertingLocalTransport;
 import org.elasticsearch.transport.Transport;
 import org.elasticsearch.transport.TransportService;
 
+import java.util.Collections;
```
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/common/network/NetworkModuleTests.java]: No code was added to this test class, only removed, so is this added import necessary?

Comment (abeyad) [inline core/src/test/java/org/elasticsearch/common/network/NetworkModuleTests.java]: Nevermind, I see, it was a remnant from the imports up top, just got shifted around

**Comment by abeyad** [comment]
LGTM

**Comment by nik9000** [comment]
Merged! Thanks @abeyad !
