### PR TITLE
[ML] fix updating opened jobs scheduled events (#31651)

### LINKED ISSUE #31651: [ML] Adding an open job to a group does not update autodetect with related scheduled events
Steps to reproduce:

1. Create a calendar with a scheduled event
2. Add a new job group to the calendar
3. Create a job and open it. In the UI this is achieved by creating the job but not starting the datafeed
4. Edit the job to add it to the new group
5. Run the job and see that is has not picked up the calendar associated with the group

The problem is that updating the job with a group does not update autodetect with scheduled events.

cc @pheyos

### PR DESCRIPTION
**Pull request by benwtrent**
Addresses issue #31651 

Now, if there is a group update, we alert that the scheduled events for the job should be updated as well.

Closes #31651

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/autodetect/UpdateParamsTests.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+            .setModelPlotConfig(new ModelPlotConfig())
+            .setDetectorUpdates(detectorUpdates);
+
+        UpdateParams params = UpdateParams.fromJobUpdate(updateBuilder.build());
+
+        assertFalse(params.isUpdateScheduledEvents());
+        assertEquals(params.getDetectorUpdates(), updateBuilder.build().getDetectorUpdates());
+        assertEquals(params.getModelPlotConfig(), updateBuilder.build().getModelPlotConfig());
+
+        updateBuilder.setGroups(Arrays.asList("bar"));
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/autodetect/UpdateParamsTests.java]: nit: Why not call this earlier where the rest of the update is built? There is no reason to separate the groups from this test's perspective.

**Review by dimitris-athanasiou — COMMENTED** [review]
Looks good. However, it would be great to add an integration test for this. Take a look at ScheduledEventsIT.testOnlineUpdate. I think we could add a similar test for this particular case.

File: x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java [hunk 2]
```diff
@@ -257,6 +259,81 @@ public void testOnlineUpdate() throws Exception {
         assertEquals(0, buckets.get(8).getScheduledEvents().size());
     }
 
+    /**
+     * An open job that later gets added to a calendar, should take the scheduled events into account
+     */
+    public void testUpdatingOpenedJob() throws Exception {
```
Comment (dimitris-athanasiou) [inline x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java]: We now have 2 tests that deal with online updates. The old one is testing online updates with regard to adding events to a calendar. This one tests online updates with regard to adding the job to a group for which there's calendars. How about we rename those tests to reflect that? `testOnlineUpdate` -> `testAddEventsToOpenJob` and `testUpdatingOpenedJob` -> `testAddOpenedJobToGroupWithCaldendar` are some suggestive names but if you have better ideas go for it.

File: x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java [hunk 3]
```diff
@@ -257,6 +259,81 @@ public void testOnlineUpdate() throws Exception {
...
+        TimeValue bucketSpan = TimeValue.timeValueMinutes(30);
+        String groupName = "opened-calendar-job-group";
+        Job.Builder job = createJob("scheduled-events-open-update", bucketSpan);
```
Comment (dimitris-athanasiou) [inline x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java]: Note that in all those integ-tests we try to name the job after the class/test itself. We found in the past that makes it easier to debug a failed test. Could you please adjust according to the final test name?

**Review by dimitris-athanasiou — COMMENTED** [review]
Thanks, that's a cool test! Left some comments regarding naming.

File: x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java]: The two hardest problems in software development:

* Cache invalidation
* Naming things

:D

File: x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java (hunk 3 above)
Comment (benwtrent) [reply x-pack/qa/ml-native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/ScheduledEventsIT.java]: definitely

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM (assuming we get a green build)

**Comment by benwtrent** [comment]
Jenkins retest this please

**Comment by benwtrent** [comment]
@elasticmachine retest this please

**Comment by benwtrent** [comment]
rerun the gradle build tests

**Comment by benwtrent** [comment]
retest this please
