### PR TITLE
ESQL: Assert no partial results in integration tests

### LINKED ISSUE #129256: ESQL: Bugs don't show up in test failures, only in logs
Since we've switched to `allow_partial_failures=true` by default, bugs are not immediately reported when they cause a csv spec test or yaml test to fail. All we see in opened CI issues is a data mismatch, typically with fewer data in the results than expected. Then we need to dig in the logs to find the actual root cause - if it was logged.

To regain proper visibility, we should update EsqlSpecTestCase so that it asserts no partial failures in the result. And do something similar for yaml tests.

### PR DESCRIPTION
**Pull request by bpintea**
This injects assertions in spec-based and YAML integration tests that the received results aren't partial. 
This only happens in case the tests themselves don't set `"allow_partial_results": true`.

Closes #129256

### CODE REVIEW

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java [hunk 1]
```diff
@@ -273,6 +273,9 @@ protected final void doTest(String query) throws Throwable {
         Map<?, ?> prevTooks = supportsTook() ? tooks() : null;
         Map<String, Object> answer = runEsql(builder.query(query), testCase.assertWarnings(deduplicateExactWarnings()));
 
+        var isPartial = answer.get("is_partial");
+        assertTrue("unexpected partial results", isPartial == null || (boolean) isPartial == false);
```
Comment (nik9000) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java]: Might be easier to read with `assertThat(..., anyOf(is(false), nullValue()))`. Dunno. Your call.

File: x-pack/plugin/esql/qa/server/single-node/src/yamlRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/AbstractEsqlClientYamlIT.java [hunk 2]
```diff
@@ -72,6 +81,33 @@ public static Iterable<Object[]> updateEsqlQueryDoSections(Iterable<Object[]> pa
...
+
+    private static List<ExecutableSection> insertPartialResultsAssertion(List<ExecutableSection> sections) {
+        var newSections = new ArrayList<ExecutableSection>(sections.size());
+        for (var section : sections) {
+            var insertIsPartial = false;
+            if (section instanceof DoSection doSection) {
+                var apiCallSection = doSection.getApiCallSection();
+                if (apiCallSection.getApi().equals("esql.query")) {
+                    // If `allow_partial_results` is explicitly set to true, partial results are allowed.
+                    // If it's missing, no partial results are expected, even if the parameter's default is true.
```
Comment (nik9000) [inline x-pack/plugin/esql/qa/server/single-node/src/yamlRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/AbstractEsqlClientYamlIT.java:99]: It's a bit of magic, I think it's a pretty reasonable sacrifice.

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java [hunk 3]
```diff
@@ -273,6 +273,9 @@ protected final void doTest(String query) throws Throwable {
...
+
```
Comment (dnhatn) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java:282]: nit: can we also extract the failures and throw them?

**Review by dnhatn — APPROVED** [review]
Thanks so much, @bpintea. I wonder if we should also do this for other QA modules (multi-node, multi-nodes, mixed-cluster).

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java]: Yes, better, thanks.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java:282]: Good idea, I've extracted `_clusters` contents into the assertion message (we don't have more otherwise).

**Comment by bpintea** [comment]
> I wonder if we should also do this for other QA modules (multi-node, multi-nodes, mixed-cluster).

The changes apply to those suites too.

**Comment by bpintea** [comment]
Thanks Nik and Nhat.
