### PR TITLE
Fix broken MvPSeriesWeightedSum tests

### LINKED ISSUE #111479: [CI] MvPSeriesWeightedSumTests testFold {TestCase=<double>, <double>} failing
**Build Scans:**
- [elasticsearch-periodic #3618 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/gk6d6ynvtlgxm)
- [elasticsearch-pull-request #26933 / part-3](https://gradle-enterprise.elastic.co/s/4fm3jelo6en2q)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvPSeriesWeightedSumTests.testFold {TestCase=<double>, <double>}" -Dtests.seed=E0EDE21D2F2E0F3B -Dtests.locale=en-GB -Dtests.timezone=Etc/GMT-10 -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testFold%20%7BTestCase%3D%3Cdouble%3E%2C%20%3Cdouble%3E%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvPSeriesWeightedSumTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a numeric value within <1.0E-8> of <1.3186357871279523E8>
     but: <1.3186357871279521E8> differed by <4.901161193847656E-9> more than delta <1.0E-8>
```

**Issue Reasons:**
- [main] 2 failures in test testFold {TestCase=<double>, <double>} (13.3% fail rate in 15 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by machadoum**
Fix flaky MvPSeriesWeightedSumTests test https://github.com/elastic/elasticsearch/issues/111479#issue-2439956189

It increases the assertion delta and updated `muted-tests.yml`

Resolves #111479 and #111498

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvPSeriesWeightedSumTests.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ private static void doubles(List<TestCaseSupplier> cases) {
                 ),
                 "MvPSeriesWeightedSumDoubleEvaluator[block=Attribute[channel=0], p=" + p + "]",
                 DataType.DOUBLE,
-                closeTo(calcPSeriesWeightedSum(field, p), 0.00000001)
+                closeTo(calcPSeriesWeightedSum(field, p), .00001)
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvPSeriesWeightedSumTests.java:58]: I wonder if this should be instead something like:
```suggestion
                closeTo(expectedResult, expectedResult * .00000001)
```
As Double precision depends on its exponent, and from what I see, [Hamcrest](https://github.com/hamcrest/JavaHamcrest/blob/master/hamcrest/src/main/java/org/hamcrest/number/IsCloseTo.java#L46) doesn't take care of it.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvPSeriesWeightedSumTests.java
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvPSeriesWeightedSumTests.java:1]: Slightly unrelated, but just found it here: that `List<Double> field = randomList(1, 10, () -> randomDouble());`.

`randomDouble()` returns a double between 0.0 and 1.0, not any double. I got fooled by its name many times already.
Related with the other comment, as we're just testing with small numbers here. If we get bigger numbers, I guess it's because of `p`.

Maybe not for this PR, as it will require also catching potential +/-Infinites from overflows. So as you consider

**Review by ivancea — COMMENTED** [review]
It's interesting that we don't have this problem in other places, unless we're using something other than `closeTo()`.
Only found another case where we apply an error derived from the value: https://github.com/elastic/elasticsearch/blob/4bf3fc30451ff22985dfd181742bb3e0fe8f1433/x-pack/plugin/spatial/src/internalClusterTest/java/org/elasticsearch/xpack/spatial/search/aggregations/metrics/CartesianCentroidIT.java#L74

Anyway, I'm curious of what others think of this approach

**Comment by machadoum** [comment]
I updated the random values range to be more realistic and readable.
field = 1 = > 10
p = -10 => 10

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvPSeriesWeightedSumTests.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvPSeriesWeightedSumTests.java:58]: I think that's probably a good call, yeah.

**Review by nik9000 — APPROVED** [review]
I think @ivancea 's proposal is worth it. Both of them are, actually. But I'd be ok grabbing then in a follow up though.

You can't use `TestCaseSupplier.doubleCases` directly because it doesn't do multivalued fields, but it comes up with a few classes of doubles. And the maximually paranoid thing is to try all of those classes here too. It's probably fine not to, but paranoia is useful for this. I would wait for a follow up for it though.

The classes:
* between 0 and 1
* between -1 and 0
* between 1 and Double.MAX_VALUE
* between -Double.MAX_VALUE and 1 (note Double.MIN_VALUE is a small *magnitude* number. not a large magnitude negative number. The constant's name is weird.)

**Comment by machadoum** [comment]
Hey, Thank you for the review!

I added  @ivancea 's proposal and limited the test scenario to more realistic values. 
I will address edge-case scenarios on another PR.

> between 0 and 1
> between -1 and 0
> between 1 and Double.MAX_VALUE
> between -Double.MAX_VALUE and 1 (note Double.MIN_VALUE is a small magnitude number. not a large magnitude negative number. The constant's name is weird.)

**Review by ivancea — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]

**Review by ivancea — APPROVED** [review]
