### PR TITLE
Ensure GCS Repository Metadata Blob Writes are Atomic

### LINKED ISSUE #72018: OOME during GCP upload resulted in creation of empty blob
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.1

**Plugins installed**: Cloud

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

The master node reported an OOME while writing the `RepositoryData` blob at `2021-03-17T04:30:56.129`. However it apparently created an empty blob rather than failing outright:

image

This rendered the repository unusable: an empty blob is not valid at this location.

**Provide logs (if relevant)**:

The stack trace from an OOME is often not an indication of the reason for the OOME, but in this case it does indicate we were writing the repository data at the time.

```
[instance-0000000001] fatal error in thread [elasticsearch[instance-0000000001][snapshot][T#1]], exiting
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3536) ~[?:?]
	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:135) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$1.lambda$write$0(GoogleCloudStorageBlobStore.java:280) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$1$$Lambda$7716/0x000000080213a840.run(Unknown Source) ~[?:?]
	at java.security.AccessController.executePrivileged(AccessController.java:784) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:554) ~[?:?]
	at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$1.write(GoogleCloudStorageBlobStore.java:280) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:74) ~[?:?]
	at java.nio.channels.Channels.writeFully(Channels.java:97) ~[?:?]
	at java.nio.channels.Channels$1.write(Channels.java:172) ~[?:?]
	at org.elasticsearch.common.io.Streams.doCopy(Streams.java:100) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.io.Streams.copy(Streams.java:92) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobResumable(GoogleCloudStorageBlobStore.java:275) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:238) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:82) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlobAtomic(GoogleCloudStorageBlobContainer.java:87) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeAtomic(BlobStoreRepository.java:1786) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$54(BlobStoreRepository.java:1580) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$$Lambda$6993/0x0000000802035440.accept(Unknown Source) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:226) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ListenableFuture$$Lambda$4550/0x0000000801b1a840.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1510) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:62) ~[elasticsearch-7.9.1.jar:7.9.1]
```

### PR DESCRIPTION
**Pull request by original-brownbear**
In the corner case of uploading a large (>5MB) metadata blob we did not set content validation
requirement on the upload request (we automatically have it for smaller requests that are not resumable
uploads). This change sets the relevant request option to enforce a MD5 hash check when writing
`BytesReference` to GCS (as is the case with all but data blob writes)

closes #72018

### CODE REVIEW

File: plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 1]
```diff
@@ -217,12 +218,33 @@ InputStream readBlob(String blobName, long position, long length) throws IOExcep
...
+    void writeBlob(String blobName, BytesReference bytes, boolean failIfAlreadyExists) throws IOException {
+        if (bytes.length() > getLargeBlobThresholdInBytes()) {
+            // Compute crc32c here so #writeBlobResumable forces the integrity check on the resumable upload.
+            // This is needed since we rely on atomic write behavior when writing BytesReferences in BlobStoreRepository which is not
+            // guaranteed for resumable uploads.
+            writeBlobResumable(
+                BlobInfo.newBuilder(bucketName, blobName).setCrc32c(Crc32C.checksum(bytes)).build(),
+                bytes.streamInput(), bytes.length(), failIfAlreadyExists);
+        } else {
+            writeBlob(blobName, bytes.streamInput(), bytes.length(), failIfAlreadyExists);
```
Comment (original-brownbear) [inline plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java:233]: No need to do any manual shenanigans here, the normal non-resumable upload path will is not affected by the issue since it always sets checksum validation on the upload.

File: plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/Crc32C.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+import org.elasticsearch.common.bytes.BytesReference;
+
+import java.io.IOException;
+import java.util.Base64;
+
+/**
+ * CRC32C implementation to compute a checksum for resumable GCS uploads.
+ * TODO: Move to java.util.zip.CRC32C instead of this custom implementation once we no longer need to support JDK-8
+ */
+public final class Crc32C {
```
Comment (original-brownbear) [inline plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/Crc32C.java:22]: Google recommends using crc32 over md5 so I went with this (MD5 isn't available for all objects, and while it seems that we never create an object that doesn't have an md5 this seemed safer).

Comment (original-brownbear) [reply plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/Crc32C.java:22]: Converting to draft for a bit until I had the chance to double check the above assumption. Maybe MD-5 and thus keeping it simple works for us in all cases after all ...

**Review by DaveCTurner — COMMENTED** [review]
Looks good, and yes either CRC32 or MD5 is fine for this purpose but I'd much rather use a built-in implementation.

---

edit: CRC32 is technically slightly worse, it doesn't distinguish all-zero files of different lengths for instance, but that doesn't really matter for us.

**Comment by original-brownbear** [comment]
@DaveCTurner jup lets go with MD5 :) Only thing left here is fixing the encrypted repository that passes us a stream here instead of a `BytesReference` in this spot. On it coding up a fix :)

**Comment by DaveCTurner** [comment]
Is there any way we can verify that this works against the real GCS, i.e. that aborting an upload for some reason doesn't generate the corresponding blob? I worry that we might lose this fix in a future refactoring and/or not have covered all the different possibilities here.

**Comment by original-brownbear** [comment]
> Is there any way we can verify that this works against the real GCS, i.e. that aborting an upload for some reason doesn't generate the corresponding blob? I worry that we might lose this fix in a future refactoring and/or not have covered all the different possibilities here.

I thought about this. The problem is, covering all possibilities is tricky to test. In the end, as long as the md5Hash field in the request body behaves as claimed by Google the assertion I added should cover all expected cases (our repo tests do in fact have 100% coverage of all the possible upload paths in the GCS blob store class). I suppose it would be nice to verify this with a tricky test against real GCS where we kill the upload mid-way, but other than surfacing GCS misbehavior we're not easily going to get more coverage than with the existing unless we find some not-yet-covered upload path in the logic?

**Comment by original-brownbear** [comment]
@DaveCTurner this should be good for review now. Not sure about enhancing the test (see above comment) it seems the effort vs coverage improvement isn't necessarily worth it relative to the assertion added here but let's see what you think :)

**Review by DaveCTurner — APPROVED** [review]
Acked, yes, LGTM. Maybe something to add to the repository analyser instead -- particularly we are relying on random "S3-compatible" implementations doing the right thing with an upload that didn't complete.

**Comment by original-brownbear** [comment]
Thanks David!
