### PR TITLE
Only allow rebalance operations to run if all shard store data is available

### LINKED ISSUE #14387: Shards relocating during rolling restarts
This behaviour is reproducible in v1.6.0 through 2.0.0.  

Expected during rolling restarts that no shard relocations will occur, however there is shard movement occurring while the cluster is in a yellow health state.  

Steps to reproduce:
 1. Create a cluster with at least 3 nodes, 1 index with 2 shards + 1 replica (4 shards total), and index some data.
 2. Stop all indexing
 3. Set allocation: none
 4. _all/_flush/synced
 5. restart a single node
 6. reenable allocation

At step 6, shards are observed to be relocating, in addition to any recovery by sync_id that has occurred.  After recoveries and relocations, the cluster will change to green state.  This was tested in slow motion by limiting bandwidth to one of the nodes in the cluster.

Relocations are **not** observed in a 2 node cluster, or when restarting the entire cluster.

### PR DESCRIPTION
**Pull request by s1monw**
This commit prevents running rebalance operations if the store allocator is
still fetching async shard / store data to prevent pre-mature rebalance decisions
which need to be reverted once shard store data is available. This is typically happening
on rolling restarts which can make those restarts extremely painful.

Closes #14387

### CODE REVIEW

**Comment by s1monw** [comment]
I tried to implement this with the least impact possible code wise to safely backport to 1.7

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocators.java [hunk 1]
```diff
@@ -76,7 +76,20 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
 
     @Override
     public boolean rebalance(RoutingAllocation allocation) {
-        return allocator.rebalance(allocation);
+        final int numberOfInFlightFetch = gatewayAllocator.getNumberOfInFlightFetch();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocators.java]: I *think* we have a race condition here where the gateway's requests have come back before we got here on the cluster state update thread. The in flight ops will be 0 but the results are not used yet. I wonder if we should have a flag on the allocation, something like "disableRebalance" which we can set in the gateway allocator. Maybe that will be simpler?

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/ClusterRebalanceRoutingTests.java [hunk 2]
```diff
@@ -624,4 +625,72 @@ public void testClusterAllActive3() {
...
+        }
+
+        logger.debug("now, start 1 more node, check that rebalancing will not happen since we have shard sync going on");
+        clusterState = ClusterState.builder(clusterState).nodes(DiscoveryNodes.builder(clusterState.nodes())
+                .put(newNode("node2")))
+                .build();
+
+        RoutingAllocation.Result reroute = strategy.reroute(clusterState);
+        assertFalse(reroute.changed());
+        numFetch.set(0);
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/ClusterRebalanceRoutingTests.java]: can we insert an extra log message here? I misses the `strategy.reroute(clusterState);` at first read and it drove me nuts - why is there a relocating shard? ;)

**Comment by s1monw** [comment]
@bleskes I pushed a new commit

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocators.java [hunk 3]
```diff
@@ -76,7 +76,19 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
+            /*
+             * see https://github.com/elastic/elasticsearch/issues/14387
+             * if we allow rebalance operations while we are still fetching shard store data
+             * we might end up with unnecessary rebalance operations which can be super confusion/frustrating
+             * since once the fetches come back we might just move all the shards back again.
+             * Therefore we only do a rebalance if we have fetched all information.
+             */
+            return allocator.rebalance(allocation);
+        } else {
+            logger.debug("skip rebalance more that on shard/store fetch operations is still in-flight");
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocators.java]: "skipping rebalance due to in-flight shard/store fetches" ?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocators.java [hunk 4]
```diff
@@ -76,7 +76,19 @@ public boolean allocateUnassigned(RoutingAllocation allocation) {
...
+        }
+        return false;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocators.java]: nitpick - can we moe the return under the else clause?

File: core/src/main/java/org/elasticsearch/gateway/ReplicaShardAllocator.java [hunk 5]
```diff
@@ -186,6 +187,7 @@ public boolean allocateUnassigned(RoutingAllocation allocation, long allocateUna
                      * see {@link org.elasticsearch.cluster.routing.RoutingService#clusterChanged(ClusterChangedEvent)}).
                      */
                     changed = true;
+                    allocation.setHasPendingAsyncFetch();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/gateway/ReplicaShardAllocator.java]: I'm not sure this one is correct? If we got here it means we know everything about the current nodes, but couldn't find a  (good) copy. Strictly speaking, we don't have an inflight async fetch. Also , I think it's OK to rebalance here?

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/ClusterRebalanceRoutingTests.java [hunk 6]
```diff
@@ -624,4 +627,92 @@ public void testClusterAllActive3() {
...
+        });
+
+        MetaData metaData = MetaData.builder()
+                .put(IndexMetaData.builder("test").settings(settings(Version.CURRENT)).numberOfShards(2).numberOfReplicas(0))
+                .put(IndexMetaData.builder("test1").settings(settings(Version.CURRENT).put(FilterAllocationDecider.INDEX_ROUTING_EXCLUDE_GROUP + "_id", "node1,node2")).numberOfShards(2).numberOfReplicas(0))
+                .build();
+
+        RoutingTable routingTable = RoutingTable.builder()
+                .addAsNew(metaData.index("test"))
+                .addAsNew(metaData.index("test1"))
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/ClusterRebalanceRoutingTests.java]: can we add a note about why we need a test1?

**Comment by bleskes** [comment]
looks great. Left one minor comment in ReplicaShardAllocator

**Comment by s1monw** [comment]
@bleskes pushed a new commit

**Comment by bleskes** [comment]
LGTM. Thanks @s1monw

**Comment by s1monw** [comment]
@ywelsch you mentioned an integration test for this you added, is the test much different to my last commit (https://github.com/s1monw/elasticsearch/commit/7b5e323ec0581ce53d407e1de6f84709776ebfe0) and if so do you wanna add it to this PR?

**Comment by ywelsch** [comment]
My test looked similar (no need to add more of the same). I did not rely on delayed shard allocation though but explicitly disabled allocation for the restart. Maybe the test can be randomised to pick one of these approaches and also chose a random number of shards?

**Comment by s1monw** [comment]
> Maybe the test can be randomised to pick one of these approaches and also chose a random number of shards?

I don't like the randominzation aspect here. I think the test should be really stable to just test what it is supposed to test.
