### PR TITLE
ES|QL - Full text functions accept null as field parameter

### LINKED ISSUE #136608: ESQL: MATCH function failing on locally missing field
### Description

A query like `FROM ... | WHERE MATCH(first_name, ...)` will currently fail to be planned, if `first_name` is `null` locally.
The failure is a `org.elasticsearch.xpack.esql.VerificationException` : `"[MATCH] function cannot operate on [first_name], which is not a field from an index mapping"`.
The reason is the way the planning goes with the locally null fields, replacing all found `FieldAttribute`s with `null` of the type in `ReplaceFieldWithConstantOrNull`:
```
  1> [2025-10-15T04:22:54,014][TRACE][o.e.x.e.o.L.changes      ][testMatchOnMissingField] Rule local.ReplaceFieldWithConstantOrNull applied with change
  1> Limit[1000[INTEGER],false]                                                  = Limit[1000[INTEGER],false]
  1> \_Filter[MATCH(first_name{f}#4,value[KEYWORD])]                             ! \_Filter[MATCH(null[KEYWORD],value[KEYWORD])]
  1>   \_EsRelation[test][_meta_field{f}#9, emp_no{f}#3, first_name{f}#4, gen..] !   \_Project[[_meta_field{f}#9, emp_no{f}#3, first_name{r}#4, gender{f}#5, hire_date{f}#10, job{f}#11, job.raw{f}#12, langu
  1>                                                                             ! ages{f}#6, last_name{f}#7, long_noidx{f}#13, salary{f}#8]]
  1>                                                                             !     \_Eval[[null[KEYWORD] AS first_name#4]]
  1>                                                                             !       \_EsRelation[test][_meta_field{f}#9, emp_no{f}#3, first_name{f}#4, gen..]
```

A fix could be to adjust the rule, but adjusting the function to allow `null`s is probably better.

### PR DESCRIPTION
**Pull request by carlosdelest**
Closes https://github.com/elastic/elasticsearch/issues/136608

Full text functions that take a field as a parameter should allow null as a field parameter. This is necessary as the field may not be present on an index mapping, and the local optimizer replaces it by null.

We allow null as a field in FullTextFunctions, meaning that they are nullable and will be replaced by `NULL`.

This PR also refactors full text functions that depend on a single field (`MATCH`, `MATCH_PHRASE`, `KNN`) to use a common superclass (`SingleFieldFullTextFunction`) that contains the common field logic.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java [hunk 1]
```diff
@@ -300,39 +286,7 @@ public final void writeTo(StreamOutput out) throws IOException {
 
     @Override
     protected TypeResolution resolveParams() {
-        return resolveField().and(resolveQuery())
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java:303]: Refactoring - all of these are moved up to `SingleFieldFullTextFunction`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+
+    /**
+     * Returns the field as a FieldAttribute for use in query translation
+     */
+    protected FieldAttribute fieldAsFieldAttribute() {
+        return fieldAsFieldAttribute(field);
+    }
+
+    @Override
+    public boolean foldable() {
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java:159]: This is what changed on this PR besides all the refactoring. When the FTF field is null, the FTF is foldable to NULL, and nullable.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java [hunk 3]
```diff
@@ -67,7 +63,8 @@ private static Batch<LogicalPlan> localRewrites() {
                 new ReplaceFieldWithConstantOrNull(),
                 new InferIsNotNull(),
                 new InferNonNullAggConstraint(),
-                new ReplaceDateTruncBucketWithRoundTo()
+                new ReplaceDateTruncBucketWithRoundTo(),
+                new FoldNull()
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java]: @alex-spies I added `foldNull` to local logical optimization, so full text functions can be folded to null when null has been replaced. Does it look OK to you?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java [hunk 4]
```diff
@@ -1083,25 +1082,46 @@ public void testPushDownDisjunctiveFullTextFunctionPastUnionAll() {
...
-        // resolveFork creates the reference attribute, provide a better source text for it
-        assertEquals(
-            "1:1: [MATCH] function cannot be used after FROM\n"
-                + "line 1:1: [MATCH] function cannot operate on [FROM test, (FROM languages)], which is not a field from an index mapping",
-            e.getMessage().substring(header.length())
-        );
+            """);
+
+        // Limit[1000[INTEGER],false,false]
+        Limit limit = as(plan, Limit.class);
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java:1088]: @fang-xing-esql , now FTFs can be pushed down  - when a field does not exist in the index, it will become NULL instead.

Does this make sense from the union all perspective?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java [hunk 5]
```diff
@@ -1083,25 +1082,46 @@ public void testPushDownDisjunctiveFullTextFunctionPastUnionAll() {
...
 
     /*
-     * If the field used in the full text function is not present in any of the indices in the UnionAll branches,
+     * If the field used in the full text function is not present in one of the indices in the UnionAll branches,
      * the full text function cannot be pushed down.
      */
     public void testFullTextFunctionCannotBePushedDownPastUnionAll() {
         assumeTrue("Requires subquery in FROM command support", EsqlCapabilities.Cap.SUBQUERY_IN_FROM_COMMAND.isEnabled());
-        VerificationException e = expectThrows(VerificationException.class, () -> planSubquery("""
+        var plan = planSubquery("""
```
Comment (kderusso) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java:1082]: Do we need to specify a new capability for this test?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 6]
```diff
@@ -0,0 +1,257 @@
...
+/**
+ * Base class for full-text functions that operate on a single field.
+ * This class extracts common functionality from Match and MatchPhrase including:
+ * - Field and options management
+ * - Type resolution for field and query parameters
+ * - Query value conversion
+ * - Field verification
+ * - Serialization patterns
+ */
+public abstract class SingleFieldFullTextFunction extends FullTextFunction
```
Comment (kderusso) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java:50]: Nice refactoring!

**Review by kderusso — COMMENTED** [review]
Changes look good to me, but will defer to someone with more ES|QL experience to 👍 😁

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java (hunk 5 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java:1082]: We don't, as the MATCH function is already released (so it's not conditionally added for release / snapshots) and this test is not executed for BwC purposes.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 7]
```diff
@@ -0,0 +1,257 @@
...
+    /**
+     * Returns a human-readable string listing the expected query types.
+     * Used in error messages.
+     */
+    protected String getExpectedQueryTypesString() {
+        return expectedTypesAsString(getQueryDataTypes());
+    }
+
+    static String expectedTypesAsString(Set<DataType> FieldDataTypes) {
+        return String.join(", ", FieldDataTypes.stream().map(dt -> dt.name().toLowerCase(Locale.ROOT)).toList());
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]:
```suggestion
    static String expectedTypesAsString(Set<DataType> dataTypes) {
        return String.join(", ", dataTypes.stream().map(DataType::typeName).toList());
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 8]
```diff
@@ -0,0 +1,257 @@
...
+     * Returns the allowed options map for this function.
+     * Keys are option names, values are the expected data types.
+     */
+    protected abstract Map<String, DataType> getAllowedOptions();
+
+    /**
+     * Returns a human-readable string listing the expected field types.
+     * Used in error messages.
+     */
+    protected String getExpectedFieldTypesString() {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]:
```suggestion
    protected String expectedFieldTypesString() {
```
for consistency (with the static method).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 9]
```diff
@@ -0,0 +1,257 @@
...
+        return expectedTypesAsString(getFieldDataTypes());
+    }
+
+    /**
+     * Returns a human-readable string listing the expected query types.
+     * Used in error messages.
+     */
+    protected String getExpectedQueryTypesString() {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]:
```suggestion
    protected String expectedQueryTypesString() {
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/FullTextFunction.java [hunk 10]
```diff
@@ -462,7 +464,7 @@ public static String getNameFromFieldAttribute(FieldAttribute fieldAttribute) {
         return fieldName;
     }
 
-    public static FieldAttribute fieldAsFieldAttribute(Expression field) {
+    protected FieldAttribute fieldAsFieldAttribute(Expression field) {
         Expression fieldExpression = field;
         // Field may be converted to other data type (field_name :: data_type), so we need to check the original field
         if (fieldExpression instanceof AbstractConvertFunction convertFunction) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/FullTextFunction.java:475]: A somewhat lateral note: we could have an unpacking loop here, for the (more likely automated query generation) case of nested conversions, like: `field::INTEGER::LONG`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 11]
```diff
@@ -0,0 +1,257 @@
...
+            getExpectedQueryTypesString()
+        ).and(isNotNull(query(), sourceText(), TypeResolutions.ParamOrdinal.SECOND));
+        if (result.unresolved()) {
+            return result;
+        }
+        result = resolveTypeQuery(query(), sourceText(), forPreOptimizationValidation(query()));
+        if (result.equals(TypeResolution.TYPE_RESOLVED) == false) {
+            return result;
+        }
+        return TypeResolution.TYPE_RESOLVED;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]:
```suggestion
        return resolveTypeQuery(query(), sourceText(), forPreOptimizationValidation(query()));
```

**Comment by carlosdelest** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots-part3

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 12]
```diff
@@ -0,0 +1,257 @@
...
+    @Override
+    public Object fold(FoldContext ctx) {
+        // We only fold when the field is null (it's not present in the mapping), so we return null
+        return Literal.NULL;
+    }
+
+    @Override
+    public Nullability nullable() {
+        // The function is nullable if the field is guaranteed to be null, due to the field not being present in the mapping
+        return Expressions.isGuaranteedNull(field()) ? Nullability.TRUE : Nullability.FALSE;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]:
```suggestion
        return field().nullable();
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/MultiMatch.java [hunk 13]
```diff
@@ -441,6 +452,24 @@ protected TypeResolution resolveParams() {
...
+    @Override
+    public Object fold(FoldContext ctx) {
+        // We only fold when all fields are null (none is present in the mapping), so we return null
+        return Literal.NULL;
+    }
+
+    @Override
+    public Nullability nullable() {
+        // The function is nullable if all fields are guaranteed to be null, due to the fields not being present in the mapping
+        return fields.stream().allMatch(Expressions::isGuaranteedNull) ? Nullability.TRUE : Nullability.FALSE;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/MultiMatch.java]:
```suggestion
        return Expressions.nullable(fields);
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java [hunk 14]
```diff
@@ -77,6 +74,11 @@ private static Batch<LogicalPlan> localRewrites() {
         return new Batch<>("Local rewrite", Limiter.ONCE, rules.toArray(Rule[]::new));
     }
 
+    @Override
+    protected List<Batch<LogicalPlan>> batches() {
+        return RULES;
+    }
+
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java]: This is just a move, right? Was it intentional?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/fulltext/AbstractMatchFullTextFunctionTests.java [hunk 15]
```diff
@@ -30,7 +32,7 @@ protected static List<TestCaseSupplier> testCaseSuppliers() {
         AbstractMatchFullTextFunctionTests.addNonNumericCases(suppliers);
         AbstractMatchFullTextFunctionTests.addQueryAsStringTestCases(suppliers);
         AbstractMatchFullTextFunctionTests.addStringTestCases(suppliers);
-        return suppliers;
+        return addNullFieldTestCases(suppliers);
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/fulltext/AbstractMatchFullTextFunctionTests.java:35]: I _think_ these aren't added to all functions, like `MatchPhraseTests` (possibly others, Knn?), right?
Raising this since `MatchPhrase.FIELD_DATA_TYPES` doesn't include `NULL`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java]: ~I think this should be beneficial, yes. Not sure why we didn't have it earlier.
Do you think you could please add one/some `LocalLogicalPlanOptimizerTests` with maybe some "easy" other function(s) (string or math?) to check that they locally now get folded too. This should add a tiny bit of performance to other functions too.~

**Review by bpintea — APPROVED** [review]
Left a few comments, but after those it should look good. 
I think some simple CSV-spec tests would be good to have too, just to check that they work with literals, centrally too. (`MATCH(null, ..)`, `..| EVAL x = null | WHERE MATCH(x, ...)`).

Would be great to wait for @fang-xing-esql check too.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java (hunk 3 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java]: the `FoldNull` rule is in the `localOperators` batch, that is applied after the `localRewrites` batch. Is it too late to wait for it to be executed in `localOperators`? I wonder why we need a duplicate of it here?

Comment (carlosdelest) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java]: Oh, I see - I didn't understand that this rule was already used as part of localOperators(). Removing it, thanks @fang-xing-esql !

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java (hunk 14 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java]: No, reverting

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/fulltext/AbstractMatchFullTextFunctionTests.java (hunk 15 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/fulltext/AbstractMatchFullTextFunctionTests.java:35]: Good call! Done in 845cd35b03589529286c6e2e89d37f20379378f1

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java (hunk 7 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]: Done! ad811e5cb8994eade1d5ca017468136d7785b06d

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java (hunk 8 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]: Done! ad811e5cb8994eade1d5ca017468136d7785b06d

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java (hunk 9 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]: Done as well in ad811e5cb8994eade1d5ca017468136d7785b06d

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java (hunk 4 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java:1088]: I found a potential issue here and I'll provide a reproducer.

Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java:1088]: The query in the test failed with `VerificationException` because the full text function does not apply to one of the subquery(branch), the field referenced in the full text function is not an index field, it doesn't throw `VerificationException` in this PR, however I run into this error when the query is executed. Shall we still throw `VerificationException` for this kind of situations? Or prune the entire branch when the field does not exist in that branch, a related comment is [here](https://github.com/elastic/elasticsearch/pull/137430#discussion_r2491882600).

```
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from sample_data_1, (from books) metadata _score | WHERE author:\"Bradbury\" | sort _score desc, author"
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Unrecognized class type class org.elasticsearch.xpack.esql.core.expression.Literal"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Unrecognized class type class org.elasticsearch.xpack.esql.core.expression.Literal"
  },
  "status" : 400
}
```

The mapping and data a like below.

```
curl -u elastic:password -X POST "localhost:9200/books/_doc?pretty" -H 'Content-Type: application/json' -d'
{"name": "Snow Crash", "author": "Neal Stephenson", "release_date": "1992-06-01", "page_count": 470, "*name": "*Snow Crash"}
'

curl -u elastic:password -X POST "localhost:9200/_bulk?refresh&pretty" -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "books" } }
{"name": "Revelation Space", "author": "Alastair Reynolds", "release_date": "2000-03-15", "page_count": 585, "*name": "*Revelation Space"}
{ "index" : { "_index" : "books" } }
{"name": "1984", "author": "George Orwell", "release_date": "1985-06-01", "page_count": 328, "*name": "*1984"}
{ "index" : { "_index" : "books" } }
{"name": "Fahrenheit 451", "author": "Ray Bradbury", "release_date": "1953-10-15", "page_count": 227, "*name": "*Fahrenheit 451"}
{ "index" : { "_index" : "books" } }
{"name": "Brave New World", "author": "Aldous Huxley", "release_date": "1932-06-01", "page_count": 268, "*name": "*Brave New World"}
{ "index" : { "_index" : "books" } }
{"name": "The Handmaids Tale", "author": "Margaret Atwood", "release_date": "1985-06-01", "page_count": 311, "*name": "*The Handmaids Tale"}
'

curl -u elastic:password -X PUT "localhost:9200/sample_data_1?pretty" -H 'Content-Type: application/json' -d'
{
  "settings" : {"mode" : "lookup"},
  "mappings": {
    "properties": {
      "client.ip": {"type": "ip"},
      "message": {"type": "text"},
      "test_date": {"type": "date"},
      "event.duration": {"type": "long"},
      "mv": {"type": "long"}
    }
  }
}
'

curl -X PUT "localhost:9200/sample_data_1/_bulk?refresh&pretty" -H 'Content-Type: application/json' -d'
{"index": {}}
{"@timestamp": "2023-10-23T12:15:03.360Z", "client.ip": "172.21.2.162", "message": "Connected to 10.1.0.3", "event.duration": 3450233, "test_date": "1985-11-21T00:00:00Z", "mv": [1.0, 2.0]}
{"index": {}}
{"@timestamp": "2023-10-23T12:27:28.948Z", "client.ip": "172.21.2.113", "message": "Connected to 10.1.0.2", "event.duration": 2764889, "test_date": "1985-11-22T00:00:00Z", "mv": [1.0, 2.0]}
{"index": {}}
{"@timestamp": "2023-10-23T13:33:34.937Z", "client.ip": "172.21.0.5", "message": "Disconnected", "event.duration": 1232382, "test_date": "1985-11-23T00:00:00Z", "mv": [1.0, 2.0]}
{"index": {}}
{"@timestamp": "2023-10-23T13:51:54.732Z", "client.ip": "172.21.3.15", "message": "Connection error", "event.duration": 725448, "test_date": "1985-11-24T00:00:00Z", "mv": [1.0, 2.0]}
{"index": {}}
{"@timestamp": "2023-10-23T13:52:55.015Z", "client.ip": "172.21.3.15", "message": "Connection error", "event.duration": 8268153, "test_date": "1985-11-25T00:00:00Z", "mv": [1.0, 2.0]}
{"index": {}}
{"@timestamp": "2023-10-23T13:53:55.832Z", "client.ip": "172.21.3.15", "message": "Connection error", "event.duration": 5033755, "test_date": "1985-11-26T00:00:00Z", "mv": [1.0, 2.0]}
{"index": {}}
{"@timestamp": "2023-10-23T13:55:01.543Z", "client.ip": "172.21.3.15", "message": "Connected to 10.1.0.1", "event.duration": 1756467, "test_date": "1985-11-27T00:00:00Z", "mv": [1.0, 2.0]}
'

```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java [hunk 16]
```diff
@@ -0,0 +1,246 @@
...
+    @Override
+    public boolean foldable() {
+        // The function is foldable if the field is guaranteed to be null, due to the field not being present in the mapping
+        return Expressions.isGuaranteedNull(field());
+    }
+
+    @Override
+    public Object fold(FoldContext ctx) {
+        // We only fold when the field is null (it's not present in the mapping), so we return null
+        return Literal.NULL;
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]: I wonder if we should just return a `null` here, instead of wrapping a `Literal` around it? A lot of implementations of `fold` return a plain `null`.

**Review by fang-xing-esql — COMMENTED** [review]
Thank you @carlosdelest, and for taking into account subqueries as well! Agreed with @bogdan, it will be great to add some additional tests(verify the logical plan and some CsvTests to validate query results) that have these full text functions with `null` as input field. If the full text functions are used in filters, the `PruneFilters` rule might be able to replace its children plans with a `LocalRelation`, that is a sign that the filter on full text function + `null` fields is applied successfully.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java (hunk 16 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/SingleFieldFullTextFunction.java]: Yes, this is what caused the error you mentioned 🤦

**Comment by carlosdelest** [comment]
> I think some simple CSV-spec tests would be good to have too, just to check that they work with literals, centrally too. (`MATCH(null, ..)`, `..| EVAL x = null | WHERE MATCH(x, ...)`).

@bpintea makes sense, added CSV tests in a9dec3d625ea008b563426d1fa4f38f54f0f3d41 and more optimization tests for null in 0c4293c2454e99a672f53c5a9f2602b8b034a928

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java (hunk 4 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownFilterAndLimitIntoUnionAllTests.java:1088]: Thanks for spotting this! This was indeed a problem with returning `Literal.NULL` instead of `null` when folding.

I fixed that in bcf5d4f510a13932b277cd060cc098f27e1f0993, and added CSV tests in a9dec3d625ea008b563426d1fa4f38f54f0f3d41 to double check.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java [hunk 17]
```diff
@@ -120,7 +123,7 @@
 import static org.hamcrest.Matchers.nullValue;
 import static org.hamcrest.Matchers.startsWith;
 
-//@TestLogging(value = "org.elasticsearch.xpack.esql:TRACE", reason = "debug")
+@TestLogging(value = "org.elasticsearch.xpack.esql:TRACE", reason = "debug")
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java:126]: Don't forget to comment out the debug log before merging.

**Review by fang-xing-esql — COMMENTED** [review]
Thank you @carlosdelest, LGTM! A couple of suggestions:

- I came across a similar issue that a field cannot be found on the data node, although it exists in the index mapping once before. It was because there are more than 10 indices on the cluster, and our batch execution model split them into multiple batches, by default 10 indices per [batch](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/QueryPragmas.java#L67). When the batch that does not have that index/field is executed, `ReplaceFieldWithConstantOrNull` converts the field to `null`. I didn't spend much time to investigate how the original/reported issue related to this PR happened, however this is likely one of the causes, and it will be great that if we have a test that covers it, an example can be found [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java#L1131) - the test creates more than 10 indices to trigger the batch executions, and it exercise the code path from a different perspective, it will be nice to have this coverage.
- `subquery` is under snapshot, adding the `test-release` label help us ensure the change(relevant to `subquery`) is not exposed to a release build.

**Comment by carlosdelest** [comment]
> the test creates more than 10 indices to trigger the batch executions, and it exercise the code path from a different perspective, it will be nice to have this coverage.

@fang-xing-esql  ah interesting - did a test to exercise that in 7a6538dddc5f96c4bc9501ecb6b1727f6b883d0c

**Comment by carlosdelest** [comment]
@fang-xing-esql I added the `test-release` tag - failures are due to `HistogramPercentileTests`, which is unrelated to this change.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java [hunk 18]
```diff
@@ -1785,6 +1785,73 @@ public void testRLikeHandlingOfEmptyLanguagePattern() throws IOException {
         assertThat(answer.get("values"), equalTo(List.of(List.of("#"), List.of("foo#bar"))));
     }
 
+    public void testMatchFunctionAcrossMultipleIndicesWithMissingField() throws IOException {
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:1788]: Do we need a capability here? Will this test fail on older versions? It also reminds me whether this fix need to be backported to some prior versions.

**Review by fang-xing-esql — COMMENTED** [review]
Thanks for adding the test, @carlosdelest. That failed release test seems to be related to a BWC issue. As long as the release tests for full-text functions and subqueries are passing, we’re good. This also reminds me to double-check the BWC of the new test(Rest).

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java (hunk 18 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:1788]: IIUC, `RestEsqlSpecIT` is not a bwc test - even for multi_node, it does not use previous ES versions. Is that correct?

Re backporting - this includes some refactoring for FTFs that I'd like to check to understand the effort needed before commiting.

**Comment by carlosdelest** [comment]
> Thanks for adding the test, @carlosdelest. That failed release test seems to be related to a BWC issue. As long as the release tests for full-text functions and subqueries are passing, we’re good. This also reminds me to double-check the BWC of the new test(Rest).

@fang-xing-esql I believe this is not due to bwc for the feature. All tests are failing for the `HistogramPercentileTests` due to:

`java.lang.IllegalArgumentException: remote node at version [9213000] doesn't understand data type [EXPONENTIAL_HISTOGRAM]`

That is not related to this change, but to a new data type being added to snapshots that is failing for release tests.

**Review by fang-xing-esql — APPROVED** [review]
Thanks for double checking!

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/137914)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/138003)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
