### PR TITLE
Coerce decimal strings for whole number types by truncating the decimal part

### LINKED ISSUE #25819: Indexing a value of "1.0" to byte field with coerce=true fails on 5.5.0
**Elasticsearch version**:
"version" : {
    "number" : "5.5.0",
    "build_hash" : "260387d",
    "build_date" : "2017-06-30T23:16:05.735Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  }

**Plugins installed**: none

**JVM version** (`java -version`):
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

**Description of the problem including expected versus actual behavior**:

Attempting to index a value of "1.0" to byte field mapped with coerce=true fails with the following error: number_format_exception

**Steps to reproduce**:

curl -X PUT localhost:9200/testing -d '{ "mappings" : { "coerceme" : { "properties" : { "test" : { "type" : "byte", "coerce" : true}}}}}'

curl -X PUT localhost:9200/testing/coerceme/1 -d '{ "test" : "1.0" }'

Response:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [test]"}],"type":"mapper_parsing_exception","reason":"failed to parse [test]","caused_by":{"type":"number_format_exception","reason":"For input string: \"1.0\""}},"status":400}

### PR DESCRIPTION
**Pull request by scottsom**
This changes makes it so you can index a value like "1.0" or "1.1" into whole
number field types like byte and integer. Without this change then the above
values would have resulted in an error, even with coerce set to true.

Closes #25819

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java [hunk 1]
```diff
@@ -612,20 +602,27 @@ Query rangeQuery(String field, Object lowerTerm, Object upperTerm,
...
-                if (value instanceof BytesRef) {
-                    value = ((BytesRef) value).utf8ToString();
+
+                // longs need special handling so we don't lose precision while parsing
+                String stringValue = (value instanceof BytesRef) ? ((BytesRef) value).utf8ToString() : value.toString();
+
+                try {
+                    return Long.parseLong(stringValue);
+                } catch (NumberFormatException e) {
+                    return (long) Double.parseDouble(stringValue);
```
Comment (scottsom) [inline core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: This does not preserve the precision of large numbers that have a decimal part and exceed the fractional bits of double but are within min/max Long. For example, while both `4115420654264075766` and `"4115420654264075766"` will be indexed as `4115420654264075766`, something like `"4115420654264075766.1"` will not be indexed as `4115420654264075766` due to String -> Double -> Long conversion.

Do we want to try to do something a bit more clever to handle this edge case?

File: core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java [hunk 2]
```diff
@@ -389,20 +383,20 @@ Query rangeQuery(String field, Object lowerTerm, Object upperTerm,
         BYTE("byte", NumericType.BYTE) {
             @Override
             Byte parse(Object value, boolean coerce) {
+                double doubleValue = objectToDouble(value);
+
+                if (doubleValue < Byte.MIN_VALUE || doubleValue > Byte.MAX_VALUE) {
+                    throw new IllegalArgumentException("Value [" + value + "] is out of range for a byte");
+                }
+                if (!coerce && doubleValue % 1 != 0) {
```
Comment (scottsom) [inline core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: This only rejects `coerce=false` values for numbers with decimals but it won't reject strings, which seems to run contrary to how coercion is supposed to work. I did not change this behaviour. I just wanted to call it out as inconsistent with how the parse methods in AbstractXContentParser work, should this be changed?

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/geogrid/GeoHashGridParserTests.java [hunk 3]
```diff
@@ -46,19 +46,6 @@ public void testParseValidFromStrings() throws Exception {
         assertNotNull(GeoGridAggregationBuilder.parse("geohash_grid", stParser));
     }
 
-    public void testParseErrorOnNonIntPrecision() throws Exception {
```
Comment (scottsom) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/geogrid/GeoHashGridParserTests.java]: I removed this test since this change breaks it _but_ I don't think that this test makes sense in the current state. For example, before this change that test would also break if you changed it from `"2.0"` to a decimal literal like `2.5`. Now it is consistent (it will accept and truncate decimals, whether you quote them or not).

File: core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java [hunk 4]
```diff
@@ -389,20 +383,20 @@ Query rangeQuery(String field, Object lowerTerm, Object upperTerm,
...
-                        throw new IllegalArgumentException("Value [" + value + "] has a decimal part");
-                    }
                     return ((Number) value).byteValue();
                 }
-                if (value instanceof BytesRef) {
-                    value = ((BytesRef) value).utf8ToString();
-                }
-                return Byte.parseByte(value.toString());
+
+                return (byte) doubleValue;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: Sorry I deleted your comment by mistake, so I am adding it back:

>  This does not preserve the precision of large numbers that have a decimal part and exceed the fractional bits of double but are within min/max Long. For example, while both 4115420654264075766 and "4115420654264075766" will be indexed as 4115420654264075766, something like "4115420654264075766.1" will not be indexed as 4115420654264075766 due to String -> Double -> Long conversion.
> 
> Do we want to try to do something a bit more clever to handle this edge case?

**Comment by jpountz** [comment]
@elasticmachine Please test it.

**Review by jpountz — APPROVED** [review]
It looks good to me, thanks for working on it.

File: core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java (hunk 1 above)
Comment (scottsom) [inline core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: Do you mean a comment in the code or in the documentation? (i.e. a warning here https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html)

**Comment by scottsom** [comment]
Added `StandardCharsets.UTF_8` to the unit test to fix the build. Can you kick off that build again?

**Comment by jpountz** [comment]
@elasticmachine Please test it.

**Comment by scottsom** [comment]
The [build failure](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/3502/console) seems transient and/or unrelated to this change.

I've rebased onto the latest master since I see some newer changes that appear to be improving test stability.

**Comment by jpountz** [comment]
@elasticmachine Test it please.

File: core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java (hunk 1 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: I mean in the code but just noticed there was one already

**Review by jpountz — APPROVED** [review]

**Comment by jpountz** [comment]
Thank you @scottsom !
