### PR TITLE
Publish to self through transport

### LINKED ISSUE #43631: VotingOnlyNodeCoordinatorTests testDoesNotElectVotingOnlyMasterNode failure
https://scans.gradle.com/s/tfu25vregk2hy
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora-29&&immutable/86/console

```
java.lang.AssertionError: (No message provided)
at __randomizedtesting.SeedInfo.seed([D28433B53AFFA3C7:4E4230F5B099413]:0)
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertFalse(Assert.java:64)
at org.junit.Assert.assertFalse(Assert.java:74)
at org.elasticsearch.cluster.coordination.VotingOnlyNodeCoordinatorTests.testDoesNotElectVotingOnlyMasterNode(VotingOnlyNodeCoordinatorTests.java:29)
```

Log file: https://scans.gradle.com/s/tfu25vregk2hy/tests/tgrx2aitn6u62-vhkxezy67i4ic

This actually reproduces for me:
```
./gradlew :x-pack:plugin:voting-only-node:test --tests "org.elasticsearch.cluster.coordination.VotingOnlyNodeCoordinatorTests.testDoesNotElectVotingOnlyMasterNode" -Dtests.seed=D28433B53AFFA3C7 -Dtests.security.manager=true -Dtests.locale=sv-AX -Dtests.timezone=Asia/Dhaka -Dcompiler.java=12 -Druntime.java=11
```

### PR DESCRIPTION
**Pull request by ywelsch**
This PR ensures that cluster state publications to self also go through the transport layer. This allows voting-only nodes to intercept the publication to self.

Fixes an issue discovered by a test failure where a voting-only node, which was the only bootstrapped node, would not step down as master after state transfer because publishing to self would succeed.

Marked as non-issue because problematic code is not released.

Closes #43631

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java [hunk 1]
```diff
@@ -156,29 +162,27 @@ public void sendPublishRequest(DiscoveryNode destination, PublishRequest publish
...
-                    // don't want to be replicated because it's not usable on another node (e.g. UnassignedInfo.unassignedTimeNanos) or
-                    // because it's mostly just debugging info that would unnecessarily blow up CS updates (I think there was one in
-                    // snapshot code).
-                    // TODO: look into these and check how to get rid of them
-                    transportService.getThreadPool().generic().execute(new AbstractRunnable() {
+                    // if publishing to self, use original request instead (see currentPublishRequestToSelf for explanation)
+                    final PublishRequest previousRequest = currentPublishRequestToSelf.getAndSet(publishRequest);
+                    assert previousRequest == null;
+                    final ActionListener<PublishWithJoinResponse> originalListener = responseActionListener;
+                    responseActionListener = new ActionListener<PublishWithJoinResponse>() {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java]: I'd rather this used a different variable rather than mutating the parameter.

**Review by DaveCTurner — APPROVED** [review]
Good catch. I left a nit, but LGTM otherwise.

File: server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java (hunk 1 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java]: fixed in 9c2822d
