### PR TITLE
ESQL: Fix serialization during can_match

### LINKED ISSUE #111701: [CI] RestEsqlIT testTopLevelFilterBoolMerged {SYNC} failing
**Build Scans:**
- [elasticsearch-periodic #3711 / release-tests](https://gradle-enterprise.elastic.co/s/t6pceldi7cczm)
- [elasticsearch-periodic #3707 / release-tests](https://gradle-enterprise.elastic.co/s/curg3m6yyrsaw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT.testTopLevelFilterBoolMerged {SYNC}" -Dtests.seed=3863D2260DB56A6A -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=th-TH -Dtests.timezone=Europe/Vienna -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTopLevelFilterBoolMerged%20%7BSYNC%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:44713], URI [/_query?pretty=true&error_trace=true], status line [HTTP/1.1 500 Internal Server Error]
Warnings: [No limit defined, adding default limit of [1000]]
:)
úerrorúroot_causeøútypeHexceptionreason!stack_traceäorg.elasticsearch.ElasticsearchException
	at org.elasticsearch.compute.operator.FailureCollector.unwrapAndCollect(FailureCollector.java:51)
	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:61)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:92)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1595)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1575)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: org.elasticsearch.tasks.TaskCancelledException: cancelled on failure
		at org.elasticsearch.compute.operator.Driver.cancel(Driver.java:304)
		at org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest$1.onCancelled(DriverTaskRunner.java:101)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.CancellableTask.cancel(CancellableTask.java:43)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.cancel(TaskManager.java:617)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancel(TaskManager.java:274)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:141)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:372)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:356)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:1085)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:160)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:982)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:877)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.setBanOnChildConnections(TaskCancellationService.java:195)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancelTaskAndDescendants(TaskManager.java:812)
		at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:65)
		... 28 more
		Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:399)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249)
			at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.close(Releasables.java:34)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:50)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:308)
			... 21 more
üsuppressedøúBWtask_cancelled_exceptionCScancelled on failureDäorg.elasticsearch.tasks.TaskCancelledException: cancelled on failure
	at org.elasticsearch.compute.operator.Driver.cancel(Driver.java:304)
	at org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest$1.onCancelled(DriverTaskRunner.java:101)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.CancellableTask.cancel(CancellableTask.java:43)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.cancel(TaskManager.java:617)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancel(TaskManager.java:274)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:141)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:372)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:356)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:1085)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:160)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:982)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:877)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.setBanOnChildConnections(TaskCancellationService.java:195)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:146)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancelTaskAndDescendants(TaskManager.java:812)
	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:65)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:92)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1595)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1575)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:399)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249)
		at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.close(Releasables.java:34)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:50)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:308)
		... 21 more
üEøúBHexceptionC`1 further exceptions were droppedDäorg.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:399)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249)
	at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.close(Releasables.java:34)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:50)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:308)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:92)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1595)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1575)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
üûùûùûùBHexceptionC!Däorg.elasticsearch.ElasticsearchException
	at org.elasticsearch.compute.operator.FailureCollector.unwrapAndCollect(FailureCollector.java:51)
	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:61)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:92)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1595)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1575)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: org.elasticsearch.tasks.TaskCancelledException: cancelled on failure
		at org.elasticsearch.compute.operator.Driver.cancel(Driver.java:304)
		at org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest$1.onCancelled(DriverTaskRunner.java:101)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.CancellableTask.cancel(CancellableTask.java:43)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.cancel(TaskManager.java:617)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancel(TaskManager.java:274)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:141)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:372)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:356)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:1085)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:160)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:982)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:877)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.setBanOnChildConnections(TaskCancellationService.java:195)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancelTaskAndDescendants(TaskManager.java:812)
		at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:65)
		... 28 more
		Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:399)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249)
			at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.close(Releasables.java:34)
			at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:50)
			at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:308)
			... 21 more
üEøúBWtask_cancelled_exceptionCScancelled on failureDäorg.elasticsearch.tasks.TaskCancelledException: cancelled on failure
	at org.elasticsearch.compute.operator.Driver.cancel(Driver.java:304)
	at org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest$1.onCancelled(DriverTaskRunner.java:101)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.CancellableTask.cancel(CancellableTask.java:43)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.cancel(TaskManager.java:617)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancel(TaskManager.java:274)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:141)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:372)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:356)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:1085)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:160)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:982)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:877)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.setBanOnChildConnections(TaskCancellationService.java:195)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:146)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.tasks.TaskManager.cancelTaskAndDescendants(TaskManager.java:812)
	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:65)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:92)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1595)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1575)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:399)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249)
		at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.close(Releasables.java:34)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:50)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:308)
		... 21 more
üEøúBHexceptionC`1 further exceptions were droppedDäorg.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:399)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249)
	at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.close(Releasables.java:34)
	at org.elasticsearch.base@8.16.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:50)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:308)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:92)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1595)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1575)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
üûùûùûstatus$¨û
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 failures in test testTopLevelFilterBoolMerged {SYNC} (1.2% fail rate in 161 executions)
- [main] 2 failures in step release-tests (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #111726: [CI] RestEsqlIT failing in release builds
### CI Link

https://gradle-enterprise.elastic.co/s/og3auotbcrwo6/tests/task/:x-pack:plugin:esql:qa:server:multi-node:javaRestTest/details/org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT/testTopLevelFilterBoolMerged%20%7BASYNC%7D?top-execution=1

### Repro line

./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT.testTopLevelFilterBoolMerged {ASYNC}" -Dtests.seed=BDDF8B812FD76586 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=en-PH -Dtests.timezone=Europe/Belgrade -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
[2024-08-08T23:53:30,617][ERROR][o.e.ExceptionsHelper     ] [test-cluster-0] fatal error java.lang.AssertionError: java.lang.ClassCastException: class org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput cannot be cast to class org.elasticsearch.xpack.esql.io.stream.PlanStreamInput (org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput is in module org.elasticsearch.server@8.16.0 of loader 'app'; org.elasticsearch.xpack.esql.io.stream.PlanStreamInput is in unnamed module of loader java.net.FactoryURLClassLoader @5817f1ca)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:444)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:434)
	at org.elasticsearch.transport.netty4@8.16.0/org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.exceptionCaught(Netty4MessageInboundHandler.java:66)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.109.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.transport@4.1.109.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.109.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.common@4.1.109.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.common@4.1.109.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### PR DESCRIPTION
**Pull request by nik9000**
This fixes that serialization of the `SingleValueQuery` during the `can_match` phase.

Closes #111726
Closes #111701

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java [hunk 1]
```diff
@@ -107,7 +107,15 @@ public static class Builder extends AbstractQueryBuilder<Builder> {
...
-                this.source = Source.readFrom((PlanStreamInput) in);
+                if (in instanceof PlanStreamInput psi) {
+                    this.source = Source.readFrom(psi);
+                } else {
+                    /*
+                     * For things like CanMatch we serialize without the Source. But we
+                     * don't use it, so that's ok.
+                     */
+                    this.source = Source.readEmpty(in);
+                }
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java:118]: I didn't want to make an `if instanceof` thing, but I think this is an appropriate work around in the short term. Maybe in the long term. We don't need this for most plan things so I like that we're isolating this at least.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/tree/Source.java [hunk 2]
```diff
@@ -51,6 +51,21 @@ public static <S extends StreamInput & PlanStreamInput> Source readFrom(S in) th
...
+     * {@link Source#EMPTY}. Use this when you will never use the {@link Source}
+     * and there is no chance of getting a {@link PlanStreamInput}.
+     */
+    public static Source readEmpty(StreamInput in) throws IOException {
+        if (in.readBoolean() == false) {
+            return EMPTY;
+        }
+        in.readInt();
+        in.readInt();
+        in.readInt();
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/tree/Source.java:65]: Thought: Maybe we should abstract reading the three ints into a `readOptionalSourcePosition` or so (whose return value we discard)?

That is duplicated in `readFrom`; factoring into a method would have a higher chance of staying in sync with `readFrom`

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/tree/Source.java [hunk 3]
```diff
@@ -51,6 +51,21 @@ public static <S extends StreamInput & PlanStreamInput> Source readFrom(S in) th
...
+        return Source.EMPTY;
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/tree/Source.java:66]: super duper nit:
```suggestion
        return EMPTY;
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java [hunk 4]
```diff
@@ -107,7 +107,15 @@ public static class Builder extends AbstractQueryBuilder<Builder> {
             this.next = in.readNamedWriteable(QueryBuilder.class);
             this.field = in.readString();
             if (in.getTransportVersion().onOrAfter(TransportVersions.ESQL_SINGLE_VALUE_QUERY_SOURCE)) {
-                this.source = Source.readFrom((PlanStreamInput) in);
+                if (in instanceof PlanStreamInput psi) {
+                    this.source = Source.readFrom(psi);
+                } else {
+                    /*
+                     * For things like CanMatch we serialize without the Source. But we
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java:114]: I couldn't find a `CanMatch.java`. Could we maybe rephrase the comment here a little so it's clear when this would be deserialized without a `PlanStreamInput`? It's currently unclear to me.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java [hunk 5]
```diff
@@ -107,7 +107,15 @@ public static class Builder extends AbstractQueryBuilder<Builder> {
...
+                     * don't use it, so that's ok.
+                     */
+                    this.source = Source.readEmpty(in);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java:117]: Thought: instead of an empty source, would it be reasonable to keep at least the line, column, and length around for debugging?

**Review by alex-spies — APPROVED** [review]
LGTM. Thanks Nik!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java (hunk 5 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/SingleValueQuery.java:117]: Another (minor) idea could be to "normally" `readFrom()` and then just `this.source = Source.EMPTY;` here, rather than make SVG's need Source's concern.
But either way is 👍 .
