### PR TITLE
[Transform] add support for unsigned_long data type

### LINKED ISSUE #63871: [Transform] Transform fails for unsigned long fields
https://github.com/elastic/elasticsearch/pull/60050 introduced a new field type `unsigned_long`. Transform fails in certain combinations if the source index uses a field mapped to `unsigned_long`.

Repro steps:

```
PUT test_ul
{
  "mappings": {
    "properties": {
      "metric": {
        "type": "unsigned_long"
      },
      "id": {
        "type": "keyword"
      }
    }
  }
}

POST test_ul/_doc/1
{
  "id": "a",
  "metric": 3333
}

POST test_ul/_doc/2
{
  "id": "b",
  "metric": 3352
}

POST test_ul/_doc/3
{
  "id": "c",
  "metric": 1222
}

POST test_ul/_doc/4
{
  "id": "d",
  "metric": 4452345
}

PUT _transform/ul1
{
  "source": {
    "index": "test_ul"
  },
  "dest": {
    "index": "ul1"
  }, 
  "pivot": {
    "group_by": {
      "id": {
        "terms": {
          "field": "id"
        }
      }
    },
    "aggregations": {
      "m": {
        "max": {
          "field": "metric"
        }
      },
      "a": {
        "avg": {
          "field": "metric"
        }
      }
    }
  }
}

POST _transform/ul1/_start
GET _transform/ul1/_stats
```

failure:

```
"reason" : "Failed to index documents into destination index due to permanent error: [org.elasticsearch.xpack.transform.transforms.BulkIndexingException: Bulk index experienced [4] failures and at least 1 irrecoverable [org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [m] of type [unsigned_long] in document with id 'YWq29udX231QplrSgrzYJUMAAAAAAAAA'. Preview of field's value: '3333.0'; java.lang.IllegalArgumentException: For input string: [3333.0].]. Other failures:; org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [m] of type [unsigned_long] in document with id 'YWq29udX231QplrSgrzYJUMAAAAAAAAA'. Preview of field's value: '3333.0'; java.lang.IllegalArgumentException: For input string: [3333.0].]",
```

Root cause: Transform indexes the output as string as it does not know that `unsigned_long` is a numeric type, which is due to the addition of `unsigned_long` as plugin.

**Non-Issue**: Because `unsigned_long` support has not been released yet, this issue is not a bug by definition. It's still important to fix.

**Blocker**: In order to not become a bug, I classify it as blocker.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
add support for unsigned_long, which required a change in
writing out integer results properly, because coerce is not
supported for unsigned_long

fixes #63871

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtil.java [hunk 1]
```diff
@@ -23,30 +23,59 @@
...
+     * Further checks (e.g. range) are done at indexing.
+     *
+     * If type is floating point and value could be an integer (ends with `.0`), we still preserve `.0` in case
+     * the destination index uses dynamic mappings as well as being json friendly.
+     *
+     * @param type the type of the value according to the schema we know
+     * @param value the value as double (aggs return double for everything)
+     * @return value if its floating point, a integer
+     */
+    public static Object convertToIntegerTypeIfNeeded(String type, double value) {
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtil.java:67]:
```suggestion
    public static Object convertToDiscreteNumeralTypeIfNeeded(String type, double value) {
```
Or some better name as this is is not an `integer` but instead some possibly large discrete numeral (big int or a long).

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtil.java [hunk 2]
```diff
@@ -23,30 +23,59 @@
...
+        if (NUMERIC_FIELD_MAPPER_TYPES.getOrDefault(type, true) == false) {
+            assert value % 1 == 0;
+            if (value < Long.MAX_VALUE) {
+                return (long) value;
+            }
+
+            // special case for unsigned long
+            return BigDecimal.valueOf(value).toBigInteger();
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtil.java:75]: Its weird to me that there is not a blanket `map doc value -> indexable value` :(

This works in a pinch, I wonder if there is anyway to use `DocValueFormat.UNSIGNED_LONG_SHIFTED`.

But looking at it, there isn't a clean cut solution :/

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtil.java (hunk 1 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/SchemaUtil.java:67]: its referring to the mathematical definition of integer, that's why integer _type_, not integer. I can try to find a better name, maybe `dropFloatingPointComponentIfNeeded`, but lets not over-complicate it, the doc string defines what it does.

**Review by benwtrent — APPROVED** [review]
