### PR TITLE
ESQL: Fix lookup join output

### LINKED ISSUE #117584: ESQL: LOOKUP JOIN's output inconsistent with JOIN's
The output computation for `LOOKUP JOIN` is still under construction, so this is not unexpected; c.f. meta issue https://github.com/elastic/elasticsearch/issues/116208.

However, currently we compute the expected output of a `LOOKUP JOIN` in a [specific method in the Analyzer](https://github.com/elastic/elasticsearch/blob/1866299fa46e387238d28fe4e0d26c713926d47e/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java#L635-L637) - which conflicts with the [computation inside the Join class](https://github.com/elastic/elasticsearch/blob/1866299fa46e387238d28fe4e0d26c713926d47e/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java#L106). This leads to inconsistencies. I believe there really should be only one place where the computation occurs, ideally centralized in the `Join` class so it's not spilled into the analyzer.

Reproducer:
```
$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/languages_lookup" -XPUT -d '{
  "mappings": {
        "properties": {"language_code": {"type": "keyword"}, "language_name":{"type": "keyword"}}}, "settings": {"index": {"mode": "lookup"}}}'

$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test/_doc?refresh' -d'{"x": 1}'

$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '{
    "query": "FROM test | eval language_code = x::keyword | limit 10 | lookup join languages_lookup on language_code"
}'

{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Found 1 problem\nline 1:58: Plan [Project[[x{f}#20, language_code{r}#18, language_name{f}#22]]] optimized incorrectly due to missing references [language_code{r}#18]"}],"type":"illegal_state_exception","reason":"Found 1 problem\nline 1:58: Plan [Project[[x{f}#20, language_code{r}#18, language_name{f}#22]]] optimized incorrectly due to missing references [language_code{r}#18]"},"status":500}
```

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/117584. More generally, make queries work where the `LOOKUP JOIN`'s `ON` field makes it into the result.

Also relates https://github.com/elastic/elasticsearch/issues/116208:
- ~Make `LOOKUP JOIN` work on data nodes.~ **Argh, the multi node tests still have issues and sometimes return `null`** instead of the correctly returned values. But at least the plans sent to data nodes are consistent with the coordinator's plan.
- Solve the item "Look whether the LookupJoin output could be computed inside the class".

**Note to reviewers:** This is not supposed to be a definitive solution for the output order of `LOOKUP JOIN`. That's still open. Accordingly, the updated tests remain minimal; this PR just aims to enable more queries so we can work on more kinds of query plans without running into bugs.

Currently, the computation of a `LookupJoin` node's output happens in the Analyzer; the computed `List<Attribute>` of output attributes is passed on as part of a new `LookupJoin` node. However, then this is replaced by a plain `Join` node in the surrogate step - which forgets about the computed attributes.
This leads to inconsistencies. It also generally prevents execution of lookup joins on data nodes because they are only ever sent `Join` nodes, not `LookupJoin` (the latter is not serializable and doesn't escape the coordinator). This means that the plain `Join` node **must** be the source of truth when it comes to the output, otherwise things will be inconsistent.

Remove the output computation from the Analyzer and move it into the `Join` node, instead.

### CODE REVIEW

**Review by craigtaverner — APPROVED** [review]
LGTM - seems mostly to be a simplification!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java [hunk 1]
```diff
@@ -161,14 +149,6 @@ public static List<Attribute> makeReference(List<Attribute> output) {
         return out;
     }
 
-    private static List<Attribute> makeNullable(List<Attribute> output) {
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java:164]: It will come back - but it's been unused for long now, and it really only wraps 1 line.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/BinaryPlan.java [hunk 2]
```diff
@@ -45,11 +43,6 @@ public final BinaryPlan replaceRight(LogicalPlan newRight) {
         return replaceChildren(left, newRight);
     }
 
-    protected AttributeSet computeReferences() {
-        // TODO: this needs to be driven by the join config
-        return Expressions.references(output());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/BinaryPlan.java:50]: This made no sense. And calling `output()` here is bad because `references()` is called in the `fieldNames` method - at which point the `output()` method is illegal to use because it requires a resolved plan.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java [hunk 3]
```diff
@@ -1945,9 +1945,10 @@ public void testLookup() {
                 .item(startsWith("job{f}"))
                 .item(startsWith("job.raw{f}"))
                 /*
-                 * Int key is returned as a full field (despite the rename)
+                 * Int is a reference here because we renamed it in project.
+                 * If we hadn't it'd be a field and that'd be fine.
                  */
-                .item(containsString("int{f}"))
+                .item(containsString("int{r}"))
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java:1951]: This test for LOOKUP_:chicken: is only reverted to how it was before we added `LOOKUP JOIN`.

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/117687)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
