### PR TITLE
Use `getPortRange` in http server tests

### LINKED ISSUE #58433: [CI] Netty4HttpServerTransportTests.testCorsRequest failures
This test started failing occasionally since June 15 in 7.7, 7.8 and 7.x branches:

https://gradle-enterprise.elastic.co/s/5vv3z2vjtlsie
https://gradle-enterprise.elastic.co/s/dcnfwib2jli5u

example:

```
 ./gradlew ':modules:transport-netty4:test' --tests "org.elasticsearch.http.netty4.Netty4HttpServerTransportTests.testCorsRequest" \
  -Dtests.seed=6B3ABF72A9A87E5E \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=fr-FR \
  -Dtests.timezone=CET \
  -Druntime.java=8
```

Error:

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=346, name=Thread-5, state=RUNNABLE, group=TGRP-Netty4HttpServerTransportTests]
	at __randomizedtesting.SeedInfo.seed([6B3ABF72A9A87E5E:D39CC37F3AB3CA5F]:0)
Caused by: java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([6B3ABF72A9A87E5E]:0)
	at org.elasticsearch.http.netty4.Netty4HttpServerTransportTests$3.dispatchRequest(Netty4HttpServerTransportTests.java:283)
	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:318)
	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:372)
	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:308)
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:42)
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:28)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently we are leaving the settings to default port range in the nio
and netty4 http server test. This has recently led to tests failing due
to what appears to be a port conflict with other processes. This commit
modifies these tests to use the test case helper method to generate port
ranges.

Fixes #58433 and #58296.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM

File: modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4BadRequestTests.java [hunk 1]
```diff
@@ -87,7 +88,8 @@ public void dispatchBadRequest(RestChannel channel, ThreadContext threadContext,
             }
         };
 
-        try (HttpServerTransport httpServerTransport = new Netty4HttpServerTransport(Settings.EMPTY, networkService, bigArrays, threadPool,
+        Settings settings = Settings.builder().put(HttpTransportSettings.SETTING_HTTP_PORT.getKey(), getPortRange()).build();
```
Comment (original-brownbear) [inline modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4BadRequestTests.java:91]: NIT: maybe extract `Settings.builder().put(HttpTransportSettings.SETTING_HTTP_PORT.getKey(), getPortRange()).build()` to a method somewhere in the test framework module to dry this up a little?
