### PR TITLE
Fix and simplify testTargetThrottling

### LINKED ISSUE #103204: [CI] IndexRecoveryIT testTargetThrottling failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/4mgoylcufngs2/tests/:server:internalClusterTest/org.elasticsearch.indices.recovery.IndexRecoveryIT/testTargetThrottling

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testTargetThrottling" -Dtests.seed=2D99499AC21945F6 -Dtests.locale=ro -Dtests.timezone=Asia/Sakhalin -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.indices.recovery.IndexRecoveryIT#testTargetThrottling`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTargetThrottling'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.indices.recovery.IndexRecoveryIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: Throttling should be =0 for 'node_t0'
Expected: <0L>
     but: was <19L>

  at __randomizedtesting.SeedInfo.seed([2D99499AC21945F6:9FF3CD3A7285B021]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.indices.recovery.IndexRecoveryIT.assertNodeHasThrottleTimeAndNoRecoveries(IndexRecoveryIT.java:337)
  at org.elasticsearch.indices.recovery.IndexRecoveryIT.lambda$testTargetThrottling$10(IndexRecoveryIT.java:839)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1278)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1251)
  at org.elasticsearch.indices.recovery.IndexRecoveryIT.testTargetThrottling(IndexRecoveryIT.java:839)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by pxsalehi**
There seems to be two potential issues that can cause failure:
1. If the`INDICES_RECOVERY_MAX_BYTES_PER_SEC_SETTING` on nodeA is too small, then we might choose a chunk size on nodeB that can cause throttling on nodeA. 
2. At the end when we remove the throttling limits, it is possible that first nodeB gets unthrottled which can cause nodeA throttling recovery, it seems. 

Closes https://github.com/elastic/elasticsearch/issues/103204

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 1]
```diff
@@ -808,27 +811,6 @@ public void testTargetThrottling() throws Exception {
 
         startShardRecovery(nodeA, nodeB);
 
-        logger.info("--> checking throttling increases on Node B (target node), while Node A (source node) reports no throttling");
```
Comment (pxsalehi) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:811]: I've removed these. It seems the throttling stats is accumulative, so just asserting on the final state seems to be enough. I might be missing the actual intention behind these though!

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 2]
```diff
@@ -782,21 +782,24 @@ public Settings onNodeStopped(String nodeName) {
      * Tests shard recovery throttling on the target node. Node statistics should show throttling time on the target node, while no
      * throttling should be shown on the source node because the target will accept data more slowly than the source's throttling threshold.
      */
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/103204")
     public void testTargetThrottling() throws Exception {
         logger.info("--> starting node A with default settings");
-        final String nodeA = internalCluster().startNode();
+        final String nodeA = internalCluster().startNode(
+            Settings.builder()
+                .put(RecoverySettings.INDICES_RECOVERY_MAX_BYTES_PER_SEC_SETTING.getKey(), randomIntBetween(10, 200), ByteSizeUnit.MB)
```
Comment (pxsalehi) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:789]: I'm avoiding the "[crazy slow](https://github.com/elastic/elasticsearch/blob/main/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java#L565)" values here since w/o unthrottling it would take a longer time and we time out on green.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:811]: This is to ensure that we see some throttling before we relax the throttle. I think we want to stick with the tight throttle that we then relax rather than setting it looser to start with, or else this test might sometimes not do any throttling at all.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:789]: I think even 10MiB/s might be slow enough to risk being throttled sometimes, if the shard is more than 50kiB in size (see [this comment](https://github.com/elastic/elasticsearch/issues/103204#issuecomment-1849513308) for the calculation). IMO let's set it "crazy fast" to just avoid all this.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 2 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:789]: The limit we set on nodeB is based on that (half of what the rate limiter considers throttle-able). How can it still happen? (We could go higher, but to me it seems this is just to avoid super slow recovery hitting the timeout, not to accidentally cause throttling on source).

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 1 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:811]: (also note that we're not doing any relaxation here. just making sure target has a quite smaller threshold for throttling.)

**Comment by pxsalehi** [comment]
Gentle reminder fore reviews!

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 3]
```diff
@@ -782,21 +782,24 @@ public Settings onNodeStopped(String nodeName) {
...
-            .size();
+        createAndPopulateIndex(INDEX_NAME, 1, SHARD_COUNT_1, REPLICA_COUNT_0);
 
-        long chunkSize = Math.max(1, shardSize.getBytes() / 10);
+        var nodeARecoverySettings = new RecoverySettings(
+            internalCluster().getInstance(Settings.class, nodeA),
+            clusterService().getClusterSettings()
+        );
+        // Use a fraction of the size that causes throttling to be triggered on the source node's RateLimiter
+        long chunkSize = nodeARecoverySettings.rateLimiter().getMinPauseCheckBytes() / 2;
```
Comment (fcofdez) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:800]: I think that we should populate the index with at least 2x the chunk size worth of data and that's not guaranteed right now?

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 1 above)
Comment (fcofdez) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:811]: @pxsalehi can't we keep the original assertions? If the throttling setting is tighter I think that the assertions will hold?

Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:811]: ++ I'd rather keep the test pretty much as it is today and just relax the throttle on the node that we don't expect to do any throttling.

Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: TBH, I do not entirely agree. The point of the change was to simplify the test so we don't need that unthrottling and the assertions in the middle. We also could still check with a wide range of setting values rather than limiting the test to just the max (200mb). But in the interest of closing the test failure, I'm fine with just using 200mb to address the failure. See https://github.com/elastic/elasticsearch/pull/103397/commits/828e10b2146308b838117742b62aff3dcee608e3.

**Review by DaveCTurner — APPROVED** [review]
LGTM
