### PR TITLE
Ensure reindex test exception is not swallowed.

### LINKED ISSUE #81997: [CI] ReindexFromOldRemoteIT testEs1 failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/aijz5ik72tqqm/tests/:modules:reindex:javaRestTest/org.elasticsearch.index.reindex.remote.ReindexFromOldRemoteIT/testEs1

**Reproduction line:**
`./gradlew ':modules:reindex:javaRestTest' --tests "org.elasticsearch.index.reindex.remote.ReindexFromOldRemoteIT.testEs1" -Dtests.seed=63785BD804AADAA4 -Dtests.locale=es-BO -Dtests.timezone=America/Jujuy -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.reindex.remote.ReindexFromOldRemoteIT&tests.test=testEs1

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:53776], URI [/test], status line [HTTP/1.1 404 Not Found]
{"error":"IndexMissingException[[test] missing]","status":404}

  at __randomizedtesting.SeedInfo.seed([63785BD804AADAA4:24C8D0D825E2B1E5]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:335)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:301)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276)
  at org.elasticsearch.index.reindex.remote.ReindexFromOldRemoteIT.oldEsTestCase(ReindexFromOldRemoteIT.java:96)
  at org.elasticsearch.index.reindex.remote.ReindexFromOldRemoteIT.testEs1(ReindexFromOldRemoteIT.java:106)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently it is possible for an exception in `ReindexFromOldRemoteIT` to
be swallowed if an exception thrown is from the finally block when
deleting the test index. This commit ensures a prior exception is
propagated in this case.

Closes #81997.

### CODE REVIEW

**Review by henningandersen — APPROVED** [review]
LGTM.

File: modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java [hunk 1]
```diff
@@ -92,8 +93,16 @@ private void oldEsTestCase(String portPropertyName, String requestsPerSecond) th
...
                 oldEs.performRequest(new Request("DELETE", "/test"));
+                indexDeleted = true;
+            } finally {
+                if (indexDeleted == false) {
+                    try {
+                        oldEs.performRequest(new Request("DELETE", "/test"));
+                    } catch (Exception deleteException) {
+                        logger.warn("Exception deleting index", deleteException);
+                    }
+                }
```
Comment (idegtiarenko) [inline modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java:105]: I do not think it is required to delete the index again in case of exception.
It is enough to catch and log it inside the finally block to propagate the original exception.

**Review by idegtiarenko — CHANGES_REQUESTED** [review]

File: modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java (hunk 1 above)
Comment (henningandersen) [reply modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java:105]: Notice that with the way it is structured now, it could have failed earlier too (for instance in one of the assertions) and in those cases the delete need to be done.

I suppose we could move the line [`idexDeleted = true`](https://github.com/elastic/elasticsearch/pull/85425/files#diff-5cead9923abe48a90807d6356afc5b0805910bd4157cae1b129624fe3461171dR97) before the attempt to delete the index if we want to avoid the double delete attempt, that seems fine to me.

Comment (idegtiarenko) [reply modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java:105]: I think the only delete attempt need to happen in `finally` block (wrapped into its own `try`).

```
try {
 createIndex;
 createTestDocuments;
 assert;
} finally {
  try { delete; }
}
```

This way it will not swallow original exception (from assert) in case index deletion fails.

Comment (tbrooks8) [reply modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java:106]: I mean I would prefer a failed delete in a success case not disappear to a warn message since that is still a concern. But I made a change in this area.

File: modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java [hunk 2]
```diff
@@ -92,8 +93,17 @@ private void oldEsTestCase(String portPropertyName, String requestsPerSecond) th
...
+                success = true;
             } finally {
-                oldEs.performRequest(new Request("DELETE", "/test"));
+                try {
+                    oldEs.performRequest(new Request("DELETE", "/test"));
+                } catch (Exception deleteException) {
+                    logger.warn("Exception deleting index", deleteException);
+                    if (success) {
+                        // Since the test completed successfully, the delete should not fail
+                        throw deleteException;
```
Comment (idegtiarenko) [inline modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java:104]: I think the comment above is slightly misleading as this branch would effectively throw exception.
May be reword to `Since the test completed successfully, the delete exception should not be swallowed if present`?

**Review by idegtiarenko — APPROVED** [review]
