### PR TITLE
Fixes SecurityIntegTestCase so it always adds at least one alias

### LINKED ISSUE #30098: CI org.elasticsearch.xpack.security.authz.ReadActionsTests testEmptyAuthorizedIndicesSearchForWildcard fails
*Original comment by @nik9000:*

This ReadActionsTests failure doesn't reproduce for me locally.

```
gradle :x-pack-elasticsearch:plugin:test -Dtests.seed=6905B0F3BC9A59AE -Dtests.class=org.elasticsearch.xpack.security.authz.ReadActionsTests -Dtests.method="testEmptyAuthorizedIndicesSearchForWildcard" -Dtests.security.manager=true -Dtests.locale=en -Dtests.timezone=America/St_Barthelemy
```

```
09:58:37 ERROR   0.32s J0 | ReadActionsTests.testEmptyAuthorizedIndicesSearchForWildcard <<< FAILURES!
09:58:37    > Throwable LINK REDACTED: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: Must specify at least one alias action;
09:58:37    > 	at __randomizedtesting.SeedInfo.seed([6905B0F3BC9A59AE:3EC5FAC192761760]:0)
09:58:37    > 	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29)
09:58:37    > 	at org.elasticsearch.action.admin.indices.alias.IndicesAliasesRequest.validate(IndicesAliasesRequest.java:460)
09:58:37    > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:131)
09:58:37    > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84)
09:58:37    > 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
09:58:37    > 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
09:58:37    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
09:58:37    > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67)
09:58:37    > 	at org.elasticsearch.client.support.AbstractClient$1.doExecute(AbstractClient.java:1784)
09:58:37    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
09:58:37    > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67)
09:58:37    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
09:58:37    > 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
09:58:37    > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
09:58:37    > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
09:58:37    > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
09:58:37    > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:110)
09:58:37    > 	at org.elasticsearch.test.SecurityIntegTestCase.createIndicesWithRandomAliases(SecurityIntegTestCase.java:422)
09:58:37    > 	at org.elasticsearch.xpack.security.authz.ReadActionsTests.testEmptyAuthorizedIndicesSearchForWildcard(ReadActionsTests.java:125)
09:58:37    > 	at java.lang.Thread.run(Thread.java:748)
```

### LINKED ISSUE #33123: [CI] org.elasticsearch.xpack.security.authz.ReadActionsTests testEmptyAuthorizedIndicesSearchForAllDisallowNoIndices failure
This test method seems to have been [failing before here](https://github.com/elastic/x-pack-elasticsearch/issues/2552#issuecomment-410660412) and [here](https://github.com/elastic/elasticsearch/issues/30098).

And just like before, it doesn't reproduce for me locally at all.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/254/console

```
gradlew :x-pack:plugin:security:test -Dtests.seed=9FE3840CBE452353 -Dtests.class=org.elasticsearch.xpack.security.authz.ReadActionsTests -Dtests.method="testEmptyAuthorizedIndicesSearchForAllDisallowNoIndices" -Dtests.security.manager=true -Dtests.locale=en-ZW -Dtests.timezone=Asia/Pyongyang -Dcompiler.java=10 -Druntime.java=10
```

```
15:04:23  ERROR   0.85s J3 | ReadActionsTests.testEmptyAuthorizedIndicesSearchForAllDisallowNoIndices <<< FAILURES!
15:04:23     > Throwable #1: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: Must specify at least one alias action;
15:04:23     > 	at __randomizedtesting.SeedInfo.seed([9FE3840CBE452353:DB3C392D6D510510]:0)
15:04:23     > 	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:26)
15:04:23     > 	at org.elasticsearch.action.admin.indices.alias.IndicesAliasesRequest.validate(IndicesAliasesRequest.java:540)
15:04:23     > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:128)
15:04:23     > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81)
15:04:23     > 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:87)
15:04:23     > 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:76)
15:04:23     > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:395)
15:04:23     > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67)
15:04:23     > 	at org.elasticsearch.client.support.AbstractClient$1.doExecute(AbstractClient.java:1776)
15:04:23     > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:395)
15:04:23     > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67)
15:04:23     > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:395)
15:04:23     > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:384)
15:04:23     > 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1242)
15:04:23     > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46)
15:04:23     > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:53)
15:04:23     > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:93)
15:04:23     > 	at org.elasticsearch.test.SecurityIntegTestCase.createIndicesWithRandomAliases(SecurityIntegTestCase.java:443)
15:04:23     > 	at org.elasticsearch.xpack.security.authz.ReadActionsTests.testEmptyAuthorizedIndicesSearchForAllDisallowNoIndices(ReadActionsTests.java:106)
```

### PR DESCRIPTION
**Pull request by colings86**
`SecurityIntegTestCase.createIndicesWithRandomAliases` could randomly
fail because its not gauranteed that the randomness of which aliases to
add to the `IndicesAliasesRequestBuilder` would always select at least
one alias to add. This change fixes the problem by keeping track of
whether we have added an alias to teh request and forcing the last
alias to be added if no other aliases have been added so far.

Closes #30098
Closes #33123

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java [hunk 1]
```diff
@@ -420,14 +420,18 @@ protected void createIndicesWithRandomAliases(String... indices) {
         createIndex(indices);
 
         if (frequently()) {
+            boolean noAliasAdded = true;
```
Comment (jasontedor) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java]: I think `aliasAdded = false;` is clearer.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java [hunk 2]
```diff
@@ -420,14 +420,18 @@ protected void createIndicesWithRandomAliases(String... indices) {
...
             IndicesAliasesRequestBuilder builder = client().admin().indices().prepareAliases();
             for (String index : indices) {
                 if (frequently()) {
                     //one alias per index with prefix "alias-"
                     builder.addAlias(index, "alias-" + index);
+                    noAliasAdded = false;
```
Comment (jasontedor) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java]: `aliasAdded = true;`

File: x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java [hunk 3]
```diff
@@ -420,14 +420,18 @@ protected void createIndicesWithRandomAliases(String... indices) {
...
                 }
             }
-            if (randomBoolean()) {
+            // If we get to this point and we haven't added an alias to the request we need to add one 
+            // or the request will fail so use noAliasAdded to force adding the alias in this case 
+            if (noAliasAdded || randomBoolean()) {
```
Comment (jasontedor) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java]: `aliasAdded == false`

**Review by jasontedor — COMMENTED** [review]
I left a suggestion. Also, if you force the `frequently()` on line 423 to `true`, the `frequently()` on line 426 to `false`, and the `randomBoolean()` on line 434 to `false`, do all of the tests in `ReadActionsTests` pass?

**Comment by colings86** [comment]
> if you force the frequently() on line 423 to true, the frequently() on line 426 to false, and the randomBoolean() on line 434 to false, do all of the tests in ReadActionsTests pass?
Tested and can confirm

**Review by jasontedor — APPROVED** [review]
🚢

**Comment by jaymode** [comment]
thanks @colings86 and @jasontedor
