### PR TITLE
Fixing testComplicatedBucketPath for avg bucket agg

### LINKED ISSUE #87155: [CI] AvgBucketAggregatorTests testComplicatedBucketPath failing
ParallelCompositeReader is not a DirectoryReader
they both inherit from BaseCompositeReader
hence a class cast exception. The cast was there since 2015, the hierarchy is the same in v8 and v9. 
Maybe something changed in lucene logic that makes the cast unsafe now?

**Build scan:**
https://gradle-enterprise.elastic.co/s/ff2icnremjen2/tests/:server:test/org.elasticsearch.search.aggregations.pipeline.AvgBucketAggregatorTests/testComplicatedBucketPath

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.pipeline.AvgBucketAggregatorTests.testComplicatedBucketPath" -Dtests.seed=CC087A41F7C0B509 -Dtests.locale=sl-SI -Dtests.timezone=Asia/Pyongyang -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.pipeline.AvgBucketAggregatorTests&tests.test=testComplicatedBucketPath

**Failure excerpt:**
```
java.lang.ClassCastException: class org.apache.lucene.index.ParallelCompositeReader cannot be cast to class org.apache.lucene.index.DirectoryReader (org.apache.lucene.index.ParallelCompositeReader and org.apache.lucene.index.DirectoryReader are in unnamed module of loader 'app')

  at __randomizedtesting.SeedInfo.seed([CC087A41F7C0B509:AF5F1AA6D9FE896]:0)
  at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:283)
  at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:256)
  at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.getMaxOrd(TermsAggregatorFactory.java:361)
  at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory$1.build(TermsAggregatorFactory.java:116)
  at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:312)
  at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:41)
  at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:81)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:243)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:554)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:498)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:471)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:452)
  at org.elasticsearch.search.aggregations.pipeline.AvgBucketAggregatorTests.testComplicatedBucketPath(AvgBucketAggregatorTests.java:189)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by benwtrent**
The test was erroneously creating a test Lucene index reader directly. This means that sometimes the reader was wrapped as a Parallel (threaded) reader which we don't support yet. 

This commit cleans up the test and uses AggregatorTestCase#newIndexSearcher directly.

closes https://github.com/elastic/elasticsearch/issues/87155

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/pipeline/AvgBucketAggregatorTests.java [hunk 1]
```diff
@@ -153,51 +154,23 @@ public void testComplicatedBucketPath() throws IOException {
...
-                    10000,
-                    new MappedFieldType[] { fieldType, valueFieldType, keywordField }
-                );
-                internalTerms = searchAndReduce(
-                    indexSearcher,
-                    query,
-                    termsBuilder,
-                    10000,
-                    new MappedFieldType[] { fieldType, valueFieldType, keywordField }
-                );
```
Comment (benwtrent) [inline server/src/test/java/org/elasticsearch/search/aggregations/pipeline/AvgBucketAggregatorTests.java:195]: Re-reading the test, I realized that none of these were necessary. Cleaning up.

File: server/src/test/java/org/elasticsearch/search/aggregations/pipeline/AvgBucketAggregatorTests.java [hunk 2]
```diff
@@ -153,51 +154,23 @@ public void testComplicatedBucketPath() throws IOException {
...
                 }
             }
 
-            InternalAvg avgResult;
-            InternalDateHistogram histogramResult;
             InternalFilter filterResult;
-            InternalTerms<?, ?> internalTerms;
             try (IndexReader indexReader = DirectoryReader.open(directory)) {
-                IndexSearcher indexSearcher = newSearcher(indexReader, true, true);
+                IndexSearcher indexSearcher = newIndexSearcher(indexReader);
```
Comment (benwtrent) [inline server/src/test/java/org/elasticsearch/search/aggregations/pipeline/AvgBucketAggregatorTests.java:164]: This is the key change. I was using the newSearcher method from lucene tests which randomly wraps it as a parallel reader, which we don't support.

**Review by not-napoleon — APPROVED** [review]
LGTM
