### PR TITLE
Tests- added helper methods to ESRestTestCase for checking warnings

### LINKED ISSUE #36251: ESRestTestCase - assertWarnings does not work
When we deprecate a server endpoint, REST test clients start failing and there's no way to write tests that check the particular warnings issued.

Rest tests currently have a stark choice:
* fail all uses of deprecated calls in a test class (setStrictDeprecationMode=true)
* ignore all deprecation warnings in a test class (setStrictDeprecationMode=false)

What we'd ideally like is to be able to write tests that check the deprecated calls we make produce the warnings we'd expect and the ESTestCase base class already has a method to do just this: `assertWarnings`.

Sadly, `assertWarnings` currently only works in server-side tests. It relies on ThreadLocals populated by calls to DeprecationLogger deep down in the server call stack. These warnings do not get materialised in remote clients like ESRestTestCase.  Ideally the Rest client would be able to take the HTTP warning headers it already knows about in `Response.getWarnings()` and make them available for checks in ESTestCase.assertWarnings. Maybe we could achieve that by also having a form of DeprecationLogger on the client? At the very least, `assertWarnings` should throw an Unsupported exception in ESRestTestCase if we don't have the means to propagate warnings.

Related: @nik9000  has https://github.com/elastic/elasticsearch/pull/36126 in flight for LLRC which helps shift the failure strictness from a class level to a method level but I don't think that helps fulfil the goal of making EsRestTestCase.assertWarnings work as expected.

### PR DESCRIPTION
**Pull request by markharwood**
Helper method for checking mixed and current-version-only clusters in Java REST tests that use LLRC or HLRC apis.

Closes #36251

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
         assert hasXPack != null;
         assert nodeVersions != null;
     }
+    
+    // Helper class to check warnings in REST responses with sensitivity to versions
+    // used in the target cluster.
+    protected class VersionSensitiveWarningsHandler implements WarningsHandler {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I *think* it'd be nicer if this were `public` and `static`, maybe in its own file. There are places were we can't use `expectVersionSpecificWarnings` and there are places where we want to make calls that aren't subclasses of `ESTestCase`. We have precident for this, specifically making `client()` `public` and `static`.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
...
+                if(version.equals(Version.CURRENT)) {
+                    return true;
+                }                
+            }
+            return false;
+        }    
+        
+    }
+    
+    protected RequestOptions expectVersionSpecificWarnings(Consumer<VersionSensitiveWarningsHandler> expectationsSetter) {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Same argument for `public` and `static`.

Do you think this should take `VersionSensistiveWarningsHandler` as an argument?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 3]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
...
         assert nodeVersions != null;
     }
+    
+    // Helper class to check warnings in REST responses with sensitivity to versions
+    // used in the target cluster.
+    protected class VersionSensitiveWarningsHandler implements WarningsHandler {
+        Set<String> requiredSameVersionClusterWarnings = new HashSet<>();
+        Set<String> allowedWarnings = new HashSet<>();
+
+        public void current(String... requiredWarnings) {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Javadoc would make this make more sense I think. It looks to me like "warnings emitted by the current version".

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 4]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
...
+            requiredSameVersionClusterWarnings.addAll(Arrays.asList(requiredWarnings));
+            if(clusterHasACurrentVersionNode()) {
+                // as a convenience add all of the current-version warnings to the allowed
+                // warnings because at least one node in the cluster is a current-version node
+                // and so we assume it can return these responses
+                allowedWarnings.addAll(Arrays.asList(requiredWarnings));
+            }
+        }
+
+        public void other(String... allowedWarnings) {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Maybe another name. Like, `compatible` maybe? These are warnings that are emitted by compatible versions.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 5]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
...
+                    if (false == allowedWarnings.contains(actualWarning)) {
+                        return true;
+                    }
+                }
+                return false;
+            }
+        }
+        
+        private boolean isExclusivelyTargetingCurrentVersionCluster() {
+            return nodeVersions.size() == 0 && nodeVersions.first().equals(Version.CURRENT);
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Should we `assert(nodeVersions, not(isEmpty()));` here?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 6]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
...
+    
+    // Helper class to check warnings in REST responses with sensitivity to versions
+    // used in the target cluster.
+    protected class VersionSensitiveWarningsHandler implements WarningsHandler {
+        Set<String> requiredSameVersionClusterWarnings = new HashSet<>();
+        Set<String> allowedWarnings = new HashSet<>();
+
+        public void current(String... requiredWarnings) {
+            requiredSameVersionClusterWarnings.addAll(Arrays.asList(requiredWarnings));
+            if(clusterHasACurrentVersionNode()) {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Do we need this if statement actually?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 7]
```diff
@@ -177,6 +182,66 @@ public void initClient() throws IOException {
...
+        @Override
+        public boolean warningsShouldFailRequest(List<String> warnings) {
+            if (isExclusivelyTargetingCurrentVersionCluster()) {
+                // absolute equality required in expected and actual.
+                Set<String> actual = new HashSet<>(warnings);
+                return false == requiredSameVersionClusterWarnings.equals(actual);
+            } else {
+                // Some known warnings can safely be ignored
+                for (String actualWarning : warnings) {
+                    if (false == allowedWarnings.contains(actualWarning)) {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Should we check if the thing is in `requiredSameVersionClusterWarnings` as well rather than add it in both spots?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/SearchIT.java [hunk 8]
```diff
@@ -224,6 +224,17 @@ public void testSearchNoQuery() throws IOException {
         }
     }
 
+    public void testSearchNoQueryDeprecated() throws IOException {
+        SearchRequest searchRequest = new SearchRequest("index");
+        searchRequest.types("foo");
+        SearchResponse searchResponse = execute(searchRequest, highLevelClient()::search, highLevelClient()::searchAsync,
+                expectVersionSpecificWarnings((v) -> {
+                    v.current("[types removal] Specifying types in search requests is deprecated.");
+                    v.other("Some legacy warning that may or may not be returned");
```
Comment (nik9000) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/SearchIT.java]: Remember to drop this example before committing!

**Review by nik9000 — COMMENTED** [review]
I think this is a great idea! I left a bunch of small stuff but I think it'll be super nice.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I think it'd be nice to have a small unit test for this.

Comment (markharwood) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: OK - I'll need to pass Set<Version> into the constructor as this is currently an inner class with direct access to EsRestTestCase.nodeVersions.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 6 above)
Comment (markharwood) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I did wonder about that too. Let's drop it.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Hmmmm. I'd be ok with a `public static SortedSet<Version> nodeVersions()` on `ESRestTestCase`. What do you think?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 2 above)
Comment (markharwood) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: The main goal of this helper method was trying to minimise the code required in tests to pass warning lists (I suspect we'll end up with a lot of calls from tests).
I wanted tests to call a helper function with `String...` typed params but of course a method/constructor can only take one of those variable length params which is why I needed 2 method invocations and this seemed like a shorthand way of doing that without clients having to call ` expect(new VersionSensitiveWarningsHandler(currentWarnings).other(allowedWarnings))`.  We'd also need to pass `Set<Version> nodeVersions` into this object too. Happy to take any alternative suggestions though.

Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Hmmm. I see what you mean here. I don't think you need to pass the `Set<Version>` because I think that can be publicly exposed on `ESRestTestCase`. The rest, yeah, I was hoping for a fluent interface, but i see how repeating the words doesn't help. I think taking the `Consumer` is fine. It is certainly easier to read and we're going to have this all over the place. So +1 for keeping the consumer.

Comment (markharwood) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: If you want VersionSensitiveWarningsHandler to work outside of EsRestTestCase (which I think you said was the case) then maybe we make it a standalone class with minimal dependencies and make the `EsRestTestCase.expectVersionSpecificWarnings` impl call VSWH constructor with `Set<Version>` rather than have VSWH reaching back to ESRestTestCase.nodeVersions to see this info

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (markharwood) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I overlooked the fact nodeVersions is already static. See following comment below on EsRestTestCase and VersionSpecificWarningsHandler dependencies

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 2 above)
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I don't think we'd want it to work if you aren't *running* an `ESRestTestCase`, but it'd be nice if it worked if you didn't *extend* from `ESRestTestCase`.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 9]
```diff
@@ -177,6 +181,69 @@ public void initClient() throws IOException {
         assert hasXPack != null;
         assert nodeVersions != null;
     }
+    
+    // Helper class to check warnings in REST responses with sensitivity to versions
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Could you use Javadoc here? I'm just so used to it in this context that anything else is like a cognitive speed bump.

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Thanks for doing this @markharwood!

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 10]
```diff
@@ -177,6 +181,71 @@ public void initClient() throws IOException {
...
+        
+        private boolean isExclusivelyTargetingCurrentVersionCluster() {
+            assertFalse("Node versions running in the cluster are missing", testNodeVersions.isEmpty());
+            return testNodeVersions.size() == 1 && 
+                    testNodeVersions.iterator().next().equals(Version.CURRENT);
+        } 
+        
+    }
+    
+    public static RequestOptions expectVersionSpecificWarnings(Consumer<VersionSensitiveWarningsHandler> expectationsSetter) {
```
Comment (javanna) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: nit: maybe this should be protected?

**Review by javanna — APPROVED** [review]

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 10 above)
Comment (markharwood) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: It was protected originally but Nik requested it be made public static to allow use from elsewhere.

**Comment by markharwood** [comment]
Thanks for the reviews @nik9000 and @javanna
