### PR TITLE
Bugfix: Deleted async search won't show on any API

### LINKED ISSUE #132423: Async search status endpoint returns for deleted search
### Elasticsearch Version

9.2.0-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

If you delete an async search, the async search status endpoint does not indicate that the search request is deleted and it seems to keep running.

### Steps to Reproduce

1. Submit an async search (`POST _async_search`) (for reproducing this bug, it needs to take awhile)
2. Delete the search (`DELETE _async_search/{id}`)

```
{
  "acknowledged": true
}
```

3. Get the status (`GET _async_search/status/{id}`) 

```
{
  "id": "FnIybFJmcFRjU1JTLV9RWFd1dDEwRmceOU40cFl4Mk5RZW1uSkZCYjQ4NVNNUTozNDQ5MDYw",
  "is_running": true,
  "is_partial": true,
  "start_time_in_millis": 1754347528891,
  "expiration_time_in_millis": 1754952334175,
  "_shards": {
    "total": 1,
    "successful": 0,
    "skipped": 0,
    "failed": 0
  }
}
```

The status is returned as if it hasn't been deleted. This is in contrast with what happens if you call `GET _async_search/{id}` directly (which correctly reports the search cannot be found, since it has been deleted):

```
{
  "error": {
    "root_cause": [
      {
        "type": "resource_not_found_exception",
        "reason": "FnIybFJmcFRjU1JTLV9RWFd1dDEwRmceOU40cFl4Mk5RZW1uSkZCYjQ4NVNNUTozNDQ5MDYw"
      }
    ],
    "type": "resource_not_found_exception",
    "reason": "FnIybFJmcFRjU1JTLV9RWFd1dDEwRmceOU40cFl4Mk5RZW1uSkZCYjQ4NVNNUTozNDQ5MDYw"
  },
  "status": 404
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by eranweiss-elastic**
Deleted async search will no longer return 200 and a full response on DELETE and GET /_async_search/status/{id} while the query is running. Instead, it will return 404 Resource Not Found, as expected.

Closes #132423

### CODE REVIEW

File: x-pack/plugin/async-search/src/javaRestTest/java/org/elasticsearch/xpack/search/AsyncSearchDeleteIT.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+                }
+              }
+            }""";
+
+        Response submitResp = submitAsyncSearchWithJsonBody(indexName, query, TimeValue.timeValueMillis(10), user);
+        assertOK(submitResp);
+        String id = extractResponseId(submitResp);
+
+        Response delResp = deleteAsyncSearch(id, user);
+        assertOK(delResp);
```
Comment (chrisparrinello) [inline x-pack/plugin/async-search/src/javaRestTest/java/org/elasticsearch/xpack/search/AsyncSearchDeleteIT.java:77]: Based on the PR description, the only thing that this request should return is the 200 status code and just the `acknowledged: true` response body? Should we assert on the response body as well. It seems like there was some different behavior based on [this](https://github.com/elastic/elasticsearch/issues/132423#issuecomment-3719852892) comment.

Comment (eranweiss-elastic) [reply x-pack/plugin/async-search/src/javaRestTest/java/org/elasticsearch/xpack/search/AsyncSearchDeleteIT.java:77]: Good point, thanks. I've added an assert on the body.

Comment (chrisparrinello) [reply x-pack/plugin/async-search/src/javaRestTest/java/org/elasticsearch/xpack/search/AsyncSearchDeleteIT.java:77]: Thanks! Looks good!

**Review by chrisparrinello — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/index/mapper/MultiValuedBinaryDocValuesField.java [hunk 2]
```diff
@@ -54,7 +54,7 @@ public int count() {
     protected void writeLenAndValues(BytesStreamOutput out) throws IOException {
         // sort the ArrayList variant of the collection prior to serializing it into a binary array
         if (values instanceof ArrayList<BytesRef> list) {
-           list.sort(Comparator.naturalOrder());
+            list.sort(Comparator.naturalOrder());
```
Comment (smalyshev) [inline server/src/main/java/org/elasticsearch/index/mapper/MultiValuedBinaryDocValuesField.java:57]: Is this ws change intentional?

Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/index/mapper/MultiValuedBinaryDocValuesField.java:57]: It's an auto-commit from spotless, after I updated the branch
