### PR TITLE
Flush translog writer before adding new operation

### LINKED ISSUE #63299: TranslogTests.testFatalIOExceptionsWhileWritingConcurrently fails
Stacktrace:

java.lang.AssertionError: expected:<98> but was:<99>
	at __randomizedtesting.SeedInfo.seed([6FCCE4EB877E5B57:3804632485A8F914]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.index.translog.TranslogTests.testFatalIOExceptionsWhileWritingConcurrently(TranslogTests.java:2357)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Reproduces locally?**:

I am able to consistently reproduce when I run 1K times in Intellij.

**Applicable branches**:

Master

This is what is happening here:

In the past, the first thing we did was write the operation to a buffered output stream which may or may not involve flushing the file. There are no guarantees at this point. After that, we marked some metadata about the operation being added to the translog.

Now we add the operation to the buffer and increment metadata. After that, if the buffer is full, we flush. This is the first time we have the options for the mocked exceptions thrown in this test. Occasionally, the exception is thrown and our test infrastructure assumed this operation was not added successfully. However, it was and the metadata was incremented. So, the total operations are not what we expect.

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently we flush the Translog buffer when a new operation causes the
buffer to breach 1MB. This introduces a scenario where an exception is
thrown AFTER the writer has accepted the operation. To avoid this, this
commit flushes the Translog in an #add call before adding a new
operation.

This fixes #63299.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 1]
```diff
@@ -185,8 +186,12 @@ private synchronized void closeWithTragicEvent(final Exception ex) {
...
+        long bufferedBytesBeforeAdd = this.bufferedBytes;
+        if (bufferedBytesBeforeAdd >= forceWriteThreshold) {
+            writeBufferedOps(Long.MAX_VALUE, bufferedBytesBeforeAdd >= forceWriteThreshold * 4);
+        }
+
         final Translog.Location location;
-        final long bytesBufferedAfterAdd;
         synchronized (this) {
             ensureOpen();
             if (buffer == null) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java:197]: Would it make sense to add:
```
assert bufferedBytes == buffer.size()
```
(3 lines down).

**Review by henningandersen — APPROVED** [review]
LGTM.
