### PR TITLE
AllTermQuery must implement equals/hashCode.

### LINKED ISSUE #13662: Elastic 2.0 beta returning wrong results from cache?
I have an array with categories in which i have genres like for example Comedy. I search for documents that contain that and other genres using filtered query in which i have empty query and terms filter. 
Next i use match query on for example title field + terms filter for genres and choose Comedy. On third query i do exact search like first one so only look for Comedy in genres (only using terms filter and empty query) and i get results of last match search (so second query results) which are obviously wrong.

### LINKED ISSUE #20161: Some boolean filters result in errors like "[and] query does not support [field1]"
Elasticsearch version: 2.3.5
Getting unexpected errors from some queries with filters. These queries worked with Elasticsearch version 1.7.5, but fail on version 2.3.5. Below are steps to reproduce.
 1. Create an index
```
PUT testindex
{
    "mappings" : {
        "type1" : {
            "properties" : {
                "field1" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }
}
```
 2. Issue the following query:
```
POST
{
    "query" : {
        "match_all" : {}
    },
    "post_filter" : {
        "not" : {
            "and" : [
                {
                    "query" : {
                        "term" : {
                            "field1" : "1234"
                        }
                    }
                }
            ]
        }
    }
}
```
And the result is:
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "query_parsing_exception",
      "reason" : "[and] query does not support [field1]",
      "index" : "testindex",
      "line" : 11,
      "col" : 29
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query_fetch",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "testindex",
      "node" : "0JJWSN2WRwaX1dvaW3yPfA",
      "reason" : {
        "type" : "query_parsing_exception",
        "reason" : "[and] query does not support [field1]",
        "index" : "testindex",
        "line" : 11,
        "col" : 29
      }
    } ]
  },
  "status" : 400
}
```
Expected result, as it also works in Elasticsearch version 1.7.5:
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

### PR DESCRIPTION
**Pull request by jpountz**
This is required as queries are used as keys in the filter cache. Currently
all AllTermQuery instances are considered equals.

Closes #20161
Closes #13662

### CODE REVIEW

**Comment by nik9000** [comment]
Lgtm

File: core/src/test/java/org/elasticsearch/common/lucene/all/SimpleAllTests.java [hunk 1]
```diff
@@ -374,4 +374,13 @@ public void testNoTokensWithKeywordAnalyzer() throws Exception {
         assertThat(docs.totalHits, equalTo(1));
         assertThat(docs.scoreDocs[0].doc, equalTo(0));
     }
+
+    public void testEquals() {
+        Term bar = new Term("foo", "bar");
+        Term baz = new Term("foo", "baz");
+        assertEquals(new AllTermQuery(bar), new AllTermQuery(bar));
+        assertFalse(new AllTermQuery(bar).equals(new AllTermQuery(baz)));
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/lucene/all/SimpleAllTests.java]: Maybe rewrite this using `assertNotEquals`? It makes it symmetric with the previous line so that it's clearer, and it gives better failure messages from JUnit when the assertion fails.

File: core/src/test/java/org/elasticsearch/common/lucene/all/SimpleAllTests.java [hunk 2]
```diff
@@ -374,4 +374,13 @@ public void testNoTokensWithKeywordAnalyzer() throws Exception {
...
+        assertEquals(new AllTermQuery(bar).hashCode(), new AllTermQuery(bar).hashCode());
+        assertFalse(new AllTermQuery(bar).hashCode() == new AllTermQuery(baz).hashCode());
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/lucene/all/SimpleAllTests.java]: Same suggestion here for `assertNotEquals`.

**Comment by jasontedor** [comment]
I left a suggestion, but it's fine either way and no need for a second round whatever you decide. LGTM.

**Comment by jpountz** [comment]
Thanks @jasontedor and @nik9000! I applied Jason's suggestion before merging.

**Comment by jpountz** [comment]
For the record, the bug does not exist on 1.7 either.
