### PR TITLE
[ML] Prevent stack overflow while copying ML jobs and datafeeds

### LINKED ISSUE #36360: StackOverflowError somewhere in the cluster applier thread
A user reported that their master node died with the following exception

```
[2018-11-16T09:59:05,744][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [REDACTED] fatal error in thread [elasticsearch[REDACTED][clusterApplierService#updateTask][T#1]], exiting
java.lang.StackOverflowError: null
        at java.util.Collections$UnmodifiableList$1.<init>(Collections.java:1339) ~[?:1.8.0_111]
        at java.util.Collections$UnmodifiableList.listIterator(Collections.java:1337) ~[?:1.8.0_111]
        at java.util.Collections$UnmodifiableList$1.<init>(Collections.java:1339) ~[?:1.8.0_111]
        at java.util.Collections$UnmodifiableList.listIterator(Collections.java:1337) ~[?:1.8.0_111]
```

This repeats until the end of the file. As far as I can tell, this can't be an _infinite_ recursion, but it could be very deeply nested if an unmodifiable list is repeatedly rewrapped.

It is possible this was introduced by #31957 which looks like it might re-wraps some lists in `unmodifiableList` each time a new `DatafeedConfig` is constructed.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
ML jobs and datafeeds wrap collections into their unmodifiable
equivalents in their constructor. However, the copying builder
does not make a copy of some of those collections resulting
in wrapping those again and again. This can eventually result
to stack overflow.

This commit addressed this issue by copying the collections in
question in the copying builder constructor.

Closes #36360

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 1]
```diff
@@ -606,14 +605,14 @@ public Builder(DatafeedConfig config) {
...
             this.frequency = config.frequency;
-            this.indices = config.indices;
-            this.types = config.types;
-            this.query = config.query;
-            this.aggregations = config.aggregations;
-            this.scriptFields = config.scriptFields;
+            this.indices = new ArrayList<>(config.indices);
+            this.types = new ArrayList<>(config.types);
+            this.query = config.query == null ? null : new HashMap<>(config.query);
+            this.aggregations = config.aggregations == null ? null : new HashMap<>(config.aggregations);
```
Comment (droberts195) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: I think `query` and `aggregations` should use `LinkedHashMap` to retain the original order.

**Review by droberts195 — APPROVED** [review]
LGTM
