### PR TITLE
EQL: fix async missing events

### LINKED ISSUE #97644: EQL: async search with missing events fails with NPE
### Elasticsearch Version

8.10.0-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Windows

### Problem Description

When using async search with missing events, there is a failure to add the saved search to the async-search index, due to a serialization issue.

### Steps to Reproduce

```
PUT /test
{
  "mappings": {
    "dynamic": false,
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "event.category": {
        "type": "keyword"
      }
    }
  }
}


POST /test/_doc
{
   "@timestamp": "2023-07-11T11:09:05.529Z",
   "event.category": "process"
}

POST /test/_doc
{
   "@timestamp": "2023-07-11T11:09:05.529Z",
   "event.category": "process"
}

POST /test/_eql/search
{
 "wait_for_completion_timeout": "0ms",
  "keep_alive": "60s",
  "query": "sequence with maxspan=24h  [ process where true ]  ![ process where true ]  "
}
```

### Logs (if relevant)

```
failed to store eql search results for [FlAyZWItOTRBVFBLckJrSWNyZFBaamcdWGdhTmV6UV9RNDJYZVFqeFRWSEpQZzoxNDY5MDY=] java.lang.NullPointerException: Cannot invoke "org.elasticsearch.common.io.stream.Writeable.writeTo(org.elasticsearch.common.io.stream.StreamOutput)" because "v" is null
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.lambda$writeCollection$35(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1060)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeList(StreamOutput.java:1048)
at org.elasticsearch.xpack.eql.action.EqlSearchResponse$Sequence.writeTo(EqlSearchResponse.java:408)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.lambda$writeCollection$35(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1060)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1041)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeList(StreamOutput.java:1048)
at org.elasticsearch.xpack.eql.action.EqlSearchResponse$Hits.writeTo(EqlSearchResponse.java:505)
at org.elasticsearch.xpack.eql.action.EqlSearchResponse.writeTo(EqlSearchResponse.java:125)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:968)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.StoredAsyncResponse.writeTo(StoredAsyncResponse.java:64)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.writeResponse(AsyncTaskIndexService.java:575)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.lambda$createResponseForEQL$1(AsyncTaskIndexService.java:222)
at org.elasticsearch.xcontent@8.10.0-SNAPSHOT/org.elasticsearch.xcontent.XContentBuilder.lambda$directFieldAsBase64$24(XContentBuilder.java:1229)
at org.elasticsearch.xcontent.impl@8.10.0-SNAPSHOT/org.elasticsearch.xcontent.provider.json.JsonXContentGenerator.writeDirectField(JsonXContentGenerator.java:543)
at org.elasticsearch.xcontent@8.10.0-SNAPSHOT/org.elasticsearch.xcontent.XContentBuilder.directFieldAsBase64(XContentBuilder.java:1223)
at org.elasticsearch.xcore@8.10.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.createResponseForEQL(AsyncTaskIndexService.java:222)
at org.elasticsearch.xpack.ql.async.AsyncTaskManagementService.storeResults(AsyncTaskManagementService.java:268)
at org.elasticsearch.xpack.ql.async.AsyncTaskManagementService.storeResults(AsyncTaskManagementService.java:263)
at org.elasticsearch.xpack.ql.async.AsyncTaskManagementService.lambda$wrapStoringListener$3(AsyncTaskManagementService.java:237)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.plugin.TransportEqlSearchAction.lambda$operation$2(TransportEqlSearchAction.java:245)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.execution.search.BasicQueryClient.lambda$fetchHits$3(BasicQueryClient.java:179)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.execution.search.PITAwareQueryClient.lambda$pitListener$3(PITAwareQueryClient.java:118)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.xpack.eql.execution.search.RuntimeUtils.lambda$multiSearchLogListener$1(RuntimeUtils.java:92)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onResponse(NodeClient.java:160)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:205)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:199)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:180)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:166)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:154)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:151)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onResponse(NodeClient.java:160)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:205)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:199)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:723)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:470)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:464)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:470)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:464)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:273)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:110)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:119)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:90)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
at org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes #97644

Missing events were represented as `null` values (before converting them to `{missing: true}` JSON), but in some circumstances events have to be serialized, eg. when executing an async search, and that caused a NPE.
This PR replaces the `null` placeholder with a constant `Event` instance to represent missing events, allowing proper serialization.

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java [hunk 1]
```diff
@@ -202,6 +203,8 @@ public String toString() {
     // Event
     public static class Event implements Writeable, ToXContentObject {
 
+        public static Event MISSING = new Event("", "", BytesArray.EMPTY, null);
```
Comment (luigidellaquila) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:206]: It would be better to distinguish missing events from actual events with a new flag in the serialization, but it would require a version increment, and it's probably not worth it.
An "empty" event (empty index, empty id, empty source) should be enough.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java [hunk 2]
```diff
@@ -417,7 +425,7 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
             if (events.isEmpty() == false) {
                 builder.startArray(Fields.EVENTS);
                 for (Event event : events) {
-                    if (event == null) {
+                    if (event == null || event == Event.MISSING) {
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:428]: Why is null still a valid option here?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java [hunk 3]
```diff
@@ -263,6 +266,11 @@ public Event(StreamInput in) throws IOException {
             }
         }
 
+        public static Event readFrom(StreamInput in) throws IOException {
+            Event result = new Event(in);
+            return result.equals(MISSING) ? MISSING : result;
```
Comment (bpintea) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:271]: Would a boolean as null indicator work as well, similar to the serialisation of other ["optionals"](server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java)? Though having a marker object works too.

**Review by bpintea — APPROVED** [review]
LGTM, but wondering about the object-as-null choice.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:206]: If the `null` occurrence plus serialisation issue is rare, I guess having `MISSING` is ok. Otherwise, having a version gated behaviour might be acceptable.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:428]: Good point, it can be removed 👍

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:271]: The problem is actually in serialization: the events are in a collection nested in the EQL response, and `StreamOutput.writeCollection()` cannot handle nulls, so a local fix (eg. a boolean in the serialization) is not enough

Comment (bpintea) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:271]: I was wondering if the "local" serialisation couldn't deal with a boolean flag, rather than de-/serialise an Event-as-null. But yes, it might require version-dependent behaviour, if this had worked at all before.

**Comment by luigidellaquila** [comment]
But it has a huge impact, now all the events have `"missing": false`...
Trying to find a better solution

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by bpintea — APPROVED** [review]
Left some questions, but functionally and from testing perspective it LGTM.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java [hunk 4]
```diff
@@ -323,9 +362,13 @@ public Map<String, DocumentField> fetchFields() {
             return fetchFields;
         }
 
+        public boolean missing() {
+            return Boolean.TRUE.equals(missing);
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:366]: Yes, it's just about the c'tor param (it has to be an Object, because it's optional - x-content bwc, you know), but it's probably better to have the attribute to be a `boolean`, I'll refactor it

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java [hunk 5]
```diff
@@ -202,23 +204,39 @@ public String toString() {
     // Event
     public static class Event implements Writeable, ToXContentObject {
 
+        public static Event MISSING_EVENT = new Event(
+            "_missing",
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:208]: Unless x-content parsers complain (and I don't think it's the case), it should be fine. Let me do it

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java [hunk 6]
```diff
@@ -261,6 +283,16 @@ public Event(StreamInput in) throws IOException {
...
+            if (in.getTransportVersion().onOrAfter(TransportVersion.V_8_500_038)) {
+                missing = in.readBoolean();
+            } else {
+                missing = false;
+            }
+        }
+
+        public static Event readFrom(StreamInput in) throws IOException {
+            Event result = new Event(in);
+            return result.missing() ? MISSING_EVENT : result;
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/action/EqlSearchResponse.java:295]: Here specifically it's just a small memory optimization; in other places I'm using the singleton in a more meaningful way.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/payload/EventPayload.java [hunk 7]
```diff
@@ -27,7 +27,7 @@ public EventPayload(SearchResponse response) {
         List<SearchHit> hits = RuntimeUtils.searchHits(response);
         values = new ArrayList<>(hits.size());
         for (SearchHit hit : hits) {
-            values.add(new Event(qualifiedIndex(hit), hit.getId(), hit.getSourceRef(), hit.getDocumentFields()));
+            values.add(new Event(qualifiedIndex(hit), hit.getId(), hit.getSourceRef(), hit.getDocumentFields(), false));
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/payload/EventPayload.java:30]: 👍 it will save us some changes in the tests code
