### PR TITLE
Remove empty results before merging

### LINKED ISSUE #126742: [CI] GeoDistanceIT testDistanceSortingWithUnmappedField failing
**Build Scans:**
- [elasticsearch-periodic #7620 / openjdk17_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/yak7bs3dh7ln4)
- [elasticsearch-periodic-platform-support #7614 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/537qlqaeyas26)
- [elasticsearch-periodic-platform-support #7614 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/vdqs5yvzjc5l2)
- [elasticsearch-periodic #7578 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/udwja2z7fxoqy)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.sort.GeoDistanceIT.testDistanceSortingWithUnmappedField" -Dtests.seed=6216A97CDE49EF02 -Dtests.locale=nn -Dtests.timezone=America/Creston -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.sort.GeoDistanceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDistanceSortingWithUnmappedField),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.action.search.SearchPhaseExecutionException: 
```

**Issue Reasons:**
- [8.x] 4 failures in test testDistanceSortingWithUnmappedField (1.8% fail rate in 221 executions)
- [8.x] 2 failures in pipeline elasticsearch-periodic (28.6% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by javanna**
We addressed the empty top docs issue with #126385 specifically for scenarios where empty top docs don't go through the wire. Yet they may be serialized from data node back to the coord node, in which case they will no longer be equal to Lucene#EMPTY_TOP_DOCS.

This commit expands the existing filtering of empty top docs to include also those that did go through serialization.

Closes #126742

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM, thanks!

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 1]
```diff
@@ -150,11 +150,12 @@ static TopDocs mergeTopDocs(List<TopDocs> results, int topN, int from) {
             return topDocs;
         } else if (topDocs instanceof TopFieldGroups firstTopDocs) {
             final Sort sort = new Sort(firstTopDocs.fields);
-            final TopFieldGroups[] shardTopDocs = results.stream().filter(td -> td != Lucene.EMPTY_TOP_DOCS).toArray(TopFieldGroups[]::new);
+            assert results.stream().noneMatch(topDoc -> topDoc == Lucene.EMPTY_TOP_DOCS);
+            final TopFieldGroups[] shardTopDocs = results.toArray(TopFieldGroups[]::new);
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:154]: I'm not entirely sure we can do that, can't we deal with this case by simply returning `null` here like we did before if the resulting `shardTopDocs` after filtering are an empty array? (I think there's cases where this can legitimately be empty looking at `org.elasticsearch.lucene.grouping.SinglePassGroupingCollector#getTopGroups` for example?)

All of that said, I'm really starting to think I simply did a bit of a bad job here upstream. If we simply don't pass the empty top docs into this method ever (like we used to without data node side batching) then we would simply return `null` out of the box and behavior is unchanged.

[the remark this answers is not in the document]
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java]: I tried the null handling one more time, and it seems to work this time. I had to add a bunch of odd null checks, but at least we can now distinguish between proper empty top docs and our own placeholder.

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 2]
```diff
@@ -722,7 +721,7 @@ private static final class QueryPerNodeState {
 
         private static final QueryPhaseResultConsumer.MergeResult EMPTY_PARTIAL_MERGE_RESULT = new QueryPhaseResultConsumer.MergeResult(
             List.of(),
-            Lucene.EMPTY_TOP_DOCS,
+            null,
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:724]: I am restoring using null, which is what we did before batched execution.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 3]
```diff
@@ -358,7 +364,7 @@ private MergeResult partialReduce(
                 }
             }
             // we have to merge here in the same way we collect on a shard
-            newTopDocs = topDocsList == null ? Lucene.EMPTY_TOP_DOCS : mergeTopDocs(topDocsList, topNSize, 0);
+            newTopDocs = topDocsList == null ? null : mergeTopDocs(topDocsList, topNSize, 0);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:367]: I am restoring using null, which is what we did before batched execution.

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 4]
```diff
@@ -140,24 +141,26 @@ static SortedTopDocs sortDocs(
     }
 
     static TopDocs mergeTopDocs(List<TopDocs> results, int topN, int from) {
-        if (results.isEmpty()) {
+        List<TopDocs> topDocsList = results.stream().filter(Objects::nonNull).toList();
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:144]: I am still unclear how `null` worked before without the filtering. Stuff breaks pretty badly if you let `null` go through here, but I don't understand how that did not happen before we introduced batched execution, given that we did allow `null`, but I guess we were never calling mergeTopDocs against null results, while we do so now.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:144]: Exactly we should just not let the `null`s get here was kinda my point initially, I think the way this PR does it now should be fine let me take a look :)

File: server/src/main/java/org/elasticsearch/common/lucene/Lucene.java [hunk 5]
```diff
@@ -384,7 +384,9 @@ public static void writeTotalHits(StreamOutput out, TotalHits totalHits) throws
      * by shard for sorting purposes.
      */
     public static void writeTopDocsIncludingShardIndex(StreamOutput out, TopDocs topDocs) throws IOException {
-        if (topDocs instanceof TopFieldGroups topFieldGroups) {
+        if (topDocs == null) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/common/lucene/Lucene.java:387]: I wonder if we should add BwC for this? I guess no need to if we merge to 8.19 right away since those tests didn't break in the first place and therefore we know that this branch is never taken :)

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 6]
```diff
@@ -140,24 +141,26 @@ static SortedTopDocs sortDocs(
...
             mergedTopDocs = TopFieldGroups.merge(sort, from, topN, shardTopDocs, false);
         } else if (topDocs instanceof TopFieldDocs firstTopDocs) {
-            final Sort sort = checkSameSortTypes(results, firstTopDocs.fields);
-            final TopFieldDocs[] shardTopDocs = results.stream().filter((td -> td != Lucene.EMPTY_TOP_DOCS)).toArray(TopFieldDocs[]::new);
+            TopFieldDocs[] shardTopDocs = topDocsList.toArray(TopFieldDocs[]::new);
+            final Sort sort = checkSameSortTypes(topDocsList, firstTopDocs.fields);
             mergedTopDocs = TopDocs.merge(sort, from, topN, shardTopDocs);
         } else {
-            final TopDocs[] shardTopDocs = results.toArray(new TopDocs[numShards]);
+            final TopDocs[] shardTopDocs = topDocsList.toArray(new TopDocs[numShards]);
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:163]: NiT: here and in the other array creation spots, if we change the line anyways lets make it a clean and faster zero size (new `Type[0]`) initialization for all of them like we had it before at some point? :)

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:144]: We never added `null` to this list because we didn't even queue empty query shard responses for merging. This sort of changed now because suggest+profiling aren't (yet) batched since we have no existing partial merge logic for those.
We can clean this up in a follow-up I had planned which leaves this logic on the transport thread (discussed in the previous PR on this), for now I think doing the filtering down here is fine :)

**Review by original-brownbear — APPROVED** [review]
LGTM unless the BwC tests complain :) thanks!

File: server/src/main/java/org/elasticsearch/common/lucene/Lucene.java (hunk 5 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/common/lucene/Lucene.java:387]: I was assuming that we are good because we are behind a feature flag. There is no roll-out made with the feature enabled, hence no bw comp guarantees?

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/common/lucene/Lucene.java:387]: I think you can by the same logic drop the other batched execution version constant once you're done backporting. That's actually fewer PRs I think? You just add the constant here, then backport, then adjust the version usage in main and remove the existing batched exec version constant in one PR.
-> 3 steps vs. 2 turn it off Prs + 1 merge and then two more for flipping the feature on again.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/common/lucene/Lucene.java]: will do so , thanks

**Comment by javanna** [comment]
@original-brownbear it seems like I have made it, finally. I am going to merge this.
