### PR TITLE
Make Geo Context Mapping Parsing More Strict

### LINKED ISSUE #32202: Geo Context suggester not working in version 5.5.2
I ned to use the geo context for my autocomplete. But it is not returning any results. When I run the autocomplete query without the context, results are returned.

1. Autocomplete query with context:
===============================
GET staging/_search
{
     "suggest": {
        "suggestion": {
          "prefix": "Südsteiermark",
          "completion": {
            "field": "autoCompleteName",
            "size": 10,
            "contexts": {
              "locationContext": [{
                "lat": "40.74164831951294",
                "lon": "-73.98714780807495",
                "precision": 12
              }]
            }
          }
        }
     }
}
==================================
RESULT of Autocomplete query with context
====================================
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "suggestion": [
      {
        "text": "Südsteiermark",
        "offset": 0,
        "length": 13,
        "options": []
      }
    ]
  }
}
===================================

3. RESULT OF QUERY WITHOUT CONTEXT:
===========================
  "took": 1713,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "suggestion": [
      {
        "text": "Südsteiermark",
        "offset": 0,
        "length": 13,
        "options": [
          {
            "text": "Südsteiermark, Tement, Zieregg 2008",
            "_index": "staging",
            "_type": "menuitemES",
            "_id": "591df0affa035585189619510x3bc",
            "_score": 1,
            "_source": {
              "venueId": "457ebeaaf964a5203f3f1fe3",
              "name": "Eleven Madison Park",
              "locP": {
                "type": "Point",
                "coordinates": [
                  40.74164831951294,
                  -73.98714780807495
                ]

========================================

4. Mapping portion:
          "autoCompleteName": {
            "type": "completion",
            "analyzer": "standard",
            "preserve_separators": true,
            "preserve_position_increments": false,
            "max_input_length": 50,
            "contexts": [
                {
                    "name":"locationContext",
                    "type":"geo",
                    "precision":"25m",
                    "path":"locP"
                }
            ]
=====================================

Please suggest what is wrong.

### PR DESCRIPTION
**Pull request by imotov**
Currently, if geo context is represented by something other than
geo_point or an object with lat and lon fields, the parsing of it
as a geo context can result in ignoring the context altogether,
returning confusing errors such as number_format_exception or trying
to parse the number specifying as long-encoded hash code. It would also
fail if the geo_point was stored.

This commit makes the mapping parsing more strict and will fail during
mapping update or index creation if the geo context doesn't point to
a geo_point field.

Supersedes #32412

Closes #32202

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM, thanks @imotov ! I wonder if we should merge to 6x because this change does not break existing indices ?

File: server/src/main/java/org/elasticsearch/search/suggest/completion/context/GeoContextMapping.java [hunk 1]
```diff
@@ -205,11 +213,11 @@ protected XContentBuilder toInnerXContent(XContentBuilder builder, Params params
                 for (IndexableField field : fields) {
                     if (field instanceof StringField) {
                         spare.resetFromString(field.stringValue());
-                    } else {
-                        // todo return this to .stringValue() once LatLonPoint implements it
+                        geohashes.add(spare.geohash());
+                    }  if (field instanceof LatLonPoint || field instanceof LatLonDocValuesField) {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/search/suggest/completion/context/GeoContextMapping.java]: Should there be an `else` here?

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 2]
```diff
@@ -421,6 +422,8 @@ static void validateTypeName(String type) {
             MapperMergeValidator.validateFieldReferences(fieldMappers, fieldAliasMappers,
                 fullPathObjectMappers, fieldTypes);
 
+            GeoContextMapping.validateGeoContextPaths(indexSettings.getIndexVersionCreated(), fieldMappers, fieldTypes::get);
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: Because this method provides a general way to valid context references, I wonder if it makes sense to future-proof a bit and reference `ContextMapping` instead, and also rename `validateGeoContextPaths` to `validateContextPaths`.

**Comment by imotov** [comment]
@jimczi yes, I was thinking about backporting it to 6.x, but I think I should open a separate PR for it since there are some non-trivial differences comparing to the master version.

**Review by jtibshirani — COMMENTED** [review]
Apologies for the 'drive by' commenting, I was just curious to see how this turned out after our conversation about mapping validation.
