### PR TITLE
Fix IndexInputUtils.withSlice to produce native-safe MemorySegments on Java 21

### LINKED ISSUE #143441: [CI] ESNextOSQVectorsScorerTests class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11926 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/vn7j446q5vdke)
- [elasticsearch-periodic-platform-support #11926 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bjy4h7bsozmvi)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/dlnywrstol3mq)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-140-3-matrix](https://gradle-enterprise.elastic.co/s/vabfnanwv5p5a)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/angbtunwbp6d4)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-140-3-matrix](https://gradle-enterprise.elastic.co/s/w3yqhkib6mj6w)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/bev2l2icaa24c)

**Reproduction Line:**
```
gradlew ":libs:simdvec:test" --tests "org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests.testScoreBulkNonAlignedBulkSize {p0=MMAP p1=1 p2=4 p3=MAXIMUM_INNER_PRODUCT}" -Dtests.seed=AA893C1AF209419 -Dtests.locale=en-KE -Dtests.timezone=Asia/Anadyr -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ kind: mapped, address: 0x2e295f60606, byteSize: 368 }; new offset = 368; new length = 4
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [main] 2 consecutive failures in step openjdk21_checkpart1_java-fips-matrix
- [main] 2 consecutive failures in step openjdk21_checkpart1_java-fips-140-3-matrix
- [main] 7 failures in class org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests (2.4% fail rate in 286 executions)
- [main] 2 failures in step windows-2025_checkpart1_platform-support-windows (66.7% fail rate in 3 executions)
- [main] 2 failures in step openjdk21_checkpart1_java-fips-matrix (100.0% fail rate in 2 executions)
- [main] 2 failures in step openjdk21_checkpart1_java-fips-140-3-matrix (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ChrisHegarty**
On Java 21, FFI disallows passing heap-backed MemorySegments to native downcalls. Java 22+ removes this restriction.

`IndexInputUtils.withSlice` is now the single path through which all simdvec scorers obtain MemorySegments from IndexInput data, and several of those scorers pass the segment directly to native downcalls. Rather than patching each and every call site across scorer classes individually, this fix takes a "safety by design" approach: `withSlice` itself now guarantees that the segment it hands to callers is always native-safe, regardless of Java version. No current or future caller needs to worry about the heap-segment restriction, correctness is enforced at the source.

I also added an assertion to the DirectAccessInput path that the byte buffer is direct, documenting the invariant that real implementations always provide native-backed buffers. 

The tradeoff here is that on Java 21 only, the copyAndApply fallback path incurs an extra native allocation and copy (via a confined Arena) where a heap-backed segment would have sufficed, since a number of call sites only use the Panama Vector API and never touch native downcalls. On Java 22+ the behavior is unchanged. This is an acceptable cost: the fallback path is already the slowest path (mmap and direct buffer paths are preferred), and the alternative - requiring every call site to independently guard against heap segments, is fragile and has already proven easy to miss. We can do some further cleanup at the call site after this fix has been merged.

caused by #141718
closes #143441

### CODE REVIEW

File: libs/simdvec/src/test21/java/org/elasticsearch/simdvec/internal/IndexInputUtilsTests.java [hunk 1]
```diff
@@ -72,6 +74,26 @@ public void testWithSlicePlainIndexInput() throws Exception {
         }
     }
 
+    public void testPlainInputFallbackProducesNativeSegmentOnJava21() throws Exception {
+        byte[] data = randomByteArrayOfLength(256);
+        try (Directory dir = new NIOFSDirectory(createTempDir())) {
+            writeData(dir, data);
+            try (IndexInput in = dir.openInput(FILE_NAME, IOContext.DEFAULT)) {
+                assertFalse(in instanceof MemorySegmentAccessInput);
```
Comment (thecoop) [inline libs/simdvec/src/test21/java/org/elasticsearch/simdvec/internal/IndexInputUtilsTests.java:82]: `assertThat(in, not(instanceOf(MemorySegmentAccessInput.class)))`, which will give you the actual type it is

**Review by benwtrent — APPROVED** [review]
I am good with this

**Review by thecoop — APPROVED** [review]
OK, with one nit

**Review by ldematte — APPROVED** [review]
LGTM
