### PR TITLE
Consistent updates of IndexShardSnapshotStatus

### LINKED ISSUE #26480: [CI] SharedClusterSnapshotRestoreIT#testGetSnapshotsRequest failing
I feel that I am to blame for this because of the https://github.com/elastic/elasticsearch/pull/26463, but I cannot reproduce locally

link:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+oracle-periodic/605/console

trace

```
20:51:14   1> org.elasticsearch.repositories.RepositoryException: [test-repo] could not read repository data from index blob
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:648) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:236) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:87) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:166) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
20:51:14   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
20:51:14   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
20:51:14   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
20:51:14   1> Caused by: java.io.IOException: Random IOException
20:51:14   1> 	at org.elasticsearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.maybeIOExceptionOrBlock(MockRepository.java:276) ~[test/:?]
20:51:14   1> 	at org.elasticsearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.listBlobsByPrefix(MockRepository.java:336) ~[test/:?]
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:777) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:755) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:607) ~[main/:?]
20:51:14   1> 	... 10 more
20:51:14   1> [2017-09-02T06:51:05,705][INFO ][o.e.s.SharedClusterSnapshotRestoreIT] 
```

reproduce with:

```
gradle :core:integTest \
  -Dtests.seed=3BFDC6F19B3167C4 \
  -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT \
  -Dtests.method="testGetSnapshotsRequest" \
  -Dtests.security.manager=true \
  -Dtests.locale=mk \
  -Dtests.timezone=Australia/Brisbane
```

### PR DESCRIPTION
**Pull request by tlrx**
IndexShardSnapshotStatus represents the status of an index shard
snapshot. During the snapshot process it can be updated multiple times,
it can also be aborted and the the Get Snapshot and Snapshot Status APIs
are susceptible to read the snapshot statuses.

Right now, the information are not updated in a coherent manner, meaning
that a IndexShardSnapshotStatus can be FAILED but the failure is not
updated yet. Or it could be FINALIZE with no index version.

This commit changes IndexShardSnapshotStatus so that the Stage is updated
coherently with any required information. It also provides a asCopy()
method that returns the status of a IndexShardSnapshotStatus at a given
point in time, ensuring that all information are coherent.

Closes #26480

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 1]
```diff
@@ -230,8 +229,9 @@ private void processIndexShardSnapshots(ClusterChangedEvent event) {
                 // running shards is missed, then the snapshot is removed is a subsequent cluster
                 // state update, which is being processed here
                 for (IndexShardSnapshotStatus snapshotStatus : entry.getValue().shards.values()) {
-                    if (snapshotStatus.stage() == Stage.INIT || snapshotStatus.stage() == Stage.STARTED) {
-                        snapshotStatus.abort();
+                    final IndexShardSnapshotStatus.Stage stage = snapshotStatus.asCopy().getStage();
+                    if (stage == Stage.INIT || stage == Stage.STARTED) {
+                        snapshotStatus.moveToAborted("snapshot has been removed in cluster state, aborting");
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: Would it make sense to change `moveToAborted` so that it only does this if the shard is in INIT or STARTED (rename it to `abortIfNotCompleted`?).

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 2]
```diff
@@ -279,12 +279,15 @@ private void processIndexShardSnapshots(ClusterChangedEvent event) {
...
+                            final IndexShardSnapshotStatus snapshotStatus = snapshotShards.shards.get(shard.key);
                             if (snapshotStatus != null) {
-                                switch (snapshotStatus.stage()) {
+                                final IndexShardSnapshotStatus.Copy lastSnapshotStatus = snapshotStatus.asCopy();
+                                final Stage stage = lastSnapshotStatus.getStage();
+                                switch (stage) {
                                     case INIT:
                                     case STARTED:
-                                        snapshotStatus.abort();
+                                        snapshotStatus.moveToAborted("snapshot has been aborted");
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: same thing here. We could just call `abortIfNotCompleted`, and then take a snapshot and then act based on FINALIZE, DONE, FAILURE

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java [hunk 3]
```diff
@@ -171,71 +144,105 @@ public synchronized void addProcessedFile(long size) {
...
+            return indexVersion;
+        }
+
+        public String getFailure() {
+            return failure;
+        }
+
+        @Override
+        public String toString() {
+            return new StringBuilder()
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: this looks a bit odd of a toString() implementation as it's very much targeted towards that one logging call site. Maybe change it to be more generic.

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java [hunk 4]
```diff
@@ -47,119 +53,86 @@
...
-
+    private final AtomicReference<Stage> stage;
     private long startTime;
-
-    private long time;
-
+    private long totalTime;
     private int numberOfFiles;
-
     private volatile int processedFiles;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: this does not need to be volatile anymore.

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java [hunk 5]
```diff
@@ -47,119 +53,86 @@
...
-
     private long totalSize;
-
     private volatile long processedSize;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: no need to be volatile anymore

**Review by ywelsch — CHANGES_REQUESTED** [review]
I very much like the approach here. Not super happy about the "Copy" name though. I've left some smaller feedback.

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java [hunk 6]
```diff
@@ -47,119 +53,86 @@
...
 
-    /**
-     * Returns snapshot processing time
-     *
-     * @return processing time
-     */
-    public long time() {
-        return this.time;
+    public synchronized Copy moveToStarted(final long startTime, final int numberOfFiles, final long totalSize) {
+        ensureNotAborted();
```
[the remark this answers is not in the document]
Comment (tlrx) [reply core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: Right, not needed anymore, thanks

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java (hunk 1 above)
Comment (tlrx) [reply core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: That's an interesting suggestion, thanks

**Comment by tlrx** [comment]
@ywelsch Thanks for review! I updated the code according to your comments, can you have another look please?

**Comment by tlrx** [comment]
> Not super happy about the "Copy" name though.

Yeah I agree, but I didn't come with a better name.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 7]
```diff
@@ -188,7 +187,7 @@ public void beforeIndexShardClosed(ShardId shardId, @Nullable IndexShard indexSh
             Map<ShardId, IndexShardSnapshotStatus> shards = snapshotShards.getValue().shards;
             if (shards.containsKey(shardId)) {
                 logger.debug("[{}] shard closing, abort snapshotting for snapshot [{}]", shardId, snapshotShards.getKey().getSnapshotId());
-                shards.get(shardId).abort();
+                shards.get(shardId).moveToAborted("shard is closing, aborting");
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: I wonder if we can also use `abortIfNotCompleted` here. Finally, looking at `BlobStoreRepository.snapshot`, we should also do the `store.decRef()` before we move to finalization. The store is unnecessarily kept open (possibly causing ShardLockObtainFailedException) and the snapshot process does not check abortion while it is doing its finalization.

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java [hunk 8]
```diff
@@ -47,119 +50,94 @@
...
-    /**
-     * Sets processed files stats
-     *
-     * @param numberOfFiles number of files in this snapshot
-     * @param totalSize     total size of files in this snapshot
-     */
-    public synchronized void processedFiles(int numberOfFiles, long totalSize) {
-        processedFiles = numberOfFiles;
-        processedSize = totalSize;
+    public void ensureNotAborted() {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: I would prefer to have the previous boolean `isAborted` method. Call sites currently catch this exception and then throw another exception.

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java [hunk 9]
```diff
@@ -171,71 +149,110 @@ public synchronized void addProcessedFile(long size) {
...
 
-    /**
-     * Number of processed files
-     *
-     * @return number of processed files
-     */
-    public int processedFiles() {
-        return processedFiles;
+    public static IndexShardSnapshotStatus newFailed(final String failure) {
+        if (failure == null) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: also add an assertion here so we fail hard in our tests?

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 10]
```diff
@@ -230,9 +229,8 @@ private void processIndexShardSnapshots(ClusterChangedEvent event) {
                 // running shards is missed, then the snapshot is removed is a subsequent cluster
                 // state update, which is being processed here
                 for (IndexShardSnapshotStatus snapshotStatus : entry.getValue().shards.values()) {
-                    if (snapshotStatus.stage() == Stage.INIT || snapshotStatus.stage() == Stage.STARTED) {
-                        snapshotStatus.abort();
-                    }
+                    final IndexShardSnapshotStatus.Stage stage = snapshotStatus.asCopy().getStage();
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: this line can be removed?

**Review by ywelsch — COMMENTED** [review]
I've added a few more comments

File: core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java (hunk 8 above)
Comment (tlrx) [reply core/src/main/java/org/elasticsearch/index/snapshots/IndexShardSnapshotStatus.java]: Ok, I revert the changes.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java (hunk 7 above)
Comment (tlrx) [reply core/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java]: > I wonder if we can also use abortIfNotCompleted here.

I think so. I wasn't sure when I added abortIfNotCompleted() but since the abort status is not checked again when finalizing the snapshot we can release the store as soon it is not needed so the shard can be closed and the finalization process continue and succeed or failed as it is already the case today.



> The store is unnecessarily kept open (possibly causing ShardLockObtainFailedException)

Good catch, I changed that too.

**Comment by tlrx** [comment]
@ywelsch Code updated, thanks.

**Review by ywelsch — APPROVED** [review]
LGTM. Let's bake this a few days on master and then backport to 6.2.

**Comment by tlrx** [comment]
Thanks @ywelsch !

**Comment by tlrx** [comment]
I didn't see any related failures since it has been merged, so I backported this change to 6.2.0 in ea6a46a99cff331079e535b2b7cc34d3c99f66d1
