### PR TITLE
Fix for ConstantKeywordClientYamlTestSuiteIT test fail

### LINKED ISSUE #145271: [CI] ConstantKeywordClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #12036 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/bvubo3vtxjqrq)
- [elasticsearch-periodic-platform-support #12036 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/zpvsn2o7pamki)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
9.2

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.constantkeyword.ConstantKeywordClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.xpack.constantkeyword.ConstantKeywordClientYamlTestSuiteIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [9.2] 1 consecutive failures in class org.elasticsearch.xpack.constantkeyword.ConstantKeywordClientYamlTestSuiteIT
- [9.2] 2 consecutive failures in step windows-2025_checkpart2_platform-support-windows
- [9.2] 1 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [9.2] 2 failures in class org.elasticsearch.xpack.constantkeyword.ConstantKeywordClientYamlTestSuiteIT (6.1% fail rate in 33 executions)
- [9.2] 2 failures in step windows-2025_checkpart2_platform-support-windows (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lukewhiting**
This one is tough to pin down due to being windows only and intermittent... Here's my best guess at what's going on looking at the test history in Devlocity + assistance from an agent:

On Windows, the test cluster uses a private copy of the distribution (because `canUseSharedDistribution()` always returns false on Windows — `AbstractLocalClusterFactory.java:359`). This copy is made via `IOUtils.syncMaybeWithLinks(...)`, which first tries hard links, falling back to copies. The lib/java-version-checker/*.jar files in this private copy may be initially inaccessible (AV scanning of newly-created hard-linked JARs) when the `elasticsearch-keystore` CLI tool runs, causing `JavaVersionChecker` to exit non-zero, which propagates as `exit /b 1` from `elasticsearch-cli.bat`.

## Why intermittent
Windows AV/Defender scans newly created files. Hard-linked JAR files trigger scans when first accessed. Depending on CI agent load and scan timing, the JAR files may or may not be available at the moment the JavaVersionChecker tries to load them.

## Fix
Add retry logic to `runToolScript(...)`

This follows the same pattern already established in `IOUtils.deleteWithRetry(...)`, which retries up to 15 times with 500ms delay on Windows for file deletion. This PR applies the same pattern when running the tool script.

This gives time for Windows Defender to finish the scan of the newly copied / linked JVM and allow execution of those executables.

Originally labelled for ":StorageEngine/Mapping" but re-classifying as investigation shows this is likely a test harness / lifecycle issue. I also pinged delivery as they may be interested?

Fixes #145271

### CODE REVIEW

File: test/test-clusters/src/main/java/org/elasticsearch/test/cluster/local/AbstractLocalClusterFactory.java [hunk 1]
```diff
@@ -927,22 +930,33 @@ private Map<ReplacementKey, String> getJvmOptionsReplacements() {
...
+                    }
+
+                    if (attempt >= TOOL_SCRIPT_RETRY_TIMES) {
+                        throw new RuntimeException("Execution of " + tool + " failed with exit code " + exit);
+                    }
 
-                if (exit != 0) {
-                    throw new RuntimeException("Execution of " + tool + " failed with exit code " + exit);
+                    attempt++;
+                    LOGGER.warn("Execution of {} failed with exit code {}, retrying ({}/{})", tool, exit, attempt, TOOL_SCRIPT_RETRY_TIMES);
```
Comment (prdoyle) [inline test/test-clusters/src/main/java/org/elasticsearch/test/cluster/local/AbstractLocalClusterFactory.java:955]: A `warn` for a retry seems a bit much, since this is ultimately operating as expected.

**Review by prdoyle — APPROVED** [review]
I see @mark-vieira's comment about the proliferation of these workarounds. Assuming we want to do this, LGTM.

One optional comment.

**Review by breskeby — APPROVED** [review]
lets give it a shot. I wish we had a better fix than a workaround for this. 🤷

**Comment by lukewhiting** [comment]
To address @mark-vieira's point, Yeah this is a pretty stinky workaround and something has indeed changed (The way the windows defender driver handles locking the file-system for scans).

I don't believe however that the workaround makes us worse off in this case... If this was better handled by windows / the JVM we would still have to wait for defender to unlock so would still be wasting time either in wait/notify or this busy/wait loop.

On the balance of everything and talking to Delivery, I think i'm going to go ahead an merge and see how we go. If it works then great, if not then we can dig further into the Windows 2025 environment.

**Comment by lukewhiting** [comment]
Looks like the Windows build is broken due to https://github.com/elastic/elasticsearch/pull/144319 and differences in the way javadoc handles `--` in an options file vs on *nix systems.

Have let @nik9000 know and will try to get this in once that's fixed.

**Comment by nik9000** [comment]
> Have let @nik9000 know and will try to get this in once that's fixed.

https://github.com/elastic/elasticsearch/pull/146414

**Comment by alex-spies** [comment]
Heya, we'll have to backport this to 9.4, too, right? I saw the same timeout issues on the 9.4 branch.

**Comment by lukewhiting** [comment]
OK I'm going to merge this without passing CI...

It's getting caught up in the timeout issue which this may possibly help so I think it's worth merging blind. We can always back it out again if it causes issues as it's only going to affect CI not prod.

**Comment by breskeby** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/155383)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
