### PR TITLE
Fix testMaxDocsLimit

### LINKED ISSUE #92037: [CI] MaxDocsLimitIT.testMaxDocsLimit
### CI Link

https://gradle-enterprise.elastic.co/s/ttoy2fz7vpo3a/tests/:server:internalClusterTest/org.elasticsearch.index.engine.MaxDocsLimitIT/testMaxDocsLimit

### Repro line

`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.engine.MaxDocsLimitIT.testMaxDocsLimit" -Dtests.seed=87A99F29C5284169 -Dtests.locale=es-PR -Dtests.timezone=America/Mazatlan -Druntime.java=17`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.index.engine.MaxDocsLimitIT&tests.test=testMaxDocsLimit#

### Failure excerpt

```
org.elasticsearch.ResourceAlreadyExistsException: index [test/JWxXBgp8T0CNYCD7JwrRlw] already exists	
	at __randomizedtesting.SeedInfo.seed([87A99F29C5284169:39D24887ACAF7B57]:0)	
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:175)	
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1360)	
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:343)	
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:298)	
	at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:551)	
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1052)	
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1017)	
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:278)	
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170)	
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)	
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	
	at java.lang.Thread.run(Thread.java:833)	
```

### PR DESCRIPTION
**Pull request by kingherc**
The issue was that the DOCUMENT_PAGE_SIZE setting could randomly get a very low value, which resulted in multiple pages for the cluster state update, which was prohibited by a randomly low max docs value.

Fixes #92037

### CODE REVIEW

**Comment by kingherc** [comment]
Hi, this test failure originates from [this line in this PR](https://github.com/elastic/elasticsearch/pull/78875/files#diff-5bbd74fa933c1584e0bb4eaecce59bdc3113a1186f2008163fc47cf674db97dcR587) which can set a very low value for the newly introduced DOCUMENT_PAGE_SIZE. According to that PR (cc @DaveCTurner ), the cluster state can now be paginated, and the pages are added as documents to an index. For a very low value of max docs, this results in an exception by Lucene like:

```
Caused by: java.lang.IllegalArgumentException: number of documents in the index cannot exceed 12
at org.apache.lucene.index.DocumentsWriterPerThread.reserveOneDoc(DocumentsWriterPerThread.java:205) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
...
at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1471) ~[lucene-core-9.4.2.jar:9.4.2 858d9b437047a577fa9457089afff43eefa461db - jpountz - 2022-11-17 12:56:39]
at org.elasticsearch.gateway.PersistedClusterStateService$Writer.lambda$addIndexMetadataDocuments$5(PersistedClusterStateService.java:1078) ~[main/:?]
at org.elasticsearch.gateway.PersistedClusterStateService$PageWriterOutputStream.flushPage(PersistedClusterStateService.java:1345) ~[main/:?]
at org.elasticsearch.gateway.PersistedClusterStateService$PageWriterOutputStream.close(PersistedClusterStateService.java:1332) ~[main/:?]
at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:249) ~[?:?]
...
at org.elasticsearch.xcontent.XContentBuilder.close(XContentBuilder.java:1235) ~[elasticsearch-x-content-8.7.0-SNAPSHOT.jar:8.7.0-SNAPSHOT]
...
at org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeIncrementalStateAndCommit(PersistedClusterStateService.java:911) ~[main/:?]
...
at org.elasticsearch.cluster.coordination.Coordinator.handlePublishRequest(Coordinator.java:464) ~[main/:?]
```

There is another alternative which would be to make the PersistedClusterStateService class aware of the number of max doc values per index writer. But judging from the comment that existed inside the test:

```
maxDocs.set(randomIntBetween(10, 100)); // Do not set this too low as we can fail to write the cluster state
```

I understood that the test does not target restricting the cluster state writes, but rather it wants to test writing real index documents. For this reason, I made this solution for the test failure, which makes sure that the cluster state is written, before testing the max doc values for real index documents.

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java [hunk 1]
```diff
@@ -61,6 +63,18 @@ protected Collection<Class<? extends Plugin>> nodePlugins() {
...
     }
 
+    @Override
+    protected Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
+        // Document page size should not be too small, else we can fail to write the cluster state for small max doc values
+        return Settings.builder()
+            .put(super.nodeSettings(nodeOrdinal, otherSettings))
+            .put(
+                PersistedClusterStateService.DOCUMENT_PAGE_SIZE.getKey(),
+                ByteSizeValue.ofBytes(randomIntBetween(1000, randomFrom(10000, 100000, 1000000)))
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java:73]: I don't think we need randomness here, let's just use the default (i.e. `PersistedClusterStateService.DOCUMENT_PAGE_SIZE.get(Settings.EMPTY)`).

**Review by DaveCTurner — APPROVED** [review]
:+1: I agree that this is the right way to fix this. LGTM, but I left one suggestion.
