### PR TITLE
[ES|QL] Fix Analyzer infinite loop for subquery referencing indices with empty mappings

### LINKED ISSUE #141029: ESQL: subqueries on indices with no fields fail
### Description

Having an index with no fields[*], the following query fails:
```
FROM
    (FROM nofields),
    (FROM nofields)
```

with `ESQL request failed with status [INTERNAL_SERVER_ERROR]: org.elasticsearch.xpack.esql.rule.RuleExecutionException: Rule execution limit [100] reached`

due to ever applying `analysis.Analyzer$ResolveRefs`:
```
[TRACE][o.e.x.e.a.A.changes      ] [runTask-0] Rule analysis.Analyzer$ResolveRefs applied with change
UnionAll[[]]                                        = UnionAll[[]]
|_Project[[<no-fields>{r$}#2]]                      = |_Project[[<no-fields>{r$}#2]]
| \_Project[[<no-fields>{r$}#2]]                    = | \_Project[[<no-fields>{r$}#2]]
|   \_Project[[<no-fields>{r$}#2]]                  = |   \_Project[[<no-fields>{r$}#2]]
|     \_Project[[<no-fields>{r$}#2]]                = |     \_Project[[<no-fields>{r$}#2]]
|       \_Subquery[]                                ! |       \_Project[[<no-fields>{r$}#2]]
|         \_EsRelation[nofields][<no-fields>{r$}#2] ! |         \_Subquery[]
\_Project[[<no-fields>{r$}#2]]                      ! |           \_EsRelation[nofields][<no-fields>{r$}#2]
  \_Project[[<no-fields>{r$}#2]]                    ! \_Project[[<no-fields>{r$}#2]]
    \_Project[[<no-fields>{r$}#2]]                  !   \_Project[[<no-fields>{r$}#2]]
      \_Project[[<no-fields>{r$}#2]]                !     \_Project[[<no-fields>{r$}#2]]
        \_Subquery[]                                !       \_Project[[<no-fields>{r$}#2]]
          \_EsRelation[nofields][<no-fields>{r$}#2] !         \_Project[[<no-fields>{r$}#2]]
                                                    !           \_Subquery[]
                                                    !             \_EsRelation[nofields][<no-fields>{r$}#2]
```

[*] nofields:
```
PUT /nofields
{
    "mappings": {
        "dynamic": false
    }
}
```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Fix #141029 

After fixing the infinite loop in `Analyzer`, subquery referencing indices with empty mappings behave the same as when there is no subquery https://github.com/elastic/elasticsearch/issues/111545, this is a separate issue that needs to be addressed.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java:1]: Would it make sense to also add a test with no main index, like in the ticket?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -1005,7 +1005,13 @@ private LogicalPlan resolveFork(Fork fork) {
...
                 List<String> subPlanColumns = logicalPlan.output().stream().map(Attribute::name).toList();
                 // We need to add an explicit projection to align the outputs.
-                if (logicalPlan instanceof Project == false || subPlanColumns.equals(forkColumns) == false) {
+                // If the branch already has a Project on top, and the output of the branch is empty,
+                // don't add another Project with only NO_FIELDS on top of it,
+                // otherwise it will cause an infinite loop in the analyzer, this happens to subquery so far.
+                // forkColumns do not contain NO_FIELD because Fork.outputUnion removes it.
+                if (logicalPlan instanceof Project == false
+                    || (subPlanColumns.equals(forkColumns) == false
+                        && (fork instanceof UnionAll && forkColumns.isEmpty() && logicalPlan.output().equals(NO_FIELDS)) == false)) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Would it make sense to extract this check into a small static method (possibly also with the comment)? Up to you.

**Review by bpintea — APPROVED** [review]

**Comment by fang-xing-esql** [comment]
Thanks for the review @bpintea! The suggested test and code refactor have been applied.
