### PR TITLE
Fix ccs permission for search with a scroll id

### LINKED ISSUE #61828: CCS with scroll requires read privilege on local cluster after having the scroll_id
The current CCS model requires no privilege on the local cluster as described in the the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/cross-cluster-configuring.html#_example_configuration_of_cross_cluster_search). However, when a search is perform with scroll enabled, the initial search will succeed, but subsequent requests using the `_scroll_id` returned from the initial response will fail with a `403` error.

Assuming CCS is setup as described in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/cross-cluster-configuring.html#_example_configuration_of_cross_cluster_search). Here are the basic steps to reproduce it:

1. The initial scroll search will work
```
GET two:logs-2017.04/_search?scroll=1h
```

2. But subsequent requests using the scroll id will fail
```
GET _search/scroll/SCROLL_ID_FROM_ABOVE
```

### PR DESCRIPTION
**Pull request by ywangd**
CCS with remote indices only does not require any privileges on the local cluster.
This PR ensures that search with scroll follow the permission model.

Resolves: #61828

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchHelper.java [hunk 1]
```diff
@@ -108,6 +109,10 @@ static ParsedScrollId parseScrollId(String scrollId) {
         }
     }
 
+    static boolean hasLocalIndices(String scrollId) {
+        return Arrays.stream(parseScrollId(scrollId).getContext()).anyMatch(c -> c.getClusterAlias() == null);
```
Comment (albertzaharovits) [inline server/src/main/java/org/elasticsearch/action/search/TransportSearchHelper.java:113]: I would suggest that `hasLocalIndices` be a method of `ParsedScrollId` , it's more OO this way.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java [hunk 2]
```diff
@@ -261,7 +262,7 @@ public void authorizeIndexAction(RequestInfo requestInfo, AuthorizationInfo auth
                 // if the action is a search scroll action, we first authorize that the user can execute the action for some
                 // index and if they cannot, we can fail the request early before we allow the execution of the action and in
                 // turn the shard actions
-                if (SearchScrollAction.NAME.equals(action)) {
+                if (SearchScrollAction.NAME.equals(action) && ((SearchScrollRequest) request).hasLocalIndices()) {
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java:265]: I would avoid throwing exceptions in this part of the code, it's very brittle, better call the `listener.onFailure` .

**Review by albertzaharovits — CHANGES_REQUESTED** [review]
Besides the two minor points, can you also please add a test similar to `AuthorizationServiceTests#testUserWithNoRolesCanPerformRemoteSearch` ?

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchHelper.java (hunk 1 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/search/TransportSearchHelper.java]: You are absolutely right. Now I wonder why I didn't do it initially ...

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java (hunk 2 above)
Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java]: This is a good catch. Thanks. I have added the exception handling and listener call. It is a pretty basic `try..catch` block. Please let me know if there are better way or convention to do it differently. Thanks.

**Comment by ywangd** [comment]
> Besides the two minor points, can you also please add a test similar to `AuthorizationServiceTests#testUserWithNoRolesCanPerformRemoteSearch` ?
>
I added a new [test](https://github.com/elastic/elasticsearch/pull/62053/files#diff-3dec0fec51a395d9a9247e011cc2808dR415). Thanks.

**Comment by ywangd** [comment]
> I added a new [test](https://github.com/elastic/elasticsearch/pull/62053/files#diff-3dec0fec51a395d9a9247e011cc2808dR415).
>
Updated the test to add randomness.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java [hunk 3]
```diff
@@ -411,6 +412,31 @@ public void testUserWithNoRolesCanPerformRemoteSearch() throws IOException {
         verifyNoMoreInteractions(auditTrail);
     }
 
+    public void testUserWithNoRolesPerformsRemoteSearchWithScroll() throws IOException {
+        final ParsedScrollId parsedScrollId = mock(ParsedScrollId.class);
+        final boolean hasLocalIndices = randomBoolean();
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java:417]: I would've made this variable take both values in this test, i.e. don't rely on randomisation.

In principle, it's better to avoid randomisation for test coverage, and use it for variables that don't have any bearing on the output of the test. That's in principle, but sometimes the input value space is large and randomisation might be used on the independent variables as well (more often inside, but sometimes across, value spaces that change the outcome of the test).

File: server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+public class ParsedScrollIdTests extends ESTestCase {
+    public void testHasLocalIndices() {
+        final int nResults = randomIntBetween(1, 3);
+        final SearchContextIdForNode[] searchContextIdForNodes = new SearchContextIdForNode[nResults];
+
+        boolean hasLocal = false;
+        for (int i = 0; i < nResults; i++) {
+
+            String clusterAlias = randomBoolean() ? randomAlphaOfLength(8) : null;
```
Comment (albertzaharovits) [inline server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java:33]: ditto https://github.com/elastic/elasticsearch/pull/62053/files#r487806064

File: server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+ * under the License.
+ */
+
+package org.elasticsearch.action.search;
+
+import org.elasticsearch.search.internal.ShardSearchContextId;
+import org.elasticsearch.test.ESTestCase;
+
+public class ParsedScrollIdTests extends ESTestCase {
+    public void testHasLocalIndices() {
```
Comment (albertzaharovits) [inline server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java:26]: This test relies on the `TransportSearchHelperTests#testParseScrollId` , where, given `SearchShardTargets`, the scroll id is encoded and then decoded, and the test asserts that the "cluster alias" shows up after decoding.

IMO, this test adds little value on top of that, and it's coded away from the above mentioned piece of code.
My personal approach would've been to parametrise the `TransportSearchHelperTests#generateQueryResults` method to allow it to generate scroll ids with/without cluster aliases, and assert the `ParsedScrollId#hasLocalIndices` method there as well (probably in another test but not necessarily so).

File: server/src/main/java/org/elasticsearch/action/search/SearchScrollRequest.java [hunk 6]
```diff
@@ -83,6 +83,10 @@ public SearchScrollRequest scrollId(String scrollId) {
         return this;
     }
 
+    public ParsedScrollId parsedScrollId() {
+        return TransportSearchHelper.parseScrollId(scrollId);
```
Comment (albertzaharovits) [inline server/src/main/java/org/elasticsearch/action/search/SearchScrollRequest.java:87]: In principle, I would shy away from getters that do any processing, unless the method has a verb in the name.

**Review by albertzaharovits — APPROVED** [review]
LGTM
I've made some "In principle" comments in order to expose my personal thinking, but I'm happy to merge this as is.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java [hunk 7]
```diff
@@ -262,7 +264,16 @@ public void authorizeIndexAction(RequestInfo requestInfo, AuthorizationInfo auth
                 // index and if they cannot, we can fail the request early before we allow the execution of the action and in
                 // turn the shard actions
                 if (SearchScrollAction.NAME.equals(action)) {
-                    authorizeIndexActionName(action, authorizationInfo, null, listener);
+                    try {
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java:267]: As you've mentioned the try-catch structure unfortunately doesn't fit too nicely with the async listener idiom .
I personally would've maintained a check like `request instanceof SearchScrollRequest && ((SearchScrollRequest)request).scrollId() != null` as I'm not a fan of catching runtime exceptions . 

Again, this is a feedback with my perspective, the codebase is cot consistent in this regard; it's your choice.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java (hunk 3 above)
Comment (ywangd) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java]: Thanks that's a good point. I changed it to always test both situations.

File: server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java (hunk 4 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java:32]: I tried to remove the randomness, but then decided to keep it as is. Here is why: The intention is to test that "any local indices will be reported as hasLocalIndices". The "any" bit makes it more suitable for randomness, because it can be:
* A single search context
* Multiple search contexts where 
  * the local one can be in the first position, second position, last position etc. 
  * Or there might be more than one local contexts, e.g. all of them are local contexts or only one of them is not local context.

The randomness in the test is intended to cover all above situations. If removed, the coverage will be reduced (or we can replace it with a very bloated test method, but I think that is less ideal).

File: server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java (hunk 5 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/search/ParsedScrollIdTests.java:26]: I am not sure if I follow your comment. This test is an unit test for `ParsedScrollId` and has nothing to do with `TransportSearchHelperTests#testParseScrollId `. Maybe you were commenting on a previous version of this test, i.e. the one before I moved this method as part of `ParsedScrollId` following your comment of [OO design](https://github.com/elastic/elasticsearch/pull/62053#discussion_r484745362)?

File: server/src/main/java/org/elasticsearch/action/search/SearchScrollRequest.java (hunk 6 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/search/SearchScrollRequest.java:87]: Given `TransportSearchHelper.parseScrollId(scrollId)` can throw exception, I think it is fair to name it with a verb. I updated to be `parseScrollId` (same name as `TransportSearchHelper#parseScrollId`). The extra layer of proxy (from ParsedScrollId to TransportSearchHelper) is because `TransportSearchHelper` is not public and it feels better to keep it that way.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java (hunk 7 above)
Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java]: I changed it to use `ActionRunnable.supply(...).run()`, which takes a `CheckedSupplier` to handle the exception. Honestly, the code is less readable with this change. But it is more in line with the overwhelming callback style.
