### PR TITLE
[ML] Refactor data extraction logic and improve cleanup handling

### LINKED ISSUE #84268: [CI] DatafeedCcsIT testDatafeedWithCcsRemoteUnavailable failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/j5g7ky5m3bsha/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.DatafeedCcsIT/testDatafeedWithCcsRemoteUnavailable

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.DatafeedCcsIT.testDatafeedWithCcsRemoteUnavailable" -Dtests.seed=8BDE2BE76C97D88B -Dtests.locale=es-US -Dtests.timezone=Asia/Srednekolymsk -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.DatafeedCcsIT&tests.test=testDatafeedWithCcsRemoteUnavailable

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <0>
     but: was <215>

  at __randomizedtesting.SeedInfo.seed([8BDE2BE76C97D88B:DF8640B27E9A8128]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.InternalTestCluster.lambda$assertSearchContextsReleased$44(InternalTestCluster.java:2529)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1068)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1041)
  at org.elasticsearch.test.InternalTestCluster.assertSearchContextsReleased(InternalTestCluster.java:2528)
  at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2470)
  at org.elasticsearch.test.AbstractMultiClustersTestCase.assertAfterTest(AbstractMultiClustersTestCase.java:139)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by valeriy42**
Fixes scroll context leaks in datafeed CCS tests by ensuring proper cleanup of scroll contexts.

Changes include:
- Wrapping DataExtractor usage in a try-finally block within `DatafeedJob.run()` to guarantee that `destroy()` is always invoked.
- Calling `clearScrollLoggingExceptions()` in `ScrollDataExtractor.clearScroll()` to handle failures smoothly.
- Destroys the previous extractor in `ChunkedDataExtractor.advanceTime()` before instantiating a new one.
- Adds a cleanup wait in the test after stopping the datafeed.
- Removes the `@AwaitsFix` annotation from `DatafeedCcsIT`.

Fixes https://github.com/elastic/elasticsearch/issues/84268

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java [hunk 1]
```diff
@@ -363,112 +363,117 @@ private void run(long start, long end, FlushJobAction.Request flushRequest) {
...
-                // deep in the exception.
-                if (e.toString().contains("doc values")) {
-                    throw new ExtractionProblemException(
-                        nextRealtimeTimestamp(),
-                        new IllegalArgumentException(
-                            "One or more fields do not have doc values; please enable doc values for all analysis fields for datafeeds"
-                                + " using aggregations"
-                        )
-                    );
+        try {
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java:366]: Wrapped DataExtractor usage in a try-finally block so `destroy()` is always called, including on early returns due to isolation.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java [hunk 2]
```diff
@@ -363,112 +363,117 @@ private void run(long start, long end, FlushJobAction.Request flushRequest) {
...
-        }
 
-        if (recordCount == 0) {
-            throw new EmptyDataCountException(nextRealtimeTimestamp(), haveEverSeenData);
+            if (recordCount == 0) {
+                throw new EmptyDataCountException(nextRealtimeTimestamp(), haveEverSeenData);
+            }
+        } finally {
+            // Ensure the extractor is always destroyed to clean up scroll contexts
+            dataExtractor.destroy();
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java:476]: This is the block I actually added

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/extractor/scroll/ScrollDataExtractor.java [hunk 3]
```diff
@@ -269,7 +269,7 @@ protected SearchResponse executeSearchScrollRequest(String scrollId) {
     }
 
     private void clearScroll() {
-        innerClearScroll(scrollId);
+        clearScrollLoggingExceptions(scrollId);
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/extractor/scroll/ScrollDataExtractor.java:272]: Changed clearScroll() in ScrollDataExtractor to use clearScrollLoggingExceptions() instead of innerClearScroll() directly, so failures are logged instead of propagating. If clearScroll() throws, it could hide the original ResourceNotFoundException. By catching and logging cleanup failures, the original exception can still propagate. This preserves the real error while still attempting cleanup.

File: x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/DatafeedCcsIT.java [hunk 4]
```diff
@@ -169,6 +168,15 @@ public void testDatafeedWithCcsRemoteUnavailable() throws Exception {
         } finally {
             client(LOCAL_CLUSTER).execute(StopDatafeedAction.INSTANCE, new StopDatafeedAction.Request(datafeedId)).actionGet();
             client(LOCAL_CLUSTER).execute(CloseJobAction.INSTANCE, new CloseJobAction.Request(jobId)).actionGet();
+            // Wait a bit to allow scroll contexts to be cleaned up after stopping the datafeed.
+            // This is especially important after network disruption when scroll contexts on the remote
+            // cluster may have been created but couldn't be cleared until connectivity was restored.
+            // The wait gives time for the destroy() cleanup to complete.
+            try {
+                Thread.sleep(2000); // 2 seconds should be sufficient for cleanup to propagate
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/DatafeedCcsIT.java]: Instead of waiting for 2000ms, can we instead poll whether the cleanup has finished?

This 2000ms always costs time when it's unnecessary, and if there's a connectivity issue for more than 2000ms it still fails.

**Review by jan-elastic — APPROVED** [review]
LGTM. Just one thing that can hopefully be improved
