### PR TITLE
Fix [CI] CcrTimeSeriesDataStreamsIT testCrossClusterReplicationForTSDB failing

### LINKED ISSUE #142797: [CI] CcrTimeSeriesDataStreamsIT testCrossClusterReplicationForTSDB failing
**Build Scans:**
- [elasticsearch-periodic #11909 / release-tests](https://gradle-enterprise.elastic.co/s/zyfqq53fbeibe)
- [elasticsearch-periodic #11909 / release-tests](https://gradle-enterprise.elastic.co/s/vzbuku3m3mdem)
- [elasticsearch-periodic-java-ea #182 / release-tests](https://gradle-enterprise.elastic.co/s/2qncm6llic67c)
- [elasticsearch-pull-request #122058 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/ortd45c6pms2g)
- [elasticsearch-pull-request #122024 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/5wfqroilqda6a)
- [elasticsearch-pull-request #121929 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/kyko36mknvt5y)
- [elasticsearch-pull-request #121883 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/bluvv34nkbk5a)
- [elasticsearch-pull-request #121883 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/hkuggvxhbcykq)
- [elasticsearch-pull-request #121853 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/uo7vtnd5ekxka)
- [elasticsearch-pull-request #121853 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/aw2je45gbzqtu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ccr:internalClusterTest" --tests "org.elasticsearch.xpack.ccr.CcrTimeSeriesDataStreamsIT.testCrossClusterReplicationForTSDB" -Dtests.seed=D0D16B19D696788F -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ar-SA -Dtests.timezone=America/Juneau -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ccr.CcrTimeSeriesDataStreamsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testCrossClusterReplicationForTSDB'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 16 consecutive failures in step checkpart2_release-tests
- [main] 19 failures in test testCrossClusterReplicationForTSDB (2.4% fail rate in 799 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 16 failures in step checkpart2_release-tests (100.0% fail rate in 16 executions)
- [main] 12 failures in pipeline elasticsearch-pull-request (2.3% fail rate in 525 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lukewhiting**
## Summary
Avoid putting `index.mapping.synthetic_id` in the CCR TSDB data stream template when the TSDB synthetic ID feature flag is disabled, so template validation no longer hits an assertion and the test no longer hangs.

## Root cause
The test always added `index.mapping.synthetic_id` to the template settings. When the feature flag is off (e.g. in CI), that setting is not registered in `IndexScopedSettings`, so `MetadataCreateIndexService.validatePrivateSettingsNotExplicitlySet` fails with `AssertionError: expected [index.mapping.synthetic_id] to be private but it was not`. The failure occurs on the master's cluster-state task thread and is not reported back to the client, so the test blocks on `putDataStreamTemplate(...).actionGet()` until the suite timeout (20 minutes).

## Fix
Only add `IndexSettings.SYNTHETIC_ID` to the template when `IndexSettings.TSDB_SYNTHETIC_ID_FEATURE_FLAG` is true. When the flag is off the default behaviour (no synthetic ID) is unchanged.

Fixes #142797

### CODE REVIEW

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrTimeSeriesDataStreamsIT.java [hunk 1]
```diff
@@ -276,46 +276,42 @@ enum Operation {
...
-                        new Template(
-                            indexSettings(primaries, replicas).put(IndexSettings.MODE.getKey(), IndexMode.TIME_SERIES.getName())
-                                .put(IndexSettings.INDEX_REFRESH_INTERVAL_SETTING.getKey(), -1)
-                                .put(IndexSettings.RECOVERY_USE_SYNTHETIC_SOURCE_SETTING.getKey(), randomBoolean())
-                                .put(IndexSettings.SYNTHETIC_ID.getKey(), useSyntheticId)
-                                .build(),
-                            new CompressedXContent("""
-                                {
-                                    "_doc": {
+                    .template(new Template(settingsBuilder.build(), new CompressedXContent("""
```
Comment (lukewhiting) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrTimeSeriesDataStreamsIT.java:289]: CI decided to reformat this :-/ Not sure why spotless would reorder a JSON...

**Review by tlrx — APPROVED** [review]
LGTM, thanks for fixing this @lukewhiting
