### PR TITLE
Fix composable templates with `subobjects: false`

### LINKED ISSUE #96768: Composable template fails with `subobjects: false` and mappings in different component templates
### Elasticsearch Version

8.9.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macOS

### Problem Description

When trying to merge two component templates, one which contains explicit mappings for dotted fields and the other containing `subobjects: false`, composition fails with:
```
type: "mapper_parsing_exception"
reason: "Tried to add subobject [XXX] to object [_doc] which does not support subobjects"
```

If the `subobjects: false` is located within the same component template alongside the fields mappings- the error doesn't occur. 
Also, this error doesn't occur if the field mapping is made for a non-dotted field.

### Steps to Reproduce

Run this test through the yaml test framework:
```yml
  - do:
      cluster.put_component_template:
        name: test-subobjects
        body:
          template:
            mappings:
              subobjects: false

  - do:
      cluster.put_component_template:
        name: test-field
        body:
          template:
            mappings:
              properties:
                parent.subfield:
                  type: keyword

  - do:
      indices.put_index_template:
        name: logs-composable-template
        body:
          index_patterns:
            - test-*
          composed_of:
            - test-subobjects
            - test-field
```

NOTE:
- if `subobjects: false` is moved to be alongside the explicit mappings within the same component template - the error doesn't occur
- if the mapping is defined for the field `parent` and not `parent.subfield` - the error doesn't occur

### Logs

```
  2> java.lang.AssertionError: Failure at [data_stream/250_logs_no_subobjects:232]: expected [2xx] status code but api [indices.put_index_template] returned [400 Bad Request] [---
    error:
      root_cause:
      - type: "illegal_argument_exception"
        reason: "composable template [logs-composable-template] template after composition\
          \ with component templates [test-subobjects, test-field] is invalid"
        stack_trace: "org.elasticsearch.ElasticsearchException$1: composable template\
          \ [logs-composable-template] template after composition with component templates\
          \ [test-subobjects, test-field] is invalid\n\tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:667)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:595)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.build(RestResponse.java:176)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:124)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:103)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onFailure(NodeClient.java:170)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:217)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:60)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:72)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:39)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:60)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:72)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:231)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:127)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:60)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:132)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$TemplateClusterStateUpdateTask.onFailure(MetadataIndexTemplateService.java:160)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$ExecutionResult.notifyFailure(MasterService.java:975)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$ExecutionResult.onClusterStateUnchanged(MasterService.java:938)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:245)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1622)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:382)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1619)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:382)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\
          \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\
          \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\
          \tat java.base/java.lang.Thread.run(Thread.java:1623)\nCaused by: java.lang.IllegalArgumentException:\
          \ composable template [logs-composable-template] template after composition\
          \ with component templates [test-subobjects, test-field] is invalid\n\tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:729)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:619)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:556)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$5.execute(MetadataIndexTemplateService.java:501)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$1.executeTask(MetadataIndexTemplateService.java:136)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$1.executeTask(MetadataIndexTemplateService.java:133)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.SimpleBatchedExecutor.execute(SimpleBatchedExecutor.java:70)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)\n\
          \t... 11 more\nCaused by: java.lang.IllegalArgumentException: invalid composite\
          \ mappings for [logs-composable-template]\n\tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$28(MetadataIndexTemplateService.java:1600)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:697)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1570)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:723)\n\
          \t... 20 more\nCaused by: org.elasticsearch.index.mapper.MapperParsingException:\
          \ Failed to parse mapping: Tried to add subobject [parent] to object [_doc]\
          \ which does not support subobjects\n\tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:385)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.assertSerialization(MapperService.java:402)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:370)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$28(MetadataIndexTemplateService.java:1593)\n\
          \t... 23 more\nCaused by: org.elasticsearch.index.mapper.MapperParsingException:\
          \ Tried to add subobject [parent] to object [_doc] which does not support subobjects\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:298)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:235)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.parse(RootObjectMapper.java:411)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:102)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:96)\n\
          \tat org.elasticsearch.server@8.9.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:383)\n\
          \t... 26 more\n"
      type: "illegal_argument_exception"
      reason: "composable template [logs-composable-template] template after composition\
        \ with component templates [test-subobjects, test-field] is invalid"
      caused_by:
        type: "illegal_argument_exception"
        reason: "invalid composite mappings for [logs-composable-template]"
        caused_by:
          type: "mapper_parsing_exception"
          reason: "Failed to parse mapping: Tried to add subobject [parent] to object\
            \ [_doc] which does not support subobjects"
          caused_by:
            type: "mapper_parsing_exception"
            reason: "Tried to add subobject [parent] to object [_doc] which does not support\
              \ subobjects"
```

### PR DESCRIPTION
**Pull request by eyalkoren**
Fixes #96768 

A fix proposal based on the [identified root cause](https://github.com/elastic/elasticsearch/issues/96768#issuecomment-1609907429).

The problem in general is that mapping properties parsing is affected by the `subobjects` setting, so if multiple mappings are merged, whenever explicit `subobjects` setting is encountered, formerly parsed mappings become invalid.
What I tried in this PR is to determine whether there is an explicit `subobjects` setting within a list of mappings before parsing (and merging) them. This allows for consistent parsing and merging of component templates when processing and validating composable component templates.

If this fix proposal is evaluated as a valid path, we still need to add some unit tests, for example:
- [x] different order of components in the `composedOf` list
- [x] contradicting `subobjects` settings
- [x] comparing the new bulk merge to the existing sequential merge

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 1]
```diff
@@ -352,24 +355,62 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
-            Mapping mapping = mergeMappings(this.mapper, incomingMapping, reason);
-            // TODO: In many cases the source here is equal to mappingSource so we need not serialize again.
-            // We should identify these cases reliably and save expensive serialization here
-            DocumentMapper newMapper = newDocumentMapper(mapping, reason, mapping.toCompressedXContent());
-            if (reason == MergeReason.MAPPING_UPDATE_PREFLIGHT) {
-                return newMapper;
-            }
-            this.mapper = newMapper;
-            assert assertSerialization(newMapper);
+        Map<String, Object> mappingSourceAsMap = MappingParser.convertToMap(mappingSource);
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:393]: Only the `XContentHelper.convertToMap()` operation was extracted from the formerly `synchronized` block. As far as I can see this is a stateless operation, which leaves the former synchronization enforcement the same.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 2]
```diff
@@ -352,24 +355,62 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+    public DocumentMapper merge(String type, List<CompressedXContent> mappingSources, MergeReason reason) {
+        final DocumentMapper currentMapper = this.mapper;
+        if (currentMapper != null && mappingSources.size() == 1 && currentMapper.mappingSource().equals(mappingSources.get(0))) {
+            return currentMapper;
+        }
+
+        List<Map<String, Object>> convertedMappings = new LinkedList<>();
+        Explicit<Boolean> explicitSubobjects = null;
+        for (CompressedXContent mappingSource : mappingSources) {
+            Map<String, Object> mapping = MappingParser.convertToMap(mappingSource);
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:370]: __Note for reviewer:__ since `MappingParser.convertToMap()` is stateless, it should be safe to first apply it to the entire mappings list and only then apply parsing-and-merging for each of the mappings in the original order.
The former logic was applying convert-parse-merge for each of the mappings in order.

So far I only replaced one usage of the former logic (that relies on the existing `merge()` method) with this new logic (that relies on this `merge()` that accepts a list of mappings). There are additional cases where the older `merge()` override is applied sequentially on a list of mappings, where it may make sense to switch to this one as well. Please advice if and where else it makes sense to replace as well.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 3]
```diff
@@ -251,7 +252,7 @@ protected static Explicit<Boolean> parseSubobjects(Map<String, Object> node) {
             if (subobjectsNode != null) {
                 return Explicit.explicitBoolean(XContentMapValues.nodeBooleanValue(subobjectsNode, "subobjects.subobjects"));
             }
-            return Explicit.IMPLICIT_TRUE;
+            return Defaults.SUBOBJECTS;
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:255]: Not related, but seems more correct

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java (hunk 2 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:370]: I do agree with you, and looking at the code, whenever the previous `merge()` logic is applied sequentially on a list of mappings we can substitute it with the new logic. 
I am battled on whether this small refactor would find it's place in this PR. My suggestion here would be to create a new PR for this change and adding to it a test to make sure that calling sequentially the old `merge()` on a list of mappings has the same behaviour as calling the new `merge()` logic, to make sure that future changes to this code will stay consistent in both methods.

**Review by piergm — COMMENTED** [review]
I think the chosen path of determining whether there is an explicit sub-objects setting before merging is the right one! Therefore the solution proposed LGTM. Thanks @eyalkoren for the PR.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java (hunk 2 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:370]: I added a basic [test](https://github.com/elastic/elasticsearch/pull/97317/files#diff-904b4a9c1fa36a624cf1f095c37881f94fdc4530bb19d61ed5eb3be5216a7d6fR421-R429) to compare the two merge options and I opened a PR on this branch for the followup refactoring. Once we merge this PR, I'll convert the followup refactor PR to a real one.

**Review by piergm — APPROVED** [review]
LGTM! Thanks for the PR @eyalkoren 👍

**Comment by eyalkoren** [comment]
Summarizing my offline discussion with @romseygeek: we may be able to generically solve this problem by merging mappings in their raw form first, before parsing them, as in [`XContentHelper#mergeDefaults`](https://github.com/elastic/elasticsearch/blob/84089fe7e490ff80e08ecfbf6815763ffa84fc5b/server/src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java#L414), possibly with slight changes and only for merges during the composition of index templates.
One possible change we'd need to apply for the current merge for example- we may be OK with simply overriding the value for a field's "type" by another type coming from another mapping, but the current expectation is to not allow conflicts of field type with object type.

Another alternative is to postpone the object expansion based on `.` in field names to be done as late as possible, after merging is done, at which time we already have the full picture from all mappings. This may be much more complicated to do.

@dakrone your input on this would be very helpful.

**Comment by eyalkoren** [comment]
Update (for my future self mostly): I added a test with the exact example described [above](https://github.com/elastic/elasticsearch/pull/97317#issuecomment-1663592849) that fails as expected. 
Applying @romseygeek's proposal of merging the raw (non-parsed JSON `Map<String, Object>` representations) mappings through `XContentHelper#mergeDefaults` fixes the test. I already know it would fail other tests that expect merge exceptions when trying to merge field X with `type: object` with another mapping in which field X is mapped to a non-object type. 
So this approach seems valid so far, but we'd need to implement our own raw merge that is very similar to `mergeDefaults` but contains all special cases for mappings merges for index templates.

**Comment by romseygeek** [comment]
> I already know it would fail other tests that expect merge exceptions when trying to merge field X with type: object with another mapping in which field X is mapped to a non-object type.

I think it's likely that we'll still get exceptions, it's just that they'll be different exceptions?  For example, overriding an object mapper with a float mapper will then throw an exception at parse time, because float mappers can't have a `properties` subfield.

**Comment by eyalkoren** [comment]
> I think it's likely that we'll still get exceptions, it's just that they'll be different exceptions? For example, overriding an object mapper with a float mapper will then throw an exception at parse time, because float mappers can't have a properties subfield.

It will then depend in the order of the merge. `XContentHelper#mergeDefaults` simply merges without knowing anything about what it is merging, so it doesn't know that it merges mappings and that the `type` key may require special handling or validations. When I ran `MetadataIndexTemplateServiceTests`, [`testIndexTemplateFailsToOverrideComponentTemplateMappingField()`](https://github.com/elastic/elasticsearch/blob/ac68e54e8e6730cb0e7e323cd30338923d8edd8a/server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateServiceTests.java#L1840-L1843) failed because it expected an exception during validation, which did not occur because the merged raw map contained `type: object`, which is OK with `properties`. On the other hand, [`testUpdateComponentTemplateFailsIfResolvedIndexTemplatesWouldBeInvalid()`](https://github.com/elastic/elasticsearch/blob/ac68e54e8e6730cb0e7e323cd30338923d8edd8a/server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateServiceTests.java#L1965-L1968) failed due to a different exception, where a `text` field is not expected to have `properties` subfield, as you say.

**Comment by eyalkoren** [comment]
@romseygeek Please check my recent changes- I tried to find the best combination of code reuse for `XContentHelper#mergeDefaults` as well as safe refactor and zero overhead for existing usages of this legacy functionality. 

From all I can tell- it works as expected and solves the issue generically at all levels of the merged documents. Hopefully the full test suite will not uncover issues that I couldn't find manually.

I don't like the hard-coded distinction between object and non-object fields, but since I need to do that in the raw map form, I couldn't think of a better way. Let me know if you think it needs different handling.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 4]
```diff
@@ -353,24 +356,70 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+                        case "type" -> {
+                            // todo: verify this check is valid
+                            if (oldValue.equals(newValue) == false
+                                && (OBJECT_FIELD_TYPES.contains(String.valueOf(oldValue))
+                                    || OBJECT_FIELD_TYPES.contains(String.valueOf(newValue)))) {
+                                throw new MapperParsingException(
+                                    "can't merge a non object mapping [" + parent + "] with an object mapping"
+                                );
+                            }
+                        }
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:386]: Note for reviewer: this type conflict was identified before (when merging the parsed mappings) based on the mapper types (i.e. `FieldMapper` or `FieldAliasMapper` vs. `ObjectMapper`). Since I need to do that in the raw form now, this is what I came up with. Let me know if there are better options to discover this type of conflicts.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 5]
```diff
@@ -1303,7 +1306,7 @@ public static List<CompressedXContent> collectMappings(
             if (template.getDataStreamTemplate().isAllowCustomRouting()) {
                 mappings.add(0, DEFAULT_TIMESTAMP_MAPPING_WITH_ROUTING);
             } else {
-                mappings.add(0, DEFAULT_TIMESTAMP_MAPPING);
+                mappings.add(0, DEFAULT_TIMESTAMP_MAPPING_WITHOUT_ROUTING);
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:1309]: Note for reviewer: note that I had to use `"_routing": {"required": false}` explicitly here, instead of relying on the default, because otherwise there is no way to detect contradiction between mapping and settings coming from `ComposableIndexTemplate.DataStreamTemplate`, as they both get translated into a single `RoutingFieldMapper`.
Since this code is executed only if `template.getDataStreamTemplate() != null`, it should be same

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 6]
```diff
@@ -365,24 +368,73 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
-                return newMapper;
-            }
-            this.mapper = newMapper;
-            assert assertSerialization(newMapper);
+        Map<String, Object> mappingSourceAsMap = MappingParser.convertToMap(mappingSource);
+        return doMerge(type, reason, mappingSourceAsMap);
+    }
+
+    private synchronized DocumentMapper doMerge(String type, MergeReason reason, Map<String, Object> mappingSourceAsMap) {
+        Mapping incomingMapping = parseMapping(type, mappingSourceAsMap);
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:427]: This line doesn't need to be within the synchronized block I think?

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 7]
```diff
@@ -399,6 +451,22 @@ public Mapping parseMapping(String mappingType, CompressedXContent mappingSource
         }
     }
 
+    /**
+     * A method to parse mapping from a source in a map form, that allows to specify explicit/implicit {@code subobjects} configuration.
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:455]: No need to talk about subobjects here any more

File: server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java [hunk 8]
```diff
@@ -73,19 +73,36 @@ private static String getRemainingFields(Map<?, ?> map) {
...
+        return XContentHelper.convertToMap(source.compressedReference(), true, XContentType.JSON).v2();
+    }
+
+    Mapping parse(@Nullable String type, CompressedXContent source) throws MapperParsingException {
+        Map<String, Object> mapping = convertToMap(source);
+        return parse(type, mapping);
+    }
+
+    /**
+     * A method to parse mapping from a source in a map form, that allows to specify explicit/implicit {@code subobjects} configuration.
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java:87]: Similarly here, we can remove the doc about subobjects

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java:87]: But keep the javadoc in general, thanks for adding it!

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 9]
```diff
@@ -589,6 +590,27 @@ protected void doXContent(XContentBuilder builder, Params params) throws IOExcep
 
     }
 
+    /**
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:593]: I don't think we need this code any more?

**Review by romseygeek — COMMENTED** [review]
Thanks @eyalkoren, this looks great!  I left some comments/questions.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java (hunk 6 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:427]: Yeah, it's misleading this way 🙂 
It is currently within the synchronized block and [I learned the hard way](https://github.com/elastic/elasticsearch/pull/97199#discussion_r1249541239) that it does need to be within it.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 10]
```diff
@@ -365,24 +368,73 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+                            if (oldValue.equals(newValue) == false
+                                && (OBJECT_FIELD_TYPES.contains(String.valueOf(oldValue))
+                                    || OBJECT_FIELD_TYPES.contains(String.valueOf(newValue)))) {
+                                throw new MapperParsingException(
+                                    "can't merge a non object mapping [" + parent + "] with an object mapping"
+                                );
+                            }
+                        }
+                        case "subobjects" -> {
+                            if (oldValue.equals(newValue) == false) {
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:400]: Well, those are two contradicting  _**explicit**_ settings, so I figured we should assume that this is an error. Don't we prefer to let everyone this contradiction was introduced ASAP, instead of being surprised about the actual mappings?

File: server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java (hunk 8 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java:87]: 👍

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 9 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:593]: No, we don't! Good catch, thanks 🙏

**Comment by eyalkoren** [comment]
@romseygeek I just added a [test case](https://github.com/elastic/elasticsearch/pull/97317/commits/0e347b76130dd0d1e11935719c44447e166fdeb4) that failed and emphasized the fact that other sequential merges should be covered as well within this PR. So I applied the new bulk-merge for `MetadataCreateIndexService` as well.

@piergm originally proposed to do this small refactor in a separate PR, but I now think it better be part of this one. 
Please look in https://github.com/eyalkoren/elasticsearch/pull/1 what I plan to migrate to the new merge API and let me know what you think.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 11]
```diff
@@ -365,24 +369,83 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+
+        Map<String, Object> mergedRawMapping = null;
+        for (CompressedXContent mappingSource : mappingSources) {
+            Map<String, Object> rawMapping = MappingParser.convertToMap(mappingSource);
+            Iterator<String> iterator = rawMapping.keySet().iterator();
+            if (iterator.hasNext()) {
+                String rootName = iterator.next();
+                if (mappingParser.isRootMappingType(rootName, type)) {
+                    rawMapping = (Map<String, Object>) rawMapping.get(rootName);
+                }
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:391]: Maybe the opposite is the right thing to do 🤔 
This may result with a multi-root mapping, so maybe what we should really do is make sure all raw merges start with a common root (eg `_doc`), in other words- add `_doc` parent if it is not the root, rather than remove it if is the root

Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: Yep, the opposite is better- I eventually decided to normalize the mappings so that all have the provided `type` argument as their single common root.

**Comment by dakrone** [comment]
Piping in here with some background. We originally designed the mappings merging to treat each field as a unit, where the unit would override the entire field definition, rather than merging it like a recursive json map merge. The idea was that by doing this we would avoid a situation where a user configures a field A with option X, Y, and Z and then has a different template with the same field A configured with option M, and N — we didn't want to end up with a field A with options X, Y, Z, M, and N, but only the most recent "unit" configuration for the field.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 12]
```diff
@@ -96,8 +96,11 @@ public class MetadataIndexTemplateService {
             Map.of("type", DateFieldMapper.CONTENT_TYPE, "ignore_malformed", "false")
         );
         try {
-            DEFAULT_TIMESTAMP_MAPPING = new CompressedXContent(
+            DEFAULT_TIMESTAMP_MAPPING_WITHOUT_ROUTING = new CompressedXContent(
                 (builder, params) -> builder.startObject(MapperService.SINGLE_MAPPING_NAME)
+                    .startObject(RoutingFieldMapper.NAME)
+                    .field("required", false)
+                    .endObject()
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:103]: I think this needs a comment as to why this is necessary

**Review by dakrone — DISMISSED** [review]
I believe this breaks the way that template mapping merges work (see my previous comment about the history), for example, I would expect the following to work:

```
PUT /_component_template/one
{
  "template": {
    "mappings": {
      "properties": {
        "field": {
          "type": "long",
          "coerce": true
        }
      }
    }
  }
}

PUT /_index_template/it
{
  "index_patterns": ["foo"],
  "data_stream": {},
  "composed_of": ["one"],
  "template": {
    "mappings": {
      "properties": {
        "field": {
          "type": "keyword",
          "ignore_above": 1024
        }
      }
    }
  }
}
```

But instead I get:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "composable template [it] template after composition with component templates [one] is invalid"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "composable template [it] template after composition with component templates [one] is invalid",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "invalid composite mappings for [it]",
      "caused_by" : {
        "type" : "mapper_parsing_exception",
        "reason" : "Failed to parse mapping: unknown parameter [coerce] on mapper [field] of type [keyword]",
        "caused_by" : {
          "type" : "mapper_parsing_exception",
          "reason" : "unknown parameter [coerce] on mapper [field] of type [keyword]"
        }
      }
    }
  },
  "status" : 400
}
```

This scenario works correctly on `main` right now, so this would be a breaking change.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java (hunk 12 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:103]: I [commented](https://github.com/elastic/elasticsearch/pull/97317/files#r1285950199) elsewhere about this in the PR. Did you mean that, or adding a comment to the code?

**Comment by eyalkoren** [comment]
@dakrone thanks a lot for explaining the rationale 🙏 

One way to address the issue you raise is by defining what a _unit_ is and adjust the customized merge accordingly. For example, our customized merge can decide that under a node called `properties`, subtrees are _replaced_ instead of being _merged_.

The main question I need to be answered now is whether we should proceed with this direction and fix whatever needs fixing within the proposed merge, or should we abandon this path and do something else.
For example- instead of fixing the merge, we can fix the parsing logic by treating dots as a valid character for field names and stop relying on them to deduce object nesting.

If you want me to go down the current path, please provide all such limitations and scenarios and I'll adjust the algorithm accordingly.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java (hunk 12 above)
Comment (dakrone) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:103]: I meant in the code, so that future code spelunkers know why it's there.

**Comment by dakrone** [comment]
> whether we should proceed with this direction and fix whatever needs fixing within the proposed merge, or should we abandon this path and do something else.
> For example- instead of fixing the merge, we can fix the parsing logic by treating dots as a valid character for field names and stop relying on them to deduce object nesting.

The field name parsing code is not an area with which I'm intimately familiar, so I'd defer this decision to @romseygeek and his team. As long as the merging invariant of "_two separate and valid mappings configurations of the same field name should always merge to a valid mapping configuration for the field_", then I think either approach is fine.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 13]
```diff
@@ -365,24 +368,139 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+                XContentHelper.merge(type, mergedRawMapping, rawMapping, RawFieldMappingMerge.INSTANCE);
+            }
+        }
+        if (mergedRawMapping != null && mergedRawMapping.size() > 1) {
+            throw new MapperParsingException("cannot merge mapping sources with different roots");
+        }
+        return (mergedRawMapping != null) ? doMerge(type, reason, mergedRawMapping) : null;
+    }
+
+    private static class RawFieldMappingMerge implements XContentHelper.CustomMerge {
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:406]: Can you add a javadoc for a high-level explanation of how this custom merger behaves? I.e., its special treatment of `subobjects`, etc.

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentMapperTests.java [hunk 14]
```diff
@@ -95,7 +95,7 @@ public void testMergeObjectAndNested() throws Exception {
                 IllegalArgumentException.class,
                 () -> MapperService.mergeMappings(objectMapper, nestedMapper.mapping(), reason)
             );
-            assertThat(e.getMessage(), containsString("can't merge a nested mapping [obj] with a non-nested mapping"));
+            assertThat(e.getMessage(), containsString("can't merge a non nested mapping [obj] with a nested mapping"));
```
Comment (dakrone) [inline server/src/test/java/org/elasticsearch/index/mapper/DocumentMapperTests.java:98]: Minor grammatical nit
```suggestion
            assertThat(e.getMessage(), containsString("can't merge a non-nested mapping [obj] with a nested mapping"));
```

**Review by dakrone — COMMENTED** [review]
I took an initial look and it looks pretty good. I left only a couple of comments, and tomorrow I plan to spend some time manually testing this. I definitely think someone on the mapping side should take a look, as I'm only an expert on the template side, not the mapping side.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 15]
```diff
@@ -365,24 +368,139 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+                // anything else (e.g. "_doc", "_meta", "properties") - no custom merge, rely on caller merge logic
+                // field mapping entries of Map type (like "fields" and "meta") are handled above and should never reach here
+                return null;
+            } else {
+                switch (key) {
+                    case "subobjects" -> {
+                        if (oldValue.equals(newValue) == false) {
+                            throw new MapperParsingException("contradicting subobjects settings provided for field: " + parent);
+                        }
+                    }
```
Comment (felixbarny) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:448]: I'd like to understand more why we're throwing an exception in this case. It seems to prevent the following use case:

- we set `subobjects: false` in `logs@mappings`
- user wants to use subobjects (for example to use the `nested` field type) so they set `subobjects: true` in `logs@custom`

Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:448]: Since this merge is done on the raw mappings, it is only about _**explicit**_ contradiction in two field mappings, so I assumed this should lead to an error (if you set `subobjects: false` for a specific field, it is likely for a reason, so setting the opposite for the same field sounds like an error). However, I assume you are thinking about setting at the root level, where it is more likely to be a non-error merge.
Whatever all you wise reviewers here think is fine with me, I won't insist about this 🙂

Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:448]: Yes, I'm mostly concerned about the case where there are different values for `subobjects` at the root level. I don't have a strong opinion on other levels. However, I'd prefer the logic to be consistent, if possible. I think I'd prefer not having that restriction on the merge algorithm itself. If the mapping is invalid due to overriding `subobjects`, it'll fail in a different place, with a more specific error message. If it's not invalid, I don't see why we'd want to disallow overriding that flag.

File: rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/indices.put_index_template/15_composition.yml [hunk 16]
```diff
@@ -349,3 +349,146 @@
           index_patterns: ["purple-index"]
           composed_of: ["red", "blue"]
           ignore_missing_component_templates: ["foo"]
+
+---
+"Composable index templates that include subobjects: false at root":
+  - skip:
+      version: ' - 8.10.1'
+      reason: 'https://github.com/elastic/elasticsearch/issues/96768 fixed after 8.10.0'
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/indices.put_index_template/15_composition.yml:357]: Thanks. I will change to "fixed _**at**_ 8.11.0" and then cross my fingers this will be the case 🤞

**Comment by eyalkoren** [comment]
@dakrone when adding the [custom merge javadoc](https://github.com/elastic/elasticsearch/pull/97317/files#diff-32c1e36544e0c0ef775f9e26576ef7df0504cc05466e513ba7b143947c234784R408-R432), I realized that we never really went carefully over all mapping parameters to identify which we want to preserve when we merge, like we plan to do with `subobjects`. For example- what about [`dynamic`](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html) which takes affect on an entire subtree? Are there any other such that affect a field mapping subtree rather than only specific field's mapping? 

Also - are there other mapping parameters that can be set at the root level (like `subobjects`)? 
I know that [`ignore_malformed`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html#ignore-malformed-setting) can be set at the root level, but since it is done through the `settings` node, it won't be a problem. Note that any parameter under `_doc` other than `subobjects` will be lost during merge with the proposed algorithm.

**Comment by eyalkoren** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java (hunk 15 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:477]: I think this will be easiest to reason about if we separate out object mappers and leaf mappers:
- for leaf mappers, later templates win by replacing the definition entirely, so there's no merging
- for object mappers that have children appearing in multiple templates, the above rule means that the later templates win and replace the child definitions entirely
- given that, I think it makes most sense (and is most understandable) to also apply this to object mapper parameters, that is, later templates with parameter values that conflict with earlier templates win.  And as Felix says, if we end up with an invalid mapping at the end, we will get a failure in any case.

Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: Thanks for the input. I removed the explicit `subobjects` contradiction verification.

**Review by romseygeek — APPROVED** [review]
LGTM, thanks for all the work on this @eyalkoren

**Review by jbaiera — APPROVED** [review]
The changes LGTM, though I'm far from an expert in mapping stuff. The template changes seem harmless enough. Left just a couple small comments.

File: server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java [hunk 17]
```diff
@@ -73,19 +73,35 @@ private static String getRemainingFields(Map<?, ?> map) {
...
+     * @param mappingSource mapping source already converted to a map form, but not yet processed otherwise
+     * @return a parsed mapping
+     * @throws MapperParsingException in case of parsing error
+     */
+    @SuppressWarnings("unchecked")
+    Mapping parse(@Nullable String type, Map<String, Object> mappingSource) throws MapperParsingException {
+        if (mappingSource.isEmpty()) {
             if (type == null) {
-                throw new MapperParsingException("malformed mapping, no type name found");
+                throw new MapperParsingException("malformed mappingSource, no type name found");
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java:98]: Looks like a result of refactor indeed. I will restore the original message.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 18]
```diff
@@ -367,24 +370,159 @@ public void merge(IndexMetadata indexMetadata, MergeReason reason) {
...
+     * </ul>
+     * When merging field mappings, we want something else. Specifically:
+     * <ul>
+     *     <li> within field mappings node (which is nested within a {@code properties} node):
+     *     <ul>
+     *         <li> if both the base mapping and the mapping to merge into it are of mergeable types (e.g {@code object -> object},
+     *         {@code object -> nested}), then we only want to merge specific mapping entries:
+     *         <ul>
+     *             <li> {@code properties} node - merging fields from both mappings
+     *             <li> {@code subobjects} entry - since this setting affects an entire subtree, we need to keep it when merging
```
[the remark this answers is not in the document]
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:423]: Ah, I was misreading and thinking this was the conflict error part that we removed earlier.  All good then!

File: server/src/test/java/org/elasticsearch/common/xcontent/support/XContentHelperTests.java [hunk 19]
```diff
@@ -66,6 +67,163 @@ public void testMergingListValuesAreMapsOfOne() {
...
     }
 
+    public void testMergingDefaults() {
+        Map<String, Object> content = getMap("key1", "content", "key3", "content");
+        Map<String, Object> defaults = getMap("key2", "default", "key3", "default");
+        XContentHelper.mergeDefaults(content, defaults);
+        Map<String, Object> expected = getMap("key1", "content", "key2", "default", "key3", "content");
+        assertThat(content, equalTo(expected));
+    }
+
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply server/src/test/java/org/elasticsearch/common/xcontent/support/XContentHelperTests.java:77]: I extended `testMergingDefaults()` to include that

**Comment by chiarch84** [comment]
Dear all,
after reading this thread it is not clear to me what to do in order to have my mappings of subobjects merged and not overrid.
In version 8.9.2 the following component templates were merged correctly. Now from version 8.10 on, the third one overrides the second one even though the subobjects fields are not conflicting. Could you please help me to understand how I can make it work in the new versions? Thanks!

```
PUT _component_template/bdap_id
{
  "version": 1,
  "template": {
    "mappings": {
      "dynamic": false,
      "_source": {
        "enabled": true
      },
      "properties": {
        "id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        }
      }
    }
  },
  "_meta": {
    "description": "Composable template for storing text ids"
  }
}
```
 
```
 PUT _component_template/bdap_stac_itemproperties
{
  "version": 2,
  "template": {
    "mappings": {
      "dynamic": false,
      "_source": {
        "enabled": true
      },
      "properties": {
        "properties": {
          "properties": {
            "title": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword"
                }
              }
            },
            "description": {
              "type": "text"
            }
          }
        }
      }
    }
  },
  "_meta": {
    "description": "Composable template for storing STAC item properties"
  }
}
```
 
```
PUT _component_template/bdap_stac_itemproperties_sat
{
  "version": 2,
  "template": {
    "mappings": {
      "dynamic": false,
      "_source": {
        "enabled": true
      },
      "properties": {
        "properties": {
          "properties": {
            "sat:absolute_orbit": {
              "type": "integer"
            },
            "sat:relative_orbit": {
              "type": "integer"
            }
          }
        }
      }
    }
  },
  "_meta": {
    "description": "Composable template for storing STAC item properties for sat: extension"
  }
}
```
 
Here the final index_template:
```
PUT _index_template/bdap_template_items_stac
{
  "version": 1,
  "priority" : 5,
  "template": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "number_of_replicas": "1"
      }
    },
    "mappings": {
      "dynamic": "strict",
      "_source": {
        "enabled": true,
        "includes": [],
        "excludes": []
      },
      "_routing": {
        "required": false
      },
      "dynamic_templates": []
    },
    "aliases": {
      "bdap": {}
    }
  },
  "index_patterns": [
    "bdap-items-stac*",
    "bdap-test-items-stac*",
    "bdap-dev-items-stac*"
  ],
  "composed_of": [
    "bdap_id",
    "bdap_stac_itemproperties",
    "bdap_stac_itemproperties_sat"
  ],
  "_meta": {
    "description": "Composable template for storing STAC items used for PROD, TEST and DEV indexes"
  }
}
```
 
If I try to do the PUT of 1 first document in version 8.10 I get an error, while in 8.9.2 it created correctly the new index by merging the mappings.
```
PUT bdap-dev-items-stac-001/_doc/1
{
    "id": "Landcover.ESA.WorldCover2020.V1.item.VRT_ESA_WorldCover_10m_2020_v100_InputQuality",
    "properties": {
      "title": "ESA_WorldCover_10m_2020_v100_InputQuality.vrt",
      "description": "xcgsdfgsdfgsd",
      "sat:absolute_orbit": 45938,
      "sat:relative_orbit": 38,
    }
}
```

**Comment by eyalkoren** [comment]
@chiarch84 thanks for reporting!
At first glance, I think this is related to the specific case of merging mappings of a field named `properties`. I could have sworn I took this option into consideration, but I can't find any evidence for it.
Please verify that this is indeed the case (for example, try only renaming your `properties` field and see if this resolves the issue) and if so, please open a separate issue with the same description as above and with the error you get.
