### PR TITLE
TSDB: Fix time series bounds default value error

### LINKED ISSUE #82832: TSDB: Confusing error message for start/end dates
If I want to have a single TSDB index it would be reasonable for me to create an index with a broad time range that would look something like this:

```
PUT test
{
  "settings": {
    "index.mode": "time_series",
    "index.routing_path": "key",
    "index.time_series.start_time": "1970-01-01T00:00:00Z",
    "index.time_series.end_time": "9999-12-31T23:59:59.999Z"
  },
  "mappings": {
    "properties": {
      "key": {
        "type": "keyword",
        "time_series_dimension": true
      },
      "val": {
        "type": "double"
      }
    }
  }
}
```

This command is generating the error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "[index.mode=time_series] requires [index.time_series.start_time]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "[index.mode=time_series] requires [index.time_series.start_time]"
  },
  "status" : 400
}
```

Analysis: both `index.time_series.start_time` and `index.time_series.end_time` are there, they just happened to be equal to default values for this setting, which is cause the code think that the settings don't exist and report incorrect error message. Since we require this setting, I don't think we need a default for it.

### PR DESCRIPTION
**Pull request by imotov**
Adds support for default start and end dates that includes entire range of dates that we can parse from year -9999 to year 9999. That should simplify the onboarding experience since if a user doesn't use datastreams they get a single index that covers all time ranges. 

Fixes #82832

Co-authored-by: weizijun <weizijun1989@gmail.com>

### CODE REVIEW

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by imotov** [comment]
@weizijun I think this might be a bit simpler approach. As a side benefit we can now create a TSDB index with a much simpler command:
```
PUT test
{
  "settings": {
    "index.mode": "time_series",
    "index.routing_path": "dim"
  },
  "mappings": {
    "properties": {
      "dim": {
        "type": "keyword",
        "time_series_dimension": true
      },
      "val": {
        "type": "double"
      }
    }
  }
}
```

**Comment by weizijun** [comment]
> @weizijun I think this might be a bit simpler approach. As a side benefit we can now create a TSDB index with a much simpler command:
> 
> ```
> PUT test
> {
>   "settings": {
>     "index.mode": "time_series",
>     "index.routing_path": "dim"
>   },
>   "mappings": {
>     "properties": {
>       "dim": {
>         "type": "keyword",
>         "time_series_dimension": true
>       },
>       "val": {
>         "type": "double"
>       }
>     }
>   }
> }
> ```

It means that   `index.time_series.start_time` and `index.time_series.end_time` are not the required settings in the tsdb index.
In the previous design, the two settings must configured in the tsdb index. Maybe discuss with @nik9000  and @martijnvg.

File: server/src/main/java/org/elasticsearch/index/IndexMode.java [hunk 1]
```diff
@@ -90,13 +90,11 @@ void validateWithOtherSettings(Map<Setting<?>, Object> settings) {
                 }
             }
             settingRequiresTimeSeries(settings, IndexMetadata.INDEX_ROUTING_PATH);
```
Comment (weizijun) [inline server/src/main/java/org/elasticsearch/index/IndexMode.java:92]: routing_path also the default problem. e.g:
```
{
  "settings": {
    "index.mode": "time_series",
    "index.routing_path": ""
  }
}
```

it will failed as:
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "[index.mode=time_series] requires [index.routing_path]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "[index.mode=time_series] requires [index.routing_path]"
    },
    "status": 400
}
```

File: rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/10_settings.yml [hunk 2]
```diff
@@ -482,3 +523,36 @@ check end_time boundary with data_nano:
           "@timestamp": "2021-09-26T03:09:52.123456789Z",
           "metricset": "pod"
         }
+
+
+---
+check time_series default time bound value:
```
Comment (csoulios) [inline rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/10_settings.yml:529]: I think we should add one more test with missing `start_time` and `end_time` bounds and make sure the default values are set. I have only seen such a test as a unit test.

**Review by csoulios — APPROVED** [review]
LGTM 

I like the fact that index creation becomes simpler when no time bounds are required.

File: server/src/main/java/org/elasticsearch/index/IndexSettings.java [hunk 3]
```diff
@@ -702,7 +702,7 @@ public IndexSettings(final IndexMetadata indexMetadata, final Settings nodeSetti
         this.indexMetadata = indexMetadata;
         numberOfShards = settings.getAsInt(IndexMetadata.SETTING_NUMBER_OF_SHARDS, null);
         mode = isTimeSeriesModeEnabled() ? scopedSettings.get(MODE) : IndexMode.STANDARD;
-        this.timestampBounds = TIME_SERIES_START_TIME.exists(settings) ? new TimestampBounds(scopedSettings) : null;
+        this.timestampBounds = mode == IndexMode.TIME_SERIES ? new TimestampBounds(scopedSettings) : null;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/IndexSettings.java:705]: Do you want to delegate this to a method on `IndexMode`? Less hard tests is nice.

File: server/src/main/java/org/elasticsearch/index/IndexMode.java [hunk 4]
```diff
@@ -89,14 +95,12 @@ void validateWithOtherSettings(Map<Setting<?>, Object> settings) {
                     throw new IllegalArgumentException(error(unsupported));
                 }
             }
-            settingRequiresTimeSeries(settings, IndexMetadata.INDEX_ROUTING_PATH);
-            settingRequiresTimeSeries(settings, IndexSettings.TIME_SERIES_START_TIME);
-            settingRequiresTimeSeries(settings, IndexSettings.TIME_SERIES_END_TIME);
```
Comment (weizijun) [inline server/src/main/java/org/elasticsearch/index/IndexMode.java:94]: Are `IndexSettings.TIME_SERIES_START_TIME` and `IndexSettings.TIME_SERIES_END_TIME` not required in the time_series index? I added the checking code to make these settings required. This is a requirement for the time_series index before. Now remove the check will change the requirement.  I think it's ok to make these settings not required, but we should check that if it satisfies the design of time_series index.

Comment (imotov) [reply server/src/main/java/org/elasticsearch/index/IndexMode.java:94]: They are no longer required, but if they are not there we just use the default values.

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/IndexMode.java:94]: It looks like if you leave it blank he's got it configured to cover -9999 to 9999. I wasn't super keen on having defaults for these a few months ago, but I suppose it's fine.

**Review by nik9000 — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/IndexMode.java (hunk 4 above)
Comment (imotov) [reply server/src/main/java/org/elasticsearch/index/IndexMode.java:94]: My preference would be to support an entire range from Long.MIN_VALUE to Long.MAX_VALUE but we are not capable of parsing such dates. This is the entire range we can parse.
