### PR TITLE
[Test] Use random port instead of fixed port to avoid conflict

### LINKED ISSUE #94653: [CI] SimpleSecurityNetty4ServerTransportTests testClientChannelUsesSeparateSslConfigurationForRemoteCluster failing
This didn't reproduce locally for me on my mac but my suspicion is it might be Windows related.

**Build scan:**
https://gradle-enterprise.elastic.co/s/eertquvftst2e/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests/testClientChannelUsesSeparateSslConfigurationForRemoteCluster

**Reproduction line:**
```
gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testClientChannelUsesSeparateSslConfigurationForRemoteCluster" -Dtests.seed=AE878A5FDDFF0F54 -Dtests.locale=en-NZ -Dtests.timezone=US/Indiana-Starke -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests&tests.test=testClientChannelUsesSeparateSslConfigurationForRemoteCluster

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <100>
     but: was null

  at __randomizedtesting.SeedInfo.seed([AE878A5FDDFF0F54:1A613F99A3AFFDFF]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testClientChannelUsesSeparateSslConfigurationForRemoteCluster(SimpleSecurityNetty4ServerTransportTests.java:619)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by ywangd**
This PR makes the remote cluster transport to bind with a random port instead of a fixed one since a fixed port could sometimes fails to bind because previous test may not release it properly.

Resolves: #94653

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/netty4/SimpleSecurityNetty4ServerTransportTests.java [hunk 1]
```diff
@@ -525,7 +525,7 @@ public void testClientChannelUsesSeparateSslConfigurationForRemoteCluster() thro
 
         final Settings fcSettings = Settings.builder()
             .put("remote_cluster_server.enabled", "true")
-            .put("remote_cluster.port", "9999")
+            .put("remote_cluster.port", "0")
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/netty4/SimpleSecurityNetty4ServerTransportTests.java:528]: Not sure why I had it as `9999` previously, everywhere else we have used `0` for random port ...

**Review by slobodanadamovic — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
Sorry for the late review here but could we use `org.elasticsearch.test.ESTestCase#getPortRange()` rather than "0"? We run tests in parallel in CI, so binding to any (ephemeral) port will mean that other tests running concurrently may connect to this node instead of getting a `Connection refused` which sometimes leads to weird test failures.

**Comment by ywangd** [comment]
@DaveCTurner Unfortunately, the [remote cluster port setting](https://github.com/elastic/elasticsearch/blob/83402605eac06cbc678276d6c82ec82853968cb2/server/src/main/java/org/elasticsearch/transport/RemoteClusterPortSettings.java#L70) currently takes an integer so that it does not accept a port range. I am not sure whether we intentionally made it an integer. I can double check. Do you have a view about it?

**Comment by DaveCTurner** [comment]
Ah. Hmm. That was intentional, and I do think that port ranges are evil (in production) but I see that we use them for this kind of thing in tests. Would `org.elasticsearch.test.ESTestCase#getWorkerBasePort()` work here?

**Comment by DaveCTurner** [comment]
or maybe something like `getWorkerBasePort() + portGenerator.incrementAndGet() % PORTS_PER_WORKER`
