### PR TITLE
If the index does not exist, delete document will not auto create it

### LINKED ISSUE #15425: Deleting a document from a non-existing index creates the index
Using the default settings, if a delete request is issued for a single document against a non-existing index, Elasticsearch will create the index. Steps to reproduce:

```
DELETE /foo
```

```
DELETE /foo/bar/1
```

Then:

```
GET /foo
```

responds with HTTP 200 OK and response body

```
{
  "foo" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1450124918393",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "Ny3PruSCTIG5TlYecU0_XA",
        "version" : {
          "created" : "3000099"
        }
      }
    },
    "warmers" : { }
  }
}
```

showing that it created the index.

### PR DESCRIPTION
**Pull request by olcbean**
Currently a `delete document` request against a non-existing index actually **creates** this index.

With this change the `delete document` no longer creates the previously non-existing index and throws an `index_not_found` exception instead.

However as discussed in https://github.com/elastic/elasticsearch/pull/15451#issuecomment-165772026, if an external version is explicitly used, the current behavior is preserved and the index is still created and the document is marked for deletion.

Fixes #15425

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java [hunk 1]
```diff
@@ -67,8 +66,29 @@ public void testDelete() throws IOException {
             // Testing non existing document
             String docId = "does_not_exist";
             DeleteRequest deleteRequest = new DeleteRequest("index", "type", docId);
+            ElasticsearchException exception = expectThrows(ElasticsearchException.class,
+                    () -> execute(deleteRequest, highLevelClient()::delete, highLevelClient()::deleteAsync));
+            assertEquals(RestStatus.NOT_FOUND, exception.status());
+            assertEquals("Elasticsearch exception [type=index_not_found_exception, reason=no such index]", exception.getMessage());
```
Comment (bleskes) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java]: The goal of this test is to check how delete behaves where it doesn't find the document in question. I don't think there is a need to test the index creation on the rest client tests (this is done in the core testing). Just create the index and let the test what it does.

File: core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java [hunk 2]
```diff
@@ -223,6 +228,18 @@ public void testDelete() {
         assertSameIndices(deleteRequest, deleteShardActions);
     }
 
+    // for delete index throws an IndexNotFoundException if the index does not exist or create the index if external version is used
+    public void testDeleteAction() throws InterruptedException, ExecutionException {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java]: I think this is the wrong place for this - this suite checks that index names are passed correctly to sub request. IMO you should create a unit test  `TransportBulkActionTests` class, which inherits from `ESTestCase` and test how the `TransportBulkAction` decides which indices need to be auto created. You can look at how `TransportBulkActionIngestTests.TestTransportBulkAction` is set up as an example. Let me know if you need more guidance and I'm happy to help

File: core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java [hunk 3]
```diff
@@ -68,7 +68,7 @@ public void testAllFail() {
         bulkRequest.add(new IndexRequest("can't"));
         bulkRequest.add(new DeleteRequest("do"));
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java]: maybe change this to a delete request with an external version?

File: docs/reference/docs/delete.asciidoc [hunk 4]
```diff
@@ -105,7 +105,8 @@ thrown instead.
 [[delete-index-creation]]
 === Automatic index creation
 
-The delete operation automatically creates an index if it has not been
+If external version is used,
```
Comment (bleskes) [inline docs/reference/docs/delete.asciidoc]: can you mention external_gte too?

**Review by bleskes — CHANGES_REQUESTED** [review]
Thx @olcbean for the PR. I left some comments. We should add a section to the breaking changes documentation [here](https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_6_0/indices.asciidoc)

File: docs/reference/docs/delete.asciidoc (hunk 4 above)
Comment (olcbean) [inline docs/reference/docs/delete.asciidoc]: What about adding a link here as there are actually 3 external version types : `external`, `external_gt` and `external_gte` ?

Comment (bleskes) [inline docs/reference/docs/delete.asciidoc]: I'm fine with something generic here (if one of the external versioning variants is used) and linking to the versioning page.

File: core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java (hunk 2 above)
Comment (olcbean) [inline core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java]: @bleskes thanks for the tip, I will add a `TransportBulkActionTests`.

Hm... It appeared to me that at the time the issue was opened, the `delete` was not using `BulkAction` ( based on some comments ). So I decided to add the test here to verify that explicitly using the `delete` endpoint will not create the index. But of course I can remove it ;)

**Comment by olcbean** [comment]
@bleskes thank you for your review!

I just pushed the changes you suggested.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java [hunk 5]
```diff
@@ -65,6 +64,11 @@
     public void testDelete() throws IOException {
         {
             // Testing non existing document
+            final XContentType xContentType = randomFrom(XContentType.values());
```
Comment (bleskes) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java]: why was this added?

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 6]
```diff
@@ -144,6 +145,9 @@ protected void doExecute(Task task, BulkRequest bulkRequest, ActionListener<Bulk
             // Attempt to create all the indices that we're going to need during the bulk before we start.
             // Step 1: collect all the indices in the request
             final Set<String> indices = bulkRequest.requests.stream()
+                .filter(request -> request.opType() != DocWriteRequest.OpType.DELETE 
+                        || request.versionType() == VersionType.EXTERNAL
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: can you add a comment here as to why we have a special handling for external versions and deletes here?

File: core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java [hunk 7]
```diff
@@ -66,6 +66,7 @@
 import org.elasticsearch.action.index.IndexRequest;
 import org.elasticsearch.action.search.SearchRequest;
 import org.elasticsearch.action.search.SearchResponse;
+import org.elasticsearch.action.search.SearchTransportService;
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java]: nit: left over formatting.. can you please remove?

File: core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionTests.java [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+
+    @After
+    public void tearDown() throws Exception {
+        ThreadPool.terminate(threadPool, 30, TimeUnit.SECONDS);
+        threadPool = null;
+        clusterService.close();
+        super.tearDown();
+    }
+
+    public void testDeleteNonExistingDoc() throws Exception {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionTests.java]: can we call this `testDeleteNonExistingDocDoesNotCreateIndices`

File: core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionTests.java [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+            assertEquals(bulkResponses.length, 1);
+            assertTrue(bulkResponses[0].isFailed());
+            assertTrue(bulkResponses[0].getFailure().getCause() instanceof IndexNotFoundException);
+            assertEquals("index", bulkResponses[0].getFailure().getIndex());
+        }, exception -> {
+            throw new AssertionError(exception);
+        }));
+    }
+
+    public void testDeleteNonExistingDocExternalVersion() throws Exception {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionTests.java]: same comment about naming. Can we add "CreatesIndex"?

**Review by bleskes — CHANGES_REQUESTED** [review]
Looks great. I left some very minor requests.

File: core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java (hunk 7 above)
Comment (olcbean) [inline core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java]: Hm... you want me revert and leave the imports not organized?

In general I agree that major reformatting should happen separately but it is just a single import ;)

Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/IndicesRequestIT.java]: I hear you. On the other hand, it's just a reset to commit away :)

File: client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java (hunk 5 above)
Comment (olcbean) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java]: I could not figure out how else to explicitly create an index in the REST client... Do you have a suggestion?

**Comment by olcbean** [comment]
@bleskes thanks for the remarks! 

Do you know how I can simply create an index in the REST client?
I know that what I came up with is far from ideal, but I did not see an alternative. It would be great if you can give me a pointer or idea?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java (hunk 5 above)
Comment (bleskes) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java]: I think you still need to use the low level client for that, using `client().performRequest()`. That said, why not change the order of the test blocks around and move the `// Testing deletion` block to be first. It will create the index.

Comment (olcbean) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/CrudIT.java]: Well, duh! :blush: Thanks @bleskes!

**Review by bleskes — APPROVED** [review]

**Comment by bleskes** [comment]
thanks a lot @olcbean . I'll merge this in.
