### PR TITLE
Fix AbstractSimpleTransportTestCase#testFailToSend

### LINKED ISSUE #75209: [CI] SimpleNetty4TransportTests testFailToSend failing
Due to #73551, error message has changed.

**Build scan:**
https://gradle-enterprise.elastic.co/s/itxvntcdo6fvm/tests/:modules:transport-netty4:test/org.elasticsearch.transport.netty4.SimpleNetty4TransportTests/testFailToSend

**Reproduction line:**
`./gradlew ':modules:transport-netty4:test' --tests "org.elasticsearch.transport.netty4.SimpleNetty4TransportTests.testFailToSend" -Dtests.seed=FE125CC6FCFFBAF8 -Dtests.locale=ro -Dtests.timezone=Asia/Sakhalin -Druntime.java=8`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.transport.netty4.SimpleNetty4TransportTests&tests.test=testFailToSend

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "failure to send"
     but: was "[TS_A][127.0.0.1:16701][fail-to-send-action]"

  at __randomizedtesting.SeedInfo.seed([FE125CC6FCFFBAF8:6FD3E050CBA36379]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.transport.AbstractSimpleTransportTestCase.testFailToSend(AbstractSimpleTransportTestCase.java:2849)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by iverase**
In #73551 we changed how we wrap exception in the transport handler. This make this test fail as the error message has changed slightly. This PR adjust the test to the new situation and it actually removes some randomisation so both paths the test is checking are run every time.

fixes https://github.com/elastic/elasticsearch/issues/75209

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]

File: test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java [hunk 1]
```diff
@@ -2708,15 +2708,21 @@ public void onConnectionClosed(Transport.Connection connection) {
...
+        TransportException exception = doFailToSend(new TransportException("fail to send"));
+        assertThat(exception.getMessage(), equalTo("fail to send"));
+        assertThat(exception.getCause(), nullValue());
+    }
+
+    public void testFailToSendIllegalStateException() throws InterruptedException {
+        TransportException exception = doFailToSend(new IllegalStateException("fail to send"));
+        assertThat(exception.getMessage(), containsString("fail-to-send-action"));
+        assertThat(exception.getCause(), instanceOf(IllegalStateException.class));
+        assertThat(exception.getCause().getMessage(), equalTo("fail to send"));
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java:2721]: Can we add:

```
assertThat(te.get(), instanceOf(SendRequestTransportException.class));
```

**Review by henningandersen — APPROVED** [review]
LGTM.

File: test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java (hunk 1 above)
Comment (iverase) [reply test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java:2721]: sure

**Comment by iverase** [comment]
Unrelated error, open https://github.com/elastic/elasticsearch/issues/75212 

@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-1
