### PR TITLE
Adjust CacheFileTests.testCacheFileCreatedAsSparseFile for encryption at rest

### LINKED ISSUE #81362: [CI] CacheFileTests.testCacheFileCreatedAsSparseFile fails on master
**Build scan**:
https://gradle-enterprise.elastic.co/s/lny65mo6chmek

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests.testCacheFileCreatedAsSparseFile" \
  -Dtests.seed=E7AB31A9E717E54B \
  -Dtests.locale=zh-CN \
  -Dtests.timezone=Etc/GMT-5 \
  -Druntime.java=17

REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests.testCacheFileCreatedAsSparseFile" \
  -Dtests.seed=E7AB31A9E717E54B \
  -Dtests.locale=zh-CN \
  -Dtests.timezone=Etc/GMT-5 \
  -Druntime.java=17
```

**Reproduces locally?**:
No

**Applicable branches**:
`master`

**Failure history**:
Two failures today.
No prior failures of this test.

**Failure excerpt**:
```
11:54:36 org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests > testCacheFileCreatedAsSparseFile FAILED
11:54:36     java.lang.AssertionError
11:54:36         at __randomizedtesting.SeedInfo.seed([45B7968DCEE813EC:C0396B8309F7EF9D]:0)
11:54:36         at org.junit.Assert.fail(Assert.java:86)
11:54:36         at org.junit.Assert.assertTrue(Assert.java:41)
11:54:36         at org.junit.Assert.assertTrue(Assert.java:52)
11:54:36         at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests.testCacheFileCreatedAsSparseFile(CacheFileTests.java:422)
```

### PR DESCRIPTION
**Pull request by tlrx**
This test fails sometimes on CI when it is executed on encrypted filesystems: the test tries to detect the block size by writing a single byte at the end of a larger file, which should result in a single block allocated, but on encrypted filesystems it can result in more than a single block being reserved.

This commit adjusts the test so that it assumes that a default block size of 4KB is always used on Linux, and if the default block size is different then it assumes that the test is executed on an encrypted filesystem and that the allocated size stays within an upper bound.

Relates https://github.com/elastic/elasticsearch/issues/81362#issuecomment-988333284

Closes #81362

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java [hunk 1]
```diff
@@ -455,13 +453,41 @@ public void testCacheFileCreatedAsSparseFile() throws Exception {
...
+                            + ", file length: "
+                            + cacheFile.getLength()
+                            + ')',
+                        sizeOnDisk.getAsLong(),
+                        allOf(greaterThanOrEqualTo(expectedSize), lessThanOrEqualTo(expectedSize + fourKb))
+                    );
+                    assertThat(
+                        "Non default block size only used in test executed with encryption at rest",
+                        file.toAbsolutePath().toString(),
+                        startsWithIgnoringCase("/mnt/secret")
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java:488]: This is not great but I can't figure a better way to check that encryption at rest is used.

See https://github.com/elastic/elasticsearch/blob/3f6fc8e592893deccb8bf231fbc01453149de116/.ci/jobs.t/elastic%2Belasticsearch%2Bperiodic%2Bear.yml#L28

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java [hunk 2]
```diff
@@ -455,13 +452,41 @@ public void testCacheFileCreatedAsSparseFile() throws Exception {
...
+                    assertThat(
+                        "Cache file size mismatches with non default block size (block size: "
+                            + blockSize
+                            + ", number of blocks: "
+                            + nbBlocks
+                            + ", file length: "
+                            + cacheFile.getLength()
+                            + ')',
+                        sizeOnDisk.getAsLong(),
+                        allOf(greaterThanOrEqualTo(expectedSize), lessThanOrEqualTo(expectedSize + fourKb))
```
Comment (DaveCTurner) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java:482]: I wonder if we're being too prescriptive here. We don't really care how big the file is on disk (we've already checked that it's no longer too small). It's kind of nice that you can often compute the size on disk by rounding up the actual size to the next multiple of `blockSize` but maybe we don't even need this assertion?

Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java:482]: Thinking about it this morning, I do agree. Being able to round up to the next `4KB` is just a consequence of generating files of 1MB max. I removed the whole assertion and just kept the `/mnt/secret` - with an additionnal comment.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks David
