### PR TITLE
ESQL: Allow the data type of `null` in filters

### LINKED ISSUE #116351: [ES|QL] `where null` throws `VerificationException` when it is not under an aggregation
The behavior of null filter is different when it is under or not under an aggregation. 

Null filter is allowed under aggregation
```
from employees
| stats max = max(salary), max_a = max(salary) where null,
        min = min(salary), min_a = min(salary) where to_string(null) == "abc"  
;

max:integer |max_a:integer|min:integer | min_a:integer
74999       |null         |25324       | null        
;
```
However if a null filter is not under an aggregation, `VerificationException ` is thrown
```
{"query": "from sample_data | where null"}
{
  "error" : {
    "type" : "verification_exception",
    "reason" : "Found 1 problem\nline 1:26: Condition expression needs to be boolean, found [NULL]"
  },
  "status" : 400
}
```

Both postgresql and mysql allow `where null`, it returns empty resultset and doesn't error out. We may want to have `where null` behave the same when it is not under an aggregation.

### PR DESCRIPTION
**Pull request by kanoshiou**
Allow filter null in ESQL.

Closes #116351

### CODE REVIEW

**Comment by kanoshiou** [comment]
I think I should write another test where the result is empty when where `null` is used, but I don't know which file to write it in.

**Comment by fang-xing-esql** [comment]
> I think I should write another test where the result is empty when where `null` is used, but I don't know which file to write it in.

Thank you for contributing to Elasticsearch. 

You may add more complicated queries in some of the `csv-spec` files under [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/qa/testFixtures/src/main/resources/) to validate the query returns correct results. For example, the [null.csv-spec](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/qa/testFixtures/src/main/resources/null.csv-spec) could be a good place to add null related queries.

And you may also add more complicated queries to [LogicalPlanOptimizerTests](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java) to validate the query plans sent from coordinator node to the data nodes are as expected.

As this change affects the behavior of the targeting queries on different Elasticsearch versions, backward compatibility should also be taken into account.

**Comment by kanoshiou** [comment]
Thank you for your detailed guidance @fang-xing-esql ! 

I have added some tests, but I am not sure if they meet the requirements. Please let me know if any changes are needed.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -6722,4 +6722,26 @@ public void testMatchFunctionIsNotNullable() {
...
+        assertThat(local.supplier(), equalTo(LocalSupplier.EMPTY));
+
+        VerificationException e = expectThrows(VerificationException.class, () -> plan("""
+            from test
+            | where concat(first_name, "foobar")
+            """));
+        assertThat(
+            e.getMessage(),
+            containsString("Found 1 problem\nline 2:9: Condition expression needs to be boolean, found [KEYWORD]")
+        );
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:6745]: This test can be moved to `VerifierTests`, as the `VerificationException` is thrown before `LogicalPlanOptimizer`.

**Review by fang-xing-esql — COMMENTED** [review]
Thank you @kanoshiou! I left a small comment, the rest looks good.

**Comment by kanoshiou** [comment]
Thank you for reviewing, @fang-xing-esql ! 

I've updated the branch according to your comment.

**Comment by fang-xing-esql** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
Hi @fang-xing-esql ,

I tried the command in [buildkite](https://buildkite.com/elastic/elasticsearch-pull-request/builds/48205#0194036e-c8bb-4654-bdd3-7b7ecdfdc77e)  to reproduce the failure on my local machine, but no exception was throwsn. This is quite puzzling.

**Comment by fang-xing-esql** [comment]
buildkite test this

**Comment by fang-xing-esql** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
I believe the [failed tests](https://buildkite.com/elastic/elasticsearch-pull-request/builds/48589#019427e1-e601-4f2b-802e-5d49dabcbc18) are unrelated to my code changes, @fang-xing-esql .

I’ve merged the latest code into my branch. The first failed test case has been muted by #119510, and I have tested the remaining two failed tests; they passed successfully.

Hope the tests pass this time. 🤞

**Comment by fang-xing-esql** [comment]
buildkite test this

**Comment by fang-xing-esql** [comment]
buildkite test this

**Review by fang-xing-esql — APPROVED** [review]
Thank you for your contribution to elasticsearch @kanoshiou! Looks good to me.

**Comment by kanoshiou** [comment]
Thank you for approving this PR @fang-xing-esql! Just a gentle reminder in case you forget to click the merge button.
