### PR TITLE
EQL: Fix NPE from incorrect use of ids search

### LINKED ISSUE #63030: EQL: NPE for sequences returning more than 10 documents.
Depending on the data size and query, a sequence query can fail with:

```
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.search.SearchHit.getIndex()" because "hit" is null
        at org.elasticsearch.xpack.eql.execution.sequence.SequencePayload.<init>(SequencePayload.java:30) ~[?:?]
        at org.elasticsearch.xpack.eql.execution.sequence.TumblingWindow.lambda$payload$5(TumblingWindow.java:306) ~[?:?]
        at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:23) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:23) [x-pack-ql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.eql.execution.search.PITAwareQueryClient.lambda$searchWithPIT$1(PITAwareQueryClient.java:61) [x-pack-eql-8.0.0-SNAPSHOT.j
```

This affects only `sequence` queries.

### PR DESCRIPTION
**Pull request by costin**
This fixes a bug introduced when moving from mget to ids query. While
mget returns all the ids given, id query is a search query and thus by
default returns only 10 documents.
The fix correctly sets the expected size so all the information is
returned inside the response.

Fix #63030

### CODE REVIEW

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/BasicQueryClient.java [hunk 1]
```diff
@@ -94,7 +95,10 @@ public void fetchHits(Iterable<List<HitReference>> refs, ActionListener<List<Lis
             .fetchSource(FetchSourceContext.FETCH_SOURCE)
             .trackTotalHits(false)
             .trackScores(false)
-            .query(idsQuery);
+            .query(idsQuery)
+            // the default size is 10 so be sure to change it
+            // this is different from mget
+            .size(referenceToPosition.size() + 1);
```
Comment (matriv) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/BasicQueryClient.java:101]: Why is this `+ 1` ?

**Review by matriv — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Asking for another review since fetchHits moved from using one search request (which could lead to document clashes across multiple indices) to multiSearch which in turn required handling for PIT.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/PITAwareQueryClient.java [hunk 2]
```diff
@@ -42,46 +48,83 @@ public PITAwareQueryClient(EqlSession eqlSession) {
...
+        super.search(search, pitListener(r -> {
+            // get pid
+            for (MultiSearchResponse.Item item : r.getResponses()) {
+                // pick the first non-failing response
+                if (item.isFailure() == false) {
+                    return item.getResponse().pointInTimeId();
+                }
+            }
+            // no results or successful responses, preserve the current pid
+            return pitId;
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/PITAwareQueryClient.java:90]: @jimczi @dnhatn fyi, this is the current code I've used for updating pit when dealing with multiSearch.

**Review by matriv — APPROVED** [review]
LGTM

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/BasicQueryClient.java [hunk 3]
```diff
@@ -67,37 +68,35 @@ protected void search(SearchRequest search, ActionListener<SearchResponse> liste
...
         int counter = 0;
 
         for (List<HitReference> list : refs) {
             innerListSize = list.size();
             for (HitReference ref : list) {
-                idsQuery.addIds(ref.id());
-                indices.add(ref.index());
-                // remember the reference position
+                // keep ids per index
+                IdsQueryBuilder query = queries.computeIfAbsent(ref.index(), v -> idsQuery());
```
Comment (jimczi) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/search/BasicQueryClient.java:89]: You also need to filter by index too since the query will hit all the indices inside the PIT so you might have duplicates ? So two filter clauses are needed, one for the ids and one to match the right index.
