### PR TITLE
Make Timestamps Returned by Snapshot APIs Consistent

### LINKED ISSUE #43074: Snapshot status API returns different timing information than snapshot info API
Snapshot info API returns the following stats for a given snapshot:
```
      "start_time" : "2019-06-10T23:02:36.637Z",
      "start_time_in_millis" : 1560207756637,
      "end_time" : "2019-06-10T23:02:37.040Z",
      "end_time_in_millis" : 1560207757040,
      "duration_in_millis" : 403,
```

Snapshot status API returns the following overall stats for the same snapshot:
```
        "start_time_in_millis" : 1560207756712,
        "time_in_millis" : 290,
```

Note that the `start_time_in_millis` values are different. The overall duration is also different, if `time_in_millis` is meant to represent the same duration as `duration_in_millis`.

I'm not sure if this is a bug or expected behavior. If it is expected, the difference should be documented more clearly.

<details><summary>Full request and responses</summary>
<p>

```
# GET /_snapshot/my-backups/snapshot_3
{
  "snapshots" : [
    {
      "snapshot" : "snapshot_3",
      "uuid" : "e450-h_FSjuTKaTNFqaZAQ",
      "version_id" : 8000099,
      "version" : "8.0.0",
      "indices" : [
        ".kibana_1",
        ".kibana_task_manager",
        ".security-7"
      ],
      "include_global_state" : true,
      "state" : "SUCCESS",
      "start_time" : "2019-06-10T23:02:36.637Z",
      "start_time_in_millis" : 1560207756637,
      "end_time" : "2019-06-10T23:02:37.040Z",
      "end_time_in_millis" : 1560207757040,
      "duration_in_millis" : 403,
      "failures" : [ ],
      "shards" : {
        "total" : 3,
        "failed" : 0,
        "successful" : 3
      }
    }
  ]
}


# GET /_snapshot/my-backups/snapshot_3/_status
{
  "snapshots" : [
    {
      "snapshot" : "snapshot_3",
      "repository" : "my-backups",
      "uuid" : "e450-h_FSjuTKaTNFqaZAQ",
      "state" : "SUCCESS",
      "include_global_state" : true,
      "shards_stats" : {
        "initializing" : 0,
        "started" : 0,
        "finalizing" : 0,
        "done" : 3,
        "failed" : 0,
        "total" : 3
      },
      "stats" : {
        "incremental" : {
          "file_count" : 22,
          "size_in_bytes" : 26378
        },
        "total" : {
          "file_count" : 67,
          "size_in_bytes" : 107766
        },
        "start_time_in_millis" : 1560207756712,
        "time_in_millis" : 290
      },
      "indices" : {
        ".kibana_task_manager" : {
          "shards_stats" : {
            "initializing" : 0,
            "started" : 0,
            "finalizing" : 0,
            "done" : 1,
            "failed" : 0,
            "total" : 1
          },
          "stats" : {
            "incremental" : {
              "file_count" : 0,
              "size_in_bytes" : 0
            },
            "total" : {
              "file_count" : 7,
              "size_in_bytes" : 13074
            },
            "start_time_in_millis" : 1560207756712,
            "time_in_millis" : 11
          },
          "shards" : {
            "0" : {
              "stage" : "DONE",
              "stats" : {
                "incremental" : {
                  "file_count" : 0,
                  "size_in_bytes" : 0
                },
                "total" : {
                  "file_count" : 7,
                  "size_in_bytes" : 13074
                },
                "start_time_in_millis" : 1560207756712,
                "time_in_millis" : 11
              }
            }
          }
        },
        ".security-7" : {
          "shards_stats" : {
            "initializing" : 0,
            "started" : 0,
            "finalizing" : 0,
            "done" : 1,
            "failed" : 0,
            "total" : 1
          },
          "stats" : {
            "incremental" : {
              "file_count" : 0,
              "size_in_bytes" : 0
            },
            "total" : {
              "file_count" : 35,
              "size_in_bytes" : 59988
            },
            "start_time_in_millis" : 1560207756712,
            "time_in_millis" : 36
          },
          "shards" : {
            "0" : {
              "stage" : "DONE",
              "stats" : {
                "incremental" : {
                  "file_count" : 0,
                  "size_in_bytes" : 0
                },
                "total" : {
                  "file_count" : 35,
                  "size_in_bytes" : 59988
                },
                "start_time_in_millis" : 1560207756712,
                "time_in_millis" : 36
              }
            }
          }
        },
        ".kibana_1" : {
          "shards_stats" : {
            "initializing" : 0,
            "started" : 0,
            "finalizing" : 0,
            "done" : 1,
            "failed" : 0,
            "total" : 1
          },
          "stats" : {
            "incremental" : {
              "file_count" : 22,
              "size_in_bytes" : 26378
            },
            "total" : {
              "file_count" : 25,
              "size_in_bytes" : 34704
            },
            "start_time_in_millis" : 1560207756844,
            "time_in_millis" : 158
          },
          "shards" : {
            "0" : {
              "stage" : "DONE",
              "stats" : {
                "incremental" : {
                  "file_count" : 22,
                  "size_in_bytes" : 26378
                },
                "total" : {
                  "file_count" : 25,
                  "size_in_bytes" : 34704
                },
                "start_time_in_millis" : 1560207756844,
                "time_in_millis" : 158
              }
            }
          }
        }
      }
    }
  ]
}
```
</p>
</details>

### PR DESCRIPTION
**Pull request by original-brownbear**
* We don't have to calculate the start and end times form the shards for the status API, we have the start time available from the CS or the `SnapshotInfo` in the repo and can either take the end time form the `SnapshotInfo` or
take the most recent time from the shard stats for in progress snapshots
* Had to add serialization of these time values since we can't compute them from the shards anymore
   * Fall back to computing time values from shards in BwC scenario 
* Started a new IT class for this since the existing ones are huge already and we have a few more API inconsistencies with snapshots to fix and add tests for
* Closes #43074

------------

Admittedly the weird mutable data structures, `SnapshotStats` in particular becomes a little more magical than it already is with this change. I'd try to clean this up in a follow-up.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStats.java [hunk 1]
```diff
@@ -46,6 +46,11 @@
     SnapshotStats() {
     }
 
+    SnapshotStats(long startTime, long time) {
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStats.java]: I don't think we need another constructor just for this, maybe reuse the existing one?

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java [hunk 2]
```diff
@@ -71,14 +72,14 @@
...
-                   final Boolean includeGlobalState) {
+    SnapshotStatus(Snapshot snapshot, State state, List<SnapshotIndexShardStatus> shards, Boolean includeGlobalState,
+                   long startTime, long time) {
         this.snapshot = Objects.requireNonNull(snapshot);
         this.state = Objects.requireNonNull(state);
         this.shards = Objects.requireNonNull(shards);
         this.includeGlobalState = includeGlobalState;
         shardsStats = new SnapshotShardsStats(shards);
-        updateShardStats();
+        updateShardStats(startTime, time);
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: Can we check that they are not < 0?

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java [hunk 3]
```diff
@@ -239,8 +239,10 @@ private SnapshotsStatusResponse buildResponse(SnapshotsStatusRequest request, Li
                         default:
                             throw new IllegalArgumentException("Unknown snapshot state " + snapshotInfo.state());
                     }
+                    final long startTime = snapshotInfo.startTime();
                     builder.add(new SnapshotStatus(new Snapshot(repositoryName, snapshotId), state,
-                        Collections.unmodifiableList(shardStatusBuilder), snapshotInfo.includeGlobalState()));
+                        Collections.unmodifiableList(shardStatusBuilder), snapshotInfo.includeGlobalState(),
+                        startTime, snapshotInfo.endTime() - startTime));
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java]: I don't think that SnapshotInfo guarantees that endTime > startTime, maybe we should be defensive here?

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+import org.elasticsearch.common.settings.Settings;
+import org.elasticsearch.test.ESIntegTestCase;
+
+import java.util.List;
+
+import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.greaterThan;
+
+@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST)
```
Comment (tlrx) [inline server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java]: I don't think this is needed, the default scope SUITE should be fine

**Review by tlrx — APPROVED** [review]
LGTM, thanks for taking care of this. I left some minor comments

I agree that SnapshotStats would benefit from a clean up

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStats.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStats.java]: Sure, I guess I hated putting all those `0` but it's shorted this way for sure and horrible regardless :D

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java]: Well no it doesn't but this isn't a new issue is it?  It just shows up in two places now instead of in one. If you have skewed clocks and a master failover during snapshotting the absolute timestamp stored in the CS won't work out. All that happens now is that we see the same issue in two places instead of one?

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java]: I guess for a single test it doesn't matter anyway, but in general I'm not a big fan of the suit scope when running tests that so heavily depend on the exact state of the cluster like here -> that's why I went with test scope. Not sure if that makes sense?

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: Actually, I don't think we need to I think :) We get these numbers from `org.elasticsearch.index.snapshots.IndexShardSnapshotStatus` which does all the checks internally so we should be good here?

**Comment by original-brownbear** [comment]
After merging `master` into this branch (even after resolving the compile issue) this is actually failing tests. Looking into it, something is off now with the timestamps somewhere.

**Comment by original-brownbear** [comment]
@tlrx I have to admit, your initial instincts about the possibility of negative timestamps were correct after all. I had to push 6223466 after merging `master`. There were two issues here:
1. The code I changed from using relative to absolute time needed absolute time. Otherwise, it will not work in a BwC scenario (because in those we will still use the time stamp on the shards to calculate the end and start times) so I moved all the logic in the repo and snapshot handling that was relevant to the same absolute time method on the thread pool to get things consistent here
2. The logic of calculating the start and end time needs to be disabled when using timestamps from `SnapshotInfo`. This only worked fine when all the code was using `System.currentTimeMillis` but stopped working now with cached time. Since all the nodes in the test cluster use different thread pools that was simulating clock skew, which lead to the calculation not working out anymore (since due to skew a shard could look like it started before the snapshot itself or finished after).

Can you take another look please? :)

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java (hunk 2 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java]: :+1:

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java (hunk 4 above)
Comment (tlrx) [reply server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java]: I still don't think there is a reason here to use TEST and not the default, unless you noticed test failures with the SUITE test scope and if so we need to investigate them.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java (hunk 3 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java]: Ok

**Review by tlrx — APPROVED** [review]
LGTM. I left a comment about test scope which I think is important.

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java]: Fine with me :) Removed it.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
