### PR TITLE
Fix incorrect results for aggregations nested under a nested aggregation

### LINKED ISSUE #27912: Aggregations using nested and filter is different on ES 6.1.x
**Elasticsearch version**
Version: 6.1.0, Build: c0c1ba0/2017-12-12T12:32:54.550Z, JVM: 1.8.0_131
Version: 5.6.5, Build: 6a37571/2017-12-04T07:50:10.466Z, JVM: 1.8.0_144

**JVM version**:
1.8.0_131

**OS version**
Ubuntu 14.04 - Linux 4.4.0-93-generic #116~14.04.1-Ubuntu
Arch Linux - Linux 4.14.6-1-ARCH

**Description of the problem including expected versus actual behavior**:
Aggregations with nested and filter aggregation changed from ES 5.6.5, returning wrong bucket count.

Expected behavior:
It should return correct bucket count when using both nested and filter aggregation

Actual behavior:
Wrong bucket count, including some null keys

**Steps to reproduce**:

 1. Create a new index with nested fields
```
PUT /catalog
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "product": {
      "properties": {
        "name": { "type": "text" },
        "attributes": {
          "type": "nested",
          "properties": {
            "key": { "type": "keyword" },
            "value": { "type": "keyword" }
          }
        },
        "ranges": {
          "type": "nested",
          "properties": {
            "key": { "type": "keyword" },
            "value": { "type": "double" }
          }
        }
      }
    }
  }
}
```

 2. Index some documents
```
PUT /catalog/product/1
{
  "name": "Product 1",
  "attributes": [
    { "key": "category", "value": "t-shirts" },
    { "key": "brand", "value": "fake1" }
  ],
  "ranges": [ { "key": "price", "value": 10 } ]
}

PUT /catalog/product/2
{
  "name": "Product 2",
  "attributes": [
    { "key": "category", "value": "shoes" },
    { "key": "brand", "value": "fake2" }
  ],
  "ranges": [ { "key": "price", "value": 100 } ]
}

PUT /catalog/product/3
{
  "name": "Product 3",
  "attributes": [
    { "key": "category", "value": "candy" },
    { "key": "brand", "value": "fake3" }
  ],
  "ranges": [ { "key": "price", "value": 5 } ]
}
```

 3. Do a nested aggregation to create facets (match_all is just for this test, there are some filters)
```
GET /catalog/product/_search
{
  "size": 0,
  "aggs": {
    "1": {
      "filter": {
        "match_all": {}
      },
      "aggs": {
        "2": {
          "nested": {
            "path": "attributes"
          },
          "aggs": {
            "3": {
              "terms": {
                "field": "attributes.key",
                "size": 100
              },
              "aggs": {
                "4": {
                  "terms": {
                    "field": "attributes.value",
                    "size": 100
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

4. Do a nested aggregation using script (notice the "key": "null1")
```
GET /catalog/product/_search
{
  "size": 0,
  "aggs": {
    "1": {
      "filter": {
        "match_all": {}
      },
      "aggs": {
        "2": {
          "nested": {
            "path": "attributes"
          },
          "aggs": {
            "3": {
              "terms": {
                "script": "doc['attributes.key'].value + '1'",
                "size": 100
              },
              "aggs": {
                "4": {
                  "terms": {
                    "field": "attributes.value",
                    "size": 100
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Provide logs (if relevant)**:

Returned values with ES 6.1.x (only aggregation node)
Where is brand fake3 and category candy? Why the null1?

```
{
  "1": {
    "2": {
      "3": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "fake1",
                  "doc_count": 1
                },
                {
                  "key": "fake2",
                  "doc_count": 1
                }
              ]
            },
            "key": "brand",
            "doc_count": 2
          },
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "shoes",
                  "doc_count": 1
                },
                {
                  "key": "t-shirts",
                  "doc_count": 1
                }
              ]
            },
            "key": "category",
            "doc_count": 2
          }
        ]
      },
      "doc_count": 6
    },
    "doc_count": 3
  }
}
```
```
{
  "1": {
    "2": {
      "3": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "fake1",
                  "doc_count": 1
                },
                {
                  "key": "fake2",
                  "doc_count": 1
                }
              ]
            },
            "key": "brand1",
            "doc_count": 2
          },
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "shoes",
                  "doc_count": 1
                },
                {
                  "key": "t-shirts",
                  "doc_count": 1
                }
              ]
            },
            "key": "category1",
            "doc_count": 2
          },
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "fake2",
                  "doc_count": 1
                },
                {
                  "key": "shoes",
                  "doc_count": 1
                }
              ]
            },
            "key": "null1",
            "doc_count": 2
          }
        ]
      },
      "doc_count": 6
    },
    "doc_count": 3
  }
}
```

Returned values with ES 5.6.5 (only aggregation node)
This version returns both fake3 and candy buckets and no null keys

```
{
  "1": {
    "2": {
      "3": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "fake1",
                  "doc_count": 1
                },
                {
                  "key": "fake2",
                  "doc_count": 1
                },
                {
                  "key": "fake3",
                  "doc_count": 1
                }
              ]
            },
            "key": "brand",
            "doc_count": 3
          },
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "candy",
                  "doc_count": 1
                },
                {
                  "key": "shoes",
                  "doc_count": 1
                },
                {
                  "key": "t-shirts",
                  "doc_count": 1
                }
              ]
            },
            "key": "category",
            "doc_count": 3
          }
        ]
      },
      "doc_count": 6
    },
    "doc_count": 3
  }
}
```
```
{
  "1": {
    "2": {
      "3": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "fake1",
                  "doc_count": 1
                },
                {
                  "key": "fake2",
                  "doc_count": 1
                },
                {
                  "key": "fake3",
                  "doc_count": 1
                }
              ]
            },
            "key": "brand1",
            "doc_count": 3
          },
          {
            "4": {
              "doc_count_error_upper_bound": 0,
              "sum_other_doc_count": 0,
              "buckets": [
                {
                  "key": "candy",
                  "doc_count": 1
                },
                {
                  "key": "shoes",
                  "doc_count": 1
                },
                {
                  "key": "t-shirts",
                  "doc_count": 1
                }
              ]
            },
            "key": "category1",
            "doc_count": 3
          }
        ]
      },
      "doc_count": 6
    },
    "doc_count": 3
  }
}
```

I'm not sure if this is a bug or a changed feature, but I wanna understand why this behavior is different with ES 6.1.x.

### PR DESCRIPTION
**Pull request by martijnvg**
Add a method that is invoked before the `getLeafCollector(...)` of children aggregators is invoked.

In the case of nested aggregator this allows it to push down buffered child docs down to children aggregator.
Before this was done as part of the `NestedAggregator#getLeafCollector(...)`, but by then the children aggregators
have already moved on to the next segment and this causes incorrect results to be produced.

Closes #27912

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/nested/NestedAggregator.java [hunk 1]
```diff
@@ -102,11 +102,15 @@ public void collect(int parentDoc, long bucket) throws IOException {
...
             };
         } else {
-            doPostCollection();
             return bufferingNestedLeafBucketCollector = new BufferingNestedLeafBucketCollector(sub, parentDocs, childDocs);
         }
     }
 
+    @Override
+    protected void preGetChildLeafCollectors() throws IOException {
+        doPostCollection();
```
Comment (colings86) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/nested/NestedAggregator.java]: nit: It seems weird to call `doPostCollection()` during collection. Maybe we should have a separate method that both call?

**Review by colings86 — APPROVED** [review]
I left two minor comments but LGTM

**Comment by IdanWo** [comment]
This bug was is relevant to all ElasticSearch versions?
