### PR TITLE
Fix ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes

### LINKED ISSUE #60262: [CI] Failure in ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes
This failed yesterday on `master` in https://gradle-enterprise.elastic.co/s/xzsmn2fpzfvfq/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testMasterFailOverWithQueuedDeletes#1

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes" -Dtests.seed=8A6CB23CE2AB701E -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=Africa/Maputo -Druntime.java=11
```

failed with

```
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes" -Dtests.seed=8A6CB23CE2AB701E -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=Africa/Maputo -Druntime.java=11
  2> java.util.concurrent.ExecutionException: org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:35412][cluster:admin/snapshot/delete]
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:273)
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:260)
        at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:87)
        at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes(ConcurrentSnapshotsIT.java:471)

        Caused by:
        org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:35412][cluster:admin/snapshot/delete]

            Caused by:
            org.elasticsearch.repositories.RepositoryException: [_all] Failed to update cluster state during repository operation
                at org.elasticsearch.snapshots.SnapshotsService.failAllListenersOnMasterFailOver(SnapshotsService.java:1645)
                at org.elasticsearch.snapshots.SnapshotsService$4.onFailure(SnapshotsService.java:982)
                at org.elasticsearch.cluster.ClusterStateTaskListener.onNoLongerMaster(ClusterStateTaskListener.java:37)
                at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onNoLongerMaster(MasterService.java:519)
                at org.elasticsearch.cluster.service.MasterService$TaskInputs.lambda$onNoLongerMaster$0(MasterService.java:762)
                at java.util.ArrayList.forEach(ArrayList.java:1540)
                at org.elasticsearch.cluster.service.MasterService$TaskInputs.onNoLongerMaster(MasterService.java:762)
                at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:209)
                at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
                at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
                at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:647)
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.lang.Thread.run(Thread.java:834)

                Caused by:
                org.elasticsearch.cluster.NotMasterException: no longer master. source: [Run ready deletions]

    java.lang.IllegalStateException: Cannot cleanup [test-repo] - a snapshot is currently being deleted in [SnapshotDeletionsInProgress[[snapshot-two/Vxpgt46xTMy_3_nNvTN_jg, snapshot-three/4sKAbQTHSrmndqU9eWIZLQ, snapshot-one/A40QWDLnTcyKsVU1OD9jug]]]
        at org.elasticsearch.action.admin.cluster.repositories.cleanup.TransportCleanupRepositoryAction$2.execute(TransportCleanupRepositoryAction.java:183)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:647)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
```

... looking into it. Reproduces locally at a rate of ~1/1000

### PR DESCRIPTION
**Pull request by original-brownbear**
The test assumed that the master fail-over would always work out as a single step.
This is not guaranteed however and we can randomly see master failing over twice,
in which case the transport listener will be failed on the node that stops being
leader and we have to catch an exception for the deletes as well just like we do
for the snapshot.

Closes #60262

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java [hunk 1]
```diff
@@ -468,8 +469,15 @@ public void testMasterFailOverWithQueuedDeletes() throws Exception {
         unblockNode(repoName, dataNode);
         unblockNode(repoName, dataNode2);
 
-        assertAcked(firstDeleteFuture.get());
```
Comment (original-brownbear) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:471]: Most of the time these go through just fine because we retry the delete requests one node disconnect and then they get batched up with the already running deletes from the previous master and all is well.
But if we fail over twice then the second fail-over will resolve the listeners with exceptions (this is on purpose, we don't want to be retrying (hence the exception wrapping) in this case yet again because we then get a mix of snapshot not found exception successful execution depending on the timing).

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!
