### PR TITLE
Use status code 500 for errors if no shard failed

### LINKED ISSUE #20004: Search reduce failures map to 503 status code
[`SearchPhaseExecutionException#status()`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java#L87-L90) returns a `503 Unavailable` status code if there are no shard failures added to the exception:

```
        if (shardFailures.length == 0) {
            // if no successful shards, it means no active shards, so just return SERVICE_UNAVAILABLE
            return RestStatus.SERVICE_UNAVAILABLE;
        }
```

If an Exception is thrown in the reduce phase (e.g. from the reduce of an aggregation) this means that it will be given a 503 status code since if there were no failures returned from the shards. 

It looks like this is primarily caused by the fact that [`ReduceSearchPhaseException`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/ReduceSearchPhaseException.java) extends `SearchPhaseExecutionException` so maybe either we should override the `status()` method in `ReduceSearchPhaseException` or we should not have `ReduceSearchPhaseException` extend `SearchPhaseExecutionException`?

### PR DESCRIPTION
**Pull request by salvatore-campagna**
If there is no shard failure we would like to use a generic
Internal Server Error other than a Service Unavailable.
Moreover, if the cause is known we use a status code that
reflects the cause.

Resolves #20004

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/ReduceSearchPhaseException.java [hunk 1]
```diff
@@ -27,4 +29,21 @@ public ReduceSearchPhaseException(String phaseName, String msg, Throwable cause,
...
+    @Override
+    public RestStatus status() {
+        ShardSearchFailure[] shardFailures = getShardFailures();
+        if (shardFailures.length == 0) {
+            return getCause() == null ? RestStatus.INTERNAL_SERVER_ERROR : ExceptionsHelper.status(getCause());
+        }
+        RestStatus status = shardFailures[0].status();
+        if (shardFailures.length > 1) {
+            for (int i = 1; i < shardFailures.length; i++) {
+                if (shardFailures[i].status().getStatus() >= 500) {
```
Comment (csoulios) [inline server/src/main/java/org/elasticsearch/action/search/ReduceSearchPhaseException.java:42]: I am not a big fan of the hardcoded `500` value here. 
Is there any way to add a constant such as `RestStatus.INTERNAL_SERVER_ERROR.getStatus()`

Also, should you perhaps delegate this to the `RestStatus.status()` method?

Would running something like `RestStatus.status(0, shardFailures.length, shardFailures)` return the same result? Again, I am not an expert on this part of the code, so take this with a grain of salt.

**Review by csoulios — COMMENTED** [review]
Generally the code looks good. I have left a minor comment. 

However, I must admit I am not an expert on the related code. So @nik9000 or @not-napoleon could have a better opinion here.

File: docs/changelog/88551.yaml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+pr: 88551
+summary: "Fix: use status code 500 for errors if no shard failed"
```
Comment (not-napoleon) [inline docs/changelog/88551.yaml:2]:
```suggestion
summary: "Fix: use status code 500 for aggregation reduce phase errors if no shard failed"
```

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java [hunk 3]
```diff
@@ -161,4 +161,8 @@ public String toString() {
     public String getPhaseName() {
         return phaseName;
     }
+
+    public ShardSearchFailure[] getShardFailures() {
```
Comment (not-napoleon) [inline server/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java:165]: I think this could be package scoped?

**Review by not-napoleon — APPROVED** [review]
LGTM.  Left a couple of nits, but I think this is a fine approach.

File: server/src/main/java/org/elasticsearch/action/search/ReduceSearchPhaseException.java [hunk 4]
```diff
@@ -32,18 +32,10 @@ public ReduceSearchPhaseException(StreamInput in) throws IOException {
...
-        RestStatus status = shardFailures[0].status();
-        if (shardFailures.length > 1) {
-            for (int i = 1; i < shardFailures.length; i++) {
-                if (shardFailures[i].status().getStatus() >= RestStatus.INTERNAL_SERVER_ERROR.getStatus()) {
-                    status = shardFailures[i].status();
-                }
-            }
-        }
-        return status;
+        return super.status();
```
Comment (csoulios) [inline server/src/main/java/org/elasticsearch/action/search/ReduceSearchPhaseException.java:39]: That's much better :)

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java (hunk 3 above)
Comment (salvatore-campagna) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java]: It looks like there is already a method `shardFailures()` which I didn't see...so I will use the existing one and get rid of the one I added.

**Comment by javanna** [comment]
Heya, have we thought about the consequence in clients code around changing the status code here? I've seen this is marked bug hence it is not considered a breaking change, I assume. But was this discussed before merging?
