### PR TITLE
Reduce GCP fixture token fetch failures count

### LINKED ISSUE #140711: [CI] org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests.testIndicesDeletedFromRepository failing in tests
### CI Link

https://gradle-enterprise.elastic.co/s/npusic2lptbi2

### Repro line

```
REPRODUCE WITH: ./gradlew ":modules:repository-gcs:internalClusterTest" --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests.testIndicesDeletedFromRepository" -Dtests.seed=49D45231F074516C -Dtests.locale=de-IT -Dtests.timezone=Pacific/Apia -Druntime.java=25
```

### Does it reproduce?

Didn't try

### Applicable branches

https://github.com/elastic/elasticsearch/pull/140671 

### Failure history

_No response_

### Failure excerpt

```
org.elasticsearch.repositories.RepositoryVerificationException: [hitnu] [[IaEnbtnjQk-67WwaRKb6Lg, 'org.elasticsearch.transport.RemoteTransportException: [node_s5][127.0.0.1:28962][internal:admin/repository/verify]']]
```

### PR DESCRIPTION
**Pull request by mhl-b**
Fix https://github.com/elastic/elasticsearch/issues/140711

It appears that GCP Oauth2 client (we don't use one directly, it's wrapped in layers of GCS client) uses different retry settings than GCS. Also these settings are hardcoded: 1 second initial delay, 3 retries, 2x multiplier. Currently fixture will always throw 2-3 errors before pass, that adds 2.5-4 seconds wait time per node, and sometimes it's no perfectly parallel.
That means a single operation such as create repository with verification=true can run longer than 10 seconds and trip testing threshold.

This PR reduces number of retries to 1. Maybe we should make `createRepository(name)` by default without verification, there are plenty of tests exercising this path.

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java [hunk 1]
```diff
@@ -291,7 +291,7 @@ protected ErroneousHttpHandler(final HttpHandler delegate, final int maxErrorsPe
             this.requests = new ConcurrentHashMap<>();
             this.delegate = delegate;
             this.maxErrorsPerRequest = maxErrorsPerRequest;
-            assert maxErrorsPerRequest > 1;
+            assert maxErrorsPerRequest > 0;
```
Comment (ywangd) [inline test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java:294]: This change is irrelevant since we have at least one error injection? One could argue that using an `ErroneousHttpHandler` implies at least one error injection or we should not use it at all. So I prefer we keep it as is aslo because we don't need the change here.

**Review by ywangd — APPROVED** [review]
LGTM

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java (hunk 1 above)
Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java:294]: Without this change it's not possible to set error count to 1. I think it's relevant, this assertion tells that there must be at least one error, not two.

Comment (ywangd) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java:294]: Err my bad. What I had in mind is indeed that `maxErrorsPerRequest` should be greater than 0, i.e. at least 1, which is what you have done. Sorry for the noise.
