### PR TITLE
Fix metadata fields being nullified/loaded by unmapped_fields setting

### LINKED ISSUE #141907: ESQL: unmapped_fields="nullify"/"load" shouldn't nullify/load metadata, esp. _score
```sql
SET unmapped_fields=\"nullify\";
FROM employees
| LIMIT 1
| KEEP _score

    _score     
---------------
null
```

It doesn't make good sense to treat metadata the same way as regular fields, and therefore we also shouldn't nullify it. If a query has a `KEEP _id` and `_id` is missing, the user has to add `METADATA _id` to the `FROM`; nullifying this just hides a mistake.

Nullifying `_score` particularly just hides the fact that the query didn't actually perform any search.

### PR DESCRIPTION
**Pull request by quackaplop**
## Summary

Fixes #141907

When `SET unmapped_fields="nullify"` or `"load"` is used, metadata fields like `_score`, `_id`, `_index`, `_version`, etc. are incorrectly treated as regular unmapped fields. Instead of producing an error that guides the user to add `METADATA _score` to the `FROM` clause, the fields are silently resolved as `NULL` (nullify mode) or treated as unmapped keyword fields (load mode).

This is problematic because:
- It hides user mistakes — the user likely intended to use the metadata field but forgot `METADATA`
- In the case of `_score`, it obscures the fact that no search scoring was performed
- It violates the principle that metadata fields require explicit opt-in via the `METADATA` clause

### Root cause

`ResolveUnmapped.collectUnresolved()` collects all `UnresolvedAttribute`s in the plan and feeds them into the nullify/load logic. Since metadata fields that aren't declared in the `METADATA` clause remain unresolved after `ResolveRefs`, they get picked up and silently resolved by `ResolveUnmapped`.

### Fix

Added a check in `collectUnresolved()` to exclude attributes whose names match known metadata fields (`MetadataAttribute.isSupported()`). This lets them stay unresolved so the verifier produces the proper `Unknown column [_score]` error, guiding the user to declare `FROM ... METADATA _score`.

When metadata fields *are* declared via the `METADATA` clause, they get resolved during `ResolveRefs` and never appear as `UnresolvedAttribute`s — so the new filter has no effect on the happy path.

## Test plan

All tests iterate over every entry in `MetadataAttribute.ATTRIBUTES_MAP`, so new metadata fields are automatically covered.

**Failure tests** (both nullify and load modes):
- [x] KEEP — `FROM test | KEEP <field>`
- [x] EVAL — `FROM test | EVAL x = <field>`
- [x] WHERE — `FROM test | WHERE <field> IS NOT NULL`
- [x] SORT — `FROM test | SORT <field>`
- [x] STATS — `FROM test | STATS x = COUNT(<field>)`
- [x] RENAME — `FROM test | RENAME <field> AS renamed`

**Complex query shapes** (both modes):
- [x] After pipeline breaker — `FROM test | STATS c = COUNT(*) | KEEP _score`
- [x] Inside FORK branch — `FROM test | FORK (WHERE _score > 1) ...`
- [x] Inside subquery — `FROM (FROM test | WHERE _score > 1)`

**Happy path** (metadata declared via `METADATA` clause, full plan structure validated):
- [x] Nullify mode — `FROM test METADATA <field> | KEEP <field>`
- [x] Load mode — same

**Regression suites:**
- [x] `AnalyzerUnmappedTests` — all pass
- [x] `AnalyzerTests` — all pass

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java [hunk 1]
```diff
@@ -3303,6 +3305,106 @@ public void testRow() {
         assertThat(Expressions.name(row.fields().getFirst()), is("x"));
     }
 
+    public void testFailMetadataFieldInKeep() {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java:3308]: This is nice, I'd suggest a couple more complex query shapes though.

For nullify, we don't disallow FORK, LOOKUP JOIN, subqueries, etc.

I'd also suggest trying to refer to the missing metadata field _after_ (not inside) pipeline breakers.

**Review by alex-spies — APPROVED** [review]
Looks good. We can consider adding a yaml test before merging that confirms a correct error message outside of just unit tests. It's probably also fine without, though.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java (hunk 1 above)
Comment (quackaplop) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerUnmappedTests.java:3308]: Good idea. Added a few

**Review by alex-spies — APPROVED** [review]
LGTM. Thank you and feel free to :shipit: at your own discretion @quackaplop !

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/143373)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
