### PR TITLE
Clear watch schedules when starting trigger engine

### LINKED ISSUE #131964: [CI] FullClusterRestartIT testWatcherWithApiKey {cluster=UPGRADED} failing
**Build Scans:**
- [elasticsearch-periodic #9608 / 8.11.4_bwc](https://gradle-enterprise.elastic.co/s/puvilteeqxzaq)
- [elasticsearch-pull-request #82885 / 9.2.0_part_2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ed4qxotejkhf4)
- [elasticsearch-pull-request #82880 / 9.0.5_part_2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ciqixxyjr2dhc)
- [elasticsearch-pull-request #82680 / 8.18.5_part_2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/waii6huty7on2)
- [elasticsearch-pull-request #82680 / 9.0.5_part_2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/qqzm7mhnsvkbs)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:full-cluster-restart:v8.11.4#bwcTest" -Dtests.class="org.elasticsearch.xpack.restart.FullClusterRestartIT" -Dtests.method="testWatcherWithApiKey {cluster=UPGRADED}" -Dtests.seed=9E6B17A22C014C76 -Dtests.bwc=true -Dtests.locale=st-ZA -Dtests.timezone=America/Kentucky/Louisville -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.restart.FullClusterRestartIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testWatcherWithApiKey%20%7Bcluster%3DUPGRADED%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: version increased: [true], executed: [false]
Expected: is <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 5 failures in test testWatcherWithApiKey {cluster=UPGRADED} (0.5% fail rate in 925 executions)
- [main] 2 failures in step 9.0.5_part_2_bwc-snapshots (2.1% fail rate in 95 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (3.0% fail rate in 101 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #137562: Duplicate Watch Executions
### Elasticsearch Version

8.16.1

### Installed Plugins

Unknown

### Java Version

ECP

### OS Version

ECP

### Problem Description

It is possible that the same Watchers were getting triggered on multiple nodes simultaneously. This results in one execution succeeding while the other fails with a `version_conflict_engine_exception` error on the `.watches` index.

### Steps to Reproduce

Create a cluster with a large (6k+) number of watches, place cluster under load, add replicates for `.watches` shards, wait for `.watches` shards to re-locate a few times, observe concurrent write errors as watch executes on multiple nodes and fails to write state due to conflicts

### Logs (if relevant)

See mentioned issues

### PR DESCRIPTION
**Pull request by michalborek**
When new nodes appear in the cluster the watch may change the node it is running on. 
If we don't reset the schedules for a given node, there is a chance multiple nodes will execute the watch.

This could be observed in #131964 where some watcher actions were unexpectedly throttled (it happened that the same watch was run on two nodes and one of the execution was throttled.

Solving this problem uncovers another issue, related to watchers. When a watcher service is being **reloaded** (e.g. due to watcher allocation changes), and at the same time a new watcher is added, the `WatcherIndexingListener`  is directly modifying the `TickerScheduleTriggerEngine` and the trigger engine `start` method **reverts this operation**.

To fix that, the recently added watchers will be treated separately from the rest and will be re-added during the start operation even if the fresh watcher has not yet been searchable.

Closes #131964 
Closes #137562

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java [hunk 1]
```diff
@@ -53,6 +52,7 @@ public class TickerScheduleTriggerEngine extends ScheduleTriggerEngine {
 
     private final TimeValue tickInterval;
     private final Map<String, ActiveSchedule> schedules = new ConcurrentHashMap<>();
+    private final Map<String, ActiveSchedule> recentlyAddedSchedules = new ConcurrentHashMap<>();
```
Comment (masseyke) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java]: We don't need a ConcurrentHashMap here since this thing is only ever accessed inside of synchronized blocks, right? I don't think it hurts anything though.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java [hunk 2]
```diff
@@ -115,12 +111,14 @@ public void add(Watch watch) {
         // watcher indexing listener
         // this also means that updating an existing watch would not retrigger the schedule time, if it remains the same schedule
         if (currentSchedule == null || currentSchedule.schedule.equals(trigger.getSchedule()) == false) {
-            if (trigger.getSchedule() instanceof IntervalSchedule) {
-                schedules.put(watch.id(), new ActiveSchedule(watch.id(), trigger.getSchedule(), calculateLastStartTime(watch)));
-            } else {
-                schedules.put(watch.id(), new ActiveSchedule(watch.id(), trigger.getSchedule(), clock.millis()));
+            synchronized (this) {
```
Comment (masseyke) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java:116]: Some customers have hundreds of thousands of watches, so this might slow things down slightly, right? I am fairly certain that there is no way this can cause deadlock though. Adding `synchronized` always makes me nervous, so I'm just thinking through it.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java [hunk 3]
```diff
@@ -115,12 +111,14 @@ public void add(Watch watch) {
...
+                ActiveSchedule schedule = createSchedule(watch, trigger, clock.millis());
```
Comment (masseyke) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java]: This could be moved to before the synchronized block, right?

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java (hunk 2 above)
Comment (michalborek) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java:116]: It may be a bit dangerous not having it in my opinion. We may lose some events (depends on where the isRunning is placed in the start method (either before start or just after stop).

Is it crucial from perf perspective here? Not sure how much "add watch" is under stress.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java (hunk 3 above)
Comment (michalborek) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java]: Yes, true!

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java (hunk 1 above)
Comment (michalborek) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java]: Yeah, that's true. I'll change that but leave a comment - it's easy to overlook it when changing the implementation.

Comment (michalborek) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java]: Fixed in [15f6598](https://github.com/elastic/elasticsearch/pull/145325/commits/15f6598928d07805e7d1e96a1026a8112cd57f48)

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java (hunk 3 above)
Comment (michalborek) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java]: Fixed in [15f6598](https://github.com/elastic/elasticsearch/pull/145325/commits/15f6598928d07805e7d1e96a1026a8112cd57f48)

**Review by masseyke — APPROVED** [review]
I think this is a big improvement. I think there might be another incredibly unlikely race condition or two (for example, remove doesn't look in recentlyAddedSchedules, but that would only be an issue if you called remove and add quickly, and I think only while the engine was also pausing and restarting -- if you do all 4 of those things in rapid succession, you've got to expect some weirdness). But I think this fixes the ones we've seen in production and in tests.

**Comment by michalborek** [comment]
> I think this is a big improvement. I think there might be another incredibly unlikely race condition or two (for example, remove doesn't look in recentlyAddedSchedules, but that would only be an issue if you called remove and add quickly, and I think only while the engine was also pausing and restarting -- if you do all 4 of those things in rapid succession, you've got to expect some weirdness). But I think this fixes the ones we've seen in production and in tests.

Yes, I agree. The symmetric to this one would be removing a watch while a reload happens. To fix this we'd need to have something like `recentlyDeletedWatches`...
