### PR TITLE
ESQL: Fix synthetic attribute pruning

### LINKED ISSUE #105821: ESQL: ProjectAwayColumns rule not handling synthetic attribute correctly
The logical optimizer rules `PushdownEval`, `PushdownRegexExtract` and `PushdownEnrich` create temporary attributes when an `EVAL`, `GROK`/`DISSECT` or `ENRICH` is pushed past a `SORT` with conflicting names; e.g. `SORT x | EVAL x = y` essentially becomes `EVAL $$x = x, x = y | SORT $$x | DROP $$x`.

The temporary attribute `$$x` should be [synthetic](https://github.com/elastic/elasticsearch/blob/b4b32aa53a53975d1540dfc37c985729d622c6b6/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java#L946-L947), but currently that results in inconsistent physical plans as the rule [`ProjectAwayColumns` will wrongly eliminate this attribute](https://github.com/elastic/elasticsearch/blob/e568f7038daa8791f6f5db92e514cf9d8408418b/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java#L108-L111) from the execution plan.

### PR DESCRIPTION
**Pull request by alex-spies**
* Fix https://github.com/elastic/elasticsearch/issues/105821 and mark synthetically introduced Aliases as `synthetic` again.
* Simplify `ProjectAwayColumns`.
* Simplify `DependencyConsistency`.
* Make `AggregateExec` track the intermediate attributes it _actually_ outputs/requries.

ProjectAwayColumns is an optimization, run on the coordinator node, which determines which columns/attributes are required from the data nodes; unused columns/attributes are projected out by adding a new projection to the PhysicalPlan's Fragment, i.e. the logical plan sent to data nodes.

The current approach tries to find [all references](https://github.com/elastic/elasticsearch/blob/78003b8ff0f102f8d57b1ef13547a5911f49791a/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java#L102-L115) by traversing the plan nodes, and, roughly, assuming each NamedExpression (that's usually an Attribute or Alias) is going to be required to be provided by the current plan nodes's children - unless it's a NamedExpression that the current node generates itself. E.g. for `EVAL x = 2*field, y = x + 1`, the plan node references `field` and `x`, but `x` is generated in the same node, so what's required from the child plan node is actually just `field`.

However, this is brittle, as plan nodes can contain all kinds of NamedExpressions, and it is also very difficult to reason about this optimization rule's correctness. https://github.com/elastic/elasticsearch/pull/99188 added a workaround to synthetic attributes accidentally not being accounted for correctly, which prevented us from using synthetic attributes in many situations because synthetic attributes couldn't be sent from data to coordinator node anymore; however, this is required for union types and some push down optimization rules.

This PR fixes and simplifies `ProjectAwayColumns` by observing that determining the minimum set of columns to run a given logical plan node while still creating the same output can be computed from 3 sets:
1. the expected output (`QueryPlan.output()`)
2. the attributes generated by this plan node (subtract the children input from `output()`)
3. any references required for this node specifically, e.g. for `EVAL x = 2*field, y = x + 1` this is only `field`.

To obtain 3., this PR fixes `QueryPlan.references`, which used to just mechanically traverse all expressions of a plan node and look for any attributes it could find. Because 3. is also implicitly computed in `DependencyConsistency` to check whether a plan node's children provide all required attributes, this PR also simplifies `DependencyConsistency`.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java [hunk 1]
```diff
@@ -156,19 +111,22 @@ public PhysicalPlan apply(PhysicalPlan plan) {
...
+                                fragmentExec.estimatedRowSize(),
+                                fragmentExec.reducer()
                             );
+                            return new ExchangeExec(exec.source(), output, exec.isInBetweenAggs(), newChild);
                         }
                     }
+                } else {
+                    AttributeSet childOutput = currentPlanNode.inputSet();
+                    AttributeSet addedAttributes = currentPlanNode.outputSet().subtract(childOutput);
+                    requiredAttributes.set(requiredAttributes.get().subtract(addedAttributes).combine(currentPlanNode.requiredInputSet()));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java:127]: The main change; the way we collected all attributes that occurred and then removed generated attributes is fully abstracted away here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java [hunk 2]
```diff
@@ -89,62 +80,26 @@ static class ProjectAwayColumns extends Rule<PhysicalPlan, PhysicalPlan> {
...
-                if (keepCollecting.get()) {
-                    p.forEachExpression(NamedExpression.class, ne -> {
-                        var attr = ne.toAttribute();
-                        // filter out attributes declared as aliases before
-                        if (ne instanceof Alias as) {
-                            aliases.put(attr, as.child());
-                            attributes.remove(attr);
-                        } else {
-                            // skip synthetically added attributes (the ones from AVG), see LogicalPlanOptimizer.SubstituteSurrogates
-                            if (attr.synthetic() == false && aliases.containsKey(attr) == false) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java:111]: Synthetic attributes were skipped because we had to solve an NPE; IMHO this was not a correct long term fix, as it made heavy assumptions on where synthetic attributes are used.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/AggregateExec.java [hunk 3]
```diff
@@ -7,57 +7,60 @@
...
 import java.util.Objects;
 
 public class AggregateExec extends UnaryExec implements EstimatesRowSize {
     private final List<? extends Expression> groupings;
     private final List<? extends NamedExpression> aggregates;
+    /**
+     * The output attributes of {@link AggregatorMode#INITIAL} aggregations, resp.
+     * the input attributes of {@link AggregatorMode#FINAL} aggregations.
+     */
+    private final List<Attribute> intermediateAttributes;
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/AggregateExec.java:29]: It looks like `AggregateExec` is only ever serialized when we use data node level reduction, which is currently barred behind a pragma and so cannot be used, so this change should be fine.

We may have to keep track on a more granular level, though: for physical optimizations to correctly respect attribute dependencies, we need to know which aggregates/groupings are responsible for which intermediate attributes.

**Note to self: double check serialization one more time before merging.**

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 4]
```diff
@@ -1197,12 +1197,23 @@ private Expression createIfDoesNotAlreadyExist(
...
         ) {
             // Generate new ID for the field and suffix it with the data type to maintain unique attribute names.
+            // NOTE: The name has to start with $$ to not break bwc with 8.15 - in that version, this is how we had to mark this as
+            // synthetic to work around a bug.
             String unionTypedFieldName = LogicalPlanOptimizer.rawTemporaryName(
                 fa.name(),
                 "converted_to",
                 resolvedField.getDataType().typeName()
             );
-            FieldAttribute unionFieldAttribute = new FieldAttribute(fa.source(), fa.parent(), unionTypedFieldName, resolvedField);
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1205]: Might be worth adding a variant of this constructor that also allows `synthetic`.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/plan/QueryPlan.java [hunk 5]
```diff
@@ -35,6 +35,11 @@ public QueryPlan(Source source, List<PlanType> children) {
 
     public abstract List<Attribute> output();
 
+    /**
+     * The attributes required to be in the {@link QueryPlan#inputSet()} for this plan to be valid.
+     */
+    public abstract AttributeSet requiredInputSet();
```
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/plan/QueryPlan.java:41]: I struggle with this name. Maybe it's just me :-).

**Review by astefan — COMMENTED** [review]
I think this is ok imo. I am curious to see how this preliminary step will help with synthetic attributes usage in other places (mainly union types).

**Comment by alex-spies** [comment]
> I think this is ok imo. I am curious to see how this preliminary step will help with synthetic attributes usage in other places (mainly union types).

I turned attributes synthetic that were meant to be synthetic in [this commit](https://github.com/elastic/elasticsearch/pull/111413/commits/96951907c620404ff3c24547745bf264e9d169aa).

For union types specifically, we turn each expression like `TO_STRING(multi_typed_field)` into a synthetic field attribute `$$multi_typed_field$converted_to$keyword`. This was previously impossible, because they would get projected away before reaching the coordinator node, which is required e.g. to compute the top n over `TO_STRING(multi_typed_field)`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Drop.java [hunk 6]
```diff
@@ -27,6 +28,11 @@ public List<NamedExpression> removals() {
         return removals;
     }
 
+    @Override
+    public AttributeSet requiredInputSet() {
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Drop.java:43]: True. `Drop` essentially is not a real logical plan node, it's an AST node. The same is true for `Lookup` and `Keep`.

We can have this throw `UnsupportedOperationException` instead; although I think returning `references()` is correct, too; this contains the `UnresolvedAttribute`s that this is trying to drop, excluding any wildcards.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 7]
```diff
@@ -1205,8 +1195,16 @@ private MultiTypeEsField resolvedMultiTypeEsField(FieldAttribute fa, HashMap<Typ
...
-            NameId id = ((FieldAttribute) convert.field()).id();
-            FieldAttribute resolvedAttr = new FieldAttribute(source, null, field.getName(), field, Nullability.TRUE, id, false);
+            FieldAttribute originalFieldAttr = (FieldAttribute) convert.field();
+            FieldAttribute resolvedAttr = new FieldAttribute(
+                source,
+                originalFieldAttr.parent(),
+                originalFieldAttr.name(),
+                field,
+                originalFieldAttr.nullable(),
+                originalFieldAttr.id(),
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1205]: Carrying over more info from the original field attribute is technically unrelated; this seemed more correct, though, as the field attribute created here can lose the parent, the full name in case of subfields, and nullability info - which could serve as excellent red herrings in case someone runs across this while debugging in the future.

**Comment by alex-spies** [comment]
Discussed offline with @costin about the difference between `QueryPlan.references()` and `QueryPlan.childrenReferences()`. We concluded that `childrenReferences` does what `references` was supposed to do, and that there shouldn't be 2 `*references` methods to avoid confusion.

I'll find out how much the scope will grow by trying to replace the (current) `references` by (this PR's) `childrenReferences`.

**Comment by alex-spies** [comment]
- Ok, it looks like we do not actually use `QueryPlan.references` - with its current implementation - as much; I'll extract the couple uses where `childrenReferences` (formerly: `requiredInputSet`) cannot replace `references`; then I'll replace the implementation of `references` by the implementation of `childrenReferences`, so there's only 1 way of determining a plans required inputs.
- @costin suggested not to change `AggregateExec` in this PR. I tried that, but for `ProjectAwayColumns` to work properly, `AggregateExec` has to correctly declare its required children attributes; otherwise we get failures, resp. require workarounds, in cases when an aggregation has to completely be done on the coordinator node. Rather than implementing workarounds, I'd rather change `AggregateExec` and bump the transport version.
- I also considered not bumping the transport version because `AggregateExec` is only used for node level reduction, and that's currently turned off. However, I think without bumping transport version, we could end up in a little bwc hell if we turn on node level reduction at some point, because then we'll be sending new `AggregateExec`s to older nodes.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Aggregate.java [hunk 8]
```diff
@@ -132,11 +133,24 @@ public boolean expressionsResolved() {
...
+    }
+
+    @Override
+    protected AttributeSet computeReferences() {
+        return requiredInputAttributes(aggregates, groupings);
+    }
+
+    public static AttributeSet requiredInputAttributes(List<? extends NamedExpression> aggregates, List<? extends Expression> groupings) {
+        return Expressions.references(groupings).combine(Expressions.references(aggregates));
+    }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Aggregate.java:152]: Are there any consumer of these methods? I'm not a fan of these cookie cutter method which in practice are one liners.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java [hunk 9]
```diff
@@ -69,6 +71,16 @@ public List<Attribute> output() {
...
 
+    @Override
+    protected AttributeSet computeReferences() {
+        return requiredAttributesFromChild(fields);
+    }
+
+    public static AttributeSet requiredAttributesFromChild(List<Alias> fields) {
+        AttributeSet generated = new AttributeSet(asAttributes(fields));
+        return Expressions.references(fields).subtract(generated);
+    }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java:82]: Same remark - is this used elsewhere externally?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java
Comment (costin) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java:1]: Nit - this looks like a noise and a step backwards.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java [hunk 10]
```diff
@@ -144,9 +148,8 @@
 import static org.elasticsearch.xpack.esql.core.type.DataType.GEO_POINT;
 import static org.elasticsearch.xpack.esql.parser.ExpressionBuilder.MAX_EXPRESSION_DEPTH;
 import static org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.MAX_QUERY_DEPTH;
-import static org.elasticsearch.xpack.esql.plan.physical.AggregateExec.Mode.FINAL;
-import static org.elasticsearch.xpack.esql.plan.physical.AggregateExec.Mode.PARTIAL;
```
Comment (costin) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java:148]: You might want to check your IDE settings - there's no reason to remove this static imports; it just creates a bunch of noise for no good reason.

**Review by costin — CHANGES_REQUESTED** [review]
Looks pretty good - thanks for incorporating the feedback and left another round.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/QueryPlan.java [hunk 11]
```diff
@@ -66,15 +65,22 @@ public List<Expression> expressions() {
...
      */
     public AttributeSet references() {
         if (lazyReferences == null) {
-            lazyReferences = Expressions.references(expressions());
+            lazyReferences = computeReferences();
         }
         return lazyReferences;
     }
 
+    protected abstract AttributeSet computeReferences();
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/QueryPlan.java:82]: I would actually prefer not to give this a default implementation.

As long as we add new commands, I'd prefer each plan node to be forced to explicitly declare what it requires from its children. This is more verbose, but consistent with `output()` - and the fact that `references` _had_ the mentioned default implementation led to many plan nodes having wrong implementations, and we built a bunch of workarounds to account for that.

Case in point: when the `Join` node was first added, its `references` implementation was wrong and needed fixing, but this was not immediately apparent at all.

Let me know how you'd like us to proceed. I'm fine with either way, but wanted to lay out my reasoning first.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Aggregate.java (hunk 8 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Aggregate.java:152]: This is re-used in `AggregateExec`; to avoid it from accidentally diverging from `Aggregate`, I factored this out into a helper method.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java (hunk 9 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java:82]: Yup, in `EvalExec`!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java (hunk 10 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java:148]: I'll reduce the noise via static imports. Do note that this change is not artificial, though; `AggregateExec` now uses the `AggregatorMode` enum instead of its own `AggregateExec.Mode`, so we can represent `Intermediate` aggregations as well, and the two enums don't diverge anymore.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java [hunk 12]
```diff
@@ -89,62 +80,26 @@ static class ProjectAwayColumns extends Rule<PhysicalPlan, PhysicalPlan> {
...
         @Override
         public PhysicalPlan apply(PhysicalPlan plan) {
-            var projectAll = new Holder<>(TRUE);
-            var keepCollecting = new Holder<>(TRUE);
-            var attributes = new AttributeSet();
-            var aliases = new AttributeMap<Expression>();
+            Holder<Boolean> keepTraversing = new Holder<>(TRUE);
+            // Invariant: if we add a projection with these attributes after the current plan node, the plan remains valid
+            // and the overall output will not change.
+            Holder<AttributeSet> requiredAttributes = new Holder<>(plan.outputSet());
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizer.java:86]: I need the holder because I need to re-assign the `requiredAttributes` after doing some non-mutating set operations like `subtract` and `combine`. Getting rid of the Holder would work if I only needed to mutate.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java [hunk 13]
```diff
@@ -123,7 +123,7 @@ public boolean equals(Object obj) {
 
     @Override
     public String toString() {
-        return name() + "{" + label() + "}" + "#" + id();
+        return name() + "{" + label() + (synthetic() ? ":s" : "") + "}" + "#" + id();
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Attribute.java:126]: Hm, that may be slightly more cryptic to people not used to seeing query plans so often - but `:s` is probably similarly cryptic. I'll change it.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java [hunk 14]
```diff
@@ -30,8 +30,7 @@
  * - nestedParent - if nested, what's the parent (which might not be the immediate one)
  */
 public class FieldAttribute extends TypedAttribute {
-    // TODO: This constant should not be used if possible; use .synthetic()
-    // https://github.com/elastic/elasticsearch/issues/105821
+    @Deprecated()
     public static final String SYNTHETIC_ATTRIBUTE_NAME_PREFIX = "$$";
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:34]: Moving this into `Attribute`, together with `rawTemporaryName`.

[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:34]: (And making it `protected static`, so it doesn't leak outside)

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java [hunk 15]
```diff
@@ -64,6 +65,8 @@ public FieldAttribute(
         this(source, parent, name, field.getDataType(), field, nullability, id, synthetic);
     }
 
+    // TODO: Should this become private? An explicitly set type will be discarded the moment this is `clone`d, so using this constructor is
```
Comment (astefan) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:68]: Agree. You could make this package protected (not `protected`), create a `FieldAttributeTestUtils` class in the `test` module but same package as `FieldAttribute` where a `static` `final` method can call this constructor. Also, adding a comment saying it's for testing purposes only.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java [hunk 16]
```diff
@@ -98,16 +95,6 @@ public String unresolvedMessage() {
         return unresolvedMsg;
     }
 
-    @Override
-    public AttributeSet references() {
-        AttributeSet refs = super.references();
-        if (indexMode == IndexMode.TIME_SERIES) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java:104]: Why did you make the move to EsqlSession? Was the `fieldNames` the only place where metrics specific metadata attributes were needed?

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java (hunk 15 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:68]: I'll also make `withDataType` throw an error, as that deceptively does nothing.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java (hunk 16 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java:104]: I think `fieldNames` is the only place where we would somehow call `UnresolvedRelation.references()` and do something with the output in case of time series indices; after the first analysis steps, there's not supposed to be any `UnresolvedRelation`s anymore.

Removing this code altogether makes the tests in `k8s-metrics` fail, whereas it currently runs green; also, the only place in the whole (non-test) code base where `IndexMode.TIME_SERIES` is set on an `UnresolvedRelation` is `LogicalPlanBuilder.visitMetricsCommand`.

I'll double-check if moving this code to `EsqlSession.fieldNames` is the best course of action; if so, I'll add a test case to `IndexResovlerFieldNamesTests`.

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java:104]: Ok, it seems like it's reasonable to have a special case for `METRICS` in `EsqlSession.fieldNames`. I added a test.

I also added a comment and made this look for `Aggregate` of `Metrics` type rather than looking for unresolved relations with timeseries mode. It's the `Aggregate` that needs to consume the `@timestamp` field if it's in `Metrics` mode, which I think is easier to grasp than "that's an unresolved time series, so probably we need the `@timestamp` field somewhere".

**Comment by alex-spies** [comment]
Ok, this should be ready to go now.

@costin would you like to take another look?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 17]
```diff
@@ -302,9 +300,9 @@ static Set<String> fieldNames(LogicalPlan parsed, Set<String> enrichPolicyMatchF
                 references.addAll(enrichRefs);
             } else {
                 references.addAll(p.references());
-                // TODO: Is this still needed? This branch used to live in UnresolvedRelation.references().
-                if (p instanceof UnresolvedRelation ur && ur.indexMode() == IndexMode.TIME_SERIES) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java]: index_mode time_series I think is more general and more appropriate for `metrics` command. I wouldn't change this to look at the aggregation type instead. My 2c (I am not very familiar with `metrics` but `index_mode == time_series` is something that's being discussed and it's a thing :-); see [this page from docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds-index-settings.html)).

**Review by astefan — APPROVED** [review]
LGTM with a final remark regarding `metrics` usage in `EsqlSession`.
Thanks @alex-spies

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java (hunk 17 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java]: Changed it back to rely on the index mode, as it was before (but left it inside fieldnames).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/QueryPlan.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/QueryPlan.java:82]: tl;dr - I've read your arguments however I'd prefer to use a default implementations, similar to inputSet, etc...

references and output are different.
The input of each set is well determined - the output set of its children. The same patter makes sense for references(), expressions() etc.. Not so with the output since each input had its own particularities.

As you point out, the issue was a bug in the default implementation - better to fix that in one place instead of having multiple places that do the same thing and potentially replicate the bug.

At the end of the day, it's an arbitrary choice. The style of the code-base is trustful towards the author, that is non-defensive: (for example collections are not copied for input/returns by default), method calls don't perform null checks for every params, etc...

Hence why I opt towards a default implementation that is useful and guiding - adding a new command requires the author to know what they're doing to begin with so I'd use this mindset, at least at this stage of the project.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java (hunk 9 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java:82]: Any reason why the methods across Eval and Aggregate don't have the same name?  Something like doComputeReferences() or determineReferences(), etc... required is a misnomer in this context.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java (hunk 16 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/UnresolvedRelation.java:104]: Better to create an issue for this - adding a separate node (or extending Aggregate) is a more elegant way for evolving this requirement.

**Review by costin — APPROVED** [review]
Left a few comments, LGTM otherwise.

**Review by costin — APPROVED** [review]
Left a few comments, LGTM otherwise.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java (hunk 9 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Eval.java:82]: I'll just overload `computeReferences` (and `output` for `Aggregate`), that should be nice and consistent.

**Comment by alex-spies** [comment]
Thanks for your reviews @astefan and @costin !
