### PR TITLE
Health monitor concurrency fixes

### LINKED ISSUE #105065: Avoid race in `LocalHealthMonitor` w.r.t `null` values
Follow up on [this](https://github.com/elastic/elasticsearch/pull/104614#discussion_r1475667009) thread.

There is a race condition in the `LocalHealthMonitor` regarding `null` values (i.e. initial/reset values):
- Last reported value was null
- there is new a health node
- New run starts the update process and records previous value null
- health node/master change
- new reported value is null
- Run sees null and considers that it's ok to update the value....

Can probably relatively easily be fixed by using some form of ref counting/versioning of the `lastReportedValue`.

### PR DESCRIPTION
**Pull request by nielsbauman**
Update the implementation of the `LocalHealthMonitor` to ensure there is always only 1 `UpdateHealthInfoCacheAction` request in-flight, and that only 1 monitoring thread can update the "internal state" (i.e. the `lastReportedValue` in the `HealthTracker`s) at the same time. By enforcing this, we're avoiding potential concurrency issues. This PR also includes several tests that aim to validate the behaviour of the `LocalHealthMonitor` in specific multi-threaded situations.

Resolves #105065

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java [hunk 1]
```diff
@@ -241,8 +255,135 @@ public void testEnablingAndDisabling() throws Exception {
...
+
+        assertBusy(() -> assertTrue(updatedHealthNodes.contains(lastHealthNode)));
+    }
+
+    private ClusterState mutateState(ClusterState previous) {
+        var masterNode = previous.nodes().getMasterNode();
+        var healthNode = HealthNode.findHealthNode(previous);
+        switch (randomInt(1)) {
+            case 0 -> masterNode = randomValueOtherThan(masterNode, () -> randomFrom(node, frozenNode));
+            case 1 -> healthNode = randomValueOtherThan(healthNode, () -> randomFrom(node, frozenNode));
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java:343]: Should we have a few more nodes to rotate/combine here? 5 perhaps? (so we get a new health/master combo more often?)

**Review by andreidan — APPROVED** [review]
Great work on this Niels! 🚀 

Left a minor testing thing, but this LGTM

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java [hunk 2]
```diff
@@ -320,34 +333,46 @@ public void run() {
...
-                    if (Objects.equals(healthNodeId, lastSeenHealthNode.get()) == false) {
-                        return;
+                    // Only record health progress if this monitoring instance hasn't been cancelled in the meantime.
+                    // This avoids any unwanted writes to the HealthTrackers' states after a new monitoring instance has possibly
+                    // already started.
+                    if (cancelled == false) {
+                        healthProgresses.forEach(HealthTracker.HealthProgress::recordProgressIfRelevant);
                     }
-                    healthProgresses.forEach(HealthTracker.HealthProgress::recordProgressIfRelevant);
+                    inFlightRequest.set(false);
```
Comment (gmarouli) [inline server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:361]: Can we combine this along with the `scheduleNextRun.run()`? It looks like they should be triggered at the same time, when the current run completes. Right?

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:361]: And rename it accordingly, of course.

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:361]: Hmm I don't think that will work because of this part:

https://github.com/elastic/elasticsearch/blob/6f34bb10660bb52774e7c05493f2bb3c362fd642/server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java#L338-L342

In that case, we don't want the `scheduleNextRun` to set the `inFlightRequest` to false, because we actually know for sure another thread has just sent a request. I do like the idea of moving the `inFlightRequest.set(false)` to one place so it's a bit easier to read/understand, but I can't really come up with a way that would work well. I could have two different `Runnable`s, the `scheduleNextRun` and one that wraps that one with the `.set(false)` statement, but I don't think that would make things a lot more readable tbh. What do you think?

File: server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java (hunk 1 above)
Comment (nielsbauman) [reply server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java]: See [4d8c947](https://github.com/elastic/elasticsearch/pull/105674/commits/4d8c947278bac2396b7a395adc7b86f00482416c).

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java (hunk 2 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:361]: Hm, I see your point. We could consider keeping this as an exception maybe. Since it's out of the try, and use a runnable that will contain both statements on the rest of the code. Would that benefit us at all?

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:361]: I think from a stylistic POV that would indeed be better. But there's one more execution path that I'm not entirely sure about. Would it be possible for the `client.execute(...)` invocation to throw an exception _after_ it has actually sent the request (and will execute the listener after the request completes). In other words, would it be possible that we end up in the `catch` block but that the `listener` will be executed afterward?

Your proposed refactoring doesn't impact this, I think, but I only realized this after implementing your proposal.

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java [hunk 3]
```diff
@@ -236,28 +249,28 @@ static class Monitoring implements Runnable, Scheduler.Cancellable {
         private final ClusterService clusterService;
         private final Client client;
 
-        private final AtomicReference<String> lastSeenHealthNode;
         private final List<HealthTracker<?>> healthTrackers;
 
+        private final AtomicReference<Boolean> inFlightRequest;
```
Comment (parkertimmins) [inline server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:254]: This is a stylistic question (at least I think it is). Any reason to use AtomicReference<Boolean> rather than AtomicBoolean? My understanding is that compareAndSet will use reference equality, which is fine here, since auto-boxed booleans objects will have == and .equals that behave the same. But auto-boxing in general is a bit confusing, so if it's possible to use AtomicBoolean, that seems a bit clearer.

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:254]: Good catch! Was indeed not intentional, so will update 👍🏻.

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java (hunk 2 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:362]: Let's dive into this. We will investigate 3 scenarios:
- `client.execute` succeeds in making a request
- `client.execute` is called but throws an exception (if possible)
- There is an exception before `client.execute` is called. 

Before we start, the catch block is not as relevant here, right? The `scheduleNextRun.run()` is being executed in the `finally` block. However, when an exception is thrown is important because it affects the value of the `nextRunScheduled` boolean flag which determines if the finally block will schedule the next run or not.

**Scenario 1**
If the `client.execute` succeeds then the `nextRunScheduled = true` will also succeed so the `scheduleNextRun.run()` will be executed only by the listener.
```
try {
    .......
    client.execute(UpdateHealthInfoCacheAction.INSTANCE, builder.build(), ActionListener.runAfter(listener, scheduleNextRun));
     nextRunScheduled = true;
} catch (Exception e) {
     logger.warn(() -> format("Failed to run scheduled health monitoring on thread pool [%s]", executor), e);
} finally {
      // If the next run isn't scheduled because for example the health info hasn't changed, we schedule it here.
      if (nextRunScheduled == false) {
            scheduleNextRun.run();
       }
}
```

Scenario 2
If the `client.execute` fails then the `nextRunScheduled` will be `false` meaning the `finally` block will be the one triggering the `scheduleNextRun.run()`. So, here, we will investigate if it's possible that listener will also be called. As you see there is a try-catch here that will delegate any failure to the listener, in this case the `client.execute` will not itself fail. Theoretically, we are safe. 
```
       try {
            doExecute(action, request, listener);
        } catch (Exception e) {
            assert false : new AssertionError(e);
            listener.onFailure(e);
        }
```

Scenario 3
If we fail anywhere before `client.execute` is called then the `nextRunScheduled` will be false and the finally block will save the day.

If in any case there is double invocation, we have wrapped the runnable with `RunOnce` which will protect us from a double invocation. 

Is this clear?

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:362]: Ahh right I forgot about the `RunOnce` part 😅. But besides that, your theory definitely makes sense, so thanks a lot for the elaborate explanation!

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:362]: Happy to! Keep asking these questions!!! It gives us the opportunity to see if we missed something!

File: server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java [hunk 4]
```diff
@@ -287,6 +281,49 @@ public void testResetDuringInFlightRequest() throws Exception {
...
+            ActionListener<AcknowledgedResponse> listener = invocation.getArgument(2);
+            listener.onResponse(null);
+            return null;
+        }).when(client).execute(any(), any(), any());
+
+        localHealthMonitor.setMonitorInterval(TimeValue.timeValueMillis(10));
+        // Run in a new thread because the `threadPool.schedule(...)` invocation will hang (as defined above).
+        new Thread(() -> localHealthMonitor.clusterChanged(new ClusterChangedEvent("start-up", initialState, ClusterState.EMPTY_STATE)))
+            .start();
+        assertBusy(() -> assertThat(counter.get(), greaterThanOrEqualTo(2)));
```
Comment (gmarouli) [inline server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java:317]: I don't fully get this assertion. I think I am missing something here.

If I understand correctly on line 315-316 we set the write conditions to start the monitoring. The monitoring will block on the first time it's trying to start because `currentCount` will be 1. Where is the second call to the `threadpool.schedule` coming from?

Comment (nielsbauman) [reply server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java:317]: That's coming from `Monitoring#scheduleNextRunIfNecessary`:https://github.com/elastic/elasticsearch/blob/f35caa2554b7e7e4608dc69bf1f8380a38bf662c/server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java#L398-L398

And for clarification, the monitoring doesn't exactly "block". When we call `threadPool.schedule(...)` here https://github.com/elastic/elasticsearch/blob/f35caa2554b7e7e4608dc69bf1f8380a38bf662c/server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java#L282-L282
We do actually execute `Monitoring#run`, as per https://github.com/elastic/elasticsearch/blob/f35caa2554b7e7e4608dc69bf1f8380a38bf662c/server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java#L297-L297
but we don't _return_ yet (i.e. we block before we return). That means the monitoring will be started, but `scheduledRun` will not be assigned yet because `threadPool.schedule(...)` hasn't returned yet.

Does that make things more clear? Do you have suggestions for comments/restructuring that would make this easier to read?

Comment (gmarouli) [reply server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java:317]: Hm, I see. So, let's walk us through this:

1) We start the monitoring, which will schedule the run but it will not return so the `scheduledRun` will not be assigned.
https://github.com/elastic/elasticsearch/blob/f35caa2554b7e7e4608dc69bf1f8380a38bf662c/server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java#L281-L283

2) The monitoring will `run` and will try to schedule the next run. This will succeed because we only apply the disruption on the first execution.
https://github.com/elastic/elasticsearch/blob/f35caa2554b7e7e4608dc69bf1f8380a38bf662c/server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java#L326

3) When we cancel the Monitoring:
https://github.com/elastic/elasticsearch/blob/f35caa2554b7e7e4608dc69bf1f8380a38bf662c/server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java#L317-L318
At this moment the `scheduledRun` actually has been set with the second scheduled job, based on my understanding. So, we are not actually cancelling the first run.

So, I think this test is testing something else. What if we changed it slightly:

1) We actually block before the execution, so we do not return and we do not run until we are sure that the cancel signal has been sent.
2) When the cancel signal has been sent, we unblock, we run and we verify that there shouldn't be any request to the health node since this has been already cancelled.

I think the above is capturing an early cancellation better. What do you think?

Comment (nielsbauman) [reply server/src/test/java/org/elasticsearch/health/node/LocalHealthMonitorTests.java]: As discussed with Andrei, I'm removing this test :). Thanks for the feedback anyway!

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java [hunk 5]
```diff
@@ -330,28 +344,33 @@ public void run() {
...
+                );
                 nextRunScheduled = true;
             } catch (Exception e) {
                 logger.warn(() -> format("Failed to run scheduled health monitoring on thread pool [%s]", executor), e);
+                // Make sure to release the "lock" in case something goes wrong, so we can try again in the next iteration.
             } finally {
                 // If the next run isn't scheduled because for example the health info hasn't changed, we schedule it here.
                 if (nextRunScheduled == false) {
-                    scheduleNextRun.run();
+                    releaseAndScheduleNextRun.run();
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:373]: I don't think this is correct here. 

This finally block might run **before** our action listener https://github.com/elastic/elasticsearch/pull/105674/files#diff-ec8692646c2c3b00102070f6daff810ef1e176024d23206287684849dd17ace2R364

IIUC it will then set `inFlight` to `false`. 

I don't think juggling `runAfter` and `RunOnce` helps readability either but perhaps that's a personal preference.

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:373]: When `finally` block runs, given there is no exception, `nextRunScheduled` would have been set to `true` so it will skip running the `releaseAndScheduleNextRun`. 

Does this address your concern?

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:373]: Ah yes! Thanks Mary, that makes sense.

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java [hunk 6]
```diff
@@ -330,28 +344,33 @@ public void run() {
...
-                client.execute(UpdateHealthInfoCacheAction.INSTANCE, builder.build(), ActionListener.runAfter(listener, scheduleNextRun));
+                client.execute(
+                    UpdateHealthInfoCacheAction.INSTANCE,
+                    builder.build(),
+                    ActionListener.runAfter(listener, releaseAndScheduleNextRun)
+                );
                 nextRunScheduled = true;
             } catch (Exception e) {
                 logger.warn(() -> format("Failed to run scheduled health monitoring on thread pool [%s]", executor), e);
+                // Make sure to release the "lock" in case something goes wrong, so we can try again in the next iteration.
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java:369]: This comment is obsolete here?

**Review by andreidan — APPROVED** [review]
Thanks for iterating on this Niels, LGTM

File: server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java (hunk 6 above)
Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/health/node/LocalHealthMonitor.java]: Good catch, thanks!
