### PR TITLE
SQL: Verifier allows aliases aggregates for sorting

### LINKED ISSUE #34607: SQL: Resolution of aliased field in ORDER BY fails even if declared in projection
The following query:
`SELECT foo f FROM x GROUP BY foo ORDER BY f`
fails with:
`Cannot order by non-grouped column [f], expected (foo)`

The analyzer should be improved to read the aliases inside an `Aggregate` projections not just grouping.

### PR DESCRIPTION
**Pull request by costin**
Improve Verifier rule that prevented grouping, aliases inside aggregates
to not be accepted for ordering.

Close #34607

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java [hunk 1]
```diff
@@ -110,6 +118,11 @@ public void testGroupByOrderByNonGrouped() {
                 verify("SELECT MAX(int) FROM test GROUP BY text ORDER BY bool"));
     }
 
+    public void testGroupByOrderByAliasedInSelectAllowed() {
+        LogicalPlan lp = accepted("SELECT text t FROM test GROUP BY text ORDER BY t");
```
Comment (matriv) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: You don't group by the alias `t` but you use `text`, was that the intention? Because here you use the alias: https://github.com/elastic/elasticsearch/pull/34773/files#diff-3d7c2dc164e7f948316c325f88c12a3fR39

**Review by matriv — APPROVED** [review]
LGTM. Left a comment.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: The verifier query is correct, the sql isn't (it's a typo). Fixing this in a follow-up commit.
