### PR TITLE
Choose postings format from FieldMapper instead of MappedFieldType

### LINKED ISSUE #77183: Warning messages logged when index_prefixes are configured in index mapping
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
For index that has `index_prefixes` configured in the mapping, so similar like this: 

```
"field" : {
          "type" : "text",
          "index_prefixes" : {
            "min_chars" : 1,
            "max_chars" : 17
          }
        },
```

we can see a number of warning events logged in Elasticsearch log. Events look like this: 
```
[index_name][10] no index mapper found for field: [field._index_prefix] returning default postings format
```

**Steps to reproduce**:

N/A

**Provide logs (if relevant)**:
N/A

### PR DESCRIPTION
**Pull request by romseygeek**
Currently we configure per-field postings formats by asking the MapperService
for the MappedFieldType of the field in question, and then checking to see if it
is a completion field.  If no MappedFieldType is available, we emit a warning.
However, MappedFieldTypes are for search fields only, and so we end up emitting
warnings for hidden sub-fields that have no corresponding field type, such as
prefix or phrase accelerator fields on text mappers.

This commit reworks things so that the MappingLookup is responsible for defining
per-field postings formats, and will detect CompletionFieldMappers at build time.
All fields that are not mapped to a completion field will just get the default postings
format. This also means that we no longer need a logger instance on CodecService.

Fixes #77183

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java [hunk 1]
```diff
@@ -313,6 +300,11 @@ public CompletionFieldType fieldType() {
         return (CompletionFieldType) super.fieldType();
     }
 
+    @Override
+    public PostingsFormat postingsFormat() {
+        return PostingsFormat.forName("Completion84");
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java:305]: Note: PostingsFormat.forName() does the same lazy-instantiation that the previous impl did

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by romseygeek** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 2]
```diff
@@ -383,6 +384,13 @@ protected void doXContentBody(XContentBuilder builder, Params params) throws IOE
         return indexAnalyzers;
     }
 
+    /**
+     * @return a PostingsFormat for this field, or {@code null} if the default postings should be used
+     */
+    public PostingsFormat postingsFormat() {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:390]: I don't think we should reopen this capability for plugins. It was removed in https://github.com/elastic/elasticsearch/issues/8746 and I don't think that the policy should change. 
Can we make this change without exposing custom postings format in field mappers ?

**Review by jimczi — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java (hunk 2 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: I've reworked things so that the MappingLookup detects completion mappers at build time and will return the relevant per-field postings format, removing the pluggability again.

**Review by jimczi — APPROVED** [review]
The change looks good thanks. Can you also modify the title of the PR to reflect the last changes.
