### PR TITLE
Wait until security index is ready for role mappings

### LINKED ISSUE #91939: File based settings work incorrectly for role mappings on startup
### Elasticsearch Version

8.6

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

This bug was discovered by @thbkrkr when testing the file based settings with node restarts. 

Essentially, we have two paths where we call processing on file based settings:
- On startup, we check if the file is there and we process it. In case we encounter an error we abort the startup and end the node.
- We watch the file for changes at runtime and apply it when it's modified. Encountering an error here is not fatal, we simply record the error in the cluster state and in the log.

The problem happens on startup when using role mappings. Role mappings are different than the rest of file based settings because we don't store them in the cluster state, instead, we store them in the security index. When we process the file based settings on start, there are no guarantees that the security index will be properly loaded, in fact it often isn't. This causes various issues, we can fail with an exception (misleading the user by saying the security index wasn't upgraded ) or sometimes it just silently fails which is what happened when @thbkrkr tested.

What we need to do here is wait on launching the file based settings processing until the `SecurityIndexManager` inside the `NativeRoleMappingStore` is available and the state is recovered. 

One caveat here is that if we wait, this will likely prevent us from terminating the node on bad startup configuration, unless we resort to throwing an `j.l.Error`, which will not be caught by the default exception handler.

### Steps to Reproduce

1. Enable security
2. Make a directory config/operator.
3. Make a sample settings file config/operator/settings.json with the following contents:
```
{
    "metadata": {
        "version": "1",
        "compatibility": "8.4.0"
    },
    "state": {
        "role_mappings": {
            "role_test": {
                "enabled": true,
                "metadata": {
                    "_foo": "something",
                    "uuid": "b9a59ba9-6b92-4be2-bb8d-02bb270cb3a7"
                },
                "roles": [
                    "kibana_user"
                ],
                "rules": {
                    "field": {
                        "username": "*"
                    }
                }
            }
        }
    }
}
```
4. Start Elasticsearch
5. The startup will fail with the following error:
```
Caused by: org.elasticsearch.reservedstate.service.FileSettingsService$FileSettingsStartupException: Error applying operator settings
	at org.elasticsearch.reservedstate.service.FileSettingsService.startWatcher(FileSettingsService.java:251) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.IllegalStateException: Error processing state change request for file_settings, errors: Security index is not on the current version - the native realm will not be operational until the upgrade API is run on the security index
	at org.elasticsearch.reservedstate.service.ReservedClusterStateService.checkAndReportError(ReservedClusterStateService.java:258) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.reservedstate.service.ReservedClusterStateService$1.onFailure(ReservedClusterStateService.java:238) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.reservedstate.service.ReservedClusterStateService$3.onFailure(ReservedClusterStateService.java:362) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.GroupedActionListener.onFailure(GroupedActionListener.java:72) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.security.action.rolemapping.ReservedRoleMappingAction$1.onFailure(ReservedRoleMappingAction.java:115) ~[?:?]
	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.GroupedActionListener.onFailure(GroupedActionListener.java:72) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore.modifyMapping(NativeRoleMappingStore.java:195) ~[?:?]
	at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore.putRoleMapping(NativeRoleMappingStore.java:178) ~[?:?]
	at org.elasticsearch.xpack.security.action.rolemapping.ReservedRoleMappingAction.nonStateTransform(ReservedRoleMappingAction.java:120) ~[?:?]
	at org.elasticsearch.xpack.security.action.rolemapping.ReservedRoleMappingAction.lambda$transform$1(ReservedRoleMappingAction.java:87) ~[?:?]
	at org.elasticsearch.reservedstate.service.ReservedClusterStateService.executeNonStateTransformationSteps(ReservedClusterStateService.java:370) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.reservedstate.service.ReservedClusterStateService.process(ReservedClusterStateService.java:196) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.reservedstate.service.FileSettingsService$1.onResponse(FileSettingsService.java:425) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.reservedstate.service.FileSettingsService$1.onResponse(FileSettingsService.java:419) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.client.internal.node.NodeClient$SafelyWrappedActionListener.onResponse(NodeClient.java:160) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:208) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:165) ~[?:?]
	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:245) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:455) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponseAsync(TransportNodesAction.java:180) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponse(TransportNodesAction.java:155) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.lambda$finishHim$1(TransportNodesAction.java:302) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:850) ~[elasticsearch-8.7.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by grcevski**
File based settings are always stored in the cluster state, except in one case - security role mappings. The role mappings are stored in the `.security` system index. While the cluster state is immediately available on bootstrap of the Node, the system indices might take a while to become available.

This PR changes the flow of updating the role mappings, such that we properly wait for the role mappings to be saved until the security index becomes available.

The code for the PR is pretty much what @ywangd provided me with :). Thanks Yang!

Outstanding item:
- [x] Add integration tests for behaviour of the role mappings saves across Node restarts. I can't do that just yet, we first need to merge https://github.com/elastic/elasticsearch/pull/92124, since we had a bug that reserved state wasn't considered in global state updates.

Closes https://github.com/elastic/elasticsearch/issues/91939

### CODE REVIEW

**Comment by grcevski** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by grcevski** [comment]
@ywangd I think this is now ready to be reviewed. Thanks again!

**Review by ywangd — COMMENTED** [review]
I have a question about the new test.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/FileSettingsRoleMappingsStartupIT.java [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+        Files.createDirectories(fileSettingsService.operatorSettingsDir());
+        Path tempFilePath = createTempFile();
+
+        logger.info("--> writing JSON config to node {} with path {}", node, tempFilePath);
+        logger.info(Strings.format(json, version));
+        Files.write(tempFilePath, Strings.format(json, version).getBytes(StandardCharsets.UTF_8));
+        Files.move(tempFilePath, fileSettingsService.operatorSettingsFile(), StandardCopyOption.ATOMIC_MOVE);
+    }
+
+    public void testFailsOnStartWithError() throws Exception {
```
Comment (ywangd) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/FileSettingsRoleMappingsStartupIT.java:71]: Nit: maybe rename this to `testFailsOnStartMasterNodeWithError` since data node starts fine.

**Review by ywangd — APPROVED** [review]
LGTM

Thanks for going the extra mile on the tests. I learned a lot from them.

**Comment by grcevski** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc
