### PR TITLE
Install plugin permissions

### LINKED ISSUE #17201: Evaluate windows permissions in InstallPluginCommand
#17176 tightened up directory permissions during plugin installations. Sadly the added permissions are no good on windows as their are POSIX based.   We should evaluate what permissions are required for windows.

See for example http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/2703/consoleText, failing with: 

```
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:492)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
	at java.nio.file.Files.createTempDirectory(Files.java:950)
	at org.elasticsearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:252)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:174)
```

For now , permissions are disabled on windows with https://github.com/elastic/elasticsearch/commit/ee95c0a3843434b6fa43c8e448a192118368e6f4

### PR DESCRIPTION
**Pull request by jasontedor**
This pull request refactors the handling of POSIX attributes when installing plugins. In particular, an exemption is no longer made merely for Windows, but instead any filesystem that does not provide POSIX support is properly handled.

Additionally, the unit tests are refactored to use mock filesystems (in addition to the native filesystem!) so that breaking issues are more likely to be caught regardless of which OS the unit tests are run on. The tests are also updated to make assertions regarding the POSIX attributes of the plugins directory, the bin directory, and the config directory. These assertions capture recent changes to these attributes.

Lastly, the checkstyle line-length violations in InstallPluginCommand.java are fixed and the suppression for this check for this file is removed.

Closes #17201

### CODE REVIEW

File: qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java [hunk 1]
```diff
@@ -82,6 +137,7 @@ static void writeJar(Path jar, String... classes) throws IOException {
             for (String clazz : classes) {
                 stream.putNextEntry(new ZipEntry(clazz + ".class")); // no package names, just support simple classes
             }
+           // stream.putNextEntry(new ZipEntry("/bin/test"));
```
Comment (nik9000) [inline qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java]: Leftover?

**Comment by nik9000** [comment]
Seems good to me. OTOH I didn't remember windows for the permissions when I reviewed the last ones and I'm tired. So maybe don't trust me?

File: qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java (hunk 1 above)
Comment (jasontedor) [inline qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java]: Yes, thanks. Removed in 87a7248d83188f00514ca5034250f9cc5b6c0def.

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 2]
```diff
@@ -301,6 +296,22 @@ private Path unzip(Path zip, Path pluginsDir) throws IOException, UserError {
...
+            perms.add(PosixFilePermission.OWNER_EXECUTE);
+            perms.add(PosixFilePermission.OWNER_READ);
+            perms.add(PosixFilePermission.OWNER_WRITE);
+            perms.add(PosixFilePermission.GROUP_READ);
+            perms.add(PosixFilePermission.GROUP_EXECUTE);
+            perms.add(PosixFilePermission.OTHERS_READ);
+            perms.add(PosixFilePermission.OTHERS_EXECUTE);
+            return Files.createTempDirectory(pluginsDir, ".installing-", PosixFilePermissions.asFileAttribute(perms));
+        } catch (IllegalArgumentException | UnsupportedOperationException e) {
+            return Files.createTempDirectory(pluginsDir, ".installing-");
```
Comment (rmuir) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: IAE only happens if the prefix (`.installing-`) cannot be used. So if it fails, we shouldnt try the same prefix again, instead pass null?

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: If we can't use the prefix that sounds like a valid reason to fail entirely?

Comment (rmuir) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: yeah, thats even better IMO. Just remove the IAE catch!

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: @rmuir Unfortunately, the `IllegalArgumentException` catch is needed because JimFS violates the javadocs for `FileSystemProvider#createDirectory`; instead of throwing an `UnsupportedOperationException` when an attempt is made to set POSIX attributes on a file on a filesystem that does not support POSIX attributes. I'll hack the catch though to only catch it when it's coming from jimfs. I'll also submit an upstream pull request to get this corrected, but for now I think this is what we have to do?

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: I opened google/jimfs#30.

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: You can just change the throws clause for this exception. All the cli tools execute methods throw Exception, so actual errors can propagate to java main instead of adding wrapped exceptions everywhere.

File: core/src/main/java/org/elasticsearch/common/io/PathUtils.java [hunk 3]
```diff
@@ -57,10 +57,30 @@ private PathUtils() {}
...
+     * Remember: this should almost never be used. Usually resolve
+     * a path against an existing one!
+     *
+     * @param fs    the given {@code FileSystem}
+     * @param first the first path component
+     * @param more  the remaining path components
+     * @return a path
+     */
+    public static Path get(FileSystem fs, String first, String... more) {
+        return fs.getPath(first, more);
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/io/PathUtils.java]: I don't understand the utility of this added method. Callers could just call it directly on the filesystem they already have?

File: core/src/main/java/org/elasticsearch/env/Environment.java [hunk 4]
```diff
@@ -108,28 +109,32 @@
     }
 
     public Environment(Settings settings) {
+        this(PathUtils.getDefaultFileSystem(), settings);
+    }
+
+    public Environment(FileSystem fs, Settings settings) {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: This change should not be necessary. We already have the ability to plugin in a filesystem in tests. See `PathUtilsForTesting.installMock()`

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: Unfortunately this does not immediately work because it overrides the filesystem for everything. In particular, 

```
private final Path tmpFile = PathUtils.get(System.getProperty("java.io.tmpdir"));
```

in `Environment` will be resolved against the installed filesystem. Since `java.io.tmpdir` will be a path that is relevant to the default filesystem for the system that the test is executing on, it will for example cause tests that are running on a filesystem that handles paths differently to fail (e.g., running on OS X against a filesystem that is configured like Windows). A possibility exists to be evil (these tests are already evil) and change the system property for `java.io.tmpdir` before the tests start (and reset it afterwards) but that's tending towards hacky.

```diff
diff --git a/core/src/main/java/org/elasticsearch/env/Environment.java b/core/src/main/java/org/elasticsearch/env/Environment.java
index ca7363a..d89d51a 100644
--- a/core/src/main/java/org/elasticsearch/env/Environment.java
+++ b/core/src/main/java/org/elasticsearch/env/Environment.java
@@ -31,7 +31,6 @@ import java.net.MalformedURLException;
 import java.net.URISyntaxException;
 import java.net.URL;
 import java.nio.file.FileStore;
-import java.nio.file.FileSystem;
 import java.nio.file.Files;
 import java.nio.file.Path;
 import java.util.ArrayList;
@@ -109,32 +108,28 @@ public class Environment {
     }
 
     public Environment(Settings settings) {
-        this(PathUtils.getDefaultFileSystem(), settings);
-    }
-
-    public Environment(FileSystem fs, Settings settings) {
         this.settings = settings;
         final Path homeFile;
         if (PATH_HOME_SETTING.exists(settings)) {
-            homeFile = PathUtils.get(fs, PATH_HOME_SETTING.get(settings));
+            homeFile = PathUtils.get(PATH_HOME_SETTING.get(settings));
         } else {
             throw new IllegalStateException(PATH_HOME_SETTING.getKey() + " is not configured");
         }
 
         if (PATH_CONF_SETTING.exists(settings)) {
-            configFile = PathUtils.get(fs, cleanPath(PATH_CONF_SETTING.get(settings)));
+            configFile = PathUtils.get(cleanPath(PATH_CONF_SETTING.get(settings)));
         } else {
             configFile = homeFile.resolve("config");
         }
 
         if (PATH_SCRIPTS_SETTING.exists(settings)) {
-            scriptsFile = PathUtils.get(fs, cleanPath(PATH_SCRIPTS_SETTING.get(settings)));
+            scriptsFile = PathUtils.get(cleanPath(PATH_SCRIPTS_SETTING.get(settings)));
         } else {
             scriptsFile = configFile.resolve("scripts");
         }
 
         if (PATH_PLUGINS_SETTING.exists(settings)) {
-            pluginsFile = PathUtils.get(fs, cleanPath(PATH_PLUGINS_SETTING.get(settings)));
+            pluginsFile = PathUtils.get(cleanPath(PATH_PLUGINS_SETTING.get(settings)));
         } else {
             pluginsFile = homeFile.resolve("plugins");
         }
@@ -144,7 +139,7 @@ public class Environment {
             dataFiles = new Path[dataPaths.size()];
             dataWithClusterFiles = new Path[dataPaths.size()];
             for (int i = 0; i < dataPaths.size(); i++) {
-                dataFiles[i] = PathUtils.get(fs, dataPaths.get(i));
+                dataFiles[i] = PathUtils.get(dataPaths.get(i));
                 dataWithClusterFiles[i] = dataFiles[i].resolve(ClusterName.clusterNameFromSettings(settings).value());
             }
         } else {
diff --git a/qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java b/qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java
index 7c51686..5b26102 100644
--- a/qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java
+++ b/qa/evil-tests/src/test/java/org/elasticsearch/plugins/InstallPluginCommandTests.java
@@ -27,10 +27,12 @@ import org.elasticsearch.Version;
 import org.elasticsearch.cli.MockTerminal;
 import org.elasticsearch.cli.UserError;
 import org.elasticsearch.common.io.PathUtils;
+import org.elasticsearch.common.io.PathUtilsForTesting;
 import org.elasticsearch.common.settings.Settings;
 import org.elasticsearch.env.Environment;
 import org.elasticsearch.test.ESTestCase;
 import org.elasticsearch.test.PosixPermissionsResetter;
+import org.junit.After;
 
 import java.io.IOException;
 import java.io.InputStream;
@@ -71,12 +73,23 @@ public class InstallPluginCommandTests extends ESTestCase {
     private final FileSystem fs;
     private final boolean isPosix;
     private final boolean isReal;
+    private final String javaIoTmpdir;
 
     public InstallPluginCommandTests(FileSystem fs, Function<String, Path> temp) {
         this.fs = fs;
         this.temp = temp;
         this.isPosix = fs.supportedFileAttributeViews().contains("posix");
         this.isReal = fs == PathUtils.getDefaultFileSystem();
+        PathUtilsForTesting.installMock(fs);
+        javaIoTmpdir = System.getProperty("java.io.tmpdir");
+        System.setProperty("java.io.tmpdir", temp.apply("tmpdir").toString());
+    }
+
+    @After
+    public void tearDown() throws Exception {
+        super.tearDown();
+        PathUtilsForTesting.teardown();
+        System.setProperty("java.io.tmpdir", javaIoTmpdir);
     }
 
     @ParametersFactory
@@ -124,7 +137,7 @@ public class InstallPluginCommandTests extends ESTestCase {
         Settings settings = Settings.builder()
             .put("path.home", home)
             .build();
-        return new Environment(fs, settings);
+        return new Environment(settings);
     }
 
     static Path createPluginDir(Function<String, Path> temp) throws IOException {
```

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: I still dont' think it is necessary. The mock FS needs to be installed before creating the Environemnt, and any calls to PathUtils.get will work correctly, including the one done for tmpDir.

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: > it will for example cause tests that are running on a filesystem that handles paths differently to fail 

But we shouldn't be testing every FS. We shoudl be testing the logic in plugin installation, which is either is or is not posix. So you can use posix for testing the stuff works, and "basic" for testing it skips the extra code gracefully for non-posix FS.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: See the diff in my comment above; I already removed the change to `Environment` in that diff but I'm inquiring about your thoughts on the hack around `java.io.tmdir`.

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: And see my comment above about why java.io.tmpdir should not matter.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/env/Environment.java]: > And see my comment above about why java.io.tmpdir should not matter.

Sure, that was a race condition. :)

> But we shouldn't be testing every FS.

That's a red herring, that's not what is being proposed.

> So you can use posix for testing the stuff works, and "basic" for testing it skips the extra code gracefully for non-posix FS.

I'm not sure I agree, I think that we should be testing with configurations that get us close to what most of our users are running on. This increases the likelihood that we detect issues locally before they even hit the CI.

**Comment by nik9000** [comment]
LGTM
