### PR TITLE
[ML] Inference API disable partial search results

### LINKED ISSUE #132361: [ML] Inference API unable to retrieve inference endpoint
We're seeing failures within the inference API where the internal search request is unable to retrieve the documents from the configuration and secrets indices.

Typically an error like this will be seen:

```
java.lang.IllegalStateException: Failed to load inference endpoint [<inference id>]. Endpoint is in an invalid state, try deleting and reinitializing the service
```

This could indicate that some other issue is occurring with the cluster. This is likely happening because we allow partial search results. Instead we should disable partial search results to bubble up the actual issue (whether a timeout or something else).

### PR DESCRIPTION
**Pull request by jonathan-buttner**
This PR disables partial search results when retrieving the inference endpoint information from the configuration and secrets index. This should bubble up the originating exception for the reason that the document from each index is not available. If an unexpected exception occurs it is wrapped in an `ElasticsearchException` to include the inference endpoint that is failing.

### CODE REVIEW

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/InferenceIndicesIT.java [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+        "similarity",
+        "cosine",
+        "api_key",
+        "my_api_key"
+    );
+
+    public static class LocalStateIndexSettingsInferencePlugin extends LocalStateCompositeXPackPlugin {
+        private final InferencePlugin inferencePlugin;
+
+        public LocalStateIndexSettingsInferencePlugin(final Settings settings, final Path configPath) throws Exception {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/InferenceIndicesIT.java:71]: If you can think of a better way to direct the inference configuration index and secrets index to separate nodes let me know. I'm injecting some settings that won't be present in production but allows us to direct the documents to specific nodes for easier testing.

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/InferenceIndicesIT.java [hunk 2]
```diff
@@ -0,0 +1,252 @@
...
+
+        // stop the node that holds the inference index
+        internalCluster().stopNode(configIndexDataNodes);
+
+        var responseFailureFuture = client().execute(GetInferenceModelAction.INSTANCE, getInferenceEndpointRequest);
+        var exception = expectThrows(ElasticsearchException.class, () -> responseFailureFuture.actionGet(TEST_REQUEST_TIMEOUT));
+        assertThat(exception.toString(), containsString("Failed to load inference endpoint [test-index-id]"));
+
+        var causeException = exception.getCause();
+        assertThat(causeException, instanceOf(SearchPhaseExecutionException.class));
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/InferenceIndicesIT.java:146]: I tried adding more assertThat's for looking for certain text in the search phase execution exception, but they exact wording changes during my test runs and was causing the test to be flaky.

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/InferenceIndex.java [hunk 3]
```diff
@@ -30,10 +30,19 @@ private InferenceIndex() {}
...
+
+    private static Settings.Builder builder() {
+        return Settings.builder().put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, 1).put(IndexMetadata.SETTING_AUTO_EXPAND_REPLICAS, "0-1");
+    }
+
+    /**
+     * This allows tests to set additional settings for the inference index.
+     * @param extraSettings additional settings to apply to the inference index.
+     */
+    public static Settings settingsForTesting(Settings extraSettings) {
```
Comment (davidkyle) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/InferenceIndex.java]: Can the 2 `settingsForTesting()` functions be moved to the test code? That would keep this cleaner

**Comment by jonathan-buttner** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/150780)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
