### PR TITLE
[TEST] Address rejected execution in SearchAsyncActionTests

### LINKED ISSUE #33699: SearchAsyncActionTests.testFanOutAndCollect throws RejectedExecutionException
I dug into #29242 again and tried to reproduce the problem at 5a3fd8e4e7c8d2721b3542ffa859c9245678d6c2 by running the affected test repeatedly until it failed by using:

    date | tee pass-times.log; while ./gradlew --console=plain :server:test -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests -Dtests.method="testFanOutAndCollect" 2>&1 > testoutput.log; do date | tee -a pass-times.log; done

After around 1000 iterations (6 hours) it failed with a different issue:

```
  2> ༩ ༡༣, ༢༠༡༨ ༢:༤༧:༢༧ ཕྱི་ཆ་ com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[Thread-1,5,TGRP-SearchAsyncActionTests]
  2> java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@db8dd7d rejected from java.util.concurrent.ThreadPoolExecutor@2e3a06e7[Terminated,
 pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
  2>    at __randomizedtesting.SeedInfo.seed([CAEABDE40791E9D5]:0)
  2>    at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2080)
  2>    at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:832)
  2>    at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:174)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:167)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:293)
  2>    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:214)
  2>    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:208)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:169)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
  2>    at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:270)
  2>    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
  2>    at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:334)
  2>    at java.base/java.lang.Thread.run(Thread.java:844)
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=CAEABDE40791E9D5 -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests -Dtests.method="testFanOutAndCollect" -Dtests.security.manager=true -Dtests.locale=dz -Dtests.timezone=Etc/GMT+11 -Dcompiler.java=10 -Druntime.java=10
ERROR   0.14s | SearchAsyncActionTests.testFanOutAndCollect <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=18, name=Thread-1, state=RUNNABLE, group=TGRP-SearchAsyncActionTests]
   >    at __randomizedtesting.SeedInfo.seed([CAEABDE40791E9D5:B11B3894FE3A2856]:0)
   > Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@db8dd7d rejected from java.util.concurrent.ThreadPoolExecutor@2e3a06e7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
   >    at __randomizedtesting.SeedInfo.seed([CAEABDE40791E9D5]:0)
   >    at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2080)
   >    at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:832)
   >    at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
   >    at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:174)
   >    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:167)
   >    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
   >    at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:293)
   >    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:214)
   >    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:208)
   >    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:169)
   >    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
   >    at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
   >    at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:270)
   >    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
   >    at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:334)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1617, maxMBSortInHeap=7.294998490965383, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@5ee576f6), locale=dz, timezone=Etc/GMT+11
  2> NOTE: Linux 4.13.0-32-generic amd64/Oracle Corporation 10 (64-bit)/cpus=8,threads=1,free=494096088,total=536870912
  2> NOTE: All tests run in this JVM: [SearchAsyncActionTests]

FAILURE: Build failed with an exception.
```

I initially saw this kind of failure using `-Dtests.iters=1000`, which yielded this failure after only a few runs, but was unsure whether it might have been a symptom of the `tests.iters` setting. This confirms that it can also occur if the test runs individually.

### LINKED ISSUE #36221: SearchAsyncActionTests testLimitConcurrentShardRequests fails with RejectedExecutionException
Failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/98/consoleFull

Error message:

```
13:08:25 ERROR   0.11s J1 | SearchAsyncActionTests.testLimitConcurrentShardRequests <<< FAILURES!
13:08:25    > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=265, name=Thread-54, state=RUNNABLE, group=TGRP-SearchAsyncActionTests]
13:08:25    > Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@32524f5f rejected from java.util.concurrent.ThreadPoolExecutor@30e9de81[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 3]
13:08:25    > 	at __randomizedtesting.SeedInfo.seed([326E2801814230CE]:0)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:173)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:166)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:290)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:213)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:207)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:168)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:267)
13:08:25    > 	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
13:08:25    > 	at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:337)
13:08:25    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=264, name=Thread-53, state=RUNNABLE, group=TGRP-SearchAsyncActionTests]
13:08:25    > Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@2ea5ff4d rejected from java.util.concurrent.ThreadPoolExecutor@30e9de81[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
13:08:25    > 	at __randomizedtesting.SeedInfo.seed([326E2801814230CE]:0)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:173)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:166)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:290)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:213)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:207)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:168)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:267)
13:08:25    > 	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
13:08:25    > 	at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:337)
13:08:25    > 	at java.lang.Thread.run(Thread.java:748)
```

Reproduction line: 

```
./gradlew :server:test \
  -Dtests.seed=326E2801814230CE \
  -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests \
  -Dtests.method="testLimitConcurrentShardRequests" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-LY \
  -Dtests.timezone=Atlantic/Stanley \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

This has failed 32 times in CI within the last 6 months. Also, #33699 seems related.

### PR DESCRIPTION
**Pull request by javanna**
SearchAsyncActionTests may fail with RejectedExecutionException as InitialSearchPhase may try to execute a runnable after the test has successfully completed, and the corresponding executor was already shut down. The latch was located in getNextPhase that is almost correct, but does not cover for the last finishAndRunNext round that gets executed after onShardResult is invoked.

This commit moves the latch to count the number of shards, and allowing the test to count down later, after finishAndRunNext has been potentially forked. This way nothing else will be executed once the executor is shut down at the end of the tests.

Closes #36221
Closes #33699

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java [hunk 1]
```diff
@@ -232,10 +224,18 @@ private synchronized Runnable tryQueue(Runnable runnable) {
     }
 
     private void executeNext(PendingExecutions pendingExecutions, Thread originalThread) {
+        executeNext(pendingExecutions == null ? null : pendingExecutions::finishAndRunNext, originalThread);
+    }
+
+    protected void executeNext(Runnable runnable, Thread originalThread) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java]: I added this protected method rather than making the existing `executeNext` protected, just to leave the `PendingExecutions` class private. While I was at it, I folded `maybeFork` into this one as it was only called from here anyways.

File: server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java [hunk 2]
```diff
@@ -256,28 +256,26 @@ private void performPhaseOnShard(final int shardIndex, final SearchShardIterator
...
                 try {
-                    executePhaseOnShard(shardIt, shard, new SearchActionListener<FirstResult>(
-                        shardIt.newSearchShardTarget(shard.currentNodeId()), shardIndex) {
-                        @Override
-                        public void innerOnResponse(FirstResult result) {
-                            try {
-                                onShardResult(result, shardIt);
-                            } finally {
-                                executeNext(pendingExecutions, thread);
+                    executePhaseOnShard(shardIt, shard,
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/InitialSearchPhase.java]: here I only adjusted the indentation, which made this section hard to read.

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java [hunk 3]
```diff
@@ -142,15 +142,21 @@ protected SearchPhase getNextPhase(SearchPhaseResults<TestSearchPhaseResult> res
                     return new SearchPhase("test") {
                         @Override
                         public void run() {
-                            latch.countDown();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: If we remove this then how do we know the search phase actually runs?

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java [hunk 4]
```diff
@@ -246,10 +253,16 @@ protected SearchPhase getNextPhase(SearchPhaseResults<TestSearchPhaseResult> res
...
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: Similarly, if we remove this then how do we know the search phase actually runs?

**Review by DaveCTurner — COMMENTED** [review]
A cunning approach, and thanks for the inline comments about refactoring/reformatting. I think as it stands this makes the affected tests weaker (see comments).

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java (hunk 4 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: yes we are just moving to counting the search the shards rather than the one search, which was counted too early.

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java (hunk 3 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: yes we are just moving to counting the search the shards rather than the one search, which was counted too early.

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: How about making an `AtomicBoolean searchPhaseDidRun` and then calling `assertTrue(searchPhaseDidRun.compareAndSet(false, true));` here and `assertTrue(searchPhaseDidRun.get());` somewhere after the `latch.await();`?

Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: yes that makes sense. I initially did not consider that we were using the latch to also make sure that we would move on to the next phase. It makes sense to check that.

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java [hunk 5]
```diff
@@ -161,28 +158,18 @@ public void testLimitConcurrentShardRequests() throws InterruptedException {
...
-            @Override
-            public void onFailure(Exception e) {
-                logger.warn("test failed", e);
-                fail(e.getMessage());
-            }
-        };
+        int numShards = 10;
+        CountDownLatch latch = new CountDownLatch(numShards);
+        AtomicBoolean searchPhaseDidRun = new AtomicBoolean(false);
+        ActionListener<SearchResponse> responseListener = ActionListener.wrap(response -> {}, e -> fail(e.getMessage()));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: `fail(e.getMessage())` loses the stack trace from the thrown exception, which might be useful. How about `throw new AssertionError("unexpected", e);` instead?

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java [hunk 6]
```diff
@@ -263,26 +257,17 @@ public void testFanOutAndCollect() throws InterruptedException {
...
-            }
-
-            @Override
-            public void onFailure(Exception e) {
-                logger.warn("test failed", e);
-                fail(e.getMessage());
-            }
-        };
+        ActionListener<SearchResponse> responseListener = ActionListener.wrap(
+            searchResponse -> response.set((TestSearchResponse) searchResponse), e -> fail(e.getMessage()));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: `fail(e.getMessage())` loses the stack trace from the thrown exception, which might be useful. How about `throw new AssertionError("unexpected", e);` instead?

**Review by DaveCTurner — COMMENTED** [review]
I think we should preserve stack traces from exceptions that cause tests to fail. Otherwise this looks great.

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java [hunk 7]
```diff
@@ -62,34 +62,24 @@
...
-            }
-
-            @Override
-            public void onFailure(Exception e) {
-                logger.warn("test failed", e);
-                fail(e.getMessage());
-            }
-        };
+        int numShards = 10;
+        ActionListener<SearchResponse> responseListener = ActionListener.wrap(response -> {}, e -> fail(e.getMessage()));
```
[the remark this answers is not in the document]
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: sure, makes sense

**Review by DaveCTurner — APPROVED** [review]
LGTM, thanks @javanna.
