### PR TITLE
Stop reusing cluster for CrossClusterAsyncQueryStopIT and unmute

### LINKED ISSUE #133481: [CI] CrossClusterAsyncQueryStopIT testStopQueryLocal failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10249 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/cd6yj66okzxru)
- [elasticsearch-pull-request #87730 / part-3](https://gradle-enterprise.elastic.co/s/bwhon3ygep554)
- [elasticsearch-pull-request #87581 / part-3](https://gradle-enterprise.elastic.co/s/s34geysc4m6gk)
- [elasticsearch-pull-request #87478 / part-3](https://gradle-enterprise.elastic.co/s/wuizi6p74buwm)
- [elasticsearch-pull-request #86924 / part-3](https://gradle-enterprise.elastic.co/s/yvt3wcu7ukdwi)
- [elasticsearch-pull-request #86801 / part-3](https://gradle-enterprise.elastic.co/s/knaznfts3yjyq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.CrossClusterAsyncQueryStopIT.testStopQueryLocal" -Dtests.seed=17F68441DB0C201F -Dtests.locale=en-LR -Dtests.timezone=Europe/Ljubljana -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClusterAsyncQueryStopIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testStopQueryLocal'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timeout waiting for DELETE response
```

**Issue Reasons:**
- [main] 6 failures in test testStopQueryLocal (0.6% fail rate in 962 executions)
- [main] 5 failures in step part-3 (1.2% fail rate in 401 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (1.3% fail rate in 399 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by smalyshev**
We got a lot of error contamination from other tests and DELETE timeouts. Let's see if not reusing clusters helps it. 

Closes https://github.com/elastic/elasticsearch/issues/133481

### CODE REVIEW

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterAsyncQueryStopIT.java [hunk 1]
```diff
@@ -351,7 +358,16 @@ public void testStopQueryInlineStats() throws Exception {
...
+            deleteAsyncId(client(), asyncExecutionId);
+        }
+    }
+
+    public void deleteAsyncId(Client client, String id) {
+        try {
+            DeleteAsyncResultRequest request = new DeleteAsyncResultRequest(id);
+            assertAcked(client.execute(TransportDeleteAsyncResultAction.TYPE, request).actionGet(30, TimeUnit.SECONDS));
+        } catch (ElasticsearchTimeoutException e) {
+            LOGGER.warn("timeout waiting for DELETE response: {}: {}", id, e);
```
Comment (chrisparrinello) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterAsyncQueryStopIT.java:370]: Should we assert here as well to ensure the underlying test is marked as failed? I'm assuming that a timeout on a DELETE request is not good either. 

This is also assuming I'm understanding the underlying fix here which is to make sure one failing test does not cause the whole suite to fail when it would otherwise succeed if the order of the tests were flipped.

Comment (smalyshev) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterAsyncQueryStopIT.java:370]: No, that's the whole thing - the delete is not part of the test, and I don't care too much what happens to it. I mean, if it fails in some weird way, then probably it's good to expose it, but if it just takes a long time that's not what the test is about... but somehow a lot of times that's where it fails, which is annoying.

Comment (chrisparrinello) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterAsyncQueryStopIT.java:370]: Okay this makes sense to me. Thanks for clarifying!

**Review by chrisparrinello — APPROVED** [review]
LGTM

**Comment by smalyshev** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/136439)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
