### PR TITLE
[Test] Ensure shardSearch task is handled before cancelling

### LINKED ISSUE #86881: [CI] ProfileCancellationIntegTests testSuggestProfilesCancellation failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/k3titqku4p2be/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.profile.ProfileCancellationIntegTests/testSuggestProfilesCancellation

**Reproduction line:**
`./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.profile.ProfileCancellationIntegTests.testSuggestProfilesCancellation" -Dtests.seed=74F6D1B80FACB410 -Dtests.locale=no-NO -Dtests.timezone=BET -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.profile.ProfileCancellationIntegTests&tests.test=testSuggestProfilesCancellation

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[107]>

  at __randomizedtesting.SeedInfo.seed([74F6D1B80FACB410:B026926B1FBFB102]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.profile.ProfileCancellationIntegTests.lambda$testSuggestProfilesCancellation$3(ProfileCancellationIntegTests.java:119)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1096)
  at org.elasticsearch.xpack.security.profile.ProfileCancellationIntegTests.testSuggestProfilesCancellation(ProfileCancellationIntegTests.java:109)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by ywangd**
When the ShardSearch task is registered but not really handled,
cancellation does not work as expected. This PR ensures the task is
actually handled, i.e. creating a new readerContext, before
cancellation.

Resolves: #86881

### CODE REVIEW

**Comment by ywangd** [comment]
@n1v0lg I didn't look into details on exactly how the the test failed. But I have a few theories. So would like to give them a try. They may fix the failure for good. If not, they can still give us more data when it fails again in future. Please let me know what you think. Thanks!

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java [hunk 1]
```diff
@@ -101,7 +102,11 @@ public void onFailure(Exception exception) {
                 taskActions,
                 hasItems(equalTo(SuggestProfilesAction.NAME), equalTo(SearchAction.NAME), startsWith(SearchAction.NAME))
             );
-            tasks.forEach(t -> taskIds.add(t.getId()));
+            assertThat(isShardSearchBlocked(), is(true));
```
Comment (ywangd) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java:105]: In addition to make sure tasks are all registered, this new assertion makes sure the shardSearch request is actually handled. This means the test should always wait for the log line "blocking search on ..." before proceeding. If this does not work, at least we can be sure that the problem is in the request handling part instead of cancellation.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java [hunk 2]
```diff
@@ -101,7 +102,11 @@ public void onFailure(Exception exception) {
...
+            tasks.forEach(t -> {
+                logger.info("task " + t.getId() + "/" + t.getAction() + " registered");
+                taskIds.add(t.getId());
+            });
```
Comment (ywangd) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java:109]: Just some more logging to tell exactly what tasks are expected to be cancelled.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java [hunk 3]
```diff
@@ -180,12 +195,20 @@ public SearchBlockPlugin(Settings settings, Path configPath) throws Exception {
         public void onIndexModule(IndexModule indexModule) {
             super.onIndexModule(indexModule);
             indexModule.addSearchOperationListener(new SearchOperationListener() {
+
+                @Override
+                public void onPreQueryPhase(SearchContext c) {
+                    logger.info("onPreQueryPhase");
+                }
```
Comment (ywangd) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java:202]: The blocking is done in the `onNewReaderContext` method. If for any reason, the reader context already exists before the search request, the method may not be called. So I added simple logging as the implementation of `onPreQueryPhase` to indicate that if it somehow happens.

**Review by n1v0lg — APPROVED** [review]
LGTM and thanks for the context! One sanity check around `isShardSearchBlocked`. 

Agreed that even if in the end the issue still persists, the extra logging will give us enough to go on for more debugging. 

Also more than happy to poke around if this crops up again. Good way for me to learn.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java [hunk 4]
```diff
@@ -166,11 +171,21 @@ private void disableSearchBlock() {
         }
     }
 
+    private boolean isShardSearchBlocked() {
+        for (PluginsService pluginsService : internalCluster().getInstances(PluginsService.class)) {
+            if (pluginsService.filterPlugins(SearchBlockPlugin.class).stream().anyMatch(SearchBlockPlugin::isShardSearchBlocked)) {
+                return true;
```
[the remark this answers is not in the document]
Comment (ywangd) [reply x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileCancellationIntegTests.java:177]: Since the profile index only has a single primary shard. The shardSearch task should only be handled on a single node (either the one hosting the primary or the one hosting the replica). So it is not possible for it to be blocked on all nodes. In fact, the test fails (timeout) if we try to assert all nodes are blocked.
