### PR TITLE
Fix PrimaryAllocationIT#testForceStaleReplicaToBePromotedToPrimary

### LINKED ISSUE #35497: Sporadic failure in testForceStaleReplicaToBePromotedToPrimary
#34140 introduces an assertion in `PrimaryAllocationIT#testForceStaleReplicaToBePromotedToPrimary` that sometimes fails. See for instance https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/56/console:

```
   > Throwable #1: java.lang.AssertionError: expected:<[]> but was:<[tuWXzhckTEu0-GBybc-VJQ]>
   > 	at __randomizedtesting.SeedInfo.seed([6DA82B0AC7639B17:3BB0A62AD8D3F5B0]:0)
   > 	at org.elasticsearch.cluster.routing.PrimaryAllocationIT.testForceStaleReplicaToBePromotedToPrimary(PrimaryAllocationIT.java:222)
   > 	at java.lang.Thread.run(Thread.java:748)
```

I think the issue is that we allocate a stale or empty primary via a reroute command, then grab the cluster state, and then assert that the in-sync IDs in that cluster state are what they should be straight after the reroute. However, if the shard has actually been allocated by the time we get hold of the cluster state then this assertion fails.

@vladimirdolzhenko could you take a look?

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**
Failure described in #35497 could be reproduced under load or just adding some delay in between reroute command execution and getting cluster state (allocation ids) - in that case recovery already passed and allocation ids contain actual node id rather expected allocation id right after command execution. 

The fix is to grab in-sync set of the 1st cluster state change after reroute execution from `ClusterService` of the node.

Closes #35497

### CODE REVIEW

**Comment by MirAkram** [comment]
mj1265849@gmail.com
در تاریخ ۲۰ نوامبر ۲۰۱۸ ۷:۲۶ بعدازظهر، "David Turner" <
notifications@github.com> نوشت:

File: server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java [hunk 1]
```diff
@@ -212,14 +216,27 @@ public void testForceStaleReplicaToBePromotedToPrimary() throws Exception {
...
+            clusterStateChangeLatch.countDown();
+        };
+        final ClusterService clusterService = internalCluster().getInstance(ClusterService.class, master);
+        clusterService.addListener(clusterStateListener);
+
         rerouteBuilder.get();
 
-        ClusterState state = client().admin().cluster().prepareState().get().getState();
+        clusterStateChangeLatch.await();
+        clusterService.removeListener(clusterStateListener);
```
[the remark this answers is not in the document]
Comment (vladimirdolzhenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: handled it in 8ec74e6

File: server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java [hunk 2]
```diff
@@ -212,14 +215,25 @@ public void testForceStaleReplicaToBePromotedToPrimary() throws Exception {
...
+            if (expectedAllocationIds.equals(allocationIds)) {
+                clusterStateChangeLatch.countDown();
+            }
+        };
+        final ClusterService clusterService = internalCluster().getInstance(ClusterService.class, master);
+        clusterService.addListener(clusterStateListener);
+
+        rerouteBuilder.get();
+
+        assertThat(clusterStateChangeLatch.await(30, TimeUnit.SECONDS), equalTo(true));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: Why not just `assertTrue()`?

File: server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java [hunk 3]
```diff
@@ -212,14 +215,25 @@ public void testForceStaleReplicaToBePromotedToPrimary() throws Exception {
...
             ? Collections.singleton(RecoverySource.ExistingStoreRecoverySource.FORCED_ALLOCATION_ID)
             : Collections.emptySet();
-        assertEquals(expectedAllocationIds, state.metaData().index(idxName).inSyncAllocationIds(0));
+
+        final CountDownLatch clusterStateChangeLatch = new CountDownLatch(1);
+        final ClusterStateListener clusterStateListener = event -> {
+            final Set<String> allocationIds = event.state().metaData().index(idxName).inSyncAllocationIds(0);
+            if (expectedAllocationIds.equals(allocationIds)) {
+                clusterStateChangeLatch.countDown();
+            }
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: Just thinking about diagnosing possible future failures, I think it would be useful to `logger.info()` any non-matching states so we can see if something weird was going on.

**Review by DaveCTurner — COMMENTED** [review]
Looks good. Asked for a bit more logging just in case it fails again.

File: server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java (hunk 2 above)
Comment (vladimirdolzhenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: agreed: there are ~3250 `assertTrue`+`assertFalse` vs 1300 `equalTo(true)`/`equalTo(false)`

addressed in 22a6ffb

File: server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java (hunk 3 above)
Comment (vladimirdolzhenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: addressed in 22a6ffb

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by MirAkram** [comment]
mj1265849@gmail.com
در تاریخ ۲۰ نوامبر ۲۰۱۸ ۹:۳۳ بعدازظهر، "David Turner" <
notifications@github.com> نوشت:

**Comment by vladimirdolzhenko** [comment]
thanks @DaveCTurner
