### PR TITLE
Fix transport serialization of `EnrichStatsAction.Request`

### LINKED ISSUE #121642: [CI] UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/110_enrich/Enrich stats query smoke test for mixed cluster} failing
**Build Scans:**
- [elasticsearch-intake #17194 / 9.0.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/uum4u2zrfn3ru)
- [elasticsearch-pull-request #54825 / 9.0.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/lsx6jyeqi324y)
- [elasticsearch-pull-request #54812 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/kovqf4jwxrjqm)
- [elasticsearch-pull-request #54811 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/xibybi4mpqvgg)
- [elasticsearch-pull-request #54780 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/npg7zqhurdr5o)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:rolling-upgrade:v9.0.0#twoThirdsUpgradedTest" -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/110_enrich/Enrich stats query smoke test for mixed cluster}" -Dtests.seed=68B1B51BE52BA06E -Dtests.bwc=true -Dtests.locale=mk -Dtests.timezone=America/Indiana/Petersburg -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dmixed_cluster%2F110_enrich%2FEnrich%20stats%20query%20smoke%20test%20for%20mixed%20cluster%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [mixed_cluster/110_enrich:7]: expected [2xx] status code but api [enrich.stats] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"e_o_f_exception","reason":null,"stack_trace":"org.elasticsearch.ElasticsearchException$1\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:725)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:639)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.build(RestResponse.java:202)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:161)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:122)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.action.RestActionListener.onFailure(Res
[truncated]
```

**Issue Reasons:**
- [main] 5 failures in test test {p0=mixed_cluster/110_enrich/Enrich stats query smoke test for mixed cluster} (1.0% fail rate in 492 executions)
- [main] 2 failures in step 9.0.0_bwc-snapshots (1.4% fail rate in 144 executions)
- [main] 3 failures in step 8.19.0_bwc-snapshots (2.0% fail rate in 153 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (3.4% fail rate in 118 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
In #121256, we changed the superclass of the request to `LocalClusterStateRequest` to make the action run on the local node instead of the master node. Most of the actions that have been updated thusfar to run on the local node used to extend `MasterNodeReadRequest` and thus serialized a `local` field. This request class, however, extended `MasterNodeRequest`, meaning that it didn't serialize that field.

Fixes #121642

### CODE REVIEW

**Comment by nielsbauman** [comment]
I'm having trouble running the failing test to prove that my changes actually fixed the issue. While I try to get the test to run locally, this PR can already be reviewed.

Also, putting `>non-issue` instead of `>bug` because the bug hasn't been released yet (yay :tada:).

File: server/src/main/java/org/elasticsearch/action/support/local/LocalClusterStateRequest.java [hunk 1]
```diff
@@ -41,12 +41,23 @@ protected LocalClusterStateRequest(TimeValue masterTimeout) {
      */
     @UpdateForV10(owner = UpdateForV10.Owner.DISTRIBUTED_COORDINATION)
     protected LocalClusterStateRequest(StreamInput in) throws IOException {
+        this(in, true);
+    }
+
+    /**
+     * This constructor exists solely for BwC purposes. It should exclusively be used by requests that used to extend
+     * {@link org.elasticsearch.action.support.master.MasterNodeReadRequest} and still need to be able to serialize incoming request.
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/support/local/LocalClusterStateRequest.java:49]: I thought that the Enrich action extended `MasterNodeRequest`, not `MasterNodeReadRequest`?

**Review by dakrone — APPROVED** [review]
LGTM, I left one question about the javadoc
