### PR TITLE
Fix inconsistent terms aggregation order for 5.x

### LINKED ISSUE #23613: Inconsistent bucket ordering using term aggregation
**Elasticsearch version**: 
[5.1.2]

**JVM version**:
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**OS version**:
macOS 10.12.2

**Description of the problem including expected versus actual behavior**:
```
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "TestId": {
              "value": "2",
              "boost": 1
            }
          }
        },
        {
          "bool": {
            "must": [
              {
                "bool": {
                  "must": [
                    {
                      "term": {
                        "content": {
                          "value": "test",
                          "boost": 1
                        }
                      }
                    }
                  ],
                  "disable_coord": false,
                  "adjust_pure_negative": true,
                  "boost": 1
                }
              },
              {
                "bool": {
                  "must": [
                    {
                      "bool": {
                        "should": [
                          {
                            "term": {
                              "catalogs": {
                                "value": "1",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "catalogs": {
                                "value": "3",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "catalogs": {
                                "value": "4",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "catalogs": {
                                "value": "5",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "catalogs": {
                                "value": "6",
                                "boost": 1
                              }
                            }
                          },
                          {
                            "term": {
                              "catalogs": {
                                "value": "7",
                                "boost": 1
                              }
                            }
                          }
                        ],
                        "disable_coord": false,
                        "adjust_pure_negative": true,
                        "boost": 1
                      }
                    }
                  ],
                  "disable_coord": false,
                  "adjust_pure_negative": true,
                  "boost": 1
                }
              }
            ],
            "disable_coord": false,
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "disable_coord": false,
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "version": true,
  "aggregations": {
    "variantGrouping": {
      "terms": {
        "field": "variantId",
        "size": 10,
        "min_doc_count": 1,
        "shard_min_doc_count": 0,
        "show_term_doc_count_error": false,
        "order":
          {
            "top_hit": "desc"
          }
      },
      "aggregations": {
        "item": {
          "top_hits": {
            "from": 0,
            "size": 1,
            "version": false,
            "explain": false
          }
        },
        "top_hit": {
          "max": {
            "script": {
              "inline": "_score",
              "lang": "painless"
            }
          }
        }
      }
    }
  }
}
```

I have a query (see above) that uses a term aggregation combined with a top-hits aggregation to achieve field collapsing. 
As suggested in the top-hits documentation an additional max-aggregation is used to sort the term buckets by their score.
This is working when the request is submitted using curl but NOT using the java API.

Using curl I can adjust the "size" of the term aggregation from x to x + y and the first x elements are sorted EXACTLY the same, which is needed for paging.
Using the java API the order is 1) different from the curl request and 2) changes when i adjust the size parameter.
In my case, the _score for every bucket is the exact same and using the java API the sorting doesn't seem to be stable.

I have found a workaround for my case using a second sort criteria as a tie breaker: 

```
"order": [
	{
	"top_hit": "desc"
	},
	{
	"_term": "asc"
	}
]
```
**Steps to reproduce**:
```
SearchRequestBuilder srb = buildSearch();
SearchResponse response = srb.execute().actionGet();
```
Using the SearchRequestBuilder I can copy the JSON request and execute it using curl.
Now I can compare the ordering of the buckets returned by curl and in the SearchResponse.

Is this a bug or am I doing something stupid?

### PR DESCRIPTION
**Pull request by qwerty4030**
This commit fixes inconsistent terms aggregation order by ensuring the order contains a tie breaker.
If needed a tie-breaker (_term asc) is added by using a compound order.

Closes #23613 for the 5.X branch (backport from #22343).

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregationBuilder.java [hunk 1]
```diff
@@ -196,7 +197,11 @@ public TermsAggregationBuilder order(Terms.Order order) {
         if (order == null) {
             throw new IllegalArgumentException("[order] must not be null: [" + name + "]");
         }
-        this.order = order;
+        if(order instanceof CompoundOrder || InternalOrder.isTermOrder(order)) {
+            this.order = order; // if order already contains a tie-breaker we are good to go
+        } else { // otherwise add a tie-breaker by using a compound order
+            this.order = Terms.Order.compound(order);
+        }
```
Comment (colings86) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregationBuilder.java]: Instead of doing this are we not able to just call `order(Collections.singletonList(order)`?

Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregationBuilder.java]: No because that method calls this one again. Also this may result in a nested `CompoundOrder`, which doesn't make sense.

**Comment by colings86** [comment]
jenkins test this

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregationBuilder.java (hunk 1 above)
Comment (colings86) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregationBuilder.java]: ok, makes sense

**Review by colings86 — APPROVED** [review]
LGTM

**Comment by colings86** [comment]
@qwerty4030 thanks for doing this, I've merged this into the 5.x branch now so it will be available from the 5.5 release
