### PR TITLE
Avoid return negative value in CounterMetric

### LINKED ISSUE #70968: [CI] AssertionError in ShardSearchStats.onFetchPhase
The following assertion tripped in the core search code while doing a search in an ML test on the 7.x branch:

https://github.com/elastic/elasticsearch/blob/6343c18f724041c13f0d101028a8055d4079272f/server/src/main/java/org/elasticsearch/index/search/stats/ShardSearchStats.java#L112

**Build scan**:

https://gradle-enterprise.elastic.co/s/innofaaydb3fc

**Repro line**:

```
./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testJobRelocationIsMemoryAware" -Dtests.seed=1CE7934034A0817E -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=America/La_Paz -Druntime.java=8
```

**Reproduces locally?**:

No

**Applicable branches**:

master, 7.x

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22Uncaught%20exception%20in%20thread%22%20AND%20ShardSearchStats.java%20AND%20112'),sort:!(time,desc))

Same thing happened in a [PR](https://github.com/elastic/elasticsearch/pull/69338) build on 24th February, but in `BasicDistributedJobsIT.testMaxConcurrentJobAllocations` instead of `MlDistributedFailureIT.testJobRelocationIsMemoryAware`.

Both tests that have triggered this are internal cluster tests - maybe there's something special about internal cluster tests that violates the expected invariants of search stats?

**Failure excerpt**:

```
скв 28, 2021 7:37:22 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_t0][search][T#1],5,TGRP-MlDistributedFailureIT]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([1CE7934034A0817E]:0)
	at org.elasticsearch.index.search.stats.ShardSearchStats.lambda$onFetchPhase$5(ShardSearchStats.java:112)
	at org.elasticsearch.index.search.stats.ShardSearchStats.computeStats(ShardSearchStats.java:117)
	at org.elasticsearch.index.search.stats.ShardSearchStats.onFetchPhase(ShardSearchStats.java:109)
	at org.elasticsearch.index.shard.SearchOperationListener$CompositeListener.onFetchPhase(SearchOperationListener.java:178)
	at org.elasticsearch.search.SearchService$SearchOperationListenerExecutor.close(SearchService.java:1415)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:464)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:435)
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:398)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by dnhatn**
We expect the values of CounterMetric to be non-negative when serializing them over the wire, but Yannick discovered that this does not always hold (see https://github.com/elastic/elasticsearch/issues/52411). The reason is that the returned value of a LongAdder is not an atomic snapshot.

We can replace LongAdder with AtomicLong, but this commit continues using LongAdder but returns 0 when the value is negative instead.

Relates #52411
Closes #70968

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/metrics/CounterMetric.java [hunk 1]
```diff
@@ -8,29 +8,48 @@
...
     }
 
     public void dec(long n) {
         counter.add(-n);
+        assert assertNonNegative(assertingCounter.addAndGet(-n));
     }
 
     public long count() {
-        return counter.sum();
+        // Retries up to 5 times as the returned value of LongAdder#sum is NOT an atomic snapshot.
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/common/metrics/CounterMetric.java:46]: why retry here instead of just directly rounding to 0 in case of negative values?

File: server/src/main/java/org/elasticsearch/common/metrics/MeanMetric.java [hunk 2]
```diff
@@ -20,13 +20,10 @@ public void inc(long n) {
         sum.add(n);
     }
 
-    public void dec(long n) {
-        counter.decrement();
-        sum.add(-n);
-    }
-
     public long count() {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/common/metrics/MeanMetric.java:23]: can you add a comment why count is supposed to only return `>= 0`

**Review by ywelsch — COMMENTED** [review]
I've left one question, o.w. looking good (perhaps more docs on the why)

File: server/src/main/java/org/elasticsearch/common/metrics/CounterMetric.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/common/metrics/CounterMetric.java]: I added a comment in https://github.com/elastic/elasticsearch/pull/71446/commits/cb76a362fbd6fa603d91ad91c0ab8ec6938b797f

File: server/src/main/java/org/elasticsearch/common/metrics/MeanMetric.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/common/metrics/MeanMetric.java:23]: added in https://github.com/elastic/elasticsearch/pull/71446/commits/cb76a362fbd6fa603d91ad91c0ab8ec6938b797f

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
Thanks Yannick!
