### PR TITLE
Discovery-ec2 plugin should check `discovery.type`

### LINKED ISSUE #13581: [cloud-aws] info message is displayed when not using ec2 discovery
In 2.0, aws plugin now tries to start immediately ec2 discovery even if we don't set `discovery.type: ec2`.

For example, if you want to use only S3 feature, this message does not make sense:

```
[2015-09-15 16:44:16,336][INFO ][org.elasticsearch.discovery.ec2] [Ocelot] Exception while retrieving instance list from AWS API: Unable to load AWS credentials from any provider in the chain
```

It should not be an issue anymore in 3.0 as aws is split in 2 plugins, so we can guess that if someone installs the discovery-ec2 plugin, it's probably to have discovery set to ec2.

### PR DESCRIPTION
**Pull request by dadoonet**
As done in #13809 and in Azure, we should check that `discovery.type` is set to `ec2` before starting services.

Closes #13581

### CODE REVIEW

File: plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/Ec2Module.java [hunk 1]
```diff
@@ -27,4 +30,18 @@
     protected void configure() {
         bind(AwsEc2Service.class).to(AwsEc2ServiceImpl.class).asEagerSingleton();
     }
+
+    /**
+     * Check if discovery is meant to start
+     * @return true if we can start discovery features
+     */
+    public static boolean isDiscoveryReady(Settings settings, ESLogger logger) {
```
Comment (bleskes) [inline plugins/discovery-ec2/src/main/java/org/elasticsearch/cloud/aws/Ec2Module.java]: can we rename this to `isEc2DiscoveryActive`? ready feels weird given the check. Also, why is this on the module? the plugin uses it , why not just put it there?

**Comment by bleskes** [comment]
left a couple of minor suggestions.

**Comment by dadoonet** [comment]
@bleskes I updated the PR. Let me know.

Marking it as a blocker for 2.0 as we have seen issues in discovery when the old `cloud-aws` is added to a cluster "only for snapshot/restore" purposes.

cc @alexbrasetvik @beiske
