### PR TITLE
[ML] updating rest and HLRC ML tests to wait for no initializing shards & necessary indices

### LINKED ISSUE #71139: [CI] MachineLearningIT testGetTrainedModelsStats failing
This didn't reproduce locally for me, and it's the first instance but I noticed another similar looking failure in `XPackRestIT` `test {p0=ml/pipeline_inference/Test pipeline regression simple}`.

Here's the node log from the other failure indicating shard errors: https://gradle-enterprise.elastic.co/s/g67zgm2dkrkgw/console-log?task=:x-pack:plugin:yamlRestTest#L12890

This test is also failing due to backing shard failures. Related?

**Build scan:**
https://gradle-enterprise.elastic.co/s/3c4qg5eq3qvt4/tests/:client:rest-high-level:asyncIntegTest/org.elasticsearch.client.MachineLearningIT/testGetTrainedModelsStats

**Reproduction line:**
`./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.elasticsearch.client.MachineLearningIT.testGetTrainedModelsStats" -Dtests.seed=D1988407AAFC971E -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Etc/GMT+8 -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.MachineLearningIT&tests.test=testGetTrainedModelsStats

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=Partial shards failure]

  at __randomizedtesting.SeedInfo.seed([D1988407AAFC971E:C9EC9DBCBBF90267]:0)
  at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
  at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
  at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
  at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
  at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
  at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1606)
  at org.elasticsearch.client.MachineLearningClient.deleteTrainedModel(MachineLearningClient.java:2528)
  at org.elasticsearch.client.MlTestStateCleaner.lambda$deleteAllTrainedModels$3(MlTestStateCleaner.java:98)
  at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
  at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
  at org.elasticsearch.client.MlTestStateCleaner.deleteAllTrainedModels(MlTestStateCleaner.java:96)
  at org.elasticsearch.client.MlTestStateCleaner.clearMlMetadata(MlTestStateCleaner.java:58)
  at org.elasticsearch.client.MachineLearningIT.cleanUp(MachineLearningIT.java:228)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by benwtrent**
In the high level rest client tests, we should clean up trained models, same as we do for datafeeds, jobs, etc.

But, to delete a trained model, it needs to not be used in a pipeline, so we grab the model stats. 

This commit does:
- waiting for no more initializing shards when ML integration tests are cleaning up before attempting to delete things
- The specific inference stats test now waits for the `.ml-stats-00001` index to exist before continuing 
- And we make sure that config index is green before attempting to run the `pipeline_inference.yml` tests

closes https://github.com/elastic/elasticsearch/issues/71139

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/MachineLearningIT.java [hunk 1]
```diff
@@ -225,6 +226,7 @@
 
     @After
     public void cleanUp() throws IOException {
+        ensureNoInitializingShards();
```
Comment (benwtrent) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/MachineLearningIT.java:229]: I added this as I didn't see any checks in our cleanup code for this. It just seems prudent.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/MachineLearningIT.java [hunk 2]
```diff
@@ -2528,6 +2529,11 @@ public void testGetTrainedModelsStats() throws Exception {
                     .collect(Collectors.toList()),
                 containsInAnyOrder(modelIdPrefix + 1, modelIdPrefix + 2));
         }
+        highLevelClient().ingest().deletePipeline(new DeletePipelineRequest("regression-stats-pipeline"), RequestOptions.DEFAULT);
+        assertBusy(() -> {
+            assertTrue(indexExists(".ml-stats-000001"));
+            ensureGreen(".ml-stats-*");
+        });
```
Comment (benwtrent) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/MachineLearningIT.java:2536]: This stinks, but it allows the stats to be persisted and makes sure the stats index exists before continuing. This is a slight pain as the stats persistence for trained models is asynchronous.

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/pipeline_inference.yml [hunk 3]
```diff
@@ -99,6 +99,12 @@ setup:
           { "product": "VCR", "cost": 180, "time": 1587501233000 }
           { "index": {} }
           { "product": "Laptop", "cost": 15000, "time": 1587501233000 }
+  - do:
+      headers:
+        Authorization: "Basic eF9wYWNrX3Jlc3RfdXNlcjp4LXBhY2stdGVzdC1wYXNzd29yZA==" # run as x_pack_rest_user, i.e. the test setup superuser
+      cluster.health:
+        index: [".ml-inference-*", ".ml-stats-*"]
+        wait_for_status: green
```
Comment (benwtrent) [inline x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/pipeline_inference.yml:107]: There was another separate test failure where these tests failed because `.ml-inference-000001` shards were not initialized. Seems weird as the earlier PUT worked. But adding this to make sure.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2
