### PR TITLE
[ESQL] Fix TopNSetTestCase test and unmute it

### LINKED ISSUE #129257: [CI] LongTopNSetTests testCrankyBreaker failing
**Build Scans:**
- [elasticsearch-intake #23882 / part3](https://gradle-enterprise.elastic.co/s/f73v22lgesnvg)
- [elasticsearch-pull-request #75044 / part-3](https://gradle-enterprise.elastic.co/s/j5a7bc3h4greu)
- [elasticsearch-pull-request #75038 / part-3](https://gradle-enterprise.elastic.co/s/jkznovguqttnm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.data.sort.LongTopNSetTests.testCrankyBreaker" -Dtests.seed=3E335CE5FF01E2E6 -Dtests.locale=br -Dtests.timezone=America/St_Thomas -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.data.sort.LongTopNSetTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCrankyBreaker),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalArgumentException: -1
```

**Issue Reasons:**
- [main] 3 consecutive failures in test testCrankyBreaker
- [main] 2 consecutive failures in step part-3
- [main] 2 consecutive failures in pipeline elasticsearch-pull-request
- [main] 3 failures in test testCrankyBreaker (75.0% fail rate in 4 executions)
- [main] 2 failures in step part-3 (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Closes https://github.com/elastic/elasticsearch/issues/129257

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java [hunk 1]
```diff
@@ -160,9 +160,10 @@ public final void testReduceLimit() {
             assertResults(sort, sortOrder, limit, values);
 
             reduceLimitByOne(sort);
+            limit--;
             collect(sort, values.get(2));
 
-            assertResults(sort, sortOrder, limit - 1, values);
+            assertResults(sort, sortOrder, limit, values);
```
Comment (GalLalouche) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java]: I'd prefer to pass `limit - 1` here. The less mutation the better :) Also, why did this sometimes pass? Did it only pass if limit was 1 or 0?

**Review by GalLalouche — CHANGES_REQUESTED** [review]

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java]: This test was passing, it was working correctly. I changed this just to be the same as the failing test, which was doing both the `limit--` and the `limit - 1` (The bug).

I'll restore this one. The other still does that, but it needs to track if it was reduced in some way, so reducing the existing limit looks nice to me (?)

Comment (GalLalouche) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java]: Ah, I see. Anyway, since `limit` is only read once after being decremented, I think it's cleaner to pass `limit - 1` instead of mutating the value, but I won't block on that.

**Review by GalLalouche — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/sort/TopNSetTestCase.java]: Reverted! 🐈

**Review by luigidellaquila — APPROVED** [review]
