### PR TITLE
[Test] Wait on master node for shard started

### LINKED ISSUE #131146: [CI] DiskThresholdMonitorIT testFloodStageExceeded failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9318 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/5kdt3bdfopg6m)
- [elasticsearch-periodic-platform-support #9269 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/mdahzpzbtrovu)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitorIT.testFloodStageExceeded" -Dtests.seed=1B9DAE00A0D5567B -Dtests.locale=he -Dtests.timezone=SystemV/CST6 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitorIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testFloodStageExceeded'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected null, but was:<true>
```

**Issue Reasons:**
- [main] 2 failures in test testFloodStageExceeded (0.4% fail rate in 480 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
The shard started may not be visible on the master node if the wait is on a data node. In that case, the DiskThreshold monitor may use stale cluster state for releasing read-only blocks. This PR fixes it by waiting on the master node, which is the behaviour before #129872.

Resolves: #131146

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorIT.java [hunk 1]
```diff
@@ -86,20 +87,12 @@ public void testFloodStageExceeded() throws Exception {
...
-                .shard(0)
-                .primaryShard();
-            assertThat(primaryShard.state(), equalTo(ShardRoutingState.STARTED));
-            assertThat(primaryShard.currentNodeId(), equalTo(newDataNodeId));
+        awaitClusterState(state -> {
+            final ShardRouting primaryShard = state.routingTable(ProjectId.DEFAULT).index(indexName).shard(0).primaryShard();
+            if (primaryShard.state() != ShardRoutingState.STARTED) {
+                return false;
+            }
+            return newDataNodeId.equals(primaryShard.currentNodeId());
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorIT.java]: one-liner suggestion:

```suggestion
            return primaryShard.state() == ShardRoutingState.STARTED && newDataNodeId.equals(primaryShard.currentNodeId());
```

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Review by pxsalehi — APPROVED** [review]

**Comment by ywangd** [comment]
@elasticmachine update branch
