### PR TITLE
[TEST] Fix MLModelDeploymentFullClusterRestartIT {cluster=OLD} Failures

### LINKED ISSUE #146030: [CI] MLModelDeploymentFullClusterRestartIT testDeploymentSurvivesRestart {cluster=OLD} failing
**Build Scans:**
- [elasticsearch-periodic #12167 / 8.1.3_bwc](https://gradle-enterprise.elastic.co/s/egp2522vqv5he)
- [elasticsearch-periodic #12167 / 8.0.1_bwc](https://gradle-enterprise.elastic.co/s/ixresx3jwumhy)
- [elasticsearch-periodic #12167 / 8.1.3_bwc](https://gradle-enterprise.elastic.co/s/mtgp4rsni6voa)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:full-cluster-restart:v8.1.3#bwcTest" -Dtests.class="org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT" -Dtests.method="testDeploymentSurvivesRestart {cluster=OLD}" -Dtests.seed=57B5978223B214B0 -Dtests.bwc=true -Dtests.locale=mi -Dtests.timezone=Australia/Perth -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.restart.MLModelDeploymentFullClusterRestartIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDeploymentSurvivesRestart%20%7Bcluster%3DOLD%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Inference failed on old cluster
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testDeploymentSurvivesRestart {cluster=OLD}
- [main] 2 consecutive failures in step 8.1.3_bwc
- [main] 1 consecutive failures in step 8.0.1_bwc
- [main] 1 consecutive failures in pipeline elasticsearch-periodic
- [main] 3 failures in test testDeploymentSurvivesRestart {cluster=OLD} (0.3% fail rate in 1000 executions)
- [main] 2 failures in step 8.1.3_bwc (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by valeriy42**
The `{cluster=OLD}` variant of `testDeploymentSurvivesRestart` has been failing at 100% on the 8.0.1 and 8.1.3 BWC steps despite two prior fix attempts (#145159, #145690). The root cause is that PyTorch model deployment inference on those very old cluster versions has never been reliable in CI — the feature was experimental in 8.0.x–8.2.x — and the test has been muted for this reason repeatedly since 2022. This PR adds an `assumeTrue` version guard to skip the old-cluster path when the old cluster is before 8.3.0 (where the unified `_infer` endpoint and stable parameter names were introduced), mutes the test while the fix propagates to CI, and removes the now-dead code: the `oldClusterHasInferEndpoint()` helper, the `deployment/_infer` fallback branch, the deprecated `inference_threads`/`model_threads` parameter branching in `startDeployment`, and the response format ternary in `assertInfer`. 

Closes #146030.

### CODE REVIEW

File: x-pack/qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java [hunk 1]
```diff
@@ -147,10 +149,7 @@ private void waitForDeploymentStarted(String modelId) throws Exception {
 
     private void assertInfer(String modelId) throws IOException {
         Response inference = infer("my words", modelId);
-        String expectedResponse = oldClusterHasInferEndpoint()
-            ? "{\"inference_results\":[{\"predicted_value\":[[1.0,1.0]]}]}"
-            : "{\"predicted_value\":[[1.0,1.0]]}";
-        assertThat(EntityUtils.toString(inference.getEntity()), equalTo(expectedResponse));
+        assertThat(EntityUtils.toString(inference.getEntity()), equalTo("{\"inference_results\":[{\"predicted_value\":[[1.0,1.0]]}]}"));
```
Comment (valeriy42) [inline x-pack/qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java:152]: No need to use old syntax, since we don't test on pre-8.3.0 versions.

File: x-pack/qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java [hunk 2]
```diff
@@ -241,15 +224,8 @@ private Response getTrainedModelStats(String modelId) throws IOException {
         return response;
     }
 
-    private boolean oldClusterHasInferEndpoint() {
```
Comment (valeriy42) [inline x-pack/qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java:244]: Removed for simplicity.

**Review by edsavage — APPROVED** [review]
LGTM

**Comment by prwhelan** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/151561)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
