### PR TITLE
[Transform] Fix Missing Config Errors

### LINKED ISSUE #134263: [Transform] Healthy transforms are shown errors on kibana UI: "Found task for transform [...], but no configuration for it. To delete this transform use DELETE with force=true." #1686
In some cases, when running `GET _transform/_all` or through kibana UI (management/data/transform), it shows some transforms are thrown errors:
`Found task for transform [...], but no configuration for it. To delete this transform use DELETE with force=true.`,

However, it could be wrong and false positive, when you run `GET _transform/<transform id>` or `GET _transform/<transform id>/_stats` for the problematic transform, the stats was in green health, and the documents_processed counts are increasing.

We need to figure out what could cause this problem.

### PR DESCRIPTION
**Pull request by prwhelan**
When there are more Transforms than the current page size, GET _transform will mistakenly display an error message `Found task for transform [...], but no configuration for it. To delete this transform use DELETE with force=true.`.

When the page size is smaller than the reported total count of transforms, we will now get all Transform Ids and compare that to the running transforms to generate the dangling tasks error message.

Resolve #134263

-----------------------

Also verified locally, without this change the UI will display this banner:
image

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/GetTransformAction.java [hunk 1]
```diff
@@ -47,24 +51,49 @@ private GetTransformAction() {
...
-            super(null, PageParams.defaultParams(), true);
+        public Request(String id, boolean checkForDanglingTasks, TimeValue timeout) {
+            super(id, PageParams.defaultParams(), true);
+            this.checkForDanglingTasks = checkForDanglingTasks;
+            this.timeout = timeout;
         }
 
         public Request(StreamInput in) throws IOException {
             super(in);
+            this.checkForDanglingTasks = (in.getTransportVersion().onOrAfter(DANGLING_TASKS) == false) || in.readBoolean();
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/GetTransformAction.java]: Could this be rewritten into ternary expression, like the one below (timeout)?
I think it would be easier to comprehend than the || operator relying on short-circuiting?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/GetTransformAction.java [hunk 2]
```diff
@@ -86,6 +115,20 @@ public String getCancelableTaskDescription() {
         public String getResourceIdField() {
             return TransformField.ID.getPreferredName();
         }
+
+        @Override
+        public boolean equals(Object obj) {
+            return this == obj
+                || (obj instanceof Request other
+                    && super.equals(obj)
+                    && Objects.equals(checkForDanglingTasks, other.checkForDanglingTasks)
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/GetTransformAction.java]: Since `checkForDanglingTasks` is of primitive type (`boolean`) I think this could be simplified to "`checkForDanglingTasks == other.checkForDanglingTasks`"

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportGetTransformAction.java [hunk 3]
```diff
@@ -131,7 +151,119 @@ protected QueryBuilder additionalQuery() {
...
+            }),
+            client::search
+        );
+    }
+
+    private static QueryBuilder query(String[] idTokens) {
+        var queryBuilder = QueryBuilders.boolQuery()
+            .filter(QueryBuilders.termQuery(TransformField.INDEX_DOC_TYPE.getPreferredName(), TransformConfig.NAME));
+
+        if (org.elasticsearch.common.Strings.isAllOrWildcard(idTokens) == false) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportGetTransformAction.java:246]: Would it make sense to add a test case for wildcard/_all?

Comment (prwhelan) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportGetTransformAction.java:246]: Half of the calls in `TransformGetAndGetStatsIT` are calling using `_all`, and a few more are calling using the transform id directly, so both use cases should be covered.

**Review by przemekwitek — APPROVED** [review]
LGTM
