### PR TITLE
Fixing test failure #127657

### LINKED ISSUE #127657: [CI] DenseVectorFieldMapperTests testRescoreVectorOldIndexVersion failing
**Build Scans:**
- [elasticsearch-intake #22570 / part1](https://gradle-enterprise.elastic.co/s/e2pqrswvlfkgs)
- [elasticsearch-pull-request #70349 / part-1](https://gradle-enterprise.elastic.co/s/5e7lv65naee5w)
- [elasticsearch-intake #22568 / part1](https://gradle-enterprise.elastic.co/s/ddvkuebl4ola6)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapperTests.testRescoreVectorOldIndexVersion" -Dtests.seed=259C644E7360502E -Dtests.locale=sg-Latn-CF -Dtests.timezone=Etc/Zulu -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapperTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRescoreVectorOldIndexVersion),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception MapperParsingException but no exception was thrown
```

**Issue Reasons:**
- [main] 2 consecutive failures in step part1
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 3 failures in test testRescoreVectorOldIndexVersion (1.7% fail rate in 180 executions)
- [main] 2 failures in step part1 (14.3% fail rate in 14 executions)
- [main] 2 failures in pipeline elasticsearch-intake (14.3% fail rate in 14 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by benwtrent**
I did the old index pattern request poorly.

closes: https://github.com/elastic/elasticsearch/issues/127657

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapperTests.java [hunk 1]
```diff
@@ -904,14 +904,17 @@ public void testRescoreVectorForNonQuantized() {
     }
 
     public void testRescoreVectorOldIndexVersion() {
-        IndexVersion incompatibleVersion = IndexVersionUtils.randomVersionBetween(
-            random(),
+        IndexVersion incompatibleVersion = randomFrom(
```
Comment (svilen-mihaylov-elastic) [inline server/src/test/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapperTests.java:907]: I understand what this is trying to do but it looks a bit confusing to me. Why not the below:

```
IndexVersionUtils.randomVersionBetween(
  random(),
  Version::min(IndexVersionUtils.getLowestReadCompatibleVersion(), IndexVersions.UPGRADE_TO_LUCENE_10_0_0)
  Version::max(IndexVersionUtils.getPreviousVersion(IndexVersions.ADD_RESCORE_PARAMS_TO_QUANTIZED_VECTORS_BACKPORT_8_X), IndexVersionUtils.getPreviousVersion(IndexVersions.ADD_RESCORE_PARAMS_TO_QUANTIZED_VECTORS))
)
```

**Review by svilen-mihaylov-elastic — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapperTests.java (hunk 1 above)
Comment (benwtrent) [reply server/src/test/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapperTests.java:907]: The problem with this is that if somebody adds a new index version for 8.x that is after ADD_RESCORE_PARAMS_TO_QUANTIZED_VECTORS_BACKPORT_8_X, it will have the version capability, but will be a version smaller than  ADD_RESCORE_PARAMS_TO_QUANTIZED_VECTORS. 

This is why its a disjoint version set.
