### PR TITLE
Fix read/write counts for copy in repo analysis

### LINKED ISSUE #126569: [CI] SnapshotRepoTestKitClientYamlTestSuiteIT test {p0=/10_analyze/Analysis without details} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7567 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/r7kqowxarxrfq)
- [elasticsearch-periodic-platform-support #7567 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/3gzqgzyeyo2o6)
- [elasticsearch-pull-request #67187 / part-2](https://gradle-enterprise.elastic.co/s/swn7xxitatqhg)
- [elasticsearch-pull-request #67177 / part-2](https://gradle-enterprise.elastic.co/s/4a74b7lxzmjnm)
- [elasticsearch-periodic #7545 / openjdk23_entitlements_false_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/plncsjz2u7sro)
- [elasticsearch-intake #21609 / part2](https://gradle-enterprise.elastic.co/s/kaqprgl27nguq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:snapshot-repo-test-kit:qa:rest:yamlRestTest" --tests "org.elasticsearch.repositories.blobstore.testkit.rest.SnapshotRepoTestKitClientYamlTestSuiteIT.test {p0=/10_analyze/Analysis without details}" -Dtests.seed=F9E6ECF99D4BE225 -Dtests.locale=it-CH -Dtests.timezone=Pacific/Enderbury -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.blobstore.testkit.rest.SnapshotRepoTestKitClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3D%2F10_analyze%2FAnalysis%20without%20details%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [/10_analyze:82]: 
Expected: <10>
     but: was <9>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test test {p0=/10_analyze/Analysis without details}
- [main] 6 failures in test test {p0=/10_analyze/Analysis without details} (3.2% fail rate in 189 executions)
- [main] 2 failures in step part-2 (2.3% fail rate in 87 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.3% fail rate in 87 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we don't count copies as writes, nor do we make sure to read both
original and copy, so repository analysis sometimes reports having done
fewer reads/writes than requested.

This commit fixes the write counting, and adjusts the read behaviour so
that we always read both original and copy at least once.

Closes #126569

### CODE REVIEW

File: x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/analyze/BlobAnalyzeAction.java [hunk 1]
```diff
@@ -251,9 +251,11 @@ private static class BlobAnalysis {
...
         private final List<DiscoveryNode> earlyReadNodes;
         private final List<DiscoveryNode> readNodes;
-        private final GroupedActionListener<NodeResponse> readNodesListener;
-        private final ListenableFuture<WriteDetails> write1Step = new ListenableFuture<>();
-        private final ListenableFuture<WriteDetails> write2Step = new ListenableFuture<>();
+        private final List<DiscoveryNode> readCopyNodes;
+        private final List<NodeResponse> nodeResponses;
+        private final RefCountingListener readNodesListeners;
+        private final SubscribableListener<WriteDetails> write1Step = new SubscribableListener<>();
+        private final SubscribableListener<WriteDetails> write2Step = new SubscribableListener<>();
```
Comment (DaveCTurner) [inline x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/analyze/BlobAnalyzeAction.java]: Changing from a `GroupedActionListener` to a `RefCountingListener` here because really it was getting pretty convoluted to make sure we always completed exactly the right number of listeners. Causes some knock-on effects because of having to keep a ref around until we send the actual read requests.

File: x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/analyze/RepositoryAnalyzeAction.java [hunk 2]
```diff
@@ -519,15 +519,17 @@ public void run() {
                 final long targetLength = blobSizes.get(i);
                 final boolean smallBlob = targetLength <= MAX_ATOMIC_WRITE_SIZE; // avoid the atomic API for larger blobs
                 final boolean abortWrite = smallBlob && request.isAbortWritePermitted() && rarely(random);
-                final boolean doCopy = minClusterTransportVersion.supports(REPO_ANALYSIS_COPY_BLOB) && rarely(random) && i > 0;
+                final boolean doCopy = minClusterTransportVersion.supports(REPO_ANALYSIS_COPY_BLOB) && rarely(random) && i < blobCount - 1;
```
Comment (DaveCTurner) [inline x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/analyze/RepositoryAnalyzeAction.java:522]: Changing `i > 0` to `i < blobCount - 1` so that we always create exactly the right number of blobs - avoids making a copy on the last one.

**Comment by mhl-b** [comment]
I had a first look. Need another one. First impression that there is too much randomization happening in the middle of the code, for example: doCopy, earlyRead, writeAndOverwrite, abortWrite. Hard to draw any conclusions in the final assertion by counting writes and reads. 

Would be nice to bound randomness to the analysis request (I guess add more arguments) and then construct predetermined plan which blobs to copy, earlyRead, etc.

**Comment by DaveCTurner** [comment]
Yeah I've never liked this implementation much, I opened #140098 to simplify it. I propose we do that and then apply this fix to `main`, and in earlier versions leave the implementation alone and weaken the test as in #140079.

**Comment by DaveCTurner** [comment]
This is ready for another look @mhl-b

**Review by mhl-b — APPROVED** [review]
LGTM
