### PR TITLE
ESQL: Skip unsupported grapheme cluster test

### LINKED ISSUE #114535: [CI] EsqlSpecIT test {string.ReverseGraphemeClusters ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic #4367 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/hi2kajpqi5bcs)
- [elasticsearch-periodic #4367 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/f5e7whta3swse)
- [elasticsearch-periodic #4367 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/hgtv5hhzipuc4)
- [elasticsearch-periodic #4363 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/cvzdm3tkbkns6)
- [elasticsearch-periodic #4363 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/mju2gkje2lpri)
- [elasticsearch-periodic #4363 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/xjeizyk6iwyzg)
- [elasticsearch-periodic #4359 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/ypdzwjdpcdegc)
- [elasticsearch-periodic #4359 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/w42xs3s54hau2)
- [elasticsearch-periodic #4359 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/u7dfrjrkvpen2)
- [elasticsearch-periodic #4355 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/q3eaiz6qt3mbs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {string.ReverseGraphemeClusters ASYNC}" -Dtests.seed=3F37804BD9C05A68 -Dtests.locale=mk-Cyrl-MK -Dtests.timezone=America/Iqaluit -Druntime.java=17
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bstring.ReverseGraphemeClusters%20ASYNC%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Data mismatch:
row 0 column 1:a list containing
row 0 column 1:0: expected "ठाीकं💖🎉👍🏽😊ûôîêâùòìèàúóíéá" but was "ीठाकं💖🎉🏽👍😊ûôîêâùòìèàúóíéá"
```

**Issue Reasons:**
- [8.x] 17 consecutive failures in step graalvm-ce17_checkpart3_java-matrix
- [8.x] 17 consecutive failures in step openjdk17_checkpart3_java-matrix
- [8.x] 17 consecutive failures in step openjdk17_checkpart3_java-fips-matrix
- [8.x] 51 failures in test test {string.ReverseGraphemeClusters ASYNC} (8.7% fail rate in 586 executions)
- [8.x] 17 failures in step graalvm-ce17_checkpart3_java-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in step openjdk17_checkpart3_java-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in step openjdk17_checkpart3_java-fips-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in pipeline elasticsearch-periodic (100.0% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114536: [CI] EsqlSpecIT test {string.ReverseGraphemeClusters SYNC} failing
**Build Scans:**
- [elasticsearch-periodic #4367 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/hi2kajpqi5bcs)
- [elasticsearch-periodic #4367 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/f5e7whta3swse)
- [elasticsearch-periodic #4367 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/hgtv5hhzipuc4)
- [elasticsearch-periodic #4363 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/cvzdm3tkbkns6)
- [elasticsearch-periodic #4363 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/mju2gkje2lpri)
- [elasticsearch-periodic #4363 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/xjeizyk6iwyzg)
- [elasticsearch-periodic #4359 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/ypdzwjdpcdegc)
- [elasticsearch-periodic #4359 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/w42xs3s54hau2)
- [elasticsearch-periodic #4359 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/u7dfrjrkvpen2)
- [elasticsearch-periodic #4355 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/q3eaiz6qt3mbs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {string.ReverseGraphemeClusters ASYNC}" -Dtests.seed=3F37804BD9C05A68 -Dtests.locale=mk-Cyrl-MK -Dtests.timezone=America/Iqaluit -Druntime.java=17
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bstring.ReverseGraphemeClusters%20SYNC%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Data mismatch:
row 0 column 1:a list containing
row 0 column 1:0: expected "ठाीकं💖🎉👍🏽😊ûôîêâùòìèàúóíéá" but was "ीठाकं💖🎉🏽👍😊ûôîêâùòìèàúóíéá"
```

**Issue Reasons:**
- [8.x] 17 consecutive failures in step graalvm-ce17_checkpart3_java-matrix
- [8.x] 17 consecutive failures in step openjdk17_checkpart3_java-matrix
- [8.x] 17 consecutive failures in step openjdk17_checkpart3_java-fips-matrix
- [8.x] 51 failures in test test {string.ReverseGraphemeClusters SYNC} (8.7% fail rate in 586 executions)
- [8.x] 17 failures in step graalvm-ce17_checkpart3_java-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in step openjdk17_checkpart3_java-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in step openjdk17_checkpart3_java-fips-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in pipeline elasticsearch-periodic (100.0% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114537: [CI] CsvTests test {string.ReverseGraphemeClusters} failing
**Build Scans:**
- [elasticsearch-periodic #4367 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/hi2kajpqi5bcs)
- [elasticsearch-periodic #4367 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/f5e7whta3swse)
- [elasticsearch-periodic #4367 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/hgtv5hhzipuc4)
- [elasticsearch-periodic #4363 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/cvzdm3tkbkns6)
- [elasticsearch-periodic #4363 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/mju2gkje2lpri)
- [elasticsearch-periodic #4363 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/xjeizyk6iwyzg)
- [elasticsearch-periodic #4359 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/ypdzwjdpcdegc)
- [elasticsearch-periodic #4359 / openjdk17_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/w42xs3s54hau2)
- [elasticsearch-periodic #4359 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/u7dfrjrkvpen2)
- [elasticsearch-periodic #4355 / graalvm-ce17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/q3eaiz6qt3mbs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {string.ReverseGraphemeClusters}" -Dtests.seed=3F37804BD9C05A68 -Dtests.locale=fr-CG -Dtests.timezone=Europe/Jersey -Druntime.java=17
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bstring.ReverseGraphemeClusters%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.CsvTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Data mismatch:
row 0 column 1:a list containing
row 0 column 1:0: expected "ठाीकं💖🎉👍🏽😊ûôîêâùòìèàúóíéá" but was "ीठाकं💖🎉🏽👍😊ûôîêâùòìèàúóíéá"
```

**Issue Reasons:**
- [8.x] 17 consecutive failures in step graalvm-ce17_checkpart3_java-matrix
- [8.x] 17 consecutive failures in step openjdk17_checkpart3_java-matrix
- [8.x] 17 consecutive failures in step openjdk17_checkpart3_java-fips-matrix
- [8.x] 51 failures in test test {string.ReverseGraphemeClusters} (8.1% fail rate in 631 executions)
- [8.x] 17 failures in step graalvm-ce17_checkpart3_java-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in step openjdk17_checkpart3_java-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in step openjdk17_checkpart3_java-fips-matrix (100.0% fail rate in 17 executions)
- [8.x] 17 failures in pipeline elasticsearch-periodic (100.0% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114558: [CI] MixedClusterEsqlSpecIT test {string.ReverseGraphemeClusters ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic #4529 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/z2zzi7iljalwe)
- [elasticsearch-periodic #4529 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/vqd4alccsljeq)
- [elasticsearch-periodic #4529 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/x43i5q7ngiwrm)
- [elasticsearch-periodic #4524 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/h7zjwpg5xoayg)
- [elasticsearch-periodic #4524 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/cbtk3rylw2uu6)
- [elasticsearch-periodic #4524 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/fty7xficsvo5u)
- [elasticsearch-periodic #4519 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/or7p4jtlfuzum)
- [elasticsearch-periodic #4519 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/oqbmyw5wlhfko)
- [elasticsearch-periodic #4519 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/dzu2hc5dfuous)
- [elasticsearch-periodic #4514 / graalvm-ce17_8.16.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/kmkrag37mzdta)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.17.0#javaRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT" -Dtests.method="test {string.ReverseGraphemeClusters SYNC}" -Dtests.seed=428BE8C14B179B81 -Dtests.bwc=true -Dtests.locale=mi-NZ -Dtests.timezone=HST -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bstring.ReverseGraphemeClusters%20ASYNC%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Data mismatch:
row 0 column 1:a list containing
row 0 column 1:0: expected "ठाीकं💖🎉👍🏽😊ûôîêâùòìèàúóíéá" but was "ीठाकं💖🎉🏽👍😊ûôîêâùòìèàúóíéá"
```

**Issue Reasons:**
- [8.x] 6 consecutive failures in test test {string.ReverseGraphemeClusters ASYNC}
- [8.x] 18 consecutive failures in step openjdk17_8.17.0_java-fips-matrix-bwc
- [8.x] 18 consecutive failures in step openjdk17_8.17.0_java-matrix-bwc
- [8.x] 18 consecutive failures in step graalvm-ce17_8.17.0_java-matrix-bwc
- [8.x] 4 consecutive failures in step graalvm-ce17_8.16.0_java-matrix-bwc
- [8.x] 3 consecutive failures in pipeline elasticsearch-periodic
- [8.x] 84 failures in test test {string.ReverseGraphemeClusters ASYNC} (14.7% fail rate in 572 executions)
- [8.x] 18 failures in step openjdk17_8.17.0_java-fips-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step openjdk17_8.17.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step graalvm-ce17_8.17.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 7 failures in step openjdk17_8.16.0_java-fips-matrix-bwc (38.9% fail rate in 18 executions)
- [8.x] 14 failures in step graalvm-ce17_8.16.0_java-matrix-bwc (77.8% fail rate in 18 executions)
- [8.x] 9 failures in step openjdk17_8.16.0_java-matrix-bwc (50.0% fail rate in 18 executions)
- [8.x] 21 failures in pipeline elasticsearch-periodic (100.0% fail rate in 21 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114559: [CI] MixedClusterEsqlSpecIT test {string.ReverseGraphemeClusters SYNC} failing
**Build Scans:**
- [elasticsearch-periodic #4529 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/z2zzi7iljalwe)
- [elasticsearch-periodic #4529 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/vqd4alccsljeq)
- [elasticsearch-periodic #4529 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/x43i5q7ngiwrm)
- [elasticsearch-periodic #4524 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/h7zjwpg5xoayg)
- [elasticsearch-periodic #4524 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/cbtk3rylw2uu6)
- [elasticsearch-periodic #4524 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/fty7xficsvo5u)
- [elasticsearch-periodic #4519 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/or7p4jtlfuzum)
- [elasticsearch-periodic #4519 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/oqbmyw5wlhfko)
- [elasticsearch-periodic #4519 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/dzu2hc5dfuous)
- [elasticsearch-periodic #4514 / openjdk17_8.16.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/gmggyrc34pbic)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.17.0#javaRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT" -Dtests.method="test {string.ReverseGraphemeClusters SYNC}" -Dtests.seed=428BE8C14B179B81 -Dtests.bwc=true -Dtests.locale=mi-NZ -Dtests.timezone=HST -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bstring.ReverseGraphemeClusters%20SYNC%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Data mismatch:
row 0 column 1:a list containing
row 0 column 1:0: expected "ठाीकं💖🎉👍🏽😊ûôîêâùòìèàúóíéá" but was "ीठाकं💖🎉🏽👍😊ûôîêâùòìèàúóíéá"
```

**Issue Reasons:**
- [8.x] 6 consecutive failures in test test {string.ReverseGraphemeClusters SYNC}
- [8.x] 18 consecutive failures in step openjdk17_8.17.0_java-fips-matrix-bwc
- [8.x] 18 consecutive failures in step openjdk17_8.17.0_java-matrix-bwc
- [8.x] 18 consecutive failures in step graalvm-ce17_8.17.0_java-matrix-bwc
- [8.x] 3 consecutive failures in pipeline elasticsearch-periodic
- [8.x] 82 failures in test test {string.ReverseGraphemeClusters SYNC} (14.3% fail rate in 572 executions)
- [8.x] 18 failures in step openjdk17_8.17.0_java-fips-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step openjdk17_8.17.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step graalvm-ce17_8.17.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 9 failures in step openjdk17_8.16.0_java-fips-matrix-bwc (50.0% fail rate in 18 executions)
- [8.x] 10 failures in step graalvm-ce17_8.16.0_java-matrix-bwc (55.6% fail rate in 18 executions)
- [8.x] 9 failures in step openjdk17_8.16.0_java-matrix-bwc (50.0% fail rate in 18 executions)
- [8.x] 21 failures in pipeline elasticsearch-periodic (100.0% fail rate in 21 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114560: [CI] MultiClusterSpecIT test {string.ReverseGraphemeClusters} failing
**Build Scans:**
- [elasticsearch-periodic #4529 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/z2zzi7iljalwe)
- [elasticsearch-periodic #4529 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/vqd4alccsljeq)
- [elasticsearch-periodic #4529 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/x43i5q7ngiwrm)
- [elasticsearch-periodic #4524 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/h7zjwpg5xoayg)
- [elasticsearch-periodic #4524 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/cbtk3rylw2uu6)
- [elasticsearch-periodic #4524 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/fty7xficsvo5u)
- [elasticsearch-periodic #4519 / openjdk17_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/or7p4jtlfuzum)
- [elasticsearch-periodic #4519 / openjdk17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/oqbmyw5wlhfko)
- [elasticsearch-periodic #4519 / graalvm-ce17_8.17.0_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/dzu2hc5dfuous)
- [elasticsearch-periodic #4514 / openjdk17_8.16.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/bnfo3e5rvxhqs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v8.17.0#bwcTest" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {string.ReverseGraphemeClusters}" -Dtests.seed=428BE8C14B179B81 -Dtests.bwc=true -Dtests.locale=jv -Dtests.timezone=SystemV/YST9YDT -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bstring.ReverseGraphemeClusters%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Data mismatch:
row 0 column 1:a list containing
row 0 column 1:0: expected "ठाीकं💖🎉👍🏽😊ûôîêâùòìèàúóíéá" but was "ीठाकं💖🎉🏽👍😊ûôîêâùòìèàúóíéá"
```

**Issue Reasons:**
- [8.x] 6 consecutive failures in test test {string.ReverseGraphemeClusters}
- [8.x] 18 consecutive failures in step openjdk17_8.17.0_java-fips-matrix-bwc
- [8.x] 18 consecutive failures in step openjdk17_8.17.0_java-matrix-bwc
- [8.x] 18 consecutive failures in step graalvm-ce17_8.17.0_java-matrix-bwc
- [8.x] 18 consecutive failures in step openjdk17_8.16.0_java-fips-matrix-bwc
- [8.x] 18 consecutive failures in step graalvm-ce17_8.16.0_java-matrix-bwc
- [8.x] 18 consecutive failures in step openjdk17_8.16.0_java-matrix-bwc
- [8.x] 3 consecutive failures in pipeline elasticsearch-periodic
- [8.x] 108 failures in test test {string.ReverseGraphemeClusters} (18.8% fail rate in 574 executions)
- [8.x] 18 failures in step openjdk17_8.17.0_java-fips-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step openjdk17_8.17.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step graalvm-ce17_8.17.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step openjdk17_8.16.0_java-fips-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step graalvm-ce17_8.16.0_java-matrix-bwc (100.0% fail rate in 18 executions)
- [8.x] 18 failures in step openjdk17_8.16.0_java-matrix-bwc (100.0% fail rate in 18 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nik9000**
This skips the test for reversing grapheme clusters if the node doesn't support reversing grapheme clusters. Nodes that are using a jdk before 20 won't support reversing grapheme clusters because they don't have https://bugs.openjdk.org/browse/JDK-8292387

This reworks `EsqlCapabilities` so we can easilly register it only if we're on jdk 20:
```
FN_REVERSE_GRAPHEME_CLUSTERS(Runtime.version().feature() < 20),
```

Closes #114537
Closes #114535
Closes #114536
Closes #114558
Closes #114559
Closes #114560

### CODE REVIEW

**Comment by nik9000** [comment]
NOTE: This is targeting 8.x and I'll manually forward port a big chunk of it into `main` and backport all of it to `8.16`. I targeting 8.x because that's a version that can fail the test.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -32,6 +32,12 @@ public enum Cap {
          */
         FN_REVERSE,
 
+        /**
+         * Support for reversing whole grapheme clusters. This is not supported
+         * on JDK versions less than 20.
+         */
+        FN_REVERSE_GRAPHEME_CLUSTERS(Runtime.version().feature() < 20),
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:39]: 👍

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/Reverse.java [hunk 2]
```diff
@@ -46,7 +46,11 @@ public class Reverse extends UnaryScalarFunction {
                 file = "string",
                 tag = "reverseEmoji",
                 description = "`REVERSE` works with unicode, too! It keeps unicode grapheme clusters together during reversal."
-            ) }
+            ) },
+        note = """
+            If Elasticsearch is running with a JDK version less than 20 then this will not properly reverse Grapheme Clusters.
+            Elastic Cloud the JDK bundled with Elasticsearch all use newer JDKs. But if you've explicitly shifted to an older jdk
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/Reverse.java:52]:
```suggestion
            Elastic Cloud and the JDK bundled with Elasticsearch all use newer JDKs. But if you've explicitly shifted to an older jdk
```

**Review by bpintea — APPROVED** [review]

**Comment by nik9000** [comment]
Forward port to main: 115321

**Comment by nik9000** [comment]
Merged!
