### PR TITLE
Fix testInvalidJoinPatterns

### LINKED ISSUE #129598: [CI] StatementParserTests testInvalidJoinPatterns failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8832 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/pez5ke33pm3fm)
- [elasticsearch-periodic-platform-support #8826 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/nruhmc3ydl4wk)
- [elasticsearch-intake #24175 / part3](https://gradle-enterprise.elastic.co/s/gcfmh3fqulzra)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.parser.StatementParserTests.testInvalidJoinPatterns" -Dtests.seed=E51A2A6622A94895 -Dtests.locale=ccp-BD -Dtests.timezone=America/Maceio -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.parser.StatementParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testInvalidJoinPatterns),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Query [FROM npoxdexsprox:-<ms5ipzf-h!zfiqc26uio*-{now/M-1M{yyyy.MM}}> | LOOKUP JOIN dlhmhbrel:""""<.nu^'cy&!it46ay^lhm23kwbkyv!0qrz*-{now/M{yyyy.MM.dd|-15:00}}>::data""",<.e*okgu6-{now/M{yyyy.MM}}>,-<.28s7a4f-{now/M{yyyy.MM}}>::failures,.fr'0^06!d.476x8$lj" ON znbhitpbcp] is expected to throw class org.elasticsearch.xpack.esql.parser.ParsingException with message [expecting UNQUOTED_SOURCE]
Expected: a string containing "expecting UNQUOTED_SOURCE"
     but: was "line 1:163: token recognition error at: ','"
```

**Issue Reasons:**
- [main] 3 failures in test testInvalidJoinPatterns (1.2% fail rate in 246 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by idegtiarenko**
According to the report, the test was accidentally generating nested quotes such as:
```
dlhmhbrel:""""<.nu^'cy&!it46ay^lhm23kwbkyv!0qrz*-{now/M{yyyy.MM.dd|-15:00}}>::data"""
```
due to date math expressions. 
Those are not necessary in this test case and could be excluded.

Closes: #129598

### CODE REVIEW

**Review by pawankartik-elastic — DISMISSED** [review]
Yikes, thanks for flagging this!

**Comment by pawankartik-elastic** [comment]
I think the right way to fix this is to not quote if the expression is already quoted due to datemath; rather than excluding them. Wdyt? If you find this acceptable, I'll push the fix to this branch.
Edit: Ref Alex's comment.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 1]
```diff
@@ -3205,7 +3205,7 @@ public void testInvalidJoinPatterns() {
         {
             var fromPatterns = randomIndexPattern();
             // Generate a syntactically invalid (partial quoted) pattern.
-            var joinPattern = randomIdentifier() + ":" + quote(randomIndexPatterns(without(CROSS_CLUSTER)));
+            var joinPattern = randomIdentifier() + ":" + quote(randomIndexPatterns(without(CROSS_CLUSTER), without(DATE_MATH)));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: I think the problem is that we use `randomIndexPatterns` (plural!). Date math should be fine in this test - why do we specifically exclude it?

Shouldn't the fix just be to use `randomIndexPattern` (singular)? That also seems to be consistent with the error message on https://github.com/elastic/elasticsearch/issues/129598:
```
token recognition error at: ','"
```

Comment (pawankartik-elastic) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: Oh, yes. This actually makes sense. I don't know why I used `randomIndexPatterns()` (likely wanted to use `randomIndexPattern()`) and was wondering what the issue with the nested quoting was since the original tests did actually use nested quoting. Even my code comment says "pattern" specifically. Should I push the changes?

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: Update: sorry, actually multiple index patterns would also be fine to test - although I'm not sure this is the original intention.

The problem seems to be the double quoting, because `randomIndexPatterns` has a `maybeQuote` in there, but we always quote the output - potentially another time.

My comment that I don't see how this relates to date math still holds IMO, but I may not be seeing something - randomization over many cases can be funny :)

Comment (pawankartik-elastic) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: Another bug that may cause an issue in the future: `randomIndexPatterns()` uses `maybeQuote()`. Shouldn't it be `quote()` considering we now prohibit partial quoting? Or else, we'll end up generating: `"a",b,c`.

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:3208]: `randomIndexPatterns` quotes the whole thing, this should be fine, I think?

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: `maybeQuote` only quotes if the patterns don't contain a single `"`, so this is fine.

**Comment by alex-spies** [comment]
@idegtiarenko , Pawan and I dissected the error message a bit offline. I still believe it's the double quoting.

```
Notice the 4 quotes:
""""<.nu^'cy&!it46ay^lhm23kwbkyv!0qrz*-{now/M{yyyy.MM.dd|-15:00}}>::data""",<.e*okgu6-{now/M{yyyy.MM}}>,-<.28s7a4f-{now/M{yyyy.MM}}>::failures,.fr'0^06!d.476x8$lj"

What I think the lexer sees:
"""
"<.nu^'cy&!it46ay^lhm23kwbkyv!0qrz*-{now/M{yyyy.MM.dd|-15:00}}>::data
"""
,<.e*okgu6-{now/M{yyyy.MM}}>,-<.28s7a4f-{now/M{yyyy.MM}}>::failures,.fr'0^06!d.476x8$lj"
The parser doesn't expect any token that starts with a comma here.

But we double quoted mistakenly:
"
"""<.nu^'cy&!it46ay^lhm23kwbkyv!0qrz*-{now/M{yyyy.MM.dd|-15:00}}>::data""",<.e*okgu6-{now/M{yyyy.MM}}>,-<.28s7a4f-{now/M{yyyy.MM}}>::failures,.fr'0^06!d.476x8$lj
"
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java (hunk 1 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: > Shouldn't the fix just be to use randomIndexPattern (singular)

Makes sense! Updated to singular and this seems to not fail after couple of thousands of iterations.

**Review by alex-spies — APPROVED** [review]
LGTM, thanks @idegtiarenko !

**Review by pawankartik-elastic — APPROVED** [review]
