### PR TITLE
Only run retention lease actions on active primary

### LINKED ISSUE #40089: [CI] Multiple failures in CcrRetentionLeaseIT
Possibly related to #39509

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/2350/console

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=377894C8C7910121 \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT \
  -Dtests.method="testRetentionLeasesAreNotBeingRenewedAfterRecoveryCompletes" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
  -Dtests.timezone=GMT0 \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=377894C8C7910121 \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT \
  -Dtests.method="testUnfollowFailsToRemoveRetentionLeases" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
  -Dtests.timezone=GMT0 \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=377894C8C7910121 \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT \
  -Dtests.method="testRetentionLeaseRenewedWhileFollowing" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
  -Dtests.timezone=GMT0 \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=377894C8C7910121 \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT \
  -Dtests.method="testRetentionLeaseIsAddedIfItDisappearsWhileFollowing" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
  -Dtests.timezone=GMT0 \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

A number of errors like:

```
java.lang.AssertionError: CreateIndexResponse failed - index creation acked but not all shards were started
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:125)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseIsAddedIfItDisappearsWhileFollowing(CcrRetentionLeaseIT.java:759)


java.lang.AssertionError: CreateIndexResponse failed - index creation acked but not all shards were started
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:125)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testUnfollowRemovesRetentionLeases(CcrRetentionLeaseIT.java:379)

java.lang.AssertionError: CreateIndexResponse failed - index creation acked but not all shards were started
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:125)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testForgetFollower(CcrRetentionLeaseIT.java:931)

com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=47, name=elasticsearch[leaderd4][transport_worker][T#2], state=RUNNABLE, group=TGRP-CcrRetentionLeaseIT]
Caused by: java.lang.AssertionError: shard [leader][0], node[xAJZZ5hpRLCJklizBkx0uw], [P], recovery_source[new shard recovery], s[INITIALIZING], a[id=MYU37kVrQOiBS8JDjMLVJA], unassigned_info[[reason=INDEX_CREATED], at[2019-03-15T02:17:39.163Z], delayed=false, allocation_status[no_attempt]] is not a primary shard in primary mode
	at __randomizedtesting.SeedInfo.seed([377894C8C7910121]:0)
	at org.elasticsearch.index.shard.IndexShard.assertPrimaryMode(IndexShard.java:1576)
	at org.elasticsearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:1974)
	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:217)
	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:193)
	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:103)
	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:98)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2503)
	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:97)
	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:59)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:299)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:292)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1073)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1032)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:918)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753)
	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:780)
	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:241)
	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:213)
	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:47)
	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119)
	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:121)
	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:397)
	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172)
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129)
	at java.lang.Thread.run(Thread.java:748)
```

[The full test log](https://github.com/elastic/elasticsearch/files/2970878/test_log.txt)

### LINKED ISSUE #40373: Failure during rolling-upgrade-multi-cluster:v6.7.0#leader#twoThirdsUpgradedTestCluster due to AssertionError
Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+periodic/246/console

This one didn't come with a reproduce line and isn't associated with a single test as far as I can tell, it happens in:
`:x-pack:qa:rolling-upgrade-multi-cluster:v6.7.0#leader#twoThirdsUpgradedTestCluster#wait`

Where getting `http://[::1]:35123/_cluster/health?wait_for_nodes=>=1&wait_for_status=yellow` fails.  The most relevant part of the stack trace appears to be tripping a real assertion:
```

\|    [2019-03-22T15:38:28,583][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-leader-1] fatal error in thread [Thread-5], exiting
--
\|    java.lang.AssertionError: shard [leader_index3][0], node[Tx87M0psSTKfxswOcbbGWg], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=RKhAp1RsT7Sm0xjVE8WfKQ], unassigned_info[[reason=NODE_LEFT], at[2019-03-22T15:37:55.999Z], delayed=true, details[node_left [Tx87M0psSTKfxswOcbbGWg]], allocation_status[fetching_shard_data]] is not a primary shard in primary mode
\|    	at org.elasticsearch.index.shard.IndexShard.assertPrimaryMode(IndexShard.java:1581) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:1979) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:217) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:193) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:103) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:98) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2512) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:97) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:59) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:299) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:292) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1071) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1030) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:916) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:751) ~[elasticsearch-7.1.0-SNAPSHOT.jar:7.1.0-SNAPSHOT]
\|    	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
\|    	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
\|    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
\|    	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
\|    	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
\|    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
\|    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
\|    	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
\|    	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
\|    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
\|    	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
\|    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
\|    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
\|    	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]


```

### PR DESCRIPTION
**Pull request by jasontedor**
In some cases, a request to perform a retention lease action can arrive on a primary shard before it is active. In this case, the primary shard would not yet be in primary mode, tripping an assertion in the replication tracker. Instead, we should not attempt to perform such actions on an initializing shard. This commit addresses this by not returning the primary shard in the single shard iterator if the primary shard is not yet active.

Closes #40089
Closes #40373

### CODE REVIEW

**Comment by jasontedor** [comment]
Another option that I considered is rejecting this when acquiring the permit on a shard that is not yet active, but this approach seems preferable to me (note that we manually handle inactive shards elsewhere, such as in the reroute phase of a replication action).

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java [hunk 1]
```diff
@@ -84,10 +87,14 @@
 
         @Override
         protected ShardsIterator shards(final ClusterState state, final InternalRequest request) {
-            return state
+            final IndexShardRoutingTable shardRoutingTable = state
                     .routingTable()
-                    .shardRoutingTable(request.concreteIndex(), request.request().getShardId().id())
-                    .primaryShardIt();
+                    .shardRoutingTable(request.concreteIndex(), request.request().getShardId().id());
+            if (shardRoutingTable.primaryShard().active()) {
```
Comment (bleskes) [inline server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java]: TransportSingleShardAction doesn't do our usual "chase the shard" pattern where we re-resolve shards on each node until we find a place where the shard is locally available. This means that if the coordinating node thinks the shard is active but the node with the shard didn't yet process the shard activation cluster state, I think this still goes wrong (i.e., the primary would not be in primary mode, which is [activated](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L482) when the cluster state is processed). I hope I'm wrong and please let me know what I'm missing.

Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java]: Good catch. In this case, I think that we should use the other approach that I [considered](
https://github.com/elastic/elasticsearch/pull/40386#issuecomment-475794196). I can not think of any situations where we would want to acquire a permit on a non-active primary?

Comment (bleskes) [reply server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java]: That was actually why I went looking - my instinct was that this should be done under permit and that the permit shouldn't be given under a non-initialized primary. We currently don't do that so that requires a much bigger change/vision. We can also have a targeted-check in asyncShardOperation that the shard is active before performing the operation.  @ywelsch any thoughts?

**Comment by jasontedor** [comment]
I thought about the targeted check there but I realized earlier there is another operation prone to this problem: forget follower which is not a single shard action. That’s why I now lean towards a global approach.

File: server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java (hunk 1 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java]: `RetentionLeaseActions` and `TransportForgetFollowerAction` can also possibly violate the assertion in `acquirePrimaryOperationPermit` that the shard is actually a primary (by the time  the request arrives, the primary could have failed and a replica allocated instead). Ensuring this was previously left to the caller of this method.

We can explore changing `acquirePrimaryOperationPermit` and `acquireAllPrimaryOperationsPermits` to throw appropriate exceptions if the shard is not in primary mode (e.g. replica or initializing/relocated primary). TRA can then react to an `IndexShardRelocatedException` to delegate to the relocation target.

Comment (bleskes) [reply server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java]: That takes it one level higher - ensuring that the primary is actually an active primary (rather than just an active shard). SGTM.

**Comment by dnhatn** [comment]
A failure relating to this: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc-tests/60/console.

```
[2019-05-20T02:35:56,265][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-leader-0] fatal error in thread [Thread-4], exiting
|    java.lang.AssertionError: shard [leader_index3][0], node[K_dcaDtcTlSLJ76pP0Wz8g], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=Ebf14YQsQkaXCWdL38NFKQ], unassigned_info[[reason=NODE_LEFT], at[2019-05-20T02:35:36.628Z], delayed=true, details[node_left [K_dcaDtcTlSLJ76pP0Wz8g]], allocation_status[fetching_shard_data]] is not a primary shard in primary mode
|        at org.elasticsearch.index.shard.IndexShard.assertPrimaryMode(IndexShard.java:1632) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:2030) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:248) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:222) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:115) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:110) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:273) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:240) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2561) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:109) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:65) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:296) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
|        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:289) ~[elasticsearch-6.8.0-SNAPSHOT.jar:6.8.0-SNAPSHOT]
```

@jasontedor @ywelsch I think we need to act on this.
