### PR TITLE
Fix '_terms_enum' on docvalue-only keywords fields

### LINKED ISSUE #94673: Exception in `_terms_enum` on docvalue-only keywords fields
### Elasticsearch Version

8.6.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Mac OS X

### Problem Description

Running a "_terms_enum" request on a `keyword` field with `index: false` setting can very likely throws UnsupportedOperationException.

This happens under two conditions. The field queries by the "_terms_enum" has index disabled ("index" : false),
which means its docvalues only. This isn't the default but could happen.
The second condition is that a shard has more than one segment. The code path that is then executed throws the following exception
```
java.lang.UnsupportedOperationException
	at org.elasticsearch.server@8.6.2/org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType$SortedSetDocValuesTerms.hasFreqs(KeywordFieldMapper.java:664)
	at org.apache.lucene.core@9.4.2/org.apache.lucene.index.MultiTerms.<init>(MultiTerms.java:56)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType$SortedSetDocValuesTerms.getTerms(KeywordFieldMapper.java:618)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType.getTerms(KeywordFieldMapper.java:537)
	at org.elasticsearch.xcore@8.6.2/org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.dataNodeOperation(TransportTermsEnumAction.java:355)
	at org.elasticsearch.xcore@8.6.2/org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.lambda$asyncNodeOperation$1(TransportTermsEnumAction.java:733)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:50)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:47)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Steps to Reproduce

```
DELETE my-index

PUT /my-index
{
  "mappings": {
    "properties": {
      "foo": {
        "type": "keyword",
        "index" : "false"
      }
    }
  }
}


// run the following a couple of times to add a few documents, each with a bit of delay so we likely roll over into a new segment
// when the default refresh interval of 1s is used
POST my-index/_doc
{
  "foo": "hello"
}

POST /my-index/_terms_enum
{
  "field": "foo"
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by cbuescher**
Running a "_terms_enum" request on a keyword field with "index: false" setting can currently fail with an exception. This change adds missing testing around the problematic case and fixes it by implementing missing methods in SortedSetDocValuesTerms.

Closes #94673

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/termsenum/TermsEnumTests.java [hunk 1]
```diff
@@ -30,18 +36,93 @@ public class TermsEnumTests extends ESSingleNodeTestCase {
...
+
+    private void indexAndRefresh(String indexName, String id, String field, String value) throws IOException {
+        client().prepareIndex(indexName)
+            .setId(id)
+            .setSource(jsonBuilder().startObject().field(field, value).endObject())
+            .setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE)
+            .get();
+    }
+
     @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/94378")
```
Comment (romseygeek) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/termsenum/TermsEnumTests.java:119]: Remove the `@AwaitsFix` annotation?

**Review by romseygeek — APPROVED** [review]
LGTM, one nit but no need for further reviews

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/termsenum/TermsEnumTests.java (hunk 1 above)
Comment (romseygeek) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/termsenum/TermsEnumTests.java:119]: Oh never mind, that's actually for a different bug isn't it

Comment (cbuescher) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/termsenum/TermsEnumTests.java:119]: Yes, that will be removed in a follow up around terms_enum for the ip type

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/docs
