### PR TITLE
Use latest busybox musl binaries for Docker distribution

### LINKED ISSUE #71138: Docker build task fails on CentOS 8 ARM CI workers
I'm seeing a very strange thing. Building our Docker images on the new CentOS ARM workers is failing due to a missing command, specifically `addgroup`. Sure enough, this utility doesn't exist on those machines. My question is, why does it matter? This command is being executed inside the _container_ so why would the setup on the host machine make any difference? Building the image on an Ubuntu host where `addgroup` exists works just fine. Am I missing something here?

https://gradle-enterprise.elastic.co/s/ee3bnyz42wxei/console-log?task=:distribution:docker:buildAarch64DockerImage#L8552

### PR DESCRIPTION
**Pull request by mark-vieira**
The busybox binaries we were using for our Docker distribution were slightly out of date, and didn't play nice with older kernel versions on aarch64. This pull request updates our Docker build to use  the same static binaries used in the busybox Docker image itself.

Closes https://github.com/elastic/elasticsearch/issues/71138

### CODE REVIEW

File: distribution/docker/src/docker/Dockerfile [hunk 1]
```diff
@@ -169,15 +168,10 @@ RUN set -e ; \\
     rm "\${TINI_BIN}.sha256sum" ; \\
     mv "\${TINI_BIN}" /rootfs/bin/tini ; \\
     chmod +x /rootfs/bin/tini ; \\
-    curl --retry 10 -L -o /rootfs/bin/busybox \\
-      "https://busybox.net/downloads/binaries/\${BUSYBOX_VERSION}-defconfig-multiarch-musl/busybox-\${BUSYBOX_ARCH}" ; \\
-    chmod +x /rootfs/bin/busybox
-
-# Add links for most of the Busybox utilities
-RUN set -e ; \\
-    for path in \$( /rootfs/bin/busybox --list-full | grep -v bin/sh | grep -v telnet | grep -v unzip); do \\
```
Comment (pugnascotia) [inline distribution/docker/src/docker/Dockerfile:178]: I was filtering the list of names that you could invoke busybox with. Besides `telnet`, was that uncessary?

File: distribution/docker/src/docker/Dockerfile [hunk 2]
```diff
@@ -169,15 +168,10 @@ RUN set -e ; \\
...
-      ln /rootfs/bin/busybox /rootfs/\$path ; \\
-    done
+    curl --retry 10 -L -O \\
+      "https://github.com/docker-library/busybox/raw/\${BUSYBOX_COMMIT}/stable/musl/busybox.tar.xz" ; \\
```
Comment (pugnascotia) [inline distribution/docker/src/docker/Dockerfile:172]: I think we need a comment explaining what's going on here, because this looks hacky compared with downloading from the official site.

Comment (pugnascotia) [reply distribution/docker/src/docker/Dockerfile:172]: Also I don't supposed you tried with busybox 1.33.0?

Comment (mark-vieira) [reply distribution/docker/src/docker/Dockerfile:172]: 1.32 is the latest "stable" release.

File: distribution/docker/src/docker/Dockerfile (hunk 1 above)
Comment (mark-vieira) [reply distribution/docker/src/docker/Dockerfile:178]: I'm not sure what the intent was to begin with. `unzip` is actually required and we even check for it explicitly in our packaging tests. As for telnet, sure, we could delete the symlink, but the capability is built into the `busybox` binary so anyone could just add it back.

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java [hunk 3]
```diff
@@ -487,7 +487,7 @@ private static void verifyOssInstallation(Installation es) {
             .forEach(
                 cliBinary -> assertTrue(
                     cliBinary + " ought to be available.",
-                    dockerShell.runIgnoreExitCode("hash " + cliBinary).isSuccess()
+                    dockerShell.runIgnoreExitCode("bash -c  'hash " + cliBinary + "'").isSuccess()
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java:490]: To be honest, I'm not sure why this change is necessary. Something about the default shell might be different? Other command work just fine but for some reason if I just do `hash foo` via `docker exec` it complains that it can't find a builtin by that name. Why it's look for a builtin command I have no clue. In the end this change doesn't affect the purpose of the assertion, which is to validate these tools are available in the container.

File: distribution/docker/src/docker/Dockerfile (hunk 2 above)
Comment (mark-vieira) [reply distribution/docker/src/docker/Dockerfile:173]: Added a clarifying comment.

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java (hunk 3 above)
Comment (pugnascotia) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java:490]: Wow, that's really peculiar...but ultimately it doesn't matter, as you say.

File: distribution/docker/src/docker/Dockerfile (hunk 2 above)
Comment (pugnascotia) [reply distribution/docker/src/docker/Dockerfile:173]: I'm a little concerned about how fiddling it will be to update those commit IDs, but let's go with it and see how we get on.

**Review by pugnascotia — APPROVED** [review]

File: distribution/docker/src/docker/Dockerfile (hunk 2 above)
Comment (mark-vieira) [reply distribution/docker/src/docker/Dockerfile:173]: Yeah, it's annoying they don't use tags in their repository. They just have branches per architecture.
