### PR TITLE
Teach runtime geopoint to parse all formats

### LINKED ISSUE #67907: Geo_point runtime field doesn't support geo_tile grid and geo_hash grid
If you index some documents containing a location and the defined location point is defined as a runtime field, the geo_tile and geo_hash grid aggregations don't return any bucket. When the location field is defined as an indexed field under properties, buckets are returned as expected.

```
curl -XPUT -HContent-Type:application/json -u elastic:password 'localhost:9200/test?pretty' -d'{
  "mappings" : {
    "runtime" : {
        "location" : {
          "type" : "geo_point"
        }
    }
  }
}
'

curl -XPOST -HContent-Type:application/json -u elastic:password 'localhost:9200/test/_doc/1?pretty&refresh=wait_for' -d'{
  "location": "52.374081,4.912350"
}
'

curl -X POST "localhost:9200/test/_search?pretty&size=0" -u elastic-admin:elastic-password -H 'Content-Type: application/json' -d'
{
  "aggs" : {
    "grid" : {
      "geohash_grid" : {
        "field" : "location",
        "precision" : 3
      }
    }
  }
}
'

{
  "took" : 11,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "grid" : {
      "buckets" : [ ]
    }
  }
}

curl -X POST "localhost:9200/test/_search?pretty&size=0" -u elastic-admin:elastic-password -H 'Content-Type: application/json' -d'
{
  "aggs" : {
    "grid" : {
      "geotile_grid" : {
        "field" : "location",
        "precision" : 8
      }
    }
  }
}
'

{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "grid" : {
      "buckets" : [ ]
    }
  }
}

```

### LINKED ISSUE #67911: Exists query returns no results against geo_point runtime field
When a geo_point field is defined as a runtime field, and there are values for it in indexed documents, the exists query returns 0 results when made against such field. When the same field is defined as an indexed field, the same query returns results.

```
curl -XPUT -HContent-Type:application/json -u elastic:password 'localhost:9200/test?pretty' -d'{
  "mappings" : {
    "runtime" : {
        "location" : {
          "type" : "geo_point"
        }
    }
  }
}
'

curl -XPOST -HContent-Type:application/json -u elastic:password 'localhost:9200/test/_doc/1?pretty&refresh=wait_for' -d'{
  "location": [-71.34, 41.14]
}
'

curl -X POST "localhost:9200/test/_search?pretty" -u elastic-admin:elastic-password -H 'Content-Type: application/json' -d'
{
  "query" : {
    "exists" : {
      "field" : "location"
    }
  }
}
'
```

### PR DESCRIPTION
**Pull request by iverase**
Currently the default parser for geo_point runtime field expects data to come in object format. This PR makes the parser to be able to read points coming in all supported formats.

Label as non-issue as it is not released.

closes  #67911
closes #67907

### CODE REVIEW

File: x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java [hunk 1]
```diff
@@ -49,20 +51,13 @@
         lookup,
         ctx
     ) {
+        final private GeoPoint scratch = new GeoPoint();
+
```
Comment (iverase) [inline x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:55]: Can execute() be called from different threads?

File: x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java [hunk 2]
```diff
@@ -49,20 +51,13 @@
...
-            @SuppressWarnings("unchecked")
-            Map<String, ?> vs = (Map<String, ?>) v;
-            Object lat = vs.get("lat");
-            Object lon = vs.get("lon");
-            if (lat instanceof Number == false || lon instanceof Number == false) {
-                return;
-            }
-            emit(((Number) lat).doubleValue(), ((Number) lon).doubleValue());
+            GeoUtils.parseGeoPoint(v, scratch, true);
+            emit(scratch.lat(), scratch.lon());
```
Comment (iverase) [inline x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:60]: Which is the strategy for invalid formats? should an error be thrown or should be just catch it?

Comment (javanna) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:60]: I think we catch it in other places and don't emit values, what do you think @romseygeek ?

**Review by javanna — APPROVED** [review]
LGTM thanks a lot for the speedy fix @iverase ! Can you also re-enable the skipped tests under `x-pack/pluging/runtime-fields/qa/build.gradle`?

**Comment by javanna** [comment]
> Can you also re-enable the skipped tests under x-pack/pluging/runtime-fields/qa/build.gradle?

Nevermind, I was referring to #67915 but I haven't merged it yet. So nothing to do, I will let you merge and then rebase and adapt the exclusion list accordingly. Thanks again!

File: x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java (hunk 2 above)
Comment (romseygeek) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:60]: Yes, elsewhere we catch exceptions and ignore

Comment (iverase) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:60]: I wonder if throwing or not an error should be controlled by something like the `ignored_flag`?. It might be surprising by users not to get any feedback why the point has not been emitted.

File: x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java [hunk 3]
```diff
@@ -49,20 +51,13 @@
         lookup,
         ctx
     ) {
+        private final GeoPoint scratch = new GeoPoint();
+
```
Comment (iverase) [inline x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:55]: I have another question, is that ok? not sure if execute method needs to be thread safe.

File: x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java (hunk 2 above)
Comment (javanna) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java]: I am a bit on the fence on this. It is true that users would like to know, on the other hand you would not want to break the query for one document that has some wrong format. This should be discussed for all runtime fields and eventually be streamlined. For now I would go for consistency and do what other runtime fields do, ignore errors.

Comment (iverase) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java]: I think the current behaviour can bet the default one but we should have a way to get those exceptions. I am thinking of a user raising the question why a query with runtime fields is not working. We currently have no way to get this feedback as exceptions are swallow so it is going to be pretty tricky to understand the issue?

Comment (javanna) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java]: yes agreed

File: x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java (hunk 3 above)
Comment (iverase) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:55]: this looks ok, we create a new instance for every query.

Comment (javanna) [reply x-pack/plugin/runtime-fields/src/main/java/org/elasticsearch/xpack/runtimefields/mapper/GeoPointFieldScript.java:55]: yea we are good, sorry I forgot to answer earlier.
