### PR TITLE
Check for global blocks after IndexNotFoundException in TransportMasterNodeAction

### LINKED ISSUE #70572: False 404 index_not_found_exception from /_cat/indices/ALIAS after master returns
**Elasticsearch version** (`bin/elasticsearch --version`):
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 7.5.2, Build: default/rpm/8bec50e1e0ad29dad5653712cf3bb580cd1afcdf/2020-01-15T12:11:52.313576Z, JVM: 13.0.1
**Plugins installed**: []
```
**JVM version** (`java -version`):
```
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
```
**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.9.2009 (Core)

**Description of the problem including expected versus actual behavior**:

After master node has been down, when it returns there is a brief window where `/_cat/indices/ALIAS` requests are accepted but elasticsearch returns a 404 `index_not_found_exception`. This is unexpected and problematic behavior to our app which considers this an error.

I'd expect a usually strongly consistent system like elasticsearch to return a 503 if it hasn't fully read enough data after master returned to determine if the alias+index exists. It's ok to give an error, it's not okay to give false information like that the index does not exist.

**Steps to reproduce**:
Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. For simplicity create a 3 node cluster with one node being the only master and not accepting data.
 2. Create an index with an alias MYALIAS.
 3. Run a curl loop below requesting an index by its alias name to a data node, verify it returns 200.
 4. Stop the master node, the curls soon fail to connect `curl: (7) Failed to connect`.
 5.  Bring the master node back up, it starts  returning `curl: (52) Empty reply from server`
 6. I see one false 404 returned before it goes back to returning a 200 (with a briefly red index).
```
$ while sleep 1 ; do curl -i ELASTICSEARCH:9200/_cat/indices/MYALIAS  ; done
...
HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 437

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [MYALIAS]","resource.type":"index_or_alias","resource.id":"MYALIAS","index_uuid":"_na_","index":"MYALIAS"}],"type":"index_not_found_exception","reason":"no such index [MYALIAS]","resource.type":"index_or_alias","resource.id":"MYALIAS","index_uuid":"_na_","index":"MYALIAS"},"status":404}
```

**Provide logs (if relevant)**:

Sorry I can try to recover logs if you can't reproduce this.

### PR DESCRIPTION
**Pull request by fcofdez**
Today we try to resolve index patterns to check cluster blocks in
certain TransportMasterNodeActions, in some scenarios where
a master node is recovering we could end up throwing a false
IndexNotFoundException. This commit adds an extra check
for global blocks when a IndexNotFoundException is thrown 
to ensure that we cover that case.

Closes #70572

### CODE REVIEW

**Comment by fcofdez** [comment]
The test failure is known https://github.com/elastic/elasticsearch/issues/78080

**Comment by fcofdez** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/action/support/master/info/TransportClusterInfoActionTests.java [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+                                         Request request,
+                                         String[] concreteIndices,
+                                         ClusterState state,
+                                         ActionListener<Response> listener) {
+            listener.onResponse(new Response());
+        }
+    }
+
+    public void testGlobalBlocksAreCheckedBeforeResolvingIndices() throws Exception {
+        final boolean unblockBeforeTimeout = randomBoolean();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/master/info/TransportClusterInfoActionTests.java:156]: Could we split this into two tests rather than randomly choosing between these branches?

Also (nit) I have a slight preference for making all the things `final`. Or none of them, but ideally not just the one.

**Review by DaveCTurner — COMMENTED** [review]
Change looks good ~but I think to fix #70572 you'd need to make the same change in `TransportGetAliasesAction` and not `TransportClusterInfoAction`.~

Edit: sorry, misread the issue, this will indeed fix that specific case.

**Comment by DaveCTurner** [comment]
Also it looks like this pattern appears in a bunch of other places, maybe we should wrap it up and more generally check for global blocks on an INFE rather than returning the INFE directly to the caller?

**Comment by fcofdez** [comment]
Thanks for the review! I've moved the check to the `TransportMasterNodeAction` as you suggested.

File: server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java [hunk 2]
```diff
@@ -193,12 +183,41 @@ public void handleException(final TransportException exp) {
...
 
+        private void handleClusterBlockException(ClusterState clusterState, ClusterBlockException blockException) {
+            if (blockException.retryable() == false) {
+                logger.trace("can't execute due to a non-retryable cluster block", blockException);
+                listener.onFailure(blockException);
+            } else {
+                logger.debug("can't execute due to a cluster block, retrying", blockException);
+                retry(clusterState, blockException, newState -> {
+                    try {
+                        ClusterBlockException newException = checkBlock(request, newState);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java:210]: If this call to `checkBlock` also throws an INFE and the `STATE_NOT_RECOVERED_BLOCK` is in place then we could reasonably reject the state I think.

File: server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java [hunk 3]
```diff
@@ -193,12 +183,41 @@ public void handleException(final TransportException exp) {
                         });
                     }
                 }
+            } catch (IndexNotFoundException e) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java:186]: Not sure about catching an INFE thrown by any of this code, could we just protect the call to `checkBlock()`?

File: server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java [hunk 4]
```diff
@@ -99,6 +100,10 @@ protected boolean localExecute(Request request) {
 
     protected abstract ClusterBlockException checkBlock(Request request, ClusterState state);
 
+    protected ClusterBlockException checkGlobalBlock(ClusterState clusterState) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java:103]: Thinking about this some more, I think we only really care about INFEs thrown while the `STATE_NOT_RECOVERED_BLOCK` is in place, other blocks don't really matter. I think rather than introducing the `checkGlobalBlock` method (which kinda duplicates `checkBlock`) it'd be better to wrap `checkBlock` like this:

```java
    private ClusterBlockException checkBlockIfStateRecovered(Request request, ClusterState state) {
        try {
            return checkBlock(request, state);
        } catch (IndexNotFoundException e) {
            if (state.blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)) {
                // no index metadata is exposed yet, but checkBlock depends on an index, so keep trying until the cluster forms
                assert GatewayService.STATE_NOT_RECOVERED_BLOCK.contains(ClusterBlockLevel.METADATA_READ);
                assert state.blocks().global().stream().allMatch(ClusterBlock::retryable);
                return state.blocks().globalBlockedException(ClusterBlockLevel.METADATA_READ);
            } else {
                throw e;
            }
        }
    }
```

**Review by DaveCTurner — COMMENTED** [review]
I worry about introducing the new method, it kind of duplicates `checkBlock()` and I expect we'll forget to override it sometimes. I suggested a possible alternative, WDYT?

**Comment by fcofdez** [comment]
> I worry about introducing the new method, it kind of duplicates checkBlock() and I expect we'll forget to override it sometimes. I suggested a possible alternative, WDYT?

I agree, I wasn't supper happy about introducing `checkGlobalBlocks`. I wasn't 100% sure if `STATE_NOT_RECOVERED_BLOCK` was the only case where we could end up in this situation or if we should check for `ClusterBlockLevel.METADATA_WRITE` blocks too. Thanks for the feedback!

File: server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java [hunk 5]
```diff
@@ -99,6 +103,21 @@ protected boolean localExecute(Request request) {
...
     protected abstract ClusterBlockException checkBlock(Request request, ClusterState state);
 
+    private ClusterBlockException checkBlockIfStateRecovered(Request request, ClusterState state) {
+        try {
+            return checkBlock(request, state);
+        } catch (IndexNotFoundException e) {
+            if (state.blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)) {
+                // no index metadata is exposed yet, but checkBlock depends on an index, so keep trying until the cluster forms
+                assert GatewayService.STATE_NOT_RECOVERED_BLOCK.contains(ClusterBlockLevel.METADATA_READ);
+                assert state.blocks().global().stream().allMatch(ClusterBlock::retryable);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java:113]: Sorry I gave you a duff assertion here, should be this:

```suggestion
                assert state.blocks().global(ClusterBlockLevel.METADATA_READ).stream().allMatch(ClusterBlock::retryable);
```

(or else we could theoretically have something like `Metadata.CLUSTER_READ_ONLY_BLOCK` in there which isn't retryable but also doesn't block metadata reads).

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by fcofdez** [comment]
Thanks David!
