### PR TITLE
Fix recovery permit exhaustion message

### LINKED ISSUE #90082: Snapshot-based peer recovery permit exhaustion yields incorrect message
We limit the number of concurrent blob downloads per node and per recovery, but if a user configures too many concurrent recoveries they may run out of per-node download permits which yields the following message:

> Unable to acquire permit to use snapshot files during recovery, this recovery will recover index files from the source node. Ensure snapshot files can be used during recovery by setting [indices.recovery.max_concurrent_snapshot_file_downloads] to be no greater than [25]

The `[25]` here is wrong, the 25 permits are shared across all inbound recoveries so we should divide the suggested value by `cluster.routing.allocation.node_concurrent_incoming_recoveries`. In extreme cases the user may have configured so many concurrent recoveries that the only reasonable limit is zero, and in that case we should suggest setting `indices.recovery.use_snapshots: false` instead.

### PR DESCRIPTION
**Pull request by volodk85**
Fix for ES [issue](https://github.com/elastic/elasticsearch/issues/90082)

Closes #90082

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java [hunk 1]
```diff
@@ -666,16 +677,28 @@ Releasable tryAcquireSnapshotDownloadPermits() {
...
+                    )
+                );
+            } else {
+                logger.warn(
+                    String.format(
+                        Locale.ROOT,
+                        "Number of concurrent incoming recoveries exceeds max number of concurrent snapshot file downloads "
+                            + "per node. Thus some recoveries won't be able to make a progress. Consider decreasing value of "
+                            + "[cluster.routing.allocation.node_concurrent_incoming_recoveries] or disabling use of "
+                            + "snapshot recovery entirely by setting [indices.recovery.use_snapshots] to [false]"
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java:698]: I'd prefer we use `CLUSTER_ROUTING_ALLOCATION_NODE_CONCURRENT_INCOMING_RECOVERIES_SETTING.getKey()` and `INDICES_RECOVERY_USE_SNAPSHOTS_SETTING.getKey()` rather than the literal setting names in the message. Not that they'll ever change, but it makes it possible to find references to the settings in your IDE.

Also could we include the current values of `maxConcurrentIncomingRecoveries` and `this.maxConcurrentSnapshotFileDownloadsPerNode` in the message?

Also (nit) perhaps a multi-line string would be preferable as the format string here?

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java [hunk 2]
```diff
@@ -666,16 +677,28 @@ Releasable tryAcquireSnapshotDownloadPermits() {
...
-                    this.maxConcurrentSnapshotFileDownloadsPerNode
-                )
-            );
+            if (this.maxConcurrentIncomingRecoveries <= this.maxConcurrentSnapshotFileDownloadsPerNode) {
+                logger.warn(
+                    String.format(
+                        Locale.ROOT,
+                        "Unable to acquire permit to use snapshot files during recovery, "
+                            + "this recovery will recover index files from the source node. "
+                            + "Ensure snapshot files can be used during recovery by setting [%s] to be no greater than [%d]",
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java:686]: Also here could we include the current values of the relevant settings in the message?

(and also perhaps convert the format string into a multi-line thing)

**Review by DaveCTurner — COMMENTED** [review]
Logic looks good to me. I left some small comments on the messages themselves. Also this change deserves some tests.

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java (hunk 1 above)
Comment (volodk85) [reply server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java]: Done

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java (hunk 2 above)
Comment (volodk85) [reply server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java]: Done

File: server/src/test/java/org/elasticsearch/indices/recovery/RecoverySettingsTests.java [hunk 3]
```diff
@@ -100,6 +102,104 @@ public void testSnapshotDownloadPermitCanBeDynamicallyUpdated() {
...
+            // Deny the second recovery to get the permit
+            assertThat(recoverySettings.tryAcquireSnapshotDownloadPermits(), is(nullValue()));
+
+            // assert that WARN message was logged
+            warnCaptureAppender.assertAllExpectationsMatched();
+
+        } finally {
+            Loggers.removeAppender(logger, warnCaptureAppender);
+            warnCaptureAppender.stop();
+        }
```
Comment (idegtiarenko) [inline server/src/test/java/org/elasticsearch/indices/recovery/RecoverySettingsTests.java:152]: I have recently merged an utility that simplifies log capturing setup, you might consider using it here: https://github.com/elastic/elasticsearch/blob/3808b53914aeb1e48eb0941b1400bfc2c3d7d1c9/test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java#L268-L275

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java [hunk 4]
```diff
@@ -666,16 +677,40 @@ Releasable tryAcquireSnapshotDownloadPermits() {
...
+                        Locale.ROOT,
+                        """
+                            Number of concurrent incoming recoveries [%d] exceeds max number of concurrent snapshot file downloads [%d]
+                            per node. Thus some recoveries won't be able to make a progress. Consider decreasing value of
+                            [%s] or disabling use of snapshot recovery entirely by setting [%s] to [false]
+                            """,
+                        this.maxConcurrentIncomingRecoveries,
+                        this.maxConcurrentSnapshotFileDownloadsPerNode,
+                        CLUSTER_ROUTING_ALLOCATION_NODE_CONCURRENT_INCOMING_RECOVERIES_SETTING.getKey(),
+                        INDICES_RECOVERY_USE_SNAPSHOTS_SETTING.getKey()
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/indices/recovery/RecoverySettings.java:710]: Likewise here:

```suggestion
                        """
                            Unable to acquire permit to use snapshot files during recovery, so this recovery will recover index files from \
                            the source node. Ensure snapshot files can be used during recovery by reducing [%s] from its current value of \
                            [%d] to be no greater than [%d], or disable snapshot-based recovery by setting [%s] to [false]""",
                        CLUSTER_ROUTING_ALLOCATION_NODE_CONCURRENT_INCOMING_RECOVERIES_SETTING.getKey(),
                        this.maxConcurrentIncomingRecoveries,
                        this.maxConcurrentSnapshotFileDownloadsPerNode,
                        INDICES_RECOVERY_USE_SNAPSHOTS_SETTING.getKey()
```

**Review by DaveCTurner — COMMENTED** [review]
Looks good, I left small wording/formatting suggestions.

**Review by DaveCTurner — COMMENTED** [review]
Thanks, I'm good with this now. Just Ievgen's comment to address (or dismiss).

Also please don't force-push to a PR branch once it's under review, it makes it much harder to keep track of history. The branch will be automatically squashed into a single commit when it's merged.

**Review by DaveCTurner — APPROVED** [review]
LGTM 👍
