### PR TITLE
Install the stack templates only if DSL available

### LINKED ISSUE #106461: [CI] DataTierMixedIT testMixedTierCompatibility failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/ebivm6xolwuiu/tests/:x-pack:qa:mixed-tier-cluster:v8.10.4%23mixedClusterTest/org.elasticsearch.mixed.DataTierMixedIT/testMixedTierCompatibility

**Reproduction line:**
```
./gradlew ':x-pack:qa:mixed-tier-cluster:v8.10.4#mixedClusterTest' -Dtests.class="org.elasticsearch.mixed.DataTierMixedIT" -Dtests.method="testMixedTierCompatibility" -Dtests.seed=F98F58B12D14BFFC -Dtests.bwc=true -Dtests.locale=es-HN -Dtests.timezone=America/Lower_Princes -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.mixed.DataTierMixedIT#testMixedTierCompatibility`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testMixedTierCompatibility'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.mixed.DataTierMixedIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**

<details>
  <summary>Failure</summary>
```
java.lang.AssertionError: timed out waiting for green state for index [test-index] cluster state [{
  "cluster_name" : "v8.10.4",
  "cluster_uuid" : "bdMIzXEdQ6maTmQH3P0ssw",
  "version" : 41,
  "state_uuid" : "DrTMytH6QUOgUcf-4gx-4A",
  "master_node" : "dPWNRcI_RLKVRrv6e0abyA",
  "blocks" : { },
  "nodes" : {
    "dPWNRcI_RLKVRrv6e0abyA" : {
      "name" : "v8.10.4-0",
      "ephemeral_id" : "Qa83MIGWS9O-6q7QudpmSQ",
      "transport_address" : "127.0.0.1:41759",
      "external_id" : "v8.10.4-0",
      "attributes" : {
        "testattr" : "test",
        "xpack.installed" : "true",
        "ml.config_version" : "12.0.0",
        "transform.config_version" : "10.0.0",
        "upgraded" : "true"
      },
      "roles" : [
        "master"
      ],
      "version" : "8.14.0",
      "min_index_version" : 7000099,
      "max_index_version" : 8504000
    },
    "W0KY-UYHSdq04h-eqagdYA" : {
      "name" : "v8.10.4-2",
      "ephemeral_id" : "lvFxaIiWTxSrs_tPdG_pig",
      "transport_address" : "127.0.0.1:36075",
      "external_id" : "v8.10.4-2",
      "attributes" : {
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0",
        "testattr" : "test"
      },
      "roles" : [
        "master"
      ],
      "version" : "8.10.4",
      "min_index_version" : 7000099,
      "max_index_version" : 8100499
    }
  },
  "transport_versions" : [
    {
      "node_id" : "dPWNRcI_RLKVRrv6e0abyA",
      "transport_version" : "8612000"
    },
    {
      "node_id" : "W0KY-UYHSdq04h-eqagdYA",
      "transport_version" : "8500061"
    }
  ],
  "metadata" : {
    "cluster_uuid" : "bdMIzXEdQ6maTmQH3P0ssw",
    "cluster_uuid_committed" : true,
    "cluster_coordination" : {
      "term" : 2,
      "last_committed_config" : [
        "W0KY-UYHSdq04h-eqagdYA",
        "dPWNRcI_RLKVRrv6e0abyA",
        "{bootstrap-placeholder}-v8.10.4-1"
      ],
      "last_accepted_config" : [
        "W0KY-UYHSdq04h-eqagdYA",
        "dPWNRcI_RLKVRrv6e0abyA",
        "{bootstrap-placeholder}-v8.10.4-1"
      ],
      "voting_config_exclusions" : [ ]
    },
    "templates" : {
      ".monitoring-beats" : {
        "order" : 0,
        "version" : 8120099,
        "index_patterns" : [
          ".monitoring-beats-7-*"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "beats_state" : {
                "properties" : {
                  "beat" : {
                    "properties" : {
                      "host" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "type" : {
                        "type" : "keyword"
                      },
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "state" : {
                    "properties" : {
                      "beat" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "host" : {
                        "properties" : {
                          "architecture" : {
                            "type" : "keyword"
                          },
                          "name" : {
                            "type" : "keyword"
                          },
                          "hostname" : {
                            "type" : "keyword"
                          },
                          "os" : {
                            "properties" : {
                              "build" : {
                                "type" : "keyword"
                              },
                              "family" : {
                                "type" : "keyword"
                              },
                              "platform" : {
                                "type" : "keyword"
                              },
                              "version" : {
                                "type" : "keyword"
                              }
                            }
                          }
                        }
                      },
                      "input" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          },
                          "names" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "module" : {
                        "properties" : {
                          "count" : {
                            "type" : "long"
                          },
                          "names" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "output" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          }
                        }
                      },
                      "service" : {
                        "properties" : {
                          "id" : {
                            "type" : "keyword"
                          },
                          "name" : {
                            "type" : "keyword"
                          },
                          "version" : {
                            "type" : "keyword"
                          }
                        }
                      }
                    }
                  },
                  "timestamp" : {
                    "format" : "date_time",
                    "type" : "date"
                  }
                }
              },
              "beats_stats" : {
                "properties" : {
                  "beat" : {
                    "properties" : {
                      "host" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "type" : {
                        "type" : "keyword"
                      },
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "metrics" : {
                    "properties" : {
                      "beat" : {
                        "properties" : {
                          "cgroup" : {
                            "properties" : {
                              "cpu" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "cfs" : {
                                    "properties" : {
                                      "period" : {
                                        "properties" : {
                                          "us" : {
                                            "type" : "long"
                                          }
                                        }
                                      },
                                      "quota" : {
                                        "properties" : {
                                          "us" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  },
                                  "stats" : {
                                    "properties" : {
                                      "periods" : {
                                        "type" : "long"
                                      },
                                      "throttled" : {
                                        "properties" : {
                                          "periods" : {
                                            "type" : "long"
                                          },
                                          "ns" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              },
                              "cpuacct" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "total" : {
                                    "properties" : {
                                      "ns" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "memory" : {
                                "properties" : {
                                  "id" : {
                                    "type" : "keyword"
                                  },
                                  "mem" : {
                                    "properties" : {
                                      "limit" : {
                                        "properties" : {
                                          "bytes" : {
                                            "type" : "long"
                                          }
                                        }
                                      },
                                      "usage" : {
                                        "properties" : {
                                          "bytes" : {
                                            "type" : "long"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "cpu" : {
                            "properties" : {
                              "system" : {
                                "properties" : {
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "total" : {
                                "properties" : {
                                  "value" : {
                                    "type" : "long"
                                  },
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "user" : {
                                "properties" : {
                                  "ticks" : {
                                    "type" : "long"
                                  },
                                  "time" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "info" : {
                            "properties" : {
                              "ephemeral_id" : {
                                "type" : "keyword"
                              },
                              "uptime" : {
                                "properties" : {
                                  "ms" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "version" : {
                                "type" : "keyword"
                              }
                            }
                          },
                          "memstats" : {
                            "properties" : {
                              "gc_next" : {
                                "type" : "long"
                              },
                              "memory_alloc" : {
                                "type" : "long"
                              },
                              "memory_total" : {
                                "type" : "long"
                              },
                              "rss" : {
                                "type" : "long"
                              }
                            }
                          },
                          "handles" : {
                            "properties" : {
                              "open" : {
                                "type" : "long"
                              },
                              "limit" : {
                                "properties" : {
                                  "hard" : {
                                    "type" : "long"
                                  },
                                  "soft" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "apm-server" : {
                        "properties" : {
                          "acm" : {
                            "properties" : {
                              "request" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "response" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "properties" : {
                                      "validate" : {
                                        "type" : "long"
                                      },
                                      "internal" : {
                                        "type" : "long"
                                      },
                                      "queue" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "decode" : {
                                        "type" : "long"
                                      },
                                      "toolarge" : {
                                        "type" : "long"
                                      },
                                      "unavailable" : {
                                        "type" : "long"
                                      },
                                      "forbidden" : {
                                        "type" : "long"
                                      },
                                      "method" : {
                                        "type" : "long"
                                      },
                                      "notfound" : {
                                        "type" : "long"
                                      },
                                      "invalidquery" : {
                                        "type" : "long"
                                      },
                                      "ratelimit" : {
                                        "type" : "long"
                                      },
                                      "closed" : {
                                        "type" : "long"
                                      },
                                      "unauthorized" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "valid" : {
                                    "properties" : {
                                      "notmodified" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "ok" : {
                                        "type" : "long"
                                      },
                                      "accepted" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "unset" : {
                                    "type" : "long"
                                  },
                                  "request" : {
                                    "properties" : {
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "server" : {
                            "properties" : {
                              "request" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "concurrent" : {
                                "properties" : {
                                  "wait" : {
                                    "properties" : {
                                      "ms" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "response" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "properties" : {
                                      "count" : {
                                        "type" : "long"
                                      },
                                      "toolarge" : {
                                        "type" : "long"
                                      },
                                      "validate" : {
                                        "type" : "long"
                                      },
                                      "ratelimit" : {
                                        "type" : "long"
                                      },
                                      "queue" : {
                                        "type" : "long"
                                      },
                                      "closed" : {
                                        "type" : "long"
                                      },
                                      "forbidden" : {
                                        "type" : "long"
                                      },
                                      "concurrency" : {
                                        "type" : "long"
                                      },
                                      "unauthorized" : {
                                        "type" : "long"
                                      },
                                      "internal" : {
                                        "type" : "long"
                                      },
                                      "decode" : {
                                        "type" : "long"
                                      },
                                      "method" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "valid" : {
                                    "properties" : {
                                      "ok" : {
                                        "type" : "long"
                                      },
                                      "accepted" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          },
                          "decoder" : {
                            "properties" : {
                              "deflate" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "gzip" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "uncompressed" : {
                                "properties" : {
                                  "content-length" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "reader" : {
                                "properties" : {
                                  "size" : {
                                    "type" : "long"
                                  },
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "missing-content-length" : {
                                "properties" : {
                                  "count" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "processor" : {
                            "properties" : {
                              "metric" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "sourcemap" : {
                                "properties" : {
                                  "counter" : {
                                    "type" : "long"
                                  },
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              },
                              "transaction" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  },
                                  "transactions" : {
                                    "type" : "long"
                                  },
                                  "spans" : {
                                    "type" : "long"
                                  },
                                  "stacktraces" : {
                                    "type" : "long"
                                  },
                                  "frames" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "error" : {
                                "properties" : {
                                  "decoding" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "validation" : {
                                    "properties" : {
                                      "errors" : {
                                        "type" : "long"
                                      },
                                      "count" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "transformations" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  },
                                  "stacktraces" : {
                                    "type" : "long"
                                  },
                                  "frames" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "span" : {
                                "properties" : {
                                  "transformations" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "sampling" : {
                            "properties" : {
                              "transactions_dropped" : {
                                "type" : "long"
                              },
                              "tail" : {
                                "properties" : {
                                  "dynamic_service_groups" : {
                                    "type" : "long"
                                  },
                                  "storage" : {
                                    "properties" : {
                                      "lsm_size" : {
                                        "type" : "long"
                                      },
                                      "value_log_size" : {
                                        "type" : "long"
                                      }
                                    }
                                  },
                                  "events" : {
                                    "properties" : {
                                      "processed" : {
                                        "type" : "long"
                                      },
                                      "dropped" : {
                                        "type" : "long"
                                      },
                                      "stored" : {
                                        "type" : "long"
                                      },
                                      "sampled" : {
                                        "type" : "long"
                                      },
                                      "head_unsampled" : {
                                        "type" : "long"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "libbeat" : {
                        "properties" : {
                          "config" : {
                            "properties" : {
                              "module" : {
                                "properties" : {
                                  "running" : {
                                    "type" : "long"
                                  },
                                  "starts" : {
                                    "type" : "long"
                                  },
                                  "stops" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "reloads" : {
                                "type" : "long"
                              }
                            }
                          },
                          "output" : {
                            "properties" : {
                              "events" : {
                                "properties" : {
                                  "acked" : {
                                    "type" : "long"
                                  },
                                  "active" : {
                                    "type" : "long"
                                  },
                                  "batches" : {
                                    "type" : "long"
                                  },
                                  "dropped" : {
                                    "type" : "long"
                                  },
                                  "duplicates" : {
                                    "type" : "long"
                                  },
                                  "failed" : {
                                    "type" : "long"
                                  },
                                  "total" : {
                                    "type" : "long"
                                  },
                                  "toomany" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "read" : {
                                "properties" : {
                                  "bytes" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "type" : {
                                "type" : "keyword"
                              },
                              "write" : {
                                "properties" : {
                                  "bytes" : {
                                    "type" : "long"
                                  },
                                  "errors" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          },
                          "pipeline" : {
                            "properties" : {
                              "clients" : {
                                "type" : "long"
                              },
                              "events" : {
                                "properties" : {
                                  "active" : {
                                    "type" : "long"
                                  },
                                  "dropped" : {
                                    "type" : "long"
                                  },
                                  "failed" : {
                                    "type" : "long"
                                  },
                                  "filtered" : {
                                    "type" : "long"
                                  },
                                  "published" : {
                                    "type" : "long"
                                  },
                                  "retry" : {
                                    "type" : "long"
                                  },
                                  "total" : {
                                    "type" : "long"
                                  }
                                }
                              },
                              "queue" : {
                                "properties" : {
                                  "acked" : {
                                    "type" : "long"
                                  },
                                  "max_events" : {
                                    "type" : "long"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "system" : {
                        "properties" : {
                          "load" : {
                            "properties" : {
                              "1" : {
                                "type" : "double"
                              },
                              "15" : {
                                "type" : "double"
                              },
                              "5" : {
                                "type" : "double"
                              },
                              "norm" : {
                                "properties" : {
                                  "1" : {
                                    "type" : "double"
                                  },
                                  "15" : {
                                    "type" : "double"
                                  },
                                  "5" : {
                                    "type" : "double"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "tags" : {
                    "type" : "keyword"
                  },
                  "timestamp" : {
                    "format" : "date_time",
                    "type" : "date"
                  }
                }
              },
              "cluster_uuid" : {
                "type" : "keyword"
              },
              "interval_ms" : {
                "type" : "long"
              },
              "source_node" : {
                "properties" : {
                  "host" : {
                    "type" : "keyword"
                  },
                  "ip" : {
                    "type" : "keyword"
                  },
                  "name" : {
                    "type" : "keyword"
                  },
                  "transport_address" : {
                    "type" : "keyword"
                  },
                  "uuid" : {
                    "type" : "keyword"
                  }
                }
              },
              "timestamp" : {
                "format" : "date_time",
                "type" : "date"
              },
              "type" : {
                "type" : "keyword"
              }
            }
          }
        },
        "aliases" : { }
      },
      ".monitoring-kibana" : {
        "order" : 0,
        "version" : 8120099,
        "index_patterns" : [
          ".monitoring-kibana-7-*"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "cluster_uuid" : {
                "type" : "keyword"
              },
              "timestamp" : {
                "type" : "date",
                "format" : "date_time"
              },
              "interval_ms" : {
                "type" : "long"
              },
              "type" : {
                "type" : "keyword"
              },
              "source_node" : {
                "properties" : {
                  "uuid" : {
                    "type" : "keyword"
                  },
                  "host" : {
                    "type" : "keyword"
                  },
                  "transport_address" : {
                    "type" : "keyword"
                  },
                  "ip" : {
                    "type" : "keyword"
                  },
                  "name" : {
                    "type" : "keyword"
                  },
                  "timestamp" : {
                    "type" : "date",
                    "format" : "date_time"
                  }
                }
              },
              "kibana_stats" : {
                "properties" : {
                  "usage" : {
                    "properties" : {
                      "index" : {
                        "type" : "keyword"
                      }
                    }
                  },
                  "kibana" : {
                    "properties" : {
                      "uuid" : {
                        "type" : "keyword"
                      },
                      "name" : {
                        "type" : "keyword"
                      },
                      "host" : {
                        "type" : "keyword"
                      },
                      "transport_address" : {
                        "type" : "keyword"
                      },
                      "version" : {
                        "type" : "keyword"
                      },
                      "snapshot" : {
                        "type" : "boolean"
                      },
                      "status" : {
                        "type" : "keyword"
                      },
                      "statuses" : {
                        "properties" : {
                          "name" : {
                            "type" : "keyword"
                          },
                          "state" : {
                            "type" : "keyword"
                          }
                        }
                      }
                    }
                  },
                  "cloud" : {
                    "properties" : {
                      "name" : {
                        "type" : "keyword"
                      },
                      "id" : {
                        "type" : "keyword"
                      },
                      "vm_type" : {
                        "type" : "keyword"
                      },
                      "region" : {
                        "type" : "keyword"
                      },
                      "zone" : {
                        "type" : "keyword"
                      },
                      "metadata" : {
                        "type" : "object"
                      }
                    }
                  },
                  "os" : {
                    "properties" : {
                      "load" : {
                        "properties" : {
                          "1m" : {
                            "type" : "half_float"
                          },
                          "5m" : {
                            "type" : "half_float"
                          },
                          "15m" : {
                            "type" : "half_float"
                          }
                        }
                      },
                      "memory" : {
                        "properties" : {
                          "total_in_bytes" : {
                            "type" : "float"
                          },
                          "free_in_bytes" : {
                            "type" : "float"
                          },
                          "used_in_bytes" : {
                            "type" : "float"
                          }
                        }
                      },
                      "uptime_in_millis" : {
                        "type" : "long"
                      }
                    }
                  },
                  "process" : {
                    "properties" : {
                      "memory" : {
                        "properties" : {
                          "heap" : {
                            "properties" : {
                              "total_in_bytes" : {
                                "type" : "float"
                              },
                              "used_in_bytes" : {
                                "type" : "float"
                              },
                              "size_limit" : {
                                "type" : "float"
                              }
                            }
                          },
                          "resident_set_size_in_bytes" : {
                            "type" : "float"
                          }
                        }
                      },
                      "event_loop_delay" : {
                        "type" : "float"
                      },
                      "uptime_in_millis" : {
                        "type" : "long"
                      }
                    }
                  },
                  "sockets" : {
                    "properties" : {
                      "http" : {
                        "properties" : {
                          "total" : {
                            "type" : "long"
                          }
                        }
                      },
                      "https" : {
                        "properties" : {
                          "total" : {
                            "type" : "long"
                          }
                        }
                      }
                    }
                  },
                  "timestamp" : {
                    "type" : "date"
                  },
                  "requests" : {
                    "properties" : {
                      "disconnects" : {
                        "type" : "long"
                      },
                      "total" : {
                        "type" : "long"
                      },
                      "status_codes" : {
                        "type" : "object"
                      }
                    }
                  },
                  "response_times" : {
                    "properties" : {
                      "average" : {
                        "type" : "float"
                      },
                      "max" : {
                        "type" : "float"
                      }
                    }
                  },
                  "concurrent_connections" : {
                    "type" : "long"
                  }
                }
              }
            }
          }
        },
        "aliases" : { }
      },
      ".monitoring-alerts-7" : {
        "order" : 0,
        "version" : 8120099,
        "index_patterns" : [
          ".monitoring-alerts-7"
        ],
        "settings" : {
          "index" : {
            "format" : "7",
            "codec" : "best_compression",
            "number_of_shards" : "1",
            "auto_expand_replicas" : "0-1",
            "number_of_replicas" : "0"
          }
        },
        "mappings" : {
          "_doc" : {
            "dynamic" : false,
            "properties" : {
              "timestamp" : {
                "type" : "date"
              },
              "update_timestamp" : {
                "type" : "date"
              },
              "resolved_...
```
</details>

**Actual failure**

The build output contains
```
» [2024-03-19T04:28:11,023][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v8.10.4-1] fatal error in thread [elasticsearch[v8.10.4-1][AsyncLucenePersistedState#updateTask][T#1]], exiting java.lang.AssertionError: org.elasticsearch.gateway.CorruptStateException: org.elasticsearch.xcontent.XContentParseException: [-1:32054] [index_template] failed to parse field [index_template]
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService$Writer.assertOnCommit(PersistedClusterStateService.java:1244)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService$Writer.commit(PersistedClusterStateService.java:1234)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeIncrementalStateAndCommit(PersistedClusterStateService.java:976)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.writeClusterStateToDisk(GatewayMetaState.java:579)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.setLastAcceptedState(GatewayMetaState.java:562)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.GatewayMetaState$AsyncPersistedState$1.doRun(GatewayMetaState.java:436)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»  	at java.base/java.lang.Thread.run(Thread.java:1583)
»  Caused by: org.elasticsearch.gateway.CorruptStateException: org.elasticsearch.xcontent.XContentParseException: [-1:32054] [index_template] failed to parse field [index_template]
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService.readXContent(PersistedClusterStateService.java:674)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService.lambda$loadOnDiskState$6(PersistedClusterStateService.java:572)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService.consumeFromType(PersistedClusterStateService.java:716)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService.loadOnDiskState(PersistedClusterStateService.java:571)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService$Writer.assertOnCommit(PersistedClusterStateService.java:1242)
»  	... 10 more
»  Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:32054] [index_template] failed to parse field [index_template]
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.fromXContent(ComposableIndexTemplateMetadata.java:67)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.NamedXContentRegistry$Entry.lambda$new$0(NamedXContentRegistry.java:54)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:147)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:414)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.cluster.metadata.Metadata$Builder.fromXContent(Metadata.java:2660)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.gateway.PersistedClusterStateService.readXContent(PersistedClusterStateService.java:672)
»  	... 14 more
»  Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:32054] [index_template] failed to parse field [template]
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.cluster.metadata.ComposableIndexTemplate.parse(ComposableIndexTemplate.java:102)
»  	at org.elasticsearch.server@8.10.4/org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.lambda$static$1(ComposableIndexTemplateMetadata.java:50)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
»  	... 23 more
»  Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:32052] [template] unknown field [lifecycle]
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.lambda$errorOnUnknown$2(ObjectParser.java:105)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:299)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)
»  	at org.elasticsearch.xcontent@8.10.4/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)
»  	... 30 more
»  
```

### PR DESCRIPTION
**Pull request by andreidan**
Data stream lifecycle has been made available only in 8.11 however we now have a stack template that makes use of it (`.kibana-reporting`).

In an 8.10-8.14 mixed cluster environment we could cause a cluster state corruption if we install the `kibana-reporting` (with `lifecycle:{}`) template before all nodes _know_ of data stream lifecycle (8.10 does not).

This changes the `StackTemplateRegistry` to wait for all nodes in the cluster to be aware of data stream lifecycle before installing the templates.

Relates to https://github.com/elastic/elasticsearch/pull/106259
Fixes https://github.com/elastic/elasticsearch/issues/106461

### CODE REVIEW

**Review by jbaiera — COMMENTED** [review]
I left some comments, but I've got some reservations on this as an approach:

First, I don't think this is how we should be using NodeFeatures... It think it'd be better if we had a feature called `DATA_STREAM_LIFECYCLE_FEATURE` and checked for that in the registry, since that is primarily what we want available, not just that a template for Kibana is using it.

I'm taking a closer look at the issue that led to this fix and I'm a bit miffed that our mixed cluster tests do not follow our rolling update policy of upgrading the active master last. Sure, we could add this guard to make the tests happier and more resilient, which is a big pro, but in practice there wouldn't be anything that stops a user from adding a template that uses DSL and causing the same problem on this cluster.

Do we have a DSL node feature that exists today? Should we? The problem is that if we don't already have one then we're likely to have issues when checking for it across the versions that don't already have it. If we don't have one then I'm ok with moving forward with the change, but we're definitely accepting some tech debt in doing so.

**Comment by jbaiera** [comment]
Ok, I have confirmed that we're actually able to add a new feature for data stream lifecycles to be returned from a new method at `DataStreamFeatures#getHistoricalFeatures` - This would let us add a feature for DSL which we could then check for in the template registry, and that would avoid us from blocking the installation of the template when in a mixed cluster with 8.11-8.13 which (I assume if lifecycles were added in 8.11) should be capable of accepting the template just fine. Thoughts?

File: x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java [hunk 1]
```diff
@@ -326,9 +330,9 @@ protected boolean requiresMasterNode() {
...
     @Override
     protected boolean isClusterReady(ClusterChangedEvent event) {
-        // Ensure current version of the components are installed only once all nodes are updated to 8.9.0.
-        // This is necessary to prevent an error caused nby the usage of the ignore_missing_pipeline property
-        // in the pipeline processor, which has been introduced only in 8.9.0
-        return featureService.clusterHasFeature(event.state(), STACK_TEMPLATES_FEATURE);
+        // Ensure current version of the components are installed only once all nodes are aware of kibana reporting being managed by DSL.
+        // Data stream lifecycle has been available only after 8.11 so installing `.kibana-reporting` with the `lifecycle: {}`
+        // configuration in 8.10 would be problematic
+        return featureService.clusterHasFeature(event.state(), KIBANA_REPORTING_MANAGED_BY_LIFECYCLE);
```
[the remark this answers is not in the document]
Comment (andreidan) [reply x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java:336]: We don't need to backport it, the code that we're releasing here (8.14) will install this template only when the entire cluster reached 8.14.

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
> Ok, I have confirmed that we're actually able to add a new feature for data stream lifecycles to be returned from a new method at DataStreamFeatures#getHistoricalFeatures - This would let us add a feature for DSL which we could then check for in the template registry, and that would avoid us from blocking the installation of the template when in a mixed cluster with 8.11-8.13 which (I assume if lifecycles were added in 8.11) should be capable of accepting the template just fine. Thoughts?

Thanks for the review Jimmy. Apologies but I'm not entirely sure I understand what would this solve? Are you suggesting we should NOT wait for the entire cluster to be on `8.14` before attempting to install these templates but do it earlier? (say, if every node is on `8.11`)

If that's the case, I'd rather not as we only introduced the `lifecycle` configuration for `kibana-reporting` only in `8.14`. We also made other changes to the template starting with `8.14` (like the `ingore_missing_component_templates`) so I wouldn't want this template to be installed in `8.11` (I'm note entirely sure of the downstream implications if we have a prolongued mixed cluster - i.e. what does this mean in Kibana? is Kibana ready for this in `8.11` ? ) 

Using the node feature functionality as it is in this PR is essentially saying "when this distribution is released, wait until all nodes in the cluster have this feature - i.e. are at least on the distribution that released this node feature" - I think this is what we want here, unless I'm missing something?

File: modules/data-streams/src/main/java/org/elasticsearch/datastreams/DataStreamFeatures.java [hunk 2]
```diff
@@ -8,19 +8,28 @@
...
 
+import java.util.Map;
 import java.util.Set;
 
 /**
  * Provides the features for data streams that this version of the code supports
  */
 public class DataStreamFeatures implements FeatureSpecification {
 
+    public static final NodeFeature SUPPORTS_DATA_STREAM_LIFECYCLE = new NodeFeature("supports_data_stream_lifecycle");
```
Comment (jbaiera) [inline modules/data-streams/src/main/java/org/elasticsearch/datastreams/DataStreamFeatures.java:26]: Looking around, the string name for these kinds of node features follow a dotted and hierarchical structure. Maybe we should go with

```suggestion
    public static final NodeFeature DATA_STREAM_LIFECYCLE = new NodeFeature("data_stream.rollover.lifecycle");
```

File: x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java [hunk 3]
```diff
@@ -38,9 +38,13 @@
 public class StackTemplateRegistry extends IndexTemplateRegistry {
     private static final Logger logger = LogManager.getLogger(StackTemplateRegistry.class);
 
-    // Current version of the registry requires all nodes to be at least 8.9.0.
+    // Historical node feature kept here as LegacyStackTemplateRegistry is deprecated
     public static final NodeFeature STACK_TEMPLATES_FEATURE = new NodeFeature("stack.templates_supported");
 
+    // this node feature is a redefinition of {@link DataStreamFeatures#SUPPORTS_DATA_STREAM_LIFECYCLE} and it's meant to avoid adding a
+    // dependency to the data-streams module just for this
+    public static final NodeFeature SUPPORTS_DATA_STREAM_LIFECYCLE = new NodeFeature("supports_data_stream_lifecycle");
```
Comment (jbaiera) [inline x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java:46]: Same suggestion here
```suggestion
    public static final NodeFeature DATA_STREAM_LIFECYCLE = new NodeFeature("data_stream.rollover.lifecycle");
```

File: x-pack/plugin/stack/src/test/java/org/elasticsearch/xpack/stack/StackTemplateRegistryTests.java [hunk 4]
```diff
@@ -538,6 +540,11 @@ public void testThatTemplatesAreNotDeprecated() {
             .forEach(p -> assertFalse((Boolean) p.get("deprecated")));
     }
 
+    public void testDataStreamLifecycleNodeFeatureId() {
+        // let's make sure these ids remain in-sync
+        assertThat(StackTemplateRegistry.SUPPORTS_DATA_STREAM_LIFECYCLE.id(), is(DataStreamFeatures.SUPPORTS_DATA_STREAM_LIFECYCLE.id()));
```
Comment (jbaiera) [inline x-pack/plugin/stack/src/test/java/org/elasticsearch/xpack/stack/StackTemplateRegistryTests.java:545]: And also another spot
```suggestion
        assertThat(StackTemplateRegistry.DATA_STREAM_LIFECYCLE.id(), is(DataStreamFeatures.DATA_STREAM_LIFECYCLE.id()));
```

**Review by jbaiera — COMMENTED** [review]
Left some quick suggestions for name styling to have the lifecycle feature match other existing features better

File: x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java [hunk 5]
```diff
@@ -38,9 +38,13 @@
 public class StackTemplateRegistry extends IndexTemplateRegistry {
     private static final Logger logger = LogManager.getLogger(StackTemplateRegistry.class);
 
-    // Current version of the registry requires all nodes to be at least 8.9.0.
+    // Historical node feature kept here as LegacyStackTemplateRegistry is deprecated
     public static final NodeFeature STACK_TEMPLATES_FEATURE = new NodeFeature("stack.templates_supported");
 
+    // this node feature is a redefinition of {@link DataStreamFeatures#SUPPORTS_DATA_STREAM_LIFECYCLE} and it's meant to avoid adding a
```
Comment (jbaiera) [inline x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java:44]:
```suggestion
    // this node feature is a redefinition of {@link DataStreamFeatures#DATA_STREAM_LIFECYCLE} and it's meant to avoid adding a
```

**Review by jbaiera — APPROVED** [review]
LGTM! I found one last rename that I missed, but once that's in I think this is all good. Thanks Andrei!
