### PR TITLE
[Monitoring] LocalExporter should catch synchronous exceptions

### LINKED ISSUE #35797: [Monitoring] Make LocalExporter::openBulk Async
This is a spin-off from #35765 and #35743, but specifically targeting the `LocalExporter` bulk initialization code.

Like #35765 is doing with the `HttpExporter::openBulk`, the `LocalExporter::openBulk` initialization code needs to be made truly, fully async as well.

### PR DESCRIPTION
**Pull request by pickypg**
In the unlikely scenario that `LocalExporter::resolveBulk` throws an exception, then we should mark the `listener` as having failed.

As discussed with @martijnvg, this is a follow-up to #35765, which already ensured that this call was async, but did not catch the [unlikely] exception.

A future PR should cleanup the `LocalExporter` to make it a bit cleaner to test (more unit tests and less integration tests taking 20s+) as well remove the dependence on receiving cluster state changes to initialize the exporter.

Closes #35797

### CODE REVIEW

File: x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java [hunk 1]
```diff
@@ -145,7 +144,11 @@ public void openBulk(final ActionListener<ExportBulk> listener) {
         if (state.get() != State.RUNNING) {
             listener.onResponse(null);
         } else {
-            listener.onResponse(resolveBulk(clusterService.state(), false));
+            try {
+                listener.onResponse(resolveBulk(clusterService.state(), false));
+            } catch (RuntimeException e) {
```
Comment (martijnvg) [inline x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java]: maybe just catch `Exception`?

**Review by martijnvg — APPROVED** [review]
LGTM - Thanks for addressing this!

File: x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java (hunk 1 above)
Comment (pickypg) [reply x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java]: No reason not to. 👍

**Comment by pickypg** [comment]
6.x/6.6: 64f8f86
