### PR TITLE
Decouple pipeline reductions from final agg reduction

### LINKED ISSUE #44914: auto_date_histogram fails where date_histogram does not
We are planning to port most of Stack Monitoring current aggregations to use `auto_date_histogram` in lieu of `date_histogram` as part of https://github.com/elastic/kibana/issues/37246.

We noticed that `auto_date_histogram` supports most of aggregations that `date_histogram` does, but fails (on `fetch` phase) with `bucket_script`. As a first pass, I tried replacing the existing `date_histogram` usage with `auto_date_histogram` and it broke:

```http
GET .monitoring-logstash-*/_search
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "logstash_stats.timestamp": {
              "format": "epoch_millis",
              "gte": 1563551274281,
              "lte": 1563554874281
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "check": {
      "auto_date_histogram": {
        "field": "logstash_stats.timestamp",
        "buckets": 10
      },
      "aggs": {
        "pipelines_nested": {
          "nested": {
            "path": "logstash_stats.pipelines"
          },
          "aggs": {
            "by_pipeline_id": {
              "terms": {
                "field": "logstash_stats.pipelines.id",
                "size": 1000
              },
              "aggs": {
                "by_pipeline_hash": {
                  "terms": {
                    "field": "logstash_stats.pipelines.hash",
                    "size": 1000
                  },
                  "aggs": {
                    "by_ephemeral_id": {
                      "terms": {
                        "field": "logstash_stats.pipelines.ephemeral_id",
                        "size": 1000
                      },
                      "aggs": {
                        "events_stats": {
                          "stats": {
                            "field": "logstash_stats.pipelines.events.out"
                          }
                        },
                        "throughput": {
                          "bucket_script": {
                            "script": "params.max - params.min",
                            "buckets_path": {
                              "min": "events_stats.min",
                              "max": "events_stats.max"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

This query fails where the same query works if you replace `auto_date_histogram` with `date_histogram` (and use `interval` instead of `buckets`). Anyone attempting to run this on an existing cluster will likely need to shift the date `range` query.

### PR DESCRIPTION
**Pull request by polyfractal**
Historically only two extra activities happened in the final reduction: empty buckets were filled, and pipeline aggs were reduced (since it was the final reduction, this was safe).  Usage of the final reduction is growing however.  Auto-date-histo might need to perform many reductions on final-reduce to merge down buckets, CCS may need to side-step the final reduction if sending to a different cluster, etc

Having pipelines generate their output in the final reduce was convenient, but is becoming increasingly difficult to manage as the rest of the agg framework advances.

This commit decouples pipeline aggs from the final reduction:

1. Introduces a new "top level" reduce, which should be called at the beginning of the reduce cycle (e.g. from the SearchPhaseController)
2. Adds a `materializePipeline()` method to InternalAggs and InternalMultiBucket.  This is essentially the final reduce for pipelines
3. Makes reductions on pipelines a no-op

By separating pipeline reduction into their own set of methods, aggregations are free to use the final reduction for whatever purpose without worrying about generating pipeline results which are non-reducible

Closes https://github.com/elastic/elasticsearch/issues/44914, predecessor PR was https://github.com/elastic/elasticsearch/pull/45359

### CODE REVIEW

**Comment by polyfractal** [comment]
Note: the first commit contains the main changes, the second commit (`"Remove unnecessary doReduce()"`) just does a bulk rename since `doReduce()` is no longer needed.  So reviewing the first commit first would be less noisy.

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java [hunk 1]
```diff
@@ -91,10 +92,46 @@ public void writeTo(StreamOutput out) throws IOException {
...
+    public static InternalAggregations topLevelReduce(List<InternalAggregations> aggregationsList, ReduceContext context) {
+        InternalAggregations reduced = reduce(aggregationsList, context);
+        if (reduced == null) {
+            return null;
+        }
+
+        if (context.isFinalReduce()) {
+            List<InternalAggregation> reducedInternalAggs = reduced.getInternalAggregations();
+            reducedInternalAggs = reducedInternalAggs.stream()
+                .map(agg -> agg.materializePipelines(agg, context)).collect(Collectors.toList());
```
Comment (not-napoleon) [inline server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java]: nit: I'm not sure if we have a style guide for streams yet, but I'd strongly suggest putting the `.collect()` call on its own line.  Personally, I find streams easier to read if each step gets a line.

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregation.java [hunk 2]
```diff
@@ -141,6 +142,28 @@ public static int countInnerBucket(Aggregation agg) {
...
+     */
+    @Override
+    public final InternalAggregation materializePipelines(InternalAggregation reducedAggs, ReduceContext reduceContext) {
+        assert reduceContext.isFinalReduce();
+        List<B> materializedBuckets = materializeBuckets(reduceContext);
+        return super.materializePipelines(create(materializedBuckets), reduceContext);
+    }
+
+    private List<B> materializeBuckets(ReduceContext reduceContext) {
+        return getBuckets().stream().map(internalBucket -> {
```
Comment (not-napoleon) [inline server/src/main/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregation.java]: I'm -0 on using streams here.  IMHO, Streams are only good when they serve to enhance readability, and I'm not sure they're doing that here, relative to the equivalent loops.  I'm ok with leaving it this way if you prefer it, but it's not my first choice.  Unless of course you've already looked at the loop based version and decided it's even harder to read, in which case I guess this is the lesser evil.

**Review by not-napoleon — APPROVED** [review]
Someone who knows Significant Terms aggregation better should probably comment on that part, I'm just taking it on faith.  Otherwise this looks good to me.  I left two nits about the use of the Streams API, but they're both a matter of opinion, so don't feel like you have to fix them.

File: server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregation.java [hunk 3]
```diff
@@ -126,23 +126,25 @@ public String getName() {
         return name;
     }
 
+    /**
+     * Creates the output from all pipeline aggs that this aggregation is associated with.  Should only
+     * be called after all aggregations have been fully reduced
+     */
+    public InternalAggregation materializePipelines(InternalAggregation reducedAggs, ReduceContext reduceContext) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregation.java]: I wonder if instead of adding `materializePipelines` in the `PipelineAggregator` we could keep `reduce` and just change the name here to be `reducePipeline`. The renaming is not really needed since pipeline and aggregator don't share a base class so there is no confusion ?

**Review by jimczi — COMMENTED** [review]
+1 to separate the aggs reduction and the pipeline reduction. However I wonder if all the renamings are needed. Could we just change `InternalAggregations` to separate `reduce` and `reducePipeline` ?

**Comment by polyfractal** [comment]
Review comments addressed.

I renamed the "materialize" stuff back to "reduce", although there's a small hiccup.  Because InternalAggregations's `reduce()` is essentially now `reducePipelines()`, we are left over with the abstract `doReduce()`.

I first renamed that to `reduce()` which makes sense, although it modifies some 70+ files :)

In the second commit I changed it to `doReduce()` which has a much more minimal impact (because all the aggs implemented `doReduce()` abstract method before), although a bit strange conceptually as there isn't a `reduce()` anymore.

I don't have a strong opinion either way, although I'd lean towards renaming to `reduce()` and just accepting that it touches every single aggregation :)

**Review by jimczi — APPROVED** [review]
The change looks good to me.

> I don't have a strong opinion either way, although I'd lean towards renaming to reduce() and just accepting that it touches every single aggregation :)

+1 to move back to `reduce` and no need for another round of review since the change should be straightforward ;).

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Comment by polyfractal** [comment]
Oh my goodness, I thought I merged this.  Fixing up conflicts so that it can go in. 

Oops!

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix
