### PR TITLE
Cluster state from API should always have a master

### LINKED ISSUE #38331: [CI] SpecificMasterNodesIT#testElectOnlyBetweenMasterNodes fails
Seen at least three times in master in the last few days:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/497/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1777/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1710/console

Latest reproduce line:
```
./gradlew :server:integTest \
  -Dtests.seed=2CFBF83AF54213EC \
  -Dtests.class=org.elasticsearch.cluster.SpecificMasterNodesIT \
  -Dtests.method="testElectOnlyBetweenMasterNodes" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Africa/Kinshasa \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Running repeatedly on Ubuntu didn't reproduce after 50 runs.

Logs contain NPEs:
```
14:52:15   1> java.lang.NullPointerException: null
14:52:15   1> 	at org.elasticsearch.test.InternalTestCluster.getMasterName(InternalTestCluster.java:1913) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:52:15   1> 	at org.elasticsearch.test.InternalTestCluster.getMasterName(InternalTestCluster.java:1902) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:52:15   1> 	at org.elasticsearch.test.InternalTestCluster.nonMasterClient(InternalTestCluster.java:776) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:52:15   1> 	at org.elasticsearch.cluster.SpecificMasterNodesIT.lambda$testElectOnlyBetweenMasterNodes$0(SpecificMasterNodesIT.java:122) ~[test/:?]
14:52:15   1> 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846) [framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
```
But there are also several earlier connection Exceptions like:

```
14:52:14   1> Caused by: java.net.ConnectException: Connection refused
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today the `TransportClusterStateAction` ignores the state passed by the
`TransportMasterNodeAction` and obtains its state from the cluster applier.
This might be inconsistent, showing a different node as the master or maybe
even having no master.

This change adjusts the action to use the passed-in state directly, and adds
tests showing that the state returned is consistent with our expectations even
if there is a concurrent master failover.

Fixes #38331
Relates #38432

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java [hunk 1]
```diff
@@ -79,50 +80,50 @@ protected ClusterStateResponse newResponse() {
...
+            : clusterState -> clusterState.metaData().version() >= request.waitForMetaDataVersion();
+
+        final Predicate<ClusterState> acceptableClusterStateOrNotMasterPredicate = request.local()
+            ? acceptableClusterStatePredicate
+            : acceptableClusterStatePredicate.or(clusterState -> clusterState.nodes().isLocalNodeElectedMaster() == false);
 
-                    @Override
-                    public void onClusterServiceClose() {
-                        listener.onFailure(new NodeClosedException(clusterService.localNode()));
+        if (acceptableClusterStatePredicate.test(state)) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java]: 👍

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
Backported to 7.2 as 52e8a64 (and unmuted the associated test)
