### PR TITLE
Fix scaled_float numeric type in aggregations

### LINKED ISSUE #22350: `scaled_float` are used as longs in aggregations
Originated from https://github.com/elastic/kibana/issues/9568

For `scaled_float` type the expectation is that aggregations works on the scaled float value. For instance for the value "6.98" with a scaling factor of 10 the bucket "6.9" should be used.
Currently the aggregations use the long value of the scaled float to compute the buckets. So instead of "6.9" the created bucket is "6". 

Steps to reproduce:

````
PUT t 
{
   "mappings": {
      "t": {
         "properties": {
            "ctMultiplier": {
               "scaling_factor": 10,
               "type": "scaled_float",
               "store": true
            }
         }
      }
   }
}

POST t/t/1
{
    "ctMultiplier": "6.8"
}

POST t/t/2
{
    "ctMultiplier": "6.9"
}


GET _search
{
    "size": 0,
    "aggs": {
        "t": {
            "terms": {
                "field": "ctMultiplier"
            }
        }
    }
}
`````

### PR DESCRIPTION
**Pull request by jimczi**
`scaled_float` should be used as FLOAT in aggregations but currently they are used as LONG.
This change fixes this issue and adds a simple it test for it.

Fixes #22350

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/ScaledFloatFieldMapper.java [hunk 1]
```diff
@@ -504,7 +504,10 @@ public Index index() {
 
         @Override
         public NumericType getNumericType() {
-            return scaledFieldData.getNumericType();
+            /**
+             * {@link ScaledFloatLeafFieldData#getDoubleValues()} transforms the raw long values in `scaled` floats.
+             */
+            return NumericType.FLOAT;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/ScaledFloatFieldMapper.java]: I don't think that will change anything in practice, but I think the correct value would be `DOUBLE`?

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by jimczi** [comment]
Thanks @jpountz
This is now pushed to master and 5.2
