### PR TITLE
[Entitlements] Add missing file entitlements for server

### LINKED ISSUE #122566: [CI] EntitlementsDeniedIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122567: [CI] EntitlementsAllowedIT class failing
**Build Scans:**
- [elasticsearch-periodic #6391 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/2fqmmrdpyn4gu)
- [elasticsearch-pull-request #56325 / part-1-entitlements](https://gradle-enterprise.elastic.co/s/ek5r6deaugpf4)
- [elasticsearch-pull-request #56129 / part-1](https://gradle-enterprise.elastic.co/s/x2o5zy4ygkosq)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [main] 3 failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedIT (0.5% fail rate in 594 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 233 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122568: [CI] EntitlementsAllowedNonModularIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122569: [CI] EntitlementsDeniedNonModularIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mosche**
Add missing file entitlements for server.

closes https://github.com/elastic/elasticsearch/issues/122569, closes https://github.com/elastic/elasticsearch/issues/122568, closes https://github.com/elastic/elasticsearch/issues/122567, closes https://github.com/elastic/elasticsearch/issues/122566 

(Note, some failures are due to a `NoSuchAlgorithmException` when fips is enabled. This issue is unrelated to entitlements)

### CODE REVIEW

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java [hunk 1]
```diff
@@ -149,8 +150,26 @@ private static PolicyManager createPolicyManager() {
...
+                                FileData.ofPath(Path.of("/proc/loadavg"), READ),
+                                // control group stats on Linux. cgroup v2 stats are in an unpredicable
+                                // location under `/sys/fs/cgroup`, so unfortunately we have to allow
+                                // read access to the entire directory hierarchy.
+                                FileData.ofPath(Path.of("/proc/self/cgroup"), READ),
+                                FileData.ofPath(Path.of("/sys/fs/cgroup/"), READ),
+                                // // io stats on Linux
+                                FileData.ofPath(Path.of("/proc/self/mountinfo"), READ),
+                                FileData.ofPath(Path.of("/proc/diskstats"), READ),
+                                FileData.ofPath(Path.of("/etc/os-release"), READ)
```
Comment (ldematte) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java:172]: This is duplicated

**Review by ldematte — APPROVED** [review]
LGTM

**Comment by mosche** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/122750)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
