### PR TITLE
Fix searching a filtered and unfiltered data stream alias

### LINKED ISSUE #95786: Searching a filtered and a non-filtered data stream alias filters the result
### Elasticsearch Version

8.x

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

Searching a filtered and a non-filtered data stream alias that both point to the same datastream currently filter the result set 
(relevant [code](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L714)  )

The desired behaviour is to **not** consider the filter in this case and return the (wider) un-filtered result.

(the desired behaviour for data stream aliases currently exists for indices aliases - relevant code that abandons applying the filter for _index aliases_ is [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L743) )

### Steps to Reproduce

```
PUT _index_template/datastream-template
{
  "index_patterns": [
    "my-datastream"
  ],
  "data_stream": {
  }, 
  "template": {
    "aliases": {
      "first_alias": {
        "filter": {
          "term": {
            "message": "first"
          }
        }
      },
      "second_alias": {}
    }
  },
  "composed_of": []
}



POST my-datastream/_doc
{
  "message":"first",
  "@timestamp":"2023-05-02T08:02:40.420Z"
}


POST my-datastream/_doc
{
  "message":"second",
  "@timestamp":"2023-05-02T08:02:40.420Z"
}

GET first_alias,second_alias/_search
```

The `GET first_alias,second_alias/_search` call only returns one hit, while it should return 2.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by andreidan**
This fixes the case when a `_search` request is targeting multiple aliases that point to the _same data stream_, some being filtered and some unfiltered.

Before this fix, such a scenario would apply the encountered filters as `should` conditions on a `BoolQuery`, despite the request containing an unfiltered (match_all) alias for the same data stream.

This fixes this scenario to disregard the filters when an unfiltered alias is encountered in the resolved expressions, targeting the same data stream.

This also fixes the same scenario for a request that targets the data stream name and a filtered alias (the expected result is that the filter should be disregarded)

Fixes #95786

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 1]
```diff
@@ -701,19 +701,40 @@ public String[] indexAliases(
         IndexAbstraction ia = state.metadata().getIndicesLookup().get(index);
         DataStream dataStream = ia.getParentDataStream();
         if (dataStream != null) {
+            if (skipIdentity == false && resolvedExpressions.contains(dataStream.getName())) {
+                return null;
+            }
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java:706]: This enables us to skip the filters when the request targets the data stream name and a filtered alias

File: server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java [hunk 2]
```diff
@@ -1672,9 +1672,8 @@ public void testIndexAliasesDataStreamAliases() {
             String[] result = indexNameExpressionResolver.indexAliases(state, index, x -> true, x -> true, false, resolvedExpressions);
             assertThat(result, nullValue());
         }
-
         {
-            // Only resolve aliases that refer to dataStreamName1 where the filter is not null
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java:1677]: This is the bug that we fix in this PR

File: server/src/test/java/org/elasticsearch/indices/IndicesServiceTests.java [hunk 3]
```diff
@@ -733,14 +734,16 @@ public void testBuildAliasFilterDataStreamAliases() {
...
         {
+            // querying an unfiltered and a filtered alias for the same data stream should drop the filters
             String index = backingIndex1.getIndex().getName();
             AliasFilter result = indicesService.buildAliasFilter(state, index, Set.of("logs_foo", "logs", "logs_bar"));
-            assertThat(result.getAliases(), arrayContainingInAnyOrder("logs_foo", "logs"));
-            BoolQueryBuilder filter = (BoolQueryBuilder) result.getQueryBuilder();
-            assertThat(filter.filter(), empty());
-            assertThat(filter.must(), empty());
-            assertThat(filter.mustNot(), empty());
-            assertThat(filter.should(), containsInAnyOrder(QueryBuilders.termQuery("foo", "baz"), QueryBuilders.termQuery("foo", "bar")));
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/indices/IndicesServiceTests.java:743]: This is the bug we fix in this PR

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java (hunk 1 above)
Comment (dakrone) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java:706]: Can you add this as a comment in the code?

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 4]
```diff
@@ -701,19 +701,40 @@ public String[] indexAliases(
...
+            List<String> requiredAliases = null;
+            for (DataStreamAlias dataStreamAlias : aliasesForDataStream) {
+                if (requiredDataStreamAlias.test(dataStreamAlias)) {
+                    if (requiredAliases == null) {
+                        requiredAliases = new ArrayList<>(aliasesForDataStream.size());
+                    }
+                    requiredAliases.add(dataStreamAlias.getName());
+                } else {
+                    // we have a non-required alias for this data stream so no need to check further
+                    return null;
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java:731]: Why does the predicate not passing for one alias name mean that no aliases are returned? What if `(dsa) -> dsa.getName().contains("foo")` was passed in as the `Predicate<DataStreamAlias> requiredDataStreamAlias` predicate, shouldn't this still go through all of the resolved aliases instead of short-circuiting?

**Review by dakrone — COMMENTED** [review]
I left a comment about the predicate check that I don't understand

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java (hunk 4 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java:732]: I believe the `required` terminology is a bit confusing here, so I totally understand where you're coming from. 

However, I think the documentation for the method clarifies why `null` is returned
```
Only aliases where the given predicate tests successfully are returned. If the indices list contains a non-required reference to the index itself - null is returned. Returns {@code null} if no filtering is required.
```

I believe the method could use more terminology that references alias filtering as that's what it does. It's currently called in 3 places - in 2 places where we don't care about filtering at all (we just want all the aliases) where the predicates are 
```
aliasMetadata -> true,
dataStreamAlias -> true,
```
and a 3rd place where we are interested in the filtering required where the predicates are 
```
AliasMetadata::filteringRequired, 
DataStreamAlias::filteringRequired
```

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by dakrone** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.7|[](https://github.com/elastic/elasticsearch/pull/96077)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
