### PR TITLE
[Test] Do not rely on MockZenPing for Azure tests

### LINKED ISSUE #27917: Azure tests rely on MockZenPing
The Azure tests currently do not disable the `MockZenPing` class which is used to shortcut cluster forming in our testing infra. As a result they don't really test what they want to test. We I disabled `MockZenPing` the tests fail because they rely on the internal test cluster to hard code the node's addresses. This has also changed with #27859 so the tests need to be adapted.

@tlrx has gracefully agreed to take this on.

### PR DESCRIPTION
**Pull request by tlrx**
This commit changes some Azure tests so that they do not rely on
MockZenPing and TestZenDiscovery anymore, but instead use a mocked
AzureComputeService that exposes internal test cluster nodes as if
they were real Azure nodes.

Related to #27859

Closes #27917, #11533

### CODE REVIEW

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java [hunk 1]
```diff
@@ -60,13 +81,107 @@ protected Settings nodeSettings(int nodeOrdinal) {
...
+         */
+        @Override
+        protected AzureUnicastHostsProvider createUnicastHostsProvider(final Settings settings,
+                                                                       final AzureComputeService azureComputeService,
+                                                                       final TransportService transportService,
+                                                                       final NetworkService networkService) {
+            return new AzureUnicastHostsProvider(settings, azureComputeService, transportService, networkService) {
+                @Override
+                protected String resolveInstanceAddress(final HostType hostType, final RoleInstance instance) {
+                    if (hostType == HostType.PRIVATE_IP) {
```
Comment (bleskes) [inline plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java]: why is this needed? we set the private IP on the RoleInstance, no?

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java [hunk 2]
```diff
@@ -49,6 +66,10 @@ protected Settings nodeSettings(int nodeOrdinal) {
             .put(super.nodeSettings(nodeOrdinal))
             .put("discovery.zen.hosts_provider", "azure");
 
+        // Make the test run faster
+        builder.put(ZenDiscovery.JOIN_TIMEOUT_SETTING.getKey(), "50ms")
```
Comment (bleskes) [inline plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java]: I suspect these will be too small and we'll have time outs.

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureMinimumMasterNodesTests.java [hunk 3]
```diff
@@ -42,52 +37,35 @@
...
-        Settings.Builder builder = Settings.builder()
+        return Settings.builder()
                 .put(super.nodeSettings(nodeOrdinal))
                 .put("discovery.zen.minimum_master_nodes", 2)
-                // Make the test run faster
-                .put(ZenDiscovery.JOIN_TIMEOUT_SETTING.getKey(), "50ms")
-                .put(ZenDiscovery.PING_TIMEOUT_SETTING.getKey(), "10ms")
-                .put("discovery.initial_state_timeout", "100ms");
-        return builder.build();
+                .put("discovery.initial_state_timeout", "100ms")
```
Comment (bleskes) [inline plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureMinimumMasterNodesTests.java]: this is interesting - we explicitly check it's not there? https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java#L586

**Review by bleskes — COMMENTED** [review]
I left some questions. Looks good but I want to double check.

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java (hunk 2 above)
Comment (tlrx) [reply plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java]: That was the previous value in AzureMinimumMasterNodesTests and I moved it here so that other tests execute faster. Do you have any recommendation or should we use the default value?

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureMinimumMasterNodesTests.java (hunk 3 above)
Comment (tlrx) [reply plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureMinimumMasterNodesTests.java]: Yes

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java (hunk 1 above)
Comment (tlrx) [reply plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java]: For private IP, AzureUnicastHostProvider resolves the network address from the RoleInstance.getIPAddress() which returns an IP address like 127.0.0.1 with no port. I suppose that this is OK on Azure, but in tests we can have multiple nodes on the same IP address. 

This is why it needs a slightly different way to resolve private IP addresses in order to include the port number. Then it will be correctly translated by [transportService.addressesFromString()](https://github.com/elastic/elasticsearch/blob/5a7c8bb04ed135be1823a4db6b08f7481d7d22c0/plugins/discovery-azure-classic/src/main/java/org/elasticsearch/discovery/azure/classic/AzureUnicastHostsProvider.java#L244) that only ping 1 port.

Before this change the test used ports 9400 and 9401 which were corresponding to the default ports used in TcpTransport.

**Comment by bleskes** [comment]
Ok. Thanks for looking. it sounds to me it's a bug in the azure system?
what happens if someone uses custom ports?

**Comment by tlrx** [comment]
> Ok. Thanks for looking. it sounds to me it's a bug in the azure system? what happens if someone uses custom ports?

Before commit e2ab62596f956c0a16b1899f3bfabd4c65a88552 on v2.1.0, the private IP address was resolved by the Azure discovery plugin using the default port range. So` 127.0.0.1` was resolved to `127.0.0.1:9400`, `127.0.0.1:9401`, `127.0.0.1:9402` etc. 

After e2ab62596f956c0a16b1899f3bfabd4c65a88552 the private IP address is resolved to only 1 address using the default port range too, so `127.0.0.1` is resolved to `127.0.0.1:9400` only. I don't think this change has been documented and it was not caught because the test was already muted at that time (apparently because of `https://github.com/elastic/elasticsearch-cloud-azure/issues/89` but the fix didn't remove the AwaitsFix annotation). 

So in order to use multiple nodes on a same Azure VM with custom ports and private IP host type resolution, the nodes must have preconfigured tcp ports and different (or same) seed node whose port number is defined by `transport.profiles.default.port` setting, so that the AzureUnicastHostProvider will correctly resolve

But the tests use ports provided by the OS and it does not follow any range so it's not possible to configure `transport.profiles.default.port` easily... we could also update `transport.profiles.default.port` before starting each new node but I find it easier to do this way.

**Comment by dadoonet** [comment]
> So in order to use multiple nodes on a same Azure VM with custom ports

@tlrx About custom ports see also #18790

**Comment by bleskes** [comment]
@tlrx I was referring to people running a single node on a single vm with a custom port, but I guess at that point Azure discovery won't help you. I'll LGTM the PR.

File: plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java (hunk 2 above)
Comment (bleskes) [reply plugins/discovery-azure-classic/src/test/java/org/elasticsearch/cloud/azure/classic/AbstractAzureComputeServiceTestCase.java]: that's hard to say. 10ms ping cycle is way short (we use to make sure we do at least one but we simplified the code at the expense of losing this). How about 1s and see?

**Review by bleskes — APPROVED** [review]

**Comment by tlrx** [comment]
Thanks Boaz! I increased the timeouts to 1s, 500ms and 1s.
