### PR TITLE
Forbidding dimension fields in aggregated stats - only allowed in grouping attributes

### LINKED ISSUE #135335: Fix aggregations on dimension fields
The following query is not supported:

```
TS kibana_sample_data_logstsdb 
| STATS results = count(agent.keyword) by TBUCKET(1day)
```

`Unexpected error from Elasticsearch: unresolved_exception - Invalid call to dataType on an unresolved object ?LASTOVERTIME_$1`

The issue is that we try to use `last_over_time` implicitly, even though `agent.keyword` is a dimension. Here, this should work as a regular agg in `FROM`.

### PR DESCRIPTION
**Pull request by pabloem**
…uping attributes - fixes #135335

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java [hunk 1]
```diff
@@ -202,6 +203,18 @@ protected void checkTimeSeriesAggregates(Failures failures) {
...
+                        fail(
+                            this,
+                            "cannot use dimension field [{}] in a time-series aggregation function [{}]. "
+                                + "Dimension fields can only be used for grouping in a BY clause. To aggregate "
+                                + "dimension fields, use the FROM command instead of the TS command.",
+                            fa.sourceText(),
+                            outer.sourceText()
+                        )
+                    );
+                }
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java]: I think we also need to check for the inner aggregation.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java [hunk 2]
```diff
@@ -119,6 +119,7 @@ public boolean equals(Object obj) {
     @Override
     public void postAnalysisVerification(Failures failures) {
         super.postAnalysisVerification(failures);
+        // We forbid grouping by a metric field itself. Metric fields are allowed only inside aggregate functions.
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java:122]: leftover?

**Review by dnhatn — COMMENTED** [review]
I've left a comment, thanks Pablo!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java (hunk 2 above)
Comment (pabloem) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java:122]: no - this comment is documenting the coe below!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java (hunk 1 above)
Comment (pabloem) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/TimeSeriesAggregate.java]: done! lmk what you thinik!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 3]
```diff
@@ -2689,6 +2689,25 @@ public void testNoMetricInStatsByClause() {
...
+        assertThat(
+            error("TS test | STATS count(host) BY bucket(@timestamp, 1 minute)", tsdb),
+            equalTo(
+                "1:11: cannot use dimension field [host] in a time-series aggregation function [count(host)]. "
+                    + "Dimension fields can only be used for grouping in a BY clause. "
+                    + "To aggregate dimension fields, use the FROM command instead of the TS command."
+            )
+        );
+        assertThat(
+            error("TS test | STATS count(to_string(host)) BY bucket(@timestamp, 1 minute)", tsdb),
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: I think this doesn't work - can you test with `STATS count(last_over_time(host))`?

**Review by dnhatn — APPROVED** [review]
LGTM, thanks Pablo!

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries-absent-over-time.csv-spec [hunk 4]
```diff
@@ -149,7 +149,7 @@ absent_over_time_of_keyword
 required_capability: ts_command_v0
 required_capability: absent_over_time
 required_capability: k8s_dataset_additional_fields
-TS k8s | STATS is_present = max(absent_over_time(pod)) BY cluster, time_bucket = tbucket(10minute) | SORT time_bucket, cluster | LIMIT 10;
+TS k8s | STATS is_present = max(absent_over_time(network.eth0.tx)) BY cluster, time_bucket = tbucket(10minute) | SORT time_bucket, cluster | LIMIT 10;
```
Comment (limotova) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries-absent-over-time.csv-spec:152]: In the interest of type-coverage can we maybe add a keyword field to the dataset for these functions? From the mappings `event` should be a keyword, but I guess it was never actually generated...

Comment (pabloem) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries-absent-over-time.csv-spec:152]: oops sorry! I will add this - I had not noticed your comment
