### PR TITLE
ESQL: Fix nullify under join and enrich

### LINKED ISSUE #141827: ESQL: SET unmapped_fields="nullify" not working with LOOKUP JOIN if a match field is nullified.
Relates #138888 

```
SET unmapped_fields="nullify";
FROM employees
            | EVAL language_code = does_not_exist
            | LOOKUP JOIN languages_lookup ON language_code


{"error":{"root_cause":[{"type":"verification_exception","reason":"Found 1 problem\nline 1:140: JOIN left field [language_code] of type [NULL] is incompatible with right field [language_code] of type [INTEGER]"}],"type":"verification_exception","reason":"Found 1 problem\nline 1:140: JOIN left field [language_code] of type [NULL] is incompatible with right field [language_code] of type [INTEGER]"},"status":400}
```

### PR DESCRIPTION
**Pull request by GalLalouche**
## Summary
When `SET unmapped_fields="nullify"` is used, referencing a non-existent field as a match field in `LOOKUP JOIN` or `ENRICH` fails with a verification error because the field has `NULL` type, which wasn't considered compatible with the right-side field type.

## Fix
Two separate code paths needed fixing:
• `LOOKUP JOIN`: `Join.comparableTypes()` didn't handle `NULL` types, so `NULL` vs `INTEGER` was rejected as incompatible.
• `ENRICH`: `Analyzer.resolveEnrich()` checks the match field type against an allow-list that didn't include `NULL`, producing an `"Unsupported type [null]"` error.

The fix allows `NULL`-typed fields to pass both type compatibility checks, since a null-valued join/enrich key simply won't match any rows.

Resolves #141827.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -2438,6 +2438,12 @@ public enum Cap {
          */
         PARQUET_ORC_STARTS_WITH_PUSHDOWN,
 
+        /**
+         * Fix for LOOKUP JOIN and ENRICH failing when the match field has NULL type from unmapped field nullification.
+         * See https://github.com/elastic/elasticsearch/issues/141827
+         */
+        FIX_NULL_MATCH_FIELD_IN_JOIN_AND_ENRICH,
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: nit: let's use a name that starts with `OPTIONAL_FIELDS` and let's group this with the other `load`/`nullify` caps?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 2]
```diff
@@ -1683,7 +1683,7 @@ private LogicalPlan resolveEnrich(Enrich enrich, List<Attribute> childrenOutput)
                     final DataType dataType = resolved.dataType();
                     String matchType = enrich.policy().getType();
                     DataType[] allowed = allowedEnrichTypes(matchType);
-                    if (Arrays.asList(allowed).contains(dataType) == false) {
+                    if (dataType != DataType.NULL && Arrays.asList(allowed).contains(dataType) == false) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: nit: why not enhance `allowedEnrichTypes`?

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 3]
```diff
@@ -629,6 +629,27 @@ x:integer      | does_not_exist:null | language_code:integer | language_name:key
 1              | null                | null                  | null
 ;
 
+// Reproducer for https://github.com/elastic/elasticsearch/issues/141827
+lookupJoinNullifiedMatchField
+required_capability: optional_fields_nullify_tech_preview
+required_capability: join_lookup_v12
+required_capability: fix_null_match_field_in_join_and_enrich
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec]: Are all of these caps required these days? Since https://github.com/elastic/elasticsearch/pull/145529, we don't have to worry about skipping stuff that CsvTests can't handle, so just the cap added in this PR should suffice?

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 4]
```diff
@@ -659,6 +680,23 @@ x:integer      | does_not_exist:null | y:keyword | language_name:keyword
...
+enrichNullifiedMatchField
+required_capability: optional_fields_nullify_tech_preview
+required_capability: enrich_load
+required_capability: fix_null_match_field_in_join_and_enrich
+required_capability: fix_null_match_field_in_join_and_enrich
+
+SET unmapped_fields="nullify"\;
+ROW x = 1
+| EVAL y = does_not_exist
+| ENRICH languages_policy ON y
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:704]: Test suggestion: `ENRICH languages_policy ON does_not_exist` (without the `EVAL`)

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 5]
```diff
@@ -629,6 +629,27 @@ x:integer      | does_not_exist:null | language_code:integer | language_name:key
...
+// Reproducer for https://github.com/elastic/elasticsearch/issues/141827
+lookupJoinNullifiedMatchField
+required_capability: optional_fields_nullify_tech_preview
+required_capability: join_lookup_v12
+required_capability: fix_null_match_field_in_join_and_enrich
+
+SET unmapped_fields="nullify"\;
+FROM employees
+| EVAL language_code = does_not_exist
+| LOOKUP JOIN languages_lookup ON language_code
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:639]: I have some test suggestions; I think `LOOKUP JOIN` could use more `nullify` tests overall:
- without the `EVAL` (language_code doesn't exist in `employees`)
- expression join: `LOOKUP JOIN languages_lookup` with expressions using 2+ attributes where the attributes are present only in the main index, lookup index, or neither, e.g.:
  - `ON language_code == does_not_exist`
  - `ON does_not_exist == does_not_exist2`
  - `ON emp_no == does_not_exist`
  - conjunctions and disjunctions of such expressions + valid expressions

Some of the latter should actually be negative tests and may require to be stuffed into the yaml or verifier tests.

Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:639]: Can we also add some optimizer tests for this? We're joining on an always wrong predicate, so `PruneLeftJoinOnNullMatchingField` should kick in.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java [hunk 6]
```diff
@@ -350,6 +350,10 @@ public void postAnalysisVerification(Failures failures) {
     private static boolean comparableTypes(Attribute left, Attribute right) {
         DataType leftType = left.dataType();
         DataType rightType = right.dataType();
+        if (leftType == NULL || rightType == NULL) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java]: Why exactly do we also have `rightType == NULL`. Do the added tests cover this? Altering this to just `leftType == NULL` I couldn't get CsvIT to fail.

The right hand side is generally "special". It's either the `STATS` output of an `INLINE STATS`, or it's the lookup index for `LOOKUP JOIN`. We shouldn't nullify fields in lookup indices, that's quite explicitly disabled in `ResolveUnmapped#nullify` and would also defy the logic of "with `nullify`, any missing fields are assumed to be in the main indices."

I suspect that this is required for `INLINE STATS`, though, because we might be doing something like `INLINE STATS max(foo) BY does_not_exist`. Let's add tests that cover this, as well as at least some optimizer unit/golden tests?

**Review by alex-spies — COMMENTED** [review]
Thanks @GalLalouche , I agree with the fix! I'd love to see more tests, though, as the different things that we can do with joins are expanding in complexity.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java (hunk 1 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: ~~Just moved this to `OPTIONAL_FIELDS` instead.~~
Done.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 2 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Done.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec (hunk 3 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec]: Done.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec (hunk 5 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:639]: Added a golden test.

Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:639]: Done.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec (hunk 4 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:704]: Done, + golden test.

Interetingly, the `Enrich` node is still present in the optimized plan (unlike the `LookupJoin` case where `PruneLeftJoinOnNullMatchingField` replaced it). This is because `PruneLeftJoinOnNullMatchingField` specifically targets Join instances and `Enrich` is not a `Join`. The golden file still captures the optimizer's treatment of the enrich with a null match field, which is useful for regression tracking.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java (hunk 6 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java]: Removed.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/GenerativeRestTest.java [hunk 7]
```diff
@@ -119,9 +119,6 @@ public abstract class GenerativeRestTest extends ESRestTestCase implements Query
         // https://github.com/elastic/elasticsearch/issues/145570
         "function cannot operate on \\[.*\\], which is not a field from an index mapping",
         "\\[:\\] operator cannot operate on \\[.*\\], which is not a field from an index mapping",
-        "JOIN left field \\[.*\\] of type \\[NULL\\] is incompatible with right", // https://github.com/elastic/elasticsearch/issues/141827
```
Comment (astefan) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/GenerativeRestTest.java:118]: 🚀

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 8]
```diff
@@ -1732,8 +1732,8 @@ private LogicalPlan resolveMMR(MMR mmr, List<Attribute> childrenOutput) {
             return resolved;
         }
 
-        private static final DataType[] GEO_TYPES = new DataType[] { GEO_POINT, GEO_SHAPE };
-        private static final DataType[] NON_GEO_TYPES = new DataType[] { KEYWORD, TEXT, IP, LONG, INTEGER, FLOAT, DOUBLE, DATETIME };
+        private static final DataType[] GEO_TYPES = new DataType[] { GEO_POINT, GEO_SHAPE, NULL };
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: This is technically inaccurate. `NULL` is a data type, but not a GEO data type. I would approach dealing with it differently.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 9]
```diff
@@ -629,6 +629,42 @@ x:integer      | does_not_exist:null | language_code:integer | language_name:key
...
 ;
 
+// Reproducer for https://github.com/elastic/elasticsearch/issues/141827
+lookupJoinNullifiedMatchField
+required_capability: optional_fields_fix_null_match_field_in_join_and_enrich
+
+SET unmapped_fields="nullify"\;
+FROM employees
+| EVAL language_code = does_not_exist
+| LOOKUP JOIN languages_lookup ON language_code
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:639]: And one test for `LOOKUP JOIN languages_lookup ON does_not_exist`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: This has a side effect that I am not sure is entirely correct. If it is correct, then we might need to check for consistency everywhere in ESQL.

Analyzer:1685
```
DataType[] allowed = allowedEnrichTypes(matchType);
                    if (Arrays.asList(allowed).contains(dataType) == false) {
                        String suffix = "only ["
                            + Arrays.stream(allowed).map(DataType::typeName).collect(Collectors.joining(", "))
                            + "] allowed for type ["
                            + matchType
                            + "]";
                        resolved = ua.withUnresolvedMessage(
                            "Unsupported type ["
                                + resolved.dataType().typeName()
                                + "] for enrich matching field ["
                                + ua.name()
                                + "]; "
                                + suffix
                        );
                    }
```

makes the error exposed to user to look like

```
  "Unsupported type [unsupported] for enrich matching field [multi_typed]; only [keyword, text, ip, long, integer, float, double, datetime, null] allowed for type [range]"
```

I am not sure if we expose `null` as a valid data type in our error message. I've tried to search for this, but didn't find any other error message like that one.
I looked at TypeResolutions.isType (line 237) and `null` is a somewhat implicit data type. Us exposing it like that with this PR I think is **wrong**.

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: I believe the initial solution was better imho. Sorry @alex-spies.

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: And one more question, sorry guys: this error message `"Unsupported type [unsupported] for enrich matching field ......"` I think is wrong by leaking the type "unsupported" in there. This feels like it should have been caught earlier by the Verifier and not "leaked" like that as `unsupported` data type exposure. I didn't dig into this one, but is this looking fishy only to me?

**Review by astefan — COMMENTED** [review]
Left some comments.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec (hunk 9 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:639]: Added.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 2 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: FYI: the `unsupported` type is already "leaked", e.g., it's part of the output type for unsupported types. Same thing for `null` if you use something like `EVAL x = null`.

Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Nevertheless, this error message style is inconsistent with other cases of union types, where we get a nice "cannot use field due to ambiguities". So let me fix the error message.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 10]
```diff
@@ -1660,23 +1661,26 @@ private LogicalPlan resolveEnrich(Enrich enrich, List<Attribute> childrenOutput)
...
-                        resolved = ua.withUnresolvedMessage(
-                            "Unsupported type ["
-                                + resolved.dataType().typeName()
-                                + "] for enrich matching field ["
-                                + ua.name()
-                                + "]; "
-                                + suffix
-                        );
+                    if (resolved instanceof FieldAttribute fa) {
+                        resolved = fa.checkUnresolved();
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Ok, here's my updated comment on the current code.

1. ++ to not adding `NULL` to the `allowedEnrichTypes`. I missed that we also use this to construct error messages, and I agree with @astefan that `NULL` doesn't need explicit mentioning in error messages (at least for now).

2. -- to replacing `fa` by `fa.checkUnresolved()` _here_. Flagging a type-conflicted field is the job of `UnionTypesCleanup`, and I'd prefer if this logic remains there; the whole type-conflict verifier flow is complicated as-is, so I'd like to keep it contained to few places.

All we want to do here is emit the most useful error message OR let `UnionTypesCleanup` pick up on the type conflict. I'd rather we add a method `FieldAttribute#hasTypeConflicts` which checks for `field instanceOf InvalidMappedField` and _do nothing_ (don't further try to resolve the `ENRICH`), so that `UnionTypesCleanup` can do its job.

That will make it simpler to retrofit implicit casting, both in general and for `load` specifically. In fact, I think the current change **probably breaks** some `ENRICH` queries (and let's test that!): for date/date_nanos type conflicts, the analyzer will automagically replace the field attribute by one that has a MultiTypeEsField in it, i.e. with implicitly resolved type conflict (by implicitly casting to nanos). I imagine this will break if we eagerly replace the match attribute by the result of `checkUnresolved`, which is an unresolveable `UnsupportedAttribute`.

3. ++ to aborting resolution when `FieldAttribute#checkUnresolved` flags this as type-conflicted. That's fixing the pre-existing problem that `ENRICH` gives you a garbage error message in case of type conflicts.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: ++ to fixing the error message, @GalLalouche .

I disagree on `NULL` being an implicit/hidden data type. It's getting exposed necessarily when using `EVAL literal = null` or when using `SET unmapped_fields="nullify"`. This type makes it into the output, it's not hidden from the user. (I agree that `UNSUPPORTED` is and should be hidden from the user, though.) In fact, I think we need to put in work to ensure users can understand the `NULL` type, so I opened https://github.com/elastic/elasticsearch/issues/140575.

However, I don't think that we need to mention `NULL` as one of the specifically supported types in the error message. That should be implicit, and we should have docs that say "you can generally use a NULL-typed expression in stead of any other expression and your query should keep working".

Now, this thread is attached to an out-of date version of the PR. Let me add a comment of what I _think_ it should look like on the current PR's code. @astefan , I'd be happy if you could comment there, too. (Update: this comment ended up below the new comment, oh well :) I meant this one, above: https://github.com/elastic/elasticsearch/pull/145743#discussion_r3147859241)

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:1]: Suggestion: can we add a couple tests to `enrich.csv-spec` that don't use `nullify`, but instead use `EVAL match_field = null` and `ROW match_field = null`?

**Review by alex-spies — CHANGES_REQUESTED** [review]
Thanks for the iterations @GalLalouche and thanks for the inputs @astefan , I think it's very valid!

I added some comments on Analyzer.java. This is on "Request changes" only because I think the eager transformation of field attribute with an IMF inside into an UnsupportedAttribute messes up with implicit date/nanos casting, so we should confirm/refute that with tests (and I left an alternative suggestion, too).

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:1]: Done.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 10 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: 2. Done (though I couldn't show breakage with the pre-fixed code).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 11]
```diff
@@ -1660,27 +1660,23 @@ private LogicalPlan resolveEnrich(Enrich enrich, List<Attribute> childrenOutput)
...
-                                        "Unsupported type [%s] for enrich matching field [%s]; only [%s] allowed for type [%s]",
-                                        dataType.typeName(),
-                                        ua.name(),
-                                        Arrays.stream(allowed).map(DataType::typeName).collect(Collectors.joining(", ")),
-                                        matchType
-                                    )
-                                );
-                            }
-                        }
+                // For type-conflicted fields, defer to ResolveUnionTypes (which may implicitly cast compatible conflicts) and ultimately
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: `ResolveUnionTypes` does no implicit casting. But `DateMillisToNanosInEsRelation` will.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 12]
```diff
@@ -97,6 +97,41 @@ public void testIncompatibleTypesInMathOperation() {
...
+        TestAnalyzer analyzer = analyzer().addIndex("test*", IndexResolution.valid(EsIndexGenerator.esIndex("test*", mapping)))
+            .addEnrichPolicy(EnrichPolicy.RANGE_TYPE, "decades_policy", "date_range", "decades", "mapping-decades.json")
+            .stripErrorPrefix(true);
+
+        analyzer.error(
+            "from test* | enrich decades_policy on multi_typed_date",
+            equalTo(
+                "1:39: Unsupported type [date_nanos] for enrich matching field [multi_typed_date];"
+                    + " only [keyword, text, ip, long, integer, float, double, datetime] allowed for type [range]"
+            )
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:131]: Aha, so we do auto-cast to date nanos before the enrich validation triggers. Good to know.

Thanks for adding the test! :)

**Review by alex-spies — APPROVED** [review]
Thanks @GalLalouche ! I think the current state is nice; we preserve the reasonable list of allowed match field types in the error message, remove the weird mention of `unsupported` in the error message, and permit nulls now. Great!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 11 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: Fixed.

**Comment by GalLalouche** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/147817)|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/147818)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
