### PR TITLE
ALLOC: Fail Stale Primary Alloc. Req. without Data

### LINKED ISSUE #37098: Allocate_stale_primary appears to succeed on wrong node
Today if one issues an `allocate_stale_primary` [reroute command](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html) requesting the primary to be allocated on a node which does not hold a stale copy of the shard in question then the reroute command still returns `200 OK`. The recovery subsequently fails, of course, because there is no copy of the shard from which to recover:

```
[2019-01-03T08:48:16,731][WARN ][o.e.c.r.a.AllocationService] [node-0] failing shard [failed shard, shard [i][1], node[0ZoVYAp6TzC6VjGW7qo2-w], [P], recovery_source[existing store recovery; bootstrap_history_uuid=true], s[INITIALIZING], a[id=H9r7KK24TkuzUz6OdNzwlg], unassigned_info[[reason=ALLOCATION_FAILED], at[2019-01-03T08:47:40.487Z], failed_attempts[1], delayed=false, details[failed shard on node [0ZoVYAp6TzC6VjGW7qo2-w]: failed recovery, failure RecoveryFailedException[[i][1]: Recovery failed on {node-1}{0ZoVYAp6TzC6VjGW7qo2-w}{psSlOmPKQZeVqw63jcncyA}{127.0.0.1}{127.0.0.1:9301}{ml.machine_memory=17179869184, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}]; nested: IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: IndexShardRecoveryException[shard allocated for local recovery (post api), should exist, but doesn't, current files: []]; nested: FileNotFoundException[no segments* file found in store(ByteSizeCachingDirectory(MMapDirectory@/Users/davidturner/discuss/162719/elasticsearch-6.5.1/data-1/nodes/0/indices/YPnPuK8hRnyDHjzM2EhLtQ/1/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@46a205e7)): files: []]; ], allocation_status[no_valid_shard_copy]], message [failed recovery], failure [RecoveryFailedException[[i][1]: Recovery failed on {node-1}{0ZoVYAp6TzC6VjGW7qo2-w}{psSlOmPKQZeVqw63jcncyA}{127.0.0.1}{127.0.0.1:9301}{ml.machine_memory=17179869184, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}]; nested: IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: IndexShardRecoveryException[shard allocated for local recovery (post api), should exist, but doesn't, current files: []]; nested: FileNotFoundException[no segments* file found in store(ByteSizeCachingDirectory(MMapDirectory@/Users/davidturner/discuss/162719/elasticsearch-6.5.1/data-1/nodes/0/indices/YPnPuK8hRnyDHjzM2EhLtQ/1/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@46a205e7)): files: []]; ], markAsStale [true]]
org.elasticsearch.indices.recovery.RecoveryFailedException: [i][1]: Recovery failed on {node-1}{0ZoVYAp6TzC6VjGW7qo2-w}{psSlOmPKQZeVqw63jcncyA}{127.0.0.1}{127.0.0.1:9301}{ml.machine_memory=17179869184, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}
	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2139) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.5.1.jar:6.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: failed to fetch index version after copying it over
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:389) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1645) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2135) ~[elasticsearch-6.5.1.jar:6.5.1]
	... 4 more
Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: shard allocated for local recovery (post api), should exist, but doesn't, current files: []
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:374) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1645) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2135) ~[elasticsearch-6.5.1.jar:6.5.1]
	... 4 more
Caused by: java.io.FileNotFoundException: no segments* file found in store(ByteSizeCachingDirectory(MMapDirectory@/Users/davidturner/discuss/162719/elasticsearch-6.5.1/data-1/nodes/0/indices/YPnPuK8hRnyDHjzM2EhLtQ/1/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@46a205e7)): files: []
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:640) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:442) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:131) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:201) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:186) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:364) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1645) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2135) ~[elasticsearch-6.5.1.jar:6.5.1]
	... 4 more
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* Get indices shard store status before enqueuing the reallocation state update task to prevent
tasks that would fail because a node does not hold a stale copy of the shard on a best effort basis
* Closes #37098

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/routing/AllocationIdIT.java [hunk 1]
```diff
@@ -135,7 +134,7 @@ public void testFailedRecoveryOnAllocateStalePrimaryRequiresAnotherAllocateStale
             assertThat(shardRouting.unassignedInfo().getReason(), equalTo(UnassignedInfo.Reason.ALLOCATION_FAILED));
         });
 
-        try(Store store = new Store(shardId, indexSettings, new SimpleFSDirectory(indexPath), new DummyShardLock(shardId))) {
+        try (Store store = new Store(shardId, indexSettings, new SimpleFSDirectory(indexPath), new DummyShardLock(shardId))) {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/cluster/routing/AllocationIdIT.java]: Sorry for these two noisy cleanups that snuck into this file

File: server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java [hunk 2]
```diff
@@ -69,18 +87,82 @@ protected ClusterRerouteResponse newResponse() {
...
-            response -> {
-                if (request.dryRun() == false) {
-                    response.getExplanations().getYesDecisionMessages().forEach(logger::info);
+        // Gather all stale primary allocation commands into a map indexed by the index name they correspond to
+        // so we can check if the nodes they correspond to actually have any data for the shard
+        Map<String, List<AbstractAllocateAllocationCommand>> stalePrimaryAllocations = null;
+        for (AllocationCommand command : request.getCommands().commands()) {
+            if (command instanceof AllocateStalePrimaryAllocationCommand) {
+                if (stalePrimaryAllocations == null) {
+                    stalePrimaryAllocations = new HashMap<>();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java]: I think we can afford to make this `HashMap` eagerly and avoid the noise in the loop.

File: server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java [hunk 3]
```diff
@@ -175,15 +175,18 @@ public void testFailedAllocationOfStalePrimaryToDataNodeWithNoData() throws Exce
...
-        client().admin().cluster().prepareReroute().add(new AllocateStalePrimaryAllocationCommand("test", 0,
-            dataNodeWithNoShardCopy, true)).get();
+        Throwable iae = expectThrows(
+            IllegalArgumentException.class,
+            () -> client().admin().cluster().prepareReroute().add(new AllocateStalePrimaryAllocationCommand("test", 0,
+            dataNodeWithNoShardCopy, true)).get());
+        assertThat(iae.getMessage(), equalTo("No data for shard [0] of index [test] found on node [" + dataNodeWithNoShardCopy + ']'));
 
         logger.info("--> wait until shard is failed and becomes unassigned again");
         assertBusy(() ->
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java]: I think we no longer want this to be an `assertBusy()` - we expect that the previous reroute didn't do anything, so it should still be in this state from beforehand.

File: server/src/test/java/org/elasticsearch/cluster/routing/AllocationIdIT.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/routing/AllocationIdIT.java]: I think we should back them out for the sake of future `git annotate` users :)

**Review by DaveCTurner — COMMENTED** [review]
Looks good. I left a small number of small comments.

I would rather avoid the `// code comments` that you added - they don't really say anything that isn't already clear to me from the code, and I always worry about comments like this that fall out of sync later.

**Comment by original-brownbear** [comment]
@DaveCTurner all points addressed, thanks for taking a look!

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1

**Comment by original-brownbear** [comment]
Jenkins run Gradle build tests 2

File: server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java [hunk 4]
```diff
@@ -69,18 +87,74 @@ protected ClusterRerouteResponse newResponse() {
...
+                ActionListener.wrap(
+                    response -> {
+                        ImmutableOpenMap<String, ImmutableOpenIntMap<List<IndicesShardStoresResponse.StoreStatus>>> status =
+                            response.getStoreStatuses();
+                        Exception e = null;
+                        for (Map.Entry<String, List<AbstractAllocateAllocationCommand>> entry : stalePrimaryAllocations.entrySet()) {
+                            final String index = entry.getKey();
+                            final ImmutableOpenIntMap<List<IndicesShardStoresResponse.StoreStatus>> indexStatus = status.get(index);
+                            if (indexStatus == null) {
+                                e = ExceptionsHelper.useOrSuppress(e, new IndexNotFoundException(index));
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java]: Could we have a test that hits this branch?

File: server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java [hunk 5]
```diff
@@ -69,18 +87,74 @@ protected ClusterRerouteResponse newResponse() {
...
+                            } else {
+                                for (AbstractAllocateAllocationCommand command : entry.getValue()) {
+                                    final List<IndicesShardStoresResponse.StoreStatus> shardStatus =
+                                        indexStatus.get(command.shardId());
+                                    if (shardStatus == null) {
+                                        e = ExceptionsHelper.useOrSuppress(e, new IllegalArgumentException(
+                                            "No data for shard [" + command.shardId() + "] of index [" + index + "] found on any node")
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java]: Could we have a test that hits this branch?

**Review by DaveCTurner — COMMENTED** [review]
Implementation looks good, I asked for a couple more tests.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java]: Done in ea98277 :)

File: server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java]: Actually no ... my bad this one is dead code. The logic in the index shard store status request already checks the index exists.
I added an assertion for this now and a test that makes sure it's not tripped when the index doesn't exist :)

**Comment by original-brownbear** [comment]
@DaveCTurner thanks for taking a look => tests added and implementation simplified a little as well in ea98277 :)

**Comment by original-brownbear** [comment]
@DaveCTurner ping :)

**Review by DaveCTurner — APPROVED** [review]
LGTM
