### PR TITLE
[ML] only retry persistence failures when the failure is intermittent and stop retrying when analytics job is stopping

### LINKED ISSUE #53687: [ML] Writing Results Retries Continue After Analytics Job Stopped
This was found on a recent 7.7 build. I created a classification analysis that became stuck in the `writing_results` phase. 

```
[2020-03-17T12:58:57,528][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [reba.lan] [openml-kr-vs-kp-classifier-0] [data_frame_analyzer/8755] [CBoostedTreeImpl.cc@241] Training finished after 18 iterations. Time per iteration in ms mean: 1287.84 std. dev:  2697.19
[2020-03-17T12:58:57,626][INFO ][o.e.x.m.d.p.AnalyticsResultProcessor] [reba.lan] [openml-kr-vs-kp-classifier-0] Started writing results
[2020-03-17T12:58:57,882][INFO ][o.e.c.m.MetaDataMappingService] [reba.lan] [openml-kr-vs-kp-classified-0/h_cT5mm3QSWfTv6b3ZBlTQ] update_mapping [_doc]
[2020-03-17T12:58:58,149][WARN ][o.e.x.m.u.p.ResultsPersisterService] [reba.lan] [openml-kr-vs-kp-classifier-0] failed to index after [1] attempts. Will attempt again in [50ms].
[2020-03-17T12:58:58,361][WARN ][o.e.x.m.u.p.ResultsPersisterService] [reba.lan] [openml-kr-vs-kp-classifier-0] failed to index after [2] attempts. Will attempt again in [75ms].
[2020-03-17T12:58:58,570][WARN ][o.e.x.m.u.p.ResultsPersisterService] [reba.lan] [openml-kr-vs-kp-classifier-0] failed to index after [3] attempts. Will attempt again in [276ms].
...lots more retires here...
[2020-03-17T13:16:19,080][WARN ][o.e.x.m.u.p.ResultsPersisterService] [reba.lan] [openml-kr-vs-kp-classifier-0] failed to index after [15] attempts. Will attempt again in [846433ms]
```

Stopping the job via the UI removed the job from the jobs list, but the job remains in a `stopping` state. The retires continue even after stopping the job:

```
[2020-03-17T13:44:24,643][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [reba.lan] [openml-kr-vs-kp-classifier-0] Stopping task with force [true]
[2020-03-17T13:44:24,668][INFO ][o.e.x.m.a.TransportStopDataFrameAnalyticsAction] [reba.lan] [openml-kr-vs-kp-classifier-0] Stopping task with force [true]
[2020-03-17T13:44:24,669][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [reba.lan] [controller/6507] [CDetachedProcessSpawner.cc@177] Child process with PID 8755 was terminated by signal 15
[2020-03-17T13:44:24,670][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [reba.lan] [controller/6507] [CDetachedProcessSpawner.cc@99] Will not attempt to kill process 8755: not a child process
[2020-03-17T13:44:24,670][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [reba.lan] [controller/6507] [CCommandProcessor.cc@96] Failed to kill process with PID 8755
[2020-03-17T13:45:13,300][WARN ][o.e.x.m.u.p.ResultsPersisterService] [reba.lan] [openml-kr-vs-kp-classifier-0] failed to index after [17] attempts. Will attempt again in [884782ms]
.
.
.
[2020-03-17T14:14:48,971][WARN ][o.e.x.m.u.p.ResultsPersisterService] [reba.lan] [openml-kr-vs-kp-classifier-0] failed to index after [19] attempts. Will attempt again in [850734ms]
```

job config:

```
{
      "id" : "openml-kr-vs-kp-classifier-0",
      "source" : {
        "index" : [
          "openml-kr-vs-kp"
        ],
        "query" : {
          "match_all" : { }
        }
      },
      "dest" : {
        "index" : "openml-kr-vs-kp-classified-0",
        "results_field" : "ml"
      },
      "analysis" : {
        "classification" : {
          "dependent_variable" : "class",
          "class_assignment_objective" : "maximize_accuracy",
          "num_top_classes" : 2,
          "prediction_field_name" : "class_prediction",
          "training_percent" : 90.0,
          "randomize_seed" : 7077816937788972687
        }
      },
      "model_memory_limit" : "512mb",
      "create_time" : 1584464253331,
      "version" : "7.7.0",
      "allow_lazy_start" : false
    }
```

### PR DESCRIPTION
**Pull request by benwtrent**
This fixes two issues:

- Results persister would retry actions even if they are not intermittent. An example of an persistent failure is a doc mapping problem.
- Data frame analytics would continue to retry to persist results even after the job is stopped.

closes https://github.com/elastic/elasticsearch/issues/53687

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/DataFrameRowsJoiner.java [hunk 1]
```diff
@@ -37,12 +38,12 @@
     private final String analyticsId;
     private final DataFrameDataExtractor dataExtractor;
     private final ResultsPersisterService resultsPersisterService;
+    private Supplier<Boolean> shouldRetryPersistence = () -> true;
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/DataFrameRowsJoiner.java]: Could this be final and passed in the constructor?

**Comment by benwtrent** [comment]
@elasticmachine update branch

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java [hunk 2]
```diff
@@ -148,12 +180,28 @@ public SearchResponse searchWithRetry(SearchRequest searchRequest,
             } catch (ElasticsearchException e) {
                 LOGGER.warn("[" + jobId + "] Exception while executing search action", e);
                 failureMessage = e.getDetailedMessage();
+                if (isIrrecoverable(e)) {
+                    LOGGER.warn(new ParameterizedMessage("[{}] experienced irrecoverable failure", jobId), e);
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java]: Could you make this message consistent with others? "...failure that cannot be..."

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java [hunk 3]
```diff
@@ -148,12 +180,28 @@ public SearchResponse searchWithRetry(SearchRequest searchRequest,
...
 
             retryContext.nextIteration("search", failureMessage);
         }
     }
 
+    /**
+     * @param ex The exception to check
+     * @return true when the failure will persist no matter how many times we retry.
+     */
+    static boolean isIrrecoverable(Exception ex) {
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java]: Should this be "private"?

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterServiceTests.java [hunk 4]
```diff
@@ -206,6 +210,21 @@ public void testSearchWithRetries_Failure_ShouldNotRetryAfterRandomNumberOfRetri
...
+        doAnswer(withFailure(new ElasticsearchStatusException("bad search request", RestStatus.BAD_REQUEST)))
+            .when(client).execute(eq(SearchAction.INSTANCE), eq(SEARCH_REQUEST), any());
+
+        ElasticsearchException e =
+            expectThrows(
+                ElasticsearchException.class,
+                () -> resultsPersisterService.searchWithRetry(SEARCH_REQUEST, JOB_ID, () -> true, (s) -> {}));
+        assertThat(e.getMessage(), containsString("experienced failure that cannot be automatically retried"));
+
+        verify(client, times(1)).execute(eq(SearchAction.INSTANCE), eq(SEARCH_REQUEST), any());
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterServiceTests.java]: I think `times(1)` is default and you can drop it.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/DataFrameRowsJoiner.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/DataFrameRowsJoiner.java]: Since the retry persistence logic depends on information stored within `AnalyticsResultProcessor` we would either have to make a Builder or a Factory class that we then pass to `AnalyticsResultProcessor` which constructs a new joiner from that passed factory. 

This option just seemed simpler and less complex.

Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/DataFrameRowsJoiner.java]: Ok, got it. Please also consider the following approach which might be even less complex:

Add `isCancelled` field and `cancel()` method to `DataFrameRowsJoiner` class. In `AnalyticsResultProcessor::cancel()`, you can also cancel the joiner:
```
    public void cancel() {
        isCancelled = true;
        dataFrameRowsJoiner.cancel();
    }
``` 

Then there is no need to pass the `Supplier` as you've already passed the actual `isCancelled` value.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java [hunk 5]
```diff
@@ -42,6 +44,22 @@
 import java.util.stream.Collectors;
 
 public class ResultsPersisterService {
+    /**
+     * List of rest statuses that we consider irrecoverable
+     */
+    public static final Set<RestStatus> IRRECOVERABLE_REST_STATUSES = new HashSet<>(
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java]: nit: since the name is in capitals it should be immutable, i.e. `Set.of()` or `Collections.unmodifiableSet()`.

**Review by przemekwitek — APPROVED** [review]
LGTM
