### PR TITLE
[ML] Clean up inference indices on failed endpoint creation

### LINKED ISSUE #123726: [ML] Inconsistent document count in .inference and .secrets-inference
### Elasticsearch Version

any

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

When creating an inference endpoint the configuration is stored in the `.inference` system index and any secrets such as an API in `.secrets-inference` If writing only one of those writes is successful and the other fails then the endpoint creation is failed but the successfully written document is not clean up. 

### Steps to Reproduce

It is difficult to engineer a reproduction. It's helpful if the `.inference` and `.secrets-inference` indices are located on different nodes and one of the nodes is disconnected as happened in this example:

```
Failed to store inference endpoint [X] index: [.secrets-inference] bulk failure message [org.elasticsearch.transport.RemoteTransportException: [es-es-index-8477bb8765-8zbn2][100.64.103.20:9300][indices:data/write/bulk[s][p]]]
```

### Logs (if relevant)

```
Failed to store inference endpoint [X] index: [.secrets-inference] bulk failure message [org.elasticsearch.transport.RemoteTransportException: [es-es-index-8477bb8765-8zbn2][100.64.103.20:9300][indices:data/write/bulk[s][p]]]
```

### PR DESCRIPTION
**Pull request by DonalEvans**
Prior to this change, if only one of the .inference or .secrets-inference indices was updated when creating an inference endpoint, the endpoint creation would fail, but the successfully written doc was not removed, leading to inconsistent document counts between the two indices.

This commit removes any documents that were written in the case that a partial failure occurred, but does not change the behaviour in the case where no updates to the indices were made.

- Invoke a cleanup listener if a partial failure occurred when storing inference endpoint information in the .inference and .secrets-inference indices
- Refactor ModelRegistry to use BulkRequestBuilder.add(IndexRequestBuilder) instead of the deprecated BulkRequestBuilder.add(IndexRequest)
- Include cause when logging bulk failure during inference endpoint creation
- Add integration tests for the new behaviour

Closes #123726

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/registry/ModelRegistry.java [hunk 1]
```diff
@@ -728,22 +740,33 @@ private ActionListener<BulkResponse> getStoreIndexListener(
                 return;
             }
 
-            logBulkFailures(model.getConfigurations().getInferenceEntityId(), bulkItemResponses);
+            boolean anySuccess = false;
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/registry/ModelRegistry.java]: nit: It might be slightly cleaner to move this boolean above the `cleanupListener`. Then in `cleanupListener` we can have a check for `anySuccess`, if there was a success, then do the delete.

Then we don't need to track `listenerToInvoke`.

**Review by jonathan-buttner — APPROVED** [review]

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/registry/ModelRegistry.java (hunk 1 above)
Comment (DonalEvans) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/registry/ModelRegistry.java]: Good idea, done

**Comment by DonalEvans** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/136724)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/136725)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/136726)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
