### PR TITLE
Reject max_number_of_allocations > 1 for low-priority model deployments

### LINKED ISSUE #111227: [ML] Low Priority models should not be updateable
### Elasticsearch Version

8.14

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

ML trained models can be deployed in a [low priority mode](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-trained-model-deployment.html#start-trained-model-deployment-query-params) which should be limited to **1 allocation and 1 thread per allocation**. When checking there is sufficient CPU resource to deploy a model the assignment planner allows multiple low priority deployments to share a single CPU allowing low priority deployments be over allocated. 

The problem is that the number of allocations can be updated to a much higher number and the because the assignment planner treats low priority deployments differently it will not consider those extra allocations when calculating the available resource. Multiple low priority deployments can be created then updated to use far more CPU than is available in the cluster. In cloud low priority deployments do not trigger a scale event so the cluster will not grow in size and can become extremely over allocated. 

Screenshot 2024-07-24 at 10 11 26

### Steps to Reproduce

1. Start a deployment in low priority mode
2. Update the number of allocations to a high number

Screenshot 2024-07-24 at 10 12 51

3. Optionally start more low priority deployments and increase the number of allocations. In the screen shot below the total required CPU cores for all deployments far exceeds what is available on the system.

Screenshot 2024-07-24 at 10 23 33

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes #111227

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/StartTrainedModelDeploymentAction.java [hunk 1]
```diff
@@ -360,6 +360,13 @@ public ActionRequestValidationException validate() {
                 if (threadsPerAllocation > 1) {
                     validationException.addValidationError("[" + THREADS_PER_ALLOCATION + "] must be 1 when [" + PRIORITY + "] is low");
                 }
+                if (adaptiveAllocationsSettings != null
+                    && adaptiveAllocationsSettings.getMaxNumberOfAllocations() != null
+                    && adaptiveAllocationsSettings.getMaxNumberOfAllocations() > 1) {
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/StartTrainedModelDeploymentAction.java:365]: Note: there's no need to verify `min_number_of_allocations`, because it's already validated to be at most `max_number_of_allocations`.

**Review by prwhelan — APPROVED** [review]
