### PR TITLE
Fix flakiness in SamlServiceProviderMetadataIT

### LINKED ISSUE #139067: [CI] SamlServiceProviderMetadataIT testAuthenticationWhenMetadataIsUnreliable failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11513 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/2c4nh3muc5h2c)
- [elasticsearch-periodic-platform-support #11513 / windows-2025_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/r7dt7lbnxvztq)
- [elasticsearch-periodic-platform-support #11506 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/opgybnsf3mljg)
- [elasticsearch-periodic-platform-support #11506 / windows-2025_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/k7wbbbbgccdkg)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:security:qa:saml-rest-tests:javaRestTest" --tests "org.elasticsearch.xpack.security.authc.saml.SamlServiceProviderMetadataIT.testAuthenticationWhenMetadataIsUnreliable" -Dtests.seed=4ABE243CE4233969 -Dtests.locale=ks-Deva -Dtests.timezone=America/Winnipeg -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.saml.SamlServiceProviderMetadataIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAuthenticationWhenMetadataIsUnreliable'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2022_checkpart4_platform-support-windows
- [main] 2 consecutive failures in step windows-2025_checkpart4_platform-support-windows
- [main] 4 failures in test testAuthenticationWhenMetadataIsUnreliable (2.8% fail rate in 144 executions)
- [main] 2 failures in step windows-2022_checkpart4_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in step windows-2025_checkpart4_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by piotrsulkowski-elastic**
There is a potential thread issue, where the contents of shared metadataAvailable field could be cached by a thread and not read the newest changes, causing the test to fail on rare occasion

Closes #139067

### CODE REVIEW

File: x-pack/plugin/security/qa/saml-rest-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/saml/SamlRestTestCase.java [hunk 1]
```diff
@@ -46,7 +47,7 @@ public class SamlRestTestCase extends ESRestTestCase {
     protected static final String SAML_SIGNING_KEY = "/saml/signing.key";
 
     private static HttpsServer httpsServer;
-    private static final Map<Integer, Boolean> metadataAvailable = new HashMap<>();
+    private static final Map<Integer, Boolean> metadataAvailable = Collections.synchronizedMap(new HashMap<>());
```
Comment (jfreden) [inline x-pack/plugin/security/qa/saml-rest-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/saml/SamlRestTestCase.java]: Nice catch with the visibility of the content of the map, could definitely be the issue. I'd use a `ConcurrentHashMap`, even if it's just a test. I think even the iteration in `makeMetadataAvailable` here could in theory break the test (because iterating the keyset in a `synchronizedMap` requires a lock).

**Review by jfreden — APPROVED** [review]
LGTM!
