### PR TITLE
Avoiding BulkProcessor deadlock in ILMHistoryStore

### LINKED ISSUE #50440: Make BulkProcessor.add asynchronously execute bulk request if needed
Currently when invoking the `.add` method on `BulkProcessor`, there is a chance that the `.add` also executes the request. This execution should be done asynchronously so that the add method can be blocking in terms of adding to the queue, but non-blocking for actual execution.

### LINKED ISSUE #68468: Generic threads deadlock related to ILMHistoryStore indexing
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.1

**Plugins installed**: Cloud

**JVM version** (`java -version`): 15.0.1+9

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

All generic threads are waiting with the following stack trace:

```
at java.util.concurrent.locks.LockSupport.park(Ljava/lang/Object;)V (LockSupport.java:211)                                                                                                             
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(Ljava/util/concurrent/locks/AbstractQueuedSynchronizer$Node;IZZZJ)I (AbstractQueuedSynchronizer.java:714)                             
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(I)V (AbstractQueuedSynchronizer.java:937)                                                                                             
at java.util.concurrent.locks.ReentrantLock$Sync.lock()V (ReentrantLock.java:153)                                                                                                                      
at java.util.concurrent.locks.ReentrantLock.lock()V (ReentrantLock.java:322)                                                                                                                           
at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(Lorg/elasticsearch/action/DocWriteRequest;)V (BulkProcessor.java:379)                                                                       
at org.elasticsearch.action.bulk.BulkProcessor.add(Lorg/elasticsearch/action/DocWriteRequest;)Lorg/elasticsearch/action/bulk/BulkProcessor; (BulkProcessor.java:361)                                   
at org.elasticsearch.action.bulk.BulkProcessor.add(Lorg/elasticsearch/action/index/IndexRequest;)Lorg/elasticsearch/action/bulk/BulkProcessor; (BulkProcessor.java:347)                                
at org.elasticsearch.xpack.ilm.history.ILMHistoryStore.lambda$putAsync$0(Lorg/elasticsearch/action/index/IndexRequest;Lorg/elasticsearch/xpack/ilm/history/ILMHistoryItem;)V (ILMHistoryStore.java:150)
at org.elasticsearch.xpack.ilm.history.ILMHistoryStore$$Lambda$8091+0x0000000801eda370.run()V (Unknown Source)                                                                                         
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run()V (ThreadContext.java:678)                                                                                    
at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1130)                                                                 
at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:630)                                                                                                                 
at java.lang.Thread.run()V (Thread.java:832)                                                                                                                                                           
```

**Steps to reproduce**:

Unknown.

**Provide logs (if relevant)**:

Not available, but I can share a heap dump privately.

### PR DESCRIPTION
**Pull request by masseyke**
We have been seeing deadlocks in ILMHistoryStore in production (#68468). The deadlock appears to be caused by the fact that BulkProcessor uses two locks (`BulkProcessor.lock` and `BulkRequestHandler.semaphore`) and holds onto the latter lock for an indefinite amount of time.

This PR avoids deadlock by using a new BulkProcessor2 that does not require that both locks be held at once, and drastically shortens the amount of time that either lock needs to be held. It does this by adding a new queue (in the Retry2 class).
Note that we have left the original BulkProcessor in place, and have cloned/modified it into BulkProcessor2. BulkProcessor2 for now is only used by ILMHistoryStore but will likely replace BulkProcessor altogether in the near future. 

The flow in the original BulkProcessor is like this:

- ILMHistoryStore adds IndexRequests to BulkProcessor asynchronously.
- BulkProcessor acquires its lock to build up a BulkRequest from these IndexRequests.
- If a call from ILMHistoryStore adds an IndexRequest that pushes the BulkRequest over its configured threshold (size or count) then it calls BulkRequestHandler to load that BulkRequest to the server.
- BulkRequestHandler must acquire a token from its semaphore to do this.
- It calls Client::bulk from the current thread.
- If it fails, it keeps the semaphore lock while it retries (possibly multiple times).

The flow in the new BulkProcessor2:

- ILMHistoryStore adds IndexRequests to BulkProcessor synchronously (since this part is very fast now).
- BulkProcessor acquires its lock to build up a BulkRequest from these IndexRequests.
- If a call from ILMHistoryStore adds an IndexRequest that pushes the BulkRequest over its configured threshold (size or count) then it calls Retry2::withBackoff to attempt to load the bulk a fixed number of times.
- If the number of bytes already in flight to Elasticsearch is higher than a configured number, or if Elasticsearch is too busy, the listener is notified with an EsRejectedExecutionException.
- Either way, control returns immediately and the BulkProcessor lock is released.

We are no longer using a semaphore to throttle how many concurrent requests can be sent to Elasticsearch at once. And there is no longer any blocking. Instead we throttle the total number of bytes in flight to Elasticsearch (approximate), and allow Elasticsearch to throw an EsRejectedExecutionException if it thinks there are too many concurrent requests.

Closes #50440
Closes #68468

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine update branch

**Comment by masseyke** [comment]
@elasticmachine update branch

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStore.java [hunk 1]
```diff
@@ -44,98 +45,119 @@
...
  */
 public class ILMHistoryStore implements Closeable {
     private static final Logger logger = LogManager.getLogger(ILMHistoryStore.class);
 
+    public static final Setting<Integer> MAX_BULK_REQUEST_QUEUE_SIZE_SETTING = Setting.intSetting(
+        "es.indices.lifecycle.history.bulk.request.queue.size",
+        100,
+        1,
+        Setting.Property.NodeScope
+    );
```
Comment (DaveCTurner) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStore.java:59]: I think it would be preferable to bound the total _size_ of all incomplete requests rather than their number. We kind of don't mind if there are 1000+ requests in progress as long as they're all small, and conversely 100 max-sized requests is still 500MiB of heap which is an awful lot of memory to dedicate to this component.

An overall bound on resources used by the whole system would also avoid having to think about bounds at each level as we do today.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java [hunk 2]
```diff
@@ -0,0 +1,419 @@
...
+        while (isClosing == false || System.nanoTime() < closingTime) {
+            boolean allowedToMakeRequest;
+            long timeRemaining = isClosing ? closingTime - System.nanoTime() : 0;
+            if (isClosing && timeRemaining > 0) {
+                try {
+                    logger.trace(
+                        "Waiting up to {} for a semaphore because the server is closing",
+                        new TimeValue(timeRemaining, TimeUnit.NANOSECONDS)
+                    );
+                    allowedToMakeRequest = requestsInFlightSemaphore.tryAcquire(timeRemaining, TimeUnit.NANOSECONDS);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:211]: This seems strange to me. Requests consume resources (i.e. heap) whether they are in flight or just waiting on the queue, so I think it's important to bound this number. Conversely there shouldn't really be a need to limit the number of requests that are actually in flight to Elasticsearch like this. It seems unlikely we'd actually overwhelm Elasticsearch with these requests, and even if we did we should just get back an `EsRejectedExecutionException` or `CircuitBreakingException` to indicate a need to retry.

Also do we really need to block a thread like this? I know it's our own flush thread so it's kind of ok but it still seems strange. This is effectively reimplementing a scheduler and thread pool queue, but I don't see a good reason for having to do this.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 3]
```diff
@@ -0,0 +1,416 @@
...
+    private final BulkRequestHandler2 bulkRequestHandler;
+    private final Runnable onClose;
+
+    private volatile boolean closed = false;
+    /*
+     * This lock is used to protect two things related to the bulkRequest object: (1) it makes sure that two threads do not add requests
+     * to the BulkRequest at the same time since BulkRequest is not threadsafe and (2) it makes sure that no other thread is writing to
+     * the BulkRequest when we swap the bulkRequest variable over to a new BulkRequest object.
+     */
+    private final ReentrantLock lock = new ReentrantLock();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:230]: Do you need a `ReentrantLock` here? I think it could just be a plain `Object` which you use as a mutex in a `synchronized (mutex) {...}` block.

**Review by DaveCTurner — COMMENTED** [review]
Thanks Keith, I left some initial thoughts.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStore.java (hunk 1 above)
Comment (masseyke) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStore.java:59]: Yeah we had talked about this being a problem with BulkProcessor, and settled on the solution being that each user would decide how big its queue would be (so here the ILM history store is defaulting to 100 because its requests will be relatively small and few). Sounds like you're suggesting instead that instead of one BulkProcessor queue per user we have one for the whole system, and bound it by size in bytes rather than count?

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 2 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:211]: ```Conversely there shouldn't really be a need to limit the number of requests that are actually in flight to Elasticsearch like this.```
We had been limiting this previously, so I carried the limit forward here. But I guess it's a good point -- if we're changing to a model where we're throwing `EsRejectedExecutionException` if the queue is full it makes sense to just do that here instead, and not use the semaphore.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java (hunk 3 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:230]: Synchronized would work fine here now that all this is doing is adding to a BulkRequest / adding a BulkRequest to a queue. Is there an advantage to it though? Performance?

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 4]
```diff
@@ -0,0 +1,416 @@
...
+     * @param consumer The consumer that is called to fulfil bulk operations
+     * @param listener The BulkProcessor2 listener that gets called on bulk events
+     * @param name     The name of this processor, e.g. to identify the scheduler threads
+     * @return the builder for BulkProcessor2
+     */
+    public static Builder builder(BiConsumer<BulkRequest, ActionListener<BulkResponse>> consumer, Listener listener, String name) {
+        Objects.requireNonNull(consumer, "consumer");
+        Objects.requireNonNull(listener, "listener");
+        final ScheduledThreadPoolExecutor flushScheduler = Scheduler.initScheduler(Settings.EMPTY, name + FLUSH_SCHEDULER_NAME_SUFFIX);
+        final ScheduledThreadPoolExecutor retryScheduler = Scheduler.initScheduler(Settings.EMPTY, name + RETRY_SCHEDULER_NAME_SUFFIX);
```
[the remark this answers is not in the document]
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:200]: Oops. Good point!

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 2 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:211]: Let me see if I'm following where you're going with this:
We keep track of how many bytes are in flight total for BulkProcessor (globally), and reject any requests that come in if that number is > X. So we don't need a queue or a semaphore or a thread to manage it. When we get a BulkRequest (including a retry), we check `if(inflightBytes + newBytes > X) throw new EsRejectedExecutionException`. Otherwise we add `newBytes` to `inflightBytes` and submit the request. When its listener is notified we subtract its number of bytes.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStore.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStore.java:59]: I'm ok with the limit being per instance, I just think the limit should be expressed in approximate-bytes-of-heap rather than items-in-the-queue.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:211]: Exactly, yes.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:230]: I just find it less noisy, no need for those `finally` blocks (or for reviewers to check that they're all there). I spent at least a little time trying to understand if we were using anything that makes `ReentrantLock` different from a regular mutex. AFAICT we aren't.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:211]: Oh wait, not quite:

> When we get a BulkRequest (including a retry)

I think not for retries, they're kind of an internal thing so we should already be tracking the bytes held by the request we're retrying. We'd only release things once the request is complete (either it's fully successful or we decide to stop retrying for some other reason).

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java (hunk 3 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:230]: Yeah it was a carryover from the old code -- we definitely needed it then (although it was buggy).

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 2 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:211]: Yeah that makes sense.

**Comment by masseyke** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java [hunk 5]
```diff
@@ -0,0 +1,286 @@
...
+                        + " because "
+                        + totalBytesInFlight.get()
+                        + " bytes are already in flight and the max is "
+                        + maxBytesInFlight
+                )
+            );
+        } else {
+            totalBytesInFlight.addAndGet(bulkRequest.estimatedSizeInBytes());
+            phaser.register();
+            consumer.accept(bulkRequest, new RetryHandler(bulkRequest, responsesAccumulator, consumer, listener, maxNumberOfRetries));
```
Comment (masseyke) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:98]: Can we assume that this consumer is async? Or do we need to put this on another thread? All the uses I know of are async.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:108]: Yes, it's reasonable to assume that this is lightweight. It's worth documenting that assumption somewhere, so that the caller can take responsibility for forking to another thread if it needs to do something heavier.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java [hunk 6]
```diff
@@ -0,0 +1,297 @@
...
+                listener.onResponse(getAccumulatedResponse());
+            } else {
+                if (canRetry(bulkItemResponses)) {
+                    logger.trace(
+                        "Got a response in {} with {} items including failures, can retry",
+                        bulkItemResponses.getTook(),
+                        bulkItemResponses.getItems().length
+                    );
+                    addResponses(bulkItemResponses, (r -> r.isFailed() == false));
+                    retry(createBulkRequestForRetry(bulkItemResponses), responsesAccumulator, consumer, listener, retriesRemaining);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:215]: This looks like it leaks the bytes corresponding with the successful items, because `createBulkRequestForRetry(bulkItemResponses)` will be smaller than the original request.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java [hunk 7]
```diff
@@ -0,0 +1,297 @@
...
+        }
+        List<BulkItemResponse> responsesAccumulator = new ArrayList<>();
+        logger.trace("Sending a bulk request with {} bytes in {} items", bulkRequest.estimatedSizeInBytes(), bulkRequest.requests.size());
+        /*
+         * Here we have a risk that multiple threads will do this check at once, and each will think it has room to run. So we could end
+         * up with slightly more bytes in flight than totalBytesInFlight. But this is acceptable risk, and preferable to using a lock or
+         * a while loop with compareAndSet.
+         */
+        long bytesInFlight = totalBytesInFlight.get();
+        if (bytesInFlight + bulkRequest.estimatedSizeInBytes() > maxBytesInFlight) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:94]: Could we do this check in `BulkProcessor2#add` rather than waiting until flush-time to reject things? Relatedly, could we count the size of the pending `BulkRequest` in `BulkProcessor2` towards the bytes-in-flight limit?

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 8]
```diff
@@ -0,0 +1,371 @@
...
+                    return false;
+                }
+
+                @Override
+                public boolean isCancelled() {
+                    return true;
+                }
+            };
+        }
+        return threadPool.scheduleWithFixedDelay(() -> {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:305]: Rather than polling for work to do every N seconds could we just schedule a flush each time we start adding items to a new bulk request? I reckon almost every time this executes will be a no-op.

**Review by DaveCTurner — COMMENTED** [review]
Thanks Keith, definitely looks simpler now. I left a few more comments.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 6 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:215]: I don't think I'm following -- leaking in what way? We're intentionally putting them in the responsesAccumulator so that we can notify the listener once for the whole bulk once we know the final result. Only the failed ones are getting added to the request to retry right?

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java (hunk 8 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:305]: If we actually were using this to load a lot of data (not the ILMHistoryStore case), that could wind up scheduling a _lot_ of flushes. I guess we could keep track of whether one is scheduled, and only schedule something if one is not already scheduled.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:305]: Yes something like that I think.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:215]: AFAICT on each retry we replace the bulk request with a _possibly-smaller_ bulk request, namely `createBulkRequestForRetry(bulkItemResponses)`. If such an attempt finally completes, we only release the `estimatedSizeInBytes()` for the very last bulk request. But we originally acquired the `estimatedSizeInBytes()` for the first attempt, which is in general going to be larger.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java (hunk 7 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:94]: Let me see what I can do. That means moving the tracking of bytes in flight to BulkProcessor2, which means a more complicated interaction between Retry2 and BulkProcessor2 (since we're subtracting bytes for the successful part of a request only when we have failures and then retry).

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:94]: I think it would be acceptable not to have such fine-grained tracking. We could just track all the bytes for the initial `BulkRequest` and hold on to them until it finally completes at which point they're all released.

Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:94]: OK I've done this. Seems like a positive change, but it does make things a little more complicated.

**Comment by masseyke** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 9]
```diff
@@ -0,0 +1,419 @@
...
+
+    /**
+     * This method sends the bulkRequest to the consumer up to maxNumberOfRetries times. The executionId is used to notify the listener
+     * both before and after the request.
+     * @param bulkRequest
+     * @param executionId
+     */
+    private void execute(BulkRequest bulkRequest, long executionId) {
+        // We're taking it off the books as far as BulkProcessor2 is concerned, and letting Retry2 account for it from here on out:
+        totalBytesInFlight.addAndGet(-1 * bulkRequest.estimatedSizeInBytes());
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:383]: Ah I intended to suggest tracking the bytes here _and only here_, releasing them alongside the calls to `listener.afterBulk` below. No need for any accounting in `Retry2` if we do that I think.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry2.java [hunk 10]
```diff
@@ -0,0 +1,303 @@
...
+            } else {
+                if (canRetry(bulkItemResponses)) {
+                    logger.trace(
+                        "Got a response in {} with {} items including failures, can retry",
+                        bulkItemResponses.getTook(),
+                        bulkItemResponses.getItems().length
+                    );
+                    addResponses(bulkItemResponses, (r -> r.isFailed() == false));
+                    BulkRequest retryRequest = createBulkRequestForRetry(bulkItemResponses);
+                    totalBytesInFlight.addAndGet(-1 * (bulkRequest.estimatedSizeInBytes() - retryRequest.estimatedSizeInBytes()));
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry2.java:220]: I don't think we need to be so fine-grained here. We can just track the whole (original) request until it's done.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 11]
```diff
@@ -0,0 +1,419 @@
...
+        }
+    }
+
+    private void internalAdd(DocWriteRequest<?> request) throws EsRejectedExecutionException {
+        // bulkRequest and instance swapping is not threadsafe, so execute the mutations under a mutex.
+        // once the bulk request is ready to be shipped swap the instance reference unlock and send the local reference to the handler.
+        Tuple<BulkRequest, Long> bulkRequestToExecute = null;
+        synchronized (mutex) {
+            ensureOpen();
+            if (totalBytesInFlight.get() + BulkRequest.getEstimatedSizeInBytes(request) > maxBytesInFlight.getBytes()) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:315]: Couple more thoughts:

1. Should we flush if this limit trips? It _could_ be that `request` was just unreasonably large, but if we assume the client is fairly well-behaved then we would expect most other calls to fail similarly until we've made some progress on the backlog, and flushing eagerly seems better than waiting for the timeout to elapse.

2. Should we allow one item of grace before tripping the limit? I.e. just check `totalBytesInFlight` vs `maxBytesInFlight`, and always add `request` to the queue if there's at least one byte of space there. I think we can afford that amount of lenience, and it'd mean we can avoid needing to estimate the size of each doc request.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java (hunk 9 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:383]: Oh so if 99% of a bulk is complete and we're just retrying that last 1%, consider it all still in flight since we're still holding onto the responses? I guess that makes sense.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java (hunk 11 above)
Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:315]: For (1) we do flush if this limit trips (we call execute() if newBulkRequestIfNeeded() is not null a few lines below). For (2) I'm changing the code to allow for the lenience you describe, which does simplify things a good bit.

Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java]: Oh sorry, you're right!

Comment (masseyke) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java]: Alright, I'm changing `newBulkRequestIfNeeded` to return a new bulk request if the bulk request is over its limits (I'm renaming the ambiguous `isOverTheLimit`) or if the totalBytesInFlight >= maxBytesInFlight. So we'll let one request go over a little, then flush it. The next one that comes through will throw an exception (without changing totalBytesInFlight). Since the only way now to increase totalBytesInFlight is to successfully add a request to a bulk, I think this covers it for us (since we do the check/flush after every add).

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStoreTests.java [hunk 12]
```diff
@@ -205,6 +210,80 @@ public void testPut() throws Exception {
...
     }
 
+    /*
+     * This tests that we don't see deadlock if we throw a lot of data at the ILMHistoryStore quickly.
+     */
+    // @TestLogging(
+    // value = "org.elasticsearch.action.bulk:trace",
+    // reason = "Logging information about locks useful for tracking down deadlock"
+    // )
+    public void testDeadlock() throws Exception {
```
Comment (joegallo) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStoreTests.java:220]: Echoing our conversation on zoom -- can you rename this test? (/me ducks when you ask what a better name would be. 😄)

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 13]
```diff
@@ -0,0 +1,427 @@
...
+
+    /**
+     * This is a task (which might be null) that is scheduled at some pont in the future to flush the bulk request and start a new bulk
+     * request. This variable is read and written to from multiple threads, and is protected by mutex.
+     */
+    private volatile Scheduler.Cancellable cancellableFlushTask = null;
+
+    private final AtomicLong executionIdGen = new AtomicLong();
+
+    private final Logger logger;
```
Comment (joegallo) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:186]: Echoing a nit from a zoom -- probably best to make sure all the loggers in this PR are static rather than instance.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 14]
```diff
@@ -0,0 +1,427 @@
...
+            long bytesBeforeNewRequest = bulkRequestUnderConstruction.estimatedSizeInBytes();
+            bulkRequestUnderConstruction.add(request);
+            totalBytesInFlight.addAndGet(bulkRequestUnderConstruction.estimatedSizeInBytes() - bytesBeforeNewRequest);
+            bulkRequestToExecute = newBulkRequestIfNeeded();
+        }
+        // execute sending the local reference outside the lock to allow handler to control the concurrency via it's configuration.
+        if (bulkRequestToExecute != null) {
+            execute(bulkRequestToExecute.v1(), bulkRequestToExecute.v2());
+        }
+        scheduleFlushTask();
```
Comment (joegallo) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:342]: Probably worth a comment about why this line is here (it does makes sense, but I could see it being something that trips somebody up in the future).

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java [hunk 15]
```diff
@@ -0,0 +1,427 @@
...
+    /**
+     * This method sends the bulkRequest to the consumer up to maxNumberOfRetries times. The executionId is used to notify the listener
+     * both before and after the request.
+     * @param bulkRequest
+     * @param executionId
+     */
+    private void execute(BulkRequest bulkRequest, long executionId) {
+        try {
+            listener.beforeBulk(executionId, bulkRequest);
+            retry.withBackoff(consumer, bulkRequest, new ActionListener<>() {
```
Comment (joegallo) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor2.java:392]: `withBackoff` is probably not the best name for this anymore.

**Review by joegallo — APPROVED** [review]

**Comment by masseyke** [comment]
@elasticmachine update branch
