### PR TITLE
Fix IndexSearcherWrapper visibility

### LINKED ISSUE #30758: ContextIndexSearcher conflicts with IndexSearcherWrapper
**Elasticsearch version** (`bin/elasticsearch --version`):
5.0.0+

**Plugins installed**: []
N/A

**JVM version** (`java -version`):
N/A

**OS version** (`uname -a` if on a Unix-like system):
N/A

**Description of the problem including expected versus actual behavior**:

Plugins can override the `onIndexModule(IndexModule indexModule)` method and call `indexModule.setSearcherWrapper`.
They implement a `IndexSearcherWrapper` (via `IndexSearcherWrapperFactory`) and override the `protected IndexSearcher wrap(IndexSearcher searcher) throws IOException` method to
wrap a given IndexSearcher. When i read the newly opened x-pack code correct it seems x-pack is doing this to implement document and field level security.

But it appears that several methods of a such wrapped IndexSearcher (like `search*`) are never really called because the wrapped IndexSearcher get itself wrapped in
a `ContextIndexSearcher` (in `DefaultSearchContext`) which never delegates the wrapped `search*` methods (and others).

For x-pack this means IMHO that the custom searcher optimizations done in [SecurityIndexSearcherWrapper](https://github.com/elastic/elasticsearch/blob/eaf672f6121c4dc2a48f3524c80fa18d39dc9d2e/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/SecurityIndexSearcherWrapper.java#L190) are never executed.

Or i'am lost in the "wrapper hell"? 

**Steps to reproduce**:
N/A

**Provide logs (if relevant)**:
N/A

### PR DESCRIPTION
**Pull request by jimczi**
This change adds a wrapper for IndexSearcher that makes IndexSearcher#search(List, Weight, Collector) visible by sub-classes. The wrapper is used by the ContextIndexSearcher to call this protected method on a searcher created by a plugin.
This ensures that an override of the protected method in an IndexSearcherWrapper plugin is called when a search is executed.

Closes #30758

### CODE REVIEW

**Review by mayya-sharipova — APPROVED** [review]
@jimczi Thanks Jim,  makes sense.

File: test/framework/src/main/java/org/elasticsearch/test/engine/MockEngineSupport.java [hunk 1]
```diff
@@ -145,8 +151,19 @@ public AssertingIndexSearcher newSearcher(Engine.Searcher searcher) throws Engin
...
+        delegate.setQueryCachingPolicy(filterCachingPolicy);
+        final XIndexSearcher wrappedSearcher = new XIndexSearcher(delegate);
         // this executes basic query checks and asserts that weights are normalized only once etc.
-        final AssertingIndexSearcher assertingIndexSearcher = new AssertingIndexSearcher(mockContext.random, wrappedReader);
+        final AssertingIndexSearcher assertingIndexSearcher = new AssertingIndexSearcher(mockContext.random, wrappedReader) {
+            @Override
+            protected void search(List<LeafReaderContext> leaves, Weight weight, Collector collector) throws IOException {
+                // we cannot use the asserting searcher because the weight is created by the ContextIndexSearcher
+                wrappedSearcher.search(leaves, weight, collector);
+            }
```
Comment (mayya-sharipova) [inline test/framework/src/main/java/org/elasticsearch/test/engine/MockEngineSupport.java]: I understand we don't want to call `AssertingIndexSearcher::search` as it will fail, as it expects `AssertingWeight`.
But I am wondering if we are losing anything by not calling `search` method of `AssertingIndexSearcher`?

Comment (jpountz) [reply test/framework/src/main/java/org/elasticsearch/test/engine/MockEngineSupport.java]: Tricky tricky, I can't think of a way to work around this?

**Review by jpountz — APPROVED** [review]
Mayya has a good point, but I can't think of a way to address it. Other than that the change looks good to me.

File: test/framework/src/main/java/org/elasticsearch/test/engine/MockEngineSupport.java (hunk 1 above)
Comment (jimczi) [reply test/framework/src/main/java/org/elasticsearch/test/engine/MockEngineSupport.java]: Yep me neither, it's not a regression though since the current code is also not using AssertingIndexSearcher::search. I think we need a better integration of the `ContextIndexSearcher` if you're willing to keep the ability to extend `IndexSearcher` in a plugin but this is probably out of the scope of this pr that I consider as a workaround (hack ;)).

**Comment by jimczi** [comment]
I had to revert the pr because some tests fail when an AssertingIndexSearcher is used on a profiled query. I'll investigate further and will open a new pr if I find a proper fix.
