### PR TITLE
Ensure tests don't use flat polygons

### LINKED ISSUE #88682: [CI] CartesianShapeQueryTests testQueryRandomGeoCollection failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/p7n7etkicebme/tests/:x-pack:plugin:spatial:internalClusterTest/org.elasticsearch.xpack.spatial.search.CartesianShapeQueryTests/testQueryRandomGeoCollection

**Reproduction line:**
`./gradlew ':x-pack:plugin:spatial:internalClusterTest' --tests "org.elasticsearch.xpack.spatial.search.CartesianShapeQueryTests.testQueryRandomGeoCollection" -Dtests.seed=D42035A03986D727 -Dtests.locale=lt -Dtests.timezone=Asia/Baku -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.spatial.search.CartesianShapeQueryTests&tests.test=testQueryRandomGeoCollection

**Failure excerpt:**
```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [geo] of type [shape]

  at __randomizedtesting.SeedInfo.seed([D42035A03986D727:CCF71E7B64748804]:0)
  at org.elasticsearch.index.mapper.AbstractGeometryFieldMapper.lambda$parse$1(AbstractGeometryFieldMapper.java:191)
  at org.elasticsearch.xpack.spatial.index.mapper.ShapeParser.parse(ShapeParser.java:40)
  at org.elasticsearch.index.mapper.AbstractGeometryFieldMapper.parse(AbstractGeometryFieldMapper.java:187)
  at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:409)
  at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:461)
  at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:313)
  at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:278)
  at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:127)
  at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
  at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:78)
  at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:999)
  at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:948)
  at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:892)
  at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:321)
  at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:187)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:253)
  at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:133)
  at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:72)
  at org.elasticsearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:211)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.IllegalArgumentException: at least three non-collinear points required

    at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:174)
    at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:152)
    at org.apache.lucene.document.XYShape.createIndexableFields(XYShape.java:83)
    at org.apache.lucene.document.XYShape.createIndexableFields(XYShape.java:72)
    at org.elasticsearch.xpack.spatial.index.mapper.CartesianShapeIndexer$LuceneGeometryVisitor.visit(CartesianShapeIndexer.java:114)
    at org.elasticsearch.xpack.spatial.index.mapper.CartesianShapeIndexer$LuceneGeometryVisitor.visit(CartesianShapeIndexer.java:50)
    at org.elasticsearch.geometry.Polygon.visit(Polygon.java:84)
    at org.elasticsearch.xpack.spatial.index.mapper.CartesianShapeIndexer$LuceneGeometryVisitor.visit(CartesianShapeIndexer.java:66)
    at org.elasticsearch.xpack.spatial.index.mapper.CartesianShapeIndexer$LuceneGeometryVisitor.visit(CartesianShapeIndexer.java:50)
    at org.elasticsearch.geometry.GeometryCollection.visit(GeometryCollection.java:51)
    at org.elasticsearch.xpack.spatial.index.mapper.CartesianShapeIndexer.indexShape(CartesianShapeIndexer.java:46)
    at org.elasticsearch.xpack.spatial.index.mapper.ShapeFieldMapper.index(ShapeFieldMapper.java:187)
    at org.elasticsearch.xpack.spatial.index.mapper.ShapeFieldMapper.index(ShapeFieldMapper.java:52)
    at org.elasticsearch.index.mapper.AbstractGeometryFieldMapper.lambda$parse$0(AbstractGeometryFieldMapper.java:187)
    at org.elasticsearch.xpack.spatial.index.mapper.ShapeParser.parse(ShapeParser.java:37)
    at org.elasticsearch.index.mapper.AbstractGeometryFieldMapper.parse(AbstractGeometryFieldMapper.java:187)
    at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:409)
    at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:461)
    at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:313)
    at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:278)
    at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:127)
    at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:78)
    at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:999)
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:948)
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:892)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:321)
    at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:187)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:253)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:133)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:72)
    at org.elasticsearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:211)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by craigtaverner**
Polygons with colinear points cannot be tessellated.

Closes #88682

### CODE REVIEW

File: x-pack/plugin/spatial/src/internalClusterTest/java/org/elasticsearch/xpack/spatial/search/CartesianShapeQueryTestCase.java [hunk 1]
```diff
@@ -71,8 +69,7 @@ protected Point nextPoint() {
     }
 
     protected Polygon nextPolygon() {
-        org.apache.lucene.geo.Polygon randomPoly = GeoTestUtil.nextPolygon();
-        return new Polygon(new LinearRing(randomPoly.getPolyLons(), randomPoly.getPolyLats()));
+        return ShapeTestUtils.randomPolygon(false);
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/internalClusterTest/java/org/elasticsearch/xpack/spatial/search/CartesianShapeQueryTestCase.java:72]: I had used the GeoTestUtil polygon before because I wanted one polygon in 'normal' range (small reasonable numbers) amongst all the other test polygons that were using extreme numbers. But switching back to the ShapeTestUtils is much more readible, rational, and allows the same fix for the geometry collection to apply to the single polygon.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeTestUtils.java [hunk 2]
```diff
@@ -27,10 +27,13 @@
 import java.util.function.Function;
 
 import static org.elasticsearch.geo.GeometryTestUtils.linearRing;
+import static org.elasticsearch.test.ESTestCase.randomValueOtherThanMany;
 
 /** generates random cartesian shapes */
 public class ShapeTestUtils {
 
+    public static final double MIN_VALID_AREA = 1e-10;
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeTestUtils.java:35]: So this threshold is rather arbitrary. For testing purposes this is probably fine though, and this is a test-only class. However, if you want something better we could use something closer to the actual rounding error between float/double which I think could be sufficient.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeTestUtils.java [hunk 3]
```diff
@@ -96,6 +99,16 @@ public static Polygon randomPolygon(boolean hasAlt) {
         return new Polygon(linearRing(floatsToDoubles(lucenePolygon.getPolyX()), floatsToDoubles(lucenePolygon.getPolyY()), hasAlt));
     }
 
+    static double area(XYPolygon p) {
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeTestUtils.java:102]: This is copied from the geo version, but I wonder (in both geo and cartesian) whether this is really a true 'area'. Perhaps the method should have another name?

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeUtilTests.java [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+import org.apache.lucene.geo.XShapeTestUtil;
+import org.apache.lucene.geo.XYPolygon;
+import org.apache.lucene.geo.XYRectangle;
+import org.elasticsearch.test.ESTestCase;
+
+import static org.hamcrest.Matchers.greaterThan;
+import static org.hamcrest.Matchers.lessThan;
+
+public class ShapeUtilTests extends ESTestCase {
+    public void testBox() {
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeUtilTests.java:19]: So this test class has a few pretty arbitrary tests in it. This is because there was no existing test class for ShapeTestUtils, and I wanted at least some test of the new `area()` function, and added a couple of basic tests just make a start on perhaps adding more test coverage later. Since we're testing a test-only class the need for tests is not that high, but I think it still has value, and also is very useful when wanting to debug specific test methods.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeUtilTests.java [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+
+    public void testPolygon() {
+        XYPolygon geom = XShapeTestUtil.nextPolygon();
+        assertThat("Geometry minX should be less than maxX", geom.minX, lessThan(geom.maxX));
+        assertThat("Geometry minY should be less than maxY", geom.minY, lessThan(geom.maxY));
+        assertThat("Geometry area should be non-zero", ShapeTestUtils.area(geom), greaterThan(0.0));
+    }
+
+    public void testFlatRectangle() {
+        XYPolygon geom = new XYPolygon(
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeUtilTests.java:33]: This test exists primarily to demonstrate the bad behaviour of the original failing test. Debugging that was not easy. I think having a failing test is good. In this case since I'm testing the return value of the area function, I do not look for an actual failure, just that the value is below the threshold.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeTestUtils.java (hunk 3 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeTestUtils.java:102]: The method could be private? Feel free to rename it, I think this just the Shoelace formula applied here.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeUtilTests.java (hunk 5 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/ShapeUtilTests.java:33]: that;s good

**Review by iverase — APPROVED** [review]
LGTM

**Comment by craigtaverner** [comment]
@elasticmachine test this please
