### PR TITLE
Relax translog assertion for inference fields

### LINKED ISSUE #120975: [CI] ShardBulkInferenceActionFilterIT testBulkOperations {p0=false} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6042 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/3fou4u3jzrjji)
- [elasticsearch-pull-request #53317 / part-2](https://gradle-enterprise.elastic.co/s/mjley6slgt3rw)
- [elasticsearch-pull-request #53173 / part-2](https://gradle-enterprise.elastic.co/s/znrpbtotgizlo)
- [elasticsearch-intake #16490 / part2](https://gradle-enterprise.elastic.co/s/wckgnfk4gkfv2)
- [elasticsearch-pull-request #53044 / part-2](https://gradle-enterprise.elastic.co/s/v63rij5m4kons)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:internalClusterTest" --tests "org.elasticsearch.xpack.inference.action.filter.ShardBulkInferenceActionFilterIT.testBulkOperations {p0=false}" -Dtests.seed=268F755E41789893 -Dtests.locale=nn-NO -Dtests.timezone=America/Santa_Isabel -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.action.filter.ShardBulkInferenceActionFilterIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testBulkOperations%20%7Bp0%3Dfalse%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 5 failures in test testBulkOperations {p0=false} (1.8% fail rate in 280 executions)
- [main] 3 failures in step part-2 (2.2% fail rate in 138 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.1% fail rate in 140 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120979: [CI] RestEsqlIT testInternalRange {ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic #6046 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/af3wdhkdrwrha)
- [elasticsearch-intake #16489 / part3](https://gradle-enterprise.elastic.co/s/lrfmmjvlold4y)
- [elasticsearch-periodic-platform-support #6035 / ubuntu-1804_platform-support-unix](https://gradle-enterprise.elastic.co/s/zecakfyfn2gr4)
- [elasticsearch-periodic-platform-support #6035 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/zndnea2h4ba6e)
- [elasticsearch-periodic-platform-support #6035 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/cpjlyag32j35o)
- [elasticsearch-periodic #6046 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ffrbgb7r2vwra)
- [elasticsearch-intake #16487 / part3](https://gradle-enterprise.elastic.co/s/pssaskf7qjhjw)
- [elasticsearch-periodic-platform-support #6035 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/ymihwipwo52vo)
- [elasticsearch-intake #16481 / part3](https://gradle-enterprise.elastic.co/s/sv2ex3iqtipxq)
- [elasticsearch-intake #16480 / part3](https://gradle-enterprise.elastic.co/s/bkpridgupv3zy)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT.testInternalRange {ASYNC}" -Dtests.seed=C12CE00B1A4EEF0D -Dtests.locale=ff-Adlm-BF -Dtests.timezone=Etc/GMT+9 -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testInternalRange%20%7BASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:43227], URI [/_query/async/FkNjNEhBR2JHU09tUlNKWFY1MDN1ZWcbOFNLdmx4US1TVmF4amxUend2Q0pkUToyMzAy?wait_for_completion_timeout=60s&pretty=true&error_trace=true], status line [HTTP/1.1 502 Bad Gateway]
¿eerror¿jroot_cause¿dtypexnode_not_connected_exceptionfreasonx;[test-cluster-1][127.0.0.1:45271] connection already closedkstack_tracexsorg.elasticsearch.transport.NodeNotConnectedException: [test-cluster-1][127.0.0.1:45271] connection already closed
ÿÿdtypexnode_not_connected_exceptionfreasonx;[test-cluster-1][127.0.0.1:45271] connection already closedkstack_tracexsorg.elasticsearch.transport.NodeNotConnectedException: [test-cluster-1][127.0.0.1:45271] connection already closed
ÿfstatusöÿ
```

**Issue Reasons:**
- [8.x] 4 consecutive failures in test testInternalRange {ASYNC}
- [8.x] 2 consecutive failures in step part3
- [8.x] 2 consecutive failures in pipeline elasticsearch-intake
- [8.x] 19 failures in test testInternalRange {ASYNC} (10.7% fail rate in 178 executions)
- [8.x] 9 failures in step part3 (39.1% fail rate in 23 executions)
- [8.x] 2 failures in step part-3 (4.1% fail rate in 49 executions)
- [8.x] 9 failures in pipeline elasticsearch-intake (39.1% fail rate in 23 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (4.1% fail rate in 49 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120980: [CI] RestEsqlIT testWarningHeadersOnFailedConversions {ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6035 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/ymihwipwo52vo)
- [elasticsearch-pull-request #53119 / part-3](https://gradle-enterprise.elastic.co/s/gpf6ieax5e7ty)
- [elasticsearch-intake #16480 / part3](https://gradle-enterprise.elastic.co/s/bkpridgupv3zy)
- [elasticsearch-intake #16479 / part3](https://gradle-enterprise.elastic.co/s/rv45gtmhdfcoa)
- [elasticsearch-periodic #6046 / openjdk17_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/qn5oq6ss4ef6k)
- [elasticsearch-periodic-platform-support #6035 / almalinux-8-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/w3yf7mtojzoue)
- [elasticsearch-intake #16478 / part3](https://gradle-enterprise.elastic.co/s/dseoofm5tfmjk)
- [elasticsearch-intake #16474 / part3](https://gradle-enterprise.elastic.co/s/xjwaahketz5gu)
- [elasticsearch-intake #16470 / part3](https://gradle-enterprise.elastic.co/s/eukgncz2mgxlk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT.testInternalRange {ASYNC}" -Dtests.seed=F5D4B475D16DFC9F -Dtests.locale=sr-Latn -Dtests.timezone=Kwajalein -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testWarningHeadersOnFailedConversions%20%7BASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:38781], URI [/_query/async/FjZtdVRiNHJNUmQtTVN5dDZsNnpyeFEbVlpwRzhfQ2xScWFReXBUQjdZX1ZEZzo0NDI1?wait_for_completion_timeout=60s&pretty=true&error_trace=true], status line [HTTP/1.1 502 Bad Gateway]
¿eerror¿jroot_cause¿dtypexnode_not_connected_exceptionfreasonx4[test-cluster-0][127.0.0.1:33989] Node not connectedkstack_tracexlorg.elasticsearch.transport.NodeNotConnectedException: [test-cluster-0][127.0.0.1:33989] Node not connected
ÿÿdtypexnode_not_connected_exceptionfreasonx4[test-cluster-0][127.0.0.1:33989] Node not connectedkstack_tracexlorg.elasticsearch.transport.NodeNotConnectedException: [test-cluster-0][127.0.0.1:33989] Node not connected
ÿfstatusöÿ
```

**Issue Reasons:**
- [8.x] 9 failures in test testWarningHeadersOnFailedConversions {ASYNC} (5.3% fail rate in 170 executions)
- [8.x] 5 failures in step part3 (25.0% fail rate in 20 executions)
- [8.x] 5 failures in pipeline elasticsearch-intake (25.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121007: [CI] RestEsqlIT testOutOfRangeComparisons {ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6045 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/wgm3s3qb3ulmw)
- [elasticsearch-periodic-platform-support #6045 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/7akychtwht5im)
- [elasticsearch-periodic-platform-support #6045 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/w7n3vd7pl5kpg)
- [elasticsearch-periodic-platform-support #6045 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/5f5vlxz52cfoo)
- [elasticsearch-periodic #6056 / openjdk23_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/ekcp474iylgxq)
- [elasticsearch-pull-request #53192 / part-3](https://gradle-enterprise.elastic.co/s/gylhknerjz2pu)
- [elasticsearch-intake #16522 / part3](https://gradle-enterprise.elastic.co/s/oqwew5ogruure)
- [elasticsearch-intake #16521 / part3](https://gradle-enterprise.elastic.co/s/x4kafozx6zgqu)
- [elasticsearch-pull-request #53218 / part-3](https://gradle-enterprise.elastic.co/s/zhouqkc7vvzeo)
- [elasticsearch-pull-request #53202 / part-3](https://gradle-enterprise.elastic.co/s/63rqpc34yeu6s)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT.testOutOfRangeComparisons {ASYNC}" -Dtests.seed=9727FCA186E97D63 -Dtests.locale=pa-Guru-IN -Dtests.timezone=Pacific/Pitcairn -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testOutOfRangeComparisons%20%7BASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:34113], URI [/_query/async/FjRMTHMtblRlUmp5aXdlS2lWVjZ6cmcbelFNckYtcEZRN0dpMWliMC05ODlKUToyODQ5?wait_for_completion_timeout=60s&pretty=true&error_trace=true], status line [HTTP/1.1 502 Bad Gateway]
¿eerror¿jroot_cause¿dtypexnode_not_connected_exceptionfreasonx;[test-cluster-1][127.0.0.1:35217] connection already closedkstack_tracexsorg.elasticsearch.transport.NodeNotConnectedException: [test-cluster-1][127.0.0.1:35217] connection already closed
ÿÿdtypexnode_not_connected_exceptionfreasonx;[test-cluster-1][127.0.0.1:35217] connection already closedkstack_tracexsorg.elasticsearch.transport.NodeNotConnectedException: [test-cluster-1][127.0.0.1:35217] connection already closed
ÿfstatusöÿ
```

**Issue Reasons:**
- [8.x] 3 consecutive failures in test testOutOfRangeComparisons {ASYNC}
- [8.x] 2 consecutive failures in step opensuse-leap-15_platform-support-unix
- [8.x] 29 failures in test testOutOfRangeComparisons {ASYNC} (18.6% fail rate in 156 executions)
- [8.x] 8 failures in step part-3 (16.3% fail rate in 49 executions)
- [8.x] 10 failures in step part3 (40.0% fail rate in 25 executions)
- [8.x] 2 failures in step opensuse-leap-15_platform-support-unix (66.7% fail rate in 3 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic-platform-support (75.0% fail rate in 4 executions)
- [8.x] 8 failures in pipeline elasticsearch-pull-request (17.8% fail rate in 45 executions)
- [8.x] 10 failures in pipeline elasticsearch-intake (40.0% fail rate in 25 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
The inference fields are synthesized from doc_values, regardless of whether the synthetic source is enabled. This change relaxes the translog assertions, allowing inference fields in the same way as we did with the synthetic source.

Relates #120045

Closes #120979
Closes #121007
Closes #120980
Closes #120975

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM, thanks @dnhatn!

**Comment by dnhatn** [comment]
Thanks Jim!

File: server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java [hunk 1]
```diff
@@ -97,7 +97,7 @@ static DirectoryReader create(
             // When using synthetic source, the translog operation must always be reindexed into an in-memory Lucene to ensure consistent
             // output for realtime-get operations. However, this can degrade the performance of realtime-get and update operations.
             // If slight inconsistencies in realtime-get operations are acceptable, the translog operation can be reindexed lazily.
-            if (mappingLookup.isSourceSynthetic()) {
+            if (mappingLookup.isSourceSynthetic() || mappingLookup.inferenceFields().isEmpty() == false) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:100]: I think this is ok as a stop-gap.

I wonder if this implies that real-time GET is now more expensive also when there are inference fields? And with this change we now include the inference fields in the real-time GET results?

If so, I wonder if that is the right way to think about inference fields. Given that they are not stored in source, it would possibly make sense to let real-time GET not return them.

I also worry that there could be a discrepancy now where reading real-time GET from translog has inference fields whereas reading from lucene directly does not. Did not check this, thinking you know the answer to it?

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java:100]: Thanks for spotting this, Henning!
We should likely restrict this behavior to TranslogOperationAsserter or . The main issue with directly comparing the raw source is that the original _inference_fields may have different precision than the indexed _inference_fields, which is restored from doc values for recovery.

For real-time GET, prior to this change, we relied on source filtering being applied in the [translog reader](https://github.com/elastic/elasticsearch/blob/5bcd170a0bde0c155a36751e034381de3606208c/server/src/main/java/org/elasticsearch/index/engine/TranslogDirectoryReader.java#L523). Therefore, this change isn't technically necessary for real-time GET, as the expectation is to return _source without _inference_fields.

That said, this change doesn’t break existing behavior, since _inference_fields is still removed from _source when parsing the document. The real concern, as you pointed out, is the additional cost of indexing the document just to obtain the pruned source. Given that we’re only removing a single field, this feels unnecessarily expensive.
I'll follow up with a PR with the proposed approach to discuss.
