### PR TITLE
Set acking timeout to 0 on dynamic mapping update

### LINKED ISSUE #30844: [CI]  IndexingMasterFailoverIT.testMasterFailoverDuringIndexingWithMappingChanges fails
The failure was in an PR build https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/10444/consoleText but after discussion with @ywelsch it doesn't seem to be related to the PR where it failed, but intstead might have been caused by #30672.

The failure doesn't reproduce:

```
  2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=A12A9F8545E5EC2C -Dtests.class=org.elasticsearch.action.support.master.IndexingMasterFailoverIT -Dtests.method="testMasterFailoverDuringIndexingWithMappingChanges" -Dtests.security.manager=true -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=Etc/GMT-1
ERROR   19.4s J2 | IndexingMasterFailoverIT.testMasterFailoverDuringIndexingWithMappingChanges <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <10L>
   >      but: was <0L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.action.support.master.IndexingMasterFailoverIT.testMasterFailoverDuringIndexingWithMappingChanges(IndexingMasterFailoverIT.java:143)
   > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=5371, name=indexingThread, state=RUNNABLE, group=TGRP-IndexingMasterFailoverIT]
   > Caused by: ElasticsearchTimeoutException[Failed to acknowledge mapping update within [25s]]
   > 	at __randomizedtesting.SeedInfo.seed([A12A9F8545E5EC2C]:0)
   > 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:90)
   > 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:80)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction$ConcreteMappingUpdatePerformer.updateMappings(TransportShardBulkAction.java:620)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:591)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:566)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:142)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:248)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:125)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:112)
   > 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:74)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1018)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:996)
   > 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:103)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:357)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:297)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:959)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:956)
   > 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:266)
   > 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:233)
   > 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2178)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:968)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:98)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:318)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:293)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:280)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:724)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by ywelsch**
As acking can fail for any reason (unrelated node being too slow, node disconnecting), it should not be required for acking to succeed in order for index requests with dynamic mapping updates to successfully complete.

Relates to #30672 and Closes #30844

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java [hunk 1]
```diff
@@ -315,6 +309,7 @@ public void testDelayedMappingPropagationOnReplica() throws Exception {
             Settings.builder()
                 .put(DiscoverySettings.COMMIT_TIMEOUT_SETTING.getKey(), "30s") // explicitly set so it won't default to publish timeout
                 .put(DiscoverySettings.PUBLISH_TIMEOUT_SETTING.getKey(), "0s") // don't wait post commit as we are blocking things by design
+                .put(MappingUpdatedAction.INDICES_MAPPING_DYNAMIC_TIMEOUT_SETTING.getKey(), "2s")
```
Comment (bleskes) [inline server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: can you elaborate on the rational of how you got to 2s?

**Review by bleskes — COMMENTED** [review]
I left a question. I also want to discuss the following - since we're ignoring the ack, should we also just not set it to the mapping timeout but rather always to 0?

File: server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java (hunk 1 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: it's high enough so that the cluster state update task will actually get to run. It's low enough so that the test still finishes in a reasonable amount of time.

**Comment by ywelsch** [comment]
If I read the code correctly, setting the timeout to 0 would result in the update mapping call returning prematurely, even before the publishing has started, which is certainly not what we want?

**Comment by ywelsch** [comment]
After merging #31303, I've updated this PR to set the acking timeout to 0.

**Comment by ywelsch** [comment]
This triggered a failure on the doc tests, which uncovered a larger issue. The reason is that with this change, we now always trigger a RetryOnPrimaryException in case of a dynamic mapping update. In return this can lead to the local checkpoint getting stuck on a replica. I've added a test that illustrates this in e8e6374

**Comment by ywelsch** [comment]
@bleskes I've updated this PR, which is now simpler due to the refactoring of TransportShardBulkAction.

File: server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java [hunk 2]
```diff
@@ -397,6 +399,21 @@ public void onFailure(Exception e) {
 
         assertBusy(() -> assertTrue(client().prepareGet("index", "type", "1").get().isExists()));
 
+        ActionFuture<IndexResponse> dynamicMappingsFut = client().prepareIndex("index", "type", "2").setSource("field2", 42).execute();
```
Comment (bleskes) [inline server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: I presume this just biffs up the test, or am I missing something specific?

Comment (bleskes) [reply server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: I also wonder if we sometime should not have an extra field

**Review by bleskes — APPROVED** [review]
LGTM.

File: server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java (hunk 2 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: the first document that is put on the test does not use dynamic mappings (there is an explicit putMapping call for that one). This one does an actual dynamic mapping update (the thing we changed in this PR).
Not having an extra field is just what the first document tests :)

Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: I've added a comment to the test here to clarify

**Comment by ywelsch** [comment]
The test failure here uncovered a problem with CCR I think. The failure is:
```
WARNING: Uncaught exception in thread: Thread[elasticsearch[followerd4][write][T#2],5,TGRP-IndexFollowingIT]
  2> java.lang.AssertionError: Only already-processed error should happen; op=[Index{id='1', type='doc', seqNo=0, primaryTerm=1, version=1, autoGeneratedIdTimestamp=-1}] error=[null]
```

I suspect that this is fails because the follower does not have the right mapping update for the batch of operations that it tries to index. CCR gets a batch of operations from the leader cluster and assumes that the mapping version that it uses from the `ClusterService` is at least as up-to-date as the operations that it gets from the index. This is not true, because we only expose the cluster state on `ClusterService` after it's been applied to the shard (and the index operation have possibly already occurred).

/cc: @martijnvg @jasontedor

File: server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java (hunk 2 above)
Comment (bleskes) [reply server/src/test/java/org/elasticsearch/indices/state/RareClusterStateIT.java]: Ok, thanks. I thought that the first call was indeed dynamic (and also adds a type, which is why another call to only add a field is required). Thanks for clarifying.
