### PR TITLE
SQL: Fix issue with timezone when paginating

### LINKED ISSUE #51258: SQL: GROUP BY with timezone and small page size returns duplicate values
The following query on the test `employees.csv`:
```
POST _sql
{
  "query": "SELECT YEAR(birth_date) FROM employees GROUP BY YEAR(birth_date)",
  "time_zone": "Europe/Berlin",
  "fetch_size": 1
}
```
will return the following paged results: `null`, `1952`, `1952`, ...
Increasing the page size to 2 will duplicate `1954`.

This doesn't (easily?) reproduce without a non-Z timezone.

### PR DESCRIPTION
**Pull request by matriv**
Previously, when the specified (or default) fetchSize led to
subsequent HTTP requests and the usage of cursors, those subsequent
were no longer using the client timezone specified in the initial
SQL query. As a consequence, Even though the query is executed once
(with the correct timezone) the processing of the query results by
the HitExtractors in the next pages was done using the default
timezone `Z`. This could lead to incorrect results.

Fix the issue by correctly using the initially specified timezone,
which is found in the deserialisation of the cursor string.

Fixes: #51258

### CODE REVIEW

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/FetchSizeTestCase.java [hunk 1]
```diff
@@ -102,6 +107,51 @@ public void testIncompleteScroll() throws Exception {
...
+            bulk.append("{\"date\":").append(datetime).append("}\n");
+        }
+        request.setJsonEntity(bulk.toString());
+        assertEquals(200, client().performRequest(request).getStatusLine().getStatusCode());
+
+        ZoneId zoneId = randomZone();
+        Properties connectionProperties = connectionProperties();
+        connectionProperties.put(JDBC_TIMEZONE, zoneId.toString());
+        try (Connection c = esJdbc(connectionProperties);
+             Statement s = c.createStatement()) {
```
Comment (astefan) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/FetchSizeTestCase.java]: Can you move this line on the above one?

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/FetchSizeTestCase.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/FetchSizeTestCase.java]: Sure, just kept the style from the other tests, e.g.: https://github.com/elastic/elasticsearch/pull/52101/files/a488512e3abd83b8de95ef0cbfcd9b2adc2b8a86#diff-7eb5a40bcec78e0f582b7ef886430b28R95

Comment (bpintea) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/FetchSizeTestCase.java]: A(n appropriate) formatter should help in these style-adjusting cases.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java [hunk 2]
```diff
@@ -151,6 +155,70 @@ public void testNextPage() throws IOException {
...
+        request.setJsonEntity(bulk.toString());
+        assertEquals(200, client().performRequest(request).getStatusLine().getStatusCode());
+
+        ZoneId zoneId = randomZone();
+        String mode = randomMode();
+        String sqlRequest =
+                "{\"query\":\"SELECT DATE_PART('TZOFFSET', date) AS tz FROM test_date_timezone ORDER BY date\","
+                        + "\"time_zone\":\"" + zoneId.getId() + "\", "
+                        + "\"mode\":\"" + mode + "\", "
+                        + "\"fetch_size\":2}";
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java]: I think it's perfectly fine as is, but was curious about the reason - if any - for choosing a `fetch_size` of `2`, vs. `1`, which would simplify the test just a bit.

**Review by bpintea — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java]: Fetch size `2` and odd number of rows ('5') makes the last page to return 1 row.

Comment (bpintea) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java]: Sure, there'll be pages with 1 and 2 rows as the `j`-based `for` makes it obvious.
But I was only curious to understand why is _that_ desired in respect to what the test checks (i.e. all rows have the same timezone). Sorry if missing anything obvious. :-)

Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java]: Doesn't have to do with the bug fixed, just another safety testing that the fetch size behavior is correct.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java [hunk 3]
```diff
@@ -80,13 +83,14 @@ public static void operation(PlanExecutor planExecutor, SqlQueryRequest request,
             planExecutor.sql(cfg, request.query(), request.params(),
                     wrap(p -> listener.onResponse(createResponseWithSchema(request, p)), listener::onFailure));
         } else {
-            planExecutor.nextPage(cfg, Cursors.decodeFromString(request.cursor()),
-                    wrap(p -> listener.onResponse(createResponse(request, null, p)),
+            Tuple<Cursor, ZoneId> decoded = Cursors.decodeFromStringWithZone(request.cursor());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java]: Is `Cursors.decodeFromString` used anywhere else ? It might be that decoding a tuple of timezone or adding it as a property in the `Cursor` class should be the default.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java [hunk 4]
```diff
@@ -68,7 +71,7 @@ protected void doExecute(Task task, SqlQueryRequest request, ActionListener<SqlQ
     /**
      * Actual implementation of the action. Statically available to support embedded mode.
      */
-    public static void operation(PlanExecutor planExecutor, SqlQueryRequest request, ActionListener<SqlQueryResponse> listener,
+    private static void operation(PlanExecutor planExecutor, SqlQueryRequest request, ActionListener<SqlQueryResponse> listener,
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java]: Nit: why make it private ? I think this will make things a bit harded in debug project.

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java (hunk 4 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java]: Ah, didn't think of that, Thx, I'll revert

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java (hunk 3 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java]: I'm planning to do that in an upcoming PR.

Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java]: Ad discussed, will not pass the zoneId into the Cursor, as zoneId is the responsibility of SqlInput/OutputStreams to handle. Instead, I remove the `decodeFromString` and only use the `decodeFromStringWithZone`, so it's obvious for consumers that the zoneId is always decoded as well and returned as part of the returned `Tuple`.
