### PR TITLE
Stabilize testSnapshotDeleteRelocatingPrimaryIndex

### LINKED ISSUE #61069: [CI] SharedClusterSnapshotRestoreIT.testSnapshotDeleteRelocatingPrimaryIndex failure
**Build scan**: https://gradle-enterprise.elastic.co/s/3rp4lbivwnjm4

**Repro line**:

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotDeleteRelocatingPrimaryIndex" -Dtests.seed=6D7443E6227C2B76 -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=Asia/Phnom_Penh -Druntime.java=14
```

**Reproduces locally?**: No

**Applicable branches**: 7.8

**Failure excerpt**:

```
org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT > testSnapshotDeleteRelocatingPrimaryIndex FAILED
    java.lang.AssertionError: 
    Expected: <PARTIAL>
         but: was <SUCCESS>
        at __randomizedtesting.SeedInfo.seed([6D7443E6227C2B76:936AC042F420BCA9]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotDeleteRelocatingPrimaryIndex(SharedClusterSnapshotRestoreIT.java:2164)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
With `100` documents the relocation might finish before the snapshot starts
causing no shards to fail snapshotting as expected.

Closes #61069

### CODE REVIEW

**Comment by original-brownbear** [comment]
This was only reported for 7.8 but is still a possible failure in 7.9+ (though much less likely because snapshots are much quicker to start without the init step in snapshotting now) so I think this is a useful fix and worth the 5s that the test will take extra because of it.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 1]
```diff
@@ -2044,7 +2044,8 @@ public void testSnapshotDeleteRelocatingPrimaryIndex() throws Exception {
         final String indexName = "test-idx";
         assertAcked(prepareCreate(indexName, 2, indexSettingsNoReplicas(between(2, 10))));
         ensureGreen(indexName);
-        indexRandomDocs(indexName, 100);
+        // Use a large number of documents so the relocation below takes long enough for the snapshot to run concurrently
+        indexRandomDocs(indexName, 25000);
```
Comment (ywelsch) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:2048]: Can we instead block relocation from completing? Otherwise there's still theoretically a race (albeit less likely)

Comment (original-brownbear) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:2048]: Do we have a pre-packaged way of doing that in tests? (I couldn't find one, hence this fix) I could try to come up with one if we don't but it looks like that would take a bit of work.

Comment (ywelsch) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:2048]: Something along the lines of `IndexRecoveryIT.RecoveryActionBlocker`

Comment (original-brownbear) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Thanks! Could've though of that myself :facepalm: -> moved the test to the dedicated cluster tests now for this so I can just black-hole the file chunk requests but don't have to bother with cleaning up the cluster networking after the test.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!
