### PR TITLE
Fix a race condition in reindex's rethrottle

### LINKED ISSUE #18744: UpdatebyQuery Rethrottle tests hangs
build URL:
http://build-us-00.elastic.co/job/es_core_master_window-2012/3196/testReport/junit/org.elasticsearch.index.reindex/RethrottleTests/testUpdateByQuery/

failure:
```
Test abandoned because suite timeout was reached.
```

reproduce URL:
```
gradle :modules:reindex:test -Dtests.seed=A5B5FA09B74893C9 -Dtests.class=org.elasticsearch.index.reindex.RethrottleTests -Dtests.method="testUpdateByQuery" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=894m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=da-DK -Dtests.timezone=Europe/Isle_of_Man
```

### PR DESCRIPTION
**Pull request by nik9000**
If you rethrottled the request while is was performing a scroll
request then it wouldn't properly pick up the rethrottle for that
batch. This was causing test failure and might cause issues for
users. The work around is simple though: just issue the rethrottle
again with a slightly faster throttle than the first time.

Caught by:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=centos/525/console

Closes #18744

### CODE REVIEW

**Comment by nik9000** [comment]
@dakrone and @tlrx, this might interest you?

**Comment by nik9000** [comment]
Rebased to make the merge clean. Looks like no review started yet so it was safe.

**Comment by nik9000** [comment]
@dakrone, could you have a look when you get a chance?

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java [hunk 1]
```diff
@@ -403,9 +403,11 @@ float getRequestsPerSecond() {
      * Schedule prepareBulkRequestRunnable to run after some delay. This is where throttling plugs into reindexing so the request can be
      * rescheduled over and over again.
      */
-    void delayPrepareBulkRequest(ThreadPool threadPool, TimeValue delay, AbstractRunnable prepareBulkRequestRunnable) {
+    void delayPrepareBulkRequest(ThreadPool threadPool, TimeValue lastBatchStartTime, int lastBatchSize,
+            AbstractRunnable prepareBulkRequestRunnable) {
         // Synchronize so we are less likely to schedule the same request twice.
         synchronized (delayedPrepareBulkRequestReference) {
+            TimeValue delay = throttleWaitTime(lastBatchStartTime, lastBatchSize);
```
Comment (dakrone) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java]: It's not apparent where this `delay` is used, is it a leftover?

**Comment by dakrone** [comment]
Left one comment, otherwise LGTM

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java (hunk 1 above)
Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkByScrollTask.java]: It is used under the one time use runnable - I'll extract the big runnable so this is easier to read.

**Comment by nik9000** [comment]
Thanks for reviewing @dakrone !
