### PR TITLE
Fix ShardSearchRequest cache key

### LINKED ISSUE #32827: IndicesRequestCacheIT#testQueryRewrite fails
IndicesRequestCacheIT#testQueryRewrite fails with an unexpected cache count.

```
FAILURE 7.39s J1 | IndicesRequestCacheIT.testQueryRewrite <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <3L>
   >      but: was <2L>
   > 	at __randomizedtesting.SeedInfo.seed([7B6066660D23E3B1:8A7EC1C3E5F6C580]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.indices.IndicesRequestCacheIT.testQueryRewrite(IndicesRequestCacheIT.java:131)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This does not reproduce locally for me.

```
./gradlew :server:integTest \
  -Dtests.seed=7B6066660D23E3B1 \
  -Dtests.class=org.elasticsearch.indices.IndicesRequestCacheIT \
  -Dtests.method="testQueryRewrite" \
  -Dtests.security.manager=true \
  -Dtests.locale=en \
  -Dtests.timezone=Europe/Gibraltar \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/6845/console
Log: [testQueryRewrite.txt](https://github.com/elastic/elasticsearch/files/2284988/testQueryRewrite.txt)

### PR DESCRIPTION
**Pull request by jimczi**
This commit ensures that we don't use the non-deterministic `canReturnNullResponseIfMatchNoDocs` boolean in the cache key of the `ShardSearchRequest`. 

The value of this boolean has no influence on the cacheability of the request.

Closes #32827

### CODE REVIEW

**Review by javanna — APPROVED** [review]
LGTM

**Review by mayya-sharipova — APPROVED** [review]
Thanks @jimczi , makes sense

File: server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java [hunk 1]
```diff
@@ -219,7 +219,9 @@ protected final void innerWriteTo(StreamOutput out, boolean asKey) throws IOExce
             out.writeOptionalString(preference);
         }
         if (out.getVersion().onOrAfter(Version.V_7_7_0)) {
-            out.writeBoolean(canReturnNullResponseIfMatchNoDocs);
+            if (asKey == false) {
+                out.writeBoolean(canReturnNullResponseIfMatchNoDocs);
+            }
```
Comment (mayya-sharipova) [inline server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java]: @jimczi  I was wondering if should also do this for `bottomSortValues` as well?

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/internal/ShardSearchRequest.java]: ++, I pushed https://github.com/elastic/elasticsearch/pull/54071/commits/d7d1c86d5ccf9d130d83aaa83c8c74cb0cf63d57
