### PR TITLE
Don't fail retention lease sync actions due to capacity constraints

### LINKED ISSUE #105926: Retention lease sync actions should not trip circuit breakers
Today `RetentionLeaseSyncAction` and `RetentionLeaseBackgroundSyncAction` are both subject to circuit-breaker and indexing pressure checks, and in particular can fail the ~primary~replica if such a request were to fail. However these actions don't really need any resources so it'd seem better to me if we didn't fail the ~primary~replica in this situation.

~Specifically, I think we should set `forceExecutionOnPrimary` when calling the superclass constructor (which overrides the indexing pressure checks too, see `org.elasticsearch.action.support.replication.TransportWriteAction#force`).~

(edit: s/primary/replica)

### PR DESCRIPTION
**Pull request by nicktindall**
Closes #105926

`RetentionLeaseSyncAction` replicates the retention leases from the primary node to the replicas and persists them to disk on both the primary and replicas.

`RetentionLeaseSyncAction` is a `TransportWriteAction`. A `TransportWriteAction` executes an update on the primary copy of the shard then on the replica(s). If the primary operation succeeds, but the replica operation(s) do not, the shard is marked as failed and an expensive recovery process is kicked off.

One of the reasons a `TransportAction` can fail is due to the [circuit breakers](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html) residing on each node. If a request comes in and the node is very busy it can fail an action to prevent running out of memory. 

Because the `RetentionLeaseSyncAction` consumes a negligible amount of memory, this PR excludes the replica component of the `RetentionLeaseSyncAction` and `BackgroundRetentionLeaseSyncAction` from the circuit breaker checks. This will prevent a costly failure without significantly increasing the risk of out-of-memory errors.

Edit: It has also [become apparent](https://github.com/elastic/elasticsearch/issues/105926#issuecomment-2254618844) that the indexing pressure check can fail the retention lease sync. I've included an additional change in this PR to force execution of the action on the primary to bypass such checks. Indexing pressure checks are already bypassed on the replica by default in `TransportReplicationAction`

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 1]
```diff
@@ -171,8 +159,7 @@ protected TransportReplicationAction(
         Writeable.Reader<Request> requestReader,
         Writeable.Reader<ReplicaRequest> replicaRequestReader,
         Executor executor,
-        boolean syncGlobalCheckpointAfterOperation,
-        boolean forceExecutionOnPrimary
+        ActionFlags... flags
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:162]: Instead of continuing to add booleans to this constructor, I thought it might be better to take a set of flags. This should help readability.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 2]
```diff
@@ -210,14 +197,14 @@ protected TransportReplicationAction(
             transportReplicaAction,
             executor,
             true,
-            true,
+            ArrayUtils.contains(flags, ActionFlags.BypassCircuitBreakerOnReplica) == false,
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:200]: The flags should represent deviations from the default so in this case, where we want to allow tripping the circuit breaker by default, we look for the absence of the bypass flag

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportWriteAction.java [hunk 3]
```diff
@@ -94,8 +95,7 @@ protected TransportWriteAction(
             request,
             replicaRequest,
             EsExecutors.DIRECT_EXECUTOR_SERVICE,
-            true,
-            forceExecutionOnPrimary
+            ArrayUtils.including(flags, ActionFlags.SyncGlobalCheckpointAfterOperation)
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportWriteAction.java:98]: In this case, all `TransportWriteActions` `SyncGlobalCheckpointAfterOperation` so we add that if it isn't present.

A shift to a set of flags means subclasses need to decide if they pass through the flags, or modify them in some way, or present their own flags or booleans representing a restricted subset of the superclass' flags.

File: server/src/main/java/org/elasticsearch/common/util/ArrayUtils.java [hunk 4]
```diff
@@ -77,12 +78,41 @@ public static <T> T[] concat(T[] one, T[] other) {
...
+     * Append a value to an array, if it's not already present
+     *
+     * @param array the original array
+     * @param mustInclude the value to add if not present
+     * @return the original array if it included the specified value, or a copy of it with the element added if not
+     * @param <T> type of the array elements
+     */
+    public static <T> T[] including(T[] array, T mustInclude) {
+        return contains(array, mustInclude) ? array : append(array, mustInclude);
+    }
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/common/util/ArrayUtils.java:114]: Maybe there's already utils for doing this kind of thing?

File: server/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointSyncAction.java [hunk 5]
```diff
@@ -63,8 +63,7 @@ public GlobalCheckpointSyncAction(
             Request::new,
             Request::new,
             threadPool.executor(ThreadPool.Names.WRITE),
-            false,
-            true
+            ActionFlags.ForceExecutionOnPrimary
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointSyncAction.java:66]: readability is improved IMO

File: server/src/main/java/org/elasticsearch/common/util/ArrayUtils.java [hunk 6]
```diff
@@ -77,12 +78,41 @@ public static <T> T[] concat(T[] one, T[] other) {
      */
     public static <T> T[] append(T[] array, T added) {
         @SuppressWarnings("unchecked")
-        final T[] updated = (T[]) Array.newInstance(added.getClass(), array.length + 1);
+        final T[] updated = (T[]) Array.newInstance(array.getClass().getComponentType(), array.length + 1);
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/common/util/ArrayUtils.java:81]: allows appending null

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 7]
```diff
@@ -89,6 +90,21 @@ public abstract class TransportReplicationAction<
...
+         */
+        ForceExecutionOnPrimary,
+        /**
+         * Sync the global checkpoint to the replicas after the action completes successfully
+         */
+        SyncGlobalCheckpointAfterOperation,
+        /**
+         * Prevent the replica action being rejected by the circuit breakers if the primary action succeeded
+         */
+        BypassCircuitBreakerOnReplica
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:105]: Not entirely sold on the name here. "bypass" could be interpreted as don't add to the circuit breaker at all, when it actually means add, but don't fail here. Happy for any suggestion of a better name.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java (hunk 1 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:160]: I think it helps to show intention that there are some set of action flags, but it hides which flags exactly. Now there are 2 different places to look at. Also missing flag interprets as a false, but it might be a bug.

Personally, I find bare booleans in constructors/methods hard to read, need intellij support with inline hints (maybe github webui will them soon and it's no longer my problem :). I would prefer simple enums, also helps with static analysis. It does not take much space for enum, cant see any drawbacks.

```java
enum BypassCircuitBreakerOnReplica { Yes, No }
```

I dont even think all flags needs to be grouped by single enum. Other than they all booleans that change behaviour nothing in common. May be a single class that holds enums to reduce files clutter.

Comment (nicktindall) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:160]: My thinking was that the flags are deviations from the default (that's usually how they end up being added, and certainly the case for the one I added) so the absence of the flag just means "do the sensible default" or "do what it's always done".
Some advantages of this over having enums to replace the booleans
- don't have to specify them if you're happy with the default (I think that's a good thing)
- easy to add additional ones without going back to edit all the call sites
- don't need to define a bunch of boolean-proxy enums
- you can have defaults (we could do this by overloading the constructor but it's not as flexible and more verbose)

I think your suggestion makes more sense if there were no sensible default, and we wanted the caller to make that decision each time. But things like "bypass some safety check" (e.g. `ForceExecutionOnPrimary` and `BypassCircuitBreakerOnReplica`) don't fall into that category IMO.

But happy to go with consensus here. Ideally just want to avoid `true, false, true...`

Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:160]: Are these flags indicate non-default behaviour? For example `TransportReplicationAction` and `GlobalCheckpointSyncAction` set `syncGlobalCheckpointAfterOperation` to `false`; and `TransportWriteAction` to `true`. Hard to tell what is default value, these are 2 different use cases. If these are truly 2 different use-cases and there is no default value I would prefer statically correct code, for example factory method that always set this flag to true or false. If it compiles it is correct. Or enums with assertions.

Comment (nicktindall) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:160]: I took the values used in the constructor that omits those flags to be the "default":

https://github.com/elastic/elasticsearch/blob/d8ff99748b5f2e7e27cc99a71578ffdca92bebb3/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L131-L159

That constructor is used by the majority of direct descendants and it sets `syncGlobalCheckpointAfterOperation=false` and `forceExecutionOnPrimary=false`.

If you look back in history you can see these flags being added to the second constructor with the defaults/status quo behaviour added to the first constructor

`syncGlobalCheckpointAfterOperation`: f35d1de502a5c90384b0af5b2e9bb41d23041063
`forceExecutionOnPrimary`: c29cebb04deed28f2fd9f92e449450bd55b6369d

I think a builder is a good approach when there's a proliferation of constructor args, but because this is an abstract parent class, the only way to apply that pattern would be as a fluent-style parameters DTO passed to the parent class. Which seems like a significant refactor and one I'd probably not reach for just yet in this case.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:160]: I think my preference here would be to change these boolean parameters into enums so that we can give the two options more specific names than just `true` and `false`. It is hard to read them at their call sites as things are today. I don't see a massive need for anything more complex than that. I would also be supportive of getting rid of the constructors which supply defaults for these parameters in favour of having each caller be explicit about the behaviour it wants. I don't see any huge advantage to hiding a couple of the 10+ parameters here, and experience shows it to be somewhat trappy.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 8]
```diff
@@ -117,6 +117,20 @@ protected enum SyncGlobalCheckpointAfterOperation {
         AttemptAfterSuccess
     }
 
+    /**
+     * Execution of the replica action
+     */
+    protected enum ReplicaActionExecution {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java:123]: Ah could we split this one out too in a separate PR, for similar reasons to #111017? That's going to reduce the noise in this PR massively.

File: server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java [hunk 9]
```diff
@@ -91,10 +91,10 @@ public RetentionLeaseSyncAction(
             RetentionLeaseSyncAction.Request::new,
             RetentionLeaseSyncAction.Request::new,
             new ManagementOnlyExecutorFunction(threadPool),
-            PrimaryActionExecution.RejectOnOverload,
+            PrimaryActionExecution.Force,
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java:94]: I don't believe this change is necessary on the `RetentionLeaseBackgroundSyncAction` because it's not a `TransportWriteAction`, and therefore `checkPrimaryLimits` (where the indexing pressure check is done) is a no-op.

Comment (nicktindall) [reply server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java:94]: I wonder if we even need to make any changes to `RetentionLeaseBackgroundSyncAction`. I don't believe its failure will have the same consequences as that of `RetentionLeaseSyncAction`.

File: docs/changelog/109414.yaml [hunk 10]
```diff
@@ -0,0 +1,6 @@
+pr: 109414
+summary: Don't trip circuit breakers for retention lease sync actions
```
Comment (nicktindall) [inline docs/changelog/109414.yaml:2]: I've broadened the PR title given the additional requirement around indexing pressure checks. If we're happy with that I'll update the changelog to be the same.

**Review by DaveCTurner — APPROVED** [review]
LGTM
