### PR TITLE
[Autoscaling] fixing random autoscaling test generation

### LINKED ISSUE #67620: [CI] TransportPutAutoscalingPolicyActionIT testUpdatePolicy failing reproducibly
This just started failing today.

**Build scan**:
https://gradle-enterprise.elastic.co/s/qbyrgkn5refj4/tests/:x-pack:plugin:autoscaling:internalClusterTest/org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT/testUpdatePolicy#1

**Repro line**:
`REPRODUCE WITH: ./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT.testUpdatePolicy" -Dtests.seed=5E99B04B51505E3B -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=America/Indiana/Tell_City -Druntime.java=11`

**Reproduces locally?**:
Yes.

**Applicable branches**:
`7.x` and `master`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT&tests.sortField=FAILED&tests.test=testUpdatePolicy&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT > testUpdatePolicy FAILED
    java.lang.IllegalArgumentException: no default nor user configured deciders for policy [dBokRDFQ] with roles [[]]
        at __randomizedtesting.SeedInfo.seed([5E99B04B51505E3B:49A8F6ED79B12432]:0)
        at org.elasticsearch.xpack.autoscaling.capacity.AutoscalingCalculateCapacityService.validate(AutoscalingCalculateCapacityService.java:56)
        at org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyAction.putAutoscalingPolicy(TransportPutAutoscalingPolicyAction.java:154)
        at org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyAction$1.execute(TransportPutAutoscalingPolicyAction.java:106)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:308)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:203)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
```

### PR DESCRIPTION
**Pull request by benwtrent**
Updates test to always have non-empty roles in autoscaling policy

Closes https://github.com/elastic/elasticsearch/issues/67620

### CODE REVIEW

File: x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/action/TransportPutAutoscalingPolicyActionIT.java [hunk 1]
```diff
@@ -42,7 +42,7 @@ public void testUpdatePolicy() {
         final AutoscalingPolicy policy = putRandomAutoscalingPolicy();
         final AutoscalingPolicy updatedPolicy = new AutoscalingPolicy(
             policy.name(),
-            new TreeSet<>(randomSubsetOf(List.of("data", "data_content", "data_hot", "data_warm", "data_cold"))),
+            new TreeSet<>(randomSubsetOf(randomIntBetween(1, 5), List.of("data", "data_content", "data_hot", "data_warm", "data_cold"))),
             mutateAutoscalingDeciders(policy.deciders())
```
Comment (benwtrent) [inline x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/action/TransportPutAutoscalingPolicyActionIT.java:46]: This `mutateAutoscalingDeciders` is:
```
public static SortedMap<String, Settings> mutateAutoscalingDeciders(final SortedMap<String, Settings> deciders) {
        if (deciders.size() == 0) {
            return randomAutoscalingDeciders();
        } else {
            // use a proper subset of the deciders
            return new TreeMap<>(
                randomSubsetOf(randomIntBetween(0, deciders.size() - 1), deciders.entrySet()).stream()
                    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue))
            );
        }
    }
```

Which seems like it could result in empty deciders. If this is OK, we can keep it.

File: x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/AutoscalingTestCase.java [hunk 2]
```diff
@@ -186,7 +186,9 @@ public static AutoscalingMetadata randomAutoscalingMetadataOfPolicyCount(final i
     }
 
     public static SortedSet<String> randomRoles() {
-        return randomSubsetOf(DiscoveryNode.getPossibleRoleNames()).stream().collect(Sets.toUnmodifiableSortedSet());
+        return randomSubsetOf(randomIntBetween(1, DiscoveryNode.getPossibleRoleNames().size() - 1), DiscoveryNode.getPossibleRoleNames())
```
Comment (henningandersen) [inline x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/AutoscalingTestCase.java:189]: I think we can/should leave this out. `randomRoles` is used in a number of tests and the empty set of roles is legal for many of those. The other change should be enough to fix this I think?

File: x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/action/TransportPutAutoscalingPolicyActionIT.java (hunk 1 above)
Comment (henningandersen) [reply x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/action/TransportPutAutoscalingPolicyActionIT.java:46]: Yes, the empty list of deciders is fine for all the data tiers. So with your change one line up, this will be OK.

**Review by henningandersen — APPROVED** [review]
LGTM. Thanks for fixing this @benwtrent

**Comment by mark-vieira** [comment]
@benwtrent I muted this test as part of https://github.com/elastic/elasticsearch/issues/67620 so you might want to update this branch from the latest changes on `master` and unmute.

File: x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/AutoscalingTestCase.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/AutoscalingTestCase.java]: yeah, this works, I ran it locally 1000s of times and it never failed again.
