### PR TITLE
Fix VectorScorerOSQBenchmarkTests data generation flakiness

### LINKED ISSUE #142881: [CI] VectorScorerOSQBenchmarkTests testSingleScalarVsVectorized {p0=1024 p1=1 p2=NIO p3=DOT_PRODUCT} failing
**Build Scans:**
- [elasticsearch-intake #34885 / part1](https://gradle-enterprise.elastic.co/s/ybwtk76wyekvy)
- [elasticsearch-pull-request #121706 / part-1](https://gradle-enterprise.elastic.co/s/2hjzib36jwnog)

**Reproduction Line:**
```
./gradlew ":benchmarks:test" --tests "org.elasticsearch.benchmark.vector.scorer.VectorScorerOSQBenchmarkTests.testSingleScalarVsVectorized {p0=1024 p1=1 p2=NIO p3=DOT_PRODUCT}" -Dtests.seed=FDBBE54D76A7E1AB -Dtests.locale=my-MM -Dtests.timezone=Asia/Jakarta -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.benchmark.vector.scorer.VectorScorerOSQBenchmarkTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSingleScalarVsVectorized%20%7Bp0%3D1024%20p1%3D1%20p2%3DNIO%20p3%3DDOT_PRODUCT%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: single scoring, scalar VS vectorized: arrays first differed at element [226]; <2.181590e-03> and <1.884073e-03> differed by <7.935762e-05> (more than 10.000000%)
```

**Issue Reasons:**
- [main] 2 failures in test testSingleScalarVsVectorized {p0=1024 p1=1 p2=NIO p3=DOT_PRODUCT} (0.3% fail rate in 782 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
## Summary

- The scalar and vectorized benchmark tests generated input data independently using the same `Random` seed. SIMD reduction order changes across JIT compilation tiers (e.g., `reduceLanes(ADD)` switching from sequential to pairwise reduction) caused the quantized data to diverge slightly between the two `setup()` calls, leading to >10% score differences on certain seeds.
- Extracted data generation into a static `generateBenchmarkData()` method returning a `BenchmarkData` record. Both test benchmarks now share the same record, ensuring identical input data.
- Added an offset-accepting overload of `writeBulkOSQVectorData` to avoid array copies when writing slices of the flat index vector array.

Fixes #142881
Fixes #142883

## Test plan

- [x] Verified the previously failing seeds now pass: `E503FB0D7B878481` (p0=384 p1=4 NIO COSINE) and `FDBBE54D76A7E1AB` (p0=1024 p1=1 NIO DOT_PRODUCT)
- [x] Full `VectorScorerOSQBenchmarkTests` suite passes with `--tests.iters=3`
- [x] `ESNextOSQVectorsScorerTests` (existing caller of `writeBulkOSQVectorData`) still passes

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: benchmarks/src/main/java/org/elasticsearch/benchmark/vector/scorer/VectorScorerOSQBenchmark.java [hunk 1]
```diff
@@ -109,49 +106,69 @@ public enum VectorImplementation {
     float[] scratchScores;
     float[] corrections;
 
-    @Setup
-    public void setup() throws IOException {
-        setup(new Random(123));
-    }
+    record BenchmarkData(
```
Comment (thecoop) [inline benchmarks/src/main/java/org/elasticsearch/benchmark/vector/scorer/VectorScorerOSQBenchmark.java]: In other benchmarks I've used `VectorData` (`VectorScorerFloatBenchmark`) - could we use the same names & patterns for consistency?

Comment (ldematte) [reply benchmarks/src/main/java/org/elasticsearch/benchmark/vector/scorer/VectorScorerOSQBenchmark.java]: Good to know, I'll update the name

**Review by thecoop — APPROVED** [review]
