### PR TITLE
[ML] Anomaly detection jobs should allow missing values for geo fields

### LINKED ISSUE #57299: [ML] lat_long should be more tolerant to missing data
Reported in 7.6 (and would exist earlier).

With a `lat_long` detector, if the `field_name` value is missing, the datafeed stops and the job closes. The following error is reported `Datafeed is encountering errors extracting data: Unexpected values for a geo_point field: []`.

This could occur on the first bucket, or part way through the job, depending on the timestamp of the doc (or docs) with the missing geo value.

Other anomaly detector functions e.g. `sum(bytes)` are tolerant of missing values. Therefore we should also be tolerant of missing values for `geo_point` and `geo_shape`.

To workaround, use `exists: geo.field_name` on the datafeed query for `lat_long` functions.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Allows geo fields (`geo_point`, `geo_shape`) to have missing values.
Fixes a bug where such missing values would result in an error.

Closes #57299

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]
👍 

🔥🐛🔥

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/extractor/GeoPointField.java [hunk 1]
```diff
@@ -24,9 +24,13 @@ public GeoPointField(String name) {
     @Override
     public Object[] value(SearchHit hit) {
         Object[] value = super.value(hit);
-        if (value.length != 1) {
+        if (value.length == 0) {
+            return new Object[0];
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/extractor/GeoPointField.java:28]: Theoretically it would save a memory allocation and garbage collection to just `return value;`.  Maybe Hotspot will optimise this in practice.

Same in the other file.
