### PR TITLE
[Tests] Fix expectations around shouldPreFilterSearchShards

### LINKED ISSUE #55514: [CI] TransportSearchActionTests.testShouldPreFilterSearchShards reproducibly fails
Test fails in master and 7.x and it can be reproduce with:

```
./gradlew ':server:test' --tests "org.elasticsearch.action.search.TransportSearchActionTests.testShouldPreFilterSearchShards"   -Dtests.seed=33D262E15B85701F   -Dtests.security.manager=true   -Dtests.locale=ar-KW   -Dtests.timezone=America/Antigua   -Dcompiler.java=14
```

The error is:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([33D262E15B85701F:8A479305E4B1685F]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.action.search.TransportSearchActionTests.testShouldPreFilterSearchShards(TransportSearchActionTests.java:867)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)

```

https://gradle-enterprise.elastic.co/s/rrrd56hjrxqju

### PR DESCRIPTION
**Pull request by cbuescher**
In the documentation of `pre_filter_shard_size` we state that the pre-filter
phase will be executed if the request targets more than 128 shards, yet in the
current test randomization we check that the
TransportSearchAction.shouldPreFilterSearchShards is true already for 127
targeted shards. This should be raised to 129 instead.

Closes #55514

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java [hunk 1]
```diff
@@ -856,17 +855,17 @@ public void testShouldPreFilterSearchShards() {
...
         }
         {
             SearchRequest searchRequest = new SearchRequest()
                 .source(new SearchSourceBuilder().query(QueryBuilders.rangeQuery("timestamp")));
             assertFalse(TransportSearchAction.shouldPreFilterSearchShards(clusterState, searchRequest,
-                indices, randomIntBetween(2, 127)));
+                indices, randomIntBetween(2, 128)));
             assertTrue(TransportSearchAction.shouldPreFilterSearchShards(clusterState, searchRequest,
-                indices, randomIntBetween(127, 10000)));
+                indices, randomIntBetween(129, 10000)));
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java:868]: I'm not exactly sure whether this should be 129 or 128, the way I read the docs I would understand them to _not_ run pre-filter phase if <=128, but I might be wrong here. Please let me know what you think is right.

**Review by jimczi — COMMENTED** [review]
LGTM,  thanks @cbuescher !

File: server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java (hunk 1 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java:868]: looking at the code it would seem 129, but I would try to run the test with a static value just to be 200% sure.

Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java:868]: That I already did, I was just wondering what the expectations are of the code should be changed to "<=" in the appropriate place. Thanks.
