### PR TITLE
ESQL: create a Vector when needed for IN

### LINKED ISSUE #99347: [CI] org.elasticsearch.xpack.esql.CsvTests > test {string.In3VLWithNull} FAILED
### CI Link

https://gradle-enterprise.elastic.co/s/ulahz7lg2xmtq/console-log?task=:x-pack:plugin:esql:test

### Repro line

./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {string.In3VLWithNull}" -Dtests.seed=5B78DAC3CF0ABB27 -Dtests.locale=sr-BA -Dtests.timezone=Asia/Bangkok -Druntime.java=20	

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

N/A

### Failure excerpt

Sorry for the bare-hands failure report, HOMER isn't working for me right now.

```
org.elasticsearch.xpack.esql.CsvTests > classMethod FAILED	
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=428, name=elasticsearch[CsvTests][esql][T#2], state=RUNNABLE, group=TGRP-CsvTests]	
        Caused by:	
        java.lang.AssertionError	
            at __randomizedtesting.SeedInfo.seed([5B78DAC3CF0ABB27]:0)	
            at org.elasticsearch.compute.data.AbstractBlock.<init>(AbstractBlock.java:42)	
            at org.elasticsearch.compute.data.AbstractArrayBlock.<init>(AbstractArrayBlock.java:30)	
            at org.elasticsearch.compute.data.BooleanArrayBlock.<init>(BooleanArrayBlock.java:23)	
            at org.elasticsearch.xpack.esql.evaluator.predicate.operator.comparison.InMapper$InExpressionEvaluator.evalWithNulls(InMapper.java:109)	
            at org.elasticsearch.xpack.esql.evaluator.predicate.operator.comparison.InMapper$InExpressionEvaluator.eval(InMapper.java:71)	
            at org.elasticsearch.compute.operator.EvalOperator.process(EvalOperator.java:42)	
            at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:67)	
            at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:163)	
            at org.elasticsearch.compute.operator.Driver.run(Driver.java:115)	
            at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:259)	
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)	
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)	
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
            at java.base/java.lang.Thread.run(Thread.java:1623)	
```

### PR DESCRIPTION
**Pull request by astefan**
Partially fixes https://github.com/elastic/elasticsearch/issues/99347

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/evaluator/predicate/operator/comparison/InMapper.java [hunk 1]
```diff
@@ -106,7 +106,12 @@ private static Block evalWithNulls(boolean[] values, BitSet nulls, boolean nullI
                         nulls.set(i);
                     } // else: leave nulls as is
                 }
-                return new BooleanArrayBlock(values, values.length, null, nulls, Block.MvOrdering.UNORDERED);
+                if (nulls.isEmpty()) {
+                    // see https://github.com/elastic/elasticsearch/issues/99347
+                    return new BooleanArrayVector(values, values.length).asBlock();
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/evaluator/predicate/operator/comparison/InMapper.java:111]: I think it's worth adding a test case that reproduces this one every time. And probably explaining why we want this statement rather than a link to the bug. It takes a bit of digging to reverse the sequence of events from the bug but it's fast to read a one liner like "no nulls, it's all true." Actually, do we only get here if everything is `true`? Maybe we should just return a constant block in that case?

**Review by ChrisHegarty — COMMENTED** [review]
LGTM
