### PR TITLE
Fix unmapped_type creation for indices created in 2.x 

### LINKED ISSUE #26162: Index created on 2.x causing "unsupported_operation_exception" in 5.x when used for sorting
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.0

**Plugins installed**: []

**JVM version** (`java -version`): Java 8 u131

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

## Create index in 2.x (I used 2.3.4)

```
DELETE test1
DELETE test2

PUT test1
{
  "mappings": {
    "_default_": {
      "properties": {
        "testfield": {
          "type": "string", "index": "not_analyzed"
        }
      }
    }
  }
}

PUT test2
{
  "mappings": {
    "_default_": {
      "properties": {
        "testfield": {
          "type": "string", "index": "not_analyzed"
        }
      }
    }
  }
}

POST test1/test
{
  "testfield": "my test"
}

# Don't index anything into test2

POST test*/_search
{
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "testfield": {
        "order": "asc",
        "unmapped_type": "string"
      }
    }
  ]
}
```

## Upgrade to 5.x (I used 5.5.0)

The query above, now results in: (Also if I change to "unmapped_type": "keyword")

```
{
  "took": 19,
  "timed_out": false,
  "_shards": {
    "total": 10,
    "successful": 5,
    "failed": 5,
    "failures": [
      {
        "shard": 0,
        "index": "test2",
        "node": "JBHJ1HPYQbKMOxJ1hSotrw",
        "reason": {
          "type": "unsupported_operation_exception",
          "reason": null
        }
      }
    ]
  },
  "hits": {
    "total": 1,
    "max_score": null,
    "hits": [
      {
        "_index": "test1",
        "_type": "test",
        "_id": "AV3Qh0G3rdu9hzgAfZn2",
        "_score": null,
        "_source": {
          "testfield": "my test"
        },
        "sort": [
          "my test"
        ]
      }
    ]
  }
}
```
and is producing this stack trace:

```
[2017-08-11T11:13:16,153][DEBUG][o.e.a.s.TransportSearchAction] [JBHJ1HP] [test2][0], node[JBHJ1HPYQbKMOxJ1hSotrw], [P], s[STARTED], a[id=OCMZA_bHTA-cdS6nEHIBgA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test*], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "match_all" : {
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "testfield" : {
        "order" : "asc",
        "unmapped_type" : "keyword"
      }
    }
  ]
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [JBHJ1HP][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_131]
	at org.elasticsearch.index.mapper.KeywordFieldMapper$TypeParser.parse(KeywordFieldMapper.java:152) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.index.mapper.MapperService.unmappedFieldType(MapperService.java:727) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:260) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:253) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-08-11T11:13:16,155][DEBUG][o.e.a.s.TransportSearchAction] [JBHJ1HP] [test2][2], node[JBHJ1HPYQbKMOxJ1hSotrw], [P], s[STARTED], a[id=kkIHhfYIRf6vXlBlebIpgg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test*], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "match_all" : {
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "testfield" : {
        "order" : "asc",
        "unmapped_type" : "keyword"
      }
    }
  ]
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [JBHJ1HP][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_131]
	at org.elasticsearch.index.mapper.KeywordFieldMapper$TypeParser.parse(KeywordFieldMapper.java:152) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.index.mapper.MapperService.unmappedFieldType(MapperService.java:727) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:260) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:253) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-08-11T11:13:16,157][DEBUG][o.e.a.s.TransportSearchAction] [JBHJ1HP] [test2][3], node[JBHJ1HPYQbKMOxJ1hSotrw], [P], s[STARTED], a[id=GyLowxvgSeO8ZabUK13b4g]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test*], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "match_all" : {
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "testfield" : {
        "order" : "asc",
        "unmapped_type" : "keyword"
      }
    }
  ]
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [JBHJ1HP][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_131]
	at org.elasticsearch.index.mapper.KeywordFieldMapper$TypeParser.parse(KeywordFieldMapper.java:152) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.index.mapper.MapperService.unmappedFieldType(MapperService.java:727) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:260) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:253) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-08-11T11:13:16,161][DEBUG][o.e.a.s.TransportSearchAction] [JBHJ1HP] [test2][1], node[JBHJ1HPYQbKMOxJ1hSotrw], [P], s[STARTED], a[id=WEeR_WDhSW-Uxkys3ChfQg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test*], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "match_all" : {
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "testfield" : {
        "order" : "asc",
        "unmapped_type" : "keyword"
      }
    }
  ]
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [JBHJ1HP][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_131]
	at org.elasticsearch.index.mapper.KeywordFieldMapper$TypeParser.parse(KeywordFieldMapper.java:152) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.index.mapper.MapperService.unmappedFieldType(MapperService.java:727) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:260) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:253) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-08-11T11:13:16,167][DEBUG][o.e.a.s.TransportSearchAction] [JBHJ1HP] [test2][4], node[JBHJ1HPYQbKMOxJ1hSotrw], [P], s[STARTED], a[id=ka-M_4BJStSmPorrvv2_Cw]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test*], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "match_all" : {
      "boost" : 1.0
    }
  },
  "sort" : [
    {
      "testfield" : {
        "order" : "asc",
        "unmapped_type" : "keyword"
      }
    }
  ]
}}]
org.elasticsearch.transport.RemoteTransportException: [JBHJ1HP][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209) ~[?:1.8.0_131]
	at org.elasticsearch.index.mapper.KeywordFieldMapper$TypeParser.parse(KeywordFieldMapper.java:152) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.index.mapper.MapperService.unmappedFieldType(MapperService.java:727) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:260) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:253) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0.jar:5.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

As soon as I index a doc in `test2`, the error goes away and the query is working:

```
POST test2/test
{
  "testfield": "my test"
}

POST test*/_search
{
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "testfield": {
        "order": "asc",
        "unmapped_type": "keyword"
      }
    }
  ]
}
``` 
now results in:

```
{
  "took": 8,
  "timed_out": false,
  "_shards": {
    "total": 10,
    "successful": 10,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": null,
    "hits": [
      {
        "_index": "test1",
        "_type": "test",
        "_id": "AV3Qh0G3rdu9hzgAfZn2",
        "_score": null,
        "_source": {
          "testfield": "my test"
        },
        "sort": [
          "my test"
        ]
      },
      {
        "_index": "test2",
        "_type": "test",
        "_id": "AV3Qku9k6j_T2EVH4QtG",
        "_score": null,
        "_source": {
          "testfield": "my test"
        },
        "sort": [
          "my test"
        ]
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by jimczi**
Setting unmapped_type to `keyword` to sort an index created in 2.x throws an UnsupportedOperationException.

Fixes #26162

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortIT.java [hunk 1]
```diff
@@ -857,7 +860,9 @@ public void testSortMissingStrings() throws IOException {
     }
 
     public void testIgnoreUnmapped() throws Exception {
-        createIndex("test");
+        Version version = VersionUtils.randomVersionBetween(random(), Version.V_2_0_0, Version.CURRENT);
+        prepareCreate("test")
+            .setSettings(Settings.builder().put(indexSettings()).put("index.version.created", version).build()).get();
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/search/sort/FieldSortIT.java]: Can you duplicate this test into one that tests 2.x indices and the other one that tests 5.x indices so that we have 100% coverage with every test run?

File: core/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 2]
```diff
@@ -165,7 +167,9 @@ public void testMappingDepthExceedsLimit() throws Throwable {
     }
 
     public void testUnmappedFieldType() {
-        MapperService mapperService = createIndex("index").mapperService();
+        Version version = VersionUtils.randomVersionBetween(random(), Version.V_2_0_0, Version.CURRENT);
+        MapperService mapperService =
+            createIndex("index", Settings.builder().put("index.version.created", version).build()).mapperService();
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java]: same comment here as for FieldSortIT

**Review by jpountz — APPROVED** [review]
I left a comment about testing but the change LGTM.

File: core/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 3]
```diff
@@ -724,7 +724,7 @@ public MappedFieldType unmappedFieldType(String type) {
             if (typeParser == null) {
                 throw new IllegalArgumentException("No mapper found for type [" + type + "]");
             }
-            final Mapper.Builder<?, ?> builder = typeParser.parse("__anonymous_" + type, emptyMap(), parserContext);
+            final Mapper.Builder<?, ?> builder = typeParser.parse("__anonymous_" + type, new HashMap<>(), parserContext);
```
Comment (archanid) [inline core/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: @jimczi Can you explain how this fixes the issue? Just curious.

**Comment by jimczi** [comment]
The `emptyMap` is immutable and the `typeParser` automatically adds entries to the provided map:
https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L152
The fix is to use a mutable map
