### PR TITLE
Fixes query_string query equals timezone check

### LINKED ISSUE #29403: QueryStringQueryBuilder equals == true when query is not equal
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.3

**Plugins installed**: [] D.N.A.

**JVM version** (`java -version`): openjdk version "1.8.0_161"

**OS version** (`uname -a` if on a Unix-like system): Linux jecstar-laptop 4.15.13-300.fc27.x86_64 #1 SMP Mon Mar 26 19:06:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: The doEquals() method in the org.elasticsearch.index.query.QueryStringQueryBuilder is not working properly. When two different instances with different queries are compared by the equals method everything works as expected (equals() == false). 
When adding an equal timezone id to both instances of the QueryStringQueryBuilder, the equals() method will return true despite the query values are not equal. This is caused because parenthesis are missing around the statement at line 928. 

**Steps to reproduce**:
For a complete example see the attached gradle project.
[querystringquerybug.tar.gz](https://github.com/elastic/elasticsearch/files/1881442/querystringquerybug.tar.gz)
 

**Provide logs (if relevant)**: D.N.A.

### PR DESCRIPTION
**Pull request by colings86**
This change fixes a bug where two `QueryStringQueryBuilder`s were found
to be equal if they had the same timezone set even if the query string
in the builders were different

Closes #29403

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java [hunk 1]
```diff
@@ -885,7 +885,7 @@ protected boolean doEquals(QueryStringQueryBuilder other) {
                 Objects.equals(rewrite, other.rewrite) &&
                 Objects.equals(minimumShouldMatch, other.minimumShouldMatch) &&
                 Objects.equals(lenient, other.lenient) &&
-                timeZone == null ? other.timeZone == null : other.timeZone != null &&
+                (timeZone == null ? other.timeZone == null : other.timeZone != null) &&
                 Objects.equals(timeZone.getID(), other.timeZone.getID()) &&
```
[the remark this answers is not in the document]
Comment (colings86) [reply server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: Yeah, I boticed this when testing and have pushed a fix for it

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java [hunk 2]
```diff
@@ -884,9 +899,9 @@ protected boolean doEquals(QueryStringQueryBuilder other) {
                 Objects.equals(tieBreaker, other.tieBreaker) &&
                 Objects.equals(rewrite, other.rewrite) &&
                 Objects.equals(minimumShouldMatch, other.minimumShouldMatch) &&
-                Objects.equals(lenient, other.lenient) &&
-                timeZone == null ? other.timeZone == null : other.timeZone != null &&
-                Objects.equals(timeZone.getID(), other.timeZone.getID()) &&
+                Objects.equals(lenient, other.lenient) && 
+                (timeZone == null ? other.timeZone == null
+                        : (other.timeZone != null && Objects.equals(timeZone.getID(), other.timeZone.getID()))) &&
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: nit: I find equals impls easier to read when they are symetric, eg. something like this should be correct?
```
Objects.equals(
    timeZone == null ? null : timeZone.getID(),
    other.timeZone == null ? null : otherTimeZone.getID())`

**Review by jpountz — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java [hunk 3]
```diff
@@ -884,9 +899,10 @@ protected boolean doEquals(QueryStringQueryBuilder other) {
                 Objects.equals(tieBreaker, other.tieBreaker) &&
                 Objects.equals(rewrite, other.rewrite) &&
                 Objects.equals(minimumShouldMatch, other.minimumShouldMatch) &&
-                Objects.equals(lenient, other.lenient) &&
-                timeZone == null ? other.timeZone == null : other.timeZone != null &&
-                Objects.equals(timeZone.getID(), other.timeZone.getID()) &&
+                Objects.equals(lenient, other.lenient) && 
+                Objects.equals(
+                        timeZone == null ? null : timeZone.getID(), 
+                        other.timeZone == null ? null : other.timeZone.getID()) &&
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: +1

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by colings86** [comment]
merged to master, will wait for master intake to catch up and pass before I backport to 6.x

**Comment by colings86** [comment]
Backported to the 6.x branch
