### PR TITLE
ESQL: Improve agg verification

### LINKED ISSUE #99751: ESQL: NPE when aggregating on literals
### Elasticsearch Version

main@b6747b48ba0901a530ba51375e3576fdb8df8527

### Installed Plugins

_No response_

### Java Version

openjdk version "17.0.8" 2023-07-18

### OS Version

Ubuntu 23.04

### Problem Description

`row a = 1 | stats max(1) by a` (or some other agg) results in:
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
	at java.base/java.util.List.of(List.java:812)
	at org.elasticsearch.xpack.esql.planner.AbstractPhysicalOperationProviders.aggregatesToFactory(AbstractPhysicalOperationProviders.java:185)
	at org.elasticsearch.xpack.esql.planner.AbstractPhysicalOperationProviders.groupingPhysicalOperation(AbstractPhysicalOperationProviders.java:133)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planAggregation(LocalExecutionPlanner.java:207)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:158)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planAggregation(LocalExecutionPlanner.java:207)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:158)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLimit(LocalExecutionPlanner.java:520)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:176)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:259)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:198)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:147)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:204)
	... 147 more
```

@nik9000 's thoughts on this: `I think this is just a kind of special case of "I can't EVAL in STATS". But it's a case the parser accepts.`

### Steps to Reproduce

Run the ESQL query from above.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by alex-spies**
~~Fixes #99751.~~ Update: fix for #99751 is already contained in #99602. I'm keeping this PR open for additional verification improvements, though.

When verifying aggregation expressions like `from employees | stats percentile(salary_change, 25*2)`, both arguments are treated the same way during verification. This is incorrect, as `salary_change` is the actual aggregation's field, while `25*2` is merely it's (first and only) parameter. This is overly restrictive.

Apply the current verification only to the aggregation's actual field, as the parameter is already verified during type resolution (it needs to be a constant expression).

### CODE REVIEW

**Comment by alex-spies** [comment]
This might need to be (adapted and) merged after #99602 since support for `count(*)` may need to be accounted for in the verifier that is updated in this PR.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/AbstractPhysicalOperationProviders.java [hunk 1]
```diff
@@ -261,7 +261,6 @@ private void aggregatesToFactory(
                             }
                             sourceAttr = List.of(attr);
                         }
-
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/AbstractPhysicalOperationProviders.java:264]: This can be reverted, I assume it was unintentional.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 2]
```diff
@@ -125,24 +125,24 @@ else if (p.resolved()) {
...
-                                        "aggregate function's parameters must be an attribute or literal; found ["
-                                            + a.sourceText()
-                                            + "] of type ["
-                                            + a.nodeName()
-                                            + "]"
-                                    )
-                                );
-                            }
-                        });
+                        Expression field = aggFunc.field();
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:128]: This leaves the non-field argument verification to each AggregateFunction in part. There are so far just two of these that require an extra param: `CountDistinct` and `Percentile`. I think there's no language restriction that these extra parameters cannot be a some sort of a field and this PR removes that check. However, both of these currently do expect a literal. So I guess relaxing this verifier check is OK.
However, there's a bug in `CountDistinct`, its type resolution not checking if the 2nd parameter is foldable, but then trying to fold it. This check was guarding against that, but with this change we should also fix that -- up to you if you want to do it here or subsequent PR.

**Review by bpintea — APPROVED** [review]
LGTM, maybe add one more test with a different function than add.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:128]: That's a good observation. I'll make sure the type resolution in `CountDistinct` is fixed and checked by tests.

**Comment by alex-spies** [comment]
@bpintea , I took care of the type resolution bug in `count_distinct`. Would you like to take another look?

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java [hunk 3]
```diff
@@ -50,6 +50,14 @@ public boolean resolved() {
...
         }
 
+        public TypeResolution and(TypeResolution other) {
+            if (this.failed == false) {
+                return other;
+            } else {
+                return this;
+            }
+        }
+
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java:60]: `return failed ? this : other`

It's nice but I wonder if there's any value of having such a short method in.

**Review by costin — APPROVED** [review]
lgtm

**Comment by costin** [comment]
Likely this has to go in 8.11 as well.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java:60]: I also find the suggestion more readable. 
But also value in the method, otherwise chaining is more verbose, the caller having to check the failure state at every step.

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by alex-spies** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1
