### PR TITLE
Fix Leaking Http Channel Objects when Http Client Stats are Disabled

### LINKED ISSUE #76183: Strange garbage collector behavior after upgrade from 7.10.2 (OSS) to 7.13.2
Hello!

On July 7, I upgraded several clusters from 7.10.2 (OSS) to 7.13.2.
At first it seemed that everything went well. However, later, errors began to pour. (not enough memory). At the same time, neither the load on the cluster, nor the application software changed. 

> {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [6188306006/5.7gb], which is larger than the limit of [6120328396/5.6gb], real usage: [6188305856/5.7gb], new bytes reserved: [150/150b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=150/150b, model_inference=0/0b, accounting=0/0b]
....
> 
Monitoring has shown that the "old" is constantly growing. 

GS1s

The strangest thing is that the heap grows most actively on the dedicated master server (red line). All traffic to the cluster goes only through this master server. This is done preferentially, since this is a test north and it’s easier to sort out problems by traffic. But, there is nothing to take up so much space. In our queries, there is not even aggregation, it only routes traffic to data nodes. 

I did a heap dump and it was over 6GB. VisualVM showed it to take up the most space:  transport.CopyBytesSocketChannel.
sizes1

And M.A.T. swore at x-pack.....HttpTransport
mat

Then I remembered that in the beginning there were still problems. Due to an error in the request, I flooded the cluster and put the monitoring system down. It turned out a lot of pairs of sockets, and somewhere between these versions, Elastic included the collection of HTTP connection statistics. 

To prevent this situation from happening again, I disabled the collection of these statistics: 
`http.client_stats.enabled: false`

I decided to check what's there now in these statistics: 
```
curl -s  http://localhost:9200/_nodes/stats|jq '.nodes[].http'
{
  "current_open": 19811,
  "total_opened": 19811,
  "clients": []
}
{
  "current_open": 8011,
  "total_opened": 8011,
  "clients": []
}
{
  "current_open": 8572,
  "total_opened": 8572,
  "clients": []
}

```
How! The number of current connections is equal to the total number of connections. This cluster has at best 5-10 simultaneous connections. IMHO, something, somewhere is clearly not released. In any case, they should not be equal. 

It seems that only statistics output is disabled, but it is still being collected. 
mat2

P.S: The dump file remains, if you can tell me what else you can find useful from it, I will be grateful.

### PR DESCRIPTION
**Pull request by original-brownbear**
We have to remove the channel from the internal collection of channels when stats are disabled.

Closes #76183

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java [hunk 1]
```diff
@@ -246,10 +246,10 @@ protected void doStop() {
 
         try {
             CloseableChannel.closeChannels(new ArrayList<>(httpChannels), true);
+            assert httpChannels.isEmpty() : "all channels should have been closed but saw [" + httpChannels + "]";
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java:249]: I think this is ok, `CloseableChannel.closeChannels(..., true)` adds a new close listener to all the channels and I am assuming that the listeners definitely complete in the order in which they were added.

**Review by DaveCTurner — APPROVED** [review]
LGTM with a couple of nits

File: server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java:249]: Welp https://gradle-enterprise.elastic.co/s/aaolqwri242tm seems to disagree 😕

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java:249]: Unfortunately turns out this doesn't work because in case the channel is already when the listener is added it will potentially run before queued listeners. Looking into an alternative check ...

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java]: hmpf that required some extra complexity https://github.com/elastic/elasticsearch/pull/76257/commits/f4d5454f1c62371115958bf07695118990b24b59 but it may be well worth it, we shouldn't shut down the even loop before all connections have been closed to begin with I think.

File: server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java [hunk 2]
```diff
@@ -331,6 +345,13 @@ protected void onServerException(HttpServerChannel channel, Exception e) {
     protected void serverAcceptedChannel(HttpChannel httpChannel) {
         boolean addedOnThisCall = httpChannels.add(httpChannel);
         assert addedOnThisCall : "Channel should only be added to http channel set once";
+        openChannels.incrementAndGet();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java:348]: Making this depend on the lifecycle and complete `allClientsClosedListener` in multiple places seems a bit ugly, could we use a `RefCounted` with one ref for the transport and one for each open channel?

**Comment by mark-vieira** [comment]
@elasticmachine retest this please

File: server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java]: ++ fair point I pushed https://github.com/elastic/elasticsearch/pull/76257/commits/59ad20a34143e602d8ea7b41b4298d3c16659017

**Review by DaveCTurner — APPROVED** [review]
LGTM still/again

**Comment by original-brownbear** [comment]
Thanks David!
