### PR TITLE
Check lenient_expand_open after aliases have been resolved

### LINKED ISSUE #13278: Searching multiple aliases using wildcard and ignore_unavailable=true throws index closed exception
Each of my `logstash-YYYY.MM.DD` indices has a filtered alias added to it named `error_messages-YYYY.MM.DD`.  Any that are older than 30 days are closed.

I'm seeing strange behavior when trying to do a match_all query on `error_messages-*`.

This is using the Java  transport client. ES version 1.6.0.
```
SearchResponse sr = client.prepareSearch("error_messages-*")
  .setQuery(QueryBuilders.matchAllQuery())
  .execute().actionGet();
throws:
org.elasticsearch.indices.IndexClosedException: [logstash-2015.07.30] closed
```
So I set `IndicesOptions.lenientExpandOpen()` to ignore unavailable indices and got a different (but similiar) error.
```
SearchResponse sr = client.prepareSearch("error_messages-*")
  .setQuery(QueryBuilders.matchAllQuery())
  .setIndicesOptions(IndicesOptions.lenientExpandOpen())
  .execute().actionGet();
throws:
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [FORBIDDEN/4/index closed]
```

Interestingly, this query works via HTTP API in Marvel:
```
POST error_messages-*/_search?ignore_unavailable=true
{
  "query": {
    "match_all": {}
  }
}
```

Also interesting is if I use the concrete index pattern `logstash-*`, the queries work in Java.

### PR DESCRIPTION
**Pull request by s1monw**
We fail today with ClusterBlockExceptions if an alias expands to a closed index
during search since we miss to check the index option down the road after we expanded
aliases.

Closes #13278

### CODE REVIEW

**Comment by javanna** [comment]
LGTM thanks a lot @s1monw

File: core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 1]
```diff
@@ -189,6 +189,7 @@ public IndexNameExpressionResolver(Settings settings) {
         return concreteIndices.toArray(new String[concreteIndices.size()]);
     }
 
+
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: remove added newline?

**Comment by martijnvg** [comment]
LGTM. Thanks @s1monw for fixing this.

**Comment by s1monw** [comment]
pushed to all relevant branches...

**Comment by oferbar** [comment]
Hi, is this also fixed for 1.6 or just 2.x?
Many thanks!
