### PR TITLE
Fix SearchReplicaSelectionIT failures

### LINKED ISSUE #70621: [CI] SearchReplicaSelectionIT.testNodeSelection
This happened locally, but I can see it failing in CI too.

**Build scan**:
https://gradle-enterprise.elastic.co/s/ewsio3cffibpa

**Repro line**:

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.routing.SearchReplicaSelectionIT.testNodeSelection" -Dtests.seed=B189466086BCB35A -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=America/Whitehorse -Druntime.java=13
```

**Reproduces locally?**:
Happened locally, but repro line did not reproduce locally.

**Applicable branches**:
master (though likely also 7.x)

**Failure history**:
Has failed a [few times per day](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:SearchReplicaSelectionIT),sort:!(time,desc))) since it was introduced in #70283.

**Failure excerpt**:

```
org.junit.ComparisonFailure: expected:<[oM8ifFUsRkG4AYoXVpxG8]g> but was:<[q6ccPdpJTyScxAYaTv88H]g>
        at __randomizedtesting.SeedInfo.seed([B189466086BCB35A:D85D541A5EDDFA1E]:0)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.search.routing.SearchReplicaSelectionIT.testNodeSelection(SearchReplicaSelectionIT.java:99)
```

### PR DESCRIPTION
**Pull request by jtibshirani**
This PR makes sure MockSearchService collects ARS statistics. Before, if we
randomly chose to use MockSearchService then ARS information would be missing
and the test would fail.

Also makes the following fixes:
* Removes a test workaround for the bug #71022, which is now fixed.
* Handle the case where nodes have same rank, to prevent random failures.

Closes #70621.

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/search/routing/SearchReplicaSelectionIT.java [hunk 1]
```diff
@@ -86,17 +85,13 @@ public void testNodeSelection() {
         assertNotNull(nodeStats);
         assertEquals(3, nodeStats.getAdaptiveSelectionStats().getComputedStats().size());
 
-        String bestNodeId = null;
-        double bestRank = Double.POSITIVE_INFINITY;
-        for (Map.Entry<String, ComputedNodeStats> entry : nodeStats.getAdaptiveSelectionStats().getComputedStats().entrySet()) {
-            double rank = entry.getValue().rank(1L);
```
Comment (jtibshirani) [inline server/src/internalClusterTest/java/org/elasticsearch/search/routing/SearchReplicaSelectionIT.java:92]: Before we fixed #71022, we passed in 1 for the number of outstanding requests so that this rank calculation matched the one used to select shards. Now that the bug is fixed, we need to remove the workaround.

**Review by jimczi — APPROVED** [review]
LGTM, thanks @jtibshirani
