### PR TITLE
Auto-generated HTTPs cert SAN includes publish addresses

### LINKED ISSUE #81313: Cannot enroll to nodes with publish addresses
In this scenario the initial node is started behind some IP translation, and the second, to-enroll, node has to use the initial node's published address to contact it.
Enrolling fails because the second node doesn't trust the certificate from the initial's node enroll endpoint. That certificate doesn't contain the published address in the SAN field.

In the following example the initial node runs inside a docker container, and the second node attempts to enroll from the host:
```
docker run -it -p 192.168.1.137:19300:9300 -p 192.168.1.137:19200:9200 -e "http.publish_host=192.168.1.137" -e "http.publish_port=19300" -e "transport.publish_host=192.168.1.137" -e "transport.publish_port=19200" -e "ES_JAVA_OPTS=-Xms2g -Xmx2g" elasticsearch:test
```
The generated node-enrollment token indeed contains the published address:
```
{"ver":"8.1.0","adr":["192.168.1.137:19300"], ...}
```
But enrolling the second node, from the docker host, fails with:
```
./bin/elasticsearch -v --enrollment-token eyJ2ZXIiOiI4LjEuMCIsImFkciI6WyIxOTIuMTY4LjEuMTM3OjE5MzAwIl0sImZnciI6ImRjYjMyMzkyZGU0Mzg3NGQyN2VhYThmZWM1ZDJmMmZhZjkxZDcwNTE1ZmIxZGRhNzlmNjFiZDhlMjE2YzY1ZjciLCJrZXkiOiJ4YktHZ0gwQm9jS1d0b2xRVmlQYzo0TW4zRm5FRlN1NmtjLWhKNF9XdEZRIn0=
warning: ignoring JAVA_HOME=/Users/albert/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home; using bundled JDK
warning: ignoring JAVA_HOME=/Users/albert/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home; using bundled JDK
warning: ignoring JAVA_HOME=/Users/albert/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home; using bundled JDK
Exception in thread "main" javax.net.ssl.SSLHandshakeException
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
        at org.elasticsearch.xpack.core.common.socket.SocketAccess.lambda$doPrivileged$0(SocketAccess.java:42)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:41)
        at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:178)
        at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:135)
        at org.elasticsearch.xpack.security.cli.AutoConfigureNode.execute(AutoConfigureNode.java:289)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.Command.main(Command.java:77)
        at org.elasticsearch.xpack.security.cli.AutoConfigureNode.main(AutoConfigureNode.java:144)
Caused by: java.security.cert.CertificateException
        at org.elasticsearch.xpack.core.security.CommandLineHttpClient$1.checkServerTrusted(CommandLineHttpClient.java:358)
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
        ... 24 more
```
From
```
openssl s_client -connect 192.168.1.137:19300 -showcerts 2> /dev/null | openssl x509 -text
```
I can see the published address is not in the SAN
```
 X509v3 Subject Alternative Name:
      DNS:localhost, IP Address:172.17.0.2, IP Address:127.0.0.1, DNS:3f73bd091c2d
```

@jkakavas I worked on the code that introduced this bug. Let me know if you want me to raise a fix.

### PR DESCRIPTION
**Pull request by albertzaharovits**
When ES sits behind a proxy/NAT wrt HTTP clients, the ES node admin has the option to include the IP/DNS in the ES settings in order for the node to advertise the addresses that it can be reached at, in the node info APIs (the publish addresses are not used for binding).

This PR makes the HTTPs certificates that Security auto-configuration generates to include the publish addresses in the certificate's SAN. This way, other nodes can enroll across NATed envs.

Closes https://github.com/elastic/elasticsearch/issues/81313

### CODE REVIEW

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 1]
```diff
@@ -783,14 +786,31 @@ private void deleteDirectory(Path directory) throws IOException {
...
-    private GeneralNames getSubjectAltNames() throws IOException {
+    private GeneralNames getSubjectAltNames(Settings settings) throws IOException {
         Set<GeneralName> generalNameSet = new HashSet<>();
         for (InetAddress ip : NetworkUtils.getAllAddresses()) {
             String ipString = NetworkAddress.format(ip);
             generalNameSet.add(new GeneralName(GeneralName.iPAddress, ipString));
         }
         generalNameSet.add(new GeneralName(GeneralName.dNSName, "localhost"));
+        // HOSTNAME should always be set by start-up scripts, and this code is always invoked only by the said startup scripts
         generalNameSet.add(new GeneralName(GeneralName.dNSName, System.getenv("HOSTNAME")));
```
Comment (albertzaharovits) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:797]: Not all hostnames, can be DNS names. Should we devise a regexp for DNS names? I don't think there's a problem if we include invalid DNS names in the SAN.

Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:797]: What are some examples you are thinking of ? If "cannot be DNS names" means simply that this will not be resolved by a DNS server that the host machine is configured to use then we can't know on configuration time right ?

For instance I think that `somestring` is a valid dnsName value for a SAN

https://datatracker.ietf.org/doc/html/rfc5280.html#section-4.2.1.6 says :

> When the subjectAltName extension contains a domain name system
   label, the domain name MUST be stored in the dNSName (an IA5String).
   The name MUST be in the "preferred name syntax", as specified by
   Section 3.5 of [RFC1034] and as modified by Section 2.1 of
   [RFC1123].
   
 and https://datatracker.ietf.org/doc/html/rfc1034#section-3.5 sees to allow a domain that includes a simple `<label>`
 
 I think we don't need to do anything additional here

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 2]
```diff
@@ -383,7 +386,7 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
                 transportKey = transportKeyPair.getPrivate();
                 transportCert = CertGenUtils.generateSignedCertificate(
                     certificatePrincipal,
-                    getSubjectAltNames(),
+                    null, // transport only validates certificates not the hostname
```
Comment (jkakavas) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:389]: good call. Not only these are not used for validation but will probably ( apart from the localhost related ones ) be _wrong_ for the other nodes that will get this certificate :+1:

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 3]
```diff
@@ -920,6 +940,9 @@ private static void fullyWriteFile(Path basePath, String fileName, boolean repla
         Path tmpPath = basePath.resolve(fileName + "." + UUIDs.randomBase64UUID() + ".tmp");
         try (OutputStream outputStream = Files.newOutputStream(tmpPath, StandardOpenOption.CREATE_NEW)) {
             writer.accept(outputStream);
+        }
+        // close file before moving, otherwise the windows FS throws IOException
```
Comment (jkakavas) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:944]: :old-man-shouts-at-windows:

File: x-pack/plugin/security/cli/build.gradle [hunk 4]
```diff
@@ -29,6 +29,11 @@ tasks.named("forbiddenPatterns").configure {
   exclude '**/*.jks'
 }
 
+tasks.named("test").configure {
+  environment 'HOSTNAME', 'dummy.test.hostname' // some tests rely on this being set, which it always is for the code running in main
+  systemProperty 'tests.security.manager', 'false' // the main code under test runs without the SecurityManager
```
Comment (jkakavas) [inline x-pack/plugin/security/cli/build.gradle:34]: I understand the point, did the SM cause any issue too ? ( just curious )

**Review by jkakavas — APPROVED** [review]
LGTM, thanks ! Apologies for the delay

File: x-pack/plugin/security/cli/build.gradle (hunk 4 above)
Comment (albertzaharovits) [reply x-pack/plugin/security/cli/build.gradle:34]: @jkakavas 
```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessUserInformation")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.checkWriteExtended(UnixFileAttributeViews.java:195)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:264)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:299)
	at org.elasticsearch.xpack.security.cli.AutoConfigureNode.execute(AutoConfigureNode.java:219)
```

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 1 above)
Comment (albertzaharovits) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:797]: Thanks for digging those up Ioannis!

Apologies for being vague, I was thinking that maybe `hostname` and `domain name` have different grammars, such that a `hostname` cannot be used in place of a `domain name`.
However, the internets ([networking - Valid characters of a hostname? - Stack Overflow](https://stackoverflow.com/questions/3523028/valid-characters-of-a-hostname) and [RFC 952: DoD Internet host table specification](https://www.rfc-editor.org/rfc/rfc952) ) says that the `hostname` IS a `domain name`.

**Comment by albertzaharovits** [comment]
Bwc test [Build Scan™ for 'elasticsearch' today at 2:53:16 PM EET | Gradle Enterprise](https://gradle-enterprise.elastic.co/s/mxgqpc3nyoiiw/console-log?task=:qa:mixed-cluster:v8.0.0%23mixedClusterTest) failure (now muted) tracked under: [[CI] MixedClusterClientYamlTestSuiteIT test {p0=indices.segments/10_basic/basic segments test} failing · Issue #82014 · elastic/elasticsearch](https://github.com/elastic/elasticsearch/issues/82014)

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/bwc
