### PR TITLE
Relax ShardFollowTasksExecutor validation

### LINKED ISSUE #59625: CcrRollingUpgradeIT fails on CI
This test started to fail regularly since July 14th 2020. The logs show some errors related to component templates but this should be addressed by #59624.

**Build scan**: 
https://gradle-enterprise.elastic.co/s/uxnrmjs7mcwve
https://gradle-enterprise.elastic.co/s/li64mi23adjtm
https://gradle-enterprise.elastic.co/s/uza2ofj3d32fe

**Applicable branches**: 7.x

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.upgrades.CcrRollingUpgradeIT%22'),sort:!(time,desc))

### PR DESCRIPTION
**Pull request by dnhatn**
If a primary shard of a follower index is being relocated, then we will fail to create a follow-task. This validation is too restricted. We should ensure that all primaries of the follower index are active instead.

Closes #59625

### CODE REVIEW

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTasksExecutor.java [hunk 1]
```diff
@@ -111,9 +112,10 @@ public ShardFollowTasksExecutor(Client client,
 
     @Override
     public void validate(ShardFollowTask params, ClusterState clusterState) {
-        IndexRoutingTable routingTable = clusterState.getRoutingTable().index(params.getFollowShardId().getIndex());
-        if (routingTable.shard(params.getFollowShardId().id()).primaryShard().started() == false) {
-            throw new IllegalArgumentException("Not all copies of follow shard are started");
+        final IndexRoutingTable routingTable = clusterState.getRoutingTable().index(params.getFollowShardId().getIndex());
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTasksExecutor.java:115]: I am not sure if we should remove this validation. Should we be able to create a follow task while some follower shards are temporarily unavailable?

Comment (ywelsch) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTasksExecutor.java:115]: yeah, I'm not sure either what the point of this validation is at this specific point in the code (maybe @martijnvg can help with that). It forces retry behavior upstream for "put follow" and "resume follow" to be resilient.

**Review by ywelsch — APPROVED** [review]
Let's merge this, and get some follow-up clarification on the raised points.

**Comment by dnhatn** [comment]
Thanks Yannick.
