### PR TITLE
Handling exceptions on watcher reload

### LINKED ISSUE #69842: Watcher should retry a failed reload
If for some reason watcher fails to start after being paused due to an unrelated instance (such as the master node disappearing), and the reload of the Watch fails like in the stack trace below, Watcher enters a "started" state, but actually does nothing. 

The remediation is stopping and starting watcher, however this is not ideal since the alerting system is now effectively down.  Watcher should continue to retry starting if the reload fails. This change would likely be setting some type of error state on the watch status so that the normal cluster state even would continue to retry starting. 

This is quite similar to https://github.com/elastic/elasticsearch/issues/44981 , however in that case a stop/start does not fix the issue..but in this case it does. The fix here is likely applicable to both issues. 

```
Mar 1, 2021 @ 11:15:02.084[instance-0000000017] error reloading watcher
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:67) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:50) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.loadWatches(WatcherService.java:285) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.reloadInner(WatcherService.java:235) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.lambda$reload$1(WatcherService.java:198) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService$1.doRun(WatcherService.java:408) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:232) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:54) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:65) ~[elasticsearch-7.11.1.jar:7.11.1]
	... 11 more

Mar 1, 2021 @ 11:15:01.750[instance-0000000006] error reloading watcher
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:67) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:50) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.loadWatches(WatcherService.java:285) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.reloadInner(WatcherService.java:235) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.lambda$reload$1(WatcherService.java:198) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService$1.doRun(WatcherService.java:408) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:232) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:54) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:65) ~[elasticsearch-7.11.1.jar:7.11.1]
	... 11 more

Mar 1, 2021 @ 11:14:57.072[instance-0000000017] reloading watcher, reason [new local watcher shard allocation ids], cancelled [0] queued tasks
Mar 1, 2021 @ 11:14:56.749[instance-0000000006] reloading watcher, reason [new local watcher shard allocation ids], cancelled [0] queued tasks
Mar 1, 2021 @ 11:14:44.765[instance-0000000017] paused watch execution, reason [no master node], cancelled [43] queued tasks
Mar 1, 2021 @ 11:14:44.585[instance-0000000006] paused watch execution, reason [no master node], cancelled [5] queued tasks
```

### PR DESCRIPTION
**Pull request by sakurai-youhei**
Exceptions during watcher reload, such as those during loading watches, may not start the trigger service, making the watcher stop triggering anything. Coupled with the behavior that the reload does not occur unless the routing table changes, the current exception handling can leave the watcher unfunctional for some time.

This PR improves the exception handling to allow the reload to occur again even if the routing table stays identical.

Closes #69842

### CODE REVIEW

**Comment by masseyke** [comment]
Thanks @sakurai-youhei. This seems like a good thing to do. A couple of questions though:
Do you think it would be difficult to put this into an integration test? It would be great to have one that has a failure during reload, and see that it does try again.
Also I notice that if I revert your change but leave the tests, 2 out of the 3 tests still pass. Was that intentional?

**Comment by sakurai-youhei** [comment]
@masseyke Thank you for your reviewing this PR.

[1]
> Do you think it would be difficult to put this into an integration test? It would be great to have one that has a failure during reload, and see that it does try again.

TBH, it's hard to cause the retry intentionally because it requires an exception at the part before `triggerService.start(watches)` [HERE](https://github.com/elastic/elasticsearch/pull/105442/files#diff-50b330fbae6cb904c027fe77a2119d864e78290d6a054ee530f94d4c76798345R258-R279). #69842 shows the exception was rooted in refreshing the watcher index [HERE](https://github.com/elastic/elasticsearch/blob/v7.11.1/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherService.java#L284-L285), but I don't think it's reasonably reproducible.

One way would be to make the refresh timeout, which is currently fixed in 5 seconds, configurable to reproduce the timeout easily, but I'm afraid that this kind of extra change would be an unfavorable scope extension. If you have other ideas, please let me know, and I will explore the options.

Btw, the retry is compromisely checked with RuntimeException forcibly thrown in one of the unit test cases.

[2]
> Also I notice that if I revert your change but leave the tests, 2 out of the 3 tests still pass. Was that intentional?

Yes. Those passing tests declare prerequisite behaviors causing #69842 that require a change in this PR. If either one of them changes in the future, the change introduced through this PR may also need to be reconsidered, so I included the cases.

**Comment by sakurai-youhei** [comment]
@masseyke Can I get your help to release this change? The issue #69842 harms reliability of watcher executions in some circumstances, and I want to eliminate such troubles with this PR.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java [hunk 1]
```diff
@@ -166,7 +166,9 @@ public void clusterChanged(ClusterChangedEvent event) {
             if (watcherService.validate(event.state())) {
                 previousShardRoutings.set(localAffectedShardRoutings);
                 if (state.get() == WatcherState.STARTED) {
-                    watcherService.reload(event.state(), "new local watcher shard allocation ids");
+                    watcherService.reload(event.state(), "new local watcher shard allocation ids", (exception) -> {
+                        clearAllocationIds(); // will cause reload again
```
Comment (masseyke) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java:170]: Do we need to also set the state to WatcherState.STARTING here? It's been a couple of years since i've been in here, so I'm not sure what bad things might happen if the state is STARTED but watcher is actually unavailable.

Comment (sakurai-youhei) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java:170]: @masseyke I understand the point but I don't think so. If the state changed to `STARTING` here, the watcher service would no longer be reloaded, which is the problematic state that was also reported in #44981. Since there are only four states, `STARTED` (but it's rather DEGRADED actually) would be affordable, in my opinion.

Comment (masseyke) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java:170]: OK that makes sense. And it's not going to be worse than the current situation (having it in STARTED state, but not doing anything).

**Review by masseyke — APPROVED** [review]
Looks like a good change to me.
