### PR TITLE
SQL: Fix groupings on empty results and HAVING on local relations

### LINKED ISSUE #74311: SQL: Empty result set on aggregates with filter foldable to false
`select count(*), max(languages) from test_emp where first_name = 'yoda'` retrieves
```
   count(*)    |max(languages) 
---------------+---------------
0              |null           
```

but if the condition is replaced with something that can be folded to false the result set becomes empty:
`select count(*), max(languages) from test_emp where 'vader' = 'yoda'`
```
   count(*)    |max(languages) 
---------------+---------------
```

Note, this only behaves inconsistently if no `GROUP BY` is used. If a `GROUP BY gender` is added to the queries above, both correctly return an empty result set.

### PR DESCRIPTION
**Pull request by Luegg**
Resolves #74311

The goal of this PR is to make implicit and explicit groupings behave consistently on empty result sets no matter whether the query is run on ES or optimized to a local relation. A typical example is a query like `SELECT COUNT(*) FROM test_emp WHERE languages = 2` vs `SELECT COUNT(*) FROM test_emp WHERE 1 = 2` where the later used to produce an empty result set instead of the expected 1 row with a count of 0.

The PR also fixes other edge case around contradictions in `HAVING` clauses that used to produce a wrong result: `SELECT COUNT(*) c, 'a' a HAVING COUNT(*) > 1000`

Previously:
```
       c       |       a       
---------------+---------------
1              |a              
```

Now:
```
       c       |       a       
---------------+---------------
```

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 1]
```diff
@@ -842,17 +848,47 @@ protected LogicalPlan rule(LogicalPlan p) {
...
+                // This optimization is only correct if `plan` has a LocalRelation descendant that is not filtered.
+                // Because PushDownAndCombineFilters might push down filters to become descendants of `plan`, this optimization
+                // must never run before PushDownAndCombineFilters.
+                LocalRelation relation = unfilteredLocalRelation(plan.child());
+                if (relation != null) {
+                    long count = (relation.executable() instanceof EmptyExecutable ? 0L : 1L);
+
+                    return plan.transformExpressionsDown(AggregateFunction.class, aggregateFunction -> {
+                        if (aggregateFunction instanceof Count) {
+                            return new Literal(Source.EMPTY, count, DataTypes.LONG);
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:865]: Copy the aggregateFunction source and datatype instead of `Source.EMPTY/Long` - it's the same thing but conveys the intent better.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 2]
```diff
@@ -842,17 +848,47 @@ protected LogicalPlan rule(LogicalPlan p) {
...
+                        } else if (count == 0) {
+                            return new Literal(Source.EMPTY, null, aggregateFunction.dataType());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:867]: Likely this needs to be `DataTypes.NULL` as well.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 3]
```diff
@@ -842,17 +848,47 @@ protected LogicalPlan rule(LogicalPlan p) {
...
 
         @Override
-        protected LogicalPlan rule(Aggregate a) {
-            boolean hasLocalRelation = a.anyMatch(LocalRelation.class::isInstance);
+        protected LogicalPlan rule(UnaryPlan plan) {
+            if (plan instanceof Aggregate || plan instanceof Filter) {
+                // This optimization is only correct if `plan` has a LocalRelation descendant that is not filtered.
+                // Because PushDownAndCombineFilters might push down filters to become descendants of `plan`, this optimization
+                // must never run before PushDownAndCombineFilters.
+                LocalRelation relation = unfilteredLocalRelation(plan.child());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:859]: Tight relationships between rules are typically an indicator a rule does too much. Here the count evaluation only applies in case there are no filters since they potentially affect the count.
Aren't filters folded for local relationships anyway? If that's the case this rule can only expect to be applied when the child is always a LocalRelation.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 4]
```diff
@@ -842,17 +848,47 @@ protected LogicalPlan rule(LogicalPlan p) {
...
-     * A COUNT in a local relation will always be 1.
-     */
-    private static class ReplaceCountInLocalRelation extends OptimizerRule<Aggregate> {
+    static class ReplaceAggregationsInLocalRelations extends OptimizerRule<UnaryPlan> {
 
         @Override
-        protected LogicalPlan rule(Aggregate a) {
-            boolean hasLocalRelation = a.anyMatch(LocalRelation.class::isInstance);
+        protected LogicalPlan rule(UnaryPlan plan) {
+            if (plan instanceof Aggregate || plan instanceof Filter) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:855]: What about `OrderBy`?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 5]
```diff
@@ -842,17 +848,47 @@ protected LogicalPlan rule(LogicalPlan p) {
...
+                if (relation != null) {
+                    long count = (relation.executable() instanceof EmptyExecutable ? 0L : 1L);
+
+                    return plan.transformExpressionsDown(AggregateFunction.class, aggregateFunction -> {
+                        if (aggregateFunction instanceof Count) {
+                            return new Literal(Source.EMPTY, count, DataTypes.LONG);
+                        } else if (count == 0) {
+                            return new Literal(Source.EMPTY, null, aggregateFunction.dataType());
+                        } else {
+                            // note, most aggregation functions have already been substituted by something like
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:869]: I think referring to the rule is enough to point out that no further processing is needed - indicating how the aggs are replaced is misleading (since the other rule can change or be replaced all together).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 6]
```diff
@@ -842,17 +848,47 @@ protected LogicalPlan rule(LogicalPlan p) {
...
+                        }
+                    });
+                }
+            }
 
-            return hasLocalRelation ? a.transformExpressionsDown(Count.class, c -> new Literal(c.source(), 1, c.dataType())) : a;
+            return plan;
+        }
+
+        private LocalRelation unfilteredLocalRelation(LogicalPlan plan) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:880]: See the comment above - instead of checking for the presence of a filter, simply check there's always a `LocalRelation`. That is, the filters have to be folded/elided for this to work as should be the case of any other block.
Any cases that you are thinking of?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 7]
```diff
@@ -1145,42 +1181,40 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
-                    Aggregate a = (Aggregate) projectOrAggregate;
-                    List<Object> folded = extractConstants(a.aggregates());
-
-                    boolean onlyConstantAggregations = leaf instanceof EsRelation
-                        && folded.size() == a.aggregates().size()
-                        && a.groupings().isEmpty();
-
-                    if (isNonSkippedLocalRelation || onlyConstantAggregations) {
-                        foldedValues = folded;
+                if(relation.executable() instanceof SingletonExecutable) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1195]: Bad formatting.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 8]
```diff
@@ -1145,42 +1181,40 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
+                    if(plan instanceof Project){
+                        foldedValues = extractConstants(((Project) plan).projections());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1197]: extractConstants -> extractLiterals

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 9]
```diff
@@ -1197,20 +1231,44 @@ protected LogicalPlan rule(LogicalPlan plan) {
...
-                    return values;
+                    return null;
                 }
             }
             return values;
         }
 
     }
 
+    static class SkipQueryForOnlyConstantAggregations extends OptimizerRule<Aggregate> {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1248]: Constant -> Literal

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 10]
```diff
@@ -1197,20 +1231,44 @@ protected LogicalPlan rule(LogicalPlan plan) {
...
+
+            return plan;
+        }
+
+        private boolean foldable(Expression e) {
+            if(e instanceof Alias){
+                return foldable(((Alias) e).child());
+            } else {
+                return e.foldable();
+            }
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1267]: This code is familiar - I wonder if it's somewhere else (could be moved into `Expressions`).
Small nit, if you make it a one liner you can put it directly in the if statement.
```suggestion
return (e instanceof Alias ? foldable((Alias) e).child()) : e.foldable());
```

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java [hunk 11]
```diff
@@ -195,8 +195,8 @@ public void testLocalExecWithCountAndWhereFalseFilter() {
         PhysicalPlan p = plan("SELECT COUNT(10), COUNT(DISTINCT 20) WHERE 1 = 2" + randomOrderByAndLimit(2));
         assertEquals(LocalExec.class, p.getClass());
         LocalExec le = (LocalExec) p;
-        assertEquals(EmptyExecutable.class, le.executable().getClass());
-        EmptyExecutable ee = (EmptyExecutable) le.executable();
+        assertEquals(SingletonExecutable.class, le.executable().getClass());
```
Comment (costin) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java:198]: Why did the empty executable was replaced by singleton? Was the initial test wrong?

**Review by costin — COMMENTED** [review]
Looks good overall. Since some rules were refactored, could you please annotate the PR with some comments on what moved where and why? Thanks!

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 4 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:855]: 👍 I forgot about `order by`. I think it will always be pruned in earlier optimizations for the relevant queries but will add it anyway.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:867]: Using the `NULL` type failed in SQL spec because H2 also returned the original type. I'm using `Literal.of` now which also preserves the original data type.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 6 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:880]: For queries like `SELECT COUNT(*) WHERE FALSE HAVING COUNT(*) = 0` you need to make sure that you only apply the replacement of `COUNT(*)` on unfiltered relations:

```
Having[count(*) = 0]
\ Aggregate[count(*)]
 \ Filter[false]
  \ Local[Single]
```

`Filter` needs to be pruned first which does not always happen because the foldings generally happen before the prunings.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java (hunk 11 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java:198]: yes, that's one of the cases where SQL engines return one row with an "empty" result. E.g. Postgres:
```
lukas=# SELECT COUNT(10), COUNT(DISTINCT 20) WHERE 1 = 2;
 count | count
-------+-------
     0 |     0
(1 row)
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 12]
```diff
@@ -124,14 +124,17 @@ public LogicalPlan optimize(LogicalPlan verified) {
...
+                new ReplaceAggregatesWithLiterals()
                 );
 
         Batch refs = new Batch("Replace References", Limiter.ONCE,
                 new ReplaceReferenceAttributeWithSource()
                 );
 
+        Batch pushDownFilters = new Batch("Push down filters",
+                // must happen in a batch before ReplaceAggregationsOnLocalRelations
+                new PushDownAndCombineFilters());
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:136]: I now managed to fix the orders of the rules such that `PushDownAndCombineFilters` can remain in the original batch.

My problem is that `ReplaceAggregationsInLocalRelations`, `ConstantFolding` and `PruneFilters` form a series of transformations that must be applied in this sequence before `PushDownAndCombineFilters`. If `PushDownAndCombineFilters` is applied in the middle of this sequence, it pushes down filters it shouldn't. E.g. for the query `SELECT COUNT(*) HAVING COUNT(*) = 0`:

Correct sequence:
```
Having[count(*) = 0]
\ Agg[count(*)]
 \ Local[single]
```
=Fold=>
```
Having[false]
\ Agg[1]
 \ Local[single]
```
=Prune=>
```
Local[empty]
```

Incorrect sequence:
```
Having[count(*) = 0]
\ Agg[count(*)]
 \ Local[single]
```
=Fold=>
```
Having[false]
\ Agg[1]
 \ Local[single]
```
=PushDownFilter=> // pushes down because Having does not contain an aggregation anymore
```
Agg[1]
 \ Having[false]
  \ Local[single]
```
=Prune=>
```
Agg[1]
\ Local[empty]
```

It's like `ReplaceAggregationsInLocalRelations` removes the information that we're dealing with an aggregation and the correct context is only restored with `PruneFilter`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 13]
```diff
@@ -1145,49 +1175,47 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
         return new LocalRelation(plan.source(), new EmptyExecutable(plan.output()));
     }
 
-    static class SkipQueryIfFoldingProjection extends OptimizerRule<LogicalPlan> {
-        @Override
-        protected LogicalPlan rule(LogicalPlan plan) {
-            List<LogicalPlan> leaves = plan.collectLeaves();
+    static class PushProjectionsIntoLocalRelation extends OptimizerRule<UnaryPlan> {
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1178]: I split the `SkipQueryIfFoldingProjection` transformation into `PushProjectionsIntoLocalRelation` and `SkipQueryForOnlyLiteralAggregations` because it looks like two different concerns and the combined logic becomes a bit more complicated with this PR.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 10 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1261]: Yes, there are a few places where we do the alias resolution manually but the methods that are called in the end are always a bit different. So if we would put it into `Expression` it would need to be fairly generic. Something like `T onResolved(Function<Expression, T> fn)` that could be used like `e.onResolved(Expression::foldable)`.

Alternatively, it might be possible to resolve the aliases in `fold` and `foldable`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 3 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:854]: See https://github.com/elastic/elasticsearch/pull/74809#discussion_r663859683

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 14]
```diff
@@ -842,17 +846,43 @@ protected LogicalPlan rule(LogicalPlan p) {
         }
     }
 
-    /**
-     * A COUNT in a local relation will always be 1.
-     */
-    private static class ReplaceCountInLocalRelation extends OptimizerRule<Aggregate> {
+    static class ReplaceAggregationsInLocalRelations extends OptimizerRule<UnaryPlan> {
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:849]: This is just a rename from `ReplaceCountInLocalRelation` to `ReplaceAggregationsInLocalRelations` to cover some more generic replacements.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 15]
```diff
@@ -842,17 +846,43 @@ protected LogicalPlan rule(LogicalPlan p) {
...
-            return hasLocalRelation ? a.transformExpressionsDown(Count.class, c -> new Literal(c.source(), 1, c.dataType())) : a;
+            return plan;
         }
+
+        private LocalRelation unfilteredLocalRelation(LogicalPlan plan) {
+            List<LogicalPlan> filterOrRelations = plan.collectFirstChildren(p -> p instanceof Filter || p instanceof LocalRelation);
+
+            if (filterOrRelations.size() == 1) {
+                LogicalPlan filterOrRelation = filterOrRelations.get(0);
+                if (filterOrRelation instanceof LocalRelation) {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:879]: Probably on the same idea as @costin's: you collect nodes by the condition on instance of Filter or LocalRelation. After you collect these nodes, you don't do anything in case of Filter, you only do something in case of LocalRelation. Otherwise, you return `null`. So, I don't see the reason for collecting nodes of type Filter.

Looking deeper (at what `collectFirstChildren` is doing), the list of nodes collected can start with a `Filter` or not. If it does start with a filter and it's the first in the list, you ignore it (as being "filtered") and return `null`. If the first children collected is a `LocalRelation` (thus being an "unfiltered" local relation) then you return it. This does raise a question regarding the functionality of the `collectFirstChildren` method which, in this specific case is confusing.

`filterOrRelation` is a misnomer. It's either Relation of `null`. Even more, I'd change this method to return a `LogicalPlan`. If the returned value is `instanceof LocalRelation` then you do something, if it's `instanceof FIlter` then you don't do anything in `rule(UnaryPlan plan)`. I think is clearer like this, rather than returning a `LocalRelation` and comparing to `null` (which in fact is a non-LocalRelation ie a `Filter`).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 16]
```diff
@@ -1145,49 +1175,47 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
-        @Override
-        protected LogicalPlan rule(LogicalPlan plan) {
-            List<LogicalPlan> leaves = plan.collectLeaves();
+    static class PushProjectionsIntoLocalRelation extends OptimizerRule<UnaryPlan> {
 
-            List<LogicalPlan> projectOrAggregates = plan.collect(p ->
-                p instanceof Project || p instanceof Aggregate);
+        @Override
+        protected LogicalPlan rule(UnaryPlan plan) {
+            if((plan instanceof Project || plan instanceof Aggregate)
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1182]: Whitespace between `if` and `((`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 17]
```diff
@@ -1145,49 +1175,47 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
+                && plan.child() instanceof LocalRelation) {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1184]: Too many empty lines between statements. Make the code more compact, please. Have a look at the original code in this class if needed.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 18]
```diff
@@ -1145,49 +1175,47 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1183]: Move this condition on the same line as the previous conditions.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 19]
```diff
@@ -1145,49 +1175,47 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
+                            return new LocalRelation(plan.source(), new EmptyExecutable(plan.output()));
+                        }
                     }
                 }
 
                 if (foldedValues != null) {
-                    return new LocalRelation(projectOrAggregate.source(),
-                        new SingletonExecutable(projectOrAggregate.output(), foldedValues.toArray()));
+                    return new LocalRelation(plan.source(),
+                        new SingletonExecutable(plan.output(), foldedValues.toArray()));
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1211]:
```suggestion
                    return new LocalRelation(plan.source(), new SingletonExecutable(plan.output(), foldedValues.toArray()));
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 20]
```diff
@@ -1197,20 +1225,44 @@ protected LogicalPlan rule(LogicalPlan plan) {
...
+                && plan.aggregates().stream().allMatch(this::foldable)) {
+
+                return plan.replaceChildrenSameSize(singletonList(new LocalRelation(plan.source(), new SingletonExecutable())));
+            }
+
+            return plan;
+        }
+
+        private boolean foldable(Expression e) {
+            if(e instanceof Alias){
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1257]:
```suggestion
            if (e instanceof Alias){
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 21]
```diff
@@ -1197,20 +1225,44 @@ protected LogicalPlan rule(LogicalPlan plan) {
                     }
                     // not everything is foldable, bail out early
                     else {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1227]:
```suggestion
                    } else {
                         // not everything is foldable, bail out early
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 22]
```diff
@@ -1197,20 +1225,44 @@ protected LogicalPlan rule(LogicalPlan plan) {
...
+    static class SkipQueryForOnlyLiteralAggregations extends OptimizerRule<Aggregate> {
+
+        @Override
+        protected LogicalPlan rule(Aggregate plan) {
+            if (plan.groupings().isEmpty()
+                && plan.child() instanceof EsRelation
+                && plan.aggregates().stream().allMatch(this::foldable)) {
+
+                return plan.replaceChildrenSameSize(singletonList(new LocalRelation(plan.source(), new SingletonExecutable())));
+            }
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1251]:
```suggestion
            if (plan.groupings().isEmpty() && plan.child() instanceof EsRelation && plan.aggregates().stream().allMatch(this::foldable)) {
                return plan.replaceChildrenSameSize(singletonList(new LocalRelation(plan.source(), new SingletonExecutable())));
            }
```

**Review by astefan — COMMENTED** [review]
Looks good in general, but I have some comments regarding code style and, maybe, a more clarifying code suggestion for `ReplaceAggregationsInLocalRelations`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 15 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java]: My intention is to get the `LocalRelation` from the first child branch if there is no `Filter` in between. Not sure whether there is a clearer way, but I'm collecting the `Filter` to stop traversal of the branch as soon as a `Filter` has been encountered. Alternatively, I could first check whether a `Filter` exists and then search for the leaf nodes and see whether it's a single `LocalRelation` but this would require two traversals. What would you suggest?

There was a potential issue though when there are multiple leave nodes of which one is a `LocalRelation`. In this case, `filterOrRelations` could have been of size one as well but the transformation is not supported. So I'm collecting all the leaf nodes now.

**Comment by Luegg** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by Luegg** [comment]
@costin I tried to retain the aggregation information in `ReplaceAggregationsInLocalRelations` as discussed in the call. The relevant information is the fact that a `Literal` in a `Filter` is derived from an aggregate function and cannot be pushed down. Please have a look at the `EliminatedAggregateFunction` class. Not sure that's the best way to retain this information.

**Comment by costin** [comment]
`EliminatedAggregateFunction` is too intrusive and acts as a black list that couples different rules, which is bad.
Assuming the implicit grouping isn't enough (by promoting it from a select with aggregate functions into a aggregate with a special grouping), the solution might light in the way things are folded.

> The relevant information is the fact that a Literal in a Filter is derived from an aggregate function and cannot be pushed down.

Why shouldn't the filter not be pushed down? To quote your previous comment:

```
Agg[1]
\ Local[empty]
```

this should be optimized away by pruning the agg due to the empty relationship. Or am I missing something?

**Comment by Luegg** [comment]
The reason I was hesitant about going with the implicit grouping is because of the edge case where
```
Agg[0 as count(*), IMPLICIT]
\ Local[empty]
```
Will be transformed to 
```
Local[single[count(*)=0]]
```
in `PushProjectionsIntoLocalRelation` (e.g. for the query `SELECT COUNT(*) WHERE FALSE`).

So it's crucial that you can never end up with something like
```
Agg[1 as count(*), IMPLICIT]
\ Local[empty]
```
instead, the IMPLICIT marker needs to be dropped in the right step. It looks like this can be done though.

I will give the IMPLICIT group by marker a try now though.

**Comment by costin** [comment]
After discussing the issue in depth with Lukas today several things became clear (@Luegg please double check):
- the behavior of count with implicit grouping was not properly addressed before - an implicit group for an empty relationship still returns a group with one entry with no values (e.g. `SELECT 2` return literal `2` once for every value in the backing relationship which is implicit yet contains one value. Same for `SELECT 2, COUNT(*)`)
- the initial approach of using rules that need to be applied in a certain order is the most promising solution so far. To reiterate the point `PruneFilter` needs to be applied before `PushDownFilter` because the latter might be triggered on a non-pushable filter (due to folding). 
An example being:
```
Having(count > 1)
\Agg(count)
--
Having(1 > 1)
\Agg(1)
--
Having(false)
\Agg(1)
--

It's important Prune gets called here so that the having(false) gets translated into an empty relationship otherwise it gets pushed down to the agg which will return 1 (unless the Agg gets morphed into a project but that can have side-effects).

@Luegg based on the insights so far, please revert to the first approach to take it up for a final review.
Thanks!

**Comment by Luegg** [comment]
Thanks Costin, I've reverted everything and the PR is now ready for another round of reviews. All other comments from the first reviews are addressed and otherwise there were no changes.

**Review by bpintea — APPROVED** [review]
LGTM.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 23]
```diff
@@ -177,8 +178,13 @@ public LogicalPlan optimize(LogicalPlan verified) {
 
         Batch local = new Batch("Skip Elasticsearch",
                 new SkipQueryOnLimitZero(),
-                new SkipQueryIfFoldingProjection()
+                new SkipQueryForOnlyLiteralAggregations(),
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:181]: Remove `Only` - `SkipQueryForLiteralAggregrations`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 24]
```diff
@@ -1145,72 +1176,86 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
-                    List<Object> folded = extractConstants(a.aggregates());
-
-                    boolean onlyConstantAggregations = leaf instanceof EsRelation
-                        && folded.size() == a.aggregates().size()
-                        && a.groupings().isEmpty();
-
-                    if (isNonSkippedLocalRelation || onlyConstantAggregations) {
-                        foldedValues = folded;
+                if (relation.executable() instanceof SingletonExecutable) {
+                    if (plan instanceof Project) {
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1188]: +1 to Bogdan's comment - having the same condition (check for Aggregate) makes it easier to 'parse' the two branches.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 25]
```diff
@@ -1145,72 +1176,86 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
+        @Override
+        protected LogicalPlan rule(Aggregate plan) {
+            if (plan.groupings().isEmpty() && plan.child() instanceof EsRelation && plan.aggregates().stream().allMatch(this::foldable)) {
+                return plan.replaceChildrenSameSize(singletonList(new LocalRelation(plan.source(), new SingletonExecutable())));
+            }
+
+            return plan;
+        }
+
+        private boolean foldable(Expression e) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1249]: Use the ternary operator :  `return e instanceof Alias ?  foldable(((Alias) e).child()) : e.foldable()`
Additionally since there's no double aliasing, after unwrapping an alias, return the foldability of the child:

```
if (e instanceof Alias) {
 e = ((Alias) e).child()
}
return e.foldable()
```

**Review by costin — APPROVED** [review]
LGTM - thanks for iterating on this!

**Review by astefan — APPROVED** [review]
LGTM
