### PR TITLE
Fix creation of large build job archives

### LINKED ISSUE #102022: Failure generating build-complete archive on Windows
https://gradle-enterprise.elastic.co/s/nenpfb4iogx3k/failure?expanded-stacktrace=WyIwLTEiXQ#1

```
* Exception is:
java.lang.RuntimeException: java.io.IOException: request to write '149' bytes exceeds size in header of '0' bytes for entry './PaxHeaders.X/modules/data-streams/build/testrun/javaRestTest/temp/test-cluster210746955614619588/'
	at org.elasticsearch.gradle.internal.ElasticsearchBuildCompletePlugin$BuildFinishedFlowAction.createBuildArchiveTar(ElasticsearchBuildCompletePlugin.java:210)
	at org.elasticsearch.gradle.internal.ElasticsearchBuildCompletePlugin$BuildFinishedFlowAction.execute(ElasticsearchBuildCompletePlugin.java:135)
	at org.elasticsearch.gradle.internal.ElasticsearchBuildCompletePlugin$BuildFinishedFlowAction.execute(ElasticsearchBuildCompletePlugin.java:108)
	at org.gradle.configurationcache.flow.FlowScheduler.schedule(FlowScheduler.kt:48)
```

### PR DESCRIPTION
**Pull request by breskeby**
This is a new PR introducing configuration cache compliant build finish logic. In addition to the original PR it addresses dealing with large file paths (mainly failing on windows) correctly. 

Example pipeline including running on windows: https://buildkite.com/elastic/elasticsearch-pull-request/builds/761
 
Fixes #102022

### CODE REVIEW

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchBuildCompletePlugin.java [hunk 1]
```diff
@@ -0,0 +1,220 @@
...
+            Property<File> getUploadFile();
+
+            @Input
+            Property<File> getProjectDir();
+
+            @Input
+            ListProperty<File> getFilteredFiles();
+
+            @Input
+            Property<BuildScanExtension> getBuildScan();
```
Comment (mark-vieira) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchBuildCompletePlugin.java:120]: Hmm, I'm not sure we should consider this an input since we're just using it to register scan links. Does `@Internal` work here?

**Review by mark-vieira — APPROVED** [review]

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchBuildCompletePlugin.java (hunk 1 above)
Comment (breskeby) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchBuildCompletePlugin.java:120]: this must be @Input. Everything else is not supported. Even though error messages in gradle are misleading

Comment (mark-vieira) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchBuildCompletePlugin.java:120]: Interesting. I'm surprised that's even serializable. This might bite us later.
