### PR TITLE
Modify the mechanism to pause indexing 

### LINKED ISSUE #126359: [CI] IndexStatsIT testThrottleStats failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7470 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bardg22hxtgqm)
- [elasticsearch-periodic-platform-support #7463 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/pyq53wy2zryz4)

**Reproduction Line:**
```
gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.stats.IndexStatsIT.testThrottleStats" -Dtests.seed=57097D939E3625A7 -Dtests.locale=ar -Dtests.timezone=Indian/Comoro -Druntime.java=22
```

**Applicable branches:**
7.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indices.stats.IndexStatsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testThrottleStats),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: index throttling didn't kick in after 5 minutes of intense merging
```

**Issue Reasons:**
- [7.17] 2 consecutive failures in step windows-2019_checkpart1_platform-support-windows
- [7.17] 2 failures in test testThrottleStats (1.7% fail rate in 118 executions)
- [7.17] 2 failures in step windows-2019_checkpart1_platform-support-windows (66.7% fail rate in 3 executions)
- [7.17] 2 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ankikuma**
This PR changes the mechanism to pause indexing which was introduced in #127173.

The original PR caused `IndexStatsIT#testThrottleStats` to fail. See #126359.

### CODE REVIEW

**Comment by ankikuma** [comment]
The problem with the original implementation of the pause lock mechanism was as follows:

1. First note that the `EngineConcurrentMergeScheduler#beforeMerge` and `EngineConcurrentMergeScheduler#afterMerge` can be called concurrently by 2 different merge threads.

2. Also note that `ThreadPoolMergeScheduler#checkMergeTaskThrottling` can be called concurrently from 2 different threads via `ThreadPoolMergeScheduler#mergeTaskDone` and `ThreadPoolMergeScheduler#submitNewMergeTask`

3. Next note that the above concurrency can cause `Engine#IndexThrottle#activate` and `Engine#IndexThrottle#deactivate` to be called concurrently. The `IndexStatsIT#testThrottleStats` test exposed that this concurrency was not handled correctly by the pause mechanism in place.

This is because the semaphore based approach relies on acquiring and releasing precise number of permits during activate and deactivate, which is not possible to synchronize. Let me try to explain with the the following scenario:
a. Thread 1 : activates throttling on shard --> acquires all but 1 permits
b. Multiple indexing jobs arrive, all waiting to acquire the single available permit --> only one goes through at a time (all is good so far)
c. Thread 2 : deactivate throttling on shard --> releases all but 1 permits --> all is good but note that the jobs in step (b) will still need to acquire and release these permits. 
d. Thread 3: activates throttling immediately after the deactivate in step (c) but it is not able to acquire the requested number of permits immediately because the indexing threads in step (b) have acquired permits in the meantime to work on indexing. So the activate is waiting for permits before it can switch the lock to pauseLock.
e. Thread 4: deactivates throttling immediately following step (d) and finds that we still have a NOOP lock and asserts. In any case, it cannot release the precise number of permits deactivate would like to release, because activate hasn't even acquired them yet.

File: server/src/main/java/org/elasticsearch/index/engine/Engine.java [hunk 1]
```diff
@@ -455,32 +455,71 @@ protected static final class IndexThrottle {
...
+            // throttlingLock.unthrottle();
+
+            if (lock == pauseLockReference) {
+                logger.trace("Deactivate index throttling pause");
+
+                // Signal the threads that are waiting on pauseCondition
+                pauseLockReference.acquire();
+                try {
+                    // System.out.println("Deactivate pause");
+                    pauseIndexing.setRelease(false);
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/Engine.java:517]: To avoid the `pauseIndexing` boolean as suggested above, we need to set the `lock = noop` no later than here.

I think we could simply this to:

```
lock = NOOP_LOCK;
pauseLockReference.acquire();
                try {
                    // System.out.println("Deactivate pause");
                    pauseIndexing.setRelease(false);
Comment
To avoid the `pauseIndexing` boolean as suggested above, we need to set the `lock = noop` no later than here.

I think we could simply this to:

```
lock = NOOP_LOCK;
try (pauseLockReference.acquire()) {
         pauseCondition.signalAll();
}
```

File: server/src/main/java/org/elasticsearch/index/engine/Engine.java [hunk 2]
```diff
@@ -455,32 +455,71 @@ protected static final class IndexThrottle {
...
+                        pauseCondition.await();
+                    }
+                } catch (InterruptedException e) {
+                    Thread.currentThread().interrupt();
+                    throw new RuntimeException(e);
+                } finally {
+                    // System.out.println("Acquired pause indexing lock");
+                    logger.trace("Acquired pause indexing lock");
+                }
+                return pauseLockReference;
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/Engine.java:486]: I think we might as well release the lock immediately and return a noop releasable?

That would allow us to use try-with-resource when acquiring the `pauseLockReference` too.

**Review by henningandersen — COMMENTED** [review]
Left a few comments.

I am ok to revert to this if you find it simpler. I see how it reduces the race condition surface, but there is still a race where if a thread deactivates throttling and at the same time another thread activates throttling, we risk running with no throttling at all.

I think that we could make activate/deactive throttling synchronized on a lock object instead to avoid all of this?

File: server/src/main/java/org/elasticsearch/index/engine/Engine.java [hunk 3]
```diff
@@ -455,33 +455,64 @@ protected static final class IndexThrottle {
         private final CounterMetric throttleTimeMillisMetric = new CounterMetric();
         private volatile long startOfThrottleNS;
         private static final ReleasableLock NOOP_LOCK = new ReleasableLock(new NoOpLock());
-        private final PauseLock throttlingLock;
-        private final ReleasableLock lockReference;
+        private final ReleasableLock lockReference = new ReleasableLock(new ReentrantLock());
+        private final Lock pauseIndexingLock = new ReentrantLock();
+        private final Condition pauseCondition = pauseIndexingLock.newCondition();
+        private final ReleasableLock pauseLockReference = new ReleasableLock(pauseIndexingLock);
+        private volatile AtomicBoolean pauseThrottling = new AtomicBoolean();
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/Engine.java:462]: Can we name this and the method differently, like `suspendThrottling`? `pauseThrottling` sounds like a variable indicating that the "pause throttling" mechanism is enabled when instead it is that it is disabled ;-)

File: server/src/main/java/org/elasticsearch/index/engine/Engine.java (hunk 2 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/index/engine/Engine.java:485]: I'd still like to see this carried through.

As we wake up after pause throttling, with the current mechanism, we'll only wake up one of the paused threads at a time until each of their indexing requests complete. Notice that `await` only allows one thread at a time to come out of `await` until the lock is released, since returning from `await` reacquires the lock.

This means that if the situation is cured, but the first few indexing requests take "a long time", we are still essentially throttling to fewer threads for a while.

I'll LGTM it for now, since it is not *that* harmful, but would prefer to see this sorted in this PR.

File: server/src/main/java/org/elasticsearch/index/engine/Engine.java [hunk 4]
```diff
@@ -455,33 +455,64 @@ protected static final class IndexThrottle {
...
 
         public IndexThrottle(boolean pause) {
-            throttlingLock = new PauseLock(pause ? 0 : 1);
-            lockReference = new ReleasableLock(throttlingLock);
+            pauseWhenThrottled = pause;
         }
 
         public Releasable acquireThrottle() {
-            return lock.acquire();
+            if (lock == pauseLockReference) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/Engine.java:471]: We read `lock` twice when doing regular throttling, once for the condition here and once below. Since it is volatile, it would be good to only read it once, i.e., copy it to a local variable:

```
var lock = this.lock;
```

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/index/engine/Engine.java (hunk 4 above)
Comment (ankikuma) [reply server/src/main/java/org/elasticsearch/index/engine/Engine.java:471]: But don't we need to read the latest value of lock inside the try block ?
