### PR TITLE
make painless the default scripting language for ScriptProcessor

### LINKED ISSUE #20943: lang is still required in Ingest Script Processor
**Elasticsearch version**: 5.0.0-rc1

**Description of the problem including expected versus actual behavior**:
Currently we [default scripts to lang=painless and treat the parameter as optional in many places](https://github.com/elastic/elasticsearch/issues/20122#issuecomment-244337340).  We [say it's not required](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/script-processor.html) in the Ingest Script Processor, but we still throw `"reason": "[lang] required property is missing"` if you don't include the parameter.  I think this one just got missed when we did the defaults switch.

**Steps to reproduce**:

    POST _ingest/pipeline/_simulate
    {
      "pipeline" :
      {
        "description": "_description",
        "processors": [
          {
            "script": {
              "inline":"ctx.hi = 'hello';"
            }
          }
        ]
      },
      "docs": [
        {
          "_index": "shanetest",
          "_type": "shanetest",
          "_id": "1",
          "_source": {
            "field_a": 3
          }
        }
      ]
    }

### PR DESCRIPTION
**Pull request by talevy**
- fixes a bug in the docs that mentions `lang` as optional
- now `lang` defaults to "painless"

Closes #20943.

### CODE REVIEW

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java [hunk 1]
```diff
@@ -80,7 +84,7 @@ public Factory(ScriptService scriptService) {
         @Override
         public ScriptProcessor create(Map<String, Processor.Factory> registry, String processorTag,
                                       Map<String, Object> config) throws Exception {
-            String lang = readStringProperty(TYPE, processorTag, config, "lang");
+            String lang = readStringProperty(TYPE, processorTag, config, "lang", "painless");
```
Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: Why is this hardcoded at all, and not just using the ScriptService and the default that is configured there?

Comment (talevy) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: @rjernst simply because I was not aware there was such default behavior in the ScriptService. I will move defaulting responsibility to the ScriptService, will update. thanks!

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java [hunk 2]
```diff
@@ -69,6 +69,10 @@ public String getType() {
         return TYPE;
     }
 
+    public Script getScript() {
```
Comment (martijnvg) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: getter can be package protected?

**Review by martijnvg — APPROVED** [review]
Left a tiny comment, LGTM
