### PR TITLE
[ML][Transform] reset failure count when a transform aggregation page is handled successfully

### LINKED ISSUE #76074: [Transform] Reset failure counter after 1st success after a failure
Transform retries per _default_ 10 times for non-permanent errors and goes into failed state if it fails 10 times in a row.

However, inspecting the code, it turns out the counter is reset per checkpoint. This does not take into account the amount of data processed for a checkpoint, neither does a success reset the counter to `0`. 

If a checkpoint looks like this with `s==success` and `f== failure`: 

`ssfffsfssfffsssssssssfssssssssssssfsssssssssf` 

the transform fails, although the failures were not in a row and there could be many `s` in between.

### PR DESCRIPTION
**Pull request by benwtrent**
Failure count should not only be reset at checkpoints. Checkpoints could have many pages of data. Consequently, we should reset the failure count once we handle a single composite aggregation page.

This way, the transform won't mark itself as failed erroneously when it has actually succeeded searches + indexing results within the same checkpoint.

closes https://github.com/elastic/elasticsearch/issues/76074

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 1]
```diff
@@ -142,71 +142,72 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
...
+    protected void handleBulkResponse(BulkResponse bulkResponse, ActionListener<BulkResponse> nextPhase) {
+        if (bulkResponse.hasFailures() == false) {
+            // We don't know the of failures that have occurred (searching, processing, indexing, etc.),
+            // but if we search, process and bulk index then we have
+            // successfully processed an entire page of the transform and should reset the counter, even if we are in the middle
+            // of a checkpoint
+            context.resetReasonAndFailureCounter();
+            nextPhase.onResponse(bulkResponse);
+            return;
+        }
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:158]: OK, this diff is a pain. The only difference here is the `resetReasonAndFailureCounter` and the comments. I created a new method here so that this is testable.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 2]
```diff
@@ -146,7 +146,7 @@ public TransformIndexer(
         this.checkpointProvider = ExceptionsHelper.requireNonNull(checkpointProvider, "checkpointProvider");
         this.auditor = transformServices.getAuditor();
         this.transformConfig = ExceptionsHelper.requireNonNull(transformConfig, "transformConfig");
-        this.progress = progress != null ? progress : new TransformProgress();
+        this.progress = transformProgress != null ? transformProgress : new TransformProgress();
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:149]: OK, this seemed like a bug, `progress` was assigning to itself, which was never set? We should set it to the passed value.

Comment (droberts195) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:149]: That was broken in #75459, which is a 7.15 change, and explains why it hasn't caused a bug report from a user yet.

Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:149]: 😌

**Review by droberts195 — APPROVED** [review]
LGTM
