### PR TITLE
Engine: refresh before translog commit

### LINKED ISSUE #13379: CI: BulkIT.testBulkUpdate_largerVolume fails one of its GetRequests
http://build-us-00.elastic.co/job/es_core_2x_strong/28/

The issue is reproducible most of the time running this seed (on osx), further parameters having no influence already removed:

```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=872FF07FDDFBCB -Dtests.class=org.elasticsearch.document.BulkIT -Dtests.method="testBulkUpdate_largerVolume" -Des.logger.level=DEBUG -Des.node.mode=local
```

When not running in `local` mode, this does not occur, also adding `waitForRelocations` makes it vanish, but I am not sure, if this is the underlying issue here.

### PR DESCRIPTION
**Pull request by brwe**
When we commit the translog, documents that were in it before cannot be retrieved from
it anymore via get and have to be retrieved from the index instead. But they will only
be visible if between index and get a refresh is called. Therfore we have to call
first refresh and then translog.commit() because otherwise there is a small gap
in which we cannot read from the translog anymore but also not from the index.

closes #13379

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 1]
```diff
@@ -522,6 +523,42 @@ public IndexSearcher wrap(EngineConfig engineConfig, IndexSearcher searcher) thr
     }
 
     @Test
+    /* */
+    public void testConcurrentGetAndFlush() throws Exception {
+        ParsedDocument doc = testParsedDocument("1", "1", "test", null, -1, -1, testDocumentWithTextField(), B_1, null);
+        engine.create(new Engine.Create(newUid("1"), doc));
+        AtomicReference<Engine.GetResult> latestGetResult = new AtomicReference<>();
+        AtomicBoolean flushFinished = new AtomicBoolean(false);
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: these must be final for backporting?

File: core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 2]
```diff
@@ -522,6 +523,42 @@ public IndexSearcher wrap(EngineConfig engineConfig, IndexSearcher searcher) thr
...
+        Thread getThread = new Thread() {
+            @Override
+            public void run() {
+                while (flushFinished.get() == false) {
+                    Engine.GetResult previousGetResult = latestGetResult.get();
+                    if (previousGetResult != null) {
+                        previousGetResult.release();
+                    }
+                    try {
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: can the sleep go?

**Comment by s1monw** [comment]
left minor commetns LGTM

File: core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java (hunk 2 above)
Comment (brwe) [inline core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: yes

**Comment by brwe** [comment]
@s1monw thanks! addressed all comments

**Comment by mikemccand** [comment]
Is there still a race here?  I.e. after `refresh` but before `translog.commit`, another thread indexes some documents, but these documents are not visible via realtime get until the next refresh?

**Comment by brwe** [comment]
@mikemccand good point. but if I understand it correctly we actually create a new translog before we refresh in `translog.prepareCommit()` and then in `translog.commit()` just delete the old one. Documents that came in between `refresh()` and `translog.commit()` will be in the new translog and therefore are still available from there after commit. Only docs that were in translog before `prepareCommit()` are not available from translog anymore but they can be retrieved from index. Let me know if this makes sense, I might just miss something.

**Comment by mikemccand** [comment]
> but if I understand it correctly we actually create a new translog before we refresh in `translog.prepareCommit()`

Aha!  Sorry, I missed the `prepareCommit` call ... so you are correct!  Thanks :)

**Comment by mikemccand** [comment]
LGTM

**Comment by s1monw** [comment]
LGTM 2
