### PR TITLE
CompoundProcessor should also catch exceptions when executing a processor

### LINKED ISSUE #84781: Ingest enrich processor then foreach processor == possible memory leak
### Elasticsearch Version

7.x, 8.x

### Problem Description

If a "foreach" processor follows an "enrich" processor to handle the results of the  the "enrich" processor but the "enrich" processor does not match anything a memory leak is possible. 

### Steps to Reproduce

Create the enrich policy and index:
```
PUT mysource/_doc/1
{ 
  "tomatch" : "a",
  "other" : ["foo", "bar"]
}

PUT /_enrich/policy/myenrich 
{ 
  "match" : { 
    "indices": [ 
      "mysource"  
    ], 
    "match_field": "tomatch",
    "enrich_fields": [ 
      "other"
    ] 
  } 
}

POST /_enrich/policy/myenrich/_execute
```

Create the pipeline:
```
PUT _ingest/pipeline/test
{
    "processors": [
        {
            "enrich": {
                "policy_name": "myenrich",
                "field": "tomatch",
                "target_field": "matched"
            }
        },      
        {
            "foreach": {
                "field": "matched",
                "processor": {
                    "append": {                        
                        "field": "matched2",
                        "value": "{{_ingest._value}}"                       
                    }
                }
            }
        }
    ]
}
```

Execute the pipeline:
```
PUT test/_doc/2?pipeline=test
{
    "tomatch" : "x"  
}
```

Check the node stats:
```
GET _nodes/stats/ingest?filter_path=**.pipelines.test

```
Here you will notice that "count" will be 0 for the "foreach" processor, but "current" will remain incremented. Repeat the pipeline execution and you can see the "current" value continue to increase.

For example:
```
"foreach": {
        "type": "foreach",
        "stats": {
            "count": 0,
            "time_in_millis": 0,
            "current": 4,
            "failed": 0
        }
    }
```

Review the tasks:
```
GET _tasks?human
```
Here you will see that the write task never finished: `"action": "indices:data/write/index"`

Check the index
```
GET test/_search
```

No data is written. 

In the above example change "tomatch" to "a" for the document getting index to allow the match to happen and all is well. This bug only presents when the match does not happen (more specifically if the {{_ingest._value}} of the foreach processor is null).

### Workaround

Use the "if" condition of the foreach processor to ensure that {{_ingest._value}} is never null by checking the value of the "field".  (you can not directly access the _ingest from the if condition - see https://github.com/elastic/elasticsearch/issues/60470)

Example above with workaround:

```
PUT _ingest/pipeline/test
{
    "processors": [
        {
            "enrich": {
                "policy_name": "myenrich",
                "field": "tomatch",
                "target_field": "matched"
            }
        },      
        {
            "foreach": {
                "if": "ctx.matched != null",
                "field": "matched",
                "processor": {
                    "append": {                        
                        "field": "matched2",
                        "value": "{{_ingest._value}}"                       
                    }
                }
            }
        }
    ]
}

```

### PR DESCRIPTION
**Pull request by martijnvg**
Currently, CompoundProcessor does not catch Exception and
if a processor throws an error and a method higher in the
call stack doesn't catch the exception then pipeline execution
stalls and bulk requests may not complete.

Usually these exceptions are caught by IngestService#executePipelines(...) method,
but when a processor executes async (for example: enrich processor) and the thread
that executes enrich is no longer the original write thread then there is no logic
that deals with failing pipeline execution and cleaning resources up. This then leads
to memory leaks.

Closes #84781

Note that this PR will be forward ported to 8.1 and master branches.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java [hunk 1]
```diff
@@ -133,30 +133,45 @@ void innerExecute(int currentProcessor, IngestDocument ingestDocument, BiConsume
         final IngestMetric metric = processorWithMetric.v2();
         final long startTimeInNanos = relativeTimeProvider.getAsLong();
         metric.preIngest();
-        processor.execute(ingestDocument, (result, e) -> {
-            long ingestTimeInNanos = relativeTimeProvider.getAsLong() - startTimeInNanos;
-            metric.postIngest(ingestTimeInNanos);
+        try {
+            processor.execute(ingestDocument, (result, e) -> {
+                long ingestTimeInNanos = relativeTimeProvider.getAsLong() - startTimeInNanos;
+                metric.postIngest(ingestTimeInNanos);
```
Comment (jbaiera) [inline server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java:139]: Should we be calling this in case of failure as well?

**Review by jbaiera — APPROVED** [review]
LGTM pending question about metrics accounting

File: server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java (hunk 1 above)
Comment (jbaiera) [reply server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java:139]: specifically `metric.postIngest(ingestTimeInNanos);`

\me shakes fist at IDEA review tools picking four lines for the comment

Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java:139]: Good point. I think `metric.postIngest(ingestTimeInNanos);` should be called as well when catch exception at line 151. 

(in case an error comes in via this handler (meaning `e` is not null) then this is already invoked)
