### PR TITLE
Don't shortcut the total hit count for text fields 

### LINKED ISSUE #89760: total hit count is wrong for exists query
### Elasticsearch Version

8.4.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macOs 10.15.7, Elasticsearch running in docker container

### Problem Description

I index 5 documents containing a minmal set of fields. One field is named `name` and for one of the docs it is empty (`""`) and for one it does not exist.

I then search for documents where this field exists. The returned hits a alright, but the value value in the total relation object is wrong. This worked in 8.3.3, but erros in 8.4.1

Expected behaviour: the total hit value is 4

Actual behaviour: the value of 3 is returned

### Steps to Reproduce

Post the following documents to `testindex`:

```
{
	"name": "name-1",
}

{
	"name": "name-2",
}

{
	"name": "name-3",
}

{
	"name": "",
}

{
	value: 42
}
```

send the following query:
```
POST /testindex/_search 
{
  "query": {
    "exists": {
      "field": "name"
    }
  }
}
```

This returns:
```
{
  "_shards": {
    "failed": 0,
    "skipped": 0,
    "successful": 1,
    "total": 1
  },
  "hits": {
    "hits": [
      {
        "_id": "4T0z9YIBgYaqNSSuHK8i",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": "name-1"
        }
      },
      {
        "_id": "4j0z9YIBgYaqNSSuOK80",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": "name-2"
        }
      },
      {
        "_id": "4z0z9YIBgYaqNSSuSq8F",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": "name-3"
        }
      },
      {
        "_id": "5D0z9YIBgYaqNSSuX68P",
        "_index": "testindex",
        "_score": 1.0,
        "_source": {
          "name": ""
        }
      }
    ],
    "max_score": 1.0,
    "total": {
      "relation": "eq",
      "value": 3
    }
  },
  "timed_out": false,
  "took": 62
}

```

Although 4 documents are returned, the total value returned is 3.

This is a problem for me as I use queries with a size of 0 and track_total_hits set to true to do a count query. This now returns wrong results.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by javanna**
When we switched to using the `FieldExistsQuery` (see #88312) instead of the deprecated `NormsFieldExistsQuery` and
`DocValuesFieldExistsQuery`, we introduced a bug that made us shortcut the total hit count for text fields to the doc count retrieved from the terms enum, which does not take into account empty strings. In presence of text fields, we cannot shortcut, and this can be prevented by checking that the field has doc_values. This was checked before indirectly by checking that the query is a `DocValuesFieldExistsQuery` which can only be the result of a field having doc_values.

Closes #89760

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/query/TopDocsCollectorContext.java [hunk 1]
```diff
@@ -408,6 +409,10 @@ static int shortcutTotalHitCount(IndexReader reader, Query query) throws IOExcep
                 FieldInfos fieldInfos = context.reader().getFieldInfos();
                 FieldInfo fieldInfo = fieldInfos.fieldInfo(field);
                 if (fieldInfo != null) {
+                    if (fieldInfo.getDocValuesType() == DocValuesType.NONE) {
+                        // no shortcut possible: it's a text field, empty values are counted as no value.
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/search/query/TopDocsCollectorContext.java:413]: For my understanding of the comment: do we know that we have a text field here because its the only one without doc values or do we know this from somewhere else? Or asked another way: could there be other field types without doc values that are not text, in which case the comment can probably be more general

**Review by cbuescher — APPROVED** [review]
Thanks for letting me review this since I was interested in that change. I left a small question for my understanding. In addition to the unit test on the Lucene collector level I think it would also be great to have an addition to e.g. the "160_exists_query.yml" yaml tests with empty strings in text fields to cover this special edge case on a more high level in case the implementation details of which Lucene query we turn our own DSL queries into change (like they have in the recent refactoring).

File: server/src/main/java/org/elasticsearch/search/query/TopDocsCollectorContext.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/query/TopDocsCollectorContext.java:413]: Good question, this is not straight-forward: there are certainly other field types that may not have doc_values, e.g. a keyword with doc_values disabled, although not so common. At the lucene level we don't really have a way to distinguish between the two. What looked funny here is that we check the doc_values type, and then if there are doc_values we may look at terms, that have nothing to do with doc_values. This is to ensure that we don't shortcut for text fields, as empty tokens after analysis means no value, like the comment says.

For more info, this logic emulates what the [`FieldExistsQuery`](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/FieldExistsQuery.java#L229) in Lucene does.
