### PR TITLE
ILM step retry safe refresh of the cached phase

### LINKED ISSUE #81921: ILM: Retrying a failed step refreshes the cached ILM phase
**Elasticsearch version** (`bin/elasticsearch --version`): 7.x and 8.x

**Description of the problem including expected versus actual behaviour**:

When ILM retries a step (moving from the ERROR step back to the failed_step) we [refresh the ILM cached phase](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java#L254).

This makes sense if a policy is changed for example (eg. correcting the configured ILM policy for an index to a new one)
however, in case the `failed_step` doesn't exist anymore in the policy (say the policy was updated and the current action was removed), refreshing the cached phase will block ILM from making progress, with a message along the lines of
```
current step [{"phase":"warm","action":"shrink","name":"shrink"}] for index [my-index] with policy [my-policy] is not recognized
```

I believe we should try and check if the `failed_step` is still part of the configured policy before refreshing the cached phase, and if that's not the case, skip re-freshing the cached phase and have ILM honour it.

### PR DESCRIPTION
**Pull request by andreidan**
When ILM retries a step (moving from the ERROR step back to the
failed_step) we always refreshed the ILM cached phase (the use case here
was that the policy might've been changed for an index due to
accidentally configuring the wrong policy).

In the case when the `failed_step` doesn't exit in the policy though,
refreshing the cached phase would block ILM as the retried step (the
`failed_step`) would not be recognized anymore.

This commit changes retrying an ILM step to only refresh the cached
phase if the failed_step's action and phase are still present in the
policy. If the action or even phase were removed, ILM will honour the
cached phase.

Fixes #81921

### CODE REVIEW

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java [hunk 1]
```diff
@@ -246,13 +247,30 @@ static ClusterState moveClusterStateToPreviouslyFailedStep(
...
             LifecyclePolicyMetadata policyMetadata = ilmMeta.getPolicyMetadatas()
                 .get(LifecycleSettings.LIFECYCLE_NAME_SETTING.get(indexMetadata.getSettings()));
-            LifecycleExecutionState nextStepState = IndexLifecycleTransition.updateExecutionStateToStep(
-                policyMetadata,
-                lifecycleState,
-                nextStepKey,
-                nowSupplier,
-                true
-            );
+
```
Comment (joegallo) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java:250]: If the only difference between the two branches of the if/else is the boolean that's being passed through, would it be more readable to extract that as a variable and then pass the variable (with no if/else)?

**Review by dakrone — APPROVED** [review]
LGTM, I agree on Joe's comment about making it a variable also. Thanks for fixing this Andrei!

**Review by kirakoki — APPROVED** [review]
