### PR TITLE
Remove `RecoveryMonitor`

### LINKED ISSUE #93544: Do we need the RecoveryMonitor?
Today we fail a recovery that seems not to have made progress within 30 minutes. IMO these days this causes more problems than it solves: we have no known deadlocks in this area, if there are any deadlocks then this timeout just hides them, and we don't do a good job of accounting for steps that genuinely take longer than the timeout in some circumstances. For instance:

- #65531
- #93542

Should we remove this feature? If not, it seems pretty much wholly untested, we should introduce some better testing in this area.

### PR DESCRIPTION
**Pull request by DaveCTurner**
There are no known situations where recoveries that take longer than
30min should fail, and several where we know it should keep on waiting.
This commit removes the unnecessary timeout and associated monitor.

Closes #93544

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoveriesCollection.java [hunk 1]
```diff
@@ -82,11 +78,6 @@ private void startRecoveryInternal(RecoveryTarget recoveryTarget, TimeValue acti
             recoveryTarget.sourceNode(),
             recoveryTarget.recoveryId()
         );
-        threadPool.schedule(
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/indices/recovery/RecoveriesCollection.java:85]: threadPool can be removed now

**Review by tlrx — APPROVED** [review]
LGTM, left a nit

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoveriesCollection.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/indices/recovery/RecoveriesCollection.java:85]: ++ thanks

**Comment by henningandersen** [comment]
Looks like it was added in 102e7adfadba1d7965d205420f1edd2511af8e0f and `IndexRecoveryIT had some added tests there. It may be worth running those in a loop to see if the reason the recovery monitor was added is a failure there that is not yet fully covered.

**Comment by DaveCTurner** [comment]
AFAICT these are all caught by `indices.recovery.internal_action_timeout` (which does influence `indices.recovery.recovery_activity_timeout`, it's true, but that's not what these tests are testing). I've run 10 iterations with no issues, will keep on running for a while more even post-merge.

**Comment by DaveCTurner** [comment]
Completed 1600+ iterations over the weekend with no failures.
