### PR TITLE
[ES|QL] To_DatePeriod and To_TimeDuration return better error messages on union_type fields

### LINKED ISSUE #112668: [ES|QL] Return correct correct message when a union type field is provided to to_dateperiod or to_timeduration
`To_DatePeriod` and `To_TimeDuration` only take constants as input, when a union type field is provided to them, the correct error message doesn't return.

Here are the steps to reproduce it:

```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test1" -XPUT -d '{
  "mappings": {                                                                                                         
        "properties": {
            "x": {       
                "type": "keyword"
            }
        }
  }
}'
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test2" -XPUT -d '{
  "mappings": {
        "properties": {
            "x": {
                "type": "text"   
            }
        }
  }
}'
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '{
    "query": "from test* | eval y = now() + to_dateperiod(x)"}
'

"verification_exception","reason":"Found 1 problem\nline 1:45: Cannot use field [x] due to ambiguities being mapped as [2] incompatible types: [keyword] in [test1], [text] in [test2]"}]
```

`To_DatePeriod` has an unresolved child, `Analyzer`'s `Verifier` errors out. However, the real/expected error that the function only takes foldable inputs are not returned, because the check to foldable is deferred to `LogicalPlanOptimizer`, which is after `Analyzer`. The correct error message is returned for the other field/data types, this is found for union type field only.

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #112668

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -1225,6 +1226,10 @@ private Expression resolveConvertFunction(AbstractConvertFunction convert, List<
             if (convert.field() instanceof FieldAttribute fa && fa.field() instanceof InvalidMappedField imf) {
                 HashMap<TypeResolutionKey, Expression> typeResolutions = new HashMap<>();
                 Set<DataType> supportedTypes = convert.supportedTypes();
+                if (convert instanceof FoldablesConvertFunction fcf && supportedTypes.isEmpty()) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1229]: Isn't the `instanceof` check sufficient, like so?
```suggestion
                if (convert instanceof FoldablesConvertFunction fcf) {
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/FoldablesConvertFunction.java [hunk 2]
```diff
@@ -59,7 +59,8 @@ protected final TypeResolution resolveType() {
 
     @Override
     protected final Map<DataType, BuildFactory> factories() {
-        // TODO if a union type field is provided as an input, the correct error message is not shown, #112668 is a follow up
+        // This is used by ResolveUnionTypes, which is expected to be applied to ES fields only
+        // FoldablesConvertFunction takes only constants as inputs, so this is empty
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/FoldablesConvertFunction.java:63]: Similarly, this comment claims that this is used, but in `resolveConvertFunction` (line 1229), the check for `supportedTypes.isEmpty()` is always true, no?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 3]
```diff
@@ -1243,6 +1248,25 @@ private Expression resolveConvertFunction(AbstractConvertFunction convert, List<
             return convert;
         }
 
+        private static Expression resolveFoldablesConvertFunction(FoldablesConvertFunction fcf) {
+            if (fcf.field() instanceof FieldAttribute fa && fa.field() instanceof InvalidMappedField imf) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1252]: In the one place where this method is called, the field is always an `InvalidMappedField` so this check is redundant, isn't it?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 4]
```diff
@@ -1243,6 +1248,25 @@ private Expression resolveConvertFunction(AbstractConvertFunction convert, List<
...
+                String unresolvedMessage = "argument of ["
+                    + fcf.sourceText()
+                    + "] must be a constant, received ["
+                    + Expressions.name(fa)
+                    + "]";
+                String types = imf.getTypesToIndices().keySet().stream().collect(Collectors.joining(","));
+                Expression ua = new UnsupportedAttribute(
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1259]: I believe we should use `UnresolvedAttribute` here.

`UnsupportedAttribute` enjoys privileged treatment by the verifier: it's used for
- fields with unsupported data type and
- multi-typed fields (that aren't resolved to a union type)
and are being passed through the compute engine as `null`s.

Currently, I think the way to mark something as invalid is using an unresolved attribute with a custom message.

(Maybe we should have an `InvalidAttribute` as well, because `UnresolvedAttribute` can either be "this is not resolved _yet_ but maybe later!", while we actually need something that says "we can't have a properly resolved attribute here because the query's invalid!")

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 5]
```diff
@@ -1243,6 +1248,25 @@ private Expression resolveConvertFunction(AbstractConvertFunction convert, List<
...
+                    fa.source(),
+                    fa.name(),
+                    new UnsupportedEsField(imf.getName(), types),
+                    unresolvedMessage
+                );
+                return fcf.replaceChildren(Collections.singletonList(ua));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1265]: bikeshed: we could probably also replace the whole convert function by an `UnresolvedAttribute` (with the custom message from above); probably irrelevant for the final verification, though.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 6]
```diff
@@ -244,6 +244,23 @@ public void testUnsupportedAndMultiTypedFields() {
                 + " [ip] in [test1, test2, test3] and [2] other indices, [keyword] in [test6]",
             error("from test* | where multi_typed is not null", analyzer)
         );
+
+        assertEquals(
+            "1:47: Cannot use field [unsupported] with unsupported type [flattened]",
+            error("from test* | eval x = now() + to_timeduration(unsupported)", analyzer)
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:250]: nit: the test cases could be parameterized to run for both `to_timeduration` and `to_dateperiod`. Or simply copy-pasted so that both foldables convert functions are tested in each scenario.

**Review by alex-spies — COMMENTED** [review]
Thanks @fang-xing-esql !

This nearly LGTM and I have mostly minor comments; the only, slightly not-so-minor remark is that we shouldn't use `UnsupportedAttribute` here as that has a pretty specific meaning and treatment in both the verifier and compute engine.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1229]: Yes, `instanceof` is sufficient, right now all of `FoldablesConvertFunction` have empty `supportedTypes`, a little too cautious here, I'll remove it.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 3 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1252]: Yeah, this method is called in only one place, the checks here are used so that we don't have to do unnecessary casting in the error messages. I'll embed the error message in the caller in stead, so that we don't have to do unnecessary check or casting here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 5 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1265]: I'd prefer to keep the function name, not reverting it back to `UnresolvedAttribute`, as `ResolveFunctions` has don't its job, and it is correct. The conversion function's name has been resolved by `ResolveFunctions`, however its children haven't been resolved yet.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java (hunk 6 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: Done.

**Comment by fang-xing-esql** [comment]
Thanks for reviewing @alex-spies ! The comments have been addressed in the last commit.

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch

**Review by bpintea — APPROVED** [review]
Lgtm

**Comment by fang-xing-esql** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116631)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
