### PR TITLE
[ML] make InferenceIngestIT more lenient when checking cache miss counts

### LINKED ISSUE #61564: [CI] InferenceIngestIT.testPipelineIngest and testPathologicalPipelineCreationAndDeletion failures
**Build scan**:
https://gradle-enterprise.elastic.co/s/2kdpwkkrjc6r4

**Repro line**:
> ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.InferenceIngestIT.testPipelineIngest" -Dtests.seed=F132D0E49ECDF4B3 -Dtests.security.manager=true -Dtests.locale=sr-ME -Dtests.timezone=Pacific/Midway -Druntime.java=8
>
> ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.InferenceIngestIT.testPathologicalPipelineCreationAndDeletion" -Dtests.seed=F132D0E49ECDF4B3 -Dtests.security.manager=true -Dtests.locale=sr-ME -Dtests.timezone=Pacific/Midway -Druntime.java=8
>

**Reproduces locally?**:
No

**Applicable branches**:
* 7.x
* 7.9

**Failure history**:

These two tests seem only fail for v7 branches. It failed 8 times within last 60 days according to [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(build.branch),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!t,params:!(pull-request,pull-request-1,pull-request-2,pull-request-bwc),type:phrases,value:'pull-request,%20pull-request-1,%20pull-request-2,%20pull-request-bwc'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(build.branch:pull-request)),(match_phrase:(build.branch:pull-request-1)),(match_phrase:(build.branch:pull-request-2)),(match_phrase:(build.branch:pull-request-bwc))))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'InferenceIngestIT%20cache_miss_count'),sort:!(process.time-start,desc))).

When they fail, there are always failures of `ClassificationIT  in the same build scan with "ClusterHealthResponse has timed out" error. Maybe they are related, like one is the cause of the other.

I also noticed we have a previous issue (#54786) for testPipelineIngest but the failure message is different. So I am opening a new issue.

**Failure excerpt**:
```

java.lang.AssertionError: |  
-- | --
  | Expected: a string containing "\"cache_miss_count\":3" |  
  | but: was "{"count":1,"trained_model_stats":[{"model_id":"test_classification","pipeline_count":0,"inference_stats":{"failure_count":0,"inference_count":10,"cache_miss_count":2,"missing_all_fields_count":0,"timestamp":1598400435615}}]}" |  

at __randomizedtesting.SeedInfo.seed([F132D0E49ECDF4B3:536E46D26C7D13F0]:0) |  
-- | --
  |   | •••
  |   | at org.elasticsearch.xpack.ml.integration.InferenceIngestIT.lambda$testPipelineIngest$1(InferenceIngestIT.java:178) |  
  |   | •••
  |   | at org.elasticsearch.xpack.ml.integration.InferenceIngestIT.testPipelineIngest(InferenceIngestIT.java:172) |  
  |   | •••


```

### PR DESCRIPTION
**Pull request by benwtrent**
Looking over the failure history, it is always the cache miss count that is off. This is mostly ok as all the failures had indicated that there were indeed cache failures and every one of them were fence-post errors. 

Opting to make the cache miss count check lenient as other stats checked verify consistency.

closes https://github.com/elastic/elasticsearch/issues/61564

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java [hunk 1]
```diff
@@ -135,13 +144,23 @@ public void testPathologicalPipelineCreationAndDeletion() throws Exception {
             try {
                 Response statsResponse = client().performRequest(new Request("GET",
                     "_ml/trained_models/" + classificationModelId + "/_stats"));
-                String response = EntityUtils.toString(statsResponse.getEntity());
-                assertThat(response, containsString("\"inference_count\":10"));
-                assertThat(response, containsString("\"cache_miss_count\":30"));
+                try (XContentParser parser = createParser(JsonXContent.jsonXContent, statsResponse.getEntity().getContent())) {
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java:147]: If I see correctly, the pattern of parsing the response and verifying `getInferenceCount` is repeated 4 times.
Please consider extracting the snippet to a separate method parameterized by the expected inference count.

**Review by davidkyle — APPROVED** [review]
Good fix!

**Review by przemekwitek — COMMENTED** [review]
LGTM
