### PR TITLE
[Transform] Wait for start in YAML tests

### LINKED ISSUE #98802: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Test start already started transform} failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/5k46ixgmcr2h2/tests/:x-pack:plugin:yamlRestTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=transform%2Ftransforms_start_stop%2FTest%20start%20already%20started%20transform%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Test start already started transform}" -Dtests.seed=A05AE1A23931E0C4 -Dtests.locale=es-UY -Dtests.timezone=America/Nome -Druntime.java=20
```

**Applicable branches:**
8.9

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Dtransform/transforms_start_stop/Test%20start%20already%20started%20transform%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:135]: expected [4xx|5xx] status code but api [transform.start_transform] returned [200 OK] [{"acknowledged":true}]

  at __randomizedtesting.SeedInfo.seed([A05AE1A23931E0C4:280EDE7897CD8D3C]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.lang.AssertionError: expected [4xx|5xx] status code but api [transform.start_transform] returned [200 OK] [{"acknowledged":true}]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:359)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1623)

```

### LINKED ISSUE #115808: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Verify start transform reuses destination index} failing
**Build Scans:**
- [elasticsearch-intake #12074 / part3](https://gradle-enterprise.elastic.co/s/3a72q6jkm3fvw)
- [elasticsearch-pull-request #38590 / part-3](https://gradle-enterprise.elastic.co/s/wztiskneipl6i)
- [elasticsearch-pull-request #38590 / rest-compatibility](https://gradle-enterprise.elastic.co/s/4gs7phvuiefh6)
- [elasticsearch-pull-request #38383 / rest-compatibility](https://gradle-enterprise.elastic.co/s/paarpfj2paobs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Verify start transform reuses destination index}" -Dtests.seed=8042280025D39B59 -Dtests.locale=en-CM -Dtests.timezone=America/El_Salvador -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_start_stop%2FVerify%20start%20transform%20reuses%20destination%20index%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:201]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-stop] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:353)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:956)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"}],"type":"status_exception","reason":"Starting transform [airline-transform-start-stop] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:353)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:956)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"},"status":408}]
```

**Issue Reasons:**
- [main] 4 failures in test test {p0=transform/transforms_start_stop/Verify start transform reuses destination index} (0.4% fail rate in 903 executions)
- [main] 2 failures in step rest-compatibility (1.0% fail rate in 192 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.0% fail rate in 193 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #117473: [CI] XPackRestIT test {p0=transform/transforms_reset/Test reset running transform} failing
**Build Scans:**
- [elasticsearch-intake #13440 / part3](https://gradle-enterprise.elastic.co/s/cse4l6vxfuzdu)
- [elasticsearch-pull-request #42711 / part-3](https://gradle-enterprise.elastic.co/s/mr3ttm7gjvrq2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_reset/Test reset running transform}" -Dtests.seed=1A342F2D556AD414 -Dtests.locale=frr-Latn-DE -Dtests.timezone=America/Noronha -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_reset%2FTest%20reset%20running%20transform%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_reset:81]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-reset] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-reset] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:353)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:956)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\n"}],"type":"status_exception","reason":"Starting transform [airline-transform-start-reset] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-reset] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:353)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:956)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\n"},"status":408}]
```

**Issue Reasons:**
- [main] 2 failures in test test {p0=transform/transforms_reset/Test reset running transform} (0.3% fail rate in 724 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #119508: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Test start/stop/start transform} failing
**Build Scans:**
- [elasticsearch-intake #15178 / part3](https://gradle-enterprise.elastic.co/s/26u6lfkheoig2)
- [elasticsearch-pull-request #48662 / part-3](https://gradle-enterprise.elastic.co/s/bxaoavr7cpd4g)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Test start/stop/start transform}" -Dtests.seed=1C906710F8BFF22 -Dtests.locale=da -Dtests.timezone=Asia/Dushanbe -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_start_stop%2FTest%20start%2Fstop%2Fstart%20transform%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:211]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-stop] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:363)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:977)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\n"}],"type":"status_exception","reason":"Starting transform [airline-transform-start-stop] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:363)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:977)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\n"},"status":408}]
```

**Issue Reasons:**
- [main] 2 failures in test test {p0=transform/transforms_start_stop/Test start/stop/start transform} (0.7% fail rate in 287 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120019: [CI] XPackRestIT test {p0=transform/transforms_unattended/Test unattended put and start} failing
**Build Scans:**
- [elasticsearch-periodic #5807 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/o4dfj7yrdkqim)
- [elasticsearch-pull-request #50079 / rest-compatibility](https://gradle-enterprise.elastic.co/s/u6xw5ur7f45iq)
- [elasticsearch-pull-request #50078 / rest-compatibility](https://gradle-enterprise.elastic.co/s/a2kmzb5osk7fq)
- [elasticsearch-pull-request #49863 / rest-compatibility](https://gradle-enterprise.elastic.co/s/2ak3rh3wtzbqy)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_unattended/Test unattended put and start}" -Dtests.seed=33BC6A68D9500561 -Dtests.locale=en-JM -Dtests.timezone=Etc/GMT-2 -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_unattended%2FTest%20unattended%20put%20and%20start%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_unattended:59]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [transform-unattended] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [transform-unattended] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:363)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:977)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n"}],"type":"status_exception","reason":"Starting transform [transform-unattended] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [transform-unattended] timed out after [30s]\n\tat org.elasticsearch.transform@9.0.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:363)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:303)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:650)\n\tat org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:977)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n"},"status":408}]
```

**Issue Reasons:**
- [main] 4 failures in test test {p0=transform/transforms_unattended/Test unattended put and start} (0.9% fail rate in 439 executions)
- [main] 3 failures in step rest-compatibility (2.7% fail rate in 111 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.7% fail rate in 110 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120720: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Test schedule_now on an already started transform} failing
**Build Scans:**
- [elasticsearch-intake #16278 / part3](https://gradle-enterprise.elastic.co/s/psszsadvhdew4)
- [elasticsearch-pull-request #51072 / part-3](https://gradle-enterprise.elastic.co/s/4kquyq66jombe)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Test schedule_now on an already started transform}" -Dtests.seed=B92FB6FD3DB162FE -Dtests.locale=wae-CH -Dtests.timezone=America/Ensenada -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_start_stop%2FTest%20schedule_now%20on%20an%20already%20started%20transform%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:149]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-stop] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop] timed out after [30s]\n\tat org.elasticsearch.transform@8.18.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:364)\n\tat org.elasticsearch.server@8.18.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:206)\n\tat org.elasticsearch.server@8.18.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@8.18.0-SNAPSHOT/org.elasticsearch.cluster.ClusterSt
[truncated]
```

**Issue Reasons:**
- [8.x] 2 failures in test test {p0=transform/transforms_start_stop/Test schedule_now on an already started transform} (0.2% fail rate in 921 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123232: [CI] AbstractAuditorTests testRecreateTemplateWhenDeleted failing
**Build Scans:**
- [elasticsearch-intake #18706 / part2](https://gradle-enterprise.elastic.co/s/6kqkupesu2czu)
- [elasticsearch-periodic #6569 / openjdk23_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/auujnwmpqcnfs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:core:test" --tests "org.elasticsearch.xpack.core.common.notifications.AbstractAuditorTests.testRecreateTemplateWhenDeleted" -Dtests.seed=DD34B710ABFBEA79 -Dtests.locale=en-IL -Dtests.timezone=MIT -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.core.common.notifications.AbstractAuditorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRecreateTemplateWhenDeleted),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.mockito.exceptions.verification.TooFewActualInvocations: 
client.execute(
    indices:admin/index_template/put,
    <any>,
    <any>
);
Wanted 2 times:
-> at org.elasticsearch.xpack.core.common.notifications.AbstractAuditorTests.lambda$testRecreateTemplateWhenDeleted$7(AbstractAuditorTests.java:267)
But was 1 time:
-> at org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:56)

```

**Issue Reasons:**
- [8.18] 2 failures in test testRecreateTemplateWhenDeleted (1.3% fail rate in 154 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #125854: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Verify start transform creates destination index with appropriate mapping} failing
**Build Scans:**
- [elasticsearch-intake #20947 / part3](https://gradle-enterprise.elastic.co/s/m6yao7zlk23fe)
- [elasticsearch-pull-request #65202 / part-3](https://gradle-enterprise.elastic.co/s/qqeo3qoxv3k64)
- [elasticsearch-periodic #7265 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/rgzwdkbfzyido)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Verify start transform creates destination index with appropriate mapping}" -Dtests.seed=8E581B091C7F3A81 -Dtests.locale=pis-SB -Dtests.timezone=Asia/Chita -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_start_stop%2FVerify%20start%20transform%20creates%20destination%20index%20with%20appropriate%20mapping%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:175]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-stop] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop] timed out after [30s]\n\tat org.elasticsearch.transform@9.1.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:364)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:217)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateO
[truncated]
```

**Issue Reasons:**
- [main] 3 failures in test test {p0=transform/transforms_start_stop/Verify start transform creates destination index with appropriate mapping} (0.8% fail rate in 380 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126240: [CI] XPackRestIT test {p0=transform/transforms_reset/Test force reseting a running transform} failing
**Build Scans:**
- [elasticsearch-intake #21296 / part3](https://gradle-enterprise.elastic.co/s/czjzucc5oopz4)
- [elasticsearch-pull-request #65952 / part-3](https://gradle-enterprise.elastic.co/s/62fxb5nedxxr2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_reset/Test force reseting a running transform}" -Dtests.seed=5AD21B045ED1392C -Dtests.locale=seh-MZ -Dtests.timezone=Asia/Bangkok -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_reset%2FTest%20force%20reseting%20a%20running%20transform%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_reset:153]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-reset] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-reset] timed out after [30s]\n\tat org.elasticsearch.transform@9.1.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:364)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:217)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObse
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test test {p0=transform/transforms_reset/Test force reseting a running transform} (0.4% fail rate in 487 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126466: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Test start/stop only starts/stops specified transform} failing
**Build Scans:**
- [elasticsearch-intake #21522 / part3](https://gradle-enterprise.elastic.co/s/3htpjf64sgmaq)
- [elasticsearch-pull-request #66590 / part-3](https://gradle-enterprise.elastic.co/s/yfnagzwdapoik)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Test start/stop only starts/stops specified transform}" -Dtests.seed=BDC9EFF9066C8E03 -Dtests.locale=es-BO -Dtests.timezone=America/Argentina/Catamarca -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_start_stop%2FTest%20start%2Fstop%20only%20starts%2Fstops%20specified%20transform%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:377]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-stop-continuous] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop-continuous] timed out after [30s]\n\tat org.elasticsearch.transform@9.1.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:364)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:217)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test test {p0=transform/transforms_start_stop/Test start/stop only starts/stops specified transform} (0.4% fail rate in 525 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126755: [CI] XPackRestIT test {p0=transform/transforms_start_stop/Test start/stop/start continuous transform} failing
**Build Scans:**
- [elasticsearch-periodic #7636 / openjdk24_entitlements_true_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/ck4vfemfgt7ic)
- [elasticsearch-pull-request #67476 / part-3](https://gradle-enterprise.elastic.co/s/rx6nrupw6mu64)
- [elasticsearch-pull-request #67476 / rest-compatibility](https://gradle-enterprise.elastic.co/s/ecufnxgctxvp6)
- [elasticsearch-pull-request #67396 / part-3](https://gradle-enterprise.elastic.co/s/govh6cu2wwlci)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Test start/stop/start continuous transform}" -Dtests.seed=A644407939721FAD -Dtests.jvm.argline="-Des.entitlements.enabled=true" -Dtests.locale=en-ZM -Dtests.timezone=UCT -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dtransform%2Ftransforms_start_stop%2FTest%20start%2Fstop%2Fstart%20continuous%20transform%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [transform/transforms_start_stop:274]: expected [2xx] status code but api [transform.start_transform] returned [408 Request Timeout] [{"error":{"root_cause":[{"type":"status_exception","reason":"Starting transform [airline-transform-start-stop-continuous] timed out after [30s]","stack_trace":"org.elasticsearch.ElasticsearchStatusException: Starting transform [airline-transform-start-stop-continuous] timed out after [30s]\n\tat org.elasticsearch.transform@9.1.0-SNAPSHOT/org.elasticsearch.xpack.transform.action.TransportStartTransformAction$2.onTimeout(TransportStartTransformAction.java:364)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:217)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:390)\n\tat org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch
[truncated]
```

**Issue Reasons:**
- [main] 4 failures in test test {p0=transform/transforms_start_stop/Test start/stop/start continuous transform} (0.6% fail rate in 636 executions)
- [main] 2 failures in step part-3 (1.7% fail rate in 117 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 131 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by prwhelan**
Extended the YAML test framework with transform-specific logic to add a wait time around starting transforms, and moved the Transform YAML tests into the transform plugin to use the new framework.

This mimics what we do for inference.

Resolve #115808
Resolve #98802
Resolve #117473
Resolve #119508
Resolve #120019
Resolve #120720
Resolve #125854
Resolve #123232
Resolve #126240
Resolve #126466
Resolve #126755

### CODE REVIEW

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+                try {
+                    Request statsRequest = new Request("GET", "/_transform/" + transformId + "/_stats");
+                    Response statsResponse = adminClientSupplier.get().performRequest(statsRequest);
+                    Map<String, Object> body = XContentHelper.convertToMap(
+                        XContentType.JSON.xContent(),
+                        statsResponse.getEntity().getContent(),
+                        false
+                    );
+                    List<Map<String, Object>> transforms = (List<Map<String, Object>>) body.get("transforms");
+                    Map<String, Object> transformStats = transforms.get(0);
```
Comment (edsavage) [inline x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java]: I think we should be explicitly checking the size of the `transforms` list before calling `get(0)` here, to give a clearer idea of what failed.

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+    @SuppressWarnings("unchecked")
+    @Override
+    public void execute(ClientYamlTestExecutionContext executionContext) throws IOException {
+        delegate.execute(executionContext);
+
+        if (delegate.getCatch() != null) {
+            return;
+        }
+
+        String transformId = delegate.getApiCallSection().getParams().get("transform_id");
```
Comment (edsavage) [inline x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java:68]: Are we making the assumption that every transform test uses "transform_id" as a parameter? If so it might be worth double checking each usage of `transform.start_transform` in the affected tests.

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/TransformYamlRestIT.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+
+    private static Iterable<Object[]> wrapStartTransformWithWait(Iterable<Object[]> parameters) {
+        List<Object[]> result = new ArrayList<>();
+        for (Object[] orig : parameters) {
+            assert orig.length == 1;
+            ClientYamlTestCandidate candidate = (ClientYamlTestCandidate) orig[0];
+            var testSection = candidate.getTestSection();
+            List<ExecutableSection> updated = testSection.getExecutableSections().stream().map(section -> {
+                if (section instanceof DoSection doSection && "transform.start_transform".equals(doSection.getApiCallSection().getApi())) {
+                    return (ExecutableSection) new DoStartTransformAndWait(doSection, TransformYamlRestIT::adminClient);
```
Comment (edsavage) [inline x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/TransformYamlRestIT.java]: nit: `DoStartTransformAndWait` already implements `ExecutableSection` so I don't think the cast here is necessary.

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+                        return;
+                    }
+                    throw new AssertionError(
+                        "Transform [" + transformId + "] has not initialized yet (state=[stopped], no evidence of execution)"
+                    );
+                } catch (IOException e) {
+                    throw new AssertionError("Failed to get transform stats for [" + transformId + "]", e);
+                }
+            }, 30, TimeUnit.SECONDS);
+        } catch (Exception | AssertionError e) {
```
Comment (edsavage) [inline x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java]: This seems very broad in the sense that it just silently swallows _any_ kind of failure. If possible could this be narrowed to only catch when stats clearly indicate `completed empty batch`? 

Or maybe add a warning for the caught exceptions here?

**Review by edsavage — APPROVED** [review]
LGTM. Just a few nits

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java (hunk 2 above)
Comment (prwhelan) [reply x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java:68]: Yeah, that reads from this required path parameter: https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-transform-put-transform#operation-transform-put-transform-transform_id

I went through and verified that each start has it

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java (hunk 4 above)
Comment (prwhelan) [reply x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java]: I added a few different branches to help express what or where failures might be happening, let me know what you think and if it's okay to merge

**Review by edsavage — APPROVED** [review]
LGTM

File: x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java (hunk 4 above)
Comment (edsavage) [reply x-pack/plugin/transform/src/yamlRestTest/java/org/elasticsearch/xpack/transform/rest/DoStartTransformAndWait.java]: Thanks Pat. Looks all good to merge to me.
