### PR TITLE
Fix role mapping DN field wildcards for users with NULL DNs

### LINKED ISSUE #41305: Distinguished Name Predicate throws NPE for null user DN
The implementation of `DistinguishedNamePredicate` (https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/UserRoleMapper.java#L161) doesn't take into consideration that the user might have a `null` DN (user property) when a role mapping that uses a wildcard or regexp is in use and would possibly apply on that user. When [evaluating the rule](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/UserRoleMapper.java#L196), this causes an `NPE` in `org.apache.lucene.util.automaton.CharacterRunAutomaton`

This can be reproduced with a role mapping such as 
```
{
    "enabled" : true,
    "roles" : [
      "kibana_user"
    ],
    "rules" : {
      "field" : {
        "dn" : "*,ou=finance,dc=somethign,dc=com"
      }
    },
    "metadata" : { }
  }
```

and a i.e. SAML user in a realm that has no `attributes.dn` mapping rule in the configuration. The result is an uncaught NPE that causes the authentication to fail

### PR DESCRIPTION
**Pull request by albertzaharovits**
The `DistinguishedNamePredicate`, used for matching users to role mapping expressions, should handle users with `null` DNs. But it fails to do so (and this is a NPE bug), if the role mapping expression contains a lucene regexp or a wildcard.

Example stacktrace:
```
[WARN ][o.e.x.s.a.AuthenticationService] [02.server] An error occurred while attempting to authenticate [<unauthenticated-saml-user>] against realm [samlrealm]
java.lang.NullPointerException: null
        at org.apache.lucene.util.automaton.CharacterRunAutomaton.run(CharacterRunAutomaton.java:47) ~[lucene-core-7.7.0.jar:7.7.0 8c831daf4eb41153c25ddb152501ab5bae3ea3d5 - jimczi - 2019-02-04 23:16:28]
        at org.elasticsearch.xpack.security.authc.support.UserRoleMapper$DistinguishedNamePredicate.test(UserRoleMapper.java:197) ~[?:?]
        at org.elasticsearch.xpack.security.authc.support.UserRoleMapper$DistinguishedNamePredicate.test(UserRoleMapper.java:162) ~[?:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_191]
        at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_191]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_191]
        at org.elasticsearch.xpack.core.security.authc.support.mapper.expressiondsl.ExpressionModel.test(ExpressionModel.java:59) ~[?:?]
        at org.elasticsearch.xpack.core.security.authc.support.mapper.expressiondsl.FieldExpression.match(FieldExpression.java:62) ~[?:?]
        at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore.lambda$resolveRoles$10(NativeRoleMappingStore.java:359) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_191]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_191]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_191]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
```

The fix simplifies `DistinguishedNamePredicate` to not handle `null` DNs at all, and instead use the `ExpressionModel#NULL_PREDICATE` for the DN field, just like any other missing user field.

Closes https://github.com/elastic/elasticsearch/issues/41305

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/UserRoleMapper.java [hunk 1]
```diff
@@ -165,22 +169,19 @@ public RealmConfig getRealm() {
         private final DN dn;
 
         public DistinguishedNamePredicate(String string) {
+            //assert string != null : "DN string should not be null. Use the dedicated NULL_PREDICATE for every user null field.";
```
Comment (jkakavas) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/support/UserRoleMapper.java]: Uncomment?

**Review by jkakavas — APPROVED** [review]
LGTM @albertzaharovits ,thanks!
