### PR TITLE
Correct bounding box logic for GeometryCollection type

### LINKED ISSUE #9360: geo_shape query matches shapes inside hole of complex polygon
See the  gist at [1] for a visual example of the polygons involved and a script to reproduce the bug. The bug occurs when you index a document containing two simple polygons and then query for shape which intersect a polygon representing a ring around (but not touching) the two indexed shapes. The query returns the document when it shouldn't since neither of the shapes interact with the ring.

Changing the `relation` option to either `within` or `disjoint` produce no results from the query.

[1] https://gist.github.com/colings86/0a0184ba79c5367685ff

This bug was raised from the following mailing list post: https://groups.google.com/forum/#!topic/elasticsearch/TlqaVu91R7A

### PR DESCRIPTION
**Pull request by nknize**
"The OpenGIS Abstract Specification: An Object Model for Interoperable Geoprocessing" published by the OGC defines "The boundary of a geometric object is a set of geometric objects of the next lower dimension." The bounding box of a GeometryCollection is therefore the set of bounding rectangles derived from the geometric objects of the next lower dimension. This commit updates the computeBoundingBox and relate methods for the ShapeCollection base class to correctly determine the prefixTree detail level used in Lucene's FilterCellIterator.

closes #9360

### CODE REVIEW

File: src/main/java/org/elasticsearch/common/geo/GeometryCollection.java [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+    Rectangle retBox = shapes.iterator().next().getBoundingBox();
+    for (Shape geom : shapes) {
+      retBox = expandBBox(retBox, geom.getBoundingBox());
+    }
+    return retBox;
+  }
+
+  @Override
+  public SpatialRelation relate(Shape other) {
+    SpatialRelation bboxRelation;
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/common/geo/GeometryCollection.java]: I think this can be a local inside the loop?

File: src/main/java/org/elasticsearch/common/geo/GeometryCollection.java [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+      if (shapeRelation == CONTAINS) {
+        return CONTAINS;
+      }
+    }
+    return (shapeRelation == null) ? SpatialRelation.DISJOINT : shapeRelation;
+  }
+
+  /**
+   * Spatial4J shapes have no knowledge of directed edges. For this reason, a bounding box
+   * that wraps the dateline can have a min longitude that is mathematically > than the
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/common/geo/GeometryCollection.java]: I would use the word "greater" here instead of ">"

File: src/main/java/org/elasticsearch/common/geo/GeometryCollection.java [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+
+/**
+ *  Overrides bounding box logic in ShapeCollection base class to comply with
+ *  OGC OpenGIS Abstract Specification: An Object Model for Interoperable Geoprocessing.
+ *
+ *  This class also overrides the 'relate' method to leverage the updated bbox logic.
+ *  NOTE: This algorithm is O(N) and can possibly be improved O(log n) using an internal R*-Tree
+ *  data structure for a collection of bounding boxes
+ */
+public class GeometryCollection<S extends Shape> extends ShapeCollection<S> {
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/common/geo/GeometryCollection.java]: I think this should be XSpaceCollection if these changes will be going back into spatial4j?

File: src/main/java/org/elasticsearch/common/geo/GeometryCollection.java [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+  @Override
+  public SpatialRelation relate(Shape other) {
+    SpatialRelation bboxRelation;
+    SpatialRelation shapeRelation = null;
+    for (Shape geom : shapes) {
+      Rectangle bbox = geom.getBoundingBox();
+      bboxRelation = bbox.relate(other);
+      if (bboxRelation == SpatialRelation.DISJOINT) {
+        continue;
+      } else if (bboxRelation == SpatialRelation.WITHIN) {
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/common/geo/GeometryCollection.java]: As discussed, I think this logic is missing a more detailed check here.  If the other shape is within the bbox, it does not mean it is within the actual shape.

**Comment by rjernst** [comment]
I left a couple comments.  The only important one is about the relates logic.

**Comment by nknize** [comment]
Updated this PR per comments. Relate logic can be removed as per comment in latest commit 4d69e36

**Comment by rjernst** [comment]
@nknize LGTM. There is still a reference to `relate` in the javadocs of `XGeometryCollection`.  Also, is the plan to add something called `GeometryCollection` to spatial4j with this modified behavior, or to modify `ShapeCollection`?  If the latter, then I think this should be called `XShapeCollection`.
