### PR TITLE
Fix RecursiveChunkingSettings.validate() logic bug and add test coverage

### LINKED ISSUE #144815: [Inference API] RecursiveChunkingSettings does not correctly validate settings
The implementation of `RecursiveChunkingSetting.validate()` has a bug where the separators are only validated if `maxChunkSize` is less than `MAX_CHUNK_SIZE_LOWER_LIMIT`:
```
public void validate() {
    ValidationException validationException = new ValidationException();

    if (maxChunkSize < MAX_CHUNK_SIZE_LOWER_LIMIT) {
        validationException.addValidationError(
            ChunkingSettingsOptions.MAX_CHUNK_SIZE + "[" + maxChunkSize + "] must be above " + MAX_CHUNK_SIZE_LOWER_LIMIT
        );

        if (separators != null && separators.isEmpty()) {
            validationException.addValidationError("Recursive chunking settings can not have an empty list of separators");
        }

        validationException.throwIfValidationErrorsExist();
    }
}
```
There is also no test coverage for any of the implementations of the `validate()` method for `RecursiveChunkingSettings`, `SentenceBoundaryChunkingSettings` or `WordBoundaryChunkingSettings`.

This is not a major issue, since validation of user-specified chunking settings is performed in the `fromMap()` methods rather than via the `validate()` method, but the bug should still be addressed and test coverage added. Some duplication of logic could also be reduced if validation was only performed in one place, rather than having both `fromMap()` and `validate()` doing the same checks.

### PR DESCRIPTION
**Pull request by sachinnn99**
## Summary
- Fix logic bug in `RecursiveChunkingSettings.validate()` where separator validation and `throwIfValidationErrorsExist()` were nested inside the `maxChunkSize < MAX_CHUNK_SIZE_LOWER_LIMIT` if-block, so they never ran when maxChunkSize was valid
- Move both out of the if-block to match the correct pattern used by `SentenceBoundaryChunkingSettings` and `WordBoundaryChunkingSettings`
- Add direct `validate()` test coverage for all three chunking settings implementations (as noted missing in the issue)

Closes #144815

## Test plan
- [x] `RecursiveChunkingSettingsTests` — 4 new validate() tests (valid settings, invalid maxChunkSize, empty separators, both invalid)
- [x] `SentenceBoundaryChunkingSettingsTests` — 4 new validate() tests (valid settings, invalid maxChunkSize, invalid sentenceOverlap, both invalid)
- [x] `WordBoundaryChunkingSettingsTests` — 4 new validate() tests (valid settings, invalid maxChunkSize, overlap too large, both invalid)
- [x] All existing tests continue to pass

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java [hunk 1]
```diff
@@ -72,6 +74,30 @@ public void testFromMapBothSeparatorsAndSeparatorGroup() {
...
 
+    public void testValidateWithValidSettings() {
+        var settings = new RecursiveChunkingSettings(randomIntBetween(10, 300), List.of("\n\n", "\n"));
+        settings.validate(); // should not throw
+    }
+
+    public void testValidateWithInvalidMaxChunkSize() {
+        var settings = new RecursiveChunkingSettings(randomIntBetween(0, 9), List.of("\n\n", "\n"));
+        var e = assertThrows(ValidationException.class, settings::validate);
+        assertThat(e.getMessage(), containsString("must be above"));
```
Comment (DonalEvans) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java]: To give the test a little extra strength and make sure that the error we return is correct, could we make the `RecursiveChunkingSettings.MAX_CHUNK_SIZE_LOWER_LIMIT` constant package-private and then change the test to be:
```
var invalidMaxChunkSize = randomIntBetween(0, MAX_CHUNK_SIZE_LOWER_LIMIT - 1);
var settings = new RecursiveChunkingSettings(, List.of("\n\n", "\n"));
var e = assertThrows(ValidationException.class, settings::validate);
assertThat(e.getMessage(), containsString(Strings.format("max_chunk_size [%s] must be above %s", invalidMaxChunkSize, MAX_CHUNK_SIZE_LOWER_LIMIT)));
```
Looking at the implementation of `RecursiveChunkingSettings.validate()`, I think the above test will actually fail right now, because the error message we're creating is missing a space after "max_chunk_size", so that's something that should probably be fixed too, if you wouldn't mind.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java [hunk 2]
```diff
@@ -72,6 +74,30 @@ public void testFromMapBothSeparatorsAndSeparatorGroup() {
...
+    }
+
+    public void testValidateWithEmptySeparators() {
+        var settings = new RecursiveChunkingSettings(randomIntBetween(10, 300), List.of());
```
Comment (DonalEvans) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java]: By changing `RecursiveChunkingSettings.MAX_CHUNK_SIZE_LOWER_LIMIT` to be package-private, this can be changed to reference it directly:
```
var settings = new RecursiveChunkingSettings(randomIntBetween(MAX_CHUNK_SIZE_LOWER_LIMIT, 300), List.of());
```

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java [hunk 3]
```diff
@@ -72,6 +74,30 @@ public void testFromMapBothSeparatorsAndSeparatorGroup() {
...
+        var e = assertThrows(ValidationException.class, settings::validate);
+        assertThat(e.getMessage(), containsString("can not have an empty list of separators"));
+    }
+
+    public void testValidateWithInvalidMaxChunkSizeAndEmptySeparators() {
+        var settings = new RecursiveChunkingSettings(randomIntBetween(0, 9), List.of());
+        var e = assertThrows(ValidationException.class, settings::validate);
+        assertThat(e.getMessage(), containsString("must be above"));
```
Comment (DonalEvans) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java]: The comments about being more specific about the exact error message we return also apply to this test.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java [hunk 4]
```diff
@@ -72,6 +74,30 @@ public void testFromMapBothSeparatorsAndSeparatorGroup() {
         assertThrows(ValidationException.class, () -> RecursiveChunkingSettings.fromMap(invalidSettings));
     }
 
+    public void testValidateWithValidSettings() {
+        var settings = new RecursiveChunkingSettings(randomIntBetween(10, 300), List.of("\n\n", "\n"));
```
Comment (DonalEvans) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/RecursiveChunkingSettingsTests.java]: By changing `RecursiveChunkingSettings.MAX_CHUNK_SIZE_LOWER_LIMIT` to be package-private, this can be changed to reference it directly:
```
var settings = new RecursiveChunkingSettings(randomIntBetween(MAX_CHUNK_SIZE_LOWER_LIMIT, 300), List.of("\n\n", "\n"));
```
It might also be worth adding a test that explicitly checks that `MAX_CHUNK_SIZE_LOWER_LIMIT` doesn't cause a validation error, since with the current implementations, there's only about a 1/300 chance of picking that specific value. If someone changed the validation logic to be `<=` instead of `<`, we very likely wouldn't see a test failure for quite a while if we weren't testing the boundary value explicitly.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/SentenceBoundaryChunkingSettingsTests.java [hunk 5]
```diff
@@ -33,6 +35,30 @@ public void testInvalidInputsProvided() {
         assertThrows(ValidationException.class, () -> { SentenceBoundaryChunkingSettings.fromMap(chunkingSettingsMap); });
     }
 
+    public void testValidateWithValidSettings() {
+        var settings = new SentenceBoundaryChunkingSettings(randomIntBetween(20, 300), randomFrom(0, 1));
```
Comment (DonalEvans) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/SentenceBoundaryChunkingSettingsTests.java]: Similar comments to the ones on `RecursiveChunkingSettingsTests` apply regarding explicitly testing the boundary value, replacing hard-coded values with references to the `SentenceBoundaryChunkingSettings.MAX_CHUNK_SIZE_LOWER_LIMIT` constant, and being more explicit about the format of the error message when `maxChunkSize` is an invalid value.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/WordBoundaryChunkingSettingsTests.java [hunk 6]
```diff
@@ -47,6 +49,32 @@ public void testOverlapGreaterThanHalfMaxChunkSize() {
         });
     }
 
+    public void testValidateWithValidSettings() {
```
Comment (DonalEvans) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/inference/chunking/WordBoundaryChunkingSettingsTests.java:54]: Similar comments to the ones on `RecursiveChunkingSettingsTests` apply regarding explicitly testing the boundary value, replacing hard-coded values with references to the `WordBoundaryChunkingSettings.MAX_CHUNK_SIZE_LOWER_LIMIT` constant, and being more explicit about the format of the error message when `maxChunkSize` is an invalid value.

**Review by DonalEvans — CHANGES_REQUESTED** [review]

**Review by DonalEvans — APPROVED** [review]
