### PR TITLE
Fix ClassCastException in Significant Terms

### LINKED ISSUE #108427: ClassCastException in SignificantTermsAggregation
### Elasticsearch Version

main, and at least back to 8.10

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

ClassCastException when running SignificantTerms aggregation on fields with the same name and different types

### Steps to Reproduce

```
PUT /index1
{
  "mappings": {
    "properties": {
      "field":    { "type": "long" }
    }
  }
}

PUT /index2
{
  "mappings": {
    "properties": {
      "field":    { "type": "keyword" }
    }
  }
}

POST index1/_doc
{
   "field":  [1, 10]
}

POST index2/_doc
{
   "field":  ["1", "x"]
}


GET index*/_search
{
  "size": 0,
  "aggs": {
    "st": {
      "significant_terms": {
        "field": "field"
      }
    }
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by not-napoleon**
Resolves https://github.com/elastic/elasticsearch/issues/108427

Prior to this PR, if a `SignificantTerms` aggregation targeted a field existing on two indices (that were included in the aggregation) but mapped to different field types, the query would fail at reduce time with a somewhat obscure `ClassCastException`.  This change brings the behavior in line with the `Terms` aggregation, which returns a 400 class `IllegalArgumentException` with a useful message in this situation.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalSignificantTerms.java [hunk 1]
```diff
@@ -208,10 +210,18 @@ protected AggregatorReducer getLeaderReducer(AggregationReduceContext reduceCont
                 reduceContext.bigArrays()
             );
 
+            private InternalAggregation referenceAgg = null;
+
             @Override
             public void accept(InternalAggregation aggregation) {
                 @SuppressWarnings("unchecked")
                 final InternalSignificantTerms<A, B> terms = (InternalSignificantTerms<A, B>) aggregation;
+                if (referenceAgg == null) {
```
Comment (iverase) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalSignificantTerms.java:219]: You need to skip Unmapped fields. Adding at the beginning should be enough:
```
             if (aggregation.canLeadReduction() == false) {
                    return;
                }
```

**Review by iverase — APPROVED** [review]
