### PR TITLE
Fix validate_* merge policy for GeoPointFieldMapper

### LINKED ISSUE #10164: [GEO] GeoPointFieldMapper.validate_* overwritten on merge
During a merge the ```validate_lat``` and ```validate_lon``` parameters for the ```geo_point``` field mapper are being overwritten by the incoming field mappings.  This can cause problems during search where invalid geo_points (which were formerly acceptable) are no longer acceptable causing exceptions when parsing the (now invalid) geo points.

### PR DESCRIPTION
**Pull request by nknize**
Fail merge if validate_lat or validate_lon values are not equal. This will prevent inconsistencies between geo_points in a merged index, and parse exceptions for bounding_box and distance filters.

Also merged separate GeoPoint test classes into a single GeoPointFieldMapperTest to be consistent with GeoShapeFieldMapperTests.

closes #10164

### CODE REVIEW

**Comment by s1monw** [comment]
@rjernst can you take a look at this please?

File: src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java [hunk 1]
```diff
@@ -413,4 +468,31 @@ public void testLonLatArrayArrayStored() throws Exception {
...
+    public void testGeoPointMapperMerge() throws Exception {
+        String stage1Mapping = XContentFactory.jsonBuilder().startObject().startObject("type")
+                .startObject("properties").startObject("point").field("type", "geo_point").field("lat_lon", true).field("geohash", true)
+                .field("validate", true).field("normalize", true).endObject().endObject()
+                .endObject().endObject().string();
+        DocumentMapperParser parser = createIndex("test").mapperService().documentMapperParser();
+        DocumentMapper stage1 = parser.parse(stage1Mapping);
+        String stage2Mapping = XContentFactory.jsonBuilder().startObject().startObject("type")
+                .startObject("properties").startObject("point").field("type", "geo_point").field("lat_lon", true).field("geohash", true)
+                .field("validate", false).field("normalize", false).endObject().endObject()
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java]: why change normalize to false here? aren't you just trying to check validate?

File: src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java [hunk 2]
```diff
@@ -413,4 +468,31 @@ public void testLonLatArrayArrayStored() throws Exception {
...
+                .endObject().endObject().string();
+        DocumentMapper stage2 = parser.parse(stage2Mapping);
+
+        DocumentMapper.MergeResult mergeResult = stage1.merge(stage2, mergeFlags().simulate(false));
+        assertThat(mergeResult.hasConflicts(), equalTo(true));
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java]: I think we should check the conflicts?

**Comment by rjernst** [comment]
LGTM, just two tiny comments. Thanks for merging these test suites!

File: src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java (hunk 1 above)
Comment (nknize) [inline src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java]: correct. normalize will be changing in a separate PR. I must have accidentally included it in this one. :)  Made changes.

File: src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java (hunk 2 above)
Comment (nknize) [inline src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java]: Added a check.  Let me know if there's a better way.

Comment (rjernst) [inline src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java]: I don't know of a better way right now, although you could, if you want, do a contains check instead of exact equality? So maybe just look for `"different validate_lat"`?

Comment (nknize) [inline src/test/java/org/elasticsearch/index/mapper/geo/GeoPointFieldMapperTests.java]: updated to simplify
