### PR TITLE
ESQL: Disallow remote enrich after lu join

### LINKED ISSUE #129372: java.lang.ClassCastException when combining LOOKUP JOIN and remote ENRICH
### Elasticsearch Version

main/9.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

*

### Problem Description

The `LOOKUP JOIN` query fails when the lookup operator is combined with ENRICH. 

### Steps to Reproduce

The query is:
```
FROM test191 | EVAL language_code = "1" | LOOKUP JOIN test-lookup191 ON color.keyword | ENRICH _remote:lang_r 
```
Where `test191` is the `test` index from [191_lookup_join_text.yml](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/191_lookup_join_text.yml) and  `test-lookup191` is the lookup index from the same test and `lang_r` is enrich policy with `language_code` and the key. 

This produces the following exception on main:
```
2025-06-12T16:03:09,790][WARN ][o.e.x.e.a.EsqlResponseListener] [node-1] ESQL request failed with status [INTERNAL_SERVER_ERROR]: java.lang.ClassCastException: class org.elasticsearch.xpack.esql.plan.physical.ProjectExec cannot be cast to class org.elasticsearch.xpack.esql.plan.physical.EsQueryExec (org.elasticsearch.xpack.esql.plan.physical.ProjectExec and org.elasticsearch.xpack.esql.plan.physical.EsQueryExec are in unnamed module of loader java.net.URLClassLoader @357c9bd9)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLookupJoin(LocalExecutionPlanner.java:719)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:294)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLimit(LocalExecutionPlanner.java:838)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:259)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:387)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:298)
	at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:217)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:582)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.executePlan(ComputeService.java:406)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.execute(ComputeService.java:198)
	at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$innerExecute$3(TransportEsqlQueryAction.java:236)
	at org.elasticsearch.xpack.esql.session.EsqlSession.executeSubPlans(EsqlSession.java:248)
	at org.elasticsearch.xpack.esql.session.EsqlSession.executeOptimizedPlan(EsqlSession.java:213)
	at org.elasticsearch.xpack.esql.session.EsqlSession$1.lambda$onResponse$0(EsqlSession.java:190)
	at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.xpack.esql.planner.premapper.PreMapper.lambda$preMapper$0(PreMapper.java:33)
	at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.xpack.esql.expression.function.fulltext.QueryBuilderResolver.resolveQueryBuilders(QueryBuilderResolver.java:50)
	at org.elasticsearch.xpack.esql.planner.premapper.PreMapper.queryRewrite(PreMapper.java:38)
	at org.elasticsearch.xpack.esql.planner.premapper.PreMapper.preMapper(PreMapper.java:31)
	at org.elasticsearch.xpack.esql.session.EsqlSession$1.onResponse(EsqlSession.java:187)
	at org.elasticsearch.xpack.esql.session.EsqlSession$1.onResponse(EsqlSession.java:184)
	at org.elasticsearch.xpack.esql.session.EsqlSession.analyzeAndMaybeRetry(EsqlSession.java:549)
```

The log with the plans can be seen here: https://gist.github.com/smalyshev/22dea5574e516ef499d37556d6a61d6f

The basic problem IMHO is that there is a problem in processing LookupJoin when it is on the remote side (inside `FragmentExec`). I have had problems with "Duplicate name ids are not allowed" in `Layout.java` but when trying to construct the reduced example of this I've also discovered this issue. By default a lot of mapping operations leave `LookupJoin` to execute on coordinator side of the computation - due to this check: 
```java
if (left instanceof FragmentExec fragment) {
                return new FragmentExec(bp);
}
```
which often fails when `FragmentExec` is not the immediate child of `LookupJoin` (same issue we dealt with when working on remote ENRICH) but if I manage to force it on the `FragmentExec` side, other problems start. 

The test above is constructed to test duplicate fields (both test191 and test-lookup191 have `color` and `description` fields) but it looks like current code fails even before getting to the remote side. 

### Logs (if relevant)

https://gist.github.com/smalyshev/22dea5574e516ef499d37556d6a61d6f

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/129372

Due to how remote ENRICH is [planned](https://github.com/elastic/elasticsearch/blob/32e50d0d94e27ee559d24bf9d5463ba6e64d1788/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java#L93), it interacts in special ways with pipeline breakers, in particular LIMIT and TopN; when these are encountered upstream from a remote ENRICH, these nodes are copied and executed a second time after the remote ENRICH.

We'd like to allow remote ENRICH after LOOKUP JOIN, but that forces the lookup to be remote as well; this has its own interactions with pipeline breakers: in particular, LIMITs and TopNs cannot just be duplicated after LOOKUP JOIN, as LOOKUP JOIN may add new rows.

For now, let's just forbid any usage of remote ENRICH after LOOKUP JOINs; remote ENRICH is mostly relevant for CCS, and LOOKUP JOIN doesn't support that in 9.1/8.19, anyway.

There is separate work that enables remote LOOKUP JOINs on remote clusters and adds the correct validations; we can later build support for remote ENRICH + LOOKUP JOIN on top of that. (C.f. my comment [here](https://github.com/elastic/elasticsearch/issues/129372#issuecomment-3083024230) and my draft https://github.com/elastic/elasticsearch/pull/131286 for enabling this.)

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 1]
```diff
@@ -2343,7 +2348,60 @@ public void testRemoteLookupJoinIsDisabled() {
...
+            "mapping-languages.json"
+        );
+        var analyzer = AnalyzerTestUtils.analyzer(
+            loadMapping("mapping-default.json", "test"),
+            defaultLookupResolution(),
+            enrichResolution,
+            TEST_VERIFIER
+        );
+
+        query("""
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:2435]: I think we don't have the same tests for `STATS + remote ENRICH` and for `coordinator ENRICH + remote ENRICH`, IMHO it's worth adding them.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java [hunk 2]
```diff
@@ -295,23 +296,43 @@ public BiConsumer<LogicalPlan, Failures> postAnalysisPlanVerification() {
...
+
+    /**
+     * For a given remote {@link Enrich}, check if there are any forbidden plans upstream.
+     */
+    private static void checkForPlansForbiddenBeforeRemoteEnrich(Enrich enrich, Failures failures) {
+        if (enrich.mode != Mode.REMOTE) {
+            return;
+        }
+
+        // TODO: shouldn't we also include FORK? Everything downstream from FORK should be coordinator-only.
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:312]: I'm not completely sure, but if FORK needs merging on the coordinator, then we definitely want it here.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 3]
```diff
@@ -4773,3 +4773,101 @@ FROM sample_data_ts_nanos
...
+lookupJoinAfterTopNAndRemoteEnrich
+required_capability: join_lookup_v12
+
+FROM sample_data
+| KEEP message
+| WHERE message == "Connected to 10.1.0.1"
+| EVAL language_code = "1"
+| SORT message
+| LIMIT 1
+| ENRICH _remote:languages_policy ON language_code
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:4861]: Same here, it would be good to have some tests with `ENRICH _remote: | STATS` and `ENRICH _remote: | ENRICH`.

Actually, if I'm not mistaken, these are the only spec tests we have for `ENRICH _remote`, and they are in `lookup-join.csv-spec`... If we add more, probably it's worth putting them in their own file.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 4]
```diff
@@ -2343,7 +2348,60 @@ public void testRemoteLookupJoinIsDisabled() {
...
+            | EVAL language_code = languages
+            | ENRICH _remote:languages ON language_code
+            | LOOKUP JOIN languages_lookup ON language_code
+            """, analyzer);
+
+        String err = error("""
+            FROM test
+            | EVAL language_code = languages
+            | LOOKUP JOIN languages_lookup ON language_code
+            | ENRICH _remote:languages ON language_code
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: In all these cases, ENRICH overwrites attributes generated by LOOKUP JOIN (`language_name` in this case).

If it were not the case, a smarter planner could swap the two and make the query executable again.

Taking an example from the csv-spec tests, these two would be equivalent

```
FROM sample_data
| KEEP message
| WHERE message == "Connected to 10.1.0.1"
| EVAL language_code = "1"
| LOOKUP JOIN message_types_lookup ON message
| ENRICH _remote:languages_policy ON language_code
```

```
FROM sample_data
| KEEP message
| WHERE message == "Connected to 10.1.0.1"
| EVAL language_code = "1"
| ENRICH _remote:languages_policy ON language_code
| LOOKUP JOIN message_types_lookup ON message
```

but now the first one is not executable, while the second one runs just fine.

I'm not sure if we want to add this case here, as it would start failing as soon as we implement this swap. 
Maybe we don't, up to you. We could open an issue about this though.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java [hunk 5]
```diff
@@ -87,7 +87,7 @@ private PhysicalPlan mapUnary(UnaryPlan unary) {
         PhysicalPlan mappedChild = map(unary.child());
 
         //
-        // TODO - this is hard to follow and needs reworking
+        // TODO - this is hard to follow, causes bugs and needs reworking
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java:90]: 👍

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java [hunk 6]
```diff
@@ -295,23 +296,43 @@ public BiConsumer<LogicalPlan, Failures> postAnalysisPlanVerification() {
...
-                }
+                aggregate[0] = true;
+            } else if (u instanceof Enrich upstreamEnrich && upstreamEnrich.mode() == Enrich.Mode.COORDINATOR) {
+                coordinatorOnlyEnrich[0] = true;
+            } else if (u instanceof LookupJoin) {
+                lookupJoin[0] = true;
             }
         });
+
+        if (aggregate[0]) {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:328]: If we add new commands (FORK?) to this list, maybe we can start considering the creation of a flag interface to identify them (similar to current `PipelineBreaker`, but it's not exactly the same thing), and avoid the list of `instanceof`

**Review by luigidellaquila — APPROVED** [review]
Thanks Alex, LGTM.

I left a few comments, especially about improvements we can do in test coverage.

One more thing we can do is add `ENRICH _remote:` to the generative tests, but that's something we can do in a follow-up PR

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java (hunk 2 above)
Comment (smalyshev) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:312]: Why does `FORK` need to be on coordinator always? I mean, if that's currently the case then yes, we must respect it here and provide the check for it, but if the clauses inside `FORK` are not coordinator-only (like `STATS`) in general why there should be the coordinator stage? Maybe I don't understand the semantics of it yet.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java (hunk 6 above)
Comment (smalyshev) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:328]: I think having an interface that identifies the "not remotable" components would be nice, however it may be tricky because some operations may depend on options (like Enrich itself which can be "coordinator" or "remote" or "any"). Still, it might save some effort for simpler operations.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java (hunk 4 above)
Comment (smalyshev) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: I imagine though in 9.2 the former query will become executable too, so there's no need really to rewrite it, and we'd probably not backport the optimization that enables it to 9.1 so by that time the point would be moot? However, *if* we wanted to get that optimization into 9.1.x that would be possible way to go, I'm just not sure whether it's worth it.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java [hunk 7]
```diff
@@ -295,23 +296,43 @@ public BiConsumer<LogicalPlan, Failures> postAnalysisPlanVerification() {
      * retaining the originating cluster and restructing pages for routing, which might be complicated.
      */
     private static void checkRemoteEnrich(LogicalPlan plan, Failures failures) {
-        boolean[] agg = { false };
-        boolean[] enrichCoord = { false };
+        // First look for remote ENRICH, and then look at its children. Going over the whole plan once is trickier as remote ENRICHs can be
+        // in separate FORK branches which are valid by themselves.
+        plan.forEachUp(Enrich.class, enrich -> { checkForPlansForbiddenBeforeRemoteEnrich(enrich, failures); });
```
Comment (smalyshev) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java]: Just `enrich -> checkForPlansForbiddenBeforeRemoteEnrich(enrich, failures)` maybe for readability?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java (hunk 2 above)
Comment (smalyshev) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:312]: Since FORK is 9.1+ though, it may be easier to take care of it in a separate pull.  And maybe even not mention FORK if we're merging it down to 8.18, otherwise somebody reading 8.18 branch code could be quite confused.

**Review by smalyshev — APPROVED** [review]

**Comment by smalyshev** [comment]
LGTM in general, added some thoughts & nitpicks inline.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:312]: I'm not familiar enough with FORK to make a quick call, so I think it's best if that is handled separately and I opened https://github.com/elastic/elasticsearch/issues/131445 to track it.

That said, the javadoc [here](https://github.com/elastic/elasticsearch/blob/d637927e3d4db6d2f5f7bbf3c70ea36493c861b9/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java#L78-L86) implies that the nodes after a FORK all execute on the coordinator, making FORK actually a pipeline breaker.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java (hunk 6 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/Enrich.java:328]: Agree. We've come across this when working on remote LOOKUP JOINs, already, see my comment [here](https://github.com/elastic/elasticsearch/pull/129013#discussion_r2182716000). I think we may want to refine the concept of pipeline breakers as part of improving remote ENRICH in https://github.com/elastic/elasticsearch/issues/115897. I'll add a comment there to track these observations :)

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java (hunk 4 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: One approach of making the remote ENRICH planning sane is to implement an optimizer rule that tries to push down remote ENRICH super aggressively, so it ends up on the data node naturally. Not sure it's the one we'll settle on, though, but we'll probably not backport it to 9.1.

But more test cases is always better :) Nice observation! I'll add some.

**Comment by alex-spies** [comment]
Thanks for the reviews @luigidellaquila and @smalyshev , very helpful feedback!

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/131533)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/131534)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/131535)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/131537)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
