### PR TITLE
[ML] refactoring lazy query and agg parsing

### LINKED ISSUE #39528: bool.max_clause_count is ignored in default distribution
Hi there !

When i'm trying to index a percolate query (query string with a lot of OR clauses), the server fails with max_clause_count error :

```
"caused_by": {
   "type": "too_many_clauses",
   "reason": "maxClauseCount is set to 1024"
}
```

I raised the ```indices.query.bool.max_clause_count``` value in configuration, restarted, checked the /_nodes entrypoint : 

```
"indices": {
  "query": {
    "bool": {
      "max_clause_count": "10240"
    }
  }
}
```

But this parameter is ignored during percolate indexation... 

Thx

Version : **6.6.1 (docker)**

### PR DESCRIPTION
**Pull request by benwtrent**
This is a refactor that removes the local creation of a SearchModule when lazily parsing DatafeedConfig queries and aggregations. Serialization is a bit tricky between versions. I am handling non-bug fixed released versions in 6.6 (put 6.6.2, but it may be .3) but that may not be necessary. I am still working through the situations (need to write tests, thus draft PR).

closes https://github.com/elastic/elasticsearch/issues/39528

### CODE REVIEW

**Review by davidkyle — COMMENTED** [review]
Looks good, extracting the lazy parsing out is a nice change

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 1]
```diff
@@ -627,74 +864,37 @@ public void setFrequency(TimeValue frequency) {
...
-                }
-
-                if (lenient) {
-                    logger.warn(msg, ex);
-                } else {
-                    throw ExceptionsHelper.badRequestException(msg, ex);
-                }
+                this.queryProvider = QueryProvider.fromParsedQuery(queryBuilder);
+            } catch (IOException exception) {
+                // eat exception as it should never happen
```
Comment (droberts195) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: It doesn't hurt to log it as an error and just not rethrow.  If the exception never happens then nothing will ever be logged...

Same in `setParsedAggregations` below.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedUpdate.java [hunk 2]
```diff
@@ -169,14 +171,17 @@ public void writeTo(StreamOutput out) throws IOException {
...
         }
         if (out.getVersion().before(Version.V_7_1_0)) {
-            out.writeOptionalNamedWriteable(lazyQueryParser.apply(query, id, new ArrayList<>()));
-            out.writeOptionalWriteable(lazyAggParser.apply(aggregations, id, new ArrayList<>()));
-        } else {
-            out.writeMap(query);
-            out.writeBoolean(aggregations != null);
-            if (aggregations != null) {
-                out.writeMap(aggregations);
+            out.writeBoolean(queryProvider != null);
```
Comment (droberts195) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedUpdate.java]: This is a breach of encapsulation for `writeOptionalNamedWriteable` - you're reproducing its internal logic here.  You'll get away with it in this case because its internal implementation is constrained by the need for BWC, but I think it would be better practice to keep using `writeOptionalNamedWriteable` as follows:

```
    out.writeOptionalNamedWriteable((queryProvider != null) ? queryProvider.getParsedQuery() : null);
```

And the same for `aggProvider` below if possible.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedUpdateTests.java [hunk 3]
```diff
@@ -314,31 +294,30 @@ protected DatafeedUpdate mutateInstance(DatafeedUpdate instance) {
...
-                boolQuery.put("must", instance.getQuery());
+            try {
+                BoolQueryBuilder query = new BoolQueryBuilder();
+                if (instance.getQuery() != null) {
+                    query.must(instance.getParsedQuery(xContentRegistry()));
+                }
+                query.filter(new TermQueryBuilder(randomAlphaOfLengthBetween(1, 10), randomAlphaOfLengthBetween(1, 10)));
+                builder.setQuery(DatafeedConfig.QueryProvider.fromParsedQuery(query));
+            } catch (IOException ex) {
+                fail(ex.getMessage());
```
Comment (droberts195) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedUpdateTests.java]: You'll get better error logging if you simply let the `IOException` propagate out of the method - that will log the whole stack trace, not just the message.  The base class signature of `mutateInstance` allows for it to throw an `IOException`, so just add that to the `throws` clause for this method and remove the two `catch (IOException ex)` blocks from this method.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 4]
```diff
@@ -241,14 +215,26 @@ public DatafeedConfig(StreamInput in) throws IOException {
...
-            this.query = QUERY_TRANSFORMER.toMap(in.readNamedWriteable(QueryBuilder.class));
-            this.aggregations = AGG_TRANSFORMER.toMap(in.readOptionalWriteable(AggregatorFactories.Builder::new));
+            this.queryProvider = QueryProvider.fromParsedQuery(in.readNamedWriteable(QueryBuilder.class));
+            AggregatorFactories.Builder aggs = in.readOptionalWriteable(AggregatorFactories.Builder::new);
+            if (aggs == null) {
+                this.aggProvider = null;
+            } else {
+                this.aggProvider = AggProvider.fromParsedAggs(aggs);
+            }
+        } else if (in.getVersion().before(Version.V_6_6_2)) {
```
Comment (droberts195) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: 6.6.2 is already past feature freeze.  This fix is not considered a blocker, so it would be dangerous to assume it will go into 6.6.2.  Unfortunately there's currently no `V_6_6_3` constant.  Therefore I think it's best to change the condition to `in.getVersion().after(Version.V_6_6_2)`, flip the `if` and `else` blocks around and hold off backporting to the 6.6 branch until after 6.6.2 is released.

Same for `writeTo` below.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 5]
```diff
@@ -403,13 +414,47 @@ public void writeTo(StreamOutput out) throws IOException {
...
+                    throw (IOException) aggProvider.parsingException;
+                } else if (aggProvider.parsingException != null){
+                    throw new ElasticsearchException(aggProvider.parsingException);
+                } else {
+                    aggProvider.parsedAggs.writeTo(out);
+                }
+            }
+        } else if (out.getVersion().before(Version.V_6_6_2)) {
+            // If we hit this situation, where the other node supports lazy parsing, but not storing the exception
+            // We should err on the side of failure query is invalid anyways
```
[the remark this answers is not in the document]
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: @davidkyle the reverse COULD work I suppose...I still need to think about this bwc serialization, it has did my head in and needed to sleep on it :D

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 6]
```diff
@@ -310,62 +294,89 @@ public Integer getScrollSize() {
...
-        return aggregations;
+        return aggProvider == null ? null : aggProvider.aggs;
     }
 
     /**
      * Returns the histogram's interval as epoch millis.
      */
-    public long getHistogramIntervalMillis() {
-        return ExtractorUtils.getHistogramIntervalMillis(getParsedAggregations());
+    public long getHistogramIntervalMillis(NamedXContentRegistry namedXContentRegistry) {
```
[the remark this answers is not in the document]
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: @davidkyle, yeah somehow storing it won't really work as we then have to continue to serialize it around. I initially thought of setting it somehow on parsing it, but there are a couple of problems that may arise:

* Different nodes having different plugins?
* How do we even get it to be stored in the object to begin with? (Sneaky side-effect of keeping a copy from the parser?)

Injection is more deliberate, but causes a larger refactor.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 7]
```diff
@@ -310,62 +294,89 @@ public Integer getScrollSize() {
...
+        }
+    }
+
+    Exception getQueryParsingException() {
+        return queryProvider == null ? null : queryProvider.parsingException;
     }
 
     /**
-     * Calls the lazy parser and returns any gathered deprecations
+     * Calls the parser and returns any gathered deprecations
```
[the remark this answers is not in the document]
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: yessir :D

**Review by droberts195 — COMMENTED** [review]
Thanks for making this extremely fiddly change.

One more thing that I think is worth doing is to add a Javadoc comment to the constructor of `SearchModule` to say that although a lot of test code constructs a dummy object in production code it must only be constructed with an accurate `settings` because the constructor sets `static` flags in Lucene.  That might stop someone else making the same mistake in future.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 8]
```diff
@@ -310,62 +294,89 @@ public Integer getScrollSize() {
...
 
-    public QueryBuilder getParsedQuery() {
-        return querySupplier.get();
+    public QueryBuilder getParsedQuery(NamedXContentRegistry namedXContentRegistry) {
+        return parseQuery(namedXContentRegistry, new ArrayList<>());
+    }
+
+    private QueryBuilder parseQuery(NamedXContentRegistry namedXContentRegistry, List<String> deprecations) {
+        try {
+            return XContentObjectTransformer.queryBuilderTransformer(namedXContentRegistry).fromMap(queryProvider.query, deprecations);
```
Comment (hendrikmuhs) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: `queryProvider` has the parsed query (`QueryBuilder`), is it necessary to parse it again?

(depredations are ignored on line 314 anyway)

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: @davidkyle, my main concern with having it this way is the situation where it gets serialized to a `6.6.0-6.6.2` node and then comes BACK to a node with the bug fix. Admittedly, I do not know all the valid paths for inter-node serialization.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 9]
```diff
@@ -310,62 +294,89 @@ public Integer getScrollSize() {
...
         return deprecations;
     }
 
     public Map<String, Object> getQuery() {
-        return query;
+        return queryProvider == null ? null : queryProvider.query;
+    }
+
+    public AggregatorFactories.Builder getParsedAggregations(NamedXContentRegistry namedXContentRegistry) {
+        return aggProvider == null ? null : parseAggregations(namedXContentRegistry, new ArrayList<>());
```
Comment (hendrikmuhs) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: same thing: the aggProvider has the `AggregatorFactories.Builder`

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java [hunk 10]
```diff
@@ -555,6 +600,198 @@ private TimeValue defaultFrequencyTarget(TimeValue bucketSpan) {
         return TimeValue.timeValueHours(1);
     }
 
+    static class QueryProvider implements Writeable {
```
Comment (hendrikmuhs) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: nit: I think readability would be improved if both providers are moved into their own files (and get corresponding unit tests)

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java (hunk 8 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: Yes, the only reason to have the parsed one kept is when serializing to a node that does not support lazily parsed objects.

Comment (hendrikmuhs) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: does that mean, `QueryBuilder.parsedQuery` could be null while query contains a __valid__ query?

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: @hendrikmuhs This would only be the case if there were 3 versions of Elastic search running in the cluster, which is unsupported. I am going to put an early failure in serialization if Parsed == null && Exception == null when shipping to an "Eager" node. 

Assume we have 3 nodes named: Eager (does not support lazy parsing), Bug (contains the bug), Fixed (contains the bug fix). 

Bug -> Fixed -> Eager would fail.

However, any interactions between them

Eager <-> Fixed (Eager contains the parsed object and send it over the wire)
Bug <-> Fixed (Bug supports lazy parsing, so no need to parse on serialization)
Eager <-> Bug (Bug contains the code that can parse right before serialization)

Comment (hendrikmuhs) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: I might have a "simplified" view. Still I think that it would get simpler if you use the parsed query in this place. Therefore queryProvider always has both the parsed and surface query and in the case of a broken query only the surface form, in this case the datafeed is broken anyway. All the serialization and BWC quirks would need to be fixed in the serialization code in a way that no matter what queryProvider gets initialized correctly. The same applies for aggregations.

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: @hendrikmuhs 
How could you parse a query from `Bug` version that only sends a `Map<String, Object>` over the wire? The serialization methods have no access to the `NamedXContentRegistry`

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/QueryProvider.java [hunk 11]
```diff
@@ -0,0 +1,162 @@
...
+    @Override
+    public void writeTo(StreamOutput out) throws IOException {
+        if (out.getVersion().onOrAfter(Version.CURRENT)) { // Has our bug fix for query/agg providers
+            out.writeMap(query);
+            out.writeOptionalNamedWriteable(parsedQuery);
+            out.writeException(parsingException);
+        } else if (out.getVersion().onOrAfter(Version.V_6_6_0)) { // Has the bug, but supports lazy objects
+            // We allow the lazy parsing nodes that have the bug throw any parsing errors themselves as
+            // they already have the ability to fully parse the passed Maps
+            out.writeMap(query);
```
Comment (hendrikmuhs) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/QueryProvider.java]: nice!

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java (hunk 8 above)
Comment (hendrikmuhs) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: I see that I misunderstood your previous answer. `QueryBuilder.parsedQuery` can be `null` in 1 case (version 6.6.0 - 6.6.2 if I read the labels correctly).

I suggest to define the API the way we want to have it for the future - ignoring the issue - 

```
public QueryBuilder getParsedQuery()
```

and have a fixup method which you call in the according places before calling `getParsedQuery()`

```
public fixupQueryBuilder(NamedXContentRegistry registry) {
  if queryProvider.getParsedQuery() == null {
  // this is the fixup code required because bla bla bla
  }
}
```

alternatively you cold have a bool `requiresParsingFix` in the QueryProvider class

The benefit of this approach: Going forward we want to get rid of this legacy. This way it is only a matter of deleting some LOC, otherwise you need another big re-factoring, which get easily forgotten and we have to live with this forever.

Correct me if I am wrong: Assuming this works and you get this in for 7.0 and 6.7, we could already delete this workaround on master (but maybe we do not want to do this right now to avoid any merge trouble, although merges shall be quite clean).

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java]: having an outside system call `fixupQueryBuilder` and then `getParsedQuery` assumes outside classes know about the internal state of the object. It makes way more sense for a uniform api in accessing the lazily parsed objects. I do not want another class to have to know when to call `fixupQueryBuilder` vs when not to. 

Correct, in master (once all is backported and figured out), some of these weird work arounds can be refactored again. But I wanted to be close to what I am going to be backporting all the way back to a 6.6.x and 6.7.0

**Comment by benwtrent** [comment]
@elasticmachine
run elasticsearch-ci/1
run elasticsearch-ci/2
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by droberts195** [comment]
Let's backport to 6.7.0, but not attempt 6.6.3 as it's extremely unlikely 6.6.3 will ever be released.

**Review by davidkyle — APPROVED** [review]
LGTM

**Review by droberts195 — APPROVED** [review]
LGTM

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/2
