### PR TITLE
Ensure dynamicMapping updates are handled in insertion order

### LINKED ISSUE #103011: Significant ingest performance regression while handling parsing dynamically added objects
### Elasticsearch Version

8.11+

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

While indexing documents with dynamically added fields, if multiple of those fields are objects are are deeper than 3-5 objects, performance is degraded significantly.

This bug was introduced in: https://github.com/elastic/elasticsearch/pull/90674

### Steps to Reproduce

I built a micro-benchmark to replicate this particular bug. 

But, any dynamic object parsing will cause this.

To mitigate the issue, statically mapped fields for objects is required. 

### Logs (if relevant)

Attached are two JFR files indicating the difference between when the bug was introduce vs. not.
[Archive 2.zip](https://github.com/elastic/elasticsearch/files/13569248/Archive.2.zip)

### PR DESCRIPTION
**Pull request by benwtrent**
The switch to holding dynamic fields in a hashmap effectively randomizes their iteration order. This can be troublesome when building the mapping update required by these updates. When iterating in an unknown order, recursing to the leaf mapper can occur many times `O(n^2)`. However, starting with insertion order, it will occur only `O(n)` times.

closes: https://github.com/elastic/elasticsearch/issues/103011

### CODE REVIEW

**Comment by benwtrent** [comment]
I confirmed this fix by running: https://github.com/elastic/elasticsearch/pull/103015

The runtime is now at or below what it was in 8.10.

I additionally double checked that the flame graphs were similar, and indeed they are.

**Review by piergm — APPROVED** [review]
Way to go @benwtrent!

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java [hunk 1]
```diff
@@ -166,9 +166,9 @@ protected DocumentParserContext(
             mappingParserContext,
             source,
             new HashSet<>(),
-            new HashMap<>(),
+            new LinkedHashMap<>(),
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:169]: Should we restrict the type of the fields to `LinkedHashMap` ? 
i.e. 
```
-    private final Map<String, List<Mapper.Builder>> dynamicMappers;
+    private final LinkedHashMap<String, List<Mapper.Builder>> dynamicMappers;
     private final Set<String> newFieldsSeen;
-    private final Map<String, ObjectMapper.Builder> dynamicObjectMappers;
+    private final LinkedHashMap<String, ObjectMapper.Builder> dynamicObjectMappers;
     private final List<RuntimeField> dynamicRuntimeFields;
     private final DocumentDimensions dimensions;
     private final ObjectMapper parent;
@@ -102,9 +102,9 @@ public abstract class DocumentParserContext {
         MappingParserContext mappingParserContext,
         SourceToParse sourceToParse,
         Set<String> ignoreFields,
-        Map<String, List<Mapper.Builder>> dynamicMappers,
+        LinkedHashMap<String, List<Mapper.Builder>> dynamicMappers,
         Set<String> newFieldsSeen,
-        Map<String, ObjectMapper.Builder> dynamicObjectMappers,
+        LinkedHashMap<String, ObjectMapper.Builder> dynamicObjectMappers,
```

**Comment by benwtrent** [comment]
To clarify to folks digging between all the various issues, this PR didn't fully address the problem. See https://github.com/elastic/elasticsearch/issues/103011#issuecomment-1874539428. 

The real fix was in 8.11.4, and was a full revert of the originating bugged code.
