### PR TITLE
Fix testAbortSnapshotWhileRemovingNode

### LINKED ISSUE #142805: [CI] SnapshotShutdownIT class failing
**Build Scans:**
- [elasticsearch-intake #34834 / part1](https://gradle-enterprise.elastic.co/s/mtnyh5m3tpvck)
- [elasticsearch-pull-request #122157 / part-1](https://gradle-enterprise.elastic.co/s/w4aib43d72gbo)
- [elasticsearch-pull-request #122114 / part-1](https://gradle-enterprise.elastic.co/s/32hjrzbor65u2)
- [elasticsearch-pull-request #122110 / part-1](https://gradle-enterprise.elastic.co/s/u6tfs7yyth3uw)
- [elasticsearch-periodic-platform-support #11882 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/acu6orgrthsg2)
- [elasticsearch-pull-request #122050 / part-1](https://gradle-enterprise.elastic.co/s/5vv2qmzfxhlei)
- [elasticsearch-pull-request #121929 / part-1](https://gradle-enterprise.elastic.co/s/g6vquek7qna2s)
- [elasticsearch-pull-request #121916 / part-1](https://gradle-enterprise.elastic.co/s/mdjs5szgcrruu)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testAbortSnapshotWhileRemovingNode" -Dtests.seed=EDD37F1EE4FE4DE4 -Dtests.locale=te-Telu-IN -Dtests.timezone=Africa/Luanda -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.snapshots.SnapshotShutdownIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: All incoming requests on node [node_s0] should have finished. Expected 0 bytes for requests in-flight but got 189 bytes; pending tasks [[{
  "node" : "node_s0",
  "id" : 2929,
  "type" : "transport",
  "action" : "internal:cluster/snapshot/update_snapshot_status",
  "description" : "",
  "start_time" : "2026-02-21T22:33:27.294Z",
  "start_time_in_millis" : 1771713207294,
  "running_time" : "1.1m",
  "running_time_in_nanos" : 66001400081,
  "cancellable" : false,
  "parent_task_id" : "syLxvCLHTHi6H0nclHlQBw:42",
  "headers" : { }
},{
  "node" : "node_s0",
  "id" : 25,
  "type" : "persistent",
  "action" : "health-node[c]",
  "status" : {
    "state" : "STARTED"
  },
  "description" : "id=health-node",
  "start_time" : "2026-02-21T22:32:53.803Z",
  "start_time_in_millis" : 1771713173803,
  "running_time" : "1.6m",
  "running_time_in_nanos" : 99492675215,
  "cancellable" : true,
  "cancelled" : false,
  "parent_task_id" : "cluster:1",
  "headers" : { }
}]]
```

**Issue Reasons:**
- [main] 8 failures in class org.elasticsearch.snapshots.SnapshotShutdownIT (2.5% fail rate in 325 executions)
- [main] 6 failures in step part-1 (2.9% fail rate in 205 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (2.9% fail rate in 204 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by joshua-adams-1**
Clear the mock transport rule in `testAbortSnapshotWhileRemovingNode` after releasing the single `update_snapshot_status` request we coordinate on, so any further requests are handled normally and complete before teardown. This prevents the test from failing in `assertAfterTest()` with "All incoming requests on node [X] should have finished".

Closes #142805

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
This looks like a good change but are you sure it fixes the test failure completely?

**Comment by joshua-adams-1** [comment]
@ywangd Hey, tell me if I'm wrong here, but AFAICT, the test blocks all `internal:cluster/snapshot/update_snapshot_status` requests on the master via `addRequestHandlingBehavior` and a `CyclicBarrier(2)`. It only releases the barrier twice (once for "data node sent pause", once for "process that pause after abort"), so exactly one request is allowed through.

When the snapshot is aborted, the data node can send a second status update (e.g. FAILED/ABORTED or completion). That second request hits the same handler and blocks on the first safeAwait(barrier) with no further barrier releases, so it never completes. After the test method returns, `InternalTestCluster.assertAfterTest()` runs and calls `assertRequestsFinished()`, which uses the in-flight-requests circuit breaker. The stuck request keeps non-zero bytes in flight and triggers:
```
AssertionError: All incoming requests on node [node_s0] should have finished.
Expected 0 bytes for requests in-flight but got 189 bytes; pending tasks [
  internal:cluster/snapshot/update_snapshot_status, ...
]
```

I believe removing the masterTransportAction rules should prevent this from happening by letting all subsequent requests occur as intended.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java [hunk 1]
```diff
@@ -613,6 +616,7 @@ public void testSnapshotShutdownProgressTracker() throws Exception {
 
         // Release the master node to respond
         snapshotStatusUpdateLatch.countDown();
+        masterTransportService.clearAllRules();
```
Comment (joshua-adams-1) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:620]: Lmk if this is the wrong place to have this. I put it here since it's the line following `snapshotStatusUpdateLatch` being counted down (and therefore the update snapshot requests are allowed to be processed, and we can remove the rules).

**Review by DaveCTurner — APPROVED** [review]
LGTM (I haven't actually reproduced the failure tho, it's quite rare)
