### PR TITLE
Avoid setting connection request timeout

### LINKED ISSUE #24069: TimeoutExceptions on REST Client - with fix proposal
**Elasticsearch version**:

5.3

**Plugins installed**: N/A

**JVM version**: All

**OS version**: Any

While running integration tests for the Hibernate Search project we noticed some requests failing for TimeoutException on rather slow machines. I initially thought it was a "just a timeout", but investigating I actually identified a problem caused by the default configuration applied by the Elasticsearch REST client.

The Apache Async HTTP client being used has a pool for Non-blocking HTTP connections, implemented by `org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager`. This pool has a connection property which can be set via `org.apache.http.client.config.RequestConfig.Builder.connectionRequestTimeout`, but the name seems to have been confusing (it certainly confused me).

This configuration property validates if the Request is stale; for some reason it's also applied to instances of `org.apache.http.nio.pool.LeaseRequest` , and the next lease instance is validated from a queue of requests even after the execution of a successul client Request. When this second request is expired, the whole execution is marked with a TimeoutException.

To clarify: the client code sends a request A to the Elasticsearch server. A is processed fine, and the response is handled fine as well. *after* this, the state of A is marked as "timed out" because the next request in the PoolingNHttpClientConnectionManager is an expired lease instance.
I suspect this is a bug in the Apache Async client code as the error handling is essentially returning an exception which seems out of place.

The solution for us was extremely simple: set this property to zero, to disable this lease mechanism.

This mechanism is disabled by default in the Apache Async Http library, but the Elasticsearch client overrides this with its own default:
 org.elasticsearch.client.RestClientBuilder.DEFAULT_CONNECTION_REQUEST_TIMEOUT_MILLIS

I'd recommend to set this default to zero as well. The name of the property is probably misleading? It's not really applied to the request processing on the Elasticsearch server, it's applied to the "request to the connection pool".

Thanks!

Relates to:
 - https://hibernate.atlassian.net/browse/HSEARCH-2681

I think it's the same problem mentioned here:
 - https://discuss.elastic.co/t/elasticsearch-in-docker-and-the-restclient-often-got-java-util-concurrent-timeoutexception/68118

### PR DESCRIPTION
**Pull request by javanna**
We've been setting this value to 500ms in the default low-level REST
client configuration, misunderstanding the effect that it would have.
This proved very problematic, as it ends up causing `TimeoutException`
returned from the leased pool in some cases even for successful requests.

Closes #24069

### CODE REVIEW

File: client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java [hunk 1]
```diff
@@ -159,6 +163,42 @@ public static void stopHttpServers() throws IOException {
         httpServer = null;
     }
 
+    /**
+     * Tests sending a bunch of async requests works well (e.g. no TimeoutException from the leased pool)
+     * See https://github.com/elastic/elasticsearch/issues/24069
+     */
+    public void testManyAsyncRequests() throws Exception {
```
Comment (javanna) [inline client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java]: @nik9000 this test may look familiar to you :)

**Comment by javanna** [comment]
retest this please

File: docs/CHANGELOG.asciidoc [hunk 2]
```diff
@@ -199,6 +199,8 @@ coming[6.3.1]
 
 Reduce the number of object allocations made by {security} when resolving the indices and aliases for a request ({pull}30180[#30180])
 
+Stop setting connection request timeout in default low-level REST client configuration ({pull}30384[#30384])
```
Comment (nik9000) [inline docs/CHANGELOG.asciidoc]: Maybe add "because it causes timeout exceptions before any requests are made which isn't how timeouts are supposed to work" or something like that.

**Review by nik9000 — APPROVED** [review]
LGTM! Sorry I missed this a few days ago.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by jpountz** [comment]
@javanna This may be backported now.
