### PR TITLE
Let `isInetAddress` utility understand the scope ID on ipv6

### LINKED ISSUE #60115: Wrong publish_address format in ipv6 network
Elasticsearch version (bin/elasticsearch --version): 7.6.0

On an ipv6 network, `network.host` is set to `_local`_, and `network.publish_host` is not configured.

network.host will be  parsed as: 
```
"[::1]:9200",
"127.0.0.1:9200"
```
```
GET /_nodes/http?pretty
```

```
"http": {
  "bound_address": [
    "[::1]:9200",
    "127.0.0.1:9200"
  ],
  "publish_address": "0:0:0:0:0:0:0:1%lo/[::1]:9200",
```

In this scenario, publish_address is better to use `ip：port` format then `hostname/ip:port` because` 0:0:0:0:0:0:0:1%lo` is not an
avalible hostname.

The rest client sniffer needs to parse publish_address to obtain the IP address, `"0:0:0:0:0:0:0:1%lo/[::1]:9200"` will cause sniffing exceptions.

### PR DESCRIPTION
**Pull request by chengyang14**
Let `isInetAddress` utility understand the scope ID on ipv6 .

Fixes #60115

### CODE REVIEW

**Comment by chengyang14** [comment]
hi @original-brownbear , can you help to review this PR.

File: server/src/main/java/org/elasticsearch/common/network/InetAddresses.java [hunk 1]
```diff
@@ -60,6 +64,9 @@ public static boolean isInetAddress(String ipString) {
                     return null;
                 }
             }
+            if (percentIndex != -1) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/common/network/InetAddresses.java:67]: should we make sure that we have something after the `%` in the string and maybe return `null` if `percentIndex == ipString.length() - 1` because that wouldn't be a valid address would it?

Unless you disagree with filtering this case out, could you also add a test for it when adding this check?

**Review by original-brownbear — COMMENTED** [review]
Thanks  @chengyang14 looks good! Just one question/point to enhance.

**Comment by original-brownbear** [comment]
Jenkins test this

File: server/src/main/java/org/elasticsearch/common/network/InetAddresses.java [hunk 2]
```diff
@@ -60,6 +64,12 @@ public static boolean isInetAddress(String ipString) {
                     return null;
                 }
             }
+            if (percentIndex == ipString.length() - 1) {
+                return null;
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/common/network/InetAddresses.java:68]: Let's add a comment here that explains that we are doing this check to filter out strings that end in `%` and have an empty scope ID.

**Review by original-brownbear — COMMENTED** [review]
All perfect thanks @chengyang14 , let's just add one comment I asked for in-line to make that subtle spot nicely readable.

**Comment by original-brownbear** [comment]
Jenkins test this

**Review by original-brownbear — APPROVED** [review]
LGTM thanks for the iterations @chengyang14 !
