### PR TITLE
Mapping: Allows upgrade of indexes with only search_analyzer specified

### LINKED ISSUE #14383: Upgrading fields with only `search_analyzer` specified
When upgrading from 1.x to 2.0, a field that has only a `search_analyzer` specified will throw an exception and prevent the node from starting.  Really, the field does have an `index_analyzer`, set to `default`.  We should be able to migrate this mapping to a 2.0 compatible version.

Relates to #14313

### PR DESCRIPTION
**Pull request by colings86**
Previously if an index was created before 2.0 using the default index_analyzer but specifying an explicit search_analyzer the index could not be started in 2.0 because we require 'analyzer' (formerly index_analyzer) to be set if you define an explicit search_analyzer. This change allows indexes created before 2.0 to use the default analyzer and specify an explicit search_analyzer. Indexes created on or after 2.0 are still required to explicitly set the analyzer if they want to explicitly set the search_analyzer.

Closes #14383

### CODE REVIEW

**Comment by colings86** [comment]
@rjernst would you be able to review this for me?

**Comment by rjernst** [comment]
Can you add a test?

**Comment by colings86** [comment]
@rjernst I've added to the unit tests for string field mapping. I also added a field mapping to the index bwc python script and generated a new bwc index for 1.7.3 which contains the new field for testing.

**Comment by rjernst** [comment]
@colings86 Please regenerate all of the indexes. There is a helper script to do that.

**Comment by colings86** [comment]
@rjernst I've added a new commit with all the bwc indices regenerated

**Comment by jpountz** [comment]
LGTM (but please wait for @rjernst to have a look as well before merging)

File: core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 1]
```diff
@@ -467,9 +468,14 @@ protected void doXContentAnalyzers(XContentBuilder builder, boolean includeDefau
...
-        } else if (includeDefaults || fieldType().indexAnalyzer().name().startsWith("_") == false && fieldType().indexAnalyzer().name().equals("default") == false) {
-            builder.field("analyzer", fieldType().indexAnalyzer().name());
-            if (fieldType().searchAnalyzer().name().equals(fieldType().indexAnalyzer().name()) == false) {
+        } else {
+            if (includeDefaults || fieldType().indexAnalyzer().name().startsWith("_") == false
+                    && fieldType().indexAnalyzer().name().equals("default") == false) {
+                builder.field("analyzer", fieldType().indexAnalyzer().name());
+            }
+            if (includeDefaults || fieldType().searchAnalyzer().name().startsWith("_") == false
+                    && fieldType().searchAnalyzer().name().equals("default") == false
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: Instead of duplicating this complicated logic twice, can you move the search analyzer check inside (ie we would only write search_analyzer if we at least wrote analyzer)?

File: core/src/test/java/org/elasticsearch/index/mapper/string/SimpleStringMappingTests.java [hunk 2]
```diff
@@ -562,9 +562,52 @@ public void testBackwardCompatible() throws Exception {
...
+                .put(IndexMetaData.SETTING_VERSION_CREATED, VersionUtils.randomVersionBetween(random(), Version.V_1_0_0, Version.V_1_7_1))
+                .build();
+
+        DocumentMapperParser parser = createIndex("backward_compatible_index", settings).mapperService().documentMapperParser();
+
+        String mapping = XContentFactory.jsonBuilder().startObject().startObject("type").startObject("properties").startObject("field1")
+                .field("type", "string").field("search_analyzer", "keyword").endObject().endObject().endObject().endObject().string();
+        parser.parse(mapping);
+
+        assertThat(parser.parse(mapping).mapping().toString(), containsString("\"search_analyzer\":\"keyword\""));
```
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/index/mapper/string/SimpleStringMappingTests.java]: Instead of relying on serialization, can the test look at the parsed mapping and see that the search analyzer is equal to keyword? And also check the index analyzer is the default?

**Comment by rjernst** [comment]
A few small suggestions. LGTM.

File: core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java (hunk 1 above)
Comment (colings86) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: But in that case we would not write search_analyzer in the case where the index_analyzer is `default` which would mean that the fix would not work (note the checks on this second if statement are checking the searchAnalyzer not the indexAnalyzer)

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: We should be writing out the settings in the "new format". There is no longer index_analyzer. So in the case of search_analyzer being set alone, when we serialize, we should write both analyzer and search_analyzer.

File: core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 3]
```diff
@@ -467,10 +468,17 @@ protected void doXContentAnalyzers(XContentBuilder builder, boolean includeDefau
...
+            boolean writtenSearchAnalyzer = false;
+            if (includeDefaults || fieldType().searchAnalyzer().name().startsWith("_") == false
+                    && fieldType().searchAnalyzer().name().equals("default") == false
+                    && fieldType().searchAnalyzer().name().equals(fieldType().indexAnalyzer().name()) == false) {
                 builder.field("search_analyzer", fieldType().searchAnalyzer().name());
+                writtenSearchAnalyzer = true;
+            }
+            if (writtenSearchAnalyzer || includeDefaults || fieldType().indexAnalyzer().name().startsWith("_") == false
+                    && fieldType().indexAnalyzer().name().equals("default") == false) {
+                builder.field("analyzer", fieldType().indexAnalyzer().name());
```
Comment (colings86) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: @rjernst I have changed this so if the `search_analyzer` is written we bypass the checks on whether to write the `analyzer` since we want to write the output in the "new format" where `search_analyzer` cannot be specified without `analyzer`. However, I can't see a way of simplifying the other checks since we need to check whether the search_analyzer is `default` or starts with `_` before we write it. Let me know if you can see a better way to write this.

File: core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 4]
```diff
@@ -467,10 +468,19 @@ protected void doXContentAnalyzers(XContentBuilder builder, boolean includeDefau
...
-        } else if (includeDefaults || fieldType().indexAnalyzer().name().startsWith("_") == false && fieldType().indexAnalyzer().name().equals("default") == false) {
-            builder.field("analyzer", fieldType().indexAnalyzer().name());
-            if (fieldType().searchAnalyzer().name().equals(fieldType().indexAnalyzer().name()) == false) {
+        } else {
+            boolean writtenSearchAnalyzer = false;
+            if (includeDefaults || fieldType().searchAnalyzer().name().startsWith("_") == false
+                    && fieldType().searchAnalyzer().name().equals("default") == false
+                    && fieldType().searchAnalyzer().name().equals(fieldType().indexAnalyzer().name()) == false) {
                 builder.field("search_analyzer", fieldType().searchAnalyzer().name());
+                writtenSearchAnalyzer = true;
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: You can simplify this to:
```
boolean writeSearchAnalyzer =  // logic
if (writeSearchAnalyzer || analyzer logic) {
  // write analyzer
}
if (writeSearchAnalyzer) {
    // write search_analyzer
}
```

This will also keep the same order (analyzer followed by search_analyzer) that we had before.

**Comment by rjernst** [comment]
LGTM

**Comment by colings86** [comment]
Pushed to the 2.0, 2.1 and 2.x branches. This fix shouldn't need to go into master since we won't need to support this kind of migration in 3.0. @clintongormley could you confirm that?

**Comment by clintongormley** [comment]
@colings86 correct, thanks
