### PR TITLE
[Transform] add support for missing bucket

### LINKED ISSUE #42941: [Transform] Add support for missing_bucket in group_by
By default documents without a value for a given group_by are ignored. Like composite aggs it would be nice to support `missing_bucket` in group_by.

Side effect: Progress reporting ignores missing values, progress calculation must be changed accordingly when implementing this feature.

### LINKED ISSUE #55102: _transform API does not support missing_bucket
**Elasticsearch/Kibana Version** 7.5.2 running in on-prem ECE

While working with the _transaform API I noticed that documents were only getting grouped if all fields in the group by section had a value. Some reading in the composite aggregation documentation I see that this can be fixed by setting `missing_bucket` to true. The terms aggregation also has a `missing` parameter that can be set but that appears to no be supported either #48243

[Composite Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/search-aggregations-bucket-composite-aggregation.html#_missing_bucket)

Any idea how we can get around this?

```json
POST _transform/_preview
{
  "source": {
    "index": [
      "visanet-transaction*"
    ],
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "dest"
  },
  "pivot": {
    "group_by": {
      "transactionTime": {
        "date_histogram": {
          "field": "transactionTime",
          "fixed_interval": "1h"
        }
      },
      "vipID": {
        "terms": {
          "field": "vipID",
          "missing_bucket": true
        }
      }
    },
    "aggregations": {
      "transactionID.value_count": {
        "value_count": {
          "field": "transactionID"
        }
      },
      "usdAmount.sum": {
        "sum": {
          "field": "usdAmount"
        }
      }
    }
  }
}
```

Error:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": "[1:20] [data_frame_terms_group] unknown field [missing_bucket], parser not found"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[1:167] [data_frame_transform_config] failed to parse field [pivot]",
    "caused_by": {
      "type": "x_content_parse_exception",
      "reason": "[1:167] [data_frame_transform_pivot] failed to parse field [group_by]",
      "caused_by": {
        "type": "x_content_parse_exception",
        "reason": "[1:20] [data_frame_terms_group] unknown field [missing_bucket], parser not found"
      }
    }
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
add support for "missing_bucket" in `group_by`

fixes #42941
fixes #55102

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
## Discussion

### missing_bucket and missing

With `missing_bucket` this PR exposes the [composite aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_missing_bucket) syntax. However in aggregations it's common to have a configuration option called [`missing`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_missing_value_17).

#### missing_bucket

 - maps non-existing fields to a bucket with key `null`
	- the query for retrieving these buckets is the same for source and dest (`!_exists_:field`)
 - if in a transform you want to map `null` buckets to a certain key instead, you need an extra ingest pipeline [set processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/set-processor.html#set-processor)
    - its not possible to collapse the bucket, e.g. if you want a default
    - even worse, wrong collapsing can lead to overwriting and therefore create broken results

#### missing
 - maps non-existing fields to a bucket with a given key, key **must not** be `null`
 - can clash (on purpose) with with existing fields, so you can collapse buckets, e.g. `"missing":0` in a histogram

It seems to me that `missing` is what we really want, however `missing` does not support `null`, which is important for rollup. Composite aggs does not support `missing`, but only `missing_bucket`.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java [hunk 1]
```diff
@@ -175,7 +227,10 @@ public boolean collectChanges(Collection<? extends Bucket> buckets) {
 
         @Override
         public QueryBuilder filterByChanges(long lastCheckpointTimestamp, long nextcheckpointTimestamp) {
+
             if (isSynchronizationField && lastCheckpointTimestamp > 0) {
+                // missing bucket can't be enabled as it would be an illegal combination
```
Comment (droberts195) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:232]: Is this enforced anywhere in the config parsing?

And do the `randomTransformConfig` methods in the tests enforce this?  I guess if they choose completely random field names for each section of the config then it's highly unlikely the time field in the sync config would randomly be the same as the time field for the date histogram.  So maybe this problem can be ignored.

**Review by droberts195 — COMMENTED** [review]
Basically this looks good although it's hard to see the important bits because they're swamped by the simple changes to pass around the extra setting.

I left one question about how it is enforced that missing bucket cannot be used with the time sync field.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 1 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:232]: good spot!

I should instead disable the `isSynchronizationField` optimization on line 214 in case `missingBucket == true`:

```
this.isSynchronizationField = isSynchronizationField && (missingBucket == false);
```

**Comment by hendrikmuhs** [comment]
> Basically this looks good although it's hard to see the important bits because they're swamped by the simple changes to pass around the extra setting.

true, sorry. During implementation I spotted missing code (client builders for geo) and bugs (missing/wrong equals and hash functions).

The important bits are in `CompositeBucketsChangeCollector.java`, especially the complex logic to find new documents that miss certain fields (see the query trees in the code comments).

**Comment by hendrikmuhs** [comment]
I re-worked the `missing_bucket` handling and introduced a audit/log if the continuous transform uses a configuration that does not allow at least 1 optimization.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 2]
```diff
@@ -347,6 +347,21 @@ protected void initializeFunction() {
 
         if (isContinuous()) {
             changeCollector = function.buildChangeCollector(getConfig().getSyncConfig().getField());
+
+            if (changeCollector.isOptimized() == false) {
+                logger.warn(
+                    new ParameterizedMessage(
+                        "[{}] could not find any optimizations for continuous execution, "
+                            + "this transform might run slow, please check your configuration.",
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:355]:
```suggestion
                            + "this transform might run slowly, please check your configuration.",
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 3]
```diff
@@ -347,6 +347,21 @@ protected void initializeFunction() {
...
+                        getJobId()
+                    )
+                );
+                auditor.warning(
+                    getJobId(),
+                    "could not find any optimizations for continuous execution, "
+                        + "this transform might run slow, please check your configuration."
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:362]:
```suggestion
                        + "this transform might run slowly, please check your configuration."
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 4]
```diff
@@ -347,6 +347,21 @@ protected void initializeFunction() {
...
+
+            if (changeCollector.isOptimized() == false) {
+                logger.warn(
+                    new ParameterizedMessage(
+                        "[{}] could not find any optimizations for continuous execution, "
+                            + "this transform might run slow, please check your configuration.",
+                        getJobId()
+                    )
+                );
+                auditor.warning(
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:359]: It would be nice to say which pivot values are causing the the optimization to be false. Each collector could respond with a `reason`.

**Review by benwtrent — APPROVED** [review]
minor logging comment.

The change overall looks good.

**Review by droberts195 — APPROVED** [review]
LGTM

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java (hunk 4 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:359]: created #60364 to follow up on this

**Comment by nicpenning** [comment]
This issue possibly mentioned in the community Slack (by me). Figured I would drop it here for others who come across this if I am following correctly.

If the field you are grouping by does not exist in the document, is it expected that the document will not be in the transformed index?
For example. I have a transform that I expect to have 5 documents but only has 4 after the transform because 1 document does not contain the file.name field at all.
If I clone that transform and remove the file.name field from the group by, I get all 5 documents in the transform.

Demo:
magic (1)

**Comment by benwtrent** [comment]
> If the field you are grouping by does not exist in the document, is it expected that the document will not be in the transformed index?

Yes it is expected behavior. We only grab docs that have ALL the group_by fields. 

With the additional support of `missing_bucket`, we should be able to grab documents that are missing the `group_by` fields.

**Comment by nicpenning** [comment]
Hey @hendrikmuhs and team!

Adding `"missing_bucket": true` to the `"terms": { }` field in the Edit JSON Config (Kibana) during the creation of a new transform does not get saved. The setting seems to get removed by the time it gets created. So basically this does not work in the Edit JSON Config section when creating a new transform.

And on a side note which will likely be worth of it's own issue is that editing the JSON Config in Kibana is very slow. Just clicking the Edit JSON takes about 20 seconds for the JSON to load. Then on top of that when you click inside of the loaded JSON and hit a key (such as enter/new line) it takes another 20 seconds. So the editing of this JSON Config is painful to use.

Here is a snippet of me trying to add "","" to the Edit JSON Config to demonstrate slowness. (Is it querying every time I make a change?)
magic2

On a positive note, the API for creating this works flawlessly. 👌

**Comment by hendrikmuhs** [comment]
@nicpenning 

The edit issue is tracked in https://github.com/elastic/kibana/issues/83266 and should be fixed in the next version. 

I don't know the reason of the perceived slowness. @walterra, do you know?

**Comment by walterra** [comment]
@nicpenning Hey Nic, how many fields does the index have you're using in the transforms wizard? There's a known issue with indices with 1000+ fields resulting in a slow wizard: https://github.com/elastic/kibana/issues/78590

**Comment by nicpenning** [comment]
Ahh, that could be it.

I am using filebeat-*.

Which I am sure you are aware contains a lot of fields if a person is using many integrations.

I imagine its well over 3K fields for that index pattern.

I suppose the work around is having a more narrow index pattern?
