### PR TITLE
ESQL: Drop null columns in text formats

### LINKED ISSUE #116848: ESQL: `drop_null_columns` doesn't work with `format=txt`
### Description

It doesn't look like `drop_null_columns` works properly with `format=txt`. We should fix that!

### PR DESCRIPTION
**Pull request by kanoshiou**
This PR resolves the issue where, despite setting `drop_null_columns=true`, columns that are entirely null are still returned when using `format=txt`, `format=csv`, or `format=tsv`.

Closes #116848

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java [hunk 1]
```diff
@@ -313,9 +320,16 @@ public String contentType(RestRequest request) {
...
 
     // utility method for consuming a row.
-    <F> void row(Writer writer, Iterator<F> row, Function<F, String> toString, Character delimiter) throws IOException {
+    <F> void row(Writer writer, Iterator<F> row, Function<F, String> toString, Character delimiter, boolean[] nullColumns)
+        throws IOException {
         boolean firstColumn = true;
+        int i = -1;
         while (row.hasNext()) {
+            i++;
+            if (nullColumns != null && nullColumns[i]) {
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java:329]: It'd make it just an array of true rather than nullable. A little easier to think about and not much extra memory used.

**Review by nik9000 — COMMENTED** [review]
Neat! I left a small thing but I think it's great!

@bpintea, you wrote the text formatter stuff, would you like to review this one too?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java (hunk 1 above)
Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java:329]: Thanks @nik9000. I suppose you mean an array of false when there is no need to drop null columns.

Comment (nik9000) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java]: Er, yeah. Right. Don't drop. Maybe we should name it `dropColumns`? That'd be a little cleared about what it's *for* in this context. Super minor thing.

Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java]: Yes, I agree. It can be confusing otherwise.

**Review by bpintea — COMMENTED** [review]
Looks good, left some small remarks.

**Comment by kanoshiou** [comment]
Thank you @bpintea . I have modified the code based on your comments. Please review it when you have time. If there are any other changes needed, please let me know. I am happy to make them.

**Comment by bpintea** [comment]
@elasticsearchmachine retest this please

**Comment by bpintea** [comment]
@elasticsearchmachine test this please

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java [hunk 2]
```diff
@@ -291,7 +291,7 @@ public Iterator<CheckedConsumer<Writer, IOException>> format(RestRequest request
         boolean[] dropColumns = dropNullColumns ? esqlResponse.nullColumns() : new boolean[esqlResponse.columns().size()];
         return Iterators.concat(
             // if the header is requested return the info
-            hasHeader(request) && esqlResponse.columns().isEmpty() == false
+            hasHeader(request) && esqlResponse.columns() != null
```
Comment (kanoshiou) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java:294]: I believe columns will never be null. However, changing the check to see if they are empty might cause some test cases to fail. Perhaps it should be updated to handle empty values and adjust the affected test cases accordingly.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java [hunk 3]
```diff
@@ -1274,11 +1274,11 @@ static String runEsqlAsTextWithFormat(RequestObjectBuilder builder, String forma
...
                     case "csv" -> {
-                        assertEquals(initialValue, "\r\n");
+                        assertEquals("\r\n", initialValue);
                         initialValue = "";
                     }
                     case "tsv" -> {
-                        assertEquals(initialValue, "\n");
+                        assertEquals("\n", initialValue);
                         initialValue = "";
                     }
```
Comment (kanoshiou) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:1283]: This is the test case I mentioned earlier that caused an error. When I first encountered this error, the expected and actual values were reversed, which confused me at first. Therefore, I think it would be better to flip them.

**Comment by kanoshiou** [comment]
@bpintea, I have modified the code to resolve the test failure. However, I can only see this one failure because my IDEA crashes every time when running checks (Maybe I should update my equipment😂). 

It might be more convenient for external contributors if the [elasticsearch-pull-request](https://buildkite.com/elastic/elasticsearch-pull-request) pipeline were open to the public, similar to the [logstash-pull-request-pipeline](https://buildkite.com/elastic/logstash-pull-request-pipeline).

**Comment by bpintea** [comment]
buildkite test this

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/formatter/TextFormat.java:294]: I didn't try it out, but it looks to me like it should produce the same result. But yes, seems like `esqlResponse.columns()` will currently never be `null`.

**Review by bpintea — APPROVED** [review]
LGTM, thanks @kanoshiou!

**Comment by bpintea** [comment]
@kanoshiou 

> It might be more convenient for external contributors if the [elasticsearch-pull-request](https://buildkite.com/elastic/elasticsearch-pull-request) pipeline were open to the public

A bit late for this PR, but it is from now on.

**Comment by kanoshiou** [comment]
Thank you very much @bpintea !
