### PR TITLE
ESQL: Fix async operator warnings not always sent when blocking

### LINKED ISSUE #128030: [CI] EsqlSpecIT test {lookup-join.MvJoinKeyOnTheLookupIndex ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic #8150 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/it3kvzq5hx64y)
- [elasticsearch-pull-request #71316 / part-3](https://gradle-enterprise.elastic.co/s/7hcwr6ulhhpi6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {lookup-join.MvJoinKeyOnTheLookupIndex ASYNC}" -Dtests.seed=3CD9BD9A23D76E3A -Dtests.locale=is-Latn-IS -Dtests.timezone=Africa/Maseru -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Blookup-join.MvJoinKeyOnTheLookupIndex%20ASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 4:3: evaluation of [LOOKUP JOIN languages_lookup_non_unique_key ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 4:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 2 failures in test test {lookup-join.MvJoinKeyOnTheLookupIndex ASYNC} (0.9% fail rate in 229 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130296: [CI] EsqlSpecIT test {lookup-join.MvJoinKeyOnFrom SYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9051 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/cqpi32uv44rxy)
- [elasticsearch-pull-request #77625 / part-3](https://gradle-enterprise.elastic.co/s/uxr65txxvcy42)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {lookup-join.MvJoinKeyOnFrom SYNC}" -Dtests.seed=50DD413B42416F8D -Dtests.locale=fy-Latn-NL -Dtests.timezone=Africa/Ceuta -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Blookup-join.MvJoinKeyOnFrom%20SYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 4:3: evaluation of [LOOKUP JOIN languages_lookup ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 4:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 2 failures in test test {lookup-join.MvJoinKeyOnFrom SYNC} (0.4% fail rate in 522 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130642: [CI] EsqlSpecIT test {lookup-join.MvJoinKeyFromRow ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9157 / windows-2025_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/m5l3v562uwxf6)
- [elasticsearch-pull-request #78391 / part-3](https://gradle-enterprise.elastic.co/s/kqzwy3beoac7e)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {lookup-join.MvJoinKeyFromRow ASYNC}" -Dtests.seed=F1A334C9DE643CB -Dtests.locale=af-ZA -Dtests.timezone=ECT -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Blookup-join.MvJoinKeyFromRow%20ASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 2:3: evaluation of [LOOKUP JOIN languages_lookup_non_unique_key ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 2:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 2 failures in test test {lookup-join.MvJoinKeyFromRow ASYNC} (0.3% fail rate in 690 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #131148: [CI] EsqlSpecIT test {lookup-join.MvJoinKeyOnFromAfterStats ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9318 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/5i6f2hf4ww2jc)
- [elasticsearch-periodic-platform-support #9255 / windows-2025_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/p3qq5teg66b3y)
- [elasticsearch-pull-request #79353 / part-3](https://gradle-enterprise.elastic.co/s/yv5bm5fxltaaq)
- [elasticsearch-pull-request #79353 / part-3](https://gradle-enterprise.elastic.co/s/zik2wfpv5kcxe)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {lookup-join.MvJoinKeyOnFromAfterStats ASYNC}" -Dtests.seed=8961781776F7B4BD -Dtests.locale=gsw-CH -Dtests.timezone=Asia/Saigon -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Blookup-join.MvJoinKeyOnFromAfterStats%20ASYNC%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 5:3: evaluation of [LOOKUP JOIN languages_lookup ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 5:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 4 failures in test test {lookup-join.MvJoinKeyOnFromAfterStats ASYNC} (0.4% fail rate in 933 executions)
- [main] 2 failures in step part-3 (0.4% fail rate in 460 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (14.3% fail rate in 14 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #131563: [CI] EsqlSpecIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9972 / ubuntu-2404-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/22o3lcj7byg5y)
- [elasticsearch-periodic-platform-support #9888 / ubuntu-2404-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/s5prwe72twqxw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {stats.CommonFilterExtractionWithAliasing SYNC}" -Dtests.seed=8ACC39260A8FBB60 -Dtests.locale=he -Dtests.timezone=America/Chicago -Druntime.java=24
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:41245], URI [/_nodes/stats], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
```

**Issue Reasons:**
- [8.18] 2 failures in class org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT (0.5% fail rate in 407 executions)
- [8.18] 2 failures in step ubuntu-2404-aarch64_checkpart3_platform-support-arm (15.4% fail rate in 13 executions)
- [8.18] 2 failures in pipeline elasticsearch-periodic-platform-support (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132554: [CI] MultiClusterSpecIT test {csv-spec:lookup-join.MvJoinKeyOnFrom} failing
**Build Scans:**
- [elasticsearch-periodic #9867 / openjdk21_9.1.1_java-matrix-bwc](https://gradle-enterprise.elastic.co/s/2bpxfys7eflhw)
- [elasticsearch-pull-request #84652 / 9.0.5_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/zz5fjplm55j4s)
- [elasticsearch-pull-request #84602 / 8.19.1_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/4bnbfnn6j527u)
- [elasticsearch-pull-request #84602 / 9.0.5_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ftfycpe2qkpk4)
- [elasticsearch-pull-request #84602 / 9.1.1_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/lys63k4qtflyi)
- [elasticsearch-pull-request #84602 / 9.2.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/jq4uuvtqbp6ze)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v9.1.1#newToOld" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {csv-spec:lookup-join.MvJoinKeyOnFrom}" -Dtests.seed=75613A2986A82F13 -Dtests.bwc=true -Dtests.locale=ar-MR -Dtests.timezone=Etc/GMT-3 -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Alookup-join.MvJoinKeyOnFrom%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 4:3: evaluation of [LOOKUP JOIN languages_lookup ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 4:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 6 failures in test test {csv-spec:lookup-join.MvJoinKeyOnFrom} (0.9% fail rate in 669 executions)
- [main] 2 failures in step 9.0.5_part_3_bwc-snapshots (2.9% fail rate in 68 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.9% fail rate in 70 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132555: [CI] EsqlSpecIT test {csv-spec:lookup-join.MvJoinKeyFromRow} failing
**Build Scans:**
- [elasticsearch-intake #26597 / part3](https://gradle-enterprise.elastic.co/s/l6d6uuo5chflc)
- [elasticsearch-pull-request #84688 / part-3](https://gradle-enterprise.elastic.co/s/hnntpbfd5k3ec)
- [elasticsearch-periodic-platform-support #9829 / ubuntu-2404-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/w4hutwl5azrbg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {csv-spec:lookup-join.MvJoinKeyFromRow}" -Dtests.seed=D08844312A5E435 -Dtests.locale=ff-Adlm-CM -Dtests.timezone=America/Blanc-Sablon -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Alookup-join.MvJoinKeyFromRow%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 2:3: evaluation of [LOOKUP JOIN languages_lookup_non_unique_key ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 2:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test test {csv-spec:lookup-join.MvJoinKeyFromRow}
- [main] 3 failures in test test {csv-spec:lookup-join.MvJoinKeyFromRow} (0.8% fail rate in 371 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132604: [CI] MixedClusterEsqlSpecIT test {csv-spec:lookup-join.MvJoinKeyFromRowExpanded} failing
**Build Scans:**
- [elasticsearch-intake #26642 / 9.1.2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/k3g2sjzex2qyi)
- [elasticsearch-pull-request #84849 / 9.1.2_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/t6g76q46wodmu)
- [elasticsearch-pull-request #84849 / 9.0.5_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ltn3k45lzdom2)
- [elasticsearch-pull-request #84849 / 8.19.2_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/gewyyot6n5woq)
- [elasticsearch-pull-request #84849 / pr-upgrade-part-3](https://gradle-enterprise.elastic.co/s/ykq5nwonp57ia)
- [elasticsearch-pull-request #84724 / 8.19.1_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/bsmcgawl4adv2)
- [elasticsearch-pull-request #84703 / 9.0.5_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ppo6szfnnpp5m)
- [elasticsearch-pull-request #84703 / 9.1.1_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/zfpyheskfd2cw)
- [elasticsearch-pull-request #84688 / 9.0.5_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/mwc2ehy3y6fi6)
- [elasticsearch-pull-request #84688 / 8.19.1_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/tt2pm6ev5pxim)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v9.1.2#javaRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT" -Dtests.method="test {csv-spec:lookup-join.MvJoinKeyFromRowExpanded}" -Dtests.seed=E93F6B86F0402D47 -Dtests.bwc=true -Dtests.locale=et -Dtests.timezone=Asia/Chongqing -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Alookup-join.MvJoinKeyFromRowExpanded%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 3:3: evaluation of [LOOKUP JOIN languages_lookup_non_unique_key ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 3:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 4 consecutive failures in step 9.0.5_part_3_bwc-snapshots
- [main] 3 consecutive failures in step 8.19.1_part_3_bwc-snapshots
- [main] 16 failures in test test {csv-spec:lookup-join.MvJoinKeyFromRowExpanded} (4.6% fail rate in 346 executions)
- [main] 4 failures in step pr-upgrade-part-3 (3.1% fail rate in 131 executions)
- [main] 4 failures in step 9.0.5_part_3_bwc-snapshots (100.0% fail rate in 4 executions)
- [main] 2 failures in step 9.1.1_part_3_bwc-snapshots (2.7% fail rate in 73 executions)
- [main] 3 failures in step 8.19.1_part_3_bwc-snapshots (100.0% fail rate in 3 executions)
- [main] 7 failures in pipeline elasticsearch-pull-request (4.8% fail rate in 145 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132778: [CI] GenerativeForkIT test {csv-spec:lookup-join.MvJoinKeyFromRowExpanded} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9983 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/fdaihx54cflt2)
- [elasticsearch-pull-request #85414 / part-3](https://gradle-enterprise.elastic.co/s/en2bmvlzjfije)
- [elasticsearch-pull-request #84849 / part-3](https://gradle-enterprise.elastic.co/s/4kuscwiuj4x3c)
- [elasticsearch-pull-request #84703 / part-3](https://gradle-enterprise.elastic.co/s/npspvtf6lj2km)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.GenerativeForkIT" -Dtests.method="test {csv-spec:lookup-join.MvJoinKeyFromRowExpanded}" -Dtests.seed=F5543ED5EE1B3F0B -Dtests.locale=pis-Latn-SB -Dtests.timezone=America/Martinique -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.GenerativeForkIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Alookup-join.MvJoinKeyFromRowExpanded%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 3:3: evaluation of [LOOKUP JOIN languages_lookup_non_unique_key ON language_code] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 3:3: java.lang.IllegalArgumentException: LOOKUP JOIN encountered multi-value" but was <missing>
```

**Issue Reasons:**
- [main] 4 failures in test test {csv-spec:lookup-join.MvJoinKeyFromRowExpanded} (0.6% fail rate in 712 executions)
- [main] 3 failures in step part-3 (1.2% fail rate in 258 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.2% fail rate in 258 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/128030
Fixes https://github.com/elastic/elasticsearch/issues/130296
Fixes https://github.com/elastic/elasticsearch/issues/130642
Fixes https://github.com/elastic/elasticsearch/issues/131148
Fixes https://github.com/elastic/elasticsearch/issues/132554
Fixes https://github.com/elastic/elasticsearch/issues/132555
Fixes https://github.com/elastic/elasticsearch/issues/132604
Fixes https://github.com/elastic/elasticsearch/issues/131563
Fixes https://github.com/elastic/elasticsearch/issues/132778

Extracted from https://github.com/elastic/elasticsearch/pull/132738

An AsyncOperator listener misordering caused the warnings collection and status metrics updates to be executed after the `onSeqNoCompleted()`>`notifyIfBlocked()`>`future.onResponse(null)`, which ends the processing in some cases.

# Bug explanation

An example profile of one of the CI fails:
```
{
  planning={took_millis=8, start_millis=1754605547195, stop_millis=1754605547203, took_nanos=8612200},
  plans=[
    {
      cluster_name=test-cluster,
      node_name=test-cluster-1,
      description=single,
      plan=
        OutputExec[org.elasticsearch.xpack.esql.plugin.ComputeService$$Lambda/0x0000000095705068@4387ca3]	
        \_ProjectExec[[language_code{r}#25708, language_name{f}#25719, country{f}#25716]]	
          \_TopNExec[[Order[language_code{r}#25708,ASC,LAST], Order[language_name{f}#25719,ASC,LAST], Order[country{f}#25716,ASC,LAST]],1000[INTEGER],104]	
            \_LookupJoinExec[[language_code{r}#25708],[language_code{f}#25718],[country{f}#25716, language_name{f}#25719]]	
              |_LocalSourceExec[[language_code{r}#25708],org.elasticsearch.xpack.esql.plan.logical.local.CopyingLocalSupplier@1ef1bc4]	
              \_EsQueryExec[languages_lookup_non_unique_key], indexMode[lookup], query[][_doc{f}#25720], limit[], sort[] estimatedRowSize[104]
    }
  ],
  query={took_millis=14, start_millis=1754605547195, stop_millis=1754605547209, took_nanos=14013972},
  drivers=[
    {
      cluster_name=test-cluster, sleeps={last=[], counts={}, first=[]}, cpu_nanos=3189539,
      operators=[
        {operator=LocalSourceOperator},
        {
          operator=LookupOperator[
            index=languages_lookup_non_unique_key
            input_type=INTEGER
            match_field=language_code
            load_fields=[country{f}#25716, language_name{f}#25719]
            inputChannel=0
          ],
          status={received_pages=0, total_terms=4, emitted_pages=1, process_nanos=0, completed_pages=0}
        },
        {
          operator=TopNOperator[
            count=0/1000,
            elementTypes=[INT, BYTES_REF, BYTES_REF],
            encoders=[DefaultSortable, UTF8TopNEncoder, UTF8TopNEncoder],
            sortOrders=[SortOrder[channel=0, asc=true, nullsFirst=false], SortOrder[channel=2, asc=true, nullsFirst=false], SortOrder[channel=1, asc=true, nullsFirst=false]]
          ],
          status={receive_nanos=36566, emit_nanos=33132, occupied_rows=0, rows_emitted=1, pages_emitted=1, ram_used=4.2kb, rows_received=1, pages_received=1, ram_bytes_used=4368}
        },
        {operator=ProjectOperator[projection = [0, 2, 1]], status={pages_processed=1, rows_emitted=1, process_nanos=2856, rows_received=1}},
        {operator=OutputOperator[columns = [language_code, language_name, country]]}
      ],
      node_name=test-cluster-1,
      description=single,
      documents_found=0,
      start_millis=1754605547205,
      stop_millis=1754605547208,
      values_loaded=0,
      iterations=3124,
      took_nanos=3432530
    }
  ]
}
```

The LookupOperator has this strange status:
`status={received_pages=0, total_terms=4, emitted_pages=1, process_nanos=0, completed_pages=0}`

0 received pages, 0 completed pages, 0 prcess_nanos, but 4 total terms and 1 emitted page. All the 0s come from `AsyncOperator`, while the others come from `LookupFromIndexOperator`.

After some investigation, the `received_pages` and `completed_pages` were actually wrong (Fixed in https://github.com/elastic/elasticsearch/pull/132738), but the process_nanos shows the issue:  That part of the code didn't get to execute yet.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java [hunk 1]
```diff
@@ -241,7 +238,7 @@ public IsBlockedResult isBlocked() {
 
     @Override
     public final Operator.Status status() {
-        return status(Math.max(0L, checkpoint.getMaxSeqNo()), Math.max(0L, checkpoint.getProcessedCheckpoint()), processNanos.sum());
+        return status(checkpoint.getMaxSeqNo() + 1, checkpoint.getProcessedCheckpoint() + 1, processNanos.sum());
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java]: @dnhatn , could you have a look at this bit?

Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java]: Actually, this whole PR to be honest. It's the kind of thing I don't trust myself with. Obviously, I broke it in the first place.

**Review by nik9000 — APPROVED** [review]
Looks better to me. Let @dnhatn look too please.

**Comment by dnhatn** [comment]
Thanks Ivan!

I think the problematic sequence is: `onSeqNoCompleted(seqNo)` → `close()` → `responseHeadersCollector.finish()` → `responseHeadersCollector.collect()` → `driverContext.removeAsyncAction()`, where `responseHeadersCollector.finish()` is called before `responseHeadersCollector.collect()`. This PR prevents that sequence. However, we should not increase the sequence number in onFailure() (call onSeqNoCompleted), as it may cause a NullPointerException later: https://github.com/elastic/elasticsearch/blob/b504514c31de7abca8224d8bc58c314cc0607b2f/x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java#L168

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java [hunk 2]
```diff
@@ -95,19 +95,16 @@ public void addInput(Page input) {
...
                 releasePageOnAnyThread(input);
                 failureCollector.unwrapAndCollect(e);
-                onSeqNoCompleted(seqNo);
             });
             final long startNanos = System.nanoTime();
             performAsync(input, ActionListener.runAfter(listener, () -> {
                 responseHeadersCollector.collect();
-                driverContext.removeAsyncAction();
                 processNanos.add(System.nanoTime() - startNanos);
+                onSeqNoCompleted(seqNo);
```
Comment (ivancea) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java:106]: (Answering you here @dnhatn, as to have a thread)

>This PR prevents that sequence. However, we should not increase the sequence number in onFailure() (call onSeqNoCompleted), as it may cause a NullPointerException later

From what I see, there's already an `if (fetched != null)` there on line 170, so no possible NPE, unless you mean something else or I missed something 👀 

https://github.com/elastic/elasticsearch/blob/9f927b22533a20e5435236a03ee2afd7e0546368/x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java#L165-L174

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java]: Hey! This change feels a bit mystic. It's properly tested in [the other PR](https://github.com/elastic/elasticsearch/pull/132738), where I fix and test multiple things around the status() here.

I'll remove it from here, it doesn't make sense in this PR, and I wanted only the other bugfix to be here!

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java (hunk 2 above)
Comment (dnhatn) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/AsyncOperator.java:106]: Thanks Ivan. I took another closer look. I think we are all good.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Ivan!
