### PR TITLE
Remove LateParsingQuery to prevent timestamp access after context is frozen

### LINKED ISSUE #21295: Strict shard request cache in 5.0 should automatically not cache non-deterministic queries  rather than throw an error
**Elasticsearch version**: 
5.0

**Plugins installed**: 
Waiting on more info can backfill once collected.

**JVM version**: 
1.8.x (waiting on confirmation)

**OS version**:
Waiting on more info

**Description of the problem including expected versus actual behavior**:

Running a bool query with a range using "now" in the query throws an error due to the shard request cache refusing to cache it:

eg the range portion of a sample query:

```
        {
          "range": {
            "sentAt": {
              "from": "now-2M",
              "to": "now-1M",
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
```
A full example query is here:
https://gist.github.com/geekpete/9b9d61dea18a86b47ce6d85d3ed6b839

**Steps to reproduce**:
 1. Use elasticsearch 5.0
 2. Run a range query (in this case was a bool query that used range
 3. Receive a RemoteTransportException with "features that prevent cachability are disabled on this context":

**Provide logs (if relevant)**:
```
RemoteTransportException[[ZRykcOY][XXXX:xxxx][indices:data/read/search[phase/fetch/id]]]; nested: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [message]]]; nested: ElasticsearchParseException[could not read the current timestamp]; nested: IllegalArgumentException[features that prevent cachability are disabled on this context]; 
```

The new version of Elasticsearch has the Shard Request Cache on by default and it's suggest that to avoid this error when using "now" in queries that the cache be disabled per-request, index-wide or cluster-wide:
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/shard-request-cache.html

An alternative to this behaviour might be to automatically not cache the requests that cannot be cached without throwing an error. Perhaps provide detail in the logs at debug level (or whatever level is suitable) whenever this occurs per request "features detected that prevent cachability" so that users can still debug when this is occurring such as when performance isn't good and the user expects that the requests are being cached.

### PR DESCRIPTION
**Pull request by s1monw**
Today we still have a leftover from older percolators where Lucene
query instances where created ahead of time and rewritten later.
This `LateParsingQuery` was resolving `now()` when it's really used which we
don't need anymore. As a side-effect this failed to execute some highlighting
queries when they get rewritten since at that point `now` access it not permitted
anymore to prevent bugs when queries get cached.

Closes #21295

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
I remember this query caused some troubles with the query refactoring and its tests. I found a comment in `RangeQueryBuilderTests`, see https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java#L130 . That test needs some updating I guess.

**Comment by s1monw** [comment]
@javanna good call I fixed the test and removed another late parsing query from the legacy mapper. Can you take a look at the test parts?

File: core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java [hunk 1]
```diff
@@ -270,7 +330,7 @@ public void testDateRangeBoundaries() throws IOException {
                 "        }\n" +
                 "    }\n" +
                 "}\n";
-        Query parsedQuery = parseQuery(query).toQuery(createShardContext()).rewrite(null);
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java]: for my education, why are the rewrite calls gone here? or maybe the right question is why we were calling rewrite before?

File: core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java [hunk 2]
```diff
@@ -2974,12 +2974,12 @@ public void testHighlightQueryRewriteDatesWithNow() throws Exception {
                     .preTags("<x>")
                     .postTags("</x>")
                 ).setQuery(QueryBuilders.boolQuery().must(
-                    QueryBuilders.rangeQuery("d").gte("now-7d/d").lte("now").includeLower(true).includeUpper(true).boost(1.0f))
+                    QueryBuilders.rangeQuery("d").gte("now-12h").lte("now").includeLower(true).includeUpper(true).boost(1.0f))
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java]: why did we have to change the range for this test?

File: core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java (hunk 1 above)
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java]: well today if you rewrite you get what used to be `rewrite(null).rewrite(null)` since we had an indirection. it's gone so if you really rewrite and you have a termrange you get a MTQ which is not expected

**Review by javanna — APPROVED** [review]
left two questions, LGTM though

File: core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java (hunk 1 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/RangeQueryBuilderTests.java]: ah right cause the LateParsingQuery is gone, makes sense thanks!

File: core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java (hunk 2 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java]: sounds good
