### PR TITLE
Fix windows memory locking

### LINKED ISSUE #111847: Elasticsearch 8.15 fails to start on Windows with bootstrap.memory_lock
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Windows Server 2019

### Problem Description

When Elasticsearch is installed on Windows 2019 with bootstrap.memory_lock it fails to load with the error.

AssertionError: java.lang.invoke.WrongMethodTypeException: handle's method type (MemorySegment,long,long)MemorySegment but found (MemorySegment,MemorySegment,long,long)boolean
at org.elasticsearch.nativeaccess.jdk.JdkKernel32Library.SetProcessWorkingSetSize(JdkKernel32Library.java:228) elasticsearch-native-8.15.0.jar

### Steps to Reproduce

Install Elasticsearch on Windows and set bootstrap.memory_lock to true.

### Logs (if relevant)

AssertionError: java.lang.invoke.WrongMethodTypeException: handle's method type (MemorySegment,long,long)MemorySegment but found (MemorySegment,MemorySegment,long,long)boolean
at org.elasticsearch.nativeaccess.jdk.JdkKernel32Library.SetProcessWorkingSetSize(JdkKernel32Library.java:228) elasticsearch-native-8.15.0.jar

### PR DESCRIPTION
**Pull request by rjernst**
Memory locking on Windows with the bundled jdk was broken by native access refactoring. This commit fixes the linking issue, as well as adds a packaging test to ensure memory locking is invoked on all supported platforms.

closes #111847

### CODE REVIEW

File: qa/packaging/src/test/java/org/elasticsearch/packaging/test/MemoryLockingTests.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+            "true",
+            "xpack.security.enabled",
+            "false",
+            "xpack.security.http.ssl.enabled",
+            "false",
+            "xpack.security.enrollment.enabled",
+            "false",
+            "discovery.type",
+            "single-node"));
+        // TODO: very locking worked. logs? check memory of process? at least we know the process started successfully
```
Comment (ldematte) [inline qa/packaging/src/test/java/org/elasticsearch/packaging/test/MemoryLockingTests.java:37]: I think the best (but complicated) way of doing this it to check the memory of the process, by calling VirtualQueryEx (and/or the equivalent function under linux/macos) from the test. 
It does work cross process, so it should be possible to do that even in a test that spawns an external cluster. No idea how to do that with a docker test though...
Another idea: expose the information we need via an `_nodes/stats` (under os.mem maybe?). Could be useful regardless (e.g. for diagnostics)

**Review by ldematte — APPROVED** [review]
Looks good, left one suggestion on how to test
