### PR TITLE
Convert InternalAggTestCase to AbstractNamedWriteableTestCase

### LINKED ISSUE #55149: [CI] SignificantLongTermsTests.testReduceRandom failure on 7x
This reliably reproduces:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.significant.SignificantLongTermsTests.testReduceRandom" \
  -Dtests.seed=A4C0204845ED86F5 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=America/North_Dakota/New_Salem \
  -Dcompiler.java=14
```

```
org.elasticsearch.search.aggregations.bucket.significant.SignificantLongTermsTests > testReduceRandom FAILED
    java.io.EOFException
        at __randomizedtesting.SeedInfo.seed([A4C0204845ED86F5:64FD8C5963B01FA3]:0)
        at org.elasticsearch.common.bytes.BytesReferenceStreamInput.readByte(BytesReferenceStreamInput.java:51)
        at org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper.readByte(AbstractBytesReference.java:202)
        at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:40)
        at org.elasticsearch.common.io.stream.StreamInput.readVInt(StreamInput.java:227)
        at org.elasticsearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:1265)
        at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:418)
        at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:38)
        at org.elasticsearch.search.aggregations.bucket.significant.InternalMappedSignificantTerms.<init>(InternalMappedSignificantTerms.java:61)
        at org.elasticsearch.search.aggregations.bucket.significant.SignificantLongTerms.<init>(SignificantLongTerms.java:114)
        at org.elasticsearch.test.ESTestCase.copyInstance(ESTestCase.java:1236)
        at org.elasticsearch.test.ESTestCase.copyWriteable(ESTestCase.java:1206)
        at org.elasticsearch.test.AbstractWireSerializingTestCase.copyInstance(AbstractWireSerializingTestCase.java:44)
```

### PR DESCRIPTION
**Pull request by polyfractal**
Some aggregations, such as the Terms* family, will use an alternate class to represent unmapped shard results (while the rest of the aggs use the same object but with some form of "empty" or "nullish" values to represent unmapped).

This was problematic with AbstractWireSerializingTestCase because it expects the instanceReader to always match the original class.  Instead, we need to use the NamedWriteable version so that the registry can be consulted for the proper deserialization reader.

Fixes https://github.com/elastic/elasticsearch/issues/55149

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java [hunk 1]
```diff
@@ -166,7 +166,7 @@
 import static org.hamcrest.Matchers.hasSize;
 import static org.hamcrest.Matchers.lessThanOrEqualTo;
 
-public abstract class InternalAggregationTestCase<T extends InternalAggregation> extends AbstractWireSerializingTestCase<T> {
+public abstract class InternalAggregationTestCase<T extends InternalAggregation> extends AbstractNamedWriteableTestCase<T> {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:169]: Could this be `extends AbstactNamedWriteableTestCase<InternalAggregation>`?

Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:169]: I think it is worth adding a comment that subclasses need to make sure that `xContentRegistry` includes the agg we're going to parse. Built in aggs are included automatically but other aggs won't be.

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java [hunk 2]
```diff
@@ -282,6 +282,16 @@ protected T createUnmappedInstance(String name, Map<String, Object> metadata) {
         return createTestInstance(name, metadata);
     }
 
+    /**
+     * The NamedWriteable class for agg tests _should_ be InternalAggregation so this is being set by default,
+     * but implementors can change if necessary
+     */
+    @Override
+    @SuppressWarnings("unchecked")
+    protected Class<T> categoryClass() {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:291]: Could this be `final`?

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java (hunk 1 above)
Comment (polyfractal) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:169]: Probably, i'll check!

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java (hunk 2 above)
Comment (polyfractal) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:291]: It could be.  I left it non-final in case an implementor needs to override it for some reason.  But I suppose with the generic bounds on <InternalAggregation> it's pretty definitive what the class should be...

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java (hunk 1 above)
Comment (polyfractal) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:169]: I think it needs to remain `<T>`... `AbstractWireTestCase#mutateInstance()` takes the `T`, so if we change it to `<InternalAggregation>` it forces signatures like

```
protected InternalBoxplot mutateInstance(InternalBoxplot instance) {
```

to be

```
protected InternalAggregation mutateInstance(InternalAggregation instance) {
```
and requires a bunch of extra casting.

Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:169]: Got it!

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java (hunk 2 above)
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:291]: I do think this should be `final` then. I guess the `suppresswarnings` means that the bounds on `AbstractNamedWriteableTestCase` are wrong.

Comment (polyfractal) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:291]: Yeah to be honest I really have no idea what's going on with the generic... scratched my head over it for a while and just gave up :/ 

I'll make `final` :+1:

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java (hunk 1 above)
Comment (polyfractal) [reply test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:179]: Buncha xpack tests needed this treatment, and it was non-trivial for tests to convert aggspecs into namedwriteables, so I did a bit of refactoring to make it easier in the general case.

File: test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java [hunk 3]
```diff
@@ -270,6 +279,58 @@ public ReduceContext forFinalReduction() {
...
+
+    /**
+     * Implementors can override this if they want to provide a custom list of namedWriteables.  If the implementor
+     * _just_ wants to register in namedWriteables provided by a plugin, prefer overriding
+     * {@link InternalAggregationTestCase#registerPlugin()} instead because that route handles the automatic
+     * conversion of AggSpecs into namedWriteables.
+     */
+    protected List<NamedWriteableRegistry.Entry> getNamedWriteables() {
+        List<NamedWriteableRegistry.Entry> entries
+            = new ArrayList<>(new SearchModule(Settings.EMPTY, emptyList()).getNamedWriteables());
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/InternalAggregationTestCase.java:300]: If you pass the plugins in instead of `emptyList()` then I think `SearchModule` will do this stuff for you.

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
Thanks @nik9000!
