### PR TITLE
[Test] Properly clean up resources after test class finishes

### LINKED ISSUE #94939: [CI] RemoteClusterSecurityRestIT and RemoteClusterSecuritySpecialUserIT and RemoteClusterSecurityWithSameModelRemotesRestIT classMethods failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/3wwnehg5i63ow/tests/:x-pack:plugin:security:qa:multi-cluster:javaRestTest/org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT&tests.test=classMethod

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([8D2E6C76D2C38EC3]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:236)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:241)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:68)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:39)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

  Caused by: java.util.concurrent.CancellationException: Request execution cancelled

    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:114)
    at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
    at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.performRequestAgainstFulfillingCluster(AbstractRemoteClusterSecurityTestCase.java:173)
    at org.elasticsearch.xpack.remotecluster.AbstractRemoteClusterSecurityTestCase.createCrossClusterAccessApiKey(AbstractRemoteClusterSecurityTestCase.java:127)
    at org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT.lambda$static$0(RemoteClusterSecurityRestIT.java:69)
    at org.elasticsearch.test.cluster.local.AbstractLocalSpecBuilder.lambda$keystore$12(AbstractLocalSpecBuilder.java:165)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.lambda$resolveKeystore$1(LocalClusterSpec.java:244)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.resolveKeystore(LocalClusterSpec.java:244)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.getSetting(LocalClusterSpec.java:208)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.isMasterEligible(LocalClusterSpec.java:194)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
    at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at org.elasticsearch.test.cluster.local.DefaultSettingsProvider.get(DefaultSettingsProvider.java:73)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.lambda$resolveSettings$0(LocalClusterSpec.java:226)
    at java.util.ArrayList.forEach(ArrayList.java:1511)
    at org.elasticsearch.test.cluster.local.LocalClusterSpec$LocalNodeSpec.resolveSettings(LocalClusterSpec.java:226)
    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.writeConfiguration(LocalClusterFactory.java:331)
    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.start(LocalClusterFactory.java:139)
    at org.elasticsearch.test.cluster.local.LocalClusterHandle.lambda$start$0(LocalClusterHandle.java:68)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
    at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
    at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
    at org.elasticsearch.test.cluster.local.LocalClusterHandle.lambda$start$1(LocalClusterHandle.java:68)
    at org.elasticsearch.test.cluster.local.LocalClusterHandle.lambda$execute$14(LocalClusterHandle.java:242)
    at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1456)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

### PR DESCRIPTION
**Pull request by ywangd**
The clients are mutable static fields on the base test classs. If they are not properly reset when a test class finishes, subsequent test class (that shares the same base class) running in the same JVM will see the partial value and fail. This PR ensures the client fields are set back to null after test class finishes.

Resolves: #94939

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I think these are similar failures not on Windows:

- https://gradle-enterprise.elastic.co/s/ssvyx7xcnoa2k
- https://gradle-enterprise.elastic.co/s/oopv3w6pwdse4

So I think we shouldn't unmute these tests like this.

**Comment by ywangd** [comment]
Thanks David. I certainly overlooked the failure history. Will take a second look into it.

**Review by n1v0lg — APPROVED** [review]
LGTM!

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/AbstractRemoteClusterSecurityTestCase.java [hunk 1]
```diff
@@ -100,7 +100,11 @@ static RestClient buildRestClient(ElasticsearchCluster targetCluster) {
 
     @AfterClass
     public static void closeFulFillingClusterClient() throws IOException {
```
Comment (DaveCTurner) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/AbstractRemoteClusterSecurityTestCase.java:102]: naming nit:

```suggestion
    public static void closeFulfillingClusterClient() throws IOException {
```

**Review by DaveCTurner — APPROVED** [review]
Ah great, that makes more sense. LGTM (one nearby nit)

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-2-windows elasticsearch-ci/packaging-tests-windows-sample

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-2-windows

**Comment by ywangd** [comment]
I am going to ignore the failure of `part-2-windows` and merge this PR. This pariticular job keeps failing due to missing checksum for jdk artefact `windows-8u302-x64`. 
```
> Dependency verification failed for configuration ':x-pack:qa:rolling-upgrade:checkstyle':
  - On artifact windows-8u302-x64.zip (adoptium_8:windows:8u302) in repository 'jdk_repo_adoptium_8u302+b08': checksum is missing from verification metadata.
```
The job is not part of the normal PR CI. I added it (along with a few other Windows related jobs) because I mistakenly thought the associated issue was Windows specific. Since we now understand it is not the case, having windows CI jobs running as part of the PR is no longer necessary.
