### PR TITLE
Fix keep_alive of derived context of point in time

### LINKED ISSUE #67307: FrozenIndexIT.testRetryPointInTime
May be this is just one off failure, and should be ignored. Please feel free to close

**Build scan**:
https://gradle-enterprise.elastic.co/s/3tlvmqrujbggq

**Repro line**:
./gradlew ':x-pack:plugin:frozen-indices:internalClusterTest' --tests "org.elasticsearch.index.engine.FrozenIndexIT.testRetryPointInTime" -Dtests.seed=DCA39E4A873000C6 -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Europe/Skopje -Druntime.java=11	

**Reproduces locally?**:
no

**Applicable branches**:
was failed on PR for master branch

**Failure history**:

**Failure excerpt**:
```bash

java.lang.AssertionError: Unexpected ShardFailures: [shard [[UYO248ViTFGMo9H2xCimwQ][test][0]], reason [org.elasticsearch.transport.RemoteTransportException: [node_s0][127.0.0.1:34427][indices:data/read/search[phase/fetch/id]] |  
-- | --
  | Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [1] |  
  | at org.elasticsearch.search.SearchService.findReaderContext(SearchService.java:623) |  
  | at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:586) |  
  | at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$12(SearchTransportService.java:363) |  
  | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) |  
  | at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:805) |  
  | at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:125) |  
  | at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:749) |  
  | at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:663) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:714) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:706) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:182) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:172) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.executeFetch(FetchSearchPhase.java:176) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:156) |  
  | at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:739) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  | ], cause [org.elasticsearch.search.SearchContextMissingException: No search context found for id [1] |  
  | at org.elasticsearch.search.SearchService.findReaderContext(SearchService.java:623) |  
  | at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:586) |  
  | at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$12(SearchTransportService.java:363) |  
  | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) |  
  | at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:805) |  
  | at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:125) |  
  | at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:749) |  
  | at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:663) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:714) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:706) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:182) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:172) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.executeFetch(FetchSearchPhase.java:176) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:156) |  
  | at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:739) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  | ]] |  
  | Expected: <0> |  
  | but: was <1>


```

### PR DESCRIPTION
**Pull request by dnhatn**
The reaper can remove derived contexts of a point in time between query and fetch phases as their keep_alive is unset (-1).

Closes #67307

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 1]
```diff
@@ -672,16 +672,15 @@ final ReaderContext createAndPutReaderContext(ShardSearchRequest request, IndexS
...
             if (keepStatesInContext || request.scroll() != null) {
-                readerContext = new LegacyReaderContext(id, indexService, shard, reader, request, keepAlive);
+                readerContext = new LegacyReaderContext(id, indexService, shard, reader, request, keepAliveInMillis);
                 if (request.scroll() != null) {
                     readerContext.addOnClose(decreaseScrollContexts);
                     decreaseScrollContexts = null;
                 }
             } else {
-                readerContext = new ReaderContext(id, indexService, shard, reader, keepAlive, request.keepAlive() == null);
+                readerContext = new ReaderContext(id, indexService, shard, reader, keepAliveInMillis, true);
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:683]: Should it be:

```suggestion
                readerContext = new ReaderContext(id, indexService, shard, reader, keepAliveInMillis, request.readerId() == null);
```
?

**Review by jimczi — APPROVED** [review]
I left one comment, LGTM otherwise

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:683]: I think all search contexts that we created here should be a single-session; otherwise, we will leak them when the query phase returns no result. We should only create multiple-session contexts when we explicitly [open a point in time](https://github.com/elastic/elasticsearch/blob/29192e591cb62f1b6ace13073fda23b448f69be3/server/src/main/java/org/elasticsearch/search/SearchService.java#L725). This is not an issue in the previous versions as we never create a search context when the readerId is specified.

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:683]: Right, thanks for clarifying.

**Comment by dnhatn** [comment]
Thanks Jim.
