### PR TITLE
Source filtering: only accept array items if the previous include pattern matches

### LINKED ISSUE #22557: source filtering (_source) field matching too loose
**Elasticsearch version**:  `5.1`

**Plugins installed**: none

**JVM version**: 
```
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
**OS version**: `Ubuntu 14.04.1 LTS`

**Description of the problem including expected versus actual behavior**:

I don't know if this is a bug or a feature, but in my opinion it shouldn't work like that.

When filtering source (`_source`), there are returned fields that contain only part of the string.

Let's say we have source object looking like this: 
```
{
    "photos": ["a.jpg", "b.jpg"],
    "photosCount": 2
}
```
When filtering like this: `"_source": ["photosCount"]`, `photos` field is also returned.
(same for `"_source": "photosCount"` and `"_source": {"include": ["photosCount"]}`)
Now I have to explicitly exclude `photos`, for not having it in response.

**Steps to reproduce**:

 1.
```
curl -XPOST 'localhost:9200/some_thing/some_type' -d '
{
    "photos": ["a.jpg", "b.jpg"],
    "photosCount": 2
}
```
 2.
```
curl -XPOST 'localhost:9200/some_thing/some_type/_search?pretty' -d '
{
  "_source": "photosCount",
  "query": {}
}
```

### PR DESCRIPTION
**Pull request by mikemccand**
Source filtering was incorrectly always accepting array items even if the include pattern did not match.

Closes #22557

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java [hunk 1]
```diff
@@ -251,19 +251,17 @@ public void testNestedFiltering() {
...
-        assertThat(falteredMap.size(), equalTo(1));
+        Map<String, Object> filteredMap = XContentMapValues.filter(map, new String[]{"array.nested"}, Strings.EMPTY_ARRAY);
+        assertThat(filteredMap.size(), equalTo(1));
 
-        // Selecting members of objects within arrays (ex. [ 1, { nested: "value"} ])  always returns all values in the array (1 in the ex)
-        // this is expected behavior as this types of objects are not supported in ES
-        assertThat((Integer) ((List) falteredMap.get("array")).get(0), equalTo(1));
-        assertThat(((Map<String, Object>) ((List) falteredMap.get("array")).get(1)).size(), equalTo(1));
-        assertThat((Integer) ((Map<String, Object>) ((List) falteredMap.get("array")).get(1)).get("nested"), equalTo(2));
+        assertThat(((List) filteredMap.get("array")).size(), equalTo(1));
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java]: `assertThat((List) filteredMap.get("array"), hasSize(1))` has better error messages.

Comment (nik9000) [inline core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java]: But you are just fixing a typo so you can skip it.

**Review by nik9000 — APPROVED** [review]

File: core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java (hunk 1 above)
Comment (mikemccand) [inline core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java]: Oh thank you for that pointer; I didn't know about `hasSize` ... I'll change it

**Comment by mikemccand** [comment]
OK I switched to `hasSize` and I also discovered that you can't use that for `Map` yet ... that's coming in next release of Hamcrest I guess.

**Comment by nik9000** [comment]
> you can't use that for Map yet ... that's coming in next release of Hamcrest I guess.

Oh!

**Review by nik9000 — APPROVED** [review]
