### PR TITLE
Fix put mappings java API documentation

### LINKED ISSUE #31906: [Doc] Update "Java API Administration >> Indices Administration" page
[This](https://www.elastic.co/guide/en/elasticsearch/client/java-api/6.3/java-admin-indices.html#java-admin-indices-put-mapping) example in the Java API Administration docs does not work correctly and is very miss leading.

Example reads:
```
client.admin().indices().prepareCreate("twitter")   
        .addMapping("\"tweet\": {\n" +              
                "  \"properties\": {\n" +
                "    \"message\": {\n" +
                "      \"type\": \"text\"\n" +
                "    }\n" +
                "  }\n" +
                "}")
        .get();
```

This example works, but it does not create the index correctly it seems, the example should read
```
client.admin.indices().prepareCreate("twitter")
         .addMapping("tweet", "message", "type=text").get();
```

### PR DESCRIPTION
**Pull request by cbuescher**
The current docs of the [put-mapping Java API](https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/java-admin-indices.html#java-admin-indices-put-mapping) is currently broken. In its current
form, it creates an index and uses the whole mapping definition given as a JSON
string as the type name. Since we didn't check the index created in the
IndicesDocumentationIT, this went unnoticed so far.

This change adds test to catch this error to the documentation test, changes the
documentation so it works correctly now and adds an input validation to
PutMappingRequest#buildFromSimplifiedDef() which was used internally to reject
calls where no mapping definition is given.

Closes #31906

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java [hunk 1]
```diff
@@ -48,16 +54,14 @@ public void testPutMappingDocumentation() throws Exception {
...
-        client.admin().indices().prepareCreate("twitter")   // <1>
-                .addMapping("\"tweet\": {\n" +              // <2>
-                        "  \"properties\": {\n" +
-                        "    \"message\": {\n" +
-                        "      \"type\": \"text\"\n" +
-                        "    }\n" +
-                        "  }\n" +
-                        "}")
+        client.admin().indices().prepareCreate("twitter")    // <1>
+                .addMapping("tweet", "message", "type=text") // <2>
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java]: I wasn't sure which of the three "addMapping" variants to use in the client API docs, but went with this one since I think its the simplest. Both alternatives `addMapping(String type, Map<String, Object> source)` and `addMapping(String type, XContentBuilder source)` would require to setup a builder or a map with the mapping first, which would make this example quiet bloated IMHO.

File: server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java [hunk 2]
```diff
@@ -89,6 +93,11 @@ public void testPutMappingDocumentation() throws Exception {
                 "}", XContentType.JSON)
         .get();
         // end::putMapping-request-source
+        getMappingsResponse = client.admin().indices().prepareGetMappings("twitter").get();
+        assertEquals(1, getMappingsResponse.getMappings().size());
+        indexMapping = getMappingsResponse.getMappings().get("twitter");
+        assertThat(indexMapping.get("user"), instanceOf(MappingMetaData.class));
```
Comment (pcsanwald) [inline server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java]: do we really need this assertion, given the one immediately following? this feels like it could be an implementation detail.

File: server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java [hunk 3]
```diff
@@ -89,6 +93,11 @@ public void testPutMappingDocumentation() throws Exception {
...
+        assertThat(indexMapping.get("user").getSourceAsMap().toString(), equalTo("{properties={name={type=text}}}"));
```
Comment (pcsanwald) [inline server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java]: small thing, but the `toString` comparison feels a bit brittle here: whitespace and other kind of cosmetic changes can break this prettty easily. could we instead assert on the Map using `containsKey` or similar?

**Review by pcsanwald — APPROVED** [review]
Few small comments, but I'll defer to your judgement on any of these are worth fixing.

File: server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java (hunk 3 above)
Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java]: Yes, I was thinking about this but wanted to avoid few extra lines of code here, since I found they would also make the test harder to read. I generally agree with "toString" being brittle. In this case, since most maps use AbstractMap#toString(), it should be quite stable though. So maybe okay to trade for succinctness and readability here, wdyt?

Comment (pcsanwald) [reply server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java]: I'm good with your reasoning.

Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/client/documentation/IndicesDocumentationIT.java]: Actually, I found a way that avoids "toString()" and is quite short as well, please take a look at the next commit to see if you like this better.
