### PR TITLE
Fix failing ICU tests

### LINKED ISSUE #35173: analysis icu rest test fails: analysis_icu/10_basic/Normalization*
Reproduce:
```
./gradlew plugins:analysis-icu:check
```
( remember to remove the blacklist from `build.gradle`, tests were muted ) 

```
Suite: org.elasticsearch.index.analysis.IcuClientYamlTestSuiteIT
  1> [2018-11-02T04:23:04,231][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Tokenizer] before test
  1> [2018-11-02T04:23:04,279][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] initializing REST clients against [http://[::1]:44335]
  1> [2018-11-02T04:23:04,491][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] initializing client, minimum es version [7.0.0-alpha1], master version, [7.0.0-alpha1], hosts [http://[::1]:44335]
  1> [2018-11-02T04:23:04,652][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Tokenizer] after test
  1> [2018-11-02T04:23:04,662][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization filter] before test
  1> [2018-11-02T04:23:04,686][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization filter] after test
  1> [2018-11-02T04:23:04,690][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Folding filter] before test
  1> [2018-11-02T04:23:04,704][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Folding filter] after test
  1> [2018-11-02T04:23:04,707][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/20_search/Index ICU content] before test
  1> [2018-11-02T04:23:05,212][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/20_search/Index ICU content] after test
  1> [2018-11-02T04:23:05,215][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization with a UnicodeSet Filter] before test
  1> [2018-11-02T04:23:05,259][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "error" : {
  1>         "root_cause" : [
  1>           {
  1>             "type" : "remote_transport_exception",
  1>             "reason" : "[node-0][127.0.0.1:46817][indices:admin/analyze[s]]",
  1>             "stack_trace" : "[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]]; nested: RemoteTransportException[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]]; nested: IllegalArgumentException[failed to find tokenizer under [keyword]];
  1>    at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639)
  1>    at org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:567)
  1>    at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)
  1>    at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
  1>    at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)
  1>    at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)
  1>    at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:72)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:239)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:220)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1100(TransportSingleShardAction.java:145)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:277)
  1>    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1127)
  1>    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1244)
  1>    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1218)
  1>    at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66)
  1>    at org.elasticsearch.action.support.HandledTransportAction$ChannelActionListener.onFailure(HandledTransportAction.java:103)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.onFailure(TransportSingleShardAction.java:113)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:711)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  1>    at java.base/java.lang.Thread.run(Thread.java:834)
  1> Caused by: RemoteTransportException[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]]; nested: IllegalArgumentException[failed to find tokenizer under [keyword]];
  1> Caused by: java.lang.IllegalArgumentException: failed to find tokenizer under [keyword]
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:720)
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:194)
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:169)
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:118)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  1>    at java.base/java.lang.Thread.run(Thread.java:834)
  1> "
  1>           }
  1>         ],
  1>         "type" : "illegal_argument_exception",
  1>         "reason" : "failed to find tokenizer under [keyword]",
  1>         "stack_trace" : "java.lang.IllegalArgumentException: failed to find tokenizer under [keyword]
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:720)
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:194)
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:169)
  1>    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80)
  1>    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:118)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  1>    at java.base/java.lang.Thread.run(Thread.java:834)
  1> "
  1>       },
  1>       "status" : 400
  1>     }
  1>   }
  1> }]
  1> [2018-11-02T04:23:05,273][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization with a UnicodeSet Filter] after test
  2> REPRODUCE WITH: ./gradlew :plugins:analysis-icu:integTestRunner -Dtests.seed=84F8F6CECF95585A -Dtests.class=org.elasticsearch.index.analysis.IcuClientYamlTestSuiteIT -Dtests.method="test {yaml=analysis_icu/10_basic/Normalization with a UnicodeSet Filter}" -Dtests.security.manager=true -Dtests.locale=sg-CF -Dtests.timezone=Australia/Currie -Dcompiler.java=11 -Druntime.java=11
FAILURE 0.06s | IcuClientYamlTestSuiteIT.test {yaml=analysis_icu/10_basic/Normalization with a UnicodeSet Filter} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [analysis_icu/10_basic:68]: expected [2xx] status code but api [indices.analyze] returned [400 Bad Request] [---
   > error:
   >   root_cause:
   >   - type: "remote_transport_exception"
   >     reason: "[node-0][127.0.0.1:46817][indices:admin/analyze[s]]"
   >     stack_trace: "[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]]; nested: RemoteTransportException[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]];\
   >       \ nested: IllegalArgumentException[failed to find tokenizer under [keyword]];\n\
   >       \tat org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639)\n\
   >       \tat org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:567)\n\
   >       \tat org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)\n\
   >       \tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)\n\
   >       \tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)\n\
   >       \tat org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)\n\
   >       \tat org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:72)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:239)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:220)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1100(TransportSingleShardAction.java:145)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:277)\n\
   >       \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1127)\n\
   >       \tat org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1244)\n\
   >       \tat org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1218)\n\
   >       \tat org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66)\n\
   >       \tat org.elasticsearch.action.support.HandledTransportAction$ChannelActionListener.onFailure(HandledTransportAction.java:103)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.onFailure(TransportSingleShardAction.java:113)\n\
   >       \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:711)\n\
   >       \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
   >       \tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: RemoteTransportException[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]];\
   >       \ nested: IllegalArgumentException[failed to find tokenizer under [keyword]];\n\
   >       Caused by: java.lang.IllegalArgumentException: failed to find tokenizer under\
   >       \ [keyword]\n\tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:720)\n\
   >       \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:194)\n\
   >       \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:169)\n\
   >       \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:118)\n\
   >       \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)\n\
   >       \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
   >       \tat java.base/java.lang.Thread.run(Thread.java:834)\n"
   >   type: "illegal_argument_exception"
   >   reason: "failed to find tokenizer under [keyword]"
   >   stack_trace: "java.lang.IllegalArgumentException: failed to find tokenizer under\
   >     \ [keyword]\n\tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:720)\n\
   >     \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:194)\n\
   >     \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:169)\n\
   >     \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80)\n\
   >     \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:118)\n\
   >     \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)\n\
   >     \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\
   >     \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
   >     \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
   >     \tat java.base/java.lang.Thread.run(Thread.java:834)\n"
   > status: 400
   > ]
   >    at __randomizedtesting.SeedInfo.seed([84F8F6CECF95585A:CACC914616935A2]:0)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:384)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
   > Caused by: java.lang.AssertionError: expected [2xx] status code but api [indices.analyze] returned [400 Bad Request] [---
   > error:
   >   root_cause:
   >   - type: "remote_transport_exception"
   >     reason: "[node-0][127.0.0.1:46817][indices:admin/analyze[s]]"
   >     stack_trace: "[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]]; nested: RemoteTransportException[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]];\
   >       \ nested: IllegalArgumentException[failed to find tokenizer under [keyword]];\n\
   >       \tat org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639)\n\
   >       \tat org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:567)\n\
   >       \tat org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)\n\
   >       \tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)\n\
   >       \tat org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)\n\
   >       \tat org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)\n\
   >       \tat org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:72)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:239)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:220)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1100(TransportSingleShardAction.java:145)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:277)\n\
   >       \tat org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1127)\n\
   >       \tat org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1244)\n\
   >       \tat org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1218)\n\
   >       \tat org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66)\n\
   >       \tat org.elasticsearch.action.support.HandledTransportAction$ChannelActionListener.onFailure(HandledTransportAction.java:103)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.onFailure(TransportSingleShardAction.java:113)\n\
   >       \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:711)\n\
   >       \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
   >       \tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: RemoteTransportException[[node-0][127.0.0.1:46817][indices:admin/analyze[s]]];\
   >       \ nested: IllegalArgumentException[failed to find tokenizer under [keyword]];\n\
   >       Caused by: java.lang.IllegalArgumentException: failed to find tokenizer under\
   >       \ [keyword]\n\tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:720)\n\
   >       \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:194)\n\
   >       \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:169)\n\
   >       \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80)\n\
   >       \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:118)\n\
   >       \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)\n\
   >       \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
   >       \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
   >       \tat java.base/java.lang.Thread.run(Thread.java:834)\n"
   >   type: "illegal_argument_exception"
   >   reason: "failed to find tokenizer under [keyword]"
   >   stack_trace: "java.lang.IllegalArgumentException: failed to find tokenizer under\
   >     \ [keyword]\n\tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.parseTokenizerFactory(TransportAnalyzeAction.java:720)\n\
   >     \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:194)\n\
   >     \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:169)\n\
   >     \tat org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:80)\n\
   >     \tat org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:118)\n\
   >     \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)\n\
   >     \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\
   >     \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\
   >     \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\
   >     \tat java.base/java.lang.Thread.run(Thread.java:834)\n"
   > status: 400
   > ]
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:261)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:400)
   >    ... 37 more
  1> [2018-11-02T04:23:05,279][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization charfilter] before test
  1> [2018-11-02T04:23:05,290][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization charfilter] after test
  1> [2018-11-02T04:23:05,292][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization with a CamcelCase UnicodeSet Filter] before test
  1> [2018-11-02T04:23:05,322][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 1]] request [PUT http://[::1]:44335/test?error_trace=true] returned 1 warnings: [299 Elasticsearch-7.0.0-alpha1-SNAPSHOT-77fab62 "[unicodeSetFilter] has been deprecated in favor of [unicode_set_filter]" "Thu, 01 Nov 2018 17:23:05 GMT"]
  1> [2018-11-02T04:23:05,327][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 1]] request [GET http://[::1]:44335/test/_analyze?error_trace=true] returned 1 warnings: [299 Elasticsearch-7.0.0-alpha1-SNAPSHOT-77fab62 "[unicodeSetFilter] has been deprecated in favor of [unicode_set_filter]" "Thu, 01 Nov 2018 17:23:05 GMT"]
  1> [2018-11-02T04:23:05,328][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "tokens" : [
  1>         {
  1>           "token" : "charfilter",
  1>           "start_offset" : 0,
  1>           "end_offset" : 10,
  1>           "type" : "<ALPHANUM>",
  1>           "position" : 0
  1>         },
  1>         {
  1>           "token" : "föo",
  1>           "start_offset" : 11,
  1>           "end_offset" : 14,
  1>           "type" : "<ALPHANUM>",
  1>           "position" : 1
  1>         },
  1>         {
  1>           "token" : "bâr",
  1>           "start_offset" : 15,
  1>           "end_offset" : 18,
  1>           "type" : "<ALPHANUM>",
  1>           "position" : 2
  1>         },
  1>         {
  1>           "token" : "ruß",
  1>           "start_offset" : 19,
  1>           "end_offset" : 22,
  1>           "type" : "<ALPHANUM>",
  1>           "position" : 3
  1>         }
  1>       ]
  1>     }
  1>   }
  1> }]
  1> [2018-11-02T04:23:05,340][INFO ][o.e.i.a.IcuClientYamlTestSuiteIT] [test] [yaml=analysis_icu/10_basic/Normalization with a CamcelCase UnicodeSet Filter] after test
  2> REPRODUCE WITH: ./gradlew :plugins:analysis-icu:integTestRunner -Dtests.seed=84F8F6CECF95585A -Dtests.class=org.elasticsearch.index.analysis.IcuClientYamlTestSuiteIT -Dtests.method="test {yaml=analysis_icu/10_basic/Normalization with a CamcelCase UnicodeSet Filter}" -Dtests.security.manager=true -Dtests.locale=sg-CF -Dtests.timezone=Australia/Currie -Dcompiler.java=11 -Druntime.java=11
FAILURE 0.05s | IcuClientYamlTestSuiteIT.test {yaml=analysis_icu/10_basic/Normalization with a CamcelCase UnicodeSet Filter} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [analysis_icu/10_basic:123]: got unexpected warning header [
   >    299 Elasticsearch-7.0.0-alpha1-SNAPSHOT-77fab62 "[unicodeSetFilter] has been deprecated in favor of [unicode_set_filter]" "Thu, 01 Nov 2018 17:23:05 GMT"
   > ]
   >    at __randomizedtesting.SeedInfo.seed([84F8F6CECF95585A:CACC914616935A2]:0)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:384)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
   > Caused by: java.lang.AssertionError: got unexpected warning header [
   >    299 Elasticsearch-7.0.0-alpha1-SNAPSHOT-77fab62 "[unicodeSetFilter] has been deprecated in favor of [unicode_set_filter]" "Thu, 01 Nov 2018 17:23:05 GMT"
   > ]
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:324)
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:257)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:400)
   >    ... 37 more
  2> NOTE: leaving temporary files on disk at: /home/alpar/work/elastic/elasticsearch/plugins/analysis-icu/build/testrun/integTestRunner/J0/temp/org.elasticsearch.index.analysis.IcuClientYamlTestSuiteIT_84F8F6CECF95585A-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=286, maxMBSortInHeap=7.650042489592934, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@6e0cc929), locale=sg-CF, timezone=Australia/Currie
  2> NOTE: Linux 4.18.14-arch1-1-ARCH amd64/Oracle Corporation 11 (64-bit)/cpus=12,threads=1,free=461970376,total=536870912
  2> NOTE: All tests run in this JVM: [IcuClientYamlTestSuiteIT]
Completed [1/2] in 1.21s, 7 tests, 2 failures <<< FAILURES!


> Task :plugins:analysis-icu:integTestRunner
Tests with failures:
  - org.elasticsearch.index.analysis.IcuClientYamlTestSuiteIT.test {yaml=analysis_icu/10_basic/Normalization with a UnicodeSet Filter}
  - org.elasticsearch.index.analysis.IcuClientYamlTestSuiteIT.test {yaml=analysis_icu/10_basic/Normalization with a CamcelCase UnicodeSet Filter}

JUnit4 test failed, ant output was:
   [junit4] <JUnit4> says नमस्ते! Master seed: 84F8F6CECF95585A
   [junit4] JVM J0:     0.26 ..     4.30 =     4.04s
   [junit4] Execution time total: 4.30 sec.
   [junit4] Tests summary: 2 suites, 17 tests, 2 failures

```

### PR DESCRIPTION
**Pull request by romseygeek**
Fixes #35173

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
@romseygeek took a quick look, can you quickly comment on why the yaml changes are introduced? I saw the checkstyle stuff but wonder if the yaml update is fixing sth. or actually just changing the test to be more specific (from keyword -> standard tokenizer)

**Comment by romseygeek** [comment]
The yaml tests were failing with 'keyword tokenizer not found', I guess due to dependency issues.  The old tests were using standard tokenizer, so it seemed to make sense to use that here as well.

File: plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuNormalizerTokenFilterFactory.java [hunk 1]
```diff
@@ -38,8 +38,10 @@
  * <p>The {@code unicodeSetFilter} attribute can be used to provide the UniCodeSet for filtering.</p>
  */
 public class IcuNormalizerTokenFilterFactory extends AbstractTokenFilterFactory implements MultiTermAwareComponent {
-    private static final DeprecationLogger deprecationLogger =
+
+    private static final DeprecationLogger DEPRECATION_LOGGER =
```
Comment (nik9000) [inline plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuNormalizerTokenFilterFactory.java]: We've been using `deprecationLogger` because the logger does things rather than is a constant.

**Review by nik9000 — APPROVED** [review]
LGTM

File: plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuNormalizerTokenFilterFactory.java (hunk 1 above)
Comment (romseygeek) [reply plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuNormalizerTokenFilterFactory.java]: Have changed it back
