### PR TITLE
Only accept transport requests after node is fully initialized

### LINKED ISSUE #16723: NullPointerException in InternalClusterService.add() using TransportClient
We are using a TransportClient to connect to ES 2.2.0, and getting the following NullPointerException:

! java.lang.NullPointerException: null
! at org.elasticsearch.cluster.service.InternalClusterService.add(InternalClusterService.java:281) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:154) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:99) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retry(TransportMasterNodeAction.java:190) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:164) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:121) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:93) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:50) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:45) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:41) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:244) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:na]
! at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.5.Final.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]
! at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]

We can reproduce this fairly often in our system tests, which starts an ES instance right before starting our client application.  The client application will create a TransportClient, then immediately do a health status check and wait for a yellow status.  If we put a sleep() between creating the TransportClient and the health check, the problem doesn't manifest.

InternalClusterService has an updateTasksExecutor that gets populated by the doStart() method.  The InternalClusterService, however, only appears to be started via Node.start(), which is started via Bootstrap.start(), which is only called by Elasticsearch.main().  In other words, the updateTasksExecutor is only populated when the ES server is run, not when an ES client is used.

The stacktrace above appears to be related to the Transport starting up and not finding a master node.  It then creates a listener to watch for changes to the master node, and tries to add this to the updateTasksExecutor of InternalClusterService, which based on the above paragraph, is null.

I believe we are running into this because we are starting ES immediately before starting our client app, and connecting before a master node has been determined.

Regards,
Ed Howe
Nexidia, Inc.

### PR DESCRIPTION
**Pull request by bleskes**
At the moment we open up the transport service before the local node has been fully initialized. This causes bug as some data structures are not fully initialized yet. See for example #16723. 

Sadly,  we can't just start the TransportService last (as we do with the HTTP server) because the ClusterService needs to know the bound published network address for the local DiscoveryNode. This address can only be determined by actually binding (people may use, for example, port 0). Instead we start the TransportService as late as possible but block any incoming requests until the node has completed initialization. 

A couple of other cleanup during start time:
1) The gateway service now starts before the initial cluster join so we can simplify the logic to recover state if the local node has become master.
2) The discovery is started before the transport service accepts requests, but we only start the join process later using a dedicated method.

Closes #16723

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/transport/TransportService.java [hunk 1]
```diff
@@ -71,7 +72,8 @@
 
     public static final String DIRECT_RESPONSE_PROFILE = ".direct";
 
-    private final AtomicBoolean started = new AtomicBoolean(false);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/transport/TransportService.java]: Can we make this a simple `CountDownLatch` that way we know it's only going in one direction (never move back to blocking), we get the wait for free and don't need to suppress forbidden API?

**Comment by s1monw** [comment]
@bleskes after looking at `InternalClusterService` I would love to explore detaching `TransportSerivce` I think we have a good chance to get it fixed if we:

 * move the LocalNode stuff into TransportService
 * add the reconnect task into a seperate class that is started seperately and depends on both transportservice and ClusterService
 * for the connect stuff we do before we notify listeners should be maybe a listener too? I think it's a messed up dependency in ClusterService?

WDYT

**Comment by bleskes** [comment]
@s1monw I think these are excellent ideas and I will explore them - I totally agree we should decouple the cluster state service from the transport service.  There are some issues to figure out in order to solve the issue where the transport service needs to bind the socket in order to make a DiscoNode , which is in turn used in the very first cluster state. I pushed another commit simplifying things here even further. I think it starts to be simple enough and we can push this without doing a bigger refactoring. It's a judgement call and I defer to your judgement. I'm good with any decision.

**Comment by s1monw** [comment]
@bleskes I think we should do what we have for 2.x and open a followup for master. I mean we can push this to master and make the followup removing this one?

**Comment by bleskes** [comment]
@s1monw will do. Thanks.
