### PR TITLE
Skip downsample IT test with TS command when command not present

### LINKED ISSUE #131500: [CI] DownsampleIT testAggMetricInEsqlTSAfterDownsampling failing
**Build Scans:**
- [elasticsearch-periodic #9440 / release-tests](https://gradle-enterprise.elastic.co/s/vckb5jqnmktem)
- [elasticsearch-pull-request #81648 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/ctxjv64xsm2fm)
- [elasticsearch-periodic #9433 / release-tests](https://gradle-enterprise.elastic.co/s/dvz65noxmdwwm)
- [elasticsearch-periodic #9426 / release-tests](https://gradle-enterprise.elastic.co/s/vypd7cnpansis)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:downsample:internalClusterTest" --tests "org.elasticsearch.xpack.downsample.DownsampleIT.testAggMetricInEsqlTSAfterDownsampling" -Dtests.seed=B42E6BA64185C8C6 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=dav-KE -Dtests.timezone=Pacific/Fakaofo -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.downsample.DownsampleIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAggMetricInEsqlTSAfterDownsampling'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.parser.ParsingException: line 1:1: mismatched input 'TS' expecting {, 'row', 'from', 'show'}
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 4 failures in test testAggMetricInEsqlTSAfterDownsampling (2.7% fail rate in 148 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 3 failures in pipeline elasticsearch-periodic (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by limotova**
Fixes #131500

### CODE REVIEW

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DownsampleIT.java [hunk 1]
```diff
@@ -216,7 +218,11 @@ public void testAggMetricInEsqlTSAfterDownsampling() throws Exception {
         };
         bulkIndex(dataStreamName, nextSourceSupplier, 100);
 
-        if (Build.current().isSnapshot() == false) {
+        // check that TS command is available
+        var response = clusterAdmin().nodesCapabilities(
+            new NodesCapabilitiesRequest().method(RestRequest.Method.POST).path("/_query").capabilities(METRICS_COMMAND.capabilityName())
+        ).actionGet();
+        if (response.isSupported().orElse(Boolean.FALSE) == false) {
```
Comment (dnhatn) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DownsampleIT.java]: Can we use assumeTrue instead?

**Review by dnhatn — APPROVED** [review]
LGTM, thanks Larisa!

**Comment by gmarouli** [comment]
Adding a comment to update github stats. 🤞
