### PR TITLE
Rest tests should be able to wait for running tasks

### LINKED ISSUE #16906: Reindex's rest tests fail frequently in CI
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=ubuntu/487/console
etc

### PR DESCRIPTION
**Pull request by nik9000**
If a task leaks from one test case to another that should fail the test. The tests should have some ability to wait for a task to complete.

Closes #16906

### CODE REVIEW

**Comment by nik9000** [comment]
@imotov can you look at this?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -261,6 +270,8 @@ private static void validateSpec(RestSpec restSpec) {
 
     @After
     public void wipeCluster() throws Exception {
+        // Running tasks might create indices and otherwise invalidate the wipe. Lets just let the finish.
+        waitForAllRunningTasksToFinish();
```
Comment (rjernst) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Hrm, shouldn't deleting an index cause any tasks for that index to be cancelled, internally? Seems this would be something a user could hit, and that we simply did not correctly cleanup all resources when deleting an index?

Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Reindex will create the index its target index if it doesn't already exist. We could probably catch that the source index was removed before creating the new index but that seems like overkill.

Comment (rjernst) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I guess I have 2 concerns. First is a user deleting an index and it causing problems. We shouldn't let this happen; deleting an index should be allowed at any time and it shouldn't cause the user to get into a messed up state. Second is having this custom wait method, when it seems we should just be able to cancel all running tasks, akin to deleting all indices?

Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: > First is a user deleting an index and it causing problems.

It'll cause the reindex request to fail, logging a warning. That seems fine.

> cancel all running tasks

I can try to cancel the tasks if you'd like but they don't always listen to a cancel request and cancellation is async. Reindex only checks the cancel flag in between requests, for example. If I cancel it and it's already started an index request that will create a new index then the index will still be created. 

So I can cancel all the running tasks but I'd still have to check to see that they've killed themselves with the same timeout. I'd just have a different exception message - instead of "timed out waiting for running tasks" it'd be "timed out waiting for tasks to die".

Comment (rjernst) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: > It'll cause the reindex request to fail, logging a warning. That seems fine.

I'm still confused. How did this cause tests to fail then?

Also, why are we kicking off a task in a rest test but never waiting for it to complete? Seems like a reindex rest test succeeding should only happen if the task completed successfully?

Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: > I'm still confused. How did this cause tests to fail then?

Another test tried to create an index with the same name.

> Also, why are we kicking off a task in a rest test but never waiting for it to complete? Seems like a reindex rest test succeeding should only happen if the task completed successfully?

There is no "please only return when this task has successfully completed" API. It'd be a great thing to have one day! For now if you explicitly set `wait_for_completion=false` then it us up to the user to monitor the task. And we have a rest test that verifies that setting wait_for_completion=false returns the task id so the user can do just that. But it can't wait for the task to finish because we don't have that API.

We should build that API. And we will. But we don't have time to build it right now.

Another idea:

Instead of waiting for all tasks to finish after each REST test we just fail the test if there are any tasks still running. And we add a new section that we can use to "wait for the task I just started to finish". When we have the API we can replace the section with the API.

Comment (rjernst) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: What do you mean by a "section", something in the rest test language? If so then I'm in favor of that. But then we should fail hard in rest test cleanup if there are any running tasks (ie the test isn't correctly waiting like it should).

Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: > What do you mean by a "section", something in the rest test language?

Yup. Looks like those things are called `ExecutableSection`s.



> But then we should fail hard in rest test cleanup if there are any running tasks (ie the test isn't correctly waiting like it should).

Yeah, that.

>> Instead of waiting for all tasks to finish after each REST test we just fail the test if there are any tasks still running.

**Comment by nik9000** [comment]
@rjernst I did the things!

**Comment by nik9000** [comment]
I had a voice/video conversation with @imotov about this and I'm going to rewrite it a third time. Two things:

* You can't fail tests if there are tasks running between them. Some tasks are run in the background. For now I'm going to convert it to a WARN level log so that if the task **do** cause failure we can see it in the CI logs. This isn't a great solution but creating a task white or blacklist seems like a large maintenance burden.

* I'm going to add a `wait_for_completion` parameter to the task list API (defaults false) that, when true, will wait for the tasks that it found to finish. It'll probably just poll or something -  I have to figure that out. That way we don't need a new REST test section, all the clients can just use it, and users can use it too.

**Comment by nik9000** [comment]
ok - I've taken a thirds stab at this. I'm not super happy with the implementation of the action but it gets the job done. It feels a bit hacky.

**Comment by nik9000** [comment]
Also I couldn't come up with a great way to unit test the new parameter so I didn't. I'm open to suggestions though.

**Comment by nik9000** [comment]
@imotov / @rjernst can you take another other other look at this?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -285,6 +291,25 @@ public void wipeCluster() throws Exception {
         adminExecutionContext.callApi("snapshot.delete_repository", deleteSnapshotsArgs, Collections.emptyList(), Collections.emptyMap());
     }
 
+    /**
+     * Fails the test if there are still running tasks. The reasoning is that any tasks still running are state the is trying to bleed into
```
Comment (imotov) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Fails -> Logs?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 3]
```diff
@@ -285,6 +291,25 @@ public void wipeCluster() throws Exception {
...
+        Set<String> runningTasks = runningTasks(tasks);
+        // Ignore the task list API - it doens't count against us
+        runningTasks.remove(ListTasksAction.NAME);
+        runningTasks.remove(ListTasksAction.NAME + "[n]");
+        if (runningTasks.isEmpty()) {
+            return;
+        }
+        List<String> stillRunning = new ArrayList<>(runningTasks);
+        sort(stillRunning);
+        logger.warn("There are still tasks running after this test that might break subsequent tests {}.", stillRunning);
```
Comment (imotov) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I am not sure that it warrants "WARN" logging level. It's perfectly fine for some of the tasks to be running in a working cluster. This includes node and master fault detection pings for example. I feel that INFO level logging would be more appropriate here.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java [hunk 4]
```diff
@@ -47,15 +48,31 @@ public ListTasksRequest detailed(boolean detailed) {
...
+     * Should this request wait for all found tasks to complete?
+     */
+    public boolean shouldWaitForCompletion() {
+        return waitForCompletion;
+    }
+
+    /**
+     * Should this request wait for all found tasks to complete?
+     */
+    public void setWaitForCompletion(boolean waitForCompletion) {
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: This is a Request and setters in requests don't typically have "set" prefix and return the request itself. I don't like this notation, but this is the notation that is used in most of the existing requests including this one. Check detailed setting above.

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: Somehow we need to distinguish "background" tasks for the cluster from those started by rest actions.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 3 above)
Comment (rjernst) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Somehow we need to distinguish "background" tasks for the cluster from those started by rest actions.

File: core/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/TestTaskPlugin.java [hunk 5]
```diff
@@ -345,7 +345,10 @@ public UnblockTestTaskResponse readFrom(StreamInput in) throws IOException {
 
 
     public static class UnblockTestTasksRequest extends BaseTasksRequest<UnblockTestTasksRequest> {
-
+        @Override
+        public boolean match(Task task) {
+            return task instanceof TestTask;
```
Comment (imotov) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/TestTaskPlugin.java]: You probably meant `return task instanceof TestTask && super.match(task)`.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java [hunk 6]
```diff
@@ -63,6 +71,33 @@ protected TaskInfo taskOperation(ListTasksRequest request, Task task) {
...
+        if (false == request.shouldWaitForCompletion()) {
+            super.processTasks(request, operation);
+            return;
+        }
+        // If we should wait for completion then we have to intercept every found task and wait for it to leave the manager.
+        TimeValue timeout = request.timeout();
+        if (timeout == null) {
+            timeout = DEFAULT_WAIT_FOR_COMPLETION_TIMEOUT;
+        }
+        long timeoutTime = System.nanoTime() + request.timeout().nanos();
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java]: Did you mean `long timeoutTime = System.nanoTime() + timeout.nanos();`?

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java [hunk 7]
```diff
@@ -63,6 +71,33 @@ protected TaskInfo taskOperation(ListTasksRequest request, Task task) {
...
+        super.processTasks(request, operation.andThen((Task t) -> {
+            while (System.nanoTime() < timeoutTime) {
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java]: Documentation for nanoTime() is suggesting to use `System.nanoTime() - timeoutTime < 0` instead to avoid numerical overflow.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 3 above)
Comment (imotov) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: While I agree that we want to know who initiated a particular task I don't think that having a leaked background tasks is much better than to have a leaked REST task :) Maybe we should simply keep the WARN level but only log tasks that are running for more than 5 seconds?

**Comment by imotov** [comment]
Left some comments.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 3 above)
Comment (rjernst) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I'm confused because I thought you were implying there are cluster level tasks always running in the background, that are simply part of the cluster operating normally. A leak is a leak, and we should catch and reject it.

Comment (imotov) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Background tasks run in background periodically, but they shouldn't run for very long time. I guess what I am trying to say is if for some reason a fault detection ping or a stats operation started by a ClusterInfoService runs for 5 minutes it's probably also a leaks, even though it doesn't have corresponding REST request that started it.

Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I think waiting for 5 seconds is somewhat likely to hide an issue?

If we can be sure that a task is really a leak we should fail the test. If we can't we can't then we should log it. And maybe we should think about how we *can* be sure.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java (hunk 4 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: I've been asked in the past to make getters and setters for new stuff on requests. Particularly when doing reindex. I really don't care either way. I used `shouldWaitForCompletion` rather than `getWaitForCompletion` because  I thought that was more readable but I can make it whatever you think is more right.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java (hunk 6 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java]: Indeed I did. Fixing.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java (hunk 7 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java]: Makes sense to me. I'll do that.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java (hunk 4 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: I am fine with the new way, but then let's fix all other setters and getters to match this one.

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: Sure. That'll be safe to backport because we haven't released this feature yet anyway.

File: core/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/TestTaskPlugin.java (hunk 5 above)
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/TestTaskPlugin.java]: Sure.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java (hunk 4 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: Should I do more than just the one class, do you think?

Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: I think everything inherited from BaseTasksRequest should be converted.

**Comment by nik9000** [comment]
@imotov have some more updates

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java [hunk 8]
```diff
@@ -31,31 +31,48 @@
...
-    public boolean detailed() {
+    public boolean getDetailed() {
         return this.detailed;
     }
 
     /**
      * Should the detailed task information be returned.
      */
-    public ListTasksRequest detailed(boolean detailed) {
+    public ListTasksRequest setDetailed(boolean detailed) {
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: Why not go all the way to `public void setDetailed(boolean detailed) {` like you did for `setWaitForCompletion`?

**Comment by imotov** [comment]
Left a small comment about setters signature. Otherwise LGTM.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java (hunk 8 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/ListTasksRequest.java]: Ah! Another point that I didn't think about when I made the setters. I think we're still going with returning `this` for the setters in requests. I'll just make the new one return `this` so they line up. If we don't like it we can change later - at least these won't clash.

**Comment by nik9000** [comment]
Merged! Waiting on https://github.com/elastic/elasticsearch/pull/16959 to backport.

**Comment by nik9000** [comment]
Now that #16959 is in I am starting the backport of this. So far it has been entirely mechanical.

**Comment by nik9000** [comment]
Backported to 2.x with 5b6779ed54b2c628e1fbb4c18518d96b8f6cec4e
