### PR TITLE
Fix thread leak in Hunspell service tests

### LINKED ISSUE #9849: Scheduling threads can be leaked on exception
In #9843, HunspellServiceTests leak scheduler and timer thread pools.  In this test class, there are 2 tests which check excepetion cases.  When those 2 tests are @Ignored, there are no more thread leaks.

### PR DESCRIPTION
**Pull request by tlrx**
An unchecked exception might be thrown when instantiating the HunspellService, leading to thread leaks in tests.

Closes #9849

### CODE REVIEW

**Comment by tlrx** [comment]
@rjernst Simple fix but I think it's enough. Can you have a look please? :)

**Comment by rjernst** [comment]
I don't think we should be hiding failures in loading the dictionaries.  Exceptions should propagate.  Is the problem Guice can't deal with unchecked exceptions properly? I see the injected constructor throws IOException; if we wrap in that will guice do the right thing?

**Comment by tlrx** [comment]
The exception is not hidden but logged as an error. Guice is not really good at handling exception during provisioning (see Google Guice wiki page [here](https://github.com/google/guice/wiki/ThrowingProviders) ), that's why I think it's not a good idea to propagate the exception in this case... Wrapping the unchecked exception into an IOException won't change anything because Guice will re-wrap it into an unchecked ProvisionException later :)

File: src/main/java/org/elasticsearch/indices/analysis/HunspellService.java [hunk 1]
```diff
@@ -130,7 +131,13 @@ private void scanAndLoadDictionaries() throws IOException {
                     if (Files.isDirectory(file)) {
                         try (DirectoryStream<Path> inner = Files.newDirectoryStream(hunspellDir.resolve(file), "*.dic")) {
                             if (inner.iterator().hasNext()) { // just making sure it's indeed a dictionary dir
-                                dictionaries.getUnchecked(file.getFileName().toString());
+                                try {
+                                    dictionaries.getUnchecked(file.getFileName().toString());
+                                } catch (UncheckedExecutionException e) {
+                                    // The cache loader throws unchecked exception (see #loadDictionary()),
+                                    // here we simply report the exception and continue loading the dictionnaries
+                                    logger.error("exception while loading dictionnary {}", file.getFileName(), e);
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/indices/analysis/HunspellService.java]: typo: dictionnary -> dictionary

File: src/main/java/org/elasticsearch/indices/analysis/HunspellService.java [hunk 2]
```diff
@@ -130,7 +131,13 @@ private void scanAndLoadDictionaries() throws IOException {
                     if (Files.isDirectory(file)) {
                         try (DirectoryStream<Path> inner = Files.newDirectoryStream(hunspellDir.resolve(file), "*.dic")) {
                             if (inner.iterator().hasNext()) { // just making sure it's indeed a dictionary dir
-                                dictionaries.getUnchecked(file.getFileName().toString());
+                                try {
+                                    dictionaries.getUnchecked(file.getFileName().toString());
+                                } catch (UncheckedExecutionException e) {
+                                    // The cache loader throws unchecked exception (see #loadDictionary()),
+                                    // here we simply report the exception and continue loading the dictionnaries
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/indices/analysis/HunspellService.java]: typo: dictionnaries -> dictionaries

**Comment by rjernst** [comment]
LGTM. 2 minor spelling issues in the comments
