### PR TITLE
Fix RareClusterStateIT Cancelling Publication too Early

### LINKED ISSUE #51308: [CI] failure in RareClusterStateIT.testDelayedMappingPropagationOnReplica
I've seen the issues in the past about similar failures [here](https://github.com/elastic/elasticsearch/issues/36813) and I am not sure the current one is actually valid, but I opened this issue for further investigation from someone more accustomed to the code. Doesn't repro locally. CC @original-brownbear 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/14/console
[7.5.3] https://gradle-enterprise.elastic.co/s/cjz5do6vk2pkq 
[6.8.7] https://gradle-enterprise.elastic.co/s/kgeuak6okd3ew
https://gradle-enterprise.elastic.co/s/decph63z42af6

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([DDE5C7E2534A19E2:A19B062D03AD2201]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.elasticsearch.cluster.coordination.RareClusterStateIT.testDelayedMappingPropagationOnReplica(RareClusterStateIT.java:371)
```

```
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.cluster.coordination.RareClusterStateIT.testDelayedMappingPropagationOnReplica" \
  -Dtests.seed=DDE5C7E2534A19E2 \
  -Dtests.security.manager=true \
  -Dtests.locale=zh-Hans-CN \
  -Dtests.timezone=America/Kentucky/Louisville \
  -Dcompiler.java=13 \
  -Druntime.java=13
```

### PR DESCRIPTION
**Pull request by original-brownbear**
Wait for the cluster to have settled down and have the same accepted version on all nodes before
executing and cancelling request so that a slow CS accept on one node doesn't make it fall behind
and then get sent the full CS because of the diff-version mismatch, breaking the mechanics of this test.

i.e. avoiding this situation:

```
[2020-01-23T11:26:39,636][DEBUG][o.e.c.c.PublicationTransportHandler] [node_t1] resending full cluster state to node {node_t0}{EepGi72fSguZAbAbXr4DPg}{hzfbHTkWTHqL2eX1Ig-_wA}{127.0.0.1}{127.0.0.1:35891}{dim} reason org.elasticsearch.transport.RemoteTransportException: [node_t0][127.0.0.1:35891][internal:cluster/coordination/publish_state]; org.elasticsearch.cluster.IncompatibleClusterStateVersionException: Expected diff for version 7 with uuid DkERyyF6QM28qJjg6gMSUA got version 9 and uuid 1IYFeZdnRIGqItz6VcFRXg
[2020-01-23T11:26:39,637][DEBUG][o.e.c.c.PublicationTransportHandler] [node_t0] received full cluster state version [9] with size [670]
[2020-01-23T11:26:39,652][DEBUG][o.e.g.PersistedClusterStateService] [node_t1] writing cluster state took [0ms]; wrote global metadata [false] and metadata for [1] indices and skipped [0] unchanged indices
[2020-01-23T11:26:39,652][DEBUG][o.e.g.PersistedClusterStateService] [node_t0] writing cluster state took [0ms]; wrote global metadata [false] and metadata for [1] indices and skipped [0] unchanged indices
[2020-01-23T11:26:39,652][DEBUG][o.e.c.c.CoordinationState] [node_t0] handleCommit: ignored commit request due to version mismatch (term 1, expected: [9], actual: [8])
[2020-01-23T11:26:39,653][DEBUG][o.e.c.c.C.CoordinatorPublication] [node_t1] ApplyCommitResponseHandler: [{node_t0}{EepGi72fSguZAbAbXr4DPg}{hzfbHTkWTHqL2eX1Ig-_wA}{127.0.0.1}{127.0.0.1:35891}{dim}] failed
org.elasticsearch.transport.RemoteTransportException: [node_t0][127.0.0.1:35891][internal:cluster/coordination/commit_state]
```

Closes #51308

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/coordination/RareClusterStateIT.java [hunk 1]
```diff
@@ -370,11 +376,9 @@ public void testDelayedMappingPropagationOnReplica() throws Exception {
 
         // Now make sure the indexing request finishes successfully
         disruption.stopDisrupting();
-        assertBusy(() -> {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/cluster/coordination/RareClusterStateIT.java]: These busy assert made no sense, we're never resending the requests we're asserting on here, all these do is make a failed test run take an extra `10s`.

**Review by ywelsch — APPROVED** [review]
LGTM. Thanks!

**Comment by original-brownbear** [comment]
Thanks Yannick!

**Comment by rjernst** [comment]
I've backported this to 7.6 as well, to address the same failure there (https://gradle-enterprise.elastic.co/s/j7bvgrn7srrie).
