### PR TITLE
Fix cancellation race condition in `onIndexAvailableForSearch` 

### LINKED ISSUE #113336: [CI] SecurityIndexManagerIntegTests testOnIndexAvailableForSearchIndexAlreadyAvailable failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4111 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/u4kbs7u5gd3ou)
- [elasticsearch-pull-request #32308 / part-4](https://gradle-enterprise.elastic.co/s/5mphls37y73rm)
- [elasticsearch-pull-request #32307 / part-4](https://gradle-enterprise.elastic.co/s/zpe26qi5ztbky)
- [elasticsearch-pull-request #31885 / part-4](https://gradle-enterprise.elastic.co/s/ltixtj3pe7nne)
- [elasticsearch-pull-request #31260 / part-4-fips](https://gradle-enterprise.elastic.co/s/uxalgnch44tys)
- [elasticsearch-pull-request #31231 / part-4-fips](https://gradle-enterprise.elastic.co/s/gjyfh2pkpecqk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.support.SecurityIndexManagerIntegTests.testOnIndexAvailableForSearchIndexAlreadyAvailable" -Dtests.seed=19DE7F0872A25AB9 -Dtests.locale=tk-TM -Dtests.timezone=Atlantic/Madeira -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testOnIndexAvailableForSearchIndexAlreadyAvailable'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.security.support.SecurityIndexManagerIntegTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchTimeoutException: timed out waiting for security index [.security-7] to become available for search
```

**Issue Reasons:**
- [main] 6 failures in test testOnIndexAvailableForSearchIndexAlreadyAvailable (0.8% fail rate in 760 executions)
- [main] 3 failures in step part-4 (1.0% fail rate in 288 executions)
- [main] 2 failures in step part-4-fips (20.0% fail rate in 10 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (1.8% fail rate in 284 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by n1v0lg**
This PR fixes following race conditions in `onIndexAvailableForSearch` introduced in https://github.com/elastic/elasticsearch/pull/112813:

1. If the method is called when the index is already available, cancellation is still scheduled and may execute before successful completion (manifested in test failures https://github.com/elastic/elasticsearch/issues/113336)
2. If the cancel task runs _before_ `addStateListener`, it may fail to remove the listener (noticed while fixing the first issue)

These race conditions only manifest for small timeout windows, and are completely bypassed for 0 timeout windows based on other checks in prod code, so the practical impact is fortunately limited.

Resolves: https://github.com/elastic/elasticsearch/issues/113336

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java [hunk 1]
```diff
@@ -364,45 +365,74 @@ public void accept(State previousState, State nextState) {
      * Notifies {@code listener} once the security index is available, or calls {@code onFailure} on {@code timeout}.
      */
     public void onIndexAvailableForSearch(ActionListener<Void> listener, TimeValue timeout) {
-        logger.info("Will wait for security index [{}] to become available for search", getConcreteIndexName());
+        logger.info("Will wait for security index [{}] for [{}] to become available for search", getConcreteIndexName(), timeout);
 
-        final ActionListener<Void> notifyOnceListener = ActionListener.notifyOnce(listener);
+        if (state.indexAvailableForSearch) {
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java:370]: Pulling the early return up since it's cleaner to avoid all below work to begin with if the index is already available anyhow. This also fixes the first race condition from the PR description.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java [hunk 2]
```diff
@@ -364,45 +365,74 @@ public void accept(State previousState, State nextState) {
...
+            logger.debug("Security index [{}] is already available", getConcreteIndexName());
+            listener.onResponse(null);
+            return;
+        }
 
+        final AtomicBoolean isDone = new AtomicBoolean(false);
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java:376]: Previously I was using a notify-once listener; this did the job of ensuring we only call onResponse or onFailure once but using an atomic boolean more cleanly avoids unnecessary calls to e.g., `removeStateListener`, and is therefore more performant

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java [hunk 3]
```diff
@@ -364,45 +365,74 @@ public void accept(State previousState, State nextState) {
...
-            removeStateListener(indexAvailableForSearchListener);
-            notifyOnceListener.onFailure(
-                new ElasticsearchTimeoutException(
-                    "timed out waiting for security index [" + getConcreteIndexName() + "] to become available for search"
-                )
-            );
-        }, timeout, client.threadPool().generic());
+        // add listener _before_ registering timeout -- this way we are guaranteed it gets removed (either by timeout below, or successful
+        // completion above)
+        addStateListener(indexAvailableForSearchListener);
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java:391]: This is the first bit to fixing the second race condition from the PR description (cancel being called _before_ addStateListener and the consumer thus sticking around).

Instead we first add the listener, thus guaranteeing removal.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java [hunk 4]
```diff
@@ -364,45 +365,74 @@ public void accept(State previousState, State nextState) {
...
+                    new ElasticsearchTimeoutException(
+                        "timed out waiting for security index [" + getConcreteIndexName() + "] to become available for search"
+                    )
+                );
+            }
+        }, timeout, client.threadPool().generic()));
     }
 
+    /**
+     * This class ensures that if cancel() is called _before_ setCancellable(), the passed-in cancellable is still correctly cancelled on
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java:407]: This is the second part of the fix mentioned here: https://github.com/elastic/elasticsearch/pull/113386/files#r1771485529

We need to ensure that if the state listener completes before the Cancellable is registered, the timeout task this gets cancelled correctly.

**Comment by n1v0lg** [comment]
Failures unrelated

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
my notes for posterity (no need to review, but if you do and see issues please comment): 

Before
---
1\) create the BiConsumer we will pass to org.elasticsearch.xpack.security.support.SecurityIndexManager#addStateListener

2\) schedule the cancel action which will call org.elasticsearch.xpack.security.support.SecurityIndexManager#removeStateListener and fail the request after the configured time

3a) (index is already available) explicity call cancel on the scheduled work which will call org.elasticsearch.xpack.security.support.SecurityIndexManager#removeStateListener and error the request 

3b)  (index is NOT available) go ahead and pass the BiConsumer to org.elasticsearch.xpack.security.support.SecurityIndexManager#addStateListener

The first problem is with 3a) when the index is already available and the scheduled cancel (likely with a time/delay of 0ms) can be invoked before the explict cancel, resulting a failure instead of a sucess of the request. Technically the main listener is completed twice (the first time a failure, the second time a success) but only the first completion time matters. 

The second problem is with 3b) when the index is not available and the scheduled cancel (likely with a time/delay of 0ms)  can be invoked before BiConsumer is passed to addStateListener. So we remove the BiConsumer before we ever add it and will immediatly fail the request before we ever call addStateListener. I think this one is less bad since it will get added and eventually removed and would likely only happen for time/delay of 0ms which is effectivly disabling the wait for availble functionaly anyway. 


After
---
1\) short circuit to return immediatly if index is available 

2\) create isDone=false atomic boolean

3\) create the BiConsumer we will pass to org.elasticsearch.xpack.security.support.SecurityIndexManager#addStateListener

4\) call org.elasticsearch.xpack.security.support.SecurityIndexManager#addStateListener with the BiConsumer just created. So, BiConsumer is always added and will only be removed by either cancel or the state change. 

5\) schedule the cancel action which will call org.elasticsearch.xpack.security.support.SecurityIndexManager#removeStateListener and fail the request after the configured time, BUT only do the work if not already done, so the BiConsumer will never be removed twice and primary listener will never be completed twice. This also prevents a new race condition between the cancel and state change. This also helps to protect a race condition between the scheduled cancel (likely with a time/delay of 0ms) and an explicit cancel via the state change.

**Review by jakelandis — APPROVED** [review]
LGTM - nice work figuring this out. 

Two meta comments:
1) this is all very complex and quite easy to get wrong. I would be open to ideas on how to simplify overall. 
2) The testing here is sufficient, but generally tests with timeouts, busy waits, and thread sleeps, even with generous values that allow for slow CI machines tend to be flakey. Ideally, any concurrent testing is based on locks,gates and time providers that are tightly controlled instead of wall clock values. I don't think the existing structure here lends itself well to testing that manner, which is a bit of code smell. Not a code smell in this PR or any code you wrote here previously, but more generally - see my first point.
