### PR TITLE
[ML] Handle failed datafeed in MlDistributedFailureIT

### LINKED ISSUE #52608: [CI] MlDistributedFailureIT.testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed failed with NPE
This one didn't reproduce locally for me but NPEs in tests seem suspect. This is the first instance of such a failure and it happened in a `7.6` build.

```
java.lang.NullPointerException: (No message provided)Close stacktrace
at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed(MlDistributedFailureIT.java:248)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

### PR DESCRIPTION
**Pull request by davidkyle**
Rarely the datafeed under test may detect the job has failed and terminate itself. The job failure is an expected part of the test but the test does not account for the datafeed stopping and having no persistent task. If the datafeed has stopped then don't set its state to stopping

Details of how this happens are in  https://github.com/elastic/elasticsearch/issues/52608#issuecomment-589579989

Closes #52608

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlDistributedFailureIT.java [hunk 1]
```diff
@@ -245,19 +245,24 @@ public void testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed() thro
...
-        // Confirm the datafeed state is now stopping - this may take a while to update in cluster state
-        assertBusy(() -> {
-            GetDatafeedsStatsAction.Request datafeedStatsRequest = new GetDatafeedsStatsAction.Request(datafeedId);
-            GetDatafeedsStatsAction.Response datafeedStatsResponse =
-                client().execute(GetDatafeedsStatsAction.INSTANCE, datafeedStatsRequest).actionGet();
-            assertEquals(DatafeedState.STOPPING, datafeedStatsResponse.getResponse().results().get(0).getDatafeedState());
-        });
+        // It is possible that the datafeed has already detected the job failure and
+        // terminated itself. In this happens there is no task
+        if (task != null) {
```
Comment (droberts195) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlDistributedFailureIT.java]: The problem with this is that if `task == null` then the test isn't doing what it's supposed to be doing, which is testing that you can stop an unassigned `stopping` datafeed.

Since this happens so rarely we could put the whole test in a loop and retry a few times if this situation occurs.

But if you don't want to do that then it would be better to use `assumeFalse("Test setup did not create the required conditions", task == null);` because then at least the test will be reported as having been skipped rather than silently succeeding when it didn't test what it was supposed to test.

Comment (davidkyle) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlDistributedFailureIT.java]: I think assumeFalse is best, retry adds complexity to an already complicated piece of code. The test could fail for any number of reasons some including general infrastructure problems retrying would add noise. 

Looking at the test, in the setup it waits for the datafeed to complete before closing the job which should have prevented flush happening after the job failed.

https://github.com/elastic/elasticsearch/blob/071b60db2941e54c19446403d4fcd49d9d3a4f9f/x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlDistributedFailureIT.java#L215

`waitForDatafeed` waits for the data counts to be indexed which the datafeed does asynchronously before flushing the job. It is amazing that the race between the writing the datacounts and calling flush is sometimes lost to a thread doing an `assertBusy` searching the index for the new datacounts and then failing the job but that is whats happening here. This is so unlikely (the first time its been reported) it's not worth rewriting the test.

**Review by droberts195 — APPROVED** [review]
LGTM
