### PR TITLE
Fix FieldStats deserialization of `ip` field

### LINKED ISSUE #20516: _field_stats returns server error when index contains an IP field
**Elasticsearch version**: 5.0-beta1, master

**Plugins installed**: none

**JVM version**: java version "1.8.0_60"

**OS version**: OSX El Capitan

**Description of the problem including expected versus actual behavior**:

_field_stats returns an INTERNAL_SERVER_ERROR when the request includes an IP field.

**Steps to reproduce**:
 1 Create an index with an IP field mapping:

```
PUT /ip
{
	"mappings": {
		"ip": {
			"properties": {
				"ip": {
					"type": "ip"
				}
			}
		}
	}
}
```

 2 Add a simple source document
```
POST /ip/ip

{
	"ip": "192.168.1.1"
}
```
 
3 Issue a _field_stats request for that field and see the error
```
GET /ip/_field_stats?fields=ip

Response:
{
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 1,
        "index": "ip",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "exception",
          "reason": "java.lang.IllegalArgumentException: encoded bytes are of incorrect length",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "encoded bytes are of incorrect length",
            "caused_by": {
              "type": "unknown_host_exception",
              "reason": "addr is of illegal length"
            }
          }
        }
      }
    ]
  },
  "indices": {
    "_all": {
      "fields": {}
    }
  }
}
```

**Provide logs (if relevant)**:

```
DEBUG - ip - action_fieldstats - [1], node[SrkoA9nWQzeJaFbEamzoqQ], [P], s[STARTED], a[id=Vn9wP1hhSx2M1NUmAombsg]: failed to execute [org.elasticsearch.action.fieldstats.FieldStatsRequest@7d8ef303]
INFO - ? - ? - org.elasticsearch.transport.RemoteTransportException: [SrkoA9n][127.0.0.1:9300][indices:data/read/field_stats[s]]
INFO - ? - ? - Caused by: org.elasticsearch.ElasticsearchException: java.lang.IllegalArgumentException: encoded bytes are of incorrect length
INFO - ? - ? - at org.elasticsearch.ExceptionsHelper.convertToElastic(ExceptionsHelper.java:55) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.TransportFieldStatsAction.shardOperation(TransportFieldStatsAction.java:204) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.TransportFieldStatsAction.shardOperation(TransportFieldStatsAction.java:57) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:300) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:296) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:534) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_60]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_60]
INFO - ? - ? - at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
INFO - ? - ? - Caused by: java.lang.IllegalArgumentException: encoded bytes are of incorrect length
INFO - ? - ? - at org.apache.lucene.document.InetAddressPoint.decode(InetAddressPoint.java:187) ~[lucene-sandbox-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.FieldStats.readFrom(FieldStats.java:609) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:682) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.indices.IndicesService.getFieldStats(IndicesService.java:1143) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.TransportFieldStatsAction.shardOperation(TransportFieldStatsAction.java:198) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.TransportFieldStatsAction.shardOperation(TransportFieldStatsAction.java:57) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:300) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:296) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
INFO - ? - ? - at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_60]
INFO - ? - ? - Caused by: java.net.UnknownHostException: addr is of illegal length
INFO - ? - ? - at java.net.InetAddress.getByAddress(InetAddress.java:1042) ~[?:1.8.0_60]
INFO - ? - ? - at java.net.InetAddress.getByAddress(InetAddress.java:1439) ~[?:1.8.0_60]
INFO - ? - ? - at org.apache.lucene.document.InetAddressPoint.decode(InetAddressPoint.java:184) ~[lucene-sandbox-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.FieldStats.readFrom(FieldStats.java:609) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:682) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.indices.IndicesService.getFieldStats(IndicesService.java:1143) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.TransportFieldStatsAction.shardOperation(TransportFieldStatsAction.java:198) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.fieldstats.TransportFieldStatsAction.shardOperation(TransportFieldStatsAction.java:57) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:300) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:296) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
INFO - ? - ? - at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_60]
```

### PR DESCRIPTION
**Pull request by jimczi**
Add missing readBytes in `ip` field deserialization
Add (de)serialization tests for all types
This change also removes the ability to set FieldStats.minValue or FieldStats.maxValue to null, this is not required anymore since the stats are built on fields with values only.

Fixes #20516

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/fieldstats/FieldStatsTests.java [hunk 1]
```diff
@@ -513,4 +521,55 @@ public void testMetaFieldsNotIndexed() {
...
+                throw new IllegalArgumentException("Invalid type");
+        }
+    }
+
+    private void assertSerialization(FieldStats stats) throws IOException {
+        BytesStreamOutput output = new BytesStreamOutput();
+        stats.writeTo(output);
+        output.flush();
+        BytesRef serialized = output.bytes().toBytesRef();
+        ByteArrayInputStream is = new ByteArrayInputStream(serialized.bytes, serialized.offset, serialized.length);
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/fieldstats/FieldStatsTests.java]: I think it is good enough to call `output.bytes().steamInput()`.

File: core/src/test/java/org/elasticsearch/fieldstats/FieldStatsTests.java [hunk 2]
```diff
@@ -513,4 +521,55 @@ public void testMetaFieldsNotIndexed() {
...
+        InputStreamStreamInput input = new InputStreamStreamInput(is);
+        FieldStats clone = FieldStats.readFrom(input);
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/fieldstats/FieldStatsTests.java]: Can you use a word other than `clone`? It makes me think of the `clone` method which this isn't. I tend to use `roundTripped` or something.

**Review by nik9000 — APPROVED** [review]
I left a few minor things but it looks right to me!

**Comment by jimferenczi** [comment]
Thanks @nik9000 !
