### PR TITLE
RestAPI: Reject forcemerge requests with a body

### LINKED ISSUE #29584: _forcemerge API erroneously accepts JSON payloads and returns ambiguously positive response
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.3

**Plugins installed**: [X-Pack 6.2.3]

**JVM version** (`java -version`): OpenJDK Runtime Environment (build 1.8.0_161-b14)

**OS version** (`uname -a` if on a Unix-like system): Linux 44e7bb4d9f24 4.9.87-linuxkit-aufs #1 SMP Fri Mar 16 18:16:33 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux _(Official Docker image running on MacOS 10.13.4)_

**Description of the problem including expected versus actual behavior**: When attempting to execute a force merge operation passing the accepted parameters as a JSON payload, a response is returned to the user which ambiguously suggests the requested operation was successful. However, inspection of `<index_name>/_segments` shows no merge having taken place.

By contrast, when passing the parameter as a URL parameter, the merge takes place as expected.

**Steps to reproduce**:

 1. Trigger a force merge with a JSON payload of the desired parameters
```
POST <index_name>/_forcemerge
{
   "max_num_segments": 1
}
```

 2. Receive positive looking response

```
{
  "_shards": {
    "total": 102,
    "successful": 102,
    "failed": 0
  }
}
```
 3. Check the status

```
GET <index_name>/_segments
```

alternatively view Segment Count in X-Pack Monitoring

In order to actually trigger the merge, do the following:

```
POST <index_name>/_forcemerge?max_num_segments=1
```

Then verify with 

```
GET <index_name>/_segments
```

### PR DESCRIPTION
**Pull request by rjernst**
This commit adds validation to forcemerge rest requests which contain a
body. All parameters to force merge must be part of http params.

closes #29584

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/rest/action/admin/indices/RestForceMergeAction.java [hunk 1]
```diff
@@ -47,6 +47,9 @@ public String getName() {
 
     @Override
     public RestChannelConsumer prepareRequest(final RestRequest request, final NodeClient client) throws IOException {
+        if (request.hasContent()) {
+            throw new IllegalArgumentException("forcemerge takes arguments in http params, not as http body");
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/rest/action/admin/indices/RestForceMergeAction.java]: These are "query parameters" (there are many different kinds of "parameters" in the HTTP specification, not only query parameters). I think we should say "request body" instead of "http body" (and let us capitalize "HTTP" if we keep it in the message.

**Review by jasontedor — APPROVED** [review]
I left some comments about the exception message. The overall change and test look good but I think we can work the message a little bit?
