### PR TITLE
Ensure remote cluster is connected before fetching `_field_caps`

### LINKED ISSUE #24763: _field_caps API doesn't trigger reconnect to remove cluster
When a remote cluster goes away, and a request to the `_field_caps` API attempts to reach that remote cluster, elasticsearch will not reconnect to the remote cluster even after it has come back online. In order to re-establish a connection a `_search` request to that cluster must be made, which triggers a reconnect and re-enables the `_field_caps` API.

perhaps related (though I'm happy to file as a separate issue) the failure states of the two API's are pretty dramatically different:

`_search` API failure state:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "connect_transport_exception",
        "reason": "[][127.0.0.1:9301] connect_timeout[30s]"
      }
    ],
    "type": "transport_exception",
    "reason": "unable to communicate with remote cluster [cluster2]",
    "caused_by": {
      "type": "connect_transport_exception",
      "reason": "[][127.0.0.1:9301] connect_timeout[30s]",
      "caused_by": {
        "type": "annotated_connect_exception",
        "reason": "Connection refused: /127.0.0.1:9301",
        "caused_by": {
          "type": "connect_exception",
          "reason": "Connection refused"
        }
      }
    }
  },
  "status": 500
}
```

`_field_caps` API failure state:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "No node available for cluster: cluster2 nodes: []"
      }
    ],
    "type": "illegal_state_exception",
    "reason": "No node available for cluster: cluster2 nodes: []"
  },
  "status": 500
}
```

### PR DESCRIPTION
**Pull request by s1monw**
If a cluster disconnects and comes back up we should ensure that
we connected to the cluster before we fire the requests.

Closes #24763

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/transport/RemoteClusterConnectionTests.java [hunk 1]
```diff
@@ -730,4 +731,58 @@ public void onFailure(Exception e) {
         }
         return statsRef.get();
     }
+
+    public void testEnsureConnected() throws IOException, InterruptedException {
+        List<DiscoveryNode> knownNodes = new CopyOnWriteArrayList<>();
+        try (MockTransportService seedTransport = startTransport("seed_node", knownNodes, Version.CURRENT);
+             MockTransportService discoverableTransport = startTransport("discoverable_node", knownNodes, Version.CURRENT)) {
+            DiscoveryNode seedNode = seedTransport.getLocalDiscoNode();
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/transport/RemoteClusterConnectionTests.java]: can you fix the indentation here?

**Review by javanna — APPROVED** [review]
LGTM thanks @s1monw
