### PR TITLE
Remove .geohash suffix from GeoDistanceQuery and GeoDistanceRangeQuery

### LINKED ISSUE #15179: Geohash query not working after migrating to Elasticsearch 2.0/2.1
I am having trouble with my query after migrating to Elasticsearch 2.0/2.1. Previously used version 1.4. I am trying to do a GeoDistance query using geohash. That's the excerpt from ES response:

    "root_cause": [
      {
        "type": "query_parsing_exception",
        "reason": "failed to find geo_point field [geohash]",
        "index": "campaigns",
        "line": 1,
        "col": 234
      }
    ]

The minimal index usable to reproduce this problem is as follows:

    curl -s -X PUT "http://localhost:9200/campaigns" -d'{
        "settings": {
                "analysis": {
                    "filter": {
                        "name_ngram": {
                            "type": "nGram",
                            "min_gram": "2",
                            "max_gram": "50"
                        }
                    },
                    "analyzer": {
                        "search_analyzer": {
                            "filter": [
                                "standard",
                                "asciifolding",
                                "lowercase",
                                "trim"
                            ],
                            "tokenizer": "standard"
                        },
                        "name_analyzer": {
                            "filter": [
                                "name_ngram",
                                "standard",
                                "asciifolding",
                                "lowercase",
                                "trim"
                            ],
                            "tokenizer": "standard"
                        }
                    }                                                                                                                                                                                                                                                                
                }                                                                                                                                                                                                                                                                    
        },                                                                                                                                                                                                                                                                           
        "mappings": {                                                                                                                                                                                                                                                                
            "campaign": {                                                                                                                                                                                                                                                            
                "properties": {                                                                                                                                                                                                                                                      
                    "locations": {                                                                                                                                                                                                                                                   
                        "properties": {                                                                                                                                                                                                                                              
                            "id": {                                                                                                                                                                                                                                                  
                                "include_in_all": false,                                                                                                                                                                                                                             
                                "type": "integer"                                                                                                                                                                                                                                    
                            },                                                                                                                                                                                                                                                       
                            "geohash": {                                                                                                                                                                                                                                             
                                "type": "geo_point"                                                                                                                                                                                                                                  
                            }                                                                                                                                                                                                                                                        
                        },                                                                                                                                                                                                                                                           
                        "type": "nested"                                                                                                                                                                                                                                             
                    },                                                                                                                                                                                                                                                               
                    "id": {                                                                                                                                                                                                                                                          
                        "type": "integer"                                                                                                                                                                                                                                            
                    }                                                                                                                                                                                                                                                                
                },                                                                                                                                                                                                                                                                   
                "_all": {                                                                                                                                                                                                                                                            
                    "search_analyzer": "search_analyzer",                                                                                                                                                                                                                            
                    "analyzer": "name_analyzer"                                                                                                                                                                                                                                      
                }                                                                                                                                                                                                                                                                    
            }                                                                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                            
    }'
I am using two analyzers here (as this is what I am using in my project, tried also with one analyzer and the result is the same).

The minimal data indexed in ES is as follows:

    curl -s -X POST "http://localhost:9200/campaigns/campaign" -d'{
        "id": 12,
        "locations": [
            {
                "id": 13,
                "geohash": {
                    "geohash": "s7ws01wyd7ws"
                }
            }
        ]
    }'

The mapping in ES:

    curl -s -X GET "http://localhost:9200/campaigns/_mapping?pretty"
    {
      "campaigns" : {
        "mappings" : {
          "campaign" : {
            "_all" : {
              "analyzer" : "name_analyzer",
              "search_analyzer" : "search_analyzer"
            },
            "properties" : {
              "id" : {
                "type" : "integer"
              },
              "locations" : {
                "type" : "nested",
                "properties" : {
                  "geohash" : {
                    "type" : "geo_point"
                  },
                  "id" : {
                    "type" : "integer",
                    "include_in_all" : false
                  }
                }
              }
            }
          }
        }
      }
    }

Working query to search by "locations.id":

    curl -s -X POST "http://localhost:9200/campaigns/_search" -d@'{
      "query": {
        "filtered": {
          "filter": {
            "nested": {
              "path": "locations",
              "filter": {
                "term": {
                  "locations.id": "13"
                }
              }
            }
          }
        }
      }
    }' | jq ''
    {
      "took": 5,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
          {
            "_index": "campaigns",
            "_type": "campaign",
            "_id": "AVFYQn4uic5h_a2BXp1k",
            "_score": 1,
            "_source": {
              "id": 12,
              "locations": [
                {
                  "id": 13,
                  "geohash": {
                    "geohash": "s7ws01wyd7ws"
                  }
                }
              ]
            }
          }
        ]
      }
    }

Not working query to search by "geohash" (only when the data is posted from file, but the same response is returned in my application):

    cat query_geohash.json 
    {
      "query": {
        "filtered": {
          "filter": {
            "nested": {
              "path": "locations",
              "filter": {
                "geo_distance": {
                  "distance": "100.0km",
                  "geohash": "s7ws01wyd7ws"
                }
              }
            }
          }
        }
      }
    }
    curl -s -X POST "http://localhost:9200/campaigns/_search" -d@query_geohash.json | jq ''
    {
      "error": {
        "root_cause": [
          {
            "type": "query_parsing_exception",
            "reason": "failed to find geo_point field [geohash]",
            "index": "campaigns",
            "line": 1,
            "col": 234
          }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
          {
            "shard": 0,
            "index": "campaigns",
            "node": "cqrNlEmRSPGcGewKuUvlnA",
            "reason": {
              "type": "query_parsing_exception",
              "reason": "failed to find geo_point field [geohash]",
              "index": "campaigns",
              "line": 1,
              "col": 234
            }
          }
        ]
      },
      "status": 400
    }

Strangely, the same query works OK when the query is not read from file, but posted "inline":

    curl -s -X POST "http://localhost:9200/campaigns/_search" -d@'{
      "query": {
        "filtered": {
          "filter": {
            "nested": {
              "path": "locations",
              "filter": {
                "geo_distance": {
                  "distance": "100.0km",
                  "geohash": "s7ws01wyd7ws"
                }
              }
            }
          }
        }
      }
    }' | jq ''
    {
      "took": 11,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
          {
            "_index": "campaigns",
            "_type": "campaign",
            "_id": "AVFYQn4uic5h_a2BXp1k",
            "_score": 1,
            "_source": {
              "id": 12,
              "locations": [
                {
                  "id": 13,
                  "geohash": {
                    "geohash": "s7ws01wyd7ws"
                  }
                }
              ]
            }
          }
        ]
      }
    }

What am I missing here? The geohash query itself looks OK (response is the same when I use "locations.geohash" instead of "geohash"). The only difference is the way the query is fed to curl. Also, both versions work correctly in ES 1.4.

I am not sure if this is a bug in Elasticsearch or if I made some mistake in my query. Anyway, I'll be really grateful for any help!

### PR DESCRIPTION
**Pull request by nknize**
Occasionally the .geohash suffix in Geo{Distance|DistanceRange}Query would conflict with a mapping that defines a sub-field by the same name. This occurs often with nested and multi-fields when a mapping defines a geo_point sub-field using the field name "geohash". Since the QueryParser already handles parsing geohash encoded geopoints, without requiring the ".geohash" suffix, the suffix parsing can be removed altogether.

This PR removes the .geohash suffix parsing, adds explicit test coverage for the nested query use-case, and adds random distance queries to the nested query test suite.

closes #15179

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/query/GeoDistanceQueryParser.java [hunk 1]
```diff
@@ -120,9 +120,6 @@ public GeoDistanceQueryBuilder fromXContent(QueryParseContext parseContext) thro
                 } else if (currentFieldName.endsWith(GeoPointFieldMapper.Names.LON_SUFFIX)) {
                     point.resetLon(parser.doubleValue());
                     fieldName = currentFieldName.substring(0, currentFieldName.length() - GeoPointFieldMapper.Names.LON_SUFFIX.length());
-                } else if (currentFieldName.endsWith(GeoPointFieldMapper.Names.GEOHASH_SUFFIX)) {
```
Comment (danielmitterdorfer) [inline core/src/main/java/org/elasticsearch/index/query/GeoDistanceQueryParser.java]: Shouldn't we be able to remove `GeoPointFieldMapper.Names.GEOHASH_SUFFIX` entirely from the code base?

File: core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java [hunk 2]
```diff
@@ -47,6 +48,8 @@ public static QueryBuilder createQuery(Random r) {
             case 3:
                 return createMultiTermQuery(r);
             case 4:
+                return new GeoDistanceRangeQueryTests().createTestQueryBuilder();
```
Comment (danielmitterdorfer) [inline core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java]: This is not related to your PR but to me it looks weird that we need to create an instance of a test class to get a query builder. I think we should change that to a cleaner API (but not in this PR).

File: core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java [hunk 3]
```diff
@@ -21,6 +21,7 @@
 
 import com.carrotsearch.randomizedtesting.generators.RandomInts;
 import com.carrotsearch.randomizedtesting.generators.RandomStrings;
+import org.apache.lucene.search.GeoPointDistanceQuery;
```
Comment (danielmitterdorfer) [inline core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java]: I can see no reference to `GeoPointDistanceQuery` in this file. Is this import needed?

**Comment by danielmitterdorfer** [comment]
@nknize: I left a few comments but apart from that LGTM. I'd just be interested how you think about the API issue in `RandomQueryBuilder`.

File: core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java (hunk 2 above)
Comment (nknize) [inline core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java]: There's no reason for it. It looks to me like `GeoDIstanceRangeQueryTests.createTestQueryBuilder` and all referenced methods can be static? They don't require any instance state.

Comment (nknize) [inline core/src/test/java/org/elasticsearch/index/query/RandomQueryBuilder.java]: Well, except the generic. But I think that can be fixed too? You're right, I think its worth exploring in a separate cleanup issue?
