### PR TITLE
Fixes ByteSizeValue to serialise correctly

### LINKED ISSUE #27568: Deprecate and remove parsing of fractional bytes values
We use ByteSizeValue to represent settings and API parameters that are byte values. This allows the user to specify the values in a human readable form and Elasticsearch to interpret it in the units most convenient to what it wants to do with the value (e.g. the user specifies the index buffer size as `"56MB"` but Elasticsearch converts this to 58720256 bytes and uses that value.

However, the current implementation has a few problems:
* The `toString()` method outputs fractional values (to 1 decimal place) preventing round trip parsing
* Parsing is sensitive to double rounding errors
* The parsing always converts the provided value to bytes so can overflow which results in the value being Long.MAX_VALUE bytes for large values (in PB range)
* The unit is not serialised so on deserialisation the value is the bytes value

We should instead prevent fractional values from being used and store the value in the original units.

@jasontedor and I spoke about this an propose the following approach:
* In 6.x 
    * Deprecate fractional parsing
    * Rename ByteSizeValue -> LegacyByteSizeValue
    * Add `@Deprecated` to LegacyByteSizeValue
    * Introduce ByteSizeValue with desired behavior:
        * Add a `getStringRep()` method which like TimeValue will output a String with the current value and unit
        * Throw an exception in the `parseByteSizeValue()` method if the input string contains a fractional value
        * Keep the original unit when parsing (e.g. 20MB is represented with units MB rather than converting it to bytes)
    * Use ByteSizeValue (the new one) in new APIs/settings
* In 7.0:
    * Auto-upgrade cluster and index settings from LegacyByteSizeValue to ByteSizeValue (the new one) and remove LegacyByteSizeValue. Fractional bytes values in elasticsearch.yml will need to be manually changed by the user when upgrading to 7.0 or can be changed before upgrading.

### PR DESCRIPTION
**Pull request by colings86**
This fix makes a few fixes to ByteSizeValue to make it possible to perform round-trip serialisation:
* Changes wire serialisation to use Zlong methods instead of VLong methods. This is needed because the value `-1` is accepted but previously if `-1` is supplied it cannot be serialised using the wire protocol.
* Limits the supplied size to be no more than Long.MAX_VALUE when converted to bytes. Previously values greater than Long.MAX_VALUE bytes were accepted but would be silently interpreted as Long.MAX_VALUE bytes rather than erroring so the user had no idea the value was not being used the way they had intended. I consider this a bug and so fine to include this bug fix in a minor version but I am open to other points of view.
* Adds a `getStringRep()` method that can be used when serialising the value to JSON. This will print the bytes value if the size is positive, `”0”` if the size is `0` and `”-1”` if the size is `-1`.
* Adds logic to detect fractional values when parsing from a String and emits a deprecation warning in this case.
* Modifies hashCode and equals methods to work with long values rather than doubles so they don’t run into precision problems when dealing with large values. Previous to this change the equals method would not detect small differences in the values (e.g. 1-1000 bytes ranges) if the actual values where very large (e.g. PBs). This was due to the values being in the order of 10^18 but doubles only maintaining a precision of ~10^15.

Closes #27568

### CODE REVIEW

**Comment by colings86** [comment]
jenkins please retest this

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java [hunk 1]
```diff
@@ -20,28 +20,40 @@
...
         unit = ByteSizeUnit.BYTES;
     }
 
     @Override
     public void writeTo(StreamOutput out) throws IOException {
-        out.writeVLong(getBytes());
+        if (out.getVersion().before(Version.V_6_2_0)) {
+            out.writeVLong(getBytes());
+        } else {
+            out.writeZLong(getBytes());
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: I think we can do better here? Write out the bytes and write out the unit and read them on de-serialization to preserve the unit?

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java [hunk 2]
```diff
@@ -105,26 +132,33 @@ public double getPbFrac() {
         return ((double) getBytes()) / ByteSizeUnit.C5;
     }
 
+    public String getStringRep() {
+        if (size <= 0) {
+            return String.valueOf(size);
+        }
+        return getBytes() + ByteSizeUnit.BYTES.getSuffix();
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: Why not `size` and `unit`?

**Review by jasontedor — CHANGES_REQUESTED** [review]
I left a few comments.

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java (hunk 1 above)
Comment (colings86) [reply core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: Agreed

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java (hunk 2 above)
Comment (colings86) [reply core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: We can do this but to maintain backward compatibility I think we need to keep the parse method converting the unit to bytes for 6.x and can only make it keep the unit in a followup PR for only the master branch. It also means that we can't compare the string representations in `BizeSizeValueTests#testParse`[1] since the parsed version will always be in bytes but the original will be in any unit. I think this is ok because we chack the original and the parsed version are equal but I wanted to point it out. Does this sound ok to you?


[1] https://github.com/elastic/elasticsearch/pull/27702/files#diff-6be961ed1a7543ed4fff562bef6b5680R240

Comment (colings86) [reply core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: Actually I think I have got a bwc to change the parsing to preserve the unit as well. To keep it bwc I've made it revert to converting the unit to bytes if the input value is fractional.

**Comment by colings86** [comment]
@jasontedor I pushed a couple of commits to address your comments. Could you take another look?

**Comment by colings86** [comment]
jenkins retest this

**Review by jasontedor — APPROVED** [review]
LGTM.

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java [hunk 3]
```diff
@@ -105,26 +134,33 @@ public double getPbFrac() {
         return ((double) getBytes()) / ByteSizeUnit.C5;
     }
 
+    public String getStringRep() {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: Please add javadocs to explain how this differs from toString()

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java [hunk 4]
```diff
@@ -51,8 +65,23 @@ public ByteSizeValue(long bytes) {
     public ByteSizeValue(long size, ByteSizeUnit unit) {
         this.size = size;
         this.unit = unit;
+        if (size > Long.MAX_VALUE / unit.toBytes(1)) {
+            throw new IllegalArgumentException(
+                    "Values greater than " + Long.MAX_VALUE + " bytes are not supported: " + size + unit.getSuffix());
+        }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: should it also fail if size is < -1 or if size == -1 and unit != BYTES?

**Review by jpountz — APPROVED** [review]
I left some questions but the change looks good.

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java (hunk 4 above)
Comment (colings86) [reply core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: Agreed, see https://github.com/elastic/elasticsearch/pull/27702/commits/ad16a5ce33b4b3b045f67aa5d5471a0ed68597d2

File: core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java (hunk 3 above)
Comment (colings86) [reply core/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java]: Agreed, see https://github.com/elastic/elasticsearch/pull/27702/commits/ad16a5ce33b4b3b045f67aa5d5471a0ed68597d2

**Comment by colings86** [comment]
@jpountz @jasontedor thanks for the reviews. I've addressed the last review comments and will merge this when I get a green build

File: core/src/test/java/org/elasticsearch/cluster/DiskUsageTests.java [hunk 5]
```diff
@@ -184,12 +181,12 @@ public void testFillDiskUsageSomeInvalidValues() {
...
         };
         FsInfo.Path[] node2FSInfo = new FsInfo.Path[] {
-                new FsInfo.Path("/least_most", "/dev/sda", -2, -1, -1),
+                new FsInfo.Path("/least_most", "/dev/sda", -1, -1, -1),
         };
 
         FsInfo.Path[] node3FSInfo =  new FsInfo.Path[] {
                 new FsInfo.Path("/most", "/dev/sda", 100, 90, 70),
-                new FsInfo.Path("/least", "/dev/sda", 10, -8, 0),
+                new FsInfo.Path("/least", "/dev/sda", 10, -1, 0),
```
Comment (colings86) [inline core/src/test/java/org/elasticsearch/cluster/DiskUsageTests.java]: @jasontedor this is the test I am unsure about. It failed when I added code to reject negative bytes values (expect the special -1 value) because this test explicitly checked that negative values for disk stats were accepted but the disk is skipped. From looking at [FSProbe#L143](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/monitor/fs/FsProbe.java#L143) which is where we gather the disk statistics it seems that we can't actually get negative values here and instead any value reported by the OS as negative are interpreted by FSProbe as an overflow and are converted to `Long.MAX_VALUE`. 

I changed this test to use the special -1 value instead and check the disks are still skipped but maybe we actually don't need this test at all?

Comment (jasontedor) [reply core/src/test/java/org/elasticsearch/cluster/DiskUsageTests.java]: I agree, the test was doing unrealistic things so I am fine with the change you made here. Let's keep whether or not the test is needed as a separate issue. There's probably other cleanup to do here, like adding asserts in FsInfo.Path about not seeing negative values.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by colings86** [comment]
jenkins test this please

**Comment by colings86** [comment]
Backport to 6.x is done but leaving the label as a reminder to change the bwc version on master to 6.2.0 once the builds have caught up with the backport

**Comment by cbuescher** [comment]
@colings86 I went ahead and pushed 54b1fed5b381610bd4899067d66e199527c80e45 to correct the bwc version on master because I think mixed cluster tests were failing, hope this was okay. Can you check briefly.

**Comment by colings86** [comment]
@cbuescher thanks for doing that.
