### PR TITLE
Fix testCannotFollowLeaderInUpgradedCluster

### LINKED ISSUE #100291: [CI] CcrRollingUpgradeIT testCannotFollowLeaderInUpgradedCluster failing
This looks like more fallout from the 8.12 version bump.

**Build scan:**
https://gradle-enterprise.elastic.co/s/iznsqgeozhlcw/tests/:x-pack:qa:rolling-upgrade-multi-cluster:v8.11.0%23follower%23upgradedClusterTest/org.elasticsearch.upgrades.CcrRollingUpgradeIT/testCannotFollowLeaderInUpgradedCluster
**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade-multi-cluster:v8.11.0#follower#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.CcrRollingUpgradeIT" -Dtests.method="testCannotFollowLeaderInUpgradedCluster" -Dtests.seed=27E3EAD1DEC83E86 -Dtests.bwc=true -Dtests.locale=sl-SI -Dtests.timezone=America/Caracas -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.CcrRollingUpgradeIT&tests.test=testCannotFollowLeaderInUpgradedCluster
**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([27E3EAD1DEC83E86:A9BC1A5D74E1259D]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
  at org.elasticsearch.upgrades.CcrRollingUpgradeIT.testCannotFollowLeaderInUpgradedCluster(CcrRollingUpgradeIT.java:223)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by idegtiarenko**
This change introduces a new arbitrary index version so that it is not possible to restore 8.12 index in 8.11.

Fixes: #100291

### CODE REVIEW

File: x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java [hunk 1]
```diff
@@ -224,8 +226,20 @@ public void testCannotFollowLeaderInUpgradedCluster() throws Exception {
                 ResponseException.class,
                 () -> followIndex(leaderClient(), "follower", "not_supported", "not_supported")
             );
-            assertThat(e.getMessage(), containsString("the snapshot was created with index version ["));
-            assertThat(e.getMessage(), containsString("] which is higher than the version used by this node ["));
+
+            assertThat(
+                e.getMessage(),
+                allOf(
```
Comment (DaveCTurner) [inline x-pack/qa/rolling-upgrade-multi-cluster/src/test/java/org/elasticsearch/upgrades/CcrRollingUpgradeIT.java:232]: I think this should be `anyOf(allOf(...), allOf(...))` - we don't have all possible combinations of messages

File: server/src/main/java/org/elasticsearch/index/IndexVersions.java [hunk 2]
```diff
@@ -87,6 +87,7 @@ private static IndexVersion def(int id, Version luceneVersion) {
     public static final IndexVersion NEW_SPARSE_VECTOR = def(8_500_001, Version.LUCENE_9_7_0);
     public static final IndexVersion SPARSE_VECTOR_IN_FIELD_NAMES_SUPPORT = def(8_500_002, Version.LUCENE_9_7_0);
     public static final IndexVersion UPGRADE_LUCENE_9_8 = def(8_500_003, Version.LUCENE_9_8_0);
+    public static final IndexVersion ES_VERSION_8_12 = def(8_500_004, Version.LUCENE_9_8_0);
```
Comment (kingherc) [inline server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: For my understanding, how does this new IndexVersion get used, since I do not see it anywhere used in this PR?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: It means that `org.elasticsearch.index.IndexVersion#current` is strictly greater in `main` than in `8.11` which allows us to enforce the right version barrier between `8.11.1-SNAPSHOT` and `8.12.0-SNAPSHOT` builds. Otherwise they have the same `org.elasticsearch.index.IndexVersion#current` which makes ES think that their indices are compatible, which breaks some test assumptions.

Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: @kingherc, `def` adds this version into `IndexVersions#IDS`. It is used later via `LATEST_DEFINED = VERSION_IDS.lastEntry().getValue();`

Comment (rjernst) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: nit: can the name be more tailored to what this is guarding? As it is, others might think a new "ES_VERSION_XXX" is needed for ever minor, yet this is specifically a guard for a bug around snapshots metadata in 8.11 right?

Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: There is nothing preventing such thing from happening during the next release. I would add it every time we release for simplicity.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: ++ I think this needs a discussion about how to handle it long-term, whether we want to preserve this behaviour (and today's tests) or not. If we want to do this every time, we need to update the release/version-bump process.

Comment (rjernst) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: I thought this was a different issue. I've added this topic for discussion to the core/infra agenda.

Comment (rjernst) [reply server/src/main/java/org/elasticsearch/index/IndexVersions.java:90]: After discussing with core/infra, I think the test issue can be assigned over to core/infra for resolution. We don't want to add new IndexVersions here, but rather slightly relax our "nothing can have semantic version checks" rules. We will follow up with a couple changes:
* Make the snapshot metadata check only occur for on-prem, and go back to semantic versions
* Add facilities for semantic version checks that will only run in serverless. This would be for things that serverless doesn't need to care about (like this too-new-index check).

**Comment by rjernst** [comment]
In addition to my [comment](https://github.com/elastic/elasticsearch/pull/101906#discussion_r1400893194) on the future of the underlying version check, after discussion with Henning I think we can still merge this PR. It won't make the situation any worse (we need to handle moving the metadata back to storing semantic version, and account for index versions). Additional index versions won't hurt that work, and it would be good to get this test running again.

**Comment by idegtiarenko** [comment]
In context of the above comment, could somebody please review again and approve?

**Review by DaveCTurner — APPROVED** [review]
LGTM (test failure is unrelated & addressed by https://github.com/elastic/elasticsearch/pull/102398), I suggest merging latest `main`.

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by idegtiarenko** [comment]
Thanks all!
