### PR TITLE
Fix error message for a put index template request without index_patterns

### LINKED ISSUE #27100: Improve error message for missing template pattern
**Describe the feature**:
We currently provide a fairly unhelpful message when somebody is missing `index_patterns`

```
PUT _template/foo
{
    "settings": {
      "index": {
        "number_of_shards": "1",
        "number_of_replicas": "0"
      }
    }
}
```

returns

```
{
  "error": {
    "root_cause": [
      {
        "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: pattern is missing;"
      }
    ],
    "type": "action_request_validation_exception",
    "reason": "Validation Failed: 1: pattern is missing;"
  },
  "status": 400
}
```

The message is fairly difficult to decipher as a new user.  It made more sense in 5.x when the name of the parameter was `pattern`, but in 6.x, we've moved to `index_patterns`.  The `1` also isn't clear to a new user.

**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0-rc1

**JVM version** (`java -version`): openjdk 8

### PR DESCRIPTION
**Pull request by dnhatn**
Correct the error message from `"Validation Failed: 1: pattern is missing;"` to `"Validation Failed: 1: index_patterns is missing;"`.

Closes #27100

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
I disagree with this change, the numbers are useful. The bigger problem with #27100 is the name of the missing field in the template is wrong.

**Comment by dnhatn** [comment]
@jasontedor, did you mean that we should emit `"reason":"Validation Failed: 1: index_patterns is missing;"`?

**Comment by jasontedor** [comment]
Yes, the field should be precise; it's `index_patterns` in 6.x now.

**Comment by dnhatn** [comment]
@jasontedor , I reverted the previous commit and updated the error message. Could you please have another look. Thank you.

File: core/src/main/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequest.java [hunk 1]
```diff
@@ -104,7 +104,7 @@ public ActionRequestValidationException validate() {
             validationException = addValidationError("name is missing", validationException);
         }
         if (indexPatterns == null || indexPatterns.size() == 0) {
-            validationException = addValidationError("pattern is missing", validationException);
+            validationException = addValidationError("index_patterns is missing", validationException);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequest.java]: I wonder if this should be "index patterns are missing" as these requests can also come in from the transport layer where there is no notion of a "index_patterns" field?

**Review by jasontedor — COMMENTED** [review]
I left a question.

File: core/src/main/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequest.java (hunk 1 above)
Comment (dnhatn) [reply core/src/main/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequest.java]: Makes sense. I pushed another change https://github.com/elastic/elasticsearch/pull/27102/commits/f81b8eae94d69b6fd6f748f0782649932f488e58.

**Review by jasontedor — CHANGES_REQUESTED** [review]
A REST test is fine; can we have a unit test too?

**Comment by dnhatn** [comment]
@jasontedor Sure, I added a unit test in https://github.com/elastic/elasticsearch/pull/27102/commits/7cc6eb4adf9a013f03c1dbe95b4e04e443123e97.

File: core/src/test/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequestTests.java [hunk 2]
```diff
@@ -107,4 +111,21 @@ public void testPutIndexTemplateRequestSerializationXContentBwc() throws IOExcep
...
+        assertThat(withoutNameAndPattern.getMessage(), containsString("index patterns are missing"));
+
+        request.name("foo");
+        ActionRequestValidationException withoutIndexPatterns = request.validate();
+        assertThat(withoutIndexPatterns.validationErrors(), hasSize(1));
+        assertThat(withoutIndexPatterns.getMessage(), containsString("index patterns are missing"));
+
+        request.patterns(Collections.singletonList("test-*"));
+        ActionRequestValidationException noError = request.validate();
+        assertTrue(noError == null || noError.validationErrors().isEmpty());
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequestTests.java]: I don't like `assertTrue`, it never gives useful failure messages (just expected true but was false). Also, I'm missing why this might be null or have empty validation errors. Can you explain why this is not definite?

**Review by jasontedor — COMMENTED** [review]
I left a question.

File: core/src/test/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequestTests.java (hunk 2 above)
Comment (dnhatn) [reply core/src/test/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequestTests.java]: I did not read the function carefully. This is addressed, could you please have another review?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
It's a small issue but I have learned many things from your feedbacks. Thank you @jasontedor.

**Comment by jasontedor** [comment]
@dnhatn This change should not have gone in to the 6.0 branch, we are trying to keep changes to the minimum necessary at this point. This one is harmless, but we want to hold a strict line here. You can keep this one in, but please keep this in mind in the future when we are trying to stabilize. Also, the label on this one is not correct, it is not a bug, it's an enhancement. I should have caught both of these during review, that's on me in the future.

**Comment by dnhatn** [comment]
@jasontedor, I agree. This should not go into 6.0 but 6.1.0.
