### PR TITLE
Fix flaky GCS ADC fallback test by isolating in its own JVM

### LINKED ISSUE #145689: [CI] GoogleCloudStorageServiceTests testApplicationDefaultCredentialsFallbackToComputeEngine failing
**Build Scans:**
- [elasticsearch-periodic #12080 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/gmzwa2ut2ppe6)
- [elasticsearch-periodic-platform-support #12057 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/55ecw5v5zgtii)
- [elasticsearch-periodic-platform-support #12057 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/xakdqzndd4cne)
- [elasticsearch-periodic-platform-support #12057 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/y254s273cnr24)
- [elasticsearch-periodic-platform-support #12057 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/xhmfgj4q3fnmk)
- [elasticsearch-periodic-platform-support #12057 / debian-13_platform-support-unix](https://gradle-enterprise.elastic.co/s/ppouvzovpitde)
- [elasticsearch-periodic-platform-support #12057 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/jec5bqaoef6ou)
- [elasticsearch-periodic-platform-support #12057 / rocky-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/sacivdpk37wha)
- [elasticsearch-periodic-platform-support #12057 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/ltypzpzjrlopk)
- [elasticsearch-periodic-platform-support #12057 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/vnk4niujy5lju)

**Reproduction Line:**
```
./gradlew ":modules:repository-gcs:test" --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageServiceTests.testApplicationDefaultCredentialsFallbackToComputeEngine" -Dtests.seed=FDFCD28223C3C6E0 -Dtests.jvm.argline="-Des.concurrent_search=true" -Dtests.locale=fr-CH -Dtests.timezone=Pacific/Noumea -Druntime.java=25
```

**Applicable branches:**
9.3

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.gcs.GoogleCloudStorageServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testApplicationDefaultCredentialsFallbackToComputeEngine'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: GCP metadata server should have been contacted to obtain Application Default Credentials
```

**Issue Reasons:**
- [9.3] 1 consecutive failures in test testApplicationDefaultCredentialsFallbackToComputeEngine
- [9.3] 2 consecutive failures in step concurrent-search-tests
- [9.3] 3 consecutive failures in step openjdk25_checkpart1_java-matrix
- [9.3] 1 consecutive failures in pipeline elasticsearch-periodic
- [9.3] 50 failures in test testApplicationDefaultCredentialsFallbackToComputeEngine (39.1% fail rate in 128 executions)
- [9.3] 2 failures in step concurrent-search-tests (66.7% fail rate in 3 executions)
- [9.3] 3 failures in step rocky-8_platform-support-unix (50.0% fail rate in 6 executions)
- [9.3] 3 failures in step oraclelinux-9_platform-support-unix (50.0% fail rate in 6 executions)
- [9.3] 2 failures in step ubuntu-2204_platform-support-unix (40.0% fail rate in 5 executions)
- [9.3] 2 failures in step rhel-8_platform-support-unix (40.0% fail rate in 5 executions)
- [9.3] 2 failures in step debian-13_platform-support-unix (40.0% fail rate in 5 executions)
- [9.3] 2 failures in step rhel-9_platform-support-unix (40.0% fail rate in 5 executions)
- [9.3] 3 failures in step rhel-10_platform-support-unix (50.0% fail rate in 6 executions)
- [9.3] 2 failures in step rocky-10_platform-support-unix (40.0% fail rate in 5 executions)
- [9.3] 2 failures in step debian-12_platform-support-unix (40.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jdconrad**
- Move `testApplicationDefaultCredentialsFallbackToComputeEngine` from `GoogleCloudStorageServiceTests` to a new `GoogleCloudStorageAdcTests` class
- Run it via a dedicated `gcsAdcTest` Gradle task in its own JVM, ensuring the `DefaultCredentialsProvider` singleton starts with clean state (`cachedCredentials`, `checkedComputeEngine`)
- Add auth validation and metadata request handling to the GCS test fixture

The test was failing ~38% of the time (#145689) because Google's `DefaultCredentialsProvider` singleton caches credentials and GCE detection state. When another test in the same JVM primed the singleton before this test ran, the credential discovery flow (including the `File.isFile()` entitlement check) was bypassed entirely.

Closes #145689

### CODE REVIEW

File: modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageAdcTests.java [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+ */
+public class GoogleCloudStorageAdcTests extends ESTestCase {
+
+    /**
+     * Verifies that when no explicit credentials are configured and no credential files are found
+     * (either because they genuinely don't exist, or because {@code File.isFile()} returns
+     * {@code false} due to entitlement enforcement), the GCS service correctly falls back to
+     * obtaining credentials from the GCP metadata server via Application Default Credentials.
+     *
+     * <p>This test exercises the code path that was broken when {@code NotEntitledException}
```
Comment (rjernst) [inline modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageAdcTests.java]: nit: I don't think this comment is really necessary. entitlements is not the point of this test, it just _should_ have caught the entitlements issue if it had actually been running.

**Review by rjernst — APPROVED** [review]
Looks good, one nit about a comment

File: modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageAdcTests.java (hunk 1 above)
Comment (jdconrad) [reply modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageAdcTests.java]: Removed.
