### PR TITLE
Fix propagating the default value for script settings

### LINKED ISSUE #20159: Setting `script.inline: false` doesn't disable all inline scripting
Starting elasticsearch as follows:

    bin/elasticsearch -Escript.inline=false

should disable all inline scripting, but it doesn't:

    GET /_cluster/settings?include_defaults&filter_path=**.script.engine.*.inline

returns:

    {
      "defaults": {
        "script": {
          "engine": {
            "painless": {
              "inline": "true"
            },
            "expression": {
              "inline": "true"
            },
            "groovy": {
              "inline": "false"
            },
            "mustache": {
              "inline": "true"
            }
          }
        }
      }
    }

First reported in https://github.com/elastic/kibana/issues/6529#issuecomment-224675359

### PR DESCRIPTION
**Pull request by dakrone**
Fixes an issue where the value for the `script.engine.<lang>.inline`
settings would be _set_ properly, but would not accurately be reflected
in the `include_defaults` output. Adds a test to ensure the default raw
setting is now correct.

Resolves #20159

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/script/ScriptSettings.java [hunk 1]
```diff
@@ -97,9 +97,25 @@ public ScriptSettings(ScriptEngineRegistry scriptEngineRegistry, ScriptContextRe
                 }
                 final boolean defaultIfNothingSet = defaultLangAndType;
 
+                Function<Settings, String> defaultLangAndTypeFn = settings -> {
+                    final Setting<Boolean> globalTypeSetting = scriptTypeSettingMap.get(scriptType);
+                    final Setting<Boolean> langAndTypeSetting = Setting.boolSetting(ScriptModes.getGlobalKey(language, scriptType),
+                            defaultIfNothingSet, Property.NodeScope);
+
+                    if (langAndTypeSetting.exists(settings)) {
+                        // fine-grained script.engine.groovy.inline
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/script/ScriptSettings.java]: `// fine-grained e.g. script.engine.groovy.inline`?

**Comment by nik9000** [comment]
LGTM. Left a minor thing about a comment.
