### PR TITLE
[CCR] Record follower index historyUUIDs

### LINKED ISSUE #33956: [CCR] Shard follow task should validate follow shard history uuid
Currently it is possible to to remove the follower index while ccr replicates document from a leader index into it and then to create a new follower index (just via create index api) and ccr will then after retrying continue to replicate documents into the the just newly created index. This is bad, because all checks that we do in the follow index are bypassed and the follow index is no longer identical to the leader index.

In order to prevent this situation, the shard follow tasks need to continuously check whether the follow shard is the same shard. I think the best way to do this is to record the history uuid of the follow shard when the shard follow task is started and the pass that down to the bulk shard operations api. In the bulk shard operations api we would then check if the provided history uuid is identical to the current history uuid and if not fail with an error that the shard follow task does not retry (e.g. IllegalStateException).

Note that in #33954, we plan to no longer retry `IndexNotFoundException` exception and that should fail a shard follow task if it would replicate the documents into a follow shard. However that doesn't help in the case that a shard follow task is idle (because there are no documents to replicate), because when after the idle period, when the shard follow task starts to replicate, the underlying follow index could have been changed.

### PR DESCRIPTION
**Pull request by martijnvg**
and verify on each bulk shard operation execution that these history UUIDs did not change.

The tricky bit in this change is that adds another async step to the create and follow api (soon to be renamed to follow api).
After the follower index has been created an its shards have started, the history UUIDs of the follower shards need be
fetched and stored in the follower index's custom metadata.

The follow api (soon to be renamed resume follow api) will fail if follower index shard history UUIDs are missing. (leader index shard UUIDs too)

Closes #33956

### CODE REVIEW

**Comment by bleskes** [comment]
I'm a bit on the fence about recording the history uuids in the index meta data. I get the need now, but I'm wondering whether long term we want to remove this. I suspect we will transfer history uuids with the future recovery mechanism. This would mean that we need to continuously validate that the history of the source with the one of the target with each operation and we will not need to store anything.

With that in mind, I want to understand if we're viewing this a temporary mechanism (i.e., accept compromises) and if so whether we really want to do it now rather than wait. I'm on the fence myself.

**Comment by martijnvg** [comment]
Good question. I don't feel comfortable with releasing CCR without the follower index UUID check that this change adds. I agree that this is a temporary solution until there is the new ccr recovery mechanism is added. So when that is added, we can remove the check that this PR is adding?

**Comment by bleskes** [comment]
That's my sentiment too. I that case I'm ok with the async extra call and there is no need to invest in cleaner solutions that will take more refactoring (will review shortly)

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTask.java [hunk 1]
```diff
@@ -50,13 +50,15 @@
     public static final ParseField MAX_WRITE_BUFFER_SIZE = new ParseField("max_write_buffer_size");
     public static final ParseField MAX_RETRY_DELAY = new ParseField("max_retry_delay");
     public static final ParseField POLL_TIMEOUT = new ParseField("poll_timeout");
-    public static final ParseField RECORDED_HISTORY_UUID = new ParseField("recorded_history_uuid");
+    public static final ParseField RECORDED_LEADER_HISTORY_UUID = new ParseField("recorded_leader_history_uuid");
```
Comment (bleskes) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTask.java]: Why are these properties of the Task - they are properties of the index (meta data)? we should get them from there?

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportCreateAndFollowIndexAction.java [hunk 2]
```diff
@@ -224,19 +211,51 @@ public ClusterState execute(final ClusterState currentState) throws Exception {
...
+                                        e -> {
+                                            logger.error("Failed to initiate the shard following", e);
+                                            listener.onResponse(new CreateAndFollowIndexAction.Response(true, true, false));
+                                        }
+                                    ));
+                                }
+                            });
+                        });
                     } else {
                         listener.onResponse(new CreateAndFollowIndexAction.Response(true, false, false));
```
Comment (bleskes) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportCreateAndFollowIndexAction.java]: I wondering if we should throw an exception here. Normally when something isn't acked, if you wait it will go through (or at has a chance of doing it). This one will just get stuck.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/bulk/BulkShardOperationsRequest.java [hunk 3]
```diff
@@ -16,19 +16,28 @@
...
     }
 
-    public BulkShardOperationsRequest(ShardId shardId, List<Translog.Operation> operations, long maxSeqNoOfUpdatesOrDeletes) {
+    public BulkShardOperationsRequest(final ShardId shardId,
+                                      final String expectedHistoryUUID,
+                                      final List<Translog.Operation> operations,
+                                      long maxSeqNoOfUpdatesOrDeletes) {
         super(shardId);
         setRefreshPolicy(RefreshPolicy.NONE);
+        this.expectedHistoryUUID = expectedHistoryUUID;
```
Comment (bleskes) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/bulk/BulkShardOperationsRequest.java]: I think we can call this history uuid, as it is the one that the ops belong to.

Comment (bleskes) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/bulk/BulkShardOperationsRequest.java]: (working towards how we want it in the future)

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/bulk/TransportBulkShardOperationsAction.java [hunk 4]
```diff
@@ -61,17 +61,23 @@ public TransportBulkShardOperationsAction(
...
     // public for testing purposes only
     public static WritePrimaryResult<BulkShardOperationsRequest, BulkShardOperationsResponse> shardOperationOnPrimary(
             final ShardId shardId,
+            final String expectedHistoryUUID,
             final List<Translog.Operation> sourceOperations,
             final long maxSeqNoOfUpdatesOrDeletes,
             final IndexShard primary,
             final Logger logger) throws IOException {
+        if (expectedHistoryUUID.equalsIgnoreCase(primary.getHistoryUUID()) == false) {
+            throw new IllegalStateException("unexpected history uuid, expected [" + expectedHistoryUUID +
```
Comment (bleskes) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/bulk/TransportBulkShardOperationsAction.java]: Can we add "shard is likely restored from snapshot or force allocated".

**Review by bleskes — COMMENTED** [review]
I left some comments. I think we need some more discussions here in the sync

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTask.java (hunk 1 above)
Comment (martijnvg) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTask.java]: Good point. We can remove them here and then make the IndexMetaData of the follower available in `ShardFollowNodeTask`. Are you ok if I do this in a follow up? (it affect the UUIDs of both leader and follower index)

**Comment by bleskes** [comment]
I talked this through with @ywelsch and we came to the conclusion that those history uuids of the follower can be captured on the instance level of the `ShardFollowNodeTask`. They basically mean that the information in that class (which was captured when it was bootstrapped) is safe to use. This implies that we can capture the history uuid when starting the task (like we do with the global checkpoint) and store it in a field of the task instance and use that to validate. Any error there should cause the task to pause and people can use resume to force another task to be started which can safely proceed.

**Comment by martijnvg** [comment]
@bleskes I've made the following changes:
* Don't record leader history uuid in the `ShardFollowTask`, but fetch it from the follower index's custom metadata.
* Bootstrap the follower history uuid when the shard follow task is started instead of recording it in `ShardFollowTask` when put follow api is executed.

**Review by bleskes — APPROVED** [review]
LGTM! nice work.
