### PR TITLE
Split third party audit exclusions by type 

### LINKED ISSUE #35591: ThirdPartyAudit failed: invalid exclusions
This build failed:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/59/console

It looks like this is the relevant error message:

```
Execution failed for task ':x-pack:plugin:sql:sql-action:thirdPartyAudit'.
> Invalid exclusions, nothing is wrong with these classes:   * com.fasterxml.jackson.dataformat.xml.XmlMapper
    * com.fasterxml.jackson.dataformat.yaml.YAMLMapper
    * com.lmax.disruptor.LifecycleAware
    * com.lmax.disruptor.RingBuffer
    * com.lmax.disruptor.dsl.Disruptor
    * com.lmax.disruptor.dsl.ProducerType
    * javax.jms.ConnectionFactory
    * javax.jms.Destination
    * javax.jms.Message
    * javax.jms.MessageConsumer
    * javax.jms.MessageProducer
    * javax.jms.Session
    * javax.mail.internet.InternetAddress
    * org.apache.kafka.clients.producer.KafkaProducer
    * org.apache.kafka.clients.producer.ProducerRecord
    * org.fusesource.jansi.Ansi
    * org.fusesource.jansi.AnsiRenderer$Code
    * org.osgi.framework.AdaptPermission
    * org.osgi.framework.AdminPermission
    * org.osgi.framework.BundleActivator
    * org.osgi.framework.BundleContext
    * org.osgi.framework.BundleEvent
    * org.osgi.framework.ServiceRegistration
    * org.osgi.framework.SynchronousBundleListener
    * org.osgi.framework.wiring.BundleWire
    * org.osgi.framework.wiring.BundleWiring
```

Sorry, not sure what else would be helpful here.

### PR DESCRIPTION
**Pull request by alpar-t**
With this change exclusions have to be specific for: class not found, use of forbidden APIs, or jar hell with the JDK. There's also a means to allow for any missing class as this is clearly the intent of some projects ( having ~2000 exclusions doesn't provide any value).

All the build-scripts are updated to reflect this. 
Not that the task validates the changes in the build scripts as we provide no leniency in any of the excludes, so any error in this migration would fail the build. 

This  closes #35591 , as the problem there was  likely a crash in forbidden APIs. 
We now output the output and try to detect it to provide a better  error message.

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java [hunk 1]
```diff
@@ -115,19 +124,36 @@ public File getJarExpandDir() {
...
 
-    public void setExcludes(String... classes) {
-        excludes.clear();
+    public void allowMissingClasses(String... classesOrPackages) {
+        for (String each : classesOrPackages) {
+            missingClassExcludes.add(each);
+        }
+    }
+
+    public void allowViolations(String... violatingClasses) {
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: Instead of "allow", I would use the term "ignore". I think that better matches what we are doing.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java [hunk 2]
```diff
@@ -115,19 +124,36 @@ public File getJarExpandDir() {
...
+        for (String each : violatingClasses) {
+            violationsExcludes.add(each);
+        }
+    }
+
+    public void allowAllMissingClasses() {
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: I don't think this is necessary? The method above taking varargs would come through as an empty array if called with no args, so this can be handled there.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java [hunk 3]
```diff
@@ -63,17 +64,20 @@
         "\\s\\sin ([a-zA-Z0-9$.]+) \\(.*\\)"
     );
 
-    /**
-     * patterns for classes to exclude, because we understand their issues
-     */
-    private Set<String> excludes = new TreeSet<>();
+    private Set<String> missingClassExcludes = new TreeSet<>();
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: Why TreeSets? the order should not matter?

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java [hunk 4]
```diff
@@ -115,19 +124,36 @@ public File getJarExpandDir() {
...
+    }
+
+    public void allowViolations(String... violatingClasses) {
+        for (String each : violatingClasses) {
+            violationsExcludes.add(each);
+        }
+    }
+
+    public void allowAllMissingClasses() {
+        allowAllMissingClasses = true;
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: Instead of a boolean, I wonder if it would be better to use `null` as an indicator for all? Then have a special string like "*" that can be passed to the method taking package names (and it looks like a wildcard on package/classnames). This way there is only one dsl method for each type of ignore.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java [hunk 5]
```diff
@@ -152,6 +178,13 @@ public void setExcludes(String... classes) {
 
     @TaskAction
     public void runThirdPartyAudit() throws IOException {
+        if (isAllowAllMissingClasses() && (false == missingClassExcludes.isEmpty())) {
+            getLogger().error("There should be no explicit missing classes listed " +
+                "when the task is configured to allow all, yet these are present:\n {}", formatClassList(missingClassExcludes));
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: With what I suggested above, I believe this check can be done at configuration time instead of runtime

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java [hunk 6]
```diff
@@ -230,33 +303,22 @@ private void assertNoJarHell(Set<String> jdkJarHellClasses) {
...
-                    (missingText.isEmpty() ?  "" : "Missing classes:\n" + missingText) +
-                    (violationsText.isEmpty() ? "" : "Classes with violations:\n" + violationsText)
-            );
+    private void assertNoPointlessExclusions(String specifics, Set<String> excludes, Set<String> problematic) {
+        String notMissing = excludes.stream()
+            .filter(each -> problematic.contains(each) == false)
+            .map(each -> "  * " + each)
+            .collect(Collectors.joining("\n"));
+        if (notMissing.isEmpty() == false) {
+            getLogger().error("Invalid exclusions, following classes " + specifics + ":\n {}", notMissing);
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: Maybe use "unnecessary" instead of "invalid"? The latter might imply a syntax error, when instead the exclusion should just be removed

**Review by rjernst — COMMENTED** [review]
Overall looks good. I left a few comments.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 1 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: I agree, I changed it in all the methods.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 4 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: I like the empty array version more so we just have `ignoreMissingClasses()`.
 `*` wouldn't be bad if we supported more pattern types.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 5 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: with the new DSL it didn't seem right to have this limitation any more, so one can go from broad to specific now.

**Comment by atorok** [comment]
@rjernst  ready for another round. I implemented your suggestions and left some comments.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 3 above)
Comment (rjernst) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: I'm not sure I understand. We don't print this set; we only use it to check a class that was caught missing by running forbidden apis right?

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 4 above)
Comment (rjernst) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: I think ignoreMissingClasses by itself is confusing personally, but I would be interested to see what others think. This isn't crucial for checking this in, but I would raise it for discussion after the holidays.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 5 above)
Comment (rjernst) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: You mean that one could have:

```
thirdPartyAudit {
  ignoreMissingClasses '*'
  ignoreMissingClasses 'foo.bar.Baz'
}
```

That seems odd. Why do we need that leniency?

**Review by rjernst — APPROVED** [review]
I left a few responses. None are critical to getting this in, but I would like it if they are addressed in followup issues/discussions.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 3 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: We do print it if it contains unnecessary entries and you could have allot of them say after a dependency upgrade.

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 6 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: changed

File: buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java (hunk 5 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/precommit/ThirdPartyAuditTask.java]: I'm not arguing that we need it, I don't even like having i, but it's something that Gradle generally offers. So from a Gradle perspective, having a property that when set to some specific value can no longer be changed is odd. I think that changing the way Gradle works too much makes the build harder to understand and work with because it increases the amount of specific knowledge required to work with or change it.
