### PR TITLE
[ES|QL] Add TSTEP(step, from, to) explicit bounds variant

### LINKED ISSUE #147228: ESQL: Add TSTEP(<period_or_duration>, <from>, <to>) variant
### CI Link

https://gradle-enterprise.elastic.co/s/ca7cevelvrjby - more failures in https://github.com/elastic/elasticsearch/issues/147058

### Repro line

./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.CsvIT" -Dtests.method="test {csv-spec:tstep.tstep_with_request_timestamp_bounds_only}" -Dtests.seed=CD3B1B924840254 -Dtests.locale=sd-Arab-PK -Dtests.timezone=SystemV/HST10 -Druntime.java=26

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
org.elasticsearch.xpack.esql.VerificationException: Found 1 problem
line 2:66: [TSTEP("1 hour")] requires a `@timestamp` range in the request query filter to anchor the step grid
```

### PR DESCRIPTION
**Pull request by sidosera**
Follow-up to https://github.com/elastic/elasticsearch/pull/144967. Adds explicit `start` & `end` arguments to  `TSTEP` so callers can supplyit explicitly similar to `TRANGE`.

Closes https://github.com/elastic/elasticsearch/issues/147228.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -1621,6 +1621,11 @@ public enum Cap {
          */
         TSTEP(Build.current().isSnapshot()),
 
+        /**
+         * Support for tstep explicit bounds variant: TSTEP(step, from, to)
+         */
+        TSTEP_EXPLICIT_BOUNDS(Build.current().isSnapshot()),
```
Comment (felixbarny) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]:
```suggestion
        TSTEP_EXPLICIT_BOUNDS(TSTEP.isEnabled()),
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java [hunk 2]
```diff
@@ -96,43 +101,35 @@ public class TStep extends GroupingFunction.EvaluatableGroupingFunction
...
-
-    /**
-     * Full constructor including optional bounds merged from the request {@code @timestamp} filter during analysis.
-     */
     public TStep(
         Source source,
-        Expression step,
-        @Nullable Expression start,
-        @Nullable Expression end,
+        @Param(name = "step", type = { "time_duration" }, description = """
```
Comment (felixbarny) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java:113]: Just like TBUCKET, this should accept either the target number of buckets, or desired bucket size. Right now, we only have the latter.

It's ok to have a separate PR for this but it should follow-up soon after, probably before we remove the snapshot gating.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java
Comment (felixbarny) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java]: We don't want `TSTEP(1 hour, "2023-10-23T12:15:00Z")` to succeed. Both params need to be absent to trigger injection. This is how `TBUCKET` works as well. Please also add a test case for this.
 
```suggestion
        return step.resolved() && (start == null && end == null);
```

File: docs/reference/query-languages/esql/kibana/definition/functions/tstep.json
Comment (felixbarny) [inline docs/reference/query-languages/esql/kibana/definition/functions/tstep.json:1]: This doesn't contain the from/to parameters, yet.

Comment (felixbarny) [reply docs/reference/query-languages/esql/kibana/definition/functions/tstep.json:1]: Looks like this is generated from `TStepTests.signatureTypes(...)`, which still only models the 1-arg form. That helper probably needs a small update as well so the `(step, from, to)` signatures get emitted.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java (hunk 2 above)
Comment (sidosera) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java:113]: Yup, that is on my radar. Will follow-up in a separate PR.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java
Comment (sidosera) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/TStep.java]: Good catch.

**Review by felixbarny — APPROVED** [review]

**Comment by alex-spies** [comment]
Heya, thanks a lot @sidosera . I know I'm late to the party, but I skimmed TStep.java to understand the gist of the change and this looks A-OK to me. <3
