### PR TITLE
[Transfrom] prevent transform from looping forever if delete by query fails permanently

### LINKED ISSUE #69274: [Transform] wrong retention_policy.time.max_age can cause transform to loop forever
On master build, 

```
"build" : {
    "hash" : "2b6250a014606f585f50e1fc574d178cc439b88b",
    "date" : "2021-02-08T16:32:43.645521Z"
  },
```

Create and start a transform with retention_policy.time.max_age: `60000000000d`, transform took 12 hours for a tiny dataset.

Transform configure:
```
{
  "id": "dft_sd-percentiles_1613665935_000_0",
  "version": "8.0.0",
  "create_time": 1613683935837,
  "source": {
    "index": [
      "sd"
    ],
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "dft-sd_1613683935802"
  },
  "pivot": {
    "group_by": {
      "@timestamp": {
        "date_histogram": {
          "field": "@timestamp",
          "calendar_interval": "1m"
        }
      }
    },
    "aggregations": {
      "sd_value.percentiles": {
        "percentiles": {
          "field": "sd_value",
          "percents": [
            37,
            95,
            99
          ]
        }
      }
    }
  },
  "settings": {},
  "retention_policy": {
    "time": {
      "field": "@timestamp",
      "max_age": "60000000000d"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
the yet unreleased retention policy feature uses delete by query to delete expired data. In
case of a failure its possible the indexer loops forever trying to finish a checkpoint. This
change has 2 parts: avoid the known misconfiguration that lead to the error, call the error 
handler if retention policy execution fails. This correctly connects the retention policy
execution to failure handling: A permanent error immediately sets the failed state, a
temporary issue enters the retry loop, only ending in failed state after a maximum number
of retries.

fixes #69274

Marking this as "non-issue", because retention policy is an unreleased feature, nevertheless this is a bug fix that should go into 7.12

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/transform/transforms/TimeRetentionPolicyConfigTests.java [hunk 1]
```diff
@@ -17,7 +18,10 @@
 public class TimeRetentionPolicyConfigTests extends AbstractSerializingTestCase<TimeRetentionPolicyConfig> {
 
     public static TimeRetentionPolicyConfig randomTimeRetentionPolicyConfig() {
-        return new TimeRetentionPolicyConfig(randomAlphaOfLengthBetween(1, 10), new TimeValue(randomLongBetween(60000, Long.MAX_VALUE)));
+        return new TimeRetentionPolicyConfig(
+            randomAlphaOfLengthBetween(1, 10),
+            new TimeValue(randomLongBetween(60000, Long.MAX_VALUE - 1))
```
Comment (benwtrent) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/transform/transforms/TimeRetentionPolicyConfigTests.java:23]: Long max value - 1 = `9223372036854775806L` which, transforming from milliseconds to days is: 

106751991167.30064

`new TimeValue()` assumes that the value will be `ms`. I think this will cause flakiness.

**Review by benwtrent — APPROVED** [review]
Looks good other than my flaky test concern.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/transform/transforms/TimeRetentionPolicyConfigTests.java [hunk 2]
```diff
@@ -34,4 +38,28 @@ protected TimeRetentionPolicyConfig createTestInstance() {
...
+    public void testValidationMax() {
+        TimeRetentionPolicyConfig timeRetentionPolicyConfig = new TimeRetentionPolicyConfig(
+            randomAlphaOfLengthBetween(1, 10),
+            TimeValue.parseTimeValue("600000000000d", "time value")
+        );
+
+        ActionRequestValidationException e = timeRetentionPolicyConfig.validate(null);
+        assertNotNull(e);
+        assertEquals(1, e.validationErrors().size());
+        assertEquals("retention_policy.time.max_age must not be greater than [106751.9d]", e.validationErrors().get(0));
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/transform/transforms/TimeRetentionPolicyConfigTests.java:63]: [nit] There is a slight inconsistency between wording of error messages:
"must be more than 60s"
vs
"must not be greater than"

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerFailureHandlingTests.java [hunk 3]
```diff
@@ -597,15 +598,218 @@ public void testInitializeFunction_WithWarnings() {
...
+            failureMessage.compareAndSet(null, message);
+        };
+
+        MockTransformAuditor auditor = MockTransformAuditor.createMockAuditor();
+        auditor.addExpectation(
+            new MockTransformAuditor.SeenAuditExpectation(
+                "timed out during dbq",
+                Level.WARNING,
+                transformId,
+                "Transform encountered an exception: org.elasticsearch.ElasticsearchTimeoutException: timed out during dbq Will attempt again at next scheduled trigger."
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerFailureHandlingTests.java:773]: Should there be some separation between "dbg Will"?
Maybe semicolon (";")?

**Review by przemekwitek — APPROVED** [review]
LGTM

Just 2 small wording comments.
