### PR TITLE
[ML] Fix test failure updating model deployment with stale cluster state.

### LINKED ISSUE #121165: PyTorchModelIT testUpdateDeployment_GivenAllocationsAreIncreased failure
In https://github.com/elastic/elasticsearch/pull/120064 a test failed due to an unusual cluster state update failure

```
[2025-01-29T11:27:29,499][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [javaRestTest-2] fatal error in thread [elasticsearch[javaRestTest-2][masterService#updateTask][T#1]], exiting
java.lang.AssertionError: java.lang.IllegalStateException: cluster state update executor did not preserve version numbers: [update model deployment]
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1082) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1032) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:244) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1685) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:452) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1682) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1277) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:452) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1256) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.IllegalStateException: cluster state update executor did not preserve version numbers: [update model deployment]
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1080) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	... 13 more
```

The failure is fairly reproducible if the entire test suite is run not just a single test

```
./gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT"
```

### PR DESCRIPTION
**Pull request by davidkyle**
When updating a model deployment (for example changing the number of allocations) calculating the new deployment is an expensive operation so it is done in a separate thread outside of the `ClusterStateUpdateTask`. However, if there was another clusterstate update while computing the new deployment then submitting the cluster state fails because the version of the cluster state used to calculate the update is now lower than the version of the latest state.  

The fix is quite easy, compute the model deployment update outside of the ClusterStateUpdateTask then merge it with the latest state when executing the task. The code already has a check that the deployment update is compatible with the new state (`areClusterStatesCompatibleForRebalance(...)`) making it safe to merge the new state. 

Closes #121165

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 1]
```diff
@@ -80,9 +78,6 @@ public class TrainedModelAssignmentClusterService implements ClusterStateListene
 
     private static final Logger logger = LogManager.getLogger(TrainedModelAssignmentClusterService.class);
 
-    private static final TransportVersion RENAME_ALLOCATION_TO_ASSIGNMENT_TRANSPORT_VERSION = TransportVersions.V_8_3_0;
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:83]: These version checks are redundant in 9.0 and 9.1. The 8.x backports will need to keep them however.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java [hunk 2]
```diff
@@ -861,27 +828,17 @@ private void updateDeployment(
...
-                    deploymentId
-                )
-            );
-            return;
-        }
 
-        ActionListener<ClusterState> updatedStateListener = ActionListener.wrap(
-            updatedState -> submitUnbatchedTask("update model deployment", new ClusterStateUpdateTask() {
+        ActionListener<TrainedModelAssignmentMetadata.Builder> updatedAssignmentListener = ActionListener.wrap(
+            updatedAssignment -> submitUnbatchedTask("update model deployment", new ClusterStateUpdateTask() {
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:833]: This is the fix, here the new assignment state is passed rather than the updated cluster state.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentNodeService.java [hunk 3]
```diff
@@ -375,20 +375,17 @@ public void clusterChanged(ClusterChangedEvent event) {
         final boolean isResetMode = MlMetadata.getMlMetadata(event.state()).isResetMode();
         TrainedModelAssignmentMetadata modelAssignmentMetadata = TrainedModelAssignmentMetadata.fromState(event.state());
         final String currentNode = event.state().nodes().getLocalNodeId();
-        final boolean isNewAllocationSupported = event.state()
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentNodeService.java:378]: Another version change that is irrelevant for 9

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java (hunk 2 above)
Comment (jan-elastic) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:832]: What if the `TrainedModelAssignmentMetadata` changed in the meantime?

That's a similar bug to the existing one, right? But much smaller, because the `TrainedModelAssignmentMetadata` changes less often than the `ClusterState`.

Should we protect against that? For example, only replace the `TrainedModelAssignmentMetadata` in the `ClusterState` if it's identical to the one we started the update computation with? And if it has changed, try this process again. More or less this paradigm:
https://github.com/elastic/elasticsearch/blob/main/test/framework/src/main/java/org/elasticsearch/common/util/MockBigArrays.java#L728-L742.

Maybe that's overkill and too complicated though. WDYT?

Comment (jan-elastic) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:832]: If we're deciding not to fix this, let's leave a comment about this small issue with this implementation and call it a day

**Review by jan-elastic — CHANGES_REQUESTED** [review]
LGTM. Left one comment. Certainly a big improvement!

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java (hunk 2 above)
Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:832]: Looking at the `areClusterStatesCompatibleForRebalance` function it also checks that the `TrainedModelAssignmentMetadata` has not changed. 

https://github.com/elastic/elasticsearch/blob/ffd02c5bb52592dd038770497e630da0a30398f3/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java#L610

By comparing the starting state with the latest state before applying the updated `TrainedModelAssignmentMetadata` (which is a lightweight operation and can be done in the `ClusterStateUpdateTask`) the code is effectively performing a "compare and swap" paradigm as linked above

Comment (jan-elastic) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java:832]: OK, cool! I missed that part of the code. Guess this all works then as is

**Review by jan-elastic — APPROVED** [review]
LGTM
