### PR TITLE
Make Snapshot Logic Write Metadata after Segments

### LINKED ISSUE #25281: Master failover during snapshotting could leave the snapshot incomplete
When a snapshot is finalized, two things happen:
 1. The snap-{uuid}.dat blob is written
 2. The index-N blob is written to include the new snapshot

If the master node fails while the snapshot is being finalized, the repository can be in one of 3 states:
 1. Master has not written either snap-{uuid}.dat nor index-N before failing.
 2. Master has written snap-{uuid}.dat but has not written index-N
 3. Master has written both snap-{uuid}.dat and index-N but has not removed the snapshot from the cluster state

Currently, we handle the first and third situations just fine.  However, we do not handle the second situation properly - when the new master is elected, it will throw a FileAlreadyExistsException when it tries to take the snapshot to completion and sees that the snap-{uuid}.dat already exists, causing the snapshot finalization process to fail. 

This issue is to improve the handling of the second situation.

This issue was discovered while debugging the test failure in DedicatedClusterSnapshotRestoreIT#testMasterShutdown (https://github.com/elastic/elasticsearch/issues/25062).  This test failed as a result of two issues: 
 1. The index file not being written before the node was shutdown (leaving the snapshot incomplete)
 2. The MockRepository waiting to be awoken from being blocked on the index-N write, but the thread gets interrupted when closing the node, so I/O operations (including finalizing the snapshot by writing the index-N blob) throw a ClosedByInterruptException.

The test has been disabled with an AwaitsFix until this issue is resolved.

### LINKED ISSUE #41581: Snapshots should write out IndexMetaData after shard data
Snapshots currently first captures the current index metadata and only then writes out the shard data. This leaves room for mapping updates that have taken place after the index metadata was captured but before the shard data was written to not be taken into consideration when the index is restored. Data that was searchable under a certain key, suddenly isn't, and doing a simple update-by-query with no changes can lead to mapping updates. Possibly worse, the same index, when restored can have a mapping update that's incompatible with the existing data in the restored index.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Write metadata during snapshot finalization after segment files to prevent outdated metadata in case of dynamic mapping updates as explained in #41581
* Keep the old behavior of writing the metadata beforehand in the case of mixed version clusters for BwC reasons
   * Still overwrite the metadata in the end, so even a mixed version cluster is fixed by this change if a newer version master does the finalization
* Fixes #41581

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java [hunk 1]
```diff
@@ -377,6 +362,9 @@ public void writeBlob(String blobName, InputStream inputStream, long blobSize, b
             public void writeBlobAtomic(final String blobName, final InputStream inputStream, final long blobSize,
                                         final boolean failIfAlreadyExists) throws IOException {
                 final Random random = RandomizedContext.current().getRandom();
+                if (blobName.startsWith("index-") && blockOnWriteIndexFile) {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/snapshots/mockstore/MockRepository.java]: This is required to fix #25281. Sorry for mixing this in here, but I think the fact that we now how to allow overwrites in snapshot finalization and its effects on this are probably easier understood in one go (there was some discussion on this change in https://github.com/elastic/elasticsearch/pull/36927 and I think the concerns from there are addressed here now in the explanations added to the snapshot finalization).

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 
(unrelated ML failure)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
(unrelated Grok failure)

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 2]
```diff
@@ -3856,76 +3811,6 @@ public void testParallelRestoreOperationsFromSingleSnapshot() throws Exception {
         assertThat(client.prepareGet(restoredIndexName2, typeName, sameSourceIndex ? docId : docId2).get().isExists(), equalTo(true));
     }
 
-    public void testAbortedSnapshotDuringInitDoesNotStart() throws Exception {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: This test doesn't really apply anymore with snapshot initialization gone.

File: server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepository.java [hunk 3]
```diff
@@ -276,9 +276,11 @@ public void writeBlob(String blobName, InputStream inputStream, long blobSize, b
                     // We do some checks in case there is a consistent state for a blob to prevent turning it inconsistent.
                     final boolean hasConsistentContent =
                         relevantActions.size() == 1 && relevantActions.get(0).operation == Operation.PUT;
-                    if (BlobStoreRepository.INDEX_LATEST_BLOB.equals(blobName)) {
+                    if (BlobStoreRepository.INDEX_LATEST_BLOB.equals(blobName)
+                        || blobName.startsWith(BlobStoreRepository.METADATA_PREFIX)) {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepository.java]: On master fail-over, we can now have overwriting for meta- blobs here. Since any metadata will be at least as fresh as all the uploaded segments overwrites here should be.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 4]
```diff
@@ -392,24 +401,31 @@ protected void doRun() {
...
                 Repository repository = repositoriesService.repository(snapshot.snapshot().getRepository());
 
-                MetaData metaData = clusterState.metaData();
-                if (!snapshot.includeGlobalState()) {
-                    // Remove global state from the cluster state
-                    MetaData.Builder builder = MetaData.builder();
-                    for (IndexId index : snapshot.indices()) {
-                        builder.put(metaData.index(index.getName()), false);
+                if (clusterState.nodes().getMinNodeVersion().onOrAfter(NO_REPO_INITIALIZE_VERSION)) {
+                    final String snapshotName = snapshot.snapshot().getSnapshotId().getName();
```
Comment (andrershov) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Copy-paste of part of `initializeSnapshot` method. Either remove this code from `initializeSnapshot` and call it here for both cases or create `checkPreconditions` method.

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java [hunk 5]
```diff
@@ -928,7 +928,6 @@ public void testMasterAndDataShutdownDuringSnapshot() throws Exception {
         }
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/25281")
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: Can we have two separate PRs - for #41581 and #25281?

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 6]
```diff
@@ -2538,28 +2536,15 @@ public void testCloseOrDeleteIndexDuringSnapshot() throws Exception {
 
         Client client = client();
 
-        boolean allowPartial = randomBoolean();
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Why is that changed?

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotResiliencyTests.java [hunk 7]
```diff
@@ -493,6 +495,84 @@ public void run() {
...
+        TestClusterNode masterNode =
+            testClusterNodes.currentMaster(testClusterNodes.nodes.values().iterator().next().clusterService.state());
+
+        final StepListener<CreateSnapshotResponse> createSnapshotResponseStepListener = new StepListener<>();
+
+        continueOrDie(createRepoAndIndex(masterNode, repoName, index, shards), createIndexResponse -> {
+            final AtomicBoolean initiatedSnapshot = new AtomicBoolean(false);
+            for (int i = 0; i < documents; ++i) {
+                masterNode.client.bulk(
+                    new BulkRequest().add(new IndexRequest(index).source(Map.of("foo" + i, "bar", "num", i)))
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SnapshotResiliencyTests.java]: Let's get rid of "num" field here. It seems that it's not necessary and it will make the assertion below easier (no +1). I also think that this piece of code requires some comment.

**Review by andrershov — CHANGES_REQUESTED** [review]
@original-brownbear I left a couple of comments.

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 6 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: We can't block on the `initialize` part of the snapshot anymore, so I removed the code paths in this test that required blocking on `initialize`. `allowPartial == true` required blocking on init => all the paths that had it set to `true` were removed.

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotResiliencyTests.java (hunk 7 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SnapshotResiliencyTests.java]: Fair point, dropped it and added a comment

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: Sure, revered the related changes will open a follow up PR then

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Yea makes sense on second though -> removed the checks from `BlobStoreRepository`

**Comment by original-brownbear** [comment]
Jenkins test this
(some weirdness when resolving deps)

**Comment by original-brownbear** [comment]
Thanks @andrershov ! All fixed I think.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by andrershov — APPROVED** [review]
Thanks, @original-brownbear, LGTM!

**Comment by original-brownbear** [comment]
Thanks @andrershov !
