### PR TITLE
[ML] Add validation that rejects duplicate detectors in PutJobAction

### LINKED ISSUE #39704: [ML] Better handling for jobs which will may fail
Found in `8.0.0-SNAPSHOT`, expected in other versions.

Usability issue.

In Dev Tools, if I create a job with a duplicate detector, the call to open the job will succeed. However the job then subsequently becomes "failed". It is difficult for the end user to know anything is wrong unless they check the job state or try to start the datafeed (at which point the datafeed fails to start because the job is not open).

Note. The UI does not allow you to create a job with a duplicate detector, so this issue concerns Dev Tools and API.

```
PUT _ml/anomaly_detectors/fq2
{
  "analysis_config": {
    "bucket_span": "15m",
    "detectors": [
      { "function": "mean", "field_name": "responsetime" },
      { "function": "mean", "field_name": "responsetime" }
    ]
  },
  "data_description": {
    "time_field": "@timestamp"
  }
}
// succeeds


PUT _ml/datafeeds/datafeed-fq2
{
  "job_id": "fq2",
  "indices": [ "farequote-*" ]
}
// succeeds

POST _ml/anomaly_detectors/fq2/_open
// succeeds 
// { "opened" : true }

POST _ml/datafeeds/datafeed-fq2/_start
// fails
// reason": "cannot start datafeed [datafeed-fq2] because job [fq2] is failed"

```

Can validation checks be implemented when the job is `PUT`?
Or, can the call to `_open` fail?
And are there other similar reasons for the job to fail that could be caught earlier with more user feedback?

### PR DESCRIPTION
**Pull request by przemekwitek**
Closes #39704

### CODE REVIEW

**Review by benwtrent — COMMENTED** [review]
I think there should be an integration test (probably a yaml test) to test this fix.

Where the tests are located: https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/src/test/resources/rest-api-spec/test/ml

Probably added to the `jobs_crud.yml` file. 

Yaml README: https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/README.asciidoc

How to execute the ML yaml tests:
```
./gradlew :x-pack:plugin:integtest -Dtests.class=org.elasticsearch.xpack.test.rest.XPackRestIT -Dtests.method="test {p0=ml/*}"
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java [hunk 1]
```diff
@@ -147,6 +147,8 @@
     public static final String JOB_CONFIG_UPDATE_ANALYSIS_LIMITS_MODEL_MEMORY_LIMIT_CANNOT_BE_DECREASED =
             "Invalid update value for analysis_limits: model_memory_limit cannot be decreased below current usage; " +
                     "current usage [{0}], update had [{1}]";
+    public static final String JOB_CONFIG_DUPLICATE_DETECTORS_DISALLOWED =
+            "Specifying duplicate detectors is disallowed, {0}";
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java]: nit: Perhaps `Duplicate detectors are not allowed` would be simpler? It sounds a bit more natural to me.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/PutJobAction.java [hunk 2]
```diff
@@ -59,6 +59,10 @@ public static Request parseRequest(String jobId, XContentParser parser) {
         public Request(Job.Builder jobBuilder) {
             // Validate the jobBuilder immediately so that errors can be detected prior to transportation.
             jobBuilder.validateInputFields();
+            // Validate that detector configs are unique.
+            // This validation logically belongs to validateInputFields call but we perform it only for PUT action to avoid BWC issues which
+            // would occur when parsing an old job config that already had duplicate detectors.
+            jobBuilder.validateDetectorsAreUnique();
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/PutJobAction.java]: @droberts195 Since we now store the jobs out of the cluster state, could we move this validation in `build()`? Also, should we target this PR only against `8.0` as there still might be jobs in cluster state in `7.x` nodes?

**Review by dimitris-athanasiou — COMMENTED** [review]
Looks great! Left a few minor comments and a question.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/PutJobAction.java (hunk 2 above)
Comment (droberts195) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/PutJobAction.java]: I don't think we can ever move this validation inside `Job.Builder.build()`.  Once our configs are out of cluster state we won't break the whole cluster if we put the validation there, but we _will_ still break ML if people have jobs that don't conform to the new validation rules.  So the best we can do is to add validation that newly added jobs conform to the tighter rules.  This PR is basically implementing the idea of https://github.com/elastic/elasticsearch/issues/39704#issuecomment-470091066.

**Comment by droberts195** [comment]
As well as `PutJobAction` it would be good to also call the new validation method from `ValidateJobConfigAction`, and add a YAML test for that endpoint too.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/config/Job.java [hunk 3]
```diff
@@ -1067,6 +1067,21 @@ private void validateGroups() {
...
 
+        /**
+         * Validates that the Detector configs are unique up to detectorIndex field (which is ignored).
+         */
+        public void validateDetectorsAreUnique() {
+            Set<Detector> canonicalDetectors = new HashSet<>();
+            for (Detector detector : this.analysisConfig.getDetectors()) {
+                // While testing for equality, ignore detectorIndex field as this field is auto-generated.
+                Detector canonicalDetector = new Detector.Builder(detector).setDetectorIndex(0).build();
+                if (!canonicalDetectors.add(canonicalDetector)) {
```
[the remark this answers is not in the document]
Comment (przemekwitek) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/config/Job.java]: Done.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java]: Done. Also, please advise on the location of '{0}' placeholder.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java [hunk 4]
```diff
@@ -148,7 +148,7 @@
             "Invalid update value for analysis_limits: model_memory_limit cannot be decreased below current usage; " +
                     "current usage [{0}], update had [{1}]";
     public static final String JOB_CONFIG_DUPLICATE_DETECTORS_DISALLOWED =
-            "Specifying duplicate detectors is disallowed, {0}";
+            "Duplicate detectors are not allowed, see ''{0}''";
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java]: Hm, perhaps we can do `"Duplicate detectors are not allowed: [{0}]"`. We prefer putting expressions in square brackets though in `Messages` there are still some messages that don't do that as heritage from the prelert days.

Comment (przemekwitek) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/messages/Messages.java]: Done.

**Comment by przemekwitek** [comment]
> As well as `PutJobAction` it would be good to also call the new validation method from `ValidateJobConfigAction`, and add a YAML test for that endpoint too.

Done.

**Comment by przemekwitek** [comment]
> I think there should be an integration test (probably a yaml test) to test this fix.
> 
> Where the tests are located: https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/src/test/resources/rest-api-spec/test/ml
> 
> Probably added to the `jobs_crud.yml` file.
> 
> Yaml README: https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/README.asciidoc
> 
> How to execute the ML yaml tests:
> 
> ```
> ./gradlew :x-pack:plugin:integtest -Dtests.class=org.elasticsearch.xpack.test.rest.XPackRestIT -Dtests.method="test {p0=ml/*}"
> ```

Done.
One question regarding YML tests (@benwtrent, @droberts195, @dimitris-athanasiou): which versions of ES are they running against?
If I just merge this PR as it is, will some integration tests fail on CI? How do I prevent that?

**Comment by droberts195** [comment]
> One question regarding YML tests: which versions of ES are they running against?

The ones in the directory you changed run against the Elasticsearch built from the PR code.

(There are some others that run using a combination of the PR code and code from previous versions - those are under directories called `rolling-upgrade` or `full-cluster-restart`.)

**Comment by benwtrent** [comment]
@przemekwitek the yaml tests that are in the repo run against the same version of the code that is currently in the repo (it builds the cluster directly). 

The only tests (that I know of) where BWC is a concern are the rolling upgrade tests.

**Comment by dimitris-athanasiou** [comment]
@przemekwitek The ones you added run against the version of the branch. There is also the BWC suite of YML tests. If we assume the version of a branch is major.minor, then the BWC tests start with a cluster whose nodes run major-1.latest, then the nodes start being upgraded to major.minor, so we have a cluster with mixed versions, and finally the whole cluster is no major.minor.

**Comment by droberts195** [comment]
This PR is very close now.  The 4 failing tests in `elasticsearch-ci/2` are because of the way our security permissions tests work.  The ones with the ML user role and with no privileges at all expect tests to return permission denied errors.  But some validations for invalid configs are done before going through security.  We discussed this with the Elasticsearch security team at the time we first noticed this, and they were happy with this behaviour.  So for the 4 tests that are failing in the `ml-with-security` suite it's because instead of the permission denied error they're returning the validation error a user with a higher privilege level would get.  We cope with this by listing the tests that are like this in `x-pack/plugin/ml/qa/ml-with-security/build.gradle`.  So I think if you do this then you'll find the PR CI goes green.  (Click the `Details` link next to `elasticsearch-ci/2` to see the 4 failing tests.)

**Review by droberts195 — APPROVED** [review]
LGTM

But please wait until all the CI checks are green before merging.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM2
