### PR TITLE
Properly encode location header

### LINKED ISSUE #23115: Strange Exception in ElasticSearch Logs
**Elasticsearch version**: 5.2.0

**Plugins installed**: -

**JVM version**: Oracle JDK 1.8.0_121

**OS version**: Centos 6

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Add an entry with _id containing empty spaces. Sample id: **id with_empty_space** 

**Provide logs (if relevant)**:

```
[2017-02-10T17:53:08,876][WARN ][o.e.r.a.d.RestIndexAction] [TeY3Ao3] Location string is not a valid URI.
java.net.URISyntaxException: Illegal character in path at index 57: /testindex/testtype/id with_empty_space
	at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0_121]
	at java.net.URI$Parser.checkChars(URI.java:3021) ~[?:1.8.0_121]
	at java.net.URI$Parser.parseHierarchical(URI.java:3105) ~[?:1.8.0_121]
	at java.net.URI$Parser.parse(URI.java:3063) ~[?:1.8.0_121]
	at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_121]
	at org.elasticsearch.action.DocWriteResponse.getLocation(DocWriteResponse.java:201) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.rest.action.document.RestIndexAction.lambda$null$0(RestIndexAction.java:96) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.rest.action.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:65) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.rest.action.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:56) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.rest.action.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:33) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:91) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:87) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishOnSuccess(TransportReplicationAction.java:831) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:741) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:727) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1017) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1090) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1080) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1070) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:111) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$3.onResponse(TransportReplicationAction.java:353) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$3.onResponse(TransportReplicationAction.java:347) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryResult.respond(TransportReplicationAction.java:401) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.respondIfPossible(TransportWriteAction.java:137) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.respond(TransportWriteAction.java:128) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$2.onResponse(TransportReplicationAction.java:320) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$2.onResponse(TransportReplicationAction.java:317) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.ReplicationOperation.finish(ReplicationOperation.java:303) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.ReplicationOperation.decPendingAndFinishIfNeeded(ReplicationOperation.java:284) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:132) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:327) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:262) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:864) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:861) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:142) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1652) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:873) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:92) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:279) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:258) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:250) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) [elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.2.0.jar:5.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

### PR DESCRIPTION
**Pull request by jasontedor**
Today when trying to encode the location header to ASCII, we rely on the Java URI API. This API requires a proper URI which blows up whenever the URI contains, for example, a space (which can happen if the type, ID, or routing contain a space). This commit addresses this issue by properly encoding the URI. Additionally, we remove the need to create a URI simplifying the code flow.

Closes #23115, relates #21057

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/DocWriteResponse.java [hunk 1]
```diff
@@ -201,31 +204,43 @@ public RestStatus status() {
     }
 
     /**
-     * Gets the location of the written document as a string suitable for a {@code Location} header.
-     * @param routing any routing used in the request. If null the location doesn't include routing information.
+     * Return the relative URI for the location of the document suitable for use in the {@code Location} header. The use of relative URIs is
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/action/DocWriteResponse.java]: nit: can you cap this at 72 columns?

**Review by rjernst — APPROVED** [review]
LGTM

File: core/src/main/java/org/elasticsearch/action/DocWriteResponse.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/DocWriteResponse.java]: I think it's odd that we would have a 140 character limit on Java source code but only 72 characters on Javadocs (and comments?). If you feel strongly about this, I think that we should discuss it more broadly.

**Comment by jasontedor** [comment]
Thanks for reviewing @rjernst.
