### PR TITLE
Fix testTracerLog Network Tests

### LINKED ISSUE #41890: SimpleSecurityNetty4ServerTransportTests.testTracerLog is failing with appends to non-started mock appender
This just failed for `SimpleSecurityNetty4ServerTransportTests.testTracerLog`:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3437/

A slightly different error message this time:
```
Expected: an empty collection
     but: <[Attempted to append to non-started appender mock]>
	at __randomizedtesting.SeedInfo.seed([BC7BFAA89193A0EF:BFF80716909B0E3A]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:484)
	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:360)
```

Reproduce line is:
```
./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testTracerLog" -Dtests.seed=BC7BFAA89193A0EF -Dtests.security.manager=true -Dtests.locale=ta-MY -Dtests.timezone=Mexico/BajaSur -Dcompiler.java=12 -Druntime.java=11
```

Relates #40586

### PR DESCRIPTION
**Pull request by original-brownbear**
* Start appender before using it like we do for e.g. the Netty leak detection appender to avoid interference from actions on the network threads that might still be dangling from previous tests in the same suite
* Closes #41890

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

File: test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java [hunk 1]
```diff
@@ -1047,10 +1047,9 @@ public String executor() {
             .build());
 
         MockLogAppender appender = new MockLogAppender();
+        appender.start();
         Loggers.addAppender(LogManager.getLogger("org.elasticsearch.transport.TransportService.tracer"), appender);
```
Comment (jasontedor) [inline test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java]: Instead maybe to move this line into the try/finally after starting the appender?

**Review by jasontedor — APPROVED** [review]
I left a suggestion, I trust your judgment so no need for another round.

**Review by Tim-Brooks — APPROVED** [review]
LGTM

File: test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java [hunk 2]
```diff
@@ -1047,10 +1047,9 @@ public String executor() {
             .build());
 
         MockLogAppender appender = new MockLogAppender();
-        Loggers.addAppender(LogManager.getLogger("org.elasticsearch.transport.TransportService.tracer"), appender);
+        appender.start();
         try {
-            appender.start();
-
+            Loggers.addAppender(LogManager.getLogger("org.elasticsearch.transport.TransportService.tracer"), appender);
```
Comment (jasontedor) [inline test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java]: Sorry, to be clear, I meant keeping the `appender.start();` in the `try` as it was, and instead of moving it up out of the `try` before the `Loggers.addAppender`, instead move the `Loggers.addAppender` below the `appender.start();`, both in the `try`.

Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java]: fixed in 50df262 :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc
