### PR TITLE
[Test] Fix ClusterInfoServiceIT testMaxQueueLatenciesInClusterInfo

### LINKED ISSUE #132957: [CI] ClusterInfoServiceIT testMaxQueueLatenciesInClusterInfo failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10025 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/2rjuh6edqvxb4)
- [elasticsearch-pull-request #86036 / part-1](https://gradle-enterprise.elastic.co/s/vmkbzfqefrhli)
- [elasticsearch-periodic-platform-support #10025 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/lrmdnd7du6oz2)
- [elasticsearch-periodic-platform-support #10025 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/czmor4yywbvvs)
- [elasticsearch-pull-request #86008 / part-1](https://gradle-enterprise.elastic.co/s/7u24mc3p3iqgy)
- [elasticsearch-pull-request #86000 / part-1](https://gradle-enterprise.elastic.co/s/k2f4sswu67nja)

**Reproduction Line:**
```
gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.ClusterInfoServiceIT.testMaxQueueLatenciesInClusterInfo" -Dtests.seed=F5440B5D5A6B1B4C -Dtests.locale=kxv-Orya -Dtests.timezone=SystemV/MST7 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.ClusterInfoServiceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMaxQueueLatenciesInClusterInfo'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Unexpectedly found a task queued for the write thread pool. Write thread pool dump: TaskExecutionTimeTrackingEsThreadPoolExecutor[name = node_t1/write, queue capacity = 10000, task execution EWMA = 17.7ms, total task execution time = 1s, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@12a864d[Running, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 10]]
Expected: <0L>
     but: was <1L>
```

**Issue Reasons:**
- [main] 6 failures in test testMaxQueueLatenciesInClusterInfo (13.3% fail rate in 45 executions)
- [main] 3 failures in step part-1 (11.5% fail rate in 26 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (12.0% fail rate in 25 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Ensure async post replication actions (checkpoint syncs for the specific test) to complete before assertions.

Resolves: #132957

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java [hunk 1]
```diff
@@ -494,6 +494,30 @@ public void testMaxQueueLatenciesInClusterInfo() throws Exception {
             for (int i = 0; i < numberOfTasks; ++i) {
                 threadsToJoin[i].join();
             }
+            Arrays.stream(threadsToJoin).forEach(thread -> assertFalse(thread.isAlive()));
+
+            // Wait for async post replication actions to complete
+            final var checkpointsSyncLatch = new CountDownLatch(numShards);
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java:500]: Related to this [comment](https://github.com/elastic/elasticsearch/pull/132675#discussion_r2274902940) on the orignal PR. The `GlobalCheckpointSyncAction` runs even when there is no replica shards since it needs to update the primary's persisted global check point from the in-memory copy as well.

**Review by nicktindall — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch
