### PR TITLE
Don't fail delete index API if an index is deleted during the request

### LINKED ISSUE #137422: DELETE _all fails if an index is deleted during the request
### Elasticsearch Version

9.x, main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

**Current behaviour**

Request `DELETE /_all` might fail if another process deletes one of the resolved indices while it is running.

**Expected behaviour**

Request `DELETE /_all` should be resilient to another process deleting one of the resolved indices considering that the user did not specify which indices to delete.

### Steps to Reproduce

We saw this while debugging #136585 but it doesn't reproduce locally.

We believe a test that forces the following sequence of events should be able to reproduce this:
- Create 2 indices.
- Request for all indices to be deleted, but add a delay after [the index resolution](https://github.com/elastic/elasticsearch/blob/569c1fc1cde793d943b1161e915727ec48d6ae25/server/src/main/java/org/elasticsearch/action/admin/indices/delete/TransportDeleteIndexAction.java#L100).
- Take advantage of the delay and delete one of the two indices.
- The above will ensure that the delete index cluster update task will actually run on a new cluster state without one of the two indices. 
- Then when the cluster update will try to [resolve the project via the index name](https://github.com/elastic/elasticsearch/blob/f0f641086f0fdfb8506e2ab19f47e3c8505c436e/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java#L148) we get an `IndexNotFoundException`.

### Logs (if relevant)

```
[2025-10-30T20:45:58,426][ERROR][o.e.t.InternalTestCluster][node_t1][transport_worker][T#1] ---- initial wiping of indices failed
  org.elasticsearch.transport.RemoteTransportException: [node_t0][127.0.0.1:19841][indices:admin/delete]
  Caused by: org.elasticsearch.index.IndexNotFoundException: no such index [[tpspdlrtri/0KOiMkdbSDuzTk1Z_mx7Hw]] and index [[tpspdlrtri/0KOiMkdbSDuzTk1Z_mx7Hw]] does not exist in any project
   at org.elasticsearch.cluster.metadata.Metadata.lambda$projectFor$13(Metadata.java:1876) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
  at org.elasticsearch.cluster.metadata.Metadata.projectFor(Metadata.java:1875) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
        at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService.deleteIndices(MetadataDeleteIndexService.java:148) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService$1.executeTask(MetadataDeleteIndexService.java:67) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService$1.executeTask(MetadataDeleteIndexService.java:61) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.SimpleBatchedAckListenerTaskExecutor.execute(SimpleBatchedAckListenerTaskExecutor.java:64) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1100) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1063) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:246) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1710) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.action.ActionListener.run(ActionListener.java:465) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1707) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1308) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  	at org.elasticsearch.action.ActionListener.run(ActionListener.java:465) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1287) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
   	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1076) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.3.0-SNAPSHOT.jar:9.3.0-SNAPSHOT]
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[?:?]
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[?:?]
  	at java.lang.Thread.run(Thread.java:1474) ~[?:?]
```

### PR DESCRIPTION
**Pull request by nielsbauman**
In some cases, an index may have already been deleted by the time we process the deletion cluster state update task. In that case, we can simply skip it instead of throwing an exception. Index name resolution will have failed in the transport action (or in security) if the index never existed.

Closes #137422

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java [hunk 1]
```diff
@@ -145,8 +146,13 @@ public void onFailure(Exception e) {
     public static ClusterState deleteIndices(ClusterState clusterState, Set<Index> indices, Settings settings) {
         final Map<ProjectId, Set<Index>> byProject = new HashMap<>();
         for (Index index : indices) {
-            final ProjectMetadata project = clusterState.metadata().projectFor(index);
-            byProject.computeIfAbsent(project.id(), ignore -> new HashSet<>()).add(index);
+            final Optional<ProjectMetadata> project = clusterState.metadata().lookupProject(index);
+            // In some cases, the index may have already been deleted by the time we process the deletion task. In that case, we can simply
+            // skip it. Index name resolution will have failed in the transport action (or in security) if the index never existed.
```
Comment (PeteGillinElastic) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java]: I think that the scenario is specifically when there's a wildcard delete request, and something else deletes the index between expanding the wildcard and doing the deletes, right? Maybe we could be more explicit about this here, I don't think I'd have realized that from this comment (I only got it from Mary's bug report).

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java [hunk 2]
```diff
@@ -145,8 +146,13 @@ public void onFailure(Exception e) {
...
+            if (project.isEmpty()) {
+                continue;
+            }
+            byProject.computeIfAbsent(project.get().id(), ignore -> new HashSet<>()).add(index);
```
Comment (PeteGillinElastic) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java:157]: Optional (no pun intended): I'm undecided whether a one-liner is more readable, or less:
```java
project.map(ProjectMetadata::id).ifPresent(projectId -> byProject.computeIfAbsent(projectId, ignore -> new HashSet<>()).add(index));
```
WDYT?

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java
Comment (PeteGillinElastic) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java:162]: Thinking aloud: I was trying to figure out whether there's a small window in which the index could have been deleted between the check above and the deletion inside this method... I don't think there is, because that would have to be another cluster state update and those are serialized. The race condition only exists before the cluster state update starts. Does that sound right?

**Review by PeteGillinElastic — APPROVED** [review]
Thanks!

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java (hunk 1 above)
Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java]: I thought about including that, but I figured that it's technically also possible with two concurrent delete requests (with concrete index names) that both resolve the same indices and then both trigger a cluster state update. But I understand that the situation from the bug report isn't immediately obvious, so I'll add a comment suggesting that as an example.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java (hunk 2 above)
Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java:157]: I don't think I have a very strong opinion here either. I'm usually a fan of one-liners, but I kind of like the explicitness of the "skip" here.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java
Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java:162]: Yep, that's exactly right. If we're inside a cluster state update task, we can be sure that no other cluster state is being processed/created.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java (hunk 2 above)
Comment (PeteGillinElastic) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java:157]: The purist would say that using `Optional.get` guarded by an `ifPresent` check is an anti-pattern, and we should always use things like `ifPresent` or `orElse`. But I'm not sure I agree... I'm happy enough with what you have here.

Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java:157]: Yeah, I usually prefer to avoid any nested code blocks when I can, as I think that generally makes things easier to read (but it doesn't always apply).
