### PR TITLE
Fix SnapshotLifecycleServiceTests.testPolicyCRUD

### LINKED ISSUE #44997: SnapshotLifecycleServiceTests testPolicyCRUD Failure
Oh foo-1 why can't you be foo-2

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=33, name=Thread-4, state=RUNNABLE, group=TGRP-SnapshotLifecycleServiceTests]
	at __randomizedtesting.SeedInfo.seed([8A2CBE77ADFEBB1F:630A2E905817C3E]:0)
Caused by: java.lang.AssertionError: 
Expected: "foo-2"
     but: was "foo-1"
	at __randomizedtesting.SeedInfo.seed([8A2CBE77ADFEBB1F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.lambda$testPolicyCRUD$10(SnapshotLifecycleServiceTests.java:196)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/966/console
https://scans.gradle.com/s/wvtal77kwzovq

### PR DESCRIPTION
**Pull request by andreidan**
Resolves #44997

### CODE REVIEW

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleServiceTests.java [hunk 1]
```diff
@@ -206,13 +207,20 @@ public void testPolicyCRUD() throws Exception {
...
             });
             clock.fastForwardSeconds(1);
 
+            // Let's make sure the job got updated
+            // We don't simply assert that triggeredJobs has one element with value "foo-2" because of a race condition that can see the
+            // list containing <foo-2, foo-1>. This can happen because when we update the policy to version 2 (ie. to foo-2) we will
+            // cancel the existing policy (foo-1) without waiting for the thread executing foo-1 to actually interrupt
+            // (see org.elasticsearch.common.util.concurrent.FutureUtils#cancel) which means that foo-1 could actually get to be
+            // rescheduled and re-run before it is indeed cancelled.
+            assertBusy(() -> assertThat(triggeredJobs, contains("foo-2")));
```
Comment (dakrone) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleServiceTests.java]: This will eventually fail, the `contains` matcher requires exact matching; so it'll fail and complain with:

```
java.lang.AssertionError: 
Expected: iterable containing ["foo-2"]
     but: item 0: was "foo-1"
```

It should be changed to check that it has `"foo-2"`, but can have anything else also.

**Review by dakrone — CHANGES_REQUESTED** [review]
I believe the assert needs to change for this, otherwise this will periodically fail

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleServiceTests.java (hunk 1 above)
Comment (andreidan) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleServiceTests.java]: Ah, that's correct (and why it hadn't fail locally - `contains` is very much overloaded) 

Thanks @dakrone , I pushed a fix to use `hasItem`

**Review by dakrone — APPROVED** [review]
LGTM, thanks Andrei!
