### PR TITLE
Reject empty IDs

### LINKED ISSUE #24116: HTTP _bulk allows "_id": "" to set empty _id
Tested on master, 5.3, 5.2, 5.0, and 2.3:

```http
PUT /_bulk
{ "index": { "_index": "test", "_type": "type", "_id": "" } }
{ "doc": "1" }
{ "index": { "_index": "test", "_type": "type", "_id": "" } }
{ "doc": "2" }
{ "index": { "_index": "test", "_type": "type" } }
{ "doc": "3" }
```

This creates **two** documents:

```json
{
  "took": 439,
  "errors": false,
  "items": [
    {
      "index": {
        "_index": "test",
        "_type": "type",
        "_id": "",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_seq_no": 0,
        "created": true,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test",
        "_type": "type",
        "_id": "",
        "_version": 2,
        "result": "updated",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_seq_no": 1,
        "created": false,
        "status": 200
      }
    },
    {
      "index": {
        "_index": "test",
        "_type": "type",
        "_id": "AVttiPbjiL4QtkRlx6WB",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_seq_no": 0,
        "created": true,
        "status": 201
      }
    }
  ]
}
```

This should create 3 documents, all with flake IDs (like the third document here). It's a bug because you can't actually `GET` a document with an empty `_id`.

```http
GET /test/type/
```

spits out:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No endpoint or operation is available at [type]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No endpoint or operation is available at [type]"
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by jasontedor**
When indexing a document via the bulk API where IDs can be explicitly specified, we currently accept an empty ID. This is problematic because such a document can not be obtained via the get API. Instead, we should rejected these requets as accepting them could be a dangerous form of leniency. Additionally, we already have a way of specifying auto-generated IDs and that is to not explicitly specify an ID so we do not need a second way. This commit the individual requests where ID is specified but empty.

Closes #24116

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/index/IndexRequest.java [hunk 1]
```diff
@@ -499,6 +499,10 @@ public void process(@Nullable MappingMetaData mappingMd, String concreteIndex) {
             }
         }
 
+        if ("".equals(id)) {
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/action/index/IndexRequest.java]: Out of curious, should we do `Strings.hasText(id) == false` here, to disallow the id `" "` also?

**Review by dakrone — APPROVED** [review]
LGTM, left one comment

File: core/src/main/java/org/elasticsearch/action/index/IndexRequest.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/index/IndexRequest.java]: I don't think we should reject " ", it can be obtained via the get API (with escaping) and rejecting it would be a breaking change. On the indexing API we take care to return a properly-escaped location headed.

Comment (dakrone) [inline core/src/main/java/org/elasticsearch/action/index/IndexRequest.java]: Sounds good to me, I think it falls into the larger input validation category anyway

**Comment by jasontedor** [comment]
Thanks @dakrone.
