### PR TITLE
Merge multiple ignored source entires for the same field

### LINKED ISSUE #111694: Fallback synthetic source produces wrong results in presence of object arrays
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

Synthetic source produced via fallback mechanism is not correct when using `subobjects: false` and using object arrays.

### Steps to Reproduce

```
PUT /my_index
{
  "mappings": {
    "_source": { "mode": "synthetic" },
    "subobjects": false,
    "properties": {
      "obj": {
        "properties": {
          "k": {
              "type": "keyword",
              "doc_values": false
          }
        }
      }
    }
  }
}
```

```
PUT my_index/_doc/1
{
  "obj": [{"k": "key1"}, {"k": "key2"}]
}
```

```
GET /my_index/_doc/1

// Produces
"_source": {
    "obj.k": "key2"
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lkts**
This PR fixes an issue with producing synthetic source when fields that need to be synthesized using ignored source are indexed multiple times in one document. Previously multiple ignored source values were not handled and this PR introduces logic to merge them together into a single field value.

Closes #111694.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java [hunk 1]
```diff
@@ -441,7 +441,7 @@ public DocValuesLoader docValuesLoader(LeafReader leafReader, int[] docIdsInLeaf
 
         private List<Integer> collectChildren(int parentDoc, BitSet parentDocs, DocIdSetIterator childIt) throws IOException {
             assert parentDocs.get(parentDoc) : "wrong context, doc " + parentDoc + " is not a parent of " + nestedTypePath;
-            final int prevParentDoc = parentDocs.prevSetBit(parentDoc - 1);
+            final int prevParentDoc = parentDoc > 0 ? parentDocs.prevSetBit(parentDoc - 1) : -1;
```
Comment (lkts) [inline server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java:444]: This is a separate bug, stole the fix from #110524. Needs to be extracted into a separate PR. We hit it a lot in tests now.

Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java:444]: https://github.com/elastic/elasticsearch/pull/112005

Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java:444]: Wanna add a test for it? I can take on it in #110524, otherwise..

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 2]
```diff
@@ -893,6 +897,65 @@ public boolean setIgnoredValues(Map<String, List<IgnoredSourceFieldMapper.NameVa
...
+                public FieldWriter mergeWith(IgnoredSourceFieldMapper.NameValue merged) {
+                    var initialValues = new ArrayList<IgnoredSourceFieldMapper.NameValue>();
+                    initialValues.add(value);
+                    initialValues.add(merged);
+
+                    return new CompositeIgnoredSource(initialValues);
+                }
+            }
+
+            class CompositeIgnoredSource implements IgnoredSourceWriter {
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:931]: Nit: I wonder if the interface complexity above is justified, since this is used only within the scope of this class. I'd probably use just this class for now, and move to an interface if needed in the future..

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 3]
```diff
@@ -851,18 +849,24 @@ public void write(XContentBuilder b) throws IOException {
...
+                        orderedFields.put(value.name(), new FieldWriter.IgnoredSource(value));
+                    } else if (existing instanceof FieldWriter.IgnoredSourceWriter isw) {
+                        orderedFields.put(value.name(), isw.mergeWith(value));
+                    }
                 }
                 for (SourceLoader.SyntheticFieldLoader field : fields) {
                     if (field.hasValue()) {
                         // Skip if the field source is stored separately, to avoid double-printing.
-                        orderedFields.putIfAbsent(field.fieldName(), field::write);
+                        orderedFields.putIfAbsent(field.fieldName(), new FieldWriter.FieldLoader(field));
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:864]: This doesn't allow mixing some ignored values with regular values? E.g. what happens when we have an array with some malformed values?

Also, this keeps creating new FieldLoaders, even if they're not used. Use `computeIfAbsent` instead?

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java [hunk 4]
```diff
@@ -92,6 +94,54 @@ static void decodeAndWrite(XContentBuilder b, BytesRef r) throws IOException {
         }
     }
 
+    static void writeMerged(XContentBuilder b, String fieldName, Collection<BytesRef> encodedParts) throws IOException {
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:97]: Nit: add a short method comment.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 5]
```diff
@@ -851,18 +849,24 @@ public void write(XContentBuilder b) throws IOException {
...
+                    var existing = orderedFields.get(value.name());
+                    if (existing == null) {
+                        orderedFields.put(value.name(), new FieldWriter.IgnoredSource(value));
+                    } else if (existing instanceof FieldWriter.IgnoredSourceWriter isw) {
+                        orderedFields.put(value.name(), isw.mergeWith(value));
+                    }
                 }
                 for (SourceLoader.SyntheticFieldLoader field : fields) {
                     if (field.hasValue()) {
                         // Skip if the field source is stored separately, to avoid double-printing.
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:863]: Iirc the use case for this is when `store_array_source` is set. We can check for that and merge otherwise.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 3 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:864]: Yes, we don't merge (keeping the current behavior). Most of the time it is not correct to merge right now since it will result in duplicate values. If we wanted to merge we would need a clear signal on when it is legal to do so and i am not sure what that would be.

When we need to mix valid values with ignored ones we create a dedicated stored field to store ignored values. However we do use ignored source directly to handle `ignore_above` in `flattened` field. I think that use case is broken with arrays. I'll file an issue.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 5 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:863]: But we don't know which mapper produced this field loader at this point?

File: server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java (hunk 1 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java:444]: #112043

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 5 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:862]: In the current logic, the param would be set in the container `ObjectMapper` running this. So this could be:

```
if (field.hasValue()) {
  if (storeArraySource()) {
    // Skip if the field source is stored separately, to avoid double-printing.
    orderedFields.computeIfAbsent(field.fieldName(), k -> new FieldWriter.FieldLoader(field));
  } else {
   // Merge with existing values.. 
  } 
}
```

Would something like this work? We can look at the mixed case separately..

**Review by kkrik-es — APPROVED** [review]
I like where this is going. We can look at the mixed case separately.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 5 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:862]: As we discussed today i think we can defer handling mixed case for now.

**Comment by lkts** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/112116)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
