### PR TITLE
[ES|QL] Adding precondition for planning tests including score

### LINKED ISSUE #136920: [CI] LogicalPlanOptimizerTests testEvalWithScoreExplicitLimit failing
**Build Scans:**
- [elasticsearch-periodic #11337 / release-tests](https://gradle-enterprise.elastic.co/s/iehfpsqc44t4u)
- [elasticsearch-periodic #11333 / release-tests](https://gradle-enterprise.elastic.co/s/lmb5ua35fjv64)
- [elasticsearch-pull-request #99918 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/hh6pv5p5tojam)
- [elasticsearch-periodic #11325 / release-tests](https://gradle-enterprise.elastic.co/s/h5eegrhburw4i)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests.testEvalWithScoreExplicitLimit" -Dtests.seed=D7B06EE1BDC85BBD -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=pt-BR -Dtests.timezone=Etc/GMT-14 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.LogicalPlanOptimizerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testEvalWithScoreExplicitLimit'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.VerificationException: Found 1 problem
line 2:12: Unknown function [SCORE]
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 4 failures in test testEvalWithScoreExplicitLimit (2.5% fail rate in 163 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 3 failures in pipeline elasticsearch-periodic (75.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by pmpailis**
Adding precondition for tests including `SCORE` to exclude non-snapshot builds, as the function is under `SNAPSHOT` atm. 

Closes https://github.com/elastic/elasticsearch/issues/136920 and https://github.com/elastic/elasticsearch/issues/136921

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -211,6 +211,10 @@ public class LogicalPlanOptimizerTests extends AbstractLogicalPlanOptimizerTests
     private static final LiteralsOnTheRight LITERALS_ON_THE_RIGHT = new LiteralsOnTheRight();
 
     public void testEvalWithScoreImplicitLimit() {
+        assumeTrue(
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: We can just check the capability.
As an example:

https://github.com/elastic/elasticsearch/blob/a654efe6bf4139149af74c9b09260e50a6f4a283/x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java#L2031

but the capability we want to check here is SCORE_FUNCTION from:
https://github.com/elastic/elasticsearch/blob/6beabf4d4bec05486cae1cec950e22e918b4a278/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java#L1121

Comment (pmpailis) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: Thanks @ioanatia ! Updated in 8998eaf9c579e62a857ec59da6b7a6dda2f2a52c.

**Review by ioanatia — APPROVED** [review]
