### PR TITLE
Deprecate specifying credentials through env vars, sys props, and remove profile files

### LINKED ISSUE #21041: Can't use `~/.aws/credentials` file with discovery-ec2 plugin
**Elasticsearch version**: 5.0.0
**Plugins installed**: `discovery-ec2`

While I was working on #21039, I observed that loading key/secret from the default location `~/.aws/credentials` is not possible.

```
[2016-10-20T13:42:07,749][DEBUG][c.a.a.AWSCredentialsProviderChain] Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@bcbbaf: access denied ("java.io.FilePermission" "/home/ubuntu/.aws/credentials" "read")
```

I tried to work around this and added the following lines in `plugin-security.policy` file but it still does not work:

```
grant {
  // AWS ProfileCredentialsProvider needs read access to this dir ~/.aws/credentials
  permission java.io.FilePermission "~/.aws/credentials", "read";
};
```

I also tried with the following (just for testing purpose) and it is also failing:

```
grant {
  // AWS ProfileCredentialsProvider needs read access to this dir ~/.aws/credentials
  permission java.io.FilePermission "/home/ubuntu/.aws/credentials", "read";
};
```

I wrap the code with:

``` java
            SecurityManager sm = System.getSecurityManager();
            if (sm != null) {
                // unprivileged code such as scripts do not have SpecialPermission
                sm.checkPermission(new SpecialPermission());
            }
            descInstances = AccessController.doPrivileged(new PrivilegedAction<DescribeInstancesResult>() {
                @Override
                public DescribeInstancesResult run() {
                    return client.describeInstances(buildDescribeInstancesRequest());
                }
            });
```

I'm unsure if this is supposed to work or if we simply can't support this authentification method anymore.

### PR DESCRIPTION
**Pull request by rjernst**
This is a follow up to #22479, where storing credentials secure way was
added.

closes #21041

### CODE REVIEW

**Comment by rjernst** [comment]
I'm not sure how to test this, since before we didn't have tests, and all of these methods rely on sys props or env vars. I've considered having special test tasks for each one of these within the repository-s3 plugin. It might work, it would just mean adding some test classes as excluded in the normal test run. Thoughts?

**Comment by dadoonet** [comment]
I think your change will also "fix" somehow what we discussed in #21041.
Can you do it as well for ec2 discovery? 

I know that we have infra tests that probably needs to be modified if we do that for ec2 as well.

**Comment by rjernst** [comment]
@dadoonet Yes I will do it for ec2 as well, but in a followup (I still need to convert ec2 to the new secure setting infra). And I want to get #22520 worked out before doing that (which will further simplify the settings we support for 6.0, and should also be done with ec2).

**Comment by rjernst** [comment]
Ok I added tests as I described above, and this actually caught a bug in my new implementation (the aws providers all throw exception if they are not found, and the default chain handles this by wrapping in try/catch).

**Comment by rjernst** [comment]
Given #21041, which I had forgot about, I removed profile file support entirely in this change (it didn't work with the security manager).

**Comment by rjernst** [comment]
retest this please

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java [hunk 1]
```diff
@@ -126,17 +133,30 @@ public static ClientConfiguration buildConfiguration(Logger logger, Settings set
...
+                if (envCredentials != null) {
+                    credentials = new StaticCredentialsProvider(envCredentials);
+                } else {
+                    AWSCredentials syspropCredentials = getDeprecatedCredentials(logger, deprecationLogger,
+                        new SystemPropertiesCredentialsProvider(), "system properties");
+                    if (syspropCredentials != null) {
+                        credentials = new StaticCredentialsProvider(syspropCredentials);
+                    } else {
+                        logger.debug("Using instance profile credentials");
+                        credentials = new InstanceProfileCredentialsProvider();
```
Comment (dadoonet) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: I think that using instance profile is a good thing actually and I have seen many people relying on that.
Basically credentials are only stored on AWS platform. Elasticsearch does not need to know them explicitly. So no one has to enter any access_key/secret_key either on `elasticsearch.yml` (in clear - which is not secured) or in elasticsearch keystore.

I'd not remove that option, at least, without speaking to the community/users.

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java [hunk 2]
```diff
@@ -126,17 +133,30 @@ public static ClientConfiguration buildConfiguration(Logger logger, Settings set
...
+                    }
+                }
             } else {
                 logger.debug("Using basic key/secret credentials");
                 credentials = new StaticCredentialsProvider(new BasicAWSCredentials(key.toString(), secret.toString()));
```
Comment (dadoonet) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: With what I just said, I'd use here a ProviderChain with:

* `StaticCredentialsProvider`
* `InstanceProfileCredentialsProvider`

**Review by dadoonet — COMMENTED** [review]
I left one comment

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 1 above)
Comment (rjernst) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: I did not deprecate instance profile. Notice it is different from the rest.

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 2 above)
Comment (rjernst) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: I don't see a reason to use a provider chain. We select exactly one set of credentials we are planning to use. I don't like having fallbacks (which a provider chain does, with its nasty blanket try/catch) when there are errors.

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 1 above)
Comment (dadoonet) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: But if we run your code without setting any key/secret in `elasticsearch.yml` (or in the vault), then we will print the deprecated notice you wrote in `getDeprecatedCredentials`, right?

I mean that when you are using instance profile, you don't have to add any key/secret as it is automatically provided by AWS platform.

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 2 above)
Comment (dadoonet) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: In that case you need to test if the user provided a key/secret pair, in that case use a `StaticCredentialsProvider`. If not, use a `InstanceProfileCredentialsProvider`. This is what a chain is doing behind the scene but I agree that you can write that part of the code yourself if you wish.

**Comment by rjernst** [comment]
@dadoonet Any more thoughts here?

**Comment by dadoonet** [comment]
@rjernst I added a comment on the issue yesterday: https://github.com/elastic/elasticsearch/pull/22567#discussion_r96577087

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 1 above)
Comment (rjernst) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: No, if it is using instance profile creds, no deprecation warning is given. Instance profile provider is not using getDeprecatedCredentials.

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 2 above)
Comment (rjernst) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: What is there works, there are new tests that prove this.  A provider chain would only obfuscate what is really happening. As it is now, it is very clear which methods are deprecated (env vars and sys props) and which are supported (instance profile). We check if env vars and sys props exist up front, instead of lazily like the provider chain would.

File: plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java (hunk 1 above)
Comment (dadoonet) [inline plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java]: I see. I misread the code.

**Review by dadoonet — APPROVED** [review]
LGTM
