### PR TITLE
SQL: Fix column size for IP data type

### LINKED ISSUE #52762: SQL: IP type reported to have column size of 0
The `IP` type is currently reported to have the column size (i.e. older "precision") of 0. This is reported in `SYS TYPES`.
This value is passed to the client applications and older ones use it as-is to allocate buffers to have the values returned in; which results in them getting just a string null-terminator only for the IP fields (i.e. empty string).

The value should contain the maximum length of an IP address in characters (as the type is backed by a KEYWORD).

(Collaterally, the `DataType`.`size` for `IP` value should be corrected from current 39 to 45.)

### PR DESCRIPTION
**Pull request by matriv**
Set size/displaySize to `45` which is the maximum string for
an IP (v6), since IPs are returned as strings.

Fixes: #52762

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/SqlDataTypes.java [hunk 1]
```diff
@@ -462,7 +462,7 @@ public static int defaultPrecision(DataType dataType) {
             return 3;
         }
         if (dataType == IP) {
-            return 39;
+            return 45;
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/SqlDataTypes.java]: `DataType.size()` could be potentially returned since it's the same value.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/SqlDataTypes.java [hunk 2]
```diff
@@ -582,7 +582,7 @@ public static int displaySize(DataType dataType) {
             return 29;
         }
         if (dataType == IP) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/SqlDataTypes.java]: `DataType.size()` could be potentially returned since it's the same value.

In fact, maybe this approach could be used for other DataTypes as well if applicable - that is whenever size == displaySize

**Review by costin — APPROVED** [review]
LGTM

**Comment by costin** [comment]
No need to backport all the way to 6.x

**Review by bpintea — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM
