### PR TITLE
[ESQL] Migrate SimplifyComparisonArithmetics optimization

### LINKED ISSUE #108388: [ESQL] Class cast exception mixing division and comparison
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

`FROM test | EVAL x = double / 2 > 4` results in a `ClassCastException`:

```
        "reason": "class org.elasticsearch.compute.data.DoubleVectorBlock cannot be cast to class org.elasticsearch.compute.data.IntBlock (org.elasticsearch.compute.data.DoubleVectorBlock and org.elasticsearch.compute.data.IntBlock are in unnamed module of loader java.net.FactoryURLClassLoader @45e11627)"
```

This seems to only happen when both division and comparison are involved.  Neither `FROM test | EVAL x = double / 2` and `FROM test | EVAL x = double > 4` trigger the error.

### Steps to Reproduce

```
PUT http://localhost:9200/test
content-type: application/json

{
  "mappings": {
    "properties": {
        "float": {"type": "float"},
        "int": {"type": "integer"},
        "double": {"type": "double"}
    }
  }
}


POST http://localhost:9200/_query?format=txt
content-type: application/json

{
  "version": "2024.04.01",
  "query": "FROM test | EVAL x = double / 2 > 4" 
}
```

### Logs (if relevant)

_No response_

### LINKED ISSUE #108743: [ESQL] SimplifyComparisonArithmetics not being correctly applied
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

The `SimplifyComparisonArithmetics` optimization rule isn't being applied everywhere we expect.  We see this as test failures for cases that should be optimized by this rule.  There are several related issues, this one is about failures related to using the QL `Neg` and `Sub` classes, instead of the ES|QL versions, in the mentioned optimization.

### Steps to Reproduce

Run the SQL tests (soon to be ported to ES|QL)

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by not-napoleon**
This pulls the SimplifyComparisonArithmetics optimization into ESQL proper, from core, and in doing so resolves two of the issues we uncovered with that optimization.  

Rather than moving this into a sub-class of `OptimzierRules`, I've opted to create a new package `optimizer.rules`, and put this as a top level class there. I have another PR open that migrates a bunch of other rules into `OptimizerRules`, and that's in general an area of the code that's being touched a lot lately.  Having top level classes in a package, rather than sub-classes in a single class file, will create fewer conflicts while working on things that are actually unrelated in this type of situation.

Although this is a bugfix, I did not mark it for backporting to 8.14.  To my knowledge, no users have reported the associated bugs (we found them through migrating tests), and this fix depends on tests and refactorings that were not backported to 8.14.  It would be possible to write an 8.14 version of this, but IMHO it's easier to do as a fresh ticket than as a backport and conflict resolution process. If we think that's important, I'm happy to do so, but at the moment I think fixing it for 8.15 is fine.

Note that this is a re-application of the changes in https://github.com/elastic/elasticsearch/pull/108200 after we did other refactoring, which that was closed to enable.

Resolves https://github.com/elastic/elasticsearch/issues/108388
Resolves https://github.com/elastic/elasticsearch/issues/108743

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/SimplifyComparisonsArithmetics.java [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+
+import org.elasticsearch.xpack.esql.core.expression.Expression;
+import org.elasticsearch.xpack.esql.core.expression.Literal;
+import org.elasticsearch.xpack.esql.core.expression.predicate.operator.arithmetic.ArithmeticOperation;
+import org.elasticsearch.xpack.esql.core.expression.predicate.operator.arithmetic.BinaryComparisonInversible;
+import org.elasticsearch.xpack.esql.core.expression.predicate.operator.comparison.BinaryComparison;
+import org.elasticsearch.xpack.esql.core.type.DataType;
+import org.elasticsearch.xpack.esql.core.type.DataTypes;
+import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Neg;
+import org.elasticsearch.xpack.esql.expression.predicate.operator.arithmetic.Sub;
```
Comment (not-napoleon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/SimplifyComparisonsArithmetics.java:18]: Changing the `Neg` and `Sub` imports to point to the esql version, instead of the esql-core versions, resolves https://github.com/elastic/elasticsearch/issues/108743

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/SimplifyComparisonsArithmetics.java [hunk 2]
```diff
@@ -0,0 +1,244 @@
...
+                return true;
+            }
+
+            return isOpUnsafe();
+        }
+
+        final Expression apply() {
+            // force float point folding for FlP field
+            Literal bcl = operation.dataType().isRational()
+                ? new Literal(bcLiteral.source(), ((Number) bcLiteral.value()).doubleValue(), DataTypes.DOUBLE)
```
Comment (not-napoleon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/SimplifyComparisonsArithmetics.java:151]: Changing this to use `new Literal` instead of `Literal.of` resolves https://github.com/elastic/elasticsearch/issues/108388

**Review by astefan — APPROVED** [review]
LGTM
