### PR TITLE
Fix Int7uScorerBenchmarkTests for running on Java 21

### LINKED ISSUE #130656: [CI] Int7uScorerBenchmarkTests class failing
**Build Scans:**
- [elasticsearch-periodic #9230 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/xcmirxc3xjazm)
- [elasticsearch-periodic #9230 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/tnu22umg6wlko)
- [elasticsearch-periodic #9223 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/eaancxvk4crlg)
- [elasticsearch-periodic #9223 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/hzwmmqnaykgwg)
- [elasticsearch-periodic #9216 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/w6a7f3ngwkvfe)
- [elasticsearch-periodic #9216 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/l6eptfieggmri)
- [elasticsearch-periodic #9209 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/smorrzadmncdq)
- [elasticsearch-periodic #9209 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/wr2wqa3gbhu5k)
- [elasticsearch-periodic #9200 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/3ftf4adqg244u)
- [elasticsearch-periodic #9200 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/a26um3pbevgfu)

**Reproduction Line:**
```
./gradlew ":benchmarks:test" --tests "org.elasticsearch.benchmark.vector.Int7uScorerBenchmarkTests.testSquareDistance {p0=96}" -Dtests.seed=45473B1425719DF9 -Dtests.locale=es-PE -Dtests.timezone=Europe/Vaduz -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.benchmark.vector.Int7uScorerBenchmarkTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.benchmark.vector.Int7uScorerBenchmarkTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.util.NoSuchElementException: No value present
```

**Issue Reasons:**
- [main] 2 consecutive failures in class org.elasticsearch.benchmark.vector.Int7uScorerBenchmarkTests
- [main] 12 consecutive failures in step openjdk21_checkpart1_java-fips-matrix
- [main] 12 consecutive failures in step openjdk21_checkpart1_java-matrix
- [main] 25 failures in class org.elasticsearch.benchmark.vector.Int7uScorerBenchmarkTests (4.5% fail rate in 551 executions)
- [main] 12 failures in step openjdk21_checkpart1_java-fips-matrix (100.0% fail rate in 12 executions)
- [main] 12 failures in step openjdk21_checkpart1_java-matrix (100.0% fail rate in 12 executions)
- [main] 12 failures in pipeline elasticsearch-periodic (100.0% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit fixes the Int7uScorerBenchmarkTests for running on Java 21, since scoring with heap segments is only supported on Java 22 and greater.

closes #130656

### CODE REVIEW

File: benchmarks/src/main/java/org/elasticsearch/benchmark/vector/Int7uScorerBenchmark.java [hunk 1]
```diff
@@ -134,10 +134,13 @@ public void setup() throws IOException {
...
-        nativeDotScorerQuery = factory.getInt7SQVectorScorer(VectorSimilarityFunction.DOT_PRODUCT, values, queryVec).get();
-        luceneSqrScorerQuery = luceneScorer(values, VectorSimilarityFunction.EUCLIDEAN, queryVec);
-        nativeSqrScorerQuery = factory.getInt7SQVectorScorer(VectorSimilarityFunction.EUCLIDEAN, values, queryVec).get();
+
+        if (Runtime.version().feature() >= 22) {
+            luceneDotScorerQuery = luceneScorer(values, VectorSimilarityFunction.DOT_PRODUCT, queryVec);
+            nativeDotScorerQuery = factory.getInt7SQVectorScorer(VectorSimilarityFunction.DOT_PRODUCT, values, queryVec).get();
+            luceneSqrScorerQuery = luceneScorer(values, VectorSimilarityFunction.EUCLIDEAN, queryVec);
+            nativeSqrScorerQuery = factory.getInt7SQVectorScorer(VectorSimilarityFunction.EUCLIDEAN, values, queryVec).get();
+        }
```
Comment (benwtrent) [inline benchmarks/src/main/java/org/elasticsearch/benchmark/vector/Int7uScorerBenchmark.java]: Do we need to do NPE checks in the benchmark methods now?

Comment (ChrisHegarty) [reply benchmarks/src/main/java/org/elasticsearch/benchmark/vector/Int7uScorerBenchmark.java]: Yeah, this could happen. In reality we'd be running with >= Java 22 as you cannot run that part of the bench without it.  I mostly just want to make the test happy. Lemme see if there is a cleaner way to restructure things.

**Review by benwtrent — APPROVED** [review]
