### PR TITLE
SQL: Enhance Verifier to prevent aggregate or grouping functions from

### LINKED ISSUE #36798: SQL: Prevent incompatible filtering
The verifier should prevent WHERE clause to contain aggregate or grouping functions. Currently this check is not in place causing incorrect queries to be processed.

### PR DESCRIPTION
**Pull request by costin**
Enhance Verifier to prevent aggregate or grouping functions from
 being used in a WHERE clause.

Fix #36798

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java [hunk 1]
```diff
@@ -542,6 +543,26 @@ private static boolean checkGroupMatch(Expression e, Node<?> source, List<Expres
         return false;
     }
 
+    private static void checkFilterOnAggs(LogicalPlan p, Set<Failure> localFailures) {
+        if (p instanceof Filter) {
+            Filter filter = (Filter) p;
+            if ((filter.child() instanceof Aggregate) == false) {
+                filter.condition().forEachDown(f -> {
+                    if (Functions.isAggregate(f)) {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: Maybe combine these two conditions into one similar with  `if (Functions.isAggregate(f) || Functions.isGrouping(f)) { localFailures.add(fail(f, "Cannot use WHERE filtering on " + Functions.isAggregate(f) ? "aggregate" : "grouping" + "function [%s], use HAVING instead", Expressions.name(f)));` ?

**Review by astefan — APPROVED** [review]
LGTM. Left one comment.

**Review by matriv — APPROVED** [review]
LGTM. Since you're "there", maybe add one more test to check the plural in the error message: https://github.com/elastic/elasticsearch/pull/36799/files#diff-65f5bc15cbaeeee27b9a9329b802d39fR372
