### PR TITLE
Fix CancellableRateLimitedFluxIteratorTests, fix potential race condition

### LINKED ISSUE #141893: [CI] CancellableRateLimitedFluxIteratorTests testErrorPath failing
**Build Scans:**
- [elasticsearch-intake #34218 / part1](https://gradle-enterprise.elastic.co/s/okmvxmyueswsq)
- [elasticsearch-pull-request #118766 / part-1](https://gradle-enterprise.elastic.co/s/uqyvafmkgsnce)
- [elasticsearch-intake #33993 / part1](https://gradle-enterprise.elastic.co/s/hpudz4f4ij7as)

**Reproduction Line:**
```
./gradlew ":modules:repository-azure:test" --tests "org.elasticsearch.repositories.azure.CancellableRateLimitedFluxIteratorTests.testErrorPath" -Dtests.seed=9A0C0717CC4075AB -Dtests.locale=no-NO -Dtests.timezone=Europe/Volgograd -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.azure.CancellableRateLimitedFluxIteratorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testErrorPath'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <[2]>
     but: was <[2]>
```

**Issue Reasons:**
- [main] 3 failures in test testErrorPath (0.4% fail rate in 818 executions)
- [main] 2 failures in step part1 (1.4% fail rate in 145 executions)
- [main] 2 failures in pipeline elasticsearch-intake (1.4% fail rate in 145 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
This PR fixes a test issue, and a potential race condition that could occur when there is an error or a cancellation.

Before #141323, on an error we would
1. Set done to true
2. Clear the queue
3. Set the error

If a consumer called next between 1 and 3 it was possible the consumer would think it had reached the end of the queue because it didn't observe the error,

The fix for that was setting done and error atomically by combining them into a `DoneState` record. I think this still leaves the possibility for a race with the following interleaving:

1. Consumer calls next, sees done = false
2. Producer calls `onError`, sets done = true with error = e OR someone calls `cancel` and sets done = true, error = null
3. Producer pulls one or more items off the queue and cleans them
4. Consumer pulls its item off the queue and consumes it (NOTE: it has read non-contiguous items here)

In this PR I 

- Added a check after the consumer polls an item to ensure we're still not done, if we are, we clean and throw away the item we just polled as there is a possibility it's not the actual next item we should be consuming. 
- Made a cancelled iterator throw an exception if someone reads from it after it was cancelled, this seems more appropriate than quietly returning nothing as it was doing, it also makes the above check easier because cancelled becomes just another error state.
- Included the check that item 2 was cleaned into the `assertBusy` in `testErrorPath` as it's possible to see an error thrown from `hasNext`, but for the queue to not be drained yet, that was what caused the test failure. Because since #141323 we started throwing errors before the queue was drained but before that we'd drain the queue before we threw an error.
- In the case where `hasNext` returns true, but the queue is empty, we now set `doneState` to an error before we `cancelSubscriber` and clean up, that will make that failure state permanent. This is minor but just changed for consistency.

All of the above could be made safer if we added some locking into this class, but I'm hesitant to add more synchronization unless we really need to incase it impacts performance by adding contention to the reactive thread(s).

I believe the race condition I fixed existed through all this.

Fixes #141893

### CODE REVIEW

**Comment by nicktindall** [comment]
Not ready for review yet @ywangd

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java [hunk 1]
```diff
@@ -129,15 +130,22 @@ public T next() {
...
+                cleanElement(nextElement);
             }
+            throw new RuntimeException(doneState.error());
+        } else if (nextElement == null) {
+            final var illegalStateException = new IllegalStateException(
+                "Queue is empty: Expected one element to be available from the Reactive Streams source."
+            );
+            doneState = new DoneState(true, illegalStateException);
+            cancelSubscription();
+            clearQueue();
```
Comment (ywangd) [inline modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java]: Is this necessary? The queue is already empty since some other process cleared it?

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java [hunk 2]
```diff
@@ -129,15 +130,22 @@ public T next() {
...
+            // as we may have begun clearing the queue
+            if (nextElement != null) {
+                cleanElement(nextElement);
             }
+            throw new RuntimeException(doneState.error());
+        } else if (nextElement == null) {
+            final var illegalStateException = new IllegalStateException(
+                "Queue is empty: Expected one element to be available from the Reactive Streams source."
+            );
+            doneState = new DoneState(true, illegalStateException);
```
Comment (ywangd) [inline modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java:144]: There could be races setting the `doneState`. It is likely some other process, e.g. cancel or onError, has set it to something else. It's possible for cancel racing with either onError or onComplete. The latter is not new. I guess it's probably OK when changing `doneState` from one error to another since we don't really care about actual error types. But it seems suspicous for `onComplete` to set it to `FINISHED` if it has just been set to cancelled and started to clear the queue? Is this scenario possible? If so, seems to be an existing issue and I can see it being a separate fix.

**Review by ywangd — APPROVED** [review]
LGTM

I have a question about another potential issue. But it can be addressed separately. At leats this PR should overall improve things even if it does not fix everything.

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java (hunk 1 above)
Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java]: Yeah probably not, I think the contract (see javadoc of `org.reactivestreams.Subscriber`) is that the producer calls `onNext`, `onError` and `onComplete` sequentially, I will remove this.

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java (hunk 2 above)
Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java:144]: Yeah you're right. The "cancel" `doneState` and the state above are really "synthetic" done states, because they're the result of something not initiated by the producer (like `onError`, `onComplete`). Do you think it makes sense to use an atomic to hold `doneState`, and a `updateAndGet` that allows "real" done-states override "synthetic" ones but not the other way around?

EDIT: just for `onError` really, we don't want `onComplete` to override any errors ever

Comment (ywangd) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java:144]: Yeah compare and swap might be necessary here. We can have it as a separate fix.

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java (hunk 1 above)
Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java]: Removed in 286699f67510208a0f655a5a4cc7134964879b6e

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java (hunk 2 above)
Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/CancellableRateLimitedFluxIterator.java:144]: I will do a separate PR because this one's getting a bit busy
