### PR TITLE
Relax Assertion About SnapshotsService Listeners

### LINKED ISSUE #56607: [CI] Various Failures in ILM/SLM Documentation Tests due to Tripped Assertion
This assertion tripped in a test, killing the test cluster:

```
» ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [asyncIntegTest-0] fatal error in thread [elasticsearch[asyncIntegTest-0][clusterApplierService#updateTask][T#1]], exiting
»  java.lang.AssertionError: Saw completion listeners for unknown snapshots in [my_repository:name-dg6og6ettfcu6rtlzn_amq/E_e_9y05QKO7FMBMCk186g] but running snapshots are [my_repository:name-_vgex2vhsburffvu4lbv5w/S7pl54NLQv6Z8K3YpLu8QA]
»  	at org.elasticsearch.snapshots.SnapshotsService.assertConsistentWithClusterState(SnapshotsService.java:436) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.snapshots.SnapshotsService.applyClusterState(SnapshotsService.java:427) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:511) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:508) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:485) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:432) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:176) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:632) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
»  	at java.lang.Thread.run(Thread.java:834) [?:?]
```

https://gradle-enterprise.elastic.co/s/k2pzddoemauck/console-log/raw

I'm on it. This looks like a legitimate bug that should only affect master as far as I can tell.

### PR DESCRIPTION
**Pull request by original-brownbear**
This assertion is too strict. A snapshot will be removed from the cluster state
on the CS thread before it is removed from the listeners map on the snapshot thread pool.
Throughout the removal from the cluster state and listener map, the snapshot is tracked
in `endingSnapshots` though, so we can relax the assertion accordingly and are still able
to catch leaked listeners.

Closes #56607

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -430,11 +431,15 @@ public void applyClusterState(ClusterChangedEvent event) {
     private boolean assertConsistentWithClusterState(ClusterState state) {
         final SnapshotsInProgress snapshotsInProgress = state.custom(SnapshotsInProgress.TYPE);
         if (snapshotsInProgress != null && snapshotsInProgress.entries().isEmpty() == false) {
-            final Set<Snapshot> runningSnapshots =
-                snapshotsInProgress.entries().stream().map(SnapshotsInProgress.Entry::snapshot).collect(Collectors.toSet());
-            final Set<Snapshot> snapshotListenerKeys = snapshotCompletionListeners.keySet();
-            assert runningSnapshots.containsAll(snapshotListenerKeys) : "Saw completion listeners for unknown snapshots in "
-                + snapshotListenerKeys + " but running snapshots are " + runningSnapshots;
+            synchronized (endingSnapshots) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:434]: The synchronization here isn't 100% necessary, could as well just copy the map before checking the listener key-set, but I figured the logic is a little easier to follow if we prevent concurrently starting another snapshot finalization.

**Comment by original-brownbear** [comment]
Sorry still WIP, this just failed a suspicious test

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/1 (slow mock WindowsFS run)

nevermind ... just a conincidence

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tanguy!
