### PR TITLE
SQL: Use ResultSets over exceptions in metadata

### LINKED ISSUE #40533: SQL: Consider replacing exception with empty result sets in JDBC metadata
Currently the `JdbcDatabaseMetaData` throws a `SQLFeatureNotSupportedException` for methods that are unsupported (such as `getVersionColumns`).
However these methods also return a `ResultSet` hence it is worth investigating whether returning an empty result set (with the appropriate column) is a better alternative as some clients might be able to handle them better (potentially eliminating existing warning inside the UI or logs).

### PR DESCRIPTION
**Pull request by costin**
Changed the JDBC metadata to return empty results sets instead of
throwing SQLFeatureNotSupported as it seems a more safer/compatible
approach for consumers.

Fix #40533

It's a follow-up to https://github.com/elastic/elasticsearch/pull/40583 hence only the latest commit is the one that counts.

### CODE REVIEW

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClient.java [hunk 1]
```diff
@@ -30,17 +30,23 @@
 class JdbcHttpClient {
     private final HttpClient httpClient;
     private final JdbcConfiguration conCfg;
-    private final InfoResponse serverInfo;
+    private InfoResponse serverInfo;
```
Comment (matriv) [inline x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClient.java]: It can still be final if there is an `else { serverInfo = null }`  in the ctor.

**Review by matriv — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClient.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClient.java]: But then [this](https://github.com/elastic/elasticsearch/pull/40641/files/ff6fcfc1116985637ae73b45b677bf9914cab19a..12826537874ae3007e70263ee170f161ab2e0f6c#diff-b2c6208433c105ca91e765533b2c82fcR87) won't work.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Since https://github.com/elastic/elasticsearch/pull/40583 has a discussion around it, I've rebased the latest commit to be able to merge this.
