### PR TITLE
Fix Source filtering in new field collapsing feature

### LINKED ISSUE #24063: Source filtering in new field collapsing feature (Elasticsearch 5.3)
Hi.

While trying out the new 'field collapsing' feature in ES 5.3, I noticed that source filtering is handled differently than when source filtering is applied inside the top query element. I created a gist to show off an example:

https://gist.github.com/byronvoorbach/bc3d73c77aaa7ddaa96ee47a9ba886fc

In short: 'collapse' feature needs an explicit include/exclude during source filtering where as this not needed when using source filtering on top level documents

### PR DESCRIPTION
**Pull request by byronvoorbach**
Added 'OBJECT_ARRAY_BOOLEAN_OR_STRING' to the ObjectParser.ValueType enum to be in line with the current configuration for source filtering in the request body. Updated InnerHitBuilder to use the new enum type. InnerHitBuilder now supports Object, Array, String or Boolean values for _source filtering

Closes https://github.com/elastic/elasticsearch/issues/24063

### CODE REVIEW

**Comment by karmi** [comment]
Hi @byronvoorbach, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/24068.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by byronvoorbach** [comment]
Whoops, that's what you get when working with multiple pc's... Added the other mail address!

**Comment by olcbean** [comment]
@byronvoorbach Thank you for contributing 😃 
Could you elaborate what problem this PR is fixing?

**Comment by nik9000** [comment]
Thanks for fixing your email @byronvoorbach. More administrative stuff:
1. Can you change the PR's title to make it clear what you changed? Most of us use email to decide what to review and without a description of what is changed or fixed we aren't likely to pick the PR to review.
2. Can you add a description? Sort of for the same reason as the above point. If you add `Closes #24063` then we'll get the nice automation when we merge the fix.

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java [hunk 1]
```diff
@@ -101,7 +101,7 @@
             } catch (IOException e) {
                 throw new ParsingException(p.getTokenLocation(), "Could not parse inner _source definition", e);
             }
-        }, SearchSourceBuilder._SOURCE_FIELD, ObjectParser.ValueType.OBJECT_OR_BOOLEAN);
+        }, SearchSourceBuilder._SOURCE_FIELD, ObjectParser.ValueType.OBJECT_ARRAY_OR_STRING);
```
Comment (jimczi) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: Not a big deal but this would break the parsing as a boolean eg.`_source:true`. You can maybe add a OBJECT_ARRAY_BOOLEAN_OR_STRING to the enum ?

File: core/src/test/java/org/elasticsearch/index/query/InnerHitBuilderTests.java [hunk 2]
```diff
@@ -312,7 +313,7 @@ public static InnerHitBuilder randomInnerHits(boolean recursive, boolean include
         innerHits.setScriptFields(new HashSet<>(scriptFields.values()));
         FetchSourceContext randomFetchSourceContext;
         if (randomBoolean()) {
-            randomFetchSourceContext = new FetchSourceContext(randomBoolean());
+            randomFetchSourceContext = new FetchSourceContext(true, Strings.EMPTY_ARRAY, Strings.EMPTY_ARRAY);
```
Comment (jimczi) [inline core/src/test/java/org/elasticsearch/index/query/InnerHitBuilderTests.java]: Can you add more randomization here. You can build a random list of field names for the includes and the excludes for instance.

**Review by jimczi — COMMENTED** [review]
Thanks for the PR @byronvoorbach 
I left some comments. As @nik9000 suggested can you also change the name of the PR to something more descriptive and put the reference to the issue it closes at the end of the PR description.

File: core/src/test/java/org/elasticsearch/index/query/InnerHitBuilderTests.java (hunk 2 above)
Comment (byronvoorbach) [inline core/src/test/java/org/elasticsearch/index/query/InnerHitBuilderTests.java]: Thanks for the comments @jimczi, I'm away from home till after the Easter weekend. Will pick them up when back!

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java (hunk 1 above)
Comment (byronvoorbach) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: Yes! Will swap it out for that one and test

**Comment by byronvoorbach** [comment]
@jimczi Sorry for the delay. I've been quite busy at one of my clients. I updated the tests and added OBJECT_ARRAY_BOOLEAN_OR_STRING. The test-cases from my gist seem to pass now. Any more comments? :)

**Comment by jimczi** [comment]
retest this please

**Review by jimczi — APPROVED** [review]
I think it's ready @byronvoorbach 
I'll merge soon if the tests are green.

**Comment by byronvoorbach** [comment]
@jimczi Cool! Thanks voor the headsup!!

**Comment by byronvoorbach** [comment]
Hey @jimczi, I noticed that the build is failing. Is there something you need from me?

**Comment by jimczi** [comment]
@byronvoorbach the build is failing but it is not related to this PR. I am currently testing your PR locally. I'll merge if the tests pass on my machine

**Comment by jimczi** [comment]
Thanks @byronvoorbach 
The fix will be available in 5.5.0
