### PR TITLE
Fixes get snapshot duplicates when asking for _all

### LINKED ISSUE #21335: Duplicate IN_PROGRESS snapshots returned by GET /_snapshot/repo/_all in Elasticsearch 5.0
**Elasticsearch version**: 
5.0.0

**Plugins installed**: 
none

**JVM version**: 
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)

**OS version**:
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.el7.x86_64
      Architecture: x86-64

**Description of the problem including expected versus actual behavior**:
When I create a snapshot in any repository, then get all snapshots in the repository. I see two snapshots IN_PROGRESS! Then when the process finishes, I only see one SUCCESSFUL snapshot. The snapshots seem to work correctly, it's just that it shows duplicates while IN_PROGRESS. You can even see below, they have the same uuid: RHlVXKe-TKqB47nAoeh3Sw. Seems like this is probably not intended behavior!

**Steps to reproduce**:
 
1. (CREATE) $ curl -XPUT localhost:9200/_snapshot/brokerhistory/test -d'{"indices":"brokerhistory_2016-11-04"}'
```json 
{"accepted":true}
```
 
2. (IN_PROGRESS) $ curl -XGET localhost:9200/_snapshot/brokerhistory/_all?pretty
```json
{
  "snapshots" : [
    {
      "snapshot" : "test",
      "uuid" : "RHlVXKe-TKqB47nAoeh3Sw",
      "version_id" : 5000099,
      "version" : "5.0.0",
      "indices" : [
        "brokerhistory_2016-11-04"
      ],
      "state" : "IN_PROGRESS",
      "start_time" : "2016-11-04T13:24:42.755Z",
      "start_time_in_millis" : 1478265882755,
      "failures" : [ ],
      "shards" : {
        "total" : 0,
        "failed" : 0,
        "successful" : 0
      }
    },
    {
      "snapshot" : "test",
      "uuid" : "RHlVXKe-TKqB47nAoeh3Sw",
      "version_id" : 5000099,
      "version" : "5.0.0",
      "indices" : [
        "brokerhistory_2016-11-04"
      ],
      "state" : "IN_PROGRESS",
      "start_time" : "2016-11-04T13:24:42.755Z",
      "start_time_in_millis" : 1478265882755,
      "failures" : [ ],
      "shards" : {
        "total" : 0,
        "failed" : 0,
        "successful" : 0
      }
    }
  ]
}
```

3. (SUCCESS) $ curl -XGET localhost:9200/_snapshot/brokerhistory/_all?pretty
```json
{
  "snapshots" : [
    {
      "snapshot" : "test",
      "uuid" : "RHlVXKe-TKqB47nAoeh3Sw",
      "version_id" : 5000099,
      "version" : "5.0.0",
      "indices" : [
        "brokerhistory_2016-11-04"
      ],
      "state" : "SUCCESS",
      "start_time" : "2016-11-04T13:24:42.755Z",
      "start_time_in_millis" : 1478265882755,
      "end_time" : "2016-11-04T13:25:31.027Z",
      "end_time_in_millis" : 1478265931027,
      "duration_in_millis" : 48272,
      "failures" : [ ],
      "shards" : {
        "total" : 1,
        "failed" : 0,
        "successful" : 1
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by abeyad**
Before, when requesting to get the snapshots in a repository, if `_all` was
specified for the set of snapshots to get, any in-progress snapshots would
be returned twice.  This commit fixes the issue ensuring that each snapshot,
whether in-progress or completed, is only returned once when making a call to
get snapshots (GET /_snapshot/{repository_name}/_all).

Closes #21335

### CODE REVIEW

**Comment by ywelsch** [comment]
retest this please

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -169,6 +169,7 @@ public SnapshotInfo snapshot(final String repositoryName, final SnapshotId snaps
         final Set<SnapshotInfo> snapshotSet = new HashSet<>();
         final Set<SnapshotId> snapshotIdsToIterate = new HashSet<>(snapshotIds);
         // first, look at the snapshots in progress
+
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: revert ;)

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 2]
```diff
@@ -80,23 +80,22 @@ protected void masterOperation(final GetSnapshotsRequest request, ClusterState s
         try {
             final String repository = request.repository();
             List<SnapshotInfo> snapshotInfoBuilder = new ArrayList<>();
+            final Map<String, SnapshotId> allSnapshotIds = new HashMap<>();
+            final List<SnapshotId> currentSnapshotIds = new ArrayList<>();
+            for (SnapshotInfo snapshotInfo : snapshotsService.currentSnapshots(repository)) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java]: guard this with `isAllSnapshots(request.snapshots()) == false`

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 3]
```diff
@@ -80,23 +80,22 @@ protected void masterOperation(final GetSnapshotsRequest request, ClusterState s
...
+                SnapshotId snapshotId = snapshotInfo.snapshotId();
+                allSnapshotIds.put(snapshotId.getName(), snapshotId);
+                currentSnapshotIds.add(snapshotId);
+            }
+            for (SnapshotId snapshotId : snapshotsService.snapshotIds(repository)) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java]: guard this with `isCurrentSnapshots(request.snapshots()) == false`

**Review by ywelsch — CHANGES_REQUESTED** [review]
Left some comments

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java (hunk 2 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java]: if you set `_all` (i.e. `isAllSnapshots(request.snapshots()) == true`), you still want the current snapshots too.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 1 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: done

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java (hunk 3 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java]: Thinking about this some more, I like the idea of being able to specify `_current` in addition to other snapshots.  I can imagine a user wanting to know the state of snapshots starting with "2016-11-*" and the "current" one.  In this case, we would treat `_current` as a regex that resolves to whatever the currently running snapshots are.  What do you think about that?

Comment (abeyad) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java]: I pushed 14e12067cc1da984c6786e22c0f5892bbba7b41e

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 4]
```diff
@@ -2505,8 +2503,34 @@ public void testGetSnapshotsRequest() throws Exception {
...
+            .get();
+        waitForBlock(initialBlockedNode, repositoryName, TimeValue.timeValueSeconds(60)); // wait for block to kick in
+        getSnapshotsResponse = client.admin().cluster()
+                                   .prepareGetSnapshots("test-repo")
+                                   .setSnapshots(randomFrom("_all", "_current", "snap-on-*", "*-on-empty-repo", "snap-on-empty-repo"))
+                                   .get();
+        assertEquals(1, getSnapshotsResponse.getSnapshots().size());
+        assertEquals("snap-on-empty-repo", getSnapshotsResponse.getSnapshots().get(0).snapshotId().getName());
+        unblockNode(repositoryName, initialBlockedNode); // unblock node
+        assertBusy(() -> {
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: instead of the assertBusy, maybe use a future above with setWaitForCompletion(true).

**Review by ywelsch — APPROVED** [review]
LGTM

File: core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 4 above)
Comment (abeyad) [inline core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: I pushed e00a2a16758da5e49faa3a6416762a3ab31c2551 to improve this

**Comment by abeyad** [comment]
thanks for the review @ywelsch !

**Comment by abeyad** [comment]
5.x commit: ff02fb43468919f06dca90b4392c6cb5f1c4dc03
5.0 commit: 7a25b1104d66bb52f2c1b28b6bf2d9f4f35bf1df
