### PR TITLE
catch processor/pipeline factory exceptions and return structured error responses

### LINKED ISSUE #16010: [Ingest] Add more descriptive pipeline factory errors in _simulate and PUT pipeline/id
When someone issues the following request to `_simulate`, The pipeline factory will error out while 
attempting to construct the supplied pipeline. The reason for this is that the `date` processor is not configured correctly, `locale` is invalid. The exception is thrown in the processor's `create` here: https://github.com/elastic/elasticsearch/blob/feature/ingest/core/src/main/java/org/elasticsearch/ingest/processor/DateProcessor.java#L130.

```json
{
            "pipeline": {
              "description": "_description",
              "processors": [
                {
                  "date" : {
                  "processor_tag" : "date_processor",
                  "match_field" : "date_source_field",
                  "target_field" : "date_target_field",
                  "match_formats" : ["dd/MM/yyyy"],
                  "locale": "UNDEFINED"
                  }
                },
                {
                  "set" : {
                    "field" : "field3",
                    "value" : "third_val"
                  }
                }
              ]
            },
            "docs": [
              {
                "_index": "index",
                "_type": "type",
                "_id": "id",
                "_source": {
                  "foo": "bar"
                }
              }
            ]
          }
```

The response from this is an internal server error. This makes it difficult to know which processor was incorrectly configured within the pipeline definition. What would be nicer is a response object that is similar to this:

```
{
 "pipeline_configuration_error": [
   {
     "errors": [
       {
         "processor_tag": "date_processor",
         "error": {
           "root_cause": [
             {
               "type": "illegal_argument_exception",
               "reason": "Invalid language tag specified: UNDEFINED"
             }
           ],
           "type": "illegal_argument_exception",
           "reason": "Invalid language tag specified: UNDEFINED"
         }
       }
     ]
   }
 ]
}
```

It would be great if we can return this processor-level configuration error to all processors that are improperly configured, instead of just the first one. This would require extra logic in the pipline factory to record exceptions and collect them into one large exception instead of throwing the first one it receives.

@martijnvg @javanna what do you think?

@BigFunger, let me know if this is what you meant? The actual response object is still up in the air.

### PR DESCRIPTION
**Pull request by talevy**
fixes: https://github.com/elastic/elasticsearch/issues/16010

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineTransportAction.java [hunk 1]
```diff
@@ -56,6 +57,10 @@ protected void doExecute(SimulatePipelineRequest request, ActionListener<Simulat
             } else {
                 simulateRequest = SimulatePipelineRequest.parse(source, request.isVerbose(), pipelineStore);
             }
+        } catch (PipelineFactoryError e) {
+            // TODO(talevy): wrap SimulatePipelineResponse & PipelineFactoryErrorActionResponse into ONE object so this would work
+            listener.onResponse(new PipelineFactoryErrorActionResponse(e));
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineTransportAction.java]: maybe `SimulatePipelineResponse` can just hold a `PipelineFactoryError` field? Then this would work and be simple?

File: core/src/main/java/org/elasticsearch/action/ingest/PipelineFactoryErrorActionResponse.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+import org.elasticsearch.common.io.stream.StreamInput;
+import org.elasticsearch.common.io.stream.StreamOutput;
+import org.elasticsearch.common.xcontent.ToXContent;
+import org.elasticsearch.common.xcontent.XContentBuilder;
+import org.elasticsearch.common.xcontent.XContentBuilderString;
+import org.elasticsearch.ingest.core.PipelineFactoryError;
+
+import java.io.IOException;
+
+public class PipelineFactoryErrorActionResponse extends ActionResponse implements ToXContent {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/action/ingest/PipelineFactoryErrorActionResponse.java]: I think should be part as a field of both the simulate response and the write pipeline response. Then instead of extending from ActionResponse this would implement Streamable.

Comment (talevy) [inline core/src/main/java/org/elasticsearch/action/ingest/PipelineFactoryErrorActionResponse.java]: The only reason I made this class was because I wanted to reuse the `toXContent` logic since I am updating the rest response from with the `WritePipelineResponseRestListener`. but I will look back at this strategy and see how to clean it up

File: core/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineTransportAction.java (hunk 1 above)
Comment (talevy) [inline core/src/main/java/org/elasticsearch/action/ingest/SimulatePipelineTransportAction.java]: yeah, that would work. I don't know why, but yesterday I felt like having this field that is not always applicable to be really confusing. but it would definitely work and be less refactoring

File: core/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 3]
```diff
@@ -156,8 +158,12 @@ public void put(ClusterService clusterService, PutPipelineRequest request, Actio
             // validates the pipeline and processor configuration before submitting a cluster update task:
             Map<String, Object> pipelineConfig = XContentHelper.convertToMap(request.getSource(), false).v2();
             constructPipeline(request.getId(), pipelineConfig);
+        } catch (ConfigurationPropertyException e) {
+            listener.onResponse(new WritePipelineResponse(new PipelineFactoryError(e)));
+            return;
         } catch (Exception e) {
-            throw new IllegalArgumentException("Invalid pipeline configuration", e);
+            listener.onResponse(new WritePipelineResponse(new PipelineFactoryError("Invalid pipeline configuration")));
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: we should include `e` here, otherwise we lose the cause of the configuration error.

File: core/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 4]
```diff
@@ -156,8 +158,12 @@ public void put(ClusterService clusterService, PutPipelineRequest request, Actio
             // validates the pipeline and processor configuration before submitting a cluster update task:
             Map<String, Object> pipelineConfig = XContentHelper.convertToMap(request.getSource(), false).v2();
             constructPipeline(request.getId(), pipelineConfig);
+        } catch (ConfigurationPropertyException e) {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: can we move the catching logic to `constructPipeline(...)`? then we can create unit tests for this and remove the java integ tests in `IngestClientIT`.

Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: since this logic is only really necessary in `put` to validate pipeline _can_ be constructed, I feel like we can rename `constructPipeline` to something more like a pipeline verification utility, including all this exception logic

File: core/src/main/java/org/elasticsearch/ingest/PipelineStore.java (hunk 3 above)
Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: will add `e.getMessage()` to the string, good catch!

File: core/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 5]
```diff
@@ -235,8 +235,16 @@ public Pipeline get(String id) {
         return result;
     }
 
-    private Pipeline constructPipeline(String id, Map<String, Object> config) throws Exception {
-        return factory.create(id, config, processorFactoryRegistry);
+    private WritePipelineResponse constructPipelineResponse(String id, Map<String, Object> config) {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: maybe just return null if all is ok? then we just need to do a null check at line 158.

Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: makes it clearer, yes. updated.

File: core/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 6]
```diff
@@ -235,8 +235,15 @@ public Pipeline get(String id) {
         return result;
     }
 
-    private Pipeline constructPipeline(String id, Map<String, Object> config) throws Exception {
-        return factory.create(id, config, processorFactoryRegistry);
+    WritePipelineResponse constructPipelineResponse(String id, Map<String, Object> config) {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: maybe rename to `validatePipelineResponse`?

File: core/src/main/java/org/elasticsearch/ingest/core/PipelineFactoryError.java [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+        builder.field(Fields.PROCESSOR_TYPE, processorType);
+        builder.field(Fields.PROCESSOR_TAG, processorTag);
+        builder.field(Fields.REASON, reason);
+        builder.field(Fields.PROPERTY_NAME, processorPropertyName);
+        builder.endObject();
+        return builder;
+    }
+
+
+    static final class Fields {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/ingest/core/PipelineFactoryError.java]: maybe remove the Fields here and just use strings in toXContent(...)? It used to be in SimulateDocumentResult subclasses too, but it was removed during reviewing.

**Comment by martijnvg** [comment]
Left two small comments. OTT LGTM

File: core/src/main/java/org/elasticsearch/ingest/core/PipelineFactoryError.java (hunk 7 above)
Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/core/PipelineFactoryError.java]: ah, I see. thought this was the desired approach, I'll move to strings

File: core/src/main/java/org/elasticsearch/ingest/PipelineStore.java (hunk 6 above)
Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: sure, I'll update to that. still feels like a weird method in general... but it works

**Comment by s1monw** [comment]
@talevy @martijnvg I think this PR should be reverted and we should use out existing exception infrastructure for this. You can set headers on all ElasticsearchExceptions that get's rendered in a strucutred way. There is no reason to add so much custom code we have a streamlined way to do this.

you can just do something like this:

```JAVA
try {
 // configure
} catch (Exception ex) {
 ElasticsearchException e = new ElasticsearchException("failed to configure pipeline", ex);
 e.addHeader("processor", "grok");
 e.addHeader("what_have_you", "boom");
  throw e;
}
```
this will get rendered as:

```JSON
{
  "type" : "exception",
  "reason" : "failed to configure pipeline",
  "caused_by" : {
    "type" : "illegal_argument_exception",
    "reason" : "something is wrong"
  },
  "header" : {
    "what_have_you" : "boom",
    "processor" : "grok"
  }
}
```

**Comment by talevy** [comment]
interesting, I was not familiar with this `header` functionality. thanks for the suggestion!

do we want to do this. shall I preserve the `ConfigurationPropertyException` and then wrap this during the same time that we have all the `PipelineFactoryError` logic? that would really clean up that level, you're right. I'll start off with that, and we can push it down further if that is suitable.

**Comment by martijnvg** [comment]
> do we want to do this. shall I preserve the ConfigurationPropertyException and then wrap this during the same time that we have all the PipelineFactoryError logic? that would really clean up that level, you're right. I'll start off with that, and we can push it down further if that is suitable.

Discussed this we only throw `SearchParseException` and add headers from the processors and `ConfigurationUtils`. The `PipelineFactoryError` logic and `ConfigurationPropertyException` are no longer needed.

**Comment by s1monw** [comment]
@martijnvg I think `ElasticsearchParseException` is what we should throw

**Comment by s1monw** [comment]
oh and @talevy @martijnvg by reverting I mean not back it out just use the existing mechanism. :)

thanks

**Comment by martijnvg** [comment]
> @martijnvg I think ElasticsearchParseException is what we should throw

Agreed `ElasticsearchParseException` is better otherwise we're forced to pass down null arguments.

**Comment by talevy** [comment]
confirming here that I am working on migrating to `ElasticsearchParseException`! thanks

**Comment by talevy** [comment]
PR for this fix can be found here: #16355
