### PR TITLE
Optimize GCS Mock

### LINKED ISSUE #50754: GoogleCloudStorageBlobContainerRetriesTests.testWriteLargeBlob fails
GoogleCloudStorageBlobContainerRetriesTests.testWriteLargeBlob has failed several times last week (see [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'summary:%22testWriteLargeBlob%22'),sort:!(time,desc)))). Some instances:

- https://gradle-enterprise.elastic.co/s/iwhv2xr66lt7o
- https://gradle-enterprise.elastic.co/s/cz6nbshaa4wvo

### LINKED ISSUE #51446: org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests testSnapshotWithLargeSegmentFiles
Reproduce with (does not repro locally): 
```
./gradlew ':plugins:repository-gcs:test' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles" -Dtests.seed=79146B9E4DC8DB20 -Dtests.security.manager=true -Dtests.locale=ro -Dtests.timezone=America/La_Paz -Dcompiler.java=13 -Druntime.java=8	
```
Error
```
 java.lang.AssertionError: Only index blobs should remain in repository but found [indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__U-yvyHGGSC-HG3-rYgESAQ, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__2W1fsDR7RHqVaHUbR2ljDg, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__PYCKH3IuR8OvsesbZ53Q4A, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__ChKaNwG-QDeOLEFMBmV4hg, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__4BrkUvaDSoaRxda8zaYzmw, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__8TyJLropTGCbwEdpGgkCgg, snap-6BvhIzAVS8Wk0yEzY1yHHw.dat, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__TYjSMqKWSAyimBORtvz2hQ, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__nr1hKmAYS8mwQoYGfONLxA, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__AIvhEKrQTT6rQ95Q_a6Mcw, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/snap-6BvhIzAVS8Wk0yEzY1yHHw.dat, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__OYx13Q6MT329W_IM0oSGsg, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__lc7ep5qgSfGUi5XOU2GgVA, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__FnKJqi01RL6xd-BqebZ9qw, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__iv8fkpEiRkGaiSfcDb6cTg, indices/U3Ra9xA9QYOIf2JnrS9qiw/meta-6BvhIzAVS8Wk0yEzY1yHHw.dat, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__45KqhxnDQJyJbNxg5bOdBw, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__zLdkon40Q5aMTM5YjMsXWQ, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__UAbVvyV5QHq0RsZGVRdphg, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__jXvlBf1lTn6Ct1d2xyEeHg, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__ED_68lu_Qci0brGcdBWWqA, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__0j2RqpNKRKqy6RNbv4iniA, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__SqeeF3m4TkqcEJrcZfx0XA, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__6j7bvik8RDqSNmZIHaHdlw, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__gj5mlfNKQmC_sqRVWkQh4A, meta-6BvhIzAVS8Wk0yEzY1yHHw.dat, indices/U3Ra9xA9QYOIf2JnrS9qiw/0/__YCpLvzOYR6m3ZMbSCjvCuw]	
 
    Expected: a collection with size <0>	
         but: collection size was <27>	
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
        at org.junit.Assert.assertThat(Assert.java:956)	
        at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.tearDownHttpServer(ESMockAPIBasedRepositoryIntegTestCase.java:112)

```

Build scan : https://gradle-enterprise.elastic.co/s/5agjwd5uxd4g6

90 day history
image

Suspected related issues (via comments from prior failures)
* https://github.com/elastic/elasticsearch/pull/48541
* https://github.com/elastic/elasticsearch/commit/732fc4d755abf1a6395e55fd50bb4762bbf1945d

Note - it seems this happens (exclusively?) on 7.5/7.6/7.x and sometimes, but not always have a SocketTimeout too. For example (different build scan then above) https://gradle-enterprise.elastic.co/s/4z2vxrxrohjmq/console-log?anchor=7206

### PR DESCRIPTION
**Pull request by original-brownbear**
This test was still very GC heavy in Java 8 runs in particular
which seems to slow down request processing to the point of timeouts
in some runs.
This PR completely removes the large number of O(MB) `byte[]` allocations
that were happening in the mock http handler which cuts the allocation rate
by about a factor of 5 in my local testing for the GC heavy `testSnapshotWithLargeSegmentFiles`
run.

Closes #51446
Closes #50754

### CODE REVIEW

**Comment by original-brownbear** [comment]
@tlrx if this doesn't help I think we have to find a way to down-scale these tests a little maybe. They're handling multiple MB of data at once which is a little tricky with `512M` heaps on Cloud. Though with this change at least on my local even Java 8 runs on `7.x` never go above ~250MB heap usage so maybe this will work :)

File: test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java [hunk 1]
```diff
@@ -212,35 +213,21 @@ public void handle(final HttpExchange exchange) throws IOException {
...
                     return;
                 }
-                byte[] blob = BytesReference.toBytes(blobs.get(blobName));
+                BytesReference blob = blobs.get(blobName);
                 final String range = exchange.getRequestHeaders().getFirst("Content-Range");
                 final Integer limit = getContentRangeLimit(range);
                 final int start = getContentRangeStart(range);
                 final int end = getContentRangeEnd(range);
 
-                final ByteArrayOutputStream out = new ByteArrayOutputStream() {
```
Comment (original-brownbear) [inline test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java]: Using the BAOS here was pretty brutal for multi MB requests :) Much nicer now with the `16kb` chunks `Streams.readFully(wrappedRequest)` produces

File: test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java [hunk 2]
```diff
@@ -308,10 +295,7 @@ private String httpServerUrl(final HttpExchange exchange) {
             } else {
                 // removes the trailing end "\r\n--__END_OF_PART__--\r\n" which is 23 bytes long
                 int len = fullRequestBody.length() - startPos - 23;
-                final InputStream stream = fullRequestBody.slice(startPos, len).streamInput();
-                final byte[] buffer = new byte[len];
-                Streams.readFully(stream, buffer);
-                content = Tuple.tuple(name, new BytesArray(buffer));
+                content = Tuple.tuple(name, fullRequestBody.slice(startPos, len));
```
Comment (original-brownbear) [inline test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java]: Even though `slice` wastes some memory here for the wrapping around the actual blob content for smaller blobs, it's a huge efficiency gain to stick with `16kb` chunks from the `BytesReference` compared to allocating a potentially MB sized array.

File: test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java [hunk 3]
```diff
@@ -212,35 +213,21 @@ public void handle(final HttpExchange exchange) throws IOException {
...
-                int length = Math.max(end + 1, limit != null ? limit : 0);
-                if ((int) bytesRead > length) {
-                    throw new AssertionError("Requesting more bytes than available for blob");
-                }
-                if (length > blob.length) {
-                    blob = ArrayUtil.growExact(blob, length);
-                }
-                System.arraycopy(out.toByteArray(), 0, blob, start, Math.toIntExact(bytesRead));
-                blobs.put(blobName, new BytesArray(blob));
+                blob = new CompositeBytesReference(blob, Streams.readFully(wrappedRequest));
```
Comment (tlrx) [inline test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java]: I didn't know about this one :+1:

**Review by tlrx — APPROVED** [review]
LGTM, thanks for taking care of this Armin

**Comment by original-brownbear** [comment]
Thanks Tanguy!
