### PR TITLE
Replace transport version utils with a build service

### LINKED ISSUE #132788: [CI] TransportVersionManagementPluginFuncTest definitions have primary ids which cannot change failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10120 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/4gxnfxbqmosa6)
- [elasticsearch-periodic-platform-support #10120 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mpybsym7su4i4)
- [elasticsearch-periodic-platform-support #10120 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/uowcoi4axtiri)
- [elasticsearch-periodic-platform-support #10113 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ciknlx2xbxqfi)
- [elasticsearch-periodic-platform-support #10113 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/j3pnhlhkc37ee)
- [elasticsearch-periodic-platform-support #10113 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/nkxco3ys5sqxq)
- [elasticsearch-periodic-platform-support #10106 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/k5bj7opqe4ptc)
- [elasticsearch-periodic-platform-support #10106 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/icvio7xkpiznk)
- [elasticsearch-periodic-platform-support #10106 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/73zezhocn3ado)
- [elasticsearch-periodic-platform-support #10099 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/dszfsbg33i5y6)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.gradle.internal.transport.TransportVersionManagementPluginFuncTest),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('definitions%20have%20primary%20ids%20which%20cannot%20change'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

normalized(givenOutput).contains(normalized(expected))
|          |            |        |          |
|          |            false    |          Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] modifies existing patch id from 8012001 to 8012002
|          |                     Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] modifies existing patch id from 8012001 to 8012002
|          =======================================
|          Elasticsearch Build Hamster says Hello!
|            Gradle Version        : 8.14.2
|            OS Info               : Windows Server 2025 10.0 (amd64)
|            JDK Version           : 21.0.7+6-LTS (Eclipse Temurin)
|            JAVA_HOME             : C:/Users/buildkite/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2
|            Random Testing Seed  
[truncated]
```

**Issue Reasons:**
- [8.19] 6 consecutive failures in test definitions have primary ids which cannot change
- [8.19] 15 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in step windows-2019_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [8.19] 45 failures in test definitions have primary ids which cannot change (75.0% fail rate in 60 executions)
- [8.19] 15 failures in step windows-2025_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in step windows-2019_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 15 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132789: [CI] TransportVersionManagementPluginFuncTest latest files cannot change base id failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10120 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/4gxnfxbqmosa6)
- [elasticsearch-periodic-platform-support #10120 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mpybsym7su4i4)
- [elasticsearch-periodic-platform-support #10120 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/uowcoi4axtiri)
- [elasticsearch-periodic-platform-support #10113 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ciknlx2xbxqfi)
- [elasticsearch-periodic-platform-support #10113 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/j3pnhlhkc37ee)
- [elasticsearch-periodic-platform-support #10113 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/nkxco3ys5sqxq)
- [elasticsearch-periodic-platform-support #10106 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/k5bj7opqe4ptc)
- [elasticsearch-periodic-platform-support #10106 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/icvio7xkpiznk)
- [elasticsearch-periodic-platform-support #10106 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/73zezhocn3ado)
- [elasticsearch-periodic-platform-support #10099 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/dszfsbg33i5y6)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.gradle.internal.transport.TransportVersionManagementPluginFuncTest),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('latest%20files%20cannot%20change%20base%20id'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

normalized(givenOutput).contains(normalized(expected))
|          |            |        |          |
|          |            false    |          Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] modifies existing patch id from 8012001 to 8012002
|          |                     Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] modifies existing patch id from 8012001 to 8012002
|          =======================================
|          Elasticsearch Build Hamster says Hello!
|            Gradle Version        : 8.14.2
|            OS Info               : Windows Server 2025 10.0 (amd64)
|            JDK Version           : 21.0.7+6-LTS (Eclipse Temurin)
|            JAVA_HOME             : C:/Users/buildkite/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2
|            Random Testing Seed  
[truncated]
```

**Issue Reasons:**
- [8.19] 6 consecutive failures in test latest files cannot change base id
- [8.19] 15 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in step windows-2019_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [8.19] 45 failures in test latest files cannot change base id (75.0% fail rate in 60 executions)
- [8.19] 15 failures in step windows-2025_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in step windows-2019_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 15 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #132790: [CI] TransportVersionManagementPluginFuncTest cannot change committed ids to a branch failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10120 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/4gxnfxbqmosa6)
- [elasticsearch-periodic-platform-support #10120 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mpybsym7su4i4)
- [elasticsearch-periodic-platform-support #10120 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/uowcoi4axtiri)
- [elasticsearch-periodic-platform-support #10113 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ciknlx2xbxqfi)
- [elasticsearch-periodic-platform-support #10113 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/j3pnhlhkc37ee)
- [elasticsearch-periodic-platform-support #10113 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/nkxco3ys5sqxq)
- [elasticsearch-periodic-platform-support #10106 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/k5bj7opqe4ptc)
- [elasticsearch-periodic-platform-support #10106 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/icvio7xkpiznk)
- [elasticsearch-periodic-platform-support #10106 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/73zezhocn3ado)
- [elasticsearch-periodic-platform-support #10099 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/dszfsbg33i5y6)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.gradle.internal.transport.TransportVersionManagementPluginFuncTest),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('cannot%20change%20committed%20ids%20to%20a%20branch'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

normalized(givenOutput).contains(normalized(expected))
|          |            |        |          |
|          |            false    |          Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] modifies existing patch id from 8012001 to 8012002
|          |                     Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] modifies existing patch id from 8012001 to 8012002
|          =======================================
|          Elasticsearch Build Hamster says Hello!
|            Gradle Version        : 8.14.2
|            OS Info               : Windows Server 2025 10.0 (amd64)
|            JDK Version           : 21.0.7+6-LTS (Eclipse Temurin)
|            JAVA_HOME             : C:/Users/buildkite/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2
|            Random Testing Seed  
[truncated]
```

**Issue Reasons:**
- [8.19] 6 consecutive failures in test cannot change committed ids to a branch
- [8.19] 15 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in step windows-2019_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [8.19] 15 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [8.19] 45 failures in test cannot change committed ids to a branch (75.0% fail rate in 60 executions)
- [8.19] 15 failures in step windows-2025_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in step windows-2019_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 15 executions)
- [8.19] 15 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 15 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by rjernst**
Several transport version build tasks have a need to access the repository-wide transport version resources. Thus far it has been done through several utility methods. This commit moves these utility methods into an encapsulated build service that is shared across the transport version tasks. The advantage is that no paths are used, the build service encapsulates access to the resources and understands internally how to find the correct filesystem path and load it.

closes #132788
closes #132789
closes #132790

### CODE REVIEW

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+    private final AtomicReference<Set<String>> changedResources = new AtomicReference<>(null);
+
+    @Inject
+    public TransportVersionResourcesService(Parameters params) {
+        this.resourcesDir = params.getResourcesDirectory().get().getAsFile().toPath();
+        this.rootDir = params.getRootDirectory().get().getAsFile().toPath();
+    }
+
+    /**
+     * Return the transport version resources directory for this repository.
```
Comment (JVerwolf) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java]: "resources directory" means something specific in this context, but also has a more general meaning that might confuse readers. Should we define this term?

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+    public interface Parameters extends BuildServiceParameters {
+        DirectoryProperty getResourcesDirectory();
+
+        DirectoryProperty getRootDirectory();
+    }
+
+    @Inject
+    public abstract ExecOperations getExecOperations();
+
+    private static final Path DEFINITIONS_DIR = Path.of("definitions");
```
Comment (JVerwolf) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java:62]: I think it would be helpful to have an description of the resources directory structure, either here or as a javadoc on the class. We could also defer to a future .md file, which we point to from here at a later time.
e.g.
```
This defines the following directory structure:
${Resources}/definitions/named  #Definitions referenced by names in the codebase.
${Resources}/definitions/initial #Initial TVs introduced by CI when branches are cut.
${Resources}/latest #The latest TVs used on each release branch.
```

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+
+                HashSet<String> resources = new HashSet<>();
+                Collections.addAll(resources, output.split(System.lineSeparator()));
+                changedResources.set(resources);
+            }
+        }
+        return changedResources.get();
+    }
+
+    // Read a trasnport version resource from the main branch, or return null if it doesn't exist on main
```
Comment (JVerwolf) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java]: Spelling: trasnport

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/GenerateTransportVersionManifestTask.java [hunk 4]
```diff
@@ -24,15 +28,24 @@
 import java.nio.file.attribute.BasicFileAttributes;
 
 public abstract class GenerateTransportVersionManifestTask extends DefaultTask {
+
+    @ServiceReference("transportVersionResources")
+    abstract Property<TransportVersionResourcesService> getTransportResources();
+
     @InputDirectory
-    public abstract DirectoryProperty getDefinitionsDirectory();
+    @Optional
```
Comment (JVerwolf) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/GenerateTransportVersionManifestTask.java:36]: For my own understanding, does `@Optional` here imply that this can be overridden by plugin setup, but defaults to `return getTransportResources().get().getDefinitionsDir();`? 

However, I don't see this being used anymore, so I'm curious why we keep this as an input?

**Review by JVerwolf — APPROVED** [review]
Much cleaner.

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/GenerateTransportVersionManifestTask.java (hunk 4 above)
Comment (rjernst) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/GenerateTransportVersionManifestTask.java:36]: It's not used directly, but it is used by gradle. Optional refers to whether the directory must exist at runtime before the task runs.

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java (hunk 2 above)
Comment (rjernst) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java:62]: I added this as a class javadoc.

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java (hunk 1 above)
Comment (rjernst) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java]: I reworded a bit to make clearer these are transport version resources.

**Comment by mark-vieira** [comment]
@rjernst I think perhaps a merge or rebase went wrong here as there are a ton of unrelated changes in this PR.

**Comment by rjernst** [comment]
> I think perhaps a merge or rebase went wrong here

Should be good now

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java [hunk 5]
```diff
@@ -0,0 +1,227 @@
...
+
+    private Path getLatestRelativePath(String releaseBranch) {
+        return LATEST_DIR.resolve(releaseBranch + ".csv");
+    }
+
+    // Return the transport version resources paths that exist in main
+    private Set<String> getMainResources() {
+        if (mainResources.get() == null) {
+            synchronized (mainResources) {
+                String output = gitCommand("ls-tree", "--name-only", "-r", "main", ".");
```
Comment (mark-vieira) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java:167]: If we're going to use relative paths here, then we should explicitly set the working directory when calling exec. There's no real guarantee that this is the workspace directory.

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesPlugin.java [hunk 6]
```diff
@@ -20,15 +20,20 @@
...
 public class TransportVersionResourcesPlugin implements Plugin<Project> {
 
     @Override
     public void apply(Project project) {
         project.getPluginManager().apply(LifecycleBasePlugin.class);
 
+        project.getGradle()
+            .getSharedServices()
+            .registerIfAbsent("transportVersionResources", TransportVersionResourcesService.class, spec -> {
+                Directory transportResources = project.getLayout().getProjectDirectory().dir("src/main/resources/transport");
```
Comment (mark-vieira) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesPlugin.java]: Presumably this plugin will only ever be applied to a single project, right? Build services are global to the build so all consumers will use the same params. It's not clear if we also use this in serverless and how that will work.

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java (hunk 5 above)
Comment (rjernst) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesService.java:167]: We set the working directory in `gitCommand` using `-C`

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesPlugin.java (hunk 6 above)
Comment (rjernst) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionResourcesPlugin.java]: Yes, and this being global is part of how it works. Note that this is also used by ValidateTransportVersionReferencesTask which are in every module/plugin. Essentially it's a way to plumb in a wrapper around the resources that are ready from source on disk instead of having shared methods (and the gradle property) to know where to find these resources.
