### PR TITLE
Address precision issue in IndexDiskUsageAnalyzerTests#testCompletionFields

### LINKED ISSUE #123269: [CI] IndexDiskUsageAnalyzerTests testCompletionField failing
**Build Scans:**
- [elasticsearch-intake #18732 / part1](https://gradle-enterprise.elastic.co/s/ulyoadoedtndq)
- [elasticsearch-periodic-platform-support #6583 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mg6tq6s27s7im)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageAnalyzerTests.testCompletionField" -Dtests.seed=DE66FA5B9B04A955 -Dtests.locale=so -Dtests.timezone=America/Toronto -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageAnalyzerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCompletionField),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: field=suggest_2 type=inverted_index actual=26527 expected=28584
```

**Issue Reasons:**
- [main] 2 failures in test testCompletionField (1.4% fail rate in 143 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by javanna**
We have some tolerance wound how many bytes we report for these completion fields. But the values depend on the distribution of the random values that determine how many docs get an option field. This commit makes the test more precise by computing the real ratio between docs that have the optional field and the total number of docs, so that we can base assertion on more realistic expectations.

This is a pretty rare failure that happened so far only in main, but it reproduces in 8.x as well, hence I suggest we backport the fix.

Closes #123269

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/admin/indices/diskusage/IndexDiskUsageAnalyzerTests.java [hunk 1]
```diff
@@ -339,23 +339,27 @@ public PostingsFormat getPostingsFormatForField(String field) {
...
                 for (int i = 0; i < numDocs; i++) {
                     final Document doc = new Document();
                     if (randomDouble() < 0.5) {
+                        numDocsWithSuggest1Field++;
                         doc.add(new SuggestField("suggest_1", randomAlphaOfLength(10), randomIntBetween(1, 20)));
                     }
                     doc.add(new SuggestField("suggest_2", randomAlphaOfLength(10), randomIntBetween(1, 20)));
                     writer.addDocument(doc);
                 }
+                docsWithSuggest1FieldRatio = (float) numDocsWithSuggest1Field / (numDocs + numDocsWithSuggest1Field);
```
Comment (drempapis) [inline server/src/test/java/org/elasticsearch/action/admin/indices/diskusage/IndexDiskUsageAnalyzerTests.java:355]: To compute the ratio of documents matching a specific criteria, isn't the formula `ratio=  count of matching documents / total document count` enough?

I wonder why the `numDocsWithSuggest1Field` is added with the `numDocs`?

Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/admin/indices/diskusage/IndexDiskUsageAnalyzerTests.java:355]: because you want to account for their size distributions across the whole index: a field that is present in every document counts as 2/3, and a field of same size that is present on about half of the documents, counts as the remaining 1/3 in the total size of that index.

Comment (drempapis) [reply server/src/test/java/org/elasticsearch/action/admin/indices/diskusage/IndexDiskUsageAnalyzerTests.java:355]: Ty @javanna for the clarification. I see the point

**Review by drempapis — APPROVED** [review]
LGTM!

**Comment by javanna** [comment]
Thanks @drempapis !
