### PR TITLE
Process dynamic templates in order.

### LINKED ISSUE #2401: Dynamic template with match_mapping_type ignored when there's a match "*" after it
I have the following dynamic mappings set up in default-mapping.json:

```javascript
{
    "_default_": {
        "_source": {
            "enabled": false
        },
        "_all": {
            "enabled": false
        },
        "dynamic_templates": [
            {
                "strings": {
                    "match": "*",
                    "match_mapping_type": "string",
                    "mapping": {
                        "type": "multi_field",
                        "fields": {
                            "{name}": {
                                "type": "string",
                                "index": "not_analyzed",
                                "omit_norms": true,
                                "omit_term_freq_and_positions": true
                            },
                            "lower": {
                                "type": "string",
                                "index": "analyzed",
                                "analyzer": "lowercase",
                                "omit_norms": true,
                                "omit_term_freq_and_positions": true
                            }
                        }
                    }
                }
            },
            {
                "everything": {
                    "match": "*",
                    "mapping": {
                        "omit_norms": true,
                        "omit_term_freq_and_positions": true
                    }
                }
            }
        ]
    }
}
```

If I understand this page correctly (at the very bottom):

http://www.elasticsearch.org/guide/reference/mapping/root-object-type.html

the first mapping that matches will be applied -- i.e. "everything" should only be applied to fields that don't match "strings".

However, this isn't what I see (in 0.19.8 anyway) -- no matter which order I put the mappings in, all fields have "everything" applied, including string fields.

(By the way, "lowercase" is a simple custom analayzer with a keyword tokenizer and lowercase token filter.)

### LINKED ISSUE #18625: Templates defined in Dynamic Mapping are NOT processed in order
**Elasticsearch version**:
1.7 or 2.2 

**JVM version**:
1.8.0_66

**OS version**:
OSX 10.11.5

**Description of the problem including expected versus actual behavior**:
According to the [dynamic-templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html)
> Templates are processed in order — the first matching template wins.

in the test case below, it's expected to hit only the first template definition, **path_match_str_def**, but it seemed hit the one next and got the exceptions attached. 

**Steps to reproduce**:
 1.mapping template 
```javascript  
"mappings": {
    "sdr": {
      "dynamic_templates": [
        {
          "path_match_str_def": {
            "path_match": "mypath.*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed",
              "doc_values": true
            }
          }
        },
        {
          "path_match_str_int": {
            "path_match": "mypath.var_i*",
            "mapping": {
              "type": "long",
              "index": "not_analyzed",
              "doc_values": true
            }
          }
        }
      ],
      "properties": {
        "mypath": {
          "type": "object",
          "properties": {
            "root": {
              "type": "string",
              "index": "not_analyzed",
              "doc_values": true
            }
          }
        }
      }
    }
  }
```
 2.document
`{
  "mypath": {
    "var_istring": "abcdef"
  }
}`
 3.got exceptions below

```java
RemoteTransportException[[Living Laser][127.0.0.1:9300][indices:data/write/index[p]]]; nested: MapperParsingException[failed to parse [mypath.var_istring]]; nested: NumberFormatException[For input string: "abcdef"];
Caused by: MapperParsingException[failed to parse [mypath.var_istring]]; nested: NumberFormatException[For input string: "abcdef"];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:343)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:318)
	at org.elasticsearch.index.mapper.DocumentParser.parseAndMergeUpdate(DocumentParser.java:765)
	at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:652)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:451)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:271)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:315)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:335)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:261)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:131)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:547)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:529)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:65)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:595)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:263)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "abcdef"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
	at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:275)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:241)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:335)
	... 26 more
 ```

### PR DESCRIPTION
**Pull request by jpountz**
When calling `findTemplateBuilder(context, currentFieldName, "text", null)`,
elasticsearch ignores all templates that have a `match_mapping_type` set since
no dynamic type is provided (the last parameter, which is null in that case).
So this should only be called _last_. Otherwise, if a path-based template
matches, it will have precedence over all type-based templates.

Closes #18625
Closes #2401

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 1]
```diff
@@ -676,16 +676,6 @@ private static void parseNullValue(ParseContext context, ObjectMapper parentMapp
...
         if (token == XContentParser.Token.VALUE_STRING) {
-            // do a quick test to see if its fits a dynamic template, if so, use it.
-            // we need to do it here so we can handle things like attachment templates, where calling
-            // text (to see if its a date) causes the binary value to be cleared
-            {
-                Mapper.Builder builder = context.root().findTemplateBuilder(context, currentFieldName, "text", null);
-                if (builder != null) {
-                    return builder;
-                }
-            }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: This code was initially added to fix #1418. But I checked and the bug does not reproduce without this block of code with recent versions of Jackson.

**Comment by s1monw** [comment]
I looked at it and I think I understand what's going on so LGTM but I think @rjernst should also look

**Comment by rjernst** [comment]
LGTM too
