### PR TITLE
Fix IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint

### LINKED ISSUE #75451: IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint fails on master
**Build scan**:

[7.15.0] https://gradle-enterprise.elastic.co/s/ae6xz7qxyhfze
https://gradle-enterprise.elastic.co/s/vmpplhnu2xmyg

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint" \
  -Dtests.seed=70409EED32B9833E \
  -Dtests.locale=sv-SE \
  -Dtests.timezone=Africa/Mogadishu \
  -Druntime.java=16

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint" \
  -Dtests.seed=70409EED32B9833E \
  -Dtests.locale=sv-SE \
  -Dtests.timezone=Africa/Mogadishu \
  -Druntime.java=16
```

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure history**:

7th  failure this year (~1 failure per month)

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: <16L>
     but: was <22L>
	at __randomizedtesting.SeedInfo.seed([70409EED32B9833E:8A1B13A925BC2776]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint(IndexRecoveryIT.java:1336)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

### PR DESCRIPTION
**Pull request by fcofdez**
In certain scenarios the synced global checkpoint can fall behind
due to a slow disk. The test made the assumption that the global
checkpoint was stable when the global checkpoint was fetched,
this commit adds a new method that waits until the global checkpoint
is stable in all nodes.

Closes #75451

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 1]
```diff
@@ -1795,4 +1798,17 @@ public void testReservesBytesDuringPeerRecoveryPhaseOne() throws Exception {
             .mapToLong(n -> n.getIndices().getStore().getReservedSize().getBytes()).sum(), equalTo(0L));
     }
 
+    private void assertGlobalCheckpointIsStableAndSyncedInAllNodes(String indexName, int shardId) throws Exception {
+        long maxSeqNo = NO_OPS_PERFORMED;
+        for (IndicesService indicesService : internalCluster().getDataNodeInstances(IndicesService.class)) {
+            IndexShard shard = indicesService.getShardOrNull(new ShardId(resolveIndex(indexName), shardId));
+            maxSeqNo = Math.max(maxSeqNo, shard.seqNoStats().getMaxSeqNo());
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:1805]: If we're certain that indexing has finished by this point then the MSN should be equal across all copies (so we can get it from any of them, and maybe assert it's equal everywhere). If we're not certain that indexing has finished then the subsequent `assertBusy()` won't always work either.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 2]
```diff
@@ -1795,4 +1798,17 @@ public void testReservesBytesDuringPeerRecoveryPhaseOne() throws Exception {
             .mapToLong(n -> n.getIndices().getStore().getReservedSize().getBytes()).sum(), equalTo(0L));
     }
 
+    private void assertGlobalCheckpointIsStableAndSyncedInAllNodes(String indexName, int shardId) throws Exception {
+        long maxSeqNo = NO_OPS_PERFORMED;
+        for (IndicesService indicesService : internalCluster().getDataNodeInstances(IndicesService.class)) {
+            IndexShard shard = indicesService.getShardOrNull(new ShardId(resolveIndex(indexName), shardId));
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:1804]: This will be `null` if the node doesn't have a copy of the shard. I think it's ok where it's used right now but I'd rather have a null check anyway to avoid trapping someone in the future.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 3]
```diff
@@ -1795,4 +1798,17 @@ public void testReservesBytesDuringPeerRecoveryPhaseOne() throws Exception {
             .mapToLong(n -> n.getIndices().getStore().getReservedSize().getBytes()).sum(), equalTo(0L));
     }
 
+    private void assertGlobalCheckpointIsStableAndSyncedInAllNodes(String indexName, int shardId) throws Exception {
+        long maxSeqNo = NO_OPS_PERFORMED;
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:1802]: Maybe start the search with something obvious invalid like `Long.MIN_VALUE`?

**Review by DaveCTurner — COMMENTED** [review]
Fix looks sound, I left a few style nits.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 3 above)
Comment (fcofdez) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: Addressed in https://github.com/elastic/elasticsearch/pull/75898/commits/20585d2aacbe324649fa273d039fc309d5ebc816

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 2 above)
Comment (fcofdez) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: Addressed in https://github.com/elastic/elasticsearch/pull/75898/commits/20585d2aacbe324649fa273d039fc309d5ebc816

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 1 above)
Comment (fcofdez) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: Addressed in https://github.com/elastic/elasticsearch/pull/75898/commits/20585d2aacbe324649fa273d039fc309d5ebc816

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
Thanks for the review David!
