### PR TITLE
Fix disabling `allow_leading_wildcard`

### LINKED ISSUE #62267: disabling allow_leading_wildcard not working in 7.9.1 like it is in 7.9.0
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.1 (from official docker image)
**Description of the problem including expected versus actual behavior**:
allow_leading_wildcard false prevent a search in 7.9.0 which runs in 7.9.1
**Steps to reproduce**:
Run this in Kibana Dev tool:
```
PUT testwildcard/_doc/1
{
  "foo": "bar"
}

POST testwildcard/_search
{
  "query": {
    "query_string": {
      "query": "*ar",
      "fields": [
        "foo"
      ],
      "allow_leading_wildcard": false
    }
  }
}
```

In 7.9.1, the document is returned, the output in 7.9.0 (and lower versions) does block the search from running as expected: 
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "Failed to parse query [*ar]",
        "index_uuid" : "UmDK7qc_Sqef6uhk-f0fWA",
        "index" : "testwildcard"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "testwildcard",
        "node" : "zyyjFmpWQnK4NE9VXPn_ng",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "Failed to parse query [*ar]",
          "index_uuid" : "UmDK7qc_Sqef6uhk-f0fWA",
          "index" : "testwildcard",
          "caused_by" : {
            "type" : "parse_exception",
            "reason" : "Cannot parse '*ar': '*' or '?' not allowed as first character in WildcardQuery",
            "caused_by" : {
              "type" : "parse_exception",
              "reason" : "'*' or '?' not allowed as first character in WildcardQuery"
            }
          }
        }
      }
    ]
  },
  "status" : 400
}
```

For ref : 
- [7.9.1 release notes](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/release-notes-7.9.1.html)
- [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) : `analyze_wildcard (Optional, boolean) If true, the query attempts to analyze wildcard terms in the query string. Defaults to false.`

### PR DESCRIPTION
**Pull request by cbuescher**
Disabling the `query_string` queries `allow_leading_wildcard` parameter didn't
work after a change probably introduced in #60959 because the various field types
`wildcardQuery` don't check the leading characters like
QueryParserBase#getWildcardQuery does. This PR adds the missing check also
before calling the field types wildcard generating method.

Closes #62267

### CODE REVIEW

**Comment by cbuescher** [comment]
@markharwood would you mind taking a look since this small regression seems to be connected with one of your recent changes?

File: server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java [hunk 1]
```diff
@@ -681,7 +681,9 @@ private Query getWildcardQuerySingle(String field, String termStr) throws ParseE
                 setAnalyzer(forceAnalyzer);
                 return super.getWildcardQuery(currentFieldType.name(), termStr);
             }
-
+            if (getAllowLeadingWildcard() == false && (termStr.startsWith("*") || termStr.startsWith("?"))) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java:684]: We should add the same check for prefix query too ?

**Review by jimczi — APPROVED** [review]
I left one comment, LGTM otherwise

File: server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java (hunk 1 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java:684]: I'm confused how leading wildcard characters can start a prefix query. Wouldn't that only be "*" and "?", and wouldn't those get resolved as wildcard expressions?

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/search/QueryStringQueryParser.java:684]: I was confused because the QueryParserBase does the check on prefix query too (`field:*`) but we intercept these queries in ES to transform them into an exists query so there's no issue here. Sorry for the confusion.

**Comment by markharwood** [comment]
Sorry, only just got to looking at this.
The fix looks good but I wonder if a future consideration is if the flag is too blunt a tool?
While an admin may want to prevent expensive requests it's the combo of field and query that make something expensive, not query type alone. A `wildcard` field or low-cardinality `keyword` field could cope with leading wildcards fine. Is there more work to be done in scoping this flag?

**Comment by cbuescher** [comment]
> A `wildcard` field or low-cardinality `keyword` field could cope with leading wildcards fine. Is there more work to be done in scoping this flag?

Sounds like an interesting discussion in another issue. To me, in this case disallowing leading wildcards is a way to prevent "bad" user behaviour like leading wildcards in search boxes to take down or slow down clusters. `query_string` tends to get used when user input is passed down to ES unfiltered, which in itself is a questionable practice, but common. I think in this case having a "blunt tool" is desirable since the fields that are queries etc... are usually hard to control, but other cases might exist where this is different. Just my 20c.
