### PR TITLE
Enhance LOOKUP JOIN csv-spec tests to cover more cases and fix several bugs found

### LINKED ISSUE #117702: ESQL: LOOKUP JOIN produces additional null rows
Reproducer:

```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/languages_lookup" -XPUT -d '{\
  "mappings": {\
        "properties": {"language_code": {"type": "keyword"}, "language_name":{"type": "keyword"}}}, "settings": {"index": {"mode": "lookup"}}}'\

$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/languages_lookup/_doc?refresh' -d'{"language_code": "1", "language_name": "English"}'
$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/languages_lookup/_doc?refresh' -d'{"language_code": "2", "language_name": "French"}'
$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test/_doc?refresh' -d'{"x": 1}'
$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test/_doc?refresh' -d'{"x": 3}'

$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '{\
    "query": "FROM test | sort x | limit 10 | eval language_code = x::keyword | lookup join languages_lookup on language_code | keep x, language_code, language_name"\
}'\

       x       | language_code | language_name 
---------------+---------------+---------------
1              |1              |English        
3              |3              |null           
null           |null           |null           
null           |null           |null  
```
Note the 2 additional rows at the bottom. The expected output should only be the 2 first rows.

Interestingly, changing the `limit 10` to `limit 4` doesn't change the query's output - but changing to `limit 3` and `limit 2` shaves off 1 resp. 2 of the wrong rows.

Here's are the optimizer diffs (not sure if they help):
```
[2024-11-28T12:28:32,894][INFO ][o.e.x.e.a.Analyzer       ] [runTask-0] Rule analysis.Analyzer$ResolveTable applied
Keep[[?x, ?language_code, ?language_name]]               = Keep[[?x, ?language_code, ?language_name]]
\_LookupJoin[LEFT OUTER USING [?language_code],[],[],[]] = \_LookupJoin[LEFT OUTER USING [?language_code],[],[],[]]
  |_Eval[[TOSTRING(?x) AS language_code]]                =   |_Eval[[TOSTRING(?x) AS language_code]]
  | \_Limit[10[INTEGER]]                                 =   | \_Limit[10[INTEGER]]
  |   \_OrderBy[[Order[?x,ASC,LAST]]]                    =   |   \_OrderBy[[Order[?x,ASC,LAST]]]
  |     \_UnresolvedRelation[test]                       !   |     \_EsRelation[test][x{f}#123]
  \_UnresolvedRelation[languages_lookup]                 !   \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
                                                        
[2024-11-28T12:28:32,895][INFO ][o.e.x.e.a.Analyzer       ] [runTask-0] Rule analysis.Analyzer$ResolveRefs applied
Keep[[?x, ?language_code, ?language_name]]                                           ! EsqlProject[[x{f}#123, language_code{r}#117, language_name{f}#125]]
\_LookupJoin[LEFT OUTER USING [?language_code],[],[],[]]                             ! \_LookupJoin[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]
  |_Eval[[TOSTRING(?x) AS language_code]]                                            !   |_Eval[[TOSTRING(x{f}#123) AS language_code]]
  | \_Limit[10[INTEGER]]                                                             =   | \_Limit[10[INTEGER]]
  |   \_OrderBy[[Order[?x,ASC,LAST]]]                                                !   |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]
  |     \_EsRelation[test][x{f}#123]                                                 =   |     \_EsRelation[test][x{f}#123]
  \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125] =   \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
                                                                                    
[2024-11-28T12:28:32,895][INFO ][o.e.x.e.a.Analyzer       ] [runTask-0] Rule analysis.Analyzer$AddImplicitLimit applied
EsqlProject[[x{f}#123, language_code{r}#117, language_name{f}#125]]                     ! Limit[10000[INTEGER]]
\_LookupJoin[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]] ! \_EsqlProject[[x{f}#123, language_code{r}#117, language_name{f}#125]]
  |_Eval[[TOSTRING(x{f}#123) AS language_code]]                                         !   \_LookupJoin[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]
  | \_Limit[10[INTEGER]]                                                                !     |_Eval[[TOSTRING(x{f}#123) AS language_code]]
  |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]                                             !     | \_Limit[10[INTEGER]]
  |     \_EsRelation[test][x{f}#123]                                                    !     |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]
  \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]    !     |     \_EsRelation[test][x{f}#123]
                                                                                        !     \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
                                                                                       
[2024-11-28T12:28:32,896][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.SubstituteSurrogatePlans applied
Limit[10000[INTEGER]]                                                                     = Limit[10000[INTEGER]]
\_EsqlProject[[x{f}#123, language_code{r}#117, language_name{f}#125]]                     = \_EsqlProject[[x{f}#123, language_code{r}#117, language_name{f}#125]]
  \_LookupJoin[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]] !   \_Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]
    |_Eval[[TOSTRING(x{f}#123) AS language_code]]                                         !     \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]
    | \_Limit[10[INTEGER]]                                                                !       |_Eval[[TOSTRING(x{f}#123) AS language_code]]
    |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]                                             !       | \_Limit[10[INTEGER]]
    |     \_EsRelation[test][x{f}#123]                                                    !       |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]
    \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]    !       |     \_EsRelation[test][x{f}#123]
                                                                                          !       \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
                                                                                         
[2024-11-28T12:28:32,896][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.CombineProjections applied
Limit[10000[INTEGER]]                                                                    = Limit[10000[INTEGER]]
\_EsqlProject[[x{f}#123, language_code{r}#117, language_name{f}#125]]                    ! \_Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]
  \_Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]                      !   \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]
    \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]    !     |_Eval[[TOSTRING(x{f}#123) AS language_code]]
      |_Eval[[TOSTRING(x{f}#123) AS language_code]]                                      !     | \_Limit[10[INTEGER]]
      | \_Limit[10[INTEGER]]                                                             !     |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]
      |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]                                          !     |     \_EsRelation[test][x{f}#123]
      |     \_EsRelation[test][x{f}#123]                                                 !     \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
      \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125] ! 
                                                                                        
[2024-11-28T12:28:32,897][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.PushDownAndCombineLimits applied
Limit[10000[INTEGER]]                                                                  ! Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]
\_Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]                      ! \_Limit[10000[INTEGER]]
  \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]    =   \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]
    |_Eval[[TOSTRING(x{f}#123) AS language_code]]                                      =     |_Eval[[TOSTRING(x{f}#123) AS language_code]]
    | \_Limit[10[INTEGER]]                                                             =     | \_Limit[10[INTEGER]]
    |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]                                          =     |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]
    |     \_EsRelation[test][x{f}#123]                                                 =     |     \_EsRelation[test][x{f}#123]
    \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125] =     \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
                                                                                      
[2024-11-28T12:28:32,898][INFO ][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.ReplaceLimitAndSortAsTopN applied
Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]                        = Project[[x{f}#123, language_code{r}#117, language_name{f}#125]]
\_Limit[10000[INTEGER]]                                                                = \_Limit[10000[INTEGER]]
  \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]    =   \_Join[LEFT,[language_code{r}#117],[language_code{r}#117],[language_code{f}#124]]
    |_Eval[[TOSTRING(x{f}#123) AS language_code]]                                      =     |_Eval[[TOSTRING(x{f}#123) AS language_code]]
    | \_Limit[10[INTEGER]]                                                             !     | \_TopN[[Order[x{f}#123,ASC,LAST]],10[INTEGER]]
    |   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]                                          !     |   \_EsRelation[test][x{f}#123]
    |     \_EsRelation[test][x{f}#123]                                                 !     \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]
    \_EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125] ! 
                                                                                      
[2024-11-28T12:28:32,898][INFO ][o.e.x.e.o.PhysicalPlanOptimizer] [runTask-0] Rule physical.ProjectAwayColumns applied
ProjectExec[[x{f}#123, language_code{r}#117, language_name{f}#125]]                                                                  = ProjectExec[[x{f}#123, language_code{r}#117, language_name{f}#125]]
\_LimitExec[10000[INTEGER]]                                                                                                          = \_LimitExec[10000[INTEGER]]
  \_LookupJoinExec[[language_code{r}#117],[language_code{r}#117],[language_code{f}#124],[x{f}#123, language_code{r}#117, language_na =   \_LookupJoinExec[[language_code{r}#117],[language_code{r}#117],[language_code{f}#124],[x{f}#123, language_code{r}#117, language_na
me{f}#125]]                                                                                                                          = me{f}#125]]
    |_EvalExec[[TOSTRING(x{f}#123) AS language_code]]                                                                                =     |_EvalExec[[TOSTRING(x{f}#123) AS language_code]]
    | \_TopNExec[[Order[x{f}#123,ASC,LAST]],10[INTEGER],null]                                                                        =     | \_TopNExec[[Order[x{f}#123,ASC,LAST]],10[INTEGER],null]
    |   \_ExchangeExec[[],false]                                                                                                     !     |   \_ExchangeExec[[x{f}#123],false]
    |     \_FragmentExec[filter=null, estimatedRowSize=0, reducer=[], fragment=[<>                                                   =     |     \_FragmentExec[filter=null, estimatedRowSize=0, reducer=[], fragment=[<>
TopN[[Order[x{f}#123,ASC,LAST]],10[INTEGER]]                                                                                         ! Project[[x{f}#123]]
\_EsRelation[test][x{f}#123]<>]]                                                                                                     ! \_TopN[[Order[x{f}#123,ASC,LAST]],10[INTEGER]]
    \_FragmentExec[filter=null, estimatedRowSize=0, reducer=[], fragment=[<>                                                         !   \_EsRelation[test][x{f}#123]<>]]
EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]<>]]                                                 !     \_FragmentExec[filter=null, estimatedRowSize=0, reducer=[], fragment=[<>
                                                                                                                                     ! EsRelation[languages_lookup][LOOKUP][language_code{f}#124, language_name{f}#125]<>]]
                                                                                                                                    
[2024-11-28T12:28:32,899][INFO ][o.e.x.e.o.LocalPhysicalPlanOptimizer] [runTask-0] Rule local.ReplaceSourceAttributes applied
EsSourceExec[languages_lookup][language_code{f}#124, language_name{f}#125] ! EsQueryExec[languages_lookup], indexMode[lookup], query[][_doc{f}#126], limit[], sort[] estimatedRowSize[null]
                                                                          
[2024-11-28T12:28:32,902][INFO ][o.e.x.e.o.LocalLogicalPlanOptimizer] [runTask-0] Rule local.ReplaceTopNWithLimitAndSort applied
Project[[x{f}#123]]                            = Project[[x{f}#123]]
\_TopN[[Order[x{f}#123,ASC,LAST]],10[INTEGER]] ! \_Limit[10[INTEGER]]
  \_EsRelation[test][x{f}#123]                 !   \_OrderBy[[Order[x{f}#123,ASC,LAST]]]
                                               !     \_EsRelation[test][x{f}#123]
                                              
[2024-11-28T12:28:32,903][INFO ][o.e.x.e.o.LocalLogicalPlanOptimizer] [runTask-0] Rule logical.ReplaceLimitAndSortAsTopN applied
Project[[x{f}#123]]                     = Project[[x{f}#123]]
\_Limit[10[INTEGER]]                    ! \_TopN[[Order[x{f}#123,ASC,LAST]],10[INTEGER]]
  \_OrderBy[[Order[x{f}#123,ASC,LAST]]] !   \_EsRelation[test][x{f}#123]
    \_EsRelation[test][x{f}#123]        ! 
                                       
[2024-11-28T12:28:32,903][INFO ][o.e.x.e.o.LocalPhysicalPlanOptimizer] [runTask-0] Rule local.ReplaceSourceAttributes applied
ProjectExec[[x{f}#123]]                                 = ProjectExec[[x{f}#123]]
\_TopNExec[[Order[x{f}#123,ASC,LAST]],10[INTEGER],null] = \_TopNExec[[Order[x{f}#123,ASC,LAST]],10[INTEGER],null]
  \_EsSourceExec[test][x{f}#123]                        !   \_EsQueryExec[test], indexMode[standard], query[][_doc{f}#127], limit[], sort[] estimatedRowSize[null]
                                                       
[2024-11-28T12:28:32,904][INFO ][o.e.x.e.o.LocalPhysicalPlanOptimizer] [runTask-0] Rule local.PushTopNToSource applied
ProjectExec[[x{f}#123]]                                                                                  = ProjectExec[[x{f}#123]]
\_TopNExec[[Order[x{f}#123,ASC,LAST]],10[INTEGER],null]                                                  ! \_EsQueryExec[test], indexMode[standard], query[][_doc{f}#127], limit[10], sort[[FieldSort[field=x{f}#123, direction=ASC, nulls=LAST]]] estimatedRowSize[null]
  \_EsQueryExec[test], indexMode[standard], query[][_doc{f}#127], limit[], sort[] estimatedRowSize[null] ! 
                                                                                                        
[2024-11-28T12:28:32,904][INFO ][o.e.x.e.o.LocalPhysicalPlanOptimizer] [runTask-0] Rule local.InsertFieldExtraction applied
ProjectExec[[x{f}#123]]                                                                                                                                        = ProjectExec[[x{f}#123]]
\_EsQueryExec[test], indexMode[standard], query[][_doc{f}#127], limit[10], sort[[FieldSort[field=x{f}#123, direction=ASC, nulls=LAST]]] estimatedRowSize[null] ! \_FieldExtractExec[x{f}#123]<[]>
                                                                                                                                                               !   \_EsQueryExec[test], indexMode[standard], query[][_doc{f}#127], limit[10], sort[[FieldSort[field=x{f}#123, direction=ASC, nulls=LAST]]] estimatedRowSize[null]
                                                                                                       
```

### PR DESCRIPTION
**Pull request by craigtaverner**
Adds several more tests to lookup-join.csv-spec, and fixes the following bugs:

* FieldCaps on right hand side should ignore fieldNames method and just use "*" because currently the fieldNames search cannot handle lookup fields with aliases (should be fixed in a followup PR).
* Stop using the lookup index in the ComputeService (so we don’t get both indices data coming in from the left, and other weird behaviour).
* Ignore failing SearchStats checks on fields from the right hand side in the logical planner (so it does not plan EVAL field = null for all right hand fields). This should be fixed properly with the correct updates to TransportSearchShardsAction (or rather to making multiple use of that for each branch of the execution model).

Fixes #117702

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 1]
```diff
@@ -261,6 +268,44 @@ public void execute(
...
+        // TODO this only works for LEFT join, so we still need to support RIGHT join
+        physicalPlan.forEachDown(
+            FragmentExec.class,
+            fragmentExec -> fragmentExec.fragment()
+                .forEachDown(
+                    Join.class,
+                    join -> join.right().forEachDown(EsRelation.class, esRelation -> lookupIndexNames.add(esRelation.index().name()))
+                )
+        );
+        return lookupIndexNames;
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:306]: Combine the iterations into one.

**Review by costin — APPROVED** [review]
LGTM. There are a number of culprits but the PR nicely avoids them while adding minimal changes.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/LookupFromIndexService.java [hunk 2]
```diff
@@ -78,9 +79,19 @@ protected TransportRequest transportRequest(LookupFromIndexService.Request reque
     @Override
     protected QueryList queryList(TransportRequest request, SearchExecutionContext context, Block inputBlock, DataType inputDataType) {
         MappedFieldType fieldType = context.getFieldType(request.matchField);
+        validateTypes(request.inputDataType, fieldType);
         return termQueryList(fieldType, context, inputBlock, inputDataType);
     }
 
+    private static void validateTypes(DataType inputDataType, MappedFieldType fieldType) {
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/LookupFromIndexService.java:86]: Not so much a bug-fix as early error generation. This could be made less strict going forward, but we thought to start strict and then open later if appropriate.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java [hunk 3]
```diff
@@ -56,10 +58,13 @@ else if (plan instanceof Project project) {
             var projections = project.projections();
             List<NamedExpression> newProjections = new ArrayList<>(projections.size());
             Map<DataType, Alias> nullLiteral = Maps.newLinkedHashMapWithExpectedSize(DataType.types().size());
+            AttributeSet joinAttributes = joinAttributes(project);
 
             for (NamedExpression projection : projections) {
                 // Do not use the attribute name, this can deviate from the field name for union types.
-                if (projection instanceof FieldAttribute f && stats.exists(f.fieldName()) == false) {
+                if (projection instanceof FieldAttribute f && stats.exists(f.fieldName()) == false && joinAttributes.contains(f) == false) {
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java:65]: This is a temporary fix to the fact that SearchStats can currently only contain all stats for the main `FROM index` part of the query. We need a full-stack change of context to support multiple SearchStats.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java [hunk 4]
```diff
@@ -117,12 +119,17 @@ public static String[] planOriginalIndices(PhysicalPlan plan) {
         var indices = new LinkedHashSet<String>();
         plan.forEachUp(
             FragmentExec.class,
-            f -> f.fragment()
-                .forEachUp(EsRelation.class, r -> indices.addAll(asList(Strings.commaDelimitedListToStringArray(r.index().name()))))
+            f -> f.fragment().forEachUp(EsRelation.class, r -> addOriginalIndexIfNotLookup(indices, r.index()))
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:122]: Part of the fix to remove join indexes from the left-hand-side of the join (ie. stop mixing left and right)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 5]
```diff
@@ -160,9 +165,11 @@ public void execute(
         Map<String, OriginalIndices> clusterToConcreteIndices = transportService.getRemoteClusterService()
             .groupIndices(SearchRequest.DEFAULT_INDICES_OPTIONS, PlannerUtils.planConcreteIndices(physicalPlan).toArray(String[]::new));
         QueryPragmas queryPragmas = configuration.pragmas();
+        Set<String> lookupIndexNames = findLookupIndexNames(physicalPlan);
+        Set<String> concreteIndexNames = selectConcreteIndices(clusterToConcreteIndices, lookupIndexNames);
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:169]: Part of the fix to remove join indexes from the left-hand-side of the join (ie. stop mixing left and right)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 6]
```diff
@@ -313,7 +313,7 @@ private <T> void preAnalyze(
             // First resolve the lookup indices, then the main indices
             preAnalyzeLookupIndices(
                 preAnalysis.lookupIndices,
-                fieldNames,
+                Set.of("*"), // Current LOOKUP JOIN syntax does not allow for field selection
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:316]: Temporary fix to work around a bug in fieldNames for lookup-join when there are aliases before, and keep after the lookup.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/InsertFieldExtraction.java [hunk 7]
```diff
@@ -102,15 +101,18 @@ public PhysicalPlan apply(PhysicalPlan plan) {
 
     private static Set<Attribute> missingAttributes(PhysicalPlan p) {
         var missing = new LinkedHashSet<Attribute>();
-        var inputSet = p.inputSet();
+        var input = new AttributeSet(p.inputSet());
 
-        // TODO: We need to extract whatever fields are missing from the left hand side.
-        // skip the lookup join since the right side is always materialized and a projection
+        // For LOOKUP JOIN we only need field-extraction on left fields used to match, since the right side is always materialized
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/InsertFieldExtraction.java:105]: The field extraction is implicitly done inside the `LookupFromIndexService`. I agree it'd be nicer to make the field extraction visible in the physical plan; currently, that'd have no benefit, though, because we cannot really materialize fields late - all looked up fields need to be extracted inside the `LookupFromIndexService`.

It'd require a fundamental change of the execution to extract additional fields _after_ the execution of the lookup join.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/InsertFieldExtraction.java [hunk 8]
```diff
@@ -102,15 +100,18 @@ public PhysicalPlan apply(PhysicalPlan plan) {
 
     private static Set<Attribute> missingAttributes(PhysicalPlan p) {
         var missing = new LinkedHashSet<Attribute>();
-        var inputSet = p.inputSet();
+        var input = p.inputSet();
 
-        // TODO: We need to extract whatever fields are missing from the left hand side.
-        // skip the lookup join since the right side is always materialized and a projection
+        // For LOOKUP JOIN we only need field-extraction on left fields used to match, since the right side is always materialized
         if (p instanceof LookupJoinExec join) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/InsertFieldExtraction.java:106]: As discussed, I think this can be simplified by just using `p.references` instead of having a special case for lookup joins, and otherwise doing something on `p.forEacExpression(...)`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java (hunk 6 above)
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:316]: I think the comment is insufficient; I believe this is a good hack but should be improved later; in a query like
```
FROM idx | LOOKUP JOIN lookup_idx ON lookup_field | KEEP another_lookup_field
```
we do not have to ask for all existing field names. We just need `another_lookup_field`.

In fact, I think this will make it so that we ask the `LookupFromIndexService` to fetch **all** fields from the index, meaning that the performance of this operation will depend on the number of fields in the lookup index. In scenarios where that index has, say, 6000 fields (not completely unheard of), that may be a serious performance drag and could cause memory issues.

To be more precise, I think we'll have to augment`fieldNames`. We should be able to walk the tree from the top, _stopping_ at the first `LOOKUP JOIN` we see - and then determining that the missing fields _so far_ are the only candidates that may come from the lookup index. This means that the output of `fieldNames` shouldn't be a single `Set<String>` - but, instead, a `Set<String>` for the main index and a `List<Set<String>>` corresponding to the missing fields we might obtain from the lookup indices.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 9]
```diff
@@ -259,6 +266,42 @@ public void execute(
...
+                    concreteIndexNames.add(index);
+                }
+            }
+        });
+        return concreteIndexNames;
+    }
+
+    private Set<String> findLookupIndexNames(PhysicalPlan physicalPlan) {
+        Set<String> lookupIndexNames = new HashSet<>();
+        // When planning JOIN on the coordinator node: "LookupJoinExec.lookup()->FragmentExec.fragment()->EsRelation.index()"
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:283]: Super useful comments!

**Review by alex-spies — COMMENTED** [review]
Thanks @craigtaverner , this is a very, very nice PR.

I added some late comments to have a reference for follow-ups.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 9 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:283]: I actually ran a test that checked which of the 19 queries hit which of these two patterns, just to be sure, and the trend was pretty clear.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 10]
```diff
@@ -85,3 +84,208 @@ emp_no:integer | language_code:integer | language_name:keyword | language_code_x
...
+
+left:keyword | client_ip:keyword | right:keyword | env:keyword
+left         | 172.21.0.5        | right         | Development
+;
+
+lookupIPFromRowWithShadowingKeep
+required_capability: join_lookup_v4
+
+ROW left = "left", client_ip = "172.21.0.5", env = "env", right = "right"
+| EVAL client_ip = client_ip::keyword
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:114]: Just for symmetry with the other tests. I had a set of tests for IP and a set for KEYWORD, and duplicated them.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/LookupFromIndexService.java [hunk 11]
```diff
@@ -78,9 +79,19 @@ protected TransportRequest transportRequest(LookupFromIndexService.Request reque
...
+        // TODO: consider supporting implicit type conversion as done in ENRICH for some types
+        if (fieldType.typeName().equals(inputDataType.typeName()) == false) {
+            throw new EsqlIllegalArgumentException(
+                "LOOKUP JOIN match and input types are incompatible: match[" + fieldType.typeName() + "], input[" + inputDataType + "]"
+            );
+        }
+    }
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/LookupFromIndexService.java:93]: Yes, the same is true for ENRICH. And for ENRICH we have both validation during planning and at this point, and the planning one is less comprehensive because less is known at that point. We should check what is known for JOIN; and if we can move this entirely to planning.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 12]
```diff
@@ -565,6 +565,7 @@ private PhysicalOperation planHashJoin(HashJoinExec join, LocalExecutionPlannerC
 
     private PhysicalOperation planLookupJoin(LookupJoinExec join, LocalExecutionPlannerContext context) {
         PhysicalOperation source = plan(join.left(), context);
+        // TODO: The source builder includes incoming fields including the ones we're going to drop
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:568]: This comment was added very early on during discussions with you. We added it as a reminder. Could it be that it went stale immediately, since you did your fixes? This should be verified.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java:65]: I did add a line to the PR description that we would like to fix this more correctly, be getting SearchStats for join indexes also. I did investigate adding that to the ComputeService, but it was not trivial, so I went for this hack instead.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java (hunk 6 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:316]: The comment in the followup work is:
>EsqlSession.fieldNames does not handle lookup references that are also mentioned in aliases (erases them)

So we want to fix this bug, and I have a reasonable idea how.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 13]
```diff
@@ -85,3 +84,208 @@ emp_no:integer | language_code:integer | language_name:keyword | language_code_x
...
+2023-10-23T12:27:28.948Z | 172.21.2.113 | 2764889             | Connected to 10.1.0.2 | Success
+2023-10-23T12:15:03.360Z | 172.21.2.162 | 3450233             | Connected to 10.1.0.3 | Success
+;
+
+lookupMessageFromIndexKeep
+required_capability: join_lookup_v4
+
+FROM sample_data
+| LOOKUP JOIN message_types_lookup ON message
+| KEEP @timestamp, client_ip, event_duration, message, type
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:249]: I'll open a PR with more tests.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:568]: It's always been stale, I just didn't understand the physical operators enough at the time :D

If you look [here](https://github.com/elastic/elasticsearch/blob/f2addbc69a2aa7fb512c1d5ca9a839f5fc7f5134/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/LookupFromIndexOperator.java#L123), you can see that the corresponding operator will only ever append blocks from the right.

I thought the layout was wrong because it would not take into account shadowing. But that's actually fine! Shadowing is a logical concept, the physical operators don't care. They only care about channels and which data is present in which. And for this, the layout constructed here appears to be very correct: it has the channels from the left hand side and additionally more channels slapped onto it from the right, containing the looked up fields.
