### PR TITLE
Fix `range` queries on `_type` field for singe type indices

### LINKED ISSUE #31476: receive _type not indexed error, but documentation says _type is always indexed
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.3.0, Build: default/zip/424e937/2018-06-11T23:38:03.357887Z, JVM: 1.8.0_171

**Plugins installed**: None

**JVM version** (`java -version`):

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux tony-laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I run a query on _type field and received HTTP 400 for "cannot search on field [_type] since it is not indexed".

According to the documentation, "The _type field is indexed in order to make searching by type name fast." I expect to receive a correct result not an error.

**Steps to reproduce**:

Create mappings:

```
PUT /test_schema_1

{
  "settings":{
    "index":{
      "number_of_shards":1,
      "number_of_replicas":0
    }
  }
}
```

```
PUT /test_schema_1/_mapping/test_table_1

{"test_table_1":{"properties":{"text_field":{"type":"text"}}}}
```

Query:

```
POST /test_schema_1/test_table_1/_search?size=4000&amp;preference=_shards%3A0&amp;scroll=300000ms

{
  "from" : 0,
  "size" : 4000,
  "query" : {
    "range" : {
      "_type" : {
        "from" : " ",
        "to" : null,
        "include_lower" : false,
        "include_upper" : true,
        "boost" : 1.0
      }
    }
  }
}
```

Response:

```
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "failed to create query: {\n  \"range\" : {\n    \"_type\" : {\n      \"from\" : \" \",\n      \"to\" : null,\n      \"include_lower\" : false,\n      \"include_upper\" : true,\n      \"boost\" : 1.0\n    }\n  }\n}",
                "index_uuid": "B6LluE64RhqZhIoVufFXSQ",
                "index": "test_schema_1"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "test_schema_1",
                "node": "7RkRZhIBQPKc43Lyr6ZY4A",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "failed to create query: {\n  \"range\" : {\n    \"_type\" : {\n      \"from\" : \" \",\n      \"to\" : null,\n      \"include_lower\" : false,\n      \"include_upper\" : true,\n      \"boost\" : 1.0\n    }\n  }\n}",
                    "index_uuid": "B6LluE64RhqZhIoVufFXSQ",
                    "index": "test_schema_1",
                    "caused_by": {
                        "type": "illegal_argument_exception",
                        "reason": "Cannot search on field [_type] since it is not indexed."
                    }
                }
            }
        ]
    },
    "status": 400
}
```

I am aware that `_type` is being deprecated. Should the documentation be updated to reflect that `_type` is no longer indexed? Or is there a bug?

### PR DESCRIPTION
**Pull request by cbuescher**
With the introduction of single types in 6.x, the `_type` field is no longer
indexed, which leads to certain queries that were working before throw errors
now. One such query is the `range` query, that, if performed on a single typer
index, currently throws an IAE since the field is not indexed.
This change adds special treatment for this case in the TypeFieldMapper,
comparing the range queries lower and upper bound to the one existing type and
either returns a MatchAllDocs or a MatchNoDocs query.

Relates to #31632
Closes #31476

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java [hunk 1]
```diff
@@ -154,6 +159,33 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
...
+                return new TermRangeQuery(name(), lowerTerm == null ? null : indexedValueForSearch(lowerTerm),
+                        upperTerm == null ? null : indexedValueForSearch(upperTerm), includeLower, includeUpper);
+            } else {
+                // this means the index has a single type and the type field is implicit
+                DEPRECATION_LOGGER.deprecatedAndMaybeLog("range_single_type",
+                        "Running [range] query on [_type] field for an index with a single type. As types are deprecated, this functionality will be removed in future releases.");
+                String type = context.getMapperService().documentMapper().type();
+                Query result = new MatchAllDocsQuery();
+                if (lowerTerm != null && lowerTerm instanceof BytesRef) {
+                    int comp = type.compareTo(((BytesRef) lowerTerm).utf8ToString());
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: Not sure if there is a better way of comparing BytesRef instances, maybe taking into account different lexicographical orderings?

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java [hunk 2]
```diff
@@ -154,6 +159,33 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
...
 
+        @Override
+        public Query rangeQuery(Object lowerTerm, Object upperTerm, boolean includeLower, boolean includeUpper, QueryShardContext context) {
+            if (hasDocValues()) {
+                return new TermRangeQuery(name(), lowerTerm == null ? null : indexedValueForSearch(lowerTerm),
+                        upperTerm == null ? null : indexedValueForSearch(upperTerm), includeLower, includeUpper);
+            } else {
+                // this means the index has a single type and the type field is implicit
+                DEPRECATION_LOGGER.deprecatedAndMaybeLog("range_single_type",
+                        "Running [range] query on [_type] field for an index with a single type. As types are deprecated, this functionality will be removed in future releases.");
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: Not sure if we really need the deprecation, but since it was mentioned at some point I added it for discussion purposes.

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java (hunk 1 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: BytesRef implements `Comparable`, so you should be able to do something like:
```
int comp = lowerTerm.compareTo(new BytesRef(type));
```

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java [hunk 3]
```diff
@@ -154,6 +159,33 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
             }
         }
 
+        @Override
+        public Query rangeQuery(Object lowerTerm, Object upperTerm, boolean includeLower, boolean includeUpper, QueryShardContext context) {
+            if (hasDocValues()) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: we don't need this `if` block, do we? All 6.x and 7.x indices have a single type.

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java [hunk 4]
```diff
@@ -154,6 +159,33 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
...
+                return new TermRangeQuery(name(), lowerTerm == null ? null : indexedValueForSearch(lowerTerm),
+                        upperTerm == null ? null : indexedValueForSearch(upperTerm), includeLower, includeUpper);
+            } else {
+                // this means the index has a single type and the type field is implicit
+                DEPRECATION_LOGGER.deprecatedAndMaybeLog("range_single_type",
+                        "Running [range] query on [_type] field for an index with a single type. As types are deprecated, this functionality will be removed in future releases.");
+                String type = context.getMapperService().documentMapper().type();
+                Query result = new MatchAllDocsQuery();
+                if (lowerTerm != null && lowerTerm instanceof BytesRef) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: we shouldn't be lenient in case `lowerTerm` doesnt't implement BytesRef

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java [hunk 5]
```diff
@@ -154,6 +159,33 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
...
+                    int comp = type.compareTo(((BytesRef) lowerTerm).utf8ToString());
+                    if (comp < 0 || (comp == 0 && includeLower == false)) {
+                        result = new MatchNoDocsQuery("[_type] was less then lower bound of range");
+                    }
+                }
+                if (upperTerm != null && upperTerm instanceof BytesRef) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: we shouldn't be lenient in case `upperTerm` doesnt't implement BytesRef

**Review by jpountz — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java (hunk 3 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: Don't we still support multi-type indices that have been created in 5.x on 6.x? I will remove this for the PR against master but I think we need it for 6.x in that case. Can you confirm?

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java (hunk 4 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: I was wondering the same, do we want to throw an IAE in those cases?

**Comment by romseygeek** [comment]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@jpountz are you also okay with this change now? Still waiting for green CI to merge, but I left one question about backporting to 6.4. In that case we still need the support for multi-type indices that I deleted in this PR against master, no?

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java (hunk 3 above)
Comment (jpountz) [reply server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: :+1:

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java (hunk 4 above)
Comment (jpountz) [reply server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: I would call `indexedValueForSearch`.

File: server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java [hunk 6]
```diff
@@ -154,6 +158,36 @@ public Query termsQuery(List<?> values, QueryShardContext context) {
...
+        @Override
+        public Query rangeQuery(Object lowerTerm, Object upperTerm, boolean includeLower, boolean includeUpper, QueryShardContext context) {
+            DEPRECATION_LOGGER.deprecatedAndMaybeLog("range_single_type",
+                    "Running [range] query on [_type] field for an index with a single type. As types are deprecated, this functionality will be removed in future releases.");
+            if ((lowerTerm != null && lowerTerm instanceof BytesRef == false)) {
+                throw new IllegalArgumentException("lower term should be BytesRef but was: " + lowerTerm.getClass().getName());
+            }
+            if ((upperTerm != null && upperTerm instanceof BytesRef == false)) {
+                throw new IllegalArgumentException("upper term should be BytesRef but was: " + upperTerm.getClass().getName());
+            }
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java]: Conversion to bytesref is done elsewhere with `indexedValueForSearch`. I'm unsure of the impact of rejecting anything but bytesrefs.

**Review by jpountz — APPROVED** [review]

**Review by jpountz — APPROVED** [review]
