### PR TITLE
Fix NullPointerException in SystemIndexMetadataUpgradeService hidden alias handling

### LINKED ISSUE #81411: [CI] FullClusterRestartIT testSecurityNativeRealm failing
This seems to be related to some unexpected deprecation warning related to system indices, that's why I tagged it as Core/Infra.

**Build scan:**
https://gradle-enterprise.elastic.co/s/cnwwh5dnseay4/tests/:x-pack:qa:full-cluster-restart:v7.9.2%23upgradedClusterTest/org.elasticsearch.xpack.restart.FullClusterRestartIT/testSecurityNativeRealm

**Reproduction line:**
`./gradlew ':x-pack:qa:full-cluster-restart:v7.9.2#upgradedClusterTest' -Dtests.class="org.elasticsearch.xpack.restart.FullClusterRestartIT" -Dtests.method="testSecurityNativeRealm" -Dtests.seed=AEA01868BA18CBDC -Dtests.bwc=true -Dtests.locale=el-GR -Dtests.timezone=EST5EDT -Druntime.java=17`

**Applicable branches:**
master, 8.0

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.restart.FullClusterRestartIT&tests.test=testSecurityNativeRealm

**Failure excerpt:**
```
org.elasticsearch.client.WarningFailureException: method [GET], host [http://127.0.0.1:45353], URI [/.security/_settings/index.format], status line [HTTP/1.1 200 OK]
{".security-7":{"settings":{"index":{"format":"6"}}}}

  at __randomizedtesting.SeedInfo.seed([AEA01868BA18CBDC:2558E43B80AE6BC4]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:331)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:301)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276)
  at org.elasticsearch.xpack.restart.FullClusterRestartIT.testSecurityNativeRealm(FullClusterRestartIT.java:112)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by williamrandolph**
There was a mysterious failure in an upgrade test. Examining the logs, I found a NullPointerException that wasn't revealed in the test failure message. Fixing the NPE fixed the test.

Should the `AliasMetadata#isHidden` method be nullable? I can't remember why it was written that way, but I can dig if there are any concerns about this fix.

Fixes #81411

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/SystemIndexMetadataUpgradeService.java [hunk 1]
```diff
@@ -106,9 +107,13 @@ public ClusterState execute(ClusterState currentState) throws Exception {
...
                     }
-                    if (isSystem && indexMetadata.getAliases().values().stream().anyMatch(a -> a.isHidden() == false)) {
+                    if (isSystem
+                        && indexMetadata.getAliases()
+                            .values()
+                            .stream()
+                            .anyMatch(a -> Objects.nonNull(a.isHidden()) && a.isHidden() == false)) {
                         for (AliasMetadata aliasMetadata : indexMetadata.getAliases().values()) {
-                            if (aliasMetadata.isHidden() == false) {
+                            if (Objects.nonNull(aliasMetadata.isHidden()) && aliasMetadata.isHidden() == false) {
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/cluster/metadata/SystemIndexMetadataUpgradeService.java:116]: another way to write this, without a compound expression, would be:

```
if (Boolean.FALSE.equals(aliasMetadata.isHidden())) {
```

**Review by rjernst — APPROVED** [review]
I don't know why AliasMetadata allows isHidden to be null, but this change does look like it should protect from null here.

**Review by grcevski — APPROVED** [review]
LGTM!
