### PR TITLE
Fix SearchableSnapshotsLicenseIntegTests.testShardAllocationOnInvalidLicense

### LINKED ISSUE #72329: SearchableSnapshotsLicenseIntegTests.testShardAllocationOnInvalidLicense fails when recreating its license
**Build scan**:
https://gradle-enterprise.elastic.co/s/2bpdnr5jqux6y/tests

**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsLicenseIntegTests.testShardAllocationOnInvalidLicense" -Dtests.seed=5470D1E16498B727 -Dtests.locale=be -Dtests.timezone=Canada/Pacific -Druntime.java=11
```
**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**:
https://build-stats.elastic.co/goto/d7017643bd9139fb127d1f231d6d81d2

image

**Failure excerpt**:

```
java.lang.AssertionError: expected:<UPGRADED_TO_TRIAL> but was:<TRIAL_ALREADY_ACTIVATED> |  
...
at __randomizedtesting.SeedInfo.seed([5470D1E16498B727:D8600A79DC686337]:0)
```

### PR DESCRIPTION
**Pull request by tlrx**
This test fails sometimes on CI (see #72329) when recreating the license. It's not clear to me why that happens but I suspect batched cluster state updates, so this pull request adds some waiting points in the test.

Closes #72329

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsLicenseIntegTests.java [hunk 1]
```diff
@@ -89,6 +89,9 @@ public void createAndMountSearchableSnapshot() throws Exception {
 
         assertAcked(client().execute(DeleteLicenseAction.INSTANCE, new DeleteLicenseRequest()).get());
         assertAcked(client().execute(PostStartBasicAction.INSTANCE, new PostStartBasicRequest()).get());
+
+        ensureClusterSizeConsistency();
```
Comment (original-brownbear) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsLicenseIntegTests.java:93]: NIT: I think we can do it in one line with `ensureStableCluster(cluster().size())`? That seems like it's all we need here? Looks like this is a retry on the master node request I guess? (though there's no master fail-over, but maybe a connection got dropped for some reason?) ... That's my best guess :)

**Review by original-brownbear — APPROVED** [review]
LGTM

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsLicenseIntegTests.java (hunk 1 above)
Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsLicenseIntegTests.java:93]: I merged as is, I wanted to ensure no pending tasks on all nodes with the same cluster state everywhere. 

And yes, retries might explain this. We'll see if that happens again

**Comment by tlrx** [comment]
Thanks Armin
