### PR TITLE
Only create MapperService in SyntheticSourceIndexSettingsProvider when required

### LINKED ISSUE #116070: Improve SyntheticSourceIndexSettingsProvider to not always create a MapperService.
A regression was detected in `nightly-elastic/logs-many-shards-quantitative-indexing-throughput-1` visualization in [the many shards nightly benchmark](https://elasticsearch-benchmarks.elastic.co/#tracks/many-shards-quantitative/nightly/default/90d). Investigation has indicated that the decrease in throughput was caused when logsdb was enabled by default. This mainly keeps track of index / data stream creation.

We should be able to add an optimization that avoids creating a new mapper service when we can figure out that synthetic source is used by just looking in the index settings (the `index.mode` and `index.mapping.source.mode` index settings). Only if the deprecated source field mapper's `mode` attribute is used we have to fall back to creating mapper service.

### PR DESCRIPTION
**Pull request by martijnvg**
In case the index.mapping.source.mode is specified, there is no need to create a mapper service to determine whether synthetic source is used.

In case of logsdb/tsdb there is also no reason to create a mapper service. If _source.mode attribute is specified, then it doesn't really matter whether what its value is for the SyntheticSourceIndexSettingsProvider. If it is synthetic, then that is the same as the index mode's default source mode. If it is stored, we just will add set `index.mapping.source.mode` to `stored`, which has no effect. And disabled source mode isn't allowed in the case of logsdb and tsdb.

Closes #116070

### CODE REVIEW

File: x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java [hunk 1]
```diff
@@ -101,6 +101,18 @@ boolean newIndexHasSyntheticSourceUsage(
...
+                || indexMode == IndexMode.TIME_SERIES) {
+                // in case when index mode is either tsdb or logsdb and only _source.mode attribute is specified, then the default could
+                // be wrong. However, it doesn't really matter, because if it is set to stored, then adding index.mapping.source.mode has
+                // no effect. And _source.mode can't be set to disabled, because that isn't allowed with logsdb/tsdb.
+                var sourceMode = SourceFieldMapper.INDEX_MAPPER_SOURCE_MODE_SETTING.get(tmpIndexMetadata.getSettings());
+                return sourceMode == SourceFieldMapper.Mode.SYNTHETIC;
+            }
+
+            // TODO: remove this when _source.mode attribute has been removed:
             try (var mapperService = mapperServiceFactory.apply(tmpIndexMetadata)) {
```
Comment (martijnvg) [inline x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java:116]: Note that an alternative to use mapper service is manually parsing mapping of each template and see whether there is a `_source.mode attribute` that is set to `synthetic`. However this is error prone.

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/part-2

File: x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java [hunk 2]
```diff
@@ -101,6 +101,18 @@ boolean newIndexHasSyntheticSourceUsage(
 
         try {
             var tmpIndexMetadata = buildIndexMetadataForMapperService(indexName, templateIndexMode, indexTemplateAndCreateRequestSettings);
+            var indexMode = tmpIndexMetadata.getIndexMode();
+            if (SourceFieldMapper.INDEX_MAPPER_SOURCE_MODE_SETTING.exists(tmpIndexMetadata.getSettings())
+                || indexMode == IndexMode.LOGSDB
+                || indexMode == IndexMode.TIME_SERIES) {
+                // in case when index mode is either tsdb or logsdb and only _source.mode attribute is specified, then the default could
+                // be wrong. However, it doesn't really matter, because if it is set to stored, then adding index.mapping.source.mode has
+                // no effect. And _source.mode can't be set to disabled, because that isn't allowed with logsdb/tsdb.
```
Comment (kkrik-es) [inline x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java:110]: `However, it doesn't really matter, because if it is set to stored, then adding index.mapping.source.mode has no effect.`

Mind explaining this? What happens if indexMode is LOGSDB and _source.mode is 'stored', if we don't read the latter?

Comment (kkrik-es) [reply x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java:110]: I see, failing to inject `stored` here won't make a difference. Maybe clarify in the comment.

File: x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java [hunk 3]
```diff
@@ -101,6 +101,18 @@ boolean newIndexHasSyntheticSourceUsage(
...
+                var sourceMode = SourceFieldMapper.INDEX_MAPPER_SOURCE_MODE_SETTING.get(tmpIndexMetadata.getSettings());
+                return sourceMode == SourceFieldMapper.Mode.SYNTHETIC;
```
Comment (kkrik-es) [inline x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java:112]: What happens if the setting doesn't exist but IndexMode is set to `LOGSDB`? Shall we treat it as synthetic?

File: x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java (hunk 2 above)
Comment (martijnvg) [reply x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java]: I updated the comment: cf601211829a95391b2dfc3acbc420bdf6156b97

File: x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java [hunk 4]
```diff
@@ -101,6 +101,20 @@ boolean newIndexHasSyntheticSourceUsage(
 
         try {
             var tmpIndexMetadata = buildIndexMetadataForMapperService(indexName, templateIndexMode, indexTemplateAndCreateRequestSettings);
+            var indexMode = tmpIndexMetadata.getIndexMode();
+            if (SourceFieldMapper.INDEX_MAPPER_SOURCE_MODE_SETTING.exists(tmpIndexMetadata.getSettings())
+                || indexMode == IndexMode.LOGSDB
+                || indexMode == IndexMode.TIME_SERIES) {
+                // in case when index mode is either tsdb or logsdb and only _source.mode mapping attribute is specified, then the default
```
Comment (kkrik-es) [inline x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/SyntheticSourceIndexSettingsProvider.java:108]: Nit: s/in/In/

**Review by kkrik-es — APPROVED** [review]
