### PR TITLE
Fix a master->7.x serialization bug

### LINKED ISSUE #54396: [CI] Aggregation mixed cluster failure
A serialization failure, because of an unknown named writeable in `MixedClusterClientYamlTestSuiteIT test {p0=search.aggregation/330_auto_date_histogram/basic}`

Failure:

```
[2020-03-30T14:31:28,724][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  "stash" : {
    "body" : {
      "error" : {
        "root_cause" : [
          {
            "type" : "illegal_argument_exception",
            "reason" : "Unknown NamedWriteable [org.elasticsearch.search.aggregations.PipelineAggregationBuilder][]",
            "stack_trace" : "org.elasticsearch.ElasticsearchException$1: Unknown NamedWriteable [org.elasticsearch.search.aggregations.PipelineAggregationBuilder][]
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644)
	at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:167)
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:626)
	at org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:572)
	at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)
    ...
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.search.aggregations.PipelineAggregationBuilder][]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112)
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45)
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.<init>(AggregatorFactories.java:257)
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:989)
	at org.elasticsearch.search.builder.SearchSourceBuilder.<init>(SearchSourceBuilder.java:204)
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:989)
	at org.elasticsearch.search.internal.ShardSearchRequest.<init>(ShardSearchRequest.java:167)
	at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:56)
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:187)
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:130)
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:107)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:681)
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:136)
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:110)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:68)
```

Build url: https://gradle-enterprise.elastic.co/s/wdpjhc2oh534q/tests/77udqutc4yt34-blndfefc2cef2

Reproduce line: `./gradlew ':qa:mixed-cluster:v7.8.0#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/330_auto_date_histogram/basic}" -Dtests.seed=2DD4185E797F2251 -Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=Asia/Ujung_Pandang -Dcompiler.java=13`

This does not reproduce for me locally.

### PR DESCRIPTION
**Pull request by nik9000**
`master` wasn't sending `auto_date_histogram`'s
`minimumIntervalExpression` over the wire to `7.x` nodes even though
everything above `7.3` expected it. We never noticed this because we
didn't have any yml tests for `auto_date_histogram` until I added some
in #54161.

Closes #54396

### CODE REVIEW

**Comment by nik9000** [comment]
I've labeled this `:non-issue` because it fixes a bug in an unreleased version (8.0.0). If we had made it to 8.0 without fixing this it would have been a bug.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java [hunk 1]
```diff
@@ -110,20 +110,6 @@
 
     private String minimumIntervalExpression;
 
-    public String getMinimumIntervalExpression() {
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java]: I'm moving these below the ctor to make me feel better.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java [hunk 2]
```diff
@@ -138,6 +124,14 @@ public AutoDateHistogramAggregationBuilder(StreamInput in) throws IOException {
         }
     }
 
+    @Override
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java]: I'm moving this up under the reading ctor so it is easier to compare.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java [hunk 3]
```diff
@@ -138,6 +124,14 @@ public AutoDateHistogramAggregationBuilder(StreamInput in) throws IOException {
...
+    protected void innerWriteTo(StreamOutput out) throws IOException {
+        out.writeVInt(numBuckets);
+        if (out.getVersion().onOrAfter(Version.V_7_3_0)) {
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java]: Changing this from `8_0_0` to `7_3_0` is the actual fix.

**Review by pcsanwald — APPROVED** [review]
very nice catch!
