### PR TITLE
Reinstate and test the native int7u bulk dot product

### LINKED ISSUE #138302: Segfault in new bulk query handling Diskbbq
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

avx512 CPUs

### Problem Description

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3d19094ac0, pid=182, tid=571
#
# JRE version: OpenJDK Runtime Environment (25.0.1+8) (build 25.0.1+8-27)
# Java VM: OpenJDK 64-Bit Server VM (25.0.1+8-27, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libvec.so+0x2ac0]  dot7u_bulk_2+0x280
#
# Core dump will be written. Default location: /usr/share/elasticsearch/logs/core
#
# An error report file with more information is saved as:

### Steps to Reproduce

Bulk scoring on avx512

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit reinstates, fixes, and tests the native int7u bulk dot product #138239 

The issue with the original change is that `size_t` is 64 bit, while we pass a 32 bit `int` from java. This is also arguably an issue with the other native definitions, but doesn't cause an issue because of position in the declaration (last). We should fix these declarations, but as a separate PR.

closes #138302

Relates to https://github.com/elastic/elasticsearch/issues/139059

### CODE REVIEW

**Comment by benwtrent** [comment]
I completely reverted the java portion of the PR. Sorry. We can add the java portion back, but just not use it until we figure out the segfault 

Thank you for the tests!!!

**Comment by ChrisHegarty** [comment]
> I completely reverted the java portion of the PR. Sorry. We can add the java portion back, but just not use it until we figure out the segfault
> 
> Thank you for the tests!!!

Ah, got it. Thanks. I didn't realise that there was a problem with the original change that was reverted.  I was noodling with an alternative implementation, which caused me to write the test. I think that we can squeeze a bit more perf out of this code, possibly another 15-20% on top of what you already got!

**Comment by benwtrent** [comment]
Absolutely beautiful!

I am not sure the cause of the segfault, but I suspect alignment issues by casting the int to a float.

So maybe we need to adjust the function definition or we do the casting in such a way it doesn't suffer from alignment problems

**Comment by ChrisHegarty** [comment]
For my own future reference, a few command to help build and test locally.

AArch64
```
$ cd libs/simdvec/native && ./gradlew buildSharedLibrary && cd -

$ cp libs/simdvec/native/build/libs/vec/shared/aarch64/libvec.dylib libs/native/libraries/build/platform/darwin-aarch64/libvec.dylib 

$ LOCAL_VEC_BINARY_OS=darwin ./gradlew :libs:native:test --tests "JDKVectorLibraryInt7uTests" -Dtests.iters=100
$ LOCAL_VEC_BINARY_OS=darwin ./gradlew :libs:simdvec:test -Dtests.iters=100

$ LOCAL_VEC_BINARY_OS=darwin ./gradlew -p benchmarks run --args "org.elasticsearch.benchmark.vector.Int7ScorerBenchmark.*Bulk"
```

x64
```
$ cd libs/simdvec/native && ./gradlew buildSharedLibrary && cd -

$ cp libs/simdvec/native/build/libs/vec/shared/amd64/libvec.so libs/native/libraries/build/platform/linux-x64/libvec.so 

$ LOCAL_VEC_BINARY_OS=amd64 ./gradlew :libs:native:test --tests "JDKVectorLibraryInt7uTests" -Dtests.iters=1000
$ LOCAL_VEC_BINARY_OS= amd64 ./gradlew :libs:simdvec:test -Dtests.iters=100

$  LOCAL_VEC_BINARY_OS=amd64 ./gradlew -p benchmarks run --args "org.elasticsearch.benchmark.vector.Int7ScorerBenchmark.*Bulk"
```

**Comment by ChrisHegarty** [comment]
Posting some benchmarking numbers.

Linux x64 - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
```
Benchmark                                       (dims)   Mode  Cnt   Score   Error   Units
Before
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     384  thrpt    5  24.548 ± 0.120  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     782  thrpt    5  21.737 ± 0.760  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk    1024  thrpt    5  22.471 ± 0.555  ops/ms
After
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     384  thrpt    5  60.246 ± 0.464  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     782  thrpt    5  35.816 ± 0.085  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk    1024  thrpt    5  41.445 ± 0.057  ops/ms
```

Mac M2
```
Benchmark                                       (dims)   Mode  Cnt   Score    Error   Units
Before
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     384  thrpt    5  36.335 ± 0.192  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     782  thrpt    5  20.941 ± 1.066  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk    1024  thrpt    5  19.750 ± 0.343  ops/ms
After
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     384  thrpt    5  54.776 ± 13.235  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk     782  thrpt    5  25.895 ±  0.621  ops/ms
Int7ScorerBenchmark.scoreFromMemorySegmentBulk    1024  thrpt    5  24.141 ±  0.037  ops/ms
```

File: libs/native/src/main/java/org/elasticsearch/nativeaccess/jdk/JdkVectorLibrary.java [hunk 1]
```diff
@@ -142,6 +154,13 @@ static int dotProduct7u(MemorySegment a, MemorySegment b, int length) {
             return dot7u(a, b, length);
         }
 
+        static void dotProduct7uBulk(MemorySegment a, MemorySegment b, int length, int count, MemorySegment result) {
+            Objects.checkFromIndexSize(0, length * count, (int) a.byteSize());
+            Objects.checkFromIndexSize(0, length, (int) b.byteSize());
+            Objects.checkFromIndexSize(0, count * Float.BYTES, (int) result.byteSize());
```
Comment (ChrisHegarty) [inline libs/native/src/main/java/org/elasticsearch/nativeaccess/jdk/JdkVectorLibrary.java:160]: I added these runtime checks here just before going native, similar to other functions, so that we have a handle on the values that we pass through. Passing invalid values could lead to crashes or worse, so we enforce these here.

**Review by ldematte — COMMENTED** [review]
LGTM, and thanks for the additional tests!
I had a feeling the segfault was due to a wrong type size, but I was chasing the wrong guy :) Nice find!

**Review by ldematte — APPROVED** [review]

File: libs/native/src/test/java/org/elasticsearch/nativeaccess/jdk/JDKVectorLibraryInt7uTests.java [hunk 2]
```diff
@@ -86,6 +92,32 @@ public void testInt7BinaryVectors() {
         }
     }
 
+    public void testInt7uBulk() {
```
Comment (ChrisHegarty) [inline libs/native/src/test/java/org/elasticsearch/nativeaccess/jdk/JDKVectorLibraryInt7uTests.java:95]: This test reliably reproduces the previous segv issue.
