### PR TITLE
Reduce memory required for search responses when many shards are unavailable

### LINKED ISSUE #90622: Searches against a large number of unavailable shards result in very large responses
Searching a large number of unavailable shards through e.g. the `*` pattern while a large cluster is recovering from a full restart or so, leads to extremely large responses containing an exception for each shard.

This example shows a 375M on heap response for ~25k unavailable shards being returned. Over the wire, this serialises with a similar size and we'd have 700M+ peak heap usage for a search request when the valid search response in a green cluster might be much smaller than this.
It seems to me that we could mostly resolve this by not returning the stack trace in this specific case of the shard not available exception (it doesn't seem valuable for users and we made a similar fix around unavailable shards in snapshots state responses)?

### PR DESCRIPTION
**Pull request by benwtrent**
When there are many shards unavailable, we repeatably store the exact same stack trace and exception. The only difference is the exception message. 

This commit fixes this by slightly modifying the created exception to not provide a stacktrace or print its stacktrace as a "reason" when a shard is unavailable.

closes https://github.com/elastic/elasticsearch/issues/90622

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/ElasticsearchException.java [hunk 1]
```diff
@@ -1585,6 +1586,12 @@ private enum ElasticsearchExceptionHandle {
             UnsupportedAggregationOnDownsampledIndex::new,
             167,
             Version.V_8_5_0
+        ),
+        SHARD_UNAVAILABLE_EXCEPTION(
+            ShardSearchFailure.ShardUnavailableException.class,
+            ShardSearchFailure.ShardUnavailableException::new,
+            168,
+            Version.V_8_7_0
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/ElasticsearchException.java:1594]: @javanna I know we talked about not having this, but apparently, every exception in /org/elasticsearch has to be registered here :/

See test: `org.elasticsearch.ExceptionSerializationTests.testExceptionRegistration`

Comment (javanna) [reply server/src/main/java/org/elasticsearch/ElasticsearchException.java:1594]: I see, I think the problem you are trying to work around is that the exception that gets thrown is used in different places, and you'd like to only affect the codepath where we wrap the different kinds of shard unavailable into the high-level one that gets returned to users. I think we should try to avoid adding yet another exception if possible. Would it be possible to extend the existing `NoShardAvailableActionException` to conditionally return an empty stacktrace, for instance based on an additional constructor argument? The flag would not need to be serialized, only used locally to control whether to expose empty stacktrace or the original one, while avoiding to create another exception instance.

File: server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java [hunk 2]
```diff
@@ -37,5 +55,31 @@ public RestStatus status() {
 
     public NoShardAvailableActionException(StreamInput in) throws IOException {
         super(in);
+        if (in.getVersion().onOrAfter(Version.V_8_7_0)) {
+            this.onShardFailureWrapper = in.readBoolean();
+        } else {
+            this.onShardFailureWrapper = false;
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java:61]: I was thinking that the flag does not need to be serialized (we could mark it transient to signal that for instance). I may be missing something, but ideally we set the flag when we throw the exception, to make sure that on that node the stacktrace will be seen as empty, which ensures that an empty array gets sent over the wire. On the other side, the stacktrace array is received empty, and there is no need for the flag to be set, false is fine too in that case because there is no stacktrace to show. Does this make sense though?

File: server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java [hunk 3]
```diff
@@ -37,5 +55,31 @@ public RestStatus status() {
...
+    }
+
+    @Override
+    public StackTraceElement[] getStackTrace() {
+        return onShardFailureWrapper ? EMPTY_STACK_TRACE : super.getStackTrace();
+    }
+
+    @Override
+    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
+        Map<String, String> delegatedParams = onShardFailureWrapper
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java:80]: I guess this is important for the case of a coordinating node that is also a data node, which throws this exception and prints it out at REST too, without going through the transport layer. Is it necessary to also forcefully skip the cause?

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java]: No, we don't need to force to skip the cause or the stacktrace.

Stack trace will be empty from the new field being set to `true` (or from serialization reading in an empty stack trace). The cause is also `null`. 

This code change isn't necessary.

File: server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java (hunk 2 above)
Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/action/NoShardAvailableActionException.java]: You are correct! We don't need to serialize field. I will remove that.

We only need to worry about the stack trace being empty on serialization, then the node reading in will simply read an empty array, and this works just fine.

**Comment by benwtrent** [comment]
run elasticsearch-ci/docs

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by javanna — COMMENTED** [review]
this looks good, the only bit I would add is a test that verifies that the actual search code throws the right exception, which may get lost over time. Perhaps it's something that we could add to AbstractSearchAsyncActionTests ?

**Review by javanna — APPROVED** [review]
LGTM thanks @benwtrent !

**Comment by javanna** [comment]
I would propose backporting this to 8.6, I added the relevant label.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc
