### PR TITLE
[ML] prevent opening anomaly detection jobs with a current model snapshot before 7.0.0

### LINKED ISSUE #78382: [ML] We should fail jobs if they try to load a pre-7.0 model snapshot on an 8.0+ node
When an anomaly detection job is opened on a node on version 8.0 or higher, the job should be put into the `failed` state if the model snapshot it tries to load is from a version before 7.0.

Version 8.0 C++ code is not guaranteed to understand model snapshots generated before 7.0, so we must prevent it being fed such a snapshot.

We have provided a model snapshot migration mechanism in 7.x, so it's reasonable to fail the job if really old snapshots are still in use.  A user who encounters such a failed job can recover in 8.0 by resetting the job to empty, or, if available, reverting to a model snapshot that was generated in 7.x.  But it's extremely unlikely anyone will see this in reality so the defensive check we add should be as simple as possible.

### PR DESCRIPTION
**Pull request by benwtrent**
Anomaly detection jobs with current model snapshot's where the min_version is before 7.0.0 shouldn't open.

To remediate, the user should do one of the following _before_ upgrading to 8.0.0:

- Delete the model snapshot
- Revert to a separate snapshot with a later minimum version
- Reset the job to empty
- Call the upgrade model snapshot: https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-upgrade-job-model-snapshot.html

The only remediations _after_ upgrading to 8.0.0 are:

- Revert to a separate snapshot with a later minimum version
- Reset the job to empty

closes https://github.com/elastic/elasticsearch/issues/78382

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java [hunk 1]
```diff
@@ -326,6 +339,61 @@ private void hasRunningDatafeedTask(String jobId, ActionListener<Boolean> listen
...
+                            }
+                            assert snapshot.getPage().results().size() == 1;
+                            ModelSnapshot snapshotObj = snapshot.getPage().results().get(0);
+                            if (snapshotObj.getMinVersion().onOrAfter(MIN_SUPPORTED_SNAPSHOT_VERSION)) {
+                                listener.onResponse(true);
+                                return;
+                            }
+                            listener.onFailure(
+                                ExceptionsHelper.serverError(
+                                    "[{}] job snapshot [{}] has min version before [{}], please upgrade the model snapshot",
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java:372]:
```suggestion
                                    "[{}] job snapshot [{}] has min version before [{}], please revert to a newer model snapshot or reset the job",
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java [hunk 2]
```diff
@@ -149,12 +154,55 @@ public void onFailure(Exception e) {
...
+                                    return;
+                                }
+                                assert modelSnapshot.getPage().results().size() == 1;
+                                if (modelSnapshot.getPage().results().get(0).getMinVersion().onOrAfter(MIN_SUPPORTED_SNAPSHOT_VERSION)) {
+                                    modelSnapshotValidationListener.onResponse(true);
+                                    return;
+                                }
+                                listener.onFailure(
+                                    ExceptionsHelper.serverError(
+                                        "[{}] job snapshot [{}] has min version before [{}], please upgrade the model snapshot",
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java:186]:
```suggestion
                                        "[{}] job snapshot [{}] has min version before [{}], please revert to a newer model snapshot or reset the job",
```

File: x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnomalyJobCRUDIT.java [hunk 3]
```diff
@@ -147,6 +153,40 @@ public void testPutJobWithClosedStateIndex() {
...
+        client().execute(RevertModelSnapshotAction.INSTANCE, new RevertModelSnapshotAction.Request(jobId, "snap_1")).actionGet();
+
+        // should fail?
+        Exception ex = expectThrows(Exception.class,
+            () -> client()
+                .execute(OpenJobAction.INSTANCE, new OpenJobAction.Request(jobId))
+                .actionGet());
+        assertThat(ex.getMessage(),
+            containsString(
+                "[open-job-with-old-model-snapshot] job snapshot [snap_1] has min version before [7.0.0], please upgrade the model snapshot"
```
Comment (droberts195) [inline x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnomalyJobCRUDIT.java:181]:
```suggestion
                "[open-job-with-old-model-snapshot] job snapshot [snap_1] has min version before [7.0.0], please revert to a newer model snapshot or reset the job"
```

**Review by droberts195 — COMMENTED** [review]
Thanks for fixing this.

The only thing that I think needs changing is the error message.  By the time the user is in version 8 it's too late to upgrade pre-7.0 model snapshots - only 7.x is guaranteed to be able to do that.  All they can do in 8.x is switch to a different model snapshot, or, in the worst case, reset the job and start again from scratch.

**Review by droberts195 — APPROVED** [review]
LGTM
