### PR TITLE
Fixed a msm accounting error that can occur during analyzing a percolator query

### LINKED ISSUE #29393: [CI] CandidateQueryTests#testDuel failure
```
   > Expected: <829L>
   >      but: was <828L>
   >    at __randomizedtesting.SeedInfo.seed([4066BC2B6E5FC61C:CE6062B30D75E0E]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.percolator.CandidateQueryTests.duelRun(CandidateQueryTests.java:874)
   >    at org.elasticsearch.percolator.CandidateQueryTests.testDuel(CandidateQueryTests.java:264)
```

Reproduces on 6.x and master branches:
```
./gradlew :modules:percolator:test \
  -Dtests.seed=4066BC2B6E5FC61C \
  -Dtests.class=org.elasticsearch.percolator.CandidateQueryTests \
  -Dtests.method="testDuel" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EA \
  -Dtests.timezone=Asia/Vladivostok
```

### PR DESCRIPTION
**Pull request by martijnvg**
In case of a disjunction query with both range and term based clauses and
msm specified, the query analyzer needs to also reduce the msn if a range
based clause for the same field is encountered. This did not happen.

Instead of fixing this bug the logic has been simplified to just set a
percolator query's msm to 1 if a disjunction contains range clauses and
msm on disjunction has been specified. The logic would otherwise just get
to complex and the performance gain isn't that much for this kind of
percolator queries.

Also added another random duel test.

Closes #29393

### CODE REVIEW

File: modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java [hunk 1]
```diff
@@ -585,15 +588,7 @@ private static Result handleDisjunction(List<Query> disjunctions, int requiredSh
...
-                if (clauses.get(i).rangeFieldNames.isEmpty() == false) {
-                    for (String rangeField: clauses.get(i).rangeFieldNames) {
-                        if (seenRangeFields.add(rangeField)) {
-                            msm += 1;
-                        }
-                    }
-                } else {
-                    msm += clauses.get(i).msm;
-                }
+                msm += clauses.get(i).msm;
```
Comment (jpountz) [inline modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java]: maybe `clauses` can directly store Integers.

**Review by jpountz — APPROVED** [review]

**Comment by martijnvg** [comment]
@jpountz The test that was added had some sporadic failes that I have addressed now the second last commit. The main issue was that in case of clauses with duplicate terms the msm was set to a too high value.

File: modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java [hunk 2]
```diff
@@ -564,35 +579,37 @@ private static Result handleDisjunction(List<Query> disjunctions, int requiredSh
...
-                            msm += 1;
-                        }
-                    }
-                } else {
-                    msm += clauses.get(i).msm;
+
+            // When there are duplicated query extractions, percolator can no longer reliably determine msm across this disjunction
+            if (hasDuplicateTerms) {
+                // pick lowest msm:
+                msm = clauses.get(0);
```
Comment (jpountz) [inline modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java]: is there always at least one element in this list? (I haven't checked whether we assert it somewhere else)

**Review by jpountz — APPROVED** [review]

File: modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java (hunk 2 above)
Comment (martijnvg) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java]: Yes, if `hasDuplicateTerms` has been set to `true` then there should be at least two clauses.
