### PR TITLE
Remove ban parent-task BWC

### LINKED ISSUE #66518: CI: testTaskCancellationOnCoordinatingNodeLeavingTheCluster fails
**Build scan**: https://gradle-enterprise.elastic.co/s/df5tjhtcm552m/console-log/raw

**Repro line**: 

```
./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests.testTaskCancellationOnCoordinatingNodeLeavingTheCluster" -Dtests.seed=4656B267C8C11E43 -Dtests.security.manager=true -Dtests.locale=nl-NL -Dtests.timezone=US/Aleutian -Druntime.java=11
```

**Reproduces locally?**: yes

**Applicable branches**: master

**Failure excerpt**:
```
org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests > testTaskCancellationOnCoordinatingNodeLeavingTheCluster FAILED
    java.lang.AssertionError: No bans on the node 1 expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([4656B267C8C11E43:1D5057DC1747CFB7]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)

```

### PR DESCRIPTION
**Pull request by dnhatn**
This BWC is no longer needed after backporting #66066 to 7.x.

Closes #66518

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/tasks/TaskManager.java [hunk 1]
```diff
@@ -502,21 +482,6 @@ public String toString() {
     @Override
     public void applyClusterState(ClusterChangedEvent event) {
         lastDiscoveryNodes = event.state().getNodes();
-        if (event.nodesRemoved()) {
-            synchronized (bannedParents) {
-                lastDiscoveryNodes = event.state().getNodes();
-                // Remove all bans that were registered by nodes that are no longer in the cluster state
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/tasks/TaskManager.java:508]: So good :tada:

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java [hunk 2]
```diff
@@ -376,101 +372,6 @@ public void testRegisterAndExecuteChildTaskWhileParentTaskIsBeingCanceled() thro
         assertTrue("onChildTasksCompleted() is not invoked", latch.await(1, TimeUnit.SECONDS));
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/66518")
-    public void testTaskCancellationOnCoordinatingNodeLeavingTheCluster() throws Exception {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:380]: Hmm this test seems somewhat useful, although I see that it's not quite valid any more. Can we make it valid again by, say, closing the connections from the "removed" nodes?

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I think we can fix the test rather than simply removing it :)

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java (hunk 2 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:380]: +1, I fixed it in https://github.com/elastic/elasticsearch/pull/66525/commits/5b5712314964bc1131eb932c63353ad3fcb38167

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:380]: The adjusted test fails for me after a few iterations. Not reproducibly, otherwise I'd share a seed, but hopefully you can see this too.

Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:380]: Thanks for checking. I will run it a few hundred iterations.

Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:380]: I pushed the fix in https://github.com/elastic/elasticsearch/pull/66525/commits/ff8b89cb1cbd6e4d689f2f9bffacb5ce3620ffa3

**Comment by dnhatn** [comment]
@DaveCTurner Would you please take another look? Thank you.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks David.
