### PR TITLE
Fix `ShardSplittingQuery` to respect nested documents.

### LINKED ISSUE #27378: shard splitting doesn't always respect nested docs
Nested docs share the same `_id` which is enough unless `_routing` is involved and / or the index is partitioned. We need to find a good way to respect nested docs when we select the docs that should be deleted. We can either do this at runtime (when we split) or we also index / store the `_routing` value from the parent. 

@jpountz WDYT

### PR DESCRIPTION
**Pull request by s1monw**
Today if nested docs are used in an index that is split the operation
will only work correctly if the index is not routing partitioned or
unless routing is used. This change fixes the query that selectes the docs
to delete to also select all parents nested docs as well.

Closes #27378

### CODE REVIEW

**Comment by s1monw** [comment]
@elasticmachine test this please

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java [hunk 1]
```diff
@@ -84,44 +94,85 @@ public Scorer scorer(LeafReaderContext context) throws IOException {
...
                 }
+
                 return new ConstantScoreScorer(this, score(), new BitSetIterator(bitSet, bitSet.length()));
             }
-
-
         };
     }
 
+    private void markChildDocs(BitSet parentDocs, BitSet deletedDocs) {
```
Comment (jimczi) [inline core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: Why deletedDocs ? It's the opposite, no ? The bitset of the matching parent+children, allDocs ?

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java [hunk 2]
```diff
@@ -240,6 +294,46 @@ public float matchCost() {
...
+                nextParentMatches = innerMatches(nextParent);
+            }
+            return nextParentMatches;
+        }
+    }
+
+    /*
+     * this is used internally to obtain a bitset for parent documents. We don't cache this since we never access the same reader more
+     * than once
+     */
```
Comment (jimczi) [inline core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: We warm this query per segment in `BitsetFilterCache#BitSetProducerWarmer` so why not using the per-segment cache directly ?

**Review by jimczi — APPROVED** [review]
I left some minor comments regarding naming and caching, otherwise LGTM

File: core/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java [hunk 3]
```diff
@@ -83,53 +104,91 @@ public void testSplitOnRouting() throws IOException {
             .numberOfShards(numShards)
             .setRoutingNumShards(numShards * 1000000)
             .numberOfReplicas(0).build();
+        boolean hasNested = true || randomBoolean();
```
Comment (martijnvg) [inline core/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java]: s/`true || randomBoolean();`/`randomBoolean();`

File: core/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java [hunk 4]
```diff
@@ -83,53 +104,91 @@ public void testSplitOnRouting() throws IOException {
...
         final int numDocs = randomIntBetween(50, 100);
         RandomIndexWriter writer = new RandomIndexWriter(random(), dir);
-        int numShards =  randomIntBetween(2, 10);
+        int numShards = randomIntBetween(2, 10);
         IndexMetaData metaData = IndexMetaData.builder("test")
             .settings(Settings.builder().put(IndexMetaData.SETTING_VERSION_CREATED, Version.CURRENT))
             .numberOfShards(numShards)
             .setRoutingNumShards(numShards * 1000000)
             .numberOfReplicas(0).build();
+        boolean hasNested = true;randomBoolean();
```
Comment (martijnvg) [inline core/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java]: same here

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java [hunk 5]
```diff
@@ -84,44 +94,85 @@ public Scorer scorer(LeafReaderContext context) throws IOException {
...
-                if (terms == null) { // this is the common case - no partitioning and no _routing values
+                if (terms == null) {
+                    // this is the common case - no partitioning and no _routing values
+                    // in this case we also don't do anything special with regards to nested docs since we basically delete
+                    // by ID and parent and nested all have the same id.
                     assert indexMetaData.isRoutingPartitionedIndex() == false;
                     findSplitDocs(IdFieldMapper.NAME, includeInShard, leafReader, bitSet::set);
                 } else {
+                    final BitSet parentBitSet;
+                    final IntPredicate includeDoc;
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: So just to double check, the `includeDoc` is to ensure that only root docs get selected and later we select the nested docs of the selected root docs in `markChildDocs(...)`, right?

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java [hunk 6]
```diff
@@ -240,6 +294,46 @@ public float matchCost() {
...
+            }
+            return nextParentMatches;
+        }
+    }
+
+    /*
+     * this is used internally to obtain a bitset for parent documents. We don't cache this since we never access the same reader more
+     * than once
+     */
+    private static BitSetProducer newParentDocBitSetProducer() {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: :+1:

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java [hunk 7]
```diff
@@ -240,6 +294,46 @@ public float matchCost() {
...
+        private int nextParent = -1;
+        private boolean nextParentMatches;
+
+        NestedRoutingPartitionedDocIdSetIterator(LeafReader leafReader, Visitor visitor, BitSet parentDocs) {
+            super(leafReader, visitor);
+            this.parentDocs = parentDocs;
+        }
+
+        @Override
+        public boolean matches() throws IOException {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: I was trying to understand why this works, because of the forward iteration here (with nested, we usually seek backwards (`BitSet.prevSetBit(...)`)). So this works because all live doc ids (root docs and nested docs) are evaluated in order.

**Review by martijnvg — COMMENTED** [review]
This looks good @s1monw! I left a few questions and small remarks.

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java (hunk 2 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: we use this only as a delete by query which is executed on a `recovery-private` index writer. There is no point in cacheing it and it won't have a cache hit either.

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java (hunk 1 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: naming issue, I will fix. In theory it will hold all docs that need to be deleted by the IndexWriter.

File: core/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java (hunk 3 above)
Comment (s1monw) [reply core/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java]: oh yeah 🗡

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java (hunk 5 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: correct

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java (hunk 7 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: correct, I will leave a comment

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java (hunk 2 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: I left a comment

**Comment by s1monw** [comment]
@jimczi @martijnvg I pushed new commits if you wanna take another look

**Review by martijnvg — APPROVED** [review]
LGTM

File: core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java (hunk 2 above)
Comment (jimczi) [reply core/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java]: Ok I missed the recovery-private thing. Thanks

**Review by jimczi — APPROVED** [review]
