### PR TITLE
Fix rounding composite aggs on sorted index

### LINKED ISSUE #57849: Composite Aggregation have missing buckets on paginated results with "size" and "after"
**Elasticsearch version**:
7.7.1

**Description of the problem including expected versus actual behavior**:
Composite aggregation will produce fewer buckets when used with limited "size" and pagination with "after"

**Steps to reproduce**:

 1. Create this index:
```
PUT test-activities
{
  "mappings" : {
      "properties" : {
        "activityTime" : {
          "type" : "date"
        },
        "subscriberID" : {
          "type" : "keyword"
        }
      }
    },
    "settings" : {
      "index" : {
        "sort" : {
          "field" : "activityTime",
          "order" : "desc"
        },
        "number_of_shards" : "1",
        "number_of_replicas" : "0"
      }
    }
}
```
 2. Add test data to the index
``` 
POST _bulk
{"index":{"_index":"test-activities"}}
{"subscriberID":37640,"activityTime":"2020-06-03T00:53:10"}
{"index":{"_index":"test-activities"}}
{"subscriberID":90640,"activityTime":"2020-06-03T00:55:10"}
{"index":{"_index":"test-activities"}}
{"subscriberID":22640,"activityTime":"2020-06-03T01:10:10"}
{"index":{"_index":"test-activities"}}
{"subscriberID":91640,"activityTime":"2020-06-03T01:15:10"}
{"index":{"_index":"test-activities"}}
{"subscriberID":11640,"activityTime":"2020-06-03T01:21:10"}
{"index":{"_index":"test-activities"}}
{"subscriberID":90640,"activityTime":"2020-06-03T01:22:10"}
{"index":{"_index":"test-activities"}}
{"subscriberID":31640,"activityTime":"2020-06-03T01:54:10"}
```

 3. Use below search request which contains a composite aggregation with size 10, **produce six buckets**.
```
POST test-activities/_search
{
  "aggs": {
    "rollup":{
      "composite": {
        "size": 10,
        "sources": [
          {
            "activityTime": {
              "date_histogram": {
                "calendar_interval": "1d",
                "field": "activityTime"
              }
            }
          },
          {
            "subscriberID": {
              "terms": {
                "field": "subscriberID",
                "missing_bucket": true
              }
            }
          }
        ]
      }
    }
  },
  "size": 0,
  "track_total_hits": false
}
```

Here are 6 buckets created for above request:

```{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "rollup" : {
      "after_key" : {
        "activityTime" : 1591142400000,
        "subscriberID" : "91640"
      },
      "buckets" : [
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "11640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "22640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "31640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "37640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "90640"
          },
          "doc_count" : 2
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "91640"
          },
          "doc_count" : 1
        }
      ]
    }
  }
}

```

4. Run above search request with limited composite aggregation size:3
```
POST test-activities/_search
{
  "aggs": {
    "rollup":{
      "composite": {
        "size": 3,
        "sources": [
          {
            "activityTime": {
              "date_histogram": {
                "calendar_interval": "1d",
                "field": "activityTime"
              }
            }
          },
          {
            "subscriberID": {
              "terms": {
                "field": "subscriberID",
                "missing_bucket": true
              }
            }
          }
        ]
      }
    }
  },
  "size": 0,
  "track_total_hits": false
}
```
Here are first 3 buckets and after key returned as below:
```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "rollup" : {
      "after_key" : {
        "activityTime" : 1591142400000,
        "subscriberID" : "31640"
      },
      "buckets" : [
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "11640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "22640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "31640"
          },
          "doc_count" : 1
        }
      ]
    }
  }
}
``` 
5. Use the after key and run below search request to get the next page:
```
POST test-activities/_search
{
  "aggs": {
    "rollup":{
      "composite": {
        "after" : {
        "activityTime" : 1591142400000,
        "subscriberID" : "31640"
        },
        "size": 3,
        "sources": [
          {
            "activityTime": {
              "date_histogram": {
                "calendar_interval": "1d",
                "field": "activityTime"
              }
            }
          },
          {
            "subscriberID": {
              "terms": {
                "field": "subscriberID",
                "missing_bucket": true
              }
            }
          }
        ]
      }
    }
  },
  "size": 0,
  "track_total_hits": false
}
```
6. The result is just 1 bucket as below, **We have only four buckets and two buckets are missing** comparing to the result without pagination. **Buckets for subscriberID 37640 and 91640 are missing.**
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "rollup" : {
      "after_key" : {
        "activityTime" : 1591142400000,
        "subscriberID" : "90640"
      },
      "buckets" : [
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "90640"
          },
          "doc_count" : 1
        }
      ]
    }
  }
}

```

Note that same search request on Elasticsearch 7.5.1 produce correct result as expected:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "rollup" : {
      "after_key" : {
        "activityTime" : 1591142400000,
        "subscriberID" : "91640"
      },
      "buckets" : [
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "37640"
          },
          "doc_count" : 1
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "90640"
          },
          "doc_count" : 2
        },
        {
          "key" : {
            "activityTime" : 1591142400000,
            "subscriberID" : "91640"
          },
          "doc_count" : 1
        }
      ]
    }
  }
}

```

### PR DESCRIPTION
**Pull request by jimczi**
This commit fixes a bug on the composite aggregation when the index
is sorted and the primary composite source needs to round values (date_histo).
In such case, we cannot take into account the subsequent sources even if they
match the index sort because the rounding of the primary sort value may break
the original index order.

Fixes #57849

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
I think it would be nice to target `7.7.2` as well.

@jimczi Do you know which versions are affected in addition to `7.7`?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java [hunk 1]
```diff
@@ -231,6 +235,10 @@ private Sort buildIndexSortPrefix(LeafReaderContext context) throws IOException
                 break;
             }
             sortFields.add(indexSortField);
+            if (sourceConfig.valuesSource() instanceof RoundingValuesSource) {
+                // rounded values break the index sort
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java:239]: It's probably worth explaining why. I *think* it is because the rounding "squashes" many values together so we can't get the order of the sub-values by looking at any one key. We'd have to merge all the values that round to that key and get the sub-values from that. And that isn't the kind of this this index sorting optimization does.

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java]: ++, I pushed https://github.com/elastic/elasticsearch/pull/57867/commits/e48605775859aeb48d6f0eb1d7356ca434fdf6d2

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by jimczi** [comment]
> Do you know which versions are affected in addition to 7.7? 

The bug was introduced in 7.6 by https://github.com/elastic/elasticsearch/pull/48399. I'll merge to 7.7 too.
