### PR TITLE
Restrict fields with the same name in different types to have the same core settings

### LINKED ISSUE #8871: Move field mappings to the index level internally
Internally, field mappings should be stored at the index level, rather than at the type level.  Types are essentially a way of grouping fields. While the mapping APIs will not change, an exception will be thrown if an attempt is made to map a field in one type in a way that conflicts with the mapping of a field with same name in another type.

The `_parent` field is the one exception - this field will remain at the type level.

Relates to #8870

### PR DESCRIPTION
**Pull request by rjernst**
We currently are very lax about allowing data types to conflict for the
same field name, across document types. This change makes the underlying
map in MapperService a 1-1 map of field name to field type, and throws
exception when new types are not compatible.

To still allow changing a type, with parameters that are allowed to be
changed, but for a field that exists in multiple types, a new parameter
to index creation and put mapping API is added: update_all_types.
This defaults to false, and the exception messages suggest using
this parameter when trying to modify a setting that is allowed to be
modified but is being limited by this restriction.

There are also a couple changes which try to base fields from new types
for dynamic mappings, and root mappers, on existing settings. For
dynamic mappings this is important if the dynamic defaults have been
changed. For root mappings, this is mostly just for backcompat when
pre 2.0 root mappers could have their field type changed.

fixes #8871

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+            } else {
+                // this new field bridges between two existing field names (a full and index name), which we cannot support
+                throw new IllegalStateException("insane mappings found. field " + fieldType.names().fullName() + " maps across types to field " + fieldType.names().indexName());
+            }
+        }
+        return new FieldTypeLookup(fullName, indexName);
+    }
+
+    /**
+     * Checks if the give mapper's field types are compatibile with existing field types.
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java]: s/give/given/

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java [hunk 2]
```diff
@@ -277,10 +277,30 @@ public void checkCompatibility(MappedFieldType other, List<String> conflicts) {
         if (!names().equals(other.names())) {
             conflicts.add("mapper [" + names().fullName() + "] has different index_name");
         }
-
         if (Objects.equals(similarity(), other.similarity()) == false) {
             conflicts.add("mapper [" + names().fullName() + "] has different similarity");
         }
+
+        if (strict) {
+            if (omitNorms() != other.omitNorms()) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: I think norms are complicated because disabling them is ok while enabling them will not work?

**Comment by jpountz** [comment]
The change looks great. I also played with the change, trying to add conflicting mappings at index creation time, through dynamic mappings and explicit mappings updates and things seem to work fine overall. I found some bugs wrt dynamic mappings that I fixed in your branch (hope you don't mind) and left comments for some other bugs.

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java [hunk 3]
```diff
@@ -228,8 +226,10 @@ public int hashCode() {
 
     /**
      * Checks for any conflicts between this field type and other.
+     * If strict is true, all properties must be equal.
+     * Otherwise, only properties which must never change in an index are checked.
      */
-    public void checkCompatibility(MappedFieldType other, List<String> conflicts) {
+    public void checkCompatibility(MappedFieldType other, List<String> conflicts, boolean strict) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: When I did the following test:

```bash
DELETE test

PUT test 
{
  "mappings": {
    "test1": {
      "properties": {
        "s": {
          "type": "binary"
        }
      }
    }
  }
}

PUT test/test2/_mapping
{
  "test2": {
    "properties": {
      "s": {
        "type": "string"
      }
    }
  }
}
```
I got the following response:
```bash
{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "Mapper for [s] conflicts with existing mapping in other types[mapper [s] has different index values]"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Mapper for [s] conflicts with existing mapping in other types[mapper [s] has different index values]"
   },
   "status": 400
}
```
I was surprised to see an error about options while the mapped type isn't even the same. I suspect it comes from this method which starts validating options without first comparing the type implementation?

File: core/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexClusterStateUpdateRequest.java [hunk 4]
```diff
@@ -126,4 +128,8 @@ public Settings settings() {
     public Set<ClusterBlock> blocks() {
         return blocks;
     }
+
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexClusterStateUpdateRequest.java]: can we get some javadocs what this means?

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 5]
```diff
@@ -493,32 +528,26 @@ private static ObjectMapper parseDynamicValue(final ParseContext context, Object
...
-                    } catch (Exception e) {
-                        // not a long number
+                try {
+                    Double.parseDouble(text);
+                    Mapper.Builder builder = context.root().findTemplateBuilder(context, currentFieldName, "double");
+                    if (builder == null) {
+                        builder = MapperBuilders.doubleField(currentFieldName);
                     }
+                    return builder;
+                } catch (Exception e) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: can this exception be more specific?

File: core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+        fullNameToFieldType = fullName;
+        indexNameToFieldType = indexName;
+    }
+
+    /**
+     * Return a new instance that contains the union of this instance and the field types
+     * from the provided fields. If a field already exists, the field type will be updated
+     * to use the new mappers field type.
+     */
+    public FieldTypeLookup copyAndAddAll(Collection<FieldMapper> newFieldMappers) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java]: is this called concurrently? I wonder if it is since I think we really want to read only the result of the `copyAndAddAll` but the `CopyOnWriteHashMap` will allow inconsistent views on the data. I wonder if we should really just use ImmutableMaps or simple maps that we never modify and based them on a copy of the existing one?

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 2 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: yeah it needs to be anti-viral like lucene is

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+ * under the License.
+ */
+package org.elasticsearch.index.mapper;
+
+/**
+ * A container for a {@link MappedFieldType} which can be updated and is reference counted.
+ */
+public class MappedFieldTypeReference {
+    private MappedFieldType fieldType; // the current field type this reference points to
+    private int refCount;
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java]: I don't know if it's used by multiple threads but I'd feel better if we either documetn it or make `refCount` and `AtomicInteger`? But then I guess we can't guarantee consistency with the set fieldType... I need to look closer

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java]: ok I see, not sure if `refCount` is the right name? I think we should rather name it `usedByTypes` or maybe even have a method like `associateType(String type)` where we can hold the type in a set that we can use in assertions to make sure it's only associated once?

File: core/src/main/java/org/elasticsearch/index/mapper/core/NumberFieldMapper.java [hunk 8]
```diff
@@ -317,8 +318,14 @@ public void merge(Mapper mergeWith, MergeResult mergeResult) throws MergeMapping
         if (!this.getClass().equals(mergeWith.getClass())) {
             return;
         }
-        if (!mergeResult.simulate()) {
-            NumberFieldMapper nfmMergeWith = (NumberFieldMapper) mergeWith;
+        NumberFieldMapper nfmMergeWith = (NumberFieldMapper) mergeWith;
+        if (this.fieldTypeRef.getRefCount() > 1 && mergeResult.updateAllTypes() == false) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/core/NumberFieldMapper.java]: yeah if we name `getRefCount` `getNumAssociatedTypes` this line is way more intuitive to read?

File: core/src/main/java/org/elasticsearch/index/mapper/internal/IdFieldMapper.java [hunk 9]
```diff
@@ -306,12 +310,13 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
             return builder;
         }
         boolean includeDefaults = params.paramAsBoolean("include_defaults", false);
+        boolean hasCustomFieldDataSettings = customFieldDataSettings != null && customFieldDataSettings.equals(Settings.EMPTY) == false;
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/internal/IdFieldMapper.java]: I guess we can abstract this into a method called `hasCustomFieldDataSettings()` that way we don't have to repeat it like 7 times?

**Comment by s1monw** [comment]
I left a bunch of comments - I'd like to talk the concurrency aspects through with you in person here and I also wonder if we can get rid of `MapperAnalyzer.java` now?

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 2 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: We already have the check for norms going the "bad" direction above:
````
if (omitNorms() && !other.omitNorms()) {
    conflicts.add("mapper [" + names().fullName() + "] cannot enable norms (`norms.enabled`)");
}
```

The check in `strict` is for when norms change at all (even the good direction), since `strict` means no changes are allowed. Would it be better if I make it explicit this is the "ok" direction with the check?

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java (hunk 7 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java]: I like `usedByTypes` much better. I'm apprehensive about having a set of associated types because we don't actually need this for anything but the count, and it would add a lot of complication to the already complicated graph of mappings objects (tons of back references).

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 2 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: I missed it, perfect!

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java (hunk 3 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java]: I agree we need a better error message here. We can't just check the class like mappers do, since some mappers use MappedFieldType directly. I think I will add a setting to MappedFieldType which is the "typename"? This will give a much better error than what we get now IMO (the actual type, instead of a classname the user knows nothing about).

File: core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 6 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java]: No, this is not called concurrently (protected by the mapping write lock in MapperService/DocumentMappers). I dont think the COW map will allow inconsistent views, since an entire new lookup is created (so any new fields will not be visible to search until this method returns and MapperService updates its lookup reference). We do have consistency problems, though. For example. DocumentMapper has its own map of fields (FieldMapers, not MappedFieldTypes) which is updated first, and then MapperService is updated. But these problems all already existed (this lookup class was formerly called FieldMappersLookup, I just renamed it when the type changed).  I'm happy to continue working towards full immutability in the mappings, but I think that should happen in follow up issues.

File: core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java (hunk 7 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/MappedFieldTypeReference.java]: I went with `numAssociatedMappers`

**Comment by rjernst** [comment]
@s1monw @jpountz I pushed a new commit. The one outstanding thing is the better error message for conflicting data types.

As for `MapperAnalyzer.java`, I would love to get rid of this, but afaict right now it is still the one thing that restricts a document to have access only to the fields defined within a type?

**Comment by rjernst** [comment]
Actually, now I'm not sure about `MapperAnalyzer.java`. The `DocumentParser` looks up fields there when parsing, so by the type the analyzer needs to lookup the field, we should be able to just lookup the fieldtype for the index. I will try removing it.

**Comment by rjernst** [comment]
@jpountz @s1monw I removed MapperAnalyzer and added a better message when field types aren't the same.

**Comment by jpountz** [comment]
LGTM!

File: core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 6 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java]: +1 to a followup

**Comment by s1monw** [comment]
>  I removed MapperAnalyzer and added a better message when field types aren't the same.

awesome!!!!

LGTM
