### PR TITLE
Fix highlighting on a stored keyword field

### LINKED ISSUE #21636: Highlighting does not work when all fields are type keyword
**Elasticsearch version**: 5.0

**Plugins installed**: N/A

**JVM version**: 1.8u112

**OS version**: Windows Server 2012

**Description of the problem including expected versus actual behavior**: Highlighting dynamic fields which are stored as keyword is not working as expected. When searching over _all I would expect highlighting to occur on all fields of the result when using `require_field_match: false`. Example query can be found here:

http://pastebin.com/sAGczFhU

My use case is that nearly every search is done for an exact value or over _all. I could get extreme performance gains by shifting dynamically created fields to Keyword, and then if full-text search is needed, defining them explicitly in the mapping. However, search highlighting is still an important part of our workflow.

Do I have a misunderstanding of how highlighting works? My interpretation is that
1. We search over _all
2. Hits are selected for highlighting as a postprocessing step
3. Each field is matched against the original search query if require_field_match: false is set to true and the highlighting_query option is unused.

**Steps to reproduce**:
 1. Create a new index with a mapping that sets dynamic fields to type Keyword
 2. Add three new documents with `"message": "Kostya Test"`
 3. Run the previous query (fixing the date range)

Expected: There should be highlighted search text extracted from the _source fields that are loaded at highlight-time
Actual: No text is highlighted

The same can be repeated where the search is an exact match for the field, and no highlighting is done then either.

### PR DESCRIPTION
**Pull request by jimczi**
The highlighter converts stored keyword fields using toString().
Since the keyword fields are stored as utf8 bytes the conversion is broken.
This change uses BytesRef.utf8toString() to convert the field value in a valid string.

Fixes #21636

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java [hunk 1]
```diff
@@ -104,9 +105,14 @@ public HighlightField highlight(HighlighterContext highlighterContext) {
...
-
             for (Object textToHighlight : textsToHighlight) {
-                String text = textToHighlight.toString();
+                String text;
+                if (textToHighlight instanceof BytesRef) {
+                    // keywords are internally stored as utf8 bytes
+                    text = ((BytesRef) textToHighlight).utf8ToString();
+                } else {
+                    text = textToHighlight.toString();
+                }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java]: would it work if we called MappedFieldType.valueForDisplay instead? I'm concerned some fields are stored as bytesrefs too but do not represent utf8 strings, like ip addresses

**Review by jpountz — COMMENTED** [review]
I left one comment. I'm also curious whether the plain highlighter is the only affected highlighter?

File: core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java (hunk 1 above)
Comment (jimczi) [inline core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java]: I agree that it's better to call valueForDisplay (I'll change the PR) though we are protected here since the highlighting can be done only on text or keyword fields.

File: core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java [hunk 2]
```diff
@@ -106,7 +107,12 @@ public HighlightField highlight(HighlighterContext highlighterContext) {
             textsToHighlight = HighlightUtils.loadFieldValues(field, mapper, context, hitContext);
 
             for (Object textToHighlight : textsToHighlight) {
-                String text = textToHighlight.toString();
+                String text;
+                if (textToHighlight instanceof BytesRef) {
+                    text = mapper.fieldType().valueForDisplay(textToHighlight).toString();
+                } else {
+                    text = textToHighlight.toString();
+                }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java]: Should we just do `String text = mapper.fieldType().valueForDisplay(textToHighlight).toString();` all the time? This looks correct to me and is more future-proof? If that does not work, feel free to merge the PR as-is.

**Review by jpountz — APPROVED** [review]
I left a suggestion but it looks good to me. Feel free to merge regardless of whether you apply this suggestion.

File: core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java (hunk 2 above)
Comment (jimczi) [inline core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/PlainHighlighter.java]: The type of textToHighlight can be different whether it comes from the _source or from the stored fields. Calling valueForDisplay on it when it comes from _source would not work.

**Comment by jimczi** [comment]
The plain highlighter is the only one affected by this bug because the others are not eligible on a keyword field. The offset and term_vector options are not exposed on a keyword field.
