### PR TITLE
Make Snapshot Deletes Less Racy

### LINKED ISSUE #54766: Test Failures in org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests
Running `org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests` in a loop I can easily reproduce failing tests from race conditions around aborting a snapshot that is in state `INIT`.

Example failure:

```
REPRODUCE WITH: ./gradlew 'null' --tests "org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testSnapshotInProgress" -Dtests.seed=3F6218BBB4942CD0 -Dtests.locale=es-AR -Dtests.timezone=America/Phoenix

org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException: [my-repo:snap-aotuscactpiiyvbypiydca/0px1dM0eS7icvTYMxcM1Hw] Another concurrent operation moved repo generation to [ 0] but this delete assumed generation [-1]

	at __randomizedtesting.SeedInfo.seed([3F6218BBB4942CD0:86DD16153A98DDDE]:0)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.deleteSnapshot(BlobStoreRepository.java:494)
	at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$15(SnapshotsService.java:1243)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1118)
	at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$17(SnapshotsService.java:1243)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:830)
```

Fix incoming in https://github.com/elastic/elasticsearch/pull/54765

### PR DESCRIPTION
**Pull request by original-brownbear**
Snapshot deletes should first check the cluster state for an in-progress snapshot
and try to abort it before checking the repository contents. This allows for atomically
checking and aborting a snapshot in the same cluster state update, removing all possible
races where a snapshot that is in-progress could not be found if it finishes between
checking the repository contents and the cluster state.
Also removes confusing races, where checking the cluster state off of the cluster state thread
finds an in-progress snapshot that is then not found in the cluster state update to abort it.
Finally, the logic to use the repository generation of the in-progress snapshot + 1 was error
prone because it would always fail the delete when the repository had a pending generation different from its safe generation when a snapshot started (leading to the snapshot finalizing at a
higher generation).

These issues (particularly that last point) can easily be reproduced by running `SLMSnapshotBlockingIntegTests` in a loop with current `master` (see #54766).

The snapshot resiliency test for concurrent snapshot creation and deletion was made to more
aggressively start the delete operation so that the above races would become visible.
Previously, the fact that deletes would never coincide with initializing snapshots resulted
in a number of the above races not reproducing.

This PR is the most consistent I could get snapshot deletes without changes to the state machine. The fact that aborted deletes will not put the delete operation in the cluster state before waiting for the snapshot to abort still allows for some possible (though practically very unlikely) races. These will be fixed by a state-machine change in upcoming work in #54705 (which will have a much simpler and clearer diff after this change).

Closes #54766

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/TransportDeleteSnapshotAction.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ public TransportDeleteSnapshotAction(TransportService transportService, ClusterS
 
     @Override
     protected String executor() {
-        return ThreadPool.Names.GENERIC;
+        return ThreadPool.Names.SAME;
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/TransportDeleteSnapshotAction.java:57]: No need to fork to the generic pool here any more, we instantly move to the cluster state thread now in the snapshots service. We'll use the generic pool there once we have to inspect the repository data

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2 (unrelated x-pack failure)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -970,61 +970,168 @@ private void failSnapshotCompletionListeners(Snapshot snapshot, Exception e) {
...
-            if (matchedEntry.isPresent() == false) {
-                Optional<SnapshotsInProgress.Entry> matchedInProgress = currentSnapshots(
-                    clusterService.state().custom(SnapshotsInProgress.TYPE), repositoryName, Collections.emptyList()).stream()
-                    .filter(s -> s.snapshot().getSnapshotId().getName().equals(snapshotName)).findFirst();
-                if (matchedInProgress.isPresent()) {
-                    matchedEntry = matchedInProgress.map(s -> s.snapshot().getSnapshotId());
-                    // Derive repository generation if a snapshot is in progress because it will increment the generation when it finishes
-                    repoGenId = matchedInProgress.get().repositoryStateId() + 1L;
+    public void deleteSnapshot(final String repositoryName, final String snapshotName, final ActionListener<Void> listener) {
+        logger.info("deleting snapshot [{}] from repository [{}]", snapshotName, repositoryName);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:983]: should we also log an info-level message once we have successfully completed the deletion?

File: server/src/main/java/org/elasticsearch/cluster/SnapshotDeletionsInProgress.java [hunk 3]
```diff
@@ -174,6 +175,8 @@ public Entry(Snapshot snapshot, long startTime, long repositoryStateId) {
             this.snapshot = snapshot;
             this.startTime = startTime;
             this.repositoryStateId = repositoryStateId;
+            assert repositoryStateId > RepositoryData.EMPTY_REPO_GEN :
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/cluster/SnapshotDeletionsInProgress.java:178]: We would incorrectly get a `-1` (empty repo gen) here when we deleted/aborted an initializing snapshot (because the repo gen is at `-2` during the snapshot INIT stage). This wouldn't have caused any corruption and only made deletes fail but still, this assertion would've avoided not catching this race for so long :)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 4]
```diff
@@ -970,61 +970,168 @@ private void failSnapshotCompletionListeners(Snapshot snapshot, Exception e) {
...
+            Snapshot runningSnapshot;
+
+            boolean abortedDuringInit = false;
+
+            @Override
+            public ClusterState execute(ClusterState currentState) {
+                SnapshotsInProgress snapshots = currentState.custom(SnapshotsInProgress.TYPE);
+                SnapshotsInProgress.Entry snapshotEntry = null;
+                if (snapshots != null) {
+                    for (SnapshotsInProgress.Entry entry : snapshots.entries()) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:996]: maybe add this a helper method to SnapshotsInProgress similar to `public Entry snapshot(final Snapshot snapshot)`

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 5]
```diff
@@ -970,61 +970,168 @@ private void failSnapshotCompletionListeners(Snapshot snapshot, Exception e) {
...
+                    } else {
+                        // no shards to wait for but a node is gone - this is the only case
+                        // where we force to finish the snapshot
+                        logger.debug("trying to delete completed snapshot with no finalizing shards - can delete immediately");
+                        shards = snapshotEntry.shards();
+                    }
+                    failure = snapshotEntry.failure();
+                }
+                return ClusterState.builder(currentState).putCustom(SnapshotsInProgress.TYPE,
+                    new SnapshotsInProgress(new SnapshotsInProgress.Entry(snapshotEntry, State.ABORTED, shards, failure))).build();
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1055]: I know that this was already the case before, but if we were to allow concurrent snapshots, this line here would be silently removing other snapshots. Let's make sure to preserve other snapshots so that we don't get nasty surprises in the future.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 6]
```diff
@@ -970,61 +970,168 @@ private void failSnapshotCompletionListeners(Snapshot snapshot, Exception e) {
...
+                                    new SnapshotMissingException(runningSnapshot.getRepository(), runningSnapshot.getSnapshotId(), e));
+                            }
+                        }
+                    }
+                ));
             }
-            deleteSnapshot(new Snapshot(repositoryName, matchedEntry.get()), listener, repoGenId, immediatePriority);
-        }, listener::onFailure));
+
+            private void tryDeleteExisting(Priority priority) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1095]: why is method defined at the previous cluster state update task level? I think I would prefer explicitly passing in the listener, and moving it up

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 7]
```diff
@@ -1050,81 +1157,15 @@ public ClusterState execute(ClusterState currentState) {
...
-                    }
-                    SnapshotsInProgress.Entry newSnapshot = new SnapshotsInProgress.Entry(snapshotEntry, State.ABORTED, shards, failure);
-                    clusterStateBuilder.putCustom(SnapshotsInProgress.TYPE, new SnapshotsInProgress(newSnapshot));
+                if (snapshots != null && snapshots.entries().isEmpty() == false) {
+                    // However other snapshots are running - cannot continue
+                    throw new ConcurrentSnapshotExecutionException(snapshot, "another snapshot is currently running cannot delete");
                 }
-                return clusterStateBuilder.build();
+                // add the snapshot deletion to the cluster state
+                return ClusterState.builder(currentState).putCustom(SnapshotDeletionsInProgress.TYPE,
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1166]: same here as before, let's preserve other deletions

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 6 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1095]: I mainly put it here to make it perfectly clear that we're only running this after trying to abort.  Also, we have the logic around the `runningSnapshot` field here so we can still log the `Waited for snapshot` ... warning. To me it just gets more confusing if we pull that to the top level because annoyingly enough it's still somewhat connected logically to what happened during the CS update.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:983]: Jup added one for abort and one for the actual delete if it happened now.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Sure extracted that logic :)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Sure, this logic looks somewhat different in the concurrent deletes branch already but at least this keeps the diff smaller logically later on :)

**Comment by original-brownbear** [comment]
Thanks @ywelsch , all addressed I think

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 8]
```diff
@@ -1042,7 +1043,12 @@ public ClusterState execute(ClusterState currentState) {
                     failure = snapshotEntry.failure();
                 }
                 return ClusterState.builder(currentState).putCustom(SnapshotsInProgress.TYPE,
-                    new SnapshotsInProgress(new SnapshotsInProgress.Entry(snapshotEntry, State.ABORTED, shards, failure))).build();
+                    new SnapshotsInProgress(snapshots.entries().stream().map(existing -> {
+                        if (existing.equals(snapshotEntry)) {
+                            return new SnapshotsInProgress.Entry(snapshotEntry, State.ABORTED, shards, failure);
+                        }
+                        return existing;
+                    }).toArray(SnapshotsInProgress.Entry[]::new))).build();
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1051]: there is also a list construcutor, so no need for the array conversion.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!
