### PR TITLE
Fix AdaptiveAllocationsScalerServiceTests.test_scaleDownToZero_whenNo…

### LINKED ISSUE #136907: [CI] AdaptiveAllocationsScalerServiceTests test_scaleDownToZero_whenNoRequests failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11314 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/p4qc6wij72y7m)
- [elasticsearch-periodic-platform-support #11262 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/zbau5epvsuboy)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ml:test" --tests "org.elasticsearch.xpack.ml.inference.adaptiveallocations.AdaptiveAllocationsScalerServiceTests.test_scaleDownToZero_whenNoRequests" -Dtests.seed=81687EF0CE1538A0 -Dtests.locale=kn-Knda-IN -Dtests.timezone=Canada/Atlantic -Druntime.java=25
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.inference.adaptiveallocations.AdaptiveAllocationsScalerServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test_scaleDownToZero_whenNoRequests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.mockito.exceptions.verification.TooFewActualInvocations: 
client.threadPool();
Wanted 2 times:
-> at org.elasticsearch.xpack.ml.inference.adaptiveallocations.AdaptiveAllocationsScalerServiceTests.test_scaleDownToZero_whenNoRequests(AdaptiveAllocationsScalerServiceTests.java:314)
But was 1 time:
-> at org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:239)

```

**Issue Reasons:**
- [8.19] 2 failures in test test_scaleDownToZero_whenNoRequests (0.6% fail rate in 332 executions)
- [8.19] 2 failures in step windows-2019_checkpart4_platform-support-windows (18.2% fail rate in 11 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic-platform-support (18.2% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes #136907

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/adaptiveallocations/AdaptiveAllocationsScalerServiceTests.java [hunk 1]
```diff
@@ -275,7 +275,7 @@ public void test_scaleDownToZero_whenNoRequests() {
             inferenceAuditor,
             meterRegistry,
             true,
-            ONE_SECOND,
+            2 * ONE_SECOND,
```
Comment (jan-elastic) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/adaptiveallocations/AdaptiveAllocationsScalerServiceTests.java:278]: These two settings:
- `timeIntervalSeconds` of `ONE_SECOND`
- `scaleToZeroAfterNoRequestsSeconds` of `ATOMIC_SECOND`

lead to a race condition. Adaptive allocations service checks after 1 second (the `timeIntervalSeconds`) whether there's been no request for 1 second (the `scaleToZeroAfterNoRequestsSeconds`).

On Unix-based systems this seems to always pass. Locally on my MacBook the `timeWithoutRequestsSeconds` is always something like 1.001 seconds, so the model is scaled to zero.

This test is probably failing on Windows builds on x86 hardware, because of a less precise system clock, see:
https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/high-resolution-timers#controlling-timer-accuracy. Not sure 100% sure, I'm no Windows expert by any means.

Increasing the `timeIntervalSeconds` to 2 seconds, and then checking whether there's been no request for 1 second, solves the issue. Unfortunately, this add 2 more seconds of unit test time, because the times are set in seconds instead of milliseconds.

**Review by prwhelan — APPROVED** [review]
