### PR TITLE
Finalize all snapshots completed by shard snapshot updates

### LINKED ISSUE #104939: [CI] SnapshotStressTestsIT testRandomActivities failing
Not the same as https://github.com/elastic/elasticsearch/issues/104072. The cluster state at failure suggests we've dropped a finalization task somehow (maybe related to a `node-left` event):

```
   1 ▽ (14) {cluster_uuid: "3iF3FzgnQbiZ4MEVUf_52w", version: 455, state_uuid: "XV_EtlP7Tp-3Yf4S5wFyYg", master_node: "SyU09oHfQdq6_ADzHuF9sw", blocks: {}, nodes: {…}, nodes_versions: […], nodes_features: […], metadata: {…}, routing_table: {…}, routing_nodes: {…}, snapshot_deletions: {…}, health: {…}, snapshots: {…}}
   2     cluster_uuid: "3iF3FzgnQbiZ4MEVUf_52w"
   3     version: 455
   4     state_uuid: "XV_EtlP7Tp-3Yf4S5wFyYg"
   5     master_node: "SyU09oHfQdq6_ADzHuF9sw"
   6     blocks: {}
   7   ▷ nodes: (4) {SyU09oHfQdq6_ADzHuF9sw: {…}, TBO2zztJRu2lpLoSDchIUQ: {…}, "o--_8jfeSTmH5ATd8cis_Q": {…}, n7WWMC0kTFOz6K6yuVroOw: {…}}
  82   ▷ nodes_versions: (4) [{…}, {…}, {…}, {…}]
 140   ▷ nodes_features: (4) [{…}, {…}, {…}, {…}]
 166   ▷ metadata: (9) {cluster_uuid: "3iF3FzgnQbiZ4MEVUf_52w", cluster_uuid_committed: true, cluster_coordination: {…}, templates: {…}, indices: {…}, repositories: {…}, "index-graveyard": {…}, persistent_tasks: {…}, reserved_state: {}}
1214   ▷ routing_table: (1) {indices: {"index-6": {…}, "index-0": {…}, "index-1": {…}, "index-3": {…}, "index-2": {…}, "index-4": {…}, "index-7": {…}, "index-5": {…}}}
1554   ▷ routing_nodes: (2) {unassigned: [], nodes: {…}}
1827   ▽ snapshot_deletions: (1) {snapshot_deletions: [{repository: "repo-1", snapshots: […], start_time: "2024-01-26T21:55:05.463Z", start_time_millis: 1706306105463, repository_state_id: 24, state: "WAITING"}]}
1828     ▽ snapshot_deletions: (1) [{repository: "repo-1", snapshots: […], start_time: "2024-01-26T21:55:05.463Z", start_time_millis: 1706306105463, repository_state_id: 24, state: "WAITING"}]
1829       ▽ [0]: (6) {repository: "repo-1", snapshots: […], start_time: "2024-01-26T21:55:05.463Z", start_time_millis: 1706306105463, repository_state_id: 24, state: "WAITING"}
1830           repository: "repo-1"
1831         ▽ snapshots: (4) ["snapshot-partial-49", "snapshot-partial-8", "snapshot-partial-10", "snapshot-partial-5"]
1832             [0]: "snapshot-partial-49"
1833             [1]: "snapshot-partial-8"
1834             [2]: "snapshot-partial-10"
1835             [3]: "snapshot-partial-5"
1837           start_time: "2024-01-26T21:55:05.463Z"
1838           start_time_millis: 1706306105463
1839           repository_state_id: 24
1840           state: "WAITING"
1844   ▷ health: (2) {disk: {…}, shard_limits: {…}}
1858   ▼ snapshots: (1) {snapshots: [{repository: "repo-1", snapshot: "snapshot-partial-34", uuid: "e2rqGJv-RTapmYZHofl-fw", include_global_state: true, partial: true, state: "SUCCESS", indices: […], start_time: "2024-01-26T21:55:14.716Z", start_time_millis: 1706306114716, repository_state_id: 24, shards: […], feature_states: [], data_streams: []}]}
1859     ▽ snapshots: (1) [{repository: "repo-1", snapshot: "snapshot-partial-34", uuid: "e2rqGJv-RTapmYZHofl-fw", include_global_state: true, partial: true, state: "SUCCESS", indices: […], start_time: "2024-01-26T21:55:14.716Z", start_time_millis: 1706306114716, repository_state_id: 24, shards: […], feature_states: [], data_streams: []}]
1860       ▽ [0]: (13) {repository: "repo-1", snapshot: "snapshot-partial-34", uuid: "e2rqGJv-RTapmYZHofl-fw", include_global_state: true, partial: true, state: "SUCCESS", indices: […], start_time: "2024-01-26T21:55:14.716Z", start_time_millis: 1706306114716, repository_state_id: 24, shards: […], feature_states: [], data_streams: []}
1861           repository: "repo-1"
1862           snapshot: "snapshot-partial-34"
1863           uuid: "e2rqGJv-RTapmYZHofl-fw"
1864           include_global_state: true
1865           partial: true
1866           state: "SUCCESS"
1867         ▷ indices: (8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
1901           start_time: "2024-01-26T21:55:14.716Z"
1902           start_time_millis: 1706306114716
1903           repository_state_id: 24
1904         ▽ shards: (19) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
1905           ▷ [0]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "TOdX3wdgRCiISfDoBdxJSA", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1916           ▷ [1]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "GeXG7ci9SbuhRzVuoz2j0A", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1927           ▷ [2]: (6) {index: {…}, shard: 2, state: "FAILED", generation: "UGF5HAe5RDmvkMpM2LpCkw", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1938           ▷ [3]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "C59sEw0WTNSObp24ZhRhdw", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1949           ▷ [4]: (6) {index: {…}, shard: 4, state: "FAILED", generation: "56s0k5MTQimT2kt4MAOgVg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1960           ▷ [5]: (6) {index: {…}, shard: 3, state: "FAILED", generation: "yZafCREsT5ColMIHdYvEeg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1971           ▷ [6]: (6) {index: {…}, shard: 2, state: "FAILED", generation: "J1Y7sqi_R6WQYNB74JwiSg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1982           ▷ [7]: (6) {index: {…}, shard: 1, state: "FAILED", generation: "jGyO3iITTaWQpe_kNoiw_Q", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
1993           ▷ [8]: (6) {index: {…}, shard: 1, state: "FAILED", generation: "aTmdCOpwSuSLcz35XqOKpg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2004           ▷ [9]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "3pPnCXohQtu0F-l8t8_ibg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2015           ▷ [10]: (6) {index: {…}, shard: 0, state: "MISSING", generation: "C-FSij6JRLKp86r9KEInRQ", node: null, reason: "primary shard is not allocated"}
2026           ▷ [11]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "7qj2AuiDRIORdetYE3Rtuw", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2037           ▷ [12]: (6) {index: {…}, shard: 3, state: "FAILED", generation: "m69FC_knQni0zOJWQCAKIg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2048           ▷ [13]: (6) {index: {…}, shard: 2, state: "FAILED", generation: "So1Gnk0YSkKGhgX7rRBcvw", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2059           ▷ [14]: (6) {index: {…}, shard: 1, state: "FAILED", generation: "_pNn0VxDR5Gj3ehR-d2kCg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2070           ▷ [15]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "l4eh9ypOQniwYlP9ySOcYg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2081           ▷ [16]: (6) {index: {…}, shard: 2, state: "FAILED", generation: "X8WtbMerSwm7XRJh_E5Itg", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2092           ▷ [17]: (6) {index: {…}, shard: 1, state: "FAILED", generation: "NmSyXaavRQKPywGYFhfUdw", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2103           ▷ [18]: (6) {index: {…}, shard: 0, state: "FAILED", generation: "Rf5BOCSgScSXBY3r3cxA0Q", node: "TBO2zztJRu2lpLoSDchIUQ", reason: "node left the cluster during snapshot"}
2115           feature_states: []
2116           data_streams: []
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/ed4zqzurtbpn6/tests/:server:internalClusterTest/org.elasticsearch.snapshots.SnapshotStressTestsIT/testRandomActivities

**Reproduction line:**
```
gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SnapshotStressTestsIT.testRandomActivities" -Dtests.seed=25353760A7947592 -Dtests.locale=ms-MY -Dtests.timezone=Jamaica -Druntime.java=21
```

**Applicable branches:**
main, 8.12

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.snapshots.SnapshotStressTestsIT#testRandomActivities`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRandomActivities'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.snapshots.SnapshotStressTestsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: failed to acquire all permits: [repo-1, snapshot-partial-8, snapshot-partial-10, snapshot-partial-5, node_s3, node_s2, node_s1, node_s0]

  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.snapshots.SnapshotStressTestsIT$TrackedCluster.run(SnapshotStressTestsIT.java:346)
  at org.elasticsearch.snapshots.SnapshotStressTestsIT.testRandomActivities(SnapshotStressTestsIT.java:87)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today when processing a batch of `ShardSnapshotUpdate` tasks each
update's listener considers whether the corresponding snapshot has
completed and, if so, it enqueues it for finalization. This is somewhat
inefficient since we may be processing many shard snapshot updates for
the same few snapshots, but there's no need to check each snapshot for
completion more than once. It's also insufficient since the completion
of a shard snapshot may cause the completion of subsequent snapshots too
(e.g. they can go from state `QUEUED` straight to `MISSING`).

This commit detaches the completion handling from the individual shard
snapshot updates and instead makes sure that any snapshot that reaches a
completed state is enqueued for finalization.

Closes #104939

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/SnapshotResiliencyTests.java [hunk 1]
```diff
@@ -1230,6 +1242,142 @@ public void testRunConcurrentSnapshots() {
         }
     }
 
+    public void testSnapshotCompletedByNodeLeft() {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/snapshots/SnapshotResiliencyTests.java:1245]: Rather than adding a test that reliably reproduces the failure in https://github.com/elastic/elasticsearch/issues/104939 I've elected to write this more general test with enough randomisation to cover a variety of similar situations too. It does reproduce the failure in https://github.com/elastic/elasticsearch/issues/104939 much more frequently than `SnapshotStressTestsIT`, but even so it might take a few hundred iterations to hit the problem.

**Review by ywangd — COMMENTED** [review]
The changes look fine on its own. But I could use some help to understand how the original code led to CI failure. Thanks!

**Comment by ywangd** [comment]
I wrote a long comment only to realize that I did not send it out when posting the overall comment ... I'll post it again ...

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -3159,7 +3169,11 @@ SnapshotsInProgress computeUpdatedState() {
                 }
                 final List<SnapshotsInProgress.Entry> newEntries = new ArrayList<>(oldEntries.size());
                 for (SnapshotsInProgress.Entry entry : oldEntries) {
-                    newEntries.add(applyToEntry(entry, updates.getValue()));
+                    final var newEntry = applyToEntry(entry, updates.getValue());
+                    newEntries.add(newEntry);
+                    if (newEntry != entry && newEntry.state().completed()) {
+                        newlyCompletedEntries.add(newEntry);
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:3175]: I could use help to better understand two piece of information. 
1. How come a shard update for one snapshot end up updating the state of another snapshot?
2. How come a `ShardSnapshotUpdate` processed unassigned shards before `SnapshotsService#processExternalChanges`?

Using [this particular failure](https://github.com/elastic/elasticsearch/issues/104939#issuecomment-1918884740) as an example, I think the answer to the first question is the following sequence of calls when processing shard updates for `snapshot-clone-11`:

https://github.com/elastic/elasticsearch/blob/d1ca37a3fe29f93fecd6252f91390691601f8536/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L3236

https://github.com/elastic/elasticsearch/blob/d1ca37a3fe29f93fecd6252f91390691601f8536/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L3345

https://github.com/elastic/elasticsearch/blob/d1ca37a3fe29f93fecd6252f91390691601f8536/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L3380

https://github.com/elastic/elasticsearch/blob/d1ca37a3fe29f93fecd6252f91390691601f8536/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L3401

In `initShardSnapshotStatus`, we found out that the shard is unassigned and marked its state to `MISSING` which in turns leads to `snapshot-paritial-12` being marked as `SUCCESS`.

Is this correct?

Assuming the above is more or less correct, now for question 2, I don't understand how the unassigned shard was *not* processed `processExternalChanges` which is called inside `SnapshotsService#applyClusterState`. This is where my lack of knowledge for cluster coordination hurts ... I thought cluster state update and apply run strictly one after the other, i.e. after a cluster state update, the apply runs before computing another update. In regular case, node disconnection is handled by `processExternalChanges` which ends snapshots based on the missing shards. How come `ShardSnapshotUpdate` sees the missing shard first in this case? You said

> while that update was in flight the node left the cluster so the other shard snapshots moved to state MISSING in the same update

This seems to say while `ShardSnapshotUpdate` is running, the cluster state changed under it? Shard update uses a dedicated master task queue which I assume they cannot be processed together with node left? Sorry this all sounds pretty silly. I must have some serious/key misunderstanding somewhere.  I'd appreciate if you could help clarify the sequence/order of events here. Thanks!

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:3175]: > In initShardSnapshotStatus, we found out that the shard is unassigned and marked its state to MISSING which in turns leads to snapshot-paritial-12 being marked as SUCCESS.

Correct.

> I don't understand how the unassigned shard was not processed processExternalChanges 

Because when `processExternalChanges` was called `[index-0][1]` was still in state `INIT` in `snapshot-clone-11`, and clones don't run on the data nodes so don't get cancelled on a node-left event, which means that the subsequent operations on `[index-0][1]` also remain unchanged (in state `QUEUED`). But then when that shard clone completes it moves to `SUCCESS` and the later `QUEUED` states all move to `MISSING` via the process you describe.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 3]
```diff
@@ -3178,12 +3192,21 @@ SnapshotsInProgress computeUpdatedState() {
...
-                        });
+                try (
+                    var onCompletionRefs = new RefCountingRunnable(
+                        () -> completionHandler.handleCompletion(result, needsReroute, newlyCompletedEntries, updatesByRepo.keySet())
+                    )
+                ) {
+                    for (final var taskContext : batchExecutionContext.taskContexts()) {
+                        if (taskContext.getTask() instanceof ShardSnapshotUpdate task) {
+                            final var ref = onCompletionRefs.acquire();
+                            needsReroute = true;
```
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Ah nice, good point. I found that flag irksome indeed, dropped in a0db49e7ed9.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:3172]: We sync in a separate channel and it helped me to understand why `snapshot-partial-12` did not get finished during `processExternalChanges`. Because (1) the shard did not get marked as a `knownFailure` since it was part of a clone and (2) `snapshot-partial-12` at that time still has the shard as `UNASSIGNED_QUEUED` which does not has a nodeId and hence does not respond to node leaving.

**Review by ywangd — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
Backported to 8.12 in a14ad5fbb6768ee3ce3bb6083b91d86b85a2676a.
