### PR TITLE
Decrease restore rate limit value to enforce its usage on SearchableSnapshotsIntegTests#testMaxRestoreBytesPerSecIsUsed

### LINKED ISSUE #59287: SearchableSnapshotsIntegTests#testMaxRestoreBytesPerSecIsUsed fails
**Build scan**: https://gradle-enterprise.elastic.co/s/ms5gfdp45aeng

**Repro line**:

```
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed" \
  -Dtests.seed=656DFBB9A0CD6D47 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-NI \
  -Dtests.timezone=Africa/Bangui \
  -Druntime.java=8
```

**Reproduces locally?**: no

**Applicable branches**: `7.8`, `7.x`, `master`

**Failure history**: Happened [seven times in the last six months](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20test:%22testMaxRestoreBytesPerSecIsUsed%22%20AND%20class:%22%20org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests%22%20AND%20stacktrace:%22a%20value%20greater%20than%20%3C0L%3E%22'),sort:!(time,desc))) (two times on a PR build)

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>
	at __randomizedtesting.SeedInfo.seed([656DFBB9A0CD6D47:483909AB92529A15]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testMaxRestoreBytesPerSecIsUsed(SearchableSnapshotsIntegTests.java:370)
```

### PR DESCRIPTION
**Pull request by fcofdez**
It seems like the rate limit value for `max_restore_bytes_per_sec` is
too close to the size of some of the generated shards, so in certain
scenarios the rate limiter isn't triggered.

Fixes #59287

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java [hunk 1]
```diff
@@ -350,13 +350,12 @@ public void testCanMountSnapshotTakenWhileConcurrentlyIndexing() throws Exceptio
...
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/59287")
     public void testMaxRestoreBytesPerSecIsUsed() throws Exception {
         final String repositoryName = randomAlphaOfLength(10).toLowerCase(Locale.ROOT);
         final Settings.Builder repositorySettings = Settings.builder().put("location", randomRepoPath());
         final boolean useRateLimits = randomBoolean();
         if (useRateLimits) {
-            repositorySettings.put("max_restore_bytes_per_sec", new ByteSizeValue(10, ByteSizeUnit.KB));
+            repositorySettings.put("max_restore_bytes_per_sec", new ByteSizeValue(5, ByteSizeUnit.KB));
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java:358]: Do you think that we could find the "best" value here if we don't randomize anything when indexing documents later in this test so that we have more predictable shard file sizes?

Comment (DaveCTurner) [reply x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java:358]: Alternatively, could we defer repository creation until after we've created the index and then compute a good value for the throttle based on the index size?

Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsIntegTests.java:358]: Good idea, it also takes care of any future Lucene change that would impact file sizes.

**Comment by fcofdez** [comment]
Thanks for the review @tlrx @DaveCTurner, I went ahead and modified the test to use the actual shard sizes instead of a  constant 👍 .

**Review by tlrx — APPROVED** [review]
LGTM, thanks Francisco
