### PR TITLE
stop throwing an IllegalStateException for unrecognized steps

### LINKED ISSUE #32181: Test and Verify whether PolicyStepsRegistry is used safely in ILM
summary of problem: CS-IndexLifecycleMetadata, indexMetaData-current_step info, and policyRegistry can get out of sync

The PolicyStepsRegistry for an IndexLifecycleService seems to be able to be both updated 
and used at the same time. It seems as though it is possible that the execution bits of the service can be attempting to read from the registry at the same time that updates are occurring.

Updates to the registry happen when [cluster-state-appliers are called](https://github.com/elastic/elasticsearch/blob/fc2f982542a3a265a6ff145885ba28303ff22f10/x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java#L126).

Reads to the registry happen in two cases

1. [IndexLifecycleRunner#runPolicy](https://github.com/elastic/elasticsearch/blob/ebf0dd45d2606d14d08d0ed5f6b436ed56d4e906/x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java#L65).
2. [ExecuteStepsUpdateTask#execute](https://github.com/elastic/elasticsearch/blob/fc2f982542a3a265a6ff145885ba28303ff22f10/x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java#L53)

There is nothing preventing the system from being in both the update and/or (1),(2) at the same time.

It is also not clear from existing tests whether this is actually a problem. From a rough peek I see an IllegalStateException to be thrown in two scenarios
A. API deletes/changes an action in a policy such that a step is removed
B. API adds a policy to an index and `runPolicy` is executed from the scheduled-job before the cluster-state-applier populates the registry
C. API changes policy such that the index is said to currently be on a specific step that has not yet been populated by the applier (similar to B.)
D. runPolicy was triggered after the node was un-elected master and there is a stale representation of the truly up-to-date cluster state with changes to policies that resulted in indices moving to new steps that didn't exist before in the stale registry

I do not think this to be an issue in (2) since it is fine if the execution task fails and tries again in a following iteration. One costly way to stop the `IllegalStateException` is to re-compute the steps on every run. Other ways may, indeed, exist, but further investigation is warranted.

### PR DESCRIPTION
**Pull request by talevy**
Since the reason for a step not being found in a registry may be due to staleness of the
registry between it and the cluster state, we do not want to throw an IllegalStateException.

Staleness is something that will be self-healing after follow-up applications of the cluster state
updates, so this is a recoverable issue that should log a warning instead of throwing an exception

Closes #32181.

### CODE REVIEW

File: x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java [hunk 1]
```diff
@@ -64,8 +64,11 @@ public void runPolicy(String policy, IndexMetaData indexMetaData, ClusterState c
         }
         Step currentStep = getCurrentStep(stepRegistry, policy, indexSettings);
         if (currentStep == null) {
-            throw new IllegalStateException(
-                "current step for index [" + indexMetaData.getIndex().getName() + "] with policy [" + policy + "] is not recognized");
+            // This may happen in the case that there is invalid ilm-step index settings or the stepRegistry is out of
+            // sync with the current cluster state
+            logger.warn("current step [" + getCurrentStepKey(indexSettings) + "] for index [" + indexMetaData.getIndex().getName()
```
Comment (talevy) [inline x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: Although I love that we want to provide the step info here, I have mixed feelings about the assertions that exist inside of `getCurrentStepKey`. I think this should be changed to throwing `IllegalStateException`. what do you think @colings86?

File: x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java [hunk 2]
```diff
@@ -64,8 +64,11 @@ public void runPolicy(String policy, IndexMetaData indexMetaData, ClusterState c
         }
         Step currentStep = getCurrentStep(stepRegistry, policy, indexSettings);
```
[the remark this answers is not in the document]
Comment (colings86) [reply x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: I think we probably need to make `PolicyStepsRegistry.getStep()` return `null` if the step is missing (in much the same way that a map returns `null` for a missing key. Then we'll have to check for `null`:
* here in `IndexLifecycleRunner.runPolicy()` and if its `null` log a warning and return
* In `IndexLifecycleRunner.moveClusterStateToStep()` where I think we should do the same as above
* In `ExecuteStepsUpdateTask.execute()` where we should log the warning if its `null` but return the cluster state up to changing the current step so we don't lose all the progress made on the previous cluster state steps

wdyt?

[the remark this answers is not in the document]
Comment (talevy) [reply x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: that is what I was thinking as well. Just wanted to double check with you before I take that route

**Comment by talevy** [comment]
test this please

File: x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java (hunk 1 above)
Comment (colings86) [reply x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: I think the assertions are fine because ILM is in full control of the phase, action and step settings (they are INTERNAL settings so can't be touched by a user and will soon be moved to a custom index metadata object further locking down access to them. Therefore, I don't think its necessary to check that if one is set all three are set in production code but its useful to have the check in testing to make sure we don't do something silly so assertions feel right to me.

File: x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java [hunk 3]
```diff
@@ -180,10 +183,9 @@ static ClusterState moveClusterStateToStep(String indexName, ClusterState curren
             throw new IllegalArgumentException("index [" + indexName + "] is not on current step [" + currentStepKey + "]");
         }
 
-        try {
-            stepRegistry.getStep(indexPolicySetting, nextStepKey);
-        } catch (IllegalStateException e) {
-            throw new IllegalArgumentException(e.getMessage());
+        Step nextStep = stepRegistry.getStep(indexPolicySetting, nextStepKey);
+        if (nextStep == null) {
+            throw new IllegalArgumentException("step [" + nextStepKey + "] with policy [" + indexPolicySetting + "] does not exist");
```
Comment (colings86) [inline x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: Could you explain why this still needs to throw an exception rather than just returning an unmodified cluster state? Also I know we threw an IllegalArgumentException before but it feels wrong to me since the user won't have supplied anything invalid

**Review by colings86 — COMMENTED** [review]
@talevy I left a few comments

File: x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java (hunk 3 above)
Comment (talevy) [reply x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: I am cool with that.

I still feel like IllegalArgumentException should be thrown to users of TransportMoveToStepAction. So I will push up a basic exception for that, and it will know that nothing "right" happened since the clusterStates will be the same instance

File: x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java [hunk 4]
```diff
@@ -185,7 +185,8 @@ static ClusterState moveClusterStateToStep(String indexName, ClusterState curren
 
         Step nextStep = stepRegistry.getStep(indexPolicySetting, nextStepKey);
         if (nextStep == null) {
-            throw new IllegalArgumentException("step [" + nextStepKey + "] with policy [" + indexPolicySetting + "] does not exist");
+            // stepRegistry may not be up-to-date with latest policies/steps in cluster-state
+            return currentState;
```
Comment (colings86) [inline x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: Sorry, I had not looked closely enough at what this method is used for. It seems that its only used for the "move to step" and retry APIs so actually its probably ok for this method to throw an exception directly. I had thought before that we use this method for moving between steps normally.

I think we should throw directly here as the alternative of returning the same cluster state and then using that as an indication that the step is not recognised is a bit trappy. To ensure this method is kept only for API calls and not for normal execution maybe we can add a JavaDoc comment?

Comment (talevy) [reply x-pack/plugin/index-lifecycle/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunner.java]: OK. I will revert the latest commit and add comment

**Review by colings86 — APPROVED** [review]
LGTM

**Comment by talevy** [comment]
thanks!
