### PR TITLE
ESQL: Grow heap attack tests

### LINKED ISSUE #121465: [CI] HeapAttackIT testLookupExplosionBigStringManyMatches failing
**Build Scans:**
- [elasticsearch-intake #17350 / part1](https://gradle-enterprise.elastic.co/s/bdvkpxls5eqqy)
- [elasticsearch-pull-request #55036 / part-1](https://gradle-enterprise.elastic.co/s/n6wpsqjdtanlq)
- [elasticsearch-periodic-platform-support #6166 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/nk46ulfdug6ve)
- [elasticsearch-periodic-platform-support #6166 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/mbuxsvpypnfsq)
- [elasticsearch-periodic #6163 / openjdk22_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/szcrxrdp34bmo)
- [elasticsearch-periodic-platform-support #6145 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/ctqss55kqavvs)
- [elasticsearch-periodic #6149 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/px4a7mp7aadna)
- [elasticsearch-periodic-platform-support #6124 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/ysfokeg5gnvmo)
- [elasticsearch-periodic-platform-support #6110 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/5fi7bzmnahscw)

**Reproduction Line:**
```
./gradlew ":test:external-modules:test-esql-heap-attack:javaRestTest" --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testLookupExplosionBigStringManyMatches" -Dtests.seed=5BB5426D4277F085 -Dtests.locale=ky-Cyrl-KG -Dtests.timezone=America/North_Dakota/Center -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testLookupExplosionBigStringManyMatches),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown
```

**Issue Reasons:**
- [8.18] 9 failures in test testLookupExplosionBigStringManyMatches (1.8% fail rate in 506 executions)
- [8.18] 2 failures in pipeline elasticsearch-periodic (14.3% fail rate in 14 executions)
- [8.18] 4 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 14 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nik9000**
This causes the ESQL heap attack tests to grow their memory usage if they first don't cause a circuit breaking exception. It just tries again with more data. That's slow, but it should stop this from failing quite as much. And it'll give us even more information about failures.

Closes #121465

### CODE REVIEW

File: test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackIT.java [hunk 1]
```diff
@@ -191,36 +191,53 @@ public void testSortByManyLongsTooMuchMemoryAsync() throws IOException {
...
+    private void assertCircuitBreaks(TryCircuitBreaking tryBreaking, MapMatcher responseMatcher) throws IOException {
+        int attempt = 1;
+        while (attempt <= MAX_ATTEMPTS) {
+            try {
+                Map<String, Object> response = tryBreaking.attempt(attempt);
+                logger.error("{}: should circuit broken but got {}", attempt, response);
+                attempt++;
+            } catch (ResponseException e) {
+                Map<?, ?> map = responseAsMap(e.getResponse());
+                logger.info("expected circuit breaker {}", map);
```
Comment (idegtiarenko) [inline test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackIT.java:223]: This is expected, I wonder if we should log it at all...

File: test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackIT.java [hunk 2]
```diff
@@ -191,36 +191,53 @@ public void testSortByManyLongsTooMuchMemoryAsync() throws IOException {
...
+                assertMap(map, responseMatcher);
+                return;
+            }
+        }
+        fail("giving up circuit breaking after " + attempt + " attempts");
+    }
```
Comment (idegtiarenko) [inline test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackIT.java:229]: Nice!

**Review by idegtiarenko — APPROVED** [review]

File: test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackIT.java (hunk 1 above)
Comment (nik9000) [reply test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackIT.java:223]: Yeah, it really isn't worth it. We get it from the assertion bit if there's a failure.

**Comment by nik9000** [comment]
run elasticsearch-ci/part-1

**Comment by nik9000** [comment]
@elasticsearchmachine, run elasticsearch-ci/part-1

**Comment by nik9000** [comment]
Backports:
9.0: https://github.com/elastic/elasticsearch/pull/121830
8.19: https://github.com/elastic/elasticsearch/pull/121831
8.18: https://github.com/elastic/elasticsearch/pull/121832
