### PR TITLE
Fix indices shown in _cat/indices

### LINKED ISSUE #39933: cat/indices no longer shows indices currently being restored
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 8.0.0-SNAPSHOT, Build: default/tar/4957cad/2019-03-11T15:48:39.514013Z, JVM: 1.8.0_151`

**Plugins installed**: []
`repository_gcs`

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

This is a usability nit.

Restoring a large snapshot may take some time. During this period you can no longer see the restoring indices listed in `GET _cat/indices` therefore you may think that the restore might not have been initiated.

If you re-run the restore command, you get the error below saying that the index already exists.

This is a change from 6.x where the indices would be listed immediately by `GET _cat/indices` with their health as yellow. This was a convenient way to see that the restoration was in progress, especially for snapshots with multiple indices. 

Perhaps the index list behaviour could be returned to previous, or a more useful error message be displayed to explain that the restore is in progress.

```
{
  "error": {
    "root_cause": [
      {
        "type": "snapshot_restore_exception",
        "reason": "[my_repo:a_large_snapshot/fYI6EIhEQYm0E_tbDiOEgA] cannot restore index [filebeat-2019] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"
      }
    ],
    "type": "snapshot_restore_exception",
    "reason": "[my_repo:a_large_snapshot/fYI6EIhEQYm0E_tbDiOEgA] cannot restore index [filebeat-2019] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"
  },
  "status": 500
}
```

Found in 3 node cluster.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `POST _snapshot/my_repo/a_large_snapshot/_restore` -- restore a large snapshot
 2. `GET _cat/indices` -- notice indices are not yet listed
 3. `POST _snapshot/my_repo/a_large_snapshot/_restore` -- re-run the restore again, before the first step has had a chance to finish.

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by tlrx**
After two recent changes (#38824 and #33888), the `_cat/indices` API no longer report information for active recovering indices and non-replicated closed indices. It also misreport replicated closed indices that are potentially not authorized for the user.

This commit changes how the cat action works by first using the Get Settings API in order to resolve authorized indices. It then uses the Cluster State, Cluster Health and Indices Stats APIs to retrieve information about the indices.

Since the health and the stats of the indices are not guaranteed to exist (ex: recovering indices have a health status but no index stats; non-replicated closed indices have no health and no stats) they are shown only if they are present.

Closes #39933

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
> Note that this API now requires an additional `indices:admin/get` privilege.

This is a breaking change but I don't come with a better solution to correctly resolved authorized indices before retrieving other information.

**Comment by tlrx** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 1]
```diff
@@ -85,48 +86,167 @@ protected void documentation(StringBuilder sb) {
...
+                sendClusterHealthRequest(concreteIndices, indicesOptions, local, masterNodeTimeout, client, step2);
+            }, listener::onFailure);
+
+            final StepListener<Map<String, IndexStats>> step3 = new StepListener<>();
+            step2.whenComplete(indicesHealths -> {
+                String[] concreteIndices = indicesHealths.keySet().toArray(Strings.EMPTY_ARRAY);
+                sendIndicesStatsRequest(concreteIndices, indicesOptions, includeUnloadedSegments, client, step3);
+            }, listener::onFailure);
+
+            final StepListener<Map<String, IndexMetaData>> step4 = new StepListener<>();
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: could step 2, 3 and 4 run in parallel?

**Comment by ywelsch** [comment]
Can we use the cluster health request to resolve the authorized indices instead of using the newly added Get Index request?

**Comment by tlrx** [comment]
> Can we use the cluster health request to resolve the authorized indices instead of using the newly added Get Index request?

The way the Cluster Health API works prevent us from using it to resolve the authorized indices: when using the Cat Indices API, the user requires the appropriate privilege to get the cluster state (`cluster:monitor/state`) and the cluster health (`cluster:monitor/health`). Those Cluster  APIs provide a cluster-wide view and don't re-filter indices given index privileges (because the Cluster API itself requires a "higher" privilege), so a user that has the privilege to access the cluster state (or the cluster health) can access the state (or health) of all indices. Then the _cat/indices tries to be smart and filters out indices as the Indices Stats API would do but even if both APIs provides a similar output I don't think we should mix them.

I'm not a big fan of adding another privilege and call for this _cat/indices but I don't have a better idea for now. I'm waiting for some ideas @albertzaharovits :)

**Comment by albertzaharovits** [comment]
Hi @tlrx ,
I think we can use the _get index settings_ API (`TransportGetSettingsAction`) to get the set of authorized indices, because, as you said, _cluster health_ and _cluster state_ are "cluster-wide" and are not confined by index permissions and that _get index stats_ is also not suitable, because we wish to display indices that are not returned by this API (recovering indices and non-replicated closed indices). If we learn of some indices that are not returned by the _get index settings_ API, then we can simply list all of them irrespective of index privileges. My reasoning is that if the user has privileges to run this API (`_cat/indices`) at all, it can also call the _cluster state_ on its own and "see" the indices there, so the hiding we're fighting with here is just a "nice to have".

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@albertzaharovits Thanks for your suggestion, it seems to work nicely :). Can you have a look please?

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 2]
```diff
@@ -85,52 +90,166 @@ protected void documentation(StringBuilder sb) {
...
+                        concreteIndices[i++] = cursor.key;
                     }
-                });
+
+                    final GroupedActionListener<ActionResponse> groupedListener = createGroupedListener(request, 4, listener);
+                    groupedListener.onResponse(getSettingsResponse);
+
+                    sendIndicesStatsRequest(concreteIndices, indicesOptions, includeUnloadedSegments, client, groupedListener);
+                    sendClusterStateRequest(concreteIndices, indicesOptions, local, masterNodeTimeout, client, groupedListener);
+                    sendClusterHealthRequest(concreteIndices, indicesOptions, local, masterNodeTimeout, client, groupedListener);
```
Comment (albertzaharovits) [inline server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: Why do we use the `concreteIndices` rather than `indices` with `indicesOptions`. There is a comment in the original code:
```
...
// This behavior can be ensured by letting the cluster health and indices
// stats requests re-resolve the index names with the same indices options
// that we used for the initial cluster state request (strictExpand).
```
that I believe still applies (if wildcards expand to indices that are subsequently deleted, we should not error).

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 3]
```diff
@@ -85,52 +90,166 @@ protected void documentation(StringBuilder sb) {
...
+            @Override
+            public void onResponse(final ClusterStateResponse response) {
+                listener.onResponse(response);
+            }
+
+            @Override
+            public void onFailure(final Exception e) {
+                listener.onFailure(e);
+            }
+        });
```
Comment (albertzaharovits) [inline server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: this can be simplified.

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 4]
```diff
@@ -85,52 +90,166 @@ protected void documentation(StringBuilder sb) {
...
+
+        client.admin().cluster().health(request, new ActionListener<>() {
+            @Override
+            public void onResponse(final ClusterHealthResponse response) {
+                listener.onResponse(response);
+            }
+
+            @Override
+            public void onFailure(final Exception e) {
+                listener.onFailure(e);
```
Comment (albertzaharovits) [inline server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: this can be simplified to `client.admin().cluster().health(request, listener)`
there are 3 occurrences of this.

**Review by albertzaharovits — APPROVED** [review]
I believe we should keep the original behavior with respect to wildcards that are expanded with the same options by all APIs. This prevents errors when the wildcard expands to indices that are subsequently removed before the other calls. This is my only objection and in case I'm not mistaken can be rectified easily.

I'll LGTM for now.
Thank you Tanguy for tackling fallouts of my changes!

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 2 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: Yes, this is not good. I restored the original comment and behavior in /4eb76f53d1d911f5c2dd21cecb27354b0ec8fe44

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 4 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: There's still a need to downcast - I pushed ff35567b66843212b5212e920278442b90d99557

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 1 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: Yes, I used a `GroupedActionListener` for this.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 5]
```diff
@@ -85,50 +89,139 @@ protected void documentation(StringBuilder sb) {
...
+
+                @Override
+                public void onFailure(final Exception e) {
+                    listener.onFailure(e);
+                }
+            });
+        };
+    }
+
+    private void sendGetSettingsRequest(final String[] indices,
```
[the remark this answers is not in the document]
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: I pushed d93c0872038cbfd7a789de57d999caf9dca8474e
