### PR TITLE
Correctly handle nulls when fetching multiple values from source

### LINKED ISSUE #68979: Retrieving a field with null value triggers a NPE
Indexing the following document:
```
{
    "a": {"b": 0},
    "a.b": null
}
```
and retrieving it with:
```
{
    "fields": [
        {
            "field": "a.b"
        }
    ]
}
```
will fail due to:
```
Caused by: java.lang.NullPointerException
        at java.util.ArrayDeque.addLast(ArrayDeque.java:303) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at java.util.ArrayDeque.copyElements(ArrayDeque.java:329) ~[?:?]
        at java.util.ArrayDeque.addAll(ArrayDeque.java:324) ~[?:?]
        at org.elasticsearch.index.mapper.SourceValueFetcher.fetchValues(SourceValueFetcher.java:67) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.fetch.subphase.FieldFetcher.fetch(FieldFetcher.java:144) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.fetch.subphase.FetchFieldsPhase$1.process(FetchFieldsPhase.java:57) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:146) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:461) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:437) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        ... 6 more
```

(Simply stripping the `null`s [before enqueuing](https://github.com/elastic/elasticsearch/blob/947f1ebb3599bef96a285e3c871b365b823450fe/server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java#L67) the values seems to fix it.)

### PR DESCRIPTION
**Pull request by romseygeek**
If a field contains a single `null` value that would have been substituted via
a mapper's configured `null_value`, then we return this configured value in
that mapper's value fetcher.  However, we also need to handle the case where
the field contains an array, one of which is `null`.

Fixes #68979

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java [hunk 1]
```diff
@@ -58,7 +58,13 @@ public SourceValueFetcher(String fieldName, SearchExecutionContext context, Obje
             while (queue.isEmpty() == false) {
                 Object value = queue.poll();
                 if (value instanceof List) {
-                    queue.addAll((List<?>) value);
+                    for (Object o : (List<?>) value) {
+                        if (o != null) {
+                            queue.add(o);
+                        } else if (nullValue != null) {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java:64]: Could we add a test to cover this case where the mappings provide a `null_value`? I'm not totally sure this logic is needed (it may be handled already in `SourceLookup#extractValue`).

**Review by jtibshirani — COMMENTED** [review]
Thank you @romseygeek !

File: server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java (hunk 1 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java:64]: There is one in FieldFetcherTests?  The part that checks `nullable_long_field`.

Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java:64]: Sorry about that, I read before coffee :) I am able to remove this 'else' block around `nullValue` and still the test passes. Do we need to strengthen the test, or can this be removed?

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java:64]: Oh, interesting, it looks as though `extractValue` already handles this case so we can remove it.

**Review by jtibshirani — APPROVED** [review]
