### PR TITLE
[CI] Fix failing PrevalidateShardPathIT#testCheckShards

### LINKED ISSUE #92056: [CI] PrevalidateShardPathIT testCheckShards failing
It does not reproduce all the time.

**Build scan:**
https://gradle-enterprise.elastic.co/s/wmtwlbi22jcpk/tests/:server:internalClusterTest/org.elasticsearch.cluster.PrevalidateShardPathIT/testCheckShards

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.PrevalidateShardPathIT.testCheckShards" -Dtests.seed=6CB113203E6F8BCF -Dtests.locale=ar-MA -Dtests.timezone=UTC -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.PrevalidateShardPathIT&tests.test=testCheckShards

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([6CB113203E6F8BCF:DDA935863B6A8FBE]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.cluster.PrevalidateShardPathIT.lambda$testCheckShards$1(PrevalidateShardPathIT.java:71)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1112)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1085)
  at org.elasticsearch.cluster.PrevalidateShardPathIT.testCheckShards(PrevalidateShardPathIT.java:65)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by pxsalehi**
The test fails sometimes since the removal of the shards after
relocation does not always succeed. This change enforces some cluster
state update to allow retrying the shard directory removal and avoids
the WindowsFS in the test since it has known issues that cause test
failures.

Closes https://github.com/elastic/elasticsearch/issues/92056

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java [hunk 1]
```diff
@@ -63,12 +71,22 @@ public void testCheckShards() throws Exception {
...
+                assertThat(resp2.getNodes().size(), equalTo(1));
+                assertThat(resp2.getNodes().get(0).getNode().getId(), equalTo(node2Id));
+                assertTrue("There should be no failures in the response", resp.failures().isEmpty());
+                assertTrue("The relocation source node should have removed the shard(s)", resp2.getNodes().get(0).getShardIds().isEmpty());
+            } catch (AssertionError e) {
+                // Removal of shards which are no longer allocated to the node is attempted on every cluster state change in IndicesStore.
+                // If for whatever reason the removal is not triggered (e.g. not enough nodes reported that the shards are active) or it
+                // temporarily failed to clean up the shard folder, we need to trigger another cluster state change for this removal to
+                // finally succeed.
+                updateIndexSettings(indexName, Settings.builder().put("index.routing.allocation.exclude.name", "non-existent"));
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java:87]: I think we need to add a random bit to the exclude:

```suggestion
                updateIndexSettings(indexName, Settings.builder().put("index.routing.allocation.exclude.name", "non-existent" + randomAlphaOfLength(5)));
```

since index settings that change nothing should not result in cluster state changes.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java [hunk 2]
```diff
@@ -63,12 +71,22 @@ public void testCheckShards() throws Exception {
...
+                throw e;
+            }
+        }, 60, TimeUnit.SECONDS);
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java:90]: This seems quite high, would the default 10 secs not work out fine?

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java [hunk 3]
```diff
@@ -21,10 +22,17 @@
...
 import java.util.stream.Collectors;
 
 import static org.hamcrest.Matchers.equalTo;
 
+/*
+ * We rely on the shard directory being deleted after the relocation. This removal sometimes fails
+ * with "java.io.IOException: access denied" when using WindowsFS which seems to be a known issue.
+ * See {@link FileSystemUtilsTests}.
+ */
+@LuceneTestCase.SuppressFileSystems(value = "WindowsFS")
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java:35]: I wonder if the retrying below would not cure this regardless? IIUC, we catch such failures to delete and retry later.

If the API is not supported on windows, we should probably note it in the documentation.

**Review by henningandersen — COMMENTED** [review]
Left a few comments.

Can you update the title of the issue to be something that can be read out of context of the issue? That title seems to indicate a very important PR, while it just fixes a test.

Also, I'd prefer to add just a sentence to the description about what is fixed (perhaps your old title with a bit more context).

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java (hunk 1 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java]: Done in https://github.com/elastic/elasticsearch/pull/92112/commits/8a511a156cdc8ed879ebaa60d591d7c24fc37cf1.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java (hunk 2 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java]: I've reduced to 10, in case it happens we can increase it later.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java (hunk 3 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java:34]: Just retrying is still not enough and sometimes the test would still failed with "access denied exception". Which is why I ended up adding the suppress WindowsFS bit.

> If the API is not supported on windows, we should probably note it in the documentation.

If you mean the prevalidation API, I am not sure this has any implications for that. We only added this part (ensuring that the shards are removed after relocation) to just make sure [our assumptions are correct](https://github.com/elastic/elasticsearch/pull/91256#discussion_r1031386237). Which I think is, but we need this fix to make the test pass.

Comment (henningandersen) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java:34]: OK, though if we sometimes leave stuff around on windows, in essence this API may not work as reliably there. But I guess that is more of a problem of the relocation than this API.

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java (hunk 3 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/PrevalidateShardPathIT.java:34]: I think the API does what it should do. As long as it sees the shard directory it reports back so. Yes, I agree that the lingering existence of the directory is more a relocation issue, but to me it seems that also is retried in a reconciliation fashion upon cluster state changes. What would make the result of the prevalidation less likely to change quickly after responding is [this improvement that we talked about](https://github.com/elastic/elasticsearch/pull/91256#issuecomment-1306976226), which I'm still to write up as an issue.
