### PR TITLE
LTR - Fix explain failure when index has multiple shards 

### LINKED ISSUE #120739: LTR rescorer throws 'local model reference is null' on multi-shards index when explained is enabled
### Elasticsearch Version

\>= 8.15

### Installed Plugins

Nome

### Java Version

_bundled_

### OS Version

Not relevant

### Problem Description

When using a Learning to Rank (LTR) rescorer with the explain feature on an index with multiple shards, the machine learning model is not loaded during the fetch phase. This results in the following error:

```
Caused by: java.lang.IllegalStateException: local model reference is null, missing rewriteAndFetch before rescore phase?
	at org.elasticsearch.xpack.ml.inference.ltr.LearningToRankRescorer.explain(LearningToRankRescorer.java:150) ~[main/:?]
	at org.elasticsearch.search.fetch.subphase.ExplainPhase$1.process(ExplainPhase.java:47) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:182) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:89) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:194) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:84) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$12(SearchService.java:970) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:79) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:76) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

### Steps to Reproduce

1. Create an index with multiple shards.
2. Create an LTR rescorer 
3. Trigger a search query that involves the LTR rescorer with `explain` set to true

### PR DESCRIPTION
**Pull request by afoucret**
Fix https://github.com/elastic/elasticsearch/issues/120739

This is a PR that try to fix an error when using both LTR and explain with a multiple shard index:

```
Caused by: java.lang.IllegalStateException: local model reference is null, missing rewriteAndFetch before rescore phase?
	at org.elasticsearch.xpack.ml.inference.ltr.LearningToRankRescorer.explain(LearningToRankRescorer.java:150) ~[main/:?]
	at org.elasticsearch.search.fetch.subphase.ExplainPhase$1.process(ExplainPhase.java:47) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:182) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:89) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:194) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:84) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$12(SearchService.java:970) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:79) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:76) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:9.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

Todo list:

- [X] Create an integration test that surface the problem (`LearningToRankExplainIT`)
  - Successful tests:
    - ✅ `testLtrExplainWithSingleShard`
    - ✅ `testLtrExplainWithReplicas`
   - Failed tests (those to be fixed):
     - ❗`testLtrExplainWithMultipleShards`
     - ❗`testLtrExplainWithReplicas`
- [x] Fix the bug

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 1]
```diff
@@ -957,32 +957,34 @@ public void executeFetchPhase(ShardFetchRequest request, SearchShardTask task, A
...
-                }
-                searchContext.assignRescoreDocIds(readerContext.getRescoreDocIds(request.getRescoreDocIds()));
-                searchContext.searcher().setAggregatedDfs(readerContext.getAggregatedDfs(request.getAggregatedDfs()));
-                try (
-                    SearchOperationListenerExecutor executor = new SearchOperationListenerExecutor(searchContext, true, System.nanoTime())
-                ) {
-                    fetchPhase.execute(searchContext, request.docIds(), request.getRankDocks());
-                    if (readerContext.singleSession()) {
-                        freeReaderContext(request.contextId());
+        rewriteAndFetchShardRequest(readerContext.indexShard(), shardSearchRequest, listener.delegateFailure((l, rewritten) -> {
```
Comment (afoucret) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:960]: @benwtrent The most straightforward patch is to add a rewrite step to the execution of the fetch phase but it feels like a huge change that will impact all the request.

WDYT? (cc @jimczi)

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:960]: Adding rewrite to all fetch's seems really expensive. Though, traditionally, queries should all be rewritten already to semi-primitive forms, so maybe it isn't so bad? 

LTR is unique in that its rewrite is used to fetch a local reference to a model as serializing the model over the wire (which can be megabytes in size) is very expensive.

I wonder if ltr rescore can add additional metadata to the long lived context if explain is used?

Comment (afoucret) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: While I like the idea of enriching the long lived context so we can reuse the inference result from the query phase in the fetch phase, it seems very complicated to achieve it (maybe that is just me).

I tried another approach that consist of executing the rewrite conditionally, so most queries won't be affected by it:

```
    private void rewriteAndFetchShardRequestBeforeFetchPhase(
        IndexShard shard,
        ShardSearchRequest request,
        ActionListener<ShardSearchRequest> listener
    ) {
        if (request.source().explain() == false || request.source().rescores().stream().allMatch(r -> r instanceof QueryRescorerBuilder)) {
            // Rewriting the shard request is useless unless explain is enabled and a learning to rank rescorer is used.
            listener.onResponse(request);
            return;
        }

        rewriteAndFetchShardRequest(shard, request, listener);
    }
```

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: > Adding rewrite to all fetch's seems really expensive. Though, traditionally, queries should all be rewritten already to semi-primitive forms, so maybe it isn't so bad?

I think it's fine, the query is already rewritten at this point so that shouldn't add any overhead. Also, if rewrite and fetch is applicable to the fetch phase then we should call it unconditionally. So +1 to just add a call to `rewriteAndFetchShardRequest` on the fetch phase, it will be a noop most of the time anyway.

Comment (afoucret) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: OK folks, `rewriteAndFetchShardRequest` is now always called during the fetch phase as @jim suggested that the overhead should be very small.

**Comment by afoucret** [comment]
I was orignally planning to backport to 8.18 branch only but I think we have an opportunity to deliver the patch as part of 8.17.2 that will come earlier for customer?

Do you think it makes sense to backport this patch to 8.17 as well?

**Review by benwtrent — APPROVED** [review]
I suspect there will be more overhead than we expect, even for LTR.  But let's see what the nightly benchmarks say.

If we do find decrease in performance, we can easily just restrict it for when `explain: true` for everything. But let's keep it simple at first.

**Review by kderusso — APPROVED** [review]
LGTM!
