### PR TITLE
ESQL: Fix case insensitive comparisons to ""

### LINKED ISSUE #127431: [CI] PushQueriesIT testPushCaseInsensitiveEqualityOnDefaults failing
**Build Scans:**
- [elasticsearch-periodic #7862 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/loklcwg3253tq)
- [elasticsearch-pull-request #69128 / part-3](https://gradle-enterprise.elastic.co/s/z23qjuo76ti4s)
- [elasticsearch-periodic-platform-support #7823 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/jy2pcjyw5eur6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.PushQueriesIT.testPushCaseInsensitiveEqualityOnDefaults" -Dtests.seed=3458C8C42AC19307 -Dtests.locale=ar-QA -Dtests.timezone=Etc/Greenwich -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.PushQueriesIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testPushCaseInsensitiveEqualityOnDefaults),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a map containing
documents_found: <1>
  values_loaded: <1>
           took: <48>
     is_partial: <false>
        profile: a map containing
          drivers: <[{cluster_name=test-cluster, sleeps={last=[], counts={}, first=[]}, cpu_nanos=1283719, operators=[{operator=LuceneSourceOperator[shards = [test:0], maxPageSize = 4854, remainingDocs = 2147483646], status={processed_slices=1, processed_shards=[test:0], total_slices=1, slice_max=0, current=2147483647, slice_min=0, rows_emitted=1, pages_emitted=1, process_nanos=146713, partitioning_strategies={test:0=SHARD}, processed_queries=[*:*], slice_index=0}}, {operator=ValuesSourceReaderOperator[fields = [test]], status={pages_processed=1, rows_emitted=1, process_nanos=761488, rows_received=1, readers_built={test:column_at_a_time:null=1, stored_fields[requires_source:true, fields:0, sequential: false]=1, test:row_stride:BlockSourceReader.Bytes=1}, values_loaded=1}}, {operator=FilterOperator[evaluator=Insens
[truncated]
```

**Issue Reasons:**
- [main] 3 failures in test testPushCaseInsensitiveEqualityOnDefaults (0.5% fail rate in 610 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nik9000**
This fixes the compute engine side of case insensitive ==. You can trigger it by writing:
```
FROM foo
| WHERE TO_LOWER(field) == ""
```

But *only* when we can't push the comparison to lucene - like if `field` is not indexed or is a `text` field.

Closes #127431

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/InsensitiveEquals.java [hunk 1]
```diff
@@ -83,6 +85,10 @@ protected TypeResolution resolveType() {
     }
 
     public static Automaton automaton(BytesRef val) {
+        if (val.length == 0) {
+            // toCaseInsensitiveString doesn't match empty strings properly so let's do it ourselves
+            return Automata.makeEmptyString();
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/InsensitiveEquals.java:90]: _search works around this as well with:
```
        // check if valueForSearch is the same as an empty string
        // if we have a length of zero, just do a regular term query
        if (valueForSearch.length == 0) {
            return termQuery(value, context);
        }
```
Which makes sense. And it's slightly faster. Here, instead of doing a term query I just make an automata for the empty string. We are *already* pushing a proper term query using the _search infrastructure when possible.

**Review by idegtiarenko — APPROVED** [review]

**Review by luigidellaquila — APPROVED** [review]
Good catch! LGTM
