### PR TITLE
Fix oom in LinearizabilityChecker

### LINKED ISSUE #98432: OOME in tests due to LinearizabilityChecker overload
The following invocation seems to stabilise very well, generating overwhelmingly many events for the linearizability checker to check, leading to an OOME:

`./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.AtomicRegisterCoordinatorTests.testAppliesNoMasterBlockAllIfConfigured" -Dtests.seed=9BFB03AB5780EC10`

Seen on a recent commit to `main`, 1fef466f50d9936b6cfe8295e943f1a6c3f6f2f2.

### PR DESCRIPTION
**Pull request by idegtiarenko**
LinearizabilityChecker is known to throw OOM when processing long history or partition. This change moves runtime limit for big histories or partitions inside the checker and exposes failure to complete the check via checked exceptions.

Closes: #98432

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java [hunk 1]
```diff
@@ -207,15 +213,10 @@ public String toString() {
...
-     * @param spec the sequential specification of the datatype
-     * @param history the history of events to check for linearizability
-     * @param missingResponseGenerator used to complete the history with missing responses
-     * @return true iff the history is linearizable w.r.t. the given spec
+     * Convenience method for {@link #isLinearizable(SequentialSpec, History, Function)} that requires the history to be complete
      */
-    public static boolean isLinearizable(SequentialSpec spec, History history, Function<Object, Object> missingResponseGenerator) {
-        return isLinearizable(spec, history, missingResponseGenerator, () -> false);
+    public static boolean isLinearizable(SequentialSpec spec, History history) throws LinearizableCheckAborted {
+        return isLinearizable(spec, history, o -> { throw new IllegalArgumentException("history is not complete"); });
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:219]: Should this be an assertion error rather than an IAE?

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java [hunk 2]
```diff
@@ -224,21 +225,41 @@ public static boolean isLinearizable(SequentialSpec spec, History history, Funct
...
+            if (history.size() > 300 || partitions.stream().anyMatch(p -> p.size() > 25)) {
+                logger.warn("Detected large history or partition for linearizable check. Limiting execution time");
+                scheduler.schedule(() -> abort.set(true), 10, TimeUnit.SECONDS);
+            }
+            var allLinearizable = partitions.stream().allMatch(h -> isLinearizable(spec, h, abort::get));
+            if (abort.get()) {
+                throw new LinearizableCheckAborted();
+            }
+            return allLinearizable;
+        } catch (OutOfMemoryError e) {
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:249]: Unfortunately an OOME might mean that some data structures are in an undefined state so I don't think it's ok to catch it and try to continue with the rest of the tests. Possibly one could argue that it's ok if the only data structures we could be mutating are discarded at this point, but I'm not sure that's true and even if it is true today it seems like it would be a fairly fragile argument given all the other things that might happen concurrently in these tests.

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java (hunk 1 above)
Comment (idegtiarenko) [reply test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:219]: Moved as is, but I agree, this should be changed to AssertionError

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java [hunk 3]
```diff
@@ -224,21 +225,41 @@ public static boolean isLinearizable(SequentialSpec spec, History history, Funct
...
+            history.complete(missingResponseGenerator); // complete history
+            final Collection<List<Event>> partitions = spec.partition(history.copyEvents());
+            // Large histories can be problematic and have the linearizability checker run OOM
+            // Bound the time how long the checker can run on such histories (Values empirically determined)
+            if (history.size() > 300 || partitions.stream().anyMatch(p -> p.size() > 25)) {
+                logger.warn("Detected large history or partition for linearizable check. Limiting execution time");
+                scheduler.schedule(() -> abort.set(true), 10, TimeUnit.SECONDS);
+            }
+            var allLinearizable = partitions.stream().allMatch(h -> isLinearizable(spec, h, abort::get));
+            if (abort.get()) {
```
Comment (fcofdez) [inline test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:245]: Maybe we should do just what we did in https://github.com/elastic/elasticsearch/pull/101357/files#diff-c1fe1b667c241e62ccc27b117ca2daf92b358596f8756e2e9c7a8eec2a8ba4e9L446-L448 and return true in that case? that will avoid having to introduce the new exception and catching it in the calling site.

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java (hunk 2 above)
Comment (idegtiarenko) [reply test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:249]: Will remove

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java (hunk 3 above)
Comment (idegtiarenko) [reply test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:245]: I think there is a value on distinguishing between `is linearizable` and `could not perform the check`. I am imagining some change could break something and will silently result in `could not perform the check` for all runs. Exception might not be the most elegant solution, we might use enum instead.

Comment (fcofdez) [reply test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:245]: Makes sense and since this is a checked exception, callers should handle it anyway 👍

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java [hunk 4]
```diff
@@ -224,21 +225,37 @@ public static boolean isLinearizable(SequentialSpec spec, History history, Funct
...
+            return allLinearizable;
+        } finally {
+            ThreadPool.terminate(scheduler, 1, TimeUnit.SECONDS);
+        }
     }
 
+    /**
+     * This exception is thrown if the check could not be completed due to timeout or OOM (that could be caused by long event history)
+     */
+    public static final class LinearizableCheckAborted extends Exception {}
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java:257]: Naming nit/suggestion

```suggestion
    public static final class LinearizabilityCheckAborted extends Exception {}
```

**Review by DaveCTurner — APPROVED** [review]
LGTM (one naming nit)

File: test/framework/src/main/java/org/elasticsearch/cluster/coordination/AbstractCoordinatorTestCase.java [hunk 5]
```diff
@@ -747,20 +744,11 @@ private void stabilise(long stabilisationDurationMillis, boolean expectIdleJoinV
...
-                }
-                final boolean linearizable = LinearizabilityChecker.isLinearizable(spec, history, i -> null, abort::get);
-                if (abort.get() == false) {
-                    assertTrue("history not linearizable: " + history, linearizable);
-                }
-            } finally {
-                ThreadPool.terminate(scheduler, 1, TimeUnit.SECONDS);
+                final boolean linearizable = LinearizabilityChecker.isLinearizable(spec, history, i -> null);
+                assertTrue("history is not linearizable: " + history, linearizable);
+            } catch (LinearizableCheckAborted e) {
```
Comment (fcofdez) [inline test/framework/src/main/java/org/elasticsearch/cluster/coordination/AbstractCoordinatorTestCase.java:750]: Maybe we should log a warning here?

**Review by fcofdez — APPROVED** [review]
LGTM
