### PR TITLE
Fix discovery-file plugin to use custom config path

### LINKED ISSUE #26660: discovery-file plugin does not use provided config directory
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0-rc1

**Plugins installed**: [discovery-file, found-elasticsearch, repository-s3, x-pack]

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Alpine

**Description of the problem including expected versus actual behavior**: discovery-file plugin does not use the provided config directory using ES_PATH_CONF to find unicast_hosts.txt but falls back on the installation directory.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. specify an alternate configuration directory using ES_PATH_CONF
 2. install discovery-file
 3. 

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by jasontedor**
The discovery-file plugin was not config path aware, so it always picked up the default config path (from Elasticsearch home) rather than a custom config path. This commit fixes the discovery-file plugin to respect a custom config path.

Closes #26660

### CODE REVIEW

**Comment by jasontedor** [comment]
This bug only exists in 6.0+ and was introduced when we removed `path.conf` as a command-line flag.

**Review by rjernst — APPROVED** [review]
LGTM

File: plugins/discovery-file/src/test/java/org/elasticsearch/discovery/file/FileBasedUnicastHostsProviderTests.java [hunk 1]
```diff
@@ -152,13 +153,20 @@ public void testSomeInvalidHostEntries() throws Exception {
         final Settings settings = Settings.builder()
                                       .put(Environment.PATH_HOME_SETTING.getKey(), homeDir)
                                       .build();
-        final Path configDir = homeDir.resolve("config").resolve("discovery-file");
-        Files.createDirectories(configDir);
-        final Path unicastHostsPath = configDir.resolve(UNICAST_HOSTS_FILE);
+        final Path configPath;
+        if (randomBoolean()) {
```
Comment (rjernst) [inline plugins/discovery-file/src/test/java/org/elasticsearch/discovery/file/FileBasedUnicastHostsProviderTests.java]: Can this flag be passed in, have a wrapper that continues to take a single arg for most tests, and have an explicit test to know we get the correct config dir?

**Comment by franekrichardson** [comment]
@jasontedor I've tested this in my local cloud environment and it works perfectly :+1:

**Review by s1monw — APPROVED** [review]
LGTM 2
