### PR TITLE
[ES|QL] Fix a bug in parsing index pattern and subquery in convertSubqueryToRemoteIndices used by MultiClusterSpecIT

### LINKED ISSUE #146178: [CI] MultiClusterSpecIT test {csv-spec:subquery.subqueryInFromWithNoFieldCountEmptyInSubquery} failing
**Build Scans:**
- [elasticsearch-intake #37446 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/erpmboxamunay)
- [elasticsearch-pull-request #136695 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/fbipxlucbb7nw)
- [elasticsearch-pull-request #136691 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/qjmsv4yxh7qdg)
- [elasticsearch-pull-request #136688 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/3oekbekaqxks2)
- [elasticsearch-pull-request #136690 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/j66b2ofis4v6c)
- [elasticsearch-pull-request #136697 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/4wwcgsrncapr2)
- [elasticsearch-pull-request #136687 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/sjwgcnjdkofcc)
- [elasticsearch-pull-request #136695 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/zsuyjd2mxmsm2)
- [elasticsearch-pull-request #136691 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/o6pbxp5tysgia)
- [elasticsearch-pull-request #136678 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/s64yhc5ittq6e)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v9.4.0#newToOld" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {csv-spec:subquery.subqueryInFromWithNoFieldCountStarInSubquery}" -Dtests.seed=33B2A6B62BB004F9 -Dtests.bwc=true -Dtests.locale=ast -Dtests.timezone=Europe/Monaco -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Asubquery.subqueryInFromWithNoFieldCountEmptyInSubquery%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:38513], URI [/_query/async/FnVORVEtOXZ1U19xR0F1RWlDQThJdGccZTd6RUJIZ3ZUTHk1VTRPRTMzTVJBUToyNTE5Nw==?wait_for_completion_timeout=6000s&pretty=true&error_trace=true], status line [HTTP/1.1 400 Bad Request]
¿eerror¿jroot_cause¿dtypeqparsing_exceptionfreasonxkline -1:-1: parsing_exception: line 2:1: mismatched input '(' expecting {<EOF>, '|', '::', ',', 'metadata'}kstack_traceyAorg.elasticsearch.xpack.esql.parser.ParsingException: line -1:-1: parsing_exception: line 2:1: mismatched input '(' expecting {<EOF>, '|', '::', ',', 'metadata'}
	at org.elasticsearch.xpack.esql.parser.EsqlParser$1.syntaxError(EsqlParser.java:265)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy
[truncated]
```

**Issue Reasons:**
- [main] 378 consecutive failures in test test {csv-spec:subquery.subqueryInFromWithNoFieldCountEmptyInSubquery}
- [main] 29 consecutive failures in step 9.4.0_bwc-snapshots
- [main] 337 consecutive failures in step 9.4.0_part_3_bwc-snapshots
- [main] 3 consecutive failures in step 9.4.0_matrix-bwc
- [main] 3 consecutive failures in step 9.4.0_bwc
- [main] 29 consecutive failures in pipeline elasticsearch-intake
- [main] 174 consecutive failures in pipeline elasticsearch-pull-request
- [main] 3 consecutive failures in pipeline elasticsearch-periodic-java-ea
- [main] 378 failures in test test {csv-spec:subquery.subqueryInFromWithNoFieldCountEmptyInSubquery} (100.0% fail rate in 378 executions)
- [main] 29 failures in step 9.4.0_bwc-snapshots (100.0% fail rate in 29 executions)
- [main] 337 failures in step 9.4.0_part_3_bwc-snapshots (100.0% fail rate in 337 executions)
- [main] 3 failures in step 9.4.0_matrix-bwc (100.0% fail rate in 3 executions)
- [main] 3 failures in step 9.4.0_bwc (100.0% fail rate in 3 executions)
- [main] 29 failures in pipeline elasticsearch-intake (100.0% fail rate in 29 executions)
- [main] 174 failures in pipeline elasticsearch-pull-request (100.0% fail rate in 174 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #146179: [CI] MultiClusterSpecIT test {csv-spec:subquery.subqueryInFromWithNoFieldCountOneInSubquery} failing
**Build Scans:**
- [elasticsearch-intake #37449 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ukmk4gy66w5qm)
- [elasticsearch-pull-request #136704 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/a3fbz7kbu3cuw)
- [elasticsearch-pull-request #136705 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/6kfjn2dxrb5z4)
- [elasticsearch-pull-request #136699 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/i7it6bbglul7u)
- [elasticsearch-pull-request #136698 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/7rrxcvnq2qdnw)
- [elasticsearch-intake #37447 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/wynlnbxnsape4)
- [elasticsearch-pull-request #136699 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/j6hh3kg5r5fu2)
- [elasticsearch-pull-request #136697 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/egd6zlmfccvfg)
- [elasticsearch-pull-request #136698 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/l2ljwxygdb5ui)
- [elasticsearch-intake #37446 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/erpmboxamunay)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v9.4.0#newToOld" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {csv-spec:subquery.subqueryInFromWithNoFieldCountStarInSubquery}" -Dtests.seed=5237C30362994388 -Dtests.bwc=true -Dtests.locale=mt-MT -Dtests.timezone=Brazil/East -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Asubquery.subqueryInFromWithNoFieldCountOneInSubquery%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:45073], URI [/_query/async/FnM2bGJQalhJUnVxQTZkTV9MeTQ2Z0Ecc05qVnF4c1JTRHVlS3RrbWgxY24tZzo2NDU0MQ==?wait_for_completion_timeout=6000s&pretty=true&error_trace=true], status line [HTTP/1.1 400 Bad Request]
---
error:
  root_cause:
  - type: "parsing_exception"
    reason: "line -1:-1: parsing_exception: line 2:1: mismatched input '(' expecting\
      \ {<EOF>, '|', '::', ',', 'metadata'}"
    stack_trace: "org.elasticsearch.xpack.esql.parser.ParsingException: line -1:-1:\
      \ parsing_exception: line 2:1: mismatched input '(' expecting {<EOF>, '|', '::',\
      \ ',', 'metadata'}\n\tat org.elasticsearch.xpack.esql.parser.EsqlParser$1.syntaxError(EsqlParser.java:265)\n\
      \tat org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)\n\
      \tat org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)\n\tat\
      \ org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMisma
[truncated]
```

**Issue Reasons:**
- [main] 388 consecutive failures in test test {csv-spec:subquery.subqueryInFromWithNoFieldCountOneInSubquery}
- [main] 31 consecutive failures in step 9.4.0_bwc-snapshots
- [main] 344 consecutive failures in step 9.4.0_part_3_bwc-snapshots
- [main] 3 consecutive failures in step 9.4.0_matrix-bwc
- [main] 3 consecutive failures in step 9.4.0_bwc
- [main] 1 consecutive failures in step 9.2.8_part_3_bwc-snapshots
- [main] 31 consecutive failures in pipeline elasticsearch-intake
- [main] 178 consecutive failures in pipeline elasticsearch-pull-request
- [main] 3 consecutive failures in pipeline elasticsearch-periodic-java-ea
- [main] 388 failures in test test {csv-spec:subquery.subqueryInFromWithNoFieldCountOneInSubquery} (100.0% fail rate in 388 executions)
- [main] 31 failures in step 9.4.0_bwc-snapshots (100.0% fail rate in 31 executions)
- [main] 344 failures in step 9.4.0_part_3_bwc-snapshots (100.0% fail rate in 344 executions)
- [main] 3 failures in step 9.4.0_matrix-bwc (100.0% fail rate in 3 executions)
- [main] 3 failures in step 9.4.0_bwc (100.0% fail rate in 3 executions)
- [main] 31 failures in pipeline elasticsearch-intake (100.0% fail rate in 31 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #146180: [CI] MultiClusterSpecIT test {csv-spec:subquery.subqueryInFromWithNoFieldCountStarInSubquery} failing
**Build Scans:**
- [elasticsearch-intake #37449 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ukmk4gy66w5qm)
- [elasticsearch-intake #37450 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/a3lxuebjydsoa)
- [elasticsearch-pull-request #136704 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/a3fbz7kbu3cuw)
- [elasticsearch-pull-request #136705 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/6kfjn2dxrb5z4)
- [elasticsearch-pull-request #136699 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/i7it6bbglul7u)
- [elasticsearch-pull-request #136698 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/7rrxcvnq2qdnw)
- [elasticsearch-intake #37447 / 9.4.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/wynlnbxnsape4)
- [elasticsearch-pull-request #136699 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/j6hh3kg5r5fu2)
- [elasticsearch-pull-request #136697 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/egd6zlmfccvfg)
- [elasticsearch-pull-request #136698 / 9.4.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/l2ljwxygdb5ui)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v9.4.0#newToOld" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {csv-spec:subquery.subqueryInFromWithNoFieldCountStarInSubquery}" -Dtests.seed=5237C30362994388 -Dtests.bwc=true -Dtests.locale=mt-MT -Dtests.timezone=Brazil/East -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Asubquery.subqueryInFromWithNoFieldCountStarInSubquery%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:45073], URI [/_query/async/FnM2bGJQalhJUnVxQTZkTV9MeTQ2Z0Ecc05qVnF4c1JTRHVlS3RrbWgxY24tZzo2NDU0MQ==?wait_for_completion_timeout=6000s&pretty=true&error_trace=true], status line [HTTP/1.1 400 Bad Request]
---
error:
  root_cause:
  - type: "parsing_exception"
    reason: "line -1:-1: parsing_exception: line 2:1: mismatched input '(' expecting\
      \ {<EOF>, '|', '::', ',', 'metadata'}"
    stack_trace: "org.elasticsearch.xpack.esql.parser.ParsingException: line -1:-1:\
      \ parsing_exception: line 2:1: mismatched input '(' expecting {<EOF>, '|', '::',\
      \ ',', 'metadata'}\n\tat org.elasticsearch.xpack.esql.parser.EsqlParser$1.syntaxError(EsqlParser.java:265)\n\
      \tat org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)\n\
      \tat org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)\n\tat\
      \ org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMisma
[truncated]
```

**Issue Reasons:**
- [main] 387 consecutive failures in test test {csv-spec:subquery.subqueryInFromWithNoFieldCountStarInSubquery}
- [main] 32 consecutive failures in step 9.4.0_bwc-snapshots
- [main] 343 consecutive failures in step 9.4.0_part_3_bwc-snapshots
- [main] 3 consecutive failures in step 9.4.0_matrix-bwc
- [main] 3 consecutive failures in step 9.4.0_bwc
- [main] 32 consecutive failures in pipeline elasticsearch-intake
- [main] 177 consecutive failures in pipeline elasticsearch-pull-request
- [main] 3 consecutive failures in pipeline elasticsearch-periodic-java-ea
- [main] 387 failures in test test {csv-spec:subquery.subqueryInFromWithNoFieldCountStarInSubquery} (100.0% fail rate in 387 executions)
- [main] 32 failures in step 9.4.0_bwc-snapshots (100.0% fail rate in 32 executions)
- [main] 343 failures in step 9.4.0_part_3_bwc-snapshots (100.0% fail rate in 343 executions)
- [main] 3 failures in step 9.4.0_matrix-bwc (100.0% fail rate in 3 executions)
- [main] 3 failures in step 9.4.0_bwc (100.0% fail rate in 3 executions)
- [main] 32 failures in pipeline elasticsearch-intake (100.0% fail rate in 32 executions)
- [main] 177 failures in pipeline elasticsearch-pull-request (100.0% fail rate in 177 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Fixes: #146178
Fixes: #146179 
Fixes: #146180

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java [hunk 1]
```diff
@@ -1671,8 +1671,10 @@ public static String convertSubqueryToRemoteIndices(String testQuery) {
         for (String indexPatternOrSubquery : indexPatternsAndSubqueries) {
             // remove the from keyword if it's there
             indexPatternOrSubquery = indexPatternOrSubquery.strip();
-            if (indexPatternOrSubquery.toLowerCase(Locale.ROOT).startsWith("from ")) {
-                indexPatternOrSubquery = indexPatternOrSubquery.strip().substring(5);
+            if (indexPatternOrSubquery.length() > 4
```
Comment (craigtaverner) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:1674]: This looks like it might be easier as a regexp.

**Review by craigtaverner — APPROVED** [review]

**Comment by fang-xing-esql** [comment]
Thanks for the review @idegtiarenko @craigtaverner !

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:1674]: Good idea! If we come across another bug here, I'll try regex.

**Comment by fang-xing-esql** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/146249)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
