### PR TITLE
SQL: Fix nested ORDER BY

### LINKED ISSUE #76013: SQL: Nested ORDER BY are evaluated in wrong order
The query `SELECT * FROM (SELECT * FROM test_emp ORDER BY gender) s ORDER BY languages` orders the documents by `gender` and uses `languages` as a tie breaker:

```
       birth_date       |    emp_no     |  first_name   |    gender     |       hire_date        |   languages   |   last_name   |         name         |    salary
------------------------+---------------+---------------+---------------+------------------------+---------------+---------------+----------------------+---------------
1952-04-19T00:00:00.000Z|10009          |Sumant         |F              |1985-02-18T00:00:00.000Z|1              |Peac           |Sumant Peac           |66174
null                    |10041          |Uri            |F              |1989-11-12T00:00:00.000Z|1              |Lenart         |Uri Lenart            |56415
null                    |10044          |Mingsen        |F              |1994-05-21T00:00:00.000Z|1              |Casley         |Mingsen Casley        |39728
1964-10-18T00:00:00.000Z|10092          |Valdiodio      |F              |1989-09-22T00:00:00.000Z|1              |Niizuma        |Valdiodio Niizuma     |25976
1961-09-01T00:00:00.000Z|10056          |Brendon        |F              |1990-02-01T00:00:00.000Z|2              |Bernini        |Brendon Bernini       |33370
1953-09-19T00:00:00.000Z|10059          |Alejandro      |F              |1991-06-26T00:00:00.000Z|2              |McAlpine       |Alejandro McAlpine    |44307
```
`/translate` result of the same query:
```
{
  ...
  "sort": [
    {
      "gender": {
        "order": "asc",
        "missing": "_last",
        "unmapped_type": "keyword"
      }
    },
    {
      "languages": {
        "order": "asc",
        "missing": "_last",
        "unmapped_type": "byte"
      }
    }
  ]
}
```

The expected behavior would be to first order the documents by `gender` and then order the whole result by `languages` which is the same as ordering by `languages` with `gender` as the tie breaker.

E.g. in H2:
```
sql> SELECT * FROM (SELECT * FROM test_emp ORDER BY gender) s ORDER BY languages;
birth_date             | emp_no | first_name  | gender | hire_date              | languages | last_name    | name                   | salary
1953-09-29 00:00:00+00 | 10023  | Bojan       | F      | 1989-12-17 00:00:00+00 | null      | Montemayor   | Bojan Montemayor       | 47896
1958-09-05 00:00:00+00 | 10024  | Suzette     | F      | 1997-05-19 00:00:00+00 | null      | Pettey       | Suzette Pettey         | 64675
1962-07-10 00:00:00+00 | 10027  | Divier      | F      | 1989-07-07 00:00:00+00 | null      | Reistad      | Divier Reistad         | 73851
1952-12-24 00:00:00+00 | 10020  | Mayuko      | M      | 1991-01-26 00:00:00+00 | null      | Warwick      | Mayuko Warwick         | 40031
1960-02-20 00:00:00+00 | 10021  | Ramzi       | M      | 1988-02-10 00:00:00+00 | null      | Erde         | Ramzi Erde             | 60408
```

### PR DESCRIPTION
**Pull request by Luegg**
Resolves #76013. Follow up of https://github.com/elastic/elasticsearch/pull/75960

As discussed in #75960, the merging of sort orders from multiple `OrderBy` is now implemented in the query folder.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java [hunk 1]
```diff
@@ -701,7 +701,12 @@ protected PhysicalPlan rule(OrderExec plan) {
                 EsQueryExec exec = (EsQueryExec) plan.child();
                 QueryContainer qContainer = exec.queryContainer();
 
-                for (Order order : plan.order()) {
+                // Reverse traversal together with the upwards fold direction ensures that sort clauses are added in reverse order of
+                // precedence. E.g. for the plan `OrderBy[a desc,b](OrderBy[a asc,c](EsExec[...]))`, `prependSort` is called with the
+                // following sequence of arguments: `c`, `a asc`, `b`, `a desc`. The resulting sort order is `a desc,b,c`.
+                for (int i = plan.order().size() - 1; i >= 0; i--) {
+                    Order order = plan.order().get(i);
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java:708]: Imo, it's cleaner to use the `listIterator` instead of the index
```
for (ListIterator<Order> i = plan.order().listIterator(); i.hasPrevious(); ) {
   Order order = i.previous();
```

**Review by costin — APPROVED** [review]
LGTM. 
Please add a comment to `prependSort` on why the order is in reverse (due to the iteration of the tree) and it might not be obvious the connection to the other rules.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java]: 👍 I was looking for something to avoid the index lookup but was not aware of `ListIterator`.

**Comment by Luegg** [comment]
`@elasticmachine run elasticsearch-ci/part-1`
