### PR TITLE
Fix testRetriesOnCorrectSchedule

### LINKED ISSUE #98772: [CI] ElectionSchedulerFactoryTests testRetriesOnCorrectSchedule failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/lxlsgu3jfzm46/tests/:server:test/org.elasticsearch.cluster.coordination.ElectionSchedulerFactoryTests/testRetriesOnCorrectSchedule

**Reproduction line:**
```
gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.ElectionSchedulerFactoryTests.testRetriesOnCorrectSchedule" -Dtests.seed=9E122BD7EF10E7BD -Dtests.locale=it-IT -Dtests.timezone=Arctic/Longyearbyen -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.coordination.ElectionSchedulerFactoryTests&tests.test=testRetriesOnCorrectSchedule

**Failure excerpt:**
```
java.lang.AssertionError: expected to see 1000 retries message but did not
Expected: <true>
     but: was <false>

  at __randomizedtesting.SeedInfo.seed([9E122BD7EF10E7BD:25AEEF51ADC12C72]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.elasticsearch.test.MockLogAppender$SeenEventExpectation.assertMatched(MockLogAppender.java:127)
  at org.elasticsearch.test.MockLogAppender$WrappedLoggingExpectation.assertMatched(MockLogAppender.java:231)
  at org.elasticsearch.test.MockLogAppender.assertAllExpectationsMatched(MockLogAppender.java:61)
  at org.elasticsearch.cluster.coordination.ElectionSchedulerFactoryTests.assertElectionSchedule(ElectionSchedulerFactoryTests.java:127)
  at org.elasticsearch.cluster.coordination.ElectionSchedulerFactoryTests.testRetriesOnCorrectSchedule(ElectionSchedulerFactoryTests.java:179)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Sometimes this test stops after exactly 1000 election attempts, in which
case we never report the 1000th failure. Fixed by asserting that we do
see a report about the 990th instead.

Closes #98772

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java [hunk 1]
```diff
@@ -68,7 +68,8 @@ private void assertElectionSchedule(
                     "retrying master election after [0] failed attempts"
                 )
             );
-            for (int i : new int[] { 10, 20, 1000 }) {
+            for (int i : new int[] { 10, 20, 990 }) {
+                // the test may stop after 1000 attempts, so might not report the 1000th failure; it definitely reports the 990th tho.
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java:72]: Is the 1000 attempts some other variable/configuration?

**Review by kingherc — APPROVED** [review]
LGTM. Although 1 minor question to understand why it can stop after 1000 attempts.

File: server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java (hunk 1 above)
Comment (kingherc) [reply server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java:72]: I see thanks! In that case shouldn't we verify 999 instead of 990?

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java:72]: No, because we only report every 10th attempt:

https://github.com/elastic/elasticsearch/blob/95a215e5e0d5127ae102f247c55718f7f20cc6ee/server/src/main/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactory.java#L194

**Review by idegtiarenko — APPROVED** [review]

**Review by fcofdez — APPROVED** [review]
LGTM

File: server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java (hunk 1 above)
Comment (kingherc) [reply server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java:72]: Sounds good!
