### PR TITLE
Stabilize testRerouteRecovery throttle testing

### LINKED ISSUE #99941: [CI] IndexRecoveryIT testRerouteRecovery failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/d3cfn2jnvzye4/tests/:server:internalClusterTest/org.elasticsearch.indices.recovery.IndexRecoveryIT/testRerouteRecovery

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery" -Dtests.seed=D90D29B7DAB2BC89 -Dtests.locale=fr-LU -Dtests.timezone=Australia/Lord_Howe -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try
UPDATE:
Does not reproduces locally on my Mac, but does on a remote cloud host running
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery" -Dtests.iters=100 -Dtests.failfast=true
```

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.indices.recovery.IndexRecoveryIT&tests.test=testRerouteRecovery

**Failure excerpt:**
```
java.lang.AssertionError: node A throttling should increase
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>

  at __randomizedtesting.SeedInfo.seed([D90D29B7DAB2BC89:74A69AE3EFEADECB]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.indices.recovery.IndexRecoveryIT.lambda$testRerouteRecovery$2(IndexRecoveryIT.java:519)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1196)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1169)
  at org.elasticsearch.indices.recovery.IndexRecoveryIT.testRerouteRecovery(IndexRecoveryIT.java:510)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by DiannaHohensee**
Refactor testRerouteRecovery, pulling out testing of shard recovery
throttling into separate targeted tests. Now there are two additional
tests, one testing source node throttling, and another testing target
node throttling. Throttling both nodes at once leads to primarily the
source node registering throttling, while the target node mostly has
no cause to instigate throttling.

Closes #99941

### CODE REVIEW

**Comment by DiannaHohensee** [comment]
Is the `>test-failure` label used for test fixes?

I've run the old and new tests a few times each at 100 iterations. I did a little tidying in the test file, too: let me know if it should be done separately.

I didn't modify the recovery path, though I did shove it into a function helper. I figure it's the same recovery functionality that's being tested.

**Comment by DaveCTurner** [comment]
`>test` is the label to use for changes that fix (or add) tests.

The cleanups/renamings/comment additions look good but a separate PR would make it a little easier to review, and also to eliminate them as a source of problems if we ever have to `git bisect` back to this change. Not a huge deal tho, I can see what's going on.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 1]
```diff
@@ -445,75 +535,109 @@ public Settings onNodeStopped(String nodeName) throws Exception {
...
+        startShardRecovery(INDEX_NAME, nodeA, nodeB);
 
-        logger.info("--> waiting for recovery to start both on source and target");
-        final Index index = resolveIndex(INDEX_NAME);
+        logger.info("--> checking throttling increases on Node A (source node), while Node B (target node) reports no throttling");
         assertBusy(() -> {
-            IndicesService indicesService = internalCluster().getInstance(IndicesService.class, nodeA);
-            assertThat(indicesService.indexServiceSafe(index).getShard(0).recoveryStats().currentAsSource(), equalTo(1));
-            indicesService = internalCluster().getInstance(IndicesService.class, nodeB);
-            assertThat(indicesService.indexServiceSafe(index).getShard(0).recoveryStats().currentAsTarget(), equalTo(1));
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:475]: Removing this wait looks suspicious to me. It's not throttling-related, it's waiting for both nodes to start handling the recovery and that looks important for the next few lines of the test.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 2]
```diff
@@ -445,75 +535,109 @@ public Settings onNodeStopped(String nodeName) throws Exception {
...
-        for (NodeStats nodeStats : statsResponse.getNodes()) {
-            final RecoveryStats recoveryStats = nodeStats.getIndices().getRecoveryStats();
-            if (nodeStats.getNode().getName().equals(nodeA)) {
-                assertThat("node A should have ongoing recovery as source", recoveryStats.currentAsSource(), equalTo(1));
-                assertThat("node A should not have ongoing recovery as target", recoveryStats.currentAsTarget(), equalTo(0));
-                nodeAThrottling = recoveryStats.throttleTime().millis();
-            }
-            if (nodeStats.getNode().getName().equals(nodeB)) {
-                assertThat("node B should not have ongoing recovery as source", recoveryStats.currentAsSource(), equalTo(0));
-                assertThat("node B should have ongoing recovery as target", recoveryStats.currentAsTarget(), equalTo(1));
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:509]: I think we should keep the check that A has 1 source and 0 targets and B has 0 sources and 1 target. We can drop the bit about the throttling here tho, and probably the `assertBusy()`.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 3]
```diff
@@ -552,37 +718,17 @@ public void testRerouteRecovery() throws Exception {
...
-            NodesStatsResponse nodesStatsResponse = clusterAdmin().prepareNodesStats()
-                .setNodesIds(nodeName)
-                .clear()
-                .setIndices(new CommonStatsFlags(CommonStatsFlags.Flag.Recovery))
-                .get();
-            assertThat(nodesStatsResponse.getNodes(), hasSize(1));
-            NodeStats nodeStats = nodesStatsResponse.getNodes().get(0);
-            final RecoveryStats recoveryStats = nodeStats.getIndices().getRecoveryStats();
-            assertThat(recoveryStats.currentAsSource(), equalTo(0));
-            assertThat(recoveryStats.currentAsTarget(), equalTo(0));
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:565]: Likewise with this bit, I think we should still be waiting for the recoveries to reach zero according to both nodes.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 4]
```diff
@@ -235,38 +234,129 @@ private void assertOnGoingRecoveryState(
...
+            assertThat(indicesService.indexServiceSafe(index).getShard(0).recoveryStats().currentAsTarget(), equalTo(1));
+        });
+
+        logger.info("--> checking cluster recovery stats reflect the ongoing recovery on each node");
+        NodesStatsResponse statsResponse = clusterAdmin().prepareNodesStats()
+            .clear()
+            .setIndices(new CommonStatsFlags(CommonStatsFlags.Flag.Recovery))
+            .get();
+        long nodeAThrottling = Long.MAX_VALUE;
+        long nodeBThrottling = Long.MAX_VALUE;
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:306]: These are unused here it seems.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 5]
```diff
@@ -445,75 +535,109 @@ public Settings onNodeStopped(String nodeName) throws Exception {
...
 
-        logger.info("--> start node B");
+        logger.info("--> starting node B with default settings");
         final String nodeB = internalCluster().startNode();
 
+        long chunkSize = Math.max(1, shardSize.getBytes() / 10);
+        logger.info(
+            "--> restarting node A with recovery throttling settings. Index shard size (MB) is `{}`. Throttling down to a "
+                + "chunk of size `{}` (MB) per second. This will slow recovery of the shard to 10 seconds.",
+            shardSize.getMb(),
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:560]: Suggest just `shardSize` here, its `toString()` will yield something readable.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 6]
```diff
@@ -445,75 +535,109 @@ public Settings onNodeStopped(String nodeName) throws Exception {
...
+            chunkSize / 1024.0 / 1024.0 /* converting bytes to megabytes */
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java:561]: Likewise, `ByteSizeValue.ofBytes(chunkSize)` will do something sensible.

**Review by DaveCTurner — COMMENTED** [review]
New tests look good; I left only a few superficial comments. I have a hunch that splitting out the renamings and other tidyups will make this a lot more readable - there's too much similarity between the old and new tests, and too many differences between the old version of the old test and its new version here, for the diff rendering to work nicely.

**Review by DiannaHohensee — COMMENTED** [review]
I've updated per review comments [here](https://github.com/elastic/elasticsearch/pull/100788/commits/c1d282da421b6726d5929bf96169b1a098b59101) and [here](https://github.com/elastic/elasticsearch/pull/100788/commits/67685554a9fe294d3992ba2137c78e3fac72ed28). I also pulled out the name changes for a follow up patch, but I think more importantly I moved the new tests below the old one so that the diff is much clearer.

**Review by DaveCTurner — APPROVED** [review]
LGTM.

Since it's only test changes (and fixes a known test bug) I think it would be good to backport to 8.11, 8.10 and 7.17 too.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 7]
```diff
@@ -249,11 +262,83 @@ private void slowDownRecovery(ByteSizeValue shardSize) {
...
 
+    /**
+     * Initiates a shard recovery and verifies that it's running.
+     *
+     * @param INDEX_NAME name of the index
+     * @param sourceNode node holding the shard
+     * @param targetNode node recovering the shard
+     * @throws Exception
+     */
+    public void startShardRecovery(String INDEX_NAME, String sourceNode, String targetNode) throws Exception {
```
[the remark this answers is not in the document]
Comment (DiannaHohensee) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: Ah yes, too much copy-paste.
