### PR TITLE
Fix race in FsBlobContainer.moveBlobAtomic by replacing move op with hard link

### LINKED ISSUE #147171: [CI] OperatorPrivilegesIT testNonOperatorUserCanCallAnalyzeRepositoryAPI failing
**Build Scans:**
- [elasticsearch-intake #38181 / part4](https://gradle-enterprise.elastic.co/s/op5k7a6a4ywf4)
- [elasticsearch-pull-request #139374 / part-4](https://gradle-enterprise.elastic.co/s/rzdctmn4wctsu)
- [elasticsearch-pull-request #139247 / part-4](https://gradle-enterprise.elastic.co/s/eknqdwtr7kpz4)
- [elasticsearch-periodic-platform-support #12134 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/kbjigti4sn2qs)
- [elasticsearch-pull-request #139150 / part-4](https://gradle-enterprise.elastic.co/s/fya4hoqhvscfc)
- [elasticsearch-pull-request #139145 / part-4](https://gradle-enterprise.elastic.co/s/5ojo5u2zgmd44)
- [elasticsearch-pull-request #139117 / part-4](https://gradle-enterprise.elastic.co/s/jfs5n3v5vmgru)
- [elasticsearch-pull-request #139117 / part-4](https://gradle-enterprise.elastic.co/s/w37x3j226mois)
- [elasticsearch-pull-request #138991 / part-4](https://gradle-enterprise.elastic.co/s/eyadaoexpiu7q)
- [elasticsearch-pull-request #138904 / part-4](https://gradle-enterprise.elastic.co/s/fmnzqwnehiq2i)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:qa:operator-privileges-tests:javaRestTest" --tests "org.elasticsearch.xpack.security.operator.OperatorPrivilegesIT.testNonOperatorUserCanCallAnalyzeRepositoryAPI" -Dtests.seed=7604F88DC268C48D -Dtests.locale=hsb -Dtests.timezone=Europe/London -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.operator.OperatorPrivilegesIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testNonOperatorUserCanCallAnalyzeRepositoryAPI'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:33965], URI [/_snapshot/testAnalysisRepo/_analyze], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[testAnalysisRepo] multiple writes succeeded to overwrite-protected blob temp-analysis-4mmA0_dGQbu0hOK1Zb-j6A/test-overwrite-blob-Qkt1E-vDRhiz723tAxQPVA","suppressed":[{"type":"repository_verification_exception","reason":"[testAnalysisRepo] failure processing [blob analysis [testAnalysisRepo:temp-analysis-4mmA0_dGQbu0hOK1Zb-j6A/test-blob-98-wMWgzgtST0a3eA4RDMXH1A, length=32, seed=-1681044207315830571, readEarly=false, writeAndOverwrite=false, abortWrite=false, copyBlobName=null]]"}]}],"type":"repository_verification_exception","reason":"[testAnalysisRepo] Elasticsearch observed the storage system underneath this repository behaved incorrectly which indicates it is not suitable for use with Elasticsearch snapshots. See [https://www.el
[truncated]
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testNonOperatorUserCanCallAnalyzeRepositoryAPI
- [main] 1 consecutive failures in step part4
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 15 failures in test testNonOperatorUserCanCallAnalyzeRepositoryAPI (1.7% fail rate in 884 executions)
- [main] 10 failures in step part-4 (1.8% fail rate in 557 executions)
- [main] 9 failures in pipeline elasticsearch-pull-request (1.6% fail rate in 548 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-java-ea (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by michalborek**
There was a TOCTOU race in `FsBlobContainer.moveBlobAtomic`. 
Instead of checking if file exists and moving the file, the hard link operation was used. This operation is atomic on kernel level and fails if the target already exists. 

Thoughts / assumptions of particular changes: 

1. When the link is successfully created, the source can be deleted.
2. I assumed the error during the deletion of the source file is highly unlikely and should not fail the move operation (which was successful) but I'm not highly opinionated on this. Happy to be challenged about this(alternatives: don't log anything, just don't catch this error, or catch -> log -> rethrow).
3. There's a fallback for FSes with no hard-link support.
4. I've extracted the fallback to a separate method for clarity reasons, but passed it as a method reference so that the fact we use a fallback is not hidden from the person reading the code. This is a highly unlikely situation. I didn't want to just inline it. 

I think this is just easier to read:
```java
if (failIfAlreadyExists) {
  moveAtomicallyUsingHardLink(targetBlobPath, sourceBlobPath, FsBlobContainer::fallbackMoveFileWithNoHardLinkSupported);
} 
```

Closes: #147171.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java [hunk 1]
```diff
@@ -379,6 +379,52 @@ private static void checkAtomicWrite() throws IOException {
...
+            );
+
+            final int threadCount = between(2, 8);
+            final var threads = new Thread[threadCount];
+            final var barrier = new CyclicBarrier(threadCount);
+            final var successCount = new AtomicLong(0);
+
+            for (int i = 0; i < threadCount; i++) {
+                final var data = new BytesArray(randomByteArrayOfLength(randomIntBetween(1, 512)));
+                threads[i] = new Thread(() -> {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java]: Maybe use `org.elasticsearch.test.ESTestCase#startInParallel` instead?

File: server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java [hunk 2]
```diff
@@ -379,6 +379,52 @@ private static void checkAtomicWrite() throws IOException {
...
+                    safeAwait(barrier);
+                    try {
+                        container.writeBlobAtomic(randomNonDataPurpose(), blobName, data, true);
+                        successCount.incrementAndGet();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java]: Maybe `assertTrue(success.compareAndSet(false, true))` on an `AtomicBoolean` instead?

File: server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java [hunk 3]
```diff
@@ -379,6 +379,52 @@ private static void checkAtomicWrite() throws IOException {
...
+                    } catch (FileAlreadyExistsException e) {
+                        // expected for all but one thread
+                    } catch (IOException e) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java]: We should catch `Exception` here, any runtime exception is also a failure right?

File: server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java [hunk 4]
```diff
@@ -379,6 +379,52 @@ private static void checkAtomicWrite() throws IOException {
...
+            for (Thread thread : threads) {
+                thread.join();
+            }
+
+            assertThat("exactly one writer should succeed", successCount.get(), equalTo(1L));
+            for (String blob : container.listBlobs(randomPurpose()).keySet()) {
+                assertFalse("unexpected temp blob [" + blob + "]", FsBlobContainer.isTempBlobName(blob));
+            }
+        } finally {
+            PathUtilsForTesting.installMock(fileSystem);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java]: I think we install the mock again before each test (because of the `@Before` annotation) so no need to restore it here too?

**Review by DaveCTurner — COMMENTED** [review]
Looks good, just a few testing nits. Would you also add the `test-windows` label so that we run CI on Windows before merging?

File: server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java (hunk 4 above)
Comment (michalborek) [reply server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java]: Thanks, this was a leftover, because the test was failing and I was trying whether it's the case...

**Comment by michalborek** [comment]
Recently, the CI started running a test multiple times if it is changed. The `-Dtests.iters` is used for that. An unrelated test case was failing because of that. It blocked my pipeline, so I've made a fix for this as well.

File: server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java (hunk 1 above)
Comment (michalborek) [reply server/src/test/java/org/elasticsearch/common/blobstore/fs/FsBlobContainerTests.java]: Nice, I didn't know that one

**Comment by DaveCTurner** [comment]
>  I've made a fix for this as well.

Would you pull that out to a separate PR that we can merge first?

**Review by DaveCTurner — COMMENTED** [review]
All seems good to me except it's still a draft and hasn't yet been tested on Windows. Don't forget to add the `test-windows` label before merging `main` after #147410 has landed.

**Comment by michalborek** [comment]
Some tests are failing consistently on windows. My first take is this is a different dependency resolution on different OSes (it may depend on how files are listed by underlying OS)

**Comment by DaveCTurner** [comment]
Hmm this seems unrelated, I'd check in #es-delivery what the overall state of Windows tests is. If it's broken in `main` then this stuff needs muting and raising with the relevant team.

**Comment by michalborek** [comment]
I'm preparing a fix for this, but it is unrelated.

**Review by DaveCTurner — APPROVED** [review]
LGTM as long as CI is happy
