### PR TITLE
Fix ArrayIndexOutOfBoundsException in fetch phase with partial results

### LINKED ISSUE #140495: array_index_out_of_bounds_exception when elastic search request is huge in size
### Elasticsearch Version

8.17.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

Getting the following exception when search query is very huge 

{
    "error": {
        "root_cause": [],
        "type": "search_phase_execution_exception",
        "reason": "",
        "phase": "fetch",
        "grouped": true,
        "failed_shards": [],
        "caused_by": {
            "type": "array_index_out_of_bounds_exception",
            "reason": "Index 242 out of bounds for length 242"
        }
    },
    "status": 500
}

### Steps to Reproduce

{
    "query": {
        "bool": {
            "filter": [
                {
                    "bool": {
                        "must": [
                            {
                                "bool": {
                                    "filter": [
                                        {
                                            "bool": {
                                                "must_not": [
                                                    {
                                                        "terms": {
                                                            "xxx: [
                                                                "YYY"
                                                            ]
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                }
                            }
                        ],
                        "must_not": [
                            {
                                "match": {
                                    "xxx": {
                                        "query": "YYY"
                                    }
                                }
                            }
                        ],
                        "should": [
                            {
                                "match": {
                                    "xxx": {
                                        "query": "ZZZ"
                                    }
                                }
                            }
                        ]
                    }
                }
            ],
            "must": [
                {
                    "bool": {
                        "must": [
                            {
                                "query_string": {
                                    "fields": [
                                        "AAA^1.2999999523162842",
                                .... <around 90 fields>
                                    ],
                                    "lenient": true,
                                    "query": "\"AAA\" || \"BBB\" || <599 string seperated by || operator> "
                                }
                            },
                            {
                                "bool": {
                                    "minimum_should_match": "1",
                                    "should": [
                                        {
                                            "match": {
                                                "XXX": {
                                                    "query": "YYYY"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "explain": false,
    "_source": {
        "excludes": [],
        "includes": [
           "XXX",
            <115 fields>
        ]
    },
    "highlight": {
        "fields": {
            "XXX": {},
            <91 fields>
        }
    },
    "timeout": "60s",
    "track_total_hits": true,
    "track_scores": true,
    "size": 10000
} 

### Logs (if relevant)

In ES getting this exception
{"@timestamp":"2025-12-04T09:41:09.304Z", "log.level": "WARN", "message":"TransportMultiSearchAction failure", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[mdm-es-master-zone-b-0][search][T#7]","log.logger":"org.elasticsearch.action.search.TransportMultiSearchAction","elasticsearch.cluster.uuid":"bbfB3EfVQZ6osom5oHf3qA","elasticsearch.node.id":"j4NQDwkdRr-QKGG-IJA6TQ","elasticsearch.node.name":"mdm-es-master-zone-b-0","elasticsearch.cluster.name":"mdm","error.type":"org.elasticsearch.action.search.SearchPhaseExecutionException","error.message":"","error.stack_trace":"Failed to execute phase [fetch], \n\tat [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:693)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:693)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:101)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:101)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:29)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:29)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\nCaused by: java.lang.ArrayIndexOutOfBoundsException: Index 217 out of bounds for length 217\n\tat [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.SearchPhaseController.getHits(SearchPhaseController.java:463)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.SearchPhaseController.getHits(SearchPhaseController.java:463)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:376)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:376)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:248)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:248)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:117)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:117)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:96)\n\tat](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:96)\n\tat) [org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\t](mailto:org.elasticsearch.server@8.17.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\t)... 6 more\n"}

### PR DESCRIPTION
**Pull request by reugn**
When a search fetch phase times out on a shard with `allow_partial_search_results: true`, the coordinating node can hit an `ArrayIndexOutOfBoundsException` in `SearchPhaseController.getHits()` or `SearchPhaseController.mergeSuggest()`. This is caused by:

* `FetchPhaseDocsIterator.iterate()` — on timeout, used `System.arraycopy(searchHits, 0, partial, 0, i)` to build the partial result. Because docs are iterated in doc-id order but placed at their original (score-sorted) positions, this copy produced a corrupted array. It included nulls at unfilled positions and dropped valid hits stored beyond index `i`. Fixed by replacing the `arraycopy` with a `stripNulls` method that returns a compact array of only the successfully fetched hits.

* `SearchPhaseController.getHits()` / `mergeSuggest()` — the query phase promises N docs from a shard, but the fetch phase may return fewer after a timeout. The merge loop used a counter to index into the fetch result array without checking bounds, causing `ArrayIndexOutOfBoundsException`. Fixed by adding a bounds check that skips entries when the counter exceeds the available hits.

### Tests
* `FetchPhaseDocsIteratorTests.testTimeoutReturnsCompactPartialResults` — verifies that `iterate()` returns a compact array (no nulls, shorter than input) when a timeout occurs mid-fetch with unsorted doc ids.
* `SearchPhaseControllerTests.testMergeWithPartialFetchResults` — verifies that `SearchPhaseController.merge()` handles a shard returning fewer fetch hits than expected without throwing `ArrayIndexOutOfBoundsException`.

Fixes #140495

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhaseDocsIterator.java [hunk 1]
```diff
@@ -125,6 +124,10 @@ public final SearchHit[] iterate(
         return searchHits;
     }
 
+    private static SearchHit[] stripNulls(SearchHit[] searchHits) {
+        return Arrays.stream(searchHits).filter(Objects::nonNull).toArray(SearchHit[]::new);
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhaseDocsIterator.java]: drive by comment: Is there a certain overhead of using streams here, especially in the case when there are no nulls to strip? Would it be worth testing something like a for loop that counts null elements, and if that count is > 0, a new compact array is created, and returned?

Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhaseDocsIterator.java]: +1

Comment (reugn) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhaseDocsIterator.java]: Refactored to return the original array when there are no nulls. Streams are only used in the fallback path where reallocation is necessary.

File: server/src/test/java/org/elasticsearch/search/fetch/FetchPhaseDocsIteratorTests.java [hunk 2]
```diff
@@ -137,6 +141,66 @@ protected SearchHit nextDoc(int doc) {
...
+            writer.addDocument(doc);
+            if (i % 50 == 0) {
+                writer.commit();
+            }
+        }
+        writer.commit();
+        IndexReader reader = writer.getReader();
+        writer.close();
+
+        ContextIndexSearcher searcher = new ContextIndexSearcher(reader, null, null, new QueryCachingPolicy() {
```
Comment (spinscale) [inline server/src/test/java/org/elasticsearch/search/fetch/FetchPhaseDocsIteratorTests.java]: could use a `TrivialQueryCachingPolicy.NEVER` here?

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 3]
```diff
@@ -263,8 +263,10 @@ private static void mergeSuggest(
                 }
                 FetchSearchResult fetchResult = searchResultProvider.fetchResult();
                 final int index = fetchResult.counterGetAndIncrement();
-                assert index < fetchResult.hits().getHits().length
-                    : "not enough hits fetched. index [" + index + "] length: " + fetchResult.hits().getHits().length;
+                if (index >= fetchResult.hits().getHits().length) {
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:266]: is this codepath tested?

**Review by spinscale — APPROVED** [review]
LGTM, left two minor comments.

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java (hunk 3 above)
Comment (reugn) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:266]: Yes, there is the `SearchPhaseControllerTests.testMergeWithPartialFetchResults`.

Comment (spinscale) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:266]: This is in `SearchPhaseController.mergeSuggest()` - when setting a breakpoint in that method I don't see it getting called when running `testMergeWithPartialFetchResults` - am I missing something? :-)
