### PR TITLE
SQL: Return error with ORDER BY on non-grouped.

### LINKED ISSUE #34590: SQL: ORDER BY COUNT(*) should display an error message
The following behavior should return an error message about the limitations of `ORDER BY`, but instead is returning some seemingly incorrect results:

```
sql> select languages,count(*) from test_emp group by languages having count(*) > 10 order by count(emp_no);
   languages   |   COUNT(1)
---------------+---------------
1              |15
2              |19
3              |17
4              |18
5              |21
```

`composite` aggregation (what is used in any `group by` sql statements) cannot order on something else other than the key itself (in this case - `languages`). But, instead of returning an error message, it gives the false impression that the results are incorrect.

Related to https://github.com/elastic/elasticsearch/issues/31860.

### PR DESCRIPTION
**Pull request by matriv**
Previously, for some queries the validation for ORDER BY
fields didn't kick in since a HAVING close or an ORDER BY
with scalar function would add `Filter` and `Project` plans
between the `OrderBy` and the `Aggregate`.

Now the LogicalPlan tree beneath `OrderBy` is traversed and
the ORDER BY fields are properly verified.

Fixes: #34590

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java [hunk 1]
```diff
@@ -238,52 +238,54 @@ private static boolean checkGroupByOrder(LogicalPlan p, Set<Failure> localFailur
...
 
-                Map<Expression, Node<?>> missing = new LinkedHashMap<>();
-                o.order().forEach(oe -> {
-                    Expression e = oe.child();
-                    // cannot order by aggregates (not supported by composite)
-                    if (Functions.isAggregate(e)) {
-                        missing.put(e, oe);
-                        return;
-                    }
+            o.forEachDown(child -> {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: I would limit the down checks since in the future, with subqueries there might multiple `Aggs` underneath.
In other words an order by can have a Filter/Project&Filter before having an Agg. Checking the entire hierarchy seems too broad...

**Review by costin — COMMENTED** [review]
Left a comment regarding hierarchy depth.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java [hunk 2]
```diff
@@ -288,6 +302,11 @@ private static boolean checkGroupByOrder(LogicalPlan p, Set<Failure> localFailur
         return true;
     }
 
+    private static boolean lala(Expression e, List<Expression> groupingAndMatchingAggregatesAliases) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: ?

**Review by costin — APPROVED** [review]
LGTM.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: :( Tried to extract a method but not necessary, sorry!

**Review by astefan — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
Backported to `6.x` with 024116f0434019a8666dc37a4fd75e631f626c53

**Comment by matriv** [comment]
Backported to `6.5` with fa3abe3998a5085fbfafbc883ae4cd0d27f4d671
