### PR TITLE
Generalize how queries on `_index` are handled at rewrite time

### LINKED ISSUE #49254: Rewrite queries on unmapped fields as MatchNoDocsQueryBuilder
It's probably more easily explained with an example: `TermQueryBuilber#doToQuery` looks like this today

```java
    protected Query doToQuery(QueryShardContext context) throws IOException {
        Query query = null;
        MappedFieldType mapper = context.fieldMapper(this.fieldName);
        if (mapper != null) {
            query = mapper.termQuery(this.value, context);
        }
        if (query == null) {
            query = new TermQuery(new Term(this.fieldName, BytesRefs.toBytesRef(this.value)));
        }
        return query;
    }
```

So if the field is unmapped, we create a TermQuery on a field that doesn't exist, which is no different from returning a MatchNoDocsQuery.

It's becoming more and more common that multiple indices that have different mappings get queried together, e.g. as part of an alias or an index pattern, so a more efficient way to handle these cases would be to _rewrite_ to a `MatchNoDocsQueryBuilder` in the `rewrite()` method. This would help figure out that the shard cannot possibly match in the `can_match` phase and skip the `query` phase completely.

### PR DESCRIPTION
**Pull request by jpountz**
#49713 aims at introducing a new `constant_keyword` field which, like `_index`, always rewrites queries to a `MatchAllQueryBuilder` or a `MatchNoneQueryBuilder` in order to skip shards in the `can_match` phase. This change introduces a new `ConstantFieldType` marker class that helps get this functionality with any field and not just `_index`.

Since this change refactors rewrites, I also took it as an opportunity to adrress #49254: instead of returning the same queries you would get on a `keyword` field when a field is unmapped, queries get rewritten to a `MatchNoDocsQueryBuilder`.

This change exposed a couple bugs, like the fact that the percolator doesn't rewrite queries at query time, or that the `significant_terms` aggregation doesn't rewrite its inner filter, which I fixed.

Closes #49254

### CODE REVIEW

**Comment by jpountz** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by mayya-sharipova — APPROVED** [review]
thanks @jpountz, makes sense

File: modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java [hunk 1]
```diff
@@ -491,7 +488,13 @@ static Query toQuery(QueryShardContext context, boolean mapUnmappedFieldsAsStrin
         // as an analyzed string.
         context.setAllowUnmappedFields(false);
         context.setMapUnmappedFieldAsString(mapUnmappedFieldsAsString);
-        return queryBuilder.toQuery(context);
+    }
+
+    static Query parseQuery(QueryShardContext context, boolean mapUnmappedFieldsAsString, XContentParser parser) throws IOException {
```
Comment (jtibshirani) [inline modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java]: This looks unused, I think it can just be deleted?

File: server/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java [hunk 2]
```diff
@@ -103,7 +104,7 @@ public final Query toQuery(QueryShardContext context) throws IOException {
             if (boost != DEFAULT_BOOST) {
                 if (query instanceof SpanQuery) {
                     query = new SpanBoostQuery((SpanQuery) query, boost);
-                } else {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java]: For my knowledge, I'm wondering why this change (and the ones to `AbstractQueryTestCase`) were necessary.

**Review by jtibshirani — COMMENTED** [review]
This also looks good to me, I had one suggestion I wanted to raise but don't feel strongly about.  Currently the contract for classes implementing `ConstantFieldType` is that they should produce either `MatchNoDocsQuery` or `MatchAllDocsQuery` for certain query factory methods. They should also make sure to break out of `termsQuery` early if they find a match. To me this strategy felt more a bit more robust:
* Add abstract methods like `bool matchesExact(Object value, QueryShardContext context)` to `ConstantFieldType`.
* Define final versions of `termQuery`, `termsQuery`, etc. in `ConstantFieldType` that call into these methods.

**Comment by jpountz** [comment]
@jtibshirani Thanks for your comments, I wondered whether I should do something like that and leaned towards not doing it to avoid introducing new abstractions, but I also agree that it reduces chances to not implement the contract. I'll implement your suggestion.

File: server/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java (hunk 2 above)
Comment (jpountz) [reply server/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java]: I made this change as a way to keep tests simple. For instance here is what `ConstantScoreQueryBuilderTests#doAssertLuceneQuery` looks like in master today.

```
    @Override
    protected void doAssertLuceneQuery(ConstantScoreQueryBuilder queryBuilder, Query query, QueryShardContext context) throws IOException {
        Query innerQuery = queryBuilder.innerQuery().toQuery(context);
        if (innerQuery == null) {
            assertThat(query, nullValue());
        } else {
            assertThat(query, instanceOf(ConstantScoreQuery.class));
            ConstantScoreQuery constantScoreQuery = (ConstantScoreQuery) query;
            assertThat(constantScoreQuery.getQuery(), instanceOf(innerQuery.getClass()));
        }
    }
```

This test only worked because most queries on unmapped fields would create the same query as on a `keyword` field. But with this change, queries on unmapped fields get rewritten as a `MatchNoneQueryBuilder`. And when its inner query rewrites to a `MatchNoneQueryBuilder`, `ConstantScoreQueryBuilder` itself rewrites to a `MatchNoneQueryBuilder`. So I updated the logic this way:

```
    @Override
    protected void doAssertLuceneQuery(ConstantScoreQueryBuilder queryBuilder, Query query, QueryShardContext context) throws IOException {
        Query innerQuery = queryBuilder.innerQuery().rewrite(context).toQuery(context);
        if (innerQuery == null) {
            assertThat(query, nullValue());
        } else if (innerQuery instanceof MatchNoDocsQuery) {
            assertThat(query, instanceOf(MatchNoDocsQuery.class));
        } else {
            assertThat(query, instanceOf(ConstantScoreQuery.class));
            ConstantScoreQuery constantScoreQuery = (ConstantScoreQuery) query;
            assertThat(constantScoreQuery.getQuery(), instanceOf(innerQuery.getClass()));
        }
    }
```

But this fails if the inner query is wrapped in a `BoostQuery`. So I had to either change `AbstractQueryBuilder` to no longer wrap `MatchNoDocsQuery` with a boost, or change this test (and a couple other ones IIRC) to check whether the inner query might be wrapped inside a `BoostQuery`. I chose the former, which sounded simpler to me.

Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java]: Thanks for the clear explanation!

**Review by jtibshirani — APPROVED** [review]
