### PR TITLE
ESQL - date nanos range bug? 

### LINKED ISSUE #125439: [ES|QL] comparison between date-like params and date_nanos fields is failing
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:22 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6041 arm64

### Problem Description

Kibana's time picker params are causing errors when compared with `date_nanos` fields.

Image

### Steps to Reproduce

This is the query that is sent

```
POST /_query/async?drop_null_columns
{
  "query": "FROM sample* | WHERE date_nanos >= ?_tstart AND date_nanos <= ?_tend | LIMIT 10",
  "locale": "en",
  "include_ccs_metadata": true,
  "params": [
    {
      "_tstart": "2010-03-20T15:08:25.608Z"
    },
    {
      "_tend": "2025-03-20T15:08:25.608Z"
    }
  ],
  "filter": {
    "bool": {
      "must": [],
      "filter": [
        {
          "range": {
            "date_nanos": {
              "format": "strict_date_optional_time",
              "gte": "2010-03-20T15:08:25.608Z",
              "lte": "2025-03-20T15:08:25.608Z"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

And the mappings for that index

<details>

```
PUT sample/_mapping
{
  "properties": {
    "keyword_key": {
      "type": "keyword"
    },
    "text_message": {
      "type": "text"
    },
    "number_amount": {
      "type": "long"
    },
    "number_price": {
      "type": "float"
    },
    "bool_enabled": {
      "type": "boolean"
    },
    "binary_blob": {
      "type": "binary"
    },
    "date": {
      "type": "date"
    },
    "date_nanos": {
      "type": "date_nanos"
    },
    "object_user": {
      "properties": {
        "first": { "type": "text" },
        "last": { "type": "text" }
      }
    },
    "nested_user": {
      "type": "nested"
    },
    "flattened_labels": {
      "type": "flattened"
    },
    "range_time_frame": {
      "type": "date_range", 
      "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
    },
    "ip_addr": {
      "type": "ip"
    },
    "version": {
      "type": "version"
    },
    "vector": {
      "type": "dense_vector",
      "dims": 3
    },
    "geo_point": {
      "type": "geo_point"
    },
    "histogram" : {
      "type" : "histogram"
    },
    "rank_features": {
      "type": "rank_features" 
    },
    "geometry": {
      "type": "shape"
    }
  }
}
```
</details>

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by not-napoleon**
Fixes https://github.com/elastic/elasticsearch/issues/125439

We were incorrectly formatting nanosecond dates when building lucene queries.  We had missed this in our testing because none of the CSV tests were running against Lucene.  This happened because the date nanos test data includes multivalue fields.  Our warning behavior for multivalue fields is inconsistent between queries run in Lucene and queries run in pure ES|QL without pushdown.  Our warning tests, however, require that the specified warnings be present in all execution paths.  When we first built the date nanos CSV tests, we worked around this by always using an MV function to unpack the multivalue fields.  But we forgot that using an MV function prevents the entire query from being pushed down to Lucene, and thus that path wasn't being tested.  

In this PR, I've duplicated many of the tests to have a version that doesn't use the MV function, and uses `warningRegex` instead of `warning`.  The regex version does not fail if the header is absent, so it's safe to use in both modes.  Rewriting the tests this way revealed several situations in which this bug can manifest, all of which are fixed in this PR.  I cannot be confidant that there aren't more paths that can trigger this bug and aren't covered by these tests, but I haven't found any yet.

I've left some trace level logging that I found helpful while debugging this.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/EsqlBinaryComparison.java [hunk 1]
```diff
@@ -375,14 +382,35 @@ private Query translate(TranslatorHandler handler) {
...
+                + right().dataType()
+                + ">] left: ["
+                + left()
+                + "<"
+                + left().dataType()
+                + ">] attribute: ["
+                + attribute
+                + "<"
+                + attribute.dataType()
+                + ">]"
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/EsqlBinaryComparison.java:398]: Could you do this with `{}` so we don't build the string every time?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/Range.java [hunk 2]
```diff
@@ -210,12 +217,21 @@ private RangeQuery translate(TranslatorHandler handler) {
         String format = null;
 
         DataType dataType = value.dataType();
-        if (DataType.isDateTime(dataType) && DataType.isDateTime(lower.dataType()) && DataType.isDateTime(upper.dataType())) {
+        logger.trace(
+            "Translating Range into lucene query.  dataType is [" + dataType + "] upper is [" + upper + "]  lower is [" + lower + "]"
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/Range.java:221]: Could you do this with `{}` so we don't build the string every time?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsPhysicalOperationProviders.java [hunk 3]
```diff
@@ -180,6 +184,7 @@ public Function<org.elasticsearch.compute.lucene.ShardContext, Query> querySuppl
     @Override
     public final PhysicalOperation sourcePhysicalOperation(EsQueryExec esQueryExec, LocalExecutionPlannerContext context) {
         final LuceneOperator.Factory luceneFactory;
+        logger.trace("Query Exec is " + esQueryExec);
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/EsPhysicalOperationProviders.java:187]: Same comment as above.

**Review by nik9000 — APPROVED** [review]
I left some small stuff about the trace logs.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date_nanos.csv-spec [hunk 4]
```diff
@@ -1304,3 +1737,28 @@ diff_sec:integer | diff_sec_m:integer | n:date_nanos
 -18489600        | -18489599        | 2023-03-23T12:15:03.360103847Z
 -18489600        | -18489599        | 2023-03-23T12:15:03.360103847Z
 ;
+
+Regression out of bounds in where clause
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/date_nanos.csv-spec:1741]: Some more tests that I think could be helpful are having both lower and upper bounds with literals that can disqualify rows, more combinations of `>`, `>=`, `< `and `<=`, for example 
```
WHERE nanos > to_datenanos("2023-10-23T12:15:00") AND nanos <= to_datenanos("2023-10-23T13:53:55.832987654Z")

WHERE nanos >= to_datenanos("2023-10-23T12:15:00") AND nanos <= now()
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/Range.java [hunk 5]
```diff
@@ -31,18 +33,23 @@
...
 import static org.elasticsearch.xpack.esql.core.util.NumericUtils.unsignedLongAsNumber;
+import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.DEFAULT_DATE_NANOS_FORMATTER;
 import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.DEFAULT_DATE_TIME_FORMATTER;
 import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.dateTimeToString;
 import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.ipToString;
+import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.nanoTimeToString;
 import static org.elasticsearch.xpack.esql.type.EsqlDataTypeConverter.versionToString;
 
 // BETWEEN or range - is a mix of gt(e) AND lt(e)
 public class Range extends ScalarFunction implements TranslationAware.SingleValueTranslationAware {
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/Range.java:51]: There is a method `areBoundariesInvalid` to validate the lower and upper bounds, `date_nanos` can be added in there too, this can be a follow up.

**Review by fang-xing-esql — APPROVED** [review]
LGTM, thank you for fixing it quickly @not-napoleon! I added a couple of comments, they can be addressed as follow ups.
