### PR TITLE
[ML] Prevent submit after autodetect worker is stopped

### LINKED ISSUE #37108: [ML][CI] Unterminated update process task fails tests
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/156/console

A number of tests failed in `XPackRestIT` because of the autodetect update process tasks had not finished during the post test clean up
```
java.lang.AssertionError: 2 active tasks found:
cluster:internal/xpack/ml/job/update/process    _JTPNiDnTSebLObvZ_0c-Q:23948 -                            transport 1546458770524 19:52:50 31.4s       127.0.0.1 node-0 
cluster:internal/xpack/ml/job/update/process[n] _JTPNiDnTSebLObvZ_0c-Q:23949 _JTPNiDnTSebLObvZ_0c-Q:23948 direct    1546458770524 19:52:50 31.4s       127.0.0.1 node-0 
 expected:<0> but was:<2>
	at __randomizedtesting.SeedInfo.seed([C4836DEA74C9C87C:4CD75230DA35A584]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForPendingTasks$1(ESRestTestCase.java:341)
```

All the failures were due to the same unterminated task which was created during `ml/jobs_crud/Test update job`. When a job is updated and autodetect needs to also receive the same change then the autodetect update is scheduled to run later after the API call returns. At the end of the test the job is closed and deleted in the clean up section creating a race between updating autodetect and closing the job. It appears likely the update task that never terminated got involved in a race with closing/deleting the job.

Writes the autodetect process are queued and executed consecutively in order by `AutodetectWorkerExecutorService` the problem seems to be that [AutodetectWorkerExecutorService.execute](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java#L776) will accept a new runnable after it has been shutdown. This explains the hung task as it was scheduled after the job closed the stopped the executor and so was never executed.

### PR DESCRIPTION
**Pull request by davidkyle**
Runnables can be submitted to `AutodetectProcessManager.AutodetectWorkerExecutorService` without error after it has been shutdown which can lead to requests timing out as their handlers are never called by the terminated executor. This change throws an EsRejectedExecutionException if a runnable is submitted after after the shutdown and calls `AbstractRunnable.onRejection` on any tasks not run. 

Closes #37108

### CODE REVIEW

**Comment by davidkyle** [comment]
run elasticsearch-ci/1

**Comment by davidkyle** [comment]
run elasticsearch-ci/1

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java [hunk 1]
```diff
@@ -835,6 +845,19 @@ void start() {
...
+                    List<Runnable> notExecuted = new ArrayList<>();
+                    queue.drainTo(notExecuted);
+
+                    for (Runnable runnable : notExecuted) {
+                        if (runnable instanceof AbstractRunnable) {
+                            ((AbstractRunnable) runnable).onRejection(
+                                    new EsRejectedExecutionException("unable to process as autodetect worker service has shutdown", true));
+                        }
+                    }
+                }
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java]: I think there's still a race condition, although probably less likely than it was before.  Consider this scenario:

1. Thread 1 is running `start()`, and is preempted on line 841.
2. Thread 2 is calling `execute()`, and is preempted on line 828 while `running == true`.
3. Thread 3 calls `shutdown()` and sets `running = false`.
4. Thread 1 goes back on CPU and progresses to line 860, i.e. all the way through the `// if shutdown with tasks pending notify the handlers` block.
5. Thread 2 goes back on CPU and adds its `command` to the `queue`.

Step 5 happens after the queue is drained, so the problem this PR is trying to fix will still occur - its `command` is never run nor rejected.

One way to fix this race would be to make the whole of `execute()` `synchronized`, plus the queue draining part of `start()`, i.e. lines 849-860.

**Review by droberts195 — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java (hunk 1 above)
Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java]: Good point, there is a lesson here about rolling your own instead of using a proven executor. 

I looked at using a fixed threadpool of size 1 from `EsExecutors.newFixed` but that method wants ThreadFactory whereas here we use a single thread from the ml autodetect pool. My preference is to use one of the standard Executors but I can't see how to make that work
