### PR TITLE
Fix RestCancellableNodeClientTests.testConcurrentExecuteAndClose()

### LINKED ISSUE #129121: [CI] RestCancellableNodeClientTests testConcurrentExecuteAndClose failing
**Build Scans:**
- [elasticsearch-periodic #8633 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/ad2cnluymfdqw)
- [elasticsearch-periodic-platform-support #8570 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/34xtkx6odhtto)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.rest.action.RestCancellableNodeClientTests.testConcurrentExecuteAndClose" -Dtests.seed=45F957398E3CA54 -Dtests.jvm.argline="-Des.concurrent_search=true" -Dtests.locale=ff-Adlm-SL -Dtests.timezone=Asia/Kabul -Druntime.java=23
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.rest.action.RestCancellableNodeClientTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testConcurrentExecuteAndClose),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeAwait: CountDownLatch did not reach zero within the timeout
```

**Issue Reasons:**
- [8.17] 2 failures in test testConcurrentExecuteAndClose (0.5% fail rate in 440 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by JeremyDahlgren**
Fixes a race condition in `testConcurrentExecuteAndClose()` where `awaitClose()` is called before `addCloseListener()` has been called, resulting in a situation where `closeListener` is never completed and the `closeLatch` is never pulled.

Closes #129121

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java [hunk 1]
```diff
@@ -303,6 +303,10 @@ public void addCloseListener(ActionListener<Void> listener) {
             // if the channel is already closed, the listener gets notified immediately, from the same thread.
             if (open.get() == false) {
                 listener.onResponse(null);
+                // Handle scenario where awaitClose() was called before any calls to addCloseListener(), this ensures closeLatch is pulled.
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java]: Ah good point, but then could we achieve the same thing by dropping the whole `if (open.get() == false)` and always calling `closeListener.onResponse(ActionListener.assertOnce(listener));`? I guess that doesn't guarantee to complete `listener` on the calling thread in that case, not sure if this is important.

File: server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java [hunk 2]
```diff
@@ -303,6 +303,10 @@ public void addCloseListener(ActionListener<Void> listener) {
...
+                if (closeListener.isDone() == false) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java]: Can we `assertFalse(closeListener.isDone())` on this branch too? Seems like it'd be a test bug to want to add two of them?

Comment (JeremyDahlgren) [reply server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java]: When the channel is closed we can get more calls here since the channel is removed from `httpChannels` in `RestCancelllableNodeClient.CloseListener.onResponse()`, so a new `RestCancelllableNodeClient.CloseListener` is created in `RestCancelllableNodeClient.doExecute()`, which leads to `maybeRegisterChannel()` and then `httpChannel.addCloseListener()`.

File: server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java (hunk 1 above)
Comment (JeremyDahlgren) [reply server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java]: Yes `testChannelAlreadyClosed()` can fail on the unexpected `RestCancellableNodeClient.getNumChannels()` value if a listener is completed async.  I can update this test and refactor `TestHttpChannel` to support waiting for the `closeLatch` to get pulled after previously calling `close()`.  Right now you can't just call `awaitClose()` since it tries to first call `close()` which will fail since the atomic has already been set.

I'll try to simplify `TestHttpChannel.addCloseListener()` to address this comment and the other comment below, adjusting the existing tests and `TestHttpChannel` as needed.

File: server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java (hunk 2 above)
Comment (JeremyDahlgren) [reply server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java]: If we want to avoid multiple `addCloseListener()` calls it looks like we'd want to check if the `httpChannel` is closed at the beginning of `RestCancellableNodeClient.doExecute()` and complete the listener with a failure before returning.  But this would be a change in existing behavior and expected cancellations and we'd need to alter the tests for it.  To keep the change minimal in the PR I removed the `isDone()` check and added an additional comment to clarify what is expected when the channel is closed.  WDYT?

File: server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java [hunk 3]
```diff
@@ -303,6 +303,9 @@ public void addCloseListener(ActionListener<Void> listener) {
             // if the channel is already closed, the listener gets notified immediately, from the same thread.
             if (open.get() == false) {
                 listener.onResponse(null);
+                // Ensure closeLatch is pulled by completing the closeListener with a noop that is ignored if it is already completed.
+                // Note that when the channel is closed we may see multiple addCloseListener() calls, so we do not assert on isDone() here.
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/rest/action/RestCancellableNodeClientTests.java]: ... nor can we rely on the listener with which `closeListener` is completed itself being completed which is why we pass in a `noop()` after completing `listener` directly ourselves. Would you add words to that effect to this comment for the next reader?

This all seems kinda ugly but I don't have a better suggestion.

**Review by DaveCTurner — APPROVED** [review]
LGTM
