### PR TITLE
[Test] Reduce number of buckets in SearchResponseTests and AggregationsTests

### LINKED ISSUE #24891: SearchResponseTests.testFromXContent fails with a specific seed
Log is here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/1022/consoleFull

The problem reproduces locally for me:

```
gradle :core:test -Dtests.seed=F9669D4F3CD3E5FA -Dtests.class=org.elasticsearch.action.search.SearchResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Europe/Podgorica
```

The error is this:

```
ERROR   26.7s | SearchResponseTests.testFromXContent <<< FAILURES!
   > Throwable #1: java.lang.OutOfMemoryError: GC overhead limit exceeded
   >    at __randomizedtesting.SeedInfo.seed([F9669D4F3CD3E5FA:D80EA857B5740520]:0)
   >    at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
   >    at java.util.HashMap.putVal(HashMap.java:630)
   >    at java.util.HashMap.put(HashMap.java:611)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:978)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleXContent(ESTestCase.java:943)
   >    at org.elasticsearch.test.ESTestCase.toShuffledXContent(ESTestCase.java:908)
   >    at org.elasticsearch.action.search.SearchResponseTests.testFromXContent(SearchResponseTests.java:104)
```

Failure is seed-specific, as this works:

```
gradle :core:test -Dtests.class=org.elasticsearch.action.search.SearchResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true
```

### PR DESCRIPTION
**Pull request by tlrx**
`AggregationsTests.createTestInstance()` is used to generate a random aggregation that can contain multiple sub aggregations. The number of sub aggregation is limited (from 0 to 4) but sub aggregations can also have sub aggregations. This aggregation "tree" is limited in depth (only 5 levels of inner aggregations are allowed) but it can still get very big and cause OOM errors. This is mostly due to the way multi bucket aggregation are generated: each multi bucket aggregation is created with many buckets (up to 10 for histograms) and each bucket will be created with the same set of sub aggregations... It basically multiplies the number of aggregation for each bucket at each level of the aggregation tree, and it blows when printing out the XContent.

This pull request changes the InternalMultiBucketAggregationTestCase class so that it now has a `maxNumberOfBuckets` attribute with a default value of 25. When executed, up to 25 buckets can be generated by InternalMultiBucketAggregationTestCase sub classes. In specific cases like `AggregationsTests` and `SearchResponseTests`, where many aggregations are combined, the `maxNumberOfBuckets` is lowered down to 3. 

Closes #24891

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/search/aggregations/AggregationsTests.java [hunk 1]
```diff
@@ -93,7 +52,7 @@
     private static final List<InternalAggregationTestCase> aggsTests = getAggsTests();
 
     private static List<InternalAggregationTestCase> getAggsTests() {
-        List<InternalAggregationTestCase> aggsTests = new ArrayList<>();
+        List<InternalAggregationTestCase> aggsTests = new ArrayList<>();/*
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/AggregationsTests.java]: Leftover?

File: core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java [hunk 2]
```diff
@@ -57,7 +73,13 @@ public void setUp() throws Exception {
 
     @Override
     protected final T createTestInstance(String name, List<PipelineAggregator> pipelineAggregators, Map<String, Object> metaData) {
-        return createTestInstance(name, pipelineAggregators, metaData, subAggregationsSupplier.get());
+        final int maxNumberOfBuckets = maxNumberOfBuckets();
+        T instance = createTestInstance(name, pipelineAggregators, metaData, subAggregationsSupplier.get());
+
+        int numberOfBuckets = instance.getBuckets().size();
+        assertThat("Expecting a maximum number of "+ maxNumberOfBuckets + " buckets for " + instance.getClass().getSimpleName()
+                + " aggregation but got " + numberOfBuckets, numberOfBuckets, lessThanOrEqualTo(maxNumberOfBuckets));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java]: Can we make this a regular "assert" since it checks some assumptions about correct test setup rather than something in the aggregation we are testing.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java [hunk 3]
```diff
@@ -37,22 +39,24 @@
     @Override
     public void setUp() throws Exception {
         super.setUp();
-        keys = new ArrayList<>();
+        List<String> listOfKeys = new ArrayList<>();
         int numFilters = randomIntBetween(2, 4);
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java]: The number of buckets should be limited to 10 (4x4 matrix, but we only represent the upper triangular matrix). I would like it better if the maxNumberOfBuckets() was somehow tied to the number of filters we generate in this particular test. There are only three possibilities: 3 (for a 2x2 matrix), 6 (3x3 matric) and 10. Is allowing for max of 10 here possible (the AggregationsTests setup overwrite is okay I think)

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java [hunk 4]
```diff
@@ -37,22 +39,24 @@
...
-                    keys.add(filters[i] + "&" + filters[j]);
+                    listOfKeys.add(filters[i] + "&" + filters[j]);
                 } else {
-                    keys.add(filters[j] + "&" + filters[i]);
+                    listOfKeys.add(filters[j] + "&" + filters[i]);
                 }
             }
         }
+        Collections.shuffle(listOfKeys, random());
+        keys = Collections.unmodifiableList(listOfKeys.stream().limit(maxNumberOfBuckets()).collect(Collectors.toList()));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java]: See above comment, I'd like it if we didn't have to truncate the list of keys here.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogramTests.java [hunk 5]
```diff
@@ -55,7 +55,7 @@ protected InternalDateHistogram createTestInstance(String name,
                                                        List<PipelineAggregator> pipelineAggregators,
                                                        Map<String, Object> metaData,
                                                        InternalAggregations aggregations) {
-        int nbBuckets = randomInt(10);
+        int nbBuckets = randomNumberOfBuckets();
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogramTests.java]: I think 10 would be fine as a default as well instead of 25, it should be enough for meaninful tests.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java [hunk 6]
```diff
@@ -40,26 +42,28 @@
...
         if (randomBoolean()) {
-            ranges.add(Tuple.tuple(new BytesRef(randomAlphaOfLength(15)), null));
+            listOfRanges.add(Tuple.tuple(new BytesRef(randomAlphaOfLength(15)), null));
         }
         if (randomBoolean()) {
-            ranges.add(Tuple.tuple(null, null));
+            listOfRanges.add(Tuple.tuple(null, null));
         }
+        Collections.shuffle(listOfRanges, random());
+        ranges = Collections.unmodifiableList(listOfRanges.stream().limit(maxNumberOfBuckets()).collect(Collectors.toList()));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java]: Nit: If we do the shuffling, can we fill the listOfRanges with the random edge-cases (the null cases) first and then fill up the rest up to the available amount of buckets with other random values? That way we are sure to include the edge cases in 50% of the cases.
Its not super important here but I think it would be easier to understand than the truncation of the list.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalRangeTests.java [hunk 7]
```diff
@@ -67,7 +68,9 @@ public void setUp() throws Exception {
         if (rarely()) {
             listOfRanges.add(Tuple.tuple(randomDouble(), Double.POSITIVE_INFINITY));
         }
-        ranges = Collections.unmodifiableList(listOfRanges);
+
+        Collections.shuffle(listOfRanges, random());
+        ranges = Collections.unmodifiableList(listOfRanges.stream().limit(maxNumberOfBuckets()).collect(Collectors.toList()));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalRangeTests.java]: Same as above with regards to the edge cases.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/date/InternalDateRangeTests.java [hunk 8]
```diff
@@ -71,7 +72,8 @@ public void setUp() throws Exception {
                 listOfRanges.add(Tuple.tuple(start, randomDoubleBetween(start, end, false)));
             }
         }
-        dateRanges = Collections.unmodifiableList(listOfRanges);
+        Collections.shuffle(listOfRanges, random());
+        dateRanges = Collections.unmodifiableList(listOfRanges.stream().limit(maxNumberOfBuckets()).collect(Collectors.toList()));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/date/InternalDateRangeTests.java]: Same here.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/geodistance/InternalGeoDistanceTests.java [hunk 9]
```diff
@@ -56,7 +57,8 @@ public void setUp() throws Exception {
             listOfRanges.add(Tuple.tuple(0.0, max / 2));
             listOfRanges.add(Tuple.tuple(max / 3, max / 3 * 2));
         }
-        geoDistanceRanges = Collections.unmodifiableList(listOfRanges);
+        Collections.shuffle(listOfRanges, random());
+        geoDistanceRanges = Collections.unmodifiableList(listOfRanges.stream().limit(maxNumberOfBuckets()).collect(Collectors.toList()));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/geodistance/InternalGeoDistanceTests.java]: same here.

**Review by cbuescher — CHANGES_REQUESTED** [review]
Thanks for doing this, I think it makes sense to limit the size of the aggregation tree we create for tests. I left some notes regarding test setup where I think the number of available buckets could be distributed differently, but the rest looks good to me.

File: core/src/test/java/org/elasticsearch/search/aggregations/AggregationsTests.java (hunk 1 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/AggregationsTests.java]: Absolutely... I ran a last test with on date histogram buckets with max number of buckets and sub aggregations and then forgot to remove the comments :(

File: core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java (hunk 2 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java]: Good point

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java (hunk 3 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java]: I agree, I wasn't fully comfortable with that. What you suggest makes sense, I updated the code.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogramTests.java (hunk 5 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogramTests.java]: do you mean changing to 10 just here or also for all multi bucket aggs (see `InternalMultiBucketAggregationTestCase.DEFAULT_MAX_NUMBER_OF_BUCKETS`) ?

Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogramTests.java]: I meant in general, but I leave that to you. I think for testing that is still a large enough number. But I leave this to you.

Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogramTests.java]: Thinking about it again, I think 10 is good enough in general. Thanks Christoph

**Comment by tlrx** [comment]
@cbuescher Thanks a lot for your review, it helps. I updated the code, can you please have another look?

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java [hunk 10]
```diff
@@ -39,24 +37,27 @@
...
+                    keys.add(filters[i] + "&" + filters[j]);
                 } else {
-                    listOfKeys.add(filters[j] + "&" + filters[i]);
+                    keys.add(filters[j] + "&" + filters[i]);
                 }
             }
         }
-        Collections.shuffle(listOfKeys, random());
-        keys = Collections.unmodifiableList(listOfKeys.stream().limit(maxNumberOfBuckets()).collect(Collectors.toList()));
+        System.out.println("");
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/adjacency/InternalAdjacencyMatrixTests.java]: Nit: Leftover

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java [hunk 11]
```diff
@@ -32,27 +32,21 @@
...
 import java.util.Map;
-import java.util.stream.Collectors;
 
 public class InternalBinaryRangeTests extends InternalRangeTestCase<InternalBinaryRange> {
 
     private List<Tuple<BytesRef, BytesRef>> ranges;
 
     @Override
+    protected int minNumberOfBuckets() {
+        return 1;
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java]: Out of curiosity: was there a problem with the default of 0?

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java [hunk 12]
```diff
@@ -62,8 +56,17 @@ public void setUp() throws Exception {
         if (randomBoolean()) {
             listOfRanges.add(Tuple.tuple(null, null));
         }
+
+        final int numRanges = randomNumberOfBuckets() - listOfRanges.size();
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java]: Nit: I liked the Math.max() solution you use later better although this also works I think.

**Review by cbuescher — APPROVED** [review]
Thanks a lot, I like it.

File: core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java (hunk 11 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java]: Yes, the serialization test fails so I restore the previous 1 value

File: core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java [hunk 13]
```diff
@@ -57,7 +72,10 @@ public void setUp() throws Exception {
 
     @Override
     protected final T createTestInstance(String name, List<PipelineAggregator> pipelineAggregators, Map<String, Object> metaData) {
-        return createTestInstance(name, pipelineAggregators, metaData, subAggregationsSupplier.get());
+        T instance = createTestInstance(name, pipelineAggregators, metaData, subAggregationsSupplier.get());
+        assert instance.getBuckets().size() <= maxNumberOfBuckets() :
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java]: small suggestion: instead of having to verify this in the base class, how about having an abstract createBucket method that gets called as many times as needed from the base class? Then we could even think of dropping the minNumberOfBuckets and minNumberOfBuckets methods for simplicity and have subclasses override randomNumberOfBuckets only?
Leave this out if it makes things too complicated rather than simplifying. I think it would be cleaner but I am not sure how easy of a change it would be to make.

**Review by javanna — APPROVED** [review]
left one suggestion, LGTM otherwise. thanks a lot for fixing this @tlrx

**Comment by tlrx** [comment]
@elasticmachine retest this please

File: core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java (hunk 13 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/search/aggregations/InternalMultiBucketAggregationTestCase.java]: I thought about something like that too but I didn't manage to implement it because some aggs need to initialize the buckets in the setUp method while the others can just generate them in the createInstance() method. So a common createBucket() method doesn't fit very well and complicates things a bit. I'm going to merge the PR as it is now.
