### PR TITLE
[ESQL] Fix parsing of large magnitude negative numbers

### LINKED ISSUE #104323: Parsing large numbers is inconsistent
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

17

### OS Version

Ubuntu 23.04

### Problem Description

- Evaluating the query `row a=0 | EVAL b=1 > -9223372036854775809` returns
  ```
  {"error":{"root_cause":[{"type":"arithmetic_exception","reason":"BigInteger out of long 
  range"}],"type":"arithmetic_exception","reason":"BigInteger out of long range"},"status":500}
  ```
  This should at least return a 400.
- `row a=0 | EVAL b=1 > 9223372036854775809` returns
  ```
  {"error":{"root_cause":[{"type":"verification_exception","reason":"Found 1 problem\nline 1:18: first argument of [1 > 9223372036854775809] is [integer] and second is [unsigned_long]. [unsigned_long] can only be operated on together with another [unsigned_long]"}],
  "type":"verification_exception","reason":"Found 1 problem\nline 1:18: first argument of [1 > 9223372036854775809] is [integer] and second is [unsigned_long]. [unsigned_long] can only be operated on together with another [unsigned_long]"},"status":400}
  ```
  This is generally correct, but it's unexpected given that the following query runs fine:
  `row a=0 | EVAL b=1 > 92233720368547758090` (just add a 0 at the end).
  
  Maybe we should not cast literals to unsigned long, unless the user explicitly writes `to_ul(...)`?

### Steps to Reproduce

See above.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by not-napoleon**
Resolves https://github.com/elastic/elasticsearch/issues/104323

This fixes and adds tests for the first of the two bullets in the linked issue.  `ExpressionBuilder#visitIntegerValue` will attempt to parse a string as an integral value, and return a Literal of the appropriate type.  The actual parsing happens in `StringUtils#parseIntegral`.  That function has special handling for values that are larger than `Long.MAX_VALUE` where it attempts to turn them into unsigned longs, and if the number is still out of range, throw `InvalidArgumentException`.  `ExpressionBuilder` catches that `InvalidArgumentException` and tries to parse a `double` instead.  If, on the other hand, the value is smaller than `Long.MIN_VALUE`, `StringUtils` never enters the unsigned long path and just calls `intValueExact`, which throws `ArithmeticException`.  This PR solves the issue by catching that `ArithmeticException` and rethrowing it as an `InvalidArgumentException`.

### CODE REVIEW

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/util/StringUtils.java [hunk 1]
```diff
@@ -354,11 +354,15 @@ public static Number parseIntegral(String string) throws InvalidArgumentExceptio
...
-        } else {
-            return bi.longValueExact();
+        try {
+            // try to downsize to int if possible (since that's the most common type)
+            if (bi.intValue() == bi.longValue()) { // ternary operator would always promote to Long
+                return bi.intValueExact();
+            } else {
+                return bi.longValueExact();
+            }
+        } catch (ArithmeticException ae) {
```
Comment (bpintea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/util/StringUtils.java:364]: This works, but I'd probably check `bi` against `Long.MIN_VALUE` and throw a dedicated exception if strictly smaller. Since by the time you get here, you need to know that magnitude of positive number's been checked anyways to throw that message.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/floats.csv-spec [hunk 2]
```diff
@@ -1,4 +1,11 @@
 // Floating point types-specific tests
+parseLargeMagnitudeValues
+required_capability: fix_parsing_large_negative_numbers
+row a = 92233720368547758090, b = -92233720368547758090;
```
Comment (bpintea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/floats.csv-spec:4]: I'd also add the previously failing example from the bug report, just for completion (I also like the use of `-9223372036854775809` as first integer below Long.MIN_LONG that should be turned into a double).

**Review by bpintea — APPROVED** [review]
Lgtm, only added two optional notes.

**Comment by not-napoleon** [comment]
Manual backport PR: https://github.com/elastic/elasticsearch/pull/110758 (conflict was capabilities that we hadn't backported.  I just re-added the new capability for this fix)
