### PR TITLE
[ML] fixing data frame analysis test when two jobs are started in succession quickly

### LINKED ISSUE #53188: RegressionIT. testTwoJobsWithSameRandomizeSeedUseSameTrainingSet fails on master
This failure came in today running on the master branch. I was able to reproduce the failure locally 100% of the runs I tried:

```
org.elasticsearch.xpack.ml.integration.RegressionIT > testTwoJobsWithSameRandomizeSeedUseSameTrainingSet {seed=[FC6B2FF692026E68:60F2C02B52CBCBBF]} FAILED
    org.elasticsearch.ElasticsearchStatusException: Could not start data frame analytics task, allocation explanation [Not opening data frame analytics job [regression_two_jobs_with_same_randomize_seed_2], because not all primary shards are active for the following indices [.ml-state-000001]]
        at __randomizedtesting.SeedInfo.seed([FC6B2FF692026E68:60F2C02B52CBCBBF]:0)
        at org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction$AnalyticsPredicate.test(TransportStartDataFrameAnalyticsAction.java:457)
        at org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction$AnalyticsPredicate.test(TransportStartDataFrameAnalyticsAction.java:436)
        at org.elasticsearch.persistent.PersistentTasksService.lambda$waitForPersistentTaskCondition$1(PersistentTasksService.java:153)
        at org.elasticsearch.persistent.PersistentTasksService.waitForPersistentTaskCondition(PersistentTasksService.java:157)
        at org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction.waitForAnalyticsStarted(TransportStartDataFrameAnalyticsAction.java:390)
        at org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction$1.onResponse(TransportStartDataFrameAnalyticsAction.java:167)
        at org.elasticsearch.xpack.ml.action.TransportStartDataFrameAnalyticsAction$1.onResponse(TransportStartDataFrameAnalyticsAction.java:164)
        at org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:163)
        at org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:163)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:97)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:144)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:138)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:89)
        at org.elasticsearch.persistent.StartPersistentTaskAction$TransportAction.lambda$masterOperation$0(StartPersistentTaskAction.java:213)
        at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:113)
        at org.elasticsearch.persistent.PersistentTasksClusterService$1.clusterStateProcessed(PersistentTasksClusterService.java:121)
        at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.clusterStateProcessed(MasterService.java:529)
        at org.elasticsearch.cluster.service.MasterService$TaskOutputs.lambda$processedDifferentClusterState$1(MasterService.java:416)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.cluster.service.MasterService$TaskOutputs.processedDifferentClusterState(MasterService.java:416)
        at org.elasticsearch.cluster.service.MasterService.onPublicationSuccess(MasterService.java:276)
        at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:268)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:245)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
```
https://gradle-enterprise.elastic.co/s/6akvzoza2fmuc

Since it reproduces so consistently on my local run, I'm going to go ahead and mute the test.

### PR DESCRIPTION
**Pull request by benwtrent**
A previous change (#53029) is causing analysis jobs to wait for certain indices to be made available. While this it is good for jobs to wait, they could fail early on _start. 

This change will cause the persistent task to continually retry node assignment when the failure is due to shards not being available.

If the shards are not available by the time `timeout` is reached by the predicate, it is treated as a _start failure and the task is canceled. 

For tasks seeking a new assignment after a node failure, that behavior is unchanged.

closes #53188

### CODE REVIEW

**Comment by droberts195** [comment]
> For the end user, this does not pose much interruption as they can call _start again.

This is assuming the user is interactively sending requests, happy to retry and won't get confused or worried by the error response they get the first time.

If the "user" is actually an automated script then it probably won't retry.

An even a human user may open a support case instead of realising the problem is transient and retrying.

An example of where failures caused by starting lots of jobs simultaneously caused a problem in production is some of the data recognizer modules in the UI.  These can create and start 5 jobs in quick succession.  And when the functionality was first added it showed up a problem similar to the one that's led to this PR.

I think we need to fix this in the production code rather than the test code.

**Comment by benwtrent** [comment]
@droberts195 Then the solution would be to NOT fail immediately due to shards being unallocated. 

We can adjust the task predicate to `return false` so that it continues to wait for a good assignment. If we time out, then use whatever exception is stored and indicate a failure to cancel the task.

Does that sound good?

**Comment by benwtrent** [comment]
run elasticsearch-ci/oss-distro-docs

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java [hunk 1]
```diff
@@ -450,9 +470,15 @@ public boolean test(PersistentTasksCustomMetaData.PersistentTask<?> persistentTa
...
-            if (assignment != null && assignment.equals(PersistentTasksCustomMetaData.INITIAL_ASSIGNMENT) == false &&
-                assignment.isAssigned() == false) {
-                // Assignment has failed despite passing our "fast fail" validation
+            if (assignment != null
+                && assignment.equals(PersistentTasksCustomMetaData.INITIAL_ASSIGNMENT) == false
+                && assignment.isAssigned() == false) {
+                assignmentExplanation = assignment.getExplanation();
+                // Assignment failed due to primary shard check.
+                // This is hopefully intermittent and we should allow another assignment attempt.
+                if (assignmentExplanation.contains("not all primary shards are active")) {
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: The risk of mistakes in future maintenance would be reduced if the string `"], because not all primary shards are active for the following indices ["` from old line 587 was put in a constant and that same constant was used here too.

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: For sure!

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by droberts195 — APPROVED** [review]
LGTM
