### PR TITLE
Set default index mode for TimeSeries to `null`

### LINKED ISSUE #97429: Synthetic source is on by default for TSDS but does not appear in mappings
### Elasticsearch Version

8.7

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

As of 8.7 the default `_source` behaviour linked to `index.mode: time_series` was changed. Prior to 8.7, `_source` was explicitly stored, from this version onward it became synthetics.
This change cannot be easily visualised by users, as the corresponding setting (`"_source": {"mode": "synthetic"}`) doesn't appear in the resulting indices.
Moreover, if a user sets this by hand in a template, indices created don't have the setting. It is as if the setting is ignored by Elasticsearch upon index creation. This is extremely confusing for users.

In general, this behaviour is misleading, since there is no clear indication to the user that the `_source` isn't fully stored. Some customers also explicitly require their `_source` not to be tampered with, for legal and auditing reasons.

This behaviour (if intended) needs to be clearly documented in the [TSDS](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) or [`_source`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source) documentation page.
We further propose that any mapping or setting explicitly written in a template should be explicitly written in any index that is instantiated from it. Anything else is too misleading.
It is also somewhat of a concern that there now appear to be two separate sources of truth for `"mode": "synthetic"`: one in mappings and another hidden somewhere in our code.

### Steps to Reproduce

This can be reproduced by running the following (notice the change of behaviour pre/post 8.7):

```
PUT /_index_template/test
{
  "index_patterns": [
    "foobar*"
  ],
  "template": {
    "settings": {
      "index": {
        "mode": "time_series",
        "routing_path": [
          "host.name"
        ]
      }
    },
    "mappings": {
      "_source": {
        "mode": "synthetic"
      }
    }
  },
  "composed_of": [
  ],
  "priority": 500,
  "data_stream": {
  }
}

POST /_index_template/_simulate/test
```

Gives the following on 8.6.x:

```
    "mappings": {
      "_source": {
        "mode": "synthetic"
      }
    },
```

This very section disappears on 8.7.x, while synthetic source remains activated.

### PR DESCRIPTION
**Pull request by kkrik-es**
If the default index mode matches the specified, we skip printing the synthetic source info in mappings. This leads to confusion as it's not immediately visible (or well known) that time series indices use synthetic source by default.

Leaving the default index mode to null does the trick here. We do pass the right value for time series indexes while building the mapping so there's no other functional impact.

This was attempted in #98586, got rolled back because it broke bwc #98803. Rolling fwd with a fix for this.

Fixes https://github.com/elastic/elasticsearch/issues/97429

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java [hunk 1]
```diff
@@ -61,6 +62,18 @@ private enum Mode {
         IndexMode.TIME_SERIES
     );
 
+    /*
+     * Synthetic source was added as the default for TSDB in v.8.7. The legacy field mapper below
+     * is used in bwc tests and mixed clusters containing time series indexes created in an earlier version.
+     */
+    private static final SourceFieldMapper TSDB_NO_SYNTHETIC = new SourceFieldMapper(
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java:69]: Maybe rename to `TSDB_LEGACY_DEFAULT`?

**Review by martijnvg — APPROVED** [review]
I forgot to say this in the previous PR, but maybe we should add a rest test (that checks that source mode is included in template simulate api)?
Otherwise LGTM.

File: server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java (hunk 1 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java]: Done.
