### PR TITLE
Fixing KDE evaluate() to return correct ValueAndMagnitude object

### LINKED ISSUE #127517: `ChangePointDetector` doesn't detect a spike
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

`ChangePointDetector` class does not detect a spike for a constant function with one spike

### Steps to Reproduce

Using a unit test, I wanted to obtain a "spike" from a `ChangePointDetector`. The data I used (25 data points with a spike in the middle):
51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 500001, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51
The spike **did not get detected**.
When I added randomness (replaced 51 with randomLongBetween(50, 53) the spike **got detected**.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by Jason-Whitmore**
Issue #127517 describes `ChangePointDetector.getChangeType()` failing to detect a spike when all non spike values are constant (for example, the input [51,51,...,51,50001,51...,51]).

Prior to this change, the `KDE.evaluate()` method would return a special object for an input with `bandwidth == 0`. This would occur if the values excluding the spike had zero variance (see `KDE` constructor). This would then cause `ChangePointDetector.getChangeType()` and `SpikeAndDipDetector.detect()` to use the wrong p-value and fail to detect the spike.

This change removes the `bandwidth == 0` condition for returning a special `ValueAndMagnitude` object. Statistical testing in `ChangePointDetector.getChangeType()` and `SpikeAndDipDetector.detect()` now properly detect the spike in the example mentioned above.

Unit tests are added to confirm the bug is fixed.

Closes #127517

### CODE REVIEW

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
Thanks for your contribution @Jason-Whitmore and thanks for adding the tests, we will try to review this as soon as possible

**Comment by davidkyle** [comment]
@elasticmachine test this please

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/changepoint/KDE.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ private interface KernelFunction {
     }
 
     private ValueAndMagnitude evaluate(IntervalComplementFunction complement, KernelFunction kernel, double x) {
-        if (bandwidth == 0.0 || orderedValues.length == 0) {
+        if (orderedValues.length == 0) {
```
Comment (tveasey) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/changepoint/KDE.java:41]: Thanks for locating this issue. This is indeed broken. My inclination would be to have another special case for `bandwidth == 0` since the response is trivial in this case and then we don't run any risk of numerical issues:
```java
if (orderedValues.length == 0) {
    return new ValueAndMagnitude(1.0, 0.0);
}
if (bandwidth == 0) {
    return new ValueAndMagnitude(x != orderedValues[0] ? 0.0 : 1.0, Maths.abs(orderedValues[0] - x))
}
...
```

**Review by tveasey — COMMENTED** [review]
I propose a small tweak.

**Review by tveasey — APPROVED** [review]

**Comment by prwhelan** [comment]
@elasticmachine generate changelog

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Review by przemekwitek — APPROVED** [review]

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Comment by brianseeders** [comment]
@elasticmachine test this please

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Comment by prwhelan** [comment]
@elasticmachine test this please

**Comment by prwhelan** [comment]
@elasticmachine test this please
