### PR TITLE
ESQL: Prevent search functions work with a non-STANDARD index

### LINKED ISSUE #129778: ESQL: MATCH, MATCH_PHRASE allowed past LOOKUP JOIN (and fails uncontrolled)
### Description

The following query fails with an assertion[*], instead of a verification error:
```
FROM sample_data
| LOOKUP JOIN sample__data_ts_nanos_lookup ON client_ip
| WHERE message : "Disconnected"
```
Here's a second example, to make the field ownership clearer (i.e. belonging to the lookup index):
```
FROM employees
| EVAL language_code = languages
| LOOKUP JOIN languages_lookup ON language_code
| WHERE language_name : "French"
| KEEP emp_no, language_code, language_name, first_name
```

The verification works for KQL, QSTR, however, the error message should be improved: `[QSTR] function cannot be used after LOOKUP` (there's a splitting of node's name and only picking the first token).

Only tried main, 8.19 is probably affected too.

[*] Assertion failure:
```
[2025-07-03T16:11:34,186][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][esql_worker][T#5]], exiting java.lang.AssertionError: LuceneQueryExpressionEvaluato
r expects DocBlock as input
        at org.elasticsearch.compute.lucene.LuceneQueryEvaluator.executeQuery(LuceneQueryEvaluator.java:66)
        at org.elasticsearch.compute.lucene.LuceneQueryExpressionEvaluator.eval(LuceneQueryExpressionEvaluator.java:39)
        at org.elasticsearch.compute.operator.FilterOperator.process(FilterOperator.java:43)
        at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:85)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:265)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:185)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:406)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

### LINKED ISSUE #130561: ESQL: match full-text search function silently returning wrong results (empty) past LOOKUP JOIN
### Description

The following query returns successfully, but wrongly, with no results:

```
FROM employees
| EVAL language_code = languages
| LOOKUP JOIN languages_lookup ON language_code
| WHERE language_name : "French"
| KEEP emp_no, language_code, language_name, first_name
```

For reference, the exact match (`| WHERE language_name  == "French"`) returns:

```
    emp_no     | language_code | language_name |  first_name   
---------------+---------------+---------------+---------------
10001          |2              |French         |Georgi         
10008          |2              |French         |Saniya         
10016          |2              |French         |Kazuhito       
10017          |2              |French         |Cristinel      
10018          |2              |French         |Kazuhide       
10037          |2              |French         |null           
10039          |2              |French         |null           
10050          |2              |French         |Yinghua        
10056          |2              |French         |Brendon        
10059          |2              |French         |Alejandro      
10060          |2              |French         |Breannda       
10065          |2              |French         |Satosi         
10067          |2              |French         |Claudi         
10071          |2              |French         |Hisao          
10078          |2              |French         |Danel          
10079          |2              |French         |Kshitij        
10081          |2              |French         |Zhongwei       
10090          |2              |French         |Kendra         
10099          |2              |French         |Valter         

```

Related: #129778, we'll likely want to prevent `:` operator, and `MATCH`* functions be placed away from the `FROM`.

### PR DESCRIPTION
**Pull request by bpintea**
This introduces verifications to prevent search functions work on fields introduced by a LOOKUP JOIN righthand-side index.

This should be a temporary fix until we can either push these filters down also on the righthand-side of a JOIN or have these functions execute within the engine.

Closes #130561
Closes #129778

### CODE REVIEW

**Comment by carlosdelest** [comment]
> have these functions execute within the engine.

@bpintea search functions can be executed within the compute engine. Is there something specific we should do on the LOOKUP JOIN side for the engine to use them?

**Review by carlosdelest — APPROVED** [review]
LGTM from the prevention side - Would like to know more about how we can enable these functions in LOOKUP JOIN 🙂

**Comment by bpintea** [comment]
> Is there something specific we should do on the LOOKUP JOIN side for the engine to use them?

@carlosdelest, it looks like it'll require dedicated work: from the quick look I had, the `ShardContext` that the evaluators use refer the  lefthand-side of the JOIN index only. So the search functions queries end up as `MatchNoDocsQuery`. And that's why they do execute "fine", but never match.

PS. Since (some of?) these can be evaluated internally, should we enable the `EVAL`-uation on them? Or having them run on a computed field (ex. `| EVAL foo = CONCAT(...) | WHERE MATCH(foo, ...)`)?

**Comment by carlosdelest** [comment]
> the ShardContext that the evaluators use refer the lefthand-side of the JOIN index only. So the search functions queries end up as MatchNoDocsQuery. And that's why they do execute "fine", but never match.

Got it, thanks! 👍 

> PS. Since (some of?) these can be evaluated internally, should we enable the EVAL-uation on them?

We could. There are a number of restrictions that we're looking to lift.

> Or having them run on a computed field (ex. | EVAL foo = CONCAT(...) | WHERE MATCH(foo, ...))?

That's trickier - full text functions still depend on Lucene, even when being evaluated on the compute engine, so they depend on the field being indexed. 

We could implement them on a computed field in case we created a Lucene in-memory index - something doable, but it hasn't been prioritized yet.

**Comment by bpintea** [comment]
> That's trickier - full text functions still depend on Lucene, even when being evaluated on the compute engine, so they depend on the field being indexed.

Right, right. I think EVAL'ing might be handier, this the computed-value idea can wait (also for broader consensus for such a need).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java [hunk 1]
```diff
@@ -393,20 +396,48 @@ public Expression replaceQueryBuilder(QueryBuilder queryBuilder) {
...
                     );
                 }
             });
-        };
+        } else {
+            // Traverse the plan to find the EsRelation outputting the field
+            plan.forEachDown(p -> {
+                if (p instanceof EsRelation esRelation && esRelation.indexMode() != IndexMode.STANDARD) {
+                    // Check if this EsRelation supplies the field
+                    if (esRelation.output().stream().anyMatch(attr -> attr.id().equals(fieldAttribute.id()))) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java]: Wouldn't it be more efficient to do `esRelation.outputSet().contains(fieldAttribute)`?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java [hunk 2]
```diff
@@ -393,20 +396,48 @@ public Expression replaceQueryBuilder(QueryBuilder queryBuilder) {
     public BiConsumer<LogicalPlan, Failures> postAnalysisPlanVerification() {
         return (plan, failures) -> {
             super.postAnalysisPlanVerification().accept(plan, failures);
-            plan.forEachExpression(Match.class, m -> {
-                if (m.fieldAsFieldAttribute() == null) {
+            fieldVerifier(plan, this, () -> field, failures);
+        };
+    }
+
+    public static void fieldVerifier(LogicalPlan plan, FullTextFunction function, Supplier<Expression> fieldSupplier, Failures failures) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java]: nit: a more natural placement would maybe be inside `FullTextFunction` rather than `Match`, as other non-inheritors of `Match` also reach for this method?

Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java]: question: why is `fieldSupplier` a supplier, rather than using a simple `Expression`? Seems like we hand it `() -> field` every time.

**Review by alex-spies — APPROVED** [review]
Thanks a lot @bpintea ! Only minor comments from me, please consider them at your own discretion.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java]: It would, ofc, thx!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java]: Yes, was a lost intention, thanks.

Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/fulltext/Match.java]: It no longer needs to, refactored.

**Comment by bpintea** [comment]
Thanks Carlos, Alex!
