### PR TITLE
Fix VectorIT.testFilteredQueryStrategy 

### LINKED ISSUE #142511: [CI] VectorIT testFilteredQueryStrategy failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11858 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/fvyy7zlh5v34m)
- [elasticsearch-periodic-platform-support #11858 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/5empv7x2cb5bq)
- [elasticsearch-pull-request #120985 / part-1](https://gradle-enterprise.elastic.co/s/7nfn2zlmlpc5o)
- [elasticsearch-pull-request #120972 / part-1](https://gradle-enterprise.elastic.co/s/jr7ipclgscbcu)
- [elasticsearch-pull-request #120773 / part-1-fips](https://gradle-enterprise.elastic.co/s/nzoc5sm7jqw5y)
- [elasticsearch-pull-request #119717 / part-1](https://gradle-enterprise.elastic.co/s/uccxut3gcyuw4)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.query.VectorIT.testFilteredQueryStrategy" -Dtests.seed=E5D4CB127B31E377 -Dtests.locale=ka-Geor-GE -Dtests.timezone=America/Cuiaba -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.query.VectorIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testFilteredQueryStrategy'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: fanoutVectorOps [34] is not gt acornVectorOps [34]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step amazonlinux-2023_platform-support-aws
- [main] 6 failures in test testFilteredQueryStrategy (0.6% fail rate in 965 executions)
- [main] 2 failures in step amazonlinux-2023_platform-support-aws (33.3% fail rate in 6 executions)
- [main] 3 failures in step part-1 (0.5% fail rate in 613 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (0.7% fail rate in 609 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by davidkyle**
The failures in #142511 happen because in rare cases the number of ACORN ops can exceed the number of FANOUT ops because of competitive pruning in FANOUT. The rare case reproduces quite reliably if you run the test for 1000 iterations. 

Claude has suggested increasing K from 1 to 10. This forces the FANOUT mode to explore more nodes so effectively we hit the visit limit in every query. Then the assertions can remain the same (that FANOUT ops < ACORN ops unless the limit is reached).

Closes #142511

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/search/query/VectorIT.java [hunk 1]
```diff
@@ -83,9 +83,9 @@ public void testFilteredQueryStrategy() {
 
         float[] vector = new float[16];
         randomVector(vector, 25);
-        int upperLimit = 35;
+        int upperLimit = 100;
```
Comment (pmpailis) [inline server/src/internalClusterTest/java/org/elasticsearch/search/query/VectorIT.java]: If we change the `upperLimit`, wouldn't we now have ~66% docs passing the filter which would cause the default `HnswGraphSearcher` to be used instead of the `FilteredHnswGraphSearcher` as per `KnnSearchStrategy.Hnsw#useFilteredSearch` ?

File: muted-tests.yml [hunk 2]
```diff
@@ -130,9 +130,9 @@ tests:
 - class: org.elasticsearch.xpack.esql.common.spatial.H3SphericalGeometryTests
   method: testIndexPoints
   issue: https://github.com/elastic/elasticsearch/issues/142439
-- class: org.elasticsearch.search.query.VectorIT
-  method: testFilteredQueryStrategy
-  issue: https://github.com/elastic/elasticsearch/issues/142511
+- class: org.elasticsearch.xpack.esql.qa.single_node.GenerativeForkIT
+  method: test {csv-spec:match-function.testMatchWithReplace}
+  issue: https://github.com/elastic/elasticsearch/issues/142501
```
Comment (davidkyle) [inline muted-tests.yml]:
```suggestion
```

File: server/src/internalClusterTest/java/org/elasticsearch/search/query/VectorIT.java (hunk 1 above)
Comment (davidkyle) [reply server/src/internalClusterTest/java/org/elasticsearch/search/query/VectorIT.java]: Thanks for pointing that out I'v tried another idea of increasing K to 10 so that in fanout mode the visit limit is always reached. Not perfect but the test doesn't fail anymore

**Review by benwtrent — APPROVED** [review]
I am good with this. Did you run it with a bunch of iterations?

If this continues to be flaky, I wonder if we want to remove this test and instead do a lower level interception type of query that directly checks that the filtered searcher is used (which would be complicated, but not flaky). The key thing we are wanting to test here is not necessarily that filtered search always is better, but that ACORN is actually used which is USUALLY better :/

**Comment by davidkyle** [comment]
> Did you run it with a bunch of iterations?

Thousands. 

At least the test shows that ACORN is not worse.
