### PR TITLE
Segregate test methods in ThreadPoolMergeExecutorServiceDiskSpaceTests wrt to the mocked filesystems

### LINKED ISSUE #129296: [CI] ThreadPoolMergeExecutorServiceDiskSpaceTests testMergeTasksAreUnblockedWhenMoreDiskSpaceBecomesAvailable failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8716 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/wkfps3d4ztm34)
- [elasticsearch-pull-request #74922 / part-1](https://gradle-enterprise.elastic.co/s/oydzwz4srfgba)
- [elasticsearch-pull-request #74898 / part-1](https://gradle-enterprise.elastic.co/s/osfuchzkcxd7y)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.index.engine.ThreadPoolMergeExecutorServiceDiskSpaceTests.testMergeTasksAreUnblockedWhenMoreDiskSpaceBecomesAvailable" -Dtests.seed=7ECAE8321B9A9093 -Dtests.locale=fr-ML -Dtests.timezone=Asia/Pyongyang -Druntime.java=24
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.engine.ThreadPoolMergeExecutorServiceDiskSpaceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testMergeTasksAreUnblockedWhenMoreDiskSpaceBecomesAvailable),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: is <460L>
     but: was <467L>
```

**Issue Reasons:**
- [8.19] 3 failures in test testMergeTasksAreUnblockedWhenMoreDiskSpaceBecomesAvailable (2.9% fail rate in 102 executions)
- [8.19] 2 failures in step part-1 (5.0% fail rate in 40 executions)
- [8.19] 2 failures in pipeline elasticsearch-pull-request (5.3% fail rate in 38 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by albertzaharovits**
Previously, out of zealousness for testing efficiency, the mocked filesystems were reused across the test suite class.
But this makes tests liable to interference wrt to filesystem stats calls. Moreover, if one test fails, it can trigger failures in other test methods.

This PR recreates the mocked filesystems for every test method. 

Fixes #129296 #130205

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceDiskSpaceTests.java [hunk 1]
```diff
@@ -96,20 +97,21 @@ public static void installMockUsableSpaceFS() throws Exception {
...
-    @AfterClass
-    public static void removeMockUsableSpaceFS() {
+    @After
+    public void removeMockUsableSpaceFS() {
+        if (setThreadPoolMergeSchedulerSetting) {
+            assertWarnings(
+                "[indices.merge.scheduler.use_thread_pool] setting was deprecated in Elasticsearch "
+                    + "and will be removed in a future release. See the breaking changes documentation for the next major version."
+            );
+        }
```
Comment (albertzaharovits) [inline server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceDiskSpaceTests.java:107]: Unrelated change that consolidates warning headers assertions.

File: server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceDiskSpaceTests.java [hunk 2]
```diff
@@ -564,7 +556,7 @@ public void testAbortingOrRunningMergeTaskHoldsUpBudget() throws Exception {
                 testDoneLatch.await();
                 return null;
             }).when(stallingMergeTask).abort();
-            threadPoolMergeExecutorService.submitMergeTask(stallingMergeTask);
+            assertTrue(threadPoolMergeExecutorService.submitMergeTask(stallingMergeTask));
```
Comment (albertzaharovits) [inline server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceDiskSpaceTests.java:559]: Unrelated change, just to make sure nothing unexpectedly fails when submitting a merge task.

**Review by BrianRothermich — APPROVED** [review]
LGTM
