### PR TITLE
Make ScheduleWithFixedDelayTest.testRunnableDoesNotRunAfterCancellation not racy

### LINKED ISSUE #97725: [CI] ScheduleWithFixedDelayTests testRunnableDoesNotRunAfterCancellation failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/e4ydwjge3ruvc/tests/:server:test/org.elasticsearch.threadpool.ScheduleWithFixedDelayTests/testRunnableDoesNotRunAfterCancellation

**Reproduction line:**
```
gradlew ':server:test' --tests "org.elasticsearch.threadpool.ScheduleWithFixedDelayTests.testRunnableDoesNotRunAfterCancellation" -Dtests.seed=EF60604806F09B56 -Dtests.locale=en-MT -Dtests.timezone=Africa/Casablanca -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.threadpool.ScheduleWithFixedDelayTests&tests.test=testRunnableDoesNotRunAfterCancellation

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <11>
     but: was <12>

  at __randomizedtesting.SeedInfo.seed([EF60604806F09B56:7CB82F66A20A5BBE]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.threadpool.ScheduleWithFixedDelayTests.testRunnableDoesNotRunAfterCancellation(ScheduleWithFixedDelayTests.java:291)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by thecoop**
Fixes #97725 (hopefully) by eliminating the race condition on extreme thread scheduling cases

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/threadpool/ScheduleWithFixedDelayTests.java [hunk 1]
```diff
@@ -274,24 +276,48 @@ public ScheduledCancellable schedule(Runnable command, TimeValue delay, Executor
...
-        final CountDownLatch doneLatch = new CountDownLatch(iterations);
-        final Runnable countingRunnable = () -> {
+        int iterations = scaledRandomIntBetween(2, 12);
+
+        // we don't have the cancellable until we schedule the task, which needs the barrier object to reference in the closure
+        // so break the circular dependency here
+        AtomicReference<Runnable> checkCancel = new AtomicReference<>();
+
+        AtomicInteger counter = new AtomicInteger();
+        CyclicBarrier barrier = new CyclicBarrier(2, () -> checkCancel.get().run());
```
Comment (ldematte) [inline server/src/test/java/org/elasticsearch/threadpool/ScheduleWithFixedDelayTests.java:286]: This is clever, but it required me a bit too much to understand why 2 and how it interacts with the `for(i.. iteration) barrier.await()`. 
I see the point of using basic primitives in this kind of tests, to be as much as possible in control and depend on as little as possible, but I wonder if using `CompletableFuture` here could bring an advantage in readability.

**Review by ldematte — APPROVED** [review]
LGTM, left a small (optional) comment on readability

File: server/src/test/java/org/elasticsearch/threadpool/ScheduleWithFixedDelayTests.java (hunk 1 above)
Comment (thecoop) [reply server/src/test/java/org/elasticsearch/threadpool/ScheduleWithFixedDelayTests.java:286]: I'm not sure how CompetableFuture could be used here_

**Comment by thecoop** [comment]
@elasticsearchmachine rerun elasticsearch-ci/eql-correctness

File: server/src/test/java/org/elasticsearch/threadpool/ScheduleWithFixedDelayTests.java (hunk 1 above)
Comment (ldematte) [reply server/src/test/java/org/elasticsearch/threadpool/ScheduleWithFixedDelayTests.java:286]: You are right, I was thinking about having `countingRunnable` complete futures from an array and then `CompletableFuture.allOf(c).whenComplete((unused, throwable) -> cancellable.get().cancel());`, but reading the docs there is no guarantee that the continuation will run on the completing thread (it might, but it's not certain), opening the door for "another round" of counting to go. While the CyclicBarrier action is " performed by the last thread entering the barrier."
