### PR TITLE
QL: Add leniency option to SQL CLI

### LINKED ISSUE #67436: SQL: CLI: query fails to run against multi-value fields / arrays
The CLI client doesn't set the leniency parameter, so queries executed against multi-value fields fail.

```
sql> select * from kibana_sample_data_ecommerce limit 1;
Server error [Server encountered an error [Arrays (returned by [manufacturer]) are not supported]. [org.elasticsearch.xpack.ql.QlIllegalArgumentException: Arrays (returne
d by [manufacturer]) are not supported
        at org.elasticsearch.xpack.ql.execution.search.extractor.AbstractFieldHitExtractor.unwrapMultiValue(AbstractFieldHitExtractor.java:164)
        at org.elasticsearch.xpack.ql.execution.search.extractor.AbstractFieldHitExtractor.extractFromSource(AbstractFieldHitExtractor.java:257)
        at org.elasticsearch.xpack.ql.execution.search.extractor.AbstractFieldHitExtractor.extract(AbstractFieldHitExtractor.java:145)
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:128)
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:31)
        at org.elasticsearch.xpack.sql.execution.search.ResultRowSet.getColumn(ResultRowSet.java:37)
        at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18)
        at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$createResponse$2(TransportSqlQueryAction.java:116)
        at org.elasticsearch.xpack.sql.session.RowSet.forEachRow(RowSet.java:27)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:114)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponseWithSchema(TransportSqlQueryAction.java:109)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$0(TransportSqlQueryAction.java:84)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128)
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Add `lenient = true/false` command to CLI client to allow execution of lenient queries on multi-value fields.

Fixes #67436

### CODE REVIEW

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java [hunk 1]
```diff
@@ -37,4 +37,45 @@ public void testSelectWithWhere() throws IOException {
...
+
+            assertThat(cliWithLeniency.command("SELECT * FROM test"), RegexMatcher.matches("\\s*name\\s*\\|\\s*tags\\s*"));
+            assertThat(cliWithLeniency.readLine(), containsString("----------"));
+            assertThat(cliWithLeniency.readLine(), RegexMatcher.matches("\\s*foo\\s*\\|\\s*bar\\s*"));
+            assertEquals("", cliWithLeniency.readLine());
+        } finally {
+            cliWithLeniency.close();
+        }
+    }
+
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java:80]: Instead of duplicating this code, use a single test method where for the arguments list you use a `.randomFrom` and use the two variants as values to choose from.

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java [hunk 2]
```diff
@@ -102,6 +103,11 @@ public Cli(CliTerminal cliTerminal) {
             .withRequiredArg()
             .ofType(Boolean.class)
             .defaultsTo(Boolean.parseBoolean(System.getProperty("cli.check", "true")));
+        this.lenientOption = parser.acceptsAll(
+            Arrays.asList("l", "lenient"),
+            "Lenient and return first value for fields with multiple values"
```
Comment (astefan) [inline x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:108]: The description is a bit confusing. How about `Enable fields multi-value leniency. Returns the first value from the values array with no guarantee of consistent results. Accepts 'true' or 'false' values.`

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java [hunk 3]
```diff
@@ -102,6 +103,11 @@ public Cli(CliTerminal cliTerminal) {
             .withRequiredArg()
             .ofType(Boolean.class)
             .defaultsTo(Boolean.parseBoolean(System.getProperty("cli.check", "true")));
+        this.lenientOption = parser.acceptsAll(
```
Comment (astefan) [inline x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:106]: Looking at the already existent commands and options for CLI, I would have inclined to make `lenient` a command and not a cli option. For example, `fetch_size` is a command (`FetchSizeCliCommand` class). The command can be executed multiple times during the life of the cli and an user can change the leniency with each query executed.

**Review by astefan — COMMENTED** [review]
Looked at half of the code and, before proceeding further, I am wondering if `lenient` shouldn't have been a command (to be used inside the CLI) and not a CLI option (to be used as a parameter when the CLI is started).

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:106]: From the session configuration point of view, this would make indeed sense.
From a practical POV, not sure if changing this behavior on a query-by-query case would be as useful, but for those users that use the CLI integrated into other scripts, having it as an argument might be preferred.

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:108]: Yes, much better. Fixing it

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java:80]: Good point, fixing

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:106]: I agree, having a command would make it much more flexible, I'm implementing it now.
Do you think it makes sense to keep both (ie. the command AND the cli option) or should we just have the command?

Comment (astefan) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:106]: It doesn't make sense to have it in both places. We are not doing this for any setting/config so far. Please, implement it as a command only.

Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java]: OK, I removed the CLI option and replaced it with a command for now (`lenient = true/false`).
In case we decide to go with both, re-enabling the option is straight forward.

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java [hunk 4]
```diff
@@ -37,4 +37,14 @@ public void testSelectWithWhere() throws IOException {
         assertThat(readLine(), RegexMatcher.matches("\\s*2\\s*\\|\\s*test_value2\\s*"));
         assertEquals("", readLine());
     }
+
+    public void testLenientCommand() throws IOException {
+        index("test", body -> body.field("name", "foo").field("tags", new String[] { "bar", "bar" }));
+        assertThat(command("lenient = true"), containsString("true"));
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java:43]: Why not checking the whole line? `lenient set to true`

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java [hunk 5]
```diff
@@ -102,6 +103,7 @@ public Cli(CliTerminal cliTerminal) {
             .withRequiredArg()
             .ofType(Boolean.class)
             .defaultsTo(Boolean.parseBoolean(System.getProperty("cli.check", "true")));
+
```
Comment (astefan) [inline x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/Cli.java:106]: Unnecessary new line.

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/command/CliSession.java [hunk 6]
```diff
@@ -24,6 +24,7 @@
     private String fetchSeparator = "";
     private boolean debug;
     private boolean binary;
+    private boolean lenient = CoreProtocol.FIELD_MULTI_VALUE_LENIENCY;
```
Comment (astefan) [inline x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/command/CliSession.java:27]: There are more and more commands and configuration settings to set. I think it's worth considering taking all these out in a separate class, like `SqlConfiguration` one for example, and the CliSession to contain a reference to this configuration instance.

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/HttpClientRequestTests.java [hunk 7]
```diff
@@ -106,7 +106,7 @@ private void assertBinaryRequestForCLI(XContentType xContentType) throws URISynt
 
         prepareMockResponse();
         try {
-            httpClient.basicQuery(query, fetchSize);
+            httpClient.basicQuery(query, fetchSize, false);
```
Comment (astefan) [inline x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/HttpClientRequestTests.java:109]: Randomize the leniency value.

**Review by astefan — COMMENTED** [review]
Looking better. Left few more comments.

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/command/CliSession.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/command/CliSession.java:27]: Yes, it makes sense. Just wondering if it makes sense to have a separate PR for this.

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/command/CliSession.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-cli/src/main/java/org/elasticsearch/xpack/sql/cli/command/CliSession.java]: Done

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/HttpClientRequestTests.java [hunk 8]
```diff
@@ -106,7 +106,7 @@ private void assertBinaryRequestForCLI(XContentType xContentType) throws URISynt
 
         prepareMockResponse();
         try {
-            httpClient.basicQuery(query, fetchSize);
+            httpClient.basicQuery(query, fetchSize, randomFrom(true, false));
```
Comment (Luegg) [inline x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/HttpClientRequestTests.java:109]: Nit: there is also `randomBoolean()`

**Review by Luegg — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java [hunk 9]
```diff
@@ -37,4 +37,14 @@ public void testSelectWithWhere() throws IOException {
         assertThat(readLine(), RegexMatcher.matches("\\s*2\\s*\\|\\s*test_value2\\s*"));
         assertEquals("", readLine());
     }
+
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java:40]: I would create a test class just for this command. And, apart from the test you have below, I'd test the `false` scenario as well (the one that generates an error).

**Review by astefan — COMMENTED** [review]
Thank you for incorporating the reviews. I've left two more comments.

**Review by costin — APPROVED** [review]
LGTM - the only comment I would make is to rename CliSession#getConfiguration to cfg or configuration() since the config object is internal and final and cannot be set.
I'm late to this PR and it seems to be CliSession == CliConfiguration at the stage (CliSession doesn't really add anything extra and it has the same scope as configuration); however in the future there might be other things to add to it so I'm fine with the refactoring.

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/HttpClientRequestTests.java (hunk 8 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/HttpClientRequestTests.java]: Changed

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java (hunk 9 above)
Comment (luigidellaquila) [reply x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/cli/SelectTestCase.java]: Done

**Review by astefan — APPROVED** [review]
LGTM
