### PR TITLE
Fix race condition in queue size test

### LINKED ISSUE #28579: [CI] SizeBlockingQueueTests.testQueueSize fails on 6.x
I am seeing this failure every once in a while:

```
Suite: org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests
  1> [2018-02-08T18:01:44,333][INFO ][o.e.c.u.c.SizeBlockingQueueTests] [testQueueSize]: before test
  1> [2018-02-08T18:01:44,355][INFO ][o.e.c.u.c.SizeBlockingQueueTests] [testQueueSize]: after test
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=69113FDE6E332977 -Dtests.class=org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests -Dtests.method="testQueueSize" -Dtests.security.manager=true -Dtests.jvms=3 -Dtests.locale=id-ID -Dtests.timezone=Africa/Conakry
FAILURE 0.04s J2 | SizeBlockingQueueTests.testQueueSize <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <20>
   >      but: was <0>
   > 	at __randomizedtesting.SeedInfo.seed([69113FDE6E332977:1884A5ABD4B7A214]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests.testQueueSize(SizeBlockingQueueTests.java:91)
   > 	at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/server/build/testrun/test/J2/temp/org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests_69113FDE6E332977-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=374, maxMBSortInHeap=7.113482659052134, sim=RandomSimilarity(queryNorm=true): {}, locale=id-ID, timezone=Africa/Conakry
  2> NOTE: Linux 4.14.16-300.fc27.x86_64 amd64/Oracle Corporation 1.8.0_151 (64-bit)/cpus=8,threads=1,free=330397240,total=532152320
```

When running *all* tests (I haven't been able to reproduce it running as a single test)

Related to #28557

### PR DESCRIPTION
**Pull request by jasontedor**
The queue size test has a race condition. Namely the offering thread can run so quickly completing all of its offering iterations before the queue size thread ever has a chance to run a single size poll iteration. This means that the size will never actually be polled and the test can spuriously fail. What we really want to do here, since this test is checking for a race condition between polling the size of the queue and offers to the queue, we want to execute each iteration in lockstep giving the threads multiple changes for the race between polling the size and offers to occur. This commit addresses this by running the two threads in lockstep for multiple iterations so that they have multiple chances to race.

Closes #28579

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/common/util/concurrent/SizeBlockingQueueTests.java [hunk 1]
```diff
@@ -47,18 +49,25 @@ public void testQueueSize() throws InterruptedException {
...
+        final CyclicBarrier barrier = new CyclicBarrier(2);
 
-        final AtomicBoolean spin = new AtomicBoolean(true);
         final AtomicInteger maxSize = new AtomicInteger();
 
         // this thread will repeatedly poll the size of the queue keeping track of the maximum size that it sees
+        final int iterations = 1 << 16;
         final Thread queueSizeThread = new Thread(() -> {
             try {
                 latch.await();
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/common/util/concurrent/SizeBlockingQueueTests.java]: Looking at this I was wondering if the latch was needed with the introduction of the barrier, it can probably be removed.

**Review by cbuescher — APPROVED** [review]
Left a small comment, the rest looks good to me. Thanks for the explanation.
