### PR TITLE
Fix data stream retrieval in `DataStreamLifecycleServiceIT`

### LINKED ISSUE #124846: [CI] DataStreamLifecycleServiceIT testAutomaticForceMerge failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7007 / ubuntu-2004-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/uxfxg6ocdj3j2)
- [elasticsearch-periodic-platform-support #7007 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/5w3fhu75hzhhs)
- [elasticsearch-periodic #6985 / openjdk23_entitlements_true_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/hxd27kcyns6pi)
- [elasticsearch-pull-request #62601 / part-1](https://gradle-enterprise.elastic.co/s/dscjlzw6jr7fm)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:internalClusterTest" --tests "org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testAutomaticForceMerge" -Dtests.seed=A4A18D06FC83A975 -Dtests.locale=ksb -Dtests.timezone=America/Cambridge_Bay -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testAutomaticForceMerge),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

**Issue Reasons:**
- [main] 4 failures in test testAutomaticForceMerge (1.9% fail rate in 214 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #124950: [CI] DataStreamLifecycleServiceIT testErrorRecordingOnRetention failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7042 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/ogjc5plegb4mo)
- [elasticsearch-pull-request #62741 / part-1](https://gradle-enterprise.elastic.co/s/rwm6hgcjahere)
- [elasticsearch-periodic #6985 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/dl6cbyi5g3n54)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:internalClusterTest" --tests "org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testErrorRecordingOnRetention" -Dtests.seed=CFDE29E4917E878A -Dtests.locale=yrl-VE -Dtests.timezone=Africa/Conakry -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testErrorRecordingOnRetention),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

**Issue Reasons:**
- [main] 3 failures in test testErrorRecordingOnRetention (1.0% fail rate in 295 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #124999: [CI] DataStreamLifecycleServiceIT testLifecycleAppliedToFailureStore failing
**Build Scans:**
- [elasticsearch-intake #20200 / part1](https://gradle-enterprise.elastic.co/s/lsqpnndmxs5ka)
- [elasticsearch-pull-request #62630 / part-1](https://gradle-enterprise.elastic.co/s/bxmye6retkkiq)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:internalClusterTest" --tests "org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testLifecycleAppliedToFailureStore" -Dtests.seed=E12E2984ECFA793C -Dtests.locale=vmw-MZ -Dtests.timezone=Asia/Tbilisi -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testLifecycleAppliedToFailureStore),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

**Issue Reasons:**
- [main] 2 failures in test testLifecycleAppliedToFailureStore (0.4% fail rate in 454 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
These tests had the potential to fail when two consecutive GET data streams requests would hit two different nodes, where one node already had the cluster state that contained the new backing index and the other node didn't yet.

Caused by #122852

Fixes #124846
Fixes #124950
Fixes #124999

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 1]
```diff
@@ -854,6 +854,32 @@ private static Settings.Builder getExcludeSettings(int num, Settings.Builder bui
...
+    public static List<String> waitForDataStreamBackingIndices(String dataStreamName, int expectedSize) {
+        return waitForDataStreamIndices(dataStreamName, expectedSize, false);
+    }
+
+    /**
+     * Waits for the specified data stream to have the expected number of backing or failure indices.
+     */
+    public static List<String> waitForDataStreamIndices(String dataStreamName, int expectedSize, boolean failureStore) {
+        final var clusterService = internalCluster().getCurrentMasterNodeInstance(ClusterService.class);
+        final var listener = ClusterServiceUtils.addTemporaryStateListener(clusterService, clusterState -> {
```
Comment (nielsbauman) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:869]: David Turner suggested using a temporary cluster state listener instead of an `assertBusy` that uses the GET data streams transport action. This has improved performance as we can react to new cluster state updates immediately instead of waiting for the exponential backoff of `assertBusy`. The only "drawback" is that an `assertBusy` would implicitly cover the GET data streams transport action. I don't think we should rely on tests like these to cover that action - i.e. we should have dedicated tests that sufficiently cover the action, and I think we do.

Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:869]: I would rather not add the override that returns the cluster state like this. Instead, just await for the cluster to reach a suitable state and then use the regular APIs and transport actions to query what you need. That way you get the little bit of extra coverage from calling the transport action, and you also get some confidence that the state you were waiting for doesn't immediately vanish in the next update since the transport action may see a future state.

File: test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java [hunk 2]
```diff
@@ -263,14 +263,24 @@ public void clusterStateProcessed(ClusterState initialState, ClusterState newSta
         );
     }
 
-    public static SubscribableListener<Void> addTemporaryStateListener(ClusterService clusterService, Predicate<ClusterState> predicate) {
-        final var listener = new SubscribableListener<Void>();
+    public static SubscribableListener<ClusterState> addTemporaryStateListener(
```
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java:266]: Having to obtain the cluster state in another way is a feature, not a bug :)

File: test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java [hunk 3]
```diff
@@ -284,11 +294,7 @@ public String toString() {
         };
         clusterService.addListener(clusterStateListener);
         listener.addListener(ActionListener.running(() -> clusterService.removeListener(clusterStateListener)));
-        if (predicate.test(clusterService.state())) {
-            listener.onResponse(null);
-        } else {
-            listener.addTimeout(ESTestCase.SAFE_AWAIT_TIMEOUT, clusterService.threadPool(), EsExecutors.DIRECT_EXECUTOR_SERVICE);
-        }
+        listener.addTimeout(ESTestCase.SAFE_AWAIT_TIMEOUT, clusterService.threadPool(), EsExecutors.DIRECT_EXECUTOR_SERVICE);
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java:297]: Checking the current cluster state is important I think, or else we will always have to wait for the next state update (which might not ever happen)

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 1 above)
Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:869]: Hm, that reduces the performance benefit because we'll have to do another request, but only by a little bit I think. I agree that it does bring back some extra coverage. I'll revert the changes to `addTemporaryStateListener` and use the API to fetch the backing indices.

File: test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java (hunk 3 above)
Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java:297]: I still do that, I just moved it up a few lines to the start of the method. That avoids adding the cluster state listener unnecessarily.

Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java:292]: Ah but you have to check the state _after_ adding the listener, or else you might miss an update that happens in between checking the state and adding the listener.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 1 above)
Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:871]: The performance benefits are all about avoiding the `Thread.sleep` in the `assertBusy` call, oversleeping past the point where the cluster state is ready for you. The cost of the transport action should be very low.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 4]
```diff
@@ -854,10 +854,44 @@ private static Settings.Builder getExcludeSettings(int num, Settings.Builder bui
...
+            final var dataStream = clusterState.metadata().getProject().dataStreams().get(dataStreamName);
+            if (dataStream == null) {
+                return false;
+            }
+            return dataStream.getDataStreamIndices(failureStore).getIndices().size() == expectedSize;
+        });
+        safeAwait(listener);
+        final var backingIndexNames = getDataStreamBackingIndexNames(dataStreamName, failureStore);
+        assertEquals("Retrieved number of data stream indices doesn't match expectation", expectedSize, backingIndexNames.size());
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:880]: suggest mentioning the data stream name in the message, and also using `assertThat("...", backingIndexNames, hasSize(expectedSize))` so you get to see more detail if it fails

**Review by DaveCTurner — COMMENTED** [review]
General pattern of changes looks good but I'll leave a detailed review to someone else if that's ok

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 4 above)
Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:880]: I'll add the data stream name in the message, but I don't think the assertion mechanism changes much:
current implementation gives
```
Retrieved number of data stream indices doesn't match expectation
Expected :1
Actual   :2
<Click to see difference>

java.lang.AssertionError: Retrieved number of data stream indices doesn't match expectation expected:<1> but was:<2>
	at __randomizedtesting.SeedInfo.seed([779A73C770529FF8:DDD333CAFBC6DD08]:0)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.elasticsearch.test.ESIntegTestCase.waitForDataStreamIndices(ESIntegTestCase.java:880)
	at org.elasticsearch.test.ESIntegTestCase.waitForDataStreamBackingIndices(ESIntegTestCase.java:861)
	at org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testErrorRecordingOnRetention(DataStreamLifecycleServiceIT.java:643)
```
Your suggestion gives
```
Retrieved number of data stream indices doesn't match expectation
Expected: a collection with size <1>
     but: collection size was <2>
java.lang.AssertionError: Retrieved number of data stream indices doesn't match expectation
Expected: a collection with size <1>
     but: collection size was <2>
	at __randomizedtesting.SeedInfo.seed([779A73C770529FF8:DDD333CAFBC6DD08]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2674)
	at org.elasticsearch.test.ESIntegTestCase.waitForDataStreamIndices(ESIntegTestCase.java:881)
	at org.elasticsearch.test.ESIntegTestCase.waitForDataStreamBackingIndices(ESIntegTestCase.java:862)
	at org.elasticsearch.datastreams.lifecycle.DataStreamLifecycleServiceIT.testErrorRecordingOnRetention(DataStreamLifecycleServiceIT.java:643)
```
I'll add the retrieved index names to the message/reason, that should probably help debugging.

Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:880]: oh hm that's disappointing, I thought `hasSize` reported the contents of the collection too

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java [hunk 5]
```diff
@@ -263,12 +231,12 @@ public void testSystemDataStreamRetention() throws Exception {
                     ).actionGet();
                     assertThat(getDataStreamResponse.getDataStreams().size(), equalTo(1));
                     assertThat(getDataStreamResponse.getDataStreams().get(0).getDataStream().getName(), equalTo(SYSTEM_DATA_STREAM_NAME));
-                    List<Index> backingIndices = getDataStreamResponse.getDataStreams().get(0).getDataStream().getIndices();
-                    assertThat(backingIndices.size(), equalTo(1)); // global retention is ignored
+                    List<Index> currentBackingIndices = getDataStreamResponse.getDataStreams().get(0).getDataStream().getIndices();
```
Comment (gmarouli) [inline modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java:234]: We could use `getDataStreamBackingIndexNames(SYSTEM_DATA_STREAM_NAME)` here, right?

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java [hunk 6]
```diff
@@ -476,7 +422,8 @@ public void testAutomaticForceMerge() throws Exception {
         int finalGeneration = randomIntBetween(3, 4);
         for (int currentGeneration = 1; currentGeneration < finalGeneration; currentGeneration++) {
             // This is currently the write index, but it will be rolled over as soon as data stream lifecycle runs:
-            final String toBeRolledOverIndex = getBackingIndices(dataStreamName).get(currentGeneration - 1);
+            final var backingIndexNames = waitForDataStreamBackingIndices(dataStreamName, currentGeneration);
```
Comment (gmarouli) [inline modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java:425]: Were there failures here and you added the wait?

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java [hunk 7]
```diff
@@ -567,40 +504,18 @@ public void testErrorRecordingOnRollover() throws Exception {
...
-            ErrorEntry writeIndexRolloverError = null;
-            Iterable<DataStreamLifecycleService> lifecycleServices = internalCluster().getInstances(DataStreamLifecycleService.class);
-
-            for (DataStreamLifecycleService lifecycleService : lifecycleServices) {
-                writeIndexRolloverError = lifecycleService.getErrorStore().getError(Metadata.DEFAULT_PROJECT_ID, writeIndexName);
-                if (writeIndexRolloverError != null) {
-                    break;
-                }
-            }
+            DataStreamLifecycleService lifecycleService = internalCluster().getCurrentMasterNodeInstance(DataStreamLifecycleService.class);
```
Comment (gmarouli) [inline modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java:516]: Nice!

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 8]
```diff
@@ -854,10 +854,53 @@ private static Settings.Builder getExcludeSettings(int num, Settings.Builder bui
...
+     * Waits for the specified data stream to have the expected number of backing indices.
+     */
+    public static List<String> waitForDataStreamBackingIndices(String dataStreamName, int expectedSize) {
+        return waitForDataStreamIndices(dataStreamName, expectedSize, false);
+    }
+
+    /**
+     * Waits for the specified data stream to have the expected number of backing or failure indices.
+     */
+    public static List<String> waitForDataStreamIndices(String dataStreamName, int expectedSize, boolean failureStore) {
```
Comment (gmarouli) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: Food for thought, what if instead of `expectedSize` we would add a predicate here. This would change the nature of this to wait for condition or something, but it might make it more reusable and extend the benefit of avoiding a `Thread.sleep` in other places too. What do you think?

**Review by gmarouli — APPROVED** [review]
LGTM, I added some comments but this is already an improvement :) . Thanks for fixing it.

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java (hunk 5 above)
Comment (nielsbauman) [reply modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java:234]: We're serializing the `getDataStreamResponse` to XContent a few lines below, so I preferred this over doing two API calls.

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java (hunk 6 above)
Comment (nielsbauman) [reply modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java:425]: Yep, https://github.com/elastic/elasticsearch/issues/124846 failed on that exact line. My theory of what happened is that at the end of this for-loop we fetch the data stream backing indices and we do so too at the start of this for-loop (i.e. this line). That's the same pattern we're seeing in the other test failures too.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 8 above)
Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: Yeah, I thought about that too. I decided to not do that (yet) as I didn't see any use cases where that would be relevant. On second thought, I think sections like these could make use of that:
https://github.com/elastic/elasticsearch/blob/b08eea64ed27ad1d744a8a689e78ca7aa5c9abef/modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/lifecycle/DataStreamLifecycleServiceIT.java#L185-L192
However, in that case, it doesn't really make sense to retrieve the backing indices. Then, having a different dedicated method just for data stream predicates feels a little over-specific, so a generic cluster-state predicate one is probably more sensible. However, then we're getting pretty close to the `addTemporaryStateListener` already (and the [`awaitClusterState`](https://github.com/elastic/elasticsearch/blob/b08eea64ed27ad1d744a8a689e78ca7aa5c9abef/test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java#L213-L213)). I would still see value in adding a wrapper in `ESIntegTestCase` that fetches the `ClusterService` instance from the master node, to avoid having to do that in every test. What do you think?

Comment (gmarouli) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: Hm, I would say it depends on how much is this going to be used, for example:
- If it's used only in this file, the helper method could reside in this file.
- If it's used only in this module, then the helper could be part of a fixture and that all the other tests use. If I am not mistaken we have more methods that could go there.
- If it's used by many tests scattered all over the place, then I agree that it's worth putting it in `ESIntegTestCase`

If you agree with the above, where do you think this should reside?

Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: I'll respond to those questions later, but I'm not sure how they're related to this discussion? I was referring to the implementation of the additional helper method.

Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: I'm going to merge this for now. There are other similar test suites that need to be updated. When I get to those, I'll automatically see what potential other use cases there are and we can adjust the helper method accordingly.

Comment (gmarouli) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: ah, I misunderstood. What I had in mind was that we can share the method that you said would be rather specific:

> Then, having a different dedicated method just for data stream predicates feels a little over-specific

Let me try to understand better what you meant with the following:

>  I would still see value in adding a wrapper in `ESIntegTestCase` that fetches the `ClusterService` instance from the master node, to avoid having to do that in every test

You mean to avoid doing this: `final var clusterService = internalCluster().getCurrentMasterNodeInstance(ClusterService.class);`? Something like:

```
public static SubscribableListener<Void> addTemporaryStateListener(Predicate<ClusterState> predicate) {
     final var clusterService = internalCluster().getCurrentMasterNodeInstance(ClusterService.class);
     return ClusterServiceUtils.addTemporaryStateListener(clusterService, predicate);
}
```

Not sure, if this is worth it honestly, considering it's only one line of code. Do you think this is too much of the mental load for a developer?

Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: See https://github.com/elastic/elasticsearch/pull/125648

Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:867]: @gmarouli, FTR, I agree that the mental load is minimal. I have a personal vendetta with boilerplate/duplicate code. In general, I'm also a fan of reducing test method sizes, as I feel a lot of our tests are hard to read, so any line reduction is a win in my eyes.
