### PR TITLE
Don't remove warning headers on all failure

### LINKED ISSUE #75739: Warning headers are removed on any failure
Whenever a request fails, the previously emitted response header warnings are removed from a response.
This was intentionally done so that when authentication fails, there would be no warnings presented to a user.
However when a failure is not related to authentication, headers are removed as well.
I suspect this behaviour fails only when security is enabled 

introduced by https://github.com/elastic/elasticsearch/pull/64948

reproduction steps:
1. create an index
2. send a request that emits a warning and also fails. For instance a rest api compatible `typed` search endpoint - emits deprecation warning- and typed query - fails parsing.
3. ```curl --request GET \
  --url http://localhost:9200/test1/sometype/_search \
  --header ‘Accept: application/vnd.elasticsearch+json;compatible-with=7’ \
  --header ‘Authorization: Basic ZWxhc3RpYzpwYXNzd29yZA==’ \
  --header ‘Content-Type: application/vnd.elasticsearch+json;compatible-with=7’ \
  --header ‘X-Opaque-ID: he’ \
  --data ‘{
	“query”: {
		“type”:{
			“value”: “_doc”
		}
	}
}’
```
`Warning` headers are missing

### PR DESCRIPTION
**Pull request by BigPandaToo**
We shouldn't remove warning when request is failing not because of
security reasons (syntax error for ex.).
Note, that security related failure could happen not only during
authentication (therefore we will check for the rest status), also all
failures happened during authentication will be considered security
related and warnings will be removed from the response.

Resolves: #75739

### CODE REVIEW

**Comment by BigPandaToo** [comment]
@jbaiera adding you, because this change affecting your recent addition to SecurityRestFilter

**Comment by tvernum** [comment]
Can we have a test for this please?

I think we need 3 basic tests all of which generate warning headers, then
- one fails during authentication
- one throws an exception in the inner rest handler
- the other throws no exceptions

And check that the warning header is removed in the first case, but not in the other 2.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/SecurityRestFilter.java [hunk 1]
```diff
@@ -89,17 +100,21 @@ public void handleRequest(RestRequest request, RestChannel channel, NodeClient c
...
+                }, e -> handleException(ActionType.Authentication, request, channel, e)));
         } else {
             restHandler.handleRequest(request, channel, client);
         }
     }
 
-    private void handleException(String actionType, RestRequest request, RestChannel channel, Exception e) {
-        logger.debug(new ParameterizedMessage("{} failed for REST request [{}]", actionType, request.uri()), e);
+    protected void handleException(ActionType actionType, RestRequest request, RestChannel channel, Exception e) {
+        logger.debug(new ParameterizedMessage("{} failed for REST request [{}]", actionType.name(), request.uri()), e);
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/SecurityRestFilter.java:117]:
```suggestion
        logger.debug(new ParameterizedMessage("{} failed for REST request [{}]", actionType, request.uri()), e);
```

`.name()` will return the enum constant. I think you want to use the `toString` here instead don't you?

**Review by tvernum — APPROVED** [review]

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/SecurityRestFilter.java [hunk 2]
```diff
@@ -109,11 +124,14 @@ private void handleException(String actionType, RestRequest request, RestChannel
 
                 @Override
                 public Map<String, List<String>> filterHeaders(Map<String, List<String>> headers) {
-                    if (headers.containsKey("Warning")) {
-                        headers = Maps.copyMapWithRemovedEntry(headers, "Warning");
-                    }
-                    if (headers.containsKey("X-elastic-product")) {
-                        headers = Maps.copyMapWithRemovedEntry(headers, "X-elastic-product");
+                    if (actionType != ActionType.RequestHandling
+                        || (restStatus == RestStatus.UNAUTHORIZED || restStatus == RestStatus.FORBIDDEN)) {
```
Comment (ywangd) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/SecurityRestFilter.java:128]: Do we want to remove warning headers on `403` (`FORBIDDEN`)? A `403` means authentication is successful. IIUC, the original intention is to remove warnings if authentication fails, i.e. `401`.

Comment (BigPandaToo) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/SecurityRestFilter.java:128]: We discussed it with @tvernum. More broadly the intention was to remove warnings in case request fails because of any security problem, which include failing authentication and failing the request handling because access was denied at some point of the handling.

Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/SecurityRestFilter.java:128]: Thanks for the clarification!

**Comment by BigPandaToo** [comment]
@elasticmachine update branch

**Comment by BigPandaToo** [comment]
@elasticmachine update branch

**Comment by BigPandaToo** [comment]
@elasticmachine update branch

**Comment by BigPandaToo** [comment]
@elasticmachine update branch
