### PR TITLE
Fix `_id` field fetch issue

### LINKED ISSUE #94515: `_id` field not returned consistently via Fields API
### Elasticsearch Version

8.6.2

### Installed Plugins

_No response_

### Java Version

Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/18.0.2/18.0.2+9-61

### OS Version

Mac OS X/12.6.3/aarch64

### Problem Description

The [fields option](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.htm) lets you query the
metadata `_id` field, but this field doesn't seem to be returned consistently over larger search result sets.

### Steps to Reproduce

 add several small documents to a test index with e.g.
```
POST /test/_doc
{
  "foo" : "bar"
}
```
then query e.g. top 10 docs disabling `_source` and querying `_id` via `fields`:

```
GET test/_search
{
  "_source": false,
  "fields": [
    "_id"
  ],
  "size": 10,
  "query": {
    "match_all": {}
  }
}
```

In my current reproduction on 8.6.2 this returns e.g.
```
  "hits": [
            {
                "_index": "test",
                "_id": "082y5YYBJUrNWn3IOYNS",
                "_score": 1,
                "fields": {
                    "_id": [
                        "082y5YYBJUrNWn3IOYNS"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "1M2y5YYBJUrNWn3IQIOO",
                "_score": 1,
                "fields": {
                    "_id": [
                        "1M2y5YYBJUrNWn3IQIOO"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "1c2y5YYBJUrNWn3IRYNb",
                "_score": 1,
                "fields": {
                    "_id": [
                        "1c2y5YYBJUrNWn3IRYNb"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "1s2y5YYBJUrNWn3ITIMM",
                "_score": 1,
                "fields": {
                    "_id": [
                        "1s2y5YYBJUrNWn3ITIMM"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "182y5YYBJUrNWn3IUIPe",
                "_score": 1,
                "fields": {
                    "_id": [
                        "182y5YYBJUrNWn3IUIPe"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "2M2z5YYBJUrNWn3IN4O4",
                "_score": 1,
                "fields": {
                    "_id": [
                        "2M2z5YYBJUrNWn3IN4O4"
                    ]
                }
            },
            {
                "_index": "test",
                "_id": "2c2z5YYBJUrNWn3IUoNm",
                "_score": 1
            },
            {
                "_index": "test",
                "_id": "2s2z5YYBJUrNWn3IVYOr",
                "_score": 1
            },
            {
                "_index": "test",
                "_id": "282z5YYBJUrNWn3IWYNq",
                "_score": 1
            },
            {
                "_index": "test",
                "_id": "3M2z5YYBJUrNWn3IW4P9",
                "_score": 1,
                "fields": {
                    "_id": [
                        "3M2z5YYBJUrNWn3IW4P9"
                    ]
                }
            }
```

Notice hits 7-9 without the `_id` field. If queried directly, these documents show the field though:
```
GET test/_search
{
  "_source": false,
  "fields": [
    "_id"
  ],
  "size": 10,
  "query": {
    "match": {
      "_id" : "282z5YYBJUrNWn3IWYNq"
    }
  }
}

--->

"hits": [
            {
                "_index": "test",
                "_id": "282z5YYBJUrNWn3IWYNq",
                "_score": 1,
                "fields": {
                    "_id": [
                        "282z5YYBJUrNWn3IWYNq"
                    ]
                }
            }
        ]
```

Strangely, also changing the "size" seems to change which docs have the `_id` in the `fields` response and which don't.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by howardhuanghua**
This PR is going to fix https://github.com/elastic/elasticsearch/issues/94515.
Copy fields values to avoid cache clear.

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/search/query/SearchQueryIT.java [hunk 1]
```diff
@@ -2079,4 +2079,21 @@ public void testIssueFuzzyInsideSpanMulti() {
...
+    public void testFetchIdFieldQuery() {
+        createIndex("test");
+        int docCount = randomIntBetween(10, 50);
+        for (int i=0; i<docCount; i++) {
+            client().prepareIndex("test").setSource("field", "foobarbaz").get();
+        }
+        ensureGreen();
+        refresh();
+
+        SearchResponse response = client().prepareSearch("test").addFetchField("_id").setSize(10).get();
```
Comment (cbuescher) [inline server/src/internalClusterTest/java/org/elasticsearch/search/query/SearchQueryIT.java:2092]: It might make sense to check all documents we indexed (docCount), not just top 10.

File: server/src/main/java/org/elasticsearch/common/document/DocumentField.java [hunk 2]
```diff
@@ -66,7 +66,12 @@ public DocumentField(String name, List<Object> values, List<Object> ignoredValue
 
     public DocumentField(String name, List<Object> values, List<Object> ignoredValues, List<LookupField> lookupFields) {
         this.name = Objects.requireNonNull(name, "name must not be null");
-        this.values = Objects.requireNonNull(values, "values must not be null");
+        if (values == null) {
+            throw new NullPointerException("values must not be null");
+        } else {
+            // copy to avoid field value cache clear
+            this.values = List.copyOf(values);
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/common/document/DocumentField.java:73]: I would prefer to do the value copying in `StoredValueFetcher#fetchValues()`  which is the one responsible for the "_id" field. That way we avoid copying other fields lists values that are not cleared with the cached field data in LeafStoredFieldsLookup.

File: server/src/internalClusterTest/java/org/elasticsearch/search/query/SearchQueryIT.java [hunk 3]
```diff
@@ -2079,4 +2079,21 @@ public void testIssueFuzzyInsideSpanMulti() {
         SearchResponse response = client().prepareSearch("test").setQuery(query).get();
         assertHitCount(response, 1);
     }
+
+    public void testFetchIdFieldQuery() {
+        createIndex("test");
+        int docCount = randomIntBetween(10, 50);
+        for (int i=0; i<docCount; i++) {
```
Comment (cbuescher) [inline server/src/internalClusterTest/java/org/elasticsearch/search/query/SearchQueryIT.java:2086]: nit: minor formatting which will eventually block the CI checks, run `./gradlew  :server:spotlessApply` to correct this here and in some other places.

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @howardhuanghua, nice catch and a great fix! I would only like to suggest copying the values in StoredValueFetcher itself rather than the place you put that operation now, only to have it be more specific for the "_id" stored fields case and related.

**Comment by howardhuanghua** [comment]
Hi @cbuescher , I have updated the PR based on your comment. Would you please help to check again? Thanks.

File: server/src/main/java/org/elasticsearch/index/mapper/StoredValueFetcher.java [hunk 4]
```diff
@@ -38,7 +38,12 @@ public void setNextReader(LeafReaderContext context) {
     @Override
     public List<Object> fetchValues(Source source, int doc, List<Object> ignoredValues) throws IOException {
         leafSearchLookup.setDocument(doc);
-        return leafSearchLookup.fields().get(fieldname).getValues();
+        List<Object> values = leafSearchLookup.fields().get(fieldname).getValues();
+        if (IdFieldMapper.NAME.equals(fieldname)) {
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/mapper/StoredValueFetcher.java:42]: I don't think we need to be that specific. StoredValueFetcher is only used in the IgnoredFieldMapper which probably also suffers from the cache clearing issue (maybe makes sense to add a test?), the LegacyTypeFieldMapper (from ES5) and otherwise only the IdFieldMapper and subtypes. Let's just return a List.copyOf here in all cases.
```suggestion
        return List.copyOf(values);
```

**Review by cbuescher — APPROVED** [review]
LGTM, thanks a lot for the changes. I left one small suggestion which would be nice to change still but I will already start running the tests to get this merged quickly.

**Comment by cbuescher** [comment]
@elasticsearchmachine test this please

File: server/src/main/java/org/elasticsearch/index/mapper/StoredValueFetcher.java [hunk 5]
```diff
@@ -38,7 +38,12 @@ public void setNextReader(LeafReaderContext context) {
     @Override
     public List<Object> fetchValues(Source source, int doc, List<Object> ignoredValues) throws IOException {
         leafSearchLookup.setDocument(doc);
-        return leafSearchLookup.fields().get(fieldname).getValues();
+        List<Object> values = leafSearchLookup.fields().get(fieldname).getValues();
+        return List.copyOf(values);
+            // copy _id field to avoid field value cache clear
+            values = List.copyOf(values);
+        }
+        return values;
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/mapper/StoredValueFetcher.java:46]: This broke a bit after accepting the last suggestion, sorry for that. Can you also add a null check to the values passed to List.copyOf(), otherwise I think e.g. in case of the ignore field this can potentially throw NPEs

Comment (howardhuanghua) [reply server/src/main/java/org/elasticsearch/index/mapper/StoredValueFetcher.java:46]: Yes, I am checking.

Comment (howardhuanghua) [reply server/src/main/java/org/elasticsearch/index/mapper/StoredValueFetcher.java]: @cbuescher Would you please help to check again? Thanks.
