### PR TITLE
ESQL: Make esql version required in REST requests

### LINKED ISSUE #107403: [CI]  MixedClusterEsqlSpecIT bwc tests fail against 8.12.2 and 8.11.4 versions with `unknown field [version]` error
### CI Link

https://gradle-enterprise.elastic.co/s/v2emima2rqcve

### Repro line

./gradlew ':x-pack:plugin:esql:qa:server:mixed-cluster:v8.11.4#javaRestTest' -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT" -Dtests.method="test {math.MvMedianRoundDown SYNC}" -Dtests.seed=66224250E1CAAABC -Dtests.bwc=true -Dtests.locale=ar-EG -Dtests.timezone=CNT -Druntime.java=21

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:44773], URI [/_query?pretty=true&error_trace=true], status line [HTTP/1.1 400 Bad Request]	
{	
  "error" : {	
    "root_cause" : [	
      {	
        "type" : "x_content_parse_exception",	
        "reason" : "[1:69] [esql/query] unknown field [version]",	
        "stack_trace" : "org.elasticsearch.ElasticsearchException$1: [1:69] [esql/query] unknown field [version]\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:670)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:598)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestResponse.build(RestResponse.java:186)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:134)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:112)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:416)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:543)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:316)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:453)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:549)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:426)\n\tat org.elasticsearch.transport.netty4@8.11.4/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.handlePipelinedRequest(Netty4HttpPipeliningHandler.java:128)\n\tat org.elasticsearch.transport.netty4@8.11.4/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:118)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.ch…	
      }	
    ],	
    "type" : "x_content_parse_exception",	
    "reason" : "[1:69] [esql/query] unknown field [version]",	
    "stack_trace" : "org.elasticsearch.xcontent.XContentParseException: [1:69] [esql/query] unknown field [version]\n\tat org.elasticsearch.xcontent@8.11.4/org.elasticsearch.xcontent.ObjectParser.lambda$errorOnUnknown$2(ObjectParser.java:105)\n\tat org.elasticsearch.xcontent@8.11.4/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:299)\n\tat org.elasticsearch.xcontent@8.11.4/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:259)\n\tat org.elasticsearch.xcontent@8.11.4/org.elasticsearch.xcontent.ObjectParser.apply(ObjectParser.java:382)\n\tat org.elasticsearch.xpack.esql.action.EsqlQueryRequest.fromXContent(EsqlQueryRequest.java:153)\n\tat org.elasticsearch.xpack.esql.action.RestEsqlQueryAction.prepareRequest(RestEsqlQueryAction.java:48)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:80)\n\tat org.elasticsearch.security@8.11.4/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:96)\n\tat org.elasticsearch.security@8.11.4/org.elasticsearch.xpack.security.rest.SecurityRestFilter.handleRequest(SecurityRestFilter.java:76)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:414)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:543)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:316)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:453)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:549)\n\tat org.elasticsearch.server@8.11.4/org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:426)\n\tat org.elasticsearch.transport.netty4@8.11.4/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.handlePipelinedRequest(Netty4HttpPipeliningHandler.java:128)\n\tat org.elasticsearch.transport.netty4@8.11.4/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:118)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)\n\tat io.netty.codec@4.1.94.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.transport@4.1.94.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHa…	
  },	
  "status" : 400	
}
```

### PR DESCRIPTION
**Pull request by alex-spies**
* Enable corresponding validation in EsqlQueryRequest.
* Add the ES|QL version to all requests to `/_query` in integration tests.

For mixed cluster tests, impersonates a language client with version 8.13, the only exception in which we do not require the version to be sent (based on https://github.com/elastic/elasticsearch/pull/107497 by @nik9000 ).

Fix https://github.com/elastic/elasticsearch/issues/107403
Main part of https://github.com/elastic/elasticsearch/issues/104890

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequest.java [hunk 1]
```diff
@@ -69,9 +69,7 @@ public EsqlQueryRequest(StreamInput in) throws IOException {
     public ActionRequestValidationException validate() {
         ActionRequestValidationException validationException = null;
         if (Strings.hasText(esqlVersion) == false) {
-            // TODO: make this required
-            // "https://github.com/elastic/elasticsearch/issues/104890"
-            // validationException = addValidationError(invalidVersion("is required"), validationException);
+            validationException = addValidationError(invalidVersion("is required"), validationException);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequest.java:72]: I want to revert this before merging, so that the actual - breaking - API change becomes a single, small PR that can be easily reverted.

File: x-pack/plugin/esql/qa/server/single-node/src/yamlRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/AbstractEsqlClientYamlIT.java [hunk 2]
```diff
@@ -44,4 +50,40 @@ private void assertRequestBreakerEmpty() throws Exception {
          */
         EsqlSpecTestCase.assertRequestBreakerEmpty();
     }
+
+    public static Iterable<Object[]> updateEsqlQueryDoSections(Iterable<Object[]> parameters, Function<DoSection, ExecutableSection> modify)
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/single-node/src/yamlRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/AbstractEsqlClientYamlIT.java:54]: Refactored `x-pack/plugin/esql/qa/server/single-node/src/yamlRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlClientYamlAsyncIT.java` a little bit, but failed moving this into a place to be used by multiple yaml tests from :/

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java [hunk 3]
```diff
@@ -179,6 +180,9 @@ public RequestObjectBuilder pragmas(Settings pragmas) throws IOException {
 
         public RequestObjectBuilder build() throws IOException {
             if (isBuilt == false) {
+                if (version != null) {
+                    builder.field("version", version);
+                }
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/RestEsqlTestCase.java:185]: Small improvement stolen from @nik9000

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequestTests.java [hunk 4]
```diff
@@ -238,7 +238,6 @@ public void testSnapshotVersionIsOnlyValidOnSnapshot() throws IOException {
         assertThat(request.validate().getMessage(), containsString(errorOnNonSnapshotBuilds));
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/104890")
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequestTests.java:241]: Needs reverting as well before this gets merged.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequest.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequest.java:72]: Nevermind, discussed with @nik9000 : we can still revert just this in case something goes wrong.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequestTests.java (hunk 4 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequestTests.java:241]: We're going to keep this one and just enable the validation.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequest.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequest.java:72]: We're going to keep this in to save the few hours of build time. If something goes wrong we can back out just this line if we have to.

**Review by nik9000 — APPROVED** [review]
