### PR TITLE
ES|QL: fix LIMIT pushdown past MV_EXPAND

### LINKED ISSUE #102061: ES|QL: limit + sort + mv_expand is not planned correctly (unknown physical plan node [OrderExec])
Planning of queries with LIMIT + SORT + MV_EXPAND fails with `IllegalArgumentException`

```
row a = 1 | limit 1 | sort a | mv_expand a
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "esql_illegal_argument_exception",
                "reason": "unknown physical plan node [OrderExec]"
            }
        ],
        "type": "esql_illegal_argument_exception",
        "reason": "unknown physical plan node [OrderExec]"
    },
    "status": 500
```

A similar problem was already [reported](https://github.com/elastic/elasticsearch/issues/99971) and fixed, but it seems the fix is not complete.

### LINKED ISSUE #102084: ESQL: Planning of  MV_EXPAND with false condition aborted because rule execution limit reached
```
row  a = 1, b = -15 | where b > 3   | mv_expand b
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "rule_execution_exception",
                "reason": "Rule execution limit [100] reached"
            }
        ],
        "type": "rule_execution_exception",
        "reason": "Rule execution limit [100] reached"
    },
    "status": 500
}
```

The problem seems to be the pushdown of LIMIT:

```
[2023-11-13T15:34:04,962][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$DuplicateLimitAfterMvExpand applied
Limit[500[INTEGER]]                 = Limit[500[INTEGER]]
\_MvExpand[b{r}#332,b{r}#337]       = \_MvExpand[b{r}#332,b{r}#337]
  \_LocalRelation[[b{r}#332],EMPTY] !   \_Limit[500[INTEGER]]
                                    !     \_LocalRelation[[b{r}#332],EMPTY]

...

[2023-11-13T15:34:04,962][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$PropagateEmptyRelation applied
Limit[500[INTEGER]]                   = Limit[500[INTEGER]]
\_MvExpand[b{r}#332,b{r}#337]         = \_MvExpand[b{r}#332,b{r}#337]
  \_Limit[500[INTEGER]]               !   \_LocalRelation[[b{r}#332],EMPTY]
    \_LocalRelation[[b{r}#332],EMPTY] ! 
                                     

...

[2023-11-13T15:34:04,964][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$DuplicateLimitAfterMvExpand applied
Limit[500[INTEGER]]                 = Limit[500[INTEGER]]
\_MvExpand[b{r}#332,b{r}#337]       = \_MvExpand[b{r}#332,b{r}#337]
  \_LocalRelation[[b{r}#332],EMPTY] !   \_Limit[500[INTEGER]]
                                    !     \_LocalRelation[[b{r}#332],EMPTY]
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/102084
Fixes https://github.com/elastic/elasticsearch/issues/102061

Allow proper pushdown of `LIMIT x` command past `MV_EXPAND`, using a two-step strategy:

- first push down the LIMIT x and keep the original limit information inside MV_EXPAND itself, ie. transform `MV_EXPAND | LIMIT x` into `LIMIT x | MV_EXPAND(with limit x)`
- (do the normal planning, with batch loops that can trigger the above operation again if there are other LIMIT or MV_EXPAND commands)
- only at the end, at mapping time, see if MV_EXPAND has an inner limit, and in case add the corresponding `LimitExec`

All this happens only at logical level, so that physical plan and operators can ignore it (mv_expand operator implementation is unbounded, this PR doesn't change it).
The inner limit is resolved locally:
- the mapper replaces inner limit with a normal `LimitExec`, so the physical plan doesn't have it
- in the `physical plan -> logical plan fragment` translation for data node routing, MV_EXPAND is created without inner limit

 so there is no need to serialize it (ie. no impact on bwc problems, no changes to TransportVersions)

---

Q: Why adding a LIMIT to MV_EXPAND and not trying to just reason on the plan? LIMIT is not strictly related to MV_EXPAND, so it seems out of context there.
A: For many reasons:
- because it avoids infinite loops: `MV_EXPAND | LIMIT` -> `LIMIT | MV_EXPAND | LIMIT` -> `... | MV_EXPAND | LIMIT`
- because reasoning on the whole plan is much more complicated and error prone than reasoning on the single MV_EXPAND

(it was previously https://github.com/elastic/elasticsearch/pull/102545)

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by craigtaverner — APPROVED** [review]
Seems like a good solution, but I did have some comments.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java [hunk 1]
```diff
@@ -33,6 +33,14 @@ public LogicalPlan rule(Limit limit) {
         } else if (limit.child() instanceof UnaryPlan unary) {
             if (unary instanceof Eval || unary instanceof Project || unary instanceof RegexExtract || unary instanceof Enrich) {
                 return unary.replaceChild(limit.replaceChild(unary.child()));
+            } else if (unary instanceof MvExpand mvx) {
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java:36]: Oh yeah, good point, I forgot about it...
We have another rule, called `DuplicateLimitAfterMvExpand`, that does exactly what I describe above:

[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java:36]: There is another rule, [AddDefaultTopN](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/AddDefaultTopN.java), that is intrinsically wrong (it adds an arbitrary limit at the beginning of the query) and that IMHO should be removed as well, but I'm not sure this fix is enough to do it, maybe the problems it tries to solve are not only related to MV_EXPAND.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/DuplicateLimitAfterMvExpand.java [hunk 2]
```diff
@@ -1,108 +0,0 @@
...
-    protected LogicalPlan rule(Limit limit) {
-        var child = limit.child();
-        var shouldSkip = child instanceof Eval
-            || child instanceof Project
-            || child instanceof RegexExtract
-            || child instanceof Enrich
-            || child instanceof Limit;
-
-        if (shouldSkip == false && child instanceof UnaryPlan unary) {
-            MvExpand mvExpand = descendantMvExpand(unary);
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/DuplicateLimitAfterMvExpand.java:36]: This rule seems to cover more cases than simply LIMIT->MvExpand, which the other rule now covers. Presumably the iterative application of the other rules will cover this scenario already, so this removal is of no consequence. And presumably test coverage will pick this up if that is not the case.

**Comment by costin** [comment]
The other PRs for this issue (#103080 and  #103582) contain multiple tests - even if this PR doesn't fix them, please add them here and disable them to get a better understanding of the limitations.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 3]
```diff
@@ -441,7 +441,12 @@ public enum Cap {
         /**
          * Support simplified syntax for named parameters for field and function names.
          */
-        NAMED_PARAMETER_FOR_FIELD_AND_FUNCTION_NAMES_SIMPLIFIED_SYNTAX(Build.current().isSnapshot());
+        NAMED_PARAMETER_FOR_FIELD_AND_FUNCTION_NAMES_SIMPLIFIED_SYNTAX(Build.current().isSnapshot()),
+
+        /**
+         * Fix pushdown of LIMIT past MV_EXPAND
+         */
+        FIX_MV_EXPAND_LIMIT_PUSHDOWN;
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:449]: Nit: Unless this PR fixes all issues around limit and mvExpand, add a PARTIAL_ prefix or describe what the PR does - ADD_LIMIT_INSIDE_MV_EXPAND.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java [hunk 4]
```diff
@@ -107,19 +115,21 @@ public List<Attribute> output() {
...
+        return Objects.hash(super.hashCode(), target, expanded, limit);
     }
 
     @Override
     public boolean equals(Object obj) {
         if (false == super.equals(obj)) {
             return false;
         }
-        return Objects.equals(target, ((MvExpand) obj).target) && Objects.equals(expanded, ((MvExpand) obj).expanded);
+        return Objects.equals(target, ((MvExpand) obj).target)
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java:131]: Extract the MvExpand casting inside equals.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java [hunk 5]
```diff
@@ -27,21 +27,24 @@ public class MvExpand extends UnaryPlan {
 
     private final NamedExpression target;
     private final Attribute expanded;
+    private final Integer limit;
 
     private List<Attribute> output;
 
-    public MvExpand(Source source, LogicalPlan child, NamedExpression target, Attribute expanded) {
+    public MvExpand(Source source, LogicalPlan child, NamedExpression target, Attribute expanded, Integer limit) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java:34]: Since the limit is "artificial" and not serialized, consider keeping the old constructor which delegates to the extended one and just passes limit as null.
Makes the change less disruptive especially in most cases looks like null is passed anyway.

**Review by costin — APPROVED** [review]
An inner limit is going to create its own problems however the original issue hasn't been addressed in over a year (I felt short) and this PR looks to improve the situation.

See my other comments on incorporating the tests (disabled them if they fail) from the other PRs .

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:449]: I think it fully addresses the LIMIT pushdown problem, but I think the name you are suggesting is more descriptive, I'll change it anyway

**Comment by luigidellaquila** [comment]
> The other PRs for this issue (https://github.com/elastic/elasticsearch/pull/103080 and https://github.com/elastic/elasticsearch/pull/103582) contain multiple tests - even if this PR doesn't fix them, please add them here and disable them to get a better understanding of the limitations.

Good point, I'm adding some of the tests from these two PRs.
Some other tests don't really make sense in this context, because they tested solutions that were specific of those PRs, in particular the pushdown of MV_EXPAND past SORT (that unfortunately is not possible in all cases).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/Mapper.java [hunk 6]
```diff
@@ -228,7 +231,13 @@ private PhysicalPlan map(UnaryPlan p, PhysicalPlan child) {
         }
 
         if (p instanceof MvExpand mvExpand) {
-            return new MvExpandExec(mvExpand.source(), map(mvExpand.child()), mvExpand.target(), mvExpand.expanded());
+            MvExpandExec result = new MvExpandExec(mvExpand.source(), map(mvExpand.child()), mvExpand.target(), mvExpand.expanded());
+            if (mvExpand.limit() != null && mvExpand.limit() >= 0) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/Mapper.java:235]: Curious about the `>= 0` bit. Is it needed, do we do it anywhere else?

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java [hunk 7]
```diff
@@ -33,6 +33,21 @@ public LogicalPlan rule(Limit limit) {
...
+                // (we also have to preserve the LIMIT afterwards)
+                //
+                // To avoid infinite loops, ie.
+                // | MV_EXPAND | LIMIT -> | LIMIT | MV_EXPAND | LIMIT -> ... | MV_EXPAND | LIMIT
+                // we add an inner limit to MvExpand and just push down the existing limit, ie.
+                // | MV_EXPAND | LIMIT N -> | LIMIT N | MV_EXPAND (with limit N)
+                var limitSource = limit.limit();
+                var limitVal = (int) limitSource.fold();
+                Integer mvxLimit = mvx.limit();
+                if (mvxLimit == null || mvxLimit < 0 || mvxLimit > limitVal) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java:47]: same here: is the negative check needed?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java [hunk 8]
```diff
@@ -51,6 +58,7 @@ public void writeTo(StreamOutput out) throws IOException {
         out.writeNamedWriteable(child());
         out.writeNamedWriteable(target());
         out.writeNamedWriteable(expanded());
+        assert limit == null;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java:61]: I guess this never triggers b/c there's currently always going to be a limit below MV_EXPAND, so it'll never be serialized in the fragment, right?

**Review by bpintea — COMMENTED** [review]
I

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java (hunk 8 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java:61]: It never happens because we do the serialization after the physical planning, and the mapper will resolve an `MvExpand(limit=n)` into a `LimitExec(n) + MvExpandExec`; after physical planning, even if that fragment remains the same, it will be re-translated to `Limit(n) + MvExpand` and serialized.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/Mapper.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/Mapper.java:235]: I'm pretty sure we don't support a LIMIT -1... probably I should remove that check.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java (hunk 8 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java:61]: I think I get it.

> To clarify, we don't need to serialize it now, but we could.

The fragment will contain the logical plan, the "original" one. So theoretically, we might need to serialise an `MvExpand` with a non-null limit. In which case the assertion would trip. But `MvExpand`'s limit would be non-`null` only if a limit was pushed down over it and since limit is a pipeline breaker, the plan will be latest broken down at the limit, so MvExpand will, in current form, never make it onto the nodes. Right?
The translation to physical and the mapping wouldn't then influence this, I guess.

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MvExpand.java:61]: > and since limit is a pipeline breaker, the plan will be latest broken down at the limit, so MvExpand will, in current form, never make it onto the nodes. Right?

Correct, and it's enough to guarantee that limited MV_EXPAND will never make it into the data nodes.

> The translation to physical and the mapping wouldn't then influence this, I guess.

I think you're right

**Review by bpintea — APPROVED** [review]
Lgtm. I guess at some point we might want to review this, if we add multiple reducers, no-limit plans or similar, but now it's a good fix.

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine update branch
