### PR TITLE
Fix leakage of log-level in LoggerTests

### LINKED ISSUE #106250: Fix leaking log-level set on root logger in LoggerTests
### CI Link

https://gradle-enterprise.elastic.co/s/ssqi5r5klvhsm

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests*" -Druntime.java=21  -Dtests.es.logger.level=DEBUG

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```org.elasticsearch.snapshots.SnapshotResiliencyTests > testIllegalArgumentExceptionLogging FAILED
    java.lang.AssertionError: expected to see INFO log but did not
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([782F1BB9840950FE:32EBB1FE53CD0BB8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.elasticsearch.test.MockLogAppender$SeenEventExpectation.assertMatched(MockLogAppender.java:127)
```

The following 4 tests started failing yesterday in `SnapshotResiliencyTests` due to an incorrectly set log-level.  
```
Tests with failures:
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testIndexNotFoundExceptionLogging
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testFullSnapshotUnassignedShards
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testIllegalArgumentExceptionLogging
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotNameAlreadyInUseExceptionLogging
 ```

 It seems that in this [PR](https://github.com/elastic/elasticsearch/pull/105020) we updated the log-level of the[ root logger](https://github.com/elastic/elasticsearch/blob/main/server/src/test/java/org/elasticsearch/common/logging/LoggersTests.java#L88) as part of the tests, so if it happens that the `SnapshotResiliencyTests` are executed **after** the `LoggersTests`, the log-level for the `SnapshotsService` logger will be set to debug causing the failures above.  

We should probably reset the log-level after the tests, as we do in `InternalEngineTests#testMergeThreadLogging`  for example

### PR DESCRIPTION
**Pull request by mosche**
Fix leakage of log-level in LoggerTests

closes #106250

### CODE REVIEW

File: qa/restricted-loggers/src/test/java/org/elasticsearch/common/logging/LoggersTests.java [hunk 1]
```diff
@@ -69,36 +69,48 @@ public void testSetLevelWithRestrictions() {
         assertThat(Loggers.RESTRICTED_LOGGERS, hasSize(greaterThan(0)));
 
         for (String restricted : Loggers.RESTRICTED_LOGGERS) {
+            Level rootLevel = LogManager.getRootLogger().getLevel();
 
             // 'org.apache.http' is an example of a restricted logger,
             // a restricted component logger would be `org.apache.http.client.HttpClient` for instance,
             // and the parent logger is `org.apache`.
             Logger restrictedLogger = LogManager.getLogger(restricted);
+            Level restrictedLoggerLevel = restrictedLogger.getLevel();
```
Comment (rjernst) [inline qa/restricted-loggers/src/test/java/org/elasticsearch/common/logging/LoggersTests.java:78]: Does getLevel return null if the effective level is inherited? Otherwise it seems we might force the current parent log level to be realized on this logger when restoring it.

**Review by rjernst — COMMENTED** [review]
One question

File: qa/restricted-loggers/src/test/java/org/elasticsearch/common/logging/LoggersTests.java (hunk 1 above)
Comment (mosche) [reply qa/restricted-loggers/src/test/java/org/elasticsearch/common/logging/LoggersTests.java]: Good point, it's always the effective log level. 
Also, when setting root to DEBUG, all the restricted loggers will be configured with level INFO. So there's a lot more to do to revert any possible changes. I've added a small util `TestLoggers.runWithLoggersRestored` to do that.

File: server/src/test/java/org/elasticsearch/common/logging/LoggersTests.java [hunk 2]
```diff
@@ -58,36 +58,37 @@ public void testCheckRestrictedLoggers() {
 
     public void testSetLevelWithRestrictions() {
```
Comment (pgomulka) [inline server/src/test/java/org/elasticsearch/common/logging/LoggersTests.java:59]: why do we have the same method in both restricted-loggers and in server?

**Review by pgomulka — APPROVED** [review]
LGTM,
I also followed up with https://github.com/elastic/elasticsearch/pull/106312 to always set root level INFO in afterclass

File: server/src/test/java/org/elasticsearch/common/logging/LoggersTests.java (hunk 2 above)
Comment (mosche) [reply server/src/test/java/org/elasticsearch/common/logging/LoggersTests.java:59]: there's a subtile difference between the two, the one in server tests an internal interface where restricted loggers are provided by the test. this is because we have the trace network flag `insecure_network_trace_enabled` enabled for server tests, which then disables restricted loggers.

this test is mostly there to have a test close to the sources and get immediate feedback.

the other one runs the same test, but with the restricted loggers defined for production code.
