### PR TITLE
IndicesClusterStateService should replace an init. replica with an init. primary with the same aId

### LINKED ISSUE #32308: [ci] IndicesClusterStateServiceRandomUpdatesTests.testRandomClusterStateUpdates
Doesn't reproduce. Has occurred 6 times in the last 90 days

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2576/console

[build-2576.txt](https://github.com/elastic/elasticsearch/files/2221493/build-2576.txt)

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=BDB828B6AFCB1CB3 \
  -Dtests.class=org.elasticsearch.indices.cluster.IndicesClusterStateServiceRandomUpdatesTests \
  -Dtests.method="testRandomClusterStateUpdates" \
  -Dtests.security.manager=true \
  -Dtests.locale=hi-IN \
  -Dtests.timezone=Canada/Mountain
```

```
FAILURE 0.16s J0 | IndicesClusterStateServiceRandomUpdatesTests.testRandomClusterStateUpdates <<< FAILURES!                                                                                  
   > Throwable #1: java.lang.AssertionError: a replica can only be promoted when active. current: [index_ytqkcgwvfrlcilx][0], node[node_002], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=96qpiMtlQ_ODQQrpk67g6g], unassigned_info[[reason=INDEX_CREATED], at[2018-07-23T23:45:43.608Z], delayed=false, allocation_status[no_attempt]] new: [index_ytqkcgwvfrlcilx][0], node[node_002], [P], recovery_source[existing recovery], s[INITIALIZING], a[id=96qpiMtlQ_ODQQrpk67g6g], unassigned_info[[reason=ALLOCATION_FAILED], at[2018-07-23T23:45:43.639Z], failed_attempts[1], delayed=false, details[failed shard on node [node_003]: fake shard failure, failure Exception[null]], allocation_status[no_attempt]]                                                   
   >    at __randomizedtesting.SeedInfo.seed([BDB828B6AFCB1CB3:C53F2165F0F0CAFA]:0)           
   >    at org.elasticsearch.indices.cluster.AbstractIndicesClusterStateServiceTestCase$MockIndexShard.updateShardState(AbstractIndicesClusterStateServiceTestCase.java:365)                 
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateShard(IndicesClusterStateService.java:582)                                                                     
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:529)                                                            
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:230)                                                               
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateServiceRandomUpdatesTests.testRandomClusterStateUpdates(IndicesClusterStateServiceRandomUpdatesTests.java:127)               
   >    at java.lang.Thread.run(Thread.java:748) 
```

### PR DESCRIPTION
**Pull request by bleskes**
In rare cases it is possible that a nodes gets an instruction to replace a replica
shard that's in `POST_RECOVERY` with a new initializing primary with the same allocation id.
This can happen by batching cluster states that include the starting of the replica, with
closing of the indices, opening it up again and allocating the primary shard to the node in
question. The node should then clean it's initializing replica and replace it with a new
initializing primary.

I'm not sure whether the test I added really adds enough value as existing tests found this. The main reason I added is to allow for simpler reproduction and to double check I fixed it. I'm open to discuss if we should keep.

Closes #32308

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java [hunk 1]
```diff
@@ -420,6 +420,12 @@ private void removeShards(final ClusterState state) {
                     // state may result in a new shard being initialized while having the same allocation id as the currently started shard.
                     logger.debug("{} removing shard (not active, current {}, new {})", shardId, currentRoutingEntry, newShardRouting);
                     indexService.removeShard(shardId.id(), "removing shard (stale copy)");
+                } else if (newShardRouting.primary() && currentRoutingEntry.primary() == false && newShardRouting.initializing()) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java]: I think we're over-special-casing this, while also possibly missing some more murky cases. May I suggest the following alternative instead, which handles both this case as well as the previous (odd) one:

```
diff --git a/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java b/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
index e6a86d47f55..42a88383937 100644
--- a/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
+++ b/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
@@ -219,10 +219,10 @@ public class IndicesClusterStateService extends AbstractLifecycleComponent imple
 
         removeUnallocatedIndices(event); // also removes shards of removed indices
 
-        failMissingShards(state);
-
         removeShards(state);   // removes any local shards that doesn't match what the master expects
 
+        failMissingShards(state);
+
         updateIndices(event); // can also fail shards, but these are then guaranteed to be in failedShardsCache
 
         createIndices(state);
@@ -414,17 +414,12 @@ public class IndicesClusterStateService extends AbstractLifecycleComponent imple
                     logger.debug("{} removing shard (stale allocation id, stale {}, new {})", shardId,
                         currentRoutingEntry, newShardRouting);
                     indexService.removeShard(shardId.id(), "removing shard (stale copy)");
-                } else if (newShardRouting.initializing() && currentRoutingEntry.active()) {
+                } else if (newShardRouting.primary() &&
+                    state.metaData().index(shardId.getIndex()).primaryTerm(shardId.id()) != shard.getPrimaryTerm()) {
                     // this can happen if the node was isolated/gc-ed, rejoins the cluster and a new shard with the same allocation id
                     // is assigned to it. Batch cluster state processing or if shard fetching completes before the node gets a new cluster
                     // state may result in a new shard being initialized while having the same allocation id as the currently started shard.
-                    logger.debug("{} removing shard (not active, current {}, new {})", shardId, currentRoutingEntry, newShardRouting);
-                    indexService.removeShard(shardId.id(), "removing shard (stale copy)");
-                } else if (newShardRouting.primary() && currentRoutingEntry.primary() == false && newShardRouting.initializing()) {
-                    assert currentRoutingEntry.initializing() : currentRoutingEntry; // see above if clause
-                    // this can happen when cluster state batching batches activation of the shard, closing an index, reopening it
-                    // and assigning an initializing primary to this node
-                    logger.debug("{} removing shard (not active, current {}, new {})", shardId, currentRoutingEntry, newShardRouting);
+                    logger.debug("{} removing shard (stale primary term)", shardId);
                     indexService.removeShard(shardId.id(), "removing shard (stale copy)");
                 }
             }
@@ -728,6 +723,11 @@ public class IndicesClusterStateService extends AbstractLifecycleComponent imple
          */
         ShardRouting routingEntry();
 
+        /**
+         * Returns the current primary term of this shard
+         */
+        long getPrimaryTerm();
+
         /**
          * Returns the latest internal shard state.
          */
diff --git a/server/src/test/java/org/elasticsearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java b/server/src/test/java/org/elasticsearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
index 5e9ba653d40..bfcca1946a6 100644
--- a/server/src/test/java/org/elasticsearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
+++ b/server/src/test/java/org/elasticsearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
@@ -383,6 +383,11 @@ public abstract class AbstractIndicesClusterStateServiceTestCase extends ESTestC
             return shardRouting;
         }
 
+        @Override
+        public long getPrimaryTerm() {
+            return term;
+        }
+
         @Override
         public IndexShardState state() {
             return null;
```

**Review by ywelsch — COMMENTED** [review]
I've suggested an (imo simpler) alternative.

File: server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java (hunk 1 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java]: After discussion, we agreed this is not quite right. We decided to go with the initial condition proposed here.

File: server/src/test/java/org/elasticsearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java [hunk 2]
```diff
@@ -74,6 +74,10 @@ public void injectRandomFailures() {
         enableRandomFailures = randomBoolean();
     }
 
+    protected void disalbeRandomFailures() {
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java]: spelling

**Review by ywelsch — APPROVED** [review]
My previous suggestion was too good to be true. The condition you've proposed is the best I can think of right now until we distinguish between allocation ids and shard copy ids. I also think it's ok to keep the test, it's relatively short and succinctly documents an edge case.

**Comment by bleskes** [comment]
Thx @ywelsch . I tend towards pushing this to 6.3 too. Do you agree?

**Comment by ywelsch** [comment]
yes
