### PR TITLE
[ML] Fix Transform upgrade test

### LINKED ISSUE #132892: TransformSurvivesUpgradeIT test testTransformRollingUpgrade failing
TransformSurvivesUpgradeIT testTransformRollingUpgrade failing

**Build Scans:**
- [Failed CI Run](https://gradle-enterprise.elastic.co/s/oqbiltitcbno4/tests/:x-pack:qa:rolling-upgrade:v9.2.0%23oldClusterTest/org.elasticsearch.upgrades.TransformSurvivesUpgradeIT/testTransformRollingUpgrade)

**Reproduction Line:**
```

./gradlew ":x-pack:qa:rolling-upgrade:v9.2.0#oldClusterTest" -Dtests.class="org.elasticsearch.upgrades.TransformSurvivesUpgradeIT" -Dtests.method="testTransformRollingUpgrade" -Dtests.seed=8D90BC8B1599DEA3 -Dtests.bwc=true -Dtests.locale=en-UM -Dtests.timezone=Africa/Maputo -Druntime.java=24
```

**Failure Message:**
```
java.lang.AssertionError:
Expected: <5>  
but: was <5L>
```

**Note:**
This issue was created from stale `AwaitsFix` test. See [#132306](https://github.com/elastic/elasticsearch/pull/132306) for more details.

### PR DESCRIPTION
**Pull request by davidkyle**
The test failed comparing an int to a long 

Closes https://github.com/elastic/elasticsearch/issues/132892

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpgradeTransformsAction.java [hunk 1]
```diff
@@ -107,7 +106,7 @@ protected void masterOperation(Task ignoredTask, Request request, ClusterState s
         }
 
         // do not allow in mixed clusters
-        if (TransportVersionUtils.isMinTransportVersionSameAsCurrent(state) == false) {
+        if (state.nodes().isMixedVersionCluster()) {
```
Comment (davidkyle) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpgradeTransformsAction.java:109]: The upgrade test failed because the original check for a mixed cluster `isMinTransportVersionSameAsCurrent` depends on the order in which the nodes are upgraded. If the master node this code runs on has not been upgraded yet the test will pass.

**Review by prwhelan — APPROVED** [review]

File: x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/TransformSurvivesUpgradeIT.java [hunk 2]
```diff
@@ -236,10 +237,12 @@ private void verifyUpgradeFailsIfMixedCluster() {
...
-        final Request upgradeTransformRequest = new Request("POST", getTransformEndpoint() + "_upgrade");
-
-        Exception ex = expectThrows(Exception.class, () -> client().performRequest(upgradeTransformRequest));
-        assertThat(ex.getMessage(), containsString("All nodes must be the same version"));
+        var oldestVersion = Version.fromString(UPGRADE_FROM_VERSION);
+        if (oldestVersion.onOrAfter(Version.V_9_2_0)) {
+            final Request upgradeTransformRequest = new Request("POST", getTransformEndpoint() + "_upgrade");
+            Exception ex = expectThrows(Exception.class, () -> client().performRequest(upgradeTransformRequest));
+            assertThat(ex.getMessage(), containsString("Cannot upgrade transforms while cluster upgrade is in progress"));
+        }
```
Comment (DonalEvans) [inline x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/TransformSurvivesUpgradeIT.java:245]: Will this change cause the method to be a no-op in most cases? Is there some way to preserve the original intent of the method (confirming that upgrading a transform fails if the cluster is mixed version) while accounting for the different behaviour when the oldest version is 9.2?

Comment (davidkyle) [reply x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/TransformSurvivesUpgradeIT.java:245]: Yes this test will become a no-op for all previous versions but going forward as new versions are released the test will be run. The problem is that older versions do not reliably test if they are in a mixed cluster. I cannot fix that  check in previous versions but this change allows me to unmute the test, some coverage is better than none

**Comment by davidkyle** [comment]
The upgrade tests from 8.19.5 are failing because the transform upgrade code is fighting it out with the automatic system index upgrader. 

First the system index migrator moves  `.transform-internal-007`  to `.transform-internal-007-reindexed-for-10`
```
[2025-10-03T10:31:34,304][INFO ][o.e.s.t.SystemIndexMigrator] [v8.19.5-0] preparing to migrate old index [.transform-internal-007] from feature [transform] to new index [.transform-internal-007-reindexed-for-10]
[2025-10-03T10:31:34,305][INFO ][o.e.s.t.SystemIndexMigrator] [v8.19.5-0] migrating index [.transform-internal-007] from feature [transform] to new index [.transform-internal-007-reindexed-for-10]
[2025-10-03T10:31:34,305][INFO ][o.e.s.t.SystemIndexMigrator] [v8.19.5-0] creating new system index [.transform-internal-007-reindexed-for-10] from feature [transform]
[2025-10-03T10:31:34,312][INFO ][o.e.c.m.MetadataCreateIndexService] [v8.19.5-0] creating index [.transform-internal-007-reindexed-for-10] in project [default], cause [migrate-system-index], templates [], shards [1]/[1]
[2025-10-03T10:31:34,386][INFO ][o.e.c.m.MetadataIndexStateService] [v8.19.5-0] adding [index.blocks.write] block to indices [[.transform-internal-007/_WTe27ThRGS_FRhiiZKK3A]]
[2025-10-03T10:31:34,450][INFO ][o.e.c.m.MetadataIndexStateService] [v8.19.5-0] completed adding [index.blocks.write] block to indices [.transform-internal-007]
[2025-10-03T10:31:34,540][INFO ][o.e.c.m.MetadataDeleteIndexService] [v8.19.5-0] [.transform-internal-007/_WTe27ThRGS_FRhiiZKK3A] deleting index
[2025-10-03T10:31:34,586][INFO ][o.e.s.t.SystemIndexMigrator] [v8.19.5-0] Successfully migrated old index [.transform-internal-007] to new index [.transform-internal-007-reindexed-for-10] from feature [transform]
```

Then `POST /_transform/_upgrade` is called the final act of which is to delete old indices and because it does not recognise `.transform-internal-007-reindexed-for-10` that is deleted too. 

```
[2025-10-03T10:31:40,876][INFO ][o.e.x.t.a.TransportUpgradeTransformsAction] [v8.19.5-0] [mixed-complex-transform] Updated transform [NONE]
[2025-10-03T10:31:40,878][INFO ][o.e.c.m.MetadataDeleteIndexService] [v8.19.5-0] [.transform-internal-007-reindexed-for-10/m6txlkEcTjCPy1jRR3Rk_A] deleting index
/* The new system index has just been deleted !! */
[2025-10-03T10:31:40,918][INFO ][o.e.x.t.a.TransportUpgradeTransformsAction] [v8.19.5-0] Successfully upgraded all transforms, (updated: [0], no action [7])
```

**Comment by davidkyle** [comment]
@prwhelan I've added https://github.com/elastic/elasticsearch/pull/132995/commits/84329e405a2444a4aeb9187a7e7c9264d80fd0c1 to address the rolling upgrade failure described above. Please can you take another look

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpgradeTransformsAction.java (hunk 1 above)
Comment (prwhelan) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpgradeTransformsAction.java:109]: Nice find

**Review by prwhelan — APPROVED** [review]

**Comment by davidkyle** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/136373)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/136374)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/136375)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/136376)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/136377)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
