### PR TITLE
[ML] Wait for the worker service to shutdown before closing task processor

### LINKED ISSUE #117563: [ML] Inference fails with Lucene AlreadyClosedException "this Analyzer is closed"
### Elasticsearch Version

8.16

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

Inference on an NLP model fails during tokenization with `org.apache.lucene.store.AlreadyClosedException: this Analyzer is closed`

### Steps to Reproduce

There is no easy reproduction, the error may be related to an upgrade or the ml node shutting down.

### Logs (if relevant)

```
org.apache.lucene.store.AlreadyClosedException: this Analyzer is closed
	at org.apache.lucene.core@10.0.0/org.apache.lucene.analysis.Analyzer$ReuseStrategy.getStoredValue(Analyzer.java:449)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.analysis.Analyzer$1.getReusableComponents(Analyzer.java:474)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:184)
	at org.elasticsearch.ml@9.0.0/org.elasticsearch.xpack.ml.inference.nlp.tokenizers.XLMRobertaTokenizer.innerTokenize(XLMRobertaTokenizer.java:178)
	at org.elasticsearch.ml@9.0.0/org.elasticsearch.xpack.ml.inference.nlp.tokenizers.NlpTokenizer.tokenize(NlpTokenizer.java:84)
	at org.elasticsearch.ml@9.0.0/org.elasticsearch.xpack.ml.inference.nlp.tokenizers.XLMRobertaTokenizer.lambda$requestBuilder$0(XLMRobertaTokenizer.java:137)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:289)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
	at org.elasticsearch.ml@9.0.0/org.elasticsearch.xpack.ml.inference.nlp.tokenizers.XLMRobertaTokenizer.lambda$requestBuilder$1(XLMRobertaTokenizer.java:138)
	at org.elasticsearch.ml@9.0.0/org.elasticsearch.xpack.ml.inference.deployment.InferencePyTorchAction.doRun(InferencePyTorchAction.java:132)
```

### PR DESCRIPTION
**Pull request by davidkyle**
The error in #117563 shows that the tokenizer was closed while the worker queue was still executing pending inference requests. The problem is that the `forcefullyStopProcess()` function was calling `shutdown` instead of `shutdownNow`, the first completes queued up work and the second exits once the current item is processed. The code still needs to wait for that item to be processed so `awaitTermination` is used before closing the tokenizer.

#117563 highlights another issue,  multiple calls to `stop()` should be idempotent. Previously there was a separate code path for the already shutting down case but reviewing the code is it fine to stop the worker service multiple times and wait for termination with a timeout. 

Closes #117563

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java [hunk 1]
```diff
@@ -631,12 +631,12 @@ synchronized void forcefullyStopProcess() {
             logger.debug(() -> format("[%s] Forcefully stopping process", task.getDeploymentId()));
             prepareInternalStateForShutdown();
 
-            if (priorityProcessWorker.isShutdown()) {
-                // most likely there was a crash or exception that caused the
-                // thread to stop. Notify any waiting requests in the work queue
-                handleAlreadyShuttingDownWorker();
```
Comment (jonathan-buttner) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java:637]: I don't know how likely this scenario is but I suppose it's possible that after we set the `running` flag to false within the `AbstractProcessWorkerExecutorService` via the call to `shutdownNow`, an interrupt occurs while the service is completing the item it was running. In that situation I believe we won't call `notifyQueueRunnables()` because of the exception. What do you think about calling `priorityProcessWorker.notifyQueueRunnables()` before `killProcessIfPresent()` just in case? If the service already drained the queue then it shouldn't do anything.

I don't think it would hurt 🤔 

A side note, I wonder if `signalAndWaitForWorkerTermination` should call `shutdownNow()` 🤔

Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java:637]: Good catch on the interrupt. 

I was worried about calling `notifyQueueRunnables()` while the executor is still running. I added a call to it if the `awaitTermination` returns sucess

Comment (jonathan-buttner) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java:637]: Just curious, what's your concern about calling `notifyQueueRunnables()` while the executor is still running? I wonder if we should do the call right before the `killProcessIfPresent()` that way we handle the potential interrupt case here too.

**Review by jonathan-buttner — APPROVED** [review]
