### PR TITLE
backwards compatible deserialization of SqlQueryResponse and fix SQL bwc tests

### LINKED ISSUE #78424: [CI] SqlSearchIT testAllTypesWithRequestToUpgradedNodes failing
This is busted in our BWC tests with node versions >= 7.10.0 and < 7.14.0. `SqlCompatIT.testNullsOrderBeforeMissingOrderSupportQueryingNewNode` is also failing on the same builds with the same error.

**Build scan:**
https://gradle-enterprise.elastic.co/s/ihwhafl6ggimq/tests/:x-pack:plugin:sql:qa:mixed-node:v7.12.1%23mixedClusterTest/org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT/testAllTypesWithRequestToUpgradedNodes

**Reproduction line:**
`./gradlew ':x-pack:plugin:sql:qa:mixed-node:v7.12.1#mixedClusterTest' -Dtests.class="org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT" -Dtests.method="testAllTypesWithRequestToUpgradedNodes" -Dtests.seed=8B155910105B6087 -Dtests.bwc=true -Dtests.locale=en-ZA -Dtests.timezone=Europe/Warsaw -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT&tests.test=testAllTypesWithRequestToUpgradedNodes

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:39823], URI [_sql], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"transport_serialization_exception","reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@1196680f/org.elasticsearch.action.support.TransportAction$1@554a8ab8]"}],"type":"transport_serialization_exception","reason":"Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.ActionListenerResponseHandler@1196680f/org.elasticsearch.action.support.TransportAction$1@554a8ab8]","caused_by":{"type":"e_o_f_exception","reason":null}},"status":500}

  at __randomizedtesting.SeedInfo.seed([8B155910105B6087:F06FF849C06FEA2D]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
  at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.runSql(SqlSearchIT.java:316)
  at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.lambda$assertAllTypesWithNodes$19(SqlSearchIT.java:303)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1027)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1012)
  at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.assertAllTypesWithNodes(SqlSearchIT.java:303)
  at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.testAllTypesWithRequestToUpgradedNodes(SqlSearchIT.java:205)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by Luegg**
Resolves #78424

With the merge of https://github.com/elastic/elasticsearch/pull/78363, it's the first time in a while that the bwc tests run cases where upgraded nodes redirect SQL queries to older nodes. Unfortunately, the upgraded nodes were not able to redirect the response from the old nodes to the client due to a bug in deserialization of `SqlQueryResponse`.

This PR fixes the deserialization issue. I also had to work around some follow up issues with `SqlSearchIT` because the new query redirect triggers some new code paths that were not yet correct in all wire compatible versions.

### CODE REVIEW

**Comment by Luegg** [comment]
I've also already created the backport PR https://github.com/elastic/elasticsearch/pull/78465 to ensure the 7.x bwc tests turn green as well.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java [hunk 1]
```diff
@@ -256,20 +251,33 @@ private void assertAllTypesWithNodes(Map<String, Object> expectedResponse, List<
...
+            request.setJsonEntity(SqlCompatIT.sqlQueryEntityWithOptionalMode(query, bwcVersion));
+            assertBusy(() -> {
+                Map<String, Object> actualResponse = dropDisplaySizes(runSql(client, request));
+                assertResponse(expectedResponse, actualResponse);
+            });
         }
     }
 
+    private Map<String, Object> dropDisplaySizes(Map<String, Object> response) {
+        // if JDBC mode is used, display_size will also be part of the response, remove it because it's not part of the expected response
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java:271]:
```suggestion
        // in JDBC mode, display_size will be part of the response, so remove it because it's not part of the expected response
```

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java [hunk 2]
```diff
@@ -256,20 +251,33 @@ private void assertAllTypesWithNodes(Map<String, Object> expectedResponse, List<
...
-            String query = "SELECT " + intervalYearMonth + intervalDayTime + fieldsList + " FROM " + index + " ORDER BY id";
+            String query = "SELECT INTERVAL '150' YEAR AS interval_year, INTERVAL '163' MINUTE AS interval_minute, "
+                + fieldsList + " FROM " + index + " ORDER BY id";
             Request request = new Request("POST", "_sql");
-            request.setJsonEntity("{\"query\":\"" + query + "\"}");
-            assertBusy(() -> { assertResponse(expectedResponse, runSql(client, request)); });
+            request.setJsonEntity(SqlCompatIT.sqlQueryEntityWithOptionalMode(query, bwcVersion));
+            assertBusy(() -> {
+                Map<String, Object> actualResponse = dropDisplaySizes(runSql(client, request));
+                assertResponse(expectedResponse, actualResponse);
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java:265]: optional nit: `actualResponse` could be inlined.

**Review by bpintea — APPROVED** [review]
Lgtm, thanks.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java [hunk 3]
```diff
@@ -135,4 +138,20 @@ private void testNullsOrderWithMissingOrderSupport(RestClient client) throws IOE
         return rows.stream().map(row -> (Integer) row.get(0)).collect(Collectors.toList());
     }
 
+    public static String sqlQueryEntityWithOptionalMode(String query, Version bwcVersion) throws IOException {
+        XContentBuilder json = XContentFactory.jsonBuilder().startObject();
+        json.field("query", query);
+        if (bwcVersion.before(Version.V_7_12_0)) {
+            // a bug previous to 7.12 caused a NullPointerException when accessing displaySize in ColumnInfo. The bug has been addressed in
+            // https://github.com/elastic/elasticsearch/pull/68802/files
+            // #diff-2faa4e2df98a4636300a19d9d890a1bd7174e9b20dd3a8589d2c78a3d9e5cbc0L110
```
Comment (astefan) [inline x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:147]: Add one more comment stating that the workaround for versions between 7.10.3 and 7.12.0 is to use the `driver` mode.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java [hunk 4]
```diff
@@ -256,20 +251,33 @@ private void assertAllTypesWithNodes(Map<String, Object> expectedResponse, List<
         ) {
             @SuppressWarnings("unchecked")
             List<Map<String, Object>> columns = (List<Map<String, Object>>) expectedResponse.get("columns");
-            String intervalYearMonth = "INTERVAL '150' YEAR AS interval_year, ";
-            String intervalDayTime = "INTERVAL '163' MINUTE AS interval_minute, ";
```
Comment (astefan) [inline x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java:260]: I find this style to be more "visible" and easier to read. Can you, please, keep the original version?

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java [hunk 5]
```diff
@@ -81,10 +82,16 @@ public SqlQueryResponse(StreamInput in) throws IOException {
...
+        if (in.getVersion().onOrAfter(Version.V_7_14_0)) {
+            columnar = in.readBoolean();
+            asyncExecutionId = in.readOptionalString();
+            isPartial = in.readBoolean();
+            isRunning = in.readBoolean();
+        } else {
+            asyncExecutionId = null;
+            isPartial = false;
+            isRunning = false;
+        }
```
Comment (astefan) [inline x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:94]: Why this change and why is `columnar` included there (it seems you grouped together the async specific settings)?

**Review by astefan — COMMENTED** [review]
Left some comments.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java (hunk 5 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:94]: It hadn't been serialised before the given version: https://github.com/elastic/elasticsearch/pull/73991/files#diff-3c77d10764f4a72e650dfabe508e5d372bf024a776ca17b81c2f4666f859fe01R187 , which was probably an oversight.

Comment (astefan) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:94]: The fact that we discovered this in a BWC test and not when the async search was introduced is troubling. At some point in future we will need a set of tests that should cover the serialization differences between bwc versions for both the request and response objects. I did something similar for EQL here: https://github.com/elastic/elasticsearch/pull/68339. @Luegg please open an issue for improving the tests coverage in this area.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java [hunk 6]
```diff
@@ -6,26 +6,27 @@
...
 import org.elasticsearch.common.xcontent.XContentBuilder;
+import org.elasticsearch.core.Nullable;
 import org.elasticsearch.xpack.ql.async.QlStatusResponse;
 import org.elasticsearch.xpack.sql.proto.ColumnInfo;
 import org.elasticsearch.xpack.sql.proto.Mode;
 import org.elasticsearch.xpack.sql.proto.Protocol;
 import org.elasticsearch.xpack.sql.proto.SqlVersion;
 import org.elasticsearch.xpack.sql.proto.StringUtils;
 
+import java.io.IOException;
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:24]: yes. I think that follows the default imports layout.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java:271]: 👍 thx

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java (hunk 4 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlSearchIT.java:260]: sure, I inlined it because I thought it was a leftover from using a conditional here in earlier revisions.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java (hunk 5 above)
Comment (astefan) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:94]: My initial question still stands.
To clarify a bit: `columnar` has been added in 7.2.0 (https://github.com/elastic/elasticsearch/pull/39287). If we should handle it differently depending on the version it shouldn't be 7.14, since that's not the version that added it. Or I am missing something.

**Review by astefan — APPROVED** [review]
Looks good in general but the original question I had about `columnar` still stands.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java (hunk 5 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:94]: > it shouldn't be 7.14, since that's not the version that added it.

True, but that's the version that added it to the serialisation.
If not mistaking, between (and before) 7.2 and 7.14, a serialised `SqlQueryResponse` didn't contain the `columnar` field. So trying to deserialise a `SqlQueryResponse` and read the `columnar` field would eventually fail.
A 7.14+ serialised `SqlQueryResponse` will otoh contain it and needs to be read.

Comment (Luegg) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryResponse.java:94]: Thanks @bpintea, I was getting confused myself.

File: x-pack/plugin/sql/qa/mixed-node/build.gradle [hunk 7]
```diff
@@ -22,7 +22,7 @@ testClusters.configureEach {
 tasks.named("integTest").configure{ enabled = false}
 
 // A bug (https://github.com/elastic/elasticsearch/issues/68439) limits us to perform tests with versions from 7.10.3 onwards
-for (Version bwcVersion : BuildParams.bwcVersions.wireCompatible.findAll { it.onOrAfter('7.10.0') }) {
+for (Version bwcVersion : BuildParams.bwcVersions.wireCompatible.findAll { it.onOrAfter('7.10.3') }) {
```
Comment (costin) [inline x-pack/plugin/sql/qa/mixed-node/build.gradle:25]: small nit but a comment would help on what changed in 7.10.3 vs 7.10.0 to make this version being considered.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java (hunk 3 above)
Comment (costin) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:147]: 👍

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/mixed-node/build.gradle (hunk 7 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/mixed-node/build.gradle:25]: Using 7.10.0 was a bug. As the comment on line 24 says the version should always have been 7.10.3. But accidentally, the tests also worked with 7.10.0 until I introduced missing_order.
