### PR TITLE
Remove support for Visio and potm files

### LINKED ISSUE #22077: Fatal error with ingest-attachment plugin
I am getting a fatal error when trying to index the attached stripped down document using the ingest-attachment plugin. This causes my cluster to reboot and does not give me an email notification. It looks to be having a problem with the embedded Visio diagram.

Version: 5.1.1 (Elastic Cloud)
ClusterId: 7e7501
Node: instance-0000000005
Plugin: ingest-attachment

Link to problematic doc: https://1drv.ms/w/s!ApTXXtrEV_GGiosenEfoUSk1rRnuYA 

Error Information

```
Dec 8 21:42:34 ERROR org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler i5@z0
```

```
[2016-12-08T21:42:34,628][ERROR][org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler] fatal error in thread [elasticsearch[index][T#1]], exiting java.lang.NoClassDefFoundError: com/graphbuilder/curve/Point
 at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_72]
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_72]
 at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_72]
 at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_72]
 at org.apache.poi.xdgf.util.ObjectFactory.put(ObjectFactory.java:34) ~[?:?]
 at org.apache.poi.xdgf.usermodel.section.geometry.GeometryRowFactory.(GeometryRowFactory.java:39) ~[?:?]
 at org.apache.poi.xdgf.usermodel.section.GeometrySection.(GeometrySection.java:55) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFSheet.(XDGFSheet.java:77) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFShape.(XDGFShape.java:113) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFShape.(XDGFShape.java:107) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFBaseContents.onDocumentRead(XDGFBaseContents.java:82) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFMasterContents.onDocumentRead(XDGFMasterContents.java:66) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFMasters.onDocumentRead(XDGFMasters.java:101) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XmlVisioDocument.onDocumentRead(XmlVisioDocument.java:106) ~[?:?]
 at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:190) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XmlVisioDocument.(XmlVisioDocument.java:79) ~[?:?]
 at org.apache.poi.xdgf.extractor.XDGFVisioExtractor.(XDGFVisioExtractor.java:41) ~[?:?]
 at org.apache.poi.extractor.ExtractorFactory.createExtractor(ExtractorFactory.java:207) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:86) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87) ~[?:?]
 at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
 at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[?:?]
 at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72) ~[?:?]
 at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:102) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:311) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:202) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:115) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:112) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87) ~[?:?]
 at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
 at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[?:?]
 at org.apache.tika.Tika.parseToString(Tika.java:568) ~[?:?]
 at org.elasticsearch.ingest.attachment.TikaImpl$1.run(TikaImpl.java:94) ~[?:?]
 at org.elasticsearch.ingest.attachment.TikaImpl$1.run(TikaImpl.java:91) ~[?:?]
 at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
 at org.elasticsearch.ingest.attachment.TikaImpl.parse(TikaImpl.java:91) ~[?:?]
 at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:72) ~[?:?]
 at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:100) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:58) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.PipelineExecutionService.innerExecute(PipelineExecutionService.java:166) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.PipelineExecutionService.access$000(PipelineExecutionService.java:41) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.PipelineExecutionService$1.doRun(PipelineExecutionService.java:65) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.1.1.jar:5.1.1]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_72]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_72]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72] 
Caused by: java.lang.ClassNotFoundException: com.graphbuilder.curve.Point
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_72]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
 ... 47 more
```

### PR DESCRIPTION
**Pull request by dadoonet**
* Send a non supported document to an ingest pipeline using `ingest-attachment`
* If Tika is not able to parse the document because of a missing class (we are not importing all jars needed by Tika), Tika throws a Throwable which is not catch.

This commit removes extracting embedded content from Office XML docs.

So elasticsearch is not killed anymore when you run a command like:

```
GET _ingest/pipeline/_simulate
{
  "pipeline" : {
    "processors" : [
      {
        "attachment" : {
          "field" : "file"
        }
      }
    ]  
  },
  "docs" : [
    {
      "_source" : {
        "file" : "UEsDBBQABgAIAAAAIQC0lAFevwEAAK8IAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADElklv2zAQhe8F8h8EXgOJTg5BUVjOocuxCdAU6JUmRzZRcQFnvP37Dr0IRSBHRh2hFwHSzHvv4xASNX3curZYQ0IbfC3uqokowOtgrF/U4ufLt/KjKJCUN6oNHmqxAxSPs5sP05ddBCxY7bEWS6L4SUrUS3AKqxDBc6UJySni27SQUenfagHyfjJ5kDp4Ak8lZQ8xm36BRq1aKr5u+fGBBFwjis+HvhxVC+uyflvmiuzVJGjxlUjF2FqtiOty7c0rsvJIVbFy34NLG/GWG84k5Mr5gPO6NZrtAJnDcm25uzJJbXj62emJNyZZA8WzSvRdOZbJTUhGmqBXjq2qt4F6Vhyaxmro9NktpqABkTNdW3UVp6w/TaKPQ6+QgvvlWmkJ3HMKEe+uxulMsx8kstDtxtlZ+JWbQ2L69x9GZz0IgbRrAd+f4OA7HA9ELBgD4Og8iLCB+Y/RKP4yHwRpQiAfaIzd6KwHIcCbkRhOzhfNAdL172TvFCBdmH//H/M5T81bGIPgaD0IQXwgwuF6/U7sbd6K5M79h5gP2PQPyz6dhlldxou+wF0iW1+9PsgHpgHTky33vxuzPwAAAP//AwBQSwMEFAAGAAgAAAAhAB6RGrfvAAAATgIAAAsACAJfcmVscy8ucmVscyCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsksFqwzAMQO+D/YPRvVHawRijTi9j0NsY2QcIW0lME9vYatf+/TzY2AJd6WFHy9LTk9B6c5xGdeCUXfAallUNir0J1vlew1v7vHgAlYW8pTF41nDiDJvm9mb9yiNJKcqDi1kVis8aBpH4iJjNwBPlKkT25acLaSIpz9RjJLOjnnFV1/eYfjOgmTHV1mpIW3sHqj1FvoYdus4ZfgpmP7GXMy2Qj8Lesl3EVOqTuDKNain1LBpsMC8lnJFirAoa8LzR6nqjv6fFiYUsCaEJiS/7fGZcElr+54rmGT827yFZtF/hbxucXUHzAQAA//8DAFBLAwQUAAYACAAAACEAUyT3RoEBAAByBwAAHAAIAXdvcmQvX3JlbHMvZG9jdW1lbnQueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0lctOwzAQRfdI/EPkPXFToDzUtJsKqQs2UBC7yk0mqUVsR/b09fdMKU1TKBYLs/S1PPfoeuzpD9eqipZgnTQ6ZUncYRHozORSlyl7mTxc3LLIodC5qIyGlG3AseHg/Kz/BJVAOuTmsnYRVdEuZXPE+p5zl81BCRebGjTtFMYqgbS0Ja9F9i5K4N1Op8dtuwYbHNWMxnnK7Dgn/8mmhr/UNkUhMxiZbKFA4wkLLhV5U0FhS8CUKcil2IlJDKpg/DRDchkSAulsC+JzuROTmIr9BhGUweGmoptsIHZrn/1NSHvQuTbYBtgrPoSkG5KhMBonYla1rqKRfBRBIfRCzcDSYztANJI3ipAQ2cKhUW/k1kDE8UHlEkF5W7MX9l4MfmuORvJGEjSTrSXYYwSwXR/AdUj/FcyeAZHaoJVDS/Qm0fn/JLz9cBX0q/oRw17xIdyFRPgaWq3fip5ovp2Rjj/KzBpnCpy+Shqi05EVK9pI4qXL11s6fjQpBx8AAAD//wMAUEsDBBQABgAIAAAAIQCHBIL5pAwAALJAAAARAAAAd29yZC9kb2N1bWVudC54bWzsWFtv4jgUfl9p/0OUd5oLAVJUGLUU2j4NmtK3SiuTGOJtYmdtA0N//Rw7Vy7l1unLaFupCcc+3/nOHfXm288kNpaYC8Joz3SubNPANGAhofOe+TIZNXzTEBLREMWM4p65xsL81v/7r5tVN2TBIsFUGgBBRXeVBj0zkjLtWpYIIpwgcZWQgDPBZvIqYInFZjMSYGvFeGi5tmPrt5SzAAsB9gaILpEwc7jg52loIUcrUFaAnhVEiEv8s8JwzgZpWdeWvw2U7LrGUkzhcMZ4giR85HMrQfxtkTYAN0WSTElM5Bog7XYBw3rmgtNuDtEoqSiVbkYlfxQa/BS7mcp9ng5t0eI4Bg6MioikZUyTS9HgMCpAloecWCZxcW+VOt7nCuI+y0oFeAr9PJVJnDE/jOjYJ2REQZQap1DYtFkwSRChleGLQlMLrtM6D8DdAWgLfB5EK4ewxDqpWmOVzj+X5QfOFmmFRj6H9kTfSiw1r87AyqulXsHic2SeI5RCKydB92lOGUfTGBhB7g1In6EzYKguMfswTacsXKtnCgdeN0UcPYU9s+l57VZzeG9qKUwkqaSd/AekXZjc4Y+eCeybnbZ7V4ru8QwtYqlOmo7rXTvFybh2WRscc/14lusY+HSXKO6ZjxipFeCYVv/GKu9MGXtTQ+5ZwnSEqwS42AqXogQ8+2fCAq/tt52W73eUJhhUf1S4HtdphGmGpoV8D3cll/2JipPBZsaAUQkjSCgdWWkWLIY0LDnkNLW1UOaPjDTPHyNAE6CARECgyAYoJlNOFHuMhLwVBE0gxeBGQiBXj7dU6MNIvVTXtVfTIkzaMHweKOC6JGAxUx5qmWerXwUmlYWBOuuZKpk6KVo4IRRydTfK1MV7oevmgOK9suG6mSxGdF7IMG0MbuvOaNHLcx6ZPAhERUzfb7h2y3Vdx/O9DAy2+Riy+n36b+3TA4pjzNeF0k5mNlRfKPlvgTN7dTSrlgx4gbSNeeZTKHOg3cK3r+2h741UgC4v/GNVPvk+yAu9XudFIW0ScjzXvWu5ynSNUNu/7jiep/qzIuTbrfZIJ2ObkN1puc5hQrrloCjQVOTP4jDGM6lAUwZjyfPywqhd4GQe6RsxOIWhxEJWKVw3W0WbFNh7O2NvE+zrkGEuK5tkr2YgdHnn4jsS5i1E2ZgzNtttFrSQbKcJ9hf8ZnVXY6ocLWOugu62IeYdHfRZHA7gm51Rvk3WKXCb4jns5iPD6UNQQoXkEygItTa6IkUBQKYcC8yX2OwbkFTjlRmm02iaxmtkvL4brwtD2So191g+lbvAqkIlrtOP4ITHhL6ppNIgUuNmczirnBEhGV9DZWv4DZe3KjjjMnDbdnuUXc4DvbkzCqvbGa7mj+w7W8N8n9k/rzZ1z31UX18X7GOb9Ejw63FY4ekjCcNyhZ/q1VlwF7XnJYaOtez49mH4YzgyNppG9e6xrr2M0FcHcN+M+Hzuz+3li+ljGlbMrdp4+3BXu/6gNfBG5sauhm88o9vh3bDstMO7uubA/7v6y3b1sVXlH1pVv3FUutu1/OcF/cNx/RvD+EQlZ+EiUP96OhDRszfLWbonr5GzUDd3xi8AAAD//+xabXOjOBL+KxT39TZB4t23TsXGeJKq2Uoqyd59uaopDLLNBCMOsJPsr79uCTDY2Mlkk6naLc9UOUhqie6nW0+3ZBdZELKhmuWsYPmGqRfK7eiLf+dPlW8PPDQsxyKm4zjKf5fKr+dPgzgtyvyBPZcX2Movfq0/bsWflN/mnM/P8fmJza7iKGLpuZRFiffMeRrMk8hbBrnSPD28ZKBzwbIgD0qmVsI/vnB5QbH1TmMOKsbSaKsTfC6hN0/i9FG0MpyZKU/EGKD+19FQpZPxxPdcSxW9JcCLvbZFDI0S7B3kRRzdDVVNczTTmo6argmbB+ukbI2I1aV62X35kjAQ3QTJUH248QiqBfYGs6L6Ww8mbF7iohkvhqphaI1gLZDHi6WQSFgQsXyoRnw7wdVNMQOxrNauEMqnPC0LkAuKMI4flmwF+KzilOdXo7SIcQUWFOWoiIP2oF/14fgSBXtnhkXZ6h7HUSzVbjsu5AlHBwkjgnXJpUjxR91HqexJgnRR97H0l9/vaxdWcVth2vgSbUrDJQco2jvFFSrHRcnzl6FKhDvw/cJbtzk6yqOWZk3lSIVSx1FX9St2rWkHrn4kcP8moItgau/tT4DxZgOsF7OnP0UDO2r+0NwDFDJjizh9P7E1NK08r5JB8SaOd08c/5kcb42oO/Vd2uV4Q/ccV3fNj+N4/W0cT4h2Ivl3kryr/SySPyNn5ET0HwHldaoUIc+Y8nvBlDAoWHGifFc7Uf6nUr5DHDLR9S7lm9bEHE19wSEnyv+rUD75iZR/LHpPlP/22n5dKnyu3De0751oX8byifY/k/Y1jZrEcewu7du6PRr5U+PjaL/aZ6/RvuOcWP+9rI+ntZ/D+ifO/xAgJ0EZKEEaKddpyRbAJzFPT4zv0hPjfybjm1PDsDxz9/6++tdhfEu3LTpuumToU4uS8VaulQY024SheuS2JSwM7V3mByzLxGcRlR4wDEslkNDsMdGfTjTDQVVeM3GqE2Jv81zLmmpErC49gOEbC86YsTnPQUVxLgrmJWYlKg8sW74WHzM0qxT2ZMGiFT79zqHjkaE7Dir0mubuWHesSZ/mjkN0Iu72Gz9YLhmNJNq9GfoKUiuYJr5z2Vow4/xxFeSP92WQlyAaR5hX4CENkIQ7X7pJohPTEuDyO/Aey1l0C0aPcxY8imG82ihzHq3DHq6r3+YDI9bvqtTpAcr1RpZv7xxXe4GaTAx/tP1iSoYfAeduMWqjNxkbridyaYNetcIHoCfW3UfPbaF38J5/Hx+RyPrxMcYQ//rI+fFd3oKiOyKg0KaWMZWJ7xgU4pR/HAp03T4UblX/VVDUN2G7zNnW3/F005QqHUozx6bTieEaVE6/OHThto99Y+Eh+wSpVPZ94eMgrGqB/aUMOdB1oD6lEKI+huirDrTAS9vCXAb4Tmfbq9T0aHOJL+lBCre8+j2sPRoC1bK8h9r47DsL0droObiBIh32q+ZSwQ/RS9XjuDZ2gAWyYhVHDtd0bM3D/bQZFMsgY8iPCiLx7RkiTPtW2qBeyHkeFfEfgB8llqb9U3yqCgf/gh0owgfg4znLc5ZA8bQBSTgYZEG5hALx0rg0E/gg5NKVH+YzU5V5nCQM3jRXFSgu+KN8FpqIpvKdY9kBEY1FZmX4ZgB0v1oDr4lnhf0vHarxXIE0yyZ58JQqWfzMkq/Q/E8clUtFBHEjWaxXyqWmkJ5uDf5fCt5oujPgR+WSgrjY3jv9uiJgkC8UL3tN6IqJ81OPQqBSz2TrwJvt428WazqVTNfQnvmHlCJae4XzLvDoWfA5bIV8XUD+4I/Cj1A5RzEEqQgl7CsxMkKephCeMvXm8IQL8kHCw0dlg2tAgRHFIBoUGYyK6hunytc2YdnEaDs+Y6LhBpJr/6MdtFXkPCE8A93Qzpys/NdSGDugjnZGM6EcRyERdfEKEmSEB4FccAHsEAclyrgUMi11UP2br/6N3HayRvJXMxapCtSOi+vJUP13DLicYUgCB58RUOgeZ+JQV3UUGQnDh2pVTqmKXFkIE9Ogumk7Osg2ioksdV5v/OOFDJRgnm+ab8o/tukBf3fpSyPWGAHtoa+OuExKUriHRak1tXXbQB780DRIPaoZk49Ig8LG/TRY/fqlrghat4M/MxX2XULu5y+BfH8Y2CbRPH+680VyL/7Ut6nR1F1t/LsjEv+tpr34f42LcrwGqhcbGgBer6oDabJJaqGq1ICxazRl23feniDMxEsqyMmW/DI1SOFQvJDtloMPVGIuMYyp+6bDyNTSfL8Pgu6IgMC1dWIfKUo/CoLj1tGx7k+0MZ5DXrNuPNZNq7ci6Y4I66qu1zZYUwEf3mCi8t/fYNUlULXB3nAVsx/31uG4Nzwdzgz6TvWm+2Ti+XSLAVpKfGKS7Qm0Op50O1tYdUcEViPdJGOvjVWvryuLO76u8Wsm7J9xKRZdzSnXEQ0sfGBE1HaicbfGbLW9bePrEru/7rx9N5YKyCO3HQp6Axr3ImsBLZvEN3xh9pxz0O4Oa0GWhhgkMjezDUtbCYxU4X5IPJIwt2fUv0LECrUuiCFfxumar4sq4yzu8W7xCepfSg3JEPBsOvUvE7PFb+J2o+QZ9OMPFtESrAm2zRkvS77atiXh1K1ldfNta5hQK/2b5mJdimb1upAneP9aUT/KiO6Ih1/yWJAZeOY2LsNlm8GkK8TjjEcv4gGmrFd40/J/AAAA//8DAFBLAwQUAAYACAAAACEALm4yA1wCAADECAAAEAAAAHdvcmQvZm9vdGVyMS54bWzElttu4jAQhu9X2neIfA9OOHQhaqgolIqbFWrZBzCJc1Djg2wngbffMQmhLNqKg1abixzGM9/89owNj09bljslVToTPEBe10UO5aGIMp4E6Nd60RkhRxvCI5ILTgO0oxo9Tb5/e6z82CgHorn2KxkGKDVG+hjrMKWM6C7LQiW0iE03FAyLOM5CiiuhItxzPXf/JpUIqdaQakZ4STRqcOH2MlqkSAXBFjjAYUqUodsjw7saMsRjPPoTxM6nJiTlMBgLxYiBT5VgRtRHITvAlcRkmyzPzA6Q7sMBIwJUKO43iE4rxYb4tZTmcYhQl+StQ+YiLBjlZp8RK5qDBsF1msl2TdmtNBhMD5Dyq0mULD/4VdIb3NcQ87oqR+Al8ptSsrxW/jXRcy+oiEW0EZdIOM15UMJIxo+Jb1qaT4vrDa8D9M4AD5pehxg2CKx37Lg1KpncV+VXJQp5pGX30Zb8o2XZo+oKVtMtnztY3yfmPSUStjIL/WXChSKbHBRB7R0on7OvgGN3CZrAQSrBMPAlUWQZBchd9GbeeNBHeyucRMZafzQXWH04rKM3cHRns/60P21NcxqTIjfnIytrGr+47ui5TrhS+8e72eWgwy9JHqCFEIYqhO2Iqh3UicOKJPRnwTa1E268cIurb5dHwi9IHs3gtHXat/VOwjJtaAL7pfG8jZxxbdQa1s7W09eShMCVimqqSoomq+nri+NY/9bxnmx/mYemtqaG3jKVyudipYSITxKZSc9+/QuxlEdHnbao553ZG8+92bNn2+o/deah2Wp9eP8fZPIbAAD//wMAUEsDBBQABgAIAAAAIQBRkj/ynwIAADMJAAAQAAAAd29yZC9mb290ZXIyLnhtbLRW227iMBB9X2n/IfJ766QQSKOGigao+rJC2+4HmMQBq/FFtoHy9zvOjVK0XSi7POQynjlz7DMz4e7+jZfehmrDpEhQcO0jj4pM5kwsE/TrZXYVIc9YInJSSkETtKMG3Y++f7vbxoXVHkQLE29VlqCVtSrG2GQryom55izT0sjCXmeSY1kULKN4K3WOb/zAr56Ulhk1BlKlRGyIQQ1c9nYaWq7JFoIdYB9nK6ItfdtjBGeDhPgWRx+B+PHWpKICFgupObHwqpeYE/26VleAq4hlC1YyuwNIf9DCyASttYgbiKuOiguJayrNrY3Qp+StQyYyW3MqbJURa1oCBynMiqnuTPlX0WBx1YJsPtvEhpet31YF/csKYlKrsgc8hX4jJS9r5p8jBv4JijiILuIUCoc5WyacMLFP/KWjeXe4QXgewM0RwMDQ8yDCBgKbHd+3xlYtL1P5Ucu12qOxy9CexGuH5UbVGVhNtbyvYHMZmecVUdDKPIuflkJqsiiBEWjvgXxepYDnugSNYJAqMPRjRTR5ymEG9ydBGvZSVFlhEllnDafDQe8hmII1hmGd/0yQ76dpb9wbd6a5dsbhJIzSYWec0IKsS3vsPnem26nvRw81i7mubs92VwK5eEPKBM2ktFQj7FZ07aAPHOZkSX+s+aJzmklhDawSkzEQNCUlW2jmPcgyd5lXY2E+mqvARX1NDdxxkwx3rOrL3wm0kfB1KvMUJrnXPb3sFEiwoEvoxcbza8hMGKtfQBdXK7FRJANcpamhekPRaD5+nHqe8+8cL8n2h30Y6urF0oOtvK+NyA8Hs3Gl7EnCCTnXUhYHue0ocG//gz8Vle41rtP5uBH60ygK09nNYSMMm99njfCvar6tv5ofrv7yjH4DAAD//wMAUEsDBBQABgAIAAAAIQCOmL+CCwIAADkHAAASAAAAd29yZC9mb290bm90ZXMueG1stJTNjpswEMfvlfoOyPfEkIV8oJCVtlGr3Kpu+wBeY4K12GPZJiRvX0OApJsoIhuVg4Gx5zf/8dizfN6LwtsxbTjIBAVjH3lMUki53Cboz+/voznyjCUyJQVIlqADM+h59fXLsoozACvBMuM5hjRxpWiCcmtVjLGhORPEjAWnGgxkdkxBYMgyThmuQKd44gd+86U0UGaMC/iNyB0xqMXR/TBaqknlnGtgiGlOtGX7EyO4GxLhBZ5/BInL1EAx6SYz0IJY96u3WBD9XqqR4ypi+RsvuD04pD/tMJCgUsu4RYx6KbVLfJTSvjoPPSTu0WUNtBRM2iYi1qxwGkCanKt+T8VnaW4y7yC7W0nsRNGtq1QQPnYg1seqnIBD5LelFMVR+W1i4A+oSI3oPYZI+Ddmp0QQLk+BP7U1Z5sbRPcBJheAqWH3IaIWgc1BnK5GpbaPVfmHhlKdaPwx2ka+96y6Yd3Bak/L+Qk2j4l5zYlyV1nQeLOVoMlb4RS52nuufF5TAa++JWh11k69KrYH5dYZpogmFjRyJp4maBQ0C5XzDON6buOM0XQ+WyzWEWqsrmXZ2jprn9rV9fb0V4J8P5xH/mLdm9YsI2VhL2d+1qbJdBK8zJqAuh56NXi1xI3NjaoZO+VXs6AgLZdl04teP2bkX0sonM0Xs6fwfyd0Vdit5M5+zOovAAAA//8DAFBLAwQUAAYACAAAACEAo0pYhAgCAAAzBwAAEQAAAHdvcmQvZW5kbm90ZXMueG1stJTbbuIwEIbvV9p3iHwPdlA4RYRKFFFxt9ruPoDrGGI1Psh2CLx9JyEk3YIQFG0unGTs+eYfjz2zp73Mgx23TmiVoLBPUMAV06lQ2wT9/bPqTVDgPFUpzbXiCTpwh57mP3/MypirVGnPXQAI5eLSsARl3psYY8cyLqnrS8Gsdnrj+0xLrDcbwTgutU3xgISk/jJWM+4cxHumakcdanBsfxsttbQE5woYYZZR6/m+Y4R3Q4Z4iidfQfI8NW24gsmNtpJ6+LVbLKl9L0wPuIZ68SZy4Q+AJKMTRieosCpuEL1WSuUSH6U0r5OHvSXu0WWpWSG58nVEbHkOGrRymTDtnsrv0mAyO0F215LYyfy0rjRh9NiBWB6r0gFvkd+UUuZH5deJIbmhIhWi9bhFwr8xT0okFaoL/K2t+bS54fA+wOAMMHL8PsSwQWB3kN3VKM32sSq/WF2YjiYeo63Ve8uq+tUdrOa0fD7B7jExrxk1cJUli9dbpS19y0ER1D6A8gV1BYLqlqB5102DMvYHA8scN9RSry0Ck0gT1AvrdQYco7iaW4ORDKPn8ZSsUG2FjuUr67h5Klfo7OlvWEiiyZBMl61pyTe0yP35zK/KNBgNwsW4DmiroVWD5zNc22A09dgIv5QD08oLVdSN6PVrPuRSOovBahotyP9O56KwK6l1327+AQAA//8DAFBLAwQUAAYACAAAACEAOOeS1EUnAACgOgEAFQAAAHdvcmQvbWVkaWEvaW1hZ2UxLmVtZux9C3xUxfX/bJLdPEl2Qx4b8lrICwmoVMAoJFmzEbGhNIq8igqEdwWMEhQKlfgoyuMH0Qr6R4sI/woSRUVqtUgSLD54+Gvaqj+t/Cw+fqCmFXzzK9r8zvfOPdnNsrvczd2QTdzJ5+TMnXtm7uy958x8z8zcuQYhxDyifCID0cYwISYRcRg5Q4g5Vwthu/wnIyGx+VKDeNMoRLhTRAm1kUIURQjxW8r7SxTkEt4cFyNGNRsFFSAGEtmIqLhCg90gMihuJgozN72LbFNVguxRojdU2Wx7uIhTy7vQHqbkiVCOakv72SPazmXZo9vife2RbfEBdiFyiVvVPGpyu3ghyTjLMbmUY/RYvpYyXesQYXeW35coiqiCiJLFhUR0W5V7g/sAMiuSTa0gA0mB3I/7CVlmKwXcMytljDPIe5Znl2XI+ySE6zHKb1//pjJVTMZrLY76g8nlUXYRvptStgv5jCyqxOuHD5eAz5o1yw5+aGUN8dr8j1qX2++fdnED+OeHDiv8H//9QhP4phNNTZCr3/FKE/KBoxzw0dMvVrgQR4ZBDhz5wFEOOMqFHNXmMXn9UduEITw83IXuDDcYkuyi1izk78R94XtdJeS9wm/H7wZRnYvVn9QuDhMoEPLesDpTUQrPcymnt0t8uJDXSRfyPt8aK8QNJDxMPd6RJY8nUrw/X0iWqwTY1PfZN+SZ+07MNfc15nA+M/2A+8J85zP3LTF8n11I1yhsux6uXyh858uNKRTm6BKDOfq+sLbrRZMu5pzletETc3Njbsi7NfaGPNw0/O4RKodi4L7dK+R9tNC/CWHt7xXfQwq1Ls/iMufVnHGUAd1+mDLWqbqtxfa0yOTb29tEx2zEEIbffqGQNoKza1Wpa98aMAL1Z0JgmTcfmtwaZQ/rXvZFtz/Zpf3VaktTiIrUODgCc5RiVmOTH3qzLRWB9QT5OE7tZG3I1iS3C6mb64TaHqn9N98r6pZr/bU11IPvuXv/cpLoI9G5Nuh6rLUMX3Za/fodjv+66PeX+SqHZTz10RkqR19tVs+hr3a5lx7Lwv1DWZwHIcbtmKCVqDbIe32yVe1g1IC2DoHuQz+HmEY4bS71YTfTfyGWR2aI5eEZ4sG/ZYj0mD1GG9EzJyJesL5LaZNut772whTri3Ru2a3zTbKUPNxbboKUYJ9sje9PMstfOXIjn1vzYdyto/5y8Prl4XuMSWEZlJxhQDVAODdPOTfFutsgz9lnju71xsZPF/QTPxJbBshyv5t0OgbpI97OEDmE+GQ6cEutML9U0quIzkHHrMRxZgbJXVF+pSPq9nvCp1K8T6X1lsqsXyUfOR0RC117+m08AestiCMNeVCfJ5R0hAzD09eXKWUhuNaFw4xblEfYrj1JUePQh0Q1jnJxjPi1D70Rdg3x54lMBqkDq4j3UfO7B5Qx2i2N7bia4qPEjWKRWEjPb4GYLRx0tID+ZorpoobScLRQ0Q9ch5oFgQcHG8AxE9JdjyNVObQTfA7H/DvpptT6sueviD4WnuzZfxviWOfItK/Pw7e8fNb6sEwgbJrLCi6bTr3lP5P63uZaPsLUC0bGQBcnHh4dg+fsyaZZ9mw2/bhHm7ap6f7ZtK2ftGnoG9s04t5s2jylvU1zXTjosWnQatWm1/qwaeT1ZtOVFD9fSBsNtL1p0W+OnQt7e3Dpq2etD8sEwt64rO5gb7UJl8TgMjbLJbrt7WkvfahM98/e6vL8szf3PpTrwkGPvU0kWqfaG/w4b/aGNF/2Np2eIfo8kFabm0rXu8ZwdpvTouMc0yKjZ/wls/+FjonjniuDf1hHKXcJ6R+2PSAK9Tt+3gC+vN9zDW+WryP/7lM6tpWCr79uscKF2FyK8+BSfnPpM7a/7MX5bTt2PAP5rcSR/xHluG4bzlP6dkU+3BnuJP8vyR4WkLGVs42hjCOqdGZu0wH8/tMxFRGnY1aGPx7XErYnviXsdXNL2NLEleFLEysilibGG1831xv3xNcbH4+rN56OiTdCfoRaLo9NPCVk292fLjrZrQ4dGZtYTBnnedSxrhmbcOpPx8YmynYubMXYX50IEt2jayXb2/9+LXo2RWgbd1i40+X2Ce/jDqyXO4kGEQ2gilwnlDaoQ3oZ8tM5kM7+fJTjwXvuLfNVDssEAmNwWf5ijK+6CGPg2oHAGA1eMIZM9w9jnBqkz0/nunDoCMaYNGmSgjHuJ3pNyDY+wSD1wBPGQB5vGGMGxS8TM+jPJm4l37xKVNMTnU2xhW2+NjjKZR/dE8EmAo1PtNgHx7TI6JsfGup4YkCsI9j6iCR7YOZ+9OCTytiKyMrYlaZ/x7UYzQktxhxLi7E5caWpObEisjkxPirHUh9lTqiP+ndcfVRlbHwU5N3xye+IricaRBdd7VaHnoBPnPqjB58EFTYWnTkv4i8+eVZIXHIBVeQ/hMQnHdHLED7h0FRWO7eS2t/Pfba/LBMIfMJldQd8UnSwOAZ1nJg406oXnxz2gk9kun/45MFh+vAJ14WDXnzSTLSAyEICS9X87uFs+ORyQidzRY1wRyiMPTAXAJ0HR2UZs/B56Bx4oPGJFvvgmBYZ/fhkuCPY+ohgGD+hdj2G+oFo6geovW+hdr8livqBaOoHYqgfiKV+IJb6gVjqB2KpH4iFvCd8gn4a+GSPWx16Dj6B/oTGT4rUODgCc734BLgE+IQqzPjEb70M4RMOTWX27y53jN7f3+GrHJYJBD7hsroDPnk+gPjkb17wiUz3D58UlerDJ1wXDnrwyWaiV4g2CXk36tX87iFeeMcncwSe9UwxX9wobiHujlGAQ6BT0A/X8RJXrMJ4hXFKZ2AVLbbCMS0yerBK1MkXHePX3+9zLGXcuEVKf/H+3Aalvxg37mulvwBHfyCPN5fiPLiU31z6pyffVfqL+h07Bsv+Zcdg2d/guDYP58EVebf+IhjGUjakpls2pFaay9PqE8an1yfMzaxPSMmuNKdkp1tSso9Z5mauThyfvjqxPG114obUYxbIu2OVJXSxfxH/gvh5hp6HVZz60zljKedc94JsLOVWqsD/Ev+SeKFBYpWO6GUIq3BoKhv1wB8d/T5Y5bP9ZZlAYBUuqztglbq6aiv62OYrxuqe6/nYC1aR6f5hlY+u0IdVuC4c9GCVJ4juphOxRB8R4b0XT1jFLLxjlXkCcz3V9HezF7TSfs4Huu86fsJrLl1xjCtBPtC4RYvdcEyLjF7cUj+gwucYi+wLavM62nfsVPuOXWrf8ZxyXLdN9h227Z76jmAYY9mQOjx2Q2p1THnaoejx6Yei52Yeik7Jro5JyR4em5JtiqP+Io76jTjqP+I2pJriIO8JtzwsJG455FaHnoJbpP50zhjLOdc9EVxjLMAtDwmJW14XjFv818sQbuHQVPbxPYccOfde6LP9ZZlA4BYuqzvgljmrq61m4tUx03Xjlm+84BaZ7h9uebhSH27hunDQOwf0AJ14jPhbBjkO6gm3II833DJDONeoyLdIagir4L/tjDUqrvM+sAFXLOPabpwNn3wltK1b12IfHOscGTe8VPJnx9JvS3z7GapMQPwMtazuYK88ZzsnWf+Y6Pce7dWmpvtnr6Ou0feeCNeFgx57XUy0lU7sJn6A+D41v3uATXmz12sF7HUR2eccstabyauoLWW7hB26xqFbAfcZNNgAx7TI6PUZnhiwNDTWqQY3nyGesFkvwmaEwQ4RFjsUR9isF2GzeMJmyhgTxpow5kTYLAHyI9RyXX2Gw0L6DKfd6tBTfAapP6GxziI1Do7AXK/PAF8TPsP3os1n8FsvQz4DB2p/nz7kyL13qm8MosoEBIOoZXUHDNJccVkM+r/nyXfQi0FiC6WcOwaR6f5hkKPDdvvlM7hjEK4LBz0Y5GEhfYa3hPQZPlTzuwdUwBsGmSNc1425ew2trewjuK4d4zTXsU/GKTgfaN9Bi51wrHNkzsRNy75dcFbfATKB8h1QVnew23vWVluhb4GYo0j0aLcD1XT/7Pb+S6XdQt868s4r14VDIHwHtBvwHT5X87sH/3yH9v7CufAdzmYDHNMio3udxLi3gu2d2CCZb6gwbkhdGVGe1hI+Pr0lfG5mS3hK9sqIlOwKY0p2vIkwmokwmokwmmlDarwJ8iPUcl19B8ThO9zgVoee4jtI/Qmt6SxS4+AIzPX6DrgQfIf5gn0H//Uy5DtwaCrbvuQVR36/rT7X1LNMIDAIl9UdMAj7Ds1r9PsONi8YRKb7h0EyHP75Du4YhOvCQQ8G2U70H3TiCuLvG+S+N54wSILwvU6i/ZpOd//BuV7T07rOc+1HaLEZjnWOzJkY6q3PGn3Wh2UC5UegrO5gw0frqq3QvUDMGRZ48f9lun82fGSkf36Eu//PdeEQCD8C/Sz8COBKTzYc7H7E2WyAY1pk9PoR9QPSQ++uq8HNj4givBZJeI1wWQvhsxYT4bVIwmtRhNeiCa9FE16LJrwWTXgtGvIj1HJd/YgFQvoRD7nVoaf4EVJ/Qu+uF6lxcATmev0I+A/wI34j2vwIv/Uy5EdwIJ098LKj970Gn+M4LBMIDMJldQcMEkg/YqgXDCLT/cMgM36qbw6C68JBDwZ5nmgNnbiV+AcGtd1qX7wSUIY3DFJN8XLyGeYRzaZnCf/BRkgEO+AuUp5pjVginGuYXH0H6BpsgdNxzOmuvgTLuLYtgfIrtNgQxzpHxq0+Uw47bvg2wbdNqzIBsWm1rO5g0yen3GaFLn78mv49cEd4GRuQ6f7Z9JCx+uYnuC4c9Nh0HdH/oxO/Iv5X4vep+d0DKubNpmdQvJos+GbqseeSLWN3a7mTdXs/H/rB9gkdY9vmMYFA+xtabINjWmT0+BsELRzj198d2otCDa7+hjludYI57kB8Q6/C+OaEwvgPLYXxdb0PEK1OqOs9xvyhpcXcnNBibujVYjbHjTFDfoRaLvsb+4g+ILrEIPd962n+hlN/QvMWRWocHIG5Hn+jkeh9ouEGuS9PR/Uy5G9woHjZTx2j9y/z3f6qMoHAJlxWd8AmRYeKY9CnBmLd9Y+9YBOZ7h82eWOyvnkLrgsHvf7Gn4i+IMIeu3hInrAJyvCGTaopPpY8iyoFm2CeQr7tiWeKfcT5qxuMU0DQFVwHdgCMwr4IOI5xzt3n4LxaMUwR/Z6BHvuXDtiQGrTI6MEwMx7ZXvbBhi87PHd+4L7xSh80kOI2Nd39eR5oqSmdOiGuEd+ccu8fuF2oEv5hE619xvj7DrSlInjrMyYIeU20IQ6iXcK5j1uxcX1kIPd0hq4MMcg9ys9l269HTzK3/7Ysuiqiw1jlbHryyJdH9z765ztLB69IaPCkJ12pE5VENUS/F06dyDduiLwmdnbA9tHsjjpxLtqOvetvL7Vfdbwk2HQC7QTGzKAT21Q5tBOB3LusO+rEu3+2lH/9yi87rZ0YFdeneHTD9MbPlk0KOp04YZB45koSSDJIufm5CcreMT9kncj7zFJePyCh03QCIfofMxrrd/TxiDG6WifGCqkT96pyNbktUVgn90PXiScHpHSaTowbt34vdGLcuKFBhyegExgr8aATAZvb7I468eJDlvIrIjq3nej9wLLGNX+9Pej6jv8xyH1TR5HA46rclNxPomqyFvyg8cS50In/XTat0WKZXhqM7QTrxDFVDjqB9zN/yDrx0YTXysavX9mpOlFwFOPjq4Ku76gi+pboj0TJBik33FRoCeQ4NXRiIkVGh3UfnSg9dVcZr/3DeoZa3Bt6ruepEi8fu7OkbFt6I/i6dwsa1146tWRM0+DGyXMvUPhPL/y+GHxizM5inAeHPPjXNyco54etNSry4MgPjvJwnstffP2qkrGDWhu2v72uGPybWIPCUYc3Yk8o/LyL31X4oLrhDQkXTS1mPv/lxxrmrVnfxiGzOzYf02EKX5ec3ADeeFmfhsLiASWTb8pqqJ19gcLfuHeIwiv+WKScB4c8OPKP3LGmjf8zbluDxbShjeP6W67Z2cZRP/BjMScaci7apPwe/l3t53uUj8fLIJPaDu403G5JsjvXPZ58/0gr65hWGyoQ8llDHuHI+ycVzrqNdE/zkulC6s0TZDhGk/xG5WguWDjHkZHvCeOLxpuMtxsLiN6LuN24NeJFIqNpa8QY03sRq0wFxlWmm4ieMI4hMppQQddrNNI1dpqc36dfEyGPcU38XvdrYlz5qoidJlvEe0RpkZOEa7vglCMbFraI+6JqFPp9ZJ1C9dFpRtDhKJQ/xEM+jFenGfdH2Yx7owqILiAaSsdDKY+vaw2lcl9R6LnIDxS6L6rQBEqL9PVbCk3vmU4bd5oaifjeoE0G53lcGCrKmC4Cs260hiJzOrlt6ljb07H+CPcyyh4eareCod0SGYZke3in9fet7aclvfb3obYsuNoyu5C2Dz6eaKaQa5gDhbn6qXHUBW3cSdH91gZMfTK17NnagT7nNVkmwt52rzq8NoDLwv1DWZwHwdfagC9bu3Dd4uv61y0+oM7Hu69Flun+rQ04uVTfWmSuC4eOrA2wDqxse6cxn+hRouVCfsuZ+0rXkCB8v9Po/hZj+/ejXkhGG8EE/cKD4zivDeBj1ziIfxfdhFpf9nstJVZ6xCj+2wzHtMjo8aFmZsaXf/L6Ooc3LJIy9MaS7NxejeB9h1obH7+6ouTFQX0bH43PVviP1v9PMfjE5t8U4zw45MEze4cp5yOGftEAeXDkB0d5OM/lN534Rcm+quMN4268oxi8IfLTEeCow+Uvva3wf7zyisJ/3ntAw39XVBQz/6zogYbWjXe3ccisqEtRMAT4xRdENoB//vfYhuPX9Sn5//UJDV/EZSv8+z05Cp+yskA5Dw55cOTfl7a8je9f8kDDT6LvaeO4/u96b2rjqB/4gn1vN1yycJ3ye/h3+YNFkuzh7XwobiurhH++lFaf6TgVtDXeN844njst/pncwvgFRAOJvsmZRrSV6BgdZyQsIHqG6HjusfjjuVvj3XHGKbrGiAQnzvggRx7jmrAp92vCJp/IGZFQmzOHaFOCr76/NudL82GFBpmPKfSFpSoXVGBB+d5wRlWuzTI7N92ygGgR0VI6Xkp5fF1rKZX7b4UGmq15oC/NP1NoU4Kv3/KzvDkJ5+eNSDiVOyLBm89UFCbXvo4nbjP0PJ/J2dbo8Zk8j/WE2qlz3E5ZzJbOHCNt7aDPFGrLurYtswtp+8PC5DpsjCn3NYR8JqdMU9nfvoso/+fiB33iP5YJhM/EZeH+BbvPdOG9gdtD4rdefCaZ7p/PlLtSn8/EdeGgx2faTZREGfLo5C+IX6Q+L/dgEb7XU5/pM7l+P8e5r4QWv8nVd2IZ2AvigfaftNgPx7TI6PGfdl4SX146fZDXOagQLjn3uCTJ3n4OitvNKtE5/tNnVFBtpG/M8VluceTzuVGRi4guIvo+p5ioluglOj5F6afo/KnIz3JfIqqNdMccrXSNtCgn5vgkRx7jmrAp92vCNp/NSYu6O6ec6Bc+x07vzmmO/qtC0dH/VOhPMXNzQRExKH+Ih3yw67m530cvyP02ehHRMqI76PgOyuPrWndQuaY8UFR0tkLN0dMU+oUyJuztt0zLK48ampcW1ZqbFuXLf6omPoH4k6Ln+U/Otibwc06hdurcj/ME45xTqC3r2rbMLpz+041C+k9PiZD/5JRpKiv4IqL8ihd8fwOFZQLhP3FZuH/B7j89+OCEGOD+QMw5PevFf5Lpfu5/s0Gf/8R14aDHf2oS0n96lvjSMO/fAQJ+8OY/1Qis8cebqNj3Bl/wwnupC5R9M2romeKNVDn3lFCKBwa7Z/8JcVQebQh+PPtRLAM7YV8K8Y7MRU01aNtbQ4stcUyLjB5fSih7IzyizEXViWDZ38AQ7jofg/vL9x2/h9uUKpc0l3bEaz9eIOQ9YGPkpuJsPsc4okouSOZTAu6ROW51ojnugKWhV6GlOaHQ8qGl0FLX+wDR6sS63mN6f2hp6d2c0NK7oVdLb3PcmN6Qd8fQsIVEg9x/o9TQU/ffgI71kP03wrHfX+eNw3dk/w3su4H9Ny4ztO2/4bdehvAOh6aypiVjHPlVG3y20SwTCLzDZfmLd7pi/w3gHbRRJ4uKdOOdfV7wjkz3D+9c84g+vMN14RCI/Tf6GeReFReoz8s9oAxveKdaoO+pJpzDe/153n8DlcQDY4INMObhsWE+dsVEkEOdWEYrztG6/4YWG+KYFhk9OAfvspQmdXwPqLO9y1K8a1zxmJO3l9706x97fOeN2wV/MYvWPqMj77egz3iVeI6qm3i/5eq42ID1A9CV7vZ+i3H7trLrSjeG3m8Jvd/SNna2jxrHjQm+x+f2ma5KWGFKSSgm+sqYkvC88SqijUQf0XG2udiUbV5BtM/0UcI+08a2OXy+xpt0DYfZOT63xSiPcU38Xvdroh2fZXSYhxkXEj1l9jVmNsxYkLhKodGWxxSy977ABJqWiPKHeMiH/uAC06TEoaaxicVElxNV0HEF5fF1rQoq94hCFZZTChUkXhYJesrs67dcFrnQbI50mN80Ocze5hrGCvkNsEVCvkvZ0+YanG2PnrmGsFC7FTTvt3TenvCtHZxrCLVlXduW2YW0/auIThDdQjTMEJprcMo0lc06sK5s2qdbfPoNLBMI35vLwv1DWZwHoSe/3/KWR997oJrun+/dvFPf3pdcFw565hruIRpFdCn6QcTV5+Ue8Gxd20AEtuOpAt/7cfW2sV5rYdscAs8dsD/NabABf3zpqQZtcwZabIJjWmT0+EiRgwc5xq8/GFz7cStzBu334+b7jt/DbUOVS5qW/rgz5gwOx7SkHo45L3VJ3OqUNfGrUzaZV6eMTjwvdXRiC9FO6yZzRdqa+Iq0JXEVaYdjdloh746FnyCag36DaL2h580ZOHUsNGdQpMbBEZjrmTOoJ5pNlSgwyG+jd1QvQ7iFQ1PZFbV2x6rX9vpso1kmELiFy/IXt3TFnMHbu4tjlDpNvk33nt0fecEtMt0/3GIf+6Au3MJ14aBnzgBt+j6imwxyX8vb1OflHszC93u57ecMKpXV5fIbI/L7QKigt/kC12OeF8AxCLoIGa3Y5iuh7btAWuyGY50j49b3JI52PHd6v8/6sEwg7JjL6g52XLum2moWgXlXpMXL3J9M98+OIyZIO4a+deR7o1wXDnq/C3SYaDmdNBrkd7882TEq5s2OZ1D8SvI5Zikrmua7zPadaafQrWiXND7vjx+idU5Pi21wTIuMHj8kc/vesutKmzt1f7qWbytLxzQ943F/Orb3KuGfT6EV0/k7p3ct0S8Ncu3qFlXnjhlFn0DiNOjKtVR2pUdd6Txspt9ffT+4vlcbju9Htf9erRbd0ed3HiJdiO6zJO4GwvE3pG0y35A2OjG6z+jEQ0Rr0zeZCzPWxBdmLIkrzDgcszYd8rArlOvqd24wSL/zj4ae6ndCV/T4ncG0lhLfiuq8dx464ndivAJ+58sG9jv918uQ38mhqezVquGO/Kq3ffbJLBMIvMpl4f6hLM6DEKzfiuqfqv9bUQJAQZzpd8p0//Dq89P0+Z1cFw568GoT0R6ix+hkCtGz6vNyD2dbmw+/cx5h1GnkfWKt2s30N5OOsCLfRkh2rvLl2sZwVNTV32Ti9WqwC5Crfwp9RJ0Q53H3zsC3WmyJY1pk9OLbn/38dZ34Ntwrvv2w/qZi4NvI9Q51zVr7foLbhyoRPPh2k0Hi26dUHZX4NnD9AXSl++3J/HDZjE+Oet1PLLT2oyvWrLXfT4x1TKsNuc87+btmbR41jtVW3+s85pnyrYNNLanHjS2pm4imG/Ot043VRC9YNxm/sh4nGmz6yjrP9AJRtRUVdL3GcrqGNc25zmO0UR7jmvi97tdEm20xWtOORlxJdFear7UXRyO+6zPECOrbp1KhlIx3FBqWjvKHeMiH/uAd4/npR439048TnSD6mo6/pjy+rvU1lbvCBLL12aLQd31aFLorzddvaTFdmbbHZE1bTsT3Bu00OPtLY4Qcx72R+EuGnrgnM7c9etasRYTaraBZsxbRab5iawfXrIXasq5ty+xC2j7uPcYXbxJy7Cfkg3NoKrOdf3HZnPs/8ek3sEwgfHAuC/cPZXEehGBcs4Z+79Ql+t8XS4YzI86cM5Lp/vngI27yzwd3nzPiunDQu7/Y+USv0sl1xN9Un5d7sAjf74uNIqSxiPxtvBc/W/Ds7y10PIP3F7sUleT1aq5+t7sPzjKu56GTIK1+t9b9xbTYD8e0yOjxp2ZmppZvHvySwxsuCe3b0xX7M0e086e43awS/vlVWv2nAnLATib5xhwFBU8mfZ6/OGkn0TyiYflPEp0k+lHyvPw5yTuJPicqKPgR0ckkd8xRRNdYmezEHP3y5TGuCZtyvybs8B95K5Ob8nYTfZrsCwc05dlT4/JBS1LyFSq1blGoJhXle8McW/Lnp27Ln526k+h3RHvoeA/l8XWtPVRuSQFoccpEheypGxX6NNnXb9lYsDt5QcHK5CIib/4T2o8rDHLPxbsMPXF/Zm5rQvuL9Yz9mYNvf7FQW9a1bZldSNv/GT2okaQUy4ivMIT8J6dMU9kfmuPLoxwHfeI/lgmE/8Rl4f6hLM6DEGxzmM9vCdz+Yjmqz+LuP8l0//ynZbfp85+4Lhz0+k/DKcMqOrkxTK5p577SNeA+uraBCGzH1ULuzzyf/hYp+4rJ9bKVyhxmDaXAgxpcgIeFtgJr7qArfIzrwR5wjDjS2F/idBDiWv2nqQZt7wdpsR+OaZHR4z+Jpj84JKbxvg5m76BHCQ+8tu3bwf9qeHbJoyV7CYcMGDekFLzhm9UKHzBud+kpOg8OeXDjWHPDXjp/7TtDdkEefBflB9/+6+O7cB5cKd+t3+4ue4pVpk5OqUytTB6atjhpVfripKOZi5P2Z1cm78+enLI/e1bq0cxS66r0UuvQtFJrZeqsVMhzX8O4eZFB4ubvDYHBzUG3p1ibjulZpxURPPqpvB/UeWPv/q7TWmiQWOXfBolVOqqXIYzDoans4oMvOdaOesZnG80ygcA4XNYPDeMM9oJxZLp/GGfq3fowDteFg951WrDFiQb5zfqZ6vNyD/6t05pBsemEd+a3fZMCbxnYxOIaVJTHhBm7eDoG8fsHPHbM+IflteKdr4S2d4a02BLHOkemfX2+3f+y4w9Ln/dZH5YJhG1zWd3Btqsny/mfykv1z/8UebTtgWq6f7ZdtNq/d4bc12ByXTjotW2M4c0iOmaQ/W9HbLuKrHiO8hxnKZaM/9PO2MfAabfso8BGXe3WdY2lq3+DNMh3xJfRugZTiy1xTIuM3rmg8ckvdBhnUlBwJlTFpqa7PdeGv1+yvBFcrsFsjwG5fagS/vklWnGhe/CGCycIec1/UQVmEF0fJvcfgFxTHvBf4LAedKW7rcFcVZ9cvnnwqdCcYbCMxStrMCPa/P2uWIN5MJ/6lXTf4+4H8+en359flH41kZnob3nziZ4m+oKO+2dcTXQ/0cH8L9IP5j+d7j7ufoSucWWGc9z95Tx5jGvi97pfE+33urwrM6bn1RDtyPA1Fj49T2Q9rdAlmQcUas26PB80JAvlD/GQD33C5fmDsiryC7KuJppENIWOp1AeX9eaQuV+oFBR5mmFRFZJAWhHhq/fUlJQk5FYcGXGkfwrM7zNIeLbrninAXN/Jw09bw7R2faEvvEa+sZr58whhtqyrm3L7ELa/jX0oHaRUtxC/AtDaA7RKdNU9sg6c/ldfUW5r3JYJhA+OJeF+4eyOA9CT/bBfwJnRpw5vibT/fPBmzbqG1/junDQM4f4MFEZZfiGTt5DPDzMsw+OCri2gQhsx3ME9g1s/+aj80tFvt9vdF1nifE0PtbqX081aJsr1GInHNMio8dvMtsaHeOTv9KwN0NzPt6Jx1wM3pHH3Ao45mLk8W7lnXlwyIPjnXjMxTy+Y8czkN9BHHMx9cQf+/XxXTi/jbjnvQTb783A9x2/h9uLKpc0lzbinM4VHklNzzySOiljX9qe9JSMPenzsvakV9omZVTa0jMrbe9lzstampWSsTRrX9rSrCOp72VCnvsUxsdY07+HyEiV/NjQ8+YKnTrWOXOF51w/g2yucBlV4A9EkSTwqUG2jx3RyxCW4dBUNrv/q45Vo477HANlmUBgGS6rO2CZurpqK3Ss+YqxurHMZC9YRqb7h2XWbNWHZbguHPTMJzQTraUT+4m+Jfqz+rzcA8rzhmUWC2CZ6fQ3k3CMRDLtkU21sjtZjfKcbe3WO+EBgsMeXN8pAXnCPZzGeTi9M+YOtdgWxzpHpn19tv262fHc0s981odlAmHrXFZ3sPVTQ8ZboaNRs+fp3r+lyqOtD1TT/bP1mm365g65Lhz02Pr9RI/Sib8QvU/0dy+2jjzebH0GxTE3iBUB2Dd0vjJjKPcQZdsE8Twh4rz2kecEOV2rvWqdD9RiHxzTIqPHXyEnq3x88olOnQ/svXQi6tot5gPhIzcb5HzdG6reAeNNzwscnoOudMc9WXYNMZaH9jYIpj1ZItp8+q7ak2Vz5tn2MRifOdiUnnncmJ65iWi6cTzRZqJP6Dg36zjRYFNu1jzTJ5nzTJsz3cfQsY/BqKz2+xjgGNfE73W/Jtpui3FU1tGIJUS7fY5rH40YaBtiBF2VXanQyL7vKDTLhvKHeMiH/uAd4/W2o8aJtuNEJ4i+puOvKY/vfQxG9l1hAlVmb1FooK1Fod3KeL2339JiWpK1xzQqazmRt/nAMULi4RuJJ4f1zD1ZZNsT+HcKQ+3WOW63gvSdwlBb1rVtmV1I28e9B/66iXhKWGg+0CnTVNacfmfZkFXRPuc5WCYQfjWXhfuHsjgPQrDtyfL2tbVW1PHpweN1+9W3wpkRZ46hyXQ/vyP2nL4xNK4LBz3zgXcRQaH6UKZlxPuHefarMVfn2gYisB1PFRhDGycm0X8b8YXKO4RSr0BoH0Cwd5QD/eJxNK1+9FSDtnk/LfbAMS0yevyjzP65DolRgmmv7O7zjuDwmGPZw2Nysj+JXZF1uteKrF7mFVl7LDnZeyzHiLbbeplH9j3da2TfT2JH9h0es90Gee47GAdvFXK+DxYdCBwcbPN+Th3rzHm/c/0NseCZ99si5LsKWQaJPTqqlyHMwqGp7DdXD3H0ecj32gyWCQRm4bL8xSxdMRdg3V0cgz7ytav17+X+Ky+YRab7h1nuatSHWbguHPR+Q2y3kHN+sUQRXjCLWfj+htjVyg4ImPFj7IJ5P57vW9i2TonH/xnH4JjxDGyCZVzn//zBNlrnCLTYDce0yOjBNt9NeK9s1+6wDvc7QsMcQeuPe6Gu3WKOYD7Rd1SJxyCs6mOLCf1E4Np+BX8QQXfPZXsPG5ohgPFlPbBPGeYq+PhS+jeB6Dyxo610b9fyFtxtAi2JWcjfGWZ39gHxRElqHOcR/z8BAAAA//8DAFBLAwQKAAAAAAAAACEAqRvoX4qtAACKrQAALQAAAHdvcmQvZW1iZWRkaW5ncy9NaWNyb3NvZnRfVmlzaW9fRHJhd2luZzEudnNkeFBLAwQUAAYACAAAACEAHY/Dt4QBAABvBgAAEwAIAltDb250ZW50X1R5cGVzXS54bWwgogQCKKAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtJXJTsMwEIbvSLxD5CtK3BaEEGraA8sReigPYNmT1iJeZLvb2zNZGkTVJRbqJVFi///3ZyaZjKdbVSZrcF4anZNhNiAJaG6E1IucfM3f0yeS+MC0YKXRkJMdeDKd3N6M5zsLPkG19jlZhmCfKfV8CYr5zFjQuFIYp1jAS7eglvFvtgA6GgweKTc6gA5pqDzIZPwKBVuVIXnb4u0miYPSk+Sl2VixcsKsLSVnAZPStRYHlLQlZKis9/iltP4OYxB6lFCtnAa0uk8sjZMCkhlz4YMpjEHXEiNSYfhK4UNk532qoMqntSYTjm2wsJliUu+THSOg98wZ67FQDnoA/ta7q0SlTi0agQsSulqcJWKR44GmKCSHriJQtVGAiGXzlQ9G/Rvf2PSEN83ElzbgN0Dbc48IXU9bybl2HmMM4xmxiNH1EffXRzxcA2FxFHmcSXiMsa8Fl9vw6x7V5Up22RwHiDCbqNit5LJ3wPENtD72SX4wdg6mQG2zZ9L6dzH5AQAA//8DAFBLAwQUAAYACAAAACEAiwvPBxYBAADOAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIySwUoDMRCG74LvEHLvzraKiDTbiwi9idQHCMnsbugmE5Jpad/eWCla6G49ZjL5/2/+yXJ18IPYY8qOgpLzqpYCgyHrQqfk5+Zt9ixFZh2sHiigkkfMctXc3y0/cNBcHuXexSyKSshK9szxBSCbHr3OFUUM5aal5DWXY+ogarPVHcKirp8g/dWQzYWmWFsl09o+SLE5xuJ8W5va1hl8JbPzGPiKBeCBMVi0s5gKW2JXphEbnTpkJS2Z91LOoGOsCraE60SL/xONTwseWVvNGgwlnOb57pgCmo8AeWcSZWq5MuRh78qOSyjz+jJ3KHOfAvtN4qf1XJ+yfhyxvrL529sxu8zkb2Rx6jkjwcUvbL4AAAD//wMAUEsDBBQABgAIAAAAIQBv6iL1hxQAAEqBAAASAAAAdmlzaW8vZG9jdW1lbnQueG1s7F3tc+O4zf/+zPR/8PQ+uJ3Oxm9xsrlJ0nHsOJte3i5Odvf65RnFpmN1ZcmV5Ozm/voCoCSSIijL12vu0iaZ2Y2NH0iQBEEQBKXDv35bBo0nESd+FB41OzvtZkOE02jmh49HzXU6f/e+2fjr8R/+7/CjD5BRNF0vRZg2gCtMjpqLNF1932ol04VYesnO0p/GURLN051ptGxF87k/Fa0nZGx1251ua+n5YVPyfh9b3NFKhFDuPIqXXprsRPFjVkReKxTS3mvFIvBSkDZZ+KuESvs+WXlTcdRcxSIR8ZNoHh/mLBORptCUpHEXrW68RwBBA0di7q2D9E58SyfpcwBf9oovL/xQWF+O/SCwvjxb+7McugtVngVrkVd3fHDYMj4fTkJvVVD3+u939w9bxneEOP2WihCHIjnu7UqA9hVBBuFjIJIWNPE59KDDz2J/dhp6D4GYHXcOW8y3hzdxlIqpbGty3D5smV8U9IW3EgZdfpHTL70kBUXRCsi/yREnXx7DmQ7IvgCxMsUpuuBwGAURFCb/Pw3T+Llx/vmo2d1tNm7PTo6a3+2P8bcJLSWoBunnkDb9cJC9HNI/wF8Osp9DxvTDQUD3pSy73f3OcI+DHOSQzvvusN9mID3QOFlK/+TgZNTnIJ0csjvCXw7SzSH7vcHpbpeDgBZnXTcYtIcspOjd/t5Bd8j1S6/o3d3OfveAlUX17hBatMvJUvTuaHjaGbP9onp31DntDLhSit7dbe+Nh9R1rVxxxjDnr7wlaOxh/mcDP98fNYde4D/EfrNxH/pgy8StFz4KMFfv+r299/vtzm6/0Wnv9/bf73U6nUanASM0XHgxKCeACNPpdffx6xsvjBIwEN1Gp9/oN7r0u9vowf/QlePAewSO7l4HhW/lYoBEZC0mCwEl6h8a5yOyQJmcV1GDgM3GeTJcJ2m0zAigD/jXUZNHgKEGgzMUQdC4OmrK2Y+GC+Y1msSPSMd5YwDQiFUC0B46AB/A1I2jeLBaBc9UvhzQrHys+pPwHxeppO20O+3dzp762delQTSNIV/QjZeClYFlotyK22gd4rJks52Gs0EcR18n/s+CqFL1M+lOxKMfEt3NaVNISm9lE1RxfHVF8+5iL5SDYXTWMFqusCV3zysprEHFQYKOFmBHqWpjHJFIFtWWigbX1XOTxeyrXqhRIxL1PjeImjiO5hQyOeha3U4ELDsI43tkgosQkq/n80Skn+22lxA/VSEeAv+fa0FraAVsMvUCAbM5jWJCGaNQVHcSrCXZ6LKCPFlEX+06LsQ8vfRiUEmbdotTyEUEB8ZFOolSMB0u6kcRpz40aBD4j8y0wlnvUKrcT/IeJmmUTYUduX5lcwuZR34MzgX4LHaDirIdQ38RTb988mfpwmZF0gfNphgWBGiX0ZNgdAHZkMQoAZIGyQpk5WsbiUCkzJREPpr0PBsYH55wG6Weq7whGGqe62P67XTmO0TE/nRTYYqD48wXexZHa0eNsFhOP33g2SbQJ67+wgULlwuecxxHS6q0Sqo72DbItYAxlNjvBDidz0GIKsQwCkOAgD/JC0PFjKOwspDzcCa+8fy3YhWAt8ETP3qxTxsSm3wVXT/844MXzsBj56jhTeyHuD/hiMM0qGCl2XwSMQLfr2agd246ruWoSHadsHcYCzF78KZfbCJuZ3gL/ckLvtzEYi5i2DkynQST5y72Hx9Fbi0bY3JsUDPWgafPbJhMdaHQs7w4sMDiFpVaoJd9noxAWyfROuaEvIou/CeR7Z6YwQJtBKfyZ3Ep4kemjVcRTIVozg4lTDARzry89ZpjdgF+6fmIJBXhu/uJLi6tIz+I569RPJPy6FRsynWIO1paq6gIY5UClR95qZeNo7vHAacpgxt3+gR9OnoIhoFfaMcG9OfxZTTbKIAsWNmRDYVewsbdx9ZvLPiDCFawaPpTQuqdN4xWz6CQmbuqUy68ZxFfiuVDpqs67fPtOhDxCPfnqXSCe4af+dMGuuS/hoq5tV9yu6ifcZevV/1el+ynSirxTiBCwion8TqpxOsSilhdxDNvuZTaZ6glWOo0hjiCHD3TmTihMQlFkk0/kwrzIYYAUTbs2iTi3TDorMhPmJlKrsjKQ1vFbGXkggd6KzkN2Ud+AsvAc0E0Rl9alzvw7ETWOH2EzhOM9WhUo+DzJF/YXYgRdBu6NcOFH8xAdLsXyFzciHgpMBTEeEYmgPGPTMANv+DdmsE32KPZzu/Y/yZmw7wLbfpNEH2tIMM+L5VxNVcrUbRs31wWAPSronqg4vbsb+vlihdAA7gryIsAx5fpZ60IADj7GdswDvzcjGn6nBVA3XDKLdM0UJNVwHmJipaiHtg9mCnxhXgSgU29FQmscbis2DQZZkBTY9PydRP2aDZxmMbBIDkPV2tmZgyeIn+GFZ7EwvvCLLykiI7BqFIV4huJFbe5cGtgPraFehgTNac6xMFm5BBeOUoIRjuQ/y66gtmT6dZOp2tsuRQg4y4DTgJwnDE2kRdg8hfknN0kD2Cdhzi2xt7bN+pXgLyAEkAKiP/mArAtQEBeAgPAOSp34HkpKpwEf1kRJYXPC63GD2b/gP0L7lJshUXRJP0usqmkWPzURUb3vMXBV/OTKRjVpxQe2DFHB4u4LUcJGEwpWMAg7JhBCUR+pex7Yw7Q97KPje9RtITB0/cMfgj+pGANKBGyUdQXUenvMv2GmyjeLtH+CiUANwWKVdu0kugrEf/gcyG3Gwg+xdqewdC7H9fgC5MtwIFXMc1O21j0FAyDZTVgoCQzXCLhgIRa6y4P3IIaMJTu0ktj/9uG4kC8OrhsQ14HipvuOjh+K6d6rmKTja07i70ZDjBYXVs/dICK/HV2+vvt/YO9Xndv/2BXnoRkUS0cpsoSdUCtEnURssM6W069VCdIRpVy6T756YJMihxYfbbcJ9ArEPTJoXZ9J+gDgKXg+z6nOuJzOdkVoyO6NDIV5UtAVRUSUVkLLfLaNNB7gcQgQBGtN+Ym0cHjSiEsoIpwQioKAS0XEAgKKlp7gZYbdmE1IEqrDFlo9CHU+nkD/acN9L9voPMSwvaC4qcQKLG1CRzL1IP4Tx7448KiPwixwq0OnJsxruCtmGO0EZrnCBcrAD8Oio7C2CIqOr9nPKONSWF1dT0qSA7RkM4LNYF0iNMZrI0O8heRThcTCLvZ8k6I5jQFkjxYwmmSbKzhp0kqGh7zaM44mAMfCQ5Jj5o3d3pjFetw4cHJqZRspyMPejMjKUG0ohkgvSCaURNMDhGO6KpcSiohMDtlcLcShQtNJYBiwA4pitWFBN4EohXfATqF0FEQ+MkCQ5AOTBZNxvg22W4tTqdtAzWUFqDjAa4Ye1YGxrvwLDjfXeGIn1xfX8ABtisQiz6TbparkYZ5dkPtU7w62NwTdGNRWBUGbZNGn1/9/7iifaPY+wqW+Bdywe5Is5BuwfRaajGchwv/wU8xWJSZA3fh2GrUIfNwoubYIuNoDTGEqTqjqsF6f45pYA8+xB6eNwpYOtN1t4T0wj6ZrWagodPOaGHYndqcjYOMblQOxEQuQJhWAbYvhiNgiAQfH95GXyk7qa2lXaDFoT6A+D5lm2hz0+FKOOIGQ48LVN5E+XzVCpZmDg4UqGZjF6PWlx0996K8WYYY/j2cdMUBrAzZEGrlX0MqIE+ZwP4B1qNFvLa5RtEagk0FIlo/LmzQBaTioQPBHqRRhznW1kHie2HR24Y/hMkUgfg2mcb+Kq0BKfrondF13DlMC8YccnoyhYAkHqUZN6AYj7G3Wjg0A+z+2I85DwQouMO3OwcItK+3KZMVruH0/bvOjhFznqxOxBySRTimwRw1F5NojA77EMU/09EgkYxOOFkHcABus8jvYXCJpC/vksJ3u6I5+hwXNVBxktNVNeVXKYkqhuTOe0iM0QCdZscOO7PYEvETOydj0oOayEZfWRCH6uo4aKxvpklUtEffCxrtUlldetkvKmaLzBglt1m5bVniGjgYOL6N6xDzxVzJbQ4IZq81cJyoHkrOxe5Qn5Cv+KQ6RDrKyOjIYpMALKsSQJoJJ4zS/BrjvlUeHHmcM1qWYF3XJw7KqIasGqfnZrmREHVUyXFuGJyvlzPlcNUsiadS3LK5x2DyktwIamTmx7glUnUVdqJb2WVqprkLtXLs3FDUBnCfi4S7aqRKlKrG1Rs09Hvq1Y3IemVq7anTUwinRtUBa/LWg5cT+9ydRhsh8gO1LL/acLlFqAMve5k1eMqOZg2WIrxQA6ulCTLTrHweoFsR6yBAJ5ZOAHSSDKnVTxc0HAg0jmoWGCRHuiDTKiwEQrXSo3JbkKIupW3Syy/ZK7Q0+WqYR4DdPa+jVRjMjccpUr90HV2ndF0aPdJTT556HBQ1LHrIjBm762EDyDb8l/vFjGKY/jEP0P1kBlH2l1mI4TezCN1/ZgCmH21MA8OZZVglvfCnnQjNr67EFOsm7GkYIHkznJ/NYHV/WyOX/dQqBxAW7+JyA25bXL7fVVSmvrl9+X0NtAn6am+o15unp69lvytPzxgnzVmiFc62nPlwvzl35u6o5Av+Fzt3/4V+izEHdGdId1UM0H/UO8nnmMokQOOq9t6YWqGtdDYcm7AFHHTXSt2oLh+iyFuUj9KX8imqiwfxt8HbqR2yf87uB7ejP7X/rNte1afoqmxTSykEX3LnVbnFuRxZUIp9VvkePc33gKswkN/o9j5setn/gJNRHPws0ASf0JMqPv2ewk7lnLF2v/TDnPFam8edOlylXWUtHnu7WYuNu7bGqHqxR3RvI198X1qlo7uFjtLzA9wqypDLGgr6rmkofNI0tAdR49yaSdNLXiUf1pQALOtFAqNgUqycA9Msf7c/x1/d2pD42g3Xbk+nvnnFem+8ecVNt7uNav4W8uS8nsLx/m1Dnm9eMWQfvIhXXI4uuxdmZuXdwoNguEuehG69bIdBp9p+gXEm/nv0B/J1mLkOzPQMRMaMa8HGAeRVZF0LZougM351PZjBsNeEGVzpujCDsK8NM6DS9WEGwV4jZnAvcZ2YqRbWVHWtmKEz14sZFHvNmMFBfpZXvm7MwKxrxwymdP2YQVjpLwyG1gbzOjKD4q8lM0AqrnRd0VB0EyBjQBUAdV3RAHHXFV3SlO8NunCly2MuGHik5jVGF9C64MYAIQe2hnjZzcHS9Ua+OHSnEUgbWvfeSStSu9FWXSQA5XixoRU5sKXrj+4CqRtPi2uQDJAK1K9DVmL0a5EMkLkeqaG0s65h3exAtyOqwj5mYjU+km5DyFjLGNTEy9cZlTnIEDFWo9Je2SOj4kSpXb5byCQPMlWUkggZRJEquHarnjupkCnQTi5kQNThG86SzWTDqsHjMg9r4osO5o/squzxNmdxELPKzuJILnesgSGXYw04l1U0DD5psQY9K/b3FmvQRuTuw+nl6cfBxZ+MKKYZeKgF18/mNjK4IhO8NHlaVaEhbDKUSppyT5+8JDeCWm4naPGCqSqrRSu6U82zjV1UFa7gpUFVdGROuRlU2spGiSgUpgWbNjJUnPbxAlUc+vEMWpO36Frkcgc7+Jq0tmxRk1yG9ce41eg05tFu23JZx4OuRuV1VaSAbWCtCIts4OQSwjawbMgLqw6S8GXj3MwzmdjcJJ4NdShnY9KrNjNtUZcuon5iuFErdCG3YqwZaOFbuSlHiufK784Wx2AbW5dzqCtZtVm0u1n1eGT4pZCNdeJJHglUIm1CapK4odZlXsaPo9rLl3pdONjBmJd76/VCxlYsdvW4rEvA9disi8HbsW0xv9QV2C1Mu2Kq3x2Kp7iLu7FRiqe+vSwu5pZ3TPzUK+BbNN+427uxEfZ9380s5TvAjC7L67ZbWTbJot0PrikI2mDtzvAWXLApzq8L1+RCs70Nl8oNKBxNGnj3IzKwgs1P0gDvxcrb0K7FqWpx+1yjPJSulBHBFwfi1cHZeRnuFtvJGGzV1RZetdhMwmAtN3VI+fb1Xr/fMwIb/F1vCwaWl7/vbSFlKMO8XW6BSBEhrzh7tqdFL5pHjagDpJBZBdBxB7yo+d+MIvGGTenk5pnHBZgcpaqbqYxN+jXjTMbTmuDxTkx1/8PBJ8fosLdfN44/breLS7PFiv7vh6I0vda98a2uL24UPt+IFJczt1nIs6cEIa9xG9NZq4y25be/9YfuW3LU9D80EWjKvqD4XS0l6BWKr2c0vULx8RUxeYD+FYrff93i771u8fdft/jvX7f4B69T/F/3+QfONdJp1F5waXtbma0l5QV7/21l/i17/21l/i17/21l/i17/9WvzFVXRSAIkqVvFCExdwqHA1JO43g9V0ZqX2piIkW/amryVknRdu7yVux2cjOboGUmOX83px8KmVGgSF7WK2JGfzyBF/o8xviEIAo5/PHPf+kYKTAvfkEqdxl/WUI0G4J+S4xuviVGqwjLq02MVucur+uAS7+iodqAcWD9eItHMYdbPLB8z5hHaQdb7MFXceKTpcYBSAtdw2lkvcd+ahvi0gVm9iymhFF51xXlvNjpC7wGV//R+/V/+NSlNGTGuQmqYjnkX4X/Fc9ZDJ9R+wBvGi5es41vHs69R1Aw+N7tOnL0st+Iay7M5ez6O3xypP9er1N4zQ+kZi65J7zjU4fhTYFPvmDejDqYzeCZZF+411R+BAYXDZpW8RRkzQCAhxB56+J1QMXTjjVIVlbxYGR8xHJmJDh41pQf13BVp3geslZcRp9M4c32ytbkzg9WBukS5ff/qVel4xgeH9L78S7gefbZn+epWOavkSYavqoI3kHdbAzo2fk0clmeCP0t3yl21PxxLdaQkxB/ETHxwRjS28oGMb7DupVEQXh0f3kxDLwkabSmy9kRSHgNr1yDR9NDo4inqBzcUq1y+PSfqHwIr4RKZe0tqk12Az4vnaJbcxGfh/Oogbla8GwGeIw9jRd+9CD/IsaFwPqS3r+NCkV/0FNMoZs60IS8TMkmH1BVfOfj27h7/YPu7vuufJ98Cx+FHUEfrfFe2PG/BAAAAP//AwBQSwMEFAAGAAgAAAAhAAKCFBvUAAAAZQIAACQAAAB2aXNpby9tYXN0ZXJzL19yZWxzL21hc3RlcnMueG1sLnJlbHO0kstqw0AMRfeF/sOgfSzbCSGUjLMrZBvSDxjGij3E82A0hObvIwiFupTsvLwInXMF2h++/aRulNnFoKGpalAUbOxdGDR8nT9XO1BcTOjNFANpuBPDoXt/259oMkWWeHSJlVACaxhLSR+IbEfyhquYKMjkErM3RWIeMBl7NQNhW9dbzL8Z0M2Y6thryMd+Dep8T2L+w/bO5sjxUiobPd6cHCDQpp5DUWoUysIweaCi4ZnXldQC/N/YLmFsXxmbJYzNK+NmCePmx4iz5+geAAAA//8DAFBLAwQUAAYACAAAACEAj8OZ7LgAAAALAQAAIAAAAHZpc2lvL3BhZ2VzL19yZWxzL3BhZ2VzLnhtbC5yZWxzXM/PCsIwDAbwu+A7lNxdNw8isnY3YVfRByhd7IrrH5oi+vbGm/MYQn5fvn54hUU8sZBPUUHXtCAw2jT56BTcrufdEQRVEyezpIgK3kgw6O2mv+BiKh/R7DMJViIpmGvNJynJzhgMNSlj5M09lWAqj8XJbOzDOJT7tj3I8muAXplinBSUcepAXN+Zk//s4G1JlO61sSnIp+cCjHbtGuU8hyyY4rAq+E5dwy+B1L1cVdAfAAAA//8DAFBLAwQUAAYACAAAACEArI+QTQIBAACEAgAAHQAAAHZpc2lvL19yZWxzL2RvY3VtZW50LnhtbC5yZWxzpJLBasMwEETvhf6D2HstOy2llMi5lECuJf0AIa9tUUsrJCVp/r5L6pK4uLnkJHaE5+14tFx9uUHsMSZLXkFVlCDQG2qs7xR8bNcPLyBS1r7RA3lUcMQEq/r+bvmOg878UeptSIJdfFLQ5xxepUymR6dTQQE937QUnc48xk4GbT51h3JRls8yXnpAPfEUm0ZB3DSPILbHwOQ/3s6aSInaXBhycm85AJtW5dRUHqxv6JDYRMcOs4JRKHgvkPPIxW3IwPkugKeRc7N4DVrdBuXfnbnFc85RkON5Df30D3qmPmpba/CNzM6hzzMtyszV43mN0/gjVr87yMnbqb8BAAD//wMAUEsDBBQABgAIAAAAIQDSNcS8qAIAALwGAAAVAAAAdmlzaW8vcGFnZXMvcGFnZXMueG1s3FTLbtswELwX6D/oxlP0SiU/EDlIbKQ1YCSB7aTJqWDklUVUIlWSsuN+fZeUnMiwm96rk0jODmdnd3lx+VoWzgakYoInJHB94gBPxYrxdUJqnZ31iXM5+vzp4p6uQTmI5iohudbV0PNUmkNJlVuyVAolMu2movRElrEUvA1DTi/0g9ArKeOkiR3Ko2hRAUfeTMiSauUKuW4pJiKtS+AaSfzYk1BQjSpVzipl2YaqoikkpJKgQG6AjKxKZzpJCOZxS0t4SIgRfhYQZ6rGtdKibLdxx/ydPkcniPPIYLtIaYGYdjVGMSCfEnLuhrH/JYibr9dgm9PnhIRufxD1z/dfK2uRA2hnxjgs9M6QosQbVhTvqyW86rfV6GIMReHcNgK/s5XO8ZqE9NwoHpx/8aN+NOj3/TgmDiY5vSXeYcQ3YOtc25DYDYMo7PUGcRyFUT88EbHIV9u7LFOgn2yI7wZh9CHu2eLO/gY0rlvzLAz9OxI5kXSLXXYM+nHTzWUPY79huaugpeskuweYSr0hfEOxlGy9Bmk8nAMep2NRCInlmEN2vXOWjbXYGbZfMMBrI96dnPKcvTC94LRqfOlKMznORPpzDlWBjdgCTKbXd3ezU8hJXRUspfoj7MP0ESfnhRVM747vNIU6zHLfJraELwX7VcMVXxf7KzpOGYS1+4amGo0w7RR0ZbZWzkEdub2A1Ayf8XJGd2BdFFtnisPgo6N7EWakLO9YcI4heEtHQOO/uTaMou7BQlNd41Djia3cns460aZyoPReMt4098H2FYrEd+CIx1TpePetqgccX4u6YTjYta8GZ5t/JLeUlHfy8OZii+3WGhWcMqrGp0t1vfhfTDqd2EmDvLa7cALtu2FeSjOlhSOHbJUQOV3ZYtjTFqRGfwAAAP//AwBQSwMEFAAGAAgAAAAhAH2B/O5+BwAACyMAABkAAAB2aXNpby9tYXN0ZXJzL21hc3RlcnMueG1s7Fnfc+I2EH7PTP4Hv/nhcPwTDm5COrINDdPcHZdcrtdHxRbGqbGpLUJpp/97d2UbZAyXXHOddtqYAUvr1erTaiV9Xs6/+3WRKA8sL+IsHarmmaEqLA2yME6jobriM62vKt9dnJ6cv6UFBzUF9NNiqM45X77R9SKYswUtzhZxkGdFNuNnQbbQs9ksDpj+EINV3TJMS1/QOFXLtm/yVutsyVKwO8vyBeXFWZZHlQk/C1YLlnIwYvT0nCWUA85iHi8LYe1NsaQBG6rLnBUsf2DqRYVTmfhD1VaVd3TBboeqv0kpQFSCLE1ZwLNcVSaFtyp4tqg0zFL3UVXwkapM82yx5EP1momOU14oVIlYynKaKDJK5Y7xNWOpEqcFp2nACiWbKXzOlCChRcGKMwACoG7i32AUYJkkcZQipKFqqcpbyoO5uynrMDOoersMKS+Vb9P4lxXDkf5uvrYI8d2BZhiGjT+G1h85BpR6Rt8b20bXtf5QFZcWpX7XG/jmYGRoY88ZaI7tW5pru33NMawe6Y5Hrj/ugv6Ucpj0dJzQCOYcEFzGYcggUKBYBsTHzRLAdB0TXD+lEbuZM8aVqzhlN3yTwCPQHMdJsqt9ZL/ybe3i3GNJorwbqtj4xzjkc1X5NFQdVbkdqpN3qt7UuGRxNOdHVW7m4fr9bFYw/lnoGGem1ZVt7BR+EgpaS0MMIqAJE89hSlo4/JyuYXncPEkJJhZdVKKRkchWDmtM0nl8F/OblC7bzRHmVRb8DCGYwBKoFBCs+/79ldxRremvlkkcQOx8Qfd28gnW7F2cxHzT7hOddxiqcOtdguFI0qjynSGjQA3hsTEt1x9MsikrVP64ZoXsMqFyA0sWlj1GyRXdsBxC7TpbK5PPGF27+MBlIkB721UuRY+XJbjsoVur2wwJTvkKthN40kAsPLENA8nSNI/TMgQbAyAAEnaglh2cpbZ0O6sNG98nq9JCQyq2qDR+EFaOD+5jTlNpHDr46OJcr5wHJRHZuDwvznEjgU2dEOISMiITj3yAMlx+RiJCxvAlHv5gjVQPR6gsrohMqpJ0E+Z2dQ+K+AUToCzMiLsnyhF0Sd76ZI0K0375Jb6ur30dRfr69ARKUx1qINVB43nXHrrnGSPkxdxf9+D/z3cYwV+8XoE33S9qVA9PT56i9WSdw+bWw+G5LraI82sGhOZNHA7VfBKKTUkvz/0G0RpsidZ1tkpDFirXsGXT8iQ4RrQeUW0QLTgcIiVLeSa40xLOvg6WUmVVMCHaAIuAI6H4ZUWBCiqguAAOO9uIh8WcLtm3YlpGv+8M3MEYqJXpPYFpjQaG6XdtUxsQy9Ycq29rhAxszexava5rmtbIQGb2VKZlvfCsBimsaZRMGhrHeK2AbO0weXnhWXtU7AbXyw9ss87ysCQUfJ11ijhkRSfMVncJ6wQr3slxrUMJ3rvCziqN8fUNGd0L0fjrZ2PVMrTrz+lJVQKmdOAYAWl7sx+skTjtXwG2b2/49ldaaJgV5p5lAczt2jfQfWEUDQwNC9KTAVDIo36Q9ERxh0F6AggmUrVG5zx7eoWBv4MGHYgQaQBQxJ59QcYDLF7ijytI+F4d0O1JHq3/hMa+31mUe659J8uA7B8hGpbYRg4QDUhGiZehoXoL+Z7jSZz200fohELTsGQUHN7WkT/QEASQqvhWvMGybXvgWX2gDBbmZR7L0PRtYvljd6z1XGOkOeMR0fr+GGjHiIx6xDQ903vhDZgye8nP1Cm0fyo/s+t/nzfgOuykkAPN8p87S5bHyznmSDshe4AEMUqKLP2vcwY/XLu22Exxb6wuD5Ie5XYMAukouMekh9iQa024TzAtsp8CaVjYKmN72GzbFuxDFnA73jYVhfn6HoVrbydGdJNInIR9IqPwJp7gGWS6UyYkJqUFX8awbR/JgyWHLdzbCEF37hsWhAx+GgimW0bTOJUFAmxw0EIkw62ZUtV+OxWTWHz2501u+kgZPNYYbKWO2FotEYWMVSjgaS6Ptg6UgxbA603dVh9tgRhszRnIJWLALESfzOD3UP0VceGRYKKAVqAD5HUdD3nAIEkadfAwmkXjGRp/JXro49BfieRHJLxQjhqEYE5IHASm1zCPcQb7GGcw4R+IijSMkgT+OYIM67GcxEGFR6jDtyIImFh4PegJbtB9CkHo9kZWb+xqpvXa1ZwRpCSI6xBt4L42+oZj257hvyQWXgiC9M/Fv48g3NEiDjoiQdeJWLZgPN90gjgPVgnN5QxDJ3ugyX+dKbR36H3J9njaf/D1dRdyDKcne+fb9n1XOiO3MtiF6zNKlsFJXfZ+33rLQ3nJEXALry8Qii29ros72Ki3+FouzIlzppbU9/KUqWv1XWQ46kp9t7f5jQY6sNAcg9AHZHgGNS7IArSlgFZMxZ525bWGVLQHE/KYtzIQeyWO0xOnao26z76+YaAglgZTaLinUdm4MHQYxgwDZSyiZYrB4QpqImiiyD6AOZEtEBJXjFvU32NfcIjBBUQB3I7FSyz6aAwC5AO5qpnDrufGzG7Fx5iC02AK1f8ZxcWfAAAA//8DAFBLAwQUAAYACAAAACEAbl3n3gsJAAAjJAAAGQAAAHZpc2lvL21hc3RlcnMvbWFzdGVyMy54bWzcWltz4jgWft+q/Q9MT9WC08RIvsnuaXqKAEmoJZfFJJM8bblBCd42mLJNujNb89/nSLZBwoJcNrtbFR6SwpbO9TufdE7y+dcf86j2QJM0jBftOtZRvUYXk3gaLu7b9VV2d+jWa79++etfPp8FaUaTbrzI6CJLa7Btkbbrsyxbfmq10smMzoNUn4eTJE7ju0yfxPNWfHcXTmjrIQThLQNhozUPwkU93/spqeyOl3QBcu/iZB5kqR4n94WIXjxZzUEtCEFOK6FRkIG56Sxcplzap3QZTGi7vkxoSpMHWv/y2Z8FS5oWv2uDXrtu12vjxyWsOkni1bJeG4YL6mePETwx67XjMIo238b0R7b+9uVzl0ZR7bxdvwwXN/Xadbtu1FvS09vq09/CaTbjj7G4+JSG97Os+nwYT9bSkQ62HrfrXMQB+yZoyxfmCsuFudDtlZ3FfUS5JiQKOI7CZe5F5XEhVVw9omn4Oz2LpwpJ4x/Z82zOF+bSD5GOTVf8eNxZvz/ujEf94waDWBJHqQ648f3xzVi/1USLQNgmtiBs68OFnQ3OG+P+zfi3QW982hjPKEuo1swDauj2tkAhK0g3iPSBAoBcMGmn/cHJ6bgU1ywN2RYmpxLZW59cXOHEds5AppxgZaxglTrl8ELMOjN8cNw4GoxvLkYNnvgm+3mrNXHzEGsH+WIBXaN4tWC1X4UNLyh/Nv3uz+LvVfxefP0Xq67qC3DnW1FxUDhSLfg0opNMja1B6i+C5ThI7mleLRJY+w/ABr2vUTcKJ98KW5mzF5f98zzv5w0pLac0Wo7jZTjhi6/D9J+Xo5tbfTKb//Szg2xPKuhuvHxM1mW6/lZrTLQao7HaWUlztW6cLOOE05Feq3WAJvjGtFYw0VRn0PXBTSAsTiEJsFySPQJFjeLv7Ml5MGeEVXLMdRCtylpjLp3HtWMgxFUUiEVwmcTzZR4Y8fEw+Eoj7iKXKiSWyQiqG/w4yf5OH/kWUdA6l1LYBwvG5V9VrHJNk/AulyNt6QVZAEz7jU6LNAk2DYPF/aDHn9PF4ZUvGtANIrqYBslmVwvitQ4aoIoH/e0Dt5YsGPrOgne0CiNe5G+OurXk9xu8URzP3x51XOr7DVqPLoMkY1e4tw+dIPv9BpCfvt0oSFNlAOHOtGBnzEMIJ0vtql33xyORTZ88LgT5/90gSheA//GhwZ3kJ5uK+K6gdXh97LjYdxi6VnF3kS4xPFTrsxjuBJBI1kAqsYml9mULidKhLoBQlaDny4kj/1Rpy7+PjpFlmj3vsNsj5qHVP7IPXdNDh65jm0d920OG5fzBUXByBVcTIaH7DIcIDOk93Fe4B0rN0gVTKUsZ6aIZApHFbRFU8aZIUFI0c/uaxlt+jdrVeh02oEk4u+hdDa/8Bm8JmthFvf6J1mY/WaOTtxsto7lzpVcu5U0WrGQ9WOfIbwi7W92LQoGmfeTvOrCGtanaQbFNaxZ7iu8tn4nhS/It5fPxeqvWhD74gOsSFh+AXr6WKxIUsxe5Oxr7iDm+6T3CeALalLKxrvSi4urbcvWuuFZ267fi/ht4z7XZvCVsVDvfv0XZL0g7MLSPqpf32S/cQe3A0j5CXqDFOw2nvNVtAv/7nbN+wz/tXPZZR1R2rVrzwwdNa9pNJHl+W9pi7LJFv91rDbwGe4q4gkGio91gcbJpatQ1NaLLOA15l8R6dbY954ZdZcHPO045rDIGN5C019REmWl1P90LE8WoBJ7mBSV1OuqWqbPK4hNaoEoMisgB1T5vn++zIAkmMIsrSGHb9W4cxXnb9LM1xRQHPKOAj+HVWQNmGGf9686w8eEomHy7h0nYYso3AChYArGBmoCZXn+z8h8r6LH5MIzNyPhirUlsrbmRNWTNMkgQ/fNhbFTUUnWGATeUy7Eyx5WxnVOO7XJu/Y/GdmWy/RmlmW7/xMtnewQDI60iuwWjlqvVEOEyCkctD5nExSaxgT9N0+KRL7eXyuRFYshyBVwWlrYWmqW7Uz4mKrnfsEClhxyXwBmGHcK3lxqlgzPfJ3uo9oyzbu6ZaOXbzQ95RnePlEb0js2H4F6xwRL36+SqM+o1ZALbPbhaz2+4K+tvbzLNOaHxnGbJY71CQOcxq5Zq9M5jNndWPV/P1SRWOY/ZHEy1ntdlLwmEWR1jwnG73o9gxpeCEkYNWMGKcMkhyDOJhw0LbjxbaEEmRshwseO5pilmvgQNgMxxMSLYQjaC4uZJWWNIfivu7+Ru6CbBIN/wTJjmI9cCrAMf9IYSZkGFAzhGnusiQ7o8HRVSZD3Mio2UZxjTLcRUY7ERsy6gnSHJp1dI9/KPaxsuQYRV/kbK2hh5EYvMHpqXoSVm8f8JrRGNzuIHOo53g4sAsLCDIW+ea2BkiQgoEUQwIZ5BXMv0HI84fM2mFQAIgx5WJ6UeQwVi5Biu6WIMhEdcTyK5l+jprr4e0d9LTWZVk8oBwKZj2gQbHnYsgKq4poQ58gzbBNvAToRsMFVcVKJYFYlyFFxAVNxW4s0hhgVnDAYzLOQ6vEz3BdB6nluGY7oITLYwMpFhekz1PrF2VayOHURsYrqOgxDawSAv1eO8Uo/leBhb2DRN1/bsJ90hCjUGtiwHIzjZ2dlOpDO4hNkL1bivU/NUMjyFWIs4BqQUoOpCBAgRsVRY/5RYrLpXP0OubiCPHRPwxz5INyGcxLfBJBcfFmmuvNrYEHniWdCmE9d01HxiGAZwieW52COeshj3GVzWogFHng25hmiBJCLVa3lcWMwbywFcQf1btrSmLM6qNU+4raI32/A8iKAJRrnYUB/EqgiX5FGykM3I0TI8F3gZE1uiybXjO8NXur3PmrXbcvierDas4Fp9n6LnAlZBdroLd2OXGIYFvObZcOUR2tDnylWx3TPk6kAPrgfABHDZgGZOIduIEE87rKI7F/5MSeCPj+CHYUmwE1joZWpUdPe0Gpm74fb2xBmBq3SnJNEXy63ynVKu6qjejr5MQ4aK8V57rZHrUbKwLD92mCPiItdAhJW8iM2yAD1EGIzg0gw4sgAhAn7LAlTdJXJPN0OUFm+64FTnv+EfZKoP5P/0+fInAAAA//8DAFBLAwQUAAYACAAAACEA96Ij3NcAAACRAgAAIAAAAHZpc2lvL3BhZ2VzL19yZWxzL3BhZ2UxLnhtbC5yZWxztJLNasMwDIDvg72D0X1WkpYxRp3eBr2O7gGMoyZm8Q+WKe3bV4cOljF6y0lIQt8ngXb7S5jVmQr7FA20ugFF0aXBx9HA1/Hj5Q0UVxsHO6dIBq7EsO+fn3afNNsqQzz5zEookQ1MteZ3RHYTBcs6ZYrSOaUSbJW0jJit+7YjYdc0r1h+M6BfMNVhMFAOwwbU8ZrF/IcdvCuJ06lqlwKevRwg0LZZQlHWqFSEYctI1YDW9xLfY6tlQ8D/5d3K8u0jebuyvHsk364s3/zIcfFI/Q0AAP//AwBQSwMEFAAGAAgAAAAhAOjMYbl2CAAAqTAAABkAAAB2aXNpby9tYXN0ZXJzL21hc3RlcjIueG1s7FtbU9tGFH7vTP+D6s5UOHVk2WCI0zgZY2NgCoZih5CnjiLWWBNZq5FkEvLre/Ym7WpXjiEOpZPykrF2dW7f2XPT5tWbz4vQukVJGuCoZ7cc17ZQ5OPrILrp2cts9vyFbb15/fNPr069NEPJAEcZirLUgteitGfPsyx+2Wym/hwtvNRZBH6CUzzLHB8vmng2C3zUvA2AeLPtttrNhRdENnv3ZaK9jWMUAd0ZThZeljo4ueEkhthfLoAtEHF3mwkKvQzETedBnFJqL9PY81HPjhOUouQW2a9fTeZejFL+r3U87Nkd25rexbCLLtnWSRChSXYXwpNt2xoFYVj8mqLPWf7r9asBCkNr3LPPg+jKti6Jnbrsb7e9t7PndvfsprLrvbqr2+7sdHdaXXnXu+A6m/NtHXnhCAU384ytyM9PsJ/zd509UGfUsymVZ66jUGA7mQxkiWxkVMs7+9FNiCgrV2Y1CoOYKao95lTl3RcoDb6gU3xtoESM/K5QyHVcd7v0Z1tvwbJTKuX06OD04LJ/slUrXqw1XKe9cz6tyzz/Wgb+R4oQwZRq0JbXD27BXYYfwkEI+7iCxAxn5wfj6cHV9N3xeEshSJ1iEoeBwfJHKIynOA58SugySP+efPAcf7745dedzl5Hsf0Ax3dJDmD+y9ry6xY5AtapOCLWACcxTqgrO5bVBxejL6YW9+Jrh2g0QT5xduJ+b8G5wbUv8Cfya0A0B7FO0CybREEMK8JPL71wKcAg1t0/OzuRrXOe4EXMFCWPm0BRI3tBlNg03X2cfQ9xgezGxcVJhBI4SR+PcBJ8MRq3RV33XsbNqV6iJNs40WHg3RiJQlS/pxtwxzqbzVJkFtR1Wh1KdnhCz+7xaIs4qANuLVuuQUPUc5I4EhymDhCmWDX0/UT88nYBbUMmQHyorhzfVR4tOH6TLlS2XAbux2VhBae1ReN07idZfzw0W7pkfuJi9SoRDeanjl7en9tfh4vQ12ApHnDd6usDJXjdzxwGrctKCFzKzwXDtfGCUga0JrWS8ZjBgZDrAFOUbfJ4rgT2Pg3xKdAUsZ2eIZraiqh+iqIlzUDshNFqRubHqEjJrlaTlwdz5H9E13xdknMYpN6H0LRygbzrsyi80985jkhVB2/RpZbMZx/dBNFhgpexvjYK7/AyG8yD0CDH1LsZewtGUSG4zDIcjaDCowTlpQlOsj8Rk488VzIZoE4CRZUVf/MW8R+wxyKbrCm2aLIjRUJNW2JP8iNQyryN2gVeRtfoutaoESI1xZ80WCYH09HWIcou0Iyf4xK9emN8Nq1YUkj/S5CWikIVUsUXvgOkNHlUYTrFFLrYortUUPU1M6p5JbEpWHOCBlyLtR8bWJ4sqnClqMKeDC+qjmtp1YAt50FO6EagleiVkZWXfnhgqY9XIbtPoWXI0o3qoTUum7HNj9KmwM0JGtAt1n5seE0NUl6nvI3IMulzoSFILYo0LTKhF/BCUlZAss2TaqltqLG3IaUSIrU6fbtWTUypdbScW8XFbejZOBeE1Pz1xqh/Mjmo139fsZEqJXtJToKtPHkfUTL6ppM2wa/U7q50EbI38Fc4CG081vGPgtJ9vYOy2IxzEFJG36AL/7tGaWiRu4YeO8hOHK1wDNqkr+MYBaX7OgZlsdIxGN4saqwRNNYIL4Sn0YPowg/qQcZGmg9oikaa94BSt87n2nR4Beln/+wtjFPEGL3VcFm8h39PYURMnzfbDTY9b7bVWQabhcMUEOjw+brS/VwN7+Brx2XPhvEbbOFM5P71vbpDDOnlLVegEyXSEeny7GKt8Q/zmk7DVRzkvSCnSDrwosNiZCzNBqS5Gu1x4bOQEIPNXUqtK2uArQl8EIDMLV5hDXG5Oac1lIZMy9lmmqrIdHNkqBn5JOepYcSA1osNGjUeCYq8NF0bC96taFCwCe9GDgkzjNG/1SPwyIeEBevHQEZqCe8DzCMekkfHyDS5fSQo7nFIqhJNxD7M8VxzfEXCfDGsFZ9PqwI/ywsrP84Og0RQkSIyPGV5R63ZxVdQ5Wl/meFDJHKQREQK6zScj7E1gq/uy9BTp6hEq5amVYuLzc6qkki4aP8FvdqaXqu/qgurS9leMfYTgWv7QWpVFzFPRK0dg1ruznaXFwt5yi3XI3D/gdwf6La79Wc03vCKkH9jks6EcN1uZ9fdZSUIy1fPN0D8iVixo1mx5ewU+tIDralbxEqTMenqt1jzQeSfiD13NXvCDZcKr5QLAM2QfLHajpul+kTMt6eZ72vuCHZa4S9i9UFmfBDdf9mQ5tpk7iWeD5f1wLrke3K5NCHNGS8/Wtsv5L+uuIsFYZF1a0YGhwgvUJbc2RrpMSb36HjPK8XWMSb3uUzPJ3P8yfg88mLTc3rxa5jAPRfWWAMTouO0Z5/iW7gOxWTSa5a8l6FJ4GvHjRZFcrdS9K7AiegiOOlVRN7Asmgq+K2Ok+sz1PN7zlDJU+Is0M9dVBTeMxsEUicE3LKkzqmmaKDCJw2KqfqJLyylZ/A16khyxQjkMHCTZyR9JnIeeuGuE7+UxCYlwhYsLtThFiQpCNRSt4SrKVMyWVZUvS/YDl42UKGh3CghX2UfPZeYgRUUzcCKVa6qbCVW4LBKTwFWvEMpVgvPp2CKs1Rb3qD9OnY3pQRe40nnSUhcFej1claxunyAX2g5SA0VwIpcENkAp241pzIchCNFw20IOxZCKACsAjWnUsK0ICVDqlhIOretB7S15oNQ8JXd8usuVLy3jge1DMGfBhF2cJWejVlPBVzLDZWG0WN/TkkBlFOUAVWYGAAtDRJJVyNTEfGwsExpzPsVoyrs1zKqnnZyXUU50HKuTLMAavtiz3u6h9m0qC6a9P41VB3i3n5T/f8Gr/8BAAD//wMAUEsDBBQABgAIAAAAIQCqkbakekcAAMz6AQAVAAAAdmlzaW8vcGFnZXMvcGFnZTEueG1s7J1bc9xGkrbvN2L/AyfmgvaG3cKxuzFheUOWZFvx2TNeSbalqwmaakncodgMsuXD/vrvSRQKVQlUAehm09JILe+OLRIo1DHrzTdPX/z372/Oj35dXV2frS/uHqez5PhodXG6fnF28eru8dvNy8+Xx0f//eV//scXP5y8Wt1fX2xWF5vrI166uL57/HqzufzbnTvXp69Xb06uZ2/OTq/W1+uXm9np+s2d9cuXZ6erO7+e0fSdLEmzO29Ozi6Ozbt/u+q9vb5cXdDuy/XVm5PN9Wx99app4sH69O0bPksjyfzO1er8ZENnr1+fXV7Xrf3t+vLkdHX3+PJqdb26+nV1/OUXT16fXK6um38fPXrAyNL0+OjpH5c8983V+u3l8dF3ZxerJ5s/zvlJfnz09dn5ufvb09Xvm/ZvX35xf3V+fvT3u8c/nF08Oz76iRdm8zxdFkm5LKvlMpnPj++op543TyVVvij93/189mLzuv7lYtb51bers1evN/Xv5rMsWebuT+E38d361O/Hkg8cfX33uG75v5KZ+px51vYmTYp03v5Z1K+Zr3bfu3fx6nxVdyXxP/31+dmlmYDej8031I8fr67P/m/1/fpFoKX/eXt2+q96hn86uTqrF7T+XOZ/7h+//K+sWP2Lpf+L++vz9dUT2XWrRxcvVr/XTxTq4w9fvlydboafYTtf8NBYU1+z64cbehrqSX8PZsdHfz95s/rx7vHj9Vv6/eLoMZ8/MXMtvwn+wmzaurXjo+9Prjcrzk7FJg/syrIs52VVpEWSplVe1Cv85PVqtZmx//9it0ixzNIsz9MkXxRqu7CvhvaKaym8a9zmzmeV/2cZ60lZZPkiWy7TvCyr3F/iwdMg+73XmdR/3T8kTDvPP7p43X9gaLTdFxAXP7sjmswQRlWh/hwfsbQ/PA197qfV1ebs9OT83vnZK2QgIkTt1np1n7x+8duT1+vf+gfBnRYRWt+fbK7OzJ5XY3ZPiTAbf8ockevxB+UAdJ96ws5FCotU/BGpy3Z8vP5N/vZ0ffnd6uXmHy9fXq823i796eT8bSMIZmwHZurBd/5M3eF9v5HHIg1v1spX683Nu0IjN+nKnWaiuIvcjMk9erU+702aN12NmJWp6m9es237t4T3aHA6e+1zj+2j/Waie80nuvuqT3Zeey91+mReik2jyG+2IY3I9nv0TM6Vk4wTjrfrk7ycei+bFRiY/3wWulAbsaHbzXrtKqGkH86HH7Zif6tNIIMreu0mXAuLdHALJBWPtEhEzYbuddlrPZ8tl1kj+jvC1PZ9cuvzXuujfQ88oHu86LU52uNom+H9+frk6uSU+5oPhbbnE+CRuQtmHi4TgAY2M1eJByu/Ayg8elA/v7r4/P49uc3MgIIf/2a1frPaXP1x3J4K6cLTu8ffr39dPV2bH/f3e/TI8qZcPvbN/o4Ontvmm/6b/e099Oa9q1P7yf7+VdtRn4vOOOwv79n5Nvt+4BbqjLe/vQc+Xs6WHfwelMx8whtef4t35sWOwR6ero7gfcM+uvNwQ2djUE4MdMadus6cLnsHMLJqE0Yc/YiPlPd3qeqlS/uXzuAWuPHyoMx2b7nO1Kn58HZZ2j+4nTdv3rn+Ce98oiu2RN3+8ovTy0ZU3fny2/XbaxiIRkETbX92egIJccc8eafGy756jwbfqFYPz1FSr5GrRqFq/xpUo9TCtVp1NisT709qNGWncFg9Ks+X1TJPymRZLIowBVDOSv9kpGUNt1xTrSK1XFbZPF0URTWfF0rfd1pVOstUx6pOY7ZfKYpJlZZZrV3FtCqWpPQ5htIgkkDXkkW+zMoyyVHSFolSGH01K5nNMzO8zmXvkxDJLMsq/7IzY+i+cSNdaytlqqYS6kshTRT5oLWpCY/x2Rfr3yY8KOrUhMfeG1XPCoSnv2/aIxJdbPOQEdjTFps3/C1uKLPAXcZzHinA9k18+G3OaGcf8YreoWUxt3xZ7NG260niH93gzvYJqloV1zresHJiL6PIqbH90Kc0V+N0Qj6svERXyTY+dBh144FrI645Di+8bjh0WQxPif9d3VYfIYrI9J+3e3n6BATB9f0RZO+O91/LSv6p+/D024ffP/zmx3uPH3zy/ZN/PH3096efPP7mq0+Sz/jn08/y8tNPfYbK1w5kEO9KIbjZ9DUKQH0NGwbMAfr+nrrJctmltZi33kQ9gG+f+qpRBPrHK/qK0b2y2SLz/1Hby21HAGJwzIHtvusE26FsNeAA82bbmTw+dyR6wO3eixdHv61+ucRYdD2E11CeNF4TpkghNvnBdpjN574zo6w4NGOxUV7MyzxJqiQBzagLvyW/y1niYzYxDgXo5kR0vEVWLPMsS4uFgn/+ffbBQTZ1A9m9I2Bld3b8gNhWxsDoQOeNyHm7KgaMjQAN81D4QgyuNS/4G3xXwKYYUK/H+0JsQbriHSA2c/c3cNNdEHtBbGp9dNv9yxXTfsyU0AVsA+0GLrCY4tfsKf+zuo83xWuBbrq7ycfiB7gmFseO7h2YvdtEa+pz9rxvhV06jEXOydoSrIEp3BFwe/FWwNrNx7uP4bnz0MNqD1+cbSxYG8JqINwOVmt+0kDc6xVOJzfAalE/hQlYrdD8Wh4lsfAySJeLKq2KeZ5Uvp7l32UHsNY4NFh10zsu9sgewNoBrBm0ukd67QDWWneuBq77N5U9ehNAurvUBGAewNqHwq0pNOEWOYZc+uh/O2pNfc5uvwNYCx3Khkm8ZbD2ePUGv40pcA1U3IFrzU8cXOMHW1BrxWyO93ZeLJfzconHaIxam2fYQ2FdS4ixYuFDrJZay2f5svSckM02cyxdaw4tC1g6nMbzIsuWiqa7PbgGOmydo+eG1g30LFks0mUKQZiU+bxSDpiauYgYMTrW0LzyrbDmqx3T1IFbw0n/g7CGTljsncm1tMoWzukoiKduhteqee6O7jIkCf8Uck2dUnVNuVtxV25tYH104/3rdZhcm9zwOwZso/10dMKBXmsRewvLR6dvz/zawPd2xGzd0zXKr82T5bwi6CTDSxhXYV8suCMTQ6mB3e43YMcwZX7ts1th1AmYbXR87kT0CLZ7l5dXHmgbNIjK1HVgm/2Rw23yk3cD3IpZPvdN5XGeLXG4Lf2TeDa1ad8NcFPEst2LB+D2YQK34GLvCbjF2ta6xVZ+bAq4KcRkN+qfD9wkwiFkidkPclOT6K4hafxmyG2g4cBd9mfaRTUUCPTT3VMH5DaG3ALTd6vITX3PHsqtkMysUJdgE0CkIyxtww9q17cMVseHbsbNqeemcDvQ7eYD3hq6BcbnjkQfuuHH1mQ7OLr3dvN6fTWM3sBDXfSGCv7o+v7b6836TfOrBuJ5eK7zjAQgviOAR+ibAnhRr7d55nzeSkV/HZi57WLCD4bU98eQqq/PIA27J4B3YOb82LUR38Qpmv8+8Z1aeN3we4XvAv10l9kB343hu8D03Sq+U9+zMOwm+A7t6cDMKfgKcOrqk+5E9OBd7fq2Db4DDnXxHWswiu86z7xDfFfOPOsNZk5jwAnYN5fzDANt2gR9+lbc28N3vgk0fzeBqIqPsEf0QOB9KASeCjoOrvXO8E6HoRpivGPBv5nhVcWhBuHjn8LfqUMqvtddeStX6K78XXx9NArblr6b2u47Rndj3XRX2QHc9cHd2OztGdvFP2fvjS2hXe9kjWI7PwCVGMTwWdwXdbfn8U6ArqPDc+ehB+0aR7ltwB3z1wV3wKNRcNd55h2Cu2KmvOpIRyrCOQDuFl4QxFK56H3Q4G6ubit7Sg/o7oNEd+HF3hO88yWt3Ud7RHdBouAdoDuFkDUC24W9UzeIXh/d+I3g3VDD7xO+C/XTXWgHgDcC8ELTd5sIT3/PHvobQTyO15YQTwkGd2ZuBeLtYcD7GJ87Ej2M92B1vnp1slkdXa9O316dbf44ulxdvTm7liT2w3Za5rED9TKwwRjU6z6zLdTD1k6S+DYxdzw5yTzHjp8VWblYLJXznBdBoc20UUc8QjU8Q+1Hw+OFN+8B6h2gXi8FPLjtkFDukFCOjOFRKvOmCUq0NDL3trvXDlDvAPXwSD0klHNHogf1nrz95Q1pSgilOKd+huT6H0pVIrnsG3z34I+LEwoSHZ3aIi/mN5Sd6P/CxFQ0dYFsiRVfZWzznqaznAS9+XJOet0MjzlFvVrdoAVr5Swr5ousyogYLeeVdnq2TzvmLZkRSbPIsgURNUW2KBYG3JmMkQ8vXjz7/KvVK0oQqTSR6gorKe2SLLOc5HbZvKpM79r3n5v3n6v3tWN5sVjm8zQnfneR5otcWdVthzsRrItC8rCmZboAvS6NXblj/zLdbjIuVukyWyzoY1HC85J0V6TvD/cef/ID+TANZ5mlf4G/bdKnXs+epZ8Ff/481Rkz688Yl6FiVi0yInBJ6lsBvYlE2dtXZCFMwuAZuWRdnugmTbQeSa4HkjcD0T9+nutx8AUzim72aMPr7uEL3538sbr6fvXmF2oT9IrRMI1Pr85evWp+Zxbon8++fvr40TffPHzs1ujhr1TlevY1FZ7UjqL7E97P/xJ5vXaLpEDSxlTnMlOt0iuyNwTQ1888/H1jnvA1HJBde2JJFGz2dLWolum80IDH7mnzhpl18mQ1e3qJOpY2rhKdLR1x3vSv9F6RF7Kc/7C+PmsKlthPm80U6KZX+yHWMe+RZ8g1s5aTBvzcPT4w2gHEoqv+PHhWHz4vK71f7ydJi1yypKdlkadFluBN0+M/HKlBEaEHzwebQ8RluaQkIIVnJdJutL1nbMopnaObCM2xzg005ndtWeeaHm6sHqcpt+Yy+vtzRxLqXLZhMc/IOFA21BH0U8j8ztTRt2nNpcuKUD0z2EBz7k7We3paUmu94imMh7dV7W5O1GQRplQXeXMbIeZMUEnVMIl3p8YYnkqKKLFtl3lVLRH/82W1KJJ5nUJiYDdHq6WIoLEFSALstL6xS6orBMapb+WyM0o4PP8j7GXoLWGYaMlbhH5FQ7ZCIBi0Fkx3j/1qIp4sTKhZiDwk00UFzyRpOmSzP/q7v52sYGphDFVvkmKRJwtueTzHgDMDbyl04DfrbSMtO/Z+BLgf0mdTTnuRFOCV4QMqjT2PNeZv4CpFvkVbcyvZL16R0on4SvqlWLyVTNNkWS6LrJqzoMXQirTr+DlF69JFRaB2Nl9w+NgEQ+8pZHhYyX61pcBKVkMr6de78VZySWA1uCSnkuiS6GlA3pQjyUkESKdSkSOfV0loIaMnbl93hJhduHI4IlnsvPmyukR0RA+I11bsuCmZnknd08jRHTpsGXRP/LD51YK8JUJeUptlCSvPOmWSAWnKEhUFF/eiJO8kJzV81g5LxB0nV5vcdc0VZ39Q/70u3isXTkytx685bsDp6fq9pz1TzjT9v0gXaOZpWVIUhzvUl4u9ixMtdEnxPOAH1hjgCHLeoTb7tNP/qb6MtooSDVNQAlo66vu4+t/UujAKP2pM+eA7pZkpiT4rU6oEUXFomS8WCeWMQ51Tt/ksDRfTqC/wZ43yUSUk7KoWCRdMWc1FmvXU+2VEve/8fEy9TyEPKtaAW9zMlFaMO621JELn592vIBvNUNJZlWcUY5pTJneeJI2X3T9/vvfd//vmux8ffsKDjZr7GRNg//Pnk/N//XC1erm6ooz2Ss0+Lxh0SoEBmqsSUn8t5jA+QD7m6AYt70GdZ1Yi+rgbZ73CETqgiL1en+Ixdf7rs99XL+7bStGqxNSWyn6zqZHSXI9wWKFNrZV9NnVN4lCIGG1SdMn+Ga0H0a/P60lvutkp6Tqs7ff6GdAbej3znvHU/V5TgQF46n6vVe/xAQ1JY/Yxfb8sikUpCnpKtmW0r9hN3dz6Y/o+XGGxTNDo5iXyNBORH7n6bYODCr/XuzQhiHmsseecgagK4PetpI9AwOG+jeo7iDVgxqKcpyStzkQ8SIP3/I3plORxld9vDt+Cht8INOdgk97YU1V+b1rrRfe2q1XL0VoYnLDLSYJUrQvdubGEFX6uRfgjLlK5SoF9qqJd23DOnQMdlC1FsU29hoOjiur7seqo7XcSbmhMAOjCRbo0fXED6OjyfcKgf8WHJonSZtw6OYXRy2WKisoz0W+wO6bxBRmnMA58Y3zBktsVzxWALEBhGVQzLJBp9Uz4AimLSMnAxTIr8kzSVkXxskIY/hb39qCWPXs/P6Lix/SXBM6yFWXQSaOiTBqLKTBq96MSRCWF27MBMMyKx9cxwhYklGKGLyCBo6gxbKyBFfHWEcOO2KIAc+gxCGAz+jBdpMDlYSHNgR1cSCRxfCEjZEHFimQY2nARE0OaEebhBfHWUepZcU+BlsneAREfWP3ocePuGyKUJ98unoIfPmx9OT9ykXLUsuhR8+8D/nu3owbOiK9QjCvArrlkunP4aSJ7DFQZXaFkTtFWqr+SRxFmB876sETtrdc/RENcAVI1yhUUkD8xZ88+V9B9enuuICsoOEqBOJDwvLF0d+yI7SEtZtQQdr4Cwm719RDFFWAAgwBkh5ENbluuACoYbI4IwddgjqMBBGT9vW18BUqxq2N+gRABmYnrRb/D/u3ONzOIEA7FEjcF8klmQV1LswkfjrMA1jbnAtzUvNGMRRl2FtA/jjoLhEvh7OELe2AXcOi4EbtQxl6fxC5s4yzQbGpQUrFEFINc+5va5w+8TZ2SBZfDHnrjFvgDc/hcP3t6RKBn3jM+f9BtKjDklj8ItOo93gU9UVAxyh+gWy24QUu0ILS/6O1t1f0BfwF6nCTzxYLKz5jKoG4pWDja3jB94DqHAJzQuRh90O0asrQcbW5E/aHNIgU/FPhkLbA6YCA0ow0o/M3sDSK8bnvUz4q25y5qb+FBaZMJBH9i8Z319qvRv8MT1gIFGU+YQ8C1rsJlgNgJCjdQVcIo1VZzbRsv+D0Kd5VDUxCDUTMNA3s6yiL4Bv0gCdC5u0MD7d3PapgdpoE1mcgC7OI1IKZmjB5ljv6QcHPXG2Ac0sLFgDDwI5xDAaSDuoqPE5Q/treRtmIButt2wjEYoQH8vdn4Tej8mo6iMTbRCA3Q3cMwYUWcVXBHKsAEoMXH1ZMYEwBHCQuA1xRVXSB3hlT6FpzSZ7rJBceKokrCrxkhEN4De2cCPorFrIYWM8YGzNNCCLqkqArAxxDP5q9lXkIiSIBYic/VQhxXe/Rc9Nzt7bIY5QO6Mps6QDsTArKDlGwXfSdC0w8duXwn74EkXyaLAvIa6gY+NDDd9ibyVwmLB4ZZqIQCxAILF3jtsEoX1nHA/vva/seXX9Sou3YgEEf2KClQbkUKdJ/ekhQoZ5gOOLG40uWkYVtw9voKRrsLcnx5M7YBbgEFFevFv6z/tCMF2OVLKcGVQUFRhgsIiFDhhVarH3MhoAHlQ1D/fcCJoD5WKEopdpcFkaviqNHvoH+588a4F8F8xvSIAsAIcI6quOdoVauyS+1D78z7+udd836Nng3ey2clVyAQJQcRYtPhStvXVxCSxomACBAOfbd2mh5JpdX+sokR0D9+XkZiBMIl1fbwhT2o/azRjdT+Kvb6ntV+bxsXVY6kNsemQ9V11P7INt63qh/oW0hbkN54P2/V+8DrgRPqq/edcQ2oPxqQD6n09ELOGA5x+Xw5l//JGy3yO19gKAQ95BMg7cltmlKLr8JDHglZNGruQINRpb7bPbz8RrHGg6hTQK9z1Jwe7dyYVp/NKhQwHMOYRgZrp29Xpb7TnNwTER8Dh4Y8sDFRp+/Oa73s3i41clieKlAr0TIXNZ8tdaSUshvW6XkPSicjp1WWYKVMykUgyoCHsqSC/KnwpMDjGbzr2g6OLarUD7sGyCjEUaxic+M2BsRGtVKj6KjsfV5ABuRf37iA+Ge6na0M9qBK5jklt2DRMSMPfWYyMyBbPq5NBv0DZMz4Hlf8v5T8xIDF7PZ1iRC4ZQhZgceGhO/My8YHZ4I6OcNigcdiKdYDnFkagNNIam+Hatm099MV5wpkTnxRJxLKHK64ZJLWwoZMac0/G2h6Oyou7IP46ga5Avk2qAhPFJQQsUpKgM6E1ZUJwBMnLRbzxRwZDSk+8JoPDvfD/HRk27io/PdbTPZAfDGDXAGLCdCVKxOBIQG4hE1NWEteyziebjGbiLEJJ9W/2K0EUIs945hgwcSJQbyFc+2rGT3Kw/xDZ+0H7rVR+oGhq+tlLjWBI5SB11j0HPeuoVhj7lbqU37iThBf+aBHgoyD0EHqMuNqjOoJ+zdx5Qnbw4kT/2qMxHkxSPtGKb/gyvtb47DQ0ygMWbUohTHfisLoPr0DhQGWJ5UoHr5ZxMe6pTBwdgegg/ebP4iuPkOgKQxihhA6BPBXOOeWhvOYTGEk1LXyKozPF8g5Pti+P5oEgfMiVsIUY4eURBI7UKjLWpRJ0Us3xrD+WIMQQwtAcGRCAoFkhDdZGNpEK+1Lbfd3BIf++QDBgUuJmby9NLwVp5FqFuaZJTU6P4+yGuFyBXocnbamfmMfvEbUH4FJmpD7gJ5HeJHbIDZkL+OOWztPN3XtB5iNZNbsZXTgOWbkxJBvnTduheXodLSnKAa65j2jKY9OWwGZ03IegWa9x/fIfxSsQwVfUeXYXgyUHrAgDvEfQOwEDbCJXCF8ZcCc0WCTByPsh+vcHIe1MaQTZz926NqIdpbN6ghnzKSQBNwJjTq1I/WhW8Pp0gw10JrDYR5G2Yr5cHOKS2jAnSE0V0qXjxMfS8K385RYhFwsCaoO3/MmEq+syH/QXoUkE2qbDo4synsMOzMIvFQXdrAvvTu57Ytszw4zMpmyEON1HA3HKAt8EcoqQRtKsZBYj/6wQtOiGEbJiWOcYsYTSyKR/0NUh8LDt8JZ6H084VSMablus85xHRoTAHHKorupuXd2oyzExyC+ulHKAlooBbhBCpOmS9Bfz7ZtdZJ2dcW7AY8IZDPIkwwwgjmjbyng5yNDT0psxT59BCu5E19BkjVMnxXswxJD6TRHFbA7bCTABY4c0ccJH11Jg8gV9WQ3iFrqW6Ar9MoP3UUewRAOnhAxrO4EyPAYweA1FmYrkpm+OwZsK+4q6ZMVxU5kBTFjsOdLbi78UrEsDyygd4DRpXDsxFMC4EeupKFjr2Szf4CDy+4/ED3hg6TUB7nKAxEYslviTAV7YnoEhqgr/tO3ylRQRUVr8f7S272xV6ZC+VqI68WYq4VoNdvQEh1brh3ER8VEFGH3ilT/PMpEhGvrdJgI3ZZjIvTPu994H5iIm+VtmB5Z0bJq2zAR+AwTT0+SN0mGimgPHch3xET0urYfJqLX7K0zESQZGAMKY0wEWeGahWKtCGIbbW86FUHI8mhrUUcM0US27dsIF5GToofRQk3jT0DurZtxEbq1pVwHt+aF4dQ7ySvR9ytgsmD78NfHzlv/Qf1SSvo0LkKgl3cULBdBKJVnBSDXUNu0A5AeuopyEcM+GDIGVWuI2Jf2QwGiIeyCMc5mEPHos/2D35hOZnBu4upujMwgZIhYY0lJhapELkCjuI+wGcwTggZNFz8KYgBwKKo3XvgtBZdvhcrQx2DCoZpOZYjH1JgAGaQy1Jkg3DbamNvHAUUIsje+tFEmgyRgGGBzhFhakZhoSKfxNCEyk+NERAJx0lHKZTu6tM0Z9S9X7yhuRWV8+CvJIsRXMuZ5IVUXoRwJ7yYTILE3A0viLaTosgkplMi8wem2nNyEQ+qvpIX8t01l6JUfuso89uFPoTL01dN4MYTsLkMnWLz+4+se9bvAYEG4u0S9k1ssmNPBro+37iQ3JtqOWMV8iRFcQhdGuMipDJa/L6InfJDK+CBXeYDKkOs0SmWIcd0nJ1il5vFAkYnaFO8/vT2VQSAldzz5rSS5FmK970bRbqJiBiKXGmLsOmjwcG4GRWXg60CNshRHTrJCkFa4br51mpgUNwKY4O6WLDN4pTI3W3tdVHiVYGUR40qFjTQ0Ql+MoVKKhxLOoATJkAh8WSCc+5OiyQ48zYir4lFsBE04jdbli7nmC2ztic7PR9wuRO0wA9hL657vBY4jOYOuyB8pLsD1iG+QOpKWzf1fwJyDIEn2JPmeyDB005b3wG4w5xE/Cbo9xc8imnZikp/FvrJSCvdR723MsUABiWoKbdRefInZ2xWYAZQeeuM2uI9uR3vKnHfsbNe8Z5QXRretwOlsvTACzXqP788Lg9MPy5stS+JHrLoUQgMNTBniPuiyGBnRovC/SMnejTecsTcNNThMfnjdI57BgPeh1qLkx06dG2E/Ps+w9eOHUSI9RVY0kcO7pqbsNneb/Ic3r/Wye1vWyL/efBFQohX7KAECTpfpIJJa7I6YHEONw5CxnuQ+ImpDksu4th3u9EBZlAEZ9cbo3eTB3lBKxN3W7DMectFXu/pjlMCGOEqOUhjkQKZ+PYeR9CeSnmUA8LYIR5aLwFD+UBoFvaokQ+zAe7dPYnQ38/jZGGExvB0LCWAmZUASxFmM3s4m+2pcTLnd2OcxhEyIr2+MxyBzBIlM2W4VSuxUMz4FR/BwgjU0GQsz4y43pPyaY6zs+N552orG+CjWki0QX8sok0FUNhQ/gd4UiUOrHThy/lGFwyJqizuXqDii8AwlN7SYU1XaW3DK6C7+wK00hcrQl8OkejNZ2CuDc6wvEVsMKhBYNniKUUziKx/jMsj8g3FHakqTw4LUlhNXnohLYKyU6yL7Ev838JqS0SG46yt/0875IJnxgS70EJ0x5JmxZEp9gmKYzug+vT2dgZGJ6wB5AksdVvZbCVLgk15nwWiMU0FqQNEZ2hdKEr75bMQEOmNJ6jTPGKbfnxZDgr8yUSwY1EpCSDgvfWrC39CcbqkXI+kxTaSMiIr+Kx8YmzGeHSPNNB/TRpLon3d9K1peI59JFI8Xm1PPqmZldvzG+8BwZDGGZBLDsaX/htnRUtqF0jHBQ9jhMOyOJuMe8D5cYuY2SAxyYsnZa3saUoF6ffMeUixGt7HAqfRZjF673vP7ozHIqk/wO6FjGAqsjWBAOxijMSRCiFTFtFa727C24ogQABaWFhlmMfzesfKjrQ2yGKpvZE0aa22cxKA68kKyDswTkvBLfVcZ7D1f3DpdeKy+BijCb27RlEgINedAmaeYoLdNSY8pShy+f27RKUAV5Bkk+YBbStH0lGofJTHwlScbEqFE4hNA1tBg4xThkJgwczGSfcK1HRzb7iSGvr8h9r3DaRQ9JkTf0X5iD9mlO5MYu/lhkOYA0pxY17lQPGL/YFOFVZwW1zCGOjYPwp3E7/O8khj43mveZtlWi/V35oSNPsJI+NtvgswZZiTsNjXFlxqH7ZDEcTsrQEhwduOqTJSQkINEgjEiBVIYucCU96yy5vjNSwAa7DGWo2AehMNKnUpx61AGvhIAHF+pGN0gGUSkFg5HS+66iSslNffw0gP3IeCbWMbwSYyqnNGVHNMo/RM3dBdMoQ6USCYXRT380BHxGotSB0p0kw4p2tjQeZPMAfFVjFEHEoYlxkUphCi6zcRlJP8y7k8khSLcDseZIa7JV6T2wwx8iOs4wAxIBoKoo4NA/enMQPfpLZmBlKyMFf4vkntEClTy7b4W3N6g5HD0YlyhFEJPO2aAlLKkGGvrRpJavn5+sp8DDJzy/BTh4hMLo8QASv4SccbI5pwI8FbQEqy2MxQnZZuMT678b/ANjxagjE5dQxSoKL4cWLGki1rhXS60Um2dHDo/H3ByIO1kOLnEbi0jVp+Z8pKkCyldnQwKx/d7n+oMGM/yJmNm5+fRShn5TDMCZhH1DHXamvqNPVACrMHNnB6iySn2TAl4exmTKtlagzvTZwSAu2YvYymVNIYSGNw/3PsmBAL97GkTgZ55z7R0QKCpwABaNiDQqvf4XsgAUQuht8juRNZSfIJwFone7FZ3HyiWIR4NEhNv4m4knGPAVGjbi3IB3c4hx8Y7hyiI1tpUXavrKQ/TFCNUgIhzCtwtACaEjnLbmN7d83fldCZAt0adNQN09s0EdCcVb7a+dhxcxwlEABek+BsDvfA9JQ9n7QJhtSGjeDNMyVvdBkDgitg27LCjB6B3ZAG6d3WoZEfgPm77IrtzVw5AXLTjODfoyMCMzxFpGZnSsJERHdRkPQgrHi2A4TWZZtFWRCVF1zFHJPyaAgb+LvWmeyuOQO/ZCScgThH09uW4L1ScIQju3xgn6XZdnyGQ6rnxlQwyBEhtdE7xwcZcTUCReLX0SBl7JtqFFIYARQWnW6n0jh9rnXw9+t72mue+Zdm/3Upu77AARYi7Ly7JJUeSwOlpmQ/JB0WCGDIPkGAHrdkWYNYnMnrgBgkCfdwGrwhPpw+HSfREddynx2srzA8EZPpOhw3sET9sQXqAUeCNXSwkJRYVj9ImH5Oe7N5h44gusHuQCljUOV4z3Ih+67BEX1h5OKD5S9GYRvOvb476L3ePzX+bxfzmav328vjo+5Przerq7nGQrJN1JJUrOi3WQaLuEqO4PXm9Wm0gudO/1Er4f7FwVKdgyThYBEQpV8lWlBZaS5eMx2gJrqlvV2evXm9oC1debACgXtRpHXfqq/xgOyHmATRYFUhZ2WnNdkzKIuGcBOGIjk3ORw//mw82abVUcxSk7zTXdo5BS9EOPs5Y1UCV7J9RWttjJMLqvbr39Rt1qvq+EmXULqNTI9AmfMNX1MQwkQNimBHq7xFxIFXtgx9xEw3vIAnWcXXAl5Nrk30VfENNJomIJQMwi4jagQ9t5B09Y3hDgj4pRQVwJz11UIlkNHrSpownonla8fM/b89O//Vk88f5Suzm99fn66t6TxCl5+8W99jXZ+fnEx7jsy/Wv0148Ov1xWbCY9K77082V2e/G0ol3rnxpx6+fLk63VyPPyh9iz3VZUXqFHGeeAaKbK7W56h9zU3169n1kydPnz31FMFttrJRVCZuYk+5n3JMWuV+avMMzkgOf28P6P73X59cnZwiaZvpEItt4k2E2wB/pTjuqUQm9s/ZdycXrx49qL+7uvj8/r0RFY0+TjFCTxMkVk1Us9kRU93xP139vvnyi9PLunxjQm9lS6wuNkf33m5er6+u//M/vrhjnqnPKEWe6n/XxZ3EMhBHHRFlTXUuC0vd9kLqjLszFisenCiU5wn1oR5CnqNG45EfWiMlCIO3SifpqpaCcmkAnLAbIzeJlwt9QotANebIIJzwOsi41fn5Ee4fbkpuIuOiLMjD8/Ozy+sVJhYOeuoddCvxKHKD/7Rk3IaqgmAILbQ9c9gWuK65Hgk5Fv6pLxkgt35CoJBsitopuHtQRFwSH4ayJNiN/VXzSrfxHvdmX7jfvNDvefQVI6tI3m3AGtq3lKg0mnfI5NnX+YcwLjPhYVwqwsQNWgJ8ew/EbVhBMByuX+YArIWc4GXcRfD9wNpVquI1regJFylzTbVwU6qlEQgrGW+gkfwr35dLcwJlYSawpoPrULrqHeJasx3DQkWwMWB5Wdte/da01Bpuru0chEpB/R3UvJxShn5zWqblOASLf4XEMAHtlqEN3JFpE97oYOHJb2wFI/iIm+h0hoMJQcwwghQUxo4dGghvqMncCQvj4QDtXyeYwEtCrsL+kT9g4Q8VC0/YylttYh8LT2n7wR8G236cWHjKDDU34ZBgm46FLy+v1r+uRtAw6vD2aHjCUNorCXQ74XEnDHlenHjIz4r9jzhNCVvqCyklCoPX1DAaxv6JQVkce0EO4+EW0wbhoN8BDb8vaBjHZ2AT/jPCMUkh9v5esmiYunJ4AhKtRqQR5rXgsy0eppaesHVkLynycLythbcWD/ebj8LbFhH3eh99pUXEDcaqnbqJkY5a0LeDxEA/BYlBDjEfLwOJOw9sD4kDFW/6yBNIvMRRUBwaUHZ8pNjKn7asjXu7BZoLwkyINSVPLqmgFenqy6OgeHGtHVCwUXwNbt4KQHRRMJWosaRxniia0FQ56ojx/aBgrAokisdbGH9fvhYSCgcUfEDB08waBxR893g6IzwBC9r7eAg3jqLgJ2eb1dG9F2/OLs6uN1cnmzFWGJ37gINBC314tD2DcsDBQpoqOOKm5B2xwj0k2V9oe+76QLX/7MeKgzkhDQ5uiHhSXJkf3T32fxKQJUBg3zAHQDWUfTYjlaLzYW9S6fXxZU7AYE3+Qnbr8mAt1s1n4t3blM7kX4bfc021wJcUZAb0knAUMt9zXnDAF1bSRNtB+8sfIxxcYxb34hIrgRcZOYRz/Oe8tpSSrjpGvEwtalxrbdfgmQXOY8FA9TdJtawmpdlfmzKxgxC1uALoecEQEjfY38uirP9cO4k09AsqAcY4/0+tRf3wNPR2bVl88vrFb09er3+rG4gc/C4nEHms6wUQeYzPdrwAIg92vQAij0nvPIO8Mgl4wgsXhfGn+l4Asea0F4B6yqgT1qoVWWzz0PNm3aYsNm/4WzypbGBKZxvxnN6+RN+4uJogN8Areofi2UIm59CmaR9tuy7mk9ZJOpzg5B+//K+IlXqw9VRpn4hpJvnIRNp+6FOaq3EazCU+FzHb40jjQ+ujG++n2g/6LdheT284D1hMh3vtL5/uZNFrS0Sm/7wVXNP76VgZf3Gn+3hQiYt/6j48/fbh9w9NrNr3T/7x9NHfn37y+JuvPkk+459PP8vLTz/1ZfWTs/8zO0t87hgERBPyzhPmW/qIRA3YsZoMzUm/2fTJ5sSLv76JN2enJ+f3rk6fro2xvL+nbrJcdmktEKo3UZSd+6qRUP3jFX3FEHrZDHra+0dtL7cdY2MObPddJ3inAQfYR9vO5PG5I9Fz+/nx8sWJqHmXl+cstgSTO88f68zqPH8qZEgD3rBEnbw5Oz06NZ5M6yv8US2MC//OALqOb6s/vS2eIyS1ohhdhmWdeCHsraEZ9yAbfgt4PpDBmphnqkmGnlY3VirhoAk5MEFKUhcYQDM5IhXLWyOhzCv13wfKiFHaL8G5AsdJ6n9gYRewGwBQ69N2PGLbCwvBDynoFI+DvMRkD+rNloY/3EdW7XzGTYZBgSylSHHclevZvkHLXVdK8ZX7wp5AFmRCVuybBpguq1iAan0yH6/fbla1l6zBNcqvBVppX1m1251cO6tgElKS1E4JuKyzk2vVh+zvpDFsdJYGKPr3c9chVQTVD+vrM5FIPZAQ6Im3KAYqmFOkv+095FGOzfkcHJVyQm2UutCQzH3i5K03xNrBv3W4ffCsPsze0H46OX9r8QM+RRmSDyGIKY1gizRwC7irC5e5sXRTCEhSIBMhJblUCmzDow0Oxpiq3o2nyo0XL2eV8Ijz+4Yo6F3oaqgjYVmy7khaZm6+RN/AQQs9WVoEZji5q1ocjCDqtofVO9pecN0nE7udRUcoevu13dTY9CWTNF7/UqZoaZJfu+HE9ArxWOVpqVtFWmxqNIXaRmRSBCXLJPMoSZW8Wl7BkW0NUL1B+Bd2TkwH3XGD6ESRhmAnk6Xu8PBwJNaBoBc83KS8y+BH2HcPVudiZJWuNOe28XpW3s8VhzHATdWi+O5xxPuZIhsU2a3E9xA7KQEY9R7S4VNWgrbiU84GVlkpK0V6jgQ/i8FqY4q28Td7VAjt/yix2dNY9Fx/f4+cdGksHD4nYqN3DmKtucUMAFoWIr6YkWhV8FxK5A2pNCWUfRnMIdZbTJEj4BJAKmZT/nB6B/aAYkEOa9lKh8G15AjH1zLoN0wQHZFWki0JzpdqAaIMcFeMnEtZSurNIFgk3oDIg8xcp/q16Knb23XjRZnGzlxP7McOiddW9Mj1rodYY4OrxFzFVykWsppyH8mthGc+sWtTVwkS3BOfVei1wyp52eOGPPpBPcp9iWUcdl/qPLCl+1I4qZIzdrSmE+qfUqeLBJlkX1Kopr1GXeYk93prK+EWIfkKCFuMJgpxOcagDZJoIlobysC1ZjuzU0RrxRUEMHWttX3bLaB1nGCQaCkvBFbKxztkbC8uo8c9a1g39QLlLuNvtBhvSvwnH/GnmYxGmI0kGQQBOCDRyFeUVWEnJ34Qp5R4JNcdZkNyU0Y+pBDVpADdGgXuYspSW09bi1z8YTTulc92TFmx9tCzJ7TXMWVFDF5iZ/NMWZGn+qasyIM3MesDFXcMaA3v5a12scclTDknikuYEPT9jMGZY+hvU6MtuZvWu8juTzd2vOuA1qHZHxRT3eH3iO2G0b7YDIeyggniaCSizE1Z5Pb2GRyFFba+EHSRrOgIhHH5i26fVxKwieAzl1Nzm3RMsUqdIJWHDWQlnwNqZegLWvSpEYfvCyezulb6mCg6xOrX0a5dgrlrl46yLI2zjDHNjcexhq9TI+hAOCqONVzYEwbtp14ka2Xrbqnc9XajftW80m++R/LZV+43r+hYVul99JUH9isqlnUgf68Tm5YSGIC+Eqrb8ViyP3IeS/KTgCCJeywJbqWaKqwzud+JRdUY0CJKtEtJ5Zuh+WDR8Em7VsBk1h4VQJAetkUX8l93EucDdFIKS7SDj5LJo+JBNrWjnATvALvIU31gF3mwA+zUU1rNiPiR+DYlzK/KIS241kqvQJXc0UXJaGadu5S29XW6u49SUPF6Bz5KSp1zNHzMlhBZJXuVDKyPbrvP62/hoqTWXbfr+xRYBXa4zz4C0m3d1EMp0E13+eyG2T8iB6XA7N2mf5L6nMUjFvXs5J7EyRpBLV33JIX33V68Ffekm493H8Nz56GnxDXeST9crS9XV5s/jh5dvFxfvRl3U0Kri7spNb/EJNx3YWrVwWluSphioaQpoktGoLBa5ME0irzX9feoXk3avuDcO1RGrr10Lvn9sJqRhqZqHNEnuyl11c4mBrx9f0rifOrB0mHcI3CoqcKZ/rWaSOINsv41qfYzKSHb5xVrm+OzGrBzMUuZiTaFoeH7dFr4qpN63ibO7/x8IHF+qhMlNrGKe/kKlhw7ElJq9uB85xudRP02iX6lfx5Not/i/L0029U6d3BrYglulDefgUfer1nUMbcmoRnqZx7+vjHbyddvNK4szFbGAo8yFc962B5WDHx2Kwcy7fvXdpd3HPFb6nWk57cQ+LT3jEc19poKHLaWagy06j1urhknh70Bbue1RKpRknETmpIviZ4PXA7uQhtxWqp9H8iY1KTZxxtUeKreXarbG/RZ8vuGhWG0sWiJvE7XpEqvMeWH0mY1dtURTwvKHOAFRdIxzFjEMZVzNA8ZK9jDSVA11kEjsmqO9FPiBRlpLrjoEM7TQiESSS7rr7i3Va06UIdluHUkz33tYcPEGGe4mJbBDkpy0r1iosnx7VVao207x6NtTr5oSBSpLFbb/wY2c5RKE1kSd3Lv3sU6V63ri7Kp1f11S9ZxaeKqm+htBIIM8Eq1hIx7G3FdE5ZGhnuqhpKlxWx27Z5g4a0n8xJxn5YkcHhCZDk2uHrXhF9TF7+/S6OyY+9HQNyDYn4PvY05IjqkrbDfQ+e0Y4IbKPjhTpPlFeuFqrNmkiZjaCkjvka4MOL6IL57FCy0+fnCS9KupHhHYdTE2Q+nCUntMbgBFJlxWMnGDXF4JZH38UMZ8TRCT8AzvUoogkhiycmZ8QHfiEDxNpNCVqEjGT1x+7ojPN+g2HnrCevx85bFzltPqMfaGl4jrtD4GkX8jPCMxe2AagR4+RY42Q4IwPa0QUhC0JMen3zsddV0Awb0GT2s0ZTU+OLfYBV3Gwre/szZWuofBdb2TzC2pDOvEA++f6w1AC1gecmW3KRkJEZxJ2O+r5k4Hf8DtLwcwsMJPPBX2xlVOj41Cs+6p/6dTC/hxd6T7cVHIhar7tH0EoxdegemF0UDOnUhphQNmzE6pjG9PrrxG9lehhp+n4wvoX460ODdyVt4TH1E1pfQ9N2m+UV/zx56OJDa62Qn+0uIM7ING6+Rrv1FCQZ3Zm7F/rKHARtiJ+h7M3l87kgEDDDn65MXR/eurlYnV9dHL8/OV0Px4WirLYDrW1fa34ZML/UvDajbu+0lnS2JvAbWU394TiBY0K7vcFmX79nW9oL+vWWIeMPlTja1SARKOPz2ozWvoBToEsvWvtL9RdTAEsb22trSbcyVKe58vvuV98DeIn1/Xw0u9YY2NXCJp8P2oj0Q/at67xaX0Lc9HntXk0uo2R6b70SvN8TdbS65pHwdMZIMFCOmy3gci4GsILyN6AhxTRxtcLrVJW/sEOq6cndsbRKCtAoGxff7RhDmWN9GOGdZIji1dE4RjJJRl3b6wBy72F1Ue3+OzUVW3NusxhghczVPKFIhZf+IOcbI3jFHxPQLzeNR+ibUNlx0QuAABUZyaMlbDROXIHcEAtXL51THqz3J3X7p2FQCKk3HiSJkuJE1g5SVih5ABExNZOlj0NGvTLbckH1/iIGMxBbgqkjaPiK9gSmUjSG8X86zJhMtgG0pSFlvXPrnVMFdUH2VqiRkmxl4ce/GG7Xxpx2k6dYbnE/GznncfNM/CkFPcrPcThqHzDdY0QKkY2OJi5hvKM5JfUuCUMm6ABkoecUmLScpLAhIxNGVoFdChAbe2rv55qNYS26O+FrGDDhS1hiKf85KIjCGFsU/mUSWUnSK8u1k7MDdP/Ra9O4ftOCohYrfNn+q9Ub61L0dYoBk+LQxoPgKxcw3uB4T2ZrhP0G1tWC8d0h2ZsWipJYXCY2SMqdUV+C0HVbo9cnlShKjyL/Jh9IXkIIU/Qhx+3dT2ngmfw2q98HTFnYNdHaWWlmX4sYk1CCbDX5deU5CDQ+ttEcw7P/nmmrDrSXkWOoogzj447flUwMq2q48hIJzWhxUtqfLeN89r5k7EQkTolw7ZgMwOVUVKUlHlmV8gCIfUXGQO0WCl2AlXFxTUj7zn5LbJzgahZgmjac+KIdIcL+aZz9gKGIq6wQMqae6REp96D3xDBQ8RIJL1jyppLqFXePDjQT/dv32+uzi1RFRBL+evRip5lYNovyI0qbCoyPZMdr7qOuZzwf7Ise/cQ4B4exkZyFHsH7cuS6iXqyHgHCLP4zpq83b0xQ3vllA+AD0xbNPY9/br3eMk70QtYBeKvzOVYqFVtJks0jINxPTrSPsIWcFqoYeVNTDpBqVGkYNVSeyK2mQ5LPGBjz9DQ97JvhPkgis+ROStl3sSbVmqYec5NQmDFeq5w01TRS0l4KH7Z/IV/SMlZRdFr0Fyn2eLsN5OPiQnjScgEfHc8Ceq24l+dvDnnan1mmVnpy+Xr1ZPbp4sfq93rKFiqsynRh+BvwqsRfrq+HHBCIPP/E01JNdgfLkmmO1tje+Qz2j2pQz3cYxTW2eWTQiwz+IXZLXn4x9pEzadwGIZiuYDNhC44nVxi+AtI1YNAIR8DmwlN0J6rmD3F+/efP24oxI3B9OrjYXqyvnDFLLHJUolzKUlvKpf3l89P3J9WZ1Vf8lGrsy1D971Nobbng49nEFpg+VkUUxPMDp06k6sn+qc2EG2z+eodBx2Z5QuQFQP9Sai3gxuIm2DPQgLnfuaDaeAL5SWGoXTcAPAoaGWCxBMcOwQMQjhUn4X8x6Pk/cyqUo8k4J9CRne0X2avLxE6Lnv64QpQbeqrKyRpELkty7/oQT6mkIqUWs8kC2IlOc1Q8F3ZiE9zhZ0pSFN+pT+O4PLnxHFcpy2ecVdjWS1ov7Tp+q6qpCFB6s4O2pIjAn03kRe0dv4jkeHgsSRxCwSmjcRBo+W5QFJWRQuugl/iih3vVc+u0O/zeE69NisqdsC7shukLGW17nABPzFdrmQwMiR38o4MQTWlY7gMnthsISthiA3wfd4VCCqK6M96bVbr/JA3AXnocs7k9XVz7oeIVJyx9z3e9vtf7tvNvK2UW2oQv9jdZDN/aVrxqmq3cyo28YrpPsMBQwWFD4ipRBSGys7U5Uux0bm4vA8fAbsL2bsGvto7uPPeDsZRudPFZ3ano67I+XdUjDi/Xp2zeri80RlrJfVq9Pzl8erV8enZg6eBcbp9hanFmrrSaSP3WuDr0oBwsvA78Iuj/4Mw9+NCp9OeM+yyUGmSwM4gsYWgyFNr3VtpPl1F5YE6pcUPeHVAD4FnJZmruyzQb17HMTN/BpFI6qgAaJbxgoecfnSFpQgHMhxol+hUYN9V+D0vF4hvmMYj4UNpYiRtkcZrZu1JV2YwhNMbbP8Juy//nzyfm/frhavVxdrS5OV2qA9ZjNlhbALlN4g9b4pl08gUoO4xuc5Vr2Oud1eaCfvBDr5dZtdc3nip903amlkFm1fz77+unjR9988/DxJ9ZpJovFEbjuDDdQxBqA8tLl6lTotEGzZpbbTYb5o6CoGZUcQ5tMA+DIJlOgl83r17smI0CkXaWuZS31b/4j8o5GvV65Yrx+c+gyJ7PtKaZvnYPiGTPEpuG/5EOErh+ECMJoRb3QbHomISv3Zf68H7csbuj1wFhaGheXIB2+ZG4oJ7W9gUyPhqAX5EuvyMdK7H2dOijFn6d3cbrbsA44qKVAMOSAfC0jL0dDH3pdwdIz1lrdkXsXr85Xwd5IZXpqoaJV4akkpj/THves2zRqaBzGfbQWXJSJ1HRvGhaZMlV29pXrfljnoLkKfy1iDshgzwKnWHS97RhsLdz9EfzscX6uonh9RDmkfHFgu0ZJv1jV5mCvmzDb4bxUMh3da31sOgINT49okKxpAa5siNCXHbCk4FmJnbOgDC4lC5HTHKuRkAZeKwtcaSSPEQEg6PncRtHXHNQRZ0OQcJFhHVei0cpTJbXJyZRAxC0IZSHuI3yDaJE90npXVMebj0q4fYsBjmokTVbwdI6IPGktlrinlukRibn/YygdNfXVu6cxhNjZdPGdGwzeCOxcNlR0C7ZonB0ogWQSJsBmJybHCP7wfn8/N65/pRz26bgb5eB1sd0+hS6N79Ogq7zcAjCgKcgHEMqFMBj65W3TjoBtigy/433qbz0rsvcgVPeEhUZjaWQxFEIZSBboNfbvKFERa/GdGgzQ6e9Ug2HDW87bqR2BCnkRFcN/mkAd3aj+A1EhetiXxlHrhhJ0yAYsvph+XBIhlZajE9USTbTNy9lJPBIUt/MZhJyvdbT7NO3+xt+Lms/NVQsKkg49qKGoJr+lKKpTBMOic8obPscyzb3Gp1g44lMcFDuEy5IArnRBBB4MNg6XKO39kfCKmqedPC4p9onNfZGRUpWA8iTG7HQunIPHpXYZ6uSoU+E5zrHo4HFZc6ue6Ed3mh6aNOCmZw+3YQ4mHrmWq5t2qFuqbmrzDO7gcfnavxgssTMkdbuqa89aZTNv3Xvx5uzCGaVqykV7W0oV2zggi0UuTdhm7QU3bef4tx75cBeksUDTIKVu2dQg6dTTUlK9d/sFbgJ9C9a5erMEf6xELFug0v7doeX50HrYo+XEmFBwEyrmikyc8Bjr9nEHL92fzrwSNez/OXhbXijxcr/xFEh7vqI9Cs7uamM+d9E/1OhYLogjqvWpUPUKx9pZTm0QaUPRNkjbeluSc8yCbfWjgKCKe1ySPKPE1WuB7ZoMHLEo/w4sd2Ko69WhqsQr6VOUhIG3f0oFbLTU6Xh0BIGkljq6Kl448+PB6/KP975E5ZSV9zWibr3K8MorhYi84Nu7XRYJGTRbw3XMFq53sfa6JOdF4O6kZ52NXBd0aQ9K0Mjy0XtdBgWCBYRazGir05gJNJlN2YD2S0NCR3+p7wwHK9JHUts37Ps3Gc+NrYbgd0L3eNzxMngIpo/AXX6+DjeCXxwG/OsH7Xk5bWfF3A37u61/Se+4+yzWwS/iJylW3j8uUXj0VfNK/3xGXzGIKp+RrI2CDwVSMYFXAvO4o+N2bWw2AkfEb8COaMrOtc/uPvoAFrSNTh6sOzl9ffb0dHV93SaUvlxfbU7Oj04uXhxtVm8uz082w/mlcR9plNwOV+vPIQqrkTS4URLJTY4oWMX/z97VtrhxA+G/ct+OQrjYu7exDUngSCn0WylpuHw8QiiFJIa75P/3GWm1mpFmZuW1nSbFn5I4q7fRvGn0aAZvC0bEYHH+nI63MX7Ldi6tO7uSyAyNzKg4ZcIZxaMIeKRho86EowQSDUU02fQFX6XZSetc4KrSRwFUkIhCnjIts0ht3HUygfLwbMT7Ff/xfvjFglFmEp6ob9yPxFkD/NmtGOUjKU4BqsxzPqK3U8AqQWYjPTOoMMJZg4aycJndyuoAwTkJqxT3D9FdTcZ55Dkkj6UHOeZTnElsKiwft5ZlxNMFIU78nse24UyJs1lcs2XmU1yzmnbU01l1sWW0QxAJgdi9oGKwu5C5s6eAVGU9skk4HwKxnAmO+nMzmUEewSGklcC0lMZNJRp4ru3BUk0xe9cz5XSEIBQ0sqZSBVKCim+Rc1OLyI4wVmfHvyOKT7EpLeuHM8HRgdCHbQUl1/ROTgm/eCA+wvAhzQwe9iEnLdybLVVQAC8cenEfZUFvJcwYZzFTDhezawZeGMC4UnYapBjcfiQuLkXYwkbEdybkXthbpaLWFm9VgQZy4ZYiinDZq99/ReySamzae6VCCXA4wTNZSBQKH6AoCWI+i6QK8lzJoik04NPuXsWXK6pzxnJRX8chlzSed5GaKq5oKR0Llh+LLkv19JMR0g3PwwHgQJijEvQC57YJMHyUiNiheDWeNzCrNTmHRR7fQeQx4OeqKq0u603E6MWHeFjGvhNq6aYlKaMwOrIFlS/Pfk7yNqWr3DJEbBHP7uEuHXUMbte3PZ4xIL8YLKI6CCfNBoEFMrnIUd0DRo9rXrWJoNKiXLh4QArYfAdVhkrW9rsnSbSW3L7BpF1y4fK0Oxd0zFHoGGR5xxOgrHsUkThI5NgpskWop1Nko0Tfw1TG4CIXXuf8MXdNzsLM/9/EvXd/vb+7orO3j3uBDrUdLwv30sBAkxED7oV/rlsGrrEvGXsvKcZeMs/RjCaMmIjrkNlvzdzyFIxbbwCnXfWoJI3n+3ADuPpIPklUdEB1rLbwKXbhiTzq/6iuRboXAJTiRYfHb3hFCSdELaSVuk+3InX3VVwrNXkzXqTUszebxLuF02bsZSfpfsR8Y/wJh5J+K35SdIkFTemQTXEHYR+2AxDF+IN7o0x9oFzMtiP64U0YMCz8q6w26mrgzLUVzp28n/JgKka5YOnBeVd5aUcvyJQfH5libDY/gCwCo9DDWBXlgZ4lXy6AoOCxPiBomlpD7wWfXoAnioUwdj0ZBakrDsWazHTuaQ4Zqa8v/M8IL/FnzXlNTlJDlMg0FUkdJurOE0C/GrmASN4RNmOefGO6gmCzv/7z4eHT3eOHt/voL9U8RSaUb+8h25W+TR5SYCLTXUlOUS1eZpPo4VzKjaN0GPKbI6n165cVOuTPb1+uwqnv8SMhQ57ywU+JFFMkLDprLVgQAIxQ5AmlUMmdBlQSUfM6jOb4bMrX2Xdb3QyAUXd44YCH2BQNjWx4NlwIMl/uAIZAYo1hg5Q36rFAGs95XMga+WVQ0xW1sG6RR27EMGVIBG7bUkqtDEd45mStCtdzSVGWHjBR84i+J1jI+kbEg8dCYblnNlW2AGfWaNA254N7PglEZGshPPJ0XIhI3w4REal1ohOZTqUj++0ArkJweq2KknQ7C/ZjZ2NExuSjuBmISDU2OyWlnRvv95NKZ8G9qrUi1lNw72wQERzRN3ja0qMACBKFAK8QkRVeWewgTcz9e/fw6dvHFFKsbE72awhgYmapwmWxnMpAGX783sJE7LxSZwOJ1BO1Nz4v30KJDHgJjOSKlErwtkcElR/JCy6KnWWjxXjXjOucPteTYmFa1r8YJdID4aFEQkJIxazdsEJlXCQ1x7MCel89kGIAM8kL1SSUzNQW6R12Tith1LgFZ7si0VqL+bUFJVIz5Yz0QNudHiZCiQPtvbJgIsv2qrgz/5lgIj/IZkEo7M0ycCIEN+5RkApOH3KpkeO7QK40aTTFhrAdFk6kUp7zTH96nAhSaDh0NHAiy+hY8PzpcCL/HSErnMj0AzaeYJt4Wz7+7eq3x/3ngAQnlBMdNfBv0uKvroNuhVNIv1BBoFfX0N1v99PHZEP28dOxMxz7nm7uaev2sQFOYsH2xlHFWPgfNhYcXDESaZ48FB1X1KHC72moaOZnh/KXFQpZa6ui4+i0qphXtx6KipJnArqL2hESShuoaU1yoLMuiUJ5jTxByR/VNTURb4Ov8kgu8ShFtzpQE/HkQD7xjlvSQDCjiXj+ko4SJzmQvyS64VaJ17RLg9ilc44UbuIbiUdmVxOmJl0kB/KXRLEfdaQm4t0K4vn8YOm8piXRSS8znr+kkFpEI17TkuRI7pKsFTUJLc2ydUXbMHPFNDWtiLC+rSMdRzs5kks7i+2aaBdQhZMk+dywtXapiXZyJHdFwZlQ9qiJv6UgzazIol3TihDy5ezgLglojqwdcASGS5N8hpgYu/YYiu79laDewsH9S5/On37IlTdqgsbpkyXOwuJ3TxGDpDsXdT9Dneg0RpZq638nnBt39pTh/bDJS0vpdk5J8Q7rXKpDt3Of6s/zkeD5Hw9/IxvSl68onPL0+l8BAAAA//8DAFBLAwQUAAYACAAAACEAaPFvCTgKAABIOAAAGQAAAHZpc2lvL21hc3RlcnMvbWFzdGVyMS54bWzsW+tz2kgS/35V9z9ofVUnWBuBhMCQC94iPGzqDPYBceBTSoYxaCM0lCSceP/663kIzUjDY5N1suXYH3Zjaaa7px+/7umW3/72ZeVpjygIXew3dNMo6RryZ3ju+ouGvokeCjVd++3in/9423fCCAUt7EfIj0INtvlhQ19G0fpNsRjOlmjlhMbKnQU4xA+RMcOrIn54cGeo+OgC8aJVMq3iynF9ne19E2R24zXyge4DDlZOFBo4WHASbTzbrIAtEClViwHynAjEDZfuOqTU3oRrZ4Ya+jpAIQoekX7xdrR01ijk/9d67YZe0bWBs0LvG3r7yXdAUm2GfR/NIhzoWi9sbcIIr/gKk609uBQ0pmvjpzXwvgzwZq1r166PRtGTB0/Oda3rel7y2xh9iba/XbxtIc/TBg391vUnunbX0C3DLFetmn1u8R8gAITfN4ftXO4dWsC6044/n+SLVl4vSgSmnECpXrdtqwI07Kp5Xs0QmBIC0zSBD+48WlIKcJwtS8KqwNhK7K6Qu1hGdHkhtX7K1k+l9dd4tj1iyQAzbDlQvr/CM8V6dqKCvIGxzuxo+gsPUYHAfbfUS+2mRLfruWumaHFVt3k96mTWMe771w1R6P6B+ngesxZMwtTGVGpUU1ZNr4uNV0kZT1hHbEGpWfuoEdtynntoXTtPKOij1T0Cx79r6CXRlzqPEGfte6/lubNP/DVR6c1tZzDuTMYfeoOcpK3xlyixLtX+qDNujoedbo6ARYC90CCOf4tDl0StYjM3NfOl/bsN2bWAeeK74CryD3P/fnOSY5K3x1e58RIRafJnlV9bSycwRmDCtEiCg5cMy5Z/6BEJvatO7/JqHBM8i0VJE5O93zqXfmqMGj8F8WvRFkCS7ebeaJgxMIj4AKuSsEhtFwND8Cag+kk4pCnuIu9ajjf7cMU8SXx3hbz1GK/dGX1154YfRx1jtlz98i8A5pLkRy28fgq2OLH9TcvN8hpJBVo/ThVaCwdrHFBINzStCaBIN4YaR/O5IcowwE3PXfjv8JesfADsXYTm9w53XUvceOltEIFquk16A8E6BpYLHg/MDz9OuuNh7/KyM8zRmJh0IdIl40K0fc22m/vf1WIM8LX7iHhygsQGoSlZhqa00dpzo8i553gnLSC559aJIE1DkqW7EzDsdXPvITcavTnEt/vwBPn9zDyz8tKJKGo1gwB/pvtF+CtJC+Hoxyz73wZAhGa8OydwqYUT7Y8g9QIekAzIgQLS9hB/Jg9EwICncaZkECj52RY7BPeegA6FAyhhSPSMabyepzPlBmMqbpnAGsqCpTPQ7s0wNxoPR81+Jze6at52CETE4JA/OznJn1258xh7zmR1TmNq0tFajk98lp9EON9tgFdrloCHaM1xVSM6IyIWQYfwX65eqIASPRMPSJQMddkdK/wEFd85MUtTwiKBZ8KEW2soFGSkgFKS0zWovEBDLEVkNCQqdx+v0RJ/7m+8yFUykfS3j4wQBkpCUlztI9Se0KBRErEMyyrZdrVk161KqWyWOwUTchKpQK+pGnIkcxZ4hjgFJyDlKKlsjYmZ56XXsYppT3cLAlVUyaqLPzUAOVmOKZdjKskxjeWQvH+/QgAclOoAIcokTWx/LAieRAjYNins0Uiq5k1iIOOP7elOEVIMp5ThjqMfz5DhJi1CE7BKIqlgGpXz0nm9Wraq53W7VoebATl3kzpBc9wcWAycuQ3PKFJzz5Jwd5/iCSbvFAGgfAdH2Bbzg38e5qYEliZzWzB7DAn480dT8II+8jcUyEj8ajSAIZHN3OhJ9G9GRoBuKAa7uUsUDdED09A2/PNng5tx+pkkfWuJZp/QXKBG1bqlIDJuuyFJqfFiAWuHyJnf+N5TFoV7PrnYxolYQh7qD/xCmC6wu94T3kStpespuI2dBQVQkr1F+d5togj7XbjkUjnEVyMcRP9FTD7ynMG/YAZLaQYUQd3Fr7/0BivSzNjh5ER8LWtWUNZLVmNZpcbmYhGgBStsBD1k9Cf6MQMLUmRBWcAu95aVP8mfiotIMEtLSukVQrEHdOA20u/cNa9zsGy3qUg5mLBvWFIV/LzGkxJqOgakl88RA7bSeGGIZ7wq/QbjZSzzHLZjd5LmoM36QNQ3GqWzmBX8U/CHhin5wPMaVgK+727YisqwLSiPeVUsxsLxUfl+1MmdnMRkEBTvPyQ8K7Yo/ks2Y1VlxjaCfjBcV2fH1wgJuG2x9XB4mhn0FWJpS4csEs0hJ0GCrCQ6twFpWlJEyrXkSzbludKUbgA3GzRvfi/IPWTT4/PlPqv+PDhbU1m15y9R4EaOD2XpsyZQ004DsByhX2tNW4rRn8eadZU14abjuX98cy17BN4esCavif8k3sq2fOF4q7yEJ/0jMC+5APYmZLiTdCRY+7SgbksJAcx7qqqmkbCq7QaKfiw8ZdulunDb8JaeNjcRvkRxq1YgLbY5SGYdYK0LQ+GN5xCcSW645IBil4HLY0CDRaDGjyNdMn6w8Er7XSK8QlEAV/m04QaYDJLp1V86BZkY+IoG8QCTLke2ZQHPfWetek479e3AWSQviQeNG3ofP6IxZjIpdJ1VNDVxYiMgQYSMSYjdCIX7iLbaSUO8ijMaklayNAR1Zz4LgIYsG+DT8cq3DfAhYqDPZ5aq5zXTrFUrdq1G+269Ae300f4TRKk5OW3djFjzilWspG93alfancs8DAFNWC/4LzSJ+ZHgVUmiz7rJafLT0xFMaSm3I8iLA1T4ZMCulStV2ypbtmXWqdgMj7MjVKkcFsaJIGW5XK5ZNcsGbZC+d4pManJKBZAHUbwlzp2RQAD7VADmLKRl/m8v+k+iTJhjyeMUtpvpbIcwfGLK6E0letMMvR1TVPF7AsFc5DHnLVpx39cCf3rofo0eor4TwBchSbzGQ7IhmbruegnT212v3mHoMa52vY2HV5Qf60aQBuxoiVBkVH6RW6uSZ+wdAsZCbwfElP72t68fF++ceiURIWTGY3v10nEFSoL5xdwFjxMQY3NOc6Jky/vzbCwUc0kSOhkIic50iMlUyYSMgSAWk5GLitH0MCMBTpPZIvmawoE7XjxgTOcw8qEFc1bDTP1QkW7H5IBMXQkDMtS8eDtb85RYvOib8C1akT0uUsgWv/GCwcpfBuZEW1+P5oXnRfOd5P/2aG4oc8wrvIvh/Qrvh74GeoX3OHMKqeslwLu1D96hmv7L4L1k1Op1q1YvW2atZpZtW1mqW0KpTnq7tFA3y0dU6nVLpF5RVuqWUKkfpv7SoN2aZCptqXKnt4bdhbr1Wqiryv8XU6jHAaEsZaXvWeIyll5CttuOr8mtHTU56SMdqJYn0gj9QFlu7SjLpW+x4sOIxf/0MJekZBZS4/eqycv7QBuaCH8D0C4cAdrw1y9ywa9q3qgwezfxnw2z1a2fVxDP/J3FT9Jt2aJxMoVICtZXEKcNEVXf4weAuJ0FcdZggb+iizstyQP5zwEv/g8AAP//AwBQSwMEFAAGAAgAAAAhAENNb2ffAwAAHw8AABkAAAB2aXNpby9tYXN0ZXJzL21hc3RlcjQueG1s5Fdbb9s2FH4fsP/Adg9Mh42SbCdNgiiFZzsXIHa9WnXSp0FVaIsYJQqU7Cb79TsSdSEteYvXAQU2v9iizo3fOd9H+uLdU8TRlsqUidjFDrExonEgHlm8dvEmW/18itG7y++/u5j6aUblSMQZjbMUgVucujjMsuTcstIgpJGfkogFUqRilZFARJZYrVhArS2D4FbPdnpW5LMYK99z2fIWCY0h7krIyM9SIuS6DDEWwSaCtBDEPrEk5X4G5aYhS9Ii2nma+AF1cSJpSuWW4suLRegnNC2/0e3YxccYec8JWBWvMLpjMV1kzxxW+hhdMc6bJ48+ZfXT5cWIco5mLp6z+AGjpYt7GH108e0MW8bLT3tf3rPHLFRvSQ8qaXnfULYOs8LCIV0GdyKo0zvEaYKgKxcX4X+0wVErSHmommzytg6aO6h0ux7DeM1pUQOMAZQ4nlzrAa84S9T+7d3lMou+/IGm7A86FY9VRK20yRa6Of7MR5wFv1cJoaz388nMmzx497ezozd6MO8pO3D3yuOQ3YNH0yaHnJ2cmphVIOfL2l7AzWhef6c3NdRtP72nNjk7HfTNjFVFu32CdbO5J8cn5kDURXW46l3W9nFDeeKJhAVFP5Ys/W3x2SdBGL36YXD8dnCm73kkkmdZD2z9hI6CNygnOppWQoBGQiZCFoQlCA2BSIVjikquPhI9cMHNRcJZSQX9XU7Y+4YmNrHt/s6nmNq5B3R2sXczmU6Ww7uj143j659s0hvMPWO2ft3AEBZsz/Wh2H0vz7ugQS4zOfFB9mL1BNLyQXxBtw8utuF3pQyKFi/jpZpJjeUaIR19w2MmK7rlJjOBrkAaN9zfMarIt9+o3hjwem+k4SYT1xT0eZnvbb/dXIooUf3psLIAngYj56sweplqaTBp4wyrJdA6Wt8MiF4LCCWxcIbkSJfaopd6iHRpEOzvW43IXzX3mwHUbwF0CJsMMCvF1dH8DyA0aCHU0+4SzRQZGvI/mSKrFGtDtT/CZRAwy/UaNByuoUt1z9VwXPp8oyTfMQ71l2hcZ85R6Es/gJtymXj3oFjAnUgpLHH6p/rnrDq8QMSUiHYmuKYiopl8xq0zaCbyS2wp35oSzkR+AHatL0LxpXM99pNyfb+czERxcI6lv95rm0PvuXgqttQTquL2iWBw9x8KYXPqQLoJh4tqxgKfD2VQ5W0L8L/MnmGBwstE65fS9rj6J5DDXMqWQd9RBW1+Gx8agtaEqM4PS4/w94i0FdfoRDVoDnkwSupWlMb6k2F9OCpGEV1S/rWYNLSyiusm0K34hn+Llvkv9/JPAAAA//8DAFBLAwQUAAYACAAAACEAFE1oHuEBAABeAwAAEQAAAHZpc2lvL3dpbmRvd3MueG1sbFJNj5swEL1X6n/g5tNizDcRsGqTVVqph6hE3fboJUOwCjaynWT333eAEKXdXpDnvZnHvJnJH1/7zjmDNkLJgjDXIw7IWh2EPBbkZJuHlDiP5ccP+bOQB3UxzroTIO2zONgW8zMfC2boC4hjawuSJQFxUFWagrTWDitKTd1Cz43bi1oroxrr1qqnqmlEDfQs8N/U95hPey7ktXal31WrASTqNkr33BpX6eNVYqPqU49NoYgXUw0dt+jGtGIwk9rKDLyGggwaDOgzkPLqxvm6KQgamL3t3wZM2mh+QfMLWFluEWVeEiQhS/1wIb5Bg2ZZFKc3aK+GgsRJtKRchxT6WZhFLGb+QiyjmpnAS5BZK2nRPui5jR0/AnHG79ThDwGXquYdRg+MOGO4RsegfxYkcJM0Dbw4S7IkjrN79tfIMi/EnTA/Sn0Wo/eqVZfvpw53XrKc3kUTs9XisODTe0LHRj5r4L9N6c01d8hcdxIHuClu52hi0JmEelzJTglpbwrv8HzbnaACa3H+psxy+lecV5IPNzaO0jDBTu6xKePp1YIcr9mUQTgn3EFTyid57MDQMt+8SY43Odp8kvylg8n5f9B8z1+qoRMWJ75T6MCNcvoPltP5jMrlYco/AAAA//8DAFBLAwQUAAYACAAAACEA/cN7IMIKAADEPQAAFgAAAHZpc2lvL3RoZW1lL3RoZW1lMS54bWzsW91u2zoSvl9g30HQvRr9/wR1D/SbpE3SIE666CVjy7ZOZMmQ5LTZxXmCvdz3OG9w3mb3PXZISjJp0XXbuEWLxgUaUfo4HM4MZ0ZD6uVvH5e59JBWdVYWI1l7ocpSWkzKaVbMR/LtTaK4slQ3qJiivCzSkfyY1vJvr/7+t5fouFmky1SC/kV9jEbyomlWx0dH9QRuo/pFuUoLeDYrqyVqoFnNj6YV+gB0l/mRrqr20RJlhSwVaAlkr1CF8jzN5Vcd4TgH6kVT4xuTvBpjsqkIPb3XMKau5ndhXkkPKB/JKvnJR69eHqHjFpA3Q1wSJ/BrcS1geq8P6JmmZdp+T48A8maIi53Yju2eHgGgyQTmMRzb1F3di1ssA6KXQ9q2bnluR5sB0UtjwLNrerFhcPQJiOLNAT62LVfVOTwBUbw1wHu2E5ghhycgircHeMe2E8vk8AS0yLPifoBWLdsItRbdQ2ZlfiqEe5aZOB3zLCr92JzXDSYPV9K6ykbyv3RHNXwjMJRIjzXFNCJPcVXLUezYixwzVhPT9P+QX718aI6JNadnUWvmD83AzpfZpCrrcta8mJTLo3I2yybp0UMG6wmsXNOPyCqBNUTsNy7Wy5FswiKj7ZPbswgYouaqqgq+2Pqve/ZHKwuYBj8b1TNi14t9xfY8G2ajxkqQJDAlw/cSH36BY7SzubufF9OnTmWgKryE2kUEEiNjkHU34DSKIj1ybU8J9ThRTEcDTt3EVzzN9BPfUN3QS1pOH1CVoQZ8EixpuvRBi0/nHPgbUiaKhtthmZfVcJ1agRdEFpE+7d7hmNZwtfoW/rfdC3BMr+GadQw/NqkZ8zimNVy5pu5oIfUMPI5pDdcv4394HNMarmLGC/E4puUMTITxRTzuiDa3dN1JacftTgFbTl8sBlAoM+RQUWL17lOUuBcolBlrqChxL8AxvYaKYhwzj2NaQ0Ux7pnHMa2hohgnzeMOqSjxIPsU5em+38YbhrV9irJ9P/RoHGF67VOUWHj7FCVeG6BQZuShosRrA3BMr6GixEYBuEMqSuwi9ilKLIZ9ihKLYZ+ixGLYpyixevcpSmy2+xRlGZ4XONuB4BOKEiuQJDGQzJKgSv92t/rsGLvdWVk0NGCKcuUl+r2sEoBgaA4BtpCax1U6QxPIwUOUZ3dVhlmFcRDzhN6a1INbeDRIZapsBYnRqX85lhnI//7893//+g/tuw28YYEXXQolvV6kxfw0bXngOr2+8i+5TmPp6qRsFtlEPMIJB0b5fF1IO/H+tR+w+JtsmdbSZfpBui6XqBCNEAfXbI/z9CEtsqV0cSMA35z6Zyw4qMoP8LqTITyEAB/fnHL4y0eUIwEuiC+5ab6rMnhREwBPbl9z3I4X1boRSfnN6QUHjNC6uEqLhYDmm8vIZyd1sy7m4rGvb1ncNUIPoqHDLfOJ1yt45ctEJMPTmOPyKkdFg+ZpkTZSuEir8j5NBRy/PzvjxLqxu/eZFKBMKJGbs2CHsZ5mS1DLo4hBUDgnm4t3UlDmollH8TseiUCKuYD5m/icE+MJWjdoKSJ541+cswI/R81CxOT4/XXI4uK6qWD0NC+leJrWtajP2+v3HLtvwGeI1X5x/v6Cpf4GVU12L6J57r99yyKj8j5coOVKhB2fXZ6y2LP6vixzJF2VjQh+8ZZfIBdlMQc9oGKnut+dxZy693uC27MTjqWNVd1m88W6EujyJH7L2e/4MZ+hlLgZcO2ck15mxbPHFojw2WO3UffZY7dZT5+HPHtsNit79thdWtwbyOE9NuukIUMfVBwDI1Qd14VquheGihlGgeJbTqSotm2GSeS7uhb82BVH/pUDZ+b0LYMId/mJV45Zlufj5jFPW6HUEH+nCdzEPbmiPVNHhCccjGuQSmpf6l8t4FLGxOBtpqHlfwMXTXHQAK5poRUwtMVR4hoisi0JDsc1DtaJSGOBpimdgWMdaAZfQxektq21vGB1mBfSh5FsGxYUsidoNZKrYgpXy9V0JNfFnGiDV+BnymlV1U2E6gUVAiHRqjEv8Ey+fGB2V2i3gT2PO/2F5Qz2ztt3Opulk4a1eOYOtkPaBI9GHYTwKen+ncB4mHLdpNV4Mf0gTbMayjGGq5mweTvNqpEMO17EJUpQB4Ft3klTyVJVNv/ImsV4gVZQ/FHpohWtU0wc5asFoqtSI5REzrXngG7/ECF2RapvIaKfbNY4hA4M626OYyFral/lOPd3wsLaREiviy8QIFFzUU5b3RI72R855xUiMXzLiDRiRPO6DfXzWlqV9V7bYrjCgRuPvsUVZra7v4mRntvfzdfLzRxUOF0gjv7zGpPu2KJUyWC7zJ5hbTMYJ7A+1QCWGdY2DPOsdRMcJCY8a2SN7VmSzHB2R3ZLblgQuyUBPPSqgiqOBLWfkWyZuA/ZoEZ5CvG869+pnKztbasFUrMuCcQCFeXAmmHqpmolCpxjgN3f0LMUN4wSxfeiMNYjU3N9vc2BgVZYFgX44LI7+EGPmXz9/rvgmMl2jrN/DX2/dHAwEpbwlqPgY9aXp0a7jJ4xLLez+oG9csI6fPok4m0gE3T8eQN7lm49JVElLmKzuA8iFBAor79haGDukDXVxVMqB+HTw+ccwCczUuvYt5c/uJ1v91bE+ODnoCU/B63DBS3YYB9GGpq7bh+yihwrSUzdUDwdDoqZuqcpvpnEihbopum6Bhwkc9rgRQ58tVuwT4xa5AwALWDAETR68eQjZDBrhkXxdHUnjCw3MhVHdeFMGZwgUwLdDxTHj4NYh/cK3w03sZpONv54kPNZ32C6fWoSfxRPN7Th2Jztwpm52HNBu3Go+FGQKKrrwFwtA04LJpvpbqUmP/S8B7yKBWDZumkYMHfNceBEZGh4cIYQlA5FSlX3vVAznV4AXRZSH0TdOKm5qsoVvCqgBl5g8SFk/AaA1+YP8AgfxujzLnh7wOFw2zfYoR94HqwO1XfAegK4CizPUSzdjmzdsJ0wMFvrgTQ7JTH6QMIb5Mnn/QBEhP14fQusFYp1kOjjFL+BPdnN1Tj7JxQCdHwAnOT9+G9/j9cOFsuQdpt9tM8+eySTjPjrjkRsbJ8mex/2M2oYbO072dLzSIJ1+dkr8ceUXrs+aJbBmj/nhXY4Z5yvmJGlKnFowc5bZEPBQfMNJbQS1dfcwDPs7qw/2dTCO1X1SVWuVwcJb5OujJHgHTNCnMY2aNKwV+ObtEYGjnOCz6B/siTFvJ1buEwkKNZt6BDRdUP9igNjAXxKB4dRCVNB9bxWJ/B+zxUlSVWtLWF01Q3IJ76RrhiO2loiDM2z1HO6Vdt5Gkc79tu+iKjmQB150wOqC53AaJUaPtQiVr+BPN3Ov4rmkxnt+O7MkG8TNyTOOU3PDGNIypVIsyBhd6JQ8azYVVzLtvTYd33biducs//ghQzSetFDf0zD0JbS5V0Kh1vrBf5+DyeURJnABgFJOJ0+m36EDSpZwjlkd03LTF0LO+P2mr4N/NT9sV5FeugkQz90+RohQmGzFyJcM0KEVi9E8iES5WFLCU/t/1Qlagz/cM3wD62e/369P0mIxrMl8p+HMAb32Za4U4g2o0m4ZjQJrV6T5DM1oSX+RP13L+ddT/ptcFw8oEWE7hYpxrFfO5d3v8POVwRfZazzpiZxG2oOFYIzTL33pokE6frq/wAAAP//AwBQSwMEFAAGAAgAAAAhALxnIMamAQAAQwMAABEACAFkb2NQcm9wcy9jb3JlLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHxSQW7bMBC8F+gfBN5liraTBoKtAG2RS5siQBy0yI0lNwobiSTIdRT9vivKUuw27Y3LmZ2dHXJz+dI22TOEaJzdMrEoWAZWOW1svWV3u6v8gmURpdWycRa2rIfILqv37zbKl8oFuAnOQ0ADMSMlG0vlt+wR0ZecR/UIrYwLYlgCH1xoJVIZau6lepI18GVRnPMWUGqJkg+CuZ8V2UFSq1nS70OTBLTi0EALFiMXC8FfuQihjW82JOSI2RrsPe10sHusrdUIzuyXaGZi13WLbpVskH/Bf1x/vU2r5sYOWSlg1UarEg02UG3465FOcf/zFygcr+eCABVAogvVF3g2NvtW73uwqXcChsifoO9c0JHaTyrq1xBVMB7pIUfxkwtiNzLiNb3sgwH9sf9jzt/4MG5ouQnGIuhqWYh1LpZ5cbYTF+V6Wa5X98nFMYnWTimP24DOKLdyTHlCvq8+fd5dsX/oTay0NE2dBduD8/8rnuWFyIvzwWHxoRSDw0lxEqjS15UItQv9mKOaK8qxkbbe09+swOZ3t+kF5qu07+m3r34DAAD//wMAUEsDBBQABgAIAAAAIQDrBtKhawEAAG4DAAATAAgBZG9jUHJvcHMvY3VzdG9tLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyTTW+CMBzG70v2HUjvSIviCwEMAiYmmzEb87CLQSjahLakLW5m2XdflWE87LSZ3fp/yfN7nqb1pu+0Mg5YSMKZD1APAgOznBeE7Xzwks7NMTCkyliRVZxhHxyxBNPg/s5bCV5joQiWhpZg0gd7pWrXsmS+xzSTPT1melJyQTOlS7GzeFmSHMc8byhmyrIhHFp5IxWnZn2RA62ee1C/lSx4fnIn1+mx1nYD71v8aJRUkcIHH7ETxbEDHdNOJpGJIJqZk/5kZMIxhPbMjuaTMPkERn1atoHBMqqjb9arRbwJH9LkaRmmyTJ8TJ61+EG5Vf0mlQg86/rcQf+I73f4WUOqYtnQLRaRwJnCRQsngwDpixzBPnKcswXd8awb4Qc/4JOC/BPd6egL+YiVIHkbect5FSjR4HPcc3WzwMMOmRKKr5OWpMJK9wIbIseEyITDFI1dOHIhej0buWxcm7FOT7H9KMEXAAAA//8DAFBLAwQUAAYACAAAACEArhjCJdABAAAWBAAAEAAIAWRvY1Byb3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcU02P0zAQvSPxHyLfW7eoi1DleAUtaA9UVLtp74MzaS0c27K91ZZfzyTZJilUSODTfPl53puxuH+pTXbCELWzOZtPZyxDq1yp7SFnu+LL5APLYgJbgnEWc3bGyO7l2zdiG5zHkDTGjCBszNkxJb/kPKoj1hCnlLaUqVyoIZEbDtxVlVa4duq5Rpv4u9nsPceXhLbEcuJ7QNYhLk/pf0FLp5r+4r44e2pYigJrbyChFHwwP3pvtIJE1OVGq+Ciq1K216SF4OOkeFJgcEWIsgITUfAhIB4QGrW2oEOU4pSWJ1TJhSzqn6TXgmXfIWLTR85OEDTYRP00ZZ3T2sbHFOQWDhgFp1znt+a4bGzrhZy3BWT8tbDD2kBMNOV/QF/cRm/a6xjSs9fcC50Mxm/VFkK6IcXdWIq2q06IgfykY/TKvtdhfbZQa5UpZ22r7ZhFX7WLGG4mHt1zs2DZI90FezA0vv5SM4juuc/GaN+Mto+0Zk/1N3IbsDStQBr01srVHuyZQr31VdsfcecLt25273V3roPi6QgBS/oUl/wQEA+0NsEQyCfaoUbva7934+pIzLC8QPyZELTP++6by/nddEan3fFLTPDhQ8tfAAAA//8DAFBLAQItABQABgAIAAAAIQAdj8O3hAEAAG8GAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhAIsLzwcWAQAAzgIAAAsAAAAAAAAAAAAAAAAAvQMAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAG/qIvWHFAAASoEAABIAAAAAAAAAAAAAAAAABAcAAHZpc2lvL2RvY3VtZW50LnhtbFBLAQItABQABgAIAAAAIQACghQb1AAAAGUCAAAkAAAAAAAAAAAAAAAAALsbAAB2aXNpby9tYXN0ZXJzL19yZWxzL21hc3RlcnMueG1sLnJlbHNQSwECLQAUAAYACAAAACEAj8OZ7LgAAAALAQAAIAAAAAAAAAAAAAAAAADRHAAAdmlzaW8vcGFnZXMvX3JlbHMvcGFnZXMueG1sLnJlbHNQSwECLQAUAAYACAAAACEArI+QTQIBAACEAgAAHQAAAAAAAAAAAAAAAADHHQAAdmlzaW8vX3JlbHMvZG9jdW1lbnQueG1sLnJlbHNQSwECLQAUAAYACAAAACEA0jXEvKgCAAC8BgAAFQAAAAAAAAAAAAAAAAAEHwAAdmlzaW8vcGFnZXMvcGFnZXMueG1sUEsBAi0AFAAGAAgAAAAhAH2B/O5+BwAACyMAABkAAAAAAAAAAAAAAAAA3yEAAHZpc2lvL21hc3RlcnMvbWFzdGVycy54bWxQSwECLQAUAAYACAAAACEAbl3n3gsJAAAjJAAAGQAAAAAAAAAAAAAAAACUKQAAdmlzaW8vbWFzdGVycy9tYXN0ZXIzLnhtbFBLAQItABQABgAIAAAAIQD3oiPc1wAAAJECAAAgAAAAAAAAAAAAAAAAANYyAAB2aXNpby9wYWdlcy9fcmVscy9wYWdlMS54bWwucmVsc1BLAQItABQABgAIAAAAIQDozGG5dggAAKkwAAAZAAAAAAAAAAAAAAAAAOszAAB2aXNpby9tYXN0ZXJzL21hc3RlcjIueG1sUEsBAi0AFAAGAAgAAAAhAKqRtqR6RwAAzPoBABUAAAAAAAAAAAAAAAAAmDwAAHZpc2lvL3BhZ2VzL3BhZ2UxLnhtbFBLAQItABQABgAIAAAAIQBo8W8JOAoAAEg4AAAZAAAAAAAAAAAAAAAAAEWEAAB2aXNpby9tYXN0ZXJzL21hc3RlcjEueG1sUEsBAi0AFAAGAAgAAAAhAENNb2ffAwAAHw8AABkAAAAAAAAAAAAAAAAAtI4AAHZpc2lvL21hc3RlcnMvbWFzdGVyNC54bWxQSwECLQAUAAYACAAAACEAFE1oHuEBAABeAwAAEQAAAAAAAAAAAAAAAADKkgAAdmlzaW8vd2luZG93cy54bWxQSwECLQAUAAYACAAAACEA/cN7IMIKAADEPQAAFgAAAAAAAAAAAAAAAADalAAAdmlzaW8vdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQC8ZyDGpgEAAEMDAAARAAAAAAAAAAAAAAAAANCfAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQDrBtKhawEAAG4DAAATAAAAAAAAAAAAAAAAAK2iAABkb2NQcm9wcy9jdXN0b20ueG1sUEsBAi0AFAAGAAgAAAAhAK4YwiXQAQAAFgQAABAAAAAAAAAAAAAAAAAAUaUAAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAABMAEwAdBQAAV6gAAAAAUEsDBBQABgAIAAAAIQAw3UMpAgYAAKQbAAAVAAAAd29yZC90aGVtZS90aGVtZTEueG1s7FlLbxNHHL9X6ncY7R38iB2SCAfFjg0tBKLEUHEc7453B8/urGbGCb5VcKxUqSqteihSbz1UbZFA6oV+mrRULZX4Cv3P7Hq9Y4/BkFSgFh+88/j934+dsS9euhszdESEpDxpebXzVQ+RxOcBTcKWd7PfO7fhIalwEmDGE9LyJkR6l7Y//OAi3lIRiQkC+kRu4ZYXKZVuVSrSh2Usz/OUJLA35CLGCqYirAQCHwPfmFXq1ep6JcY08VCCY2B7YzikPkF9zdLbnjLvMvhKlNQLPhOHmjWxKAw2GNX0Q05khwl0hFnLAzkBP+6Tu8pDDEsFGy2vaj5eZftipSBiagltia5nPjldThCM6oZOhIOCsNZrbF7YLfgbAFOLuG632+nWCn4GgH0fLM10KWMbvY1ae8qzBMqGi7w71Wa1YeNL/NcW8Jvtdru5aeENKBs2FvAb1fXGTt3CG1A2bC7q397pdNYtvAFlw/UFfO/C5nrDxhtQxGgyWkDreBaRKSBDzq444RsA35gmwAxVKWVXRp+oZbkW4ztc9ABggosVTZCapGSIfcB1cDwQFGsBeIvg0k625MuFJS0LSV/QVLW8j1MMFTGDvHj644unj9HJvScn9345uX//5N7PDqorOAnLVM+//+Lvh5+ivx5/9/zBV268LON//+mz33790g1UZeCzrx/98eTRs28+//OHBw74jsCDMrxPYyLRdXKMDngMhjkEkIF4PYp+hGmZYicJJU6wpnGguyqy0NcnmOXRsXBtYnvwloAW4AJeHt+xFD6MxFhRB/BqFFvAPc5ZmwunTVe1rLIXxknoFi7GZdwBxkcu2Z25+HbHKeTyNC1taEQsNfcZhByHJCEK6T0+IsRBdptSy6971Bdc8qFCtylqY+p0SZ8OrGyaEV2hMcRl4lIQ4m35Zu8WanPmYr9LjmwkVAVmLpaEWW68jMcKx06NcczKyGtYRS4lDyfCtxwuFUQ6JIyjbkCkdNHcEBNL3asYepEz7HtsEttIoejIhbyGOS8jd/moE+E4depMk6iM/UiOIEUx2ufKqQS3K0TPIQ44WRruW5RY4X51bd+koaXSLEH0zli4SoJwux4nbIiJYV6Z69UxTV7WuBmFzp1JOLvGDa3y2bcP3Z31nWzZO/D2ctXMfKNehptvzx0uAvrud+ddPE72CRSEA/q+Ob9vzv/55rysns++Jc+6sDmCTw/ahk289NQ9pIwdqgkj16Tp3xLMC3qwaCaGqDjkpxEMc3EWLhTYjJHg6hOqosMIpyCmZiSEMmcdSpRyCVcLs+zkrTfg/aGyteb0UglorPZ4kC2vlS+bBRszC82FdipoTTNYVdjahdMJq2XAFaXVjGqL0gqTndLMI/cm1A3C+qeE2no9Ew2JghkJtN8zBtOwnHmIZIQDksdI271oSM34bQW36Yvj6tI2NdtTSFslSGVxjSXiptE7TZSmDGZR0nU7V44ssWfoGLRq1pse8nHa8oZw3IJhnAI/qVsVZmHS8nyVm/LKYp432J2WtepSgy0RqZBqF8soozJbORFLZvrXmw3th7MxwNGNVtNibaP2FrUwj3JoyXBIfLVkZTbN9/hYEXEYBcdowMbiAIPeOlXBnoBKeFWYXNMTARVqdmBmV35eBfO/+eTVgVka4bwn6RKdWpjBzbjQwcxK6hWzOd3f0BRT8mdkSjmN/2em6MyFA+5aoIc+HAMERjpHWx4XKuLQhdKI+j0BBwcjC/RCUBZaJcT0L9haV3I061sZD1NQcGJRBzREgkKnU5EgZF/ldr6CWS3vinll5IzyPlOoK9PsOSBHhPV19a5r+z0UTbtJ7giDmw+aPc+dMQh1ob6rJ58sbV73eDATlNGvKqzU9Euvgs3TqfCar9qsYy2IqzdXftWmcE1B+gsaNxU+m51v+/wAoo/Y9ESJIBHPZQcPpEsxGw1A52wxk6ZZZRL+rWPULASF3Dlnl4vjDJ1dHJfmnP1ycW/u7Hxk+bqcRw5XVxZLtFK6yJjZwj9ZfHAHZO/C/WjMlDT2kbtwKe1M/4MAPplEQ7r9DwAAAP//AwBQSwMEFAAGAAgAAAAhAGBLI+bFDgAA9EMAABEAAAB3b3JkL3NldHRpbmdzLnhtbLRcWW8cyZF+X2D/A8Fnc5hX5EGMxshzd4yRbZizP6DZXRQb6gvVTWlow//dUX2IOr405DX8pGZ9lVmRcUdkpn78/W/r1dWHYdwvt5s31/IHcX01bObbxXLz7s31//3abvz11f4w2yxmq+1meHP9Muyvf//Tf//Xjx/v9sPhwK/tr3iKzf5uPX9z/XQ47O5ub/fzp2E92/+w3Q0bBh+343p24D/Hd7fr2fj+eXcz3653s8PyYblaHl5ulRD2+jzN9s3187i5O09xs17Ox+1++3iYhtxtHx+X8+H8z2XE+D3fPQ0p2/nzetgcjl+8HYcV07Dd7J+Wu/1ltvX/dzYGny6TfPhni/iwXl3e+yjFdyz343ZcfBrxPeRNA3bjdj7s9yyg9epC4HLz+mHzzUSfvv0Df/u8xONUPFyK46/PKad/bQL1zQR2P/xrU9B5itv9y3r47TLRfvU9LDlBvywfxtl4UrgzP9bzu5/fbbbj7GHF5DBfrnhpV0fqrn9iLf/rdru++ni3G8Y5i5pNRIjr2wk4jLP5+78MH5aT6eyPjxbD4+x5dfh19nB/2O541IcZE+fUecT8acZjDsN4v5vNWTB5uzmM29XlvcX2j9tDZsMYWW6nEY/b7WGzPQx/Hj//iwcsF2+ub+SXL50fHz92+/XYYbP45o+v5vny6WWaLwaezPb11/3JBfCQzWzN7PvCrN9uF2yjH++ex+X3y3kacOSGNGemwQ9t2WWNy8Xw6yS2+8PLamjMzPvlX4e4WfzheX9Y8oxH4/43KPhnBAyb6ct/YkX79WU3tGF2eGax/Yc+dtSMtlru3i7HcTv+vFmwKv67H7v9XJzs/xf7y4+/sOZcXhXCe6llOJE3oa+IEFKz44aI5kEQkSrRWbRfI8bYDkI5Z4xY5UoHSY4w4shiRLlUIkS0aR7Tpl1yPaQWjBhpgsOISgrzjSQP6yA1YimQzRkjVhurMWJ8h2qnlcF64EjJhBGXCUsu2mjOfvErJEmrsXySbBV/J1kr8ZisyFWM6BbwbNlQxVRnooLHFJUy5mgVtUN1VVpiPag2KgWRZk1rCJFCVQeplkL7DHnAOuUrpEAKSw1yVAonpO8gBlu9lNJhH8JIIWjBUpmSIA/Y64QAdYedjnOYAq0dtlOpjbSYo2zBCdqPNEJ1OGqUrJ0xpjioB5KEjVB3JOnc4RuZWPFK2YIJr8dJ67GGOC0ans3ZYLG0g9SEqQ7SYKuXgaLESFS+I7lEoYc400GKiB5rb6GOv5bFFoE1sUq6pCNfI8paLO2qhe4htTOmSdOwNTbWBExbUypCRLHVE5Sc4pDhIQVKmiqhzSlpA7ZTpQwpGDWV4vgDtZf9nrRwpUprImglymhvodUrkjnjlZLKDa+HtMVeTJGxBdo2I83ilTLNBeq1shwa8UqtiTiiK3a9Bmova5vG8YcR15vNKYPXwz454fU4zt86Y5gJmAJvgsI8CLZmTFtwpmANiToRHhMpdr6TurxONldowSpzMINejBHnMXeylALTlpUw2EoyO8vObLZZzINigsHaW8hITEEhr7F8qpQGc6cqF2DEUJUoYiuptunObKxvmOrKwQTT1jh/wmMaEY7OmhOEAHmg2YBwfqCVm1pNCNGsBpACThw6mqjZ72C+aWK7hzqqnfEOU+A5r+oh1WLagtENjwkUcNapowgaylQnkTSmOlEJnTHOecxrzvxbB3Gp4tkKTwa1ipGSoAXryvaIpcBZNM6vdaOKNdFwZSKhnTKSsOfjZDDgvNdwColzCs45nYN+x3DgdpA7RqnkoVeekIQpULphT2G01hFy1GiyAnokY0zE+QHX7qTwbMZmXDsb41jjIEKKEoyAhkwSeDarRYb6ZtzkYDpIzHg2RxJn3pxdi4BlGjn3x+uJLFIs7aiD78zmLPajjETcQzFJuopnSy4aTFsW9tKh/AZxBWtiNg5nqiZTpyNjKvtlrInNlQh5TRwdE6SAS6agIEcnpEDaGEkRahVJ1bB3IWkt9i7s4nPBFHB9in08aY5APcR3aNNsWngMGyrOQ8hQwB0msjLjqo2szhHPZnUn/pA1hL0/OfI4h+X8pOD6hzyVBP0beU5ioVcm70yGes1IwjbHyUEJWNpBhoqlHTl1wbNFVwRGUpdvyXncC6As2S9ChL+CozMVF3GUoWoatlOq5HAtw7WH7+hbI04IEWKnXAhKzgrrJKTN8kJxH9ZKVXCWZqUTuJ7jMkvgrqFVOmENsYqywmO0bQ36HaudVXg2I42A8mEk4GzDGpOwvlnmJ67aLLksMA8skwZlysVhxtprOT/B+Q7LTeEeip0a6JgCRxn3nqyztnYocCJ3ZnPSYr6xD8HdfetJexhLGPEdvgUZI7QSG1zGHTPOLH3C34m9XvSEYM9nEyscXmnSDnfmbLKhYsll1XA/0RYZcH1qiykNI5WVClPQOBPBVtIsYQvmVMwKqNdOaok13klnIowyTsmIOeqUFjivcsZ2PJ/jdBDHH0ciWagHjFQNec0JpMVdUMfBXuP1kKnYJzoug2XnO84EqNeMRIm/Y7XEFRjnnA7n5M5Sw70A51xPpl4qBy3LcXagoadw3hpcvTMS8D6TC7Y6LNPIlgXtlPPhmjEF0UqcebvoBPaJjISIeZBsp3fLiMV7OS45W/CYzFUbHjPtTWEKMlWcJ7qpS91BmDbM0eoKYR40Nm5MQZMNZ7eu6YR3BFyjhLvUXhDhOpiRDtWsiBpb8KSiuTOGBK41vVYa6wEjHveEvDYa76Qw4hMewxUy5o4nmQrUUU+qYE1kpOJcjINmaXilVkrCs1lpcX+UkdQw1U5lnCszUhT+Tvf8wYTgPVcfmGrMnaBNhd7FcyWOux5cmCXcv/bRCrzzwIjH1uiT6ux8+6lGx1LImnBe5bPLFVNdTMY9SF9sx4v5arg8xAglha2xyYz3nX3THmc1vnEuBmcLwkS8IxCUcTg2hmnzA/I6sGnjnCIY1dl3ZqQ6KJ9AXJphCkgUDzUk0LQF1UFcgNobuDTDOXlgKxGYAqcl7iwEzq9xDA6elwO1N0ynMzCSpMM9VS6PvcUcTWQrlkKyDvv4kLXDUSaUqe2AERnxjkAoKuJ6O9TJ7jpIxXlVqLpzpiRUlzryaSriiB7a1C9CSBSiYk8ehbY4J48cn3HuEqWUndkkRRw1o7ShQPlERRrnYlFxPopn01wCdRAOZ9CHMGJxNhiNtDiPj8TShlJgpHP6jJGKO86RrMZ7u4wQ9qPRao+lHZ3udKWiN1pBy4ocuB3WkMCZPKYtcvKANYQVAZ8ciUlLvHfIiMLVR0xGdvjGOSzuPcVsBM7WGTF4LzRmR/gsWyxK4I4MIzljKXDNhs+yxco1P0aa6uzTJiET7myzM1D4hEqSurMDlThzwT2HJK3BFT8jAdfBSSmBe0JJ6YCr0AnBGUpSxggYzZKijGN9mg7TQZtLxKkIHkNGY4+UOM7hzIERwjGLkVChT0xBEK5/UrAeW0niSg9rSErTMIywG8PryaJjwSlrhT1fysYpTEF2FtdZXCwEBW0hFaPx/lzqniVgJOLKNRWnOjpaOe/FY6pJODonjpq4ZkqNCPfwsxANZxtZksZ7lFm6hnU0K9vZo8xGKrxXfXRiUD7ZWIHrrGzZV0EPm51TuDrMXnmch0wI7qkyUnE3PHOC3aE6ioJPiWZOA3AHPUfOyTEF0UlcNzKicS2TEyV8ZiFnUbDV5yw7/QNmdMRncXI2DfcCciGDM7tcpcAdwFyVwz2uXHvxNFfOKfCYpiquAXMjg71/ETrgDnqRpjg424TgvY8iifDOUJEuY8sqWmacCRXNxTv0fEUbiXveRduMa6ZiOEXA6zGqc9KiGKvxLmkhQRFqbyFlcf+gcCQhqDuFKOPTdIVsLng229sPLtYVvJNS/NQx6iAJV67F64JjcOGsE+ejJZgU8HqibdiHlGQC9kglOdehjaNChwdZ64Z5UEznNkQp1uAsjZGCM9Uq2BjgSqswFttpFa5zS4EdhcFWUtV0ohsjqnhojVWRx9KubHP47HE1UmLJMeJx14PLScJ6zYjHJ0eqMRGf3a9scziiM2Jxr7NOBTL+DvU6THU6OQ+lXYkFBz1Stcbh/K1a6/FOV3VTcgkRz8ky5ptnz9dBnMLZLSOdjlkNbHZ4pcES7k7WyIUo5gFXbTiiV05RcKRlRON9s1plwTurdToNhGXalMT+mhHSWOMbF4fYGpvlBA4hTaqItbcp6y+3PL9CtJT49kDTquE6uGmKePelGVVxZ7tZoXEMblZHfB6Jkc7JnjYdJsDfcULjU/DNmYYjU3O2c4K1Odewr2p+alhhhCLuHjdvOxrPSMV1CSONMNVBWoVpC9LhPl9LIuJKvCVj8e0oVgKP950ZyfhuX8s6YX/dMomOJmaquP/WOHkJmLbiLL7X1qpp+IZLq65zM6g13dlHb6y+pwrs9gTtf/pxfTfdj59uEZ9+Tdd1r9anEXm2fhiXs6u30w362+mNh/F9Wm4u+MPwuB2Hz5H754cLeHNzAvbr2WrVxtn8AhzZtr5bLPe7Mjwef6/ezsZ3r/Oe3xjh08Xw+IdPc01Xv4fxf8bt8+6Efhxnu9M13Msr0pxaJuu75ebwy3J9eb5/fri/jNrMxpfPoOfN4k8fxiOfXtnz8e7wNKyP15l/mR3vAB/fHTY3l8Jkvhrvp6u+w9vZbne6JvzwTr65Xi3fPR3kdMn3wH8tZuP74x8P79QZU0dMnbDjH7P5tDJ++/zj9Zm6PPvsPX15pl+fmcsz8/qMLs/o9Zm9PLPTs6eX3TCulpv3b64//ZyeP25Xq+3HYfG/r/g3j05M2D/NdkM53bdn9dqeHpwv4O+vPtwNvx2Ya4vl4fpqv1su1rPfprv7py2s89ur2cv2+fDFuxM2vbz7cobF7DC7XJv+YvBRxb+iZfp/AOZLVsf7l/XD6/X+H06Er5b7w/2wm42zw3a8YL87YtLcLbbzn9mS+NfZlrgcpHMfStInmE7w37y25EKrN0Su3hhq+SYpF26CjWaqCTO59vezIV7+u46f/gEAAP//AwBQSwMEFAAGAAgAAAAhANqloZ7AGAAAiAwBAA8AAAB3b3JkL3N0eWxlcy54bWzsXV1z27iSfd+q/Q8sP+0+eKxv2VPXc8uW5U12k0xu7Jl5piTIZkKRuqQUJ/PrF58kyAZAgIT8kXimasYiiUOwz+lGowmS//jnt00cfEVZHqXJ+VH/l95RgJJluoqSu/OjP26vj0+PgnwXJqswThN0fvQd5Uf//O0//+MfD7/mu+8xygMMkOS/bpbnR/e73fbXk5N8eY82Yf5LukUJ3rlOs024wz+zu5NNmH3Zb4+X6WYb7qJFFEe77yeDXm9yxGEyG5R0vY6W6Cpd7jco2dH2JxmKMWKa5PfRNhdoDzZoD2m22mbpEuU5vuhNzPA2YZQUMP0RANpEyyzN0/XuF3wxvEcUCjfv9+hfm7gEGLsBDADAJEduEGMOcZJ/36BvR8Fm+evbuyTNwkWMkfAlBbhXAQU++g2zuUqXV2gd7uNdTn5mHzP+k/+i/7tOk10ePPwa5ssousW9wFCb8HOavblI8ugI70FhvrvIo1DsjBJp5z35Q9lsme+kzZfRKjo6IWfM/8Y7v4bx+dFgILbMSA8q2+IwuRPbUHI8u5B7Qjf9cUM2LTDu+VGYHd9ckIYn/MLY/6XL3dZ/0RNvw2VEzxOudwgLFeuEgMYR8YvBdCJ+fNoTC4f7XcpPQgHY/wvYE2BxrF+s5hvmVHgvWr9Ll1/Q6maHd5wf0XPhjX+8/ZhFaYYd5/zo7IxvvEGb6E20WqFEOjC5j1bor3uU/JGjVbn9X9dU/HzDMt0n+O/htE9VEOer+bcl2hJXwnuTkHDygTSIydH7qDw5bf5vAdbnTKja36OQxJOg3x1iQFrk0tUCTGqSfe3a6VFOJxo+1olGj3Wi8WOdiDrCY5xo+lgnOn2sE1GYQ54oSlboG3NEeBqA2oSj8UZnHI2zOeNofMkZR+MqzjgaT3DG0QjdGUejY2ccjUwdcHbpUqdCSexDjdrNuM1jRDvc5iGhHW7zCNAOtzngt8Ntju/tcJvDeTvc5ujdDrc5WLvjslQreIvdLNl19rJ1mu6SdIeCHfrWHS1MMBadZPnBI4MeyrxcpAcYFtn4QNwZbRnS380KoU7qpDwygQvSdbCO7vYZno137SpKvqIYz4uDcLXCeB4BM7TbZxobtFFxhtYoQ8kS+ZSyP1Ay9wuS/WbhQY3b8M4bFkpWns0nEL2EgULQeMZ8T9wi8iDqTbjM0u5dS0NvEeFdlHe3FQEJLvdxjDxhffAjMYrVfTZAYbpPBihM97kAhek+FZA482UijubJUhzNk8E4mie7MX36shtH82Q3jubJbhytu91uo11MQ7ycZ/TtS22zOCWF8M79uInukhAnAN2HG14lDT6GWXiXhdv7gNSh1bDyNbue5zJdfQ9ufYxpBZKvTJ5KZIavOkr23Q1aQfPlXAWeJ/cq8Dw5WIHX3cXe4zSZJGhv/MxgbvaLndJpjY3CeM9S2O7+Fe66a6qU/HWU5d6Er4b1oNkPJIElBPqIdWUvu3esxOruSPU45LV7HNJDL+N0+cVP4H3zfYsyPBH70hnpOo3j9AGt/CHe7LKUaU128gGlxGpknm+292Ee0dlRBcJ+cBc3zYP34bbzBX2Mwyjxw9v8eBNGceAvZ3hz+/5dcJtuycSSGMYP4GW626Ubb5i82vdff6HFf/vp4AWe9ibfPV3thaeCEAWbRR4GGYaUrjwh4cQySiIvYyjF+z/0fZGG2coP2scMsXUqO+QJ8SbcbFma4cG3cFx8wPHHQ/5D8f4Ms4hUgnw51a0XMKlQmO8Xn9Gye6j7kAZeakG/73e04kiTW9raH1z3NKEC1z1FoGzi4YHo18PFVuC6X2wFztfFzuIwzyPtbdLWeL4uV+D5vt7u0z2Ol8Zptt7H/gwoAL1ZUAB6M2Ea7zdJ7vOKKZ7HC6Z4vq/Xo2QonociHMX7nyxaeSODgvligoL5ooGC+eKAgnkloPsqHAms+1IcCaz7ehwG5ikFkMB86czr8O/pvo4E5ktnFMyXziiYL51RMF86G14FaL3GSbC/IUaC9KU5CdLfQJPs0GabZmH23RPkPEZ3oYcCKUP7mKVr8gBDmrCF2h4gSVU69phsMzhfJP+FFt66RrB89stDRTSM4zT1VFsrBxzaUiocjs8am9GnNTp34WMcLtF9Gq9QprkmfVs8X75hj17Uu29q9S66u98FN/dFfV9uOOk1thRT9Eqz5hOqrDwRT6momr1Hq2i/ER2Fj0hMhvaNqYYrjUfNjcvcodJybNkSnnPS3LLMiystp5Yt4TlPLVtSz6y0NHnAVZh9UQphatJPMavTiG9qUlHRWHlak5CKlioJTk0qqrhKcLFckvsDkB07n9G3t3MefXsXL9KjuLiTHsXar/QQJgf7hL5GZCx3CZP0fMUKifrphjRttrpF9K99yir1lVtMdCWzVfu3OFVKchQocYb2t6oqUUZvR+two4ewjjt6COsApIewikTa5k4hSY9iHZv0ENZBSg/hHK3giOAWrWB7t2gF27eJVhClTbTqkAXoIazTAT2Es6NCCGdH7ZAp6CGcHBU0b+WoEMXZUSGEs6NCCGdHhQmYm6PC9m6OCtu3cVSI0sZRIYqzo0IIZ0eFEM6OCiGcHRVCODtqy9xe27yVo0IUZ0eFEM6OCiGcHZXmix0cFbZ3c1TYvo2jQpQ2jgpRnB0VQjg7KoRwdlQI4eyoEMLZUSGEk6OC5q0cFaI4OyqEcHZUCOHsqOwBwvaOCtu7OSps38ZRIUobR4Uozo4KIZwdFUI4OyqEcHZUCOHsqBDCyVFB81aOClGcHRVCODsqhHB2VHp7sIOjwvZujgrbt3FUiNLGUSGKs6NCCGdHhRDOjgohnB0VQjg7KoRwclTQvJWjQhRnR4UQzo4KIUz65DcldQvr+yYzijqndlW+6fL5iT/Jj2TLjYc2FVZ9a5PZLtP0S6B8SHBoMtVltIijlBaXNbfAZSS6fMHpJuXvM/PTODJ6x5cg8ecW6P1NAD6ybQmqISOT1eWWYHo2MhlebgnyxZEpbsotwQA2MoVL6lFiAQkeSEBjU4CQGvc1zU1xVmoOTWyKrlJDaGFTTJUaQgObQoDUcByQsFpvPba006RYCwoQTHKUEKZ6BJMsIVcikELHsCVNj2DLnh7BlkY9ghOfWhh3YvVQzgzrodpRDd3Mler2jqpHcKUaIrSiGsC0pxpCtaYaQrWjGgZGV6ohgivV7YOzHqEV1QCmPdUQqjXVEKod1XAoc6UaIrhSDRFcqe44IGth2lMNoVpTDaHaUQ2TO1eqIYIr1RDBlWqI0IpqANOeagjVmmoI1Y5qML91phoiuFINEVyphgitqAYw7amGUK2phlAmqmn9o0K1E8NSc7ckTGroNiBLDd2Cs9SwxWxJat1ytiQhtJwtQa4E526zJZk0PYIte3oEWxr1CE58amHcidVDOTOsh2pHtdtsSUV1e0fVI7hS7TZb0lLtNlsyUu02WzJS7TZb0lPtNltSUe02W1JR3T446xFaUe02WzJS7TZbMlLtNlvSU+02W1JR7TZbUlHtNltSUd1xQNbCtKfabbZkpNpttqSn2m22pKLabbakotpttqSi2m22pKXabbZkpNpttmSk2m22pKfabbakotpttqSi2m22pKLabbakpdpttmSk2m22ZKRaM1s6eah8EIlg0++N4YN337eIvCFbetRlxd4Qym8C0gPfrooPF5HGpCcB/0QU30w7zG8Y0r+zHM/q+DG93mAy6F9yssEnoBbk1Uy4F3327jXxRSh2X0x88knz3azzo1kYR4us/CRWuYWebUlMJDoy6pF/yaH0C1nUfOdH5M3b9FrpxtuIfMPp8po1l76ZJbojPnNFLdNgy8J6/HYs+zCUbL/ye070fAl5GaDCtOSleWK7wJrdhxnbS76P9QmtyBu4UAMTk7P+xUWViWS/Kf54WxwqlFPsze+LfcsY4VMH3Lr8+1z45zqK8d75ZH4656fYhQuqN/x/0ThGazot36Y5+WoVO4s4DqpidCqrgv/i3wljXMLvhJGOJYTWfRjz513p1pS9SOnd17gwiIvGgss0XkGhFZuX+IIuskhwtmD/neWsR+GW/yErEjvG5WDOtVZcO911zBQna3DII6783Ta2raMuB1pd8rHCQZeDUpdlKBLH8GBbXW/QINnpZNif8zhfl2wUl1wKFzKrGAhsUBFYRV9TGhZU+oJKomfvGq1sJDMcTOZiLU9NMnwZgiQYcZwsGGGTLoIZagXDl18sQkzs72TcqmjDWU1D32q6uhrNL7gfmdRko5we91CoBtG6qobqYDS56ImOSMMMF3rl04x0W0fGRlrG+LIXX4yNDOOSHwp7s8F4yoOmiUIqRTOFioxDRadAMjl381c6yz3M4MUVsd/E3eub/GYvNVlR4jvKaqyVFQ9GvmQ19h0IxjgXGvBoZVKRsJJBRdXMlfyiqFFCTkfyHbxxLJYof14K5EW6u9cpTpz1oIpblGIQXZaGnhenxYlWizzM+tLi5KlSHOpTrZLya/pPwc013bgIl1/usnSfrHjuBHUozmhOa27D+3QTSlkN32ClpeFkfH1WyoZrKaRT2nIzWSGNlHJS5DheRsypVk58cuNLTtOnkpOYOhQ7If/ikA7816NOxP5rGWkOoQ4fU/lTrTq44X2p4/Sp1EFVblaHOMSjOl6qHs60euAc+dLD2VPpQcRUgx7EIR308FhxQZGE9C1HjSUmIFzyt7VryqX8O0vFS4ToV5bqCtF8jEnDLR+jy8c51FTr+70jZWNDn2lZ2VjnZZVnrfi4+pp6iPuziJk08B9vaZb8wOdirKerb1wNeP8MxfH7kB2dbvWHkjyb7e336Es6a/sX7HsT2vYZvdmhBTipdob9NOuEfXMyYk/haMvqpKKvMDd9mKurpS01vNzn2DQ35IB6/yrF5nov+c6gH5QxqRbmlH6gC21c4fqK9Yutzz60KZ87RqJmFllpVsfiwBOLfEjTDk760eflF00dCWHVTR0hQ0+E8CKHJSFygfRwhFSqnw2EdKmJOhLCipc6QkaeCOEVV0tC5HKnpzqQoKZjSaeJtw6FHkfeWHVQx9vYE2/8Ci15kwuMfngrcuMfhjdWSdPxNvHEG48z/kYk84xW72PtJi0auurB0CHHsKkGeuealbl0XE89cc0zxcfimrNcq2k9BueWRQtHkli1SUfSqSeSuMUfmaQXTAsr+uhoOfNEi6gePUWcPLzvVCmq0mZb+lGXAMlUnX2rHVBE1+vxfSp+5GKffp6vKKFUuZjP8QyHX5dxWRe4J65aKSUqeJZ2MMiXXP7xZbxHasMcB3SfyjBkf/kKbnqEwzI3U02zYg/hrnwvqF0ykVYTrqmYunTRS3ltSsvULz2OsHkKudJDuGs3yspiFcaQz0j0Bp2PhzPxDW3zukFwU0mxcKZcuFf5UV1lBbjQVGYcWTCoVc9JjQ4XazuJVLG2oEfNw35eYHB+CO+7WHPAjqK/4EGuhi7COKmY3UYbLLwP6CH4hEN34tfiH2iJFK3URVC+UyqFNgcJDzGhpmDHaFhcG3svVP2i2NYmFdncD6JI5cCvuGHABwQnk2wvVyzwiXI5PTTHYuKfgP2b3OYhf2CJCT75JGN0fdq/vNIN11xpHN+8FouvqGkQrnn0gnJGYb67yKNQTK/Dz2k259s4JRxVDvez6fhUXQLmqcUXlBUklrUquOVw1atSCkq5dU0PJc3qVdalrGskJjBVGZ8nVQUx/Dv1dVb4Zo1FxT1qO7+tJCosm26bl7DPjNQ7y7aq1OMasShSqUWLxGTAE+BWIYzfEVQEsAF9/o1HMPrUjIhghYKMoapYKiov8RucqhftGWoDo95Z78wylbSNBaWRlUR2jQWSGvR0+b7F48mEatXzV0CqxV/9Ao8PJ5BPZxq9h11Gb3anXKF8Wfh9OqzKBUJ2fYaRv7F5o9sQd6Gj+pClrKpRvbJwtj+mj6DT2/P8p8rLgKJwzrFnX5gUiuJbmhQ1GI16E9uiw6nneg9Qh1GQXZ25Iv0GHbr79PNioFj9UmZNZAt5/QzMmugDlnSXyrjyQhmN1cTnIMEs+vT6suKxpZfw1NdtaiyvpLlMsxXK2PN2Nv6vdn/9qNnc1jZ0qFuLFTitGkdYYSv0plvzP9s1P6man/1sMxSROiyCPk9WEiK1n5sWC6LMNL5Y1xbHo+G4Vy39KB7rJL7Joht9sHM0YX5ZOYYSXBxyNmQVS2Iu7eOf8qTQxTO6R2LJgnU+2C4fRXfBqp4ePRftUqlO947bpljXaUoMXrfjmm120TVDetV1e11LFqzzwXZ11TUn+8fStXp6/wbvy8i1wxBR7HEzZAc9T8fDYZGsMRtWjNLD/0g3/blR7qsd3Yuj+QjYwelvf5/x+4owv5LeUK+yD9/X8FIERa7aZv37ZDidDKpJ2ReEth/wWek28uMddkiWqFrdRnqwX4pRpiCq4COaNrwsQRFIprSsYVUzrVyEalk/tWrDjEsu3RWLmazqesqWy5yKlG++jFbCzQ/yWIDSDjZ1QWzhsGyIkuM/buTrPj/6HB7/78eOXgTfGrJLl+KNIS2qETY3BG2DjsJ5gCzJzSlJQC0sAN9PQSzAy6QvxwK1emGxVqStWeBbGIhZ1G9geDFmGVVf/ONqlsswjtM0ucWXCKzD9wV0Z5OR5JRGArVJPZsfgHGwVdeMUZtQ6RbnBPy+r7RUpwyFfcUjDmybvxpY3domGrsmq7Jc3FjVU9jd3p2S2YPQJU0fsMEe0Eqf+sIj3Ojx51fj+Xg6uaiQUrHsKc6IxXSue+JrUPS3eAJflEE3NkUh/QU53K+3qF/pi/ZPugBFuE5tDUogp1iKncLB4B7NipaaMMpkWUoC+RopuCq+SALLPuFMcEZ58qoh+IILurGzhn5a0hfsv6p7EEoJNM8DDi0B+FIKuvFlSgBfPx7FLuLoLtmQ91fyDvKS26tGWmoEvpqCbuyskR9hqHkRknsJYxF83wXd+BqIfmZVTHsKVYgv4L6q4hCqeHHD0xSWM+nGzhp5HZ5eA1EhMlgxphtfA9FPrQpYMKcbX1XxbIanp9cIfFEy3dhZI6/D06vkNJJT1YanHmrDrxr5cTSiqv1OX2rt90VoxLBAfXxG/n0slcCV6/TDTGQRS6RYXMW+2iT2qgRisX5dvEygqp/5eHJ6faXRT5d702ChGlOX/oZnZQWPMOFDZTk89aRP6cNlmKxuor8L+/CppjgCw+uPsFlSLz8NKw/apstgrFg+YusAelLtNftZtchHYmcmrHWU5TtsISqhwy08kINtjSpm5yXfsjyoueUHG5KIK/8AHDxUH2QoTlV7QqG2vXj0gG8n1JX2oL94lCiJ1NAah6+s/nisUmfFvaK0GjiwVYgnqAWOnf0/UcZWWzXQryTLv10f7Jffznrk34J19ia06lBDtrH1NUMx2tizRs3zJs3+/unN0za/OWYfN4RV40qeIz6BqK4jP/OEp8Wi5eeZ8jS+AKRdaLZ5r8jPmvZYmNzbEGlxrtfU55XZgzD7mv5Y29VhfL8aXl3P5wXvbHyvDzw/cwLk1UD6FEi91nqWbkh57BNaowwlS/h2kjBJ0l1IPxCdFQcxJT/+auvT4Wgolplxr/KzEF39oAc3jvJBD8kuJFlVmkT3rIeEe4hnPWQrgRHKdSA65Jtn63ao25jv9/IUhsylm70bJfiYjxHLgmd0tKPIKPib/eIzWho1n/NDVIQAU8sPg4GdCpL4+Q/tG+Zx2Y+25UvRyZsfo1e4Ml7o7fbE+pbt+UzUDqf/79Eq2m/Iyz372tk/O4a+GjTod5/987utVXPPLqbDOeflaW53SAbkyRP/g8r6dabPfponDWI+qHSYW3KaQz+23maOeNjpXIeJmDzFVgTpmrj716OzKegJETddjNfGMs9foC9nivtqd4s5/AuaTT+3ea1ubOdV+wEf3uFqXT68i+r+QIzw6iW8NiM8X4hx6BH+KQbpvs5ryvU2Jp9rbN5h0H2cImxt0Kl93ogHi4X6+0YqN7ILgRZmdy7QWmA+8Q3BcW9UxmE5bogB/blV6yvSkI5yZn+V7kU0+5u/NvrnIt/ys2H+Mp7H8uvCYK/+2iGpPChbz3FthEfTvvT7SKfkX0NkkPfwhQxXtJD1ROnv4/Q3QeSD4TaU/vhJhpvhHgrDqUbx1wTPj+1P+MSM+k7DxI0aeb2P6SfddFVZcRCry3atyooHNn+WqixjRyjUMaTNr64H1/WQpp/R98VLPQuXsCufLhiXhx/wjU5EPwmhcCLbLrQb5c7mw4uh2sS0Q/URYzZzHjHcqqu1DvHLrfeo3puuUVFnfItnE17GtEPYyENO7ALllAO2nL08k3TxBRVKL+fj62qnjF0VH1h1HG/VC4A+hneIfQWRXoY80m7xriBh+xjPj7/iZzobj6/E17I0F6Zey/AJfY3yKE3AZRU76Onupc60u2M+G40m4kCvycLTriuRwgq3u/gr/+3/BQAAAP//AwBQSwMEFAAGAAgAAAAhACEwqPDXCgAAY8AAABIAAAB3b3JkL251bWJlcmluZy54bWzsXd2OozgWvl9p36EUKZedYH4ClKZ6BCHZ6VXPaDTdq72mEqrCNj8RkKqu23mZfYR9rHmFtYEASYzBzm/NnLpJxdjm/Pp8HB+TH378HgZ3L16S+nH0MEAjaXDnRYt46UfPD4N/fZ1/MAZ3aeZGSzeII+9h8Oalgx8//v1vP7zeR5vw0Utwxzs8R5Tev64XD4NVlq3vx+N0sfJCNx2F/iKJ0/gpGy3icBw/PfkLb/waJ8uxLCEp/2+dxAsvTfE8Uzd6cdNBOd3ie7/Zlon7igeTCdXxYuUmmfe9ngNxT6KNzbGxP1F4yFq89iJ88SlOQjfDX5Pncegm3zbrD3jetZv5j37gZ294SmmynSZ+GGyS6L6c4kNFChlyX5BSfmxHJH3uWwxx4sUm9KIsv+M48QJMQxylK39dyTQUnQ1fXG0neWEx8RIG236va6QeZxBOoZV6wj7kl6oMg4Jy9oxI6qERMkU1og8Ju/fcUhK6flTfWEg0DeEijW8C+WCCSerxTaGVU4zTt7B2jdf183Fa/kcSb9b1bP5xs32KvlVzkQWLY67SWpoWnB5HzJeVu8auHC7uPz1HceI+BpgirPs7rL67XAN3xEsGH/Fy6j6mWeIusl824d3Ot0/LhwFelvGQ+8TDa3FCGouV13rKvMROPPcb6UJmiVJ/iYe/uMHDYJ7/GeZgTK6EmyDzP3svXvD1be1t+xAqAy9vLrpl4TrYXtTnaCbb01lxJXghF3z8sb1ZTsy2Myp64agwD6vGx00QeFlxZf0lewuqG3/208xuXMXTfvW+VwP/+P1/Vfs/F9vWwHvaTvZrklOL5VR+bvtgArCw7tcx1p0ykUj3cd3Rj4h4yDzFVfxl5UbPebire5ezJ+XHPI6ylCglXfjYPL+8hY9xkA+1sLx3GvwIT7z0nlws7XKyfJZxzkn+2VBtp96RiN4lU7dUU1ZYel+9PSb+8mdyLWhRvj2zNE1XacrH/2brAMdEJEmmJEnznuaw9BZ+6JY329P4EI36aLypQF3mVGCnenYZJdLfYRSZeQsOizi2vnikRz/Gg/jVSz57GVYbnXmZm3mkqkzu6SzJByzZx7D0Wxy6EZ0jhcZR4j+v2lmS0Z5HIqMHSwrFHMVYYpqnyq0h2TAENKRezug0bpYwBwIsaRczugm/0anK3irSy+gmlzE6nVtDmiSyLOiXMzqDnyWdHajpLBkXMzqT3+gm6t7S0GJ0nHCBrO4CcGFuSwhNC2JF4cJEUS19qudc7CqiARd0Z2LNnIlR0NCKFPcE/IHXYLhxQQnsrMR3cxjnuWlmpb77FWN+bCihj8H7TwTr5dMWoK/qvEgbX8QRBvZbsowoPY2SIa+YV15dUKJVYNN4k/hecveL99qQzF4rkc9+Rz4pNUBLKSXteCn98ft/eeV0gE/6yunfuDdJqaUNKe228QmkAXlKgfRdy5gC6fXIxYNwzvIItSuKBly6ogd14aJre1ADgV3Vgw7A1rU8qIHfrupBXXDtAh7UwH5X9KAukHdtD2rAyat60AFyvJwHcYJREqS4wSiyZFNVLWbOshuMaoo9tWVDroRbqbEBRk3bsPSZPhNQ42Eq81c3cZ8Td7061cIgimFPty4cZL8Am1KkdJBQk4pYy/+Y+efHqqWACsM6sYDeOXatPOzkovkzY9mb8rhbxLY35XG3hXVvyOPeEfa9KY97P1iYrPT8WHhmzHRNUQv+RbHwXNemsqSxsTDs4/ZjHPZxi1bYx+1kB/ZxjzA62MeFfdy/8D4ucTRuuCAjXZWV2ZGpM8tRJNNCRiWKShENuDDXJ1PDsSwR19jNnRW8eUuSQ6NrhR9OELNimFkPOIFBcxzEyfZu7ibLMX1vlHHNvVxJEBNfcS+XtFz7WQI77u3u7Z5BQPz5Mu3qGWnaXu/JRcOfL5NvO0NN2/s9g0Fxe5xi3kiGmrYXfAYBcXucOrl6hpq2N3xy0fDny9TbzlDT9orPYFD8+TJ0tQw1JwAmLikAgGeKgsx5wT8dAOetbbvGaD61bEOtxFoptO9xF3ZejNv/lRwsVdoi3xvaakOhpyB1NKzzhf2f7naoJd87qZVPRe1oWB536U/wftaRfO8k+ASQXiASGJMc+lSkku99/PaU0Ot0ihoN1dFQ45UBfvjP19X6UZs0dCqsb5VOf8JHw9ywuWhH2q4r5w2dtE/OQftoqHOTL5u7vp03dJKvn4n80bDOTogm2fOGTg6KQvWzcDAalokaDiY0Y3cZyBsoTHAGWwLy+IOtos2Rg0pXEM02Sdp0IkmOVYmiEn0j23TVAs2bqsOCMwKtUoIzAnsCgTMClSjgjACcERAQCJwRqEQBZwTgjEAvgXBCTyIxfuhpYVCGlBI0Cr/fwpobkq3Uz3KVGg/rogB63lK5JBwJEFsW4EjAu4KqcCQAjgTAkYBLQls4EgBHAi4GfUlhJj/0tR0DLypH1vghVVENew5HAi5SKAtHAmjYE44EnNXo4EgADX7BkYCzGh0cCaAhkNMcCUBkUn684CBnIqtlpBfFC7ZtWFr1hrimJgAvAF4AvNCtIcALgBcAL+yzBHjhjHhB6NXx8sxy1KmjFtTyl1CbiiPNNYm6qSbgA7tnBX/yXJKNKYfti75u7p+c3ZH7+cqrqWzU2Zc96MNfeq1MlEvVXlNZqUuvD1i5tbrsbmZK229hZjSsr/dFZ/kPADUYaqveFjhzKlSWTWW7rsduYfvGS7apTNXrUDtTN17OTeWrruBm8nXjpd5U1urS7i7WbrwMnMpdXfPdg7sbKhFHQm+WV2RHnhj6kbsVpjWTdd2wKllUemlkH8zp3LJsieJiZfzZ1RRj0+lib5ufuoGPeSdj+7xvvtF9kWZlR/c/cWL7y6If1PZAbc8V9j13BQS1Pa2igdoeqO2B2p5LehzU9kBtzzVqexAxM364rCFTdnTmDzHB+wt6kQrvL2iFZ/0IhvcXtCsK3l8A7y84hnx4f8GJk1NCb9dWbFVRJkrpx/zR1kLaTJ5to3VT6hBtu6mFaCvgf7w0d4Td4yLlaRFCZ3S8AEaAUAuhFkItO9QKvZlaVQ1TN/RyzYUfsoAqVMaGClSh9jRPqELNoAq1YgmqUEWNDqpQs/NVoQq9yFdVHV2xnWN/BNacG87cZJ9amSmarGqzKz30iP7mAPzIK1R9UPEJVH3wIZ6L7DzsiwaqPrqlBlUfHQKCqo9W0UDVB1R9XKXqgxgeN9jVMPpUFaQWAoCqjyNIhX2oVnjWj2Co+mhXFFR9wFYUbEXd0FaU0LuDJ7opaY6dSxFeiEI+YCuqDuv7LMFWVD/zhK2oHimVtkh/KaODrSjYivorb0UJvXBVV/Cz+dQ6Ei8Y8nw2RfY7Ll3pDwJO5AoQ9CHoQ9CHoA9BH4K+eNDPLZk/6Duqos7sWUEtpOSPIBVS8q1Buh/BkJJvVxSk5CElDyn5i6bkozzKRuUjdc7VTsituMuJGuddD8YVizV9XC6WlnHFmkkdt9UBbVix5FCH5YtHy7DC4elUbo2WNq5wNu7bFUZOv13uaC3jCtOij8tDWcu44kmdOq6KX7RxqMAw1IEssSCWtWzXMOpAUXNBDHthD2RYDHsgy2aYAxlGwx7IMBuWCyKG2WyDIXUcw2wQa6DMMJvt2kMdxzIblj/JLLNh3lFwmZFZVsMcyLIa1jiG0bA8X2bYDMsRZYbN7KxQxWfxpPXx/wAAAP//AwBQSwMEFAAGAAgAAAAhAHQ/OXrCAAAAKAEAAB4ACAFjdXN0b21YbWwvX3JlbHMvaXRlbTEueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMz7GKwzAMBuD94N7BaG+c3FDKEadLKXQ7Sg66GkdJTGPLWGpp377mpit06CiJ//tRu72FRV0xs6dooKlqUBgdDT5OBn77/WoDisXGwS4U0cAdGbbd50d7xMVKCfHsE6uiRDYwi6RvrdnNGCxXlDCWy0g5WCljnnSy7mwn1F91vdb5vwHdk6kOg4F8GBpQ/T3hOzaNo3e4I3cJGOVFhXYXFgqnsPxkKo2qt3lCMeAFw9+qqYoJumv103/dAwAA//8DAFBLAwQUAAYACAAAACEAuC67FeIAAABVAQAAGAAoAGN1c3RvbVhtbC9pdGVtUHJvcHMxLnhtbCCiJAAooCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACckMFqwzAMhu+DvUPQ3XWapUla4pStzqDXscKuruMkhtgKtjM2xt59Djt1x53EJyF9P6qPH2ZK3pXzGi2D7SaFRFmJnbYDg8vrM6kg8UHYTkxoFQOLcGzu7+rOHzoRhA/o1Dkok8SGjvXMGXydTo8831c5adsyI3lR7sj+Ic/IE2+Lqtxxnm7Lb0ii2sYznsEYwnyg1MtRGeE3OCsbhz06I0JEN1Dsey0VR7kYZQPN0rSgcol682YmaNY8v9svqve3uEZbnP6v5aqvk8bBiXn8BNrU9I9q5ZtXND8AAAD//wMAUEsDBBQABgAIAAAAIQC38a4krwAAAA4BAAATACgAY3VzdG9tWG1sL2l0ZW0xLnhtbCCiJAAooCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsj8EKwjAQRH8l7N2mehApbaUgnkSEKnjwkqbbNpDsliSK/r1BxC/wOG/gDVNun86KB/pgmCpYZjkIJM29obGCy3m/2IAIUVGvLBNWQAzbuuyKlu9eYxAtWtQR+za+bKpvzanJru0BxAcclUswMRBph0LRVTDFOBdSBj2hUyHjGSl1A3unYop+lDwMRuOO9d0hRbnK87XsTGcNj17N0+sr+4uqLuXvTP0GAAD//wMAUEsDBBQABgAIAAAAIQAM4rLSagEAALsCAAARAAgBZG9jUHJvcHMvY29yZS54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8ktFOwjAUhu9NfIel96MtyMRmG4kQbhRD4ozGu6Y9QOPWLW1h7O3dBhugxsvm/86X078Np4cs9fZgrMp1hOiAIA+0yKXSmwi9JQt/gjzruJY8zTVEqAKLpvHtTSgKJnIDK5MXYJwC69UmbZkoIrR1rmAYW7GFjNtBTeg6XOcm464+mg0uuPjiG8BDQgKcgeOSO44boV/0RnRSStEri51JW4EUGFLIQDuL6YDiM+vAZPbPgTa5IDPlqgL+RLuwpw9W9WBZloNy1KL1/hR/LJ9f26v6SjddCUBxKAUTBrjLTfwEe6W9l82uAh3ii6ApMeXWLeu+1wrkYxXPtkZZb75b5zsT4t95M2JqX/NeMSUt0p8738oo7UDGQ0LHPqE+GSf0gdEhI+Szl3ZQeKrsuBVIr74qOxbTJe+j2TxZoLMvSOiEkfuj78f8WZid1v7fGPh06JO7hAZsPLk2doK4Xfr6u8XfAAAA//8DAFBLAwQUAAYACAAAACEA3JNYaZoCAAB/DAAAEgAAAHdvcmQvZm9udFRhYmxlLnhtbNSWwY7aMBCG75X6DpHvS5wQCKCFFVCQeumhS9WzCQ5Yje3IDrC8fcd2WKCBXUJb1MZCJGPnj/1l5ncen1545m2o0kyKPgoaGHlUJHLBxLKPvs2mDx3k6YKIBcmkoH20oxo9DT5+eNz2UikK7cH9Qvd40kerosh7vq+TFeVEN2ROBXSmUnFSwKVa+pyoH+v8IZE8JwWbs4wVOz/EuI1KGXWNikxTltBPMllzKgp7v69oBopS6BXL9V5te43aVqpFrmRCtYY188zpccLEq0wQVYQ4S5TUMi0asJhyRlYKbg+wPePZQaBVTyCsCLQ1rSfRKiV8veP0BXk86X1eCqnIPAMlWJIHs/KsMBqUL9Pb9gTh0P2843OZ2XhOhNQ0gK4NyfoIt6AF2Cwyxm34b+EY+WZgsiJKU6PhBoYunBLOst0+qiQnwnXkrEhW+/iGKGZm5ro0W0LHWs8x6JQHcpEAcvQ0ElbGNE8jidXpnEaCozHwTN8BqICYMU6194Vuva925ueIhNDauAkkIviFcBadJ2Kf9PtEJjDncDKdHoiMIRJ3WqMKke5bROxl4HSuJzKEaZ3PjBCPgENkebhWh4PeMq3/CIeoeQ8OY5KxuWIXSExtJlgGkA93ITH8lUQYxXfJiLFcK0aVqZILNGJg0LU0DJWoFg0uF1SdK5CUvdDFv5YV32ELMVunvuCdlaOGd5J1If8j6xwTDvVBLqSEsUpnmcY66xXIbZaJw+OkiEwkeo1cScJeBt3brMIbyWxx0S9it3Pc4Be182Ji0qBCYzg+Q+OKEqlLY0ZW8P7e3EFcYpid5C/7ZnDOK9q4upOG74EIbvBN+Hhdq93FAjEkzNfWPb4p3CI78YHE8SprFgh+NyXKEz34CQAA//8DAFBLAwQUAAYACAAAACEAqYeqztMBAACtCwAAFAAAAHdvcmQvd2ViU2V0dGluZ3MueG1s7JZNa+MwEIbvC/sfjO6Nvz+pUwilpbAsy7b9AbIsJ2IljZGUuOmvX8V2m7TZQ33aHHzSaEbv4xleYXR98yK4s6NKM5Al8hcecqgkUDO5LtHz091VhhxtsKwxB0lLtKca3Sy/f7vuio5Wj9QYe1I7liJ1IUiJNsa0hetqsqEC6wW0VNpiA0pgY7dq7Qqs/mzbKwKixYZVjDOzdwPPS9CIUV+hQNMwQm+BbAWVpte7inJLBKk3rNVvtO4rtA5U3SogVGs7j+ADT2Am3zF+dAYSjCjQ0JiFHWbsqEdZue/1keBHQDwNEJwBEk2nIeIR4eq9oC/IEaR4WEtQuOKWZEdybFdOD0ZLa2nNdnpcna5gdYmiMIrzOMy8vl5Bvb/tazvM7XVB7iFrDf1BG/OW9d6zv9l684/0E7TnyRUYA+JT3vaxqtUhMkeNtBcR2Y1+PZw7BC0mdIwJcLD3B28NDAh+0tk0ZfWho2ladTr5FKl7HHoIP9qReFmaWTfi2Y5LsCMPvSwPgiCZ7bgIO+I0TNMoCmc7LsEOP8zSKPeSfP5bXYQfgR+kfpZncT778b/8GNb+kQWtYYK90jtQKwWdpqr/GuYcul8/7wf9ySN7+RcAAP//AwBQSwMEFAAGAAgAAAAhALpc8WHcAQAA3QMAABAACAFkb2NQcm9wcy9hcHAueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnFPBbtswDL0P2D8Yujdygi7NAlnFkGLoYVsDxG3PmkwnwmRJkNig2dePthtP2XaaT4+P1NMjKYvb184WR4jJeFex+axkBTjtG+P2FXusP1+tWJFQuUZZ76BiJ0jsVr5/J7bRB4hoIBUk4VLFDohhzXnSB+hUmlHaUab1sVNIYdxz37ZGw53XLx045IuyXHJ4RXANNFdhEmSj4vqI/yvaeN37S0/1KZCeFDV0wSoE+a0/aWeNx07wiRW1R2Vr04G8uSF+isRW7SHJheAjEM8+NknOS2JGKDYHFZVGGqH8sFoJnsXiUwjWaIU0XPnV6OiTb7F4GBwX/XnB8xJBXexAv0SDJ1kKnofii3Fk4FrwEZCzqPZRhQPZ6e1NkdhpZWFD/ctW2QSC/ybEPah+t1tlen9HXB9Bo49FMj9puwtWfFcJ+qlV7KiiUQ7ZWDYGA7YhYZS1QUvaUzzAvCzH5ro3OYLLwiEYPBC+dDfckB5a6g3/YXaemx08jFYzO7mz8x1/qG58F5Sj+fIJ0YB/pMdQ+7v+bbzN8JLMtv5s8LALStNOlquP+f6zjNgRCw0tdNrJRIh76iDaXp/Ouj0055q/E/2Lehr/Vjlfzkr6hid05ughTL+R/AUAAP//AwBQSwECLQAUAAYACAAAACEAtJQBXr8BAACvCAAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQItABQABgAIAAAAIQAekRq37wAAAE4CAAALAAAAAAAAAAAAAAAAAPgDAABfcmVscy8ucmVsc1BLAQItABQABgAIAAAAIQBTJPdGgQEAAHIHAAAcAAAAAAAAAAAAAAAAABgHAAB3b3JkL19yZWxzL2RvY3VtZW50LnhtbC5yZWxzUEsBAi0AFAAGAAgAAAAhAIcEgvmkDAAAskAAABEAAAAAAAAAAAAAAAAA2wkAAHdvcmQvZG9jdW1lbnQueG1sUEsBAi0AFAAGAAgAAAAhAC5uMgNcAgAAxAgAABAAAAAAAAAAAAAAAAAArhYAAHdvcmQvZm9vdGVyMS54bWxQSwECLQAUAAYACAAAACEAUZI/8p8CAAAzCQAAEAAAAAAAAAAAAAAAAAA4GQAAd29yZC9mb290ZXIyLnhtbFBLAQItABQABgAIAAAAIQCOmL+CCwIAADkHAAASAAAAAAAAAAAAAAAAAAUcAAB3b3JkL2Zvb3Rub3Rlcy54bWxQSwECLQAUAAYACAAAACEAo0pYhAgCAAAzBwAAEQAAAAAAAAAAAAAAAABAHgAAd29yZC9lbmRub3Rlcy54bWxQSwECLQAUAAYACAAAACEAOOeS1EUnAACgOgEAFQAAAAAAAAAAAAAAAAB3IAAAd29yZC9tZWRpYS9pbWFnZTEuZW1mUEsBAi0ACgAAAAAAAAAhAKkb6F+KrQAAiq0AAC0AAAAAAAAAAAAAAAAA70cAAHdvcmQvZW1iZWRkaW5ncy9NaWNyb3NvZnRfVmlzaW9fRHJhd2luZzEudnNkeFBLAQItABQABgAIAAAAIQAw3UMpAgYAAKQbAAAVAAAAAAAAAAAAAAAAAMT1AAB3b3JkL3RoZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEAYEsj5sUOAAD0QwAAEQAAAAAAAAAAAAAAAAD5+wAAd29yZC9zZXR0aW5ncy54bWxQSwECLQAUAAYACAAAACEA2qWhnsAYAACIDAEADwAAAAAAAAAAAAAAAADtCgEAd29yZC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhACEwqPDXCgAAY8AAABIAAAAAAAAAAAAAAAAA2iMBAHdvcmQvbnVtYmVyaW5nLnhtbFBLAQItABQABgAIAAAAIQB0Pzl6wgAAACgBAAAeAAAAAAAAAAAAAAAAAOEuAQBjdXN0b21YbWwvX3JlbHMvaXRlbTEueG1sLnJlbHNQSwECLQAUAAYACAAAACEAuC67FeIAAABVAQAAGAAAAAAAAAAAAAAAAADnMAEAY3VzdG9tWG1sL2l0ZW1Qcm9wczEueG1sUEsBAi0AFAAGAAgAAAAhALfxriSvAAAADgEAABMAAAAAAAAAAAAAAAAAJzIBAGN1c3RvbVhtbC9pdGVtMS54bWxQSwECLQAUAAYACAAAACEADOKy0moBAAC7AgAAEQAAAAAAAAAAAAAAAAAvMwEAZG9jUHJvcHMvY29yZS54bWxQSwECLQAUAAYACAAAACEA3JNYaZoCAAB/DAAAEgAAAAAAAAAAAAAAAADQNQEAd29yZC9mb250VGFibGUueG1sUEsBAi0AFAAGAAgAAAAhAKmHqs7TAQAArQsAABQAAAAAAAAAAAAAAAAAmjgBAHdvcmQvd2ViU2V0dGluZ3MueG1sUEsBAi0AFAAGAAgAAAAhALpc8WHcAQAA3QMAABAAAAAAAAAAAAAAAAAAnzoBAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAABUAFQBtBQAAsT0BAAAA"  
      }
    }
  ]
}
```

The good news is that it does not kill the node anymore and allows to extract the text which is in the Office document.

Closes #22077.

### CODE REVIEW

File: plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/AttachmentProcessor.java [hunk 1]
```diff
@@ -127,7 +127,7 @@ public void execute(IngestDocument ingestDocument) {
                 }
                 additionalFields.put(Property.CONTENT_LENGTH.toLowerCase(), length);
             }
-        } catch (Exception e) {
+        } catch (Throwable e) {
```
Comment (jasontedor) [inline plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/AttachmentProcessor.java]: Let's not do this. We worked incredibly hard to remove it from the codebase, see #19231. It just hides bugs, and swallows truly fatal errors.

**Review by jasontedor — CHANGES_REQUESTED** [review]
Sorry @dadoonet.

**Comment by dadoonet** [comment]
@jasontedor Can you tell me what you think of the latest changes? Thanks!

**Comment by jasontedor** [comment]
Why are we doing this instead of adding the missing dependency?

**Comment by javanna** [comment]
I totally agree on not catching Throwable and the effort made to change that in our codebase. That said in this specific case it seems pretty awkward that the node crashes. Is it right to let it go down for a missing dependency problem triggered by some specific call? I guess there is no way to check for this earlier when the node is started?

**Comment by dadoonet** [comment]
> Why are we doing this instead of adding the missing dependency?

Well. We reduced the number of dependencies with this PR: https://github.com/elastic/elasticsearch-mapper-attachments/pull/186.
IIRC we wanted to avoid some Security Manager issues with 3rd party libs and some JarHell issues.

We ended up saying that we will only support a subset of files. Here the user is sending a Word document which is supported but within the Word document he is having an embedded Visio Chart, which we don't support.
Probably we can fix the issue for Visio. But then, what will be the next problem? MP3?

I think that killing a node because a end user is sending a non supported format should be prevented.

@javanna No we can't check that on startup because it depends on the end user's request.

**Comment by rjernst** [comment]
> Is it right to let it go down for a missing dependency

Yes, it is. We (developers) did not setup the system correctly. We didn't find the problem because of inadequate tests. Let's fix the tests, not try to mask the problems.

The underlying issue is the OOXMLParser in tika is poorly designed (all static functions) and does not allow overriding which embedded formats are supported. If we are going to handle this by catching (instead of adding the dependency), then it should be completely local and specific to this case, not general purpose for all of tika (so we don't mask other issues). OOXMLParser is subclassable, where we can catch the NCDFE, not throwable. But such a hack should only be done after opening an issue in tika (and referencing in a comment with the hacky catch).

We also desperately need more tests, ideally each type of embedded file (and there are a limited number of these that are possible, so we should try to cover each one). I believe tika has an extensive collection of files for testing, perhaps we can reuse some of those?

**Comment by dadoonet** [comment]
> so we don't mask other issues

We don't mask it here. We fail the ingestion with an error message which tells what is happening.

```java
throw new ElasticsearchParseException("Missing classes to parse document in field [{}]", e, field);
```

We just don't kill anymore the node.

Definitely I don't want to hide any error.

**Comment by javanna** [comment]
I think everybody agrees that we should not blindly catch Throwable in our code. We made efforts to not hide OOM errors and such, and we don't want to go back there for sure. But, maybe I didn't state it clearly, I don't think it is acceptable that a node crashes because of a missing dependency. We are currently exposing an api that can kill a node, that is a big concerning problem to me. I am not confident that this category of errors with the attachment processor can be solved by testing, cause so many things can go wrong with tika and the many formats it supports. For sure catching `NoClassDefFoundError` is not an elegant solution, it's far from ideal, but is there a better alternative that doesn't involve crashing a node then?

**Comment by clintongormley** [comment]
> But, maybe I didn't state it clearly, I don't think it is acceptable that a node crashes because of a missing dependency. We are currently exposing an api that can kill a node, that is a big concerning problem to me.

+1

**Comment by nik9000** [comment]
I think if we should add the dependency we should add the dependency and consider that the bug that caused the thing to go down, not the lack of catch. If we don't want the dependency we should figure out some way to work around not having it. I don't think we should have a global "catch NoClassDefError" across all of our code because we don't want to hide other problems. If the way work around this is by catching the Error then I'm all for adding it, but I agree with @rjernst that we should file an issue with tika. If they intend for us to be able to run without the dependency then they should throw a friendlier exception. If they don't intend for us to be able to run without the dependency then we have more thinking to do....

**Comment by javanna** [comment]
> I don't think we should have a global "catch NoClassDefError" across all of our code because we don't want to hide other problems.

David is introducing a catch in the `AttachmentProcessor`, that is not a global catch. Anyways, I do see how it is not the most elegant solution. Even if we are going to add this missing jar back and testing this case explicitly and filing an issue to tika, I wonder how long it will take for a similar error to arise due to another missing dependency which we haven't yet tested. Can we really make sure that we test all the possible situations here?

**Comment by nik9000** [comment]
> David is introducing a catch in the AttachmentProcessor, that is not a global catch.

Right. I'm cool with it.

> Can we really make sure that we test all the possible situations here?

That argument makes sense to me. Something along the lines of "Tika throws these instead of UnsupportedOperationException when you are missing an optional dependency." is fine reasoning for adding it. I think we should file an issue with Tika about it. I'd like to be able to remove it one day and catch something that is less likely to mask other weird stuff.

**Comment by dadoonet** [comment]
So what is the outcome on this? Do we want to merge my PR?
I opened https://issues.apache.org/jira/browse/TIKA-2208 to see if they can do anything better on their side.

**Comment by jasontedor** [comment]
I agree that taking a node down in this situation is bad, but I disagree with the conclusion that we should catch `NoClassDefFoundError` here. Catching `NoClassDefFoundError` is too blunt, it catches more than just a missing dependency for an embedded document format that we do not support (for example, a class initializer that throws will cause a `NoClassDefFoundError` too; [JLS 12.4.2](http://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.4.2)):

> 5. If the `Class` object for `C` is in an erroneous state, then initialization is not possible. Release `LC` and throw a `NoClassDefFoundError`.

Like @rjernst said, we need to work this one on the Tika side.

**Comment by dadoonet** [comment]
I'm going to test the workaround proposed on the JIRA and will update the PR if successful.

**Comment by jasontedor** [comment]
Thanks @dadoonet.

**Comment by dadoonet** [comment]
For information, the proposed workaround does not work in our case as I explained at https://issues.apache.org/jira/browse/TIKA-2208?focusedCommentId=15753790&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15753790

Basically, the Tika checks are made when Tika instance is created not when it is used.

I can obviously fix the current problem by adding the missing library but I think that it will hide potential other issues with missing JARs.
May be we can do something on Gradle side which checks that when we add an explicit dependency like `org.apache.poi:poi-ooxml:3.15`, all the needed transitive dependencies are also declared?

**Comment by dadoonet** [comment]
I pushed another commit based on the latest discussions I had with Tika team.
I also changed the title and the description of the PR.

What it does now:

* We still don't support Visio files
* If an embedded Visio content exists in a Word `docx` file, its extraction is now skipped
* Which means that we don't fail anymore, we don't have any exception and cherry on the cake, the text coming from the `docx` file is extracted!

File: plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/TikaImpl.java [hunk 2]
```diff
@@ -54,6 +59,12 @@
  */
 final class TikaImpl {
 
+    /** Exclude some formats */
+    private static final Set<MediaType> EXCLUDES =
```
Comment (nik9000) [inline plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/TikaImpl.java]: This is usually easier to write as `Collections.singleton("x-tika-ooxml")`.

Comment (nik9000) [inline plugins/ingest-attachment/src/main/java/org/elasticsearch/ingest/attachment/TikaImpl.java]: Er, `Collections.singleton(MediaType.application("x-tika-ooxml"))` actually.

**Review by nik9000 — APPROVED** [review]
Change makes sense and is what upstream advises and tests make sense.

**Comment by dadoonet** [comment]
@jasontedor Can you also please update your review? Thanks!

**Review by jasontedor — APPROVED** [review]
Thanks for your work on this @dadoonet, I think that we got to the right place. LGTM.

**Comment by dadoonet** [comment]
So this is making our tests failing now.
I need to dig more. 

`testPPT.potm` Tika sample file is now returned with an empty content as soon as we add `Collections.singleton(MediaType.application("x-tika-ooxml")`.

**Comment by dadoonet** [comment]
I checked the full suite of documents we have and only `testPPT.potm` is now failing.
I asked on [Tika project](https://issues.apache.org/jira/browse/TIKA-2208?focusedCommentId=15758867&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15758867) to see if we have a workaround.

If not, we have 2 choices I believe:

* Revert completely my change and just add missing libraries
* remove support of `potm` files

From http://www.reviversoft.com/file-extensions/potm:

> The POTM file extension is used to label macro-enabled templates created by Microsoft’s PowerPoint, a well-known software used to create presentations with the use of slide shows. 

So I think we should better add missing lib. But it will never prevent not parseable embedded content.
We can just expect that Tika is able to handle such a case instead of throwing a ClassNotFoundError.

**Comment by dadoonet** [comment]
I tried to add missing libs:

```gradle
  compile "com.github.virtuald:curvesapi:1.04"
  compile "com.bbn.poi.visio:ooxml-visio-schemas:2011.1"
```

But it now fails with JarHell:

```
Caused by: java.lang.IllegalStateException: jar hell!
class: com.microsoft.schemas.office.visio.x2012.main.CellType$Factory
jar1: /Users/dpilato/.gradle/caches/modules-2/files-2.1/org.apache.poi/poi-ooxml-schemas/3.15/de4a50ca39de48a19606b35644ecadb2f733c479/poi-ooxml-schemas-3.15.jar
jar2: /Users/dpilato/.gradle/caches/modules-2/files-2.1/com.bbn.poi.visio/ooxml-visio-schemas/2011.1/5c395aefc5c1a33f517c243843c909c1f4d6b3f0/ooxml-visio-schemas-2011.1.jar
```

**Comment by dadoonet** [comment]
@jasontedor Do you have any idea on how I could fix https://github.com/elastic/elasticsearch/pull/22079#issuecomment-267823297?

**Comment by jasontedor** [comment]
> > The POTM file extension is used to label macro-enabled templates created by Microsoft’s PowerPoint, a well-known software used to create presentations with the use of slide shows.

Do we really need to support this, it seems obscure?

**Comment by sergeytkachenko** [comment]
Hello everybody.
The error persists?
We have this problem in production ES 5.2.0

**Comment by dadoonet** [comment]
@sergeytkachenko About your error here, I think we probably don't want to support indexing Visio files. At least we don't mean to support them. I'm going to try to have a proper rejection when you index a Visio file instead of killing the node like this.
But the issue we have within this thread is happening when you have a Visio content (not supported) embedded within a Word document (supported).

Thanks for sharing your Visio file BTW!

**Comment by dadoonet** [comment]
Actually I was wrong. This PR removes support for Visio files even embedded. I'm going to update the PR soonish.

**Comment by dadoonet** [comment]
@jasontedor So I removed support for POTM files. I rebased on master and squashed everything. Could you check again this PR?

**Comment by jasontedor** [comment]
I am missing in this pull request where support for POTM files was removed?

Also, please do not squash commits in the middle of review cycles. You can merge master into your branch instead of rebasing, too.

**Comment by dadoonet** [comment]
@jasontedor `POTM` is removed in the zip file. That's why you can't see it and why I opened #22958

**Comment by dadoonet** [comment]
I'm going to push a new commit to my branch because I just merged #22959 so you will see in a more obvious way the POTM file removal.

**Comment by dadoonet** [comment]
@jasontedor I merged with master so it's ready. Can you review it please?

**Comment by sergeytkachenko** [comment]
@dadoonet thank you repaired, and now we do not have such an error!

**Comment by dadoonet** [comment]
@sergeytkachenko Do you mean that you tried out that branch?

**Comment by sergeytkachenko** [comment]
@dadoonet Yes! 
I build elasticsearch 6 and ingest-attachemnt 6 plugin with gradel from fix/22077-ingest-attachment branch. 
And error has gone.
Thank you very match!

**Comment by dadoonet** [comment]
Thanks for testing it @sergeytkachenko. 

You can apply the same fix on 5.2.0 tag and build another version of the plugin if it's a blocker for your production.

**Comment by dadoonet** [comment]
If no one objects in the meantime, I'll merge that change tomorrow morning CET.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dadoonet** [comment]
Thanks @jasontedor !
