### PR TITLE
[apm-data] Apply lazy rollover on index template creation

### LINKED ISSUE #116230: apm-data plugin does not automatically roll over existing APM data streams when upgrading to 8.15.x
### Elasticsearch Version

8.15.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

The apm-data plugin installs index templates that should trigger a lazy rollover for data streams with matching index patterns, if the index templates have the highest priority. The rollover logic is only triggering on upgrade, and not on the first installation, so data streams that were previously managed by the Fleet integration package will not be rolled over automatically when upgrading.

### Steps to Reproduce

1. Create an 8.14.x Elastic Cloud deployment, send some APM data to populate data streams
2. Upgrade deployment to 8.15.x
3. Observe that none of the data streams have been (lazily) rolled over

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by axw**
Trigger a lazy rollover of existing data streams regardless of whether the index template is being created or updated. This ensures that the apm-data plugin will roll over data streams that were previously using the Fleet integration package.

Fixes https://github.com/elastic/elasticsearch/issues/116230

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java [hunk 1]
```diff
@@ -793,41 +797,43 @@ private void invokeRollover(
...
-                    new ActionListener<>() {
-                        @Override
-                        public void onResponse(Collection<RolloverResponse> rolloverResponses) {
-                            creationCheck.set(false);
-                            onRolloversBulkResponse(rolloverResponses);
-                        }
+            if (rolloverTargets.isEmpty()) {
+                creationCheck.set(false);
+                return;
+            }
```
Comment (axw) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:803]: This fixes another bug: we were never setting creationCheck to false in the case where there were no data streams to roll over on upgrade. This led to the plugin not recreating templates as intended, as the registry thought template creation was perpetually in-progress.

Comment (axw) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:803]: BTW without this change, the existing YAML REST tests would fail with the change to trigger the rollover path on template creation. I've also added a test case for template reinstallation for good measure.

**Review by felixbarny — APPROVED** [review]
LGTM, but the data management team should also have a look.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java (hunk 1 above)
Comment (gmarouli) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:803]: Nice catch! I would recommend to change the code a bit to make this less error prone. I think it will be easier if the responsibility to reset the check flag would happen in one spot. I think it would be nice to move to https://github.com/elastic/elasticsearch/pull/116219/files#diff-a74931128493bfa2cd8c35c1bf3378014fd64c596c4bfbea0f91ddedd5db7011R552-R555.

For example:

```
 if (applyRolloverAfterTemplateV2Update()) {
       invokeRollover(state, templateName, indexTemplate, () -> creationCheck.set(false));
} else {
     creationCheck.set(false);
}
```

Then the `invokeRollover` would apply it accordingly:
```
    private void invokeRollover(
        final ClusterState state,
        final String templateName,
        final ComposableIndexTemplate indexTemplate,
        Runnable runAfter
    ) {
        final Executor executor = threadPool.generic();
        executor.execute(() -> {
            List<String> rolloverTargets = findRolloverTargetDataStreams(state, templateName, indexTemplate);
            if (rolloverTargets.isEmpty()) {
                runAfter.run();
                return;
            }
            ActionListener<RolloverResponse> groupedActionListener = ActionListener.runAfter(new GroupedActionListener<>(
                rolloverTargets.size(),
                new ActionListener<>() {
                    @Override
                    public void onResponse(Collection<RolloverResponse> rolloverResponses) {
                        onRolloversBulkResponse(rolloverResponses);
                    }

                    @Override
                    public void onFailure(Exception e) {
                        onRolloverFailure(e);
                    }
                }), runAfter);
            for (String rolloverTarget : rolloverTargets) {
                logger.info(
                    "rolling over data stream [{}] lazily as a followup to the upgrade of the [{}] index template [{}]",
                    rolloverTarget,
                    getOrigin(),
                    templateName
                );
                RolloverRequest request = new RolloverRequest(rolloverTarget, null);
                request.lazy(true);
                request.masterNodeTimeout(TimeValue.MAX_VALUE);
                executeAsyncWithOrigin(
                    client.threadPool().getThreadContext(),
                    getOrigin(),
                    request,
                    groupedActionListener,
                    (req, listener) -> client.execute(RolloverAction.INSTANCE, req, listener)
                );
            }
        });
    }
```

The benefit of the above, is that `creationCheck` would be reset once when all the listeners have finished (assuming my understanding is correct) and the responsibility lies on the first snippet to declare that there is something that needs to be run and the `invokeRollover` needs to apply that `runAfter`, whatever that is.

Does this make sense? By the way this is a draft, if you like the suggestion please test it also ;)

File: x-pack/plugin/apm-data/src/yamlRestTest/resources/rest-api-spec/test/10_rollover.yml [hunk 2]
```diff
@@ -0,0 +1,54 @@
+---
+setup:
+  - do:
+      cluster.health:
+        wait_for_events: languid
```
Comment (gmarouli) [inline x-pack/plugin/apm-data/src/yamlRestTest/resources/rest-api-spec/test/10_rollover.yml:5]: It is not clear to me why we are waiting here

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java (hunk 1 above)
Comment (axw) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:803]: :+1: I like it, thanks for the suggestion. I agree that it's a bit error prone (evidently!) with the way it's spread around at the moment. I will test and push an update shortly.

**Review by gmarouli — COMMENTED** [review]
Nice work @axw , in general it looks really good. I added some suggestions, let me know what you think.

File: x-pack/plugin/apm-data/src/yamlRestTest/resources/rest-api-spec/test/10_rollover.yml (hunk 2 above)
Comment (axw) [reply x-pack/plugin/apm-data/src/yamlRestTest/resources/rest-api-spec/test/10_rollover.yml:5]: The intention here is to wait for the apm-data plugin to install the templates. Is that not necessary, or is there a better way?

Comment (gmarouli) [reply x-pack/plugin/apm-data/src/yamlRestTest/resources/rest-api-spec/test/10_rollover.yml:5]: In general this increases the chances that the templates would be installed before the test runs, but it doesn't guarantee it. So, in this specific case, I do not think it adds anything for two reasons:

1. The only test in this suite disables the apm plugin.
2. You skip the test anyway because we cannot guarantee that the templates will be installed, so why wait?

Comment (axw) [reply x-pack/plugin/apm-data/src/yamlRestTest/resources/rest-api-spec/test/10_rollover.yml:5]: Fair. The real reason it's there is because I copied another test ;)
I'll remove the setup from this file.

**Review by gmarouli — APPROVED** [review]
LGTM, I would still recommend to remove the waiting in the `10_rollover.yml` test, but it's minor. Good work @axw 🚀

**Review by lahsivjar — APPROVED** [review]
LGTM! one minor doubt/concern.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java [hunk 3]
```diff
@@ -550,8 +549,8 @@ private void putComposableTemplate(
                     @Override
                     public void onResponse(AcknowledgedResponse response) {
                         if (response.isAcknowledged()) {
-                            if (isUpgrade && applyRolloverAfterTemplateV2Upgrade()) {
-                                invokeRollover(state, templateName, indexTemplate, creationCheck);
+                            if (applyRolloverAfterTemplateV2Update()) {
```
[the remark this answers is not in the document]
Comment (axw) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:552]: I'm not sure I understand the scenario. Do you mean a negative check, verifying something that does not match the index pattern is rolled over? I think the existing `IndexTemplateRegistryTests.testAutomaticRollover` covers that: it creates two logs and one traces data stream, and verifies that only the logs ones are rolled over when updating the logs template.

[the remark this answers is not in the document]
Comment (lahsivjar) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java:552]: Not exactly a negative check -- my concern is when plugins operate under normal circumstances then there is no need for migrating datastream to the plugin. I was thinking of having a test case to cover this scenario. Does it make sense?

**Comment by lahsivjar** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/116244)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
