### PR TITLE
Decode max and min optimization more carefully

### LINKED ISSUE #52220: Unexpected behaviour for min - max aggregations on date_nanos type
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.0-SNAPSHOT

**build_hash** : "6653ed095a2fa342c9f58ddefd03dd47fb72b5d7",

**build_date** : "2020-02-11T02:35:28.882468Z",

**Plugins installed**: [`repository-gcs-7.6.0-SNAPSHOT.zip`]

**JVM version** (`java -version`): openjdk version "12.0.2"

**OS version** (`uname -a` if on a Unix-like system): 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

Computing the min and max aggregations on a `date_nanos` field produce an unexpected `"value_as_string"` string representation value.

If a query range is added to manually specify the upper limit, the problem does not arise. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
```
PUT /test
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "properties" : {
        "@timestamp" : {
          "type" : "date_nanos",
          "format" : "yyyy-MM-dd HH:mm:ss.SSSSSSSSS"
        }
        }
    }
}
```

 2.
```
PUT /test/_doc/1
{
  "@timestamp": "2015-01-01 00:10:00.838000000"
}

PUT /test/_doc/2
{
  "@timestamp": "2016-01-01 00:00:00.575000000"
}
```
 3.

```
GET /test/_search
{
  "size": 0, 
  "aggs": {
    "min": {
      "min": {
        "field": "@timestamp"
      }
    },
    "max" : {
      "max": {
        "field": "@timestamp"
      }
    }
  }
}
```

this produces the following output:

```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "min" : {
      "value" : 1.42007100083800013E18,
      "value_as_string" : "+45002228-08-10 03:26:40.128000000"
    },
    "max" : {
      "value" : 1.45160640057500006E18,
      "value_as_string" : "+46001545-08-23 15:43:20.064000000"
    }
  }
}
```

4. Now, if we add a range

```
GET /test/_search
{
  "size": 0, 
  "query": {
    "range": {
      "@timestamp": {
        "lte": "2016-01-01 00:00:00.575000000"
      }
    }
  }, 
  "aggs": {
    "min": {
      "min": {
        "field": "@timestamp"
      }
    },
    "max" : {
      "max": {
        "field": "@timestamp"
      }
    }
  }
}
```
We get the right values:

```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "min" : {
      "value" : 1.420071000838E12,
      "value_as_string" : "2015-01-01 00:10:00.838000000"
    },
    "max" : {
      "value" : 1.451606400575E12,
      "value_as_string" : "2016-01-01 00:00:00.575000000"
    }
  }
}
```

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by nik9000**
Fixes the the no-query optimization for `min` and `max` aggregations
for `date_nanos` fields by delegating decoding dates "through" their
`resolution` member.

Closes #52220

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/MaxAggregator.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ public LeafBucketCollector getLeafCollector(LeafReaderContext ctx,
         if (pointConverter != null) {
             Number segMax = findLeafMaxValue(ctx.reader(), pointField, pointConverter);
             if (segMax != null) {
-                /**
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/MaxAggregator.java]: This was a javadoc comment in an invalid spot for javadoc.

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java [hunk 2]
```diff
@@ -799,21 +815,6 @@ public void testMinShortcutRandom() throws Exception {
             (v) -> DoublePoint.decodeDimension(v, 0));
     }
 
-    private void testMinCase(IndexSearcher searcher,
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java]: This isn't used any more.

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java [hunk 3]
```diff
@@ -889,12 +890,17 @@ private Aggregator mockAggregator() {
         return config;
     }
 
-    private ValuesSourceConfig<ValuesSource.Numeric> mockDateValuesSourceConfig(String fieldName, boolean indexed) {
+    private ValuesSourceConfig<ValuesSource.Numeric> mockDateValuesSourceConfig(String fieldName, boolean indexed,
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java]: There is a *ton* more ceremony here because `resolution` is only set when you call `build`. Bleh.

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java [hunk 4]
```diff
@@ -740,41 +743,54 @@ public void testShortcutIsApplicable() {
...
-                null,
-                mockDateValuesSourceConfig("number", true)
-            )
-        );
         assertNull(
             MinAggregator.getPointReaderOrNull(
                 mockSearchContext(new MatchAllDocsQuery()),
                 mockAggregator(),
-                mockDateValuesSourceConfig("number", true)
+                mockDateValuesSourceConfig("number", true, randomFrom(DateFieldMapper.Resolution.values()))
```
Comment (not-napoleon) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java]: I'm a little uncomfortable using a randomization for coverage here.  I'd rather loop over the possible resolution values like we loop over the possible numeric types above.

**Review by not-napoleon — APPROVED** [review]
LGTM

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java (hunk 4 above)
Comment (nik9000) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/MinAggregatorTests.java]: Sure!

**Comment by nik9000** [comment]
Thanks @not-napoleon !
