### PR TITLE
Fix synthetic source for flattened field when used with ignore_above

### LINKED ISSUE #112044: Synthetic source is wrong for arrays of flattened fields containing subfields longer than ignore_above
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

x

### Problem Description

Synthetic source is wrong for arrays of flattened fields containing fields longer than ignore_above.

### Steps to Reproduce

```
PUT /my_index
{
  "mappings": {
    "_source": { "mode": "synthetic" },
    "properties": {
      "n": {
        "type": "flattened",
        "ignore_above": 4
      }
    }
  }
}

PUT my_index/_doc/1
{
  "n": [
    {
      "foo": "bar"
    },
    {
      "foo": "bazzzzzzz"
    }
  ]
}

GET my_index/_doc/1
```

Produces:
```
"_source": {
    "n": {
        "foo": "bazzzzzzz"
    }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lkts**
Previously if any leaf field in `flattened` field value was ignored due to `ignore_above` setting we would store the entire object in ignored source. This is not correct since it is possible that another object will be indexed which does not have any ignored leaf fields. Since ignored source takes precedence over native synthetic source, second object would be lost in such scenario.

This PR changes the approach to instead only store leaf values that are ignored in a dedicated stored field. When synthetic source is synthesized these values are merged with doc values to produce a document.

Closes #112044.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldSyntheticWriterHelper.java [hunk 1]
```diff
@@ -226,19 +225,27 @@ public boolean equals(Object obj) {
...
+        KeyValue curr = new KeyValue(sortedKeyedValues.next());
         KeyValue prev = KeyValue.EMPTY;
         final List<String> values = new ArrayList<>();
         values.add(curr.value());
-        for (int i = 1; i < dv.docValueCount(); i++) {
-            KeyValue next = new KeyValue(dv.lookupOrd(dv.nextOrd()));
+        while (true) {
+            BytesRef nextValue = sortedKeyedValues.next();
+            if (nextValue == null) {
+                break;
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldSyntheticWriterHelper.java:246]: Nit: `for (BytesRef nextValue = sortedKeyedValues.next(); nextValue != null; nextValue = sortedKeyedValues.next()) {`

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java [hunk 2]
```diff
@@ -110,8 +155,65 @@ public int count() {
...
+        private DocValuesWithIgnoredSortedKeyedValues(
+            FlattenedFieldSyntheticWriterHelper.SortedKeyedValues docValues,
+            TreeSet<BytesRef> ignoredValues
+        ) {
+            this.docValues = docValues;
+            this.ignoredValues = ignoredValues;
+        }
+
+        @Override
+        public BytesRef next() throws IOException {
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java:178]: Nit: let's add some high-level comments below so that we remember the logic in a year from now.

File: server/src/test/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldMapperTests.java [hunk 3]
```diff
@@ -742,11 +748,71 @@ private static class FlattenedFieldSyntheticSourceSupport implements SyntheticSo
 
         @Override
         public SyntheticSourceExample example(int maxValues) throws IOException {
-            // NOTE: values must be keywords and we use a TreeMap to preserve order (doc values are sorted and the result
-            // is created with keys and nested keys in sorted order).
-            final TreeMap<Object, Object> map = new TreeMap<>();
-            randomMapExample(map, 0, maxValues);
-            return new SyntheticSourceExample(map, map, this::mapping);
+            if (randomBoolean()) {
+                var value = randomObject();
```
Comment (kkrik-es) [inline server/src/test/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldMapperTests.java:752]: `// Return a singleton value`

File: server/src/test/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldMapperTests.java [hunk 4]
```diff
@@ -742,11 +748,71 @@ private static class FlattenedFieldSyntheticSourceSupport implements SyntheticSo
...
+                return new SyntheticSourceExample(value, mergeIntoExpectedMap(List.of(value)), this::mapping);
+            }
+
+            var values = new ArrayList<Map<String, Object>>();
```
Comment (kkrik-es) [inline server/src/test/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldMapperTests.java:756]: `// Return an array of flattened values`

**Review by kkrik-es — APPROVED** [review]
Looks good overall, can we also add the yaml test with the repro?

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldParser.java [hunk 5]
```diff
@@ -151,19 +133,24 @@ private void parseFieldValue(
...
         }
+
         String keyedValue = createKeyedValue(key, value);
         BytesRef bytesKeyedValue = new BytesRef(keyedValue);
+
+        if (value.length() > ignoreAbove) {
+            if (context.documentParserContext().mappingLookup().isSourceSynthetic()) {
+                fields.add(new StoredField(keyedIgnoredValuesFieldFullPath, bytesKeyedValue));
+            }
+
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldParser.java:150]: nit: unneeded newline

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java [hunk 6]
```diff
@@ -13,27 +13,43 @@
...
 import java.io.IOException;
+import java.util.ArrayList;
+import java.util.List;
+import java.util.Map;
+import java.util.TreeSet;
+import java.util.stream.Stream;
 
-public class FlattenedSortedSetDocValuesSyntheticFieldLoader extends SourceLoader.DocValuesBasedSyntheticFieldLoader {
-    private DocValuesFieldValues docValues = NO_VALUES;
+public class FlattenedSortedSetDocValuesSyntheticFieldLoader implements SourceLoader.SyntheticFieldLoader {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java:27]: I think this class visibility can be reduced to package protected?

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java [hunk 7]
```diff
@@ -13,27 +13,43 @@
...
     private final String fieldFullPath;
     private final String keyedFieldFullPath;
+    private final String keyedIgnoredValuesFieldFullPath;
     private final String leafName;
 
+    private DocValuesFieldValues docValues = NO_VALUES;
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java:33]: Can we just use `SortedSetDocValues` here directly instead of using an additional layer of abstraction? 

For example in `DocValuesSortedKeyedValues` we directly sorted set doc values instead of `DocValuesFieldValues` as an intermediate interface.

Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java:33]: Do we need the `DocValuesFieldValues` interface at all? It is either no value or uses `SortedSetDocValues`. Maybe we always use `SortedSetDocValues` directly and in case of no value it is null?

**Review by martijnvg — APPROVED** [review]
LGTM - I like that flattened field now uses its own stored fields for ignore above instead of relying on ignored source infrastructure. Left a question and two nits.

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java (hunk 7 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java:33]: I was actually looking at that too. I believe we can't directly use `SortedSetDocValues` because when there is no doc values, it contains an empty singleton which we don't expect. We could just set it to null indeed.

**Comment by lkts** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java (hunk 7 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedSortedSetDocValuesSyntheticFieldLoader.java:33]: So `FlattenedFieldDocValuesLoader` also tracks if current document has doc values and i think inlining all this logic into `FlattenedSortedSetDocValuesSyntheticFieldLoader` reduces readability quite a bit. I'll keep this as is.

**Comment by lkts** [comment]
Failures are not related.

**Comment by lkts** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/113568)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
