### PR TITLE
Fix Broken Snapshot State Machine in Corner Case

### LINKED ISSUE #63498: [CI] ConcurrentSnapshotsIT.testDeletesAreBatched fails
**Build scan**: https://gradle-enterprise.elastic.co/s/ddwl7fzpvxuck

**Repro line**:
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testDeletesAreBatched" \
  -Dtests.seed=B05CAAB2F86ED160 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=sq-AL \
  -Dtests.timezone=Indian/Mauritius \
  -Druntime.java=8

**Reproduces locally?**:
no

**Applicable branches**:
7.x

**Failure history**:
Another one on 7.9 on Oct 8th:https://gradle-enterprise.elastic.co/s/q5pxw3i4jidi2
Two more back in August: 
https://gradle-enterprise.elastic.co/s/4onwuh6duap5g
https://gradle-enterprise.elastic.co/s/vx64ubpuwjwbc

**Failure excerpt**:
java.lang.AssertionError: 
Expected: is <SUCCESS>
     but: was <PARTIAL>
	at __randomizedtesting.SeedInfo.seed([B05CAAB2F86ED160:94FBBD6B29151D05]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testDeletesAreBatched(ConcurrentSnapshotsIT.java:141)

### PR DESCRIPTION
**Pull request by original-brownbear**
This fixes a gap in testing and a bug that can occur in various forms:
When we would start a snapshot or clone related to a shard that was done
snapshotting/cloning but its overall operation was not yet finalized
at the time of starting the operation, we would base the operation off of
the wrong generation. This would not cause a corrupted repo, but would
cause the operation to be `PARTIAL`.
This commit fixes the state machine to take into account the correct generation
in this case.

Closes #63498

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java [hunk 1]
```diff
@@ -1248,6 +1248,33 @@ public void testAbortNotStartedSnapshotWithoutIO() throws Exception {
         assertThat(getRepositoryData(repoName).getGenId(), is(0L));
     }
 
+    public void testStartWithSuccessfulShardSnapshotPendingFinalization() throws Exception {
```
Comment (original-brownbear) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:1251]: Sorry for making this so complicated, but this required 4 new tests I'm afraid because you can have all possible combinations of clone or snapshot ready for a shard but not finalized and then wanting to run either a new clone or new snapshot => 2 x 2 = 4 possible buggy scenarios.

File: server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+import java.util.Set;
+
+/**
+ * Holds information about currently in-flight shard level snapshot or clone operations on a per-shard level.
+ * Concretely, this means information on which shards are actively being written to in the repository currently
+ * as well as the latest written shard generation per shard in case there is a shard generation for a shard that has
+ * been cleanly written out to the repository but not yet made part of the current {@link org.elasticsearch.repositories.RepositoryData}
+ * through a snapshot finalization.
+ */
+public final class InFlightShardSnapshotStates {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java:44]: I was really torn about adding a new class for this one, but I figured adding this logic to `SnapshotsInProgress` or `SnapshotsService` isn't so great because those two classes are already very very complicated. This way we can at least take some of the complication out of them?

File: test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java [hunk 3]
```diff
@@ -111,8 +111,15 @@ public long getFailureCount() {
...
+    /**
+     * Allows blocking on writing the index-N blob and subsequently failing it on unblock.
+     * This is a way to enforce blocking the  finalization of a snapshot, while permitting other IO operations to proceed unblocked.
+     */
+    private volatile boolean blockAndFailOnWriteIndexFile;
+
+    /**
+     * Same as {@link #blockAndFailOnWriteIndexFile} but proceeds without error after unblock.
+     */
     private volatile boolean blockOnWriteIndexFile;
```
Comment (original-brownbear) [inline test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java:123]: Not having this was a serious gap in our testing unfortunately. We've had various test failures that were essentially the result of a race with physically writing the next index generation while the repo wasn't yet in a consistent state. The new tests using this significantly up the coverage of this scenario (at the annoying cost of making this class yet again more complex).

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 4]
```diff
@@ -484,26 +484,22 @@ public ClusterState execute(ClusterState currentState) {
...
                                 final RepositoryShardId repoShardId = new RepositoryShardId(count.v1(), shardId);
-                                if (busyShardsInRepo.contains(repoShardId)) {
+                                final String indexName = repoShardId.indexName();
+                                if (inFlightShardStates.isBusy(indexName, shardId)) {
                                     clonesBuilder.put(repoShardId, ShardSnapshotStatus.UNASSIGNED_QUEUED);
                                 } else {
-                                    clonesBuilder.put(repoShardId,
-                                            new ShardSnapshotStatus(localNodeId, shardGenerations.getShardGen(count.v1(), shardId)));
+                                    clonesBuilder.put(repoShardId, new ShardSnapshotStatus(localNodeId,
+                                        inFlightShardStates.bestGeneration(repoShardId.index(), shardId, shardGenerations)));
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:502]: Obvious bug here and in snapshot creation in hindsight ... fortunately this was not something that would corrupt the repository but it would lead to a lot of partial snapshots in practice (seen this in prod. logs as well not just this test failure).

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java [hunk 5]
```diff
@@ -435,7 +435,7 @@ public void testMasterFailOverWithQueuedDeletes() throws Exception {
         final ActionFuture<AcknowledgedResponse> firstDeleteFuture = startDeleteFromNonMasterClient(repoName, firstSnapshot);
         awaitNDeletionsInProgress(1);
 
-        blockDataNode(repoName, dataNode2);
+        blockNodeOnAnyFiles(repoName, dataNode2);
```
Comment (original-brownbear) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:438]: The fact that we would block on data files here even though snapshot `3`  and snapshot `2` were snapshotting the same data actually already demonstrated the bug in hindsight. Since this test forces an exception on this snapshot below this was hidden from us unfortunately.

**Comment by original-brownbear** [comment]
I believe this will also fix https://github.com/elastic/elasticsearch/issues/63473

File: server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+     * snapshots or clones have set a relevant generation and then falling back to {@link ShardGenerations#getShardGen}
+     * if not.
+     *
+     * @param indexId          index id of the shard
+     * @param shardId          shard id of the shard
+     * @param shardGenerations current shard generations in the repository data
+     * @return most recent shard generation for the given shard
+     */
+    @Nullable
+    String bestGeneration(IndexId indexId, int shardId, ShardGenerations shardGenerations) {
```
Comment (fcofdez) [inline server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java:133]: I find this method name a bit confusing. Maybe we should rename it to `generationForShard` or something along those lines?

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/CloneSnapshotIT.java [hunk 7]
```diff
@@ -469,6 +470,105 @@ public void testDoesNotStartOnBrokenSourceSnapshot() throws Exception {
...
+        final ActionFuture<CreateSnapshotResponse> otherSnapshot = startFullSnapshot(repoName, "other-snapshot");
+        awaitNumberOfSnapshotsInProgress(2);
+        assertFalse(blockedClone.isDone());
+        unblockNode(repoName, masterName);
+        awaitNumberOfSnapshotsInProgress(1);
+        awaitMasterFinishRepoOperations();
+        unblockNode(repoName, dataNode);
+        assertAcked(blockedClone.get());
+        assertEquals(getSnapshot(repoName, cloneName).state(), SnapshotState.SUCCESS);
+        assertSuccessful(otherSnapshot);
```
Comment (fcofdez) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/CloneSnapshotIT.java:500]: I guess that it's enough to assert that the snapshot is successful to ensure that they get the corresponding generation number? otherwise it would be a partial snapshot, right?

File: server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java (hunk 2 above)
Comment (fcofdez) [reply server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java:44]: I think it was a good idea to factor out this into its own class. The client code is easier to read.

**Review by fcofdez — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+    }
+
+    /**
+     * Check if a given shard currently has an actively executing shard operation.
+     *
+     * @param indexName name of the shard's index
+     * @param shardId   shard id of the shard
+     * @return true if shard has an actively executing shard operation
+     */
+    boolean isBusy(String indexName, int shardId) {
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java:118]: Maybe `isActive()`? I find that using busy / active wording is too much.

File: test/framework/src/main/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java [hunk 9]
```diff
@@ -570,4 +579,17 @@ protected SnapshotInfo getSnapshot(String repository, String snapshot) {
...
         return snapshotInfos.get(0);
     }
+
+    protected void awaitMasterFinishRepoOperations() throws Exception {
+        logger.info("--> waiting for master to finish all repo operations on its SNAPSHOT pool");
+        final ThreadPool masterThreadPool = internalCluster().getMasterNodeInstance(ThreadPool.class);
+        assertBusy(() -> {
+            for (ThreadPoolStats.Stats stat : masterThreadPool.stats()) {
+                if (ThreadPool.Names.SNAPSHOT.equals(stat.getName())) {
+                    assertEquals(stat.getActive(), 0);
```
Comment (tlrx) [inline test/framework/src/main/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java:589]: The number of active threads relies on `ThreadPoolExecutor#getActiveCount()` which is approximate, but having `core == max` should make this OK I think.

File: test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java [hunk 10]
```diff
@@ -111,8 +111,15 @@ public long getFailureCount() {
 
     private volatile boolean blockOnDeleteIndexN;
 
-    /** Allows blocking on writing the index-N blob; this is a way to enforce blocking the
-     *  finalization of a snapshot, while permitting other IO operations to proceed unblocked. */
+    /**
+     * Allows blocking on writing the index-N blob and subsequently failing it on unblock.
+     * This is a way to enforce blocking the  finalization of a snapshot, while permitting other IO operations to proceed unblocked.
```
Comment (tlrx) [inline test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java:116]:
```suggestion
     * This is a way to enforce blocking the finalization of a snapshot, while permitting other IO operations to proceed unblocked.
```

File: test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java (hunk 3 above)
Comment (tlrx) [reply test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java:123]: It worth it IMO

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 11]
```diff
@@ -2086,19 +2083,20 @@ public static ClusterState updateWithSnapshots(ClusterState state,
...
                     if (useShardGenerations) {
-                        if (isNewIndex) {
+                        final String inFlightGeneration = inFlightShardStates.bestGeneration(index, shardId.id(), shardGenerations);
+                        if (inFlightGeneration == null && isNewIndex) {
                             assert shardGenerations.getShardGen(index, shardId.getId()) == null
                                 : "Found shard generation for new index [" + index + "]";
                             shardRepoGeneration = ShardGenerations.NEW_SHARD_GEN;
                         } else {
-                            shardRepoGeneration = shardGenerations.getShardGen(index, shardId.getId());
+                            shardRepoGeneration = inFlightGeneration;
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:2092]: Double checking my understanding, this will also update the shard generation to use for WAITING shard snapshots, right?

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:2092]: Yes exactly, see a few line below where we use this variable:


```java
                    } else if (primary.relocating() || primary.initializing()) {
                        shardSnapshotStatus = new ShardSnapshotStatus(
                            primary.currentNodeId(), ShardState.WAITING, shardRepoGeneration);
```

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/CloneSnapshotIT.java (hunk 7 above)
Comment (original-brownbear) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/CloneSnapshotIT.java:500]: Yea exactly, if the snapshot was based off of a broken/outdated shard generation value it would be `PARTIAL` because the shard(s) working from the broken generation would fail with a ~`FileNotFoundException`/404.

**Comment by original-brownbear** [comment]
Thanks Tanguy & Francisco, all points addressed I think :)

File: server/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java [hunk 12]
```diff
@@ -694,6 +695,10 @@ private static boolean assertConsistentEntries(List<Entry> entries) {
                 }
             }
         }
+        for (String repoName : assignedShardsByRepo.keySet()) {
+            // make sure in-flight-shard-states can be build cleanly for the entries without tripping assertions
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java:699]:
```suggestion
            // make sure in-flight-shard-states can be built cleanly for the entries without tripping assertions
```

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tanguy & Francisco!
