### PR TITLE
Clarify SourceLookup sharing across fetch subphases.

### LINKED ISSUE #31000: _source not returned in "explain": true with certain queries
**Elasticsearch version**: 5.9.6 & 6.2.4

**Plugins installed**: []

**JVM version**: independent

**OS version**: independent

**Description of the problem including expected versus actual behavior**:
The `_source` is not being returned for hits when `explain` is set to `true` for a specific set of queries. The conditions for `_source` to be missing appear to be:

+ A mapping with a nested field
+ A document with that nested field populated
+ A query which:
  + Matches that document
  + Has explain set to true
  + Uses rescore, with a nested function_score query matching the nested field
  + Adjusts the score using script_score

**Steps to reproduce**:
```
PUT /test
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1
  },
  "mappings": {
    "type1": {
      "properties": {
        "object1": {
          "type": "nested",
          "properties": {
            "field1": {
              "type": "text"
            }
          }
        }
      }
    }
  }
}
```
```
PUT /test/type1/1
{
  "object1": {
    "field1": "some text goes here"
  }
}
```
```
GET /test/_search
{
  "from" : 0,
  "size" : 10,
  "query" : {
    "match_all": { }
  },
  "explain" : true,
  "rescore" : [
    {
      "window_size" : 200,
      "query" : {
        "rescore_query" : {
          "nested" : {
            "query" : {
              "function_score" : {
                "query" : {
                  "match_all": { }
                },
                "functions" : [
                  {
                    "script_score" : {
                      "script" : {
                        "source" : "1",
                        "lang" : "painless"
                      }
                    }
                  }
                ],
                "score_mode" : "multiply"
              }
            },
            "path" : "object1"
          }
        },
        "query_weight" : 1.0,
        "rescore_query_weight" : 1.0,
        "score_mode" : "total"
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by jtibshirani**
The `SourceLookup` class provides access to the _source for a particular
document, specified through `SourceLookup#setSegmentAndDocument`. Previously
the search context contained a single `SourceLookup` that was shared between
different fetch subphases. It was hard to reason about its state: is
`SourceLookup` set to the expected document? Is the _source already loaded and
available?

Instead of using a global source lookup, the fetch hit context now provides
access to a lookup that is set to load from the hit document.

This refactor closes #31000, since the same `SourceLookup` is no longer shared
between the 'fetch _source phase' and script execution.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java [hunk 1]
```diff
@@ -65,10 +65,6 @@ public void hitsExecute(SearchContext context, SearchHit[] hits) throws IOExcept
                 }
                 innerHits.docIdsToLoad(docIdsToLoad, 0, docIdsToLoad.length);
                 innerHits.setId(hit.getId());
-                innerHits.lookup().source().setSource(context.lookup().source().internalSourceRef());
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java:68]: We set the root document's _source here, but when processing inner hits we didn't use it and instead reloaded the _source. So this is safe to remove for now.

In a follow-up PR, I will fix this to make sure the _source is loaded only once for the root doc + inner hits.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java [hunk 2]
```diff
@@ -39,13 +40,15 @@
         private IndexSearcher searcher;
         private LeafReaderContext readerContext;
         private int docId;
+        private final SourceLookup sourceLookup = new SourceLookup();
```
Comment (mayya-sharipova) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java:43]: Do we always need to create `SourceLookup` object here?  What about cases where we don't need _source?

**Comment by mayya-sharipova** [comment]
@jtibshirani Thanks for the PR, I like the idea. I had an initial look, and will look more thoroughly tomorrow.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java [hunk 3]
```diff
@@ -154,13 +153,12 @@ protected Aggregator createInternal(SearchContext searchContext, Aggregator pare
...
 
         SignificantTextCollectorSource(
-            SourceLookup sourceLookup,
             BigArrays bigArrays,
             MappedFieldType fieldType,
             String[] sourceFieldNames,
             boolean filterDuplicateText
         ) {
-            this.sourceLookup = sourceLookup;
+            this.sourceLookup = new SourceLookup();
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java:161]: Since this one happens at query time maybe we can keep using it? I think what you have here would cause two significant text aggs to load source twice.

File: server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java [hunk 4]
```diff
@@ -27,31 +27,22 @@
...
+        this.mapperService = mapperService;
     }
 
     public LeafSearchLookup getLeafSearchLookup(LeafReaderContext context) {
         return new LeafSearchLookup(context,
-                docMap.getLeafDocLookup(context),
-                sourceLookup,
-                fieldsLookup.getLeafFieldsLookup(context));
+                docLookup.getLeafDocLookup(context),
+                new SourceLookup(),
```
Comment (mayya-sharipova) [inline server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:41]: Similar to @nik9000's comment, it looks like source will be loaded twice here for cases when a script needs to access ` _source` and when `_source` is requested for a document, for example for queries like this:

```js
{
  "_source": true,
  "query": {
    "match_all": {}
  },
  "script_fields": {
    "my_script": {
      "script": {
        "source": "params['_source']['my_field']"
      }
    }
  }
}
```

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java (hunk 2 above)
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java:43]: I think we should add a comment here about why we don't want to share the lookup in QueryShardContext.

File: server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java [hunk 5]
```diff
@@ -27,31 +27,22 @@
 import java.util.function.Function;
 
 public class SearchLookup {
-
-    final DocLookup docMap;
-
-    final SourceLookup sourceLookup;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:33]: I think we still need `SourceLookup` here both for significant text, and for the thing we talked about where I wanted `SearchLookup` on `FieldMapper#lookup`.

File: server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java (hunk 4 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:41]: I'm not sure this is the case -- looking at `ScriptFieldsPhase`, it overwrites `hitsExecute` and so processes all hits at once. That means it wouldn't be able to re-use the loaded _source (even before the refactor) ?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java (hunk 3 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java:161]: Oops, this is a great point. I think I took it the refactor too far. I plan to restore the shared `SourceLookup` on `SearchLookup` so it can be used to share cached _source in the query phase.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java (hunk 2 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java:43]: To me the optimization might not be worth it, it's not an expensive object to construct and we only create one `SourceLookup` per hit?

**Comment by jtibshirani** [comment]
I caught up with @nik9000 offline about the refactor and wanted to add more context as to its benefits:
* The _source loading semantics are clearer. We attempt to load the _source once at the start of the fetch phase, and explicitly add it to the `HitContext` to make it available for the subphases. Before we manipulated global state (setting the _source on `SearchContext`), and it was not obvious what the intention was.
* Any subphase that overrides `hitExecute` (singular) will have access to the hit context, which contains a reference to the _source for the current document. The subphases that override `hitsExecute` do not have access to a hit context and need to reload _source. Previously this difference in behavior was unclear.

However I now see a downside to this refactor. There used to be only one way to share a `SourceLookup` instance (as part of `SearchLookup` on `QueryShardContext`), but now we've added another specific to the fetch phase. This means that a subphase that overwrites `hitExecute` and also uses a script will not share the loaded _source.

I'm curious as to what others think. I still like the refactor and feel that it moves us in a better direction.

File: server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java (hunk 4 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:41]: Another note: I'll add some Javadoc to `HitContext` explaining the _source sharing strategy, since it is quite tricky to understand.

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:41]: I do think this'll break the shared loading of `_source` in scripts at query time though. Each script calls this method to get its own fresh LeafSearchLookup and we sort of rely on them being able to share the loaded `_source`.

**Comment by jimczi** [comment]
> However I now see a downside to this refactor. There used to be only one way to share a SourceLookup instance (as part of SearchLookup on QueryShardContext), but now we've added another specific to the fetch phase. This means that a subphase that overwrites hitExecute and also uses a script will not share the loaded _source.

We don't have such example at the moment, right ? That's also something we can tackle in a follow up, currently we use the lookup of the query shard context to compile the scripted field but we could refactor this part to move to the new hit context ? Hits are now [sorted by doc ids](https://github.com/elastic/elasticsearch/pull/57273) in fetch sub phases so it's also a good chance to get ride of the `hitsExecute` completely. That would allow to load the `_source` only once since today sub phases that use `hitsExecute` have no way to reuse `_source` ?

File: server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java (hunk 5 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:33]: 👍  will restore it.

File: server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java (hunk 4 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/lookup/SearchLookup.java:41]: > I do think this'll break the shared loading of _source in scripts at query time though.

👍  I agree, this will be fixed when I restore the shared `SourceLookup` on `SearchLookup`.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java (hunk 2 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java:43]: 👍

**Comment by jtibshirani** [comment]
> We don't have such example at the moment, right ?

I also can't think of an example right now.

> ... so it's also a good chance to get ride of the hitsExecute completely.

This is a good goal, and like you said I think the refactor leaves open these future simplifications.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java (hunk 2 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java:43]: I added Javadoc on `HitContext#sourceLookup` and `FetchPhase#prepareHitContext` to explain the logic. Let me know if it could use more clarification.

**Comment by jtibshirani** [comment]
> We don't have such example at the moment, right ?
> I also can't think of an example right now.

A correction here: I hadn't realized that `_source` was available within score scripts. So it is possible to have an 'explain' phase for a query that uses a score script (that then accesses `_source`). I'm not really worried about optimizing performance in this case though, since 'explain' is intended as a debugging tool.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 6]
```diff
@@ -222,42 +221,60 @@ private int findRootDocumentIfNested(SearchContext context, LeafReaderContext su
...
+            SearchHit hit = new SearchHit(docId, null, null, null);
+            hitContext.reset(hit, subReaderContext, subDocId, context.searcher());
         } else {
-            searchHit = new SearchHit(docId, fieldsVisitor.id(), emptyMap(), emptyMap());
-        }
-        // Set _source if requested.
-        SourceLookup sourceLookup = context.lookup().source();
-        sourceLookup.setSegmentAndDocument(subReaderContext, subDocId);
-        if (fieldsVisitor.source() != null) {
-            sourceLookup.setSource(fieldsVisitor.source());
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:249]: I wonder if we can still assign the `context.lookup().source()` with the current _source so that `_script` can share the source with other fetch sub-phase. That would only work for sub-phases that use a script and override `hitExecute` so the new `FetchFieldsPhase` would benefit from this hack ? We can then think how we could clenup the context for script in a follow up ?

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/InnerHitsPhase.java:68]: +1, that's something that we spotted sometime ago: https://github.com/elastic/elasticsearch/issues/32818#issuecomment-412878390 and maybe https://github.com/elastic/elasticsearch/issues/56210 but never implemented.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceScoreOrderFragmentsBuilder.java [hunk 7]
```diff
@@ -36,11 +35,10 @@
 public class SourceScoreOrderFragmentsBuilder extends ScoreOrderFragmentsBuilder {
 
     private final MappedFieldType fieldType;
-
-    private final QueryShardContext context;
+    private final FetchSubPhase.HitContext context;
 
     public SourceScoreOrderFragmentsBuilder(MappedFieldType fieldType,
-                                            QueryShardContext context,
+                                            FetchSubPhase.HitContext context,
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceScoreOrderFragmentsBuilder.java:41]: Maybe just pass the `SourceLookup` directly ?

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceSimpleFragmentsBuilder.java [hunk 8]
```diff
@@ -21,21 +21,20 @@
...
 import java.util.List;
 
 public class SourceSimpleFragmentsBuilder extends SimpleFragmentsBuilder {
 
-    private final QueryShardContext context;
+    private final FetchSubPhase.HitContext context;
 
     public SourceSimpleFragmentsBuilder(MappedFieldType fieldType,
-                                        QueryShardContext context,
+                                        FetchSubPhase.HitContext context,
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceSimpleFragmentsBuilder.java:37]: Same here ?

**Review by jimczi — APPROVED** [review]
I like this change. I left one comment regarding a possible hack to ensure that scripts and fetch sub phase can still share the _source but I don't feel strongly about it. We can solve the double load more nicely in a follow up if needed.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceScoreOrderFragmentsBuilder.java (hunk 7 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceScoreOrderFragmentsBuilder.java:41]: 👍

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceSimpleFragmentsBuilder.java (hunk 8 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/SourceSimpleFragmentsBuilder.java:37]: 👍

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 6 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:249]: I don't think `FetchFieldsPhase` would benefit currently, because it doesn't support scripts? I like the plan of considering it in a follow-up, for example as part of converting `ScriptFieldsPhase` to use `hitExecute`.

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:249]: Right, I was thinking preemptively of runtime scripted field but +1 to consider this in a follow up.

**Comment by jtibshirani** [comment]
In addition to restoring the shared `SourceLookup` on `SearchLookup`, I ended up removing all changes to the `SearchLookup` class, as they weren't core to this PR. So now the PR is scoped just to 'fetch' and avoids @nik9000 and @mayya-sharipova's concern around scripts sharing _source in the query phase.

Here is the final summary of changes:
* Store `SourceLookup` on `HitContext` and set the source when creating hits.
* Fetch subphases access source through `HitContext` when possible.
* Stop saving parent _source before loading inner hits (it was unused).
* Remove `SearchContext#lookup` method.

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani Thanks Julie, looks a very good change to me!

**Review by nik9000 — APPROVED** [review]
LGTM2

**Comment by jtibshirani** [comment]
Thanks everyone, the review feedback was really helpful.
