### PR TITLE
Avoiding watcher validation errors when a data stream points to more than one index

### LINKED ISSUE #85508: Watcher can fail to restart in early version of 8.x
### Description

Watcher will perform some basic validation prior to starting. One part of this validation is ensuring that if there is an alias to the .watcher-history-* index that it only contains a single index. In 8.0+ this validation can incorrectly cause Watcher to fail to start. In 8.0+ .watcher-history-* is a data stream (not an alias) and the data stream is expected to have multiple backing indices (unlike the elder alias support). The implementation/api is shared between resolving aliases and resolving data streams so the validation will incorrectly flag multiple backing indices for data streams as problematic and cause Watcher to fail to start. 

This issue will only happen when .watcher-history-16 data stream has multiple backing indices AND watcher needs to restart for any reason. Watcher can need to be restarted on cluster start, explicit start/stop, and any change to the allocation assignment for the .watches shards. 

The error message is (only seen for a logger at debug level ` "logger.org.elasticsearch.xpack.watcher": "debug"`) :
```
[2022-03-30T13:13:48,011][DEBUG][o.e.x.w.WatcherService   ] [runTask-0] error validating to start watcher
java.lang.IllegalStateException: Alias [.watcher-history-16] points to more than one index
        at org.elasticsearch.xpack.watcher.watch.WatchStoreUtils.getConcreteIndex(WatchStoreUtils.java:32) ~[x-pack-watcher-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.xpack.watcher.history.HistoryStore.validate(HistoryStore.java:79) ~[x-pack-watcher-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.xpack.watcher.WatcherService.validate(WatcherService.java:157) [x-pack-watcher-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.xpack.watcher.WatcherLifeCycleService.clusterChanged(WatcherLifeCycleService.java:162) [x-pack-watcher-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:564) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:550) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:510) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:714) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260) [elasticsearch-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
``` 
You can determine if this is the case by looking at `GET _watcher/stats` and `"watcher_state": "stopped"` and ` "manually_stopped": false` which means that the system via validation, not a user has stopped Watcher.  (you can also tell by increasing the log level and reviewing the logs)

You can reproduce with the following steps:

```
PUT _cluster/settings
{
    "persistent": {
        "logger.org.elasticsearch.xpack.watcher": "debug"
    }
}


PUT _watcher/watch/test
{
    "trigger": {
        "schedule": {
            "interval": "1s"
        }
    },
    "input": {
        "simple": {
            "key": "value"
        }
    },
    "actions": {
        "my_logger": {
            "logging": {
                "text": "Watch payload [{{ctx.payload}}]",
                "level": "debug"
            }
        }
    }
}

GET _data_stream/.watcher-history-16?expand_wildcards=all

POST _watcher/_stop

POST _watcher/_start

GET _watcher/stats

POST .watcher-history-16/_rollover

GET _data_stream/.watcher-history-16?expand_wildcards=all

POST _watcher/_stop

POST _watcher/_start

GET _watcher/stats
```

You can work around this issue by ensuring there are never more than 1 backing index in the .watcher-history-16 data stream. Use the ILM policy to ensure at  most 1 index for the watcher-history.

```
# increase max age to 7 days and remove min age from the delete phase of the default policy
PUT _ilm/policy/watch-history-ilm-policy-16
{
    "policy": {
        "phases": {
            "hot": {
                "min_age": "0ms",
                "actions": {
                    "rollover": {
                        "max_primary_shard_size": "50gb",
                        "max_age": "7d"
                    }
                }
            },
            "delete": {
                "actions": {
                    "delete": {
                        "delete_searchable_snapshot": true
                    }
                }
            }
        },
        "_meta": {
            "managed": true,
            "description": "default policy for the watcher history indices"
        }
    }
}

#wait up to 10 minutes (depending on ILM poll interval) to see a single backing index
GET _data_stream/.watcher-history-16?expand_wildcards=all

POST _watcher/_start

GET _watcher/stats
```

### PR DESCRIPTION
**Pull request by masseyke**
We are seeing this error in 8.0.1 if a node is restarted after the `.watcher-history-16` data stream is pointing to more than one index.
```
[instance-0000000000] error validating to start watcher
java.lang.IllegalStateException: Alias [.watcher-history-16] points to more than one index
	at org.elasticsearch.xpack.watcher.watch.WatchStoreUtils.getConcreteIndex(WatchStoreUtils.java:32) ~[x-pack-watcher-8.1.0.jar:8.1.0]
	at org.elasticsearch.xpack.watcher.history.HistoryStore.validate(HistoryStore.java:79) ~[x-pack-watcher-8.1.0.jar:8.1.0]
	at org.elasticsearch.xpack.watcher.WatcherService.validate(WatcherService.java:158) [x-pack-watcher-8.1.0.jar:8.1.0]
	at org.elasticsearch.xpack.watcher.WatcherLifeCycleService.clusterChanged(WatcherLifeCycleService.java:162) [x-pack-watcher-8.1.0.jar:8.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:564) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:550) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:510) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:717) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:260) [elasticsearch-8.1.0.jar:8.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223) [elasticsearch-8.1.0.jar:8.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
This change makes it ok to use an alias with a write index or a data stream (which always has a write index).
Closes #85508

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java [hunk 1]
```diff
@@ -28,11 +29,18 @@ public static IndexMetadata getConcreteIndex(String name, Metadata metadata) {
             return null;
         }
 
-        if (indexAbstraction.getType() != IndexAbstraction.Type.CONCRETE_INDEX && indexAbstraction.getIndices().size() > 1) {
+        if ((indexAbstraction.getType() != IndexAbstraction.Type.CONCRETE_INDEX
```
Comment (martijnvg) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java:32]: This if statement does look a bit complicated.
Can we instead have two simpler if statements for the valid cases?
One if statement for when `indexAbstraction` is a data stream and one when `indexAbstraction` is an alias.
In all other cases we would fail.

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+        for (int i = 0; i < randomIntBetween(2, 10); i++) {
+            String indexName = dataStreamName + "_" + i;
+            indexNames.add(indexName);
+            IndexMetadata.Builder indexMetadataBuilder = new IndexMetadata.Builder(indexName);
+            Settings settings = Settings.builder()
+                .put(IndexMetadata.SETTING_PRIORITY, 5)
+                .put(IndexMetadata.INDEX_NUMBER_OF_SHARDS_SETTING.getKey(), 1)
+                .put(IndexMetadata.INDEX_NUMBER_OF_REPLICAS_SETTING.getKey(), 1)
+                .put(IndexMetadata.SETTING_INDEX_VERSION_CREATED.getKey(), Version.CURRENT)
+                .build();
```
Comment (martijnvg) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java:48]: maybe move this to a private helper method?

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java [hunk 3]
```diff
@@ -0,0 +1,179 @@
...
+                indexNames.stream().map(indexName -> new Index(indexName, IndexMetadata.INDEX_UUID_NA_VALUE)).collect(Collectors.toList()),
+                randomInt(),
+                Collections.emptyMap(),
+                true,
+                randomBoolean(),
+                true,
+                randomBoolean(),
+                IndexMode.TIME_SERIES
+            )
+        );
```
Comment (martijnvg) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java:66]: Maybe use a helper method from `DataStreamTestHelper` to create the `DataStream` instance?
(maybe the helper method needs to be modified to accept time series mode or have a dedicated method that creates random tsdb data streams)

**Review by martijnvg — COMMENTED** [review]
Looks good! I left a question and a comments about the tests.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java (hunk 1 above)
Comment (masseyke) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java:32]: I think we also support if it's just a concrete index, right? I was not sure if there were other types I didn't know about so I left it mostly as it was. If there are definitely just those 3 though (alias, data stream, concrete index) I can definitely simplify it.

Comment (masseyke) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java:32]: In at least one place we pass `.watches` to this method, which I believe is a concrete index (although I could definitely be wrong about that).

Comment (martijnvg) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java]: Thanks, it does.

**Review by martijnvg — APPROVED** [review]
👍 LGTM (pending successful build)

Failure occurred due to error message change:

```
java.lang.AssertionError: |  
-- | --
  | Expected: is "Alias [.triggered_watches] points to more than one index" |  
  | but: was "Alias [.triggered_watches] points to 2 indices, and does not have a designated write index" |  
  | at __randomizedtesting.SeedInfo.seed([8F6C099FB918BA97:988C8EAA4DCC424]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.watcher.execution.TriggeredWatchStoreTests.testLoadingFailsWithTwoAliases(TriggeredWatchStoreTests.java:391)
```

(and I think bwc failures should be fixed by merging in master)

**Comment by masseyke** [comment]
@elasticmachine update branch
