### PR TITLE
Fix propagation of enablePositionIncrements in QueryStringQueryBuilder

### LINKED ISSUE #43574: enable_position_increments not working for phrase queries with stopwords
Hi there,

I'm reporting here a bug found by me and another user, witch i found the original message on https://discuss.elastic.co with no response.

**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1 (docker)

**Description of the problem including expected versus actual behavior**:

I'm following this guide https://stackoverflow.com/questions/31719249/how-to-query-a-phrase-with-stopwords-in-elasticsearch to run phrase queries against text with stopwords removed, and the verified answer doesn't work in Elasticsearch 7. Setting enable_position_increments to false in my query_string query doesn't do anything at all.

**Steps to reproduce**:

```
PUT /fr_articles
{
   "settings": {
      "analysis": {
         "analyzer": {
            "stop": {
               "type": "standard",
               "stopwords" : ["the"]
            }
         }
      }
   },
   "mappings": {
      "properties": {
            "title": {
               "type": "text",
               "analyzer": "stop"
            }
         }
   }
}
```
```
POST /fr_articles/test/1
{
    "title" : "Tom the king of Toulon!"
}
```
```
POST /fr_articles/_search
{
   "query": {
      "query_string": {
         "default_field": "title",
         "query" : "\"tom king\"",
         "enable_position_increments": false
      }
   }
}
```
This returns 0 results.

### PR DESCRIPTION
**Pull request by jimczi**
This change fixes the propagation of the enablePositionIncrements option
to the underlying QueryBuilder.

Closes #43574

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/search/MatchQuery.java [hunk 1]
```diff
@@ -320,11 +320,11 @@ private boolean hasPositions(MappedFieldType fieldType) {
             super(analyzer);
             this.fieldType = fieldType;
             if (hasPositions(fieldType)) {
-                setAutoGenerateMultiTermSynonymsPhraseQuery(autoGenerateSynonymsPhraseQuery);
+                setAutoGenerateMultiTermSynonymsPhraseQuery(MatchQuery.this.autoGenerateSynonymsPhraseQuery);
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/search/MatchQuery.java]: To me it'd be clearer to pass these two flags through the constructor, as it avoids having to figure out the inheritance structure.

**Review by jtibshirani — APPROVED** [review]
It looks good to me, I left a suggestion but it's not critical.

**Comment by jimczi** [comment]
@elasticmachine update branch
