### PR TITLE
[ES|QL] Better estimation on loading large text field from `_source`

### LINKED ISSUE #141550: [CI] HeapAttackIT testLastAggWithGiantText and testLastAggWithGiantText failing
### CI Link

https://gradle-enterprise.elastic.co/s/ao4wdrrv5nwxe/tests/overview?outcome=FAILED

### Repro line

```
 ./gradlew ":test:external-modules:test-esql-heap-attack:javaRestTest" --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testLastAggWithGiantText" -Dtests.seed=BCBF016ADFFFB895 -Dtests.locale=sr-Latn -Dtests.timezone=Africa/Windhoek -Druntime.java=25
```

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

This failures can be reliably reproduced from the stateful repo when adding `-Dtests.iters=100`, no specific seed needed. In 100 runs, it will fail 10-20 times.

In stateful, increasing the documents count for these 2 tests from `50` to `100` reliably fixes the issue. However, this fix reliably fails in serverless. See the attached heap dump.

Snippets from the 4 `esql_worker` threads, from the heap dump.
```
"elasticsearch[search-JWDArIV][esql_worker][T#1]" daemon prio=5 tid=101 WAITING
    at jdk.internal.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:369)
    at java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:458)
       local variable: java.util.concurrent.LinkedTransferQueue$DualNode#83
       local variable: java.util.concurrent.LinkedTransferQueue#3
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#14
    at java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:613)
       local variable: java.util.concurrent.LinkedTransferQueue#3
       local variable: java.util.concurrent.LinkedTransferQueue$DualNode#83
       local variable: java.util.concurrent.LinkedTransferQueue$DualNode#77
    at java.util.concurrent.LinkedTransferQueue.take(LinkedTransferQueue.java:1257)
    at org.elasticsearch.common.util.concurrent.SizeBlockingQueue.take(SizeBlockingQueue.java:153)
       local variable: org.elasticsearch.common.util.concurrent.SizeBlockingQueue#2
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1016)
       local variable: org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor#1
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       local variable: org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor#1
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#35
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#14
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#35
    at java.lang.Thread.runWith(Thread.java:1487)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#14
       local variable: class java.lang.Thread
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#35
    at java.lang.Thread.run(Thread.java:1474)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#14
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#35
       local variable: class java.lang.Thread
```

```
"elasticsearch[search-JWDArIV][esql_worker][T#3]" daemon prio=5 tid=104 RUNNABLE
    at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:618)
       local variable: org.elasticsearch.common.util.BigArrays#3
       local variable: org.elasticsearch.common.util.BigArrays#3
    at org.elasticsearch.common.util.BigArrays.resize(BigArrays.java:640)
       local variable: org.elasticsearch.common.util.BigArrays$ByteArrayWrapper#15
       local variable: org.elasticsearch.common.util.BigArrays$ByteArrayWrapper#15
    at org.elasticsearch.common.util.BigArrays.grow(BigArrays.java:655)
    at org.elasticsearch.common.io.stream.BytesStreamOutput.ensureCapacity(BytesStreamOutput.java:215)
       local variable: org.elasticsearch.common.io.stream.BytesStreamOutput#11
    at org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:105)
       local variable: org.elasticsearch.common.io.stream.BytesStreamOutput#11
       local variable: byte[]#268421
    at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:499)
    at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2210)
    at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1376)
       local variable: com.fasterxml.jackson.core.json.UTF8JsonGenerator#1
       local variable: char[]#104603
    at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:596)
       local variable: com.fasterxml.jackson.core.json.UTF8JsonGenerator#1
    at com.fasterxml.jackson.core.JsonGenerator._copyCurrentStringValue(JsonGenerator.java:2796)
    at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2687)
       local variable: com.fasterxml.jackson.core.json.UTF8JsonGenerator#1
       local variable: com.fasterxml.jackson.core.filter.FilteringParserDelegate#1
    at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:2638)
    at org.elasticsearch.xcontent.provider.json.JsonXContentGenerator.copyCurrentStructure(JsonXContentGenerator.java:540)
    at org.elasticsearch.xcontent.XContentBuilder.copyCurrentStructure(XContentBuilder.java:1246)
       local variable: org.elasticsearch.xcontent.XContentBuilder#1
    at org.elasticsearch.search.lookup.SourceFilter.lambda$buildBytesFilter$1(SourceFilter.java:177)
       local variable: org.elasticsearch.xcontent.XContentBuilder#1
       local variable: org.elasticsearch.xcontent.provider.json.JsonXContentParser#1
    at org.elasticsearch.search.lookup.SourceFilter$$Lambda+0x00000fc00192c000.apply(<unresolved string 0x0>)
    at org.elasticsearch.search.lookup.SourceFilter.filterBytes(SourceFilter.java:153)
    at org.elasticsearch.search.lookup.Source$1.filter(Source.java:137)
    at org.elasticsearch.index.mapper.SourceLoader$Stored$1.source(SourceLoader.java:98)
    at org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader.source(BlockLoaderStoredFieldsFromLeafLoader.java:48)
       local variable: org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader#1
       local variable: org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader#1
    at org.elasticsearch.index.mapper.BlockSourceReader.read(BlockSourceReader.java:54)
       local variable: org.elasticsearch.index.mapper.BlockSourceReader$BytesRefs#1
       local variable: org.elasticsearch.compute.data.BytesRefBlockBuilder#1
       local variable: org.elasticsearch.index.mapper.SourceValueFetcher$3#1
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader$RowStrideReaderWork.read(ValuesFromSingleReader.java:233)
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.loadFromRowStrideReaders(ValuesFromSingleReader.java:172)
       local variable: org.elasticsearch.compute.lucene.read.ValuesFromSingleReader#1
       local variable: org.elasticsearch.compute.data.Block[]#3
       local variable: java.util.ArrayList#26023
       local variable: org.elasticsearch.compute.lucene.read.ValuesReaderDocs#1
       local variable: org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader#1
       local variable: java.util.ArrayList$Itr#1
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.loadFromSingleLeaf(ValuesFromSingleReader.java:114)
       local variable: org.elasticsearch.compute.lucene.read.ValuesFromSingleReader#1
       local variable: org.elasticsearch.compute.data.Block[]#3
       local variable: org.elasticsearch.compute.lucene.read.ValuesReaderDocs#1
       local variable: java.util.ArrayList#26022
       local variable: java.util.ArrayList#26023
       local variable: org.elasticsearch.compute.lucene.read.ComputeBlockLoaderFactory#1
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.load(ValuesFromSingleReader.java:59)
    at org.elasticsearch.compute.lucene.read.ValuesReader.next(ValuesReader.java:38)
       local variable: org.elasticsearch.compute.lucene.read.ValuesFromSingleReader#1
       local variable: org.elasticsearch.compute.data.Block[]#3
    at org.elasticsearch.compute.lucene.read.ValuesReader.next(ValuesReader.java:18)
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator.next(AbstractPageMappingToIteratorOperator.java:337)
       local variable: org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator#1
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator.next(AbstractPageMappingToIteratorOperator.java:313)
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator.next(AbstractPageMappingToIteratorOperator.java:189)
       local variable: org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator#1
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator.next(AbstractPageMappingToIteratorOperator.java:174)
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator.getOutput(AbstractPageMappingToIteratorOperator.java:148)
       local variable: org.elasticsearch.compute.lucene.read.ValuesSourceReaderOperator#1
    at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:283)
       local variable: org.elasticsearch.compute.operator.Driver#1
       local variable: java.util.ArrayList$ListItr#1
       local variable: org.elasticsearch.compute.lucene.read.ValuesSourceReaderOperator#1
       local variable: org.elasticsearch.compute.operator.ProjectOperator#1
    at org.elasticsearch.compute.operator.Driver.run(Driver.java:191)
       local variable: org.elasticsearch.compute.operator.Driver#1
       local variable: org.elasticsearch.compute.operator.Driver$1$$Lambda+0x00000fc0018e77a8#1
       local variable: org.elasticsearch.compute.operator.IsBlockedResult#1
    at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:431)
       local variable: org.elasticsearch.compute.operator.Driver$1#1
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       local variable: org.elasticsearch.compute.operator.Driver$1#1
    at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       local variable: org.elasticsearch.compute.operator.DriverScheduler$1#1
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
       local variable: org.elasticsearch.common.util.concurrent.TimedRunnable#1
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1113)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       local variable: org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable#41
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
       local variable: org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor#1
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#31
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#24
       local variable: org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable#41
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#31
    at java.lang.Thread.runWith(Thread.java:1487)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#24
       local variable: class java.lang.Thread
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#31
    at java.lang.Thread.run(Thread.java:1474)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#24
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#31
       local variable: class java.lang.Thread
```

```
"elasticsearch[search-JWDArIV][esql_worker][T#2]" daemon prio=5 tid=105 RUNNABLE
    at com.fasterxml.jackson.core.JsonGenerator._copyCurrentStringValue(JsonGenerator.java:2796)
    at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2687)
       local variable: com.fasterxml.jackson.core.json.UTF8JsonGenerator#2
       local variable: com.fasterxml.jackson.core.filter.FilteringParserDelegate#2
    at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:2638)
    at org.elasticsearch.xcontent.provider.json.JsonXContentGenerator.copyCurrentStructure(JsonXContentGenerator.java:540)
    at org.elasticsearch.xcontent.XContentBuilder.copyCurrentStructure(XContentBuilder.java:1246)
       local variable: org.elasticsearch.xcontent.XContentBuilder#2
    at org.elasticsearch.search.lookup.SourceFilter.lambda$buildBytesFilter$1(SourceFilter.java:177)
       local variable: org.elasticsearch.xcontent.XContentBuilder#2
       local variable: org.elasticsearch.xcontent.provider.json.JsonXContentParser#2
    at org.elasticsearch.search.lookup.SourceFilter$$Lambda+0x00000fc00192c000.apply(<unresolved string 0x0>)
    at org.elasticsearch.search.lookup.SourceFilter.filterBytes(SourceFilter.java:153)
    at org.elasticsearch.search.lookup.Source$1.filter(Source.java:137)
    at org.elasticsearch.index.mapper.SourceLoader$Stored$1.source(SourceLoader.java:98)
    at org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader.source(BlockLoaderStoredFieldsFromLeafLoader.java:48)
       local variable: org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader#2
       local variable: org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader#2
    at org.elasticsearch.index.mapper.BlockSourceReader.read(BlockSourceReader.java:54)
       local variable: org.elasticsearch.index.mapper.BlockSourceReader$BytesRefs#2
       local variable: org.elasticsearch.compute.data.BytesRefBlockBuilder#2
       local variable: org.elasticsearch.index.mapper.SourceValueFetcher$3#2
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader$RowStrideReaderWork.read(ValuesFromSingleReader.java:233)
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.loadFromRowStrideReaders(ValuesFromSingleReader.java:172)
       local variable: org.elasticsearch.compute.lucene.read.ValuesFromSingleReader#2
       local variable: org.elasticsearch.compute.data.Block[]#4
       local variable: java.util.ArrayList#26025
       local variable: org.elasticsearch.compute.lucene.read.ValuesReaderDocs#2
       local variable: org.elasticsearch.index.mapper.BlockLoaderStoredFieldsFromLeafLoader#2
       local variable: java.util.ArrayList$Itr#2
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.loadFromSingleLeaf(ValuesFromSingleReader.java:114)
       local variable: org.elasticsearch.compute.lucene.read.ValuesFromSingleReader#2
       local variable: org.elasticsearch.compute.data.Block[]#4
       local variable: org.elasticsearch.compute.lucene.read.ValuesReaderDocs#2
       local variable: java.util.ArrayList#26024
       local variable: java.util.ArrayList#26025
       local variable: org.elasticsearch.compute.lucene.read.ComputeBlockLoaderFactory#2
    at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.load(ValuesFromSingleReader.java:59)
    at org.elasticsearch.compute.lucene.read.ValuesReader.next(ValuesReader.java:38)
       local variable: org.elasticsearch.compute.lucene.read.ValuesFromSingleReader#2
       local variable: org.elasticsearch.compute.data.Block[]#4
    at org.elasticsearch.compute.lucene.read.ValuesReader.next(ValuesReader.java:18)
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator.next(AbstractPageMappingToIteratorOperator.java:337)
       local variable: org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator#2
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator.next(AbstractPageMappingToIteratorOperator.java:313)
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator.next(AbstractPageMappingToIteratorOperator.java:189)
       local variable: org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator#2
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator.next(AbstractPageMappingToIteratorOperator.java:174)
    at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator.getOutput(AbstractPageMappingToIteratorOperator.java:148)
       local variable: org.elasticsearch.compute.lucene.read.ValuesSourceReaderOperator#2
    at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:283)
       local variable: org.elasticsearch.compute.operator.Driver#2
       local variable: java.util.ArrayList$ListItr#2
       local variable: org.elasticsearch.compute.lucene.read.ValuesSourceReaderOperator#2
       local variable: org.elasticsearch.compute.operator.ProjectOperator#2
    at org.elasticsearch.compute.operator.Driver.run(Driver.java:191)
       local variable: org.elasticsearch.compute.operator.Driver#2
       local variable: org.elasticsearch.compute.operator.Driver$1$$Lambda+0x00000fc0018e77a8#1
       local variable: org.elasticsearch.compute.operator.IsBlockedResult#1
    at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:431)
       local variable: org.elasticsearch.compute.operator.Driver$1#2
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       local variable: org.elasticsearch.compute.operator.Driver$1#2
    at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       local variable: org.elasticsearch.compute.operator.DriverScheduler$1#2
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
       local variable: org.elasticsearch.common.util.concurrent.TimedRunnable#2
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1113)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       local variable: org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable#42
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
       local variable: org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor#1
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#33
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#26
       local variable: org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable#42
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#33
    at java.lang.Thread.runWith(Thread.java:1487)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#26
       local variable: class java.lang.Thread
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#33
    at java.lang.Thread.run(Thread.java:1474)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#26
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#33
       local variable: class java.lang.Thread
```

```
"elasticsearch[search-JWDArIV][esql_worker][T#4]" daemon prio=5 tid=106 WAITING
    at jdk.internal.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:369)
    at java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:458)
       local variable: java.util.concurrent.LinkedTransferQueue$DualNode#77
       local variable: java.util.concurrent.LinkedTransferQueue#3
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#27
    at java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:613)
       local variable: java.util.concurrent.LinkedTransferQueue#3
       local variable: java.util.concurrent.LinkedTransferQueue$DualNode#77
       local variable: java.util.concurrent.LinkedTransferQueue$DualNode#76
    at java.util.concurrent.LinkedTransferQueue.take(LinkedTransferQueue.java:1257)
    at org.elasticsearch.common.util.concurrent.SizeBlockingQueue.take(SizeBlockingQueue.java:153)
       local variable: org.elasticsearch.common.util.concurrent.SizeBlockingQueue#2
    at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1016)
       local variable: org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor#1
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       local variable: org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor#1
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#34
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#27
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#34
    at java.lang.Thread.runWith(Thread.java:1487)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#27
       local variable: class java.lang.Thread
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#34
    at java.lang.Thread.run(Thread.java:1474)
       local variable: org.elasticsearch.common.util.concurrent.EsExecutors$EsThread#27
       local variable: java.util.concurrent.ThreadPoolExecutor$Worker#34
       local variable: class java.lang.Thread

```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Fixes: #141550 

Loading giant(e.g. 5MB) text field from `_source` can potentially take 10x(10*5MB) untracked memory in ES|QL according to heap dump, 10x includes the memory consumed in lucene, and some data structures used in the intermediate steps. Loading a big amount of documents with giant text fields can cause significant memory pressure on GC, cause GC delay and trigger OOM, it has been observed in #140218. The situation gets worse when the number of concurrency increases, like in the case of subqueries, when there are multiple `esql_worker`  threads reading giant text field simultaneously, GC delay is more noticeable and OOM happens more frequently.

#142344 and #142790 attempted to give better estimation during loading from `_source` and add penalty to giant page/documents in pipeline breakers like `exchange` and `topn`. This PR takes a different approach by adding penalty to giant `BytesRef` blocks, giving the penalty earlier in the pipeline.

There are two major changes in this PR that help reduce the possibility/frequency of OOM when loading giant text fields.

1. Before loading a giant text field from `_source` ensure the circuit breaker has 10x capacity in it.
2. When a `BytesRefArrayVector` and `ConstantBytesRefVector` are created, if they are bigger than a certain threshold, apply penalty to them, the overestimation is used to balance the memory pressure to GC.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/generated-src/org/elasticsearch/compute/data/BytesRefArrayVector.java [hunk 1]
```diff
@@ -130,12 +130,24 @@ public ReleasableIterator<BytesRefBlock> lookup(IntBlock positions, ByteSizeValu
...
     public static long ramBytesEstimated(BytesRefArray values) {
-        return BASE_RAM_BYTES_USED + RamUsageEstimator.sizeOf(values);
+        return ramBytesEstimated(
+            values,
+            BlockFactory.DEFAULT_BYTES_REF_RAM_OVERESTIMATE_THRESHOLD,
+            BlockFactory.DEFAULT_BYTES_REF_RAM_OVERESTIMATE_FACTOR
+        );
+    }
+
+    public static long ramBytesEstimated(BytesRefArray values, long overestimateThreshold, double overestimateFactor) {
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/generated-src/org/elasticsearch/compute/data/BytesRefArrayVector.java:151]: These deserve javadoc I think.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/BlockFactory.java [hunk 2]
```diff
@@ -43,14 +48,44 @@ public BlockFactory(CircuitBreaker breaker, BigArrays bigArrays, ByteSizeValue m
         this(breaker, bigArrays, maxPrimitiveArraySize, null);
     }
 
+    public BlockFactory(
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/BlockFactory.java:51]: I think we want a follow-up TODO where we make a build for this thing. I don't like having a zillion ctor overrides. It'd be nice to have:
```
BlockFactory.builder(bigArrays).circuitBreaker(breaker).maxPrimitiveArraySize(whatever).bytesRefRamOverestimateThreshold(whatever).build()
```
And tests can just get the defaults with
```
BlockFactory.builder(bigArrays)
```

File: server/src/main/java/org/elasticsearch/index/mapper/BlockLoaderStoredFieldsFromLeafLoader.java [hunk 3]
```diff
@@ -76,4 +83,25 @@ public Map<String, List<Object>> storedFields() throws IOException {
...
     }
+
+    /**
+     * Returns the raw byte size of the last loaded _source. This is useful for estimating
+     * the untracked memory overhead from source parsing (parsed Java Strings occupy
+     * approximately 2x the raw byte size due to UTF-16 encoding).
+     */
+    public long lastSourceBytesSize() {
+        return lastSourceBytesSize;
+    }
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/mapper/BlockLoaderStoredFieldsFromLeafLoader.java:87]: Can this be ` source != null && source.internalSourceRef() != null ? source.internalSourceRef().length() : 0` so we don't need to clear it?

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/mapper/BlockLoaderStoredFieldsFromLeafLoader.java:87]: Like, we don't need the variable at all.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/BlockFactory.java [hunk 4]
```diff
@@ -419,7 +469,7 @@ public BytesRefBlock newConstantBytesRefBlockWith(BytesRef value, int positions)
     }
 
     public BytesRefVector newConstantBytesRefVector(BytesRef value, int positions) {
-        long preadjusted = ConstantBytesRefVector.ramBytesUsedWithLength(value);
+        long preadjusted = ConstantBytesRefVector.ramBytesEstimated(value, bytesRefRamOverestimateThreshold, bytesRefRamOverestimateFactor);
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/BlockFactory.java:472]: :+1:

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java [hunk 5]
```diff
@@ -174,6 +176,32 @@ public record ShardContext(
     private int lastShard = -1;
     private int lastSegment = -1;
 
+    /**
+     * The maximum raw byte size of _source observed so far. This persists across pages so
+     * the pre-reservation for source parsing overhead can protect even the first (and only)
+     * document in a page. On a 512MB JVM, jumboBytes is ~512KB, so each 5MB text field
+     * creates a 1-doc page. Without persisting this, every page starts with 0 reservation.
+     */
+    volatile long lastKnownSourceSize;
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java]: I don't believe this should be `volatile`. It's not shared between threads. There's just one per `ValuesSourceReaderOperator` instance.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java [hunk 6]
```diff
@@ -174,6 +176,32 @@ public record ShardContext(
...
+    final double sourceReservationFactor;
+
+    /**
+     * Persistent reservation on the circuit breaker for the expected overhead of _source
+     * parsing. Held while this operator is active and loading large documents. When multiple
+     * operators load large _source concurrently, their persistent reservations accumulate
+     * on the shared circuit breaker, causing it to trip before the aggregate untracked
+     * temporaries from concurrent loads can overwhelm the heap.
+     */
+    private long sourceLoadingReservation;
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java:204]: Would you kindly put these with the other `final` stuff? I like to keep the mutable below the immutable stuff.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java [hunk 7]
```diff
@@ -199,17 +228,37 @@ public ValuesSourceReaderOperator(
...
+    /**
+     * Acquires or increases the persistent source loading reservation on the circuit breaker.
+     * Called at the start of each page and after each row load that updates
+     * {@link #lastKnownSourceSize}. If the breaker trips, the exception propagates and
+     * prevents further loading, limiting concurrent large _source operations.
+     */
+    void acquireSourceLoadingReservation() {
+        if (lastKnownSourceSize <= jumboBytes) {
+            return;
+        }
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java]: I think we should do this so long as the source size is `>= 0` instead.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java [hunk 8]
```diff
@@ -157,6 +157,12 @@ private void readRowStride(int doc) throws IOException {
                 assert r.columnAtATime == null;
                 r.rowStride.read(doc, storedFields, r.builder);
             }
+            long sourceBytes = storedFields.lastSourceBytesSize();
+            if (sourceBytes > operator.lastKnownSourceSize) {
+                operator.lastKnownSourceSize = sourceBytes;
+                operator.acquireSourceLoadingReservation();
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java]: What do you think of leaving the bytes reserved the entire time the `Operator` is alive, not just while it is processing a `Page`. That's over-greedy, but maybe the right kind of excessive.


Either way, I'd take move these to the `ValuesSourceReaderOperator` on a method like `accountForSourceBytes(BlockLoaderStoredFieldsFromLeafLoader loader)` or something.

**Review by nik9000 — CHANGES_REQUESTED** [review]
Looks great! I've requested some small things.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java (hunk 5 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java]: Done.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java (hunk 8 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java]: Done

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java (hunk 6 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java:204]: `sourceReservationFactor` is final(10x) and it is moved next to the other final stuff. The `sourceLoadingReservation` is the size of the largest source for calculating how much memory is needed to reserve in circuit breaker, and it can be changed after fetching each source, so I left it here with the other mutable stuff.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java (hunk 7 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java]: Do we want to reserve 10x for smaller sources as well? The `jumboBytes` for our heap attack tests is 1MB, so if the source size is less than 1MB, we don't reserve 10x from the circuit breaker. It seems like GC is not super delayed by smaller stuff according to the heap dump.

**Comment by fang-xing-esql** [comment]
> Looks great! I've requested some small things.

Thanks for reviewing @nik9000 ! The majority of the suggestion have been applied. 

I left the BlockFactory comment as a follow up, thanks for helping with it! 

I left a question - do we want to reserve 10x for all sources, regardless whether it is below or above the jumboBytes(1MB), the pattern in the heap dump of 5MB text field is different from the heap dump of smaller sources, it seems like for smaller sources, GC is not super delayed because of fetching the data from indices. The memory pressure of tests with smaller sources are more from serialization, as we still can potentially create big pages with many many smaller blocks in some places like `TopN` and `ValuesFromManyReader` - that we are going to fix next.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java (hunk 7 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java]: I suppose it's not 10x bad, but it's using the _source still takes some multiple of the memory. I'd just go with the 10x I think.

Comment (fang-xing-esql) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperator.java]: Ok, let's just do it, I'll remove the check.

**Review by nik9000 — APPROVED** [review]
Looks good to me. Could you add something to the block tests? Just a small thing to see it kicking in. I know it does, but it'll help six months from now when we ask "are we super duper sure this works?"

**Comment by fang-xing-esql** [comment]
> Looks good to me. Could you add something to the block tests? Just a small thing to see it kicking in. I know it does, but it'll help six months from now when we ask "are we super duper sure this works?"

I added some tests for `BytesRefArrayVector`, `BytesRefArrayBlock`, `BytesRefVectorBuilder`, `BytesRefBlockBuilder` and `ConstantBytesRefVector` in `BlockAccountingTests`. Thanks for the review @nik9000 !
