### PR TITLE
fix date-processor to a new default year for every new pipeline execution

### LINKED ISSUE #22547: Ingest node date processor uses stale year information on calendar year change
**Elasticsearch version**:
5.1.1

**JVM version**:
1.8.0.111

**OS version**:
CentOS 7.3

**Description of the problem including expected versus actual behavior**:

I'm feeding /var/log/secure to elasticsearch, using filebeat and ingest node. This worked fine before the new year, but then I noticed entries appearing with a one year old timestamp.
Turns out, the date processor was parsing the date string "Jan 2 23:59:48" as "2016-01-02T23:59:48.000Z". Restarting elasticsearch caused new entries to get the correct year information.

More info available [here](https://discuss.elastic.co/t/filebeat-syslog-module-problem-on-year-change/71114).
Possibly related to [logstash-plugins/logstash-filter-date#3](https://github.com/logstash-plugins/logstash-filter-date/issues/3)

### PR DESCRIPTION
**Pull request by talevy**
Beforehand, the DateProcessor constructs its joda pattern formatter during processor
construction. This led to newly ingested documents being defaulted to
the year that the pipeline was constructed, not that of processing.

Fixes #22547.

### CODE REVIEW

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateProcessorTests.java [hunk 1]
```diff
@@ -105,14 +106,28 @@ public void testJodaPatternLocale() {
     }
 
     public void testJodaPatternDefaultYear() {
+        // fix joda's new DateTime() to Jan 12, 2017
+        DateTimeUtils.setCurrentMillisFixed(1484255848828L);
```
Comment (talevy) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateProcessorTests.java]: this seems to be the way Joda set up to do such mock-hackery... I don't especially like it since this may affect other threads running during testing (not sure).

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateProcessorTests.java [hunk 2]
```diff
@@ -105,14 +106,28 @@ public void testJodaPatternLocale() {
...
+        // bump year to check next execution's default year
+        // fix joda's new DateTime() to Jan 12, 2018
+        DateTimeUtils.setCurrentMillisFixed(1515791848828L);
+
+        ingestDocument = RandomDocumentPicks.randomIngestDocument(random(), document);
+        dateProcessor.execute(ingestDocument);
+        assertThat(ingestDocument.getFieldValue("date_as_date", String.class), equalTo("2018-06-12T00:00:00.000+02:00"));
+
+        // cleanup
+        DateTimeUtils.setCurrentMillisSystem();
```
Comment (rjernst) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateProcessorTests.java]: I think this should be done in a `finally` block?

**Review by rjernst — APPROVED** [review]
LGTM, one minor comment on the test

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateProcessorTests.java (hunk 2 above)
Comment (talevy) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateProcessorTests.java]: sounds like a plan. I thought about it but realized the test is already somewhat making assumptions that things will go right, but I'll wrap it for extra measure 👍

**Comment by talevy** [comment]
@rjernst I've reverted the tests to pass security checks

**Comment by rjernst** [comment]
LGTM

**Comment by talevy** [comment]
retest this please

**Comment by talevy** [comment]
retest this please

**Comment by talevy** [comment]
retest this please
