### PR TITLE
Fix early termination of aggregators that run with breadth-first mode

### LINKED ISSUE #44909: Terms aggregations shows partial results with terms aggregation over invalid field
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.1
Works as expected in 6.4.3.
Unexpected behavior for versions 6.5.3 to 6.8.1

**Plugins installed**: Default plugins in docker image provided Elastic

**JVM version** (`java -version`): 11.0

**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**:
Aggregations with a term referrencing a `min` aggregation over an invalid field does not return results per bucket. Other aggregations are not affected.

**Steps to reproduce**:

The following script reproduces the issue on a local default ES instance:
```python
import requests

ES = 'http://localhost:9200'

## Set up
requests.delete(ES + '/parrot')

requests.put(ES + '/parrot')

requests.post(ES + '/parrot/doc', json={ "a": 1, "b": 2 })
requests.post(ES + '/parrot/doc', json={ "a": 1, "b": 2 })
requests.post(ES + '/parrot/doc', json={ "a": 2, "b": 3 })

requests.post(ES + '/parrot/_refresh')

resp = requests.get(ES + '/parrot/_search', json={
    "size":0,
    "timeout":"1m",
    "query":{
        "constant_score":{
            "filter":{
                "bool":{
                    "filter":[{"exists":{"field":"a","boost":1.0}}],
                    "adjust_pure_negative":True,"boost":1.0
                }
            },"boost":1.0
        }
    },
    "aggregations":{
        "v__max:max":{"max":{"field":"invalid"}},
        "a":{"terms":{"field":"a","show_term_doc_count_error":False,"order":[{"v__max:max":"asc"},{"_key":"asc"}]},
        "aggregations":{"v__max:max":{"max":{"field":"invalid"}}}}
    }
})
print(resp.json())

resp = requests.get(ES + '/parrot/_search', json={
    "size":0,
    "timeout":"1m",
    "query":{
        "constant_score":{
            "filter":{
                "bool":{
                    "filter":[{"exists":{"field":"a","boost":1.0}}],
                    "adjust_pure_negative":True,"boost":1.0
                }
            },"boost":1.0
        }
    },
    "aggregations":{
        "v__min:min":{"min":{"field":"invalid"}},
        "a":{"terms":{"field":"a","show_term_doc_count_error":False,"order":[{"v__min:min":"asc"},{"_key":"asc"}]},
        "aggregations":{"v__min:min":{"min":{"field":"invalid"}}}}
    }
})
print(resp.json())
```

Actual behavior:
```
{
  'took':369,
  'timed_out':False,
  '_shards':{
    'total':5,
    'successful':5,
    'skipped':0,
    'failed':0
  },
  'hits':{
    'total':3,
    'max_score':0.0,
    'hits':[

    ]
  },
  'aggregations':{
    'a':{
      'doc_count_error_upper_bound':0,
      'sum_other_doc_count':0,
      'buckets':[
        {
          'key':1,
          'doc_count':2,
          'v__max:max':{
            'value':None
          }
        },
        {
          'key':2,
          'doc_count':1,
          'v__max:max':{
            'value':None
          }
        }
      ]
    },
    'v__max:max':{
      'value':None
    }
  }
}
```
```
{
  'took':22,
  'timed_out':False,
  '_shards':{
    'total':5,
    'successful':5,
    'skipped':0,
    'failed':0
  },
  'hits':{
    'total':3,
    'max_score':0.0,
    'hits':[

    ]
  },
  'aggregations':{
    'a':{
      'doc_count_error_upper_bound':0,
      'sum_other_doc_count':0,
      'buckets':[

      ]
    },
    'v__min:min':{
      'value':None
    }
  }
}
```
The query with min returns no buckets.

Expected behavior:

```
{'took': 256, 'timed_out': False, '_shards': {'total': 5, 'successful': 5, 'skipped': 0, 'failed': 0}, 'hits': {'total': 3, 'max_score': 0.0, 'hits': []}, 'aggregations': {'a': {'doc_count_error_upper_bound': 0, 'sum_other_doc_count': 0, 'buckets': [{'key': 1, 'doc_count': 2, 'v__max:max': {'value': None}}, {'key': 2, 'doc_count': 1, 'v__max:max': {'value': None}}]}, 'v__max:max': {'value': None}}}
```
```
{'took': 156, 'timed_out': False, '_shards': {'total': 5, 'successful': 5, 'skipped': 0, 'failed': 0}, 'hits': {'total': 3, 'max_score': 0.0, 'hits': []}, 'aggregations': {'a': {'doc_count_error_upper_bound': 0, 'sum_other_doc_count': 0, 'buckets': [{'key': 1, 'doc_count': 2, 'v__min:min': {'value': None}}, {'key': 2, 'doc_count': 1, 'v__min:min': {'value': None}}]}, 'v__min:min': {'value': None}}}
```

### PR DESCRIPTION
**Pull request by jimczi**
This commit fixes a bug when a deferred aggregator tries to early terminate the collection. In such case the CollectionTerminatedException is not caught and
the search fails on the shard. This change makes sure that we catch the exception in order to continue the deferred collection on the next leaf.

Fixes #44909

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java [hunk 1]
```diff
@@ -411,4 +412,34 @@ public void testEarlyTermination() throws Exception {
...
         assertThat(count.getValue(), equalTo(20L));
     }
+
+    public void testNestedEarlyTermination() throws Exception {
+        for (Aggregator.SubAggCollectionMode collectionMode : Aggregator.SubAggCollectionMode.values()) {
+            SearchResponse searchResponse = client().prepareSearch("idx")
+                .setTrackTotalHits(false)
+                .setQuery(matchAllQuery())
+                .addAggregation(max("max").field("values"))
+                .addAggregation(count("count").field("values"))
```
Comment (polyfractal) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java]: An unrelated question: is the `count` agg required here to check for correctness?  It looks like `count` doesn't use the early termination optimization, so wasn't sure if that is being used as a proxy to make sure that other aggs are unaffected, or something?

Asking because @csoulios is converting the max IT to unit tests, and we were discussing the other early termination test last week. I wasn't quite sure the purpose of `count` here, or if it was included because why not :)

**Review by polyfractal — APPROVED** [review]
LGTM.  Shame we have to use exceptions for control flow, but last time I looked at all of this it definitely seemed like the path of least resistance :)

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java (hunk 1 above)
Comment (jimczi) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java]: Yes, it is used to check if a sibling is not affected by an aggregation that terminates early. So the fact that we don't collect any hits for the `max` aggregation should not impact the `count` one which needs to see all hits.

Comment (polyfractal) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java]: Gotcha, thanks.  So if we embedded this inside a `filter` agg with `match_all` it should be functionally the same, right?

`AggregatorTestCase` currently assumes a single top-level agg for simplicity, so when converting these IT over to unit tests we weren't sure how to handle it.  We could also just leave the early termination tests as IT too.

(Note: not for this PR, just discussion regarding the changes we're making to tests in a separate PR)

**Comment by jimczi** [comment]
@elasticmachine run elasticsearch-ci/2

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java (hunk 1 above)
Comment (jimczi) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/MaxIT.java]: > So if we embedded this inside a filter agg with match_all it should be functionally the same, right?

Yes
