### PR TITLE
Reject IPv6-mapped IPv4 addresses when using the CIDR notation.

### LINKED ISSUE #26078: `ip` field does not allow prefix queries with ipv6-mapped ipv4 addresses
Recreation:
```
PUT index
{
  "mappings": {
    "doc": {
      "properties": {
        "client_ip": {
          "type": "ip"
        }
      }
    }
  }
}

GET index/_validate/query?rewrite=true
{
  "query": {
    "query_string": {
      "query": "client_ip:\"::ffff:0:0/96\""
    }
  }
}
```
which gives

```
{
  "valid": true,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "explanations": [
    {
      "index": "index",
      "valid": true,
      "explanation": """MatchNoDocsQuery("failed [client_ip] query, caused by illegal_argument_exception:[illegal prefixLength '96'. Must be 0-32 for IPv4 ranges, 0-128 for IPv6 ranges]")"""
    }
  ]
}
```

The issue is that the ip address is automatically translated to an ipv4 address, so we then interpret the prefix length as if the ip was an ipv4 address.

### PR DESCRIPTION
**Pull request by jpountz**
It introduces ambiguity as to whether the prefix length should be interpreted as
a v4 prefix length or a v6 prefix length.

See https://issues.apache.org/jira/browse/LUCENE-7920.

Closes #26078

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/common/network/InetAddressesTests.java [hunk 1]
```diff
@@ -214,4 +216,26 @@ public void testToUriStringIPv6() {
...
     }
+
+    public void testParseCidr() {
+        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> InetAddresses.parseCidr(""));
+        assertThat(e.getMessage(), Matchers.containsString("Expected [ip/prefix] but was []"));
+
+        e = expectThrows(IllegalArgumentException.class, () -> InetAddresses.parseCidr("192.168.1.42/40"));
+        assertThat(e.getMessage(), Matchers.containsString("Illegal prefix length"));
+
+        e = expectThrows(IllegalArgumentException.class, () -> InetAddresses.parseCidr("::1/130"));
```
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/common/network/InetAddressesTests.java]: Can you test the edges for each, so 129, 128 and 32, 33?

**Review by rjernst — APPROVED** [review]
LGTM
