### PR TITLE
Fix flaky test addSnapshotLifecyclePolicy

### LINKED ISSUE #46021: [CI] Failure in ILMDocumentationIT.testAddSnapshotLifecyclePolicy
The following failed on `7.x`:

```
11:09:05 org.elasticsearch.client.documentation.ILMDocumentationIT > testAddSnapshotLifecyclePolicy FAILED
11:09:05     java.lang.AssertionError: 
11:09:05     Expected: <1L>
11:09:05          but: was <2L>
11:09:05         at __randomizedtesting.SeedInfo.seed([667E1B76EEB11627:FF88531C062144A]:0)
11:09:05         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:09:05         at org.junit.Assert.assertThat(Assert.java:956)
11:09:05         at org.junit.Assert.assertThat(Assert.java:923)
11:09:05         at org.elasticsearch.client.documentation.ILMDocumentationIT.testAddSnapshotLifecyclePolicy(ILMDocumentationIT.java:869)
11:09:06 REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.documentation.ILMDocumentationIT.testAddSnapshotLifecyclePolicy" -Dtests.seed=667E1B76EEB11627 -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=America/Lima -Dcompiler.java=12 -Druntime.java=8
```

[Build Scan](https://gradle-enterprise.elastic.co/s/r2vkjnwvgohzs/console-log)

@dakrone can you take a look?

### PR DESCRIPTION
**Pull request by andreidan**
Fixes #46021 

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java [hunk 1]
```diff
@@ -797,32 +797,11 @@ public void testAddSnapshotLifecyclePolicy() throws Exception {
         // end::slm-put-snapshot-lifecycle-policy-response
         assertTrue(putAcknowledged);
 
-        // tag::slm-put-snapshot-lifecycle-policy-execute-listener
-        ActionListener<AcknowledgedResponse> putListener =
```
Comment (dakrone) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java]: These are here because they are used as snippets to generate the high level rest client documentation (that's what the surrounding `// tag::etcetc` and `// end::etcetc` are for, so I don't think we should remove these

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java [hunk 2]
```diff
@@ -858,18 +838,7 @@ public void onFailure(Exception e) {
         SnapshotLifecyclePolicyMetadata policyMeta =
             getResponse.getPolicies().get("policy_id"); // <1>
         long policyVersion = policyMeta.getVersion();
-        long policyModificationDate = policyMeta.getModifiedDate();
```
Comment (dakrone) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java]: Even though these appear unused, they are documenting how to retrieve things from the policy metadata, so we should leave them. See `get_snapshot_lifecycle_policy.asciidoc` for the callout usages

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java [hunk 3]
```diff
@@ -797,32 +797,11 @@ public void testAddSnapshotLifecyclePolicy() throws Exception {
...
-
-            @Override
-            public void onFailure(Exception e) {
-                // <2>
-            }
-        };
-        // end::slm-put-snapshot-lifecycle-policy-execute-listener
-
-        // tag::slm-put-snapshot-lifecycle-policy-execute-async
-        client.indexLifecycle().putSnapshotLifecyclePolicyAsync(request,
```
Comment (dakrone) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/ILMDocumentationIT.java]: I think rather than remove this (which we need for documentation), we should relax or remove the assertion to not trip on the policy version.

**Review by dakrone — CHANGES_REQUESTED** [review]
Thanks for taking a look at this Andrei, I left comments about what these unused blocks of code are for and why we shouldn't remove them.

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by andreidan** [comment]
retest this please
