### PR TITLE
SQL: Fix incorrect parameter resolution

### LINKED ISSUE #56013: SQL: incorrect column resolution from parameter
```
POST _sql
{
  "query": "SELECT ?, ? FROM library",
  "params": [
    {
      "type": "INTEGER",
      "value": 1
    },
    {
      "type": "INTEGER",
      "value": 2
    }
  ],
  "mode": "jdbc",
  "version": "7.7.0"
}
```
will fail with `Unknown output attribute ?{r}#9796`.

Leaving the index out _or_ changing the parameter type (i.e. no type repetition in the list) will work as expected.

Stacktrace:
```
    java.sql.SQLException: Server encountered an error [Unknown output attribute ?{r}#27]. [org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Unknown output attribute ?{r}#27
        at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.asFieldExtraction(QueryContainer.java:478)
        at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.addColumn(QueryContainer.java:445)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$PlanOutputToQueryRef.rule(QueryFolder.java:781)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$PlanOutputToQueryRef.rule(QueryFolder.java:770)
        at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$11(Node.java:197)
        at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:191)
        at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:197)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:875)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:871)
        at org.elasticsearch.xpack.ql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.ql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)
        at org.elasticsearch.xpack.ql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:111)
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:160)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:156)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:144)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:288)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:88)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:101)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:97)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1103)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1181)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1161)
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

### PR DESCRIPTION
**Pull request by palesz**
For example in the query `SELECT ? FROM test` with a single integer
(value = 100) parameter the ? turns into an `Alias
(child=Literal(100),name="?")` or if we try to print it back into SQL, `SELECT 100 
as ? FROM test`.

A problem arises when multiple `?` is in the query with the same type.
For example the `SELECT ?, ? FROM test` query with integer parameters
(value=100, 200) will turn into `SELECT 100 as ?, 200 as ? FROM test`.

This commit changes the way aliases are assigned: the first unaliased
parameter will stay `?`, but from the 2nd unaliased parameter literal
a counter will be added to the alias (`?2`, `?3`, ...).

Callout: This will introduce a change for the users: a query with
multiple unaliased parameters (but each parameter with different
types) successfully executed before and returned the results with
multiple `?` columns (although must have accessed via index from the
result set instead of alias). Now all, but the first column will have a 
suffix ( `?` -> `?n`).

Fix #56013

### CODE REVIEW

**Comment by palesz** [comment]
I had a suspicion that this will happen. This change of mine broke the subselects. I guess this was the reason of using vanilla maps as an input of the `AttributeMap` constructors. Tomorrow I will take another stab.

**Review by costin — CHANGES_REQUESTED** [review]
This approach works but being downstream, in the Analyzer, makes things more complicated.
Instead of passing the parameters all the way to the analyzer, it's easier to assign the proper alias directly in the parser when creating the literal in the first place.
See `ExpressionBuilder#visitParamLiteral` - the ordinal can be created on the fly or further more inferred into the map since that information is already available.

Also I opt for consistency - if we add indices, it makes sense to do that for `?` signs including the first one.
The question remains whether the count should start at 0 or 1 depending on the rest of the jdbc/odbc API conventions.

**Comment by palesz** [comment]
Pushed down the changes from the `Analyzer` into the parser (`ExpressionBuilder#visitSelectExpression`) based on our discussion.

Note: Indexing of the parameters changed, `SELECT ?, ? as x, ? FROM test` with parameters `(100, 200)` will be parsed into `SELECT 100 as ?1, ? as x, 200 as ?3 FROM test`, so the suffixes represent the position of the original parameter (starting with 1 to mimic the JDBC parameter indexes). This will introduce a breaking change to the client, columns names will change from `?` to `?<param index>` in all unaliased cases.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 1]
```diff
@@ -956,8 +956,7 @@ private boolean hasUnresolvedAliases(List<? extends NamedExpression> expressions
 
         private List<NamedExpression> assignAliases(List<? extends NamedExpression> exprs) {
             List<NamedExpression> newExpr = new ArrayList<>(exprs.size());
-            for (int i = 0; i < exprs.size(); i++) {
-                NamedExpression expr = exprs.get(i);
+            for (NamedExpression expr : exprs) {
                 NamedExpression transformed = (NamedExpression) expr.transformUp(ua -> {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:960]: Please revert. The PRs should contain the minimal number of changes needed and not affect the rest of the code

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java [hunk 2]
```diff
@@ -767,6 +777,16 @@ private SqlTypedParamValue param(TerminalNode node) {
         return params.get(token);
     }
 
+    private SqlParser.SqlParameter param(ParserRuleContext ctx) {
+        if (!ctx.getStart().equals(ctx.getStop())) {
+            throw new ParsingException(source(ctx), "Single PARAM literal expected");
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:782]: Incorrect style (use `== false` instead of `!`).
I'm not sure what this check tries to prevent...

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/SqlParser.java [hunk 3]
```diff
@@ -240,26 +261,28 @@ public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int
...
         public Token nextToken() {
             Token token = delegate.nextToken();
             if (token.getType() == SqlBaseLexer.PARAM) {
-                if (param >= params.size()) {
+                if (paramIndex >= params.size()) {
                     throw new ParsingException("Not enough actual parameters {} ", params.size());
                 }
-                paramTokens.put(token, params.get(param));
-                param++;
+                paramTokens.put(token, new SqlParameter(paramIndex+1, params.get(paramIndex)));
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/SqlParser.java:284]: incorrect formatting `paramIndex + 1`

**Review by costin — CHANGES_REQUESTED** [review]
> Callout: This will introduce a change for the users: a query with
multiple unaliased parameters (but each parameter with different
types) successfully executed before and returned the results with
multiple ? columns (although must have accessed via index from the
result set instead of alias). Now all, but the first column will have a
suffix ( ? -> ?n).

I think aliasing with `?` is incorrect and in fact we should alias with the actual value.
I'd check with other DBs to see how they handle this:

`SELECT ?` is the same as `SELECT <param>` so I would expect this to return the value aliases as <param> not ?.

**Comment by costin** [comment]
I think a much easier fix is if in `ExpressionBuilder#visitParamLiteral` the original source is not preserved and instead it is replaced by the literal value.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java (hunk 2 above)
Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:782]: style: any reason why this is not part of `checkStyle` and the `precommit` checks?
I will remove this check, it was more like a sanity check (during unit & integ test) for me to see if there are any possibility where the start and stop token won't be the same. This should never happen.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/SqlParser.java (hunk 3 above)
Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/SqlParser.java:284]: style: will do, again would be great to add it to `checkStyle`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 1 above)
Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:960]: Thanks, leftover from prev commits.

**Review by matriv — COMMENTED** [review]
@costin 
> I think aliasing with `?` is incorrect and in fact we should alias with the actual value.
> I'd check with other DBs to see how they handle this:

PostgreSQL supports alias on the `?` params. For a query like:
```SELECT ? AS x, ? FROM test```
executed with JDBC prepared stmt, the returned column names are:
`x` and `?column?` respectively.

**Comment by palesz** [comment]
> I think aliasing with `?` is incorrect and in fact we should alias with the actual value.
> I'd check with other DBs to see how they handle this:

Checked MySQL (alias with actual value) and PostgreSQL (`?column?`), SQLite (`?`) all have their own approaches. None of them aliases with the index of the parameter.

### mysql through JDBC
```sql
SELECT ?, ?, ? as aliased, col1 from test_table
```

| param without alias | second param without alias | aliased | col1 |
| ------------------- | -------------------------- | ------- | ---- |
| param without alias | second param without alias | param with alias | 0 |



### postgresql through JDBC
```sql
SELECT ?, ?, ? as aliased, col1 from test_table
```

| ?column? | ?column? | aliased | col1 |
| -------- | -------- | ------- | ---- |
| param without alias | second param without alias | param with alias | 0 |



### sqlite through JDBC
```sql
SELECT ?, ?, ? as aliased, col1 from test_table
```

| ? | ? | aliased | col1 |
| - | - | ------- | ---- |
| param without alias | second param without alias | param with alias | 0 |

**Review by matriv — COMMENTED** [review]
@palesz Could we please have some test where the aliased param is also used somewhere else in the query? e.g.:
```
SELECT ? AS x FROM test WHERE  foo > x
```
Although SQL standard doesn't support alias to be used in the WHERE clause, but only if it's wrapped as a subselect of an outer select that would now of the defined alias, ee added this support to ES-EQL to ease the life of our users. So it would be great to see how the alias on a param would behave.

**Comment by palesz** [comment]
> `SELECT ?` is the same as `SELECT <param>` so I would expect this to return the value aliases as not ?.

Ok, I am convinced, we can go with the MySQL approach.

> I think a much easier fix is if in `ExpressionBuilder#visitParamLiteral` the original source is not preserved and instead it is replaced by the literal value.

Aside that I don't like changing the `Source` on the `Literal, just tried this approach by overriding the original source in the `ExpressionBuilder#visitParamLiteral`: 

```java
source = new Source(source.source(), String.valueOf(param.value));
```

This results in the exact same problem as reported in the original issue, see this test case:

```java
    public void testFoldingWithParamsWithoutIndex() {
        PhysicalPlan p = optimizeAndPlan(parameterizedSql("SELECT ?, ?, ? FROM test",
            new SqlTypedParamValue("integer", 100),
            new SqlTypedParamValue("integer", 100),
            new SqlTypedParamValue("integer", 200)));
        assertThat(p.output(), everyItem(isA(ReferenceAttribute.class)));
        assertThat(p.output().get(0).toString(), startsWith("100{r}#"));
        assertThat(p.output().get(1).toString(), startsWith("100{r}#"));
        assertThat(p.output().get(2).toString(), startsWith("200{r}#"));
    }
```

and the exception I get running the case above:

```
Unknown output attribute 100{r}#24
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Unknown output attribute 100{r}#24
	at __randomizedtesting.SeedInfo.seed([1CAB04E18267B857:2B44D1843B319971]:0)
	at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.asFieldExtraction(QueryContainer.java:478)
```

since there will be two Literals with `100` value and those two have the same `hashCode` -> only one entry will be in the `AttributeMap` -> one of attributes will be unknown -> back to the starting point.

I have an idea though how to solve this still (mostly) in the `visitParamLiteral` (stay tuned).

**Comment by palesz** [comment]
> > `SELECT ?` is the same as `SELECT <param>` so I would expect this to return the value aliases as not ?.
> 
> Ok, I am convinced, we can go with the MySQL approach.
> 

Actually, if I alias to the Literal value the above test case can fail no matter what we dig even deeper and fix the underlying issue regarding the Expression -> ReferenceAttribute mapping. I can only solve this with unique param aliases without touching the `ReferenceAttribute` mapping.

**Comment by palesz** [comment]
Even the `SELECT 3, 3 FROM test_table` query (without parameters) failed, so this was really not connected to the parameter literals, so the fix also has nothing to do with them. Now even that double-constant query works (see below):


### The SQL call that failed originally now works

    POST /_sql
    Content-Type: application/json
    
    {
      "query": "SELECT ?, ? FROM library",
      "params": [
        {
          "type": "INTEGER",
          "value": 1
        },
        {
          "type": "INTEGER",
          "value": 1
        }
      ],
      "mode": "jdbc",
      "version": "7.7.0"
    }

Result:

    HTTP/1.1 200 OK
    Took-nanos: 13019032
    content-type: application/cbor
    content-length: 95
    
    gcolumnsdnamea?dtypegintegerldisplay_sizednamea?dtypegintegerldisplay_sizedrows

### Without the `jdbc` mode

    POST /_sql
    Content-Type: application/json
    
    {
      "query": "SELECT ?, ? FROM library",
      "params": [1, 1],
      "version": "7.7.0"
    }

Result: 

    {
      "columns": [
        {
          "name": "?",
          "type": "integer"
        },
        {
          "name": "?",
          "type": "integer"
        }
      ],
      "rows": [
        [
          1,
          1
        ]
      ]
    }

### query without params (previously only worked without `FROM ...`)



    POST /_sql
    Content-Type: application/json
    
    {
      "query": "SELECT 3, 3 FROM library",
      "version": "7.7.0"
    }

Result:

    {
      "columns": [
        {
          "name": "3",
          "type": "integer"
        },
        {
          "name": "3",
          "type": "integer"
        }
      ],
      "rows": [
        [
          3,
          3
        ]
      ]
    }

**Comment by palesz** [comment]
> @palesz Could we please have some test where the aliased param is also used somewhere else in the query? e.g.:
> 

Did not add it yet, but quickly querying it via `http` it works (I guess this should go somewhere in `csv-spec`):

Note: `library` has a single record with `x=1`

    POST /_sql
    Content-Type: application/json
    
    {
      "query": "SELECT ? as a, x FROM library WHERE x < a",
      "params": [100],
      "version": "7.7.0"
    }

Result:

    {
      "columns": [
        {
          "name": "a",
          "type": "integer"
        },
        {
          "name": "x",
          "type": "long"
        }
      ],
      "rows": [
        [
          100,
          1
        ]
      ]
    }

Query:

    POST /_sql
    Content-Type: application/json
    
    {
      "query": "SELECT ? as a, x FROM library WHERE x < a",
      "params": [-100],
      "version": "7.7.0"
    }

Result: 

    {
      "columns": [
        {
          "name": "a",
          "type": "integer"
        },
        {
          "name": "x",
          "type": "long"
        }
      ],
      "rows": []
    }

**Comment by palesz** [comment]
Seems that `ci` builds failed with transient `docker` issues + left a couple `System.out.println`s in that failed the `forbiddenApiTest`.

**Comment by palesz** [comment]
After a lots of back and forth and discussions here is a summary of the issue and the root cause:

```
(1) SELECT 100, 100 -> success
(2) SELECT ?, ? (with params: 100, 100) -> success
(3) SELECT 100, 100 FROM test -> Unknown output attribute exception for the second 100
(4) SELECT ?, ? FROM test (params: 100, 100) -> Unknown output attribute exception for the second ?
(5) SELECT field1 as "x", field1 as "x" FROM test -> Unknown output attribute exception for the second "x"
```

There are two separate issues at play here:
1. Construction of `AttributeMap`s keeps only one of the `Attribute`s with the same name even if the `id`s are different (see the `AttributeMapTests` in this PR). This should be fixed no matter what, we should not overwrite attributes with one another during the construction of the `AttributeMap`.
2. The `id` on the `Alias`es is not the same in case the `Alias` name

It was considered to simpy fix the second issue by just reassigning the same `id`s to the `Alias`es with the same name and child, but it would not solve the `unknown output attribute exception` (see notes below). This PR covers the fix for the first issue and I'll create a new PR for the second issue which is not urgent to fix, rather *good to have*.

----

### Notes and more context

Reassigning `id`s would not work in the `Analyzer/ReplaceAlias` either, as long I need to transform `Alias` -> `Alias` (just `id` change), the `node.transform...` functions will not change the tree if the transformed object is equal to the original one. Which it will be, since neither the `equals` or the `semanticEquals` of the `Alias` take into account the `id` field (`id` field only counts for the `Attribute#semanticEquals`, not even for the `Attribute#equals`) --> We can only do this `id` change where the `Literal` is wrapped into an `Alias` and where the `Alias` is created, so the tree changes after the transform from the `node#transform...`’s point of view.

Further, think about the following case:

```sql
SELECT ?, ?, ? FROM test
``` 

with params `100`, `100`, `200`.

This would be translated into:

```sql
SELECT 100 AS ?#1, 100 AS ?#2, 200 AS ?#3 FROM test
```

Once we change the IDs to match on the `Alias`es with the same literals (only `Alias` have id, `Literal` does not), we get:

```sql
SELECT 100 AS ?#1, 100 AS ?#1, 200 AS ?#3 FROM test
```

This will result in three reference attributes that we try to put into a `Map` and later into an `AttributeMap`:

```
?#{r}1 (ReferenceAttribute(name=?, id=1, type=INTEGER) -> 100
?#{r}1 (ReferenceAttribute(name=?, id=1, type=INTEGER) -> 100
?#{r}3 (ReferenceAttribute(name=?, id=3, type=INTEGER) -> 200
```

But this will exactly lead to the same issue, we will get `unknown output attribute` because the `AttributeMap` will look like this:

```
?#{r}1 (ReferenceAttribute(name=?, id=1, type=INTEGER) -> 200
```

Which is incorrect. It should be:

```
?#{r}1 (ReferenceAttribute(name=?, id=1, type=INTEGER) -> 100
?#{r}3 (ReferenceAttribute(name=?, id=3, type=INTEGER) -> 200
```

Why does this happen? Becase from the `List<Alias>`es gets transformed into a simple `LinkedHashMap` via `map.put(alias.toAttribute(), alias.child)` and later it is turned into an `AttributeMap` via the `AttributeMap(Map)` constructor. But the `map.put` uses the `Attribute#equals` which only checks the `name`, but not the `id`. The `AttributeMap` uses the `Attribute#semanticEquals` which checks the `id`, but by the time the `AttributeMap` gets populated the .

The only way to fix this is to additionally to reassigning the `id`s, we also change the aliasing from `100 as ?` to `100 as 100`. But this is to workaround the fact that the way we construct the `AttributeMap` is not correct right now (we overwrite `ReferenceAttribute`s unintentionally.

I would add to this that the following case also fails with `unknown output attribute`:

```
SELECT col1 AS "x", col1 AS "x" FROM test
```

Which won’t be fixed, even if I re-alias the parameter literals to their values  (`literal as ?` -> `literal as literal`). And I cannot use the normal node transform functions to replace their alias either (see above).

Conclusion: No matter what, I think we should fix the way `AttributeMap` are constructed. We need to remove the `AttributeMap(Map)` constructor and use the `builder` that can call the `AttrbuteMap#add` internally.

Once we did that, we can also think about whether or not to reuse the same `id`s.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java [hunk 4]
```diff
@@ -189,11 +189,12 @@ public Verifier(Metrics metrics) {
             plan.forEachExpressionsUp(e -> {
                 if (e instanceof Alias) {
                     Alias a = (Alias) e;
-                    collectRefs.put(a.toAttribute(), a.child());
+                    Attribute attr = a.toAttribute();
+                    collectRefs.put(attr, a.child());
```
Comment (palesz) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java:193]: Will merge these two lines.

**Comment by palesz** [comment]
As a separate PR I will also remove the deprecetad `AttributeMap(Map)` ctor.

File: x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec [hunk 5]
```diff
@@ -48,6 +48,8 @@ SELECT salary, first_name, salary AS x, salary y FROM test_emp ORDER BY y LIMIT
 
 constantWithLimit
 SELECT 3 FROM "test_emp" LIMIT 5;
+sameConstantsWithLimit
+SELECT 3, 3, 5 FROM "test_emp" LIMIT 5;
```
Comment (costin) [inline x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec:52]: Work adding a few more variations here:
`SELECT 3, 5, 3`, `SELECT 5, 3, 3, 3` with and without FROM.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java (hunk 4 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java:193]: You need the checks to pass before merging so you'll have to do it anyway, better do it sooner rather than later.

**Review by costin — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Worth creating/linking the issue around `SELECT ?, ?` and id reuse to this issue.

File: x-pack/plugin/ql/src/test/java/org/elasticsearch/xpack/ql/expression/AttributeMapTests.java [hunk 6]
```diff
@@ -37,6 +38,47 @@ private static Attribute a(String name) {
...
+        assertFalse(attributeMap.containsKey(param2.toAttribute())); // results in unknown attribute exception
+
+        AttributeMap.Builder<Expression> mapBuilder = AttributeMap.builder();
+        for (Alias a : List.of(param1, param2)) {
+            mapBuilder.put(a.toAttribute(), a.child());
+        }
+        AttributeMap<Expression> newAttributeMap = mapBuilder.build();
+
+        assertTrue(newAttributeMap.containsKey(param1.toAttribute()));
+        assertTrue(newAttributeMap.containsKey(param2.toAttribute())); // no more unknown attribute exception
```
Comment (matriv) [inline x-pack/plugin/ql/src/test/java/org/elasticsearch/xpack/ql/expression/AttributeMapTests.java:72]: Maybe also check the returned values with get() from the map, can be done in the next PR though.

**Review by matriv — APPROVED** [review]
LGTM, Thx a lot for this effort!

File: x-pack/plugin/ql/src/test/java/org/elasticsearch/xpack/ql/expression/AttributeMapTests.java [hunk 7]
```diff
@@ -37,6 +38,47 @@ private static Attribute a(String name) {
...
+        Map<Attribute, Expression> collectRefs = new LinkedHashMap<>();
+        for (Alias a : List.of(param1, param2)) {
+            collectRefs.put(a.toAttribute(), a.child());
+        }
+        // we can look up the same item by both attributes
+        assertNotNull(collectRefs.get(param1.toAttribute()));
+        assertNotNull(collectRefs.get(param2.toAttribute()));
+        AttributeMap<Expression> attributeMap = new AttributeMap<>(collectRefs);
+
+        // validate that all Alias can be e
```
Comment (bpintea) [inline x-pack/plugin/ql/src/test/java/org/elasticsearch/xpack/ql/expression/AttributeMapTests.java:61]: nit: "~ wrapper collided" or some other comment correction (can be the next PR, obv.)

**Review by bpintea — APPROVED** [review]
LGTM
