### PR TITLE
Fix and unmute package upgrade tests

### LINKED ISSUE #79950: [CI] PackageUpgradeTests test20InstallUpgradedVersion failing
Seems our package upgrade tests are failing when upgrading from 8.0.0 to 8.1.0 when verifying that we don't run security auto configuration again. It's possible this might be an actual issue.

**Build scan:**
https://gradle-enterprise.elastic.co/s/krjoyc56huo76/tests/:qa:os:destructiveDistroUpgradeTest.v8.0.0.default-deb/org.elasticsearch.packaging.test.PackageUpgradeTests/test20InstallUpgradedVersion

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PackageUpgradeTests&tests.test=test20InstallUpgradedVersion

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <false>
     but: was <true>

  at __randomizedtesting.SeedInfo.seed([1A9709608842AF00:4608857FB4D610FB]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.packaging.test.PackagingTestCase.verifySecurityNotAutoConfigured(PackagingTestCase.java:724)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.test20InstallUpgradedVersion(PackageUpgradeTests.java:84)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by jkakavas**
Fixes package upgrade tests and unmutes failing tests

resolves: #79950, #76283

### CODE REVIEW

**Comment by jkakavas** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-upgrade-tests

File: qa/os/src/test/java/org/elasticsearch/packaging/test/PackagesSecurityAutoConfigurationTests.java [hunk 1]
```diff
@@ -75,15 +75,13 @@ public void test10SecurityAutoConfiguredOnPackageInstall() throws Exception {
     public void test20SecurityNotAutoConfiguredOnReInstallation() throws Exception {
         // we are testing force upgrading in the current version
         // In such a case, security remains configured from the initial installation, we don't run it again.
-        Optional<String> autoConfigDirName = getAutoConfigDirName(installation);
+        byte[] transportKeystore = Files.readAllBytes(installation.config("certs").resolve("transport.p12"));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/PackagesSecurityAutoConfigurationTests.java:78]: Should we be using `AUTOCONFIG_DIRNAME` instead of `"certs"` here?

File: qa/os/src/test/java/org/elasticsearch/packaging/test/PackagesSecurityAutoConfigurationTests.java [hunk 2]
```diff
@@ -75,15 +75,13 @@ public void test10SecurityAutoConfiguredOnPackageInstall() throws Exception {
...
         installation = Packages.forceUpgradePackage(sh, distribution);
         assertInstalled(distribution);
         verifyPackageInstallation(installation, distribution, sh);
         verifySecurityAutoConfigured(installation);
-        // Since we did not auto-configure the second time, the directory name should be the same
-        assertThat(autoConfigDirName.isPresent(), is(true));
-        assertThat(getAutoConfigDirName(installation).isPresent(), is(true));
-        assertThat(getAutoConfigDirName(installation).get(), equalTo(autoConfigDirName.get()));
+        // Since we did not auto-configure the second time, the keystore should be the one we generated the first time, above
+        assertThat(transportKeystore, equalTo(Files.readAllBytes(installation.config("certs").resolve("transport.p12"))));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/PackagesSecurityAutoConfigurationTests.java:84]: Again, should we be using `AUTOCONFIG_DIRNAME` instead of `"certs"` here?

**Review by pugnascotia — APPROVED** [review]

**Comment by jkakavas** [comment]
a

**Comment by jkakavas** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/83206)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
