### PR TITLE
Fix DatabaseRegistry for Windows

### LINKED ISSUE #70977: [CI] GeoIpDownloaderStatsIT.testStats failing assertion
**Build scan**:
https://gradle-enterprise.elastic.co/s/gm4z6ub5ul5uk
**Repro line**:
./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderStatsIT.testStats" -Dtests.seed=E90EE55159FA9828 -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=Asia/Khandyga -Druntime.java=11
**Reproduces locally?**:
Yes
**Applicable branches**:
master
**Failure history**:
First failure
**Failure excerpt**:
```
java.lang.AssertionError: 
  | Expected: map containing ["databases"->ANYTHING] |  
  | but: map was [<files_in_temp=[GeoLite2-ASN.mmdb_README.txt, GeoLite2-ASN.mmdb_COPYRIGHT.txt]>] |  
  |   | at __randomizedtesting.SeedInfo.seed([E90EE55159FA9828:738FBCEE3126560B]:0) |  
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.ingest.geoip.GeoIpDownloaderStatsIT.lambda$testStats$1(GeoIpDownloaderStatsIT.java:96)



```

### LINKED ISSUE #71006: [CI] DatabaseRegistryTests testCheckDatabases failing
This has failed a number of times today and reproduces locally.

**Build scan**:
https://gradle-enterprise.elastic.co/s/vlat4vnmzmwra/tests/:modules:ingest-geoip:test/org.elasticsearch.ingest.geoip.DatabaseRegistryTests/testCheckDatabases#1

**Repro line**:
`./gradlew ':modules:ingest-geoip:test' --tests "org.elasticsearch.ingest.geoip.DatabaseRegistryTests.testCheckDatabases" -Dtests.seed=DC51F7818CF75EB6 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=Etc/GMT+9 -Druntime.java=11`

**Reproduces locally?**:
Yes.

**Applicable branches**:
master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.ingest.geoip.DatabaseRegistryTests&tests.sortField=FAILED&tests.test=testCheckDatabases&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.ingest.geoip.DatabaseRegistryTests > testCheckDatabases FAILED
    java.lang.AssertionError: 
    Expected: not null
         but: was null
        at __randomizedtesting.SeedInfo.seed([DC51F7818CF75EB6:E0E5ECF359A7F3B6]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.ingest.geoip.DatabaseRegistryTests.testCheckDatabases(DatabaseRegistryTests.java:143)
```

### PR DESCRIPTION
**Pull request by probakowski**
In `DatabaseRegistry` we tried to replace file that was still open. This is not a problem under Linux and MacOS but Windows doesn't like it. 
It was caught by our CI with reproducible failures when `WindowsFS` was set up by Lucene.
Now we skip one temp file and use `GzipInputStream` directly which fixes this problem.

Marking as non-issue since the code was not released yet.

Closes https://github.com/elastic/elasticsearch/issues/70977
Closes https://github.com/elastic/elasticsearch/issues/71006

### CODE REVIEW

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseRegistry.java [hunk 1]
```diff
@@ -259,12 +259,12 @@ void retrieveAndUpdateDatabase(String databaseName, GeoIpTaskState.Metadata meta
...
             () -> {
                 LOGGER.debug("decompressing [{}]", databaseTmpGzFile.getFileName());
-                decompress(databaseTmpGzFile, databaseTmpFile);
 
                 Path databaseFile = geoipTmpDirectory.resolve(databaseName);
                 // tarball contains <database_name>.mmdb, LICENSE.txt, COPYRIGHTS.txt and optional README.txt files.
                 // we store mmdb file as is and prepend database name to all other entries to avoid conflicts
-                try (TarInputStream is = new TarInputStream(new BufferedInputStream(Files.newInputStream(databaseTmpFile)))) {
+                try (TarInputStream is =
+                         new TarInputStream(new GZIPInputStream(new BufferedInputStream(Files.newInputStream(databaseTmpGzFile))))) {
```
Comment (dakrone) [inline modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseRegistry.java:267]: I think you may still want to pass 8192 into the GZIPInputStream constructor, if you want to keep the buffer at 8k? Otherwise the default is 512

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy, I left one comment about the change in buffer size

File: modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseRegistry.java (hunk 1 above)
Comment (probakowski) [reply modules/ingest-geoip/src/main/java/org/elasticsearch/ingest/geoip/DatabaseRegistry.java]: That makes sense, I've updated it

**Comment by probakowski** [comment]
I'm gonna merge it despite `packaging-sample-unix` not finished, it was green before cosmetic change from review and change has nothing to do with packaging
