### PR TITLE
Stabilise test by shortening the GCP/translog sync intervals

### LINKED ISSUE #146604: [CI] OpenCloseIndexIT testTranslogStats failing
**Build Scans:**
- [elasticsearch-periodic #12135 / openjdk25_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/24jmdtuxa27oe)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indices.state.OpenCloseIndexIT.testTranslogStats" -Dtests.seed=EF7A7E8E6D5D6526 -Dtests.locale=sr-ME -Dtests.timezone=America/Eirunepe -Druntime.java=25
```

**Applicable branches:**
9.3

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indices.state.OpenCloseIndexIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTranslogStats'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <3>
     but: was <8>
```

**Issue Reasons:**
- [9.3] 1 consecutive failures in test testTranslogStats
- [9.3] 1 consecutive failures in step openjdk25_checkpart1_java-matrix
- [9.3] 1 consecutive failures in pipeline elasticsearch-periodic

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by michalborek**
The test waits for a background task and in some cases takes up to 10 seconds to execute. 

Reducing the default intervals for background operations will make it faster (~10s -> 1-2s)

Closes: #146604

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 1]
```diff
@@ -360,7 +371,15 @@ public void testOpenCloseIndexWithBlocks() {
 
     public void testTranslogStats() throws Exception {
         final String indexName = "test";
-        createIndex(indexName, Settings.builder().put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0).build());
+        createIndex(
+            indexName,
+            Settings.builder()
+                .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
+                // sync global checkpoint and translog quickly so we can speed up the test
```
Comment (inespot) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: Nit: can you add a note to the comment that those settings should only really matter when the test uses `ASYNC` durability (if my understanding of your investigation so far is correct)?

**Review by inespot — APPROVED** [review]
LGTM!

File: server/src/internalClusterTest/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java (hunk 1 above)
Comment (michalborek) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: Actually, it matters in both cases. This shortens the REQUEST test as well (in some cases).

Comment (michalborek) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: When digging deeper into that I realized that the issue with faulty randomness mislead me

Comment (michalborek) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: This change should stabilize this test.

**Review by inespot — APPROVED** [review]
Given the seed weirdness flagged in Slack and the fact that we couldn't always fully confirm whether durability was `ASYNC` or `REQUEST` in all the repros, might be worth us keeping an eye on this one over the next few weeks?
