### PR TITLE
Finalize failed clone entries

### LINKED ISSUE #142919: Failed clone can lead to stucked snapshot deletion
When a clone fails, such as being deleted while running, it is [removed directly from the cluster state](https://github.com/elastic/elasticsearch/blob/dec6783fcba8a42a1e2ce2ae69a0e2708a8498bc/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L1034-L1044) without going through finalization. This is problematic because `removeFailedSnapshotFromClusterState` does not invoke [runNextQueuedOperation](https://github.com/elastic/elasticsearch/blob/dec6783fcba8a42a1e2ce2ae69a0e2708a8498bc/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L1527-L1529) when `repositoryData` is `null`. If a snapshot deletion is ready to run (state is `STARTED`), e.g. the very deletion that deleted the clone, it won't be kicked off and therefore stuck. 

One option to fix it is to let failed clone go through proper finalization. See also https://github.com/elastic/elasticsearch/pull/142192#discussion_r2813760908

### PR DESCRIPTION
**Pull request by ywangd**
Instead of removing them directly from the cluster state, this PR make them go through the same finalization path as all other snapshot entries and ensures continuous transitions for the snapshot state machines.

Resolves #142919

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -1150,17 +1138,21 @@ protected void doRun() {
...
                 final ShardState state = status.state();
                 if (state.failed()) {
-                    shardFailures.add(new SnapshotShardFailure(status.nodeId(), entry.shardId(shardId), status.reason()));
+                    final var shardId = entry.isClone()
+                        ? new ShardId(repoShardId.indexName(), IndexMetadata.INDEX_UUID_NA_VALUE, repoShardId.shardId())
+                        : entry.shardId(repoShardId);
+                    shardFailures.add(new SnapshotShardFailure(status.nodeId(), shardId, status.reason()));
                 } else if (state.completed() == false) {
-                    shardFailures.add(new SnapshotShardFailure(status.nodeId(), entry.shardId(shardId), "skipped"));
+                    assert entry.isClone() == false : "a finalizing clone has unexpected shard state " + entry;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:952]: Unrelated, but how can we be finalizing a regular snapshot into a state which is not completed?

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -1150,17 +1138,21 @@ protected void doRun() {
...
                     continue;
                 }
                 ShardSnapshotStatus status = shardStatus.getValue();
                 final ShardState state = status.state();
                 if (state.failed()) {
-                    shardFailures.add(new SnapshotShardFailure(status.nodeId(), entry.shardId(shardId), status.reason()));
+                    final var shardId = entry.isClone()
+                        ? new ShardId(repoShardId.indexName(), IndexMetadata.INDEX_UUID_NA_VALUE, repoShardId.shardId())
+                        : entry.shardId(repoShardId);
+                    shardFailures.add(new SnapshotShardFailure(status.nodeId(), shardId, status.reason()));
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:950]: Somewhat unrelated but it seems fairly pointless to record these things in `SnapshotInfo` for a `FAILED` snapshot which can therefore never be restored anyway.

**Review by DaveCTurner — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 1 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:952]: This branch was added in #51416. Back then, the create snapshot is a two step process, similar to clone, with adding an empty entry to the cluster state first, then populating the shards. The snapshot can fail during population for shard failures such as missing primary etc so that the finalization may see `INIT` shards.

It's no longer the case anymore. The `INIT` state for the Snapshot entry (not the shard) is not really used anywhere. So we should be able to remove this branch. Let me get to it in a separate PR.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:950]: I assume the failure reason might be interesting to keep for history purpose?
