### PR TITLE
[ML] Get ML filters size should default to 100

### LINKED ISSUE #54206: [ML] Get filters size defaults to 10 instead of 100
**Steps to reproduce**

1. Create 11 filters
2. Call the get filters API with no additional params

**Observed behaviour**

This should return all 11 filters that were created

**Actual behaviour**

Only 10 filters are returned.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
When get filters is called without setting the `size`
parameter only up to 10 filters are returned. However,
100 filters should be returned. This commit fixes this
and adds an integ test to guard it.

It seems this was accidentally broken in #39976.

Closes #54206

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/MlFiltersIT.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+import static org.hamcrest.Matchers.equalTo;
+
+public class MlFiltersIT extends MlNativeIntegTestCase {
+
+    @Override
+    protected void cleanUpResources() {
+        // nothing to clean
+    }
+
+    public void testGetFilters_ShouldReturnUpTo100ByDefault() {
```
Comment (benwtrent) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/MlFiltersIT.java]: #nit 
This seems like a very expensive test. Spinning up 3 nodes and native processes to make filter API calls. 

I suppose it is thorough. Might could move to our single node internal cluster tests at some point.

**Review by benwtrent — APPROVED** [review]

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/MlFiltersIT.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/MlFiltersIT.java]: Good point. I fixed it.
