### PR TITLE
Grok returns a list of matches for repeated pattern names #92092

### LINKED ISSUE #92092: Grok processor extracts only the first value if there are multiple matches
### Elasticsearch Version

7.17.6, 8.x

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Doesn't depend on the OS Version

### Problem Description

The Grok processor in the elasticsearch ingest pipelines does not extract multiple value that match a group but only the first one.

For example the following Grok expression:
```
^%{IPORHOST:source.address} (%{IPORHOST:source.address} )?
```

when given the following input:
```
"127.0.0.1 127.0.0.2"
```

It should match both values and not only the first one.

### Steps to Reproduce

```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "_description",
    "processors": [
      {
        "grok": {
          "field": "message",
          "patterns": [
            "^%{IPORHOST:source.address} (%{IPORHOST:source.address} )?"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "message": "82.10.222.126 192.168.10.1"
      }
    }
  ]
}
```

The `source.addresses` in the response is:
```
{
  "docs": [
    {
      "doc": {
        "_index": "index",
        "_id": "id",
        "_version": "-3",
        "_source": {
          "message": "82.10.222.126 192.168.10.1",
          "apache": {
            "access": {
              "user": {
                "identity": "jean"
              }
            }
          },
          "source": {
            "address": "82.10.222.126"
          }
        },
        "_ingest": {
          "timestamp": "2022-12-01T09:10:24.439912308Z"
        }
      }
    }
  ]
}
```

While the expected value of `source.address` is:
```
{
  "docs": [
    {
      "doc": {
        "_index": "index",
        "_id": "id",
        "_version": "-3",
        "_source": {
          "message": "82.10.222.126 192.168.10.1",
          "apache": {
            "access": {
              "user": {
                "identity": "jean"
              }
            }
          },
          "source": {
            "address": [
              "82.10.222.126",
              "192.168.10.1"
            ]
          }
        },
        "_ingest": {
          "timestamp": "2022-12-01T09:10:24.439912308Z"
        }
      }
    }
  ]
}

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by HiDAl**
This commit makes the Elasticsearch Grok processor behaves the same that Logstash's grok:

when Logstash's Grok processor runs with a pattern having repeated pattern names (e.g.: `"%{IP:ip} %{IP:ip} %{anything else}"`), it returns a list of matches, instead only the first match. 

Closes #92092

### CODE REVIEW

**Comment by HiDAl** [comment]
## Logstash example:
```
Logstash config:
input {
    file {
        path => "/Users/palcantar/workspace/ES-scripts/sample-log.log"
        start_position => "beginning"
        sincedb_path => "NUL"
        codec => json
    }
}

filter {
    grok {
        match => { "message" => "^%{IPORHOST:user.address} (%{IPORHOST:user.address} )?" }
    }
}

output {
    file { 
        path => "/Users/palcantar/workspace/ES-scripts/sample-out.log"
        codec => json 
    }
}

## OUTPUT
{
  "message": "81.12.23.34 ",
  "@version": "1",
  "event": {
    "original": "{\"message\": \"81.12.23.34 \"}"
  },
  "@timestamp": "2022-12-28T11:02:48.017377Z",
  "user.address": "81.12.23.34",
  "host": {
    "name": "Pablos-MBP.home"
  },
  "log": {
    "file": {
      "path": "/Users/palcantar/workspace/ES-scripts/sample-log.log"
    }
  }
}
{
  "message": "81.12.23.34 127.0.0.1",
  "@version": "1",
  "event": {
    "original": "{\"message\": \"81.12.23.34 127.0.0.1\"}"
  },
  "@timestamp": "2022-12-28T11:02:48.017670Z",
  "user.address": [
    "81.12.23.34",
    "127.0.0.1"
  ],
  "host": {
    "name": "Pablos-MBP.home"
  },
  "log": {
    "file": {
      "path": "/Users/palcantar/workspace/ES-scripts/sample-log.log"
    }
  }
}
{
  "message": "81.12.23.34 192.168.1.1 0.0.0.0",
  "@version": "1",
  "event": {
    "original": "{\"message\": \"81.12.23.34 192.168.1.1 0.0.0.0\"}"
  },
  "@timestamp": "2022-12-28T11:02:48.018653Z",
  "user.address": [
    "81.12.23.34",
    "192.168.1.1"
  ],
  "host": {
    "name": "Pablos-MBP.home"
  },
  "log": {
    "file": {
      "path": "/Users/palcantar/workspace/ES-scripts/sample-log.log"
    }
  }
}
```

## Local manual test
```
{
  "docs": [
    {
      "doc": {
        "_index": "index",
        "_id": "id",
        "_version": "-3",
        "_source": {
          "number": [
            "111",
            "222",
            "3",
            "32132",
            "hola"
          ],
          "message_str": "82.10.222.126 192.168.10.1 jean",
          "source": [
            "82.10.222.126",
            "192.168.10.1"
          ],
          "words_str": "one two three four five",
          "word": [
            "one",
            "two",
            "three",
            "four"
          ],
          "numbers_str": "111 hola 222 3 32132"
        },
        "_ingest": {
          "timestamp": "2022-12-28T09:48:40.30187Z"
        }
      }
    }
  ]
}

{
  "docs": [
    {
      "doc": {
        "_index": "index",
        "_id": "id",
        "_version": "-3",
        "_source": {
          "number": [
            "111",
            "222",
            "3",
            "32132",
            "hola"
          ],
          "message_str": "82.10.222.126 192.168.10.1 jean",
          "source": [
            "82.10.222.126",
            "192.168.10.1"
          ],
          "words_str": "one two three four five",
          "word": [
            "one",
            "two",
            "three",
            "four"
          ],
          "numbers_str": "111 hola 222 3 32132"
        },
        "_ingest": {
          "timestamp": "2022-12-28T09:48:40.30187Z"
        }
      }
    }
  ]
}
```

**Comment by HiDAl** [comment]
## Local manual test
```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "_description",
    "processors": [
      {
        "grok": {
          "field": "message_str",
          "patterns": [
            "^%{IPORHOST:source} (%{IPORHOST:source})?"
          ]
        }
      }
      ,
      {
        "grok": {
          "field": "words_str",
          "patterns": [
            "^%{WORD:word} (%{WORD:word})? (%{WORD:word})? (%{WORD:word})?"
          ]
        }
      },

      {
        "grok": {
          "field": "numbers_str",
          "patterns": [
            "^%{NUMBER:number} (%{WORD:number})? (%{NUMBER:number})? (%{NUMBER:number})? (%{NUMBER:number})?"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "message_str": "82.10.222.126 192.168.10.1 jean",
        "words_str": "one two three four five",
        "numbers_str": "111 hola 222 3 32132"
      }
    }
  ]
}

{
  "docs": [
    {
      "doc": {
        "_index": "index",
        "_id": "id",
        "_version": "-3",
        "_source": {
          "number": [
            "111",
            "222",
            "3",
            "32132",
            "hola"
          ],
          "message_str": "82.10.222.126 192.168.10.1 jean",
          "source": [
            "82.10.222.126",
            "192.168.10.1"
          ],
          "words_str": "one two three four five",
          "word": [
            "one",
            "two",
            "three",
            "four"
          ],
          "numbers_str": "111 hola 222 3 32132"
        },
        "_ingest": {
          "timestamp": "2022-12-28T09:48:40.30187Z"
        }
      }
    }
  ]
}
```

File: libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java [hunk 1]
```diff
@@ -26,14 +27,16 @@ public abstract class GrokCaptureExtracter {
      * is mutable and should be discarded after collecting a single result.
      */
     static class MapExtracter extends GrokCaptureExtracter {
-        private final Map<String, Object> result;
+        private final Map<String, List<Object>> result;
```
Comment (HiDAl) [inline libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:30]: I've decided to use this type of `Map` since otherwise, the code becomes a bit messy while extracting the elements

File: libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java [hunk 2]
```diff
@@ -26,14 +27,16 @@ public abstract class GrokCaptureExtracter {
...
         private final List<GrokCaptureExtracter> fieldExtracters;
 
         MapExtracter(List<GrokCaptureConfig> captureConfig) {
             result = captureConfig.isEmpty() ? emptyMap() : new HashMap<>();
             fieldExtracters = new ArrayList<>(captureConfig.size());
             for (GrokCaptureConfig config : captureConfig) {
-                fieldExtracters.add(config.objectExtracter(v -> result.put(config.name(), v)));
+                fieldExtracters.add(
+                    config.objectExtracter(value -> result.computeIfAbsent(config.name(), __ -> new ArrayList<>()).add(value))
```
Comment (joegallo) [inline libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:38]: Usually we used `ignored` rather than something like `__` for this.

**Comment by HiDAl** [comment]
@elasticsearchmachine update branch

**Comment by HiDAl** [comment]
@elasticmachine update branch

File: libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java (hunk 1 above)
Comment (gmarouli) [reply libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:30]: I see, do you think we could implement this maybe earlier in the process? In the emission of the values maybe? This is just an idea to discuss where it's better to implement this.

I am trying to consider also the performance a bit, adding it here adds a small penalty to every grok processor. I was hoping if we did it closer to the emission we could check if there are multiple entries and only use a list there.

Let me know what you think. I haven't worked  on the solution by the way, I am just sharing my thoughts on the subject and I think it might be worth a small effort to see if it's possible.

File: libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java [hunk 3]
```diff
@@ -45,7 +48,10 @@ void extract(byte[] utf8Bytes, int offset, Region region) {
         }
 
         Map<String, Object> result() {
-            return result;
+            return result.entrySet().stream().map(e -> {
+                // In case there's only 1 element, let's extract it from the list to be backward-compatible
```
Comment (gmarouli) [inline libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:52]: Great job capturing this.

File: libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java (hunk 1 above)
Comment (HiDAl) [reply libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:30]: This is the earlier stage where this can happen because within the `Grok` class we never traverse the list of (potential) captured groups. Thinking about the performance, I had an idea to avoid having to reserve memory in case a group is only being used once (-> do not have to create an ArrayList with 1 element). I'll the update the PR tomorrow

**Review by gmarouli — COMMENTED** [review]
So, I like very much that we relatively cheaply we calculate if we are encountering a multivalue or not. However we still create more objects in the form of the holders and we have the iteration over the map's values to extract the results.

I was wondering if we could use the `hasMultipleBackReferences` to decide if we will create a list or if we will just put the value in the map. A very rough version of it would be:

```
MapExtracter(List<GrokCaptureConfig> captureConfig) {
            result = captureConfig.isEmpty() ? emptyMap() : new HashMap<>();
            fieldExtracters = new ArrayList<>(captureConfig.size());
            for (GrokCaptureConfig config : captureConfig) {
                if (config.hasMultipleBackReferences()) {
                    fieldExtracters.add(config.objectExtracter(value -> {
                        if (result.containsKey(config.name()) == false) {
                           result.put(config.name(), new ArrayList<>());
                        }
                        if (result.get(config.name()) instanceof List) {
                            ((List<Object>) result.get(config.name())).add(value);
                        }
                    } ));
                } else {
                    fieldExtracters.add(config.objectExtracter(v -> result.put(config.name(), v)));
                }
            }
        }
```

I am curious about your thoughts on something like this.

**Comment by HiDAl** [comment]
@gmarouli You're right it's more optimal than the creation of intermediate holder objects and the code is still legible (what I was worried about mainly). I've applied the needed changes :) thanks for the feedback

**Comment by HiDAl** [comment]
@elasticmachine run elasticsearch-ci/part-3

File: libs/grok/src/main/java/org/elasticsearch/grok/MapExtracter.java [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+    @Override
+    public void extract(byte[] utf8Bytes, int offset, Region region) {
+        fieldExtracters.forEach(extracter -> extracter.extract(utf8Bytes, offset, region));
+    }
+
+    Map<String, Object> result() {
+        // Maintain compatibility with Logstash's Grok:
+        // Even though we could have a pattern with 2 or more groups with the same name (`%{NUMBER:name}%{WORD:name}%`) and only one
+        // match, logstash still flatten the result returning just 1 element.
+        return result.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> {
```
Comment (gmarouli) [inline libs/grok/src/main/java/org/elasticsearch/grok/MapExtracter.java:60]: Ah very good catch... I didn't think that even if it has multiple terms in the GROK expression it might not have matches!!

**Review by gmarouli — COMMENTED** [review]
One more suggestion, and that will be probably my last :). What do you think about instead of checking if the name has multiple back references, we check if it has multiple matches?

Do you think that would work? Something like (not pretty but you can see what I mean):
```
               if (result.containsKey(key)) {
                    if (result.get(key) instanceof List<?> list) {
                        ((ArrayList<Object>) list).add(value);
                    } else {
                        List<Object> list = new ArrayList<>();
                        list.add(result.get(key));
                        list.add(value);
                        result.put(key, list);
                    }
                } else {
                    result.put(key, value);
                }
```
One of my concerns is that this could only work if the value is not of type list, but I think that is indeed the case. (btw, what I am trying to do is to not check this during the result but prepare the result on the right format upon creation).

What are your thoughts?

**Comment by HiDAl** [comment]
@gmarouli I thought about this during lunch. We're synchronized :) will update the PR. Thanks!

**Comment by HiDAl** [comment]
@elasticmachine generate changelog

File: libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java [hunk 5]
```diff
@@ -20,34 +20,55 @@
...
  */
-public abstract class GrokCaptureExtracter {
+public interface GrokCaptureExtracter {
+
     /**
      * Extract {@link Map} results. This implementation of {@link GrokCaptureExtracter}
      * is mutable and should be discarded after collecting a single result.
      */
-    static class MapExtracter extends GrokCaptureExtracter {
+    class MapExtracter implements GrokCaptureExtracter {
```
Comment (gmarouli) [inline libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:29]: Nit: I was wondering why you extracted this. I have a preference on how it was before because it was very clear in the file structure that this `MapExtracter` is related to `GrokCaptureExtracter` but I am curious to hear your thoughts. My apologies for not mentioning it earlier.

Comment (gmarouli) [reply libs/grok/src/main/java/org/elasticsearch/grok/GrokCaptureExtracter.java:29]: Ignore.. you already fixed this...

File: libs/grok/src/test/java/org/elasticsearch/grok/GrokTests.java [hunk 6]
```diff
@@ -801,9 +801,15 @@ public void testMultipleNamedCapturesWithSameName() {
...
-        assertThat(grok.captures("12"), equalTo(expected));
+        assertThat(grok.captures("12"), equalTo(Map.of("num", List.of("1", "2"))));
+
+        grok = new Grok(bank, "%{SINGLEDIGIT:num:int}(%{SINGLEDIGIT:num:int})?", logger::warn);
+        assertCaptureConfig(grok, Map.of("num", INTEGER));
+        assertEquals(grok.captures("1"), Map.of("num", 1));
+        assertEquals(grok.captures("1a"), Map.of("num", 1));
+        assertEquals(grok.captures("a1"), Map.of("num", 1));
+        assertEquals(grok.captures("12"), Map.of("num", List.of(1, 2)));
+        assertEquals(grok.captures("123"), Map.of("num", List.of(1, 2)));
```
Comment (gmarouli) [inline libs/grok/src/test/java/org/elasticsearch/grok/GrokTests.java:812]: Kudos for the testing cases!

**Review by gmarouli — APPROVED** [review]
LGTM! Thank you for fixing this!

**Comment by HiDAl** [comment]
@elasticmachine generate changelog

**Comment by ishleenk17** [comment]
@HiDAl: In the above change, in case the values are duplicated ideally we should not add them to the list. 
Eg: In these [scenarios](https://github.com/elastic/integrations/issues/6016), which caused this issue.

Can we change this behaviour in ES, to drop the duplicated fields ?
