### PR TITLE
Don't test corruption detection within CFS checksum

### LINKED ISSUE #33881: [CI] IndexShardTests.testIndexCheckOnStartup failure
Reproduces reliably for me on `6.x` (but seems to be specific to this seed)
```
05:23:59   2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=714504A126B124F7 -Dtests.class=org.elasticsearch.index.shard.IndexShardTests -Dtests.method="testIndexCheckOnStartup" -Dtests.security.manager=true -Dtests.locale=es-NI -Dtests.timezone=Europe/Sofia -Dcompiler.java=10 -Druntime.java=8
05:23:59 Suite: org.elasticsearch.index.shard.IndexShardTests
```
```
05:23:59   1> [2018-09-20T08:23:51,459][INFO ][o.e.i.s.IndexShardTests  ] [testIndexCheckOnStartup] before test
05:23:59   1> [2018-09-20T08:23:51,604][INFO ][test                     ] [testIndexCheckOnStartup] Corrupting file --  flipping at position 2519 from ffffff8e to ffffff8f file: _0.cfs
05:23:59   1> [2018-09-20T08:23:51,605][INFO ][test                     ] [testIndexCheckOnStartup] Checksum before: [3342765594] after: [3342765594] checksum value after corruption: 3342765850] file: _0.cfs length: 2521
05:23:59   1> [2018-09-20T08:23:51,689][INFO ][o.e.i.s.IndexShardTests  ] [testIndexCheckOnStartup] after test
05:23:59 FAILURE 0.25s J3 | IndexShardTests.testIndexCheckOnStartup <<< FAILURES!
05:23:59    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IndexShardRecoveryException but no exception was thrown
05:23:59    > 	at __randomizedtesting.SeedInfo.seed([714504A126B124F7:70E3D1082C37E62F]:0)
05:23:59    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2693)
05:23:59    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2678)
05:23:59    > 	at org.elasticsearch.index.shard.IndexShardTests.testIndexCheckOnStartup(IndexShardTests.java:2673)
05:23:59    > 	at java.lang.Thread.run(Thread.java:748)
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/34/consoleFull

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**
It is known that Lucene does not check the tail of CFS file (CompoundFileS, like an archive) - see note at https://github.com/apache/lucene-solr/blob/60e8ee717d9cd8d2425c100c21168d6a43b78516/lucene/core/src/java/org/apache/lucene/codecs/lucene50/Lucene50CompoundReader.java#L82-L85

Therefore if we'd like Lucene checkIndex to detect corruption we should not corrupt checksum (last 4 bytes) of cfs file.

Closes #33881

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
With
```
./gradlew :server:test -Dtests.seed=714504A126B124F7 -Dtests.class=org.elasticsearch.index.shard.IndexShardTests -Dtests.method="testIndexCheckOnStartup"
```

and manual position adjustment:

CheckIndex does **not** detect corruption on flipping at position 2517..2520 on file: _0.cfs, length: 2521

CheckIndex **does** detect corruption on flipping at position 2516 file: _0.cfs, length: 2521

File: test/framework/src/main/java/org/elasticsearch/test/CorruptionUtils.java [hunk 1]
```diff
@@ -78,8 +78,19 @@ public static void corruptFile(Random random, Path... files) throws IOException
                 checksumBeforeCorruption = CodecUtil.retrieveChecksum(input);
             }
             try (FileChannel raf = FileChannel.open(fileToCorrupt, StandardOpenOption.READ, StandardOpenOption.WRITE)) {
+                long maxPosition = raf.size();
+
+                if (fileToCorrupt.getFileName().toString().endsWith(".cfs") && maxPosition > Integer.BYTES) {
+                    // TODO: it is known that Lucene does not check the tail of CFS file (CompoundFileS, like an archive), see note at
+                    // https://github.com/apache/lucene-solr/blob/branch_7_5/lucene/core/src/java/org/apache/lucene/codecs/lucene50/
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/CorruptionUtils.java]: Could you make this link into the following so that it doesn't rot as the code changes:

https://github.com/apache/lucene-solr/blob/60e8ee717d9cd8d2425c100c21168d6a43b78516/lucene/core/src/java/org/apache/lucene/codecs/lucene50/Lucene50CompoundReader.java#L82-L85

In fact it might be better to just put this link in the body of the first post of this PR, and make the code comment be a link to this PR, as it'll be much shorter.

File: test/framework/src/main/java/org/elasticsearch/test/CorruptionUtils.java [hunk 2]
```diff
@@ -78,8 +78,19 @@ public static void corruptFile(Random random, Path... files) throws IOException
...
+                    // Lucene50CompoundReader.java#L82
+                    // so far, don't corrupt checksum (last 4 bytes) of cfs file
+                    maxPosition -= Integer.BYTES;
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/CorruptionUtils.java]: This is a little confusing: the checksum is actually the last 8 bytes of the file, but the first 4 of those should be 0 (and we verify that). Could (a) the comment be more detailed and (b) the `Integer.BYTES` just say `4` to avoid this confusion?

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Good catch!

Could we have a test that fails if this issue is fixed in Lucene? Otherwise it could be fixed without anyone noticing and then we'd have a gap in our coverage.

I've run a few thousand iterations of these tests with this fix in place without finding an issue, but it also seems tricky to reproduce without the fix, so I'm keeping it running for a while.

File: test/framework/src/main/java/org/elasticsearch/test/CorruptionUtils.java (hunk 1 above)
Comment (vladimirdolzhenko) [reply test/framework/src/main/java/org/elasticsearch/test/CorruptionUtils.java]: updated link in PR description (it was pointed to a single line)

the problem with the link that it violates checkstyle 140 chars max per line, will add link to this PR as it way shorter 💯

**Comment by vladimirdolzhenko** [comment]
@elasticmachine test this please

**Comment by vladimirdolzhenko** [comment]
@elasticmachine test this please

**Review by DaveCTurner — APPROVED** [review]
LGTM, thanks. NB PR builds are not currently running so please wait until they're back up (and this PR has passed) before merging.

**Comment by vladimirdolzhenko** [comment]
@elasticmachine retest it please pleeeeeeeeeeeese

**Comment by vladimirdolzhenko** [comment]
@elasticmachine retest it please pleeeeeeeeeeeese

**Comment by DaveCTurner** [comment]
The magic words are "test this please" :)

**Comment by vladimirdolzhenko** [comment]
@elasticmachine test this please
