### PR TITLE
Fix Clone Snapshot State Machine Bug

### LINKED ISSUE #67871: Tripped Snapshot Consistency Assertion in o.e.s.CloneSnapshotIT.testBackToBackClonesForIndexNotInCluster
This only ever tripped once in https://gradle-enterprise.elastic.co/s/e4odu76ylem2w/tests/:server:internalClusterTest/org.elasticsearch.snapshots.CloneSnapshotIT/testBackToBackClonesForIndexNotInCluster#1

```
ene 25, 2021 12:20:27 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
ADVERTENCIA: Uncaught exception in thread: Thread[elasticsearch[node_t0][masterService#updateTask][T#1],5,TGRP-CloneSnapshotIT]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([5E79788A9EBA7C82]:0)
	at org.elasticsearch.snapshots.InFlightShardSnapshotStates.assertGenerationConsistency(InFlightShardSnapshotStates.java:107)
	at org.elasticsearch.snapshots.InFlightShardSnapshotStates.addStateInformation(InFlightShardSnapshotStates.java:79)
	at org.elasticsearch.snapshots.InFlightShardSnapshotStates.forRepo(InFlightShardSnapshotStates.java:63)
	at org.elasticsearch.cluster.SnapshotsInProgress.assertConsistentEntries(SnapshotsInProgress.java:780)
	at org.elasticsearch.cluster.SnapshotsInProgress.<init>(SnapshotsInProgress.java:809)
	at org.elasticsearch.cluster.SnapshotsInProgress.of(SnapshotsInProgress.java:804)
	at org.elasticsearch.snapshots.SnapshotsService$4.execute(SnapshotsService.java:671)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:391)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:59)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219)
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:684)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

came from 

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.CloneSnapshotIT.testBackToBackClonesForIndexNotInCluster" -Dtests.seed=5E79788A9EBA7C82 -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=Asia/Ulan_Bator -Druntime.java=8
```

but shows a serious bug. I'm on it.

### PR DESCRIPTION
**Pull request by original-brownbear**
This fixes a left over from #65042 where if a clone
was initially put in the cluster state before another clone
but then initialized after the other clone already finished its shard clones,
a broken snapshot state would be reached where the first clone
would be queued before the almost finished clone.

closes #67871

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java [hunk 1]
```diff
@@ -247,6 +251,15 @@ public void setFailReadsAfterUnblock(boolean failReadsAfterUnblock) {
         this.failReadsAfterUnblock = failReadsAfterUnblock;
     }
 
+    /**
+     * Enable blocking a single read of {@link org.elasticsearch.snapshots.SnapshotInfo} in case the repo is already blocked on another
+     * file. This allows testing very specific timing issues where a read of {@code SnapshotInfo} is much slower than another concurrent
+     * repository operation.
+     */
+    public void setBlockOnceOnReadSnapshotInfoIfAlreadyBlocked() {
```
Comment (original-brownbear) [inline test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java:259]: This is admittedly pretty :facepalm: but we don't have a clean way of expressing just a one-time block here. The dependency on another block is due to how the `blockExecution` loop works (doesn't play well with one-time actions).

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -491,32 +491,24 @@ public ClusterState execute(ClusterState currentState) {
...
-                            // repository, so in order to make sure we don't set a shard to QUEUED before (as in before it in the
-                            // `updatedEntries` list) one that is actively executing we just put it to the back of the list as if we had
-                            // just created the entry
-                            // TODO: If we could eventually drop the snapshot clone init phase we don't need this any longer
-                            updatedEntries.remove(i);
-                            updatedEntries.add(updatedEntry);
-                        } else {
-                            updatedEntries.set(i, updatedEntry);
-                        }
+                        // Move the now ready to execute clone operation to the back of the snapshot operations order because its
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:507]: This broke because for `SUCCESS` state shards we would not queue up the shard clone (rightfully so) but would still have the `SUCCESS` state clone that is just about to finalize after the current clone, tripping assertions (and without them leading to stuck clone operations).
Should have never had the `queuedShards` condition here, it just creates all kinds of trouble to not simply move

**Comment by original-brownbear** [comment]
This is pretty close to a ">blocker" I think as it can lead to a stuck snapshot state machine (though it's not a new issue and cloning is still very rarely used I suppose). We can discuss this tomorrow.

File: test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java (hunk 1 above)
Comment (fcofdez) [reply test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java:259]: Could you add a reference to `MockRepository#blockExecution` in the javadoc? It took me a bit to understand how the dependency on another block was enforced.

**Review by fcofdez — APPROVED** [review]
LGTM 👍

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2  ( some Jenkins issue it seems the build just died)

**Comment by original-brownbear** [comment]
Thanks Francisco!
