### PR TITLE
Reduce global checkpoint sync interval in disruption tests

### LINKED ISSUE #36789: [CI] ClusterDisruptionIT.testAckedIndexing fails with global checkpoints sync mismatch
Even though there is [another issue](https://github.com/elastic/elasticsearch/issues/36042) where this exact test fails, I think this is a new one, as the assertion is thrown in `ESIntegTestCase.cleanUpCluster()`  - so not sure if related. This did not reproduce locally for me even after a hundred test runs.

Build at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/678/console

```
   > Throwable #1: java.lang.AssertionError: [test][0], node[9dhUaSxHQdamimAnmokazg], [R], s[STARTED], a[id=fn0K4Pw6RFC7hVING
OFrsw] global checkpoint syncs mismatch
   > Expected: <2L>
   >      but: was <5L>
   >    at __randomizedtesting.SeedInfo.seed([28739239BF9765D1:A2B226CAE3EA839A]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.InternalTestCluster.lambda$assertSeqNos$9(InternalTestCluster.java:1330)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
   >    at org.elasticsearch.test.InternalTestCluster.assertSeqNos(InternalTestCluster.java:1295)
   >    at org.elasticsearch.discovery.AbstractDisruptionTestCase.beforeIndexDeletion(AbstractDisruptionTestCase.java:104)
   >    at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:585)
   >    at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2199)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.AssertionError: [test][0], node[9dhUaSxHQdamimAnmokazg], [R], s[STARTED], a[id=fn0K4Pw6RFC7hVIN
GOFrsw] global checkpoint syncs mismatch
   > Expected: <2L>
   >      but: was <5L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.test.InternalTestCluster.lambda$assertSeqNos$9(InternalTestCluster.java:1330)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   >            ... 39 more
   >    Suppressed: java.lang.AssertionError: [test][0], node[9dhUaSxHQdamimAnmokazg], [R], s[STARTED], a[id=fn0K4Pw6RFC7hVIN
GOFrsw] global checkpoint syncs mismatch
   > Expected: <2L>
   >      but: was <5L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.test.InternalTestCluster.lambda$assertSeqNos$9(InternalTestCluster.java:1330)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   >            ... 39 more
   >    Suppressed: java.lang.AssertionError: [test][0], node[9dhUaSxHQdamimAnmokazg], [R], s[STARTED], a[id=fn0K4Pw6RFC7hVIN
GOFrsw] global checkpoint syncs mismatch

```

### LINKED ISSUE #38318: [CI] ClusterDisruptionIT#testAckedIndexing failure on 6.6
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+periodic/281/console

Reproduce
```
./gradlew :server:integTest \
  -Dtests.seed=28EA74D48DC5F83F \
  -Dtests.class=org.elasticsearch.discovery.ClusterDisruptionIT \
  -Dtests.method="testAckedIndexing" \
  -Dtests.security.manager=true \
  -Dtests.locale=zh-SG \
  -Dtests.timezone=Asia/Almaty \
  -Dcompiler.java=11 \
  -Druntime.java=8
```
I kept this running in a loop for about 15 repetiotions locally before I got the first failure. Looks like this then:
```
   > Throwable #1: java.lang.AssertionError: [test][1], node[L-28xZP7Q0WyfVS1JrcTHA], [R], s[STARTED], a[id=EX57TRsNTX-vc3tfmteydQ] seq_no_stats mismatch
   > Expected: <SeqNoStats{maxSeqNo=4, localCheckpoint=4, globalCheckpoint=4}>
   >      but: was <SeqNoStats{maxSeqNo=4, localCheckpoint=4, globalCheckpoint=1}>
   >    at __randomizedtesting.SeedInfo.seed([28EA74D48DC5F83F:A22BC027D1B81E74]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.InternalTestCluster.lambda$assertSeqNos$8(InternalTestCluster.java:1328)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
   >    at org.elasticsearch.test.InternalTestCluster.assertSeqNos(InternalTestCluster.java:1298)
   >    at org.elasticsearch.discovery.AbstractDisruptionTestCase.beforeIndexDeletion(AbstractDisruptionTestCase.java:104)
   >    at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:585)
   >    at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2199)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.AssertionError: [test][1], node[L-28xZP7Q0WyfVS1JrcTHA], [R], s[STARTED], a[id=EX57TRsNTX-vc3tfmteydQ] seq_no_stats mismatch
   > Expected: <SeqNoStats{maxSeqNo=4, localCheckpoint=4, globalCheckpoint=4}>
   >      but: was <SeqNoStats{maxSeqNo=4, localCheckpoint=4, globalCheckpoint=1}>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.test.InternalTestCluster.lambda$assertSeqNos$8(InternalTestCluster.java:1328)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   >            ... 40 more
```

This is also what I see in the build logs.

### PR DESCRIPTION
**Pull request by dnhatn**
We verify seq_no_stats is aligned between copies at the end of some disruption tests. Sometimes, the assertion `assertSeqNos` is tripped due to a lagged global checkpoint on replicas. This happens because the global checkpoint is synced 30 seconds (by default) after the last replication operation. This change reduces the global checkpoint sync-internal to 1s in the disruption tests.

Closes #38318
Closes #36789

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM!

File: server/src/test/java/org/elasticsearch/recovery/RelocationIT.java [hunk 1]
```diff
@@ -110,6 +110,13 @@ protected void beforeIndexDeletion() throws Exception {
         internalCluster().assertSameDocIdsOnShards();
     }
 
+    @Override
+    public Settings indexSettings() {
+        return Settings.builder().put(super.indexSettings())
+            // sync global checkpoint quickly so we can verify seq_no_stats aligned between all copies after tests.
+            .put(IndexService.GLOBAL_CHECKPOINT_SYNC_INTERVAL_SETTING.getKey(), "1s").build();
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/recovery/RelocationIT.java]: some tests in this class explicitly set this to `100ms`. Is that not needed anymore now?

**Review by ywelsch — APPROVED** [review]

**Comment by dnhatn** [comment]
Thanks @jasontedor @ywelsch!
