### PR TITLE
Unique names for bulk processor scheduler threads

### LINKED ISSUE #68470: BulkProcessor creates multiple scheduler threads with identical names
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2 (and others)

**Plugins installed**: N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:

`BulkProcessor#builder(BiConsumer, Listener)` constructs two scheduler threads, both called `[node-name][scheduler][T#1]`, which is also the name of the node's main scheduler thread. This is confusing, it would be preferable if these threads all had different names.

**Steps to reproduce**:

Do something that involves the ILM history store, which uses `BulkProcessor#builder(BiConsumer, Listener)`,  and then take a thread dump of the node.

**Provide logs (if relevant)**:

Not relevant.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today every `BulkProcessor` creates two scheduler threads, both called
`[node-name][scheduler][T#1]`, which is also the name of the main
scheduler thread for the node. The duplicated thread names make it
harder to interpret a thread dump.

This commit makes the names of these threads distinct.

Closes #68470

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java [hunk 1]
```diff
@@ -213,20 +216,21 @@ public static Builder builder(Client client, Listener listener) {
     /**
      * @param consumer The consumer that is called to fulfil bulk operations
      * @param listener The BulkProcessor listener that gets called on bulk events
+     * @param name     The name of this processor, e.g. to identify the scheduler threads
      * @return the builder for BulkProcessor
      */
-    public static Builder builder(BiConsumer<BulkRequest, ActionListener<BulkResponse>> consumer, Listener listener) {
+    public static Builder builder(BiConsumer<BulkRequest, ActionListener<BulkResponse>> consumer, Listener listener, String name) {
```
Comment (jakelandis) [inline server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java:222]: since this class is the [documented approach](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-document-bulk.html#java-rest-high-document-bulk-processor) for clients ingestion, can we preserve binary compatibility here ? (i.e. preserve the original method signature and pass an empty/hard-coded string)

**Review by jakelandis — APPROVED** [review]
LGTM. As mentioned in the comment, I would prefer to preserve java compatibility for the builder method, otherwise looks good. 

(and sorry it took so long to review, this one slipped through the cracks)

File: server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java:233]: Acked, yes, I added the original method back and marked it deprecated so we can remove it at a later date, see 92ea717.
