### PR TITLE
ES|QL StatementParser LIMIT BY tests in snapshot builds only

### LINKED ISSUE #144268: [CI] StatementParserTests testLimitByQualifiedName failing
**Build Scans:**
- [elasticsearch-periodic #11997 / release-tests](https://gradle-enterprise.elastic.co/s/6g65zzn7fvoow)
- [elasticsearch-periodic #11997 / release-tests](https://gradle-enterprise.elastic.co/s/zp3hogdsw433i)
- [elasticsearch-periodic-java-ea #205 / release-tests](https://gradle-enterprise.elastic.co/s/76b2jktqkpeju)
- [elasticsearch-periodic #11993 / release-tests](https://gradle-enterprise.elastic.co/s/z24n3txveub6q)
- [elasticsearch-periodic #11993 / release-tests](https://gradle-enterprise.elastic.co/s/vzmbyqxnwhi3g)
- [elasticsearch-periodic-java-ea #204 / release-tests](https://gradle-enterprise.elastic.co/s/nufsvk5g2r5es)
- [elasticsearch-pull-request #128314 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/4edazc6bx6jpy)
- [elasticsearch-periodic-java-ea #204 / release-tests](https://gradle-enterprise.elastic.co/s/7cnupfxtgk3mq)
- [elasticsearch-pull-request #128213 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/alvy4c5zmjtns)
- [elasticsearch-pull-request #128169 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/afgnln7s5gds6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.parser.StatementParserTests.testLimitBy" -Dtests.seed=99377731EF349EAE -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ky-KG -Dtests.timezone=America/Coyhaique -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.parser.StatementParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testLimitByQualifiedName'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.parser.ParsingException: line 3:16: no viable alternative at input 'BY'
```

**Issue Reasons:**
- [main] 7 consecutive failures in step release-tests
- [main] 4 consecutive failures in step checkpart3_release-tests
- [main] 11 failures in test testLimitByQualifiedName (3.8% fail rate in 293 executions)
- [main] 7 failures in step release-tests (100.0% fail rate in 7 executions)
- [main] 4 failures in step checkpart3_release-tests (100.0% fail rate in 4 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.8% fail rate in 170 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-java-ea (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by tteofili**
Checks ES|QL statement tests for Limit By only run in snapshot builds.

Fixes https://github.com/elastic/elasticsearch/issues/144268 and https://github.com/elastic/elasticsearch/issues/144267

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 1]
```diff
@@ -1087,6 +1087,7 @@ public void testBasicLimitCommand() {
     }
 
     public void testLimitBy() {
+        assumeTrue("LIMIT BY requires snapshot builds", new EsqlConfig(TEST_FUNCTION_REGISTRY).isDevVersion());
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: we actually need a dedicated capability - in https://github.com/elastic/elasticsearch/pull/144102/ where the initial change is made, there's no esql capability we can reuse.
I think we can just add one `LIMIT_BY(Build.current().isSnapshot())` in EsqlCapabilities.

Comment (tteofili) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java]: thanks @ioanatia, I've added the capability in https://github.com/elastic/elasticsearch/pull/144310/commits/08940a3468aa02b9763982dbce5725552061a0c8. 
but if you prefer to have a separate for that, just LMK.

**Review by ioanatia — APPROVED** [review]

**Review by ncordon — APPROVED** [review]
Thanks for fixing this 🤗
