### PR TITLE
Delay searchable snapshot allocation during shutdown

### LINKED ISSUE #85052: Shards are relocated while node is restarted and shutdown API has been called
### Elasticsearch Version

7.17.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

ECK running on GKE 1.22.7-gke.900

### Problem Description

Shards are relocated between nodes in the cold tier while they are restarting, despite the fact that the [shutdown API](https://www.elastic.co/guide/en/elasticsearch/reference/current/put-shutdown.html#put-shutdown-api-request-body) is called with the type `restart`.

It has been first reported by an ECK user [here](https://github.com/elastic/cloud-on-k8s/issues/5464):
> I see the managed Elasticsearch cluster try to reallocate 350+ searchable snapshots from the restart of a cold node.

I also managed to reproduce it consistently:

1. See a first report [here](https://gist.github.com/barkbay/ef1c7b516bf93534d216bfa48827b70d), full logs from the master node are [here](https://gist.githubusercontent.com/barkbay/0f25a9588755a8eb06bea0a70ec6a1a7/raw/bfe10bf910ac2ae0ffab07454395fd4d694e0cc1/master-0.ndjson).

2. I also reproduced the problem while `logger.org.elasticsearch.cluster.routing.allocation.decider` was set to true `TRACE`,  logs are available [here](https://gist.githubusercontent.com/barkbay/0f25a9588755a8eb06bea0a70ec6a1a7/raw/bfe10bf910ac2ae0ffab07454395fd4d694e0cc1/master-0.traces.ndjson). While the node `elasticsearch-gcs-sample-es-cold-2` is restarted, shard `restored-.ds-metricbeat-8.0.0-2022.03.16-000003` has been relocated to `elasticsearch-gcs-sample-es-cold-1`.

It does not seem to happen for other tiers (not sure about the frozen though).

### Steps to Reproduce

1. Deploy a cluster with a cold tier, shards being backed by a snapshot. Without replica.
2. Call the shutdown API with the `restart` type on a node in the cold tier
3. Monitor the shards location
4. Restart the node
5. Shards are being relocated

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by henningandersen**
During a shutdown, searchable snapshots should not be re-allocated to new nodes,
since this leads to data download. Instead, now wait for the shutdown reallocation
delay before reallocating shards.

Fixes #85052

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotAllocator.java [hunk 1]
```diff
@@ -341,11 +342,26 @@ private AllocateUnassignedDecision decideAllocation(RoutingAllocation allocation
...
             }
+        } else if (isDelayedDueToShutdown(allocation, shardRouting)) {
+            return ReplicaShardAllocator.delayedDecision(shardRouting, allocation, logger, nodeDecisions);
         }
+
         // TODO: do we need handling of delayed allocation for leaving replicas here?
         return AllocateUnassignedDecision.NOT_TAKEN;
     }
 
+    private boolean isDelayedDueToShutdown(RoutingAllocation allocation, ShardRouting shardRouting) {
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotAllocator.java:353]:
```suggestion
    private boolean isDelayedDueToNodeRestart(RoutingAllocation allocation, ShardRouting shardRouting) {
```

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+                            .cluster()
+                            .health(Requests.clusterHealthRequest(restoredIndexName))
+                            .actionGet();
+                        assertThat(response.getUnassignedShards(), Matchers.equalTo(shards));
+                    });
+                    return super.onNodeStopped(nodeName);
+                }
+            });
+            // leave shutdown in place for some nodes to check that shards get assigned anyway.
+            if (randomBoolean()) {
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java:82]: I wonder if this can cause some test failures when a low number of data nodes is picked up? I quickly tested with a 10 shards index and 2 data nodes and got a failure after ~5 runs.

**Review by tlrx — COMMENTED** [review]
This looks good but I suspect that the test will cause failures on CI

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+import java.util.Locale;
+import java.util.Map;
+import java.util.Set;
+import java.util.concurrent.ExecutionException;
+import java.util.stream.Collectors;
+import java.util.stream.StreamSupport;
+
+import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
+
+@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, minNumDataNodes = 2, numDataNodes = 2)
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java:41]:
```suggestion
@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, minNumDataNodes = 2)
```

**Review by tlrx — APPROVED** [review]
LGTM - I left some minor comments.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotAllocator.java (hunk 1 above)
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotAllocator.java]: Forgot this in prior round, done now in df9115a0833a8344c9a1c38927b0029b10a2d896

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java (hunk 3 above)
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java]: :thu:, leftover from some testing, done in 263b644ec66c3e1fff7031bf255e3c3904c51d52

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+        }
+
+        ensureGreen(restoredIndexNamesArray);
+    }
+
+    private List<String> setupMountedIndices() throws Exception {
+        int count = between(1, 10);
+        List<String> restoredIndices = new ArrayList<>();
+        for (int i = 0; i < count; ++i) {
+            final String indexName = randomAlphaOfLength(10).toLowerCase(Locale.ROOT);
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java]: :+1: , see 9db957e6cc136ebef03d4c5920723ae158bf2851, also now just does one repo.

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+            createAndPopulateIndex(indexName, Settings.builder());
+
+            final String repositoryName = randomAlphaOfLength(10).toLowerCase(Locale.ROOT);
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java]: Changed to one repo in 9db957e6cc136ebef03d4c5920723ae158bf2851

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+        );
+        assertTrue(client().execute(PutShutdownNodeAction.INSTANCE, putShutdownRequest).get().isAcknowledged());
+    }
+
+    private void removeShutdown(String node) throws ExecutionException, InterruptedException {
+        assertTrue(client().execute(DeleteShutdownNodeAction.INSTANCE, new DeleteShutdownNodeAction.Request(node)).get().isAcknowledged());
+    }
+
+    @Override
+    protected int numberOfShards() {
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotShutdownIntegTests.java]: :+1: , see 9db957e6cc136ebef03d4c5920723ae158bf2851
