### PR TITLE
Fix GeoDistance Ordinal for BWC

### LINKED ISSUE #24816: Document backwards-incompatible change for GeoDistance queries (5.3 breaking change/incompatibility)
When running a 5.2.2 client against a 5.3 or 5.4 server, when GeoDistance queries with default settings are sent, the server responds with an error:

Caused by: java.io.IOException: Unknown GeoDistance ordinal [3]

This regression was introduced in 5.3 and on in this commit:

https://github.com/elastic/elasticsearch/commit/3a2c628fabe2b30545cd16afc9227542b24bfcfe

That commit changed the ordinals of the Enums in a backwards-incompatible way.

This should be documented in the breaking changes for 5.3. This also breaks the promise of 5.x clients being able to talk to 5.x servers compatibly (note that the 5.2.2 client is not using any new features here).

### PR DESCRIPTION
**Pull request by nknize**
`GeoDistance` enum ordinals from 5.3+ are not backwards compatible with earlier client versions.. This PR adds backward compatibilty support in `GeoDistance` serialization.

closes #24816

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java [hunk 1]
```diff
@@ -40,7 +41,26 @@
...
+                case 2: return ARC;
+                case 3:
+                    // bwc client deprecation for SLOPPY_ARC
+                    DEPRECATION_LOGGER.deprecated("[sloppy_arc] is deprecated. Using [arc] instead.");
+                    return ARC;
+                default:
+                    throw new IOException("Unknown GeoDistance ordinal [" + ord + "]");
+            }
+        }
+
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java]: Can you also fix the write side so that if the client is on 5.4 while the cluster is on 5.3 then things would still work?

**Review by jpountz — CHANGES_REQUESTED** [review]
The change looks good but I think we need to fix the write side too.

File: core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java [hunk 2]
```diff
@@ -40,7 +41,26 @@
 
     /** Creates a GeoDistance instance from an input stream */
     public static GeoDistance readFromStream(StreamInput in) throws IOException {
+        Version clientVersion = in.getVersion();
         int ord = in.readVInt();
+        // bwc client deprecation for FACTOR and SLOPPY_ARC
+        if (clientVersion.before(Version.V_5_3_3)) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java]: we should update version labels on #19846?

File: core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java (hunk 1 above)
Comment (nknize) [inline core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java]: absolutely! Good catch @jpountz made the fix.

File: core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java [hunk 3]
```diff
@@ -50,6 +70,20 @@ public static GeoDistance readFromStream(StreamInput in) throws IOException {
     /** Writes an instance of a GeoDistance object to an output stream */
     @Override
     public void writeTo(StreamOutput out) throws IOException {
+        Version clientVersion = out.getVersion();
+        int ord = this.ordinal();
+        if (clientVersion.before(Version.V_5_3_3)) {
+            switch (ord) {
+                case 0:
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java]: can you add a comment saying it is the ordinal of `PLANE`

File: core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java [hunk 4]
```diff
@@ -50,6 +70,20 @@ public static GeoDistance readFromStream(StreamInput in) throws IOException {
...
+                    out.write(0);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java]: same here

File: core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java [hunk 5]
```diff
@@ -50,6 +70,20 @@ public static GeoDistance readFromStream(StreamInput in) throws IOException {
...
+                    return;
+                case 1:
+                    out.write(2);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/geo/GeoDistance.java]: can you comment those are the ordinals of `ARC` in both cases?

File: core/src/test/java/org/elasticsearch/common/geo/GeoDistanceTests.java [hunk 6]
```diff
@@ -67,6 +70,25 @@ public void testInvalidReadFrom() throws Exception {
...
+                GeoDistance copy = GeoDistance.readFromStream(in);
+                assertThat(copy, isOneOf(GeoDistance.PLANE, GeoDistance.ARC));
+                if (ordinal == 1) {
+                    assertWarnings("[factor] is deprecated. Using [plane] instead.");
+                } else if (ordinal == 3) {
+                    assertWarnings("[sloppy_arc] is deprecated. Using [arc] instead.");
+                }
+            }
+        }
+    }
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/common/geo/GeoDistanceTests.java]: quickly test writeTo too?

**Review by jpountz — APPROVED** [review]
Looks good, can you just add the comments and test I mentioned before merging?
