### PR TITLE
Fix RestartIndexFollowingIT.testFollowIndex in case of fatal exception

### LINKED ISSUE #90666: [CI] RestartIndexFollowingIT testFollowIndex failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/3ia43d647stqy/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex

**Reproduction line:**
`gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.testFollowIndex" -Dtests.seed=88838658B243966D -Dtests.locale=en-AU -Dtests.timezone=Israel -Druntime.java=18`

**Applicable branches:**
main, 8.5

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ccr.RestartIndexFollowingIT&tests.test=testFollowIndex

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <411L>
     but: was <370L>

  at __randomizedtesting.SeedInfo.seed([88838658B243966D:6BEF496A8BFBAFE7]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.lambda$testFollowIndex$1(RestartIndexFollowingIT.java:96)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1105)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1078)
  at org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.testFollowIndex(RestartIndexFollowingIT.java:95)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by tlrx**
This test failed several times after the leader cluster is fully restarted for the second time. The logs indicate that one or more `ShardFollowNodeTask` (the persistent task in charge or replication operations for a shard) have been stopped because a fatal exception occured. 

The fatal exception is an `IllegalStateException` with the `Unable to open any connections to remote cluster` message. I think this is due to the leader cluster being slow to restart and the remote cluster sniff strategy giving up after it tried to connect to the leader cluster nodes.

<details>

```java
 1> [2022-10-09T12:09:14,066][WARN ][o.e.x.c.a.ShardFollowNodeTask] [follower0] shard follow task encounter non-retryable error
  1> java.lang.IllegalStateException: Unable to open any connections to remote cluster [leader_cluster]
  1> 	at org.elasticsearch.transport.SniffConnectionStrategy$SniffClusterStateResponseHandler.handleNodes(SniffConnectionStrategy.java:408) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.SniffConnectionStrategy$SniffClusterStateResponseHandler$1.onFailure(SniffConnectionStrategy.java:390) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:38) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:92) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListenerDirectly(ListenableFuture.java:115) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:100) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.BaseFuture.setException(BaseFuture.java:149) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.onFailure(ListenableFuture.java:147) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.ClusterConnectionManager.failConnectionListener(ClusterConnectionManager.java:385) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.ClusterConnectionManager.lambda$connectToNodeOrRetry$7(ClusterConnectionManager.java:262) ~[elasticsearch-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
```
</details>

Since this exception is fatal, the `ShardFollowNodeTask` stopped to replicate all operations and the test fails waiting for the number of docs to match on leader and follower clusters:

```java
REPRODUCE WITH: gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.testFollowIndex" -Dtests.seed=BEB30D9C209D0820 -Dtests.locale=es-MX -Dtests.timezone=Pacific/Norfolk -Druntime.java=18
  2> java.lang.AssertionError: 
    Expected: <205L>
         but: was <190L>
        at __randomizedtesting.SeedInfo.seed([BEB30D9C209D0820:5DDFC2AE192531AA]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.lambda$testFollowIndex$1(RestartIndexFollowingIT.java:96)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1105)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1078)
        at org.elasticsearch.xpack.ccr.RestartIndexFollowingIT.testFollowIndex(RestartIndexFollowingIT.java:95)
```

The documented way to resolve CCR fatal exceptions for follower is to recreate the follower. This is what I choose to do to adjust the test here.

Closes #90666

### CODE REVIEW

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java [hunk 1]
```diff
@@ -151,4 +160,16 @@ private void cleanRemoteCluster() throws Exception {
             assertThat(infos.size(), equalTo(0));
         });
     }
+
+    private boolean hasFollowTaskWithFatalException(String indexName) {
```
Comment (DaveCTurner) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java:164]: I'd prefer a more precise name here, we're only checking for the specific case of a disconnected cluster.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java [hunk 2]
```diff
@@ -87,16 +92,20 @@ public void testFollowIndex() throws Exception {
...
 
-        assertBusy(
-            () -> assertThat(
-                followerClient().prepareSearch("index2").get().getHits().getTotalHits().value,
-                equalTo(firstBatchNumDocs + secondBatchNumDocs + thirdBatchNumDocs)
-            )
-        );
+        var totalDocs = firstBatchNumDocs + secondBatchNumDocs + thirdBatchNumDocs;
+        assertBusy(() -> {
+            if (hasFollowTaskWithFatalException("index2")) {
```
Comment (DaveCTurner) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java:102]: I think we don't need this in the `assertBusy()`, we should only have to reconnect at most once after `fullRestart()` has returned.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java [hunk 3]
```diff
@@ -87,16 +92,20 @@ public void testFollowIndex() throws Exception {
...
+                logger.info("follower has encountered a fatal exception, recreating");
+                assertAcked(followerClient().admin().indices().prepareDelete("index2"));
+                followerClient().execute(PutFollowAction.INSTANCE, putFollow("index1", "index2", ActiveShardCount.ALL)).get();
```
Comment (DaveCTurner) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java:105]: Could we pause and unpause the follower instead? Maybe randomly choose between the two

**Review by DaveCTurner — COMMENTED** [review]
Makes sense, I left some suggestions.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java (hunk 3 above)
Comment (tlrx) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java:111]: I think we can, yes, it should recreate the task and ensure the remote cluster is connected. I randomized the two since recreating is what is documented today.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java (hunk 1 above)
Comment (tlrx) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java]: I renamed to `isFollowerStoppedBecauseOfRemoteClusterDisconnection` but I'm not sure it is much better 😬

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
> The documented way to resolve CCR fatal exceptions for follower is to recreate the follower.

The docs seem a little inconsistent, or at least not totally clear. There's these docs about handling the follower falling too far behind:

https://github.com/elastic/elasticsearch/blob/08515eac09ca549036c963df5670ca0956aaa047/docs/reference/ccr/managing.asciidoc#L69-L73

But then there's these which say resuming should be enough to resolve a fatal error:

https://github.com/elastic/elasticsearch/blob/08515eac09ca549036c963df5670ca0956aaa047/docs/reference/ccr/apis/follow/get-follow-stats.asciidoc?plain=1#L70-L73

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java (hunk 2 above)
Comment (tlrx) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java]: Ok, I pushed 1a481fa95dff2b0807842952d9e55092b3bfe311, let me know if that's what you have in mind.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java [hunk 4]
```diff
@@ -87,16 +94,41 @@ public void testFollowIndex() throws Exception {
...
+                                followerClient().execute(PutFollowAction.INSTANCE, putFollow("index1", "index2", ActiveShardCount.ALL))
+                                    .actionGet();
+                            }
+                        } catch (AssertionError e2) {
+                            e.addSuppressed(e2);
+                        }
+                    }
+                }
+                throw e;
+            }
```
[the remark this answers is not in the document]
Comment (tlrx) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/RestartIndexFollowingIT.java]: Much better, I stole it, thanks

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
Thanks a lot David. I'll open a follow up for the doc.
