### PR TITLE
ESQL: Fix alias removal in regex extraction with `JOIN`

### LINKED ISSUE #127467: ES|QL: pruning of JOINs leads to missing fields
Probably related to https://github.com/elastic/elasticsearch/issues/126017, but the symptoms are different:

With CSV dataset:

```
from books,message_*,ul* 
| enrich languages_policy on status 
| drop `language_name`, `bytes_out`, `id`, id 
| dissect book_no "%{type}" 
| dissect author.keyword "%{HZicfARaID}" 
| mv_expand `status` 
| sort HZicfARaID, year DESC NULLS LAST, publisher DESC NULLS FIRST, description DESC, type NULLS LAST, message ASC NULLS LAST, title NULLS FIRST, status NULLS LAST 
| enrich languages_policy on book_no 
| grok message "%{WORD:DiLNyZKNDu}" 
| limit 7972
| rename year as language_code 
| lookup join languages_lookup on language_code 
| limit 13966 
| stats  rcyIZnSOb = min(language_code), `ratings` = min(@timestamp), dgDxwMeFYrD = count(`@timestamp`), ifyZfXigqVN = count(*), qTXdrzSpY = min(language_code) by author.keyword
| rename author.keyword as message 
| lookup join message_types_lookup on message 
| stats  `ratings` = count(*) by type 
| stats  `type` = count(type), `ratings` = count(*) 
| keep `ratings`, ratings	
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "verification_exception",
                "reason": "Found 1 problem\nline 1:832: Unknown column [type]"
            }
        ],
        "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:832: Unknown column [type]"
    },
    "status": 400
}
```

### PR DESCRIPTION
**Pull request by kanoshiou**
Because we aim to minimize the number of attributes required from `field_caps` at pre-analysis time, a removal check helps eliminate fields defined by users (such as `eval`). However, this removal logic does not apply to `ReferenceAttribute` produced by regex extraction commands `grok` and `dissect`, even though these fields are also user-defined.

Closes #127467

### CODE REVIEW

**Comment by astefan** [comment]
buildkite test this

**Review by astefan — CHANGES_REQUESTED** [review]
The solution is not optimal. Maybe it fixes the problem, but the `canRemoveAliases` references in multiple places makes the code hard to follow and reason about.

Instead, look at [the code that is tied to `lookup join` and `enrich` ](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java#L657-L674) where, after seeing this issue with `dissect`, it is clear that this code - `p.forEachExpressionDown(Alias.class, alias -> {` shouldn't only apply to `Alias` (which comes from `eval` commands), but also to whatever comes out from `dissect` (meaning, any user-defined columns).

Rather than using `canRemoveAliases[0]` in `RegexExtract` check, look into adjusting the code I mentioned above.

**Comment by kanoshiou** [comment]
Thank you for your review and detailed guidance @astefan! Your keen eye for code goes far beyond mine, I still have a long journey ahead in learning and improving.

I've updated the branch, please feel free to review it again at your convenience. If there are any further adjustments needed, I'm more than happy to make them.

**Comment by astefan** [comment]
buildkite test this

**Comment by astefan** [comment]
buildkite test this

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 1]
```diff
@@ -661,15 +659,21 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
                 // remove any already discovered UnresolvedAttributes that are in fact aliases defined later down in the tree
                 // for example "from test | eval x = salary | stats max = max(x) by gender"
                 // remove the UnresolvedAttribute "x", since that is an Alias defined in "eval"
+                // also remove other down-the-tree references to the extracted fields from "grok" and "dissect"
                 AttributeSet planRefs = p.references();
                 Set<String> fieldNames = planRefs.names();
-                p.forEachExpressionDown(Alias.class, alias -> {
+                p.forEachExpressionDown(NamedExpression.class, expression -> {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:665]: Just a naming preference towards `NamedExpression` - `ne` that's used in other places in code.
```suggestion
                p.forEachExpressionDown(NamedExpression.class, ne-> {
```

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 2]
```diff
@@ -1650,3 +1650,69 @@ event_duration:long
 2764889
 3450233
 ;
+
+
+joinMaskingRegex
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:1655]: I am not a big fan of having such test queries here. At least, add a comment with the link to the original bug report.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 3]
```diff
@@ -1650,3 +1650,69 @@ event_duration:long
...
+;
+
+ratings:long
+1
+;
+
+joinMaskingDissect
+required_capability: join_lookup_v12
+required_capability: fix_join_masking_regex_extract
+from sample_data
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:1687]: Add this test and the one below in IndexResolverFieldNamesTests as well.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 4]
```diff
@@ -661,15 +659,21 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
...
+                    }
                     // do not remove the UnresolvedAttribute that has the same name as its alias, ie "rename id AS id"
                     // or the UnresolvedAttributes that are used in Functions that have aliases "STATS id = MAX(id)"
-                    if (fieldNames.contains(alias.name())) {
+                    if (fieldNames.contains(expression.name())) {
                         return;
                     }
-                    referencesBuilder.removeIf(attr -> matchByName(attr, alias.name(), keepCommandRefsBuilder.contains(attr)));
+                    referencesBuilder.removeIf(
+                        attr -> matchByName(attr, expression.name(), (expression instanceof Alias) && keepCommandRefsBuilder.contains(attr))
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:675]: Why this check here? `(expression instanceof Alias)`

Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:675]: I didn't give it much thought since `skipIfPattern` was set to` false` for `RegexExtract`. After considering it briefly, I think removing this check wouldn't hurt too much.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec (hunk 3 above)
Comment (astefan) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:1689]: I think you missed this request here.

**Review by astefan — COMMENTED** [review]
@kanoshiou, please address all reviews.

**Comment by astefan** [comment]
buildkite test this

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec (hunk 3 above)
Comment (kanoshiou) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:1689]: Oh, sorry! I misunderstood what you meant. I was actually thinking about adding comments of links to the original issue.

Comment (kanoshiou) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:1689]: Added in [d56383b](https://github.com/elastic/elasticsearch/pull/127687/commits/d56383b4f10bf4030becff6c29c5ce84518358ca)

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 5]
```diff
@@ -1042,6 +1042,12 @@ public enum Cap {
          */
         DROP_AGAIN_WITH_WILDCARD_AFTER_EVAL,
 
+        /**
+         * During resolution (pre-analysis) we have to consider that joins can override regex extracted values
+         * see <a href="https://github.com/elastic/elasticsearch/issues/127467"> ES|QL: pruning of JOINs leads to missing fields #127467 </a>
+         */
+        FIX_JOIN_MASKING_REGEX_EXTRACT,
+
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:1050]: Please, add this capability at the end of the list of capabilities. It will be slightly easier for me to manually backport the PR, if the automatic backport fails.

**Comment by astefan** [comment]
When you get the chance, please integrate new changes from `main` and I'll start a new CI round of tests. Thank you.

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
Thank you @astefan!
