### PR TITLE
Fix: ILMDownsampleDisruptionIT.testILMDownsampleRollingRestart

### LINKED ISSUE #136585: [CI] ILMDownsampleDisruptionIT testILMDownsampleRollingRestart failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11230 / almalinux-8-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/orvciwoqmi2ma)
- [elasticsearch-pull-request #99182 / part-2](https://gradle-enterprise.elastic.co/s/pd73hytrz34yg)
- [elasticsearch-pull-request #99113 / part-2](https://gradle-enterprise.elastic.co/s/sxk3jv5vdwz3e)
- [elasticsearch-pull-request #99003 / part-2](https://gradle-enterprise.elastic.co/s/kuend2slyn5le)
- [elasticsearch-pull-request #98995 / part-2](https://gradle-enterprise.elastic.co/s/ejfpvf6cwp3v4)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:downsample:internalClusterTest" --tests "org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT.testILMDownsampleRollingRestart" -Dtests.seed=30E0CBFB781FCAF4 -Dtests.locale=es-ES -Dtests.timezone=Etc/GMT-5 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.downsample.ILMDownsampleDisruptionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testILMDownsampleRollingRestart'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Shard [downsample-1h-xncwqbcsbt][0] is still locked after 5 sec waiting
```

**Issue Reasons:**
- [main] 5 failures in test testILMDownsampleRollingRestart (2.2% fail rate in 230 executions)
- [main] 4 failures in step part-2 (3.3% fail rate in 120 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (3.3% fail rate in 120 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by gmarouli**
This PR stabilises `testILMDownsampleRollingRestart` and closes #136585. 

This test started failing more often after https://github.com/elastic/elasticsearch/pull/135834 because this change increased the chance of manifesting https://github.com/elastic/elasticsearch/issues/137422.

To reduce this chance we wait for ILM to finish the phase before we end the test.

Closes #136585

### CODE REVIEW

**Review by nielsbauman — APPROVED** [review]
Thanks a lot for the investigation, Mary!!

And sorry that this ended up being ILM/Data Management after all...

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java [hunk 1]
```diff
@@ -172,6 +173,18 @@ public void testILMDownsampleRollingRestart() throws Exception {
         startDownsampleTaskViaIlm(sourceIndex, targetIndex);
         assertBusy(() -> assertTargetIndex(cluster, targetIndex, indexedDocs));
         ensureGreen(targetIndex);
+        // We assert that ILM to successfully completed the phase
+        assertBusy(() -> {
```
Comment (DaveCTurner) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java]: Could we do this with `ClusterServiceUtils#addTemporaryStateListener` rather than polling any API? We can check the API response afterwards ofc but every `assertBusy` adds a little extra idle time to tests and in total that's a pretty big contributor to overall test runtime.

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java [hunk 2]
```diff
@@ -172,6 +173,14 @@ public void testILMDownsampleRollingRestart() throws Exception {
         startDownsampleTaskViaIlm(sourceIndex, targetIndex);
         assertBusy(() -> assertTargetIndex(cluster, targetIndex, indexedDocs));
         ensureGreen(targetIndex);
+        // We assert that ILM successfully completed the phase
+        logger.info("Waiting for ILM to complete the phase for index [{}]", targetIndex);
+        ClusterServiceUtils.addTemporaryStateListener(clusterState -> {
+            IndexMetadata indexMetadata = getIndexMetadataByIndexName(clusterState, targetIndex);
```
Comment (nielsbauman) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java]: Integration tests don't need to be project-aware yet, as we don't have any way of making them work with different projects.


```suggestion
            IndexMetadata indexMetadata = clusterState.metadata().getProject().index(targetIndex);
```

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java [hunk 3]
```diff
@@ -173,18 +173,14 @@ public void testILMDownsampleRollingRestart() throws Exception {
...
-                    new ExplainLifecycleRequest(TimeValue.THIRTY_SECONDS).indices(targetIndex)
-                )
-            );
-            IndexLifecycleExplainResponse ilmExplain = explainLifecycleResponse.getIndexResponses().get(targetIndex);
-            assertThat(ilmExplain, notNullValue());
-            assertThat(ilmExplain.getStep(), equalTo(PhaseCompleteStep.NAME));
-        }, 60, TimeUnit.SECONDS);
+        // We assert that ILM successfully completed the phase
+        logger.info("Waiting for ILM to complete the phase for index [{}]", targetIndex);
+        ClusterServiceUtils.addTemporaryStateListener(clusterState -> {
```
Comment (DaveCTurner) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java]: This just adds (and returns) the listener - you have to `safeAwait` on it too :)

Comment (gmarouli) [reply x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java]: _face palm....._

Comment (nielsbauman) [reply x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java]: You could also use `awaitClusterState` instead :)

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java [hunk 4]
```diff
@@ -172,6 +169,13 @@ public void testILMDownsampleRollingRestart() throws Exception {
         startDownsampleTaskViaIlm(sourceIndex, targetIndex);
         assertBusy(() -> assertTargetIndex(cluster, targetIndex, indexedDocs));
         ensureGreen(targetIndex);
+        // We assert that ILM successfully completed the phase
```
Comment (DaveCTurner) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java]: nit

```suggestion
        // We wait for ILM to successfully complete the phase
```

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java [hunk 5]
```diff
@@ -172,6 +169,13 @@ public void testILMDownsampleRollingRestart() throws Exception {
...
+        logger.info("Waiting for ILM to complete the phase for index [{}]", targetIndex);
+        awaitClusterState(clusterState -> {
```
Comment (DaveCTurner) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java:174]: Ohh yes I'd completely forgotten we had an `awaitClusterState` to do this 👍

**Review by DaveCTurner — APPROVED** [review]
LGTM

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java (hunk 5 above)
Comment (gmarouli) [reply x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java:174]: Me too, credits to @nielsbauman

Comment (DaveCTurner) [reply x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/ILMDownsampleDisruptionIT.java:174]: I have less of an excuse tho 😇 

```
$ git annotate -- test/framework/src/main/java/org/elasticsearch/test/ClusterServiceUtils.java | grep awaitClusterState
1337476bc9efc	(David Turner	2025-08-26 12:54:45 +0100	241)    public static void awaitClusterState(Predicate<ClusterState> statePredicate, ClusterService clusterService) {
```
