### PR TITLE
Fix spurious failures in AsyncSearchIntegTestCase

### LINKED ISSUE #55895: AsyncSearchActionIT can fail during 'after test' checks
The `AsyncSearchActionIT` test doesn't always pass the checks in `TestCluster#assertAfterTest`. 

Build scan: https://gradle-enterprise.elastic.co/s/byylhh2vpytkq
Example reproduce line:
```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testUpdateRunningKeepAlive" -Dtests.seed=43B6F15A7AB86387 -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Mexico/BajaNorte -Dcompiler.java=14 -Druntime.java=11
```

The failure doesn't reproduce consistently.

Excerpt from logs:

```
  2> java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_sd1, are there still Lucene indices around?
    Expected: <0L>
         but: was <1222L>
        at __randomizedtesting.SeedInfo.seed([43B6F15A7AB86387:152B3C508C1EE026]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$37(InternalTestCluster.java:2199)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:865)
        at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2197)
        at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:90)
```

### LINKED ISSUE #55988: [CI] AsyncSearchActionIT failing with assertion error
Had a build on `7.7` branch fail with a number of tests from this suite with the following message. This seems to be the first of its kind but I thought I'd write this up since there's been a lot of work being done around this area. This didn't reproduce locally for me, perhaps Windows related?

```
org.elasticsearch.xpack.search.AsyncSearchActionIT > testRestartAfterCompletion FAILED
    java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
        at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
        at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$8(ESTestCase.java:532)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:917)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:890)
        at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:532)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.RuntimeException: [adoEdDSDTjWhheNvODX9pA][.async-search][0]scroll=[5m] query=[expiration_time:[-9223372036854775808 TO 1588201780463]]
            at org.elasticsearch.search.MockSearchService.addActiveContext(MockSearchService.java:60)
            at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:78)
            at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:635)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:428)
            at org.elasticsearch.search.SearchService.access$200(SearchService.java:135)
            at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395)
            at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:411)
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            ... 1 more

    java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
        at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
        at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$8(ESTestCase.java:532)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:917)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:890)
        at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:532)
        at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:382)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.RuntimeException: [adoEdDSDTjWhheNvODX9pA][.async-search][0]scroll=[5m] query=[expiration_time:[-9223372036854775808 TO 1588201780463]]
            at org.elasticsearch.search.MockSearchService.addActiveContext(MockSearchService.java:60)
            at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:78)
            at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:635)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:428)
            at org.elasticsearch.search.SearchService.access$200(SearchService.java:135)
            at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395)
            at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:411)
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            ... 1 more
REPRODUCE WITH: gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRestartAfterCompletion" -Dtests.seed=398B1AC9099AB198 -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Africa/Kigali -Dcompiler.java=14 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by jimczi**
Async search integration tests are subject to random failures when:
  * The test index has more than one replica.
  * The request cache is used.
  * Some shards are empty.
  * The maintenance service starts a garbage collection when node is closing.

They are also slow because the test index is created/populated on each
test method.

This change refactors these integration tests in order to:
  * Create the index once for the entire test suite.
  * Fix the usage of the request cache and replicas.
  * Ensures that all shards have at least one document.
  * Increase the delay of the maintenance service garbage collection.

Closes #55895
Closes #55988

### CODE REVIEW

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java [hunk 1]
```diff
@@ -115,4 +119,51 @@ protected int doHashCode() {
     public String getWriteableName() {
         return NAME;
     }
+
+    static class QueryLatch implements Closeable {
+        private volatile CountDownLatch countDownLatch;
+        private Set<Integer> failedShards = new HashSet<>();
```
Comment (javanna) [inline x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:125]: this could be final

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java [hunk 2]
```diff
@@ -115,4 +119,51 @@ protected int doHashCode() {
     public String getWriteableName() {
         return NAME;
     }
+
+    static class QueryLatch implements Closeable {
```
Comment (javanna) [inline x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:123]: I would try to document what this class does and how to use it. I will try with my words but correct me if I am wrong: BlockingQueryBuilder blocks on each shard, until the next set of results is requested through reacquireBlock. Also failures are sent back based on the provided number of failures.

I would also consider renaming tryBlock and reacquireBlock to reflect what they are used for.

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java [hunk 3]
```diff
@@ -115,4 +119,51 @@ protected int doHashCode() {
...
+
+        private void tryBlock(int shardId) throws IOException, InterruptedException {
+            CountDownLatch last = countDownLatch;
+            if (last != null) {
+                last.await();
+            }
+            synchronized (this) {
+                if (failedShards.contains(shardId)) {
+                    throw new IOException("boom");
+                } else if (numShardFailures > 0) {
```
Comment (javanna) [inline x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:141]: can you add a small comment to explain that we have the scenario where the same shard id appears multiple times due to replicas and we want to count that as one failure?

Comment (javanna) [reply x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:141]: also could this block be replaced with the following?

```
if (failedShards.add(shardId)) {
    numShardFailures--;
}
throw new IOException("boom");
```

and the set could be some concurrent impl so that we can remove the synchronized block?

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/AsyncSearchIntegTestCase.java [hunk 4]
```diff
@@ -148,40 +169,25 @@ protected void ensureTaskCompletion(String id) throws Exception {
     }
 
     protected SearchResponseIterator assertBlockingIterator(String indexName,
```
Comment (javanna) [inline x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/AsyncSearchIntegTestCase.java:171]: could you add a quick comment explaining what this iterator allows to do?

**Review by javanna — APPROVED** [review]
left a couple of comments, LGTM otherwise

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java (hunk 3 above)
Comment (jimczi) [reply x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:150]: I added a comment in https://github.com/elastic/elasticsearch/pull/56026/commits/0304ec6b3b521e2ebe47c40a9c064797203bc021. We could avoid the synchronized block but it feels easier to read and it's not a critical path ?

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/AsyncSearchIntegTestCase.java (hunk 4 above)
Comment (jimczi) [reply x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/AsyncSearchIntegTestCase.java:176]: I pushed https://github.com/elastic/elasticsearch/pull/56026/commits/0304ec6b3b521e2ebe47c40a9c064797203bc021

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java (hunk 2 above)
Comment (jimczi) [reply x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:131]: I pushed https://github.com/elastic/elasticsearch/pull/56026/commits/0304ec6b3b521e2ebe47c40a9c064797203bc021

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java (hunk 3 above)
Comment (javanna) [reply x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/BlockingQueryBuilder.java:150]: I don't mind the synchronized. On readability, it's debatable I guess, I personally find the `if` based on the `add` result more readable. Up to you.
