### PR TITLE
Fix testCloseOrDeleteIndexDuringSnapshot

### LINKED ISSUE #39828: [CI] SharedClusterSnapshotRestoreIT testCloseOrDeleteIndexDuringSnapshot failed
`org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT testCloseOrDeleteIndexDuringSnapshot` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/60/console

The REPRO command was:

```
./gradlew :server:integTest \
  -Dtests.seed=BBE286746EB2E3EC \
  -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT \
  -Dtests.method="testCloseOrDeleteIndexDuringSnapshot" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-CH \
  -Dtests.timezone=America/Ojinaga \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

This didn't reproduce locally for me.

The exception was:

```
FAILURE 2.98s J1 | SharedClusterSnapshotRestoreIT.testCloseOrDeleteIndexDuringSnapshot <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <SUCCESS>
   >      but: was <PARTIAL>
   > 	at __randomizedtesting.SeedInfo.seed([BBE286746EB2E3EC:A0CB08C85FC687F8]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testCloseOrDeleteIndexDuringSnapshot(SharedClusterSnapshotRestoreIT.java:2529)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* This test was resulting in a `PARTIAL` instead of a `SUCCESS` state for
the case of closing an index during snapshotting on 7.x
  * The reason for this is the changed default behavior regarding
waiting for active shards between 8.0 and 7.x
  * Fixed by adjusting the waiting behavior on the close index request
in the test so that the primary is guaranteed to become active and we don't run into a shard snapshot failure due to a missing primary
* Closes #39828

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 1]
```diff
@@ -2483,7 +2483,7 @@ public void testCloseOrDeleteIndexDuringSnapshot() throws Exception {
                 } else {
                     logger.info("--> close index while partial snapshot is running");
                     closedOnPartial = true;
-                    client.admin().indices().prepareClose("test-idx-1").get();
+                    client.admin().indices().prepareClose("test-idx-1").setWaitForActiveShards(ActiveShardCount.DEFAULT).get();
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: I don't understand how this helps, because JavaDoc for `setWaitForActiveShards` claims that `ActiveShardCount.DEFAULT` is the default value, so the change should introduce no difference in the behaviour

Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: On `7.x` the default is `NONE` https://github.com/elastic/elasticsearch/blob/7.x/server/src/main/java/org/elasticsearch/action/admin/indices/close/CloseIndexRequest.java#L43 in `master` it's `DEFAULT`.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
thanks @ywelsch !
