### PR TITLE
Exclude all but string fields from highlighting if wildcards are used…

### LINKED ISSUE #17537: Invalid shift value (xx) in prefixCoded bytes (is encoded value really a geo point?)
Hi guys,

we have upgraded ElasticSearch from 2.3.0 and reindexed our geolocations so the latitude and longitude are stored separately. We have noticed that some of our visualisation started to fail after we add a filter based on geolocation rectangle. However, map visualisation are working just fine. The problem occurs when we include actual documents. In this case, we get some failed shards (usually 1 out of 5) and error: Invalid shift value (xx) in prefixCoded bytes (is encoded value really a geo point?).

Details:
Our geolocation index is based on:

    "dynamic_templates": [{
    ....
    {
            "ner_geo": {
              "mapping": {
                "type": "geo_point",
                "lat_lon": true
              },
              "path_match": "*.coordinates"
            }
          }],

The ok query with the error is as follows. If we change the query size to 0 (map visualizations example), the query completes without problem.

    {
      "size": 100,
      "aggs": {
        "2": {
          "geohash_grid": {
            "field": "authors.affiliation.coordinates",
            "precision": 2
          }
        }
      },
      "query": {
        "filtered": {
          "query": {
            "query_string": {
              "analyze_wildcard": true,
              "query": "*"
            }
          },
          "filter": {
            "bool": {
              "must": [
                {
                  "geo_bounding_box": {
                    "authors.affiliation.coordinates": {
                      "top_left": {
                        "lat": 61.10078883158897,
                        "lon": -170.15625
                      },
                      "bottom_right": {
                        "lat": -64.92354174306496,
                        "lon": 118.47656249999999
                      }
                    }
                  }
                }
              ],
              "must_not": []
            }
          }
        }
      },
      "highlight": {
        "pre_tags": [
          "@kibana-highlighted-field@"
        ],
        "post_tags": [
          "@/kibana-highlighted-field@"
        ],
        "fields": {
          "*": {}
        },
        "require_field_match": false,
        "fragment_size": 2147483647
      }
    }

Elasticsearch version**: 2.3.0
OS version**: Elasticsearch docker image with head plugin, marvel and big desk installed

Thank you for your help,
regards,
Jakub Smid

### PR DESCRIPTION
**Pull request by brwe**
… in fieldname

We should prevent highlighting if a field is anything but a text or keyword field.
However, someone might implement a custom field type that has text and still want to
highlight on that. We cannot know in advance if the highlighter will be able to
highlight such a field and so we do the following:
If the field is only highlighted because the field matches a wildcard we assume
it was a mistake and do not process it.
If the field was explicitly given we assume that whoever issued the query knew
what they were doing and try to highlight anyway.

closes #17537

Note that with this pr if a user adds the full name of a `geo_point` field to the highlight part of the request they will still get the exception seen in  #17537.

Another option would be to list all the fields that we know we cannot highlight and exclude them in the HighlightPhase. But then someone with a custom mapper might run into issues when using wildcards in the highlight request.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java [hunk 1]
```diff
@@ -102,6 +104,20 @@ public void hitExecute(SearchContext context, HitContext hitContext) {
                     continue;
                 }
 
+                // We should prevent highlighting if a field is anything but a text or keyword field.
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java]: the comment says text or keyword but the code tests text or string?

Comment (brwe) [inline core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java]: That is a bug. I wanted to make that keyword or text. I pushed a commit.

Comment (clintongormley) [inline core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java]: @brwe Note that in 5.x we can have text, keyword AND string fields

File: core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java [hunk 2]
```diff
@@ -102,6 +105,20 @@ public void hitExecute(SearchContext context, HitContext hitContext) {
...
+                // However, someone might implement a custom field type that has text and still want to
+                // highlight on that. We cannot know in advance if the highlighter will be able to
+                // highlight such a field and so we do the following:
+                // If the field is only highlighted because the field matches a wildcard we assume
+                // it was a mistake and do not process it.
+                // If the field was explicitly given we assume that whoever issued the query knew
+                // what they were doing and try to highlight anyway.
+                if (fieldNameContainsWildcards) {
+                    if (fieldMapper.fieldType().typeName().equals(TextFieldMapper.CONTENT_TYPE) == false && fieldMapper.fieldType().typeName().equals
+                        (KeywordFieldMapper.CONTENT_TYPE) == false) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java]: like Clint said, we should allow string fields too (which will continue to exist on 2.x indices)

File: core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java (hunk 1 above)
Comment (brwe) [inline core/src/main/java/org/elasticsearch/search/highlight/HighlightPhase.java]: Indeed. I got confused with the options and versions. I pushed another commit.

File: docs/reference/search/request/highlighting.asciidoc [hunk 3]
```diff
@@ -35,7 +35,9 @@ be used for highlighting if it mapped to have `store` set to `true`.
 ==================================
 
 The field name supports wildcard notation. For example, using `comment_*`
-will cause all fields that match the expression to be highlighted.
+will cause all <<text,text>> or <<keyword,keyword>> fields that match the expression to be highlighted.
```
Comment (jpountz) [inline docs/reference/search/request/highlighting.asciidoc]: this says text or keyword but the code seems to be doing text or string

**Comment by jpountz** [comment]
LGTM

**Comment by clintongormley** [comment]
@brwe this is merged into 2.3, correct? please could you also merge to 2.x

**Comment by brwe** [comment]
@clintongormley 2.x commit is here: https://github.com/elastic/elasticsearch/commit/968d3a0d561b0c77575de3feaf7b6ec207b548fc and 2.3 here:https://github.com/elastic/elasticsearch/commit/635b0e9db9bcbd5fce7722a85f4ef4decf448e23

**Comment by clintongormley** [comment]
thanks @brwe - i've added the appropriate version labels

**Comment by rodgermoore** [comment]
I'm still running into issue https://github.com/elastic/elasticsearch/issues/17537 after updating to 2.3.3.

**Comment by benzitohhh** [comment]
Highlighting no longer works for Lucene-style wilcard queries within a function-score.

This was working ok in v2.3.4, but is not working since v2.4.0

For example, previously the below was returning highlights ok. Now it still returns results, but without any highlights:
```
{
    "highlight": {
        "fields": {
          "name": {}
        }
    },
  
    "query": {
        "function_score": {
            "script_score": {
                "script": "(1 + 5 * log(1 + doc['size_active'].value) )"
            },

            "query": {
                "query_string": {
                    "fields": [
                        "name"
                    ],
                    "query": "microsof*"
                }
            }

        }
    }
}
```

The same query without the wildcard works returns highlights for all hits:
```
{
    "highlight": {
        "fields": {
          "name": {}
        }
    },
  
    "query": {
        "function_score": {
            "script_score": {
                "script": "(1 + 5 * log(1 + doc['size_active'].value) )"
            },

            "query": {
                "query_string": {
                    "fields": [
                        "name"
                    ],
                    "query": "microsoft"
                }
            }

        }
    }
}
```
