### PR TITLE
Load FieldInfos from store if not yet initialised through a refresh on IndexShard

### LINKED ISSUE #125483: [Field_caps] field_caps request don't return fields for indices with readonly_state when include_empty_fields=false
### Elasticsearch Version

9.0rc1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macOS 15.3.2

### Problem Description

When requesting **field_stats** using the param **include_empty_fields** set to **false** targeting an index in readonly state, the only fields returned are `_tier`, `_index`, `_index_mode`.  There should be much more fields being returned, attaching a screenshot showing the problem with migrated indices from 7.18 -> 9.0rc1:

Image

Originally reported by @jughosta 

### Steps to Reproduce

* Set an Elasticsearch index to readonly
* Target the index with a `field_caps` request with the parameter `include_empty_fields=false`
* The returned resultset just returns a few meta fields

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by original-brownbear**
Load field caps from store if they haven't been initialised through a refresh yet.
Keep the plain reads to not mess with performance characteristics too much on the good path but protect against confusing races when loading field infos now (that probably should have been ordered stores in the first place but this was safe due to other locks/volatiles on the refresh path).

Closes #125483

### CODE REVIEW

**Review by piergm — APPROVED** [review]
LGTM! Thanks @original-brownbear for working on this :D

**Review by andreidan — APPROVED** [review]
LGTM too :) Thanks for fixing this Armin

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -4266,16 +4281,21 @@ public void beforeRefresh() {}
...
+                FIELD_INFOS.setRelease(IndexShard.this, loadFieldInfos());
             }
         }
     }
 
+    private FieldInfos loadFieldInfos() {
+        try (Engine.Searcher hasValueSearcher = getEngine().acquireSearcher("field_has_value")) {
+            return FieldInfos.getMergedFieldInfos(hasValueSearcher.getIndexReader());
+        } catch (AlreadyClosedException ignore) {
+            // engine is closed - no update to3 FieldInfos is fine
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: lol right and in the process of fixing grammar/typo no less 🤣 thanks!

**Comment by original-brownbear** [comment]
Thanks you two!

**Comment by javanna** [comment]
Thanks for fixing @original-brownbear I believe it makes sense to backport this to 8.18 as well.

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsSearchIntegTests.java [hunk 2]
```diff
@@ -125,5 +126,9 @@ public void testKeywordSortedQueryOnFrozen() throws Exception {
             assertThat(searchResponse.getTotalShards(), equalTo(20));
             assertThat(searchResponse.getHits().getTotalHits().value(), equalTo(4L));
         });
+
+        // check that field_caps empty field filtering works as well
+        FieldCapabilitiesResponse response = client().prepareFieldCaps(mountedIndices).setFields("*").setincludeEmptyFields(false).get();
+        assertNotNull(response.getField("keyword"));
```
Comment (javanna) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsSearchIntegTests.java:132]: I wonder if it makes sense to add the same test to the N-2 indices related tests for indices that are imported as verified read-only. We know the fix addresses the same issue for them too, but it'd be safer to have a specific test for them? These tests are under `qa/lucene-index-compatibility` .

Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsSearchIntegTests.java:132]: ++ definitely. Let me try something, maybe I can get the full field caps suite running for searchable snapshots and there somehow, would be really nice to have coverage across all the implementations that play tricks on the engine :)
