### PR TITLE
Check docs limit before indexing on primary

### LINKED ISSUE #51136: Exceeding the maximum doc count of a shard fails the shard
Today (7.5.0) if we try and index a document into a shard that already contains 2147483519 documents then it is rejected by Lucene and a no-op is written to the translog to record this. However, since #30226 we also try and record no-ops themselves as documents in Lucene; the index is already full so we fail to add the tombstone too. The failure to add this tombstone is fatal to the shard:

```
[2020-01-17T09:20:02,405][WARN ][o.e.i.c.IndicesClusterStateService] [node-0] [i][0] marking and sending shard failed due to [shard failure, reason [no-op origin[PRIMARY] seq#[2147483519] failed at document level]]
java.lang.IllegalArgumentException: number of documents in the index cannot exceed 2147483519
        at org.apache.lucene.index.DocumentsWriterPerThread.reserveOneDoc(DocumentsWriterPerThread.java:225) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:495) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1594) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.elasticsearch.index.engine.InternalEngine.innerNoOp(InternalEngine.java:1533) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:937) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:796) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:768) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:725) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:258) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:161) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:193) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:118) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:79) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:917) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:108) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:394) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:316) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$21(IndexShard.java:2752) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:113) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:285) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:237) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2726) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:858) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:312) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:275) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) ~[?:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:315) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:752) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) ~[elasticsearch-7.5.0.jar:7.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.5.0.jar:7.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

However, we immediately restart the shard:

```
[2020-01-17T09:20:02,408][INFO ][o.e.c.r.a.AllocationService] [node-0] Cluster health status changed from [GREEN] to [RED] (reason: [shards failed [[i][0]]]).
[2020-01-17T09:20:02,963][INFO ][o.e.c.r.a.AllocationService] [node-0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[i][0]]]).
```

I _think_ this is ok - the operation fails before it makes it to the translog so there's nothing to replay - but it would be good to confirm that there's no risk we do something bad (e.g. leak a seqno) here.

### PR DESCRIPTION
**Pull request by dnhatn**
Today indexing to a shard with 2147483519 documents will fail that shard. We should check the number of documents and reject the write requests instead.

Closes #51136

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -176,6 +176,16 @@
...
     private final AtomicBoolean shouldPeriodicallyFlushAfterBigMerge = new AtomicBoolean(false);
 
+    /**
+     * If multiple writes passed {@link InternalEngine#testReserveDocs(Operation, int)} (int)} but haven't adjusted
+     * {@link IndexWriter#getPendingNumDocs()} yet, then IndexWriter can fail with too many documents. In this case,
+     * we have to fail the engine because we already generated sequence numbers for write operations; otherwise we
+     * will have gaps in sequence numbers. To avoid this (best-effort), we use a lower limit when trying to reserve
+     * documents in InternalEngine.
+     */
+    static final int DEFAULT_MAX_DOCS = IndexWriter.MAX_DOCS - 1000;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:186]: I'm wondering why we use a margin of 1000 docs here. IIUC the index writer will only under-count the total by at most one doc per write thread?

OTOH if there is more severe under-counting under concurrent load then is 1000 enough?

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+    public void testMaxDocsLimit() throws Exception {
+        final int maxDocs = TestEnginePlugin.maxDocs;
+        IndexWriterMaxDocsChanger.setMaxDocs(maxDocs);
+        try {
+            internalCluster().ensureAtLeastNumDataNodes(1);
+            assertAcked(client().admin().indices().prepareCreate("test")
+                .setSettings(Settings.builder().put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, 1)
+                    .put(IndexSettings.INDEX_TRANSLOG_DURABILITY_SETTING.getKey(), Translog.Durability.REQUEST)));
+            int numDocs = randomIntBetween(maxDocs + 1, maxDocs * 2);
+            for (int i = 0; i < numDocs; i++) {
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java:78]: Could we run this test (or a similar one) with concurrent indexing too, to demonstrate that we only exceed the limit by a bounded amount?

**Review by DaveCTurner — COMMENTED** [review]
Thanks @dnhatn, this is great. I left a couple of minor questions.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:186]: > IIUC the index writer will only under-count the total by at most one doc per write thread?

Yes, but IW can under-count more than one with nested documents.

> OTOH if there is more severe under-counting under concurrent load then is 1000 enough?

I think 1000 is enough because all writes should execute using the WRITE thread pool, which has no more threads than the number of cores. Do you have a suggestion for this?

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java (hunk 2 above)
Comment (dnhatn) [reply server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java:78]: ++, I will add a new test.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:186]: Ah darn it yes, nested docs strike again. In which case I don't think 1000 is enough for all users. Can we instead acquire a proper reservation for the right number of docs in `testReserveDocs` (e.g. using a `Semaphore`) and then release them once they're tracked by the `IndexWriter`?

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java (hunk 2 above)
Comment (dnhatn) [reply server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java]: added in https://github.com/elastic/elasticsearch/pull/63273/commits/efa8145303e98c3a1b9f4886691a5cfbd5c548b4.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Adjusted in https://github.com/elastic/elasticsearch/pull/63273/commits/efa8145303e98c3a1b9f4886691a5cfbd5c548b4

**Comment by dnhatn** [comment]
@DaveCTurner Thanks for looking. I've addressed your comments.

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java [hunk 3]
```diff
@@ -0,0 +1,212 @@
...
+        IndexWriterMaxDocsChanger.restoreMaxDocs();
+    }
+
+    public static void assertNoOutstandingReservingDocs() throws Exception {
+        assertBusy(() -> {
+            for (IndicesService indicesService : internalCluster().getDataNodeInstances(IndicesService.class)) {
+                for (IndexService indexService : indicesService) {
+                    for (IndexShard indexShard : indexService) {
+                        try {
+                            assertThat(EngineTestCase.getReservingDocs(IndexShardTestCase.getEngine(indexShard)), equalTo(0L));
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java:101]: Can we make this assertion more generally too? IIRC there are some other assertions that check that things have settled down after a test (no in-flight operations, for instance) although I'm not quite sure where they are.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 4]
```diff
@@ -176,6 +176,18 @@
...
 
+    /**
+     * If multiple writes passed {@link InternalEngine#tryReserveDocs(Operation, int)} but they haven't adjusted
+     * {@link IndexWriter#getPendingNumDocs()} yet, then IndexWriter can fail with too many documents. In this case, we have to fail
+     * the engine because we already generated sequence numbers for write operations; otherwise we will have gaps in sequence numbers.
+     * To avoid this, we keep track the number of documents that are being added to IndexWriter, and account it in
+     * {@link InternalEngine#tryReserveDocs(Operation, int)}. Although we can double count some adding documents in both IW and Engine,
+     * this shouldn't be an issue because it happens for a short window and we adjust the reservingNumDocs once an indexing is completed.
+     */
+    private final AtomicLong reservingNumDocs = new AtomicLong();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:187]: Naming nit: `reserved` feels rather too general a term for me, how would you feel about renaming this something like `inFlightDocCount` instead?

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 5]
```diff
@@ -1275,11 +1308,35 @@ public DeleteResult delete(Delete delete) throws IOException {
...
+        if (totalDocs > maxDocs) {
+            adjustReservingDocs(-addingDocs);
+            return new IllegalArgumentException("Number of documents in the index can't exceed [" + maxDocs + "]");
+        } else {
+            return null;
+        }
+    }
+
+    private void adjustReservingDocs(int numDocs) {
+        assert numDocs <= 0 : numDocs;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:1331]: Since we only ever use this to release the docs, how about renaming this to something like `releaseInFlightDocs ` and accepting a positive parameter instead?

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 6]
```diff
@@ -1275,11 +1308,35 @@ public DeleteResult delete(Delete delete) throws IOException {
...
             }
             throw e;
+        } finally {
+            adjustReservingDocs(-reservedDocs);
         }
         maybePruneDeletes();
         return deleteResult;
     }
 
+    private Exception tryReserveDocs(Operation operation, int addingDocs) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:1318]: Contrasting with `releaseInFlightDocs` how about `tryAcquireInFlightDocs`?

**Review by DaveCTurner — COMMENTED** [review]
Thanks @dnhatn; implementation looks good now. I left a couple of suggestions for alternative names and an idea for a more general assertion too.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 5 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Good suggestion. I pushed https://github.com/elastic/elasticsearch/pull/63273/commits/294fcb478194df3b0ab9f659e42a9946ad5ab519.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 4 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: ++

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 6 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Ok, see https://github.com/elastic/elasticsearch/pull/63273/commits/294fcb478194df3b0ab9f659e42a9946ad5ab519

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java (hunk 3 above)
Comment (dnhatn) [reply server/src/internalClusterTest/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java]: This assertion should be very lightweight. I added it in https://github.com/elastic/elasticsearch/pull/63273/commits/290806d102a5f63ecd2af1476ba0fffb360ffc77.

**Review by DaveCTurner — APPROVED** [review]
LGTM, thanks @dnhatn

Do we consider this a bug fix? If so, do you think it should go into `7.10`?

**Comment by dnhatn** [comment]
@DaveCTurner Thanks so much for the helpful reviews.

> Do we consider this a bug fix? If so, do you think it should go into 7.10?

+1. I will backport to 7.10.
