### PR TITLE
[ESQL/Aggs] Fix testConcurrentEquals for TDigest-based aggregations

### LINKED ISSUE #146113: [CI] InternalMedianAbsoluteDeviationTests testConcurrentEquals failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #12084 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/exnczfusmfrjq)
- [elasticsearch-periodic-platform-support #12084 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/5etipqnvobb7c)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests.testConcurrentEquals" -Dtests.seed=5DA5FFA647A64C19 -Dtests.locale=en-MS -Dtests.timezone=Asia/Krasnoyarsk -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testConcurrentEquals'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"AJjML":{"meta":{},"value":0.24488496870618862,"value_as_string":"0.24"}}> but was: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"AJjML":{"meta":{},"value":0.24488496870618862,"value_as_string":"0.24"}}>
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testConcurrentEquals
- [main] 2 consecutive failures in step ubuntu-2404_platform-support-unix
- [main] 1 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [main] 2 failures in test testConcurrentEquals (3.8% fail rate in 53 executions)
- [main] 2 failures in step ubuntu-2404_platform-support-unix (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by GalLalouche**
## Gal says
AFAICT, this has been broken for a very long time, but hasn't been caught in CI yet. Even going back 2 years ago in git still shows this (flakey) failure with the given seed.

## Cursor says
`TDigestState.equals()` and `hashCode()` call `centroids()` and `centroidCount(),` which trigger lazy, non-thread-safe internal mutations (`MergingDigest.mergeNewValues` / `SortingDigest.compress`). When `testConcurrentEquals` calls `equals()` from multiple threads on a deserialized copy whose buffers have not been flushed yet, these concurrent mutations corrupt internal state.

`InternalMedianAbsoluteDeviation:` compare `medianAbsoluteDeviation` (a final `double` written as-is on the wire) instead of `valuesSketch.` A simple `compress()` in the `StreamInput` constructor is not sufficient here because the underlying `MergingDigest` has a residual concurrency issue in its read path even after flushing. Comparing the precomputed MAD value sidesteps `TDigestState` entirely and is semantically correct: it is the only externally meaningful output of this aggregation.

`AbstractInternalTDigestPercentiles:` add `state.compress()` to the `StreamInput` constructor, matching the regular constructor which already compresses. The percentile tests always stay in `SortingDigest` mode (<=100 values, compression=100, maxSortingSize=2000), where `compress()` is a lossless in-place sort that makes subsequent concurrent reads safe.

Closes #146113

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/AbstractInternalTDigestPercentiles.java [hunk 1]
```diff
@@ -68,6 +68,7 @@ protected AbstractInternalTDigestPercentiles(StreamInput in) throws IOException
             } else {
                 state = HistogramUnionState.readAsPureTDigest(HistogramUnionState.NOOP_BREAKER, in);
             }
+            state.compress();
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/AbstractInternalTDigestPercentiles.java:71]: @JonasKunz any performance implications for this one? This should normally be redundant, if we compress before serializing, and I wonder if we want to combine multiple states before compressing.

Comment (JonasKunz) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/AbstractInternalTDigestPercentiles.java:71]: I don't think the performane here should matter?
When we deserialize, we are deserializing a combined `TDigest` created by merging all TDigests of a segment (or maybe even the entire shard?). So the number of invocations here will be so low that it shouldn't matter in comparison to the rest of the work done per document?

**Review by kkrik-es — APPROVED** [review]
