### PR TITLE
Fix package upgrade test CI failure

### LINKED ISSUE #85386: [CI] PackageUpgradeTests test21CheckUpgradedVersion failing
Many other failures including:

https://gradle-enterprise.elastic.co/s/7lahgua5jheji

https://gradle-enterprise.elastic.co/s/5cjldjf3c7t3m

https://gradle-enterprise.elastic.co/s/avrzglb2fmi5i

All with
```
"type" : "security_exception",	
            "reason" : "missing authentication credentials for REST request [/library/_doc/1?pretty]",
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/xfmliqyqa5bwc/tests/:qa:os:destructiveDistroUpgradeTest.v8.1.1.default-deb/org.elasticsearch.packaging.test.PackageUpgradeTests/test21CheckUpgradedVersion

**Reproduction line:**
`null`

**Applicable branches:**
8.1, 8.0

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PackageUpgradeTests&tests.test=test21CheckUpgradedVersion

**Failure excerpt:**
```
java.lang.RuntimeException: Request failed:
HTTP/1.1 401 Unauthorized
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "missing authentication credentials for REST request [/library/_doc/1?pretty]",
        "header" : {
          "WWW-Authenticate" : [
            "Basic realm=\"security\" charset=\"UTF-8\"",
            "ApiKey"
          ]
        }
      }
    ],
    "type" : "security_exception",
    "reason" : "missing authentication credentials for REST request [/library/_doc/1?pretty]",
    "header" : {
      "WWW-Authenticate" : [
        "Basic realm=\"security\" charset=\"UTF-8\"",
        "ApiKey"
      ]
    }
  },
  "status" : 401
}

  at __randomizedtesting.SeedInfo.seed([E966C08FA96F984A:2C5542C3FE45F7A8]:0)
  at org.elasticsearch.packaging.util.ServerUtils.makeRequest(ServerUtils.java:362)
  at org.elasticsearch.packaging.util.ServerUtils.makeRequest(ServerUtils.java:354)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.assertDocsExist(PackageUpgradeTests.java:116)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.lambda$test21CheckUpgradedVersion$0(PackageUpgradeTests.java:112)
  at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:285)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.test21CheckUpgradedVersion(PackageUpgradeTests.java:112)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by n1v0lg**
The `test21CheckUpgradedVersion` package upgrade test is written with the assumption that security is disabled. However, a preceding test may run a force upgrade which enables security. This PR ensures that security is disabled at the end of the previous test.

Resolves: https://github.com/elastic/elasticsearch/issues/85386

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-upgrade-tests

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-upgrade-tests

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-upgrade-tests

File: qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java [hunk 1]
```diff
@@ -106,11 +106,14 @@ public void test20InstallUpgradedVersion() throws Exception {
         assertInstalled(distribution);
         verifyPackageInstallation(installation, distribution, sh);
         verifySecurityNotAutoConfigured(installation);
+
+        // Upgrade overwrites the configuration file because we run with `--force-confnew`, so we need to remove security configuration
+        // again
+        possiblyRemoveSecurityConfiguration(installation);
```
Comment (n1v0lg) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java:112]: I know it looks suspicious that we `verifySecurityNotAutoConfigured` and then `possiblyRemoveSecurityConfiguration`; however, `verifySecurityNotAutoConfigured` does not actually check if security is enabled or not.

Comment (albertzaharovits) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java:112]: Here's my understanding of the issue:
The BWC distrib is installed without Security, either because it is older than 8.0 or, if it is newer, the auto-configuration is reverted after installation and before starting the node.
When going from such a BWC install, the upgraded distribution is also NOT going to be auto-configured. We assert that, and that's good.
But even if the new distrib is not auto-configured for Security, Security (and authentication) still defaults to enabled.

Based on the above understanding, I suggest we use this alternative approach, which I believe is cleaner in its intention to disable security (but not refer to auto-configuration):

```
diff --git a/qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java b/qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java
index f4a4fbf79ca..5ebee7d80ec 100644
--- a/qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java
+++ b/qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java
@@ -97,15 +97,14 @@ public class PackageUpgradeTests extends PackagingTestCase {
         } else {
             installation = Packages.upgradePackage(sh, distribution);
         }
-        // We add this so that we don't trigger the SecurityImplicitBehaviorBootstrapCheck in 8
-        if (Version.fromString(bwcDistribution.baseVersion).before(Version.V_8_0_0)
-            && Version.fromString(distribution.baseVersion).onOrAfter(Version.V_8_0_0)) {
-            ServerUtils.addSettingToExistingConfiguration(installation, "xpack.security.enabled", "false");
-        }

         assertInstalled(distribution);
         verifyPackageInstallation(installation, distribution, sh);
         verifySecurityNotAutoConfigured(installation);
+
+        // TODO modify tests to work with Security
+        // Security is still enabled by default even if not autoconfigured
+        ServerUtils.addSettingToExistingConfiguration(installation, "xpack.security.enabled", "false");
     }

     @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/85386")
```

**Review by albertzaharovits — COMMENTED** [review]
I suggested an slightly different workaround. I hope you find it useful.

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-upgrade-tests

File: qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java (hunk 1 above)
Comment (albertzaharovits) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java]: I put the `addSettingToExistingConfiguration` at the end so that `assertInstalled`, `verifyPackageInstallation`, `verifySecurityNotAutoConfigured` get to run and do their stuff on the genuine files set by the upgrade process.
The bootstrap checks only run when the node starts, which is in the following test, so maybe we should move `addSettingToExistingConfiguration` there, but I don't have strong preferences.

**Review by albertzaharovits — APPROVED** [review]
LGTM

File: qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java (hunk 1 above)
Comment (n1v0lg) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java]: > The bootstrap checks only run when the node starts, which is in the following test, so maybe we should move addSettingToExistingConfiguration there, but I don't have strong preferences.

I think it's all good at the end of the current test.

**Comment by n1v0lg** [comment]
Build failed with:

> ERROR: Not all environment variables could be successfully injected. Check for similarly-named environment variables.

Which is not related to test changes.

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-windows
