### PR TITLE
Fix pooled SearchHits leak in MergeResult#writeTo on transport version mismatch

### LINKED ISSUE #146420: SearchHit - LEAK: resource was not cleaned up before it was garbage-collected.
### CI Link

https://gradle-enterprise.elastic.co/s/5hw7lt5m33wyo/console-log

### Repro line

-

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

[2026-04-15T17:24:26,619][ERROR][o.e.t.LeakTracker        ] [v9.4.0-rev-remote-0] LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	in [elasticsearch[v9.4.0-rev-remote-0][transport_worker][T#2]][]
	org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.search.SearchHit.<init>(SearchHit.java:200)
	org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.search.SearchHit.readFrom(SearchHit.java:282)
	org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.search.SearchHits.readFrom(SearchHits.java:138)
	org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.metrics.InternalTopHits.<init>(InternalTopHits.java:73)

### PR DESCRIPTION
**Pull request by eranweiss-elastic**
This PR fixes pooled `SearchHits` leaks when `MergeResult` re-serializes `DelayableWriteable.Serialized` aggs for a different `TransportVersion` by expanding once and releasing top_hits hits after the write. It also handles the pre-batched branch only for the serialized expand case (referencing live aggs unchanged). Tests reproduce the refcount issue via a capturing `InternalAggregations` reader.

Closes https://github.com/elastic/elasticsearch/issues/146420

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 1]
```diff
@@ -723,13 +723,65 @@ static MergeResult readFrom(StreamInput in) throws IOException {
...
+         *       We intercept by expanding here where we control the lifecycle.</li>
+         *   <li><b>Pre-BATCHED</b>: receivers expect raw {@link InternalAggregations} on the wire;
+         *       expansion is unavoidable. Only {@link DelayableWriteable.Serialized} produces fresh
+         *       objects that need releasing; a referencing {@link DelayableWriteable} returns the live
+         *       caller-owned reference and must not be released here.</li>
+         * </ul>
+         */
+        private static void writeAggs(StreamOutput out, DelayableWriteable<InternalAggregations> reducedAggs) throws IOException {
+            if (out.getTransportVersion().supports(BATCHED_QUERY_EXECUTION_DELAYABLE_WRITEABLE)) {
+                if (reducedAggs instanceof DelayableWriteable.Serialized<?> s && out.getTransportVersion() != s.getSerializedAtVersion()) {
```
Comment (drempapis) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:747]: nit: 

The wildcard `<?>` is fine, however I think writing `DelayableWriteable.Serialized<InternalAggregations>` would be more precise.

Based on the coding paradigms used in the code, I would expect

```
out.getTransportVersion().equals(s.getSerializedAtVersion()) == false
```

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:747]: Wildcards are erased at runtime in java. I don't think `instanceof DelayableWriteable.Serialized<InternalAggregations>` compiles.

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Eran

**Review by drempapis — COMMENTED** [review]
LGTM, though it would be good to have a second review. cc @andreidan

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 1 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:747]: Yes, at runtime, there is no difference. I verified that it compiles successfully by building the code.

**Review by drempapis — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:747]: Is the instanceof here required because there's two variants that return true from their `isSerialized` method (`Serialized` and `DelegatingDelayableWriteable`) ? Given that we already have `getSerializedSize` in the base class, I also wonder if we should add the `serializedAtVersion` to the base class too, and perhaps rework things so that no instanceof is required. Would that make sense?

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 2]
```diff
@@ -723,13 +723,65 @@ static MergeResult readFrom(StreamInput in) throws IOException {
...
+
+        /**
+         * Writes {@code reducedAggs} to {@code out}, releasing any pooled {@link SearchHits} held by
+         * top-hits aggregations after the write whenever expansion produces freshly deserialized objects.
+         *
+         * <p>Two paths require an explicit expand + release to avoid leaking pooled SearchHits:
+         * <ul>
+         *   <li><b>BATCHED, version mismatch</b>: {@link DelayableWriteable.Serialized#writeTo} would
+         *       expand transiently via {@code referencing(expand()).writeTo(out)} and discard the result.
+         *       We intercept by expanding here where we control the lifecycle.</li>
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:738]: for my understanding, the expansion in this scenario would already happen , same as this PR does, but we'd miss to release the expanded variant once written? We are mostly replicating what writeTo already does, adding the release on top?

Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:738]: Correct.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 1 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:747]: @drempapis honestly, I find the code clearer as-is.
@javanna sounds reasonable to me, but out of scope for this bug fix.
