### PR TITLE
Better handling of node ids from shutdown metadata

### LINKED ISSUE #100201: NullPointerException in DiskThresholdMonitor via RoutingNode.iterator
### Elasticsearch Version

8.7.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

ess docker image

### Problem Description

It seems to occur on the master when a node has left the cluster.
```
[INFO ][org.elasticsearch.cluster.InternalClusterInfoService] failed to notify [org.elasticsearch.node.Node$$Lambda$4937/0x00000008020ab618@62cb72f] of new cluster info
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.routing.RoutingNode.iterator()" because the return value of "org.elasticsearch.cluster.routing.RoutingNodes.node(String)" is null
	at org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor.onNewInfo(DiskThresholdMonitor.java:386) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.cluster.InternalClusterInfoService$AsyncRefresh.callListeners(InternalClusterInfoService.java:330) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:102) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:54) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.action.support.RefCountingRunnable.releaseRef(RefCountingRunnable.java:134) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.action.support.RefCountingRunnable$AcquiredRef.close(RefCountingRunnable.java:77) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.core.IOUtils.close(IOUtils.java:71) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.core.Releasables.close(Releasables.java:32) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.action.ActionListener$6.run(ActionListener.java:521) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.action.ActionListener$RunAfterActionListener.onResponse(ActionListener.java:394) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:49) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:958) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.7.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Steps to Reproduce

Observed in production, have not reproduced.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ldematte**
Currently, the DiskThresholdMonitor code considers shutdown metadata to identify nodes that are being replaced. If the node-to-be-replaced (source) leaves the cluster before the corresponding shutdown metadata is removed from the cluster state, we can have a NPE. This PR adds a test for that and improves a bit code to handle node ids for source and target from shutdown metadata.

Fixes https://github.com/elastic/elasticsearch/issues/100201

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorTests.java [hunk 1]
```diff
@@ -1409,6 +1409,78 @@ public void testSkipDiskThresholdMonitorWhenStateNotRecovered() {
...
+                )
+            )
+        );
+
+        final Metadata metadata = metadataBuilder.build();
+        final RoutingTable routingTable = RoutingTable.builder(TestShardRoutingRoleStrategies.DEFAULT_ROLE_ONLY)
+            .addAsNew(metadata.getProject(projectId).index("test"))
+            .build();
+        DiscoveryNodes.Builder discoveryNodes = DiscoveryNodes.builder()
+            // .add(newNormalNode("node1", "node1"))
```
Comment (mosche) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorTests.java:1443]: remove?

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorTests.java [hunk 2]
```diff
@@ -1409,6 +1409,78 @@ public void testSkipDiskThresholdMonitorWhenStateNotRecovered() {
...
+            .add(newNormalNode("node2", "node2"));
+        // node1 which is replaced by node1 may or may not be in the cluster
```
Comment (mosche) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorTests.java:1445]: node1 is replaced by node 3

**Review by mosche — APPROVED** [review]
thanks @ldematte , lgtm, just some minor tiny nits on the tests

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorTests.java (hunk 2 above)
Comment (ldematte) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitorTests.java:1445]: Thanks for spotting this
