### PR TITLE
SQL: Fix literal projection with condition

### LINKED ISSUE #64567: SQL: wrong result on literal selection with condition
While 
`SELECT * FROM test_emp WHERE languages = 0` correctly returns nothing (there's no match for the filter), 
`SELECT true FROM test_emp WHERE languages = 0` wrongly returns one row/column result: `true`.  Noteworthy, 
`SELECT true FROM test_emp WHERE false` returns nothing, es expected.

### PR DESCRIPTION
**Pull request by Luegg**
Fixes https://github.com/elastic/elasticsearch/issues/64567

Queries with a literal selection and a filter like `SELECT 1 FROM test_emp WHERE gender = 'F'` are currently erroneously optimised to use a local relation. This causes ES to always return a single record, no matter how many records match the filter condition.

This PR makes sure that `SkipQueryIfFoldingProjection` only skips the query if it's an aggregate with only constants (e.g. `SELECT 'foo' FROM test GROUP BY 1`). This optimization seems to lead to another issue https://github.com/elastic/elasticsearch/issues/74064 that's not yet addressed in this PR.

Besides this the "skip query" optimization, the `SkipQueryIfFoldingProjection` class also folds constants from `LocalRelation`s and pushes the evaluated values into a new `LocalRelation` (e.g. for queries like `SELECT 1 + 2`).

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 1]
```diff
@@ -1149,22 +1150,48 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
         @Override
         protected LogicalPlan rule(LogicalPlan plan) {
             Holder<LocalRelation> optimizedPlan = new Holder<>();
-            plan.forEachDown(Project.class, p -> {
-                List<Object> values = extractConstants(p.projections());
-                if (values.size() == p.projections().size() && (p.child() instanceof EsRelation) == false &&
-                    isNotQueryWithFromClauseAndFilterFoldedToFalse(p)) {
+            var leafRelation = leafRelation(plan);
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1153]: Personally, I'm not fun of `var` in the code, I like more in the tests for simplification, but let's wait for the opinion of the others.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 2]
```diff
@@ -1149,22 +1150,48 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
             if (optimizedPlan.get() != null) {
                 return optimizedPlan.get();
             }
 
             plan.forEachDown(Aggregate.class, a -> {
                 List<Object> values = extractConstants(a.aggregates());
-                if (values.size() == a.aggregates().size() && a.groupings().isEmpty()
-                    && isNotQueryWithFromClauseAndFilterFoldedToFalse(a)) {
+
+                // aggregations on only constant values like "SELECT 'foo' FROM test GROUP BY 1"
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1181]: Might be worth adding this statement (or similar) into the optimiser tests too, imo.

**Review by bpintea — COMMENTED** [review]
Nice! Looks good, only left a few small notes.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1153]: Personally I also find that making the type explicit is more readable, although there are places in ES - less so in *QL, I think - where `var` is used.

Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1153]: 👍 Costin also pointed out that `var` is not yet available in Java 8, so not using it also helps a lot with backporting the fix to 7.x.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1181]: `testSkipQueryOnEsAggregationWithOnlyConstants` should cover this case

**Comment by Luegg** [comment]
I've addressed your comments and also tried to consolidate the partially duplicated logic of the `Project` and `Aggregate` cases. Thanks to the consolidated logic and the `collectFirstDown` method it should also use less traversals through the query tree.

Please have another look.

**Review by matriv — APPROVED** [review]
LGTM. Thank you!

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/tree/Node.java [hunk 3]
```diff
@@ -161,6 +162,33 @@ protected void doCollectFirst(Predicate<? super T> predicate, List<T> matches) {
         }
     }
 
+    public <R> Optional<R> collectFirstDown(Class<R> typeToken) {
```
Comment (astefan) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/tree/Node.java:165]: This method is never used.
I'd suggest adding it when needed.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 4]
```diff
@@ -1148,32 +1149,37 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
+            Optional<LogicalPlan> optimized = plan.collectFirstDown(p -> {
+                Optional<List<Object>> foldedValues = Optional.empty();
+
+                if (p instanceof Project && isNonSkippedLocalRelation) {
+                    foldedValues = Optional.of(extractConstants(((Project) p).projections()));
+                } else if (p instanceof Aggregate) {
+                    Aggregate a = (Aggregate) p;
+                    List<Object> folded = extractConstants(a.aggregates());
+
+                    boolean onlyConstantAggregations = relation instanceof EsRelation &&
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1169]: We should try to use a consistent code style and one of the practices is the use of `&&` and `||` at the start of the line, not at the end, in case of multiline conditions.

**Review by astefan — APPROVED** [review]
LGTM overall. Left two minor comments.
Also, why the use of `Optional`? It's not something we use in *QL.

**Review by bpintea — APPROVED** [review]
Lgtm.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/tree/Node.java [hunk 5]
```diff
@@ -161,6 +162,23 @@ protected void doCollectFirst(Predicate<? super T> predicate, List<T> matches) {
         }
     }
 
+    @SuppressWarnings("unchecked")
+    public <R> Optional<R> collectFirstDown(Function<T, Optional<R>> fn) {
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/tree/Node.java:166]: This method is not needed; it's a tweaked version of `collectFirstChildren` that has several issues:

1. collect methods should return a list not a single value.
2. Optional is not used in the QL code-base (missing is null for single value, empty lists for multiple ones).
3. for condition parameter, use Predicate not Function (another reason why Optional doesn't work)
4. collectFirstDown is similar to collectFirstChildren. The former returns at first match while the latter looks at all current children in case of a match. I don't think there are any performance issues with this approach and it forces the caller to look at the issue in a more general fashion:
- do I only need for one child to match?
- what if there are multiple matches - is that acceptable or a non existing case?

File: x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec [hunk 6]
```diff
@@ -54,6 +54,10 @@ sameConstantsWithLimitV2
 SELECT 5, 3, 3 FROM "test_emp" LIMIT 5;
 sameConstantsWithLimitV3
 SELECT 3, 5, 3, 3 FROM "test_emp" LIMIT 5;
+constantWithWhere
+SELECT 1 FROM "test_emp" WHERE gender = 'F';
+constantWithWhereOrderAndLimit
+SELECT 1 FROM "test_emp" WHERE gender = 'F' ORDER BY emp_no LIMIT 5;
```
Comment (costin) [inline x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec:60]: Please add more tests to test different varieties of tested plan:
`WHERE a and b`
`WHERE a and function(b)`
`WHERE a and b ORDER BY c`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 7]
```diff
@@ -1148,32 +1149,37 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
         protected LogicalPlan rule(LogicalPlan plan) {
-            Holder<LocalRelation> optimizedPlan = new Holder<>();
-            plan.forEachDown(Project.class, p -> {
-                List<Object> values = extractConstants(p.projections());
-                if (values.size() == p.projections().size() && (p.child() instanceof EsRelation) == false &&
-                    isNotQueryWithFromClauseAndFilterFoldedToFalse(p)) {
-                    optimizedPlan.set(new LocalRelation(p.source(), new SingletonExecutable(p.output(), values.toArray())));
-                }
-            });
+            LogicalPlan relation = plan
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1152]: This statement is confusing since it looks for nodes that have no children. Which currently happens to be `Relation` nodes however that's not mandatory in the future.
It's better to just introduce a `Relation` class which can be just an extension to `LeafPlan` and be the super class of all existing Relation classes (`EsRelation` and `LocalRelation`).
Then this condition becomes `plan.collect(Relation::instanceOf)`.
As an alternative that doesn't require introducing a `Relation` class simply look at the leaves and check whether they are relationship - `plan.collectLeaves()`.

**Review by costin — CHANGES_REQUESTED** [review]
Left a few comments regarding the new method on `Node` and iteration style.

**Comment by Luegg** [comment]
@costin please have another look, I've addressed your comments and the implementation should now also be more robust against some cases where the optimization might have erroneously be applied when it shouldn't. E.g. there might be cases (in the future?) with more than one Project/Aggregate or Relation.

I'm hesitant of introducing `Relation` as I'm not sure it adds much value in general and even in this case I'm only interested in two specific relations and not e.g. `UnresolvedRelation` or the EQL `LocalRelation`. The `collectLeaves` approach seems sufficient to me.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 8]
```diff
@@ -1148,29 +1148,40 @@ private static LogicalPlan skipPlan(UnaryPlan plan) {
...
+                // exclude LocalRelations that have been introduced by earlier optimizations (skipped ESRelations)
+                boolean isNonSkippedLocalRelation = leaf instanceof LocalRelation
+                    && ((LocalRelation) leaf).executable() instanceof EmptyExecutable == false;
 
-            plan.forEachDown(Aggregate.class, a -> {
-                List<Object> values = extractConstants(a.aggregates());
-                if (values.size() == a.aggregates().size() && a.groupings().isEmpty()
-                    && isNotQueryWithFromClauseAndFilterFoldedToFalse(a)) {
-                    optimizedPlan.set(new LocalRelation(a.source(), new SingletonExecutable(a.output(), values.toArray())));
+                if (projectOrAggregate instanceof Project && isNonSkippedLocalRelation) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1166]: The if/else could be optimized by swapping it around and avoid checking for Project:
```
if (projectOrAggregate instanceof Aggregate) {
 ...
 }
else if (isNonSkippedLocalRelation) // no need to check for Project
```

**Review by costin — APPROVED** [review]
Thanks. This looks great!
