### PR TITLE
[ML] shore up the ML feature reset code and fix potential bugs

### LINKED ISSUE #71282: TestFeatureResetIT#testMLFeatureReset due to IndexNotFoundException and index existance
Both of these failures most likely occur because an index is in the middle of creating (or just recently created) when the cleanup code is called. 

Either way, ML seems to be creating an index right when (or immediately after) the feature cleanup is called.

**Build scan**:
https://gradle-enterprise.elastic.co/s/ehe5tqwsisrdw (master IndexNotFoundException)

https://gradle-enterprise.elastic.co/s/xfedsqfusfgq6 (indices existing)

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.testMLFeatureReset" -Dtests.seed=A4E4BA6353C5E27B -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Asia/Omsk -Druntime.java=11
```

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.testMLFeatureReset" -Dtests.seed=CF9724BE7F079A8B -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=America/Cayenne -Druntime.java=8
```
**Reproduces locally?**:
No
**Applicable branches**:
master, 7.x
**Failure history**:

**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.TestFeatureResetIT > testMLFeatureReset FAILED
    [.ml-annotations-6] org.elasticsearch.index.IndexNotFoundException: no such index [.ml-annotations-6]
        at __randomizedtesting.SeedInfo.seed([A4E4BA6353C5E27B:102D59B586A84AFB]:0)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:985)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:922)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:878)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:218)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:196)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:83)
        at org.elasticsearch.action.support.master.info.TransportClusterInfoAction.checkBlock(TransportClusterInfoAction.java:38)
        at org.elasticsearch.action.support.master.info.TransportClusterInfoAction.checkBlock(TransportClusterInfoAction.java:24)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:121)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:98)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:46)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:77)
        at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:42)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:75)
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:160)
        at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:217)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:77)
        at org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:22)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.IndicesAliasesRequestInterceptor.intercept(IndicesAliasesRequestInterceptor.java:106)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.ResizeRequestInterceptor.intercept(ResizeRequestInterceptor.java:86)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.BulkShardRequestInterceptor.intercept(BulkShardRequestInterceptor.java:77)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:77)
        at org.elasticsearch.xpack.security.authz.interceptor.UpdateRequestInterceptor.intercept(UpdateRequestInterceptor.java:24)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:385)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:362)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$9(AuthorizationService.java:302)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:687)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:662)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
        at org.elasticsearch.xpack.security.authz.RBACEngine.buildIndicesAccessControl(RBACEngine.java:556)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$authorizeIndexAction$4(RBACEngine.java:336)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.lambda$getAsync$0(AuthorizationService.java:725)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.resolveIndexNames(AuthorizationService.java:599)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$6(AuthorizationService.java:290)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.lambda$getAsync$0(AuthorizationService.java:725)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.RBACEngine.loadAuthorizedIndices(RBACEngine.java:367)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$5(AuthorizationService.java:286)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.getAsync(AuthorizationService.java:723)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$8(AuthorizationService.java:289)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.getAsync(AuthorizationService.java:723)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$authorizeIndexAction$5(RBACEngine.java:328)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexActionName(RBACEngine.java:352)
        at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexAction(RBACEngine.java:325)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:300)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:265)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$1(AuthorizationService.java:229)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$1(RBACEngine.java:127)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:249)
        at org.elasticsearch.xpack.security.authz.RBACEngine.getRoles(RBACEngine.java:133)
        at org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:121)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:231)
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:178)
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$4(SecurityActionFilter.java:159)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:336)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$8(AuthenticationService.java:414)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:425)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:333)
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:167)
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:154)
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:106)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:75)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:53)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:53)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:49)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:232)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$0(SecurityServerTransportInterceptor.java:286)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:77)
        at org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:22)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.IndicesAliasesRequestInterceptor.intercept(IndicesAliasesRequestInterceptor.java:106)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.ResizeRequestInterceptor.intercept(ResizeRequestInterceptor.java:86)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.BulkShardRequestInterceptor.intercept(BulkShardRequestInterceptor.java:77)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$runRequestInterceptors$14(AuthorizationService.java:379)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:87)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:116)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:53)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29)
        at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:77)
        at org.elasticsearch.xpack.security.authz.interceptor.UpdateRequestInterceptor.intercept(UpdateRequestInterceptor.java:24)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:385)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:362)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$9(AuthorizationService.java:302)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:687)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:662)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
        at org.elasticsearch.xpack.security.authz.RBACEngine.buildIndicesAccessControl(RBACEngine.java:556)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$authorizeIndexAction$4(RBACEngine.java:336)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.lambda$getAsync$0(AuthorizationService.java:725)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.resolveIndexNames(AuthorizationService.java:599)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$6(AuthorizationService.java:290)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.lambda$getAsync$0(AuthorizationService.java:725)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.RBACEngine.loadAuthorizedIndices(RBACEngine.java:367)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$5(AuthorizationService.java:286)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.getAsync(AuthorizationService.java:723)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$8(AuthorizationService.java:289)
        at org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.getAsync(AuthorizationService.java:723)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$authorizeIndexAction$5(RBACEngine.java:328)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexActionName(RBACEngine.java:352)
        at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexAction(RBACEngine.java:325)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:300)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:265)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$1(AuthorizationService.java:229)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
        at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$1(RBACEngine.java:127)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:249)
        at org.elasticsearch.xpack.security.authz.RBACEngine.getRoles(RBACEngine.java:133)
        at org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:121)
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:231)
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:112)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:336)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$8(AuthenticationService.java:414)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:425)
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:333)
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:184)
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:103)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:293)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:61)
        at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:203)
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:102)
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:84)
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:678)
        at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:129)
        at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104)
        at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:63)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:834)
```

&&

```
org.elasticsearch.xpack.ml.integration.TestFeatureResetIT > testMLFeatureReset FAILED
    java.lang.AssertionError: 
    Expected: an empty array
         but: array size was <2>
        at __randomizedtesting.SeedInfo.seed([CF9724BE7F079A8B:7B5EC768AA6A320B]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.lambda$testMLFeatureReset$2(TestFeatureResetIT.java:82)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1019)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:992)
        at org.elasticsearch.xpack.ml.integration.TestFeatureResetIT.testMLFeatureReset(TestFeatureResetIT.java:82)
```

### PR DESCRIPTION
**Pull request by benwtrent**
The ML feature reset code was originally force closing all datafeeds, anomaly jobs, and analytics jobs.

This does not allow the caller to wait for the persistent tasks to complete. It is possible for a persistent task
to NOT exist in cluster state, but the individual node task is still executing. But, there is no visibility.

To prevent this from causing issues and more complexity in the feature reset code, this commit
attempts to close/stop all datafeeds, jobs, and data frame jobs without force first. If that fails, then
force is attempted.

additionally, this commit addresses two gaps in the reset mode handling:

- In the bulk execution retry, this was previously ignoring the reset mode flag
- In trained model stats persister, this was also ignoring the reset mode flag

closes https://github.com/elastic/elasticsearch/issues/71282

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java [hunk 1]
```diff
@@ -106,6 +108,11 @@ public void beforeStop() {
                 shutdown();
             }
         });
+        clusterService.addListener((event) -> {
+            if (event.metadataChanged()) {
+                isResetMode = MlMetadata.getMlMetadata(event.state()).isResetMode();
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java:113]: I think there is a nasty edge case with this.

The scenario is that a reset starts and finishes while this class is sleeping between retries.  Then when it wakes up it writes documents that were retrying from before the refresh.

One way around this that I can think of is to have an incrementing count of how many times reset mode has toggled.  Any scheduled retries that wake up check if that count is different to what it was when they were originally scheduled, and if there's a difference they do nothing.

Another way might be to cancel any scheduled retries when this reset mode flag changes value.

**Review by droberts195 — COMMENTED** [review]
> this commit attempts to close/stop all datafeeds, jobs, and data frame jobs without force first

The problem with doing this is that if the jobs _do_ close gracefully, they will persist state and could take a long time to do this and generate significant system load while they do.  For example, a job that has a 20GB uncompressed state will have to generate the ~2GB compressed version of that, then chunk and index those documents, only for the index they were indexed into to immediately get blown away.

Possibly explicitly calling the kill process action first might help.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/persistence/ResultsPersisterService.java:113]: > Another way might be to cancel any scheduled retries when this reset mode flag changes value.

This might be the easiest way as we already keep track of which retryable actions are inflight. Will just have to separate out the search and the bulk inflight actions.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Review by droberts195 — APPROVED** [review]
LGTM
