### PR TITLE
Skip the shrink step if the number of shards of the shrunk index is the same with the original

### LINKED ISSUE #80180: [ILM] Shrink action fails with a single primary shard in conjunction with `max_primary_shard_size`
**Elasticsearch version** (`bin/elasticsearch --version`): `7.14.2`

**Plugins installed**: []

**JVM version** (`java -version`): ESS

**OS version** (`uname -a` if on a Unix-like system): ESS

**Description of the problem including expected versus actual behavior**:

The `shrink` ILM phase failed when trying to apply to an index with a single primary shard and a phase definition that utilises the `max_primary_shard_size` option.

Exception recorded:
```
java.lang.IllegalArgumentException: can't shrink an index with only one shard
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateShrinkIndex(MetadataCreateIndexService.java:1147)
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.prepareResizeIndexSettings(MetadataCreateIndexService.java:1233)
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.aggregateIndexSettings(MetadataCreateIndexService.java:809)
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithExistingMetadata(MetadataCreateIndexService.java:631)
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:334)
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:377)
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:294)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:313)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:208)
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:62)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create an index with a single primary shard.
 2. Define an ILM policy with the following `warm` phase:
  ```json
{
  "policy": "metricbeat",
  "phase_definition": {
    "min_age": "0d",
    "actions": {
      "allocate": {
        "number_of_replicas": 1,
        "include": {},
        "exclude": {},
        "require": {}
      },
      "forcemerge": {
        "max_num_segments": 1
      },
      "set_priority": {
        "priority": 25
      },
      "shrink": {
        "max_primary_shard_size": "50gb"
      }
    }
  },
  "version": 18,
  "modified_date_in_millis": 1635781185067
}
  ```
 3. Associate ILM policy with index
 4. Trigger rollover of index.

**Provide logs (if relevant)**:

Related: #33275

### PR DESCRIPTION
**Pull request by gmarouli**
This PR extends the existing of functionality of skipping the shrink step in ILM if the `number_of_shards` in the action is the same with the number of primary shards of the original index to also apply when we configure `max_primary_shard_size`.

This should resolve: #80180

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java [hunk 1]
```diff
@@ -0,0 +1,190 @@
...
+    /**
+     * Verifies if the target number of shards is feasible based on the operation. For example, in the case of SHRINK it will check if the
+     * doc count per shard is within limits and in the other opetations it will ensure we get the right exceptions if the number of shards
+     * is wrong or less than etc.
+     * @param numberOfShards the number of shards the target index is going to have
+     * @param sourceMetadata the index metadata of the source index
+     */
+    void verify(int numberOfShards, IndexMetadata sourceMetadata);
+
+    class Shrink implements TargetNumberOfShardsCalculator {
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:51]: I wonder if having such simple naming for these classes would be confusing when searching the codebase? Would ShrinkShardsCalculator or such be more grep friendly?

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java [hunk 2]
```diff
@@ -0,0 +1,190 @@
...
+public interface TargetNumberOfShardsCalculator {
+
+    /**
+     * Calculates the target number of shards based on the parameters of the request
+     * @param numberOfShards requested number of shards or null if it was not provided
+     * @param maxPrimaryShardSize requested max primary shard size or null if it was not provided
+     * @param sourceMetadata the index metadata of the source index
+     * @return the number of shards for the target index
+     */
+    int calculate(@Nullable Integer numberOfShards, ByteSizeValue maxPrimaryShardSize, IndexMetadata sourceMetadata);
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:40]: I believe the `maxPrimaryShardSize` can be nullable too. Shall we annotate it?

File: server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+import org.elasticsearch.cluster.metadata.IndexMetadata;
+import org.elasticsearch.common.settings.Settings;
+import org.elasticsearch.common.unit.ByteSizeValue;
+import org.elasticsearch.index.shard.DocsStats;
+import org.elasticsearch.index.store.StoreStats;
+import org.elasticsearch.test.ESTestCase;
+
+import static org.elasticsearch.action.admin.indices.shrink.TargetNumberOfShardsCalculator.Shrink.calculateAcceptableNumberOfShards;
+
+public class TargetNumberOfShardsCalculatorTests extends ESTestCase {
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java:21]: ❤️

File: server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+            .put("index.version.created", Version.CURRENT)
+            .build();
+        IndexMetadata indexMetadata = IndexMetadata.builder("index").settings(settings).build();
+
+        TargetNumberOfShardsCalculator.Shrink shrink = new TargetNumberOfShardsCalculator.Shrink(
+            new StoreStats(between(1, 100), between(0, 100), between(1, 100)),
+            (i) -> new DocsStats(between(1, 1000), between(1, 1000), between(0, 10000))
+        );
+        assertEquals(4, shrink.calculate(4, null, indexMetadata));
+        assertEquals(1, shrink.calculate(null, null, indexMetadata));
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java:36]: should this be illegal? ie. an exception thrown or such? It's not clear to me why this would be `1`

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkAction.java [hunk 5]
```diff
@@ -173,10 +169,26 @@ public boolean isSafeAction() {
...
-                return false;
-            }
+                String indexName = indexMetadata.getIndex().getName();
+                client.admin()
+                    .indices()
+                    .prepareStats(indexName)
+                    .clear()
+                    .setDocs(true)
+                    .setStore(true)
+                    .execute(listener.delegateFailure((delegateListener, indicesStatsResponse) -> {
```
Comment (andreidan) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkAction.java:182]: can we add a test for this such that it fails and moves ILM to the ERROR step?

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java [hunk 6]
```diff
@@ -117,7 +118,27 @@ public void testShrinkSameShards() throws Exception {
...
+        createNewSingletonPolicy(client(), policy, "warm", new ShrinkAction(null, ByteSizeValue.ofGb(50)));
+        updatePolicy(client(), index, policy);
+        assertBusy(() -> {
+            assertTrue(indexExists(index));
+            Map<String, Object> settings = getOnlyIndexSettings(client(), index);
+            assertThat(getStepKeyForIndex(client(), index), equalTo(PhaseCompleteStep.finalStep("warm").getKey()));
+            assertNull(settings.get(IndexMetadata.INDEX_BLOCKS_WRITE_SETTING.getKey()));
+            assertThat(settings.get(IndexMetadata.INDEX_ROUTING_REQUIRE_GROUP_SETTING.getKey() + "_id"), nullValue());
+            // the shrink action was effectively skipped so there must not be any `shrink_index_name` in the ILM state
+            assertThat(explainIndex(client(), index).get(SHRINK_INDEX_NAME), nullValue());
```
Comment (andreidan) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java:141]: These assertions are all valid if ILM does not run for this index. 

Would asserting ILM is in the complete step for the warm phase and the target would've been shrunk index does not exist make sense here?

**Review by andreidan — CHANGES_REQUESTED** [review]
Thanks for working on this Mary. I've left a first round of suggestions and questions.

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java [hunk 7]
```diff
@@ -0,0 +1,190 @@
...
+
+import java.util.Objects;
+import java.util.Set;
+import java.util.function.IntFunction;
+
+/**
+ * This class calculates and verifies the number of shards of a target index after a resize operation. It supports three operations SHRINK,
+ * SPLIT and CLONE.
+ */
+public interface TargetNumberOfShardsCalculator {
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:31]: Yes! Thank you! `ResizeNumberOfShardsCalculator` is what I was looking for (but I couldn't come with it :p)

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java [hunk 8]
```diff
@@ -0,0 +1,190 @@
...
+    int calculate(@Nullable Integer numberOfShards, ByteSizeValue maxPrimaryShardSize, IndexMetadata sourceMetadata);
+
+    /**
+     * Verifies if the target number of shards is feasible based on the operation. For example, in the case of SHRINK it will check if the
+     * doc count per shard is within limits and in the other opetations it will ensure we get the right exceptions if the number of shards
+     * is wrong or less than etc.
+     * @param numberOfShards the number of shards the target index is going to have
+     * @param sourceMetadata the index metadata of the source index
+     */
+    void verify(int numberOfShards, IndexMetadata sourceMetadata);
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:49]: Yes, validate sounds better also, I will keep it in mind for the future.

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java (hunk 1 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:51]: Good point, I didn't think about that, I will change it.

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java (hunk 2 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:40]: Definitely, I missed it

File: server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java [hunk 9]
```diff
@@ -0,0 +1,190 @@
...
+        public Shrink(String sourceIndex, IndicesStatsResponse indicesStatsResponse) {
+            this.indexStoreStats = indicesStatsResponse.getPrimaries().store;
+            this.perShardDocStats = i -> {
+                IndexShardStats shard = indicesStatsResponse.getIndex(sourceIndex).getIndexShards().get(i);
+                return shard == null ? null : shard.getPrimary().getDocs();
+            };
+        }
+
+        // Facilitates testing
+        public Shrink(StoreStats indexStoreStats, IntFunction<DocsStats> perShardDocStats) {
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculator.java:66]: I wanted to avoid defining the `perShardDocStats` in every call, but maybe it's not that bad and I like having only one constructor for this. I will change it.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkAction.java (hunk 5 above)
Comment (gmarouli) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkAction.java:182]: I added a test that checks that the error gets propagated to the listener which I think is effectively the same, because the `onFailure` of the `IndexLifecycleRunner` will move it to the error step.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java (hunk 6 above)
Comment (gmarouli) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java:141]: Line 137 :)

```
assertThat(getStepKeyForIndex(client(), index), equalTo(PhaseCompleteStep.finalStep("warm").getKey()));
```

File: server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java (hunk 4 above)
Comment (gmarouli) [reply server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java]: Confirmed, this path is triggered but this request: `POST /many-shards/_shrink/shrinked`

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java (hunk 6 above)
Comment (andreidan) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java:141]: Ah, way ahead of me :) Sorry, I missed that

Comment (gmarouli) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/ShrinkActionIT.java:141]: No worries, I cannot take the credit, I used the existing tests as an example.

File: server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java (hunk 4 above)
Comment (andreidan) [reply server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TargetNumberOfShardsCalculatorTests.java]: Ah thanks for checking this. I think we should improve the shrink API docs (not in this PR) to state that we default to 1 when no target (number of shards, or max primary shard size) is specified

**Review by andreidan — APPROVED** [review]
LGTM, thanks for iterating on this Mary
