### PR TITLE
Handle nested fields with the termvectors REST API in artificial docs

### LINKED ISSUE #91902: Term vectors for nested fields
### Elasticsearch Version

7.14.2

### Installed Plugins

_No response_

### Java Version

openjdk version "1.8.0-262" OpenJDK Runtime Environment (build 1.8.0-262-b10) OpenJDK 64-Bit Server VM (build 25.71-b10, mixed mode)

### OS Version

windows 10

### Problem Description

Using the [mtermvectors api](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-termvectors.html) to get the term vectors (with term_statistics) for an artificial document Elasticsearch will ignore the nested fields. 

### Steps to Reproduce

To reproduce:
Create the index and upload a doc
```
PUT /my-index-000001
{
  "mappings": {
    "properties": {
      "user": {
        "type": "nested",
        "properties": {
            "first" :  {
                "type": "text"
            },
            "last" :  {
                "type": "text"
            },
            "description":{
                "type": "text"
            }
        }
      }
    }
  }
}
PUT /my-index-000001/_doc/1
{
  "group" : "fans",
  "user" : [
    {
      "first" : "John",
      "last" :  "Smith",
      "description":"first description"
    },
    {
      "first" : "Alice",
      "last" :  "White",      
      "description":"second description"
    }
  ]
}
```
Request the term vector for an artificial document
```
GET my-index-000001/_mtermvectors
{ 
   "docs": [ 
    { 
        "doc" : {
            "group":"test",
            "user" : [
                {
                "first" : "John",
                "last" :  "Smith",
                "description":"artificial description"
                }
            ]
        }, 
        "fields": ["*"], 
        "term_statistics":true,
        "positions":false,
        "offsets":false
    }
   ]
}
```
Response
```
{
    "docs": [
        {
            "_index": "my-index-000001",
            "_type": "_doc",
            "_version": 0,
            "found": true,
            "took": 0,
            "term_vectors": {
                "group": {
                    "field_statistics": {
                        "sum_doc_freq": 1,
                        "doc_count": 1,
                        "sum_ttf": 1
                    },
                    "terms": {
                        "test": {
                            "term_freq": 1
                        }
                    }
                }
            }
        }
    ]
}
```
The response does not include the term vector for the nested field.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by scampi**
Close #91902

### CODE REVIEW

**Comment by scampi** [comment]
You need any change to this PR ?

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Comment by carlosdelest** [comment]
@elasticmachine test this please

File: server/src/main/java/org/elasticsearch/index/termvectors/TermVectorsService.java [hunk 1]
```diff
@@ -185,6 +186,11 @@ private static boolean isValidField(MappedFieldType fieldType) {
         if (fieldType.isIndexed() == false) {
             return false;
         }
+        // and must not be the nested path field
+        if (fieldType.name().equals(NestedPathFieldMapper.NAME)) {
```
Comment (carlosdelest) [inline server/src/main/java/org/elasticsearch/index/termvectors/TermVectorsService.java:190]: Added this to the original PR

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Comment by benwtrent** [comment]
@elasticmachine test this please

**Review by carlosdelest — APPROVED** [review]
LGTM

**Comment by carlosdelest** [comment]
Better late than never, merging this into Elasticsearch. Thanks for your contribution @scampi !
