### PR TITLE
Remove environment from transport client

### LINKED ISSUE #13155: 2.0.beta1 - Exception "path.home is not configured" when starting ES in transport and client mode
Hi,
I just installed the new beta version 2.0.0-beta1 and ran some code that used to work with ES 1.7.0. 
I got an exception where it complained that "path.home is not configured". 
Is this something new? Why would I need to configure anything beside the cluster name in transport mode?

Thanks

```
Exception in thread "main" java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:97)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:70)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:114)
	at com.thesoftwarefactory.persistence.elasticsearch.DataConnection.open(DataConnection.java:62)
```

### PR DESCRIPTION
**Pull request by rjernst**
Transport clients run embedded within external applications, so
elasticsearch should not be doing anything with the filesystem, as there
is not elasticsearch home.

This change makes a number of cleanups to the internal API for loading
settings and creating an environment. The loadFromConfig option was
removed, since it was always true except for tests. We now always
attempt to load settings from config a file when an environment is
created. The prepare methods were also simplified so there is now
prepareSettingsAndEnvironment which nodes use, and prepareSettings which
the transport client uses. I also attempted to improve the tests, but
there is a still a lot of follow up work to do there.

closes #13155

NOTE: I left a handful of TODOs for things that looked fishy in prepareSettingsAndEnvironment. In general this should really be cleaned up to be much simpler. There are far to many ways to configure the settings for a developer to understand the code, so I don't know how a user would understand whether to put a setting in properties, env vars, or one of many possible files, or forcing a property, or setting a default, etc.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java [hunk 1]
```diff
@@ -197,7 +197,7 @@ private static void setupLogging(Settings settings, Environment environment) {
 
     private static Tuple<Settings, Environment> initialSettings(boolean foreground) {
         Terminal terminal = foreground ? Terminal.DEFAULT : null;
-        return InternalSettingsPreparer.prepareSettings(EMPTY_SETTINGS, true, terminal);
+        return InternalSettingsPreparer.prepareSettingsAndEnvironment(EMPTY_SETTINGS, terminal);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: it might be simpler to just name this `InternalSettingsPreparer.prepareEnvironment` and return only `Environment` since it has the settings already as a member then we can spare the tuple and things are less funky?

File: core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java [hunk 2]
```diff
@@ -52,22 +53,22 @@
  */
 public class InternalSettingsPreparer {
 
-    static final List<String> ALLOWED_SUFFIXES = Arrays.asList(".yml", ".yaml", ".json", ".properties");
+    static final String[] ALLOWED_SUFFIXES = {".yml", ".yaml", ".json", ".properties"};
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java]: should these be private? not sure who is using it...

File: core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java [hunk 3]
```diff
@@ -75,126 +76,143 @@
...
-                // if explicit, just load it and don't load from env
-                if (Strings.hasText(System.getProperty("es.config"))) {
-                    loadFromEnv = false;
-                    settingsBuilder.loadFromPath(environment.configFile().resolve(System.getProperty("es.config")));
-                }
-                if (Strings.hasText(System.getProperty("elasticsearch.config"))) {
-                    loadFromEnv = false;
-                    settingsBuilder.loadFromPath(environment.configFile().resolve(System.getProperty("elasticsearch.config")));
-                }
+        // TODO: can we simplify all of this and have a single filename, which is looked up in the config dir?
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java]: huge +1

File: core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java [hunk 4]
```diff
@@ -220,37 +238,40 @@ static String randomNodeName(Environment environment) {
...
+                // TODO: why do we remove settings if prompt returns empty??
+                settings.remove(setting);
+            }
+        }
+        for (String setting : textToPrompt) {
+            String textValue = promptForValue(setting, terminal, false);
+            if (Strings.hasLength(textValue)) {
+                settings.put(setting, textValue);
+            } else {
+                // TODO: why do we remove settings if prompt returns empty??
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java]: this deserves a sep issue I guess but good catch

File: core/src/main/java/org/elasticsearch/plugins/PluginsService.java [hunk 5]
```diff
@@ -87,10 +87,10 @@
     /**
      * Constructs a new PluginService
      * @param settings The settings of the system
-     * @param environment The environment of the system
+     * @param pluginsDirectory The directory plugins exist in, or null if plugins should not be loaded from the filesystem
      * @param classpathPlugins Plugins that exist in the classpath which should be loaded
      */
-    public PluginsService(Settings settings, Environment environment, Collection<Class<? extends Plugin>> classpathPlugins) {
+    public PluginsService(Settings settings, Path pluginsDirectory, Collection<Class<? extends Plugin>> classpathPlugins) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/plugins/PluginsService.java]: can we now remove the import `import org.elasticsearch.env.Environment;` here?

**Comment by s1monw** [comment]
left some minors LGTM otherwise

File: core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java (hunk 1 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: I think the only issue with that right now is the last line of the method, which modifies the log file setting to be absolute, after creating the environment.

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: yeah I wonder if we should do this first?

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: well it is using the resolved config dir from the environment...

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: but i agree, this is already breaking. i will move it and simplify as you suggested

**Comment by clintongormley** [comment]
@rjernst could you also add a note to the breaking changes docs please: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_java_api_changes.html

**Comment by s1monw** [comment]
@clintongormley what is the breaking change here?

**Comment by clintongormley** [comment]
@s1monw the fact that the node client now requires a `path.home` setting, which it didn't before.

**Comment by rjernst** [comment]
It's also breaking because the `loadConfigSettings` argument is gone.

@clintongormley I added a note to the migration guide.

**Comment by rjernst** [comment]
@s1monw I updated to remove the extra path.logs setter at the end of prepare. It was only there for logging, so I moved it directly to the logging configurator.

**Comment by s1monw** [comment]
LGTM

**Comment by rjernst** [comment]
2.x commit: 2d698d6
2.0 commit: 5cd65d0

**Comment by mtraynham** [comment]
Just ran into this with an upgrade from 1.7 to 2.2, since we were using `elasticsearch.yml` to config the node name for our TransportClient.

I want to point out that the documentation ([here](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html)) is wrong to suggest you can still do this.

> Or using elasticsearch.yml file as shown in Node Client

**Comment by clintongormley** [comment]
thanks @mtraynham - fixed in https://github.com/elastic/elasticsearch/commit/1769e9b78a5f8c17aa5ca5d8f00916a6ac96cfb8
