### PR TITLE
[ML] Fix .inference index leaking out of tests.

### LINKED ISSUE #114962: [CI] EnrichIT testBasicFlowDate failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4480 / windows-2019_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/waopafpu3xgno)
- [elasticsearch-periodic-platform-support #4470 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/l6ytqsadnucms)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:enrich:qa:rest:javaRestTest" --tests "org.elasticsearch.xpack.enrich.EnrichIT.testBasicFlowDate" -Dtests.seed=DCD5B3F60312E360 -Dtests.locale=se -Dtests.timezone=Africa/Djibouti -Druntime.java=22
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testBasicFlowDate'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.enrich.EnrichIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [DELETE], host [http://127.0.0.1:60512], URI [*,-.ds-ilm-history-*,-.ds-.slm-history-*,-.ds-.watcher-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.inference], but in a future major version, direct access to system indices will be prevented by default]
{"acknowledged":true}
```

**Issue Reasons:**
- [8.x] 2 failures in test testBasicFlowDate (2.6% fail rate in 78 executions)
- [8.x] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by davidkyle**
Many tests in the Enrich and Eql test suites are failing with the error

```
org.elasticsearch.client.WarningFailureException: method [DELETE], host [http://127.0.0.1:37795], URI [*,-.ds-ilm-history-*,-.ds-.slm-history-*,-.ds-.watcher-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.inference], but in a future major version, direct access to system indices will be prevented by default]
{"acknowledged":true}
```

`.inference` is a system index and will be removed automatically when the test clean up code calls the feature reset API (`POST _features/_reset`). The error is occurring when the indices are deleted post feature reset.

https://github.com/elastic/elasticsearch/blob/a182b710eedfba1f837e315e208134ef47cc5a70/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L889

The failing tests all have monitoring enabled `xpack.monitoring.collection.enabled`, when enabled one of the collectors periodically calls the xpack usage API. Xpack usage calls `GET _inference/_all` for the list of inference endpoints. A recent change to the Inference registry persisted the default configurations the first time they read with a GET request which is what the monitoring collector was doing via the xpack uasage API. The GET causes a write to the `.inference` index  which auto creates it causing the warning in delete indices. 

The fix here is to pass a parameter `do not persist` when calling `GET _inference/_all` so that the .inference index is not created by the xpack usage API.

Reverts the change in #114928 to suppress the failures. 

Closes #114962 #114791 #114790 #114789 #114775 #114773 #114771 #114769 #114763 #114761 #114840 #114839 #114773 #114749

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportInferenceUsageAction.java [hunk 1]
```diff
@@ -63,7 +63,7 @@ protected void masterOperation(
         ClusterState state,
         ActionListener<XPackUsageFeatureResponse> listener
     ) {
-        GetInferenceModelAction.Request getInferenceModelAction = new GetInferenceModelAction.Request("_all", TaskType.ANY);
+        GetInferenceModelAction.Request getInferenceModelAction = new GetInferenceModelAction.Request("_all", TaskType.ANY, true);
```
[the remark this answers is not in the document]
Comment (davidkyle) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportInferenceUsageAction.java:66]: .inference is a system index and should be cleaned up by the owning plugin - see SystemIndexPlugin.cleanUpFeature. The test are failing when the clean up code deletes all indices with the wildcard  *, the deletion emits the warning `Warnings: [this request accesses system indices: [.inference]` which fails the test.

The problem is that the .inference index has been recreated between the call to `SystemIndexPlugin.cleanUpFeature` - called by feature reset and the delete all indices request. The culprit is the usages collector that calls GET _inference/* causing the index to be created.

**Comment by davidkyle** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java [hunk 2]
```diff
@@ -34,19 +34,40 @@ public GetInferenceModelAction() {
 
     public static class Request extends AcknowledgedRequest<GetInferenceModelAction.Request> {
 
+        private static boolean DEFAULT_DO_NOT_PERSIST_DEFAULT_CONFIGS = false;
+
         private final String inferenceEntityId;
         private final TaskType taskType;
+        // Default endpoint configurations are persisted on first read.
+        // Set to true to avoid persisting on read.
+        // This setting only applies to GET * requests it has
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java:43]: ... request. It has ...

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java [hunk 3]
```diff
@@ -34,19 +34,40 @@ public GetInferenceModelAction() {
...
+        // no effect when getting a single model
+        private final boolean doNotPersistDefaultConfigs;
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java:45]: In general, I dislike negative boolean variable names. Why not name it `persistDefaultConfig`?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceModelAction.java [hunk 4]
```diff
@@ -100,8 +100,9 @@ private void getSingleModel(
         }));
     }
 
-    private void getAllModels(ActionListener<GetInferenceModelAction.Response> listener) {
+    private void getAllModels(boolean doNotPersistEndpoints, ActionListener<GetInferenceModelAction.Response> listener) {
         modelRegistry.getAllModels(
+            doNotPersistEndpoints == false,
```
Comment (jan-elastic) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceModelAction.java:105]: Why `== false`?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java [hunk 5]
```diff
@@ -34,19 +34,40 @@ public GetInferenceModelAction() {
 
     public static class Request extends AcknowledgedRequest<GetInferenceModelAction.Request> {
 
+        private static boolean DEFAULT_DO_NOT_PERSIST_DEFAULT_CONFIGS = false;
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java:37]: I don't understand why we need this as part of the user-facing request.

At first glance, this is needed to fix some issues with the test setup, which shouldn't lead to changes in production code.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java (hunk 3 above)
Comment (davidkyle) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java]: I flip flopped on this having switched the meaning once already. I'm not sure of the reason why I decided to use the verbose form other that it was friday afternoon. I've renamed to `persistDefaultConfig`

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceModelAction.java (hunk 4 above)
Comment (davidkyle) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceModelAction.java]: See flip flop above. The tests should have caught this but they needed updating to

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java (hunk 5 above)
Comment (davidkyle) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java]: The option is internal to the transport action it cannot be set by an REST API user. The inference usage action however can be called by a REST API user. Xpack telemetry and monitoring also call the usage action.  If the inference API is not being used it is preferable not to create the .inference index, having the flag here stops any callers of the [GET /_xpack/usage](https://www.elastic.co/guide/en/elasticsearch/reference/current/usage-api.html) from indirectly creating the index. It is also very beneficial that this change fixes the tests but even for production code it should not be creating the index if a user calls the usage action.

This entire problem relates to the design decision to persist the default configs on read. The reasons for this design are:
- It is not known until late in the cluster startup lifecycle whether the linux x86 optimised model can be used
- The code should make that decision once and initialise the config with the correct model variant
- Doing this on read rather than at some fixed point in the cluster lifecycle means failures are trivially retried on the next read.

**Comment by davidkyle** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java (hunk 5 above)
Comment (jan-elastic) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/inference/action/GetInferenceModelAction.java]: Thanks, that explanation helps! And I missed that this is internal-only.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceModelAction.java (hunk 4 above)
Comment (jan-elastic) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportGetInferenceModelAction.java]: One benefit of always using the "positive" boolean names is that you never need "flips" like this when passing the variable on.

**Review by jan-elastic — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
@elasticmachine update branch
