### PR TITLE
Change bulk's retry condition to be based on RestStatus

### LINKED ISSUE #28885: Using Java High Level Rest client does not auto-retry Bulk requests
**Elasticsearch version** (`bin/elasticsearch --version`):
Tested on both 5.6 and 6.2

**Plugins installed**: [ None ]

**JVM version** (`java -version`): 1.8.0_31-b13 

**OS version** (`uname -a` if on a Unix-like system): Using the Dockerized version from https://quay.io/repository/pires/docker-elasticsearch

**Description of the problem including expected versus actual behavior**:
(This is pretty much just a copy of my original description at: https://discuss.elastic.co/t/using-java-high-level-rest-client-does-not-auto-retry-bulk-requests/121724)

If the `BulkProcessor` is made to use the High Level Rest Client to issue requests, it is unable to issue retries even though it passes through the `Retry` handler's `canRetry` logic

**Steps to reproduce**:

1. Create an index in ES

1. Configure the thread_pool to limit the bulk requests and make more likely a rejection. In my case I used a very small queue size of 2

1. To demonstrate "expected" functionality, create a `BulkProcessor` which submits requests using `TransportClient`

`BulkProcessor.builder(client, listener);`

1. Submit requests which result in rejection. You will find that the resulting `BulkResponse` does not contain failures (unless `BackoffPolicy` was exhausted), however querying the /_cat/thread_pool will show rejections, and the document count should have went up based on the total submitted, indicating all documents eventually made it via retries. 

1. Create a BulkProcessor which submits requests using the High Level Rest client's client.bulkAsyncmethod:

     ```java
      BulkProcessor.Builder builder(BulkProcessor.Listener listener) {
          return BulkProcessor.builder(client::bulkAsync, listener);
     }

1. Submit requests at a rate to create rejection 

1. Perform the same set of inserts, you will find that the `BulkResponse` contains failures and the individual `Failure` objects have an ElasticsearchException which contain "type=es_rejected_execution_exception"

**Additional Notes**
I think the "root" cause is that with the High Level Rest Client, the `ElasticsearchException` that is extracted is not one of the sub-types such as `EsRejectedExceptionException` (_this is actually documented behavior in the `fromXContent` method of ElasticsearchException_)

I made a naive attempt to modify `fromXContent` to return the correct typed `ElasticsearchException`, but in its current form this results in a deadlock during retry attempts due (I think) to the synchronization that occurs in `BulkProcessor`. You can make it work by setting high enough concurrency but this is a workaround. 

Probably not relevant (except for anyone that might stumble on this same issue): We are using Apache Flink with an Elasticsearch sink. We identified this issue during attempts to upgrade from ES 5.6 to 6.2 to get additional features. However Flink's pending ES6 support is High Level Rest client based, and does not include TransportClient support for 6.2. It has code attempting to perform retries but it is never triggered due to the same issue with typed exceptions (and in fact, would deadlock in any case).

### PR DESCRIPTION
**Pull request by PnPie**
Previously bulk's retry logic was based on the exception type (`EsRejectedExecutionException`) of the failed response, this changes it to be based on RestStatus (`RestStatus.TOO_MANY_REQUESTS`), in order to support rest hight level client. (more information can be found #29254).

Close #28885

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/bulk/Retry.java [hunk 1]
```diff
@@ -40,12 +40,12 @@
...
 public class Retry {
-    private final Class<? extends Throwable> retryOnThrowable;
+    private final RestStatus retryOnStatus;
     private final BackoffPolicy backoffPolicy;
     private final Scheduler scheduler;
 
-    public Retry(Class<? extends Throwable> retryOnThrowable, BackoffPolicy backoffPolicy, Scheduler scheduler) {
-        this.retryOnThrowable = retryOnThrowable;
+    public Retry(RestStatus retryOnStatus, BackoffPolicy backoffPolicy, Scheduler scheduler) {
+        this.retryOnStatus = retryOnStatus;
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry.java]: shall we consider making this hardcoded rather than an argument given that we always pass in the same value for it?

File: server/src/main/java/org/elasticsearch/action/bulk/Retry.java [hunk 2]
```diff
@@ -160,9 +160,8 @@ private boolean canRetry(BulkResponse bulkItemResponses) {
             }
             for (BulkItemResponse bulkItemResponse : bulkItemResponses) {
                 if (bulkItemResponse.isFailed()) {
-                    final Throwable cause = bulkItemResponse.getFailure().getCause();
-                    final Throwable rootCause = ExceptionsHelper.unwrapCause(cause);
-                    if (!rootCause.getClass().equals(retryOnThrowable)) {
+                    final RestStatus status = bulkItemResponse.getFailure().getStatus();
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/bulk/Retry.java]: just to double check: we don't need to unwrap here anymore because the status of the root cause is propagated to its ancestor?

File: server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java [hunk 3]
```diff
@@ -114,9 +114,9 @@ public void afterBulk(long executionId, BulkRequest request, Throwable failure)
                 for (BulkItemResponse bulkItemResponse : bulkResponse.getItems()) {
                     if (bulkItemResponse.isFailed()) {
                         BulkItemResponse.Failure failure = bulkItemResponse.getFailure();
-                        Throwable rootCause = ExceptionsHelper.unwrapCause(failure.getCause());
-                        if (rootCause instanceof EsRejectedExecutionException) {
-                            if (rejectedExecutionExpected == false) {
+                        if (failure.getStatus() == RestStatus.TOO_MANY_REQUESTS) {
+                            if (!rejectedExecutionExpected) {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java]: can you leave the previous `rejectedExecutionExpected == false` please? we prefer this one for readability.

File: server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java [hunk 4]
```diff
@@ -114,9 +114,9 @@ public void afterBulk(long executionId, BulkRequest request, Throwable failure)
...
+                                Throwable rootCause = ExceptionsHelper.unwrapCause(failure.getCause());
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java]: maybe we do not even need to unwrap it here anymore? could we just use getCause instead when throwing assertion error below?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java [hunk 5]
```diff
@@ -0,0 +1,221 @@
...
+import static org.hamcrest.Matchers.lessThan;
+
+public class BulkProcessorRetryIT extends ESRestHighLevelClientTestCase {
+
+    private static final String INDEX_NAME = "index";
+    private static final String TYPE_NAME = "type";
+
+    static {
+        System.setProperty("tests.rest.cluster", "localhost:9200");
+    }
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java]: this static block should go away. I don't see why it's needed.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java [hunk 6]
```diff
@@ -0,0 +1,221 @@
...
+        }
+
+        highLevelClient().indices().refresh(new RefreshRequest());
+        int searchResultCount = highLevelClient().multiGet(multiGetRequest).getResponses().length;
+
+        if (rejectedAfterAllRetries) {
+            assertThat(searchResultCount, lessThan(numberOfAsyncOps));
+        } else {
+            assertThat(searchResultCount, equalTo(numberOfAsyncOps));
+        }
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java]: the assertions seem more accurate here, thanks! Would you mind making the same change in the original test for the transport client? It should work there too right?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java [hunk 7]
```diff
@@ -0,0 +1,221 @@
...
+
+    }
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java]: do you think that we should also have the last check based on the search API and the returned total hits? Or maybe now that we are using multi_get that step is not necessary?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java [hunk 8]
```diff
@@ -0,0 +1,221 @@
...
+                }
+            } else {
+                Throwable t = (Throwable) response;
+                // we're not expecting any other errors
+                throw new AssertionError("Unexpected failure", t);
+            }
+        }
+
+        highLevelClient().indices().refresh(new RefreshRequest());
+        int searchResultCount = highLevelClient().multiGet(multiGetRequest).getResponses().length;
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java]: can you rename this variable, this is not about search anymore, rather the result of multi_get

**Review by javanna — CHANGES_REQUESTED** [review]
looks good @PnPie thanks a lot for opening this! I left a few comments but this is already pretty close.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java (hunk 6 above)
Comment (PnPie) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java]: Yes !

File: client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java (hunk 7 above)
Comment (PnPie) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java]: Yeah, I think the `multi get request` we prepared when we indexed the documents is doing this, the same thing ? do a search (multi get) for all the indices in the end, to compare ? Seems in rest high level tests we are using rather multi get.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry.java (hunk 1 above)
Comment (PnPie) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry.java]: Yes, as it's only used here in bulk for this case.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry.java (hunk 2 above)
Comment (PnPie) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry.java]: Here we get the `status` field of `BulkItemResponse`'s `Failure`, it is a seperate field than `Exception cause` in `Failure` class. So I find it always has the good value (`RestStatus.TOO_MANY_REQUESTS`) ? because the exception type was changed only through `toXContent/fromXContent` of `BulkItemResponse`, but in it the `status` was already parsed seperatly. So the status should always be good ? (except after toXContent/fromXContent, the `BulkItemResponse` was transfered again using `readFrom/writeTo`, which I don't think it's the case ?)

If it's this, I changed `bulkItemResponse.getFailure().getStatus();` to `bulkItemResponse.status();`, because it's the same.

**Review by PnPie — COMMENTED** [review]
@javanna Thank you for your detailed reveiw ! I updated it according to the comments.

File: server/src/main/java/org/elasticsearch/action/bulk/Retry.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/bulk/Retry.java]: I think this is correct. I also don't follow why `readFrom/writeTo` Would cause issues, the exception type does change but the status stays the same right?

File: server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java (hunk 4 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java]: I see that this has not been addressed. Is that on purpose? I see that you have done this on the client version of the test so it should be fine here too.

File: server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java (hunk 3 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorRetryIT.java]: Could you address this please?

**Review by javanna — CHANGES_REQUESTED** [review]
hi @PnPie thanks for addressing the comments, I left a couple more minors, but I see some tests are failing:

```
Tests with failures:
  - org.elasticsearch.client.CrudIT.testBulkProcessorIntegration
  - org.elasticsearch.client.BulkProcessorRetryIT.testBulkRejectionLoadWithBackoff
  - org.elasticsearch.client.BulkProcessorRetryIT.testBulkRejectionLoadWithoutBackoff
  - org.elasticsearch.client.BulkProcessorIT.testBulkProcessorConcurrentRequestsReadOnlyIndex
```

and 

```
Tests with failures:
- org.elasticsearch.action.bulk.RetryTests.testRetryWithListenerBacksOff
- org.elasticsearch.action.bulk.RetryTests.testRetryBacksOff
```

Could you please have a look at these? I am under the impressions that tests were green before recent changes, but I may be wrong, could you please look into this? Let me know if you need any help

**Comment by javanna** [comment]
hi @PnPie would you have a chance to address my last comments? This is a good change, would love to get it in.

**Comment by PnPie** [comment]
Hello @javanna,
Srry for the delay, in fact I had a very quick look last week-end but found a lot of strange things. I just re-check it today and I find I've had made a very ridiculous mistake :( I put the retry condition as `status == RETRY_STATUS -> fail` instead of `status != RETRY_STATUS -> fail` ...
I modified it and checked all the tests you mentioned passes, except `org.elasticsearch.client.BulkProcessorRetryIT` I have a TimeoutException, I feel like it might be my env problem ? So can we launch a test with jenkins to have a look ?

**Comment by javanna** [comment]
test this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
@PnPie tests were failing but not sure the failures were related to your changes, I merged master in and triggered a new build.

**Comment by PnPie** [comment]
Hi @javanna,
Yes, seems sometimes `org.elasticsearch.action.bulk.BulkProcessorRetryIT` fails after adding the `rejectedAfterAllRetries` changes. I can look at it this week-end.

**Comment by PnPie** [comment]
Hello @javanna,
I updated the PR and seems previously `BulkProcessorRetryIT` fails sometimes because we didn't take account of the "no retry (no back off)" situation. In this case when there is no retry for bulk request, the indexed docs could be equal to number of docs in bulk request (when there is no failures), or less than the number of docs in bulk request (when there is failures). I changed it as this.

**Review by javanna — APPROVED** [review]
thanks @PnPie LGTM . As far as I can see the timeout exceptions are caused by another bug, see #24069 . It's great that we can finally reproduce it consistently. I will merge your PR once I fixed that other bug.

**Comment by javanna** [comment]
For the record, this requires #30384 otherwise the added tests fail.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
thanks a lot @PnPie !

**Comment by jpountz** [comment]
@javanna This may be backported now.
