### PR TITLE
Don't apply the rewrite-as-range optimization if field is multivalued

### LINKED ISSUE #82903: Data histogram aggregation issue for arrays field
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0 - 7.16.3

**Plugins installed**: [Netty4Plugin.class, PainlessPlugin.class, CommonAnalysisPlugin.class, ParentJoinPlugin.class]

**JVM version** (`java -version`): 11.0.13

**OS version** (`uname -a` if on a Unix-like system):Darwin Kernel Version 21.2.0 and on windows 10

**Description of the problem including expected versus actual behavior**:
During the upgrade from 7.10.2 to 7.16.3 I encounter the issue with date histogram aggregation for the arrays field. Aggregated buckets are displayed after query, but if I select one then the rest are gone. 
To explaining behavioral I will based on document with array field `"date":["2021-05-01","2021-04-01"]`. 
I expect that when I made a query with date aggregation by month and on `date` field for that document then I got, as a result, two buckets: `2021-05` and `2021-04`. Which is working as expected. The issue here is when I select one of the buckets as a filter then as result I didn't got the second bucket. This is unexpected because the given document matches also the second filter. In version `<=7.10.2` it's working as expected. 

Current behavioral break facet approach in search driven application. It is intended behavior or a bug?

**Steps to reproduce**:
1. Create doc 
```
POST test/_doc
{
  "date":["2021-05-01","2021-04-01","2021-04-22"]
} 
```
2. Make a search request with filter (doesn't work in 7.16.3, but works in 7.10.2)
```
GET test/_search?q=date:2021-04-01
{
  "aggs": {
    "NAME": {
      "date_histogram": {
        "field": "date",
        "interval": "1M"
      }
    }
  }
}
```

3. Make a search request with range filter (work, but is a kinda workaround)
```
GET test/_search?q=date:[2021-04-01 TO 2021-08-01]
{
  "aggs": {
    "NAME": {
      "date_histogram": {
        "field": "date",
        "interval": "1M"
      }
    }
  }
}
```

I checked for other types, an issue occurs only for `date` type.

### PR DESCRIPTION
**Pull request by not-napoleon**
resolves https://github.com/elastic/elasticsearch/issues/82903

This fixes a subtle bug when rewriting date histogram aggregations into range aggregations, which is the step before applying filter-by-filters.  When there is a filter query, we can use that to build range buckets that should mirror the date histogram results.  But, in the case of multi-valued fields, one value can match the filter (thus including the document) but another value might fall outside the range.  In the "default" date histogram logic, this will create two buckets, but in the range re-write, it does not because we never generate a range covering the second bucket.

This fixes the problem by disabling the optimization when we see multivalued fields (based on the points size).

### CODE REVIEW

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/bwc

File: server/src/main/java/org/elasticsearch/search/aggregations/support/AggregationContext.java [hunk 1]
```diff
@@ -221,6 +222,16 @@ public final AggregationUsageService getUsageService() {
...
     public abstract SubSearchContext subSearchContext();
 
+    /**
+     *  Check if the given field is multivalued
+     *
+     * @param field Name of the field to check
+     * @return true if the field contians multiple indexed values
+     */
+    public boolean isMultiValued(String field) throws IOException {
+        return PointValues.size(searcher().getIndexReader(), field) > PointValues.getDocCount(searcher().getIndexReader(), field);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/support/AggregationContext.java:232]: This is only going to work on a points field - it should probably throw if the field doesn't have points. Because it's just not the right kind of field.

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/support/AggregationContext.java:237]: I think it's worth keeping the size in a variable so you don't have to do it twice. It looks fairly fast but we may as well not do it twice.

File: server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java [hunk 2]
```diff
@@ -310,8 +310,17 @@ public ValuesSource getField(FieldContext fieldContext, AggregationScript.LeafFa
...
                     }
 
-                    // Check the query for bounds
-                    if (context.query() != null) {
+                    boolean isMultiValue;
+                    try {
+                        isMultiValue = context.isMultiValued(fieldContext.field());
+                    } catch (AggregationExecutionException ex) {
+                        // If we can't check, don't agressively disable the optimization
+                        isMultiValue = false;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java:318]: Do we hit this case when the field is declared but is empty?

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java:318]: I suppose if the field isn't searchable the query wouldn't find anything. But it might just not be indexed. Or empty. I guess. I'm not sure `false` is right here - but maybe it doesn't matter because we never get here. If that's the case, can we just throw?

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java [hunk 3]
```diff
@@ -416,6 +438,8 @@ public String typeName() {
         return value();
     }
 
+    public static final Logger log = LogManager.getLogger(CoreValuesSourceType.class);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java:441]: I think this belongs at the top of the file.

**Review by nik9000 — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java (hunk 3 above)
Comment (not-napoleon) [reply server/src/main/java/org/elasticsearch/search/aggregations/support/CoreValuesSourceType.java:441]: This is an enum, not a class, so I can't put it at the top.  The enum constants need to be defined first.  I can put it a couple lines higher if you think that will be better.

**Comment by not-napoleon** [comment]
@elasticmachine update branch
