### PR TITLE
Track cancellable tasks by parent ID

### LINKED ISSUE #75316: Performance regression starting from 7.8.0 when too many search requests closes before getting result
**Elasticsearch version** (`bin/elasticsearch --version`):
`7.10.2`

**Plugins installed**: []

**JVM version** (`java -version`):
```
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
`Linux HOSTNAME 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
After the upgrade of the ES from 7.6.2 to 7.10.2 one of our clusters become degraded a lot in terms of latency and throughput. After a big and long investigation, I [found the suspect](https://github.com/elastic/elasticsearch/commit/61e5350e770966172cd64430661eeb903bc94518). It looks like starting from 7.8.0, we have this performance regression, even in the latest 7.13.3.
Our cluster has a unique workload that is used mainly for testing purposes. We are evaluating ElasticSearch as a DB backed for our app, and to gather some performance metrics in the long run, we have a "shadow traffic," which has mirror requests from our production app to ES, but if the gateway can get a response faster from its main data source than from ES, it will close request, and Nginx shows that as 499 status code. As a side-effect, I can't use almost any /_cat API requests. This is the example:

```
$ > time curl -sS localhost:9200/_cat/tasks | awk '{print $1}' | sort | uniq -c
0.01user 0.15system 6:01.05elapsed 0%CPU (0avgtext+0avgdata 1232maxresident)k
0inputs+0outputs (0major+350minor)pagefaults 0swaps
 256591 cluster:admin/tasks/cancel
   2243 cluster:admin/tasks/cancel[n]
     23 cluster:monitor/nodes/info
     39 cluster:monitor/nodes/stats
      1 cluster:monitor/stats
     18 cluster:monitor/tasks/lists
     83 cluster:monitor/tasks/lists[n]
 121370 indices:data/read/msearch
 121370 indices:data/read/search
     10 indices:data/read/search[can_match]
      3 indices:data/read/search[phase/fetch/id]
    141 indices:data/read/search[phase/query]
   2243 internal:admin/tasks/ban
``` 

While cluster has a load of search requests - I can't get much from it. Latency skyrockets from 400ms(99 percentile) to 20seconds - 120seconds ( 99percentile ) 

**Steps to reproduce**:

I was able to write [simple script](https://gist.github.com/libbkmz/199891acb668f6fff6a677d47f29b85d) which can reproduce the issue, unfortunately, one active instance is not enough, and to simulate our real production shadow workload, I have had to run 5 instances to get stuck in [setBan method](https://github.com/elastic/elasticsearch/blob/v7.10.2/server/src/main/java/org/elasticsearch/tasks/TaskManager.java#L354). Also, I'm attaching java flame graph captured by async-profiler for this particular problem. [es_setban_bug.flamegraph.html.gz](https://github.com/elastic/elasticsearch/files/6812577/es_setban_bug.flamegraph.html.gz)

Moreover, I don't know how good our search query parameters, but this one is very intensive, and we have a lot of queries like this, and I'm able to reproduce the issue with such a simple script. 

Our cluster has 83 nodes in total, with 73 of data nodes, 3 master nodes, and 6 proxy nodes. However, we found some issues with our hardware, and we were using only 1 proxy node for more than 2 months. So, all the ES requests come to a single ES instance with flags `it` only on version 7.10.2. But using more than 1 proxy node doesn't help at all - the outcome is the same...

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today when cancelling a task with its descendants we perform a linear
scan through all the tasks looking for the few that have the right
parent ID. With potentially hundreds of thousands of tasks this takes
quite some time, particularly if there are many tasks to cancel.

This commit introduces a second map that tracks the tasks by their
parent ID so that it's super-cheap to find the descendants that need to
be cancelled.

Closes #75316

### CODE REVIEW

**Comment by DaveCTurner** [comment]
My biggest concern with this right now is the `can_match` phase of a search which I believe will make a child task of the same parent for every shard on a node. That might be hundreds of shards, and updating the new map is O(N^2) in the number of children. It might be ok since these tasks are handled directly on the transport worker thread which naturally limits the concurrency (to 6 by default) but that seems pretty implicit. It'd be awfully nice if we batched these up at the node level instead tho.

**Comment by DaveCTurner** [comment]
I wrote a simple benchmark:

<details>

```
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

package org.elasticsearch.benchmark.tasks;

import org.elasticsearch.common.Randomness;
import org.elasticsearch.tasks.CancellableTask;
import org.elasticsearch.tasks.CancellableTasksTracker;
import org.elasticsearch.tasks.Task;
import org.elasticsearch.tasks.TaskId;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Param;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import static java.util.Collections.emptyMap;

@Warmup(iterations = 5)
@Measurement(iterations = 7)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Fork(value = 1)
public class CancellableTasksTrackerBenchmark {

    @Param({"30000", "3000", "300", "30", "3"})
    private int parentCount;

    @Param({"1000", "100", "10", "1"})
    private int childCountPerParent;

    private List<BenchmarkTask> benchmarkTasks;
    private CancellableTasksTracker<String> cancellableTasksTracker;
    private TaskId targetParent;

    @Setup
    public void createTasks() {
        final int taskCount = parentCount * childCountPerParent;
        benchmarkTasks = new ArrayList<>(taskCount);
        for (int i = 0; i < taskCount; i++) {
            benchmarkTasks.add(new BenchmarkTask(i % parentCount, i / parentCount, i));
        }
        Randomness.shuffle(benchmarkTasks);
        cancellableTasksTracker = new CancellableTasksTracker<>(String.class, String[]::new);
        targetParent = new TaskId("node", parentCount / 2);
    }

    @Benchmark
    public long trackTasks() {
        for (BenchmarkTask benchmarkTask : benchmarkTasks) {
            cancellableTasksTracker.put(benchmarkTask.task, benchmarkTask.payload);
        }

        final long count = cancellableTasksTracker.getByParent(targetParent).count();

        if (count != childCountPerParent) {
            throw new AssertionError("wrong count: " + count);
        }

        for (BenchmarkTask benchmarkTask : benchmarkTasks) {
            cancellableTasksTracker.remove(benchmarkTask.task);
        }

        return count;
    }

    private static class BenchmarkTask {
        final int parentIndex;
        final int childIndex;
        final Task task;
        final String payload;

        public BenchmarkTask(int parentIndex, int childIndex, long taskId) {
            this.parentIndex = parentIndex;
            this.childIndex = childIndex;
            this.task = new CancellableTask(taskId, "test", "action", "", new TaskId("node", parentIndex), emptyMap());
            this.payload = "task-" + taskId + "-child-" + childIndex + "-parent-" + parentIndex;
        }
    }
}
```
</details>

These times track adding and then removing all the tasks; even with 30000 parent tasks each with 1000 child tasks the mean overhead per task is ~2.2µs.

```
Benchmark                                    (childCountPerParent)  (parentCount)  Mode  Cnt            Score            Error  Units  Mean overhead
CancellableTasksTrackerBenchmark.trackTasks                   1000          30000  avgt    7  67980271397.429 ± 4994967681.178  ns/op        2266 ns
CancellableTasksTrackerBenchmark.trackTasks                   1000           3000  avgt    7   4569715417.524 ± 2111582392.913  ns/op        1523 ns
CancellableTasksTrackerBenchmark.trackTasks                   1000            300  avgt    7    246249754.634 ±    2054156.379  ns/op         820 ns
CancellableTasksTrackerBenchmark.trackTasks                   1000             30  avgt    7     21136582.188 ±    4286645.660  ns/op         704 ns
CancellableTasksTrackerBenchmark.trackTasks                   1000              3  avgt    7      1602687.020 ±      67016.293  ns/op         534 ns
CancellableTasksTrackerBenchmark.trackTasks                    100          30000  avgt    7   3136513434.357 ±   92213951.212  ns/op        1045 ns
CancellableTasksTrackerBenchmark.trackTasks                    100           3000  avgt    7    120281883.393 ±    4909672.536  ns/op         400 ns
CancellableTasksTrackerBenchmark.trackTasks                    100            300  avgt    7      8515642.306 ±     442334.003  ns/op         283 ns
CancellableTasksTrackerBenchmark.trackTasks                    100             30  avgt    7       587387.451 ±      27483.477  ns/op         195 ns
CancellableTasksTrackerBenchmark.trackTasks                    100              3  avgt    7        47650.830 ±        587.080  ns/op         158 ns
CancellableTasksTrackerBenchmark.trackTasks                     10          30000  avgt    7    142939788.670 ±    9858893.675  ns/op         476 ns
CancellableTasksTrackerBenchmark.trackTasks                     10           3000  avgt    7      5624404.751 ±     386408.517  ns/op         187 ns
CancellableTasksTrackerBenchmark.trackTasks                     10            300  avgt    7       425179.307 ±      13136.734  ns/op         141 ns
CancellableTasksTrackerBenchmark.trackTasks                     10             30  avgt    7        37709.674 ±       2988.665  ns/op         125 ns
CancellableTasksTrackerBenchmark.trackTasks                     10              3  avgt    7         3535.776 ±        173.179  ns/op         117 ns
CancellableTasksTrackerBenchmark.trackTasks                      1          30000  avgt    7      4452360.723 ±     494622.243  ns/op         148 ns
CancellableTasksTrackerBenchmark.trackTasks                      1           3000  avgt    7       391214.089 ±      18580.306  ns/op         130 ns
CancellableTasksTrackerBenchmark.trackTasks                      1            300  avgt    7        46769.278 ±      16795.350  ns/op         155 ns
CancellableTasksTrackerBenchmark.trackTasks                      1             30  avgt    7         3648.374 ±        468.714  ns/op         121 ns
CancellableTasksTrackerBenchmark.trackTasks                      1              3  avgt    7          385.357 ±         30.390  ns/op         128 ns
```

**Comment by DaveCTurner** [comment]
I reverted the "optimisation" for the one-item case because the same benchmark indicates it's actually slightly slower, even in the runs when there's only one child task per parent.

```
(childCountPerParent)  (parentCount)  Mode  Cnt            Score            Error  Units  Mean overhead
                 1000          30000  avgt    7  67134033515.714 ± 5033933634.050  ns/op        2238 ns
                 1000           3000  avgt    7   4236755545.619 ±   61234713.992  ns/op        1412 ns
                 1000            300  avgt    7    232844652.583 ±    4661204.334  ns/op         776 ns
                 1000             30  avgt    7     18675622.451 ±     560322.362  ns/op         623 ns
                 1000              3  avgt    7      1530250.913 ±      14278.994  ns/op         510 ns
                  100          30000  avgt    7   2956281942.714 ±   62127970.363  ns/op         985 ns
                  100           3000  avgt    7    104351606.728 ±    1645461.830  ns/op         348 ns
                  100            300  avgt    7      7655082.583 ±     103660.312  ns/op         255 ns
                  100             30  avgt    7       521039.197 ±      18967.814  ns/op         174 ns
                  100              3  avgt    7        43946.254 ±        266.907  ns/op         146 ns
                   10          30000  avgt    7    145160690.114 ±    3963524.892  ns/op         484 ns
                   10           3000  avgt    7      5117603.806 ±     187243.301  ns/op         171 ns
                   10            300  avgt    7       421472.832 ±      11077.558  ns/op         140 ns
                   10             30  avgt    7        36384.819 ±        814.380  ns/op         121 ns
                   10              3  avgt    7         3518.711 ±        177.121  ns/op         117 ns
                    1          30000  avgt    7      4274559.294 ±      70630.509  ns/op         142 ns
                    1           3000  avgt    7       389427.491 ±       8577.194  ns/op         130 ns
                    1            300  avgt    7        36697.487 ±        666.284  ns/op         122 ns
                    1             30  avgt    7         3421.890 ±        103.902  ns/op         114 ns
                    1              3  avgt    7          366.648 ±          3.457  ns/op         122 ns
```

**Comment by DaveCTurner** [comment]
The version in 76ed88962f3 is a slight improvement at larger child counts and ~no difference otherwise.

```
(childCountPerParent)  (parentCount)  Mode  Cnt            Score            Error  Units  Mean overhead
                 1000          30000  avgt    7  57538573339.000 ± 1104612283.253  ns/op        1918 ns
                 1000           3000  avgt    7   4003685036.000 ±  198740962.106  ns/op        1335 ns
                 1000            300  avgt    7    219989120.589 ±    8365899.700  ns/op         733 ns
                 1000             30  avgt    7     16874024.911 ±     193951.882  ns/op         562 ns
                 1000              3  avgt    7      1327812.381 ±      80334.396  ns/op         443 ns
                  100          30000  avgt    7   2852655991.393 ±   57674477.573  ns/op         951 ns
                  100           3000  avgt    7    119850366.740 ±    1403569.814  ns/op         400 ns
                  100            300  avgt    7      7668485.509 ±     136576.566  ns/op         256 ns
                  100             30  avgt    7       472136.967 ±      13905.206  ns/op         157 ns
                  100              3  avgt    7        37112.812 ±        177.624  ns/op         124 ns
                   10          30000  avgt    7    140966921.858 ±    1561421.755  ns/op         470 ns
                   10           3000  avgt    7      5151352.980 ±     280335.160  ns/op         172 ns
                   10            300  avgt    7       397245.162 ±       8335.522  ns/op         132 ns
                   10             30  avgt    7        34949.180 ±        800.483  ns/op         116 ns
                   10              3  avgt    7         3360.763 ±        178.012  ns/op         112 ns
                    1          30000  avgt    7      4236124.666 ±     139988.026  ns/op         141 ns
                    1           3000  avgt    7       415290.801 ±       4607.121  ns/op         138 ns
                    1            300  avgt    7        37496.980 ±        983.645  ns/op         125 ns
                    1             30  avgt    7         3541.204 ±        295.871  ns/op         118 ns
                    1              3  avgt    7          378.129 ±          8.648  ns/op         126 ns
```

File: server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+            }
+
+            actionThread = new Thread(() -> {
+                awaitStart.run();
+
+                state.incrementAndGet();
+                tracker.put(task, item);
+                state.incrementAndGet();
+
+                state.incrementAndGet();
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java:64]: I am not entirely sure we would ever see state==2 in other threads, I would think it would be ok for the JVM to optimize it away.

This is possibly even true for the entire `actionThread` since there is no synchronization with the watch threads here. The watch threads may only see the the final output. I would advocate a yield should help, but that is outside JMM I think.

File: server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+                    assertSame(item, removed);
+                }
+
+                assertNull(tracker.remove(task));
+            }, "action-thread-" + item);
+
+            watchThread = new Thread(() -> {
+                awaitStart.run();
+
+                for (int i = 0; i < 10; i++) {
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java:77]: Should this not always run at least until state.get() ==4 (and then another round)?

File: server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+
+        for (TestTask task : tasks) {
+            task.start();
+        }
+
+        for (TestTask task : tasks) {
+            task.join();
+        }
+    }
+}
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java:174]: I think we should also check the more trivial case where no parent id is set.

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+    public CancellableTasksTracker(T[] empty) {
+        assert empty.length == 0;
+        this.empty = empty;
+    }
+
+    private final Map<Long, T> byTaskId = ConcurrentCollections.newConcurrentMapWithAggressiveConcurrency();
+    private final Map<TaskId, T[]> byParentTaskId = ConcurrentCollections.newConcurrentMapWithAggressiveConcurrency();
+
+    /**
+     * Add an item for the given task. Should only be called once for each task.
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:34]: Also add a comment that items must be unique per task.

**Review by henningandersen — COMMENTED** [review]
This looks great. Left a few comments around testing.

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+
+    private final T[] empty;
+
+    public CancellableTasksTracker(T[] empty) {
+        assert empty.length == 0;
+        this.empty = empty;
+    }
+
+    private final Map<Long, T> byTaskId = ConcurrentCollections.newConcurrentMapWithAggressiveConcurrency();
+    private final Map<TaskId, T[]> byParentTaskId = ConcurrentCollections.newConcurrentMapWithAggressiveConcurrency();
```
Comment (arteam) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:31]: Does it make sense to store tasks as `List<T>` instead of `T[]` for the clarity sake if we don't do any specific optimizations? We could simplify code by relying on the `List` API for copying and inserting data instead of `Arrays.copyOf` and `Arrays.copyOfRange`

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+import java.util.Map;
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.stream.Stream;
+
+/**
+ * Tracks items that are associated with cancellable tasks, supporting efficient lookup by task ID and by parent task ID
+ */
+public class CancellableTasksTracker<T> {
+
+    private final T[] empty;
```
Comment (arteam) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:23]: Can `empty` be a constant? It doesn't seems to modified anywhere and it's used in `Arrays.copyOf`.

File: server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java:64]: Ah, an earlier iteration had some assertions in between these calls. In theory you're right that it would be legitimate for the compiler to collapse these tests to something fairly trivial, but in practice they do cover many interleavings and the other threads do indeed observe `state==2` cases. Just try adding bugs :) I'll add a `yield` anyway.

File: server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java:77]: I found that this sometimes noticeably added to the test runtime, we spent ages doing this loop before actually doing the useful work. Again, in practice this covers what we care about.

File: server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/tasks/CancellableTasksTrackerTests.java:174]: Maybe I misunderstand, I think we already do?

```
                    rarely() ? TaskId.EMPTY_TASK_ID : randomFrom(parentTaskIds),
```

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 4 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:34]: ++ although I'm not sure that's true, I believe we handle duplicates ok?

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:31]: I didn't find a better `List<T>`-based implementation myself, but I'm open to ideas. Would you pull this branch, flesh out your suggestion, push it to your fork and then link to it here?

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:23]: Again I didn't find a way to do so, but you're welcome to show me how :)

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:33]: Yes I don't think we can express any true invariants very easily; I added an eventually-true assertion in 9554f12527d2253f43ac6858f126a56b4d445582.

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 6 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:25]: Why does this have to be a generic, `T == CancellableTaskHolder` is the only use case we have isn't it?

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 5 above)
Comment (arteam) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:33]: @DaveCTurner Pushed it here! https://github.com/arteam/elasticsearch/commit/a2bdcfbd80b37f509586f4aadf7922dab8da909e

**Review by original-brownbear — APPROVED** [review]
LGTM (dropping the generic may be a nit but I can see how it's more fun to have it for tests)

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 5 above)
Comment (arteam) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:33]: We can also potentially use `merge` instead of `compute` to make the addition operation more concise https://github.com/elastic/elasticsearch/commit/a50401fa7b5f77b7c638f624b27b89ea619f002c

Comment (arteam) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:33]: We can also consider using `merge` instead of `concat` for Lists to make the addition operation more concise 
https://github.com/arteam/elasticsearch/commit/a50401fa7b5f77b7c638f624b27b89ea619f002c

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:33]: The benchmarks indicate that a2bcdfb is a few nanoseconds quicker for the 1-child case but quite substantially slower otherwise (I skipped the 30k-parent cases because they add a lot to the runtime for no real benefit):

```
(childCountPerParent)  (parentCount)  Mode  Cnt            Score           Error  Units  Mean overhead
                 1000          30000                     SKIPPED
                 1000           3000  avgt    7  25940199095.000 ± 142227031.895  ns/op        8647 ns     
                 1000            300  avgt    7   2392018166.114 ±  30498397.694  ns/op        7973 ns     
                 1000             30  avgt    7    218739912.786 ±   1249128.187  ns/op        7291 ns     
                 1000              3  avgt    7     22607793.973 ±    111531.112  ns/op        7536 ns     
                  100          30000                     SKIPPED
                  100           3000  avgt    7    418881040.660 ±  20161249.132  ns/op        1396 ns     
                  100            300  avgt    7     35457186.201 ±    417486.108  ns/op        1182 ns     
                  100             30  avgt    7      3033577.940 ±     97236.034  ns/op        1011 ns     
                  100              3  avgt    7       299040.083 ±     18249.359  ns/op         997 ns     
                   10          30000                     SKIPPED
                   10           3000  avgt    7     12848626.628 ±    235736.397  ns/op         428 ns     
                   10            300  avgt    7       855412.478 ±      5594.042  ns/op         285 ns     
                   10             30  avgt    7        82910.096 ±      2885.424  ns/op         276 ns     
                   10              3  avgt    7         7580.669 ±        28.137  ns/op         253 ns     
                    1          30000                     SKIPPED
                    1           3000  avgt    7       302676.158 ±      8294.205  ns/op         101 ns     
                    1            300  avgt    7        29608.966 ±       889.803  ns/op          99 ns     
                    1             30  avgt    7         2935.642 ±        42.769  ns/op          98 ns     
                    1              3  avgt    7          310.498 ±         1.610  ns/op         103 ns     
```

This code is on a fairly hot path, every time a search touches a shard it will register and unregister a cancellable task for instance, a cluster could be handling thousands of searches per second each touching thousands of shards, so I think it's worth dropping to the raw arrays even if it is a bit harder to read.

I'd also be concerned about the additional memory usage and GC workload, we're making and growing an `ArrayList` in each `.stream().filter(item -> item != oldItem).collect(Collectors.toList())`, which adds quite some overhead, although I will admit I haven't measured this.

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 6 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:25]: > I don't think it makes a performance difference. I could be persuaded.

Nah there isn't any difference I think lets leave it as is then IMO :)

File: server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java (hunk 5 above)
Comment (arteam) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTasksTracker.java:33]: That sounds alright! I think it totally makes sense to use raw arrays in hot paths :+1:

**Review by arteam — APPROVED** [review]
