### PR TITLE
test(TestInferenceService): prevent negative embedding values

### LINKED ISSUE #133453: [CI] ShardBulkInferenceActionFilterIT testRestart {p0=false p1=true} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10241 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/fglvst5752ehg)
- [elasticsearch-periodic-platform-support #10192 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gj5chrresofpm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:internalClusterTest" --tests "org.elasticsearch.xpack.inference.action.filter.ShardBulkInferenceActionFilterIT.testRestart {p0=false p1=true}" -Dtests.seed=9641C2BAED105BC7 -Dtests.locale=sd -Dtests.timezone=Asia/Taipei -Druntime.java=24
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.action.filter.ShardBulkInferenceActionFilterIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRestart%20%7Bp0%3Dfalse%20p1%3Dtrue%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failed to index document MGfUuDdINcJupKXdXHRZ: org.elasticsearch.index.mapper.DocumentParsingException: [1:772] failed to parse field [_inference_fields] of type [_inference_fields] in document with id 'MGfUuDdINcJupKXdXHRZ'. Preview of field's value: 'null'
```

**Issue Reasons:**
- [9.1] 2 failures in test testRestart {p0=false p1=true} (1.1% fail rate in 179 executions)
- [9.1] 2 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mromaios**
Closes https://github.com/elastic/elasticsearch/issues/133453

This PR fixes edge cases where the generated test embeddings could become negative.
- `Math.abs` can overflow when the provided int is `Integer.MIX_VALUE` causing a negative embedding value
- The expression `<abs(hashCode)> + 1 + position` was computed as an `int` which can also overflow if the absolute value is close to `Integer.MAX_VALUE`

### CODE REVIEW

File: x-pack/plugin/inference/qa/test-service-plugin/src/main/java/org/elasticsearch/xpack/inference/mock/TestSparseInferenceServiceExtension.java [hunk 1]
```diff
@@ -191,7 +191,7 @@ protected ServiceSettings getServiceSettingsFromMap(Map<String, Object> serviceS
 
         private static float generateEmbedding(String input, int position) {
             // Ensure non-negative and non-zero values for features
-            return Math.abs(input.hashCode()) + 1 + position;
+            return Integer.toUnsignedLong(input.hashCode()) + 1 + position;
```
Comment (Mikep86) [inline x-pack/plugin/inference/qa/test-service-plugin/src/main/java/org/elasticsearch/xpack/inference/mock/TestSparseInferenceServiceExtension.java]: This change is likely causing test failures because these embedding values are used in tests that evaluate result ordering. Can we do something else here that will not change the value of existing embeddings that don't roll over?

Comment (mromaios) [reply x-pack/plugin/inference/qa/test-service-plugin/src/main/java/org/elasticsearch/xpack/inference/mock/TestSparseInferenceServiceExtension.java]: Yep, that was my guess as well. Will revisit. Thanks Mike

Comment (mromaios) [reply x-pack/plugin/inference/qa/test-service-plugin/src/main/java/org/elasticsearch/xpack/inference/mock/TestSparseInferenceServiceExtension.java]: Fixed in https://github.com/elastic/elasticsearch/pull/136806/commits/b103dd860973f591fb3a685b9da3313a64b80cc9

was also missing another potential overflow 😅

**Review by Mikep86 — APPROVED** [review]
LGTM! Can we also backport this as far back as 8.19? This test code has been around for a while and it's only a matter of time until get failures for those releases as well.

**Comment by mromaios** [comment]
> LGTM! Can we also backport this as far back as 8.19? This test code has been around for a while and it's only a matter of time until get failures for those releases as well.

Sure, on it.

**Comment by mromaios** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/136855)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/136856)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/136857)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/136858)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
