### PR TITLE
ESQL: Update mechanism for under construction data types

### LINKED ISSUE #135193: ESQL: data types transitioning from unsupported to supported fail queries
If a data type, like `dense_vector`, is currently unsupported, fields of that type can still be used in queries. The output will be populated with nulls, and you cannot use the field in expressions, but you can `KEEP` it.

Now, if we start supporting the new data type, new nodes will definitely start to actually extract the field from the index, and the output will have the appropriate type. But during rolling upgrades, and in CCS setups, remote nodes may still treat the data type as unsupported.

This means that `FROM idx | KEEP unsupported_field` will now start to fail even though it was just returning `null`s before, because the `FieldAttribute` representing `unsupported_field` will now have a data type that may not even be present on older remote nodes - like 8.19 nodes, which are perfectly acceptable in CCS setups.

### PR DESCRIPTION
**Pull request by alex-spies**
Close https://github.com/elastic/elasticsearch/issues/135193

Follow-up to https://github.com/elastic/elasticsearch/pull/135215

Fix the test expectations for our `AllSupportedFieldsIT`s according to https://github.com/elastic/elasticsearch/pull/135215#discussion_r2378700820.

Additionally, clean up our mechanism and docs for "under construction" data types:
1. For SNAPSHOT builds, go back to the old status quo where all types are considered supported and we just skip tests based on capabilities.
2. Re-brand the `CreatedVersion` for data types to `SupportedVersion`. For release builds, it doesn't matter when serialization code for a type was introduced; it matters only when it was actually released, and this is generally (much) later than when the serialization code for the type was written.
3. Make the `SupportedVersion` non-optional in the data type builder, so that we don't accidentally mark a new data type as "supported on all versions" in the future.
4. Remove the old feature-flag based system for marking types as "under construction" as we don't plan to use feature flags, but minimum transport versions to determine if a remote node/cluster supports a type.

Point 1. prevents having to update existing capabilities when a new type is released (which was required for https://github.com/elastic/elasticsearch/pull/135604 and https://github.com/elastic/elasticsearch/pull/135213) and thus gives a little bit of extra safety by keeping bwc tests intact (even if they technically test versions that don't officially support a type, yet).

Point 4. is lining up our data type system for https://github.com/elastic/elasticsearch/issues/131108.

# Some context on under-construction data types

We have data types that are considered under construction until they are released. Older nodes may not know these types at all (not able to deserialize), or they may know them but not actually support them.

Previously, we had a feature flag-based mechanism that would determine if a type is supported or not. Unfortunately, we do not check the feature flags on remote nodes and clusters, so this mechanism alone doesn't work; moreover, it leads to broken queries when the coordinator considers a type supported, but a remote node can't even deserialize it. The remote node will then not participate in simple queries like `FROM logs-*` and be counted as partial failure, even though it participated just fine in the past, when the data type was considered unsupported.

That was fixed for the `aggregate_metric_double` and `dense_vector` types, specifically, in the workaround https://github.com/elastic/elasticsearch/pull/135215; these types now require the query to contain functions or commands that are only available when the types are actually released, otherwise we still consider these types as unsupported.

Of course, that's not a long term solution. Long term, we want to consider types as supported if the minimum transport version of all participating nodes is at least the version when the type was declared released. This is https://github.com/elastic/elasticsearch/issues/131108. (See the ongoing work in https://github.com/elastic/elasticsearch/pull/135633).

### CODE REVIEW

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+        public String toString() {
+            return "UnderConstruction";
+        }
+    };
+
+    static SupportedVersion supportedOn(TransportVersion supportedVersion) {
+        return new SupportedVersion() {
+            @Override
+            public boolean supports(TransportVersion version) {
+                return version.supports(supportedVersion) || Build.current().isSnapshot();
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java:80]: This is a subtle change that considers released types supported on snapshot builds, always.

Similarly, under construction types are also always considered supported on snapshot builds.

I thought about making a distinction between "created at version" and "supported from version", but that wouldn't really add anything as we already have capabilities to control the behavior of bwc tests in snapshot builds.

Comment (nik9000) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java:80]: I'm good with just having the supported from version.

It does feel weird to say that released types are always supported on snapshots though.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java [hunk 2]
```diff
@@ -795,9 +794,9 @@ public static ArgSignature paramWithoutAnnotation(String name) {
      * Remove types that are being actively built.
      */
     private static String[] removeUnderConstruction(String[] types) {
-        for (Map.Entry<DataType, FeatureFlag> underConstruction : DataType.UNDER_CONSTRUCTION.entrySet()) {
-            if (underConstruction.getValue().isEnabled() == false) {
-                types = Arrays.stream(types).filter(t -> underConstruction.getKey().typeName().equals(t) == false).toArray(String[]::new);
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java:800]: I suppose you could pass the feature flag into the under construction `SupportVersion` variant and use the enabled/disabled-ness of the feature flag. I'm wondering whether a `createdVersion` AND a `featureFlag` might be the right thing here. It's more work when you make a new data type, but it feels a little more true.

**Comment by justzh** [comment]
This seems like a business issue.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java:80]: I'll add a comment to explain that this is so that we don't break a bunch of existing tests when finally enabling a type.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java:800]: I guess you could have a feature-flag based override to enable under-construction types outside of SNAPSHOT; e.g. so that folks toying around with in-development data types could enable them on their local cluster (and live with the fact that queries might break in unexpected ways, esp. if connected to a remote cluster that may not enable the same feature flag).

That said, we currently have no under construction types anymore, so that would complicate the system for no gain. But I could leave a comment in place so that future-us will know how to do that.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java:80]: Added some javadoc.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java:800]: Added a comment.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java [hunk 3]
```diff
@@ -120,19 +114,20 @@
  *         EsqlDataTypeConverter#commonType, individual function type checking, the
  *         verifier rules, or other places. We suggest starting with CSV tests and
  *         seeing where they fail.</li>
+
```
Comment (nik9000) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java]: Extra

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/SupportedVersion.java:80]: :+1:

This is an interesting compromise that makes tests flow more nicely. We don't discard any backwards compatibility tests that we wrote while working on the new type. That's good. But those tests *might* be guaranteeing more backwards compatibility than we actually offer in production. That's ok. And it makes it explicit when we disable that backward compatibility. All good.

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java]: Oh right.

I think it's fine to remove *just that* and not wait on the whole CI to run again before merging - that's what I'm gonna do.

**Comment by justzh** [comment]
test
