### PR TITLE
ILM: fix searchable snapshot action to wait for the restored index

### LINKED ISSUE #67879: [CI] Failure in SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment
This failed a couple of times last week:

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment" -Dtests.seed=901F56500B783268 -Dtests.security.manager=true -Dtests.locale=ms -Dtests.timezone=America/Virgin -Druntime.java=8
```

fails as:

```
org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT > testSearchableSnapshotForceMergesIndexToOneSegment FAILED
    org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:45419], URI [/_snapshot/XssEL/2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q], status line [HTTP/1.1 503 Service Unavailable]
    {"error":{"root_cause":[{"type":"concurrent_snapshot_execution_exception","reason":"[XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA] cannot delete snapshot during a restore in progress in [RestoreInProgress[{TYgVzEj7TKi-wUKD9xMPYA}{XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA}]]"}],"type":"concurrent_snapshot_execution_exception","reason":"[XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA] cannot delete snapshot during a restore in progress in [RestoreInProgress[{TYgVzEj7TKi-wUKD9xMPYA}{XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA}]]"},"status":503}
        at __randomizedtesting.SeedInfo.seed([901F56500B783268:3EC09A4B54875623]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeSnapshots(ESRestTestCase.java:757)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:584)
        at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:344)
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)
```

See https://gradle-enterprise.elastic.co/s/xqc5p6ffe7fby/console-log/raw

Does not reproduce locally.

### PR DESCRIPTION
**Pull request by andreidan**
This fixes a bug in `WaitForIndexColorStep` which was not waiting for the
restored index to be `GREEN` but it was checking the original/managed index.

This has the potential of ILM moving forward with the `searchable_snapshot` action
and deleting the original index, whilst the restored index is not fully restored
and allocated, yielding a possible **search** downtime.

Fixes #67879

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java [hunk 1]
```diff
@@ -75,17 +75,26 @@ public boolean equals(Object obj) {
 
     @Override
     public Result isConditionMet(Index index, ClusterState clusterState) {
-        String indexName = indexNamePrefix != null ? indexNamePrefix + index.getName() : index.getName();
-        IndexMetadata indexMetadata = clusterState.metadata().index(index);
```
Comment (andreidan) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java:79]: The problem originated here as we don't use the computed `indexName` but the original `index`

**Comment by andreidan** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java [hunk 2]
```diff
@@ -75,17 +75,26 @@ public boolean equals(Object obj) {
...
-
-        if (indexMetadata == null) {
+        // check if the original (managed) index still exists
+        if (clusterState.metadata().index(index) == null) {
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java:79]: I'm not sure why we need to ensure the original index also exists? Otherwise it seems strange to say "wait for shrink-foo to be green" that fails if "foo" doesn't exist.

I think we can just deal with the next `if` statement, since it would check either the prefixed or non-prefixed version depending on if a prefix were specified?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java [hunk 3]
```diff
@@ -75,17 +75,26 @@ public boolean equals(Object obj) {
...
             logger.debug(errorMessage);
             return new Result(false, new Info(errorMessage));
         }
 
+        String indexName = indexNamePrefix != null ? indexNamePrefix + index.getName() : index.getName();
+        IndexMetadata indexMetadata = clusterState.metadata().index(indexName);
+        // check if the (potentially) derived index exists
+        if (indexMetadata == null) {
+            String errorMessage = String.format(Locale.ROOT, "[%s] lifecycle action for index [%s] executed but the target index [%s] " +
+                    "no longer exists",
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java:92]: I think it's confusing for this to be in past tense since it could be that we checked too early (the index doesn't exist *yet*), so minor suggestion to change it to:

```suggestion
                    "does not exist",
```

**Review by dakrone — COMMENTED** [review]
I left a comment, I think we don't need the double-checking, we can only check the single index whose color we are asserting.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java (hunk 2 above)
Comment (andreidan) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForIndexColorStep.java:79]: Yes, that's a good point. 

My reasoning here is that we might be in an inconsistent state as the managed index was deleted but the target index isn't. The next steps would silently not execute and there will be no settings and execution state copied to the target index. 
I believe the user can end up with a GREEN target index that's not managed by ILM and doesn't have the identity of the original index (when this step is used in the `searchable_snapshot` context). 

I think we should flag this situation but I agree the messaging might be confusing

**Review by dakrone — APPROVED** [review]
LGTM, great job tracking this down!
