### PR TITLE
Extend timeout in `IngestGeoIpClientYamlTestSuiteIT`

### LINKED ISSUE #138460: [CI] IngestGeoIpClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11451 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/6h4yztdjxqsky)
- [elasticsearch-periodic-platform-support #11443 / ubuntu-2404-aarch64_checkrestcompat_platform-support-arm](https://gradle-enterprise.elastic.co/s/oe45vgi7cejri)

**Reproduction Line:**
```
./gradlew ":modules:ingest-geoip:yamlRestCompatTest" --tests "org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT.test {yaml=ingest_geoip/20_geoip_processor/Test geoip processor with lists, first only}" -Dtests.seed=6C5CDC64CB8FC1B7 -Dtests.locale=gu-Gujr-IN -Dtests.timezone=Australia/Adelaide -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <4>
     but: was <3>
```

**Issue Reasons:**
- [9.1] 2 failures in class org.elasticsearch.ingest.geoip.IngestGeoIpClientYamlTestSuiteIT (2.8% fail rate in 71 executions)
- [9.1] 2 failures in step ubuntu-2404-aarch64_checkrestcompat_platform-support-arm (66.7% fail rate in 3 executions)
- [9.1] 2 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
Some slow CI test clusters are not able to download all four GeoIP databases within 10 seconds, so we bump the timeout to 20 seconds.

See #138460 for a more detailed analysis.

Fixes #138460
Fixes #138502

### CODE REVIEW

File: modules/ingest-geoip/src/yamlRestTest/java/org/elasticsearch/ingest/geoip/IngestGeoIpClientYamlTestSuiteIT.java [hunk 1]
```diff
@@ -158,7 +159,8 @@ static void assertDatabasesLoaded() throws Exception {
 
             // ensure that the extra config database has been set up, too:
             assertThat(node.get("config_databases"), equalTo(List.of("asn.mmdb")));
-        });
+            // Downloading all four databases may take some time, so we set a longer timeout here.
+        }, 20, TimeUnit.SECONDS);
```
Comment (szybia) [inline modules/ingest-geoip/src/yamlRestTest/java/org/elasticsearch/ingest/geoip/IngestGeoIpClientYamlTestSuiteIT.java:164]: nit: if i was writing this, i'd even go up to 30 seconds to make it more likely will never have to be touched again and won't false-positive again

**Review by szybia — APPROVED** [review]

File: modules/ingest-geoip/src/yamlRestTest/java/org/elasticsearch/ingest/geoip/IngestGeoIpClientYamlTestSuiteIT.java (hunk 1 above)
Comment (nielsbauman) [reply modules/ingest-geoip/src/yamlRestTest/java/org/elasticsearch/ingest/geoip/IngestGeoIpClientYamlTestSuiteIT.java:164]: I intentionally didn't go up to 30 seconds, as I feel like it's worth looking into ways to speed up the test if it really takes that long to download 4 databases.

Comment (szybia) [reply modules/ingest-geoip/src/yamlRestTest/java/org/elasticsearch/ingest/geoip/IngestGeoIpClientYamlTestSuiteIT.java:164]: in that case, comment to document this thinking so next person doesn't just ++ the timeout (unlikely but just in case)? 🙏

**Comment by nielsbauman** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/138642)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/138645)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/138646)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
