### PR TITLE
Do not run TickerScheduleTriggerEngine watches if the schedule trigger engine is paused

### LINKED ISSUE #105933: Watcher executes on a node after the .watches shard has been moved to a different node
### Elasticsearch Version

8.8.2 (but likely others as well)

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

This happens only rarely, but I have seen evidence of it twice in the same cluster a few days apart. As part of normal shard reallocation, a `.watches` shard gets moved off of a node (I'll call it `nodeA`) and onto another node (`nodeB`). This ought to mean that nodeA stops running watches. And we see in nodeA's logs:
```
paused watch execution, reason [no local watcher shards found], cancelled [0] queued tasks
```
But if we search `.watcher-history-*`, we see that now both nodeA and nodeB are executing the same watch, at nearly the same time on the same schedule. So instead of getting executed once every 10 minutes (for example), the watch gets executed twice every 10 minutes.
Aside from the message above, I haven't seen anything relevant in the logs. Restarting the nodes solves the problem.

### Steps to Reproduce

Unknown

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by masseyke**
This changes watcher to bail out of executing triggered watches if the watcher engine is paused. It fixes the problem described in https://github.com/elastic/elasticsearch/issues/105933#issuecomment-2093624251
Closes #105933

### CODE REVIEW

**Comment by masseyke** [comment]
Some notes on the things I've tried so far in this PR:

1. **Fail when a watch is added to TickerScheduleTriggerEngine when the engine is paused**: Several tests failed when I did this. I believe all the tests were single-node though. It looks like the problem is that on startup we pause/restart watcher, and we expect any watches added during that time to be executed.
2. **Ignore any watches added to TickerScheduleTriggerEngine when the engine is paused**: As expected (based on what I found above), some tests failed because watches never ran as expected. SmokeTestWatcherWithSecurityIT.testSearchTransformHasPermissions() is an example. Nothing ever appeared in watcher history.
3. **Fail when we are executing a watch in TickerScheduleTriggerEngine when the engine is paused**. I am guessing that none of our existing tests will regularly hit this. I have a stress test locally though that I am hoping will trigger it. If this is the case, then it might be a good fix to just bail out of execution when we detect this.

**Review by nielsbauman — APPROVED** [review]

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java [hunk 1]
```diff
@@ -81,17 +85,22 @@ public synchronized void start(Collection<Watch> jobs) {
...
-    public synchronized void pauseExecution() {
+    public void pauseExecution() {
+        logger.debug("Pausing engine");
+        isRunning.set(false);
         schedules.clear();
     }
 
     @Override
     public void add(Watch watch) {
+        logger.debug("Adding watch [{}] to engine (engine is running: {})", watch.id(), isRunning.get());
```
Comment (jakelandis) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java:103]: might want to make this a trace level message since this could result in thousands of log messages.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java [hunk 2]
```diff
@@ -81,17 +85,22 @@ public synchronized void start(Collection<Watch> jobs) {
...
+        logger.debug("Stopping engine");
+        isRunning.set(false);
         schedules.clear();
         ticker.close();
     }
 
     @Override
-    public synchronized void pauseExecution() {
+    public void pauseExecution() {
+        logger.debug("Pausing engine");
```
Comment (jakelandis) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java:96]: might want to make these engine state changes stop/start/pause at info level. Debug can be very verbose, and I think these are worthy of info.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java [hunk 3]
```diff
@@ -106,13 +115,25 @@ public void add(Watch watch) {
...
+            logger.debug(
+                "Watcher not running because the engine is paused. Currently scheduled watches being skipped: {}",
+                schedules.size()
+            );
+            return;
+        }
         long triggeredTime = clock.millis();
         List<TriggerEvent> events = new ArrayList<>();
         for (ActiveSchedule schedule : schedules.values()) {
+            if (isRunning.get() == false) {
```
Comment (jakelandis) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java:133]: should this be moved a bit lower to the notify listeners and only notify them if it is running (else log the message) ? as-is there is not much difference between how race-like this can be. I think preventing the core action would help a bit more with the race like conditions.

**Review by jakelandis — APPROVED** [review]
This creates more of an implicit coupling between the unpause and start methods. Ideally we would not introduce another boolean to represent the running state since there are already way too many of them and more state is more hard w.r.t. race conditions. I would have a preference to wire in the ExecutionService#pause boolean, even it requires an awkward setter to a boolean supplier. That would allow the same logic but without additional booleans or more coupling. 

I don't think the changes here will cause issues, but also not sure if they will fix the race condition. Also, as-is there is only a very, very small window of difference between clearing the schedules. I will approve it since the the log messages will help and the addtional state won't hurt, but think it could be a bit more optimal.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java (hunk 3 above)
Comment (masseyke) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/engine/TickerScheduleTriggerEngine.java:133]: There were a couple of reasons I did it here instead:
(1) I was trying to modify as little code as possible to avoid introducing some new bug or making things worse
(2) The real problem (in my opinion) isn't if a single event happens to slip through after the `.watches` shard has been moved -- it's that we just keep running events until the end of time. This bails out pretty quickly once the `.watches` shard has been moved.

**Comment by masseyke** [comment]
> I don't think the changes here will cause issues, but also not sure if they will fix the race condition.

I am not 100% sure that this will fix the issues either. But without these changes I can repeatably cause the race condition, and with them I have not been able to.

>  Also, as-is there is only a very, very small window of difference between clearing the schedules.

I think that this is why it happens fairly rarely in the wild and is so hard to reproduce. But if it does happen, the impact is pretty bad -- the watch will continue to run forever.
