### PR TITLE
Fix test: sync index shard to ensure we have the latest global checkp…

### LINKED ISSUE #124447: [CI] IndexStatsIT testFilterCacheStats failing
**Build Scans:**
- [elasticsearch-periodic #6887 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/t4sjpm4i7qr5s)
- [elasticsearch-pull-request #60929 / part-1](https://gradle-enterprise.elastic.co/s/b7h6w6gbm4gva)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indices.stats.IndexStatsIT.testFilterCacheStats" -Dtests.seed=6D428E2B759773A9 -Dtests.locale=lkt-Latn-US -Dtests.timezone=America/Mexico_City -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indices.stats.IndexStatsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testFilterCacheStats),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <1L>
     but: was <-1L>
```

**Issue Reasons:**
- [main] 2 failures in test testFilterCacheStats (0.4% fail rate in 506 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by michalborek**
After adding a method responsible for syncing the in-memory and persisted global checkpoint we directly called engine to get the max seq no. This sequence number might be ahead of the global checkpoint and then an error is triggered.

I changed the helper method to sync the global checkpoint before.

Closes: #124447

### CODE REVIEW

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by michalborek** [comment]
Thanks @tlrx, unfortunately this was also failing so I made another attempt and use the former approach with comparing the last known vs synced global checkpoints. I run it on a remote machine with 50 successes (vs almost immediate failure with a max seq no). 

Take a look at this please, since I remember some doubts about using the last known global checkpoint.

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 1]
```diff
@@ -236,7 +235,9 @@ public static void persistGlobalCheckpointOnPrimaryShards(InternalTestCluster cl
                             equalTo(true)
                         );
 
-                        final var globalCheckpoint = indexShard.withEngine(Engine::getMaxSeqNo);
+                        indexShard.sync();
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: `indexShard.sync()` should just be redundant given we call `syncGlobalCheckpoint` below. Or did you find something specific it does that `syncGlobalCheckpoint` doesn't cover?

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: I may be missing something, but I think the inner loop do not actually filter on only the indexShards from the "index"  index

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 2]
```diff
@@ -236,7 +235,9 @@ public static void persistGlobalCheckpointOnPrimaryShards(InternalTestCluster cl
                             equalTo(true)
                         );
 
-                        final var globalCheckpoint = indexShard.withEngine(Engine::getMaxSeqNo);
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:239]: I'm not sure I fully understand yet how `getMaxSeqNo` can diverge from the primary's global checkpoint when there are no replicas. Based on my understanding so far, the flow (seqNo assignment -> replication -> primary global checkpoint update) is synchronous and completes before the client ack. If that's correct, this discrepancy shouldn't happen by the time the test calls this helper. I wonder if we might be missing a piece of the puzzle. Perhaps something at engine open time?

Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:239]: Hm, I'm not sure I fully understand it, either :)

If I undertsand correctly, the maxSeqNo is the latest operation executed, while the globalCheckpoint defines the latest operation executed where all the previous operations are also executed (no gaps). 

so in case of op1 (finished), op2 (running), op3 (finished),
Then the max seq no would be on op3 while global checkpoint would be on op1.

Does it make sense?

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 1 above)
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: Thanks Ines, this one may be redundant in this case (it's a leftover from the former commit). I will run some tests to confirm that.

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: That's true, any index that's available on the node that has the "index" index is there... This is clearly not an intended behavior

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 2 above)
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:239]: Sorry, you mentioned that all tasks should already be completed, so no gaps are expected... let me think why this diverges, because it clearly does

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: Fixed!

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 1 above)
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: I removed that, because I have a similar understanding to yours.

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 2 above)
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:239]: It's getting interesting when I started logging what's happening in the failing tests:

1. using seq max no (no sync() before):
```
shard [index][4]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0                                                                                                                                                                                                                  
shard [index][6]: maxSeqNo=0, processedCP=0, persistedCP=-1, globalCheckpoint=-1, activeOps=0    
```
2. using seq max no (with sync() before):
```
shard [index][2]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0                                                                                                                                                                                                                  
shard [index][4]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0                                                                                                                                                                                                                    
shard [index][6]: maxSeqNo=0, processedCP=0, persistedCP=0, globalCheckpoint=-1, activeOps=0  
```   

We can clearly see a lag, and the sync solves only a problem of the local checkpoint (this is the `persistedCP`)

Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:239]: When adding even more logs:
```
ReplicationTracker.updateLocalCheckpoint: shard=[index][6], allocationId=zlwxJcssTAOZ0DllYw3lnw, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
ReplicationTracker.updateLocalCheckpoint: shard=[index][6], allocationId=zlwxJcssTAOZ0DllYw3lnw, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
ReplicationTracker.updateLocalCheckpoint: shard=[index][5], allocationId=u7n84s2qQwSIrNtyiUQ8Dg, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
ReplicationTracker.updateLocalCheckpoint: shard=[index][3], allocationId=I2rtJWTGQnKrbDx21L6xYQ, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
ReplicationTracker.updateLocalCheckpoint: shard=[index][3], allocationId=I2rtJWTGQnKrbDx21L6xYQ, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
ReplicationTracker.updateLocalCheckpoint: shard=[index][1], allocationId=Jtvpy_yCRwe1CARoCjaIDQ, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
ReplicationTracker.updateLocalCheckpoint: shard=[index][1], allocationId=Jtvpy_yCRwe1CARoCjaIDQ, localCheckpoint=-1, previous=-1, globalCheckpoint=-1                                                                                                                                                              
shard [index][4]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0, durability=ASYNC                                                                                                                                                                                                  
shard [index][2]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0, durability=ASYNC                                                                                                                                                                                                  
shard [index][0]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0, durability=ASYNC                                                                                                                                                                                                  
shard [index][8]: maxSeqNo=-1, processedCP=-1, persistedCP=-1, globalCheckpoint=-1, activeOps=0, durability=ASYNC                                                                                                                                                                                                  
shard [index][6]: maxSeqNo=0, processedCP=0, persistedCP=0, globalCheckpoint=-1, activeOps=0, durability=ASYNC 
```
We can see the updateLocalCheckpoint is never called for value `0` on `shard 6`.

When synced that manually:
```
                        indexShard.updateLocalCheckpointForShard(
                            indexShard.routingEntry().allocationId().getId(),
                            indexShard.getLocalCheckpoint()  
                        );
```

the test started passing with the maxSeqNo value

Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:239]: The test (before changes) passes where durability == REQUEST but fails on ASYNC.

So, the indexShard() sync ensures the local checkpoint is processed while the updateLocalCheckpointForShard updates the ReplicationTracker.

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 3]
```diff
@@ -221,11 +221,14 @@ public static void persistGlobalCheckpointOnPrimaryShards(String index) {
...
      */
-    public static void persistGlobalCheckpointOnPrimaryShards(InternalTestCluster cluster, String index) {
+    public static void persistGlobalCheckpointOnPrimaryShards(InternalTestCluster cluster, String index) throws IOException {
         final var future = new PlainActionFuture<Void>();
         try (var listeners = new RefCountingListener(future)) {
             for (String node : cluster.nodesInclude(index)) {
                 for (IndexService indexService : cluster.getInstance(IndicesService.class, node)) {
+                    if (indexService.index().getName().equals(index) == false) {
+                        continue;
+                    }
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:235]: Alternatively, if we wanted to avoid looping and explicitly handle the case when the index does not exist, I think we could do:
```
final var index = cluster.clusterService().state().metadata().getProject().index(indexName);
// here, deal with whether the index exists explicitly
for (String node : cluster.nodesInclude(indexName)) {
    final var indexService = cluster.getInstance(IndicesService.class, node).indexServiceSafe(index);
    for (IndexShard indexShard : indexService) {
...
```

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 1 above)
Comment (inespot) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: For future ref, see: https://github.com/elastic/elasticsearch/pull/146507#discussion_r3100762222

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 4]
```diff
@@ -235,8 +238,16 @@ public static void persistGlobalCheckpointOnPrimaryShards(InternalTestCluster cl
                             indexShard.routingEntry().active(),
                             equalTo(true)
                         );
+                        indexShard.sync(); // sync to ensure local checkpoint is processed
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: Nit: could we group this next to `indexShard.updateLocalCheckpointForShard` and document the async-durability flow? Eg:
```
  /// Synchronously ensure durability in case `index.translog.durability = [ASYNC]`
  ///
  /// 1. `sync()` the translog; the engine’s persisted local checkpoint catches up on the calling thread.
  /// 2. `updateLocalCheckpointForShard`: aligns `ReplicationTracker` with that checkpoint. When
  ///    the tracked local checkpoint increases, the tracker runs `updateGlobalCheckpointOnPrimary()`.
  /// 3. `syncGlobalCheckpoint` persist the global checkpoint, which relies on the tracker being up to date
```

**Review by inespot — APPROVED** [review]
Lgtm with some small requests!
Could we also run the test 3000+ times before merging to make sure we have not missed any other race? 🙏

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 3 above)
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:235]: I didn't know that one :) Thanks!
