### PR TITLE
Always write empty role descriptor fields to index

### LINKED ISSUE #110416: [CI] RoleWithDescriptionRestIT testCreateOrUpdateRoleWithDescription failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/tftzbhgjfyyhi/tests/:x-pack:plugin:security:qa:security-trial:javaRestTest/org.elasticsearch.xpack.security.role.RoleWithDescriptionRestIT/testCreateOrUpdateRoleWithDescription

**Reproduction line:**
```
./gradlew ':x-pack:plugin:security:qa:security-trial:javaRestTest' --tests "org.elasticsearch.xpack.security.role.RoleWithDescriptionRestIT.testCreateOrUpdateRoleWithDescription" -Dtests.seed=5E23800DD8ABD74F -Dtests.locale=ar-SY -Dtests.timezone=Indian/Cocos -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.security.role.RoleWithDescriptionRestIT#testCreateOrUpdateRoleWithDescription`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCreateOrUpdateRoleWithDescription'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.security.role.RoleWithDescriptionRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <{role_with_description=Role[name=role_with_description, cluster=[all], global=[], indicesPrivileges=[IndicesPrivileges[indices=[index-*], allowRestrictedIndices=[false], privileges=[all], ],], applicationPrivileges=[], runAs=[], metadata=[{}], remoteIndicesPrivileges=[], remoteClusterPrivileges=[], restriction=Restriction[workflows=[]], description=]}>
     but: was <{role_with_description=Role[name=role_with_description, cluster=[all], global=[], indicesPrivileges=[IndicesPrivileges[indices=[index-*], allowRestrictedIndices=[false], privileges=[all], ],], applicationPrivileges=[], runAs=[], metadata=[{}], remoteIndicesPrivileges=[], remoteClusterPrivileges=[], restriction=Restriction[workflows=[]], description=FtJAwrK]}>

  at __randomizedtesting.SeedInfo.seed([5E23800DD8ABD74F:164AD461D59AB823]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2332)
  at org.elasticsearch.xpack.security.SecurityOnTrialLicenseRestTestCase.fetchRoleAndAssertEqualsExpected(SecurityOnTrialLicenseRestTestCase.java:188)
  at org.elasticsearch.xpack.security.role.RoleWithDescriptionRestIT.testCreateOrUpdateRoleWithDescription(RoleWithDescriptionRestIT.java:59)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

### PR DESCRIPTION
**Pull request by jfreden**
Resolves: https://github.com/elastic/elasticsearch/issues/110416

A RoleDescriptor's `toXContent` function doesn't serialize some fields that are not set. This currently works because when we do an update, we will always overwrite the full RoleDescriptor in the index to make sure fields that are not set, will be updated properly. 

In the bulk role update, we use an upsert, that combined with not knowing what fields are set leads to us not clearing fields that are set to nothing in requests. To fix that we have some alternatives: 
- Change to do an index request instead of update request and always overwrite the whole doc. 
- Serialize the full RoleDescriptor when we write to the index to make sure all fields are as expected. 

If we go with the first alternative, we can't leverage the noop functionality of the upsert anymore and for large volumes of roles being written, we would do a lot of unnecessary IO to write to the Lucene index. Since this is the expected behaviour of the Connectors project, I'm hesitant to going down that path. 

This PR explores the second alternative to write empty fields for: 
- `runAs`
- `remoteIndices`
- `remoteCluster`
- `description`

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStore.java [hunk 1]
```diff
@@ -607,16 +608,41 @@ private DeleteRequest createRoleDeleteRequest(final String roleName) {
...
         assert NativeRealmValidationUtil.validateRoleName(role.getName(), false) == null
             : "Role name was invalid or reserved: " + role.getName();
         assert false == role.hasRestriction() : "restriction is not supported for native roles";
-        return role.toXContent(
-            jsonBuilder(),
-            ToXContent.EMPTY_PARAMS,
-            true,
-            featureService.clusterHasFeature(clusterService.state(), SECURITY_ROLES_METADATA_FLATTENED)
-        );
+
```
Comment (jfreden) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStore.java:616]: I went back and forth on this but landed on that the cleanest approach is to handle the special case for the security index defaults and `metadata_flattened` logic here. 

Simply using the `docCreation` is `true` is not enough since it's also used in the [ApiKeyService](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ApiKeyService.java#L2028) in a couple of places, to create role descriptors. Since we don't do the same upsert operations on api keys, the default values are not needed and the `metadata_falttened` field is not needed. This could be fixed by providing a couple of extra parameters to `toXContent` or a context object of some sort, that would need to be populated by all callers. In the end this turned in to many booleans, instead of actually doing the logic where we have all the context. 

The downside with this approach is that the role descriptor logic is now spread out.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStoreTests.java [hunk 2]
```diff
@@ -807,6 +809,62 @@ public void testBulkDeleteReservedRole() {
         verify(client, times(0)).bulk(any(BulkRequest.class), any());
     }
 
+    /**
+     * Make sure all top level fields for a RoleDescriptor have default values to make sure they can be set to empty in an upsert
+     * call to the roles API
+     */
+    public void testAllTopFieldsHaveEmptyDefaultsForUpsert() throws IOException, IllegalAccessException {
```
Comment (jfreden) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStoreTests.java:816]: The purpose of this test is to catch any new top level role descriptor fields that do not provide defaults since it's easy to forget to add that and there is no guarantee that a regular unit test would catch that.

File: x-pack/plugin/security/qa/security-trial/src/javaRestTest/java/org/elasticsearch/xpack/security/role/BulkPutRoleRestIT.java [hunk 3]
```diff
@@ -181,15 +181,74 @@ public void testPutNoValidRoles() throws Exception {
     public void testBulkUpdates() throws Exception {
         String request = """
             {"roles": {"test1": {"cluster": ["all"],"indices": [{"names": ["*"],"privileges": ["all"]}]}, "test2":
-            {"cluster": ["all"],"indices": [{"names": ["*"],"privileges": ["read"]}]}, "test3":
-            {"cluster": ["all"],"indices": [{"names": ["*"],"privileges": ["write"]}]}}}""";
-
+            {"cluster": ["all"],"indices": [{"names": ["*"],"privileges": ["read"]}], "description": "something"}, "test3":
```
Comment (jfreden) [inline x-pack/plugin/security/qa/security-trial/src/javaRestTest/java/org/elasticsearch/xpack/security/role/BulkPutRoleRestIT.java:184]: Added some more explicit validation that we can reset some top level fields. These things are already implicitly caught by other tests but I think it's nice to do some more validation.

**Comment by jfreden** [comment]
Serverless CI Failure is unrelated: 
```
java.lang.AssertionError: java.lang.IllegalStateException: Blob store is null
```

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Comment by albertzaharovits** [comment]
In the description you mention `runAs` but that already implements a default of [] when serialized by `RoleDescriptor#toXContent` right?

**Comment by jfreden** [comment]
Yes, there is a check if [runAs != null](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java#L451) and exclude it if it is, but [runAs](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java#L186) is never `null` as far as I can see.
