### PR TITLE
Correctly encode warning headers

### LINKED ISSUE #27244: ES 5.3.0 Crash with carriage return in indexed field
ES 5.3.0 Crashes because of an unhandled exception from Netty when building the Warning response header with a deprecation message containing a field with a carriage return.

When indexing a message containing a field with a carriage return, such as
`{
	"\r_xyz": "",
       ...
}`

And with a deprecated dynamic mapping template such as
`'dynamic_templates'  => [{
                            'string_fields'      => {
                                'mapping'            => {
                                    'fielddata'    => {
                                        'format'       => 'disabled'
                                    }
                                    ,
                                    'index'        => 'analyzed',
                                    'omit_norms'   => true,
                                    'type'         => 'string',
                                    'fields'       => {
                                        'raw'          => {
                                            'ignore_above' => 256,
                                            'index'        => 'not_analyzed',
                                            'type'         => 'string',
                                        }
                                    }
                                }
                                ,
                                'match_mapping_type' => 'string',
                                'match'              => '*'
                            }
                        }
                        ],
                }`

ES 5.3.0 crashes with the following exception:

> java.lang.IllegalArgumentException: only '\n' is allowed after '\r': 299 Elasticsearch-5.3.0-3adb13b "The [string] field is deprecated, please use [text] or [keyword] instead on [^M_xyz]" "Tue, 28 Oct 2017 10:21:14 GMT"
                at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.validateValueChar(DefaultHttpHeaders.java:454) ~[?:?]
                at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:411) ~[?:?]
                at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:402) ~[?:?]
                at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:318) ~[?:?]
                at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.setHeaderField(Netty4HttpChannel.java:160) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.setHeaderField(Netty4HttpChannel.java:155) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.addCustomHeaders(Netty4HttpChannel.java:181) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.sendResponse(Netty4HttpChannel.java:114) ~[?:?]
                at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:445) ~[elasticsearch-5.3.0.jar:5.3.0]

Full exception:

> [ERROR][o.e.r.a.RestResponseListener] failed to send failure response
java.lang.IllegalStateException: Channel is already closed
        at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.close(RestController.java:451) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:444) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:49) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:368) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onResponse(TransportBulkAction.java:349) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onResponse(TransportBulkAction.java:338) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishOnSuccess(TransportReplicationAction.java:855) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:765) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:751) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1025) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1098) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1088) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1078) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:111) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$2.onResponse(TransportReplicationAction.java:348) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$2.onResponse(TransportReplicationAction.java:342) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryResult.respond(TransportReplicationAction.java:414) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.respondIfPossible(TransportWriteAction.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.respond(TransportWriteAction.java:118) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$onResponse$0(TransportReplicationAction.java:320) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation.finish(ReplicationOperation.java:305) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation.decPendingAndFinishIfNeeded(ReplicationOperation.java:286) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation.access$100(ReplicationOperation.java:55) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:190) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:186) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1025) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:1386) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1378) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1347) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-5.3.0.jar:5.3.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.7.Final.jar:4.1.7.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
        Suppressed: java.lang.IllegalArgumentException: only '\n' is allowed after '\r': 299 Elasticsearch-5.3.0-3adb13b "The [string] field is deprecated, please use [text] or [keyword] instead on [^M_xyz]" "Tue, 28 Oct 2017 10:21:14 GMT"
                at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.validateValueChar(DefaultHttpHeaders.java:454) ~[?:?]
                at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:411) ~[?:?]
                at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:402) ~[?:?]
                at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:318) ~[?:?]
                at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.setHeaderField(Netty4HttpChannel.java:160) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.setHeaderField(Netty4HttpChannel.java:155) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.addCustomHeaders(Netty4HttpChannel.java:181) ~[?:?]
                at org.elasticsearch.http.netty4.Netty4HttpChannel.sendResponse(Netty4HttpChannel.java:114) ~[?:?]
                at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:445) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:368) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onResponse(TransportBulkAction.java:349) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onResponse(TransportBulkAction.java:338) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishOnSuccess(TransportReplicationAction.java:855) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:765) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:751) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1025) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1098) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1088) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1078) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:111) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$2.onResponse(TransportReplicationAction.java:348) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$2.onResponse(TransportReplicationAction.java:342) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryResult.respond(TransportReplicationAction.java:414) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.respondIfPossible(TransportWriteAction.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportWriteAction$WritePrimaryResult.respond(TransportWriteAction.java:118) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$onResponse$0(TransportReplicationAction.java:320) ~[elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.ReplicationOperation.finish(ReplicationOperation.java:305) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.ReplicationOperation.decPendingAndFinishIfNeeded(ReplicationOperation.java:286) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.ReplicationOperation.access$100(ReplicationOperation.java:55) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:190) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.support.replication.ReplicationOperation$1.onResponse(ReplicationOperation.java:186) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1025) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:1386) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1378) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1347) [elasticsearch-5.3.0.jar:5.3.0]
                at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-5.3.0.jar:5.3.0]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.7.Final.jar:4.1.7.Final]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

### PR DESCRIPTION
**Pull request by jasontedor**
The warnings headers have a fairly limited set of valid characters (cf. quoted-text in RFC 7230). While we have assertions that we adhere to this set of valid characters ensuring that our warning messages do not violate the specificaion, we were neglecting the possibility that arbitrary user input would trickle into these warning headers. Thus, missing here was tests for these situations and encoding of characters that appear outside the set of valid characters. This commit addresses this by encoding any characters in a deprecation message that are not from the set of valid characters.

Closes #27244

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/common/logging/DeprecationLoggerTests.java [hunk 1]
```diff
@@ -71,6 +72,54 @@ public void testAddsHeaderWithThreadContext() throws IOException {
...
+
+            final Map<String, List<String>> responseHeaders = threadContext.getResponseHeaders();
+
+            assertThat(responseHeaders.size(), equalTo(1));
+            final List<String> responses = responseHeaders.get("Warning");
+            assertThat(responses, hasSize(1));
+            assertThat(responses.get(0), warningValueMatcher);
+
+            // convert UTF-16 to UTF-8 by hand to show the hard-coded constant below is correct
+            assertThat("😱", equalTo("\uD83D\uDE31"));
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/common/logging/DeprecationLoggerTests.java]: any chance we can specify this using the \u notation and not have crazy chars in the code?

**Review by bleskes — APPROVED** [review]
LGTM. I left some optional suggestions. I do have two higher level comments:
1) Where did you find this encoding? I can't find it in the specification?
2) I wonder if we should make things simpler - assert our messages are always ASCII and always encode into utf8, converting to % syntax if a char is 128? Since it seems unicode field names will anyway be encoded, I think we will end up having the same end result and the code will be much simpler, no?

**Comment by jasontedor** [comment]
> Where did you find this encoding? I can't find it in the specification?

As we discussed, percent encoding is fairly common (for example, percent encoding of URIs). The specification does not require a specific encoding, only that the characters in the warning header fall in a certain character set which we ensure with this encoding.

> I wonder if we should make things simpler - assert our messages are always ASCII and always encode into utf8, converting to % syntax if a char is 128? Since it seems unicode field names will anyway be encoded, I think we will end up having the same end result and the code will be much simpler, no?

It's not exactly the same, since it would encode extended ASCII characters too which the current implementation does not. I agree that it would be simpler.

File: core/src/test/java/org/elasticsearch/common/logging/DeprecationLoggerTests.java (hunk 1 above)
Comment (bleskes) [reply core/src/test/java/org/elasticsearch/common/logging/DeprecationLoggerTests.java]: we decided to live on the edge and have fun. The concern was around non ascii codes breaking tooling but CI seems happy. Let's see how far we get.

**Comment by jasontedor** [comment]
> It's not exactly the same, since it would encode extended ASCII characters too which the current implementation does not. I agree that it would be simpler.

This has a downside compared to the current approach which is that it always involves a UTF-16 to UTF-8 conversion whereas the current approach will avoid this in the common case (when the message is ASCII-only). While we could avoid this by first scanning the string to see if there are any non-ASCII characters, that loses some of the simplicity though.

Your previous [suggestion](https://github.com/elastic/elasticsearch/pull/27269#discussion_r149047770) leads to another simplification though. I pushed d224d2078db9b179424734bcff0c24508a7104d4.

**Review by bleskes — APPROVED** [review]
LGTM, again.

File: core/src/main/java/org/elasticsearch/common/logging/DeprecationLogger.java [hunk 2]
```diff
@@ -337,8 +350,88 @@ public static String formatWarning(final String s) {
...
+        final CharArrayWriter writer = new CharArrayWriter();
+        boolean encodingNeeded = false;
+        for (int i = 0; i < s.length();) {
+            int current = (int) s.charAt(i);
+            /*
+             * Either the character does not need encoding or it does; when the character does not need encoding we append the character to
+             * a buffer and move to the next character and when the character does need encoding, we peel off as many characters as possible
+             * which we encode using UTF-8 until we encounter another character that does not need encoding.
+             */
+            if (doesNotNeedEncoding.get(current)) {
```
[the remark this answers is not in the document]
Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/common/logging/DeprecationLogger.java]: Yeah, it grows on writes if needed, and reads are always okay.
