### PR TITLE
Handle index deletion while querying in ES|QL

### LINKED ISSUE #135863: [ES|QL] Search Task is Stuck
### Elasticsearch Version

8.19.3

### Installed Plugins

None

### Java Version

_bundled_

### OS Version

ECH Hosted

### Problem Description

A very simple set of ES|QL searches is triggering long running tasks that are not cancellable (even after cancelling, the runtime keeps going up).

### Steps to Reproduce

This does not reproduce consistently. I have no idea why it happens for some searches and not others. It's new in 8.19.3 from 8.15.x though.

### Logs (if relevant)

Here is an example of the ES|QL search task that is "open" for 11 days:

```http
GET /_tasks/9aB-DY70TdWnJja1jyfSYA:2108421440
```

```
{
  "completed": false,
  "task": {
    "node": "9aB-DY70TdWnJja1jyfSYA",
    "id": 2108421440,
    "type": "transport",
    "action": "indices:data/read/esql",
    "description": """FROM my-index-alias
| WHERE type == "my-type" AND cluster_id == "my-cluster-id"
| WHERE timestamp >= TO_DATETIME(1758269383313) AND timestamp < TO_DATETIME(1758270283313)
| STATS max_ts = MAX(timestamp), total_fractions = MAX(total_fractions)
  BY transaction_id, index, node_id
| STATS max_ts = MAX(max_ts), slices_agg = COUNT(*), total_fractions = MAX(total_fractions)
  BY transaction_id, index
| SORT max_ts DESC, transaction_id ASC
| LIMIT 1000
""",
    "start_time_in_millis": 1758270343508,
    "running_time_in_nanos": 1152741808301307,
    "cancellable": true,
    "cancelled": true,
    "headers": {
      "trace.id": "a2d3556e6f18273ef5312371e443066a"
    }
  }
}
```

The alias matches an ILM-based set of time series indexes. In this case, it's two small indexes (around 30 MB each and only around 300K documents total).

As a note about the runtime going up even though it's cancelled:

```
{
  "completed": false,
  "task": {
    "node": "9aB-DY70TdWnJja1jyfSYA",
    "id": 2108421440,
    ...
    "start_time_in_millis": 1758270343508,
    "running_time_in_nanos": 1156539887452789,
    "cancellable": true,
    "cancelled": true,
    "headers": {
      "trace.id": "a2d3556e6f18273ef5312371e443066a"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by dnhatn**
If the index is deleted while querying, ES|QL might try to get the index routing from the latest cluster state. This could throw an index-not-found exception, which is not handled properly, causing the user to never receive a response, even though execution has completed. This also results in a dangling task in the task manager.

Relates #126653
Closes #135863

### CODE REVIEW

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlRetryIT.java [hunk 1]
```diff
@@ -59,6 +65,37 @@ public void testRetryOnShardFailures() throws Exception {
...
+                    .addRequestHandlingBehavior(ComputeService.DATA_ACTION_NAME, (handler, request, channel, task) -> {
+                        if (deleted.compareAndSet(false, true)) {
+                            deleteIndexCompletely("log-index-2");
+                            waitForDeletion.countDown();
+                        } else {
+                            assertTrue(waitForDeletion.await(10, TimeUnit.SECONDS));
+                        }
+                        handler.messageReceived(request, channel, task);
+                    });
+            }
```
Comment (nik9000) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlRetryIT.java:84]: Very cute.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 2]
```diff
@@ -325,6 +342,11 @@ public void onSkip() {
                     onResponse(new DataNodeComputeResponse(DriverCompletionInfo.EMPTY, Map.of()));
                 }
             }
+
+            private void expectNoFailure(String message, Exception e) {
+                LOGGER.error(message, e);
+                assert false : new AssertionError(message, e);
+            }
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:352]: I believe the change to this file says "we expect no failures handling the response and if there is one log something big and loud and, if we're testing, crash loudly so we see if and fix it right away. If we're in production just be loud."

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 3]
```diff
@@ -515,15 +537,18 @@ Map<ShardId, List<DiscoveryNode>> resolveShards(Set<ShardId> shardIds) {
...
                     .shardRoutingTable(shardId)
                     .allShards()
                     .filter(shard -> shard.active() && shard.isSearchable())
                     .map(shard -> project.cluster().nodes().get(shard.currentNodeId()))
-                    .toList()
-            );
+                    .toList();
+            } catch (Exception ignored) {
+                continue;
+            }
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:566]: Should we continue on *any* exception here or just the one we get from the index being deleted. Is that just `IndexNotFoundException`?

Would you kindly add a comment around `continue;` saying "this is a shard being deleted after we started the request"?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 2 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:352]: Yes, that's correct. In production, if a request enters this state, we will fail it fast and log the error.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 3 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:566]: Sure, I added a comment in https://github.com/elastic/elasticsearch/pull/137702/commits/691c5cd832858ecedccd92df3d8f82a4c6f69dc6

**Comment by dnhatn** [comment]
@nik9000 Can you take another look? Thank you!

**Review by nik9000 — APPROVED** [review]
LGTM. thanks for the iteration and patience.

**Comment by dnhatn** [comment]
@nik9000 Thanks for the review!

**Comment by dnhatn** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/138113)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/138114)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/138116)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
