### PR TITLE
Remove test usages of `DataStream#getDefaultBackingIndexName` in ILM integration tests

### LINKED ISSUE #117403: [CI] TimeSeriesLifecycleActionsIT testHistoryIsWrittenWithDeletion failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5494 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/wemg2vesu3ngo)
- [elasticsearch-periodic-platform-support #5419 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/uidcy2m2x7ufw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithDeletion" -Dtests.seed=1130862426BABC16 -Dtests.locale=tr-TR -Dtests.timezone=PRC -Druntime.java=23
```

**Applicable branches:**
8.16

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testHistoryIsWrittenWithDeletion),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:45661], URI [.ds-ilm-history-7-2024.12.23-000001/_lifecycle/explain], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.ds-ilm-history-7-2024.12.23-000001]","resource.type":"index_or_alias","resource.id":".ds-ilm-history-7-2024.12.23-000001","index_uuid":"_na_","index":".ds-ilm-history-7-2024.12.23-000001"}],"type":"index_not_found_exception","reason":"no such index [.ds-ilm-history-7-2024.12.23-000001]","resource.type":"index_or_alias","resource.id":".ds-ilm-history-7-2024.12.23-000001","index_uuid":"_na_","index":".ds-ilm-history-7-2024.12.23-000001"},"status":404}
```

**Issue Reasons:**
- [8.16] 2 failures in test testHistoryIsWrittenWithDeletion (0.4% fail rate in 456 executions)
- [8.16] 2 failures in pipeline elasticsearch-periodic-platform-support (12.5% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123202: [CI] SearchableSnapshotActionIT testRestoredIndexManagedByLocalPolicySkipsIllegalActions failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6541 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/qr455oxwsd7ok)
- [elasticsearch-pull-request #58805 / part-5](https://gradle-enterprise.elastic.co/s/zpmmmglyg5jcg)
- [elasticsearch-pull-request #58103 / part-5-entitlements](https://gradle-enterprise.elastic.co/s/bitkzu7wvtyao)
- [elasticsearch-pull-request #57696 / part-5-entitlements](https://gradle-enterprise.elastic.co/s/gg53y75rvhtwo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testRestoredIndexManagedByLocalPolicySkipsIllegalActions" -Dtests.seed=C5211E9060FDED2 -Dtests.locale=zu -Dtests.timezone=America/Porto_Acre -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRestoredIndexManagedByLocalPolicySkipsIllegalActions),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 4 failures in test testRestoredIndexManagedByLocalPolicySkipsIllegalActions (0.4% fail rate in 945 executions)
- [main] 2 failures in step part-5-entitlements (5.9% fail rate in 34 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.7% fail rate in 421 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123203: [CI] TimeSeriesLifecycleActionsIT testHistoryIsWrittenWithFailure failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6668 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/gtjmei3ibyyvk)
- [elasticsearch-periodic-platform-support #6584 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/t6mjhbh6lcjsq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithFailure" -Dtests.seed=6F99046BCB9E69EB -Dtests.locale=fr-CM -Dtests.timezone=Europe/Bratislava -Druntime.java=23
```

**Applicable branches:**
8.16

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testHistoryIsWrittenWithFailure),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:44945], URI [.ds-ilm-history-7-2025.02.28-000001/_lifecycle/explain], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.ds-ilm-history-7-2025.02.28-000001]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":".ds-ilm-history-7-2025.02.28-000001","index":".ds-ilm-history-7-2025.02.28-000001"}],"type":"index_not_found_exception","reason":"no such index [.ds-ilm-history-7-2025.02.28-000001]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":".ds-ilm-history-7-2025.02.28-000001","index":".ds-ilm-history-7-2025.02.28-000001"},"status":404}
```

**Issue Reasons:**
- [8.16] 2 failures in test testHistoryIsWrittenWithFailure (0.5% fail rate in 396 executions)
- [8.16] 2 failures in pipeline elasticsearch-periodic-platform-support (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #124439: [CI] TimeSeriesLifecycleActionsIT testHistoryIsWrittenWithSuccess failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6875 / rhel-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/vf7scfbip7gri)
- [elasticsearch-periodic-platform-support #6875 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/bbs3brepgtf4m)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess" -Dtests.seed=F8B8F9B5E5364D69 -Dtests.locale=pt-TL -Dtests.timezone=America/Kralendijk -Druntime.java=23
```

**Applicable branches:**
8.16

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testHistoryIsWrittenWithSuccess),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:37085], URI [.ds-ilm-history-7-2025.03.09-000001/_lifecycle/explain], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.ds-ilm-history-7-2025.03.09-000001]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":".ds-ilm-history-7-2025.03.09-000001","index":".ds-ilm-history-7-2025.03.09-000001"}],"type":"index_not_found_exception","reason":"no such index [.ds-ilm-history-7-2025.03.09-000001]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":".ds-ilm-history-7-2025.03.09-000001","index":".ds-ilm-history-7-2025.03.09-000001"},"status":404}
```

**Issue Reasons:**
- [8.16] 2 consecutive failures in test testHistoryIsWrittenWithSuccess
- [8.16] 2 failures in test testHistoryIsWrittenWithSuccess (2.1% fail rate in 94 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by gmarouli**
Relates to https://github.com/elastic/elasticsearch/issues/123376.

In this PR we change the way we retrieve the name of the backing index of data streams. We replace usages of time sensitive `DataStream#getDefaultBackingIndexName` with the retrieval of the name via an API call. The problem with using the time sensitive method is that we can have test failures around midnight.

Because this is part of a larger effort https://github.com/elastic/elasticsearch/issues/123376 we think it's a good idea to add a helper method to facilitate the retrieval of the backing index names to the base test classes.

Fixes: https://github.com/elastic/elasticsearch/issues/117403
Fixes: https://github.com/elastic/elasticsearch/issues/123203
Fixes: https://github.com/elastic/elasticsearch/issues/123202
Fixes: https://github.com/elastic/elasticsearch/issues/124439

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 1]
```diff
@@ -850,6 +852,22 @@ private static Settings.Builder getExcludeSettings(int num, Settings.Builder bui
...
     }
 
+    /**
+     * Returns a list of the data stream's backing index names.
+     */
+    public List<String> getDataStreamBackingIndexNames(String dataStreamName) {
+        GetDataStreamAction.Response response = safeGet(
+            client().execute(
+                GetDataStreamAction.INSTANCE,
+                new GetDataStreamAction.Request(TimeValue.THIRTY_SECONDS, new String[] { dataStreamName })
```
Comment (nielsbauman) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:862]: Nit:
```suggestion
                new GetDataStreamAction.Request(TEST_REQUEST_TIMEOUT, new String[] { dataStreamName })
```

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java [hunk 2]
```diff
@@ -1230,8 +1229,8 @@ private void assertHistoryIsPresent(
             fail("failed to perform search:" + e.getMessage());
         }
 
-        // Finally, check that the history index is in a good state
-        String historyIndexName = DataStream.getDefaultBackingIndexName("ilm-history-7", 1);
+        String historyIndexName = getDataStreamBackingIndexNames("ilm-history-7").getFirst();
+        assertThat(historyIndexName, notNullValue());
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java:1233]: Nit: I don't think this assertion is super valuable. The only way it could be null is if the GET data streams API returns the data stream, with indices, but the index doesn't have it's `index_name` set -- in all other cases, `getDataStreamBackingIndex` will throw an exception already.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java [hunk 3]
```diff
@@ -1230,8 +1229,8 @@ private void assertHistoryIsPresent(
             fail("failed to perform search:" + e.getMessage());
         }
 
-        // Finally, check that the history index is in a good state
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java:1233]: Nit: is there a reason you removed this comment? I don't think it should get an aware for "most valuable comment ever", but I do think it helps a little bit.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java [hunk 4]
```diff
@@ -104,7 +103,8 @@ public void testSearchableSnapshotAction() throws Exception {
         // rolling over the data stream so we can apply the searchable snapshot policy to a backing index that's not the write index
         rolloverMaxOneDocCondition(client(), dataStream);
 
-        String backingIndexName = DataStream.getDefaultBackingIndexName(dataStream, 1L);
+        String backingIndexName = getDataStreamBackingIndexNames(dataStream).getFirst();
+        assertThat(backingIndexName, endsWith("1"));
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java:107]: Same in this class about the assertion.

File: x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMMultiNodeIT.java [hunk 5]
```diff
@@ -105,7 +105,8 @@ public void testShrinkOnTiers() throws Exception {
             ).get();
             logger.info("--> explain: {}", Strings.toString(explain));
 
-            String backingIndexName = DataStream.getDefaultBackingIndexName(index, 1);
+            String backingIndexName = getDataStreamBackingIndexNames(index).getFirst();
+            assertThat(backingIndexName, notNullValue());
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMMultiNodeIT.java:109]: Same about the null-assertion.

File: x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMMultiNodeWithCCRDisabledIT.java [hunk 6]
```diff
@@ -105,7 +105,8 @@ public void testShrinkOnTiers() throws Exception {
             ).get();
             logger.info("--> explain: {}", Strings.toString(explain));
 
-            String backingIndexName = DataStream.getDefaultBackingIndexName(index, 1);
+            String backingIndexName = getDataStreamBackingIndexNames(index).getFirst();
+            assertThat(backingIndexName, notNullValue());
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/ILMMultiNodeWithCCRDisabledIT.java:109]: Last one :)

**Review by nielsbauman — APPROVED** [review]
Left some minor comments, but other than that LGTM. Thanks, Mary! One big step closer to never having these annoying test failures again :)

I think we should backport this because the failures occurred on `8.16` too.

Also, I see https://github.com/elastic/elasticsearch/issues/124439 got opened after you opened this PR, so you can close that one with this PR too. Four closed issues with one PR is not too bad at all :smile:

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/LifecycleLicenseIT.java [hunk 7]
```diff
@@ -107,7 +107,8 @@ public void testSearchableSnapshotActionErrorsOnInvalidLicense() throws Exceptio
         // rolling over the data stream so we can apply the searchable snapshot policy to a backing index that's not the write index
         rolloverMaxOneDocCondition(client(), dataStream);
 
-        String backingIndexName = DataStream.getDefaultBackingIndexName(dataStream, 1L);
+        String backingIndexName = getDataStreamBackingIndexNames(dataStream).getFirst();
+        assertThat(backingIndexName, endsWith("1"));
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/LifecycleLicenseIT.java:111]: > I do feel like asserting there is only one backing index is slightly more relevant than asserting the last character, but it's not a blocker for me. What do you think?

I only added this assertion after a rollover was performed, so we would have to assert that size is 2. I can do that. No strong feelings about it.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java (hunk 2 above)
Comment (gmarouli) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java:1233]: Good point I will remove it.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 1 above)
Comment (gmarouli) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:862]: Fixed but offline to not initiate too many ci builds.

**Comment by gmarouli** [comment]
Thank you for the review @nielsbauman , comments addressed :)

**Comment by nielsbauman** [comment]
LGTM! Thanks!

**Comment by gmarouli** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/124467)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
