### PR TITLE
SQL: Fix SUM(all zeroes) to return 0 instead of NULL

### LINKED ISSUE #45251: SQL: SUM of multiple 0 values returns NULL
Given:
- `SELECT SUM(val) FROM test WHERE val IS NOT NULL GROUP BY name`
- all `val` values are 0 for a certain `name` value

The result of the above query will return NULL, whereas the result should be 0. This boils down to `AggregationInspectionHelper.hasValue(InternalSum)` that will return `true`/`false` if the sum is 0: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/support/AggregationInspectionHelper.java#L160
We use these methods to decide if the result of aggregations has a value or not.

Relates to https://github.com/elastic/elasticsearch/pull/36020. CC @polyfractal @costin

### PR DESCRIPTION
**Pull request by palesz**
Previously the SUM(all zeroes) was `NULL`, but after this change the SUM
SQL function call is automatically upgraded into a `stats` aggregation
instead of a `sum` aggregation. The `stats` aggregation only results in
`NULL` if the there were no rows, no values to aggregate, which is the
expected behaviour across different SQL implementations.

This is a workaround for #45251 .

### CODE REVIEW

**Comment by palesz** [comment]
#65792 is prerequisite of this PR.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 1]
```diff
@@ -983,6 +984,37 @@ public LogicalPlan apply(LogicalPlan p) {
         }
     }
 
+    static class ReplaceSumWithStats extends OptimizerBasicRule {
+        // this is a workaround for the https://github.com/elastic/elasticsearch/issues/45251 issue
+        // should be removed as soon as the issue is fixed
+        // NOTE: this rule should always be applied AFTER the ReplaceAggsWithStats rule
+
+        @Override public LogicalPlan apply(LogicalPlan plan) {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:992]: `@Override` goes on a separate line.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java [hunk 2]
```diff
@@ -1023,4 +1022,43 @@ public void testReplaceAttributesWithTarget() {
...
+        Sum sum = new Sum(EMPTY, fa);
+        
+        Alias sumAlias = new Alias(EMPTY, "sum", sum);
+        
+        Aggregate aggregate = new Aggregate(EMPTY, FROM(), emptyList(), asList(sumAlias));
+        LogicalPlan optimizedPlan = new Optimizer().optimize(aggregate);
+        assertEquals(Aggregate.class, optimizedPlan.getClass());
+        Aggregate p = (Aggregate) optimizedPlan; 
+        assertEquals(1, p.aggregates().size());
+        assertEquals(Alias.class, p.aggregates().get(0).getClass());
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1040]:
```suggestion
        `assertTrue(p.aggregates().get(0) instanceof Alias);`
```

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java [hunk 3]
```diff
@@ -1023,4 +1022,43 @@ public void testReplaceAttributesWithTarget() {
...
+        Alias alias = (Alias) p.aggregates().get(0);
+        assertEquals(InnerAggregate.class, alias.child().getClass());
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1042]:
```suggestion
        `assertTrue(alias.child() instanceof InnerAggregate);`
```

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java [hunk 4]
```diff
@@ -1023,4 +1022,43 @@ public void testReplaceAttributesWithTarget() {
...
+    //
+    public void testSumIsReplacedWithStats() {
+        FieldAttribute fa = getFieldAttribute();
+        Sum sum = new Sum(EMPTY, fa);
+        
+        Alias sumAlias = new Alias(EMPTY, "sum", sum);
+        
+        Aggregate aggregate = new Aggregate(EMPTY, FROM(), emptyList(), asList(sumAlias));
+        LogicalPlan optimizedPlan = new Optimizer().optimize(aggregate);
+        assertEquals(Aggregate.class, optimizedPlan.getClass());
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1037]:
```suggestion
        `assertTrue(optimizedPlan instanceof Aggregate);`
```

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java [hunk 5]
```diff
@@ -1023,4 +1022,43 @@ public void testReplaceAttributesWithTarget() {
...
+        Aggregate p = (Aggregate) optimizedPlan; 
+        assertEquals(1, p.aggregates().size());
+        assertEquals(Alias.class, p.aggregates().get(0).getClass());
+        Alias alias = (Alias) p.aggregates().get(0);
+        assertEquals(InnerAggregate.class, alias.child().getClass());
+        assertEquals(sum, ((InnerAggregate)alias.child()).inner());
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1043]:
```suggestion
        assertEquals(sum, ((InnerAggregate) alias.child()).inner());
```

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java [hunk 6]
```diff
@@ -1023,4 +1022,43 @@ public void testReplaceAttributesWithTarget() {
...
+    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/45251")
+    public void testSumIsNotReplacedWithStats() {
+        FieldAttribute fa = getFieldAttribute();
+        Sum sum = new Sum(EMPTY, fa);
+
+        Alias sumAlias = new Alias(EMPTY, "sum", sum);
+
+        Aggregate aggregate = new Aggregate(EMPTY, FROM(), emptyList(), asList(sumAlias));
+        LogicalPlan optimizedPlan = new Optimizer().optimize(aggregate);
+        assertEquals(Aggregate.class, optimizedPlan.getClass());
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1059]:
```suggestion
        assertTrue(optimizedPlan instanceof Aggregate);
```

**Review by astefan — COMMENTED** [review]
Left some comments and questions. Also, I'd like to see a test being added to QueryTranslatorTests. Thanks.

File: x-pack/plugin/sql/qa/server/src/main/resources/agg-nulls-zeros.csv-spec [hunk 7]
```diff
@@ -0,0 +1,359 @@
+
```
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/qa/server/src/main/resources/agg-nulls-zeros.csv-spec:1]: +1

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java (hunk 4 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1037]: We have a mix of those assertions, I wouldn't mind keeping it as is.

**Review by matriv — COMMENTED** [review]
Left also a few comments, I agree with @astefan for having also a test in QueryTranslatorTests.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 8]
```diff
@@ -983,6 +984,37 @@ public LogicalPlan apply(LogicalPlan p) {
         }
     }
 
+    static class ReplaceSumWithStats extends OptimizerBasicRule {
+        // this is a workaround for the https://github.com/elastic/elasticsearch/issues/45251 issue
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:988]: Class comment sound sit before the class declaration

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 9]
```diff
@@ -983,6 +984,37 @@ public LogicalPlan apply(LogicalPlan p) {
...
+            plan.forEachExpressionsUp(e -> {
+                if (e instanceof Sum) {
+                    statsPerField.computeIfAbsent(((Sum) e).field(), field -> {
+                        Source source = new Source(field.sourceLocation(), "STATS(" + field.sourceText() + ")");
+                        return new Stats(source, field);
+                    });
+                }
+            });
+            
+            if (statsPerField.isEmpty()) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1004]: Minor adjustment - to avoid having two return staments do the transformation if the list is non-empty and assign that to the plan

```
if (statsPerField.isEmpty() == false) {
   plan = plan.transformExpression()
}

return plan;
```

File: x-pack/plugin/sql/qa/server/src/main/resources/setup_test_emp.sql [hunk 10]
```diff
@@ -9,4 +9,17 @@ CREATE TABLE "test_emp" (
                     "last_name" VARCHAR(50),
                     "salary" INT
                    )
-   AS SELECT * FROM CSVREAD('classpath:/employees.csv');
\ No newline at end of file
+   AS SELECT * FROM CSVREAD('classpath:/employees.csv');
+   
+DROP TABLE IF EXISTS "logs";
```
Comment (costin) [inline x-pack/plugin/sql/qa/server/src/main/resources/setup_test_emp.sql:14]: To Andrei's point, isn't logs.csv used already and if not can you track down why we add it in the first place? Additionally instead of adding a new data file (assuming it is not used) you can emulate the null using a CASE function for bonus points.

File: x-pack/plugin/sql/qa/server/src/main/resources/agg-nulls-zeros.csv-spec [hunk 11]
```diff
@@ -0,0 +1,359 @@
...
+aggregatingAllZerosWithFirst
```
Comment (costin) [inline x-pack/plugin/sql/qa/server/src/main/resources/agg-nulls-zeros.csv-spec:2]: No need to prefix all tests with `aggregating` - that already happens through the file name.

**Review by costin — CHANGES_REQUESTED** [review]
The fix looks good however the testing needs cleaning up.

**Comment by costin** [comment]
> #65792 is prerequisite of this PR.

Why? That fix focused on PIVOT, this is a SUM.

File: x-pack/plugin/sql/qa/server/src/main/resources/agg-nulls-zeros.csv-spec [hunk 12]
```diff
@@ -0,0 +1,359 @@
...
+schema::FIRST_AllZeros:i
+SELECT FIRST(bytes_in) as "FIRST_AllZeros" FROM logs WHERE bytes_in = 0;
```
[the remark this answers is not in the document]
Comment (palesz) [reply x-pack/plugin/sql/qa/server/src/main/resources/agg-nulls-zeros.csv-spec:4]: Regarding the non-SUM aggregation function: I can move them to a separate commit, but I wanted to check the behaviour of each of the aggregation functions with `NULL` vs `0`, to understand if any other aggregation beside the `SUM` is also impacted.

+1 on the more complex cases. I checked them, but they did not make it to the integration test file, will add them.

File: x-pack/plugin/sql/qa/server/src/main/resources/setup_test_emp.sql (hunk 10 above)
Comment (palesz) [reply x-pack/plugin/sql/qa/server/src/main/resources/setup_test_emp.sql:14]: The `logs.csv` was only used before in `*.csv-spec` tests and loaded by the `DataLoader` by this method:

https://github.com/elastic/elasticsearch/blob/c874e6cdd3e051ce599b50c18642de038b84105f/x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/DataLoader.java#L65

, but it was not loaded during the `*.sql-spec` tests into H2.

`logs` is used in the `pivot.csv-spec` and `ip.csv-spec`. 

Regarding CASE: Originally was thinking about using this trick, but the CASE only works for the `stats` and `extended_stats` aggregations, and does not work for the `matrix_stats` aggregations, hence I decided to go with just a field instead of emulating null with CASE.

```
SELECT client_port
  , SKEWNESS(CASE WHEN bytes_in < 30 THEN NULL ELSE bytes_in END)
FROM logs
GROUP BY client_port

Found 1 problem
line 2:14: [SKEWNESS()] cannot be used on top of operators or scalars
```

**Comment by palesz** [comment]
> > #65792 is prerequisite of this PR.
> 
> Why? That fix focused on PIVOT, this is a SUM.

PIVOT is a GROUP BY with aggregations underneath. Without the #65792 change I cannot promote the SUM aggregation to `stats` inside PIVOT and we would end up with SUM returning 0 in the GROUP BY, but returning NULL inside the PIVOT.

I have two (+ one) options:
1. Do #65792 before the fix of SUM
2. Don't do #65792 and only fix SUM inside the GROUP BY (double workaround)
3. Do not support SUM inside PIVOT (breaking change and lost major functionality of PIVOTs)

File: x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec [hunk 13]
```diff
@@ -1325,3 +1325,386 @@ F              |1964-10-18T00:00:00.000Z|1952-04-19T00:00:00.000Z
...
+-----------------
+null             
+;
+
+nullsAndZerosCombined
+schema::COUNT(*):l|COUNT_AllZeros:l|COUNT_AllNulls:l|FIRST_AllZeros:i|FIRST_AllNulls:i|SUM_AllZeros:i|SUM_AllNulls:i
+SELECT
+    COUNT(*)
+    , COUNT(bytes_in) AS "COUNT_AllZeros"
+    , COUNT(bytes_out) AS "COUNT_AllNulls"
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec:1678]: Could you put comma at the end of the line instead of at the start?

File: x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec [hunk 14]
```diff
@@ -1325,3 +1325,386 @@ F              |1964-10-18T00:00:00.000Z|1952-04-19T00:00:00.000Z
...
+    bytes_in
+    , COUNT(*)
+    , SUM(bytes_in)
+    , MIN(bytes_in)
+    , MAX(bytes_in)
+    , AVG(bytes_in)
+FROM logs
+WHERE NVL(bytes_in, 0) = 0
+GROUP BY bytes_in
+ORDER BY bytes_in;
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec:1704]: Just a minor suggestion: ORDER BY ... DESC.

File: x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec [hunk 15]
```diff
@@ -1325,3 +1325,386 @@ F              |1964-10-18T00:00:00.000Z|1952-04-19T00:00:00.000Z
 M              |1965-01-03T00:00:00.000Z|1952-02-27T00:00:00.000Z
 ;
 
+
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec:1328]: Please, add one more test, that uses two SUMs and some other elements: `SELECT SUM(bytes_in), SUM(bytes_out), client_ip, COUNT(*) AS c FROM logs WHERE client_ip = '10.0.0.0/16' AND NVL(bytes_out, 0) = 0 GROUP BY client_ip ORDER BY c DESC, SUM(bytes_in) ASC NULLS FIRST`

**Review by astefan — APPROVED** [review]
LGTM. Left some minor comments, though.

File: x-pack/plugin/sql/qa/server/src/main/resources/logs.csv [hunk 16]
```diff
@@ -99,3 +99,4 @@ id,@timestamp,bytes_in,bytes_out,client_ip,client_port,dest_ip,status
 98,2017-11-10T21:12:24Z,74,90,10.0.0.134,57203,172.20.10.1,OK
 99,2017-11-10T21:17:37Z,39,512,10.0.0.128,29333,,OK
 100,2017-11-10T03:21:36Z,64,183,10.0.0.129,4541,172.16.1.1,OK
+101,2017-11-10T23:22:36Z,,,10.0.2.129,4541,172.20.11.1,OK
```
Comment (costin) [inline x-pack/plugin/sql/qa/server/src/main/resources/logs.csv:102]: Why was this added and what would have happened without it?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 17]
```diff
@@ -983,6 +984,38 @@ public LogicalPlan apply(LogicalPlan p) {
         }
     }
 
+    // This is a workaround for the https://github.com/elastic/elasticsearch/issues/45251 issue
+    // Should be removed as soon as the above issue is fixed
+    // NOTE: this rule should always be applied AFTER the ReplaceAggsWithStats rule
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:989]: I find this comment confusing.
This PR is a fix for https://github.com/elastic/elasticsearch/issues/45251 itself due to an issue in Elasticsearch not SQL.
Once the issue in Elasticsearch is fixed the workaround in QL won't be needed. Pointing to the SQL issue itself asking for the workaround is incorrect.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java [hunk 18]
```diff
@@ -1023,4 +1022,43 @@ public void testReplaceAttributesWithTarget() {
...
+        Alias alias = (Alias) p.aggregates().get(0);
+        assertTrue(alias.child() instanceof InnerAggregate);
+        assertEquals(sum, ((InnerAggregate) alias.child()).inner());
+    }
+
+    /**
+     * Once the bug is fixed, the above {@link OptimizerTests#testSumIsReplacedWithStats()} should be
+     * invalid and should be deleted, and the test below should apply.
+     */
+    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/45251")
```
Comment (costin) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java:1050]: Incorrect issue referenced - this PR provides the workaround in SQL for ES. Once the issue in ES gets solved, this test can be enabled.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java [hunk 19]
```diff
@@ -2443,4 +2443,19 @@ public void testPercentileOptimization() {
         test.accept("PERCENTILE", p -> ((PercentilesAggregationBuilder)p).percentiles());
         test.accept("PERCENTILE_RANK", p -> ((PercentileRanksAggregationBuilder)p).values());
     }
+
+    // workaround for the https://github.com/elastic/elasticsearch/issues/45251 issue
```
Comment (costin) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:2447]: Same comment here regarding the Github issue.

**Review by costin — APPROVED** [review]
Left some comments but otherwise LGTM.

File: x-pack/plugin/sql/qa/server/src/main/resources/logs.csv (hunk 16 above)
Comment (astefan) [reply x-pack/plugin/sql/qa/server/src/main/resources/logs.csv:102]: @costin this a follow up to my suggestion [here](https://github.com/elastic/elasticsearch/pull/65796#discussion_r534770344) to allow a more complex test query to be added.

File: x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec (hunk 13 above)
Comment (palesz) [reply x-pack/plugin/sql/qa/server/src/main/resources/agg.csv-spec:1678]: Will move those commas. Good old habit (easier to comment out fields this way).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 17 above)
Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:989]: I intended to keep #45251 open after this PR and only close it after the `sum` aggregations can differentiate between `SUM(all zeroes)` and `SUM(all nulls)`. Reworded the comment to make this more obvious.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 20]
```diff
@@ -983,6 +984,39 @@ public LogicalPlan apply(LogicalPlan p) {
...
+    // should be removed as soon as root cause is fixed and the sum aggregation results can differentiate between SUM(all zeroes) 
+    // and SUM(all nulls)
+    // NOTE: this rule should always be applied AFTER the ReplaceAggsWithStats rule
+    static class ReplaceSumWithStats extends OptimizerBasicRule {
+        
+        @Override 
+        public LogicalPlan apply(LogicalPlan plan) {
+            final Map<Expression, Stats> statsPerField = new LinkedHashMap<>();
+            
+            plan.forEachExpressionsUp(e -> {
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:997]: Not related to this PR, but I was wondering: most `forEachExpressionsUp/Down` methods invocations do pattern matching as first thing. Wouldn't an alternative method similar to `Node#forEachUp/Down` taking a type token make sense?

Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:997]: The issue lies with collections. Expressions are not just used as individual nodes but also as properties. Take `Project(List<NamedExpression> projections)` - this led to issues in not only filtering but in reconstructing said collections with the new expressions while preserving their types. See the comment in `LogicalPlan.doTransformExpression`

It would be nicer to do:
`plan.forEachExpressionsUp(s -> , Sum.class)` instead of doing the `instanceof` check however the issue right now is preserving the type information before and after transformation without causing a CCE.

That said, I plan to take another look at this to see whether it can be sorted out.

**Review by costin — APPROVED** [review]
LGTM

**Comment by Luegg** [comment]
Closes #45251.

(see also #74396)
