### PR TITLE
Fix layout for MV_EXPAND

### LINKED ISSUE #102912: ES|QL: IndexOutOfBounds on mv_expand layout management
The following query

```
row  a = \"a\", b = 1 | stats  e = min(b) by a | dissect a \"%{e}\" | mv_expand e
```

throws an IndexOutOfBoundsException when building the layout for MV_EXPAND.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/102912

Fixing MV_EXPAND layout by manually replacing the input attribute with the output one (that is what practically the operator does).

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/docs

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 1]
```diff
@@ -581,20 +581,10 @@ private PhysicalOperation planLimit(LimitExec limit, LocalExecutionPlannerContex
...
-            if (childOutput.get(index).name().equals(expandedName)) {
-                layout.append(mvExpandExec.expanded());
-            } else {
-                layout.append(inverse.get(index));
-            }
-        }
-
+        // Layout outputLayout = outputLayout(source, mvExpandExec);
+        Layout.Builder layout = source.layout.builder();
+        layout.replace(mvExpandExec.target().id(), mvExpandExec.expanded().id());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:587]: ++ this is much easier to understand and verify

**Review by alex-spies — APPROVED** [review]
LGTM

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/docs
