### PR TITLE
Fix AnalysisModuleTests#testStandardFilterBWC

### LINKED ISSUE #38635: [CI] AnalysisModuleTests#testStandardFilterBWC fails on master
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/230/console

Reproduces locally on master with:
```
./gradlew :server:unitTest \
  -Dtests.seed=19B79C99E068891A \
  -Dtests.class=org.elasticsearch.indices.analysis.AnalysisModuleTests \
  -Dtests.method="testStandardFilterBWC" \
  -Dtests.security.manager=true \
  -Dtests.locale=cs-CZ \
  -Dtests.timezone=Asia/Tbilisi \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
java.lang.IllegalArgumentException: The [standard] token filter has been removed.
	at __randomizedtesting.SeedInfo.seed([19B79C99E068891A:6879C7DDA92FB39F]:0)
	at org.elasticsearch.indices.analysis.AnalysisModule.lambda$setupPreConfiguredTokenFilters$1(AnalysisModule.java:189)
	at org.elasticsearch.index.analysis.PreConfiguredTokenFilter.lambda$singletonWithVersion$2(PreConfiguredTokenFilter.java:60)
	at org.elasticsearch.index.analysis.PreConfiguredTokenFilter$1.create(PreConfiguredTokenFilter.java:116)
	at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:92)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199)
	at org.elasticsearch.indices.analysis.AnalysisModuleTests.testStandardFilterBWC(AnalysisModuleTests.java:254)
```

### PR DESCRIPTION
**Pull request by cbuescher**
The part of this test that has been checking deprecation warnings on pre-7.0
nodes doesn't work anymore on 8.0 and must be removed.

Closes #38635

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/indices/analysis/AnalysisModuleTests.java [hunk 1]
```diff
@@ -240,34 +240,15 @@ public void testUnderscoreInAnalyzerName() throws IOException {
...
 
-    @AwaitsFix(bugUrl="https://github.com/elastic/elasticsearch/issues/38635")
     public void testStandardFilterBWC() throws IOException {
-        Version version = VersionUtils.randomVersionBetween(random(), Version.V_6_0_0, Version.CURRENT.minimumCompatibilityVersion());
-        // bwc deprecation
-        {
-            Settings settings = Settings.builder()
-                .put("index.analysis.analyzer.my_standard.tokenizer", "standard")
+        Version version = VersionUtils.randomVersionBetween(random(), Version.V_7_0_0, Version.CURRENT);
+        final Settings settings = Settings.builder().put("index.analysis.analyzer.my_standard.tokenizer", "standard")
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/indices/analysis/AnalysisModuleTests.java]: The standard tokenizer is still there, I think?  You need to add `index.analysis.analyzer.my_standard.filter=standard`

Comment (romseygeek) [reply server/src/test/java/org/elasticsearch/indices/analysis/AnalysisModuleTests.java]: Oh, never mind, it's still there - ignore me.

**Review by romseygeek — APPROVED** [review]
LGTM, sorry for the misread in my review.

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2
