### PR TITLE
[test] list of plugins should have well-defined order

### LINKED ISSUE #12174: list of plugins (e.g. from nodes info) should have well-defined order.
Can we alphasort this?

I think today its sorted by filesystem order, which makes for hell in tests because many developers have macs. So me and jenkins get the short end of the stick since we run linux and tests fail sporatically.

### PR DESCRIPTION
**Pull request by dadoonet**
We now return list of plugins sorted by name.

Closes #12174.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginInfo.java [hunk 1]
```diff
@@ -178,6 +177,10 @@ public int hashCode() {
         return name.hashCode();
     }
 
+    public int compare(PluginInfo other) {
+        return this.name.compareTo(other.name);
+    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginInfo.java]: For the record, I was a bit confused at that method, which I first read as if it was Comparable.compareTo while it's not

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfo.java [hunk 2]
```diff
@@ -45,7 +47,17 @@ public PluginsInfo(int size) {
...
     }
 
+    /**
+     * @return an ordered list based on plugins name
+     */
     public List<PluginInfo> getInfos() {
+        Collections.sort(infos, new Comparator<PluginInfo>() {
+            @Override
+            public int compare(final PluginInfo o1, final PluginInfo o2) {
+                return o1.compare(o2);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfo.java]: maybe we can directly have o1.getName().compareTo(o2.getName()) here and remove PluginInfo.compare?

Comment (dadoonet) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfo.java]: lol. That's what I did at first but I was wondering if it's a better practice to have that in the Class itself... :p

File: core/src/test/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfoTest.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+        pluginsInfo.add(new PluginInfo("d", "foo", true, true, "dummy"));
+
+        final List<PluginInfo> infos = pluginsInfo.getInfos();
+        List<String> names = Lists.transform(infos, new Function<PluginInfo, String>() {
+            @Override
+            public String apply(PluginInfo input) {
+                return input.getName();
+            }
+        });
+        assertThat(names, contains("a", "b", "c", "d", "e"));
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfoTest.java]: I hate hamcrest, I had to look up the javadocs to know if it would check order. But ignore that comment, that's probably only me. :-)

File: core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginInfo.java (hunk 1 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/node/info/PluginInfo.java]: same here :)

File: core/src/test/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfoTest.java (hunk 3 above)
Comment (dadoonet) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/node/info/PluginsInfoTest.java]: I had to look at it as well! I found then `containsInAnyOrder()` which means that `contains` actually means `containsExactlyInThisOrder()` :)

**Comment by dadoonet** [comment]
@jpountz Thanks for the review. I pushed a new commit.

**Comment by jpountz** [comment]
LGTM
