### PR TITLE
ESQL: Fix Driver creating status with a live list of operators

### LINKED ISSUE #131564: [CI] CrossClusterAsyncEnrichStopIT testEnrichAfterStop failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9462 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/i64vduluu2lle)
- [elasticsearch-periodic-platform-support #9434 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/57ouunxnraf3a)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.CrossClusterAsyncEnrichStopIT.testEnrichAfterStop" -Dtests.seed=AB5262D6307DCCD8 -Dtests.locale=bm -Dtests.timezone=Africa/Bangui -Druntime.java=24
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClusterAsyncEnrichStopIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testEnrichAfterStop'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.util.ConcurrentModificationException: null
```

**Issue Reasons:**
- [8.19] 2 failures in test testEnrichAfterStop (1.4% fail rate in 147 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic-platform-support (40.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
`DriverStatus` is an immutable record created by the Driver. However, its components are not inherently immutable.

This PR fixes a live collection used by the Driver, that was being directly put into the status, leading to `ConcurrentModificationException`s when reading it (Through the Task list API, for example).

Some example errors:
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at org.elasticsearch.compute.operator.DriverStatus.toXContent(DriverStatus.java:134)
	at org.elasticsearch.xcontent@9.2.0/org.elasticsearch.xcontent.XContentBuilder.value(XContentBuilder.java:993)
	at org.elasticsearch.xcontent@9.2.0/org.elasticsearch.xcontent.XContentBuilder.field(XContentBuilder.java:978)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.tasks.TaskInfo.toXContent(TaskInfo.java:113)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.admin.cluster.node.tasks.list.TaskGroup.toXContent(TaskGroup.java:63)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.admin.cluster.node.tasks.list.TaskGroup.toXContent(TaskGroup.java:67)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.admin.cluster.node.tasks.list.ListTasksResponse.lambda$groupedByParent$10(ListTasksResponse.java:183)
```
And:
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at org.elasticsearch.compute.operator.DriverStatus.documentsFound(DriverStatus.java:157)
	at org.elasticsearch.compute.operator.DriverStatus.toXContent(DriverStatus.java:129)
	at org.elasticsearch.xcontent@9.2.0/org.elasticsearch.xcontent.XContentBuilder.value(XContentBuilder.java:993)
	at org.elasticsearch.xcontent@9.2.0/org.elasticsearch.xcontent.XContentBuilder.field(XContentBuilder.java:978)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.tasks.TaskInfo.toXContent(TaskInfo.java:113)
	at org.elasticsearch.server@9.2.0org.elasticsearch.action.admin.cluster.node.tasks.list.TaskGroup.toXContent(TaskGroup.java:63)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.admin.cluster.node.tasks.list.TaskGroup.toXContent(TaskGroup.java:67)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.admin.cluster.node.tasks.list.ListTasksResponse.lambda$groupedByParent$10(ListTasksResponse.java:183)

```

Also, this looks like the source of this issue, with another similar case:
Fixes https://github.com/elastic/elasticsearch/issues/131564

### CODE REVIEW

**Review by smalyshev — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java [hunk 1]
```diff
@@ -556,7 +556,7 @@ private void updateStatus(long extraCpuNanos, int extraIterations, DriverStatus.
                 prev.cpuNanos() + extraCpuNanos,
                 prev.iterations() + extraIterations,
                 status,
-                statusOfCompletedOperators,
+                new ArrayList<>(statusOfCompletedOperators),
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java]: I'd probably do `List.copyOf` here, but this is fine.

I think it's worth a comment that we always update the `statusOfCompletedOperators` list in this thread, but we read it in many threads.

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java]: Added the suggestion, and a test.

About the `statusOfCompletedOperators`, after this change, it's never read outside of the `updateStatus()`

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
> Status 	Branch 	Result
> ✅ 	[9.1](https://github.com/elastic/elasticsearch/pull/132333) 	[](https://github.com/elastic/elasticsearch/pull/132333)
> ❌ 	8.19 	Commit could not be cherrypicked due to conflicts
> ❌ 	9.0 	Commit could not be cherrypicked due to conflicts
> ❌ 	8.17 	Commit could not be cherrypicked due to conflicts
> ❌ 	8.18 	Commit could not be cherrypicked due to conflicts

Enjoy!
