### PR TITLE
Apply missing request options to the expand phase

### LINKED ISSUE #26649: post filter not applied to field collapsing inner hits?
**Elasticsearch version**: 5.3.3

**Plugins installed**: [discovery-ec2, repository-s3, x-pack]

**JVM version** : 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM

**OS version** : 3.13.0-121-generic AWS Ubuntu 14.04 LTS

**Description of the problem including expected versus actual behavior**: I recently started using the new [field collapsing](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-request-collapse.html) functionality and I noticed that the search `post_filter` is *not* applied to the `inner_hits`. This was surprising behavior to me because the `post_filter` applies to the collapsed search hits just fine and I did not see anything that said it wouldn't work. However I'm not 100% sure if this would be a bug or enhancement.

We use the `post_filter` for the typical faceted navigation use case and we wanted to leverage the new field `collapse` with `inner_hits` to add more variety to our search results. I guess a workaround would be to use a `top_hits` + `filter` aggregation to do the [field collapse](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-aggregations-metrics-top-hits-aggregation.html#_field_collapse_example)? Are there any significant performance differences between using the `top_hits` aggregation vs the new `collapse` functionality?

**Steps to reproduce**:

```
POST test-index/test-type/1
{
  "value":1,
  "common":1
}

POST test-index/test-type/2
{
  "value":2,
  "common":1
}

POST test-index/test-type/_search
{
  "collapse": {
    "field": "common",
    "inner_hits": {
      "name": "common"
    }
  },
  "post_filter": {
    "term": {
      "value": 1
    }
  }
}
```

Note the search result `inner_hits` contains both doc 1 and 2, but I'm expecting to see only doc 1 because the `post_filter` does not match doc 2.

### LINKED ISSUE #27079: use routing and preference  of original SearchRequest in  collapse innerhits requests
We use the collapse feature with inner_hits as described here : https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-collapse.html

Is there a reason why the routing and preference settings of the main search request are not used for the inner hit queries. I think it would be a valid optimization to preserve these settings.

see org.elasticsearch.action.search.ExpandSearchPhase
https://github.com/elastic/elasticsearch/blob/ec64c2c05f64304d776cd7f9b4fa1d939ba96ba2/core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java#L92

### PR DESCRIPTION
**Pull request by jimczi**
This change adds some missing options to the expand query that builds the inner hits for field collapsing.
The following options are now applied to the inner_hits query:
 * post_filters
 * preferences
 * routing

Closes #27079
Closes #26649

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java [hunk 1]
```diff
@@ -120,6 +119,25 @@ public void run() throws IOException {
...
+            .indicesOptions(orig.indicesOptions())
+            .requestCache(orig.requestCache());
+        groupRequest.setMaxConcurrentShardRequests(orig.getMaxConcurrentShardRequests());
+        if (orig.preference() != null) {
+            groupRequest.preference(orig.preference());
+        }
+        if (orig.routing() != null) {
+            groupRequest.routing(orig.routing());
+        }
+        if (orig.searchType() != null) {
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java]: nit: looks like searchType cannot be null

File: core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java [hunk 2]
```diff
@@ -120,6 +119,25 @@ public void run() throws IOException {
...
     }
 
+    private SearchRequest buildExpandSearchRequest(SearchRequest orig, SearchSourceBuilder sourceBuilder) {
+        SearchRequest groupRequest = new SearchRequest(orig.indices())
+            .types(orig.types())
+            .source(sourceBuilder)
+            .indicesOptions(orig.indicesOptions())
+            .requestCache(orig.requestCache());
+        groupRequest.setMaxConcurrentShardRequests(orig.getMaxConcurrentShardRequests());
+        if (orig.preference() != null) {
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java]: nit: maybe the null check isn't necessary

File: core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java [hunk 3]
```diff
@@ -120,6 +119,25 @@ public void run() throws IOException {
...
+            groupRequest.preference(orig.preference());
+        }
+        if (orig.routing() != null) {
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/action/search/ExpandSearchPhase.java]: nit: maybe the null check isn't necessary

**Review by cbuescher — APPROVED** [review]
LGTM, I left some very minor suggestions

**Comment by cbuescher** [comment]
+1

**Comment by jmuscireum** [comment]
Hi! Would you mind backporting this fix to 5.6? #26649 is a major bug for us and we are unfortunately not ready for 6.x yet.
