### PR TITLE
Tweak WatcherIndexTemplateRegistry bwc logic

### LINKED ISSUE #69918: Failure in WatcherRestartIT.testWatcherRestart
**Build scan**: https://gradle-enterprise.elastic.co/s/pgbuawfavusl2

**Repro line**: `./gradlew ':x-pack:qa:rolling-upgrade:v7.9.1#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.WatcherRestartIT" -Dtests.method="testWatcherRestart" -Dtests.seed=3DE603A8143C17BA -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=fr-CA -Dtests.timezone=Africa/Tripoli -Druntime.java=8	
`

**Reproduces locally?**: No

**Applicable branches**: 7.x, 7.11, 7.12

**Failure history**: Failing pretty frequently as of the morning of 3/3/21

**Failure excerpt**:

```

java.lang.AssertionError: |  
-- | --
  | Expected: not a string containing "\"watcher_state\":\"stopped\"" |  
  | but: was "{\"_nodes\":{\"total\":3,\"successful\":3,\"failed\":0},\"cluster_name\":\"v7.9.1\",\"manually_stopped\":false,\"stats\":[{\"node_id\":\"qEEjrtXgSVqMj7QTR-ec6w\",\"watcher_state\":\"started\",\"watch_count\":0,\"execution_thread_pool\":{\"queue_size\":0,\"max_size\":0}},{\"node_id\":\"zxGWpG4yRSO_e2B8k2Xyqw\",\"watcher_state\":\"stopped\",\"watch_count\":0,\"execution_thread_pool\":{\"queue_size\":0,\"max_size\":0}},{\"node_id\":\"orv9jd8cTkOqJNipcPYfNg\",\"watcher_state\":\"started\",\"watch_count\":0,\"execution_thread_pool\":{\"queue_size\":0,\"max_size\":1}}]}"


at __randomizedtesting.SeedInfo.seed([3DE603A8143C17BA:A8BE0D275F20CEE3]:0) |  
-- | --
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.upgrades.WatcherRestartIT.lambda$ensureWatcherStarted$2(WatcherRestartIT.java:153) |  
  |   | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1014) |  
  |   | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:987) |  
  |   | at org.elasticsearch.upgrades.WatcherRestartIT.ensureWatcherStarted(WatcherRestartIT.java:147) |  
  |   | at org.elasticsearch.upgrades.WatcherRestartIT.testWatcherRestart(WatcherRestartIT.java:40)



```

### PR DESCRIPTION
**Pull request by martijnvg**
* The WatcherIndexTemplateRegistry moved from legacy templates to composable index templates in version 7.10.0 and not 7.9.0
* The WatcherIndexTemplateRegistry#validate(...) method should only care whether a template for watcher history indices exist and
not whether that template is a composable index template or a legacy template. This shouldn't matter whether to determine if watcher can be started on a node. The content of the templates didn't change in a breaking manner (since version 6.8.0).

(marking as non-issue, as this hasn't yet been released)

Closes #69918

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ public WatcherIndexTemplateRegistry(Settings nodeSettings, ClusterService cluste
 
     @Override
     protected List<IndexTemplateConfig> getLegacyTemplateConfigs() {
-        if (clusterService.state().nodes().getMinNodeVersion().onOrAfter(Version.V_7_9_0)) {
+        if (clusterService.state().nodes().getMinNodeVersion().onOrAfter(Version.V_7_10_0)) {
```
Comment (martijnvg) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java:76]: See: https://github.com/elastic/elasticsearch/blob/7.9/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java#L73

**Comment by martijnvg** [comment]
Locally also ran `./gradlew ':x-pack:qa:rolling-upgrade:v7.10.2#bwcTest'` and `./gradlew ':x-pack:qa:rolling-upgrade:v7.9.2#bwcTest'`, which passed (without this change, these test runs fail)(this isn't ran as part of pr build, but is on [the bwc build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc/). 

I will also run `./gradlew ':x-pack:qa:rolling-upgrade:bwcTest'`, which runs rolling upgrade for all supported versions (may take a while).

**Comment by martijnvg** [comment]
@elasticmachine run bwcTest

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
(merged after `./gradlew ':x-pack:qa:rolling-upgrade:bwcTest'` locally passed)
