### PR TITLE
ES|QL: fix _index LIKE with ? wildcard

### LINKED ISSUE #146364: ESQL: _index LIKE with `?` in pattern doesn't work
Reproducer:
```
FROM k8s-downsampled METADATA _index
| WHERE _index LIKE "k8s?downsampled"
| STATS c = COUNT(*);

c:long
27
;
```

A cursory investigation with @ivancea has shown that `IndexFieldMapper` overrides `wildcardLilkeQuery` and [internally uses](https://github.com/elastic/elasticsearch/blob/43546651315a7d9411d83f26fdbc68eeede94d42/server/src/main/java/org/elasticsearch/index/mapper/IndexFieldMapper.java#L133) `Regex.simpleMatch`. The latter doesn't seem to respect `?`, only `*`.

Cc @julian-elastic

### PR DESCRIPTION
**Pull request by alighahramani-alig**
wildcardLikeQuery used Regex.simpleMatch which only handles *, so ? was treated as a literal character. Replaced with Lucene's WildcardQuery.toAutomaton which handles both.

Closes #146364 
Assisted by Claude

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/IndexFieldMapper.java [hunk 1]
```diff
@@ -130,7 +133,10 @@ private static Query getWildcardLikeQuery(String value, boolean caseInsensitve,
                 value = value.toLowerCase(Locale.ROOT);
                 indexName = indexName.toLowerCase(Locale.ROOT);
             }
-            if (Regex.simpleMatch(value, indexName)) {
+            CharacterRunAutomaton runAutomaton = new CharacterRunAutomaton(
```
Comment (julian-elastic) [inline server/src/main/java/org/elasticsearch/index/mapper/IndexFieldMapper.java]: It seems elsewhere we catch an exception to convert 500 error to 400. 
try {
          return doCreateAutomaton(ignoreCase);
      } catch (TooComplexToDeterminizeException e) {
          throw new IllegalArgumentException("Pattern was too complex to determinize", e);
      }

**Review by julian-elastic — CHANGES_REQUESTED** [review]
Please see my comment below. Also lets talk about backporting before merging the PR

**Review by julian-elastic — APPROVED** [review]
Looks good, thank you for addressing my concern with the missing exception handling.
