### PR TITLE
SQL: CAST supports both SQL and ES types

### LINKED ISSUE #40282: SQL: CAST failures for float value
The following CASTs of a float value lead to failures:
* `SCALED_FLOAT`:
```
sql> select cast('0.' as SCALED_FLOAT);
Bad request [line 1:22: Does not recognize type [SCALED_FLOAT]]
```
* same for `HALF_FLOAT`;
* any integer type:
```
sql> select cast('0.0' as long);
Server error [Server encountered an error [cannot cast [0.0] to [long]]. [SqlIllegalArgumentException[cannot cast [0.0] to [long]]; nested: NumberFormatException[For input string: "0.0"];
```

### PR DESCRIPTION
**Pull request by costin**
Extend CAST to support all data types notations (whether SQL or ES
specific)

Fix #40282

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java [hunk 1]
```diff
@@ -107,6 +107,29 @@ public void testIncompatibleInterval() throws Exception {
         assertNull(compatibleInterval(INTERVAL_HOUR, INTERVAL_MONTH));
         assertNull(compatibleInterval(INTERVAL_MINUTE_TO_SECOND, INTERVAL_MONTH));
     }
+    
+    public void testEsToDataType() throws Exception {
+        String type = randomFrom("null", "boolean", "bool",
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java]: Can we take the list of types to randomize from from somewhere else, so that in case we change one or we add a new one, we don't have to remember this test here to add here as well?
From `DataType` I think we can do this?

**Review by astefan — APPROVED** [review]
LGTM. Left a comment, though.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java]: +1

**Review by matriv — APPROVED** [review]
LGTM. I agree with the comment about testing.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java]: The thing is the list is only assembled in the `DataType` itself so testing that against itself kinda defeats the purpose. And thus one ends up with a different list that needs to be maintained by hand which I see no way around hence this test in its current form.

Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/type/DataTypesTests.java]: I've extended the list by adding all data types that are primitive to the existing list of strings, which should cover any non-complex types automatically.

**Comment by costin** [comment]
This took longer than expected since I ran into a subtle bug - by supporting both ES types and SQL types we ended up with a name clash, namely `float` which could be interpreted either as SQL (as thus mapped to ES `double`) or ES `float and thus mapped to ... `float`.
I took the former and added a section in the docs about it.
