### PR TITLE
Copy metrics and default_metric properties when downsampling aggregate_metric_double

### LINKED ISSUE #96076: TSDS Downsampling data loss with `aggregate_metric_double` types
### Elasticsearch Version

8.6.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

3.16.0-4-amd64

### Problem Description

When a `aggregate_metric_double` field is created with a subset of metrics sub-fields mappings for downsampled index is created with the full complement of sub-fields resulting in the down-sampling process losing all docs.

### Steps to Reproduce

Create a TSDS index with a mapping template like so:

```json
{
  "template": {
    "mappings": {
      "properties": {
        "@timestamp": { "type": "date", "format": "strict_date_optional_time" },
        "host": { "type": "keyword", "time_series_dimension": true },
        "calls": { "type": "aggregate_metric_double", "metrics": [ "sum" ], "default_metric": "sum", "time_series_metric": "gauge" }
      }
    }
  }
}
```

Now create the TSDS data stream and you should have a set of backing index with a mapping that looks something like:

```json
{
  ".ds-tsds-test-2023.05.11-000002": {
    "mappings": {
      "_data_stream_timestamp": {
        "enabled": true
      },
      "properties": {
        "@timestamp": {
          "type": "date",
          "format": "strict_date_optional_time"
        },
        "host": {
          "type": "keyword",
          "time_series_dimension": true
        },
        "calls": {
          "type": "aggregate_metric_double",
          "metrics": [
            "sum"
          ],
          "default_metric": "sum",
          "time_series_metric": "gauge"
        }
      }
    }
  }
}
```

If you then have an ILM policy that down samples for a stage, e.g.:

```json
"warm": {
  "min_age": "7d",
  "actions": {
    "set_priority": { "priority": 40 },
    "downsample": { "fixed_interval": "5m" },
    "shrink": { "number_of_shards": 1 },
    "forcemerge": { "max_num_segments": 1 }
  }
}
```

And trigger it either by waiting the given time or adjusting the index age you will end up with a down-sampled index with a mapping like the following and with 0 docs:

```json
{
  "shrink-ujei-downsample-te_v-.ds-tsds-test-2023.05.11-000001": {
    "mappings": {
      "_data_stream_timestamp": {
        "enabled": true
      },
      "dynamic_templates": [
        {
          "strings": {
            "match_mapping_type": "string",
            "mapping": {
              "type": "keyword"
            }
          }
        }
      ],
      "properties": {
        "@timestamp": {
          "type": "date",
          "meta": {
            "fixed_interval": "5m",
            "time_zone": "UTC"
          }
        },
        "host": {
          "type": "keyword",
          "time_series_dimension": true
        },
        "calls": {
          "type": "aggregate_metric_double",
          "metrics": [
            "min",
            "max",
            "sum",
            "value_count"
          ],
          "default_metric": "max",
          "time_series_metric": "gauge"
        }
      }
    }
  }
}
```

Notice how the `min`, `max`, and `value_count` sub-fields exist in the downsampled mapping but not in the template / original mapping. This in turn causes the downsampled docs to be not indexable resulting in all data being dropped.

### Logs (if relevant)

```
[2023-05-11T20:11:25,576][ERROR][o.e.x.d.RollupShardIndexer] [es1.test.example.com] Shard [[.ds-tsds-test-2023.05.11-000001][4]] failed to populate rollup index. Failures: [{null=org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [calls] of type [aggregate_metric_double] in a time series document at [2023-05-10T07:35:00.000Z]. Preview of field's value: 'null',...
```

### LINKED ISSUE #119696: `default_metric` field is not propagated when downsampling an `aggregate_metric_double` field
### Elasticsearch Version

9.0 and before

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

-

### Problem Description

`default_metric` mapping parameter is lost during downsampling.

### Steps to Reproduce

Downsample an index with the following mapping:
```
"m": {
  "type": "aggregate_metric_double",
  "metrics": ["min", "max", "sum", "value_count"],
  "default_metric": "min",
  "time_series_metric": "gauge"
}
```

Downsampled index has the following mapping:
```
"m": {
    "type": "aggregate_metric_double",
    "metrics": [
        "min",
        "max",
        "sum",
        "value_count"
    ],
    "default_metric": "max",
    "time_series_metric": "gauge"
}
```

Note the change of `default_metric` from `min` to `max`.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jordan-powers**
Fixes #119696
Fixes #96076

### CODE REVIEW

File: x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java [hunk 1]
```diff
@@ -752,9 +753,22 @@ private static void addMetricFieldMapping(final XContentBuilder builder, final S
                 builder.field(fieldProperty, fieldProperties.get(fieldProperty));
             }
         } else {
-            final String[] supportedAggsArray = metricType.supportedAggs();
+            List<String> supportedAggs = List.of(metricType.supportedAggs());
             // We choose max as the default metric
-            final String defaultMetric = List.of(supportedAggsArray).contains("max") ? "max" : supportedAggsArray[0];
+            String defaultMetric = supportedAggs.contains("max") ? "max" : supportedAggs.get(0);
```
Comment (martijnvg) [inline x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:758]: Maybe isolate the logic that extracts default metrics in a (static?) method? Then we can maybe add a unit test for this in `TransportDownsampleActionTests`.

**Review by martijnvg — APPROVED** [review]
One minor comment, LGTM otherwise.

I think merge conflict comes from #121254, shouldn't be to difficult to fix.

File: x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java [hunk 2]
```diff
@@ -752,12 +786,13 @@ private static void addMetricFieldMapping(final XContentBuilder builder, final S
...
-            // We choose max as the default metric
-            final String defaultMetric = List.of(supportedAggsArray).contains("max") ? "max" : supportedAggsArray[0];
+            var supported = getSupportedMetrics(metricType, fieldProperties);
+
+            String[] supportedMetricsArray = supported.supportedMetrics.toArray(String[]::new);
+
             builder.field("type", AggregateMetricDoubleFieldMapper.CONTENT_TYPE)
-                .array(AggregateMetricDoubleFieldMapper.Names.METRICS, supportedAggsArray)
-                .field(AggregateMetricDoubleFieldMapper.Names.DEFAULT_METRIC, defaultMetric)
+                .array(AggregateMetricDoubleFieldMapper.Names.METRICS, supportedMetricsArray)
```
Comment (lkts) [inline x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:794]: nit: looks like you could use `stringListField` and avoid the array

**Review by lkts — APPROVED** [review]

File: x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java (hunk 2 above)
Comment (jordan-powers) [reply x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:794]: Ah, I thought there might be an API like that, but I couldn't find it. Thanks!
