### PR TITLE
Explicitly set packaging permissions

### LINKED ISSUE #17634: Packaging tests fail and package installation is dependent on user's umask
When running the packages on my development machines, they fail due to incorrect expected permissions, for example, my `umask` permissions are 002, which means that directories are created with 775 permissions, however, our tests compare the directories from the *user* with the ones generated by a *root* install, which has a different umask (022).

Thus, you get:

```
# Expected privileges: 775, found 755
not ok 10 [TAR PLUGINS] install jvm-example plugin with a custom CONFIG_DIR
# (from function `assert_file' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash, line 181,
#  from function `install_jvm_example' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/plugins.bash, line 87,
#  in test file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/25_tar_plugins.bats, line 143)
#   `CONF_DIR="$ESCONFIG" install_jvm_example' failed
```

And

```
# Expected privileges: 644, found 664
not ok 27 [TAR PLUGINS] check lang-expression module
# (from function `assert_file' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash, line 181,
#  from function `assert_module_or_plugin_file' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash, line 208,
#  from function `check_module' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/modules.bash, line 35,
#  from function `check_secure_module' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/modules.bash, line 43,
#  in test file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/25_tar_plugins.bats, line 242)
#   `check_secure_module lang-expression antlr4-runtime-*.jar asm-5.0.4.jar asm-commons-*.jar asm-tree-*.jar lucene-expressions-*.jar' failed
# Should exist: /tmp/elasticsearch/modules/lang-expression
```

(and many others)

I think there are multiple options for fixing this:

1. Set the umask bats will expect in the tests before these tests are run
2. Change the tests to hardcode the correct "expected" permissions instead of
   inferring them from the user's directory
3. Change our packaging to set the permissions correctly instead of relying on
   umask

Personally, I think we should go with number 3.

Number 1 I'm not actually sure would work, I haven't tested it, but we would be
fooling ourselves if anyone actually changed their umask in the field.

Number 2 would be semi-okay, but again, if the umask changes or a user installs
the package as non-root (yes, with `dpkg --force-not-root`) the permissions will
be different because root's umask will not be used.

I really don't like the variance of number 1 and number 2, we have a lot of
checks to tell users when their settings may be wrong, this is a situation where
we should set the permissions to the exact values they should be to prevent
unintended errors. Hence, I believe we should go with number 3.

### PR DESCRIPTION
**Pull request by dakrone**
This changes our packaging to be explicit about the permissions of files
and directories in the tar.gz, rpm, and deb packages. This is to protect
against a user having an incorrectly set umask when installing.

Additionally, plugins that are installed now have their permissions set
by the plugin installation so that plugins that may have been packaged
with incorrect permissions are secured.

As a nice side effect of this PR, I can now actually run the vagrant tests
on my development machine, which previously failed due to
umask problems.

Resolves #17634

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 1]
```diff
@@ -134,6 +134,26 @@
     private final OptionSpec<Void> batchOption;
     private final OptionSpec<String> arguments;
 
+    public static final Set<PosixFilePermission> dirAndExecutablePerms = new HashSet<>(7);
+    public static final Set<PosixFilePermission> filePerms = new HashSet<>(4);
+
+    static {
+        // Directories and executables get chmod 755
+        dirAndExecutablePerms.add(PosixFilePermission.OWNER_EXECUTE);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Can we create a local set, add the permissions to that set, and then make `dirAndExecutablePerms` an unmodifiable copy of the local set?

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 2]
```diff
@@ -134,6 +134,26 @@
...
+        dirAndExecutablePerms.add(PosixFilePermission.OWNER_READ);
+        dirAndExecutablePerms.add(PosixFilePermission.OWNER_WRITE);
+        dirAndExecutablePerms.add(PosixFilePermission.GROUP_EXECUTE);
+        dirAndExecutablePerms.add(PosixFilePermission.GROUP_READ);
+        dirAndExecutablePerms.add(PosixFilePermission.OTHERS_READ);
+        dirAndExecutablePerms.add(PosixFilePermission.OTHERS_EXECUTE);
+
+        // Files get chmod 644
+        filePerms.add(PosixFilePermission.OWNER_READ);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Same thing here: can we create a local set, add the permissions to that set, and then make `filePerms` an unmodifiable copy of the local set?

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 3]
```diff
@@ -134,6 +134,26 @@
     private final OptionSpec<Void> batchOption;
     private final OptionSpec<String> arguments;
 
+    public static final Set<PosixFilePermission> dirAndExecutablePerms = new HashSet<>(7);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Can we name this like a constant `DIR_AND_EXECUTABLE_PERMS`?

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 4]
```diff
@@ -134,6 +134,26 @@
...
+    public static final Set<PosixFilePermission> filePerms = new HashSet<>(4);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Can we name this like a constant `FILE_PERMS`?

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 5]
```diff
@@ -409,6 +421,15 @@ private void install(Terminal terminal, boolean isBatch, Path tmpRoot) throws Ex
             }
 
             Files.move(tmpRoot, destination, StandardCopyOption.ATOMIC_MOVE);
+            try (DirectoryStream<Path> stream = Files.newDirectoryStream(destination)) {
+                for (Path pluginFile : stream) {
+                    if (Files.isDirectory(pluginFile)) {
+                        Files.setPosixFilePermissions(pluginFile, dirAndExecutablePerms);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Sadly, I think that these need to be guarded (e.g., Windows does not have POSIX support).

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 6]
```diff
@@ -427,17 +448,7 @@ private void installBin(PluginInfo info, Path tmpBinDir, Path destBinDir) throws
...
-        final Set<PosixFilePermission> perms = new HashSet<>();
-        final PosixFileAttributeView binAttributeView = Files.getFileAttributeView(destBinDir.getParent(), PosixFileAttributeView.class);
-        if (binAttributeView != null) {
-            perms.addAll(binAttributeView.readAttributes().permissions());
-            // setting execute bits, since this just means "the file is executable", and actual execution requires read
-            perms.add(PosixFilePermission.OWNER_EXECUTE);
-            perms.add(PosixFilePermission.GROUP_EXECUTE);
-            perms.add(PosixFilePermission.OTHERS_EXECUTE);
-        }
+        Files.setPosixFilePermissions(destBinDir, dirAndExecutablePerms);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Needs a guard.

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 7]
```diff
@@ -449,11 +460,7 @@ private void installBin(PluginInfo info, Path tmpBinDir, Path destBinDir) throws
 
                 Path destFile = destBinDir.resolve(tmpBinDir.relativize(srcFile));
                 Files.copy(srcFile, destFile);
-
-                final PosixFileAttributeView view = Files.getFileAttributeView(destFile, PosixFileAttributeView.class);
-                if (view != null) {
-                    view.setPermissions(perms);
-                }
+                Files.setPosixFilePermissions(destFile, dirAndExecutablePerms);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Needs a guard.

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 8]
```diff
@@ -468,8 +475,7 @@ private void installConfig(PluginInfo info, Path tmpConfigDir, Path destConfigDi
             throw new UserError(ExitCodes.IO_ERROR, "config in plugin " + info.getName() + " is not a directory");
         }
 
-        // create the plugin's config dir "if necessary"
-        Files.createDirectories(destConfigDir);
+        Files.createDirectories(destConfigDir, PosixFilePermissions.asFileAttribute(dirAndExecutablePerms));
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Needs a guard.

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 9]
```diff
@@ -487,6 +493,7 @@ private void installConfig(PluginInfo info, Path tmpConfigDir, Path destConfigDi
                 Path destFile = destConfigDir.resolve(tmpConfigDir.relativize(srcFile));
                 if (Files.exists(destFile) == false) {
                     Files.copy(srcFile, destFile);
+                    Files.setPosixFilePermissions(destFile, filePerms);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Needs a guard.

**Comment by jasontedor** [comment]
Other than the POSIX permissions not being guarded, I left one comment about the creation of the permissions objects. Everything else looks great.

**Comment by jasontedor** [comment]
LGTM.
