### PR TITLE
DISCOVERY: Fix RollingUpgradeTests

### LINKED ISSUE #35178: Fix discovery in rolling upgrade tests
#33675 has improved how discovery is configured in most tests, but the rolling upgrade tests still have vestiges of the old way of doing things, particularly:

- explicitly setting `minimum_master_nodes` to 3 on freshly-started nodes
- manually configuring the unicast hosts list rather than relying on file-based discovery

This pertains to at least:

- `:qa:rolling-upgrade`
- `:x-pack:qa:rolling-upgrade-basic`
- `:x-pack:qa:rolling-upgrade`

### PR DESCRIPTION
**Pull request by original-brownbear**
* Don't manually manage min master nodes
* Regarding the issue asking to use file based discovery: This already happens. We are passing the transportURIs in a hacky way via the node property and they are written to the discovery file in `6.5` and newer  so I don't think we have to do anything about that here.
* Remove some dead code
* Closes #35178

### CODE REVIEW

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterConfiguration.groovy [hunk 1]
```diff
@@ -110,6 +110,14 @@ class ClusterConfiguration {
         return seedNode.transportUri()
     }
 
+    /**
+     * A closure to call which returns a manually supplied list of unicast seed hosts.
+     */
+    @Input
+    Closure<List<String>> manualSeedUris = {
```
Comment (DaveCTurner) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterConfiguration.groovy]: How about `otherUnicastHostAddresses` (they're not really URIs, and "seed" isn't quite the right word either)

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy [hunk 2]
```diff
@@ -715,10 +715,15 @@ class ClusterFormationTasks {
...
             Collection<String> unicastHosts = new HashSet<>()
-            nodes.forEach { otherNode ->
-                String unicastHost = otherNode.config.unicastTransportUri(otherNode, null, project.ant)
-                if (unicastHost != null) {
-                    unicastHosts.addAll(Arrays.asList(unicastHost.split(",")))
+            nodes.forEach { node ->
+                List<String> manualSeedUris = node.config.manualSeedUris.call()
+                if (manualSeedUris.empty == false) {
+                    unicastHosts.addAll(manualSeedUris)
+                } else {
```
Comment (DaveCTurner) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: I think the unicast hosts file should be the _union_ of these, so no need for the `else`.

File: qa/rolling-upgrade/build.gradle [hunk 3]
```diff
@@ -77,8 +76,7 @@ for (Version version : bwcVersions.wireCompatible) {
     configure(extensions.findByName("${baseName}#${name}")) {
       dependsOn lastRunner, "${baseName}#oldClusterTestCluster#node${stopNode}.stop"
       clusterName = 'rolling-upgrade'
-      unicastTransportUri = { seedNode, node, ant -> unicastSeed() }
-      minimumMasterNodes = { 3 }
+      manualSeedUris = { unicastSeed() }
```
Comment (DaveCTurner) [inline qa/rolling-upgrade/build.gradle]: Also would prefer to avoid `Seed` (in `unicastSeed`) here 🌱

File: x-pack/qa/rolling-upgrade-basic/build.gradle [hunk 4]
```diff
@@ -58,8 +54,7 @@ for (Version version : bwcVersions.wireCompatible) {
         configure(extensions.findByName("${baseName}#${name}")) {
             dependsOn lastRunner, "${baseName}#oldClusterTestCluster#node${stopNode}.stop"
             clusterName = 'rolling-upgrade-basic'
-            unicastTransportUri = { seedNode, node, ant -> unicastSeed() }
-            minimumMasterNodes = { 3 }
+            manualSeedUris = { unicastSeed() }
```
Comment (DaveCTurner) [inline x-pack/qa/rolling-upgrade-basic/build.gradle]: Also would prefer to avoid `Seed` (in `unicastSeed`) here 🌱

File: x-pack/qa/rolling-upgrade/build.gradle [hunk 5]
```diff
@@ -188,8 +186,7 @@ subprojects {
         dependsOn lastRunner, "${baseName}#oldClusterTestCluster#node${stopNode}.stop"
         setupCommand 'setupTestUser', 'bin/elasticsearch-users', 'useradd', 'test_user', '-p', 'x-pack-test-password', '-r', 'superuser'
         clusterName = 'rolling-upgrade'
-        unicastTransportUri = { seedNode, node, ant -> unicastSeed() }
-        minimumMasterNodes = { 3 }
+        manualSeedUris = { unicastSeed() }
```
Comment (DaveCTurner) [inline x-pack/qa/rolling-upgrade/build.gradle]: Also would prefer to avoid `Seed` (in `unicastSeed`) here 🌱

**Review by DaveCTurner — COMMENTED** [review]
Looks great. Just a few minor nits.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy (hunk 2 above)
Comment (original-brownbear) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: I think I agree, unfortunately this forces us to manually set min master nodes (just tried it out). The reason being that the nodes that we have join the cluster effectively think they're in a 1 node cluster => if we add the node itself to the unicast hosts here it blows up => I'll add the min master nodes setting back but set it to  `2` maybe so it's more realistic + make it merge the lists here?

Comment (original-brownbear) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: We can still drop the min master node setting for the initial `oldCluster` though :)

**Comment by original-brownbear** [comment]
@DaveCTurner  Thanks for the review! => All suggestions applied (see me comment on the min master nodes though).

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy (hunk 2 above)
Comment (DaveCTurner) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: Bah of course, it's a different cluster from Gradle's point of view, so yes we need to set `minimum_master_nodes` on the new nodes.

I'm surprised that adding the node to its own unicast hosts list makes a difference, I think this would be broken either way:

https://github.com/elastic/elasticsearch/blob/93c2c604e57cae4ba093c7053dec604a33d89e36/server/src/main/java/org/elasticsearch/discovery/zen/UnicastZenPing.java#L213-L214

Comment (original-brownbear) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: Hmm it did work when I ran it locally :D but yea, set them to `2` now on the 1 node "clusters" and it passed fine locally.

**Comment by DaveCTurner** [comment]
> All suggestions applied

Except for the ones about losing `Seed` from `unicastSeed`. How about `getOtherUnicastHostAddresses`?

**Comment by original-brownbear** [comment]
@DaveCTurner ah sure will rename to `getOtherUnicastHostAddresses` (sorry missed that one since it was named like that before) as well.

**Comment by original-brownbear** [comment]
@DaveCTurner renamed to `getOtherUnicastHostAddresses` :)

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks @original-brownbear.

**Comment by original-brownbear** [comment]
@DaveCTurner thanks for the review!
