### PR TITLE
Set `keyUsage` for generated HTTP certificates and self-signed CA

### LINKED ISSUE #117769: Elasticsearch CA certificates are rejected by Python 3.13
### Elasticsearch Version

8.16.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin arm64

### Problem Description

Python 3.13 (released in October 2024) [enabled by default the VERIFY_X509_STRICT](https://github.com/python/cpython/issues/107361) flag for improved RFC 5280 compliance. This setting maps to the [X509_V_FLAG_X509_STRICT OpenSSL flag](https://docs.openssl.org/1.1.1/man3/X509_VERIFY_PARAM_set_flags/#verification-flags) documented as:

> The `X509_V_FLAG_X509_STRICT` flag disables workarounds for some broken certificates and makes the verification strictly apply `X509` rules.

The CA certificates generated by Elasticsearch (either by default on startup) or by elasticsearch-certutil are not compliant, at least because they're missing the key usage extension.

### Steps to Reproduce

Run Elasticsearch:

```
$ docker run --name es01 -p 9200:9200 -it -m 1GB docker.elastic.co/elasticsearch/elasticsearch:8.16.1
... wait for startup
$ docker container cp es01:/usr/share/elasticsearch/config/certs/http_ca.crt .
```

Try connecting to it using the Elasticsearch Python client:

```python
from elasticsearch import Elasticsearch

client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="http_ca.crt",
    basic_auth=("elastic", "...")
)
print(client.info())
```

This fails with:

```python
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA cert does not include key usage extension (_ssl.c:1020)
```

Alternatively, you can inspect the `http_ca.crt` file:

```bash
$ openssl x509 -in http_ca.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a4:50:12:ea:89:c9:78:fe:9e:9a:4b:7c:64:18:e0:13:04:d6:fb:58
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Elasticsearch security auto-configuration HTTP CA
        Validity
            Not Before: Nov 29 14:07:47 2024 GMT
            Not After : Nov 29 14:07:47 2027 GMT
        Subject: CN=Elasticsearch security auto-configuration HTTP CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    [...]]
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                F4:BC:A2:F5:ED:8B:FD:93:F2:AE:76:82:A2:58:9E:EE:58:82:B9:BC
            X509v3 Authority Key Identifier: 
                F4:BC:A2:F5:ED:8B:FD:93:F2:AE:76:82:A2:58:9E:EE:58:82:B9:BC
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        [...]
```

In `X509v3 extensions`, you can see that the `Key Usage` extension is missing. If by contrast, I'm looking at the test CA certificate generated by [trustme](https://trustme.readthedocs.io/en/latest/) and used in the Python client:

```
$ openssl x509 -in .buildkite/certs/ca.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            21:80:a5:61:65:e2:4e:c0:7c:68:ca:c4:10:ca:f3:76:b9:39:ac:eb
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: O=trustme v1.2.0, OU=Testing CA #biw1Wc10lpqCFQL5
        Validity
            Not Before: Jan  1 00:00:00 2000 GMT
            Not After : Jan  1 00:00:00 3000 GMT
        Subject: O=trustme v1.2.0, OU=Testing CA #biw1Wc10lpqCFQL5
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    [...]
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                2A:C6:19:C3:BD:BF:45:00:59:2B:03:F7:73:FF:C7:63:13:36:22:5B
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:9
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
    Signature Algorithm: ecdsa-with-SHA256
    Signature Value:
        [...]
```

You can see that `Key Usage` is included, and indeed connections to Python 3.13 work.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by slobodanadamovic**
The `elasticsearch-certutil http` command, and security auto-configuration, generate the HTTP certificate and CA without setting the `keyUsage` extension.

This PR fixes this by setting (by default):
- `keyCertSign` and `cRLSign` for self-signed CAs 
- `digitalSignature` and `keyEncipherment` for HTTP certificates and CSRs

These defaults can be overridden when running `elasticsearch-certutil http` command. 
The user will be prompted to change them as they wish.

For `elasticsearch-certutil ca`, the default value can be overridden by passing the `--keysage` option, e.g.
```
elasticsearch-certutil ca --keyusage "digitalSignature,keyCertSign,cRLSign" -pem    
```

Fixes #117769

### CODE REVIEW

**Review by tvernum — COMMENTED** [review]
Did you consider whether `elasticsearch-certutil ca` should be changed?
It's typically not used as a HTTP ca, but our docs to show how it can be.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java [hunk 1]
```diff
@@ -14,6 +14,7 @@
 import org.bouncycastle.asn1.x509.ExtendedKeyUsage;
 import org.bouncycastle.asn1.x509.GeneralNames;
 import org.bouncycastle.asn1.x509.KeyPurposeId;
+import org.bouncycastle.asn1.x509.KeyUsage;
```
[the remark this answers is not in the document]
Comment (slobodanadamovic) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java:17]: I've missed that part. I'll adjust it to default to `keyCertSign` and `cRLSign`, but make it overridable.

**Comment by slobodanadamovic** [comment]
> Did you consider whether `elasticsearch-certutil ca` should be changed?

Honestly, I haven't but it does make sense. I'll make it default to `keyCertSign` and `cRLSign` but also make it overridable if necessary.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertGenUtils.java [hunk 2]
```diff
@@ -347,7 +380,9 @@ static PKCS10CertificationRequest generateCSR(
         if (sanList != null) {
             extGen.addExtension(Extension.subjectAlternativeName, false, sanList);
         }
-
+        if (keyUsage != null) {
+            extGen.addExtension(Extension.keyUsage, true, keyUsage);
```
Comment (slobodanadamovic) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertGenUtils.java:384]: It's debatable if CSR should include `keyUsage`. I went with adding it to the request and letting the issuer decide if it should be respected or not.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java [hunk 3]
```diff
@@ -979,6 +1039,31 @@ private static Integer readKeySize(Terminal terminal, int keySize) {
         });
     }
 
+    private static List<String> readKeyUsage(Terminal terminal, List<String> defaultKeyUsage) {
```
Comment (slobodanadamovic) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java:1042]: The current implementation of `readKeyUsage` will not allow users to remove the `keyUsage`, but rather only to change the default value. I think this is okay, otherwise it would defeat the purpose of adding it in the first place (but I may oversee a use case where this could be a requirement).

Let me know if you think we should allow it to be overridden to a "none".

**Comment by slobodanadamovic** [comment]
@tvernum I've fixed [the missed place](https://github.com/elastic/elasticsearch/pull/126376#discussion_r2030523291) to add key usage and also made the default key usage overridable when running both `elasticsearch-certutil http` and `elasticsearch-certutil ca` commands. Please take another look.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java [hunk 4]
```diff
@@ -309,6 +330,18 @@ final int getKeySize(OptionSet options) {
             }
         }
 
+        final List<String> getCaKeyUsage(OptionSet options) {
+            if (options.has(caKeyUsageSpec)) {
+                String rawCaKeyUsage = caKeyUsageSpec.value(options);
```
Comment (tvernum) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java:335]: Should this be `values` so that users can pass `--ca-keyusage=keyCertSign --ca-keyusage=keyAgreement` (as is the case with `--dns` and `--ip`)

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java [hunk 5]
```diff
@@ -274,6 +278,23 @@ final void acceptInputFile() {
             inputFileSpec = parser.accepts("in", "file containing details of the instances in yaml format").withRequiredArg();
         }
 
+        final void acceptCertificateAuthorityKeyUsage() {
+            OptionSpecBuilder builder = parser.accepts(
+                "ca-keyusage",
```
Comment (tvernum) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java:283]: If we only support this on `certutil ca` then we can just rename it to `--keyusage` (drop the "ca-" prefix)

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java [hunk 6]
```diff
@@ -247,6 +250,7 @@ final void acceptsCertificateAuthority() {
                 .withOptionalArg();
 
             acceptsCertificateAuthorityName();
+            acceptCertificateAuthorityKeyUsage();
```
Comment (tvernum) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java:253]: I think we want to drop this (because we don't support generating a ca on the fly any more, since 8.0 I think)

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java (hunk 3 above)
Comment (tvernum) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/HttpCertificateCommand.java:1042]: I think for `http` it's fine - I'm not even sure we _need_ to let them change it.
If they want unlimited options they can use `openssl` (and suffer in pain)

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertGenUtils.java [hunk 7]
```diff
@@ -73,14 +78,78 @@ public class CertGenUtils {
...
+     * <li>keyEncipherment         (2)</li>
+     * <li>dataEncipherment        (3)</li>
+     * <li>keyAgreement            (4)</li>
+     * <li>keyCertSign             (5)</li>
+     * <li>cRLSign                 (6)</li>
+     * <li>encipherOnly            (7)</li>
+     * <li>decipherOnly            (8)</li>
+     * </ul>
+     */
+    public static final Map<String, Integer> KEY_USAGE_BITS = Map.of(
```
[the remark this answers is not in the document]
Comment (slobodanadamovic) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertGenUtils.java]: Yes. I've pushed https://github.com/elastic/elasticsearch/pull/126376/commits/41b982f707a0cff716fef060add147bb1b207b31

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java (hunk 4 above)
Comment (slobodanadamovic) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java]: Much nicer! Thanks for the suggestion. I've pushed https://github.com/elastic/elasticsearch/pull/126376/commits/5fdda888ae611cfd57364106e3599c655a4916dd

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java (hunk 6 above)
Comment (slobodanadamovic) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java]: I wasn't sure for this one and went with adding it. I've removed it. Now it's only applicable with `ca` option (https://github.com/elastic/elasticsearch/pull/126376/commits/5fdda888ae611cfd57364106e3599c655a4916dd).

File: docs/reference/elasticsearch/command-line-tools/certutil.md [hunk 8]
```diff
@@ -99,6 +99,9 @@ The `http` mode guides you through the process of generating certificates for us
 `--ca-dn <name>`
 :   Defines the *Distinguished Name* (DN) that is used for the generated CA certificate. The default value is `CN=Elastic Certificate Tool Autogenerated CA`. This parameter cannot be used with the `csr` or `http` parameters.
 
+`--ca-keyusage <key_usages>`
+:   Specifies a comma-separated list of key usage restrictions (as per RFC 5280) that are used for the generated CA certificate. The default value is `keyCertSign,cRLSign`. This parameter cannot be used with the `csr` or `http` parameters.
```
[the remark this answers is not in the document]
Comment (slobodanadamovic) [reply docs/reference/elasticsearch/command-line-tools/certutil.md]: 👍 pushed https://github.com/elastic/elasticsearch/pull/126376/commits/5fdda888ae611cfd57364106e3599c655a4916dd

File: docs/reference/elasticsearch/command-line-tools/certutil.md [hunk 9]
```diff
@@ -13,10 +13,10 @@ The `elasticsearch-certutil` command simplifies the creation of certificates for
 ```shell
 bin/elasticsearch-certutil
 (
-(ca [--ca-dn <name>] [--days <n>] [--pem])
+(ca [--ca-dn <name>] [--ca-keyusage <key_usages>] [--days <n>] [--pem])
 
 | (cert ([--ca <file_path>] | [--ca-cert <file_path> --ca-key <file_path>])
-[--ca-dn <name>] [--ca-pass <password>] [--days <n>]
+[--ca-dn <name>] [--ca-keyusage <key_usages>] [--ca-pass <password>] [--days <n>]
```
[the remark this answers is not in the document]
Comment (slobodanadamovic) [reply docs/reference/elasticsearch/command-line-tools/certutil.md]: pushed https://github.com/elastic/elasticsearch/pull/126376/commits/5fdda888ae611cfd57364106e3599c655a4916dd and https://github.com/elastic/elasticsearch/pull/126376/commits/e03f0962c669c4db46d8adbad30d85fdb68358c9

**Review by tvernum — APPROVED** [review]
LGTM.

Thanks for the multiple rounds - it ended up being more than a 1 liner.

**Comment by slobodanadamovic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.17|[](https://github.com/elastic/elasticsearch/pull/126448)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
