### PR TITLE
Fix numerous checks for equality and compatibility in mapper field types

### LINKED ISSUE #13112: IP fields cause mapping conflicts
While using the 2.0 branch, @jbudz and I are noticing that `_default_` mappings always cause unresolvable type conflicts.

This is the mapping we are testing with:
```curl
curl -XPOST localhost:9200/logstash-2015.08.25 -d '{
  "mappings":{
    "_default_": {
      "properties":{
        "ip":{
          "type":"ip"
        }
      }
    }
  }
}'
```

And the documents that we are sending:
```
curl -XPOST localhost:9200/_bulk -d '{"index":{"_index":"logstash-2015.08.25","_type":"apache"}}
{"index":"logstash-2015.08.25","ip":"192.168.1.1"}
{"index":{"_index":"logstash-2015.08.25","_type":"nginx"}}
{"index":"logstash-2015.08.25","ip":"192.168.1.1"}
'
```

But the bulk fails with `"Mapper for [ip] conflicts with existing mapping in other types:\n[mapper [ip] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types.]"`. 

Since we are using `_default_` as the type, it seems like `update_all_types` should not be needed, since we are not actually creating the types until the documents are indexed.

### PR DESCRIPTION
**Pull request by rjernst**
The field type tests for mappings had a huge hole: check compatibility
was not tested directly at all! I had meant for this to happen in a
follow up after #8871, and was relying on existing mapping tests.
However, there were a number of issues.

This change reworks the fieldtype tests to be able to check all settable
properties on a field type work with checkCompatibility. It fixes a
handful of small bugs in various field types. In particular, analyzer
comparison was just wrong: it was comparing reference equality for
search analyzer instead of the analyzer name. There was also no check
for search quote analyzer.

closes #13112

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/analysis/NamedAnalyzer.java [hunk 1]
```diff
@@ -104,4 +106,17 @@ public void setReusableComponents(Analyzer a, String f, TokenStreamComponents c)
...
         }
     };
+
+    @Override
+    public boolean equals(Object o) {
+        if (this == o) return true;
+        if (!(o instanceof NamedAnalyzer)) return false;
+        NamedAnalyzer that = (NamedAnalyzer) o;
+        return Objects.equals(name, that.name);
+    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/analysis/NamedAnalyzer.java]: I don't have a better idea, but this makes me slightly nervous since nothing in the API prevents you from doing

```java
Analyzer a1 = new NamedAnalyzer("foo", someAnalyzer);
Analyzer a2 = new NamedAnalyzer("foo", otherAnalyzer);
```

**Comment by jpountz** [comment]
I left one question about the equality checks but I don't have better ideas... This is good progress compared to what we have in master though so feel free to push even if you don't have ideas how to improve it either.

File: core/src/main/java/org/elasticsearch/index/analysis/NamedAnalyzer.java (hunk 1 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/analysis/NamedAnalyzer.java]: Since an analyzer is essentially code (made up of bundles of other code like tokenizers and token filters), I don't think there is really a way to make them comparable. So I'm not sure there is really anything we can do, the name is the only comparable identifier we have.

**Comment by rjernst** [comment]
I will backport this to 2.0 as well, but am waiting on the backport of some geo changes that will make the backport clean.

**Comment by rjernst** [comment]
Here is the 2.0 commit: 9e10e88
