### PR TITLE
Fix Chunked APIs sending incorrect responses to HEAD requests

### LINKED ISSUE #92032: Chunked HTTP APIs send (final/empty) chunk in response to HEAD requests
Responses to `HEAD` requests should contain no body, but we send an empty body instead. That's indistinguishable for one-shot APIs, but with chunked encoding this means we send a single empty chunk as a terminator:

```
00000000  48 45 41 44 20 2f 5f 61  6c 6c 20 48 54 54 50 2f   HEAD /_a ll HTTP/
00000010  31 2e 31 0d 0a 48 6f 73  74 3a 20 6c 6f 63 61 6c   1.1..Hos t: local
00000020  68 6f 73 74 3a 39 32 30  30 0d 0a 41 63 63 65 70   host:920 0..Accep
00000030  74 2d 45 6e 63 6f 64 69  6e 67 3a 20 67 7a 69 70   t-Encodi ng: gzip
00000040  0d 0a 0d 0a                                        ....
    00000000  48 54 54 50 2f 31 2e 31  20 32 30 30 20 4f 4b 0d   HTTP/1.1  200 OK.
    00000010  0a 58 2d 65 6c 61 73 74  69 63 2d 70 72 6f 64 75   .X-elast ic-produ
    00000020  63 74 3a 20 45 6c 61 73  74 69 63 73 65 61 72 63   ct: Elas ticsearc
    00000030  68 0d 0a 63 6f 6e 74 65  6e 74 2d 74 79 70 65 3a   h..conte nt-type:
    00000040  20 61 70 70 6c 69 63 61  74 69 6f 6e 2f 6a 73 6f    applica tion/jso
    00000050  6e 0d 0a 54 72 61 6e 73  66 65 72 2d 45 6e 63 6f   n..Trans fer-Enco
    00000060  64 69 6e 67 3a 20 63 68  75 6e 6b 65 64 0d 0a 0d   ding: ch unked...
    00000070  0a 30 0d 0a 0d 0a                                  .0....
              ^^ should have stopped here!
```

This became particularly noticeable with https://github.com/elastic/elasticsearch/pull/92016 because `HEAD /<index>` is the recognised way to determine if an index exists, but really this is a general problem with the infrastructure introduced in https://github.com/elastic/elasticsearch/pull/88311.

### PR DESCRIPTION
**Pull request by original-brownbear**
Response bodies must always be empty for HEAD requests. Since the request encoder does not know that its dealing with a response to a HEAD request we have to indicate this fact to it. Also, needed to adjust the test http client to use the http-codec so it is able to correlate what responses are meant for HEAD requests and will correctly read responses for HEAD requests.
Without this change the added test reproduces the extra bytes and fails with an assert about more than one response received.

closes #92032

### CODE REVIEW

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java [hunk 1]
```diff
@@ -324,7 +326,15 @@ protected void initChannel(Channel ch) throws Exception {
             ch.pipeline()
                 .addLast("decoder", decoder)
                 .addLast("decoder_compress", new HttpContentDecompressor())
-                .addLast("encoder", new HttpResponseEncoder())
+                .addLast("encoder", new HttpResponseEncoder() {
+                    @Override
+                    protected boolean isContentAlwaysEmpty(HttpResponse msg) {
```
Comment (original-brownbear) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java:331]: Same fix of sorts is used by vert.x, see discussion in https://github.com/netty/netty/issues/6761

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java [hunk 2]
```diff
@@ -324,7 +326,15 @@ protected void initChannel(Channel ch) throws Exception {
...
+                        // non-chunked responses (Netty4HttpResponse extends Netty's DefaultFullHttpResponse) with chunked transfer
+                        // encoding are only sent by us in response to HEAD requests an must always have an empty body
+                        return msg instanceof Netty4HttpResponse && HttpUtil.isTransferEncodingChunked(msg)
```
Comment (original-brownbear) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java:334]: It's a little dirty to guess things like this, but it seemed nicer than unnecessarily adding another field to the netty response implementation.

Comment (DaveCTurner) [reply modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java:334]: Seems _ok_ but would it also work to just check if there's anything in the body (i.e. `((Netty4HttpResponse)msg).content().isReadable()`)? At least IMO we should assert there's no body here.

**Review by DaveCTurner — COMMENTED** [review]
Looks good, one question.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
Are we going to backport this to 8.6 (and maybe even 8.5?). Seems safe enough, although it might not be a very impactful bug it'd be embarrasing for someone to hit it in the months before 8.7 comes out.
