### PR TITLE
[TEST] Handle error in concurrent downsample actions

### LINKED ISSUE #122158: [CI] DownsampleActionSingleNodeTests testDuplicateDownsampleRequest failing
**Build Scans:**
- [elasticsearch-intake #17674 / part2](https://gradle-enterprise.elastic.co/s/mgcyb4mrdiyek)
- [elasticsearch-pull-request #55080 / part-2](https://gradle-enterprise.elastic.co/s/shcmjcodu2e4k)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:downsample:test" --tests "org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests.testDuplicateDownsampleRequest" -Dtests.seed=F5C8F9E8A4AEA95A -Dtests.locale=hr-BA -Dtests.timezone=Africa/Conakry -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDuplicateDownsampleRequest),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=104, name=Thread-9, state=RUNNABLE, group=TGRP-DownsampleActionSingleNodeTests]
```

**Issue Reasons:**
- [main] 2 failures in test testDuplicateDownsampleRequest (0.2% fail rate in 811 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by kkrik-es**
The reported test failure indicates that there are two identical persistent tasks proceeding, which is not an issue with the downsample action (this shouldn't be happening).

Fixes #122158

### CODE REVIEW

File: x-pack/plugin/downsample/src/test/java/org/elasticsearch/xpack/downsample/DownsampleActionSingleNodeTests.java [hunk 1]
```diff
@@ -1760,7 +1760,7 @@ public void testDuplicateDownsampleRequest() throws Exception {
         new Thread(() -> {
             try {
                 downsample(sourceIndex, targetIndex, config);
-            } catch (ResourceAlreadyExistsException e) {
+            } catch (ElasticsearchException e) {
```
Comment (martijnvg) [inline x-pack/plugin/downsample/src/test/java/org/elasticsearch/xpack/downsample/DownsampleActionSingleNodeTests.java:1763]: A persistent task with the same id/name should result in a `ResourceAlreadyExistsException`. However maybe it is wrapped in another exception and that is why the test failed. I think just catching a parent exception is ok here. We could also maybe unwrap the cause? (`ExceptionsHelper`)

**Review by martijnvg — APPROVED** [review]
LGTM

File: x-pack/plugin/downsample/src/test/java/org/elasticsearch/xpack/downsample/DownsampleActionSingleNodeTests.java (hunk 1 above)
Comment (kkrik-es) [reply x-pack/plugin/downsample/src/test/java/org/elasticsearch/xpack/downsample/DownsampleActionSingleNodeTests.java:1763]: The log shows that actually both tasks ran, somehow.. The exception is from the second task failing to write to the target index, as it's marked as read-only by the first one after populating it. I'm not sure how it is possible to have both tasks to run, couldn't reproduce it.
