### PR TITLE
Always rebuild checkpoint tracker for old indices

### LINKED ISSUE #46311: [CI] checkpoint tracker failure in 6.8 cluster upgrade test
BWC tests: 6.5.0 -> 6.8

In `:x-pack:qa:full-cluster-restart:without-system-key:v6.5.0#upgradedClusterTestCluster`

- https://gradle-enterprise.elastic.co/s/gcxbry3p3y6o6/console-log?task=:x-pack:qa:full-cluster-restart:without-system-key:v6.5.0%23upgradedClusterTestCluster%23wait#L258
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc/BWC_VERSION=6.5.0,nodes=centos-7&&immutable/90/console

```
[2019-09-04T10:07:34,985][INFO ][o.e.x.m.e.l.LocalExporter] [node-0] waiting for elected master node [{node-1}{Iu3gP669TKqwgd5WOGm5fw}{IadoUf9wQyGoOw05oGWWrw}{127.0.0.1}{127.0.0.1:35699}{testattr=test, ml.machine_memory=63158317056, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}] to setup local exporter [default_local] (does it have x-pack installed?)
[2019-09-04T10:07:35,162][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] fatal error in thread [elasticsearch[node-0][generic][T#3]], exiting
java.lang.AssertionError: local checkpoint tracker is not updated seq_no=49 id=49
	at org.elasticsearch.index.engine.InternalEngine.compareOpToLuceneDocBasedOnSeqNo(InternalEngine.java:729) ~[elasticsearch-6.8.3-SNAPSHOT.jar:6.8.3-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.planIndexingAsNonPrimary(InternalEngine.java:1012) ~[elasticsearch-6.8.3-SNAPSHOT.jar:6.8.3-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by dnhatn**
The max_seq_no of Lucene commit of the old indices (before 6.6.2) can be smaller than seq_no of some documents in the commit (see https://github.com/elastic/elasticsearch/pull/38879).  Although we fixed this bug in 6.6.2 and 7.0.0, a problematic index commit can still affect the newer version after a rolling upgrade or full cluster restart. In particular, if a FollowingEngine (or InternalEngine with MSU enabled) restores from a problematic commit, then it can apply MSU optimization for existing documents. The symptom that we see here is the local checkpoint tracker [assertion](https://github.com/elastic/elasticsearch/blob/384cbce68e76dd93ec5910bdcef2a5c43d9914c5/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L728-L729) is violated.

Closes #46311
Relates #38879

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/lucene/Lucene.java [hunk 1]
```diff
@@ -1017,20 +1017,18 @@ public CacheHelper getReaderCacheHelper() {
...
+     * This method invokes the callback {@code onNewSeqNo} whenever a sequence number value is found.
      *
      * @param directoryReader the directory reader to scan
      * @param fromSeqNo       the lower bound of a range of seq_no to scan (inclusive)
-     * @param toSeqNo         the upper bound of a range of seq_no to scan (inclusive)
      * @param onNewSeqNo      the callback to be called whenever a new valid sequence number is found
      */
-    public static void scanSeqNosInReader(DirectoryReader directoryReader, long fromSeqNo, long toSeqNo,
-                                          LongConsumer onNewSeqNo) throws IOException {
+    public static void scanSeqNosInReader(DirectoryReader directoryReader, long fromSeqNo, LongConsumer onNewSeqNo) throws IOException {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/common/lucene/Lucene.java]: I would prefer to keep this method signature with fromSeqNo and toSeqNo, and instead invoke it with Long.MAX_VALUE when we have a commit from < 6.6.2

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 2]
```diff
@@ -261,10 +261,12 @@ private static LocalCheckpointTracker createLocalCheckpointTracker(EngineConfig
             // Thus, we need to restore the LocalCheckpointTracker bit by bit to ensure the consistency between LocalCheckpointTracker and
             // Lucene index. This is not the only solution since we can bootstrap max_seq_no_of_updates with max_seq_no of the commit to
             // disable the MSU optimization during recovery. Here we prefer to maintain the consistency of LocalCheckpointTracker.
-            if (localCheckpoint < maxSeqNo && engineConfig.getIndexSettings().isSoftDeleteEnabled()) {
+            // The max_seq_no of Lucene commit in the old indices might be smaller than seq_no of some documents in the commit.
+            // We have to rebuild the LocalCheckpointTracker for those indices. See https://github.com/elastic/elasticsearch/pull/38879.
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: perhaps add a comment that this is only necessary for 6.6.0 and 6.6.1 indices (earlier indices did not have soft-deletes)

**Review by ywelsch — APPROVED** [review]
I've asked for two cosmetic changes, o.w. looking good.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 3]
```diff
@@ -261,10 +261,12 @@ private static LocalCheckpointTracker createLocalCheckpointTracker(EngineConfig
             // Thus, we need to restore the LocalCheckpointTracker bit by bit to ensure the consistency between LocalCheckpointTracker and
             // Lucene index. This is not the only solution since we can bootstrap max_seq_no_of_updates with max_seq_no of the commit to
             // disable the MSU optimization during recovery. Here we prefer to maintain the consistency of LocalCheckpointTracker.
-            if (localCheckpoint < maxSeqNo && engineConfig.getIndexSettings().isSoftDeleteEnabled()) {
+            // The max_seq_no of Lucene commit in the old indices might be smaller than seq_no of some documents in the commit.
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: If this is the case, do we not then also risk that the commit that we use is not the safe commit? Since when we find the safe commit we use the max seq-no and take the newest one with max-seq-no <= global-checkpoint?

This change is still good, but I wonder if we should tackle that in a follow-up?

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 3 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Note that this issue only affected 6.6.0 and 6.6.1 with soft-deletes enabled (when we introduced soft-deletes, which was by default disabled in these releases, and had to be explicitly enabled for CCR indices, back when CCR was still a beta feature). I think we don't need to spend too much engineering effort on this.

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: This bug also affects indices created between 7.0 and 7.2 where soft-deletes are enabled by default.

Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: I'm confused. I thought https://github.com/elastic/elasticsearch/pull/38879 was fixed in 7.0?

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: Sorry, I was confused by the label v7.2.0 in #38879. You're right here.

**Comment by dnhatn** [comment]
run elasticsearch-ci/2

**Comment by dnhatn** [comment]
@ywelsch and @henningandersen Thanks for reviewing.
