### PR TITLE
Fix `minimum should match` in `simple_query_string` for single term and multiple fields

### LINKED ISSUE #13884: Bug with simple_query_string, minimum_should_match, and multiple fields.
```
# With a one-word query and minimum_should_match=-50%, adding extra non-matching fields should not matter.
# Tested on v1.7.2.

# delete and re-create the index
curl -XDELETE localhost:9200/test
curl -XPUT localhost:9200/test

echo 

 # insert a document
curl -XPUT 'http://localhost:9200/test/test/1' -d '
 { "title": "test document"}
 '
curl -XPOST 'http://localhost:9200/test/_refresh'

echo 

 # this correctly finds the document (f1 is a non-existent field)
 curl -XGET 'http://localhost:9200/test/test/_search' -d '{
  "query" : {
    "simple_query_string" : {
      "fields" : [ "title", "f1" ],
      "query" : "test",
      "minimum_should_match" : "-50%"
    }
  }
 }
'

echo 

# this incorrectly does not find the document (f1 and f2 are non-existent fields)
curl -XGET 'http://localhost:9200/test/test/_search' -d '{
  "query" : {
    "simple_query_string" : {
      "fields" : [ "title", "f1", "f2" ],
      "query" : "test",
      "minimum_should_match" : "-50%"
    }
  }
 }
'

echo
```

### PR DESCRIPTION
**Pull request by cbuescher**
Currently a `simple_query_string` query with one term and multiple fields
gets parsed to a BooleanQuery where the number of clauses is determined
by the number of fields, which lead to wrong calculation of `minimum_should_match`.

This PR adds checks to detect this case and wrap the resulting BooleanQuery into
another BooleanQuery with just one should-clause, so `minimum_should_match`
calculation is corrected.

In order to differentiate between the case where one term is queried across
multiple fields and the case where multiple terms are queried on one field,
we override a simplification step in Lucenes SimpleQueryParser that reduces
a one-clause BooleanQuery to the clause itself.

Closes #13884

### CODE REVIEW

**Comment by clintongormley** [comment]
@jdconrad is this something that should go into Lucene's simple query string?

**Comment by cbuescher** [comment]
@dakrone would you mind taking a look at this?

File: core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java [hunk 1]
```diff
@@ -285,8 +287,20 @@ protected Query doToQuery(QueryShardContext context) throws IOException {
         sqp.setDefaultOperator(defaultOperator.toBooleanClauseOccur());
 
         Query query = sqp.parse(queryText);
-        if (minimumShouldMatch != null && query instanceof BooleanQuery) {
-            query = Queries.applyMinimumShouldMatch((BooleanQuery) query, minimumShouldMatch);
+        if (query instanceof BooleanQuery) {
+            BooleanQuery booleanQuery = (BooleanQuery) query;
+            if (booleanQuery.clauses().size() > 1
+                    && ((booleanQuery.clauses().get(0)).getQuery() instanceof BooleanQuery) == false) {
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java]: I'd recommend using the same syntax Lucene does:

```
bq.clauses().iterator().next().getQuery()
```

Just to follow their conventions

Comment (dakrone) [inline core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java]: Also, this doesn't really seem to make sense to me, since it could potentially do different things depending on the order of the clauses in the query (if it's a bool holding clauses like [TermQuery BooleanQuery] versus a bool holding [BooleanQuery TermQuery]). Am I misunderstanding something?

File: core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java [hunk 2]
```diff
@@ -285,8 +287,20 @@ protected Query doToQuery(QueryShardContext context) throws IOException {
...
+                // special case for one term query and more than one field: f1:t1 f2:t1 f3:t1
+                // we need to wrap this in additional BooleanQuery so minimum_should_match is applied correctly
+                BooleanQuery.Builder builder = new BooleanQuery.Builder();
+                builder.add(new BooleanClause(booleanQuery, Occur.SHOULD));
+                booleanQuery = builder.build();
+            }
+            if (minimumShouldMatch != null) {
```
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java]: If there isn't more than a single bq clause, should we just ignore applying this at all anyway?

File: core/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java [hunk 3]
```diff
@@ -359,4 +386,39 @@ public void testNegativeFlags() throws IOException {
...
+
+    public void testMinimumShouldMatch() throws IOException {
+        QueryShardContext shardContext = createShardContext();
+        int numberOfTerms = randomIntBetween(1, 4);
+        int numberOfFields = randomIntBetween(1, 4);
+        StringBuilder queryString = new StringBuilder();
+        for (int i = 0; i < numberOfTerms; i++) {
+            queryString.append("t" + i + " ");
+        }
+        SimpleQueryStringBuilder simpleQueryStringBuilder = new SimpleQueryStringBuilder(queryString.toString());
```
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java]: Should add `.trim()` here also?

**Comment by dakrone** [comment]
@cbuescher Left some minor comments and a clarification where I think I am misunderstanding what you are trying to do

File: core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java (hunk 1 above)
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java]: The problem in #13884 is that for one query term & multiple fields, `minimum_should_match` gets calculated based on the number of fields instead of just the one term like it should. As far as I can see this seems to be because SimpleQueryParser only starts combining the BooleanQueries that are produced for each term into new BooleanQueries for more than one term/subquery. 

What I'm trying to do here is applying this additional wrapping for the one-term case. The problem now is, how to distiguish the one-term/multi-field case from the multi-term/one-field case. Before this change, Lucenes SimpleQueryParser#simplify() performs some rewrite of one-clause subqueries, so the resulting queries for those two cases have the same structure:
```
field1: "T1 T2 T3" => (field1:T1 field1:T2 field1:T3) 
field1, field2, field3: "T1" => (field1:T1 field2:T1 field3:T1)
```
This PR removes this simplification, so now each term/subquery should be a BooleanQuery in itself:
```
field1: "T1 T2 T3" =>  ( (field1:T1)  (field1:T2) (field1:T3) )
field1, field2, field3: "T1" => (field1:T1 field2:T1 field3:T1)
```
Now I can detect the "problematic" case (one term, multiple fields), since it will have leaf TermQueries on the second level of the query tree. That's the case where we need one extra wrapping into an additinal BooleanQuery, so the `minimum_should_match` gets calculated correctly.

File: core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java (hunk 2 above)
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/index/query/SimpleQueryStringBuilder.java]: There might be more than one bq clause here, e.g. if we query `"t1 t2"` for two fields `f1`,`f2`, then the resulting query will be `( (f1:t1 f2:t1) (f1:t2 f2:t2) )` (one clause per term), so we should apply `minimum_should_match`. I think this could go into an `else` branch of the previous check, though.

**Comment by cbuescher** [comment]
@dakrone thanks, I adressed the two minor comments and left some comments regarding your questions. Hope this makes the original problem and my attempt to fix a bit clearer.

**Comment by dakrone** [comment]
Thanks @cbuescher , I think this looks good now.

**Comment by javanna** [comment]
Heya @cbuescher sorry I am late to the party. I believe that the way we fixed the original issue is not future proof as it requires reverse engineering the lucene simple query parser.  I think lucene should rather support minimum should match properly, or we should remove support for it in elasticsearch as it can't be properly supported otherwise. I think we previously discussed what the behaviour should be, but maybe we should re-discuss how to implement that and where that logic should be. Thoughts?

**Comment by cbuescher** [comment]
After feedback from @jpountz and @javanna it became clear that this fix is too fragile and will likely break with future changes in the way lucene parses simple query string. I'll revert this commit on master, reopen the original issue.

**Comment by cbuescher** [comment]
Reverted with 2fe519c3e71c78536b21fa16fe0de27e53544334
