### PR TITLE
Promote longs to doubles when a terms agg mixes decimal and non-decimal numbers

### LINKED ISSUE #22232: Promote longs to doubles when merging terms agg results that contain both longs and doubles
This won't be perfect as doubles cannot represent all long values, so this might cause a precision loss on large longs which should be documented. But I think this would be a better user-experience than today since we fail such aggregations entirely.

As a next step, we should make the field stats API still consider that fields are aggregatable if some indices map the field as a long and others as a double.

### PR DESCRIPTION
**Pull request by jimczi**
This change makes the terms aggregation work when the buckets coming from different indices are a mix of decimal numbers and non-decimal numbers. In this case non-decimal number (longs) are promoted to decimal (double) which can result in a loss of precision for big numbers.

Fixes #22232

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/LongTerms.java [hunk 1]
```diff
@@ -152,4 +154,52 @@ public XContentBuilder doXContentBody(XContentBuilder builder, Params params) th
...
+        DocValueFormat decimalFormat = null;
+        for (InternalAggregation agg : aggregations) {
+            if (agg instanceof DoubleTerms) {
+                /**
+                 * this terms agg mixes longs and doubles, we must promote longs to doubles to make the internal aggs
+                 * compatible
+                 */
+                promoteLongsToDouble = true;
+                decimalFormat = ((DoubleTerms) agg).format;
+                break;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/LongTerms.java]: Maybe in that case we could just `return agg.doReduce` on this DoubleTerms instance which would reuse the logic we have in DoubleTerms rather than duplicating it below?

**Review by jpountz — APPROVED** [review]
Looks good, I just left a suggestion about the implementation.

**Comment by jimczi** [comment]
Thanks @jpountz I pushed a modif to address your feedback. Should we merge this to 5.x ?

**Comment by jimczi** [comment]
This should not be back ported to 5.x (this should be considered as a breaking change) until https://github.com/elastic/elasticsearch/issues/22265 is resolved.

**Comment by tylerfontaine** [comment]
@jimczi with #22265 closed, will this be backported to 5.x, or are we still considering it a breaking change, and it won't be available until 6.0?
