### PR TITLE
Re-deprecate xpack rollup endpoints

### LINKED ISSUE #36044: [CI] Problems in mixed cluster cleanup in ESRestTestCase#wipeRollupJobs
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+default-distro-bwc-tests/131/console

This one has a bunch of failures in the mixed cluster tests:

```
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=index/60_refresh/refresh=wait_for waits until changes are visible in search}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=indices.put_template/10_basic/Put multiple template}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=indices.update_aliases/20_routing/Numeric Routing}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=nodes.stats/10_basic/Nodes stats level}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=nodes.stats/11_indices_metrics/Metric - multi}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search.aggregation/40_range/Date Range Missing}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/160_exists_query/Test exists query on mapped date field}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/160_exists_query/Test exists query on unmapped geo_point field}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/30_limits/Docvalues_fields size limit}
org.elasticsearch.backwards.IndexingIT testIndexVersionPropagation
```

The failures look similar to this, so it probably not be the tests itself that fail but some cleanup:
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:46698], URI [/_rollup/job/_all], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"},"status":404}
	at __randomizedtesting.SeedInfo.seed([3DF3A00DADE684BC:B5A79FD7031AE944]:0)
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:687)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeRollupJobs(ESRestTestCase.java:477)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:407)
	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:193)
```

I tried to reproduce with one of the reproduce lines on master:
```
./gradlew :qa:mixed-cluster:v6.6.0#mixedClusterTestRunner \
  -Dtests.seed=3DF3A00DADE684BC \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/160_exists_query/Test exists query on mapped date field}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar \
  -Dtests.timezone=Kwajalein \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8
``` 

And got this:
```
ERROR   7.60s | MixedClusterClientYamlTestSuiteIT.test {p0=search/160_exists_query/Test exists query on mapped date field} <<< FAILURES!
   > Throwable #1: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:52996], URI [/_rollup/job/_all], status line [HTTP/1.1 404 Not Found]
   > {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"},"status":404}
   >    at __randomizedtesting.SeedInfo.seed([3DF3A00DADE684BC:B5A79FD7031AE944]:0)
   >    at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:687)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
   >    at org.elasticsearch.test.rest.ESRestTestCase.wipeRollupJobs(ESRestTestCase.java:477)
   >    at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:407)
   >    at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:193)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:52996], URI [/_rollup/job/_all], status line [HTTP/1.1 404 Not Found]
   > {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"},"status":404}
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:307)
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:292)
   >    at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
   >    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
   >    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   >    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   >    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   >    ... 1 more
  2> NOTE: leaving temporary files on disk at: /Users/christoph/workspace/elasticsearch/qa/mixed-cluster/build/testrun/v6.6.0#mixedClusterTestRunner/J0/temp/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT_3DF3A00DADE684BC-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1457, maxMBSortInHeap=7.982721853983626, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@138084b3), locale=ar, timezone=Kwajalein
  2> NOTE: Mac OS X 10.14.1 x86_64/Oracle Corporation 1.8.0_181 (64-bit)/cpus=8,threads=1,free=445255424,total=514850816
  2> NOTE: All tests run in this JVM: [MixedClusterClientYamlTestSuiteIT]
```

### PR DESCRIPTION
**Pull request by nik9000**
Redeprecates the `/_xpack/rollup` endpoints in favor of `/_rollup`.

When we cleanup the rollup in a cluster containing 6.x nodes we need to
use `/_xpack/rollup` instead of `/_rollup` because the 6.x nodes don't
know about `/_rollup`. In those cases we must ignore the deprecation
warnings that the 7.0 node will return for the end point.

Closes #36044

### CODE REVIEW

**Comment by nik9000** [comment]
@jasontedor I see that you made non-`_xpack` rollup endpoints in another PR. Would you like for me to deprecate the `_xpack` endpoints as part of this one?

**Comment by jasontedor** [comment]
Yes please, sorry for the conflicts.

**Comment by nik9000** [comment]
> Yes please, sorry for the conflicts.

Will do! Conflicts happen.

**Comment by nik9000** [comment]
So now that I've merged this I'm not sure that I need the warnings work.... Let me check if I can drop that.

**Comment by nik9000** [comment]
> So now that I've merged this I'm not sure that I need the warnings work.... Let me check if I can drop that.

Yes indeed. I can just revert all of that. We don't need it now.

**Comment by jasontedor** [comment]
@elasticmachine test this please

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/rest/RestDeleteRollupJobAction.java [hunk 1]
```diff
@@ -47,7 +55,7 @@ protected RestStatus getStatus(DeleteRollupJobAction.Response response) {
 
     @Override
     public String getName() {
-        return "rollup_delete_job_action";
+        return "delete_rollup_job";
```
Comment (nik9000) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/rest/RestDeleteRollupJobAction.java]: I've noticed a few of these changes that came along with my unrevert. Are these changes compatible with a mixed version cluster?

File: x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java [hunk 2]
```diff
@@ -633,7 +633,12 @@ private void assertRollUpJob(final String rollupJob) throws Exception {
         waitForRollUpJob(rollupJob, expectedStates);
 
         // check that the rollup job is started using the RollUp API
-        final Request getRollupJobRequest = new Request("GET", "_xpack/rollup/job/" + rollupJob);
+        final Request getRollupJobRequest;
+        if (isRunningAgainstOldCluster()) {
+            getRollupJobRequest = new Request("GET", "/_xpack/rollup/job/" + rollupJob);
```
Comment (nik9000) [inline x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java]: These are required because we can do a full cluster restart against versions that don't have the new endpoint.

**Comment by nik9000** [comment]
This is ready for review so I've removed `WIP`.

**Review by jasontedor — APPROVED** [review]
Looks good. Sorry about the deprecation work/unwork; it didn't occur to me until looking at the problems that the security and ML work that we had another way to approach this that could be cleaner and avoid the difficulties we were initially trying to work around here.

**Comment by nik9000** [comment]
> Looks good. Sorry about the deprecation work/unwork; it didn't occur to me until looking at the problems that the security and ML work that we had another way to approach this that could be cleaner and avoid the difficulties we were initially trying to work around here.

We're going to need to do some work on deprecation when we go to remove the old APIs in master. But we should have the tools that we need for that already available then so it'll be easier.

File: docs/reference/rollup/api-quickref.asciidoc [hunk 3]
```diff
@@ -9,26 +9,26 @@ Most {rollup} endpoints have the following base:
...
+* {ref}/rollup-stop-job.html[POST /_rollup/job/<job_id>/_stop]: Stop a job
+* {ref}/rollup-delete-job.html[DELETE /_rollup/job/<job_id+++>+++]: Delete a job
 
 [float]
 [[rollup-api-data]]
 === /data/
 
-* {ref}/rollup-get-rollup-caps.html[GET /_xpack/rollup/data/<index_pattern+++>/_rollup_caps+++]: Get Rollup Capabilities
+* {ref}/rollup-get-rollup-caps.html[GET /_rollup/data/<index_pattern+++>/_rollup_caps+++]: Get Rollup Capabilities
 * {ref}/rollup-get-rollup-index-caps.html[GET /<index_name+++>/_rollup/data/+++]: Get Rollup Index Capabilities
```
Comment (polyfractal) [inline docs/reference/rollup/api-quickref.asciidoc]: Heh, accidental typo becomes the correct endpoint XD

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/rest/RestDeleteRollupJobAction.java (hunk 1 above)
Comment (polyfractal) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/rest/RestDeleteRollupJobAction.java]: That's a good question... I'm not sure.  I don't really know how REST request names are used (or if they are just for display/task purposes?)

File: x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RollupIDUpgradeIT.java [hunk 4]
```diff
@@ -89,7 +89,7 @@ public void testIDsUpgradeCorrectly() throws Exception {
             client().performRequest(indexRequest);
 
             // create the rollup job
-            final Request createRollupJobRequest = new Request("PUT", "/_xpack/rollup/job/rollup-id-test");
+            final Request createRollupJobRequest = new Request("PUT", "/_rollup/job/rollup-id-test");
```
Comment (polyfractal) [inline x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RollupIDUpgradeIT.java]: I'm not entirely sure how rolling upgrade tests pick their versions, but couldn't we go from `< 6.6` to `>= 6.6, <7.0`?  In which case we'll need an `assumeTrue()` on this test, or some kind of version check on these URIs?

**Review by polyfractal — APPROVED** [review]
LGTM, although I'm not sure about your question re: names.  Left a question/comment about the rolling restart tests.

File: x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RollupIDUpgradeIT.java (hunk 4 above)
Comment (nik9000) [reply x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RollupIDUpgradeIT.java]: The rolling upgrade tests only go through the wire compatible versions so this should be safe.

**Comment by jasontedor** [comment]
Thank you @nik9000!

**Comment by nik9000** [comment]
I'm glad our intake build went green and I could get it merged! Thanks for
the review!
