### PR TITLE
Fix replica-primary inconsistencies when indexing during primary relocation with ongoing replica recoveries

### LINKED ISSUE #19248: Indexing during primary relocation with ongoing replica recoveries can lead to documents not being properly replicated
Primary relocation violates two invariants that ensure proper interaction between document replication and peer recoveries, ultimately leading to documents not being properly replicated. As this is quite a tricky issue to understand, I'll first give a short summary on how document replication and peer recoveries integrate:

1) Peer recoveries are triggered by the recovery target node (the one that wants to recover) but only successfully started on the recovery source node (holding the primary shard) when the source node knows that the recovery target shard exists. This check is realized by looking at the current cluster state on the recovery source node and checking the routing table if a corresponding initializing shard exists on the target node.
2) Once this check successfully passes the source node remembers the current position in the translog and syncs Lucene files to the target node (this is called phase 1). At the end of phase 1, the engine is started on the target recovery shard. From this moment on the shard accepts document writes.
3) In a second phase the source shard takes a snapshot of the translog, containing all writes that have been added since the saved position in the translog while the lucene files were copied to the target shard. The source shard then sends all the operations in the snapshot to the target shard. New operations that happen after the snapshot was taking a replicated to the target shard using the normal replication logic.

The following two invariants are (among others) required for data replication to properly integrate with peer recoveries:

**Invariant 1**: Document writes must be replicated based on the routing table of a cluster state that includes all shards which have ongoing or finished recoveries. This is ensured by the fact that do not start a recovery that is not reflected by the cluster state available on the primary node *and* we always sample a fresh cluster state before starting to replicate write operations. 

**Invariant 2**: Every operation that is not part of the snapshot taken for phase 2, must be succesfully indexed on the target replica (pending shard level errors which will cause the target shard to be failed). To ensure this, we start replicating to the target shard as soon as the recovery start and open it's engine before we take the snapshot. All operations that are indexed after the snapshot was taken are guaranteed to arrive to the shard when it's ready to index them. Note that this also means that the replication doesn't fail a shard if it's not yet ready to recieve operations - it's a normal part of a recovering shard.

With primary relocations, the two invariants can be possibly violated. To illustrate the issues, let's consider a primary relocating while there is another replica shard recovering from the primary shard.

Invariant 1 can be violated if the target of the primary relocation is so lagging on cluster state processing that it doesn't even know about the new initializing replica. This is very rare in practice as replica recoveries take time to copy all the index files but it is a theoretical gap that surfaces in testing scenarios.

Invariant 2 can be violated even if the target primary knows about the initializing replica. This can happen if the target primary replicates an operation to the intializing shard and that operation arrives to the initializing shard *before* it opens it's engine but arrives to the primary source *after* it has taken the snapshot of the translog. Those operations will be currently missed on the new initializing replica.

The obvious easy fix for this will be to forbid any replica recovery while the primary is relocating. However, since primary relocation can take a long time (we do it in the background and throttle it) this will result in a large time window where the cluster will not be able to recover from a potential replica loss (either by a network hickup or a true node loss).

We currently working on a fix using the following two directions:
1) As part of the primary hand off before source and target, the source will make sure the target knows about  all ongoing recoveries. This will make sure invariant 1 can not violated.
2) We will not start the phase2 of recoveries (where the snapshot is taken) after the hand off has taken place (the source shard state is `RELOCATED`). Since we now guarantee that no operations are inflight while the hand off happens ( #15900 ), we know that from the moment operations are routed via the target primary, no new snapshots will be taken which is the premise of violating invariant 2.

### PR DESCRIPTION
**Pull request by ywelsch**
Primary relocation violates two invariants that ensure proper interaction between document replication and peer recoveries, ultimately leading to documents not being properly replicated (see #19248 for more details).

Closes #19248

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoveriesCollection.java [hunk 1]
```diff
@@ -152,6 +160,51 @@ public boolean cancelRecoveriesForShard(ShardId shardId, String reason) {
...
+            final PlainActionFuture<Void> future = new PlainActionFuture<>();
+            observer.waitForNextChange(new ClusterStateObserver.Listener() {
+
+                @Override
+                public void onNewClusterState(ClusterState state) {
+                    future.onResponse(null);
+                }
+
+                @Override
+                public void onClusterServiceClose() {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoveriesCollection.java]: we use this implementation a lot - maybe we should make utility base class for it (different PR). a default method implementation will be tricky because of the local node. Maybe it should be a parameter to the onClusterServiceClose. Food for thought.

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java [hunk 2]
```diff
@@ -119,16 +114,7 @@ private RecoveryResponse recover(final StartRecoveryRequest request) throws IOEx
         }
 
         logger.trace("[{}][{}] starting recovery to {}", request.shardId().getIndex().getName(), request.shardId().id(), request.targetNode());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java]: can we log this after the add(), which may actually delay the recovery?

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java [hunk 3]
```diff
@@ -144,38 +130,57 @@ public void messageReceived(final StartRecoveryRequest request, final TransportC
         }
     }
 
-    private static final class OngoingRecoveries {
-        private final Map<IndexShard, Set<RecoverySourceHandler>> ongoingRecoveries = new HashMap<>();
+    private final class OngoingRecoveries {
+        private final Map<IndexShard, ShardRecoveryContext> ongoingRecoveries = new HashMap<>();
+
+        synchronized RecoverySourceHandler add(StartRecoveryRequest request, IndexShard shard) {
+            final RecoverySourceHandler handler;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java]: maybe just :

```
final ShardRecoveryContext shardContext = ongoingRecoveries.computeIfAbsent(shard, s -> new ShardRecoveryContext());
return shardContext.addNewRecovery(() -> createRecoverySourceHandler(request, shard, shardContext));
```

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java [hunk 4]
```diff
@@ -144,38 +130,57 @@ public void messageReceived(final StartRecoveryRequest request, final TransportC
...
+            }
+            return handler;
+        }
 
-        synchronized void add(IndexShard shard, RecoverySourceHandler handler) {
-            Set<RecoverySourceHandler> shardRecoveryHandlers = ongoingRecoveries.get(shard);
-            if (shardRecoveryHandlers == null) {
-                shardRecoveryHandlers = new HashSet<>();
-                ongoingRecoveries.put(shard, shardRecoveryHandlers);
+        private RecoverySourceHandler createRecoverySourceHandler(StartRecoveryRequest request, IndexShard shard,
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java]: can we move this to ShardRecoveryContext and pass request and shard to addNewRecovery ? this way won't need all the supplier fun. Might as well rename the add method here to addNewRecovery too? or maybe `registerRecovery`?  (I don't mind much about the names, just a suggestion)

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java [hunk 5]
```diff
@@ -144,38 +130,57 @@ public void messageReceived(final StartRecoveryRequest request, final TransportC
...
+            final ShardRecoveryContext shardRecoveryContext = ongoingRecoveries.get(shard);
+            assert shardRecoveryContext != null : "Shard was not registered [" + shard + "]";
+            boolean remove = shardRecoveryContext.recoveryHandlers.remove(handler);
             assert remove : "Handler was not registered [" + handler + "]";
             if (remove) {
                 shard.recoveryStats().decCurrentAsSource();
             }
-            if (shardRecoveryHandlers.isEmpty()) {
+            if (shardRecoveryContext.recoveryHandlers.isEmpty()) {
                 ongoingRecoveries.remove(shard);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java]: can we assert that the delay recovery exception is null?

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 6]
```diff
@@ -136,6 +146,16 @@ public RecoveryResponse recoverToTarget() throws IOException {
                 }
             }
 
+            // engine was just started at the end of phase 1
+            if (shard.state() == IndexShardState.RELOCATED) {
+                /**
+                 * we could have missed replication operations on the target if its engine wasn't started yet after primary relocation
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: maybe, "the primary shard has been relocated while we copied files. This means we can't guarantee any more that any operation that was replicated during the file copy (when the target engine was not yet opened) will be present in the local translog and thus will be resent on phase 2. The reason is that operation replicated by the target primary are sent to recovery target and the local shard (old primary) concurrently, meaning it may have arrived at the recovery target before we opened the engine and is still on inlight on the local shard.

Checking the relocated status here, after we opened the engine on the target,  is safe because primary relocation waits for all ongoing operations to complete and be fully replicated. Therefore all future operation by the new primary are guaranteed to reach the target shard when it's engine is open.
"

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 7]
```diff
@@ -136,6 +146,16 @@ public RecoveryResponse recoverToTarget() throws IOException {
...
+                 * hand-off completed. The reason is that replication failures are just (silently) ignored if the engine isn't started yet,
+                 * see {@link ReplicationOperation#ignoreReplicaException(Throwable)} and {@link IndexShard#getEngine()}.
+                 */
+                throw new IndexShardRelocatedException(request.shardId());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: do we need to use IndexShardRelocationException? I looked at the other usages of it, and I think we can get of it all together? We can  use IllegalIndexShardStateException ?

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java [hunk 8]
```diff
@@ -362,11 +382,37 @@ public void finalizeRecovery() {
         cancellableThreads.execute(recoveryTarget::finalizeRecovery);
 
         if (isPrimaryRelocation()) {
+            // in case of primary relocation we have to ensure that the cluster state on the primary relocation target has all
+            // replica shards that have recovered or are still recovering from the current primary, otherwise replication actions
+            // will not be send to these replicas. To accomplish this, first block new recoveries, then take version of latest cluster
+            // state. This means that no new recovery can be completed based on information of a newer cluster state than the current one.
+            newRecoveriesHandler.handle(new DelayRecoveryException("primary relocation hand-off in progress or completed for " + shardId));
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: I think we should make newRecoveriesHanlder be:
```
 private final Function<String, Releasable> delayNewRecoveries; 
```

and then all of this becomes:

```
            try (Releasable ignored = delayNewRecoveries.apply("primary relocation hand-off in progress or completed for " + shardId)) {
                final long currentClusterStateVersion = currentClusterStateVersionSupplier.get();
                logger.trace("[{}][{}] waiting on {} to have cluster state with version [{}]", indexName, shardId, request.targetNode(),
                    currentClusterStateVersion);

                cancellableThreads.execute(() -> recoveryTarget.waitForClusterState(currentClusterStateVersion));

                logger.trace("[{}][{}] performing relocation hand-off to {}", indexName, shardId, request.targetNode());
                cancellableThreads.execute(() -> shard.relocated("to " + request.targetNode()));
            }
```

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java [hunk 9]
```diff
@@ -85,7 +87,8 @@
 
     private final Map<String, String> tempFileNames = ConcurrentCollections.newConcurrentMap();
 
-    public RecoveryTarget(IndexShard indexShard, DiscoveryNode sourceNode, RecoveryTargetService.RecoveryListener listener) {
+    public RecoveryTarget(IndexShard indexShard, DiscoveryNode sourceNode, RecoveryTargetService.RecoveryListener listener,
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java]: can we add some java docs?

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoveryTargetHandler.java [hunk 10]
```diff
@@ -44,6 +44,11 @@
     void finalizeRecovery();
 
     /**
+     * Blockingly waits for cluster state with at least clusterStateVersion to be available
+     */
+    void waitForClusterState(long clusterStateVersion);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoveryTargetHandler.java]: nit: maybe `ensureClusterStateVersion` ?

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoveryWaitForClusterStateRequest.java [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+import org.elasticsearch.common.io.stream.StreamInput;
+import org.elasticsearch.common.io.stream.StreamOutput;
+import org.elasticsearch.index.shard.ShardId;
+import org.elasticsearch.transport.TransportRequest;
+
+import java.io.IOException;
+
+public class RecoveryWaitForClusterStateRequest extends TransportRequest {
+
+    private long recoveryId;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoveryWaitForClusterStateRequest.java]: time for a base class for all these recovery requests? we can remove a lot of boilerplate in RecoveryTargetService by have the  recovery resolving shared. As a different PR , of course.

**Comment by bleskes** [comment]
thx @ywelsch . I left some comments. Can we also maybe add some tests to RecoverySourceHandlerTests to test the new relocation behavior (waiting for a cluster state version and fail on move to relocated )?

**Comment by ywelsch** [comment]
@bleskes I've pushed a new change addressing comments. I've also added the unit tests that you asked for but I am not convinced that they are too useful.

**Comment by bleskes** [comment]
@ywelsch I'm wondering if changing the title to `Fix replica-primary inconsistencies when indexing during primary relocation with ongoing replica recoveries` will better describe the situation?  or even take over the issue's title? (we use PR to drive change lists)

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java (hunk 7 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java]: We talked about this already on another PR, and my answer is the same here: We currently have an exception for each shard state. Some of the others are used as sparsely as this one. If we want to clean this up, we should not only remove this one. Can be a follow-up but it's really low on my list...

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java [hunk 12]
```diff
@@ -200,32 +177,50 @@ synchronized void cancel(IndexShard shard, String reason) {
...
-             * Makes new recoveries throw the provided exception. If set to null, re-enables starting new recoveries.
+             * Makes new recoveries throw a {@link DelayRecoveryException} with the provided message.
              *
-             * Throws {@link IllegalStateException} if new recoveries are already being prevented or allowed.
+             * Throws {@link IllegalStateException} if new recoveries are already being blocked.
              */
-            synchronized void throwExceptionOnNewRecovery(@Nullable DelayRecoveryException onNewRecoveryException)
-                throws IllegalStateException {
-                if (onNewRecoveryException != null && this.onNewRecoveryException != null) {
+            synchronized Releasable blockNewRecoveries(String exceptionMessage) throws IllegalStateException {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java]: nit: block suggest "block the thread" like on have it wait on a lock. don't you like "delay"?

**Comment by bleskes** [comment]
LGTM. Thanks @ywelsch

File: core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java (hunk 12 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/indices/recovery/RecoverySource.java]: `delayNewRecoveries` sounds good!
