### PR TITLE
Fix ingest timezone parsing

### LINKED ISSUE #63458: [Ingest Pipeline] Date processor ignores timezone offset XXX
Currently tested in Dev Console on 7.9.2 running on ESS.

**Steps to reproduce**:

It seems that timezone formats that work in pure Java is being ignored when using the date processor in ingest pipelines. Example:

```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "_description",
    "processors": [
      {
        "date": {
          "field": "message",
          "target_field": "@timestamp", 
          "formats": ["EEE MMM  d HH:mm:ss YYYY XXX"],
          "timezone": "UTC"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "message": """Wed Oct  21 11:19:17 2020 -04:00"""
      }
    }
  ]
}
```

This will output:

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "index",
        "_type" : "_doc",
        "_id" : "id",
        "_source" : {
          "@timestamp" : "2020-10-21T11:19:17.000Z",
          "message" : "Wed Oct  21 11:19:17 2020 -04:00"
        },
        "_ingest" : {
          "timestamp" : "2020-10-08T09:21:11.48095Z"
        }
      }
    }
  ]
}
```

As you can see even though the offset is -04:00, and date processors defaults to UTC; it does not calculate any offset?

The same behavior is seen with other offset examples like `Z`, `z`, `VV` etc.

The same format in Java will work (sample code provided by @marc-gr ):
```
import java.util.*;
import java.util.Date;
import java.text.SimpleDateFormat;
public class Main {
    public static void main(String[] args) throws Exception {
        SimpleDateFormat format = new SimpleDateFormat("E MMM  d HH:mm:ss YYYY XXX");
        String dateString = format.format( new Date()   );
        Date   date       = format.parse ( "Wed Oct  21 11:19:17 2020 -04:00" );    
        System.out.println(date);
    }
}
```

Anyone know if this is intended behavior?

### PR DESCRIPTION
**Pull request by pgomulka**
this commit aligns timezone parsing logic with `DateFormat.Iso8601`. Timezone can be provided on a pattern and as ingest parameter. When no timezone is provided on a pattern it is defaulted to UTC or an ingest parameter (if provided).

When timezone is not present in a pattern, but an ingest timezone parameter is provided - a date should be parsed as if it was in that timezone. 
Example: pattern "uuuu-MM-dd'T'HH:mm", text "2020-01-01T01:00", timezone: `-01:00` should return `2020-01-01T01:00:00-01:00`
If the pattern has a timezone and a timezone parameter is provided - a date should parsed with a timezone from input, and then "recalculated" to an ingest parameter
Example "uuuu-MM-dd'T'HH:mm XXX", text "2020-01-01T01:00 -02:00", timezone `-01:00` should return `2020-01-01T02:00:00-01:00`
relates https://github.com/elastic/elasticsearch/pull/38407
relates https://github.com/elastic/elasticsearch/pull/51215
closes https://github.com/elastic/elasticsearch/issues/63458

### CODE REVIEW

**Comment by pgomulka** [comment]
@elasticmachine update branch

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java [hunk 1]
```diff
@@ -94,22 +94,17 @@ private long parseMillis(String date) {
...
+
             final DateFormatter formatter = dateFormatter;
             return text -> {
                 TemporalAccessor accessor = formatter.parse(text);
                 // if there is no year nor year-of-era, we fall back to the current one and
                 // fill the rest of the date up with the parsed date
                 if (accessor.isSupported(ChronoField.YEAR) == false
                     && accessor.isSupported(ChronoField.YEAR_OF_ERA) == false
-                    && accessor.isSupported(WeekFields.of(locale).weekOfWeekBasedYear()) == false) {
+                    && accessor.isSupported(WeekFields.of(locale).weekBasedYear()) == false) {
```
Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java:107]: Is this change unrelated to the timezone issue?

**Review by rjernst — COMMENTED** [review]
This looks fine, but it seems there is an unrelated change in here?

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java (hunk 1 above)
Comment (pgomulka) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java:107]: not related to the timezone issue, but also mentioned by a user https://github.com/elastic/elasticsearch/issues/63458#issuecomment-706503574

I realised I have note added a test case for it

**Comment by pgomulka** [comment]
@elasticmachine update branch

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java (hunk 1 above)
Comment (rjernst) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java:107]: I think it would be better to isolate such a separate fix, so that the commit message is associated with what is being fixed, rather than a seemingly unrelated change.

Comment (pgomulka) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java:107]: this is a good idea, better to isolate this change. 
A separate PR https://github.com/elastic/elasticsearch/pull/65717

**Review by rjernst — APPROVED** [review]
LGTM
