### PR TITLE
Fix data stream retrieval in `TimeSeriesDataStreamsIT`

### LINKED ISSUE #124987: [CI] TimeSeriesDataStreamsIT testRolloverAction failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7070 / ubuntu-2404-aarch64_checkpart5_platform-support-arm](https://gradle-enterprise.elastic.co/s/4yoe4t4o3xtig)
- [elasticsearch-periodic #7048 / openjdk23_entitlements_true_checkpart5_java-matrix](https://gradle-enterprise.elastic.co/s/pzpfkiuy34qm6)
- [elasticsearch-pull-request #62808 / part-5](https://gradle-enterprise.elastic.co/s/pbjgxhyof7ziq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testRolloverAction" -Dtests.seed=3EFB608771468786 -Dtests.locale=szl-Latn-PL -Dtests.timezone=America/Port-au-Prince -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRolloverAction),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:33007], URI [/.ds-logs-anbivaggyy-2025.03.17-000002/_settings?flat_settings=true], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.ds-logs-anbivaggyy-2025.03.17-000002]","resource.type":"index_or_alias","resource.id":".ds-logs-anbivaggyy-2025.03.17-000002","index_uuid":"_na_","index":".ds-logs-anbivaggyy-2025.03.17-000002"}],"type":"index_not_found_exception","reason":"no such index [.ds-logs-anbivaggyy-2025.03.17-000002]","resource.type":"index_or_alias","resource.id":".ds-logs-anbivaggyy-2025.03.17-000002","index_uuid":"_na_","index":".ds-logs-anbivaggyy-2025.03.17-000002"},"status":404}
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testRolloverAction
- [main] 3 failures in test testRolloverAction (1.1% fail rate in 282 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
This test had the potential to fail when two consecutive GET data streams requests would hit two different nodes, where one node already had the cluster state that contained the new backing index and the other node didn't yet.

Caused by #122852

Fixes #124987

### CODE REVIEW

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesDataStreamsIT.java [hunk 1]
```diff
@@ -83,9 +83,6 @@ public void testRolloverAction() throws Exception {
             final var backingIndices = getDataStreamBackingIndexNames(dataStream);
             assertEquals(2, backingIndices.size());
             assertTrue(Boolean.parseBoolean((String) getIndexSettingsAsMap(backingIndices.getLast()).get("index.hidden")));
-        });
-        assertBusy(() -> {
-            final var backingIndices = getDataStreamBackingIndexNames(dataStream);
             assertEquals(PhaseCompleteStep.finalStep("hot").getKey(), getStepKeyForIndex(client(), backingIndices.getFirst()));
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/TimeSeriesDataStreamsIT.java:86]: I originally added two `assertBusy`s because I thought we needed the 20 second timeout. In hindsight, I don't think we actually do. This also avoids the issue with the two back-to-back GET data stream API calls.

**Review by gmarouli — APPROVED** [review]
LGTM!
