### PR TITLE
Run keystore management tests on docker distros

### LINKED ISSUE #49469: Make KeystoreManagementTests work in the docker case
While I was working on #32691, we added some Docker packaging tests. Right now, some of the keystore tests are failing on the `distroTest.default-docker` task, e.g. `:qa:os:centos-6:distroTest.default-docker`.

Ideally, the keystore management tests can be flexible enough to run even in the docker case. If not, the tests should be fixed so that they don't run for that docker testing task.

Relates #32691

### PR DESCRIPTION
**Pull request by williamrandolph**
This PR moves some of the Docker-specific setup and teardown from `DockerTests` up to `PackagingTestCase` so that the KeystoreManagement tests will run on Docker. The main thing that needs to happen is setting the testing `Shell` to be a `DockerShell`. Previously, the KeystoreManagementTests were mostly "passing" on Docker because they ran shell commands on the underlying system and then queried a Docker installation. Now, we can be more confident that the tests are doing the right thing in the Docker case.

Fixes #49469

### CODE REVIEW

**Comment by williamrandolph** [comment]
TODOs remaining:
- [ ] fix TODO for verifying keystore permissions
- [ ] (potentially) remove redundant tests from DockerTests

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/packaging-matrix-unix

File: qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java [hunk 1]
```diff
@@ -80,9 +83,30 @@ public void test11InstallPackageDistribution() throws Exception {
...
+
+        try {
+            waitForPathToExist(installation.config("elasticsearch.keystore"));
+        } catch (InterruptedException e) {
+            throw new RuntimeException(e);
+        }
+
+        final Installation.Executables bin = installation.executables();
+        Shell.Result r = sh.runIgnoreExitCode(bin.keystoreTool.toString() + " has-passwd");
+        assertThat("has-passwd should fail", r.exitCode, not(is(0)));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java]:
```suggestion
        assertFalse("has-passwd should fail", r.isSuccess());
```

File: qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java [hunk 2]
```diff
@@ -80,9 +83,30 @@ public void test11InstallPackageDistribution() throws Exception {
...
+        assertThat("has-passwd should fail", r.stdout, containsString("ERROR: Keystore is not password-protected"));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java]: Since the previous line checked that the command failed, how about changing the message here:

```suggestion
        assertThat("has-passwd didn't fail with the expected error", r.stdout, containsString("ERROR: Keystore is not password-protected"));
```

**Review by pugnascotia — APPROVED** [review]

**Review by pugnascotia — APPROVED** [review]

**Review by rjernst — APPROVED** [review]
LGTM
