### PR TITLE
Open and close index to honour allow_no_indices option

### LINKED ISSUE #24031: POST-ing to /_all/_open and /_all/_close break wildcard expansion
Calling `POST /_all/_open` when there is no closed index or calling `POST /_all/_close` when there's no open index breaks the wildcard expansion of `_all` and `*`, causing ES to return a 404 message saying it couldn't find an index whose name is the unexpanded value.

On the other hand, calling `POST /your_index/_open` and `POST /your_index/_close` (i.e. using the exact name of the index) when `your_index` is acknowledged regardless of the state that `your_index` is in.

Steps to replicate:

1. Run ES (tested with the official Docker image)

```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.3.0
```

2. Try to call `POST /_all/_open`

```
curl -XPOST -u elastic:changeme localhost:9200/_all/_close?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index",
        "index_uuid" : "_na_",
        "index" : "[_all]"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "index_uuid" : "_na_",
    "index" : "[_all]"
  },
  "status" : 404
}
```

### PR DESCRIPTION
**Pull request by olcbean**
The endpoints `_open` and `_close` require at least one index to be specified as the target for the requested action. Under the default setting of ` allow_no_indices` (`false`) `_open` allows the use of a wildcard resolving to a currently closed index. If the wildcard does not match any such index, the `index_not_found_exception` is thrown. `_close` has the same behavior.

However setting `allow_no_indices=true` both `_open` and `_close` would still throw an exception if there is no matching target index. In other words `allow_no_indices` is ignored in this context.

This PR addresses the above inconsistency.
 
Fixes #24031

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 1]
```diff
@@ -190,6 +190,39 @@ public void testCloseOpenAllWildcard() {
         assertThat(openIndexResponse.isAcknowledged(), equalTo(true));
         assertIndexIsOpened("test1", "test2", "test3");
     }
+    
+    // if there are no indices to open/close throw an exception
+    public void testOpenCloseWildCardsNoIdcicesDefault() {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: there's a typo in the method name ;)

File: core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 2]
```diff
@@ -190,6 +190,39 @@ public void testCloseOpenAllWildcard() {
...
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareClose("*").execute().actionGet());
+        
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareOpen("_all").execute().actionGet());
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareClose("_all").execute().actionGet());
+    }
+    
+    // if there are no indices to open/close and allow_no_indices=true, the open/close is a no-op
+    public void testOpenCloseWildCardsNoIdcicesAllowNoIndices() {
+        IndicesOptions openIncidesOptions = IndicesOptions.fromOptions(false, true, false, true);
+        IndicesOptions closeIncidesOptions = IndicesOptions.fromOptions(false, true, true, false);
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: Incides -> Indices ? ;)

File: core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 3]
```diff
@@ -190,6 +190,39 @@ public void testCloseOpenAllWildcard() {
...
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareClose("test").execute().actionGet());
+        
+        assertAcked(client().admin().indices().prepareClose("test*").setIndicesOptions(openIncidesOptions).execute().actionGet());
+        assertAcked(client().admin().indices().prepareClose("test*").setIndicesOptions(closeIncidesOptions).execute().actionGet());
+        
+        assertAcked(client().admin().indices().prepareClose("*").setIndicesOptions(openIncidesOptions).execute().actionGet());
+        assertAcked(client().admin().indices().prepareClose("*").setIndicesOptions(closeIncidesOptions).execute().actionGet());
+        
+        assertAcked(client().admin().indices().prepareClose("_all").setIndicesOptions(openIncidesOptions).execute().actionGet());
+        assertAcked(client().admin().indices().prepareClose("_all").setIndicesOptions(closeIncidesOptions).execute().actionGet());
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: if you want to save some characters you can replace all these `execute().actionGet()` with just `get()`

File: core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 4]
```diff
@@ -190,6 +190,39 @@ public void testCloseOpenAllWildcard() {
...
+        
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareOpen("*").execute().actionGet());
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareClose("*").execute().actionGet());
+        
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareOpen("_all").execute().actionGet());
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareClose("_all").execute().actionGet());
+    }
+    
+    // if there are no indices to open/close and allow_no_indices=true, the open/close is a no-op
+    public void testOpenCloseWildCardsNoIdcicesAllowNoIndices() {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: typo in the method name here too

File: core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 5]
```diff
@@ -190,6 +190,39 @@ public void testCloseOpenAllWildcard() {
...
+        IndicesOptions openIncidesOptions = IndicesOptions.fromOptions(false, true, false, true);
+        IndicesOptions closeIncidesOptions = IndicesOptions.fromOptions(false, true, true, false);
+
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareOpen("test").execute().actionGet());
+        expectThrows(IndexNotFoundException.class, () -> client().admin().indices().prepareClose("test").execute().actionGet());
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: this looks like the same tests that you have in the other method. Did you mean to set the indices options here too? if you set ignore unavailable to true even these calls are acked with no exception right?

**Review by javanna — CHANGES_REQUESTED** [review]
I left a few minor comments around testing, fix looks good though. Thanks for opening the PR!

**Comment by olcbean** [comment]
Thanks for the feedback, @javanna!
The issues should be fixed now ;)

File: core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 6]
```diff
@@ -190,6 +190,41 @@ public void testCloseOpenAllWildcard() {
...
+    
+    // if there are no indices to open/close and allow_no_indices=true, the open/close is a no-op
+    public void testOpenCloseWildCardsNoIndicesAllowNoIndices() throws InterruptedException, ExecutionException {
+        IndicesOptions openIndicesOptions = IndicesOptions.fromOptions(false, true, false, true);
+        IndicesOptions closeIndicesOptions = IndicesOptions.fromOptions(false, true, true, false);
+
+        expectThrows(IndexNotFoundException.class,
+                () -> client().admin().indices().prepareOpen("test").setIndicesOptions(openIndicesOptions).execute().actionGet());
+        expectThrows(IndexNotFoundException.class,
+                () -> client().admin().indices().prepareClose("test").setIndicesOptions(closeIndicesOptions).execute().actionGet());
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: one more thing, can you use .get() consistently in all the tests you added please?

Comment (olcbean) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: @javanna Unfortunately it is not as straight forward as simply replacing `actionGet()` with `get()`. The difference between `get()` and `actionGet()` is that the later unwraps the `ExecutionException` and throws the actual cause (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/ActionFuture.java#L37)

In my case when `get()` is used an `ExecutionException` is throws ( which wraps an `IndexNotFoundException` ). Checking for such a general exception is not really useful, so I will need to unwrap and check the actual cause. This will make a simple test more difficult to read and somewhat cumbersome. That's why I opted for the simpler use of `actionGet()` whenever an exception is expected and check the actual cause. And for the shorter version `get()` whenever no exception is expected.

Of course I can use `actionGet()` consistently for all the tests :)

Comment (javanna) [inline core/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: oh I see thanks for explaining. leave it as-is then, thanks! I will merge this in the coming days.

**Comment by javanna** [comment]
jenkins test this please

**Review by javanna — APPROVED** [review]

**Comment by javanna** [comment]
Merged to master and cherry-pick to 5.x. Thanks a lot @olcbean !
