### PR TITLE
Fix StringIndexOutOfBoundsException in COMPLETION command when options are omitted.

### LINKED ISSUE #138361: StringIndexOutOfBoundsException in ESQL COMPLETION command when optional parameters are omitted
## Summary
A `StringIndexOutOfBoundsException` occurs when parsing ES|QL `COMPLETION` commands with omitted optional parameters (`WITH` clause). 

## Error Details

The error happens when attempting to extract source text from an empty `CommandNamedParametersContext` that has invalid token indices.

```
java.lang.StringIndexOutOfBoundsException: Range [174, 174 + -1) out of bounds for length 198
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:118)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:397)
	at java.base/java.lang.String.checkBoundsOffCount(String.java:4925)
	at java.base/java.lang.String.<init>(String.java:546)
	at org.antlr.v4.runtime.CodePointCharStream$CodePoint8BitCharStream.getText(CodePointCharStream.java:160)
	at org.elasticsearch.xpack.esql.parser.ParserUtils.source(ParserUtils.java:131)
	at org.elasticsearch.xpack.esql.parser.ParserUtils.source(ParserUtils.java:103)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.applyCompletionOptions(LogicalPlanBuilder.java:1166)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.lambda$visitCompletionCommand$39(LogicalPlanBuilder.java:1155)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitCompositeQuery(LogicalPlanBuilder.java:200)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitCompositeQuery(LogicalPlanBuilder.java:114)
	at org.elasticsearch.xpack.esql.parser.EsqlBaseParser$CompositeQueryContext.accept(EsqlBaseParser.java:379)
	at org.elasticsearch.xpack.esql.parser.ParserUtils.typedParsing(ParserUtils.java:72)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.plan(LogicalPlanBuilder.java:135)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitCompositeQuery(LogicalPlanBuilder.java:197)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitCompositeQuery(LogicalPlanBuilder.java:114)
	at org.elasticsearch.xpack.esql.parser.EsqlBaseParser$CompositeQueryContext.accept(EsqlBaseParser.java:379)
	at org.elasticsearch.xpack.esql.parser.ParserUtils.typedParsing(ParserUtils.java:72)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.plan(LogicalPlanBuilder.java:135)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitSingleStatement(LogicalPlanBuilder.java:168)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitStatements(LogicalPlanBuilder.java:158)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.visitStatements(LogicalPlanBuilder.java:114)
	at org.elasticsearch.xpack.esql.parser.EsqlBaseParser$StatementsContext.accept(EsqlBaseParser.java:250)
	at org.elasticsearch.xpack.esql.parser.ParserUtils.typedParsing(ParserUtils.java:72)
	at org.elasticsearch.xpack.esql.parser.LogicalPlanBuilder.statement(LogicalPlanBuilder.java:130)
	at org.elasticsearch.xpack.esql.parser.EsqlParser.invokeParser(EsqlParser.java:172)
	at org.elasticsearch.xpack.esql.parser.EsqlParser.createQuery(EsqlParser.java:132)
	at org.elasticsearch.xpack.esql.session.EsqlSession.parse(EsqlSession.java:454)
	at org.elasticsearch.xpack.esql.session.EsqlSession.execute(EsqlSession.java:189)
	at org.elasticsearch.xpack.esql.execution.PlanExecutor.lambda$esql$2(PlanExecutor.java:102)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:465)
	at org.elasticsearch.xpack.esql.execution.PlanExecutor.esql(PlanExecutor.java:102)
	at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.innerExecute(TransportEsqlQueryAction.java:257)
	at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.doExecuteForked(TransportEsqlQueryAction.java:227)
	at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$doExecute$5(TransportEsqlQueryAction.java:217)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1076)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

### PR DESCRIPTION
**Pull request by afoucret**
Fixes #138361

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java [hunk 1]
```diff
@@ -1157,16 +1157,20 @@ public PlanFactory visitCompletionCommand(EsqlBaseParser.CompletionCommandContex
...
-            throw new ParsingException(source(ctx), "Missing mandatory option [{}] in COMPLETION", Completion.INFERENCE_ID_OPTION_NAME);
+            throw new ParsingException(
+                completion.source(),
+                "Missing mandatory option [{}] in COMPLETION",
+                Completion.INFERENCE_ID_OPTION_NAME
+            );
         }
 
-        Map<String, Expression> optionsMap = visitCommandNamedParameters(ctx).keyFoldedMap();
+        Map<String, Expression> optionsMap = optionsExpression.keyFoldedMap();
```
Comment (afoucret) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:1173]: ℹ️ For whatever reason (abuse of pizzas?) I was not reusing the optionExpression while it was the right things to do.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java [hunk 2]
```diff
@@ -1157,16 +1157,20 @@ public PlanFactory visitCompletionCommand(EsqlBaseParser.CompletionCommandContex
...
+        MapExpression optionsExpression = ctx == null ? null : visitCommandNamedParameters(ctx);
 
-        if (optionsExpresion == null || optionsExpresion.containsKey(Completion.INFERENCE_ID_OPTION_NAME) == false) {
+        if (optionsExpression == null || optionsExpression.containsKey(Completion.INFERENCE_ID_OPTION_NAME) == false) {
             // Having a mandatory named parameter for inference_id is an antipattern, but it will be optional in the future when we have a
             // default LLM. It is better to keep inference_id as a named parameter and relax the syntax when it will become optional than
             // completely change the syntax in the future.
-            throw new ParsingException(source(ctx), "Missing mandatory option [{}] in COMPLETION", Completion.INFERENCE_ID_OPTION_NAME);
+            throw new ParsingException(
+                completion.source(),
```
Comment (afoucret) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:1167]: ℹ️ Using `completion.source` instead of `source(ctx)`. Avoid `StringIndexOutOfBoundsException` that were cause when options were missing (`ctx` is null)

File: docs/changelog/138363.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+pr: 138363
+summary: Fix `StringIndexOutOfBoundsException` in COMPLETION command when option…
```
Comment (kderusso) [inline docs/changelog/138363.yaml]: Nitpick: Looks like the summary was truncated?

**Review by kderusso — APPROVED** [review]
LGTM

File: docs/changelog/138363.yaml (hunk 3 above)
Comment (afoucret) [inline docs/changelog/138363.yaml]: This is right.

```suggestion
summary:Fix StringIndexOutOfBoundsException in COMPLETION command when options are omitted.
