### PR TITLE
[Test] Ensure correct initial datasetSize estimation

### LINKED ISSUE #99762: StoreTests.testStoreSize
### CI Link

https://gradle-enterprise.elastic.co/s/doijmf2rj77a6/console-log?task=:server:test

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.index.store.StoreTests.testStoreSizes" -Dtests.seed=BAFF5AE277B58421 -Dtests.locale=en-NZ -Dtests.timezone=America/Yellowknife -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
org.elasticsearch.index.store.StoreTests > testStoreSizes FAILED |  
java.lang.AssertionError: |  
Expected: <40L> |  
but: was <0L> |  
at __randomizedtesting.SeedInfo.seed([BAFF5AE277B58421:76B6314660FDF343]:0) |  
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
at org.junit.Assert.assertThat(Assert.java:956) |  
at org.junit.Assert.assertThat(Assert.java:923) |  
at org.elasticsearch.index.store.StoreTests.testStoreSizes(StoreTests.java:878)
```

The log also seems to indicate a corrupt index, but I'm not sure if this is expected. It fails reliable with the given repro line (on JDK 20 and 21).

### PR DESCRIPTION
**Pull request by ywangd**
This PR accounts for the extra file created by ExtraFS for initial dataset size estimation.

Resolves: #99762

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/store/StoreTests.java [hunk 1]
```diff
@@ -815,7 +815,7 @@ public void testStoreSizes() throws IOException {
         // directory that returns total written bytes as the data set size
         final var directory = new ByteSizeDirectory(StoreTests.newDirectory(random())) {
 
-            final AtomicLong dataSetBytes = new AtomicLong(0L);
+            final AtomicLong dataSetBytes = new AtomicLong(estimateSizeInBytes(getDelegate()));
```
Comment (ywangd) [inline server/src/test/java/org/elasticsearch/index/store/StoreTests.java:818]: I am new to this area of code. Please let me know if the fix makes sense. Thanks!

**Review by pxsalehi — APPROVED** [review]
Also not super familiar with this, but the fix makes sense to me as well.
