### PR TITLE
ES|QL: Fix queries with document level security on lookup indexes

### LINKED ISSUE #120509: ESQL: Make LOOKUP JOIN respect document level permissions
Currently, LOOKUP JOIN respects index level permissions, and it seems like it also correctly respects [field level permissions](https://www.elastic.co/guide/en/elasticsearch/reference/current/field-level-security.html). It does not, however, respect [document level permissions](https://www.elastic.co/guide/en/elasticsearch/reference/current/document-level-security.html).

We should:
- Fix the latter and add tests.
- Also add tests for field level security, and
- add tests for a mix of both to guard against regressions in any possible weird edge cases.

What follows is a way to locally see that document level security is not yet respected.

Setup:
```
./gradlew run -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.es.xpack.license.self_generated.type=trial -Dtests.es.xpack.security.enabled=true 

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_security/role/test_role" -d '{
  "indices": [
    {                                                
      "names": [ "test*" ], 
      "privileges": [ "read" ],
      "field_security" : {          
        "grant" : [ "x", "y" ]
      }, "query": "{\"match\": {\"z\": 1}}"
    }
  ]
}'

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_security/user/test_user" -d'
{
  "password" : "123456",                             
  "roles" : [ "test_role" ],
  "full_name" : "Test Role",
  "email" : "test.role@example.com"
}'

curl -u elastic-admin:elastic-password -H "Content-Type: application/json" "127.0.0.1:9200/test_lookup" -XPUT -d '{
  "mappings": {        
        "properties": {"x": {"type": "integer"}, "y": {"type": "integer"}}}, "settings": {"index": {"mode": "lookup"}}}'

curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test_lookup/_doc?refresh' -d '{"x": 1, "y": 1, "z": null}'
```

Confirming that permissions work if using `FROM test_lookup`:
```

curl -u test_user:123456 -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{                                                                                                                                  
  "query": "from test_lookup"
}'
       x       |       y       
---------------+---------------
```

Now, using `LOOKUP JOIN`, we still have access to the document that didn't show up above:
```
curl -u test_user:123456 -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{
  "query": "row x = 1 | lookup join test_lookup on x"
}'
       x       |       y       
---------------+---------------
1              |1   
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/120509

Make ES|QL respect document level permissions on lookup indexes.

This fix exposes a problem with aliases as lookup indexes: if a user has permissions on an alias, but not on the underlying index, the query fails with an authorization error. This needs to be investigated further and fixed. For now we'll just disable support for aliases in LOOKUP JOIN command

### CODE REVIEW

**Comment by luigidellaquila** [comment]
Failures due to https://github.com/elastic/elasticsearch/pull/120637

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 1]
```diff
@@ -109,6 +112,16 @@ Collection<Failure> verify(LogicalPlan plan, BitSet partialMetrics) {
         return failures.failures();
     }
 
+    private void checkLookupJoin(LogicalPlan p, Failures failures) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:115]: Drive by comment: `LookupJoin` could implement `PostAnalysisVerificationAware` and perform the check there.

**Review by dnhatn — APPROVED** [review]
The LookupService looks good to me. Thanks @luigidellaquila

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:115]: Thanks @bpintea, good point, doing it now

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java [hunk 2]
```diff
@@ -563,25 +564,50 @@ public void testLookupJoinIndexAllowed() throws Exception {
         );
         assertThat(respMap.get("values"), equalTo(List.of(List.of(40.0, "sales"))));
 
-        // Alias, should find the index and the row
-        resp = runESQLCommand("alias_user1", "ROW x = 31.0 | EVAL value = x | LOOKUP JOIN `lookup-first-alias` ON value | KEEP x, org");
+        // Aliases are now allowed in LOOKUP JOIN
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:567]:
```suggestion
        // Aliases are not allowed in LOOKUP JOIN
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 3]
```diff
@@ -71,4 +75,14 @@ protected NodeInfo<Join> info() {
             config().rightFields()
         );
     }
+
+    @Override
+    public void postAnalysisVerification(Failures failures) {
+        super.postAnalysisVerification(failures);
+        if (right() instanceof EsRelation esr) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:82]: Rather than directly checking `right`, can we traverse down and look for the `EsRelation`?

I'm afraid we might stuff something else between the `EsRelation` and the lookup join some time in the future, and then this check will be accidentally circumvented.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 4]
```diff
@@ -71,4 +75,14 @@ protected NodeInfo<Join> info() {
             config().rightFields()
         );
     }
+
+    @Override
+    public void postAnalysisVerification(Failures failures) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:80]: Nit: While I think using `PostAnalysisVerificationAware` is preferable, now the checks for lookup join are split between here and directly in `Analyzer.resolveIndex`: https://github.com/elastic/elasticsearch/blob/e2f2ac35c2f91f101dc049a3f06a184c78c69873/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java#L240-L256

If it's not too much work, could we consolidate the two?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 5]
```diff
@@ -71,4 +75,14 @@ protected NodeInfo<Join> info() {
...
+        super.postAnalysisVerification(failures);
+        if (right() instanceof EsRelation esr) {
+            if (esr.concreteIndices().contains(esr.indexPattern()) == false) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:83]: nit: can we add a comment here that this check may be crucial for security, as we cannot deal with aliases adequately, yet?

Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:83]: Also: Could there be weird edge cases where the name of the index contains e.g. an escaped wildcard character, so that an index pattern _is_ being used, but coincidentally, it also matches a concrete index? There's no escaping in index names, right? Per the docs it doesn't seem so: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html

I understand this is as edge case-y as it gets; but since avoiding aliases is required to ensure permissions are respected correctly, we better try to think about every possible scenario.

**Review by alex-spies — COMMENTED** [review]
Had a first look, will continue tomorrow. Looking good so far, thanks @luigidellaquila !

File: docs/changelog/120617.yaml [hunk 6]
```diff
@@ -0,0 +1,5 @@
+pr: 120617
+summary: Fix queries with document level security on lookup indexes
+area: ES|QL
+type: bug
+issues: []
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply docs/changelog/120617.yaml:5]: Uhm... I expected the bot to pick it up from the issue description. No big deal, I'll add it manually

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/190_lookup_join.yml [hunk 7]
```diff
@@ -102,7 +102,10 @@ non-lookup index:
   - contains: { error.reason: "Found 1 problem\nline 1:45: invalid [test] resolution in lookup mode to an index in [standard] mode" }
 
 ---
+
 "Alias as lookup index":
+  - skip:
+      awaits_fix: "LOOKUP JOIN does not support index aliases for now"
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/190_lookup_join.yml:108]: This one skips the test on current release; `task.skipTest` skips bwc tests (yamlRestCompatTest), that fetch yaml files from _previous builds_

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java (hunk 4 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:80]: I guess the check in `Analyzer` is generic (ie. doesn't refer to LOOKUP) only because it's easier and because we use IndexMode.LOOKUP only in LOOKUP JOIN.
I'll move it to LookupJoin.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java [hunk 8]
```diff
@@ -270,4 +275,17 @@ protected void innerRelease() {
...
+
+    @Override
+    protected void sendChildRequest(
+        CancellableTask parentTask,
+        ActionListener<List<Page>> delegate,
+        DiscoveryNode targetNode,
+        TransportRequest transportRequest
+    ) {
+        ThreadContext threadContext = transportService.getThreadPool().getThreadContext();
+        try (ThreadContext.StoredContext unused = threadContext.stashWithOrigin(ClientHelper.ENRICH_ORIGIN)) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java:287]: Can we try and add a comment here with the best understanding that we can gather on what's happening here?

I think it's crucial and extremely important for how permissions are handled for ENRICH.

My understanding:
- This performs the ENRICH lookup without regard for the role of the user that sent the query. That is, at this point we _assume_ that we are allowed to access any enrich index.
- This is safe because there's a dedicated privilege for ENRICH which is checked before we reach here, more specifically where `hasPrivilege` is being used. (I see `manage_enrich` and `monitor_enrich` [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html), and I think we require the latter - although the former seems to be stronger and is probably also sufficient.)

@dnhatn , could you maybe confirm that this is happening, or correct me if I'm wrong?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 9]
```diff
@@ -71,4 +76,40 @@ protected NodeInfo<Join> info() {
...
+                            "invalid [{}] resolution in lookup mode to an index in [{}] mode",
+                            esr.indexPattern(),
+                            indexNameWithModes.values().iterator().next()
+                        )
+                    );
+                }
+
+            }
+
+            // this check is crucial for security: ES|QL would use the concrete indices, so it would bypass the security on the alias
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:109]: Note: After debugging a little, I believe we wouldn't actually bypass security, but we would "forget" about the alias and instead act as if the concrete index was requested - which the user may or may not have permissions on. But it's still better to leave this comment as-is in to emphasize that changing this check should be scary.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java (hunk 4 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:81]: Yeah. I think it's actually clearer the way you moved it.

This relied on the fact that we assign `IndexMode.LOOKUP` at _parsing time_ to the `UnresolvedRelation` obtained from parsing `LOOKUP JOIN`. But that's more convoluted than your PR's current solution.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 10]
```diff
@@ -71,4 +76,40 @@ protected NodeInfo<Join> info() {
             config().rightFields()
         );
     }
+
+    @Override
+    public void postAnalysisVerification(Failures failures) {
+        super.postAnalysisVerification(failures);
+        right().forEachDown(EsRelation.class, esr -> {
+
+            if (esr.indexMode().equals(IndexMode.LOOKUP)) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:85]: This `if` has become redundant. The right hand side of the `LOOKUP JOIN` _must_ have `IndexMode.LOOKUP`, otherwise something is wrong.

I'd remove this `if`, otherwise we might mask failures. In fact, given that we rely on `esr.indexMode` in the optimizer (maybe questionably, so?), I think we should either
- add an assertion that `esr.indexMode` is `IndexMode.LOOKUP`, or
- add an outright check that fails with `InvalidStateException`.

File: x-pack/plugin/esql/qa/security/src/javaRestTest/resources/roles.yml
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/resources/roles.yml:1]: To be extra paranoid, could we maybe
- add another document-level-security role with a different query and check what happens when a user has both roles assigned?
- Similarly, it'd be interesting to have a test where the user has two field level security roles assigned to them.

I'd like to guard against the system accidentally applying only one role; although this would likely be an "upstream" bug (not from esql itself), we could also accidentally mess with e.g. the threadcontext or so and lose a role. Maybe.

(Mixtures of both, dls and fls, would also be interesting, but that's extra, extra paranoid)

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:1]: I think we need to add some fls tests as well.

Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:1]: And finally, some tests with data streams.

**Review by alex-spies — COMMENTED** [review]
Thanks Luigi, this looks great. I believe the solution is correct, and double checked that with your approach, the actual user role is used to check if they have the permissions on the concrete index. (Although I'm no expert on our security system, of course.)

My remarks are minor or suggestions to have more tests, but this could also be merged as-is if you wanted to address something in a follow-up PR instead.

File: x-pack/plugin/esql/qa/security/src/javaRestTest/resources/roles.yml [hunk 11]
```diff
@@ -93,6 +93,21 @@ fls_user:
...
+      field_security:
+        grant: [ "org", "value" ]
+
+fls_user3:
+  cluster: []
+  indices:
+    - names: [ 'lookup-user2' ]
+      privileges: [ 'read' ]
+      field_security:
+        grant: [ "org", "value", "other" ]
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/resources/roles.yml:110]: nit: the granted fields of `fls_userX` are always subsets of one another. Maybe it'd be interesting to have a `fls_user4` that has only `org` granted - then what happens if I have roles `fls_user` and `fls_user4`?

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java [hunk 12]
```diff
@@ -608,6 +625,65 @@ public void testLookupJoinDocLevelSecurity() throws Exception {
...
+
+        resp = runESQLCommand("dls_user2", "ROW x = 32.0 | EVAL value = x | LOOKUP JOIN `lookup-user2` ON value | KEEP x, org");
+        assertOK(resp);
+        respMap = entityAsMap(resp);
+        assertThat(
+            respMap.get("columns"),
+            equalTo(List.of(Map.of("name", "x", "type", "double"), Map.of("name", "org", "type", "keyword")))
+        );
+        assertThat(respMap.get("values"), equalTo(List.of(List.of(32.0, "marketing"))));
+
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:648]: Nice, these are very helpful. Thanks for adding!

**Review by alex-spies — APPROVED** [review]
Thanks a lot for the iterations @luigidellaquila !

I have a final test suggestion, but otherwise LGTM.

File: x-pack/plugin/esql/qa/security/src/javaRestTest/resources/roles.yml (hunk 11 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/security/src/javaRestTest/resources/roles.yml:110]: Thanks Alex!
Added one more test with non overlapping roles

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 13]
```diff
@@ -71,4 +76,36 @@ protected NodeInfo<Join> info() {
...
+    @Override
+    public void postAnalysisVerification(Failures failures) {
+        super.postAnalysisVerification(failures);
+        right().forEachDown(EsRelation.class, esr -> {
+            var indexNameWithModes = esr.indexNameWithModes();
+            if (indexNameWithModes.size() != 1) {
+                failures.add(
+                    fail(
+                        esr,
+                        "invalid [{}] resolution in lookup mode to an index in [{}] indices",
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:89]:
```suggestion
                        "invalid [{}] resolution in lookup mode to [{}] indices",
```

Previously it had a slightly different message, not sure if it was changed intentionally.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java (hunk 8 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java:290]: Thanks @dnhatn, I agree, it will make things much more clear. Doing it now.

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java:290]: Agree, with @dnhatn 's suggestion the whole situation is more localized and more clear.

Personally, I'd still leave a comment in place because for people unfamiliar with this code, it can be unexpected that the call to `ThreadContext.stashWithOrigin` will abandon the current user's authorization. (It's explained in `stashWithOrigin`'s javadoc, but that requires an extra hop.)

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java [hunk 14]
```diff
@@ -674,6 +685,20 @@ public void testLookupJoinFieldLevelSecurity() throws Exception {
...
+            respMap.get("columns"),
+            equalTo(
+                List.of(
+                    Map.of("name", "x", "type", "double"),
+                    Map.of("name", "value", "type", "double"),
+                    Map.of("name", "org", "type", "keyword")
+                )
+            )
+        );
     }
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:702]: Sorry, one last test suggestion - we can also add this in a separate PR if you're already about to make this ready to merge.

I just noticed: all of the fls test cases have permission to read the `value` field, which is the join key.

I think it'd be interesting if forbidding this field for a user makes it so all look ups are null. And, if we wanna be extra paranoid, consider the case where the lookup index has duplicates for a given join key, so the `LOOKUP JOIN` would lead to extra rows - but without permissions granted on the join key, no extra rows should be emitted. (Otherwise, users could exfiltrate statistics about fields they have no permissions on).

**Review by alex-spies — APPROVED** [review]
Thanks a lot for the iterations @luigidellaquila ! I'm feeling much more confident about the security of `LOOKUP JOIN` now :)

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java (hunk 14 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:702]: Thanks Alex, I still have a couple of things to push, I'll add this one as well.
I _think_ the whole query will fail because the user doesn't see the join key in the schema, but I'll double-check

Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:710]: The new tests confirm the above: if a role cannot see the join key in the lookup index, the query will fail with "Unknown column"

**Comment by luigidellaquila** [comment]
Thanks for the reviews folks! 
I addressed all the comments, if there are no further observations I'll merge it as soon as the CI is happy.
