### PR TITLE
Reenable MonitoringIT.testMonitoringService

### LINKED ISSUE #29880: MonitoringIT testMonitoringService fails in CI
*Original comment by @jaymode:*

The `MonitoringIT#testMonitoringService` fails (but not reproducibly) in CI due to not finding documents that the test expects:

```
07:56:49 FAILURE 10.5s J1 | MonitoringIT.testMonitoringService <<< FAILURES!
07:56:49    > Throwable LINK REDACTED: java.lang.AssertionError: No monitoring documents yet
07:56:49    > Expected: a value greater than <0L>
07:56:49    >      but: <0L> was equal to <0L>
07:56:49    > 	at __randomizedtesting.SeedInfo.seed([7CC06B70BE47318E:572522E2D7107E38]:0)
07:56:49    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
07:56:49    > 	at org.elasticsearch.xpack.monitoring.integration.MonitoringIT.lambda$enableMonitoring$13(MonitoringIT.java:542)
07:56:49    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:734)
07:56:49    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:708)
07:56:49    > 	at org.elasticsearch.xpack.monitoring.integration.MonitoringIT.enableMonitoring(MonitoringIT.java:537)
07:56:49    > 	at org.elasticsearch.xpack.monitoring.integration.MonitoringIT.whenExportersAreReady(MonitoringIT.java:511)
07:56:49    > 	at org.elasticsearch.xpack.monitoring.integration.MonitoringIT.testMonitoringService(MonitoringIT.java:214)
07:56:49    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07:56:49    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
07:56:49    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:56:49    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
07:56:49    > 	at java.base/java.lang.Thread.run(Thread.java:844)
07:56:49    > 	Suppressed: java.lang.AssertionError: No monitoring documents yet
```

Failure links:
LINK REDACTED
LINK REDACTED
LINK REDACTED
LINK REDACTED

I am muting this test on master and 6.x. Assigning to @pickypg and @tlrx based on git history.

### PR DESCRIPTION
**Pull request by tlrx**
This pull request reenables the test `MonitoringIT.testMonitoringService` and gives it a bit more time to start. This is curious that the test `testMonitoringBulk` passes and not this one, so I'm opening this pull request and I'll give it many CI builds to see if it fails a lot or not.

Closes #29880

### CODE REVIEW

**Comment by tlrx** [comment]
Test is green, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Test is green, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Test is green, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Test is red but this is unrelated to this change, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Test is red but this is unrelated to this change, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Test is green, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Test is green, let's run it again: @elasticmachine run elasticsearch-ci/2

**Comment by tlrx** [comment]
Given the facts that this pull request got many successful builds and that the other test in the same class does not fail, I think we can reenable the muted test and see how it goes.

Can anyone from the @elastic/es-core-features team review this please?

File: x-pack/plugin/monitoring/src/test/java/org/elasticsearch/xpack/monitoring/integration/MonitoringIT.java [hunk 1]
```diff
@@ -374,9 +374,6 @@ private void assertClusterStatsMonitoringDoc(final Map<String, Object> document,
         assertThat(clusterState.remove("cluster_uuid"), notNullValue());
         assertThat(clusterState.remove("master_node"), notNullValue());
         assertThat(clusterState.remove("nodes"), notNullValue());
```
Comment (jakelandis) [inline x-pack/plugin/monitoring/src/test/java/org/elasticsearch/xpack/monitoring/integration/MonitoringIT.java]: Curious to why we are removing these assertions ?

Comment (tlrx) [reply x-pack/plugin/monitoring/src/test/java/org/elasticsearch/xpack/monitoring/integration/MonitoringIT.java]: I think it's been added for Zen 2 but removed afterwards, but not noticed since the test was muted.

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
Thanks @jakelandis ! I merged this pull request and I'm going to let it run on CI/master for a few days before backporting the change to other branches.

**Comment by jpountz** [comment]
Removing the `v7.1.0` and `backport pending` labels after discussing with @tlrx.
