### PR TITLE
Fix memory segment overrun for D1Q4 bbq_disk comparisons

### LINKED ISSUE #143648: [CI] ESNextOSQVectorsScorerTests class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11934 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ne6nlq3y3u6jq)
- [elasticsearch-periodic-platform-support #11934 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/6o2d67akysrgc)
- [elasticsearch-periodic-java-ea #195 / checkpart1_windows-2025](https://gradle-enterprise.elastic.co/s/vf3k342pfgcfi)
- [elasticsearch-periodic-java-ea #195 / checkpart1_windows-2025](https://gradle-enterprise.elastic.co/s/lobjf7htwefzo)
- [elasticsearch-periodic-java-ea #194 / checkpart1_windows-2025](https://gradle-enterprise.elastic.co/s/z2frtakmakpcg)
- [elasticsearch-periodic-platform-support #11926 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/vn7j446q5vdke)
- [elasticsearch-periodic-platform-support #11926 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bjy4h7bsozmvi)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/dlnywrstol3mq)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-140-3-matrix](https://gradle-enterprise.elastic.co/s/vabfnanwv5p5a)
- [elasticsearch-periodic #11949 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/angbtunwbp6d4)

**Reproduction Line:**
```
gradlew ":libs:simdvec:test" --tests "org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests.testScoreBulkNonAlignedBulkSize {p0=MMAP p1=1 p2=4 p3=MAXIMUM_INNER_PRODUCT}" -Dtests.seed=63153AE8A3863AF8 -Dtests.locale=tt -Dtests.timezone=Africa/Lome -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ kind: mapped, address: 0x1e20ffd03de, byteSize: 368 }; new offset = 368; new length = 4
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [main] 3 consecutive failures in step checkpart1_windows-2025
- [main] 12 failures in class org.elasticsearch.simdvec.internal.vectorization.ESNextOSQVectorsScorerTests (1.7% fail rate in 712 executions)
- [main] 2 failures in step windows-2022_checkpart1_platform-support-windows (66.7% fail rate in 3 executions)
- [main] 2 failures in step openjdk21_checkpart1_java-fips-140-3-matrix (50.0% fail rate in 4 executions)
- [main] 2 failures in step openjdk21_checkpart1_java-fips-matrix (50.0% fail rate in 4 executions)
- [main] 3 failures in step checkpart1_windows-2025 (100.0% fail rate in 3 executions)
- [main] 2 failures in step windows-2025_checkpart1_platform-support-windows (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-java-ea (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by thecoop**
Fixes #143648. The wrong parameter was passed in, causing a memory segment overrun. This fixes D1Q4 to match the other implementations.

It was only found on windows, as linux tests use the native implementation.

Not a 'real' bug, as the nextBBQ format is not released yet

### CODE REVIEW

File: libs/simdvec/src/main21/java/org/elasticsearch/simdvec/internal/vectorization/MSBitToInt4ESNextOSQVectorsScorer.java [hunk 1]
```diff
@@ -738,7 +738,7 @@ private float applyCorrections256BulkImpl(
                 scores,
                 bulkSize,
                 limit,
-                i,
+                0,
```
Comment (ldematte) [inline libs/simdvec/src/main21/java/org/elasticsearch/simdvec/internal/vectorization/MSBitToInt4ESNextOSQVectorsScorer.java]: It took me a bit, but I see what's going on: we are applying the offset twice here, once as "limit", once as i. I think this needs to be fixed in applyCorrections128BulkImpl too; better, offset is always 0, so we should get rid of it.

Comment (thecoop) [reply libs/simdvec/src/main21/java/org/elasticsearch/simdvec/internal/vectorization/MSBitToInt4ESNextOSQVectorsScorer.java]: Ah yes, this parameter can just go away

**Review by ldematte — APPROVED** [review]
LGTM
