### PR TITLE
Fix(?) and unmute DatafeedJobsRestIT.

### LINKED ISSUE #111319: [CI] DatafeedJobsRestIT class failing
**Build Scans:**
- [elasticsearch-periodic #5168 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/cpqzyf3llnjdq)
- [elasticsearch-pull-request #44085 / part-4](https://gradle-enterprise.elastic.co/s/6p5gnffnemybe)
- [elasticsearch-pull-request #43932 / part-4](https://gradle-enterprise.elastic.co/s/vzkhnvq7hermu)
- [elasticsearch-pull-request #43505 / part-4](https://gradle-enterprise.elastic.co/s/67h222r5mzgwu)
- [elasticsearch-pull-request #43443 / part-4](https://gradle-enterprise.elastic.co/s/ieqwp6colwktw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT.testLookbackOnlyWithRuntimeFields" -Dtests.seed=E28CDC0671B1A13E -Dtests.locale=naq -Dtests.timezone=America/Montevideo -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 2 active tasks found:
cluster:admin/xpack/ml/job/close    z-Mju6L3TEyJVV1HCrOduA:24555 -                            transport  1733147134469 13:45:34 1.8m        127.0.0.1 javaRestTest-2 
cluster:admin/xpack/ml/job/close[n] z-Mju6L3TEyJVV1HCrOduA:24561 z-Mju6L3TEyJVV1HCrOduA:24555 transport  1733147134477 13:45:34 1.8m        127.0.0.1 javaRestTest-2 
 expected:<0> but was:<2>
```

**Issue Reasons:**
- [main] 5 failures in class org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT (0.7% fail rate in 740 executions)
- [main] 4 failures in step part-4 (1.5% fail rate in 263 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 261 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116127: [CI] DatafeedJobsRestIT testLookbackWithIndicesOptions failing
**Build Scans:**
- [elasticsearch-intake #12331 / part4](https://gradle-enterprise.elastic.co/s/ps5jgpdvyn6xu)
- [elasticsearch-pull-request #39604 / part-4](https://gradle-enterprise.elastic.co/s/n533ui7iczdnq)
- [elasticsearch-pull-request #39601 / part-4](https://gradle-enterprise.elastic.co/s/smnyfmomqkpkg)
- [elasticsearch-pull-request #39601 / part-4](https://gradle-enterprise.elastic.co/s/yaevxkrbinwba)
- [elasticsearch-pull-request #39593 / part-4](https://gradle-enterprise.elastic.co/s/ucmnz7keol7yk)
- [elasticsearch-intake #12322 / part4](https://gradle-enterprise.elastic.co/s/zi3wit3h6cesa)
- [elasticsearch-intake #12321 / part4](https://gradle-enterprise.elastic.co/s/ayuu7uc7sshvq)
- [elasticsearch-intake #12319 / part4](https://gradle-enterprise.elastic.co/s/j6rajvmeocqhk)
- [elasticsearch-intake #12311 / part4](https://gradle-enterprise.elastic.co/s/qw3ui7nfttq7u)
- [elasticsearch-intake #12314 / part4](https://gradle-enterprise.elastic.co/s/jz7e7avaxjkya)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT.testLookbackWithIndicesOptions" -Dtests.seed=E7142F54D3B30265 -Dtests.locale=ar-DZ -Dtests.timezone=EST -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testLookbackWithIndicesOptions),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:39693], URI [/.hidden-index], status line [HTTP/1.1 200 OK]
Warnings: [Index [.hidden-index] name begins with a dot (.), which is deprecated, and will not be allowed in a future Elasticsearch version.]
{"acknowledged":true,"shards_acknowledged":true,"index":".hidden-index"}
```

**Issue Reasons:**
- [8.x] 10 consecutive failures in test testLookbackWithIndicesOptions
- [8.x] 6 consecutive failures in step part4
- [8.x] 4 consecutive failures in step part-4
- [8.x] 6 consecutive failures in pipeline elasticsearch-intake
- [8.x] 3 consecutive failures in pipeline elasticsearch-pull-request
- [8.x] 10 failures in test testLookbackWithIndicesOptions (100.0% fail rate in 10 executions)
- [8.x] 6 failures in step part4 (100.0% fail rate in 6 executions)
- [8.x] 4 failures in step part-4 (100.0% fail rate in 4 executions)
- [8.x] 6 failures in pipeline elasticsearch-intake (100.0% fail rate in 6 executions)
- [8.x] 3 failures in pipeline elasticsearch-pull-request (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes: https://github.com/elastic/elasticsearch/issues/111319
fixes: https://github.com/elastic/elasticsearch/issues/116127

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/DatafeedJobsRestIT.java [hunk 1]
```diff
@@ -1802,7 +1801,7 @@ private void bulkIndex(String bulk) throws IOException {
         bulkRequest.addParameter("refresh", "true");
         bulkRequest.addParameter("pretty", null);
         String bulkResponse = EntityUtils.toString(client().performRequest(bulkRequest).getEntity());
-        assertThat(bulkResponse, not(containsString("\"errors\": false")));
+        assertThat(bulkResponse, containsString("\"errors\" : false"));
```
Comment (jan-elastic) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/DatafeedJobsRestIT.java:1804]: This assertion is wrong and is suppressing potential problems.

**Review by davidkyle — APPROVED** [review]
LGTM
