### PR TITLE
ESQL: Fix COUNT+query push down losing aggs

### LINKED ISSUE #146479: ESQL: ArrayIndexOutOfBoundsException in GroupingAggregatorFunction
### Description

So there are multiple variants of this issue, including a different stacktrace altogether if the query is changed slightly. Posting them all below. But first, the original query:

```
from date_nanos 
| stats  nanos = count(*), kCVMjFGk = top(date_trunc(1 year, millis), 2, "desc"), GZpnHsjST = std_dev(num), tKvCCAlvSpSB = count(*) by num 
| inline stats  yLGnddnjMrg = count(*), TzPHmblZ = sum(GZpnHsjST) + sum(GZpnHsjST) + min(GZpnHsjST), GZpnHsjST = absent(kCVMjFGk), MduWZbflrUKK = count(kCVMjFGk) 
| rename TzPHmblZ AS kCVMjFGk 
| drop kCVMjFGk 
| FORK  (where true AND  NOT yLGnddnjMrg <= 39) (where true) (where true) (where  NOT true OR tKvCCAlvSpSB IS NOT NULL) (where true) (where  NOT false) 
| WHERE _fork == "fork4" 
| DROP _fork 
| where yLGnddnjMrg <= 92 AND  NOT yLGnddnjMrg == -94 
| keep nanos, yLGnddnjMrg, MduWZbflrUKK, GZpnHsjST
```

Now some simplifications, the first ones all have the same stack trace as the original above:

---

```
from date_nanos 
| stats a = count(*), y = top(date_trunc(1 year, millis), 2, "desc") by num 
| inline stats x = count(*), z = absent(y)
| keep x, z, a
```

results in

```
[WARN ][r.suppressed             ] [runTask-0] path: /_query, params: {format=txt, error_trace=true}, status: 500 java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at org.elasticsearch.compute.data.Page.getBlock(Page.java:169)
        at org.elasticsearch.compute.aggregation.TopLongGroupingAggregatorFunction.addIntermediateInput(TopLongGroupingAggregatorFunction.java:288)
        at org.elasticsearch.compute.aggregation.GroupingAggregator$1.add(GroupingAggregator.java:51)
        at org.elasticsearch.compute.operator.HashAggregationOperator$1AddInput.add(HashAggregationOperator.java:298)
        at org.elasticsearch.compute.aggregation.blockhash.LongBlockHash.add(LongBlockHash.java:82)
        at org.elasticsearch.compute.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:330)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:337)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:194)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:506)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1114)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.lang.Thread.run(Thread.java:1516)
```

---

```
from date_nanos 
 | stats a = count(*), y = max(date_trunc(1 year, millis)) by num 
 | inline stats x = count(*), z = absent(y)
 | keep x, z, a
```

results in 

```
[WARN ][r.suppressed             ] [runTask-0] path: /_query, params: {format=txt, error_trace=true}, status: 500 java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at org.elasticsearch.compute.data.Page.getBlock(Page.java:169)
        at org.elasticsearch.compute.aggregation.MaxLongGroupingAggregatorFunction.addIntermediateInput(MaxLongGroupingAggregatorFunction.java:318)
        at org.elasticsearch.compute.aggregation.GroupingAggregator$1.add(GroupingAggregator.java:51)
        at org.elasticsearch.compute.operator.HashAggregationOperator$1AddInput.add(HashAggregationOperator.java:298)
        at org.elasticsearch.compute.aggregation.blockhash.LongBlockHash.add(LongBlockHash.java:82)
        at org.elasticsearch.compute.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:330)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:337)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:194)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:506)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1114)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.lang.Thread.run(Thread.java:1516)
```

---

```
from employees 
 | stats a = count(*), y = top(date_trunc(1 year, hire_date), 2, "desc") by languages
 | inline stats x = count(*), z = absent(y)
 | keep x, z, a
```

results in **a different stack trace and error**

```
[WARN ][r.suppressed             ] [runTask-0] path: /_query, params: {format=txt, error_trace=true}, status: 500 java.lang.ClassCastException: class org.elasticsearch.compute.data.LongVectorBlock cannot be cast to class org.elasticsearch.compute.data.IntBlock (org.elasticsearch.compute.data.LongVectorBlock and org.elasticsearch.compute.data.IntBlock are in unnamed module of loader java.net.URLClassLoader @f0020b1)
        at org.elasticsearch.compute.aggregation.blockhash.IntBlockHash.add(IntBlockHash.java:73)
        at org.elasticsearch.compute.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:330)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:337)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:194)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:506)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1114)
        at org.elasticsearch.server@9.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.lang.Thread.run(Thread.java:1516)
```

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/146479

For a query like `STATS COUNT(*), MAX(ROUND_TO(...)) by y | DROP y`, the `PushCountQueryAndTagsToSource` rule tries to push it down based on:
- There's a single COUNT
- There's a BY
- There's a Lucene Query (RoundTo generates it)

However, the DROP removes the grouping from the aggs, and a missing condition thiks the second agg is a grouping, effectively discarding it.

Made with AI assistance

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToGoldenTests.java [hunk 1]
```diff
@@ -73,6 +73,36 @@ public void testDateTruncBucketTransformToQueryAndTagsWithMultipleAggregates() {
         }
     }
 
+    // https://github.com/elastic/elasticsearch/issues/146479
+    // When the grouping key is dropped and COUNT(*) is the only agg, CombineProjections removes
+    // the grouping key from aggregates leaving [COUNT] (size 1). The rule doesn't fire (missed
+    // optimization, but correct results).
+    public void testDateTruncCountOnlyNotPushedWhenGroupingKeyDropped() {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToGoldenTests.java]: Logic may be improved to effectively optimize this case. I'll try changing it to be simpler and more reliable, covering this case too

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 2]
```diff
@@ -5729,10 +5729,77 @@ from employees
...
+5              |10002          |F              |[1.0, 1.0, 1.0]|[1, 2, 3]
+4              |10003          |M              |[1.0, 1.0, 1.0]|[1, 2, 3]
+5              |10004          |M              |[1.0, 1.0, 1.0]|[1, 2, 3]
+1              |10005          |M              |[1.0, 1.0, 1.0]|[1, 2, 3]
+;
+
+inlineStatsAbsentOnTopWithDateTrunc
+required_capability: inline_stats
+required_capability: fn_absent
+required_capability: fix_push_count_query_and_tags_with_multiple_aggs
```
Comment (GalLalouche) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec:5741]: I think only the last capability is needed here, since we don't have to worry about compatibility with `CsvTests` anymore (here and below).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java [hunk 3]
```diff
@@ -65,10 +65,14 @@ protected PhysicalPlan rule(AggregateExec aggregateExec) {
         // There should be exactly one grouping field (hence 2 aggregates: agg + group by field).
         // The aggregation should be Count(*) or CountApproximate(*), without a filter on the count
         // itself.
+        // Note: CombineProjections may remove the grouping key from aggregates when it's unused
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java]: Should this comment appear closer to the actual condition being checked?

File: x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/golden_tests/SubstituteRoundToGoldenTests/testDateTruncBucketNotTransformToQueryAndTagsWithLookupJoin/bucket/local_physical_optimization.expected [hunk 4]
```diff
@@ -1,11 +0,0 @@
-LimitExec[1000[INTEGER],null]
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/golden_tests/SubstituteRoundToGoldenTests/testDateTruncBucketNotTransformToQueryAndTagsWithLookupJoin/bucket/local_physical_optimization.expected:1]: Is this an orphan output?

**Review by GalLalouche — APPROVED** [review]
Thanks @ivancea! I have a few minor notes/questions, but otherwise LGTM.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java [hunk 5]
```diff
@@ -65,10 +65,14 @@ protected PhysicalPlan rule(AggregateExec aggregateExec) {
...
+        // downstream, leaving 2 aggregates that are both aggregate functions (e.g. COUNT + MAX).
+        // We must verify the second aggregate is NOT an aggregate function.
         if (aggregateExec.aggregates().size() == 2
             && aggregateExec.aggregates().getFirst() instanceof Alias alias
             && ((alias.child() instanceof Count count && count.hasFilter() == false && count.field() instanceof Literal)
                 || (alias.child() instanceof CountApproximate ca && ca.hasFilter() == false && ca.field() instanceof Literal))
+            && (Alias.unwrap(aggregateExec.aggregates().get(1)) instanceof AggregateFunction == false)
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java]:
```suggestion
        // CombineProjections may remove the grouping key from aggregates when it's unused downstream
        // (e.g. DROP x), so we positively verify the second aggregate matches the single grouping key.
        if (aggregateExec.aggregates().size() == 2
            && aggregateExec.groupings().size() == 1
            && aggregateExec.aggregates().getFirst() instanceof Alias alias
            && ((alias.child() instanceof Count count && count.hasFilter() == false && count.field() instanceof Literal)
                || (alias.child() instanceof CountApproximate ca && ca.hasFilter() == false && ca.field() instanceof Literal))
            && Expressions.equalsAsAttribute(Alias.unwrap(aggregateExec.aggregates().get(1)), aggregateExec.groupings().get(0))
```

This is not a big change, it's just a more robust check for the things it's checking.  The check "second aggregate is NOT an AggregateFunction" is a negative check. It would be more robust to positively verify that the second aggregate matches one of the grouping keys. For example, if some future optimization introduced a non-AggregateFunction, non-grouping expression at position 1 in aggregates(), this check would incorrectly allow the rule to fire.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec [hunk 6]
```diff
@@ -4185,5 +4185,59 @@ from employees
 ;
 
     max(c):l   |    min(c):l   |    min(s):d   |    avg(s):d
-null           |null           |null           |null           
+null           |null           |null           |null
+;
+
+statsCountAndMaxWithDateTruncDropGroupingKey
+required_capability: fix_push_count_query_and_tags_with_multiple_aggs
+
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:4193]: I would add some more tests here:
```
FROM employees
| EVAL x = DATE_TRUNC(1 year, hire_date)
| STATS y = COUNT(*), a = MAX(salary), y = COUNT(*) BY x
| DROP x
```

```
FROM employees
| EVAL x = DATE_TRUNC(1 year, hire_date)
| STATS y = COUNT(*), a = MAX(salary), z = COUNT(*) BY x
| DROP x
```

```
FROM employees
| EVAL x = DATE_TRUNC(1 year, hire_date)
| STATS a = MAX(salary), y = COUNT(*) BY x
| DROP x
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java [hunk 7]
```diff
@@ -65,10 +65,14 @@ protected PhysicalPlan rule(AggregateExec aggregateExec) {
         // There should be exactly one grouping field (hence 2 aggregates: agg + group by field).
         // The aggregation should be Count(*) or CountApproximate(*), without a filter on the count
         // itself.
+        // Note: CombineProjections may remove the grouping key from aggregates when it's unused
+        // downstream, leaving 2 aggregates that are both aggregate functions (e.g. COUNT + MAX).
+        // We must verify the second aggregate is NOT an aggregate function.
         if (aggregateExec.aggregates().size() == 2
             && aggregateExec.aggregates().getFirst() instanceof Alias alias
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java:77]: @GalLalouche do you remember why this is was designed like this? This reads `| STATS y = COUNT(*), a = MAX(salary) BY languages` has the optimization applied while `| STATS a = MAX(salary), y = COUNT(*) BY languages` does not.

If there are no strong reasons for doing it like this, may I suggest a GH issue and follow up?

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec [hunk 8]
```diff
@@ -4185,5 +4185,59 @@ from employees
...
+5
+6
+8
+9
+11
+11
+12
+13
+15
 ;
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:4243]: And another test for multiple groupings, please:

```
FROM employees
| EVAL x = DATE_TRUNC(1 year, hire_date)
| STATS a = COUNT(*) BY x, languages
| DROP x
| SORT languages, a
| LIMIT 5
```

Might be worth also adding a golden test for this one.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 9]
```diff
@@ -5729,10 +5729,77 @@ from employees
...
+;
+ignoreOrder:true
+
+x:long | z:boolean | a:long
+6      | false     | 10
+6      | false     | 15
+6      | false     | 17
+6      | false     | 18
+6      | false     | 19
+6      | false     | 21
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec:5798]: And this one, please:

```
FROM employees
| EVAL x = DATE_TRUNC(1 year, hire_date)
| STATS a = COUNT(*), y = MAX(salary) BY x
| INLINE STATS total = SUM(a)
| KEEP a, y, total
| SORT a ASC, y ASC
| LIMIT 5
```

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec (hunk 8 above)
Comment (astefan) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:4243]: Or a golden test for something simpler but still with two groupings:

```
    public void testDateTruncBucketNotPushedWithMultipleGroupings() {
        for (var queryAndName : dateHistograms) {
            String query = LoggerMessageFormat.format(null, """
                from all_types
                | stats count(*) by x = {}, long
                """, queryAndName.query());
            runGoldenTest(query, EnumSet.of(Stage.LOCAL_PHYSICAL_OPTIMIZATION), STATS, queryAndName.name());
        }
    }
```

**Review by astefan — COMMENTED** [review]
LG. Left few comments. Most are optional, but would be good to have more tests. I would put more emphasis on the suggestion I made for the `PushCountQueryAndTagsToSource` check robustness.

File: x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/golden_tests/SubstituteRoundToGoldenTests/testDateTruncBucketNotTransformToQueryAndTagsWithLookupJoin/bucket/local_physical_optimization.expected (hunk 4 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/golden_tests/SubstituteRoundToGoldenTests/testDateTruncBucketNotTransformToQueryAndTagsWithLookupJoin/bucket/local_physical_optimization.expected:1]: I think so. I deleted everything from the outputs folder, and regenrated it, and those files disappeared. But I'll double check the test in case it's some other thing

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java (hunk 7 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java:77]: The optimization can only optimize a `STATS COUNT(*) BY x`. The second aggregate has to be the grouping attribute; it can't be another agg

Comment (GalLalouche) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushCountQueryAndTagsToSource.java:77]: What @ivancea said :) This is a very limited optimization.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToGoldenTests.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/SubstituteRoundToGoldenTests.java]: This was fixed too @astefan @GalLalouche. We don't require it to have "2 aggs" anymore. If it has 1 COUNT agg and 1 grouping, we optimize it too (Added CSV and Golden tests for this case)

**Review by astefan — APPROVED** [review]
LGTM
