### PR TITLE
Address UUIDTests#testCompression failures.

### LINKED ISSUE #50048: org.elasticsearch.common.UUIDTests.testCompression Fails
Multiple build failures due to this test failure

Reproduces reliably with: 
```
./gradlew ':server:test' --tests "org.elasticsearch.common.UUIDTests.testCompression" \
  -Dtests.seed=4713F1387D472105 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-BA \
  -Dtests.timezone=Africa/Asmera \
  -Dcompiler.java=12
```
Additional reproduce line:
```
./gradlew ':server:test' --tests "org.elasticsearch.common.UUIDTests.testCompression" \
  -Dtests.seed=5AD9FA10D2CE6D04 \
  -Dtests.security.manager=true \
  -Dtests.locale=bg \
  -Dtests.timezone=Pacific/Truk \
  -Dcompiler.java=12
```

Builds: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux-6&&immutable/443/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles-12&&immutable/443/console

Failure:
```
org.elasticsearch.common.UUIDTests > testCompression FAILED
    java.lang.AssertionError:
    Expected: a value less than <14.0>
         but: <15.22106> was greater than <14.0>
        at __randomizedtesting.SeedInfo.seed([4713F1387D472105:BC26D75E7799D156]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.common.UUIDTests.testCompression(UUIDTests.java:123)
```

### PR DESCRIPTION
**Pull request by jpountz**
Those were due to codec randomization.

Closes #50048

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/common/UUIDTests.java [hunk 1]
```diff
@@ -152,6 +153,7 @@ protected long currentTimeMillis() {
         // the quality of this test
         Directory dir = newFSDirectory(createTempDir());
         IndexWriterConfig config = new IndexWriterConfig()
+                .setCodec(Codec.forName("Lucene84"))
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/common/UUIDTests.java]: Should we use `Lucene.LATEST_CODEC` here so we don't need to update on every lucene bump in multiple places?

**Review by rjernst — APPROVED** [review]
LGTM
