### PR TITLE
Protect SortBuilder.toString() from JsonGenerationException.

### LINKED ISSUE #20853: SortBuilder toString throws an exception
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**: 1.8.0_31

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:

Trying to print a SortBuilder throws an exception. Expected behaviour is that toString returns a string.

This did work on 2.3.3

**Steps to reproduce**:
 1. Run this code:

````
import org.elasticsearch.search.sort.SortBuilder
import org.elasticsearch.search.sort.SortBuilders
import org.elasticsearch.search.sort.SortOrder

SortBuilder sort = SortBuilders.fieldSort('foo').order(SortOrder.DESC)

println sort
````

**Provide logs (if relevant)**:

Error message is:

````
Exception thrown
ElasticsearchException[Failed to build query]; nested: JsonGenerationException[Can not write a field name, expecting a value];
	at org.elasticsearch.search.sort.SortBuilder.toString(SortBuilder.java:40)
	at ConsoleScript2.run(ConsoleScript2:7)
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1886)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writePPFieldName(UTF8JsonGenerator.java:369)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:180)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:147)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:288)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:270)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:157)
	at org.elasticsearch.search.sort.FieldSortBuilder.toXContent(FieldSortBuilder.java:134)
	at org.elasticsearch.search.sort.SortBuilder.toString(SortBuilder.java:37)
	... 1 more
````

### PR DESCRIPTION
**Pull request by juazugas**
It fixes #20853. As @s1monw said in #20853 in 5.0 is been fixed and haven't been ported to 2.4 branch. 

SortBuilder.toString() throws an exception when tries to generate the Json equivalent string. Though is not a critical bug, the calls to this function must be protected in order to prevent the exception and the consecuent break.

I've added two test to ensure the right behaviour of the toString() function.

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import org.elasticsearch.common.xcontent.XContentFactory;
+import org.elasticsearch.common.xcontent.XContentType;
+import org.elasticsearch.test.ESTestCase;
+
+public class FieldSortBuilderTests extends ESTestCase {
+
+    private static final String FIELDNAME = "myfield";
+    private static final String QUOTES = "\"";
+
+    public void testToXContent() throws Exception {
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: I don't think you need to explicitely test toXContent, this is done by toString implicitely and this is the change that we want to check.

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        xc.startObject();
+        fieldSortBuilder.toXContent(xc, FieldSortBuilder.EMPTY_PARAMS);
+        xc.endObject();
+
+        assertThat(xc.string(), stringContainsInOrder(
+                Arrays.asList(QUOTES + FIELDNAME + QUOTES, QUOTES + "order" + QUOTES, QUOTES + SortOrder.ASC.toString() + QUOTES)));
+    }
+
+    public void testToString() throws Exception {
+        FieldSortBuilder fsb = prepareFSB();
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: For this simple test, maybe you can inline the builder creation.

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+
+        String fsbPrint = fsb.toString();
+
+        assertThat(fsbPrint, stringContainsInOrder(
+                Arrays.asList(QUOTES + FIELDNAME + QUOTES, QUOTES + "order" + QUOTES, QUOTES + SortOrder.ASC.toString() + QUOTES)));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: I'd prefer to have a simple `assertEquals` and to a String comparison here. No need for all the constants either, makes it harder to read IMHO.

File: core/src/test/java/org/elasticsearch/search/sort/ScriptSortBuilderTests.java [hunk 4]
```diff
@@ -58,4 +60,13 @@ public void testToXContentWithParams() throws Exception {
         
         assertEquals(xcWith.string(), xcWithOut.string());
     }
+    
+    public void testToString() {
+        ScriptSortBuilder ssb = prepareSSB();
+
+        String ssbPrint = ssb.toString();
+
+        assertThat(ssbPrint, containsString("testtype"));
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/sort/ScriptSortBuilderTests.java]: Same here, simple assertQuals with String comparison would be easier to read I think.

**Comment by cbuescher** [comment]
@juazugas thanks, I left a few comments, however I'm not entirely sure we should merge this to the 2.4 branch since its not a critical change and at this point it is not clear whether we will have any more releases from this branch. Normally we would only add critical bugfixes to these old branches, but this might be an exception because its very small and shouldn't affect much, I think. I will ask for others to comment.

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java (hunk 1 above)
Comment (juazugas) [reply core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: Ok. As FieldSortBuilder test didn't exist, I used it as an already-to-develop test before to start fixing the failing one. I didn't even think in remove it, but indeed it's not a needed test for this change.

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java (hunk 3 above)
Comment (juazugas) [reply core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: ToString method does a pretty print of the Json content. I didn't want to be bothered about whitespaces or tabs. At least will you concede me an equalToIgnoringWhiteSpace? I think that would do the test less fragile. Something like ...

```java
assertThat(fsbPrint, equalToIgnoringWhiteSpace("{\"myfield\":{\"order\":\"asc\"}}")
```

Or a simple checking like
```java
 assertTrue(fsbPrint.contains("myfield")). 
```
What do you think?

Comment (cbuescher) [reply core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: Good point, I forgot about the pretty printing. `equalToIgnoringWhiteSpace` sounds good.

**Comment by cbuescher** [comment]
@juazugas thanks for the changes, I can merge this to the branch but as I said at this point its unlikely that there will be any more 2.4 releases.
@elasticmachine test this please

File: core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java [hunk 5]
```diff
@@ -0,0 +1,18 @@
+package org.elasticsearch.search.sort;
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: @juazugas just realized our fabolous CI testing robot doesn't work on the 2.4 branch any more, I just kicked of a maven build by hand and realized this file needs out standard licencing header just like the other tests in this folder. Can you simply add it to the top of the file so it passes the licence header checks?

Comment (juazugas) [reply core/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java]: Ok.

**Comment by cbuescher** [comment]
@juazugas thanks, I merged this, though its unlikely we'll have another release from this branch.

**Comment by juazugas** [comment]
@cbuescher thanks to you. It's been a pleasure. Next time we'll catch it on time.
