### PR TITLE
ES|QL: Fix layout management for Project

### LINKED ISSUE #102120: ES|QL: NullPointerException on stats + mv_expand planning
The problem seems to be related to both multiple aggs with the same expression and mv_expand. Removing one of the two the query works fine

```
show functions |  stats  ctvxDDE = count(*), language_name = count(*), NzAUsvB = count(*) |  mv_expand NzAUsvB
```

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : "Cannot read field \"nameIds\" because \"set\" is null",
...
}
```

```
[2023-11-14T09:35:07,032][WARN ][o.e.x.e.a.EsqlResponseListener] [runTask-0] Request failed with status [INTERNAL_SERVER_ERROR]: java.lang.NullPointerException: Cannot read field "nameIds" because "set" is null
        at org.elasticsearch.xpack.esql.planner.Layout$Builder.append(Layout.java:79)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planMvExpand(LocalExecutionPlanner.java:626)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:202)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLimit(LocalExecutionPlanner.java:610)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:200)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:310)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:224)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:168)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:260)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.execute(ComputeService.java:143)
        at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$doExecuteForked$3(TransportEsqlQueryAction.java:108)

```

Maybe related to https://github.com/elastic/elasticsearch/issues/102083, but the error is different

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/102120

In case of multiple aggs with the same expression, the layout has multiple entries pointing to the same position.
Project planning didn't manage this situation properly, resulting in the same entry appearing multiple times in the layout and pointing to multiple positions (that violates the layout contract).
The planning of the following commands (eg. MV_EXPAND) resulted in a NullPointerException, because the layout.inverse() could not be calculated properly.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 1]
```diff
@@ -585,16 +585,20 @@ private PhysicalOperation planProject(ProjectExec project, LocalExecutionPlanner
...
+            if (channelSet == null) {
+                channelSet = new Layout.ChannelSet(new HashSet<>(), input.type());
+                newSet = true;// I cannot add an empty set, I'll do it later
+            }
             if (channelSet.type() != input.type()) {
                 throw new IllegalArgumentException("type mismatch for aliases");
             }
             channelSet.nameIds().add(ne.id());
 
-            layout.append(channelSet);
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:597]: The channelSet was added anyway, even if it was already added previously, resulting in duplicate entries in the layout.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java [hunk 2]
```diff
@@ -585,16 +585,20 @@ private PhysicalOperation planProject(ProjectExec project, LocalExecutionPlanner
...
+            if (newSet) {
+                layout.append(channelSet);
+            }
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:601]: I find it less easy to read and follow like this, but it's up to you:

```
            Layout.ChannelSet channelSet = inputChannelToOutputIds.get(input.channel());

            if (channelSet == null) {
                channelSet = new Layout.ChannelSet(new HashSet<>(), input.type());
                channelSet.nameIds().add(ne.id());
                layout.append(channelSet);
            } else {
                channelSet.nameIds().add(ne.id());
            }
            if (channelSet.type() != input.type()) {
                throw new IllegalArgumentException("type mismatch for aliases");
            }
```

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/LocalExecutionPlanner.java:601]: I agree, there is a small repetition but the readability is much better

**Review by astefan — APPROVED** [review]
With the additional tests in place, this LGTM.
