### PR TITLE
Ensure necessary security context for s3 bulk deletions

### LINKED ISSUE #108049: Deleting files in s3 buckets can trip AccessControlException
Since 8.13.0, the task runs in the background to delete stale files of snapshots can sometimes run into `AccessControlException`.  The most relevant stacktrace is show below. It's been identified that the issue is with running `deletePartition` inside the lambda of  `MapIterator.forEachRemaining` which changes the stack frame for SecurityManager and makes the top level `doPrivilegedVoid` not effective. The lambda version of `forEachRemaining` was introduced in #103581 which is part of the 8.13.0 release. We should change `doPrivileged` call to be tightly around the necessary networking call to re-establish correct the permission grant.

```
Caused by: java.security.AccessControlException: access denied ("java.net.SocketPermission" "x.x.x.x:y" "connect,resolve")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:488) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:1085) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:411) ~[?:?]
	at java.lang.SecurityManager.checkConnect(SecurityManager.java:905) ~[?:?]
	at java.net.Socket.connect(Socket.java:748) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[?:?]
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142) ~[?:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[?:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[?:?]
	at com.amazonaws.http.conn.$Proxy92.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[?:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[?:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[?:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[?:?]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:2335) ~[?:?]
	at org.elasticsearch.repositories.s3.S3BlobStore.deletePartition(S3BlobStore.java:338) ~[?:?]
	at org.elasticsearch.repositories.s3.S3BlobStore.lambda$deleteBlobsIgnoringIfNotExists$0(S3BlobStore.java:315) ~[?:?]
	at org.elasticsearch.common.collect.Iterators$MapIterator.lambda$forEachRemaining$0(Iterators.java:175) ~[elasticsearch-8.13.0.jar:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:314) ~[?:?]
	at java.util.Spliterators$1Adapter.forEachRemaining(Spliterators.java:706) ~[?:?]
	at org.elasticsearch.common.collect.Iterators$MapIterator.forEachRemaining(Iterators.java:175) ~[elasticsearch-8.13.0.jar:?]
	at org.elasticsearch.repositories.s3.S3BlobStore.lambda$deleteBlobsIgnoringIfNotExists$1(S3BlobStore.java:312) ~[?:?]
	at org.elasticsearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:46) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:45) ~[?:?]
	at org.elasticsearch.repositories.s3.S3BlobStore.deleteBlobsIgnoringIfNotExists(S3BlobStore.java:311) ~[?:?]
	... 9 more
```

### PR DESCRIPTION
**Pull request by ywangd**
This PR moves the doPrivileged wrapper closer to the actual deletion request to ensure the necesary security context is established at all times. Also added a new repository setting to configure max size for s3 deleteObjects request.

Fixes: #108049

### CODE REVIEW

File: x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/S3SnapshotRepoTestKitIT.java [hunk 1]
```diff
@@ -61,6 +61,11 @@ protected Settings repositorySettings() {
         final String basePath = System.getProperty("test.s3.base_path");
         assertThat(basePath, not(blankOrNullString()));
 
-        return Settings.builder().put("client", "repo_test_kit").put("bucket", bucket).put("base_path", basePath).build();
+        return Settings.builder()
+            .put("client", "repo_test_kit")
+            .put("bucket", bucket)
+            .put("base_path", basePath)
+            .put("deletion_batch_size", between(1, 1000))
```
Comment (ywangd) [inline x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/S3SnapshotRepoTestKitIT.java:68]: I took the easy way to piggyback on the existing repo analysis test. Please let me know if this works for you. Thanks!

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java [hunk 2]
```diff
@@ -172,6 +172,16 @@ class S3Repository extends MeteredBlobStoreRepository {
      */
     static final Setting<String> BASE_PATH_SETTING = Setting.simpleString("base_path");
 
+    /**
+     * The batch size for bulk deletion
+     */
+    static final Setting<Integer> DELETION_BATCH_SIZE_SETTING = Setting.intSetting(
+        "deletion_batch_size",
```
Comment (DaveCTurner) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java:179]: Naming nit/suggestion: WDYT about `delete_objects_max_size`? The relevant S3 API is called [`DeleteObjects`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) so I think mentioning that in the name would be helpful.

File: x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/S3SnapshotRepoTestKitIT.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/S3SnapshotRepoTestKitIT.java:68]: :+1: should be fine, but could you just confirm that this exposes the bug?

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java [hunk 3]
```diff
@@ -315,18 +319,19 @@ public void deleteBlobsIgnoringIfNotExists(OperationPurpose purpose, Iterator<St
...
-                        deletePartition(purpose, clientReference, partition, aex);
-                        partition.clear();
-                    }
-                });
-                if (partition.isEmpty() == false) {
+
+            blobNames.forEachRemaining(key -> {
+                partition.add(key);
+                if (partition.size() == bulkDeletionBatchSize) {
+                    logger.info("--> deleting INSIDE {}", partition);
```
Comment (DaveCTurner) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:326]: Stray debug log?

```suggestion
```

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java [hunk 4]
```diff
@@ -315,18 +319,19 @@ public void deleteBlobsIgnoringIfNotExists(OperationPurpose purpose, Iterator<St
...
                     deletePartition(purpose, clientReference, partition, aex);
+                    partition.clear();
                 }
             });
+            if (partition.isEmpty() == false) {
+                logger.info("--> deleting outside {}", partition);
```
Comment (DaveCTurner) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:332]: Stray debug log?

```suggestion
```

**Review by DaveCTurner — COMMENTED** [review]
Couple of nits, overall looks great tho. WDYT about backporting all the way to 8.13? I think there'll be another release before 8.14, would be good to fix this ASAP.

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java (hunk 3 above)
Comment (ywangd) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:326]: Errr yes. thanks for spotting it. removed.

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java (hunk 4 above)
Comment (ywangd) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobStore.java:332]: Removed as well.

File: x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/S3SnapshotRepoTestKitIT.java (hunk 1 above)
Comment (ywangd) [reply x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/S3SnapshotRepoTestKitIT.java:68]: Yes I tested locally with real s3 by setting the properties listed [here](https://github.com/elastic/elasticsearch/blob/5a6f8cdb97a7e2493e8bebf04bb3d9c9a304e143/x-pack/plugin/snapshot-repo-test-kit/qa/s3/build.gradle#L43-L48). I can confirm the test can fail without the fix. 

A few notes:
1. It does not fail with the fixture. I wonder whether it has something to do with the fixture running on localhost.
2. When the size is 1, it will fail at repo verification without even start running the test. 
3. I expected it to fail anytime the deletion is done inside the lambda but that is not always the case. I guess maybe if there is existing connection to perform the deletion request, it does not trigger the permission check. I did not look into it deeply since it feels sufficient to me that it does fail sometimes without the fix.

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java (hunk 2 above)
Comment (ywangd) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java]: Sounds good to me. Updated it as you suggested 61255e54b1b632193880817836a6cd960530b5de

**Comment by ywangd** [comment]
> WDYT about backporting all the way to 8.13? I think there'll be another release before 8.14, would be good to fix this ASAP.

I agree. Added v8.13.4. Thanks!

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Review by arteam — APPROVED** [review]
LGTM2

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.13|[](https://github.com/elastic/elasticsearch/pull/108299)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
