### PR TITLE
Remove bogus assertion in InternalEngine#flushHoldingLock

### LINKED ISSUE #103861: [CI] InternalEngineTests testConcurrentEngineClosed failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/qzvswg7p64vra/tests/:server:test/org.elasticsearch.index.engine.InternalEngineTests/testConcurrentEngineClosed

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testConcurrentEngineClosed" -Dtests.seed=F8DD0298C7176C72 -Dtests.locale=es-CO -Dtests.timezone=Universal -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.index.engine.InternalEngineTests#testConcurrentEngineClosed`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testConcurrentEngineClosed'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.index.engine.InternalEngineTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([F8DD0298C7176C72]:0)
  at org.elasticsearch.index.engine.InternalEngine.flushHoldingLock(InternalEngine.java:2174)
  at org.elasticsearch.index.engine.Engine.flushAndClose(Engine.java:1935)
  at org.elasticsearch.index.engine.InternalEngineTests$8.doRun(InternalEngineTests.java:3706)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
This assertion was introduced in #103871 but in fact it does not hold.
This is not a new thing, it would have failed before #103871 too:

```diff
diff --git a/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java b/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
index ca9ed06d4d2..ff305291fce 100644
--- a/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
+++ b/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
@@ -2181,6 +2181,15 @@ public class InternalEngine extends Engine {
     @Override
     protected void flushHoldingLock(boolean force, boolean waitIfOngoing, ActionListener<FlushResult> listener) throws EngineException {
         ensureOpen();
+
+        try {
+            Thread.sleep(100);
+        } catch (Exception e) {
+            throw new AssertionError(e);
+        }
+
+        assert isClosed.get() == false;
+
         if (force && waitIfOngoing == false) {
             assert false : "wait_if_ongoing must be true for a force flush: force=" + force + " wait_if_ongoing=" + waitIfOngoing;
             throw new IllegalArgumentException(
diff --git a/server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java b/server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
index cbb713f01ec..3d3a478ecc0 100644
--- a/server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
+++ b/server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
@@ -3688,6 +3688,7 @@ public class InternalEngineTests extends EngineTestCase {
             @Override
             protected void doRun() throws Exception {
                 barrier.await();
+                Thread.sleep(50);
                 engine.failEngine("test", new RuntimeException("test"));
             }
         });
```

Closes #103861

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -2177,8 +2177,7 @@ private boolean shouldPeriodicallyFlush(long flushThresholdSizeInBytes, long flu
 
     @Override
     protected void flushHoldingLock(boolean force, boolean waitIfOngoing, ActionListener<FlushResult> listener) throws EngineException {
-        assert isClosed.get() == false; // might be closing, but not closed yet
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:2180]: Did you consider changing it to:

```
assert isClosed.get() == false || failedEngine.get() != null;
```
?

**Review by henningandersen — APPROVED** [review]
LGTM

left one completely optional comment.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:2180]: I did, but it doesn't seem especially useful - it says we're either open, or closed due to a failure, but the reason for closing doesn't really matter here, AFAICT it'd be fine if we closed gracefully while running this method too.

Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:2180]: Makes sense, thanks for clarifying.
