### PR TITLE
Use the smallest version rather than the default version

### LINKED ISSUE #11474: Minimum compatible version being written as 3.6.0
I've run the upgrade API on indices created in 0.20, and it sets the minimum compatible version to 3.6.0, which means that ES 2.0 fails to open them.

### PR DESCRIPTION
**Pull request by s1monw**
The minimum version comparison was always using the default version
sicne the comparison was flipped.

Closes #11474

### CODE REVIEW

**Comment by s1monw** [comment]
@rjernst @imotov can you review?

File: src/test/java/org/elasticsearch/rest/action/admin/indices/upgrade/UpgradeReallyOldIndexTest.java [hunk 1]
```diff
@@ -59,5 +62,6 @@ public void testUpgradeMixed_0_20_6_and_0_90_6() throws Exception {
 
         // We succeeded in upgrading only the ancient segments but leaving the "merely old" ones untouched:
         assertTrue(UpgradeTest.hasOldButNotAncientSegments(client(), indexName));
+        assertEquals(Version.CURRENT.luceneVersion.toString(), client().admin().indices().prepareGetSettings(indexName).get().getSetting(indexName, IndexMetaData.SETTING_VERSION_MINIMUM_COMPATIBLE));
     }
```
Comment (rmuir) [inline src/test/java/org/elasticsearch/rest/action/admin/indices/upgrade/UpgradeReallyOldIndexTest.java]: I'm confused about this assert. especially given the comments above it. If this minimum version is a lucene version, should it not be the oldest lucene version? In this case the ancient segments will be upgraded, but the "merely old" ones will still be there, so I can't see it being CURRENT.

File: src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 2]
```diff
@@ -734,9 +735,9 @@ public void optimize(OptimizeRequest optimize) throws ElasticsearchException {
     }
 
     public org.apache.lucene.util.Version minimumCompatibleVersion() {
-        org.apache.lucene.util.Version luceneVersion = org.apache.lucene.util.Version.LUCENE_3_6;
+        org.apache.lucene.util.Version luceneVersion = Version.indexCreated(indexSettings).luceneVersion;
         for(Segment segment : engine().segments()) {
-            if (luceneVersion.onOrAfter(segment.getVersion())) {
+            if (segment.getVersion().onOrAfter(luceneVersion)) {
                 luceneVersion = segment.getVersion();
             }
```
Comment (rmuir) [inline src/main/java/org/elasticsearch/index/shard/IndexShard.java]: What happens if the index is empty and just a commit point?

**Comment by rmuir** [comment]
I added some questions. One bigger question is: I don't like the hoops we are jumping through here. I also don't like the hoops lucene jumps through just to deliver the correct exception. Maybe lucene should store the minimum version inside the segments_N when we commit? If its an empty commit, its still populated with that version. This might simplify lucene itself on reading commits and make stuff like this easier for everyone.

**Comment by s1monw** [comment]
@rmuir I mixed something up you are right the test assertion didn't make sense

**Comment by rjernst** [comment]
+1

**Comment by rjernst** [comment]
Also +1 to storing min version in segments_N @rmuir

File: src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 3]
```diff
@@ -734,13 +735,13 @@ public void optimize(OptimizeRequest optimize) throws ElasticsearchException {
...
+        org.apache.lucene.util.Version luceneVersion = null;
         for(Segment segment : engine().segments()) {
-            if (luceneVersion.onOrAfter(segment.getVersion())) {
+            if (luceneVersion == null || luceneVersion.onOrAfter(segment.getVersion())) {
                 luceneVersion = segment.getVersion();
             }
         }
-        return luceneVersion;
+        return luceneVersion == null ?  Version.indexCreated(indexSettings).luceneVersion : luceneVersion;
     }
```
Comment (rmuir) [inline src/main/java/org/elasticsearch/index/shard/IndexShard.java]: OK but this indexCreated is an immutable thing in ES right? So this means a user can never upgrade an empty index?

Comment (s1monw) [inline src/main/java/org/elasticsearch/index/shard/IndexShard.java]: if there are no docs in the index it won't do anything here yes! in this case we should make this method more low level - I will fix that too

**Comment by mikemccand** [comment]
+1 to have Lucene track this in segments_N

**Comment by s1monw** [comment]
I added more are asserts, I think the empty index is a different issue and should be solved elsewhere it's pretty tricky to get the version the segmetns_N file was written. I think we are good to go

**Comment by imotov** [comment]
If this is an empty index, maybe we can just return `org.apache.lucene.util.Version.LUCENE_4_0_0` in 1.x and `org.apache.lucene.util.Version.LUCENE_5_0_0` in master since it doesn't have any segments anyway, so it's compatible with that, and if we will index any records afterwards, this is the version that we are going to get. Otherwise LGTM.

**Comment by s1monw** [comment]
> If this is an empty index, maybe we can just return org.apache.lucene.util.Version.LUCENE_4_0_0 in 1.x and org.apache.lucene.util.Version.LUCENE_5_0_0 in master since it doesn't have any segments anyway, so it's compatible with that, and if we will index any records afterwards, this is the version that we are going to get. Otherwise LGTM.

the problem is that if we try to open an empty index with a version taht doesn't support this segments_N format we get an exception we can't recover from so somehow we need to be able to upgrade it

**Comment by rmuir** [comment]
+1 Lets spin off the empty index separately into another PR? We can leave a TODO for that. I still feel strongly it should be fixed, but this moves things forward.

**Comment by imotov** [comment]
@s1monw we flush before running optimize and it overwrites the segments_N file even if there are no segments. So, shouldn't this make such index upgraded?
