### PR TITLE
Fix Snapshots Capturing Incomplete Datastreams

### LINKED ISSUE #58544: [SLM] Capturing global state in snapshot also captures data streams
**Elasticsearch version** (`bin/elasticsearch --version`): Snapshot of latest building artifact at time of issue creation `elasticsearch-oss-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**JVM version** (`java -version`): openjdk 12.0.2 2019-07-16

**OS version** (`uname -a` if on a Unix-like system): Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

When creating a snapshot policy users are given the option to include global state, by setting `include_global_state` to `true`. Creating a snapshot policy like:

```
PUT _slm/policy/test-k
{
  "name": "<test-k-{now/d}>",
  "schedule": "0 30 1 * * ?",
  "repository": "test",
  "config": {
    "indices": [
      ".k*"
    ],
    "include_global_state": true
  }
}
```

And running it yields a snapshot that also contains all the data streams metadata. Even though there are no data streams in the policy that match the patterns specified in `indices`.

Furthermore, when attempting to restore a snapshot created with the above policy the following error is reported:

```
[index_not_found_exception] no such index [.ds-test-data-stream-000001], with { index_uuid="_na_" & index=".ds-test-data-stream-000001" }
```

I would expect the policy snapshot to not include _any_ data about data streams (as it does not contain any of the backing indices either).

I would also expect the snapshot to be restore-able.

**Steps to reproduce**:

#### Create an index template

```
PUT /_index_template/test-data-stream
{
	"index_patterns": [
		"test-data-stream*"
	],
	"template": {
		"mappings": {
			"properties": {
				"@timestamp": {
					"type": "date"
				}
			}
		}
	},
	"data_stream": {
		"timestamp_field": "@timestamp"
	}
}
```

#### Create a data stream

```
PUT /_data_stream/test-data-stream
```

#### Then...

After the policy has created the snapshot, inspect the data concerning that snapshot, it should contain information about he data stream that was just created (which it should not).

#### Do the restore

I was using the Kibana UI to restore the snapshot and required that the global metadata be included in the snapshot

CC @martijnvg

### PR DESCRIPTION
**Pull request by original-brownbear**
Only snapshot datastreams that are recorded in `SnapshotInfo` and clean those
that aren't from the snapshotted metadata.
Do not restore all datastreams by default when restoring global metadata, use the same
mechanics used for indices here.

Closes #58544

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 1]
```diff
@@ -215,9 +215,12 @@ public void restoreSnapshot(final RestoreSnapshotRequest request, final ActionLi
                     dataStreams = new HashMap<>();
                 } else {
                     globalMetadata = repository.getSnapshotGlobalMetadata(snapshotId);
-                    dataStreams = globalMetadata.dataStreams();
-                    if (request.includeGlobalState() == false) {
-                        dataStreams.keySet().retainAll(requestedDataStreams);
+                    final Map<String, DataStream> dataStreamsInSnapshot = globalMetadata.dataStreams();
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:218]: 1. We gotta only restore those data streams actually matched by the restore request, even if we include global state.
2. We really shouldn't be mutating the deserialization result here. Come to think of it, we also shouldn't be deserializing the data streams to a mutable map, that invites all kinds of weird bugs. I'll open a PR to fix that.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -230,13 +230,8 @@ public ClusterState execute(ClusterState currentState) {
...
                     request.indicesOptions(), true, request.indices()));
 
-                Map<String, DataStream> allDataStreams = currentState.metadata().dataStreams();
-                List<String> dataStreams;
-                if (request.includeGlobalState()) {
-                    dataStreams = new ArrayList<>(allDataStreams.keySet());
-                } else {
-                    dataStreams = indexNameExpressionResolver.dataStreamNames(currentState, request.indicesOptions(), request.indices());
-                }
+                final List<String> dataStreams =
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:233]: Just like for indices we should respect the data streams constraints given by the request and not simply always snapshot all data-streams when doing a global snapshot.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 3]
```diff
@@ -354,9 +349,10 @@ private static ShardGenerations buildGenerations(SnapshotsInProgress.Entry snaps
     }
 
     private static Metadata metadataForSnapshot(SnapshotsInProgress.Entry snapshot, Metadata metadata) {
+        final Metadata.Builder builder;
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:352]: This change is a little ugly because now we filter data streams that aren't part of the snapshot from metadata but not indices. In fact, for indices we could (and probably should) do the same as the index metadata for indices that aren't recorded in `SnapshotInfo` is not touched by restores anyway and just pointless bytes.
For data streams we absolutely have to clean up the metadata though since when writing `SnapshotInfo`, we use the metadata contents to determine what data streams go into `SnapshotInfo`.
If we don't clean this up here, then data streams not initially request for snapshotting will be part of the snapshot for every snapshot that includes global metadata.

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:218]: > Come to think of it, we also shouldn't be deserializing the data streams to a mutable map, that invites all kinds of weird bugs.

I don't fully understand. Do you mean that the `DataStream` instances also need to be copied/cloned? So that the deserialization result cannot be altered at all?

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:218]: Aren't the `DataStream` instances immutable? If they aren't already I think we should make them immutable.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 3 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:352]: I don't see another way around this too. Although not a super clean change, but it is needed.

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:218]: In practice they are (all operations that modify a data stream create a new instance), however in order to make it stricter we should wrap the `indices` list always with `Collections.unmodifiableList(...)`.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks @martijnvg !
