### PR TITLE
Use NamedWritable to enable GeoBoundingBox serialisation

### LINKED ISSUE #99089: Failed Serialization of Scripted Geo fields
### Elasticsearch Version

8.7

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

In a multi-node cluster with multiple shards it is not possible to use scripted geo fields.
It fails with:
```
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "can not write type [class org.elasticsearch.common.geo.GeoBoundingBox]"
        }
```

### Steps to Reproduce

In a multi node cluster, create an index with more than 1 shard:
```
PUT /test-geo/
{
  "settings": { "number_of_shards": 2},
  "mappings": { "properties": { "geo_shape" : { "type": "geo_shape" }}}
}
```
Index a few shapes to it so that both shards are populated:
```
POST /test-geo/_doc/
{
  "geo_shape": "POLYGON((24.04725 59.942,24.04825 59.94125,24.04875 59.94125,24.04875 59.94175,24.048 59.9425,24.0475 59.94275,24.0465 59.94225,24.046 59.94225,24.04575 59.9425,24.04525 59.94225,24.04725 59.942))"
}
```

Then search with:
```
GET /test-geo/_search
{
  "script_fields": {
    "bbox": {
      "script": { "source": "doc['geo_shape'].getBoundingBox()" }
    }
  }
}
```

The non-local shard will fail.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by craigtaverner**
`BoundingBox` allows inter-node serialisation only within aggs results as components of aggregations that themselves use `NamedWritable`. However, if a `GeoBoundingBox` is added to search `hits`, serialisation fails as this type is not explicitly supported by `StreamOuput/StreamInput`. This was never noticed before because the only way to get a `BoundingBox` into the `hits` is through a painless script, something that appears to have not been used by customers, and is only tested internally using a single-node, single-shard yaml test, which does not touch this code path. We only found this issue due to recent effort to run all yaml tests in a serverless environment, which appears to always require serialisation from backend data nodes to a coordinator node.

Having said that, it is a surface API that could be used by users, and so should be fixed. While the missing type could be added explicitly, a much more flexible approach is to allow named classes to encapsulate their own serialization/deserialization logic. Here we use `NamedWritable` for that purpose.

Tasks:

- [x] Implement GenericNamedWriteable with version checking capabilities (based on VersionedNamedWriteable)
- [x] Manual testing with a multi-node cluster to verify this fixes #99089
- [x] Unit tests for version checking
- [x] Unit tests for serialization of GeoBoundingBox
- [x] Support CartesianBoundingBox by registering the named writable in SpatialPlugin

Fixes #99089

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java [hunk 1]
```diff
@@ -789,6 +789,7 @@ public Object readGenericValue() throws IOException {
             case 27 -> readOffsetTime();
             case 28 -> readDuration();
             case 29 -> readPeriod();
+            case 30 -> readNamedWriteable(NamedWriteable.class);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java:792]: This makes me a little uncomfortable, we should use a more precise class than just `NamedWriteable`. But I see why it's tricky here when we really don't know the context in which we're reading.

Could we introduce a marker type called `GenericNamedWriteable` and use that instead of `NamedWriteable`? That would help to protect against just accepting absolutely any `NamedWriteable` here.

Also I think this counts as a new transport version, we need to add a new version constant and throw an exception if the remote node version is too old rather than sending it something it won't understand.

Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java:792]: Great advice. I'm creating GenericNamedWriteable to extend VersionedNamedWriteable, which also provides the version checking.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java]: I recommend not using `VersionNamedWriteable`, it is kind of a bad idea (it's designed to just silently drop stuff when sending to older versions, and that's almost certainly a mistake).

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java]: Actually wait, I see, it could be useful here. But we do need to throw something (and ideally `assert false` too) if the sender is trying to send a value that the receiver won't understand.

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java [hunk 2]
```diff
@@ -782,6 +782,11 @@ public final void writeOptionalInstant(@Nullable Instant instant) throws IOExcep
             o.writeInt(period.getYears());
             o.writeInt(period.getMonths());
             o.writeInt(period.getDays());
+        }),
+        entry(GenericNamedWriteable.class, (o, v) -> {
+            o.writeByte((byte) 30);
+            GenericNamedWriteable w = (GenericNamedWriteable) v;
+            o.writeNamedWriteable(w);
         })
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: This is the extra validation I think we should have:

```suggestion
        entry(GenericNamedWriteable.class, (o, v) -> {
            final var genericNamedWriteable = (GenericNamedWriteable) v;
            final var minSupportedVersion = TransportVersion.max(
                TransportVersion.V_8_500_069,
                genericNamedWriteable.getMinimalSupportedVersion()
            );

            if (o.getTransportVersion().before(minSupportedVersion)) {
                final var message = Strings.format(
                    "[%s] requires minimal transport version [%s] and cannot be sent using transport version [%s]",
                    genericNamedWriteable,
                    minSupportedVersion,
                    o.getTransportVersion()
                );
                assert false : message;
                throw new IllegalStateException(message);
            }

            o.writeByte((byte) 30);
            o.writeNamedWriteable(genericNamedWriteable);
        })
```

File: server/src/main/java/org/elasticsearch/common/geo/BoundingBox.java [hunk 3]
```diff
@@ -194,4 +195,9 @@ public int hashCode() {
     public String toString() {
         return "BBOX (" + left() + ", " + right() + ", " + top() + ", " + bottom() + ")";
     }
+
+    @Override
+    public TransportVersion getMinimalSupportedVersion() {
+        return TransportVersion.V_8_500_069;
+    }
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/geo/BoundingBox.java:202]: I think it'd be better to have this in the concrete subclasses. That way if we add another one in future we won't forget to set this to the correct value.

Also it (and the `getWriteableName` implementations) probably should to be `final` to make sure we don't accidentally add further subclasses without thinking about the consequences in this area..

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 2 above)
Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: That code looks good, but does it really do anything different to https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/io/stream/VersionCheckingStreamOutput.java#L64? That code should be called already, inside the call to `writeNamedWritable`, so the check already exists, as far as I can tell.

Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: What I would like would be compatibility checks that verify that the exception is indeed thrown when we have mix-clusters. I wrote some tests like this before (in other work), but they were flaky (throwing the expected exception 99% of the time, not 100%, which was odd). I can try again.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: `VersionCheckingStreamOutput` doesn't consider it a bug to try and send an unknown writable, it just throws an IAE which maps onto a `400 Bad Request` and isn't logged. I think that's unduly lenient (although I see why checking this properly is tricky in a cross-cluster situation) and I'd rather we were stricter where possible, asserting that this doesn't happen and throwing an ISE if ever it does.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: > What I would like would be compatibility checks that verify that the exception is indeed thrown when we have mix-clusters.

I think a unit test is enough for this. We shouldn't even be trying to send unknown stuff over the wire ideally, hence why I think we should assert that we don't. Instead I'd rather that we looked at `org.elasticsearch.cluster.ClusterState#getMinTransportVersion` and avoided even creating the problematic object until all nodes can understand it.

Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: I'm thinking, if we have a mixed cluster, and there is a query involving a new feature that requires sending something new over the wire, that only some of the cluster understands, the consequence is:

* If the sender is an old version, it will not even get to this point because the new feature is not understood causing an exception in the feature itself (eg. in my case the painless script will fail with a painless exception).
* If the sender is new, but the receiver is old, then the sender serialises type=30, and the receiver throws `IOException("Can't read unknown type [" + type + "]")` in `StreamInput.readGenericValue`.

So, as far as I can tell your suggestion is that instead of the receiver throwing this exception, we have a sender that detects the receiver is old and throws an exception before sending, which moves the error to a different node in the cluster. Is this a big improvement?

In fact there are three scenarios:

* If we do no checking of versions at all (ie. my initial code) we get the behaviour described above
* If we check with VersionedNamedWritable (ie. my current code) we get an exception in the sender if the VersionedNamedWritable version is later than the senders TransportVersion which only considers local node state, so does not care if the remote node has an older version
* We check the remote transport version also, and throw an exception there. Looking at your code, it does not do this but seems to consider local transport version only, so very similar to the current behaviour. Perhaps your last suggestion of using `ClusterState#getMinTransportVersion` is the way to do this? But again, the consequence is only to move the exception to a different node in the cluster.

Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: I've done a little more digging and it looks like VersionedNamedWritable checks only occur for CCS, way too narrow a scope for our needs, so it is clear that I do need to write the check you have suggested. I'll go for that now.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:790]: We should forbid the use of any features that the whole cluster does not understand (which is why I think we should be looking at `ClusterState#getMinTransportVersion`). At least, that's [the documented behaviour](https://www.elastic.co/guide/en/elastic-stack/8.9/upgrading-elasticsearch.html#rolling-upgrades). Then we should consider it a bug (and `assert false`) if ever we get into a position where we're trying to send a message that the remote won't understand.

> Looking at your code, it does not do this but seems to consider local transport version only

No, it's looking at `StreamOutput#getTransportVersion` which is a transport version compatible with both sender and receiver.

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java [hunk 4]
```diff
@@ -782,6 +783,27 @@ public final void writeOptionalInstant(@Nullable Instant instant) throws IOExcep
             o.writeInt(period.getYears());
             o.writeInt(period.getMonths());
             o.writeInt(period.getDays());
+        }),
+        entry(GenericNamedWriteable.class, (o, v) -> {
+            final var genericNamedWriteable = (GenericNamedWriteable) v;
+            final var minSupportedVersion = TransportVersion.max(
```
Comment (craigtaverner) [inline server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:789]: This will always return the value of `genericNamedWriteable.getMinimalSupportedVersion()` since the concept of `GenericNamedWritable` was only introduced at this version.

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java [hunk 5]
```diff
@@ -782,6 +783,27 @@ public final void writeOptionalInstant(@Nullable Instant instant) throws IOExcep
...
+            );
+
+            if (o.getTransportVersion().before(minSupportedVersion)) {
+                final var message = Strings.format(
+                    "[%s] requires minimal transport version [%s] and cannot be sent using transport version [%s]",
+                    genericNamedWriteable,
+                    minSupportedVersion,
+                    o.getTransportVersion()
+                );
+                assert false : message;
```
Comment (craigtaverner) [inline server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:801]: These asserts seem to cause integration tests to fail in more opaque ways, with the test code receiving less information about the failure. Is this generally a good idea? Is the advantage that we fail faster, and so avoid being mislead by later errors?

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 4 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:789]: That's true, as long `getMinimalSupportedVersion()` is implemented correctly and not (say) copied from one of the implementations that returns `TransportVersion.MINIMUM_COMPATIBLE`. However BwC serialization is fairly subtle, and bugs in this area are just awful, so I'd like the extra check.

(We could also reasonably assert that `genericNamedWriteable.getMinimalSupportedVersion().onOrAfter(V_8_500_069)`)

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:801]: We definitely want to fail here in tests, and simply throwing an exception won't necessarily do that because exceptions can be caught. It's unfortunate that we have less context to share here, although I would expect these things to be fairly easy to reproduce.

File: server/src/main/java/org/elasticsearch/common/geo/BoundingBox.java (hunk 3 above)
Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/geo/BoundingBox.java:202]: Done

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 4 above)
Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java]: I've added the assert now

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 5 above)
Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:800]: At least here we assert with the same message. The test failure I debugged recently failed without the message, hiding the reason for failure, making it much harder to track initially.

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 2 above)
Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java]: I've investigated further and figured out why I misunderstood this. I did not see the uses of `setTransportVersion`, which allows for the behaviour you describe.

File: server/src/main/java/org/elasticsearch/TransportVersion.java [hunk 6]
```diff
@@ -182,6 +182,8 @@ private static TransportVersion registerTransportVersion(int id, String uniqueId
     public static final TransportVersion V_8_500_067 = registerTransportVersion(8_500_067, "a7c86604-a917-4aff-9a1b-a4d44c3dbe02");
     public static final TransportVersion V_8_500_068 = registerTransportVersion(8_500_068, "2683c8b4-5372-4a6a-bb3a-d61aa679089a");
     public static final TransportVersion V_8_500_069 = registerTransportVersion(8_500_069, "5b804027-d8a0-421b-9970-1f53d766854b");
+    public static final TransportVersion V_8_500_070 = registerTransportVersion(8_500_070, "6BADC9CD-3C9D-4381-8BD9-B305CAA93F86");
+
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/TransportVersion.java:186]:
```suggestion
```

nit: no extra whitespace here please

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java [hunk 7]
```diff
@@ -760,6 +762,24 @@ public final void writeOptionalInstant(@Nullable Instant instant) throws IOExcep
             o.writeInt(period.getYears());
             o.writeInt(period.getMonths());
             o.writeInt(period.getDays());
+        }),
+        entry(GenericNamedWriteable.class, (o, v) -> {
+            // Note that we do not rely on the checks in VersionCheckingStreamOutput because that only applies to CCS
+            final var genericNamedWriteable = (GenericNamedWriteable) v;
+            TransportVersion minSupportedVersion = genericNamedWriteable.getMinimalSupportedVersion();
+            assert minSupportedVersion.onOrAfter(V_8_500_070) : "[GenericNamedWriteable] requires [" + V_8_500_070 + "]";
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:770]: Might be worth mentioning `minSupportedVersion` in the message too.

File: server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+        for (int runs = 0; runs < NUMBER_OF_TEST_RUNS; runs++) {
+            GenericNamedWriteable testInstance = createTestInstance();
+
+            // Test reading and writing with valid versions
+            GenericNamedWriteable deserializedInstance = copyInstance(testInstance, valid, valid);
+            assertEqualInstances(testInstance, deserializedInstance);
+
+            // Test writing fails with older version
+            try {
+                copyInstance(testInstance, older, valid);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java:105]: I think we should just verify that writing to an older stream fails, no need to make a `copyInstance` which tries to read it back again.

File: server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+            } catch (Throwable e) {
+                assertThat(
+                    "Writing with older TransportVersion",
+                    e.getMessage(),
+                    containsString("[GeoBoundingBox] requires minimal transport version")
+                );
+            }
+
+            // Test reading succeeds with older version (we do not cripple the reader)
+            deserializedInstance = copyInstance(testInstance, valid, older);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java:116]: I think this doesn't really make sense, we are always sure that reading and writing always use the same transport version, and the message we're creating isn't actually something an older node would be able to create.

**Review by DaveCTurner — COMMENTED** [review]
Looks great, just a few small comments.

File: server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java (hunk 7 above)
Comment (craigtaverner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:770]: Since this was in an assert that would only happen in tests, and therefor tracked by a developer who will easily follow the code, I favoured brevity (and a non-wrapping line) over detail.

The next line that does the real check for production code is much more informative (for both the user and any developer tracking a failure).

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java:770]: Makes sense, thanks.

File: server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java (hunk 9 above)
Comment (craigtaverner) [reply server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java:116]: OK. I've simplified this failure test to only test the failure case. The first part with (valid,valid) was already tested in another test `testSerialization`, and the last part is unnecessary:

File: server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java (hunk 8 above)
Comment (craigtaverner) [reply server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java:105]: OK. After simplifying the test I replaced this with just the writing code.

File: server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java [hunk 10]
```diff
@@ -0,0 +1,113 @@
...
+    }
+
+    private GenericNamedWriteable readGenericValue(StreamInput in) throws IOException {
+        Object obj = in.readGenericValue();
+        if (obj instanceof GenericNamedWriteable result) {
+            return result;
+        }
+        throw new IllegalStateException("Read result of wrong type: " + obj.getClass().getSimpleName());
+    }
+
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java:82]: This is no longer needed, we can just use the `copyInstance` implementation in the subclass.

```suggestion
```

(also needs a spotless run to clean up imports)

**Review by DaveCTurner — APPROVED** [review]
LGTM (left a comment about some now-unnecessary test code tho)

File: server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java (hunk 10 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/search/geo/GeoBoundsGenericWriteableTests.java]: acked, I think I can see a way to make this a little less special, but let's merge this and I'll follow up with a suggestion.
