### PR TITLE
ESQL: Fix missing refs due to pruning renamed grouping columns

### LINKED ISSUE #107083: DROP of EVAL planning issues
```js
PUT /test/_doc/1?refresh
{
    "k": "a",
    "v": 1
}
```

```js
PUT /test/_doc/2?refresh
{
    "k": "a",
    "v": 2
}
```

```js
POST /_query?error_trace
{
    "query": "FROM test | EVAL k1 = k | STATS avg(v) BY k, k1 | DROP k1"
}
```

```
"reason": "Found 1 problem\nline 1:27: Plan [Aggregate[[k{f}#199, k1{r}#192],[SUM(v{f}#198) AS $$SUM$avg(v)$0, COUNT(v{f}#198) AS $$COUNT$avg(v)$1, k{f}#199]]] optimized incorrectly due to missing references [k1{r}#192]",
```

And  without aggs

```js
POST /_query?error_trace
{
    "query": "FROM test | EVAL k1 = k | STATS BY k, k1 | DROP k1"
}
```

```
"stack_trace": "java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.xpack.esql.planner.Layout$ChannelSet.nameIds()\" because the return value of 
 \"java.util.List.get(int)\" is null
\tat org.elasticsearch.xpack.esql.planner.ExchangeLayout.get(ExchangeLayout.java:36)
\tat org.elasticsearch.xpack.esql.planner.AbstractPhysicalOperationProviders.groupingPhysicalOperation(AbstractPhysicalOperationProviders.java:122)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planAggregation(LocalExecutionPlanner.java:234)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:182)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planProject(LocalExecutionPlanner.java:508)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:196)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLimit(LocalExecutionPlanner.java:548)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:200)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:267)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:224)
\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:167)
\tat org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:441)
\tat org.elasticsearch.xpack.esql.plugin.ComputeService.execute(
        ComputeService.java:208)
\tat org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$innerExecute$4(TransportEsqlQueryAction.java:166)
```

### LINKED ISSUE #107166: ESQL: Prune duplicate groups hidden behind aliases
### Description

`EVAL x = field | STATS by field, x` can be optimized to `STATS field as X by field`

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/107083, more specifically [this remaining case](https://github.com/elastic/elasticsearch/issues/107083#issuecomment-2047865621).
Close https://github.com/elastic/elasticsearch/issues/107166.

In some cases, `CombineProjections` prunes grouping columns if the column was only renamed. E.g.

```
...
| EVAL x = y, foo = bar
| STATS min(foo) BY x

// This is optimized to something equivalent to:

...
// EVAL pruned as it only renames vars
STATS `min(foo)` = min(bar) BY x
```

Notice how the `x` is still in the groupings. Confusingly, the query still got executed correctly in most cases.

This PR propagates the renaming `x = y` into the groupings. To be correct, we have to avoid propagating the same reference attribute twice into the grouping (otherwise layout errors occur), so this PR also prunes duplicate groupings:

```
...
| EVAL x = y, z = y
| STATS BY x, z

// This becomes something equivalent to

...
| STATS BY x = y, z = y
// and the corresponding Aggregate plan only has y in its groupings,
// and `x = y` and `z = y` in its aggregates.
```

### CODE REVIEW

**Comment by alex-spies** [comment]
@elasticmachine update branch

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 1]
```diff
@@ -482,6 +487,27 @@ private static List<NamedExpression> combineProjections(
...
+                // record the alias
+                aliases.put(ne.toAttribute(), Alias.unwrap(ne));
+            }
+
+            // Replace any matching attribute directly with the aliased attribute from the projection.
+            AttributeSet replaced = new AttributeSet();
+            for (Expression expr : upperGroupings) {
+                // All substitutions happen before; groupings must be attributes at this point.
+                Attribute attr = (Attribute) expr;
+                replaced.add((Attribute) aliases.resolve(attr, attr));
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:506]: This will lead to a CCE - if there's always an attribute inside the alias (what about c = a + 1), make the aliases be a `AttributeMap<Attribute>`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 2]
```diff
@@ -482,6 +487,27 @@ private static List<NamedExpression> combineProjections(
...
+            }
+            return replaced.stream().map(attr -> (Expression) attr).toList();
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:508]: `new ArrayList<Expression>(replaced)`;

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 3]
```diff
@@ -482,6 +487,27 @@ private static List<NamedExpression> combineProjections(
             return replaced;
         }
 
+        private static List<Expression> combineUpperGroupingsAndLowerProjections(
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:490]: This method looks quite similar to combineProjections()  which is the reused inside projectAggregations().
Have you looked into reusing them on groupings?

**Review by costin — COMMENTED** [review]
Good catch.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:506]: This shouldn't cause CCE in practice, but I can use an `AttributeMap<Attribute>`. (Still need to cast the expressions under the projection's aliases to attributes, then.)

(I'd prefer not having to cast at all, but our Aggs/Projections don't adequately represent the fact that we don't have general expressions here, but attributes.)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:490]: I initially wanted to re-use this, but I need to make some assumptions (in the form of casting expressions) that are only true if the upper expressions are groupings. I can probably still combine these, but that might become confusing to read.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 4]
```diff
@@ -419,7 +420,13 @@ protected LogicalPlan rule(UnaryPlan plan) {
             // Agg with underlying Project (group by on sub-queries)
             if (plan instanceof Aggregate a) {
                 if (child instanceof Project p) {
-                    plan = new Aggregate(a.source(), p.child(), a.groupings(), combineProjections(a.aggregates(), p.projections()));
+                    plan = new Aggregate(
+                        a.source(),
+                        p.child(),
+                        // After substitutions groupings can only contain attributes.
+                        combineUpperGroupingsAndLowerProjections((List<? extends Attribute>) (List<?>) a.groupings(), p.projections()),
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:427]:
```suggestion
                        combineUpperGroupingsAndLowerProjections((List<? extends Attribute>) a.groupings(), p.projections()),
```

**Review by bpintea — APPROVED** [review]
Lgtm.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 4 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:427]: Ah, sorry, this suggestion is wrong. 
Why the double cast though and not call the combining function with a `List<Expression>` and cast downstream, since groupings are expected as attributes? Same cast as for the projection list.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 5]
```diff
@@ -419,7 +420,13 @@ protected LogicalPlan rule(UnaryPlan plan) {
...
+                        combineProjections(a.aggregates(), p.projections())
+                    );
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:429]: If we really expect Attributes at this point, let's make this intention clear: I've changed the ugly double casting plus made the comment more clear; also, a proper exception is thrown if our expectation is not met (vs. letting a CCE being thrown in case the list of groupings is not a list of Attributes).

```suggestion
                    var groupings = a.groupings();
                    List<Attribute> groupingAttrs = new ArrayList<>(a.groupings().size());
                    for (Expression grouping : groupings) {
                        if (grouping instanceof Attribute attribute) {
                            groupingAttrs.add(attribute);
                        } else {
                            // After "Substitutions" batch, the groupings of an Aggregate can only be attributes
                            throw new EsqlIllegalArgumentException("Expected an Attribute, got {}", grouping);
                        }
                    }
                    plan = new Aggregate(
                        a.source(),
                        p.child(),
                        combineUpperGroupingsAndLowerProjections(groupingAttrs, p.projections()),
                        combineProjections(a.aggregates(), p.projections())
                    );
```

**Review by astefan — APPROVED** [review]
Left a suggestion. Otherwise LGTM

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 6]
```diff
@@ -419,7 +420,13 @@ protected LogicalPlan rule(UnaryPlan plan) {
             // Agg with underlying Project (group by on sub-queries)
             if (plan instanceof Aggregate a) {
                 if (child instanceof Project p) {
-                    plan = new Aggregate(a.source(), p.child(), a.groupings(), combineProjections(a.aggregates(), p.projections()));
+                    plan = new Aggregate(
+                        a.source(),
+                        p.child(),
+                        // After substitutions groupings can only contain attributes.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:426]: I'll make this comment more precise.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 5 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:429]: Yeah, that's better, thank you!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 4 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java]: Nevermind, explicitly casting each grouping now per Andrei's suggestion.

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.13|[](https://github.com/elastic/elasticsearch/pull/107599)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
