### PR TITLE
[ML] Fix loss of context in the inference API for streaming APIs

### LINKED ISSUE #119000: [ML] [Inference API] The `_stream` API doesn't consistently return the elastic product header
### Elasticsearch Version

8.16.0 and onward

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

The api inconsistently returns the `X-elastic-product` header in the response.

The API should always return the header.

### Steps to Reproduce

Create an openai endpoint
```
PUT http://localhost:9200/_inference/test
{
    "service": "openai",
    "task_type": "completion",
    "service_settings": {
        "api_key": "<api key>",
        "model_id": "gpt-4o"
    }
}
```

Make a request
```
POST http://localhost:9200/_inference/completion/test/_stream
{
    "input": "What's the best American food?"
}
```

Observe that the header isn't always returned.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jonathan-buttner**
This PR fixes an issue where the `X-elastic-produce` header was not being returned sometimes. I believe this was a concurrency issue in someway because when testing using the `_stream` API the header is usually _not_ returned. But when testing with the `_unified` API the header _is_ usually returned.

I believe the issue relates to the fact that the rest handler's listener doesn't immediately return the response. The `onResponse` method creates a new listener that is called sometime later (maybe on a different thread?).

One thing I noticed is that the headers are only returned once which is why I only preserve the context on the first action listener.

TODO

- Adds some unit tests ✅ (but they don't seem to help)
  - Find some other way to test this
- Pass in a `SetOnce` instead of the `ThreadPool` to avoid a potential issue where the `createComponents()` call gets moved after the route retrieval. ✅ 

Fixes https://github.com/elastic/elasticsearch/issues/119000

### CODE REVIEW

File: x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/InferenceBaseRestTest.java [hunk 1]
```diff
@@ -341,31 +342,44 @@ protected Map<String, Object> infer(String modelId, List<String> input) throws I
...
 
-    private Deque<ServerSentEvent> execAsyncCall(Request request) throws Exception {
+    private Deque<ServerSentEvent> execAsyncCall(Request request, @Nullable Consumer<Response> responseConsumerCallback) throws Exception {
         var responseConsumer = new AsyncInferenceResponseConsumer();
         request.setOptions(RequestOptions.DEFAULT.toBuilder().setHttpAsyncResponseConsumerFactory(() -> responseConsumer).build());
         var latch = new CountDownLatch(1);
         client().performRequestAsync(request, new ResponseListener() {
             @Override
             public void onSuccess(Response response) {
+                if (responseConsumerCallback != null) {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/InferenceBaseRestTest.java:380]: Adding a way to get the response so we can check the headers

File: x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/InferenceCrudIT.java [hunk 2]
```diff
@@ -469,7 +477,7 @@ public void testSupportedStream() throws Exception {
 
         var input = IntStream.range(1, 2 + randomInt(8)).mapToObj(i -> randomAlphanumericOfLength(5)).toList();
         try {
-            var events = streamInferOnMockService(modelId, TaskType.COMPLETION, input);
+            var events = streamInferOnMockService(modelId, TaskType.COMPLETION, input, VALIDATE_ELASTIC_PRODUCT_HEADER_CONSUMER);
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/InferenceCrudIT.java:480]: Unfortunately, even if I remove my change this test still passes. I opted for keeping these tests just in case something really goes wrong in the future but they wouldn't have caught the original issue 😞

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rest/ServerSentEventsRestActionListener.java [hunk 3]
```diff
@@ -115,6 +121,12 @@ private void initializeStream(InferenceAction.Response response) {
                 )
             );
         });
+
+        nextBodyPartListener = ContextPreservingActionListener.wrapPreservingContext(
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rest/ServerSentEventsRestActionListener.java:125]: When I manually test this, it fixes the issue. I always get the header back as expected. Without the fix the `_stream` api usually does not return the header. I believe this is because we are create a new listener that maybe gets executed with a different thread context. I think if we responded in the `onResponse` implementation of this class it'd probably avoid the issue. But that's not how this was designed so I'm keeping the structure as it was.

**Review by maxhniebergall — APPROVED** [review]
LGTM. Thanks for finding this fix for this!

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by jonathan-buttner** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/119218)|
|✅|8.17|[](https://github.com/elastic/elasticsearch/pull/119222)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/119223)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
