### PR TITLE
Audited API Key authentication might not have a realm name

### LINKED ISSUE #59425: [CI] Auditing log fails for API key realm name during BWC with version prior to v7.5
The failed test `UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/120_api_key_auth/Test API key authentication will work in a mixed cluster}`.

ApiKey realm name is not available in Authentication metadata till [v7.5](https://github.com/elastic/elasticsearch/commit/7b6246ec670040e8e5dfef05b33bb2b39f8a9357). Hence auditing log fails to [retrieve it](https://github.com/elastic/elasticsearch/blob/7.x/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java#L464) for older versions. 

The failed test has been configured to run only for v7.5 and up. Once this issue is fixed, it can be renabled for older versions by removing [these two lines](https://github.com/elastic/elasticsearch/blob/master/x-pack/qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/120_api_key_auth.yml#L6-L7).

Build scan: https://gradle-enterprise.elastic.co/s/zyiwyg5feg74a

### PR DESCRIPTION
**Pull request by albertzaharovits**
The `Authentication` object that gets built following an API Key authentication contains the realm name of the owner user that created the key (which is audited), but the specific field used for storing that changed in https://github.com/elastic/elasticsearch/pull/51305 .

This PR makes it so that auditing tolerates an "unfound" realm name (so it doesn't throw an NPE), because the owner realm name is not under the expected field.

Closes https://github.com/elastic/elasticsearch/issues/59425

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java [hunk 1]
```diff
@@ -819,9 +833,13 @@ LogEntryBuilder withAuthentication(Authentication authentication) {
...
                 logEntry.with(API_KEY_ID_FIELD_NAME, (String) authentication.getMetadata().get(ApiKeyService.API_KEY_ID_KEY))
-                        .with(API_KEY_NAME_FIELD_NAME, (String) authentication.getMetadata().get(ApiKeyService.API_KEY_NAME_KEY))
-                        .with(PRINCIPAL_REALM_FIELD_NAME,
-                                (String) authentication.getMetadata().get(ApiKeyService.API_KEY_CREATOR_REALM_NAME));
+                        .with(API_KEY_NAME_FIELD_NAME, (String) authentication.getMetadata().get(ApiKeyService.API_KEY_NAME_KEY));
+                String creatorRealmName = (String) authentication.getMetadata().get(ApiKeyService.API_KEY_CREATOR_REALM_NAME);
+                if (creatorRealmName != null) {
+                    // can be null for API keys created before version 7.7
+                    logEntry.with(PRINCIPAL_REALM_FIELD_NAME,
+                            (String) authentication.getMetadata().get(ApiKeyService.API_KEY_CREATOR_REALM_NAME));
```
Comment (ywangd) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java:841]: This can just be 
```java
logEntry.with(PRINCIPAL_REALM_FIELD_NAME, creatorRealmName);
```

**Review by ywangd — APPROVED** [review]
LGTM.

I noticed that the `realm` info is added to authentication metadata since v7.4 (#45897). But you are right, the field name is changed in v7.7 with my PR (#51305). So API keys created before v7.7 will have empty string as realm name in audit logs. We could go extra mileage to make it work with v7.4. But I don't think it's all that necessary. This is one bwc that we can afford to not have. Thanks!

**Comment by ywangd** [comment]
One more thing: Could you please re-enable the muted test by deleting these [two lines](https://github.com/elastic/elasticsearch/blob/7.x/x-pack/qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/120_api_key_auth.yml#L6-L7) from the yaml test.

**Comment by albertzaharovits** [comment]
> Could you please re-enable the muted test by deleting these two lines from the yaml test as part of this PR?

My reflex would've been to push a separate PR to toggle tests back after this PR is merged and backported, but your suggestion would work just as well.

**Comment by ywangd** [comment]
> > Could you please re-enable the muted test by deleting these two lines from the yaml test as part of this PR?
> 
> 
> 
> My reflex would've been to push a separate PR to toggle tests back after this PR is merged and backported, but your suggestion would work just as well.

Sorry I forgot this PR is for master and the test is for 7.x. The one for master is not enabled because I was waiting for the 7.x backport. In this case, sorry please ignore my previous suggestion and I will take care of enabling the tests for both master and 7.x.

**Comment by ywangd** [comment]
I see that you have already enabled the test. It works this way as well. Sorry I was confused initially.
