### PR TITLE
[ML] fixing test related to #40963

### LINKED ISSUE #40963: CI Failure: DataFrameGetAndGetStatsIT testGetPersistedStatsWithoutTask
```
Expected: a value greater than <0>
     but: <0> was equal to <0>
	at __randomizedtesting.SeedInfo.seed([565E9E23D6E0611E:F4F08DAE1E49B812]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT.testGetPersistedStatsWithoutTask(DataFrameGetAndGetStatsIT.java:133)
```

Reproduce: 
```
./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner \
  -Dtests.seed=565E9E23D6E0611E \
  -Dtests.class=org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT \
  -Dtests.method="testGetPersistedStatsWithoutTask" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-AE \
  -Dtests.timezone=Europe/Bratislava \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/95/console

### PR DESCRIPTION
**Pull request by benwtrent**
This removes the possible zero value check of `search_time_in_ms`. I have seen this before where the search time is actually recorded as zero. This is OK for this test as we really only care about there being valid statistics. The remain checks are enough to achieve this. 

closes #40963

### CODE REVIEW

File: x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameGetAndGetStatsIT.java [hunk 1]
```diff
@@ -131,7 +130,6 @@ public void testGetPersistedStatsWithoutTask() throws Exception {
         for (Map<String, Object> transformStats : transformsStats) {
             Map<String, Object> stat = (Map<String, Object>)transformStats.get("stats");
             assertThat(((Integer)stat.get("documents_processed")), greaterThan(0));
-            assertThat(((Integer)stat.get("search_time_in_ms")), greaterThan(0));
```
Comment (davidkyle) [inline x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameGetAndGetStatsIT.java]: or use `greaterThanOrEqualTo`

Comment (benwtrent) [reply x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameGetAndGetStatsIT.java]: @davidkyle I could, but that does not add anything :(. A `0` value is also the default value for when there aren't stats recorded

Comment (davidkyle) [reply x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameGetAndGetStatsIT.java]: it proves the field is present... but that should be covered in other tests

**Review by davidkyle — APPROVED** [review]
LGTM
