### PR TITLE
Remove early phase failure in batched

### LINKED ISSUE #134151: [Search] Exceptions in datanodes leading to assertFirstRun() failures
While debugging CircuitBreakingExceptions in `_search` with 3 or more nodes, I found that sometimesit throws an assertion error. The first call to `assertFirstRun()` was:

<details>
<summary>First exception stacktrace</summary>

```
org.elasticsearch.ElasticsearchException: executed already
	at org.elasticsearch.action.ActionListener$3.assertFirstRun(ActionListener.java:403)
	at org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:422)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:647)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:624)
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.onPhaseFailure(SearchQueryThenFetchAsyncAction.java:81)
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$1.handleException(SearchQueryThenFetchAsyncAction.java:536)
	at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1731)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1511)
	at org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:510)
	at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:497)
	at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:488)
	at org.elasticsearch.transport.InboundHandler.executeResponseHandler(InboundHandler.java:164)
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:134)
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:830)
	at org.elasticsearch.transport.InboundPipeline.forwardFragment(InboundPipeline.java:116)
	at org.elasticsearch.transport.InboundPipeline.lambda$doHandleBytes$1(InboundPipeline.java:78)
	at org.elasticsearch.transport.InboundDecoder.finishMessage(InboundDecoder.java:144)
	at org.elasticsearch.transport.InboundDecoder.internalDecode(InboundDecoder.java:129)
	at org.elasticsearch.transport.InboundDecoder.decode(InboundDecoder.java:58)
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:79)
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	at org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:54)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4.NettyByteBufSizer.channelRead(NettyByteBufSizer.java:33)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:660)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1447)
```
</details>

The second call triggering the assertion had an identical stacktrace.

I reproduced this in main (a59c182f9f7e9d1bf3d6eecbc0e44f24ff91d053, when the issue was opened) with this test:

<details>
<summary>AggregationsCircuitBreakingIt.java</summary>

```java
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.aggregations.bucket;

import com.carrotsearch.randomizedtesting.annotations.Repeat;

import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.index.IndexRequestBuilder;
import org.elasticsearch.action.search.SearchPhaseExecutionException;
import org.elasticsearch.aggregations.AggregationIntegTestCase;
import org.elasticsearch.common.breaker.CircuitBreakingException;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.search.aggregations.bucket.composite.TermsValuesSourceBuilder;
import org.elasticsearch.test.ESIntegTestCase;
import org.elasticsearch.xcontent.XContentBuilder;
import org.elasticsearch.xcontent.XContentFactory;
import org.hamcrest.core.Every;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import java.util.stream.LongStream;

import static org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.REQUEST_CIRCUIT_BREAKER_LIMIT_SETTING;
import static org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.REQUEST_CIRCUIT_BREAKER_TYPE_SETTING;
import static org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.TOTAL_CIRCUIT_BREAKER_LIMIT_SETTING;
import static org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.USE_REAL_MEMORY_USAGE_SETTING;
import static org.elasticsearch.search.aggregations.AggregationBuilders.composite;
import static org.elasticsearch.search.aggregations.AggregationBuilders.topHits;
import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
import static org.hamcrest.Matchers.instanceOf;

@ESIntegTestCase.ClusterScope(numDataNodes = 3)
@Repeat(iterations = 10)
public class AggregationsCircuitBreakingIT extends AggregationIntegTestCase {
    @Override
    protected Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
        return Settings.builder()
            .put(super.nodeSettings(nodeOrdinal, otherSettings))
            .put(REQUEST_CIRCUIT_BREAKER_TYPE_SETTING.getKey(), "memory")
            .build();
    }

    private void createIndex() throws IOException {
        XContentBuilder mappingBuilder = XContentFactory.jsonBuilder();
        mappingBuilder.startObject();
        mappingBuilder.startObject("properties");
        {
            mappingBuilder.startObject("integer");
            mappingBuilder.field("type", "integer");
            mappingBuilder.endObject();
        }
        {
            mappingBuilder.startObject("long");
            mappingBuilder.field("type", "long");
            mappingBuilder.endObject();
        }

        mappingBuilder.endObject(); // properties
        mappingBuilder.endObject();

        assertAcked(
            prepareCreate("index").setSettings(Settings.builder().put("index.number_of_shards", randomIntBetween(1, 10)).build())
                .setMapping(mappingBuilder)
        );

        int minimumCombinations = 10_000_000; // To fill the 65k buckets in the composite agg, times the 100 top_hits count
        int docCount = randomIntBetween(100, 10000); // 100 at least to fill the top_hits agg
        int integerFieldMvCount = randomIntBetween(100, (int) Math.ceil((double) minimumCombinations / docCount));
        int longFieldMvCount = (int) Math.ceil((double) minimumCombinations / docCount / integerFieldMvCount);

        List<IndexRequestBuilder> docs = new ArrayList<>();
        for (int i = 0; i < docCount; i++) {
            XContentBuilder docSource = XContentFactory.jsonBuilder();
            docSource.startObject();
            final int docNumber = i;
            List<Integer> integerValues = IntStream.range(0, integerFieldMvCount).map(x -> docNumber + x * 100).boxed().toList();
            List<Long> longValues = LongStream.range(0, longFieldMvCount).map(x -> docNumber + x * 100).boxed().toList();
            docSource.field("integer", integerValues);
            docSource.field("long", longValues);
            docSource.endObject();

            docs.add(prepareIndex("index").setOpType(DocWriteRequest.OpType.CREATE).setSource(docSource));
        }
        indexRandom(true, false, docs);
    }

    public void testCBTrippingOnBigComposite() throws IOException {
        createIndex();

        updateClusterSettings(
            Settings.builder()
                .put(TOTAL_CIRCUIT_BREAKER_LIMIT_SETTING.getKey(), "100MB")
                .put(REQUEST_CIRCUIT_BREAKER_LIMIT_SETTING.getKey(), "10MB")
                .put(USE_REAL_MEMORY_USAGE_SETTING.getKey(), true)
        );

        var searchRequestBuilder = prepareSearch("index").setSize(0)
            .addAggregation(
                composite(
                    "composite",
                    List.of(new TermsValuesSourceBuilder("integer").field("integer"), new TermsValuesSourceBuilder("long").field("long"))
                ).size(65536).subAggregation(
                    topHits("top_hits").size(100)
                )
            );

        try {
            searchRequestBuilder.get();

            fail("Expected the breaker to trip");
        } catch (SearchPhaseExecutionException e) {
            assertThat(List.of(e.guessRootCauses()), Every.everyItem(instanceOf(CircuitBreakingException.class)));
        } finally {
            updateClusterSettings(
                Settings.builder()
                    .putNull(TOTAL_CIRCUIT_BREAKER_LIMIT_SETTING.getKey())
                    .putNull(REQUEST_CIRCUIT_BREAKER_LIMIT_SETTING.getKey())
                    .putNull(USE_REAL_MEMORY_USAGE_SETTING.getKey())
            );
        }
    }
}

```
</details>

### PR DESCRIPTION
**Pull request by benchaplin**
Resolves https://github.com/elastic/elasticsearch/issues/134151, https://github.com/elastic/elasticsearch/issues/130821.

## Background

A bug was introduced by https://github.com/elastic/elasticsearch/pull/121885 due to the following code, which handles batched query exceptions due to a batched partial reduction failure: https://github.com/elastic/elasticsearch/blob/bd356491b1e32b19993ed6cd70cc2415df1253ce/server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java#L525-L544

Raising a phase failure in this way leads to a couple issues:
1. It can be called more than once (as seen in #134151). 
2. The subsequent freeing of contexts can miss concurrent in-flight queries, resulting in open contexts after the failure (as seen in #130821).

## Solution

Problem 1 could be resolved with a simple flag, as proposed in https://github.com/elastic/elasticsearch/pull/131085. Problem 2 could be resolved with some careful use of the same flag to clean contexts upon receiving stale query results. However, in the interest of stability, I propose a solution that more closely resembles how a reduction failure is handled by a non-batched query phase. In non-batched, a reduction failure is held in the QueryPhaseResultConsumer until shard fanout is complete. Only later, during final reduction at the beginning of the fetch phase, do we fail the search. 

Fast failure + proper task cancellation are worthy goals for the future. I am tracking these as follow-up improvements for after the release of batched query execution.

This PR:
1. Alters a batched query request to respond with shard results in the case of a reduction failure on the data node (the failure is now conditionally included in the NodeQueryResponse).
2. Removes the early phase failure on the coord node. The coord's QueryPhaseResultConsumer will hold onto the failure and fail eventually during the fetch phase, same as non-batched.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 1]
```diff
@@ -225,20 +223,33 @@ public static final class NodeQueryResponse extends TransportResponse {
...
         private final Object[] results;
+        private final Exception reductionFailure;
         private final SearchPhaseController.TopDocsStats topDocsStats;
         private final QueryPhaseResultConsumer.MergeResult mergeResult;
 
         public NodeQueryResponse(StreamInput in) throws IOException {
             this.results = in.readArray(i -> i.readBoolean() ? new QuerySearchResult(i) : i.readException(), Object[]::new);
-            this.mergeResult = QueryPhaseResultConsumer.MergeResult.readFrom(in);
-            this.topDocsStats = SearchPhaseController.TopDocsStats.readFrom(in);
+            boolean hasReductionFailure = in.readBoolean();
```
Comment (chrisparrinello) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java]: Since we're changing the shape of this message, do we need to create a new transport version or is that taken care of for us?

Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java]: Yes I believe I do, once I learn how 😂

**Review by chrisparrinello — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 2]
```diff
@@ -801,68 +815,80 @@ void onShardDone() {
...
+                releaseAllResultsContexts();
+                channelListener.onFailure(e);
             }
             ActionListener.respondAndRelease(
                 channelListener,
                 new BytesTransportResponse(out.moveToBytesReference(), out.getTransportVersion())
             );
         }
 
+        private void writeSuccessfulResponse(RecyclerBytesStreamOutput out) throws IOException {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:891]: Is it necessary to refactor this serialization code? Moving it around makes it more difficult to eye ball it somehow.

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 3]
```diff
@@ -229,8 +232,7 @@ public static final class NodeQueryResponse extends TransportResponse {
 
         public NodeQueryResponse(StreamInput in) throws IOException {
             this.results = in.readArray(i -> i.readBoolean() ? new QuerySearchResult(i) : i.readException(), Object[]::new);
-            boolean hasReductionFailure = in.readBoolean();
-            if (hasReductionFailure) {
+            if (in.getTransportVersion().supports(BATCHED_RESPONSE_MIGHT_INCLUDE_REDUCTION_FAILURE) && in.readBoolean()) {
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:238]: is this bwc? we will **not** read the boolean if we're reading from an old version, but the old version would've written the boolean on the wire
I think we should always read the boolean

Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:238]: I believe this is correct - the old version doesn't write a boolean.
The old version writes: results, mergeResult, topDocsStats.
The new version writes: results, boolean, boolean ? reductionFailure : (mergeResults, topDocsStats).

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:238]: Ah you're right, sorry for the noise (was reviewing this commit and thought the boolean was there before this change :) https://github.com/elastic/elasticsearch/pull/136889/commits/7540aa964b9a47c6afed6e7e4639e4ce88be1b37 )

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:891]: disregard this previous comment. I understand why you did things the way you did. It's fine as-is. As for the review, I simply trust that the successful writing is a plain copy of the previous code we had, with no changes.

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 4]
```diff
@@ -817,13 +862,98 @@ void onShardDone() {
...
+                var result = queryPhaseResultConsumer.results.get(i);
+                if (result == null) {
+                    NodeQueryResponse.writePerShardException(out, failures.remove(i));
+                } else {
+                    NodeQueryResponse.writePerShardResult(out, result);
+                }
+            }
+            out.writeBoolean(true); // does have a reduction failure
+            out.writeException(reductionFailure);
+            releaseAllResultsContexts();
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:943]: should this be in a finally block ?

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 5]
```diff
@@ -817,13 +862,98 @@ void onShardDone() {
...
+                    // free context id and remove it from the result right away in case we don't need it anymore
+                    maybeFreeContext(result, relevantShardIndices, namedWriteableRegistry);
+                    NodeQueryResponse.writePerShardResult(out, result);
+                }
+            }
+            out.writeBoolean(false); // does not have a reduction failure
+            NodeQueryResponse.writeMergeResult(out, mergeResult, queryPhaseResultConsumer.topDocsStats);
+        }
+
+        private void writeReductionFailureResponse(RecyclerBytesStreamOutput out, Exception reductionFailure) throws IOException {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:930]: Maybe add a comment about where the corresponding read code for this can be found? future readers may be looking for it and not easily finding it, due to the fact that we write to an opaque bytes transport response.

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java [hunk 6]
```diff
@@ -817,13 +862,98 @@ void onShardDone() {
...
+        void bwcRespond() {
             RecyclerBytesStreamOutput out = null;
             boolean success = false;
             var channelListener = new ChannelActionListener<>(channel);
             try (queryPhaseResultConsumer) {
                 var failure = queryPhaseResultConsumer.failure.get();
                 if (failure != null) {
-                    handleMergeFailure(failure, channelListener, namedWriteableRegistry);
+                    releaseAllResultsContexts();
+                    channelListener.onFailure(failure);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:959]: I wonder if I am missing something: is this doing the same that handleMergeFailure was previously doing?

**Review by javanna — APPROVED** [review]
I left a couple of minor comments. LGTM otherwise

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java (hunk 2 above)
Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:891]: That's right, same as the previous code except for the additional `out.writeBoolean(false);`, telling us there's no reduction failure.

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java (hunk 6 above)
Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:959]: Yes, the exact same. handleMergeFailure doesn't make sense to keep in the new serialization scheme, so I decided to remove the method.

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java (hunk 4 above)
Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:943]: In the case of an IOException, the caller releases contexts in a catch block. So I think this is alright, else we'll be releasing twice?

File: server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java (hunk 5 above)
Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/SearchQueryThenFetchAsyncAction.java:930]: Good idea, done.

File: server/src/main/java/org/elasticsearch/search/query/QuerySearchResult.java [hunk 7]
```diff
@@ -504,7 +504,6 @@ public void writeToNoId(StreamOutput out) throws IOException {
                 out.writeBoolean(true);
                 writeTopDocs(out, topDocsAndMaxScore);
             } else {
-                assert isPartiallyReduced();
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/search/query/QuerySearchResult.java:507]: A failure might occur during the final data node reduction. In this case, due to the central change of this PR, we still send back QuerySearchResults to sit on the coord node. Therefore we can no longer assert that a QuerySearchResult has been reduced when serializing it.
