### PR TITLE
Fix the ability to remove old plugin

### LINKED ISSUE #28538: Unable to remove old plugins in ES 6.2.0 with elasticsearch-plugin
**Elasticsearch version**:
Version: 6.2.0, Build: 37cdac1/2018-02-01T17:31:12.527918Z, JVM: 1.8.0_161

**Plugins installed**: 
[ingest-geoip, ingest-user-agent]

**JVM version**:
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**OS version**:
3.10.0-693.17.1.el7.x86_64 (CentOS 7.4.1708)

**Description of the problem including expected versus actual behavior**:
Uninstalling an old plugin fails after upgrading to 6.2.0. Currently using elasticsearch-plugin I'm unable to remove old plugins in order to install updated plugins that are compatible with 6.2.0.

**Steps to reproduce**:
 1. Get list of installed plugins with `./elasticsearch-plugin list`
ingest-geoip
WARNING: plugin [ingest-geoip] is incompatible with version [6.2.0]; was designed for version [6.1.3]
ingest-user-agent
WARNING: plugin [ingest-user-agent] is incompatible with version [6.2.0]; was designed for version [6.1.3]
 2. Run `./elasticsearch-plugin remove ingest-geoip`
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ingest-geoip] is incompatible with version [6.2.0]; was designed for version [6.1.3]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:224)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:329)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:89)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:67)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

 2. Similar results with `./elasticsearch-plugin remove ingest-user-agent`
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ingest-geoip] is incompatible with version [6.2.0]; was designed for version [6.1.3]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:224)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:329)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:89)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:67)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

**Provide logs (if relevant)**:

See above.

### PR DESCRIPTION
**Pull request by jasontedor**
We now read the plugin descriptor when removing an old plugin. This is to check if we are removing a plugin that is extended by another plugin. However, when reading the descriptor we enforce that it is of the same version that we are. This is not the case when a user has upgraded Elasticsearch and is now trying to remove an old plugin. This commit fixes this by skipping the version enforcement when reading the plugin descriptor only when removing a plugin.

Closes #28538

### CODE REVIEW

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/RemovePluginCommandTests.java [hunk 1]
```diff
@@ -137,6 +147,13 @@ public void testBasic() throws Exception {
         assertRemoveCleaned(env);
     }
 
+    public void testRemoveOldVersion() throws Exception {
+        createPlugin("fake", VersionUtils.randomVersionBetween(random(), Version.CURRENT.minimumCompatibilityVersion(), Version.CURRENT));
```
Comment (rjernst) [inline distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/RemovePluginCommandTests.java]: Since randomVersionBetween is inclusive, I think the top end of this range should be `VersionUtils.getPreviousVersion()`?

**Review by rjernst — COMMENTED** [review]
This looks ok, but I would rather not have 2 variants of readFromProperties. What about moving the enforcement out to another method in install/startup, so reading the properties is just reading properties?

**Comment by jasontedor** [comment]
> This looks ok, but I would rather not have 2 variants of readFromProperties. What about moving the enforcement out to another method in install/startup, so reading the properties is just reading properties?

I have mixed feelings about this. Currently we validate everything in `readFromProperties`. We have never had a need to skip a portion of the validation (because we did not previously need to read the properties descriptor). I am okay reconsidering this, but I would prefer that to be in a follow-up?

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/RemovePluginCommandTests.java (hunk 1 above)
Comment (jasontedor) [reply distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/RemovePluginCommandTests.java]: I pushed a commit for this.

**Review by rjernst — APPROVED** [review]
I'm ok with considering that in a followup. LGTM.
