### PR TITLE
Move back to single EngineConfig

### LINKED ISSUE #10584: Test IndexingMemoryControllerTests#testIndexBufferSizeUpdateAfterCreationRemoval fails post #10452
I was looking at a test failure to see if it relates to my change with the JVM stats aspect. Turns out it didn't, but managed to find the commit that did (#10452). Still did not chase it down into why. Running only the test on IntelliJ with ` -Dtests.seed=F617D748C91B4DD4` causes it to fail on my machine every time, but this for some reason doesn't repro it (still not sure why, weird): 

```
mvn clean test -Dtests.seed=F617D748C91B4DD4 -Dtests.class=org.elasticsearch.indices.memory.IndexingMemoryControllerTests -Dtests.method="testIndexBufferSizeUpdateAfterCreationRemoval" -Dtests.locale=uk -Dtests.timezone=America/Indiana/Tell_City -Dtests.processors=4
```

### PR DESCRIPTION
**Pull request by s1monw**
We need to preserve settings (yet transient) even though the engine is not yet
started. This commit moves back to a single EngineConfig to simplify IndexShard
and settings state.

Closes #10584

### CODE REVIEW

File: src/test/java/org/elasticsearch/indices/memory/IndexingMemoryControllerTests.java [hunk 1]
```diff
@@ -37,7 +38,7 @@
 public class IndexingMemoryControllerTests extends ElasticsearchIntegrationTest {
 
     @Test
-    @LuceneTestCase.AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/10584")
+    @Seed(value = "F617D748C91B4DD4")
```
Comment (bleskes) [inline src/test/java/org/elasticsearch/indices/memory/IndexingMemoryControllerTests.java]: left over...

**Comment by bleskes** [comment]
LGTM. left one minor comment

File: src/test/java/org/elasticsearch/indices/memory/IndexingMemoryControllerTests.java (hunk 1 above)
Comment (s1monw) [inline src/test/java/org/elasticsearch/indices/memory/IndexingMemoryControllerTests.java]: baaah! :)
