### PR TITLE
[ML] Wait for test to finish

### LINKED ISSUE #110536: [CI] TrainedModelAssignmentNodeServiceTests testLoadQueuedModelsWhenOneFails failing
**Build Scans:**
- [elasticsearch-intake #7976 / part4](https://gradle-enterprise.elastic.co/s/yizitplnpimwq)
- [elasticsearch-intake #7973 / part4](https://gradle-enterprise.elastic.co/s/4smytacarzbmq)
- [elasticsearch-intake #7970 / part4](https://gradle-enterprise.elastic.co/s/73nqpjbfu6bsu)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeServiceTests.testLoadQueuedModelsWhenOneFails" -Dtests.seed=713CDEE7BEA268EF -Dtests.locale=es-AR -Dtests.timezone=America/Cordoba -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testLoadQueuedModelsWhenOneFails'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeServiceTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
deploymentManager.stopDeployment(
    <Capturing argument: TrainedModelDeploymentTask>
);
-> at org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeServiceTests.testLoadQueuedModelsWhenOneFails(TrainedModelAssignmentNodeServiceTests.java:338)

However, there were exactly 2 interactions with this mock:
deploymentManager.startDeployment(
    Task{id=1, type='trained_model_assignment', action='xpack/ml/trained_model_assignment[n]', description='model_id[loading-foo]', parentTask=unset, startTime=1720189983528, startTimeNanos=254127493635},
    org.elasticsearch.action.support.SubscribableListener@5b91852b
);
-> at org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeService.lambda$loadModel$4(TrainedModelAssignmentNodeService.java:235)

deploymentManager.startDeployment(
    Task{id=2, type='trained_model_assignment', action='xpack/ml/trained_model_assignment[n]', description='model_id[failed-loading-foo]', parentTask=unset, startTime=1720189983528, startTimeNanos=254127551141},
    org.elasticsearch.action.support.SubscribableListener@1e86a220
);
-> at org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeService.lambda$loadModel$4(TrainedModelAssignmentNodeService.java:235)


```

**Issue Reasons:**
- [main] 2 consecutive failures in test testLoadQueuedModelsWhenOneFails (0.3% fail rate)
- [main] 2 consecutive failures in step part4 (2.2% fail rate)
- [main] 2 consecutive failures in pipeline elasticsearch-intake (2.2% fail rate)
- [main] 3 failures in test testLoadQueuedModelsWhenOneFails (0.3% fail rate)
- [main] 3 failures in step part4 (2.2% fail rate)
- [main] 3 failures in pipeline elasticsearch-intake (2.2% fail rate)
- [main] 2.2% failure rate in step part4 (2.2% fail rate)
- [main] 2.2% failure rate in pipeline elasticsearch-intake (2.2% fail rate)

**Note:**
This issue was created using new, in-development muting automation. Please mind any issues.

### PR DESCRIPTION
**Pull request by prwhelan**
The tests can kick off tasks on another thread.  We should wait for
those threads to join back before we begin making assertions.

Fix #110536

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentNodeService.java [hunk 1]
```diff
@@ -184,6 +184,7 @@ void stop() {
 
     void loadQueuedModels(ActionListener<Boolean> rescheduleImmediately) {
         if (stopped) {
+            rescheduleImmediately.onResponse(false);
```
Comment (prwhelan) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentNodeService.java:187]: This is to not leave the listener dangling - the `if (stopped)` check happens again from the schedule function so it won't kick off a new execution

**Review by maxhniebergall — APPROVED** [review]
LGTM
