### PR TITLE
Do not expose hard-deleted docs in Lucene history

### LINKED ISSUE #32269: CCR:  Aborted document is exposed in Lucene changes
The CCR branch started failing frequently after merging https://github.com/elastic/elasticsearch/pull/31007. Some CI instances:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+ccr+feature-branch-periodic/1002/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+ccr+feature-branch-periodic/1000/console

These failures can be explained as follows:

1. A user issues an indexing which will throw an exception in the analyzing phase. Since the IndexingChain fails to process a document,  the DocumentsWriterPerThread will hard-delete that document internally in Lucene on the primary.

```
[2018-07-20T18:04:15,095][DEBUG][o.e.a.b.TransportShardBulkAction] [test][0] failed to execute bulk item (index) BulkShardRequest [[test][0]] containing [index {[test][test][2], source[{"suggest_context":{"input":"foo"}}]}]
java.lang.IllegalArgumentException: Contexts are mandatory in context enabled completion field [suggest_context]
```

2. On ES, we make all docs live when reading Lucene changes history (in fact, we can not distinguish between hard-deletes and soft-deletes). If a recovering replica reads the aborted document, it will fail to index that document. In fact, the replica will never be able to complete its recovery.

```
[2018-07-20T18:04:15,148][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] fatal error in thread [elasticsearch[node-1][generic][T#4]], exiting
java.lang.AssertionError: unexpected failure while replicating translog entry: java.lang.IllegalArgumentException: Contexts are mandatory in context enabled completion field [suggest_context]
    at org.elasticsearch.indices.recovery.RecoveryTarget.indexTranslogOperations(RecoveryTarget.java:401) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
    at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:458) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
    at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:448)
```

The problem is that we read aborted documents which should never be exposed. This might be a critical problem in CCR and Lucene rollbacks.

/cc @s1monw and @bleskes

### PR DESCRIPTION
**Pull request by dnhatn**
Today when reading operation history in Lucene, we read all documents.
However, if indexing a document is aborted, IndexWriter will hard-delete
it; we, therefore, need to exclude that document from Lucene history.

This commit makes sure that we exclude aborted documents by using the
hard liveDocs of a SegmentReader if there are deletes.

Closes #32269

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/lucene/Lucene.java [hunk 1]
```diff
@@ -869,14 +875,29 @@ public CacheHelper getReaderCacheHelper() {
...
                 public LeafReader wrap(LeafReader leaf) {
-                    return new SubReaderWithAllLiveDocs(leaf);
+                    try {
+                        SegmentReader segmentReader = segmentReader(leaf);
+                        SegmentCommitInfo si = segmentReader.getSegmentInfo();
+                        // TODO: Replace this by hard live bits in LUCENE-8425 and add tests for rolled back
+                        if (si.getDelCount() == 0) {
+                            return new LeafReaderWithLiveDocs(segmentReader, null, segmentReader.maxDoc());
+                        } else {
+                            Bits hardLiveBits = si.info.getCodec().liveDocsFormat().readLiveDocs(si.info.dir, si, IOContext.READ);
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/common/lucene/Lucene.java]: I tried to think this through and we might be subject to concurrent deletes if we do it this way. Can't we instead do something like this: 
```Java
DocIdSetIterator soft_deletes = DocValuesFieldExistsQuery.getDocValuesDocIdSetIterator("soft_deletes", sr);
          Bits liveDocs = sr.getLiveDocs();
          FixedBitSet hardLiveDocs = new FixedBitSet(numDeletes);
          hardLiveDocs.set(0, numDeletes);
          for (int i = 0; i < liveDocs.length(); i++) {
            if (liveDocs.get(i) == false) {
              if (soft_deletes.docID() < i) {
                int doc = soft_deletes.docID() == DocIdSetIterator.NO_MORE_DOCS ? DocIdSetIterator.NO_MORE_DOCS : soft_deletes.advance(i);
                if (doc != i) {
                  hardLiveDocs.clear(i);
                }
              }
            }
          }
```

note I didn't try this out.. just to provide an idea

**Review by s1monw — CHANGES_REQUESTED** [review]

**Comment by dnhatn** [comment]
@s1monw I've updated the PR using the hardLiveDocs exposed in Lucene. I wonder if we should expose "isNRT" property of a SegmentReader so that we know if we can use SegmentInfos to calculate numDocs instead of getting the cardinality of the liveDocs. Can you please have another look? Thank you.

File: server/src/main/java/org/elasticsearch/common/lucene/Lucene.java [hunk 2]
```diff
@@ -869,14 +875,32 @@ public CacheHelper getReaderCacheHelper() {
...
                 @Override
                 public LeafReader wrap(LeafReader leaf) {
-                    return new SubReaderWithAllLiveDocs(leaf);
+                    SegmentReader segmentReader = segmentReader(leaf);
+                    Bits hardLiveDocs = segmentReader.getHardLiveDocs();
+                    if (hardLiveDocs == null) {
+                        return new LeafReaderWithLiveDocs(leaf, null, leaf.maxDoc());
+                    }
+                    final int numDocs;
+                    if (hardLiveDocs instanceof FixedBitSet) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/common/lucene/Lucene.java]: does it ever kick in? I would assume you get a `FixedBits` instance for live docs instead of a mutable FixedBitSet.

File: server/src/test/java/org/elasticsearch/common/lucene/LuceneTests.java [hunk 3]
```diff
@@ -406,4 +414,55 @@ public void testMMapHackSupported() throws Exception {
...
+            IndexSearcher searcher = new IndexSearcher(reader);
+            Set<String> actualDocs = new HashSet<>();
+            TopDocs topDocs = searcher.search(new MatchAllDocsQuery(), Integer.MAX_VALUE);
+            for (ScoreDoc scoreDoc : topDocs.scoreDocs) {
+                actualDocs.add(reader.document(scoreDoc.doc).get("id"));
+            }
+            assertThat(actualDocs, equalTo(liveDocs));
+        }
+        IOUtils.close(writer, dir);
+    }
```
Comment (jpountz) [inline server/src/test/java/org/elasticsearch/common/lucene/LuceneTests.java]: can we make it two tests? one that never inserts a document that fails indexing, and another one that always inserts one?

**Review by jpountz — CHANGES_REQUESTED** [review]
I left some comments.

File: server/src/main/java/org/elasticsearch/common/lucene/Lucene.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/common/lucene/Lucene.java]: Yes, we convert then return a read-only bits. I removed this 💯.

File: server/src/test/java/org/elasticsearch/common/lucene/LuceneTests.java (hunk 3 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/common/lucene/LuceneTests.java]: done

**Comment by dnhatn** [comment]
@jpountz I have addressed your feedbacks? Can you please have another look? Thank you.

**Review by jpountz — APPROVED** [review]
LGTM. We should probably leave a TODO about avoiding to count live docs. Unfortunately we can't do it easily with a FilterDirectoryReader since composite readers count documents eagerly, but maybe we could find a different way to consume hard deletes that doesn't require to count them.

**Comment by dnhatn** [comment]
@jpountz Thanks for reviewing. I added a TODO.

**Comment by dnhatn** [comment]
Thanks @jpountz and @s1monw.
