### PR TITLE
Add a cluster listener to fix missing cluster features after upgrade

### LINKED ISSUE #109254: Features not matching version after an upgrade to 8.13+
### Elasticsearch Version

8.13.x

- Java Version: _bundled_

- OS Version: N/A (different k8s versions)

### Problem Description

ECK operator `2.12.1`  fails upgrading Elasticsearch `8.13+` as it is stalled on the following error when calling the desired nodes API:
```rust
400 Bad Request: {
    Reason: [node_version] field is required and must have a valid value 
    Type: x_content_parse_exception
    ...
}
```

### Steps to Reproduce

The steps should be (not tested yet):
- Deploy ECK 2.12.1+
- Deploy Elasticsearch 8.11.x?
- Upgrade to Elasticsearch 8.13+

### Notes

Note: this is from ECK `2.12.1` that the operator stops to use the deprecated `node_version` field if the cluster is 8.13+:
- https://github.com/elastic/cloud-on-k8s/pull/7663

Two occurences of this issue have been reported for these versions upgrades:
- 8.11.x -> 8.13.3
- 8.11.4 -> 8.13.2

Each time, the users confirmed that:
- some nodes did not have `desired_node.version_deprecated` feature 
- a restart fixes the issue

### PR DESCRIPTION
**Pull request by thecoop**
The cluster listener spots the instances when the master has been upgraded to the most recent code version, along with non-master nodes, but some nodes are missing cluster features

Fixes https://github.com/elastic/elasticsearch/issues/109254

### CODE REVIEW

**Comment by thecoop** [comment]
This doesn't have a test attached, as our existing upgrade tests don't have non-master nodes in them.

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixListener.java [hunk 1]
```diff
@@ -0,0 +1,215 @@
...
+             * We can't use features to determine when this should happen, as the features are incorrect.
+             * So use transport version as a proxy instead.
+             */
+            ClusterFeatures nodeFeatures = event.state().clusterFeatures();
+            Map<String, CompatibilityVersions> nodeVersions = getCompatibilityVersions(event.state());
+            Set<String> queryNodes = event.state()
+                .nodes()
+                .stream()
+                .map(DiscoveryNode::getId)
+                .filter(n -> nodeVersions.get(n).transportVersion().onOrAfter(TransportVersions.NODE_FEATURES_QUERY_ACTION))
```
Comment (thecoop) [inline server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixListener.java:138]: This check is not actually reliable for upgrading from versions before 8.8.0, due to the transport version being inferred to start with. This would require this listener to run strictly after `TransportVersionsFixupListener` has completed, but I don't think it's possible to add a dependency in this way.

Comment (thecoop) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixListener.java:138]: We would need to integrate this with `TransportVersionsFixupListener` to enforce the ordering properly

Comment (mosche) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixListener.java:138]: Using `Version` (option 2.) seems ok to me as well in this case.
Alternatively we could listen for the fix implemented by `NodeFeaturesFixListener` listener in addition to make sure the fix has been applied.

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+import org.elasticsearch.threadpool.ThreadPool;
+
+import java.util.Collections;
+import java.util.HashSet;
+import java.util.Map;
+import java.util.Set;
+import java.util.concurrent.Executor;
+import java.util.stream.Collectors;
+
+@UpdateForV9    // this can be removed in v9
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:45]: Why can this be removed in v9? Is it because you can't upgrade to v9 from versions prior to 8.13 anyway?

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java [hunk 3]
```diff
@@ -0,0 +1,217 @@
...
+public class NodeFeaturesFixupListener implements ClusterStateListener {
+
+    private static final Logger logger = LogManager.getLogger(NodeFeaturesFixupListener.class);
+
+    private static final TimeValue RETRY_TIME = TimeValue.timeValueSeconds(30);
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:50]: Should this be a setting?

**Review by prdoyle — COMMENTED** [review]
I'm afraid my review is fairly superficial.

This PR seems like a great one to bookmark for the next person who wants to add a transport action.

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java (hunk 2 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:45]: You can only upgrade to v9 from v8.last, which will definitely have cluster features. So this won't be needed once its not possible to upgrade from a cluster that doesnt know about features

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java (hunk 3 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:50]: Why would users want to change it?

Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:50]: Fair enough. I don't know TBH.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/features/TransportNodesFeaturesAction.java [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+import org.elasticsearch.tasks.Task;
+import org.elasticsearch.threadpool.ThreadPool;
+import org.elasticsearch.transport.TransportRequest;
+import org.elasticsearch.transport.TransportService;
+
+import java.io.IOException;
+import java.util.List;
+
+@UpdateForV9
+// @UpdateForV10 // this can be removed in v10. It may be called by v8 nodes to v9 nodes.
```
Comment (ldematte) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/node/features/TransportNodesFeaturesAction.java:30]: Unrelated to this PR, but should we already create @UpdateForV10?

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java [hunk 5]
```diff
@@ -0,0 +1,217 @@
...
+        @Override
+        public ClusterState execute(BatchExecutionContext<NodesFeaturesTask> context) {
+            ClusterState.Builder builder = ClusterState.builder(context.initialState());
+            var existingFeatures = builder.nodeFeatures();
+
+            boolean modified = false;
+            for (var c : context.taskContexts()) {
+                for (var e : c.getTask().results().entrySet()) {
+                    // double check there are still no features for the node
+                    if (existingFeatures.getOrDefault(e.getKey(), Set.of()).isEmpty()) {
```
Comment (ldematte) [inline server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:111]: Why is this needed?
Should not we merge the maps in any case?

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java [hunk 6]
```diff
@@ -0,0 +1,217 @@
...
+    }
+
+    private void scheduleRetry(Set<String> nodes, int thisRetryNum) {
+        // just keep retrying until this succeeds
+        logger.debug("Scheduling retry {} for nodes {}", thisRetryNum + 1, nodes);
+        scheduler.schedule(() -> queryNodesFeatures(nodes, thisRetryNum + 1), RETRY_TIME, executor);
+    }
+
+    private void queryNodesFeatures(Set<String> nodes, int retryNum) {
+        // some might already be in-progress
```
Comment (ldematte) [inline server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:167]: This is for the case this runs more times, right? What are the cases? 
Retry for failure, but also more nodes joined?
Would it be possible to have a test for this?

**Review by ldematte — COMMENTED** [review]
Looks good, I have a couple of questions

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java (hunk 5 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:111]: This is more being extra-safe - in the case the node has left and re-joined in the meantime it will have the features in there already, which may be different to those that were queried before the node was shut down.

File: server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java (hunk 6 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:167]: I've added a test for overlapping operations

Comment (ldematte) [reply server/src/main/java/org/elasticsearch/cluster/features/NodeFeaturesFixupListener.java:167]: Thanks!

**Review by ldematte — APPROVED** [review]
LGTM
