### PR TITLE
Snapshot/Restore: Ensure that shard failure reasons are correctly stored in CS

### LINKED ISSUE #25878: NullPointerException when getting list of snapshots on S3
**Elasticsearch version**: 5.5.0 (issue first appeared while on 5.4.1)

**Plugins installed**: [x-pack, repository-s3]

**JVM version** (`java -version`): openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Linux ip-10-127-1-159 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Trying to get the list of available snapshots on an S3 backed repository fails with NullPointerException.

```
curl elasticsearch:9200/_snapshot/long_term/_all
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[SVVyQPF][10.127.1.203:9300][cluster:admin/snapshot/get]"}],"type":"null_pointer_exception","reason":null},"status":500}
```

Elasticsearch logs:

```
[2017-07-25T12:01:47,038][WARN ][r.suppressed             ] path: /_snapshot/long_term/_all, params: {repository=long_term, snapshot=_all}
org.elasticsearch.transport.RemoteTransportException: [SVVyQPF][10.127.1.203:9300][cluster:admin/snapshot/get]
Caused by: java.lang.NullPointerException
```

I use curator to take the backups and after grabbing backups successfully it fails when it tries to delete old snapshots because that's when it requires a list too:

```
2017-07-25 11:53:02,191 ERROR     Failed to complete action: delete_snapshots.  <class 'curator.exceptions.FailedExecution'>: Unable to get snapshot information from repository: long_term.  Error: TransportError(500, 'null_pointer_exception', '[SVVyQPF][10.127.1.203:9300][cluster:admin/snapshot/get]')
```

I have a feeling this is due to some kind of timeout. I turned on debug logging and while I couldn't find a more specific reason this fails I noticed it made ~ 2K requests to S3 until it failed and it stopped at 90 seconds. Is this a configurable timeout?

In the past getting a list of snapshots took increasingly long but it eventually responded. Now it breaks earlier than that.

Also posted on the forums: https://discuss.elastic.co/t/nullpointerexception-when-getting-list-of-snapshots-on-s3/94458

### PR DESCRIPTION
**Pull request by imotov**
The failure reason for snapshot shard failures might not be propagated properly if the master node changes after the errors were reported by other data nodes. This commits ensures that the snapshot shard failure reason is preserved properly and adds workaround for reading old snapshot files where this information might not have been preserved.

Closes #25878

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java [hunk 1]
```diff
@@ -413,9 +415,15 @@ public SnapshotsInProgress(StreamInput in) throws IOException {
...
-                String nodeId = in.readOptionalString();
-                State shardState = State.fromValue(in.readByte());
-                builder.put(shardId, new ShardSnapshotStatus(nodeId, shardState));
+                // TODO: Change this to an appropriate version when it's backported
+                if (in.getVersion().onOrAfter(Version.V_6_0_0_beta1)) {
+                    builder.put(shardId, new ShardSnapshotStatus(in));
+                } else {
+                    String nodeId = in.readOptionalString();
+                    State shardState = State.fromValue(in.readByte());
+                    String reason = shardState.failed() ? "" : null;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java]: can you add a comment here saying why we set `reason` to `""`?

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardFailure.java [hunk 2]
```diff
@@ -215,6 +216,11 @@ public static SnapshotShardFailure fromXContent(XContentParser parser) throws IO
             throw new ElasticsearchParseException("index shard was not set");
         }
         snapshotShardFailure.shardId = new ShardId(index, index_uuid, shardId);
+        // Workaround for https://github.com/elastic/elasticsearch/issues/25878
+        // Some old snapshot might still have null in shard failure reasons
+        if (snapshotShardFailure.reason == null) {
+            snapshotShardFailure.reason = "";
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotShardFailure.java]: What I don't quite understand: Why will it happily parse the `reason` field if it is null? Currently we parse it using `text()`, shouldn't that fail and should we use `textOrNull()` instead?

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 3]
```diff
@@ -1128,7 +1128,7 @@ public ClusterState execute(ClusterState currentState) throws Exception {
                         for (ObjectObjectCursor<ShardId, ShardSnapshotStatus> shardEntry : snapshotEntry.shards()) {
                             ShardSnapshotStatus status = shardEntry.value;
                             if (!status.state().completed()) {
-                                shardsBuilder.put(shardEntry.key, new ShardSnapshotStatus(status.nodeId(), State.ABORTED));
+                                shardsBuilder.put(shardEntry.key, new ShardSnapshotStatus(status.nodeId(), State.ABORTED, "aborted"));
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: maybe extend the message to `"aborted by snapshot deletion"`

File: core/src/test/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java [hunk 4]
```diff
@@ -135,6 +135,13 @@ public static String blockMasterFromFinalizingSnapshot(final String repositoryNa
         return masterName;
     }
 
+    public static String blockMasterFromCreatingSnapshot(final String repositoryName) {
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java]: The method name made me think that it would prevent the master from creating a snapshot at all. Maybe we can call it something along the lines of "blockMasterFromFinalizingSnapshot"?

**Review by ywelsch — APPROVED** [review]
I've left some minor suggestions and a question around JSON deserialization. Thanks @imotov

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotShardFailure.java (hunk 2 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotShardFailure.java]: You are right, it should be `textOrNull()`.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by imotov** [comment]
@ywelsch thanks a lot for review and help! I will let it "cook" in CI on the master branch over the weekend and then I will backport it to 5.6 and update the version in writeTo and readFrom if everything goes well.

**Comment by imotov** [comment]
It looks like it didn't make it into 6.0.0-beta1. Will try to backport to 6.0.0-beta2 when beta1 is released.
