### PR TITLE
ESQL: Fix bug in grammar that allowed spaces inside id pattern

### LINKED ISSUE #105441: ES|QL: regression on identifier patterns
The fixes introduced by https://github.com/elastic/elasticsearch/pull/105325 seem to have an unexpected side effect:
the following query is parsed correctly (and probably it should not)

```
row a = 10 | rename a as this is fine
```

the output has a field name that is not what is defined in the queries (`thisisfine` vs `this is fine`)

```
  thisisfine   
---------------
10
```

### PR DESCRIPTION
**Pull request by costin**
Change id pattern into a lexer rule and rely on fragments to avoid
 having whitespaces inside an id pattern

Fix #105441

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 1]
```diff
@@ -874,6 +875,44 @@ private void assertIdentifierAsIndexPattern(String identifier, String statement)
...
+    }
+
+    public void testIdPatternQuoted() throws Exception {
+        var string = "`escaped string`";
+        assertThat(breakIntoFragments(string), contains(string));
+    }
+
+    public void testIdPatternQuotedWithDoubleBackticks() throws Exception {
+        var string = "`escaped``string`";
+        assertThat(breakIntoFragments(string), contains(string));
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:890]: 👍 👍 👍 

nit: it would be good to test that the final field name will be ```escaped`string```, ie. that the double backtick is an escape for backtick inside quoted strings.

I couldn't find this detail in the docs, @leemthompo could you please double-check?

**Review by luigidellaquila — COMMENTED** [review]
LGTM, thanks!

**Review by astefan — COMMENTED** [review]
The changes in the PR LGTM.

**But**, to save us time, a bug report, a new PR and a round of reviews, the `enrich` command needs an update as well. And we could do it in this PR.

`ExpressionBuilder.enrichFieldName` method should be changed to (and some tests added, maybe `ROW a = \"1\" | ENRICH languages_policy ON a WITH ```name``*` = language_name`):

```
    private NamedExpression enrichFieldName(EsqlBaseParser.QualifiedNamePatternContext ctx) {
        var name = visitQualifiedNamePattern(ctx);
        if (name != null && name instanceof UnresolvedNamePattern up) {
            throw new ParsingException(source(ctx), "Using wildcards (*) in ENRICH WITH projections is not allowed [{}]", up.pattern());
        }
        return name;
    }
```

**Review by luigidellaquila — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:890]: Thanks for checking @leemthompo, that looks good, no need to add further information IMHO
