### PR TITLE
Work around JVM Bug in LongGCDisruptionTests

### LINKED ISSUE #50047: LongGCDisruptionTests.testNotBlockingUnsafeStackTraces failed
Over the last month + there have been periodic failures of org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces

A recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/379/console

Reproduce Line: 
```
./gradlew ':test:framework:test' --tests "org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces" \
  -Dtests.seed=60FAC2799A7B2796 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu-HU \
  -Dtests.timezone=US/Central \
  -Dcompiler.java=12
```

The internal stack trace:
```
11:07:35   2> java.lang.RuntimeException: suspending node threads took too long
11:07:35         at __randomizedtesting.SeedInfo.seed([60FAC2799A7B2796:62E98AC6BE559FFF]:0)
11:07:35         at org.elasticsearch.test.disruption.LongGCDisruption.startDisrupting(LongGCDisruption.java:124)
11:07:35         at org.elasticsearch.test.disruption.LongGCDisruptionTests.testNotBlockingUnsafeStackTraces(LongGCDisruptionTests.java:149)
```

The threadstacks:
```
11:07:35   1> [2019-12-10T10:07:32,452][WARN ][o.e.t.d.LongGCDisruptionTests$2] [testNotBlockingUnsafeStackTraces] failed to suspend node [test_node]'s threads within [30000] millis. Suspending thread stack trace:
11:07:35   1>  java.base@11.0.5/java.lang.Thread.suspend0(Native Method)
11:07:35   1> java.base@11.0.5/java.lang.Thread.suspend(Thread.java:1085)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruption.suspendThreads(LongGCDisruption.java:254)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruption$1.doRun(LongGCDisruption.java:87)
11:07:35   1> app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> Threads that weren't suspended:
11:07:35   1>  [test_node][0]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][4]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
11:07:35   1> java.base@11.0.5/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$LockedExecutor.executeLocked(LongGCDisruptionTests.java:45)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:139)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][3]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][1]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
11:07:35   1> [test_node][2]
11:07:35   1> ----
11:07:35   1> java.base@11.0.5/java.lang.Thread.yield(Native Method)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$2(LongGCDisruptionTests.java:131)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$260/0x000000010033e840.run(Unknown Source)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testNotBlockingUnsafeStackTraces$3(LongGCDisruptionTests.java:141)
11:07:35   1> app//org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$261/0x000000010033ec40.run(Unknown Source)
11:07:35   1> java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
There is a JVM bug causing `Thread#suspend` calls to randomly take
multiple seconds breaking these tests that call the method numerous times
in a loop. Increasing the timeout would will not work since we may call
`suspend` tens if not hundreds of times and even a small number of them
experiencing the blocking will lead to multiple minutes of waiting.

This PR detects the specific issue by timing the `Thread#suspend` calls and
skips the remainder of the test if it timed out because of the JVM bug.

Closes #50047

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/disruption/LongGCDisruption.java [hunk 1]
```diff
@@ -251,7 +265,11 @@ protected boolean suspendThreads(Set<Thread> nodeThreads) {
                          * assuming that it is safe.
                          */
                         boolean definitelySafe = true;
+                        final long startTime = System.nanoTime();
                         thread.suspend();
+                        if (System.nanoTime() - startTime > TimeUnit.SECONDS.toNanos(3L)) {
+                            sawSlowSuspendBug.set(true);
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/disruption/LongGCDisruption.java]: Could we make this conditional on the JVM version so that we are sure to keep tracking that JVM bug and to drop this fix when it's no longer needed?

Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/disruption/LongGCDisruption.java]: Technically we could, but right now we're seeing this failure on all versions. This is a little unexpected on `8` so I figured we'd apply the fix for 8 as well to identify whether it's the same issue (slow `suspend`) there or if it's blocked somewhere else.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!
