### PR TITLE
Fix lossy-conversions lint warnings

### LINKED ISSUE #95839: Compilation failure with JDK 20
### Description

ElasticSearch compilation is failing when using jdk 20. The failure is caused by number of (new?) `warning: [lossy-conversions] implicit cast from long to int in compound assignment is possibly lossy` emitted by the compiler that are not supressed/permitted.

This could be reproduced when using:
```
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)
```
and running
```
./gradlew compileJava
```

### PR DESCRIPTION
**Pull request by ChrisHegarty**
JDK 20 has added a new javac lint warning for possible _lossy conversion_ in compound assignments - because of implicit type casts, e.g. 
  `warning: [lossy-conversions] implicit cast from int to byte in compound assignment is possibly lossy`

The change resolves all such warnings, by either widening the type of the left-hand operand, or explicitly casting the type of the right-hand operand. The changes are largely mechanical.

Resolving these issues allows to build with JDK 20 using JAVA_TOOLCHAIN_HOME.

FYI - The JDK issue that added the javac lint warning - https://bugs.openjdk.org/browse/JDK-8244681

closes #95839

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/io/stream/ByteArrayStreamInput.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public void reset(byte[] bytes, int offset, int len) {
     }
 
     public void skipBytes(long count) {
-        pos += count;
+        pos += (int) count;
     }
```
Comment (ChrisHegarty) [inline server/src/main/java/org/elasticsearch/common/io/stream/ByteArrayStreamInput.java:63]: Optionally, we could choose to use `Math::toIntExact` here.

**Review by pugnascotia — APPROVED** [review]
LGTM
