### PR TITLE
Handle primary failure handling replica response

### LINKED ISSUE #24935: [CI] SmokeTestMultiNodeClientYamlTestSuiteIT {create/60_refresh/refresh=wait_for} fails
The following test failed on CI (see [this build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/2970/console)): 

org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search}

It doesn't reproduce locally and I don't know what happened. The trace shows that the wait_for option timed out but I have no clue why:

  ```
1> [2017-05-28T00:04:33,592][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] [test {yaml=cat.aliases/10_basic/Column headers}]: after test
  1> [2017-05-28T00:04:33,598][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] [test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search}]: before test
  1> [2017-05-28T00:05:03,705][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] [test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search}]: after test
  1> [2017-05-28T00:05:03,709][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : null
  1>   }
  1> }]
ERROR   30.1s | SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search} <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Failure at [create/60_refresh:67]: listener timeout after waiting for [30000] ms
   > 	at __randomizedtesting.SeedInfo.seed([C14AB41884F38AA8:491E8BC22A0FE750]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:346)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:328)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:169)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:157)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:89)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:221)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:344)
   > 	... 37 more
```

### PR DESCRIPTION
**Pull request by jasontedor**
Today if the primary throws an exception while handling the replica response (e.g., because it is already closed while updating the local checkpoint for the replica), or because of a bug that causes an exception to be thrown in the replica operation listener, this exception is caught by the underlying transport handler plumbing and is translated into a response handler failure transport exception that is passed to the onFailure method of the replica operation listener. This causes the primary to turn around and fail the replica which is a disastrous and incorrect outcome as there's nothing wrong with the replica, it is the primary that is broken and deserves a paddlin'. This commit handles this situation by failing the primary.

Closes #24935

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java [hunk 1]
```diff
@@ -185,7 +185,13 @@ private void performOnReplica(final ShardRouting shard, final ReplicaRequest rep
             @Override
             public void onResponse(ReplicaResponse response) {
                 successfulShards.incrementAndGet();
-                primary.updateLocalCheckpointForShard(response.allocationId(), response.localCheckpoint());
+                try {
+                    primary.updateLocalCheckpointForShard(response.allocationId(), response.localCheckpoint());
+                } catch (final Exception e) {
+                    final String message = String.format(Locale.ROOT, "primary failed updating local checkpoint for replica %s", shard);
+                    primary.failShard(message, e);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: we need to fix the java docs on failShard.

File: core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java [hunk 2]
```diff
@@ -185,7 +185,13 @@ private void performOnReplica(final ShardRouting shard, final ReplicaRequest rep
             @Override
             public void onResponse(ReplicaResponse response) {
                 successfulShards.incrementAndGet();
-                primary.updateLocalCheckpointForShard(response.allocationId(), response.localCheckpoint());
+                try {
+                    primary.updateLocalCheckpointForShard(response.allocationId(), response.localCheckpoint());
+                } catch (final Exception e) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I think we need to be careful hare. It's ok to have closed the shard. For example if the index was deleted (or more complicated, if this a target primary and the source node left the cluster before the master activated this primary. In these cases, we shouldn't fail the operation (nor the shard, for that matter) but rather let things finish in their natural flow. If the op was properly replicated to all active shards, we're all good. If not, we're in trouble but that would be picked up by the logic handling failures from replicas.

**Review by bleskes — CHANGES_REQUESTED** [review]
I left one main comment. I don't think we should fail the primary on all failures.

File: core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java (hunk 2 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I pushed 2ac842287c8c03d49e0fa6e96b38b90ad6ced0a8.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I pushed 2ac842287c8c03d49e0fa6e96b38b90ad6ced0a8.

File: core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I pushed 2ac842287c8c03d49e0fa6e96b38b90ad6ced0a8.

**Comment by jasontedor** [comment]
@bleskes I've responded to your feedback.

**Comment by nik9000** [comment]
I edited the description of the PR to include a reference to an issue tracking the CI failure that discovered it.

File: core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java [hunk 3]
```diff
@@ -185,7 +186,15 @@ private void performOnReplica(final ShardRouting shard, final ReplicaRequest rep
...
                 successfulShards.incrementAndGet();
-                primary.updateLocalCheckpointForShard(response.allocationId(), response.localCheckpoint());
+                try {
+                    primary.updateLocalCheckpointForShard(response.allocationId(), response.localCheckpoint());
+                } catch (final AlreadyClosedException e) {
+                    // okay, the index was deleted or this shard was never activated after a relocation; fallthrough and finish normally
+                } catch (final Exception e) {
+                    final String message = String.format(Locale.ROOT, "primary failed updating local checkpoint for replica %s", shard);
+                    primary.failShard(message, e);
+                    finishAsFailed(new RetryOnPrimaryException(primary.routingEntry().shardId(), message, e));
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I don't think we should do this. The failure is not related to this operation. IMO we should keep processing the operation as normal. This would be identical to the primary failing just after we acked the write (for whatever reason)

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I pushed dc4531bbebdd1b9f55bbb1ef09b863a7e2c4e609.

**Review by bleskes — APPROVED** [review]
LGTM
