### PR TITLE
Don't use the fixed bitset filter cache for child nested level filters, but the regular filter cache instead

### LINKED ISSUE #8810: java.lang.OutOfMemoryError: Java heap space after upgrade from 0.90
We have 6 servers and 14 shards in cluster, the index size 26GB, we have 1 replica so total size is 52GB, and ES v1.4.0, java version "1.7.0_65"
We use servers with RAM of 14GB (m3.xlarge), and heap is set to 7GB

After update from 0.90 we started facing next issue:
random cluster servers around once a day/two hits the heap size limit (java.lang.OutOfMemoryError: Java heap space) in log, and cluster falls - becomes red or yellow

We tried to add more servers to cluster - even 8, but than it's a matter of time when we'll hit the problem, so looks like there is no matter how many servers are in cluster - it still hits the limit after some time.
Before we started facing the problem we were running smoothly with 3 servers
Also we tried to set indices.fielddata.cache.size:  40% but it didnt helped
Also, there are possible workarounds to flush heap:
1) reboot some server - than heap becomes under 70% and for some time cluster is ok
or
2) decrease number of replicas to 0, and than back to 1

Upgrade to 1.4.1 hasn't solved an issue. 

Finally <b>found the query causing the cluster crashes</b>. After I commented code doing this - the claster is ok for few days. Before it was crashing once a day in average.

the query looks like:

        {
            "sort": [
                {
                    "user_last_contacted.ct": {
                        "nested_filter": {
                            "term": {
                                "user_last_contacted.owner_id": "542b2b7fb0bc2244056fd90f"
                            }
                        },
                        "order": "desc",
                        "missing": "_last"
                    }
                }
            ],
            "query": {
                "filtered": {
                    "filter": {
                        "term": {
                            "company_id": "52c0e0b7e0534664db9dfb9a"
                        }
                    },
                    "query": {
                        "match_all": {}
                    }
                }
            },
            "explain": false,
            "from": 0,
            "size": 100
        }

the mapping looks like:

            "contact": {
                "_all": {
                    "type": "string",
                    "enabled": true,
                    "analyzer": "default_full",
                    "index": "analyzed"
                },
                "_routing": {
                    "path": "company_id",
                    "required": true
                },
                "_source": {
                    "enabled": false
                },
                "include_in_all": true,
                "dynamic": false,
                "properties": {
                    "user_last_contacted": {
                        "include_in_all": false,
                        "dynamic": false,
                        "type": "nested",
                        "properties": {
                            "ct": {
                                "include_in_all": false,
                                "index": "not_analyzed",
                                "type": "date"
                            },
                            "owner_id": {
                                "type": "string"
                            }
                        }
                    }...

user_last_contacted is an array field with nested objects. The size of the array can be 100+ items.

### PR DESCRIPTION
**Pull request by martijnvg**
Random access based bitsets are not required for the child level nested level filters.

Closes #8810

### CODE REVIEW

File: src/main/java/org/elasticsearch/search/MultiValueMode.java [hunk 1]
```diff
@@ -438,39 +441,65 @@ public long get(int docID) {
...
         }
+        final DocIdSetIterator innerDocs = innerDocSet.iterator();
+        if (innerDocs == null) {
+            return select(DocValues.emptySortedNumeric(maxDoc), missingValue);
+        }
+
         return new NumericDocValues() {
 
+            int lastSeenRootDoc = -1;
+            long lastEmittedValue;
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/search/MultiValueMode.java]: Should we rather initialize lastSeenRootDoc=0 and lastEmittedValue=missingValue to avoid the `if (rootDoc == 0)` check below?

**Comment by jpountz** [comment]
LGTM

File: src/main/java/org/elasticsearch/search/MultiValueMode.java (hunk 1 above)
Comment (martijnvg) [inline src/main/java/org/elasticsearch/search/MultiValueMode.java]: yes, that makes sense! I'll change that.
