### PR TITLE
Fix serialization errors when cross cluster search goes to a single shard

### LINKED ISSUE #26833: Cross cluster search sometimes fails
**Elasticsearch version**: Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z, JVM: 1.8.0_144

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:
When doing a cross-cluster search on a remote alias, the remote master will drop encounter a serialization error and will drop the connection with a remote node.

The client receives the following error: 
```
{"error":{"root_cause":[{"type":"transport_serialization_exception","reason":"Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"concrete-index","node":"a1P-CIioRmeJ96CqoWo0gA","reason":{"type":"transport_serialization_exception","reason":"Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]","caused_by":{"type":"index_out_of_bounds_exception","reason":"readerIndex(45) + length(1) exceeds writerIndex(45): UnpooledDuplicatedByteBuf(ridx: 45, widx: 45, cap: 65536, unwrapped: PooledHeapByteBuf(ridx: 6, widx: 45, cap: 65536))"}}}]},"status":500}
```

This issue does not always reproduce but I have noticed the following:
- For an index with a one shard and one replica, it happens if there are three cluster nodes but not two.
- It can be possible to mitigate the problem by assigning certain nodes to master and making them gateway nodes.
- The issue sometimes triggers on a concrete index although less reliably

**Steps to reproduce**:

1. Setup clusters

Local client cluster:
```
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.client \
  -Epath.logs=logs.client \
  -Ecluster.name=client \
  -Etransport.tcp.port=9300 \
  -Ehttp.port=9200 \
  -d
```

Remote cluster:
```
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.remote1 \
  -Epath.logs=./logs.remote1 \
  -Ecluster.name=remote \
  -Etransport.tcp.port=9310 \
  -Ehttp.port=9210 \
  -Ediscovery.zen.ping.unicast.hosts=localhost:9320 \
  -d
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.remote2 \
  -Epath.logs=./logs.remote2 \
  -Ecluster.name=remote \
  -Etransport.tcp.port=9320 \
  -Ehttp.port=9220 \
  -Ediscovery.zen.ping.unicast.hosts=localhost:9310 \
  -d
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.remote3 \
  -Epath.logs=./logs.remote3 \
  -Ecluster.name=remote \
  -Etransport.tcp.port=9330 \
  -Ehttp.port=9230 \
  -Ediscovery.zen.ping.unicast.hosts=localhost:9310 \
  -d
```

2. Wait for the nodes to start
3. Add a seed for cross cluster search to the local node
```
curl -XPUT 'http://localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "transient": {
    "search.remote.remote.seeds": "127.0.0.1:9310"
  }
}'
```
4. Create the remote index
```
curl -XPUT 'http://localhost:9210/concrete-index?pretty' -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "index" : {
            "number_of_shards" : 1,
            "number_of_replicas" : 1
        }
    },
    "aliases" : {
        "alias" : {}
    }
}'
```

5. Execute a search
```
curl 'http://localhost:9200/remote:alias/_search?pretty'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "transport_serialization_exception",
        "reason" : "Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "concrete-index",
        "node" : "D7hySVoNTzK41TZdXsYElA",
        "reason" : {
          "type" : "transport_serialization_exception",
          "reason" : "Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]",
          "caused_by" : {
            "type" : "index_out_of_bounds_exception",
            "reason" : "readerIndex(45) + length(1) exceeds writerIndex(45): UnpooledDuplicatedByteBuf(ridx: 45, widx: 45, cap: 65536, unwrapped: PooledHeapByteBuf(ridx: 6, widx: 45, cap: 65536))"
          }
        }
      }
    ]
  },
  "status" : 500
}
```

### PR DESCRIPTION
**Pull request by javanna**
The single shard optimization that we have in our search api changes the type of response returned by the query transport action name based on the shard search request. if the request goes to one shard, we will do query and fetch at the same time, hence the response will be different. The proxying layer used in cross cluster search was not aware of this distinction, which causes serialization issues every time a cross cluster search request goes to a single shard and goes through a gateway node which has to forward the shard request to a data node. The coordinating node would then expect a `QueryFetchSearchResult` while the gateway would return a `QuerySearchResult`.

Closes #26833

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/transport/TransportActionProxy.java [hunk 1]
```diff
@@ -53,23 +53,25 @@ private TransportActionProxy() {} // no instance
         public void messageReceived(T request, TransportChannel channel) throws Exception {
             DiscoveryNode targetNode = request.targetNode;
             TransportRequest wrappedRequest = request.wrapped;
-            service.sendRequest(targetNode, action, wrappedRequest, new ProxyResponseHandler<>(channel, responseFactory));
+            service.sendRequest(targetNode, action, wrappedRequest, new ProxyResponseHandler<>(channel, wrappedRequest, responseFactory));
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/transport/TransportActionProxy.java]: do we really need to hold on to the request or can we invoke the function here? I really think we shouldn't hold on to the request?!

**Review by s1monw — CHANGES_REQUESTED** [review]
I left one comment, LGTM otherwise

**Comment by javanna** [comment]
@s1monw my last commit should address your concerns ;) good points!

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by hankduan** [comment]
Does the tag mean this will be fixed in v5.6.3?

**Comment by tvernum** [comment]
@hankduan You can read the release notes for 5.6.3 here: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/release-notes-5.6.3.html

This fix is the last item on that list.

**Comment by hankduan** [comment]
Great, thank you!
