### PR TITLE
[ML][Data Frames] unify validation exceptions between PUT/_preview

### LINKED ISSUE #44953: [ML-DataFrame] unsupported aggregation error/code inconsistent
found: `7.3.0-SNAPSHOT`

When trying to preview/create a data frame transform using an unsupported aggregation, the error message and HTTP return codes are inconsistent:

preview:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "No enum constant org.elasticsearch.xpack.dataframe.transforms.pivot.Aggregations.AggregationType.TERMS"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "No enum constant org.elasticsearch.xpack.dataframe.transforms.pivot.Aggregations.AggregationType.TERMS"
  },
  "status": 400
}
```

put:
```
{
  "error": {
    "root_cause": [
      {
        "type": "runtime_exception",
        "reason": "Failed to validate data frame configuration"
      }
    ],
    "type": "runtime_exception",
    "reason": "Failed to validate data frame configuration",
    "caused_by": {
      "type": "runtime_exception",
      "reason": "Unsupported aggregation type [terms]"
    }
  },
  "status": 500
}
```

Ideally it should return the error message(Unsupported aggregation type [terms]) of put but the return code of _preview (400)

## Repro:

```
#POST _data_frame/transforms/_preview
PUT _data_frame/transforms/pivot-kib
{
  "source": {
    "index": "kibana_sample_data_ecommerce"
  },
  "dest": {
    "index": "pivot_kib"
  }, 
  "pivot": {
    "group_by": {
      "customer_id": {
        "terms": {
          "field": "customer_id"
        }
      }
    },
    "aggregations": {
      "days": {
        "terms": {
          "field": "day_of_week",
          "size": 10
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by benwtrent**
We should not be returning a 500 to the end user on a validation failure. Additionally, we should have _preview return the same error as PUT when there is an unsupported aggregation.

closes #44953

### CODE REVIEW

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/pivot/Pivot.java [hunk 1]
```diff
@@ -72,7 +73,7 @@ public Pivot(PivotConfig config) {
     public void validateConfig() {
         for (AggregationBuilder agg : config.getAggregationConfig().getAggregatorFactories()) {
             if (Aggregations.isSupportedByDataframe(agg.getType()) == false) {
-                throw new RuntimeException("Unsupported aggregation type [" + agg.getType() + "]");
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/pivot/Pivot.java]: I changed all of these from `RuntimeException` to `ElasticsearchException` as they probably should never have been an `RuntimeException` due to serialization between nodes and making sure we only catch and unhandled exceptions we throw on purpose.

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/pivot/Pivot.java [hunk 2]
```diff
@@ -82,15 +83,15 @@ public void validateQuery(Client client, SourceConfig sourceConfig, final Action
...
                 return;
             }
             if (response.status() != RestStatus.OK) {
-                listener.onFailure(new RuntimeException("Unexpected status from response of test query: "+ response.status()));
+                listener.onFailure(new ElasticsearchException("Unexpected status from response of test query: "+ response.status()));
                 return;
             }
             listener.onResponse(true);
-        }, e -> listener.onFailure(new RuntimeException("Failed to test query", e))));
+        }, e -> listener.onFailure(new ElasticsearchException("Failed to test query", e))));
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/pivot/Pivot.java]: does not look like a 400 to me, but another 5xx one. ElasticsearchStatusException with 503?

All errors here are corner cases: any invalid query would not make it here as we parse the query before this is called. So an invalid query syntax is not catched here.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java [hunk 3]
```diff
@@ -213,15 +215,19 @@ private void putDataFrame(Request request, ActionListener<AcknowledgedResponse>
...
 
         try {
             pivot.validateConfig();
-        } catch (Exception e) {
+        } catch (ElasticsearchException e) {
             listener.onFailure(
-                new RuntimeException(DataFrameMessages.REST_PUT_DATA_FRAME_FAILED_TO_VALIDATE_DATA_FRAME_CONFIGURATION,
+                new ElasticsearchStatusException(
+                    DataFrameMessages.REST_PUT_DATA_FRAME_FAILED_TO_VALIDATE_DATA_FRAME_CONFIGURATION,
+                    RestStatus.BAD_REQUEST,
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: this overwrites whatever is defined by the catched exception. It think we should forward the rest status of the catched exception.

**Review by hendrikmuhs — COMMENTED** [review]
added some comments

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java (hunk 3 above)
Comment (benwtrent) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: This assumes that the underlying exception throws a rest status. They were previously runtime exceptions, which did nothing of the sort. I can adjust so that the underlying query validation throws status exceptions.

Comment (hendrikmuhs) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: `ElasticSearchException` has `status()` so you have a status you can use. Let me elaborate the suggestion: 

```
try {
    pivot.validateConfig();
} catch (ElasticsearchException e) {
// expected errors, e.g. user error
    listener.onFailure(new ElasticsearchStatusException(
      DataFrameMessages.REST_PUT_DATA_FRAME_FAILED_TO_VALIDATE_DATA_FRAME_CONFIGURATION,
      e.status(), e));
} catch (Exception e) {
// for the unexpected error, e.g. bugs (feel free to use a different message text)
    listener.onFailure(new ElasticsearchStatusException(
    DataFrameMessages.REST_PUT_DATA_FRAME_FAILED_TO_VALIDATE_DATA_FRAME_CONFIGURATION,
    RestStatus.INTERNAL_SERVER_ERROR,
    e));
}

Comment (benwtrent) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: Yes, I did something similar in the latest commit.

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/1

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
