### PR TITLE
Prevent data nodes from sending stack traces to coordinator when `error_trace=false`

### LINKED ISSUE #116772: EsRejectedExecutionException instances consume an unreasonable amount of heap on coordinating nodes
Currently, if a data node rejects the execution of a query it sends a full `EsRejectedExecutionException` back to the coordinating node.
Each of these instances is then wrapped in a `ShardSearchFailure` and stored on heap on the coordinating node until all responses are received. Each instances practically comes out to about 50kb, resulting in searches targeting thousands of shards that all reject taking up hundreds of MB for these exceptions that will eventually not even see their stack-traces (which consume the bulk of the heap here) serialised on the REST layer.

Practically this leads to situations like this:

Image

A search targeting 5k shards that mostly sees rejections consumes over 100M for the exceptions until the response is serialised.
Outside of wasting heap, this can easily lead to a cascading failure effect in a cluster. Under sustained heavy load, once data nodes are overwhelmed as far as query processing goes, coordinating nodes can easily get overwhelmed by the heap consumption shown above.
The more shards targeted the easier it is to overwhelm a coordinating node but practically assuming constant rejections from the data nodes, there's currently a request rate above which any coordinating node gets overwhelmed.

### PR DESCRIPTION
**Pull request by piergm**
This PR updates the behavior of data nodes to optimize error handling during search operations. When the query parameter `error_trace=false` is specified in the request (which defaults to `false`), data nodes will no longer send stack traces to the search coordinator node.

With `error_trace=false`, the stack trace is already excluded from the REST response to the client. By extending this to the communication between data nodes and the coordinator node, we further reduce unnecessary data transfer and lower the memory needed to handle search requests in case of errors in the coordinating node.

To implement this, the `error_trace` query parameter is passed to data nodes via the transport request header `error_trace`. This ensures consistent handling of the `error_trace` flag throughout the search request lifecycle.
After this change the `error_trace` header will be always sent to data nodes. Nodes with an older version will therefore have no way to specify if we want or not stack trace, therefore upon reading the header in the data node, if not specified we default to true, mimicking the current behaviour.

closes: #116772

### CODE REVIEW

**Comment by piergm** [comment]
@elasticmachine test this please

File: server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java [hunk 1]
```diff
@@ -72,6 +80,9 @@ public String getName() {
 
     @Override
     public RestChannelConsumer prepareRequest(final RestRequest request, final NodeClient client) throws IOException {
+        // set weather data nodes should send back stack trace based on the `error_trace` query parameter
+        context.putHeader("error_trace", request.param("error_trace", "false"));
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java:84]: do we have a constant for error_trace that we could point to?

File: server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java [hunk 2]
```diff
@@ -72,6 +80,9 @@ public String getName() {
 
     @Override
     public RestChannelConsumer prepareRequest(final RestRequest request, final NodeClient client) throws IOException {
+        // set weather data nodes should send back stack trace based on the `error_trace` query parameter
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java:83]: s/weather/whether

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 3]
```diff
@@ -813,6 +834,7 @@ public void executeQueryPhase(
      * when the object is no longer needed.
      */
     public void executeQueryPhase(QuerySearchRequest request, SearchShardTask task, ActionListener<QuerySearchResult> listener) {
+        listener = maybeWrapListenerForStackTrace(listener);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:837]: I can see how we need end-to-end tests for this functionality, yet I wish we had some unit tests of some sort as well. The bits in SearchServiceTests are an example. I know that it takes effort to create a full-blown SearchService instance, but we could probably test the wrapping at least in isolation, and maybe the fact that it is called in SearchServiceTests (which is a single node test class)

File: server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java [hunk 4]
```diff
@@ -87,6 +88,24 @@ default Collection<RestHandler> getRestHandlers(
         return Collections.emptyList();
     }
 
+    /**
+    * Rest handlers added by this plugin with ThreadContext.
+    */
+    default Collection<RestHandler> getRestHandlers(
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java:94]: I get that this is needed to get the ThreadContext as a constructor argument, but it looks odd that we are adding a second getRestHandlers method, and I don't follow where this is called e.g. in ActionModule. I must be missing something.

File: server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java [hunk 5]
```diff
@@ -87,6 +88,24 @@ default Collection<RestHandler> getRestHandlers(
...
+        Settings settings,
+        NamedWriteableRegistry namedWriteableRegistry,
+        RestController restController,
+        ClusterSettings clusterSettings,
+        IndexScopedSettings indexScopedSettings,
+        SettingsFilter settingsFilter,
+        IndexNameExpressionResolver indexNameExpressionResolver,
+        Supplier<DiscoveryNodes> nodesInCluster,
+        Predicate<NodeFeature> clusterSupportsFeature,
+        ThreadContext context
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java:104]: A general question for core/infra perhaps: are we good using ThreadContext to set transport headers like we do in this PR? I believe that an advantage is that it can be used in other places, as opposed to adding a specific SearchRequest flag that would be specific to search. I'd assume that the same problem around carrying around stacktraces without ever returning them to the user is common.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+                    "simple_query_string" : {
+                        "query": "foo",
+                        "fields": ["field"]
+                    }
+                }
+            }
+            """);
+        searchRequest.addParameter("error_trace", "false");
+        getRestClient().performRequest(searchRequest);
+        assertFalse(hasStackTrace.get());
```
Comment (javanna) [inline x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:123]: I think that we should add tests where we retrieve results from the async search index too. You may need to lower the `wait_for_completion_timeout` otherwise async search behaves like _search and does not save results to the index. I'd like to know what the behaviour there is before and after this change. Does get async search API also accept error_trace and can it enable/disable whether you get back the trace at retrieval, once the search has completed?

File: server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java [hunk 7]
```diff
@@ -95,6 +98,8 @@ public Set<String> supportedCapabilities() {
 
     @Override
     public RestChannelConsumer prepareRequest(final RestRequest request, final NodeClient client) throws IOException {
+        // set weather data nodes should send back stack trace based on the `error_trace` query parameter
+        context.putHeader("error_trace", request.param("error_trace", "false"));
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java:102]: Maybe we could also centralize the putHeader call somewhere. Where do we handle the common rest parameters perhaps?

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 8]
```diff
@@ -503,7 +505,23 @@ protected void doClose() {
         keepAliveReaper.cancel();
     }
 
+    // Wraps the listener to avoid sending StackTrace if error_trace is set to false
+    private <T> ActionListener<T> maybeWrapListenerForStackTrace(ActionListener<T> listener) {
+        String header = threadPool.getThreadContext().getHeaderOrDefault("error_trace", "true");
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:510]: Can you remind me the rationale behind using true as a default value here?

**Review by javanna — COMMENTED** [review]
Thanks for working on this Matteo, I left some comments

File: server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java (hunk 1 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java]: I added a constant and modified the already existing paramAsBoolean function calls for `error_trace, that takes the default, to use the new constant. (I could also make this a separate PR, but the change is quite small)

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 8 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:510]: We wanted the node behaviour to be consistent across version. And by default we return the stack trace.
If this is no longer a concern I can use the ERROR_CONTEXT_DEFAULT here too.

File: server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java (hunk 7 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/action/search/RestSearchAction.java]: Done!

File: server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java (hunk 4 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java]: I removed ThreadContext from the constructors and added a method to set it in the parent class. I think this is cleaner and avoids the duplication of getRestHandler.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 3 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:837]: I've added also a unit test for the listener wrapping

File: server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java (hunk 2 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java]: Done! :D

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 8 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:511]: Ok, so the idea is that nodes on older version don't have a way to request the stacktrace, hence if we remove it by default they are never going to get it even if error_trace is true. is that it? If so can you clarify that in a comment perhaps?

File: server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java [hunk 9]
```diff
@@ -270,4 +277,10 @@ protected Set<String> responseParams(RestApiVersion restApiVersion) {
         return responseParams();
     }
 
+    protected void setErrorTraceTransportHeader(RestRequest r) {
+        // set whether data nodes should send back stack trace based on the `error_trace` query parameter
+        if (threadContext != null) {
+            threadContext.putHeader("error_trace", r.param("error_trace", ERROR_TRACE_DEFAULT));
+        }
+    }
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java:285]: There's a couple of problems with this approach, the thread context being mutable (the setter could be called multiple times in theory) and the instanceof check in ActionModule. It isn't the cleanest way. That said, before looking into alternatives, I'd look for core/infra review on this and get help there.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 8 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:522]: Updated comment and gh description

File: server/src/main/java/org/elasticsearch/action/ActionModule.java [hunk 10]
```diff
@@ -825,6 +826,9 @@ public void initRestHandlers(Supplier<DiscoveryNodes> nodesInCluster, Predicate<
         Predicate<AbstractCatAction> catActionsFilter = restExtension.getCatActionsFilter();
         Predicate<RestHandler> restFilter = restExtension.getActionsFilter();
         Consumer<RestHandler> registerHandler = handler -> {
+            if (handler instanceof BaseRestHandler baseRestHandler && threadPool != null) {
+                baseRestHandler.setThreadContext(threadPool.getThreadContext());
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/action/ActionModule.java:830]: I don't think we should add a mutable member. We've strived to keep things like rest handlers immutable. They should be stateless.

The way we've handled common things to utilize within the rest handlers before is to  pass them in to handleRequest. This is why the NodeClient is passed there. Could that approach be used? If so, we should do that as a separate change because it will affect the signature of all rest handlers.

Comment (rjernst) [reply server/src/main/java/org/elasticsearch/action/ActionModule.java:830]: What do you mean by "transport headers"? Headers are part of http requests, transport protocol doesn't have any such concept. If you mean using thread context to pass additional information to transport requests, why wouldn't we adjust the transport requests? These are internal and can change freely.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/ActionModule.java:830]: The idea of using the context was motivated by us having a bunch of spots where we eventually want to fix the same thing. The second most important one after this is errors in bulk responses.
Since we already have this as a generic header on all REST requests we figured it might be ok to use the thread context to propagate this information generically as well.
It's also just a lot easier to do it this way for us just from the mechanics of our code. We have so many different transport APIs, it would require some effort fixing all of them :)

Comment (piergm) [reply server/src/main/java/org/elasticsearch/action/ActionModule.java:830]: Keep me honest here, but in OutboundMessage we have the writeVariableHeader method, that serialises `ThreadContext.defaultHeader` to the wire, so that every transport message has, besides the request "body" also headers from the threadpool context. 
I agree another possible solution would be to not use the header but instead change the transport request but I wanted to build a more general approach so that we can use the same mechanism in the future for other endpoints.
I think this should not be a transport request change, since both request and response can be the exact same. We just need to inform the datanode that we don't want stack trace and that (IMO) can be done via headers.

Comment (piergm) [reply server/src/main/java/org/elasticsearch/action/ActionModule.java:830]: > The way we've handled common things to utilize within the rest handlers before is to pass them in to handleRequest. This is why the NodeClient is passed there. Could that approach be used? If so, we should do that as a separate change because it will affect the signature of all rest handlers.

Actually this is easier than expected, thanks for the input, we have threadpool directly in the NodeClient so I can simply use that 😄

File: server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java [hunk 11]
```diff
@@ -270,4 +272,10 @@ protected Set<String> responseParams(RestApiVersion restApiVersion) {
         return responseParams();
     }
 
+    protected void setErrorTraceTransportHeader(RestRequest r, ThreadContext c) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java:275]: this does not access any state of the handler, does it? Is it supposed to be a static utility method then?

File: server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java [hunk 12]
```diff
@@ -44,6 +45,7 @@
 @ServerlessScope(Scope.PUBLIC)
 public class RestMultiSearchAction extends BaseRestHandler {
     private static final Set<String> RESPONSE_PARAMS = Set.of(RestSearchAction.TYPED_KEYS_PARAM, RestSearchAction.TOTAL_HITS_AS_INT_PARAM);
+    private static final String ERROR_TRACE_DEFAULT = String.valueOf(RestController.ERROR_TRACE_DEFAULT);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java:48]: is this still used?

File: server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java [hunk 13]
```diff
@@ -2928,6 +2928,35 @@ public void testSlicingBehaviourForParallelCollection() throws Exception {
...
+                }
+            }
+        };
+        Exception e = new Exception();
+        e.fillInStackTrace();
+        assertThat(e.getStackTrace().length, is(not(0)));
+        listener.onFailure(e);
+        listener = service.maybeWrapListenerForStackTrace(listener);
+        isWrapped.set(true);
+        listener.onFailure(e);
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java:2957]: the functionality tested here seems easy enough to be tested without starting up a node? Could we move this test to SearchServiceTests? Does it really need a full blown instance of SearchService?

**Review by javanna — COMMENTED** [review]
some more comments, getting closer!

File: server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java (hunk 11 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java]: Done!

File: server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java (hunk 12 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/action/search/RestMultiSearchAction.java]: Removed

File: server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java (hunk 13 above)
Comment (piergm) [reply server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java]: Moved to SearchServiceTests :D

File: server/src/main/java/org/elasticsearch/action/ActionModule.java (hunk 10 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/action/ActionModule.java]: @rjernst I think I addressed the main concern you had about rest handlers immutability and since the implementation does not need signature changes for all the handlers I think we can avoid opening a different PR.
One question I have is if you are okay with the usage we did of ThreadContext.

File: server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java [hunk 14]
```diff
@@ -270,4 +272,10 @@ protected Set<String> responseParams(RestApiVersion restApiVersion) {
         return responseParams();
     }
 
+    protected static void setErrorTraceTransportHeader(RestRequest r, ThreadContext c) {
+        // set whether data nodes should send back stack trace based on the `error_trace` query parameter
+        if (c != null) {
+            c.putHeader("error_trace", r.param("error_trace", ERROR_TRACE_DEFAULT));
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java:278]: Why are we setting the default? Aren't we now blowing up the size of every transport message for the default use case?

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 15]
```diff
@@ -506,7 +508,32 @@ protected void doClose() {
...
+                l.onFailure(e);
+            });
+        }
+        return listener;
+    }
+
     public void executeDfsPhase(ShardSearchRequest request, SearchShardTask task, ActionListener<SearchPhaseResult> listener) {
+        listener = maybeWrapListenerForStackTrace(listener);
         final IndexShard shard = getShard(request);
         rewriteAndFetchShardRequest(shard, request, listener.delegateFailure((l, rewritten) -> {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:538]: since we are actually wrapping the listener here anyway, should we just manually wrap it once maybe?
We have a capturing lambda for `delegateFailure` anyway, so maybe just save heap and indirection and go `new ActionListener() {...}` and override both methods by hand?

**Review by original-brownbear — COMMENTED** [review]
Two comments around avoiding potentially small regressions here :) 
PS: Sorry for the late review!

File: server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java (hunk 14 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java]: removed from header if error_trace is false and added transport version to set the default when reading it in https://github.com/elastic/elasticsearch/pull/118266/commits/cf16266dea83b2d396385d041b30bd09ea5e66f0

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 15 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:544]: After the changes in https://github.com/elastic/elasticsearch/pull/118266/commits/cf16266dea83b2d396385d041b30bd09ea5e66f0 I'd rather not, we would need to duplicate also the version checks and I am not sure that would result clean.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 16]
```diff
@@ -0,0 +1,209 @@
...
+        searchRequest.addParameter("error_trace", "true");
+        searchRequest.addParameter("keep_on_completion", "true");
+        Map<String, Object> responseEntity = performRequestAndGetResponseEntity(searchRequest);
+        String asyncExecutionId = (String) responseEntity.get("id");
+        Request request = new Request("GET", "/_async_search/" + asyncExecutionId);
+        request.addParameter("error_trace", "true");
+        while (responseEntity.get("is_running") instanceof Boolean isRunning && isRunning) {
+            responseEntity = performRequestAndGetResponseEntity(request);
+        }
+        assertTrue(transportMessageHasStackTrace.get());
```
Comment (javanna) [inline x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:120]: Why do we get the stacktrace here via get async search? Would be worth to perhaps add a couple of comments to clarify the behaviour here?

**Review by javanna — APPROVED** [review]
Left a couple of comments and questions, LGTM otherwise

File: server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java [hunk 17]
```diff
@@ -270,4 +271,13 @@ protected Set<String> responseParams(RestApiVersion restApiVersion) {
         return responseParams();
     }
 
+    protected static void setErrorTraceTransportHeader(RestRequest r, ThreadContext c) {
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java:274]: Make sense, moved to ThreadContext and made it non-static :D

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 18]
```diff
@@ -506,7 +510,36 @@ protected void doClose() {
...
+     * @param listener       the action listener to be wrapped
+     * @param version        channel version of the request
+     * @return the wrapped action listener
+     */
+    <T> ActionListener<T> maybeWrapListenerForStackTrace(ActionListener<T> listener, TransportVersion version) {
+        String header = "true";
+        if (version.onOrAfter(ERROR_TRACE_IN_TRANSPORT_HEADER)) {
+            header = getThreadPool().getThreadContext().getHeaderOrDefault("error_trace", "false");
+        }
+        if (header.equals("false")) {
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:529]: Using Boolean.parseBoolean now

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 19]
```diff
@@ -506,7 +510,36 @@ protected void doClose() {
...
+     * node if the `error_trace` header is set to {@code false}. Upon reading we
+     * default to {@code true} to maintain the same behavior as before the change,
+     * due to older nodes not being able to specify whether it needs stack traces.
+     *
+     * @param <T>            the type of the response
+     * @param listener       the action listener to be wrapped
+     * @param version        channel version of the request
+     * @return the wrapped action listener
+     */
+    <T> ActionListener<T> maybeWrapListenerForStackTrace(ActionListener<T> listener, TransportVersion version) {
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:524]: Done!

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 20]
```diff
@@ -0,0 +1,209 @@
...
+        indexRandom(
+            true,
+            prepareIndex("test1").setId("1").setSource("field", "foo"),
+            prepareIndex("test2").setId("10").setSource("field", 5)
+        );
+        refresh();
+    }
+
+    public void testAsyncSearchFailingQueryErrorTraceDefault() throws IOException {
+        transportMessageHasStackTrace = new AtomicBoolean();
```
[the remark this answers is not in the document]
Comment (piergm) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:72]: The atomic boolean is used inside the wrapped listener when we call setupMessageListener() before the test run, in order not to assert on a previous test run we want to make sure that it's a new instance every time.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java (hunk 16 above)
Comment (piergm) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:120]: We don't get stack traces here, this is a check to see if it was transmitted from the data node to the coordinating node.
I'll add comments to clarify this :D

**Comment by piergm** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/118969)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 21]
```diff
@@ -0,0 +1,209 @@
...
+            """);
+        searchRequest.addParameter("error_trace", "true");
+        searchRequest.addParameter("keep_on_completion", "true");
+        Map<String, Object> responseEntity = performRequestAndGetResponseEntity(searchRequest);
+        String asyncExecutionId = (String) responseEntity.get("id");
+        Request request = new Request("GET", "/_async_search/" + asyncExecutionId);
+        request.addParameter("error_trace", "true");
+        while (responseEntity.get("is_running") instanceof Boolean isRunning && isRunning) {
+            responseEntity = performRequestAndGetResponseEntity(request);
+        }
```
[the remark this answers is not in the document]
Comment (javanna) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:123]: I did not mean to imply that sleep is a good solution, I wonder if the sleep ends up slowing down the test and how much. We can maybe finetune this as a followup

[the remark this answers is not in the document]
Comment (piergm) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:123]: From my local tests I saw that with 0ms of wait_for_completion_timeout and 1 second sleep we always get back the response with the first GET /_async_search. So it should not slow down the test too much IMO. But I am open to finetune it 😄

**Comment by piergm** [comment]
Just to remove the backport_pending label. Thanks for the ping, removed.
