### PR TITLE
8.16][ML] Don't make request on older nodes which don't have the ml cache info action

### LINKED ISSUE #117206: [CI] UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Start scroll in mixed cluster on upgraded node that we will continue after upgrade} failing
**Build Scans:**
- [elasticsearch-periodic #4960 / 8.1.3_bwc](https://gradle-enterprise.elastic.co/s/ubrwsn4jd64m6)
- [elasticsearch-periodic #4900 / 8.1.3_bwc](https://gradle-enterprise.elastic.co/s/m4iw3pyw6cnta)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:rolling-upgrade:v8.1.3#twoThirdsUpgradedTest" -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/100_analytics_usage/Basic test for usage stats on analytics indices}" -Dtests.seed=31D5B83898963B81 -Dtests.bwc=true -Dtests.locale=en-SD -Dtests.timezone=Australia/Currie -Druntime.java=23
```

**Applicable branches:**
8.16

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Dmixed_cluster%2F10_basic%2FStart%20scroll%20in%20mixed%20cluster%20on%20upgraded%20node%20that%20we%20will%20continue%20after%20upgrade%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [mixed_cluster/100_analytics_usage:64]: field [analytics.stats.cumulative_cardinality_usage] is not greater than [$cumulative_cardinality_usage]
Expected: a value greater than <1>
     but: <1> was equal to <1>
```

**Issue Reasons:**
- [8.16] 2 failures in test test {p0=mixed_cluster/10_basic/Start scroll in mixed cluster on upgraded node that we will continue after upgrade} (0.4% fail rate in 468 executions)
- [8.16] 2 failures in step 8.1.3_bwc (15.4% fail rate in 13 executions)
- [8.16] 2 failures in pipeline elasticsearch-periodic (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by davidkyle**
Backport of #116236

Closes #117206, #117205, #117204

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportMlMemoryAction.java [hunk 1]
```diff
@@ -106,7 +107,11 @@ protected void masterOperation(
                 .setTimeout(request.ackTimeout())
                 .execute(delegate.delegateFailureAndWrap((delegate2, nodesStatsResponse) -> {
                     TrainedModelCacheInfoAction.Request trainedModelCacheInfoRequest = new TrainedModelCacheInfoAction.Request(
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportMlMemoryAction.java:109]: Its really weird that the action itself just doesn't have a min_transport version :/
