### PR TITLE
Make AbstractSimpleTransportTestCase#testTransportStats(WithException) tolerant of version bumps

### LINKED ISSUE #139861: [CI] SimpleSecurityNetty4ServerTransportTests testTransportStats failing
**Build Scans:**
- [elasticsearch-intake #32648 / part4](https://gradle-enterprise.elastic.co/s/pvberesuner5k)
- [elasticsearch-intake #32606 / part4](https://gradle-enterprise.elastic.co/s/6zzekmf7cmyyo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testTransportStats" -Dtests.seed=AB2B7E60CC47270E -Dtests.locale=ff-Adlm-LR -Dtests.timezone=US/Mountain -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTransportStats'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<35> but was:<36>
```

**Issue Reasons:**
- [9.1] 2 consecutive failures in step part4
- [9.1] 2 consecutive failures in pipeline elasticsearch-intake
- [9.1] 2 failures in test testTransportStats (6.5% fail rate in 31 executions)
- [9.1] 2 failures in step part4 (100.0% fail rate in 2 executions)
- [9.1] 2 failures in pipeline elasticsearch-intake (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139862: [CI] SimpleSecurityNetty4ServerTransportTests testTransportStatsWithException failing
**Build Scans:**
- [elasticsearch-intake #32650 / part4](https://gradle-enterprise.elastic.co/s/vpjzow2gvn7ae)
- [elasticsearch-intake #32648 / part4](https://gradle-enterprise.elastic.co/s/pvberesuner5k)
- [elasticsearch-intake #32606 / part4](https://gradle-enterprise.elastic.co/s/6zzekmf7cmyyo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testTransportStatsWithException" -Dtests.seed=FBAA75D8775D59DE -Dtests.locale=kab -Dtests.timezone=Europe/Podgorica -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTransportStatsWithException'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<35> but was:<36>
```

**Issue Reasons:**
- [9.1] 2 consecutive failures in test testTransportStatsWithException
- [9.1] 3 consecutive failures in step part4
- [9.1] 3 consecutive failures in pipeline elasticsearch-intake
- [9.1] 3 failures in test testTransportStatsWithException (9.4% fail rate in 32 executions)
- [9.1] 3 failures in step part4 (100.0% fail rate in 3 executions)
- [9.1] 3 failures in pipeline elasticsearch-intake (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139863: [CI] SimpleNetty4TransportTests testTransportStatsWithException failing
**Build Scans:**
- [elasticsearch-intake #32650 / part1](https://gradle-enterprise.elastic.co/s/fo3iwfaqhtb72)
- [elasticsearch-intake #32651 / part1](https://gradle-enterprise.elastic.co/s/44cfcfmpo44vs)
- [elasticsearch-intake #32648 / part1](https://gradle-enterprise.elastic.co/s/p454jl7tpv4pm)
- [elasticsearch-intake #32606 / part1](https://gradle-enterprise.elastic.co/s/w2t6ai4a5wwb6)

**Reproduction Line:**
```
./gradlew ":modules:transport-netty4:test" --tests "org.elasticsearch.transport.netty4.SimpleNetty4TransportTests.testTransportStats" -Dtests.seed=AF76B83549729F9F -Dtests.locale=ga -Dtests.timezone=Etc/GMT+6 -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.transport.netty4.SimpleNetty4TransportTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTransportStatsWithException'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<35> but was:<36>
```

**Issue Reasons:**
- [9.1] 2 consecutive failures in test testTransportStatsWithException
- [9.1] 4 consecutive failures in step part1
- [9.1] 4 consecutive failures in pipeline elasticsearch-intake
- [9.1] 4 failures in test testTransportStatsWithException (6.1% fail rate in 66 executions)
- [9.1] 4 failures in step part1 (100.0% fail rate in 4 executions)
- [9.1] 4 failures in pipeline elasticsearch-intake (100.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139864: [CI] SimpleNetty4TransportTests testTransportStats failing
**Build Scans:**
- [elasticsearch-intake #32650 / part1](https://gradle-enterprise.elastic.co/s/fo3iwfaqhtb72)
- [elasticsearch-intake #32652 / part1](https://gradle-enterprise.elastic.co/s/mldtrq5yw5yhy)
- [elasticsearch-intake #32651 / part1](https://gradle-enterprise.elastic.co/s/44cfcfmpo44vs)
- [elasticsearch-intake #32648 / part1](https://gradle-enterprise.elastic.co/s/p454jl7tpv4pm)
- [elasticsearch-intake #32606 / part1](https://gradle-enterprise.elastic.co/s/w2t6ai4a5wwb6)

**Reproduction Line:**
```
./gradlew ":modules:transport-netty4:test" --tests "org.elasticsearch.transport.netty4.SimpleNetty4TransportTests.testTransportStats" -Dtests.seed=AF76B83549729F9F -Dtests.locale=ga -Dtests.timezone=Etc/GMT+6 -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.transport.netty4.SimpleNetty4TransportTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTransportStats'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<35> but was:<36>
```

**Issue Reasons:**
- [9.1] 3 consecutive failures in test testTransportStats
- [9.1] 5 consecutive failures in step part1
- [9.1] 5 consecutive failures in pipeline elasticsearch-intake
- [9.1] 5 failures in test testTransportStats (7.5% fail rate in 67 executions)
- [9.1] 5 failures in step part1 (100.0% fail rate in 5 executions)
- [9.1] 5 failures in pipeline elasticsearch-intake (100.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
A few tests have failed because the build version string became one character longer, this PR attempts to account for the variability in the version string length so it doesn't happen again.

I will un-mute the broken tests in 9.1.10 in the backport PR

Fixes #139864
Fixes #139863
Fixes #139862
Fixes #139861

Please confirm that I've added all the relevant versions for back-porting

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java [hunk 1]
```diff
@@ -2892,19 +2896,63 @@ public void handleException(TransportException exp) {
...
+     * <p>
+     * A handshake request body includes the build version as a string, so its length depends on
+     * the version of the sender.
+     *
+     * @see OutboundHandler#sendRequest
+     * @return The length of a handshake request sent by this version of the software in bytes
+     */
+    private long sizeOfHandshakeRequest() {
+        return Build.current().version().length() + 55;
+    }
```
Comment (nicktindall) [inline test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java:2923]: These are specific to the TcpTransport, but as far as I know we don't plan on having another type of transport anytime in the near future.

File: test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java [hunk 2]
```diff
@@ -2762,21 +2763,23 @@ public void handleException(TransportException exp) {
                 TransportRequestOptions.EMPTY,
                 transportResponseHandler
             );
+            final int sizeOfTestRequest = 59;
+            final int sizeOfTestResponse = 25;
```
Comment (nicktindall) [inline test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java:2767]: I assume it's fine to not itemise these values any further?

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks Nick

**Comment by nicktindall** [comment]
Skipped serverless checks because the build seems unrelatedly broken

**Comment by nicktindall** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/140148)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
