### PR TITLE
Reject mappings that (eventually) set dimension and metric in the same field

### LINKED ISSUE #138044: Invalid passthrough object the mixes dimensions and metrics fields
### Elasticsearch Version

main, 9.x, 8.19

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

It is possible to create an invalid mapping that has defined a passthrough object that is a time series dimension and one of its nested objects is a time series metric.

### Steps to Reproduce

For example:
```
PUT invalid-mapping-index
{
  "mappings": {
    "properties": {
      "attributes": {
          "type": "passthrough",
          "time_series_dimension": true,
          "priority": 20,
          "properties": {
            "my-metric": {
              "type": "double",
              "time_series_metric": "gauge"
            }
          }
      }
    }
  }
}
```

A draft unit test to capture this could be added to `PassThroughObjectMapperTests`:
```
    public void testMetricSubFieldOfPassthroughDimension() throws IOException {
        MapperException exception = expectThrows(MapperException.class, () -> createMapperService(mapping(b -> {
            b.startObject("labels").field("type", "passthrough").field("priority", "0");
            {
                b.startObject("properties");
                b.startObject("dim").field("type", "long").field("time_series_metric", "counter").endObject();
                b.endObject();
            }
            b.endObject();
        })));
    }
```

### Notes

⚠️ When fixing this we need to see how a cluster that already has an invalid mapping and gets upgraded to the fixed version behaves.

### PR DESCRIPTION
**Pull request by gmarouli**
In this PR we add a check that will reject the following mapping:
```
PUT my-index-2
{
  "mappings": {
    "properties": {
      "attributes": {
          "type": "passthrough",
          "time_series_dimension": true,
          "priority": 20,
          "properties": {
            "attributes.kube_job_status_active": {
              "type": "double",
              "time_series_metric": "gauge"
            }
          }
      }
    }
  }
}
```

This mapping was rejected when assertions were enabled, but on production environments it was not checked properly. 

The problem is that we were checking that a field cannot be both a dimension and a metric during parsing. When the mapping is first parsed the `attributes.kube_job_status_active` does not explicitly list `"time_series_dimension": true` so it passes the check, then during building the mappers we do add it but we do not recheck it then.

Now we check this when we build a `NumberFieldMapper`.

Fixes: https://github.com/elastic/elasticsearch/issues/138044

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java [hunk 1]
```diff
@@ -2316,6 +2316,17 @@ public void doValidate(MappingLookup lookup) {
                 TimeSeriesParams.TIME_SERIES_DIMENSION_PARAM + " can't be configured in nested field [" + fullPath() + "]"
             );
         }
+        if (dimension && metricType != null) {
+            throw new IllegalArgumentException(
+                "["
+                    + TimeSeriesParams.TIME_SERIES_DIMENSION_PARAM
+                    + "] and ["
+                    + TimeSeriesParams.TIME_SERIES_METRIC_PARAM
+                    + "] cannot be set in conjunction with each other ["
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java:2325]:
```suggestion
                    + "] cannot be set for the same field ["
```

**Review by kkrik-es — APPROVED** [review]
Nice, that was quick.
