### PR TITLE
SnapshotShardSizeInfo should prefer default value when provided

### LINKED ISSUE #63376: Test failure in CI due to tripping an assertion in DiskThresholdDecider
**Build scan**: https://gradle-enterprise.elastic.co/s/pvza4lbmqvddk

**Repro line**: `./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testAutoFollow" -Dtests.seed=D31F9C6068CCF791 -Dtests.security.manager=true -Dtests.locale=es-BO -Dtests.timezone=Pacific/Bougainville **-Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: `7.x`

**Failure history**: No other failures in the history in build-stats, but the failure does not seem to be due to the test itself.

**Failure excerpt**:
Failure is due to tripping [an assertion in `DiskThresholdDecider`](https://github.com/elastic/elasticsearch/blob/dd5ec83c99cac5fcb78b5cc2607e12f6023bdf9c/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java#L275).

Stack Trace:
```
java.lang.AssertionError: -1	
	at __randomizedtesting.SeedInfo.seed([D31F9C6068CCF791]:0)	
	at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDecider.canAllocate(DiskThresholdDecider.java:275)	
	at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:73)	
	at org.elasticsearch.gateway.PrimaryShardAllocator.buildNodesToAllocate(PrimaryShardAllocator.java:325)	
	at org.elasticsearch.gateway.PrimaryShardAllocator.makeAllocationDecision(PrimaryShardAllocator.java:138)	
	at org.elasticsearch.gateway.BaseGatewayShardAllocator.allocateUnassigned(BaseGatewayShardAllocator.java:58)	
	at org.elasticsearch.gateway.GatewayAllocator.innerAllocatedUnassigned(GatewayAllocator.java:154)	
	at org.elasticsearch.gateway.GatewayAllocator.allocateUnassigned(GatewayAllocator.java:143)	
	at org.elasticsearch.cluster.routing.allocation.AllocationService.allocateExistingUnassignedShards(AllocationService.java:448)	
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:432)	
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:400)	
	at org.elasticsearch.cluster.routing.BatchedRerouteService$1.execute(BatchedRerouteService.java:112)	
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)	
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702)	
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324)	
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219)	
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73)	
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)	
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)	
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)	
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by tlrx**
In #61906 we agreed on always providing the default value `ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE` when the `SnasphotInfoService` failed to retrieve the exact size for a given snapshot shard. The motivation was to allow the shard allocation to move forward in case of failures (so that the unassigned shard does not get stuck in an unassigned state for too long) while relying on the fallback values for shard sizes. 

Sadly a bug in the `SnapshotShardSizeInfo#getShardSize(ShardRouting, long)` makes the default value to be ignored when the snapshot shard size retrieval previously failed, returning `ShardRouting.UNAVAILABLE_EXPECTED_SHARD_SIZE` instead of the provided default value. With `DiskThresholdDecider` also not relying on the provided default value this triggers some assertion like in #63376 which helped us to spot the bug.

Note that we'd like to add more test to the `DiskThresholdDecider` as suggested in https://github.com/elastic/elasticsearch/pull/61906#pullrequestreview-502046246

Closes #63376

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM (except that Checkstyle is unhappy)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardSizeInfo.java [hunk 1]
```diff
@@ -48,6 +48,7 @@ public Long getShardSize(ShardRouting shardRouting) {
 
     public long getShardSize(ShardRouting shardRouting, long fallback) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotShardSizeInfo.java:49]: maybe rename this to `getFetchedShardSize`? I am not too fond of having two methods with same name and a fallback argument that behaves differently (thinking of the `!= null` assertion meaning this is only legal to call when size has been fetched).

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardSizeInfo.java (hunk 1 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotShardSizeInfo.java:49]: I think the assertion I added is too optimistic, there are no guarantee that the information has been fetched. I removed it.

**Comment by tlrx** [comment]
@elasticmachine run  elasticsearch-ci/packaging-sample-windows

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by tlrx** [comment]
Thanks David and Henning!
