### PR TITLE
Expand wildcards to closed indices in /_cat/indices

### LINKED ISSUE #16419: Indices cat API doesn't list closed indices when filtered
Hi,

With the `indices` cat API, I can list my indices, either *open* or *close*.

```
→ curl http://127.0.0.1:9200/_cat/indices
       close partner_results-20150930
yellow open  partner_requests-20150929     1 1     17     0 230.3kb 230.3kb
yellow open  partner_results-20151102      5 1   4311     0   1.5mb   1.5mb
yellow open  search_requests-20150902      5 1     10     0  51.3kb  51.3kb
```

If I filter my results, I no longer see *close* indices : 

```
→ curl http://127.0.0.1:9200/_cat/indices/\*_results-\*
yellow open  partner_results-20151102      5 1   4311     0   1.5mb   1.5mb
```

I didn't find the documentation about that so I don't know if it a bug or an undocumented behavior.

I thought there might be an argument for `/_cat/indices` to show `all/open/close` indices, but I haven't found anything.

### LINKED ISSUE #17395: /_cat/indices: race condition/exception thrown when creating/deleting indices rapidly
**Elasticsearch Versions**:
2.1.x - 2.2.x

**JVM Version**:
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

**Description of the problem including expected versus actual behavior**:

It looks like if you create and delete indices very rapidly you can sometimes end up getting a 404 index_not_found_exception from the `/_cat/indices` API. So basically rather than seeing the indices that still exist, you get an exception because one index was created and deleted between when the endpoint resolves indices and then call indices stats api for those indices.

**Steps to reproduce**:

Attached is a script that should hopefully reproduce the problem, but it can take some time (few minutes  depending on the ability of your ES cluster to handle responses :)

[cat-indices-issue.sh.zip](https://github.com/elastic/elasticsearch/files/194945/cat-indices-issue.sh.zip)

The script is Bash. It will run a number of background processes that simply spin creating and then deleting an index with the REST API.  The script waits until the output of `_cat/indices` produces the exception, then exits. **NOTE:** It will clean-up any background processes it creates but won't clean up any test indices that might still exist.

When the script dies, it will produce output like:

```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"testindex3","index":"testindex3"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"testindex3","index":"testindex3"},"status":404}
...output of the script cleaning up after itself...
```

### PR DESCRIPTION
**Pull request by ywelsch**
Closed indices are already displayed when no indices are explicitly selected. This commit ensures that closed indices are also shown when wildcard filtering is used (fixes #16419). It also addresses another issue that is caused by the fact that the cat action is based internally on 3 different cluster states (one when we query the cluster state to get all indices, one when we query cluster health, and one when we query indices stats). We currently fail the cat request when the user specifies a concrete index as parameter that does not exist. The implementation works as intended in that regard. It checks this not only for the first cluster state request, but also the subsequent indices stats one. This means that if the index is deleted before the cat action has queried the indices stats, it rightfully fails. In case the user provides wildcards (or no parameter at all), however, we fail the indices stats as we pass the resolved concrete indices to the indices stats request and fail to distinguish whether these indices have been resolved by wildcards or explicitly requested by the user. This means that if an index has been deleted before the indices stats request gets to execute, we fail the overall cat request (see #17395). The fix is to let the indices stats request do the resolving again and not pass the concrete indices.

Closes #16419
Closes #17395

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 1]
```diff
@@ -77,27 +77,31 @@ public void doRequest(final RestRequest request, final RestChannel channel, fina
...
-                ClusterState state = clusterStateResponse.getState();
-                final IndicesOptions concreteIndicesOptions = IndicesOptions.fromOptions(false, true, true, true);
-                final String[] concreteIndices = indexNameExpressionResolver.concreteIndexNames(state, concreteIndicesOptions, indices);
-                final String[] openIndices = indexNameExpressionResolver.concreteIndexNames(state, IndicesOptions.lenientExpandOpen(), indices);
-                ClusterHealthRequest clusterHealthRequest = Requests.clusterHealthRequest(openIndices);
+                final ClusterState state = clusterStateResponse.getState();
+                final String[] concreteIndices = indexNameExpressionResolver.concreteIndexNames(state, strictExpandIndicesOptions, indices);
+                // concreteIndices should contain exactly the indices in state.metaData() that were selected by clusterStateRequest using
+                // IndicesOptions.strictExpand(). We select the indices again here so that they come in the requested order.
+                assert concreteIndices.length == state.metaData().getIndices().size();
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: can we not read the indices from the cluster state response instead of resolving them manually again? I guess I don't get the order problem...

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java [hunk 2]
```diff
@@ -77,27 +77,31 @@ public void doRequest(final RestRequest request, final RestChannel channel, fina
...
+
+                ClusterHealthRequest clusterHealthRequest = Requests.clusterHealthRequest(indices);
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: maybe add a comment to keep track of the fact that if an index is gone after the cluster state request, subsequent requests will fail with index not found.

**Comment by javanna** [comment]
left a couple of comments, thanks @ywelsch

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 1 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: when you run `/_cat/indices/foo,bar`, the `cat` api currently returns the results in a table where the entries are ordered according to the specified parameters (first `foo`, then `bar`). I did not want to break that behavior with this PR. I just added the comment above to document why we do that.

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 2 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: For the cluster health request that's not true as cluster health requests have hard-coded indices options that negate that effect (`lenientExpandOpen()`). The best we can do is ensure it for the indices stats request (that's what we do).

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 1 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: ok, while using cluster state output elements are ordered in a non deterministic way? I did not know what.

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java (hunk 2 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: right, thanks for clarifying. I am just looking for a way to not lose the research that you have done after we get this in :) a small comment about indices stats that may fail if the index is deleted meanwhile?

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestIndicesAction.java]: I've pushed a commit with more documentation. Can you have another look please?

**Comment by javanna** [comment]
LGTM
