### PR TITLE
SQL: Serialize Intervals and GeoShapes as Strings

### LINKED ISSUE #68439: SQL: transport communication serialization failure
For inter-node communication at transport level, the serialization of `SqlQueryResponse` fails for `GeoShape` and `Interval` instances with an exception similar to the following:

```
[2021-02-03T01:28:55,170][WARN ][o.e.t.OutboundHandler    ] [v7.9.0-1] send message failed [channel: Netty4TcpChannel{localAddress=/127.0.0.1:60026, remoteAddress=/127.0.0.1:60278}]
java.lang.IllegalArgumentException: can not write type [class org.elasticsearch.xpack.sql.expression.literal.geo.GeoShape]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:824) ~[elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.xpack.sql.action.SqlQueryResponse.writeTo(SqlQueryResponse.java:141) ~[?:?]
	at org.elasticsearch.transport.OutboundMessage.writeMessage(OutboundMessage.java:87) ~[elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:64) ~[elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:159) ~[elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:144) ~[elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.OutboundHandler$SendContext.get(OutboundHandler.java:197) [elasticsearch-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler$WriteOperation.buffer(Netty4MessageChannelHandler.java:213) [transport-netty4-client-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.doFlush(Netty4MessageChannelHandler.java:147) [transport-netty4-client-7.9.0.jar:7.9.0]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.flush(Netty4MessageChannelHandler.java:117) [transport-netty4-client-7.9.0.jar:7.9.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

This happens because these `NamedWriteable` instances are attempted to be serialized as generic values.

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/68439.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java [hunk 1]
```diff
@@ -126,4 +129,25 @@ private static SqlQueryResponse createResponse(SqlQueryRequest request, ZoneId z
...
+            return r.toString();
+        } else if (r instanceof Interval) {
+            if (mode == CLI) {
+                return r.toString();
+            } else {
+                return ((Interval) r).value();
+            }
+        }
+
+        return r;
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java:151]: Minor nit to eliminate the number of `return`s is to assign the new value to r and return it instead:

```suggestion
        if (r instanceof GeoShape) {
            r = r.toString();
        } else if (r instanceof Interval) {
            if (mode == CLI) {
                r = r.toString();
            } else {
                r = ((Interval) r).value();
            }
        }

        return r;
```

**Review by costin — APPROVED** [review]
LGTM - a small update to a somewhat bigger problem.
Likely in the future we should move away from serializing `NamedWritable`s in the payload as it offers no benefit to the consumer (RestAction).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java [hunk 2]
```diff
@@ -126,4 +129,25 @@ private static SqlQueryResponse createResponse(SqlQueryRequest request, ZoneId z
...
+    @SuppressWarnings("rawtypes")
+    private static Object value(Object r, Mode mode) {
+        /*
+         * Intervals and GeoShape instances need to be serialized (as in StreamInput/Ouput serialization) as Strings
+         * since SqlQueryResponse creation doesn't have access to GeoShape nor Interval classes to make the decision
+         * so, we flatten them as Strings before being serialized.
+         * CLI gets a special treatment see {@link org.elasticsearch.xpack.sql.action.SqlQueryResponse#value()}
+         */ 
+        if (r instanceof GeoShape) {
+            r = r.toString();
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java:142]: Minor, but I'd prefer a new variable declared as String, instead of assigning to the method arg.

Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlQueryAction.java:142]: Nevermind, missed the generic `return r`.
