### PR TITLE
Close translog writer if exception on write channel

### LINKED ISSUE #29390: [CI] TranslogTests#testFatalIOExceptionsWhileWritingConcurrently failure
A reproducible failure with an assertion error
```
FAILURE 0.42s | TranslogTests.testFatalIOExceptionsWhileWritingConcurrently <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([4E4569681BD5E1BB:198DEEA7190343F8]:0)
   >    at org.elasticsearch.index.translog.TranslogTests.testFatalIOExceptionsWhileWritingConcurrently(TranslogTests.java:1872)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

```
./gradlew :server:test \
  -Dtests.seed=4E4569681BD5E1BB \
  -Dtests.class=org.elasticsearch.index.translog.TranslogTests \
  -Dtests.method="testFatalIOExceptionsWhileWritingConcurrently" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=America/Martinique
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1896/console

### PR DESCRIPTION
**Pull request by jasontedor**
Today we close the translog write tragically if we experience any I/O exception on a write. These tragic closes lead to use closing the translog and failing the engine. Yet, there is one case that is missed which is when we touch the write channel during a read (checking if reading from the writer would put us past what has been flushed). This commit addresses this by closing the writer tragically if we encounter an I/O exception on the write channel while reading. This becomes interesting when we consider that this method is invoked from the engine through the translog as part of getting a document from the translog. This means we have to consider closing the translog here as well which will cascade up into us finally failing the engine.

Note that there is no semantic change to, for example, primary/replica resync and recovery. These actions will take a snapshot of the translog which syncs the translog to disk. If an I/O exception occurs during the sync we already close the writer tragically and once we have synced we do not ever read past the position that was synced while taking the snapshot.

Closes #29390

### CODE REVIEW

**Comment by jasontedor** [comment]
This addresses the test failure in #29390 exactly because the test is asserting that the translog is closed after a tragic event occurred on the writer but because of the missed handling of an I/O exception on the write channel in the read method, the translog will not be closed by the random readOperation that was added to TranslogThread#run.

**Review by dnhatn — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/index/translog/Translog.java [hunk 1]
```diff
@@ -584,7 +584,12 @@ public Operation readOperation(Location location) throws IOException {
             if (current.generation == location.generation) {
                 // no need to fsync here the read operation will ensure that buffers are written to disk
                 // if they are still in RAM and we are reading onto that position
-                return current.read(location);
+                try {
+                    return current.read(location);
+                } catch (final IOException e) {
+                    closeOnTragicEvent(e);
+                    throw e;
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/translog/Translog.java]: The other calls to `closeOnTragicEvent` are all of the form
```
try {
    closeOnTragicEvent(ex);
} catch (final Exception inner) {
    ex.addSuppressed(inner);
}
throw ex;
```

which does not make any sense btw when you look at `closeOnTragicEvent` which already takes care of exceptions that happen during closing. Can you unify the code in this class?

File: server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java [hunk 2]
```diff
@@ -380,16 +380,21 @@ public boolean syncUpTo(long offset) throws IOException {
...
+                    // which is not really important in production but some test can make most strict assumptions
+                    // if we don't fail in this call unless absolutely necessary.
+                    if (position + targetBuffer.remaining() > getWrittenOffset()) {
+                        outputStream.flush();
+                    }
                 }
             }
+        } catch (final IOException e) {
+            closeWithTragicEvent(e);
+            throw e;
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: Here, I think you should adopt the pattern we use throughout the rest of the class, i.e.,

```
try {
    closeWithTragicEvent(e);
} catch (Exception inner) {
    ex.addSuppressed(inner);
}
throw e;
```

so that we get the original cause.

**Review by ywelsch — CHANGES_REQUESTED** [review]
I've left one ask (and one optional ask)

File: server/src/main/java/org/elasticsearch/index/translog/Translog.java (hunk 1 above)
Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/index/translog/Translog.java]: Okay, I would like to do this in an immediate follow-up to this one. For now I pushed: f9a88eb6216155c6b7413fc59d5e0cb18e49aab3

File: server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java (hunk 2 above)
Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: Bah! Thrown off by the fact that the method this is in declares `throws IOException`. I will address.

Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java]: I pushed 8ccaaf374fe4d10b95bba7f501238b5aabbdef27.

**Review by ywelsch — APPROVED** [review]
LGTM
