### PR TITLE
[Transform] Stop transforms at the end of tests

### LINKED ISSUE #122980: [CI] TransformTaskFailedStateIT testStartFailedTransform failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6501 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/qr4eyp7ikazce)
- [elasticsearch-periodic-platform-support #6459 / ubuntu-2004-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/sqoviu77pycac)
- [elasticsearch-periodic-platform-support #6368 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/l7tai6ckesgf2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:transform:qa:single-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT.testStartFailedTransform" -Dtests.seed=7213E9CD69C89547 -Dtests.locale=ff -Dtests.timezone=Atlantic/South_Georgia -Druntime.java=23
```

**Applicable branches:**
9.0

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testStartFailedTransform),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: is an empty collection
     but: <[ht63p8kdTO6B-3058zsN_Q:221091]>
```

**Issue Reasons:**
- [9.0] 3 failures in test testStartFailedTransform (0.4% fail rate in 668 executions)
- [9.0] 3 failures in pipeline elasticsearch-periodic-platform-support (15.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by prwhelan**
Stopping the transform at the end of test, before the reset, can help other tests running in parallel.

Resolve #122980

### CODE REVIEW

File: x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformUpdateIT.java [hunk 1]
```diff
@@ -340,6 +340,9 @@ private void updateTransferRightsTester(boolean useSecondaryAuthHeaders) throws
             Map<?, ?> transformStatsAsMap = getTransformStateAndStats(transformIdCloned);
             assertThat(XContentMapValues.extractValue("stats.documents_indexed", transformStatsAsMap), equalTo(27));
         }, 15, TimeUnit.SECONDS);
+
+        stopTransform(transformId, BASIC_AUTH_VALUE_TRANSFORM_ADMIN_1, true, false);
+        stopTransform(transformIdCloned, BASIC_AUTH_VALUE_TRANSFORM_ADMIN_1, true, false);
```
Comment (darius-vil) [inline x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformUpdateIT.java:369]: No need to `deleteTransform`?

**Review by darius-vil — APPROVED** [review]

File: x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformUpdateIT.java (hunk 1 above)
Comment (prwhelan) [reply x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformUpdateIT.java:369]: I don't think so? But let's add it just to be safe, it'll keep a consistent pattern across the testing frameworks

**Review by benwtrent — COMMENTED** [review]
I am not blocking this change, but generally, if you need to do this, you should add an `@After` teardown type of thing to the tests to clear up any created transforms. Otherwise, if something throws inside the test, the transform will not be cleaned up (idk if we care about this or not).

A common pattern is to have some deque that keeps track of the IDs successfully created and then running through that deque in `@After` to clear up any created transforms.
