### PR TITLE
Fix TDigestState.read CB leaks

### LINKED ISSUE #114194: [CI] EsqlActionBreakerIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4292 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/i2t5dfszsgjvg)
- [elasticsearch-pull-request #34642 / part-3](https://gradle-enterprise.elastic.co/s/jaqnm2rsgc6ko)
- [elasticsearch-pull-request #34343 / part-3](https://gradle-enterprise.elastic.co/s/66cxlakxyj2xc)
- [elasticsearch-periodic-platform-support #4240 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/fi5d462bc7jl6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EsqlActionBreakerIT.testRowStatsProjectGroupByDouble" -Dtests.seed=390913EDBDC5313D -Dtests.locale=szl-Latn-PL -Dtests.timezone=Asia/Famagusta -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.action.EsqlActionBreakerIT'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.action.EsqlActionBreakerIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s2
Expected: <0L>
     but: was <96L>
```

**Issue Reasons:**
- [main] 4 failures in class org.elasticsearch.xpack.esql.action.EsqlActionBreakerIT (0.6% fail rate in 713 executions)
- [main] 2 failures in step part-3 (0.8% fail rate in 247 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (14.3% fail rate in 14 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.8% fail rate in 251 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Closes https://github.com/elastic/elasticsearch/issues/114194

Fixes `TDigestState.read()` CB leak on error on `.reserve()`.

### CODE REVIEW

**Review by bpintea — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TDigestState.java [hunk 1]
```diff
@@ -210,14 +210,19 @@ public static TDigestState read(CircuitBreaker breaker, StreamInput in) throws I
             breaker.addWithoutBreaking(-SHALLOW_SIZE);
             throw e;
         }
-        int n = in.readVInt();
-        if (size > 0) {
-            state.tdigest.reserve(size);
-        }
-        for (int i = 0; i < n; i++) {
-            state.add(in.readDouble(), in.readVLong());
+        try {
```
Comment (iverase) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/TDigestState.java:213]: I would prefer a try / finally block and use a boolean variable to control the outcome of the execution as we do in other places. See https://github.com/elastic/elasticsearch/blob/e2c314eec8bd7190a56f85c52342521491a5098e/server/src/main/java/org/elasticsearch/search/aggregations/metrics/HyperLogLogPlusPlus.java#L74

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateReleasingTests.java [hunk 2]
```diff
@@ -32,14 +36,75 @@ public TDigestStateReleasingTests(TDigestState.Type digestType) {
...
+    public void testCreateOfType() {
+        testCircuitBreakerTrip(circuitBreaker -> TDigestState.createOfType(circuitBreaker, digestType, 100));
+    }
+
+    public void testCreateUsingParamsFrom() {
+        testCircuitBreakerTrip(circuitBreaker -> {
+            try (TDigestState example = TDigestState.createOfType(newLimitedBreaker(ByteSizeValue.ofMb(100)), digestType, 100)) {
+                return TDigestState.createUsingParamsFrom(example);
+            }
+        });
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateReleasingTests.java:48]: If you use the cranky breaker service it'll blow up *randomly* and you can assert that you always freed the memory, no matter the random explosion. I rather like it for this sort of thing.


Which one of your tests hits a the breaker exception you are guarding?

Comment (ivancea) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateReleasingTests.java:48]: > Which one of your tests hits a the breaker exception you are guarding?

The `testReadWithData()`. The reserve is only called when it has data in it. So I added that one explicitly.

About the cranky breaker, I'm not sure we want it to break randomly. This has multiple potential breaking points I wanted to test (Add memory and release on error, on every constructor).

The cranky breaks 1/20 times. If we're fine with this one (The full suite takes around 1 second on my machine), I would leave it as-is. It tests every potential breaking point (_Divided in 16 random seeds_).
Is it too much? Not sure

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TDigestState.java (hunk 1 above)
Comment (ivancea) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TDigestState.java]: Updated. Also, changed the internal catch to a finally too. merging both try-finally in one made the code a bit more complex, so left them separated

Comment (iverase) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TDigestState.java]: Thanks you, that's looks good.

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateReleasingTests.java (hunk 2 above)
Comment (iverase) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateReleasingTests.java:48]: >About the cranky breaker, I'm not sure we want it to break randomly. This has multiple potential breaking points I wanted to test (Add memory and release on error, on every constructor).

That's where the cranky is really good at.

Comment (ivancea) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/TDigestStateReleasingTests.java:49]: Just updated it to use the cranky breaker. It will fail ~1/5 times, so I guess it's ok. I suppose even 1/20 times would be ok for something like this.
I guess I was reinventing the wheel here XD

**Review by iverase — APPROVED** [review]
LGTM

**Review by nik9000 — APPROVED** [review]
