### PR TITLE
Fix ThreadPoolMergeExecutorServiceTests testIORateIsAdjustedForRunningMergeTasks

### LINKED ISSUE #125842: [CI] ThreadPoolMergeExecutorServiceTests testIORateIsAdjustedForRunningMergeTasks failing
**Build Scans:**
- [elasticsearch-periodic #7286 / openjdk24_entitlements_false_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/f7fv2rsrf2mwy)
- [elasticsearch-pull-request #64612 / part-1](https://gradle-enterprise.elastic.co/s/tngdgyw3r5jgm)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.index.engine.ThreadPoolMergeExecutorServiceTests.testIORateIsAdjustedForRunningMergeTasks" -Dtests.seed=9BD0AF493A33E7D -Dtests.jvm.argline="-Des.entitlements.enabled=false" -Dtests.locale=zh-Latn -Dtests.timezone=America/Lima -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.engine.ThreadPoolMergeExecutorServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testIORateIsAdjustedForRunningMergeTasks),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: is <15288239L>
     but: was <18874368L>
```

**Issue Reasons:**
- [main] 2 failures in test testIORateIsAdjustedForRunningMergeTasks (0.3% fail rate in 666 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by albertzaharovits**
Fixes https://github.com/elastic/elasticsearch/issues/125842
Relates https://github.com/elastic/elasticsearch/pull/120869

### CODE REVIEW

**Comment by albertzaharovits** [comment]
The only test failure (https://gradle-enterprise.elastic.co/s/f7fv2rsrf2mwy) was when some merge thread was interrupted...

**Review by henningandersen — COMMENTED** [review]
AFAICS from the test run, the order of things is opposite. The assertBusy below seems to time-out, which then causes us to interrupt the threads.

I think we've not found the root cause here?

**Comment by albertzaharovits** [comment]
>I think we've not found the root cause here?

I haven't figured it out 100% what's happening here, but I've strengthen the assertions that the submitted task was indeed running or aborting before asserting the disk IO rate update on the set of all currently running merge tasks (this should rule out any interference between the loops in the test).

**Comment by albertzaharovits** [comment]
@henningandersen Can you take another look here, please?

File: server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceTests.java [hunk 1]
```diff
@@ -337,31 +339,33 @@ public void testIORateIsAdjustedForRunningMergeTasks() throws Exception {
...
                         // wait to be signalled before completing
                         runMergeSemaphore.acquire();
+                        currentlyRunningOrAbortingMergeTasksSet.remove(mergeTask);
                         return null;
                     }).when(mergeTask).abort();
-                    int activeMergeTasksCount = threadPoolExecutor.getActiveCount();
-                    threadPoolMergeExecutorService.submitMergeTask(mergeTask);
-                    long newIORate = threadPoolMergeExecutorService.getTargetIORateBytesPerSec();
-                    // all currently running merge tasks must be IO throttled
+                    boolean mergeTaskSubmitted = threadPoolMergeExecutorService.submitMergeTask(mergeTask);
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceTests.java:358]: Can we assert that the runSemaphore has no permits here? I think that is an assumption.

**Review by henningandersen — APPROVED** [review]
LGTM

File: server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceTests.java (hunk 1 above)
Comment (albertzaharovits) [reply server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeExecutorServiceTests.java:358]: Pushed https://github.com/elastic/elasticsearch/pull/126058/commits/5db6465dbf0db37361dad686f5730bb375e6d711
