### PR TITLE
Decouple BulkProcessor from ThreadPool

### LINKED ISSUE #26028: BulkProcessor can't be used with empty settings in the high level client
According to [the documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-high-document-bulk.html#java-rest-high-document-bulk-processor), you "only" need to write the following code to create a Rest Bulk Processor:

```java
        ThreadPool threadPool = new ThreadPool(Settings.EMPTY);
        BulkProcessor.Listener listener = new BulkProcessor.Listener() {
            @Override public void beforeBulk(long executionId, BulkRequest request) { }
            @Override public void afterBulk(long executionId, BulkRequest request, BulkResponse response) { }
            @Override public void afterBulk(long executionId, BulkRequest request, Throwable failure) { }
        };

        bulkProcessorDoc = new BulkProcessor.Builder(client.getHlClient()::bulkAsync, listener, threadPool).build();
```

This is actually failing with empty settings as the `ThreadPool` class [is waiting for a `node.name` setting](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L166):

```java
        assert Node.NODE_NAME_SETTING.exists(settings);
```

I think we should either remove the need for the node name when configuring a Client ThreadPool or to document that this is needed for now:

```java
        ThreadPool threadPool = new ThreadPool(Settings.builder().put(Node.NODE_NAME_SETTING.getKey(), "high-level-client").build());
```

I wonder though if the High Level Rest Client itself should not provide OOTB a default ThreadPool with a name like `high-level-client`.

Thoughts?

### PR DESCRIPTION
**Pull request by javanna**
The goal of this PR is to not require to provide a `ThreadPool` when creating a `BulkProcessor`. This way, we make it easier to use the `BulkProcessor` from the high-level REST client.

The initial [idea](https://github.com/elastic/elasticsearch/issues/26028#issuecomment-325412254) around removing the need for passing in a `ThreadPool` to `BulkProcessor` was to require two functions: `BiFunction<Runnable, TimeValue, ScheduledFuture<?>>` to schedule a task and `Function<Runnable, Runnable>` to wrap the command into one that preserves the thread context. When trying that approach, a few issues came up. The flush task is a periodic task (scheduled through `scheduleWithFixedDelay`) and gets executed on the `GENERIC` thread pool rather than `SAME`. Also the `ThreadPool#scheduleWithFixedDelay` method has different semantics compared to the standard `ScheduledThreadPoolExecutor#scheduleWithFixedDelay` when it comes to failures.

The approach I went for in this PR is based on extracting the minimal code that allows to schedule tasks into a new base interface called `Scheduler` which the `BulkProcessor` depends on. `ThreadPool` implements `Scheduler` and enhances it, so that all of the components that already used `BulkProcessor` and had a `ThreadPool` available can keep on doing the same exactly the same way, while the high-level REST client internally creates its own instance of the `Scheduler` (users don't even have to provide it while they previously needed to create the `ThreadPool`), which works exactly as the `ThreadPool` but it doesn't support multiple executors, and shuts it down on close (also it doesn't log anything in case of failures).

This approach allows to not have to reinvent the wheel in the high-level REST client and use the same code that we already have to schedule one-shot and periodic tasks, all without requiring an entire `ThreadPool` which the high-level REST client doesn't need.

Closes #26028

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/threadpool/Scheduler.java [hunk 1]
```diff
@@ -0,0 +1,283 @@
...
+import java.io.IOException;
+import java.util.concurrent.ScheduledExecutorService;
+import java.util.concurrent.ScheduledFuture;
+import java.util.concurrent.ScheduledThreadPoolExecutor;
+import java.util.concurrent.TimeUnit;
+
+/**
+ * Scheduler that allows to schedule one-shot and periodic commands.
+ */
+public class Scheduler extends AbstractComponent implements Closeable {
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/threadpool/Scheduler.java]: I was thinking of an interface that is part of the bulk processor like:
```
interface Scheduler {
  ScheduledFuture<?> schedule(TimeValue delay, String executor, Runnable command);
  Cancellable scheduleWithFixedDelay(Runnable command, TimeValue interval, String executor);
  void shutdown();
}
```

That way core doesn't depend on bulk processor stuff, bulk processor stuff depends on core. Or at least can be adapted into core.

And when we want to work with a ThreadPool we could implement it like:
```
  new Scheduler() {
    ScheduledFuture<?> schedule(TimeValue delay, String executor, Runnable command) {
      return threadPool.schedule(delay, executor, command);
    }

    Cancellable scheduleWithFixedDelay(Runnable command, TimeValue interval) {
      ThreadPool.Cancellable c = threadPool.scheduleWithFixedDelay(threadPool.preserveContext(command), interval, SAME);
      return new Cancellable() {
        void cancel() {c.cancel();}
        boolean isCancelled() {return c.isCancelled();}
    }

    void shutdown() {
      // Do nothing because we don't want to shut down the shared ThreadPool.
    }
  }
```

Is that crazy? It feels like that lets users plug it into whatever scheduling solution they want.

Comment (javanna) [reply core/src/main/java/org/elasticsearch/threadpool/Scheduler.java]: I would prefer if users didn't have to do anything. I did try the interface idea, but I quickly realized that I need the same code in both scheduler impls (the one used by ThreadPool and the one that BulkProcessor uses).

How would you implement scheduleWithFixedDelay in the bulk processor impl? This question led me to the current impl. Some of the reasons are in the description of this PR. From then on, I had to add some more methods to the base class, but in hindsight it kinda makes sense to have the scheduler bits extracted out and shared, I thought.

Comment (nik9000) [reply core/src/main/java/org/elasticsearch/threadpool/Scheduler.java]: Something like:

```
class ThreadPoolExecutorScheduler implements Scheduler {
  private final ScheduledThreadPoolExecutor exec;

  public ScheduledFuture<?> schedule(TimeValue delay, String executor, Runnable command) {
      return exec.schedule(delay, executor, command);
    }

    public Cancellable scheduleWithFixedDelay(Runnable command, TimeValue interval) {
      ScheduledFuture<?> c = threadPool.scheduleWithFixedDelay(command, interval, SAME);
      return new Cancellable() {
        void cancel() {c.cancel();}
        boolean isCancelled() {return c.isCancelled();}
    }

    public void shutdown() {
      exec.shutdown();
    }
  }
```

I really don't want stuff like `Settings` and `AbstractComponent` to make their way too far into the high level rest client if we can help it. I mean, `ThreadPool` is even worse because it is all of those things, so the change as you have it is an improvement.

I think the user doesn't really have to do anything. If the BulkProcessor by default builds it own scheduler building a `ScheduledThreadPoolExecutor` on the fly then great. If they call `builder.withScheduler(ScheduledThreadPoolExecutor)` then we can build a scheduler for them. And if they want ultimate control they can call `builder.withScheduler(Scheduler)`. And we can have a `builder.withSchedulerFromThreadPool(threadPool)` for transport client users.

Comment (nik9000) [reply core/src/main/java/org/elasticsearch/threadpool/Scheduler.java]: Er, I was using bad names in the comment above. Edited.

Comment (nik9000) [reply core/src/main/java/org/elasticsearch/threadpool/Scheduler.java]: Talked with @javanna - the trouble with what I propose is that `ScheduledThreadPoolExecutor` doesn't react the same way to failures as `ThreadPool`. Especially with regards to `scheduleWithFixedDelay` style stuff. In `ThreadPool` we retry even if it fails. `ScheduledThreadPoolExecutor` doesn't. We think.

Comment (javanna) [reply core/src/main/java/org/elasticsearch/threadpool/Scheduler.java]: I think you meant to call `exec.scheduldWithFixedDelay` from `scheduleWithFixedDelay`. The problem is that "If any execution of the task encounters an exception, subsequent executions are suppressed." In our own impl (currently in `ThreadPool`) a failure won't affect subsequent runs, which will still happen. That is the main reason why I didn't go for an interface, and move some more methods to the base impl, which can be shared between ES core and the high-level client. I do see how AbstractComponent is annoying, together with Settings, but that is a problem that we may want to fix in ES core directly and probably just a small downside in the context of this change?

**Comment by nik9000** [comment]
I dunno. I feel like it'd still be cleaner to go with the interface solution and catch `Exception` in the `Runnable` we queue rather than leak make the change this way. I'm torn though, because that feels like a fair bit of duplication. Maybe it is worth it not to leak ES internals into the high level rest client maybe not. I dunno.

I admit I don't like refactoring ThreadPool like this either and I can't really put my finger on why.

I think it might be time to get another reviewer involved to get some fresh ideas.

**Comment by nik9000** [comment]
I dunno. I feel like it'd still be cleaner to go with the interface solution and catch `Exception` in the `Runnable` we queue rather than leak make the change this way. I'm torn though, because that feels like a fair bit of duplication. Maybe it is worth it not to leak ES internals into the high level rest client maybe not. I dunno.

I admit I don't like refactoring ThreadPool like this either and I can't really put my finger on why.

I think it might be time to get another reviewer involved to get some fresh ideas.

**Comment by javanna** [comment]
Given the last linked issue (#26762) I will look at getting rid of the `AbstractComponent` and logging stuff, I didn't realize that would be a problem. That should also address some of your concerns @nik9000 . I'd still try to avoid duplication as much as possible though.

**Comment by javanna** [comment]
@nik9000 this is ready for another round, I succeeded in doing what you suggested. I like it better too. The only downsides is we don't have logged failures from the REST client, as logging in the scheduler was really in the way. All the rest should work the same, without code duplication. Let me know what you think. Also @jasontedor this is ready for you too ;)

**Review by nik9000 — APPROVED** [review]
Looks like an improvement to me. I think it'd be nice to have some javadocs on the static methods.

@jasontedor should probably look at the `ThreadPool` changes as well.

**Review by nik9000 — APPROVED** [review]
Looks like an improvement to me. I think it'd be nice to have some javadocs on the static methods.

@jasontedor should probably look at the `ThreadPool` changes as well.

File: core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 2]
```diff
@@ -361,13 +334,30 @@ public Cancellable scheduleWithFixedDelay(Runnable command, TimeValue interval,
...
+        return scheduler.schedule(new ThreadPool.LoggingRunnable(command), delay.millis(), TimeUnit.MILLISECONDS);
+    }
+
+    @Override
+    public Cancellable scheduleWithFixedDelay(Runnable command, TimeValue interval, String executor) {
+        return new ReschedulingRunnable(command, interval, executor, this,
+                (e) -> {
+                    if (logger.isDebugEnabled()) {
+                        logger.debug((Supplier<?>) () -> new ParameterizedMessage("scheduled task [{}] was rejected on thread pool [{}]",
+                                command, executor), e);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: This log statement does not have `toString` on the command yet the other warn does, can you make them consistent?

File: core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 3]
```diff
@@ -722,27 +715,29 @@ private static boolean awaitTermination(
      * Returns <code>true</code> if the given pool was terminated successfully. If the termination timed out,
      * the service is <code>null</code> this method will return <code>false</code>.
      */
-    public static boolean terminate(ThreadPool pool, long timeout, TimeUnit timeUnit) {
-        if (pool != null) {
+    public static boolean terminate(ThreadPool threadPool, long timeout, TimeUnit timeUnit) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: Can you revert all changes to this method, they are cosmetic?

File: core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 4]
```diff
@@ -376,7 +366,7 @@ public void shutdown() {
         scheduler.shutdown();
         for (ExecutorHolder executor : executors.values()) {
             if (executor.executor() instanceof ThreadPoolExecutor) {
-                ((ThreadPoolExecutor) executor.executor()).shutdown();
+                executor.executor().shutdown();
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: These are cosmetic changes, let's revert them here.

**Review by jasontedor — APPROVED** [review]
I left some nits, otherwise this is so good, so so so good. Thank you for doing this.

File: core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java (hunk 3 above)
Comment (javanna) [reply core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: sure

File: core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java (hunk 4 above)
Comment (javanna) [reply core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: this looks like a good change to me though. It resolves a warning in my IDE caused by the unnecessary cast. Why not keep it?

Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: It’s fine @javanna, pull it in in this one. I would prefer we keep changes like this out of PRs, they can go in separately, I want less to think about when I review.
