### PR TITLE
Fix deadlock in jwt realm

### LINKED ISSUE #99317: Potential deadlock during JWT credentials rotation
We observed a node (running a somewhat nonstandard build of ES in a fairly unusual environment) which was deadlocked while invalidating a JWT credentials cache entry while rotation credentials. It looked like it might be possible to experience the same deadlock in regular ES too.

```
Found one Java-level deadlock:
=============================
"elasticsearch[es-es-search-5577dfb9fd-fcjtw][transport_worker][T#12]":
  waiting for ownable synchronizer 0x000000070826d178, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "elasticsearch[es-es-search-5577dfb9fd-fcjtw][transport_worker][T#20]"

"elasticsearch[es-es-search-5577dfb9fd-fcjtw][transport_worker][T#20]":
  waiting for ownable synchronizer 0x0000000708ff86b8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "elasticsearch[es-es-search-5577dfb9fd-fcjtw][system_critical_read][T#1]"

"elasticsearch[es-es-search-5577dfb9fd-fcjtw][system_critical_read][T#1]":
  waiting for ownable synchronizer 0x000000070826d178, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "elasticsearch[es-es-search-5577dfb9fd-fcjtw][transport_worker][T#20]"
```

<details>
<summary>Expand for more complete stack traces</summary>

```
"elasticsearch[es-es-search-5577dfb9fd-fcjtw][transport_worker][T#12]":
    at jdk.internal.misc.Unsafe.park(java.base@20.0.2/Native Method)
    - parking to wait for  <0x000000070826d178> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(java.base@20.0.2/LockSupport.java:221)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@20.0.2/AbstractQueuedSynchronizer.java:754)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@20.0.2/AbstractQueuedSynchronizer.java:1079)
    at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@20.0.2/ReentrantReadWriteLock.java:738)
    at org.elasticsearch.common.util.concurrent.ReleasableLock.acquire(org.elasticsearch.server@8.11.0-SNAPSHOT/ReleasableLock.java:43)
    at org.elasticsearch.common.cache.Cache$CacheSegment.get(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:199)
    at org.elasticsearch.common.cache.Cache.get(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:350)
    at org.elasticsearch.common.cache.Cache.get(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:345)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm.tryAuthenticateWithCache(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtRealm.java:348)


"elasticsearch[es-es-search-5577dfb9fd-fcjtw][transport_worker][T#20]":
    at jdk.internal.misc.Unsafe.park(java.base@20.0.2/Native Method)
    - parking to wait for  <0x0000000708ff86b8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(java.base@20.0.2/LockSupport.java:221)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@20.0.2/AbstractQueuedSynchronizer.java:754)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@20.0.2/AbstractQueuedSynchronizer.java:990)
    at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@20.0.2/ReentrantLock.java:153)
    at java.util.concurrent.locks.ReentrantLock.lock(java.base@20.0.2/ReentrantLock.java:322)
    at org.elasticsearch.common.util.concurrent.ReleasableLock.acquire(org.elasticsearch.server@8.11.0-SNAPSHOT/ReleasableLock.java:43)
    at org.elasticsearch.common.cache.Cache.invalidateAll(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:529)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm.invalidateJwtCache(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtRealm.java:453)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm.expireAll(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtRealm.java:181)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm$$Lambda$4053/0x0000000101c181f0.reloaded(org.elasticsearch.security@8.11.0-SNAPSHOT/Unknown Source)
    at org.elasticsearch.xpack.security.authc.jwt.JwtSignatureValidator$PkcJwtSignatureValidator.lambda$validate$0(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtSignatureValidator.java:311)
    at org.elasticsearch.xpack.security.authc.jwt.JwtSignatureValidator$PkcJwtSignatureValidator$$Lambda$8830/0x00000001025cdb48.accept(org.elasticsearch.security@8.11.0-SNAPSHOT/Unknown Source)
    at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.11.0-SNAPSHOT/ActionListener.java:177)
    at org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(org.elasticsearch.server@8.11.0-SNAPSHOT/SubscribableListener.java:273)
    at org.elasticsearch.action.support.SubscribableListener.tryComplete(org.elasticsearch.server@8.11.0-SNAPSHOT/SubscribableListener.java:193)
    at org.elasticsearch.action.support.SubscribableListener.addListener(org.elasticsearch.server@8.11.0-SNAPSHOT/SubscribableListener.java:96)
    at org.elasticsearch.action.support.SubscribableListener.addListener(org.elasticsearch.server@8.11.0-SNAPSHOT/SubscribableListener.java:71)
    at org.elasticsearch.xpack.security.authc.jwt.JwkSetLoader.reload(org.elasticsearch.security@8.11.0-SNAPSHOT/JwkSetLoader.java:90)
    at org.elasticsearch.xpack.security.authc.jwt.JwtSignatureValidator$PkcJwtSignatureValidator.validate(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtSignatureValidator.java:292)
    at org.elasticsearch.xpack.security.authc.jwt.JwtSignatureValidator$DelegatingJwtSignatureValidator.validate(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtSignatureValidator.java:144)
    at org.elasticsearch.xpack.security.authc.jwt.JwtAuthenticator.validateSignature(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtAuthenticator.java:101)
    at org.elasticsearch.xpack.security.authc.jwt.JwtAuthenticator.authenticate(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtAuthenticator.java:93)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm.authenticate(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtRealm.java:291)
    at org.elasticsearch.xpack.security.authc.RealmsAuthenticator.lambda$consumeToken$4(org.elasticsearch.security@8.11.0-SNAPSHOT/RealmsAuthenticator.java:147)

"elasticsearch[es-es-search-5577dfb9fd-fcjtw][system_critical_read][T#1]":
    at jdk.internal.misc.Unsafe.park(java.base@20.0.2/Native Method)
    - parking to wait for  <0x000000070826d178> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(java.base@20.0.2/LockSupport.java:221)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@20.0.2/AbstractQueuedSynchronizer.java:754)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@20.0.2/AbstractQueuedSynchronizer.java:990)
    at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(java.base@20.0.2/ReentrantReadWriteLock.java:959)
    at org.elasticsearch.common.util.concurrent.ReleasableLock.acquire(org.elasticsearch.server@8.11.0-SNAPSHOT/ReleasableLock.java:43)
    at org.elasticsearch.common.cache.Cache$CacheSegment.remove(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:293)
    at org.elasticsearch.common.cache.Cache.evictEntry(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:764)
    at org.elasticsearch.common.cache.Cache.evict(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:755)
    at org.elasticsearch.common.cache.Cache.promote(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:746)
    at org.elasticsearch.common.cache.Cache.put(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:470)
    at org.elasticsearch.common.cache.Cache.put(org.elasticsearch.server@8.11.0-SNAPSHOT/Cache.java:457)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm.lambda$processValidatedJwt$4(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtRealm.java:408)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm$$Lambda$7938/0x000000010251aaa8.accept(org.elasticsearch.security@8.11.0-SNAPSHOT/Unknown Source)
    at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.11.0-SNAPSHOT/ActionListener.java:177)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm.lambda$processValidatedJwt$5(org.elasticsearch.security@8.11.0-SNAPSHOT/JwtRealm.java:432)
    at org.elasticsearch.xpack.security.authc.jwt.JwtRealm$$Lambda$7957/0x000000010251cfa0.accept(org.elasticsearch.security@8.11.0-SNAPSHOT/Unknown Source)
    at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.11.0-SNAPSHOT/ActionListener.java:177)
    at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore.lambda$resolveRoles$18(org.elasticsearch.security@8.11.0-SNAPSHOT/NativeRoleMappingStore.java:381)
    at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore$$Lambda$7969/0x000000010251e920.accept(org.elasticsearch.security@8.11.0-SNAPSHOT/Unknown Source)
    at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.11.0-SNAPSHOT/ActionListener.java:177)
    at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore.lambda$loadMappings$0(org.elasticsearch.security@8.11.0-SNAPSHOT/NativeRoleMappingStore.java:140)
    at org.elasticsearch.xpack.security.authc.support.mapper.NativeRoleMappingStore$$Lambda$7989/0x0000000102521370.accept(org.elasticsearch.security@8.11.0-SNAPSHOT/Unknown Source)
    at org.elasticsearch.action.ActionListener$2.onResponse(org.elasticsearch.server@8.11.0-SNAPSHOT/ActionListener.java:177)
    at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(org.elasticsearch.server@8.11.0-SNAPSHOT/ContextPreservingActionListener.java:32)
    at org.elasticsearch.xpack.core.security.ScrollHelper$1.onResponse(org.elasticsearch.xcore@8.11.0-SNAPSHOT/ScrollHelper.java:97)
```

</details>

---

### Symptoms

In this case the node left the cluster and could not rejoin, reporting timeouts. In other cases it might remain a member of the cluster, but some requests to the node will hang.

To diagnose the problem, use `jstack` to take a stack dump of the problematic node, look for reports of a deadlock, and compare the stack traces to the ones listed above.

---

### Workaround

Disable caching for all JWT-type realms:

```
xpack.security.authc.realms.jwt.<realmname>.jwt.cache.ttl: "0m"
```

or 

```
xpack.security.authc.realms.jwt.<realmname>.jwt.cache.size: 0
```

Note that this may have a performance impact.

### PR DESCRIPTION
**Pull request by jakelandis**
This commit fixes the deadlock described in https://github.com/elastic/elasticsearch/issues/99317 for the jwt realm. 
The fix is to ensure that Cache#put and Cache#invalidateAll are mutually exclusive as to not 
trigger the deadlock that can occur in the Cache implementation. (see https://github.com/elastic/elasticsearch/issues/99326)

This commit also renames the variables to make them more obvious as to what they represent. 

Fixes #99317

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java [hunk 1]
```diff
@@ -327,7 +327,7 @@ private void buildThenMaybeCacheRole(
             restrictedIndices,
             listener.delegateFailureAndWrap((delegate, role) -> {
                 if (role != null && tryCache) {
-                    try (ReleasableLock ignored = roleCacheHelper.acquireUpdateLock()) {
+                    try (ReleasableLock ignored = roleCacheHelper.acquireReadLock()) {
```
Comment (jakelandis) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java:330]: this is just a name change, but we should probably see (in a different PR) if this should be a write lock to prevent against deadlock.

**Comment by jakelandis** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc  (issue [unrelated](https://gradle-enterprise.elastic.co/s/7fspelwwporou/console-log?anchor=1855&page=2) and appears transient)

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by ywangd — APPROVED** [review]
LGTM

There are other places where we simply just call `put` and `invalidateAll` without any protection. Also, based on existing patterns, the use of `CacheHelper` is actually not necessary because it is meant to be used only when we need iterate through the cache and JWT realm does not do that. That said, I was totally not aware that `put` an `invalidateAll` can deadlock inside `Cache`. This means we will need to fix other places as well. Not sure whether `Cache.computeIfAbsent` has the same problem and this is also used extensively in the code base.

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/bwc

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java [hunk 2]
```diff
@@ -23,31 +23,33 @@
...
         // iterator but when not iterating we can modify the cache without external locking. When making normal modifications to the cache
-        // the read lock is obtained so that we can allow concurrent modifications; however when we need to iterate over the keys or values
+        // the read lock can obtained so that we can allow concurrent modifications; however when we need to iterate over the keys or values
         // of the cache the write lock must obtained to prevent any modifications.
-        updateLock = new ReleasableLock(lock.readLock());
-        iteratorLock = new ReleasableLock(lock.writeLock());
+        // Note - the write lock is needed for concurrent modifications across Cache#put and Cache#invalidateAll
+        // see https://github.com/elastic/elasticsearch/issues/99326 for additional information
+        readLock = new ReleasableLock(lock.readLock());
+        writeLock = new ReleasableLock(lock.writeLock());
```
Comment (tvernum) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java:39]: Are you sure you want to make this change? The methods were named based on how they're supposed to be used, and that nuance is lost by the name change.

The new names imply that you need to obtain the read-lock to read from the cache and the write-lock in order to modify the cache. We don't want people to have that impression: locking for basic reads and/or obtaining exclusive locks for all simply writes is going to kill performance.

If I understand the analysis in https://github.com/elastic/elasticsearch/issues/99326 correctly, the issue is that we need to take the exclusive (write) lock in order to call `invalidateAll`, I think the we should have names that reflect that behaviour rather than the misleading names of `read` and `write`

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java [hunk 3]
```diff
@@ -403,7 +403,7 @@ private void processValidatedJwt(
                     () -> format("Realm [%s] roles resolved [%s] for principal=[%s].", name(), join(",", user.roles()), principal)
                 );
                 if (isCacheEnabled()) {
-                    try (ReleasableLock ignored = jwtCacheHelper.acquireUpdateLock()) {
+                    try (ReleasableLock ignored = jwtCacheHelper.acquireWriteLock()) {
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java:406]: Per my other comment, I think this is wrong. The `Cache.put` should use the reentrant lock not the exclusive lock. Only the `invalidateAll` needs exclusive access.

Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java:406]: Thanks Tim. This makese sense. Sorry I didn't think it carefully enough. @jakelandis I will go ahead and make changes to this PR. I hope you don't mind. I'll iterate it with Tim to hopefully get this PR merged during my day time.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java (hunk 2 above)
Comment (ywangd) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java]: I think we can leave the name discussion in a future PR. So I have restored the original names in this PR to focus on the actual fix. Hope this works for both of you. Thanks!

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealmAuthenticateTests.java [hunk 4]
```diff
@@ -530,4 +533,82 @@ public void testSameIssuerTwoRealmsDifferentClientSecrets() throws Exception {
         final int jwtAuthcCount = randomIntBetween(2, 3);
         doMultipleAuthcAuthzAndVerifySuccess(jwtIssuerAndRealm.realm(), user, jwt, clientSecret, jwtAuthcCount);
     }
+
+    public void testConcurrentPutAndInvalidateCacheWorks() throws Exception {
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealmAuthenticateTests.java:537]: Add a test which fails about 1 out 10 runs due to deadlock without the fix.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java [hunk 5]
```diff
@@ -31,8 +31,11 @@ public CacheIteratorHelper(Cache<K, V> cache) {
         final ReadWriteLock lock = new ReentrantReadWriteLock();
         // the lock is used in an odd manner; when iterating over the cache we cannot have modifiers other than deletes using the
         // iterator but when not iterating we can modify the cache without external locking. When making normal modifications to the cache
-        // the read lock is obtained so that we can allow concurrent modifications; however when we need to iterate over the keys or values
-        // of the cache the write lock must obtained to prevent any modifications.
+        // the read lock can be obtained so that we can allow concurrent modifications; however when we need to iterate over the keys or
+        // values
+        // of the cache the write lock must be obtained to prevent any modifications.
```
Comment (tvernum) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java:36]:
```suggestion
        // values of the cache the write lock must be obtained to prevent any modifications.
```

**Review by tvernum — APPROVED** [review]
LGTM

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java (hunk 2 above)
Comment (tvernum) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java]: I agree with pushing it to a separate PR.
In terms of naming, I would be happy with `acquireSharedLock` and `acquireExclusiveLock`  and use the JavaDoc to explain which cache operations need which lock (& maybe there's a better name than shared?)

I think `read` / `write` are a problem because they lead to the scenario we almost had where we held an exclusive lock for a write on the critical path. The previous names tried to avoid that problem by naming the locks after the types of operations that needed each lock, but it turns out that the set of operations that need an exclusive lock is more than just "iteration". 
If we name them shared/exclusive we force authors to think about which one they need, at the cost that it's less obvious which one you need and you might have to check the docs.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java (hunk 3 above)
Comment (jakelandis) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtRealm.java]: thanks for catching this.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java (hunk 2 above)
Comment (jakelandis) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/support/CacheIteratorHelper.java]: +1 to push the naming discussion to another PR, but generally I don't like the names that mask what it actually is. I think most developers understand the semantics of a read/write lock while shared and exclusive are less well defined. 

> I think read / write are a problem because they lead to the scenario we almost had where we held an exclusive lock for a write on the critical path.

That wasn't due to the naming or misunderstanding, just a mistake while trying to fix this ASAP. I actually don't think we should expose any locks at all and just wrap the calls to the cache with the appropriate lock and rename CacheIteratorHelper to CacheHelper and javadoc to why we are wrapping. i.e. ChacheHelper#put(k,v) grabs the read lock and CacheHelper#InvalidateAll() grabs the write lock such that the calling code only ever deals with helper and the helper does the right thing.
