### PR TITLE
Fix upsert too long id

### LINKED ISSUE #102981: add validation on _id field when upsert new doc
### Elasticsearch Version

any versions

### Installed Plugins

_No response_

### Java Version

java version "17.0.5" 2022-10-18 LTS

### OS Version

Darwin

### Problem Description

It seems that validate() in UpdateRequest does not include the limitation on _id, but IndexRequest does:

image

In this scenario, when I add a new document through upsert, it will be executed successfully. But later when I reindex from the source index, it fail due to the limitation on _id, because reindex first search then add IndexRequests to bulk.

### Steps to Reproduce

1. index a doc with a long id, it fail:
`
curl --location --request POST 'localhost:9200/test_id/_bulk' \
--header 'Content-Type: application/json' \
--data-raw '{ "index" : {"_id" : "Ю10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8Ю10iS7hWAbPcH8πЮ10iS7hWAbPcH8ππЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ1" } }
{ "doc" : {"field2" : "value2"}}
'
`

2. upsert a doc with a long id, it success:
`
curl --location --request POST 'localhost:9200/test_id/_bulk' \
--header 'Content-Type: application/json' \
--data-raw '{ "update" : {"_id" : "Ю10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8Ю10iS7hWAbPcH8πЮ10iS7hWAbPcH8ππЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ10iS7hWAbPcH8πЮ1" } }
{ "doc" : {"field2" : "value2"}, "doc_as_upsert": true}
'
`

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by wdongyu**
Closes #102981

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/update/UpdateRequestTests.java [hunk 1]
```diff
@@ -495,6 +496,27 @@ public void testToValidateUpsertRequestWithVersion() {
         assertThat(updateRequest.validate().validationErrors(), contains("can't provide version in upsert request"));
     }
 
+    public void testUpdatingRejectsLongIds() {
+        String id = randomAlphaOfLength(511);
```
Comment (bohemia420) [inline server/src/test/java/org/elasticsearch/action/update/UpdateRequestTests.java:500]: @wdongyu this can be looped. code isnt compact here and DRY/iteration can be followed.

File: server/src/test/java/org/elasticsearch/action/update/UpdateRequestTests.java [hunk 2]
```diff
@@ -495,6 +496,27 @@ public void testToValidateUpsertRequestWithVersion() {
...
+        request.doc("{}", XContentType.JSON);
+        validate = request.validate();
+        assertNull(validate);
+
+        id = randomAlphaOfLength(513);
+        request = new UpdateRequest("index", id);
+        request.doc("{}", XContentType.JSON);
+        validate = request.validate();
+        assertThat(validate, notNullValue());
+        assertThat(validate.getMessage(), containsString("id [" + id + "] is too long, must be no longer than 512 bytes but was: 513"));
```
Comment (bohemia420) [inline server/src/test/java/org/elasticsearch/action/update/UpdateRequestTests.java:517]: @wdongyu 512, 513 are hardcoded and repeated. 512 can be a maxlen constant.

**Comment by bohemia420** [comment]
@wdongyu there may be no need to have 2 commits - kindly squash into 1.

**Comment by bohemia420** [comment]
is there any nomenclature for git branching? can we name it better than `wdongyu:fix_upsert_too_long_id`, maybe as **bug-103399-wdongyu**? @wdongyu

**Comment by benwtrent** [comment]
> @wdongyu there may be no need to have 2 commits - kindly squash into 1.


No, don't do this. Whenever this gets actually reviewed and merged, it will be squashed. Never force push with a squashed commit once a PR starts getting reviewed. 

> is there any nomenclature for git branching? can we name it better than wdongyu:fix_upsert_too_long_id, maybe as bug-103399-wdongyu? @wdongyu

Branch names mean nothing. As long as the branch merger references the issue ID in the commit message, its fine.

**Comment by wdongyu** [comment]
> is there any nomenclature for git branching? can we name it better than `wdongyu:fix_upsert_too_long_id`, maybe as **bug-103399-wdongyu**? @wdongyu

@bohemia420 maybe we can name it to `wdongyu:bug-102981-fix-upsert-too-long-id` ?

**Comment by benwtrent** [comment]
@wdongyu I committed a change log entry for this change.

**Comment by benwtrent** [comment]
buildkite test this

**Comment by wdongyu** [comment]
this pr lefts a task only, could you assign an assignee @benwtrent @bohemia420

**Comment by benwtrent** [comment]
I am pinging the experts on this part of the code.

Pinging @elastic/es-distributed (Team:Distributed)

**Comment by kingherc** [comment]
Hi, thanks for the PR! It looks reasonable. Initially I wondered whether we should consider this a breaking change or a bugfix, but after some discussion with the team, we're already [documenting](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) the 512 limit so we can consider this as a bugfix. Will rebase the branch, pass another final CI and will merge it afterwards.

**Comment by kingherc** [comment]
@elasticmachine rebase branch

**Comment by kingherc** [comment]
@elasticmachine update branch

**Comment by kingherc** [comment]
buildkite test this

**Review by kingherc — APPROVED** [review]
Follows the logic of testIndexingRejectsLongIds. LGTM.

**Comment by benwtrent** [comment]
🎉 🎉 🎉 @wdongyu 🎉 🎉 🎉 Thank you for the contribution!!!

**Comment by wdongyu** [comment]
Thank you all guys for the approval of the first pr from a beginner😊
