### PR TITLE
Optimize search shard iterator sort

### LINKED ISSUE #135472: GroupShardsIterator can significantly tie up transport workers
### Elasticsearch Version

8.17+

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When querying many shards, it has been observed that iterating the shards themselves can end up tying up a transport_worker thread. I am not sure if we want to optimize this path further or pivot to a different thread when above some shard threshold. 

Switching to another threadpool on few shards (<10k?) seems unhelpful.

### Steps to Reproduce

Have many shards, query something that hits all of them ;)

### Logs (if relevant)

```
100.3% [cpu=100.3%, idle=0.0%] (501.4ms out of 500ms) cpu usage by thread 'elasticsearch[instance-0000000279][transport_worker][T#6]'
  2/10 snapshots sharing following 292 elements
    app/org.apache.lucene.core@9.12.0/org.apache.lucene.util.TimSorter.sort(TimSorter.java:203)
    app/org.apache.lucene.core@9.12.0/org.apache.lucene.util.CollectionUtil.timSort(CollectionUtil.java:186)
    app/org.apache.lucene.core@9.12.0/org.apache.lucene.util.CollectionUtil.timSort(CollectionUtil.java:200)
    app/org.elasticsearch.server@8.17.9/org.elasticsearch.cluster.routing.GroupShardsIterator.sortAndCreate(GroupShardsIterator.java:33)
    app/org.elasticsearch.server@8.17.9/org.elasticsearch.cluster.routing.OperationRouting.searchShards(OperationRouting.java:140)
    app/org.elasticsearch.server@8.17.9/org.elasticsearch.action.search.TransportSearchAction.getLocalShardsIterator(TransportSearchAction.java:1840)
[...]
```

### PR DESCRIPTION
**Pull request by eranweiss-elastic**
Moved sorting of search shard iterators from the searchShards function that runs in the transport worker to after the CanMatch phase, which is in the search thread pool. Additionally, sorting only after the filter reduces CPU usage, especially relevant if the shard count is high relative to the result count.

Fixed #135472

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java [hunk 1]
```diff
@@ -116,7 +116,6 @@ public List<SearchShardRouting> searchShards(
                 );
             }
         }
-        res.sort(SearchShardRouting::compareTo);
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java]: More than just TransportSearchAction call this method - can we can safely do this? Have you verified no other callers rely on the sort?

Comment (jimczi) [inline server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java:119]: We still need to do the sort for callers that don't run the can match phase. Maybe add a parameter to apply sorting or not?

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java:119]: We also need to apply the sort in TransportSearchAction if the can match phase is not triggered?

**Review by jimczi — COMMENTED** [review]
I left some comments, thanks for tackling this.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java [hunk 2]
```diff
@@ -239,6 +237,8 @@ private void runCoordinatorRewritePhase() {
                 consumeResult(false, request);
             }
         }
+        // order matching shard by the natural order, so that search results will use that order
+        matchedShardLevelRequests.sort(SearchShardIterator::compareTo);
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: I'm curious if we can push this further - this is just the first step of the can-match phase (purely on the coordinator node). Could we wait until the entire can-match phase is complete before sorting? I see there is some `sortShards` that already runs - do we need to do any more sorting?

**Review by benchaplin — COMMENTED** [review]
++ to Jim's note as well, we should be careful not to disrupt other callers of searchShards. Perhaps none of them rely on a sorted response but that requires some careful investigation, maybe not worth it.

I'm also wondering if we should add some tests here. The underlying assumption of this PR is that can-match does not need to run on a sorted list of shards. Can we verify that somehow with testing? The change you've made ensures we _leave_ the can-match phase with sorted shards - can we test that property, protecting it for the future?

File: server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java (hunk 1 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java:119]: I've added a shouldSort parameter, controlled in the TransportSearchAction by the phase, and true everywhere else.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java (hunk 2 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: I think sortShards sorts by a different comparator, and the sort here is the tie breaker in that sort (and possibly others), so I don't think there's redundancy between the sorts.

Regarding waiting longer, the main benefit here should be from filtering in the coordinator node. Both practically, from data streams timestamps, and because I think that the cost of sending requests to other node should overweight the cost of sorting.

**Comment by eranweiss-elastic** [comment]
@benchaplin , as for Jim comments, please see my reply and updated code.

I'm not sure how to verify that can-match can run on unsorted input, other than running our tests and seeing them pass. In this PR, can-match runs with unsorted input.

As for tests, CanMatch already has tests that check order of replies (CanMatchPreFilterSearchPhaseTests.java). Is there something specific that you think should be added?

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java [hunk 3]
```diff
@@ -111,18 +110,17 @@ private CanMatchPreFilterSearchPhase(
         final int size = shardsIts.size();
         possibleMatches = new FixedBitSet(size);
         minAndMaxes = new MinAndMax<?>[size];
-        // we compute the shard index based on the natural order of the shards
+        // we compute a shard index based on the order of the shards
         // that participate in the search request. This means that this number is
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: > This means that this number is consistent between two requests that target the same shards.

Er, should we remove this too? Maybe I'm misunderstanding it.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java [hunk 4]
```diff
@@ -239,6 +237,9 @@ private void runCoordinatorRewritePhase() {
                 consumeResult(false, request);
             }
         }
+        // order matching shard by the natural order, so that search results will use that order
+        // this can possibly be pushed after filtering by data nodes, if needed
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: Thanks for adding this note!

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java (hunk 2 above)
Comment (benchaplin) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: After talking with Eran offline, he convinced agree the main benefit is achieved from moving the sort here, and that we can wait and see if other issues crop up before considering pushing it farther down the line. Thanks!

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java [hunk 5]
```diff
@@ -1733,7 +1733,8 @@ private void executeSearch(
                 searchRequest,
                 searchRequest.getLocalClusterAlias(),
                 indicesAndAliases,
-                concreteLocalIndices
+                concreteLocalIndices,
+                searchPhaseProvider.getClass().getName().equals(CanMatchPreFilterSearchPhase.class.getName()) == false
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java]: I don't think this works - CanMatchPreFilterSearchPhase is not a SearchPhaseProvider. Whether the can-match phase runs is based on the result of shouldPreFilterSearchShards.

**Review by benchaplin — COMMENTED** [review]
Hm @eranweiss-elastic I took a look at CanMatchPreFilterSearchPhaseTests and I don't think any of those tests run CanMatchPreFilterSearchPhase.execute with a List<SearchShardIterator> that is not already sorted. That's what I'm looking for with testing: a test that runs with a shuffled list of shard iterators, and outputs (calls the listener.onResponse) with a list of shard iterators that IS sorted.

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java (hunk 5 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java]: Good catch! I missed that. I'll fix it.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java (hunk 3 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: Good point, I'll remove it.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java [hunk 6]
```diff
@@ -473,31 +470,51 @@ private synchronized List<SearchShardIterator> getIterator(List<SearchShardItera
             possibleMatches.set(shardIndexToQuery);
         }
         int i = 0;
+        List<SearchShardIterator> possibleShards = new ArrayList<>(possibleMatches.length());
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: It's a good idea to get rid of the skipped shards at this stage but we still have some downstream tasks that rely on them being present. For instance [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/search/AbstractSearchAsyncAction.java#L141) or [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/search/AbstractSearchAsyncAction.java#L189).
We shouldn't have to though and maybe just providing the skipped count to the downstream task would be enough?

Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: I think you're right. a few lines below, after the sort, the skipped shards are added to the list to support that functionality.
Replacing a list of skipped shards are replacing them with a skipped count sounds like a great idea, but maybe we should split it off from this task.

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: ++ for a follow up, let's just sort the entire list for now.

Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: Is sorting the entire list required? Because is the size of the list that we're trying to avoid sorting (unless I'm missing something).

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: Yep sorry, re-adding afterward is better.

**Review by jimczi — APPROVED** [review]
LGTM!

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java (hunk 6 above)
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: Perhaps a better name here? This List starts out as "possible" shard iterators but quickly turns into all shard iterators with skipped at the end.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java [hunk 7]
```diff
@@ -473,31 +470,51 @@ private synchronized List<SearchShardIterator> getIterator(List<SearchShardItera
...
+                possibleShards.add(iter);
             } else {
                 iter.skip(true);
             }
         }
+        // order matching shard by the natural order, so that search results will use that order
+        possibleShards.sort(SearchShardIterator::compareTo);
+        // add skipped shards
+        i = 0;
+        for (SearchShardIterator iter : shardsIts) {
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java]: I think we can leave out several of the lines here: no need to reset the iterator, assert, or set skip to true, right? We've already done all of those things.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java [hunk 8]
```diff
@@ -473,31 +470,51 @@ private synchronized List<SearchShardIterator> getIterator(List<SearchShardItera
             possibleMatches.set(shardIndexToQuery);
         }
         int i = 0;
+        List<SearchShardIterator> possibleShards = new ArrayList<>(possibleMatches.length());
         for (SearchShardIterator iter : shardsIts) {
```
Comment (benchaplin) [inline server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java:474]: Perhaps it'd be faster to create two lists: one for not-skipped and one for skipped, then append skipped to non-skipped after sorting. This avoids walking the entire original list twice.

File: server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java [hunk 9]
```diff
@@ -260,6 +260,7 @@ public void testMergeShardsIterators() {
         for (SearchShardIterator searchShardIterator : groupShardsIterator) {
             result.add(searchShardIterator);
         }
+        result.sort(SearchShardIterator::compareTo);
```
Comment (benchaplin) [inline server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java:263]: Nit: maybe it's better to remove the shuffle calls above instead, what do you think?

File: server/src/test/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhaseTests.java [hunk 10]
```diff
@@ -180,12 +181,9 @@ public void sendCanMatch(
             }
         } else if (shard1 == false && shard2 == false) {
             assertFalse(result.get().get(0).skip());
-            assertTrue(result.get().get(1).skip());
```
Comment (benchaplin) [inline server/src/test/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhaseTests.java:183]: Are these changes necessary after you adjusted your approach to put skipped shards back at the end of the list?

Comment (eranweiss-elastic) [reply server/src/test/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhaseTests.java:183]: Some of them, because the skipped shards are not sorted. I went over the changes, and reverted what I could.

File: server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java (hunk 9 above)
Comment (eranweiss-elastic) [reply server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java:263]: I think that shuffling is nice for testing purposes, even though it shouldn't affect the comparison later.

File: server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java (hunk 8 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhase.java:474]: I re-did this section of code, with your comments in mind. Please take a look at the new code.

**Review by benchaplin — APPROVED** [review]
Awesome work on this!
