### PR TITLE
Only fail the relocation target when a replication request on it fails

### LINKED ISSUE #15790: Failed replication requests on relocating shards causes unnecessary recoveries
When executing a replication request against a shard that is relocating, the request is routed to the target of the relocation. However, if that request fails we currently fail the source of the relocation. This correctly causes the target of the relocation to be marked as failed but since it leads to both the source and the target being marked as failed, it leads to an unnecessary recovery.

### PR DESCRIPTION
**Pull request by jasontedor**
This commit addresses an issue when handling a failed replication
request against a relocating target shard. Namely, if a replication
request fails against the target of a relocation we currently fail both
the source and the target. This leads to an unnecessary
recovery. Instead, only the target of the relocation should be failed.

Closes #15790

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 1]
```diff
@@ -844,11 +844,11 @@ protected void doRun() {
                 // we never execute replication operation locally as primary operation has already completed locally
                 // hence, we ignore any local shard for replication
                 if (nodes.localNodeId().equals(shard.currentNodeId()) == false) {
-                    performOnReplica(shard, shard.currentNodeId());
+                    performOnReplica(shard);
                 }
                 // send operation to relocating shard
                 if (shard.relocating()) {
-                    performOnReplica(shard, shard.relocatingNodeId());
+                    performOnReplica(shard.buildTargetRelocatingShard());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: I'm fine with this for this fix (to keep it small), but it's a shame we create these objects. As a followup I think we should change IndexShardRoutingTable#activeShards to include relocation targets (as allInitializingShards does). Then we can use that list which is cached and we also won't need the relocation check,

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java [hunk 2]
```diff
@@ -486,7 +488,37 @@ protected void runReplicateTest(IndexShardRoutingTable shardRoutingTable, int as
...
+            // no duplicate requests
+            assertTrue(nodesSentTo.add(capturedRequest.node.getId()));
+            // the request is hitting the correct shard
+            Request replicationRequest = (Request)capturedRequest.request;
+            assertEquals(request.shardId, replicationRequest.shardId);
+        }
+
+        // requests were sent to the correct shard copies
+        List<ShardRouting> shards =
+            clusterService.state().getRoutingTable().index(shardId.getIndex()).shard(shardId.id()).shards();
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: we have a utility method RoutingTable.shardRoutingTable which gives you what you want. Also IndexShardRoutingTabel is iterable so we don't need the temp list.

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java [hunk 3]
```diff
@@ -486,7 +488,37 @@ protected void runReplicateTest(IndexShardRoutingTable shardRoutingTable, int as
...
+        for (ShardRouting shard : shards) {
+            if (!shard.primary() && !executeOnReplica) {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: use == false . Also where do we check that the total number of captured requests is what we expect? (to guarantee it doesn't contain the node the primary shard is on).

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java [hunk 4]
```diff
@@ -486,7 +488,37 @@ protected void runReplicateTest(IndexShardRoutingTable shardRoutingTable, int as
...
+                continue;
+            }
+            if (shard.unassigned()) {
+                continue;
+            }
+            if (!clusterService.state().getNodes().localNodeId().equals(shard.currentNodeId())) {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: == false

Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: we always run on the node with primary, so I don't think we need this check?

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java [hunk 5]
```diff
@@ -511,6 +543,12 @@ protected void runReplicateTest(IndexShardRoutingTable shardRoutingTable, int as
                     transport.clear();
                     assertEquals(1, shardFailedRequests.length);
                     CapturingTransport.CapturedRequest shardFailedRequest = shardFailedRequests[0];
+                    // get the shard the request was sent to
+                    ShardRouting routing = clusterService.state().getRoutingNodes().node(capturedRequest.node.id()).get(request.shardId.id());
+                    // and the shard that was requested to be failed
+                    ShardStateAction.ShardRoutingEntry shardRoutingEntry = (ShardStateAction.ShardRoutingEntry)shardFailedRequest.request;
+                    // the shard the request was sent to and the shard to be failed should be the same
+                    assertTrue(shardRoutingEntry.getShardRouting().isSameAllocation(routing));
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: I wonder if we should use equality here?

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java (hunk 4 above)
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: sorry - got confused - I thought this code skips the primary. I think it will be clear if the if here would say "ShardRouting.primary() == false "

**Comment by jasontedor** [comment]
@bleskes I pushed 7e8cdab357ae681c06e30738b328b5c4d797c28a to address your feedback on `TransportReplicationActionTests#runReplicateTest`.

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java [hunk 6]
```diff
@@ -486,7 +491,40 @@ protected void runReplicateTest(IndexShardRoutingTable shardRoutingTable, int as
         replicationPhase.run();
         final CapturingTransport.CapturedRequest[] capturedRequests = transport.capturedRequests();
         transport.clear();
+
         assertThat(capturedRequests.length, equalTo(assignedReplicas));
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: this can go away now...

**Comment by bleskes** [comment]
awesome. LGTM. Can we open an issue/work on that comment regarding building the target routing for each request? just making sure it's not lost :)

File: core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java (hunk 6 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationActionTests.java]: @bleskes Removed in 3c4edd143a6d26e6104f9ae42250ce687d2ccd9b.

File: core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: @bleskes I opened #15798.
