### PR TITLE
ILM: don't take snapshot of a data stream's write index

### LINKED ISSUE #58125: [CI] TimeSeriesDataStreamsIT.testSearchableSnapshotAction fails
**Build scan**:
https://gradle-enterprise.elastic.co/s/lxldutwf4ie5o

**Repro line**:
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testSearchableSnapshotAction" -Dtests.seed=5BA0786658AA3229 -Dtests.security.manager=true -Dtests.locale=es-CU -Dtests.timezone=Hongkong -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
`8.0.0`, `7.9.0`

**Failure excerpt**:
```
  2> java.lang.AssertionError: Found in progress snapshots [{lzwjR=[{failures=[], include_global_state=false, end_time=1970-01-01T00:00:00.000Z, duration_in_millis=0, version_id=8000099, uuid=B8wvKC2GSHGsLjbnw8st_g, version=8.0.0, start_time=2020-06-15T15:27:28.390Z, shards={total=0, failed=0, successful=0}, indices=[.ds-logs-foo-000002], start_time_in_millis=1592234848390, state=IN_PROGRESS, snapshot=2020.06.15-.ds-logs-foo-000002-logs-policy-qdivrwvcqvozfpi-ri7dfg, end_time_in_millis=0}]}].
    Expected: a map with size <0>
         but: map size was <1>
        at __randomizedtesting.SeedInfo.seed([5BA0786658AA3229:8D786789CBA38E9D]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:607)
        at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:296)
```

### PR DESCRIPTION
**Pull request by andreidan**
We don't allow converting a data stream's writeable index into a searchable
snapshot. We are currently preventing swapping a data stream's write index
with the restored index.

This adds another step that will not proceed with the searchable snapshot action
until the managed index is not the write index of a data stream anymore.

Fixes #58125

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+            return new Result(false, new Info(errorMessage));
+        }
+
+        String policyName = indexMetadata.getSettings().get(LifecycleSettings.LIFECYCLE_NAME);
+        IndexAbstraction indexAbstraction = clusterState.metadata().getIndicesLookup().get(indexName);
+        assert indexAbstraction != null : "invalid cluster metadata. index [" + indexName + "] was not found";
+        IndexAbstraction.DataStream dataStream = indexAbstraction.getParentDataStream();
+        if (dataStream != null) {
+            assert dataStream.getWriteIndex() != null : dataStream.getName() + " has no write index";
+            if (dataStream.getWriteIndex().getIndex().getName().equals(indexName)) {
```
Comment (danhermann) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java:64]: Minor, but other places we've made a point to compare `Index` instances so both the index name and UUID match.
```suggestion
            if (dataStream.getWriteIndex().getIndex().equals(index)) {
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+
+/**
+ * Some actions cannot be executed on a data stream's write index (eg. `searchable-snapshot`). This step checks if the managed index is
+ * part of a data stream, in which case it will check it's not the write index. If the managed index is the write index of a data stream
+ * this step will wait until that's not the case (ie. rolling over the data stream will create a new index as the data stream's write
+ * index and this step will be able to complete)
+ */
+public class CheckNotDataStreamWriteIndexStep extends ClusterStateWaitStep {
+
+    public static final String NAME = "check-no-write-index";
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java:31]: Minor suggestion to make it clearer that we're not waiting for the write index not to exist:

```suggestion
    public static final String NAME = "check-not-write-index";
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+        String policyName = indexMetadata.getSettings().get(LifecycleSettings.LIFECYCLE_NAME);
+        IndexAbstraction indexAbstraction = clusterState.metadata().getIndicesLookup().get(indexName);
+        assert indexAbstraction != null : "invalid cluster metadata. index [" + indexName + "] was not found";
+        IndexAbstraction.DataStream dataStream = indexAbstraction.getParentDataStream();
+        if (dataStream != null) {
+            assert dataStream.getWriteIndex() != null : dataStream.getName() + " has no write index";
+            if (dataStream.getWriteIndex().getIndex().getName().equals(indexName)) {
+                String errorMessage = String.format(Locale.ROOT, "index [%s] is the write index for data stream [%s]. " +
+                    "stopping execution of lifecycle [%s]. manually rolling over the index will resume the execution of the policy as " +
+                    "the index will not be the data stream's write index anymore", indexName, dataStream.getName(), policyName);
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java:67]: I think calling it "stopping" might be a little confusing, I would suggest something like:

"index [.ds-foo-0001] is the write index for data stream [foo], pausing ILM execution until this index is no longer the write index for the data stream via manual or automated rollover"

What do you think?

**Review by dakrone — COMMENTED** [review]
This looks good, I left two minor comments, are we intending to use this same step in the shrink, freeze, and readonly actions also?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java (hunk 3 above)
Comment (andreidan) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CheckNotDataStreamWriteIndexStep.java:67]: sure, good point

**Comment by andreidan** [comment]
@dakrone I was planning on using this step in `ReadOnly` and `Freeze` actions. For `Shrink` I think we shouldn't as we have a small optimisation and skip the action all together if the target number of shards is the same as the index's number of shards ( https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkAction.java#L153 )

What do you think?

**Comment by dakrone** [comment]
> What do you think?

I think it sounds good to use it for readonly and freeze, I think we should still use it for shrink, it should just go after the check (so only check if it's the write index if we're actually going to do the shrink).

Is this work for a subsequent PR then?

**Comment by andreidan** [comment]
> Is this work for a subsequent PR then? 

@dakrone yes, I was thinking of adding it in another PR to keep this targeted at the searchable snapshot test failure

**Review by dakrone — APPROVED** [review]
LGTM, thanks Andrei!

**Comment by danhermann** [comment]
LGTM, too!
