### PR TITLE
Return a better error message when Timestamp is renamed in TS queries

### LINKED ISSUE #134994: [ES|QL] TS Command: Can't rename timestamp field
```
ts k8s 
| rename `@timestamp` AS nNVStdFbIFX 
| stats  max(rate(network.total_cost)) by bucket(nNVStdFbIFX,1hour)
```
same query with bucket on `@timestamp` also fails

```
            "type" : "verification_exception",
            "reason" : "Found 1 problem
line 3:14: Unknown column [@timestamp]",
            "stack_trace" : "org.elasticsearch.xpack.esql.VerificationException: Found 1 problem
line 3:14: Unknown column [@timestamp]
     org.elasticsearch.xpack.esql.analysis.Analyzer.verify(Analyzer.java:235)
     org.elasticsearch.xpack.esql.analysis.Analyzer.analyze(Analyzer.java:229)
     org.elasticsearch.xpack.esql.session.EsqlSession.analyzedPlan(EsqlSession.java:784)
     org.elasticsearch.xpack.esql.session.EsqlSession.analyzeWithRetry(EsqlSession.java:725)
     org.elasticsearch.xpack.esql.session.EsqlSession.lambda$analyzedPlan$11(EsqlSession.java:407)
     org.elasticsearch.server@9.2.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
     org.elasticsearch.server@9.2.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:406)
     org.elasticsearch.server@9.2.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:326)
     org.elasticsearch.server@9.2.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:355)
     org.elasticsearch.server@9.2.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:262)
     org.elasticsearch.xpack.esql.session.EsqlSession.preAnalyzeLookupIndices(EsqlSession.java:422)
     org.elasticsearch.xpack.esql.session.EsqlSession.lambda$analyzedPlan$10(EsqlSession.java:406)
```

### PR DESCRIPTION
**Pull request by not-napoleon**
Resolves https://github.com/elastic/elasticsearch/issues/134994

After discussing this more on https://github.com/elastic/elasticsearch/pull/136062, we have decided queries that rename the `@timestamp` field should fail with a clear error message.

This relates to https://github.com/elastic/elasticsearch/issues/136772

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 1]
```diff
@@ -1181,29 +1230,26 @@ public void testAggsResolutionWithUnresolvedGroupings() {
     public void testNotAllowRateOutsideMetrics() {
         assertThat(
             error("FROM tests | STATS avg(rate(network.bytes_in))", tsdb),
-            equalTo("1:24: time_series aggregate[rate(network.bytes_in)] can only be used with the TS command")
+            equalTo("1:24: Rate aggregation requires @timestamp field, but @timestamp was renamed or dropped")
```
Comment (not-napoleon) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: This is wrong.  I don't see why the custom error message is overwriting this more specific error here, and in the other tests in this file.

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/40_tsdb.yml [hunk 2]
```diff
@@ -3,41 +3,41 @@ setup:
...
-                          type: ip
-                        network:
-                          properties:
-                            tx:
-                              type: long
-                              time_series_metric: counter
-                            rx:
-                              type: integer
-                              time_series_metric: counter
+        index: test
```
Comment (dnhatn) [inline x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/esql/40_tsdb.yml]: this: nit: can we avoid reformatting this file?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/AbstractLogicalPlanOptimizerTests.java [hunk 3]
```diff
@@ -57,7 +57,7 @@ public abstract class AbstractLogicalPlanOptimizerTests extends ESTestCase {
     protected static Analyzer multiIndexAnalyzer;
     protected static Analyzer sampleDataIndexAnalyzer;
 
-    protected static EnrichResolution enrichResolution;
+    public static EnrichResolution enrichResolution;
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/AbstractLogicalPlanOptimizerTests.java]: nit: we don't need this change?

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries.csv-spec [hunk 4]
```diff
@@ -593,3 +593,52 @@ max_cost:integer | pod:keyword | time_bucket:datetime     | max_cluster_cost:int
...
+
+maxRate:double | tbucket:datetime
+0.058979885057471274 | 2024-05-10T00:00:00.000Z
+;
+
+Max of Rate with Bucket, rename _tsid
+required_capability: ts_command_v0
+
+TS k8s METADATA _tsid
+| RENAME _tsid AS newTsid
```
Comment (dnhatn) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries.csv-spec:612]: Hmm, I think these queries should fail. You don't have to handle them in this PR.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/UnresolvedTimestamp.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+            id(),
+            super.unresolvedMessage(),
+            resolutionMetadata(),
+            errorMessage
+        );
+    }
+
+    @Override
+    public UnresolvedTimestamp withUnresolvedMessage(String unresolvedMessage) {
+        return new UnresolvedTimestamp(source(), qualifier(), name(), id(), unresolvedMessage, resolutionMetadata(), errorMessage);
```
Comment (dnhatn) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/UnresolvedTimestamp.java:51]: If you don't want to override `String unresolvedMessage()`, you can override `unresolvedMessage` here instead. Either approach is good.

**Review by dnhatn — APPROVED** [review]
I left some nits, but this looks good. Can you also change to `UnresolvedTimestamp` for LastOverTime, FirstOverTime, Increase, Irate, Delta, and IDelta? Thank you, Mark!

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries.csv-spec (hunk 4 above)
Comment (not-napoleon) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/k8s-timeseries.csv-spec:612]: Yeah, we need to open a few follow up issues.  There's also the case of shadowing timestamp in an eval that should fail.

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Comment by not-napoleon** [comment]
manual backport PR: https://github.com/elastic/elasticsearch/pull/137112
