### PR TITLE
SQL: JDBC: fix temporary directory locked test errors in Windows

### LINKED ISSUE #56882: sql.client.VersionTests cleanup failure on Windows
**Build scan**:
https://gradle-enterprise.elastic.co/s/4a6jt3jrli22q

**Repro line**:
```
gradlew ':x-pack:plugin:sql:sql-client:test' --tests "org.elasticsearch.xpack.sql.client.VersionTests" \
  -Dtests.seed=7744CD7E2883EFFE \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=GMT \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

**Reproduces locally?**:
Unknown, I don't have a Windows machine to test on. 

**Applicable branches**:
7.7, 7.x.m master 

**Failure history**:
Frequently since 16th May.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:VersionTests),sort:!(time,desc))

**Failure excerpt**:
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005\es-sql-jdbc.jar: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005\es-sql-jdbc.jar: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005
   C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001

	at __randomizedtesting.SeedInfo.seed([C287621E387C0F36]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by bpintea**
The tests involving a temporary directory (containing the JDBC JAR) fail
on Windows because they can't be deleted, due to still being in use.
This PR forces an early closing of the JAR file, which mitigates
the failure by giving the JVM more time to collect any open FDs.
(Calling the System.gc() in the tests is another working alternative
fix.)

The stream-based JAR access is taken care by disabling the cache usage
(which has the same effect of closing the JAR).

Fixes #56882.

### CODE REVIEW

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java [hunk 1]
```diff
@@ -87,7 +88,11 @@ static Manifest getManifest(URL url) throws IOException {
             if (url.getProtocol().equals("jar")) {
                 JarURLConnection jarConn = (JarURLConnection) conn;
                 if (jarConn.getEntryName() == null) { // the URL points to a JAR file
-                    return jarConn.getManifest(); // in case of a fat JAR, this would return the outermost JAR's manifest
+                    Manifest manifest = jarConn.getManifest(); // in case of a fat JAR, this would return the outermost JAR's manifest
+                    try {
+                        jarConn.getJarFile().close(); // prevent locked file errors in Windows. The Manifest has been read by now
+                    } catch (IOException e) {/* ignore any closing failure */}
```
Comment (matriv) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:94]: Maybe we should log here, since this is not only for testing.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java [hunk 2]
```diff
@@ -87,7 +88,11 @@ static Manifest getManifest(URL url) throws IOException {
...
+                    return manifest;
```
Comment (matriv) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:95]: Shouldn't this be in a `finally` block to return not only in case of exception?

**Review by matriv — COMMENTED** [review]
Left a couple of comments.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:95]: Not sure I get your suggestion: the function returns irrespective of an `IOException` being raised. Or are you rather suggesting to return a version (in the calling function), also when an `IOExceptoin` is raised (which we currently propagate into a `IllegalArgumentException`)?

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:94]: We could, but where: the CLI client uses `java.util.logging`, but JDBC uses it's own logging. Would hooking into either just for this warning - since it's not really an error - be justified?

Comment (matriv) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:94]: My bad, sorry, misread that the return is within the catch block.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:95]: My bad, sorry, misread that the return is within the catch block.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java [hunk 3]
```diff
@@ -87,7 +88,11 @@ static Manifest getManifest(URL url) throws IOException {
             if (url.getProtocol().equals("jar")) {
                 JarURLConnection jarConn = (JarURLConnection) conn;
                 if (jarConn.getEntryName() == null) { // the URL points to a JAR file
-                    return jarConn.getManifest(); // in case of a fat JAR, this would return the outermost JAR's manifest
+                    Manifest manifest = jarConn.getManifest(); // in case of a fat JAR, this would return the outermost JAR's manifest
+                    try {
+                        jarConn.getJarFile().close(); // prevent locked file errors in Windows. The Manifest has been read by now
```
Comment (astefan) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:93]: Here both `getJarFile()` and `.close()` can throw an IOException. `getManifest()` call above does use `getJarFile()` so the danger of an IOException being thrown while calling `getJarFile()` wouldn't be ignored. But, would make sense to call `jarConn.getJarFile()` and reuse this object in both `getManifest()` and `.close()` calls?

**Review by astefan — APPROVED** [review]
LGTM, but left one comment.
There is another aspect that is still unknown to me: why is this `.close()` needed now, but wasn't needed before?

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java]: > why is this .close() needed now, but wasn't needed before?

We just didn't test with JAR non-entry URLs. The tests were using file (i.e. setting the `ClientVersion.CURRENT`) and entry JAR URLs (i.e. the JarInJar test).

> Here both getJarFile() and .close() can throw an IOException. 

True. And while the former's exception should surface, the latter (if it can ever occur) is non-critical.

> would make sense to call jarConn.getJarFile() and reuse this object in both getManifest() and .close() calls?

That exposes a bit more of "deprecated" surface and is more verbose, but I see how this would make sense. I've applied your suggestion.

**Comment by bpintea** [comment]
@elasticmachine update branch

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java [hunk 4]
```diff
@@ -87,7 +89,12 @@ static Manifest getManifest(URL url) throws IOException {
             if (url.getProtocol().equals("jar")) {
                 JarURLConnection jarConn = (JarURLConnection) conn;
                 if (jarConn.getEntryName() == null) { // the URL points to a JAR file
-                    return jarConn.getManifest(); // in case of a fat JAR, this would return the outermost JAR's manifest
+                    JarFile jar = jarConn.getJarFile();
```
Comment (costin) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:92]: I suggest using the try/close approach - it's similar but more concise:

```suggestion
if (jarConn.getEntryName() == null) {
 try (JarFile jar = jarconn.getJarFile()) {
      return jar.getManifest();
  }
}
```

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:96]: Probably not I guess...

**Review by matriv — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 4 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java]: Beautiful, forgot `JarFile` implements `AutoCloseable`. Thanks!

Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java]: For the record, that will still interrupt the loading if closing fails (while it shouldn't), but OTOH, I can't imagine a case where opening would work, but closing not.
