### PR TITLE
Fix incorrect calculation of how many buckets will result from a merge

### LINKED ISSUE #43577: auto_date_histogram generates too many buckets for smaller time range
It seems, that the `auto_date_histogram` seems to generate sometimes too many buckets, especially when using an overall small time-range to filter on. It's not constantly happening (I assume it is related a bit to the exact time you send it), but it happened reliable enough to reproduce it always within max. 1 minute trying.

I just used the following request (after injecting the Kibana Flight sample data set):

```json
GET kibana_sample_data_flights/_search
{
  "size": 0, 
  "query": {
    "range": {
      "timestamp": {
        "gte": "now-20m",
        "lte": "now"
      }
    }
  },
  "aggs": {
    "foo": {
      "auto_date_histogram": {
        "field": "timestamp",
        "buckets": 1
      }
    }
  }
}
```

This request returned the following response:

```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "foo" : {
      "buckets" : [
        {
          "key_as_string" : "2019-06-25T11:14:00.000Z",
          "key" : 1561461240000,
          "doc_count" : 1
        },
        {
          "key_as_string" : "2019-06-25T11:24:00.000Z",
          "key" : 1561461840000,
          "doc_count" : 3
        }
      ],
      "interval" : "10m"
    }
  }
}
```

As you can see even though we specified, we need 1 bucket, it generated 2 buckets for us. When playing around with the overall filter it seems that behavior never triggered for me once I had a timerange larger than 30 minutes, but was able to reproduce it rather often with time ranges below 30 minutes (wasn't linked to exactly 20 minutes time range). I tested this mainly on `master`. I was also not able to reproduce that behavior if I didn't use `now` as the upper bound but tried something like `now-1440m` to `now-1420m`.

cc @polyfractal

### PR DESCRIPTION
**Pull request by pcsanwald**
Fixed #43577 

Reproducing the problem in the issue showed that this calculation is incorrect:

```
int resultingBuckets = buckets.size() / interval;
                if (resultingBuckets <= targetBuckets)
```

because we can end up with extra buckets if the remainder here is not zero.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java [hunk 1]
```diff
@@ -108,10 +108,7 @@ public void testGetAppropriateRoundingUsesCorrectIntervals() {
         assertThat(result, equalTo(2));
     }
 
-
-    @Override
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/39497")
-    // TODO: When resolving the above AwaitsFix, just delete this override. Method is only overriden to apply the annotation.
```
Comment (pcsanwald) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: I've unmuted this test because the bug  _could_ have caused some of the failures we've seen previously, which seem to be off by one errors, such as in #39497. Some of those failures look quite similar:

```
   > Throwable #1: java.lang.AssertionError: expected:<{1548979200000=989}> but was:<{1548979200000=928, 1551398400000=61}>
```

**Review by polyfractal — APPROVED** [review]
:tada: LGTM!

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java (hunk 1 above)
Comment (polyfractal) [reply server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java]: ++ Agreed
