### PR TITLE
[Transform] improve continuous transform date_histogram group_by with ingest timestamps

### LINKED ISSUE #59061: [Transform] Performance: Unexpected long runtime for date_histogram group_by when using 2 different time fields
**Elasticsearch version** : 7.8

**Plugins installed**: []

**JVM version** : official docker for release 7.8

**OS version** : official docker for release 7.8

**Description of the problem including expected versus actual behavior**:

As asked on forum: https://discuss.elastic.co/t/continous-transforms-accumulating-delay-can-be-tweak-for-speed-up/239807/6

Transforms don't use last checkpoint date on date range calculation when we use differents fields on timestamp aggregation and on sync transforms setting.

**Steps to reproduce**:

On source index, create two time fields : 

- @timestamp => The date of the creation on the log on nginx
- processed_at => The date of processing the log, added by the ingest (logstash on my case)

Create a continuous transform like this : 

```
{  
  "settings": {
    "max_page_search_size": 10000
  },
  "frequency": "60s",
  "id": "THE_ID",
  "source": {
    "index": [
      "source-*"
    ],
    "query": {
      "bool": {
        "filter": [
          {
             // filter of transform
          }
        ]
      }
    }
  },
  "dest": {
    "index": "destination-index"
  },
  "sync": {
    "time": {
      "field": "processed_at",
      "delay": "5m"
    }
  },
  "pivot": {
    "group_by": {
      "@timestamp": {
        "date_histogram": {
          "field": "@timestamp",
          "calendar_interval": "1h"
        }
      },
      // some other group by
    },
    "aggregations": {
      // some aggregation settings
    }
  }
}
```

On each checkpoint transform query all index instead of range between old and current checkpoint.

**Provide logs (if relevant)**:

`range\":{\"processed_at\":{\"from\":null,\"to\":1594027879901
`

### PR DESCRIPTION
**Pull request by hendrikmuhs**
optimize continuous data histogram group_by for other time fields independent
of sync, this allows the usage of ingest timestamps in continuous mode

fixes #59061

How it works in a nutshell:

When querying for changes, transform adds `min` and `max` aggregations to later narrow the update query
by adding a range query given the output of `min` and `max`.

image

The optimization is similar to https://github.com/elastic/elasticsearch/issues/54254#issuecomment-604551359, worst case we re-query and re-write every document for each checkpoint without this optimization.

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/packaging-sample-windows

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java [hunk 1]
```diff
@@ -523,13 +707,22 @@ public boolean isOptimized() {
...
         Map<String, SingleGroupSource> groups,
         String synchronizationField
     ) {
         Map<String, FieldCollector> fieldCollectors = createFieldCollectors(groups, synchronizationField);
-        return new CompositeBucketsChangeCollector(compositeAggregationBuilder, fieldCollectors);
+
+        // after building the field collectors we know whether we need the composite aggregation
+        boolean keepCompositeAggregatonBuilder = fieldCollectors.values().stream().anyMatch(FieldCollector::requiresCompositeSources);
+
+        return new CompositeBucketsChangeCollector(keepCompositeAggregatonBuilder ? compositeAggregationBuilder : null, fieldCollectors);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:725]: This is a strange optimization to me. If you only want to optionally construct the `compositeAggregationBuilder` make it a `CachedSupplier` that is only called once or something.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java [hunk 2]
```diff
@@ -492,20 +670,26 @@ public boolean processSearchResponse(final SearchResponse searchResponse) {
...
-        final CompositeAggregation agg = aggregations.get(compositeAggregation.getName());
-
-        Collection<? extends Bucket> buckets = agg.getBuckets();
-        afterKey = agg.afterKey();
+        boolean isDone = true;
 
-        if (buckets.isEmpty()) {
-            return true;
+        // collect changes from composite buckets
+        if (compositeAggregation != null) {
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:676]: Why are you doing this `null` check? Wouldn't it be better to rely on if any of `fieldCollector` items `requiresCompositeSources` ?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java [hunk 3]
```diff
@@ -492,20 +670,26 @@ public boolean processSearchResponse(final SearchResponse searchResponse) {
...
+            final CompositeAggregation agg = aggregations.get(compositeAggregation.getName());
+            Collection<? extends Bucket> buckets = agg.getBuckets();
+            afterKey = agg.afterKey();
+            for (FieldCollector fieldCollector : fieldCollectors.values()) {
+                isDone &= fieldCollector.collectChangesFromCompositeBuckets(buckets);
+            }
+        } else {
+            afterKey = AFTER_KEY_MAGIC;
```
[the remark this answers is not in the document]
Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:684]: If the changes detector is not using a composite agg, the caller shouldn't attempt to iterate on it. Consequently a `null` after key would be acceptable as it would only be called once.

**Review by benwtrent — COMMENTED** [review]
definitely going to have to read through again :)

First pass review.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:684]: This is basically a state problem. I need to know whether the "changes query" has been executed or not, that means this is conceptually a boolean `hasRun`. However, this state is managed by the indexer, not by the change collector. E.g. what if something fails, the change collector doesn't know how to handle failures, but the indexer does. With that magic I let the indexer control this state object instead of having a boolean in the collector.

Having that said, I fully agree that this looks hacky. I will look at it again, suggestions welcome.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 1 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:725]: true, however I am not convinced a CachedSupplier is necessary. It makes it more complicated than necessary. Note that this is constructed exactly once after `_start`, so performance does not matter.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 2 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:676]: yes, that's an alternative, however the null check is more robust regarding bugs.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java [hunk 4]
```diff
@@ -449,10 +625,12 @@ private CompositeBucketsChangeCollector(
     public SearchSourceBuilder buildChangesQuery(SearchSourceBuilder sourceBuilder, Map<String, Object> position, int pageSize) {
         sourceBuilder.size(0);
         for (FieldCollector fieldCollector : fieldCollectors.values()) {
-            AggregationBuilder aggregationForField = fieldCollector.aggregateChanges();
 
-            if (aggregationForField != null) {
-                sourceBuilder.aggregation(aggregationForField);
+            // add aggregations, but only for the 1st run
+            if (position == null || position.isEmpty()) {
```
[the remark this answers is not in the document]
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:630]: yes

Note that `AFTER_KEY_MAGIC` is only used if there is only a field collector for `date_histogram` using aggs, but not if you combine `date_histogram` with `terms`.

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:676]: The only reason it is more robust in regarding bugs is because it is set to null explicitly earlier. 

I am not sure that is even necessary. It seems to me that some external thing is knowledgable of the internal logic of this system and is making changes. 

The separation of concerns seem to be bleeding across a bit.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:684]: Could these methods return `IterationResult` instead of a map?

It seems we always need two pieces of info:

- Are we done?
- What is the position?

That might prove a nicer abstraction than having a special bucket position. 

Also, I am not sure in what case the bucket processor (when not utilizing composite aggs), should ever be called twice. It seems weird to me as it should indicate that it is done :/.

[the remark this answers is not in the document]
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java]: by moving the `afterKey` to the indexer - where it actually belongs - I was able to remove the bool and the method to get the key. Note that the key can not be persisted right after the response, but only after the real changes got indexed. This is necessary in the failure scenario.

The "special bucket position" is part of making change collection scalable, it's required if more than 65k (10k in older versions) changes have been found.

In case you have 1 field collector that uses min/max and 1 that uses the composite agg(terms), the collector only adds the min/max aggs on the 1st run, but not on following runs in case the terms collector requires it.

I think the challenge is that we combine 2 different ways of change collection in 1 call.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java (hunk 2 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java]: I moved the creation of the composite agg part into the change collector, that way I also addressed your concern regarding creating the composite but than throwing it away. The also made the checks a bit easier, although we still need some as you can have any combination of aggs, depending on which collectors are used.

**Review by benwtrent — APPROVED** [review]
👍

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java [hunk 5]
```diff
@@ -486,26 +672,42 @@ public QueryBuilder buildFilterQuery(long lastCheckpointTimestamp, long nextchec
...
+            isDone &= fieldCollector.collectChangesFromAggregations(aggregations);
         }
 
-        for (FieldCollector fieldCollector : fieldCollectors.values()) {
-            fieldCollector.collectChanges(buckets);
+        // collect changes from composite buckets
+        final CompositeAggregation compositeAggResults = aggregations.get(COMPOSITE_AGGREGATION_NAME);
+
+        // xor: either both must exist or not exist
+        assert (compositeAggregation == null ^ compositeAggResults == null) == false;
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/CompositeBucketsChangeCollector.java:694]: [optional] Alternatively, you could express it this way:
```
        assert (compositeAggregation == null) == (compositeAggResults == null);
```
but I'm not sure which one is more readable.

File: x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/continuous/DateHistogramGroupByOtherTimeFieldIT.java [hunk 6]
```diff
@@ -0,0 +1,234 @@
...
+                Double.valueOf((Integer) XContentMapValues.extractValue(INGEST_RUN_FIELD, source)) - (Double) XContentMapValues
+                    .extractValue(MAX_RUN_FIELD, source),
+                is(lessThanOrEqualTo(1.0))
+            );
+        }
+        assertFalse(sourceIterator.hasNext());
+        assertFalse(destIterator.hasNext());
+    }
+
+    private Map<String, Object> flattenedResult(long second, String event, long count) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/continuous/DateHistogramGroupByOtherTimeFieldIT.java:227]: static

**Review by przemekwitek — APPROVED** [review]
LGTM
