### PR TITLE
Handle `index.mapping.ignore_malformed` in downsampling

### LINKED ISSUE #119075: Downsampling fails for indexes configured with [index.mapping.ignore_malformed:true]
### Elasticsearch Version

8.17

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

For TSDS configured with `[index.mapping.ignore_malformed:true]`, downsampling fails to create downsampled indexes as this setting is not allowed for `@timestamp` field:

```
[instance-0000000008] policy [downsampling_experiment_logs] for index [.ds-downsampling_experiment-2024.12.18-000001] failed on step [{"phase":"hot","action":"downsample","name":"rollup"}]. Moving to ERROR step
java.lang.IllegalArgumentException: data stream timestamp field [@timestamp] has disallowed [ignore_malformed] attribute specified
	at org.elasticsearch.index.mapper.DataStreamTimestampFieldMapper.doValidate(DataStreamTimestampFieldMapper.java:154) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.index.mapper.FieldMapper.validate(FieldMapper.java:352) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.index.mapper.Mapping.validate(Mapping.java:112) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.index.mapper.DocumentMapper.validate(DocumentMapper.java:117) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.index.mapper.MapperService.newDocumentMapper(MapperService.java:587) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.index.mapper.MapperService.doMerge(MapperService.java:577) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:561) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.xpack.downsample.TransportDownsampleAction.createDownsampleIndexMapping(TransportDownsampleAction.java:685) ~[?:?]
	at org.elasticsearch.xpack.downsample.TransportDownsampleAction.lambda$masterOperation$6(TransportDownsampleAction.java:338) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:203) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:197) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:336) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:97) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:336) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:184) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetMappingsAction.doMasterOperation(TransportGetMappingsAction.java:74) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetMappingsAction.doMasterOperation(TransportGetMappingsAction.java:31) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.support.master.info.TransportClusterInfoAction.masterOperation(TransportClusterInfoAction.java:65) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.support.master.info.TransportClusterInfoAction.masterOperation(TransportClusterInfoAction.java:25) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:127) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:238) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023) ~[elasticsearch-8.16.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-8.16.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

This happens even if the TSDS has `@timestamp` explicitly configured with `[ignore_malformed:false]`.

### Steps to Reproduce

Create a TSDS with index setting `[index.mapping.ignore_malformed:true]` and `@timestamp` configured with `[ignore_malformed:false]`. 

Trigger a downsample action.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lkts**
Currently `ignore_malformed` parameter of `@timestamp` field is not propagated to downsampled index. This is problematic when `index.mapping.ignore_malformed` is set to `true` because it leads to a validation error for data streams (ignoring timestamp does not make logical sense in a data stream). This PR fixes it.

Additionally we need to set `index.mapping.ignore_malformed` index setting earlier in the downsampling logic. Currently it is applied after the index is created with initial mapping. This leads to hitting this assert https://github.com/elastic/elasticsearch/blob/103d29f0c8a47053f6e7afd292b14bc0416581d5/server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java#L74 When `index.mapping.ignore_malformed` is not set it defaults to `false` which matches the value of `ignore_malformed` on `@timestamp` and so `ignore_malformed` is not serialized in mapping but it is present in mapping source.

Fixes #119075.

### CODE REVIEW

File: x-pack/plugin/downsample/src/test/java/org/elasticsearch/xpack/downsample/DownsampleActionSingleNodeTests.java [hunk 1]
```diff
@@ -201,14 +202,15 @@ public void setup() throws IOException {
...
+            .put(IndexSettings.TIME_SERIES_END_TIME.getKey(), "2106-01-08T23:40:53.384Z")
+            .put(FieldMapper.IGNORE_MALFORMED_SETTING.getKey(), randomBoolean());
 
         if (randomBoolean()) {
             settings.put(IndexMetadata.SETTING_INDEX_HIDDEN, randomBoolean());
         }
 
         XContentBuilder mapping = jsonBuilder().startObject().startObject("_doc").startObject("properties");
-        mapping.startObject(FIELD_TIMESTAMP).field("type", "date").endObject();
+        mapping.startObject(FIELD_TIMESTAMP).field("type", "date").field("ignore_malformed", false).endObject();
```
Comment (kkrik-es) [inline x-pack/plugin/downsample/src/test/java/org/elasticsearch/xpack/downsample/DownsampleActionSingleNodeTests.java:213]: This should be set when randomBoolean( ) above is also set (and left unset otherwise), for coverage.

File: x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java [hunk 2]
```diff
@@ -897,6 +901,12 @@ private void createDownsampleIndex(
                 sourceIndexMetadata.getSettings().get(MapperService.INDEX_MAPPING_TOTAL_FIELDS_LIMIT_SETTING.getKey())
             );
         }
+        if (sourceIndexMetadata.getSettings().hasValue(FieldMapper.IGNORE_MALFORMED_SETTING.getKey())) {
+            builder.put(
+                FieldMapper.IGNORE_MALFORMED_SETTING.getKey(),
+                sourceIndexMetadata.getSettings().get(FieldMapper.IGNORE_MALFORMED_SETTING.getKey())
+            );
+        }
```
Comment (kkrik-es) [inline x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:909]: I'm somewhat puzzled by this, so how does `@timestamp` pick up `ignore_above:true` if this is not set? I assume it's passed somewhere but not everywhere..

**Review by kkrik-es — APPROVED** [review]
Nice.

**Comment by kkrik-es** [comment]
Backport to 8.16.x, too?

File: x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java (hunk 2 above)
Comment (martijnvg) [reply x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:909]: I also don't fully understand this. Maybe the setting came from an index template?

Comment (lkts) [reply x-pack/plugin/downsample/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:909]: There are two sets of index settings:
1. Settings applied when index is created (what you are looking at).
2. Setting applied _after_ the index is created - everything from the original index is copied (except settings in 1).

I have to admit i don't understand the reason for the split but this is the code structure. `FieldMapper.IGNORE_MALFORMED_SETTING` was in 2 but now is in 1. The reason is that by the time 2 is applied it's too late to "fix" mapping of `@timestamp` with it in mind.

**Comment by kkrik-es** [comment]
> No more 8.16 releases will happen, so back porting this to 8.x and 8.17 branches is sufficient.

I see a FFreeze 8.16.3 on the cal?

**Comment by martijnvg** [comment]
> I see a FFreeze 8.16.3 on the cal?

I don't see a dev issue for it and given that 8.17.0 has been released, it means no 8.16.x releases will happen.
