### PR TITLE
Fix for issue 119723

### LINKED ISSUE #119723: [CI] HighlightBuilderTests.testInvalidMaxAnalyzedOffset failing
### CI Link

https://buildkite.com/elastic/elasticsearch-pull-request/builds/49210#0194425e-e5c7-483c-83db-840864b6b8c0

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.search.fetch.subphase.highlight.HighlightBuilderTests.testInvalidMaxAnalyzedOffset" -Dtests.seed=A37DB756B4D5F422 -Dtests.locale=ee-Latn-GH -Dtests.timezone=Etc/GMT+11 -Druntime.java=23

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
HighlightBuilderTests > testInvalidMaxAnalyzedOffset FAILED
    junit.framework.AssertionFailedError: Expected exception XContentParseException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([A37DB756B4D5F422:C77F7E165821388F]:0)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2889)
        at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2875)
        at org.elasticsearch.search.fetch.subphase.highlight.HighlightBuilderTests.expectParseThrows(HighlightBuilderTests.java:182)
        at org.elasticsearch.search.fetch.subphase.highlight.HighlightBuilderTests.testInvalidMaxAnalyzedOffset(HighlightBuilderTests.java:578)
```

### PR DESCRIPTION
**Pull request by svilen-mihaylov-elastic**
Adjust random parameter generator to exclude newly valid value (-1)

Closes #119723

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightBuilderTests.java [hunk 1]
```diff
@@ -574,11 +574,10 @@ public void testPreTagsWithoutPostTags() throws IOException {
         assertEquals("pre_tags are set but post_tags are not set", e.getCause().getCause().getMessage());
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/119723")
     public void testInvalidMaxAnalyzedOffset() throws IOException {
         XContentParseException e = expectParseThrows(
             XContentParseException.class,
-            "{ \"max_analyzed_offset\" : " + randomIntBetween(-100, -1) + "}"
+            "{ \"max_analyzed_offset\" : " + randomIntBetween(-100, -2) + "}"
```
Comment (svilen-mihaylov-elastic) [inline server/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightBuilderTests.java:580]: Sorry, I thought -1 was exclusive upper bound, should have checked closer.

**Review by mayya-sharipova — APPROVED** [review]
Thanks @svilen-mihaylov-elastic

**Comment by svilen-mihaylov-elastic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/122552)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
