### PR TITLE
[Inference API] Fix inference initialization thread exhaustion

### LINKED ISSUE #147290: [Inference API] Http sender startup failed
### Elasticsearch Version

9.2.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

In this PR: https://github.com/elastic/elasticsearch/pull/135462

We introduced async initialization logic for the inference API. When a node restarts we have observed that it can report failures for the initialization logic taking too long.

This is likely a race condition where the inference API threadpool is starved because multiple requests are waiting and using threads which prevents the `RequestExecutorService` from actually starting.

### Steps to Reproduce

N/A

### Logs (if relevant)

Stacktrace

```
"java.lang.IllegalStateException: Http sender startup did not complete in time
	at org.elasticsearch.inference@9.5.0/org.elasticsearch.xpack.inference.external.http.sender.HttpRequestSender.waitForStartToComplete(HttpRequestSender.java:175)
	at org.elasticsearch.inference@9.5.0/org.elasticsearch.xpack.inference.external.http.sender.HttpRequestSender.waitForStartToCompleteWithListener(HttpRequestSender.java:147)
	at org.elasticsearch.inference@9.5.0/org.elasticsearch.xpack.inference.external.http.sender.HttpRequestSender.lambda$startAsynchronously$1(HttpRequestSender.java:125)
	at org.elasticsearch.server@9.5.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:1047)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1516)
	Suppressed: java.lang.IllegalStateException: Http sender startup did not complete in time
		... 7 more
"
```

### PR DESCRIPTION
**Pull request by jonathan-buttner**
This PR fixes some errors we've seen when the first inference API request is received for a node. The stacktrace indicates that waiting for the initialization to complete times out.

The issue is there's a potential for exhausting the inference utility threadpool while waiting for internal services to initialize.

My understanding is that the issue is temporary. Once some of the threads have finished timing out the actual initialization can be performed and requests should begin working.

This PR refactors the logic in a few ways:
- Only the first request to kick off the initialization will use a thread execute, additional calls are queued in a subscribing listener which if succeeded/failed will do so for all the queued listeners
- I also moved the `startAsynchronously()` call to be done in the `send*()` methods. This guarantees that it'll be called in all paths. Previously we were making a direct call to `startAsynchronously()` before each
- `HttpRequestSender::startSynchronously()` now throws. Once we refactor Amazon Bedrock to not leverage SenderService we should be able to drop `startSynchronously()` from the interface entirely

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 1]
```diff
@@ -201,14 +198,15 @@ public void send(
         @Nullable TimeValue timeout,
         ActionListener<InferenceServiceResults> listener
     ) {
-        assert startInitiated.get() : "call start() before sending a request";
-        waitForStartToComplete();
-        service.execute(requestCreator, inferenceInputs, timeout, listener);
+        SubscribableListener.<Void>newForked(l -> startAsynchronously(l, timeout))
+            .<InferenceServiceResults>andThen(sendListener -> service.execute(requestCreator, inferenceInputs, timeout, sendListener))
+            .addListener(listener);
     }
```
[the remark this answers is not in the document]
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: Good feedback, I'll fix this.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java [hunk 2]
```diff
@@ -225,11 +229,11 @@ public void embeddingInfer(Model model, EmbeddingRequest request, TimeValue time
                 return;
             }
             if (supportsMultipleItemsPerContent()) {
-                doEmbeddingInfer(model, request, resolvedInferenceTimeout, embeddingInferListener);
+                doEmbeddingInfer(model, request, resolvedInferenceTimeout, listener);
             } else {
                 var index = indexContainingMultipleInferenceStrings(request.inputs());
                 if (index == null) {
-                    doEmbeddingInfer(model, request, resolvedInferenceTimeout, embeddingInferListener);
+                    doEmbeddingInfer(model, request, timeout, listener);
```
[the remark this answers is not in the document]
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java]: Good catch, this was a mistake when resolving merge conflicts. I'll fix it.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java [hunk 3]
```diff
@@ -323,35 +404,13 @@ public void testSendWithoutQueuing_SendsRequestAndReceivesResponse() throws Exce
...
 
-            var result = listener.actionGet(TIMEOUT);
+            var result = listener.actionGet(TEST_REQUEST_TIMEOUT);
             assertThat(result, instanceOf(ElasticInferenceServiceAuthorizationResponseEntity.class));
             var authResponse = (ElasticInferenceServiceAuthorizationResponseEntity) result;
             assertThat(authResponse.authorizedEndpoints(), is(elserResponse.responseEntity().authorizedEndpoints()));
         }
     }
 
-    public void testHttpRequestSender_Throws_WhenCallingSendBeforeStart() throws Exception {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java:333]: No longer applicable since we call start in the send*() calls.

**Comment by jonathan-buttner** [comment]
@coderabbitai full review

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 4]
```diff
@@ -57,126 +57,98 @@ public Factory(ServiceComponents serviceComponents, HttpClientManager httpClient
...
+                contextPreservedListener,
+                ignored -> contextPreservedListener.onFailure(
+                    new ElasticsearchStatusException("Http sender startup did not complete in time", RestStatus.SERVICE_UNAVAILABLE)
+                )
+            )
+            : contextPreservedListener;
+        // All callers — first and concurrent — register here. SubscribableListener fires immediately
+        // if startup is already done, otherwise queues the listener until startInternal completes.
+        startupNotifier.addListener(wrappedListener);
     }
```
[the remark this answers is not in the document]
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: Good catch, this should be fixed now.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 5]
```diff
@@ -9,12 +9,16 @@
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:9]: Give close attention to the changes in this file because they're fundamental to how sending a request works within the inference API.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 6]
```diff
@@ -84,99 +72,92 @@ public Sender createSender() {
...
+                threadPool.executor(UTILITY_THREAD_POOL_NAME),
+                contextPreservedListener,
+                ignored -> contextPreservedListener.onFailure(
+                    new ElasticsearchStatusException("Http sender startup did not complete in time", RestStatus.SERVICE_UNAVAILABLE)
+                )
+            )
+            : contextPreservedListener;
+        // All callers — first and concurrent — register here. SubscribableListener fires immediately
+        // if startup is already done, otherwise queues the listener until startInternal completes.
+        startupNotifier.addListener(wrappedListener);
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:143]: This requires [SubscribableListener](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/support/SubscribableListener.java) to be thread safe. My understanding is that it is. Best to double check me though.

We should be able to see it's thread safety in it's tests too: https://github.com/elastic/elasticsearch/blob/main/server/src/test/java/org/elasticsearch/action/support/SubscribableListenerTests.java#L182

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java [hunk 7]
```diff
@@ -109,11 +109,13 @@ public void infer(
         @Nullable TimeValue timeout,
         ActionListener<InferenceServiceResults> listener
     ) {
-        SubscribableListener.newForked(this::init).<InferenceServiceResults>andThen((inferListener) -> {
+        try {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java:112]: We don't really need SubscribableListener anymore since we aren't calling `andThen()` anymore.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java [hunk 8]
```diff
@@ -213,7 +217,7 @@ protected boolean supportsChatCompletionReasoning() {
 
     @Override
     public void embeddingInfer(Model model, EmbeddingRequest request, TimeValue timeout, ActionListener<InferenceServiceResults> listener) {
-        SubscribableListener.newForked(this::init).<InferenceServiceResults>andThen((embeddingInferListener) -> {
+        try {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java:291]: @DonalEvans double check me here because I originally had some merge conflicts with the resolved timeout changes.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 9]
```diff
@@ -84,99 +72,101 @@ public Sender createSender() {
...
+            ? ListenerTimeouts.wrapWithTimeout(
+                threadPool,
+                timeout,
+                threadPool.executor(UTILITY_THREAD_POOL_NAME),
+                contextPreservedListener,
+                ignored -> contextPreservedListener.onFailure(
+                    new ElasticsearchStatusException("Http sender startup did not complete in time", RestStatus.SERVICE_UNAVAILABLE)
+                )
+            )
+            : contextPreservedListener;
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: I think this is slightly easier to read as:
```
var wrappedListener = timeout == null ? contextPreservedListener : ListenerTimeouts.wrapWithTimeout(
    threadPool,
    timeout,
    threadPool.executor(UTILITY_THREAD_POOL_NAME),
    contextPreservedListener,
    ignored -> contextPreservedListener.onFailure(
        new ElasticsearchStatusException("Http sender startup did not complete in time", RestStatus.SERVICE_UNAVAILABLE)
    )
);
```

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 6 above)
Comment (DonalEvans) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:143]: It's certainly supposed to be thread safe. I think that if it's not, we'd have a lot of problems outside of this use.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java [hunk 10]
```diff
@@ -18,17 +18,37 @@
 import java.io.Closeable;
 
 public interface Sender extends Closeable {
+
+    /**
+     * Initialize the sender synchronously. This must be called before calling {@link #send} or {@link #sendWithoutQueuing}.
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java]: Nitpick, but would it be more accurate to say that the start methods must be called before **or as part of** calling `send()` or `sendWithoutQueuing()`, since that's what `HttpRequestSender` does?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java (hunk 8 above)
Comment (DonalEvans) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java:291]: Looks good.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java [hunk 11]
```diff
@@ -419,24 +427,20 @@ protected boolean supportsChunkedInfer() {
     }
 
     public void start(Model model, ActionListener<Boolean> listener) {
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java]: I think we can inline this method now, since it's only called in tests.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java [hunk 12]
```diff
@@ -419,24 +427,20 @@ protected boolean supportsChunkedInfer() {
...
+        start(model, null, listener);
     }
 
     @Override
-    public void start(Model model, @Nullable TimeValue unused, ActionListener<Boolean> listener) {
-        start(model, listener);
+    public void start(Model model, @Nullable TimeValue timeout, ActionListener<Boolean> listener) {
+        SubscribableListener.<Void>newForked(l -> sender.startAsynchronously(l, timeout))
+            .<Boolean>andThen((doStartListener) -> doStart(model, doStartListener))
+            .addListener(listener);
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java]: It's a little awkward that we need to wait for `startAsynchronously()` to complete and then complete a new listener with a boolean here. Would it make sense to change `start()` to take `ActionListener<Void>` instead of `ActionListener<Boolean>`? We don't seem to actually use the boolean value returned by the listener anywhere, and I'm not sure in what situation we'd ever complete with false instead of just failing the listener with an exception.

If we make the listener passed in here `ActionListener<Void>` then I think we can simplify the method to just:
```
public void start(Model model, @Nullable TimeValue timeout, ActionListener<Void> listener) {
    sender.startAsynchronously(listener, timeout);
}
```

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java [hunk 13]
```diff
@@ -144,59 +165,121 @@ public void testStart_ThrowsExceptionWaitingForStartToComplete_WhenAnErrorOccurs
...
+            var exception = expectThrows(ElasticsearchException.class, () -> startSynchronously(sender));
 
-            assertThat(exception.getMessage(), is("failed"));
+            assertThat(exception.getMessage(), is("Failed to initialize inference components"));
+            assertThat(exception.getCause().getMessage(), is("failed"));
         }
     }
 
-    public void testStart_ThrowsExceptionWaitingForStartToComplete() {
+    public void testStartSync_ThrowsServiceUnavailableWhenStartupTimesOut() {
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java]: This test doesn't actually call `HttpRequestSender.startSynchronously()`, since that method is deprecated and throws, so I think it should just be removed to avoid confusion. It's functionally the same as `testStartAsync_ThrowsServiceUnavailableWhenStartupTimesOut()`, except with the `actionGet()` call hidden in the static `startSynchronously()` method.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java [hunk 14]
```diff
@@ -144,59 +165,121 @@ public void testStart_ThrowsExceptionWaitingForStartToComplete_WhenAnErrorOccurs
...
+        sender.startAsynchronously(timedListener, TimeValue.timeValueMillis(1));
+        var ex = expectThrows(ElasticsearchStatusException.class, () -> timedListener.actionGet(TEST_REQUEST_TIMEOUT));
+        assertThat(ex.getMessage(), is("Http sender startup did not complete in time"));
+        assertThat(ex.status(), is(RestStatus.SERVICE_UNAVAILABLE));
 
-        var listenerCompleted = new PlainActionFuture<Void>();
-        sender.startAsynchronously(listenerCompleted);
-        assertNull(listenerCompleted.actionGet(TIMEOUT));
+        // Unblock startup so startupNotifier resolves successfully
+        blockStartLatch.countDown();
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java:207]: This test could get a little more coverage if we add two listeners before calling `blockStartLatch.countDown()`, one with a very short timeout that we expect to fail (like the test is already doing) and one with a longer timeout (or no timeout at all) that we expect to succeed after we count down the latch. That way we also get confirmation that if there are multiple listeners queued and one times out, the other queued ones aren't impacted, which isn't currently covered here.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 15]
```diff
@@ -57,25 +58,12 @@ public Factory(ServiceComponents serviceComponents, HttpClientManager httpClient
...
             var executorServiceSettings = new RequestExecutorServiceSettings(serviceComponents.settings());
             executorServiceSettings.init(clusterService);
 
-            var service = new RequestExecutorService(
-                serviceComponents.threadPool(),
-                startCompleted,
-                executorServiceSettings,
-                requestSender
-            );
+            var service = new RequestExecutorService(serviceComponents.threadPool(), null, executorServiceSettings, requestSender);
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: Since we now always pass `null` as the start-completed latch here could we remove the argument entirely? Tests can be reworked if needed.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 16]
```diff
@@ -84,99 +72,101 @@ public Sender createSender() {
...
-        } else {
-            listener.onResponse(null);
+            try {
+                threadPool.executor(UTILITY_THREAD_POOL_NAME).execute(this::startInternal);
+            } catch (Exception e) {
+                // Consider making this an error log because it's not recoverable
+                logger.warn("Failed to execute http sender start thread", e);
+                startupNotifier.onFailure(
+                    new ElasticsearchStatusException(
+                        "Failed to begin initializing inference components",
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:120]: Should we reword this to `Failed to initialize inference components`?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 9 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: ++

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java (hunk 10 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java]: At the moment it's a bit confusing as the bedrock implementation does not start itself on send. At the moment, it seems like `startAsynchronously()` is called from a few other places (e.g. on PUT).

I think we should clarify what the contract is here: do users of `Sender` need to manage starting or not? If not, I'd remove the start methods entirely from the interface.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java (hunk 12 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java]: ++

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java [hunk 17]
```diff
@@ -410,6 +464,84 @@ public void testSendWithoutQueuingWithTimeout_Throws_WhenATimeoutOccurs() throws
         }
     }
 
+    public void testConcurrentSend_OnlyStartsOnce() throws Exception {
+        // At a minimum we need 1 for the startAsynchronously to kick off the init tasks
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java]: Do we need to give the pool 2 threads in order to properly check tasks are only started once? Having a single thread forces start to be finished effectively before it can be run again.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java (hunk 12 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java]: I think the interface was originally designed that way to support whether an ML deployment was started:

https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/elasticsearch/BaseElasticsearchInternalService.java#L130

Which is called here: https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/TransportPutInferenceModelAction.java#L313

Doesn't look like the boolean is used in the response so we could remove it. I'll create an issue to remove the Boolean aspect. For `SenderService`, I think we can refactor because it doesn't seem like any services override `doStart()` so we can probably remove that and simply the method but for now I think I'll leave the Boolean portion.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 18]
```diff
@@ -201,14 +192,15 @@ public void send(
         @Nullable TimeValue timeout,
         ActionListener<InferenceServiceResults> listener
     ) {
-        assert startInitiated.get() : "call start() before sending a request";
-        waitForStartToComplete();
-        service.execute(requestCreator, inferenceInputs, timeout, listener);
+        SubscribableListener.<Void>newForked(l -> startAsynchronously(l, STARTUP_TIMEOUT))
```
Comment (Jan-Kazlouski-elastic) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: Perhaps we would want to change it to more meaningful variable name for clarity?
Param can be renamed to `actionListener` and this one to just `listener`

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java (hunk 12 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/SenderService.java]: https://github.com/elastic/elasticsearch/issues/147709

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java [hunk 19]
```diff
@@ -84,99 +72,101 @@ public Sender createSender() {
...
-        } else if (startCompleted.get() == false) {
-            var preservedListener = ContextPreservingActionListener.wrapPreservingContext(listener, threadPool.getThreadContext());
-            // wait on another thread so we don't potential block a transport thread
-            threadPool.executor(UTILITY_THREAD_POOL_NAME).execute(() -> waitForStartToCompleteWithListener(preservedListener));
-        } else {
-            listener.onResponse(null);
+            try {
+                threadPool.executor(UTILITY_THREAD_POOL_NAME).execute(this::startInternal);
+            } catch (Exception e) {
+                // Consider making this an error log because it's not recoverable
```
Comment (Jan-Kazlouski-elastic) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:116]: I think this comment is valid. If it is not recoverable - it **_should_** be ERROR level. Because it is reserved for unrecoverable states.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java (hunk 10 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java]: > At the moment it's a bit confusing as the bedrock implementation does not start itself on send. At the moment, it seems like startAsynchronously() is called from a few other places (e.g. on PUT).

Yeah Bedrock needs to be completely refactored. It should be more like the SageMaker integration because it doesn't need to rely on the SenderService functionality at all because the internal SDK handles rate limiting already.

We have an issue for that refactoring, but we haven't gotten to it yet. Once Bedrock no longer depends on `SenderService` then we can remove the `startSynchronously()` method.

You make a good point about `PUT` though. I don't think we need `SenderService::start()` to call `start*()` at all because the validation in the `PUT` logic calls the `send*()` first. I think the `SenderService::start()` can be a noop actually.

Then I think we can remove the `startAsync/Sync()` from the interface.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java [hunk 20]
```diff
@@ -18,17 +18,37 @@
...
+     * @deprecated use {@link #startAsynchronously} instead.
+     */
     void startSynchronously();
 
-    void startAsynchronously(ActionListener<Void> listener);
+    /**
+     * Initialize the sender asynchronously. This must be called before calling {@link #send} or {@link #sendWithoutQueuing}.
+     * The listener will be notified when the initialization is complete or if it fails.
+     * @param listener the listener to notify when initialization is complete or if it fails
+     * @param timeout the maximum time to wait for initialization to complete. If null, the implementation should use a default timeout.
```
Comment (Jan-Kazlouski-elastic) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java]: It says `If null, the implementation should use a default timeout`.
Correct me if I'm wrong, but I can see an implication here that some default timeout exists within the `startAsynchronously` method. But that is not true. Timeout for startup is only passed from `send` and `start` methods. There is no default timeout wrapping happening inside if it is passed as null. I think that javadoc is misleading.
We should either make code enforce some default timeout or change the javadoc.

Also If for `send` we have 5 sec default timeout, for `start` we'll be waiting forever if `null` is passed.

**Review by Jan-Kazlouski-elastic — COMMENTED** [review]
Great job Jonathan. Left a few small comments.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 15 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java]: Tests of the `RequestExecutorService` leverage it so I'll expose a different constructor 👍

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 16 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:120]: I intentionally made the string different from the one below so it'd be easier to differentiate between the two errors if we got an SDH or something. I can make them the same though if you'd like. We'll have to logs which should have a stacktrace.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java (hunk 17 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSenderTests.java]: Yeah good point.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 19 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:116]: Good call out. I'll create an issue: https://github.com/elastic/elasticsearch/issues/147731

I'd like these changes to be in prod for a bit before we switch to using error logs in case we have a failure. Error logs will trigger alerts by default.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java (hunk 20 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java]: Good call out. I've refactored this so the `start()` doesn't exist anymore. Take a look and let me know if I missed something though.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 6 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:143]: One clarification, I think this is the first time in the inference API where multiple threads can access the same `SubscriableListener`. In most (all?) places we do a `SubscribableListener.newForked()` which is creating unique instances on each thread.

This method's behavior is using the same instance, and I'm intentionally not adding locking around it because it's a hot path.

**Review by DonalEvans — APPROVED** [review]

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java (hunk 19 above)
Comment (Jan-Kazlouski-elastic) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/HttpRequestSender.java:116]: Good thinking. I agree.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java (hunk 20 above)
Comment (Jan-Kazlouski-elastic) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/Sender.java]: Thanks @jonathan-buttner 
I believe that solves it. We could inline timeout value because it is null only in tests, but I think it is more handy for testing purposes and more future-proof to have it as a param. So it is up to you.

**Review by Jan-Kazlouski-elastic — APPROVED** [review]
Thanks for the fixes @jonathan-buttner 
This PR looks good to me.

**Comment by jonathan-buttner** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/148151)|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/148153)|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/148157)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
