### PR TITLE
Fix explain output for dfs query

### LINKED ISSUE #15369: score and explanation for dfs queries don't match
Tested 1.7 vs 2.1. The following example:

```
POST test/doc/1
{
  "text": "Score and explanation should match I think?"
}

POST test/doc/2
{
  "text": "Score and explanation did match in 1.7..."
}


GET test/_search?search_type=dfs_query_then_fetch&explain
{
  "query": {
    "match": {
      "text": "score"
    }
  }
}
```

for 1.7.0 returns:

```
{
   "took": 48,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": 0.22295055,
      "hits": [
         {
            "_shard": 2,
            "_node": "5IoTIXdmROKObfLRmqCQYQ",
            "_index": "test",
            "_type": "doc",
            "_id": "1",
            "_score": 0.22295055,
            "_source": {
               "text": "Score and explanation should match I think?"
            },
            "_explanation": {
               "value": 0.22295056,
               "description": "weight(text:score in 0) [PerFieldSimilarity], result of:",
               "details": [
                  {
                     "value": 0.22295056,
                     "description": "score(doc=0,freq=1.0), product of:",
                     "details": ```
         {
            "_shard": 2,
            "_node": "8AbQaexnTwKbvcL1Va4yfw",
            "_index": "test",
            "_type": "doc",
            "_id": "1",
            "_score": 0.22295055,
            "_source": {
               "text": "Score and explanation should match I think?"
            },
            "_explanation": {
               "value": 0.22295056,
               "description": "weight(text:score in 0) [PerFieldSimilarity], result of:",[
                        {
                           "value": 0.99999994,
                           "description": "queryWeight, product of:",
                           "details": [
                              {
                                 "value": 0.5945349,
                                 "description": "idf(docFreq=2, maxDocs=2)"
                              },
                              {
                                 "value": 1.681987,
                                 "description": "queryNorm"
                              }
                           ]
                        },
                        {
                           "value": 0.22295058,
                           "description": "fieldWeight in 0, product of:",
                           "details": [
                              {
                                 "value": 1,
                                 "description": "tf(freq=1.0), with freq of:",
                                 "details": [
                                    {
                                       "value": 1,
                                       "description": "termFreq=1.0"
                                    }
                                 ]
                              },
                              {
                                 "value": 0.5945349,
                                 "description": "idf(docFreq=2, maxDocs=2)"
                              },
                              {
                                 "value": 0.375,
                                 "description": "fieldNorm(doc=0)"
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         },
         {
            "_shard": 3,
            "_node": "5IoTIXdmROKObfLRmqCQYQ",
            "_index": "test",
            "_type": "doc",
            "_id": "2",
            "_score": 0.22295055,
            "_source": {
               "text": "Score and explanation did match in 1.7..."
            },
            "_explanation": {
               "value": 0.22295056,
               "description": "weight(text:score in 0) [PerFieldSimilarity], result of:",
               "details": [
                  {
                     "value": 0.22295056,
                     "description": "score(doc=0,freq=1.0), product of:",
                     "details": [
                        {
                           "value": 0.99999994,
                           "description": "queryWeight, product of:",
                           "details": [
                              {
                                 "value": 0.5945349,
                                 "description": "idf(docFreq=2, maxDocs=2)"
                              },
                              {
                                 "value": 1.681987,
                                 "description": "queryNorm"
                              }
                           ]
                        },
                        {
                           "value": 0.22295058,
                           "description": "fieldWeight in 0, product of:",
                           "details": [
                              {
                                 "value": 1,
                                 "description": "tf(freq=1.0), with freq of:",
                                 "details": [
                                    {
                                       "value": 1,
                                       "description": "termFreq=1.0"
                                    }
                                 ]
                              },
                              {
                                 "value": 0.5945349,
                                 "description": "idf(docFreq=2, maxDocs=2)"
                              },
                              {
                                 "value": 0.375,
                                 "description": "fieldNorm(doc=0)"
                              }
                           ]
                        }
                     ]
                  }
               ]
            }
         }
      ]
   }
}

```

and in 2.1:

```
{
   "took": 46,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": 0.22295055,
      "hits": [
         {
            "_shard": 2,
            "_node": "hcC0CtAfTSSILbEq32T_fw",
            "_index": "test",
            "_type": "doc",
            "_id": "2",
            "_score": 0.22295055,
            "_source": {
               "text": "Score and explanation did match in 1.7..."
            },
            "_explanation": {
               "value": 0.11506981,
               "description": "weight(text:score in 0) [PerFieldSimilarity], result of:",
               "details": [
                  {
                     "value": 0.11506981,
                     "description": "fieldWeight in 0, product of:",
                     "details": [
                        {
                           "value": 1,
                           "description": "tf(freq=1.0), with freq of:",
                           "details": [
                              {
                                 "value": 1,
                                 "description": "termFreq=1.0",
                                 "details": []
                              }
                           ]
                        },
                        {
                           "value": 0.30685282,
                           "description": "idf(docFreq=1, maxDocs=1)",
                           "details": []
                        },
                        {
                           "value": 0.375,
                           "description": "fieldNorm(doc=0)",
                           "details": []
                        }
                     ]
                  }
               ]
            }
         },
         {
            "_shard": 3,
            "_node": "hcC0CtAfTSSILbEq32T_fw",
            "_index": "test",
            "_type": "doc",
            "_id": "1",
            "_score": 0.22295055,
            "_source": {
               "text": "Score and explanation should match I think?"
            },
            "_explanation": {
               "value": 0.11506981,
               "description": "weight(text:score in 0) [PerFieldSimilarity], result of:",
               "details": [
                  {
                     "value": 0.11506981,
                     "description": "fieldWeight in 0, product of:",
                     "details": [
                        {
                           "value": 1,
                           "description": "tf(freq=1.0), with freq of:",
                           "details": [
                              {
                                 "value": 1,
                                 "description": "termFreq=1.0",
                                 "details": []
                              }
                           ]
                        },
                        {
                           "value": 0.30685282,
                           "description": "idf(docFreq=1, maxDocs=1)",
                           "details": []
                        },
                        {
                           "value": 0.375,
                           "description": "fieldNorm(doc=0)",
                           "details": []
                        }
                     ]
                  }
               ]
            }
         }
      ]
   }
}

```

### PR DESCRIPTION
**Pull request by jimczi**
ContextIndexSearcher#explain ignores the dfs data to create the normalized weight.
This change fixes this discrepancy by using the dfs data to create the normalized weight when needed.

Fixes #15369

### CODE REVIEW

**Comment by javanna** [comment]
I gues this fix is correct, but can you please write a test for it? ;)

**Comment by jimferenczi** [comment]
Thanks @javanna. 
I pushed a small test to validate that the fix is correct, could you please review it ?

File: core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java [hunk 1]
```diff
@@ -317,6 +326,11 @@ public void testDfsQueryAndFetch() throws Exception {
             SearchHit hit = searchResponse.getHits().hits()[i];
 //            System.out.println(hit.shard() + ": " +  hit.explanation());
             assertThat(hit.explanation(), notNullValue());
+            assertThat(hit.explanation().getDetails().length, equalTo(1));
+            assertThat(hit.explanation().getDetails()[0].getDetails().length, equalTo(2));
+            assertThat(hit.explanation().getDetails()[0].getDetails()[0].getDescription(),
+                endsWith("idf(docFreq=100, docCount=100)"));
+            assertThat(hit.explanation(), notNullValue());
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: this last line is redundant I think, we already check the same above

File: core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java [hunk 2]
```diff
@@ -146,6 +147,10 @@ public void testDfsQueryThenFetch() throws Exception {
             }
             for (int i = 0; i < hits.length; ++i) {
                 SearchHit hit = hits[i];
+                assertThat(hit.explanation().getDetails().length, equalTo(1));
+                assertThat(hit.explanation().getDetails()[0].getDetails().length, equalTo(2));
+                assertThat(hit.explanation().getDetails()[0].getDetails()[0].getDescription(),
+                    endsWith("idf(docFreq=100, docCount=100)"));
                 assertThat(hit.explanation(), notNullValue());
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: should this be moved up?

File: core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java [hunk 3]
```diff
@@ -170,6 +175,10 @@ public void testDfsQueryThenFetchWithSort() throws Exception {
...
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: should this be moved up?

Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: should this be moved up?

File: core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java [hunk 4]
```diff
@@ -317,6 +326,11 @@ public void testDfsQueryAndFetch() throws Exception {
...
 //            System.out.println(hit.shard() + ": " +  hit.explanation());
             assertThat(hit.explanation(), notNullValue());
+            assertThat(hit.explanation().getDetails().length, equalTo(1));
+            assertThat(hit.explanation().getDetails()[0].getDetails().length, equalTo(2));
+            assertThat(hit.explanation().getDetails()[0].getDetails()[0].getDescription(),
+                endsWith("idf(docFreq=100, docCount=100)"));
+            assertThat(hit.explanation(), notNullValue());
 //            assertThat("id[" + hit.id() + "]", hit.id(), equalTo(Integer.toString(100 - i - 1)));
             assertThat("make sure we don't have duplicates", expectedIds.remove(hit.id()), notNullValue());
         }
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: should we add the assertions to other methods in this class that use dfs?

Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: ignore this, sorry for the noise :)

Comment (jimferenczi) [inline core/src/test/java/org/elasticsearch/search/basic/TransportTwoNodesSearchIT.java]: ;)

**Comment by javanna** [comment]
LGTM, but I am not too familiar with dfs so I would prefer @jpountz to have a quick second look.

**Comment by jpountz** [comment]
LGTM!

**Comment by jimferenczi** [comment]
Thansk @javanna and @jpountz !
