### PR TITLE
Fix max-int limit for number of points reduced in geo_centroid

### LINKED ISSUE #55992: Int 32 overflow on geo centroid aggregation
https://github.com/elastic/elasticsearch/blob/6f244eb167edb7a4d262fb7626ffc9cdb2c8d60a/server/src/main/java/org/elasticsearch/search/aggregations/metrics/geocentroid/InternalGeoCentroid.java#L109

We have a Elasticsearch with billions of docs with geopoint and this local variable (int totalCount) is being overflowed when a bucket has more than 2.147Bi docs.

### PR DESCRIPTION
**Pull request by talevy**
A bug in InternalGeoCentroid#reduce existed that summed up
the aggregation's long-valued counts into a local integer variable.
Since it is definitely possible to reduce more than Integer.MAX points,
this change simply updates that variable to be a long-valued number.

Closes #55992.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java [hunk 1]
```diff
@@ -115,7 +115,7 @@ public long count() {
     public InternalGeoCentroid reduce(List<InternalAggregation> aggregations, ReduceContext reduceContext) {
         double lonSum = Double.NaN;
         double latSum = Double.NaN;
-        int totalCount = 0;
+        long totalCount = 0;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java:118]: Huh! The `count` member variable was always a long!

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroidTests.java [hunk 2]
```diff
@@ -67,6 +70,16 @@ protected void assertReduced(InternalGeoCentroid reduced, List<InternalGeoCentro
         assertEquals(totalCount, reduced.count());
     }
 
+    public void testReduceMaxCount() {
+        InternalGeoCentroid maxValueGeoCentroid = new InternalGeoCentroid("agg", new GeoPoint(10, 0),
+            Long.MAX_VALUE, Collections.emptyMap());
+        InternalGeoCentroid reducingGeoCentroid = new InternalGeoCentroid("agg", new GeoPoint(10, 0),
+            randomNonNegativeLong(), Collections.emptyMap());
+        InternalGeoCentroid reducedGeoCentroid = reducingGeoCentroid
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroidTests.java:78]: Usually the reducing result is in the list, right?

Comment (talevy) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroidTests.java:78]: I suppose I was not really interested in the semantics of how this method was used in the real world, and more interested in the reduce logic itself -- as it is returned. should I change this?

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java (hunk 1 above)
Comment (talevy) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java:118]: yup!

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroidTests.java (hunk 2 above)
Comment (nik9000) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroidTests.java:78]: It'd make me feel better if you did `maxValueGeoCentroid.reduce(singletonList(maxValueGeoCentroid), null)`.

Comment (talevy) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroidTests.java]: done

**Review by nik9000 — APPROVED** [review]
Much :heart:

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java (hunk 1 above)
Comment (iverase) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/InternalGeoCentroid.java:118]: Huh!

**Comment by talevy** [comment]
thanks Nik!
