### PR TITLE
[ILM] Fix Move To Step API causing ILM to hang

### LINKED ISSUE #34294: [ILM] Move to step API does not work if moving to a new phase
The move to step API in ILM only works if the current and next step are in the same phase. This is because the API blindly move the index to the target step and does not do the extra steps like injecting the new phase definition if the phase is different.

### PR DESCRIPTION
**Pull request by AthenaEryma**
The Move To Step API now checks to see if the target step is an
AsyncActionStep, and if so, runs it.

AsyncActionSteps are otherwise only run when they are entered by
executing the previous step, rather than periodically or on cluster state 
updates, so if an AsyncActionStep was entered via the Move To Step API, ILM
would never touch that index again.

Fixes #34294

### CODE REVIEW

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java [hunk 1]
```diff
@@ -62,6 +62,16 @@ public ClusterState execute(ClusterState currentState) {
                         request.getNextStepKey());
                 }
 
+                @Override
+                public void clusterStateProcessed(String source, ClusterState oldState, ClusterState newState) {
+                    IndexMetaData newIndexMetaData = newState.metaData().index(indexMetaData.getIndex());
+                    if (newIndexMetaData == null) {
```
Comment (talevy) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: can this occur due to batching of updates?

Comment (colings86) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: After talking with @DaveCTurner it seems like we won't have any batching here because batching occurs within the same instance of `ClusterStateTaskExecutor` and we don't implement batching ourselves here. However I think this check is still nice to have in case there are other factors at play.

**Review by colings86 — APPROVED** [review]
Left a reply on your comment but this LGTM

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: Can this be `assert newIndexMetaData != null`?

Comment (talevy) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: I like David's suggestion here, as it suggests this should never happen more strongly than an if

Comment (colings86) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: An assert is less strong though? because the check will not be done in production code, only in tests.

If we can envisage any scenarios where the `newState` passed to this method can be different to the state we returned in `execute()` then I think this whould stay as an `if` statement so we don't end up in a situation where we have a NPE thrown here because the index was deleted. IF we are confident that this kind of scenario should never occur and assert is fine.

Comment (talevy) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: right. I guess I don't see this hurting, so I won't block it, but it may be misleading to people new to the code to walk through state in which this may be possible.

Comment (gwbrown) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: We could add something like `assert false : "there should be no opportunity for the index to be deleted"` inside the if - that way we can catch it in testing while still handling it in production if there's a case we missed.  Does that sound reasonable, or is it too messy?

**Comment by gwbrown** [comment]
@elasticmachine retest this please

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java (hunk 1 above)
Comment (colings86) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: Lets add an `assert newIndexMetaData != null` for testing but leave the if statement for production so we don't NPE if this ever does happen.

Comment (colings86) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/action/TransportMoveToStepAction.java]: I think we should leave this with the if statement so we are protected against NPEs. If we also want to add an assert to catch things in tests then that fine but I think the protection against a NPE in production should remain
