### PR TITLE
Fix edge case in "_terms_enum" API for ip fields

### LINKED ISSUE #142811: [CI] TermsEnumTests testTermsEnumIPRandomized failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11890 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/typo65nn27nii)
- [elasticsearch-periodic-platform-support #11890 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/uhrb3okyv3wh4)
- [elasticsearch-pull-request #122282 / part-2](https://gradle-enterprise.elastic.co/s/fumuw7n4pu3do)
- [elasticsearch-pull-request #122274 / part-2](https://gradle-enterprise.elastic.co/s/wfxxp4zroxuro)
- [elasticsearch-pull-request #121874 / part-2](https://gradle-enterprise.elastic.co/s/ugs27jbcjnrsk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:core:test" --tests "org.elasticsearch.xpack.core.termsenum.TermsEnumTests.testTermsEnumIPRandomized" -Dtests.seed=4ED6E49608803825 -Dtests.locale=en-NL -Dtests.timezone=America/Vancouver -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.core.termsenum.TermsEnumTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTermsEnumIPRandomized'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected 1 for prefix 0 but was 0, [] expected:<1> but was:<0>
```

**Issue Reasons:**
- [main] 2 consecutive failures in step rocky-8_platform-support-unix
- [main] 5 failures in test testTermsEnumIPRandomized (1.2% fail rate in 428 executions)
- [main] 2 failures in step rocky-8_platform-support-unix (50.0% fail rate in 4 executions)
- [main] 3 failures in step part-2 (1.1% fail rate in 274 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.1% fail rate in 269 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by cbuescher**
This change fixes an issue in the "_terms_enum" API for ip fields. When matching IPv6 addresses with a "0" prfix, we currently don't return addresses where the second IPv6 group isn't all 0s. Currently we expect no prefix with leading zeros to match any IPv6 address, because "_terms_enum" output returns the formatted compressed IPv6 address where leading zeros are compressed into "::". When the second group is non-zero however, this assumption isn't true so this change creates a special case for it. Also adding tests to verify and explain the changed assumptions.

Closes #142811

### CODE REVIEW

**Review by chrisparrinello — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/index/mapper/IpPrefixAutomatonUtilTests.java [hunk 1]
```diff
@@ -101,22 +102,38 @@ public void testBuildPrefixAutomaton() throws UnknownHostException {
...
+            assertTrue(accepts(a, "0:517::b12a:6a52:0:0"));
             assertFalse(accepts(a, "::1.1.2.3"));
             assertFalse(accepts(a, "1c7:21d6:ffff:ffff:6852:f279::"));
+            // the next is not an IP4 address, so the condensed display form we are expecting from the TermsEnum
+            // output is "::7f00:1" and shouldn't match
             assertFalse(accepts(a, "0000::127.0.0.1"));
+            assertEquals("::7f00:1", NetworkAddress.format(getByName("0000::127.0.0.1")));
+            // same for more than one leading 0, those get condensed to "::" in the terms API output, so we shouldn't match them
+            assertFalse(accepts(a, "0:0:0::127.0.0.1"));
+            assertEquals("::7f00:1", NetworkAddress.format(getByName("0000::127.0.0.1")));
```
Comment (spinscale) [inline server/src/test/java/org/elasticsearch/index/mapper/IpPrefixAutomatonUtilTests.java]: minor nit: this is a duplicate of the assertion three lines above? Did you want to use `0:0:0::127.0.0.1`?

Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/index/mapper/IpPrefixAutomatonUtilTests.java]: Ah yes, nicely spotted. This is of course a copy&paste error I will correct before merging.
