### PR TITLE
Re-enable some performance updates to ES|QL spec tests after resilience improvement to EsqlSpecTestCase

### LINKED ISSUE #134890: ESQL: re-apply the parallel loading of test data
### Description

Re-apply the changes that made parallel loading of data for the Spec tests, meaning reverting this https://github.com/elastic/elasticsearch/pull/134738 and, possibly this one https://github.com/elastic/elasticsearch/pull/134511

After an internal investigation from @craigtaverner, it is possible that a bug while creating the data is hidden. This can potentially aggravate a race condition in the `setup()` method in `EsqlSpecTestCase` where the `dataLoaded` boolean is not set to `true` even if the loading happens. If later parts of the loading process fail, the data will have been loaded, while the boolean remains `false`, so the next test will re-attempt the data load, leading to the error that shows that a resource already exists - `resource_already_exists_exception`.

Related to https://github.com/elastic/elasticsearch/pull/131949

### PR DESCRIPTION
**Pull request by craigtaverner**
Some recent test performance updates flushed out test fragility due to non-thread safety and other concurrency issues with test setup, and so two optimizations were reverted. A recent PR at #136780 added improved resiliency to concurrency issues in test setup which should allow us to bring back the performance optimizations.

The resiliency fix included in #136780 was originally extracted from the Views PR at https://github.com/elastic/elasticsearch/pull/134995, which, due to early issues in view creation/deleting during test setup was reliably exposing the same errors seen in https://github.com/elastic/elasticsearch/issues/134736, and so it seems likely it will also fix the issues seen in the optimizations.

Checklist:
 - [x] Add thread safety checks in index and dataset setup for tests (merged in #136780)
 - [x] Revert https://github.com/elastic/elasticsearch/pull/134738
 - [x] Revert https://github.com/elastic/elasticsearch/pull/134511

Fixes #134890

### CODE REVIEW

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java [hunk 1]
```diff
@@ -122,23 +123,59 @@ protected EsqlSpecTestCase(
...
+        }
+
+        private synchronized void reset() {
+            completed = false;
+            started = false;
+            failure = null;
+        }
+    }
+
+    private static final Protected INGEST = new Protected();
```
Comment (craigtaverner) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java:165]: In the Views PR we use a separate VIEWS protector, semi-decoupling views from index creation. We could break the index parts into finer grained stuff too, but I see risks with that.

**Comment by craigtaverner** [comment]
Sadly, we already see failures from the parallel data loading. I think the changes to EsqlSpecTestCase do give slightly better error messages, but not enough to determine the underlying cause. I'll do some local investigation to see if I can figure this out, otherwise revert that particular commit, and we deal with parallel data loading separately.

File: x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/MultiClusterSpecIT.java [hunk 2]
```diff
@@ -284,6 +284,44 @@ static Request[] cloneRequests(Request orig, int numClones) throws IOException {
...
+            }
+
+            @Override
+            public void onFailure(Exception exception) {
+                localResponse.completeExceptionally(exception);
+            }
+        });
+        try {
+            Response remote = remoteResponse.get();
+            Response local = localResponse.get();
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/MultiClusterSpecIT.java:322]: NIT: you could use `PlainActionFuture` instead of anonymous listeners implementations here.

Comment (craigtaverner) [reply x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/MultiClusterSpecIT.java:322]: Since this code comes from a revert of a revert of an approved PR, I do not want to fiddle with it.

**Review by astefan — COMMENTED** [review]
I can't tell what exactly is the novelty in this PR compared to the two previous ones it reverts. You had [this commit](https://github.com/elastic/elasticsearch/pull/136781/commits/7b6749debb702ce50c3c3b04f593b2dcb184844d) initially, but the code didn't make it in the final variant of the PR.

It would help me, at least, to compare what we did before and what this PR does **new** now, if you could point out in your changes or with a comment the relevant bits. Thanks.

**Comment by craigtaverner** [comment]
> I can't tell what exactly is the novelty in this PR compared to the two previous ones it reverts. You had [this commit](https://github.com/elastic/elasticsearch/pull/136781/commits/7b6749debb702ce50c3c3b04f593b2dcb184844d) initially, but the code didn't make it in the final variant of the PR.

Very good point. It turns out that the first commit you pointed out was actually also part of another PR, the one at https://github.com/elastic/elasticsearch/pull/136780, which was merged two weeks ago, and this this PR got those updates when it merged main, effectively erasing the first commit, since it replaced it. So the real fix has been in for a few weeks now, and this PR now represents only the two optimizations being reverted.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java [hunk 3]
```diff
@@ -429,18 +433,42 @@ private static void loadDataSetIntoEs(
...
+            ENRICH_POLICIES,
+            policy -> loadEnrichPolicy(client, policy.policyName, policy.policyFileName, logger),
+            "Failed to load enrich policies in parallel"
+        );
+
+    }
+
+    private static <T> void executeInParallel(List<T> items, IOConsumer<T> consumer, String errorMessage) {
+        Semaphore semaphore = new Semaphore(PARALLEL_THREADS);
+        ESTestCase.runInParallel(items.size(), i -> {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:462]: `ESTestCase.runInParallel` internally creates a thread per each task.
Today we have 47 data sets but we only want to populate 10 at the time. I believe it would be much cheaper to use `Executors.newFixedThreadPool(threads)` rather than create a thread per task, especially if we want to limit parallelism.
