### PR TITLE
Fix BWC assertion in GetFieldMappingsResponse

### LINKED ISSUE #49702: [CI] Failure in org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT
An assertion added in https://github.com/elastic/elasticsearch/pull/48815 is tripping in https://gradle-enterprise.elastic.co/s/el42prl447wfk/console-log#L5228 

It's this one:

```java
    GetFieldMappingsResponse(StreamInput in) throws IOException {
        super(in);
        int size = in.readVInt();
        Map<String, Map<String, FieldMappingMetaData>> indexMapBuilder = new HashMap<>(size);
        for (int i = 0; i < size; i++) {
            String index = in.readString();
            if (in.getVersion().before(Version.V_8_0_0)) {
                int typesSize = in.readVInt();
                assert typesSize == 1; // <--- trips
```

### PR DESCRIPTION
**Pull request by romseygeek**
Closes #49702

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/indices/mapping/get/GetFieldMappingsResponse.java [hunk 1]
```diff
@@ -66,7 +66,10 @@
             String index = in.readString();
             if (in.getVersion().before(Version.V_8_0_0)) {
                 int typesSize = in.readVInt();
-                assert typesSize == 1;
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/admin/indices/mapping/get/GetFieldMappingsResponse.java]: NIT: Maybe add an assertion message containing the value of `typesSize` ?

**Review by original-brownbear — APPROVED** [review]
LGTM :)
