### PR TITLE
Do not block transport thread on startup

### LINKED ISSUE #41745: [CI] RemoteClusterClientTests#testConnectAndExecuteRequest fails
On master: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian-9/369/console

Couldn't reproduce with:
```
./gradlew :server:test --tests "org.elasticsearch.transport.RemoteClusterClientTests.testConnectAndExecuteRequest" \
  -Dtests.seed=5BFCD458F15F6DA4 \
  -Dtests.security.manager=true \
  -Dtests.locale=tr \
  -Dtests.timezone=America/Atka \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([5BFCD458F15F6DA4:248A7562ED2FB133]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.transport.RemoteClusterClientTests.testConnectAndExecuteRequest(RemoteClusterClientTests.java:60)
```

### PR DESCRIPTION
**Pull request by ywelsch**
We currently block the transport thread on startup. For example, the test failure linked by this comment: https://github.com/elastic/elasticsearch/issues/41071#issuecomment-515607553, which is different to the other ones on that issue, shows both transport threads (there are only two with MockNioTransport) being blocked on the latch, somehow not allowing the startup phase to complete. I think this is some kind of deadlock situation. I don't think we should even block a transport thread, and there's also no need to do so. We can just reject requests as long we're not fully set up. Note that the HTTP layer is only started much later (after we've completed full start up of the transport layer), so that one should be completely unaffected by this.

Closes #41745

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/transport/TransportService.java [hunk 1]
```diff
@@ -877,11 +877,8 @@ public static boolean isValidActionName(String actionName) {
      */
     @Override
     public void onRequestReceived(long requestId, String action) {
-        try {
-            blockIncomingRequestsLatch.await();
-        } catch (InterruptedException e) {
-            Thread.currentThread().interrupt();
-            throw new IllegalStateException("interrupted while waiting for incoming requests block to be removed");
+        if (handleIncomingRequests.get() == false) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/transport/TransportService.java]: NIT: maybe just make it a `volatile boolean` since we only use `get` and `set` anyway?

**Review by original-brownbear — APPROVED** [review]
LGTM (assuming tests go green). I think this is the way to go, if this is causing tests to fail we should fix those test. I'm completely +1 to the blocking on the IO thread being horrible.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2
(unrelated ml test failure)

**Comment by original-brownbear** [comment]
@ywelsch can you make this PR close https://github.com/elastic/elasticsearch/issues/41745 as well, which will def. go away with this change?
