### PR TITLE
ES|QL: MMR more fixes

### LINKED ISSUE #142674: [CI] EsqlNodeSubclassTests testTransform {class org.elasticsearch.xpack.esql.plan.logical.MMR} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11878 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/etocigwmzwdd4)
- [elasticsearch-periodic-platform-support #11878 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/2zgi7n3eum7b6)
- [elasticsearch-pull-request #121792 / part-3](https://gradle-enterprise.elastic.co/s/itzszsy64r3zg)
- [elasticsearch-pull-request #121735 / part-3](https://gradle-enterprise.elastic.co/s/ntpazi25oluy4)
- [elasticsearch-periodic-platform-support #11874 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/vfyjrjbuei55u)
- [elasticsearch-periodic-platform-support #11874 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/xgbkcedodwhyi)
- [elasticsearch-pull-request #121469 / part-3](https://gradle-enterprise.elastic.co/s/4jq34qxaqxkki)
- [elasticsearch-pull-request #121442 / part-3](https://gradle-enterprise.elastic.co/s/qnffpuw36e2f4)
- [elasticsearch-pull-request #121402 / part-3](https://gradle-enterprise.elastic.co/s/jqgxktr7arleu)
- [elasticsearch-pull-request #121354 / part-3](https://gradle-enterprise.elastic.co/s/pbq4uboktzhjq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.tree.EsqlNodeSubclassTests" -Dtests.method="testTransform {class org.elasticsearch.xpack.esql.plan.logical.MMR}" -Dtests.seed=BA1753D35F28CE7C -Dtests.locale=en-KE -Dtests.timezone=America/Goose_Bay -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.tree.EsqlNodeSubclassTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTransform%20%7Bclass%20org.elasticsearch.xpack.esql.plan.logical.MMR%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<MMR[[nLYjy].[suZTo]{r}#Mock for NameId, hashCode: 374122723,WEIGHTEDAVG(?LeAAB,?[rgqNt].[MtOdV],?[maLEN].[WmJOa],?[
jgQqd].[vKcND]),REPLACE(?[eCuhd].[jmHaU],?cXTcH,?[FaWAO].[XwUJY]),CHUNK(?UxGVn,?[YZana].[CAYuR])]
\_UnresolvedRelation[Mock for IndexPattern, hashCode: 291681935]> but was:<MMR[[nLYjy].[suZTo]{r}#Mock for NameId, hashCode: 374122723,WEIGHTEDAVG(?LeAAB,?[rgqNt].[MtOdV],?[maLEN].[WmJOa],?[
jgQqd].[vKcND]),TODENSEVECTOR(42335570[INTEGER]),CHUNK(?UxGVn,?[YZana].[CAYuR])]
\_UnresolvedRelation[Mock for IndexPattern, hashCode: 291681935]>
```

**Issue Reasons:**
- [main] 2 consecutive failures in step ubuntu-2204_platform-support-unix
- [main] 14 failures in test testTransform {class org.elasticsearch.xpack.esql.plan.logical.MMR} (1.7% fail rate in 826 executions)
- [main] 2 failures in step ubuntu-2204_platform-support-unix (25.0% fail rate in 8 executions)
- [main] 2 failures in step rhel-10_platform-support-unix (25.0% fail rate in 8 executions)
- [main] 7 failures in step part-3 (1.4% fail rate in 487 executions)
- [main] 2 failures in step amazonlinux-2023_platform-support-aws (25.0% fail rate in 8 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-platform-support (57.1% fail rate in 7 executions)
- [main] 7 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 480 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ioanatia**
still a draft, still in progress
Fixes various MMR bugs:

1. closes https://github.com/elastic/elasticsearch/issues/142674

The way we mutate `queryVector` in the constructor, wrapping it in a `to_dense_vector` function call, causes these tests to fail:

https://github.com/elastic/elasticsearch/blob/12a10a9f5859234b30ec355d44c2d5144338191d/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java#L45-L58

This is because `queryVector` is part of the `NodeInfo` for MMR and it seems to be an anti-pattern to mutate it in the constructor (I couldn't find other `LogicalPlan`s where we do this).

2. We don't check that the query vector is actually foldable and resolved to a constant. So it's possible to do ` | MMR my_vector ON my_other_vector LIMIT 10`. Surprisingly, the ES|Q succeeds, because we evaluate the query vector to `null` in `MMRExec`.

3. (in progress) Query vectors that are keywords, can lead to 500 errors:

```
MMR "ef" ON rgb_vector LIMIT 10
```

error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "class_cast_exception",
        "reason": "class java.lang.Float cannot be cast to class java.util.ArrayList (java.lang.Float and java.util.ArrayList are in module java.base of loader 'bootstrap')"
      }
    ],
    "type": "class_cast_exception",
    "reason": "class java.lang.Float cannot be cast to class java.util.ArrayList (java.lang.Float and java.util.ArrayList are in module java.base of loader 'bootstrap')"
  },
  "status": 500
}
```

4. We don't validate that lambda needs to be a number:

```
FROM colors
| WHERE rgb_vector is not null
| LIMIT 100
| MMR "efefef" ON rgb_vector LIMIT 10 WITH {"lambda": "abc"}

```

error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "verification_exception",
        "reason": """Found 1 problem
line 2:58: class org.apache.lucene.util.BytesRef cannot be cast to class java.lang.Double (org.apache.lucene.util.BytesRef is in module org.apache.lucene.core@10.4.0 of loader 'app'; java.lang.Double is in module java.base of loader 'bootstrap')"""
      }
    ],
    "type": "verification_exception",
    "reason": """Found 1 problem
line 2:58: class org.apache.lucene.util.BytesRef cannot be cast to class java.lang.Double (org.apache.lucene.util.BytesRef is in module org.apache.lucene.core@10.4.0 of loader 'app'; java.lang.Double is in module java.base of loader 'bootstrap')"""
  },
  "status": 400
}
```

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java [hunk 1]
```diff
@@ -130,107 +131,73 @@ public void postAnalysisVerification(Failures failures) {
...
-
-        try {
-            Expression lambdaValueExpression = optionsMap.remove(MMR.LAMBDA_OPTION_NAME);
-            Float extractedLambda = extractLambdaFromMMROptions(lambdaValueExpression);
-            if (extractedLambda != null && (extractedLambda < 0.0f || extractedLambda > 1.0f)) {
-                failures.add(fail(this, "MMR lambda value must be a number between 0.0 and 1.0"));
+        options.keyFoldedMap().forEach((key, value) -> {
+            if (key.equals(LAMBDA_OPTION_NAME)) {
+                if ((value instanceof Literal) == false) {
+                    failures.add(new Failure(this, "expected " + key + " to be a literal, got [" + value.sourceText() + "]"));
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java]: Nit - clarify a bit more and avoid having another error for the next check

```suggestion
                    failures.add(fail(this, "expected " + key + " to be a constant, got [" + value.sourceText() + "]"));
                    return;
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java [hunk 2]
```diff
@@ -10,50 +10,55 @@
...
+public class MMR extends UnaryPlan
+    implements
+        TelemetryAware,
+        ExecutesOn.Coordinator,
+        PostAnalysisVerificationAware,
+        PostOptimizationPlanVerificationAware {
+
     public static final String LAMBDA_OPTION_NAME = "lambda";
-    private static final List<String> VALID_MMR_OPTION_NAMES = List.of(LAMBDA_OPTION_NAME);
+    public static Float DEFAULT_LAMBDA = 0.5f;
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java]:
```suggestion
    public static final float DEFAULT_LAMBDA = 0.5f;
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java [hunk 3]
```diff
@@ -130,107 +131,73 @@ public void postAnalysisVerification(Failures failures) {
...
-            Float extractedLambda = extractLambdaFromMMROptions(lambdaValueExpression);
-            if (extractedLambda != null && (extractedLambda < 0.0f || extractedLambda > 1.0f)) {
-                failures.add(fail(this, "MMR lambda value must be a number between 0.0 and 1.0"));
+        options.keyFoldedMap().forEach((key, value) -> {
+            if (key.equals(LAMBDA_OPTION_NAME)) {
+                if ((value instanceof Literal) == false) {
+                    failures.add(new Failure(this, "expected " + key + " to be a literal, got [" + value.sourceText() + "]"));
+                }
+                if (value.dataType().isNumeric() == false) {
+                    failures.add(new Failure(this, "expected " + key + " to be numeric, got [" + value.sourceText() + "]"));
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/MMR.java]: Nit - for consistency, there are more on this class

```suggestion
                    failures.add(fail(this, "expected " + key + " to be numeric, got [" + value.sourceText() + "]"));
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/MMRExec.java [hunk 4]
```diff
@@ -96,37 +87,46 @@ public boolean equals(Object o) {
...
+        if (options == null) {
+            return MMR.DEFAULT_LAMBDA;
         }
 
-        return null;
+        Literal lambdaValueExpression = (Literal) options.keyFoldedMap().getOrDefault(MMR.LAMBDA_OPTION_NAME, null);
+        if (lambdaValueExpression == null) {
+            return MMR.DEFAULT_LAMBDA;
+        }
+        return ((Double) lambdaValueExpression.value()).floatValue();
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/MMRExec.java]: I think this can throw a ClassCastException if lambda is an integer value, probably we want:

```suggestion
        return ((Number) lambdaValueExpression.value()).floatValue();
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 5]
```diff
@@ -3798,7 +3798,7 @@ public void testMMRLimitIsValid() {
                 defaultAnalyzer,
                 VerificationException.class
             ),
-            equalTo("1:58: MMR limit must be a positive integer")
+            equalTo("1:58: MMR limit must be a positive integer, got [-5]")
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:3883]: We may want to test for 0 explicitly to understand the bug is solved

Also, testing for a non-double numeric value so we double check there's no ClassCastEx as pointed above

**Review by carlosdelest — COMMENTED** [review]
LGTM! A couple of things to address:

- A possible ClassCastException when using a non-double value for lambda
- A test for the zero case for lambda

**Review by tteofili — APPROVED** [review]
LGTM
