### PR TITLE
Ignore any other warnings when detecting Java version

### LINKED ISSUE #55804: [6.8] A problem occurred evaluating project ':benchmarks'.
`A problem occurred evaluating project ':benchmarks'.`

Build 20200427115226-68434CDB
Log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk15,nodes=general-purpose/656/console
Build Scans https://gradle-enterprise.elastic.co/s/mmxpvcs6ulojy

The following can be found in logs:
```
Caused by: java.lang.IllegalArgumentException: Could not determine java version from ''.
	at org.gradle.api.JavaVersion.assertTrue(JavaVersion.java:227)
	at org.gradle.api.JavaVersion.findFirstNonVersionCharIndex(JavaVersion.java:254)
	at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:80)
	at org.gradle.api.JavaVersion$toVersion$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.elasticsearch.gradle.BuildPlugin.globalBuildInfo(BuildPlugin.groovy:155)
	at org.elasticsearch.gradle.BuildPlugin$globalBuildInfo$3.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:208)
	at org.elasticsearch.gradle.BuildPlugin.apply(BuildPlugin.groovy:102)
	at org.elasticsearch.gradle.BuildPlugin.apply(BuildPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:177)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:267)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:155)
	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:152)
```

As @droberts195 pointed out it may be due to using Java 15 in the old (6.8) build.

### PR DESCRIPTION
**Pull request by mark-vieira**
Follow up to #55903 to address an issue where JVM warning messages output to standard error break our Java probe logic.

Closes #55804

### CODE REVIEW

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy [hunk 1]
```diff
@@ -503,7 +503,12 @@ class BuildPlugin implements Plugin<Project> {
             result.rethrowFailure()
             result.assertNormalExitValue() // assert exit value in case the failure cause is null
         }
-        return (captureStdErr ? stderr : stdout).toString('UTF-8').trim()
+        String[] lines = (captureStdErr ? stderr : stdout).toString('UTF-8').trim().split('\n')
+        if (lines.length == 0) {
+            throw new GradleException("Expected command to produce output but it did not.")
+        }
+
+        return lines[lines.length - 1]
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy:511]: Why only the last line? Why do we need to split instead of just checking the length of the entire output being zero?

Comment (mark-vieira) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy:511]: Because the JVM logs warning messages to stderr. What was happening is Jenkins sets `JAVA_TOOL_OPTIONS` which then results in `jshell` printing `Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8` to stderr. We need to ignore any such output and only care about the last thing printed out, which is going to be our script output.

**Review by rjernst — APPROVED** [review]
At first I thought we should then change the return to the full array of return lines, but then I realized this change is only for 6.8. LGTM.
