### PR TITLE
Check for incompatible mappings while upgrading old indices

### LINKED ISSUE #11857: Conflicting mappings causes runaway shard failures on upgrade
Start Elasticsearch 1.6.0, and run the following commands:

    DELETE *

    PUT bad
    {
      "mappings": {
        "x": {
          "properties": {
            "foo": {
              "type": "string"
            }
          }
        },
        "y": {
          "properties": {
            "foo": {
              "type": "date"
            }
          }
        }
      }
    }
    
    PUT bad/x/1
    {"foo": "bar"}
    
    PUT bad/y/1
    {"foo": "2015-01-01"}
    
    POST _flush

Then shutdown and start ES compiled from master.  The `bad` index fails to recover because of the conflicting mappings, and the failures just keep being repeated endlessly:

    [2015-06-24 18:22:46,644][WARN ][indices.cluster          ] [Crossbones] [bad] failed to add mapping [y], source [{"y":{"properties":{"foo":{"t
    ype":"date","format":"dateOptionalTime"}}}}]
    java.lang.IllegalArgumentException: Mapper for [foo] conflicts with existing mapping in other types[mapper [foo] cannot be changed from type [s
    tring] to [date]]
            at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
            at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:350)
            at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:305)
            at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:255)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:422)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:376)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:181)
            at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:484)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThr
    eadPoolExecutor.java:209)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolE
    xecutor.java:179)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:722)
    [2015-06-24 18:22:46,701][WARN ][indices.cluster          ] [Crossbones] [[bad][0]] marking and sending shard failed due to [failed to update m
    appings]
    java.lang.IllegalArgumentException: Mapper for [foo] conflicts with existing mapping in other types[mapper [foo] cannot be changed from type [s
    tring] to [date]]
            at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
            at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:350)
            at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:305)
            at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:255)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:422)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:376)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:181)
            at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:484)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThr
    eadPoolExecutor.java:209)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolE
    xecutor.java:179)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:722)
    [2015-06-24 18:22:46,703][WARN ][cluster.action.shard     ] [Crossbones] [bad][0] received shard failed for [bad][0], node[_DucCUykRy6JHLfcchxVVg], [P], s[INITIALIZING], unassigned_info[[reason=CLUSTER_RECOVERED], at[2015-06-24T16:22:46.149Z]], indexUUID [RET0PNdWQQWhX_fglK4FIw], reason [shard failure [failed to update mappings][IllegalArgumentException[Mapper for [foo] conflicts with existing mapping in other types[mapper [foo] cannot be changed from type [string] to [date]]]]]
    [2015-06-24 18:22:46,705][WARN ][indices.cluster          ] [Crossbones] [[bad][1]] marking and sending shard failed due to [failed to update mappings]
    java.lang.IllegalArgumentException: Mapper for [foo] conflicts with existing mapping in other types[mapper [foo] cannot be changed from type [string] to [date]]
            at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
            at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:350)
            at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:305)
            at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:255)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:422)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:376)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:181)
            at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:484)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:209)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:179)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:722)
    [2015-06-24 18:22:46,706][WARN ][cluster.action.shard     ] [Crossbones] [bad][0] received shard failed for [bad][0], node[_DucCUykRy6JHLfcchxVVg], [P], s[INITIALIZING], unassigned_info[[reason=CLUSTER_RECOVERED], at[2015-06-24T16:22:46.149Z]], indexUUID [RET0PNdWQQWhX_fglK4FIw], reason [master [Crossbones][_DucCUykRy6JHLfcchxVVg][Slim-2.local][inet[/127.0.0.1:9300]] marked shard as initializing, but shard is marked as failed, resend shard failure]

### PR DESCRIPTION
**Pull request by imotov**
Conflicting mappings that were allowed before v2.0 can cause runaway shard failures on upgrade. This commit adds a check that prevents a cluster from starting if it contains such indices as well as restoring such indices from a snapshot into already running cluster.

Closes #11857

### CODE REVIEW

**Comment by bleskes** [comment]
@imotov correct me if I'm wrong, but since we now check the mapping in the constructor of GatewayMetaState, if it runs into a mapping that's incompatible with 2.0 it will throw an exception and prevent the node from starting...

**Comment by imotov** [comment]
@bleskes you are right and this is the behavior described in the commit comment. It is consistent with a node behavior in case of other detected incompatibilities. We had a discussion about this and came to the conclusion that this is the best user experience we can provide. A user trying to upgrade a cluster with incompatible indices will not be able to start a node and since we haven't updated any metadata or data files at this point yet, they still will be able to downgrade to the previous version and fix the issue before trying to upgrade again. An alternative would be to start the cluster with potentially all indices closed and no way back.

**Comment by clintongormley** [comment]
@imotov i like this approach

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/ShardUpgradeResponse.java [hunk 1]
```diff
@@ -32,7 +33,9 @@
  */
 class ShardUpgradeResponse extends BroadcastShardResponse {
 
-    private org.apache.lucene.util.Version version;
+    private org.apache.lucene.util.Version luceneVersion;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/ShardUpgradeResponse.java]: If my understanding is correct, this is the version of the "oldest" segment in the index? If yes, can you document it: I had to think about it for a bit since the elasticsearch version below also points to a lucene version which is the version which has been used to write the index initially.

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java [hunk 2]
```diff
@@ -94,20 +95,40 @@ protected UpgradeResponse newResponse(UpgradeRequest request, AtomicReferenceArr
...
+                    }
+                    // For the lucene version we are interested in the _oldest_ lucene version since it determines the
+                    // oldest version that we need to support
+                    if (shardUpgradeResponse.luceneVersion().onOrAfter(versionTuple.v2()) == false) {
+                        luceneVersion = shardUpgradeResponse.luceneVersion();
+                        changed = true;
+                    }
+                    if (changed) {
+                        versions.put(index, new Tuple<>(version, luceneVersion));
+                    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java]: maybe we don't need this `changed` logic, calling `versions.put(index, new Tuple<>(version, luceneVersion));` would always be correct?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 3]
```diff
@@ -239,4 +261,62 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
...
+                try (MapperService mapperService = new MapperService(index, settings, analysisService, similarityLookupService, scriptService)) {
+                    for (ObjectCursor<MappingMetaData> cursor : indexMetaData.getMappings().values()) {
+                        MappingMetaData mappingMetaData = cursor.value;
+                        mapperService.merge(mappingMetaData.type(), mappingMetaData.source(), true, true);
+                    }
+                }
+            }
+        } catch (Exception ex) {
+            // Wrap the inner exception so we have the index name in the exception message
+            throw new IllegalArgumentException("unable to upgrade the index [" + indexMetaData.getIndex() + "], reason: [" + ex.getMessage() + "]", ex);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: should it rather be an IllegalStateException?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 4]
```diff
@@ -239,4 +261,62 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
...
+        Settings settings = indexMetaData.settings();
+        try {
+            SimilarityLookupService similarityLookupService = new SimilarityLookupService(index, settings);
+            // We cannot instantiate real analysis server at this point because the node might not have
+            // been started yet. However, we don't really need real analyzers at this stage - so we can fake it
+            try (AnalysisService analysisService = new FakeAnalysisService(index, settings)) {
+                try (MapperService mapperService = new MapperService(index, settings, analysisService, similarityLookupService, scriptService)) {
+                    for (ObjectCursor<MappingMetaData> cursor : indexMetaData.getMappings().values()) {
+                        MappingMetaData mappingMetaData = cursor.value;
+                        mapperService.merge(mappingMetaData.type(), mappingMetaData.source(), true, true);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Should `updateAllTypes` really be `true`? This might hide some problems?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 5]
```diff
@@ -239,4 +261,62 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
...
+        Settings settings = Settings.builder().put(indexMetaData.settings()).put(IndexMetaData.SETTING_VERSION_UPGRADED, Version.CURRENT).build();
+        return IndexMetaData.builder(indexMetaData).settings(settings).build();
+    }
+
+    /**
+     * A fake analysis server that returns the same keyword analyzer for all requests
+     */
+    private static class FakeAnalysisService extends AnalysisService {
+
+        private static Analyzer keywordAnalyzer = new KeywordAnalyzer();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I don't think it should be static

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java [hunk 6]
```diff
@@ -130,8 +151,8 @@ protected ShardUpgradeResponse newShardResponse() {
     @Override
     protected ShardUpgradeResponse shardOperation(ShardUpgradeRequest request) {
         IndexShard indexShard = indicesService.indexServiceSafe(request.shardId().getIndex()).shardSafe(request.shardId().id());
-        org.apache.lucene.util.Version version = indexShard.upgrade(request.upgradeRequest());
-        return new ShardUpgradeResponse(request.shardId(), indexShard.routingEntry().primary(), version);
+        org.apache.lucene.util.Version luceneVersion = indexShard.upgrade(request.upgradeRequest());
+        return new ShardUpgradeResponse(request.shardId(), indexShard.routingEntry().primary(), Version.CURRENT, luceneVersion);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java]: Should it return the created version or the upgraded version (if it exists) instead of Version.CURRENT?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 4 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Actually I think applyDefaults should be false too since we already have a mapping?

**Comment by jpountz** [comment]
@imotov I like the behaviour. I guess something that I'm missing from the PR is an upgrade test where there are two types that have a common field which has the same mappings, to make sure we don't reject that case?

**Comment by imotov** [comment]
@jpountz because I couldn't create conflicting mapping in 2.0, I had to generate an index with a conflicting mapping using [this script](https://github.com/elastic/elasticsearch/pull/12406/files#diff-e51a08a43dde51ab5c488e98ac24b538R1) and then test it as part [UpgradeReallyOldIndexTest](https://github.com/elastic/elasticsearch/pull/12406/files#diff-0c8235e2974b7061d9f8e9476b11688cR52).

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 5 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: This analyzer is only compared to null it's not really used as an analyzer.

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java (hunk 6 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java]: So, the idea is that luceneVersion track the version of the latest segment. The elasticsearch version tracks the version of metadata, and since we update metadata to match the current version I am using the current version instead of version when index was created. This is the tricky part so I will add some comments here.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 5 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: The reason why I added this comment was because I saw it was closed in FakeAnalysisService.close(). So instead should we create an anonymous fake analyzer (that throws an exception in createComponents) and never close it?

Comment (imotov) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Makes sense.

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java [hunk 7]
```diff
@@ -94,20 +95,35 @@ protected UpgradeResponse newResponse(UpgradeRequest request, AtomicReferenceArr
...
+                    // For the metadata we are interested in the _latest_ elasticsearch version that was processing the metadata
+                    // Since we rewrite the mapping during upgrade the metadata is always rewritten by the latest version
+                    if (shardUpgradeResponse.upgradeVersion().after(versionTuple.v1())) {
+                        version = shardUpgradeResponse.upgradeVersion();
+                    }
+                    // For the lucene version we are interested in the _oldest_ lucene version since it determines the
+                    // oldest version that we need to support
+                    if (shardUpgradeResponse.oldestLuceneSegment().onOrAfter(versionTuple.v2()) == false) {
+                        luceneVersion = shardUpgradeResponse.oldestLuceneSegment();
+                    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java]: the comment says it looks for the oldest version but the code looks for the newest version?

**Comment by imotov** [comment]
@jpountz I pushed an update.

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java (hunk 7 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeAction.java]: sorry I missed the ==false

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 8]
```diff
@@ -239,4 +261,67 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
...
+        }
+
+        @Override
+        public NamedAnalyzer analyzer(String name) {
+            return new NamedAnalyzer(name, fakeAnalyzer);
+        }
+
+        @Override
+        public void close() {
+            fakeAnalyzer.close();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I don't think we need to close the fake analyzer since it doesn't hold resources?

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java [hunk 9]
```diff
@@ -86,8 +88,11 @@ public RestResponse buildResponse(UpgradeResponse response, XContentBuilder buil
                 builder.startObject();
                 buildBroadcastShardsHeader(builder, request, response);
                 builder.startObject("upgraded_indices");
-                for (Map.Entry<String, String> entry : response.versions().entrySet()) {
-                    builder.field(entry.getKey(), entry.getValue(), XContentBuilder.FieldCaseConversion.NONE);
+                for (Map.Entry<String, Tuple<Version, String>> entry : response.versions().entrySet()) {
+                    builder.startObject(entry.getKey(), XContentBuilder.FieldCaseConversion.NONE);
+                    builder.field("version", entry.getValue().v1());
+                    builder.field("lucene_version", entry.getValue().v2());
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java]: I think we need to come up with more descriptive names?

**Comment by jpountz** [comment]
This looks good to me in general but I would appreciate if someone else could give it a look to make sure I didn't overlook anything.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 8 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: The parent class has a non-empty close method, so while you are right - there is nothing really happens there, I don't think it causes any harm to close it and it will make reasoning about the code easier.

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java (hunk 9 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java]: I am going to rename them to `upgrade_version` and `minimum_compatible_lucene_version`.

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java]: "minimum compatible" is confusing.  Compatible with what? Can we maybe call this `oldest_lucene_segment_version`?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 10]
```diff
@@ -239,4 +261,67 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
         // No changes:
         return indexMetaData;
     }
+
+
+    /**
+     * Checks the mappings of the mappings for compatibility with the current version
+     */
+    private IndexMetaData upgradeMappings(IndexMetaData indexMetaData) {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: The `upgradeMappings()` doesn't seem to modify the provided `indexMetaData ` variable, so I think this method should have `void`as return type?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 11]
```diff
@@ -239,4 +261,67 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
         // No changes:
         return indexMetaData;
     }
+
+
+    /**
+     * Checks the mappings of the mappings for compatibility with the current version
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: mappings of mappings? Maybe just one mappings?

File: core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/UpgradeResponse.java [hunk 12]
```diff
@@ -55,8 +57,9 @@ public void readFrom(StreamInput in) throws IOException {
         versions = newHashMap();
         for (int i=0; i<size; i++) {
             String index = in.readString();
-            String version = in.readString();
-            versions.put(index, version);
+            Version version = Version.readVersion(in);
+            String luceneVersion = in.readString();
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/UpgradeResponse.java]: Can we use the same "lucene oldest segment" terminology here?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 13]
```diff
@@ -83,13 +93,25 @@ public MetaDataIndexUpgradeService(Settings settings) {
      */
     public IndexMetaData upgradeIndexMetaData(IndexMetaData indexMetaData) {
         // Throws an exception if there are too-old segments:
+        if(isUpgraded(indexMetaData)) {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: nit: space after if

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 14]
```diff
@@ -83,13 +93,25 @@ public MetaDataIndexUpgradeService(Settings settings) {
...
+        newMetaData = upgradeMappings(newMetaData);
+        newMetaData = markAsUpgraded(newMetaData);
         return newMetaData;
     }
 
     /**
+     * Checks if the index was already opened by this version of Elasticsearch and doesn't require any additional checks.
+     */
+    private boolean isUpgraded(IndexMetaData indexMetaData) {
+        return indexMetaData.creationVersion().onOrAfter(Version.V_2_0_0_beta1) || indexMetaData.upgradeVersion().onOrAfter(Version.V_2_0_0_beta1);
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Is it possible to just check upgrade version? Can we default that to the created version, so this logic is very simple to think about here?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 15]
```diff
@@ -239,4 +261,67 @@ private IndexMetaData addDefaultUnitsIfNeeded(IndexMetaData indexMetaData) {
...
+                try (MapperService mapperService = new MapperService(index, settings, analysisService, similarityLookupService, scriptService)) {
+                    for (ObjectCursor<MappingMetaData> cursor : indexMetaData.getMappings().values()) {
+                        MappingMetaData mappingMetaData = cursor.value;
+                        mapperService.merge(mappingMetaData.type(), mappingMetaData.source(), false, false);
+                    }
+                }
+            }
+        } catch (Exception ex) {
+            // Wrap the inner exception so we have the index name in the exception message
+            throw new IllegalStateException("unable to upgrade the index [" + indexMetaData.getIndex() + "], reason: [" + ex.getMessage() + "]", ex);
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: upgrade -> upgrade mappings?

File: core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java (hunk 9 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/rest/action/admin/indices/upgrade/RestUpgradeAction.java]: Were you still going to rename these?

File: core/src/test/java/org/elasticsearch/action/admin/indices/upgrade/UpgradeReallyOldIndexTest.java [hunk 16]
```diff
@@ -38,11 +40,25 @@ public void testUpgrade_0_90_6() throws Exception {
...
         // This index has only ancient segments, so it should now be fully upgraded:
         UpgradeTest.assertUpgraded(client(), indexName);
         assertEquals(Version.CURRENT.luceneVersion.toString(), client().admin().indices().prepareGetSettings(indexName).get().getSetting(indexName, IndexMetaData.SETTING_VERSION_MINIMUM_COMPATIBLE));
         assertMinVersion(indexName, Version.CURRENT.luceneVersion);
+
+        assertEquals(client().admin().indices().prepareGetSettings(indexName).get().getSetting(indexName, IndexMetaData.SETTING_VERSION_UPGRADED), Integer.toString(Version.CURRENT.id));
+    }
+
+    public void testUpgradeConflictingMapping() throws Exception {
+        String indexName = "index-1.7.0";
```
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/action/admin/indices/upgrade/UpgradeReallyOldIndexTest.java]: Can we name this index differently to indicate it is an error case? Perhaps index-conflicting-mappings-1.7.0?

**Comment by rjernst** [comment]
This looks good. I left a handful of minor comments/questions.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 14 above)
Comment (imotov) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: If upgrade version is not present, it is set to created version, so we can just check upgrade version.

**Comment by imotov** [comment]
@rjernst I pushed an update

**Comment by rjernst** [comment]
LGTM, just one minor comment about naming.
