### PR TITLE
SQL: allow LEFT and RIGHT as function names

### LINKED ISSUE #32046: SQL:  LEFT and RIGHT functions are not parsed correctly
It seems there might be an ambiguity in evaluating a LEFT or RIGHT function, probably because of LEFT/RIGHT JOINs?

Trying to run `SELECT LEFT("first_name",2) f FROM "test_emp" LIMIT 3;` results in:

```
java.sql.SQLSyntaxErrorException: line 1:8: extraneous input 'LEFT' expecting {'(', 'ANALYZE', 'ANALYZED', 'CAST', 'CATALOGS', 'COLUMNS', 'DEBUG', 'EXECUTABLE', 'EXISTS', 'EXPLAIN', 'EXTRACT', 'FALSE', 'FORMAT', 'FUNCTIONS', 'GRAPHVIZ', 'MAPPED', 'MATCH', 'NOT', 'NULL', 'OPTIMIZED', 'PARSED', 'PHYSICAL', 'PLAN', 'RLIKE', 'QUERY', 'SCHEMAS', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TRUE', 'TYPE', 'TYPES', 'VERIFY', '{FN', '{D', '{T', '{TS', '{GUID', '+', '-', '*', '?', STRING, INTEGER_VALUE, DECIMAL_VALUE, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}
```

### PR DESCRIPTION
**Pull request by costin**
Due to the way ANTLR works, any declared tokens need to be accounted for
manually inside function names (otherwise a different rule gets applied).

Fix #32046

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/SqlParserTests.java [hunk 1]
```diff
@@ -44,6 +45,11 @@ public void testSelectScore() {
         assertEquals("SCORE", f.functionName());
     }
 
+    public void testSelectLeft() {
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/SqlParserTests.java]: Minor thing: method called `testSelectLeft()` but the test itself is about the `RIGHT` function.

**Review by astefan — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]
LGTM other than the thing @astefan caught.
