### PR TITLE
SQL: Fix function resolution

### LINKED ISSUE #34114: SQL Function name resolution depends on the case
When SQL resolves function names, it takes case into consideration that produces unexpected results.

For example, the following tree statements work
```
SELECT CHAR_LENGTH("blah");
SELECT Char_Length("blah");
SELECT CharLength("blah");
```

But if the following 2 statements produce error messages:
```
SELECT cHaR_length("blah");
SELECT CHARLENGTH("blah");
```
In the first case the error message is
```
Unknown function [cHaR_length], did you mean any of [CHAR_LENGTH, CHARACTER_LENGTH, BIT_LENGTH]?
```
Expected behavior is SQL should be case insensitive in the function name resolution.

### PR DESCRIPTION
**Pull request by matriv**
If conversion from camelCase to CAMEL_CASE format doesn't succeed,
try to resolve the function by capitalizing all letters.

Fixes: #34114

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java [hunk 1]
```diff
@@ -221,7 +222,7 @@ public FunctionDefinition resolveFunction(String name) {
 
     public String concreteFunctionName(String alias) {
         String normalized = normalize(alias);
-        return aliases.getOrDefault(normalized, normalized);
+        return aliases.getOrDefault(normalized, alias.toUpperCase(Locale.ROOT));
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java]: I agree with the `alias.toUpperCase()` but I don't see why we normalize the received name. This means we accept `CharLength` as a function name, but if the function name is incorrect (for example `CharLen`) we tell the user what he meant (CHARACTER_LENGTH, CHAR_LENGTH). No mentioning of CHARLENGTH.

Imo, given that it's impossible to guess where to put the underscore in case of a `CharLength` or `CharlEngth`, we should only accept straight names, without trying to normalize. Otherwise, we won't be able to offer a consistent behavior to the user.

**Review by astefan — CHANGES_REQUESTED** [review]

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java]: But if I understand correctly, with your suggestion we'll break the existing "feature" of converting camelCase to CAMEL_CASE.

Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java]: I don't have any objection on this suggestion. It will simplify things and the rule would be as simple as: apply upperCase to the input and try to resolve from the register function names and aliases.

**Comment by matriv** [comment]
@costin @astefan Removed the CamelCase conversion for user input. Just converting to uppercase and then try to match aliases or primary names: https://github.com/elastic/elasticsearch/pull/34137/commits/f7a65393273c0f12f0673a9913ab57b2e2f5342f

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 2]
```diff
@@ -771,9 +771,9 @@ protected LogicalPlan resolve(LogicalPlan plan, Map<String, List<Function>> seen
                         return uf;
                     }
 
-                    String normalizedName = functionRegistry.concreteFunctionName(name);
+                    name = functionRegistry.concreteFunctionName(name);
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java]: I am not convinced that this change combined with https://github.com/elastic/elasticsearch/pull/34137/files#diff-bb6b97c81fc9a1971733dc1d3b90be73R229 is the right approach. LGTM if @costin is also ok with it.

**Review by astefan — APPROVED** [review]
LGTM with a comment.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java]: The 2 function calls must remain discrete since in-between we need to do the resolution through the "seen" functions. I choose to remove the new string variable and re-assign to name as the `concreteFunctionName()` doesn't guarantee that it returns the actual concrete function name, it's just an attempt, so I didn't like to use a variable with a name like `concreteName`. I'd also like to rename the `concreteFunctionName()` to something like `tryResolveFromAliases`.

Do you maybe have a good suggestion for a variable name here?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java [hunk 3]
```diff
@@ -220,12 +221,12 @@ public FunctionDefinition resolveFunction(String name) {
...
     public String concreteFunctionName(String alias) {
-        String normalized = normalize(alias);
-        return aliases.getOrDefault(normalized, normalized);
+        String upperCase = alias.toUpperCase(Locale.ROOT);
+        return aliases.getOrDefault(upperCase, upperCase);
     }
 
     public boolean functionExists(String name) {
-        return defs.containsKey(normalize(name));
+        return defs.containsKey(name);
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistry.java]: This should use the `concreteFunctionName` since one might ask for a lower_case function name or alias.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java]: I'm not sure I follow - why not use `functionName` or simply `resolvePotentialAlias`/`resolveAlias`/`getName`?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistryTests.java [hunk 4]
```diff
@@ -6,31 +6,35 @@
...
 import static org.elasticsearch.xpack.sql.expression.function.FunctionRegistry.def;
 import static org.elasticsearch.xpack.sql.expression.function.UnresolvedFunction.ResolutionType.DISTINCT;
 import static org.elasticsearch.xpack.sql.expression.function.UnresolvedFunction.ResolutionType.EXTRACT;
 import static org.elasticsearch.xpack.sql.expression.function.UnresolvedFunction.ResolutionType.STANDARD;
 import static org.hamcrest.Matchers.endsWith;
+import static org.hamcrest.Matchers.is;
 import static org.mockito.Mockito.mock;
-import static java.util.Collections.emptyList;
 
 public class FunctionRegistryTests extends ESTestCase {
```
Comment (costin) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistryTests.java]: Is there a test for a function with multiple aliases to see whether they are resolved accordingly?

**Review by costin — COMMENTED** [review]
Left some comments.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistryTests.java (hunk 4 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/function/FunctionRegistryTests.java]: I have renamed the Dummy to DummyFunction so it's registered as `DUMMY_FUNCTION` and I also have an alias for it which is tested for resolution: https://github.com/elastic/elasticsearch/pull/34137/files/7dfb1701b7f5362ce341d6474a6630f867b58849#diff-7722161be74f8c03f338863e37902813R173

Do you think of something else?

**Comment by matriv** [comment]
@costin Pushed fixup to address your comments. Please check.

**Review by costin — APPROVED** [review]
LGTM. Thanks!

**Comment by matriv** [comment]
Backported to `6.x` with afcc8b59ced68f740474d6ba9a9fdef3568a741f
