### PR TITLE
MasterNodeChangePredicate should use the node instance to detect master change

### LINKED ISSUE #25471: [CI] SpecificMasterNodesIT#testSimpleOnlyMasterNodeElection failure
Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/383/consoleText

```
ERROR   32.6s J0 | SpecificMasterNodesIT.testSimpleOnlyMasterNodeElection <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Can't get master node NodeNotConnectedException[[node_tm1][127.0.0.1:9401] Node not connected]
   > 	at __randomizedtesting.SeedInfo.seed([B5244B21C6B2CCB8:C9FFA236E02797B6]:0)
   > 	at org.elasticsearch.test.InternalTestCluster.getMasterName(InternalTestCluster.java:1594)
   > 	at org.elasticsearch.test.InternalTestCluster.getMasterName(InternalTestCluster.java:1580)
   > 	at org.elasticsearch.test.InternalTestCluster.nonMasterClient(InternalTestCluster.java:688)
   > 	at org.elasticsearch.cluster.SpecificMasterNodesIT.testSimpleOnlyMasterNodeElection(SpecificMasterNodesIT.java:78)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: MasterNotDiscoveredException[NodeNotConnectedException[[node_tm1][127.0.0.1:9401] Node not connected]]; nested: NodeNotConnectedException[[node_tm1][127.0.0.1:9401] Node not connected];
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:209)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:575)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	... 1 more
   > Caused by: NodeNotConnectedException[[node_tm1][127.0.0.1:9401] Node not connected]
   > 	at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:617)
   > 	at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:118)
   > 	at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:523)
   > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:486)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:175)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:126)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:104)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:54)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
   > 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64)
   > 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:54)
   > 	at org.elasticsearch.transport.AssertingTransportInterceptor$1.messageReceived(AssertingTransportInterceptor.java:76)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1525)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:139)
   > 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1482)
   > 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1352)
   > 	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:171)
   > 	at org.elasticsearch.transport.MockTcpTransport.access$900(MockTcpTransport.java:72)
   > 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.lambda$doRun$0(MockTcpTransport.java:349)
   > 	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105)
   > 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.doRun(MockTcpTransport.java:349)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	... 3 more
```
Reproduce command: `gradle :core:integTest -Dtests.seed=B5244B21C6B2CCB8 -Dtests.class=org.elasticsearch.cluster.SpecificMasterNodesIT -Dtests.method="testSimpleOnlyMasterNodeElection" -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=Australia/Adelaide`

It didn't reproduce for me.

### PR DESCRIPTION
**Pull request by bleskes**
This predicate is used to deal with the intricacies of detecting when a master is reelected/nodes rejoins an existing master. The current implementation is based on nodeIds, which is fine if the master really change. If the nodeId is equal the code falls back to detecting an increment in the cluster state version which happens when a node is re-elected or when the node rejoins. Sadly this doesn't cover the case where the same node is elected after a full restart of all master nodes. In that case we recover the cluster state from disk but the version is reset back to 0. To fix this, the check should be done based on ephemeral IDs which are reset on restart.

Fixes #25471

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java [hunk 1]
```diff
@@ -33,13 +33,13 @@ private MasterNodeChangePredicate() {
      */
     public static Predicate<ClusterState> build(ClusterState currentState) {
         final long currentVersion = currentState.version();
-        final String currentMaster = currentState.nodes().getMasterNodeId();
+        final String currentMasterId = currentState.nodes().getMasterNode().getEphemeralId();
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java]: NullPointerException if `getMasterNode()` returns null?

File: core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java [hunk 2]
```diff
@@ -33,13 +33,13 @@ private MasterNodeChangePredicate() {
...
         return newState -> {
-            final String newMaster = newState.nodes().getMasterNodeId();
+            final String newMasterId = newState.nodes().getMasterNode().getEphemeralId();
             final boolean accept;
-            if (newMaster == null) {
+            if (newMasterId == null) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java]: `newMasterId` (= `getEphemeralId()`) cannot be null, `getMasterNode()` can be, however.

File: core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java [hunk 3]
```diff
@@ -33,13 +33,13 @@ private MasterNodeChangePredicate() {
...
                 accept = false;
-            } else if (newMaster.equals(currentMaster) == false){
+            } else if (newMasterId.equals(currentMasterId) == false){
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java]: maybe it's nicer to just capture the `DiscoveryNode` object here and use `equals` on that (internally it will use the ephemeral id for comparison anyhow).

**Review by ywelsch — CHANGES_REQUESTED** [review]
NullPointerException

File: core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java (hunk 2 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java]: bad refactoring. yikes. will fix and check for the testing coverage.

File: core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java (hunk 3 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java]: That's I had it before. I refactored it as I prefer to have explicit references to places that depends on the ephemeral id. I know we use the disco nodes themselves in many places but I don't want to add another one.

**Comment by bleskes** [comment]
Thx @ywelsch . I addressed your feedback. Can you take another look please?

File: core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java [hunk 4]
```diff
@@ -33,13 +35,14 @@ private MasterNodeChangePredicate() {
...
+        final DiscoveryNode masterNode = currentState.nodes().getMasterNode();
+        final String currentMasterId = masterNode == null ? null : masterNode.getEphemeralId();
         return newState -> {
-            final String newMaster = newState.nodes().getMasterNodeId();
+            final DiscoveryNode newMaster = newState.nodes().getMasterNode();
             final boolean accept;
             if (newMaster == null) {
                 accept = false;
-            } else if (newMaster.equals(currentMaster) == false){
+            } else if (newMaster.getEphemeralId().equals(currentMasterId) == false){
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/MasterNodeChangePredicate.java]: space missing between closing and opening bracket: `false){`

File: core/src/test/java/org/elasticsearch/action/support/master/TransportMasterNodeActionTests.java [hunk 5]
```diff
@@ -298,10 +299,12 @@ public void testDelegateToMaster() throws ExecutionException, InterruptedExcepti
     }
 
     public void testDelegateToFailingMaster() throws ExecutionException, InterruptedException {
-        boolean failsWithConnectTransportException = randomBoolean();
+        boolean failsWithConnectTransportException = true || randomBoolean();
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/action/support/master/TransportMasterNodeActionTests.java]: You probably want to remove `true ||` before pushing ;-)

File: core/src/test/java/org/elasticsearch/action/support/master/TransportMasterNodeActionTests.java [hunk 6]
```diff
@@ -314,10 +317,30 @@ public void testDelegateToFailingMaster() throws ExecutionException, Interrupted
         assertThat(capturedRequest.action, equalTo("testAction"));
 
         if (rejoinSameMaster) {
-            transport.handleRemoteError(capturedRequest.requestId, new ConnectTransportException(remoteNode, "Fake error"));
+            transport.handleRemoteError(capturedRequest.requestId, new ConnectTransportException(masterNode, "Fake error"));
             assertFalse(listener.isDone());
-            // reset the same state to increment a version simulating a join of an existing node
-            setState(clusterService, clusterService.state());
+            if (randomBoolean()) {
+                // simulate master node removal removal
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/action/support/master/TransportMasterNodeActionTests.java]: removal removal removal

**Review by ywelsch — APPROVED** [review]
LGTM (after addressing 3 nits)
