### PR TITLE
Configurable MIME type for mustache template encoding on set processor

### LINKED ISSUE #65115: The set processor introduces unwanted escape characters (backslashes) when using templated fields
**Elasticsearch version** (`bin/elasticsearch --version`): 

7.9.3 on Elastic cloud

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

The set processor introduces unwanted escape characters (backslashes) when using templated fields. The behaviour has been observed for double quotes (`"`)

**Steps to reproduce**:

Input:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "set": {
          "field": "message2",
          "value": "{{message}}"
        }
      }
    ]
  },
  "docs": [
    {
      "_source" : {
      "message" : """10.10.1.1 - - [17/Nov/2020:04:59:43 +0000] "GET /info HTTP/1.1" 200 6229 "-" "-"  2"""
      }
    }
    ]
}
```

Output:

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_doc",
        "_id" : "_id",
        "_source" : {
          "message" : """10.10.1.1 - - [17/Nov/2020:04:59:43 +0000] "GET /info HTTP/1.1" 200 6229 "-" "-"  2""",
          "message2" : """10.10.1.1 - - [17/Nov/2020:04:59:43 +0000] \"GET /info HTTP/1.1\" 200 6229 \"-\" \"-\"  2"""
        },
        "_ingest" : {
          "timestamp" : "2020-11-17T05:26:12.174346581Z"
        }
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by danhermann**
The set processor permits the value that it sets to be specified with a [Mustache](https://mustache.github.io/) template snippet. Our Mustache script engine allows three different MIME encodings to be used when writing the value that the snippet evaluates to but the Set processor was hard-coded to always use the `application/json` MIME type. This adds an optional `mime_type` property to the Set processor that may be set to any of the three MIME types (`application/json`, `text/plain`, `application/x-www-form-urlencoded`) that the Mustache script engine supports. The default type remains `application/json`.

Closes #65115

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by probakowski — APPROVED** [review]
LGTM, thanks @danhermann ! 
We should add documentation for this new property either in this PR or in the follow up

**Comment by danhermann** [comment]
Thank you, @probakowski! I will open another PR shortly with documentation for this option.

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java [hunk 1]
```diff
@@ -110,10 +111,11 @@ public SetProcessor create(Map<String, Processor.Factory> registry, String proce
                                    String description, Map<String, Object> config) throws Exception {
             String field = ConfigurationUtils.readStringProperty(TYPE, processorTag, config, "field");
             String copyFrom = ConfigurationUtils.readOptionalStringProperty(TYPE, processorTag, config, "copy_from");
+            String mimeType = ConfigurationUtils.readMimeTypeProperty(TYPE, processorTag, config, "mime_type", "application/json");
```
Comment (pgomulka) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java:114]: are we sure we want `mime_type` as a name here? I thought mime was replace with `media_type` 
but wouldn't `content_type`  be more consistent with what we have in mustache templating engine?

File: server/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java [hunk 2]
```diff
@@ -49,6 +49,7 @@
 
     public static final String TAG_KEY = "tag";
     public static final String DESCRIPTION_KEY = "description";
+    public static final String[] VALID_MIME_TYPES = {"application/json", "text/plain", "application/x-www-form-urlencoded"};
```
Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java:52]: do we want the se hardcoded? What if someone specifies `application/json; charset=utf-8` ? 
Would it be of any help if this bit was unified with what CustomMustacheFactory defines? I made an attempt here https://github.com/elastic/elasticsearch/pull/66857/files#diff-207cacc1e4a5b24109a693c0b63dd762156452bb5984b5ce04499b28e6c191e8R28

**Review by pgomulka — COMMENTED** [review]
I left some questions which might be related to my work here https://github.com/elastic/elasticsearch/pull/66857
I am mostly concerned about the mime_type name and that we duplicate the media types allowed by our templating engine

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java (hunk 1 above)
Comment (pgomulka) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java:114]: or we could consider to rename the content_type to media_type?

Comment (danhermann) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java:114]: I'm happy to rename to whatever is most appropriate. I went with `mime_type` because that is what was used in `CustomMustacheFactory` but I would agree that `media_type` or possibly `content_type` would be better.

File: server/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java (hunk 2 above)
Comment (danhermann) [reply server/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java:52]: I agree that unifying this set of options would be good. I can do that after you merge that PR. I don't believe that we want to allow the specification of a particular character set for the use case of the ingest processor, though.

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java (hunk 1 above)
Comment (jakelandis) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java:114]: +1 to follow up with a change to `media_type` to be more correct.

File: server/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java (hunk 2 above)
Comment (danhermann) [reply server/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java:52]: Now that #66857 has been closed in favor of #67677, I believe the only improvement that can be made here is changing `content_type` to `media_type`. I'll go ahead and open a PR for that.

**Comment by danhermann** [comment]
@elastic/es-ui, is there work required on the UI side to update Kibana auto-complete with the new `media_type` option on this processor?

**Comment by cjcenizal** [comment]
@danhermann Yes, we'll update Console to autocomplete with this new option when we regenerate all of the autocomplete definitions for 7.12.
