### PR TITLE
Modified searchAndReduce() to return empty agg when no docs exist 

### LINKED ISSUE #55824: AggregatorTestCase.searchAndReduce() returns null as aggregation result
It is common for metric aggregations to test cases that aggregations are run without having inserted any documents first. 

In those cases the expected outcome should be an "empty aggregation" constructed by `Aggregator.buildEmptyAggregation()` 

It was noticed that in the case that no documents have been inserted first, `AggregatorTestCase.searchAndReduce()` returns null. This causes `NullPointerException` errors in some tests.

### PR DESCRIPTION
**Pull request by csoulios**
Modified `AggregatorTestCase.searchAndReduce()` method so that it returns an empty aggregation result when no documents have been inserted.

Also refactored several aggregation tests so they do not re-implement method `AggregatorTestCase.testCase()`

Fixes #55824

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java [hunk 1]
```diff
@@ -499,7 +499,9 @@ protected ScriptService getMockScriptService() {
             InternalAggregationTestCase.assertMultiBucketConsumer(agg, shardBucketConsumer);
         }
         if (aggs.isEmpty()) {
-            return null;
+            root.preCollection();
```
Comment (csoulios) [inline test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:502]: This should all the work for returning an empty aggregation. I am not 100% sure pre-pos-Collection is needed. Feedback is very welcome.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java [hunk 2]
```diff
@@ -155,18 +155,18 @@ public void testMatchAllDocs() throws IOException {
...
-                histogram -> {
-                    assertEquals(0, histogram.getBuckets().size());
-                    assertFalse(AggregationInspectionHelper.hasValue(histogram));
-                }, false
-        );
-        testSearchAndReduceCase(query, dates, aggregation,
-                histogram -> assertNull(histogram), false
-        );
+        Consumer<DateHistogramAggregationBuilder>
+            aggregation =
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java:159]: Extra newline?

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java [hunk 3]
```diff
@@ -228,31 +228,31 @@ public void testSummationAccuracy() throws IOException {
 
     public void testUnmappedField() throws IOException {
         AvgAggregationBuilder aggregationBuilder = new AvgAggregationBuilder("_name").field("number");
-        testCase(aggregationBuilder, new DocValuesFieldExistsQuery("number"), iw -> {
+        this.<AvgAggregationBuilder, InternalAvg>testCase(aggregationBuilder, new DocValuesFieldExistsQuery("number"), iw -> {
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java:231]: Do we need the `<` bits?

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregatorTests.java [hunk 4]
```diff
@@ -181,25 +177,9 @@ private void testCase(Query query, CheckedConsumer<RandomIndexWriter, IOExceptio
         testCase(aggregationBuilder, query, buildIndex, verify, fieldType);
     }
 
-    private void testCase(CardinalityAggregationBuilder aggregationBuilder, Query query,
+    protected void testCase(CardinalityAggregationBuilder aggregationBuilder, Query query,
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregatorTests.java:180]: Maybe rename these so they don't "hide" the superclass method and require the casts?

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java (hunk 1 above)
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:502]: What about just calling `aggregator.buildEmptyAggregation`? I think this one shouldn't need the pre and post stuff. Probably.

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregatorTests.java [hunk 5]
```diff
@@ -181,25 +177,9 @@ private void testCase(Query query, CheckedConsumer<RandomIndexWriter, IOExceptio
...
-        CardinalityAggregator aggregator = createAggregator(aggregationBuilder, indexSearcher,
-            fieldType);
-        aggregator.preCollection();
-        indexSearcher.search(query, aggregator);
-        aggregator.postCollection();
-        verify.accept((InternalCardinality) aggregator.buildAggregation(0L));
-
-        indexReader.close();
-        directory.close();
+        super.testCase(aggregationBuilder, query, buildIndex, verify, fieldType);
```
Comment (csoulios) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregatorTests.java:183]: Creating a method with specific (and not generic) arguments is a shortcut that saves us from writing
```
   this.<CardinalityAggregationBuilder, InternalCardinality>testCase(.....)
```

at every test case. This method simply passes the arguments to the generic `AggregatorTestCase.testCase()` method. I don't have a strong opinion about which option is best and I am happy go with any of the two methods.

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java (hunk 3 above)
Comment (csoulios) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java:231]: The `<` bits are ugly but required, otherwise compile fails. Hence I suggested this:
https://github.com/elastic/elasticsearch/pull/55826#discussion_r416151331

Comment (nik9000) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java:231]: I see what is up. I wonder if it'd be cleaner to return `V` instead of take a `Consumer<V>`. You'd get the implicit cast from assigning it to the result type you wanted. I wonder if that could save us a little ceremony?

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java (hunk 1 above)
Comment (csoulios) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:502]: `aggregator.buildEmptyAggregation()` seems to be working fine. thanks!

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java (hunk 3 above)
Comment (csoulios) [reply server/src/test/java/org/elasticsearch/search/aggregations/metrics/AvgAggregatorTests.java]: For every agg test I have created a local private method named `testAggregation()`. This method converts generic arguments to specific arguments and calls `AggregateTestCase.testCase()`. I think this is a lot cleaner and simpler.

Please check commit 23917bd and let me know what you think.

**Review by nik9000 — APPROVED** [review]
LGTM. It isn't how I'd do it but that is super ok!

**Review by polyfractal — APPROVED** [review]
No strong opinions from me... six one way, half a dozen another.  I'm happy this quirk is getting cleaned up :)
