### PR TITLE
Fix score count validation in reranker response

### LINKED ISSUE #111202: Reranker retriever query fails if window size > top N in inference endpoint
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

The `text_similarity_reranker` retriever query fails if `rank_window_size` is greater than `top_n` in the rerank inference endpoint's task settings.

When creating the inference endpoint we have the option to specify `top_n` to return only N documents. By default this is omitted and the issue doesn't occur. However if e.g. `top_n = 10` is specified in the endpoint and the reranker query defines a `rank_window_size` greater than 10, the reranker process fails due to an array index of bounds error.

### Steps to Reproduce

1. Create a deployment (serverless or 8.15+).
2. Index some documents, e.g. short passages with a `text` field.
3. Create a rerank inference endpoint with `top_n` set in the task settings:
```
PUT _inference/rerank/cohere-rerank-inference-top-10
{
  "service": "cohere",
  "service_settings": {
    "model_id": "rerank-english-v3.0",
    "api_key":  <COHERE_API_KEY>
  },
  "task_settings": {
    "top_n": 10
  }
}
```

4. Run a rerank retriever query with a window size larger than the top N value from above:
```
POST rerank/_search
{
  "retriever": {
    "text_similarity_reranker": {
      "retriever": {
        "standard": {
          "query": {
            "match": {
              "text": "Most famous landmark in Paris"
            }
          }
        }
      },
      "rank_window_size": 20,
      "field": "text",
      "inference_id": "cohere-rerank-inference-top-10",
      "inference_text": "Most famous landmark in Paris"
    }
  },
  "size": 20
}
```

Expected: the query succeeds and returns the top 10 documents.

Observed: the query fails with an error similar to this:
```
{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "Computing updated ranks for results failed",
    "phase": "rank-feature",
    "grouped": true,
    "failed_shards": [],
    "caused_by": {
      "type": "array_index_out_of_bounds_exception",
      "reason": "Index 16 out of bounds for length 10"
    }
  },
  "status": 500
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by demjened**
Fixes https://github.com/elastic/elasticsearch/issues/111202.

The text_similarity_reranker retriever query fails if `rank_window_size` is greater than `top_n` in the rerank inference endpoint's task settings. More details and steps to reproduce in the above mentioned issue.

The cause is [this line](https://github.com/elastic/elasticsearch/blob/61cb0a2b6be3ca2611c7a2d99a3243631684e211/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java#L95). The `rerank` inference response contains document indices in reference to the `rank_window_size` inputs. However if `task_settings.top_n` is specified in the inference endpoint, it only returns the top N of those. For example with `rank_window_size==20` and `top_n==10` this is a valid response:

```
[RankedDoc{index='1', relevanceScore='0.9961155', text='null', hashcode=-1335808012},
RankedDoc{index='15', relevanceScore='0.9865199', text='null', hashcode=-1340785186},
RankedDoc{index='3', relevanceScore='0.049773447', text='null', hashcode=1815090117}, 
... (7 more RankedDoc-s)]
```

The problematic line creates a `scores` array with a length of 10, but processing the 2nd item (`index='15'`) triggers the out-of-bounds exception.

The validation of rereanker input == score output is already in place (and covered by the `TextSimilarityRankTests#testRerankInferenceFailure` test), however due to the above bug the process never reaches that state, it fails with an index out of bounds exception. The solution is to move the validation logic before the scores are extracted.

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 1]
```diff
@@ -54,12 +54,24 @@ protected void computeScores(RankFeatureDoc[] featureDocs, ActionListener<float[
...
-            if (scores.length != featureDocs.length) {
+            InferenceServiceResults results = r.getResults();
+            assert results instanceof RankedDocsResults;
+
+            // Ensure we get exactly as many scores as the number of docs we passed, otherwise we may return incorrect results
+            List<RankedDocsResults.RankedDoc> rankedDocs = ((RankedDocsResults) results).getRankedDocs();
+            if (rankedDocs.size() != featureDocs.length) {
                 l.onFailure(
-                    new IllegalStateException("Document and score count mismatch: [" + featureDocs.length + "] vs [" + scores.length + "]")
+                    new IllegalStateException(
```
Comment (pmpailis) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:64]: Could we also add a test that throws this exception?

**Review by benwtrent — COMMENTED** [review]
Nice catch! Let's have a test that would fail with an IOOB exception without this fix and then throws the better exception now.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java (hunk 1 above)
Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:64]: @benwtrent @pmpailis I added a test case for simulating invalid indices (https://github.com/elastic/elasticsearch/pull/111212/commits/7e3f153410e4de7eb69094176cb06edd21457682).

Note I don't think it actually covers the use case, because it's a sub-case of the reranker input/output count mismatch. With the bugfix this is now caught before the actual doc index assignment happens that would trigger the IOOB. (We do not have specific handling of N inputs -> N outputs -> index pointing outside 0..N-1, I'd consider that a reranker error.)

Comment (benwtrent) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:64]: @demjened AH, ok, is there a way to parse this `top_n` setting and validate that it matches the window size earlier in the request? That seems like we should return "Bad Request" in that scenario.

Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:64]: @benwtrent Not without issuing a GET call before each inference call to check the inference endpoint's configuration, I'm afraid. The rerank retriever framework only exposes hooks for creation and [submission of an inference request](https://github.com/elastic/elasticsearch/blob/97f62945312c5141a7130bbf00066cb41e6d4560/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java#L70), and parsing the results, but it doesn't know about the config.

**Comment by Mikep86** [comment]
Is it OK if `top_n` > `rank_window_size`?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 2]
```diff
@@ -54,12 +54,24 @@ protected void computeScores(RankFeatureDoc[] featureDocs, ActionListener<float[
...
+                        "Document and score count mismatch: ["
+                            + featureDocs.length
+                            + "] vs ["
+                            + rankedDocs.size()
+                            + "]. Check your rerank inference endpoint configuration and ensure it returns rank_window_size scores for "
+                            + "rank_window_size input documents."
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:70]: This error message requires some non-trivial interpretation by the user. IMO would be better to be direct, something along the lines of "check that `top_n` >= `rank_window_size`".

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java [hunk 3]
```diff
@@ -37,6 +37,20 @@ public class TextSimilarityRankTests extends ESSingleNodeTestCase {
      */
     public static class InvalidInferenceResultCountProvidingTextSimilarityRankBuilder extends TextSimilarityRankBuilder {
 
+        private boolean hasInvalidDocumentIndices = false;
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:40]: Kind of a nit, but I think this test would be more configurable and understandable if we could just pass in an integer value for for `top_n`. It more closely reflects how this error would occur in production.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java [hunk 4]
```diff
@@ -164,6 +179,27 @@ public void testRerankInferenceResultMismatch() {
...
+                        "my-rerank-model",
+                        "my query",
+                        100,
+                        1.5f,
+                        true
+                    )
+                )
+                .setQuery(QueryBuilders.matchAllQuery()),
+            RestStatus.INTERNAL_SERVER_ERROR,
+            containsString("Failed to execute phase [rank-feature], Computing updated ranks for results failed")
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: Two things here:

- We should return a 400 response here, the error is ultimately due to a bad value provided by the user
- Can we test that the returned error message contains the root cause of the problem (i.e. "Document and score count mismatch")?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java [hunk 5]
```diff
@@ -164,6 +179,27 @@ public void testRerankInferenceResultMismatch() {
         );
     }
 
+    public void testRerankInvalidDocumentIndices() {
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:182]: This is a nit, but this test name could be misleading to someone reading the code quickly and without context. In the context of ES, "index" usually refers to a collection of documents, which is especially easy to confuse here given the "DocumentIndices" terminology. Could we change the name to something that more clearly indicates this is testing when `top_n` < `rank_window_size`?

**Review by Mikep86 — COMMENTED** [review]
Good catch on the bug!

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 4 above)
Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: The error response is produced [here](https://github.com/elastic/elasticsearch/blob/52834fe041da5cfe4a2b09fcb9b72ba05785a23c/server/src/main/java/org/elasticsearch/action/search/RankFeaturePhase.java#L197), which responds to an `IllegalStateException`. @pmpailis do you know of any way to turn this into a 400?

I'll look into using different matchers in the test to verify the cause.

Comment (Mikep86) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: We should work on making the HTTP response code configurable. 500 == rest suppressed errors == things to investigate during serverless on-call

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 3 above)
Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:40]: It does make things cleaner, but then we should also remove the "invalid indices in the top_n < rank_window_size" test case because the process doesn't care about the invalid indices, it raises the error beforehand (see [comment](https://github.com/elastic/elasticsearch/pull/111212#discussion_r1689985230)). WDYT?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 4 above)
Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: Update: there's no method in [ElasticsearchAssertions#assertFailures](https://github.com/elastic/elasticsearch/blob/52834fe041da5cfe4a2b09fcb9b72ba05785a23c/test/framework/src/main/java/org/elasticsearch/test/hamcrest/ElasticsearchAssertions.java#L496) that we can use to check the cause of a shard failure 🙁.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:64]: > Not without issuing a GET call before each inference call to check the inference endpoint's configuration, I'm afraid...  but it doesn't know about the config.

We need to fix this. If there are things that are invalid for a configuration & a search request, we need to fix this.

Calling a local GET to retrieve some minor documentation is way cheaper than calling some external service when the we know the request will fail. I would hold off on merging or progressing this until we can eagerly validate the search request as we know ahead of time that it won't work.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 4 above)
Comment (pmpailis) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: I think that we could slightly rewrite this to capture the cause's message (as there won't be any response to decref). E.g:
```
        SearchPhaseExecutionException ex = expectThrows(
            SearchPhaseExecutionException.class,
            client.prepareSearch()
                .setRankBuilder(
                    // Simulate reranker returning different number of results from input, also invalid document indices in results
                    new InvalidInferenceResultCountProvidingTextSimilarityRankBuilder(
                        "text",
                        "my-rerank-model",
                        "my query",
                        100,
                        1.5f,
                        true
                    )
                )
                .setQuery(QueryBuilders.matchAllQuery())::get
        );
        assertThat(ex.getDetailedMessage(), containsString("Document and score count mismatch"));
```

Comment (pmpailis) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: I think that we could slightly rewrite this to capture the cause's message (as there won't be any response to decref).
E.g:
```
        SearchPhaseExecutionException ex = expectThrows(
            SearchPhaseExecutionException.class,
            client.prepareSearch()
                .setRankBuilder(
                    // Simulate reranker returning different number of results from input, also invalid document indices in results
                    new InvalidInferenceResultCountProvidingTextSimilarityRankBuilder(
                        "text",
                        "my-rerank-model",
                        "my query",
                        100,
                        1.5f,
                        true
                    )
                )
                .setQuery(QueryBuilders.matchAllQuery())::get
        );
        assertThat(ex.getDetailedMessage(), containsString("Document and score count mismatch"));
```

Comment (pmpailis) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:199]: > @pmpailis do you know of any way to turn this into a 400?

The status of the error is determined through the `SearchPhaseExecutionException#status`, which in turn uses the cause for the exception through `org.elasticsearch.ExceptionsHelper#status` .  I think converting the `IllegalStateException` to an `IllegalArgumentException` should be enough to have a 400 response.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 3 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:40]: I don't think we should remove that test, but we should rename it. Ultimately, we need a test for when `top_n` < `rank_window_size`, no matter what it is called.

Comment (benwtrent) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:40]: Agreed, we should have a test that throws a `BAD_REQUEST` when we see that `rank_window_size` is larger than the referenced inference top_n configuration.

This check should be done eagerly, before the inference request is made.

Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:40]: @Mikep86  What I mean is currently there are two overlapping tests: `testRerankInferenceResultCountMismatch` and `testRerankInvalidDocumentIndices`. Both set the `top_n` to be less than `rank_window_size`, the latter also corrupts some document indices in the reranker respose to point outside the returned range. This is what was throwing the IOOE the first place.

This state however will never be reached with this fix in place, because if `top_n < rank_window_size`, we fail fast without ever reaching the result processing and finding the invalid indices. So I don't see a point for keeping both test cases.

There _is_ a possible use case where `top_n == rank_window_size` and yet there is an `index` property pointing outside the N elements. But this means there's something broken in the reranker and it doesn't honor the API contract, which is not under our control. I'd argue whether we want to add new code to validate the result and throw an exception if the indices are off, or just let the IOOE cover it. (If we did that, where do we draw the line for validation? Checking that they are all integers? Ensuring there are no duplicates? etc.)

Comment (Mikep86) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:40]: Got it, then i don't see a reason to keep the second test. Let's modify `testRerankInferenceResultCountMismatch` to check that `BAD_REQUEST` is returned, per @benwtrent's guidance.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java (hunk 1 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:64]: Could we modify the rerank inference service to check if `top_n` < `rank_window_size`, and throw an appropriate exception before the call to Cohere (or any other external provider/model)?

Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:87]: @benwtrent @Mikep86 @pmpailis I'll summarize the latest changes here that accommodates all your suggestions (thanks for those):
- There is now handling logic for two failure scenarios: 1. we find out that `task_settings.top_n < rank_window_size` and preemptively fail before running the inference, 2. the reranker actually returns <>N output on N inputs. These are tested in `testRerankTopNConfigurationAndRankWindowSizeMismatch()` and `testRerankInputSizeAndInferenceResultsMismatch()` respectively.
- The 1st scenario results in a 400, the 2nd one a 500 (as it's not a client-side error if the reranker misbehaves).
- The extraction logic of `top_n` from the fetched inference endpoint config is [vendor-specific](https://github.com/elastic/elasticsearch/pull/111212/files#diff-b26d78113170a533a4916c2b0f58aa28e2a59df3b3c7671760e8a320104ed479R148-R156). I'm not happy about this, but the empty `TaskSettings` interface doesn't give me much options to get the top N other than casting after a type check.
- In the test class, the mock configuration for scenario 1 requires passing the expected top N as part of the inference ID and [parsing it](https://github.com/elastic/elasticsearch/pull/111212/files#diff-8f058251ff737cad9ab6eebb676447455ca3fcaaa4c8f8eb825bc65cdbd02b6eR135-R140) (i.e. `my-inference-id-task-settings-top-3 -> top_n=3`). Again I'm not proud of this implementation, but `GetInferenceModelAction` has a very limited interface to pass control parameters in in order to mock behavior in a test.
- Reworded the error messages to make them more clear and actionable. Also the failure tests now check the exact message, based on Panos' suggestion.

Let me know if you feel there are still things to improve and must go in this PR; I want to timebox the remaining effort as the bug has been fixed and I want to make sure this gets merged by 8.15.0 BC5.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 6]
```diff
@@ -106,15 +138,16 @@ private float[] extractScoresFromRankedDocs(List<RankedDocsResults.RankedDoc> ra
...
+    private Integer getTopNFromInferenceEndpointTaskSettings() {
+        GetInferenceModelAction.Request request = new GetInferenceModelAction.Request(inferenceId, TaskType.RERANK);
+        ActionFuture<GetInferenceModelAction.Response> response = client.execute(GetInferenceModelAction.INSTANCE, request);
+        ModelConfigurations modelConfigurations = response.actionGet().getEndpoints().get(0);
+
+        return modelConfigurations.getService().equals(CohereService.NAME)
+            && modelConfigurations.getTaskType().equals(TaskType.RERANK)
+            && modelConfigurations.getTaskSettings() instanceof CohereRerankTaskSettings
+                ? ((CohereRerankTaskSettings) modelConfigurations.getTaskSettings()).getTopNDocumentsOnly()
+                : null;
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java]: Lets not use an "ActionFuture" this will take a thread and block on it. We should instead keep it all asynchronous.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 7]
```diff
@@ -51,6 +56,22 @@ public TextSimilarityRankFeaturePhaseRankCoordinatorContext(
...
+                new IllegalArgumentException(
+                    "Inference endpoint ["
+                        + inferenceId
+                        + "] is configured to return the top ["
+                        + inferenceEndpointTopN
+                        + "] results. Reduce rank_window_size to be less than or equal to this value."
+                )
+            );
+            return;
+        }
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:75]: We should definitely keep this asynchronous. Rule of thumb, never use an ActionFuture or make a async call synchronous when you can easily avoid it. 

It should be something like this (obviously with things better filled in)
```java
        // The rerank inference endpoint may have an override to return top N documents only, in that case let's fail fast to avoid
        // assigning scores to the wrong inputs
        // rank Listener
        final ActionListener<InferenceAction.Response> actionListener = scoreListener.delegateFailureAndWrap((l, r) -> {
            // rank task
        }); 

        // top N listener
        GetInferenceModelAction.Request request = new GetInferenceModelAction.Request(inferenceId, TaskType.RERANK, );
        ActionListener<GetInferenceModelAction.Response> topNListener = ActionListener.wrap(
            topN -> {
                Integer topNDocs = null;
                if (topN.getEndpoints().get(0).getTaskSettings() instanceof CohereRerankTaskSettings cohere) {
                    topNDocs = cohere.getTopNDocumentsOnly();
                } else if (topN.getEndpoints().get(0).getTaskSettings() instanceof GoogleVertexAiRerankTaskSettings googl) {
                    topNDocs = googl.topN();
                }
                if (topNDocs != null && topNDocs < featureDocs.length) {
                    scoreListener.onFailure(
                        new IllegalArgumentException(
                            "Inference endpoint ["
                                + inferenceId
                                + "] is configured to return the top ["
                                + topNDocs 
                                // indicate what the rank window size is
                                + "] results. Reduce rank_window_size to be less than or equal to this value."
                        )
                    );
                    return;
                }
                List<String> featureData = Arrays.stream(featureDocs).map(x -> x.featureData).toList();
                InferenceAction.Request inferenceRequest = generateRequest(featureData);
                try {
                    client.execute(InferenceAction.INSTANCE, inferenceRequest, actionListener);
                } finally {
                    request.decRef();
                }
            },
            f -> {
                // throw appropriate errors.
            }
        );
client.execute(GetInferenceModelAction.INSTANCE, request, topNListener);
```

**Review by benwtrent — COMMENTED** [review]
Looking way better!

Let's keep it async, but this is looking nice.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java (hunk 1 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:87]: Heads up that @demjened & I discussed offline yesterday and we're going to investigate doing the `task_settings.top_n < rank_window_size` check in ML code

Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:87]: @Mikep86 I've been thinking about this; while moving this logic to the ML code would make it cleaner and would remove coupling, I'm worried it's not a good idea from a product perspective.

For reference, here's the code you suggested that would replace the preemptive top_n check from the reranker:
```java
// CohereService#doInfer
...
        CohereModel cohereModel = (CohereModel) model;
        var actionCreator = new CohereActionCreator(getSender(), getServiceComponents());

        if (model instanceof CohereRerankModel rerankModel) {
            Integer topN = rerankModel.getTaskSettings().getTopNDocumentsOnly();
            if (topN != null && topN < input.size()) {
                listener.onFailure(new IllegalArgumentException("top_n < doc count"));
                return;
            }
        }
...
```

The problem is we're invalidating a normal use case. It _is_ a valid scenario that a rerank endpoint is configured to return a maximum of N hits for >N inputs. It's only an issue from the reranker _retriever's_ perspective, where the a `model.top_k < retriever.rank_window_size` can lead to partial or incorrect results.

So we have 3 options to implement the check:
1. (Current) Fetch task settings and validate in retriever context. Problem: coupling with ML code, need to maintain.
2. (Proposal in this comment) Move validation to `XxxService`-s in ML code. Problem: invalidating valid use case.
3. Maybe a control flag to toggle this validation in ML code - `doInfer(..., inputSizeMustMatchTopN)` + the code above? Problem: complex, requires refactoring of the interface and transport objects.

WDYT?

Comment (benwtrent) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:87]: It is valid for the the reranker API to return fewer docs as that is the whole point of `topN`. Otherwise, why is it even configurable?

The retriever also sets window size. For now, we should enforce that window size is <= topN. Maybe we can adjust this in the future, but for retrievers, this is a sane default  & safe behavior.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java (hunk 7 above)
Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java]: @benwtrent Thanks for the code snippet, I updated it.

One question regarding your comment:
```
            f -> {
                // throw appropriate errors.
            }
```
Isn't it sufficient to just delegate to the outer listener, i.e. `scoreListener.onFailure(f)`?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java [hunk 8]
```diff
@@ -151,17 +156,36 @@ public void testRerankInferenceFailure() {
...
+                    new TextSimilarityRankBuilder("text", "my-rerank-model-task-settings-top-3", "my query", 100, 1.5f)
                 )
-                .setQuery(QueryBuilders.matchAllQuery()),
-            RestStatus.INTERNAL_SERVER_ERROR,
-            containsString("Failed to execute phase [rank-feature], Computing updated ranks for results failed")
+                .setQuery(QueryBuilders.matchAllQuery())
+        );
+        assertThat(
+            ex.getDetailedMessage(),
+            containsString("Reduce rank_window_size to be less than or equal to the configured top N value.")
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:173]: Can we test that the cause is an `IllegalArgumentException` here, to verify that the user will get a 400 response?

Even better if we could test that the response code is 400 directly :)

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java [hunk 9]
```diff
@@ -151,17 +156,36 @@ public void testRerankInferenceFailure() {
...
+            SearchPhaseExecutionException.class,
+            // Execute search with text similarity reranking
+            client.prepareSearch()
+                .setRankBuilder(
+                    // Simulate reranker returning different number of results from input
+                    new InferenceResultCountAcceptingTextSimilarityRankBuilder("text", "my-rerank-model", "my query", 100, 1.5f, 4)
+                )
+                .setQuery(QueryBuilders.matchAllQuery())
         );
+        assertThat(ex.getDetailedMessage(), containsString("Reranker input document count and returned score count mismatch"));
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:188]: Similar here, can we test that the cause is `IllegalStateException`, or that the response code is 500?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityTestPlugin.java [hunk 10]
```diff
@@ -100,31 +108,66 @@ public int order() {
...
-            boolean hasInvalidInferenceResultCount = (boolean) ((InferenceAction.Request) request).getTaskSettings()
-                .getOrDefault("invalidInferenceResultCount", false);
+        @SuppressWarnings("unchecked")
+        private <Response extends ActionResponse> void handleGetInferenceModelActionRequest(
+            GetInferenceModelAction.Request request,
+            ActionListener<Response> listener
+        ) {
+            String inferenceEntityId = request.getInferenceEntityId();
+            Integer topN = null;
+            Matcher extractTopN = Pattern.compile(".*(task-settings-top-\\d+).*").matcher(inferenceEntityId);
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityTestPlugin.java:137]: IMO would be a bit cleaner if top N was passed explicitly as a constructor arg, like you do with `InferenceResultCountAcceptingTextSimilarityRankBuilder`

**Review by Mikep86 — COMMENTED** [review]
Nice work, I like the new approach 🙌

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 8 above)
Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java]: Done.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java (hunk 9 above)
Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankTests.java:210]: Done.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityTestPlugin.java (hunk 10 above)
Comment (demjened) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityTestPlugin.java:137]: Done.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 11]
```diff
@@ -53,24 +56,75 @@ public TextSimilarityRankFeaturePhaseRankCoordinatorContext(
...
+                            + configuredTopN
+                            + "] results, but rank_window_size is ["
+                            + rankWindowSize
+                            + "]. Reduce rank_window_size to be less than or equal to the configured top N value."
+                    )
+                );
+                return;
+            }
+            List<String> featureData = Arrays.stream(featureDocs).map(x -> x.featureData).toList();
+            InferenceAction.Request inferenceRequest = generateRequest(featureData);
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:106]: @demjened So, While we are doing all this validation and work, there has been this assumption that the `top_n` value is static. Couldn't we pass a hashmap where the value of `top_n: <rank_window_size>`?

I see that the `InferenceAction.Request` accepts a bunch of various override options.

Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:106]: @benwtrent We could do that, but I don't think it's the best approach. Since `max_n` is optional, there might a reason for a customer wanting to set it when creating the endpoint; maybe they want to control the cost of model inference. I think it's better to be explicit if there is a mismatch than overriding the configuration silently. (The customer can easily remove the limitation by updating the task settings, or creating a separate inference endpoint without top N.)
WDYT?

Comment (benwtrent) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:106]: Yeah, we can fail for now and potentially adjust in the future. I just noticed the code and wanted to make sure we considered it.

**Review by benwtrent — APPROVED** [review]

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 12]
```diff
@@ -53,24 +56,75 @@ public TextSimilarityRankFeaturePhaseRankCoordinatorContext(
...
-            client.execute(InferenceAction.INSTANCE, request, actionListener);
-        } finally {
-            request.decRef();
-        }
+        // top N listener
+        ActionListener<GetInferenceModelAction.Response> topNListener = scoreListener.delegateFailureAndWrap((l, r) -> {
+            // The rerank inference endpoint may have an override to return top N documents only, in that case let's fail fast to avoid
+            // assigning scores to the wrong input
+            Integer configuredTopN = null;
+            if (r.getEndpoints().get(0).getTaskSettings() instanceof CohereRerankTaskSettings cohereTaskSettings) {
```
[the remark this answers is not in the document]
Comment (demjened) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java]: Yeah, if the inference endpoint doesn't exist or it's not a `rerank` type. I added a check for `getEndpoints().isEmpty() == false`.
