### PR TITLE
Do not mark bulk indexing requests as retried after primary relocations

### LINKED ISSUE #141586: Do not mark bulk indexing requests as retried after primary relocations
When a shard relocation occurs, in-flight indexing operations wait to acquire a primary permit until the relocation completes. Upon successful relocation, these operations receive a [`RetryOnPrimaryException`](https://github.com/elastic/elasticsearch/blob/c3f07ad1ec13ba9c688adbea9c094563cfd69bff/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L484-L494), which [marks the request as retried](https://github.com/elastic/elasticsearch/blob/c3f07ad1ec13ba9c688adbea9c094563cfd69bff/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L1088-L1096). This [forces a version lookup](https://github.com/elastic/elasticsearch/blob/184c51b9edcf82fada430492acd28f4e336a0364/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L1516-L1519) during indexing on the new primary, even for operations that could have used the auto-generated ID append-only optimization.

For shards with high indexing throughput, relocations can take a while to complete. During this time, many operations queue up, all marked as retried. When they finally execute on the new primary, they must perform version lookups (requiring at least a terms dictionary lookup) with a likely cold cache. This can overwhelm the new primary shard.

We should detect this situation and avoid marking the request as retried, since we can safely assume the documents were not indexed on the old primary.

### PR DESCRIPTION
**Pull request by pxsalehi**
I've added a flag to `RetryOnPrimaryException` which indicates whether the request which is to be retried might have ran or not. If true (default value and default behaviour before this PR) the request is marked as retry. If false, it is safe to run the request as if it is not a retry, and we skip marking it as a retry. This should impact only [one specific path](https://github.com/elastic/elasticsearch/blob/f8908057ea3e95374b720c2a5f70d2598220569e/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L493) of the retries in the TransportReplicationAction.

Assisted by Cursor

Closes https://github.com/elastic/elasticsearch/issues/141586.
Relates ES-14121

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 1]
```diff
@@ -1066,6 +1067,15 @@ public void handleException(TransportException exp) {
                     try {
                         // if we got disconnected from the node, or the node / shard is not in the right state (being closed)
                         final Throwable cause = exp.unwrapCause();
+                        boolean markAsRetry = true;
+                        // When the request is forwarded to the relocated primary (during relocation handoff),
+                        // and that node throws a RetryOnPrimaryException, the request has NOT been executed yet.
+                        // In this case, we should NOT mark the request as a retry to avoid unnecessary version lookups.
+                        if (isPrimaryAction
+                            && cause.getClass() == ReplicationOperation.RetryOnPrimaryException.class
+                            && request instanceof BulkShardRequest) {
```
Comment (pxsalehi) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: I've included that last check (that the request is a bulk shard request) just to make this very specific. Otherwise, I think it is implied.

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java [hunk 2]
```diff
@@ -0,0 +1,130 @@
...
+
+        var indicesService = internalCluster().getInstance(org.elasticsearch.indices.IndicesService.class, node2);
+        var indexService = indicesService.indexService(resolveIndex("index1"));
+        var indexShard = indexService.getShardOrNull(0);
+        assertNotNull(indexShard);
+        long numVersionLookups = indexShard.tryWithEngineOrNull(engine -> {
+            assertNotNull(engine);
+            return EngineTestCase.getNumIndexVersionLookups(engine);
+        });
+        assertThat(numVersionLookups, equalTo((long) indexRequestsWithId));
```
Comment (pxsalehi) [inline server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:162]: hmmm... this doesn't alway hold (could be less or more!). Not sure why. I'll try to find out...

Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:162]: ok. I think sometimes the retry happens earlier, when the request is routed to another node initially and due to some [cluster state version check](https://github.com/pxsalehi/elasticsearch/blob/da6c79ef195df73994d84a3c9c086ef8bfdccf65/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L933) it will retry with `UnavailableShardsException`. It seems to me that is also safe to not mark as retry as we know we haven't done the work. Does that make sense?

Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:162]: pushed https://github.com/elastic/elasticsearch/pull/142157/commits/57b6a2cb03857a4641888380c86e4ea693665bc0, ~but I'll check more~.

Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:162]: The other case during reroute is when there is [a retryable block](https://github.com/pxsalehi/elasticsearch/blob/da6c79ef195df73994d84a3c9c086ef8bfdccf65/server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L815). But I am not going to touch that. I think we can leave that as is, as that is not directly related to the relocation case we are fixing here.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
Comment (pxsalehi) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Or would it be more obviously correct, if we change the exception we throw here and check for that exception dow in this file (instead of `RetryOnPrimaryException` and to distinguish between the cases in `org.elasticsearch.action.support.replication.ReplicationOperation#onNoLongerPrimary`)? [This case](https://github.com/elastic/elasticsearch/blob/82756e97fe2cfda32df090d73494f40b3fed4a5a/server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java#L331) for example doesn't necessarily mean that the operation didn't do any changes, but then again it also means the shard copy is not authoritative on what is the latest state, AFAIU.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: I'd like to omit that - or if we need it, make it a protected method that is overridden for bulk shard action.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: I would find that easier to reason about. We may then incrementally move other exceptions over to be the new "do not mark retry" exception (better name needed).

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 3]
```diff
@@ -1090,14 +1100,20 @@ public void handleException(TransportException exp) {
...
             assert failure != null;
             if (observer.isTimedOut()) {
                 // we running as a last attempt after a timeout has happened. don't retry
                 finishAsFailed(failure);
                 return;
             }
             setPhase(task, "waiting_for_retry");
-            request.onRetry();
+            if (markRequestAsRetry) {
+                request.onRetry();
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Maybe we need to clarify the behavior on ReplicationRequest.onRetry, i.e., that it may not be called if the action did not do any real work yet.

We could also consider adding the `markRequestAsRetry` (under another name) boolean to the method instead, mainly to make the contract clearer (same functionality).

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+
+@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, numDataNodes = 0)
+public class RelocationCausedIndexingRetryIT extends ESIntegTestCase {
+
+    @Override
+    protected Collection<Class<? extends Plugin>> nodePlugins() {
+        return List.of(MockTransportService.TestPlugin.class);
+    }
+
+    public void testPrimaryRelocationShouldNotMarkIndexRequestAsRetry() throws Exception {
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:43]: Do we have the opposite test, i.e., that we still mark as retry when necessary?

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+        if (useBulk) {
+            BulkRequestBuilder bulk = client().prepareBulk();
+            for (int i = 0; i < indexRequestsWithId; i++) {
+                bulk.add(prepareIndex("index1").setId(randomUUID()).setSource("text", randomAlphaOfLength(10)));
+            }
+            for (int i = 0; i < indexRequestsWithoutId; i++) {
+                bulk.add(prepareIndex("index1").setSource("text", randomAlphaOfLength(10)));
+            }
+            final var listener = bulk.execute();
+            continueRelocationLatch.countDown();
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:129]: Should we wait for the bulk to arrive and wait for the permit - to ensure we are in the handoff case and not the reroute phase?

We should probably also have tests for the reroute phase though.

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+            safeAwait(node1ForwardedTheBulk);
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java]: I am not sure waiting here does anything beyond waiting for the listener? We could assert that it got forwarded after the listener invocation instead, but we already check that it was received by node 2, which I think is enough.

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+            final var bulkResponse = listener.get();
+            assertThat(node2ReceivedTheBulk.get(), equalTo(true));
+            assertThat(bulkResponse.hasFailures(), equalTo(false));
+            assertThat(bulkResponse.getItems().length, equalTo(indexRequestsWithId + indexRequestsWithoutId));
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:133]: Should we verify that the ids returned can be looked up? I imagine that if anything went wrong with the retry mechanism, i.e., we indeed did process the same auto-id insertion twice, the lookup might fail.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 8]
```diff
@@ -1066,6 +1067,15 @@ public void handleException(TransportException exp) {
                     try {
                         // if we got disconnected from the node, or the node / shard is not in the right state (being closed)
                         final Throwable cause = exp.unwrapCause();
+                        boolean markAsRetry = true;
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Can we make the calculation here a method instead? Together with a dedicated exception that seems like it could operate purely on the exception. It can have a default return true in `TransportReplicationAction` and be overridden in `TransportShardBulkAction` to ensure we only impact that.

It can also be called inline below instead then.

**Review by henningandersen — COMMENTED** [review]
Left a few comments. I did not try to deeply investigate whether all `RetryOnPrimaryException` should disregard the retry, let me know if you think it is the right route to go.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
Comment (pxsalehi) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: @henningandersen do you have an objection to only addressing this specific case of `RetryOnPrimaryException` here and not the `UnavailableShardsException`? We won't change the reroute phase in this case. The latter is I believe a separate issue. That limits this PR to this one change and we don't have to weed out the `UnavailableShardsException` cases which I think are not the main issue. I can track that in a separate issue. At the very minimum, I think they can be two separate PRs and go in independently.

Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Yeah, I am good with not doing anything for unavailability, seems like a very different case. We are primarily after improving the happy path.

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java (hunk 4 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:43]: There are also previous unit tests. I've also added and update some in `TransportReplicationActionTests`. The change set touches fewer patch than the last one though (see [here](https://github.com/elastic/elasticsearch/pull/142157#discussion_r2805111286)).

File: server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java (hunk 5 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/action/support/replication/RelocationCausedIndexingRetryIT.java:129]: these are addressed i think now.

**Review by pxsalehi — COMMENTED** [review]
Thanks for the review @henningandersen. this is ready for another round.

File: server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequest.java [hunk 9]
```diff
@@ -278,11 +278,17 @@ public String getDescription() {
...
+    public void onRetry() {
+        onRetry(true);
+    }
+
     /**
-     * This method is called before this replication request is retried
-     * the first time.
+     * Called before this replication request is retried.
+     * <p>
+     * {@code markAsRetry} controls whether request should be marked as retry or not. For some retry paths (for example
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequest.java]: Can we name this similar to the exception boolean, i.e., possiblyExecuted? I find that slightly better since `onRetry` with a `mark` boolean seems slightly confusing.

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 10]
```diff
@@ -1077,7 +1077,11 @@ public void handleException(TransportException exp) {
                                 ),
                                 exp
                             );
-                            retry(exp);
+                            boolean markAsRetry = true;
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: can we keep the `possiblyExecuted` naming?

File: server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java [hunk 11]
```diff
@@ -1090,14 +1094,18 @@ public void handleException(TransportException exp) {
         }
 
         void retry(Exception failure) {
+            retry(failure, true);
+        }
+
+        void retry(Exception failure, boolean markRequestAsRetry) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java]: Also `possiblyExecuted` naming here.

**Review by henningandersen — APPROVED** [review]
LGTM.
