### PR TITLE
Fix InternalEngineTests.testMergeThreadLogging

### LINKED ISSUE #90071: [CI] InternalEngineTests testMergeThreadLogging failing
Also seen in a local run of `./gradlew :server:test` but doesn't easily reproduce, even when running many iterations in a loop.

**Build scan:**
https://gradle-enterprise.elastic.co/s/kbbpmnbim32ck/tests/:server:test/org.elasticsearch.index.engine.InternalEngineTests/testMergeThreadLogging

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testMergeThreadLogging" -Dtests.seed=A7B12EB0B151C9B5 -Dtests.locale=es-PA -Dtests.timezone=Europe/Tiraspol -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

Edit to add: eventually this failed for me after a couple of thousand iterations on a machine that was concurrently running `stress-ng --timeout 0 --cpu 16`

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.engine.InternalEngineTests&tests.test=testMergeThreadLogging

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: (an empty collection or iterable containing [a string starting with "JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration.", a string starting with "JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. "] or iterable containing [a string starting with "JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. "])
     but: was <[Attempted to append to non-started appender testMergeThreadLogging]>

  at __randomizedtesting.SeedInfo.seed([A7B12EB0B151C9B5:62EC5C98C993D8A4]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:658)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:464)
  at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by tlrx**
The test has to wait for all merge thread log messages (include Lucene ones) to be seen before reset the log level and stop the appender.

Previous attempt wasn't enough: the test failure in https://github.com/elastic/elasticsearch/issues/90071#issuecomment-1638128883 shows that Lucene's merge scheduler thread can log after the Elasticsearch one, and if the appender has been closed in the meanwhile it can fail the test.

```java
1> [2023-07-17T11:33:12,559][TRACE][o.e.i.e.Engine           ] [testMergeThreadLogging] [index][0] rollback indexWriter done
  1> [2023-07-17T11:33:12,559][DEBUG][o.e.i.e.Engine           ] [testMergeThreadLogging] [index][0] engine closed [api]
  1> [2023-07-17T11:33:12,562][DEBUG][o.e.i.s.Store            ] [testMergeThreadLogging] [index][0] store reference count on close: 0
  1> [2023-07-17T11:33:12,562][TRACE][o.e.i.e.I.EngineMergeScheduler] [[index] [index][0] merge thread elasticsearch[[index][0]: Lucene Merge Thread #0] end
  1> [2023-07-17T11:33:12,562][TRACE][o.e.i.e.E.MS             ] [[index] [index][0] elasticsearch[[index][0]: Lucene Merge Thread #0] MS: merge thread elasticsearch[[index][0]: Lucene Merge Thread #0] end
  1> 2023-07-17 11:33:12,568 elasticsearch[[index][0]: Lucene Merge Thread #0] ERROR Attempted to append to non-started appender testMergeThreadLogging
  1> [2023-07-17T11:33:12,589][WARN ][o.e.i.e.Engine           ] [org.elasticsearch.index.engine.InternalEngineTests] [index][0] failed engine [merge failed]
  1> org.apache.lucene.index.MergePolicy$MergeException: org.apache.logging.log4j.core.appender.AppenderLoggingException: Attempted to append to non-started appender testMergeThreadLogging
  1> 	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun(InternalEngine.java:2780) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
  1> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
  1> Caused by: org.apache.logging.log4j.core.appender.AppenderLoggingException: Attempted to append to non-started appender testMergeThreadLogging
```

This pull request ensure that the appender saw the Merge Scheduler `end` message before resetting the log level and close the engine.

Closes #90071

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 1]
```diff
@@ -2613,26 +2625,29 @@ public void testMergeThreadLogging() throws Exception {
...
+                        containsInRelativeOrder(
+                            matchesRegex("^merge thread .* start$"),
+                            matchesRegex("^merge thread .* merge segment.*$"),
+                            matchesRegex("^merge thread .* end$")
+                        )
+                    );
+                    assertThat(mockAppender.mergeCompleted(), is(true));
+                });
+
+                Loggers.setLevel(rootLogger, savedLevel);
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java:2648]: nit are these needed? Because I see the .setLevel also in the finally(), but I do not see the engine.close() there (but I assume it happens automatically somehow?).

**Review by kingherc — APPROVED** [review]
Nice finding!

>  [2023-07-17T11:33:12,562][TRACE][o.e.i.e.I.EngineMergeScheduler] [[index] [index][0] merge thread elasticsearch[[index][0]: Lucene Merge Thread #0] end
> [2023-07-17T11:33:12,562][TRACE][o.e.i.e.E.MS             ] [[index] [index][0] elasticsearch[[index][0]: Lucene Merge Thread #0] MS: merge thread elasticsearch[[index][0]: Lucene Merge Thread #0] end

For my knowledge, what's MS? And why are there two same messages? I guess the second one failed (because the logger was closed in the meantime)?

File: server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java (hunk 1 above)
Comment (tlrx) [reply server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java:2648]: Not really needed, but wanted to reset the log level before closing the engine (which can also log more things that we are not interested in this test)

**Comment by tlrx** [comment]
Thanks Iraklis!
