### PR TITLE
Fix Snapshot not Starting in Partial Snapshot Corner Case

### LINKED ISSUE #59384: SnapshotResiliencyTests testSnapshotWithNodeDisconnects and testSnapshotPrimaryRelocations failures
**Build scan**:
https://gradle-enterprise.elastic.co/s/puwxv532d7p5u

**Repro line**:
```
 ./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotWithNodeDisconnects" \
  -Dtests.seed=AB11F5CEE90655C4 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SY \
  -Dtests.timezone=Pacific/Pitcairn \
  -Druntime.java=11
```

**Reproduces locally?**:
Yes 😲 

**Applicable branches**:
Master

**Failure history**:
Once or twice a day since 08/07/2020

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,class,stacktrace),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'SnapshotResiliencyTests%20testSnapshotWithNodeDisconnect'),sort:!(time,desc))

**Failure excerpt**:
```
java.lang.AssertionError: Condition wasn't fulfilled.
	at __randomizedtesting.SeedInfo.seed([AB11F5CEE90655C4:A5DE5A06F3C06E04]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.snapshots.SnapshotResiliencyTests.runUntil(SnapshotResiliencyTests.java:1163)
	at org.elasticsearch.snapshots.SnapshotResiliencyTests.verifyReposThenStopServices(SnapshotResiliencyTests.java:280)
```

'Condition wasn't fulfilled' <- you are such a disappointment

### PR DESCRIPTION
**Pull request by original-brownbear**
We were not handling the case where during a partial snapshot all
shards would enter a failed state right off the bat.

Closes #59384

Marking as non-issue since the bug wasn't released because it was caused by #56365.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -294,8 +294,8 @@ public ClusterState execute(ClusterState currentState) {
                 }
                 newEntry = new SnapshotsInProgress.Entry(
                         new Snapshot(repositoryName, snapshotId), request.includeGlobalState(), request.partial(),
-                        State.STARTED, indexIds, dataStreams, threadPool.absoluteTimeInMillis(), repositoryData.getGenId(), shards,
-                        null, userMeta, version);
+                        completed(shards.values()) ? State.SUCCESS : State.STARTED, indexIds, dataStreams,
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:297]: Also fixes yet another spot where we'd produce a snapshot with all shards in a final state but not a final state for the overall snapshot. I'll try to track down any remaining cases (I think this should've been the last one) if there are any and add an assertion to prevent this kind of bug going forward.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!
