### PR TITLE
Make setting index.translog.sync_interval be dynamic

### LINKED ISSUE #32763: Documentation claims "index.translog.sync_interval" is dynamic, but it can not be set dynamically
```json
{
    "error": {
        "root_cause": [
            {
                "type": "remote_transport_exception",
                "reason": "[fKNxi7c][10.0.0.155:9300][indices:admin/settings/update]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Can't update non dynamic settings [[index.translog.sync_interval]] for open indices ["
    },
    "status": 400
}
```

Tested on ES 6.3.2

https://www.elastic.co/guide/en/elasticsearch/reference/6.4/index-modules-translog.html

### PR DESCRIPTION
**Pull request by liketic**
Currently, we cannot update index setting ```index.translog.sync_interval``` if index is open, because it's not dynamic which can be updated for closed index only. 

Closes #32763

### CODE REVIEW

**Review by ywelsch — CHANGES_REQUESTED** [review]
This PR has the same flaw as the attempt in https://github.com/elastic/elasticsearch/pull/34104. Repeating my comment here:
While there's testing on the IndexSettings level, I don't think that the update logic actually takes effect on a live shard. The reason for this is that the fsyncTask (see IndexService) is currently only rescheduled when translog durability changes, not when the translog sync interval changes.

**Comment by liketic** [comment]
Thanks @ywelsch ! I pushed f5a6343a7695d36cc81627027378e0f3c3ee5ce2 , could you please review again ?

**Comment by ywelsch** [comment]
@elasticmachine test this please

File: server/src/main/java/org/elasticsearch/index/IndexService.java [hunk 1]
```diff
@@ -672,19 +673,27 @@ public boolean isForceExecution() {
                 rescheduleRefreshTasks();
             }
             final Translog.Durability durability = indexSettings.getTranslogDurability();
-            if (durability != oldTranslogDurability) {
+            final TimeValue syncInterval = indexSettings.getTranslogSyncInterval();
+            if (syncInterval.equals(oldSyncInterval) == false) {
+                rescheduleFsyncTask(() -> new AsyncTranslogFSync(IndexService.this));
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/IndexService.java]: What if both durability and sync interval are changed in the same update? This update here ignores the change to durability. In particular, if durability is SYNC, this will now suddenly schedule a sync task when the sync interval is changed even though there's no such sync task supposed to run due to durability SYNC.

It might be better to restructure the sync task scheduling code to not look at `oldTranslogDurability` but just at whether we have a current task and whether we're supposed to have one, and if we have both, check that the intervals match (you can get the current tasks interval directly from the task (see `refreshTask.getInterval()` as an example a few lines above it), and then just do  a plain `rescheduleFsyncTask` without parameters where it gets all it needs from the indexSettings (which have been updated).

**Review by ywelsch — CHANGES_REQUESTED** [review]
Thanks for the update @liketic. I think there's still a bug in this code, which means we should also look at beefing up the tests around setting both durability and the sync interval. I've added a comment to detail how to simplify the implementation. Let me know if you need more assistance on this.

File: server/src/main/java/org/elasticsearch/index/IndexService.java (hunk 1 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/IndexService.java]: How about the following:

```
diff --git a/server/src/main/java/org/elasticsearch/index/IndexService.java b/server/src/main/java/org/elasticsearch/index/IndexService.java
index 604d27a1e70..da95ef3eff2 100644
--- a/server/src/main/java/org/elasticsearch/index/IndexService.java
+++ b/server/src/main/java/org/elasticsearch/index/IndexService.java
@@ -197,7 +197,7 @@ public class IndexService extends AbstractIndexComponent implements IndicesClust
         this.refreshTask = new AsyncRefreshTask(this);
         this.trimTranslogTask = new AsyncTrimTranslogTask(this);
         this.globalCheckpointTask = new AsyncGlobalCheckpointTask(this);
-        rescheduleFsyncTask(indexSettings.getTranslogDurability());
+        updateFsyncTaskIfNecessary();
     }
 
     public int numberOfShards() {
@@ -636,8 +636,6 @@ public class IndexService extends AbstractIndexComponent implements IndicesClust
 
     @Override
     public synchronized void updateMetaData(final IndexMetaData currentIndexMetaData, final IndexMetaData newIndexMetaData) {
-        final Translog.Durability oldTranslogDurability = indexSettings.getTranslogDurability();
-
         final boolean updateIndexMetaData = indexSettings.updateIndexMetaData(newIndexMetaData);
 
         if (Assertions.ENABLED
@@ -689,20 +687,23 @@ public class IndexService extends AbstractIndexComponent implements IndicesClust
                 });
                 rescheduleRefreshTasks();
             }
-            final Translog.Durability durability = indexSettings.getTranslogDurability();
-            if (durability != oldTranslogDurability) {
-                rescheduleFsyncTask(durability);
-            }
+            updateFsyncTaskIfNecessary();
         }
     }
 
-    private void rescheduleFsyncTask(Translog.Durability durability) {
-        try {
-            if (fsyncTask != null) {
-                fsyncTask.close();
+    private void updateFsyncTaskIfNecessary() {
+        if (indexSettings.getTranslogDurability() == Translog.Durability.REQUEST) {
+            try {
+                if (fsyncTask != null) {
+                    fsyncTask.close();
+                }
+            } finally {
+                fsyncTask = null;
             }
-        } finally {
-            fsyncTask = durability == Translog.Durability.REQUEST ? null : new AsyncTranslogFSync(this);
+        } else if (fsyncTask == null) {
+            fsyncTask = new AsyncTranslogFSync(this);
+        } else {
+            fsyncTask.updateIfNeeded();
         }
     }
 
@@ -841,6 +842,13 @@ public class IndexService extends AbstractIndexComponent implements IndicesClust
             super(indexService, indexService.getIndexSettings().getTranslogSyncInterval());
         }
 
+        void updateIfNeeded() {
+            final TimeValue newInterval = indexService.getIndexSettings().getTranslogSyncInterval();
+            if (newInterval.equals(getInterval()) == false) {
+                setInterval(newInterval);
+            }
+        }
+
         @Override
         protected String getThreadPool() {
             return ThreadPool.Names.FLUSH;
```

**Comment by michaelbaamonde** [comment]
@liketic Are you still interested in moving this forward?

**Comment by liketic** [comment]
@michaelbaamonde Yes, will update soon.

**Comment by ywelsch** [comment]
ping @liketic

**Comment by liketic** [comment]
@ywelsch please review again.

**Review by ywelsch — APPROVED** [review]
LGTM. Thank you @liketic!

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Comment by ywelsch** [comment]
CI run failed for unrelated reasons:

> Could not determine the dependencies of task ':distribution:extractWindowsJdk'.
 [7.1.0] > Could not resolve all files for configuration ':distribution:jdk_windows'.
 [7.1.0]    > Could not download windows.zip (jdk:windows:12)
 [7.1.0]       > Could not get resource 'https://download.java.net/java/GA/jdk12/33/GPL/openjdk-12_windows-x64_bin.zip'.
 [7.1.0]          > Premature end of Content-Length delimited message body (expected: 196405895; received: 2097152
 [7.1.0] 

@elasticmachine retest this please

**Comment by ywelsch** [comment]
another unrelated test failure:

> ERROR   0.17s J2 | InternalEngineTests.testDeleteWithFatalError <<< FAILURES!
   > Throwable #1: java.io.IOException: could not remove the following files (in the order of attempts):
   >    /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/build/testrun/unitTest/J2/temp/org.elasticsearch.index.engine.InternalEngineTests_D5B77D5B191D2491-001/translog-primary-001/translog-2.tlog: java.io.IOException: access denied: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/build/testrun/unitTest/J2/temp/org.elasticsearch.index.engine.InternalEngineTests_D5B77D5B191D2491-001/translog-primary-001/translog-2.tlog
   >    /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/build/testrun/unitTest/J2/temp/org.elasticsearch.index.engine.InternalEngineTests_D5B77D5B191D2491-001/translog-primary-001/translog-1.tlog: java.io.IOException: access denied: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/build/testrun/unitTest/J2/temp/org.elasticsearch.index.engine.InternalEngineTests_D5B77D5B191D2491-001/translog-primary-001/translog-1.tlog
   >    /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/build/testrun/unitTest/J2/temp/org.elasticsearch.index.engine.InternalEngineTests_D5B77D5B191D2491-001/translog-primary-001: java.nio.file.DirectoryNotEmptyException: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/build/testrun/unitTest/J2/temp/org.elasticsearch.index.engine.InternalEngineTests_D5B77D5B191D2491-001/translog-primary-001
   > 	at __randomizedtesting.SeedInfo.seed([D5B77D5B191D2491:39307CC9B117DA9]:0)
   > 	at org.elasticsearch.core.internal.io.IOUtils.rm(IOUtils.java:196)
   > 	at org.elasticsearch.index.translog.Translog.createEmptyTranslog(Translog.java:1865)
   > 	at org.elasticsearch.index.translog.Translog.createEmptyTranslog(Translog.java:1860)
   > 	at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:511)
   > 	at org.elasticsearch.index.engine.InternalEngineTests.testDeleteWithFatalError(InternalEngineTests.java:3318)
   > 	at java.lang.Thread.run(Thread.java:748)

/cc: @dnhatn 

@elasticmachine run elasticsearch-ci/1
