### PR TITLE
Simplify and Speed up `ExecutorSelector`

### LINKED ISSUE #82450: Resolving the Executor for Write can be Unexpectedly Expensive in org.elasticsearch.indices.SystemIndices#findMatchingDescriptor
Found this in a user issue: `org.elasticsearch.indices.SystemIndices#findMatchingDescriptor` can become quite expensive in terms of runtime by running multiple regex in a loop on index names and for every replication action.

In case of running small numbers of documents per index the overhead can become non-trivial leading to hot-threads output as such:

```
 100.0% [cpu=0.4%, other=99.6%] (500ms out of 500ms) cpu usage by thread 'elasticsearch[es-data01][transport_worker][T#7]'
     unique snapshot
       java.base@17.0.1/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
       java.base@17.0.1/java.util.Collections$2.tryAdvance(Collections.java:4853)
       java.base@17.0.1/java.util.Collections$2.forEachRemaining(Collections.java:4861)
       java.base@17.0.1/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
       java.base@17.0.1/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
       java.base@17.0.1/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
       java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
       java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
       java.base@17.0.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
       java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
       java.base@17.0.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
       app//org.elasticsearch.indices.SystemIndices.findMatchingDescriptor(SystemIndices.java:263)
       app//org.elasticsearch.indices.ExecutorSelector.executorForWrite(ExecutorSelector.java:81)
       app//org.elasticsearch.indices.ExecutorSelector.getWriteExecutorForShard(ExecutorSelector.java:102)
       app//org.elasticsearch.action.bulk.TransportShardBulkAction$$Lambda$5102/0x00000008019b58e8.apply(Unknown Source)
       app//org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:192)
       app//org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:50)
       app//org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1153)
       app//org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:124)
       app//org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:508)
       app//org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:414)
       app//org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction$$Lambda$7183/0x0000000801dbaec0.accept(Unknown Source)
```

I think we should make sure that the overhead from resolving the executor becomes trivial by storing the executor for each index that has a special executor (i.e. is a system index?) in a map (or similar) so that we don't have to do the regex match on every update and just have an O(1) lookup here no matter how many features we have.
The map can just be updated whenever an index is created so we only have to pay the pattern matching cost once.
This also makes more sense than resolving the executor at runtime and then throwing if multiple executors match through an error in the features patterns.

### PR DESCRIPTION
**Pull request by original-brownbear**
This runs on the transport threads and was just needlessly high overhead
for large bulk requests that target many different indices.
This change should makes the method disappear from profiling.
For datastreams the duplicate checks are obviously unecessary
due to the way the map for those is build now.
For indices the existing checks for no-pattern-overlap should be
goo enough as well to allow for a tight loop without allocations.

closes #82450

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/SystemIndices.java [hunk 1]
```diff
@@ -270,75 +281,22 @@ public ExecutorSelector getExecutorSelector() {
      * @throws IllegalStateException if multiple descriptors match the name
```
Comment (gwbrown) [inline server/src/main/java/org/elasticsearch/indices/SystemIndices.java:281]: Nitpick: Can you remove the `@throws` since it no longer throws under any circumstance?

**Review by AthenaEryma — COMMENTED** [review]
LGTM, thanks for finding and fixing this!

**Review by AthenaEryma — APPROVED** [review]
Review the second, in which I remember to click "Approve".

**Comment by original-brownbear** [comment]
Thanks Gordon!
