### PR TITLE
[ML] ML stats failures should not stop the usage API working

### LINKED ISSUE #91893: .ml indices that are closed prevent Kibana monitoring from displaying.
### Elasticsearch Version

8.3.3, 8.4.3

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

.ml indices that are closed prevent Kibana monitoring from displaying. Using the GET _ml/anomaly_detectors/_stats endpoint:

```
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "index [.ml-anomalies-shared] blocked by: [FORBIDDEN/4/index closed];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "index [.ml-anomalies-shared] blocked by: [FORBIDDEN/4/index closed];"
  },
  "status": 403
}
```

### Steps to Reproduce

(Reproduced)

1. Started with the closed .ml indices. (In ESS) Run a plan to change Logging and Monitoring to send to itself (self-monitoring), not a dedicated monitoring cluster.
2. Plan change completed but the cluster's Stack Monitoring page would not render any data, it shows the message that you need to enable it in the console.
3. Opened the .ml* indices and the Stack Monitoring data is displayed.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by droberts195**
It is possible to meddle with internal ML state such that calls to the ML stats APIs return errors. It is justifiable for these single purpose APIs to return errors when the internal state of ML is corrupted. However, it is undesirable for these low level problems to completely prevent the overall usage API from returning, because then callers cannot find out usage information from any part of the system.

This change makes errors in the ML stats APIs non-fatal to the overall response of the usage API. When an ML stats APIs returns an error, the corresponding section of the ML usage information will be blank.

Fixes #91893

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearningUsageTransportAction.java [hunk 1]
```diff
@@ -137,45 +141,76 @@ protected void masterOperation(
...
                 client.execute(GetDatafeedsStatsAction.INSTANCE, datafeedStatsRequest, datafeedStatsListener);
-            }, listener::onFailure)),
-            listener::onFailure
+            }, e -> {
+                logger.warn("Failed to get job configs to include in ML usage", e);
+                client.execute(GetDatafeedsStatsAction.INSTANCE, datafeedStatsRequest, datafeedStatsListener);
+            })),
+            e -> {
+                logger.warn("Failed to get job stats to include in ML usage", e);
+                client.execute(GetDatafeedsStatsAction.INSTANCE, datafeedStatsRequest, datafeedStatsListener);
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearningUsageTransportAction.java:208]: This is difficult to read but are you intentionally skipping the call to get job configs if get job stats fails.

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearningUsageTransportAction.java:208]: Yes, because the `addJobsUsage` method requires both stats and configs, so if either fails then we can't call it.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM
