### PR TITLE
SQL: Fix querying of indices without columns

### LINKED ISSUE #53001: SQL: a query touching an empty index shouldn't return an error message
Following the change in https://github.com/elastic/elasticsearch/pull/52967, a `SELECT * FROM test` where `test` index doesn't have a mapping will return an error message. It should return no columns and no error message.

### PR DESCRIPTION
**Pull request by Luegg**
Fixes #53001

Adds support for querying indices without columns. Previously, such queries failed.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 1]
```diff
@@ -417,8 +417,9 @@ else if (plan instanceof OrderBy) {
             for (NamedExpression ne : projections) {
                 if (ne instanceof UnresolvedStar) {
                     List<NamedExpression> expanded = expandStar((UnresolvedStar) ne, output);
+
                     // the field exists, but cannot be expanded (no sub-fields)
-                    if (expanded.isEmpty()) {
+                    if (expanded == null) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:422]: why not keep the empty list vs a null?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 2]
```diff
@@ -455,6 +456,10 @@ else if (plan instanceof OrderBy) {
                 else if (q.resolved() == false) {
                     return singletonList(q);
                 }
+                // qualifier resolves to a non-struct field and cannot be expanded
+                else if (DataTypes.isPrimitive(q.dataType())) {
+                    return null;
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:461]: Use `emptyList()` instead of `null` - allows iteration without blowing up and it's still fast as it avoid any allocation.

**Review by costin — APPROVED** [review]
LGTM.
Left a comment on null vs emptyList. Small nit, the table name could be improve to `no_columns`, `no_mapping` or `empty_index`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:422]: That's more or less what caused the bug. Previously, expansion errors resulted in an empty list but that's ambiguous if the star is expanded on an index without columns. In this case, it returns an empty list meaning "star has been expanded to no fields".

To distinguish between expansion errors and empty expansions I now had to encode the error case with a `null` return value.

**Comment by Luegg** [comment]
> LGTM.
> Left a comment on null vs emptyList. Small nit, the table name could be improve to `no_columns`, `no_mapping` or `empty_index`.

I first used `empty_index` everywhere but then realized that this can mean either "empty mapping" or "no documents". Looking at the terminology in the docs, "empty_mapping" would probably be most accurate?

File: x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql [hunk 3]
```diff
@@ -0,0 +1,4 @@
+DROP TABLE IF EXISTS "no_cols";
+CREATE TABLE "no_cols" ();
+
+INSERT INTO "no_cols" DEFAULT VALUES;
```
Comment (matriv) [inline x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql:4]: Is this required?

File: x-pack/plugin/sql/qa/server/src/main/resources/no-columns.sql-spec [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+// awaits fix: https://github.com/elastic/elasticsearch/issues/74311
+// selectCountWithWhere
+// SELECT COUNT(*) FROM no_cols WHERE 1 + 1 = 3;
+
+selectConst
+SELECT 1, 2, 3 FROM no_cols;
+selectConstAggregation
+SELECT MAX(1), SUM(2) FROM no_cols;
+
+// fails in H2 but cannot be tested in CSV spec because datasets without columns cannot be parsed
```
Comment (matriv) [inline x-pack/plugin/sql/qa/server/src/main/resources/no-columns.sql-spec:19]: - Just curious, why does it fail in H2?
- Maybe you can open an issue to improve testing and have a way to assert no cols in csv in the feature and link it here.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java [hunk 5]
```diff
@@ -182,7 +182,9 @@ public QueryContainer(Query query,
      */
     public BitSet columnMask(List<Attribute> columns) {
         BitSet mask = new BitSet(fields.size());
-        aliasName(columns.get(0));
+        if(columns.size() > 0) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java:185]: nit: 
```suggestion
        if (columns.size() > 0) {
```

**Review by matriv — APPROVED** [review]
LGTM. Left a few comments though. Thx!

File: x-pack/plugin/sql/qa/server/src/main/resources/no-columns.csv-spec [hunk 6]
```diff
@@ -0,0 +1,23 @@
+selectConstAggregationWithGroupBy
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/no-columns.csv-spec:1]: they also behave differently in H2 and all return no rows. I'll add a comment to clarify this.

File: x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql (hunk 3 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql:4]: I also want to cover cases with empty documents indexed in the empty mapping index.

File: x-pack/plugin/sql/qa/server/src/main/resources/no-columns.sql-spec (hunk 4 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/no-columns.sql-spec:19]: H2 fails with a syntax error:
```
Syntax error in SQL statement "SELECT
FROM PUBLIC.""no_cols""[*]"; expected "(, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
CREATE FORCE VIEW PUBLIC._0 AS
SELECT
FROM PUBLIC."no_cols" [42001-197]
```
Looks like it uses a view to execute the subselect and the creation fails because it selects an empty list. The latest version of H2 supports the query though, so https://github.com/elastic/elasticsearch/issues/39895 would resolve the issue as well.

Comment (matriv) [reply x-pack/plugin/sql/qa/server/src/main/resources/no-columns.sql-spec]: Thx!

File: x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql (hunk 3 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql]: Yes that's true. Do you think it would be worth to also have an `empty_empty_mapping` index for covering the no rows cases? To some extent, the "no rows" cases are already covered by tests that filter out all records.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:422]: You could return `singletonList(ne)` instead of passing null and treat it separately.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:461]: I think you could simply return `singleton(q)` and avoid any special/null handling.

File: x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql (hunk 3 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/server/src/main/resources/setup_no_cols.sql]: I don't know if that's too much, @costin, what do you think?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java]: got it, makes sense 👍

**Review by bpintea — APPROVED** [review]
Nice. Lgtm.

**Review by astefan — COMMENTED** [review]
I've left few comments, all related to the same issue basically.

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/DataLoader.java [hunk 7]
```diff
@@ -74,6 +74,15 @@ protected static void loadEmpDatasetIntoEs(RestClient client) throws Exception {
...
         freeze(client, "frozen_emp");
+        loadNoColsDatasetIntoEs(client, "empty_mapping");
+    }
+
+    private static void loadNoColsDatasetIntoEs(RestClient client, String index) throws Exception {
+        createEmptyIndex(client, index);
+        Request request = new Request("POST", "/" + index + "/_bulk");
+        request.addParameter("refresh", "true");
+        request.setJsonEntity("{\"index\":{}\n{}\n" + "{\"index\":{}\n{}\n");
+        client.performRequest(request);
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/DataLoader.java:85]: I think it's helpful to also check whether the behavior is correct with documents in an index with an empty mapping. That's why I'm indexing two empty documents.

File: x-pack/plugin/sql/qa/server/src/main/resources/empty-mapping.csv-spec [hunk 8]
```diff
@@ -0,0 +1,28 @@
+
+// the following queries all return no rows in H2
+
+selectConstAggregationWithGroupBy
+SELECT 1 a, COUNT(*) b, MAX(1) c FROM empty_mapping GROUP BY a;
+
+       a:i     |       b:l     |       c:i
+---------------+---------------+---------------
+1              |2              |1
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/empty-mapping.csv-spec:9]: It's two empty docs in the index.

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/DataLoader.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/DataLoader.java:85]: Ok. Thanks.

File: x-pack/plugin/sql/qa/server/src/main/resources/empty-mapping.csv-spec (hunk 8 above)
[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/sql/qa/server/src/main/resources/empty-mapping.csv-spec:9]: Sorry, missed that.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/qa/server/src/main/resources/empty-mapping.csv-spec (hunk 8 above)
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/empty-mapping.csv-spec:9]: I also initially split the request body in two lines to make it more explicit like this:

```
request.setJsonEntity(
    "{\"index\":{}\n{}\n" +
    "{\"index\":{}\n{}\n");
```

but spotless didn't like it and I had to squash it into one line...

**Comment by joegallo** [comment]
```
$ git log --oneline upstream/master | grep "Fix querying of indices without columns"
6f93303c36f SQL: Fix querying of indices without columns (#74312)
$ git log --oneline upstream/7.x | grep "Fix querying of indices without columns"
2bb34e48605 SQL: Fix querying of indices without columns (#74312) (#74466)
$ git log --oneline upstream/7.14 | grep "Fix querying of indices without columns"
2bb34e48605 SQL: Fix querying of indices without columns (#74312) (#74466)
$ git log --oneline upstream/7.13 | grep "Fix querying of indices without columns"
ae96371d822 SQL: Fix querying of indices without columns (#74312) (#74465)
```
