### PR TITLE
CCR: Add TransportService closed to retryable errors

### LINKED ISSUE #34694: [CI] IndexFollowingIT test failures
The following tests fail:
* testFailOverOnFollower
* testFollowIndexAndCloseNode

```
IndexFollowingIT.testFailOverOnFollower <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <285L>
   >      but: was <125L>
   >    at __randomizedtesting.SeedInfo.seed([2BA269C25D3BF18F:F4F1C05EC95B52B5]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.ccr.IndexFollowingIT.lambda$assertSameDocCount$37(IndexFollowingIT.java:935)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=2BA269C25D3BF18F -Dtests.class=org.elasticsearch.xpack.ccr.IndexFollowingIT -Dtests.method="testDeleteLeaderIndex" -Dtests.security.manager=true -Dtests.locale=en-MS -Dtests.timezone=Asia/Dili -Dcompiler.java=11 -Druntime.java=11
   >    at org.elasticsearch.xpack.ccr.IndexFollowingIT.assertSameDocCount(IndexFollowingIT.java:930)
   >    at org.elasticsearch.xpack.ccr.IndexFollowingIT.testFailOverOnFollower(IndexFollowingIT.java:666)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
   >    Suppressed: java.lang.AssertionError: 
```

```
IndexFollowingIT.testFollowIndexAndCloseNode <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <1374L>
   >      but: was <1031L>
   >    at __randomizedtesting.SeedInfo.seed([6E852E371598B0D3:33A48218C2DD362C]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.ccr.IndexFollowingIT.lambda$assertSameDocCount$37(IndexFollowingIT.java:936)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
   >    at org.elasticsearch.xpack.ccr.IndexFollowingIT.assertSameDocCount(IndexFollowingIT.java:931)
   >    at org.elasticsearch.xpack.ccr.IndexFollowingIT.testFollowIndexAndCloseNode(IndexFollowingIT.java:315)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.AssertionError: 
```

These test failures do not reproduce and I've not been able to spot a reason in the logs why these tests would fail.

Build urls:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/31/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/11/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/37/console

### PR DESCRIPTION
**Pull request by dnhatn**
Both testFollowIndexAndCloseNode and testFailOverOnFollower failed
because they responded to the FollowTask a TransportService closed
exception which is currently considered as a fatal error. This behavior
is not desirable since a closing node can throw that exception, and we
should retry in this case.

This change adds TransportService closed error to the list of retryable
errors.

Closes #34694

This approach is quite ugly - I am open to suggestions.

### CODE REVIEW

**Comment by dnhatn** [comment]
[CI failed](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/581/) because we hit IndexNotFoundException (not retryable) when a node is being closed.

```
1> [2018-10-22T22:40:25,275][WARN ][o.e.x.c.a.ShardFollowNodeTask] [follower0] shard follow task encounter non-retryable error
  1> org.elasticsearch.index.IndexNotFoundException: no such index
  1> 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:182) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
```

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java [hunk 1]
```diff
@@ -387,6 +390,14 @@ static boolean shouldRetry(Exception e) {
...
         } else if (NetworkExceptionHelper.isCloseConnectionException(e)) {
             return true;
+        } else {
+            final TransportException transportError = (TransportException) ExceptionsHelper.unwrap(e.getCause(), TransportException.class);
+            if (transportError != null) {
+                if (transportError instanceof NodeNotConnectedException ||
+                    (transportError.getMessage() != null && transportError.getMessage().contains("TransportService is closed"))) {
+                    return true;
+                }
+            }
```
Comment (martijnvg) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: I think if you add this below then that will work too and it is shorter:

```
(actual instanceof NodeNotConnectedException && actual.getMessage().contains("TransportService is closed"))
```

**Review by martijnvg — COMMENTED** [review]
> CI failed because we hit IndexNotFoundException (not retryable) when a node is being closed.

It looks like it failed because of `NodeDisconnectedException` instead:

```
1> [2018-10-22T22:40:29,638][INFO ][o.e.t.InternalTestCluster] [testFollowIndexAndCloseNode] Closing random non master node [follower0] current master [follower1] 
  1> [2018-10-22T22:40:29,645][INFO ][o.e.n.Node               ] [testFollowIndexAndCloseNode] stopping ...
  1> [2018-10-22T22:40:29,671][WARN ][o.e.x.c.a.ShardFollowNodeTask] [follower0] shard follow task encounter non-retryable error
  1> org.elasticsearch.transport.NodeDisconnectedException: [leaderm0][127.0.0.1:40071][indices:data/read/xpack/ccr/shard_changes] disconnected
  1> [2018-10-22T22:40:29,662][WARN ][o.e.x.c.a.ShardFollowNodeTask] [follower1] shard follow task encounter non-retryable error
  1> org.elasticsearch.transport.RemoteTransportException: [follower0][127.0.0.1:45630][indices:data/write/bulk_shard_operations[s]]
  1> Caused by: org.elasticsearch.transport.SendRequestTransportException: [follower0][127.0.0.1:39049][indices:data/write/bulk_shard_operations[s][p]]
  1>    at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:670) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
  1>    at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:573) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
  1>    at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:561) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
  1>    at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.performAction(TransportReplicationAction.java:813) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
```

The `IndexNotFoundException` happens in the `testDeleteFollowerIndex()` test.

I think we should also retry when `NodeDisconnectedException` occurs?

**Comment by dnhatn** [comment]
Thanks @martijnvg for looking into the failure. I've addressed your comment. Could you please have another look?

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java [hunk 2]
```diff
@@ -397,7 +400,10 @@ static boolean shouldRetry(Exception e) {
             actual instanceof AlreadyClosedException ||
             actual instanceof ElasticsearchSecurityException || // If user does not have sufficient privileges
             actual instanceof ClusterBlockException || // If leader index is closed or no elected master
-            actual instanceof IndexClosedException; // If follow index is closed
+            actual instanceof IndexClosedException || // If follow index is closed
+
+            actual instanceof NodeDisconnectedException || actual instanceof NodeNotConnectedException ||
```
Comment (martijnvg) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: add `actual instanceof NodeNotConnectedException ||` on a newline?

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java [hunk 3]
```diff
@@ -369,6 +371,7 @@ private void handleFailure(Exception e, AtomicInteger retryCounter, Runnable tas
             scheduler.accept(TimeValue.timeValueMillis(delay), task);
         } else {
             fatalException = ExceptionsHelper.convertToElastic(e);
+            LOGGER.warn("shard follow task encounter non-retryable error", e);
```
Comment (martijnvg) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: 👍

**Review by martijnvg — APPROVED** [review]
I left one commit. LGTM

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java (hunk 3 above)
Comment (dnhatn) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: @martijnvg Should we also mark the follow-task as failed in this case?

Comment (dnhatn) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: Good point.

**Comment by dnhatn** [comment]
Thanks @martijnvg for reviewing.
