### PR TITLE
Invoke initial AsyncActionStep for newly created indices

### LINKED ISSUE #77269: ILM policies with searchable_snapshot and allocate in the cold phase will get stuck
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.1

**Description of the problem including expected versus actual behavior**:

If an ILM policy uses both `searchable_snapshot` and `allocate` in the cold phase, then the `allocate` action won't work right, and in fact will get wedged permanently (see workaround below for how to unstick it).

**Steps to reproduce**:

```
PUT _cluster/settings
{
  "transient": {
    "indices.lifecycle.poll_interval": "30s"
  }
}

PUT _ilm/policy/test-policy
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0m",
        "actions": {
          "set_priority": {
            "priority": 100
          }
        }
      },
      "warm": {
        "min_age": "2m",
        "actions": {
          "set_priority": {
            "priority": 50
          }
        }
      },
      "cold": {
        "min_age": "4m",
        "actions": {
          "set_priority": {
            "priority": 100
          },
          "searchable_snapshot": {
            "snapshot_repository": "found-snapshots"
          },
          "allocate": {
            "number_of_replicas": 0
          }
        }
      },
      "frozen": {
        "min_age": "6m",
        "actions": {
          "searchable_snapshot": {
            "snapshot_repository": "found-snapshots"
          }
        }
      }
    }
  }
}

PUT _template/test-template
{
  "index_patterns": ["test-index*"],
  "settings": {
    "lifecycle": {
      "name": "test-policy"
    },
    "number_of_shards": 1,
    "number_of_replicas": 1
  }
}

POST test-index-1/_doc
{
  "field1": "someValue2"
}
```

Once the policy gets to the `allocate` action & step, it'll just sit there forever:

```
GET test-index-1/_ilm/explain
{
  "indices" : {
    "restored-test-index-1" : {
      "index" : "restored-test-index-1",
      "managed" : true,
      "policy" : "test-policy",
      "lifecycle_date_millis" : 1630689049418,
      "age" : "6.5m",
      "phase" : "cold",
      "phase_time_millis" : 1630689317926,
      "action" : "allocate",
      "action_time_millis" : 1630689318037,
      "step" : "allocate",
      "step_time_millis" : 1630689379467,
      "repository_name" : "found-snapshots",
      "snapshot_name" : "2021.09.03-test-index-1-test-policy-vx9cjvout8q3ahibxej20g",
      "phase_execution" : {
        "policy" : "test-policy",
        "phase_definition" : {
          "min_age" : "4m",
          "actions" : {
            "allocate" : {
              "number_of_replicas" : 0,
              "include" : { },
              "exclude" : { },
              "require" : { }
            },
            "searchable_snapshot" : {
              "snapshot_repository" : "found-snapshots",
              "force_merge_index" : true
            },
            "set_priority" : {
              "priority" : 100
            }
          }
        },
        "version" : 4,
        "modified_date_in_millis" : 1630689027809
      }
    }
  }
}
```

**Workaround**:

For any stuck indices, if you manually move the stuck index to complete, then everything will pick back up.

```
POST /_ilm/move/restored-test-index-1
{
  "current_step": {
    "phase": "cold",
    "action": "allocate",
    "name": "allocate"
  },
  "next_step": {
    "phase": "cold",
    "action": "complete",
    "name": "complete"
  }
}
```

### PR DESCRIPTION
**Pull request by dakrone**
Some ILM actions can create indices, and these indices start on a step that is an `AsyncActionStep`.
Because of the way that we prevent AsyncActionSteps from being invoked more than once, they can
accidentally end up never continuing their execution until a new master node is elected.

This commit adds a method to the `ClusterStateActionStep` that returns an index name and `StepKey`
so that the `CopyExecutionStateStep` step can tell `ExecuteStepsUpdateTask` that async actions
should be invoked for an index *other* than the initially passed in index. This allows situations
where steps that create new indices having an async action as their first step to continue
execution (the observed case is when the `allocate` action is combined with `searchable_snapshot` in
the `cold` phase).

Resolves #77269

### CODE REVIEW

**Comment by dakrone** [comment]
There are probably other ways to solve this particular problem, this is just the easiest one I could think of for an initial stab at fixing it.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/ExecuteStepsUpdateTask.java [hunk 1]
```diff
@@ -34,6 +39,7 @@
     private final PolicyStepsRegistry policyStepsRegistry;
     private final IndexLifecycleRunner lifecycleRunner;
     private final LongSupplier nowSupplier;
+    private final Map<String, Step.StepKey> indexToStepKeysForAsyncActions;
```
Comment (andreidan) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/ExecuteStepsUpdateTask.java:42]: I think this generally looks good, thanks for fixing this tricky one Lee! 

I'm only a bit worried for this being a `Map`. Namely, I'm still mulling over the implications of this not maintaining order and the fact that it can contain multiple indices. 

Multiple, consecutive `ClusterStateAction` steps could add to this `Map`. We don't have this situation **yet** but I'd like to think about what it would mean if we did. 

Would for now be ok to add an assertion that the size of this Map is `1` in `onClusterStateProcessed`?

Comment (DaveCTurner) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/ExecuteStepsUpdateTask.java:42]: This is I think a side-effect of the use of `LegacyClusterTaskResultActionListener` in `IndexLifecycleRunner#ILM_TASK_EXECUTOR`. When that's addressed we will be able to pass data directly from the `doExecute()` method to the publish handler rather than relying on mutable fields on each task (that's exactly why https://github.com/elastic/elasticsearch/issues/83784 exists).

Comment (dakrone) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/ExecuteStepsUpdateTask.java:42]: > Multiple, consecutive ClusterStateAction steps could add to this Map. We don't have this situation yet but I'd like to think about what it would mean if we did.

This is part of why I used a map rather than a single `Tuple`. We don't have that situation now, but it would be handled in the event that we do in the future.

> Would for now be ok to add an assertion that the size of this Map is 1 in onClusterStateProcessed?

I don't think we need to enforce order here, as each index would be independent from the others, so I'm not sure whether we need to enforce it to always be 1? (Even though right now it's always going to be one, this will handle > 1 indices correctly)

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Lee

**Comment by dakrone** [comment]
@elasticmachine update branch
