### PR TITLE
Fix TranslogTests testDisabledFsync

### LINKED ISSUE #108321: [CI] TranslogTests testDisabledFsync failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/jdtfindbkrryw/tests/:server:test/org.elasticsearch.index.translog.TranslogTests/testDisabledFsync

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.translog.TranslogTests.testDisabledFsync" -Dtests.seed=5010F3511D07D12B -Dtests.locale=ar-EG -Dtests.timezone=Indian/Antananarivo -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.index.translog.TranslogTests#testDisabledFsync`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDisabledFsync'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.index.translog.TranslogTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.io.IOException: could not remove the following files (in the order of attempts):
   /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002/translog.ckp: java.io.IOException: access denied: /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002/translog.ckp
   /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002/translog-2.tlog: java.io.IOException: access denied: /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002/translog-2.tlog
   /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002/translog-1.tlog: java.io.IOException: access denied: /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002/translog-1.tlog
   /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002: java.nio.file.DirectoryNotEmptyException: /dev/shm/bk/bk-agent-prod-gcp-1715004739279441559/elastic/elasticsearch-intake/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_5010F3511D07D12B-001/tempDir-002

  at __randomizedtesting.SeedInfo.seed([5010F3511D07D12B:158E31C8F1CA5886]:0)
  at org.elasticsearch.core.IOUtils.rm(IOUtils.java:203)
  at org.elasticsearch.index.translog.Translog.createEmptyTranslog(Translog.java:1901)
  at org.elasticsearch.index.translog.Translog.createEmptyTranslog(Translog.java:1873)
  at org.elasticsearch.index.translog.Translog.createEmptyTranslog(Translog.java:1863)
  at org.elasticsearch.index.translog.TranslogTests.testDisabledFsync(TranslogTests.java:4014)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by idegtiarenko**
The test used to reuse a translogDir directory that has nother translog created in it. I believe the other one locked files and prevented them from being deleted.

Closes: #108321

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 1]
```diff
@@ -4000,8 +4000,8 @@ static boolean hasCircularReference(Exception cause) {
         return false;
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/108321")
     public void testDisabledFsync() throws IOException {
+        var translogDir = createTempDir();
```
Comment (ywangd) [inline server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java:4004]: Is this the right fix? In `setUp`, we also have `translogDir = createTempDir()` so it should be pretty unique for each test method? If we think the directory might be reused, maybe we should remove the directory in `tearDown`?

Comment (idegtiarenko) [reply server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java:4004]: It is,

setups create a translogDirectory and creates an empty translog in it:
https://github.com/elastic/elasticsearch/blob/a0dcca2f5d00664f1e0d1bb73bb3a7ce9079f8ed/server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java#L243-L249

then the test was creating another one in the same directory
https://github.com/elastic/elasticsearch/blob/a0dcca2f5d00664f1e0d1bb73bb3a7ce9079f8ed/server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java#L4005-L4020

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java (hunk 1 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java:4004]: OK thanks for explaining.

**Review by ywangd — APPROVED** [review]
LGTM

File: server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java (hunk 1 above)
Comment (arteam) [inline server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java:4004]: It would be nice for this variable to have a different name, otherwise it shadows the `translogDir` field.
