### PR TITLE
Fix StatementParserTests

### LINKED ISSUE #129887: [CI] StatementParserTests class failing
**Build Scans:**
- [elasticsearch-periodic #8925 / release-tests](https://gradle-enterprise.elastic.co/s/ec3jzaucb5rha)
- [elasticsearch-periodic #8919 / release-tests](https://gradle-enterprise.elastic.co/s/4x5r64cjwvyj4)
- [elasticsearch-pull-request #76859 / part-3](https://gradle-enterprise.elastic.co/s/xx25iz6idq2im)
- [elasticsearch-pull-request #76740 / part-3](https://gradle-enterprise.elastic.co/s/6bjzwtdjn4hwc)
- [elasticsearch-pull-request #76676 / part-3](https://gradle-enterprise.elastic.co/s/kzbvy6kb5elz2)
- [elasticsearch-pull-request #76375 / part-3](https://gradle-enterprise.elastic.co/s/4crxchigpgatq)
- [elasticsearch-pull-request #76252 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/ehj4igjmyllqw)
- [elasticsearch-periodic-platform-support #8832 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/pez5ke33pm3fm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.parser.StatementParserTests.testPreserveParanthesis" -Dtests.seed=20EC2EB8ED7AB65B -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=lmo-Latn-IT -Dtests.timezone=Europe/Budapest -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.parser.StatementParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.esql.parser.StatementParserTests),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Query [explain] is expected to throw class org.elasticsearch.xpack.esql.parser.ParsingException with message [line 1:8: mismatched input '<EOF>' expecting '(']
Expected: a string containing "line 1:8: mismatched input '<EOF>' expecting '('"
     but: was "line 1:1: mismatched input 'explain' expecting {, 'row', 'from', 'show'}"
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 8 failures in class org.elasticsearch.xpack.esql.parser.StatementParserTests (0.8% fail rate in 989 executions)
- [main] 2 failures in step release-tests (28.6% fail rate in 7 executions)
- [main] 4 failures in step part-3 (1.0% fail rate in 399 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (10.5% fail rate in 19 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (1.3% fail rate in 397 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by idegtiarenko**
This change fixes StatementParserTests.testPreserveParanthesis as it now depends on capability enabled only on snapshot builds

Closes: #129887
Related to: #129526

### CODE REVIEW

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 1]
```diff
@@ -961,14 +961,12 @@ public void testBasicSortCommand() {
     }
 
     public void testSubquery() {
-        assertEquals(new Explain(EMPTY, PROCESSING_CMD_INPUT), statement("explain ( row a = 1 )"));
-    }
-
-    public void testSubqueryWithPipe() {
+        assumeTrue("Requires EXPLAIN capability", EsqlCapabilities.Cap.EXPLAIN.isEnabled());
         assertEquals(new Explain(EMPTY, PROCESSING_CMD_INPUT), statement("explain ( row a = 1 )"));
     }
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:966]: testSubquery and testSubqueryWithPipe are identical now. I am keeping only one of them.

**Review by luigidellaquila — APPROVED** [review]
Thanks @idegtiarenko, LGTM
