### PR TITLE
Bug Fix: System Data Streams Should Be Restorable

### LINKED ISSUE #89261: `.fleet-actions-results` data stream cannot be restored via the `fleet` feature state
### Elasticsearch Version

8.3.3

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Deployment in ESS

### Problem Description

`.fleet-actions-results` data stream cannot be restored via the `fleet` feature state.

Consider the following scenario (observed in the field in ESS):

1) Due to unforeseen situation, cluster becomes red with the following red indices:

```
health status index                                                                                                                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size sth
green  open   .ds-.fleet-actions-results-2022.05.04-000002                                                                                    eZO3mXu3RYOZpygHvC2dgQ   1   1          0            0       450b           225b false
red    open   .ds-.fleet-actions-results-2022.06.03-000003                                                                                    iBbSWmHaQbqJFn_aBVqaYg   1   1                                                   false
red    open   .ds-.fleet-actions-results-2022.07.03-000004                                                                                    sF3-S4uoQkybpm7ujaZBVg   1   1                                                   false
red    open   .ds-.fleet-actions-results-2022.08.02-000006                                                                                    t-U-Wrd_RpqZUqSS2a3TqA   1   1                                                   false
red    open   .fleet-actions-7                                                                                                                8zgOKVzdQIeS_YGq_JX--w   1   1                                                   false
red    open   .fleet-agents-7                                                                                                                 p7sWhvhPRaWQ_unOHIJQTQ   1   1                                                   false
red    open   .fleet-artifacts-7                                                                                                              iingfeghRJ2bfqLAGFt0Aw   1   1                                                   false
red    open   .fleet-enrollment-api-keys-7                                                                                                    8J1tyEuJSfyhMxf5HsfU2A   1   1                                                   false
red    open   .fleet-policies-7                                                                                                               HufDBhgBQraUYlNosY1ysg   1   1                                                   false
red    open   .fleet-policies-leader-7                                                                                                        jpqhCaF9SL-S0AjlWqa6xg   1   1                                                   false
red    open   .fleet-servers-7                                                                                                                5xdgNy-kSXSdsWZbM8mRHw   1   1                                                   false
```

2) User attempts to restore the `fleet` feature state using the following restore snapshot API:

```
POST _snapshot/found-snapshots/cloud-snapshot-2022.08.08-lywsv4teqe-zj3ygvjkria/_restore?wait_for_completion=false
{
  "indices": "-*",
  "ignore_unavailable": "true",
  "include_global_state": "false",
  "include_aliases": "false",
  "feature_states": [
   "fleet"
  ]
}
```

3) Above API fails with the following error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "snapshot_restore_exception",
        "reason": "[found-snapshots:cloud-snapshot-2022.08.08-lywsv4teqe-zj3ygvjkria/H3i28HlrSiKyrLaiDCE6uA] cannot restore index [.ds-.fleet-actions-results-2022.06.03-000003] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"
      }
    ],
    "type": "snapshot_restore_exception",
    "reason": "[found-snapshots:cloud-snapshot-2022.08.08-lywsv4teqe-zj3ygvjkria/H3i28HlrSiKyrLaiDCE6uA] cannot restore index [.ds-.fleet-actions-results-2022.06.03-000003] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name"
  },
  "status": 500
}
```

4) Checking the `fleet` feature state, it seems that the `SystemIndexDescriptor` (c.f [code](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/fleet/src/main/java/org/elasticsearch/xpack/fleet/Fleet.java#L149)) does contain the `.fleet-actions-results-*` pattern. A couple of guesses about the reported problem:
- The implementation only considers regular indices and not data streams?
- The implementation considers the data stream but fails to close the backing indices before restoring them?

### Steps to Reproduce

1. Create a cluster version 8.3.3 and deploy an Elastic Agent with the Osquery Manager integration.
2. Run a new live Osquery.
3. Observe that the `.fleet-actions-results` data stream is created with the respective backing indices.
4. Restore the `fleet` feature state using the restore snapshot API and observe the same error as above.

### Workaround

1. Create `fleet_superuser` role

```
POST _security/role/fleet_superuser
{
  "indices": [
    {
      "names": [
        ".fleet*"
      ],
      "privileges": [
        "all"
      ],
      "allow_restricted_indices": true
    }
  ]
}
```

2.  Create `temp_user` user with `superuser`, `fleet_superuser` roles:
```
POST _security/user/temp_user
{
  "password": "temp_password",
  "roles": [
    "superuser",
    "fleet_superuser"
  ]
}
```

3) Close `.fleet-actions-results` backing indices using the below cURL command:
```
curl -k -XPOST --user temp_user:temp_password -H 'x-elastic-product-origin:fleet' https://$CLUSTER_ADDRESS/.ds-.fleet-actions-results-2022.05.04-000002,.ds-.fleet-actions-results-2022.06.03-000003,.ds-.fleet-actions-results-2022.07.03-000004,.ds-.fleet-actions-results-2022.08.02-000006/_close
```

Note: for users running the cURL command on Windows, make sure to use double quotes instead for the header: `"x-elastic-product-origin:fleet"`

4) Restore fleet feature state:

```
POST _snapshot/found-snapshots/cloud-snapshot-2022.08.08-lywsv4teqe-zj3ygvjkria/_restore?wait_for_completion=false
{
  "indices": "-*",
  "ignore_unavailable": "true",
  "include_global_state": "false",
  "include_aliases": "false",
  "feature_states": [
    "fleet"
  ]
}
```

5) Delete `temp_user` user
```
DELETE _security/user/temp_user
```

6) Delete `fleet_superuser` role
```
DELETE _security/role/fleet_superuser
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by JVerwolf**
This PR deletes system data streams prior to a `restore` operation.  To enable this, I refactored the way that datastreams are deleted to allow for a single metadata update operation that both deletes existing system datastreams and then restores them as part of a single operation.

closes https://github.com/elastic/elasticsearch/issues/89261

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    /**
+     * Removes the given data streams from the Cluster State.
+     *
+     * @param clusterState The cluster state
+     * @param dataStreams  The data streams to remove
+     * @param settings     The settings
+     * @return The updated Cluster State
+     */
+    @FixForMultiProject // Once callers have Project State we can update/remove this method.
+    public static ClusterState deleteDataStreams(ClusterState clusterState, Set<DataStream> dataStreams, Settings settings) {
```
Comment (JVerwolf) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java:40]: (before any comments come in) This is clearly busted.  Fixing.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java [hunk 2]
```diff
@@ -608,6 +711,69 @@ public void testSystemIndexAliasesAreAlwaysRestored() {
 
     }
 
+    // TODO: This test is failing because the assertion `assertTrue(indexExists(systemDataStreamAlias));` trips.
+    @AwaitsFix(bugUrl = "assertTrue(indexExists(systemDataStreamAlias)); is broken")
```
Comment (JVerwolf) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java:715]: This test is failing because the alias isn't restored. I'm supposing this is a bug, and not expected behaviour for system datastreams?

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+import org.elasticsearch.index.Index;
+import org.elasticsearch.logging.LogManager;
+import org.elasticsearch.logging.Logger;
+
+import java.util.HashMap;
+import java.util.HashSet;
+import java.util.Map;
+import java.util.Set;
+
+public class MetadataDeleteDataStreamService {
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java:25]: Could these methods be on the existing MetadataDataStreamService?

**Review by rjernst — COMMENTED** [review]
A few minor initial comments. I suggest someone from data management review.

File: docs/changelog/124651.yaml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+pr: 124651
+summary: "System Data Streams Should Be Restorable"
```
Comment (dakrone) [inline docs/changelog/124651.yaml:2]: Since these go into changelogs, this should be an active sentence. Something like "Fix system data streams to be restorable from a snapshot"

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java [hunk 5]
```diff
@@ -510,6 +610,7 @@ public void testRestoreSystemIndicesAsGlobalStateWithNoFeatureStates() {
      *
      * However, other feature states should be unaffected.
      */
+    // TODO: determine if we can create a datastream test for this
```
Comment (JVerwolf) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java:613]: @alexey-ivanov-es , do you know if a similar test can be written for datastreams? e.g. do datastreams follow a dimilar pattern with matchin descriptors?  (I can also dig into this, but wondering if you know offhand since you've recently worked in this area)

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java (hunk 2 above)
Comment (dakrone) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java:715]: Data stream aliases are similar to index aliases, where they are metadata on the data stream itself. I would expect restoring a data stream (system or otherwise) to also restore the alias for that data stream.

I tested that with a non-system data stream, the alias is restored when the data stream is restored, so I would treat this as a bug.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+
+    private static final Logger LOGGER = LogManager.getLogger(MetadataDeleteDataStreamService.class);
+
+    /**
+     * Removes the given data streams from the Cluster State.
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java:30]:
```suggestion
     * Removes the given data streams and their backing indices from the Cluster State.
```

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+        }
+
+        for (final Map.Entry<ProjectId, Set<DataStream>> entry : byProject.entrySet()) {
+            clusterState = deleteDataStream(clusterState.projectState(entry.getKey()), entry.getValue(), settings);
+        }
+        return clusterState;
+    }
+
+    /**
+     * Removes the given data streams from the Project State.
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteDataStreamService.java:52]:
```suggestion
     * Removes the given data streams and their backing indices from the Project State.
```

**Review by dakrone — COMMENTED** [review]
I left a couple of comments from the Data Management side, but nothing major. I agree with Ryan about trying to combine with `MetadataDataStreamsService` instead of adding a new service if possible.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java (hunk 5 above)
Comment (alexey-ivanov-es) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java:613]: System data streams themselves don't have a name pattern - just a name, so it is not possible to have another data stream in the same pattern

File: docs/changelog/124651.yaml (hunk 4 above)
Comment (JVerwolf) [reply docs/changelog/124651.yaml]: Good point, thanks!

**Review by nielsbauman — COMMENTED** [review]
Thanks for working on this, John! It's looking good to me, I just left a few comments, mostly related to MP changes.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java [hunk 8]
```diff
@@ -432,6 +442,71 @@ private static IndexAbstraction validateIndex(ProjectMetadata project, String in
...
+    /**
+     * Removes the given data streams and their backing indices from the Cluster State.
+     *
+     * @param clusterState The cluster state
+     * @param dataStreams  The data streams to remove
+     * @param settings     The settings
+     * @return The updated Cluster State
+     */
+    @FixForMultiProject // Once callers have Project State we can update/remove this method.
+    public static ClusterState deleteDataStreams(ClusterState clusterState, Set<DataStream> dataStreams, Settings settings) {
```
[the remark this answers is not in the document]
Comment (JVerwolf) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java:454]: Thanks @nielsbauman .  Since I'm still developing familiarity with the new multiproject code, is this the way I should be getting the project state at the call site? : 
```
currentState.projectState(currentState.metadata().getProject().id())
``` 
It seems convoluted, but I don't see another way to do it...

File: modules/data-streams/src/main/java/org/elasticsearch/datastreams/action/DeleteDataStreamTransportAction.java [hunk 9]
```diff
@@ -164,25 +163,11 @@ static ClusterState removeDataStream(
             );
```
[the remark this answers is not in the document]
Comment (JVerwolf) [reply modules/data-streams/src/main/java/org/elasticsearch/datastreams/action/DeleteDataStreamTransportAction.java]: Nice catch!

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java [hunk 10]
```diff
@@ -466,6 +478,51 @@ public void testUpdateDataStreamOptions() {
...
+                System.currentTimeMillis(),
+                (long) randomIntBetween(0, 1000),
+                Map.of(),
+                null,
+                SnapshotInfoTestUtils.randomUserMetadata(),
+                IndexVersionUtils.randomVersion()
+            )
+        );
+        final DataStream dataStream = DataStreamTestHelper.randomInstance(dataStreamName);
+        ClusterState state = ClusterState.builder(clusterState(dataStream)).putCustom(SnapshotsInProgress.TYPE, snaps).build();
```
[the remark this answers is not in the document]
Comment (JVerwolf) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java]: Ah, I should have read further down in the comments,I just spent some time figuring out how to do this after resolving your comment to remove the overloaded method!

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (nielsbauman) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java]: You can just call [`currentState.projectState()`](https://github.com/elastic/elasticsearch/blob/1bee2cc3ccbcb3bc917b9e88d91c69dfbe26ab02/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L536-L542). That basically does the same thing as you wrote, but less convoluted :)

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (nielsbauman) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java]: Ah sorry about that, I assumed my comments would be read in the order I added them. I should have linked or referred to my other comment...

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java [hunk 11]
```diff
@@ -466,6 +479,56 @@ public void testUpdateDataStreamOptions() {
         assertThat(updatedDataStream.getDataStreamOptions(), equalTo(DataStreamOptions.EMPTY));
     }
 
+    public void testDeleteMissing() {
+        DataStream dataStream = DataStreamTestHelper.randomInstance();
+        ProjectState state = ClusterState.builder(ClusterName.DEFAULT).build().projectState(randomProjectIdOrDefault());
```
Comment (nielsbauman) [inline server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java:484]: Since we're not adding a project to the cluster state and cluster states by default only have the `default` project, creating/extracting a project state with a random project ID is going to fail (about 50% of the time). The most correct way of doing it would be
```java
final var projectId = randomProjectIdOrDefault();
ProjectState state = ClusterState.builder(ClusterName.Default)
    .putProjectMetadata(ProjectMetadata.builder(projectId))
    .projectState(projectId);
```
That ensures the requested project is always present (but it can still be the default project).

Comment (JVerwolf) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java]: Thanks @nielsbauman .  I had to modify slightly:
```java
        ProjectState state = ClusterState.builder(ClusterName.DEFAULT)
            .putProjectMetadata(ProjectMetadata.builder(projectId))
            .build()
            .projectState(projectId);
```
I also changed the MetadataDataStreamsService#deleteDataStreams to throw a `ResourceNotFoundException` if the datastream doesn't exist. (the prior exception was thrown by the `projectFor` code that has since been removed.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java (hunk 2 above)
Comment (JVerwolf) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java]: Thanks @dakrone , I found the bug, fixed it, and enabled the test.

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java
[the remark this answers is not in the document]
Comment (JVerwolf) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java:1]: Perhaps this is something we can do in a follow up PR? Ideally we'd have it in this one, but I'm not sure I'll have time to refactor all the testing before the RC cut.  I'll see what I can do.

 For now, our test coverage is still the same (transitively via the [DeleteDataStreamTransportActionTests.java](https://github.com/elastic/elasticsearch/blob/9cbb26247bad7ee50b3dcbea4ee64ed5deb14409/modules/data-streams/src/test/java/org/elasticsearch/datastreams/action/DeleteDataStreamTransportActionTests.java#L40-L40) tests).  I agree we should eventually move any coverage we can to this class as well.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java [hunk 12]
```diff
@@ -432,6 +440,52 @@ private static IndexAbstraction validateIndex(ProjectMetadata project, String in
...
+        // (this to avoid data stream validation from failing when deleting an index that is part of a data stream
+        // without updating the data stream)
+        // TODO: change order when "delete index api" also updates the data stream the "index to be removed" is a member of
+        ClusterState newState = projectState.updatedState(builder -> {
+            for (DataStream ds : dataStreams) {
+                LOGGER.info("removing data stream [{}]", ds.getName());
+                builder.removeDataStream(ds.getName());
+                if (projectState.metadata().dataStreams().get(ds.getName()) == null) {
+                    throw new ResourceNotFoundException("data stream [" + ds.getName() + "] not found");
+                }
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java:483]: I think it would make more sense if we do this check in the loop where were constructing `backingIndicesToRemove`. Then we can exit early before building a new cluster state if a data stream doesn't exist. What do you think?

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemResourceSnapshotIT.java [hunk 13]
```diff
@@ -691,6 +898,7 @@ public void testNoneFeatureStateOnCreation() {
         assertThat(snapshottedIndices, allOf(hasItem(regularIndex), not(hasItem(SystemIndexTestPlugin.SYSTEM_INDEX_NAME))));
     }
 
+    // TODO, Do we need to test this for Datastreams?
```
[the remark this answers is not in the document]
Comment (JVerwolf) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemResourceSnapshotIT.java:899]: I'm not sure how we'd even test this.  Any ideas?

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 14]
```diff
@@ -650,19 +652,21 @@ private static Tuple<Map<String, DataStream>, Map<String, DataStreamAlias>> getD
...
                         "omitting system data stream [{}] from snapshot restoration because its feature state was not requested",
                         requestedDataStream
                     );
                 }
             }
-            if (includeAliases) {
+            if (includeAliases || systemDataStreams.isEmpty() == false) {
                 dataStreamAliases = new HashMap<>();
                 final Map<String, DataStreamAlias> dataStreamAliasesInSnapshot = globalMetadata.getProject().dataStreamAliases();
+                Map<String, DataStream> dataStreamsWithAliases = includeAliases ? systemDataStreams : allDataStreams;
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:667]: Wouldn't this need to be inverted? So `includeAliases ? allDataStreams : systemDataStreams`?

Might also be worth adding a small comment to explain why we're doing that.

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java
[the remark this answers is not in the document]
Comment (nielsbauman) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsServiceTests.java:1]: I assumed it would be pretty straightforward to move the methods, but I definitely don't want to let this get in the way of you making your deadline, so a follow-up PR is fine with me :+1:.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemResourceSnapshotIT.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (dakrone) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemResourceSnapshotIT.java:899]: A partial snapshot would be one where some of the shards were snapshotted and others weren't. If we take a snapshot with `partial: true` while the index is red (say it had two primaries and one were unavailable) that would cause a partial snapshot.

It would probably be good to test this as well, since we test it for regular system indices.

[the remark this answers is not in the document]
Comment (JVerwolf) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemResourceSnapshotIT.java:901]: Thanks @dakrone .  Fixed.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java [hunk 15]
```diff
@@ -432,6 +440,52 @@ private static IndexAbstraction validateIndex(ProjectMetadata project, String in
...
+                throw new ResourceNotFoundException("data stream [" + dataStream.getName() + "] not found");
+            }
+            backingIndicesToRemove.addAll(dataStream.getIndices());
+            backingIndicesToRemove.addAll(dataStream.getFailureIndices());
+        }
+
+        // first delete the data streams and then the indices:
+        // (this to avoid data stream validation from failing when deleting an index that is part of a data stream
+        // without updating the data stream)
+        // TODO: change order when "delete index api" also updates the data stream the "index to be removed" is a member of
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java:479]: I don't understand this TODO entirely, why would we want to change the order when invoked by the delete index API?

Comment (JVerwolf) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDataStreamsService.java:479]: Me neither, but it was already there in the transport action so I kept it. It was originally added by Marijn.

**Review by nielsbauman — APPROVED** [review]
LGTM, thanks a lot for the iterations, @JVerwolf!

**Comment by JVerwolf** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/124900)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/124910)|
|❌|8.18|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 124651
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by JVerwolf** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/124912)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by JVerwolf** [comment]
Curiously, the backports are all failing the `SystemResourceSnapshotTests` (previously `SystemIndexSnapshotTests`) when the whole test class is run, but they all succeed when run individually. In a debugger, I see missing features that should have been added by the plugins.  Seems like a test framework bug.  Does anyone here have intuition about what might have changed on <9.1 versions?
