### PR TITLE
Flatten Get Snapshots Response

### LINKED ISSUE #43462: GetSnapshotsResponse should re-wrap failed exceptions so callsites are visible in the stacktrace
From the following code:

https://github.com/elastic/elasticsearch/blob/f879e84e5a536c921f463465557297f994c54e3e/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java#L156-L166

It's possible for snapshot exceptions to be generated on a different line than where they are actually thrown, for example, code that prior to https://github.com/elastic/elasticsearch/pull/42090 worked like this:

```java
GetSnapshotsRequest getSnapshotsRequest = new GetSnapshotsRequest(new String[]{repo}, new String[]{snapshotName});
final GetSnapshotsResponse snaps;
try {
    snaps = client.snapshot().get(getSnapshotsRequest, RequestOptions.DEFAULT);
} catch (Exception e) {
    if (e.getMessage().contains("snapshot_missing_exception")) {
        fail("snapshot does not exist: " + snapshotName);
    }
    throw e;
}

Optional<SnapshotInfo> info = snaps.getSnapshots(repo).stream().findFirst();
if (info.isPresent()) {
    info.ifPresent(si -> {
        assertThat(si.snapshotId().getName(), equalTo(snapshotName));
        assertThat(si.state(), equalTo(SnapshotState.SUCCESS));
    });
} else {
    fail("unable to find snapshot; " + snapshotName);
}
```

Now fails. 

The exception is generated from the `snaps.getSnapshots(repo)` call above, *however*, the stacktrace for the exception actually traces back to the line

```java
    snaps = client.snapshot().get(getSnapshotsRequest, RequestOptions.DEFAULT);
```

which is very confusing, because that line itself is wrapped in a try/catch.

`GetSnapshotsResponse` should change this line:

https://github.com/elastic/elasticsearch/blob/f879e84e5a536c921f463465557297f994c54e3e/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java#L165

Into something like

```java
throw new ElasticsearchException(error);
```

So that the stacktrace correctly identifies the caller.

### LINKED ISSUE #69108: Support v7 response format for get-snapshots API
In #42090 we changed the response format for the get-snapshots action in 8.0. When the work to support versioned response formats lands, we should revisit this breaking change and make sure we continue to return the older format if requested.

### PR DESCRIPTION
**Pull request by original-brownbear**
This PR returns the get snapshots API to the 7.x format (and transport client behavior) and enhances it for requests that ask for multiple repositories.
The changes for requests that target multiple repositories are:
* Add `repository` field to `SnapshotInfo` and REST response
* Add `failures` map alongside `snapshots` list instead of returning just an exception response as done for single repo requests
* Pagination now works across repositories instead of being per repository for multi-repository requests

closes #69108
closes #43462

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/docs (git ssh timeout)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java [hunk 1]
```diff
@@ -700,8 +720,14 @@ public XContentBuilder toXContent(final XContentBuilder builder, final Params pa
         final boolean verbose = params.paramAsBoolean("verbose", GetSnapshotsRequest.DEFAULT_VERBOSE_MODE);
         // write snapshot info for the API and any other situations
         builder.startObject();
+        final SnapshotId snapshotId = snapshot.getSnapshotId();
         builder.field(SNAPSHOT, snapshotId.getName());
         builder.field(UUID, snapshotId.getUUID());
+
+        if (params.paramAsBoolean("include_repository", true)) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:727]: I suppose we could also leave this and related code out and just always return the repository name in responses. That would simplify code a little and adding the field seems fine even in `7.x`. We've added other fields like `metadata` in the past without user complaints or other issues. I put the flag in here for now as this is what we discussed yesterday though.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 2]
```diff
@@ -135,16 +140,23 @@ private void getMultipleReposSnapshotInfo(
...
+                final List<SnapshotInfo> allSnapshots = responses.stream()
+                    .map(Tuple::v2)
+                    .filter(Objects::nonNull)
+                    .flatMap(Collection::stream)
+                    .collect(Collectors.toUnmodifiableList());
+                final Map<String, ElasticsearchException> failures = responses.stream()
+                    .map(Tuple::v1)
+                    .filter(Objects::nonNull)
+                    .collect(Collectors.toMap(Tuple::v1, Tuple::v2));
+                return new GetSnapshotsResponse(sortSnapshots(allSnapshots, sortBy, after, size, order), failures);
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:158]: There's obviously more efficient ways to implement this than just paginating each repo and then merging/sorting as done here. In the interest of time and given that this is just a temporary solution I figured this was good enough though.

**Comment by original-brownbear** [comment]
@henningandersen @tlrx this should finally be good for review now. Sorry this took so long, adjusting all the tests affected turned out to be more involved than expected (though on the bright side, this aligns the 7.x and master code for them again :)). 
Also, admittedly this PR could have been polished a little more but with how little time is left on this work and how follow-ups will redo the way `SnapshotInfo` is serialized in the repo and how pagination works under the hood, I tried to find a good compromise here. Let me know what you think :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2

**Comment by pgomulka** [comment]
this also fixes the rest compat tests for `snapshot.get` 
```
./gradlew ':rest-api-spec:yamlRestCompatTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {yaml=snapshot.get/*}"
```
Can we also enable them in `rest-api-spec/build.gradle` ? (just need to remove them from blacklist)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java [hunk 3]
```diff
@@ -700,8 +720,14 @@ public XContentBuilder toXContent(final XContentBuilder builder, final Params pa
...
+            builder.field(REPOSITORY, snapshot.getRepository());
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:728]: I don't see YAML REST tests for this new field - maybe add at least one?

**Review by tlrx — COMMENTED** [review]
I made some comments but nothing to worry about. I think it deserve a review from Henning because I'm not sure I followed all discussions on this topic

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java [hunk 4]
```diff
@@ -171,59 +96,56 @@ public boolean isFailed() {
...
-            builder.field("repository", snapshots.getKey());
-            builder.startArray("snapshots");
-            for (SnapshotInfo snapshot : snapshots.getValue()) {
-                snapshot.toXContent(builder, params);
+    public void writeTo(StreamOutput out) throws IOException {
+        if (out.getVersion().onOrAfter(GetSnapshotsRequest.MULTIPLE_REPOSITORIES_SUPPORT_ADDED)) {
+            out.writeMap(failedResponses, StreamOutput::writeString, StreamOutput::writeException);
+        } else {
+            if (failedResponses.isEmpty() == false) {
+                throw failedResponses.values().iterator().next();
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java:104]: Hmm now that you mention it, I think this is actually dead code now with the changes I made. We would always just straight throw the exception in the transport action when communicating with an old version node and never get here because the old version node would only request snapshots for a single repo. Let me see what I can do about this :)

File: server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestGetSnapshotsAction.java [hunk 5]
```diff
@@ -73,6 +80,20 @@ public RestChannelConsumer prepareRequest(final RestRequest request, final NodeC
...
         getSnapshotsRequest.masterNodeTimeout(request.paramAsTime("master_timeout", getSnapshotsRequest.masterNodeTimeout()));
         return channel -> new RestCancellableNodeClient(client, request.getHttpChannel()).admin().cluster()
-                .getSnapshots(getSnapshotsRequest, new RestToXContentListener<>(channel));
+                .getSnapshots(getSnapshotsRequest, new RestToXContentListener<>(channel) {
+                    @Override
+                    public RestResponse buildResponse(GetSnapshotsResponse response, XContentBuilder builder) throws Exception {
+                        final ToXContent.Params params;
+                        if (getSnapshotsRequest.isSingleRepositoryRequest()) {
+                            final Map<String, String> updatedParams = new HashMap<>(request.params());
+                            updatedParams.put("include_repository", "false");
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestGetSnapshotsAction.java:89]: My thinking as well at this point. Lets see if @henningandersen agrees, then we can just delete this here and in the create snapshot action :)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:730]: ++ let's see what we come down on in terms of how this parameter is going to behave. If we just enable it by default even for single repo requests then we can  (and have to in case of docs tests) just add it to existing tests. If we don't want it on by default, then I'll add a new test with multiple repo requests that check for this field :)

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsRequest.java [hunk 6]
```diff
@@ -176,6 +177,13 @@ public GetSnapshotsRequest repositories(String... repositories) {
         return this.repositories;
     }
 
+    public boolean isSingleRepositoryRequest() {
+        return repositories.length == 1
+            && repositories[0].equals("_all") == false
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsRequest.java]: ++ added that check

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java:105]: I added an assertion for this in https://github.com/elastic/elasticsearch/pull/74451/commits/fc027a47ef0518301e2a4801989755b0b2d390fd#diff-0f20d081deb6b8f13072b3c96acaee24ba6877e5ac31c867830ec17d65956facR104 and kept the code as it was since I think it's dead code anyways as far as I can see, but just to be safe in case I'm missing something I kept the existing logic around.

**Comment by original-brownbear** [comment]
Thanks @tlrx addressed all points I think :)

Also, thanks @pgomulka I reenabled those tests and they're green on my local as well :)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:729]: Also +1 on adding the field by default (and adapting existing YAML tests).

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java [hunk 7]
```diff
@@ -171,59 +96,57 @@ public boolean isFailed() {
...
+            snapshotInfo.toXContent(builder, params);
         }
-
         builder.endArray();
+        if (failedResponses.isEmpty() == false) {
+            builder.startObject("failures");
+            for (Map.Entry<String, ElasticsearchException> error : failedResponses.entrySet()) {
+                builder.field(error.getKey(), (b, pa) -> {
+                    b.startObject();
+                    error.getValue().toXContent(b, pa);
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java:124]: Looks like we go from detailed (`ElasticsearchException.generateFailureXContent`) to some other form of exception output. I did not dig into the difference, but if you did, perhaps you can summarize it here?

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java [hunk 8]
```diff
@@ -160,12 +172,12 @@ private void getMultipleReposSnapshotInfo(
                 size,
                 order,
                 groupedActionListener.delegateResponse((groupedListener, e) -> {
-                    if (e instanceof ElasticsearchException) {
-                        groupedListener.onResponse(GetSnapshotsResponse.Response.error(repoName, (ElasticsearchException) e));
+                    if (isMultiRepoRequest && e instanceof ElasticsearchException) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:175]: I think this way of error handling is new compared to elsewhere. I wonder if you considered one of following options:

* Respond with a failure if all repos failed (which would be the same as here in the single repo case). This is sort of similar to search.
* Breakingly never respond failures, expect users to look into the `failures` map.
* Have an option to fail the request or send back failures in response.

Do we have other similar cases in ES we can lean on in order to decide?

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:729]: One exception though is when it is the unknown repo name, we do not want to output that.

**Review by henningandersen — COMMENTED** [review]
I have only been through the non-test file changes for now. Mainly one comment needs attention: error handling.

File: docs/reference/snapshot-restore/monitor-snapshot-restore.asciidoc [hunk 9]
```diff
@@ -31,6 +31,8 @@ PUT /_snapshot/my_fs_backup
 }
 
 PUT /_snapshot/my_backup/snapshot_1?wait_for_completion=true
+
+PUT /_snapshot/my_backup/some_other_snapshot?wait_for_completion=true
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply docs/reference/snapshot-restore/monitor-snapshot-restore.asciidoc:35]: Since we moved back to 7.x error handling for single repo requests, this would fail now instead of return a `200` with errors in the response map. In fact this line is included in the 7.x version of this file (I assume for that very reason) and this nicely aligns the versions ago :)

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java (hunk 7 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java:124]: As far as I can see `generateFailureXContent` is more geared towards requests for multiple shards with it's `guessRootCauses` that would render a `root_cause` field which does not apply to our use case. Other than that it's the same format via `generateThrowableXContent` except that it's put at another level of nesting into an `error:` field which seems unnecessary for our use case of having a map by repo name.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java (hunk 8 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:175]: > Respond with a failure if all repos failed (which would be the same as here in the single repo case). This is sort of similar to search.

That seems more complicated to work with than having the failures map? My thinking was to have the same behavior for all requests that target multiple repos. I'm somewhat indifferent here, making it look like search is nice, but in isolation I like this approach better I think.

> Breakingly never respond failures, expect users to look into the failures map.

This is quite annoying to users perhaps (note that in 7.x we also have to think about the transport client behavior that would be changed by this). It may also be a troubling breaking change for Cloud? I'd rather not do this I think.

> Have an option to fail the request or send back failures in response.

I don't think we have that kind of behavior anywhere else? Not sure it's worth the complexity for a very small number of use cases?

> Do we have other similar cases in ES we can lean on in order to decide?

None come to mind for me that are similar enough but that doesn't mean there aren't any. I think I was in large part driven by not breaking the transport client API for users and cloud orchestration. In both cases changing the behavior for a single repo request seems risky?

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java [hunk 10]
```diff
@@ -13,147 +13,72 @@
...
-            throw new IllegalArgumentException("No such repository");
+    public GetSnapshotsResponse(StreamInput in) throws IOException {
+        if (in.getVersion().onOrAfter(GetSnapshotsRequest.MULTIPLE_REPOSITORIES_SUPPORT_ADDED)) {
+            final Map<String, ElasticsearchException> failedResponses = in.readMap(StreamInput::readString, StreamInput::readException);
+            this.failedResponses = Collections.unmodifiableMap(failedResponses);
+        } else {
+            this.failedResponses = Collections.emptyMap();
         }
-        throw error;
+        this.snapshots = in.readList(SnapshotInfo::readFrom);
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java]: yea that looks nicer, done :)

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java [hunk 11]
```diff
@@ -13,147 +13,72 @@
...
-
-        private static Response fromXContent(XContentParser parser) throws IOException {
-            return RESPONSE_PARSER.parse(parser, null);
-        }
     }
 
-    private final Map<String, List<SnapshotInfo>> successfulResponses;
+    private final List<SnapshotInfo> snapshots;
+
     private final Map<String, ElasticsearchException> failedResponses;
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsResponse.java]: ++ done

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java]: ++ added that check

**Comment by original-brownbear** [comment]
Thanks @henningandersen all points addressed now I think :)

**Review by henningandersen — COMMENTED** [review]
A few minor comments on the tests

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java (hunk 8 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java:175]: We discussed this on another channel with following conclusion:

1. We will merge this PR as is.
2. We will follow-up with a PR to add the option to fail-fast or not, regardless of multi/single repo in regular breaking change style. The default in 7 will be fail fast, default in 8 will be always put it in array. Flag to be removed in 9.

**Review by henningandersen — APPROVED** [review]
LGTM

**Review by tlrx — APPROVED** [review]
LGTM 2

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java [hunk 12]
```diff
@@ -128,14 +130,8 @@ public void testFullPolicySnapshot() throws Exception {
                 snapshotResponseMap = XContentHelper.convertToMap(XContentType.JSON.xContent(), is, true);
             }
             assertThat(snapshotResponseMap.size(), greaterThan(0));
-            List<Map<String, Object>> snapResponse = ((List<Map<String, Object>>) snapshotResponseMap.get("responses")).stream()
-                .peek(m -> logger.info("--> responses: {}", m))
-                .map(m -> (List<Map<String, Object>>) m.get("snapshots"))
-                .peek(allReposSnapshots -> logger.info("--> all repository's snapshots: {}", allReposSnapshots))
-                .filter(allReposSnapshots -> allReposSnapshots.stream().anyMatch(repoHasSnapshot))
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java:135]: ++ removed it and checked the snapshot name prefix manually below

File: client/rest-high-level/src/test/java/org/elasticsearch/client/SnapshotIT.java [hunk 13]
```diff
@@ -209,14 +211,15 @@ public void testGetSnapshots() throws IOException {
...
+            response.getSnapshots().stream().map(SnapshotInfo::repository).collect(Collectors.toSet())
+        );
 
-        assertThat(response.getSnapshots(repository2), hasSize(1));
-        assertThat(response.getSnapshots(repository2).get(0).snapshotId().getName(), equalTo(snapshot2));
-        assertThat(response.getSnapshots(repository2).get(0).userMetadata(), equalTo(originalMetadata));
+        assertThat(response.getSnapshots(), hasSize(2));
+        assertThat(response.getSnapshots().get(0).snapshotId().getName(), equalTo(snapshot1));
+        assertThat(response.getSnapshots().get(1).snapshotId().getName(), equalTo(snapshot2));
+        assertThat(response.getSnapshots().get(1).userMetadata(), equalTo(originalMetadata));
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/SnapshotIT.java:223]: Yes definitely, added that assertion :)

**Comment by original-brownbear** [comment]
Thanks so much Henning + Tanguy!
