### PR TITLE
Increase disruption test publish timeout to 5s

### LINKED ISSUE #51329: [CI] Test failure: ConcurrentSeqNoVersioningIT » testSeqNoCASLinearizability
`ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability` failed in the following build:
 https://gradle-enterprise.elastic.co/s/tngp7hvapc5c6/console-log

I wasn't able to reproduce this failure locally.

Reproduce line:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability" -Dtests.seed=2657E8F9B4C405BC -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=America/Toronto -Dcompiler.java=13
```

### PR DESCRIPTION
**Pull request by henningandersen**
With the new mechanism for storing cluster state in lucene, we store
index metadata in multiple data paths too. This causes cluster state
publish to timeout too frequently with a 1s timeout, so increasing it to
5s.

Closes #51329

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/discovery/AbstractDisruptionTestCase.java [hunk 1]
```diff
@@ -128,7 +128,7 @@ protected void beforeIndexDeletion() throws Exception {
             .put(FollowersChecker.FOLLOWER_CHECK_TIMEOUT_SETTING.getKey(), "1s") // for hitting simulated network failures quickly
             .put(FollowersChecker.FOLLOWER_CHECK_RETRY_COUNT_SETTING.getKey(), 1) // for hitting simulated network failures quickly
             .put(JoinHelper.JOIN_TIMEOUT_SETTING.getKey(), "10s") // still long to induce failures but to long so test won't time out
-            .put(Coordinator.PUBLISH_TIMEOUT_SETTING.getKey(), "1s") // <-- for hitting simulated network failures quickly
+            .put(Coordinator.PUBLISH_TIMEOUT_SETTING.getKey(), "5s") // <-- for hitting simulated network failures quickly
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/discovery/AbstractDisruptionTestCase.java]: I think we should do the same for the follower check, which is also racing publication and can depend on writing out state. For full symmetry, perhaps also for leader check.

Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/discovery/AbstractDisruptionTestCase.java]: Fixed here 3163f62c1587691013261b086d76ec4a9cc85e2c

**Review by ywelsch — APPROVED** [review]
LGTM
