### PR TITLE
Use a copy of the SearchExecutionContext for each Percolator execution

### LINKED ISSUE #141489: NoSuchElementException in NestedScope.previousLevel() during percolate query execution with nested queries
### Elasticsearch Version

8.19.6

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Ubuntu 24.04 (using the official elastic docker image)

## Description
After upgrading from Elasticsearch 7.17.5 to 8.19.6, percolate queries
intermittently fail with a NoSuchElementException when attempting to pop from
an empty stack in NestedScope.previousLevel(). The error occurs during query
phase execution when processing percolate queries that contain nested queries.

## Observed Behavior
- Intermittent failures: Not all percolate queries fail, suggesting specific
  query patterns trigger the bug
- Shard-specific: Failures occur on specific shards, likely those containing
  problematic percolate query patterns
- Query pattern: Percolate queries with nested queries within bool clauses
  appear to be affected

## Additional Notes
- This issue did NOT occur in Elasticsearch 7.17.5
- We're using the 7.x client with compatibility mode enabled.

### Steps to Reproduce

While I haven't isolated a minimal reproduction case yet, the issue seems to be
triggered by:

1. Creating an index with nested field mappings
2. Storing percolate queries that include:
   - Nested queries referencing the nested paths
   - Multiple bool query clauses at different nesting levels
   - Mix of must/should/filter clauses containing nested queries
3. Executing a percolate query with documents matching these stored queries

Reproducing is proving difficult due to the intermittent nature of this bug. I can follow-up with further steps if I can narrow it down to a particular document shape and query. That being said, in order to surface the error, I am executing the exact same percolation requests (documents are not changing between requests) and stored percolate queries are remaining the same as well, however, the response is _occasionally_  partial. Could this be a bug related to parallel query execution?

Our documents contain multiple nested fields (ie various nested paths), each nested fields may have more than 200 nested documents, index is spread across 10 shards, we are using the 7.x ruby client with compatibility mode enabled (we are in the middle of an upgrade to 8.x)

## Stacktrace
```
org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.query.QueryPhase.addCollectorsAndSearch(QueryPhase.java:237)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.query.QueryPhase.executeQuery(QueryPhase.java:143)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:70)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:652)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:824)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$6(SearchService.java:688)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:79)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:76)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.util.NoSuchElementException
	at java.base/java.util.LinkedList.removeFirst(LinkedList.java:282)
	at java.base/java.util.LinkedList.pop(LinkedList.java:813)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.support.NestedScope.previousLevel(NestedScope.java:45)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.NestedQueryBuilder.toQuery(NestedQueryBuilder.java:318)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.NestedQueryBuilder.doToQuery(NestedQueryBuilder.java:271)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:119)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:325)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:308)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:119)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:325)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:307)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:119)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:325)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:308)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:119)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:325)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:305)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:119)
	at org.elasticsearch.percolator@8.19.6/org.elasticsearch.percolator.PercolateQueryBuilder.lambda$createStore$9(PercolateQueryBuilder.java:613)
	at org.elasticsearch.percolator@8.19.6/org.elasticsearch.percolator.PercolateQuery$1$2.matchDocId(PercolateQuery.java:170)
	at org.elasticsearch.percolator@8.19.6/org.elasticsearch.percolator.PercolateQuery$BaseScorer$1.matches(PercolateQuery.java:283)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.ConjunctionDISI$ConjunctionTwoPhaseIterator.matches(ConjunctionDISI.java:346)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:295)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:236)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:46)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.BulkScorer.score(BulkScorer.java:43)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:447)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:736)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:374)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.internal.ContextIndexSearcher.lambda$search$3(ContextIndexSearcher.java:352)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.TaskExecutor$TaskGroup$1.run(TaskExecutor.java:120)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.TaskExecutor$TaskGroup.invokeAll(TaskExecutor.java:176)
	at org.apache.lucene.core@9.12.2/org.apache.lucene.search.TaskExecutor.invokeAll(TaskExecutor.java:84)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:356)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:323)
	at org.elasticsearch.server@8.19.6/org.elasticsearch.search.query.QueryPhase.addCollectorsAndSearch(QueryPhase.java:212)
	... 15 more
```

### PR DESCRIPTION
**Pull request by davidkyle**
The `AutoPrefilteringScope` member of `SearchExecutionContext` is not thread safe but Percolate accesses the member from multiple threads resulting in the stack trace below. `SearchExecutionContext::NestedScope` can also be used in non-thread safe manner in Percolator query. 

This PR adds a `copyForConcurrentUse()` to `SearchExecutionContext` which creates a shallow copy of the context with new instances of the mutable members. These members are no longer shared between the threads removing the concurrent access issues.  

```
Caused by: java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:282) ~[?:?]
	at java.util.LinkedList.pop(LinkedList.java:813) ~[?:?]
	at org.elasticsearch.index.query.support.AutoPrefilteringScope.pop(AutoPrefilteringScope.java:47) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.elasticsearch.index.query.support.AutoPrefilteringScope.close(AutoPrefilteringScope.java:59) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:333) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:303) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:119) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.elasticsearch.percolator.PercolateQueryBuilder.lambda$createStore$9(PercolateQueryBuilder.java:577) ~[main/:?]
	at org.elasticsearch.percolator.PercolateQuery$1$1$1.matchDocId(PercolateQuery.java:138) ~[main/:?]
	at org.elasticsearch.percolator.PercolateQuery$BaseScorer$1.matches(PercolateQuery.java:301) ~[main/:?]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreTwoPhaseIterator(Weight.java:311) ~[lucene-core-10.3.2.jar:10.3.2 dadfd90b4401947f4d0387669dc94999fbb2c830 - 2025-11-13 10:41:29]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:282) ~[lucene-core-10.3.2.jar:10.3.2 dadfd90b4401947f4d0387669dc94999fbb2c830 - 2025-11-13 10:41:29]
	at org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:483) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:809) ~[lucene-core-10.3.2.jar:10.3.2 dadfd90b4401947f4d0387669dc94999fbb2c830 - 2025-11-13 10:41:29]
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:407) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at org.elasticsearch.search.internal.ContextIndexSearcher.lambda$search$3(ContextIndexSearcher.java:385) ~[elasticsearch-9.4.0-SNAPSHOT.jar:9.4.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:328) ~[?:?]
	at org.apache.lucene.search.TaskExecutor$Task.run(TaskExecutor.java:173) ~[lucene-core-10.3.2.jar:10.3.2 dadfd90b4401947f4d0387669dc94999fbb2c830 - 2025-11-13 10:41:29]
	at org.apache.lucene.search.TaskExecutor.lambda$invokeAll$1(TaskExecutor.java:98) ~[lucene-core-10.3.2.jar:10.3.2 dadfd90b4401947f4d0387669dc94999fbb2c830 - 2025-11-13 10:41:29]
```

Closes #141489

### CODE REVIEW

File: modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java [hunk 1]
```diff
@@ -572,8 +574,25 @@ static PercolateQuery.QueryStore createStore(MappedFieldType queryBuilderFieldTy
...
 
-                    queryBuilder = Rewriteable.rewrite(queryBuilder, context);
-                    return queryBuilder.toQuery(context);
+                    // The QueryBuilder.toQuery() function modifies the search context's
+                    // AutoPrefilteringScope in a way that is not thread safe. For other
+                    // queries this is not a problem, but Percolate will call the returned
+                    // PercolateQuery.QueryStore function from multiple threads. Here the
+                    // solution is to create an AutoPrefilteringScope for each invocation
+                    // of PercolateQuery.QueryStore
+                    var safeContext = new FilteredSearchExecutionContext(context) {
```
Comment (benwtrent) [inline modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: I am not sure that Percolator should be reading/writing from the auto-prefiltering scope at all. 

I really dislike that this was just added for all boolean queries, when its only needed in very specific cases for knn searches.

**Review by benwtrent — COMMENTED** [review]
@dimitris-athanasiou @Mikep86 

y'all might find this interesting.

File: modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java (hunk 1 above)
Comment (benwtrent) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: I think this `autoPrefilteringScope` should be null and not available at all unless the very specific query asks for it. Otherwise we end up with weird latent bugs for code paths that aren't actually necessary or expected.

Comment (Mikep86) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: @benwtrent `autoPrefilteringScope` uses the same design pattern as `nestedScope`, which is one of the reasons we went with it. This leads to an immediate follow-up question: Are there similar potential issues with nested percolated queries?

Comment (Mikep86) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: Indeed, this issue seems to happen with `nestedScope` as well: https://github.com/elastic/elasticsearch/issues/141489

I've been trying to reproduce this with percolated nested queries locally, but haven't had much luck yet. Such is the nature of concurrency bugs :/

Comment (davidkyle) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: I added a `copyForConcurrentUse()` method to SearchExecutionContext that addresses both the AutoPrefilteringScope  and NestedScope issues.

Comment (davidkyle) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: > I really dislike that this was just added for all boolean queries, when its only needed in very specific cases for knn searches.

I explored walking the query tree to find a knn query and only enabling auto pre-filtering if present and ended up with logic not dissimilar to this https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/query/support/AutoPrefilteringUtils.java#L45

There doesn't seem to be a _blessed_ way to walk the query tree as getting the child queries for each query type has to be handled differently. It feels out of scope for this bug fix, we can explore the best way to handle this in another PR possibly by adding a `List<QueryBuilder> subQueries()` function to `QueryBuilder`

File: modules/percolator/src/test/java/org/elasticsearch/percolator/QueryBuilderStoreTests.java [hunk 2]
```diff
@@ -84,18 +90,53 @@ public void testStoringQueryBuilders() throws IOException {
                 }
             }
 
-            SearchExecutionContext searchExecutionContext = mock(SearchExecutionContext.class);
```
Comment (davidkyle) [inline modules/percolator/src/test/java/org/elasticsearch/percolator/QueryBuilderStoreTests.java:87]: The test could use a mock anymore as it is passed to the FilteredSearchExecutionContext constructor

File: modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java (hunk 1 above)
Comment (Mikep86) [reply modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: ++ for exploring other ways to walk the query tree in a separate PR. I think this one should focus only on making `SearchExecutionContext` usable by percolator.

File: modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java [hunk 3]
```diff
@@ -572,8 +572,17 @@ static PercolateQuery.QueryStore createStore(MappedFieldType queryBuilderFieldTy
...
-                    queryBuilder = Rewriteable.rewrite(queryBuilder, context);
-                    return queryBuilder.toQuery(context);
+                    // The QueryBuilder.toQuery() function modifies the search context's
+                    // AutoPrefilteringScope in a way that is not thread safe. For other
+                    // queries this is not a problem, but Percolate will call the returned
+                    // PercolateQuery.QueryStore function from multiple threads.
+                    // The context's NestedScope is also vulnerable to concurrent modification.
+                    // Use a cloned SearchExecutionContext for each thread with new instances of
+                    // the mutable fields.
+                    var safeContext = context.copyForConcurrentUse();
```
Comment (davidkyle) [inline modules/percolator/src/main/java/org/elasticsearch/percolator/PercolateQueryBuilder.java]: The context here is actually a FilteredSearchExecutionContext create at https://github.com/elastic/elasticsearch/blob/main/modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java#L581

File: server/src/main/java/org/elasticsearch/index/query/FilteredSearchExecutionContext.java [hunk 4]
```diff
@@ -390,4 +391,17 @@ public void setRewriteToNamedQueries() {
...
+        return in.autoPrefilteringScope();
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    @Override
+    public FilteredSearchExecutionContext copyForConcurrentUse() {
+        return new FilteredSearchExecutionContext(this);
+    }
```
Comment (Mikep86) [inline server/src/main/java/org/elasticsearch/index/query/FilteredSearchExecutionContext.java]: The copy constructor for `FilteredSearchExecutionContext` calls the underlying copy constructor for `SearchExecutionContext`, but then sets `in` to refer to the original:

```
    public FilteredSearchExecutionContext(SearchExecutionContext in) {
        super(in);
        this.in = in;
    }
```

Doesn't that mean that calls to `autoPrefilteringScope` will refer to the original?

**Review by Mikep86 — COMMENTED** [review]
Partial review, I can finish up tomorrow

File: server/src/main/java/org/elasticsearch/index/query/FilteredSearchExecutionContext.java (hunk 4 above)
Comment (davidkyle) [reply server/src/main/java/org/elasticsearch/index/query/FilteredSearchExecutionContext.java]: Yikes good catch!

I'v created a unit test to cover this scenario. FilteredSearchExecutionContext is usually subclassed when it is used with one or more of the functions overridden. For that reason I can't clone it using a copy constructor as it will lose the behaviour added in the subclass. I've opted for cloning instead and it's a fairly simple solution that is easy to test. See e39e73143b5933641b9b427925c28c61d08a2b20

**Review by Mikep86 — COMMENTED** [review]
I took a closer look at this and I think the current solution is both too complicated and fundamentally flawed.

We create the `FilteredSearchExecutionContext`  for the percolator query in [`wrapAllEmptyTextFields`](https://github.com/Mikep86/elasticsearch/blob/d29810df206d8afa320270485bf35f7c8085ead3/modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java#L581-L581). However, when copying it in `createStore`, we generate a new `FilteredSearchExecutionContext` instance that does not persist the anonymously overridden methods. The whole reason for using `FilteredSearchExecutionContext` is lost by generating a copy.

There is a simpler solution that both generates a copy of `SearchExecutionContext` and persists the anonymously overridden methods: [Configure the context](https://github.com/Mikep86/elasticsearch/blob/d29810df206d8afa320270485bf35f7c8085ead3/modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java#L511-L530) late in `createStore`. The steps would be:

1. Refactor `configureContext` and downstream methods as necessary so they are callable from `createStore`.
2. Simplify the implementation of `wrapAllEmptyTextFields` to:

```
    static SearchExecutionContext wrapAllEmptyTextFields(SearchExecutionContext searchExecutionContext) {
        return new SearchExecutionContext(searchExecutionContext) {
            @Override
            public boolean fieldExistsInIndex(String fieldname) {
                return true;
            }
        };
    }
```

This both generates a copy of the context (fixing this bug) and anonymously overrides the desired methods in each copy.

3. Call `configureContext` in `createStore`
4. We can completely remove `FilteredSearchExecutionContext` at this point. It is only used by the percolator query, which no longer needs it.

@benwtrent WDYT?

**Review by benwtrent — APPROVED** [review]
This ended up in a nice place. Thank you @Mikep86 @davidkyle !!!

File: modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java [hunk 5]
```diff
@@ -406,7 +405,7 @@ public void parse(DocumentParserContext context) throws IOException {
             throw new IllegalArgumentException("a document can only contain one percolator query");
         }
 
-        executionContext = configureContext(executionContext, isMapUnmappedFieldAsText());
+        executionContext = PercolateQueryBuilder.newPercolateSearchContext(executionContext, isMapUnmappedFieldAsText());
```
Comment (Mikep86) [inline modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java:408]: It's great that we're using a `SearchExecutionContext` configured similarly at both document parsing time and at query time. There were probably other bugs we hadn't found yet caused by using differently configured contexts here vs. at query time...

**Review by Mikep86 — COMMENTED** [review]
LGTM, nice clean fix!

**Review by Mikep86 — APPROVED** [review]

**Comment by Mikep86** [comment]
@davidkyle Sorry to pile on, but if we're backporting to 8.19, we should backport to 9.2 as well.
