### PR TITLE
[ML][Data Frame] treat bulk index failures as an indexing failure

### LINKED ISSUE #44101: [ML] Individual bulk index failures in data frame should be treated as index failures
Follow up from #43194 

**Steps to reproduce:**
1. Create a dataset
2. Create data frame transform
3. Create destination index with conflicting mappings
4. Start data frame transform
5. Notice that it finishes without reporting any indexing failures in the `_stats` API, even though ES logs show 100% of the docs have failed to index.

**Bug:**
There are 2 issues:

- the indexer does not fail
- the error count is wrong (we should count the bulk index failure as a whole, not the individual index failures)

**Solution:**
The error handling should use the same error handler that we use for search failures, meaning it should classify the issue into:

- temporary failures (e.g. individual shard failures due to trouble on the node holding the shard)
- irrecoverable failures (e.g. mapping conflict)

Temporary failures shall be retried, irrecoverable failures will set the state to failed without retry.

Retry will re-create/re-index the full page **as a whole** but not the individual index requests (which would be very complex).

/cc @dolaru @sophiec20

### PR DESCRIPTION
**Pull request by benwtrent**
Since 7.2 Bulk index failures have been skipped over and cause a completely silent failure. This is a very bad user experience as their transform could be writing NO data, but scrolling through all index without stopping.

In 7.3, with continuously reading from source index, this bad experience is exacerbated. 

The only concern here is that our frequency is STATIC. So, we will not attempt this bulk action again until the task is triggered again. Which is `60s` by default.

closes #44101

### CODE REVIEW

File: x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFramePivotRestIT.java [hunk 1]
```diff
@@ -723,6 +730,44 @@ public void testPivotWithWeightedAvgAgg() throws Exception {
...
+            120,
+            TimeUnit.SECONDS);
+
+        Map<?, ?> state = getDataFrameState(transformId);
+        assertThat((String) XContentMapValues.extractValue("state.reason", state),
+            containsString("task encountered more than 10 failures; latest failure: Bulk index experienced failures."));
+
+        // Force stop the transform as bulk indexing caused it to go into a failed state
+        stopDataFrameTransform(transformId, true);
+        deleteIndex(dataFrameIndex);
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFramePivotRestIT.java]: I delete the index here as these tests keep created indices by default. I delete it so that it can be ran with repeatedly with the `-Dtests.iters` flag

File: x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameRestTestCase.java [hunk 2]
```diff
@@ -211,7 +211,8 @@ protected void createPivotReviewsTransform(String transformId, String dataFrameI
                 + "     \"avg_rating\": {"
                 + "       \"avg\": {"
                 + "         \"field\": \"stars\""
-                + " } } } }"
+                + " } } } },"
+                + "\"frequency\":\"1s\""
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameRestTestCase.java]: Default frequency is low (meaning more time between triggered actions) by default. Making it `1s` for our tests so that things can progress more quickly.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java [hunk 3]
```diff
@@ -591,21 +591,31 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
...
                             }
+                            // TODO gather information on irrecoverable failures and update isIrrecoverableFailure
                         }
-                        auditor.warning(transformId,
-                            "Experienced at least [" +
-                                failureCount +
-                                "] bulk index failures. See the logs of the node running the transform for details. " +
-                                bulkResponse.buildFailureMessage());
-                        auditBulkFailures = false;
+                        if (auditBulkFailures) {
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: We should only write this large audit once per page. Now that we fail on bulk failures, it could occur more than once per page (possibly causing the task to fail).

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java [hunk 4]
```diff
@@ -591,21 +591,31 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
...
+                                    bulkResponse.buildFailureMessage());
+                            auditBulkFailures = false;
+                        }
+                        // This calls AsyncTwoPhaseIndexer#finishWithIndexingFailure
+                        // It increments the indexing failure, and then calls the `onFailure` logic
+                        nextPhase.onFailure(
+                            new BulkIndexFailure("Bulk index experienced failures. " +
+                                "See the logs of the node running the transform for details."));
+                    } else {
+                        auditBulkFailures = true;
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: We can audit the bulk failures again on the next page

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java [hunk 5]
```diff
@@ -591,21 +591,31 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
...
+                                "Experienced at least [" +
+                                    failureCount +
+                                    "] bulk index failures. See the logs of the node running the transform for details. " +
+                                    bulkResponse.buildFailureMessage());
+                            auditBulkFailures = false;
+                        }
+                        // This calls AsyncTwoPhaseIndexer#finishWithIndexingFailure
+                        // It increments the indexing failure, and then calls the `onFailure` logic
+                        nextPhase.onFailure(
+                            new BulkIndexFailure("Bulk index experienced failures. " +
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: I manually created a logging message here so that it is reliably the same thing each time. There could be different bulk failures on each attempt and thus gets logged/audit too many times as we continue to retry the indexing request.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java [hunk 6]
```diff
@@ -807,4 +817,11 @@ protected void failIndexer(String failureMessage) {
                 }, e -> {}));
         }
     }
+
+    // Considered a recoverable indexing failure
+    private static class BulkIndexFailure extends Exception {
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: These exception classes really only need to be seen by the `isIrrecoverableFailure` method. That method currently does not know about them, but it eventually will.

**Review by hendrikmuhs — APPROVED** [review]
LGTM

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java (hunk 6 above)
Comment (droberts195) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: When I saw this I thought it was a bit dangerous passing it to the `onFailure` method of a listener.  If this needed to be transported to a different node then it would cause an error because the exception transport wouldn't know how to serialise it.

I think it's OK as the code stands now because it's consumed on the same node where it's thrown.

I also think it's best practice that exception class names end in `Exception`.  Certainly all the classes that extend `ElasticsearchException` follow this naming pattern.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java [hunk 7]
```diff
@@ -591,21 +591,31 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
...
+                                    failureCount +
+                                    "] bulk index failures. See the logs of the node running the transform for details. " +
+                                    bulkResponse.buildFailureMessage());
+                            auditBulkFailures = false;
+                        }
+                        // This calls AsyncTwoPhaseIndexer#finishWithIndexingFailure
+                        // It increments the indexing failure, and then calls the `onFailure` logic
+                        nextPhase.onFailure(
+                            new BulkIndexFailure("Bulk index experienced failures. " +
+                                "See the logs of the node running the transform for details."));
```
Comment (droberts195) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: If I saw this message my immediate question would be "which node is that?"  How hard would it be to add this?

Adding the node name will not cause the message to be logged more frequently, because if the transform switches nodes then the local variables that remember the message has already been logged will be different.

If it's really hard or messy to add the node name then just add a TODO for now.

Comment (benwtrent) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: @droberts195 when we write the audit message there is a field `node_name: <nodeName>` in the recorded audit message. Additionally, if they see the log, then they are already on the node.

**Review by droberts195 — APPROVED** [review]
LGTM
