### PR TITLE
Fix simple_query_string on invalid input

### LINKED ISSUE #28204: Wrong result of "simple_query_search" with prefix query.
**Elasticsearch version**
6.1.0

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version**:
Ubuntu 17.10 with 4.13.0-21-generic

**Description of the problem including expected versus actual behavior**:
When index's mapping includes text and date properties, result of **simple_query_search**, which includes asterisk for prefix query,
returns no documents. 
When there's no date properties on index's mappping, query works fine.
The same query works fine on 5.6 version.

**Steps to reproduce**:
1. Create index "tests" with text and date properties.
```
curl -XPUT http://localhost:9200/tests -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{
  "mappings": {
    "test": {
      "properties": {
        "date": {
          "type": "date"
        },
        "name": {
          "type": "text",
          "fields": {
            "raw": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}'
```

2. Put some data
```
curl -XPUT http://localhost:9200/tests/test/1 -H 'Content-Type: application/json' -H 'Accept: application/json' -d '
{
  "date": "2018-01-12",
  "name": "test1"
}'
```

3. Try to search with simple_query_search and asterisk.
```
curl -XPOST http://localhost:9200/tests/_search -H 'Content-Type: application/json' -H 'Accept: application/json' -d '
{
  "query": {
    "simple_query_string": {
      "query": "te*"
    }
  }
}'
```

Received result: no documents found
Expected result: document with id 1 found

**Provide logs (if relevant)**:
there's no errors on logs

### PR DESCRIPTION
**Pull request by jimczi**
This change converts any exception that occurs during the parsing of
a simple_query_string to a match_no_docs query (instead of a null query)
when leniency is activated.

Closes #28204

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/index/search/SimpleQueryStringQueryParser.java [hunk 1]
```diff
@@ -90,7 +91,7 @@ private Analyzer getAnalyzer(MappedFieldType ft) {
      */
     private Query rethrowUnlessLenient(RuntimeException e) {
         if (settings.lenient()) {
-            return null;
+            return Queries.newMatchNoDocsQuery("failed query, caused by " + e.getMessage());
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/search/SimpleQueryStringQueryParser.java]: nit: can you update the comment to refect that we return MatchNoDocs instead of null now?

**Comment by cbuescher** [comment]
@jimczi also looked at the additional commit, makes sense. I left one suggestion regarding changes in the comment, other than that this looks good.

**Review by cbuescher — APPROVED** [review]
Great, good to go once CI is green I think.
