### PR TITLE
[ML] Implement force deleting a data frame analytics job

### LINKED ISSUE #48124: [ML] Allow a force delete for analytics jobs
For jobs which may have failed, there is currently a two step process to delete this job. First it must be force closed, then it can be deleted.

We should allow a force delete action so that:
- it allows a single step delete for failed jobs
- it matches anomaly and transform options
- we can stop in-progress analytics jobs quicker as we do not need to wait for any state to be saved as it is about to be deleted (note, this was true for anomaly detection)

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Adds a `force` parameter to the delete data frame analytics
request. When `force` is `true`, the action force-stops the
jobs and then proceeds to the deletion. This can be used in
order to delete a non-stopped job with a single request.

Closes #48124

Docs preview:
* http://elasticsearch_50553.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/delete-dfanalytics.html
* http://elasticsearch_50553.docs-preview.app.elstc.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-x-pack-ml-delete-data-frame-analytics.html

### CODE REVIEW

**Comment by dimitris-athanasiou** [comment]
Could @szabosteve or @lcawl take a look at the docs changes of this one?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java [hunk 1]
```diff
@@ -30,13 +30,21 @@ private DeleteDataFrameAnalyticsAction() {
...
+
+        public static final ParseField FORCE = new ParseField("force");
 
         private String id;
+        private boolean force;
 
         public Request(StreamInput in) throws IOException {
             super(in);
             id = in.readString();
+            if (in.getVersion().onOrAfter(Version.CURRENT)) {
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java]: #nit, 
```suggestion
            if (in.getVersion().onOrAfter(Version.V_8_0_0)) {
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java [hunk 2]
```diff
@@ -49,34 +57,39 @@ public String getId() {
...
             DeleteDataFrameAnalyticsAction.Request request = (DeleteDataFrameAnalyticsAction.Request) o;
-            return Objects.equals(id, request.id);
+            return Objects.equals(id, request.id) && force == request.force;
         }
 
         @Override
         public void writeTo(StreamOutput out) throws IOException {
             super.writeTo(out);
             out.writeString(id);
+            if (out.getVersion().onOrAfter(Version.CURRENT)) {
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java]: #nit, 
```suggestion
            if (in.getVersion().onOrAfter(Version.V_8_0_0)) {
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java [hunk 3]
```diff
@@ -100,6 +101,32 @@ protected AcknowledgedResponse read(StreamInput in) throws IOException {
...
+        if (request.isForce()) {
+            forceDelete(parentTaskClient, id, listener);
+        } else {
+            normalDelete(parentTaskClient, state, id, listener);
+        }
+    }
+
+    private void forceDelete(ParentTaskAssigningClient parentTaskClient, String id,
+                             ActionListener<AcknowledgedResponse> listener) {
+        logger.debug("[] Force deleting data frame analytics job", id);
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java]:
```suggestion
        logger.debug("[{}] Force deleting data frame analytics job", id);
```

**Review by benwtrent — COMMENTED** [review]
just some minor things.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java]: I will have to turn off BWC tests for this. I have the habit of leaving those as `CURRENT` and change them when I unmute the BWC tests after backporting.

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/DeleteDataFrameAnalyticsAction.java]: @dimitris-athanasiou I can understand that, I have just noticed that using `CURRENT` allows you to backport without actually changing the version (since it still compiles). `V_8_0_0` forces me to do things in the correct order.

I just find this helpful, I am not gonna prevent a 👍 over it :D

**Review by benwtrent — APPROVED** [review]

File: docs/reference/ml/df-analytics/apis/delete-dfanalytics.asciidoc [hunk 4]
```diff
@@ -32,6 +32,13 @@ information, see <<security-privileges>> and <<built-in-roles>>.
 (Required, string)
 include::{docdir}/ml/ml-shared.asciidoc[tag=job-id-data-frame-analytics]
 
+[[ml-delete-dfanalytics-query-params]]
+==== {api-query-params-title}
```
Comment (lcawl) [inline docs/reference/ml/df-analytics/apis/delete-dfanalytics.asciidoc]:
```suggestion
==== {api-query-parms-title}
```

File: docs/reference/ml/df-analytics/apis/delete-dfanalytics.asciidoc [hunk 5]
```diff
@@ -32,6 +32,13 @@ information, see <<security-privileges>> and <<built-in-roles>>.
...
+
+`force`::
+  (Optional, boolean) Use to forcefully delete a job that is not stopped; this method is
```
Comment (szabosteve) [inline docs/reference/ml/df-analytics/apis/delete-dfanalytics.asciidoc]: #nitpicking
If I understand correctly then in this case "forcefully" means "deleting the job without stopping it beforehand". If my understanding is correct, then I think "forcefully" is redundant. 

```suggestion
  (Optional, boolean) Deletes a job that is not stopped; this method is
```
