### PR TITLE
Uses `ClusterSettings` instead of Node `Settings` in `HealthMetadataService`

### LINKED ISSUE #96219: max_shards_in_cluster is not properly calculated from max_shards_per_node
### Elasticsearch Version

8.6.0, 8.7.0, 8.8.0, 8.9.0

### Installed Plugins

ESS default

### Java Version

ESS default

### OS Version

ESS default

### Problem Description

Our clusters hit continuously the following error on ESS

It is related to the number of shards per cluster `max_shards_in_cluster` that is calculated based on `max_shards_per_node` but is not correctly calculated, our value for `max_shards_per_node` is 10000. We have 10 data nodes, so we have configured more than 7000 shards per cluster for sure. No matter the value you put on `max_shards_per_node`, we cannot have more than 7000 shards in our clusters.

image

```
      "shards_capacity" : {
        "status" : "Red",
        "symptom" : "Cluster is close to reaching the configured maximum number of shards for data nodes.",
        "details" : {
          "data" : {
            "max_shards_in_cluster" : 7000,
            "current_used_shards" : 9023
```

```
{
  "status": "green",
  "number_of_nodes": 10,
  "unassigned_shards": 0,
  "number_of_pending_tasks": 2,
  "number_of_in_flight_fetch": 0,
  "timed_out": false,
  "active_primary_shards": 5185,
  "task_max_waiting_in_queue_millis": 600,
  "cluster_name": "0000000000000000000000000",
  "relocating_shards": 0,
  "active_shards_percent_as_number": 100,
  "active_shards": 9753,
  "initializing_shards": 0,
  "number_of_data_nodes": 7,
  "delayed_unassigned_shards": 0
}
```

Probably related to https://github.com/elastic/elasticsearch/issues/91119

### Steps to Reproduce

* Deploy a cluster with Elastic Stack 8.7.0
* Create more than 7000 shards
* Change the value of `max_shards_per_node` to 5000
* Wait until the error appears again

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by HiDAl**
While we built the first version of `HealthMetadata` object, we use the `Settings` object, which has the Node's settings. Due to this we always used the default values of the settings. This makes that every time a new master was selected, the initial `HealthMetadata` was built with the default values instead of the settings configured by the user.

closes #96219

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 1]
```diff
@@ -93,7 +105,7 @@ public void testWatermarkSettingUpdate() throws Exception {
             int numberOfNodes = 3;
             ByteSizeValue randomBytes = ByteSizeValue.ofBytes(randomLongBetween(6, 19));
             String initialWatermark = percentageMode ? randomIntBetween(86, 94) + "%" : randomBytes.toString();
-            ByteSizeValue initialMaxHeadroom = percentageMode ? randomBytes : ByteSizeValue.MINUS_ONE;
+            ByteSizeValue initialMaxHeadroom = randomBytes;
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:108]: Is percentage mode not needed here anymore? Below at line 140 we check it when we do the assertion

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 2]
```diff
@@ -147,9 +163,20 @@ public void testWatermarkSettingUpdate() throws Exception {
...
                 var diskMetadata = healthMetadata.getDiskMetadata();
                 assertThat(diskMetadata.describeHighWatermark(), equalTo(updatedHighWatermark));
-                assertThat(diskMetadata.highMaxHeadroom(), equalTo(updatedHighMaxHeadroom));
+
+                // The value of the setting `cluster.routing.allocation.disk.watermark.high.max_headroom` depends upon the existence of
+                // `cluster.routing.allocation.disk.watermark.high`.
+                // Check {@link DiskThresholdSettings.CLUSTER_ROUTING_ALLOCATION_HIGH_DISK_MAX_HEADROOM_SETTING}
+                assertThat(diskMetadata.highMaxHeadroom(), equalTo(percentageMode ? updatedHighMaxHeadroom : ByteSizeValue.ofGb(150)));
                 assertThat(diskMetadata.describeFloodStageWatermark(), equalTo(updatedFloodStageWatermark));
-                assertThat(diskMetadata.floodStageMaxHeadroom(), equalTo(updatedFloodStageMaxHeadroom));
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:152]: Is this flood headroom check removal on purpose?

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Pablo 🚀 

Sorry, it took me a while to test this. 
Namely, I had in mind a potential race-condition concern between the `InsertHealthMetadata` and `UpsertHealthMetadataTask` (in case a setting is updated as there's a also a master failover).

However, I don't think we're subject to it as we have 1 cluster state applier thread and the cluster settings are applied (and listeners notified here https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java#L490) _before_ the cluster state listeners are notified https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java#L502

Equally, now that `InsertHealthMetadata` uses the `ClusterSettings` it will see the changes to the cluster settings. 

Browsing a bit the code I noticed we use this pattern for cluster settings : 
1. read the default value using the `Settings` object
2. subscribe for change notifications via the `ClusterSettings` object
However, step 1 can be performed using the `ClusterSettings` as you've done here for the `indices.dlm.poll_interval` setting

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java (hunk 1 above)
Comment (HiDAl) [reply server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:108]: in this line, no, not needed anymore. This setting has logic when getting the default value, depending upon a different setting. While checking this test, the old behavior was incorrect, using `-1` just to make the test pass. The percentage logic at line 107, will either trigger or not the default-getter-logic

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java (hunk 2 above)
Comment (HiDAl) [reply server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:152]: nop, it's a couple of lines bellow :P  (176-179)

Comment (HiDAl) [reply server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:152]: same comment that https://github.com/elastic/elasticsearch/pull/96843/files#r1230675689

Comment (andreidan) [reply server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:152]: Ah thanks 👍 🚀

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 3]
```diff
@@ -66,7 +66,12 @@ public void testEachMasterPublishesTheirThresholds() throws Exception {
                 var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService().state());
                 var diskMetadata = healthMetadata.getDiskMetadata();
                 assertThat(diskMetadata.describeHighWatermark(), equalTo(watermarkByNode.get(electedMaster)));
-                assertThat(diskMetadata.highMaxHeadroom(), equalTo(maxHeadroomByNode.get(electedMaster)));
+                // The value of the setting `cluster.routing.allocation.disk.watermark.high.max_headroom` depends upon the existence of
+                // `cluster.routing.allocation.disk.watermark.high`. Check {@link CLUSTER_ROUTING_ALLOCATION_HIGH_DISK_MAX_HEADROOM_SETTING}
+                assertThat(
+                    diskMetadata.highMaxHeadroom(),
+                    equalTo(percentageMode ? maxHeadroomByNode.get(electedMaster) : ByteSizeValue.ofGb(150))
```
Comment (gmarouli) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:73]: It took me a while to figure out the relation between the `percentageMode` and the maxHeadroom. Maybe add a comment here that the headroom is not set in the settings if `percentageMode` is false. Or, if possible, set null in the hashmap that passes the value. This way while reading the test I can see how they relate.

What do you think?

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 4]
```diff
@@ -121,7 +133,11 @@ public void testWatermarkSettingUpdate() throws Exception {
                 var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService().state());
                 var diskMetadata = healthMetadata.getDiskMetadata();
                 assertThat(diskMetadata.describeHighWatermark(), equalTo(initialWatermark));
-                assertThat(diskMetadata.highMaxHeadroom(), equalTo(initialMaxHeadroom));
+
+                // The value of the setting `cluster.routing.allocation.disk.watermark.high.max_headroom` depends upon the existence of
+                // `cluster.routing.allocation.disk.watermark.high`.
+                // Check {@link DiskThresholdSettings.CLUSTER_ROUTING_ALLOCATION_HIGH_DISK_MAX_HEADROOM_SETTING}
+                assertThat(diskMetadata.highMaxHeadroom(), equalTo(percentageMode ? initialMaxHeadroom : ByteSizeValue.ofGb(150)));
```
Comment (gmarouli) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:140]: Nit: if possible, I would prefer to use `CLUSTER_ROUTING_ALLOCATION_HIGH_DISK_MAX_HEADROOM_SETTING.getDefault(...)` instead of the hard coded value, because if the value changes for some reason then this test will not fail. Or at least create a constant, if it changes we can easily change it in one place. What do you think?

**Review by gmarouli — APPROVED** [review]
Wow, nice catch with this! I can't believe we didn't see it earlier. Thanks for fixing it. I added some minor comments but LGTM.

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java (hunk 3 above)
Comment (HiDAl) [reply server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:73]: that's why I added the comment to each of these tests, to clearly state that the value depends on the value of other settings... craziness
