### PR TITLE
Handle null columns in ES|QL CHANGE_POINT

### LINKED ISSUE #142858: ESQL: change point value must be numeric for a NULL data type
### Description

```
SET unmapped_fields="nullify";
from employees | change_point foo
```

Or, simpler:

```
from *
| eval foo = null, @timestamp = @timestamp::datetime
| change_point foo
```

returns 

```
change point value [foo] must be numeric",
```

but if I do

```
from *
| eval foo = null::int, @timestamp = @timestamp::datetime
| change_point foo
```
seems to be fine.

The error message is confusing and/or wrong:
- it should either accept a `NULL` data type and return `null` or something similar + warning
- or it should say what kind of numerics it's accepting and what it actually got
For example, `grok` / `dissect` say something like this: `Grok only supports KEYWORD or TEXT values, found expression [foo] type [NULL]"`

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes https://github.com/elastic/elasticsearch/issues/142858

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/ChangePoint.java [hunk 1]
```diff
@@ -156,13 +156,12 @@ public LogicalPlan surrogate() {
     @Override
     public void postAnalysisVerification(Failures failures) {
         // Key must be sortable
-        Order order = order();
-        if (DataType.isSortable(order.dataType()) == false) {
-            failures.add(fail(this, "change point key [" + key.name() + "] must be sortable"));
+        if (DataType.isSortable(key.dataType()) == false) {
+            failures.add(fail(key, "CHANGE_POINT only supports sortable keys, found expression [{}] type [{}]", key.sourceText(), key.dataType()));
```
Comment (jan-elastic) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/ChangePoint.java]: This error message mirrors GROK's error message:
https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/RegexExtract.java#L113

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 2]
```diff
@@ -1032,7 +1032,7 @@ public enum Cap {
         /**
          * Support change point detection "CHANGE_POINT".
          */
-        CHANGE_POINT,
+        CHANGE_POINT_V2,
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: We usually add a new capability whenever there is a change (like this bug fix).

Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: This was added almost a year ago.  I believe we should keep it in order to keep running upgrade tests and instead introduce new "fix" capability instead.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/ChangePoint.java [hunk 3]
```diff
@@ -156,13 +156,21 @@ public LogicalPlan surrogate() {
...
     public void postAnalysisVerification(Failures failures) {
         // Key must be sortable
-        Order order = order();
-        if (DataType.isSortable(order.dataType()) == false) {
-            failures.add(fail(this, "change point key [" + key.name() + "] must be sortable"));
+        if (DataType.isSortable(key.dataType()) == false) {
+            failures.add(
+                fail(key, "CHANGE_POINT only supports sortable keys, found expression [{}] type [{}]", key.sourceText(), key.dataType())
+            );
         }
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/ChangePoint.java]:
```suggestion
    public void postAnalysisVerification(Failures failures) {
        // Key must be sortable
        DataType type = key.dataType();
        if (DataType.isSortable(type) == false) {
            failures.add(
                fail(key, "CHANGE_POINT only supports sortable keys, found expression [{}] type [{}]", key.sourceText(), type)
            );
        }
        // Value must be a number
        type = value.dataType();
        if (DataType.isNullOrNumeric(type) == false) {
            failures.add(
                fail(
                    value,
                    "CHANGE_POINT only supports numeric values, found expression [{}] type [{}]",
                    value.sourceText(),
                    type
                )
            );
        }
    }
```

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/change_point.csv-spec [hunk 4]
```diff
@@ -1017,9 +1017,9 @@ null     | 1             | null         | null
 
 
 values null column
-required_capability: change_point
+required_capability: change_point_v2
 
-ROW time=[7,13,12,17,14,5,16,10,19,18,20,2,3,21,25,4,22,15,6,23,9,11,1,8,24], values=NULL::INTEGER
+ROW time=[7,13,12,17,14,5,16,10,19,18,20,2,3,21,25,4,22,15,6,23,9,11,1,8,24], values=NULL
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/change_point.csv-spec:1063]: I wouldn't change this test. I would add a new one. And the new Capability will be specified only on the new tests. No need to change all the capabilities for all the tests.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/change_point.csv-spec [hunk 5]
```diff
@@ -1201,7 +1201,7 @@ true        | 1             | null         | null
 
 
 example for docs
-required_capability: change_point
+required_capability: change_point_v2
 
 // tag::changePointForDocs[]
 ROW key=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/change_point.csv-spec:1295]: Please, add more tests here. At least, those two mentioned in the original bug report: https://github.com/elastic/elasticsearch/issues/142858

Be creative:
- NULL coming from a folding operation: `eval x = 1 + null` or `eval y = NULL, x = NULL + y`
- NULL coming from unmapped_fields="nullify". There are a lot of tests in `unmapped-nullify.csv-spec` as inspiration.

**Review by astefan — COMMENTED** [review]
Inho, the change is simple and correct, but it would be good to have more tests to double check there are no loose ends. Thanks.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/change_point.csv-spec (hunk 5 above)
Comment (jan-elastic) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/change_point.csv-spec:1295]: add some more tests

**Review by astefan — APPROVED** [review]
LGTM
