### PR TITLE
[Enrich] add logging for when there are search/bulk failures on _execute

### LINKED ISSUE #60491: EnrichPolicyRunner#transferDataToEnrichIndex does not log bulk indexing failure cause
https://github.com/elastic/elasticsearch/blob/f3403faf1276351dae348e2712a4a36ff1a0914d/x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java#L352-L358

On bulk indexing failure, it will help users to debug the cause if the failure message is logged.

Right now it isn't.

**Elasticsearch version** (`bin/elasticsearch --version`):
7.7.1+
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Have an enrich policy fail on `_execute`. Notice that no information about the bulk index failure is in the logs

### PR DESCRIPTION
**Pull request by benwtrent**
When calling `_execute` there is a chance that there will be bulk indexing failures 
or search failures. 

These will result in the call failing overall. But, no information is provided for troubleshooting the failure.

This commit adds logging to indicate the number of failures, and new debug level logging so that
failure details can be determined if necessary.

closes https://github.com/elastic/elasticsearch/issues/60491

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java [hunk 1]
```diff
@@ -352,8 +355,39 @@ private void transferDataToEnrichIndex(final String destinationIndexName) {
...
+                    logger.warn(
+                        "Policy [{}]: encountered [{}] bulk failures. Turn on DEBUG logging for details.",
+                        policyName,
+                        bulkByScrollResponse.getBulkFailures().size()
+                    );
+                    for (BulkItemResponse.Failure failure : bulkByScrollResponse.getBulkFailures()) {
+                        logger.debug(
+                            new ParameterizedMessage(
+                                "Policy [{}]: bulk index failed for index [{}], id [{}]",
+                                failure.getIndex(),
```
Comment (martijnvg) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java:367]: `policyName` is missing as argument.

Comment (benwtrent) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java]: fixed :D. Also wrapped in a `logger.isDebugEnabled()` as there is no point in looping over them unless debug is enabled
