### PR TITLE
Assert translog stats busily

### LINKED ISSUE #45801: [CI] OpenCloseIndexIT testTranslogStats failures
```
java.lang.AssertionError: 
Expected: <9>
     but: was <30>
	at __randomizedtesting.SeedInfo.seed([9BC7168A89B5BF68:DDF74C95536F1D97]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.state.OpenCloseIndexIT.testTranslogStats(OpenCloseIndexIT.java:379)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1361/console
https://gradle-enterprise.elastic.co/s/thddxf4hncok4

[Build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2019-08-10T23:00:00.000Z',mode:absolute,to:'2019-08-21T22:59:59.999Z'))&_a=(columns:!(message,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:OpenCloseIndexIT),sort:!(time,desc))) shows this test has failed a few times recently

Does not reproduce:
```
./gradlew :server:integTest --tests "org.elasticsearch.indices.state.OpenCloseIndexIT.testTranslogStats" \
  -Dtests.seed=9BC7168A89B5BF68 \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP \
  -Dtests.timezone=Africa/Mbabane \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

### PR DESCRIPTION
**Pull request by dnhatn**
If soft-deletes is enabled, we will trim translog above the local checkpoint of the safe commit immediately. However, if the translog durability is async, the last commit might not be the safe commit as the local checkpoint won't advance until translog is synced. We can't verify translog stats in this case.

Closes #45801 
Relates #45473

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java [hunk 1]
```diff
@@ -377,8 +378,13 @@ public void testTranslogStats()  {
 
         IndicesStatsResponse stats = client().admin().indices().prepareStats(indexName).clear().setTranslog(true).get();
         assertThat(stats.getIndex(indexName), notNullValue());
-        assertThat(stats.getIndex(indexName).getPrimaries().getTranslog().estimatedNumberOfOperations(), equalTo(
-            softDeletesEnabled ? uncommittedOps : nbDocs));
+        // If soft-deletes is enabled, we will trim translog above the local checkpoint of the safe commit immediately.
+        // However, if the translog durability is async, the last commit might not be the safe commit as the local checkpoint
+        // won't advance until translog is synced. We can't check for translog stats in this case.
+        if (translogDurability != Translog.Durability.ASYNC || softDeletesEnabled == false) {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: Can't we busy assert here in the async durability case?  The max sync interval setting we use in tests seems to be `5s` so that should work?

Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/indices/state/OpenCloseIndexIT.java]: Good suggestion. I pushed https://github.com/elastic/elasticsearch/pull/45809/commits/2a63de94e4eeb662c71a3b23c1276d8828bff5f4.

**Review by original-brownbear — APPROVED** [review]
thanks @dnhatn LGTM!

**Comment by dnhatn** [comment]
Thanks @original-brownbear.
