### PR TITLE
Esql/lookup join grammar

### LINKED ISSUE #116208: ESQL: Lookup Join meta issue
### Description

Meta ticket around the main implementation topics required for lookup join

- [x] add grammar / parser `LOOKUP JOIN`
- [x] Make it execute correctly on data nodes, too, and enable csv tests `...OnTheDataNode`. See (reproducible) failed runs from https://github.com/elastic/elasticsearch/pull/117639's branch:
  - https://gradle-enterprise.elastic.co/s/5cihyuwehu2lu
  - https://gradle-enterprise.elastic.co/s/aox7wtnevoij2
  - https://github.com/elastic/elasticsearch/pull/117843
- [x] `ON` condition
    - [ ] ~rewrite into JOIN equi-join~ **maybe later**
    - [x] make `ON field`  alias to `USING field` (syntax already used in enrich) - alternative is to deprecate this syntax
    - [x] change index name grammar for identifier to source (to allow date math and others)
    - [x] enhance the field matching grammar against various declarations such as `parent.subfield` & co.

- [x] CSV tests (some suggestions to start with: https://github.com/elastic/elasticsearch/pull/116515#discussion_r1846386923)
  - [x] Cover primary use cases: https://github.com/elastic/elasticsearch/pull/117843/
  - [x] Add tests for using timeseries indices in the `FROM`
- [ ] Known bugs
  - [x] Make `PushDownAndCombineLimits` work for `Join`s https://github.com/elastic/elasticsearch/issues/117698
  - [x] Additional `null` rows https://github.com/elastic/elasticsearch/issues/117702
  - [x] EsqlSession.fieldNames does not handle lookup references that are also mentioned in aliases (erases them)
  - [x] EsqlSession calls `preAnalyzeLookupIndices` asking for all the lookup index' fields all the time, c.f. https://github.com/elastic/elasticsearch/pull/117843#discussion_r1868123620
  - [x] Using an index alias makes it fail with a 500
  - [x] Filtering right side columns removes all data https://github.com/elastic/elasticsearch/pull/118658
  - [x] using same lookup index in FROM breaks an internal assumption https://github.com/elastic/elasticsearch/issues/118865
  - [x] duplicate rows in some specific cases https://github.com/elastic/elasticsearch/issues/118852
  - [x] https://github.com/elastic/elasticsearch/issues/120817
  - [ ] https://github.com/elastic/elasticsearch/issues/120272
- [x] field resolution
    - [x] establish shadowing rules
    - [x] clarify in USING/ON pattern the rules around the join key which are following downstream (left vs right)
    - [x] make the other side fields [nullable](https://github.com/elastic/elasticsearch/pull/116515/files#r1842280850) (this changes the equality for existing fields causing side-effects) create new fields or update the entire field declaration.
    - [x] check resolution exception to differentiate between 500 and 400  https://github.com/elastic/elasticsearch/pull/118826(https://github.com/elastic/elasticsearch/pull/116515#discussion_r1845526933)
- [x] clarify output order rules in case of common keys (join keys and columns with same names) for consistency
     - SQL JOIN: 
          - columns are kept in place and in lacking qualifiers, lead to ambiguation errors
          - JOIN USING moves the join keys in front followed by the columns in table declaration order
     - in ESQL the columns override each other:
          - in EVAL, the latest declaration wins alongside its position - all previous declarations are _hidden_ as if they were removed
          - existing LOOKUP and INLINESTATS return left columns, join keys, right columns using EVAL rules for non-joining keys
          - STATS BY x, returns grouping keys last (declaration order)
     - proposal: 
        - a. return join keys first (like SQL first)
        - b. return join keys last (declaration order, similar to STATS BY - clashes with USING)
        - c. we use `ON`, which is not a thing in SQL, and have it behave similar to ENRICH: join columns in `ON` remain in place, right hand side columns are added on the right (like ENRICH) and shadow any left hand side columns with conflicting names.
     - (c.f. output computation in Analyzer (https://github.com/elastic/elasticsearch/pull/116515#discussion_r1845526358))
     - **We decided on Proposal c.**
     
- [x] Filter pushdown (on the left/main branch) - see #118410
- [x] Fetch only the required fields (relates to field extraction + fieldNames), resp. prune irrelevant lookup index fields from the plan.  https://github.com/elastic/elasticsearch/pull/118808
- [x] Look whether the LookupJoin output could be computed inside the class https://github.com/elastic/elasticsearch/pull/117639
- [x] Resolve lookup table mappings - https://github.com/elastic/elasticsearch/pull/117246
  - [x] Update lookup table mappings solution to support multiple join commands - Craig
- [x] Update verifier and add corresponding tests https://github.com/elastic/elasticsearch/pull/116515#discussion_r1845504613.
  - [x] disallow lookup joins on remote clusters/validate against CCQ
  - [x] disallow lookup joins on more than 1 join field
  - [x] Have validation for stuff that the grammar permits but we can't actually handle yet, like `LOOKUP JOIN idx ON a == b AND to_upper(c) LIKE d`
- [x] Enhance tests
  - [x] Cover primary use cases: https://github.com/elastic/elasticsearch/pull/117843/
  - [x] Add negative tests (missing indexes, indexes with wrong mode, unresolvable field references, etc.) https://github.com/elastic/elasticsearch/pull/117922

#### Compute
- [ ] ~Make field extractor work with LookupOperators (keep field extraction in one place)~
- [ ] ~Bifurcate join operator/allow other operators between join and Lookup source (eval, filter, etc..)~
- [ ] ~Align LookupJoin and LookupJoinExec - the first allows branching, the second does not.~

**Update:** decided to postpone all this until we either evolve the way we perform the actual lookup join, or allow more features like actual condition expressions.

#### Later
- [x] Pushdown optimizations https://github.com/elastic/elasticsearch/issues/119082

#### Maybe
- [x] obtain IndexMode inside IndexResolver (FieldCaps)
- [ ] ReplaceMissingFieldWithNull rule does not have access to SearchStats for lookup indices https://github.com/elastic/elasticsearch/issues/118690
- [ ] refactor JoinConfig into general Expression 
- [ ] rewrite into JOIN equi-join
- [ ] name qualifiers (for disambiguation) (look to descope)

### PR DESCRIPTION
**Pull request by costin**
First PR for adding LOOKUP JOIN in ESQL.
Introduces grammar and wires the main building blocks to execute a query; follow-ups are required (see #116208 for more details).

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+        public String toString() {
+            return joinName();
+        }
+    }
+
+    /**
+     * Private class so it doesn't get used yet it is defined to showcase why the join type was defined as an interface instead of a simpler
+     * enum.
+     */
+    private abstract static class NaturalJoinType implements JoinType {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java:120]: As `USING` establishes a natural  join, why not use/expand this "type"/class, instead of the `UsingJoinType`? Will we ever use them both?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+    public static JoinType INNER = CoreJoinType.INNER;
+    public static JoinType LEFT = CoreJoinType.LEFT;
+    public static JoinType RIGHT = CoreJoinType.RIGHT;
+    public static JoinType FULL = CoreJoinType.FULL;
+    public static JoinType CROSS = CoreJoinType.CROSS;
+
+    /**
+     * The predefined core join types. Implements as enum for easy comparison and serialization.
+     */
+    private enum CoreJoinType implements JoinType {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java:34]: This class implementing `JoinType` feels a bit odd -- does it need to? 
I _suppose_ it's so to be able to keep it private, so that the public constants can be used as is? But it feels a bit odd to init other implementations of `JoinType` (like  `UsingJoinType`) with a `JoinType`, to actually defines its behaviour.
In the Analyser we check for an instance of `UsingJoinType`, which is a `JoinType`, then get out of it the core type, which is another `JoinType`.
I guess what I'm wondering is if we could model the concepts of "how do we stitch" vs "what do we match" separately?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/MapperUtils.java [hunk 3]
```diff
@@ -53,7 +58,15 @@ private MapperUtils() {}
...
-            return new RowExec(row.source(), row.fields());
+            // return new RowExec(row.source(), row.fields());
+            // convert row into local relation
+            List<Alias> fields = row.fields();
+            List<Object> values = new ArrayList<>(fields.size());
+            for (Alias field : fields) {
+                values.add(field.child().fold());
+            }
+            Block[] blocks = BlockUtils.fromListRow(PlannerUtils.NON_BREAKING_BLOCK_FACTORY, values);
+            p = new LocalRelation(row.source(), row.output(), LocalSupplier.of(blocks));
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/MapperUtils.java:69]: Makes sense. I guess we can purge `RowExec` entirely? (It shouldn't have ever been serialised.)
But was this intended in this PR?

**Review by bpintea — COMMENTED** [review]
Some minor questions.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java:120]: Using and Natural are similar but different:
- in Using the keys are specified by the user. Using supports Inner, Left, right and full outer join.
- Natural - the keys are detected at runtime. Only supports inner join.

Hence why these are modelled differently.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java:34]: It's unusual - trying to mix the enum/limited functionality with extension for holding the keys specified by USING.
LEFT JOIN x USING a is different from LEFT JOIN x ON l.a == x.b (assuming namespace will be supported) - it's not just about the condition but also semantics (SQL USING returns the keys as the first column).

There's no strong reason to keep the core enum private; mainly to force the use of the interface and JoinTypes constants helps with evolution (before the enum was differently defined).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/MapperUtils.java (hunk 3 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/MapperUtils.java:69]: It's a workaround to have the mapping works - otherwise it fails since it expects a local relationship and the row throws it off.
It's a topic we've identified before:
https://github.com/elastic/elasticsearch/issues/104960, https://github.com/elastic/elasticsearch/issues/106653

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java [hunk 4]
```diff
@@ -106,31 +101,49 @@ public List<Attribute> output() {
...
+
+    private static List<Attribute> removeDuplicateNames(List<Attribute> attributes, Set<String> sideNames, Set<String> matchFieldNames) {
+        List<Attribute> result = new ArrayList<>(attributes.size());
         for (Attribute attr : attributes) {
-            if ((matchFields.contains(attr) || matchFieldNames.contains(attr.name())) == false) {
+            String name = attr.name();
+            if ((sideNames.contains(name) || matchFieldNames.contains(name)) == false) {
                 result.add(attr);
             }
         }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java:149]: This has become unused.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java [hunk 5]
```diff
@@ -106,31 +101,49 @@ public List<Attribute> output() {
...
+     */
+    private static List<Attribute> merge(List<Attribute> left, List<Attribute> right) {
+        // use linked hash map to preserve order
+        Map<String, Attribute> nameToAttribute = Maps.newLinkedHashMapWithExpectedSize(left.size() + right.size());
+        for (Attribute a : left) {
+            nameToAttribute.put(a.name(), a);
+        }
+        for (Attribute a : right) {
+            // override the existing entry in place
+            nameToAttribute.compute(a.name(), (name, existing) -> a);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java:136]: Guess we should make `a` nullable here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java [hunk 6]
```diff
@@ -106,31 +101,49 @@ public List<Attribute> output() {
...
 
-    private static List<Attribute> removeCollisionsWithMatchFields(
-        List<Attribute> attributes,
-        AttributeSet matchFields,
-        Set<String> matchFieldNames
-    ) {
-        List<Attribute> result = new ArrayList<>();
+    /**
+     * Merge the two lists of attributes into one and preserves order.
+     * In case of conflicts, specify the existing entry is overridden (in place) or not.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java:126]: Doc doesn't match implementation (yet?). Currently the right overrides the left, no way to specify otherwise.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java [hunk 7]
```diff
@@ -0,0 +1,145 @@
...
+    }
+
+    public static JoinType readFrom(StreamInput in) throws IOException {
+        byte id = in.readByte();
+        return switch (id) {
+            case 1 -> INNER;
+            case 2 -> LEFT;
+            case 3 -> RIGHT;
+            case 4 -> FULL;
+            case 5 -> CROSS;
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/JoinTypes.java:141]: nit: maybe this can be made a little more robust by directly using the `CoreJoinType.id`s here, e.g. by iterating over the enum's values and throwing them into a map with ids (obtained from each enum element directly) as key. Would avoid repeating the assignment between enum element and id here.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java [hunk 8]
```diff
@@ -170,7 +171,7 @@ public class CsvTests extends ESTestCase {
 
     @ParametersFactory(argumentFormatting = "%2$s.%3$s")
     public static List<Object[]> readScriptSpec() throws Exception {
-        List<URL> urls = classpathResources("/*.csv-spec");
+        List<URL> urls = classpathResources("/lookup-join.csv-spec");
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java:174]: Marking this for later as that's an important NOCOMMIT :)

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plan/logical/JoinSerializationTests.java [hunk 9]
```diff
@@ -27,7 +28,7 @@ protected Join createTestInstance() {
     }
 
     private static JoinConfig randomJoinConfig() {
-        JoinType type = randomFrom(JoinType.values());
+        JoinType type = randomFrom(JoinTypes.LEFT, JoinTypes.RIGHT, JoinTypes.INNER);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plan/logical/JoinSerializationTests.java:31]: Why do we restrict the join types in this serialization test?

**Review by alex-spies — COMMENTED** [review]
I had a first pass with some questions and thoughts.

**Review by fang-xing-esql — COMMENTED** [review]
I added some thoughts on the grammar/parser first, will look into the rest next.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+
+FROM employees
+| EVAL language_code = languages
+| LOOKUP JOIN languages_lookup ON language_code
+| WHERE emp_no < 1
+| KEEP emp_no, language_name
+| LIMIT 1;
+
+emp_no:integer | language_name:keyword
+;
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec]: Fixed

File: x-pack/plugin/esql/src/main/antlr/EsqlBaseParser.g4 [hunk 11]
```diff
@@ -322,3 +323,19 @@ lookupCommand
 inlinestatsCommand
     : DEV_INLINESTATS stats=aggFields (BY grouping=fields)?
     ;
+
+joinCommand
+    : type=(DEV_JOIN_LOOKUP | DEV_JOIN_LEFT | DEV_JOIN_RIGHT)? DEV_JOIN joinTarget joinCondition
+    ;
+
+joinTarget
+    : index=identifier (AS alias=identifier)?
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/antlr/EsqlBaseParser.g4:332]: I've added this to the metadata https://github.com/elastic/elasticsearch/issues/116208
It will be delicate since the command already uses identifiers which will clashes/is ambiguous with the indexSource declaration.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/UnaryScalarFunction.java [hunk 12]
```diff
@@ -75,62 +75,6 @@
 import static org.elasticsearch.xpack.esql.core.expression.TypeResolutions.isNumeric;
 
 public abstract class UnaryScalarFunction extends EsqlScalarFunction {
-    public static List<NamedWriteableRegistry.Entry> getNamedWriteables() {
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/UnaryScalarFunction.java:78]: Should be fixed now - sorry for the noise.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java (hunk 5 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/Join.java:136]: Added a TODO plus entry in the meta ticket - making the attributes nullable changes their equality which has side effects in the plan.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plan/logical/JoinSerializationTests.java (hunk 9 above)
Comment (costin) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plan/logical/JoinSerializationTests.java:31]: Because natural and using don't survive analysis and thus don't/shouldn't get serialized.

File: x-pack/plugin/esql/src/main/antlr/EsqlBaseParser.g4 [hunk 13]
```diff
@@ -322,3 +323,19 @@ lookupCommand
...
+    ;
+
+joinCondition
+    : ON joinPredicate (COMMA joinPredicate)*
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/antlr/EsqlBaseParser.g4:336]: ON a is the same as USING a.
Moving forward USING should be converted in an expression (after the field resolution happens since we don't have qualifiers and thus the name is not enough).

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:1]: Before merging, I believe we'll need a couple tests here. I can think of:
- LOOKUP JOIN up with an index that is not in lookup mode.
- LOOKUP JOIN with an index that does not exist.
- LOOKUP JOIN ON/USING a field that does not exist in the left/right hand side or both.
- LOOKUP JOIN with USING where there isn't a matching field in the left/right hand side because names or datatypes differ.
- LOOKUP JOIN ON/USING a field with a data type that we cannot join on - e.g. `_source`, spatial or whichever types we won't be able to join on in the beginning.
- Cases with currently disabled join types, like left/right/full

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:1]: Maybe not in this PR, but I believe we'll need some tests that ensure that lookup indices with all kinds of names, incl. special characters, and date math (good point @fang-xing-esql !) applied to them work correctly. Could also throw in `ON`/`USING` for subfields like `parent.subfield` _if_ we want to allow using such fields in lookup indices. And tests for whichever quoting convention we end up using.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java [hunk 14]
```diff
@@ -1948,7 +1948,7 @@ public void testLookup() {
                  * Int is a reference here because we renamed it in project.
                  * If we hadn't it'd be a field and that'd be fine.
                  */
-                .item(containsString("int{r}"))
+                .item(containsString("int{f}"))
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java:1951]: This is subtle. Marking this for before we merge: if this change remains in place, I think we should update the comment above to make sense. Or we just disable the test for now but leave the initial expectations in place.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 15]
```diff
@@ -588,6 +620,76 @@ private LogicalPlan resolveLookup(Lookup l, List<Attribute> childrenOutput) {
             return l;
         }
 
+        private Join resolveLookupJoin(LookupJoin join) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:623]: super duper nit:
```suggestion
        private LookupJoin resolveLookupJoin(LookupJoin join) {
```
I think it's relevant to convey that we're not mapping to a general join here - which would lose us information, rather than only adding information by means of resolving references.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 16]
```diff
@@ -588,6 +620,76 @@ private LogicalPlan resolveLookup(Lookup l, List<Attribute> childrenOutput) {
...
+                        name,
+                        "Only LEFT join is supported with USING"
+                    );
+                    return join.withConfig(new JoinConfig(type, singletonList(errorAttribute), emptyList(), emptyList()));
+                }
+                // resolve the using columns against the left and the right side then assemble the new join config
+                List<Attribute> leftKeys = resolveUsingColumns(cols, join.left().output(), "left");
+                List<Attribute> rightKeys = resolveUsingColumns(cols, join.right().output(), "right");
+                List<Attribute> output = new ArrayList<>(join.left().output());
+                output.addAll(join.right().outputSet().subtract(new AttributeSet(rightKeys)));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:651]: This is subtle. Using the rhs `outputSet` is actually stable in terms of the order of the attributes, because AttributeMaps use a LinkedHashMap internally, right? Maybe we could point this out in a comment here. (Or we add a big, prominent note to AttributeMap's javadoc.)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 17]
```diff
@@ -588,6 +620,76 @@ private LogicalPlan resolveLookup(Lookup l, List<Attribute> childrenOutput) {
...
+
+                // update the config - pick the left keys as those in the output
+                type = new UsingJoinType(coreJoin, rightKeys);
+                config = new JoinConfig(type, leftKeys, leftKeys, rightKeys);
+                join = new LookupJoin(join.source(), join.left(), join.right(), config, output);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:656]: Why do we have to rewrite the config and the output here, in the first place? Shouldn't the output be computed from the left/right sides + the join config in `LookupJoin.output()`? Seems like we place the output computation into multiple places.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 16 above)
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:651]: Is it really correct to subtract the right hand side's attributes based on name id, which we do here?

I'd expect the left and right hand side's attributes to _normally_ have completely disjoint output sets, esp. because we normally plan to join different indices. They _should_ not have field attributes with the same name ids; instead, we should match them up based on their names, no?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 18]
```diff
@@ -588,6 +620,76 @@ private LogicalPlan resolveLookup(Lookup l, List<Attribute> childrenOutput) {
...
+                // columns are expected to be unresolved - if that's not the case return an error
+                else {
+                    return singletonList(
+                        new UnresolvedAttribute(
+                            col.source(),
+                            col.name(),
+                            "Surprised to discover column [ " + col.name() + "] already resolved"
+                        )
+                    );
+                }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:688]: I think this should be an IllegalStateException - otherwise we mask an internal server error (500) as an invalid query (400).

**Review by alex-spies — COMMENTED** [review]
Time for another round!

I didn't review the contained refactor of the writables, as that's many changed lines and deserves its own careful review. I'd appreciate if we could do that in a separate PR.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java
Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:1]: On second thought, that's probably best addressed in a separate PR, but I think we should add it to the meta issue. I took the liberty of adding it to https://github.com/elastic/elasticsearch/issues/116208.

**Review by alex-spies — CHANGES_REQUESTED** [review]
Ok, all done now. I think we're not too far away, but I think there's a couple things that needs to be done before merging - and a bunch of things that can be done after.

Here's what I think we should do:
- I believe the refactoring of the named writable entries should become its own PR. Currently, our mixed cluster test suite is muted, which means that making such a large scale refactor to our serialization is quite risky.
- It looks to me like our current planning for lookup joins expects the match fields from the left and right hand side's outputs to _have the same name ids_. I believe this is wrong and will lead to inconsistent planning; see my comment on the changes to `Analyzer.java`. The fields in the lookup index are different from fields that we join on. Actually, even if we join the lookup index with itself, we should probably still assign different name ids to the respective field attrs. to avoid bugs. There's a comment in `LookupJoinExec` that claims we need qualifiers to make this work, but I don't believe so - name ids should disambiguate the attributes just fine.
- `LookupJoin` and `LookupJoinExec` have some inconsistencies and hacks which I think we best address to avoid them from lingering and producing secondary issues. E.g. the fact that `LookupJoinExec` doesn't have any right hand side attributes in its `references()`, the fact that `LookupJoin.info()` is not quite right etc. See the individual comments.
- Test coverage (can be addressed in a follow up, but then we need to put it in the meta issue as well):
  - The test for lookup joins on the data nodes doesn't look right to me. But we can consider lookup joins on data nodes a follow-up.
  - In general, the test coverage in terms of csv tests for lookup joins even on the coordinator is too small. We can address this in a follow-up, though, but at least should add it to the meta issue.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/ExpressionCoreWritables.java [hunk 19]
```diff
@@ -0,0 +1,48 @@
...
+ */
+
+package org.elasticsearch.xpack.esql.core.expression;
+
+import org.elasticsearch.common.io.stream.NamedWriteableRegistry;
+
+import java.util.ArrayList;
+import java.util.List;
+
+public class ExpressionCoreWritables {
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/ExpressionCoreWritables.java:15]: Indeed the reason for that was that each implementation subclass gained a `getNamedWritables()` so one (me :) ) that returned not the class writable but the entire hierarchy writables.
Which is confusing since Field.getNamedWritable() not only it's possible but doesn't return FieldAttribute.ENTRY but also MetadataAttribute and others. Plus it added a cyclic dependency.

I ended up working on it since the CsvTests had errors due to LookupJoinExec serialization not being written in and the serialization code style was split - see the change in EsqlPlugin.getNamedWritables (mix of utility classes plus individual entries).
I'll work look into extracting it in a separate PR.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec [hunk 20]
```diff
@@ -0,0 +1,48 @@
...
+
+//TODO: this returns different results in CI then locally
+// sometimes null, sometimes spanish (likely related to the execution order)
+FROM employees
+| EVAL language_code = languages
+| LOOKUP JOIN languages_lookup ON language_code
+| WHERE emp_no < 500
+| KEEP emp_no, language_name
+| SORT emp_no
+| LIMIT 1
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:17]: The tests didn't start out this way however it triggered a number of issues including with MixedCluster tests (related to CCS) - see #116208.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java
Comment (costin) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:1]: Thanks, see top entry in #116208

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 16 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:651]: See #116208 "clarify output order" - tl;dr this is not final.
Longer:
you are right that each side, including common keys have different ids. the goal is to move away from name matching and convert the using into a equality condition which can then be pushed down and combined with per-side filtering.
That is, formalize the using into an equal-join that is a filter with equality filter which simplifies other optimizations such as transitive filtering (left_key < 1 AND left_key == right_key --> implies right_key < 1; the left_key filter and right_key filter end up pushed down on their respective sides).
This means moving away from JoinCondition to an expression

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 18 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:688]: Added item to #116208

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 21]
```diff
@@ -0,0 +1,84 @@
...
+        JoinConfig cfg = config();
+        JoinConfig newConfig = new JoinConfig(LEFT, cfg.matchFields(), cfg.leftFields(), cfg.rightFields());
+        Join normalized = new Join(source(), left(), right(), newConfig);
+        // TODO: decide whether to introduce USING or just basic ON semantics - keep the ordering out for now
+        return new Project(source(), normalized, output);
+    }
+
+    public List<Attribute> output() {
+        return output;
+    }
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:56]: I've added a line in #116208.
The main reason why right now it's in the Analyzer is because in case of failure, the LookupJoin becomes an unresolved Join since it doesn't survive (it gets rewritten to a regular join with a special output due to the particularities of using).
Separately the logic around LEFT/RIGHT, etc.. types of join and dealing with each branch are harder to encapsulate because the class has to check itself whether it's children are resolved, what's left and right side.
This type of pattern matching and traversal is done outside the tree classes.

See the TODO I added in JoinConfig and my previous comments.
JoinConfig models an equijoin however moving forward a condition expression since it encapsulates better the generality in the future (ON a > b) and simplifies tree traversal (JoinConfig doesn't extend Node and thus cannot be visited by our rules).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 22]
```diff
@@ -0,0 +1,84 @@
...
+    @Override
+    public Join replaceChildren(LogicalPlan left, LogicalPlan right) {
+        return new LookupJoin(source(), left, right, config(), output);
+    }
+
+    @Override
+    protected NodeInfo<Join> info() {
+        // Do not just add the JoinConfig as a whole - this would prevent correctly registering the
+        // expressions and references.
+        return NodeInfo.create(this, LookupJoin::new, left(), right(), config(), output);
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:67]: The comment was no longer relevant and was removed.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java [hunk 23]
```diff
@@ -0,0 +1,84 @@
...
+import java.util.List;
+import java.util.Objects;
+
+import static java.util.Collections.emptyList;
+import static org.elasticsearch.xpack.esql.plan.logical.join.JoinTypes.LEFT;
+
+/**
+ * Lookup join - specialized LEFT (OUTER) JOIN between the main left side and a lookup index (index_mode = lookup) on the right.
+ * In the future, as the join capabilities of the engine will evolve, a regular LEFT JOIN will be used instead, letting the planner decide
+ * the strategy at runtime.
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java:27]: Thanks, updated the javadoc.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java [hunk 24]
```diff
@@ -202,6 +204,19 @@ private PhysicalPlan mapBinary(BinaryPlan bp) {
...
+                && relation.indexMode() == IndexMode.LOOKUP) {
+                return new LookupJoinExec(
+                    join.source(),
+                    left,
+                    right,
+                    config.matchFields(),
+                    config.leftFields(),
+                    config.rightFields(),
+                    join.output()
+                );
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java:218]: I agree right now the abstraction is simplistic but the point is to decouple the command from the execution.

LookupJoin is syntactic sugar for special left join with special output - it gets folded into a regular join since I'd like to avoid serializing it (and dealing with versioning) and to have the compute engine pick up the pattern not the class.
That means any syntax that gets converted into a left join could be executed against a lookup join. Enrich for example could be attached onto this one but the dependency between the logical and physical happens through the pattern NOT the Lookup class.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/LookupJoinExec.java [hunk 25]
```diff
@@ -0,0 +1,160 @@
...
+    @Override
+    public List<Attribute> output() {
+        return output;
+    }
+
+    @Override
+    public AttributeSet inputSet() {
+        // TODO: this is a hack until qualifiers land since the right side is always materialized
+        return left().outputSet();
+    }
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/LookupJoinExec.java:121]: I've updated the comment.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/LookupJoinExec.java [hunk 26]
```diff
@@ -0,0 +1,160 @@
...
+
+    @Override
+    protected AttributeSet computeReferences() {
+        return Expressions.references(leftFields);
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/LookupJoinExec.java:125]: added a TODO

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/lookup-join.csv-spec:1]: Thanks for adding these to #116208

**Comment by costin** [comment]
Thanks @alex-spies for all the comments, see my nested replies. This PR doesn't aim to fully address the lookup join, rather add the basic layers that can later be distributed and worked on as a follow-up from https://github.com/elastic/elasticsearch/issues/116208 in which you already commented (thanks for that!).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java (hunk 22 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/LookupJoin.java]: I think we still have to pass the individual components of the join config to the node info instead of the join config object as a whole.

If we want to, say, rewrite the plan and need to rename an attribute in the join config's left hand side, just calling `forEachExpression` on the join will be wrong because it ignores the join config.

We had issues because of this with `Join` before; let's fix it so we don't run into trouble later.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/mapper/Mapper.java:218]: That's fair - but we aren't at the point yet where an Enrich, or anything else for that matter, is rewritten into a pattern that is translated into a LookupJoinExec. Currently, we only have the Lookup logical plan node, which doesn't need the additional round trip via surrogate + pattern matching.

I really prefer deferring such generalizations until they have actual use cases - because getting the generalization wrong early on leads to pain :/ and it makes the code more complex than it currently needs.

But that's supposed to be a nit anyway :)

**Review by alex-spies — APPROVED** [review]
Heya - approving this to unblock the PR. I think it's fine to address most things in follow ups, as you suggested @costin.

Before merging, I think it'd be great to
- merge https://github.com/elastic/elasticsearch/pull/117029 first so that the serialization refactoring can be easily backported,
- carefully consider if this should be backported as well (not doing so can seriously hamper our ability to auto-backport as this PR touches many places, even when factoring out the serialization changes), and
- fix `LookupJoin.info()` as commented before.
