### PR TITLE
Unwrap exception more tenaciously in testQueuedOperationsAndBrokenRepoOnMasterFailOver

### LINKED ISSUE #102348: [CI] ConcurrentSnapshotsIT testQueuedOperationsAndBrokenRepoOnMasterFailOver failing
This has failed a few times on the 7.17 branch in the past week.

**Build scan:**
https://gradle-enterprise.elastic.co/s/7do7yy5iakb4o/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testQueuedOperationsAndBrokenRepoOnMasterFailOver

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testQueuedOperationsAndBrokenRepoOnMasterFailOver" -Dtests.seed=41E6956DB2667CA9 -Dtests.locale=sv-SE -Dtests.timezone=EST -Druntime.java=17
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testQueuedOperationsAndBrokenRepoOnMasterFailOver'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.snapshots.ConcurrentSnapshotsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected RepositoryException but got RemoteTransportException[[node_t0][127.0.0.1:25991][cluster:admin/snapshot/delete]]; nested: RemoteTransportException[[node_t2][127.0.0.1:25993][cluster:admin/snapshot/delete]]; nested: RemoteTransportException[[node_t0][127.0.0.1:25991][cluster:admin/snapshot/delete]]; nested: RepositoryException[[test-repo] could not read repository data from index blob]; nested: IOException[Illegal character ((CTRL-CHAR, code 15)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (org.apache.lucene.mockfile.HandleTrackingFS$1); line: 1, column: 2]];

  at __randomizedtesting.SeedInfo.seed([41E6956DB2667CA9:DFA462882AA9FB7F]:0)
  at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2761)
  at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2749)
  at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testQueuedOperationsAndBrokenRepoOnMasterFailOver(ConcurrentSnapshotsIT.java:722)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: org.elasticsearch.transport.RemoteTransportException: [node_t0][127.0.0.1:25991][cluster:admin/snapshot/delete]


    Caused by: org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:25993][cluster:admin/snapshot/delete]


      Caused by: org.elasticsearch.transport.RemoteTransportException: [node_t0][127.0.0.1:25991][cluster:admin/snapshot/delete]


        Caused by: org.elasticsearch.repositories.RepositoryException: [test-repo] could not read repository data from index blob

          at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:2122)
          at org.elasticsearch.repositories.blobstore.BlobStoreRepository.doGetRepositoryData(BlobStoreRepository.java:1917)
          at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
          at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777)
          at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
          at java.lang.Thread.run(Thread.java:833)

          Caused by: java.io.IOException: Illegal character ((CTRL-CHAR, code 15)): only regular white space (\r, \n, \t) is allowed between tokens
           at [Source: (org.apache.lucene.mockfile.HandleTrackingFS$1); line: 1, column: 2]

            at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:727)
            at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3115)
            at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:756)
            at org.elasticsearch.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:73)
            at org.elasticsearch.repositories.RepositoryData.snapshotsFromXContent(RepositoryData.java:791)
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:2111)
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.doGetRepositoryData(BlobStoreRepository.java:1917)
            at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
There can be more than 10 layers of wrapping RTEs, see #102351. As a
workaround to address the test failure, this commit just manually
unwraps them all.

Closes #102348

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java [hunk 1]
```diff
@@ -767,8 +768,18 @@ public void testQueuedOperationsAndBrokenRepoOnMasterFailOver() throws Exception
         internalCluster().stopCurrentMasterNode();
         ensureStableCluster(3);
 
-        awaitNoMoreRunningOperations();
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:770]: Do we still need this statement?

**Review by ywangd — APPROVED** [review]
LGTM

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:770]: Um thanks, not sure where that went! Probably not necessary indeed since we are waiting (indefiniteyl!) on `deleteFuture::get` either way but I did not mean to remove it.
