### PR TITLE
Always treat dash-prefixed expression as index exclusion

### LINKED ISSUE #64752: Multi-target syntax does not exclude literal index of the first wildcard exclude
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.3

**Plugins installed**: None.

**JVM version** (`java -version`): 14

**OS version**: CentOS 7.4

**Description of the problem including expected versus actual behavior**: When trying to query an index and excluding with wildcard, the first wildcard exclude is not excluded. 

Given the indices `tatiana`, `virginia` and `alina`, the expected result of `GET tatiana,-ta*` is nothing, while the actual response includes the index `tatiana`. However, `GET tatiana,-al*,-ta*` will **not** include `tatiana`.

**Steps to reproduce**:
 1. Create an index:
```
curl -XPUT localhost:9200/tatiana/1 -d '{
 "title": "test document"
}'
```
 2. GET the index `tatiana` and remove (exclude) all indices that begin with `ta*`
`curl -XGET localhost:9200/tatiana,-ta*`

**Provide logs (if relevant)**: -

### LINKED ISSUE #83435: snapshot with exclude expression `-` does not work if index contains hyphen
### Elasticsearch Version

7.16.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

OS X

### Problem Description

On https://www.elastic.co/guide/en/elasticsearch/reference/7.16/slm-api-put-policy.html, you can see that `-*` allows you to exclude all data streams and indices and I thought a single hyphen `-` works as exclude expression.

Then I wanted to only exclude certain index and I used `-us` which resulted in the error below.
The workaround I found was to `-u*` to exclude index named `us`.

I am not sure if this is intended, but if it is, I think it might be helpful to indicate that you cannot specify explicit index name like I did and it has to be combined with wildcard `*` to do so.

>indices
(Optional, string or array of strings) Comma-separated list of data streams and indices to include in the snapshot. Supports [multi-index syntax](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/api-conventions.html#api-multi-index). Defaults to an empty array ([]), which includes all regular data streams and regular indices. To exclude all data streams and indices, use -*.

But when the index name contains hyphen, you get this error

```
[2022-02-03T09:42:12,723][WARN ][o.e.s.SnapshotsService   ] [nami.local] [my_repository][daily-snap-2022.02.03-o69tulghqhchwmpswjj13w] failed to create snapshot
org.elasticsearch.index.IndexNotFoundException: no such index [-us]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:1250) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:1188) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:1144) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:292) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:270) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:92) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.snapshots.SnapshotsService$2.execute(SnapshotsService.java:498) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:487) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:836) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:403) ~[elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:243) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:170) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) [elasticsearch-7.16.2.jar:7.16.2]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) [elasticsearch-7.16.2.jar:7.16.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-02-03T09:42:12,724][ERROR][o.e.x.s.SnapshotLifecycleTask] [nami.local] failed to create snapshot for snapshot lifecycle policy [daily-snapshots]: [-us] IndexNotFoundException[no such index [-us]]
```

### Steps to Reproduce

```
PUT japan
PUT us

# error pattern
PUT /_slm/policy/daily-snapshots
{
  "schedule": "0 30 1 * * ?", 
  "name": "<daily-snap-{now/d}>", 
  "repository": "my_repository", 
  "config": { 
    "indices": ["japan", "-us"], 
    "ignore_unavailable": false,
    "include_global_state": false
  }
}

PUT /_slm/policy/daily-snapshots/_execute


# successful pattern
PUT /_slm/policy/daily-snapshots
{
  "schedule": "0 30 1 * * ?", 
  "name": "<daily-snap-{now/d}>", 
  "repository": "my_repository", 
  "config": { 
    "indices": ["japan", "-u*"], 
    "ignore_unavailable": false,
    "include_global_state": false
  }
}

PUT /_slm/policy/daily-snapshots/_execute
```

Note that the response does not show you the error and you have to look in the log file to see the error.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ywangd**
Fixed a bug that dash prefix expressions, including both concrete names and wildcard patterns, are not always treated as index exclusion during index resolution process. The PR also updates relevant document to make the behaviour clear. 

Resolves: #64752
Resolves: #83435

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/ResolvedIndexExpressions.java [hunk 1]
```diff
@@ -93,8 +93,14 @@ public void addRemoteExpressions(String original, Set<String> remoteExpressions)
...
+                while (iter.hasNext()) {
+                    final ResolvedIndexExpression current = iter.next();
+                    if (expressionsToExclude.contains(current.original())) {
+                        iter.remove();
+                        continue;
+                    }
+                    final Set<String> localExpressions = current.localExpressions().indices();
                     if (localExpressions.isEmpty()) {
                         continue;
                     }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/action/ResolvedIndexExpressions.java:106]: This change ensures that an expression like `foo,bar,-foo` work correctly by excluding `foo` entirely from the `ResolvedExpressions`. It is so far a CPS only feature and strictly speaking not necessary for stateful code yet. But we would have to mute or skip tests without it. So I decided to include it given the its relative small size.

**Comment by ywangd** [comment]
Both `indexNameExpressionResolver` and `IndexAbstractionResolver` have the problematic exclusion handling. The former can still take effect when security is disabled. The PR fixes the issues in both places.

**Review by idegtiarenko — APPROVED** [review]
ES|QL will take advantage of this changes once merged as we indirectly use IndexNameExpressionResolver.

Thanks, looking forward for this change to be merged!

**Review by DaveCTurner — DISMISSED** [review]
A user who is snapshotting `very-important-index,other-indices*,-*ant*` today will, after this change, silently stop having snapshots of `very-important-index`. I understand that we might like to change this behaviour, even perhaps considering it a bug, but still it's a potentially-data-loss-causing breaking change that at least needs some discussion with the BCC before proceeding.

The original design in which specifically-named indices (no wildcards) are not excluded was a deliberate choice.

**Comment by ywangd** [comment]
@DaveCTurner 

> needs some discussion with the BCC before proceeding

Indeed. There is an approval proposal for this change. I tagged you in Slack for the relevant message. Thanks for checking!

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 2]
```diff
@@ -401,12 +401,11 @@ protected static Collection<ResolvedExpression> resolveExpressionsToResources(Co
         Collection<ResolvedExpression> resources = expandWildcards && WildcardExpressionResolver.hasWildcards(expressions)
             ? new LinkedHashSet<>()
             : new ArrayList<>(expressions.length);
-        boolean wildcardSeen = false;
         for (int i = 0, n = expressions.length; i < n; i++) {
             String originalExpression = expressions[i];
 
             // Resolve exclusion, a `-` prefixed expression is an exclusion only if it succeeds a wildcard.
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: This comment is now inaccurate :)

**Review by DaveCTurner — COMMENTED** [review]
Sorry, I was misreading the effects of this change, it doesn't have the impact I initially thought. I'm ok with it now, sorry for the noise.

File: docs/changelog/138467.yaml [hunk 3]
```diff
@@ -0,0 +1,7 @@
+pr: 138467
+summary: "Fixed a bug that dash prefix expressions, including both concrete names\
```
Comment (leemthompo) [inline docs/changelog/138467.yaml]: `language nit`: I'd rephrase and add examples:

_Fixed a bug where dash-prefixed expressions, for both specific index names and wildcard patterns (for example: `-system-index`, `-logs-*`), were not consistently excluded during index resolution._

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java (hunk 2 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: Fixed in 5a3aaba4d8a22bc190a85914f3c01ab5dbfd8898 Thanks

File: docs/changelog/138467.yaml (hunk 3 above)
Comment (ywangd) [reply docs/changelog/138467.yaml]: Thanks for the suggestion. Updated in 1f1d7573eea7f5c6bb1b0e020c06f2bf99dac2c3

File: docs/reference/elasticsearch/rest-apis/api-conventions.md [hunk 4]
```diff
@@ -282,7 +282,21 @@ Most APIs that accept a `<data-stream>`, `<index>`, or `<target>` request path p
...
+For example, `test3*,-test3,test*` resolves to all resources that start with `test`, including `test3`, because it is included
+by the last `test*` pattern.
+
+{applies_to}`stack: ga 9.3` A dash-prefixed (`-`) expression is always treated as an exclusion.
+
+::::{note}
+In previous versions, such expression is sometimes _not_ treated as an exclusion due to a bug.
+For example, neither `test,-test` nor `test3,-test*` is treated as exclusion.
+Instead, `IndexNotFoundException` is thrown for the first expression while the second resolves to `test3`.
+This bug has since been fixed in 9.3.
```
Comment (leemthompo) [inline docs/reference/elasticsearch/rest-apis/api-conventions.md]:
```suggestion
In previous versions, dash-prefixed expressions were sometimes not treated as exclusions due to a bug. For example:
- `test,-test` threw an `IndexNotFoundException` instead of excluding `test`
- `test3,-test*` incorrectly resolved to `test3` instead of excluding matches to the wildcard pattern

This bug is fixed in 9.3.
```

File: docs/changelog/138467.yaml [hunk 5]
```diff
@@ -0,0 +1,9 @@
+pr: 138467
+summary: >
+  Fixed a bug where dash-prefixed expressions, for both specific index names and wildcard patterns
+  (for example: -index, -logs-*), were not consistently excluded during index resolution.
```
Comment (leemthompo) [inline docs/changelog/138467.yaml]:
```suggestion
  Fixed a bug where dash-prefixed expressions were not consistently excluded during index resolution. This impacted both specific index names and wildcard patterns (example: `-index, -logs-*`).
```

editing my first edit :)

**Review by leemthompo — COMMENTED** [review]
Just couple language issues. I think the note is OK, but I'll let @DaveCTurner weigh in on whether it's clear enough to his eyes

File: docs/reference/elasticsearch/rest-apis/api-conventions.md [hunk 6]
```diff
@@ -282,7 +282,21 @@ Most APIs that accept a `<data-stream>`, `<index>`, or `<target>` request path p
...
+For example, `test*,-test3` resolves to all resources that start with `test` except for the resource named `test3`.
+It is possible for exclusion to exclude all resources. For example, `test*,-test*` resolves to an empty set.
+An exclusion affects targets listed _before_ it and has no impact on targets listed _after_ it.
+For example, `test3*,-test3,test*` resolves to all resources that start with `test`, including `test3`, because it is included
+by the last `test*` pattern.
+
+{applies_to}`stack: ga 9.3` A dash-prefixed (`-`) expression is always treated as an exclusion.
+
+::::{note}
+In previous versions, such expression is sometimes _not_ treated as an exclusion due to a bug.
```
Comment (DaveCTurner) [inline docs/reference/elasticsearch/rest-apis/api-conventions.md]: Can we use `removed 9.3` here?

```
{applies_to}`stack: removed 9.3`
```

I think that'd be nicer than a `::::{note}` which highlights this whole paragraph as if it's important.

Comment (leemthompo) [reply docs/reference/elasticsearch/rest-apis/api-conventions.md]: I think `removed` is aimed more at features that have been deprecated and eventually removed 🤔 

Pinging the experts @florent-leborgne @shainaraskas @colleenmcginnis who will have more ideas about the appropriate pattern to use here. 

> nicer than a ::::{note} which highlights this whole paragraph as if it's important.

Yes, I think we could just remove the note too and that might suffice here, as the new behavior now has the applies_to tag

Comment (shainaraskas) [reply docs/reference/elasticsearch/rest-apis/api-conventions.md]: I think that just pulling this out of a note would work. I think until we have ranges (eta 9.3), that's the best choice

Comment (ywangd) [reply docs/reference/elasticsearch/rest-apis/api-conventions.md]: Thanks. I removed the `note` annotation as suggested fb4b24a75094f0ae8d3a1a0148b68d6a8f8052cf

**Review by leemthompo — APPROVED** [review]
Thanks for iterating on the docs!

**Review by tvernum — APPROVED** [review]
