### PR TITLE
Limit shard realocation retries

### LINKED ISSUE #79445: Shard relocations are retried indefinitely
We keep count of how many times we've tried to allocate a shard, and if we fail too many times in a row then we give up (via the `MaxRetryAllocationDecider`) rather than repeatedly failing forever. Today the failure count is attached to the `ShardRouting` which makes sense for unassigned shards, but when a shard is already assigned and being relocated then the relocation target is represented by a temporary `ShardRouting` which only exists while the relocation is ongoing. If the relocation fails then the target `ShardRouting` disappears so we lose track of the failure, which means there's nothing stopping us from attempting the same relocation forever.

### PR DESCRIPTION
**Pull request by idegtiarenko**
This change ensures that elasticsearch would not indefinitely retry relocating shard if operation fails.

Closes: #79445

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/routing/RelocationFailureInfoTests.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    }
+
+    @Override
+    protected RelocationFailureInfo createTestInstance() {
+        return new RelocationFailureInfo(randomInt());
+    }
+
+    @Override
+    protected RelocationFailureInfo mutateInstance(RelocationFailureInfo instance) throws IOException {
+        return createTestInstance();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/RelocationFailureInfoTests.java:30]: `mutateInstance` must return a different value (I know, the chance of failure is very low here)

File: server/src/test/java/org/elasticsearch/cluster/routing/RelocationFailureInfoTests.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+public class RelocationFailureInfoTests extends AbstractWireSerializingTestCase<RelocationFailureInfo> {
+
+    @Override
+    protected Writeable.Reader<RelocationFailureInfo> instanceReader() {
+        return RelocationFailureInfo::new;
+    }
+
+    @Override
+    protected RelocationFailureInfo createTestInstance() {
+        return new RelocationFailureInfo(randomInt());
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/routing/RelocationFailureInfoTests.java:25]: Hmm I think we need the number of failures to be ≥0?

**Review by DaveCTurner — COMMENTED** [review]
I left some initial comments.

File: server/src/main/java/org/elasticsearch/cluster/routing/RelocationFailureInfo.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+import org.elasticsearch.xcontent.ToXContentFragment;
+import org.elasticsearch.xcontent.XContentBuilder;
+
+import java.io.IOException;
+import java.util.Objects;
+
+/**
+ * Holds additional information as to why the shard failed to relocate.
+ */
+public class RelocationFailureInfo implements ToXContentFragment, Writeable {
```
[the remark this answers is not in the document]
Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/cluster/routing/RelocationFailureInfo.java]: Converted to a record. I wanted to keep it a class/record in case we want to make this behavior more complex in the future (similar to UnassignedInfo with recording failed nodes or introducing a delay)

File: server/src/main/java/org/elasticsearch/cluster/routing/RelocationFailureInfo.java [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+
+import java.io.IOException;
+
+/**
+ * Holds additional information as to why the shard failed to relocate.
+ */
+public record RelocationFailureInfo(int failedRelocations) implements ToXContentFragment, Writeable {
+
+    public RelocationFailureInfo {
+        assert failedRelocations > 0 : "Expect positive failures count, got: " + failedRelocations;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/RelocationFailureInfo.java:25]: I'm not a big fan of using `null` to represent `RelocationFailureInfo(0)`. Let's make the field non-nullable and use a singleton for `RelocationFailureInfo(0)` to avoid the unnecessary allocation & heap usage.

```suggestion
        assert failedRelocations >= 0 : "Expect non-negative failures count, got: " + failedRelocations;
```

File: server/src/main/java/org/elasticsearch/cluster/routing/RelocationFailureInfo.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+public record RelocationFailureInfo(int failedRelocations) implements ToXContentFragment, Writeable {
+
+    public static final RelocationFailureInfo NO_FAILURES = new RelocationFailureInfo(0);
+
+    public RelocationFailureInfo {
+        assert failedRelocations >= 0 : "Expect non-negative failures count, got: " + failedRelocations;
+    }
+
+    public RelocationFailureInfo(StreamInput in) throws IOException {
+        this(in.readVInt());
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/RelocationFailureInfo.java:31]: We should also return `NO_FAILURES` when reading a zero off the wire.

File: server/src/main/java/org/elasticsearch/cluster/routing/ShardRouting.java [hunk 6]
```diff
@@ -774,6 +826,9 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
         if (unassignedInfo != null) {
             unassignedInfo.toXContent(builder, params);
         }
+        if (relocationFailureInfo != RelocationFailureInfo.NO_FAILURES) {
+            relocationFailureInfo.toXContent(builder, params);
```
[the remark this answers is not in the document]
Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/cluster/routing/ShardRouting.java:831]: Do we have any clients that fail on unknown fields that we need to notify about the change?

**Review by DaveCTurner — APPROVED** [review]
LGTM
