### PR TITLE
Fail recovery when index not found with non-empty starting seq no

### LINKED ISSUE #118733: [CI] SearchWithRandomIOExceptionsIT testRandomDirectoryIOExceptions failing
**Build Scans:**
- [elasticsearch-intake #15753 / part1](https://gradle-enterprise.elastic.co/s/32dp6vfgbktia)
- [elasticsearch-pull-request #50439 / part-1](https://gradle-enterprise.elastic.co/s/4ey7xz57y745e)
- [elasticsearch-periodic #5845 / openjdk22_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/wlusawhlzx7hi)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions" -Dtests.seed=68D49D0C3D2BCBF6 -Dtests.locale=shi-Tfng -Dtests.timezone=America/Bahia -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRandomDirectoryIOExceptions),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Shard [test][0] is still locked after 5 sec waiting
```

**Issue Reasons:**
- [8.x] 3 failures in test testRandomDirectoryIOExceptions (5.3% fail rate in 57 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by tlrx**
When an IndexNotFoundException is caught during peer recovery but the starting sequence number from translog is valid (!= UNASSIGNED), this indicates an inconsistent state between Lucene index files and the translog.

Previously, this was only checked via an assertion which could be disabled in production. This change throws a RecoveryFailedException in this scenario to properly fail the recovery and trigger cleanup of the inconsistent local shard files.

As far as I know this situation has never been observed in production but can occur in tests due to simulated I/O errors. I'm running the test `SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions` in a loop for a while now but it haven't failed yet after 1K iterations on `main` nor on `8.19`.

But it reproduces easily on 8.18.0 on commit `af14e5cb78550b90a1b80e891de7a98916d0e8ef` with the following reproducer:
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions" -Dtests.seed=68D49D0C3D2BCBF6 -Dtests.locale=shi-Tfng -Dtests.timezone=America/Bahia
```

Fixes #118733

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM makes sense to me

File: server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java [hunk 1]
```diff
@@ -762,6 +768,35 @@ public void testSnapshotFileDownloadPermitIsReleasedAfterClosingRecoveryTarget()
         closeShards(shard);
     }
 
+    public void testFailsRecoveryIfIndexNotFoundWithNonEmptyStartingSeqNoInTranslog() throws Exception {
+        IndexShard shard = newStartedShard(false);
+        populateRandomData(shard);
+
+        DiscoveryNode pNode = DiscoveryNodeUtils.builder("foo").roles(Collections.emptySet()).build();
+        DiscoveryNode rNode = DiscoveryNodeUtils.builder("foo").roles(Collections.emptySet()).build();
```
Comment (inespot) [inline server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java]: Nit: "bar" so we don't have conflicting ids? Or is that intentional?

**Review by inespot — APPROVED** [review]
One small question, otherwise LGTM! 
Thanks for the detailed comments in the code, this is pretty interesting!

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java (hunk 1 above)
Comment (tlrx) [reply server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java]: Not intentional, I blatantly copied that from previous tests which probably suffered from a wrong copy/paste.

I pushed 3fef96250c27f66f9ff1263875e52892baf06e55 to change the replica node to "bar".

**Comment by tlrx** [comment]
Thanks everyone!
