### PR TITLE
Re-check node cache stats before failing

### LINKED ISSUE #112384: [CI] NodesCachesStatsIntegTests testNodesCachesStats failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3884 / centos-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/qqm7gy4hnman4)
- [elasticsearch-pull-request #29293 / part-2](https://gradle-enterprise.elastic.co/s/7tazkuxk5eooy)
- [elasticsearch-pull-request #29079 / part-2](https://gradle-enterprise.elastic.co/s/tluqdydyvenjo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:searchable-snapshots:internalClusterTest" --tests "org.elasticsearch.xpack.searchablesnapshots.cache.shared.NodesCachesStatsIntegTests.testNodesCachesStats" -Dtests.seed=1EA29C05D828C3CD -Dtests.locale=ar-LY -Dtests.timezone=IST -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testNodesCachesStats'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.searchablesnapshots.cache.shared.NodesCachesStatsIntegTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>
```

**Issue Reasons:**
- [main] 3 failures in test testNodesCachesStats (0.3% fail rate in 966 executions)
- [main] 2 failures in step part-2 (0.8% fail rate in 237 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.8% fail rate in 240 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
This failure is very difficult to reproduce (and understand), in discussion with @tlrx, he suggested perhaps `writeCount` might return zero temporarily due to contention on the `LongAdder`. If that's true, this should fix the test, if not, we'll know to look elsewhere.

Closes #112384

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/NodesCachesStatsIntegTests.java [hunk 1]
```diff
@@ -136,30 +136,34 @@ public void testNodesCachesStats() throws Exception {
...
-                assertThat(nodeCachesStats.getEvictions(), greaterThan(0L));
-            } else {
-                assertThat(nodeCachesStats.getWrites(), equalTo(0L));
-                assertThat(nodeCachesStats.getBytesWritten(), equalTo(0L));
-                assertThat(nodeCachesStats.getReads(), equalTo(0L));
-                assertThat(nodeCachesStats.getBytesRead(), equalTo(0L));
-                assertThat(nodeCachesStats.getEvictions(), equalTo(0L));
+        // We've seen `getWrites` inexplicably return zero. `assertBusy` to test the theory of it being due
+        // to contention on the `LongAdder` at `SharedBlobCacheService#writeCount`.
+        assertBusy(() -> {
```
Comment (nicktindall) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/NodesCachesStatsIntegTests.java:141]: We could also log a message including all the `NodeCachesStatsResponse` when we fail (for troubleshooting), but if the theory is correct that's just extra log noise.

**Review by tlrx — APPROVED** [review]
LGTM, since we have no better idea
