### PR TITLE
Fix OperatorTestCase small input size

### LINKED ISSUE #136903: [CI] MedianAbsoluteDeviationLongAggregatorFunctionTests testSimpleSmallInput failing
**Build Scans:**
- [elasticsearch-intake #30319 / part3](https://gradle-enterprise.elastic.co/s/txwgzsq5l6ku4)
- [elasticsearch-periodic #11329 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/nlpjg45oct6ty)
- [elasticsearch-pull-request #99978 / part-3](https://gradle-enterprise.elastic.co/s/yqxi23l5cuwzc)
- [elasticsearch-periodic #11329 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/vj3kky5loieam)
- [elasticsearch-intake #30307 / part3](https://gradle-enterprise.elastic.co/s/riwb2pulgh4ya)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests.testSimpleSmallInput" -Dtests.seed=CAF3595A0431A881 -Dtests.locale=et-EE -Dtests.timezone=Asia/Muscat -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationLongAggregatorFunctionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSimpleSmallInput'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <23.0>
     but: was <15.5>
```

**Issue Reasons:**
- [main] 5 failures in test testSimpleSmallInput (2.1% fail rate in 242 executions)
- [main] 2 failures in step part3 (5.6% fail rate in 36 executions)
- [main] 2 failures in pipeline elasticsearch-intake (5.6% fail rate in 36 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #136904: [CI] MedianAbsoluteDeviationDoubleAggregatorFunctionTests testSimpleSmallInput failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11313 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/lszzpgs7tdey4)
- [elasticsearch-periodic-platform-support #11313 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/334viv2x3guzi)
- [elasticsearch-periodic-platform-support #11313 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/kz2ng6ftvzkle)
- [elasticsearch-intake #30319 / part3](https://gradle-enterprise.elastic.co/s/txwgzsq5l6ku4)
- [elasticsearch-periodic #11329 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/nlpjg45oct6ty)
- [elasticsearch-pull-request #99978 / part-3](https://gradle-enterprise.elastic.co/s/yqxi23l5cuwzc)
- [elasticsearch-periodic #11329 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/vj3kky5loieam)
- [elasticsearch-intake #30307 / part3](https://gradle-enterprise.elastic.co/s/riwb2pulgh4ya)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationDoubleAggregatorFunctionTests.testSimpleSmallInput" -Dtests.seed=8D8BD658102D1F75 -Dtests.locale=yi -Dtests.timezone=America/Denver -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationDoubleAggregatorFunctionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSimpleSmallInput'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0.8>
     but: was <1.9249999999999998>
```

**Issue Reasons:**
- [main] 3 consecutive failures in test testSimpleSmallInput
- [main] 8 failures in test testSimpleSmallInput (3.0% fail rate in 266 executions)
- [main] 2 failures in step part3 (5.6% fail rate in 36 executions)
- [main] 2 failures in pipeline elasticsearch-intake (5.6% fail rate in 36 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #136905: [CI] MedianAbsoluteDeviationIntAggregatorFunctionTests testSimpleSmallInput failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11313 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/lszzpgs7tdey4)
- [elasticsearch-periodic-platform-support #11313 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/334viv2x3guzi)
- [elasticsearch-periodic-platform-support #11313 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/kz2ng6ftvzkle)
- [elasticsearch-intake #30319 / part3](https://gradle-enterprise.elastic.co/s/txwgzsq5l6ku4)
- [elasticsearch-periodic #11329 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/nlpjg45oct6ty)
- [elasticsearch-pull-request #99978 / part-3](https://gradle-enterprise.elastic.co/s/yqxi23l5cuwzc)
- [elasticsearch-periodic #11329 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/vj3kky5loieam)
- [elasticsearch-intake #30307 / part3](https://gradle-enterprise.elastic.co/s/riwb2pulgh4ya)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationIntAggregatorFunctionTests.testSimpleSmallInput" -Dtests.seed=8D8BD658102D1F75 -Dtests.locale=ka-GE -Dtests.timezone=Africa/Lusaka -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.aggregation.MedianAbsoluteDeviationIntAggregatorFunctionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSimpleSmallInput'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <23.0>
     but: was <35.0>
```

**Issue Reasons:**
- [main] 3 consecutive failures in test testSimpleSmallInput
- [main] 8 failures in test testSimpleSmallInput (3.0% fail rate in 267 executions)
- [main] 2 failures in step part3 (5.4% fail rate in 37 executions)
- [main] 2 failures in pipeline elasticsearch-intake (5.4% fail rate in 37 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #136945: [CI] HashAggregationOperatorTests testSimpleSmallInput failing
**Build Scans:**
- [elasticsearch-intake #30348 / part3](https://gradle-enterprise.elastic.co/s/nicxf2zgn5yeu)
- [elasticsearch-pull-request #100089 / part-3](https://gradle-enterprise.elastic.co/s/cnibg6cqs2qey)
- [elasticsearch-intake #30342 / part3](https://gradle-enterprise.elastic.co/s/owmtftyfelcxe)
- [elasticsearch-pull-request #100054 / part-3](https://gradle-enterprise.elastic.co/s/226ht726zvyjm)
- [elasticsearch-periodic-platform-support #11313 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/334viv2x3guzi)
- [elasticsearch-pull-request #100007 / part-3](https://gradle-enterprise.elastic.co/s/g4sqhpkk2zd3q)
- [elasticsearch-periodic #11329 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/nlpjg45oct6ty)
- [elasticsearch-periodic #11329 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/vj3kky5loieam)
- [elasticsearch-intake #30307 / part3](https://gradle-enterprise.elastic.co/s/riwb2pulgh4ya)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.operator.HashAggregationOperatorTests.testSimpleSmallInput" -Dtests.seed=EEBDAA4410928EA6 -Dtests.locale=ff-Latn-GH -Dtests.timezone=Asia/Singapore -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.operator.HashAggregationOperatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSimpleSmallInput'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <5>
     but: was <3>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testSimpleSmallInput
- [main] 9 failures in test testSimpleSmallInput (3.3% fail rate in 269 executions)
- [main] 3 failures in step part3 (6.3% fail rate in 48 executions)
- [main] 3 failures in step part-3 (2.6% fail rate in 114 executions)
- [main] 3 failures in pipeline elasticsearch-intake (6.3% fail rate in 48 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.7% fail rate in 113 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by afoucret**
- Fixes #136133 
- Fixes #136903
- Fixes #136904
- Fixes #136905
- Fixes #136945

### CODE REVIEW

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ public final void testSimpleSmallInput() {
     }
 
     protected int smallInputSize() {
-        return randomIntBetween(1, 100);
+        return randomIntBetween(10, 100);
```
Comment (afoucret) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java:76]: A `0` was stayed in my keyboard.

**Review by kderusso — APPROVED** [review]
Gotta love typos 😁
