### PR TITLE
ESQL: Unmute and fix Avg/Sum tests double precision matchers

### LINKED ISSUE #142037: [CI] AvgTests testGroupingAggregate {TestCase=<random exponential histograms>} failing
**Build Scans:**
- [elasticsearch-intake #34322 / part3](https://gradle-enterprise.elastic.co/s/ox5qk4uq2sh3m)
- [elasticsearch-pull-request #119283 / part-3](https://gradle-enterprise.elastic.co/s/rgt3hleofv7zy)
- [elasticsearch-pull-request #119177 / part-3](https://gradle-enterprise.elastic.co/s/sntg4cqyp6gp6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.aggregate.AvgTests.testGroupingAggregate {TestCase=<random exponential histograms>}" -Dtests.seed=2AE3316A2EEBA29D -Dtests.locale=ja-JP -Dtests.timezone=Asia/Bishkek -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.aggregate.AvgTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGroupingAggregate%20%7BTestCase%3D%3Crandom%20exponential%20histograms%3E%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <-6752.672007491653>
     but: was <-6752.672007491652>
```

**Issue Reasons:**
- [main] 3 failures in test testGroupingAggregate {TestCase=<random exponential histograms>} (1.3% fail rate in 229 executions)
- [main] 2 failures in step part-3 (1.5% fail rate in 136 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 134 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #142068: [CI] AvgTests testAggregateIntermediate {TestCase=<random exponential histograms>} failing
**Build Scans:**
- [elasticsearch-periodic #11853 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/427svfqipshvk)
- [elasticsearch-intake #34250 / part3](https://gradle-enterprise.elastic.co/s/gs3ica4mf34my)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.aggregate.AvgTests.testAggregateIntermediate {TestCase=<random exponential histograms>}" -Dtests.seed=54E0820975890D69 -Dtests.locale=naq -Dtests.timezone=Australia/North -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.aggregate.AvgTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAggregateIntermediate%20%7BTestCase%3D%3Crandom%20exponential%20histograms%3E%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <-10469.46018715665>
     but: was <-10469.460187156652>
```

**Issue Reasons:**
- [main] 2 failures in test testAggregateIntermediate {TestCase=<random exponential histograms>} (0.6% fail rate in 332 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #142081: [CI] SumTests testGroupingAggregate {TestCase=<random exponential histograms>} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11830 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/72x5pvegczllq)
- [elasticsearch-periodic-platform-support #11830 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/lmehvasdtxnrg)
- [elasticsearch-intake #34322 / part3](https://gradle-enterprise.elastic.co/s/ox5qk4uq2sh3m)
- [elasticsearch-pull-request #119283 / part-3](https://gradle-enterprise.elastic.co/s/rgt3hleofv7zy)
- [elasticsearch-pull-request #119177 / part-3](https://gradle-enterprise.elastic.co/s/sntg4cqyp6gp6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.aggregate.SumTests.testGroupingAggregate {TestCase=<random exponential histograms>}" -Dtests.seed=79C175A579AA00F9 -Dtests.locale=de -Dtests.timezone=Chile/Continental -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.aggregate.SumTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGroupingAggregate%20%7BTestCase%3D%3Crandom%20exponential%20histograms%3E%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <4.935163008898125E7>
     but: was <4.935163008898124E7>
```

**Issue Reasons:**
- [main] 2 consecutive failures in step rocky-8_platform-support-unix
- [main] 5 failures in test testGroupingAggregate {TestCase=<random exponential histograms>} (1.8% fail rate in 281 executions)
- [main] 2 failures in step rocky-8_platform-support-unix (66.7% fail rate in 3 executions)
- [main] 2 failures in step part-3 (1.5% fail rate in 137 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 137 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/142037
Fixes https://github.com/elastic/elasticsearch/issues/142068
Fixes https://github.com/elastic/elasticsearch/issues/142081

These tests were enabled and changed here: https://github.com/elastic/elasticsearch/pull/141775
They never ran before, and they are failing sometimes because of double precision issues.

### CODE REVIEW

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/AvgTests.java [hunk 1]
```diff
@@ -187,7 +189,7 @@ private static TestCaseSupplier makeSupplier(TestCaseSupplier.TypedDataSupplier
                 List.of(fieldTypedData),
                 "Avg[field=Attribute[channel=0]]",
                 DataType.DOUBLE,
-                equalTo(expected)
+                expected == null ? nullValue() : closeTo(expected, Math.abs(expected * 1e-10))
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/AvgTests.java:192]: I've had to do this in geospatial tests a lot where we use kahan summation. But when the data range is limited (like geo- lat/lon -180..180) a fixed tolerance makes more sense. When the data range is not limited (eg. max/min float ranges), then a scaled tolerance like you are using here makes more sense.

**Review by craigtaverner — APPROVED** [review]
LGTM, but do check that the numerical ranges used in the test are unlimited, otherwise consider a fixed tolerance.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/AvgTests.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/AvgTests.java:192]: These functions generate expected values based on random data. So yes, unlimited in this case
