### PR TITLE
Fix windows service tests

### LINKED ISSUE #113160: [CI] WindowsServiceTests test30StartStop failing
**Build Scans:**
- [elasticsearch-periodic-packaging #3759 / windows-2022_packaging-tests-windows](https://gradle-enterprise.elastic.co/s/j5arrkc34ujzy)
- [elasticsearch-pull-request #31803 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/fvkeaywpjcwhu)
- [elasticsearch-pull-request #31815 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/cqnf36r2txkp6)
- [elasticsearch-pull-request #31809 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/c6he7om74na4g)
- [elasticsearch-pull-request #31803 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/igjdaqqcfcvwc)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test30StartStop'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.WindowsServiceTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 5 failures in test test30StartStop (4.3% fail rate in 115 executions)
- [main] 4 failures in step windows-2019_default-windows-archive_packaging-tests-windows-sample (4.0% fail rate in 99 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (3.0% fail rate in 100 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #113177: [CI] WindowsServiceTests test33JavaChanged failing
**Build Scans:**
- [elasticsearch-periodic-packaging #3764 / windows-2022_packaging-tests-windows](https://gradle-enterprise.elastic.co/s/orzv3nqgsgh6u)
- [elasticsearch-pull-request #31882 / windows-2022_default-windows-archive_packaging-tests-windows](https://gradle-enterprise.elastic.co/s/7ohjm6reujgk6)
- [elasticsearch-pull-request #31881 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/6cwflfu3mflj6)
- [elasticsearch-pull-request #31876 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/trlrlgcirvwva)
- [elasticsearch-pull-request #31865 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/77gvrmetpuen2)
- [elasticsearch-pull-request #31862 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/arh6rtq7v2bum)
- [elasticsearch-pull-request #31857 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/ylfo4jri6cir4)
- [elasticsearch-pull-request #31855 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/qa6z4doae5pbi)
- [elasticsearch-pull-request #31846 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/xwelc6av55edm)
- [elasticsearch-pull-request #31833 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/zvuiapmhzxcws)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test33JavaChanged'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.WindowsServiceTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.RuntimeException: java.io.IOException: could not remove the following files (in the order of attempts):
   C:\tmp\elasticsearch\jdk.copy\bin\extnet.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\extnet.dll
   C:\tmp\elasticsearch\jdk.copy\bin\java.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\java.dll
   C:\tmp\elasticsearch\jdk.copy\bin\java.exe: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\java.exe
   C:\tmp\elasticsearch\jdk.copy\bin\jimage.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\jimage.dll
   C:\tmp\elasticsearch\jdk.copy\bin\jli.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\jli.dll
   C:\tmp\elasticsearch\jdk.copy\bin\jsvml.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\jsvml.dll
   C:\tmp\elasticsearch\jdk.copy\bin\le.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\le.dll
   C:\tmp\elasticsearch\jdk.copy\bin\management.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\management.dll
   C:\tmp\elasticsearch\jdk.copy\bin\management_ext.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\management_ext.dll
   C:\tmp\elasticsearch\jdk.copy\bin\msvcp140.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\msvcp140.dll
   C:\tmp\elasticsearch\jdk.copy\bin\net.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\net.dll
   C:\tmp\elasticsearch\jdk.copy\bin\nio.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\nio.dll
   C:\tmp\elasticsearch\jdk.copy\bin\server\jvm.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\server\jvm.dll
   C:\tmp\elasticsearch\jdk.copy\bin\server: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\jdk.copy\bin\server
   C:\tmp\elasticsearch\jdk.copy\bin\sunmscapi.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\sunmscapi.dll
   C:\tmp\elasticsearch\jdk.copy\bin\vcruntime140.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\vcruntime140.dll
   C:\tmp\elasticsearch\jdk.copy\bin\vcruntime140_1.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\vcruntime140_1.dll
   C:\tmp\elasticsearch\jdk.copy\bin\verify.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\verify.dll
   C:\tmp\elasticsearch\jdk.copy\bin\zip.dll: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\jdk.copy\bin\zip.dll
   C:\tmp\elasticsearch\jdk.copy\bin: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\jdk.copy\bin
   C:\tmp\elasticsearch\jdk.copy\lib\modules: java.nio.file.FileSystemException: C:\tmp\elasticsearch\jdk.copy\lib\modules: The process cannot access the file because it is being used by another process
   C:\tmp\elasticsearch\jdk.copy\lib: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\jdk.copy\lib
   C:\tmp\elasticsearch\jdk.copy: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\jdk.copy

```

**Issue Reasons:**
- [main] 10 failures in test test33JavaChanged (10.0% fail rate in 100 executions)
- [main] 8 failures in step windows-2019_default-windows-archive_packaging-tests-windows-sample (9.2% fail rate in 87 executions)
- [main] 9 failures in pipeline elasticsearch-pull-request (10.1% fail rate in 89 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #113219: [CI] WindowsServiceTests test80JavaOptsInEnvVar failing
**Build Scans:**
- [elasticsearch-periodic-packaging #3769 / windows-2016_packaging-tests-windows](https://gradle-enterprise.elastic.co/s/c3f53cw6x3cqm)
- [elasticsearch-pull-request #32028 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/l5zfkgyebhtmc)
- [elasticsearch-pull-request #32027 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/yoduafmn7ntim)
- [elasticsearch-pull-request #32026 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/ky7dizuy2inys)
- [elasticsearch-pull-request #32011 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/yhptpuqnefw5u)
- [elasticsearch-pull-request #32003 / windows-2022_default-windows-archive_packaging-tests-windows](https://gradle-enterprise.elastic.co/s/2aiwd5qpyqnd4)
- [elasticsearch-pull-request #32002 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/sqmujogdves3a)
- [elasticsearch-pull-request #31990 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/6hhrurawrzpiu)
- [elasticsearch-pull-request #31925 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/qkm2zagmeefce)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test80JavaOptsInEnvVar'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.WindowsServiceTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 4 consecutive failures in test test80JavaOptsInEnvVar
- [main] 3 consecutive failures in step windows-2019_default-windows-archive_packaging-tests-windows-sample
- [main] 3 consecutive failures in pipeline elasticsearch-pull-request
- [main] 9 failures in test test80JavaOptsInEnvVar (8.2% fail rate in 110 executions)
- [main] 7 failures in step windows-2019_default-windows-archive_packaging-tests-windows-sample (7.4% fail rate in 94 executions)
- [main] 8 failures in pipeline elasticsearch-pull-request (8.3% fail rate in 96 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #113313: [CI] WindowsServiceTests test81JavaOptsInJvmOptions failing
**Build Scans:**
- [elasticsearch-periodic-packaging #3784 / windows-2016_packaging-tests-windows](https://gradle-enterprise.elastic.co/s/gf75sks5dic2u)
- [elasticsearch-pull-request #32304 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/hsfuad6aqwqdu)
- [elasticsearch-pull-request #32287 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/mdizf5rhsish2)
- [elasticsearch-pull-request #32276 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/32wfrebf7ymna)
- [elasticsearch-pull-request #32260 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/r4aob3zcvfnlu)
- [elasticsearch-pull-request #32249 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/3x3d7v5qtpzcg)
- [elasticsearch-pull-request #32228 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/t3kfweiow6m4y)
- [elasticsearch-pull-request #32223 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/xkmecyedkciuo)
- [elasticsearch-pull-request #32190 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/5fyb2xsy5wevg)
- [elasticsearch-pull-request #32187 / windows-2019_default-windows-archive_packaging-tests-windows-sample](https://gradle-enterprise.elastic.co/s/nqwcbxylkmae4)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test81JavaOptsInJvmOptions'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.WindowsServiceTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 24 failures in test test81JavaOptsInJvmOptions (15.5% fail rate in 155 executions)
- [main] 23 failures in step windows-2019_default-windows-archive_packaging-tests-windows-sample (16.2% fail rate in 142 executions)
- [main] 23 failures in pipeline elasticsearch-pull-request (16.4% fail rate in 140 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
This PR attempts to fix (definitely) Windows services tests.

We used `procrun` as a service control tool; however, `procrun` (as a service) suffers from a race condition _and_ `procrun` as a tool seems to suffer from it. 
Furthermore, the implementation of `stop` in `procrun` is (at the very least), "strange": it seems to wait for he service to stop, but it's not guaranteed to wait till the end, returning an error (potentially)
In general, this is true for all (most) of the service control tools: the return when the service is still in a STOP_PENDING state. We actually have to "busy wait" for the service to be really STOPPED.

This PR adds the busy wait and adjusts how we stop the service slightly. It also moves to the standard Windows `sc.exe` tool for service control operations (`start`, `stop` and `delete`) in tests.

Fixes: https://github.com/elastic/elasticsearch/issues/113177
  Fixes: https://github.com/elastic/elasticsearch/issues/113160
  Fixes: https://github.com/elastic/elasticsearch/issues/113219
  Fixes: https://github.com/elastic/elasticsearch/issues/113313

### CODE REVIEW

File: qa/packaging/src/test/java/org/elasticsearch/packaging/test/WindowsServiceTests.java [hunk 1]
```diff
@@ -53,6 +66,29 @@ private void assertService(String id, String status) {
         assertThat(result.stdout(), containsString("Status      : " + status));
     }
 
+    private void waitForStop(String id, Duration timeout) {
```
Comment (rjernst) [inline qa/packaging/src/test/java/org/elasticsearch/packaging/test/WindowsServiceTests.java:69]: Should we consider replacing the service control calls in the windows service cli with sc.exe calls (and this wait in stop)? Then these changes could benefit users too, not just tests.

**Comment by ldematte** [comment]
This is the race condition in procrun:

In a normal execution, the thread serving the stop request and the thread doing/waiting for the JNI "stop" operation generate a reasonable sequence of SetServiceStatus calls:
```
[2025-10-31 14:14:16] [debug] ( javajni.c:1169) [ 3748] apxJavaWait -> WaitForSingleObject (0x0000000000000274, 60000 milliseconds) (-1=INFINITE)...
[2025-10-31 14:14:26] [debug] ( javajni.c:1094) [ 3244] Java worker thread finished org/elasticsearch/launcher/CliToolLauncher:close with status = 0
[2025-10-31 14:14:26] [debug] ( prunsrv.c:1184) [ 1036] reportServiceStatusE: dwCurrentState = 3 (SERVICE_STOP_PENDING), dwWin32ExitCode = 0, dwWaitHint = 60000 milliseconds, dwServiceSpecificExitCode = 0.
[2025-10-31 14:14:26] [debug] ( javajni.c:1172) [ 3748] apxJavaWait <- WaitForSingleObject (0x0000000000000274, 60000 milliseconds) = 0
[2025-10-31 14:14:26] [debug] ( prunsrv.c:1347) [ 3748] Java JNI stop worker finished.
[2025-10-31 14:14:26] [debug] ( prunsrv.c:1443) [ 3748] Waited 10563 timeout (60000)
[2025-10-31 14:14:26] [debug] ( prunsrv.c:1184) [ 3748] reportServiceStatusE: dwCurrentState = 3 (SERVICE_STOP_PENDING), dwWin32ExitCode = 0, dwWaitHint = 49437 milliseconds, dwServiceSpecificExitCode = 0.
[2025-10-31 14:14:26] [debug] ( prunsrv.c:2020) [ 1036] JVM destroyed.
[2025-10-31 14:14:26] [debug] ( prunsrv.c:1184) [ 1036] reportServiceStatusE: dwCurrentState = 1 (SERVICE_STOPPED), dwWin32ExitCode = 0, dwWaitHint = 0 milliseconds, dwServiceSpecificExitCode = 0.
[2025-10-31 14:14:26] [info]  ( prunsrv.c:2060) [11432] Run service finished.
[2025-10-31 14:14:26] [info]  ( prunsrv.c:1482) [ 3748] Service stop thread completed.
[2025-10-31 14:14:26] [info]  ( prunsrv.c:2320) [11432] Apache Commons Daemon procrun finished.
```
In many executions however the thread handling the stop request overlaps with the other threads, trying to re-set the status "back":
```
[2025-10-31 14:14:57] [debug] ( javajni.c:1169) [10748] apxJavaWait -> WaitForSingleObject (0x00000000000002AC, 60000 milliseconds) (-1=INFINITE)...
[2025-10-31 14:15:07] [debug] ( javajni.c:1094) [12720] Java worker thread finished org/elasticsearch/launcher/CliToolLauncher:close with status = 0
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1184) [ 2832] reportServiceStatusE: dwCurrentState = 3 (SERVICE_STOP_PENDING), dwWin32ExitCode = 0, dwWaitHint = 60000 milliseconds, dwServiceSpecificExitCode = 0.
[2025-10-31 14:15:07] [debug] ( javajni.c:1172) [10748] apxJavaWait <- WaitForSingleObject (0x00000000000002AC, 60000 milliseconds) = 0
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1347) [10748] Java JNI stop worker finished.
[2025-10-31 14:15:07] [debug] ( prunsrv.c:2020) [ 2832] JVM destroyed.
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1184) [ 2832] reportServiceStatusE: dwCurrentState = 1 (SERVICE_STOPPED), dwWin32ExitCode = 0, dwWaitHint = 0 milliseconds, dwServiceSpecificExitCode = 0.
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1443) [10748] Waited 10735 timeout (60000)
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1184) [10748] reportServiceStatusE: dwCurrentState = 3 (SERVICE_STOP_PENDING), dwWin32ExitCode = 0, dwWaitHint = 49265 milliseconds, dwServiceSpecificExitCode = 0.
[2025-10-31 14:15:07] [info]  ( prunsrv.c:2060) [ 4192] Run service finished.
[2025-10-31 14:15:07] [error] ( prunsrv.c:1207) [10748] Failed to set service status.
[2025-10-31 14:15:07] [error] ( prunsrv.c:1207) [10748] The handle is invalid.
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1461) [10748] Waiting for worker to die naturally...
[2025-10-31 14:15:07] [debug] ( prunsrv.c:1472) [10748] Worker finished gracefully in 0 milliseconds.
[2025-10-31 14:15:07] [info]  ( prunsrv.c:1482) [10748] Service stop thread completed.
[2025-10-31 14:15:07] [info]  ( prunsrv.c:2320) [ 4192] Apache Commons Daemon procrun finished.
```
Notice the `SERVICE_STOP_PENDING` after `SERVICE_STOPPED`.

This does not seem to have a visible effect; Windows recognizes the service has stopped, and invalidated the handle to it.  However if it turns out that it does have bad effects we can fix it (feel free to ping me)

File: qa/packaging/src/test/java/org/elasticsearch/packaging/test/WindowsServiceTests.java (hunk 1 above)
Comment (ldematte) [reply qa/packaging/src/test/java/org/elasticsearch/packaging/test/WindowsServiceTests.java:69]: I raised this question on the slack thread too :)
I think this is a good idea, but I'd prefer to be sure. 
My proposal is to make these changes in tests, then let them run for a week or so. If the issue is definitely fixed, we can either use `sc.exe` in most of the ProcrunCommands, or consider replacing them with direct calls to Win32 functions (should be rather easy, and would make the code for wait a lot nicer -- no external script needed).

**Review by rjernst — APPROVED** [review]
LGTM
