### PR TITLE
Execute lazy rollover with an internal dedicated user  #104732

### LINKED ISSUE #104732: Lazy rollover causes writes to fail if writer lacks `manage` index privilege
### Elasticsearch Version

8.13.0-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

After a lazy rollover, document writes will start failing if the writer lacks index management privileges. This means that lazy rollover is not transparent to writers, and requires additional privileges of writers when compared to synchronous rollover.

### Steps to Reproduce

```
ELASTICSEARCH_URL=http://admin:changeme@localhost:9200

# Create a data stream.
curl -XPUT $ELASTICSEARCH_URL/_data_stream/logs-rollover-bug

# Rollover the data stream lazily.
curl -XPOST $ELASTICSEARCH_URL/logs-rollover-bug/_rollover?lazy

# Create an API Key that can only auto_configure (create on index) data streams, and create documents. This matches what Fleet configures for Elastic Agent.
API_KEY=$(curl -XPOST -H Content-Type:application/json $ELASTICSEARCH_URL/_security/api_key --data-binary '{
  "name": "writer-key",
  "expiration": "1d",   
  "role_descriptors": { 
    "writer": {
      "indices": [
        {
          "names": ["logs-*"],
          "privileges": ["auto_configure", "create_doc"]
        }
      ]
    }
  }
}' | jq -r .encoded)

# Attempt to index a document. This will fail with an error about the `indices:admin/rollover` action.
curl -XPOST -H "Authorization: ApiKey $API_KEY" -H Content-Type:application/json $ELASTICSEARCH_URL/logs-rollover-bug/_doc --data '{"@timestamp": "2024-01-25"}'
```

### Logs (if relevant)

`{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/rollover] is unauthorized for API key id [pdmdP40BivS0Pj5zQ7AE] of user [admin] on indices [logs-rollover-bug], this action is granted by the index privileges [manage_follow_index,manage,all]"}],"type":"security_exception","reason":"action [indices:admin/rollover] is unauthorized for API key id [pdmdP40BivS0Pj5zQ7AE] of user [admin] on indices [logs-rollover-bug], this action is granted by the index privileges [manage_follow_index,manage,all]"},"status":403}`

### PR DESCRIPTION
**Pull request by gmarouli**
As reported in #104732, currently if the user indexing in a data stream doesn't have the permission to rollover the data stream, the lazy rollover will fail the indexing of the document when it's time to rollover.

In this we are introducing a dedicated internal user to execute this rollover so it's not limited by the privileges of the user is indexing the document that triggers this lazy rollover.

Triggered by this issue, we propose that the lazy rollover does not perform a stats request. This will make the rollover action more light weight and it will not burden too much the bulk request that triggered it.

Fixes #104732

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+    private AutoRolloverAction() {
+        super(NAME);
+    }
+
+    @Override
+    public String name() {
+        return NAME;
+    }
+
+    public static final class TransportAction extends TransportRolloverAction {
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java:50]: Can you call this `TransportAutoRolloverAction` so that it's class name gives a little more indication when searching for it?

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 2]
```diff
@@ -579,7 +589,7 @@ void createIndex(String index, boolean requireDataStream, TimeValue timeout, Act
     void rolloverDataStream(String dataStream, TimeValue timeout, ActionListener<RolloverResponse> listener) {
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:589]: Super minor, but should we rename this to `autoRolloverDataStream` to indicate that it's only for automatic rollovers?

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+                client,
+                allocationService,
+                metadataDataStreamsService
+            );
+        }
+
+        @Override
+        protected void masterOperation(
+            Task task,
+            RolloverRequest rolloverRequest,
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java:81]: Should we add a check (not just an assert, but maybe an actual exception check) that the `rolloverRequest` doesn't have any conditions here? I think it might be a good sanity check.

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 4]
```diff
@@ -579,7 +589,7 @@ void createIndex(String index, boolean requireDataStream, TimeValue timeout, Act
...
         RolloverRequest rolloverRequest = new RolloverRequest(dataStream, null);
         rolloverRequest.masterNodeTimeout(timeout);
-        client.execute(RolloverAction.INSTANCE, rolloverRequest, listener);
+        client.execute(AutoRolloverAction.INSTANCE, rolloverRequest, listener);
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:592]: Can you add a comment above this line about why this uses `AutoRolloverAction` instead of the regular `RolloverAction`? (I want to avoid it getting accidentally undone or misunderstood in the future)

**Review by dakrone — APPROVED** [review]
I think this looks good to me, I left some comments but they're mostly naming or doc things. How did we decide on `auto_configure` being the correct role? Is that one we are certain our internal uses will have?

**Comment by axw** [comment]
> In this PR we want to use the auto_configure privilege to allow users to index even when the data stream requires a rollover without being able to directly rollover the index.

Is it necessary to require _any_ additional privileges for the writer? As I said on Slack:

> I would think intuitively that the user that initiated the lazy rollover (i.e. invoked _rollover?lazy) has implicitly granted permission for any writer
>
> put another way: I don't think a lazy rollover should change the privileges required by a writer

Although this change would work for Elastic Agent and APM, it still means that other writers that do _not_ have `auto_configure` would be broken if another service started calling `_rollover?lazy` instead of `_rollover`. Is that desirable?

**Review by andreidan — APPROVED** [review]
This looks good to me too Mary. Thanks for fixing this.

**Comment by gmarouli** [comment]
> Although this change would work for Elastic Agent and APM, it still means that other writers that do _not_ have `auto_configure` would be broken if another service started calling `_rollover?lazy` instead of `_rollover`. Is that desirable?

Good point, we need to add some documentation in the lazy rollover. The `auto_configure` is an existing privilege that is being used when we auto create an index or a data stream, I think it's reasonable to require the same one for rollover since it is a creating a new index. But it should be explicitly mentioned. 

Does this address your concern @axw ?

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java (hunk 3 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java:81]: Since this is an internal operation I am thinking of using an `IllegalStateException`.

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java:81]: > Update: maybe even better create a new Request for this that only accepts a target name.

This won't work because we are extending the `TransportRolloverAction`.

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/AutoRolloverAction.java:81]: So going back to:
- asserting that the request does not set parameters that shouldn't be set (to inform the dev in time)
- create a new request when submitting the rollover task and that ensures that the rollover will happen.

**Comment by axw** [comment]
>> Although this change would work for Elastic Agent and APM, it still means that other writers that do not have auto_configure would be broken if another service started calling _rollover?lazy instead of _rollover. Is that desirable?
>
> Good point, we need to add some documentation in the lazy rollover. The auto_configure is an existing privilege that is being used when we auto create an index or a data stream, I think it's reasonable to require the same one for rollover since it is a creating a new index. But it should be explicitly mentioned.
>
> Does this address your concern @axw ?

Not really. It's not a practical issue for me or Elastic Agent, more of an "in principle this seems wrong" kind of thing. So I'll leave it to you all, but I'll try to explain my concern again with a hypothetical scenario:

---

Let's say you have thousands of agents that write data to a data stream in Elasticsearch. These agents have just one index privilege, `create_doc`. They cannot auto-create data streams; this is left to a central process. The data stream is using an index template managed by a bundled IndexTemplateRegistry.

On upgrade to 8.13, there's a change to the index template and so a rollover is automatically performed. In this hypothetical scenario https://github.com/elastic/elasticsearch/issues/104083 has been resolved, and the rollover is performed with `?lazy`. Now all of a sudden those thousands of agents cannot index any documents, and they need to have their privileges updated to include `auto_configure`.

---

Why should we require additional privileges for those writers? They didn't ask for the rollover to happen, and the initiator of the rollover has already been authorised. The initiator is giving its consent for the next write to roll over the data stream on its behalf.

**Comment by gmarouli** [comment]
@dakrone do we have any history with this? I do understand @axw concern. Should we then reduce the writes to whoever can execute a `create_doc`?

**Comment by dakrone** [comment]
> Why should we require additional privileges for those writers? They didn't ask for the rollover to happen, and the initiator of the rollover has already been authorised. The initiator is giving its consent for the next write to roll over the data stream on its behalf.

This is correct. The lazy rollover should be completely transparent to whoever is indexing documents (within reason, when we hit things like the cluster shard max that's not a security issue). Any validation of roles and permissions should happen on the call to `POST /<index>/_rollover?lazy`. I don't think we necessarily need to have additional permission checking during the rollover, but instead perform it with something akin to our `OriginSettingClient` instances, which we use internally when we do super-user-y things internally.

**Comment by gmarouli** [comment]
> I don't think we necessarily need to have additional permission checking during the rollover, but instead perform it with something akin to our `OriginSettingClient` instances, which we use internally when we do super-user-y things internally.

I will look into this!

**Comment by gmarouli** [comment]
I will work on the test failures, the problem is with the way I mock the client in the test not with the code itself as far as I understand.

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 5]
```diff
@@ -82,24 +84,28 @@
 public class TransportBulkAction extends HandledTransportAction<BulkRequest, BulkResponse> {
 
     private static final Logger logger = LogManager.getLogger(TransportBulkAction.class);
+    public static final String LAZY_ROLLOVER_ORIGIN = "lazy_rollover";
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:87]: I think this can be private?

**Review by dakrone — APPROVED** [review]
I think this LGTM assuming CI is happy, thanks Mary!

**Comment by axw** [comment]
Thank you for fixing this, and for the change to not require additional privileges! :heart:

**Comment by gmarouli** [comment]
> Thank you for fixing this, and for the change to not require additional privileges! ❤️


Thank YOU for challenging this, I didn't know we did this so I learnt something new!

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java (hunk 5 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:87]: It has to be public to be accessible from `org.elasticsearch.xpack.security.authz.AuthorizationUtils`, in this class we pair it with the internal user.
