### PR TITLE
Fix node health-check-related test failures

### LINKED ISSUE #59172: [CI] FollowersCheckerTests#testFailsNodeThatIsUnhealthy fails on master
**Build scan**:
https://gradle-enterprise.elastic.co/s/uwmxo33dnzojo

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.FollowersCheckerTests.testFailsNodeThatIsUnhealthy" \
  -Dtests.seed=2C28E5E8C9CA7F3B \
  -Dtests.security.manager=true \
  -Dtests.locale=en-ZA \
  -Dtests.timezone=Etc/GMT+7 \
  -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: "health check failed"
     but: was "followers check retry count exceeded"
	at __randomizedtesting.SeedInfo.seed([2C28E5E8C9CA7F3B:EF7745CE84E82FC0]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.cluster.coordination.FollowersCheckerTests.lambda$testBehaviourOfFailingNode$19(FollowersCheckerTests.java:363)
	at org.elasticsearch.cluster.coordination.FollowersChecker$FollowerChecker$2.run(FollowersChecker.java:370)
	at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:133)
	at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:127)
	at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:77)
	at org.elasticsearch.cluster.coordination.FollowersCheckerTests.testBehaviourOfFailingNode(FollowersCheckerTests.java:372)
	at org.elasticsearch.cluster.coordination.FollowersCheckerTests.testFailsNodeThatIsUnhealthy(FollowersCheckerTests.java:310)
```

### LINKED ISSUE #59252: FsHealthServiceTests » testLoggingOnHungIO fails on windows builds
**Build scan**:
https://gradle-enterprise.elastic.co/s/hpdyjffydv7om
**Repro line**:
```
gradlew ':server:test' --tests "org.elasticsearch.monitor.fs.FsHealthServiceTests.testLoggingOnHungIO" -Dtests.seed=3C203AA224C46D04 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Asia/Famagusta -Druntime.java=11
```
**Reproduces locally?**:
Windows, so unknown
**Applicable branches**:
master
**Failure history**:

This has been happening for a few days now

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.monitor.fs.FsHealthServiceTests%22%20AND%20test:%22testLoggingOnHungIO%22'),sort:!(time,asc))
**Failure excerpt**:

```
Suite: Test class org.elasticsearch.monitor.fs.FsHealthServiceTests
  1> [2020-07-08T21:11:01,327][INFO ][o.e.e.NodeEnvironment    ] [testLoggingOnHungIO] using [2] data paths, mounts [[(C:)]], net usable_space [282.6gb], net total_space [349.9gb], types [NTFS]
  1> [2020-07-08T21:11:01,327][INFO ][o.e.e.NodeEnvironment    ] [testLoggingOnHungIO] heap size [512mb], compressed ordinary object pointers [true]
  2> REPRODUCE WITH: gradlew ':server:test' --tests "org.elasticsearch.monitor.fs.FsHealthServiceTests.testLoggingOnHungIO" -Dtests.seed=3C203AA224C46D04 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Asia/Famagusta -Druntime.java=11  2> 
  2> java.lang.AssertionError: expected:<2> but was:<0>
        at __randomizedtesting.SeedInfo.seed([3C203AA224C46D04:76E1FC3AF7C253C5]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.monitor.fs.FsHealthServiceTests.testLoggingOnHungIO(FsHealthServiceTests.java:164)
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
In #52680 we introduced a new health check mechanism. This commit fixes
up some sporadic related test failures, and improves the behaviour of
the `FollowersChecker` slightly in the case that no retries are
configured.

Closes #59252
Closes #59172

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/coordination/FollowersChecker.java [hunk 1]
```diff
@@ -327,16 +327,16 @@ public void handleException(TransportException exp) {
                         failureCountSinceLastSuccess++;
 
                         final String reason;
-                        if (failureCountSinceLastSuccess >= followerCheckRetryCount) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/FollowersChecker.java:330]: We should check the failure count last so we can report more specific errors (`disconnected` etc) if available.

File: server/src/test/java/org/elasticsearch/monitor/fs/FsHealthServiceTests.java [hunk 2]
```diff
@@ -325,7 +324,7 @@ public FileChannel newFileChannel(Path path, Set<? extends OpenOption> options,
                 @Override
                 public void force(boolean metaData) throws IOException {
                     if (injectIOException.get()) {
-                        if (path.toString().startsWith(pathPrefix) && path.toString().endsWith(".es_temp_file")) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/monitor/fs/FsHealthServiceTests.java:328]: No need to check the path starts with `/` and, indeed, it doesn't on Windows.

**Review by ywelsch — APPROVED** [review]
LGTM
