### PR TITLE
[Test] Skip testDelayWithALargeAmountOfShards on Windows

### LINKED ISSUE #137384: [CI] ClusterRerouteIT testDelayWithALargeAmountOfShards failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11354 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/wvdanb5osotly)
- [elasticsearch-periodic-platform-support #11346 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ejlnoztstlkuc)

**Reproduction Line:**
```
gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards" -Dtests.seed=A74D9E2714A276E9 -Dtests.locale=lo-Laoo-LA -Dtests.timezone=Atlantic/Madeira -Druntime.java=25
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.allocation.ClusterRerouteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDelayWithALargeAmountOfShards'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state
```

**Issue Reasons:**
- [8.19] 2 failures in test testDelayWithALargeAmountOfShards (2.9% fail rate in 69 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Windows can sometimes be slow at handling the large number of cluster state updates.

Resolves: #137384

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/allocation/ClusterRerouteIT.java [hunk 1]
```diff
@@ -199,6 +200,7 @@ public void testRerouteWithAllocateLocalGateway_enableAllocationSettings() throw
     }
 
     public void testDelayWithALargeAmountOfShards() throws Exception {
+        assumeFalse("Windows can be too slow on handling larget amount of cluster state updates", Constants.WINDOWS);
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/allocation/ClusterRerouteIT.java]: As [commented](https://github.com/elastic/elasticsearch/issues/137384#issuecomment-3470761846) on the issue, one alternative is to extend the timeout on Windows. But it's already 2min and I don't particularly like to increase it more and it does not feel all that useful to keep the test for Windows either.

**Review by DaveCTurner — COMMENTED** [review]
Hmm I think I'd rather wait longer in this case. 2 minutes seems like a long time but it's still kinda arbitrary to fail the test if the worker is even slower than that, and equally arbitrary to exclude a whole platform from some tests just for this reason.

**Comment by ywangd** [comment]
Sure I pushed 77d30eee39911b4e48c01461ab120b78b0b8e074 to double the waiting time on Windows.

**Review by DaveCTurner — APPROVED** [review]
LGTM tho an indefinite wait (on all platforms) would also be fine.

**Comment by ywangd** [comment]
> tho an indefinite wait (on all platforms) would also be fine.

Noted. Will go for this option if it ends up failing again.
