### PR TITLE
permit at+jwt typ header value in jwt access tokens

### LINKED ISSUE #119370: Support `at+jwt` Types in JWT Realm
### Description

Some JWT providers (e.g. logto.io) only provie Access Token JWTs with a `typ` of `at+jwt`, but Elasticsearch currently only supports JWT `typ`es of `JWT` in the JWT Realm for authentication.

Attempting to connect with such Access Token JWTs in Elasticsearch results in:

> Caused by java.lang.IllegalArgumentException: invalid jwt typ header; Caused by com.nimbusds.jose.proc.BadJOSEException: JOSE header typ (type) at+jwt not allowed

It may be that a custom JWT Decoder needs to be included in a SecurityFilterChain (or similar, depending upon how Elasticsearch implements such security), similar to the approach suggested for Spring applicaitons in https://github.com/logto-io/logto/blob/master/packages/console/src/assets/docs/guides/api-spring-boot/README.mdx

### PR DESCRIPTION
**Pull request by richard-dennehy**
Resolves https://github.com/elastic/elasticsearch/issues/119370

Permit `at+jwt` `typ` header values when parsing Access tokens, as required by [RFC 9068](https://datatracker.ietf.org/doc/html/rfc9068#section-2.1).

We continue to accept `typ` = `JWT` or `null` to maintain backwards compatibility.

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtTypeValidator.java [hunk 1]
```diff
@@ -17,14 +17,20 @@
 
 public class JwtTypeValidator implements JwtFieldValidator {
 
-    private static final JOSEObjectTypeVerifier<SecurityContext> JWT_HEADER_TYPE_VERIFIER = new DefaultJOSEObjectTypeVerifier<>(
+    private final JOSEObjectTypeVerifier<SecurityContext> JWT_HEADER_TYPE_VERIFIER;
+
+    public static final JwtTypeValidator ID_TOKEN_INSTANCE = new JwtTypeValidator(JOSEObjectType.JWT, null);
+
+    // strictly speaking, this should only permit `at+jwt`, but removing the other two options is a breaking change
+    public static final JwtTypeValidator ACCESS_TOKEN_INSTANCE = new JwtTypeValidator(
```
Comment (richard-dennehy) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtTypeValidator.java:25]: split validator into 2, as we don't want to allow `at+jwt` for ID tokens

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtTypeValidator.java [hunk 2]
```diff
@@ -17,14 +17,20 @@
...
         JOSEObjectType.JWT,
+        new JOSEObjectType("at+jwt"),
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/jwt/JwtTypeValidator.java:27]: Nit: let's make this a private constant

**Review by n1v0lg — APPROVED** [review]
LGTM 🚀 

For additional functional coverage, I'd also tweak one of our JWT REST tests ([here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/security/qa/jwt-realm/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/jwt/JwtRestIT.java#L827-L829)) to randomly set a `at+jwt` header -- provided that it's an application token JWT. This will take a bit of tweaking to the method signature, i.e., something like a boolean flag `allowAtJwtType`. 

Let's also open a backport to 8.19.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/jwt/JwtTypeValidatorTests.java [hunk 3]
```diff
@@ -19,30 +19,53 @@
...
         } catch (Exception e) {
             throw new AssertionError("validation should have passed without exception", e);
         }
     }
 
     public void testInvalidType() throws ParseException {
+        final JwtTypeValidator validator = randomFrom(JwtTypeValidator.ID_TOKEN_INSTANCE, JwtTypeValidator.ACCESS_TOKEN_INSTANCE);
 
         final JWSHeader jwsHeader = JWSHeader.parse(
             Map.of("typ", randomAlphaOfLengthBetween(4, 8), "alg", randomAlphaOfLengthBetween(3, 8))
```
[the remark this answers is not in the document]
Comment (richard-dennehy) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/jwt/JwtTypeValidatorTests.java:64]: turns out the parser ignores case - I've added `AT+JWT` to the success test case instead
