### PR TITLE
Address test bug in testOptionalColumnAtATimeReaderBinary

### LINKED ISSUE #139432: [CI] ES819TSDBDocValuesFormatTests testOptionalColumnAtATimeReaderBinary failing
**Build Scans:**
- [elasticsearch-intake #32268 / part1](https://gradle-enterprise.elastic.co/s/3vrhhp6xuurkq)
- [elasticsearch-intake #32267 / part1](https://gradle-enterprise.elastic.co/s/2d76kjcmrfhpe)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.codec.tsdb.es819.ES819TSDBDocValuesFormatTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testOptionalColumnAtATimeReaderBinary'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.ClassCastException: class org.apache.lucene.util.BytesRef cannot be cast to class java.util.List (org.apache.lucene.util.BytesRef is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')
```

**Issue Reasons:**
- [main] 2 consecutive failures in step part1
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 2 failures in test testOptionalColumnAtATimeReaderBinary (0.8% fail rate in 263 executions)
- [main] 2 failures in step part1 (5.9% fail rate in 34 executions)
- [main] 2 failures in pipeline elasticsearch-intake (5.9% fail rate in 34 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by martijnvg**
Closes #139432

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesFormatTests.java [hunk 1]
```diff
@@ -1313,7 +1313,7 @@ public void testOptionalColumnAtATimeReaderBinary() throws Exception {
                         random().nextBoolean(),
                         null,
                         false,
-                        useCustomBinaryFormat
+                        true
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesFormatTests.java]: This shouldn't be randomized because this field is always in custom binary format.

**Review by parkertimmins — APPROVED** [review]

**Review by salvatore-campagna — APPROVED** [review]

**Comment by martijnvg** [comment]
Test failure is unrelated.
