### PR TITLE
ESQL: Fix for overzealous validation in case of invalid mapped fields

### LINKED ISSUE #111452: ESQL: unexpected verification_exception for same field name in two indices (union types)
### Description

test1 index

```
{
    "mappings": {
        "properties": {
            "x": {
                "type": "keyword"
            }
        }
    }
}
```

test2 index

```
{
    "mappings": {
        "properties": {
            "x": {
                "type": "long"
            },
            "whatever": {
                "type": "text"
            }
        }
    }
}
```

`from test* | rename whatever as foo` results in 

```
     "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:1: Cannot use field [x] due to ambiguities being mapped as [2] incompatible types: [keyword] in [test1], [long] in [test2]",
        "stack_trace": "org.elasticsearch.xpack.esql.VerificationException: Found 1 problem\nline 1:1: Cannot use field [x] due to ambiguities being mapped as [2] incompatible types: [keyword] in [test1], [long] in [test2]
```

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/111452

https://github.com/elastic/elasticsearch/pull/107545 postpones some of the validation for fields that occur in multiple indices with different types. Such fields must not be explicitly used in the query.

The validation now happens [after the main reference resolution](https://github.com/elastic/elasticsearch/pull/107545/files#diff-2c689d9c0606d310fd36a603064f43cb4b23d356f08983fbdb98c65e76e6919dR1187-R1192). This is problematic for renames in particular. Consider a field `a` that has the same type in all indices:
```
FROM idx | RENAME a AS b
```
is perfectly valid. But after reference resolution, the `RENAME` becomes a `PROJECT` that has to list _all_ fields that it will output. If there is a `field` that is `keyword` in `index1` but `ip` in `index2`, we have the following
```
FROM idx | PROJECT field, a AS b
```
Performing the validation _now_ gives wrong results, because it sees `field` and flags it as invalid; `field` was not used explicitly, but ended up in the plan due to replacing `RENAME` by a `PROJECT`.

~~This PR reverts to the original approach: during the initial resolution in `ResolveRefs`, we immediately validate usage of a field attribute referring to a multi-typed field. Usage is considered valid if the attribute is either used inside a conversion function, like `TO_IP`, or if the attribute is being dropped.~~

**Updated with another approach**: This PR now aligns how we treat multi-typed fields with how we treat unsupported field types. The latter are already being passed through and are even allowed to be mentioned explicitly in `KEEP`, ~~`RENAME`~~ and `DROP`. To achieve this, rather than mapping `FieldAttribute`s containing an `InvalidMappedField` to `UnresolvedAttribute` - which the verifier finds and counts as invalid query - we map such field attributes to `UnsupportedAttribute`, which is what fields with unsupported types are also being mapped to.

To avoid weird workarounds when resolving `STATS`, type resolution for convert functions becomes more lenient, so that multi-typed field attributes (`FieldAttribute` containing an `InvalidMappedField`) are considered resolved as long as all of the mapped types are supported by the convert function; e.g. `TO_IP(client_ip)` in case `client_ip` is mapped as both `keyword` and `ip`.

### CODE REVIEW

**Comment by alex-spies** [comment]
The current version now reverts back to how we validated multi-typed fields before we added union types:
- While resolving refs, we try to map unresolved attributes to field attributes.
- If we find one, but it contains an `InvalidMappedField`, we'll generally not resolve this, causing a validation error if someone explicitly uses multi-typed fields,
- unless the multi-typed field is inside a conversion function like `to_string`, or if it's inside a `DROP`.

This should be correct from the get-go because it performs the resolution and validation directly on the _parsed_ logical plan, rather than after the plan has already been altered by resolution steps.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -874,8 +904,19 @@ private static List<Attribute> potentialCandidatesIfNoMatchesFound(
...
+            var field = fa.field();
+            // Multi-typed fields are allowed if and only if we convert them to a single type immediately.
+            if (field instanceof InvalidMappedField imf && (parent instanceof AbstractConvertFunction == false)) {
+                resolveTo = toResolve.withUnresolvedMessage(
+                    "Cannot use field [" + fa.name() + "] due to ambiguities being " + imf.errorMessage()
+                );
+            }
+        }
+
+        return resolveTo.withLocation(toResolve.source());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:919]: `handleSpecialFields` used to look for FieldAttributes mapped with multiple types before https://github.com/elastic/elasticsearch/pull/107545. This brings back this logic, but takes into account the attribute's parent because multi-typed FieldAttributes are allowed if they're immediately cast.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/TypeResolutions.java [hunk 2]
```diff
@@ -176,19 +177,35 @@ public static TypeResolution isType(
...
-                    e.dataType().typeName()
-                )
-            );
+        if (predicate.test(e.dataType()) || e.dataType() == NULL) {
+            return TypeResolution.TYPE_RESOLVED;
+        }
+
+        if (e instanceof FieldAttribute fa && fa.field() instanceof InvalidMappedField imf) {
+            return new TypeResolution(errorStringIncompatibleTypes(operationName, paramOrd, name(e), imf.errorMessage(), acceptedTypes));
+        }
```
Comment (alex-spies) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/TypeResolutions.java:186]: This improves error messages for failed type resolutions in case of union types, see yaml tests.

**Comment by alex-spies** [comment]
I took a new approach today; this should be closer to what we already had, because it uses the pass-through mechanism that we have in place for fields with unsupported data types (passed through as `null`s). It also avoids any changes to `Node`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 3]
```diff
@@ -1067,24 +1068,19 @@ public static Expression castStringLiteral(Expression from, DataType target) {
                     target,
                     e.getMessage()
                 );
-                return new UnsupportedAttribute(
-                    from.source(),
-                    String.valueOf(from.fold()),
-                    new UnsupportedEsField(String.valueOf(from.fold()), from.dataType().typeName()),
-                    message
-                );
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1075]: Unrelated, but maybe it's better not to fake an ES field here, `UnresolvedAttribute` seems to do the trick as well.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 4]
```diff
@@ -1120,24 +1116,6 @@ private LogicalPlan doRule(LogicalPlan plan) {
...
-                // Aggregates where the grouping key comes from a union-type field need to be resolved against the grouping key
-                Map<Attribute, Expression> resolved = new HashMap<>();
-                for (Expression e : agg.groupings()) {
-                    Attribute attr = Expressions.attribute(e);
-                    if (attr != null && attr.resolved()) {
-                        resolved.put(attr, e);
-                    }
-                }
-                plan = plan.transformExpressionsOnly(UnresolvedAttribute.class, ua -> resolveAttribute(ua, resolved));
-            }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1139]: This may have been already obsolete; in any case, there shouldn't be a need to special-case aggs while resolving union types.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 5]
```diff
@@ -1264,7 +1230,14 @@ public LogicalPlan apply(LogicalPlan plan) {
...
                 String unresolvedMessage = "Cannot use field [" + fa.name() + "] due to ambiguities being " + imf.errorMessage();
-                return new UnresolvedAttribute(fa.source(), fa.name(), fa.qualifier(), fa.id(), unresolvedMessage, null);
+                String types = imf.getTypesToIndices().keySet().stream().collect(Collectors.joining(","));
+                return new UnsupportedAttribute(
+                    fa.source(),
+                    fa.name(),
+                    new UnsupportedEsField(imf.getName(), types),
+                    unresolvedMessage,
+                    fa.id()
+                );
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:1240]: This is the crux of the fix.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 6]
```diff
@@ -461,7 +460,9 @@ private LogicalPlan resolveStats(Stats stats, List<Attribute> childrenOutput) {
             if (stats.expressionsResolved() == false) {
                 AttributeMap<Expression> resolved = new AttributeMap<>();
                 for (Expression e : groupings) {
-                    Attribute attr = Expressions.attribute(e);
+                    // In case of union types, the expression may contain yet-to-be resolved conversion functions, so do not perform a
+                    // type check here.
+                    Attribute attr = Expressions.attributeUnchecked(e);
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:465]: Oh no, forcing a reference attribute here is also wrong, because in case of truly unresolved expressions, calling `.datatype()` is wrong. I'll figure out a way around this.

[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:465]: Thanks for the explanation - replace the Alias logic here; if it's an alias , return a ReferenceAttribute otherwise call toAttribute().
This gets rid of the attributeUnchecked() method

**Review by costin — CHANGES_REQUESTED** [review]
Thanks for moving this forward Alex - great stuff.
Don't generalize toAttributeUnchecked - rather perform the Alias over unresolved into the stats resolution.
I wonder though if this can occur in other places where we have named union types..

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/NamedExpression.java [hunk 7]
```diff
@@ -55,8 +55,18 @@ public boolean synthetic() {
...
+     * Try to return either {@code this} if it is an {@link Attribute}, or a {@link ReferenceAttribute} to it otherwise.
+     * Return an {@link UnresolvedAttribute} if this is unresolved.
+     */
     public abstract Attribute toAttribute();
 
+    /**
+     * Return either {@code this} if it is an {@link Attribute}, or a {@link ReferenceAttribute} to it otherwise.
+     * Do not return an {@link UnresolvedAttribute} if this is unresolved.
+     */
+    public abstract Attribute toAttributeUnchecked();
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/NamedExpression.java:68]: Yeah, I think this needs to go; I think I found a better way: be more precise in how we perform the resolution of the aggregates in `resolveStats` based on the already resolved groupings.

[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/NamedExpression.java]: Nevermind; I had to go another route after all. I _wanted_ to only resolve the aggregates if the groups could be resolved - but that created wrong error messages, as resolvable aggregates were treated as unresolvable.

**Comment by alex-spies** [comment]
One more approach that seems to solve the problems when resolving aggregates:
Consider expressions like `TO_IP(client_ip)` _resolved_ when `client_ip` is a multi-typed field attribute whose types can all be used in `TO_IP`. Considering it unresolved caused issues when trying to resolve `STATS` and `INLINESTATS`, which would've been hacky to work around; considering `TO_IP(client_ip)` resolved is conceptually cleaner, as we _know_ this is valid.

**Review by astefan — COMMENTED** [review]
I think it's ok to allow these unsupported fields in `keep` and `rename` (`drop` was already allowed) but we need to be careful to the conceptual side effects (I don't know if there are any yet) meaning we must have a good story around allowing unsupported data types in these additional commands. So far, we said "this is unsupported, so I want to remove it, `drop` gives me that", so what's the argument for `keep` and especially `rename`?

I've tested various things:

1.
```
        "properties": {
            "x": {
                "type": "text"
            },
            "flatx": {
                "type": "flattened"
            } 
        }
```
`from test | rename flatx as whatever`

results in 
```
"Cannot invoke \"org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()\" because the return value of \"org.elasticsearch.xpack.esql.planner.Layout.get(org.elasticsearch.xpack.esql.core.expression.NameId)\" is null"
```
which is **the same behavior in `main` and in this PR**.

2. `FROM sample_data, sample_data_str | rename client_ip as foo | sort bla`

results in

```
path: /_query, params: {format=txt, error_trace=true}, status: 500 org.elasticsearch.xpack.esql.core.capabilities.UnresolvedException: Invalid call to dataType on an unresolved object ?bla
        at org.elasticsearch.xpack.esql.core.expression.UnresolvedAttribute.dataType(UnresolvedAttribute.java:101)
        at org.elasticsearch.xpack.esql.core.expression.Attribute.canonicalize(Attribute.java:146)
        at org.elasticsearch.xpack.esql.core.expression.Expression.canonical(Expression.java:161)
        at org.elasticsearch.xpack.esql.core.expression.Expressions.canonicalize(Expressions.java:96)
        at org.elasticsearch.xpack.esql.core.expression.Expression.canonicalize(Expression.java:170)
        at org.elasticsearch.xpack.esql.core.expression.Expression.canonical(Expression.java:161)
        at org.elasticsearch.xpack.esql.core.expression.ExpressionSet.add(ExpressionSet.java:81)
        at org.elasticsearch.xpack.esql.optimizer.rules.PruneRedundantSortClauses.rule(PruneRedundantSortClauses.java:24)
        at org.elasticsearch.xpack.esql.optimizer.rules.PruneRedundantSortClauses.rule(PruneRedundantSortClauses.java:17)
```

which is **the same behavior in `main` and in this PR**.

3. `FROM sample_data, sample_data_str | rename client_ip as foo` which is more relevant to this PR:

**in main** `"Cannot use field [client_ip] due to ambiguities being mapped as [2] incompatible types: [ip] in [sample_data], [keyword] in [sample_data_str]"`

**in PR** 

```
"Cannot invoke \"org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()\" because the return value of \"org.elasticsearch.xpack.esql.planner.Layout.get(org.elasticsearch.xpack.esql.core.expression.NameId)\" is null"
```

**Comment by alex-spies** [comment]
`FROM sample_data, sample_data_str | rename client_ip as foo` excellent find @astefan (How could I miss that..).

The error message that this yields

```
"Cannot invoke \"org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()\" because the return value of \"org.elasticsearch.xpack.esql.planner.Layout.get(org.elasticsearch.xpack.esql.core.expression.NameId)\" is null"
```

is consistent with what you get when you rename a field of unsupported type; in your example, that'd be
```
from test | rename flatx as foo
```

I'll try to improve that; renaming should be okay for both or have a nice error message for both. I'm leaning towards error message, because otherwise users might wanna do `FROM idx | RENAME multi_typed_field AS foo | EVAL foo = to_ip(foo)`.

The argument for allowing multi-typed field in more places, i.e. `KEEP`, is that we should not be _more_ restrictive with multi-typed fields than with fields of unsupported types. Mapping `FieldAttribute`s containing `InvalidMappedField`s (i.e. union type fields) to `UnsupportedAttribute` forces consistency for these two kinds of fields.

In particular, `KEEP flatx` is allowed in your example. And allowing this is _important_ because on main, `KEEP *x` _fails_ which is a bad UX imho - I wanna be able to `KEEP` a bunch of fields matching a wildcards; if this accidentally includes a couple multi-typed fields, I as a user won't care so much; but having to explicitly `DROP` them before the `KEEP` is inconvenient, and it's inconsistent because it's not needed for fields of unsupported type, like `flatx`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 8]
```diff
@@ -458,17 +456,17 @@ private LogicalPlan resolveStats(Stats stats, List<Attribute> childrenOutput) {
                 }
             }
 
-            if (stats.expressionsResolved() == false) {
-                AttributeMap<Expression> resolved = new AttributeMap<>();
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:462]: The role of AttributeMap is to guarantee equality - while it can deal with ordering (it's a linkedmap), it's better to have this recorded elsewhere such as a list.

**Comment by costin** [comment]
> So far, we said "this is unsupported, so I want to remove it, drop gives me that", so what's the argument for keep and especially rename?

Unsupported fields are allowed to pass through. With keep we allow for the them to be retained, with drop to be discarded and with rename to change their alias. All valid sub-cases of projection.
However unsupported fields cannot be manipulated.

> FROM idx | RENAME multi_typed_field AS foo | EVAL foo = to_ip(foo)

Can the query be written differently to not throw an error? Is the issue EVAL or RENAME?

**Comment by alex-spies** [comment]
> with drop to be discarded and with rename to change their alias. All valid sub-cases of projection.
However unsupported fields cannot be manipulated.

That's all true except for `RENAME`; this currently does not work with unsupported types in main (layout errors). We can fix it or forbid it. In any case, I'd like to do the same for multi-typed fields and fields of unsupported type for consistency.

> `FROM idx | RENAME multi_typed_field AS foo | EVAL foo = to_ip(foo)`
> Can the query be written differently to not throw an error? Is the issue EVAL or RENAME?

This can be simply written as `FROM idx | EVAL foo = to_ip(multi_typed_field)`. As of now, the problem is the layout issue with RENAME used on unsupported attributes; but even if fixed, it'd be a bit of additional work to ensure renaming a multi-typed field _and then_ using a conversion function on it is properly supported - at the very least we'd need to add good tests.

**Comment by alex-spies** [comment]
Found a fix for `RENAME unsupported AS foo` which also fixes `RENAME multi_typed_field AS foo`. It required creating reference attributes from aliases even if the child expression is not fully resolved - which is exactly the case for `UnsupportedAttribute`, which is considered unresolved, but its type is resolved (to `UNSUPPORTED`).

@costin @astefan let's discuss whether we want to allow `RENAME` for unsupported/multi types before moving on with this fix.

(Side note: maybe the verification step could be simplified if we didn't consider `UnsupportedAttribute` as unresolvable. I suspect that the mechanism that allows passing through unsupported types could be simpler if we shifted the responsibility to the type resolution step only, i.e. don't fail a query just because we see an `UnsupportedAttribute`, but fail it when this is used in a place that requires something other than the `UNSUPPORTED` data type. It would prevent having to change `Alias.toAttribute` as well.)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/local/EsqlProject.java [hunk 9]
```diff
@@ -65,8 +66,12 @@ public EsqlProject replaceChild(LogicalPlan newChild) {
...
     public boolean expressionsResolved() {
         for (NamedExpression projection : projections()) {
-            // don't call dataType() - it will fail on UnresolvedAttribute
-            if (projection.resolved() == false && projection instanceof UnsupportedAttribute == false) {
+            // Pass through for unsupported types.
+            if (projection instanceof UnsupportedAttribute
+                || (projection instanceof Alias a && a.child() instanceof UnsupportedAttribute)) {
+                continue;
+            }
+            if (projection.resolved() == false) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/local/EsqlProject.java:74]: @astefan this fixes validation for the query `FROM sample_data, sample_data_str | rename client_ip as foo | sort bla` (very good find!).

If we're happy with the current approach, I'll add a verifier test for it.

**Comment by alex-spies** [comment]
@astefan found another nice edge case:

```
// client_ip is mapped as ip and keyword
FROM sample_data, sample_data_str | rename client_ip as foo | sort foo
```
In the current state of the PR, this actually computes, while
```
FROM sample_data, sample_data_str | sort client_ip
```
Correctly returns a validation error. The same is true when we replace the `sort` by an `mv_expand`.

This indicates that allowing to `RENAME my_unsupported_field AS foo` will require more work because we'll at least have to carefully re-check the validation and add additional tests.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:461]: Ah, fair point; however, there shouldn't be groupings with same name id but different names, so the `mergeOutputAttributes` below should take care of deduplicating fine.

I think using the `AttributeMap` here is less obvious (I completely forgot the thing preserves iteration order), esp. since an `AttributeSet` seems to suffice.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec [hunk 10]
```diff
@@ -1015,3 +1015,256 @@ client_ip:ip | event_duration:long |    message:keyword    |    @timestamp:keywo
...
+;
+
+multiIndexIndirectUseOfUnionTypesInWildcardKeep2
+// TODO: `union_types` is required only because this makes the test skip in the csv tests; better solution:
+// make the csv tests work with multiple indices.
+required_capability: union_types
+required_capability: union_types_fix_rename_resolution
+FROM sample_data, sample_data_ts_long
+// This is not allowed because it implicitly uses @timestamp, which is a multi-typed field.
+// It probably should be! Otherwise we're inconsistent with `KEEP *`.
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec:1097]: Is this comment still applicable?

**Review by astefan — APPROVED** [review]
LGTM 👍

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec (hunk 10 above)
Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/union_types.csv-spec:1097]: Good catch, thank you!

**Review by costin — APPROVED** [review]
👍

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec [hunk 11]
```diff
@@ -2018,6 +2018,19 @@ M
 null
 ;
 
+shadowingInternalWithGroup2#[skip:-8.14.1,reason:implemented in 8.14]
```
Comment (bpintea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:2021]: I guess this is not related, but good to add a shadowing test within the groups in particular.

Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:2021]: This could've tripped due to the logic in the resolution of STATS, which _didn't look_ like it correctly tracks the order of the groups. Turns out it did, because `AttributeMap` uses a `LinkedHashMap` internally; but better to have something to guard against regressions.

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/111735)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
