### PR TITLE
Run CheckIndex on metadata index before loading

### LINKED ISSUE #29358: Enhance BufferedChecksumIndexInput error when a state file is empty
**Elasticsearch version** (`bin/elasticsearch --version`): Any version

**Plugins installed**: [none]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Any

**Provide logs (if relevant)**:

If a state file is empty after some issue (hardware issue, NFS issue and others) a node will fail to start and we will see something like the following in the logs:

```
[2018-04-03T18:12:25,227][ERROR][o.e.g.GatewayMetaState   ] [xxxx] failed to read local state, exiting...
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:20, legacy:false, file:/xxx/elasticsearch/xxx/xxx/nodes/0/indices/indexname/_state/state-20.st]
	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:150) ~[elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:334) ~[elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.util.IndexFolderUpgrader.upgrade(IndexFolderUpgrader.java:90) ~[elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.util.IndexFolderUpgrader.upgradeIndicesIfNeeded(IndexFolderUpgrader.java:128) ~[elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87) [elasticsearch-5.4.3.jar:5.4.3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_161]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_161]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:176) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:43) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.node.Node.<init>(Node.java:491) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.node.Node.<init>(Node.java:242) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:350) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.4.3.jar:5.4.3]
Caused by: java.io.IOException: failed to read [id:20, legacy:false, file:/xxx/elasticsearch/xxx/xxx/nodes/0/indices/indexname/_state/state-20.st]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:327) ~[elasticsearch-5.4.3.jar:5.4.3]
	... 37 more
Caused by: java.lang.IllegalStateException: class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)
	at org.apache.lucene.store.ChecksumIndexInput.seek(ChecksumIndexInput.java:50) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
	at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:519) ~[lucene-core-6.5.1.jar:6.5.1 cd1f23c63abe03ae650c75ec8ccb37762806cc75 - jimczi - 2017-04-21 12:17:15]
	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:189) ~[elasticsearch-5.4.3.jar:5.4.3]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:322) ~[elasticsearch-5.4.3.jar:5.4.3]
	... 37 more
```

Discussing it with @jpountz , `(pos=-16 getFilePointer()=0)` seems to indicate that the file is empty, but so far we return a `IOException` without explaining that a state file is empty. 

So my question here is:

1. Does it make sense to add some extra content to the log to explicitly mention that the file is empty?
2. Perhaps we can mention in the logs that when this happens the shards get corrupted and you need to recreate it (or remove it)?
3. Do we see any other option than [2]? For example starting the node and have an option to disregard that shard (possibly delete it?- yes doesn't sounds like a very good idea, but worth discussing it).

### PR DESCRIPTION
**Pull request by DaveCTurner**
The metadata index is small and important and only read at startup.
Today we rely on Lucene to spot if any of its components is corrupt, but
Lucene does not necesssarily verify all checksums in order to catch a
corruption. With this commit we run `CheckIndex` on the metadata index
first, and fail on startup if a corruption is detected.

Closes #29358

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 1]
```diff
@@ -291,17 +295,45 @@ public static void overrideVersion(Version newVersion, Path... dataPaths) throws
...
+                            checkIndex.setChecksumsOnly(true);
+                            isClean = checkIndex.checkIndex().clean;
+                        }
 
-                if (nodeId.equals(onDiskState.nodeId) == false) {
-                    throw new IllegalStateException("unexpected node ID in metadata, found [" + onDiskState.nodeId +
-                        "] in [" + dataPath + "] but expected [" + nodeId + "]");
+                        if (isClean == false) {
+                            if (logger.isErrorEnabled()) {
+                                outputStream.bytes().utf8ToString().lines().forEach(l -> logger.error("checkIndex: {}", l));
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:323]: This isn't great: we materialise all the bytes, then convert them to a string, and then split them into lines. A streaming implementation is definitely possible but doesn't seem worth the effort here.

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 2]
```diff
@@ -291,17 +295,46 @@ public static void overrideVersion(Version newVersion, Path... dataPaths) throws
...
+                            }
+                            throw new IllegalStateException("metadata index at [" + dataPath +
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:325]: We often refer to this as either cluster state or global state. I wonder if we could call it `global state metadata index`, just to be sure this message is interpreted correctly by operators?

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java [hunk 3]
```diff
@@ -291,17 +295,46 @@ public static void overrideVersion(Version newVersion, Path... dataPaths) throws
...
+                                "] has been changed by an external force after it was last written by Elasticsearch and is now unreadable");
+                        }
+                    }
+                }
+
+                try (DirectoryReader directoryReader = DirectoryReader.open(directory)) {
+                    onDiskState = loadOnDiskState(dataPath, directoryReader);
+
+                    if (nodeId.equals(onDiskState.nodeId) == false) {
+                        throw new IllegalStateException("unexpected node ID in metadata, found [" + onDiskState.nodeId +
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:335]: Same comment on `metadata` as above, perhaps `global state metadata`?

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java:323]: Agreed.

**Review by henningandersen — COMMENTED** [review]
This looks good. I wonder if we want a tool that reads the state without check index and rewrites it fully? Perhaps an option to the "unsafe bootstrap master" tool?

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java]: _Cluster state_ includes the metadata contained in this index but also includes ephemeral things like the routing table; conversely the metadata in this index comprises _global_ metadata and _index_ metadata. "Metadata index" is more correct than either, but I tried a few ideas and settled on `the index containing the cluster metadata`, see 95378d23f4ea9c56c29d4fe3eecd45010871d336.

File: server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java]: You had to be doing something pretty weird to hit this message anyway, and doubly so today since the node IDs that we're comparing both come from the user-data from the latest commit of this index. Harmonised with the other message in 9e89fed6f2b2628d1ac09af6f631639ee05364ef.

**Comment by DaveCTurner** [comment]
> I wonder if we want a tool that reads the state without check index and rewrites it fully?

I have my doubts that we could implement such a thing robustly enough to be useful. I ran the corruption test 2000 times and saw only 44 cases (<2.5%) in which the state was readable after corruption anyway. Of course this test makes a pretty small state so the chances of hitting something vital with a one-byte error are maximised, but even so many of the exceptions seen are failures to parse a document in the index. Conversely in reality a corruption likely hits multiple bytes, perhaps even a whole disk sector at once, so I reckon we'd not be able to read the state in almost every case.

With a larger state there's a better chance that there are multiple segments, so `CheckIndex#exorciseIndex` might yield something useful, but I still think the probability of success is very low.

We could also perhaps extract the global metadata from an otherwise-broken index with slightly higher probability since we always write it first so it should be near the start of the stored fields of whichever segment it's in, and then we could fall back on dangling indices to recover the index metadata. This all seems overly heroic tho, I'd rather not go down this path.

**Review by henningandersen — APPROVED** [review]
LGTM.
