### PR TITLE
Validate the `_rollover` target index name early to also fail if dry_run=true

### LINKED ISSUE #21149: Rollover API: indicate failure in dry run if an index already exists
**Elasticsearch version**: 5.0.0

**Description of the problem including expected versus actual behavior**:
When executing `_rollover?dry_run`, check for the existence of `new_index` and indicate if a rollover is expected to succeed or fail according to known conditions at execution time.

**Steps to reproduce**:
1. Setup an index for rollover
2. Create an empty index having a name matching the next `new_index` after rollover
3. Execute `_rollover?dry_run`.
4. Execute `_rollover`.

```
GET packetbeat/_aliases
{
  "packetbeat-000004": {
    "aliases": {
      "packetbeat": {}
    }
  }
}
```

```
PUT packetbeat-000005
{
  "acknowledged": true,
  "shards_acknowledged": true
}
```

Normally this is a 7 day rollover. Set it to 0 day (or remove the condition entirely) to just execute it:

```
POST packetbeat/_rollover?dry_run
{
  "conditions": {
    "max_age": "0d"
  }
}

{
  "old_index": "packetbeat-000004",
  "new_index": "packetbeat-000005",
  "rolled_over": false,
  "dry_run": true,
  "acknowledged": false,
  "shards_acknowledged": false,
  "conditions": {
    "[max_age: 0s]": true
  }
}
```

I would have expected the dry run to indicate failure.

The actual rollover fails as expected:

```
POST packetbeat/_rollover
{
  "conditions": {
    "max_age": "0d"
  }
}

{
  "error": {
    "root_cause": [
      {
        "type": "index_already_exists_exception",
        "reason": "index [packetbeat-000005/0FDcEuIQTh6lVvD-l7lkxg] already exists",
        "index_uuid": "0FDcEuIQTh6lVvD-l7lkxg",
        "index": "packetbeat-000005"
      }
    ],
    "type": "index_already_exists_exception",
    "reason": "index [packetbeat-000005/0FDcEuIQTh6lVvD-l7lkxg] already exists",
    "index_uuid": "0FDcEuIQTh6lVvD-l7lkxg",
    "index": "packetbeat-000005"
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by s1monw**
Today we validate the target index name late and therefore don't fail for instance
if the target index already exists and `dry_run=true` was specified. This change
validates the index name before we early terminate if dry_run is set.

Closes #21149

### CODE REVIEW

**Comment by s1monw** [comment]
@clintongormley FYI

File: core/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java [hunk 1]
```diff
@@ -109,16 +110,18 @@ protected void masterOperation(final RolloverRequest rolloverRequest, final Clus
         final String sourceProvidedName = indexMetaData.getSettings().get(IndexMetaData.SETTING_INDEX_PROVIDED_NAME,
             indexMetaData.getIndex().getName());
         final String sourceIndexName = indexMetaData.getIndex().getName();
+        final String unresolvedName = (rolloverRequest.getNewIndexName() != null)
+            ? rolloverRequest.getNewIndexName()
+            : generateRolloverIndexName(sourceProvidedName, indexNameExpressionResolver);
+        final String rolloverIndexName = indexNameExpressionResolver.resolveDateMathExpression(unresolvedName);
+        MetaDataCreateIndexService.validateIndexName(rolloverIndexName, state); // will fail if the index already exists
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java]: this also validates the index name. Is it worth adding a small test to verify that we don't accept index names that are not valid too?

**Review by javanna — APPROVED** [review]
LGTM besides the minor comment I left

File: rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/10_basic.yaml [hunk 2]
```diff
@@ -102,3 +102,44 @@
...
+  # also do it without dry_run
+  - do:
+      catch: /index_already_exists_exception/
+      indices.rollover:
+        dry_run: false
+        alias: "logs_search"
+        wait_for_active_shards: 1
+        body:
+          conditions:
+            max_docs: 1
```
Comment (javanna) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/10_basic.yaml]: I may not remember correctly but I think the Perl runner needs an empty new line here or it will fail...

Comment (s1monw) [inline rest-api-spec/src/main/resources/rest-api-spec/test/indices.rollover/10_basic.yaml]: we fail too but it passed and I added one... maybe I didn't do a git add... I will check

**Comment by s1monw** [comment]
@javanna pushed a new commit

**Comment by javanna** [comment]
perfect thanks, still LGTM
