### PR TITLE
Restart ES after keystore upgrade in postinst

### LINKED ISSUE #82433: deb package update stop service because it can't create /etc/elasticsearch/elasticsearch.keystore.tmp
**Elasticsearch version** (`bin/elasticsearch --version`):

```
# /usr/share/elasticsearch/bin/elasticsearch --version
Version: 7.16.1, Build: default/deb/5b38441b16b1ebb16a27c107a4c3865776e20c53/2021-12-11T00:29:38.865893768Z, JVM: 17.0.1
```

**Plugins installed**: []

```
# /usr/share/elasticsearch/bin/elasticsearch-plugin list
# echo $?
0
```

**JVM version** (`java -version`):

```
# java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.12+7-post-Debian-2deb10u1, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):

```
# uname -a
Linux acseo-ccimp-www00 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

When `elasticsearch` is update through `apt`, the update fail and the service stop because the write permissions for `/etc/elasticsearch` are incorrect. #41755 didn't solve the issue here because the [`chown` part](https://github.com/elastic/elasticsearch/blob/f1860c17ab4b9e2931a5d7482905fe5f1589239c/distribution/packages/src/common/scripts/postinst#L136-L150) of the `postinst` script is executed after restarting `elasticsearch.service`.  So the restart fail because it's run as `elasctisearch:elasticsearch` which isn't allowed to write in `/etc/elasticsearch` exiting the `postinst` script abruptly (because of `set -e`) cause the `chown` part to never be executed.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Install `elasticsearch` 7.5.0
 2. Make sure `elasticsearch.service` is actually running
 3. Upgrade up-to 7.16.1
 4. The upgrade will fail and `elasticsearch.service` will be stoped.

**Provide logs (if relevant)**:
<details>

```
# zcat /var/log/syslog.20210520.gz | grep -i elasticsearch
[...]
May 20 13:01:25 acseo-ccimp-www00 systemd-tmpfiles[11427]: [/usr/lib/tmpfiles.d/elasticsearch.conf:1] Line references path below legacy directory /var/run/, updating /var/run/elasticsearch → /run/elasticsearch; please update the tmpfiles.d/ drop-in file accordingly.
May 20 21:47:18 acseo-ccimp-www00 systemd[1]: Stopping Elasticsearch...
May 20 21:47:19 acseo-ccimp-www00 systemd[1]: elasticsearch.service: Succeeded.
May 20 21:47:19 acseo-ccimp-www00 systemd[1]: Stopped Elasticsearch.
May 20 21:47:24 acseo-ccimp-www00 systemd[1]: Configuration file /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
May 20 21:47:24 acseo-ccimp-www00 systemd[1]: Configuration file /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
May 20 21:47:39 acseo-ccimp-www00 systemd[1]: Configuration file /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
May 20 21:47:39 acseo-ccimp-www00 systemd[1]: Starting Elasticsearch...
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.elasticsearch.cli.UserException: unable to create temporary keystore at [/etc/elasticsearch/elasticsearch.keystore.tmp], write permissions required for [/etc/elasticsearch] or run [elasticsearch-keystore upgrade]
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/elasticsearch.keystore.tmp
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:484)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:253)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:228)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:343)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.cli.Command.main(Command.java:79)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
May 20 21:47:42 acseo-ccimp-www00 systemd-entrypoint[13008]: #011at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
May 20 21:47:42 acseo-ccimp-www00 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
May 20 21:47:42 acseo-ccimp-www00 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
May 20 21:47:42 acseo-ccimp-www00 systemd[1]: Failed to start Elasticsearch.
May 20 21:47:43 acseo-ccimp-www00 systemd[1]: Configuration file /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
May 20 21:47:44 acseo-ccimp-www00 systemd[1]: Configuration file /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
May 20 21:59:08 acseo-ccimp-www00 systemd[1]: Configuration file /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
May 20 21:59:23 acseo-ccimp-www00 systemd[1]: Starting Elasticsearch...
May 20 21:59:38 acseo-ccimp-www00 systemd[1]: Started Elasticsearch.
[...]

# zcat /var/log/dpkg.log.2.gz | grep elasticsearch:
[...]
2021-05-20 21:47:18 upgrade elasticsearch:amd64 7.12.0 7.12.1
2021-05-20 21:47:18 status half-configured elasticsearch:amd64 7.12.0
2021-05-20 21:47:19 status unpacked elasticsearch:amd64 7.12.0
2021-05-20 21:47:19 status half-installed elasticsearch:amd64 7.12.0
2021-05-20 21:47:23 status unpacked elasticsearch:amd64 7.12.1
2021-05-20 21:47:39 configure elasticsearch:amd64 7.12.1 <none>
2021-05-20 21:47:39 status unpacked elasticsearch:amd64 7.12.1
2021-05-20 21:47:39 status half-configured elasticsearch:amd64 7.12.1
2021-05-20 21:47:43 status installed elasticsearch:amd64 7.12.1
[...]
```

</details>

@jasontedor since you wrote #41755, note the log following log line with `or run [elasticsearch-keystore upgrade]` indicating we are not in the same case as #41726.
```
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.elasticsearch.cli.UserException: unable to create temporary keystore at [/etc/elasticsearch/elasticsearch.keystore.tmp], write permissions required for [/etc/elasticsearch] or run [elasticsearch-keystore upgrade]
```

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #82433. If the environment variable `RESTART_ON_UPGRADE` is
true, then ensure that we delay restarting Elasticseach until after
the keystore is upgraded, or else we can run into permissions
problems.

Note that this issue only appears to manifest pre-8.0. I was unable
to replicate it in an 8.2 snapshot debian package, which I attributed
to the security-by-default work. I will still forward-port the
changes in case of regressions.

### CODE REVIEW

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DebPreservationTests.java [hunk 1]
```diff
@@ -90,4 +93,31 @@ public void test30Purge() throws Exception {
...
+        sh.run("systemctl daemon-reload");
+        sh.run("systemctl enable elasticsearch.service");
+        sh.run("systemctl start elasticsearch.service");
+
+        final JournaldWrapper journaldWrapper = new JournaldWrapper(sh);
+        sh.getEnv().put("RESTART_ON_UPGRADE", "true");
+        installation = installPackage(sh, distribution());
+        final String logs = journaldWrapper.getLogs().stdout;
+
+        assertThat(
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DebPreservationTests.java:117]: This seems like an awfully specific assertion. Shouldn't we just assert that ES is successfully running when using that option. That would catch more regressions related to `RESTART_ON_UPGRADE` no?

**Review by mark-vieira — APPROVED** [review]
Let's make the `test40RestartOnUpgrade` a bit more broad and sort out why it's failing in CI obviously. Otherwise, LGTM. Thanks for addressing this.

**Comment by pugnascotia** [comment]
Forward ports:

   * `master` -> fb5b44c522a
   * `8.1` -> b47d0a52593
   * `8.0` -> 801d9ccc7c2
