### PR TITLE
ESQL: Fix error message when failing to resolve aggregate groupings

### LINKED ISSUE #108053: Confusing error message when I have a syntax error on bucket function
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

Trying to write the `bucket` command I had a syntax error. ES returns 2 errors. The first is correct, it describes what I should do to fix the query but the second is wrong as it says that the column doesn't exist. The column exists and if I fix the syntax error the buckets will be created

image (34)

### Steps to Reproduce

Just try to create a syntaxx error on the bucket function. Example:

```
from index  | stats count_distinct(message.keyword) by BUCKET(bytes_gauge, 10)
```

This returns the errors:

```
[esql] > Unexpected error from Elasticsearch: verification_exception - Found 2 problems
line 1:84: function expects exactly four arguments when the first one is of type [LONG] and the second of type [INTEGER]
line 1:64: Unknown column [message.keyword]
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/108053

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -377,9 +377,9 @@ private LogicalPlan resolveAggregate(Aggregate a, List<Attribute> childrenOutput
                 }
             }
 
-            if (a.expressionsResolved() == false && Resolvables.resolved(groupings)) {
+            if (a.expressionsResolved() == false) {
                 AttributeMap<Expression> resolved = new AttributeMap<>();
-                for (Expression e : groupings) {
+                for (Expression e : groupings.stream().filter(Expression::resolved).toList()) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:382]: Use a `for` loop over the groupings with a simple `if` for `Expression::resolved` (instead of the streaming approach), it's a less complex structure.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.14|[](https://github.com/elastic/elasticsearch/pull/108246)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
