### PR TITLE
Fix rollover alias definition in templates validation

### LINKED ISSUE #70258: Rollover fails if legacy template defines rollover alias, even if shadowed by valid composable template
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8 onwards

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
In order to avoid indexing request being rejected, Elasticsearch validates that no index template defines the alias used when rolling over an index. This validation is in place in order to avoid the case where newly created indices will match an index template whose alias contains the rollover alias, in which case the rollover alias would point to multiple indices.

However, if we have a legacy template that defines the rollover alias and a composable template that "overrides" the legacy template and doesn't define the rollover alias, this validation should not be triggered (because the composable template takes precedence over the legacy template and it is valid) 

**Steps to reproduce**:
```
--
PUT _template/legacy
{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  },
  "aliases" : {
    "alias1" : {}
  }
}

--
PUT _index_template/newtemplate
{
  "index_patterns": ["te*", "bar*"],
  "template": {
    "settings": {
      "number_of_shards": 2
    }
  }
}

--
PUT testindex
{
  "aliases": {
    "alias1": {}
  }
}

--
POST alias1/_rollover/testindex-000002
```

Rolling over in this case would yield:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Rollover alias [alias1] can point to multiple indices, found duplicated alias [[alias1]] in index template [legacy]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Rollover alias [alias1] can point to multiple indices, found duplicated alias [[alias1]] in index template [legacy]"
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by andreidan**
This fixes the case where a valid composable template overrides/shadows a
legacy template that defines the rollover alias. This is a valid configuration
and rollover should not fail.

Fixes #70258

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java [hunk 1]
```diff
@@ -391,6 +391,28 @@ public void testRejectDuplicateAliasV2UsingComponentTemplates() {
...
+
+        final Metadata metadata = Metadata.builder().put(createMetadata(randomAlphaOfLengthBetween(5, 7)), false)
+            .put(legacyTemplate).put("composable-template", composableTemplate).build();
+        String indexName = randomFrom("foo-123", "bar-xyz");
+        String aliasName = randomFrom("foo-write", "bar-write");
+        try {
+            MetadataRolloverService.checkNoDuplicatedAliasInIndexTemplate(metadata, indexName, aliasName, randomBoolean());
+            // success
+        } catch (Exception e) {
+            fail("the valid v2 template takes priority over the v1 template. was not expecting a failure but got: " + e.getMessage());
```
Comment (dakrone) [inline server/src/test/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java:412]: We probably don't need to catch this exception, since uncaught exceptions would cause the test to fail anyway. This also swallows the stacktrace which would make it slightly harder to investigate for someone triaging a failure.

**Review by dakrone — APPROVED** [review]
LGTM, I left one minor comment, thanks for fixing this Andrei!
