### PR TITLE
WIP Fix failing Keystore Passphrase test for feature branch

### LINKED ISSUE #50079: Fix problems with KeystoreManagementTests#test51WrongKeystorePasswordFromFile
On the cleaned-up feature branch for the password-protected keystore, there are two problems with one of our packaging tests: first, it fails occasionally, and second, it doesn't clean up after itself when it does, so a bunch of later tests also fail.

It's not yet clear to me why this test fails, but when it does, the stack trace is:

```
java.lang.AssertionError: 

Expected: a string containing "Provided keystore password was incorrect"
     but: was "<<Too large to read: 105340 bytes>>"

at __randomizedtesting.SeedInfo.seed([264C6E7CFA0C535D:F86B07EA259CE6AE]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.packaging.test.PackagingTestCase.assertElasticsearchFailure(PackagingTestCase.java:307)
at org.elasticsearch.packaging.test.KeystoreManagementTests.test51WrongKeystorePasswordFromFile(KeystoreManagementTests.java:247)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:834)
```

Relates #32691

### PR DESCRIPTION
**Pull request by williamrandolph**
On the cleaned-up feature branch for the password-protected keystore, there are two problems with one of our packaging tests: first, it fails occasionally, and second, it doesn't clean up after itself when it does, so a bunch of later tests also fail.

It appears that the issue is that some systems store journald logs in `/run/log/journal` while Fedora and Ubuntu store them in `/var/log/journal`, so our method that clears out the journald logs shoudl clear both locations.

Fixes #50079

### CODE REVIEW

File: qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java [hunk 1]
```diff
@@ -93,7 +93,7 @@ public void test20CreateKeystoreManually() throws Exception {
         String possibleSudo = distribution().isArchive() && Platforms.LINUX
             ? "sudo -u " + ARCHIVE_OWNER + " "
             : "";
-        Shell.Result r = sh.run(possibleSudo + bin.elasticsearchKeystore + " list");
+        Shell.Result r = sh.run(possibleSudo + bin.keystoreTool + " list");
```
Comment (rjernst) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java]: You can use keystoreTool.run like above now right?

File: qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java [hunk 2]
```diff
@@ -192,87 +192,74 @@ public void test50KeystorePasswordFromFile() throws Exception {
...
         Platforms.onLinux(() -> {
-            distribution().packagingConditional()
-                .forPackage(() -> sh.run(bin.elasticsearchKeystore + " create"))
-                .forArchive(() -> sh.run("sudo -u " + ARCHIVE_OWNER + " " + bin.elasticsearchKeystore + " create"))
-                .forDocker(/* TODO */ Platforms.NO_ACTION)
-                .run();
+            switch (distribution.packaging) {
+                case TAR:
+                case ZIP:
+                    sh.run("sudo -u " + ARCHIVE_OWNER + " " + bin.keystoreTool + " create");
```
Comment (rjernst) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java]: I thought I made run so it will do the sudo if necessary, so this should not be necessary and you can run `bin.keystoreTool.run("create")`, in which case I'm not sure we need any of these platform specific blocks?

**Review by rjernst — APPROVED** [review]
LGTM. I think there are several places that can use the `run()` method on the keystore tool Executable.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java (hunk 2 above)
Comment (williamrandolph) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/KeystoreManagementTests.java]: Yep, you're right! I though of that while bringing in the master branch, and now I've followed up on it.

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Packages.java [hunk 3]
```diff
@@ -286,7 +286,7 @@ private static void verifyDefaultInstallation(Installation es) {
      */
     public static void clearJournal(Shell sh) {
         if (isSystemd()) {
-            sh.run("rm -rf /run/log/journal/*");
+            sh.run("rm -rf /run/log/journal/* /var/log/journal/*");
```
Comment (williamrandolph) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/Packages.java]: @rjernst All refactoring aside, here's the one-line fix for the test failure. Does this look OK to you?

Comment (rjernst) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Packages.java]: Yes that seems fine.
