### PR TITLE
Fix potential NPE in SyntheticIdField empty token stream

### LINKED ISSUE #140624: [CI] TSDBSyntheticIdsIT testSyntheticId failing
**Build Scans:**
- [elasticsearch-intake #33229 / part1](https://gradle-enterprise.elastic.co/s/vf4rdrqaexhck)
- [elasticsearch-pull-request #112943 / part-1](https://gradle-enterprise.elastic.co/s/kry6vxild3vp2)
- [elasticsearch-pull-request #112882 / part-1](https://gradle-enterprise.elastic.co/s/tg5d3e5o35dos)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:internalClusterTest" --tests "org.elasticsearch.datastreams.TSDBSyntheticIdsIT.testSyntheticId" -Dtests.seed=B03B3556AC8ACB98 -Dtests.locale=ky-Cyrl-KG -Dtests.timezone=Asia/Hong_Kong -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.TSDBSyntheticIdsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSyntheticId'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.action.NoShardAvailableActionException: null
```

**Issue Reasons:**
- [main] 3 failures in test testSyntheticId (1.5% fail rate in 200 executions)
- [main] 2 failures in step part-1 (1.5% fail rate in 132 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.6% fail rate in 127 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140665: [CI] TSDBSyntheticIdsIT testRecoveredOperations failing
**Build Scans:**
- [elasticsearch-periodic #11733 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/23nwty2dcjucq)
- [elasticsearch-periodic-platform-support #11706 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/c4io5h6vwfjey)
- [elasticsearch-periodic-platform-support #11706 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/shx6eobym3cvu)
- [elasticsearch-pull-request #114268 / part-1](https://gradle-enterprise.elastic.co/s/jwz4g5cdzdhpg)
- [elasticsearch-periodic-platform-support #11706 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/etkxjgrhryqw4)
- [elasticsearch-periodic-platform-support #11701 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/4kyvw35tim7cs)
- [elasticsearch-pull-request #113292 / part-1](https://gradle-enterprise.elastic.co/s/damokyjtiipmg)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:internalClusterTest" --tests "org.elasticsearch.datastreams.TSDBSyntheticIdsIT.testRecoveredOperations" -Dtests.seed=E79B8338799C2C24 -Dtests.jvm.argline="-Des.concurrent_search=true" -Dtests.locale=sr-RS -Dtests.timezone=Europe/Vaduz -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.TSDBSyntheticIdsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRecoveredOperations'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Unexpected ShardFailures: failure in bulk execution:
[0]: index [.ds-ndfrubxth-2026.01.14-000001], id [ORMTxFWLuERcBcn-RcJvY57QOX___mRDK2vvYItx4Q], message [java.lang.NullPointerException: Cannot invoke "org.apache.lucene.util.AttributeImpl.end()" because "state.attribute" is null]
Expected: is <false>
     but: was <true>
```

**Issue Reasons:**
- [main] 2 consecutive failures in step almalinux-8-aarch64_checkpart1_platform-support-arm
- [main] 7 failures in test testRecoveredOperations (2.5% fail rate in 277 executions)
- [main] 2 failures in step part-1 (1.1% fail rate in 180 executions)
- [main] 2 failures in step almalinux-8-aarch64_checkpart1_platform-support-arm (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.1% fail rate in 176 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by fcofdez**
SyntheticIdField uses an empty token stream with no attributes. 
Override #end() to prevent NPE from attribute access in the base implementation.

Closes #140492
Closes #140665
Closes #140624

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java [hunk 1]
```diff
@@ -32,6 +32,11 @@ public final class SyntheticIdField extends Field {
         public boolean incrementToken() {
             return false;
         }
+
+        @Override
+        public void end() {
```
Comment (fcofdez) [inline server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java]: I wonder if we're just accumulating attributes here and it would make more sense to create a new token stream instance per invocation? wdyt? I mention this because this is hard to reproduce, so maybe I'm missing something here.

Comment (tlrx) [reply server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java]: Yes, I think it makes sense to create a new reusable `TokenStream` instance and maybe just call `clearAttributes();` in the reset method.

**Comment by fcofdez** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java (hunk 1 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java]: I see the `clearAttributes()` call in the reset method but do you plan to move to a new instance (non static one)?

Comment (fcofdez) [reply server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java]: I think that I misunderstood your comment, weren't you suggesting to keep the singleton instance and just call `clearAttributes()` on reset so we ensure that we don't keep accumulating them?

Comment (tlrx) [reply server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java]: Sorry if I wasn't clear.

I think we should create a new TokenStream instance instead of using the static one. I think SyntheticIdField#tokenStream could return the `reuse` instance if it is not null. And we can make sure that the reused instance is correctly reset by calling `clearAttributes()` in the reset method.

Something like:
```java

    @Override
    public TokenStream tokenStream(Analyzer analyzer, TokenStream reuse) {
        if (reuse != null) {
            assert reuse instanceof EmptyTokenStream : reuse;
            return reuse; // will be reset before reuse
        }
        return new EmptyTokenStream();
    }

    private static class EmptyTokenStream extends TokenStream {

        @Override
        public void reset() throws IOException {
            super.reset();
            clearAttributes();
        }

        @Override
        public boolean incrementToken() {
            return false;
        }
    }
```

If you also think this is correct.

Comment (fcofdez) [reply server/src/main/java/org/elasticsearch/index/mapper/SyntheticIdField.java]: NP, I've just pushed https://github.com/elastic/elasticsearch/pull/140556/commits/656f6260af5766b7d00446068bacea62193dcebd with the suggested approach. I've kept the `end()` override to avoid potential issues.

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
This will also closes #140665

**Comment by burqen** [comment]
... and https://github.com/elastic/elasticsearch/issues/140624

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
@fcofdez do you plan to unmute the tests from muted-tests.yml too?

**Comment by fcofdez** [comment]
Good call @tlrx 🤦. Let me fix that

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
@elasticmachine update branch
