### PR TITLE
Check bucket metric ages point to a multi bucket agg

### LINKED ISSUE #25775: Cryptic error message for pipeline aggregations based on combination of nested and reverse_nested aggs
ES version **2.4.1**:

Consider the following mapping:

```json
{
    "timestamp_source": {
        "type": "nested",
        "properties": {
            "my_timestamp_1": {
                "type": "date"
            },
            "my_timestamp_2": {
                "type": "date"
            }
        }
    },
    "quantity": {
        "type": "float"
    }
}
```

and the following document:

```json
{
    "timestamp_source": [
        {
            "my_timestamp_1": "2014-05-11T23:52:38+0000",
            "my_timestamp_2": "2015-05-11T23:52:38+0000"
        },
        {
            "my_timestamp_1": "2016-05-11T23:52:38+0000",
            "my_timestamp_2": "2017-05-11T23:52:38+0000"
        }
    ],
    "quantity": 42
}
```

I'm after bucketing the timestamps, summing the quantities and calculating the `avg_bucket`. However the following query fails w/ a cryptic error msg:

```bash
curl -XGET 'localhost:9200/my_index/_search?pretty&size=0' -d '
{
    "query": {
        "match_all": {}
    },
    "aggs": {
        "by_frequency": {
            "nested": {
                "path": "timestamp_source"
            },
            "aggs": {
                "by_frequency": {
                    "date_histogram": {
                        "field": "timestamp_source.my_timestamp_1",
                        "interval": "month",
                        "min_doc_count": 0
                    },
                    "aggs": {
                        "total": {
                            "reverse_nested": {},
                            "aggs": {
                                "total": {
                                    "sum": {
                                        "field": "quantity"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "monthly_average": {
            "avg_bucket": {
                "buckets_path": "by_frequency>by_frequency>total>total",
                "gap_policy": "insert_zeros"
            }
        }
    }
}
'

{
  "error" : {
    "root_cause" : [ ],
    "type" : "reduce_search_phase_exception",
    "reason" : "[reduce] ",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "class_cast_exception",
      "reason" : null
    }
  },
  "status" : 503
}
```

**Actual behaviour**

The error message isn't descriptive enough.

**Expected behaviour**

The 'reason' field explains in more detail the reasons behind failure.

Alternatively (if this query is valid), the query succeeds.

### PR DESCRIPTION
**Pull request by colings86**
This adds a validation step to the BucketMetricsPipelineAggregationBuilder which ensure that the first aggregation in the `buckets_path` is a multi-bucket aggregation. It does this using a new `MultiBucketAggregationBuilder` marker interface.

The change also moves the validate of pipeline aggregations to the `AggregatorFactories.build()` method so the validate can inspect sibling `AggregatorBuilder` objects rather than `AggregatorFactory` objects. Further it removes the validate from `AggregatorFactory` since this was never implemented and since aggregators only depend on their own internal state and not on other aggregators they should be validated ideally at setter time but in rare case where this is not possible the validation should be done in the `AggregationBuilder.build()` step.

Closes #25775

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/BucketMetricsPipelineAggregationBuilder.java [hunk 1]
```diff
@@ -106,12 +109,29 @@ public GapPolicy gapPolicy() {
...
             List<PipelineAggregationBuilder> pipelineAggregatorFactories) {
         if (bucketsPaths.length != 1) {
             throw new IllegalStateException(PipelineAggregator.Parser.BUCKETS_PATH.getPreferredName()
                     + " must contain a single entry for aggregation [" + name + "]");
         }
+        // Need to find the first agg name in the buckets path to check its a
+        // multi bucket agg: aggs are split with '>' and can optionally have a
+        // metric name after them by using '.' so need to split on both to get
+        // just the agg name
+        final String firstAgg = bucketsPaths[0].split(">")[0].split("\\.")[0];
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/BucketMetricsPipelineAggregationBuilder.java]: let's split on both chars at once? `split("[>\\.]")`

**Review by jpountz — APPROVED** [review]
LGTM
