### PR TITLE
TEST: Reenable RemoveCorruptedShardDataCommandIT.testCorruptIndex 

### LINKED ISSUE #36189: [ci] RemoveCorruptedShardDataCommandIT.testCorruptIndex and 3 others
Doesn't repro locally, I'm not sure whether something in the test or the node failing is the root cause here

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu&&virtual/97/console

[build-unix-97.txt.zip](https://github.com/elastic/elasticsearch/files/2641737/build-unix-97.txt.zip)

testCorruptIndex has this in its logging

```
  1> [2018-12-04T11:42:15,394][INFO ][o.e.i.s.RemoveCorruptedShardDataCommandIT] [testCorruptIndex] after test
ERROR   1.71s J5 | RemoveCorruptedShardDataCommandIT.testCorruptIndex <<< FAILURES!
   > Throwable #1: ElasticsearchException[Shard does not seem to be corrupted at /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/ubuntu&&virtual/server/build/testrun/integTest/J5/temp/org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT_7292077B46A25BBF-001/tempDir-002/data/nodes/0/indices/-LSNcjAZQ0uqCXST_25kNA/0]
   >    at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.lambda$execute$1(RemoveCorruptedShardDataCommand.java:347)
   >    at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.findAndProcessShardPath(RemoveCorruptedShardDataCommand.java:202)
   >    at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.execute(RemoveCorruptedShardDataCommand.java:282)
   >    at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT$2.onNodeStopped(RemoveCorruptedShardDataCommandIT.java:192)
   >    at org.elasticsearch.test.InternalTestCluster$NodeAndClient.closeForRestart(InternalTestCluster.java:917)
   >    at org.elasticsearch.test.InternalTestCluster.restartNode(InternalTestCluster.java:1689)
   >    at org.elasticsearch.test.InternalTestCluster.restartNode(InternalTestCluster.java:1649)
   >    at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT.testCorruptIndex(RemoveCorruptedShardDataCommandIT.java:188)
   >    at java.lang.Thread.run(Thread.java:748)
```

All the tests have this in their logging

```
java.lang.RuntimeException: already closed
   >    at org.elasticsearch.test.InternalTestCluster$NodeAndClient.client(InternalTestCluster.java:849)
   >    at org.elasticsearch.test.InternalTestCluster.client(InternalTestCluster.java:703)
   >    at org.elasticsearch.test.ESIntegTestCase.client(ESIntegTestCase.java:641)
   >    at org.elasticsearch.test.ESIntegTestCase.client(ESIntegTestCase.java:634)
   >    at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:553)
   >    at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2191)
   >    at java.lang.Thread.run(Thread.java:748)
```

```
./gradlew :server:integTest -Dtests.seed=7292077B46A25BBF -Dtests.class=org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT -Dtests.method="testCorruptIndex" -Dtests.security.manager=true -Dtests.locale=ko-KR -Dtests.timezone=Pacific/Tarawa -Dcompiler.java=11 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* Merging the `zen2` branch has made it impossible to reproduce the test failure here, likely as a result of the state now being written atomically
* Closes #36189

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/gateway/MetaDataStateFormat.java [hunk 1]
```diff
@@ -255,58 +255,70 @@ long findMaxStateId(final String prefix, Path... locations) throws IOException {
...
+                } catch (NoSuchFileException | FileNotFoundException e) {
+                    // A state file was deleted by a concurrent process so the files list is not correct any longer
+                    // and we have to start over and fetch the list of state files again
+                    logger.debug(
+                        () -> new ParameterizedMessage(
+                            "{}: failed to read [{}] because it was deleted by a concurrent action, retrying...",
+                            pathAndStateId.file.toAbsolutePath(), prefix
+                        ), e
+                    );
+                    continue RETRY_LOOP;
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/gateway/MetaDataStateFormat.java]: I know continuing a named loop is kinda dirty here, but with the way we collect exceptions and such it seemed like the cleanest/shortest way to add a retry.

File: server/src/main/java/org/elasticsearch/gateway/MetaDataStateFormat.java [hunk 2]
```diff
@@ -255,58 +255,70 @@ long findMaxStateId(final String prefix, Path... locations) throws IOException {
...
-            } catch (Exception e) {
-                exceptions.add(new IOException("failed to read " + pathAndStateId.toString(), e));
-                logger.debug(() -> new ParameterizedMessage(
+            final List<Throwable> exceptions = new ArrayList<>();
+            for (PathAndStateId pathAndStateId : pathAndStateIds) {
+                try {
+                    T state = read(namedXContentRegistry, pathAndStateId.file);
+                    logger.trace("state id [{}] read from [{}]", pathAndStateId.id, pathAndStateId.file.getFileName());
+                    return state;
+                } catch (NoSuchFileException | FileNotFoundException e) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/gateway/MetaDataStateFormat.java]: This can only happen if a concurrent delete occurred I think. Just starting over with new `files` should work out eventually.

**Review by DaveCTurner — COMMENTED** [review]
LGTM. For future readers, we think this is fixed by the fact that metadata is now written atomically, so removing the `@AwaitsFix` annotation is enough.

**Review by DaveCTurner — APPROVED** [review]
