### PR TITLE
ML: Fix error race condition on stop _all datafeeds and close _all jobs

### LINKED ISSUE #37959: [ML] _all requests can suffer "job not found" errors
(Migrated from https://github.com/elastic/elasticsearch/issues/37545#issuecomment-455237072 to improve visibility.)

The failure of https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/166/ showed that it is possible for a request to do some ML operation for `_all` can return an error that it could not find an entity it expected to find.

For example, closing `_all` jobs might return an error that job `foo` does not exist.  Or stopping `_all` datafeeds might return an error that datafeed `bar` does not exist.

This seems completely crazy, as it's obvious that `_all` should only include entities that exist.

The reason this can happen is that our actions involve multiple base level Elasticsearch actions chained together, and entities could be deleted in between these base level steps.  For example:

1. Alice requests force delete of job `foo`
2. Bob requests close `_all` jobs
3. Bob's request to close `_all` jobs expands `_all` to `foo` and `bar`
4. Alice's request to force delete `foo` removes the config associated with job `foo`
5. Bob's request to close `_all` jobs attempts to find the config for job `foo`
6. Bob's request to close `_all` fails because the config for job `foo` does not exist

Although the test failure that highlighted this problem was a 6.5 test run, I suspect the problem is worse in 6.6 and above because expanding `_all` requires a search for configs in an index rather than just looking in the (in-memory on all nodes) cluster state.

ML actions that operate on `_all` should silently ignore failures to find entities from the original expansion of `_all`, on the assumption that these entities have been deleted by a concurrent request.

### PR DESCRIPTION
**Pull request by benwtrent**
The main issue resides around our task updating service. If the task went away us after gathering state info, and then we try to update it, it will fail. 

Only when `_all`, `*`, ` `, is passed do we ignore the `ResourceNotFound` thrown from the task service. 

The only endpoints where this sort of thing seems to be possible is in close jobs and stop datafeeds. All other endpoints that expand and store Ids/Configs either use a search/bulk action, or only use the state information that exists when the request is being handled. 

closes https://github.com/elastic/elasticsearch/issues/37959

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java [hunk 1]
```diff
@@ -331,10 +338,13 @@ public void onResponse(PersistentTasksCustomMetaData.PersistentTask<?> task) {
 
                             @Override
                             public void onFailure(Exception e) {
-                                final int slot = counter.incrementAndGet();
-                                failures.set(slot - 1, e);
-                                if (slot == numberOfJobs) {
-                                    sendResponseOrFailure(request.getJobId(), listener, failures);
+                                if ((e instanceof ResourceNotFoundException &&
+                                    Strings.isAllOrWildcard(new String[]{request.getJobId()})) == false) {
+                                    final int slot = counter.incrementAndGet();
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java]: I think this line needs to come before the `if` statement, otherwise we won't respond to the caller if the race occurs.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java [hunk 2]
```diff
@@ -331,10 +338,13 @@ public void onResponse(PersistentTasksCustomMetaData.PersistentTask<?> task) {
...
+                                    failures.set(slot - 1, e);
+                                    if (slot == numberOfJobs) {
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java]: I think this `if` statement needs to be after the scope of `if ((e instanceof ResourceNotFoundException &&
	                                    Strings.isAllOrWildcard(new String[]{request.getJobId()})) == false) {` ends, otherwise we won't respond to the caller if the race occurs on the very last job.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStopDatafeedAction.java [hunk 3]
```diff
@@ -186,10 +187,14 @@ public void onResponse(PersistentTasksCustomMetaData.PersistentTask<?> persisten
...
                     public void onFailure(Exception e) {
-                        final int slot = counter.incrementAndGet();
-                        failures.set(slot - 1, e);
-                        if (slot == startedDatafeeds.size()) {
-                            sendResponseOrFailure(request.getDatafeedId(), listener, failures);
+                        if ((e instanceof ResourceNotFoundException &&
+                            Strings.isAllOrWildcard(new String[]{request.getDatafeedId()})) == false) {
+
+                            final int slot = counter.incrementAndGet();
+                            failures.set(slot - 1, e);
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStopDatafeedAction.java]: Same problem as for jobs - only `failures.set(slot - 1, e);` should be within the scope of the newly added `if`.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCloseJobAction.java]: yeah man, you are absolutely correct. I don't know what I was thinking :). Should have a commit pushed soon to address

**Review by droberts195 — APPROVED** [review]
LGTM
