### PR TITLE
Handle individual doc parsing failure in bulk request with pipeline

### LINKED ISSUE #138445: The entire bulk request fails if any document parsing fails with pipeline configured
### Elasticsearch Version

8.18, 9.0 (potentially other versions too, need to double check)

### Problem Description

Normally in a bulk request, if indexing for individual document fails (eg. due to invalid json), the rest of the documents in the bulk request will still succeed, and respond a `200` status, with error details for individual doc in the body. However, if the failing document has a pipeline configured, the entire request will fail with `400` status and none of the documents will be indexed.

This is reported by https://github.com/elastic/sdh-elasticsearch/issues/9486, and this [comment](https://github.com/elastic/sdh-elasticsearch/issues/9486#issuecomment-3558500212) pointed we may need to tighten up the error handling in `IngestService`.

### Steps to Reproduce

Create a dummy pipeline
```
PUT /_ingest/pipeline/test-ds-pl-1
{
  "processors": [
    {
      "append": {
        "field": "name",
        "value": "value"
      }
    }
  ]
}
```

Bulk index invalid json doc entry without pipeline
```
PUT /_bulk
{"create":{"_index":"test-ds-1"}}
{"@timestamp":"2024-06-01T00:00:00Z"}
{"create":{"_index":"test-ds-1"}}
{"@timestamp":"2024-06-01T00:00:00Z","@timestamp":"2024-07-01T00:00:00Z"}
```
- Responds `200`, the first doc is indexed, the second doc is not. This is expected.

Bulk index invalid json doc entry with a pipeline
```
PUT /_bulk?pipeline=test-ds-pl-1
{"create":{"_index":"test-ds-1"}}
{"@timestamp":"2024-06-01T00:00:00Z"}
{"create":{"_index":"test-ds-1"}}
{"@timestamp":"2024-06-01T00:00:00Z","@timestamp":"2024-07-01T00:00:00Z"}
```
- Responds `400` and no docs are indexed.

### PR DESCRIPTION
**Pull request by samxbr**
Handle individual doc parsing failure gracefully in a bulk request with pipeline, to prevent the whole bulk request failing due to a single doc failure.

Closes #138445

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java [hunk 1]
```diff
@@ -1784,6 +1785,92 @@ public void testBulkRequestExecutionWithFailures() throws Exception {
...
+        IndexRequest invalidRequest2 = new IndexRequest("_index").id("invalid").setPipeline(pipelineId).setFinalPipeline("_none");
+        invalidRequest2.source(new BytesArray(invalidJson2), XContentType.JSON);
+        bulkRequest.add(invalidRequest2);
+
+        final Processor processor = mock(Processor.class);
+        when(processor.getType()).thenReturn("mock");
+        when(processor.getTag()).thenReturn("mockTag");
+        doAnswer(args -> {
+            @SuppressWarnings("unchecked")
+            BiConsumer<IngestDocument, Exception> handler = (BiConsumer) args.getArguments()[1];
```
Comment (PeteGillinElastic) [inline server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java]: Nit: I'm pretty sure you can do `args.getArgument(1)`, drop the cast, and drop the `@SuppressWarnings`. That method is generic and it'll infer the correct (generic) type to cast the return value to. It's a bit neater and saves us having to think about the suppression. (The unchecked conversion is moved from our code into mockito's.)

File: server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java [hunk 2]
```diff
@@ -1784,6 +1785,92 @@ public void testBulkRequestExecutionWithFailures() throws Exception {
...
+            .putProjectMetadata(ProjectMetadata.builder(projectId).build())
+            .build();
+        ClusterState previousClusterState = clusterState;
+        clusterState = executePut(projectId, putRequest, clusterState);
+        ingestService.applyClusterState(new ClusterChangedEvent("", clusterState, previousClusterState));
+
+        @SuppressWarnings("unchecked")
+        TriConsumer<Integer, Exception, IndexDocFailureStoreStatus> requestItemErrorHandler = mock(TriConsumer.class);
+        @SuppressWarnings("unchecked")
+        final ActionListener<Void> listener = mock(ActionListener.class);
```
Comment (PeteGillinElastic) [inline server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java]: In these two cases, I'm pretty sure you can drop the argument to `mock` and drop the `@SuppressWarnings`. Again, it'll infer the correct generic types. (This was added in mockito 4.something and not enough people know about it.)

**Review by PeteGillinElastic — APPROVED** [review]
LGTM. Just a couple of nits around some mockito syntax to avoid those unchecked conversions.

**Comment by samxbr** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/138706)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/138707)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/138708)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/138709)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by samxbr** [comment]
Not backporting to 8.18 and 9.0 as they are no longer maintained. The bug fix will be backported to `8.19`, `9.1` and `9.2`
