### PR TITLE
Trigger replica recovery restarts by master when primary relocation completes

### LINKED ISSUE #23904: CI: Test failure RelocationIT testIndexAndRelocateConcurrently
This failed on 5.3 multijob-unix-compatibility. The tests passed when I ran them locally. When I searched, I could not find a recent issue for this test failure.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.3+multijob-unix-compatibility/os=sles/98/

``
2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=7A83A8E80EB06D97 -Dtests.class=org.elasticsearch.recovery.RelocationIT -Dtests.method="testIndexAndRelocateConcurrently" -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=America/Whitehorse
  1> [2017-04-04T07:56:47,096][DEBUG][o.e.i.e.Engine           ] [node_t0] [test][1] close now acquiring writeLock
  1> [2017-04-04T07:56:47,096][DEBUG][o.e.i.e.Engine           ] [node_t0] [test][1] close acquired writeLock
  1> [2017-04-04T07:56:47,097][DEBUG][o.e.i.t.Translog         ] [node_t0] [test][1] translog closed
  1> [2017-04-04T07:56:47,097][DEBUG][o.e.i.e.Engine           ] [node_t0] [test][1] engine closed [api]
  1> [2017-04-04T07:56:47,097][DEBUG][o.e.i.s.Store            ] [node_t0] [test][1] store reference count on close: 0
  1> [2017-04-04T07:56:47,097][DEBUG][o.e.i.IndexService       ] [node_t0] [test] [1] closed (reason: [shutdown])
  1> [2017-04-04T07:56:47,097][DEBUG][o.e.i.IndexService       ] [node_t0] [test] [2] closing... (reason: [shutdown])
  1> [2017-04-04T07:56:47,097][DEBUG][o.e.i.s.IndexShard       ] [node_t0] [test][2] state: [STARTED]->[CLOSED], reason [shutdown]
```

### PR DESCRIPTION
**Pull request by ywelsch**
When a primary relocation completes while there are ongoing replica recoveries, the recoveries for these replicas need to be restarted (as a new primary is in charge of replicating changes). Before this PR, the need for a recovery restart was detected by the data nodes that had the replicas, by checking on each cluster state update if the recovery process had completed before the recovery source changed. That code had a race, however, which could lead to a not-fully recovered shard exposing itself as started (see #23904).

This PR takes a different approach: When the primary relocation completes and the master updates the cluster state to move the primary shard from relocating to started, it will reinitialize all initializing replica shards, by giving them a fresh allocation id. Data nodes that have the replica shard will simply detect that the allocation id changed and restart the recovery process (instead of trying to determine the need to restart based on ongoing recoveries).

Note: Removal of the code in `IndicesClusterStateService` that checks whether the recovery source has changed will not be backported to the 5.x branch. This ensures backward compatibility for the situation where the master node is older and does not have the code changes that have been introduced in this PR.

Closes #23904

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -416,6 +416,9 @@ public void updateRoutingEntry(ShardRouting newRouting) throws IOException {
                 // active primaries.
                 throw new IndexShardRelocatedException(shardId(), "Shard is marked as relocated, cannot safely move to state " + newRouting.state());
             }
+            assert newRouting.active() == false || state == IndexShardState.STARTED || state == IndexShardState.RELOCATED ||
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: to make sure I don't miss something: this PR doesn't make this assertion before, it was relevant before as well, right?

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 2]
```diff
@@ -416,6 +416,9 @@ public void updateRoutingEntry(ShardRouting newRouting) throws IOException {
...
+                state == IndexShardState.CLOSED :
+                "shard state is " + state + ", but routing is active " + newRouting;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: I'm not sure this is correct.

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/StartedShardsRoutingTests.java [hunk 3]
```diff
@@ -84,4 +87,66 @@ public void testStartedShardsMatching() {
         assertThat(shardRouting.currentNodeId(), equalTo("node2"));
         assertThat(shardRouting.relocatingNodeId(), nullValue());
     }
+
+    public void testRelocatingPrimariesWithInitializingReplicas() {
+        AllocationService allocation = createAllocationService();
+
+        logger.info("--> building initial cluster state");
+        AllocationId primaryId = AllocationId.newRelocation(AllocationId.newInitializing());
+        AllocationId replicaId = AllocationId.newRelocation(AllocationId.newInitializing());
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/StartedShardsRoutingTests.java]: This doesn't need to be relocating per se? should we use the relocatingReplica boolean?

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/StartedShardsRoutingTests.java [hunk 4]
```diff
@@ -84,4 +87,66 @@ public void testStartedShardsMatching() {
...
+            assertEquals(replica.relocatingNodeId(), startedReplica.relocatingNodeId());
+            assertEquals(replica.allocationId().getId(), startedReplica.allocationId().getId());
+            assertNotEquals(replica.allocationId().getRelocationId(), startedReplica.allocationId().getRelocationId());
+        } else {
+            assertTrue(startedReplica.initializing());
+            assertEquals(replica.currentNodeId(), startedReplica.currentNodeId());
+            assertNotEquals(replica.allocationId().getId(), startedReplica.allocationId().getId());
+        }
+
+        logger.info("--> test starting of relocating primary shard together with initializing / relocating replica");
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/StartedShardsRoutingTests.java]: ++

**Review by bleskes — CHANGES_REQUESTED** [review]
Looks great. Left a bunch of nits and questions. Nothing major there

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingChangesObserver.java [hunk 5]
```diff
@@ -69,6 +69,11 @@
      */
     void replicaPromoted(ShardRouting replicaShard);
 
+    /**
+     * Called when an initializing replica is reinitialized.
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingChangesObserver.java]: sure, I've pushed f53cdedea0

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingChangesObserver.java [hunk 6]
```diff
@@ -120,6 +125,11 @@ public void startedPrimaryReinitialized(ShardRouting startedPrimaryShard, ShardR
         public void replicaPromoted(ShardRouting replicaShard) {
 
         }
+
+        @Override
+        public void initializedReplicaReinitialized(ShardRouting initializingReplica, ShardRouting reinitializedReplica) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingChangesObserver.java]: 1) There is an implementation of the interface (RoutingNodesChangedObserver) where I want to be 100% sure that every method that is added to the interface is properly implemented in that class. With default methods, it's easy to miss this.
2) I've renamed the method parameter.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/RoutingNodesChangedObserver.java [hunk 7]
```diff
@@ -96,6 +96,15 @@ public void replicaPromoted(ShardRouting replicaShard) {
         setChanged();
     }
 
+    @Override
+    public void initializedReplicaReinitialized(ShardRouting initializingReplica, ShardRouting reinitializedReplica) {
+        assert initializingReplica.initializing() && initializingReplica.primary() == false :
+            "expected initializing replica shard " + initializingReplica;
+        assert reinitializedReplica.initializing() && reinitializedReplica.primary() == false :
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/RoutingNodesChangedObserver.java]: sure, I've pushed f53cdedea0

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 1 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: yes, it was relevant before, and actually broken: If we had had this assertion, it would have triggered when we had the test failure here: #23904.

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 2 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: can you elaborate? What's not correct?
What I want to check is `newRouting.active() ==> state == XYZ`, which is rewritten as `newRouting.active() == false || state == XYZ`

File: core/src/test/java/org/elasticsearch/cluster/routing/allocation/StartedShardsRoutingTests.java (hunk 3 above)
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/cluster/routing/allocation/StartedShardsRoutingTests.java]: right, I've pushed f53cdedea0

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 2 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: OK. got it. I got confusing. I would prefer a message like "routing is active, but local shard state isn't.  routing [] , local state [ ]". If you prefer yours I'm got with keeping as is.

**Review by bleskes — APPROVED** [review]
LGTM. Thanks Yannick.
