### PR TITLE
Fix copy_to when the target is a dynamic object field.

### LINKED ISSUE #11237: copy_to needs top level object
You should specify that ```{"copy_to": "top.child"}```  needs ```top``` field defined first, otherwise it would throw an error when indexing.

Also, I'm completely dissatisfied with the documentation on the site.

### PR DESCRIPTION
**Pull request by jimczi**
Tentative fix for #111237.
Fixes #11237

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 1]
```diff
@@ -712,37 +710,55 @@ private static void parseCopy(String field, ParseContext context) throws IOExcep
...
+                            Mapper.Builder builder = context.root().findTemplateBuilder(context, paths[i], "object");
+                            if (builder == null) {
+                                builder = MapperBuilders.object(paths[i]).enabled(true).pathType(parent.pathType());
+                            }
+                            Mapper.BuilderContext builderContext = new Mapper.BuilderContext(context.indexSettings(), context.path());
+                            mapper = (ObjectMapper) builder.build(builderContext);
+                            context.path().add(paths[i]);
+                        } else {
+                            // dynamic == FALSE: read everything up to end object
+                            context.parser().skipChildren();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: why is it needed?

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 2]
```diff
@@ -712,37 +710,55 @@ private static void parseCopy(String field, ParseContext context) throws IOExcep
...
+                            context.path().remove();
+                            throw new StrictDynamicMappingException(context.path().fullPathAsText(""), paths[i]);
+                        } else if (dynamic == ObjectMapper.Dynamic.TRUE) {
+                            context.path().remove();
+                            Mapper.Builder builder = context.root().findTemplateBuilder(context, paths[i], "object");
+                            if (builder == null) {
+                                builder = MapperBuilders.object(paths[i]).enabled(true).pathType(parent.pathType());
+                            }
+                            Mapper.BuilderContext builderContext = new Mapper.BuilderContext(context.indexSettings(), context.path());
+                            mapper = (ObjectMapper) builder.build(builderContext);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: I think we should throw an exception if `mapper.nested() != Nested.NO`, as this would not make sense (and I'm pretty sure some users have dynamic templates to make all their objects nested by default).

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 3]
```diff
@@ -712,37 +710,55 @@ private static void parseCopy(String field, ParseContext context) throws IOExcep
...
+            ObjectMapper[] mappers = new ObjectMapper[paths.length-1];
+            if (paths.length > 1) {
                 ObjectMapper parent = context.root();
-                posDot = objectPath.lastIndexOf('.');
-                if (posDot > 0) {
-                    parentPath = objectPath.substring(0, posDot);
-                    parent = context.docMapper().objectMappers().get(parentPath);
+                for (int i = 0; i < paths.length-1; i++) {
+                    context.path().add(paths[i]);
+                    mapper = context.docMapper().objectMappers().get(paths[i]);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: Hmm, shouldn't we look up the object mapper using `context.path().fullPathAsText("")` instead?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: So maybe we need a test where two levels of nested objects already exist. This would catch this bug?

**Comment by jpountz** [comment]
I left some comments but this looks like a good start!

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 2 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: You want to disallow the creation of dynamic nested objects throw the copy_to ? It makes sense and if the user wants to force the creation of a nested objects for the copy_to target he just need to add the definition in the template. Bottom line (but maybe I am missing something) it seems weird to define a copy_to without defining the type of the target in the mapping (lazy users ? ;) ).

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: > You want to disallow the creation of dynamic nested objects throw the copy_to ?

Exactly.

> if the user wants to force the creation of a nested objects for the copy_to target he just need to add the definition in the mapping

This belongs to a different issue, but I'm also wondering that copying to a nested field, even if it already exists should not be allowed as we have no idea in which nested doc the value should be copied?

To be clear, if you are currently parsing a.b.c and copying to a.b.d and a.b is a nested object field, it's fine since the source and target and under the same nested scope (so adding to the current nested doc that is being built is fine). However, if you're copying from a.b.c to a.d.e and a.d is nested, then we have no way to know to which nested document of a.d.e the value should go, so we should reject it?

(I'm starting this discussion here because your code made me think about this potential problem, but please don't try to address it in the current PR, I think this should go into a dedicated PR.)

> Bottom line (but maybe I am missing something) it seems weird to define a copy_to without defining the type of the target in the mapping (lazy users ? ;) ).

I tend to agree. I think the idea is that we already support dynamic field creation for fields, so we want to be consistent and do it with objects as well.

Comment (clintongormley) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: > This belongs to a different issue, but I'm also wondering that copying to a nested field, even if it already exists should not be allowed as we have no idea in which nested doc the value should be copied?

Agreed. See https://github.com/elastic/elasticsearch/issues/14659

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: Why do we need a good github search when we have @clintongormley  :)

**Comment by jpountz** [comment]
LGTM
