### PR TITLE
Validate dynamic mappings updates on the master node.

### LINKED ISSUE #8650: mapping potentially lost with `"dynamic" : "strict"`, `_default_` mapping and failed document index
The effect is very similar to https://github.com/elasticsearch/elasticsearch/pull/5623
When a document is indexed that does have a dynamic field then the indexing fails as expected. 
However, the type is created locally in the mapper service of the node but never updated on master, see https://github.com/brwe/elasticsearch/commit/340f5c5de207a802085f23aeb984dbd98349301a#diff-defbaaff93b959a2f9a93e7167f6f345R165

This can cause several problems:

1. `_default_` mappings are applied locally and can potentially later not be updated anymore, see https://github.com/brwe/elasticsearch/commit/340f5c5de207a802085f23aeb984dbd98349301a#diff-ed65252ffbbf8656bf257a8cd6251420R68 (thanks @pkoenig10 for the test, https://github.com/elasticsearch/elasticsearch/issues/8423#issuecomment-64395503)
2. Mappings that were created via `_default_` mappings when indexing a document can be lost, see https://github.com/brwe/elasticsearch/commit/340f5c5de207a802085f23aeb984dbd98349301a#diff-defbaaff93b959a2f9a93e7167f6f345R187

### LINKED ISSUE #8688: Mapping updates should be synchronous
Today, a new field can be added to the local mapping of two shards simultaneously. If the detected field type is different, then each shard can end up with a different field type.  These shards then send their new mapping to the master, but only of the mappings will win.

This can result in incorrect results and even data loss, eg: one shard thinks that the field is a string, and the other shard (and the master) thinks that it is a number.  In this case, sorting and aggregations will be wrong (#8485).  Then, when the string-shard is allocated to a new node, that node will receive the "number" mapping from the master.  Replaying the transaction log can cause shard failures (eg #8684).  Or new numeric doc values are written but, when we try to merge segments, it fails with a doc values exception (https://github.com/elasticsearch/elasticsearch/issues/8009).

The only way to ensure that dynamic fields are the same on all shards is to wait for the master to acknowledge the mapping changes before indexing the document, so:

* parse the document
* update local mapping
* **if changed, send to master and wait for ack**
* index document

This will potentially slow down indexing when many dynamic fields are being added, but it is the only way to automatically protect against data loss due to mapping conflicts.

Should a user wish to disable waiting for the master (and they are certain that their dynamic mapping rules are good enough to prevent these problems) then we should allow them to opt-out by setting `"dynamic": "unsafe"`

### PR DESCRIPTION
**Pull request by jpountz**
This commit changes dynamic mappings updates so that they are synchronous on the
entire cluster and their validity is checked by the master node. There are some
important consequences of this commit:
- a failing index request on a non-existing type does not implicitely create
  the type anymore
- dynamic mappings updates cannot create inconsistent mappings on different
  shards
- indexing requests that introduce new fields might induce latency spikes
  because of the overhead to update the mappings on the master node

Closes #8688
Closes #8650

### CODE REVIEW

**Comment by jpountz** [comment]
This is still a work-in-progress as I have test failures on RiverTests. I am suspecting this is because this test triggers lots of concurrent dynamic mappings updates and there is a deadlock somehow because of my ignorange of how our transport works (eg. it is ok to update the mappings like I do in MapperUtils.validateDynamicMappingsUpdateOnMaster?). Any help would be greatly appreciated.

File: src/main/java/org/elasticsearch/index/gateway/IndexShardGateway.java [hunk 1]
```diff
@@ -157,34 +155,12 @@ public void recover(boolean indexShouldExists, RecoveryState recoveryState) thro
...
-                        throw e;
-                    }
-                }
-            });
-
+        for (Map.Entry<String, Mapping> mappingUpdate : typesToUpdate.entrySet()) {
+            try {
+                MapperUtils.validateDynamicMappingsUpdateOnMaster(client, logger, indexService.index().name(), mappingUpdate.getKey(), mappingUpdate.getValue(), waitForMappingUpdatePostRecovery);
+            } catch (Throwable t) {
+                logger.debug("failed to send mapping update post recovery to master for [{}]", t, mappingUpdate.getKey());
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/index/gateway/IndexShardGateway.java]: This seems like a bad case to get into? At least should it be warn or error level? This means we reapplied some updates from the translog, but the master rejected those updates...but we dont seem to do anything with the validation, so does that mean the mappings have already been updated in place? Also, could we limit the catch to just whatever exception would mean failed validation? Otherwise a bug as simple as an NPE in validate would get caught and just logged?

File: src/main/java/org/elasticsearch/index/mapper/MapperUtils.java [hunk 2]
```diff
@@ -76,7 +82,50 @@ public void addConflict(String mergeFailure) {
...
+     */
+    public static void merge(Mapper mergeInto, Mapper mergeWith) {
+        mergeInto.merge(mergeWith, newStrictMergeContext());
+    }
+
+    /**
+     * Merge {@code mergeWith} into {@code mergeTo}. Note: this method only
+     * merges mappings, not lookup structures. Conflicts are returned as exceptions.
+     */
+    public static void merge(Mapping mergeInto, Mapping mergeWith) {
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/index/mapper/MapperUtils.java]: This seems like a duplicate of the method above?

File: src/main/java/org/elasticsearch/index/mapper/MapperUtils.java [hunk 3]
```diff
@@ -76,7 +82,50 @@ public void addConflict(String mergeFailure) {
...
+        PutMappingRequestBuilder requestBuilder = client.admin().indices()
+                .preparePutMapping(index)
+                .setType(type)
+                .setSource(mappingUpdate);
+        if (timeout != null) {
+            requestBuilder.setTimeout(timeout);
+        }
+        final PutMappingResponse response = requestBuilder.get();
+        if (response.isAcknowledged() == false) {
+            throw new ElasticsearchIllegalStateException("Failed to validate dynamic mappings updates on the master node - response was not acknowledged");
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/index/mapper/MapperUtils.java]: Is illegal state the right exception to use? I would normally use this for inconsistent state (meaning we have broken code)?

File: src/main/java/org/elasticsearch/index/mapper/Mapping.java [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+            if (rootMapper.includeInObject()) {
+                continue;
+            }
+            RootMapper mergeWithRootMapper = mergeWith.rootMapper(rootMapper.getClass());
+            if (mergeWithRootMapper != null) {
+                rootMapper.merge(mergeWithRootMapper, mergeContext);
+            }
+        }
+
+        if (!mergeContext.mergeFlags().simulate()) {
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/index/mapper/Mapping.java]: Use `== false` like we do in many other places?

File: src/main/java/org/elasticsearch/percolator/PercolatorService.java [hunk 5]
```diff
@@ -280,10 +282,13 @@ private ParsedDocument parseRequest(IndexService documentIndexService, Percolate
...
-                        Tuple<DocumentMapper, Boolean> docMapper = mapperService.documentMapperWithAutoCreate(request.documentType());
-                        doc = docMapper.v1().parse(source(parser).type(request.documentType()).flyweight(true)).setMappingsModified(docMapper);
-                        if (doc.mappingsModified()) {
-                            mappingUpdatedAction.updateMappingOnMaster(request.shardId().getIndex(), docMapper.v1(), documentIndexService.indexUUID());
+                        Tuple<DocumentMapper, Mapping> docMapper = mapperService.documentMapperWithAutoCreate(request.documentType());
+                        doc = docMapper.v1().parse(source(parser).type(request.documentType()).flyweight(true));
+                        if (docMapper.v2() != null) {
+                            doc.addDynamicMappingsUpdate(docMapper.v2());
+                        }
+                        if (doc.dynamicMappingsUpdate() != null) {
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/percolator/PercolatorService.java]: could you not merge this with the `if` above?

File: src/test/java/org/elasticsearch/index/mapper/update/default_mapping_with_disabled_root_types.json [hunk 6]
```diff
@@ -1 +1 @@
-{"type":{"_timestamp":{"enabled":false},"_index":{"enabled":false},"_size":{"enabled":false},"properties":{}}}
\ No newline at end of file
+{"type":{"_timestamp":{"enabled":false},"_index":{"enabled":false},"_size":{"enabled":false}}}
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/index/mapper/update/default_mapping_with_disabled_root_types.json]: removed newline?

**Comment by rjernst** [comment]
The mappings side looks great! My main question is about what to do on translog replay if sending mapping updates to the master fails.

**Comment by jpountz** [comment]
Good question. This should hopefully not happen once mappings updates are synchronous but I believe this could happen when upgrading from 1.x. In that case I don't think we can do better than warning a scary message to the logs?

**Comment by rjernst** [comment]
@jpountz Ok, let's put it at warn level then?

**Comment by bleskes** [comment]
I think we should fail the shard in this case. It means that some data was indexed in a way that is inconsistent with the “master” mapping in which case you probably have rogue lucene indices. Picking up on another copy is a better alternative. If we ending up having no copies we are at least clearly communicating things are bad (master have a different mapping that is inconsistent with any shard). If people want to still recover they can intervene and delete the translog (which may loose some data but I think it’s an acceptable solution for this bad place to be in). Also note that we flush on close during node shutdown, so the chance this will happen is small...

File: src/main/java/org/elasticsearch/index/mapper/MapperUtils.java (hunk 2 above)
Comment (jpountz) [inline src/main/java/org/elasticsearch/index/mapper/MapperUtils.java]: It does the same thing indeed, but on a Mapping object instead of a Mapper.

File: src/main/java/org/elasticsearch/percolator/PercolatorService.java (hunk 5 above)
Comment (jpountz) [inline src/main/java/org/elasticsearch/percolator/PercolatorService.java]: I don't think we can? It might happen that the first condition is false and the second is true if you only got dynamic updates through `copy_to` directives (which needs to be handled differently since it can insert dynamic mappings at arbitrary places in the mappings).

File: src/test/java/org/elasticsearch/index/mapper/update/default_mapping_with_disabled_root_types.json (hunk 6 above)
Comment (jpountz) [inline src/test/java/org/elasticsearch/index/mapper/update/default_mapping_with_disabled_root_types.json]: Yes, so that tests can check `"foo".equals(string)` instead of `"foo\n".equals(string)`

**Comment by jpountz** [comment]
I added (and beasted) more tests about concurrent indexing requests and the rivers issue seems to be specific to rivers actually so I left mapping updates handled like today when it comes to rivers (ie. updated locally first and then propagated to the master).

Also failing to apply a mapping update on recovery now fails the shard.

File: src/main/java/org/elasticsearch/index/gateway/IndexShardGateway.java [hunk 7]
```diff
@@ -151,41 +151,49 @@ public void recover(boolean indexShouldExists, RecoveryState recoveryState) thro
...
-            });
-            cancellableThreads.execute(new CancellableThreads.Interruptable() {
-                @Override
-                public void run() throws InterruptedException {
-                    try {
-                        if (latch.await(waitForMappingUpdatePostRecovery.millis(), TimeUnit.MILLISECONDS) == false) {
-                            logger.debug("waited for mapping update on master for [{}], yet timed out", type);
+    private void validateMappingUpdate(final String type, Mapping update) {
+        final CountDownLatch latch = new CountDownLatch(1);
+        final Throwable[] error = new Throwable[1];
```
Comment (kimchy) [inline src/main/java/org/elasticsearch/index/gateway/IndexShardGateway.java]: can this be an AtomicReference?

File: src/main/java/org/elasticsearch/index/gateway/IndexShardGateway.java [hunk 8]
```diff
@@ -151,41 +151,49 @@ public void recover(boolean indexShouldExists, RecoveryState recoveryState) thro
...
+            public void onFailure(Throwable t) {
+                latch.countDown();
+                error[0] = t;
+            }
+        });
+        cancellableThreads.execute(new CancellableThreads.Interruptable() {
+            @Override
+            public void run() throws InterruptedException {
+                try {
+                    if (latch.await(waitForMappingUpdatePostRecovery.millis(), TimeUnit.MILLISECONDS) == false) {
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/index/gateway/IndexShardGateway.java]: waitForMappingUpdatePostRecovery defaults to 30s, give that the timeout now results in a failed shard (good!) I think we should be more lenient. Especially given the fact that local gateway recovery runs on full cluster restart where the master might be overloaded by things to do. How about something very conservative like 15m (which is what we use for the same update mapping  - see RecoverySourceHandler#updateMappingOnMaster)

**Comment by jpountz** [comment]
@bleskes @kimchy Pushed a new commit to address your comments

**Comment by purduemike** [comment]
+1 this is happening everyday for me during an index rollover.
Looks like this fix is slated for v2.0.0.  Can we instead merged into the next minor release?
