### PR TITLE
Data tiers: migrate the coldest node attribute

### LINKED ISSUE #81633: Bug in `MetadataMigrateToDataTiersRoutingService` - `_tier_preference` could be incorrect
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.0 

(but the problem was likely present since the introduction of this service in https://github.com/elastic/elasticsearch/pull/73689).

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**: 

- `MetadataMigrateToDataTiersRoutingService` is assuming that if an index is configured with a `_tier_preference` then it is the right data tier index allocation (c.f [code](https://github.com/elastic/elasticsearch/blob/5b38441b16b1ebb16a27c107a4c3865776e20c53/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java#L512)):

```
        // look at the value, get the correct tiers config and update the settings
        if (currentIndexSettings.keySet().contains(TIER_PREFERENCE)) {
            newSettingsBuilder.remove(attributeBasedRoutingSettingName);
            logger.debug("index [{}]: removed setting [{}]", indexName, attributeBasedRoutingSettingName);
        } else {
            // parse the custom attribute routing into the corresponding tier preference and configure it
            String attributeValue = currentIndexSettings.get(attributeBasedRoutingSettingName);
            String convertedTierPreference = convertAttributeValueToTierPreference(attributeValue);
```

**Steps to reproduce**:

We have seen in the field indices configured with the following settings:

- Example 1:
```
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_hot"
            },
            "require" : {
              "data" : "warm"
            }
          }
        },
```

- Example 2:
```
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            },
            "require" : {
              "data" : "warm"
            }
          }
        },
```

In both examples, these indices were actually in the warm phase (confirmed with the ILM explain API results). As a user, if I were to run the `_ilm/migrate_to_data_tiers` API when migrating from nodes types to nodes roles, this would result in an incorrect allocation. These indices will then be allocated to the hot and content and data tier - instead of the warm data tier.

The only way to recover from this is to identify the corresponding ILM phase for the affected indices and set the data tier index allocation accordingly. As a user, it is impossible to do so out of the box (i.e it requires some scripting to cross check information from the list of indices, index settings and ILM explain results of each index).

### PR DESCRIPTION
**Pull request by andreidan**
This fixes the migrate to data tiers routing API to take into account
the scenario where the node attribute configuration for an index is more
accurate than the existing `_tier_preference` configuration.

Previously we would simply remove the node attributes routing if there
was a `_tier_preference` configured for the index.

With this commit, we'll look if either the `require.data` or
`include.data` custom routings are colder than the existing `_tier_preference`
configuration (ie. `cold` vs `data_warm,data_hot`) and update the tier
routing accordingly.

eg.
```
{
  index.routing.allocation.require.data: "warm",
  index.routing.allocation.include.data: "cold",
  index.routing.allocation.include._tier_preference: "data_hot"
}
```
will be migrated to:
```
{
  index.routing.allocation.include._tier_preference: "data_cold,data_warm,data_hot"
}
```

This also removes the existing invariant that had the `require.data`
configuration take precedence over a possible `include.data`
configuration, and will now migrate the coldest configuration to the
corresponding `_tier_preference`.

eg.
```
{
  index.routing.allocation.require.data: "warm",
  index.routing.allocation.include.data: "cold"
}
```
will be migrated to:
```
{
  index.routing.allocation.include._tier_preference: "data_cold,data_warm,data_hot"
}
```

Fixes #81633

### CODE REVIEW

**Review by dakrone — CHANGES_REQUESTED** [review]
The code LGTM, but I think we need to update the docs also?

**Comment by andreidan** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/DataTier.java [hunk 1]
```diff
@@ -188,6 +188,37 @@ public static boolean isFrozenNode(final Set<DiscoveryNodeRole> roles) {
...
+     * NOTE: `data_content` is treated as "equal to data_hot" in the tiers hierarchy.
+     * If invalid tier names are passed the result is non-deterministic.
+     */
+    public static int compare(String tier1, String tier2) {
+        if (tier1.equals(DATA_CONTENT)) {
+            tier1 = DATA_HOT;
+        }
+        if (tier2.equals(DATA_CONTENT)) {
+            tier2 = DATA_HOT;
+        }
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/DataTier.java:209]: @dakrone handling the case where an index has  the following configuration. Not entirely happy with treating `data_content` as equal to `data_hot` (as they are not comparable, or shouldn't be) but I guess it'll have to do unless you have a better suggestion? 

```
"routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            },
            "require" : {
              "data" : "warm"
            }
          }
        }
```

Comment (dakrone) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/DataTier.java:209]: I don't think there's any way around it unfortunately. Functionally though, we consider them to be on the same hardware, so I don't think this is so bad, since it's only for the purpose of (internal) ordering rather than overwriting.

**Review by dakrone — CHANGES_REQUESTED** [review]
This LGTM (with the data_content fix), but we still need to change the docs for the migrate API to document this behavior

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@dakrone the documentation for the API doesn't go into details about how exactly it migrates the entities. We have the manual migration guide that does. I've updated the guide in https://github.com/elastic/elasticsearch/pull/81940/commits/8ba044c71f0348e159ac7c075a0c2739eff0c1d7

Maybe we should rework the docs for the API to be more detailed? Especially with https://github.com/elastic/elasticsearch/issues/82170 coming in soon? Or maybe it's ok we're keeping the docs rather high level? @debadair what do you think? 

@dakrone in any case, I think if we decide to refactor the docs we should do that in a follow-up and take https://github.com/elastic/elasticsearch/issues/82170 into account once that's done. What do you think?

File: docs/reference/data-management/migrate-index-allocation-filters.asciidoc [hunk 2]
```diff
@@ -194,3 +194,34 @@ PUT my-index/_settings
...
+----
+PUT my-index/_settings
+{
+  "index.routing.allocation.require.data": null,
+  "index.routing.allocation.include._tier_preference": "data_warm,data_hot"
+}
+----
+// TEST[continued]
+
+This situation can occur in a system that defaults to data tiers when, for eg,
```
Comment (dakrone) [inline docs/reference/data-management/migrate-index-allocation-filters.asciidoc:224]:
```suggestion
This situation can occur in a system that defaults to data tiers when, e.g.,
```

**Review by dakrone — APPROVED** [review]
LGTM, I left one comment about Latin pedantry :)

> I think if we decide to refactor the docs we should do that in a follow-up and take #82170 into account once that's done. What do you think?

This sounds good to me :+1:
