### PR TITLE
Fix SearchContext CB memory accounting

### LINKED ISSUE #136836: Should we be more aggressive with CB checks for TopHits source fetching?
### Elasticsearch Version

_any_

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

I have noticed numerous OOMs where the cause is (somewhat large) terms aggregation (10k), but with a `TopHits` sub-aggregation, loading the entire `_source` of a document.

In this particular case, it was only a single document, but indeed, it was the entire source. 

6 parallel searches of similar ilk ended up using 5GB of heap on a single node:

Image

An individual _source object size ended up being about 250kb, but we loaded 22k of them  (each terms agg was asking for 10k docs).

It seems like CBEs should have tripped and cancelled a couple of these searches earlier on, but didn't. I honestly don't know if we are indicating heap utilization when loading source for TopHits (or fetch phase in general).

### Steps to Reproduce

N/A

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixing FetchPhase memory management

Problems and TODO (spotted so far):

- [x] `SearchContext.checkRealMemoryCB` doesn't account for CB memory (always zero) - this just triggers Real Memory CB, but it's not enough apparently
- [x] sometimes `FetchPhase.buildSearchHits` batches are too small (eg. in TopHits), the memory buffer never accumulates enough to be tracked
- [x] We don't release CB memory, we only rely on real memory CB
- [x] plumb `TopHitsAggregator` memory management lifecycle
- [x] Add tests triggering CB
- [ ] ~~plumb `InnerHitsPhase` memory management lifecycle~~
- [ ] ~~plumb `SearchService.execute*Phase()` memory management lifecycle~~
- [x] Fall back to try/finally logic for scenarios that don't have a clear CB lifecycle
- [x] `TopHitsAggregator.subSearchContext.closeFuture` grows too much - this is due to [this block](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/internal/SearchContext.java#L77-L82), so it's irrelevant in prod.

Fixes: https://github.com/elastic/elasticsearch/issues/136836

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 1]
```diff
@@ -206,10 +212,6 @@ protected SearchHit nextDoc(int doc) throws IOException {
                 if (context.isCancelled()) {
                     throw new TaskCancelledException("cancelled");
                 }
-                if (context.checkRealMemoryCB(locallyAccumulatedBytes[0], "fetch source")) {
-                    // if we checked the real memory breaker, we restart our local accounting
-                    locallyAccumulatedBytes[0] = 0;
```
Comment (luigidellaquila) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:211]: Most of the time these batches were too small, so this didn't trigger.

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 2]
```diff
@@ -971,7 +971,7 @@ public void executeRankFeaturePhase(RankFeatureShardRequest request, SearchShard
                     return searchContext.rankFeatureResult();
                 }
                 RankFeatureShardPhase.prepareForFetch(searchContext, request);
-                fetchPhase.execute(searchContext, docIds, null);
+                fetchPhase.execute(searchContext, docIds, null, i -> {});
```
Comment (luigidellaquila) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: These did not account for memory before anyway, but now they could.
The hard part is releasing the CB; I don't see close+relase logic around here, and I'm not very familiar with this code. Maybe this could be a follow-up

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java [hunk 3]
```diff
@@ -198,7 +199,7 @@ public InternalAggregation buildAggregation(long owningBucketOrdinal) throws IOE
         for (int i = 0; i < topDocs.scoreDocs.length; i++) {
             docIdsToLoad[i] = topDocs.scoreDocs[i].doc;
         }
-        FetchSearchResult fetchResult = runFetchPhase(subSearchContext, docIdsToLoad);
+        FetchSearchResult fetchResult = runFetchPhase(subSearchContext, docIdsToLoad, this::addRequestCircuitBreakerBytes);
```
Comment (luigidellaquila) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:202]: Should we batch here and avoid invoking the CB for every document? 
Maybe `addRequestCircuitBreakerBytes` should take care of this?

I suspect that fetching source is way more expensive than invoking the CB, so I'm not sure we want more complication here.

File: server/src/main/java/org/elasticsearch/search/internal/SearchContext.java [hunk 4]
```diff
@@ -394,7 +394,7 @@ public Query rewrittenQuery() {
      */
     public final boolean checkRealMemoryCB(int locallyAccumulatedBytes, String label) {
         if (locallyAccumulatedBytes >= memAccountingBufferSize()) {
-            circuitBreaker().addEstimateBytesAndMaybeBreak(0, label);
+            circuitBreaker().addEstimateBytesAndMaybeBreak(locallyAccumulatedBytes, label);
```
Comment (luigidellaquila) [inline server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:397]: This was the crux

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/LargeTopHitsIT.java [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+                Terms terms = response.getAggregations().get("terms");
+                assertThat(terms, notNullValue());
+            });
+        }
+    }
+
+    // This works most of the time, but it's not consistent: it still triggers OOM sometimes.
+    // The test env is too small and non-deterministic to hold all these data and results.
+    @AwaitsFix(bugUrl = "see comment above")
+    public void testBreakAndRecover() throws IOException {
```
Comment (luigidellaquila) [inline server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/LargeTopHitsIT.java:90]: I'd really like to have this test working, but I couldn't find a way to make it pass deterministically; depending on the system conditions sometimes it OOMs before CB, and if I reduce the memory further, it doesn't CB anymore.
 
We have unit tests for FetchPhase CB, but having an integration test would be really really good.

I don't know if we should keep this here or delete it

File: server/src/main/java/org/elasticsearch/search/internal/SearchContext.java (hunk 4 above)
Comment (ivancea) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:397]: The `checkRealMemoryCB()` functions usually add 0 explicitly to force a memory check; are we sure we want to add memory here?
My major questions here would be:
1. Are we freeing it later?
2. Should we rename the method then?
3. This conditionally adds the memory depending on the value, which may lead to wrongly freeing memory later (?)

Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:397]: I just realized that nobody is using this method anymore (apart from a unit test).

> The checkRealMemoryCB() functions usually add 0 explicitly to force a memory check; are we sure we want to add memory here?

Maybe this was the intention at the beginning, but apparently it was not so effective, since in my tests the CB was always empty. And if I remember well, it was a ChildMemoryCircuitBreaker

> Are we freeing it later?

With this fix I'm delegating the memory accounting to AggregatorBase, that handles tracking and releasing CB memory, so we should be safe.

> Should we rename the method then?

I think we can just delete it

> This conditionally adds the memory depending on the value, which may lead to wrongly freeing memory later

I guess, since the CB memory management is delegated to AggregatorBase, we should be safe

Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:397]: Let's be conservative here, I'll make the memoryChecker nullable, and in case I'll keep trying to triggering the real memory CB

**Comment by luigidellaquila** [comment]
Thanks for the contribution and for the off-line conversation @drempapis
If you have a chance, please have a look and see if it covers your expectations.
Unfortunately I can't rely on the try/finally logic in the Aggs scenarios, since the batches are too small and I need to keep the memory accounted for the whole duration of the aggregation, that could span hundreds (sometimes thousands) of FetchPhase executions

File: server/src/main/java/org/elasticsearch/search/internal/SearchContext.java [hunk 6]
```diff
@@ -386,15 +386,14 @@ public Query rewrittenQuery() {
...
-     * Checks if the accumulated bytes are greater than the buffer size and if so, checks the available memory in the parent breaker
-     * (the real memory breaker).
+     * Checks if the accumulated bytes are greater than the buffer size and if so, checks the circuit breaker.
      * @param locallyAccumulatedBytes the number of bytes accumulated locally
      * @param label the label to use in the breaker
-     * @return true if the real memory breaker is called and false otherwise
+     * @return true if the circuit breaker is called and false otherwise
      */
-    public final boolean checkRealMemoryCB(int locallyAccumulatedBytes, String label) {
+    public final boolean checkCircuitBreaker(int locallyAccumulatedBytes, String label) {
```
Comment (luigidellaquila) [inline server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:395]: This is no longer RealMemory, but rather normal (Request) CB

Comment (ivancea) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:395]: Just in case, is there something else using this, that could not be freeing the accounted memory?

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java (hunk 3 above)
Comment (ivancea) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:202]: Maybe worth checking an esrally benchmark here?

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/LargeTopHitsIT.java (hunk 5 above)
Comment (ivancea) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/LargeTopHitsIT.java:90]: FWIW I had a similar problem with the aggs reduction phase memory test, which is now muted: https://github.com/elastic/elasticsearch/issues/134667

Test works, but it fails sometimes. I tried tweaking it to have an exact amount of nodes of each kind, as well as docs, queyr limits and CB settings, and it improved, but still flaky.

Maybe you could try forcing a set amount of nodes, like in here:

https://github.com/elastic/elasticsearch/blob/c6ddf5d7f7079b74973e1545ca2792177660def7/modules/aggregations/src/internalClusterTest/java/org/elasticsearch/aggregations/bucket/AggregationReductionCircuitBreakingIT.java#L44

Less random, but less flaky (luckily 🤞 )

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 7]
```diff
@@ -67,6 +69,17 @@ public FetchPhase(List<FetchSubPhase> fetchSubPhases) {
...
     public void execute(SearchContext context, int[] docIdsToLoad, RankDocShardInfo rankDocs) {
+        execute(context, docIdsToLoad, rankDocs, null);
+    }
+
+    /**
+     *
+     * @param context
+     * @param docIdsToLoad
+     * @param rankDocs
+     * @param memoryChecker if not provided, the fetch phase will try to use the real memory breaker to check memory usage
```
Comment (ivancea) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]:
```suggestion
     * @param memoryChecker if not provided, the fetch phase will use the circuit breaker to check memory usage
```

**Review by ivancea — APPROVED** [review]
LGTM! I would wait for another review if possible, apart of the benchmark, if it makes sense

**Comment by luigidellaquila** [comment]
Buildkite benchmark this with nyc_taxis-1n-8g please

File: server/src/main/java/org/elasticsearch/search/internal/SearchContext.java (hunk 6 above)
Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:395]: That's the only usage for now

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java (hunk 3 above)
Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:202]: I'll run some aggs nightlies and see what happens

**Comment by luigidellaquila** [comment]
Buildkite benchmark this with wikipedia please

**Comment by luigidellaquila** [comment]
Buildkite benchmark this with noaa-1n-1g please

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhaseDocsIterator.java [hunk 8]
```diff
@@ -32,6 +32,16 @@
  */
 abstract class FetchPhaseDocsIterator {
 
+    private long requestBreakerBytes;
+
+    public void addRequestBreakerBytes(long delta) {
```
Comment (drempapis) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhaseDocsIterator.java:41]: It’d be good to document that this field is strictly for fetch-phase memory accounting, will be reversed at the end of the FetchPhase, and shouldn’t be accessed or modified by subclasses. (if any added in the future)

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java (hunk 3 above)
Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/TopHitsAggregator.java:202]: I ran nyc-taxis track, and I see no slowdown (actually it seems faster).
Now I'm running NOAA, that contains more aggs

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 9]
```diff
@@ -233,7 +248,18 @@ protected SearchHit nextDoc(int doc) throws IOException {
 
                     BytesReference sourceRef = hit.hit().getSourceRef();
                     if (sourceRef != null) {
-                        locallyAccumulatedBytes[0] += sourceRef.length();
+                        // This is an empirical value that seems to work well.
```
Comment (drempapis) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:259]: To simplify the logic, we could create an `IntConsumer` once when constructing the `FetchPhaseDocsIterator`

```
IntConsumer checker = memoryChecker != null
    ? memoryChecker
    : bytes -> {
        locallyAccumulatedBytes[0] += bytes;
        if (context.checkCircuitBreaker(locallyAccumulatedBytes[0], "fetch source")) {
            addRequestBreakerBytes(locallyAccumulatedBytes[0]);
            locallyAccumulatedBytes[0] = 0;
        }
    };
```
and simply call

```
if (sourceRef != null) {
    checker.accept(sourceRef.length() * 2);
}
```
We should double check if that works

Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:259]: Thanks @drempapis, I'll give it a try

File: server/src/main/java/org/elasticsearch/search/internal/SearchContext.java (hunk 6 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/internal/SearchContext.java:395]: We should add to the Javadoc that callers are responsible for decrementing the breaker by the same amount at some point.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 9 above)
Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:259]: I made this change and yes, the code looks much better now 👍

**Comment by luigidellaquila** [comment]
Thanks for the reviews

@ivancea the benchmarks didn't show any significant changes in performance.

@drempapis please let me know if you have any further comments, otherwise I'll more forward and merge.

Thanks!

**Review by drempapis — APPROVED** [review]
LGTM! Thank you @luigidellaquila

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 10]
```diff
@@ -245,24 +270,31 @@ protected SearchHit nextDoc(int doc) throws IOException {
...
-        }
 
-        TotalHits totalHits = context.getTotalHits();
-        return new SearchHits(hits, totalHits, context.getMaxScore());
+            TotalHits totalHits = context.getTotalHits();
+            return new SearchHits(hits, totalHits, context.getMaxScore());
+        } finally {
+            long bytes = docsIterator.getRequestBreakerBytes();
+            if (bytes > 0L) {
+                context.circuitBreaker().addWithoutBreaking(-bytes);
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: @luigidellaquila @drempapis Sorry for the late comment here. Thanks for iterating on this. 

I think we're releasing the bytes from the circuit breaker too soon here? The response has not been sent to the client yet so these hits are still in memory.

Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: @andreidan I agree, we should do better here.
IMHO the right approach would be to manage the CB allocation/release together with the request lifecycle. That's what I did for Aggs, using a `memoryChecker` that was already part of the aggregation memory accounting, but for Search I couldn't find anything similar. I don't know that part of the codebase in depth though, so I could have missed something obvious.

Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: @andreidan, we missed it!
I’ve started an alternative here: https://github.com/elastic/elasticsearch/pull/139124. It’s WIP and expected to take more time.

I’ll work on it in parallel and make it a priority, given the complexity of the alternative.

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: Thanks for the additional context. While https://github.com/elastic/elasticsearch/pull/139124 (which looks like an excellent way to move forward) is under development, how confident are we with this change ? Do we have an overview of which queries and scenarios it improves over the previous implementation? and perhaps more importantly where it might fall a bit short to what we had previously? 

From the PR description it seems that the thing that we fixed was: 
```
sometimes FetchPhase.buildSearchHits batches are too small (eg. in TopHits), the memory buffer never accumulates enough to be tracked
```
but we didn't have to replace the real CB to achieve this. Did we consider triggering the real memory CB on a doc count too? (i.e. accumulated 1MiB in source size or retrieved 1024 documents)

Comment (luigidellaquila) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: @andreidan looking at previous discussions (eg. [this](https://github.com/elastic/elasticsearch/pull/112115)  and the internal ES-12944), my impression is that we don't want to rely too much on the real memory CB.

I started this PR mostly to address memory problems with TopHits (as for the comment you mentioned above); my original implementation was intended to use the request breaker when the fetch phase was part of Aggs, but based on the discussions with @drempapis (again, see the internal ES-12944) we ended up using it also for the general case (ie. for Search). I'll let @drempapis comment on this and on the possible regressions, as he probably has more visibility the Search side. For Aggs we are definitely in a much better position now.

> Did we consider triggering the real memory CB on a doc count too? (i.e. accumulated 1MiB in source size or retrieved 1024 documents)

Not that I know

Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: In ES-12944 we analyzed a core issue: on nodes with small `JVM` heaps, large per-document `_source` payloads combined with large `size` values, cause the `fetch phase` to materialize a very large `SearchHit[]` fully in memory. This is a limitation of the current fetch implementation, which constructs the entire hit array and all _source bytes on-heap before returning anything to the client.

For `search memory` accounting, the change introduced here ensures that `_source` bytes are now charged to the `request cb`. This helps by tripping earlier in scenarios that previously bypassed breaker enforcement. However, it only `partially` improves the situation. It does not fully resolve the underlying low-heap, large-source problem because the fetch phase continues to eagerly materialize the full response on-heap. 

Even when the request breaker is active, its default limit (60 percent of heap) is often too high to protect a small-heap node once baseline memory usage is included. The parent-memory breaker only fires at very high global heap occupancy and usually reacts too late, after most of the large objects are already live.

I opened a [PR](https://github.com/elastic/elasticsearch/pull/139243) to mitigate the issue of releasing bytes from the circuit breaker too early while the searchHits are still resident in memory. This is a short-term fix until a more complete solution will be implemented.

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:295]: Ah excellent, thanks for working on https://github.com/elastic/elasticsearch/pull/139243 Dimi ❤️ Awesome we're jumping right on it to fix it! 
Let me know when it's ready and I'll review it.
