### PR TITLE
Fix race condition in SnapshotBasedIndexRecoveryIT

### LINKED ISSUE #79420: [CI] SnapshotBasedIndexRecoveryIT testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation failing
This fails on my PR. It does *not* reproduce on both my PR branch and the latest master.

**Build scan:**
https://gradle-enterprise.elastic.co/s/buhzjdvuto4oo/tests/:server:internalClusterTest/org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT/testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT.testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation" -Dtests.seed=C34EA3B23849FE43 -Dtests.locale=en-PH -Dtests.timezone=Europe/Kirov -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT&tests.test=testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is a value greater than <0L>
     but: <0L> was equal to <0L>

  at __randomizedtesting.SeedInfo.seed([C34EA3B23849FE43:CC927E66AD6F2D44]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT.assertPeerRecoveryUsedSnapshots(SnapshotBasedIndexRecoveryIT.java:1087)
  at org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT.lambda$testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation$7(SnapshotBasedIndexRecoveryIT.java:947)
  at org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT.executeRecoveryWithSnapshotFileDownloadThrottled(SnapshotBasedIndexRecoveryIT.java:1060)
  at org.elasticsearch.indices.recovery.SnapshotBasedIndexRecoveryIT.testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation(SnapshotBasedIndexRecoveryIT.java:894)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by fcofdez**
If we don't cancel the re-location of the index to the same target
node, it is possible that the recovery is retried, meaning that it's
possible that the available permit is granted to indexRecoveredFromSnapshot1
instead of to indexRecoveredFromSnapshot2.

Relates #79316
Closes #79420

### CODE REVIEW

File: x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java [hunk 1]
```diff
@@ -963,6 +968,16 @@ public void testRecoveryUsingSnapshotsPermitIsReturnedAfterFailureOrCancellation
...
                     channelRef.get().sendResponse(new IOException("unable to clean files"));
+                    PeerRecoveryTargetService peerRecoveryTargetService = internalCluster().getInstance(
+                        PeerRecoveryTargetService.class,
+                        targetNode
+                    );
+                    assertBusy(() -> {
+                        // Wait until the current RecoveryTarget releases the snapshot download permit
+                        Releasable snapshotDownloadPermit = peerRecoveryTargetService.tryAcquireSnapshotDownloadPermits();
+                        assertThat(snapshotDownloadPermit, is(notNullValue()));
+                        snapshotDownloadPermit.close();
```
Comment (DaveCTurner) [inline x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java:979]: Slight preference for using a try-with-resources here.

File: x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java [hunk 2]
```diff
@@ -1140,10 +1155,11 @@ private void executeRecoveryWithSnapshotFileDownloadThrottled(SnapshotBasedRecov
                     indexName,
                     Settings.builder()
                         .put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, 1)
+                        .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
                         .put(MergePolicyConfig.INDEX_MERGE_ENABLED, false)
                         .put(IndexService.GLOBAL_CHECKPOINT_SYNC_INTERVAL_SETTING.getKey(), "1s")
                         .put("index.routing.allocation.require._name", dataNodes.get(0))
-                        .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
+                        .put("index.allocation.max_retries", 0)
```
Comment (DaveCTurner) [inline x-pack/plugin/snapshot-based-recoveries/src/internalClusterTest/java/org/elasticsearch/xpack/snapshotbasedrecoveries/recovery/SnapshotBasedIndexRecoveryIT.java:1162]: Slight preference for using the setting directly rather than its literal name:

```suggestion
                        .put(SETTING_ALLOCATION_MAX_RETRY.getKey(), 0)
```

**Review by DaveCTurner — APPROVED** [review]
LGTM (with a couple of nits)
