### PR TITLE
Fix flaky test in SetProcessorTests

### LINKED ISSUE #97164: [CI] SetProcessorTests testSetExistingFields failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/ol67zg6nlufds/tests/:modules:ingest-common:test/org.elasticsearch.ingest.common.SetProcessorTests/testSetExistingFields

**Reproduction line:**
```
./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.SetProcessorTests.testSetExistingFields" -Dtests.seed=8970DEFD8FE56CF -Dtests.locale=ga -Dtests.timezone=Pacific/Pitcairn -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.common.SetProcessorTests&tests.test=testSetExistingFields

**Failure excerpt:**
```
java.lang.IllegalArgumentException: Can't pick a random object from an empty collection.

  at __randomizedtesting.SeedInfo.seed([8970DEFD8FE56CF:C4B1BF9A3C989B34]:0)
  at com.carrotsearch.randomizedtesting.generators.RandomPicks.randomFrom(RandomPicks.java:50)
  at org.elasticsearch.ingest.RandomDocumentPicks.randomExistingFieldName(RandomDocumentPicks.java:72)
  at org.elasticsearch.ingest.common.SetProcessorTests.testSetExistingFields(SetProcessorTests.java:37)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by HiDAl**
the random documents can have entries with an empty map, so, while building the full key in `randomExistingFieldName`, in case we stumble upon this empty map, we won't be able to find a new element because the entry set is empty.

1. Test using the same seed is passing
2. 10000 iterations, all passing
3. 40000 iterations, all passing

```
➜  elasticsearch git:(fix-97164) ✗ ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.SetProcessorTests.testSetExistingFields" -Dtests.seed=8970DEFD8FE56CF
[..]

BUILD SUCCESSFUL in 7s
76 actionable tasks: 3 executed, 73 up-to-date

Publishing build scan...
https://gradle-enterprise.elastic.co/s/hunb7calp7oaq

➜  elasticsearch git:(fix-97164) ✗ ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.SetProcessorTests.testSetExistingFields" -Dtests.iters=10000
[..]

BUILD SUCCESSFUL in 12s
76 actionable tasks: 1 executed, 75 up-to-date

Publishing build scan...
https://gradle-enterprise.elastic.co/s/wqums5silsxkw

➜  elasticsearch git:(fix-97164) ✗ ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.SetProcessorTests.testSetExistingFields" -Dtests.iters=40000
[..]

BUILD SUCCESSFUL in 33s
76 actionable tasks: 1 executed, 75 up-to-date

Publishing build scan...
https://gradle-enterprise.elastic.co/s/3dwuvm6im5jh6

```

Closes #97164

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/ingest/RandomDocumentPicks.java [hunk 1]
```diff
@@ -68,6 +68,8 @@ public static String randomExistingFieldName(Random random, IngestDocument inges
         while (randomEntry.getValue() instanceof Map) {
             @SuppressWarnings("unchecked")
             Map<String, Object> map = (Map<String, Object>) randomEntry.getValue();
+            // we have reached an empty map hence the max depth we can reach
+            if (map.isEmpty()) break;
```
Comment (andreidan) [inline test/framework/src/main/java/org/elasticsearch/ingest/RandomDocumentPicks.java:72]: Shall we use `{ }` here ?

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Pablo

LGTM (assuming CI is happy) with a minor suggestion to use `{ }` for better readability
