### PR TITLE
[Test] Increase timeout of waiting for indexing operations

### LINKED ISSUE #112423: [CI] UpdateMappingIntegrationIT class failing
**Build Scans:**
- [elasticsearch-periodic #3938 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ubfsygwjpbthk)
- [elasticsearch-pull-request #29721 / part-1](https://gradle-enterprise.elastic.co/s/bhbk7gutpq4fo)
- [elasticsearch-pull-request #29602 / part-1-fips](https://gradle-enterprise.elastic.co/s/pnsvakotxiwk4)
- [elasticsearch-pull-request #29418 / part-1](https://gradle-enterprise.elastic.co/s/qny3shkufrjno)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT.testUpdateMappingNoChanges" -Dtests.seed=5781C7FEEB91EDF1 -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=fr -Dtests.timezone=Asia/Novosibirsk -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.discovery.MasterNotDiscoveredException: null
```

**Issue Reasons:**
- [main] 4 failures in class org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT (0.6% fail rate in 643 executions)
- [main] 2 failures in step part-1 (1.3% fail rate in 149 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.9% fail rate in 154 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Larger number of indexing operations can take a while to complete on slower machines for which we need to wait for longer.

Relates: #111957
Resolves: #112423

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 1]
```diff
@@ -1864,7 +1864,15 @@ private void postIndexAsyncActions(String[] indices, List<CountDownLatch> inFlig
...
-            safeAwait(inFlightAsyncOperations.remove(waitFor));
+            try {
+                assertTrue(
+                    "operation did not complete within timeout",
+                    inFlightAsyncOperations.remove(waitFor).await(60, TimeUnit.SECONDS)
+                );
+            } catch (InterruptedException e) {
+                Thread.currentThread().interrupt();
+                fail(e, "interrupted while waiting for operation to complete");
+            }
```
Comment (ywangd) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:1875]: Alternatively, we could limit the number of operations. I think most usages are just a few indexing requests. But decided to keep the change minimal which is a middle ground between the previous code (wait indefinitely) and the current code.

**Review by DaveCTurner — APPROVED** [review]
Bleurgh we should really not have such slow tests here. I am planning to revisit this area at some point to clean up the waiting mechanism, this'll do for now.

**Review by idegtiarenko — APPROVED** [review]

**Comment by ywangd** [comment]
@elasticmachine update branch
