### PR TITLE
Validate forced awareness allocation setting

### LINKED ISSUE #72524: Wrong forced shard allocation setting crashing the cluster
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.8.1, Build: default/tar/b5ca9c58fb664ca8bf9e4057fc229b3396bf3a89/2020-07-21T16:40:44.668009Z, JVM: 14.0.1 (and others)

**Plugins installed**: []
None

**JVM version** (`java -version`):
JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14.0.1/14.0.1+7]

**OS version** (`uname -a` if on a Unix-like system):
Linux server1 4.4.0-1117-aws #131-Ubuntu SMP Tue Oct 6 20:45:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
A wrong forced shard allocation awareness setting crashes Elasticsearch, dropping nodes from the cluster and making it no longer possible for them to re-join.

A student by mistake used an underscore (following the attribute name) instead of a dot when configuring forced shard allocation awareness (see https://discuss.elastic.co/t/how-to-completely-reset-forced-shard-allocation-awareness/271710). The bogus setting did not get rejected and brought the cluster state in a non-working configuration. Any bogus setting results in the same behavior.

Expected behavior: A bogus / mal-formatted setting should get rejected.

**Steps to reproduce**:
 1. Start up a cluster
 2. Execute 
```
PUT /_cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.awareness.force.nonsense": ""
  }
}
```

**Provide logs (if relevant)**:
Excerpt:
```
[2021-04-30T08:55:47,698][WARN ][o.e.c.s.ClusterSettings  ] [MacBook-Pro.lan] failed to apply settings
org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.setForcedAwarenessAttributes(AwarenessAllocationDecider.java:93) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1102) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1076) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-04-30T08:55:47,704][WARN ][o.e.c.s.ClusterApplierService] [MacBook-Pro.lan] failed to apply updated cluster state in [0s]:
version [37], uuid [WgofdmjvSomtdLRgLT1TpQ], source [Publication{term=1, version=37}]
org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.setForcedAwarenessAttributes(AwarenessAllocationDecider.java:93) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1102) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1076) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-04-30T08:55:47,707][INFO ][o.e.c.s.ClusterApplierService] [MacBook-Pro.lan] master node changed {previous [{MacBook-Pro.lan}{ZToSgRxDTGerkkiW9nguzw}{ncGSE2FXQX2FSSt2ekihoQ}{127.0.0.1}{127.0.0.1:9300}{cdfhilmrstw}{ml.machine_memory=68719476736, xpack.installed=true, transform.node=true, ml.max_open_jobs=20, ml.max_jvm_size=33285996544}], current []}, term: 1, version: 37, reason: becoming candidate: clusterApplier#onNewClusterState
[2021-04-30T08:55:47,711][INFO ][o.e.c.s.ClusterSettings  ] [MacBook-Pro.lan] updating [cluster.routing.allocation.awareness.force.] from [{}] to [{"nonsense":""}]
[2021-04-30T08:55:47,711][WARN ][o.e.c.s.ClusterSettings  ] [MacBook-Pro.lan] failed to apply settings
org.elasticsearch.common.settings.SettingsException: Failed to get setting group for [] setting prefix and setting [nonsense] because of a missing '.'
	at org.elasticsearch.common.settings.Settings.getGroupsInternal(Settings.java:440) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Settings.getAsGroups(Settings.java:452) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.setForcedAwarenessAttributes(AwarenessAllocationDecider.java:93) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1102) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.Setting$GroupSetting$1.apply(Setting.java:1076) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-04-30T08:55:47,710][WARN ][o.e.c.s.MasterService    ] [MacBook-Pro.lan] took [0s] and then failed to publish updated cluster state (version: 37, uuid: WgofdmjvSomtdLRgLT1TpQ) for [cluster_update_settings]:
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today any setting under `cluster.routing.allocation.awareness.force.**`
is accepted, but only those matching `...force.*.values` are actually
valid. Accepting other things means that we cannot apply the resulting
cluster state, which is disastrous. This commit adds settings validation
to enforce the expected structure of these settings.

Closes #72524

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/2

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java [hunk 1]
```diff
@@ -231,4 +238,19 @@ private static Decision debugNoMissingAttribute(String awarenessAttribute, List<
                 CLUSTER_ROUTING_ALLOCATION_AWARENESS_ATTRIBUTE_SETTING.getKey(),
                 Strings.collectionToCommaDelimitedString(awarenessAttributes));
     }
+
+    private static void validateForceAwarenessSettings(Settings forceSettings) {
+        for (Map.Entry<String, Settings> entry : forceSettings.getAsGroups().entrySet()) {
+            final Optional<String> notValues = entry.getValue().keySet().stream().filter(s -> s.equals("values") == false).findFirst();
+            if (notValues.isPresent()) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java:245]: I am not sure I completely see how applying the state fails when an entry without `values` is found. I do understand it makes little sense though, but depending on how it fails, it may be worthwhile ensure it not only has a `values` entry but also that it is non-empty?

**Review by henningandersen — COMMENTED** [review]
I have a question, looking good otherwise.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java:245]: Yes, if you set something of the form `cluster.routing.allocation.awareness.force.attr.not_values` today then that doesn't cause a failure at application time, we simply ignore it, so it's really just another bit of inadvertent lenience in the same area that we should be catching at validation time. The failure only comes from setting something of the form `cluster.routing.allocation.awareness.force.no_more_dots`.

I think an empty `cluster.routing.allocation.awareness.force.attr.values` is valid, it effectively says that the only values of `attr` are the ones that currently exist in the cluster which is the default behaviour if the setting is absent.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/allocation/AwarenessAllocationIT.java [hunk 2]
```diff
@@ -307,4 +309,22 @@ public void testAwarenessZonesIncrementalNodes() {
         assertThat(counts.get(B_1), equalTo(2));
         assertThat(counts.get(noZoneNode), equalTo(2));
     }
+
+    public void testForceAwarenessSettingValidation() {
+        final String prefix = AwarenessAllocationDecider.CLUSTER_ROUTING_ALLOCATION_AWARENESS_FORCE_GROUP_SETTING.getKey();
+
+        expectThrows(SettingsException.class, () ->
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/allocation/AwarenessAllocationIT.java:316]: I could be wrong, but I think this results in a 500 internal error at the REST layer? If so, I think we should fix that to be a 400 in the validation of the forced awareness setting.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java:245]: Got it now, thanks for the explanation!

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/allocation/AwarenessAllocationIT.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/cluster/allocation/AwarenessAllocationIT.java]: Yes I think you're right. Wrapped in an IAE in 6977ba5, although maybe `SettingsException` should always be a 400. That's a debate for another day...
