### PR TITLE
Fix ReindexManagementMultiProjectIT

### LINKED ISSUE #141123: [CI] ReindexManagementMultiProjectIT testGettingReindexOnlyWorksForCorrectProject failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11747 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/hcqfcriau6erc)
- [elasticsearch-periodic-platform-support #11747 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/nyxsxvtnfku54)
- [elasticsearch-pull-request #115989 / part-1](https://gradle-enterprise.elastic.co/s/3dwwe6vhfyia2)

**Reproduction Line:**
```
./gradlew ":modules:reindex-management:qa:multi-project:javaRestTest" --tests "org.elasticsearch.reindex.management.ReindexManagementMultiProjectIT.testListingReindexOnlyWorksForCorrectProject" -Dtests.seed=FD083C76EFC3D231 -Dtests.locale=vmw-Latn-MZ -Dtests.timezone=Israel -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reindex.management.ReindexManagementMultiProjectIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGettingReindexOnlyWorksForCorrectProject'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:46003], URI [/_project/Jcf_FQAAQACCf8gPAAAAAA], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"project [Jcf_FQAAQACCf8gPAAAAAA] does not exist"}],"type":"illegal_argument_exception","reason":"project [Jcf_FQAAQACCf8gPAAAAAA] does not exist"},"status":400}
```

**Issue Reasons:**
- [main] 2 consecutive failures in step amazonlinux-2023_platform-support-aws
- [main] 3 failures in test testGettingReindexOnlyWorksForCorrectProject (4.7% fail rate in 64 executions)
- [main] 2 failures in step amazonlinux-2023_platform-support-aws (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by samxbr**
Tests were failing for 2 reasons:
- cluster state update from project deletion is async, the clean-up list-delete loop in the next test can find stale projects from last test, causing project not found error
- reindex tasks were still running after projects are deleted, causing error during indexing

Tested with 100 iterations (https://gradle-enterprise.elastic.co/s/eofbcaj6ttcai/tests/overview):
```
./gradlew ":modules:reindex-management:qa:multi-project:javaRestTest" --tests "org.elasticsearch.reindex.management.ReindexManagementMultiProjectIT" -Dtests.iters=100
```

Closes #141122 
Closes #141123

### CODE REVIEW

File: modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java [hunk 1]
```diff
@@ -258,4 +262,12 @@ private static void setRequestProjectId(final Request request, final String proj
         options.addHeader(Task.X_ELASTIC_PROJECT_ID_HTTP_HEADER, projectId);
         request.setOptions(options);
     }
+
+    private void cancelAllRunningReindexTasks() throws IOException {
+        final Request cancelRequest = new Request("POST", "/_tasks/_cancel");
+        cancelRequest.addParameter("actions", ReindexAction.NAME);
+        cancelRequest.addParameter("wait_for_completion", "true");
+        adminClient().performRequest(cancelRequest);
```
Comment (szybia) [inline modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java]: nit, i typically spam these everywhere, assume we're not guaranteed to throw an exception in non-successful scenarios although would have to check

```suggestion
        assertOK(adminClient().performRequest(cancelRequest));
```

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -3003,7 +3003,19 @@ protected void cleanUpProjects() throws IOException {
             if (projectId.equals(ProjectId.DEFAULT.id())) {
                 continue;
             }
-            deleteProject(projectId);
+            try {
```
Comment (szybia) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:3006]: iiuc, should we prefer to maybe assertBusy that there's no projectIDs left here (cluster state applies) before returning?

your fix fixes your failures but it might violate a developer expectation that `after test, all state is gone` 🤔

File: modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java [hunk 3]
```diff
@@ -66,6 +67,9 @@ protected String getTestRestCluster() {
     @After
     public void removeNonDefaultProjects() throws IOException {
```
Comment (szybia) [inline modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java]: maybe to reflect new functionality
```suggestion
    public void cleanUpProjectsAndReindexTasks() throws IOException {
```

File: modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java [hunk 4]
```diff
@@ -14,6 +14,7 @@
 import org.elasticsearch.client.Response;
```
Comment (szybia) [inline modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java:14]: (i fixed your description to close both issues, seems like wasn't doing that before, i had to add a newline 🚀 )

**Review by szybia — COMMENTED** [review]
nits and 1 comment around assertBusy 🚀

File: modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java (hunk 4 above)
Comment (samxbr) [reply modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java:14]: Thanks!

File: modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java (hunk 3 above)
Comment (samxbr) [reply modules/reindex-management/qa/multi-project/src/javaRestTest/java/org/elasticsearch/reindex/management/ReindexManagementMultiProjectIT.java]: I think I will just name it `cleanup`, the code is self-explanatory enough

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 2 above)
Comment (samxbr) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:3006]: Ensuring clean project state probably should be in separate methods, since deleting the project doesn't ensure the state is clean. There are more things to clean up than just the project ids, for example the reindex task could be still running.

Comment (samxbr) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:3006]: Maybe we can have one method that checks and cleans up everything, I don't want to tackle that right now though

Comment (szybia) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:3006]: hmm, but for this specific method, shouldn't we wait for the projects to actually be deleted?

i'd expect if i call `cleanUpProjects`, then once it returns there are no projects and the next state has clean "state"/nothing carried over from last test

i don't think i'm missing anything but maybe you can help me understand if i am

iiuc, to be explicit this is what i'm suggesting:
```java
    protected void cleanUpProjects() throws Exception {
        assert multiProjectEnabled;
        final var projectIds = getProjectIds(adminClient());
        for (String projectId : projectIds) {
            if (projectId.equals(ProjectId.DEFAULT.id())) {
                continue;
            }
            deleteProject(projectId);
        }
        assertBusy(() -> assertThat(getProjectIds(adminClient()), equalTo(1)));
    }
```

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 5]
```diff
@@ -2996,15 +2996,32 @@ protected Collection<String> getProjectIds(RestClient client) throws IOException
...
         assert multiProjectEnabled;
         final var projectIds = getProjectIds(adminClient());
         for (String projectId : projectIds) {
             if (projectId.equals(ProjectId.DEFAULT.id())) {
                 continue;
             }
-            deleteProject(projectId);
+            try {
+                deleteProject(projectId);
+            } catch (ResponseException e) {
```
Comment (szybia) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:3008]: do we still need the try-catch? 🤔 there should be no stragglers left no?

Comment (samxbr) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:3008]: It's safer to keep it, since we can't guarantee this is the only method that deletes projects.

**Review by szybia — APPROVED** [review]
nice!
