### PR TITLE
Return all assertion failure together

### LINKED ISSUE #134356: Return all assertion errors for yaml rest tests
Yaml rest tests usually have more than one assertion, as an example:

https://github.com/elastic/elasticsearch/blob/cce52ddb0c051225a681aa83beb6891e7484a2fc/x-pack/plugin/rank-rrf/src/yamlRestTest/resources/rest-api-spec/test/linear/10_linear_retriever.yml#L778-789

Currently, when a test case is executed, we execute each assertion one by one.
The moment one assertion fails, we consider the test failed and return the error.

Which means that if you have more than one assertion in your test, you need to run the yaml rest test multiple times until you fixed all the assertions you need to include. Which takes time, especially since yaml rest test take longer to execute than regular unit tests.

Instead, we could execute all assertions we have for the response and collect all the assertion errors (with `ErrorCollector`?). If any assertion errors are collected we output them and consider that the test case failed.

Looking at `ESClientYamlSuiteTestCase::test`/`ExecutableSection`/`Assertion` it certainly seems possible and this might reduce the time we spend (re)running yaml tests when we need to correct them.

### PR DESCRIPTION
**Pull request by mamazzol**
When multiple assertion fail in a yamlRestTest, all the failures are printed together. 
This allows for all the errors to be known in one test run.

Closes: #134356

### CODE REVIEW

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java [hunk 1]
```diff
@@ -108,6 +108,8 @@ public abstract class ESClientYamlSuiteTestCase extends ESRestTestCase {
 
     private static ClientYamlSuiteRestSpec restSpecification;
 
+    private ESClientYamlSuitErrorCollector errorCollector;
```
Comment (ldematte) [inline test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: This can be final, I think

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java [hunk 2]
```diff
@@ -533,16 +519,25 @@ private void executeSection(ExecutableSection executableSection) {
...
-        return "Failure at [" + testCandidate.getSuitePath() + ":" + executableSection.getLocation().lineNumber() + "]: " + t.getMessage();
+    protected boolean skipSetupSections() {
+        return false;
+    }
+
+    /**
+     * Execute an {@link ExecutableSection}, careful to log its place of origin on failure.
+     */
+    private void executeSection(ExecutableSection executableSection) {
+        errorCollector.checkSucceeds(executableSection);
```
Comment (ldematte) [inline test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: I find this a bit obscure; maybe the naming (what the method is actually doing is executeSectionAndCollectErrors or something similar).
But I would prefer a signature similar to the ErrorCollector; something like 
`errorCollector.checkSucceds(executableSection::execute)` would be more clear to me, and possibly also easier to test (mocking the executableSection maybe?)

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+ * License v3.0 only", or the "Server Side Public License, v 1".
+ */
+
+package org.elasticsearch.test.rest.yaml;
+
+import org.apache.logging.log4j.Logger;
+import org.elasticsearch.test.rest.yaml.section.ExecutableSection;
+import org.junit.rules.ErrorCollector;
+
+public class ESClientYamlSuitErrorCollector extends ErrorCollector {
```
Comment (ldematte) [inline test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java]: Is there any advantage in using inheritance here (over composition?)
E.g. can we use this as a junit errorcollector somewhere?

**Review by ldematte — COMMENTED** [review]
Looks like a good first step, thanks!
I think it is worth adding some tests, both to see if this works as intended and to have a better idea of the kind of output we will get.

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java (hunk 1 above)
Comment (mamazzol) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: The errorCollector is initialised before every test so I am not sure it can be final

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java (hunk 3 above)
Comment (mamazzol) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java]: I don't think this could be usable as a junit error collector in other situations as the customised parts are very specific to the yaml rest test execution, where we cannot use the error collector. 

The advantage of using inheritance is I can reuse the "verify" method, which is protected.

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java (hunk 1 above)
Comment (ldematte) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: But this is created once in the ctor, right?

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java (hunk 3 above)
Comment (ldematte) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java]: Is there a reason in particular we are using ErrorCollector at all?

Comment (mamazzol) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java]: It's a tool that does what is needed (collecting errors and throwing an exception with all of them with a nice error message).  We could write a similar thing from scratch if we need more customisation but for now it looks okay

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java (hunk 1 above)
Comment (mamazzol) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: No it's instantiated every time in the `initAndResetContext` method which is run before every test.

Comment (ldematte) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: Oh I see! GH diff fooled me :D

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java (hunk 3 above)
Comment (ldematte) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuitErrorCollector.java]: I see that in the new code the derived ErrorCollector is much smaller, I can see the appeal of reusing something that's already there.

**Review by ldematte — APPROVED** [review]
LGTM

File: test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java (hunk 2 above)
Comment (ldematte) [reply test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java]: I see in the new revision this disappeared, as it is calling directly `ErrorCollector#checkSucceds(Runnable)`. That makes it more clear to me, thanks

**Review by mosche — APPROVED** [review]
lgtm
