### PR TITLE
Spatial search functions support multi-valued fields in compute engine

### LINKED ISSUE #110830: [ESQL] Spatial functions pushed down to lucene produce different results for multi-values
Currently the compute engine return false when executing  a spatial function with multivalues but if the function is pushed down to lucene, then the relationship is computed as it the multivalues is a Geometry collection.  These means the results might be different depending on a function being pushed down to lucene or not.

This can be reproduced with the following commands:
```

PUT indexed
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_point"
      }
    }
  }
}

PUT not_indexed
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_point",
        "index": false,
        "doc_values": false
      }
    }
  }
}

POST indexed/_doc 
{
  "location" : ["POINT(0 0)", "POINT(180 0)"]
}

POST not_indexed/_doc 
{
  "location" : ["POINT(0 0)", "POINT(180 0)"]
}

POST _query 
{
  "query" : """
  FROM indexed | WHERE ST_INTERSECTS(location, TO_GEOSHAPE("POINT(0 0)")) 
  """
}

POST _query 
{
  "query" : """
  FROM not_indexed | WHERE ST_INTERSECTS(location, TO_GEOSHAPE("POINT(0 0)")) 
  """
}
```
 
The results of the queries should be the same regardless of how the field is defined in the mappings.

### LINKED ISSUE #112102: ST_WITHIN on multi-valued cartesian points returns false positives from lucene pushdown
The issue at https://github.com/elastic/elasticsearch/issues/110830 describes how Lucene pushdown for spatial predicates does not match the compute engine results. This is mostly because we support multi-values in Lucene pushdown, but not in the compute engine. The fix at https://github.com/elastic/elasticsearch/pull/112063 enabled multi-value support in the compute engine, but exposes an additional bug.

For cartesian multi-value points, the lucene pushdown for `ST_WITHIN` acts like `ST_INTERSECTS` in that it returns `true` if `ANY` of the points intersect the test geometry, instead of requiring `ALL` points to intersect the test geometry.

To reproduce this we have failing tests:
* `SpatialPushDownCartesianPointIT.testPushedDownQueriesMultiValue()`
* `SpatialPushDownCartesianPointIT.testSimplePointInPolygon()`

The latter simply creates explicit tests of single and multivalued points, where it is clear which are merely intersecting or entirely within the test polygon. This works fine for `geo_point`, but fails for `cartesian_point` with multi-values where the points are partially within the polygon.

### LINKED ISSUE #112505: ES|QL: ST_CENTROID_AGG fails when no doc-values are available
When a point field is used only for aggregating in `ST_CENTROID_AGG`, then the field extraction is switched to extract doc-values for higher performance:

```
FROM indexed | WHERE ST_INTERSECTS(location, TO_GEOSHAPE("POLYGON ((-10 -10, -10 10, 10 10, 10 -10, -10 -10))")) | STATS COUNT(*), ST_CENTROID_AGG(location)
```

However, if the index field mapping is mapped with out doc values:
```
{
  "properties" : {
    "location": { "type" : "geo_point",  "index" : false, "doc_values" : false }
  }
}
```

This this query will fail:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s5][esql_worker][T#2],5,TGRP-SpatialPushDownGeoPointIT]
java.lang.AssertionError: BYTES_REF NOT IN (NULL, LONG)
	at __randomizedtesting.SeedInfo.seed([E092AB3A4E3619A6]:0)
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:164)
	at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:76)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:258)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:189)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:991)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The message `BYTES_REF NOT IN (NULL, LONG)` basically means that what was actually read from the store was `BYTES_REF` (as expected for geo_point from source), but what the reader expected to see from the field type was `LONG` (as expected from geo_point from doc-values).

### PR DESCRIPTION
**Pull request by craigtaverner**
In #110830 it was noted that ES|QL produces different results during spatial search for multi-values when we pushdown to lucene versus when we do not. The lucene query understands spatial multi-values, while the compute engine does not.

Normally ES|QL predicates do not support multi-values because it is ambiguous whether the predicate means `ANY` or `ALL` on the multi-value. For example, if the field `age=[10,30]` and we have the query `FROM index | WHERE age > 20`, it should pass for `ANY` and fail for `ALL`. But in order to answer that, the predicate needs knowledge of this choice between `ANY` and `ALL`.

It turns out that this choice is already made for the spatial predicates. They contain knowledge of how to deal with multi-value fields (the choice of `ANY`, `ALL` or some other logic). This is because the spatial types understand the concept of a collection, and already deal with collections, so multi-valued types can be handled naturally. The lucene queries used for lucene-pushdown already support multi-values for spatial predicates like `ST_INTERSECTS`. However, the compute engine does not. The code generated from the `Evaluator` methods explicitly filters out multi-valued fields.

While this PR originally added generic support for multi-value fields using an extension to the `@Evaluator` annotation to explicitly define a combiner (Any vs All combiners), that solution was only sufficient for `ST_INTERSECTS` and `ST_DISJOINT`. It turns out that if the right-hand-side is also compound, then `ST_CONTAINS` and `ST_WITHIN` need more complex support to consider that each of the components of the other parameter needs to be contained or within at least one of the components of the first parameter. For this scenario, it is much simpler to just combined all multi-values into a single parameter before evaluation. For this reason the `@Evaluator` extension was removed in https://github.com/elastic/elasticsearch/pull/112063/commits/1792442e7338a628b2634b5132815158d6ccb692.

Instead the solution chosen here was to pass in the parameters as the original Blocks, and rely on the spatial functions to decide how to deal with them (by merging them into single compound geometries before performing the spatial relationship check). The total code complexity is lower. However, if there is interest in supporting the more general Any/All approach to other predicate functions, then reverting the above mentioned commit is one place to consider starting.

Fixes #110830
Fixed #112102
Fixes #112505

### CODE REVIEW

**Comment by nik9000** [comment]
> `ST_INTERSECTS(field, polygon)` - `true` if `ANY` value can intersect the polygon

What if the RHS is many polygons? Is that true if any field intersects any of the polygons?

File: x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/EvaluatorImplementer.java [hunk 1]
```diff
@@ -544,6 +606,7 @@ public void buildInvocation(StringBuilder pattern, List<Object> args, boolean bl
                 return;
             }
             if (blockStyle) {
+                // TODO: Support multiValued for non-BytesRefBlock types
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/EvaluatorImplementer.java:609]: I'd throw for now until you need it. That way the compiler will fail and folks can get an error message you wrote.

**Comment by iverase** [comment]
> ST_INTERSECTS(field, polygon) - true if ANY value can intersect the polygon
> What if the RHS is many polygons? Is that true if any field intersects any of the polygons?

Yes, intersects is true if the geometries have at least one point in common.

File: x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/MvCombiner.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+/**
+ * When supporting multivalued fields, it is necessary to know how to combine them.
+ * This is done using a loop over the fields, calling combiner.combine(previous, value) on each, where the previous
+ * value was initialized to combiner.initial() before the loop.
+ * @param <T> the return type of the method that is annotated by the Evaluator annotation.
+ */
+public interface MvCombiner<T> {
+    T initial();
+
+    T combine(T previous, T value);
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/MvCombiner.java:19]: If we invoke these over the interface there's a good chance the JVM'll run the invocation as megamorphic. The particular way you are doing it now runs into a edge case in my knowledge - because there's always a single subclass for each call site so, theoretically, it could know that this site always uses that subclass. I'm not sure if it does though.

Either way, I think it'd be better to declare the member variable as having the exact type of the implementation. So they'd be `AllCombiner combiner = new AllCombiner()` in the class. That way it *knows*.

I know it's premature optimization, but that's kind of the point of these `ExpressionEvaluator`s - to be as efficient as we can make them.

Also! I think the `<T>` is trouble here - at least at runtime. Maybe these should just be locked to `bool` for now.  I get that this is flexible so you can do a `BytesRefBuilder` or a `long` or whatever for combination, but for now we only need `bool` and I'm pretty sure the boxing/unboxing business gives optimizers trouble.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/AnyCombiner.java [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+ */
+
+package org.elasticsearch.xpack.esql.expression.function.scalar.spatial;
+
+import org.elasticsearch.compute.ann.MvCombiner;
+
+/**
+ * This multivalue combiner supports combining boolean types, where any true value will result in a true result.
+ */
+public class AnyCombiner implements MvCombiner<Boolean> {
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/AnyCombiner.java:15]: I'd stick these next to `MvCombiner` over in the `compute` engine.

**Review by nik9000 — APPROVED** [review]
I think the compute engine side is good. I left a note around performance. I know, do it right, then fast. But I'm a little paranoid about these.

It'd be really nice to have a microbenchmark too. Mostly so we can compare future work. But that can come in a follow up. Honestly, so can my point about `<T>` and declaring the actual types in the generated code.

I've not looked at any of the correctness, especially with regards to geo specifics. Just the way you are going about this in the compute engine. And that I think is a really good direction.

**Comment by nik9000** [comment]
> Yes, intersects is true if the geometries have at least one point in common.

:+1:

And that's what I saw when I reviewed the compute side. Thanks for confirming that's what it's supposed to do.

File: x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/MvCombiner.java (hunk 2 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/MvCombiner.java]: This change has been implemented as a side effect of other changes I was making. We do now declare the evaluators field as the concrete type, not the interface, so hopefully these concerns are alleviated.

There might be some boxing/unboxing left, but hopefully that is a minor issue. I have taken care that we should only ever see that for multi-value cases, which right now is only for spatial search functions, so if there is any impact, it has a very narrow blast radius.

File: x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/Evaluator.java
Comment (ivancea) [inline x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/Evaluator.java:1]: Why implementing the new combiner here instead of migrating the functions to `@MvEvaluator`?
With this, `@Evaluator` now also handles multivalues, making these annotations "overlap".

Adding to it, the Combiner working with generics and boxing also feels weird (Already commented by Nik, so nothing to add here).

So my general point here is, is it worth it to do this this way?

File: x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/EvaluatorImplementer.java (hunk 1 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/compute/gen/src/main/java/org/elasticsearch/compute/gen/EvaluatorImplementer.java]: Added code path for multi-value case.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/AnyCombiner.java (hunk 3 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/AnyCombiner.java]: Each attempt caused dependency issues, so I've left it where it is for now.

File: x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/Evaluator.java
Comment (craigtaverner) [reply x-pack/plugin/esql/compute/ann/src/main/java/org/elasticsearch/compute/ann/Evaluator.java:1]: I did a brief look into MvEvaluator, but it did not seem to cover the cases I wanted. Perhaps I misunderstood things, but I did notice that some MV functions use Evaluator, not MvEvaluator, so I think there are cases where this makes sense. But it would be good to get more clarity on what the exact usages of Evaluator vs. MvEvaluator are.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java [hunk 4]
```diff
@@ -87,21 +98,37 @@ protected boolean geometryRelatesGeometry(BytesRef left, BytesRef right) throws
...
+            GeometryDocValueReader leftDocValueReader = asGeometryDocValueReader(coordinateEncoder, shapeIndexer, left.combined());
+            return geometryRelatesGeometries(leftDocValueReader, rightComponent2Ds);
+        }
+
         private boolean geometryRelatesGeometries(GeometryDocValueReader leftDocValueReader, Component2D[] rightComponent2Ds)
             throws IOException {
+            boolean contains = true;
+            boolean intersectsButNotContains = false;
             for (Component2D rightComponent2D : rightComponent2Ds) {
+                boolean containsComp = geometryRelatesGeometry(leftDocValueReader, rightComponent2D);
```
Comment (iverase) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java:122]: I don't think this is going to work. We should try to do exactly the same thing we are doing in lucene. Therefore we should create a doc value with all the geometries and then check the spatial relationship. Otherwise there can be several edge cases which are going to be a pain.

Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialContains.java]: I have simplified this now.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java [hunk 5]
```diff
@@ -188,4 +194,94 @@ protected boolean pointRelatesGeometry(Point point, Component2D component2D) {
             }
         }
     }
+
+    /**
+     * When dealing with ST_CONTAINS and ST_WITHIN we need to pre-combine the field geometries for multi-values in order
+     * to perform the relationship check. This means instead of relying on the generated evaluators to iterate over all
```
Comment (iverase) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:200]: Why don't we use this approach for Intersects and Contains? I would rather prefer to use the same approacch in all functions and it will remove lots of complexity too.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java [hunk 6]
```diff
@@ -188,4 +194,94 @@ protected boolean pointRelatesGeometry(Point point, Component2D component2D) {
...
+        Geometry combined();
+    }
+
+    /**
+     * Values read from source will be encoded as WKB in BytesRefBlock. The block contains multiple rows, and within
+     * each row multiple values, so we need to efficiently iterate over only the values required for the requested row.
+     * This class works for point and shape fields, because both are extracted into the same block encoding.
+     * However, we do detect if all values in the field are actually points and create a MultiPoint instead of a GeometryCollection.
+     */
+    protected static class MultiValuesBytesRef implements MultiValuesCombiner {
```
Comment (iverase) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:214]: I wonder if this abstraction is really needed. The methods in this class can be implemented as helper methods in this class?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java (hunk 5 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:239]: All functions now use the Block.Builder approach.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java (hunk 6 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/spatial/SpatialRelatesFunction.java:249]: It is possible, but makes the code more complex. We have 4 methods that take the interface type `MultiValuesCombiner`), and these would need to be doubled to 8 methods (for LongBlock and BytesRefBlock versions) and each would need to add additional position parameters. I think the added complexity is not worth it.
