### PR TITLE
Fix alias resolution runtime complexity.

### LINKED ISSUE #40248: Resolving queried indices runs in quadratic time with the number of queried indices
Say you run a request against the index pattern `index-*`. First we resolve `index-*` to a list of concrete indices. But then we do work on each index that runs in linear time with the number of matched expressions, such as `IndexNameExpressionResolver#filteringAliases` which figures out whether some matched concrete indices require filtering because they were matched through an alias.

When querying lots of indices at once, this can become the main bottleneck of query execution. This is especially harmful now that Kibana queries entire index patterns such as `logstash-*` and relies on Elasticsearch's `can_match` phase to do the filtering of indices that don't have matches.

### PR DESCRIPTION
**Pull request by jpountz**
A user reported that the same query that takes ~900ms when querying an index
pattern only takes ~50ms when only querying indices that have matches. The
query is a date range query and we confirmed that the `can_match` phase works
as expected. I was able to reproduce this issue locally with a single node: with
900 1-shard indices, a query to an index pattern that matches all indices runs
in ~90ms while a query to the only index that has matches runs in 0-1ms.

This ended up not being related to the `can_match` phase but to the cost of
resolving aliases when querying an index pattern that matches lots of indices.
In that case, we first resolve the index pattern to a list of concrete indices
and then for each concrete index, we check whether it was matched through an
alias, meaning we might have to apply alias filters. Unfortunately this second
per-index operation runs in linear time with the number of matched concrete
indices, which means that alias resolution runs in O(num_indices^2) overall.
So queries get exponentially slower as an index pattern matches more indices.

I reorganized alias resolution into a one-step operation that runs in linear
time with the number of matches indices, and then a per-index operation that
runs in linear time with the number of aliases of this index. This makes alias
resolution run is O(num_indices * num_aliases_per_index) overall instead. When
testing the scenario described above, the `took` went down from ~90ms to ~10ms.
It is still more than the 0-1ms latency that one gets when only querying the
single index that has data, but still much better than what we had before.

Closes #40248

### CODE REVIEW

**Comment by jpountz** [comment]
@martijnvg @s1monw Git blame is pointing to you as being familiar with this part of the code base. Would you mind having a look?

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 1]
```diff
@@ -314,17 +317,17 @@ public String resolveDateMathExpression(String dateExpression) {
      * <p>Only aliases with filters are returned. If the indices list contains a non-filtering reference to
      * the index itself - null is returned. Returns {@code null} if no filtering is required.
      */
-    public String[] filteringAliases(ClusterState state, String index, String... expressions) {
-        return indexAliases(state, index, AliasMetaData::filteringRequired, false, expressions);
+    public Function<String, String[]> filteringAliases(ClusterState state, String... expressions) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: Note to reviewers: please pay special attention to changes in this file where I reorganized loops to make things perform better.

**Review by martijnvg — APPROVED** [review]
This is a good change and will improve alias resolution. Not that it has been a while since I worked on this part of the code base, but this does look good to me. 

Looks like the pr build needs to be kicked off again?

**Comment by jpountz** [comment]
@elasticmachine please test it

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java [hunk 2]
```diff
@@ -116,9 +116,10 @@ public TransportSearchAction(ThreadPool threadPool, TransportService transportSe
     private Map<String, AliasFilter> buildPerIndexAliasFilter(SearchRequest request, ClusterState clusterState,
                                                               Index[] concreteIndices, Map<String, AliasFilter> remoteAliasMap) {
         final Map<String, AliasFilter> aliasFilterMap = new HashMap<>();
+        final Function<String, AliasFilter> indexToAliasFilter = searchService.buildAliasFilter(clusterState, request.indices());;
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java]: nit extra `;`

**Review by s1monw — COMMENTED** [review]
it looks good to me while I'm not very happy with the Function. I wonder if we should extract the expression resolving into something like `Set<String> responveExpression(String expressionString)` that we can then pass into the relevant functions? Might also be easier to unittest that way. If we need a dedicated class for type safety I am ok with that too.

**Comment by jpountz** [comment]
@s1monw updated

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 3]
```diff
@@ -308,73 +311,68 @@ public String resolveDateMathExpression(String dateExpression) {
...
     }
 
+    /**
+     * Resolve an array of expressions to the set of indices and aliases that these expressions match.
+     */
+    public Set<String> resolveExpressions(ClusterState state, String... expressions) {
+        Context context = new Context(state, IndicesOptions.lenientExpandOpen(), true, false);
+        List<String> resolvedExpressions = Arrays.asList(expressions);
+        for (ExpressionResolver expressionResolver : expressionResolvers) {
+            resolvedExpressions = expressionResolver.resolve(context, resolvedExpressions);
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: I think we should also fix the ExpressionResolver to take and return a Set<String>. I can see `WildcardExpressionResolver` is already converting from set to list internally. I am ok with doing this as a followup. Either way is fine

**Review by s1monw — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java (hunk 3 above)
Comment (jpountz) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: Agreed, I added a TODO in WildcardExpressionResolver. I'd like to keep this change contained if possible since I intend to backport it to stable branches, so I'd rather like to do this as a follow-up.

**Comment by jpountz** [comment]
I was unhappy about the fact that this new way of resolving aliases might become slower in the case that an index has many aliases, so I refactored it in such a way that we decide how to resolve aliases based on the number of resolved expressions vs the number of aliases of the index that is being considered. Would you mind having another look?

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 4]
```diff
@@ -308,71 +313,90 @@ public String resolveDateMathExpression(String dateExpression) {
...
+     * <b>NOTE</b>: The provided expressions must have been resolved already via {@link #resolveExpressions}.
      */
-    public String[] filteringAliases(ClusterState state, String index, String... expressions) {
-        return indexAliases(state, index, AliasMetaData::filteringRequired, false, expressions);
+    public String[] filteringAliases(ClusterState state, String index, Set<String> resolvedExpressions) {
+        return indexAliases(state, index, AliasMetaData::filteringRequired, false, resolvedExpressions);
     }
 
+    // pkg-private for testing
+    Boolean forceIterateIndexAliases;
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: can we rather have a method that takes the two sets and returns a boolean value that we can override in the tests? I don't like this test only variable.

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java (hunk 3 above)
Comment (s1monw) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: ++

**Review by s1monw — APPROVED** [review]
LGTM I left a comment regarding to testing.

**Review by jasontedor — APPROVED** [review]
LGTM.
