### PR TITLE
Fix double-pausing shard snapshot

### LINKED ISSUE #109143: [CI] SnapshotStressTestsIT testRandomActivities failing
Found when investigating https://github.com/elastic/elasticsearch/issues/108907 but looks like a different failure - a shard ends up being marked as `PAUSED_FOR_NODE_REMOVAL` in two separate snapshots:

```
java.lang.AssertionError: Tuple[v1=index-1, v2=1] is assigned twice in [{"repository":"repo-0","snapshot":"snapshot-partial-5","uuid":"cdvmwF6sTkm7j0fVy4fA7g","include_global_state":true,"partial":true,"state":"SUCCESS","indices":[{"name":"index-3","id":"iiD7ALDGTUKF0pUx7ryBNA"},{"name":"index-1","id":"iR2oYK6JQCOk7VjrDnQaOA"}],"start_time_millis":17169382...
        at __randomizedtesting.SeedInfo.seed([4899850D0D379B5B]:0)
        at org.elasticsearch.cluster.SnapshotsInProgress.assertShardStateConsistent(SnapshotsInProgress.java:421)
        at org.elasticsearch.cluster.SnapshotsInProgress.assertConsistentEntries(SnapshotsInProgress.java:390)
        at org.elasticsearch.cluster.SnapshotsInProgress.<init>(SnapshotsInProgress.java:119)
        at org.elasticsearch.cluster.SnapshotsInProgress.withUpdatedEntriesForRepo(SnapshotsInProgress.java:135)
        at org.elasticsearch.snapshots.SnapshotsService$SnapshotShardsUpdateContext.computeUpdatedState(SnapshotsService.java:3213)
        at org.elasticsearch.snapshots.SnapshotsService$SnapshotTaskExecutor.execute(SnapshotsService.java:3935)
        at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1084)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1049)
        at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:244)
        at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1690)
        at org.elasticsearch.action.ActionListener.run(ActionListener.java:433)
        at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1687)
        at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1282)
        at org.elasticsearch.action.ActionListener.run(ActionListener.java:433)
        at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1261)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

Copious logs:

[testoutput-2024-05-28T23:17:03.715Z-fail.tar.gz](https://github.com/elastic/elasticsearch/files/15480532/testoutput-2024-05-28T23.17.03.715Z-fail.tar.gz)

### PR DESCRIPTION
**Pull request by DaveCTurner**
Closes #109143

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -3354,6 +3354,11 @@ private <T> void executeShardSnapshotUpdate(
                     updatedState = updateSnapshotState.updatedState;
                 }
 
+                if (updatedState.state() == ShardState.PAUSED_FOR_NODE_REMOVAL) {
+                    // leave subsequent entries for this shard alone until this one is unpaused
+                    iterator.remove();
+                }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:3360]: It still feels a bit odd that `tryStartNextTaskAfterSnapshotUpdated` can init shard snapshot without  checking whether this shard is already active in snapshots that come before it. I think it relied on the fact that the possible updated states sent by data nodes are all "non-active" which is true till we add `PAUSED_FOR_NODE_REMOVAL`. Theoretically this could happen again in future if we add another similar ShardState. That said, I can see it would be quite a lot work to change things in `tryStartNextTaskAfterSnapshotUpdated`. So I am good with this fix.

**Review by ywangd — APPROVED** [review]
LGTM

I think this fixes ES-8563 as well. Could you please cross link between this PR and ES-8563? Thanks!

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:3360]: ++ valid point, I think we can at least add an assertion to catch a future bug in this area - see 615cebf49ea.
