### PR TITLE
More unsupported locales in Kerberos tests for CLDR

### LINKED ISSUE #109621: KerberosTicketValidatorTests fails when locale database is set to CLDR
This is in the context of #109465. The COMPAT locale database has been removed in JDK 23, and so we need to change to the CLDR dataset. However, doing so breaks `KerberosTicketValidatorTests` in a very strange way:

```
java.security.PrivilegedActionException: javax.security.auth.login.LoginException: Parse Generalized time, invalid format
    at __randomizedtesting.SeedInfo.seed([FD4F44A45D0B391C:73F8EF4888446031]:0)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:575)
    at org.elasticsearch.xpack.security.authc.kerberos.SpnegoClient.<init>(SpnegoClient.java:84)
    at org.elasticsearch.xpack.security.authc.kerberos.KerberosTicketValidatorTests.testValidKebrerosTicket(KerberosTicketValidatorTests.java:126)

    Caused by:
    javax.security.auth.login.LoginException: Parse Generalized time, invalid format
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:789)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:754)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:678)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:676)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:676)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.elasticsearch.xpack.security.authc.kerberos.SpnegoClient.loginUsingPassword(SpnegoClient.java:193)
        at org.elasticsearch.xpack.security.authc.kerberos.SpnegoClient.lambda$new$0(SpnegoClient.java:85)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        ... 2 more

        Caused by:
        java.io.IOException: Parse Generalized time, invalid format
            at java.base/sun.security.util.DerValue.toDigit(DerValue.java:1058)
            at java.base/sun.security.util.DerValue.getTimeInternal(DerValue.java:903)
            at java.base/sun.security.util.DerValue.getGeneralizedTime(DerValue.java:1101)
            at java.security.jgss/sun.security.krb5.internal.KerberosTime.parse(KerberosTime.java:286)
            at java.security.jgss/sun.security.krb5.internal.KRBError.init(KRBError.java:350)
            at java.security.jgss/sun.security.krb5.internal.KRBError.<init>(KRBError.java:193)
            at java.security.jgss/sun.security.krb5.KrbAsRep.<init>(KrbAsRep.java:63)
            at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.send(KrbAsReqBuilder.java:345)
            at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
            at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:751)
            ... 12 more
```

REPRODUCTION STEPS:

1. Change [this line](https://github.com/elastic/elasticsearch/blob/main/build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchTestBasePlugin.java#L89) from `SPI,COMPAT` to `SPI,CLDR`
2. Run the following reproduction
```
./gradlew ':x-pack:qa:evil-tests:test' --tests "org.elasticsearch.xpack.security.authc.kerberos.KerberosTicketValidatorTests.testValidKebrerosTicket" -Dtests.seed=FD4F44A45D0B391C
```

It seems like its using locale information when generating a token, but that shouldn't be happening.

Note that several other tests will be broken by changing COMPAT to CLDR; these are fixed by #109465. This specific test failure is standalone.

### PR DESCRIPTION
**Pull request by n1v0lg**
https://github.com/elastic/elasticsearch/pull/109465 switches the locale database from COMPAT to CLDR. This means the introduction of many new locales. 

Our Kerberos test suite has an external dependency which does not correctly handle Arabic (and other) languages. This PR includes the newly introduced unsupported locales to the ignore list for Kerberos tests.  

Resolves: https://github.com/elastic/elasticsearch/issues/109621

### CODE REVIEW

File: x-pack/qa/evil-tests/src/test/java/org/elasticsearch/xpack/security/authc/kerberos/KerberosTestCase.java [hunk 1]
```diff
@@ -59,6 +59,8 @@ public abstract class KerberosTestCase extends ESTestCase {
     /*
      * Arabic and other language have problems due to handling of generalized time in SimpleKdcServer. For more, look at
      * org.apache.kerby.asn1.type.Asn1GeneralizedTime#toBytes
+     *
+     * Note: several unsupported locales were added in CLDR. #109670 included these below.
```
Comment (n1v0lg) [inline x-pack/qa/evil-tests/src/test/java/org/elasticsearch/xpack/security/authc/kerberos/KerberosTestCase.java:63]: Git blame gives us this info too, but it feels like a nice time saver to have the context and PR ref ready.

**Review by thecoop — APPROVED** [review]

**Review by albertzaharovits — APPROVED** [review]

**Comment by n1v0lg** [comment]
@elasticmachine update branch
