### PR TITLE
[Connector API] Bugfix: support list type in filtering advanced snippet value

### LINKED ISSUE #2189: Elasticsearch Connector API Throws `x_content_parse_exception` on Valid Advanced Sync Rules Configuration
## Bug Description

When querying the connector endpoint as documented in the Elasticsearch reference guide, the API response is breaking due to advanced sync rules configuration in the connector. Despite the connector being properly configured and working as expected otherwise, an `x_content_parse_exception` error is thrown, indicating that the value does not support values of type: START_ARRAY. This behavior is unexpected and suggests an issue with how arrays are parsed or handled within the connector configuration, specifically when dealing with advanced sync rules.

### Steps To Reproduce

1\. Configure a 'postgresql' Elastic connector with advanced sync rules
2\. Execute the curl request to query the connector endpoint:
   ```
   curl \
       -u "username:password" \
       --cacert <path/to/cert> \
       -X GET \
       https://<host>:9200/_connector/<connector>
   ```
3\. Observe the error response indicating a parsing exception related to `connector_filtering_advanced_snippet`.

## Expected behavior

The expected behavior is that the API call successfully retrieves the connector information without any parsing exceptions, reflecting the connector's configuration and its advanced sync rules.

## Screenshots

Not applicable in this context, but the error response provided in the bug report template serves as a textual representation of the issue encountered.

## Environment
- OS: N/A
- Browser: N/A
- Version: 8.12.1

## Additional context

The connector configuration includes advanced sync rules, which are specified as an array in the configuration. The exact configuration causing the issue is as follows:
```
[
  {
    "tables": [
      "search_indices"
    ],
    "query": "SELECT id, st_geohash(coordinates) FROM public.search_indices;"
  }
]
```

This configuration works as expected in other contexts, but when querying the connector endpoint, it leads to the `x_content_parse_exception`. This suggests a potential issue with how the Elasticsearch connector API handles arrays within the advanced sync rules configuration.

### PR DESCRIPTION
**Pull request by jedrazb**
### Bug description

Filtering advanced snippet value can be array of objects (instead of just an object). This is expected by current implementation of the Connector framework. If connector uses advanced filtering, then the parser can break when reading connector data (sync start)

### Changes 
Adapt parser logic to support list-type as filtering advanced snippet value. 

### Verficiation
- manual tests
- unit tests
- e2e tests

### CODE REVIEW

File: x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/filtering/FilteringAdvancedSnippet.java [hunk 1]
```diff
@@ -84,7 +80,14 @@ public FilteringAdvancedSnippet(StreamInput in) throws IOException {
...
             ObjectParser.ValueType.STRING
         );
-        PARSER.declareField(constructorArg(), (p, c) -> p.map(), VALUE_FIELD, ObjectParser.ValueType.OBJECT);
+        PARSER.declareField(constructorArg(), (p, c) -> {
+            if (p.currentToken() == XContentParser.Token.START_ARRAY) {
+                return p.list();
+            } else if (p.currentToken() == XContentParser.Token.START_OBJECT) {
+                return p.map();
+            }
+            throw new XContentParseException("Unsupported token [" + p.currentToken() + "]");
```
Comment (timgrein) [inline x-pack/plugin/ent-search/src/main/java/org/elasticsearch/xpack/application/connector/filtering/FilteringAdvancedSnippet.java:89]:
```suggestion
            throw new XContentParseException("Unsupported token [" + p.currentToken() + "]. Expected an array or an object.");
```

nit: We could add a hint, what was actually expected

**Comment by jedrazb** [comment]
@elasticsearchmachine run buildkite/docs-build-pr

File: x-pack/plugin/ent-search/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/entsearch/332_connector_update_filtering.yml [hunk 2]
```diff
@@ -41,7 +44,13 @@ setup:
                 advanced_snippet:
                   created_at: "2023-05-25T12:30:00.000Z"
                   updated_at: "2023-05-25T12:30:00.000Z"
-                  value: {}
+                  value:
```
Comment (timgrein) [inline x-pack/plugin/ent-search/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/entsearch/332_connector_update_filtering.yml:47]: Should we add one additional test, which tests that parsing an object to a map with actual values works? I think we only have empty objects like `value: {}` in this integration test. It could also make sense to separate the tests to `Update Connector Filtering with advanced snippet value array`, `Update Connector Filtering with advanced snippet value object`, `Update Connector Filtering with advanced snippet value literal`, but this is just a personal opinion.

File: x-pack/plugin/ent-search/src/test/java/org/elasticsearch/xpack/application/connector/ConnectorFilteringTests.java [hunk 3]
```diff
@@ -110,6 +110,73 @@ public void testToXContent() throws IOException {
 
     }
 
+    public void testToXContent_WithAdvancedSnippetPopulated() throws IOException {
```
Comment (timgrein) [inline x-pack/plugin/ent-search/src/test/java/org/elasticsearch/xpack/application/connector/ConnectorFilteringTests.java:113]: Similar suggestion to the one in the integration tests. Should we've explicit test for the different cases: literal, object and array?

**Review by timgrein — APPROVED** [review]
LGTM, I left some suggestions around the tests, but as you're on SDH I can also take these suggestions and provide a follow-up after your merge today :)

File: x-pack/plugin/ent-search/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/entsearch/332_connector_update_filtering.yml (hunk 2 above)
Comment (jedrazb) [reply x-pack/plugin/ent-search/qa/rest/src/yamlRestTest/resources/rest-api-spec/test/entsearch/332_connector_update_filtering.yml:47]: Let's add it in followup PR, I want to get this merged before next BC
