### PR TITLE
Release search contexts after failed dfs or query phase for dfs queries

### LINKED ISSUE #11400: SearchContext not released when search request is rejected
It seams that SearchContexts are not released in case the search requests fails due to a rejection (thread pool queue full). I have a test that fails each time here: https://github.com/brwe/elasticsearch/blob/open-search-contexts/src/test/java/org/elasticsearch/search/SearchWithRejectionsTests.java

### PR DESCRIPTION
**Pull request by brwe**
When the dfs phase runs a SearchContext is created on each node that has a shard
for this query. When the query phase (or query and fetch phase) failed that SearchContext
was released only if the query was actually executed on the node. If for example
the query was rejected because the thread pool queue was full then the search context
was not released.
This commit adds a dedicated call for releasing the SearchContext in this case.

In addition, set the docIdsToLoad to null in case the fetch phase failed, otherwise
search contexts might not be released in releaseIrrelevantSearchContexts.

closes #11400

### CODE REVIEW

File: src/test/java/org/elasticsearch/search/SearchWithRejectionsTests.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+            try {
+                SearchResponse searchResponse = responses[i].get();
+                if (searchResponse.getFailedShards() > 0) {
+                    failures++;
+                }
+            } catch (Throwable t) {
+                failures++;
+            }
+        }
+        assertThat(failures, greaterThanOrEqualTo(1));
```
Comment (s1monw) [inline src/test/java/org/elasticsearch/search/SearchWithRejectionsTests.java]: is this guaranteed? I mean if the cpu is fast/slow enough we might not reject anything in theory? I think we can omit this assertion?

**Comment by s1monw** [comment]
this looks great! I left one minor comment on the test

File: src/main/java/org/elasticsearch/action/search/type/TransportSearchDfsQueryAndFetchAction.java [hunk 2]
```diff
@@ -105,6 +105,10 @@ public void onResponse(QueryFetchSearchResult result) {
                 @Override
                 public void onFailure(Throwable t) {
                     onSecondPhaseFailure(t, querySearchRequest, shardIndex, dfsResult, counter);
+                    // the query might not have been executed at all (for example because thread pool rejected execution)
+                    // and the search context that was created in dfs phase might not be released.
+                    // release it again to be in the safe side
+                    sendReleaseSearchContext(querySearchRequest.id(), node);
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/action/search/type/TransportSearchDfsQueryAndFetchAction.java]: Even if onSecondPhaseFailure is not supposed to throw exceptions, should we put onSecondPhaseFailure in a try block and sendReleaseSearchContext in the finally to be on the safe side?

**Comment by brwe** [comment]
thanks for the review! addressed all comments. want to take another look?

**Comment by s1monw** [comment]
LGTM
