### PR TITLE
ESQL: Fix usage of already released null block in ValueSourceReaderOperator

### LINKED ISSUE #125850: ESQL: can't increase refCount on already released object [ConstantNullBlock[...]]
### Elasticsearch Version

main, 8.16.3 at least

### Installed Plugins

_No response_

### Java Version

N/A

### OS Version

N/A

### Problem Description

Queries with union types of type boolean/keyword can lead to re-using an already released constant null block in the value source reader operator. This causes an illegal state exception and returns a 500 to the user.

The error may be in `ComputeBlockLoaderFactory.constantNulls()` ([here](https://github.com/elastic/elasticsearch/blob/dc484393035c1c32fa0556c1de9ad8527b739c7b/x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java#L684-L687)), where we do not take into account that a constant null block that was once handed out may already have been consumed and closed downstream.

### Steps to Reproduce

```bash
./gradlew run

curl -u elastic-admin:elastic-password -H "Content-Type: application/json" "127.0.0.1:9200/test1" -XPUT -d '{
  "mappings": {
        "properties": {"truefalse1": {"type": "boolean"}, "truefalse2": {"type": "boolean"}}}}'

curl -u elastic-admin:elastic-password -H "Content-Type: application/json" "127.0.0.1:9200/test2" -XPUT -d '{
  "mappings": {
        "properties": {"truefalse1": {"type": "keyword"}, "truefalse2": {"type": "keyword"}}}}'

curl -u elastic-admin:elastic-password -H "Content-Type: application/json" "127.0.0.1:9200/test3" -XPUT -d '{
  "mappings": {
        "properties": {"truefalse1": {"type": "keyword"}, "truefalse2": {"type": "keyword"}}}}'

curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test1/_doc?refresh' -d '{"truefalse1": null}'

curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test2/_doc?refresh' -d '{"truefalse1": null}' 

curl -u elastic:password -HContent-Type:application/json 'localhost:9200/test3/_doc?refresh' -d '{"foo": 1}'

curl -u elastic-admin:elastic-password -H "Content-Type: application/json" 'localhost:9200/_query?format=txt&error_trace' -d '
{
  "query": "from test* | eval t1 = truefalse1::boolean, t2 = truefalse2::boolean | keep t1, t2"
}'
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/125850

### CODE REVIEW

**Comment by alex-spies** [comment]
In addition to the enclosed IT, I'd love to have a unit test for this.

It looks like we should be able to add a case to `ValueSourceReaderOperatorTests`, but I struggled to build one that travels the specific code path with the bug, though. The reason is that the bug only happens when we re-use the same `ComputeBlockLoaderFactory` and create null blocks for multiple pages; but this only happens when the doc block doesn't belong to a single shard, but multiple ones.

@nik9000 if you have an idea how to add a test without major effort, I'd love to add it, too.

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 1]
```diff
@@ -681,7 +681,12 @@ public BlockLoader.Builder nulls(int expectedCount) {
 
         @Override
         public Block constantNulls() {
-            if (nullBlock == null) {
+            // Avoid creating a new null block if we already have one.
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:684]: I'd use a `/*` for these.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 2]
```diff
@@ -681,7 +681,12 @@ public BlockLoader.Builder nulls(int expectedCount) {
...
+            // However, downstream operators take ownership of the null block we hand to them and may close it, forcing us to create a new
+            // one.
+            // This could be avoided altogether if this factory itself kept a reference to the null block, but we'd have to also ensure
+            // to release this block once the factory is not used anymore.
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:688]: Right, the factory itself would have to be `Releasable`. FWIW, that's not really a big deal. I think I'd prefer it to this fix to be honest. I'm kind of ok with whichever though.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 3]
```diff
@@ -947,7 +947,12 @@ public enum Cap {
         /**
          * Supercedes {@link Cap#MAKE_NUMBER_OF_CHANNELS_CONSISTENT_WITH_LAYOUT}.
          */
-        FIX_REPLACE_MISSING_FIELD_WITH_NULL_DUPLICATE_NAME_ID_IN_LAYOUT;
+        FIX_REPLACE_MISSING_FIELD_WITH_NULL_DUPLICATE_NAME_ID_IN_LAYOUT,
+
+        /**
+         * Fix https://github.com/elastic/elasticsearch/issues/125850
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:953]: I'd prefer a short description of the bug so I don't have to switch a web browser when scanning the code. Just a sentence like "fix double release bug for nulls" - I mean, that's the name. But still, I don't real the name so much as I read the comment....

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 2 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:688]: But if you are trying to get this merged quickly I'd be fine with this solution - especially if you are willing to try the other in a followup.

Comment (alex-spies) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:688]: I also prefer making this `Releasable`. It's easy to do, I'll push a commit with the change.

Wrong implementations of `.close()` or forgetting to incref when handing out blocks actually nicely show up as test failures already in the existing tests, so I think this is guarding better against regressions.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 4]
```diff
@@ -345,27 +344,28 @@ void run() throws IOException {
...
+                    shard = shards.getInt(p);
+                    segment = segments.getInt(p);
+                    boolean changedSegment = positionFieldWorkDocGuarteedAscending(shard, segment);
+                    if (changedSegment) {
+                        ctx = ctx(shard, segment);
+                        fieldsMoved(ctx, shard);
+                    }
+                    verifyBuilders(loaderBlockFactory, shard);
+                    read(docs.getInt(p), shard);
+                }
```
Comment (alex-spies) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:368]: This just got indented, the diff is actually just whitespace o.O

**Review by nik9000 — APPROVED** [review]
I like it much more now. Thanks!

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 4 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:368]: If you add `?w=1` to the url it'll ignore whitespace ala `git diff -w`. There's an option for it hiding behind the gear icon at the top of the page too.

**Comment by alex-spies** [comment]
The Serverless checks are failing with an unrelated test failure that is already known (Serverless CI issue opened last week, re-muted 4h ago).

I think it's not worth updating the branch to run CI again just to pick up on the mute for this test, so I'm going to go ahead with the merge as all other tests and CI checks passed.

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/126480)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
