### PR TITLE
Prevent field caps from failing due to can match failure

### LINKED ISSUE #116106: IllegalStateException thrown in SemanticQueryBuilder
### Description

For a `_field_caps` request with `params: {types=, ignore_unavailable=true, expand_wildcards=open, allow_no_indices=true, index=*,-.*, serverlessRequest=true, include_empty_fields=false}`, resulting in a `status: 500`, the following suppressed exception is logged:

```
java.lang.IllegalStateException: No inference results set for [semantic_text] field [description_embedding]
	at org.elasticsearch.inference@9.0.0/org.elasticsearch.xpack.inference.queries.SemanticQueryBuilder.doRewriteBuildSemanticQuery(SemanticQueryBuilder.java:169)
	at org.elasticsearch.inference@9.0.0/org.elasticsearch.xpack.inference.queries.SemanticQueryBuilder.doRewrite(SemanticQueryBuilder.java:155)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:281)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.rewriteClauses(BoolQueryBuilder.java:399)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.doRewrite(BoolQueryBuilder.java:353)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:281)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.rewriteClauses(BoolQueryBuilder.java:399)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.doRewrite(BoolQueryBuilder.java:353)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:281)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SubSearchSourceBuilder.rewrite(SubSearchSourceBuilder.java:90)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SubSearchSourceBuilder.rewrite(SubSearchSourceBuilder.java:38)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:57)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:40)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:125)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:1178)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:94)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:57)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:40)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.internal.ShardSearchRequest$RequestRewritable.rewrite(ShardSearchRequest.java:588)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.internal.ShardSearchRequest$RequestRewritable.rewrite(ShardSearchRequest.java:577)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:57)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.SearchService.queryStillMatchesAfterRewrite(SearchService.java:1740)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.FieldCapabilitiesFetcher.canMatchShard(FieldCapabilitiesFetcher.java:245)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.FieldCapabilitiesFetcher.doFetch(FieldCapabilitiesFetcher.java:113)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.FieldCapabilitiesFetcher.fetch(FieldCapabilitiesFetcher.java:77)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.lambda$messageReceived$0(TransportFieldCapabilitiesAction.java:591)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:356)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.messageReceived(TransportFieldCapabilitiesAction.java:570)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.messageReceived(TransportFieldCapabilitiesAction.java:565)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:632)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:621)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:640)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.ResizeRequestInterceptor.intercept(ResizeRequestInterceptor.java:105)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.ValidateRequestInterceptor.intercept(ValidateRequestInterceptor.java:20)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.ShardSearchRequestInterceptor.intercept(ShardSearchRequestInterceptor.java:23)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.UpdateRequestInterceptor.intercept(UpdateRequestInterceptor.java:27)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:20)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.IndicesAliasesRequestInterceptor.intercept(IndicesAliasesRequestInterceptor.java:127)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.SearchRequestCacheDisablingInterceptor.intercept(SearchRequestCacheDisablingInterceptor.java:53)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.BulkShardRequestInterceptor.intercept(BulkShardRequestInterceptor.java:85)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.DlsFlsLicenseRequestInterceptor.intercept(DlsFlsLicenseRequestInterceptor.java:106)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:619)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$13(AuthorizationService.java:517)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1033)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:999)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexAction(RBACEngine.java:384)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:510)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:442)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:329)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:257)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(RBACEngine.java:156)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$4(CompositeRolesStore.java:202)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$5(CompositeRolesStore.java:220)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.xcore@9.0.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$0(RoleReferenceIntersection.java:49)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:57)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.buildRoleFromRoleReference(CompositeRolesStore.java:317)
	at org.elasticsearch.xcore@9.0.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$1(RoleReferenceIntersection.java:53)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.elasticsearch.xcore@9.0.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.buildRole(RoleReferenceIntersection.java:53)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(CompositeRolesStore.java:218)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:195)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:152)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:345)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:114)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:97)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticate(AuthenticatorChain.java:93)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:264)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:201)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.authenticate(ServerTransportFilter.java:127)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:105)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:643)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:76)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:1098)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)\n

```

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Prevent field_caps from failing when can-match fails

`FieldCapabilitiesFetcher` performs a can-match in order to quickly
return an empty response if no shard can match. However, if can-match
fails for some reason, it can cause the field capabilities request to fail.

An example of that is when a semantic query is used as filter. can-match
will fail as it won't be able to expand the inference results of the query.

In cases like that, it makes no sense to fail the field capabilities request.
Instead, we should treat can-match as returning `true` to proceed.

This change does that by following suit with other callers of can-match.

Fixes #116106

### CODE REVIEW

**Comment by dimitris-athanasiou** [comment]
Note: The first commit is reverting #131111. Before merging I'll split that out of this PR and raise it separately. But it is necessary for the fix to be reviewed here.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesFetcher.java [hunk 1]
```diff
@@ -249,12 +249,17 @@ private static boolean canMatchShard(
...
         assert alwaysMatches(indexFilter) == false : "should not be called for always matching [" + indexFilter + "]";
         assert nowInMillis != 0L;
         ShardSearchRequest searchRequest = new ShardSearchRequest(shardId, nowInMillis, AliasFilter.EMPTY);
         searchRequest.source(new SearchSourceBuilder().query(indexFilter));
-        return SearchService.queryStillMatchesAfterRewrite(searchRequest, searchExecutionContext);
+        try {
+            return SearchService.queryStillMatchesAfterRewrite(searchRequest, searchExecutionContext);
+        } catch (Exception e) {
+            // treat as if shard is still a potential match
+            return true;
```
Comment (Mikep86) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesFetcher.java:261]: @javanna I know we discussed that logging isn't necessary here, but silently swallowing an exception is such a big anti-pattern. IMO we should at least add a WARN log entry so these events are traceable. WDYT?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapper.java [hunk 2]
```diff
@@ -136,6 +136,7 @@ public class SemanticTextFieldMapper extends FieldMapper implements InferenceFie
     public static final NodeFeature SEMANTIC_TEXT_ALWAYS_EMIT_INFERENCE_ID_FIX = new NodeFeature(
         "semantic_text.always_emit_inference_id_fix"
     );
+    public static final NodeFeature SEMANTIC_TEXT_FILTER_FIELD_CAPS_FIX = new NodeFeature("semantic_text.filter_field_caps_fix");
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapper.java]: I think this feature would be more appropriate in `SemanticQueryBuilder`, as the problem is with the `semantic` query, not the `semantic_text` mapper.

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml
Comment (Mikep86) [inline x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml:1]: We already have some field caps tests in `10_semantic_text_field_mapping.yml` (and `10_semantic_text_field_mapping_bwc.yml`), can we add this new test there?

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+      index:
+        index: test-index
+        id: doc_1
+        body:
+          semantic_text_field: "This is a story about a cat and a dog."
+          std_text_field: "some text"
+        refresh: true
+
+---
+"Field caps with semantic_text filter does not fail":
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml]:
```suggestion
"Field caps with semantic query does not fail":
```

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml [hunk 4]
```diff
@@ -0,0 +1,56 @@
+setup:
+  - requires:
+      cluster_features: "semantic_text.filter_field_caps_fix"
+      reason: "fixed bug with semantic query filtering in field_caps (#116106)"
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml]: Nit: We usually don't reference the issue number directly here

**Review by Mikep86 — COMMENTED** [review]
Nice work! Approach and tests look good overall, just a few nit comments. The big thing is silently swallowing the exception (which I know we discussed in https://github.com/elastic/elasticsearch/issues/116106), but that feels so wrong...

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml
Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml:1]: Definitely. Also added it in the BWC tests.

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml (hunk 4 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/100_semantic_text_field_caps.yml]: I find it quite useful to have the issue there for easily retrieving context. We do reference issues in a bunch of other places. I'd rather keep it in unless strongly opposed.

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/part-2

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesFetcher.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesFetcher.java:261]: This is fine in this case. Nobody will do anything with that log line if we do log it anyways. We do this in other places too.

**Comment by dimitris-athanasiou** [comment]
@Mikep86 I have addressed review comments. This is ready for another look.

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/10_semantic_text_field_mapping.yml [hunk 5]
```diff
@@ -548,6 +548,30 @@ setup:
   - not_exists: fields.dense_field.inference.chunks
   - not_exists: fields.dense_field.inference
 
+---
+"Field caps with semantic query does not fail":
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/10_semantic_text_field_mapping.yml:552]: We need to check for the cluster feature here

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/10_semantic_text_field_mapping_bwc.yml [hunk 6]
```diff
@@ -447,6 +447,31 @@ setup:
   - not_exists: fields.dense_field.inference.chunks.text
   - not_exists: fields.dense_field.inference.chunks
   - not_exists: fields.dense_field.inference
+
+---
+"Field caps with semantic query does not fail":
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/10_semantic_text_field_mapping_bwc.yml:452]: Same here, we need to check for the cluster feature

**Review by Mikep86 — COMMENTED** [review]
Looks good except for two things:

- A missing cluster feature check
- No changelog entry for the bug fix. CI should catch this, but maybe that's broken because we are reverting another changelog entry in this PR. Can you manually add it?

Once those are fixed, there are some logistics about how to merge and backport this:

- Merge https://github.com/elastic/elasticsearch/pull/134209 first and merge those changes into this PR, which should cancel out the revert changes here.
- Merge and backport this, which should go smoothly now that the revert changes above are cancelled out.

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/10_semantic_text_field_mapping.yml (hunk 5 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/10_semantic_text_field_mapping.yml:552]: Ouch! Forgot to add those after moving the test. Will add. Thanks for catching this!

**Comment by dimitris-athanasiou** [comment]
@Mikep86 I have added the missing cluster feature checks and the changelog. I'm also fully onboard with the merging plan you laid out.

**Review by Mikep86 — APPROVED** [review]
LGTM!

**Comment by dimitris-athanasiou** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by Mikep86** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Comment by dimitris-athanasiou** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/134551)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/134552)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/134557)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/134558)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
