### PR TITLE
Fix test: wait for global checkpoint to be synced for each shard

### LINKED ISSUE #124447: [CI] IndexStatsIT testFilterCacheStats failing
**Build Scans:**
- [elasticsearch-periodic #6887 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/t4sjpm4i7qr5s)
- [elasticsearch-pull-request #60929 / part-1](https://gradle-enterprise.elastic.co/s/b7h6w6gbm4gva)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indices.stats.IndexStatsIT.testFilterCacheStats" -Dtests.seed=6D428E2B759773A9 -Dtests.locale=lkt-Latn-US -Dtests.timezone=America/Mexico_City -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indices.stats.IndexStatsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testFilterCacheStats),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <1L>
     but: was <-1L>
```

**Issue Reasons:**
- [main] 2 failures in test testFilterCacheStats (0.4% fail rate in 506 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by michalborek**
Fixing a flaky test.

The previous assertion was insufficient because the global checkpoint is asynchronously synced.

Changed to a listener based solution (to avoid assert Busy).

Closes #124447
Closes #135390  - this PR becomes obsolete.

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java [hunk 1]
```diff
@@ -1374,20 +1373,35 @@ public void testWriteLoadIsCaptured() throws Exception {
...
+                                listener.onResponse(null);
+                            } else {
+                                listener.onFailure(e);
+                            }
+                        });
+                    }
                 }
             }
         }
+        future.actionGet(10, TimeUnit.SECONDS);
```
Comment (tlrx) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: You can use safeGet() here

File: server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java [hunk 2]
```diff
@@ -1374,20 +1373,35 @@ public void testWriteLoadIsCaptured() throws Exception {
...
+            for (String node : internalCluster().nodesInclude(index)) {
+                for (IndexService indexService : internalCluster().getInstance(IndicesService.class, node)) {
+                    for (IndexShard indexShard : indexService) {
+                        if (indexShard.routingEntry().primary() == false || indexShard.routingEntry().active() == false) {
+                            continue;
+                        }
+                        indexShard.sync();
+                        final var lastKnownGlobalCheckpoint = indexShard.getLastKnownGlobalCheckpoint();
+                        final var listener = listeners.acquire(
+                            __ -> assertThat(
```
Comment (tlrx) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: There are not many uses of `__` for naming an ignored parameter, I think simply name it `ignored` is more common across the codebase. But if checkstyle/spotless are happy with `__` I'm happy too :)

File: server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java [hunk 3]
```diff
@@ -1374,20 +1373,35 @@ public void testWriteLoadIsCaptured() throws Exception {
...
+    private static void persistGlobalCheckpoint(String index) throws IOException {
+        final var future = new PlainActionFuture<Void>();
+        try (var listeners = new RefCountingListener(future)) {
+            for (String node : internalCluster().nodesInclude(index)) {
+                for (IndexService indexService : internalCluster().getInstance(IndicesService.class, node)) {
+                    for (IndexShard indexShard : indexService) {
+                        if (indexShard.routingEntry().primary() == false || indexShard.routingEntry().active() == false) {
+                            continue;
+                        }
+                        indexShard.sync();
```
Comment (tlrx) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: Now I checked the code again, it seems that `syncGlobalCheckpoint` does execute a `sync` so maybe we don't need `indexShard.sync()` after all.

File: server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java [hunk 4]
```diff
@@ -1374,20 +1373,35 @@ public void testWriteLoadIsCaptured() throws Exception {
...
+                        final var lastKnownGlobalCheckpoint = indexShard.getLastKnownGlobalCheckpoint();
```
Comment (tlrx) [inline server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: The last know global checkpoint is updated asynchronously so it might be out of date I think. What we want here is to wait for the global checkpoint to catch up the max. issued sequence number seen on this primary shard:

```suggestion
final var globalCheckpoint = indexShard.withEngine(Engine::getMaxSeqNo);
```

File: server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java (hunk 2 above)
Comment (michalborek) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: I'll follow the current convention - There's https://openjdk.org/jeps/456 but starting from Java 22, maybe good to wait and eventually switch to a single underscore :)

File: server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java (hunk 3 above)
Comment (michalborek) [reply server/src/internalClusterTest/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: I removed that and run 1k times - works fine on my machine...

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 5]
```diff
@@ -192,4 +199,43 @@ public static void assertRetentionLeasesAdvanced(Client client, String indexName
...
+    public static void persistGlobalCheckpointOnPrimaryShards(String index) throws IOException {
+        final var future = new PlainActionFuture<Void>();
+        try (var listeners = new RefCountingListener(future)) {
+            for (String node : internalCluster().nodesInclude(index)) {
+                for (IndexService indexService : internalCluster().getInstance(IndicesService.class, node)) {
+                    for (IndexShard indexShard : indexService) {
+                        if (indexShard.routingEntry().primary() == false) {
+                            continue;
+                        }
+                        assertThat("Shard should be active", indexShard.routingEntry().active(), equalTo(true));
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java]: Nitty nit: log which shard in case that ever fails

**Review by tlrx — APPROVED** [review]
LGTM (assuming CI passes), thanks for fixing this.

Could you mention that it targets tests only in the title and description of the PR? In its current form one could think it somehow affects production code.

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 6]
```diff
@@ -192,4 +199,43 @@ public static void assertRetentionLeasesAdvanced(Client client, String indexName
...
         });
     }
+
+    /**
+     * Persist the global checkpoint on all shards of the given index into disk.
+     * This makes sure that the persisted global checkpoint on those shards will equal to the in-memory value.
+     *
+     * Uses the default {@link ESIntegTestCase#internalCluster()}.
+     */
+    public static void persistGlobalCheckpointOnPrimaryShards(String index) throws IOException {
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:211]: I’m wondering whether this helper should be a bit more generic. Right now it reads the primary’s latest op sequence number and then asks only the primary to persist that value _as the global checkpoint_, which may confuse future readers. On an index with replicas, the replication-tracker global checkpoint can legitimately lag the primary’s max seq no, so this helper could fail but with the current implementation it might not be clear why. 
Would it make sense to take the latest op from the primary but then sync that checkpoint on every shard (primaries and replicas)? That would still cover this test while being safer and clearer for broader reuse.

**Review by inespot — COMMENTED** [review]
A small question and nit!

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 6 above)
Comment (inespot) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:211]: Discussed in Slack :) Still think it might worth making the javadoc a tiny bit more explicit, but will leave it up to you!

**Review by inespot — APPROVED** [review]
Thanks for the iterations!

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 6 above)
Comment (michalborek) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:211]: Yeah, I agree on the javadoc. I'm gonna fix the log line above and improve the javadoc. The method may be improved in the future if needed. Thanks a lot Ines, I do appreciate these comments!

**Review by lkts — APPROVED** [review]
Thank you!
