### PR TITLE
Fixed missed stopping of SchedulerEngine

### LINKED ISSUE #38875: ArrayCompareConditionSearchTests thread leak suite failure
ArrayCompareConditionSearchTests test suite is flaky due to the integ cluster's 
SchedulerEngine's thread `trigger_engine_scheduler` not shutting down in time.

failure instance in CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/240/console

num occurrences: 6 times in last 6 months.

stacktrace:

```
ERROR   0.00s J2 | ArrayCompareConditionSearchTests (suite) <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.xpack.watcher.condition.ArrayCompareConditionSearchTests: 
   >    1) Thread[id=337, name=elasticsearch[node_sm1][trigger_engine_scheduler][T#1], state=TIMED_WAITING, group=TGRP-ArrayCompareConditionSearchTests]
   >         at java.base@12/jdk.internal.misc.Unsafe.park(Native Method)
   >         at java.base@12/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
   >         at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   >         at java.base@12/java.lang.Thread.run(Thread.java:835)
   > 	at __randomizedtesting.SeedInfo.seed([3D43839813A5AEA5]:0)Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   >    1) Thread[id=337, name=elasticsearch[node_sm1][trigger_engine_scheduler][T#1], state=TIMED_WAITING, group=TGRP-ArrayCompareConditionSearchTests]
   >         at java.base@12/jdk.internal.misc.Unsafe.park(Native Method)
   >         at java.base@12/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
   >         at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   >         at java.base@12/java.lang.Thread.run(Thread.java:835)
   > 	at __randomizedtesting.SeedInfo.seed([3D43839813A5AEA5]:0)
Completed [111/140] on J2 in 18.31s, 1 test, 2 errors <<< FAILURES!
```

RollupIT had the same [problem](https://github.com/elastic/elasticsearch/issue/31258) because it leverages the SchedulerEngine, its [solution](https://github.com/elastic/elasticsearch/pull/31977) was to move away from integ tests and rewrite the test as rest tests. It looks like this test suite can do the same.

### PR DESCRIPTION
**Pull request by jaymode**
The SchedulerEngine is used in several places in our code and not all
of these usages properly stopped the SchedulerEngine, which could lead
to test failures due to leaked threads from the SchedulerEngine. This
change adds stopping to these usages in order to avoid the thread leaks
that cause CI failures and noise.

Closes #38875

### CODE REVIEW

**Comment by jaymode** [comment]
Hit failure fixed by #39198

@elasticmachine  run elasticsearch-ci/default-distro

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycle.java [hunk 1]
```diff
@@ -137,6 +138,12 @@ protected Clock getClock() {
         }
         indexLifecycleInitialisationService.set(new IndexLifecycleService(settings, client, clusterService, threadPool,
                 getClock(), System::currentTimeMillis, xContentRegistry));
+        clusterService.addLifecycleListener(new LifecycleListener() {
```
Comment (talevy) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycle.java]: IndexLifecycle Plugin closes the scheduler when it itself is closed. Is this not done by the node 
where it calls close() on all the plugins?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java [hunk 2]
```diff
@@ -53,23 +53,20 @@
     private final PolicyStepsRegistry policyRegistry;
     private final IndexLifecycleRunner lifecycleRunner;
     private final Settings settings;
-    private final ThreadPool threadPool;
-    private Client client;
     private ClusterService clusterService;
     private LongSupplier nowSupplier;
     private SchedulerEngine.Job scheduledJob;
+    private boolean closed = false;
```
Comment (talevy) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java]: I think the signal of whether the scheduler is shutdown should be 
contained within the SchedulerEngine. is this not the same as checking `engine.isShutdown()`:

```diff
--- a/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/scheduler/SchedulerEngine.java
+++ b/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/scheduler/SchedulerEngine.java
@@ -123,6 +123,11 @@ public class SchedulerEngine {
         jobs.forEach(this::add);
     }
 
+
+    public boolean isShutdown() {
+        return scheduler.isShutdown();
+    }
+
     public void stop() {
         scheduler.shutdownNow();
         try {
```

**Review by talevy — COMMENTED** [review]
I haven't looked at the stuff outside of ILM, but I had some questions
around the ILM changes.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycle.java (hunk 1 above)
Comment (jaymode) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycle.java]: It does but I think we may want to stop before then. The node close mechanism calls `stop()` first, which stops the cluster service but the IndexLifecycle job can still run before the plugin is actually closed. That said, I can remove this part of the change since I don't think it will actually affect the issue at hand.

**Comment by jaymode** [comment]
@talevy thanks for reviewing. I simplified this so that there are not changes to persistent tasks but instead use closing of the plugin to terminate the SchedulerEngine. The change to IndexLifecycle is a bit ugly due to the lazy initialization. Essentially we don't want concurrent calls to the method that creates the SchedulerEngine and close otherwise we might actually miss closing the SchedulerEngine.

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleServiceTests.java [hunk 3]
```diff
@@ -108,6 +110,7 @@ public void prepareServices() {
 
     @After
     public void cleanup() {
+        when(clusterService.lifecycleState()).thenReturn(State.STOPPED);
```
Comment (talevy) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleServiceTests.java]: should this randomize between State.STOPPED and State.CLOSED?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java [hunk 4]
```diff
@@ -265,4 +270,8 @@ public void submitOperationModeUpdate(OperationMode mode) {
         clusterService.submitStateUpdateTask("ilm_operation_mode_update",
             new OperationModeUpdateTask(mode));
     }
+
+    private static boolean isStoppedOrClosed(State state) {
```
Comment (talevy) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java]: this doesn't feel like it belongs in this class, but since it doesn't seem to be used elsewhere, I think 
it is reasonable to leave here for now. Might help to add javadocs explaining the nature of this check
and why using it in the assertion above is acceptable

Comment (jaymode) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java]: How about I make it a non static method with the name `isClusterServiceStoppedOrClosed` that takes no arguments? This would be in addition to javadocs

Comment (talevy) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleService.java]: sure!

**Review by talevy — APPROVED** [review]
thanks Jay!

**Comment by talevy** [comment]
I hope this fixes the leakage
