### PR TITLE
[ML] Make inference timeout test more reliable

### LINKED ISSUE #81091: [CI][ML] PyTorchModelIT testEvaluateWithMinimalTimeout failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/irafccgouilyk
https://gradle-enterprise.elastic.co/s/vgysxwentnox6

**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluateWithMinimalTimeout" \
  -Dtests.seed=82882C0276D19551 \
  -Dtests.locale=fr-CH \
  -Dtests.timezone=Europe/Dublin \
  -Druntime.java=17
```

**Reproduces locally?**:
No

**Applicable branches**:
8.1, 8.0

**Failure history**:

**Failure excerpt**:
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown
	at __randomizedtesting.SeedInfo.seed([82882C0276D19551:65FE53F0D91AAB91]:0)
	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2874)
	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2860)
	at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluateWithMinimalTimeout(PyTorchModelIT.java:203)
```

### PR DESCRIPTION
**Pull request by davidkyle**
#81091 shows that `PyTorchModelIT::testEvaluateWithMinimalTimeout` is not reliable as the timeout does not always occur. 
The test can be made robust by relaxing the assertion to say that if an error occurs it must be a timeout error. 

This also changes the HTTP status code from too many requests (429) to request timeout (408) 

Closes #81091

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java [hunk 1]
```diff
@@ -297,7 +297,7 @@ void onTimeout() {
             if (notified.compareAndSet(false, true)) {
                 processContext.getResultProcessor().ignoreResposeWithoutNotifying(String.valueOf(requestId));
                 listener.onFailure(
-                    new ElasticsearchStatusException("timeout [{}] waiting for inference result", RestStatus.TOO_MANY_REQUESTS, timeout)
+                    new ElasticsearchStatusException("timeout [{}] waiting for inference result", RestStatus.REQUEST_TIMEOUT, timeout)
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java:300]: ❤️ 

Good change. This is left over from before we had queueing back-pressure as the signal for too many requests.

**Review by benwtrent — APPROVED** [review]
