### PR TITLE
Fix multi-level breadth-first aggregations.

### LINKED ISSUE #9823: Aggs: breadth_first does not work on several levels
Probably introduced in #9544 since I can reproduce the issue on master but not 1.x. The following recreation generates an error: `Deferred collectors cannot be collected directly. They must be collected through the recording wrapper`.

```
DELETE test

PUT test
{
  "mappings": {
    "test": {
      "properties": {
        "a": {
          "type": "string",
          "index": "no",
          "doc_values": "yes"
        },
        "b": {
          "type": "string",
          "index": "no",
          "doc_values": "yes"
        },
        "c": {
          "type": "string",
          "index": "no",
          "doc_values": "yes"
        }
      }
    }
  }
}

PUT test/test/1
{
  "a": "foo",
  "b": "bar",
  "c": "baz"
}

GET test/_search
{
  "aggs": {
    "a_terms": {
      "terms": {
        "field": "a",
        "collect_mode": "breadth_first"
      },
      "aggs": {
        "b_terms": {
          "terms": {
            "field": "b",
            "collect_mode": "breadth_first"
          },
          "aggs": {
            "c_terms": {
              "terms": {
                "field": "c"
              }
            }
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by jpountz**
The refactoring in #9544 introduced a regression that broke multi-level
aggregations using breadth-first. This was due to sub-aggregators creating
deferred collectors before their parent aggregator and then the parent
aggregator trying to collect sub aggregators directly instead of going through
the deferred wrapper.

This commit fixes the issue but we should try to simplify all the pre/post
collection logic that we have.

Also `breadth_first` is now automatically ignored if the sub aggregators need
scores (just like we ignore `execution_mode` when the value does not make sense
like using ordinals on a script).

Close #9823

### CODE REVIEW

**Comment by jpountz** [comment]
@colings86 Would you mind reviewing this change?

File: src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java [hunk 1]
```diff
@@ -76,18 +76,20 @@ public void preProcess(SearchContext context) {
...
             try {
                 aggregators = context.aggregations().factories().createTopLevelAggregators(aggregationContext);
+                for (int i = 0; i < aggregators.length; i++) {
+                    if (aggregators[i] instanceof GlobalAggregator == false) {
+                        collectors.add(aggregators[i]);
+                    }
+                }
+                context.aggregations().aggregators(aggregators);
+                final BucketCollector collector = BucketCollector.wrap(collectors);
+                collector.preCollection();
```
Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java]: Can the these two lines not be put inside of the if statement so we don't create the wrapper unless we are going to use it?

File: src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java [hunk 2]
```diff
@@ -120,6 +122,7 @@ public void execute(SearchContext context) throws ElasticsearchException {
                 query = new FilteredQuery(query, searchFilter);
             }
             try {
+                collector.preCollection();
```
Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java]: Is this needed here? Will this not have already been called in the preProcess method?

File: src/main/java/org/elasticsearch/search/aggregations/bucket/DeferringBucketCollector.java [hunk 3]
```diff
@@ -138,6 +138,9 @@ public void replay(long... selectedBuckets) throws IOException {
         this.selectedBuckets = hash;
 
         collector.preCollection();
+        if (collector.needsScores()) {
+            throw new ElasticsearchIllegalStateException("Cannot defer if scores are needed");
+        }
```
Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/bucket/DeferringBucketCollector.java]: Is there any way to do this check earlier? maybe in the preCollection method? Only wondering as we will have already done the main collect phase by this point so it would be nice to fail faster if we can

File: src/test/java/org/elasticsearch/search/aggregations/bucket/TopHitsTests.java [hunk 4]
```diff
@@ -531,37 +529,6 @@ public void testFailWithSubAgg() throws Exception {
             assertThat(e.getMessage(), containsString("Aggregator [top_tags_hits] of type [top_hits] cannot accept sub-aggregations"));
         }
     }
-    
-    @Test
```
Comment (colings86) [inline src/test/java/org/elasticsearch/search/aggregations/bucket/TopHitsTests.java]: As we have changed the functionality, should we now have a test which explicitly makes sure the aggregation is run when you run top hits on a breath_first terms agg? i.e. confirm that the setting is indeed ignored. Or is this already done elsewhere?

**Comment by colings86** [comment]
@jpountz left some comments

File: src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java (hunk 2 above)
Comment (jpountz) [inline src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java]: This is a different set of aggregators (the `global` ones) which run separately from regular aggregators. Regular aggregators are pre-collected in preProcess but global aggregators do everything in execute (they run on a MatchAllDocsQuery).

Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/AggregationPhase.java]: ah, ok, I missed that is was only for the global aggs. Maybe it would be a good idea to rename this collector to something like `globalsCollector` for clarity?

File: src/main/java/org/elasticsearch/search/aggregations/bucket/DeferringBucketCollector.java (hunk 3 above)
Comment (jpountz) [inline src/main/java/org/elasticsearch/search/aggregations/bucket/DeferringBucketCollector.java]: This is already checked earlier in TermsAggregator.shouldDefer. I see it as an invariant check.

**Comment by jpountz** [comment]
@colings86 Pushed a new commit

File: src/main/java/org/elasticsearch/search/aggregations/bucket/DeferringBucketCollector.java (hunk 3 above)
Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/bucket/DeferringBucketCollector.java]: ok, fair enough then

**Comment by colings86** [comment]
LGTM
