### PR TITLE
ESQL: Fix async query inconsistent headers

### LINKED ISSUE #135042: ES|QL `GET _query/async/{id}` returns inconsistent headers
### Elasticsearch Version

9.2.0-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

When an ES|QL async query is submitted (`POST _query/async`), the headers in the response contain both a `x-elasticsearch-async-id` and `x-elasticsearch-async-is-running`:

```json
{
  "x-elasticsearch-async-is-running": "?1",
  "x-elastic-product": "Elasticsearch",
  "transfer-encoding": "chunked",
  "x-opaque-id": "eb265ac8-a1ef-4d93-9e78-e5a50845d6df;kibana:application:discover:new;application:discover:new",
  "content-type": "application/vnd.elasticsearch+json;compatible-with=9",
  "took-nanos": "201111334",
  "x-elasticsearch-async-id": "FnRUYVdrbElOUUR1VUdCUm1xZ3hHVncdd2RJMUtWU01SQlNmQk1icFgtNGp4QTo1NzU5MTY="
}
```

If the query takes a bit of time, then we poll on the ID returned in the first request. While the query is still running, the response headers from polling (`GET _query/async/{id}`) do *not* contain the `x-elasticsearch-async-id` and `x-elasticsearch-async-is-running` headers:

```json
{
  "x-elastic-product": "Elasticsearch",
  "transfer-encoding": "chunked",
  "x-opaque-id": "5f8c8392-b269-496d-8c3e-76508e388cab;kibana:application:discover:new;application:discover:new",
  "content-type": "application/json",
  "took-nanos": "204451667"
}
```

However, when the request completes, the response from polling (still `GET _query/async/{id}`) do contain these headers:

```json
{
  "x-elasticsearch-async-is-running": "?0",
  "x-elastic-product": "Elasticsearch",
  "transfer-encoding": "chunked",
  "warning": "299 Elasticsearch-9.2.0-09250da4bdc785e783e9dbb221b489d665fa91b4 \"No limit defined, adding default limit of [1000]\"",
  "x-opaque-id": "0aefa8fb-0e42-4488-931d-da573eb8ecfe;kibana:application:discover:new;application:discover:new",
  "content-type": "application/json",
  "took-nanos": "17916093875",
  "x-elasticsearch-async-id": "FnRUYVdrbElOUUR1VUdCUm1xZ3hHVncdd2RJMUtWU01SQlNmQk1icFgtNGp4QTo1NzU5MTY="
}
```

These headers should be consistently returned from the endpoint regardless of the status of the underlying query. For context, the `is-running` header is important in Kibana to determine whether we should continue polling.

### Steps to Reproduce

```
POST /_query/async?drop_null_columns
{"wait_for_completion_timeout":"200ms","keep_on_completion":true,"keep_alive":"60000ms","query":"FROM filebeat-* METADATA _index\n  | EVAL buckets = DATE_TRUNC(5 minute, @timestamp), delay = DELAY(10ms)\n  | STATS count = COUNT(*) BY buckets, delay","locale":"en","include_ccs_metadata":true,"filter":{"bool":{"must":[],"filter":[{"range":{"@timestamp":{"format":"strict_date_optional_time","gte":"2025-09-18T21:38:06.992Z","lte":"2025-09-18T21:53:06.992Z"}}}],"should":[],"must_not":[]}}}

// After a few seconds, poll every few seconds
GET /_query/async/{id}?wait_for_completion_timeout=200ms&keep_alive=60000ms&drop_null_columns=true
```

The latter query returns inconsistent headers.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/135042

This PR:
- Fixes the get-result not always returning the expected headers
- Fixes the non-async query incorrectly returning the "is running" async header

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryResponse.java [hunk 1]
```diff
@@ -208,7 +208,7 @@ public boolean isRunning() {
     }
 
     public boolean isAsync() {
-        return isRunning;
+        return isAsync;
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlQueryResponse.java:211]: This was only being used on a test, so changing it is safe

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlAsyncGetResultsAction.java [hunk 2]
```diff
@@ -75,14 +78,21 @@ public Writeable.Reader<EsqlQueryResponse> responseReader() {
...
     /**
-     * Unwraps the exception in the case of failure. This keeps the exception types
-     * the same as the sync API, namely ParsingException and VerificationException.
+     * Adds async headers, and unwraps the exception in the case of failure.
+     * <p>
+     *     This keeps the exception types the same as the sync API, namely ParsingException and VerificationException.
+     * </p>
      */
-    static <R> ActionListener<R> unwrapListener(ActionListener<R> listener) {
+    ActionListener<EsqlQueryResponse> unwrapListener(String asyncExecutionId, ActionListener<EsqlQueryResponse> listener) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlAsyncGetResultsAction.java:86]: I could rename this method, listening to better names here. I was unironically considering switching it to "wrapListener()"

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 3]
```diff
@@ -669,6 +669,11 @@ public enum Cap {
          */
         ASYNC_QUERY_STATUS_HEADERS,
 
+        /**
```
Comment (ncordon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:672]: Do we need the `ASYNC_QUERY_STATUS_HEADERS` capability anymore?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlQueryAction.java [hunk 4]
```diff
@@ -288,7 +288,20 @@ private void innerExecute(Task task, EsqlQueryRequest request, ActionListener<Es
...
                 recordCCSTelemetry(task, executionInfo, request, null);
                 planExecutor.metrics().recordTook(executionInfo.overallTook().millis());
-                listener.onResponse(toResponse(task, request, configuration, result));
+                var response = toResponse(task, request, configuration, result);
+                assert response.isAsync() == request.async() : "The response must be async if the request was async";
+
+                if (response.isAsync()) {
+                    if (response.asyncExecutionId().isPresent()) {
+                        String asyncExecutionId = response.asyncExecutionId().get();
+                        threadPool.getThreadContext().addResponseHeader(AsyncExecutionId.ASYNC_EXECUTION_ID_HEADER, asyncExecutionId);
```
Comment (ncordon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlQueryAction.java:297]: Dummy question: why do we need this duplicated (in `TransportEsqlAsyncGetResultsAction.java` also)?

**Review by ncordon — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java (hunk 3 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:672]: Unless in snapshot or some other special cases, we usually don't remove them.
Also, a 8.19 server could be executing tests against this one ([rest compatibility tests](https://docs.elastic.dev/elasticsearch-team/esql/contributing/testing#backward-compatibility-testing)), and this one should say "Yes, I can handle _that_".

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlQueryAction.java (hunk 4 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlQueryAction.java:297]: Async queries have 2 endpoints: `POST _query/async` to execute the query, and `GET _query/async/<id>`.

The bug was that we already had the headers for query execution (Here I just refactored it a bit), but the "get" class wasn't setting them.

It worked when the GET returned a result, as the headers are stored with it. But before it had the result, there were no headers.

**Review by dnhatn — APPROVED** [review]
Looks great. Thanks Ivan!
