### PR TITLE
Consider error_trace supported by all endpoints

### LINKED ISSUE #109612: The `error_trace` parameter should be considered supported on all REST endpoints
### Elasticsearch Version

8.14

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

When a `RestHandler` specifies its set of `supportedQueryParameters`, incoming requests will be validated to ensure they contain only the supported set of parameters. 

There are some query parameters that are interpreted by the REST infrastructure and available on every endpoint. They are considered "supported" by every endpoint without every endpoint having to list them in their `supportedQueryParameters`. `error_trace` is missing from that set, [despite being available on every endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-error-options).

### Steps to Reproduce

Specify `supportedQueryParameters` for an endpoint. Send a request to that endpoint including `error_trace=true`.

The request will be rejected due to an unsupported parameter.

It should not be rejected.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nicktindall**
Closes #109612

I had a go at fixing this, I can see why `error_trace` wasn't included in the first place, the other `ALWAYS_SUPPORTED` parameters are all consumed by `AbstractRestChannel`. `error_trace` isn't consumed until we create the `RestResponse`, so it won't be listed as consumed when we check for unconsumed parameters.

There is API for specifying response parameters (which we exclude from the unconsumed check) but it's overridable, so I don't know the ideal place to put the parameter(s) that `RestResponse` consumes.

This is one approach, feel free to suggest a better one.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/rest/RestResponse.java [hunk 1]
```diff
@@ -37,6 +37,7 @@
 public final class RestResponse implements Releasable {
 
     public static final String TEXT_CONTENT_TYPE = "text/plain; charset=UTF-8";
+    public static final Set<String> RESPONSE_PARAMS = Set.of("error_trace");
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/rest/RestResponse.java:40]: It felt right for `RestResponse` to specify which parameters it consumed? not sure if this is the best way to go about it.

Comment (thecoop) [reply server/src/main/java/org/elasticsearch/rest/RestResponse.java:40]: I think so - this is kinda short-term anyway whilst we look at consolidating the validation steps

**Review by thecoop — APPROVED** [review]
This is good enough to get things working. We'll be looking at all this properly when we come to consolidate parameter validation
