### PR TITLE
BlendedTermQuery's equals method should consider boosts

### LINKED ISSUE #48184: BlendedTermQuery's equals method should not disregard boosts
Currently the BlendedTermQuerys `equals()` method only checks equality of the terms it contains, not of the boosts associated to them.
This is an unexpected behaviour and a little suprising e.g. when using equality checks in tests.

### PR DESCRIPTION
**Pull request by cbuescher**
This changes the queries equals() method so that the boost factors for each term
are considered for the equality calculation. This means queries are only equal
if both their terms and associated boosts match. The ordering of the terms
doesn't matter as before, which is why we internally need to sort the terms and
boost for comparison on the first equals() call like before. Boosts that are
`null` are considered equal to boosts of 1.0f because topLevelQuery() will only
wrap into BoostQuery if boost is not null and different from 1f.

Closes #48184

### CODE REVIEW

File: server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java [hunk 1]
```diff
@@ -243,36 +243,82 @@ public String toString(String field) {
...
+        public boolean equals(Object o) {
+            if (this == o) {
+                return true;
+            }
+            if (o instanceof TermAndBoost == false) {
+                return false;
+            }
+
+            TermAndBoost that = (TermAndBoost) o;
+            return term.equals(that.term) && boost == that.boost;
```
Comment (mayya-sharipova) [inline server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java]: should we compare boosts as `Float.compare(boost, that.boost) ==0` ?

**Review by mayya-sharipova — APPROVED** [review]
thanks @cbuescher. Nice addition.

Not completely related to your PR, I wonder how ES `BlendedTermQuery` is related to Lucene's [BlendedTermQuery](https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/search/BlendedTermQuery.java)?

**Comment by cbuescher** [comment]
> Not completely related to your PR, I wonder how ES `BlendedTermQuery` is related to Lucene's [BlendedTermQuery](https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/search/BlendedTermQuery.java)?

I don't really know tbh. but on cursory inspection they seem to be working differently, e.g. the way they rewrite against an IndexReader seem to follow different logic (the Lucene one having different RewriteMethods while the ES ones offers to overwrite topLevelQuery(), which in the one case I see produces a DisjunctionMaxQuery). 
It might be interesting to see how both versions differe at this point and if we could merge them at some point.
