### PR TITLE
[Transform] Forward indexServiceSafe exceptions to listener

### LINKED ISSUE #108418: [Transforms] IndexNotFoundException in GetCheckpoint
### Description

```java
[<>] uncaught exception in thread [elasticsearch[<>][<>][<>]]
org.elasticsearch.index.IndexNotFoundException: no such index [<>]
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:570) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.xpack.transform.action.TransportGetCheckpointNodeAction.getGlobalCheckpoints(TransportGetCheckpointNodeAction.java:86) ~[?:?]
	at org.elasticsearch.xpack.transform.action.TransportGetCheckpointAction.getCheckpointsFromNodes(TransportGetCheckpointAction.java:239) ~[?:?]
	at org.elasticsearch.xpack.transform.action.TransportGetCheckpointAction.lambda$resolveIndicesAndGetCheckpoint$1(TransportGetCheckpointAction.java:147) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:186) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:39) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:214) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27) ~[elasticsearch-8.12.2.jar:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:39) ~[elasticsearch-8.12.2.jar:?]
```

### PR DESCRIPTION
**Pull request by prwhelan**
IndexService.indexServiceSafe can throw an IndexNotFoundException while getting the Global Checkpoints. 
 In theory, any exception in TransportGetCheckpointNodeAction should be forwarded to the listener.

Fix #108418

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportGetCheckpointNodeAction.java [hunk 1]
```diff
@@ -83,17 +86,27 @@ protected static void getGlobalCheckpoints(
...
+                final IndexShard indexShard = indexService.getShard(shardId.id());
+
+                checkpointsByIndexOfThisNode.computeIfAbsent(shardId.getIndexName(), k -> {
+                    long[] seqNumbers = new long[indexService.getIndexSettings().getNumberOfShards()];
+                    Arrays.fill(seqNumbers, SequenceNumbers.UNASSIGNED_SEQ_NO);
+                    return seqNumbers;
+                });
+                checkpointsByIndexOfThisNode.get(shardId.getIndexName())[shardId.getId()] = indexShard.seqNoStats().getGlobalCheckpoint();
+                ++numProcessedShards;
+            } catch (Exception e) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportGetCheckpointNodeAction.java:101]: The PR description says that the `IndexNotFoundException` is forwarded but in fact **every** exception is forwarded here.
I think the code is ok, just please update PR description.

**Review by przemekwitek — APPROVED** [review]
LGTM
