### PR TITLE
SQL: Fix result column names for CAST

### LINKED ISSUE #33571: SQL: column names for CASTed fields is incorrectly handled
Scenario 1:

```
sql> SELECT CAST(MAX("salary") AS INTEGER), DAYNAME("hire_date") day_name FROM "test_emp" GROUP BY DAYNAME("hire_date") HAVING MAX("salary") > 50000 ORDER BY DAYNAME("hire_date");
  MAX(salary)  |   day_name
---------------+---------------
74572.0        |Friday
68431.0        |Monday
74970.0        |Saturday
56415.0        |Sunday
67492.0        |Thursday
73578.0        |Tuesday
74999.0        |Wednesday
```

This SELECT is about a CAST AS INTEGER and the column name doesn't include CAST in it.

Scenario 2:

```
sql> SELECT CAST(MAX("salary") AS DOUBLE), DAYNAME("hire_date") day_name FROM "test_emp" GROUP BY DAYNAME("hire_date") HAVING MAX("salary") > 50000 ORDER BY DAYNAME("hire_date");
CAST(MAX(salary))|   day_name
-----------------+---------------
74572.0          |Friday
68431.0          |Monday
74970.0          |Saturday
56415.0          |Sunday
67492.0          |Thursday
73578.0          |Tuesday
74999.0          |Wednesday
```

In this second case `CAST` is present in the column name but `AS DOUBLE` is missing.

### PR DESCRIPTION
**Pull request by matriv**
Previously, when an non-pruned cast (casting as a different
data type) got applied on a table column in the `SELECT` clause,
the name of the result column didn't contain the target data type
of the cast, e.g.:

  SELECT CAST(MAX(salary) AS DOUBLE) FROM "test_emp"

returned as column name:

  CAST(MAX(salary))

instead of:

  CAST(MAX(salary) AS DOUBLE)

Closes #33571

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java [hunk 1]
```diff
@@ -111,4 +111,11 @@ public boolean equals(Object obj) {
     public String toString() {
         return functionName() + "(" + field().toString() + " AS " + to().sqlName() + ")#" + id();
     }
-}
\ No newline at end of file
+
+    @Override
+    public String name() {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java]: Isn't `super.name + "AS " + to().sqlName() enough? What's the last character in super.name() that needs removing?

LGTM otherwise.

**Review by costin — COMMENTED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java]: Your suggestion would give: `CAST(SUM(salary))AS DOUBLE`, so I need to add the AS .. before the final closing `)`.

Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java]: Got it - thanks.

**Comment by matriv** [comment]
Pushed fixup. Please check again.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
Backported to `6.x` -> 7791c89084404e72166d63fa4e68d7cf1514e26c
