### PR TITLE
Reindex should gracefully handle when _source is disabled

### LINKED ISSUE #17666: Better handling when _source is disabled for reindex api
**Elasticsearch version**: 2.3.1

**Description of the problem including expected versus actual behavior**:

When _source is disabled, reindex api throws a NPE. 

**Steps to reproduce**:
 1.  Create an index with a type that has _source disabled
 2.  Create a document in the index
 3.  Use the reindex api and you will see:

```
{
   "error": {
      "root_cause": [
         {
            "type": "null_pointer_exception",
            "reason": null
         }
      ],
      "type": "null_pointer_exception",
      "reason": null
   },
   "status": 500
}
```

**Provide logs (if relevant)**:

```
[2016-04-11 15:39:45,057][WARN ][rest.suppressed          ] /_reindex Params: {}
java.lang.NullPointerException
	at org.elasticsearch.common.compress.lzf.LZFCompressor.isCompressed(LZFCompressor.java:54)
	at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:74)
	at org.elasticsearch.common.compress.CompressorFactory.uncompressIfNeeded(CompressorFactory.java:118)
	at org.elasticsearch.search.internal.InternalSearchHit.sourceRef(InternalSearchHit.java:200)
	at org.elasticsearch.index.reindex.TransportReindexAction$AsyncIndexBySearchAction.buildIndexRequest(TransportReindexAction.java:152)
	at org.elasticsearch.index.reindex.AbstractAsyncBulkIndexByScrollAction.buildBulk(AbstractAsyncBulkIndexByScrollAction.java:90)
	at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction$2.doRun(AbstractAsyncBulkByScrollAction.java:199)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

While the reindex api requires _source, it will be nice to handle this situation better.

### PR DESCRIPTION
**Pull request by nik9000**
Closes #17666

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java [hunk 1]
```diff
@@ -86,6 +86,9 @@ protected BulkRequest buildBulk(Iterable<SearchHit> docs) {
         Map<String, Object> scriptCtx = null;
 
         for (SearchHit doc : docs) {
+            if (doc.isSourceEmpty()) {
+                throw new IllegalArgumentException("[" + doc.index() + "][" + doc.type() + "][" + doc.id() + "] didn't store _source");
```
Comment (colings86) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: Is the document having an empty source the same as a _source being disabled. Presumably I could have _source enabled on my index but I happen to have some documents which have no content (e.g. dirty data or a failed etl process on that document). Should we not actually check the mapping to determine if _source is disabled rather than letting one bad document fail an entire reindex?

Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: I can certainly check the mapping but I imagined that a document that made it into the index without any source always did so because the source was disabled. I'll play around and see if I can get that to happen without source being disabled.

I guess if it can happen then I can use an empty JSON structure as the source.

Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: I played with it a bit and wasn't able to cram an empty document into Elasticsearch without setting _source to false.

Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: Ok - it looks like the source can be empty if you don't request it. Since reindex lets you modify the fields parameter that could cause it. I think the right thing there is to prevent the user from modifying the fields parameter on the search request at all.

Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: I added another patch to this one to guard against the changes to fields which could get you to this point.

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java [hunk 2]
```diff
@@ -86,6 +86,14 @@ protected BulkRequest buildBulk(Iterable<SearchHit> docs) {
         Map<String, Object> scriptCtx = null;
 
         for (SearchHit doc : docs) {
+            if (doc.isSourceEmpty()) {
+                /*
+                 * Either the document didn't store _source or we didn't fetch it for some reason. Since we don't allow the user to
+                 * change the "fields" part of the search request it is unlikely that we got here because we didn't fetch _source.
+                 * Thus the error message assumes that it wasn't stored.
+                 */
+                throw new IllegalArgumentException("[" + doc.index() + "][" + doc.type() + "][" + doc.id() + "] didn't store _source");
```
Comment (colings86) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: Just tested and the following creates a document in Elasticsearch:

```
PUT test4/doc/1
{
  
}
```

Response:
```
{
  "_index": "test4",
  "_type": "doc",
  "_id": "1",
  "_version": 1,
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "created": true
}
```

So you can definitely create a document with no fields in ES. In this case I think it's wrong for us to throw any exception if we read a document from and index which has no source when re-indexing, we should in fact index it into the new index like any other document. So although I like the checks you added to stop source filtering when re-indexing, I don't think we should be throwing an IllegalArgumentException here.

Comment (jpountz) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: Looking at the impl of isSourceEmpty:

```
    public boolean isSourceEmpty() {
        return source == null;
    }
```
So I think it is badly named and will actually return false if a document is indexed with a json doc that has no fields? It would only return true if the source is not storred at all?

Comment (colings86) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: hmm ok, maybe we can change that method name to `hasSource()` to avoid further confusion and add a test to check that reindexing a document with no fields works?

Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: Fine by me. Want me to roll all that into this PR?

Comment (colings86) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: Sounds good to me

Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractAsyncBulkIndexByScrollAction.java]: I just pushed a change that does both.

**Comment by colings86** [comment]
Thanks @nik9000 LGTM now 😄

**Comment by nik9000** [comment]
Thanks for complaining about confusing things. It is the only way we make the software less confusing!
