### PR TITLE
SQL: Add support for FROZEN indices

### LINKED ISSUE #39377: Support for ignore_throttled parameter in /_xpack/sql request
Currently adding an `ignore_throttled=false` parameter to a `/_xpack/sql` request results in this error:

`request [/_xpack/sql] contains unrecognized parameter: [ignore_throttled]`

It therefore seems to be impossible (though happy to be proven wrong on this) to query frozen indices using SQL.  I'm guessing there are also other options (e.g. from `IndicesOptions`) that aren't supported yet for SQL queries but possibly could be.

### LINKED ISSUE #39390: SQL: Support Frozen indices
Introduced in 6.6, frozen indices support searches within certain constraints.
SQL should be able to detect them and run queries around them. Even better, it should chose the correct search options (such as `pre_filter_shard_size`).

Related to #39377

### PR DESCRIPTION
**Pull request by costin**
Allow querying of FROZEN indices both through dedicated SQL grammar
extension:
> SELECT field FROM FROZEN index

and also through driver configuration parameter, namely:
> index.include.frozen: true/false

Fix #39390
Fix #39377

### CODE REVIEW

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java [hunk 1]
```diff
@@ -42,14 +43,8 @@ public CsvSpecTestCase(String fileName, String groupName, String testName, Integ
...
         // TODO: https://github.com/elastic/elasticsearch/issues/40779
-        if ("time".equals(groupName)) {
-            try (Connection csv = csvConnection(testCase); Connection es = esJdbc(connectionProperties())) {
-                executeAndAssert(csv, es);
-            }
-        } else {
-            try (Connection csv = csvConnection(testCase); Connection es = esJdbc()) {
-                executeAndAssert(csv, es);
-            }
+        try (Connection csv = csvConnection(testCase); Connection es = esJdbc()) {
```
Comment (costin) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java]: @matriv The previous hack was unnecessary - the conditional should be addressed in `connectionProperties` and further more, `esJdbc()` actually calls `esJdbc(connectionProperties())` so the code was not only duplicated but also identical in results.

File: x-pack/plugin/sql/qa/src/main/resources/command.csv-spec [hunk 2]
```diff
@@ -188,49 +188,49 @@ TODAY          |SCALAR
 showTables
 SHOW TABLES;
 
-       name        |     type      
-logs               |BASE TABLE
-test_alias         |VIEW          
-test_alias_emp     |VIEW          
-test_emp           |BASE TABLE     
-test_emp_copy      |BASE TABLE     
+       name        |     type   |  native
```
Comment (costin) [inline x-pack/plugin/sql/qa/src/main/resources/command.csv-spec]: Still thinking whether the third column should be `native` or something else (`storage` doesn't fit either).

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryRequest.java [hunk 3]
```diff
@@ -33,12 +33,14 @@
     private static final ObjectParser<SqlQueryRequest, Void> PARSER = objectParser(SqlQueryRequest::new);
     static final ParseField COLUMNAR = new ParseField("columnar");
     static final ParseField FIELD_MULTI_VALUE_LENIENCY = new ParseField("field_multi_value_leniency");
+    static final ParseField INDEX_INCLUDE_FROZEN = new ParseField("index_include_frozen");
```
Comment (costin) [inline x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryRequest.java]: @bpintea this is a new parameter that drivers can pass in to allow all queries inside one connection to include frozen indices. If not, the user would have to manually mention this through `INCLUDE FROZEN` and `FROZEN`.

File: x-pack/plugin/sql/src/main/antlr/SqlBase.g4 [hunk 4]
```diff
@@ -50,9 +50,9 @@ statement
         )*
         ')')?
         statement                                                                                         #debug
-    | SHOW TABLES (tableLike=likePattern | tableIdent=tableIdentifier)?                                   #showTables
-    | SHOW COLUMNS (FROM | IN) (tableLike=likePattern | tableIdent=tableIdentifier)                       #showColumns
-    | (DESCRIBE | DESC) (tableLike=likePattern | tableIdent=tableIdentifier)                              #showColumns
+    | SHOW TABLES (INCLUDE FROZEN)? (tableLike=likePattern | tableIdent=tableIdentifier)?                 #showTables
```
Comment (costin) [inline x-pack/plugin/sql/src/main/antlr/SqlBase.g4]: This is the declarative approach for frozen which is useful when not using `index.include.frozen` (again `.` are used by drivers, `_` is used in rest).

File: x-pack/plugin/sql/src/main/antlr/SqlBase.g4 [hunk 5]
```diff
@@ -50,9 +50,9 @@ statement
...
+    | SHOW COLUMNS (INCLUDE FROZEN)? (FROM | IN) (tableLike=likePattern | tableIdent=tableIdentifier)     #showColumns
+    | (DESCRIBE | DESC) (INCLUDE FROZEN)? (tableLike=likePattern | tableIdent=tableIdentifier)            #showColumns
     | SHOW FUNCTIONS (likePattern)?                                                                       #showFunctions
     | SHOW SCHEMAS                                                                                        #showSchemas
     | SYS TABLES (CATALOG clusterLike=likePattern)?
```
Comment (costin) [inline x-pack/plugin/sql/src/main/antlr/SqlBase.g4]: Notice the `SYS` commands do not require `INCLUDE FROZEN` since these are meant only for drivers in which case the option is set through the configuration.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java [hunk 6]
```diff
@@ -408,14 +444,14 @@ public void resolveAsSeparateMappings(String indexWildcard, String javaRegex, Ac
     /**
      * Assemble an index-based mapping from the field caps (which is field based) by looking at the indices associated with
      * each field.
-     */
+                 */
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolver.java]: Looks like formatting got affected in merging -will follow up.

File: x-pack/plugin/sql/qa/src/main/resources/command.csv-spec (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/command.csv-spec]: I like `native` but how about `native_type` ?

**Review by matriv — COMMENTED** [review]
Looks great overall! Left some minor comments.

Could we have a test also for the translate api on a frozen index?

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java]: I don't get how this is addressed only for a specific file, in this case: `time.csv-spec`.

**Review by astefan — COMMENTED** [review]
LGTM in general. Left few comments.
Documentation will be added later?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java [hunk 7]
```diff
@@ -130,13 +132,14 @@ public void query(List<Attribute> output, QueryContainer query, String index, Ac
         client.search(search, l);
     }
 
-    public static SearchRequest prepareRequest(Client client, SearchSourceBuilder source, TimeValue timeout, String... indices) {
+    public static SearchRequest prepareRequest(Client client, SearchSourceBuilder source, TimeValue timeout, boolean includeFrozen,
+            String... indices) {
         SearchRequest search = client.prepareSearch(indices)
-                // always track total hits accurately
-                .setTrackTotalHits(true)
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java]: Good catch - merging error.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java]: It is not but then again, it wasn't before.
In other words, the if ("time".equals(groupName)) does the right thing but calling esJdbc(connectionProperties()) is the same as calling esJdbc() meaning the if and else branch end up calling the same code path.

File: x-pack/plugin/sql/qa/src/main/resources/command.csv-spec (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/qa/src/main/resources/command.csv-spec]: somewhat redundant - type, native type - plus should it be `native_type` or `native type`? A single word is much preferred.

File: x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryRequest.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlQueryRequest.java]: Opened https://github.com/elastic/elasticsearch-sql-odbc/pull/151. Note that the parameter is `false` by default.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java]: It's not the case, if you check again there are 2 different `connectionProperties()` involved there. and the one for the `time` sets the timezone to UTC where the other uses a random timezone.

File: x-pack/plugin/sql/qa/src/main/resources/command.csv-spec (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/command.csv-spec]: Imho the name of a previous column (`type`) is completely irrelevant of the next one, and I believe it's more clear to have it as `native_type`. And I would for sure vote for the `_` instead of a space: ` `.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/PreAnalyzer.java [hunk 8]
```diff
@@ -23,9 +24,9 @@
     public static class PreAnalysis {
         public static final PreAnalysis EMPTY = new PreAnalysis(emptyList());
 
-        public final List<TableIdentifier> indices;
+        public final List<Tuple<TableIdentifier, Boolean>> indices;
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/PreAnalyzer.java]: TableIdentifier is mapped to parsing and has a well defined scope - frozen is a property of a table not of its id (which is just another property).
Since in the future we might have other properties (potentially remote from CCS), I've retrofitted the tuple into a `TableInfo` class inside the analysis package.

File: x-pack/plugin/sql/qa/src/main/resources/command.csv-spec (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/qa/src/main/resources/command.csv-spec]: I opted for `kind` - one word, small (4 letters like the rest) and fairly accurate.

**Comment by costin** [comment]
> LGTM in general. Left few comments.
> Documentation will be added later?

Yes, I'd like to keep it separate since it would be easy to iterate over it in the CI without running the whole suite.

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CsvSpecTestCase.java]: @costin Did you check this ^^ ?

**Comment by costin** [comment]
Currently blocked by #41795

**Review by matriv — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
run elasticsearch-ci/1
