### PR TITLE
RestRequest parameter parsing should not cause 500 error

### LINKED ISSUE #112604: RestRequest parameter parsing should not cause 500 error
Currently, RestRequest can throw IllegalStateExceptions in a few places (e.g. "contentOrSourceParam") that results in 500 errors on the client side and e.g. turn up as warnings in the "rest.suppressed" error log. I believe they should mostly be 400s (Bad Request) instead.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently, RestRequest throws IllegalStateExceptions in a few places which leads to 500 errors on the client side and e.g. turn up as warnings in the "rest.suppressed" error log. By changing them to IllegalArgumentExceptions we can change these to 400 (Bad Request) error codes.

Closes #112604

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java [hunk 1]
```diff
@@ -321,7 +321,7 @@ public final BytesReference requiredContent() {
         if (hasContent() == false) {
             throw new ElasticsearchParseException("request body is required");
         } else if (xContentType.get() == null) {
-            throw new IllegalStateException("unknown content type");
+            throw new IllegalArgumentException("unknown content type");
```
Comment (ldematte) [inline server/src/main/java/org/elasticsearch/rest/RestRequest.java:324]: I see why you are making the change, but technically the IllegalStateException here was correct (since xContent is a field, not an argument).
Do you think this check could be moved at the time xContent is set (the ctor I think?).
That would make the IllegalArgumentException "more legit".
Alternatively, what about using one of our own exception types (ElasticsearchParseException, or a new one like XContentException)?

Comment (ldematte) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java:324]: > Moving to the ctor is not straight foward either because this is a static utility method that is used elsewhere.

That was my fear too. It would have been more fitting to throw a IAE where the argument is actually processed, but if it's not trivial, better not do it.

>  IllegalStateException also doesn't sound particularly fitting for this case

Yeah, reading the docs it does not seem like it's fitting - I thought more of an exception like "your class invariants are broken" or "the various fields in your class do not play well in this case".

TBH `ValidationException` seems better to me, but I'm fine either way.

**Review by ldematte — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java (hunk 1 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java]: 👍 I changed to ValidationException, hope I don't need to adapt more tests to get through CI

**Comment by cbuescher** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/112656)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
