### PR TITLE
Exclude patch versions from TransportVersionUtils

### LINKED ISSUE #139741: [CI] ClusterPersistentTasksCustomMetadataTests testMinVersionSerialization failing
**Build Scans:**
- [elasticsearch-intake #32601 / part1](https://gradle-enterprise.elastic.co/s/owu5esph7dvmo)
- [elasticsearch-intake #32565 / part1](https://gradle-enterprise.elastic.co/s/aid6g5lpzhja2)
- [elasticsearch-pull-request #110775 / part-1](https://gradle-enterprise.elastic.co/s/ki2qqstryrvdy)
- [elasticsearch-pull-request #110775 / part-1](https://gradle-enterprise.elastic.co/s/uajtutwl2dagw)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.persistent.ClusterPersistentTasksCustomMetadataTests.testMinVersionSerialization" -Dtests.seed=A74616C6B00BADC0 -Dtests.locale=se -Dtests.timezone=Asia/Novokuznetsk -Druntime.java=25
```

**Applicable branches:**
9.3

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.persistent.ClusterPersistentTasksCustomMetadataTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMinVersionSerialization'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: iterable containing ["test_compatible_version"]
     but: not matched: "test_incompatible_version"
```

**Issue Reasons:**
- [9.3] 4 failures in test testMinVersionSerialization (22.2% fail rate in 18 executions)
- [9.3] 2 failures in step part1 (22.2% fail rate in 9 executions)
- [9.3] 2 failures in step part-1 (22.2% fail rate in 9 executions)
- [9.3] 2 failures in pipeline elasticsearch-intake (22.2% fail rate in 9 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mark-vieira**
Patch versions break certain assumptions around temporality when comparing transport versions. For this reason, some tests that rely on methods in `TransportVersionUtils` may begin to fail in the presence of patch versions. To avoid this, we simply exclude patch version when requesting a random version, as well as prohibit patch versions as bound arguments to these methods.

Closes https://github.com/elastic/elasticsearch/issues/139740
Closes https://github.com/elastic/elasticsearch/issues/139741

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/TransportVersionUtils.java [hunk 1]
```diff
@@ -24,7 +24,8 @@
 public class TransportVersionUtils {
 
     private static final NavigableSet<TransportVersion> RELEASED_VERSIONS = Collections.unmodifiableNavigableSet(
-        new TreeSet<>(TransportVersion.getAllVersions())
+        // Exclude patch versions since they break the semantics of methods like `randomVersionBetween`
+        TransportVersion.getAllVersions().stream().filter(v -> v.isPatchVersion() == false).collect(Collectors.toCollection(TreeSet::new))
```
Comment (jdconrad) [inline test/framework/src/main/java/org/elasticsearch/test/TransportVersionUtils.java]: I wonder if this should create a new version where the patch version in the linked-list is always `null` as well, so supports won't check any patch versions unintentionally in tests.

File: server/src/main/java/org/elasticsearch/TransportVersion.java [hunk 2]
```diff
@@ -379,6 +379,18 @@ public boolean isPatchFrom(TransportVersion version) {
...
 
+    /**
+     * Returns {@code true} if this version is a patch version. Transport versions are generally monotoic, that is, when comparing
+     * transport versions via {@link #compareTo(VersionId)} a later version is also temporally "newer". This, however, is not the case
+     * for patch versions, as they can be introduced at any time. There may be cases where this distinction is important, in which case
+     * this method can be used to determine if a version is a patch, and therefore, may actually be temporally newer than "later" versions.
+     *
+     * @return whether this version is a patch version.
+     */
+    public boolean isPatchVersion() {
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/TransportVersion.java]: Could this be defined as an (internal) utility looking at id in TransportVersionUtils? That way it can only be within tests. I think we should avoid adding new methods like this that are really only for tests because they inevitably get used in production code and it makes it harder to change.

Comment (mark-vieira) [reply server/src/main/java/org/elasticsearch/TransportVersion.java]: Ah, yes. I didn't occur to me that the `id` field was public since this is a record. I'll do that.

**Review by jdconrad — APPROVED** [review]

**Comment by mark-vieira** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/140192)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
