### PR TITLE
ThreadPool: make sure no leaking threads are left behind in case of initialization failure

### LINKED ISSUE #9107: ThreadPool: make sure no leaking threads are left behind in case of initialization failure
Our `ThreadPool` constructor creates a couple of threads (scheduler and timer) which might not get shut down if the initialization of a node fails. A guice error might occur for example, which causes the `InternalNode` constructor to throw an exception. In this case the two threads are left behind, which is not a big problem when running es standalone as the error will be intercepted and the jvm will be stopped as a whole. It can become more of a problem though when running es in embedded mode, as we'll end up with lingering threads.

The steps to reproduce are a bit exotic: create a tribe node, and make sure one of its inner client nodes initialization fails. Whether the threads are left behind or not depends on when the failure happens, whether it happens before or after the `ThreadPool` has been initialized.

```
    @Test
    public void testThreadPoolLeakingThreadsWithTribeNode() {
        Settings settings = ImmutableSettings.builder()
                .put("node.name", "thread_pool_leaking_threads_tribe_node")
                .put("tribe.t1.cluster.name", "non_existing_cluster")
                 //trigger initialization failure of one of the tribes (doesn't require starting the node)
                .put("tribe.t1.plugin.mandatory", "non_existing").build();

        try {
            NodeBuilder.nodeBuilder().settings(settings).build();
        } catch(Throwable t) {
            //all good
            assertThat(t.getMessage(), containsString("mandatory plugins [non_existing]"));
        }
    }
```

I think creating threads on the constructor is quite bad already, even worse since we haven't started the node yet. In general I would love to have more lightweight constructors, especially since we use guice. I think we should delay the threads creation to the actual start phase of the node, but this requires quite some changes as we currently schedule executions (`threadPool.schedule`) from different objects constructors, which need the thread pool scheduler to be already initialized.

### PR DESCRIPTION
**Pull request by imotov**
Our ThreadPool constructor creates a couple of threads (scheduler and timer) which might not get shut down if the initialization of a node fails. A guice error might occur for example, which causes the InternalNode constructor to throw an exception. In this case the two threads are left behind, which is not a big problem when running es standalone as the error will be intercepted and the jvm will be stopped as a whole. It can become more of a problem though when running es in embedded mode, as we'll end up with lingering threads or testing an handling of initialization failures.

Closes #9107

### CODE REVIEW

**Comment by javanna** [comment]
I like it, LGTM

File: src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 1]
```diff
@@ -148,15 +147,16 @@ public ThreadPool(Settings settings, @Nullable NodeSettingsService nodeSettingsS
...
-            nodeSettingsService.addListener(new ApplySettings());
-        }
 
         TimeValue estimatedTimeInterval = settings.getAsTime("threadpool.estimated_time_interval", TimeValue.timeValueMillis(200));
         this.estimatedTimeThread = new EstimatedTimeThread(EsExecutors.threadName(settings, "[timer]"), estimatedTimeInterval.millis());
         this.estimatedTimeThread.start();
     }
 
+    public void setNodeSettingsService(NodeSettingsService nodeSettingsService) {
+        nodeSettingsService.addListener(new ApplySettings());
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: Should we add some safety that this method is called only once?

File: src/main/java/org/elasticsearch/node/Node.java [hunk 2]
```diff
@@ -198,10 +201,17 @@ public Node(Settings preparedSettings, boolean loadConfigSettings) {
...
             success = true;
         } finally {
             if (!success) {
                 nodeEnvironment.close();
+                threadPool.shutdown();
+                try {
+                    threadPool.awaitTermination(10, TimeUnit.SECONDS);
+                } catch (InterruptedException e) {
+                    Thread.currentThread().interrupt();
+                }
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/node/Node.java]: Maybe use ThreadPool.terminate instead?

File: src/main/java/org/elasticsearch/client/transport/TransportClient.java [hunk 3]
```diff
@@ -125,24 +126,39 @@ public TransportClient build() {
...
+                success = true;
+                return transportClient;
+            } finally {
+                if (!success) {
+                    threadPool.shutdown();
+                    try {
+                        threadPool.awaitTermination(10, TimeUnit.SECONDS);
+                    } catch (InterruptedException e) {
+                        Thread.currentThread().interrupt();
+                    }
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/client/transport/TransportClient.java]: ThreadPool.terminate?

**Comment by jpountz** [comment]
Left some suggestions but I like the change too!

**Comment by imotov** [comment]
@jpountz I pushed some changes. Could you take another look? Thanks!

File: src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 4]
```diff
@@ -91,13 +91,14 @@
 
     private final EstimatedTimeThread estimatedTimeThread;
 
+    private volatile boolean settingsListenerIsSet = false;
```
Comment (jpountz) [inline src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: I don't think we need the volatile here?

**Comment by jpountz** [comment]
LGTM, only one minor comment
