### PR TITLE
ESQL: allow DATE_PARSE to read the timezones

### LINKED ISSUE #117680: [ES|QL] date_parse seems to ignore timezone
### Elasticsearch Version

8.16.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux amd64 5.15.0-1032-gcp

### Problem Description

```
POST /_query
{
    "query": """
row message = "192.168.1.199 - - [12/Jul/2022:10:24:10 +0900] \"GET /cgi-bin/try/ HTTP/1.0\" 200 3005"
| grok message "%{COMMONAPACHELOG}"
| keep timestamp
| eval @timestamp = date_parse("dd/MMM/yyyy:HH:mm:ss Z", timestamp)
"""
}
```
produces
```
{
  "took": 15,
  "columns": [
    {
      "name": "timestamp",
      "type": "keyword"
    },
    {
      "name": "@timestamp",
      "type": "date"
    }
  ],
  "values": [
    [
      "12/Jul/2022:10:24:10 +0900",
      "2022-07-12T10:24:10.000Z"
    ]
  ]
}
```

but 
```
POST /_ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "date": {
          "field": "timestamp",
          "formats": [
            "dd/MMM/yyyy:HH:mm:ss Z"
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "timestamp": "12/Jul/2022:10:24:10 +0900"
      }
    }
  ]
}
```
produces
```
{
  "docs": [
    {
      "doc": {
        "_index": "index",
        "_version": "-3",
        "_id": "id",
        "_source": {
          "timestamp": "12/Jul/2022:10:24:10 +0900",
          "@timestamp": "2022-07-12T01:24:10.000Z"
        },
        "_ingest": {
          "timestamp": "2024-11-28T07:11:48.58392818Z"
        }
      }
    }
  ]
}
```

I suspect `date_parse` in ES|QL ignores the timezone offset. Will you look into it, please?

### Steps to Reproduce

You can run
```
POST /_query
{
    "query": """
row message = "192.168.1.199 - - [12/Jul/2022:10:24:10 +0900] \"GET /cgi-bin/try/ HTTP/1.0\" 200 3005"
| grok message "%{COMMONAPACHELOG}"
| keep timestamp
| eval @timestamp = date_parse("dd/MMM/yyyy:HH:mm:ss Z", timestamp)
"""
}
```
, which produces
```
{
  "took": 15,
  "columns": [
    {
      "name": "timestamp",
      "type": "keyword"
    },
    {
      "name": "@timestamp",
      "type": "date"
    }
  ],
  "values": [
    [
      "12/Jul/2022:10:24:10 +0900",
      "2022-07-12T10:24:10.000Z"
    ]
  ]
}
```

I think `@timestamp` should be "2022-07-12T01:24:10.000Z".

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by bpintea**
This just removes fixing a formatter to a timezone (UTC), allowing `DATE_PARSE` to correctly read timezones.

Fixes #117680.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java [hunk 1]
```diff
@@ -46,11 +46,24 @@ public static Iterable<Object[]> parameters() {
...
                         equalTo(1683244800000L)
                     )
                 ),
+                new TestCaseSupplier(
+                    "Timezoned Case",
+                    List.of(DataType.KEYWORD, DataType.KEYWORD),
+                    () -> new TestCaseSupplier.TestCase(
+                        List.of(
+                            new TestCaseSupplier.TypedData(new BytesRef("dd/MMM/yyyy:HH:mm:ss Z"), DataType.KEYWORD, "first"),
+                            new TestCaseSupplier.TypedData(new BytesRef("12/Jul/2022:10:24:10 +0900"), DataType.KEYWORD, "second")
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java:60]: nit: we could randomize this a bit (only on the hour of course, no need to complicate it too much)

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec [hunk 2]
```diff
@@ -494,6 +494,52 @@ b:datetime
 null
 ;
 
+evalDateParseWithTimezone
+required_capability: date_parse_tz
+row s = "12/Jul/2022:10:24:10 +0900" | eval d = date_parse("dd/MMM/yyyy:HH:mm:ss Z", s);
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec:499]: nit: it would be good to have at least one test that crosses midnight (we could complicate it more with months/years/leap day but IMHO it's overkill)

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks @bpintea 

I left just a couple of comments about tests.

**Review by costin — APPROVED** [review]
LGTM
