### PR TITLE
Distinguish no shutdowns case in NodeShutdownAllocationDecider

### LINKED ISSUE #89823: Indices with auto_expand_replicas are not replicated
### Elasticsearch Version

7.17.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Ubuntu 18.04

### Problem Description

Problem originally discussed [here](https://discuss.elastic.co/t/auto-expand-replicas-not-working-on-enrich-index/313569). See the complete discussion and the things I've tried there.

Summary
* 3 nodes cluster, all nodes have all roles (`node.roles` is not defined, so nodes have all roles)
* All system indices with `auto_expand_replicas: "0-all"` are not replicated. Problem exists on enrich indices, kibana indices, monitoring indices , etc.
* Problem can be reproduced with a regular, user-defined index simply by setting `auto_expand_replicas: "0-all"` in index settings as per the reproduction script below

On my cluster, the indices always have 0 replicas. I've tried to force set `number_of_replicas` to a higher value with no luck, value is reverted to 0 immediately. I've enabled TRACE logging on a few loggers around allocation, I've got plenty of logs but none mentioned the inability to replicate thoses indices...

Can you help troubleshoot the issue?

Thanks in advance,

Cheers,
David

### Steps to Reproduce

Kibana script
```
PUT /testing_auto_expand_replicas
{
  "settings": {
    "auto_expand_replicas": "0-all"
  }
}

GET /testing_auto_expand_replicas/_settings

GET _cluster/allocation/explain?include_yes_decisions
{
  "index": "testing_auto_expand_replicas",
  "shard": 0,
  "primary": true
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today the `NodeShutdownAllocationDecider` explains its `YES` decision as `this node is not shutting down` whether there are other node shutdowns ongoing or not. It'd be useful to distinguish these cases, so this commit refines the explanation to do so.

Closes #89823

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDecider.java [hunk 1]
```diff
@@ -27,16 +27,22 @@ public class NodeShutdownAllocationDecider extends AllocationDecider {
...
+    private static final Decision YES_EMPTY_SHUTDOWN_METADATA = Decision.single(Decision.Type.YES, NAME, "no nodes are shutting down");
+    private static final Decision YES_NODE_NOT_SHUTTING_DOWN = Decision.single(Decision.Type.YES, NAME, "this node is not shutting down");
+
     /**
      * Determines if a shard can be allocated to a particular node, based on whether that node is shutting down or not.
      */
     @Override
     public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, RoutingAllocation allocation) {
-        final SingleNodeShutdownMetadata thisNodeShutdownMetadata = allocation.nodeShutdowns().get(node.nodeId());
+        final var nodeShutdowns = allocation.nodeShutdowns();
```
Comment (grcevski) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDecider.java:38]: It looks like this logic to decide which message is reported can be common and extracted into a validation method. It could simplify making a unit test too.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDecider.java]: Good point, in fact there's no real need to have different messages for the allocate and auto-expand cases either so the whole thing can just be a single method. See f034829a3b981114428d240cf1780d322a2c8f5d.

**Review by grcevski — APPROVED** [review]
LGTM!
