### PR TITLE
ES|QL: fix null folding of nested COALESCE

### LINKED ISSUE #139344: ESQL: FoldNull can wrongly fold COALESCE to null
Reproducer:
```
ROW x = null
| EVAL z = COALESCE(x, "1")
| EVAL append_coalesce = MV_APPEND("2", COALESCE(x, "1"))
| EVAL append_z = MV_APPEND("2", z)

       x       |       z       |append_coalesce|   append_z    
---------------+---------------+---------------+---------------
null           |1              |null           |[2, 1]   
```
`append_coalesce` should be the same as `append_z`.

Looking at the change logger output, it looks like the problem is inside `FoldNull`:

```
[2025-12-11T10:09:59,716][TRACE][o.e.x.e.o.L.changes      ] [runTask-0] Rule logical.FoldNull applied with change
Limit[1000[INTEGER],false,false]                                                                                      = Limit[1000[INTEGER],false,false]
\_Eval[[COALESCE(x{r}#14,1[KEYWORD]) AS z#17, MVAPPEND(2[KEYWORD],COALESCE(x{r}#14,1[KEYWORD])) AS append_coalesce#20 ! \_Eval[[COALESCE(x{r}#14,1[KEYWORD]) AS z#17, null[KEYWORD] AS append_coalesce#20, MVAPPEND(2[KEYWORD],z{r}#17) AS ap
, MVAPPEND(2[KEYWORD],z{r}#17) AS append_z#23]]                                                                       ! pend_z#23]]
  \_Row[[null[NULL] AS x#14]]                                                                                         =   \_Row[[null[NULL] AS x#14]]
```

We shouldn't have folded to null because `COALESCE(null, "1")` should be `"1"`.

### PR DESCRIPTION
**Pull request by luigidellaquila**
COALESCE can't be folded if one of the children is null, even if it's nested inside other expressions.
The same applies to all the functions that don't have `Nullability.TRUE` (eg. `Case` and `MvUnion`)

Fixes: https://github.com/elastic/elasticsearch/issues/139344

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java [hunk 1]
```diff
@@ -36,23 +35,22 @@ public Expression rule(Expression e, LogicalOptimizerContext ctx) {
             }
         }
 
-        if (result != e) {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java:39]: Old QL code, no longer used

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec [hunk 2]
```diff
@@ -830,3 +830,13 @@ row x = 1
 a:keyword | z:integer | x:integer
 foo       | 1         | 9
 ;
+
+
+foldCoalesce
+required_capability: fix_fold_coalesce
+ROW x = null|  EVAL append_coalesce = MV_APPEND("2", COALESCE(x, "1"))
```
Comment (mouhc1ne) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec]: Small spacing typo.

**Review by mouhc1ne — APPROVED** [review]
LGTM.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java [hunk 3]
```diff
@@ -36,23 +35,22 @@ public Expression rule(Expression e, LogicalOptimizerContext ctx) {
...
+        if (e instanceof In in) {
             if (Expressions.isGuaranteedNull(in.value())) {
                 return Literal.of(in, null);
             }
         } else if (e instanceof Alias == false && e.nullable() == Nullability.TRUE
         // Non-evaluatable functions stay as a STATS grouping (It isn't moved to an early EVAL like other groupings),
         // so folding it to null would currently break the plan, as we don't create an attribute/channel for that null value.
             && e instanceof GroupingFunction.NonEvaluatableGroupingFunction == false
-            && Expressions.anyMatch(e.children(), Expressions::isGuaranteedNull)) {
+            && e.children().stream().anyMatch(FoldNull::isNull)) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java:46]: Can this be: 

```suggestion
            isNull(e)) {
```

Also, highly optional, streams might be heavy.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java [hunk 4]
```diff
@@ -36,23 +35,22 @@ public Expression rule(Expression e, LogicalOptimizerContext ctx) {
...
                 return Literal.of(e, null);
             }
         return e;
     }
 
-    protected Expression tryReplaceIsNullIsNotNull(Expression e) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java:55]: 👍

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec (hunk 2 above)
Comment (bpintea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec]: Maybe an extra test with a NULL literal?

**Review by bpintea — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/FoldNull.java:46]: Unfortunately it doesn't work. We only have to check that the children are not null, not the parent object, otherwise we'll also try to replace literals (it was my first implementation, and it resulted in several failures)
