### PR TITLE
[ES|QL]  Split large page in ValuesFromManyReader

### LINKED ISSUE #143314: [CI] HeapAttackSubqueryIT testManyRandomKeywordFieldsInSubqueryIntermediateResults failing
**Build Scans:**
- [elasticsearch-intake #35217 / part1](https://gradle-enterprise.elastic.co/s/htfkp2elmojzu)
- [elasticsearch-pull-request #123583 / part-1](https://gradle-enterprise.elastic.co/s/4l5aqcchuxx2g)

**Reproduction Line:**
```
./gradlew ":test:external-modules:test-esql-heap-attack:javaRestTest" --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackSubqueryIT.testManyRandomKeywordFieldsInSubqueryIntermediateResults" -Dtests.seed=2273E857AA8FB1B8 -Dtests.locale=vec -Dtests.timezone=America/Paramaribo -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.heap_attack.HeapAttackSubqueryIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testManyRandomKeywordFieldsInSubqueryIntermediateResults'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:39503], URI [/_nodes/stats], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
```

**Issue Reasons:**
- [main] 2 failures in test testManyRandomKeywordFieldsInSubqueryIntermediateResults (0.4% fail rate in 503 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #143177 
Fixes: #141203 
Fixes: #141202 
Fixes: #143314

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java [hunk 1]
```diff
@@ -94,8 +113,130 @@ void run(int offset) throws IOException {
...
+            int runStart = offset;
+            readRowStride(firstDoc);
+            int prevDoc = firstDoc;
+            int i = offset + 1;
+            long estimated = estimatedRamBytesUsed();
+            while (i < docs.getPositionCount() && estimated < operator.jumboBytes) {
+                int doc = docs.docs().getInt(i);
+                if (doc < prevDoc) {
+                    readColumnAtATimeBatch(runStart, i);
+                    resetReaders(ctx);
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java]: The method `sameShardNewSegment` should do this already. Probably ok to rename it.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java [hunk 2]
```diff
@@ -94,8 +113,130 @@ void run(int offset) throws IOException {
                  * loading in a way that is correct for the mapped field type, and then convert between that type and the desired type.
                  */
                 finalBuilders[f] = operator.fields[f].info.type()
-                    .newBlockBuilder(docs.getPositionCount(), operator.driverContext.blockFactory());
+                    .newBlockBuilder(docs.getPositionCount() - offset, operator.driverContext.blockFactory());
+            }
+            int bytesRefFieldCount = bytesRefFieldCount();
+            if (docs.singleShardSingleSegment() && bytesRefFieldCount >= operator.docSequenceBytesRefFieldThreshold) {
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromManyReader.java]: I think we'd be better off if we did this regardless of single-segment or not. Reset all the time.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/DocVector.java [hunk 3]
```diff
@@ -578,4 +578,40 @@ public Config mayContainDuplicates() {
...
+                return false;
+            }
+        }
+        return true;
+    }
+
+    /**
+     * Returns true if this vector contain only documents from a single shard and segment.
+     */
+    public boolean singleShardSingleSegment() {
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/DocVector.java]: I don't think we need these any more. Though a good follow-up might be to move this into the `DocBlock.Builder` and always emit constants for shard and segment.

**Review by nik9000 — APPROVED** [review]
I found something we no longer need. But it looks good otherwise. I think we should get it in and play with it some more. Get some performance numbers on when we take this path and experiment!
