### PR TITLE
[ML] Add support for nested NDJSON records in TextStructure endpoints

### LINKED ISSUE #127777: find_structure API unable to process nested fields from ndjson
### Elasticsearch Version

8.16.5

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

The `find_structure` API is unable to find fields nested under an object.

This limits the Kibana Data Visualizer functionality

- Kibana `analyzeFile` function: https://github.com/elastic/kibana/blob/162d3abc53cc161e485b570ea6f8587d5cea9f2a/x-pack/platform/plugins/private/file_upload/server/analyze_file.tsx#L16-L29
  - calls `_text_structure/find_structure` https://github.com/elastic/kibana/blob/162d3abc53cc161e485b570ea6f8587d5cea9f2a/src/platform/plugins/shared/console/server/lib/spec_definitions/json/generated/text_structure.find_structure.json#L34-L36

```diff
{
    "overrides": {
        "explain": "true"
    },
    "results": {
        "num_lines_analyzed": 3,
        "num_messages_analyzed": 3,
-        "sample_start": "{\"host\": {\"id\": \"1\", \"category\": \"NETWORKING DEVICE\"}}\n{\"host\": {\"id\": \"2\", \"category\": \"NETWORKING DEVICE\"}}\n",
        "charset": "UTF-8",
        "has_byte_order_marker": false,
        "format": "ndjson",
        "ecs_compatibility": "disabled",
        "need_client_timezone": false,
-        "mappings": {
-            "properties": {
-                "host": {
-                    "type": "object"
-                }
-            }
-        },
        "explanation": [
            "Using character encoding [UTF-8], which matched the input with [15%] confidence - first [8kB] of input was pure ASCII",
            "Deciding sample is newline delimited NDJSON"
        ]
    }
}
```

Image

It would be ideal to document as a known issue or limitation for now

### Steps to Reproduce

Submit an ndjson with nested fields
```
POST _text_structure/find_structure?filter_path=mappings
{"host": {"id": "1", "category": "NETWORKING DEVICE"}}
{"host": {"id": "2", "category": "NETWORKING DEVICE"}}
```
Only the parent level object is detected
```
{
  "properties": {
    "host": {
      "type": "object"
    }
  }
}
```

We have to flatten the structure to work around this:
```
POST _text_structure/find_structure?filter_path=mappings
{"host.id": 1, "host.category": "NETWORKING DEVICE"}
{"host.id": 2, "host.category": "NETWORKING DEVICE"}
```

```
{
  "mappings": {
    "properties": {
      "host.category": {
        "type": "keyword"
      },
      "host.id": {
        "type": "long"
      }
    }
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by darius-vil**
Fixes #127777 

I started from an old abandoned PR (https://github.com/elastic/elasticsearch/pull/131530/), but I found that:
1. It does not return a flattened result, effectively completely changing the response format
1. It goes only 1 level deep 
1. The behavior around mixed arrays changed - an exception was no longer thrown

Key changes:
1. Handles nested objects recursively to a set depth.
1. The endpoints have a `should_parse_recursively=<true/false>` parameter now, default to `false` if unspecified (in which case you get the old behavior). Agreed on it with Kibana: https://github.com/elastic/kibana/pull/249654. The argument has no effect if used with formats other than NDJSON.
1.  The main changes are in TextStructureUtils:
    1. It previously had two public methods for determining mappings: `guessMappingAndCalculateFieldStats` (used in tests only) and `guessMappingsAndCalculateFieldStats` (uses `guessMappingAndCalculateFieldStats` underneath). To make it easier to enforce consistent behavior between these two, I replaced all uses of `guessMappingAndCalculateFieldStats` with `guessMappingsAndCalculateFieldStats` in tests and made that method private.
1. There's one case that the current implementation won't handle - list of lists (nested lists), e.g. `"key": [[1],[2]]` or `"key": [[{"id": 1}], [{"id": 2}]]`. or `"key": [[1, 2, 3]]` etc. I thought of this after being mostly done and I started to weight whether it's worth adding more complexity to cover this (hopefully rare?) case. I wrote a unit test that checks exactly that. I can give it a shot if anyone feels it's worth it.

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java [hunk 1]
```diff
@@ -338,6 +350,9 @@ public int hashCode() {
             columnNames,
             hasHeaderRow,
             delimiter,
+            quote, // TODO were these two missing?
```
Comment (darius-vil) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]: Leftover "TODO" by me, will remove.

These two fields were missing in hashCode() and equals() though, I don't think there is a good reason why

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinderTests.java [hunk 2]
```diff
@@ -49,4 +55,49 @@ public void testCreateConfigsGivenGoodJson() throws Exception {
         assertEquals(Collections.singletonList("UNIX_MS"), structure.getJodaTimestampFormats());
         assertEquals(Collections.singleton("properties"), structure.getMappings().keySet());
     }
+
+    public void testCreateConfigsGivenNestedJson() throws Exception {
```
Comment (darius-vil) [inline x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinderTests.java]: Authored by the person that worked on it before. 

I might remove this, I think it's sufficiently tested in TextStructureUtilsTest

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 3]
```diff
@@ -354,6 +385,121 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     * @param timeoutChecker Will abort the operation if its timeout is exceeded.
+     * @param depth The current recursion depth.
+     * @param maxDepth The max recursion depth.
+     */
+    private static void flattenListValues(
+        String prefix,
+        List<Object> list,
+        Map<String, Object> flattenedResult,
+        TimeoutChecker timeoutChecker,
+        int depth,
```
Comment (darius-vil) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: It's called `currentDepth` elsewhere - replace all `depth` with `currentDepth` for consistency

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 4]
```diff
@@ -354,6 +385,121 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+
+        Map<String, List<Object>> collectedValues = new LinkedHashMap<>();
+        for (Object item : list) {
+            if (item instanceof Map) {
+                @SuppressWarnings("unchecked")
+                Map<String, ?> nestedMap = (Map<String, ?>) item;
+                Map<String, Object> flattenedItem = new LinkedHashMap<>();
+                if (currentDepth >= maxDepth) {
+                    // Max depth reached - will be mapped as "object" type
+                    flattenedResult.put(prefix, Collections.emptyMap());
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Should this be followed by `return` for early exit?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 5]
```diff
@@ -354,6 +385,121 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     * @param currentDepth The current recursion depth.
+     * @param maxDepth The max recursion depth.
+     */
+    private static void flattenListValues(
+        String prefix,
+        List<Object> list,
+        Map<String, Object> flattenedResult,
+        TimeoutChecker timeoutChecker,
+        int currentDepth,
+        int maxDepth
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Is there validation somewhere that prevents `maxDepth` from having a negative value?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/rest/RestFindStructureArgumentsParser.java [hunk 6]
```diff
@@ -59,6 +59,9 @@ static void parse(RestRequest restRequest, AbstractFindStructureRequest request)
         request.setDelimiter(restRequest.param(FindStructureAction.Request.DELIMITER.getPreferredName()));
         request.setQuote(restRequest.param(FindStructureAction.Request.QUOTE.getPreferredName()));
         request.setShouldTrimFields(restRequest.paramAsBoolean(FindStructureAction.Request.SHOULD_TRIM_FIELDS.getPreferredName(), null));
+        request.setShouldParseRecursively(
+            restRequest.paramAsBoolean(FindStructureAction.Request.SHOULD_PARSE_RECURSIVELY.getPreferredName(), false)
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/rest/RestFindStructureArgumentsParser.java:63]: Isn't the usual pattern in this code to set the default value of `Boolean` flags to `null` instead of `true` or `false`? I  see this happening in `setShouldParseRecursively()` right above.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 7]
```diff
@@ -354,6 +385,121 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     * Flattens values from a list, handling nested maps within the list.
+     * For lists of maps like [{"id": 1}, {"id": 2}], this merges them into a map with arrays: {"id": [1, 2]}
+     * @param prefix The current field prefix for dot notation.
+     * @param list The list to process.
+     * @param flattenedResult The output map to add flattened fields to.
+     * @param timeoutChecker Will abort the operation if its timeout is exceeded.
+     * @param currentDepth The current recursion depth.
+     * @param maxDepth The max recursion depth.
+     */
+    private static void flattenListValues(
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: This is a complex method. Maybe you can extract some smaller methods to reduce cognitive complexity.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java [hunk 8]
```diff
@@ -28,6 +30,10 @@
  */
 public class NdJsonTextStructureFinder implements TextStructureFinder {
 
+    public static final int NO_RECURSION_DEPTH = 1;
+    public static final int DEFAULT_RECURSION_DEPTH = MapperService.INDEX_MAPPING_TOTAL_FIELDS_LIMIT_SETTING.getDefault(Settings.EMPTY)
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java]: Please add a Javadoc comment explaining how the recursion depth is connected to the field's limit.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java [hunk 9]
```diff
@@ -39,6 +39,7 @@ public abstract class AbstractFindStructureRequest extends LegacyActionRequest {
     public static final ParseField DELIMITER = TextStructure.DELIMITER;
     public static final ParseField QUOTE = TextStructure.QUOTE;
     public static final ParseField SHOULD_TRIM_FIELDS = TextStructure.SHOULD_TRIM_FIELDS;
+    public static final ParseField SHOULD_PARSE_RECURSIVELY = new ParseField("parse_recursively");
```
Comment (valeriy42) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]:
```suggestion
    public static final ParseField SHOULD_PARSE_RECURSIVELY = new ParseField("should_parse_recursively");
```
for consistency

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 10]
```diff
@@ -354,6 +385,121 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+        int maxDepth
+    ) {
+        timeoutChecker.check("record flattening");
+        boolean hasNestedMaps = list.stream().anyMatch(item -> item instanceof Map);
+        if (hasNestedMaps == false) {
+            flattenedResult.put(prefix, list);
+            return;
+        }
+
+        boolean hasNonMaps = list.stream().anyMatch(item -> item != null && (item instanceof Map) == false);
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: nit: maybe you can get  `hasNestedMaps` and `hasNonMaps` in one go to avoid streaming through the list twice.

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java [hunk 11]
```diff
@@ -1116,22 +1385,60 @@ public void testGuessMappingWithNullValue() {
...
+        Map<String, Object> input = Map.of("level" + desiredDepth, 1);
+        for (int i = desiredDepth - 1; i >= 1; i--) {
+            input = Map.of("level" + i, input);
+        }
+        Map<String, Object> finalInput = new LinkedHashMap<>(input);
+        finalInput.put("timestamp", "1478261151445");
+        return finalInput;
+    }
+
+    private void assertKeyAndMappedType(Map<String, Object> mappings, String expectedKey, String expectedType) {
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java]: Consider moving `assertKeyAndMappedType` and `assertKeyAndMappedTime` to `TextStructureTestCase` so they can be reused by other test case derivatives.

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java [hunk 12]
```diff
@@ -618,6 +620,273 @@ public void testGuessMappingGivenObjectAndNonObject() {
         ecsCompatibilityModes.forEach(testGuessMappingGivenEcsCompatibility);
     }
 
+    /**
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java:436]: What happens if the Input is one of edge cases
```json
{"field": []}

{"host": {"id": null, "name": "test"}}
```
?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 13]
```diff
@@ -354,6 +385,121 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+                List<Object> list = (List<Object>) value;
+                flattenListValues(key, list, flattenedResult, timeoutChecker, currentDepth, maxDepth);
+            } else {
+                flattenedResult.put(key, value);
+            }
+        }
+    }
+
+    /**
+     * Flattens values from a list, handling nested maps within the list.
```
Comment (valeriy42) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Consider documenting the limitation mentioned in the PR description:
> Note: Nested lists (e.g., [[1,2],[3,4]]) are not currently supported and will be mapped as type 'object'. Only single-level lists of primitives or objects are flattened.

**Review by valeriy42 — COMMENTED** [review]
Good work on this PR @darius-vil 🚀  Looks mostly good to me. I have only a few comments. 

Remember to add a documentation PR to https://github.com/elastic/elasticsearch-specification/tree/main/specification/text_structure/find_structure

Also, since this is not my area of expertise, maybe @jan-elastic can take another look.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/rest/RestFindStructureArgumentsParser.java (hunk 6 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/rest/RestFindStructureArgumentsParser.java:63]: I noticed that pattern too, but I have no good explanation on why "nulls" were chosen as default there above. I felt like setting "false", the actual default value I want, is much more readable.

I'll change the default to "null" for consistency. There's a "isFalse || isNull" check later on anyway, so functionally it's the same.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 13 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Will do!

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 4 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Absolutely!

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java (hunk 11 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java]: Done!

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java (hunk 12 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java:436]: In this case the behavior didn't change - null fields or empty lists are simply not mapped to any type, they're ignored.
There are two existing test cases checking these two scenarios `testGuessMappingWithNullValue` and `testGuessMappingGivenNothing` (although both these are non-recursive)

I added two tests cases to check this in a nested scenario.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 10 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Doable, but probably with a for loop instead of `stream()`s, so more verbose.

I'll try to break this whole function `flattenListVales` into smaller pieces

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java (hunk 9 above)
Comment (darius-vil) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]: Done!

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java (hunk 8 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java]: Autocomplete did me dirty here, it was supposed to be `MapperService.INDEX_MAPPING_DEPTH_LIMIT_SETTING`, not `MapperService.INDEX_MAPPING_TOTAL_FIELDS_LIMIT_SETTING` :D 

Good that this caught your eye.
I think in this case the field name becomes self-explanatory and no java doc is necessary?

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java (hunk 12 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java:436]: One update here - made these fields private, no reason for them to be public

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 7 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Although I think the complexity remains quite high, I gave an attempt to make it a bit better by breaking it down into separate, hopefully well-described functions

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 13 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: The documentation PR is open, but I'll share it for review once this PR is settled

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 5 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Nope.
Added validation + unit test

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java [hunk 14]
```diff
@@ -79,6 +81,7 @@ public abstract class AbstractFindStructureRequest extends LegacyActionRequest {
         delimiter = in.readBoolean() ? (char) in.readVInt() : null;
         quote = in.readBoolean() ? (char) in.readVInt() : null;
         shouldTrimFields = in.readOptionalBoolean();
+        shouldParseRecursively = in.readOptionalBoolean();
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]: Shouldn't this be surrounded by a `TransportVersion.supports(...)` to not break backwards compatibility?

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java [hunk 15]
```diff
@@ -0,0 +1,131 @@
...
+        .setting("xpack.security.enabled", "false")
+        .build();
+
+    @Override
+    protected String getTestRestCluster() {
+        return cluster.getHttpAddresses();
+    }
+
+    public void testJsonObjectDetectionBasicRequest() throws IOException {
+        String nestedJsonSample = """
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: I don't think this is a nested JSON sample.

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java [hunk 16]
```diff
@@ -0,0 +1,131 @@
...
+    }
+
+    private static Map<String, Object> executeAndVerifyRequest(String sample) throws IOException {
+        return executeAndVerifyRequest(sample, false, false);
+    }
+
+    private static Map<String, Object> executeAndVerifyRequest(
+        String sample,
+        boolean parseRecursivelyArgument,
+        boolean parseRecursivelyValue
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: I find two two booleans a bit confusing.

I think it's cleaner it you add a `Boolean parseRecursively` (note: `Boolean` class).

Setting it to `null` adds no query param (so default behavior). Setting it to `true`/`false` sets the param.

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java [hunk 17]
```diff
@@ -0,0 +1,131 @@
...
+
+        assertThat(
+            "Setting `should_parse_recursively=false` is equivalent to not setting this argument at all",
+            responseMap1,
+            equalTo(responseMap2)
+        );
+    }
+
+    private static Map<String, Object> executeAndVerifyRequest(String sample) throws IOException {
+        return executeAndVerifyRequest(sample, false, false);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: I'd remove this method and always explicitly set it.

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java [hunk 18]
```diff
@@ -0,0 +1,131 @@
...
+        @SuppressWarnings("unchecked")
+        Map<String, Object> mappings = (Map<String, Object>) responseMap.get("mappings");
+        assertThat(mappings, hasKey("properties"));
+
+        @SuppressWarnings("unchecked")
+        Map<String, Object> properties = (Map<String, Object>) mappings.get("properties");
+
+        assertThat(properties, hasKey(expectedKey));
+        @SuppressWarnings("unchecked")
+        Map<String, Object> timestampMapping = (Map<String, Object>) properties.get(expectedKey);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: `timestampMapping`?

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java [hunk 19]
```diff
@@ -0,0 +1,131 @@
...
+        Response response = client().performRequest(request);
+        assertOK(response);
+        return entityAsMap(response);
+    }
+
+    private void assertKeyValue(String expectedKey, String expectedType, Map<String, Object> responseMap) {
+        assertThat(responseMap.get("format"), equalTo("ndjson"));
+
+        @SuppressWarnings("unchecked")
+        Map<String, Object> mappings = (Map<String, Object>) responseMap.get("mappings");
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java:114]: I think you should also assert that:
- `responseMap` `hasKey("mapping")`
- `response.get("mappings")` `isInstanceOf(Map)`
- `response.get("properties")` `isInstanceOf(Map)`

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java [hunk 20]
```diff
@@ -87,8 +93,17 @@ static NdJsonTextStructureFinder makeNdJsonTextStructureFinder(
...
+            ? DEFAULT_RECURSION_DEPTH
+            : NO_RECURSION_DEPTH;
         Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> mappingsAndFieldStats = TextStructureUtils
-            .guessMappingsAndCalculateFieldStats(explanation, sampleRecords, timeoutChecker, overrides.getTimestampFormat());
+            .guessMappingsAndCalculateFieldStats(
+                explanation,
+                sampleRecords,
+                timeoutChecker,
+                overrides.getTimestampFormat(),
+                maxRecursionDepth
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java:105]: I would pass the boolean `parseRecursively` here.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java [hunk 21]
```diff
@@ -39,6 +39,7 @@ public abstract class AbstractFindStructureRequest extends LegacyActionRequest {
     public static final ParseField DELIMITER = TextStructure.DELIMITER;
     public static final ParseField QUOTE = TextStructure.QUOTE;
     public static final ParseField SHOULD_TRIM_FIELDS = TextStructure.SHOULD_TRIM_FIELDS;
+    public static final ParseField SHOULD_PARSE_RECURSIVELY = new ParseField("should_parse_recursively");
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java:47]: Why `should_parse_recursively` instead of just `parse_recursively`. Didn't we agree on that in chat?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 22]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     * For example, {"host": {"id": 1}, "name": "test"} becomes {"host.id": 1, "name": "test"}
+     *
+     * @param record         The record with potentially nested objects.
+     * @param timeoutChecker Will abort the operation if its timeout is exceeded.
+     * @param maxDepth       The max recursion depth.
+     * @return A flattened map with dot-notation keys.
+     */
+    private static Map<String, Object> flattenRecord(Map<String, ?> record, TimeoutChecker timeoutChecker, int maxDepth) {
+        Map<String, Object> flattened = new LinkedHashMap<>();
+        flattenRecordRecursive("", record, flattened, timeoutChecker, 1, maxDepth);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I would pass on the boolean `parseRecursively` until here, and only replace it by a max depth in this spot.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 23]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     */
+    private static void flattenListValues(
+        String prefix,
+        List<Object> list,
+        Map<String, Object> flattenedResult,
+        TimeoutChecker timeoutChecker,
+        int currentDepth,
+        int maxDepth
+    ) {
+        timeoutChecker.check("record flattening");
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: list flattening

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 24]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+        return flattened;
+    }
+
+    private static void flattenRecordRecursive(
+        String prefix,
+        Map<String, ?> record,
+        Map<String, Object> flattenedResult,
+        TimeoutChecker timeoutChecker,
+        int currentDepth,
+        int maxDepth
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: You don't need `currentDepth` and `maxDepth`. You can decrease `maxDepth` by `1` if you recurse.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 25]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+        String prefix,
+        List<Object> list,
+        Map<String, Object> flattenedResult,
+        TimeoutChecker timeoutChecker,
+        int currentDepth,
+        int maxDepth
+    ) {
+        timeoutChecker.check("record flattening");
+        boolean hasNestedMaps = false;
+        boolean hasNonMaps = false;
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I would stick to ES terminology, like `hasObjects` and `hasConcreteValues`

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 26]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+            return;
+        }
+
+        if (hasNestedMaps && hasNonMaps) {
+            throw new IllegalArgumentException(
+                "Field [" + prefix + "] has both object and non-object values - this is not supported by Elasticsearch"
+            );
+        }
+
+        Map<String, List<Object>> collectedValues = flattenObjectsInAList(
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I think you should loop over all list elements, and call `flattenRecordRecursive` again.

Furthermore, before putting something into `flattenedResult`, you should check for existence / inconsistency. I think...

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 27]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+            list,
+            flattenedResult,
+            timeoutChecker,
+            currentDepth,
+            maxDepth
+        );
+        addListFlatteningResultToGeneralResults(flattenedResult, collectedValues);
+    }
+
+    private static void addListFlatteningResultToGeneralResults(
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: If you recursively call `flattenRecordRecursive` or `flattenListValues` again, I don't think you need this method nor the next one.

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java [hunk 28]
```diff
@@ -618,6 +621,351 @@ public void testGuessMappingGivenObjectAndNonObject() {
...
+     * Input:
+     * {
+     *  "host": {"id": 1, "category": "NETWORKING DEVICE"},
+     *  "timestamp": "1478261151445",
+     *  "message": "Connection established"
+     * }
+     */
+    public void testGuessMappingGivenNestedObjectAndNoRecursion() {
+        Map<String, Object> nestedObject = new LinkedHashMap<>();
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtilsTests.java:445]: I think there's a few missing cases, like
- `{"key": [ {"x": 1}, {"y": {"z": 10}}, {"y": {"z":42}} ]}`
- `{"key": [ {"x": 1}, {"y": {"z": 10}}, {"y": {"z":"a"}} ]}`
- `{"key": [ {"x": 1}, {"y": {"z": 10}}, {"y": {"z":{"w":1}}} ]}`
- etc

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 13 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I don't like the fact that this doesn't work for nested lists. I think that should be fixed, and I also think the code is simpler if it's fixed... (consider that a challenge 😄  )

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java [hunk 29]
```diff
@@ -338,6 +350,9 @@ public int hashCode() {
             columnNames,
             hasHeaderRow,
             delimiter,
+            quote,
+            shouldTrimFields,
+            shouldParseRecursively,
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java:364]: Good find!

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 30]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+                if (nestedMap.isEmpty() || currentDepth >= maxDepth) {
+                    // Empty nested objects or max depth reached - will be mapped as "object" type
+                    flattenedResult.put(key, Collections.emptyMap());
+                } else {
+                    flattenRecordRecursive(key, nestedMap, flattenedResult, timeoutChecker, currentDepth + 1, maxDepth);
+                }
+            } else if (value instanceof List) {
+                @SuppressWarnings("unchecked")
+                List<Object> list = (List<Object>) value;
+                flattenListValues(key, list, flattenedResult, timeoutChecker, currentDepth, maxDepth);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I think you can remove the method `flattenListValues` and just call `flattenRecordRecursive` for each element. And before calling ` flattenedResult.put` assert that the insertion is consistent.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 7 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I think this and all follow-up methods can be removed, see comment ☝️

**Review by jan-elastic — CHANGES_REQUESTED** [review]
generally looks good, but I think the logic can be simplified and work for all cases.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 31]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+        String prefix,
+        Map<String, ?> record,
+        Map<String, Object> flattenedResult,
+        TimeoutChecker timeoutChecker,
+        int currentDepth,
+        int maxDepth
+    ) {
+        timeoutChecker.check("record flattening");
+        for (Map.Entry<String, ?> entry : record.entrySet()) {
+            String key = prefix.isEmpty() ? entry.getKey() : prefix + "." + entry.getKey();
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I think this key building is pretty inefficient.

E.g. for `{"a": {"b": {"c": { ... {"y": {"z": 42}} ... }}}}`, you're generating all of `ab`, `abc`, `abc...y`, `abc...yz`.

A `List<String> keyParts` where you push and pop parts sounds better. You can get the final key with
```
key = String.join(".", keyParts);
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java (hunk 21 above)
Comment (darius-vil) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java:47]: We did! 
I made it `parse_recursively` initially, but a suggestion was made to change it to `should_parse_recursively` in the first review to make it consistent with `should_trim_fields` and I accepted it.

Since `should_parse_recursively` isn't too far from `parse_recursively`, I didn't think it's necessary to ask if everyone is fine with it again (sorry!)

@valeriy42 , @jan-elastic - do any of you feel strongly about `should_parse_recursively` or `parse_recursively`? If not, I'll stick to `should_parse_recursively` for consistency

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java (hunk 14 above)
Comment (darius-vil) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]: Wasn't aware of this mechanism, thanks for pointing this out!
Will wrap both the input and output stream with these checks

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java (hunk 16 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: Done!

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java (hunk 17 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: Done!

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java (hunk 19 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java:114]: Done!

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java (hunk 18 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: Fixed

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java (hunk 15 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java]: Right, it isn't and it isn't supposed to be!

Wrong variable name - fixed.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java (hunk 20 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java:105]: Hmm, I think I feel the contrary here.

I feel like the method having a `int maxDepth` as a parameter gives a better indication of what this method will do. With `maxDepth` kept as an internal part of `TextStructureUtils`, it could come to a surprise to someone why are some keys omitted (until they peek at the implementation to find out that it's capped at 20).

I find the unit tests a little bit better this way too - I can set a concrete desired depth on test setup and assert that the key depth is to what I set it right after invoking the method.

But it's a minor thing, I can change it if you insist.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 22 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: See comment above

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 31 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Done! 

Also made sure that `String.join(".", keyParts);` is invoked right before `flattenedResult.put(...)`

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 30 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Good instincts - redid it according to your suggestion, I think it's an improvement

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 26 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: > I think you should loop over all list elements, and call flattenRecordRecursive again.

Addressed above

---

> Furthermore, before putting something into flattenedResult, you should check for existence / inconsistency. I think...

Regarding "existence", I think it's important for me to make sure that
```
{ "host": [{"id": 1}, {"id": "id1"}] }
```
gets flattened into `host.id -> [1, "id1"]`, cause later on, `guessScalarMapping(...)` (an existing function, not written by me), takes these arrays of "primitives" and guesses the most likely mapping. Any more concerns regarding "existence" I should think of?

Unless you wonder what should happen in this case: 
Input:
```
{ "host": [{"id": 1}, {"id": "id1"}, {"id": { "deepKey", "deepValue"}}] }
```
Output:
```
host.id -> [1, "id1"],
host.id.deepKey -> "deepValue" // should this entry exist at all? If not - do we ignore it, throw an exception? I'd keep this entry.
```

---

Regarding "inconsistencies" - what inconsistencies do you think could happen here? Any examples?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 13 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I just did, much simpler after your suggestion above
Things to note there:

1. Nested lists count towards the depth now.
    - Note that the depth stop condition differs for List vs Map - this is to keep the behavior identical to before my change. Left a comment in the code there
1. I made a new helper function (addConcreteRecordToResultMap) to help me keep the results in the format that I want

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 24 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Done!

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java (hunk 21 above)
Comment (jan-elastic) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java:47]: let's leave it like this for consistency (tbh I don't like `should_trim_fields` either)

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java (hunk 20 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java:105]: Agree to disagree; let's leave it like this

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 32]
```diff
@@ -268,9 +268,36 @@ private static List<Tuple<String, TimestampFormatFinder>> findCandidates(
      * @param sampleRecords The sampled records.
      * @param timeoutChecker Will abort the operation if its timeout is exceeded.
      * @param timestampFormatOverride The format of the timestamp as given in the request overrides.
+     * @param maxDepth The max recursion depth.
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I don't think this JavaDoc explains well what this does.

Please add something about nested JSON / field names etc.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 33]
```diff
@@ -268,9 +268,36 @@ private static List<Tuple<String, TimestampFormatFinder>> findCandidates(
...
+    /**
+     * Given the sampled records, guess appropriate Elasticsearch mappings.
+     * @param explanation List of reasons for making decisions.  May contain items when passed and new reasons
+     *                    can be appended by this method.
+     * @param sampleRecords The sampled records.
+     * @param timeoutChecker Will abort the operation if its timeout is exceeded.
+     * @param timestampFormatOverride The format of the timestamp as given in the request overrides.
+     * @return A map of field name to mapping settings.
+     */
+    public static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMappingsAndCalculateFieldStats(
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Is this method used? I guess only in very few places. Maybe consider setting the `maxDepth=1` there.

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Same about the other `guessMappingsAndCalculateFieldStats` methods. Do we really need that many?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 32 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Instead of `maxDepth`, let's call it `mappingDepthLimit` (analogous to the setting). That's more clear if you ask me.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 24 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: If you collect `keyParts`, then `keyParts.size()` also is the `currentDepth`.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 13 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I don't think the lists should count towards depth.

The restriction `mappingDepthLimit` is about the number of key parts.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 26 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I meant that the line
```
flattenedResult.put(key, value)
```
shouldn't just overwrite results. It should append if something already exists.

But it's not about inconsistencies (I misunderstood some part of the code).

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 34]
```diff
@@ -354,6 +389,166 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+                    flattenedResult.put(key, Collections.emptyMap());
+                } else {
+                    flattenRecordRecursive(key, nestedMap, flattenedResult, timeoutChecker, currentDepth + 1, maxDepth);
+                }
+            } else if (value instanceof List) {
+                @SuppressWarnings("unchecked")
+                List<Object> list = (List<Object>) value;
+                flattenListValues(key, list, flattenedResult, timeoutChecker, currentDepth, maxDepth);
+            } else {
+                flattenedResult.put(key, value);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: If key already exists, you should overwrite, but append. If I understand correctly.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 33 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Regarding the number of `guessMappingsAndCalculateFieldStats`...
There are multiple signatures for various combinations of these 3 optional parameters: boolean ecsCompatibility, String timestampFormatOverride, int maxDepth

And by the looks of it: 
1. `boolean ecsCompatibility` is never provided outside of tests, so it always defaults to `DEFAULT_ECS_COMPATIBILITY` in actual runtime, but on the other hand it's very extensively tested with various values in the unit tests (and so did I in my changes, following the pattern). Maybe let me figure out if it's still needed in a follow up? I'll reach out to Ed, looks like he contributed here, he might know the answer
2. `String timestampFormatOverride` - there's only one signature WITHOUT this parameter and it's used in tests only - I'll fill that parameter with `null` there - that's one signature less.
3. `int maxDepth` - currently used by `NdJsonTextStructureFinder` only. There are two more uses of a signature without the `maxDepth` parameter (in `DelimitedTextStructureFinder` and `XmlTextStructureFinder`). Setting `maxDepth = 1` in `DelimitedTextStructureFinder` feels off though, since it does not represent a nested structure in the first place (I'll admit your earlier suggestion, to have a `parseResursively: true/false` parameter, would have been more natural in this very case 😄 But I still feel like having a numerical `maxDepth` parameter is useful in the tests, so I'd keep a separate signature for `maxDepth` and leave the current uses without it untouched)

Additionally, there were two `guessMappingAndCalculateFieldStats` (singular "Mapping") signatures, one unused - removed.

TL;DR - 2 signatures removed, 1 signature (with `ecsCompatibility`) is likely to be removed and we'll be left with 2 signatures in the end (with `mappingDepthLimit` and without `mappingDepthLimit` specified) - sounds good?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 34 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Yep, noticed it when implementing some of the extra test cases you suggested earlier - should be fixed in the next revision :)

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 32 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Thanks for the naming suggestion + added a short example to illustrate what it will do

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 13 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I was worried it could also lead to an overflow if anyone (for whatever reason) has data with super nested lists.
But I guess it's very unlikely, we check for the execution time anyway so maybe the likelihood it close to zero...

Removed the depth check in list recursion

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 26 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I see. The result overwriting was an issue, I think it should be fixed now.

The crucial change here is in the `validateParentKeysAndMarkThemAsTaken` helper method - it helps me keep track of which keys are free to be used as a mapping for concrete values.

One more change in the following revision - the flattening result is of type `Map<String, List<Object>>`, cause I had to perform a lot of type casts otherwise and it was difficult to track...

So if previously the flattening result was:
```
"a" -> 1,
"b" -> 1
"a.c" -> ["aaa", "bbb"]
```
Now it will be 
```
"a" -> [1],
"b" -> [1]
"a.c" -> ["aaa", "bbb"]
```

It should result in the same during type mapping alter on

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java [hunk 35]
```diff
@@ -26,6 +27,8 @@
 
 public abstract class AbstractFindStructureRequest extends LegacyActionRequest {
 
+    private static final TransportVersion RECURSIVE_PARSING_SUPPORT = TransportVersion.fromName("should_parse_recursively_parameter");
```
Comment (jan-elastic) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]: These TV names should be globally unique (I think), so let's do something like
```
find_structure_request_should_parse_recursively
```

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 33 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: If something is only used in tests, please remove it, and let the test test something else, that is actually used in production.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 36]
```diff
@@ -311,24 +328,36 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+        if (mappingDepthLimit < 1) {
+            throw new IllegalArgumentException("Mapping depth limit must be at least 1");
+        }
 
         SortedMap<String, Object> mappings = new TreeMap<>();
         SortedMap<String, FieldStats> fieldStats = new TreeMap<>();
 
-        Set<String> uniqueFieldNames = sampleRecords.stream().flatMap(record -> record.keySet().stream()).collect(Collectors.toSet());
+        List<Map<String, List<Object>>> flattenedRecords = sampleRecords.stream()
+            .map(x -> (Object) x)
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Why this cast to an Object? Everything is an Object, isn't it?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 37]
```diff
@@ -311,24 +328,36 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+            .map(record -> flattenRecord(record, timeoutChecker, mappingDepthLimit))
+            .toList();
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: This `List` is collecting everything before merging. That's a bit memory inefficient.

I think you can do better by using `.collect(Collectors.toMap(...))`

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 38]
```diff
@@ -355,26 +384,176 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     *                          the mapping will reach down to "a.b" and map it as an object,
+     *                          but will not dive into "c". Increasing the depth allows for deeper mapping.
+     * @return A flattened map with dot-notation keys, where each key maps to a list of values.
      */
-    static Tuple<Map<String, String>, FieldStats> guessMappingAndCalculateFieldStats(
-        List<String> explanation,
-        String fieldName,
-        List<Object> fieldValues,
+    private static Map<String, List<Object>> flattenRecord(Object record, TimeoutChecker timeoutChecker, int mappingDepthLimit) {
+        Map<String, List<Object>> flattened = new LinkedHashMap<>();
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Should you verify here that `Object` is a `Map` to start with?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 39]
```diff
@@ -355,26 +384,176 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+    ) {
+        timeoutChecker.check("record flattening");
+        if (record instanceof Map) {
+            @SuppressWarnings("unchecked")
+            Map<String, ?> nestedMap = (Map<String, ?>) record;
+            flattenMap(keyParts, nestedMap, flattenedResult, keyHasChildrenObjects, timeoutChecker, remainingDepth);
+        } else if (record instanceof List) {
+            @SuppressWarnings("unchecked")
+            List<Object> list = (List<Object>) record;
+            flattenList(keyParts, list, flattenedResult, keyHasChildrenObjects, timeoutChecker, remainingDepth);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I think the implementations of `flattenMap` and `flattenList` are so short, that you'd better inline them here.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 40]
```diff
@@ -355,26 +384,176 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     * it means we're trying to mix objects and concrete values under a single key.
+     */
+    private static void validateParentKeysAndMarkThemAsTaken(
+        Map<String, List<Object>> flattenedResult,
+        List<String> keyParts,
+        Set<String> keyHasChildrenObjects
     ) {
-        return guessMappingAndCalculateFieldStats(explanation, fieldName, fieldValues, timeoutChecker, ecsCompatibility, null);
+        for (int i = keyParts.size() - 1; i >= 1; i--) {
+            String parentKey = String.join(DOT_DELIMITER, keyParts.subList(0, i));
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: This is constructing many strings.

I think for deeply nested data, this can be a significant slowdown.

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: You probably need a datastructure like a [Trie / prefix tree](https://en.wikipedia.org/wiki/Trie)

(maybe things aren't terrible with the max recursion depth of 20 🤷 )

**Comment by jan-elastic** [comment]
This is looking a lot better! Well done. Left a few more comments.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 40 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I gave this some more thought. For the input:
```
{"very_laaarrrrggggeeee_key_at_depth_1": {"2": {"3":{...{"19":{"20":"value"}...}}}}}
```
you generate the strings:
- `very_laaarrrrggggeeee_key_at_depth_1.2`
- `very_laaarrrrggggeeee_key_at_depth_1.2.3`
- `very_laaarrrrggggeeee_key_at_depth_1.2...19`
- `very_laaarrrrggggeeee_key_at_depth_1.2...19.20`

which is 20x memory overhead.

I don't think that's a good idea and it should be fixed.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 36 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: No idea! My bad! Removed

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 33 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Removed `ecsCompatibility` parameter, reducing the number `guessMappingsAndCalculateFieldStats` to two.
Gives quite a big diff, especially in tests, but it's contained in a single commit.

While removing this parameter, I noticed that the `timestampFormatOverride` doesn't seem to have any effect. There is a test even that seems to check that providing this parameter has no effect.

So this could probably be removed too... Do you prefer I remove it now or in a follow up PR? I don't want to make this review more difficult for you

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 38 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: `flattenRecord(Object record, ...)` gets invoked by `guessMappingsAndCalculateFieldStats(..., List<Map<String, ?>> sampleRecords, ...)` only.

So I can actually change `flattenRecord(Object record, ...)` to `flattenRecord(Map<String, ?>>  record, ...)` and get better type safety. I cast the original records into an object too early.

Good observation!

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 40 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I looked if there's anything I can reuse, but in the end I decided to implement my own trie-like structure just for this purpose.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 37 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I gave it a try - combined the two streams into one, collected into a map in one stream. No need to map, filter, collect again later on in the loop either.

As a downside there's probably more array copying going on, but it's probably still an improvement

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 39 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: If you don't mind, I'd stick with separate private methods, even if they're short super short!

This came after one of the previous suggestions and I grew accustomed to it - I feel the flow is a bit easier to follow.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java (hunk 35 above)
Comment (darius-vil) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java]: Done!

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java [hunk 41]
```diff
@@ -0,0 +1,113 @@
...
+package org.elasticsearch.xpack.textstructure.structurefinder;
+
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+
+/**
+ * A Trie-like data structure with immutable leaves.
+ * For example, say we have a trie with the following path: ["a", "b", "c"], where "c" is a leaf:
+ * - attempting to add ["a", "f"] will fail because "a" is already a non-leaf node, and it can't be turned into a leaf
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java]: i don't understand: why can't `"f"` be added as another child of `"a"`?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java [hunk 42]
```diff
@@ -0,0 +1,113 @@
...
+
+    /**
+     * Finds where a conflict would occur if we tried to add the given path.
+     * @param path The path, starting from the root and ending at the leaf.
+     * @return the path prefix where the conflict occurs, or null if no conflict.
+     * For example, if the trie has the path ["a", "b", "c"]
+     * - if we try to add ["a", "b"], the conflicting path will be ["a", "b"].
+     * - if we try to add ["a", "b", "c", "d"], the conflicting path will be ["a", "b", "c"].
+     */
+    public List<String> findConflict(List<String> path) {
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java]: Can you just merge these two methods?

E.g. make it
```
public List<String> tryAdd(...)
```
which returns:
- `null` if successful (and then the Trie is updated)
- the conflicting path if not successful

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 43]
```diff
@@ -356,25 +326,171 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+    }
+
+    /**
+     * Validates that we're not adding a concrete value to a list of objects
+     * (or an object to a list of concrete values).
+     * @param keyParts The current key parts.
+     * @param existingValues The list of values already stored for this key.
+     * @param newElement The new element being added.
+     */
+    private static void validateNewElement(List<String> keyParts, List<Object> existingValues, Object newElement) {
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Isn't this already validated by the Trie?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 44]
```diff
@@ -356,25 +326,171 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+     * @param mappingDepthLimit How deep into the nested objects we should look for keys.
+     *                          For example, with depth=2 and input:
+     *                          {"a": [{"b": {"c": 1}}]}
+     *                          the mapping will reach down to "a.b" and map it as an object,
+     *                          but will not dive into "c". Increasing the depth allows for deeper mapping.
+     * @return A flattened map with dot-notation keys, where each key maps to a list of values.
+     */
+    private static Map<String, List<Object>> flattenRecord(Map<String, ?> record, TimeoutChecker timeoutChecker, int mappingDepthLimit) {
+        Map<String, List<Object>> flattened = new LinkedHashMap<>();
+        ImmutableLeavesTrie keysPointingToConcreteValues = new ImmutableLeavesTrie();
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: I think that having `keysPointingToConcreteValues` and `flattened` side-by-side is slightly overcomplicating things.

Can't the Trie have a `List<Object>` is the leaf nodes instead of the `isLeaf` boolean?

And then implement a method `Trie::flatten`, which produces this `Map<String, List<Object>>` with one DFS (so afterwards, instead of in parallel).

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 45]
```diff
@@ -268,77 +270,45 @@ private static List<Tuple<String, TimestampFormatFinder>> findCandidates(
...
+            String fieldName = entry.getKey();
+            List<Object> fieldValues = entry.getValue();
 
             Tuple<Map<String, String>, FieldStats> mappingAndFieldStats = guessMappingAndCalculateFieldStats(
                 explanation,
                 fieldName,
                 fieldValues,
                 timeoutChecker,
-                ecsCompatibility,
+                DEFAULT_ECS_COMPATIBILITY,
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: Is this correct?

Shouldn't the `ecsCompatibility` from the request get to here?

**Review by jan-elastic — COMMENTED** [review]
Reviewed again; left a few comments/questions

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 45 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: This change is a result of this discussion, where you suggested to reduce the number of public methods:
https://github.com/elastic/elasticsearch/pull/141045#discussion_r2742494330

In a nutshell, we had a `guessMappingsAndCalculateFieldStats` signature with a `ecsCompatibility` parameter, but it was never used outside of tests or TextStructureUtils itself.

See the current uses of `guessMappingsAndCalculateFieldStats`, none of them seem to pass in ecsCompatibility: https://github.com/search?q=org%3Aelastic+guessMappingsAndCalculateFieldStats+AND+NOT+path%3A*Tests.java+NOT+path%3A*%2FTextStructureUtils.java&type=code

In the old path, it was immediately defaulted to `DEFAULT_ECS_COMPATIBILITY`: https://github.com/elastic/elasticsearch/blob/96be973fb5687c9837f51352fd7c8c5d2a5894aa/x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java#L283

Is my though process OK here? Or is there something I'm missing? 😄

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 43 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Generally yes, with one edge case - when we're at the depth limit
Until now, we didn't accept a mix of objects and concrete values in an array and I wanted to preserve that: https://github.com/elastic/elasticsearch/blob/9c62de081446eec1177d6e22362dfbe5c79e6bbd/x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java#L413

In my implementation, when I stumble on an object while out of depth, I insert a `{}`: https://github.com/elastic/elasticsearch/pull/141045/changes#diff-45eb7b7722212d048d308c5d0f9a9ce2bf33d33f5903b9a56051317189552551R462

A few examples, assume `mappingDepthLimit = 1`:
```
Input:
{
  "foo": [1, 2]
}
// No flattening necessary, OK!
```

```
Input:
{
  "foo": [{"bar1": 1}, {"bar2": 2}]
}

// Will be flattened to:
{
  "foo": [{}, {}]
}
// OK - `foo`s type will be "object"
```

```
Input:
{
  "foo": [{"bar": 1}, 2]
}

// Will be flattened to:
{
  "foo": [{}, 2]
}
// Not OK! That's why I validate new elements as as I add them
```

Actually the user could provide this too, in any depth:
```
Input:
{
  "foo": [{}, 2]
}
```


Does it make sense?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 45 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: I'm 100% in favor of cleaning up unused (in production) code.

I'm just surprised now that the `ecsCompatibility` from the request ([this one](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/textstructure/action/AbstractFindStructureRequest.java#L64)) does not find its way to the `guessMappingsAndCalculateFieldStats` code. I'd say that can't be right...

What is this request parameter used for? 

It's very well possible that something has been wrong for a long time, and this cleanup of yours exposed it.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 43 above)
Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: This is allowed right?
- first insert `{"a":{}}`
- next insert `{"a":{"b":10}}`

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: If a node has a `List<Object> values` and `List<Node> children`, just one should be allowed to be non-null.

I think: `insert {"a":{}}`should set `a.children = emptyList()`. This means a follow-up `{"a":{"b":10}}` is allowed (add an additional child), but a follow-up `{"a":42}` is not (both children and values non-null).

Does that make sense?

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java (hunk 42 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java]: Yes! That's how I implemented it initially, but then pivoted to a `true/false` response on `add`, cause that's more inline to how java's `Collection`s behave.
I didn't mind having and extra pass from invoking `findConflict` either, cause that's invoked only once were wrapping up anyway...

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java]: I'm more worried about 2x times the code. More code, more maintenance, more mental load, more bugs...

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 45 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: I'll have to dig around a bit more, maybe check if there's any useful context in git history...

That argument is passed further down to a function responsible for mapping the timestamp field.

I'll try and find out.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 44 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Hmm, on the other hand, it's easier to visualize/follow how a map's state changes as records are processed rather than a tree's (at least for me)
A bit easier to debug too if there's ever a need.

I'll give it a try though and share what I think in the next revision

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 45 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: I dug around a little bit and...

What `ecsCompatibility` effectively does is dictate how/whether fields are determined to be of "date" type: https://github.com/elastic/elasticsearch/blob/f3f19cd9fbac28c85838f2c4b8c5ae9d245d1e3f/x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TimestampFormatFinder.java#L466-L467

Two sets of options here: `ORDERED_CANDIDATE_FORMATS` or `ORDERED_CANDIDATE_FORMATS_ECS_V1`. 

A field is compared against a list of patterns in order. If match - it's a date type.

`ORDERED_CANDIDATE_FORMATS_ECS_V1` is `ORDERED_CANDIDATE_FORMATS` + `a few extra patterns` - `two old patterns`: https://github.com/elastic/elasticsearch/blob/f3f19cd9fbac28c85838f2c4b8c5ae9d245d1e3f/x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TimestampFormatFinder.java#L369-L376

---

So I picked one of the formats in `ORDERED_CANDIDATE_FORMATS_ECS_V1` and made a request to see if it's picked up
```
POST _text_structure/find_structure?ecs_compatibility=v1
{"@timestamp": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
{"@timestamp": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
{"@timestamp": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
```

To my surprise - yes
```
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date"  # <----------- OK!
      },
      "status": {
        "type": "keyword"
      },
      "tags": {
        "type": "long"
      }
    }
  },
```
Try the same with `ecs_compatibility=disabled`, and the timestamp will be mapped to keyword
```
POST _text_structure/find_structure?ecs_compatibility=disabled
{"@timestamp": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
{"@timestamp": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
{"@timestamp": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
```
Response:
```
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "keyword" # <----------- KEYWORD, CAUSE FIELD IS OF ECS_V1 FORMAT
      },
      "status": {
        "type": "keyword"
      },
      "tags": {
        "type": "long"
      }
    }
  },
```

Try adding another date field though:
```
POST _text_structure/find_structure?ecs_compatibility=v1
{"@timestamp": "29-Aug-2021 12:03:33.578", "otherdate": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
{"@timestamp": "29-Aug-2021 12:03:33.578", "otherdate": "29-Aug-2021 12:03:33.578","tags": [1,2,3], "status": "active"}
{"@timestamp": "29-Aug-2021 12:03:33.578", "otherdate": "29-Aug-2021 12:03:33.578", "tags": [1,2,3], "status": "active"}
```
And you'll see that the other date field is not recognized as a date
```
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date" # <----------- OK!
      },
      "otherdate": {
        "type": "keyword" # <----------- ODD!
      },
      "status": {
        "type": "keyword"
      },
      "tags": {
        "type": "long"
      }
    }
  },
```

Give the other date field a format present in `ORDERED_CANDIDATE_FORMATS` though, and it looks fine
```
POST _text_structure/find_structure?ecs_compatibility=v1
{"time": "29-Aug-2021 12:03:33.578", "otherdate": "20210129010203", "tags": [1,2,3], "status": "active"}
{"time": "29-Aug-2021 12:03:33.578", "otherdate": "20210129010203","tags": [1,2,3], "status": "active"}
{"time": "29-Aug-2021 12:03:33.578", "otherdate": "20210129010203", "tags": [1,2,3], "status": "active"}
```
Response:
```
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date" # <----------- OK!
      },
      "otherdate": {
        "type": "date", # <----------- OK!
        "format": "yyyyMMddHHmmss"
      },
      "status": {
        "type": "keyword"
      },
      "tags": {
        "type": "long"
      },
      "time": {
        "type": "keyword"
      }
    }
  },
```


The explanation for this is that NdJsonStructureFinder maps it's fields in two steps:
1. It attempts to guess the timestamp field first. Note that it passes the entire `overrides` object into `guessTimestampField` - this is later used to check the compatibility insidethe function (`overrides.getEcsCompatibility()`): https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java#L59C46-L59C55
2. The other fields are mapped with `guessMappings...` - since it doesn't accept the `ecs_compatibiltiy override`, only fields that fall into `ORDERED_CANDIDATE_FORMATS` are mapped to "date": https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinder.java#L91

This does feel like a discrepancy. I think it's always been like that judging from git history.
I feel like this should be fixed, no? Do I do it in this PR or a separate one?

Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: And BTW, the same is probably true for other file formats (`DelimitedTextStructureFinder`, `XmlTextStructureFinder`)

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: I agree that feels like a bug. Let's create a github issue for it, summarizing your findings. Let's not increase the scope of this PR.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java (hunk 41 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ImmutableLeavesTrie.java]: `I think I meant to write "attempting to add ["a"] will fail because "a" is...` here...

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 43 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: Makes sense!

Redid the Trie:
1. Returns the path of conflict on fail
2. Nodes either store values in a list or point to other objects
3. Changed the terminology a bit (it's object and value nodes now), changed the class name to better reflect what this trie is
4. The trie now stores values too - no more `flattenedResults` in TextStructureUtils.java, the trie has a `flatten` method instead
5. Apart from a `tryAdd` method to add values to the trie, it has a `markAsObject` method to handle the case you described above (insert `{"a":{}}` followed by `{"a":{"b":10}}`) - `tryAdd` and `markAsObject` are very similar in implementation though and you had concerns about duplicating code before. I can try extracting some common logic if you want, but I don't think it will improve readability much. Extracting the path traversal is the best candidate here I think
6. No need to validate new elements in TextStructureUtils.java anymore.

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 45 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java:311]: https://github.com/elastic/elasticsearch/issues/142103

File: x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java [hunk 46]
```diff
@@ -0,0 +1,128 @@
...
+        return entityAsMap(response);
+    }
+
+    private void assertKeyValue(String expectedKey, String expectedType, Map<String, Object> responseMap) {
+        assertThat(responseMap.get("format"), equalTo("ndjson"));
+        assertThat(responseMap, hasKey("mappings"));
+
+        @SuppressWarnings("unchecked")
+        Map<String, Object> mappings = (Map<String, Object>) responseMap.get("mappings");
+        assertThat(mappings, instanceOf(Map.class));
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java:115]: This assert isn't useful. If mapping isn't a class, the typecast above would have failed.

I think you meant:
```
assertThat(responseMap.get("mappings"), instanceOf(Map.class));
Map<String, Object> mappings = (Map<String, Object>) responseMap.get("mappings");
```

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/javaRestTest/java/org/elasticsearch/xpack/textstructure/rest/TextStructureNestedJsonIT.java:115]: same underneath

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java [hunk 47]
```diff
@@ -0,0 +1,204 @@
...
+
+            if (isLastElement) {
+                if (nextNode == null) {
+                    Node newNode = Node.createValueNode(value);
+                    currentNode.addChild(nextNodeKey, newNode);
+                    return null;
+                }
+
+                if (nextNode.isObjectNode()) {
+                    return List.copyOf(path.subList(0, i + 1));
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java]: why copy the list? just `subList` should work, right?

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java]: same underneath

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java [hunk 48]
```diff
@@ -0,0 +1,204 @@
...
+        Node currentNode = root;
+        for (int i = 0; i < path.size(); i++) {
+            String nextNodeKey = path.get(i);
+            Node nextNode = currentNode.getChild(nextNodeKey);
+            boolean isLastElement = (i == path.size() - 1);
+
+            if (isLastElement) {
+                if (nextNode == null) {
+                    currentNode.addChild(nextNodeKey, Node.createObjectNode());
+                }
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java:99]: What if `nextNode.isValueNode()`? That should be an error, right?

If so, please:
- create a unit test the triggers the error
- fix the bug
- verify the unit test now works

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java [hunk 49]
```diff
@@ -356,25 +326,119 @@ static Tuple<SortedMap<String, Object>, SortedMap<String, FieldStats>> guessMapp
...
+
+        if (record.isEmpty() || remainingDepth <= 0) {
+            // Empty nested objects or max depth reached - will be mapped as "object" type
+            objectValueTrie.markAsObject(keyParts);
+            return;
+        }
+
+        for (Map.Entry<String, ?> entry : record.entrySet()) {
+            keyParts.add(entry.getKey());
+            var recordValue = (Object) entry.getValue();
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: is this cast to Object doing anything? Isn't everything an Object?

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrieTests.java [hunk 50]
```diff
@@ -0,0 +1,162 @@
...
+    public void testTryAdd_noConflictsWhenAddingSeparatePath() {
+        ObjectValueTrie trie = new ObjectValueTrie();
+        assertNull(trie.tryAdd(List.of("a", "b", "c"), "v1"));
+        assertNull(trie.tryAdd(List.of("d", "e", "f"), "v2"));
+    }
+
+    public void testTryAdd_noConflictsWhenBranchingOut() {
+        ObjectValueTrie trie = new ObjectValueTrie();
+        assertNull(trie.tryAdd(List.of("a", "b", "c"), "v1"));
+        assertNull(trie.tryAdd(List.of("d", "b", "e"), "v2"));
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrieTests.java]: Did you mean `a b e`? This is not branching out, right?

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrieTests.java [hunk 51]
```diff
@@ -0,0 +1,162 @@
...
+        ObjectValueTrie trie = new ObjectValueTrie();
+        assertNull(trie.markAsObject(List.of()));
+    }
+
+    public void testMarkAsObject_returnsConflictWhenExtendingPastValueNode() {
+        ObjectValueTrie trie = new ObjectValueTrie();
+        assertNull(trie.tryAdd(List.of("a", "b"), "value"));
+
+        List<String> conflict = trie.markAsObject(List.of("a", "b", "c"));
+        assertEquals(List.of("a", "b"), conflict);
```
Comment (jan-elastic) [inline x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrieTests.java:85]: Please add the test
- `tryAdd([a,b],value)`
- `markAsObject([a,b])`

**Review by jan-elastic — COMMENTED** [review]
I think I found one small bug. Furthermore, LGTM! Nice job

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java (hunk 47 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java]: Yes, returning `.subList` would be functionally the same, but it returns a modifiable view of the sublist.
So I decided to use `copyOf` to return an unmodifiable list. 

Whether it's a copy or a view doesn't make a difference as long as it's used in TextStructureUtils.java. Maybe I'm overly defensive here?

Comment (jan-elastic) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java]: I think it's too defensive. Making a copy costs memory. 

If you want to be very defensive, I think
```
Collections.unmodifiableList(path.subList(0, i + 1))
```
is a lot cheaper.

But I would just return the subList.

File: x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrieTests.java (hunk 50 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/test/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrieTests.java]: Yes! 🤦

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java (hunk 49 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/TextStructureUtils.java]: You pointed out something similar before...
Should have caught this one too. No more pointless casts!

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java (hunk 48 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java:99]: You're right, had a gap in my unit tests!
Unit test added and bug addressed

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java (hunk 47 above)
Comment (darius-vil) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/ObjectValueTrie.java]: Done, will be simply returning the sublist

**Review by jan-elastic — APPROVED** [review]
LGTM. Great job!
