### PR TITLE
Change process kill order for testclusters shutdown

### LINKED ISSUE #46262: MlMappingsUpgradeIT.testMappingsUpgrade fails with testclusters
I'm working in porting bwc tests to run with testclusters and can't get this one to pass:
https://gradle-enterprise.elastic.co/s/oqrlvw6evjqa4/tests/q3vpzt4orcdaq-vgix7kzieu2xs

I'm going to mute this since it's the only one that fails with this conversion and kindly ask someone from the team to take a look.

### PR DESCRIPTION
**Pull request by droberts195**
The testclusters shutdown code was killing child processes
of the ES JVM before the ES JVM.  This causes any running
ML jobs to be recorded as failed, as the ES JVM notices that
they have disconnected from it without being told to stop,
as they would if they crashed.  In many test suites this
doesn't matter because the test cluster will never be
restarted, but in the case of upgrade tests it makes it
impossible to test what happens when an ML job is running
at the time of the upgrade.

This change reverses the order of killing the ES process
tree such that the parent processes are killed before their
children.  A list of children is stored before killing the
parent so that they can subsequently be killed (if they
don't exit by themselves as a side effect of the parent
dying).

Fixes #46262

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 1]
```diff
@@ -807,6 +807,7 @@ public synchronized void stop(boolean tailLogs) {
         requireNonNull(esProcess, "Can't stop `" + this + "` as it was not started or already stopped.");
         // Test clusters are not reused, don't spend time on a graceful shutdown
         stopHandle(esProcess.toHandle(), true);
+        reaper.unregister(toString());
```
Comment (droberts195) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Moving this is not directly related to the fix, but I think it was in the wrong place before because:

1. It was only called for forcible stops, not successful graceful stops
2. It was called multiple times with exactly the same arguments in the event of forcibly stopping a process tree with more than one process

**Review by rjernst — APPROVED** [review]
LGTM
