### PR TITLE
SQL: Fix issue with DataType for CASE with NULL

### LINKED ISSUE #46032: SQL: CASE WHEN with NULL result yields NULL column type
If there's a `null` in the results of a CASE WHEN query, the column type is incorrectly set to `null`.

Example: 
```
SELECT (CASE WHEN ({fn DAYOFWEEK("employees"."hire_date")} IN (7, 1)) THEN NULL ELSE "employees"."hire_date" END) AS DOW
FROM "employees"
GROUP BY 1
```
returns:
```
{
  "columns" : [
    {
      "name" : "DOW",
      "type" : "null"
    }
  ],
  "rows" : [
    [
      null
    ],
    [
      "1985-02-18T00:00:00.000Z"
    ],
    [
      "1985-05-13T00:00:00.000Z"
    ],
  ...
```

### PR DESCRIPTION
**Pull request by matriv**
Previously, if the DataType of all the WHEN conditions of a CASE
statement is NULL, then it was set to NULL even if the ELSE clause
has a non-NULL data type, e.g.:
```
CASE WHEN a = 1 THEN NULL
           WHEN a = 5 THEN NULL
ELSE 'foo'
```

Fixes: #46032

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/CaseTests.java [hunk 1]
```diff
@@ -77,6 +81,42 @@ public void testReplaceChildren() {
         assertEquals(new Case(c.source(), newChildren), c.replaceChildren(newChildren));
     }
 
+    public void testDataTypes() {
+        // CASE WHEN 1 = 1 THEN NULL
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/CaseTests.java]: Imo, you could keep the comments on one line, but am happy either way.

**Review by astefan — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
LGTM
