### PR TITLE
SQL: Fix metrics reporting when sorting on aggregated values

### LINKED ISSUE #81502: SQL: Incorrect stats reported when sorting by aggregated values
The following query increases the `rest.total` counter by 11 and the `rest.paging` counter by 10 (as returned by `_sql/stats`):

```
GET http://localhost:9201/_sql

{
  "fetch_size": 10,
  "query": "select last_name, sum(languages) from test_emp group by 1 order by 2"
}
```

Expected behavior would be to only increase `rest.total` by 1.

The bug is caused by `LocalAggregationSorterListener` using `PlanExecutor` to fetch all records before sorting.

### PR DESCRIPTION
**Pull request by Luegg**
Resolves https://github.com/elastic/elasticsearch/issues/81502

The bug has been caused by `Querier` using `PlanExecutor.nextPage` for internal calls. Because `PlanExecutor.nextPage` also reports the API usage metrics, the `<clientType>.paging`, `<clientType>.total`, `_all.paging` and `_all.total` counters have been increased incorrectly for queries performing a sort on aggregated values.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java [hunk 1]
```diff
@@ -91,24 +88,19 @@
...
-    private final QueryBuilder filter;
-
-    public Querier(SqlSession sqlSession) {
-        this.planExecutor = sqlSession.planExecutor();
-        this.client = sqlSession.client();
-        this.cfg = sqlSession.configuration();
-        this.filter = cfg.filter();
-        this.size = cfg.pageSize();
+
+    public Querier(Client client, NamedWriteableRegistry writeableRegistry, SqlConfiguration cfg) {
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:95]: Also making the dependencies of `Querier` more precise and removing the redundant `size` and `filter` fields.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java [hunk 2]
```diff
@@ -245,7 +237,7 @@ public void onResponse(Page page) {
             // 1a. trigger a next call if there's still data
             if (cursor != Cursor.EMPTY) {
                 // trigger a next call
-                planExecutor.nextPage(cfg, cursor, this);
+                cursor.nextPage(cfg, client, writeableRegistry, this);
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:240]: Why this change? The plan executor is the one that increments the metrics; by calling the cursor this is skipped.
Is this what's causing the bug? Wouldn't it be easier to fix `planExecutor.nextPage` to stop incrementing total and only next?
The cursor shouldn't be used directly outside the planExecutor - the point of the latter is to abstract low-level details like `writeableRegistry` which now require handling.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:95]: Not sure if this is an improvement since all these arguments are available on the session - it's now on the caller to unpack these items.
It's unclear to me what the gain is.

**Review by costin — COMMENTED** [review]
Unclear why the planExecutor wasn't fixed directly instead of the querier.
It's the former that does the metric counting since it's the central entity for doing navigation.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:240]: @costin @Luegg regarding
> Wouldn't it be easier to fix planExecutor.nextPage to stop incrementing total and only next?

I think `total` should still be incremented. This is counting the `rest` calls, be it paging calls with cursor or regular (no pagination) calls, it's still a REST call. This has been like this by design.
The bug lies in counting the "internal" (in the background) calls that ORDER-BY-an-aggregation-function is performing to gather all the data in memory and do the sorting in memory. We assume paging stats should be for end-user paging calls, which is true, but with `ORDER BY SUM` we are using the same mechanism.

What should be happening though, is that PlanExecutor should have a `nextPage` and an "internal" `nextPage`. Both will do the same set of operation except the internal one will not increase the stats counter.

Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:240]: As far as I understand, the metric is supposed to count the number of calls o the SQL APIs, not the internal calls that are implementation dependent. Alternatively, we could also have an internal implementation of `PlanExecutor.nextPage` that does not increment the counters and inject `PlanExecutor` into `Querier`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:95]: `SqlSession` is a very powerful class, so currently we're exposing a lot of power to `Querier` by default. Also, it requires callers to actually have an `SqlSession` which is asking for a lot. Since there is only one caller using `Querier` plus the `QuerierTests` that had to mock `SqlSession` the amount of code is even reduced.

Not feeling super strong about this change but I think it helps to avoid errors like the one fixed by this PR.

**Review by astefan — COMMENTED** [review]
Nice bug find!
I've added a comment regarding the tests which, even though they text the fix, I think it'd be better if you add tests showing "paging" counter working as expected.

Also, I think the description you added in the PR doesn't actually explain the issue. Sorting by an aggregate has been added after the metrics were introduced. I would prefer a description more like "skip increasing the paging stats counter for ORDER BY an aggregate type of queries (which use pagination to gather all the values to be sorted afterwards in memory)"

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java]: 👍 looks like we had the same idea at the same time :)

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlUsageTestCase.java [hunk 3]
```diff
@@ -224,6 +240,47 @@ public void testSqlRestUsage() throws IOException {
         assertClientTypeAndAllQueryMetrics(clientTypeTotalQueries, allTotalQueries, responseAsMap);
     }
 
+    public void testScrollUsage() throws IOException {
+        index(testData);
+
+        String cursor = runSql("SELECT page_count, name FROM library ORDER BY page_count", 1);
```
Comment (astefan) [inline x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlUsageTestCase.java:246]: You could randomize the `fetchSize` value with something between 1 and `testData.size()`.

**Review by astefan — APPROVED** [review]
LGTM
Left one small suggestion.
Don't forget to change the description of the PR.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java]: > I think it helps to avoid errors like the one fixed by this PR.

Wondering if this still holds with current proposed change.
(I personally tend to favor shorter args lists too, but feel as weak about it in this case.)

**Review by bpintea — APPROVED** [review]
Lgtm.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java]: I still think that it holds but I'm reverting the change because there seems to be a general preference of the `SqlSession` param.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java]: I missed that the change happens inside `LocalAggregationSorterListener`, makes sense now.

**Review by costin — APPROVED** [review]
LGTM
