### PR TITLE
Read streams in blob store retries tests

### LINKED ISSUE #142315: [CI] GoogleCloudStorageBlobContainerRetriesTests testRetriesAreTerminatedWhenClientProviderIsClosed failing
**Build Scans:**
- [elasticsearch-periodic #11869 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/gz4hg6ng4njbw)
- [elasticsearch-periodic #11869 / openjdk21_checkpart1_java-fips-140-3-matrix](https://gradle-enterprise.elastic.co/s/v6yzui7ntedse)
- [elasticsearch-periodic #11869 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/zb3rqsovpephc)

**Reproduction Line:**
```
./gradlew ":modules:repository-gcs:test" --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests.testRetriesAreTerminatedWhenClientProviderIsClosed" -Dtests.seed=2BE914A890913301 -Dtests.locale=en-DE -Dtests.timezone=Europe/Ljubljana -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRetriesAreTerminatedWhenClientProviderIsClosed'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected org.apache.lucene.store.AlreadyClosedException to be thrown, but nothing was thrown
```

**Issue Reasons:**
- [main] 3 consecutive failures in test testRetriesAreTerminatedWhenClientProviderIsClosed
- [main] 3 failures in test testRetriesAreTerminatedWhenClientProviderIsClosed (6.0% fail rate in 50 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #142318: [CI] AzureBlobContainerRetriesTests class failing
**Build Scans:**
- [elasticsearch-intake #34506 / part1](https://gradle-enterprise.elastic.co/s/lr3gmy4em6x2w)
- [elasticsearch-pull-request #120254 / part-1](https://gradle-enterprise.elastic.co/s/6ic7g3g5nvtha)
- [elasticsearch-periodic #11869 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/gz4hg6ng4njbw)
- [elasticsearch-pull-request #120236 / part-1](https://gradle-enterprise.elastic.co/s/izmqbm43hx656)
- [elasticsearch-periodic-java-ea #173 / checkpart1_windows-2025](https://gradle-enterprise.elastic.co/s/mqe4pi6has7pm)
- [elasticsearch-pull-request #119806 / part-1](https://gradle-enterprise.elastic.co/s/yarke5nynvms6)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [main] 6 failures in class org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests (1.8% fail rate in 335 executions)
- [main] 3 failures in step part-1 (1.4% fail rate in 221 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.4% fail rate in 218 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
On JDK21 it turns out we need to read from these streams or else we
won't trigger any retries.

Closes #142315
Closes #142318

### CODE REVIEW

**Review by joshua-adams-1 — APPROVED** [review]
LGTM! Good catch

**Comment by DaveCTurner** [comment]
@nicktindall https://github.com/elastic/elasticsearch/pull/142193 got backported to `9.3` but https://github.com/elastic/elasticsearch/pull/142187 is only on `main` (i.e. 9.4+) - was this inconsistency intentional? I've marked this fix for backporting to 9.3 too and will have to fix it up if the Azure change is not going back there.

**Comment by nicktindall** [comment]
> @nicktindall https://github.com/elastic/elasticsearch/pull/142193 got backported to `9.3` but https://github.com/elastic/elasticsearch/pull/142187 is only on `main` (i.e. 9.4+) - was this inconsistency intentional? I've marked this fix for backporting to 9.3 too and will have to fix it up if the Azure change is not going back there.

Hi @DaveCTurner thanks for fixing this, I don't believe the Azure retrying change made it into 9.3, it was the last one to be done. Hence the lack of a backport.

I will double check that today and add any necessary backports.

**Comment by DaveCTurner** [comment]
++ thanks - I backported this just for the GCS test, please make sure to include this in the Azure backport if you do that.

**Comment by nicktindall** [comment]
Just for posterity, there is no `AzureRetryingInputStream` in 9.3 so the problematic test wasn't back-ported. Nothing to do here.

File: modules/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureBlobContainerRetriesTests.java [hunk 1]
```diff
@@ -653,7 +653,10 @@ public void testRetriesAreTerminatedWhenClientProviderIsClosed() {
             }
         });
 
-        assertThrows(AlreadyClosedException.class, () -> blobContainer.readBlob(randomRetryingPurpose(), "read_blob_while_store_closes"));
+        assertThrows(
```
Comment (joshua-adams-1) [inline modules/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureBlobContainerRetriesTests.java:656]: On a second reading, why did we only make changes to the `testRetriesAreTerminatedWhenClientProviderIsClosed` function when the linked failing test issue https://github.com/elastic/elasticsearch/issues/142318 specified the entire class was failing? Is it because tests run sequentially so if this the stream isn't read properly, then it affects the next test?

I only ask because there has been a second test failure https://github.com/elastic/elasticsearch/issues/142423 and I'm trying to understand the process behind how this was diagnosed / debugged

Comment (DaveCTurner) [reply modules/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureBlobContainerRetriesTests.java:656]: Ummm. I ran the AzureBlobContainerRetriesTests too and they also failed on JDK21, but you're right I didn't actually look at the build scans. They seem to have a different cause indeed.
