### PR TITLE
Fix `ThreadedActionListenerTests#testRejectionHandling`

### LINKED ISSUE #130129: [CI] ThreadedActionListenerTests testRejectionHandling failing
**Build Scans:**
- [elasticsearch-intake #25664 / part1](https://gradle-enterprise.elastic.co/s/uo76sv3lczrsm)
- [elasticsearch-periodic #9388 / openjdk17_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/a2z7swmmn3uq2)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.action.support.ThreadedActionListenerTests.testRejectionHandling" -Dtests.seed=9DF70F4BBA3E5A3 -Dtests.locale=ru -Dtests.timezone=AST -Druntime.java=24
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.action.support.ThreadedActionListenerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRejectionHandling'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.19] 2 failures in test testRejectionHandling (1.6% fail rate in 122 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Closes #130129

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java [hunk 1]
```diff
@@ -75,7 +77,9 @@ public void onResponse(Void ignored) {}
                             public void onFailure(Exception e) {
                                 assertNull(e.getCause());
                                 if (e instanceof EsRejectedExecutionException esRejectedExecutionException) {
-                                    assertTrue(esRejectedExecutionException.isExecutorShutdown());
+                                    if (pool.equals("fixed-bounded-queue") == false || forceExecution) {
+                                        assertTrue(esRejectedExecutionException.isExecutorShutdown());
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:86]: This is the key fix, we sometimes reject these tasks on the bounded queue before the executor is shut down.

**Review by DaveCTurner — COMMENTED** [review]
This test had weak coverage because it would usually shut the threadpool down before doing anything else. Introduced another latch to delay the shutdown a bit, and also fixed the actual problem.

File: server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java (hunk 1 above)
Comment (kingherc) [reply server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:86]: nit David just to understand, would they be rejected on the bounded queue because it's bounded? I.e., it happens that more than 10 listeners are submitted to it before they are actully triggered?

If so, I think a code comment above this fix would be nice as well.

File: server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java [hunk 2]
```diff
@@ -31,7 +31,8 @@ public class ThreadedActionListenerTests extends ESTestCase {
 
     public void testRejectionHandling() throws InterruptedException {
         final var listenerCount = between(1, 1000);
-        final var countdownLatch = new CountDownLatch(listenerCount);
+        final var startLatch = new CountDownLatch(between(1, listenerCount));
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:36]: nit 

```suggestion
        final var latchMinListenersToStartBeforeShutdown = new CountDownLatch(between(1, listenerCount));
```

File: server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java [hunk 3]
```diff
@@ -31,7 +31,8 @@ public class ThreadedActionListenerTests extends ESTestCase {
...
+        final var finishLatch = new CountDownLatch(listenerCount);
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:39]: nit

```suggestion
        final var latchAllListenersCompleted = new CountDownLatch(listenerCount);
```

**Review by kingherc — APPROVED** [review]
LGTM @DaveCTurner , just some nits for potentially improve readability, feel free to pick any of them as you see fit.

File: server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:36]: I've added a comment describing `startLatch` but I find such long symbol names to be somewhat hostile to readers so I'd rather keep it as-is.

File: server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:39]: I've added a comment describing `finishLatch` but I find such long symbol names to be somewhat hostile to readers so I'd rather keep it as-is.

Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/support/ThreadedActionListenerTests.java:39]: I would prefer the more descriptive version, to be honest. 

This test is generally very hard to understand. I wonder if there's a way to reveal the intention of particular sections anyhow... and e.g. separate the "setup" "run" and "verification" parts of the test.

Just a loose idea.
