### PR TITLE
Reduce profiling overhead.

### LINKED ISSUE #24799: Wrapping collect(doc) with System.nanoTime() calls is a poor choice
`org.elasticsearch.search.profile.ProfileCollector` uses this approach to measure time spent:
```
            public void collect(int doc) throws IOException {
                final long start = System.nanoTime();
                try {
                    super.collect(doc);
                } finally {
                    time += Math.max(1, System.nanoTime() - start);
                }
            }
```

`nanoTime()` however is rather slow itself (in the range of 30-40 ns). And can even have microseconds granularity on some platforms.

See this, for example:
http://stas-blogspot.blogspot.nl/2012/02/what-is-behind-systemnanotime.html
https://shipilev.net/blog/2014/nanotrusting-nanotime/

So for high-rate calls like `collect(doc)` you'd get something like this:
image

Instead you should probably measure time for every 1000 `collect()` calls.
Or use stack trace sampling like [commercial profilers do](http://stackoverflow.com/a/2482313/306345). (which is probably an overkill in this case)

### PR DESCRIPTION
**Pull request by jpountz**
Calling `System.nanoTime()` for each method call may have a significant
performance impact.

Closes #24799

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/search/profile/TimerTests.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+        final AtomicLong counter = new AtomicLong();
+        Timer t = new Timer() {
+            long time = 50;
+            @Override
+            long nanoTime() {
+                counter.incrementAndGet();
+                return time += 1;
+            }
+        };
+        for (int i = 0; i < 100000; ++i) {
```
Comment (danielmitterdorfer) [inline core/src/test/java/org/elasticsearch/search/profile/TimerTests.java]: nit: unrelated but maybe we should use a separator here and write it as `100_000`?

File: core/src/main/java/org/elasticsearch/search/profile/Timer.java [hunk 2]
```diff
@@ -33,38 +33,59 @@
...
+    public final long getTiming() {
         if (start != 0) {
             throw new IllegalStateException("#start call misses a matching #stop call");
         }
-        return timing;
+        // We don't have timings for the last `count-lastCount` method calls
+        // se we assume that they had the same timing as the lastCount first
+        // calls. This approximation is ok since at most 1/256th of method
+        // calls have not been timed.
+        return timing + (count - lastCount) * timing / lastCount;
```
Comment (danielmitterdorfer) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: Makes sense to me.

**Review by danielmitterdorfer — APPROVED** [review]
I left a couple of comments but I think nothing critical. LGTM.

File: core/src/test/java/org/elasticsearch/search/profile/TimerTests.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+package org.elasticsearch.search.profile;
+
+import org.elasticsearch.test.ESTestCase;
+
+import java.util.concurrent.atomic.AtomicLong;
+
+public class TimerTests extends ESTestCase {
+
+    public void testTimingInterval() {
+        final AtomicLong counter = new AtomicLong();
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/search/profile/TimerTests.java]: this counter counts how many times nanoTime is called. I should rename it.

File: core/src/test/java/org/elasticsearch/search/profile/TimerTests.java (hunk 1 above)
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/search/profile/TimerTests.java]: ok

File: core/src/main/java/org/elasticsearch/search/profile/Timer.java [hunk 4]
```diff
@@ -33,38 +33,59 @@
...
         if (start != 0) {
             throw new IllegalStateException("#start call misses a matching #stop call");
         }
         return count;
     }
 
-    /** Return an approximation of the total time spend between consecutive calls of #start and #stop. */
-    public long getTiming() {
+    /** Return an approximation of the total time spent between consecutive calls of #start and #stop. */
+    public final long getTiming() {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: ok

File: core/src/test/java/org/elasticsearch/search/profile/TimerTests.java (hunk 3 above)
Comment (danielmitterdorfer) [inline core/src/test/java/org/elasticsearch/search/profile/TimerTests.java]: Ah, I see. I totally missed that. Renaming is a good idea. :)

File: core/src/main/java/org/elasticsearch/search/profile/Timer.java [hunk 5]
```diff
@@ -33,38 +33,59 @@
...
-        start = System.nanoTime();
     }
 
     /** Stop the timer. */
-    public void stop() {
-        timing += Math.max(System.nanoTime() - start, 1L);
-        start = 0;
+    public final void stop() {
+        if (doTiming) {
+            timing += (count - lastCount) * Math.max(nanoTime() - start, 1L);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: True. This is a pre-existing issue that I don't know how to fix without changing the approach entirely.

File: core/src/main/java/org/elasticsearch/search/profile/Timer.java [hunk 6]
```diff
@@ -33,38 +33,59 @@
...
     /** Start the timer. */
-    public void start() {
+    public final void start() {
         assert start == 0 : "#start call misses a matching #stop call";
+        // We measure the timing of each method call for the first 256
+        // calls, then 1/2 call up to 512 then 1/3 up to 768, etc. with
+        // a maximum interval of 1024, which is reached for 1024*2^8 ~= 262000
+        // This allows to not slow down things too much because of calls
+        // to System.nanoTime() when methods are called millions of time
+        // in tight loops, while still providing useful timings for methods
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: 256 nanoTime calls should still take much less than 1ms so I don't worry about it

Comment (danielmitterdorfer) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: I was not aware of the relative times. What I meant was that calling `System.nanoTime()` takes on typical systems 30ns (see [nanotrusting nanotime](https://shipilev.net/blog/2014/nanotrusting-nanotime/#_one_off_measurements)). If the code you want to measure takes a similarly long time then you will have a significant measurement error. However, if you measure code that takes e.g. 500µs to execute, the overhead is much lower.

File: core/src/main/java/org/elasticsearch/search/profile/Timer.java (hunk 5 above)
Comment (danielmitterdorfer) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: This was more of a comment than a call-to-action for you. I also do not think that this can be overcome without changing the approach completely. This is the eternal dilemma of tracing vs. sampling. You have to pick one poison. :)

File: core/src/main/java/org/elasticsearch/search/profile/Timer.java (hunk 6 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/profile/Timer.java]: Agreed.
