### PR TITLE
Handle exceptions when register compute group

### LINKED ISSUE #123101: [CI] CrossClusterQueryWithPartialResultsIT testPartialResults failing
**Build Scans:**
- [elasticsearch-intake #19088 / part3](https://gradle-enterprise.elastic.co/s/5o4qzaxvyfy3m)
- [elasticsearch-periodic-platform-support #6671 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/673vpvfdtji7s)
- [elasticsearch-pull-request #59520 / part-3](https://gradle-enterprise.elastic.co/s/7ar3xiimmuvte)
- [elasticsearch-intake #18727 / part3](https://gradle-enterprise.elastic.co/s/5t3mi7bdl4yzg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT.testPartialResults" -Dtests.seed=CC9ED55CD72A903 -Dtests.locale=pcm-NG -Dtests.timezone=America/Caracas -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testPartialResults),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected IllegalStateException but got org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
```

**Issue Reasons:**
- [8.x] 4 failures in test testPartialResults (0.8% fail rate in 495 executions)
- [8.x] 2 failures in step part3 (3.7% fail rate in 54 executions)
- [8.x] 2 failures in pipeline elasticsearch-intake (3.7% fail rate in 54 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123216: [CI] CrossClusterQueryWithPartialResultsIT class failing
**Build Scans:**
- [elasticsearch-periodic #6717 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/tsxwelsf656oc)
- [elasticsearch-intake #19088 / part3](https://gradle-enterprise.elastic.co/s/5o4qzaxvyfy3m)
- [elasticsearch-periodic-platform-support #6671 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/673vpvfdtji7s)
- [elasticsearch-pull-request #59520 / part-3](https://gradle-enterprise.elastic.co/s/7ar3xiimmuvte)
- [elasticsearch-intake #18727 / part3](https://gradle-enterprise.elastic.co/s/5t3mi7bdl4yzg)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 5 failures in class org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT (0.8% fail rate in 655 executions)
- [8.x] 2 failures in step part3 (3.2% fail rate in 62 executions)
- [8.x] 2 failures in pipeline elasticsearch-intake (3.2% fail rate in 62 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123451: [CI] CrossClusterQueryWithPartialResultsIT testOneRemoteClusterPartial failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6632 / ubuntu-2004-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/d4lhfvwub2dwq)
- [elasticsearch-periodic-platform-support #6569 / almalinux-8-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/4blyzc6fnfodw)
- [elasticsearch-intake #18541 / part3](https://gradle-enterprise.elastic.co/s/pzljumvbuh4oc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT.testOneRemoteClusterPartial" -Dtests.seed=9379329E74F537E7 -Dtests.locale=en-VI -Dtests.timezone=Etc/GMT-4 -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClusterQueryWithPartialResultsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testOneRemoteClusterPartial),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 3 failures in test testOneRemoteClusterPartial (0.3% fail rate in 918 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (11.8% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
```  
  java.lang.AssertionError: org.elasticsearch.tasks.TaskCancelledException: task cancelled before starting [cancelled on failure]
        at __randomizedtesting.SeedInfo.seed([842AF61A97BFEAAA]:0)
        at org.elasticsearch.action.ActionListenerImplementations.expectNoException(ActionListenerImplementations.java:157)
        at org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:221)
        at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:97)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:49)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1499)
        at org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:434)
        at org.elasticsearch.transport.InboundHandler$2.doRun(InboundHandler.java:391)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

```
        Caused by:
        org.elasticsearch.tasks.TaskCancelledException: task cancelled before starting [cancelled on failure]
            at app//org.elasticsearch.tasks.TaskManager.registerCancellableTask(TaskManager.java:245)
            at app//org.elasticsearch.tasks.TaskManager.register(TaskManager.java:152)
            at app//org.elasticsearch.tasks.TaskManager.register(TaskManager.java:118)
            at app//org.elasticsearch.xpack.esql.plugin.ComputeService.createGroupTask(ComputeService.java:436)
            at app//org.elasticsearch.xpack.esql.plugin.ClusterComputeHandler.lambda$startComputeOnRemoteCluster$6(ClusterComputeHandler.java:112)
            at app//org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:219)
            ... 12 more
```

If the parent task is canceled, registering the compute group task might throw a TaskCancelledException, so the listener won't be notified.

Closes #123216
Closes #123101
Closes #123451

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 1]
```diff
@@ -431,7 +432,7 @@ Runnable cancelQueryOnFailure(CancellableTask task) {
         });
     }
 
-    CancellableTask createGroupTask(Task parentTask, Supplier<String> description) {
+    CancellableTask createGroupTask(Task parentTask, Supplier<String> description) throws TaskCancelledException {
```
Comment (smalyshev) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:435]: Isn't `TaskCancelledException` a runtime exception? So making it checked here doesn't do much except documenting the fact it may be thrown, am I missing something?

**Review by smalyshev — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 1 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:435]: Yes, that's correct.

**Comment by dnhatn** [comment]
Thanks everyone!
