### PR TITLE
Fix typed parameters in IndexRequestBuilder and CreateIndexRequestBuilder

### LINKED ISSUE #10825: Typed parameters in Java index API
I believe the method signature for `IndexRequestBuilder.setSource(Map<String, Object> source)` should be changed to `IndexRequestBuilder.setSource(Map<String, ?> source)`.
Since the method is overloaded, a call to `setSource` with a `Map<String, String>` as parameters will invoke the method `IndexRequestBuilder.setSource(Object... source)`, to great confusion. 

The same goes for `CreateIndexRequestBuilder.setSettings(Map<String, Object> source)` in the indices admin client, and a few others.

### PR DESCRIPTION
**Pull request by cbuescher**
IndexRequestBuilder#setSource as well as CreateIndexRequestBuilder#setSettings and CreateIndexRequestBuilder#setSouce will not work with `Map<String, String>` argument although the API looks like it should. This PR fixes the problem introducing correct wildcard parameters and adds tests.

Closes #10825

### CODE REVIEW

File: src/test/java/org/elasticsearch/action/index/IndexRequestBuilderTest.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+import org.elasticsearch.common.xcontent.XContentHelper;
+import org.elasticsearch.common.xcontent.XContentType;
+import org.elasticsearch.test.ElasticsearchSingleNodeTest;
+import org.junit.Test;
+
+import java.io.ByteArrayOutputStream;
+import java.util.HashMap;
+import java.util.Map;
+
+public class IndexRequestBuilderTest extends ElasticsearchSingleNodeTest {
```
Comment (javanna) [inline src/test/java/org/elasticsearch/action/index/IndexRequestBuilderTest.java]: do we really need a node here? I don't think we are sending any request? Should it just extend `ElasticsearchTestCase`?

File: src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequestBuilderTest.java [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+import org.elasticsearch.common.xcontent.XContentFactory;
+import org.elasticsearch.test.ElasticsearchSingleNodeTest;
+import org.junit.Test;
+
+import java.io.ByteArrayOutputStream;
+import java.io.IOException;
+import java.util.HashMap;
+import java.util.Map;
+
+public class CreateIndexRequestBuilderTest extends ElasticsearchSingleNodeTest {
```
Comment (javanna) [inline src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequestBuilderTest.java]: do we really need a node here? I don't think we are sending any request? Should it just extend `ElasticsearchTestCase`?

**Comment by javanna** [comment]
left one comment around testing, looks good besides that

File: src/test/java/org/elasticsearch/action/index/IndexRequestBuilderTest.java (hunk 1 above)
Comment (cbuescher) [inline src/test/java/org/elasticsearch/action/index/IndexRequestBuilderTest.java]: I had problems creating empty IndexRequestBuilder without a client (`IndexRequestBuilder(ElasticsearchClient client, IndexAction action)`), if there's any dummy client implementation I can pass in there that would probably possible. Used the ElasticsearchSingleNodeTest because of its handy creation of the IndexRequestBuilder.

Comment (cbuescher) [inline src/test/java/org/elasticsearch/action/index/IndexRequestBuilderTest.java]: I found a workaround using an inner `DummyClient implements ElasticsearchClient` class, but that bloats the test. It's really fast though. Would be an ideal use case for Mockito or Jmock, not sure if I already asked around if we can use that in core? I think I saw it beeing used in Shield?

Comment (javanna) [inline src/test/java/org/elasticsearch/action/index/IndexRequestBuilderTest.java]: I think we have at least one similar test that does the same, we can maybe share the dummy client to minimize the code repetition. It's not that we cannot use mockito, we could, we would need to have a bigger discussion around it, some people are in favour of that and some others are totally against it. I personally don't think mockito would solve all our problems, we should strive to make elasticsearch more unit testable, easier to say that to do though :)

**Comment by cbuescher** [comment]
I changed the tests to use an existing NoOpClient to make it a proper unit test case. To facilitate that I moved the formerly private test client to its own class alongside the original test it came from. This way I can use it in my own test setup.

**Comment by javanna** [comment]
looks great thanks a lot @cbuescher
