### PR TITLE
fix(logsdb): batch bulk indexing to prevent OOM in challenge tests

### LINKED ISSUE #138717: [CI] BulkDynamicMappingChallengeRestIT testEsqlTermsAggregation failing
**Build Scans:**
- [elasticsearch-intake #31702 / part2](https://gradle-enterprise.elastic.co/s/67wutxa43m7os)
- [elasticsearch-pull-request #105601 / part-2](https://gradle-enterprise.elastic.co/s/z46y7yfxqfdcc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:logsdb:javaRestTest" --tests "org.elasticsearch.xpack.logsdb.qa.BulkDynamicMappingChallengeRestIT.testEsqlTermsAggregation" -Dtests.seed=5BC46FD84CD43571 -Dtests.locale=de-IT -Dtests.timezone=America/Rankin_Inlet -Druntime.java=25
```

**Applicable branches:**
9.2

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.logsdb.qa.BulkDynamicMappingChallengeRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testEsqlTermsAggregation'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.OutOfMemoryError: Java heap space
```

**Issue Reasons:**
- [9.2] 2 failures in test testEsqlTermsAggregation (1.4% fail rate in 143 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Fixes flaky OOM test failure in `BulkDynamicMappingChallengeRestIT.testEsqlTermsAggregation`.

The test was failing intermittently with `java.lang.OutOfMemoryError: Java heap space` when building bulk request strings for large randomly-generated documents.

When indexing documents, the test built a single bulk request string containing all documents. With complex mappings and several documents, the bulk request string could grow quite large.

Changes include:
1. Batch bulk indexing (`BulkChallengeRestIT.java`):
   * Documents are now indexed in batches of 20 instead of all at once
   * Extracted common batching logic into `indexDocumentsInBatches()` method
   * Reuses `StringBuilder` with `setLength(0)` instead of creating new instances

2. Disable ML (`AbstractChallengeRestTest.java`):
   * Added `.setting("xpack.ml.enabled", "false")` since these tests don't require ML
   

Closes #138717

### CODE REVIEW

File: x-pack/plugin/logsdb/src/javaRestTest/java/org/elasticsearch/xpack/logsdb/qa/AbstractChallengeRestTest.java [hunk 1]
```diff
@@ -60,6 +60,7 @@ public abstract class AbstractChallengeRestTest extends ESRestTestCase {
         .setting("xpack.security.autoconfiguration.enabled", "false")
         .setting("xpack.license.self_generated.type", "trial")
         .setting("cluster.logsdb.enabled", "true")
+        .setting("xpack.ml.enabled", "false")
```
Comment (martijnvg) [inline x-pack/plugin/logsdb/src/javaRestTest/java/org/elasticsearch/xpack/logsdb/qa/AbstractChallengeRestTest.java:63]: I don't think this will really affect test coverage. This isn't like disabling security.

**Review by martijnvg — APPROVED** [review]
LGTM

File: x-pack/plugin/logsdb/src/javaRestTest/java/org/elasticsearch/xpack/logsdb/qa/AbstractChallengeRestTest.java (hunk 1 above)
Comment (salvatore-campagna) [reply x-pack/plugin/logsdb/src/javaRestTest/java/org/elasticsearch/xpack/logsdb/qa/AbstractChallengeRestTest.java:63]: Right...I guess it is still useful anyway as it is not really needed and allows to reproduce the test locally. When I tried to run the test locally it was failing with:

```
[2025-12-18T07:11:59,849][ERROR][o.e.b.Elasticsearch      ] [test-cluster-0] fatal exception while booting Elasticsearch org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
```
