### PR TITLE
Track source for arrays of objects

### LINKED ISSUE #90708: Synthetic _source: preserve source for specific fields (object arrays)
We'd really like to use synthetic source for the traces index in APM but we hit a few blockers.

While for most of the fields, we should be good with the modifications of the synthetic _source compared to the original _source, there are a few fields where it is problematic that arrays are moved to leaf fields that are ordered alphabetically and de-duplicated.

Currently we know about these two fields that are problematic: `span.links` and `error.stacktrace`. As these fields are not present in the majority of documents, we'd be fine with just storing the plain _source. In fact, `error.stacktrace` is not actually mapped at all (the mapping is configured with `dynamic: false`, therefore _source is the only place where the stack trace is stored) and we never do queries or aggregations on it. The `span.links` field is mapped and we do queries on it, but we rely on being able to retrieve the original source as it is an array of objects.

Ideally, we'd just mark these two fields to opt-into storing the original source for them, even if synthetic source is enabled in the mapping.

An alternative we thought about is that we store the source of these fields in a dedicated field as an escaped JSON string. However, this would requite a lot more changes in the application so we'd hope for something more transparent.

<details>
<summary>Click to expand contrived <code>span.links</code> example</summary>

```json
{
  "span": {
    "links": [
      {
        "trace": {
          "id": "a"
        },
        "span": {
          "id": "1"
        }
      },
      {
        "trace": {
          "id": "b"
        },
        "span": {
          "id": "1"
        }
      }
    ]
  }
}
```
</details>

<details>
<summary>Click to expand full example span with a <code>stacktrace</code></summary>

```json
{
  "_index": ".ds-traces-apm-default-2022.09.07-000010",
  "_id": "HOp_g4MBOF4RiJ14nodp",
  "_score": 1,
  "_source": {
    "parent": {
      "id": "7b8a7bd5c40cba85"
    },
    "agent": {
      "name": "java",
      "ephemeral_id": "e7c145da-7a81-42cd-aadd-e2a8720dfdce",
      "version": "1.33.0"
    },
    "data_stream.namespace": "default",
    "destination": {
      "address": "db-postgresql",
      "port": 5432
    },
    "processor": {
      "name": "transaction",
      "event": "span"
    },
    "data_stream.type": "traces",
    "cloud": {
      "availability_zone": "us-central1-c",
      "instance": {
        "name": "gke-release-oblt-release-oblt-pool-c4163099-5vhg",
        "id": "2598324766217814632"
      },
      "provider": "gcp",
      "machine": {
        "type": "n1-standard-4"
      },
      "project": {
        "name": "elastic-observability",
        "id": "8560181848"
      },
      "region": "us-central1"
    },
    "observer": {
      "hostname": "7e3186d65a3a",
      "id": "476bfcfa-fbc9-4c12-9709-68138fd31009",
      "ephemeral_id": "940f2094-a11a-4ab3-98af-55830c19fe5d",
      "type": "apm-server",
      "version": "8.4.2"
    },
    "trace": {
      "id": "c68001c7c6a43442a173f59298a64c33"
    },
    "@timestamp": "2022-09-28T09:48:31.312Z",
    "ecs": {
      "version": "1.12.0"
    },
    "service": {
      "environment": "testing",
      "name": "opbeans-java",
      "target": {
        "name": "opbeans-java",
        "type": "postgresql"
      }
    },
    "data_stream.dataset": "apm",
    "event": {
      "agent_id_status": "missing",
      "ingested": "2022-09-28T09:48:42Z",
      "outcome": "success"
    },
    "transaction": {
      "id": "7b8a7bd5c40cba85"
    },
    "timestamp": {
      "us": 1664358511312010
    },
    "span": {
      "duration": {
        "us": 10981
      },
      "stacktrace": [
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "ApplicationFilterChain.java",
          "classname": "org.apache.catalina.core.ApplicationFilterChain",
          "line": {
            "number": 168
          },
          "function": "doFilter",
          "module": "org.apache.catalina.core"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "StandardWrapperValve.java",
          "classname": "org.apache.catalina.core.StandardWrapperValve",
          "line": {
            "number": 198
          },
          "function": "invoke",
          "module": "org.apache.catalina.core"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "StandardContextValve.java",
          "classname": "org.apache.catalina.core.StandardContextValve",
          "line": {
            "number": 96
          },
          "function": "invoke",
          "module": "org.apache.catalina.core"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "AuthenticatorBase.java",
          "classname": "org.apache.catalina.authenticator.AuthenticatorBase",
          "line": {
            "number": 496
          },
          "function": "invoke",
          "module": "org.apache.catalina.authenticator"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "StandardHostValve.java",
          "classname": "org.apache.catalina.core.StandardHostValve",
          "line": {
            "number": 140
          },
          "function": "invoke",
          "module": "org.apache.catalina.core"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "ErrorReportValve.java",
          "classname": "org.apache.catalina.valves.ErrorReportValve",
          "line": {
            "number": 81
          },
          "function": "invoke",
          "module": "org.apache.catalina.valves"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "StandardEngineValve.java",
          "classname": "org.apache.catalina.core.StandardEngineValve",
          "line": {
            "number": 87
          },
          "function": "invoke",
          "module": "org.apache.catalina.core"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "CoyoteAdapter.java",
          "classname": "org.apache.catalina.connector.CoyoteAdapter",
          "line": {
            "number": 342
          },
          "function": "service",
          "module": "org.apache.catalina.connector"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "Http11Processor.java",
          "classname": "org.apache.coyote.http11.Http11Processor",
          "line": {
            "number": 803
          },
          "function": "service",
          "module": "org.apache.coyote.http11"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "AbstractProcessorLight.java",
          "classname": "org.apache.coyote.AbstractProcessorLight",
          "line": {
            "number": 66
          },
          "function": "process",
          "module": "org.apache.coyote"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "AbstractProtocol.java",
          "classname": "org.apache.coyote.AbstractProtocol$ConnectionHandler",
          "line": {
            "number": 790
          },
          "function": "process",
          "module": "org.apache.coyote"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "NioEndpoint.java",
          "classname": "org.apache.tomcat.util.net.NioEndpoint$SocketProcessor",
          "line": {
            "number": 1468
          },
          "function": "doRun",
          "module": "org.apache.tomcat.util.net"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "SocketProcessorBase.java",
          "classname": "org.apache.tomcat.util.net.SocketProcessorBase",
          "line": {
            "number": 49
          },
          "function": "run",
          "module": "org.apache.tomcat.util.net"
        },
        {
          "exclude_from_grouping": false,
          "library_frame": true,
          "filename": "TaskThread.java",
          "classname": "org.apache.tomcat.util.threads.TaskThread$WrappingRunnable",
          "line": {
            "number": 61
          },
          "function": "run",
          "module": "org.apache.tomcat.util.threads"
        }
      ],
      "subtype": "postgresql",
      "name": "SELECT FROM order_lines",
      "destination": {
        "service": {
          "resource": "postgresql/opbeans-java"
        }
      },
      "action": "query",
      "id": "2a892de57a2fd152",
      "type": "db",
      "db": {
        "instance": "opbeans-java",
        "statement": "select product1_.id as col_0_0_, product1_.sku as col_1_0_, product1_.name as col_2_0_, product1_.stock as col_3_0_, sum(orderline0_.amount) as col_4_0_ from order_lines orderline0_ left outer join products product1_ on orderline0_.product_id=product1_.id group by product1_.id order by col_4_0_ desc limit ?",
        "type": "sql",
        "user": {
          "name": "elastic"
        }
      }
    }
  },
  "fields": {
    "span.name": [
      "SELECT FROM order_lines"
    ],
    "span.action": [
      "query"
    ],
    "destination.port": [
      5432
    ],
    "cloud.project.name": [
      "elastic-observability"
    ],
    "cloud.availability_zone": [
      "us-central1-c"
    ],
    "transaction.id": [
      "7b8a7bd5c40cba85"
    ],
    "cloud.instance.id": [
      "2598324766217814632"
    ],
    "trace.id": [
      "c68001c7c6a43442a173f59298a64c33"
    ],
    "span.duration.us": [
      10981
    ],
    "processor.event": [
      "span"
    ],
    "service.target.type": [
      "postgresql"
    ],
    "agent.name": [
      "java"
    ],
    "destination.address": [
      "db-postgresql"
    ],
    "event.agent_id_status": [
      "missing"
    ],
    "event.outcome": [
      "success"
    ],
    "service.environment": [
      "testing"
    ],
    "cloud.region": [
      "us-central1"
    ],
    "service.name": [
      "opbeans-java"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "processor.name": [
      "transaction"
    ],
    "span.id": [
      "2a892de57a2fd152"
    ],
    "span.subtype": [
      "postgresql"
    ],
    "service.target.name": [
      "opbeans-java"
    ],
    "data_stream.type": [
      "traces"
    ],
    "observer.hostname": [
      "7e3186d65a3a"
    ],
    "span.type": [
      "db"
    ],
    "cloud.machine.type": [
      "n1-standard-4"
    ],
    "cloud.provider": [
      "gcp"
    ],
    "timestamp.us": [
      1664358511312010
    ],
    "observer.id": [
      "476bfcfa-fbc9-4c12-9709-68138fd31009"
    ],
    "event.ingested": [
      "2022-09-28T09:48:42Z"
    ],
    "@timestamp": [
      "2022-09-28T09:48:31.312Z"
    ],
    "observer.ephemeral_id": [
      "940f2094-a11a-4ab3-98af-55830c19fe5d"
    ],
    "observer.version": [
      "8.4.2"
    ],
    "ecs.version": [
      "1.12.0"
    ],
    "observer.type": [
      "apm-server"
    ],
    "data_stream.dataset": [
      "apm"
    ],
    "agent.ephemeral_id": [
      "e7c145da-7a81-42cd-aadd-e2a8720dfdce"
    ],
    "parent.id": [
      "7b8a7bd5c40cba85"
    ],
    "agent.version": [
      "1.33.0"
    ],
    "span.destination.service.resource": [
      "postgresql/opbeans-java"
    ],
    "cloud.instance.name": [
      "gke-release-oblt-release-oblt-pool-c4163099-5vhg"
    ],
    "cloud.project.id": [
      "8560181848"
    ]
  }
}
```
</details>

<details>
<summary>Click to expand traces index mapping</summary>

```json
{
  "mappings": {
    "dynamic": "false",
    "_meta": {
      "package": {
        "name": "apm"
      },
      "managed_by": "fleet",
      "managed": true
    },
    "_data_stream_timestamp": {
      "enabled": true
    },
    "dynamic_templates": [
      {
        "numeric_labels": {
          "path_match": "numeric_labels.*",
          "mapping": {
            "scaling_factor": 1000000,
            "type": "scaled_float"
          }
        }
      },
      {
        "strings_as_keyword": {
          "match_mapping_type": "string",
          "mapping": {
            "ignore_above": 1024,
            "type": "keyword"
          }
        }
      }
    ],
    "date_detection": false,
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "agent": {
        "properties": {
          "ephemeral_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "child": {
        "properties": {
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "client": {
        "properties": {
          "domain": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "geo": {
            "properties": {
              "city_name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "continent_name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "country_iso_code": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "country_name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "location": {
                "type": "geo_point"
              },
              "region_iso_code": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "region_name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "ip": {
            "type": "ip"
          },
          "port": {
            "type": "long"
          }
        }
      },
      "cloud": {
        "properties": {
          "account": {
            "properties": {
              "id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "availability_zone": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "instance": {
            "properties": {
              "id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "machine": {
            "properties": {
              "type": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "origin": {
            "properties": {
              "account": {
                "properties": {
                  "id": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              },
              "provider": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "region": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "service": {
                "properties": {
                  "name": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "project": {
            "properties": {
              "id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "provider": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "region": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "service": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          }
        }
      },
      "container": {
        "properties": {
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "data_stream": {
        "properties": {
          "dataset": {
            "type": "constant_keyword",
            "value": "apm"
          },
          "namespace": {
            "type": "constant_keyword",
            "value": "default"
          },
          "type": {
            "type": "constant_keyword",
            "value": "traces"
          }
        }
      },
      "destination": {
        "properties": {
          "address": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ip": {
            "type": "ip"
          },
          "port": {
            "type": "long"
          }
        }
      },
      "ecs": {
        "properties": {
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "event": {
        "properties": {
          "agent_id_status": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ingested": {
            "type": "date",
            "format": "strict_date_time_no_millis||strict_date_optional_time||epoch_millis"
          },
          "outcome": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "faas": {
        "properties": {
          "coldstart": {
            "type": "boolean"
          },
          "execution": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "trigger": {
            "properties": {
              "request_id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "type": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "host": {
        "properties": {
          "architecture": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "hostname": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ip": {
            "type": "ip"
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "os": {
            "properties": {
              "platform": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          }
        }
      },
      "http": {
        "properties": {
          "request": {
            "properties": {
              "headers": {
                "type": "object"
              },
              "method": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "referrer": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "response": {
            "properties": {
              "finished": {
                "type": "boolean"
              },
              "headers": {
                "type": "object"
              },
              "status_code": {
                "type": "long"
              }
            }
          },
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "kubernetes": {
        "properties": {
          "namespace": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "node": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "pod": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "uid": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          }
        }
      },
      "labels": {
        "dynamic": "true",
        "properties": {
          "a": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "administrativeMonitor": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_host_ip": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_host_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_host_user": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_session": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_args_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_args_value": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_host_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_host_status": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_message": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_module": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_task_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ansible_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "b": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_multibranch_type": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_run_cause": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_run_committers": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_run_completed": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_run_result": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_run_url": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_run_user": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ci_pipeline_type": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "company": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "complete": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "completed": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "customer_email": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "customer_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "customer_tier": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_connection_string": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_operation": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_sql_table": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_statement": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_system": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "db_user": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "enduser_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "exception_message": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "exception_type": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "foo": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "git_branch": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "git_clone_shallow": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "git_repository": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "git_username": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "host_ip": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "host_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "http_flavor": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "http_route": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_computer_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_opentelemetry_plugin_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_agent_label": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_interruption_causes": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_plugin_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_plugin_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_pipeline_step_type": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_url": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "jenkins_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "lorem": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_build_container_image_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_build_container_image_tags": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_build_container_registry_url": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_execution_goal": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_execution_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_execution_lifecyclePhase": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_plugin_artifactId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_plugin_groupId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_plugin_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_project_artifactId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_project_groupId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "maven_project_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "multi-line": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "net_transport": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "pitId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "process_runtime_description": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "query_index": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "query_keepAlive": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "query_match_jobFullName": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "query_match_traceId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "query_pointInTimeId": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "request_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "served_from_cache": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "service_namespace": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "telemetry_auto_version": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "this-is-a-very-long-tag-name-without-any-spaces": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "thread_name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "worker": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "network": {
        "properties": {
          "carrier": {
            "properties": {
              "icc": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "mcc": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "mnc": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "connection": {
            "properties": {
              "subtype": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "type": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          }
        }
      },
      "numeric_labels": {
        "dynamic": "true",
        "properties": {
          "ansible_task_result": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "ci_pipeline_run_durationMillis": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "ci_pipeline_run_number": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "events_encoded": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "events_failed": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "events_original": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "events_published": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "git_clone_depth": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "http_request_content_length": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "http_response_content_length": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "order_id": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "product_id": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "query_from": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "query_match_runNumber": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "query_size": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "response_size": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          },
          "thread_id": {
            "type": "scaled_float",
            "scaling_factor": 1000000
          }
        }
      },
      "observer": {
        "properties": {
          "ephemeral_id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "hostname": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "type": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "parent": {
        "properties": {
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "process": {
        "properties": {
          "args": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "pid": {
            "type": "long"
          },
          "ppid": {
            "type": "long"
          },
          "title": {
            "type": "keyword",
            "ignore_above": 1024,
            "fields": {
              "text": {
                "type": "match_only_text"
              }
            }
          }
        }
      },
      "processor": {
        "properties": {
          "event": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "name": {
            "type": "constant_keyword",
            "value": "transaction"
          }
        }
      },
      "service": {
        "properties": {
          "environment": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "framework": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "language": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "node": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "origin": {
            "properties": {
              "id": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "runtime": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "target": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "type": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "session": {
        "properties": {
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "sequence": {
            "type": "long"
          }
        }
      },
      "source": {
        "properties": {
          "domain": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "ip": {
            "type": "ip"
          },
          "nat": {
            "properties": {
              "ip": {
                "type": "ip"
              },
              "port": {
                "type": "long"
              }
            }
          },
          "port": {
            "type": "long"
          }
        }
      },
      "span": {
        "properties": {
          "action": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "composite": {
            "properties": {
              "compression_strategy": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "count": {
                "type": "long"
              },
              "sum": {
                "properties": {
                  "us": {
                    "type": "long"
                  }
                }
              }
            }
          },
          "db": {
            "properties": {
              "link": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "rows_affected": {
                "type": "long"
              }
            }
          },
          "destination": {
            "properties": {
              "service": {
                "properties": {
                  "name": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "resource": {
                    "type": "keyword",
                    "ignore_above": 1024
                  },
                  "type": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "duration": {
            "properties": {
              "us": {
                "type": "long"
              }
            }
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "kind": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "links": {
            "properties": {
              "span": {
                "properties": {
                  "id": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              },
              "trace": {
                "properties": {
                  "id": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "message": {
            "properties": {
              "age": {
                "properties": {
                  "ms": {
                    "type": "long"
                  }
                }
              },
              "queue": {
                "properties": {
                  "name": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "subtype": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "sync": {
            "type": "boolean"
          },
          "type": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "timestamp": {
        "properties": {
          "us": {
            "type": "long"
          }
        }
      },
      "trace": {
        "properties": {
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "transaction": {
        "properties": {
          "duration": {
            "properties": {
              "us": {
                "type": "long"
              }
            }
          },
          "experience": {
            "properties": {
              "cls": {
                "type": "scaled_float",
                "scaling_factor": 1000
              },
              "fid": {
                "type": "scaled_float",
                "scaling_factor": 1000
              },
              "longtask": {
                "properties": {
                  "count": {
                    "type": "long"
                  },
                  "max": {
                    "type": "scaled_float",
                    "scaling_factor": 1000
                  },
                  "sum": {
                    "type": "scaled_float",
                    "scaling_factor": 1000
                  }
                }
              },
              "tbt": {
                "type": "scaled_float",
                "scaling_factor": 1000
              }
            }
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "marks": {
            "type": "object",
            "dynamic": "true"
          },
          "message": {
            "properties": {
              "age": {
                "properties": {
                  "ms": {
                    "type": "long"
                  }
                }
              },
              "queue": {
                "properties": {
                  "name": {
                    "type": "keyword",
                    "ignore_above": 1024
                  }
                }
              }
            }
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024,
            "fields": {
              "text": {
                "type": "text"
              }
            }
          },
          "result": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "sampled": {
            "type": "boolean"
          },
          "span_count": {
            "properties": {
              "dropped": {
                "type": "long"
              }
            }
          },
          "type": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "url": {
        "properties": {
          "domain": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "fragment": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "full": {
            "type": "wildcard",
            "ignore_above": 1024,
            "fields": {
              "text": {
                "type": "match_only_text"
              }
            }
          },
          "original": {
            "type": "wildcard",
            "ignore_above": 1024,
            "fields": {
              "text": {
                "type": "match_only_text"
              }
            }
          },
          "path": {
            "type": "wildcard",
            "ignore_above": 1024
          },
          "port": {
            "type": "long"
          },
          "query": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "scheme": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      },
      "user": {
        "properties": {
          "domain": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "email": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024,
            "fields": {
              "text": {
                "type": "match_only_text"
              }
            }
          }
        }
      },
      "user_agent": {
        "properties": {
          "device": {
            "properties": {
              "name": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "name": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "original": {
            "type": "keyword",
            "ignore_above": 1024,
            "fields": {
              "text": {
                "type": "match_only_text"
              }
            }
          },
          "os": {
            "properties": {
              "family": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "full": {
                "type": "keyword",
                "ignore_above": 1024,
                "fields": {
                  "text": {
                    "type": "match_only_text"
                  }
                }
              },
              "kernel": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "name": {
                "type": "keyword",
                "ignore_above": 1024,
                "fields": {
                  "text": {
                    "type": "match_only_text"
                  }
                }
              },
              "platform": {
                "type": "keyword",
                "ignore_above": 1024
              },
              "version": {
                "type": "keyword",
                "ignore_above": 1024
              }
            }
          },
          "version": {
            "type": "keyword",
            "ignore_above": 1024
          }
        }
      }
    }
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by kkrik-es**
This PR uses option `store_array_source` for objects to track the source of (sub)object arrays in synthetic mode. This allows preserving the original source, as synthetic mode merges, deduplicates and sorts array entries by default. The downside is that the whole object array (including children objects and fields) gets stored twice, while there's additional overhead while synthesizing source at query time.

This functionality will be experimental initially, to get some experience before documenting and opening up its use.

Fixes #90708

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 1]
```diff
@@ -585,8 +586,27 @@ private static boolean parsesArrayValue(Mapper mapper) {
         return mapper instanceof FieldMapper && ((FieldMapper) mapper).parsesArrayValue();
     }
 
-    private static void parseNonDynamicArray(DocumentParserContext context, final String lastFieldName, String arrayFieldName)
-        throws IOException {
+    private static void parseNonDynamicArray(
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:589]: Maybe also add unit tests to `DocumentParserTests` that test with store array source? Including some tests with multi levels of object array fields and store array source param being enabled on different levels.

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java [hunk 2]
```diff
@@ -74,6 +84,58 @@ static void decodeAndWrite(XContentBuilder b, BytesRef r) throws IOException {
...
+            .withRestApiVersion(parser.getRestApiVersion());
+        return Tuple.tuple(configuration, builder);
+    }
+
+    private static DocumentParserContext cloneDocumentParserContext(
+        DocumentParserContext context,
+        XContentParserConfiguration configuration,
+        XContentBuilder builder
+    ) throws IOException {
+        DocumentParserContext subcontext = context.switchParser(
```
[the remark this answers is not in the document]
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:131]: Done.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 1 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:589]: I added tests in `IgnoredSourceFieldMapperTests`, along with the rest of the tests for extended synthetic source. Any suggestions for scenarios to cover?

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java [hunk 3]
```diff
@@ -117,6 +117,7 @@ public int get() {
     private final SeqNoFieldMapper.SequenceIDFields seqID;
     private final Set<String> fieldsAppliedFromTemplates;
     private final Set<String> copyToFields;
+    private boolean sourceStored = false;
```
Comment (lkts) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:120]: For my understanding - this means "source is already stored at a higher level of object hierarchy"?

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 4]
```diff
@@ -839,19 +844,30 @@ public void write(XContentBuilder b) throws IOException {
...
+                    // Check if the field source is stored separately, to avoid double-printing.
+                    if (field.hasValue() && storedFields.contains(field.fieldName()) == false) {
+                        field.write(b);
+                    }
                 }
-            }
-            hasValue = false;
-            if (ignoredValues != null) {
                 for (IgnoredSourceFieldMapper.NameValue ignored : ignoredValues) {
                     b.field(ignored.getFieldName());
```
Comment (lkts) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:859]: I didn't think about this before - doesn't this break the alphabetic sorting of fields in the source? We say in documentation that it is sorted.

**Review by lkts — COMMENTED** [review]
Should we add documentation for new parameter?

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 3 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:120]: Right, _ignored_source should no longer be used for this parse subcontext.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 4 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:859]: This is a good point. I'll work on a follow-up PR to restore ordering.

**Comment by kkrik-es** [comment]
> Should we add documentation for new parameter?

I was thinking of keeping it experimental initially, until Observability provides feedback on its use. @felixbarny fyi.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 4 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: Well, I gave it a try here. While it's easy to order fields at the object level, we don't do so for the contents of the object array that get stored and retrieved verbatim. I added tests for this, not sure if there's an easy way to fix this..

**Review by lkts — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 4 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: I think that's exactly what we need, we only specify ordering of fields.

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:131]: Looking at the concerns we had with switchParser, i think your assessment is right. Also, its javadocs says

>  we are actively deprecating and removing the ability to pass complex objects to multifields, so try and avoid using this method

Given that this was committed 4 years ago, the "actively" part no longer holds true. I reviewed the current usages of switchParser and they seem ok to me. I have a slight concern that we are now using the method in a general utility method, that may spread its usage instead of limiting it to the only places where it's strictly needed. I am not sure what to do about that though, and I am ok with the current plan. Thanks for raising this.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:589]: I missed that the tests in `IgnoredSourceFieldMapperTests` also invoke this method. The tests `IgnoredSourceFieldMapperTests` look good to me.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java [hunk 5]
```diff
@@ -260,7 +265,10 @@ public final Collection<String> getIgnoredFields() {
      * Add the given ignored values to the corresponding list.
      */
     public final void addIgnoredField(IgnoredSourceFieldMapper.NameValue values) {
-        ignoredFieldValues.add(values);
+        if (sourceStored == false) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:268]: I wonder whether this if check needed here? This is also checked in `parseNonDynamicArray(...)` and so this should always be false?

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 3 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:124]: Maybe rename this to `clonedSource`? Since this is set to true when invoking `cloneDocumentParserContext(...)` method?

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java [hunk 6]
```diff
@@ -74,6 +84,58 @@ static void decodeAndWrite(XContentBuilder b, BytesRef r) throws IOException {
         }
     }
 
+    /**
+     * Stores the current parser structure (subtree) to an {@link XContentBuilder} and returns it, along with a
+     * {@link DocumentParserContext} wrapping it that can be used to reparse the subtree.
+     * The parser of the original context is also advanced to the end of the current structure (subtree) as a side effect.
+     */
+    static Tuple<DocumentParserContext, XContentBuilder> cloneSubContext(DocumentParserContext context) throws IOException {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:92]: Maybe these methods instead of returning a tuple should return a record? I think `getParserContext()` or `getBuilder()` reads easier than `v1()` and `v2()`?

**Review by martijnvg — COMMENTED** [review]
Left a few more questions and comments.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 5 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:268]: There may be other reasons where we try to store a subfield, e.g. a disabled object. Double-storing is redundant, though it has no side effects.

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java [hunk 7]
```diff
@@ -74,6 +84,58 @@ static void decodeAndWrite(XContentBuilder b, BytesRef r) throws IOException {
...
+        var tuple = cloneSubContextParserConfiguration(context);
+        return Tuple.tuple(cloneDocumentParserContext(context, tuple.v1(), tuple.v2()), tuple.v2());
+    }
+
+    /**
+     * Initializes a {@link XContentParser} with the current parser structure (subtree) and returns it, along with a
+     * {@link DocumentParserContext} wrapping the subtree that can be used to reparse it.
+     * The parser of the original context is also advanced to the end of the current structure (subtree) as a side effect.
+     */
+    static Tuple<DocumentParserContext, XContentParser> cloneSubContextWithParser(DocumentParserContext context) throws IOException {
```
[the remark this answers is not in the document]
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:102]: @lkts will be using it in his PR.

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java (hunk 6 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:92]: Since we just need to wrap a couple of objects and there are no methods, I'd think a tuple is a good match here.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 3 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:124]: We do store the source in `_ignored_source` though, no? The point here is to relay that we shouldn't be writing to `_ignored_source` anything for the current parsing context, since it's already covered.

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java (hunk 6 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:92]: Then this is just me :)

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 5 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:268]: Gotcha, this makes sense to me now.

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:102]: I see, then let's leave it here.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 3 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:124]: Maybe we can see that as a side effect of the cloning of a `DocumentParserContext`?

File: server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java (hunk 6 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/XContentDataHelper.java:92]: I did change the call sites to skip using `var`, it's should be more readable now.

**Review by martijnvg — APPROVED** [review]
LGTM 👍

**Comment by felixbarny** [comment]
The `store_array_source` flag looks good to me, I've pinged the team to test it and provide feedback.
