### PR TITLE
Batch process node left and node failure

### LINKED ISSUE #19282: Node failures are not batch processed by the master
Currently when nodes fail we go through the failures one by one, each resulting in a cluster state publish. This can cause an issue on large clusters that lose a significant number of nodes. 

@bleskes

### PR DESCRIPTION
**Pull request by jasontedor**
Today when a node is removed the cluster (it leaves or it fails), we
submit a cluster state update task. These cluster state update tasks are
processed serially on the master. When nodes are removed en masse (e.g.,
a rack is taken down or otherwise becomes unavailable), the master will
be slow to process these failures because of the resulting reroutes and
publishing of each subsequent cluster state. We improve this in this
commit by processing the node removals using the cluster state update
task batch processing framework.

Closes #19282

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java [hunk 1]
```diff
@@ -97,6 +97,24 @@ public static boolean isIngestNode(Settings settings) {
...
+     * version. it corresponds to the minimum version this elasticsearch version can communicate with. If a higher version is used
+     * the node might not be able to communicate with the remove node. After initial handshakes node versions will be discovered
+     * and updated.
+     * </p>
+     *
+     * @param id               the nodes unique (persistent) node id. This constructor will auto generate a random ephemeral id.
+     * @param address          the nodes transport address
+     * @param version          the version of the node
+     */
+    public DiscoveryNode(final String id, TransportAddress address, Version version) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java]: can you remove this overloaded constructor? We already have too many of them. AFAICS this new one is only used in one place (in a test), where we can easily just provide the 2 extra arguments.

File: core/src/main/java/org/elasticsearch/cluster/service/DuplicateClusterStateUpdateTaskException.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+ * under the License.
+ */
+
+package org.elasticsearch.cluster.service;
+
+/**
+ * An exception thrown is a cluster state update task is submitted for an executor and that task
+ * already exists in the executor's task queue.
+ */
+public class DuplicateClusterStateUpdateTaskException extends IllegalArgumentException {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/service/DuplicateClusterStateUpdateTaskException.java]: This exception (if it goes through Transport) is handled as an IllegalArgumentException (and recreated as IllegalArgumentException upon deserialization). I agree that this exception is probably meant to be handled directly by the caller of submitStateUpdateTask. I wonder if we should add a note about this though.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 3]
```diff
@@ -35,6 +38,7 @@
 import org.elasticsearch.cluster.routing.allocation.AllocationService;
 import org.elasticsearch.cluster.routing.allocation.RoutingAllocation;
 import org.elasticsearch.cluster.service.ClusterService;
+import org.elasticsearch.cluster.service.DuplicateClusterStateUpdateTaskException;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: The exception is not really used in this class? So far it's only used in the tests? If it's only used by the test then I would prefer we just match on the message of the IllegalArgumentException and not introduce this exception.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 4]
```diff
@@ -500,43 +504,116 @@ private boolean joinElectedMaster(DiscoveryNode masterNode) {
...
+            if (!electMasterService.hasEnoughMasterNodes(remainingNodesClusterState.nodes())) {
+                return resultBuilder.build(rejoin.apply(remainingNodesClusterState, "not enough master nodes"));
+            } else {
+                final RoutingAllocation.Result routingResult = allocationService.reroute(remainingNodesClusterState, describeTasks(tasks));
+                return resultBuilder.build(ClusterState.builder(remainingNodesClusterState).routingResult(routingResult).build());
+            }
+        }
+
+        // visible for testing
+        ClusterState remainingNodesClusterState(final ClusterState currentState, DiscoveryNodes.Builder remainingNodesBuilder) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: can you make the method protected and change the comment above that the method is there because we want to override it in tests?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 5]
```diff
@@ -500,43 +504,116 @@ private boolean joinElectedMaster(DiscoveryNode masterNode) {
...
+        }
+
+        @Override
+        public void onFailure(final String source, final Exception e) {
+            logger.error("unexpected failure during [{}]", e, source);
+        }
+
+        @Override
+        public String describeTasks(List<Task> tasks) {
+            return tasks.stream().map(Task::toString).collect(Collectors.joining(", "));
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I'm probably missing something here but how is this different from the default implementation?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 6]
```diff
@@ -500,43 +504,116 @@ private boolean joinElectedMaster(DiscoveryNode masterNode) {
...
-                    }
-                    // eagerly run reroute to remove dead nodes from routing table
-                    RoutingAllocation.Result routingResult = allocationService.reroute(ClusterState.builder(currentState).build(),
-                            "[" + node + "] left");
-                    return ClusterState.builder(currentState).routingResult(routingResult).build();
-                }
-
-                @Override
-                public void onNoLongerMaster(String source) {
-                    // ignoring (already logged)
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: why didn't you add this to `NodeRemovalClusterStateTaskExecutor`?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 7]
```diff
@@ -500,43 +504,116 @@ private boolean joinElectedMaster(DiscoveryNode masterNode) {
...
-                }
-
-                @Override
-                public void onFailure(String source, Exception e) {
-                    logger.error("unexpected failure during [{}]", e, source);
-                }
-            });
+            removeNode(node, "zen-disco-node-left", "left");
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: If I see this correctly, the source still appears in pending cluster state tasks, which is why it should still contain the node name, i.e. `"zen-disco-node-left(" + node + ")"`

File: core/src/test/java/org/elasticsearch/discovery/zen/NodeRemovalClusterStateTaskExecutorTests.java [hunk 8]
```diff
@@ -0,0 +1,185 @@
...
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.verify;
+import static org.mockito.Mockito.verifyNoMoreInteractions;
+import static org.mockito.Mockito.when;
+
+public class NodeRemovalClusterStateTaskExecutorTests extends ESTestCase {
+
+    public void testRemovingNonExistentNodes() throws Exception {
+        final ZenDiscovery.NodeRemovalClusterStateTaskExecutor executor =
+                new ZenDiscovery.NodeRemovalClusterStateTaskExecutor(null, null, null, mock(ESLogger.class));
```
Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/discovery/zen/NodeRemovalClusterStateTaskExecutorTests.java]: why mock the logger here? The test logger could reveal interesting information when debugging a failing test.

**Comment by ywelsch** [comment]
@jasontedor I've left some comments / questions. I would prefer that we remove the `DuplicateClusterStateUpdateTaskException` change from this PR. At the moment it's not used by the node batching here and I don't think we should add it as long as we don't have an actual use for it (I also think that there might be another solution for this, but that's another discussion - let's not have it on this PR).

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 4 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Why? Package-private is more restrictive than protected?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 3 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I pushed cf41ff445d15b3f1fc4a4a38a1acd996b1e5e662. I think that it should be an `IllegalStateException` though.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Sure, this is leftover that I should have removed. Initially, the `DiscoveryNode` was used as the task and a node leaving could lead to duplicate submissions and thus a special exception was needed (catching `IllegalArgumentException` here would have been way too broad).

I think that it should be an `IllegalStateException` though. I pushed I pushed cf41ff445d15b3f1fc4a4a38a1acd996b1e5e662.

File: core/src/main/java/org/elasticsearch/cluster/service/DuplicateClusterStateUpdateTaskException.java (hunk 2 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/service/DuplicateClusterStateUpdateTaskException.java]: The lack of serialization was a deliberate choice but it's moot now.

File: core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java]: There have been many times that I've wanted this constructor and this time I've finally added it (the verbosity of any of the other constructors just gets in the way when writing tests since we often passing empty for the attributes and roles). I'm happy to move it to a convenience method in the test sources, but I would prefer to keep it.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 5 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Leftover from an initial implementation that was different, removed in cf41ff445d15b3f1fc4a4a38a1acd996b1e5e662.

File: core/src/test/java/org/elasticsearch/discovery/zen/NodeRemovalClusterStateTaskExecutorTests.java (hunk 8 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/discovery/zen/NodeRemovalClusterStateTaskExecutorTests.java]: Silliness. Removed in 65a0c66730239d4193c7c058828025ff9b898fd0.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 7 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I pushed 2dcc963509e8454776a1e2339b2f91d6daa79a00.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 6 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: It's an implementation detail that the no longer master already (and it's only logged at the debug level there anyway). Here, we log at the error level (since the default implementation of `onNoLongerMaster` just invokes `onFailure` so I think that we should not be overriding as was the case before.

**Comment by jasontedor** [comment]
@ywelsch Thanks for the feedback. I've responded to all of your comments.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 4 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Just to show intent that the method is to be overridden. Or at least the comment above it could convey that. When I looked at the method I wondered why such a trivial implementation would need to be exposed to tests.

File: core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java (hunk 1 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java]: ok, if you feel that strongly about it.

File: core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java [hunk 9]
```diff
@@ -411,7 +411,7 @@ public void submitStateUpdateTask(final String source, final ClusterStateUpdateT
                 List<UpdateTask> existingTasks = updateTasksPerExecutor.computeIfAbsent(executor, k -> new ArrayList<>());
                 for (@SuppressWarnings("unchecked") UpdateTask<T> existing : existingTasks) {
                     if (tasksIdentity.containsKey(existing.task)) {
-                        throw new IllegalArgumentException("task [" + existing.task + "] is already queued");
+                        throw new IllegalStateException("task [" + existing.task + "] with source [" + source + "] is already queued");
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/service/ClusterService.java]: ++ on IllegalStateException

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java [hunk 10]
```diff
@@ -148,6 +149,7 @@
 
     // must initialized in doStart(), when we have the allocationService set
     private volatile NodeJoinController nodeJoinController;
+    private volatile NodeRemovalClusterStateTaskExecutor nodeRemovalExecutor;
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: final, not volatile...

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: It can't be final, it's constructed on zen discovery start because the elect master service isn't available until then.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 6 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I think that the idea behind that was not to log on error level when node was no longer master (as node leave don't matter in that case anymore).

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 10 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: but `electMasterService` is passed to the ZenDiscovery constructor? I don't follow, sorry.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Sorry, I meant the allocation service!

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: right! oh the confusion :D

File: core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java]: My precious.

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 4 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I pushed 0ef53214bc10497383b208b913ca98d2018dbeec. Does that help?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 6 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: Maybe it's not clear what the initial intent was, but I was going off the comment about "already logged"?

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 4 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I would have been happy already if the comment just stated "overridden by tests". No need for all the explanations :-)

File: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java (hunk 6 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: maybe @bleskes can clarify (he wrote these lines)?

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: yeah, my guess is (long ago :)) that the idea was to reduce unneeded noise - this whole node leave business is to prevent ugly messages like "pinging failed to this node" and have a cleaner shutdown experience. So if a node sent the leave request to a master but got it wrong, it's not a big deal. I'm fine with going either way, error or debug but I tend towards the later (debug)

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: that awfully sounds like two voices for debug.... your turn, @jasontedor.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java]: I pushed 21a39678bc37b64624025ab4c2700d3e22b88e55.

**Comment by ywelsch** [comment]
LGTM. Thanks @jasontedor!
