### PR TITLE
Reduce memory usage on Azure repository implementation

### LINKED ISSUE #66385: [CI] AzureBlobStoreRepositoryTests failures
In some cases these tests are failing due to high memory usage.

### PR DESCRIPTION
**Pull request by fcofdez**
This commit moves the upload logic to the repository itself
instead of delegating into the SDK.
Multi-block uploads are done sequentially instead of in parallel
that allows to bound the outstanding memory.
Additionally the number of i/o threads have been reduced to 1,
to reduce the memory overhead.

Closes #66385

### CODE REVIEW

File: plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java [hunk 1]
```diff
@@ -150,7 +150,6 @@ private static ByteBufAllocator createByteBufAllocator() {
         int tinyCacheSize = PooledByteBufAllocator.defaultTinyCacheSize();
         int smallCacheSize = PooledByteBufAllocator.defaultSmallCacheSize();
         int normalCacheSize = PooledByteBufAllocator.defaultNormalCacheSize();
-        boolean useCacheForAllThreads = PooledByteBufAllocator.defaultUseCacheForAllThreads();
 
         return new PooledByteBufAllocator(false,
             nHeapArena,
```
Comment (fcofdez) [inline plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java:155]: I think that we can reduce those too, wdyt @original-brownbear?

Comment (original-brownbear) [reply plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java:155]: Yea, can't we just do `1` maybe when we only use one thread now anyway?

File: plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java [hunk 2]
```diff
@@ -404,12 +403,156 @@ public void writeBlob(String blobName, InputStream inputStream, long blobSize, b
...
+            // 128 elements (that's hardcoded) once it's subscribed (later on, it requests
+            // by 64 elements), that's why we provide 64kb buffers.
+            return Flux.range(0, (int) Math.ceil((double) length / (double) chunkSize))
+                .map(i -> i * chunkSize)
+                .concatMap(pos -> Mono.fromCallable(() -> {
+                    long count = pos + chunkSize > length ? length - pos : chunkSize;
+                    int numOfBytesRead = 0;
+                    int offset = 0;
+                    int len = (int) count;
+                    final byte[] buffer = new byte[len];
```
Comment (original-brownbear) [inline plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java:485]: This still scares me a little. If we only do 64k at a time here, can't we use the Netty memory allocator (or manage  our own set of `byte[]` and recycle them on `doOnComplete` or do we still have no guarantees about flushing at that point?

**Review by original-brownbear — COMMENTED** [review]
Thanks Francisco. I only have one question pretty much. 
That said, I think the move to a single thread and reducing the heap arenas are straight forward in any case. Lets see what we can do about the upload flux. I guess if that turns out to be trickier we could pull the arena and thread count changes to a separate PR so we can reenable tests asap maybe?

File: plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java (hunk 2 above)
Comment (fcofdez) [reply plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java:485]: Sadly we don't have guarantees about flushing at that point

Comment (fcofdez) [reply plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java:485]: I explored a different approach where I was passing an allocator there, and recycling at the end of the request, but in that case you end up holding that memory for the entire duration of the request.

**Review by original-brownbear — APPROVED** [review]
Discussed this on a different channel and it looks like there is no easy way to get rid of the allocations in uploading (SDK does the same thing under the hood as well).

=> LGTM :)
