### PR TITLE
Fix the timestamp field of a data stream to @timestamp

### LINKED ISSUE #58583: Make timestamp field mapping part of data stream definition
Currently when creating a composable index template with a data stream definition, the timestamp field mapping must be defined too:

```
PUT /_index_template/logs_data_stream
{
  "index_patterns": [ "logs*" ],
  "data_stream": {
    "timestamp_field": "@timestamp"
  },
  "template": {
    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        }
      }
    }
  }
}
```

The template is much cleaner to read if the mapping itself for timestamp field mapping
is inlined with the data stream definition:

```
PUT /_index_template/logs_data_stream
{
  "index_patterns": [ "logs*" ],
  "data_stream": {
    "timestamp_field": "@timestamp",
    "timestamp_mapping": {
      "type": "date"
    }
  }
}
```

Also since most of time, just `"type": "date"` will be provided, it makes sense to make this the default:

```
PUT /_index_template/logs_data_stream
{
  "index_patterns": [ "logs*" ],
  "data_stream": {
    "timestamp_field": "@timestamp"
  }
}
```

In the last two example the backing indices created will have the following mapping:

```
{
  "_doc": {
    "properties": {
      "@timestamp": {
        "type": "date"
      }
    }
  }
}
```

The simulate index template api should also include the inserted / generated timestamp field mapping
in the response.

### LINKED ISSUE #58956: Component templates are considered invalid without timestamp_field
**Elasticsearch version** (`bin/elasticsearch --version`):
8.0.0 snapshot
https://storage.googleapis.com/kibana-ci-es-snapshots-daily/8.0.0/archives/20200702-061321_92851b422f0/elasticsearch-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz

```
{
  "name" : "jbuttner-mbp",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "NyhzfY6ATt26icttpHgMMg",
  "version" : {
    "number" : "8.0.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "92851b422f0a341f211008e24fdfe563291c84b9",
    "build_date" : "2020-07-02T06:05:57.277162Z",
    "build_snapshot" : true,
    "lucene_version" : "8.6.0",
    "minimum_wire_compatibility_version" : "7.9.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

OS version (uname -a if on a Unix-like system):
macOS

**Description of the problem including expected versus actual behavior**:
If a template uses a component template to be built, it will be rejected by ES if the component template does not have the `timestamp_field` even if the `_index_template` API request contains the necessary field.

**Steps to reproduce**:

```
POST _component_template/metrics-endpoint.metadata-mappings
{
  "template": {
    "mappings": {
      "dynamic": true
    }
  }
}
PUT _index_template/test1
{
  "priority": 4,
  "index_patterns": [
    "metrics-endpoint.metadata-*"
  ],
  "template": {
    "mappings": {
      "date_detection": false,
      "properties": {
        "@timestamp": {
          "type": "date"
        }
      }
    }
  },
  "data_stream": {
    "timestamp_field": "@timestamp"
  },
  "composed_of": [
    "metrics-endpoint.metadata-mappings"
  ]
}
```
This will fail with the following error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "composable template [test1] template after composition with component templates [metrics-endpoint.metadata-mappings] is invalid"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "composable template [test1] template after composition with component templates [metrics-endpoint.metadata-mappings] is invalid",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "invalid composite mappings for [test1]",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "expected timestamp field [@timestamp], but found no timestamp field"
      }
    }
  },
  "status" : 400
}
```

If we use this component template instead the request will succeed:

```
POST _component_template/metrics-endpoint.metadata-mappings
{
  "template": {
    "mappings": {
      "dynamic": false,
      "properties": {
        "@timestamp": {
          "type": "date"
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by martijnvg**
The commit makes the following changes:
* The timestamp field of a data stream definition in a composable
  index template can only be set to `@timestamp`.
* Removed custom data stream timestamp field validation and reuse the validation from `TimestampFieldMapper` and
  instead only check that the _timestamp field mapping has been defined on a backing index of a data stream.
* Moved code that injects _timestamp meta field mapping from `MetadataCreateIndexService#applyCreateIndexRequestWithV2Template(...)` method
  to `MetadataIndexTemplateService#collectMappings(...)` method.
* Fixed a bug (#58956) that cases timestamp field validation to be performed
  for each template and instead of the final mappings that is created.

Relates to #58642
Relates to #53100
Closes #58956
Closes #58583

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

File: server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java [hunk 1]
```diff
@@ -256,6 +257,10 @@ public String toString() {
         private final String timestampField;
 
         public DataStreamTemplate(String timestampField) {
+            if ("@timestamp".equals(timestampField) == false) {
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java:260]: Can we make this a public static string so it can be referenced elsewhere?

File: server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java [hunk 2]
```diff
@@ -267,6 +272,13 @@ public String getTimestampField() {
             this(in.readString());
         }
 
+        /**
+         * @return a mapping snippet for a backing index with `_timestamp` meta field mapper properly configured.
+         */
+        public Map<String, Object> getDataSteamMappingSnippet() {
+            return Map.of("_doc", Map.of(TimestampFieldMapper.NAME, Map.of("path", timestampField)));
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java:279]: Super minor:

```suggestion
            return Map.of(MapperService.SINGLE_MAPPING_NAME, Map.of(TimestampFieldMapper.NAME, Map.of("path", timestampField)));
```

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java [hunk 3]
```diff
@@ -213,67 +207,37 @@ public int hashCode() {
...
         private final String name;
-        private final Map<String, Object> fieldMapping;
-
-        public TimestampField(String name, Map<String, Object> fieldMapping) {
-            assert fieldMapping.containsKey("type") : "no type defined for mapping of timestamp_field";
-            assert ALLOWED_TIMESTAMPFIELD_TYPES.contains(fieldMapping.get("type")) :
-                "invalid type defined for mapping of timestamp_field";
 
+        public TimestampField(String name) {
+            assert "@timestamp".equals(name) : "unexpected timestamp field [" + name + "]";
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java:224]: I think we should transform this into an actual error, that way if we end up using it for the HLRC it doesn't fail to throw because assertions are disabled

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java [hunk 4]
```diff
@@ -213,67 +207,37 @@ public int hashCode() {
     public static final class TimestampField implements Writeable, ToXContentObject {
 
         static ParseField NAME_FIELD = new ParseField("name");
-        static ParseField FIELD_MAPPING_FIELD = new ParseField("mapping");
 
         @SuppressWarnings("unchecked")
         private static final ConstructingObjectParser<TimestampField, Void> PARSER = new ConstructingObjectParser<>(
             "timestamp_field",
-            args -> new TimestampField((String) args[0], (Map<String, Object>) args[1])
+            args -> new TimestampField((String) args[0])
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java:214]: This makes me wonder, this is fine as-is, but should we even bother having this class or specifying the name of the field if it's going to be hardcoded for the foreseeable future?

**Review by dakrone — APPROVED** [review]
LGTM, thanks Martijn! I left some really minor comments

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java (hunk 3 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java:224]: I think HLRC uses its own `DataStream` pojo. I will change this from an assertion to an actual error.

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java (hunk 4 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java:214]: I prefer to keep this class. I think that that the timestamp field will not stay hard coded for a long time.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 5]
```diff
@@ -902,6 +909,23 @@ public static String findV2Template(Metadata metadata, String indexName, boolean
         Optional.ofNullable(template.template())
             .map(Template::mappings)
             .ifPresent(mappings::add);
+
+        // Only include _timestamp mapping snippet if creating backing index.
+        if (indexName.startsWith(DataStream.BACKING_INDEX_PREFIX)) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:914]: @dakrone I had to add this if statement otherwise the meta field mapper was going to be applied on each create index api call. In a docs test, the new logs-*-* composable index template was triggered by a regular create index api call and then the test failed, because the document being indexed had no timestamp field. 

I think only applying the meta field automatically makes sense for backing indices only and not when a user creates a new index via create index api and the index composable template matches?

See commits: a23d2e484594b5cbe788f3ef4bfcd40f97136f67, which then was superseded by: c78733204c12cf44b53026052aff9865d99ced03

Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:914]: Note currently in master, the `_timestamp` field gets only applied if the create index request originates from create data stream api and data stream rollover (signalled via `CreateIndexClusterStateUpdateRequest#dataStreamName` field), but now this logic moved `MetadataIndexTemplateService.collectMappings(...)` method, which didn't have that context.

File: server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java [hunk 6]
```diff
@@ -267,6 +275,13 @@ public String getTimestampField() {
             this(in.readString());
         }
 
+        /**
+         * @return a mapping snippet for a backing index with `_timestamp` meta field mapper properly configured.
+         */
+        public Map<String, Object> getDataSteamMappingSnippet() {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java:281]: Noticed this typo as I was trying to pull up the method: `DataSteam` -> `DataStream`.

File: server/src/main/java/org/elasticsearch/index/mapper/TimestampFieldMapper.java [hunk 7]
```diff
@@ -196,6 +196,10 @@ public void validate(DocumentFieldMappers lookup) {
         }
     }
 
+    public String getPath() {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/TimestampFieldMapper.java:199]: Does `TimestampFieldMapper` need a `path` parameter now? We're not sure how we will eventually implement custom timestamp names, I can see an implementation where we don't use `path` here at all. So maybe we could simplify and just have an `enabled` boolean flag instead.

Depending on the implementation, we can always add `path` later and just default to `@timestamp` if it's not specified.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java [hunk 8]
```diff
@@ -183,31 +169,16 @@ public static ComposableIndexTemplate lookupTemplateForDataStream(String dataStr
...
-            fieldPath.startsWith(".") ||
-            fieldPath.endsWith(".") : "illegal field path [" + fieldPath + "]";
-
-        String mappingPath;
-        if (fieldPath.indexOf('.') == -1) {
-            mappingPath = "properties." + fieldPath;
-        } else {
-            mappingPath = "properties." + fieldPath.replace(".", ".properties.");
+        if (timestampFieldName.equals(fieldMapper.getPath()) == false) {
+            throw new IllegalArgumentException("[_timestamp] meta field doesn't point to data stream timestamp field [" +
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java:176]: I think this error will be hard for end users to understand, since they shouldn't be aware of the `_timestamp` field. Maybe we won't even need this check, once we remove the ability to set `timestamp_field`, as discussed in https://github.com/elastic/elasticsearch/pull/59317#issuecomment-656236960?

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 9]
```diff
@@ -1047,16 +1071,19 @@ private static void validateCompositeTemplate(final ClusterState state,
                     // shard id and the current timestamp
                     xContentRegistry, tempIndexService.newQueryShardContext(0, null, () -> 0L, null));
 
+                // triggers inclusion of _timestamp field and its validation:
+                String indexName = DataStream.BACKING_INDEX_PREFIX + temporaryIndexName;
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:1075]: Should we only add the `_timestamp` mapping if this template has a data stream block? Otherwise it could just be a normal template that happens to contain a field named `@timestamp`, and we attempt to validate that mapping.

**Review by jtibshirani — COMMENTED** [review]
I left a few late comments!

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java (hunk 5 above)
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:914]: Would it be cleaner to pull this check out of `collectMappings` and into the caller? That way we could avoid the workaround here: https://github.com/elastic/elasticsearch/pull/59076/files#diff-115cd2f0fff9dd97acc95e1d29012a15R1075.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java (hunk 8 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java:176]: This is more of a sanity check. Kind of ensuring that we did apply the `_data_stream_timestamp` meta field mapper. If a user would run into this error then this would be a bug. Can tweak this check.
