### PR TITLE
Fix mvt error when returning partial results

### LINKED ISSUE #98730: _mvt endpoint returns 400 when results are incomplete (shard errors) instead of partial results like _search endpoint
### Elasticsearch Version

main

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

21.6.0 Darwin Kernel Version 21.6.0

### Problem Description

_mvt endpoint returns 400 when results are incomplete (shard errors) instead of partial results like _search endpoint

### Steps to Reproduce

Run commands to set up data
```
PUT local1
{}

PUT local1/_mapping
{
  "properties": {
    "value": {
      "type": "keyword"
    },
    "location": {
      "type": "geo_point"
    }
  }
}

PUT local1/_doc/1
{
    "value" : "foo1",
    "location": [0, 0]
}

PUT local2
{}

PUT local2/_mapping
{
  "properties": {
    "value": {
      "type": "keyword"
    },
    "location": {
      "type": "geo_point"
    }
  }
}

PUT local2/_doc/1
{
    "value" : "foo2",
    "location": [1, 1]
}
```

Run _mvt request
```
POST /local*/_mvt/location/1/1/1
{
  "buffer": 0,
  "grid_precision": 0,
  "exact_bounds": true,
  "extent": 4096,
  "query": {
    "bool": {
      "filter": [
        {
          "error_query": {
            "indices": [
              {
                "error_type": "exception",
                "message": "local shard failure message 123",
                "name": "local2"
              }
            ]
          }
        }
      ],
      "must": [],
      "must_not": [],
      "should": []
    }
  }
}
```

Notice how the response returns 400.
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Unsupported vector tile type for field [_shards.failures.0] : java.util.LinkedHashMap"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Unsupported vector tile type for field [_shards.failures.0] : java.util.LinkedHashMap"
  },
  "status": 400
}
```

The same request to _search endpoint returns partial results. _mvt should mimic this behavior.
```
POST /local*/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "error_query": {
            "indices": [
              {
                "error_type": "exception",
                "message": "local shard failure message 123",
                "name": "local2"
              }
            ]
          }
        }
      ],
      "must": [],
      "must_not": [],
      "should": []
    }
  }
}
```

```
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 2,
    "successful": 1,
    "skipped": 0,
    "failed": 1,
    "failures": [
      {
        "shard": 0,
        "index": "local2",
        "node": "XPQtz28bSLW26Oynf6oUmg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: [local2][0] local shard failure message 123",
          "index_uuid": "sg-JHdyNRUqszXjYiQTBNQ",
          "index": "local2",
          "caused_by": {
            "type": "runtime_exception",
            "reason": "[local2][0] local shard failure message 123"
          }
        }
      }
    ]
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 0,
    "hits": [
      {
        "_index": "local1",
        "_id": "1",
        "_score": 0,
        "_source": {
          "value": "foo1",
          "location": [
            0,
            0
          ]
        }
      }
    ]
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by iverase**
In https://github.com/elastic/elasticsearch/pull/97619, we make stricter the parsing of the query result and we throw an error when we cannot add part of the result to the vector tile. This had an undesirable side effect because the flattened method used to generate tags for the vector tile keeps the original maps. 

This PR adds the logic to be able to ignore map objects when adding properties to the tile

fixes https://github.com/elastic/elasticsearch/issues/98730

### CODE REVIEW

File: x-pack/plugin/vector-tile/src/main/java/org/elasticsearch/xpack/vectortile/rest/VectorTileUtils.java [hunk 1]
```diff
@@ -64,6 +64,10 @@ public static void addPropertyToFeature(VectorTile.Tile.Feature.Builder feature,
             // guard for null values
             return;
         }
+        if (value instanceof Map<?, ?> map) {
+            // maps should have been flattened already in Maps#flatten but still contains the original maps
```
Comment (craigtaverner) [inline x-pack/plugin/vector-tile/src/main/java/org/elasticsearch/xpack/vectortile/rest/VectorTileUtils.java:68]: Maps.flatten does include recursive code for this, so it is surprising it does not happen. Perhaps there is a bug in Maps.flatten.

**Review by craigtaverner — APPROVED** [review]
LGTM, although I wonder why Maps.flatten does not do the job
