### PR TITLE
[TEST] Fix MappingStatsTests failures in RHEL

### LINKED ISSUE #138236: [CI] MappingStatsTests testToXContent failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11566 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/u2m2el2u5h3xa)
- [elasticsearch-periodic-platform-support #11566 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/7pn4w6rxx3xas)
- [elasticsearch-periodic-platform-support #11562 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/gkmlbpgi47wqg)
- [elasticsearch-periodic-platform-support #11562 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/mpznkbigyg77g)
- [elasticsearch-periodic-platform-support #11558 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/2svib7l7mshec)
- [elasticsearch-periodic-platform-support #11558 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/jscth4v2mwhea)
- [elasticsearch-periodic-platform-support #11554 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/xr2gz35xhn5wc)
- [elasticsearch-periodic-platform-support #11554 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/kqcy3757jog6a)
- [elasticsearch-periodic-platform-support #11550 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/vukwg5lhkr5hs)
- [elasticsearch-periodic-platform-support #11550 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/sdaxq4m7rkayw)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.action.admin.cluster.stats.MappingStatsTests.testToXContentWithSomeSharedMappings" -Dtests.seed=C11A0211D12F0EF6 -Dtests.locale=yue-Hans -Dtests.timezone=Africa/Maseru -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.action.admin.cluster.stats.MappingStatsTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testToXContent'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.junit.ComparisonFailure: expected:<...d_mapping_size" : "5[19b",
    "total_deduplicated_mapping_size_in_bytes" : 519],
    "field_types" ...> but was:<...d_mapping_size" : "5[21b",
    "total_deduplicated_mapping_size_in_bytes" : 521],
    "field_types" ...>
```

**Issue Reasons:**
- [main] 12 consecutive failures in step rhel-10_platform-support-unix
- [main] 12 failures in test testToXContent (1.3% fail rate in 892 executions)
- [main] 12 failures in step rhel-10_platform-support-unix (100.0% fail rate in 12 executions)
- [main] 6 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by kkrik-es**
RHEL reports slightly different values for mapping size.

Fixes #138236
Fixes #138729

### CODE REVIEW

**Comment by kkrik-es** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/139881)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

File: server/src/test/java/org/elasticsearch/action/admin/cluster/stats/MappingStatsTests.java [hunk 1]
```diff
@@ -109,6 +109,8 @@ public void testToXContent() {
         Metadata metadata = Metadata.builder().put(meta, false).put(meta2, false).build();
         assertThat(metadata.getProject().getMappingsByHash(), Matchers.aMapWithSize(1));
         MappingStats mappingStats = MappingStats.of(metadata, () -> {});
+        // RHEL reports slighlty higher mapping size - JVM issue?
+        String mappingStatsString = Strings.toString(mappingStats, true, true).replace("261", "260");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/admin/cluster/stats/MappingStatsTests.java:113]: This variable is ignored, the test still asserts against `Strings.toString(mappingStats, true, true)` without the replacement.

**Review by DaveCTurner — COMMENTED** [review]
Probably not a JVM issue so much as a diffference in Zlib versions? Would be nice to actually confirm this tho.

I'd rather we measured the actual sizes with `metadata.getMappingsByHash().values().stream().mapToLong(v -> v.source().compressed().length).sum()` and then verified that this was exactly what the stats reported. That way we're resilient to such variances now and in future.

Also did you intend to merge this without a review? I don't think we should be doing that.

**Comment by kkrik-es** [comment]
> Also did you intend to merge this without a review? I don't think we should be doing that.

This is what happens with auto-backport?

File: server/src/test/java/org/elasticsearch/action/admin/cluster/stats/MappingStatsTests.java (hunk 1 above)
Comment (kkrik-es) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/stats/MappingStatsTests.java:113]: Hm you're right, lemme send a fix for that.

**Comment by DaveCTurner** [comment]
> This is what happens with auto-backport?

No, that's not what this label does. Also it looks like it didn't even get a green CI run before merge.

**Comment by kkrik-es** [comment]
> > This is what happens with auto-backport?
> 
> No, that's not what this label does. 

Sorry, I'm confused. https://github.com/elastic/elasticsearch/pull/139901 was created by `auto-backport` and it's labeled with `auto-merge-without-approval`. This will be submitted without a review, correct? If so, how is it different?

**Comment by DaveCTurner** [comment]
That's correct, `auto-merge-without-approval` auto-merges without waiting for approval and is appropriate for backports of previously-reviewed PRs. But this PR (#139722) is not a backport of a previously-reviewed PR so it should have been reviewed before merge. I don't see any approving reviews here. Maybe I'm missing something?

**Comment by kkrik-es** [comment]
I see, this was the original PR. Point taken, this is correct.
