### PR TITLE
Don't ignore empty index template that have no template definition.

### LINKED ISSUE #98834: Handle index template with no template defined correctly
A composable index template with no `template` defined in the body is mistakingly always assumed to not be a time series template. Even if it refers to a component template that has the `index.mode` setting set to `time_series` and the component template defines mappings with dimension fields or routing paths.

Incorrectly this causes to create a data stream with a tsdb index *without* time series start and end time settings set. The fact that this can happen is another bug and is being tracked #98833.

What should happen in this case is that a tsdb data stream is created with a valid tsdb backing index (with correctly generated time series start and end time settings).

This bug was found as part investigating #98792 and is the cause of that bug.

### PR DESCRIPTION
**Pull request by martijnvg**
A composable index template with no template defined in the body is mistakingly always assumed to not be a time series template. Even if it refers to a component template that has the `index.mode` setting set to `time_series` and the component template defines mappings with dimension fields or routing paths.

Closes #98834

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java [hunk 1]
```diff
@@ -2240,6 +2241,40 @@ public void testEnsureMetadataFieldCheckedForGlobalStateChanges() {
...
+                null,
+                null,
+                new ComposableIndexTemplate.DataStreamTemplate()
+            );
+            Metadata m = Metadata.builder().put("component_template_1", componentTemplate).put("index_template_1", indexTemplate).build();
+            assertThat(m.isTimeSeriesTemplate(indexTemplate), is(true));
+        }
+        // Settings in composable index template:
+        {
+            var componentTemplate = new ComponentTemplate(new Template(null, null, null), null, null);
```
Comment (salvatore-campagna) [inline server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:2263]: From the code it looks to me the template (as a whole object) is expected to be not null even if it is not enforced with something like `Objects.requireNotNull(...)`, for instance in the `ComponentTemplate` constructor, while a template with all null fields is allowed. Should we require that the template in ComponentTemplate is not null using an `Objects.requireNotNull(...)`?

**Comment by salvatore-campagna** [comment]
I left two comments but I think the rest is ok...we just prevent early exit if template is null.

**Review by salvatore-campagna — APPROVED** [review]

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/TsdbDataStreamRestIT.java [hunk 2]
```diff
@@ -223,6 +223,94 @@ public void testTsdbDataStreamsNanos() throws Exception {
...
+                        "index": {
+                            "mode": "time_series",
+                            "routing_path": ["metricset", "k8s.pod.uid"]
+                        }
+                    },
+                    "mappings":{
+                        "dynamic_templates": [
+                            {
+                                "labels": {
+                                    "path_match": "pod.labels.*",
```
[the remark this answers is not in the document]
Comment (martijnvg) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/TsdbDataStreamRestIT.java:241]: I just copied the template part from the index template at the top of this source file.
I think it is based on mapping used in tsdb Rally track.

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java (hunk 1 above)
Comment (martijnvg) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:2263]: > Should we require that the template in ComponentTemplate is not null using an Objects.requireNotNull(...)?

👍

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/TsdbDataStreamRestIT.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (martijnvg) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/TsdbDataStreamRestIT.java:241]: I will remove the dynamic mapping here. No data gets actually indexed in this test.

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java (hunk 1 above)
Comment (martijnvg) [reply server/src/test/java/org/elasticsearch/cluster/metadata/MetadataTests.java:2263]: I will  change this in another PR. It could require changes in other places as well.

**Comment by martijnvg** [comment]
Unrelated failure: #98863

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/part-2
