### PR TITLE
[logstash-bridge] Introduce GeoIp interfaces

### LINKED ISSUE #334: [Move to ES bridge -> ES scope] Introduce Bridge and proxies for GeoIP
## Description
Currently, plugin GeoIP package (`co.elastic.logstash.filters.elasticintegration.geoip`) doesn't have Bridge APIs associated. We need to 
- include geoip ingest module to logstash-bridge (somehow commented compileOnly project(':modules:ingest-geoip'))
- introduce Wrappers for GeoIP classes used by the plugin

### LINKED ISSUE #335: [Move to ES bridge -> ES scope] Introduce wrappers for missed interfaces and close the gap
### Description
Based on #331 investigation outcome, introduce/modify the wrappers to properly utilize them by the plugin.

Beside the GeoIP changes, plugin has following class/interface usages need to be moved to the bridge:
- org.elasticsearch.action.support.RefCountingRunnable;
- org.elasticsearch.ingest.common.FailProcessorException;
- org.elasticsearch.core.Releasable;

### PR DESCRIPTION
**Pull request by mashhurs**
### What this PR does?
It introduces GeoIP bridge interfaces where Logstash `elastic_integration` plugin can utilize.

- [x] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- [x] Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- [x] If submitting code, have you built your formula locally prior to submission with `gradle check`?
- [x] If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- [x] If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- [x] If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

File: modules/ingest-geoip/src/main/java/module-info.java [hunk 1]
```diff
@@ -19,5 +19,5 @@
     exports org.elasticsearch.ingest.geoip.direct to org.elasticsearch.server;
     exports org.elasticsearch.ingest.geoip.stats to org.elasticsearch.server;
 
-    exports org.elasticsearch.ingest.geoip to com.maxmind.db;
+    exports org.elasticsearch.ingest.geoip to com.maxmind.db, org.elasticsearch.logstashbridge;
```
Comment (yaauie) [inline modules/ingest-geoip/src/main/java/module-info.java]: I can understand that this needs to export to `org.elasticsearch.logstashbridge`, but am unsure why it needs to export _to_ `com.maxmind.db`, which I believe to be a dependency _of_ this module (not dependent _on_ this module).

I'm okay paring this off as a separate thing to chase down.

**Review by yaauie — APPROVED** [review]
While there's a lot going on here, I'm pretty confident in the general shape and the downstream project is passing CI when pointed at these changes.

 - all bridges are interfaces, and provide factory methods to create instances from bridged inputs, making the `ProxyInternal`-ish classes locked-down implementation details of this bridge that are _not_ exposed to consumers of the bridge.
 - we provide `AbstractExternal`...`Bridge` base classes for implementing bridged interfaces externally _without_ needing to know about Elasticsearch-internal types.

**Comment by yaauie** [comment]
> ## 1 failing check
>
> Check labels — Missing: [:Team]

While we're tagged `Team:Logstash`, the failing check is looking for a tag that begins with a `:` (the ES short-hand for team ownership)

File: modules/ingest-geoip/src/main/java/module-info.java (hunk 1 above)
Comment (mashhurs) [reply modules/ingest-geoip/src/main/java/module-info.java]: Oops! Your assumption is correct and I believe we should remove this. I will do it now as I don't see any harmful side affects to our changes.
