### PR TITLE
Speed up converting of temporal accessor to zoned date time

### LINKED ISSUE #37826: Drop in indexing performance and increase in agg latency after mappings/aggs switch to java time in #36363
#36363 (merged to master in https://github.com/elastic/elasticsearch/commit/daa2ec8a605d385a65b9ab3e89d016b3fd0dffe2) has caused a performance drop manifested in both a drop in indexing throughput (see: https://elasticsearch-benchmarks.elastic.co/#tracks/nyc-taxis/nightly/30d for `http_logs` / `nyc_taxis` / `nested` / `noaa`) as well as latency increase in aggs (see: `nyc_taxis`, `nested`, `http_logs`) and `gc` (`nested`) on 2018-01-23.

- Before: `nyc_taxis` median indexing throughput: 81421 docs/s 
- After: `nyc_taxis` median indexing throughput: 65981 docs/s

### Reproduction steps:

Java time commit `daa2ec8`:

```
esrally --pipeline="from-sources-complete" --track="nyc_taxis" --car="4gheap" --runtime-jdk=8 --challenge="append-no-conflicts" --revision="daa2ec8" --include-tasks="delete-index,create-index,check-cluster-health,index,refresh-after-index"
```

Previous commit `7b3dd30`:

```
esrally --pipeline="from-sources-complete" --track="nyc_taxis" --car="4gheap" --runtime-jdk=8 --challenge="append-no-conflicts" --revision="7b3dd30" --include-tasks="delete-index,create-index,check-cluster-health,index,refresh-after-index"
```

Note: If you are using Oracle JDK you can also get a profile by specifying `--telemetry=jfr`.

### PR DESCRIPTION
**Pull request by spinscale**
The existing implementation was slow due to exceptions being thrown if
an accessor did not have a time zone. This implementation queries for
having a timezone, local time and local date and also checks for an
instant preventing to throw an exception and thus speeding up the conversion.

This removes the existing method and create a new one named
DateFormatters.from(TemporalAccessor accessor) to resemble the naming of
the java time ones.

Before this change an epoch millis parser using the toZonedDateTime
method took

DateFormatterToZonedTimeBenchmark.benchmarkToZonedDateTime  avgt   30  3970,202 ± 71,260  ns/op

With this change

DateFormatterToZonedTimeBenchmark.benchmarkToZonedDateTime  avgt   30  67,863 ± 1,162  ns/op

Closes #37826

### CODE REVIEW

**Comment by spinscale** [comment]
@elasticmachine retest elasticsearch-ci/default-distro

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java [hunk 1]
```diff
@@ -662,7 +662,8 @@ private void assertSameDate(String input, String format, DateFormatter jodaForma
         DateTime jodaDateTime = jodaFormatter.parseJoda(input);
 
         TemporalAccessor javaTimeAccessor = javaFormatter.parse(input);
-        ZonedDateTime zonedDateTime = DateFormatters.toZonedDateTime(javaTimeAccessor);
+//        ZonedDateTime zonedDateTime = DateFormatters.toZonedDateTime(javaTimeAccessor);
```
Comment (danielmitterdorfer) [inline server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: Leftover?

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java [hunk 2]
```diff
@@ -80,20 +93,33 @@ private long parseMillis(String date) {
...
-                    .withZone(DateUtils.dateTimeZoneToZoneId(timezone));
+                    .withZone(zoneId);
                 return text -> {
-                    ZonedDateTime defaultZonedDateTime = Instant.EPOCH.atZone(ZoneOffset.UTC).withYear(year);
                     TemporalAccessor accessor = formatter.parse(text);
-                    long millis = DateFormatters.toZonedDateTime(accessor, defaultZonedDateTime).toInstant().toEpochMilli();
+                    // if there is no year, we fall back to the current one and
+                    // fill the rest of the date up with the parsed date
+                    if (accessor.isSupported(ChronoField.YEAR) == false) {
+                        ZonedDateTime newTime = Instant.EPOCH.atZone(ZoneOffset.UTC).withYear(year);
```
Comment (danielmitterdorfer) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java]: Shouldn't we use the "current" year in the specified time zone instead of UTC? Wouldn't we otherwise either use the next or the previous year around the turn of the year?

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java [hunk 3]
```diff
@@ -1544,105 +1552,82 @@ static JavaDateFormatter merge(String pattern, List<DateFormatter> formatters) {
...
+     * - If an iso based weekyear is found, but not week is specified, the first monday
+     *   of the new year is chosen (reataining BWC to joda time)
+     * - If an iso based weekyear is found and an iso based weekyear week, the start
+     *   of the day is used
+     *
+     * @param accessor The accessor returned from a parser
+     *
+     * @return The converted zoned date time
+     */
+    @SuppressForbidden(reason = "LocalDate.of is fine here")
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: I wonder whether we should extract the access to `LocalDate#of` to a dedicated method so we can reduce the scope of the `SuppressForbidden` annotation.

**Review by danielmitterdorfer — COMMENTED** [review]
I left a few comments.

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java (hunk 2 above)
Comment (spinscale) [reply modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateFormat.java]: I resembled the joda time behaviour here. I also created a test that compares joda time with java time to make sure the output is the same

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java (hunk 1 above)
Comment (spinscale) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: yes, removed

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java (hunk 3 above)
Comment (spinscale) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: totally. done.

**Review by danielmitterdorfer — APPROVED** [review]
Thanks for iterating. LGTM.

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java [hunk 4]
```diff
@@ -1544,105 +1552,86 @@ static JavaDateFormatter merge(String pattern, List<DateFormatter> formatters) {
             dateTimeFormatters.toArray(new DateTimeFormatter[0]));
     }
 
-    private static final ZonedDateTime EPOCH_ZONED_DATE_TIME = Instant.EPOCH.atZone(ZoneOffset.UTC);
+    private static final LocalDate LOCALDATE_EPOCH = LocalDate.of(1970, 1, 1);
```
Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: there is an annotation below `    @SuppressForbidden(reason = "LocalDate.of is fine here")`
Why is it forbidden ? Should be also then applied here?

Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: there is an annotation below @SuppressForbidden(reason = "LocalDate.of is fine here")
Why is it forbidden ? Should be also then applied here?
i suppose that maybe this was already discussed [comment](https://github.com/elastic/elasticsearch/pull/37915#discussion_r251743419)

**Review by pgomulka — APPROVED** [review]
LGTM - I really like this change. I only left one comment which I supposed you already spotted with Daniel
