### PR TITLE
[Transform] Set runtime mappings on search request in LatestContinuousIT

### LINKED ISSUE #68394: [CI] TransformContinuousIT.testContinousEvents fails
**Build scan**:
https://gradle-enterprise.elastic.co/s/55hcl2h5lzcvu

**Repro line**:

```
./gradlew ':x-pack:plugin:transform:qa:multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" -Dtests.seed=99F2CC3E4300F517 -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Asia/Dubai -Druntime.java=11
```

**Reproduces locally?**:
yes

**Applicable branches**:
master

**Failure history**:

**Failure excerpt**:
```

[2021-02-02T19:11:41,116][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] before test |  
-- | --
  | [2021-02-02T19:11:41,118][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] initializing REST clients against [http://[::1]:39769, http://127.0.0.1:41881, http://[::1]:45157, http://127.0.0.1:39787, http://[::1]:45989, http://127.0.0.1:43133] |  
  | [2021-02-02T19:11:41,144][WARN ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] Skipping test case: [continuous-histogram-pivot-test], because it is disabled, see [https://github.com/elastic/elasticsearch/issues/67887] |  
  | [2021-02-02T19:11:41,197][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putPipeline: {"processors":[{"set":{"field":"run_ingest","value":0}}]} |  
  | [2021-02-02T19:11:41,273][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] Creating source index with: {"settings":{"index":{"number_of_shards":4}},"mappings":{"properties":{"timestamp":{"type":"date"},"event":{"type":"keyword"},"metric":{"type":"integer"},"location":{"type":"geo_point"},"run":{"type":"integer"},"metric-timestamp":{"type":"date"},"some-timestamp":{"type":"date"}},"runtime":{"metric-rt-2x":{"type":"long","script":{"source":"if (params._source.metric != null) {emit(params._source.metric * 2)}"}},"event-upper":{"type":"keyword","script":{"source":"if (params._source.event != null) {emit(params._source.event.toUpperCase())}"}},"timestamp-at-runtime":{"type":"date","script":{"source":"emit(parse(params._source.get('timestamp')))"}},"metric-timestamp-5m-earlier":{"type":"date","script":{"source":"if (doc['metric-timestamp'].size()!=0) {emit(doc['metric-timestamp'].value.minus(5, ChronoUnit.MINUTES).toInstant().toEpochMilli())}"}},"some-timestamp-10m-earlier":{"type":"date","script":{"source":"if (doc['some-timestamp'].size()!=0) {emit(doc['some-timestamp'].value.minus(10, ChronoUnit.MINUTES).toInstant().toEpochMilli())}"}},"metric":{"type":"long"}}}} |  
  | [2021-02-02T19:11:41,725][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putTransform: {"id":"continuous-terms-pivot-test","source":{"index":["test-transform-continuous-events"]},"dest":{"index":"continuous-terms-pivot-test","pipeline":"transform-ingest"},"frequency":"1s","sync":{"time":{"field":"timestamp","delay":"1s"}},"pivot":{"group_by":{"event":{"terms":{"field":"event"}}},"aggregations":{"run.max":{"max":{"field":"run"}},"count":{"value_count":{"field":"run"}},"time.max":{"max":{"field":"timestamp"}},"metric.avg":{"avg":{"field":"metric-rt-2x"}}}},"settings":{"max_page_search_size":10}} |  
  | [2021-02-02T19:11:42,034][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putTransform: {"id":"continuous-terms-on-date-pivot-test","source":{"index":["test-transform-continuous-events"]},"dest":{"index":"continuous-terms-on-date-pivot-test","pipeline":"transform-ingest"},"frequency":"1s","sync":{"time":{"field":"timestamp","delay":"1s"}},"pivot":{"group_by":{"some-timestamp":{"terms":{"field":"some-timestamp","missing_bucket":true}}},"aggregations":{"run.max":{"max":{"field":"run"}},"count":{"value_count":{"field":"run"}},"time.max":{"max":{"field":"timestamp"}},"metric.avg":{"avg":{"field":"metric-rt-2x"}}}},"settings":{"max_page_search_size":10}} |  
  | [2021-02-02T19:11:42,109][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putTransform: {"id":"continuous-date-histogram-pivot-test","source":{"index":["test-transform-continuous-events"]},"dest":{"index":"continuous-date-histogram-pivot-test","pipeline":"transform-ingest"},"frequency":"1s","sync":{"time":{"field":"timestamp","delay":"1s"}},"pivot":{"group_by":{"second":{"date_histogram":{"field":"timestamp","missing_bucket":true,"fixed_interval":"1s"}}},"aggregations":{"run.max":{"max":{"field":"run"}},"count":{"value_count":{"field":"run"}},"time.max":{"max":{"field":"timestamp"}}}},"settings":{"max_page_search_size":10}} |  
  | [2021-02-02T19:11:42,180][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putTransform: {"id":"continuous-date-histogram-pivot-other-timefield-test","source":{"index":["test-transform-continuous-events"]},"dest":{"index":"continuous-date-histogram-pivot-other-timefield-test","pipeline":"transform-ingest"},"frequency":"1s","sync":{"time":{"field":"timestamp","delay":"1s"}},"pivot":{"group_by":{"second":{"date_histogram":{"field":"metric-timestamp","fixed_interval":"1s"}}},"aggregations":{"run.max":{"max":{"field":"run"}},"count":{"value_count":{"field":"run"}},"time.max":{"max":{"field":"timestamp"}}}},"settings":{"max_page_search_size":10,"dates_as_epoch_millis":true}} |  
  | [2021-02-02T19:11:42,243][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putTransform: {"id":"continuous-latest-test","source":{"index":["test-transform-continuous-events"],"runtime_mappings":{"event-upper-at-search":{"type":"keyword","script":{"source":"if (params._source.event != null) {emit(params._source.event.toUpperCase())}"}}}},"dest":{"index":"continuous-latest-test","pipeline":"transform-ingest"},"frequency":"1s","sync":{"time":{"field":"timestamp","delay":"1s"}},"latest":{"unique_key":["event-upper-at-search"],"sort":"timestamp-at-runtime"},"settings":{"max_page_search_size":10}} |  
  | [2021-02-02T19:11:42,314][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] putPipeline: {"processors":[{"set":{"field":"run_ingest","value":0}}]} |  
  | [2021-02-02T19:11:48,047][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] startTransform: continuous-terms-pivot-test |  
  | [2021-02-02T19:11:48,245][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] startTransform: continuous-terms-on-date-pivot-test |  
  | [2021-02-02T19:11:48,568][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] startTransform: continuous-date-histogram-pivot-test |  
  | [2021-02-02T19:11:48,878][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] startTransform: continuous-date-histogram-pivot-other-timefield-test |  
  | [2021-02-02T19:11:49,291][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] startTransform: continuous-latest-test |  
  | [2021-02-02T19:11:49,642][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] wait until transform reaches timestamp_millis: 2021-02-02T15:11:50.641481Z (takes into account the delay: 1s) iteration: 0 |  
  | [2021-02-02T19:11:52,020][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] stopTransform: continuous-terms-pivot-test |  
  | [2021-02-02T19:11:52,099][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] stopTransform: continuous-terms-on-date-pivot-test |  
  | [2021-02-02T19:11:52,178][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] stopTransform: continuous-date-histogram-pivot-test |  
  | [2021-02-02T19:11:52,264][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] stopTransform: continuous-date-histogram-pivot-other-timefield-test |  
  | [2021-02-02T19:11:52,334][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] stopTransform: continuous-latest-test |  
  | [2021-02-02T19:11:52,482][WARN ][o.e.c.RestClient         ] [testContinousEvents] request [POST http://127.0.0.1:41881/_refresh?expand_wildcards=open%2Chidden] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-0b4b59c7849ce9be2aaaf60143df93688e5381e1 "this request accesses system indices: [.transform-internal-005], but in a future major version, direct access to system indices will be prevented by default"] |  
  | [2021-02-02T19:11:52,929][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] deletePipeline: transform-ingest |  
  | [2021-02-02T19:11:52,979][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] deleteTransform: continuous-date-histogram-pivot-other-timefield-test |  
  | [2021-02-02T19:11:53,054][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] deleteTransform: continuous-date-histogram-pivot-test |  
  | [2021-02-02T19:11:53,131][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] deleteTransform: continuous-latest-test |  
  | [2021-02-02T19:11:53,210][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] deleteTransform: continuous-terms-on-date-pivot-test |  
  | [2021-02-02T19:11:53,287][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] deleteTransform: continuous-terms-pivot-test |  
  | [2021-02-02T19:11:53,570][WARN ][o.e.c.RestClient         ] [testContinousEvents] request [DELETE http://127.0.0.1:39787/*,-.ds-ilm-history-*?expand_wildcards=open%2Cclosed%2Chidden] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-0b4b59c7849ce9be2aaaf60143df93688e5381e1 "this request accesses system indices: [.transform-internal-005], but in a future major version, direct access to system indices will be prevented by default"] |  
  | [2021-02-02T19:11:53,574][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] Clearing template [test-transform-continuous-events_template] |  
  | [2021-02-02T19:11:53,807][INFO ][o.e.x.t.i.c.TransformContinuousIT] [testContinousEvents] after test |  
  | REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" -Dtests.seed=99F2CC3E4300F517 -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Asia/Dubai -Druntime.java=11


```

### PR DESCRIPTION
**Pull request by przemekwitek**
In `LatestContinuousIT` we sometimes use search runtime field in transform.
We should set the same search runtime field in runtime mappings of the search request against source index.
This PR implements this.

Fixes https://github.com/elastic/elasticsearch/issues/68394

### CODE REVIEW

File: x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/continuous/LatestContinuousIT.java [hunk 1]
```diff
@@ -38,11 +38,17 @@
 import static org.hamcrest.Matchers.is;
 import static org.hamcrest.Matchers.not;
 
-@AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/68394")
 public class LatestContinuousIT extends ContinuousTestCase {
 
     private static final String NAME = "continuous-latest-test";
 
+    private static final Map<String, Object> RUNTIME_MAPPINGS =
+        new HashMap<>() {{
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/continuous/LatestContinuousIT.java:46]: I think this uses java features that we can't use in `7.x`. Unless I'm wrong, could we change this to the older (and unfortunately more verbose) syntax to avoid conflicts on future backports?

**Review by dimitris-athanasiou — COMMENTED** [review]
Just a comment on using java features that are not available in 7.x

File: x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/continuous/LatestContinuousIT.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/continuous/LatestContinuousIT.java]: Done.

I usually add the generic parameters during backport, but can do it here as well.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM
