### PR TITLE
[SECURITY] Set Auth-scheme preference

### LINKED ISSUE #32699: Unexpected basic auth prompt with SPNEGO (kerberos) enabled in browser
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**: With kerberos enabled, basic auth still has first priority and issues a popup for user/pass in the browser. Moving kerberos to order 0 doesn't change this behavior.

**Steps to reproduce**:
_elasticsearch.yml_
```
xpack.security.audit.enabled: true
xpack.security.audit.outputs: [ logfile ]
xpack.security.enabled: true
xpack:
  security:
    authc:
      realms:
        kerberos:
            type: kerberos
            order: 0
            keytab.path: /Users/rgil/Downloads/elasticsearch-6.4.0/config/elasticsearch.test.keytab
            remove_realm_name: true
            krb.debug: true
            enabled: true
```
_role mapping_
```
{
  "roles" : [ "superuser"],
  "enabled": true,
  "rules" : {
    "field" : { "username" : "*" }
  }
}
```
After hitting cancel on the basic auth, the SPNEGO auth passes just fine. 

With SPNEGO enabled, I would expect no authentication popups/prompts

For Firefox `firefox network.negotiate-auth.trusted-uris` needs to be set correctly for the service principal being used (in my testing I used `elasticsearch.test`)

Configuration for kerberos is using FreeIPA

Client OS is OSX (_not_ MIT kerberos)

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

- Create keytab
- Configure /etc/krb5.conf on server (hosting elasticsearch)
- Grant permissions to service principal
- Configure ES
- Set Role
- kinit <user>@<realm>
- `curl -s --negotiate -u : -b ~/cookiejar.txt -c ~/cookiejar.txt  http://elasticsearch.test:9200/_xpack/security/_authenticate|jq` to validate
- Test in browser with proper configuration mentioned above 

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by bizybot**
Some browsers (eg. Firefox) behave differently when presented with
multiple auth schemes in 'WWW-Authenticate' header. The expected
behavior is that browser select the most secure auth-scheme before
trying others, but Firefox selects the first presented auth scheme and
tries the next ones sequentially. As the browser interpretation is
something that we do not control, we can at least present the auth
schemes in most to least secure order as the server's preference.

This commit modifies the code to collect and sort the auth schemes
presented by most to least secure. The priority of the auth schemes is
fixed, the lower number denoting more secure auth-scheme.
The current order of schemes based on the ES supported auth-scheme is
[`Negotiate`, `Bearer`,`Basic`] and when we add future support for
other schemes we will need to update the code. If need be we will make
this configuration customizable in future.

Unit test to verify the `WWW-Authenticate` header values are sorted by
server preference as more secure to least secure auth schemes.
Tested with Firefox, Chrome, Internet Explorer 11.

Closes#32699

### CODE REVIEW

**Review by jaymode — CHANGES_REQUESTED** [review]

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java [hunk 1]
```diff
@@ -107,8 +108,27 @@ public void testExceptionProcessingRequest() {
...
+        assertThat(ese, is(notNullValue()));
+        assertThat(ese.getHeader("WWW-Authenticate"), is(notNullValue()));
+        assertThat(ese.getMessage(), equalTo("error attempting to authenticate request"));
+        assertWWWAuthenticateWithSchemes(ese, basicAuthScheme, bearerAuthScheme, negotiateAuthScheme);
+    }
+
     private void assertWWWAuthenticateWithSchemes(final ElasticsearchSecurityException ese, final String... schemes) {
         assertThat(ese.getHeader("WWW-Authenticate").size(), is(schemes.length));
+        // Auth scheme are ordered as more secure to least secure
+        Arrays.sort(schemes, (o1, o2) -> authSchemePriority(o1).compareTo(authSchemePriority(o2)));
```
Comment (jaymode) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java]: can you make this explicit? ie there could be a bug in `authSchemePriority` so we should validate Negotiate first, then bearer, then basic

**Review by jaymode — CHANGES_REQUESTED** [review]

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java [hunk 2]
```diff
@@ -102,11 +102,28 @@ public void testExceptionProcessingRequest() {
...
         }
 
     }
 
+    public void testSortsWWWAuthenticateHeaderValues() {
+        final String basicAuthScheme = "Basic realm=\"" + XPackField.SECURITY + "\" charset=\"UTF-8\"";
+        final String bearerAuthScheme = "Bearer realm=\"" + XPackField.SECURITY + "\"";
+        final String negotiateAuthScheme = randomFrom("Negotiate", "Negotiate Ijoijksdk");
+        final Map<String, List<String>> failureResponeHeaders = new HashMap<>();
+        failureResponeHeaders.put("WWW-Authenticate", Arrays.asList(basicAuthScheme, bearerAuthScheme, negotiateAuthScheme));
```
Comment (jaymode) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java]: We should randomize the order of this list, ie `Collections.shuffle(list, random())`

**Review by jaymode — APPROVED** [review]
I left one minor comment, otherwise LGTM

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java (hunk 2 above)
Comment (bizybot) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/DefaultAuthenticationFailureHandlerTests.java]: Thanks, addressed this.

**Comment by azasypkin** [comment]
> Some browsers (eg. Firefox) behave differently when presented with
multiple auth schemes in 'WWW-Authenticate' header. The expected
behavior is that browser select the most secure auth-scheme before
trying others, but Firefox selects the first presented auth scheme and
tries the next ones sequentially. As the browser interpretation is
something that we do not control, we can at least present the auth
schemes in most to least secure order as the server's preference.

@bizybot, have we filed a bug against Firefox (assuming there was no existing one)? Can you please share a link? Thanks!

**Comment by tvernum** [comment]
@azasypkin
See https://github.com/elastic/elasticsearch/issues/32699#issuecomment-412763576

**Comment by azasypkin** [comment]
> See #32699 (comment)

Thanks! `Reported: 8 years ago` :disappointed:

**Comment by tvernum** [comment]
Yeah, we decided it probably wasn't worth waiting on an upstream fix.
