### PR TITLE
Fix setting timezone on default DateTime formatter

### LINKED ISSUE #12531: Inconsistent usage of ValueFormatter.DateTime
ValueFormatter.DateTime is mutable so that we can set the timezone to use in order to display date/times (DateHistogramParser calls this method). But we also have the ValueFormatter.DateTime.DEFAULT constant, so if this constant is used and there are several concurrent requests, then they might invalidate each other's timezone parameter.

### PR DESCRIPTION
**Pull request by cbuescher**
This PR prevents setting timezone on ValueFormatter.DateTime. Instead
the timezone information needed when printing buckets key-as-string
information is provided at constrution time of the ValueFormatter, making
sure we don't overwrite any constants. This, however, made it necessary to
be able to access the timezone information when resolving the format
in ValueSourseParser, so the `time_zone` parameter is now parsed alongside
the `format` parameter in ValueSourceParser rather than in DateHistogramParser.

Closes #12531

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/rounding/TimeZoneRounding.java [hunk 1]
```diff
@@ -64,7 +64,9 @@ public Builder(TimeValue interval) {
         }
 
         public Builder timeZone(DateTimeZone timeZone) {
-            this.timeZone = timeZone;
+            if (timeZone != null) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/rounding/TimeZoneRounding.java]: why do we need this null check, it looks trappy?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/rounding/TimeZoneRounding.java]: maybe we should check that the timeZone argument is not null and fix callers to not call this method with a null timezone?

Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/common/rounding/TimeZoneRounding.java]: Will add throwing an exception here, this was just for added security since the callers should already always use UTC as default.

**Comment by cbuescher** [comment]
@jpountz Added exception when trying to set null as timezone value, all callers should already use UTC as defaults where possible.

File: core/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceParser.java [hunk 2]
```diff
@@ -66,7 +70,7 @@ public static Builder any(String aggName, InternalAggregation.Type aggType, Sear
         return new Builder<>(aggName, aggType, context, ValuesSource.GeoPoint.class).targetValueType(ValueType.GEOPOINT).scriptable(false);
     }
 
-    private static class Input {
+    public static class Input {
         String field = null;
```
Comment (colings86) [inline core/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceParser.java]: Maybe Input should be immutable if we are going to make it public?

**Comment by colings86** [comment]
@cbuescher I left one comment but otherwise it looks good :)

File: core/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceParser.java (hunk 2 above)
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceParser.java]: Lookig at this again, I don't like exposing the Input just to get the timezone information in the DateHistogramParser, I think it better belongs there where it was in the first place. Will add a commit where I change to passing timezone as optional argument to `ValueSourceParse.config()`, IMHO much cleaner.

**Comment by cbuescher** [comment]
@colings86 thanks, I looking at your comment I opted for changing to a slightly different solution which involves even less changes in the existing code. Mind to take another look?

**Comment by colings86** [comment]
I actually prefer the previous solution (with Input made immutable) than this. The problem here for me is that the valuesSource interface now exposes timezone when it isn't a common property of valuesSource, its an option which is configured in the request which is exactly what the Input class represents. Also, in the upcoming aggregation refactoring changes the Input class will be exposed anyway so the previous solution will need to be implemented regardless and the timezone will need to be included in that Input class.

**Comment by cbuescher** [comment]
@colings86 no problem, when back to the previous solution, making fields in Input final is impossible since ValueSourceParse directly updates them, but I made them all private an only expose the timezone which is needen in DateHistogramParser for now. Let me know if you think this is okay.

**Comment by colings86** [comment]
@cbuescher ok great, it LGTM but maybe @jpountz would like to have a last look before its merged?

**Comment by jpountz** [comment]
LGTM
