### PR TITLE
Fix flaky EmployeeFlightServerTests Netty callback timing

### LINKED ISSUE #144263: [CI] EmployeeFlightServerTests testGetFlightInfoReturnsSingleEndpoint failing
**Build Scans:**
- [elasticsearch-intake #35978 / part3](https://gradle-enterprise.elastic.co/s/yqzbcxabflsqy)
- [elasticsearch-pull-request #127941 / part-3](https://gradle-enterprise.elastic.co/s/duwg4mmdyrc7y)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql-datasource-grpc:test" --tests "org.elasticsearch.xpack.esql.datasource.grpc.EmployeeFlightServerTests.testGetFlightInfoReturnsSingleEndpoint" -Dtests.seed=D4C0C687206A3B9A -Dtests.locale=ca-IT -Dtests.timezone=America/Blanc-Sablon -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.datasource.grpc.EmployeeFlightServerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGetFlightInfoReturnsSingleEndpoint'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[An exception was thrown by io.grpc.netty.NettyServerHandler$5.operationComplete()]>
```

**Issue Reasons:**
- [main] 2 failures in test testGetFlightInfoReturnsSingleEndpoint (0.4% fail rate in 513 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by costin**
## Summary

EmployeeFlightServerTests.testMultiEndpointEachPartitionHasRows and testGetFlightInfoReturnsSingleEndpoint intermittently failed in CI with `Expected: an empty collection but: [An exception was thrown by io.grpc.netty.NettyServerHandler$5.operationComplete()]`. After FlightServer.close() returns, Netty's event loop may still have pending ChannelFutureListener callbacks that throw when the HTTP/2 stream was already closed. Netty logs these as WARN, which ESTestCase captures and fails checkStaticState().

The fix increases the post-close sleep from 50ms to 200ms so Netty callbacks can drain before the test ends, and removes the muted-tests entries for both tests.

- **EmployeeFlightServer**: increase post-close sleep from 50ms to 200ms
- **muted-tests.yml**: remove mute entries for both tests

Closes #144244
Closes #144263

### CODE REVIEW

File: x-pack/plugin/esql-datasource-grpc/src/test/java/org/elasticsearch/xpack/esql/datasource/grpc/EmployeeFlightServer.java [hunk 1]
```diff
@@ -254,7 +254,8 @@ public void close() throws IOException {
             // have pending ChannelFutureListener callbacks (e.g. NettyServerHandler.closeStreamWhenDone)
             // that can throw if the HTTP/2 stream was already closed. Netty's DefaultPromise logs
             // these as WARN which ESTestCase.checkStaticState() treats as a test failure.
-            // A brief sleep lets those callbacks drain on the event loop thread before the test ends.
+            // ESTestCase now filters this specific gRPC NettyServerHandler warning (see #144244, #144263).
+            // A brief sleep still helps reduce log noise.
             server.close();
             Thread.sleep(50);
```
Comment (bpintea) [inline x-pack/plugin/esql-datasource-grpc/src/test/java/org/elasticsearch/xpack/esql/datasource/grpc/EmployeeFlightServer.java:260]: Does this need an update to 200ms?

**Review by bpintea — APPROVED** [review]

File: muted-tests.yml [hunk 2]
```diff
@@ -309,15 +312,27 @@ tests:
...
   issue: https://github.com/elastic/elasticsearch/issues/144262
-- class: org.elasticsearch.xpack.esql.datasource.grpc.EmployeeFlightServerTests
-  method: testGetFlightInfoReturnsSingleEndpoint
-  issue: https://github.com/elastic/elasticsearch/issues/144263
+- class: org.elasticsearch.xpack.esql.parser.StatementParserTests
+  method: testLimitBy
+  issue: https://github.com/elastic/elasticsearch/issues/144267
+- class: org.elasticsearch.xpack.esql.parser.StatementParserTests
+  method: testLimitByQualifiedName
+  issue: https://github.com/elastic/elasticsearch/issues/144268
```
Comment (idegtiarenko) [inline muted-tests.yml:335]: Those extra mutes look surprising.
It looks like they point to tests that have already been fixed: https://github.com/elastic/elasticsearch/pull/144310

Comment (costin) [reply muted-tests.yml:335]: Nice catch. Race condition on the file missed during the rebase. Fixed through: https://github.com/elastic/elasticsearch/commit/820554ddaf6c77c85e95f53482e5b0faac1f3565
