### PR TITLE
ESQL: fix for missing indices error message

### LINKED ISSUE #111712: ESQL: no error message on missing index
```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test" -XPUT -d '{
  "mappings": {
        "properties": {
            "x": {
                "type": "long"
            },
            "y": {
                "type": "long"
            }
        }
  }
}'

from test, some_missing_index
```

This doesn't cause an `IndexNotFoundException` anymore, like it did in 8.15.

This is not the same as https://github.com/elastic/elasticsearch/issues/104987 because the index name does not use a wildcard, in which case it's reasonable to be more lenient.

### PR DESCRIPTION
**Pull request by astefan**
Reverts a part of https://github.com/elastic/elasticsearch/pull/109483 by going back to the previous (more restrictive) way of dealing with missing indices or aliases. More specifically, if an index pattern used in a query refers to a missing index or alias name and doesn't use a wildcard for this name, then we error out. Our lack of testing in this area made the change in https://github.com/elastic/elasticsearch/pull/109483 to be invisible.

Fixes https://github.com/elastic/elasticsearch/issues/111712

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Thank you for adding many great tests here 👍

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java [hunk 1]
```diff
@@ -841,23 +856,16 @@ public void testAlias() throws Exception {
             }""");
         assertOK(adminClient().performRequest(putRoleRequest));
         // query `employees2`
-        for (String index : List.of("*:employees2", "*:employee*", "*:employee*,*:alias-employees,*:employees3")) {
+        for (String index : List.of("*:employees2", "*:employee*")) {
             Request request = esqlRequest("FROM " + index + " | KEEP emp_id | SORT emp_id | LIMIT 100");
+            System.out.println("FROM " + index);
```
Comment (bpintea) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java:861]: Leftover. 
(Interesting it wasn't caught by the APIs check)

File: x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/Clusters.java [hunk 2]
```diff
@@ -12,9 +12,13 @@
 import org.elasticsearch.test.cluster.util.Version;
 
 public class Clusters {
+
+    static final String REMOTE_CLUSTER_NAME = "remote_cluster";
```
Comment (bpintea) [inline x-pack/plugin/esql/qa/server/multi-clusters/src/javaRestTest/java/org/elasticsearch/xpack/esql/ccq/Clusters.java:16]: 👍

**Review by bpintea — APPROVED** [review]
LGTM

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java]: Ouch. Thanks for spotting it.

**Comment by astefan** [comment]
@elasticsearchmachine run elasticsearch-ci/part-4

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/part-4

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java [hunk 3]
```diff
@@ -222,18 +222,60 @@ public void testInsufficientPrivilege() {
...
-            FROM index-user1,index-user2 METADATA _index
-            | STATS sum=sum(value), index=VALUES(_index)
-            """);
-        assertOK(resp);
-        Map<String, Object> respMap = entityAsMap(resp);
+        ResponseException resp = expectThrows(
+            ResponseException.class,
+            () -> runESQLCommand(
+                "metadata1_read2",
+                "FROM index-user1,index-user2 METADATA _index | STATS sum=sum(value), index=VALUES(_index)"
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:229]: Should this work for just
```
                "FROM index-user1,index-user2 METADATA _index | STATS index = VALUES(_index)"
```
because we have metadata privileges on `index-user1`? If so, do we have a test for this as well?

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java [hunk 4]
```diff
@@ -222,18 +222,60 @@ public void testInsufficientPrivilege() {
...
+        assertThat(resp.getResponse().getStatusLine().getStatusCode(), equalTo(HttpStatus.SC_FORBIDDEN));
+
+        resp = expectThrows(
+            ResponseException.class,
+            () -> runESQLCommand(
+                "alias_user2",
+                "from second-alias,index-user2 METADATA _index | stats sum=sum(value), index=VALUES(_index)"
+            )
+        );
+        System.out.println(EntityUtils.toString(resp.getResponse().getEntity()));
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:271]: Leftover! :)

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java [hunk 5]
```diff
@@ -0,0 +1,170 @@
...
+        assertErrorMessages(inexistentIndexNameWithWildcard, getInexistentIndexErrorMessage(), 400);
+    }
+
+    public void testInexistentIndexNameWithoutWildcard() throws IOException {
+        assertErrorMessages(inexistentIndexNameWithoutWildcard, getInexistentIndexErrorMessage(), 400);
+    }
+
+    public void testExistentIndexWithoutWildcard() throws IOException {
+        for (String indexName : existentIndexWithoutWildcard) {
+            assertErrorMessage(indexName, "\"reason\" : \"no such index [inexistent]\"", 404);
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java:90]: Should we have a 400 for `inexistentIndexNameWithoutWildcard` but a 404 if the same index wasn't found as part of a pattern from `existentIndexWithoutWildcard`?

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java:1]: <3 this is a very neatly designed test suite!

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java [hunk 6]
```diff
@@ -347,21 +348,6 @@ public void testCrossClusterQuery() throws Exception {
...
 
-        // query remote cluster only - but also include employees2 which the user does not have access to
-        response = performRequestWithRemoteSearchUser(esqlRequest("""
-            FROM my_remote_cluster:employees,my_remote_cluster:employees2
-            | SORT emp_id ASC
-            | LIMIT 2
-            | KEEP emp_id, department"""));
-        assertRemoteOnlyResults(response); // same as above since the user only has access to employees
-
-        // query remote and local cluster - but also include employees2 which the user does not have access to
```
Comment (alex-spies) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityEsqlIT.java:358]: nit: we could keep the comments, since the asserted error messages don't immediately give away the reason why the request was invalid.

**Review by alex-spies — APPROVED** [review]
LGTM! Thanks @astefan , this is great!

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java (hunk 4 above)
Comment (astefan) [reply x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:271]: Thanks.
That's the "joy" of not being able to debug this test locally.

File: x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java (hunk 3 above)
Comment (astefan) [reply x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java:229]: @alex-spies it doesn't matter the privileges here, but more how ES discovers the index patterns provided. The change in ComputeService is the essential one where I changed back the indices options to `SearchRequest.DEFAULT_INDICES_OPTIONS` which is slightly different and less permissive than the one we have in `IndexResolver`.

And I _think_ (haven't dug deep into this one) the relevant difference in indices options is 
`.concreteTargetOptions(ConcreteTargetOptions.ALLOW_UNAVAILABLE_TARGETS)` in `IndexResolver` and 
`.concreteTargetOptions(ConcreteTargetOptions.ERROR_WHEN_UNAVAILABLE_TARGETS)` in `SearchRequest`.

What permissions (at Security level) this needs I am not sure, but I tested in the same method of this class the equivalent `_search` query for `from index-user1,index-user2` like this:

```
        XContentBuilder json = JsonXContent.contentBuilder();
        json.startObject();
        json.field("query", QueryBuilders.matchAllQuery());
        json.endObject();
        Request request = new Request("GET", "/index-user1,index-user2/_search");
        request.setJsonEntity(Strings.toString(json));
        request.setOptions(RequestOptions.DEFAULT.toBuilder().addHeader("es-security-runas-user", "metadata1_read2"));
        resp = expectThrows(ResponseException.class, () -> client().performRequest(request));
        assertThat(
            EntityUtils.toString(resp.getResponse().getEntity()),
            containsString(
                "unauthorized for user [test-admin] run as [metadata1_read2] with effective roles [metadata1_read2] on indices [index-user1]"
            )
        );
        assertThat(resp.getResponse().getStatusLine().getStatusCode(), equalTo(HttpStatus.SC_FORBIDDEN));
```

And the test passes which means that ES|QL for this index pattern and test setup (I refer here to users, roles and permissions) behaves exactly like `_search` query DSL does.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java (hunk 5 above)
Comment (astefan) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java:90]: `from existent, inexistent` with `404` (`existentIndexWithoutWildcard`) comes from ES itself.
`from inexistent` with `400` (`inexistentIndexNameWithoutWildcard`) comes from ES|QL.

Comment (alex-spies) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java:90]: Hm, I wonder if ESQL should just catch the errors from ES to provide consistent `ValidationException`s, and consistent error codes.

Comment (astefan) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlRestValidationTestCase.java:90]: Created issue https://github.com/elastic/elasticsearch/issues/112132
