### PR TITLE
Handle parallel calls to createWeight when profiling is on

### LINKED ISSUE #104131: Profiling can throw when using kNN with a pre-filter
### Elasticsearch Version

8.11+

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When profiling complex queries an exception can be thrown during profiling

### Steps to Reproduce

still working on this...

### Logs (if relevant)

```
Caused by: org.elasticsearch.search.dfs.DfsPhaseExecutionException: Dfs Failed [Exception during dfs phase]
  at org.elasticsearch.search.dfs.DfsPhase.execute(DfsPhase.java:61)
  at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:500)
  at org.elasticsearch.search.SearchService.lambda$executeDfsPhase$0(SearchService.java:489)
  at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51)
  at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48)
  at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: index_out_of_bounds_exception: Index: 26, Size: 23
  at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:838)
  at java.util.ArrayList.add(ArrayList.java:510)
  at org.elasticsearch.search.profile.AbstractInternalProfileTree.addDependencyNode(AbstractInternalProfileTree.java:103)
  at org.elasticsearch.search.profile.AbstractInternalProfileTree.getProfileBreakdown(AbstractInternalProfileTree.java:78)
  at org.elasticsearch.search.profile.AbstractProfiler.getQueryBreakdown(AbstractProfiler.java:26)
  at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:225)
  at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:59)
  at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:245)
  at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:230)
  at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:136)
  at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight.rewrite(AbstractMultiTermQueryConstantScoreWrapper.java:174)
  at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight$1.get(AbstractMultiTermQueryConstantScoreWrapper.java:269)
  at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
  at org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:212)
  at org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:131)
  at org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:111)
  at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
  at org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:212)
  at org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:131)
  at org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:111)
  at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
  at org.elasticsearch.search.profile.query.ProfileWeight.scorer(ProfileWeight.java:45)
  at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:134)
  at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:117)
  at org.apache.lucene.search.AbstractKnnVectorQuery.lambda$parallelSearch$0(AbstractKnnVectorQuery.java:111)
  at java.util.concurrent.FutureTask.run(FutureTask.java:317)
  ... 6 more
```

### LINKED ISSUE #104235: [CI] DfsProfilerIT testProfileDfs failing
This reproduced locally for me.

**Build scan:**
https://gradle-enterprise.elastic.co/s/5tk2twhstr3iy/tests/:server:internalClusterTest/org.elasticsearch.search.profile.dfs.DfsProfilerIT/testProfileDfs

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.profile.dfs.DfsProfilerIT.testProfileDfs" -Dtests.seed=F1A3160151EBA0D6 -Dtests.locale=tr-TR -Dtests.timezone=America/Indiana/Knox -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.search.profile.dfs.DfsProfilerIT#testProfileDfs`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testProfileDfs'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.search.profile.dfs.DfsProfilerIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed

  at __randomizedtesting.SeedInfo.seed([F1A3160151EBA0D6:D5270E587F366AE1]:0)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:708)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:400)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:740)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:493)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:331)
  at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
  at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:656)
  at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1717)
  at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
  at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1575)
  at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1550)
  at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:46)
  at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:38)
  at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:146)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: org.elasticsearch.ElasticsearchException$1: Index: 33, Size: 31

    at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:673)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:398)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:740)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:493)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:331)
    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
    at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:656)
    at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1717)
    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1575)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1550)
    at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:46)
    at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:38)
    at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:146)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

    Caused by: java.lang.IndexOutOfBoundsException: Index: 33, Size: 31

      at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:838)
      at java.util.ArrayList.add(ArrayList.java:510)
      at org.elasticsearch.search.profile.AbstractInternalProfileTree.addDependencyNode(AbstractInternalProfileTree.java:103)
      at org.elasticsearch.search.profile.AbstractInternalProfileTree.getProfileBreakdown(AbstractInternalProfileTree.java:78)
      at org.elasticsearch.search.profile.AbstractProfiler.getQueryBreakdown(AbstractProfiler.java:26)
      at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:219)
      at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:136)
      at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight.rewrite(AbstractMultiTermQueryConstantScoreWrapper.java:174)
      at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight$1.get(AbstractMultiTermQueryConstantScoreWrapper.java:269)
      at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
      at org.apache.lucene.search.DisjunctionMaxQuery$DisjunctionMaxWeight$1.get(DisjunctionMaxQuery.java:154)
      at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
      at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
      at org.elasticsearch.search.profile.query.ProfileWeight.scorer(ProfileWeight.java:45)
      at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:116)
      at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:99)
      at org.apache.lucene.search.AbstractKnnVectorQuery.lambda$rewrite$0(AbstractKnnVectorQuery.java:86)
      at org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:118)
      at java.util.concurrent.FutureTask.run(FutureTask.java:317)
      at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
      at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
      at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by javanna**
We disable inter-segment concurrency in the query phase whenever profile is on, because there are known concurrency issues that need fixing. The way we disable concurrency is by creating a single slice that search will execute against. We still offload the execution to the search workers thread pool.

Inter-segment concurrency in Lucene is though not always based on slices. Knn query (as well as terms enum loading and other places) parallelizes across all segments independently of slices that group multiple segments together. That behavior is not easy to disable unless you don't set the executor to the searcher, in which case though you entirely disable using the separate executor for potentially heavy CPU/IO based loads which is not desirable.

That means that when executing a knn query, it will execute in parallel (in DFS as well as in the query phase) no matter if inter-segment concurrency has been disabled because profiling is on. When using pre-filtering, there are queries like multi term queries that will call createWeight from each segment, in parallel, when pulling the scorer. That causes non-deterministic behavior as the profiler does not support concurrent access to some of its data structures.

This commit protects the profiler from concurrent access to its data structures by synchronizing access to its tree. Performance is not a concern here, as profiler is already known to slow down query execution.

Closes #104235
Closes #104131

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/profile/AbstractInternalProfileTree.java [hunk 1]
```diff
@@ -48,7 +48,7 @@ public AbstractInternalProfileTree() {
      * @param query The scoring query we wish to profile
      * @return      A ProfileBreakdown for this query
      */
-    public PB getProfileBreakdown(E query) {
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/profile/AbstractInternalProfileTree.java:51]: could you make all the fields `private` ? Otherwise inheriting classes can access them non-synchronized.

**Review by benwtrent — APPROVED** [review]
This isn't a big concern IMO. I think just synchronizing is sane enough protection.

File: server/src/main/java/org/elasticsearch/search/profile/AbstractInternalProfileTree.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/profile/AbstractInternalProfileTree.java:51]: thank you for catching that, it's important.
