### PR TITLE
Throw Error on deprecated nGram and edgeNGram custom filters

### LINKED ISSUE #50360: nGram and edgeNGram names don't throw an error with custom filters on ES 7+
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.0 - 7.5.1

**Plugins installed**: []

**JVM version** (`java -version`): n/a

**OS version** (`uname -a` if on a Unix-like system): n/a

**Description of the problem including expected versus actual behavior**:

Hi, according to [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#deprecated-ngram-edgengram-token-filter-cannot-be-used), the `nGram` and `edgeNGram` token filter should throw an error in ES 7 (since they've been replaced with `ngram` and `edge_ngram`). However, this doesn't appear to be the case if you use them in custom filters. 

**Steps to reproduce**:

```sh
curl -X PUT "localhost:9200/my_index?pretty" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "bad_analyzer": { 
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "bad_filter"
          ]
        }
      },
      "filter": {
        "bad_filter": {
          "type": "nGram"
        }
      }
    }
  }
}
'
curl -X GET "localhost:9200/my_index/_analyze?pretty" -H 'Content-Type: application/json' -d'
{
  "analyzer": "bad_analyzer", 
  "text":     "Is this déjà vu?"
}
'
```

### PR DESCRIPTION
**Pull request by cbuescher**
The camel-case `nGram` and `edgeNGram` filter names were deprecated in 6. We
currently throw errors on new indices when they are used. However these errors
are currently only thrown for pre-configured filters, adding them as custom
filters doesn't trigger the warning and error. This change adds the appropriate
exceptions for `nGram` and `edgeNGram` respectively.

Closes #50360

### CODE REVIEW

File: modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java [hunk 1]
```diff
@@ -242,7 +244,17 @@
         filters.put("dictionary_decompounder", requiresAnalysisSettings(DictionaryCompoundWordTokenFilterFactory::new));
         filters.put("dutch_stem", DutchStemTokenFilterFactory::new);
         filters.put("edge_ngram", EdgeNGramTokenFilterFactory::new);
-        filters.put("edgeNGram", EdgeNGramTokenFilterFactory::new);
+        filters.put("edgeNGram", (IndexSettings indexSettings, Environment environment, String name, Settings settings) -> {
+            if (indexSettings.getIndexVersionCreated().onOrAfter(org.elasticsearch.Version.V_7_6_0)) {
```
Comment (cbuescher) [inline modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java]: Unfortunately we can only error for these cases starting with 7.6 now since there might already be existing indices <7.6 that we don't want to break on minor version upgrade. Those should at least be logging a deprecation now.

Comment (nik9000) [reply modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java]: Do you think we should wait until 8 because this is technically breaking? I mean, using them relies on a bug, but still.

File: modules/analysis-common/src/test/java/org/elasticsearch/analysis/common/CommonAnalysisPluginTests.java [hunk 2]
```diff
@@ -19,6 +19,8 @@
 
 package org.elasticsearch.analysis.common;
 
+import com.carrotsearch.randomizedtesting.annotations.Repeat;
```
Comment (nik9000) [inline modules/analysis-common/src/test/java/org/elasticsearch/analysis/common/CommonAnalysisPluginTests.java]: Unused import?

Comment (cbuescher) [reply modules/analysis-common/src/test/java/org/elasticsearch/analysis/common/CommonAnalysisPluginTests.java]: Gone already

File: modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java (hunk 1 above)
Comment (cbuescher) [reply modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java]: We already removed the PreConfiguredTokenFilter registration for "nGram" and "edgeNGram" in 8 (using those should have thrown errors since 7.0), but I see we still register them in `getTokenFilters()`. Still we clearly [documented the deprecation and removal](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#deprecated-ngram-edgengram-token-filter-cannot-be-used) and I think we don't mention those variants in the docs for a long time now. I think disallowing new index creation using those in 7.6 should be okay, wdyt?
I think for 8.0 this means we cannot remove the registration for these names just yet and need to forward-port this error/deprecation handling there as well unfortunately.

Comment (nik9000) [reply modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java]: I just don't want someone who does a minor upgrade to have their daily indices not get created any more.

Comment (cbuescher) [reply modules/analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java]: Sound like we should start logging the deprecation warning with 7.6 and throw an error on 8.0 for this then. That would only apply for this type of custom filter use left out by the original deprecation back in https://github.com/elastic/elasticsearch/pull/30209.
I will update the PR and see if I can change the target branch so we add this on master and then backport to 7.x

**Comment by cbuescher** [comment]
@nik9000 moved the PR to target master, the deprecation part would be the backported to 7.6.0.

**Review by nik9000 — APPROVED** [review]
LGTM. Sorry for all the trouble.

**Comment by cbuescher** [comment]
@elasticmachine update branch
