### PR TITLE
Normalize negative scores for text_similarity_reranker retriever

### LINKED ISSUE #120201: text_similarity_reranker returns negative scores for some models
### Elasticsearch Version

8.16.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Reproducable on cloud

### Problem Description

Certain supported rerank models, including `cross-encoder__ms-marco-minilm-l-6-v2`, return negative scores when used in conjunction with the `text_similarity_reranker`. Negative scores are not allowed in the query phase, so we need to handle this better. 

One potential solution is linearly shifting or otherwise normalizing the returned score values, so they're always within certain parameters.

### Steps to Reproduce

```
PUT _inference/rerank/ms-marco-minilm-l-6-v2
{
  "service": "elasticsearch",
  "task_type": "rerank",
  "service_settings": {
    "num_allocations": 1,
    "num_threads": 1,
    "model_id": "cross-encoder__ms-marco-minilm-l-6-v2"
  },
  "task_settings": {
    "return_documents": true
  }
}

PUT /my-index
{
  "mappings": {
    "properties": {
      "title": {
        "type": "text"
      }
    }
  }
}

POST /my-index/_doc/
{
  "text": "Dog training classes"
}

POST my-index/_search
{
  "retriever": {
    "text_similarity_reranker": {
      "retriever": {
        "standard": {
          "query": {
            "match": {
              "text": "dog"
            }
          }
        }
      },
      "field": "text",
      "inference_id": "ms-marco-minilm-l-6-v2",
      "inference_text": "dog",
      "rank_window_size": 100
    }
  }
}
```

The returned search result is: 
```
{
  "took": 26,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": -0.5682936,
    "hits": [
      {
        "_index": "my-index",
        "_id": "s1xJapQBZfij0Ahq54L5",
        "_score": -0.5682936,
        "_source": {
          "text": "Dog training classes"
        }
      }
    ]
  }
}
```

The score of the document is < 0. 

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by pmpailis**
It is valid for some rerankers to return negative scores, so in this PR we add a normalization step for the final scores, to ensure that all scores are >=0, as Lucene assumes that all scores should be positive. 

The normalization function that we'll apply is the following: 
```
score = max(score, 0) + min(exp(score), 1)
```
which will ensure that all positive scores lie in the `[1, inf)` while negative values will be projected to `(0, 1)`

Closes https://github.com/elastic/elasticsearch/issues/120201

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/retriever/rankdoc/RankDocsQuery.java [hunk 1]
```diff
@@ -160,7 +165,7 @@ public float getMaxScore(int docId) {
 
                         @Override
                         public float score() {
-                            return docs[upTo].score;
+                            return Math.max(docs[upTo].score, Float.MIN_VALUE);
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/retriever/rankdoc/RankDocsQuery.java:168]: why are you doing this? The ctor of the query already disallows negative values.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java [hunk 2]
```diff
@@ -130,10 +131,14 @@ protected void computeScores(RankFeatureDoc[] featureDocs, ActionListener<float[
...
-            .sorted(Comparator.comparing((RankFeatureDoc doc) -> doc.score).reversed())
-            .toArray(RankFeatureDoc[]::new);
+        List<RankFeatureDoc> docs = new ArrayList<>();
+        for (RankFeatureDoc doc : originalDocs) {
+            if (minScore == null || doc.score >= minScore) {
+                doc.score = normalizeScore(doc.score);
+                docs.add(doc);
+            }
+        }
+        return docs.stream().sorted(Comparator.comparing((RankFeatureDoc doc) -> doc.score).reversed()).toArray(RankFeatureDoc[]::new);
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/rank/textsimilarity/TextSimilarityRankFeaturePhaseRankCoordinatorContext.java:141]:
```
docs.sort(RankFeatureDoc::compareTo);
return docs.toArray(new RankFeatureDoc[0]);
```
Why not this? Seems way easier to read and avoids streams, which we know can cause way too much garbage.

**Review by benwtrent — COMMENTED** [review]
This is looking good to me. One minor question on the scoredoc query.

File: server/src/main/java/org/elasticsearch/search/retriever/rankdoc/RankDocsQuery.java (hunk 1 above)
Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/search/retriever/rankdoc/RankDocsQuery.java:168]: Discussed this briefly with @jimczi as well. The main idea for this change was because the minmax normalizer would output a 0 score for the lowest scoring doc by default, and we'd want to still differentiate between a 0 that would still be a valid top doc (from the `RankDocs`) compared to the tail docs that would also get a score of 0 due to filtering etc.  Happy to discuss any alternatives :)

Comment (benwtrent) [reply server/src/main/java/org/elasticsearch/search/retriever/rankdoc/RankDocsQuery.java:168]: @pmpailis understood. Please add a comment to this change as its unintuitive.

Comment (pmpailis) [reply server/src/main/java/org/elasticsearch/search/retriever/rankdoc/RankDocsQuery.java:172]: Added in a78290d9fd0e12a8fa6d8010b9ef41bbd8a9df15

**Review by benwtrent — APPROVED** [review]
🥾
🐛 

Bug squashed
