### PR TITLE
[Security] Check auth scheme case insensitively

### LINKED ISSUE #31486: Authentication scheme in authorization header must be case insensitive
**Elasticsearch version** (`bin/elasticsearch --version`): 
All versions affected

**Plugins installed**: []

**JVM version** (`java -version`):
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin X 17.6.0 Darwin Kernel Version 17.X.X: Tue May  X X:22:16 X 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
According to [RFC 7617](https://tools.ietf.org/html/rfc7617), the authorization scheme should not be case sensitive; thus BASIC, or Basic, or basic are all valid.
Applicable to bearer token where "Bearer " auth scheme is used. Ref:  [RFC 6750](https://tools.ietf.org/html/rfc6750) [RFC 7235](https://tools.ietf.org/html/rfc7235#page-10) 
> Note that both scheme and parameter names are matched case-
   insensitively.

**Steps to reproduce**:

Following example invocations fail:
curl -k -v -H "Authorization: basic ZW..." https://es.demo.local:9200/_xpack?pretty
curl -k -v -H "Authorization: BASIC ZW..." https://es.demo.local:9200/_xpack?pretty
curl -k -H "Authorization: bearer wZ+..." https://es.ipademo.local:9200/_xpack?pretty

Workaround: "Basic "/"Bearer " works, depends on HTTP client used if it allows to use this in `Authorization: ` header.

**Provide logs (if relevant)**: NA

### PR DESCRIPTION
**Pull request by bizybot**
According to [RFC 7617](https://tools.ietf.org/html/rfc7617), the `Basic` authentication scheme name should not be case sensitive.
Case insensitive comparisons are also applicable for bearer tokens where `Bearer` authentication scheme is used as per [RFC 6750](https://tools.ietf.org/html/rfc6750) and [RFC 7235](https://tools.ietf.org/html/rfc7235#page-10)

Some Http clients may send authentication scheme names in different case types for eg. `Basic`
`basic`, `BASIC`, `BEARER` etc., so the lack of case-insensitive check is an issue when these clients try to authenticate with elasticsearch. This commit adds case-insensitive checks for `Basic ` and `Bearer ` authentication schemes.

Closes #31486

### CODE REVIEW

**Comment by jaymode** [comment]
@bizybot we need a better description for this PR.

> the authorization scheme 

this should be `the 'Basic' authentication scheme`.

> Applicable to bearer tokens

This is only a partial thought. We need complete thoughts like `Case insensitive comparisons are also applicable for bearer tokens where the 'Bearer' authentication scheme is used per RFC 6750 and RFC 7235.`

> This is problem for some of HTTP clients using values like
BASIC, basic, BEARER etc.

There is a lot of ambiguity here IMO. Maybe: Clients may send values in various casing, such as Basic, basic, BEARER, Bearer, etc, so the lack of a case insensitive check is an issue when these clients try to authenticate with elasticsearch.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java [hunk 1]
```diff
@@ -1007,9 +1007,9 @@ private void maybeStartTokenRemover() {
      */
     private String getFromHeader(ThreadContext threadContext) {
         String header = threadContext.getHeader("Authorization");
-        if (Strings.hasLength(header) && header.startsWith("Bearer ")
+        if (Strings.hasText(header) && header.regionMatches(true, 0, "Bearer ", 0, "Bearer ".length())
                 && header.length() > "Bearer ".length()) {
-            return header.substring("Bearer ".length());
+            return header.substring("Bearer ".length()).trim();
```
Comment (jaymode) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java]: Is the trimming per the RFC? If so, we should add a test for this.

Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java]: I added it as it was referring to RFC 2617 but other than that I could not find explicit mention of this as a requirement so I will remove it.

**Review by jaymode — APPROVED** [review]
LGTM. Please make sure the title and commit message are correct when merging.
