### PR TITLE
Fix RemoteClusterSecurityRestIT by waiting for tasks to finish

### LINKED ISSUE #128009: [CI] RemoteClusterSecurityRestIT testTaskCancellation failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8130 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/5opzyp5aw3ymi)
- [elasticsearch-pull-request #71305 / part-4](https://gradle-enterprise.elastic.co/s/hcv6kl4zj65vy)
- [elasticsearch-pull-request #71273 / part-4](https://gradle-enterprise.elastic.co/s/psnjlcecs4lpc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:qa:multi-cluster:javaRestTest" --tests "org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT.testTaskCancellation" -Dtests.seed=E6B6B03B46085FD5 -Dtests.locale=ar-LY -Dtests.timezone=Europe/Zagreb -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testTaskCancellation),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:33671], URI [/_cluster/settings], status line [HTTP/1.1 200 OK]
Warnings: [Index [.async-search] name begins with a dot (.), which is deprecated, and will not be allowed in a future Elasticsearch version.]
:)
úacknowledged#persistentúûtransientúûû
```

**Issue Reasons:**
- [main] 3 failures in test testTaskCancellation (2.5% fail rate in 122 executions)
- [main] 2 failures in step part-4 (3.3% fail rate in 60 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (3.3% fail rate in 60 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by benchaplin**
Will fix https://github.com/elastic/elasticsearch/issues/128009 if the issue is that still running search tasks recreate the .async-search index after the test is complete, interfering with cleanup.

### CODE REVIEW

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java [hunk 1]
```diff
@@ -308,6 +308,27 @@ public void testTaskCancellation() throws Exception {
...
+                        false
+                    );
+                    AtomicBoolean searchTasksFound = new AtomicBoolean(false);
+                    selectTasksWithOpaqueId(responseMap, asyncSearchOpaqueId, task -> {
+                        if (task.get("action") instanceof String action && action.contains("indices:data/read/search")) {
+                            searchTasksFound.set(true);
+                        }
+                    });
+                    assertFalse("Expected no search tasks to be running", searchTasksFound.get());
+                } catch (IOException e) {
```
Comment (smalyshev) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: Not sure why exactly try/catch here would be needed - `assertBusy` allows checked exceptions and seems to handle them properly?

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java [hunk 2]
```diff
@@ -308,6 +308,27 @@ public void testTaskCancellation() throws Exception {
...
+                    assertOK(queryingClusterTasks);
+                    Map<String, Object> responseMap = XContentHelper.convertToMap(
+                        JsonXContent.jsonXContent,
+                        EntityUtils.toString(queryingClusterTasks.getEntity()),
+                        false
+                    );
+                    AtomicBoolean searchTasksFound = new AtomicBoolean(false);
+                    selectTasksWithOpaqueId(responseMap, asyncSearchOpaqueId, task -> {
+                        if (task.get("action") instanceof String action && action.contains("indices:data/read/search")) {
+                            searchTasksFound.set(true);
```
Comment (smalyshev) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: Can't we just fail right here?

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java (hunk 1 above)
Comment (benchaplin) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: I saw the pattern earlier in the test and understood it this way: this code may make repeated network requests, and `performRequest` throwing `IOException` indicates a network problem which means we should fail fast.

Comment (smalyshev) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: But from what I can see `assertBusy` would pass through `IOException` anyway, it only catches `AssertionError`.

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java (hunk 2 above)
Comment (benchaplin) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: I'm expecting there may exist search tasks (with cancelled: true) at this stage. I want to wait for them to disappear as I believe they're the ones creating the .async-search index.

Comment (smalyshev) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: Yes, I understand. The question is why you need to set `searchTasksFound` and then check it instead of calling `fail()` right here if you found the non-disappeared task?

Comment (benchaplin) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: Ah I see what you mean, I thought you meant fail the whole test itself. Thanks for the note, definitely cleaner to use `fail()` - I'll make the change!

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java (hunk 1 above)
Comment (benchaplin) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: Good point, I just tested and it doesn't treat IOException and RuntimeException any differently. Let me poke around and see if the pattern has any other use else I'll remove it.

Comment (benchaplin) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: I think it's nice _not_ to throw the exception and fail the test for potentially transient network errors, so I've refactored this to catch ResponseExceptions and `fail` in that case.

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java [hunk 3]
```diff
@@ -308,6 +308,25 @@ public void testTaskCancellation() throws Exception {
...
+                    Response queryingClusterTasks = adminClient().performRequest(new Request("GET", "/_tasks"));
+                    assertOK(queryingClusterTasks);
+                    Map<String, Object> responseMap = XContentHelper.convertToMap(
+                        JsonXContent.jsonXContent,
+                        EntityUtils.toString(queryingClusterTasks.getEntity()),
+                        false
+                    );
+                    selectTasksWithOpaqueId(responseMap, asyncSearchOpaqueId, task -> {
+                        if (task.get("action") instanceof String action && action.contains("indices:data/read/search")) {
+                            fail();
```
Comment (smalyshev) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityRestIT.java]: I'd add a message here since if it actually fails (i.e. the timeout expires) for some weird reason, we'd want to know it was this place.

**Review by smalyshev — APPROVED** [review]

**Comment by benchaplin** [comment]
This actually doesn't need a backport, as https://github.com/elastic/elasticsearch/pull/127799 caused the tests to begin failing and it was not backported to 9.0.

**Comment by DaveCTurner** [comment]
Backporting this to 8.19 in https://github.com/elastic/elasticsearch/pull/156598 - see https://github.com/elastic/elasticsearch/issues/156573.
