### PR TITLE
Retry shard movements during ESQL query

### LINKED ISSUE #125947: [CI] ManyShardsIT testCancelUnnecessaryRequests failing
**Build Scans:**
- [elasticsearch-periodic #7349 / openjdk23_entitlements_false_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/z6liemop2vxu4)
- [elasticsearch-pull-request #65500 / part-3](https://gradle-enterprise.elastic.co/s/sltclf5h3hah4)
- [elasticsearch-periodic-platform-support #7252 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/gm6srf2zlnp7u)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.ManyShardsIT.testCancelUnnecessaryRequests" -Dtests.seed=2B36B5E6A61236E2 -Dtests.jvm.argline="-Des.entitlements.enabled=false" -Dtests.locale=tt-RU -Dtests.timezone=America/Belize -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.ManyShardsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCancelUnnecessaryRequests),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 3 failures in test testCancelUnnecessaryRequests (0.3% fail rate in 871 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by idegtiarenko**
Today we fail entire query if a shard is unavailable (because it has moved to another node) and there are no other shard copies to retry the query. 

This change schedules another shard location resolution round in such cases in order to not fail the query.

Closes: #125947

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 1]
```diff
@@ -281,6 +306,13 @@ public void onSkip() {
                     onResponse(new DataNodeComputeResponse(List.of(), Map.of()));
                 }
             }
+
+            private void maybeScheduleRetry(ShardId shardId, Exception e) {
+                if (targetShards.getShard(shardId).remainingNodes.isEmpty()
+                    && unwrapFailure(e) instanceof NoShardAvailableActionException) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:312]: This relies on `org.elasticsearch.xpack.esql.plugin.DataNodeRequestSender#unwrapFailure` that uses

https://github.com/elastic/elasticsearch/blob/a59c182f9f7e9d1bf3d6eecbc0e44f24ff91d053/server/src/main/java/org/elasticsearch/action/support/TransportActions.java#L22-L30

Probably this should only retry ShardNotFoundException/NoShardAvailableActionException/UnavailableShardsException. Not sure. Please let me know what do you think.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+                ExchangeService.OPEN_EXCHANGE_ACTION_NAME,
+                (handler, request, channel, task) -> {
+                    // move index shard
+                    if (shouldMove.compareAndSet(true, false)) {
+                        var currentShardNodeId = clusterService().state()
+                            .routingTable()
+                            .index(index)
+                            .shard(0)
+                            .primaryShard()
+                            .currentNodeId();
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:68]: I need to check if this could be replaced by a proper API call instead

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+                        ensureGreen("index-1");
+                    }
+                    // execute data node request
+                    handler.messageReceived(request, channel, task);
+                }
+            );
+        }
+
+        try (EsqlQueryResponse resp = run("FROM " + randomFrom("index-1,index-2", "index-*"))) {
+            assertThat(getValuesList(resp), hasSize(2));
```
Comment (nik9000) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:94]: Do we send back the node id that we ran the driver on when we `profile`? Could we add that as a double check?

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+
+import java.util.Collection;
+import java.util.concurrent.atomic.AtomicBoolean;
+
+import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.as;
+import static org.elasticsearch.xpack.esql.EsqlTestUtils.getValuesList;
+import static org.hamcrest.Matchers.hasSize;
+
+public class DataNodeRequestSenderIT extends AbstractEsqlIntegTestCase {
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:30]: Can we make this test similar to SearchWhileRelocatingIT? We continue running ES|QL on one thread while moving shards back and forth between two sets of nodes.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 5]
```diff
@@ -236,11 +247,28 @@ private List<ShardSearchFailure> selectFailures() {
...
             void onAfter(List<DriverProfile> profiles) {
                 nodePermits.get(request.node).release();
                 if (concurrentRequests != null) {
                     concurrentRequests.release();
                 }
+
+                if (pendingRetries.isEmpty() == false && remainingTargetShardSearchAttempts.decrementAndGet() > 0) {
+                    ongoingTargetShardResolutionAttempts.incrementAndGet();
+                    var indices = pendingRetries.stream().map(ShardId::getIndexName).distinct().toArray(String[]::new);
+                    searchShards(indices, pendingRetries::contains, computeListener.acquireAvoid().delegateFailure((l, newSearchShards) -> {
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:262]: I think we need to make changes to the search_shards API to allow bypassing can_match in this case. We only need the up-to-date routing table here.

**Review by dnhatn — COMMENTED** [review]
I left two comments. Thanks @idegtiarenko

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 5 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:262]: Good point. I think we can have a separate action for it to make it simpler.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java (hunk 3 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:94]: I would like to avoid it. We do not really know source for each row nor where shards are currently allocated to.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java (hunk 4 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:32]: Added

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java (hunk 3 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:156]: :+1:

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+        // start shard movements
+        var rounds = randomIntBetween(1, 10);
+        var names = internalCluster().getNodeNames();
+        for (int i = 0; i < rounds; i++) {
+            for (String name : names) {
+                client().admin()
+                    .cluster()
+                    .prepareUpdateSettings(TEST_REQUEST_TIMEOUT, TEST_REQUEST_TIMEOUT)
+                    .setPersistentSettings(Settings.builder().put("cluster.routing.allocation.exclude._name", name))
+                    .get();
```
Comment (nik9000) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSenderIT.java:80]: Fun

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 7]
```diff
@@ -236,11 +244,27 @@ private List<ShardSearchFailure> selectFailures() {
...
+                    ongoingTargetShardResolutionAttempts.incrementAndGet();
+                    resolveShards(pendingRetries, computeListener.acquireAvoid().delegateFailure((l, resolutions) -> {
+                        for (var entry : resolutions.entrySet()) {
+                            targetShards.shards.get(entry.getKey()).remainingNodes.addAll(entry.getValue());
+                        }
+                        ongoingTargetShardResolutionAttempts.decrementAndGet();
+                        trySendingRequestsForPendingShards(targetShards, computeListener);
+                        l.onResponse(null);
+                    }));
+                }
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:266]: The other branch should be in else?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 8]
```diff
@@ -236,11 +244,27 @@ private List<ShardSearchFailure> selectFailures() {
...
                 nodePermits.get(request.node).release();
                 if (concurrentRequests != null) {
                     concurrentRequests.release();
                 }
+
+                if (pendingRetries.isEmpty() == false && remainingTargetShardSearchAttempts.getAndDecrement() > 0) {
+                    ongoingTargetShardResolutionAttempts.incrementAndGet();
+                    resolveShards(pendingRetries, computeListener.acquireAvoid().delegateFailure((l, resolutions) -> {
+                        for (var entry : resolutions.entrySet()) {
+                            targetShards.shards.get(entry.getKey()).remainingNodes.addAll(entry.getValue());
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:260]: Here we can execute the same target nodes up to 10 times if we hit failed on that node (with unavailable)?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 9]
```diff
@@ -433,7 +461,7 @@ void searchShards(
                     skippedShards++;
                     continue;
                 }
-                List<DiscoveryNode> allocatedNodes = new ArrayList<>(group.allocatedNodes().size());
+                List<DiscoveryNode> allocatedNodes = Collections.synchronizedList(new ArrayList<>(group.allocatedNodes().size()));
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:464]: I wonder if we should make the logic that resolves the new target nodes a helper method and call it under sendingLock to avoid handling concurrency.

**Review by dnhatn — COMMENTED** [review]
I have some more comments. Thanks @idegtiarenko.

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchShardsAction.java [hunk 10]
```diff
@@ -131,11 +131,8 @@ public void searchShards(Task task, SearchShardsRequest searchShardsRequest, Act
             listener.delegateFailureAndWrap((delegate, searchRequest) -> {
                 Index[] concreteIndices = resolvedIndices.getConcreteLocalIndices();
                 final Set<ResolvedExpression> indicesAndAliases = indexNameExpressionResolver.resolveExpressions(
-
```
[the remark this answers is not in the document]
Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/action/search/TransportSearchShardsAction.java:134]: Yeap, looks like a leftover after merging https://github.com/elastic/elasticsearch/commit/2adb36e109706633ca8754e91edcfcfcffaf9bfe#diff-e9bf1f63e5fb1069f6fd3e4a7fb3b1fa44ff67a60c10dd9bb5f74caa40f2f3e3

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 7 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:266]: Not necessary. We could make progress without waiting for the moved shard(s) resolution in case there are other shards in queue.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 8 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:260]: I do not follow. If the shard is unavailable it should no longer be in the routing table and should not be passed here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResolveNodesAction.java [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+    protected void doExecute(Task task, ResolveNodesRequest request, ActionListener<ResolveNodesResponse> listener) {
+        ActionListener.completeWith(listener, () -> {
+            var project = projectResolver.getProjectState(clusterService.state());
+            var nodes = Maps.<ShardId, List<DiscoveryNode>>newMapWithExpectedSize(request.shardIds.size());
+            for (var shardId : request.shardIds) {
+                nodes.put(
+                    shardId,
+                    project.routingTable()
+                        .shardRoutingTable(shardId)
+                        .allShards()
```
[the remark this answers is not in the document]
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResolveNodesAction.java:72]: I guess it is possible, although would require a bit more dependency management to bring ClusterService and ProjectResolver to DataNodeRequestSender

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 12]
```diff
@@ -466,4 +509,25 @@ void searchShards(
             new ActionListenerResponseHandler<>(searchShardsListener, SearchShardsResponse::new, esqlExecutor)
         );
     }
+
+    void resolveShards(Set<ShardId> shardIds, ActionListener<Map<ShardId, List<DiscoveryNode>>> listener) {
+        ActionListener.completeWith(listener, () -> doResolveShards(shardIds));
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:514]: Can we just return this without listener?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 13]
```diff
@@ -242,11 +256,25 @@ private List<ShardSearchFailure> selectFailures() {
...
+
             void onAfter(DriverCompletionInfo info) {
                 nodePermits.get(request.node).release();
                 if (concurrentRequests != null) {
                     concurrentRequests.release();
                 }
+
+                if (pendingRetries.isEmpty() == false && remainingTargetShardSearchAttempts.getAndDecrement() > 0) {
+                    ongoingTargetShardResolutionAttempts.incrementAndGet();
+                    resolveShards(pendingRetries, computeListener.acquireAvoid().delegateFailure((l, resolutions) -> {
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:270]: Can we move this retry to `trySendingRequestsForPendingShards` under sendingLock to avoid handling concurrency?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 8 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java]: Here we are using the cluster state on the coordinator, which might not be up to dated.

**Review by dnhatn — COMMENTED** [review]
Thanks @idegtiarenko.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 8 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java]: This is generally okay as we are going to retry more than once. 
We could make it transport action again and run on elected master by extending `TransportMasterNodeAction` but even then there is always a possibility of state changing while we waiting for the response.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java (hunk 13 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:270]: This is possible in principle, but this would block sending more requests while resolving failure. We do not need to do that necessary

**Review by dnhatn — APPROVED** [review]
Talked to @idegtiarenko offline. He will make changes to address the race condition between retry and sendingRequests. With the upcoming changes, the PR should be good to go. Thank you for all the iterations!
