### PR TITLE
Ensure error handler is called during SLM retention callback failure

### LINKED ISSUE #55217: SnapshotRetentionTask#getAllRetainableSnapshots Exception Handling is Broken
If the callback used in this method encounters an exception (possible to trigger by e.g. concurrently deleting a repository but I bet there's lots of other possible ways of getting there via repo IO issues) then the `running` flag (https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java#L69) is never set to `false` again, apparently breaking SLM on a node until it is restarted because all future retention tasks will just be skipped.
We need to properly handle exceptions throughout to make sure we can't leak a state that doesn't return the flag to `false` right? (see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java#L274 which can throw for the exact broken spot)

### PR DESCRIPTION
**Pull request by dakrone**
When retrieving the snapshots for a set of repos or deleting a single snapshot, it's possible for
the body of the `ActionListener`'s `onResponse` method to throw an Exception. In this case, the
`errHandler` passed in may not be executed, resulting in the `running` boolean not being reset back
to false.

This commit uses `ActionListener.wrap(...)` instead of creating a new ActionListener, which ensures
that if the `onResponse` fails in any way, the `onFailure` handler is still called.

Resolves #55217

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotRetentionTaskTests.java [hunk 1]
```diff
@@ -375,6 +384,114 @@ public void testOkToDeleteSnapshots() {
...
+            task.getAllRetainableSnapshots(Collections.singleton(repoId), new ActionListener<>() {
+                @Override
+                public void onResponse(Map<String, List<SnapshotInfo>> stringListMap) {
+                    logger.info("--> forcing failure");
+                    throw new ElasticsearchException("forced failure");
+                }
+
+                @Override
+                public void onFailure(Exception e) {
+                    fail("we have another err handler that should have been called");
```
Comment (andreidan) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotRetentionTaskTests.java:429]: I found this confusing, but I see it's just how `getAllRetainableSnapshots` does the listener callback, so maybe it's a discussion we should have on a separate ocasion

**Review by andreidan — APPROVED** [review]
LGTM thanks for fixing this Lee

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotRetentionTaskTests.java (hunk 1 above)
Comment (dakrone) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotRetentionTaskTests.java:429]: Yeah, we can do that maybe in future work since it's technically not really a bugfix.
