### PR TITLE
Fix updating include_in_parent/include_in_root of nested field.

### LINKED ISSUE #53792: Change in `index_in_parent` doesn't work, but throws no error
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.6 / 7.6.0

**Description**:
Trying to change the value of `index_in_parent` seems to succeed, but doesn't.
I would expect that it is working as designed that that value cannot be changed, but I think it's a bug that no error is returned when trying to change it.

**Steps to Reproduce:**
```
PUT /parenttest
```
```
PUT /parenttest/_mapping/_doc
{
  "properties": {
    "email": {
      "type": "keyword"
    },

            "user" : {
                "type" : "nested",
                "include_in_parent": true,
                "properties": {
                    "first" : {"type": "text" },
                    "last"  : {"type": "text" }
                }
            }

  }
}
```
```
GET parenttest
```
```
PUT /parenttest/_mapping/_doc
{
  "properties": {
    "email": {
      "type": "keyword"
    },

            "user" : {
                "type" : "nested",
                "include_in_parent": false,
                "properties": {
                    "first" : {"type": "text" },
                    "last"  : {"type": "text" }
                }
            }

  }
}
```
```
GET parenttest
```

*Expected behaviour:*
The third `PUT` returns an error explaining that it's not possible to change the value of "include_in_parent"

*Observed Behaviour:*
None of the calls throws an error.
The second `GET` returns exactly the same data as the first.

### PR DESCRIPTION
**Pull request by gaobinlong**
Closes #53792 

The main changes are:

1. Throw an error when updating `include_in_parent` or `include_in_root` attribute of nested field dynamically by the PUT mapping API.
2. Add a test for the change.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 1]
```diff
@@ -490,6 +490,16 @@ private static void checkEnabledFieldChange(ObjectMapper mergeWith, Mapper merge
                 final String path = mergeWith.fullPath() + "." + mergeWithObjectMapper.simpleName() + ".enabled";
                 throw new MapperException("Can't update attribute for type [" + path + "] in index mapping");
             }
+
+            if (mergeIntoObjectMapper.nested().isIncludeInParent() != mergeWithObjectMapper.nested().isIncludeInParent()) {
+                final String path = mergeWith.fullPath() + "." + mergeWithObjectMapper.simpleName() + ".include_in_parent";
+                throw new MapperException("Can't update attribute for type [" + path + "] in index mapping");
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: I think a message like this would be clearer: "Merging mappings failed for the [user] field: the [include_in_parent] parameter cannot be updated."

File: server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 2]
```diff
@@ -742,4 +743,36 @@ public void testReorderParent() throws IOException {
         assertThat(doc.docs().get(1).get("nested1.field2"), equalTo("4"));
         assertThat(doc.docs().get(2).get("field"), equalTo("value"));
     }
+
+    public void testMergeNestedMappings() {
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: It's great that you put together a real unit test. But for consistency with the rest of this class and how we currently test mapping behavior, we should perform these checks using higher-level services like `MapperService`. You can take a look at `testParentObjectMapperAreNested` in this class for a simple example. The test case `testLimitOfNestedFieldsPerIndex` shows how to merge in a new mapping.

**Review by jtibshirani — COMMENTED** [review]
Thanks @gaobinlong for the contribution! I left a couple comments.

File: server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 3]
```diff
@@ -742,4 +742,40 @@ public void testReorderParent() throws IOException {
         assertThat(doc.docs().get(1).get("nested1.field2"), equalTo("4"));
         assertThat(doc.docs().get(2).get("field"), equalTo("value"));
     }
+
+    public void testMergeNestedMappings() throws  IOException {
+        MapperService mapperService = createIndex("index1", Settings.EMPTY, jsonBuilder().startObject()
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java:747]: Instead of creating two different indices, then merging the object mappers, I think it would be more realistic to create one index, then call `MapperService.merge` with a mapping update. You can look at `testLimitOfNestedFieldsPerIndex` in this class for an example of how to perform the merge.

**Review by jtibshirani — COMMENTED** [review]
The new structure looks good, I have one last comment about the test. I'll kick off CI to check that all tests pass.

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by gaobinlong** [comment]
@jtibshirani, I have pushed a new commit, can you take a look at the change?

File: server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 4]
```diff
@@ -742,4 +742,43 @@ public void testReorderParent() throws IOException {
...
+
+    public void testMergeNestedMappings() throws IOException {
+        MapperService mapperService = createIndex("index1", Settings.EMPTY, jsonBuilder().startObject()
+            .startObject("properties")
+                .startObject("nested1")
+                    .field("type", "nested")
+                .endObject()
+            .endObject().endObject()).mapperService();
+
+        Function<String, String> mapping1 = type -> {
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java:754]: Let's try to simplify this part:
* We can remove the 'supplier' function, and just define a `String` mapping directly.
* There's no need to catch and rewrap the `IOException`, since this method includes `throws IOException` in its signature.

I see that you took inspiration from `testLimitOfNestedFieldsPerIndex` -- apologies that the method wasn't the best example.

**Review by jtibshirani — COMMENTED** [review]
One last comment, thanks for your patience on this review.

File: server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java (hunk 4 above)
Comment (gaobinlong) [reply server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java:754]: OK, I will change that.

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Review by jtibshirani — APPROVED** [review]
Looks good to me! I will merge and backport to 7.x, along with a note in the migration docs.
