### PR TITLE
Always use CacheService for caching metadata blobs

### LINKED ISSUE #70728: SearchableSnapshotDirectoryStatsTests failures
Some searchable snapshots tests are failing today:

**Build scan**:
https://gradle-enterprise.elastic.co/s/rkhnksundfwxy
https://gradle-enterprise.elastic.co/s/qg2pyjp2w5ie4/

**Repro line**:

./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryStatsTests.testReadBytesContiguously" -Dtests.seed=BFE4833CEC7197EF -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=America/El_Salvador -Druntime.java=8

./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryStatsTests.testCachedBytesReadsAndWrites" -Dtests.seed=BFE4833CEC7197EF -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=America/El_Salvador -Druntime.java=8

**Applicable branches**: master and 7.x

### LINKED ISSUE #70763: Failure in CachedBlobContainerIndexInputTests.testRandomReads
**Build scan**: https://gradle-enterprise.elastic.co/s/3g6dnmunvdxgw

**Repro line**: `./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads" -Dtests.seed=B14197630B410474 -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=America/Indiana/Indianapolis -Druntime.java=11`

**Reproduces locally?**: Yes

**Applicable branches**: master

**Failure history**: So far, just once on 3/23/21

**Failure excerpt**:

```

java.lang.AssertionError: Expected at most 1 ranges fetched from the source |  
-- | --
   | Expected: a value less than or equal to <1L> |  
   | but: <2L> was greater than <1L>

at __randomizedtesting.SeedInfo.seed([B14197630B410474:84433590E1EDA05E]:0) |  
-- | --
   |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
   |   | at org.junit.Assert.assertThat(Assert.java:956) |  
   |   | at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads(CachedBlobContainerIndexInputTests.java:148)


```

### PR DESCRIPTION
**Pull request by ywelsch**
This PR unifies CachedBlobContainerIndexInput and FrozenIndexInput so that they share the same infrastructure for caching metadata blobs as well as header and footer ranges for data blobs. The idea is to always use CacheService for this, which does not evict the metadata, and which efficiently stores the information on disk (using sparse file support).

This also allows us to align writes in FrozenCacheService to 4KB block sizes in this PR, which addresses an issue when reusing regions from the shared cache, as writes that are not aligned on page cache boundaries causes the existing data (which we don't care about) to be loaded from disk, which comes with a dramatic performance penalty.

In a follow-up, we should also add a test / bootstrap check that ensures that sparse file support is always provided.

Closes #70728
Closes #70763

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java [hunk 1]
```diff
@@ -83,13 +57,13 @@ public FrozenIndexInput(
             0L,
             0L,
             fileInfo.length(),
+            new CacheFileReference(directory, fileInfo.physicalName(), fileInfo.length()),
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:60]: I'm a bit torn on the file's length that is passed here. It means that we'll create a potentially large file in the cache service (and cause potential evictions) while we know it will only be used to cache at most `directory.getBlobCacheByteRange(name, fileInfo.length()).length()` bytes. We could maybe affine this?

**Review by tlrx — COMMENTED** [review]
This change makes sense to me. I've done a first pass and left some comments.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java (hunk 1 above)
Comment (ywelsch) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:60]: Note that CacheService is always supposed to be unbounded (and that's how it should be, the goal is to remove the undocumented setting to even make this configurable, and remove the complexity around that)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/MetadataCachingIndexInput.java [hunk 2]
```diff
@@ -0,0 +1,480 @@
...
+        this.recoveryRangeSize = recoveryRangeSize;
+        this.lastReadPosition = offset;
+        this.lastSeekPosition = offset;
+        assert offset >= compoundFileOffset;
+        assert getBufferSize() <= BlobStoreCacheService.DEFAULT_CACHED_BLOB_SIZE; // must be able to cache at least one buffer's worth
+    }
+
+    @Override
+    protected void doReadInternal(ByteBuffer b) throws IOException {
+        final long position = getAbsolutePosition();
```
[the remark this answers is not in the document]
Comment (ywelsch) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/MetadataCachingIndexInput.java:95]: I've addressed the other comments here, but I'm not yet sure how to go about this one. I've pushed aaa69e6 which removes the virtual file logic from FrozenCacheService and which simplifies things a bit further when it comes to position calculations (same for FrozenIndexInput as well as CachedBlobContainerIndexInput now).

**Comment by ywelsch** [comment]
@elasticmachine run elasticsearch-ci/2 (timeout downloading stuff from the internet)

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsPrewarmingIntegTests.java [hunk 3]
```diff
@@ -304,6 +300,21 @@ public void testConcurrentPrewarming() throws Exception {
...
+    @After
+    public void resetTracker() {
+        getTrackingRepositoryPlugin().clear();
+    }
+
+    private TrackingRepositoryPlugin getTrackingRepositoryPlugin() {
+        TrackingRepositoryPlugin tracker = null;
+        for (RepositoryPlugin plugin : getInstanceFromNode(PluginsService.class).filterPlugins(RepositoryPlugin.class)) {
+            if (plugin instanceof TrackingRepositoryPlugin) {
+                tracker = ((TrackingRepositoryPlugin) plugin);
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsPrewarmingIntegTests.java:312]: nit: return here directly

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsUuidValidationIntegTests.java [hunk 4]
```diff
@@ -33,6 +34,7 @@
 import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
 import static org.hamcrest.Matchers.containsString;
 
+@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST)
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsUuidValidationIntegTests.java:37]: There is a single test in this class, why changing the scope to TEST?

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java (hunk 1 above)
Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:60]: Right, I forgot about that point. Also my suggestion was pretty bad since the file length here passed to the sparse file tracker and that would just break things. Sorry for the noise.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java [hunk 5]
```diff
@@ -102,48 +76,46 @@ private FrozenIndexInput(
...
-    private ByteRange computeRange(long position) {
-        final long rangeSize = getDefaultRangeSize();
-        long start = (position / rangeSize) * rangeSize;
-        long end = Math.min(start + rangeSize, frozenCacheFile.getLength());
-        return ByteRange.of(start, end);
-    }
-
     @Override
-    protected void doReadInternal(ByteBuffer b) throws IOException {
-        ensureContext(ctx -> ctx != CACHE_WARMING_CONTEXT);
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:139]: :+1:

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java [hunk 6]
```diff
@@ -591,33 +324,32 @@ private void writeCacheFile(
...
+                // add the remaining bytes to buf
+                buf.put(copyBuffer, bytesToAdd, bytesRead - bytesToAdd);
+            } else {
+                buf.put(copyBuffer, 0, bytesRead);
             }
-            buf.put(copyBuffer, 0, bytesRead);
             remaining -= bytesRead;
         }
+        // ensure that last write is aligned on 4k boundaries (= page size)
+        final int off = buf.position() % SharedBytes.PAGE_SIZE;
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:342]:
```suggestion
        final int remainder = buf.position() % SharedBytes.PAGE_SIZE;
```

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java [hunk 7]
```diff
@@ -591,33 +324,32 @@ private void writeCacheFile(
...
+        final int adjustment = off == 0 ? 0 : SharedBytes.PAGE_SIZE - off;
+        buf.position(buf.position() + adjustment);
         long bytesWritten = positionalWrite(fc, fileChannelPos + bytesCopied, buf);
-        bytesCopied += bytesWritten;
+        bytesCopied += (bytesWritten - adjustment); // adjust to not break RangeFileTracker
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:346]: Maybe the stats should show the exact bytes copied (ie we can confirm the 4K alignment) but progress updater got updated with the adjusted bytes copied?

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/MetadataCachingIndexInput.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/MetadataCachingIndexInput.java:95]: Ok, let's keep it as it is. I'll give it a try.

**Review by tlrx — APPROVED** [review]
LGTM - I've left only minor things along the review, feel free to apply or ignore

File: x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsUuidValidationIntegTests.java (hunk 4 above)
Comment (ywelsch) [reply x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsUuidValidationIntegTests.java:37]: It's because when you run the test with `tests.iters=x`, it will reuse the same node, and that breaks the test (RestoreBlockingActionFilter.executed and unblocked are not reset)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java (hunk 7 above)
Comment (ywelsch) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java:346]: ++

Comment (ywelsch) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/FrozenIndexInput.java]: I will defer that to a follow-up as it will break a lot of tests (again)
