### PR TITLE
Permit overwritten blobs to be missing

### LINKED ISSUE #69087: FsSnapshotRepoTestKitIT#testRepositoryAnalysis can fail with repository_verification_exception
**Build scan**: https://gradle-enterprise.elastic.co/s/7sc5twij3b5bc

**Repro line**:
```
./gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:rest:integTest' --tests "org.elasticsearch.repositories.blobstore.testkit.rest.FsSnapshotRepoTestKitIT.testRepositoryAnalysis" -Dtests.seed=9A24749B69423ACF -Dtests.security.manager=true -Dtests.locale=ca -Dtests.timezone=Etc/GMT-10 -Druntime.java=11
```

**Reproduces locally?**: no

**Applicable branches**: master, maybe 7.x

**Failure history**: the test was introduced recently in https://github.com/elastic/elasticsearch/pull/67247

**Failure excerpt**:
```
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] [GetRepositoryBlobChecksumRequest{retrieve [176717-217691] from [repository:temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q/test-blob-6-riacINAwRK6-fjhy0-wb3w]}] (after write complete) failed on node [{integTest-0}{uflyZK1jTICL2L5Ki5ZpcA}{DWnV16kqRXCSJm3OfzQ2xg}{127.0.0.1}{127.0.0.1:43743}{cdfhilmrstw}{ml.machine_memory=101362774016, xpack.installed=true, transform.node=true, testattr=test, ml.max_open_jobs=20, ml.max_jvm_size=518979584}]: blob not found"}],"type":"repository_verification_exception","reason":"[repository] analysis failed, you may need to manually remove [temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q]","caused_by":{"type":"repository_verification_exception","reason":"[repository] failure processing [blob analysis [repository:temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q/test-blob-6-riacINAwRK6-fjhy0-wb3w, length=262144, seed=5958866466975255369, readEarly=false, writeAndOverwrite=true]]","caused_by":{"type":"repository_verification_exception","reason":"[repository] [GetRepositoryBlobChecksumRequest{retrieve [176717-217691] from [repository:temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q/test-blob-6-riacINAwRK6-fjhy0-wb3w]}] (after write complete) failed on node [{integTest-0}{uflyZK1jTICL2L5Ki5ZpcA}{DWnV16kqRXCSJm3OfzQ2xg}{127.0.0.1}{127.0.0.1:43743}{cdfhilmrstw}{ml.machine_memory=101362774016, xpack.installed=true, transform.node=true, testattr=test, ml.max_open_jobs=20, ml.max_jvm_size=518979584}]: blob not found"}}},"status":500} |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([9A24749B69423ACF:6319D5F5B7D90926]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.repositories.blobstore.testkit.AbstractSnapshotRepoTestKitRestTestCase.testRepositoryAnalysis(AbstractSnapshotRepoTestKitRestTestCase.java:34) |  
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) |  
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today blob overwrites are not completely atomic, there is an
intermediate state in which the blob is missing, but the repository
analyser does not fully account for that intermediate state.

This commit relaxes the check for missing blobs if they were
overwritten.

Closes #69087

### CODE REVIEW

File: x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java [hunk 1]
```diff
@@ -368,20 +368,7 @@ private void readOnNodes(List<DiscoveryNode> nodes, boolean beforeWriteComplete)
...
-                                                + blobChecksumRequest
-                                                + "] (after write complete) failed on node ["
-                                                + node
-                                                + "]: blob not found"
-                                        )
-                                    );
-                                } else {
-                                    readNodesListener.onResponse(makeNodeResponse(node, beforeWriteComplete, response));
-                                }
+                                readNodesListener.onResponse(makeNodeResponse(node, beforeWriteComplete, response));
```
Comment (DaveCTurner) [inline x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java:371]: Note that we don't completely ignore the not-found case, we handle it correctly in `onReadsComplete()`:

https://github.com/elastic/elasticsearch/blob/f2c18d4d580921d7370b5c12fd9e5b053ba25c26/x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java#L473-L483

I added this extra check here during some testing and clearly forgot to remove it.

**Review by original-brownbear — APPROVED** [review]
LGTM, though we should still fix the way `FsRepository` does the overwriting IMO

**Comment by DaveCTurner** [comment]
> LGTM, though we should still fix the way FsRepository does the overwriting IMO

Indeed; at least now we know we can detect it in tests :)

**Review by fcofdez — APPROVED** [review]
LGTM, and +1 to fix the `FsRepository` behaviour
