### PR TITLE
[Transform] Exclude clusters in license check

### LINKED ISSUE #114509: [ML] Remote clusters can't be excluded using "-" from AD datafeed
**Version:** 
8.15.1

**Step to reproduce:**
1. Setup two remote clusters: cluster1, cluser2
2. Load kibana sample data on both remote cluster1 and remote cluster2
3. Create a dataview to exclude one of them: "*:kibana*,-cluster1:*"
4. Create a simple AD job using the above dataview
5. at the last step of AD job wizard, it will hit a no_such_remote_cluster_exception error:

```
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "[no_such_remote_cluster_exception\n\tRoot causes:\n\t\tno_such_remote_cluster_exception: no such remote cluster: [-cluster1]]: no such remote cluster: [-cluster1]",
  "attributes": {
    "body": {
      "error": {
        "root_cause": [
          {
            "type": "no_such_remote_cluster_exception",
            "reason": "no such remote cluster: [-cluster1]"
          }
        ],
        "type": "no_such_remote_cluster_exception",
        "reason": "no such remote cluster: [-cluster1]"
      },
      "status": 404
    }
  }
}
```

### LINKED ISSUE #114514: [ML] Transform: remote clusters can't be excluded using "-"
**Version:**
8.15.1

**Step to reproduce:**

1. Setup two remote clusters: cluster1, cluster2
2. Load kibana sample data on both remote cluster1 and remote cluster2
3. try transform _preview by excluding one of cluster using ""*:kibana*,-cluster1:*" as source index

```
POST _transform/_preview
{
      "source": {
        "index": [
          "*:kibana*,-cluster1:*"
        ]
   },
   "pivot": ...
}
```

**Observed:**

it will hit an error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Validation Failed: 1: no such remote cluster: [-cluster1];"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Validation Failed: 1: no such remote cluster: [-cluster1];"
  },
  "status": 400
}
```

**Workaround:**

1. don't use "-" to exclude, instead, explicitly include remotes by names
2. use a query to exclude remote clusters:
```
"bool": {
      "must_not": [
        {
          "terms": {
            "_index": [
              "cluster1:*"
            ]
          }
        }
      ]
    }
```

### PR DESCRIPTION
**Pull request by prwhelan**
When users specified `-` to exclude a cluster in the indices list, then remove the cluster alias from the license check.

Resolve #114514
Resolve #114509

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/license/RemoteClusterLicenseChecker.java [hunk 1]
```diff
@@ -264,20 +267,32 @@ public static List<String> remoteIndices(final Collection<String> indices) {
     /**
      * Extract the list of remote cluster aliases from the list of index names. Remote index names are of the form
      * {@code cluster_alias:index_name} and the cluster_alias is extracted (and expanded if it is a wildcard) for
-     * each index name that represents a remote index.
+     * each index name that represents a remote index. Exclusion patterns of the form {@code -cluster_alias:*} are
+     * handled by removing the corresponding clusters from the result.
```
Comment (valeriy42) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/license/RemoteClusterLicenseChecker.java:271]:
```suggestion
     * handled by removing the corresponding clusters from the result.
     * Exclusions are applied to the complete set of
     * included clusters regardless of their position in the list (order-independent).
```

**Review by valeriy42 — APPROVED** [review]
LGTM. One minor comment
