### PR TITLE
Use date format in `date_range` mapping before fallback to default

### LINKED ISSUE #29282: range filter on date_range datatype should use the format defined in the mapping
Tested on 6.2.3:

This is a Range query on a date field:

```
DELETE test
PUT test
{
  "mappings": {
    "_doc": {
      "properties": {
        "mydate": {
          "type": "date", 
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    }
  }
}
PUT test/_doc/1
{
  "mydate" : "2015-10-31 12:00:00"
}
GET test/_search
{
  "query": {
    "range": {
      "mydate": {
        "gte": "2015-10-31 12:00:00"
      }
    }
  }
}
```

This works well.

This is a Range query on a date_range field:

```
DELETE range_index
PUT range_index
{
  "mappings": {
    "_doc": {
      "properties": {
        "time_frame": {
          "type": "date_range", 
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    }
  }
}
PUT range_index/_doc/1
{
  "time_frame" : { 
    "gte" : "2015-10-31 12:00:00", 
    "lte" : "2015-11-01"
  }
}
GET range_index/_search
{
  "query" : {
    "range" : {
      "time_frame" : {
        "gte" : "2015-10-31 12:00:00",
        "lte" : "2015-11-01",
        "relation" : "within" 
      }
    }
  }
}
```

This is failing with:

```
      {
        "type": "parse_exception",
        "reason": "failed to parse date field [2015-10-31 12:00:00] with format [strict_date_optional_time||epoch_millis]"
      }
```

We can see that the format defined in the mapping is not used here. It should use `yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis` but it uses `strict_date_optional_time||epoch_millis`.

If we manually force the `format` to be the same as the `mapping`, then it works:

```
GET range_index/_search
{
  "query" : {
    "range" : {
      "time_frame" : {
        "gte" : "2015-10-31 12:00:00",
        "lte" : "2015-11-01",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||yyyy", 
        "relation" : "within" 
      }
    }
  }
}
```

I suggest that we try first to use the mapping defined for the field and fallback to the default one if needed.

cc @melvynator

### PR DESCRIPTION
**Pull request by liketic**
If the date format is not forced in query, use the format in mapping before fallback to the default format.

Closes #29282

### CODE REVIEW

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @liketic, yet another great PR, thanks for picking this up. I think the fix in RangeFieldMapper is good, however I'd like the test to be less generic and randomized. In its current form it seems to test all kinds of ranges (not only date), many versions etc. while I would be convinced more that the fix works if it would stick closer to the scenario described in #29282. I'd remove a lot of the randomization and make this test more specialized about the scenario described there I think.

File: server/src/test/java/org/elasticsearch/index/mapper/RangeFieldTypeTests.java [hunk 1]
```diff
@@ -84,20 +87,50 @@ public void testRangeQuery() throws Exception {
...
+        ShapeRelation relation = randomFrom(ShapeRelation.values());
+        DateTime from = DateTime.now();
+        DateTime to = DateTime.now().plusDays(DISTANCE);
+
+        // Test default date format
+        DateMathParser defaultParser = new DateMathParser(DateFieldMapper.DEFAULT_DATE_TIME_FORMATTER);
+        assertEquals(
+            RangeType.DATE.rangeQuery(FIELDNAME, true, from, to, true,
+                true, relation, null, defaultParser, context),
+            fieldType.rangeQuery(from, to, true, true, relation, null, null, context));
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/index/mapper/RangeFieldTypeTests.java]: I'm not sure what is tested here, can you explain? 
As far as I can see, `fieldType.rangeQuery` only redirects to `DATE#rangeQuery`, so other than checking if the parser gets picked up, this test is not doing much in my opinion, but I might miss something.
I'd prefer it it would check that the from/to values are parsed correctly using the parser supplied by `fieldType.setDateTimeFormatter`. For that I think the from/to values should be String representations of dates that DEFAULT_DATE_TIME_FORMATTER would reject otherwise. I'd like to see a test that checks that using the DEFAULT_DATE_TIME_FORMATTER we get an error (expectThrows) and with the right parser the query contains the expected min/max values. Accessing the min/max values of the Lucene query might be a bit tricky on first inspection of the code, but I think most shape relations should produce LongRange queries which Query can be cast to to use the getters.

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @liketic, thanks for reworking the test. I'm not sure I'm convinced about what the test does yet, I think currently it might not do the right thing (at the moment is passes with or without your change in the RangeFieldMapper). 
I hope the comment I left makes sense, happy to clear things up if you have questions.

**Comment by cbuescher** [comment]
@liketic checking in to see if we can get this PR in soon. The fix is fine I think, only the test needs some reworking as I mentioned in the comments. Let me know what you think and if you have time to get back to this in the next week or so.

**Comment by liketic** [comment]
@cbuescher My apologies for the delay. Thanks for your comments. I'll fix it before next week.

**Review by cbuescher — APPROVED** [review]
@liketic thanks a lot, this looks good to me. I will kick of a run of CI testing. There seems to be a new requirement to add changelog information to PRs that I'm not completely up to date with myself but I will come back with some info on what we need here (if anything).

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@liketic when you add the changelog, could you also merge in master once more, CI run didn't pass but its not related to this change I think.

**Comment by cbuescher** [comment]
@liketic I found out how to push to user PRs and added the changlog entry and merged in master, hope you don't mind.
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@liketic finally a green CI run. I merged this to master and will also port it to the 6.4 branch.

**Comment by liketic** [comment]
Thanks @cbuescher !
