### PR TITLE
Fix environment variable substitutions in list setting

### LINKED ISSUE #27926: Since Elasticsearch 6.1.0 environment variable substitutions in lists do not work
In elasticsearch 6.1.0 and 6.1.1 I can not use variable substitutions for x-pack related configuration in elasticsearch. Also mentioned here: https://discuss.elastic.co/t/x-pack-6-1-0-does-not-handle-variable-substitutions/111953
`
xpack:
  security:
    authc:
      realms:
          ssl:
            certificate_authorities: [ "${ELASTICSEARCH_CONFIG_PATH}/certs/myca.crt" ]
`
I am receiving:
`java.nio.file.NoSuchFileException: /app/volumes/config/${ELASTICSEARCH_CONFIG_PATH}/certs/myca.crt`
Last known working version is 6.0.1. I am quite surprised this bug passed release testing cycle so I tried to find if this is a feature but it seems it is not.

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Since Elasticsearch 6.1.0 environment variable substitutions in lists do not work
This commit fixes it.

Closes #27926

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java [hunk 1]
```diff
@@ -68,6 +68,17 @@ public void testReplacePropertiesPlaceholderSystemProperty() {
         assertThat(settings.get("setting1"), equalTo(value));
     }
 
+    public void testReplacePropertiesPlaceholderSystemPropertyList() {
+        String value = System.getProperty("java.home");
+        assertFalse(value.isEmpty());
+        Settings settings = Settings.builder()
+            .put("property.placeholder", value)
+            .putList("setting1", "${property.placeholder}", "${property.placeholder}")
+            .replacePropertyPlaceholders()
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java]: We have `replacePropertyPlaceholders(Function<String, String>)`; we use this rather than pulling from the same settings object as I think this will be a more realistic test?

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 2]
```diff
@@ -1210,10 +1211,23 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
...
                 Map.Entry<String, Object> entry = entryItr.next();
-                if (entry.getValue() == null || entry.getValue() instanceof List) {
+                if (entry.getValue() == null) {
                     // a null value obviously can't be replaced
                     continue;
                 }
+                if (entry.getValue() instanceof List) {
+                    List<String> ls = (List<String>) entry.getValue();
+                    ListIterator<String> li = ls.listIterator();
+                    while(li.hasNext()){
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Nit: spacing between `while` and `(`.

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 3]
```diff
@@ -1210,10 +1211,23 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
...
+                        String value = li.next();
+                        String value2 = propertyPlaceholder.replacePlaceholders(value, placeholderResolver);
+                        if (! value.equals(value2)){
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Nit: spacing between `!` and `value`.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Can we use a clearer name than `value2`?

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 4]
```diff
@@ -1210,10 +1211,23 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
             Iterator<Map.Entry<String, Object>> entryItr = map.entrySet().iterator();
             while (entryItr.hasNext()) {
                 Map.Entry<String, Object> entry = entryItr.next();
-                if (entry.getValue() == null || entry.getValue() instanceof List) {
+                if (entry.getValue() == null) {
                     // a null value obviously can't be replaced
                     continue;
                 }
+                if (entry.getValue() instanceof List) {
+                    List<String> ls = (List<String>) entry.getValue();
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: `ls` is never used again after the next line; do we need this local variable?

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 5]
```diff
@@ -1210,10 +1211,23 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
...
+                    ListIterator<String> li = ls.listIterator();
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Can this be a local final variable?

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 6]
```diff
@@ -1210,10 +1211,23 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
...
+                    while(li.hasNext()){
+                        String value = li.next();
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Can we use a clearer name than `value`?

File: core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java [hunk 7]
```diff
@@ -68,6 +68,17 @@ public void testReplacePropertiesPlaceholderSystemProperty() {
...
+            .build();
+        assertThat(settings.getAsList("setting1"), contains(value, value));
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java]: Can we test replacing different placeholders?

File: core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java [hunk 8]
```diff
@@ -68,6 +68,17 @@ public void testReplacePropertiesPlaceholderSystemProperty() {
         assertThat(settings.get("setting1"), equalTo(value));
     }
 
+    public void testReplacePropertiesPlaceholderSystemPropertyList() {
+        String value = System.getProperty("java.home");
+        assertFalse(value.isEmpty());
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java]: I don't think this will be needed if you take the suggestion below, but in general `assertFalse` and `assertTrue` should be avoided because they do not give good error messages (a failing expectation would only say `AssertionError`). Here, we could use `assertThat(value, not(isEmptyOrNullString())` as then the expectation would say

```
Expected: not (null or an empty string)
     but: was ""
```

which is a lot more helpful!

**Review by jasontedor — COMMENTED** [review]
Thanks @mayya-sharipova; the changes to production code look great I left a bunch of suggestions.

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java (hunk 5 above)
Comment (mayya-sharipova) [reply core/src/main/java/org/elasticsearch/common/settings/Settings.java]: +1 for `final`.  I am very clear what you meant by **local** ?  Do you recommend to declare `li` before the while loop on the line 1213?

File: core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java (hunk 8 above)
Comment (mayya-sharipova) [reply core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java]: thank you, this is very helpful to know

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java (hunk 5 above)
Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Sorry for not being clear. What I mean is that these variables (which are local variables, they only have scope of the current) block I think would clearer if they were final because they I know by the declaration they are never mutated instead of having to keep checking the code "is this the same object as when the variable was first declared?".

File: core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java [hunk 9]
```diff
@@ -69,14 +69,12 @@ public void testReplacePropertiesPlaceholderSystemProperty() {
...
     public void testReplacePropertiesPlaceholderSystemPropertyList() {
-        String value = System.getProperty("java.home");
-        assertFalse(value.isEmpty());
-        Settings settings = Settings.builder()
-            .put("property.placeholder", value)
-            .putList("setting1", "${property.placeholder}", "${property.placeholder}")
-            .replacePropertyPlaceholders()
+        final String hostname = randomAlphaOfLength(16);
+        final Settings settings = Settings.builder()
+            .putList("setting1", "${HOSTNAME}", "${HOSTNAME}")
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/common/settings/SettingsTests.java]: Can we use two different placeholders here to test that that works?

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 10]
```diff
@@ -1216,13 +1216,12 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
...
-                    while(li.hasNext()){
-                        String value = li.next();
-                        String value2 = propertyPlaceholder.replacePlaceholders(value, placeholderResolver);
-                        if (! value.equals(value2)){
-                            li.set(value2);
+                    final ListIterator<String> li = ((List<String>) entry.getValue()).listIterator();
+                    while (li.hasNext()){
+                        final String settingValueRaw = li.next();
+                        final String settingValueResolved = propertyPlaceholder.replacePlaceholders(settingValueRaw, placeholderResolver);
+                        if (!settingValueRaw.equals(settingValueResolved)){
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Nit: space after `))` so `)) }`

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java [hunk 11]
```diff
@@ -1216,13 +1216,12 @@ public boolean shouldRemoveMissingPlaceholder(String placeholderName) {
...
                 if (entry.getValue() instanceof List) {
-                    List<String> ls = (List<String>) entry.getValue();
-                    ListIterator<String> li = ls.listIterator();
-                    while(li.hasNext()){
-                        String value = li.next();
-                        String value2 = propertyPlaceholder.replacePlaceholders(value, placeholderResolver);
-                        if (! value.equals(value2)){
-                            li.set(value2);
+                    final ListIterator<String> li = ((List<String>) entry.getValue()).listIterator();
+                    while (li.hasNext()){
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: Nit: space after `))` so `)) }`

File: core/src/main/java/org/elasticsearch/common/settings/Settings.java (hunk 10 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Settings.java]: I wonder if it's simpler to do away with this `if`? If they are equal, it's okay to do the set?

**Review by jasontedor — COMMENTED** [review]
Thanks @mayya-sharipova; looks good. I left a few more comments.

**Review by jasontedor — APPROVED** [review]
LGTM. However, I think the commit message could be more thorough (right now it basically says: "something was broken, this fixes it"). When you merge, can you write a more thorough commit message please?

**Comment by mayya-sharipova** [comment]
@jasontedor thanks a lot for comprehensive review, I learned useful stuff.

Just to confirm, I intend to backport this commit to 6.1 and 6.x

**Comment by jasontedor** [comment]
It is not clear if we will do a 6.1 release that has this fix but please backport to both 6.1 (in case), and 6.x. The label on 6.1 should be 6.1.3.

**Comment by jasontedor** [comment]
@mayya-sharipova If this is backported, can you remove the backport-pending label. Separately, can you fix the 6.1 label?
