### PR TITLE
Fetch all test results for terms aggregation

### LINKED ISSUE #111441: [CI] StandardVersusLogsIndexModeChallengeRestIT testTermsAggregation failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3580 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/iltt2r7ux6czk)
- [elasticsearch-pull-request #27297 / part-1](https://gradle-enterprise.elastic.co/s/ew3lhpwbwmoty)
- [elasticsearch-periodic-platform-support #3576 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ie3vacvvks3zw)
- [elasticsearch-periodic-platform-support #3576 / rhel-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/gvkg4sy64l5c4)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:javaRestTest" --tests "org.elasticsearch.datastreams.logsdb.qa.StandardVersusLogsIndexModeChallengeRestIT.testTermsAggregation" -Dtests.seed=D7DCE5621A863818 -Dtests.locale=mk -Dtests.timezone=Africa/Douala -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTermsAggregation'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.datastreams.logsdb.qa.StandardVersusLogsIndexModeChallengeRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Error [Lists do not match when ignoring sort order] actual mappings [{"_doc":{"properties":{"host.name":{"type":"keyword"},"gvuYK":{"type":"keyword"},"L":{"type":"long"},"OCGAZrjc":{"type":"keyword"},"PBjCTj":{"type":"keyword"}}}}] actual settings [{"index":{"mode":"logsdb","number_of_shards":"3","mapping":{"total_fields":{"limit":"5000"}}}}] expected mappings [{"_doc":{"subobjects":false,"properties":{"host.name":{"type":"keyword"},"gvuYK":{"type":"keyword"},"L":{"type":"long"},"OCGAZrjc":{"type":"keyword"},"PBjCTj":{"type":"keyword"}}}}] expected settings [{"index":{"number_of_replicas":"2","mapping":{"total_fields":{"limit":"5000"}}}}] 
```

**Issue Reasons:**
- [main] 4 failures in test testTermsAggregation (2.1% fail rate in 189 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by kkrik-es**
More changes: add debug info in failure messages, separate common settings to use the same values in base and test.

Fixes #111441

### CODE REVIEW

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/logsdb/qa/matchers/Matcher.java [hunk 1]
```diff
@@ -104,4 +108,15 @@ protected static String formatErrorMessage(
             + "] ";
     }
 
+    protected static String prettyPrintArrays(final Object[] actualArray, final Object[] expectedArray) {
```
Comment (lkts) [inline modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/logsdb/qa/matchers/Matcher.java:111]: Nice

**Review by lkts — APPROVED** [review]
