### PR TITLE
Fix Term Vectors with artificial docs and keyword fields

### LINKED ISSUE #53494: Term Vectors doesn't work on artificial docs with keyword fields
Steps to reproduce:
```
PUT test_termvector
{
    "mappings": {
    "properties": {
      "words": {
        "type": "keyword"
      }
    }
  }
}

PUT test_termvector/_doc/1?refresh
{
  "words": [
    "b",
    "b",
    "b",
    "a",
    "e",
    "f",
    "f"
  ]
}

# we can get terms score without artifical documents
GET test_termvector/_termvectors/1
{
  "fields": [
    "words"
  ],
  "term_statistics": false,
  "field_statistics": false,
  "positions": false,
  "offsets": false,
  "filter": {
    "max_num_terms": 3
  }
}

{
  "_index" : "test_termvector",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "found" : true,
  "took" : 0,
  "term_vectors" : {
    "words" : {
      "terms" : {
        "b" : {
          "term_freq" : 3,
          "score" : 3.0
        },
        "e" : {
          "term_freq" : 1,
          "score" : 1.0
        },
        "f" : {
          "term_freq" : 2,
          "score" : 2.0
        }
      }
    }
  }
}


# we **cannot** get terms score with artifical documents of keyword type
GET test_termvector/_termvectors
{
  "doc": {
    "words": [
      "b",
      "b",
      "b",
      "a",
      "e",
      "f",
      "f"
    ]
  },
  "fields": [
    "words"
  ],
  "term_statistics": false,
  "field_statistics": false,
  "positions": false,
  "offsets": false,
  "filter": {
    "max_num_terms": 3
  }
}

{
  "_index" : "test_termvector",
  "_type" : "_doc",
  "_version" : 0,
  "found" : true,
  "took" : 0,
  "term_vectors" : { }
}
```

Issue is spotted in `ParseContext#getValues()` where  `field.stringValue()` returns `null` for keyword fields. Need to check for the `KeywordFieldType` and convert BytesRef to UTF8 string.

### PR DESCRIPTION
**Pull request by matriv**
Previously, Term Vectors API was returning empty results for
artificial documents with keyword fields. Checking only for `string()`
on `IndexableField` is not enough, since for `KeywordFieldType`
`binaryValue()` must be used instead.

Fixes #53494

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java [hunk 1]
```diff
@@ -131,8 +131,12 @@ public IndexableField getByKey(Object key) {
         public final String[] getValues(String name) {
             List<String> result = new ArrayList<>();
             for (IndexableField field : fields) {
-                if (field.name().equals(name) && field.stringValue() != null) {
-                    result.add(field.stringValue());
+                if (field.name().equals(name)) {
+                    if (field.stringValue() != null) {
+                        result.add(field.stringValue());
+                    } else if (field.binaryValue() != null) { // KeywordFieldType
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java]: We cannot use the binary value without checking the type of the field. It could be a real `binary` field that doesn't store utf8 bytes. Since this function is only used in the terms vector service, can you move it there and adds a check to extract binary values only if the field is of type `keyword` ?

**Review by jimczi — CHANGES_REQUESTED** [review]
Good catch @matriv, I left a comment regarding the applicability of the fix.

File: server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java (hunk 1 above)
Comment (matriv) [reply server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java]: The method is called as you said only by TermVectorService and it's guarded by a isValidField:
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/termvectors/TermVectorsService.java#L304 but I agree, it makes sense to move the method close to this so it's visible.

**Comment by matriv** [comment]
@jimczi I moved it to `TermVectorService` but I'm unsure if it worths avoiding the `instanceof`.

File: server/src/main/java/org/elasticsearch/index/termvectors/TermVectorsService.java [hunk 2]
```diff
@@ -313,14 +314,33 @@ private static Fields generateTermVectorsFromDoc(IndexShard indexShard, TermVect
...
+     * matching fields.  It never returns null.
+     * @param fields The <code>IndexableField</code> to get the values from
+     * @return a <code>String[]</code> of field values
+     */
+    public static String[] getValues(IndexableField[] fields) {
+        List<String> result = new ArrayList<>();
+        for (IndexableField field : fields) {
+            if (field.stringValue() != null) {
+                result.add(field.stringValue());
+            } else if (field.binaryValue() != null) { // KeywordFieldType
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/termvectors/TermVectorsService.java]: I think that this will create duplicates due to doc values field that also use a binary value (`SortedSetDocValuesField`). You should change this to something like:
````
if (field.fieldType() instanceof KeywordFieldMapper.KeywordFieldType) {
  result.add(field.binaryValue().utf8ToString());
} else if (field.fieldType() instanceof StringFieldType) {
  result.add(field.stringValue());
}
````

**Review by jimczi — COMMENTED** [review]
Thanks for moving the function. I left one comment regarding the field value extraction.

**Review by jimczi — APPROVED** [review]
LGTM
