### PR TITLE
Fix Queued Snapshot Clone not Starting after Data Node Drops Out

### LINKED ISSUE #77101: AssertionError: Found shard snapshot waiting to be assigned...
In a recent `master` (707dd497e489bb6917dc3d0bd58928ce13a33927) I saw a snapshot stress test trip the `Found shard snapshot waiting to be assigned` exception. The problematic shard was `[index-1][1]` and the assertion tripped at the cluster state transition which finalised a snapshot with a future clone queued up. The previous state of this shard was like this:

    snapshot:
    {
      "index": {
        "index_name": "index-1",
        "index_uuid": "kigpd8yeTZm5R6PHbZKpww"
      },
      "shard": 1,
      "state": "FAILED",
      "generation": "CcvNa4iURmCdg0YDvwIM9w",
      "node": "PgoVP627RAqZnA5y4ZQeDQ",
      "reason": "node shutdown"
    },

    clone:
    {
      "index": {
        "name": "index-1",
        "id": "3cG2OCEuSB2MINCVHFxI4g"
      },
      "shard": 1,
      "state": "QUEUED",
      "generation": null,
      "node": null
    }

The finalisation removed the first entry, leaving the dangling `QUEUED` clone. FWIW the shard was in yellow health at the time, although as a clone we should be able to proceed even if it were red.

Full test output in case it helps: [testoutput-1630475019.tar.gz](https://github.com/elastic/elasticsearch/files/7088887/testoutput-1630475019.tar.gz)

### PR DESCRIPTION
**Pull request by original-brownbear**
We have to account for queued up clones when dealing with nodes dropping out
and start them when they become ready to execute because of a node leaving the cluster.
Added test to reproduce the issue in #77101 and another test to verify that the more complex
case of clone queued after snapshot queued after clone still works correctly as well.
The solution here is the most direct fix I could think of and the by far easiest to backport.
That said, I added a TODO that asks for a follow-up that should allow for completely removing
the duplicate code across handling shard updates and external changes. The difference between
the two ways of updating the state is a left-over from the time before we had concurrent
operations and has become a needless complexity nowadays.

closes #77101

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -1122,19 +1126,73 @@ public ClusterState execute(ClusterState currentState) {
...
+                                    InFlightShardSnapshotStates inFlightShardSnapshotStates = null;
+                                    for (Map.Entry<RepositoryShardId, ShardSnapshotStatus> failureEntry : knownFailures.getOrDefault(
+                                        snapshot.repository(),
+                                        Collections.emptyMap()
+                                    ).entrySet()) {
+                                        final RepositoryShardId repositoryShardId = failureEntry.getKey();
+                                        final ShardSnapshotStatus existingStatus = snapshot.shardsByRepoShardId().get(repositoryShardId);
+                                        if (ShardSnapshotStatus.UNASSIGNED_QUEUED.equals(existingStatus)) {
+                                            if (inFlightShardSnapshotStates == null) {
+                                                inFlightShardSnapshotStates = InFlightShardSnapshotStates.forRepo(
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1163]: This isn't great performance wise but I found it the easiest to understand and the fixed situation should be practically very rare anyway. Moving this code path to the `SHARD_STATE_EXECUTOR` in a follow-up will use more efficient logic for this computation so I figured it wasn't worth optimizing anything here.

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tanguy!
