### PR TITLE
ES|QL: Fix NPE on single value detection

### LINKED ISSUE #103141: ES|QL: NullPointerException on stats avg()
Reproduces more or less deterministically on https://demo.elastic.co

```
POST _query
{
  "query":"from metrics-* | stats avg(event.duration) | limit 10"
}
```

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.index.mapper.MappedFieldType.typeName()" because "fieldType" is null
	at org.elasticsearch.xpack.esql.stats.SearchStats.detectSingleValue(SearchStats.java:185)
	at org.elasticsearch.xpack.esql.stats.SearchStats.lambda$isSingleValue$10(SearchStats.java:168)
	at org.elasticsearch.xpack.esql.stats.SearchStats.doWithContexts(SearchStats.java:283)
	at org.elasticsearch.xpack.esql.stats.SearchStats.isSingleValue(SearchStats.java:167)
	at org.elasticsearch.xpack.esql.optimizer.LocalPhysicalPlanOptimizer$PushStatsToSource.lambda$pushableStats$0(LocalPhysicalPlanOptimizer.java:379)
	at java.util.Map.computeIfAbsent(Map.java:1066)
	at org.elasticsearch.xpack.esql.optimizer.LocalPhysicalPlanOptimizer$PushStatsToSource.pushableStats(LocalPhysicalPlanOptimizer.java:364)
	at org.elasticsearch.xpack.esql.optimizer.LocalPhysicalPlanOptimizer$PushStatsToSource.rule(LocalPhysicalPlanOptimizer.java:331)
	at org.elasticsearch.xpack.esql.optimizer.LocalPhysicalPlanOptimizer$PushStatsToSource.rule(LocalPhysicalPlanOptimizer.java:323)
	at org.elasticsearch.xpack.esql.optimizer.PhysicalOptimizerRules$ParameterizedOptimizerRule.lambda$apply$0(PhysicalOptimizerRules.java:37)

```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/103141

Fix NullPointerException in detection of single value fields in SearchStats.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java [hunk 1]
```diff
@@ -161,14 +161,16 @@ public boolean isSingleValue(String field) {
             if (exists(field) == false) {
                 stat.singleValue = true;
             } else {
-                var sv = new boolean[] { false };
+                var sv = new boolean[] { true };
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java:164]: Was this a bug...?

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java:164]: I guess it's safe to assume that there will be at least one valid MappedFieldType, and if the type allows MV it will be set to `false` anyway.
Or maybe there are situations where none of the contexts has a MappedFieldType for that specific field, and in that case we still want to fall back to `false`?

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Review by alex-spies — COMMENTED** [review]
Can't say if there's situations when none search contexts will have a mapped field type, so we may want to wait for answer from @costin on this one. If there's such situations, a test case would be great IMO.

Otherwise, IMO if we add a test that reproduces the NPE that is fixed by this PR, this should be good to go as it improves our code's health in any case.

**Review by costin — APPROVED** [review]
Please add an integration test for it. Looking at the mapped method, looks like it's not just true and null but also potentially an exception.
 ```
* If the field is not mapped, the behaviour depends on the index.query.parse.allow_unmapped_fields setting, which defaults to true.
* In case unmapped fields are allowed, null is returned when the field is not mapped.
* In case unmapped fields are not allowed, either an exception is thrown or the field is automatically mapped as a text field.
```

**Comment by costin** [comment]
Btw, since this is a bug, it should be backported to 8.12.x

**Comment by luigidellaquila** [comment]
>  a test case would be great IMO.

> Please add an integration test for it.

yeah, I spent hours trying to unit-test it, but I have to mock too many layers (I realized why this class does not have a unit test). I'll go for an integration test
