### PR TITLE
Fixing permission errors for `KERBEROS` security mode for HDFS Repository

### LINKED ISSUE #22156: ES-v5.0.1 throw java.lang.SecurityException while snapshot
**Elasticsearch version**: 5.0.1

**Plugins installed**: `repository-hdfs`

**JVM version**:

```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**OS version**:

```
CentOS release 6.7 (Final)
Linux version 2.6.32-573.26.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Wed May 4 00:57:44 UTC 2016
```

**Description of the problem including expected versus actual behavior**:
When I create repositories, ES response 

```
{
  "acknowledged": true
}
```

but when I create snapshot of index, it throws exception:

```
[2016-12-12T11:38:04,417][WARN ][r.suppressed             ] path: /_snapshot/my_hdfs_repo/20161209-snapshot, params: {repository=my_hdfs_repo, snapshot=20161209-snapshot}
org.elasticsearch.transport.RemoteTransportException: [node-2][10.90.6.234:9340][cluster:admin/snapshot/create]
Caused by: org.elasticsearch.repositories.RepositoryException: [my_hdfs_repo] could not read repository data from index blob
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:751) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:226) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:86) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.doRun(TransportMasterNodeAction.java:170) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.io.IOException: com.google.protobuf.ServiceException: java.security.AccessControlException: access denied ("javax.security.auth.PrivateCredentialPermission" "org.apache.hadoop.security.Credentials" "read")
        at org.apache.hadoop.ipc.ProtobufHelper.getRemoteException(ProtobufHelper.java:47) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getListing(ClientNamenodeProtocolTranslatorPB.java:580) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187) ~[?:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[?:?]
        at com.sun.proxy.$Proxy34.getListing(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:2094) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:2077) ~[?:?]
        at org.apache.hadoop.fs.Hdfs.listStatus(Hdfs.java:254) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util$1.next(FileContext.java:1798) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util$1.next(FileContext.java:1794) ~[?:?]
        at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1800) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1759) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1718) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer$6.run(HdfsBlobContainer.java:145) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer$6.run(HdfsBlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobStore$4.run(HdfsBlobStore.java:136) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
        at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_92]
        at org.elasticsearch.repositories.hdfs.HdfsBlobStore.execute(HdfsBlobStore.java:133) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer.listBlobsByPrefix(HdfsBlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:849) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:818) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:721) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:226) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:86) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.doRun(TransportMasterNodeAction.java:170) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_92]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: service_exception: java.security.AccessControlException: access denied ("javax.security.auth.PrivateCredentialPermission" "org.apache.hadoop.security.Credentials" "read")
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:243) ~[?:?]
        at com.sun.proxy.$Proxy33.getListing(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getListing(ClientNamenodeProtocolTranslatorPB.java:573) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187) ~[?:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[?:?]
        at com.sun.proxy.$Proxy34.getListing(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:2094) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:2077) ~[?:?]
        at org.apache.hadoop.fs.Hdfs.listStatus(Hdfs.java:254) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util$1.next(FileContext.java:1798) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util$1.next(FileContext.java:1794) ~[?:?]
        at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1800) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1759) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1718) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer$6.run(HdfsBlobContainer.java:145) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer$6.run(HdfsBlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobStore$4.run(HdfsBlobStore.java:136) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
        at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_92]
        at org.elasticsearch.repositories.hdfs.HdfsBlobStore.execute(HdfsBlobStore.java:133) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer.listBlobsByPrefix(HdfsBlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:849) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:818) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:721) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:226) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:86) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.doRun(TransportMasterNodeAction.java:170) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_92]
Caused by: java.lang.SecurityException: access denied ("javax.security.auth.PrivateCredentialPermission" "org.apache.hadoop.security.Credentials" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_92]
        at java.security.AccessControlContext.checkPermission2(AccessControlContext.java:538) ~[?:1.8.0_92]
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:481) ~[?:1.8.0_92]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_92]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_92]
        at javax.security.auth.Subject$ClassSet.populateSet(Subject.java:1414) ~[?:1.8.0_92]
        at javax.security.auth.Subject$ClassSet.<init>(Subject.java:1372) ~[?:1.8.0_92]
        at javax.security.auth.Subject.getPrivateCredentials(Subject.java:767) ~[?:1.8.0_92]
        at org.apache.hadoop.security.UserGroupInformation.getCredentialsInternal(UserGroupInformation.java:1499) ~[?:?]
        at org.apache.hadoop.security.UserGroupInformation.getTokens(UserGroupInformation.java:1464) ~[?:?]
        at org.apache.hadoop.ipc.Client$Connection.<init>(Client.java:436) ~[?:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1519) ~[?:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1446) ~[?:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1407) ~[?:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229) ~[?:?]
        at com.sun.proxy.$Proxy33.getListing(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getListing(ClientNamenodeProtocolTranslatorPB.java:573) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187) ~[?:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) ~[?:?]
        at com.sun.proxy.$Proxy34.getListing(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:2094) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:2077) ~[?:?]
        at org.apache.hadoop.fs.Hdfs.listStatus(Hdfs.java:254) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util$1.next(FileContext.java:1798) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util$1.next(FileContext.java:1794) ~[?:?]
        at org.apache.hadoop.fs.FSLinkResolver.resolve(FSLinkResolver.java:90) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1800) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1759) ~[?:?]
        at org.apache.hadoop.fs.FileContext$Util.listStatus(FileContext.java:1718) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer$6.run(HdfsBlobContainer.java:145) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer$6.run(HdfsBlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobStore$4.run(HdfsBlobStore.java:136) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_92]
        at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_92]
        at org.elasticsearch.repositories.hdfs.HdfsBlobStore.execute(HdfsBlobStore.java:133) ~[?:?]
        at org.elasticsearch.repositories.hdfs.HdfsBlobContainer.listBlobsByPrefix(HdfsBlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:849) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:818) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:721) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:226) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:86) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.doRun(TransportMasterNodeAction.java:170) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) ~[elasticsearch-5.0.1.jar:5.0.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.1.jar:5.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_92]
```

**Steps to reproduce**:
 1.create repositories

```
PUT /_snapshot/my_backup
{
"type": "hdfs",
"settings": {
      "path": "/path/on/hadoop",
      "uri": "hdfs://hadoop_cluster_domain:[port]",
      "conf_location":"/hadoop/hdfs-site.xml,/hadoop/core-site.xml",
      "user":"hadoop"
    }
}
```

 2.snapshot my index

```
PUT /_snapshot/my_backup/snapshot_1?wait_for_completion=true
```

 3.exception is thrown

### PR DESCRIPTION
**Pull request by jbaiera**
This PR is meant to address the permission errors that are encountered in the HDFS Repository Plugin as described in https://github.com/elastic/elasticsearch/issues/22156.

When Hadoop security is enabled, the HDFS client requests the current logged in Subject for a hadoop based Credentials object, which trips a missing permission in the plugin's policy file. This is not caught during testing since we neither use the actual HDFS client code nor do we execute with Kerberos security enabled.

I'm working on testing this on a local environment at the moment since it requires a secured HDFS service to activate the code path. My main concern is that there may be other permissions that have not yet had the chance to trip up the plugin because they have not yet been reached in the code.

Closes #22156

### CODE REVIEW

**Comment by rjernst** [comment]
I do not think we should add a permission that we cannot test (all the time, not manually). Can you improve the hdfs fixture so that we can use credentials with it to test this actually works?

**Comment by jbaiera** [comment]
@rjernst I completely agree with you on that. I'm still trying to dig through all the permission violations at the moment against a local kerberized cluster, then will circle back to assess the effort for the test fixtures.

**Comment by surekhabalaji** [comment]
So glad to see this issue being worked on. W are waiting on this fix for the hdfs plugin issue with Elastic Search 5.2 in order to take snapshots on hdfs repository.  Any ETA on when this will get released?

**Comment by jbaiera** [comment]
@surekhabalaji It's hard to say at this stage. It's been a long process of testing, seeing new permissions that are missing, retesting, repeat, and the iteration cycle for testing is fairly large due to the overhead of requiring a secure HDFS environment. Rest assured that it is being actively worked on.

**Comment by jbaiera** [comment]
At this point the code should be complete. I'm able to manually test this in a sandbox environment with a Kerberos-enabled HDFS cluster. Repository creation, snapshots and restores are working in that environment. @rjernst and @jasontedor, does it make sense to get this change in then immediately circle back around for the testing fixtures after?

**Comment by jasontedor** [comment]
@jbaiera This looks like an elaborate and difficult change to have worked through, and I appreciate the effort and the documentation within the change. However, building off what @rjernst said, I think that we need a testing plan before this can be integrated (n.b.: plan). As we discussed via another channel, if the fixture approach is too much effort I'm fine with testing this through a VM.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobStore.java [hunk 1]
```diff
@@ -118,7 +119,8 @@ private Path translateToHdfsPath(BlobPath blobPath) {
         try {
             return AccessController.doPrivileged((PrivilegedExceptionAction<V>)
                     () -> operation.run(fileContext), null, new ReflectPermission("suppressAccessChecks"),
-                     new AuthPermission("modifyPrivateCredentials"), new SocketPermission("*", "connect"));
+                     new AuthPermission("modifyPrivateCredentials"), new SocketPermission("*", "connect"),
+                     new AuthPermission("doAs"), new ServicePermission("*", "initiate,accept"));
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobStore.java]: I think that the comment on this method is no longer accurate. Can you adjust it?

File: plugins/repository-hdfs/src/main/plugin-metadata/plugin-security.policy [hunk 2]
```diff
@@ -25,17 +25,44 @@ grant {
   permission java.lang.RuntimePermission "accessDeclaredMembers";
   permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
 
+  // Needed so that Hadoop can load the correct classes for SPI and JAAS
+  //   org.apache.hadoop.security.SecurityUtil clinit
+  //   org.apache.hadoop.security.UserGroupInformation.newLoginContext()
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/plugin-metadata/plugin-security.policy]: Nit: please fix the indentation here

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsPlugin.java [hunk 3]
```diff
@@ -79,6 +83,34 @@ private static Void evilHadoopInit() {
...
+         * come annotated with configurations that denote information about if they support
+         * certain security options like Kerberos, and how to send information with the
+         * message to support that authentication method. SecurityUtil creates a service loader
+         * in a static field during its clinit. This loader provides the implementations that
+         * pull the security information for each proto class. The service loader sources its
+         * services from the current thread's context class loader, which must contain the Hadoop
+         * jars. Since plugins don't execute with their class loaders installed as the thread's
+         * context class loader, we need to install the loader briefly, allow the util to be
+         * initialized, then restore the old loader since we don't actually own this thread.
+         */
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsPlugin.java]: I appreciate the thoroughness of this comment.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 4]
```diff
@@ -51,6 +49,8 @@
 
 public final class HdfsRepository extends BlobStoreRepository {
 
+    private static final Logger LOGGER = Logger.getLogger(HdfsRepository.class);
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Why are we using the old Log4j API here? I understand that Hadoop needs it, but we can use the new Log4j API here, and our Log4j API to acquire a logger, no?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 5]
```diff
@@ -118,23 +118,33 @@ private static FileContext createContext(URI uri, Settings repositorySettings)
...
-        Subject subject;
+        // Initialize the UGI with the configuration.
+        UserGroupInformation.setConfiguration(cfg);
+
+        // Debugging
+        if (UserGroupInformation.isSecurityEnabled()) {
+            LOGGER.info("Hadoop Security Is [ENABLED]");
+        } else {
+            LOGGER.info("Hadoop Security is [DISABLED]");
+        }
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Can this whole block be replaced by:

```diff
diff --git a/plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java b/plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java
index 95619b1d40..d65686e356 100644
--- a/plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java
+++ b/plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java
@@ -122,11 +122,7 @@ public final class HdfsRepository extends BlobStoreRepository {
         UserGroupInformation.setConfiguration(cfg);
 
         // Debugging
-        if (UserGroupInformation.isSecurityEnabled()) {
-            LOGGER.info("Hadoop Security Is [ENABLED]");
-        } else {
-            LOGGER.info("Hadoop Security is [DISABLED]");
-        }
+        LOGGER.info("Hadoop security enabled: [{}]", UserGroupInformation.isSecurityEnabled());
         UserGroupInformation.AuthenticationMethod method = SecurityUtil.getAuthenticationMethod(cfg);
         LOGGER.info("Using Hadoop authentication method : [" + method + "]");
 ```

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 6]
```diff
@@ -118,23 +118,33 @@ private static FileContext createContext(URI uri, Settings repositorySettings)
             cfg.set(entry.getKey(), entry.getValue());
         }
 
-        // create a hadoop user. if we want some auth, it must be done different anyway, and tested.
-        Subject subject;
+        // Initialize the UGI with the configuration.
+        UserGroupInformation.setConfiguration(cfg);
+
+        // Debugging
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: If this is debugging, why we are logging at the info level?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 7]
```diff
@@ -118,23 +118,33 @@ private static FileContext createContext(URI uri, Settings repositorySettings)
...
+        if (UserGroupInformation.isSecurityEnabled()) {
+            LOGGER.info("Hadoop Security Is [ENABLED]");
+        } else {
+            LOGGER.info("Hadoop Security is [DISABLED]");
+        }
+        UserGroupInformation.AuthenticationMethod method = SecurityUtil.getAuthenticationMethod(cfg);
+        LOGGER.info("Using Hadoop authentication method : [" + method + "]");
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Is this better on the debug level?

**Review by jasontedor — CHANGES_REQUESTED** [review]
Thanks @jbaiera. I left some first-round review comments.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java (hunk 7 above)
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: This will make the logger usage checker unhappy, can you rewrite this to be parameterized?

**Review by jasontedor — CHANGES_REQUESTED** [review]
I left one more comment that I forgot leave on the first review, sorry.

**Comment by rjernst** [comment]
The changes look alright, but as I said before, I really don't trust any of it without tests.  This may fix the issue for one particular configuration (which you tested manually), but we don't know that it works for other configurations.  In addition to a plan for how to test this, I think we need an explicitly documented set of authentication types that we claim to support with hadoop. Then what needs to be tested should come naturally from that.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobStore.java (hunk 1 above)
Comment (jbaiera) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobStore.java]: I pushed 	d973296

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java (hunk 6 above)
Comment (jbaiera) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Good catch. Should be fixed in 8845f2d.

**Review by jasontedor — APPROVED** [review]

**Comment by jbaiera** [comment]
After further scoping out testing requirements for this, I've come across some potentially nasty problems with how Hadoop tries to refresh Kerberos tickets in the CCACHE.

1. Hadoop spawns a thread that refreshes the ticket in the background
2. Hadoop needs the kerberos client packages installed on the local OS because...
3. Hadoop spawns a child process (default is `kinit -R`) to do the ticket refresh

I haven't personally run into this issue yet, but that's because I haven't let the repository soak long enough for the testing ticket I've been using to need refreshing. Hadoop is basically sitting on its hands waiting to execute code that is questionable for our security model. I'm going to work on a clean reproduction of this to confirm, but the uncertainty around it makes me uncomfortable about making it a blocker for 5.3.0.

**Comment by jbaiera** [comment]
I've made some local changes to see if I could force the command execution to trip the security checks and, to my dismay, succeeded. Alas, it seems that using a Kerberos TGT from the CCACHE in Elasticsearch is not going to be supportable unless Hadoop finds a better way to refresh Kerberos Tickets instead of forking a process to do so.

I have seen that logging in with a keytab does not launch this background refresh process in the Hadoop code. I'll dig into how the Kerberos auth module works to see if there's some potential to still allow authentication.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+            // Still far and away fewer permissions than the original full plugin policy
+        };
+    }
+
+    /**
+     * Locates the keytab file in the environment and verifies that it exists.
+     * Expects keytab file to exist at {@code $CONFIG_DIR$/kerberos/krb5.keytab}
+     */
+    public static Path locateKeytabFile(Environment environment) {
+        Path keytabPath = environment.configFile().resolve("kerberos").resolve("krb5.keytab");
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: I think that this should be in `config/repository-hdfs/krb5.keytab` rather than in a separate directory. This is the convention for plugin-specific configuration files.

**Review by jasontedor — CHANGES_REQUESTED** [review]
I left one comment, it does not constitute a full review but only something that I noticed when I took a quick peek. I'll do a full review tomorrow.

**Comment by jasontedor** [comment]
test this please

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 9]
```diff
@@ -107,43 +115,105 @@ protected void doStart() {
...
+                    originalPrincipal, finalPrincipal);
+            }
+        }
+        return finalPrincipal;
+    }
+
+    @SuppressForbidden(reason = "InetAddress.getLocalHost()")
+    private static String findHostName() {
+        try {
+            return InetAddress.getLocalHost().getCanonicalHostName();
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Can we leave a comment here explaining why this should not block as it's a bit indirect (Log4j does a lookup, it's cached by the JVM, default TTL with a security manager is infinite, etc.)?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 10]
```diff
@@ -107,43 +115,105 @@ protected void doStart() {
...
+            if (originalPrincipal.equals(finalPrincipal) == false) {
+                LOGGER.debug("Found service principal. Converted original principal name [{}] to server principal [{}]",
+                    originalPrincipal, finalPrincipal);
+            }
+        }
+        return finalPrincipal;
+    }
+
+    @SuppressForbidden(reason = "InetAddress.getLocalHost()")
+    private static String findHostName() {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Nit: `findHostName` -> `getHostName`

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 11]
```diff
@@ -0,0 +1,153 @@
...
+            // 1) hadoop dynamic proxy is messy with access rules
+            new ReflectPermission("suppressAccessChecks"),
+            // 2) allow hadoop to add credentials to our Subject
+            new AuthPermission("modifyPrivateCredentials"),
+            // 3) allow hadoop to act as the logged in Subject
+            new AuthPermission("doAs"),
+            // 4) Listen and resolve permissions for kerberos server principals
+            new SocketPermission("localhost:0", "listen,resolve"),
+            // We add the following since hadoop requires the client to re-login when the kerberos ticket expires:
+            // 5) All the permissions needed for UGI to do it's weird JAAS hack
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Nit: `it's` -> `its`

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+            // 7) allow code to initiate kerberos connections as the logged in user
+            // Still far and away fewer permissions than the original full plugin policy
+        };
+    }
+
+    /**
+     * Locates the keytab file in the environment and verifies that it exists.
+     * Expects keytab file to exist at {@code $CONFIG_DIR$/kerberos/krb5.keytab}
+     */
+    public static Path locateKeytabFile(Environment environment) {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: I think that this can be package-private.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 13]
```diff
@@ -0,0 +1,153 @@
...
+            if (Files.exists(keytabPath) == false) {
+                LOGGER.error("Could not locate keytab file at [{}].", keytabPath);
+                throw new RuntimeException("Could not locate keytab");
+            }
+        } catch (SecurityException se) {
+            LOGGER.error((Supplier<String>)() ->
+                String.format(Locale.getDefault(), "Denied access to keytab file at [%s].", keytabPath),
+                se
+            );
+            throw new RuntimeException("Could not locate keytab");
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: This drops the original exception on the floor. I wonder if we need to swallow and wrap here at all?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 14]
```diff
@@ -0,0 +1,153 @@
...
+        }
+        return keytabPath;
+    }
+
+    private final UserGroupInformation ugi;
+    private final Permission[] restrictedExecutionPermissions;
+
+    public HdfsSecurityContext(UserGroupInformation ugi) {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: This can be package-private.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 15]
```diff
@@ -0,0 +1,153 @@
...
+import org.elasticsearch.common.logging.Loggers;
+import org.elasticsearch.env.Environment;
+
+/**
+ * Oversees all the security specific logic for the HDFS Repository plugin.
+ *
+ * Keeps track of the current user for a given repository, as well as which
+ * permissions to grant the blob store restricted execution methods.
+ */
+public class HdfsSecurityContext {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: I think that this class can be package private?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 16]
```diff
@@ -0,0 +1,153 @@
...
+            // as the logged in user.
+            permissions[permissions.length-1] = new ServicePermission(ugi.getUserName(), "initiate");
+        } else {
+            // SIMPLE
+            permissions = Arrays.copyOf(SIMPLE_AUTH_PERMISSIONS, SIMPLE_AUTH_PERMISSIONS.length);
+        }
+        return permissions;
+    }
+
+    public UserGroupInformation getUser() {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: I do not see where this method is used?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 17]
```diff
@@ -0,0 +1,153 @@
...
+        return ugi;
+    }
+
+    public Permission[] getRestrictedExecutionPermissions() {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Can it be package-private?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 18]
```diff
@@ -0,0 +1,153 @@
...
+        return restrictedExecutionPermissions;
+    }
+
+    public void ensureLogin() {
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Can it be package private?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 19]
```diff
@@ -107,43 +115,105 @@ protected void doStart() {
...
+
+            if (originalPrincipal.equals(finalPrincipal) == false) {
+                LOGGER.debug("Found service principal. Converted original principal name [{}] to server principal [{}]",
+                    originalPrincipal, finalPrincipal);
+            }
+        }
+        return finalPrincipal;
+    }
+
+    @SuppressForbidden(reason = "InetAddress.getLocalHost()")
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: The reason should be more explicit about why this needed.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 20]
```diff
@@ -107,43 +115,105 @@ protected void doStart() {
...
+
+    // Convert principals of the format 'service/_HOST@REALM' by subbing in the local address for '_HOST'.
+    private static String preparePrincipal(String originalPrincipal) {
+        String finalPrincipal = originalPrincipal;
+        // Don't worry about host name resolution if they don't have the _HOST pattern in the name.
+        if (originalPrincipal.contains("_HOST")) {
+            try {
+                finalPrincipal = SecurityUtil.getServerPrincipal(originalPrincipal, findHostName());
+            } catch (IOException e) {
+                throw new RuntimeException(e);
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: `UncheckedIOException`?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 21]
```diff
@@ -107,43 +115,105 @@ protected void doStart() {
...
+        try {
+            if (UserGroupInformation.isSecurityEnabled()) {
+                String principal = preparePrincipal(kerberosPrincipal);
+                String keytab = HdfsSecurityContext.locateKeytabFile(environment).toString();
+                LOGGER.debug("Using kerberos principal [{}] and keytab located at [{}]", principal, keytab);
+                return UserGroupInformation.loginUserFromKeytabAndReturnUGI(principal, keytab);
+            }
+            return UserGroupInformation.getCurrentUser();
+        } catch (IOException e) {
+            throw new RuntimeException("Could not retrieve the current user information", e);
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: `UncheckedIOException`?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 22]
```diff
@@ -0,0 +1,153 @@
...
+        if (ugi.isFromKeytab()) {
+            try {
+                ugi.checkTGTAndReloginFromKeytab();
+            } catch (IOException ioe) {
+                throw new RuntimeException("Could not re-authenticate", ioe);
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: `UncheckedIOException`?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 23]
```diff
@@ -0,0 +1,153 @@
...
+    /**
+     * Locates the keytab file in the environment and verifies that it exists.
+     * Expects keytab file to exist at {@code $CONFIG_DIR$/kerberos/krb5.keytab}
+     */
+    public static Path locateKeytabFile(Environment environment) {
+        Path keytabPath = environment.configFile().resolve("repository-hdfs").resolve("krb5.keytab");
+        try {
+            if (Files.exists(keytabPath) == false) {
+                LOGGER.error("Could not locate keytab file at [{}].", keytabPath);
+                throw new RuntimeException("Could not locate keytab");
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Include the path in the exception message? I question whether the logging statement is needed given that the exception message will effectively say the same thing? Can you throw this as a FileNotFoundException from here and let it bubble all the way up to a higher layer for wrapping?

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java [hunk 24]
```diff
@@ -107,43 +115,105 @@ protected void doStart() {
     }
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: Commenting here since the line that I want to comment on is not changed here. I see that `doStart` catches an `IOException` and wraps it in an `ElasticsearchGenerationException`. That seems odd to me, I think this should be either `UncheckedIOException` or `RuntimeException`.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java [hunk 25]
```diff
@@ -0,0 +1,153 @@
...
+            // KERBEROS
+            // Leave room to append one extra permission based on the logged in user's info.
+            int permlen = KERBEROS_AUTH_PERMISSIONS.length + 1;
+            permissions = new Permission[permlen];
+
+            System.arraycopy(KERBEROS_AUTH_PERMISSIONS, 0, permissions, 0, KERBEROS_AUTH_PERMISSIONS.length);
+
+            // Append a kerberos.ServicePermission to only allow initiating kerberos connections
+            // as the logged in user.
+            permissions[permissions.length-1] = new ServicePermission(ugi.getUserName(), "initiate");
```
Comment (jasontedor) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Nit: `permissions.length-1` -> `permissions.length - 1`

**Review by jasontedor — CHANGES_REQUESTED** [review]
Thanks @jbaiera, I left some comments.

File: docs/plugins/repository-hdfs.asciidoc [hunk 26]
```diff
@@ -95,3 +95,34 @@ The following settings are supported:
...
+The following authentication methods are supported by the plugin:
+
+[horizontal]
+`simple`::
+
+    Also means "no security". Uses information from underlying operating system account to inform Hadoop of who the current user is.
+
+`kerberos`::
+
+    Authenticates to Hadoop through the usage of a Kerberos principal and ticket. The Kerberos ticket must be available to the user running the Elasticsearch process by means of the credential cache (ccache).
```
Comment (jbaiera) [inline docs/plugins/repository-hdfs.asciidoc]: The docs still need some work at this point. None of this is accurate any longer. I'll address this soon.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java (hunk 23 above)
Comment (jbaiera) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Good point. Originally I was logging the path but since it was going to be user configurable at the start I figured it would be wise to not broadcast a potentially sensitive file location to any requestor who asks. Since we're standardizing on one canonical place for the file now I don't see why we can't add it back in.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java (hunk 16 above)
Comment (jbaiera) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsSecurityContext.java]: Was a test spot, missed it in the cleaning. I'll remove it.

File: plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java (hunk 24 above)
Comment (jbaiera) [inline plugins/repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java]: I pushed 6b325a1

**Comment by jbaiera** [comment]
Rebasing onto the most recent master to see if I can get the CI build to pass.

**Comment by jbaiera** [comment]
@rjernst @jasontedor, Docs are completed. This is probably ready for another round of review.

Regarding the testing strategy, I have a different branch built out with the following changes, but they depend on this branch at the moment:
1. Splits the build Fixture class into an interface and implementation (Fixture and AntFixture).
2. Introduces a VagrantFixture implementation of Fixture based on the existing VagrantCommand task.
3. Vagrantfile containing setup and provisioning for MIT Kerberos 5 (KRB5) added.
4. Modifications to HDFS Test Fixture to allow it to interface with kerberos hosted in vagrant
5. Create a new secure hdfs fixture task in the repository build with dependencies on a vagrant based kerberos fixture task
6. New test suite specifically modeled for interacting with secure HDFS. Configured a test runner specifically for that suite to run using the secure HDFS fixture and the kerberos vagrant fixture.

I can merge all that into this branch and we can review it here, but It's rather a lot of code for all that, so I'd like to open a different PR for it after this is merged in. Thoughts?

**Comment by rjernst** [comment]
I think separate PRs would be good, at least for the first 2 bullets which are necessary, but semi unrelated.

**Comment by jbaiera** [comment]
I opened #24249 for the vagrant test fixture changes.

**Comment by jbaiera** [comment]
@rjernst @jasontedor Any thing else needed for this at this time? I'd like to see if I can get this merged in.

**Review by jasontedor — APPROVED** [review]
I left one more comment, it does not require another round from me but please make the change.

**Comment by Divyakoganti** [comment]
Hi,
Thanks for the information.
I need some information on configure hdfs repository with kerebos which i am not able to do.
i read from the posts that its still in progress as :
Kerberos authentication for the HDFS Repository Snapshot plugin does not function correctly in 5.x at the moment. There is currently an effort to re-add this functionality so that it may function well with the internal security manager.
Can you please help me when can i get this functionality added or any other method for using this plugin.

Divya
