### PR TITLE
[ML] fixes categorize_text parameter validation to be parse order independent

### LINKED ISSUE #82629: ES isn't throwing an error when both `categorization_filters` and `categorization_analyzer` are given.
**Elasticsearch version** (`bin/elasticsearch --version`): 8.1.0-snapshot

**Plugins installed**: [] platinum version of ES

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system): Windows

**Description of the problem including expected versus actual behavior**:
Issue was found when tests were failing in `elasticsearch-py` in the following file
`rest-api-spec/test/platinum/ml/categorization_agg.yml`

**Steps to reproduce**:

In the following section
```
  - do:
      catch: /\[categorization_filters\] cannot be used with \[categorization_analyzer\]/
      search:
        index: to_categorize
        body: >
          {
            "size": 0,
            "aggs": {
              "categories": {
                "categorize_text": {
                  "field": "text",
                  "categorization_filters": ["foo"],
                  "categorization_analyzer": "english"
                }
              }
            }
          }
```

ES isn't throwing an error when both `categorization_filters` and `categorization_analyzer` are given. 

Can be found in : https://clients-ci.elastic.co/job/elastic+elasticsearch-py+pull-request/449/PYTHON_CONNECTION_CLASS=urllib3,PYTHON_VERSION=3.9,STACK_VERSION=8.1.0-SNAPSHOT,TEST_SUITE=platinum,label=linux/consoleFull

### PR DESCRIPTION
**Pull request by benwtrent**
Depending on how the input is parsed, we may not validate that the categorization_analyzer isn't set when the filters are present.

This commit addresses this bug.

closes https://github.com/elastic/elasticsearch/issues/82629

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/CategorizeTextAggregationBuilder.java [hunk 1]
```diff
@@ -153,6 +153,13 @@ public CategorizeTextAggregationBuilder setSimilarityThreshold(int similarityThr
     }
 
     public CategorizeTextAggregationBuilder setCategorizationAnalyzerConfig(CategorizationAnalyzerConfig categorizationAnalyzerConfig) {
+        if (this.categorizationAnalyzerConfig != null) {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/CategorizeTextAggregationBuilder.java:156]: Shouldn't we be checking against the filters?

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/CategorizeTextAggregationBuilder.java:156]: The `filters` create an analyzer config, we don't store them.

**Review by kirakoki — APPROVED** [review]

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/CategorizeTextAggregationBuilder.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/CategorizeTextAggregationBuilder.java:156]: Ah, right. Got it.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM
