### PR TITLE
Fix ThreadPoolMergeSchedulerStressTestIT testMergingFallsBehindAndThenCatchesUp

### LINKED ISSUE #125744: [CI] ThreadPoolMergeSchedulerStressTestIT testMergingFallsBehindAndThenCatchesUp failing
**Build Scans:**
- [elasticsearch-intake #20849 / part1](https://gradle-enterprise.elastic.co/s/b47bj364pigce)
- [elasticsearch-periodic-platform-support #7273 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/ha5n6iyhvpnhq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.engine.ThreadPoolMergeSchedulerStressTestIT.testMergingFallsBehindAndThenCatchesUp" -Dtests.seed=BEBE22A867691519 -Dtests.locale=ml-Mlym-IN -Dtests.timezone=Africa/Timbuktu -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.engine.ThreadPoolMergeSchedulerStressTestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testMergingFallsBehindAndThenCatchesUp),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Error: Maximum permit count exceeded
```

**Issue Reasons:**
- [main] 2 failures in test testMergingFallsBehindAndThenCatchesUp (0.9% fail rate in 212 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by albertzaharovits**
We don't know how many semaphore merge permits we need to release, or how many are already released.

Fixes https://github.com/elastic/elasticsearch/issues/125744

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java [hunk 1]
```diff
@@ -82,7 +82,9 @@ public static class TestEnginePlugin extends Plugin implements EnginePlugin {
         void allowAllMerging() {
             // even when indexing is done, queued and backlogged merges can themselves trigger further merging
             // don't let this test be bothered by that, and simply let all merging run unhindered
-            runMergeSemaphore.release(Integer.MAX_VALUE - initialRunMergesCount);
```
Comment (albertzaharovits) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java:85]: The semaphore was also released when excess merges were enqueued. This is a dynamic process. I preferred I not fudge an upper limit value, or put Integer.MAX_VALUE / 2 ...

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java [hunk 2]
```diff
@@ -82,7 +82,9 @@ public static class TestEnginePlugin extends Plugin implements EnginePlugin {
...
+            if (runMergeSemaphore.availablePermits() < 10_000) {
+                runMergeSemaphore.release(10_000);
+            }
```
Comment (ankikuma) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java:87]: I am not quite sure what we are doing here. Isn't the maximum number of permits we can release = initialRunMergesCount - runMergeSemaphore.availablePermits() ?

Comment (albertzaharovits) [reply server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java:87]: We need to release as many permits as there are merges, but we don't know how many of those are going to be generated (depends on many parameters). And the fact that there is some "background" merging while merging is otherwise mostly stopped, complicates computations.

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java [hunk 3]
```diff
@@ -82,7 +82,9 @@ public static class TestEnginePlugin extends Plugin implements EnginePlugin {
         void allowAllMerging() {
             // even when indexing is done, queued and backlogged merges can themselves trigger further merging
             // don't let this test be bothered by that, and simply let all merging run unhindered
-            runMergeSemaphore.release(Integer.MAX_VALUE - initialRunMergesCount);
+            if (runMergeSemaphore.availablePermits() < 10_000) {
```
Comment (henningandersen) [inline server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java:85]: How can it have more than 10K available already? Should we instead assert it has not?

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java (hunk 3 above)
Comment (albertzaharovits) [reply server/src/internalClusterTest/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerStressTestIT.java:85]: It can't have more than 10K, or Integer.MAX_VALUE / 2, 99999, etc...
It's just strange to fudge any sort of non-obvious value, but on the other hand, the shenanigans required to avoid that are not worth it. I'll fudge a value, and drop a comment.
