### PR TITLE
SQL: Fix unecessary evaluation for CASE/IIF

### LINKED ISSUE #49672: SQL: division by zero when grouping by
Similar to https://github.com/elastic/elasticsearch/issues/49388, but this time on the aggregation side, where the Painless script already evaluates the value: 

```
SELECT CASE WHEN languages - 1 = 0 THEN NULL ELSE ( salary / (languages - 1) ) END AS x FROM test_emp GROUP BY 1
```

results in:

```
Caused by: java.lang.ArithmeticException: / by zero
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.Arithmetics.div(Arithmetics.java:110) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.BinaryArithmeticProcessor$NumericArithmetic.wrap(BinaryArithmeticProcessor.java:29) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.BinaryArithmeticProcessor$BinaryArithmeticOperation.doApply(BinaryArithmeticProcessor.java:131) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.PredicateBiFunction.apply(PredicateBiFunction.java:24) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.function.scalar.whitelist.InternalSqlScriptUtils.div(InternalSqlScriptUtils.java:198) ~[?:?]
        at org.elasticsearch.painless.PainlessScript$Script.execute(InternalSqlScriptUtils.caseFunction([InternalSqlScriptUtils.eq(InternalSqlScriptUtils.sub(InternalSqlScriptUtils.docValue(doc,params.v0),params.v1),params.v2),params.v3,InternalSqlScriptUtils.div(InternalSqlScriptUtils.docValue(doc,params.v4),InternalSqlSc ...:266) ~[?:?]
        at org.elasticsearch.search.aggregations.support.values.ScriptLongValues.advanceExact(ScriptLongValues.java:51) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.composite.LongValuesSource$1.collect(LongValuesSource.java:174) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregator$1.collect(CompositeAggregator.java:190) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by matriv**
Previously, CASE and IIF when translated to painless scripts
(used in GROUP BY, HAVING, WHERE) a custom `caseFunction` registered
in the `InternalSqlScriptUtils` was used. This function received and
array of arbitrary length:
```
[condition1, result1, condition2, result2, ... elseResult]
```
Painless doesn't know of the context and therefore is evaluating
all conditions and results before invoking the `caseFunction` on them.
As a consequence erroneous results (i.e. division by 0) where always
evaluated despite of the guarding condition.

Replace the `caseFunction` with painless `<cond> ? <res1> : <res2>`
expressions to properly guard the result expressions and only evaluate
the one for which its guarding condition evaluates to true (or of course
the elseResult).

As a bonus, this approach includes performance benefits since we avoid
unnecessary evaluations of both conditions and result expressions.

Fixes: #49672

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java [hunk 1]
```diff
@@ -161,14 +161,24 @@ public ScriptTemplate asScript() {
         }
         templates.add(asScript(elseResult));
 
-        StringJoiner template = new StringJoiner(",", "{sql}.caseFunction([", "])");
+        // Use painless if-else expressions to prevent evaluation of return expression
+        // if the condition is guarded by evaluates to false (e.g. division by 0)
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java:165]: `...is guarded by evaluation to...`?

**Review by bpintea — APPROVED** [review]
nice solution.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java [hunk 2]
```diff
@@ -161,14 +161,24 @@ public ScriptTemplate asScript() {
...
+        StringBuilder sb = new StringBuilder();
         ParamsBuilder params = paramsBuilder();
-
-        for (ScriptTemplate scriptTemplate : templates) {
-            template.add(scriptTemplate.template());
+        for (int i = 0; i < templates.size(); i++) {
+            ScriptTemplate scriptTemplate = templates.get(i);
+            if (i < templates.size() - 1) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java:170]: Why is nullSafeFilter added at this level  - we already add it (or should do so) on the top-level (`ScriptQuery`), why does this has to happen inside `Case`?

**Review by costin — COMMENTED** [review]
Left some comments.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java:170]: Because the painless `? :` operator complains when receives a `Boolean` object instead of primitive `boolean`.

Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/predicate/conditional/Case.java:170]: I see - the nullSafe then is a good wrapper. Please add a comment since this Painless behavior is not obvious looking at the assembly.

**Review by costin — APPROVED** [review]
LGTM
