### PR TITLE
SQL: Fix issue with complex HAVING and GROUP BY ordinal

### LINKED ISSUE #36059: SQL: GroupBy with ordinal returns an error
```
SELECT gender AS g,
  SUM({fn CONVERT(emp_no, SQL_BIGINT)}) AS "sum"
FROM test_emp
GROUP BY 1
HAVING (NOT (SUM({fn CONVERT(emp_no, SQL_BIGINT)}) IS NULL));
```
throws:
```
java.sql.SQLDataException: line 4:10: Group ordinal 1 refers to an aggregate function Alias which is not compatible/allowed with GROUP BY
```

### PR DESCRIPTION
**Pull request by matriv**
When trying to analyze a HAVING condition, we crate a temp Aggregate
Plan which wasn't created correctly (missing the expressions from the
SELECT clause) and as a result the ordinal (1, 2, etc) in the GROUP BY
couldn't be resolved correctly.

Also after successfully analyzing the HAVING condition, still the
original plan was returned.

Fixes: #36059

### CODE REVIEW

**Comment by costin** [comment]
Maybe add a description of the approach taken and what failed ?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/rule/RuleExecutor.java [hunk 1]
```diff
@@ -152,6 +152,9 @@ protected ExecutionInfo executeWithInfo(TreeType plan) {
                 batchRuns++;
 
                 for (Rule<?, TreeType> rule : batch.rules) {
+                    if (log.isTraceEnabled()) {
+                        log.trace("Trying to apply rule {}", rule);
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/rule/RuleExecutor.java]: "About to apply rule" - trying implies that it might not be applied.

**Review by costin — APPROVED** [review]
LGTM.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/rule/RuleExecutor.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/rule/RuleExecutor.java]: Which can be the case... But I prefer the "About to apply rule"

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java [hunk 2]
```diff
@@ -209,7 +209,7 @@ public void testGroupByOrderByScalarOverNonGrouped_WithHaving() {
     }
 
     public void testGroupByHavingNonGrouped() {
-        assertEquals("1:48: Cannot filter by non-grouped column [int], expected [text]",
+        assertEquals("1:48: Cannot filter HAVING on non-aggregate [int]; consider using WHERE instead",
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: Why are we losing here the `text` proposal? Can we still have it?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java [hunk 3]
```diff
@@ -396,6 +390,21 @@ public void testTranslateMathFunction_HavingClause_Painless() {
         assertThat(aggFilter.scriptTemplate().params().toString(), endsWith(", {v=10}]"));
     }
 
+    public void testGroupByAndHavingWithFunctionOnTopOfAggregation() {
+        LogicalPlan p = plan("SELECT keyword, max(int) FROM test GROUP BY 1 HAVING " + "abs(max(int)) > 10");
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java]: `HAVING " + "abs(max(int))` - one String only, no need to split it in half.

**Review by astefan — APPROVED** [review]
LGTM. Left two comments

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 3 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java]: yep, was some leftover

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: Thx for catching it, I had it in mind but forgot to open a relevant issue for that.
Here it is: #36693

**Comment by matriv** [comment]
Backported to `6.5` with dead7c6c65f7bb259aec08720dc63cff2d33fd36
