### PR TITLE
Do not copy index.default_pipeline and index.final_pipeline

### LINKED ISSUE #96478: Prevent downsample indices to inherit pipeline-related index settings
### Elasticsearch Version

8.7

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

All

### Problem Description

When downsampling a source index into a target index, the target index is created copying some settings from the source index. Among the settings we copy there are two of them `index.default_pipeline` and `index.final_pipeline` which control execution of ingest pipelines for the (target) index. As a result of the transformation we apply to the target (downsampled) index, including aggregation of metric fields, it is possible that the pipeline script execution fails because metric fields (counters, gauges and so on) are converted to `aggregate_metric_double` fields. These fields are not accessible in the same way as the original ones since they are of different type and because they just include aggregate metrics (sum, min, max and value_count).

We need to skip copying the two settings, `index.default_pipeline` and `index.final_pipeline`, from the source index to the target index in order to avoid pipeline processing to be applied to the target (downsampled) index.

### Steps to Reproduce

Try to downsample a source index that has the following two settings `index.default_pipeline` and `index.final_pipeline`. The target index will include the same settings. That should not be the case.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by salvatore-campagna**
We need to skip copying the two settings, index.default_pipeline and index.final_pipeline, from the source index to the target index in order to avoid pipeline processing to be applied to the target (downsampled) index.
Some pipeline scripts might fail due to the differences in mappings and settings between the downsampling source and target index.

Resolves #96478

### CODE REVIEW

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java [hunk 1]
```diff
@@ -584,12 +591,16 @@ private IndexMetadata.Builder copyIndexMetadata(IndexMetadata sourceIndexMetadat
                 // the same rules with resize apply
                 continue;
             }
+            if (FORBIDDEN_SETTINGS.contains(key)) {
+                continue;
+            }
             // Do not override settings that have already been set in the rollup index.
```
Comment (martijnvg) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/downsample/TransportDownsampleAction.java:597]: maybe update this comment too?

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by salvatore-campagna** [comment]
I forgot to push the yaml test... 🤔
