### PR TITLE
Validate top-level keys when parsing mget requests

### LINKED ISSUE #23720: Bad error message when misspelling docs in _mget
**Elasticsearch version**: 5.x

**JVM version**: 8

**OS version**: OSX 10.11.6

**Description of the problem including expected versus actual behavior**: When searching _mget and passing `{"doc": []}` (misspelling `docs`), should throw a better error message when seeing the array.

**Steps to reproduce**:
`doc` instead of `docs`:
```
GET _mget
{
  "doc" : [
    {
      "_index" : "orders-current",
      "_type" : "order",
      "_id" : 6
    },
    {
      "_index" : "products",
      "_type" : "product",
      "_id" : 4321
    }
  ]
}
```

Error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: no documents to get;"
      }
    ],
    "type": "action_request_validation_exception",
    "reason": "Validation Failed: 1: no documents to get;"
  },
  "status": 400
}
```

@dakrone

### PR DESCRIPTION
**Pull request by jasontedor**
Today, when parsing mget requests, we silently ignore keys in the top level that do not match "docs" or "ids". This commit addresses this situation by throwing an exception if any other key occurs here, and providing the names of valid keys.

Closes #23720

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java [hunk 1]
```diff
@@ -327,6 +328,13 @@ public MultiGetRequest add(@Nullable String defaultIndex, @Nullable String defau
...
                     parseIds(parser, this.items, defaultIndex, defaultType, defaultFields, defaultFetchSource, defaultRouting);
+                } else {
+                    final String message = String.format(
+                            Locale.ROOT,
+                            "Unknown key [%s] for a %s, expected [docs] or [ids]",
+                            currentFieldName,
+                            token);
+                    throw new ParsingException(parser.getTokenLocation(), message);
                 }
             }
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java]: should we also add another else where we throw error if the token is not field_name nor start_object?

**Review by javanna — APPROVED** [review]
left a small comment LGTM otherwise

File: core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java]: I pushed a7c986306b99e367e73a1c2a56944e9724a6b33c.

**Comment by jasontedor** [comment]
Thanks @javanna, I pushed a commit responding to your feedback if you want to take another look.

File: rest-api-spec/src/main/resources/rest-api-spec/test/mget/12_non_existent_index.yaml [hunk 2]
```diff
@@ -21,7 +21,6 @@
   - do:
       mget:
         body:
-          index:  test_2
```
Comment (javanna) [inline rest-api-spec/src/main/resources/rest-api-spec/test/mget/12_non_existent_index.yaml]: nice one!

**Review by javanna — APPROVED** [review]
LGTM thanks

**Comment by jasontedor** [comment]
Thank you @javanna.
