### PR TITLE
Increase timeout for index migration in FullClusterRestartSystemIndexCompatibilityIT

### LINKED ISSUE #127245: [CI] FullClusterRestartSystemIndexCompatibilityIT testAsyncSearchIndexMigration {p0=8.18.0} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8038 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/j5gwfl6cv6ooa)
- [elasticsearch-periodic-platform-support #8032 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/4tidxvo4v4ruk)
- [elasticsearch-periodic-platform-support #8014 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/k5jsezuvlhcyo)

**Reproduction Line:**
```
gradlew ":qa:lucene-index-compatibility:javaRestTest" --tests "org.elasticsearch.lucene.FullClusterRestartSystemIndexCompatibilityIT" -Dtests.method="testAsyncSearchIndexMigration {p0=8.18.0}" -Dtests.seed=AA972A430176EC91 -Dtests.locale=om-ET -Dtests.timezone=Africa/Bamako -Druntime.java=24
```

**Applicable branches:**
9.0

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.lucene.FullClusterRestartSystemIndexCompatibilityIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testAsyncSearchIndexMigration%20%7Bp0%3D8.18.0%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [9.0] 3 failures in test testAsyncSearchIndexMigration {p0=8.18.0} (2.8% fail rate in 107 executions)
- [9.0] 2 failures in step ubuntu-2404-aarch64_checkpart1_platform-support-arm (40.0% fail rate in 5 executions)
- [9.0] 3 failures in pipeline elasticsearch-periodic-platform-support (60.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by cbuescher**
This test occasionally fails on version 8.19 clusters when we are waiting for system index migration to finish.
This changes the wait time from the 10s default to 30s to account for the occasional super slow cluster in tests.

Closes #127245

### CODE REVIEW

File: qa/lucene-index-compatibility/src/javaRestTest/java/org/elasticsearch/lucene/FullClusterRestartSystemIndexCompatibilityIT.java [hunk 1]
```diff
@@ -83,19 +89,29 @@ public void testAsyncSearchIndexMigration() throws Exception {
...
+                                .equals("IN_PROGRESS")
+                        );
+                    } catch (IOException e) {
+                        throw new AssertionError("System feature migration failed", e);
+                    }
+                });
+            } catch (AssertionError e) {
+                logger.debug(
+                    "--> system index migration not finished yet, response: {}",
+                    EntityUtils.toString(client().performRequest(checkMigrateProgress).getEntity())
```
Comment (original-brownbear) [inline qa/lucene-index-compatibility/src/javaRestTest/java/org/elasticsearch/lucene/FullClusterRestartSystemIndexCompatibilityIT.java:111]: Does this tell us much though when we execute it after the busy wait ran? Maybe instead we should/could make the responses part of the assertion error we accumulate?
They should be tiny anyway?

**Comment by cbuescher** [comment]
@original-brownbear changed the PR to increase the timeout instead of the previous additional logging after our direct conversation.

**Review by original-brownbear — APPROVED** [review]
