### PR TITLE
Use direct mapping call in Kernel32Library

### LINKED ISSUE #9802: Kernel32LibraryTests creates JNA proxy classes
With the current tests policy in place, this hits SecurityException (e.g. http://build-us-00.elasticsearch.org/job/es_core_master_window-2012/1004/console).

Does the functionality or just the test need to create these proxies? Can we avoid it? Otherwise, we can add this permission, but it is a little bit strange that JNA for e.g. unix mlockall does not need to create proxies but on windows it does.

 Caused by: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "newProxyInPackage.org.elasticsearch.common.jna")
  1>     java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
  1>     java.security.AccessController.checkPermission(AccessController.java:884)
  1>     java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
  1>     [...java.lang.reflect.*]
  1>     com.sun.jna.Native.loadLibrary(Native.java:415)
  1>     com.sun.jna.Native.loadLibrary(Native.java:391)
  1>     org.elasticsearch.common.jna.Kernel32Library.<init>(Kernel32Library.java:50)
  1>     org.elasticsearch.common.jna.Kernel32Library.<init>(Kernel32Library.java:36)
  1>     org.elasticsearch.common.jna.Kernel32Library$Holder.<clinit>(Kernel32Library.java:45)
  1>     org.elasticsearch.common.jna.Kernel32Library.getInstance(Kernel32Library.java:60)
  1>     org.elasticsearch.common.jna.Kernel32LibraryTests.testKernel32Library(Kernel32LibraryTests.java:74)

### PR DESCRIPTION
**Pull request by tlrx**
This commit modifies the Kernel32Library to use direct mapping instead of a proxy class when doing native calls on Windows platforms. It also adds the "createSecurityManager" permission to the tests.policy file, and adds unit tests that should have failed when the Java security manager is enabled.

Closes #9802

### CODE REVIEW

**Comment by tlrx** [comment]
@rmuir @s1monw Can you have a look please?

**Comment by rmuir** [comment]
This looks much simpler to me!

File: src/main/java/org/elasticsearch/common/jna/Kernel32Library.java [hunk 1]
```diff
@@ -37,17 +36,21 @@
 
     private static ESLogger logger = Loggers.getLogger(Kernel32Library.class);
 
-    private Kernel32 internal;
+    private boolean loaded = false;
```
Comment (rmuir) [inline src/main/java/org/elasticsearch/common/jna/Kernel32Library.java]: Can we remove this boolean? There is only one constructor for this class, so if it succeeds, then we loaded. otherwise we have no object to call addConsoleCtrlHandler() on, so we can remove the check for it there, too.

**Comment by rmuir** [comment]
@tlrx i added a comment, but this looks good to me.

File: src/main/java/org/elasticsearch/common/jna/Kernel32Library.java (hunk 1 above)
Comment (rmuir) [inline src/main/java/org/elasticsearch/common/jna/Kernel32Library.java]: and i guess where we instantiate singleton, we just let Kernel32Library be null if it cant load? I dont know if its cleaner actually, it means callers woudl have to check for that. i just think its wierd to have all methods have to check isLoaded and do nothing. Currently there are only a few, but if the class increases...

Comment (tlrx) [inline src/main/java/org/elasticsearch/common/jna/Kernel32Library.java]: Ok, I understand your point. I think we can remove the boolean and the method isLoaded(). If the native lib cannot be loaded, the singleton is still instantiated and not null, but any call to a native method (or call to Kernel32Library.addConsoleCtrlHandler which calls the native SetConsoleCtrlHandler) will throw an UnsatisfiedLinkError which is completely acceptable to me since, well, we are doing native calls :)

**Comment by rmuir** [comment]
+1, looks great.
