### PR TITLE
Significant terms test refactor for extendability

### LINKED ISSUE #75442: [CI] ChiSquareTests testBasicScoreProperties failing
The failing value, -7.655210869425632E17, is very very close to zero, and arguably equal to zero given the limitations of floating point precision.  It may be best to `assert` in the core code that the value is greater than -0.1, then just return the max of zero and the calculation result so the caller never sees the very slightly negative numbers

**Build scan:**
https://gradle-enterprise.elastic.co/s/mdipouk6dxa6q/tests/:server:test/org.elasticsearch.search.aggregations.bucket.terms.heuristic.ChiSquareTests/testBasicScoreProperties

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.heuristic.ChiSquareTests.testBasicScoreProperties" -Dtests.seed=C39AB4684F293C4A -Dtests.locale=es-NI -Dtests.timezone=America/Phoenix -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.bucket.terms.heuristic.ChiSquareTests&tests.test=testBasicScoreProperties

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a value equal to or greater than <0.0>
     but: <-7.655210869425632E17> was less than <0.0>

  at __randomizedtesting.SeedInfo.seed([C39AB4684F293C4A:73E11A2551D3680A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.search.aggregations.bucket.terms.AbstractSignificanceHeuristicTests.testBasicScoreProperties(AbstractSignificanceHeuristicTests.java:147)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by benwtrent**
The original PR https://github.com/elastic/elasticsearch/pull/75264 made some test mistakes

NXY Significant term heuristics have additional values that need to be set when testing
basicScore properties.

Additionally, previous refactor kept the abstract test class in a package that other plugins
don't have access to.

closes https://github.com/elastic/elasticsearch/issues/75442

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/heuristic/ChiSquareTests.java [hunk 1]
```diff
@@ -8,21 +8,17 @@
...
+    public void testAssertions() {
+        testBackgroundAssertions(new ChiSquare(true, true), new ChiSquare(true, false));
     }
 
     @Override
-    public void testAssertions() {
-        testBackgroundAssertions(new ChiSquare(true, true), new ChiSquare(true, false));
+    protected SignificanceHeuristic getHeuristic(boolean includeNegatives, boolean backgroundIsSuperset) {
+        return new ChiSquare(includeNegatives, backgroundIsSuperset);
     }
```
Comment (not-napoleon) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/heuristic/ChiSquareTests.java:23]: ...okay github, that's an interesting way to interpret that change

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+ * in compliance with, at your election, the Elastic License 2.0 or the Server
+ * Side Public License, v 1.
+ */
+
+package org.elasticsearch.search.aggregations.bucket;
+
+import org.elasticsearch.search.aggregations.bucket.terms.heuristic.SignificanceHeuristic;
+
+/**
+ * Abstract test case for testing significant term heuristics
```
Comment (not-napoleon) [inline test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java:14]: Maybe a little more detail here?  What makes the NXY version different than plain old `AbstractSignigicanceHeuristicTestCase`.  What does NXY even mean here?

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+     * @return A random instance of the heuristic to test
+     */
+    @Override
+    protected SignificanceHeuristic getHeuristic() {
+        return getHeuristic(randomBoolean(), randomBoolean());
+    }
+
+    /**
+     * @param includeNegatives value for this test run
+     * @param backgroundIsSuperset value for this test run
```
Comment (not-napoleon) [inline test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java:28]: Again, I think a little more detail would be helpful.  Think about reading this as a new developer coming to this code.  Include negative what?  What does `backgroundIsSuperset` mean?  Superset of what?

**Review by not-napoleon — APPROVED** [review]
This looks okay to me.  I left a couple of notes on javadoc I'd like to see expanded a bit though.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/heuristic/ChiSquareTests.java (hunk 1 above)
Comment (benwtrent) [reply server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/heuristic/ChiSquareTests.java:23]: yeah, sorry :(. It looked cleaner on a local `git diff`

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java (hunk 2 above)
Comment (benwtrent) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java:14]: I wish I knew what NXY meant, but that is what they are called...Will add some stuff.

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java (hunk 3 above)
Comment (benwtrent) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java:28]: `backgroundIsSuperset` is that its the super set of the "subset". Otherwise they are treated as two disjoint sets. Will add some docs.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/heuristic/ChiSquareTests.java (hunk 1 above)
Comment (not-napoleon) [reply server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/heuristic/ChiSquareTests.java:23]: Not your fault.  I think github optimizes for minimal edit distance, not fewest lines changed.  I got the point though, and that's all that matters.

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java (hunk 2 above)
Comment (not-napoleon) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/bucket/AbstractNXYSignificanceHeuristicTestCase.java:14]: :lolsob:  Well, at least I'm not the only one.
