### PR TITLE
[Transform] Retry when failing to start indexer

### LINKED ISSUE #128221: [Transform] Stuck in Stopping
There is a chance that a Transform can get stuck in `Stopping` if it fails to update its status and register the Transform thread.
- [TransformTask](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java#L303) updates the cluster state with the Transform's persistent Task. If that update fails, the persistent task will remain alive but the Transform indexer thread gets marked as `Stopped`.
- [TransformStats](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/TransformStats.java#L244) displays a `Stopped` indexer as `Stopping`, because the persistent task exists but the indexer thread is not running.

Workaround:
- Stop the Transform with `?force=true`, which will remove the persistent task
- Start the Transform

### PR DESCRIPTION
**Pull request by prwhelan**
Bug: when the indexer state fails to save during a cluster state update, the Transform is stuck in STOPPING and cannot be restarted unless the user force stops to delete the task.

Fix: the task will continuously retry starting the indexer until the cluster state update can succeed.

Notes:
- users can cancel the retry by force stopping the transform
- the retry is displayed in the UI as "degraded" with a message as to why the transform is restarting
- the transform now displays as STARTING rather than STOPPING until it successfully starts
- the retry is audited so it displays in the Messages tab of the UI
- the retry timer is randomly selected between 45s and 90s, this should help during rolling restarts for clusters that have a large amount of transforms

Fix #128221

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformPersistentTasksExecutor.java [hunk 1]
```diff
@@ -485,17 +488,57 @@ private ActionListener<Boolean> retryListener(TransformTask task) {
...
+                params.requiresRemote()
+            );
+            logger.debug("Failed to start Transform, retrying in [{}] seconds.", retryTimer.seconds());
+            // tell the user when and why the retries are happening and how to stop them
+            // force stopping will eventually deregister this retry task from the scheduler
+            auditor.warning(
+                params.getId(),
+                Strings.format(
+                    "Failed while starting Transform. Automatically retrying every [%s] seconds. "
+                        + "To cancel retries, force stop this transform. Failure: [%s]",
```
Comment (jonathan-buttner) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformPersistentTasksExecutor.java]: What do you think about including the force stop command in the message here? Or is it expected that the user would do that via a UI button (I'm imagining it being done from the dev console)?

**Review by jonathan-buttner — APPROVED** [review]

**Comment by prwhelan** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/154900)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
