### PR TITLE
Reenable PingAndInfoIT.testXPackInfo() on 6.x

### LINKED ISSUE #34386: [CI] PingAndInfoIT#testXPackInfo fails on 6.x
PingAndInfoIT#testXPackInfo fails on 6.x branch. I can reproduce this locally.

```
 ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=10E186DE107D69A4 \
  -Dtests.class=org.elasticsearch.client.PingAndInfoIT \
  -Dtests.method="testXPackInfo" \
  -Dtests.security.manager=true \
  -Dtests.locale=he \
  -Dtests.timezone=Europe/Volgograd \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Failure:

```
FAILURE 0.67s | PingAndInfoIT.testXPackInfo <<< FAILURES!
   > Throwable #1: org.junit.ComparisonFailure: expected:<[]6.5.0> but was:<[based on ]6.5.0>
   >    at __randomizedtesting.SeedInfo.seed([10E186DE107D69A4:F8BD46DAC76111C3]:0)
   >    at org.elasticsearch.client.PingAndInfoIT.testXPackInfo(PingAndInfoIT.java:87)
   >    at java.lang.Thread.run(Thread.java:748)
```

CI instances:
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=opensuse/53/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/53/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/53/console

### PR DESCRIPTION
**Pull request by tlrx**
The version exposed in ML feature set are extracted from the ML engine.
The format of the version have changed (see https://github.com/elastic/elasticsearch/pull/38168#pullrequestreview-199014466) . 

This PR unmutes the test.

Closes #34386

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/PingAndInfoIT.java [hunk 1]
```diff
@@ -85,8 +88,8 @@ public void testXPackInfo() throws IOException {
         assertNotNull(ml.description());
         assertTrue(ml.available());
         assertTrue(ml.enabled());
-        assertEquals(mainResponse.getVersion().toString(),
-                ml.nativeCodeInfo().get("version").toString().replace("-SNAPSHOT", ""));
+        assertThat(ml.nativeCodeInfo().get("version").toString().replace("-SNAPSHOT", ""),
+            anyOf(equalTo(mainResponse.getVersion().toString()), startsWith("based on " + mainResponse.getVersion().toString())));
```
Comment (droberts195) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/PingAndInfoIT.java]: I don't think this test should tolerate "based on".  The ml-cpp build system adds "based on" to the version when it builds a repo with uncommitted changes.  CI should never be testing ml-cpp builds with uncommitted changes, and we should never have uploaded such a build to the official download location on S3.

Please can you try changing this PR to _just_ unmute the test, and leave the assertion as it was before.  If this test then fails in the PR build then I'll take over and find out what is wrong now.

This test was muted around 18th October 2018, when we switched over from building ml-cpp snapshots on the old Prelert Jenkins to building on infra's Jenkins at elasticsearch-ci.elastic.co.  For a few days there was a problem where ml-cpp built within a Docker container on infra's setup had a crazy idea of the state of the git repo within the Docker container because it was relying on symlinks to directories outside of the Docker container to optimize the cloning process (inherited from the elasticsearch repo's worker setup).  We fixed this in elastic/ml-cpp#270 after debugging using elastic/ml-cpp#269.  The full story is in elastic/infra#7464.

It's unfortunate that nobody in the ML team was pinged when this test was muted, as we could have dealt with unmuting at the same time as we fixed the underlying problem.  (In fact, you can see from the dates of those other issues and PRs that I linked that we didn't notice there was a problem for a couple of days after the ES test failure revealed it.)

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/PingAndInfoIT.java]: Thanks David for explaining the whole story around this. I wasn't sure about the tagged/dev differences and that's why I pinged you directly.


> Please can you try changing this PR to _just_ unmute the test, and leave the assertion as it was before. If this test then fails in the PR build then I'll take over and find out what is wrong now.

Done. It doesn't fail on master so I expect it to be fine in 6.x too.

> It's unfortunate that nobody in the ML team was pinged when this test was muted, as we could have dealt with unmuting at the same time as we fixed the underlying problem.

I agree. But this kind of things happen when we have to deal with a large number of failures :(

**Comment by tlrx** [comment]
@droberts195 I updated the test according to your comment. Can you have another look please?

**Review by droberts195 — APPROVED** [review]
LGTM assuming that test passes now

**Comment by droberts195** [comment]
Thanks for working on this @tlrx!

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample
