### PR TITLE
Move the FIPS configuration back to the build plugin

### LINKED ISSUE #41721: [ci] corrupted keystore on java8 fips build
7.x periodic fips builds have been failing since 19 April with this, unsure if the master equivalent is also effected as it has not run since 7 April

```
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin
```

```
  2> REPRODUCE WITH: ./gradlew :integTestRunner --tests "org.elasticsearch.example.painlesswhitelist.PainlessWhitelistClientYamlTestSuiteIT.test {yaml=painless_whitelist/30_static/custom static imported method}" -Dtests.seed=927E287605F73A70 -Dtests.security.manager=true -Dtests.locale=mt -Dtests.timezone=Egypt -Dcompiler.java=12 -Druntime.java=8FIPS
  2> java.lang.IllegalStateException: could not create the default ssl context

        Caused by:
        java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)

            Caused by:
            java.security.KeyStoreException: problem accessing trust store

                Caused by:
                java.io.IOException: BCFKS KeyStore corrupted: MAC calculation failed.
```

Earliest https://scans.gradle.com/s/pvn346idu54go/tests/orjfcz7hu5lqq-o3tyn5hvqpucy
Most recent (slightly different stack trace) https://scans.gradle.com/s/kzcihhmmfxx54/tests/orjfcz7hu5lqq-axhth7m5yd5sq

### PR DESCRIPTION
**Pull request by alpar-t**
This is necesary for external users of build-tools.
Closes #41721

### CODE REVIEW

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy [hunk 1]
```diff
@@ -116,6 +116,21 @@ class BuildPlugin implements Plugin<Project> {
         configureTestTasks(project)
         configurePrecommit(project)
         configureDependenciesInfo(project)
+
+        // Common config when running with a FIPS-140 runtime JVM
```
Comment (jkakavas) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy]: Maybe add a comment on why this is left in the BuildPlugin so that we won't move it again in the future?

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by mark-vieira** [comment]
Since this is mainly for external users of `build-tools`, do we really need to backport this change? Isn't `build-tools` published only from `master`?

**Comment by rjernst** [comment]
> Isn't build-tools published only from master?

build-tools is published every time we do a release, from the release branch, never from master. The versioning of build-tools matches elasticsearch's versioning

**Comment by mark-vieira** [comment]
> build-tools is published every time we do a release, from the release branch, never from master. The versioning of build-tools matches elasticsearch's versioning

Thanks for the clarification!

**Comment by mark-vieira** [comment]
FWIW, this is going to conflict a bit with #41392 so if that gets merged first this'll have to get tweaked a bit.

**Review by mark-vieira — APPROVED** [review]
