### PR TITLE
[Transform] Don't search if all indices are unchanged between checkpoints

### LINKED ISSUE #77137: [Transform] If there are no changes to source indices between checks then all indices are searched
One of the security solution tests is getting this error from transforms:

```
Failed to index documents into destination index due to permanent error: [org.elasticsearch.xpack.transform.transforms.BulkIndexingException: Bulk index experienced [1] failures and at least 1 irrecoverable [org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [data_stream.dataset] of type [constant_keyword] in document with id 'Xy_cEPawfBodqd3xVPy9vEgAAAAAAAAA'. Preview of field's value: 'elastic_agent.elastic_agent'; java.lang.IllegalArgumentException: [constant_keyword] field [data_stream.dataset] only accepts values that are equal to the value defined in the mappings [endpoint.metadata], but got [elastic_agent.elastic_agent]].; org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [data_stream.dataset] of type [constant_keyword] in document with id 'Xy_cEPawfBodqd3xVPy9vEgAAAAAAAAA'. Preview of field's value: 'elastic_agent.elastic_agent'; java.lang.IllegalArgumentException: [constant_keyword] field [data_stream.dataset] only accepts values that are equal to the value defined in the mappings [endpoint.metadata], but got [elastic_agent.elastic_agent]]
```

The Elasticsearch log file shows this:

```
    info [o.e.x.t.t.ClientTransformIndexer] [local] [endpoint.metadata_current-default-1.1.1] Failed to create a point in time reader, falling back to normal search.
         org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: [index] is not specified;
           at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:15) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
           at org.elasticsearch.action.search.OpenPointInTimeRequest.validate(OpenPointInTimeRequest.java:67) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
...
```

There are no more errors in the log, but I strongly suspect the next step is then to do a normal search with no indices specified, which means search _all_ indices as in `GET _search` :scream:.

This would then explain why the output of the transform contains information from a logs index rather than a metrics index.

The bug was most likely introduce in #75839 and the line at fault is most likely to be: https://github.com/elastic/elasticsearch/blob/4974a7cd7bb47f3d1921e77a835d30cc6b1539ff/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java#L1159

In the case where `changeCollector.getIndicesToQuery()` returns an empty collection we need to skip the search entirely instead of searching all indices.

It should be possible to put together an integration test that tests the scenario of no changes to the source indices between two successive runs of a transform.  If the theory above is correct then this will reproduce the problem and validate the fix.

This problem is in 7.16 and above, so can easily be fixed before it affects end users.

### PR DESCRIPTION
**Pull request by droberts195**
When every index that a transform is configured to search has
remained completely unchanged between checkpoints the transform
should not do a search at all.

Following #75839 there was a problem where the scenario of all
indices being unchanged between checkpoints could cause an empty
list of indices to be searched, which Elasticsearch treats as
meaning _all_ indices. This change should prevent that happening
in future.

Fixes #77137

### CODE REVIEW

**Comment by droberts195** [comment]
Labelled `>non-issue` because it's fixing a problem in an unreleased version.

This proved to be very hard to test within the existing framework for testing continuous transforms using an external cluster.  That framework repeatedly stops and starts the continuous transforms.  Doing this appears to make the transform go through a different code path that never passed through the search avoidance code.  Any advice on how to add this without adding a completely new continuous transform test framework would be gratefully received.  Alternatively, maybe the QA tests can be used to guard against any regressions.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 1]
```diff
@@ -455,20 +455,27 @@ private void injectPointInTimeIfNeeded(
         );
     }
 
-    private void doSearch(Tuple<String, SearchRequest> namedSearchRequest, ActionListener<SearchResponse> listener) {
-        logger.trace(() -> new ParameterizedMessage("searchRequest: [{}]", namedSearchRequest.v2()));
+    void doSearch(Tuple<String, SearchRequest> namedSearchRequest, ActionListener<SearchResponse> listener) {
+        SearchRequest searchRequest = namedSearchRequest.v2();
+        // We want to treat a request to search 0 indices as a request to do nothing, not a request to search all indices
+        if (searchRequest.indices().length == 0) {
+            logger.debug("[{}] Search optimized to noop; request [{}]", getJobId(), searchRequest);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:462]:
```suggestion
            logger.debug(() -> new ParameterizedMessage("[{}] Search optimized to noop; request [{}]", getJobId(), searchRequest));
```
Serializing the search request to string could be non trivial

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 2]
```diff
@@ -455,20 +455,27 @@ private void injectPointInTimeIfNeeded(
...
+            listener.onResponse(null);
+            return;
+        }
+        logger.trace("searchRequest: [{}]", searchRequest);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:466]:
```suggestion
        logger.trace(() -> new ParameterizedMessage("searchRequest: [{}]", searchRequest));
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 3]
```diff
@@ -1168,7 +1166,7 @@ private SearchRequest buildQueryToUpdateDestinationIndex() {
         }
 
         sourceBuilder.query(queryBuilder);
-        logger.debug(() -> new ParameterizedMessage("[{}] Querying for data: {}", getJobId(), sourceBuilder));
+        logger.debug("[{}] Querying {} for data: {}", getJobId(), request.indices(), sourceBuilder);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:1169]: I always thought that the logger would serialize the strings unless we provided a message provider. 

Consequently, if we weren't on debug level, we are serializing the sourceBuilder unnecessarily.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 4]
```diff
@@ -1131,7 +1129,7 @@ private SearchRequest buildQueryToFindChanges() {
         // TODO: if buildChangesQuery changes the query it get overwritten
         sourceBuilder.query(filteredQuery);
 
-        logger.debug("[{}] Querying for changes: {}", getJobId(), sourceBuilder);
+        logger.debug("[{}] Querying {} for changes: {}", getJobId(), request.indices(), sourceBuilder);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:1132]: `ParameterizedMessage`?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:462]: Also, it would be good to log which named search was optimized `namedSearchRequest.v1()`

Comment (droberts195) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:462]: The `debug()` method is calling https://github.com/apache/logging-log4j2/blob/85b564a49f420fbcb9ac8abd3a20a252303d8198/log4j-api/src/main/java/org/apache/logging/log4j/spi/AbstractLogger.java#L449 which takes `Object` arguments.  They only have their `toString()` methods called if logging at the level is enabled.  As far as I can see the `ParameterizedMessage` approach is only necessary when you want to log _both_ a parameterized message _and_ an exception with stack trace.

Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:462]: AH! Cool! Well, forget about the message supplier stuff, but having the search name would be nice.

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
> This proved to be very hard to test within the existing framework for testing continuous transforms using an external cluster. That framework repeatedly stops and starts the continuous transforms. Doing this appears to make the transform go through a different code path that never passed through the search avoidance code.

I did a manual test instead that proves the changes of this PR work.  However, there might also be some other bug that the automated tests aren't revealing because they repeatedly stop and restart the "continuous" transforms.

This is what I did:

1. Run Elasticsearch locally using `./gradlew run -Drun.license_type=trial -Dtests.heap.size=4`
2. Run Kibana locally using `yarn kbn bootstrap` followed by `yarn start`
3. Log into Kibana
4. Add the sample eCommerce data: Home -> Try sample data -> Sample eCommerce orders
5. Go to transform management: Stack Management -> Transforms
6. Create a new transform using the `kibana_sample_data_ecommerce` index pattern
7. Create a `Latest` transform using `customer_id` as the unique field, `order_date` as the sort field, `latest_orders` as the transform name and `latest_orders` as the destination index name
8. Select continuous mode with `order_date` as the date field, `10s` delay and `10s` frequency
9. Click "Create and start"
10. Watch the ES log

The transform worked for its initial checkpoint.  The dodgy thing was that the second run that validated this bug fix didn't take place for over 8 minutes:

```
[2021-09-03T11:11:08,411][INFO ][o.e.x.t.t.TransformTask  ] [runTask-0] [latest_orders] updating state for transform to [{"task_state":"started","indexer_state":"stopped","checkpoint":0,"progress":{"docs_indexed":0,"docs_processed":0},"should_stop_at_checkpoint":false}].
[2021-09-03T11:11:08,498][INFO ][o.e.x.t.t.TransformPersistentTasksExecutor] [runTask-0] [latest_orders] successfully completed and scheduled task in node operation
[2021-09-03T11:11:08,627][INFO ][o.e.c.m.MetadataMappingService] [runTask-0] [latest_orders/UWahPSkzRa6PjOfmmSr1eA] update_mapping [_doc]
[2021-09-03T11:11:59,095][INFO ][o.e.c.m.MetadataCreateIndexService] [runTask-0] [.async-search] creating index, cause [auto(bulk api)], templates [], shards [1]/[0]
[2021-09-03T11:12:00,968][INFO ][o.e.c.m.MetadataMappingService] [runTask-0] [.kibana_8.0.0_001/rUYOAIvfRYOb3Agd2wrqYA] update_mapping [_doc]
[2021-09-03T11:12:04,960][INFO ][o.e.c.m.MetadataMappingService] [runTask-0] [.kibana_8.0.0_001/rUYOAIvfRYOb3Agd2wrqYA] update_mapping [_doc]
[2021-09-03T11:20:48,737][DEBUG][o.e.x.t.t.ClientTransformIndexer] [runTask-0] [latest_orders] Search request [apply_results] optimized to noop; searchRequest [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[ignore_unavailable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=false, ignore_aliases=false, ignore_throttled=false], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=false, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"size":0,"query":{"bool":{"filter":[{"match_all":{"boost":1.0}},{"range":{"order_date":{"from":null,"to":1630664438671,"include_lower":true,"include_upper":false,"format":"epoch_millis","boost":1.0}}},{"range":{"order_date":{"from":1630663858500,"to":1630664438671,"include_lower":true,"include_upper":false,"format":"epoch_millis","boost":1.0}}}],"boost":1.0}},"aggregations":{"_transform":{"composite":{"size":5000,"sources":[{"customer_id":{"terms":{"field":"customer_id","missing_bucket":true,"order":"asc"}}}]},"aggregations":{"_top_hits":{"top_hits":{"from":0,"size":1,"version":false,"seq_no_primary_term":false,"explain":false,"sort":[{"order_date":{"order":"desc"}}]}}}}}}}]
```

This seems strange to me given that both `frequency` and `delay` were `10s`.  I don't think this is a bug introduced by this PR, but might be something to investigate separately.

**Review by benwtrent — APPROVED** [review]

**Comment by hendrikmuhs** [comment]
> The transform worked for its initial checkpoint. The dodgy thing was that the second checkpoint that validated this bug fix didn't take place for over 8 minutes:

I think this is by design, because transform should stop early if there are no changes. I wonder why #77137 passed this pre-check.

I will try your repro steps, but enable trace logging, if I suspicion is correct the log should tell us, see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java#L374:

```
logger.trace("[{}] source has not changed, finish indexer early.", getJobId());
```

The reason why after 8 and 16 minutes it found something should be future timestamps in the sample data.

**Comment by hendrikmuhs** [comment]
After enabling trace logging:

```
[2021-09-07T08:55:39,600][DEBUG][o.e.x.t.t.TransformTask  ] [hendrik-p1] [data_frame/transforms/schedule_latest_orders] transform indexer schedule has triggered, state: [STARTED].
[2021-09-07T08:55:39,602][TRACE][o.e.x.t.t.TransformIndexer] [hendrik-p1] [latest_orders] change detected [false].
[2021-09-07T08:55:39,603][TRACE][o.e.x.t.t.TransformIndexer] [hendrik-p1] [latest_orders] source has not changed, finish indexer early.
[2021-09-07T08:56:39,600][DEBUG][o.e.x.t.t.TransformTask  ] [hendrik-p1] [data_frame/transforms/schedule_latest_orders] transform indexer schedule has triggered, state: [STARTED].
[2021-09-07T08:56:39,601][TRACE][o.e.x.t.t.TransformIndexer] [hendrik-p1] [latest_orders] change detected [false].
[2021-09-07T08:56:39,601][TRACE][o.e.x.t.t.TransformIndexer] [hendrik-p1] [latest_orders] source has not changed, finish indexer early.
[2021-09-07T08:57:39,600][DEBUG][o.e.x.t.t.TransformTask  ] [hendrik-p1] [data_frame/transforms/schedule_latest_orders] transform indexer schedule has triggered, state: [STARTED].
[2021-09-07T08:57:39,602][TRACE][o.e.x.t.t.TransformIndexer] [hendrik-p1] [latest_orders] change detected [false].
[2021-09-07T08:57:39,602][TRACE][o.e.x.t.t.TransformIndexer] [hendrik-p1] [latest_orders] source has not changed, finish indexer early.
```

This is expected. 

I think the real problem sits in #75839 and the failures reported in #77310 is probably connected to the change in #75839.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 5]
```diff
@@ -455,22 +455,30 @@ private void injectPointInTimeIfNeeded(
...
 
-    private void doSearch(Tuple<String, SearchRequest> namedSearchRequest, ActionListener<SearchResponse> listener) {
-        logger.trace(() -> new ParameterizedMessage("searchRequest: [{}]", namedSearchRequest.v2()));
+    void doSearch(Tuple<String, SearchRequest> namedSearchRequest, ActionListener<SearchResponse> listener) {
+        String name = namedSearchRequest.v1();
+        SearchRequest searchRequest = namedSearchRequest.v2();
+        // We want to treat a request to search 0 indices as a request to do nothing, not a request to search all indices
+        if (searchRequest.indices().length == 0) {
+            logger.debug("[{}] Search request [{}] optimized to noop; searchRequest [{}]", getJobId(), name, searchRequest);
+            listener.onResponse(null);
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:464]: The introduction of a magic value `null` is dangerous, what if the client returns `null`. It seems better to return an empty result set, so that `null` causes the transform to fail as before.

**Comment by hendrikmuhs** [comment]
I think the bug is a disconnection between sequence id's and timestamp.

Let's take checkpoint A with:

```
timestamp_epoch_seconds: 1000
seq_id's: index1: 20_s1, 21_s2, 22_s3
```

and checkpoint B with:

```
timestamp_epoch_seconds: 1010
seq_id's: index1: 20_s1, 21_s2, 22_s3
```

The change in #75839 calculates the diff between A and B purely on sequence id's. Because they are equal `changes(A,B) = {}`. 

However we must take the timestamp _and_ `delay` into account, because when we query `A` we do _not_ query for all data in A, but for all data in A with `< timestamp_epoch_seconds - delay`.

A could contain documents that are part of the checkpoints w.r.t. to the seq id, but _not_ queried because of `delay`.
