### PR TITLE
Fix CanMatchPreFilterSearchPhaseTests#testInvalidSortShards() test & SearchCancellationIT NPE

### LINKED ISSUE #101416: [CI] CanMatchPreFilterSearchPhaseTests testInvalidSortShards failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/tyb5363335zey/tests/:server:test/org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests/testInvalidSortShards
**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests.testInvalidSortShards" -Dtests.seed=EC8F6AFDBEEC89EC -Dtests.locale=ja -Dtests.timezone=Australia/Broken_Hill -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests&tests.test=testInvalidSortShards

**Failure excerpt:**
```
java.lang.AssertionError: expected:<true> but was:<false>

  at __randomizedtesting.SeedInfo.seed([EC8F6AFDBEEC89EC:9AF2D653D8890A91]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:118)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests.testInvalidSortShards(CanMatchPreFilterSearchPhaseTests.java:473)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by benwtrent**
closes https://github.com/elastic/elasticsearch/issues/101416

Related to: https://github.com/elastic/elasticsearch/issues/99929

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhaseTests.java [hunk 1]
```diff
@@ -442,7 +442,7 @@ public void sendCanMatch(
                 shardsIter,
                 timeProvider,
                 null,
-                true,
+                shardToSkip.size() > shardsIter.size(),
```
Comment (benwtrent) [inline server/src/test/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhaseTests.java:445]: @dnhatn this is interesting, it is possible for this test to randomly skip ALL shards, but we have this logic that prefers matching against at least one local shard. 

To make this test pass I addressed this, but what do you think? Could this also be related to: https://github.com/elastic/elasticsearch/issues/92058 ???

File: test/framework/src/main/java/org/elasticsearch/test/AbstractSearchCancellationTestCase.java [hunk 2]
```diff
@@ -281,7 +281,9 @@ public void onIndexModule(IndexModule indexModule) {
             indexModule.addSearchOperationListener(new SearchOperationListener() {
                 @Override
                 public void onNewReaderContext(ReaderContext c) {
-                    runOnNewReaderContext.get().accept(c);
+                    if (runOnNewReaderContext.get() != null) {
+                        runOnNewReaderContext.get().accept(c);
+                    }
```
Comment (benwtrent) [inline test/framework/src/main/java/org/elasticsearch/test/AbstractSearchCancellationTestCase.java:286]: @JVerwolf take a gander, I noticed that this could throw NPEs as the plugin isn't always initialized in the tests.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @benwtrent.

**Comment by benwtrent** [comment]
@elasticmachine update branch
