### PR TITLE
Fix S3ClientSettings Leak

### LINKED ISSUE #56702: S3Service Leaks S3ClientSettings on Repository Close
There is a small memory leak in `org.elasticsearch.repositories.s3.S3Service`'s handling of `S3ClientSettings`.
If you use a repository definition that includes any setting override in the `Settings` in `RepositoryMetadata` like e.g. `endpoint` then the cached settings instance will never be removed from `org.elasticsearch.repositories.s3.S3Service#derivedClientSettings` when closing the repository even though it's not used by any client any longer.

A reproducer test for the issue would be:

```java
    public void testCachedClientsAreReleased() {
        final S3Service s3Service = new S3Service();
        final Settings settings = Settings.builder().put("endpoint", "http://first").build();
        final RepositoryMetadata metadata = new RepositoryMetadata("first", "s3", settings);
        final S3ClientSettings clientSettings = s3Service.settings(metadata);
        final AmazonS3Reference reference = s3Service.client(metadata);
        reference.close();
        s3Service.close();
        final AmazonS3Reference referenceReloaded = s3Service.client(metadata);
        assertNotSame(referenceReloaded, reference);
        referenceReloaded.close();
        s3Service.close();
        final S3ClientSettings clientSettingsReloaded = s3Service.settings(metadata);
        assertNotSame(clientSettings, clientSettingsReloaded);
    }
```

The last line currently fails, because even though no client remains that uses the `clientSettings` instance the cache still finds cached settings for the given metadata.

This is practically a non-issue and has been around ever since at least 6.8.x without any one noticing. We should still fix the logic in `S3Service` to properly clean up the settings cache at some point.

### PR DESCRIPTION
**Pull request by original-brownbear**
Fixes the fact that repository metadata with the same settings still results in
multiple settings instances being cached as well as leaking settings on closing
a repository.

Closes #56702

### CODE REVIEW

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java [hunk 1]
```diff
@@ -214,6 +215,7 @@ private synchronized void releaseCachedClients() {
         }
         // clear previously cached clients, they will be build lazily
         clientsCache = emptyMap();
+        derivedClientSettings = emptyMap();
```
Comment (original-brownbear) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java:218]: The logic of just blank clearing out everything here isn't great but with the complicated way in which we handle the AWS references I figured I'd rather not make this code more complicated and for now keep invalidating the whole cache on closing any repo.

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java [hunk 2]
```diff
@@ -57,7 +57,7 @@
      * Client settings derived from those in {@link #staticClientSettings} by combining them with settings
      * in the {@link RepositoryMetadata}.
      */
-    private volatile Map<S3ClientSettings, Map<RepositoryMetadata, S3ClientSettings>> derivedClientSettings = emptyMap();
+    private volatile Map<S3ClientSettings, Map<Settings, S3ClientSettings>> derivedClientSettings = emptyMap();
```
Comment (original-brownbear) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java:60]: Keying this by metadata was just plain wrong. The whole point of this map was to not duplicate `S3ClientSettings` but no two repos will ever share the exact same metadata obviously ... moving this to settings since only the `Settings` in the metadata go into the derived settings anyway.

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java [hunk 3]
```diff
@@ -57,7 +57,7 @@
      * Client settings derived from those in {@link #staticClientSettings} by combining them with settings
      * in the {@link RepositoryMetadata}.
      */
-    private volatile Map<S3ClientSettings, Map<RepositoryMetadata, S3ClientSettings>> derivedClientSettings = emptyMap();
+    private volatile Map<Settings, S3ClientSettings> derivedClientSettings = emptyMap();
```
Comment (original-brownbear) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java:60]: This was way over-engineered. Since we don't have any selective cache invalidation when the static settings get refreshed, using this kind of complicated map was completely pointless.

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java [hunk 4]
```diff
@@ -179,14 +178,13 @@ private S3ClientSettings(S3BasicCredentials credentials, String endpoint, Protoc
     /**
      * Overrides the settings in this instance with settings found in repository metadata.
      *
-     * @param metadata RepositoryMetadata
+     * @param settings found in repository metadata
      * @return S3ClientSettings
      */
-    S3ClientSettings refine(RepositoryMetadata metadata) {
-        final Settings repoSettings = metadata.settings();
+    S3ClientSettings refine(Settings settings) {
```
Comment (fcofdez) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java:184]: nit: maybe we can name the parameter `repositorySettings`?

**Review by fcofdez — APPROVED** [review]
Other than the minor naming comment, LGTM.

**Comment by original-brownbear** [comment]
Thanks Francisco!
