### PR TITLE
Fix Snapshot Out of Order Finalization Repo Corruption

### LINKED ISSUE #75336: Concurrent Snapshots Finalizing out of Order May Corrupt a Repository
The following test fails 100% of the time:

```java
    public void testOutOfOrderFinalization() throws Exception {
        internalCluster().startMasterOnlyNode();
        final List<String> dataNodes = internalCluster().startDataOnlyNodes(2);
        final String index1 = "index-1";
        final String index2 = "index-2";
        createIndexWithContent(index1, dataNodes.get(0), dataNodes.get(1));
        createIndexWithContent(index2, dataNodes.get(1), dataNodes.get(0));

        final String repository = "test-repo";
        createRepository(repository, "mock");

        blockNodeWithIndex(repository, index2);

        final ActionFuture<CreateSnapshotResponse> snapshot1 = clusterAdmin()
                .prepareCreateSnapshot(repository, "snapshot-1")
                .setIndices(index1, index2)
                .setWaitForCompletion(true)
                .execute();
        awaitNumberOfSnapshotsInProgress(1);
        final ActionFuture<CreateSnapshotResponse> snapshot2 = clusterAdmin()
                .prepareCreateSnapshot(repository, "snapshot-2")
                .setIndices(index1)
                .setWaitForCompletion(true)
                .execute();
        assertSuccessful(snapshot2);
        unblockAllDataNodes(repository);
        final SnapshotInfo sn1 = assertSuccessful(snapshot1);
        assertAcked(startDeleteSnapshot(repository, sn1.snapshot().getSnapshotId().getName()).get());

        assertThat(
                clusterAdmin().prepareSnapshotStatus().setSnapshots("snapshot-2").setRepository(repository).get().getSnapshots(),
                hasSize(1)
        );
    }
```

=> If a shard snapshot in an earlier is successful but a later snapshot containing that shard finalizes before the earlier snapshot finalizes the shard level metadata gets corrupted in a very subtle way where the shard points at an incorrect generation but all the `snap-` blobs in the shard are still correct until the next delete (thus `_status` api calls will still work) but data blobs still may be deleted incorrectly for the shard.

=>  on it fixing this.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Fix up shard generations in `SnapshotsInProgress` during snapshot finalization (don't do it earlier because it's a really heavy computation and we have a ton of places where it would have to run).
* Adjust finalization queue to be able to work with changing snapshot entries after they've been enqueued for finalisation
* Still one remaining bug left after this (see TODO about leaking generations) that I don't feel confident in fixing for `7.13.4` due to the complexity of a fix and how minor the blob leak is (+ it's cleaned up just fine during snapshot deletes)

NOTE: this could probably be dried up a lot against other shard state machine logic but I did want to isolate this change as much as I could for easy backporting as well as to minimise risk as it's not a trivial change at all. By only running the generation fixing after finalizing and with the newly added tests I feel confident in this fix though. 

Closes #75336

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -1711,13 +1713,180 @@ public void clusterStateProcessed(String source, ClusterState oldState, ClusterS
...
+     * given state. This method will update the shard generations of snapshots that the given snapshot depended on so that finalizing them
+     * will not cause rolling back to an outdated shard generation.
      *
      * @param state    current cluster state
      * @param snapshot snapshot for which to remove the snapshot operation
      * @return updated cluster state
      */
-    private static ClusterState stateWithoutSnapshot(ClusterState state, Snapshot snapshot) {
+    private static ClusterState stateWithoutSuccessfulSnapshot(ClusterState state, Snapshot snapshot) {
+        // TODO: updating snapshots here leaks their outdated generation files, we should add logic to clean those up and enhance
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1725]: The logic in this method would definitely benefit from a state tracking object like we have for the shard status update executor. In the interest of time and keeping it simple I went with this solution for now. Ideally, I'd like to resolve this todo and make the whole logic simpler to follow in 7.15 by finally refactoring `SnapshotsInProgress` into a form that is more appropriate for the logic around concurrent snapshots than to add yet another round of elaborate logic to nicely work around its shortcomings.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-1 (unrelated + known)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2 (unrelated + known)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2 (unrelated + known)

File: server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java [hunk 2]
```diff
@@ -102,7 +103,9 @@ private static boolean assertGenerationConsistency(
         @Nullable String activeGeneration
     ) {
         final String bestGeneration = generations.getOrDefault(indexName, Collections.emptyMap()).get(shardId);
-        assert bestGeneration == null || activeGeneration == null || activeGeneration.equals(bestGeneration);
+        if ((bestGeneration == null || activeGeneration == null || activeGeneration.equals(bestGeneration)) == false) {
+            throw new AssertionFailedException("gnarf");
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java:107]: Changing this assertion failure into a runtime exception is, I think, cheating ;)

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java [hunk 3]
```diff
@@ -1446,6 +1447,168 @@ public void testConcurrentRestoreDeleteAndClone() throws Exception {
...
+        logger.info("--> deleting snapshots [{},{}] from repo [{}]", sn1, sourceSnapshot, repository);
+        assertAcked(clusterAdmin().prepareDeleteSnapshot(repository).setSnapshots(sn1, sourceSnapshot).get());
+
+        assertThat(
+            clusterAdmin().prepareSnapshotStatus().setSnapshots(targetSnapshot).setRepository(repository).get().getSnapshots(),
+            hasSize(1)
+        );
+    }
+
+    public void testOutOfOrderCloneFinalization() throws Exception {
```
Comment (fcofdez) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:1570]: I think the clone - clone case is missing?

File: server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/InFlightShardSnapshotStates.java]: sorry needed a breakpoint there :D

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java:1570]: Yea sorta, that's incredibly hard to reproduce because it all runs on the same master node (can't selectively block one just one shard easily with the current infra) and I couldn't find a quick way of adding the infrastructure for that test. I can try to find time for it later today but not guarantees.

**Review by fcofdez — APPROVED** [review]
LGTM, but I agree that we should simplify this logic in the near future, it's becoming quite complex to follow. 👍

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 4]
```diff
@@ -1711,13 +1713,180 @@ public void clusterStateProcessed(String source, ClusterState oldState, ClusterS
...
+            final SnapshotsInProgress.Entry removedEntry = entryList.get(indexOfEntry);
+            for (int i = 0; i < indexOfEntry; i++) {
+                final SnapshotsInProgress.Entry previousEntry = entryList.get(i);
+                if (previousEntry.repository().equals(removedEntry.repository())) {
+                    if (removedEntry.isClone()) {
+                        if (previousEntry.isClone()) {
+                            ImmutableOpenMap.Builder<RepositoryShardId, ShardSnapshotStatus> updatedShardAssignments = null;
+                            for (ObjectObjectCursor<RepositoryShardId, ShardSnapshotStatus> finishedShardEntry : removedEntry.clones()) {
+                                final ShardSnapshotStatus shardState = finishedShardEntry.value;
+                                if (shardState.state() == ShardState.SUCCESS) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1749]: tiny nit: we're inconsistent about this vs ```if (shardState.state() != ShardState.SUCCESS) { continue; }``` across the 4 branches

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 5]
```diff
@@ -1711,13 +1713,180 @@ public void clusterStateProcessed(String source, ClusterState oldState, ClusterS
...
+                            ImmutableOpenMap.Builder<ShardId, ShardSnapshotStatus> updatedShardAssignments = null;
+                            for (ObjectObjectCursor<RepositoryShardId, ShardSnapshotStatus> finishedShardEntry : removedEntry.clones()) {
+                                final ShardSnapshotStatus shardState = finishedShardEntry.value;
+                                if (shardState.state() != ShardState.SUCCESS) {
+                                    continue;
+                                }
+                                final RepositoryShardId repoShardId = finishedShardEntry.key;
+                                final IndexMetadata indexMeta = state.metadata().index(repoShardId.indexName());
+                                if (indexMeta == null) {
+                                    // The index name that finished cloning does not exist in the cluster state so it isn't relevant
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1769]: I'm confused by this. If we deleted this index and then created another one with the same name then we'd be updating the entry with the wrong index UUID. I'm not sure this matters, but it certainly seems like it puts the entry in a strange state. Can we not use the shard ID from the actual entry?

**Review by DaveCTurner — COMMENTED** [review]
I left one question and one tiny nit, LGTM otherwise.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1749]: Ah I did this on purpose to not indent so deeply when there's more complicated logic in a branch ... maybe just confusing though I can change it if you want :)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 5 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1769]: Actually in this case `org.elasticsearch.snapshots.SnapshotsService#maybeAddUpdatedAssignment` will just not find the shard entry in the snapshot's map that still contains the old uuid because the `ShardId` won't be equal so that should be fine I think.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1769]: ugh ok even weirder :) Looking forward to this all getting cleaned up soon...

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David + Francisco!
