### PR TITLE
Fix internal cluster and single node security tests

### LINKED ISSUE #120983: [CI] JwtRealmSingleNodeTests testActivateProfileForJWT failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6052 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/x6a6vqlj5m444)
- [elasticsearch-periodic-platform-support #6052 / ubuntu-2004-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/x6lseagbyibwi)
- [elasticsearch-pull-request #53580 / part-4-fips](https://gradle-enterprise.elastic.co/s/svb3mh76ku2rs)
- [elasticsearch-intake #16581 / part4](https://gradle-enterprise.elastic.co/s/rw7prf77ku2mo)
- [elasticsearch-pull-request #53265 / part-4](https://gradle-enterprise.elastic.co/s/x74bhp47h4s7a)
- [elasticsearch-pull-request #53027 / part-4](https://gradle-enterprise.elastic.co/s/dmd4kf7nsjjgs)
- [elasticsearch-intake #16510 / part4](https://gradle-enterprise.elastic.co/s/ayexjnxgilcfs)
- [elasticsearch-pull-request #53183 / part-4](https://gradle-enterprise.elastic.co/s/yo6hodkt6k3ec)
- [elasticsearch-periodic-platform-support #6037 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/zyik6f4t6x4bs)
- [elasticsearch-periodic-platform-support #6037 / ubuntu-2004-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/dbccbmxjpmpmi)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.authc.jwt.JwtRealmSingleNodeTests.testActivateProfileForJWT" -Dtests.seed=E054AB40CDA8E671 -Dtests.locale=fr-CI -Dtests.timezone=EET -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.jwt.JwtRealmSingleNodeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testActivateProfileForJWT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchSecurityException: error attempting to authenticate request
```

**Issue Reasons:**
- [main] 11 failures in test testActivateProfileForJWT (3.2% fail rate in 341 executions)
- [main] 2 failures in step ubuntu-2004-aarch64_checkpart4_platform-support-arm (50.0% fail rate in 4 executions)
- [main] 2 failures in step part4 (3.3% fail rate in 61 executions)
- [main] 3 failures in step part-4 (1.9% fail rate in 159 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-intake (3.3% fail rate in 61 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 152 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120985: [CI] JwtRealmSingleNodeTests testClientSecretRotation failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6037 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/3bspxrb7ad4ww)
- [elasticsearch-periodic-platform-support #6032 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/5esij6jrswf4e)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.authc.jwt.JwtRealmSingleNodeTests.testClientSecretRotation" -Dtests.seed=FE624AFFEB9DF2E4 -Dtests.locale=pt-MO -Dtests.timezone=America/Pangnirtung -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.jwt.JwtRealmSingleNodeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testClientSecretRotation),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:9200], URI [/_security/_authenticate], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"unavailable_shards_exception","reason":"at least one search shard for the index [.security-7] is unavailable"}],"type":"security_exception","reason":"error attempting to authenticate request","additional_unsuccessful_credentials":"oauth2 token: invalid token","caused_by":{"type":"unavailable_shards_exception","reason":"at least one search shard for the index [.security-7] is unavailable"},"header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\", charset=\"UTF-8\""]}},"status":401}
```

**Issue Reasons:**
- [main] 2 failures in test testClientSecretRotation (0.8% fail rate in 248 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120987: [CI] ProfileIntegTests testProfileIndexAutoCreation failing
**Build Scans:**
- [elasticsearch-intake #16712 / part4](https://gradle-enterprise.elastic.co/s/vim5gf4jc32ya)
- [elasticsearch-periodic #6058 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/4e7ptzuel7iuc)
- [elasticsearch-periodic-platform-support #6037 / ubuntu-2004-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/dbccbmxjpmpmi)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.profile.ProfileIntegTests.testProfileIndexAutoCreation" -Dtests.seed=65C6204C11F6A30A -Dtests.locale=he -Dtests.timezone=Pacific/Bougainville -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.profile.ProfileIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testProfileIndexAutoCreation),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 3 failures in test testProfileIndexAutoCreation (0.9% fail rate in 333 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120988: [CI] ServiceAccountSingleNodeTests testAuthenticateWithServiceFileToken failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6376 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/doy42gsmwtqj2)
- [elasticsearch-periodic-platform-support #6362 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/5ggwqmms3xb3c)
- [elasticsearch-periodic-platform-support #6355 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/dcs72bq5yqrge)
- [elasticsearch-periodic-platform-support #6341 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/kyi3ik5ddogqg)
- [elasticsearch-periodic-platform-support #6306 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/f7gu6trfr6zws)
- [elasticsearch-periodic-platform-support #6292 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/3hikbvsih2e7c)
- [elasticsearch-periodic-platform-support #6278 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/t3jcvlmj3htji)
- [elasticsearch-periodic #6289 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/lixzhiizpcupg)
- [elasticsearch-periodic-platform-support #6264 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/gci6bjdxpp77g)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.authc.service.ServiceAccountSingleNodeTests.testAuthenticateWithServiceFileToken" -Dtests.seed=F4A38F5B68D8EA0B -Dtests.locale=seh -Dtests.timezone=Asia/Aqtobe -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.service.ServiceAccountSingleNodeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testAuthenticateWithServiceFileToken),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.action.UnavailableShardsException: at least one search shard for the index [.security-7] is unavailable
```

**Issue Reasons:**
- [8.18] 9 failures in test testAuthenticateWithServiceFileToken (1.4% fail rate in 638 executions)
- [8.18] 5 failures in step windows-2019_checkpart4_platform-support-windows (31.3% fail rate in 16 executions)
- [8.18] 2 failures in step ubuntu-2404-aarch64_checkpart4_platform-support-arm (12.5% fail rate in 16 executions)
- [8.18] 8 failures in pipeline elasticsearch-periodic-platform-support (47.1% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121022: [CI] ProfileIntegTests testSuggestProfilesWithName failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6264 / almalinux-8-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/p5w24iwma7t4g)
- [elasticsearch-pull-request #55051 / part-4](https://gradle-enterprise.elastic.co/s/enlqcajejaevo)
- [elasticsearch-periodic-platform-support #6131 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/fzh4ujxn2w6zo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.profile.ProfileIntegTests.testSuggestProfilesWithName" -Dtests.seed=A0522CFDB8F1E5AE -Dtests.locale=en-TV -Dtests.timezone=Africa/Bangui -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.profile.ProfileIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSuggestProfilesWithName),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [8.18] 3 failures in test testSuggestProfilesWithName (0.4% fail rate in 781 executions)
- [8.18] 2 failures in pipeline elasticsearch-periodic-platform-support (10.0% fail rate in 20 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121039: [CI] JwtRealmSingleNodeTests testGrantApiKeyForJWT failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6151 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/uqxgzagxswq6o)
- [elasticsearch-periodic-platform-support #6144 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/dhp4df2uirmbe)
- [elasticsearch-periodic-platform-support #6137 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/4qv6cqhsw3sui)
- [elasticsearch-pull-request #54525 / part-4](https://gradle-enterprise.elastic.co/s/czliguom5c63c)
- [elasticsearch-periodic-platform-support #6081 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/2ae4dlonwhpze)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.authc.jwt.JwtRealmSingleNodeTests.testGrantApiKeyForJWT" -Dtests.seed=4E6145BD2DA2CD5E -Dtests.locale=haw -Dtests.timezone=Asia/Hovd -Druntime.java=23
```

**Applicable branches:**
9.0

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.jwt.JwtRealmSingleNodeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGrantApiKeyForJWT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchSecurityException: error attempting to authenticate request
```

**Issue Reasons:**
- [9.0] 2 consecutive failures in step windows-2022_checkpart4_platform-support-windows
- [9.0] 5 failures in test testGrantApiKeyForJWT (1.6% fail rate in 310 executions)
- [9.0] 2 failures in step windows-2022_checkpart4_platform-support-windows (20.0% fail rate in 10 executions)
- [9.0] 4 failures in pipeline elasticsearch-periodic-platform-support (36.4% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121096: [CI] ProfileIntegTests testProfileAPIsWhenIndexNotCreated failing
**Build Scans:**
- [elasticsearch-intake #17949 / part4](https://gradle-enterprise.elastic.co/s/7onjbur4lftlw)
- [elasticsearch-periodic #6366 / openjdk17_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/yp7v3heob5rdg)
- [elasticsearch-periodic #6324 / release-tests](https://gradle-enterprise.elastic.co/s/yp7ividkr6qji)
- [elasticsearch-periodic-platform-support #6306 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/ov3zigfytxs7y)
- [elasticsearch-periodic-platform-support #6292 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/evoaxgkx2cono)
- [elasticsearch-periodic #6303 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/3txczwwf33y7u)
- [elasticsearch-periodic-platform-support #6271 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/7mgg4ihfusqt6)
- [elasticsearch-periodic-platform-support #6222 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/22kwdt4unnhuc)
- [elasticsearch-periodic-platform-support #6215 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/s7wuv6lnif2uc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.profile.ProfileIntegTests.testProfileAPIsWhenIndexNotCreated" -Dtests.seed=8825D05629B633A3 -Dtests.locale=sah-Cyrl-RU -Dtests.timezone=Atlantic/Stanley -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.profile.ProfileIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testProfileAPIsWhenIndexNotCreated),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [8.18] 9 failures in test testProfileAPIsWhenIndexNotCreated (1.1% fail rate in 838 executions)
- [8.18] 2 failures in step ubuntu-2404-aarch64_checkpart4_platform-support-arm (9.5% fail rate in 21 executions)
- [8.18] 5 failures in pipeline elasticsearch-periodic-platform-support (23.8% fail rate in 21 executions)
- [8.18] 3 failures in pipeline elasticsearch-periodic (14.3% fail rate in 21 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121101: [CI] ProfileIntegTests testGetProfiles failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6187 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/7db6apfclpxoi)
- [elasticsearch-pull-request #54124 / checkpart4_release-tests](https://gradle-enterprise.elastic.co/s/3uu3kurg7q52k)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.profile.ProfileIntegTests.testGetProfiles" -Dtests.seed=930C3CD63FE6E69E -Dtests.locale=bez-TZ -Dtests.timezone=Etc/GMT+1 -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.profile.ProfileIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGetProfiles),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [8.18] 2 failures in test testGetProfiles (0.3% fail rate in 602 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121108: [CI] ProfileIntegTests testUpdateProfileData failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6362 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/bofelihsb2yws)
- [elasticsearch-pull-request #56725 / part-4](https://gradle-enterprise.elastic.co/s/3fvl3a2q7rjba)
- [elasticsearch-periodic #6366 / openjdk22_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/zl5epcmjua26o)
- [elasticsearch-periodic-platform-support #6341 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/q4ghwvjd2vst6)
- [elasticsearch-periodic-platform-support #6313 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/le67xhqsqtii4)
- [elasticsearch-periodic #6296 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ba2ddqpgcl352)
- [elasticsearch-periodic-platform-support #6271 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/7mgg4ihfusqt6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.profile.ProfileIntegTests.testUpdateProfileData" -Dtests.seed=90E3F4217B9463FA -Dtests.locale=ku -Dtests.timezone=Asia/Yangon -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.profile.ProfileIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testUpdateProfileData),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [8.18] 7 failures in test testUpdateProfileData (1.3% fail rate in 523 executions)
- [8.18] 4 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 14 executions)
- [8.18] 2 failures in pipeline elasticsearch-periodic (14.3% fail rate in 14 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #121116: [CI] ProfileIntegTests testSuggestProfilesWithHint failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6128 / almalinux-8-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/adacf3aedzt3m)
- [elasticsearch-intake #17064 / part4](https://gradle-enterprise.elastic.co/s/gpvxmgjiv4l2i)
- [elasticsearch-intake #17032 / part4](https://gradle-enterprise.elastic.co/s/st56mxdhzkktu)
- [elasticsearch-intake #16957 / part4](https://gradle-enterprise.elastic.co/s/irmltuspkx7kk)
- [elasticsearch-pull-request #54333 / part-4](https://gradle-enterprise.elastic.co/s/r7ytotooj2b5g)
- [elasticsearch-pull-request #54314 / part-4](https://gradle-enterprise.elastic.co/s/ouq2vkswk7r6e)
- [elasticsearch-intake #16815 / part4](https://gradle-enterprise.elastic.co/s/av3eukd3xj6by)
- [elasticsearch-pull-request #53859 / part-4](https://gradle-enterprise.elastic.co/s/v6uwp4nxru6dm)
- [elasticsearch-intake #16745 / part4](https://gradle-enterprise.elastic.co/s/qntl6cu2uywlk)
- [elasticsearch-pull-request #53593 / part-4](https://gradle-enterprise.elastic.co/s/tkh64s4uvms4u)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.profile.ProfileIntegTests.testSuggestProfilesWithHint" -Dtests.seed=5126C1569F5376DD -Dtests.locale=hi -Dtests.timezone=America/Rainy_River -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.profile.ProfileIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSuggestProfilesWithHint),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 12 failures in test testSuggestProfilesWithHint (1.3% fail rate in 955 executions)
- [main] 5 failures in step part4 (2.9% fail rate in 172 executions)
- [main] 6 failures in step part-4 (1.5% fail rate in 393 executions)
- [main] 5 failures in pipeline elasticsearch-intake (2.9% fail rate in 172 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (1.6% fail rate in 381 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by slobodanadamovic**
This PR fixes `SecuritySingleNodeTestCase` and `ProfileIntegTests` tests.

- The security single node test failures are solved by ensuring every test starts with security index created and available. This is in order to have consistent state for every test. With the changes introduce in the [#120323](https://github.com/elastic/elasticsearch/pull/120323) PR, only the first test would execute with `.security` index being created async. Subsequent tests would execute without security index creation due to the fact that whole cluster is wiped after each test. This caused a flakiness only for the first test, because there was no mechanism in place to ensure that the `.security` index is active before test execution.
- The profile integration tests are solved by introducing an anonymous role which don't have application privileges. The application privileges are resolved from the `.security` index and assigned to all users, including the `es_test_root` user which is used during cluster wiping. Due to asynchronous nature of [cluster setup](https://github.com/elastic/elasticsearch/blob/656b54bc74ee46994e14150459aed7ac50876f30/test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java#L369-L374) and `.security` index creation, this now causes flakiness. The main problem is that wiping is done asynchronously and uses `es_test_root` which had assigned anonymous `rac_role` which depends on `.security` index being available for search in order to resolve application privileges. The application privilege resolution is done in `buildRoleFromDescriptors` [which currently does not wait for security index availability](https://github.com/elastic/elasticsearch/blob/656b54bc74ee46994e14150459aed7ac50876f30/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java#L595)(can be improved - but still wouldn't fix internal cluster tests). This wasn't a problem before just because we simply return [empty results when `.security` index does not exist](https://github.com/elastic/elasticsearch/blob/656b54bc74ee46994e14150459aed7ac50876f30/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java#L224-L225).  There is some complexity in making internal clusters wait for availability of security shards before the test, so I think this solution is acceptable given that it's not required for this tests to have anonymous role with application privileges.

Resolves https://github.com/elastic/elasticsearch/issues/121022
Resolves https://github.com/elastic/elasticsearch/issues/121096
Resolves https://github.com/elastic/elasticsearch/issues/121101
Resolves https://github.com/elastic/elasticsearch/issues/120988
Resolves https://github.com/elastic/elasticsearch/issues/121108
Resolves https://github.com/elastic/elasticsearch/issues/120983
Resolves https://github.com/elastic/elasticsearch/issues/120987
Resolves https://github.com/elastic/elasticsearch/issues/121179
Resolves https://github.com/elastic/elasticsearch/issues/121183
Resolves https://github.com/elastic/elasticsearch/issues/121346
Resolves https://github.com/elastic/elasticsearch/issues/121151
Resolves https://github.com/elastic/elasticsearch/issues/120985
Resolves https://github.com/elastic/elasticsearch/issues/121039
Resolves https://github.com/elastic/elasticsearch/issues/121483
Resolves https://github.com/elastic/elasticsearch/issues/121116
Resolves https://github.com/elastic/elasticsearch/issues/121258
Resolves https://github.com/elastic/elasticsearch/issues/121486

### CODE REVIEW

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authc/esnative/ReservedRealmElasticAutoconfigIntegTests.java [hunk 1]
```diff
@@ -70,46 +58,10 @@ protected SecureString getBootstrapPassword() {
...
-                latch.countDown();
-            }
-        });
-        if (isMigrationComplete(clusterService.state())) {
-            latch.countDown();
-        }
-        safeAwait(latch);
-    }
-
-    private void deleteSecurityIndex() {
```
Comment (slobodanadamovic) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authc/esnative/ReservedRealmElasticAutoconfigIntegTests.java:92]: Renamed this one and moved it into `SecuritySingleNodeTestCase`.

**Review by n1v0lg — APPROVED** [review]
LGTM -- tricky business! 

> The application privilege resolution is done in buildRoleFromDescriptors [which currently does not wait for security index availability](https://github.com/elastic/elasticsearch/blob/656b54bc74ee46994e14150459aed7ac50876f30/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java#L595)

Yeah we probably want to default wait here. Just need to find the time to think through all corner cases...

**Comment by slobodanadamovic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/122732)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/122733)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/122734)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
