### PR TITLE
Check for degenerated lines when calculating the centroid

### LINKED ISSUE #55851: [CI] TriangleTreeTests.testRandomMultiLineIntersections failure
Reproduce with:

```
./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.index.fielddata.TriangleTreeTests.testRandomMultiLineIntersections" \
  -Dtests.seed=7E1399ABEE4CC90 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-SA \
  -Dtests.timezone=Pacific/Johnston \
  -Dcompiler.java=14 \
  -Druntime.java=8

```

Error:

```
java.lang.IllegalArgumentException: invalid longitude NaN; must be between -180.0 and 180.0
	at __randomizedtesting.SeedInfo.seed([7E1399ABEE4CC90:509A24FA3F5BDABE]:0)
	at org.apache.lucene.geo.GeoUtils.checkLongitude(GeoUtils.java:73)
	at org.apache.lucene.geo.GeoEncodingUtils.encodeLongitude(GeoEncodingUtils.java:91)
	at org.elasticsearch.xpack.spatial.index.fielddata.GeoShapeCoordinateEncoder.encodeX(GeoShapeCoordinateEncoder.java:22)
	at org.elasticsearch.xpack.spatial.index.fielddata.TriangleTreeWriter.writeTo(TriangleTreeWriter.java:38)
	at org.elasticsearch.xpack.spatial.index.fielddata.TriangleTreeTests.triangleTreeReader(TriangleTreeTests.java:431)
	at org.elasticsearch.xpack.spatial.index.fielddata.TriangleTreeTests.testRandomMultiLineIntersections(TriangleTreeTests.java:266)
```

https://gradle-enterprise.elastic.co/s/dchseua5cx2ym

### PR DESCRIPTION
**Pull request by iverase**
Check that the weight of a line centroid is bigger than 0. In case it is 0, the centroid is calculated as if the line is a point.

fixes #55851

### CODE REVIEW

**Comment by talevy** [comment]
oh woah, I did not see this open test issue!

Do you think it would be best to update the `CentroidCalculatorTests#testLineAsClosedPoint` to be more generic to when the approximate weight is effectively zero?

I mistakenly thought the only time the weight would be zero was if this were a closed point, but apparently not!

**Comment by iverase** [comment]
> Do you think it would be best to update the CentroidCalculatorTests#testLineAsClosedPoint to be more generic to when the approximate weight is effectively zero?

I don't think so, it will be hard to make sure that you are creating degenerated lines and this actually shows up in other tests.

I am updating the logic a bit, let me know what do you think. I am going to work a bit more as I think this might still happen with degreased Rectangles and I would want to fix it in this PR.

**Comment by iverase** [comment]
@talevy I think this is ready for review.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculatorTests.java [hunk 1]
```diff
@@ -250,7 +258,7 @@ public void testPolygonAsPoint() {
         CentroidCalculator calculator = new CentroidCalculator(polygon);
         assertThat(calculator.getX(), equalTo(GeoUtils.normalizeLon(point.getX())));
         assertThat(calculator.getY(), equalTo(GeoUtils.normalizeLat(point.getY())));
-        assertThat(calculator.sumWeight(), equalTo(1.0));
+        assertThat(calculator.sumWeight(), equalTo(3.0));
```
Comment (talevy) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculatorTests.java:261]: a point should have a weight of 1?

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java [hunk 2]
```diff
@@ -224,18 +224,18 @@ public Void visit(Polygon polygon) {
...
-            } else if (diffY != 0) {
-                calculator.addCoordinate(rectangle.getMinX(), sumY / 2, diffY, DimensionalShapeType.LINE);
+            double rectWeight = Math.abs(diffX * diffY);
+            if (rectWeight != 0) {
+                double sumX = rectangle.getMaxX() + rectangle.getMinX();
+                double sumY = rectangle.getMaxY() + rectangle.getMinY();
+                calculator.addCoordinate(sumX / 2, sumY / 2, rectWeight, DimensionalShapeType.POLYGON);
             } else {
-                visitPoint(rectangle.getMinX(), rectangle.getMinY());
+                // degenerated rectangle, transform to Line
```
Comment (talevy) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java:235]: good find!

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java [hunk 3]
```diff
@@ -246,22 +246,20 @@ private void visitPoint(double x, double y) {
...
+            // line segment weighted by the line segment's length in degrees
+            for (int i = 0; i < length - 1; i++) {
+                double diffX = x.get(i) - x.get(i + 1);
+                double diffY = y.get(i) - y.get(i + 1);
+                double xAvg = (x.get(i) + x.get(i + 1)) / 2;
+                double yAvg = (y.get(i) + y.get(i + 1)) / 2;
+                double weight = Math.sqrt(diffX * diffX + diffY * diffY);
+                if (weight == 0) {
+                    // degenerated line, it can be considered a point
+                    visitPoint(x.get(i), y.get(i));
```
Comment (talevy) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java:259]: Do we believe this is right?

If a line segment has repeating sections where the weight is effectively zero, then we could potentially be counting multiple points per `Line`?

**Review by talevy — COMMENTED** [review]
Overall looks good, but I have some questions

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculatorTests.java (hunk 1 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculatorTests.java:261]: This is a bit of a fake test as we are trying to compute the centroid of a polygon which all points are the same. This is an invalid polygon and we should never get here. I think it is ok to consider in this case that the centroid is the sum of the centroid of each point. It has no practical consequences.

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java (hunk 3 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java:259]: I think it is ok. If there is one segment with length, the centroid of the points will be discarded. If all points are equivalent, then it will be weight by the number of points. I think it is the right thing to do.

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculatorTests.java (hunk 1 above)
Comment (talevy) [reply x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculatorTests.java:261]: OK

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java (hunk 3 above)
Comment (talevy) [reply x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java:259]: OK. just wanted to be sure! thanks

**Review by talevy — APPROVED** [review]
