### PR TITLE
Cross Cluster Search: make remote clusters optional

### LINKED ISSUE #26118: cross cluster search - entire response failure although only one cluster down
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.5.1, Build: 19c13d0/2017-07-18T20:44:24.823Z, JVM: 1.8.0_131

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux zbook-15-G3 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
There are 3 elastic clusters and cluster_1 is configured to be able to search across clusters: cluster_2 and cluster_3.
When cluster_3 is down (cluster_1, cluster_2 are up) wildcard cluster search returns failure:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "connect_transport_exception",
        "reason" : "[][127.0.0.1:9303] connect_timeout[30s]"
      }
    ],
    "type" : "transport_exception",
    "reason" : "unable to communicate with remote cluster [cluster_3]",
    "caused_by" : {
      "type" : "connect_transport_exception",
      "reason" : "[][127.0.0.1:9303] connect_timeout[30s]",
      "caused_by" : {
        "type" : "annotated_connect_exception",
        "reason" : "Connection refused: /127.0.0.1:9303",
        "caused_by" : {
          "type" : "connect_exception",
          "reason" : "Connection refused"
        }
      }
    }
  },
  "status" : 500
}
```

I would expect that result of all up clusters is returned.

**Steps to reproduce**:

 1. Add data to cluster_2
```
curl -XPUT 'localhost:9202/test-2/data/1?pretty' -H 'Content-Type: application/json' -d'
{
    "user" : "user2",
    "message" : "test2"
}
'
```
 2. Add data to cluster_3
```
curl -XPUT 'localhost:9203/test-3/data/1?pretty' -H 'Content-Type: application/json' -d'
{
    "user" : "user3",
    "message" : "test3"
}
'
```
 3. Set cross cluster search on cluster_1
```
curl -XPUT 'localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "search": {
      "remote": {
        "cluster_2": {
          "seeds": [
            "127.0.0.1:9302"
          ]
        },
        "cluster_3": {
          "seeds": [
            "127.0.0.1:9303"
          ]
        }
      }
    }
  }
}
'
```
4. Down cluster_3
5. Get all test-* indexes from cluster_2 and cluster_3
```
curl -XPOST 'localhost:9200/*:test-*/data/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "match_all": {}
  }
}
'
```
Please also see console output from the test case:
[test.console.txt](https://github.com/elastic/elasticsearch/files/1211490/test.console.txt)

### PR DESCRIPTION
**Pull request by javanna**
Today Cross Cluster Search requires at least one node in each remote cluster to be up once the cross cluster search is run. Otherwise the whole search request fails despite some of the data (either local and/or remote) is available. This happens when performing the `_search/shards` calls to find out which remote shards the query has to be executed on. This scenario is different from shard failures that may happen later on when the query is actually executed, in case e.g. remote shards are missing, which is not going to fail the whole request but rather yields partial results, and the _shards section in the response will indicate that.

This commit introduces a boolean setting per cluster called `search.remote.$cluster_alias.skip_if_disconnected`, set to `false` by default, which allows to skip certain clusters if they are down when trying to reach them through a cross cluster search requests. By default all clusters are mandatory.

Scroll requests support such setting too when they are first initiated (first search request with scroll parameter), but subsequent scroll rounds (_search/scroll endpoint) will fail if some of the remote clusters went down meanwhile.

The search API response contains now a new `_clusters` section, similar to the `_shards` section, that gets returned whenever one or more clusters were disconnected and got skipped:

```
"_clusters" : {
    "total" : 3,
    "successful" : 2,
    "skipped" : 1
}
```

Such section won't be part of the response if no clusters have been skipped.

The per cluster `skip_unavailable` setting value has also been added to the output of the `remote/info` API.

~~This PR is marked "work in progress", here is what's left to do:~~

- ~~there are halfway scenarios that need to be considered when it comes to reconnecting to remote clusters that were down: the cluster could be responding but it's recovering the index, in which case it may return `IndexNotFoundException` (depending on the indices options provided with the original CCS) which may be surprising. The current approach ignores any failures from the remote cluster that have `skip_unavailable` marked to `true`. Maybe the setting should rather be called `ignore_failures` though, as it is not just about not failing when a remote cluster is disconnected but rather ignoring any failure coming from the remote cluster.~~
- ~~yaml tests should probably be converted to java tests, the complication is to properly simulate disconnected nodes (though we have unit tests for all that)~~ 
- ~~is it enough to return the number of skipped clusters, or should we go the extra mile and return which clusters were skipped?~~
- ~~settings validation: you can submit `skip_unavailable` for a remote cluster that is not registered (with no seeds) #27161 should help with this~~
- ~~would be nice to clean up the `skip_unavailable` setting once its corresponding remote is removed (as its seeds are set to null), otherwise it stays part of settings although it has no effect.~~

Closes #26118

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 1]
```diff
@@ -296,6 +312,28 @@ public static SearchResponse fromXContent(XContentParser parser) throws IOExcept
...
+                            currentFieldName = parser.currentName();
+                        } else if (token.isValue()) {
+                            if (Clusters.SUCCESSFUL_FIELD.match(currentFieldName)) {
+                                successful = parser.intValue();
+                            } else if (Clusters.TOTAL_FIELD.match(currentFieldName)) {
+                                total = parser.intValue();
+                            } else if (Clusters.SKIPPED_FIELD.match(currentFieldName)) {
+                                skipped = parser.intValue();
+                            } else {
+                                parser.skipChildren();
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: should we be more strict and just fail if this happens?

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 2]
```diff
@@ -296,6 +312,28 @@ public static SearchResponse fromXContent(XContentParser parser) throws IOExcept
...
+                            }
+                        } else {
+                            parser.skipChildren();
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: see above

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 3]
```diff
@@ -322,6 +360,9 @@ public void readFrom(StreamInput in) throws IOException {
                 shardFailures[i] = readShardSearchFailure(in);
             }
         }
+        if (!in.getVersion().before(Version.V_6_1_0)) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: please `onOrAfter` instead and I think it should be 7.0.0 for now?

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 4]
```diff
@@ -340,7 +381,9 @@ public void writeTo(StreamOutput out) throws IOException {
         for (ShardSearchFailure shardSearchFailure : shardFailures) {
             shardSearchFailure.writeTo(out);
         }
-
+        if (!out.getVersion().before(Version.V_6_1_0)) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: same comment as above

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 5]
```diff
@@ -353,4 +396,78 @@ public String toString() {
...
+        static final ParseField SUCCESSFUL_FIELD = new ParseField("successful");
+        static final ParseField SKIPPED_FIELD = new ParseField("skipped");
+        static final ParseField TOTAL_FIELD = new ParseField("total");
+
+        private final int total;
+        private final int successful;
+        private final int skipped;
+
+        Clusters(int total, int successful, int skipped) {
+            this.total = total;
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: can you also check that they are never negative

File: core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java [hunk 6]
```diff
@@ -129,6 +133,13 @@ synchronized void updateSeedNodes(List<DiscoveryNode> seedNodes, ActionListener<
         connectHandler.connect(connectListener);
     }
 
+    /**
+     * Updates the skipIfDisconnected flag that can be dynamically set for each remote cluster
+     */
+    synchronized void updateSkipIfDisconnected(boolean skipIfDisconnected) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java]: it's volatile no need for synchronized then

File: core/src/main/java/org/elasticsearch/transport/RemoteConnectionInfo.java [hunk 7]
```diff
@@ -62,6 +64,11 @@ public RemoteConnectionInfo(StreamInput input) throws IOException {
         initialConnectionTimeout = new TimeValue(input);
         numNodesConnected = input.readVInt();
         clusterAlias = input.readString();
+        if (input.getVersion().before(Version.V_6_1_0)) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/transport/RemoteConnectionInfo.java]: please use onOrAfter it has better semantics IMO

**Comment by s1monw** [comment]
> is it enough to return the number of skipped clusters, or should we go the extra mile and return which clusters were skipped?

 I am not sure since we also don't do this if we skip shards? I wonder what would be the usecase. I think we can go and return warning headers for disconnected clusters that are skipped?

> settings validation: you can submit skip_if_disconnected for a remote cluster that is not registered (with no seeds) #27161 should help with this

this should be taken care of soon.

> would be nice to clean up the skip_if_disconnected setting once its corresponding remote is removed (as its seeds are set to null), otherwise it stays part of settings although it has no effect.

the change in #27161 should make sure it's never left behind.

> there are halfway scenarios that need to be considered when it comes to reconnecting to remote clusters that were down: the cluster could be responding but it's recovering the index, in which case it may return IndexNotFoundException (depending on the indices options provided with the original CCS) which may be surprising. The current approach ignores any failures from the remote cluster that have skip_if_disconnected marked to true. Maybe the setting should rather be called ignore_failures though, as it is not just about not failing when a remote cluster is disconnected but rather ignoring any failure coming from the remote cluster.

First I think the reason for disconnection isn't important in this scenario. We want to read what is possible to read. Down the road we might replace the extra roundtrip with a partial reduction on the remote cluster so we really only care if we can get the info or not. Yet, I am ok with stuff like `skip_not_available` or so.

**Review by s1monw — COMMENTED** [review]
Looks good IMO. I will do another round once you remove the WIP

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java (hunk 1 above)
Comment (javanna) [reply core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: this parsing method is used in the high-level REST client, we are lenient there to guarantee forward compatibility, meaning that if one day we add a new field under _clusters, we don't break while parsing that but we rather ignore it and everything is fine. This is tested in SearchResponseTests#testFromXContentWithRandomFields

Comment (s1monw) [reply core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: got it

File: qa/ccs-unavailable-clusters/build.gradle [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+apply plugin: 'elasticsearch.standalone-rest-test'
+apply plugin: 'elasticsearch.rest-test'
+apply plugin: 'elasticsearch.test-with-dependencies'
+
+dependencies {
```
Comment (javanna) [inline qa/ccs-unavailable-clusters/build.gradle]: I wanted to added this new test to the existing multi-cluster-search qa module, but that one has two clusters and runs yaml tests against both of them. Whenever you add a new IT test to that module it gets run multiple times (one against the remote cluster, one against the ccs cluster). Also this new module uses the rest high level client too. Maybe we should look into merging the two though as a follow-up, I don't like having too many qa modules and they slow down the build.

**Comment by javanna** [comment]
@s1monw I removed the WIP label, this is ready for another round of review

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 9]
```diff
@@ -71,15 +74,18 @@
 
     private ShardSearchFailure[] shardFailures;
 
+    private Clusters clusters;
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: can be final?

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java [hunk 10]
```diff
@@ -71,15 +74,18 @@
...
+
     private long tookInMillis;
 
     public SearchResponse() {
     }
 
     public SearchResponse(SearchResponseSections internalResponse, String scrollId, int totalShards, int successfulShards,
-                          int skippedShards, long tookInMillis, ShardSearchFailure[] shardFailures) {
+                          int skippedShards, long tookInMillis, ShardSearchFailure[] shardFailures, @Nullable Clusters clusters) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: instead of allowing null should we make it required and just don't render it if `total == successful` ? I don't like null invariants

File: core/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java [hunk 11]
```diff
@@ -215,6 +217,20 @@ protected void doExecute(Task task, SearchRequest searchRequest, ActionListener<
         }
     }
 
+    static SearchResponse.Clusters buildClusters(OriginalIndices localIndices, Map<String, OriginalIndices> remoteIndices,
+                                                 Map<String, ClusterSearchShardsResponse> searchShardsResponses) {
+        int localClusters = localIndices.indices().length == 0 ? 0 : 1;
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java]: `Math.min(localIndices.indices().length, 1);` maybe?

File: docs/reference/modules/cross-cluster-search.asciidoc [hunk 12]
```diff
@@ -179,6 +179,82 @@ will be prefixed with their remote cluster name:
...
+the search request is executed, otherwise the whole request fails and no search results are returned
+despite some of the clusters are available. Remote clusters can be made optional through the
+boolean `skip_unavailable` setting, set to `false` by default.
+
+[source,js]
+--------------------------------
+PUT _cluster/settings
+{
+  "persistent": {
+    "search": {
```
Comment (s1monw) [inline docs/reference/modules/cross-cluster-search.asciidoc]: would it be easier to say `search.remote.cluster_one.skip_unavailable: true`?

File: qa/ccs-unavailable-clusters/build.gradle (hunk 8 above)
Comment (s1monw) [reply qa/ccs-unavailable-clusters/build.gradle]: do we have to have a java test for this or can we just use `multi-cluster-search` for it. I mean we can add a 3rd stage where we shutdown one cluster and then run our tests? To me it seems like we can pull it all in yaml land? I can help if you want with that. I am also ok to make it a followup.

**Review by s1monw — APPROVED** [review]
LGTM I left some suggestions

File: core/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java (hunk 11 above)
Comment (javanna) [reply core/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java]: oh boy yes

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java (hunk 10 above)
Comment (javanna) [reply core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: that's what I had before, but I think in this specific case null makes sense. Rendering only when total != successful becomes confusing as the same response is also used for scroll responses where rendering this section has no value. Also, you don't see the section unless something went wrong. I think it would be better to print the section out for all CCS requests, and never when going only local. null allows to distinguish between responses that involved CCS and responses that come from local nodes only. Would you prefer to have a placeholder instead of null, called let's say `EMPTY`, which indicates that the section has no meaningful value and should not be printed out?

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java (hunk 9 above)
Comment (javanna) [reply core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: I'm afraid not, SearchResponse implements Streamable and not Writeable as it is an ActionResponse.

File: docs/reference/modules/cross-cluster-search.asciidoc (hunk 12 above)
Comment (javanna) [reply docs/reference/modules/cross-cluster-search.asciidoc]: yep

File: qa/ccs-unavailable-clusters/build.gradle (hunk 8 above)
Comment (javanna) [reply qa/ccs-unavailable-clusters/build.gradle]: I am not sure about this. I personally prefer this java part that shuts down a transport as part of the test over gradle magic that shuts clusters down. I spent some time trying to adapt multi-cluster-search but it was complicated in different ways. And this test also has the advantage of using the high-level client when CCS is used, which we don't test otherwise. Can we eventually address this later?

**Comment by s1monw** [comment]
@javanna what's the status on this?

**Comment by javanna** [comment]
@s1monw I replied to your comments. Also making the docs snippets work, I had some issues there.

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java (hunk 10 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: placeholder would be fine IMO

File: core/src/main/java/org/elasticsearch/action/search/SearchResponse.java (hunk 9 above)
Comment (s1monw) [reply core/src/main/java/org/elasticsearch/action/search/SearchResponse.java]: fair enough

**Comment by s1monw** [comment]
@javanna wanna push this?

**Comment by luxiaoxun** [comment]
@javanna 
How you guys decide one remote cluster is unavailable? 
Do we have some settings like "connection timeout" or "heartbeat detecting" to decide one remote cluster is unavailable ?
Why I am asking this because when I enable the firewall between 2 clusters, the search response is 'java.io.IOException: listener timeout after waiting for [30000] ms' then after almost 15 minutes, one cluster can find out the other one can not be connected. Then the search will skip the "unavailable one".

**Comment by javanna** [comment]
hi @luxiaoxun we currently catch any exception coming back from the remote cluster (could be any type of timeout, or just an error returned), which we recently realized is too broad. We are working on a change to reflect that "unavailable" means we can't connect to a remote cluster, so that skip_unavailable will not make us ignore any error returned from the remote clusters.

I am curious though about the timeout exception you are getting, would you be able to share a stacktrace and expand a bit on the behaviour you are seeing so we can evaluate improvements? It would be better to post it to our [discuss forum](https://discuss.elastic.co/), and ping me there. Thanks!
