### PR TITLE
ESQL: Refactor Greatest and Least functions to use evaluator map (#114036)

### LINKED ISSUE #114036: [ESQL] Greatest and Least can fail with Illegal Data Type on types that resolved correctly
Related to https://github.com/elastic/elasticsearch/pull/113961

`resolveType` for Greatest and Least only checks that all the input data types are the same (or null).  The `toEvaluator` function, however, has an explicit list of types it maps to evaluators, and if a type does not match we throw from there.  Personally, I recommend a strategy like we used in the binary comparisons, where we have a map from data types to evaluators, and resolve types by checking if they are keys in the map.  There are probably other solutions as well.  The goal is that `resolveType` should be consistent with `toEvaluator` with regard to type support.

### PR DESCRIPTION
**Pull request by shinsj4653**
# ESQL: Refactor Greatest and Least functions to use switch statements

## Description
This PR refactors the `Greatest` and `Least` functions to use Java switch expressions instead of Map-based evaluator lookup for better performance and code clarity. The changes include:

1. Replaced `EVALUATOR_MAP` with switch expressions in `toEvaluator` method
2. Added `isSupportedDataType` helper method using switch expression
3. Improved error messages with proper type validation
4. Added comprehensive type validation tests in `VerifierTests`

## Changes
- `Greatest.java`:
  - Replaced Map-based evaluator lookup with switch expression
  - Added `isSupportedDataType` method for type validation
  - Updated `toEvaluator` to use switch-based factory creation
  - Improved error handling and type checking

- `Least.java`:
  - Replaced Map-based evaluator lookup with switch expression  
  - Added `isSupportedDataType` method for type validation
  - Updated `toEvaluator` to use switch-based factory creation
  - Improved error handling and type checking

- `VerifierTests.java`:
  - Added `testGreatestLeastWithUnsupportedDataTypes()` test method
  - Tests unsupported data types (geo_point, cartesian_point)
  - Tests mixed type scenarios with proper error message validation
  - Ensures type consistency between `resolveType` and `toEvaluator`

## Testing

- `GreatestTests.java`, `LeastTests.java`
```bash
./gradlew :x-pack:plugin:esql:test --tests "*GreatestTests*" --tests "*LeastTests*" -x :libs:simdvec:compileMain21Java -x :libs:simdvec:compileMain22Java --console=plain
```
image  

- `VerifierTests.testGreatestLeastWithUnsupportedDataTypes`
```bash
./gradlew :x-pack:plugin:esql:test --tests "VerifierTests.testGreatestLeastWithUnsupportedDataTypes" -x :libs:simdvec:compileMain21Java -x :libs:simdvec:compileMain22Java --console=plain --info
```
image

### ✅ Greatest/Least Function Tests
- **GreatestTests**: All tests PASSED
- **LeastTests**: All tests PASSED
- Covers all supported data types and edge cases
- No regressions introduced

### ✅ VerifierTests - Type Validation
- **testGreatestLeastWithUnsupportedDataTypes**: PASSED
- Tests unsupported data types (geo_point, cartesian_point)
- Validates proper error messages for type mismatches
- Ensures consistency between `resolveType` and `toEvaluator`

### 🔍 Error Scenario Validation
The new type validation correctly rejects unsupported data types:
- `geo_point` → "Cannot use [geo_point] with function [Greatest]"
- `cartesian_point` → "Cannot use [cartesian_point] with function [Least]"
- Mixed types → Proper type mismatch error messages

**Note**: The error messages are validated by the test framework and don't appear in logs when tests pass, which is the expected behavior.

## Related Issues
Closes #114036

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Backport
- [ ] Backport to 8.19
- [ ] Backport to 8.18
- [ ] Backport to 8.17

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java [hunk 1]
```diff
@@ -138,27 +159,24 @@ public boolean foldable() {
...
             return new LeastBytesRefEvaluator.Factory(source(), factories);
         }
-        throw EsqlIllegalArgumentException.illegalDataType(dataType);
+
+        var evaluatorFactory = EVALUATOR_MAP.get(dataType);
+        if (evaluatorFactory == null) {
+            throw EsqlIllegalArgumentException.illegalDataType(dataType);
+        }
+
+        return evaluatorFactory.apply(factories);
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java]: I wonder if this is one of the things worth doing with java`s switch? Each data type is enum and compile time constant

**Review by alex-spies — DISMISSED** [review]
Hi @shinsj4653 and thank you very much for your contribution!

I'm sorry it took us so long to get back to you.

Unfortunately, this PR does not contain tests that demonstrate that the earlier type check actually happens and returns the expected error message. We often add cases to the `VerifierTests` in such situations.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java (hunk 1 above)
Comment (shinsj4653) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java]: Thanks for the feedback! This is really helpful. I'll work on refactoring the code based on your suggestions :)

**Comment by shinsj4653** [comment]
Hi @alex-spies, I appreciate your feedback. I'll add a test case for this issue using VerifierTests

**Comment by shinsj4653** [comment]
Hi @alex-spies @idegtiarenko,

Thank you for the valuable feedback! I've implemented the suggested changes:

✅ **idegtiarenko's feedback**: Refactored to use switch expressions instead of Map-based evaluator lookup
✅ **alex-spies's feedback**: Added comprehensive type validation tests in VerifierTests

The changes ensure:
- Better performance with switch expressions
- Proper type validation for unsupported data types
- Consistency between resolveType and toEvaluator

All tests are passing. PTAL and I'd appreciate your review! 🙏

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 2]
```diff
@@ -2590,6 +2590,118 @@ private void checkFullTextFunctionNullArgs(String functionInvocation, String arg
         );
     }
 
+public void testGreatestLeastWithUnsupportedDataTypes() {
```
Comment (ncordon) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: This doesn't look correctly indented, which probably the CI will complain about. You should be able to format these files with:

```
./gradlew :x-pack:plugin:esql:spotlessApply 
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 3]
```diff
@@ -2590,6 +2590,118 @@ private void checkFullTextFunctionNullArgs(String functionInvocation, String arg
...
+            "1:78: [MultiMatch] function cannot operate on [initial], which is not a field from an index mapping",
+            error("from test | eval initial = substring(first_name, 1) | where multi_match(\"A\", initial)")
+        );
+        assertEquals(
+            "1:80: [MultiMatch] function cannot operate on [text], which is not a field from an index mapping",
+            error("from test | eval text=concat(first_name, last_name) | where multi_match(\"cat\", text)")
+        );
+    }
+
+    public void testMultiMatchFunctionNotAllowedAfterCommands() throws Exception {
```
Comment (ncordon) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java]: Why are we adding tests for multimatch here?

**Review by ncordon — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution @shinsj4653!

> ✅ idegtiarenko's feedback: Refactored to use switch expressions instead of Map-based evaluator lookup

We have now duplicated the logic for knowing whether we support a type in `resolveType()` and `toEvaluator()` and we should not do that in my opinion. Otherwise, if somebody added a new type, they would have to add it to both places. Going with that approach misses the point of the issue https://github.com/elastic/elasticsearch/issues/114036, so I'm going to ask you to please revert to the evaluator map you used in https://github.com/elastic/elasticsearch/pull/128429/changes/95f84d28b019d07c1c648bf61f3c09fec75a4081

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java [hunk 4]
```diff
@@ -42,6 +47,17 @@ public class Least extends EsqlScalarFunction implements OptionalArgument {
...
+    private static final Map<DataType, Function<ExpressionEvaluator.Factory[], ExpressionEvaluator.Factory>> EVALUATOR_MAP = Map.of(
+        DataType.BOOLEAN, factories -> new LeastBooleanEvaluator.Factory(Source.EMPTY, factories),
+        DataType.DOUBLE, factories -> new LeastDoubleEvaluator.Factory(Source.EMPTY, factories),
+        DataType.INTEGER, factories -> new LeastIntEvaluator.Factory(Source.EMPTY, factories),
+        DataType.LONG, factories -> new LeastLongEvaluator.Factory(Source.EMPTY, factories),
+        DataType.DATETIME, factories -> new LeastLongEvaluator.Factory(Source.EMPTY, factories),
+        DataType.DATE_NANOS, factories -> new LeastLongEvaluator.Factory(Source.EMPTY, factories),
+        DataType.IP, factories -> new LeastBytesRefEvaluator.Factory(Source.EMPTY, factories),
+        DataType.VERSION, factories -> new LeastBytesRefEvaluator.Factory(Source.EMPTY, factories)
+    );
```
Comment (ncordon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java]: This is not correct. We cannot pass `Source.EMPTY`.

For reference in https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/GreaterThan.java we have this code:

```java
    private static final Map<DataType, EsqlArithmeticOperation.BinaryEvaluator> evaluatorMap = Map.ofEntries(
        Map.entry(DataType.INTEGER, GreaterThanIntsEvaluator.Factory::new),
        Map.entry(DataType.DOUBLE, GreaterThanDoublesEvaluator.Factory::new),
        Map.entry(DataType.LONG, GreaterThanLongsEvaluator.Factory::new),
        Map.entry(DataType.UNSIGNED_LONG, GreaterThanLongsEvaluator.Factory::new),
        Map.entry(DataType.DATETIME, GreaterThanLongsEvaluator.Factory::new),
        Map.entry(DataType.DATE_NANOS, GreaterThanLongsEvaluator.Factory::new),
        Map.entry(DataType.KEYWORD, GreaterThanKeywordsEvaluator.Factory::new),
        Map.entry(DataType.TEXT, GreaterThanKeywordsEvaluator.Factory::new),
        Map.entry(DataType.VERSION, GreaterThanKeywordsEvaluator.Factory::new),
        Map.entry(DataType.IP, GreaterThanKeywordsEvaluator.Factory::new)
    );
```

and then we apply that to the source and the arguments:

```java
evaluatorMap.get(commonType).apply(source(), lhs, rhs);
```

**Comment by ncordon** [comment]
buildkite test this please

**Comment by shinsj4653** [comment]
Hi @ncordon, thank you for the feedback and patience.

I have updated the PR with the following changes:

1. Reverted to Map-based Evaluator:
- Switched back to using `EVALUATOR_MAP` as requested, removing the switch expressions.
- Important Fix: To correctly pass the `source` (instead of Source.EMPTY), I updated the map values to be a `BiFunction` that accepts the source. This follows the pattern in `GreaterThan.java` as you suggested.
2. Cleaned up VerifierTests:
- Removed the unrelated `testMultiMatchFunctionNotAllowedAfterCommands` test.
- Also cleaned up some unrelated `MultiMatch` tests that were accidentally included in the previous rebase.
3. Formatting:
- Applied `spotlessApply` to fix formatting issues.


I've rebased onto the latest main and verified the changes by running the following local tests, which all passed successfully:

- `:x-pack:plugin:esql:test --tests "org.elasticsearch.xpack.esql.analysis.VerifierTests"`
- `:x-pack:plugin:esql:test --tests "org.elasticsearch.xpack.esql.expression.function.scalar.conditional.GreatestTests"`
- `:x-pack:plugin:esql:test --tests "org.elasticsearch.xpack.esql.expression.function.scalar.conditional.LeastTests"`


Please verify!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Greatest.java [hunk 5]
```diff
@@ -140,26 +167,24 @@ public boolean foldable() {
...
-            return new GreatestIntEvaluator.Factory(source(), factories);
-        }
-        if (dataType == DataType.LONG || dataType == DataType.DATETIME || dataType == DataType.DATE_NANOS) {
-            return new GreatestLongEvaluator.Factory(source(), factories);
-        }
-        if (DataType.isString(dataType) || dataType == DataType.IP || dataType == DataType.VERSION || dataType == DataType.UNSUPPORTED) {
 
+        if (DataType.isString(dataType)) {
             return new GreatestBytesRefEvaluator.Factory(source(), factories);
         }
```
Comment (ncordon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Greatest.java]: This can also be put in the evaluator map, there are two possible underlying types that are considered string I think

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java [hunk 6]
```diff
@@ -138,27 +165,24 @@ public boolean foldable() {
...
-            return new LeastIntEvaluator.Factory(source(), factories);
-        }
-        if (dataType == DataType.LONG || dataType == DataType.DATETIME || dataType == DataType.DATE_NANOS) {
-            return new LeastLongEvaluator.Factory(source(), factories);
-        }
-        if (DataType.isString(dataType) || dataType == DataType.IP || dataType == DataType.VERSION || dataType == DataType.UNSUPPORTED) {
 
+        if (DataType.isString(dataType)) {
             return new LeastBytesRefEvaluator.Factory(source(), factories);
         }
```
Comment (ncordon) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Least.java]: Same here 😄

**Review by ncordon — COMMENTED** [review]
Last suggested nit I am happy to approve and merge 😄

**Comment by ncordon** [comment]
buildkite test this please

**Comment by ncordon** [comment]
@shinsj4653 I think you deleted all of the tests from the pr by mistake

File: docs/changelog/128429.yaml [hunk 7]
```diff
@@ -0,0 +1,6 @@
+pr: 128429
+summary: [ESQL] Refactor Greatest and Least functions to use evaluator map
```
Comment (ncordon) [inline docs/changelog/128429.yaml]: I don't think the CI likes this square brakets much

**Comment by shinsj4653** [comment]
@ncordon I've addressed your feedback and pushed the updates:

1. `Changelog Fix`: Resolved the validate-changelogs failure by escaping the brackets in the YAML summary.
2. `Test Coverage`: Restored and expanded tests for Greatest.java and Least.java in VerifierTests.java
- Verified support for all mapped types including String (Keyword/Text), IP, Version, and Date, in addition to Numerics.
- Specific tests for Text fields were added using fullTextAnalyzer.

Local build and tests passed. Ready for another look when you have a chance. Thanks!

**Comment by ncordon** [comment]
buildkite test this please

**Comment by ncordon** [comment]
buildkite test this please

**Comment by ncordon** [comment]
buildkite test this please

**Comment by ncordon** [comment]
buildkite test this please

**Review by ncordon — APPROVED** [review]
Thanks for your contribution @shinsj4653. LGTM!

**Comment by shinsj4653** [comment]
Thank you @ncordon for your guidance and support throughout this contribution!
It was a great learning experience. I look forward to contributing more to Elasticsearch and other open source projects in the future. Have a great day!

**Comment by injae-kim** [comment]
Aweesome @shinsj4653 👍 👍 👍
