### PR TITLE
Peer recovery should flush at the end

### LINKED ISSUE #39588: CloseWhileRelocatingShardsIT.testCloseWhileRelocatingShards failure on master due to AssertionError in production code
Example CI links:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu8,nodes=immutable&&linux&&docker/272/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2323/console

I believe this may be related to replicated closed indices, as this particular failure first appeared (according to build stats) on the `replicated-closed-indices` branch on Feb. 8.

The assertion appears to come from [this check](https://github.com/elastic/elasticsearch/blob/11b58eb4c0bbf0e478aa495e395386a717b0d41d/server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java#L115-L118).

Reproduce line, does not reproduce locally:
```
./gradlew :server:integTest \
  -Dtests.seed=BB15E4FDA1CABDD9 \
  -Dtests.class=org.elasticsearch.indices.state.CloseWhileRelocatingShardsIT \
  -Dtests.method="testCloseWhileRelocatingShards" \
  -Dtests.security.manager=true \
  -Dtests.locale=de-DE \
  -Dtests.timezone=America/Lower_Princes \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Stack trace:
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=5128, name=elasticsearch[node_sd2][generic][T#1], state=RUNNABLE, group=TGRP-CloseWhileRelocatingShardsIT]
	at __randomizedtesting.SeedInfo.seed([B020647676D038FA:9FAB7AE3594E6E40]:0)
Caused by: java.lang.AssertionError: max seq. no. [-1] does not match [531]
	at __randomizedtesting.SeedInfo.seed([B020647676D038FA]:0)
	at org.elasticsearch.index.engine.ReadOnlyEngine.assertMaxSeqNoEqualsToGlobalCheckpoint(ReadOnlyEngine.java:142)
	at org.elasticsearch.index.engine.ReadOnlyEngine.<init>(ReadOnlyEngine.java:116)
	at org.elasticsearch.index.engine.NoOpEngine.<init>(NoOpEngine.java:40)
	at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1442)
	at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1395)
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:424)
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95)
	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302)
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93)
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1681)
	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2318)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'm going to mute this test in master as it appears to be failing a few times per day and looks like a legitimate failure.

### LINKED ISSUE #40024: [CI] CloseIndexIT.testCloseIndex failed
CloseIndexIT.testCloseIndex failed on
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/2283/console

Unable to reproduce locally with the following command:
```
./gradlew :server:integTest \
-Dtests.seed=82A3B95002BA7D9B \
-Dtests.class=org.elasticsearch.indices.state.CloseIndexIT \
-Dtests.method="testCloseIndex" \
-Dtests.security.manager=true \
-Dtests.locale=fr-CA \
-Dtests.timezone=America/Tortola \
-Dcompiler.java=11 \
-Druntime.java=8
```

### PR DESCRIPTION
**Pull request by dnhatn**
Flushing at the end of a peer recovery (if needed) can bring these benefits:

- Closing an index won't end up with the red state for a recovering replica should always be ready for closing whether it performs the verifying-before-close step or not.
- Good opportunities to compact store (i.e., flushing and merging Lucene, and trimming translog)

Closes #40024
Closes #39588
Relates #33888

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java [hunk 1]
```diff
@@ -303,11 +304,27 @@ public void finalizeRecovery(final long globalCheckpoint, ActionListener<Void> l
...
 
+    private boolean hasUncommittedOperations() {
+        if (indexShard.translogStats().getUncommittedOperations() == 0) {
+            return false;
+        }
+        // In peer recovery, we transfer history from primary to replica, thus we don't have to flush
+        // if all those uncommitted operations have baked into the existing Lucene index commit already.
+        final SequenceNumbers.CommitInfo commitInfo = SequenceNumbers.loadSeqNoInfoFromLuceneCommit(
+            indexShard.commitStats().getUserData().entrySet());
+        return commitInfo.maxSeqNo != commitInfo.localCheckpoint
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java]: I wonder if the condition above about the translog is sufficient. What situation is the condition here addressing that's not addressed by the above one?

**Review by ywelsch — CHANGES_REQUESTED** [review]
I've left a question.

File: server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java]: If a file-based occurs, the primary also sends its translog to replica. These operations are uncommitted on the replica even though they are baked into the commit already.  We need this condition to avoid flushing in this case to keep the syncId. I pushed https://github.com/elastic/elasticsearch/pull/41660/commits/07c3a7c03cc493b63ea6c7300fb4dbc1bbe501e9 to use another check.

**Comment by dnhatn** [comment]
run testDeleteExpiredData

**Comment by dnhatn** [comment]
run elasticsearch-ci/2

**Comment by dnhatn** [comment]
@elasticmachine test this please

**Review by henningandersen — COMMENTED** [review]
I think this could solve the issue and have other benefits as described.

But I am a bit worried about the implications, especially for future maintenance. If we ever add anything into `VerifyShardBeforeClose`, we need to also ensure the same holds at the end of a recovery. Also, I am not 100% sure recovery is the only place to ensure this (though I have no concrete cases).

I would find it more intuitive to (maybe in addition to this) add a check in `MetaDataIndexStateService.closeRoutingTable` to fail closing the index if the routing table contains unvalidated shard copies (meaning we would have to collect more info in the previous steps).

**Comment by ywelsch** [comment]
Good point @henningandersen, but failing the closing operation would also not be very user-friendly, as shards are free to move around based on rebalancing decisions. Let's consider more options here.

**Comment by dnhatn** [comment]
@henningandersen found that we can always validate max_seq_no equals to the global checkpoint in ReadOnlyEngine with this change. I pushed https://github.com/elastic/elasticsearch/pull/41660/commits/6e952c5cc45067c4cfb54c3a8e0e54febf57cfcf to enable it.

**Comment by henningandersen** [comment]
> @henningandersen found that we can always validate max_seq_no equals to the global checkpoint in ReadOnlyEngine with this change. I pushed [6e952c5](https://github.com/elastic/elasticsearch/commit/6e952c5cc45067c4cfb54c3a8e0e54febf57cfcf) to enable it.

I tend to think I was wrong about this, since FrozenEngine extends ReadOnlyEngine. If something was frozen on 6.7 or 7.0, it might not obey the invariant if they have #41041 ?

**Review by ywelsch — APPROVED** [review]
LGTM

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks everyone!
