### PR TITLE
Fix put mapping authorization for aliases with a write-index and multiple read indices

### LINKED ISSUE #40831: ILM policy Rollover action fails in case alias points to more than one index
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.2

**Description of the problem including expected versus actual behavior**:
Rollover action via ILM fails with unauthorized access when the user does
not have access to concrete index but only to alias.
This only happens when `is_write_index` is true, that is after the rollover
we can have rolled over-index with the same alias.

The authorization check fails as `IndicesAndAliasesResolver#getPutMappingIndexOrAlias` filters
out the alias name as it has multiple indices associated with it. For multiple indexes for the given alias, we should check if there is only one write index associated with it instead of simple size check.

https://github.com/elastic/elasticsearch/blob/c7379435439cc56c203329d085d4ad4cfd931ccb/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java#L249-L253

**Expected behavior:**
The rollover action should succeed resulting in successful policy run.

**Actual behavior:**
Fails with 
```
action [indices:admin/mapping/put] is unauthorized for user [test_user]
```

**Steps to reproduce**:
- Create ILM policy
```
PUT /_ilm/policy/foo-policy
         {
            "policy" : {
               "phases" : {
                  "hot" : {
                    "min_age": "0ms",
                    "actions" : {
                       "rollover" : {
                          "max_docs" : 2
                       }
                    }
                  }
               }
             }
          }
```

- Put Index template
```
PUT /_template/foo-template
         {
            "index_patterns": ["foo-logs-*"],
            "settings": {
              "number_of_shards": 1,
              "number_of_replicas": 0,
              "index.lifecycle.name": "foo-policy",
              "index.lifecycle.rollover_alias": "foo_alias"
            }
          }
```
- Create an index with alias
```
PUT /foo-logs-000001
         {
            "aliases": {
              "foo_alias" : { "is_write_index": true }
            }
          }
```

- Create a user with a role
```
PUT /_xpack/security/user/ufoo '{ "password": "foobar", "roles" : [ "foo_role" ]  }'

PUT /_xpack/security/role/foo_role '{ "cluster": [ "all" ], "indices": [ { "names": ["foo_alias"], "privileges": ["write", "manage"] } ] }'
```

- Index some documents such that ILM gets policy gets triggered using created user (`ufoo`)
```
POST /foo_alias/_doc '{ "field" : "foo" }'
POST /foo_alias/_doc '{ "field" : "foo" }'
```

- Verify new index exists
```
GET /foo-logs-000002
```

- Try to index using alias
```
POST /foo_alias/_doc '{ "field" : "foo" }'
```
Fails with :
```
action [indices:admin/mapping/put] is unauthorized for user [ufoo]
```

### PR DESCRIPTION
**Pull request by bizybot**
When the same alias points to multiple indices we can write to only one index
with `is_write_index` value `true`. The special handling in case of the put
mapping request(to resolve authorized indices) has a check on indices size
for a concrete index. If multiple indices existed then it marked the request
as unauthorized.

The check has been modified to consider write index flag and only when the
requested index matches with the one with write index alias, the alias is considered
for authorization.

Closes #40831

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java [hunk 1]
```diff
@@ -248,8 +248,17 @@ static String getPutMappingIndexOrAlias(PutMappingRequest request, List<String>
...
                 Optional<String> foundAlias = aliasMetaData.stream()
                     .map(AliasMetaData::alias)
+                    .filter(aliasName -> {
+                        List<IndexMetaData> indexMetadata = metaData.getAliasAndIndexLookup().get(aliasName).getIndices();
+                        if (indexMetadata.size() == 1) {
+                            return true;
+                        } else {
+                            IndexMetaData idxMeta = ((AliasOrIndex.Alias) metaData.getAliasAndIndexLookup().get(aliasName))
+                                    .getWriteIndex();
+                            return idxMeta != null && idxMeta.getIndex().getName().equals(concreteIndexName);
```
Comment (bizybot) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: A simple check would have been sufficient to check for `indexMetadata.size() >= 1`.
But this check helps in a scenario:
`logs-1` index with `is_write_index=false` and alias `alias-1`
`logs-2` index with `is_write_index=true` and alias `alias-1`
If the query is for `logs-1` and this request is `PutMappingRequest` this should not be allowed to proceed further.
From the authorization point of view, the user has access to `alias-1` but then the index `logs-1` is not writable.
I am on fence about this check, WDYT?

Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: I think, given "authorization on aliases" is a feature, we should stick with it and support it correctly.

If I have write access to `alias-1` (but no direct access to any indices), and that alias points to `logs-${today}` _(write index)_ and `logs-*` _(read)_, then the expectation would be that I only have write access to today's logs.
The security admin would be very surprised if this allowed a user to update mappings on old (in theory, read only) log indices.

Does that answer your question?

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java [hunk 2]
```diff
@@ -248,8 +248,17 @@ static String getPutMappingIndexOrAlias(PutMappingRequest request, List<String>
...
+                        }
+                    })
                     .filter(authorizedIndicesList::contains)
-                    .filter(aliasName -> metaData.getAliasAndIndexLookup().get(aliasName).getIndices().size() == 1)
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: Why did you need to move this above the `contains` filter?

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java [hunk 3]
```diff
@@ -248,8 +248,17 @@ static String getPutMappingIndexOrAlias(PutMappingRequest request, List<String>
             if (aliasMetaData != null) {
                 Optional<String> foundAlias = aliasMetaData.stream()
                     .map(AliasMetaData::alias)
+                    .filter(aliasName -> {
+                        List<IndexMetaData> indexMetadata = metaData.getAliasAndIndexLookup().get(aliasName).getIndices();
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: Can we extract `metaData.getAliasAndIndexLookup().get(aliasName)` into a local, and `assert` that it's an instance of `Alias` ?

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java [hunk 4]
```diff
@@ -1355,6 +1359,23 @@ public void testDynamicPutMappingRequestFromAlias() {
...
+        assert metaData.getAliasAndIndexLookup().get("logs-alias").getIndices().size() == 3;
+        String putMappingIndexOrAlias = IndicesAndAliasesResolver.getPutMappingIndexOrAlias(request, authorizedIndices, metaData);
+        assertEquals("logs-alias", putMappingIndexOrAlias);
+
+        index = "logs-00002";
+        request = new PutMappingRequest(Strings.EMPTY_ARRAY).setConcreteIndex(new Index(index, UUIDs.base64UUID()));
+        authorizedIndices = Collections.singletonList("logs-alias");
+        assert metaData.getAliasAndIndexLookup().get("logs-alias").getIndices().size() == 3;
+        putMappingIndexOrAlias = IndicesAndAliasesResolver.getPutMappingIndexOrAlias(request, authorizedIndices, metaData);
+        assertEquals(index, putMappingIndexOrAlias);
```
Comment (tvernum) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java]: Can you add a comment here, about why this is the expected behaviour
With the metadata setup being up top, it's easier to reason about this test if it has some comments.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java [hunk 5]
```diff
@@ -1355,6 +1359,23 @@ public void testDynamicPutMappingRequestFromAlias() {
         request = new PutMappingRequest(Strings.EMPTY_ARRAY).setConcreteIndex(new Index(index, UUIDs.base64UUID()));
         putMappingIndexOrAlias = IndicesAndAliasesResolver.getPutMappingIndexOrAlias(request, authorizedIndices, metaData);
         assertEquals(index, putMappingIndexOrAlias);
+
+    }
+
+    public void testDynamicPutMappingRequestForOneAliasForMultipleIndices() {
```
Comment (tvernum) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java]: I don't feel like this name captures the purpose of the test. Actually I think it will be easier to name well if the 2 cases are split into 2 tests.

File: x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/32_ilm_using_alias.yml [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+        body: >
+          {
+            "name" : "doc2"
+          }
+
+  - do:
+      indices.refresh: {}
+
+  # sleep so ilm task gets triggered
+  # this is a hacky way to sleep for 1s, since we will never have 10 nodes
```
Comment (tvernum) [inline x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/32_ilm_using_alias.yml]: I think this is a sign that maybe we shouldn't be trying to use a YAML test for this.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java (hunk 1 above)
Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: Yes, the only concern from this authorization checks is now the user is going to get access denied for the `logs-*` (read) when you try to write to those indices. Just that the user is not notified as write is denied because the concrete index is `read` only.
I think we both are on same page that it is right thing to deny access than failing at the later stage when actual write is being performed on the `read` index.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java (hunk 2 above)
Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: Thanks for noticing this, I think I was testing a scenario which failed but then realized it was more of a configuration issue but the change remained.
Modified this to filter out the authorized indices before other check as it was earlier.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java (hunk 3 above)
Comment (bizybot) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: Done, Thank you.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java (hunk 4 above)
Comment (bizybot) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java]: Done, Thanks

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java (hunk 5 above)
Comment (bizybot) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java]: Split this into two cases with a clear test name. Thank you.

File: x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/32_ilm_using_alias.yml (hunk 6 above)
Comment (bizybot) [reply x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/32_ilm_using_alias.yml]: I got carried away as I was trying to reproduce the problem and later converted into a test case. I have moved this test to ilm qa tests.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java (hunk 1 above)
Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: You & I seem to be thinking about this from different angles.
From my point of view all of this is an intention to make automatic dynamic mapping changes work when ingesting to an alias (even under a `is_write_index` scenario).
So if you write to `alias1` and that triggers a mapping update to `index1` it should work.
As a side-effect, if you do an explicit mapping update to `index1` it will also work because we can't distinguish between those cases, but we don't care because there was an avenue by which this would work, so this side-effect isn't opening up anything you couldn't already do.

You seem to be looking at this from a point of view of if I try to do a mapping update to `logs-${today}` it will work, but if I do it to `logs-${yesterday}` it will fail, even though I have the same privileges on those 2 indices.
And the reason is that the `logs` alias is writing to `logs-${today}` so that's why this mapping update is allowed.
I think it's a valid concern - security should aim to be clear and understandable, and it's not nice to have things that work/fail for reasons that are hard to discover.

But, while I appreciate the concern, I don't think this is really any different than the previous situation (before `is_write_index` existed) where you'd have separate `logs-write` and `logs-read` aliases (the former pointing to `logs-${today}`, the latter to `logs-*`).
It's a potential issue, but not one I've seen cause problems for users, and not one we need to solve here.

File: x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/32_ilm_using_alias.yml (hunk 6 above)
Comment (tvernum) [reply x-pack/plugin/src/test/resources/rest-api-spec/test/security/authz/32_ilm_using_alias.yml]: Thanks. I think it would be good for someone from @elastic/es-core-features to review that test since it's under the ILM module and they're likely to become the first point of call for maintenance, etc.

File: x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java [hunk 7]
```diff
@@ -126,7 +133,46 @@ public void testCanViewExplainOnUnmanagedIndex() throws Exception {
         assertOK(client().performRequest(request));
     }
 
-    private void createNewSingletonPolicy(String policy, String phaseName, LifecycleAction action) throws IOException {
+    public void testILMPolicyWithRolloverActionWhereUserRoleIsLimitedByAliasOfIndex() throws IOException, InterruptedException {
```
Comment (talevy) [inline x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java]: this test makes sense to me!

Since there is a lot of setup to get the user, index, and alias in the right state for the test, 
maybe some extra code comments could help people new to the code know what is being 
tested at a glance.

File: x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java [hunk 8]
```diff
@@ -126,7 +133,46 @@ public void testCanViewExplainOnUnmanagedIndex() throws Exception {
...
+        createNewSingletonPolicy(adminClient(), "foo-policy", "hot", new RolloverAction(null, null, 2L));
```
Comment (talevy) [inline x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java]: Actually, I have a question.

ILM executes its actions as the user that created the policy. In this case, it is the admin user, not `test_user`. 

This test is interested in verifying that the `test_user` has permissions to roll over the index? Looks like it may have permission to roll-over in this case, but it would not have permissions for other index-level actions, right?

File: x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java (hunk 7 above)
Comment (bizybot) [reply x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java]: Thanks, I have updated the documentation and changed the method name to reflect on what is being tested.

File: x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java (hunk 8 above)
Comment (bizybot) [reply x-pack/plugin/ilm/qa/with-security/src/test/java/org/elasticsearch/xpack/security/PermissionsIT.java]: I think the test name was misleading, the test is *not* to test ILM permissions but to test a scenario wherein the user `test_user` can write to the new index after rollover. The `test_user` has only manage and write privilege over the alias.
Thank you, I have corrected the documentation, test name.

**Review by talevy — APPROVED** [review]

**Review by albertzaharovits — APPROVED** [review]
LGTM, sorry for the delay!

I suggest when merging to change the name of the commit/PR, to something more representative such as: "put mapping authorization for aliases with write-index"

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java [hunk 9]
```diff
@@ -249,7 +249,17 @@ static String getPutMappingIndexOrAlias(PutMappingRequest request, List<String>
                 Optional<String> foundAlias = aliasMetaData.stream()
                     .map(AliasMetaData::alias)
                     .filter(authorizedIndicesList::contains)
-                    .filter(aliasName -> metaData.getAliasAndIndexLookup().get(aliasName).getIndices().size() == 1)
+                    .filter(aliasName -> {
+                        List<IndexMetaData> indexMetadata = metaData.getAliasAndIndexLookup().get(aliasName).getIndices();
+                        if (indexMetadata.size() == 1) {
+                            return true;
+                        } else {
+                            AliasOrIndex alias = metaData.getAliasAndIndexLookup().get(aliasName);
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: This could be moved up a couple of lines to before you assign `indexMetadata`, then you could use it there as well.

**Review by tvernum — APPROVED** [review]
LGTM, but I have 1 suggestion.
