### PR TITLE
[Test] Account for auto-repairing for shard gen file

### LINKED ISSUE #112769: [CI] RepositoryVerifyIntegrityIT testCorruption failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3995 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/vdbicx35akwn6)
- [elasticsearch-periodic-platform-support #3995 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/bmpyl2547zefe)
- [elasticsearch-pull-request #30817 / part-2](https://gradle-enterprise.elastic.co/s/n5guiktkdftsq)
- [elasticsearch-pull-request #30797 / part-2](https://gradle-enterprise.elastic.co/s/zyeurze3sk4qs)
- [elasticsearch-intake #9559 / part2](https://gradle-enterprise.elastic.co/s/46dvnpy6zmjzq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:snapshot-repo-test-kit:internalClusterTest" --tests "org.elasticsearch.repositories.blobstore.testkit.integrity.RepositoryVerifyIntegrityIT.testCorruption" -Dtests.seed=4C617F002EA1A2D6 -Dtests.locale=be-BY -Dtests.timezone=America/Danmarkshavn -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCorruption'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.blobstore.testkit.integrity.RepositoryVerifyIntegrityIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: not an empty collection
     but: was <[]>
```

**Issue Reasons:**
- [main] 5 failures in test testCorruption (12.8% fail rate in 39 executions)
- [main] 2 failures in step part-2 (10.5% fail rate in 19 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (11.1% fail rate in 18 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Since #112337, missing shard gen files are automatically reconstructed based on the existing shard snapshot files. If the list of shard snapshot files is complete, it means the repository is effectively not corrupted. This PR updates the test to account for this situation.

Resolves: #112769

### CODE REVIEW

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/integrity/RepositoryVerifyIntegrityIT.java [hunk 1]
```diff
@@ -344,16 +344,21 @@ public void testCorruption() throws IOException {
                 ? equalTo(testContext.indexNames().size())
                 : lessThan(testContext.indexNames().size())
         );
-        assertThat(anomalies, not(empty()));
+        // Missing shard generation file is automatically repaired based on the shard snapshot files.
+        // See also BlobStoreRepository#buildBlobStoreIndexShardSnapshots
+        assertThat(anomalies, corruptedFileType == RepositoryFileType.SHARD_GENERATION ? empty() : not(empty()));
```
Comment (ywangd) [inline x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/integrity/RepositoryVerifyIntegrityIT.java:349]: Alternatively, we can add a flag to make `buildBlobStoreIndexShardSnapshots` not repair missing shard gen file so that the verification can fail. I am not sure whether it is necessary since this would return warnings to users for something we already have a workaround, i.e. no action is required on the user side. In addition, the warning message about the repairing is logged in this case and I think that is all we need for this type of issue.

**Review by DaveCTurner — COMMENTED** [review]
Bah I didn't re-run these tests enough after implementing that workaround. However I don't think this is quite right, we should still get `failed to load shard generation` if the shard gen file is _corrupt_ (truncated or modified) rather than just deleted.

**Comment by ywangd** [comment]
> we should still get failed to load shard generation if the shard gen file is corrupt (truncated or modified) rather than just deleted.

Thanks! You are right. I updated the PR to account for that.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/112788)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
