### PR TITLE
[Transform] stop transform regardless of transform nodes

### LINKED ISSUE #69260: [Transform] can't delete transform, stop start after rolling upgrade / node role change
**Upstream issue**: https://github.com/elastic/kibana/issues/91570

**Affected versions**: 7.7.0 - 

After a change to the cluster - could by a rolling upgrade or fine-tuning of settings - a formerly running transform reports it is stopped, e.g.:

```
{
  "count" : 1,
  "transforms" : [
    {
      "id" : "t2",
      "state" : "stopped",
```

However trying to delete it, claims it is running:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "status_exception",
        "reason" : "Cannot delete transform [t2] as the task is running. Stop the task first"
      }
    ],
    "type" : "status_exception",
    "reason" : "Cannot delete transform [t2] as the task is running. Stop the task first"
  },
  "status" : 409
}
```

Trying to delete it with `force` times out and trying to start it, claims the task as well.

As a result it is not possible to delete the transform or use it.

**Mitigation**:

Transform requires a transform node to run on. To verify whether you have a node that can run transform check the output of ```GET _cat/nodes```:

```
v.x.y.z 2 99 2 0.68 0.66 1.43 dm  * elasticsearch01
...
```

The above output is not valid, because only data and master node roles are available. You _must_ have at least 1 node that has a `t`, e.g.:

```
...
v.x.y.z 2 99 2 0.68 0.66 1.43 dt  * elasticsearch03
...
```

The above shows a data _and_ transform node. Note, you only need 1 node with a `t` aka transform node.

**Solution**:

The solution of this problem has 2 aspects:

 - operational:
   - it must be possible to delete a (running) transform
   - stats should report the correct state
 - user-experience:
   - API's must better handle the case of a missing transform node
     - stats warn about no transform nodes / show number of transform nodes
     - preview should warn about no transform nodes
     - the UI should show the number of transform nodes (and visually indicate if there is none)

### PR DESCRIPTION
**Pull request by hendrikmuhs**
allow stop transform to stop a transform task if its waiting for assignment(e.g. if
the cluster lacks a transform node)

fixes #69260

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodeAssignments.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+        final Set<String> stopped
+    ) {
+        this.executorNodes = Collections.unmodifiableSet(executorNodes);
+        this.assigned = Collections.unmodifiableSet(assigned);
+        this.waitingForAssignment = Collections.unmodifiableSet(waitingForAssignment);
+        this.stopped = Collections.unmodifiableSet(stopped);
+    }
+
+    /*
+     * Get nodes were (requested) transforms are executed.
```
Comment (davidkyle) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodeAssignments.java:42]:
```suggestion
     * Get nodes where (requested) transforms are executed.
```

'were' -> 'where'

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodes.java [hunk 2]
```diff
@@ -38,14 +41,23 @@ private TransformNodes() {}
...
+                    assigned.add(task.getId());
+                } else {
+                    waitingForAssignment.add(task.getId());
+                }
             }
         }
 
-        return executorNodes.toArray(new String[0]);
+        Set<String> stopped = transformIds.stream()
+            .filter(id -> (assigned.contains(id) || waitingForAssignment.contains(id) == false))
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodes.java:58]: Shouldn't the parentheses be different here?
```
.filter(id -> (assigned.contains(id) || waitingForAssignment.contains(id)) == false)
```

Comment (davidkyle) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodes.java]: Stopped transforms are the ones that don't have a task, the id is neither assigned or unassigned.

```suggestion
            .filter(id -> (assigned.contains(id) == false || waitingForAssignment.contains(id) == false))
```

Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodes.java]: :+1: I applied @przemekwitek suggestion and moved the parentheses. There are also some more tests.

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodeAssignments.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+
+package org.elasticsearch.xpack.transform.action;
+
+import java.util.Collections;
+import java.util.Set;
+
+/**
+ * Record of transform tasks and their current persistent task state.
+ *
+ * This class is aimed to be be used by start/stop and stats action.
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformNodeAssignments.java:16]:
```suggestion
 * This class is aimed to be used by start/stop and stats action.
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java [hunk 4]
```diff
@@ -185,15 +187,29 @@ protected void doExecute(Task task, Request request, ActionListener<Response> li
...
+                        doExecuteListener.onResponse(new Response(true));
+                    }
                 }, e -> {
                     if (e instanceof ResourceNotFoundException) {
                         Tuple<Set<String>, Set<String>> runningTasksAndNodes = findTasksWithoutConfig(state, request.getId());
                         if (runningTasksAndNodes.v1().isEmpty()) {
                             listener.onFailure(e);
                             // found transforms without a config
                         } else if (request.isForce()) {
+                            // TODO: handle tasks waiting for assignment
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java:212]: So, what is there left to do? Aren't waiting tasks handled by `cancelTransformTasksWithNoAssignment`?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java [hunk 5]
```diff
@@ -458,4 +474,34 @@ private void waitForTransformStopped(
             listener.onFailure(e);
         }));
     }
+
+    private ActionListener<Response> cancelTransformTasksWithNoAssignment(
+        final ActionListener<Response> finalListener,
+        final TransformNodeAssignments transformNodeAssignments
+    ) {
+        final ActionListener<Response> doExecuteListener;
+        doExecuteListener = ActionListener.wrap(response -> {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java:483]: Could you get rid of `doExecuteListener` and just call `return ActionListener.wrap(...)`?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java [hunk 6]
```diff
@@ -458,4 +474,34 @@ private void waitForTransformStopped(
...
+            GroupedActionListener<PersistentTask<?>> groupedListener;
+            groupedListener = new GroupedActionListener<>(
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java:485]:
```suggestion
            GroupedActionListener<PersistentTask<?>> groupedListener = new GroupedActionListener<>(
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java [hunk 7]
```diff
@@ -458,4 +474,34 @@ private void waitForTransformStopped(
...
+                transformNodeAssignments.getWaitingForAssignment().size()
+            );
+
+            for (String unassignedTaskId : transformNodeAssignments.getWaitingForAssignment()) {
+                persistentTasksService.sendRemoveRequest(unassignedTaskId, groupedListener);
+            }
+
+        }, e -> {
+            GroupedActionListener<PersistentTask<?>> groupedListener;
+            groupedListener = new GroupedActionListener<>(
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java:496]:
```suggestion
            GroupedActionListener<PersistentTask<?>> groupedListener = new GroupedActionListener<>(
```

**Review by davidkyle — APPROVED** [review]
LGTM

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java (hunk 4 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java:212]: this is the special case were the transform "lost" the configuration, meaning it could not be found in the transform index. This happens if you e.g. manually delete the document or the whole index. 

I still think we should handle it, but I like to postpone it to the follow up, I added the todo there.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java (hunk 5 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java]: good points, not sure, why I ended up with this, maybe due to a re-factoring. Thanks for the hint.

**Review by przemekwitek — APPROVED** [review]
LGTM
