### PR TITLE
[Test] Wait for clsuter to form before assertions

### LINKED ISSUE #130979: [CI] VotingOnlyNodePluginTests testVotingOnlyNodesCannotBeMasterWithoutFullMasterNodes failing
**Build Scans:**
- [elasticsearch-periodic #9265 / openjdk24_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/iy6yiyxam2ab2)
- [elasticsearch-pull-request #79858 / part-2](https://gradle-enterprise.elastic.co/s/rysa5w5a4oukw)
- [elasticsearch-pull-request #79850 / part-2](https://gradle-enterprise.elastic.co/s/wztwiqmlhmraq)
- [elasticsearch-pull-request #79636 / part-2](https://gradle-enterprise.elastic.co/s/sw2buunne7rog)
- [elasticsearch-intake #25217 / part2](https://gradle-enterprise.elastic.co/s/6yamuzronsg54)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:voting-only-node:internalClusterTest" --tests "org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodePluginTests.testVotingOnlyNodesCannotBeMasterWithoutFullMasterNodes" -Dtests.seed=57D5D7769012CADB -Dtests.locale=br-Latn-FR -Dtests.timezone=America/Detroit -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodePluginTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testVotingOnlyNodesCannotBeMasterWithoutFullMasterNodes'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Values should be different. Actual: null
```

**Issue Reasons:**
- [main] 5 failures in test testVotingOnlyNodesCannotBeMasterWithoutFullMasterNodes (1.8% fail rate in 285 executions)
- [main] 3 failures in step part-2 (2.0% fail rate in 147 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.0% fail rate in 147 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
The original cluster should be properly formed before the tests kick off. This PR ensures that.

Relates: #129118
Resolves: #130883
Resolves: #130979

### CODE REVIEW

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java [hunk 1]
```diff
@@ -108,6 +109,7 @@ public void testPreferFullMasterOverVotingOnlyNodes() throws Exception {
         internalCluster().stopCurrentMasterNode();
         awaitMasterNode();
         assertNotEquals(originalMaster, internalCluster().getMasterName());
+        ensureStableCluster(2 + numDataNodes); // wait for all nodes to join
```
Comment (DaveCTurner) [inline x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: This weakens the test slightly more than I'd like. The trouble here is in fact that these tests run with `autoManageMasterNodes = false` so they skip over the call to `validateClusterFormed()` when starting nodes here:

https://github.com/elastic/elasticsearch/blob/ecbc360f37463b9c67a0f882a2bd1b429768a0b0/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java#L2252-L2254

That makes sense in general because if we're not auto-bootstrapping the test cluster we cannot expect it to be fully-formed after each node starts. But in these tests we can expect the cluster to be fully formed after we've finished starting all the nodes, so we should call that method explicitly ourselves there. Importantly, I think we should do that _before_ stopping the original master node, since the new master node should not spuriously drop any of  the other nodes from the cluster when it takes over.

I think I'd like us to rework these tests slightly so that rather than an `assertBusy()` on the current state having the right size of configuration we use `ESIntegTestCase#awaitClusterState(Predicate<ClusterState>)` to wait for a state which has the right voting configuration _and_ the right number of nodes.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 2]
```diff
@@ -965,12 +965,13 @@ public void awaitMasterNode(String viaNode, String masterNodeName) {
     }
 
     /**
-     * Waits for all nodes in the cluster to have a consistent view of which node is currently the master.
+     * Waits for all nodes forming the publish quorum in the cluster to have a consistent view of which node is currently the master.
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java]: This isn't correct. A publish quorum is some subset of the master-eligible nodes in the cluster (e.g. 2 of the 3 masters) which is much weaker than what this does. Here we're waiting for all the nodes in the cluster (i.e. in `ClusterState#nodes`).

**Review by DaveCTurner — CHANGES_REQUESTED** [review]

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 2 above)
Comment (ywangd) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java]: Thanks! I meant the nodes could still be in a different cluster state version after this method is returned, is this true? But you are right that the nodes should all have the same master. The trouble here is that there could still be nodes trying to join the cluster when this returns. In that case, it does _not_ guarantee the "all nodes", which is more than `ClusterState#nodes`, to see the same master. Technically it is the current behaviour, but kindas defeats its purpose in such situation?

Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java]: The `setWaitForEvents(Priority.LANGUID)` means that there was a point in time during the execution of this method where there was a committed cluster state and all the nodes in that cluster state were on the same cluster state version (or stuff was timing out, but that doesn't happen in these tests). It can't guarantee that another publication hasn't started before the method returns ofc.

You're right that there may also be nodes still trying to join the cluster at this point, but they're not _in the cluster_ (they haven't joined it yet). In practice, it's up to the caller to account for this.

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java (hunk 1 above)
Comment (ywangd) [reply x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: Updated as suggested in ce1452cbb1956a9926883b6110c6867f279aa571
Please let me know if it looks right to you. Thanks!

Comment (ywangd) [reply x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: The update also includes fix for a new but similar nature failure #130979

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 2 above)
Comment (ywangd) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java]: I reverted changes to the comment in 5445ef6500875f174b55b5daa9795d4e412bb792. We can update it separately (if at all). Thanks!

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java [hunk 3]
```diff
@@ -96,24 +97,21 @@ public void testPreferFullMasterOverVotingOnlyNodes() throws Exception {
...
+        internalCluster().validateClusterFormed();
+
+        awaitClusterState(
+            state -> state.getLastCommittedConfiguration().getNodeIds().size() == 3 && state.nodes().size() == 3 + numDataNodes
         );
         final String originalMaster = internalCluster().getMasterName();
 
         internalCluster().stopCurrentMasterNode();
-        awaitMasterNode();
+        internalCluster().validateClusterFormed();
```
Comment (DaveCTurner) [inline x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: I'd rather this remained as just an `awaitMasterNode()`. That should be sufficient here...

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java [hunk 4]
```diff
@@ -96,24 +97,21 @@ public void testPreferFullMasterOverVotingOnlyNodes() throws Exception {
...
         assertNotEquals(originalMaster, internalCluster().getMasterName());
-        assertThat(
-            VotingOnlyNodePlugin.isVotingOnlyNode(
-                clusterAdmin().prepareState(TEST_REQUEST_TIMEOUT).get().getState().nodes().getMasterNode()
-            ),
-            equalTo(false)
-        );
+        final ClusterState state = clusterAdmin().prepareState(TEST_REQUEST_TIMEOUT).get().getState();
+        assertThat(state.nodes().size(), equalTo(2 + numDataNodes));
```
Comment (DaveCTurner) [inline x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: ... except for this new assertion, which I think we should revert. This requires us to wait for the old master to be removed, and that shouldn't be necessary to make the more important assertion that the elected master is not voting-only.

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java [hunk 5]
```diff
@@ -157,21 +155,21 @@ public void testVotingOnlyNodesCannotBeMasterWithoutFullMasterNodes() throws Exc
...
-        awaitMasterNode();
-        final String oldMasterId = clusterAdmin().prepareState(TEST_REQUEST_TIMEOUT).get().getState().nodes().getMasterNodeId();
+        final String oldMasterId = internalCluster().getMasterName();
 
         internalCluster().stopCurrentMasterNode();
         awaitMasterNotFound();
 
         // start a fresh full master node, which will be brought into the cluster as master by the voting-only nodes
         final String newMaster = internalCluster().startNode();
+        internalCluster().validateClusterFormed();
```
Comment (DaveCTurner) [inline x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: I think we should revert this too, it's stronger than needed. `InternalTestCluster#getMasterName` already waits for the new master to be elected, and that's enough.

**Review by DaveCTurner — APPROVED** [review]
LGTM

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java (hunk 3 above)
Comment (ywangd) [reply x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: I think it is theoretically possible that the data node fails to join the new master so that `awaitMasterNode()` returns without seeing the data node. If we later ask the data node (via a randomed client) about its master and it could fail with NPE. That said, it is not a practical concern for this test. So I reverted back to use `awaitMasterNode`.

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java (hunk 4 above)
Comment (ywangd) [reply x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: Good point. I removed this.

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java (hunk 5 above)
Comment (ywangd) [reply x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: I think my above [reply](https://github.com/elastic/elasticsearch/pull/130973#discussion_r2197134042) applies to here. Thanks!

**Comment by ywangd** [comment]
This has been a good case for me to dig a bit deeper into the cluster coordination area. Thanks a lot for the review and discussion!

File: x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java (hunk 3 above)
Comment (DaveCTurner) [reply x-pack/plugin/voting-only-node/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/votingonly/VotingOnlyNodePluginTests.java]: > theoretically possible that the data node fails to join the new master

No, that shouldn't be possible (i.e. I'd want the test to fail if that happens). The new master will start from the state that the old master last committed, which will include the data node, so the data node will automatically be part of the new master's cluster. The new master would only remove the data node from its cluster if something positively fails (e.g. network disconnect).
