### PR TITLE
[Transform] Rearrange failure reason

### LINKED ISSUE #106819: [Transform] Rearrange stop/start failure message
### Description

Current messages have the `force` parameter suggestion at the end of the error message, potentially hidden by a very long stack trace.  We should rearrange it so that the suggestion is before the stack trace.

### PR DESCRIPTION
**Pull request by prwhelan**
Stop and Start error messages include the reason for the error followed by the suggestion to use force=true.  This may cause the suggestion to be hidden by the reason, so we will move the reason after the suggestion.

Close #106819

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMessages.java [hunk 1]
```diff
@@ -35,11 +35,12 @@ public class TransformMessages {
...
 
-    public static final String CANNOT_STOP_FAILED_TRANSFORM = "Unable to stop transform [{0}] as it is in a failed state with reason [{1}]."
-        + " Use force stop to stop the transform.";
-    public static final String CANNOT_START_FAILED_TRANSFORM =
-        "Unable to start transform [{0}] as it is in a failed state with failure: [{1}]. "
-            + "Use force stop and then restart the transform once error is resolved.";
+    public static final String CANNOT_STOP_SINGLE_FAILED_TRANSFORM = "Unable to stop transform [{0}] as it is in a failed state. "
+        + "Use force stop to stop the transform. More details: [{1}]";
+    public static final String CANNOT_STOP_MULTIPLE_FAILED_TRANSFORM = "Unable to stop transforms. The following transforms are in a failed"
+        + " state [{0}]. Use force stop to stop the transform. More details: [{1}]";
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMessages.java:41]:
```suggestion
        + " state [{0}]. Use force stop to stop the transforms. More details: [{1}]";
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMessages.java [hunk 2]
```diff
@@ -35,11 +35,12 @@ public class TransformMessages {
...
         "Transform requires the transform node role for at least 1 node, found no transform nodes";
 
-    public static final String CANNOT_STOP_FAILED_TRANSFORM = "Unable to stop transform [{0}] as it is in a failed state with reason [{1}]."
-        + " Use force stop to stop the transform.";
-    public static final String CANNOT_START_FAILED_TRANSFORM =
-        "Unable to start transform [{0}] as it is in a failed state with failure: [{1}]. "
-            + "Use force stop and then restart the transform once error is resolved.";
+    public static final String CANNOT_STOP_SINGLE_FAILED_TRANSFORM = "Unable to stop transform [{0}] as it is in a failed state. "
+        + "Use force stop to stop the transform. More details: [{1}]";
+    public static final String CANNOT_STOP_MULTIPLE_FAILED_TRANSFORM = "Unable to stop transforms. The following transforms are in a failed"
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMessages.java:40]:
```suggestion
    public static final String CANNOT_STOP_MULTIPLE_FAILED_TRANSFORMS = "Unable to stop transforms. The following transforms are in a failed"
```

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/action/TransportStopTransformActionTests.java [hunk 3]
```diff
@@ -80,20 +79,60 @@ public void testTaskStateValidationWithTransformTasks() {
...
+        ex = expectThrows(
+            ElasticsearchStatusException.class,
+            () -> TransportStopTransformAction.validateTaskState(csBuilderMultiTask.build(), List.of("failed-task", "failed-task-2"), false)
+        );
+
+        assertThat(ex.status(), equalTo(CONFLICT));
+        assertThat(
+            ex.getMessage(),
+            equalTo(
+                TransformMessages.getMessage(
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/action/TransportStopTransformActionTests.java:130]: Could you just put the full message here?
This will also verify that the substitution works correctly.

File: x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformTaskFailedStateIT.java [hunk 4]
```diff
@@ -84,10 +84,10 @@ public void testForceStopFailedTransform() throws Exception {
         assertThat(ex.getResponse().getStatusLine().getStatusCode(), equalTo(RestStatus.CONFLICT.getStatus()));
         assertThat(
             (String) XContentMapValues.extractValue("error.reason", entityAsMap(ex.getResponse())),
-            matchesRegex(
-                "Unable to stop transform \\[test-force-stop-failed-transform\\] as it is in a failed state with reason \\["
+            startsWith(
```
Comment (przemekwitek) [inline x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformTaskFailedStateIT.java:87]: BTW, could it be `equalTo` now?

**Review by przemekwitek — APPROVED** [review]
LGTM

I can't see the release notes file in this PR.
Could it be that you pushed the PR with force to GitHub?
Could you try restore this file?

File: x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformTaskFailedStateIT.java (hunk 4 above)
Comment (prwhelan) [reply x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformTaskFailedStateIT.java:87]: It cannot, there's a much longer error message behind it: `Failed to index documents into destination index due to permanent error: [org.elasticsearch.xpack.transform.transforms.BulkIndexingException: Bulk index experienced [7] failures and at least 1 irrecoverable [org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.DocumentParsingException: [1:30] failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0'; java.lang.IllegalArgumentException: For input string: "user_0"].; org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.; org.elasticsearch.index.mapper.DocumentParsingException: [1:30] failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0'; java.lang.IllegalArgumentException: For input string: "user_0"]`

It's possible to be `equalTo` this but I can't seem to figure out why we switched from that to `matchRegex`
