### PR TITLE
Don't return TEXT type for functions that take TEXT

### LINKED ISSUE #111537: ESQL: "expr::text" cast returning a keyword
The `<x>::text` inline cast depends on `ToString` to make the cast, which always returns `keyword`.
It could make sense in `ToString`, but a `<x>::text` cast is expected to return a `text`.

## Reproduce with:

Query:
```sql
ROW txt="abc"::text
```

Result:
```json
{
  "columns": [
    {
      "name": "txt",
      "type": "keyword"
    }
  ],
  "values": [
    [
      "txt"
    ]
  ]
}
```

Note that the column type is "keyword".

## Another example

Index `test` with mapping:
```json
{
  "text_field": {
    "type": "text"
  }
}
```

Query:
```sql
FROM test
| eval x = CASE(true, text_field, "txt"::text)
```

Result:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "verification_exception",
        "reason": "Found 1 problem line 4:12: third argument of [CASE(true, text_field, \"txt\"::text)] must be [text], found value [\"txt\"::text] type [keyword]"
      }
    ],
    "type": "verification_exception",
    "reason": "Found 1 problem line 4:12: third argument of [CASE(true, text_field, \"txt\"::text)] must be [text], found value [\"txt\"::text] type [keyword]"
  },
  "status": 400
}
```

### LINKED ISSUE #114333: TEXT fields should be converted to KEYWORD by any function that changes their values
In ES|QL, many functions can take both KEYWORD and TEXT as input parameters, and change their values to strings. This change destroys the meaning of any analyzer associated with the original TEXT, and so the output should always be KEYWORD. But several functions mistakenly return TEXT (ie. return their input data type).

Functions known to have this issue:
* Explicitly returning `field.dataType`
  * ToUpper
  * ToLower
* Implicitly as a result of extending `UnaryScalarFunction`:
  * LTrim
  * RTrim
  * Trim
  * Reverse

Other functions that take TEXT but already are fixed to only return KEYWORD:
* ToString
* FromBase64
* ToBase64
* Replace
* Right
* Left

### PR DESCRIPTION
**Pull request by craigtaverner**
Always return `KEYWORD` for functions that previously returned `TEXT`, because any change to the value, no matter how small, is enough to render meaningless the original analyzer associated with the `TEXT` field value. In principle, if the attribute is no longer the original `FieldAttribute`, it can no longer claim to have the type `TEXT`.

This has been done for all functions: conversion functions, aggregating functions, multi-value functions. There were several that already produced `KEYWORD` for `TEXT` input (eg. ToString, FromBase64 and ToBase64, MvZip, ToLower, ToUpper, DateFormat, Concat, Left, Repeat, Replace, Right, Split, Substring), but many others that incorrectly claimed to produce `TEXT`, while this was really a false claim. This PR makes that now strict, and includes changes to the functions' units tests to disallow the tests to expect any functions output to be `TEXT`.

One side effect of this change is that methods that take multiple parameters that require all of them to have the same type, will now treat TEXT and KEYWORD the same. This was already the case for functions like `Concat`, but is now also the case for `Greatest`, `Least`, `Case`, `Coalesce` and `MvAppend`.

An associated change is that the type casting operator `::text` has been entirely removed. It used to map onto the `ToString` function which returned type KEYWORD, and so `::text` really produced a `KEYWORD`, which is a lie, or at least a `bug`, which is now fixed. Should we ever wish to actually produce real `TEXT`, we might love the fact that this operator has been freed up for future use (although it seems likely that function will require parameters to specify the analyzer, so might never be an operator again).

### Backwards compatibility issues:

This is a change that will fail BWC tests, since we have many tests that assert on TEXT output to functions. For this reason we needed to block two scenarios:

* We used the capability `functions_never_emit_text` to prevent 7 csv-spec tests and 2 yaml tests from being run against older versions that still emit text.
* We used `skipTest` to also block those two yaml tests from being run against the latest build, but using older yaml files downloaded (as far back as 8.14).

In all cases the change observed in these tests was simply the results columns no longer having `text` type, and instead being `keyword`.

### Kibana

Kibana makes use of some JSON files we produce during tests runs that explain the signatures of the functions, and the available type-casting operators. These are now edited to remove all `TEXT` output, and remove the `::test` operator.

### Fixes

Fixes #114333
Fixes #111537

### CODE REVIEW

**Review by astefan — CHANGES_REQUESTED** [review]
I think it's a good step forward, but imo we could do better.
This needs a general evaluation of the situation because `text` as an output data type of our own functions is confusing, meaningless and not so useful at this point in the life of the language. So:
- all functions need to be checked. I've caught `max(text)` which returns `text`. If we are to make this change, let's make it general.
- to catch any misses, we should have a check in a central location for return data types of any kind of function/operator/anything-else (maybe after the logical planner is done, not sure). Maybe with an `assert` so that we don't fail queries at runtime, unless it's CI/tests.
- another way of looking at the problem is that `text` (as a data type) does only make sense for FieldAttributes? (meaning we can accept `text` fields, we can do stuff with them, but creating a `text` shouldn't be possible)

**Comment by astefan** [comment]
> > * Change the parent class `UnaryScalarFunction` to always return KEYWORD for TEXT fields (done in this PR to cover functions not yet fixed)
> 
> I think I'd _prefer_ if `UnaryScalarFunction` didn't have a default return type. That's a bigger change though because everyone's got to fill in their return type.

++
Also, `UnaryScalarFunction` is not the only function in the class' hierarchy.

**Comment by nik9000** [comment]
> central location

I was thinking that the tests for functions could assert that they never spit out `text`. I think you could override that when we go to implement `ANALYZE(kwd, FRENCH)` or whatever we call it, but only a hand full of function will ever output `text` fields and I'm ok with extra work telling you "you probably don't want to return `text` here" when writing them.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java [hunk 1]
```diff
@@ -80,7 +82,8 @@ public Values replaceChildren(List<Expression> newChildren) {
 
     @Override
     public DataType dataType() {
-        return field().dataType();
+        DataType t = field().dataType();
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java:85]: Instead of doing this for every aggregation function, how about going to `AggregateFunction` and define there something similar to `UnaryScalarFunction.dataType()`?

**Review by mark-vieira — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Max.java [hunk 2]
```diff
@@ -107,7 +109,8 @@ protected TypeResolution resolveType() {
 
     @Override
     public DataType dataType() {
-        return field().dataType();
+        DataType t = field().dataType();
+        return t == TEXT ? KEYWORD : t;
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Max.java:113]: I have a small suggestion - feel free to leave this as it is - instead of checking for `t == TEXT` we could do `DataType.isString(t) ? KEYWORD : t`. The intention would be a bit clearer that for string arguments, the return type is keyword.
This would work in case we want to add another string type - which we do, we are working on adding `semantic_text`. So I think that even if we leave this as it is for now, we would still need to change this check to use `DataType.isString` when we add support for `semantic_text` to be a string type.

Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Max.java:113]: I double-checked, and this particular case was indeed not switched to use `noText()`, so I'll fix that directly, and look for more cases I might have missed.

**Review by astefan — APPROVED** [review]
LGTM. Looking much better. Thanks, Craig.

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypeConverter.java [hunk 3]
```diff
@@ -117,7 +117,6 @@ public class EsqlDataTypeConverter {
         entry(LONG, ToLong::new),
         // ToRadians, typeless
         entry(KEYWORD, ToString::new),
-        entry(TEXT, ToString::new),
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/type/EsqlDataTypeConverter.java:120]: Yes! I was busy creating a new issue for that, but glad to see you already did, way back! I'll add a 'fixes' line to the PR description.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/TestCaseSupplier.java [hunk 4]
```diff
@@ -1435,7 +1435,7 @@ public static TestCase typeError(List<TypedData> data, String expectedTypeError)
             this.source = Source.EMPTY;
             this.data = data;
             this.evaluatorToString = evaluatorToString;
-            this.expectedType = expectedType;
+            this.expectedType = expectedType == null ? null : expectedType.noText();
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/TestCaseSupplier.java:1438]: This is the comprehensive 'catch all' case we added late in the PR once we had covered all the low hanging fruit. But perhaps this means we can remove some of the other earlier code. I'll investigate.

[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/TestCaseSupplier.java:1438]: Indeed there were 12 places we had added this `noText()` that no longer needed it, since they all called into this TestCase constructor. I've removed them all and will push a commit after re-running tests to be safe.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java [hunk 5]
```diff
@@ -584,6 +584,10 @@ static Builder builder() {
         return new Builder();
     }
 
+    public DataType noText() {
```
Comment (bpintea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java:587]: `textAsKeyword()`? `noText` is compact, but I find it a tad misleading. Minor preference, can stay as is.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Top.java [hunk 6]
```diff
@@ -175,7 +177,8 @@ protected TypeResolution resolveType() {
 
     @Override
     public DataType dataType() {
-        return field().dataType();
+        DataType t = field().dataType();
+        return t == TEXT ? KEYWORD : t;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Top.java:181]: noText()?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java [hunk 7]
```diff
@@ -91,7 +93,8 @@ public Values withFilter(Expression filter) {
...
+        return t == TEXT ? KEYWORD : t;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java:97]: noText()?

**Review by bpintea — APPROVED** [review]
Lgtm

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java (hunk 5 above)
Comment (craigtaverner) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java:587]: The idea is sound, but I have a minor preference for `noText` as `textAsKeyword` also seems to say something about the current datatype being TEXT; which it likely is not.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Min.java [hunk 8]
```diff
@@ -107,7 +109,8 @@ protected TypeResolution resolveType() {
 
     @Override
     public DataType dataType() {
-        return field().dataType();
+        DataType t = field().dataType();
+        return t == TEXT ? KEYWORD : t;
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Min.java:113]: Done. I normally like to accept the commit suggestion, but in this case the remaining imports would cause a build failure, so I did this locally and will push a commit for all three places soon.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java (hunk 7 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java]: done

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Top.java (hunk 6 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Top.java]: done

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java [hunk 9]
```diff
@@ -584,6 +584,10 @@ static Builder builder() {
...
+        return this == DataType.TEXT ? DataType.KEYWORD : this;
```
[the remark this answers is not in the document]
Comment (craigtaverner) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/type/DataType.java]: Done

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Min.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Min.java]: all good, it's not like i really contributed :)
