### PR TITLE
[ML] Fix race condition when creating multiple jobs

### LINKED ISSUE #38785: [ML] Errors when running nginx module jobs
**Found in version**
- 7.0.0-beta1 BC2

**Steps to reproduce**
- Use the `nginx` module to create ML jobs

**Expected result**
- The 5 jobs defined in the module are created without errors

**Actual result**
- The elasticsearch.log shows a lot of errors of the form:
```
[DEBUG][o.e.a.b.TransportShardBulkAction] [elastic-ro] [.ml-anomalies-shared][0] failed to execute bulk item (index) index {[.ml-anomalies-.write-dr_remote_ip_request_rate][doc][dr_remote_ip_request_rate_influencer_1489273200000_3600_nginx.access.remote_ip_837166815_39], source[{"job_id":"dr_remote_ip_request_rate","result_type":"influencer","influencer_field_name":"nginx.access.remote_ip","influencer_field_value":"d59e:bcc0:846e:c67e:12fb:c430:f37c:9aec","nginx.access.remote_ip":"d59e:bcc0:846e:c67e:12fb:c430:f37c:9aec","influencer_score":5.767481395370252,"initial_influencer_score":5.767481395370252,"probability":2.1435293947279067E-6,"bucket_span":3600,"is_interim":true,"timestamp":1489273200000}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
    at org.elasticsearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:177) ~[elasticsearch-7.0.0-beta1.jar:7.0.0-beta1]
    at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:74) ~[elasticsearch-7.0.0-beta1.jar:7.0.0-beta1]

[...]

Caused by: java.lang.ClassCastException: org.elasticsearch.index.mapper.KeywordFieldMapper cannot be cast to org.elasticsearch.index.mapper.ObjectMapper
    at org.elasticsearch.index.mapper.DocumentParser.getDynamicParentMapper(DocumentParser.java:898) ~[elasticsearch-7.0.0-beta1.jar:7.0.0-beta1]
```

**Additional information**
- The `.ml-anomalies-shared` result index does not contain mappings for the job's term field mappings.

### PR DESCRIPTION
**Pull request by droberts195**
If multiple jobs are created together and the anomaly
results index does not exist then some of the jobs could
fail to update the mappings of the results index.  This
lead them to fail to write their results correctly later.

Although this scenario sounds rare, it is exactly what
happens if the user creates their first jobs using the
Nginx module in the ML UI.

This change fixes the problem by updating the mappings
of the results index if it is found to exist during a
creation attempt.

Fixes #38785

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java [hunk 1]
```diff
@@ -301,30 +303,53 @@ public void createJobResultIndex(Job job, ClusterState state, final ActionListen
...
+                                    // just been created.  So we need yet another operation to get the mappings for it.
+                                    getLatestIndexMappings(indexName, ActionListener.wrap(
+                                        response -> {
+                                            // Expect one index and one type.  If this is not the case then it means the
+                                            // index has been deleted almost immediately after being created, and this is
+                                            // so unlikely that it's reasonable to fail the whole operation.
+                                            ImmutableOpenMap<String, MappingMetaData> indexMappings =
+                                                response.getMappings().iterator().next().value;
+                                            MappingMetaData typeMappings = indexMappings.iterator().next().value;
+                                            addTermsAndAliases(typeMappings, indexName, termFields, createAliasListener);
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java]: It seems to me that a race condition around mappings still exists, though it is an equally rare one. 
* 3 calls to create the results index
* It gets created with by one of the calls (with those term mappings)
* The other two fail and fall into this clause, pull that single job's mapping, update it with their own fields, and put the whole mapping again
* The first of the two "late" jobs would lose its terms due to the second of the "late" jobs replacing the mapping on with `PutMappingRequest`

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java]: > * The first of the two "late" jobs would lose its terms due to the second of the "late" jobs replacing the mapping on with `PutMappingRequest`

No, because if you put mappings they always _add_ to the current mappings, they don't replace them.  This is how Elasticsearch mappings have always worked and is why we get away with _only_ putting mappings for the new job terms.  We don't put our core result field mappings except when the index is initially created and they don't get wiped out.

You are correct there is still a race condition, but it's on the number of fields in the mappings.  If you create 3 jobs simultaneously each with 400 new term fields then the one that creates the index will add the first 400.  The other two will see that their 400 plus the 400 already in the index is 800, which is OK, so will both try to put mappings.  And whichever of these requests arrives second will fail because then the index would have too many field mappings: 1200 plus however many core fields we have.  However, this has always been a bug as it could also happen in the code path where the index already exists.  The end result of this is that you'd get an unfriendly error message about mapping limits instead of a friendly one telling you you need to use a custom results index for the job, so it's not _that_ bad considering the tiny chance of it happening.

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java]: @droberts195 I read
```
// Put the whole mapping, not just the term fields, otherwise we'll wipe the _meta section of the mapping
try (XContentBuilder termFieldsMapping = ElasticsearchMappings.resultsMapping(mappingType, termFields)) {
```
incorrectly. I keep forgetting that an `UPDATE` to a mapping is done via a PUT and not a POST...

The number of fields is still a race condition, but only when it comes to failing early, which is acceptable.

**Review by benwtrent — APPROVED** [review]

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/packaging-sample
