### PR TITLE
compile ScriptProcessor inline scripts when creating ingest pipelines

### LINKED ISSUE #21842: 5.0: pipeline painless script error doesn't fail fast
I'm in the process of converting a groovy script to painless (previously run as a transform). One thing I noticed was that even through the script was incorrect it was accepted. Part of the mantra for 5.x is fail fast so as to give you a good dev experience. 

```json
PUT _ingest/pipeline/events-pipeline
{
  "processors": [
    {
      "script": {
        "inline": "\r\nif (!ctx._source.containsKey('data') || !(ctx._source.data.containsKey('@error') || ctx._source.data.containsKey('@simple_error')))\r\n    return\r\n\r\ndef types = []\r\ndef messages = []\r\ndef codes = []\r\ndef err = ctx._source.data.containsKey('@error') ? ctx._source.data['@error'] : ctx._source.data['@simple_error']\r\ndef curr = err\r\nwhile (curr != null) {\r\n    if (curr.containsKey('type'))\r\n        types.add(curr.type)\r\n    if (curr.containsKey('message'))\r\n        messages.add(curr.message)\r\n    if (curr.containsKey('code'))\r\n        codes.add(curr.code)\r\n    curr = curr.inner\r\n}\r\n\r\nerr['all_types'] = types.join(' ')\r\nerr['all_messages'] = messages.join(' ')\r\nerr['all_codes'] = codes.join(' ')"
      }
    }
  ]
}
```

I don't see a failure until I try to ingest data.

```json
PUT /test-events-201502/events/54dbc16ca0f5c61398427b00?op_type=create&pipeline=events-pipeline
{
  "id": "54dbc16ca0f5c61398427b00",
  "organization_id": "1ecd0826e447ad1e78877555",
  "project_id": "1ecd0826e447ad1e78877ab2",
  "stack_id": "1ecd0826e447a44e78877ab1",
  "is_first_occurrence": false,
  "is_fixed": true,
  "is_hidden": false,
  "created_utc": "2015-02-11T20:54:04.4082284",
  "type": "log",
  "source": "GET /Print",
  "date": "2015-02-11T20:54:04.3457274+00:00",
  "data": {
    "@version": "1.2.3.0",
    "@level": "Error"
  }
}
```

With the error

```json
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "java.lang.IllegalArgumentException: ScriptException[compile error]; nested: IllegalArgumentException[invalid sequence of tokens near ['types'].]; nested: NoViableAltException;",
        "header": {
          "processor_type": "script"
        }
      }
    ],
    "type": "exception",
    "reason": "java.lang.IllegalArgumentException: ScriptException[compile error]; nested: IllegalArgumentException[invalid sequence of tokens near ['types'].]; nested: NoViableAltException;",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "ScriptException[compile error]; nested: IllegalArgumentException[invalid sequence of tokens near ['types'].]; nested: NoViableAltException;",
      "caused_by": {
        "type": "script_exception",
        "reason": "compile error",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "invalid sequence of tokens near ['types'].",
          "caused_by": {
            "type": "no_viable_alt_exception",
            "reason": null
          }
        },
        "script_stack": [
          "... r')))\r\n    return\r\n\r\ndef types = []\r\ndef messages  ...",
          "                             ^---- HERE"
        ],
        "script": "\r\nif (!ctx._source.containsKey('data') || !(ctx._source.data.containsKey('@error') || ctx._source.data.containsKey('@simple_error')))\r\n    return\r\n\r\ndef types = []\r\ndef messages = []\r\ndef codes = []\r\ndef err = ctx._source.data.containsKey('@error') ? ctx._source.data['@error'] : ctx._source.data['@simple_error']\r\ndef curr = err\r\nwhile (curr != null) {\r\n    if (curr.containsKey('type'))\r\n        types.add(curr.type)\r\n    if (curr.containsKey('message'))\r\n        messages.add(curr.message)\r\n    if (curr.containsKey('code'))\r\n        codes.add(curr.code)\r\n    curr = curr.inner\r\n}\r\n\r\nerr['all_types'] = types.join(' ')\r\nerr['all_messages'] = messages.join(' ')\r\nerr['all_codes'] = codes.join(' ')",
        "lang": "painless"
      }
    },
    "header": {
      "processor_type": "script"
    }
  },
  "status": 500
}
```

### PR DESCRIPTION
**Pull request by talevy**
Inline scripts defined in Ingest Pipelines are not compiled at creation time and compile-time errors lazily occur upon initial execution of the pipeline.

WIP because it lacks tests.

Fixes #21842.

### CODE REVIEW

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java [hunk 1]
```diff
@@ -121,7 +143,12 @@ public ScriptProcessor create(Map<String, Processor.Factory> registry, String pr
                 throw newConfigurationException(TYPE, processorTag, null, "Could not initialize script");
             }
 
-            return new ScriptProcessor(processorTag, script, scriptService);
+            CompiledScript compiledInlineScript = null;
+            if (script.getType() == ScriptType.INLINE) {
+                compiledInlineScript = scriptService.compile(script, ScriptContext.Standard.INGEST, script.getOptions());
```
Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: I don't think the compile script should be stashed here. Instead, just check that the script can be resolved with the script service (don't just check inline; for example, it would then also ensure if they use a file script it exists).

Comment (talevy) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: ++ this is why I open WIP PRs! thanks – I'll check out what it means to resolve a script

**Comment by talevy** [comment]
@rjernst updated, please let me know if this is what you meant. thanks!

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java [hunk 2]
```diff
@@ -121,6 +131,15 @@ public ScriptProcessor create(Map<String, Processor.Factory> registry, String pr
                 throw newConfigurationException(TYPE, processorTag, null, "Could not initialize script");
             }
 
+            // compile inline and file-backed scripts to ensure they are valid before constructing the processor.
+            if (script.getType() == ScriptType.INLINE || script.getType() == ScriptType.FILE) {
```
Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: I don't see why we need to restrict types here. This should work fine for stored scripts as well, and they should be validated too.

Comment (talevy) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: I guess my assumption was that stored scripts are compiled when being stored. is this not the case?

Comment (talevy) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: but, yeah, I'm good with it. less branching

Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: Yes they are, but you still want to ensure the script id exists?

Comment (talevy) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: yes 😞. working on this in-between logstash builds is not helping my thought process. will update. thanks for review

**Comment by talevy** [comment]
retest this please

**Comment by talevy** [comment]
retest this please

**Comment by talevy** [comment]
retest this please

**Comment by talevy** [comment]
@rjernst mind taking another gander when you find the time? thanks

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java [hunk 3]
```diff
@@ -28,38 +28,48 @@
...
 import static org.elasticsearch.common.Strings.hasLength;
 import static org.elasticsearch.ingest.ConfigurationUtils.newConfigurationException;
 import static org.elasticsearch.ingest.ConfigurationUtils.readOptionalMap;
 import static org.elasticsearch.ingest.ConfigurationUtils.readOptionalStringProperty;
-import static org.elasticsearch.ingest.ConfigurationUtils.readStringProperty;
 import static org.elasticsearch.script.ScriptType.FILE;
 import static org.elasticsearch.script.ScriptType.INLINE;
 import static org.elasticsearch.script.ScriptType.STORED;
 
-/**
```
Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: Can you keep some basic docs here?

File: modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java [hunk 4]
```diff
@@ -28,38 +28,48 @@
...
+    /**
+     * Executes the script with the Ingest document in context.
+     *
+     * @param document The Ingest document passed into the script context under the "ctx" object.
+     */
     @Override
     public void execute(IngestDocument document) {
-        ExecutableScript executableScript = scriptService.executable(script, ScriptContext.Standard.INGEST);
+        ExecutableScript executableScript;
+        executableScript = scriptService.executable(script, ScriptContext.Standard.INGEST);
```
Comment (rjernst) [inline modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ScriptProcessor.java]: revert splitting this over 2 lines?

**Review by rjernst — APPROVED** [review]
Looks good.
