### PR TITLE
ESQL: Document VALUES uniques

### LINKED ISSUE #128091: [ES|QL] `values` function does not return _all_ values as it dedupes them
### Elasticsearch Version

8.18.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Container

### Problem Description

The [`values`](https://www.elastic.co/docs/reference/query-languages/esql/functions-operators/aggregation-functions#esql-values) aggregation states that it returns _all_ values as a multi-valued field:

> Returns all values in a group as a multivalued field.

However, if 2 or more values are the same, the returned result will only include the value once, instead of having _all_ values.

### Steps to Reproduce

1. Create an index
2. Index some docs, and have a field that you want to use `values` against

```json
POST example-index/_doc
{
  "vc": "vc0001",
  "share": 1
}

POST example-index/_doc
{
  "vc": "vc0002",
  "share": 1
}

POST example-index/_doc
{
  "vc": "vc0003",
  "share": 3,
}
```

3. Run an ES|QL query like:

```
FROM example-index
| STATS shares = VALUES(share)
```

4. Get the response

`shares = [1, 3]`

5. Expected (based on the wording of the docs) to get

`shares = [1, 1, 3]`

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nik9000**
Documents that the VALUES aggregate function returns unique documents and points folks to the TOP aggregate function if they want to keep dupes.

Closes #128091

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
Thanks Nik!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java [hunk 1]
```diff
@@ -72,9 +72,13 @@ public class Values extends AggregateFunction implements ToAggregator {
...
             "version" },
         preview = true,
-        description = "Returns all values in a group as a multivalued field. The order of the returned values isn’t guaranteed. "
-            + "If you need the values returned in order use <<esql-mv_sort>>.",
+        description = """
+            Returns unique values as a multivalued field. The order of the returned values isn’t guaranteed.
+            If you need the values returned in order use <<esql-mv_sort>>.""",
         appendix = """
+            ::::{note}
+            Use <<esql-top>> if you need to keep repeated values.
```
Comment (leemthompo) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java:80]:
```suggestion
            If you need the values returned in order use [`MV_SORT`](/reference/query-languages/esql/functions-operators/mv-functions.md#esql-mv_sort).""",
        appendix = """
            ::::{note}
            Use [`TOP`](/reference/query-languages/esql/functions-operators/aggregation-functions.md#esql-top) if you need to keep repeated values.
```

nit: if this is for 9.x only we should probably eventually get into the habit of using docsv3 rather than asciidoc syntax 

wdyt @craigtaverner?

**Comment by nik9000** [comment]
As those are the only public docs these days I don't think we will
backport. So that's fine.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java [hunk 2]
```diff
@@ -72,9 +72,13 @@ public class Values extends AggregateFunction implements ToAggregator {
             "long",
             "version" },
         preview = true,
-        description = "Returns all values in a group as a multivalued field. The order of the returned values isn’t guaranteed. "
-            + "If you need the values returned in order use <<esql-mv_sort>>.",
+        description = """
+            Returns unique values as a multivalued field. The order of the returned values isn’t guaranteed.
+            If you need the values returned in order use [`MV_SORT`](/reference/query-languages/esql/functions-operators/mv-functions.md#esql-mv_sort).""",
         appendix = """
+            ::::{note}
```
Comment (leemthompo) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Values.java:79]:
```suggestion
            ::::{tip}
```

nit: this is more educational than mandatory so helpful tip might be more appropriate :)
