### PR TITLE
Fix the `max` score mode.

### LINKED ISSUE #24647: "score_mode": "max" is not working for nested Query and function score
**Elasticsearch version**: 5.4.0

**Plugins installed**: [X-Pack]

**JVM version** (`java -version`):java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): macOS Sierra Version 10.12.4 (16E195)

**Description of the problem including expected versus actual behavior**:
The minimum score of the nested document is applied to the parent, although "score_mode": "max" is specified.

**Steps to reproduce**:

Create Index
```
PUT tests
{
  "mappings": {
    "test": {
      "properties": {
        "nestedDoc": {
          "type": "nested"
        }
      }
    }
  }
}
```

Index a test document
```
PUT tests/test/1
{
  "topVal" : 1,
  "nestedDoc": [
    {
      "nestedVal": 2
    },
    {
      "nestedVal": 3
    }
  ]
}
```

Verify the existence of the test document
```
GET tests/_search
```

Do a nested query with function scoring on the nestedVal. The expected score of the parent document should be 3, the maximum. However, 2 is returned. "avg" as score_mode works.
```
GET tests/test/_search
{
  "explain": true, 
  "query": {
    "nested" : {
      "query" : {
        "function_score" : {
          "query" : {
            "match_all": {}
          },
          "functions" : [
            {
              "filter" : {
                "match_all" : {
                  "boost" : 1.0
                }
              },
              "field_value_factor" : {
                "field" : "nestedDoc.nestedVal",
                "factor" : 1.0,
                "missing" : 0.0,
                "modifier" : "none"
              }
            }
          ],
          "score_mode" : "sum",
          "boost_mode" : "replace"
        }
      },
      "path" : "nestedDoc",
      "score_mode" : "max",
      "inner_hits" : {
        "name" : "nestedDoc",
        "ignore_unmapped" : true,
        "from" : 0,
        "size" : 30,
        "version" : false,
        "explain" : true,
        "track_scores" : true,
        "_source" : false
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by jpountz**
This PR backports https://issues.apache.org/jira/browse/LUCENE-7833 to 5.4.

Closes #24647

### CODE REVIEW

File: core/src/main/java/org/apache/lucene/search/XToParentBlockJoinQuery.java [hunk 1]
```diff
@@ -0,0 +1,404 @@
...
+          switch (scoreMode) {
+            case Total:
+            case Avg:
+              score += childScore;
+              break;
+            case Min:
+              score = Math.min(score, childScore);
+              break;
+            case Max:
+              score = Math.max(score, childScore);
```
Comment (martijnvg) [inline core/src/main/java/org/apache/lucene/search/XToParentBlockJoinQuery.java]: Can you add some kind of marking here that this is the only change compared to the class that ships with lucene 6.5?

```
// BEGIN CHANGE
score = Math.max(score, childScore);
// END CHANGE
```

**Review by martijnvg — APPROVED** [review]
Left one comment, other than that LGTM.
