### PR TITLE
token_count type : add enable_position_increments option (fix #23227)

### LINKED ISSUE #23227: token_count type : add an option to count tokens (and not positions)
**Elasticsearch version**: 2.4.2 and 5.2.1

**Description of the problem including expected versus actual behavior**:
Currently, if I have a "token_count" field, based on an analyzer containing a stop filter, the indexed "token_count" field counts stop words. 
It would be great to have an option to only count analysis result tokens.

**Steps to reproduce**:
 1. I have this index configuration :
``` json
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "default": {
            "tokenizer": "standard",
            "filter": [
              "standard",
              "lowercase",
              "stop_words"
            ]
          }
        },
        "filter": {
          "stop_words": {
            "type": "stop",
            "stopwords": [
              "this", "is", "a"
            ]
          }
        }
      }
    }
  },
  "mappings": {
      "properties": {
        "mytext": {
        	"index": "analyzed",
         	"type": "string",
         	"analyzer": "default",
         	"fields": {
         		"length": {
         			"type": "token_count",
         			"analyzer": "default",
         			"store": "yes"
         		}
         	}
        }
      }
    }
  }
}
```
 2. I index this document :
``` json
{
 "mytext": "this is a cat"
}
```
 3. I make this search query :
```
GET _search
{
  "query": {
    "query_string": {
      "query": "mytext.length:1"
    }
  }
}
```
 4. It should return 1 result. But it actually returns 0 result.

### PR DESCRIPTION
**Pull request by fbaligand**
Add option "enable_position_increments" with default value true.
If option is set to false, indexed value is the number of tokens
(not position increments count)

Fix #23227

### CODE REVIEW

**Review by jimczi — CHANGES_REQUESTED** [review]
This looks great, thanks @fbaligand 
I left one comment regarding the meaning of the option. The title of the PR is misleading I think, `enable_position_increments` should not take 0-increment token into account so it's still the number of positions that we are after. We simply don't want to count positions where all tokens have been filtered.

Can you also add a description of the option in the docs:
https://github.com/elastic/elasticsearch/blob/master/docs/reference/mapping/types/token-count.asciidoc

File: core/src/test/java/org/elasticsearch/index/mapper/TokenCountFieldMapperTests.java [hunk 1]
```diff
@@ -102,6 +102,28 @@ public TokenStreamComponents createComponents(String fieldName) {
...
+        Collections.shuffle(Arrays.asList(tokens), random());
+        final TokenStream tokenStream = new CannedTokenStream(finalTokenIncrement, 0, tokens);
+        // TODO: we have no CannedAnalyzer?
+        Analyzer analyzer = new Analyzer() {
+                @Override
+                public TokenStreamComponents createComponents(String fieldName) {
+                    return new TokenStreamComponents(new MockTokenizer(), tokenStream);
+                }
+            };
+        assertThat(TokenCountFieldMapper.countTokens(analyzer, "", ""), equalTo(3));
```
Comment (fbaligand) [inline core/src/test/java/org/elasticsearch/index/mapper/TokenCountFieldMapperTests.java]: Hi @jimczi 
First, thanks for this first review.

Then, concerning your comment : the feature global goal is to have an option to count the number of tokens after analysis, whatever their positions. In that unit test, there are 3 tokens in the stream, so that's why I expect 3 as a result.

Given your comment, maybe the option "enable_position_increments" is misnamed for this feature goal ?

Comment (jimczi) [inline core/src/test/java/org/elasticsearch/index/mapper/TokenCountFieldMapperTests.java]: I think the naming is fine. This feature as described in the issue is about not counting tokens filtered from the token stream. This is what `enable_position_increments=false` does and I think it's all we need to do here. If your analyzer adds alternative tokens to each position they should not alter the final count since we're looking for the number of tokens in the original text.

Comment (fbaligand) [inline core/src/test/java/org/elasticsearch/index/mapper/TokenCountFieldMapperTests.java]: OK, I get what you mean.
That makes sense, especially when you use `synonym` filter.

=> I will fix all your requested changes and push them soon.

**Comment by fbaligand** [comment]
Hi @jimczi 

I fixed your requested changes.

By the way, I fixed also some compilation warnings on TokenCount classes.
If you want that I cancel this commit, tell me.

**Comment by jimczi** [comment]
jenkins please test this

File: docs/reference/mapping/types/token-count.asciidoc [hunk 2]
```diff
@@ -50,9 +50,10 @@ GET my_index/_search
 
 [NOTE]
 ===================================================================
-Technically the `token_count` type sums position increments rather than
+Technically, the `token_count` type sums position increments rather than
 counting tokens. This means that even if the analyzer filters out stop
-words they are included in the count.
+words they are included in the count.  
+If you don't want to count stop words, set option `enable_position_increments` to `false`
```
Comment (jimczi) [inline docs/reference/mapping/types/token-count.asciidoc]: this is redundant with the definition below and it's a little bit confusing since it impacts not only the stop filter ?

**Review by jimczi — APPROVED** [review]
This is ready I think. I left one comment regarding the docs that could clarify the usage. 
This PR is actually tested by our internal CI so I'll merge it if it passes the test.
Thank you very much for your contribution @fbaligand !

File: docs/reference/mapping/types/token-count.asciidoc (hunk 2 above)
Comment (fbaligand) [inline docs/reference/mapping/types/token-count.asciidoc]: You're right.
I see 2 options : 
- remove the note.
- only keep this part to just explain explain the mechanism :

> Technically, the `token_count` type sums position increments rather than counting tokens.

Which do you prefer ?

Moreover, I can add this precision to `enable_position_increments` definition :

> Set to `true` if you want to count all tokens computed by analyzer tokenizer. 

What do you think ?

Comment (jimczi) [inline docs/reference/mapping/types/token-count.asciidoc]: I think you can just remove the note. The definition of the param below is descriptive enough.

Comment (fbaligand) [inline docs/reference/mapping/types/token-count.asciidoc]: So, for enable_position_increments definition, you mean to not add "Set to true if you want to count all tokens computed by analyzer tokenizer" ?

Comment (jimczi) [inline docs/reference/mapping/types/token-count.asciidoc]: Yep the current definition is ok.

**Comment by fbaligand** [comment]
OK. I removed the note, rebased my code on master branch, and pushed it !

**Comment by fbaligand** [comment]
Great !
Thanks @jimczi  for the review, merge into master and inclusion in 5.5.0 release !
It was a pleasure to "work" on this PR with you :)
