### PR TITLE
Fix enforcing that only one recovery gets retried and succeeds

### LINKED ISSUE #91041: [CI] IndexRecoveryWithSnapshotsIT testTransientErrorsDuringRecoveryAreRetried failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/klqfwwxtfujhk/tests/:x-pack:plugin:snapshot-based-recoveries:internalClusterTest/org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.IndexRecoveryWithSnapshotsIT/testTransientErrorsDuringRecoveryAreRetried

**Reproduction line:**
`gradlew ':x-pack:plugin:snapshot-based-recoveries:internalClusterTest' --tests "org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.IndexRecoveryWithSnapshotsIT.testTransientErrorsDuringRecoveryAreRetried" -Dtests.seed=975DA8E689048BA -Dtests.locale=uk -Dtests.timezone=Etc/UTC -Druntime.java=19`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.IndexRecoveryWithSnapshotsIT&tests.test=testTransientErrorsDuringRecoveryAreRetried

**Failure excerpt:**
```
java.lang.AssertionError: timed out waiting for green state

  at __randomizedtesting.SeedInfo.seed([975DA8E689048BA:609F36D1AE96A02E]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:966)
  at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:905)
  at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:894)
  at org.elasticsearch.indices.recovery.AbstractIndexRecoveryIntegTestCase.checkTransientErrorsDuringRecoveryAreRetried(AbstractIndexRecoveryIntegTestCase.java:201)
  at org.elasticsearch.xpack.snapshotbasedrecoveries.recovery.IndexRecoveryWithSnapshotsIT.testTransientErrorsDuringRecoveryAreRetried(IndexRecoveryWithSnapshotsIT.java:26)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

### LINKED ISSUE #91087: [CI] IndexRecoveryIT testTransientErrorsDuringRecoveryAreRetried failing
### CI Link

https://gradle-enterprise.elastic.co/s/bettqvfg5kyos

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testTransientErrorsDuringRecoveryAreRetried" -Dtests.seed=4BDFC31A406EBDF9 -Dtests.locale=ga -Dtests.timezone=America/Atikokan -Druntime.java=19	

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Rome&tests.container=org.elasticsearch.indices.recovery.IndexRecoveryIT&tests.test=testTransientErrorsDuringRecoveryAreRetried

### Failure excerpt

```
java.lang.AssertionError: timed out waiting for green state
```

Call to `ensureGreen()` times out before being able to reach a stable cluster state.

### PR DESCRIPTION
**Pull request by arteam**
~~#90994 fixed the order or arguments in TransientReceiveRejected and it highlighted the fact that `SingleStartEnforcer` had never actually worked. We never recieve `PeerRecoveryTargetService.Actions.FINALIZE`, so `finalizeReceived` was never true. It was set to true only due to mixed arguments order in `TransientReceiveRejected` which yielded the check useless.~~

We have to register an explicit handler for an `PeerRecoveryTargetService.Actions.FINALIZE` event in order to `finalizeReceived` to be set.

Fixes #91087 
Fixes #91041

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update elasticsearch-ci/part-1

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java [hunk 1]
```diff
@@ -160,14 +158,10 @@ protected void checkTransientErrorsDuringRecoveryAreRetried(String recoveryActio
...
 
-        final AtomicBoolean recoveryStarted = new AtomicBoolean(false);
-        final AtomicBoolean finalizeReceived = new AtomicBoolean(false);
-
-        final SingleStartEnforcer validator = new SingleStartEnforcer(indexName, recoveryStarted, finalizeReceived);
-        redTransportService.addSendBehavior(blueTransportService, (connection, requestId, action, request, options) -> {
-            validator.accept(action, request);
-            connection.sendRequest(requestId, action, request, options);
-        });
+        redTransportService.addSendBehavior(
```
Comment (fcofdez) [inline test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java:161]: I don't think this is the right fix, what's happening here is the following:
- We throw/drop the connection during one of the recovery steps 
    - In this case we schedule a retry after the configured retry delay
- Additionally, we drop the connection from the target -> source
    - When this is detected we try to reestablish the recovery, this takes a while
- Concurrently, while we try to reestablish the recovery connection, the original request that failed makes progress
- The recovery ends, removing it from the on going recoveries collection in the source node
- When the target node reaches the source node trying to reestablish the recovery, this is gone
- The behaviour here is to re-start the recovery, hence the second START_RECOVERY message that we see producing the failure
- The issue is that we set the finalizeReceived value in `TransientReceiveRejected` and that's incorrect, since that's configured to be called only when `recoveryActionToBlock` is received. 

I think that the right fix is something like:
```diff
diff --git a/test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java b/test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java
index 02d46839b29..96f1cc70ac5 100644
--- a/test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java
+++ b/test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java
@@ -181,9 +181,12 @@ public abstract class AbstractIndexRecoveryIntegTestCase extends ESIntegTestCase
         TransientReceiveRejected handlingBehavior = new TransientReceiveRejected(
             recoveryActionToBlock,
             recoveryStarted,
-            finalizeReceived,
             connectionBreaker
         );
+        redTransportService.addRequestHandlingBehavior(PeerRecoveryTargetService.Actions.FINALIZE, (handler, request, channel, task) -> {
+            finalizeReceived.set(true);
+            handler.messageReceived(request, channel, task);
+        });
         redTransportService.addRequestHandlingBehavior(recoveryActionToBlock, handlingBehavior);

         try {
@@ -580,19 +583,16 @@ public abstract class AbstractIndexRecoveryIntegTestCase extends ESIntegTestCase

         private final String actionName;
         private final AtomicBoolean recoveryStarted;
-        private final AtomicBoolean finalizeReceived;
         private final Runnable connectionBreaker;
         private final AtomicInteger blocksRemaining;

         private TransientReceiveRejected(
             String actionName,
             AtomicBoolean recoveryStarted,
-            AtomicBoolean finalizeReceived,
             Runnable connectionBreaker
         ) {
             this.actionName = actionName;
             this.recoveryStarted = recoveryStarted;
-            this.finalizeReceived = finalizeReceived;
             this.connectionBreaker = connectionBreaker;
             this.blocksRemaining = new AtomicInteger(randomIntBetween(1, 3));
         }
@@ -605,9 +605,6 @@ public abstract class AbstractIndexRecoveryIntegTestCase extends ESIntegTestCase
             Task task
         ) throws Exception {
             recoveryStarted.set(true);
-            if (actionName.equals(PeerRecoveryTargetService.Actions.FINALIZE)) {
-                finalizeReceived.set(true);
-            }
             if (blocksRemaining.getAndUpdate(i -> i == 0 ? 0 : i - 1) != 0) {
                 String rejected = "rejected";
                 String circuit = "circuit";
```
Maybe we can refine it further and assert that we only see the `START_RECOVERY` message once per recovery id.

**Review by fcofdez — CHANGES_REQUESTED** [review]

File: test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java (hunk 1 above)
Comment (arteam) [reply test/framework/src/main/java/org/elasticsearch/indices/recovery/AbstractIndexRecoveryIntegTestCase.java]: Thank you @fcofdez! I noticed that the `PeerRecoveryTargetService.Actions.FINALIZE` event never happened in the handler  `finalizeReceived` wasn't being set when I was debugging the issue, but I decided to restore the state of things before #90994. Fixing the handler is indeed a much better solution!

**Review by fcofdez — APPROVED** [review]
LGTM 👍 thanks for fixing this!
