### PR TITLE
Make sure listener is resolved when file queue is cleared

### LINKED ISSUE #89927: [CI] DedicatedClusterSnapshotRestoreIT testSnapshotDeleteRelocatingPrimaryIndex failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/4647z2olruffa/tests/:server:internalClusterTest/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT/testSnapshotDeleteRelocatingPrimaryIndex

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotDeleteRelocatingPrimaryIndex" -Dtests.seed=7CB99D2060E62358 -Dtests.locale=ar-KW -Dtests.timezone=ECT -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT&tests.test=testSnapshotDeleteRelocatingPrimaryIndex

**Failure excerpt:**
```
java.util.concurrent.TimeoutException: Timeout waiting for task.

  at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:228)
  at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:53)
  at org.elasticsearch.test.ClusterServiceUtils.awaitClusterState(ClusterServiceUtils.java:226)
  at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitClusterState(AbstractSnapshotIntegTestCase.java:577)
  at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitNoMoreRunningOperations(AbstractSnapshotIntegTestCase.java:560)
  at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitNoMoreRunningOperations(AbstractSnapshotIntegTestCase.java:555)
  at org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotDeleteRelocatingPrimaryIndex(DedicatedClusterSnapshotRestoreIT.java:1140)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

As discussed with @pxsalehi this is a real bug that can lead to aborted or failed shard snapshots never completing due to an oversight in #88209 . This could theoretically also affect other tests around aborting/failing shard snapshots. A fix is known and in-progress.

### LINKED ISSUE #89956: [CI] SharedClusterSnapshotRestoreIT.testDataFileFailureDuringSnapshot failing
### CI Link

https://gradle-enterprise.elastic.co/s/ou2sap2dhy3q2/tests/:server:internalClusterTest/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT/testDataFileFailureDuringSnapshot

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testDataFileFailureDuringSnapshot" -Dtests.seed=37B64CEE1DCEACEB -Dtests.locale=uk -Dtests.timezone=Africa/Lusaka -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
java.lang.Exception: Test abandoned because suite timeout was reached. 
    at __randomizedtesting.SeedInfo.seed([37B64CEE1DCEACEB]:0)
```

### PR DESCRIPTION
**Pull request by pxsalehi**
Handle a bug introduced in https://github.com/elastic/elasticsearch/pull/88209 while refactoring how file upload tasks run in a shard snapshot. The corner case where the queue of files to snapshot gets cleared when a file snapshot runs into an exception is not addressed in that PR.

Closes https://github.com/elastic/elasticsearch/issues/89927 
Closes https://github.com/elastic/elasticsearch/issues/89956

### CODE REVIEW

**Comment by pxsalehi** [comment]
I would like to also somehow refactor that part a bit, and add a test for this corner case. Whether here or in another PR. Since there is a failing test, we might want to merge this.

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 1]
```diff
@@ -393,4 +404,55 @@ private RepositoryData addRandomSnapshotsToRepoData(RepositoryData repoData, boo
...
+        // Generate some FileInfo, as the files that get uploaded as part of the shard snapshot
+        SnapshotShardContext context = ShardSnapshotTaskRunnerTests.dummyContext();
+        int noOfFiles = randomIntBetween(10, 100);
+        BlockingQueue<BlobStoreIndexShardSnapshot.FileInfo> files = new LinkedBlockingQueue<>(noOfFiles);
+        ActionListener<Collection<Void>> allFilesUploadListener = ActionListener.wrap(() -> listenerCalled.set(true));
+        for (int i = 0; i < noOfFiles; i++) {
+            files.add(ShardSnapshotTaskRunnerTests.dummyFileInfo());
+        }
+        repository.snapshotFiles(context, files, allFilesUploadListener);
+        assertBusy(() -> assertTrue(listenerCalled.get()));
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java:446]: I kind of dislike this pattern in tests, it causes test to be needlessly slow in aggregate because of the sleeps in the busy polling from `assertTrue`. Maybe just use a `PlainActionFuture` for the listener above and then wait for its completion here?

**Review by original-brownbear — COMMENTED** [review]
Thanks for fixing this so quickly @pxsalehi ! The fix looks fine, just one complaint about a test detail :)

**Review by original-brownbear — APPROVED** [review]

**Comment by pxsalehi** [comment]
Thanks, Armin!
