### PR TITLE
Bootstrap does not set system properties

### LINKED ISSUE #16579: Elasticsearch does not start as a daemon
Due to the settings refactoring and the magical action-at-a-distance way that some settings like `es.foreground` are set via system properties, Elasticsearch does not currently start as a daemon (and thus as a service) when built from master:

```
$ ~/elasticsearch/elasticsearch-3.0.0-SNAPSHOT/bin/elasticsearch -d
$ Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [foreground]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:227)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:216)
        at org.elasticsearch.common.settings.SettingsModule.configure(SettingsModule.java:60)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:224)
        at org.elasticsearch.node.Node.<init>(Node.java:156)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:294)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:37)
Refer to the log for complete error details.
```

Closes #11564

### PR DESCRIPTION
**Pull request by jasontedor**
Today, certain bootstrap properties are set and read via system
properties. This action-at-distance way of managing these properties is
rather confusing, and completely unnecessary. But another problem exists
with setting these as system properties. Namely, these system properties
are interpreted as Elasticsearch settings, not all of which are
registered. This leads to Elasticsearch failing to startup if any of
these special properties are set. Instead, these properties should be
kept as local as possible, and passed around as method parameters where
needed. This eliminates the action-at-distance way of handling these
properties, and eliminates the need to register these non-setting
properties. This commit does exactly that.

Additionally, today we use the "-D" command line flag to set the
properties, but this is confusing because "-D" is a special flag to the
JVM for setting system properties. This creates confusion because some
"-D" properties should be passed via arguments to the JVM (so via
ES_JAVA_OPTS), and some should be passed as arguments to
Elasticsearch. This commit changes the "-D" flag for Elasticsearch
settings to "-E".

Closes #16579, supersedes #16791

### CODE REVIEW

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterConfiguration.groovy [hunk 1]
```diff
@@ -73,6 +73,8 @@ class ClusterConfiguration {
         return tmpFile.exists()
     }
 
+    Map<String, String> esSettings = new HashMap<>();
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterConfiguration.groovy]: We already have setting below, this seems a duplicate?

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy [hunk 2]
```diff
@@ -129,14 +129,16 @@ class NodeInfo {
             'JAVA_HOME' : project.javaHome,
             'ES_GC_OPTS': config.jvmArgs // we pass these with the undocumented gc opts so the argline can set gc, etc
         ]
-        args.add("-Des.node.portsfile=true")
-        args.addAll(config.systemProperties.collect { key, value -> "-D${key}=${value}" })
+        args.addAll("-E", "es.node.portsfile=true")
+        args.addAll(config.esSettings.collectMany { key, value -> ["-E", "${key}=${value}" ] })
+        env.put('ES_JAVA_OPTS', config.systemProperties.collect { key, value -> "-D${key}=${value}" }.join(" "))
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy]: Can we just use JAVA_OPTS?

File: core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java [hunk 3]
```diff
@@ -218,22 +222,19 @@ static void initLoggerPrefix() {
      * This method is invoked by {@link Elasticsearch#main(String[])}
      * to startup elasticsearch.
      */
-    static void init(String[] args) throws Throwable {
+    static void init(
+            final boolean daemonize,
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: I think we should keep this name `foreground`, since we don't actually daemonize from within java and this setting is all about whether we close streams.

File: core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java [hunk 4]
```diff
@@ -297,6 +298,13 @@ static void init(String[] args) throws Throwable {
         }
     }
 
+    @SuppressForbidden(reason = "Sets system properties passed as CLI parameters")
+    private static void elasticsearchSettings(Map<String, String> esSettings) {
+        for (Map.Entry<String, String> esSetting : esSettings.entrySet()) {
+            System.setProperty(esSetting.getKey(), esSetting.getValue());
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: Why would we do this? I don't believe we do it currently, and I don't think we should be setting any sysprops from within java.

File: core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java [hunk 5]
```diff
@@ -19,23 +19,98 @@
...
-public final class Elasticsearch {
+class Elasticsearch extends Command {
+
+    private final OptionSpec<Void> versionOption;
+    private final OptionSpec<Void> daemonizeOption;
+    private final OptionSpec<String> pathHomeOption;
+    private final OptionSpec<String> pidfileOption;
+    private final OptionSpec<KeyValuePair> propertyOption;
 
     /** no instantiation */
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java]: This javadoc is no longer correct.

File: core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+import java.util.List;
+import java.util.Map;
+import java.util.concurrent.atomic.AtomicBoolean;
+import java.util.function.Consumer;
+
+import static org.hamcrest.CoreMatchers.containsString;
+import static org.hamcrest.CoreMatchers.equalTo;
+import static org.hamcrest.Matchers.hasEntry;
+
+public class ElasticsearchCommandLineParsingTests extends ESTestCase {
```
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java]: nit: this name is quite wordy..I would just call it ElasticsearchCliTests

File: core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+    private void runTest(
+            final int expectedStatus,
+            final boolean expectedInit,
+            final Consumer<String> outputConsumer,
+            final InitConsumer initConsumer,
+            String... args) throws Exception {
+        final MockTerminal terminal = new MockTerminal();
+        try {
+            final AtomicBoolean init = new AtomicBoolean();
+            final int status = Elasticsearch.main(args, new Elasticsearch() {
```
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java]: You could make this tests class extend the existing CommandTestCase, and create this modified Elasticsearch in `newCommand()`

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy [hunk 8]
```diff
@@ -407,6 +407,7 @@ class BuildPlugin implements Plugin<Project> {
             systemProperty 'jna.nosys', 'true'
             // default test sysprop values
             systemProperty 'tests.ifNoTests', 'fail'
+            // TODO: remove setting logging level via system property
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy]: I don't think we can do anything but through a system property. However, we should make it a test specific prop that is read by BootstrapForTesting (which should be initializing logging for tests...I was surprised to see there was no explicit init of logging there...)

File: core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java [hunk 9]
```diff
@@ -19,23 +19,98 @@
...
-    private Elasticsearch() {}
+    Elasticsearch() {
+        super("starts elasticsearch");
+        // TODO: in jopt-simple 5.0, make this mutually exclusive with all other options
+        versionOption = parser.acceptsAll(Arrays.asList("V", "version"),
+            "Prints elasticsearch version information and exits");
+        daemonizeOption = parser.acceptsAll(Arrays.asList("d", "daemonize"),
+            "Starts Elasticsearch in the background");
+        // TODO: in jopt-simple 5.0 this option type can be a Path
+        pathHomeOption = parser.acceptsAll(Arrays.asList("H", "path.home"), "").withRequiredArg();
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java]: I have the same concerned I expressed in the previous PR. This should not be a setting a user ever sees or knows about. It is not something they can simply change.

**Comment by rjernst** [comment]
@jasontedor I left some comments. My largest concern is again about path.home being exposed.

File: docs/reference/migration/migrate_5_0/settings.asciidoc [hunk 10]
```diff
@@ -172,3 +172,18 @@ Two cache concurrency level settings
 `indices.fielddata.cache.concurrency_level` because they no longer apply to
 the cache implementation used for the request cache and the field data cache.
 
+==== Using system properties to configure Elasticsearch
+
+Elasticsearch can be configured by setting system properties on the
+command line via `-Des.name.of.property=value.of.property`. This will be
+removed in a future version of Elasticsearch. Instead, use
+`-E es.name.of.setting=value.of.setting`. Note that in all cases the
```
Comment (pickypg) [inline docs/reference/migration/migrate_5_0/settings.asciidoc]: would the space (` `) work?

File: docs/reference/modules/cluster/allocation_awareness.asciidoc [hunk 11]
```diff
@@ -21,7 +21,7 @@ attribute called `rack_id` -- we could use any attribute name.  For example:
 
 [source,sh]
 ----------------------
-./bin/elasticsearch --node.rack_id rack_one <1>
+./bin/elasticsearch -Ees.node.rack_id=rack_one <1>
```
Comment (pickypg) [inline docs/reference/modules/cluster/allocation_awareness.asciidoc]: Now that it's `-E`, do we actually need to prefix every setting name? It clearly made a ton of sense as a system property, but I feel like it's unnecessary as an Elasticsearch setting (and therefore implied as `es.*`).

Comment (rjernst) [inline docs/reference/modules/cluster/allocation_awareness.asciidoc]: +1 to remove the `es.` prefix handling.

File: core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java (hunk 4 above)
Comment (pickypg) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: I do know that at least the logging API used to modify the system property, although I wholeheartedly agree with your point.

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/logging/Loggers.java#L41

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: @rjernst We do to it today, from the [new bootstrap CLI parser](https://github.com/elastic/elasticsearch/blob/e4bed0c97e7e0acb293624f9601027f8be38c874/core/src/main/java/org/elasticsearch/bootstrap/BootstrapCliParser.java#L87):

```java
        for (String property : propertyOption.values(options)) {
            String[] keyValue = property.split("=", 2);
            if (keyValue.length != 2) {
                throw new UserError(ExitCodes.USAGE, "Malformed elasticsearch setting, must be of the form key=value");
            }
            String key = keyValue[0];
            if (key.startsWith("es.") == false) {
                key = "es." + key;
            }
            System.setProperty(key, keyValue[1]);
        }
```

I *very* much want to get rid of it, but I consider it outside of the scope of this pull request. My [comment](https://github.com/elastic/elasticsearch/pull/16791#issuecomment-188171755) from the original pull request which this pull request supersedes:

> This pull request is complete, but the work here is not. In particular, the eventual end game is to remove the use of setting system properties to get command line arguments from the CLI parser down to the bootstrap process. The pieces are in place for this to be a simple extension of this pull request, but there is a lot of time-consuming tedious work to be done to change all the places where we are setting system properties (tests, docs, etc.). This can be done in a follow-up pull request.

File: core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java (hunk 3 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java]: Sure, I pushed fac0f990fcbea296871ac4e6092502fcb62e09b4.

File: core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java (hunk 5 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java]: Thanks. I pushed 088dea8863339639710431a44cd7f7b15f8e79e8.

File: docs/reference/migration/migrate_5_0/settings.asciidoc (hunk 10 above)
Comment (jasontedor) [inline docs/reference/migration/migrate_5_0/settings.asciidoc]: Yes, and there is a [test](https://github.com/jasontedor/elasticsearch/commit/8a05c2a2bef6b5980df286d885ae732657872d15#diff-179c30a6dc225a58837c95771941fbc1R124) that shows this. :)

File: core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java (hunk 6 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java]: Shortened in d1b85f69ef469812693b26393c1519618793cf2f.

File: core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java (hunk 7 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCommandLineParsingTests.java]: That will not work because the new instance closes over a local variable and a method parameter.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy (hunk 8 above)
Comment (jasontedor) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy]: > I don't think we can do anything but through a system property. However, we should make it a test specific prop that is read by BootstrapForTesting (which should be initializing logging for tests...I was surprised to see there was no explicit init of logging there...)

Me too, but the system property is consumed in `InternalTestCluster`.

File: docs/reference/modules/cluster/allocation_awareness.asciidoc (hunk 11 above)
Comment (clintongormley) [inline docs/reference/modules/cluster/allocation_awareness.asciidoc]: +1

Comment (jasontedor) [inline docs/reference/modules/cluster/allocation_awareness.asciidoc]: I'm fine with that, but I think that removing this should be addressed in the [same followup PR](https://github.com/elastic/elasticsearch/pull/17088/files#r55955307) that removes allowing setting settings via system properties. The reason is because setting settings via system properties *should* continue to require the `es.` prefix. I think the followup should just remove the ability to set settings via system properties, and completely do away with the `es.` prefix handling then.

Comment (pickypg) [inline docs/reference/modules/cluster/allocation_awareness.asciidoc]: Sounds good to me and the effect is both proper and the same.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy (hunk 2 above)
Comment (jasontedor) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy]: `JAVA_OPTS` is not officially supported, it looks like a few projects use it (most notably Tomcat). The [officially-supported environment variable](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html) for this purpose is `JAVA_TOOL_OPTIONS`, but [some issues on Ubuntu break the usage](https://github.com/elastic/elasticsearch/issues/13785) of that so we do not support it. We publicly document `ES_JAVA_OPTS`, and do not publicly document `ES_JAVA_OPTS`. Since we can not use the standard one, do not document `JAVA_OPTS` and it's not really official, I see no reason to break the documented `ES_JAVA_OPTS` here and think that we should just get rid of supporting `JAVA_OPTS`.

Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy]: I'll at least be happier if we just support one instead of many.

Comment (jasontedor) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy]: I opened #17121

File: core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java (hunk 9 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java]: @rjernst I pushed 4ee90db13dc54744a9eb7b5d56df2ea4238014d8.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterConfiguration.groovy (hunk 1 above)
Comment (jasontedor) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterConfiguration.groovy]: Oddly, I think that the `setting` that you refer to is unused, and what is also puzzling is how it exists yet all the properties that I cut over from using `systemProperty` to `esSetting` were not using it. Either way, I pushed 66ba044ec569f76b6e2b03bfe7ba0912c44707df to cut everything over to `setting`. (I note there is a technical difference between the `esSetting` that I added which the added settings on the command line, and the existing `setting` which added the settings to the config file; however, this difference does not matter.)

**Comment by jasontedor** [comment]
> I left some comments. My largest concern is again about path.home being exposed.

@rjernst Thanks for the review. I've responded to all of your comments, and most importantly have removed exposing `path.home`. I think that this is ready for another review round.

**Comment by rjernst** [comment]
Thanks for all the investigation into eg JAVA_OPTS. LGTM.
