### PR TITLE
[ESQL] Fix async logging consistency and severity

### LINKED ISSUE #142374: ESQL: Correctly log errors when storing async results
Relates https://github.com/elastic/elasticsearch/issues/139883.

We were too noisy and generally logged exceptions during storing of async ESQL results as ERROR. This is getting downgraded to WARN in https://github.com/elastic/elasticsearch/pull/142112.

However, the noise mostly comes from CBEs and rejected store requests because the result sets were too big. These are fine to log as WARN, but now we do not log genuine bugs (e.g. IllegalStateException) as ERROR; this is, however, required to ensure good alerting for bugs in async queries, esp. in Serverless.

We should probably do the same as #140905 and distinguish between exceptions based on their status:
- log 5xx exceptions as ERROR
- log other exceptions as WARN

### PR DESCRIPTION
**Pull request by MattAlp**
## Summary
- Ensure async ESQL requests log post-timeout failures and partial failures through the same status-aware paths used by synchronous request handling.
- Classify async result-store failures by status so 5xx/internal failures are logged at ERROR while expected/non-server failures remain WARN (with DocumentMissing and VersionConflict still suppressed).
- Add focused tests for timeout callback invocation and failure status classification to guard this behavior.

## Related
- Depends on #142330
- Closes #142316
- Closes #142374

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/operator/DriverTests.java [hunk 1]
```diff
@@ -247,6 +255,59 @@ public void testUnchangedStatus() {
...
+            IllegalArgumentException.class,
+            Level.DEBUG,
+            "*User error running driver [test-task]*"
+        );
+        assertFailureLogged(
+            new CircuitBreakingException("too many bytes", CircuitBreaker.Durability.PERMANENT),
+            CircuitBreakingException.class,
+            Level.DEBUG,
+            "*User error running driver [test-task]*"
+        );
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/operator/DriverTests.java]: NIT: above scenarios could be simplified with:
```
for (var exception: List.of(....)) {
        assertFailureLogged(
            exception,
            exception.getClass(),
            Level.DEBUG,
            "*User error running driver [test-task]*"
        );
}
```

**Review by idegtiarenko — APPROVED** [review]
