### PR TITLE
Fix "key_as_string" for date histogram and epoch_millis/epoch_second format with time zone

### LINKED ISSUE #19038: Incorrect 'key_as_string' response in date_histogram when using 'epoch_millis'  and 'time_zone'
When doing a `date_histogram` aggregation with `"format":"epoch_millis"`, the aggregation response key shows the correct value as UTC time stamp, but the `key_as_string` does not reflect that key if a `time_zone` other than UTC is used. Reproduced on 2.3 and master:

```
PUT /foo

PUT /foo/_mapping/bar
{
  "properties":{
    "timestamp":{
      "type":"date",
      "format":"epoch_millis"
    }
  }
}

POST /foo/bar/1
{
  "timestamp": 1463875200000
}

POST /foo/bar/_search
{
  "aggs": {
    "ts": {
      "date_histogram": {
        "field": "timestamp",
        "interval": "month",
        "time_zone": "+01:00"
      }
    }
  }
}
```
The aggregation in the response:
```
"aggregations": {
    "ts": {
      "buckets": [
        {
          "key_as_string": "1462060800000",
          "key": 1462057200000,
          "doc_count": 1
        }
      ]
    }
  }
```
The key correctly represents the date `2016-05-01T00:00:00.000+01:00`, the expectation would for `epoch_millis` format that the `key_as_string` is the same value.
Same problem happens for `epoch_second` format. With other formats like `date_optional_time` or custom formats `key_as_string` changes correctly according to the keys value.

### PR DESCRIPTION
**Pull request by cbuescher**
When doing a `date_histogram` aggregation with `"format":"epoch_millis"` or `"format" : "epoch_second"` and using a time zone other than UTC, the `key_as_string` ouput in the response does not reflect the UTC timestamp that is used as the key. This happens because when applying the `time_zone` in DocValueFormat.DateTime to an epoch-based formatter, this adds the time zone offset to the value being formated. Instead we should adjust the added display offset to get back the utc instance in EpochTimePrinter.

Closes #19038

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/DocValueFormat.java [hunk 1]
```diff
@@ -124,14 +126,20 @@ public BytesRef parseBytesRef(String value) {
...
         private final DateMathParser parser;
+        private final DateTimeFormatter formatter;
 
         public DateTime(FormatDateTimeFormatter formatter, DateTimeZone timeZone) {
-            this.formatter = Objects.requireNonNull(formatter);
+            this.format = Objects.requireNonNull(formatter.format());
             this.timeZone = Objects.requireNonNull(timeZone);
             this.parser = new DateMathParser(formatter);
+            if (formatter.format().startsWith("epoch_millis") || formatter.format().startsWith("epoch_second")) {
+                this.formatter = formatter.printer();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/DocValueFormat.java]: do we really need a special case here or could we fix the printer impl for these formats to apply the timezone when printing a date?

Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/DocValueFormat.java]: I looked into this some more. It's problematic, the actual joda EpochPrinter prints whatever time instant (long) is given to it, the time zone adjustment happens in joda DateTimeFormatter.printTo(Appendable, long, Chronology), and if we use `withZone()` (which we need for other formatters to work correct) the time zone offset gets added. I don't see another way around this atm. but am open to suggestions where to dig further if you have ideas.

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/DocValueFormat.java]: I'm wondering that this might be something that should be fixed upstream?

Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/DocValueFormat.java]: Sorry, I was mistaken when I thought EpochTimePrinter is part of Joda, its in our code base and we can fix the problem there. I will rebase and update this PR.

**Comment by cbuescher** [comment]
@jpountz sorry for the confusion about EpochTimePrinter, this is actually part of our codebase and we can correct the time zone adjustment directly there. I'm not completely sure if `epoch_millis` format is supposed to always output the date instance in UTC, maybe @spinscale can conform this since it look like he was the one that introduced the printer class.

**Comment by spinscale** [comment]
yes, epoch time is considered the seconds elapsed since 1970 in UTC timezone.

**Comment by jpountz** [comment]
+1 to always UTC

File: core/src/main/java/org/elasticsearch/common/joda/Joda.java [hunk 2]
```diff
@@ -378,18 +377,18 @@ public int estimatePrintedLength() {
         @Override
         public void printTo(StringBuffer buf, long instant, Chronology chrono, int displayOffset, DateTimeZone displayZone, Locale locale) {
             if (hasMilliSecondPrecision) {
-                buf.append(instant);
+                buf.append(instant - displayOffset);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/joda/Joda.java]: maybe leave a comment where this comes from?

**Comment by jpountz** [comment]
LGTM

**Comment by cbuescher** [comment]
Merged to 2.4 with 5301ee30
