### PR TITLE
Handle Concurrent Repo Modification to Fix Test

### LINKED ISSUE #47384: JvmErgonomicsTests.testExtractValidHeapSizeNoOptionPresent fails on 7.4
It fails with:

```
org.elasticsearch.tools.launchers.JvmErgonomicsTests > testExtractValidHeapSizeNoOptionPresent FAILED
    java.lang.AssertionError: 
    Expected: a value greater than <0L>
         but: <0L> was equal to <0L>
        at __randomizedtesting.SeedInfo.seed([22C99F519C4644E0:535C63ED1A8DEF9E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.tools.launchers.JvmErgonomicsTests.testExtractValidHeapSizeNoOptionPresent(JvmErgonomicsTests.java:59)
```

What's strange is that this did not print any reproduction line, so I wasn't able to try the exact test.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.4+multijob-windows-compatibility/os=windows-2019/64/consoleFull
https://gradle-enterprise.elastic.co/s/mm3dqwj56d4aa/console-log

### LINKED ISSUE #47834: [CI] SLMSnapshotBlockingIntegTests.testRetentionWhileSnapshotInProgress failing
`org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testRetentionWhileSnapshotInProgress` has started failing pretty often now with the following error:

```
java.lang.AssertionError: expected at least one master-eligible node left in {node_sc1=org.elasticsearch.test.InternalTestCluster$NodeAndClient@6e458321}
```

Here are some example build scans:
https://gradle-enterprise.elastic.co/s/hlldgfw3cx4bc/tests/rfsroxnx4sflo-uvkkyo6qd6mno
https://gradle-enterprise.elastic.co/s/i4ncjbmiflt6a/tests/rfsroxnx4sflo-uvkkyo6qd6mno
https://gradle-enterprise.elastic.co/s/33mp5rqowzsbi/tests/rfsroxnx4sflo-uvkkyo6qd6mno

Looking at [build-stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'test:%20%22testRetentionWhileSnapshotInProgress%22'),sort:!(time,desc))) this looks to be happening in both `master` and `7.x`.

### PR DESCRIPTION
**Pull request by original-brownbear**
Just like #48329 (and using the changes) in that PR
we can run into a concurrent repo modification that we
will throw on and must retry until consistent handling of
this situation is implemented.

Closes #47834

### CODE REVIEW

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SLMSnapshotBlockingIntegTests.java [hunk 1]
```diff
@@ -215,6 +215,10 @@ public void testRetentionWhileSnapshotInProgress() throws Exception {
                     SnapshotsStatusResponse s =
                         client().admin().cluster().prepareSnapshotStatus(REPO).setSnapshots(completedSnapshotName).get();
                     assertNull("expected no snapshot but one was returned", s.getSnapshots().get(0));
+                } catch (RepositoryException e) {
+                    // Concurrent status calls and write operations may lead to failures in determining the current repository generation
+                    // TODO: Remove this hack once tracking the current repository generation has been made consistent
```
Comment (gwbrown) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SLMSnapshotBlockingIntegTests.java]: Is there an issue we could link to here so that we have something we can reference to see if it's safe to remove the hack?

Comment (original-brownbear) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SLMSnapshotBlockingIntegTests.java]: Not yet I'm afraid. We have https://github.com/elastic/elasticsearch/issues/38941 but the fix to the corruption issue may not fully resolve this situation yet.

Not even sure we have to solve this one with any kind of priority outside of tests:

What's basically happening here is that the snapshot status API breaks for a tiny window during snapshot delete and create (in practice that window will be a little more thanthe latency of one API request). Maybe this is even an ok long term solution? (I'll gather some feedback on that tomorrow and will create an issue accordingly :))

**Review by tlrx — APPROVED** [review]

**Comment by tlrx** [comment]
> Closes #47384

Is that really the issue you want to close?

**Comment by original-brownbear** [comment]
@tlrx thanks for taking a look and spotting that! Obviously mixed up the last two numbers there and want to close #47834 instead :)

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SLMSnapshotBlockingIntegTests.java (hunk 1 above)
Comment (original-brownbear) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SLMSnapshotBlockingIntegTests.java]: We discussed this today during snapshot resiliency sync and I'll code up a fix for this shortly and will remove the todos :)

**Comment by gwbrown** [comment]
@original-brownbear This test was muted in https://github.com/elastic/elasticsearch/issues/48441, when you do the backports for this fix, can you verify that you unmute the test in other branches if necessary? (I'll take care of unmuting in master).

**Comment by ywelsch** [comment]
Was this ever backported?

**Comment by original-brownbear** [comment]
Yea my bad for not linking things properly this change was pulled into 7.6 by Gordon in 5021410165b77af60881df380a1e694738475bc6
