### PR TITLE
Source filtering should treat dots in field names as sub objects.

### LINKED ISSUE #20719: Source Filtering does not Expose Field Names with Dots
**Elasticsearch version**: 5.0.0-beta1

**Plugins installed**: []

**JVM version**: 1.8.0_91

**Description of the problem including expected versus actual behavior**:
In certain cases of using source filtering on field names that contain dots, results that are inconsistent can be returned. My understanding of the source filtering is that it is strictly a filter that is applied over the source document as is.

**Steps to reproduce**:
 1. Insert a document with a dotted field name and a field that is a regular object:
   * `curl -XPUT localhost:9200/dots/test/1 -d '{"a.b":0,"c":1,"d":{"e":2}}'`
 2. Execute a match all query and request each field explicitly from the source filter:
   * `curl -XPOST 'localhost:9200/dots/test/_search?_source=a,c,d'`
 1. Notice that the response does not include the "a.b" field:
   * `"hits" : [
      {
        "_index" : "dots",
        "_type" : "test",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "c" : 1,
          "d" : {
            "e" : 2
          }
        }
      }
    ]`
 3. Execute a match all query and request the `a` field using a wild card:
   * `curl -XPOST 'localhost:9200/dots/test/_search?_source=a.*,c,d'`
 1. Notice that the response includes the "a.b" field now:
   1. `"hits" : [
      {
        "_index" : "dots",
        "_type" : "test",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "c" : 1,
          "a.b" : 0,
          "d" : {
            "e" : 2
          }
        }
      }
    ]`

Worth Mentioning:
 1. If you insert another document into the index that contains `a.b` as a json object, the fields from that document come back in source filtered queries:
   1. `curl -XPUT localhost:9200/dots/test/2 -d '{"a":{"b":5}}'`
 1. `curl -XPOST 'localhost:9200/dots/test/_search?_source=a,c,d&pretty'`
   1. `"hits" : [
      {
        "_index" : "dots",
        "_type" : "test",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "c" : 1,
          "d" : {
            "e" : 2
          }
        }
      },
      {
        "_index" : "dots",
        "_type" : "test",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "a" : {
            "b" : 5
          }
        }
      }
    ]`

**Describe the feature**:
My understanding is that the source filter works only on the raw source field. In the above case the field `a` does not exist in the original document, only the field `a.b`. Since `"a.b" != "a"` the field is ignored. The discussion that I want to whip up about this is whether or not the source filter logic should be consistent with the rest of Elasticsearch in how it handles parsing of dotted field names before checking if they match a source filter.

Edit: Removed a bogus reproduction step.

### PR DESCRIPTION
**Pull request by jpountz**
Mappings treat dots in field names as sub objects, for instance

```
{
  "a.b": "c"
}
```

generates the same dynamic mappings as

```
{
  "a": {
    "b": "c"
  }
}
```

Source filtering should be consistent with this behaviour so that an include
list containing `a` should include fields whose name is `a.b`.

To make this change easier, source filtering was refactored to use automata.
The ability to treat dots in field names as sub objects is provided by the
`makeMatchDotsInFieldNames` method of `XContentMapValues`.

Closes #20719

### CODE REVIEW

**Comment by jbaiera** [comment]
+1 LGTM, Thanks @jpountz

**Comment by jpountz** [comment]
@mikemccand would you ming having a quick look at the usage of the Automaton API before it gets merged?

**Comment by nik9000** [comment]
If Mike doesn't get to it i can look again in the morning. I looked earlier
at it and didn't have any strong thoughts though.

File: core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java [hunk 1]
```diff
@@ -551,4 +551,25 @@ public void testNestedMapInList() throws IOException {
...
+        Map<String, Object> filtered = XContentMapValues.filter(map, new String[] {"a"}, new String[0]);
+        Map<String, Object> expected = new HashMap<>(map);
+        expected.remove("d");
+        assertEquals(expected, filtered);
+
+        // dots in field names in excludes
+        filtered = XContentMapValues.filter(map, new String[0], new String[] {"a"});
+        expected = new HashMap<>(map);
+        expected.keySet().retainAll(Collections.singleton("d"));
+        assertEquals(expected, filtered);
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java]: Could you add a test with strings longer than one char? Sadly, you probably also want on that has a character that is two java `char` wide as well. I'd be good to assert everything works right when you fail half way through the word - say you try and match `cat` against the pattern `cbs`. The `c` works, the `a` would put you in the `-1` state, etc.

**Review by nik9000 — CHANGES_REQUESTED** [review]

**Comment by jpountz** [comment]
@nik9000 I pushed more tests as requested.

**Review by nik9000 — APPROVED** [review]
LGTM. I was worried about the contract of step. I figured you'd got it right but that didn't leave any defense against it changing out from under us.

File: core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java [hunk 2]
```diff
@@ -134,115 +139,171 @@ private static Object extractValue(String[] pathElements, int index, Object curr
...
+            excludeA = Regex.simpleMatchToAutomaton(excludes);
+            excludeA = makeMatchDotsInFieldNames(excludeA);
+        }
+        CharacterRunAutomaton exclude = new CharacterRunAutomaton(excludeA);
+
+        // NOTE: We cannot use Operations.minus because of the special case that
+        // we want all sub properties to match as soon as an object matches
+
+        return filter(map,
+                include, include.getInitialState(),
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java]: The initial state is always 0 w/ Lucene's automata ... I'll fix Lucene to make this clearer :)

File: core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java [hunk 3]
```diff
@@ -134,115 +139,171 @@ private static Object extractValue(String[] pathElements, int index, Object curr
...
+        if (excludes == null || excludes.length == 0) {
+            excludeA = Automata.makeEmpty();
+        } else {
+            excludeA = Regex.simpleMatchToAutomaton(excludes);
+            excludeA = makeMatchDotsInFieldNames(excludeA);
+        }
+        CharacterRunAutomaton exclude = new CharacterRunAutomaton(excludeA);
+
+        // NOTE: We cannot use Operations.minus because of the special case that
+        // we want all sub properties to match as soon as an object matches
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java]: I wonder if you could use `Operations.minus`, but then union that result with another automaton that accepts any string matched by the include automaton followed by `.` (literal) followed by any suffix?  Then a single automaton could do all the matching I think?

File: core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java [hunk 4]
```diff
@@ -134,115 +139,171 @@ private static Object extractValue(String[] pathElements, int index, Object curr
...
+     *
+     * If an object matches, then any of its sub properties are automatically
+     * considered as matching as well, both for includes and excludes.
+     *
+     * Dots in field names are treated as sub objects. So for instance if a
+     * document contains {@code a.b} as a property and {@code a} is an include,
+     * then {@code a.b} will be kept in the filtered map.
+     */
+    public static Map<String, Object> filter(Map<String, ?> map, String[] includes, String[] excludes) {
+        CharacterRunAutomaton matchAllAutomaton = new CharacterRunAutomaton(Automata.makeAnyString());
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java]: Isn't this invoked once per returned hit?  We should maybe (separate change) compile the automaton/a up front, and re-use that across all the hits?

**Review by mikemccand — COMMENTED** [review]
Woops, sorry I missed my calling here ;)

I left a few small comments.
