### PR TITLE
Check and repair index under the store metadata lock

### LINKED ISSUE #24481: [TEST] CorruptedFileIT.testReplicaCorruption
This test sometimes fails in 5.x and 5.4 but the failure does not reproduce locally:

````
gradle :core:integTest -Dtests.seed=EB43781CD72967EA -Dtests.class=org.elasticsearch.index.store.CorruptedFileIT -Dtests.method="testReplicaCorruption" -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=America/Indianapolis
````

Build output:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-darwin-compatibility/461/consoleFull
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-darwin-compatibility/410/consoleFull

It seems that the recovery is blocked if the `segment_*` file is corrupted:

````
1> Caused by: java.io.EOFException: read past EOF: MMapIndexInput(path="/private/var/lib/jenkins/workspace/elastic+elasticsearch+5.x+multijob-darwin-compatibility/core/build/testrun/integTest/J2/temp/org.elasticsearch.index.store.CorruptedFileIT_D04C89BC1BDC6CB3-001/tempDir-002/data/nodes/4/indices/djB78NKbThaDzb0A0xah6A/1/index/segments_2")
  1> 	at org.apache.lucene.store.ByteBufferIndexInput.readByte(ByteBufferIndexInput.java:75) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.store.MockIndexInputWrapper.readByte(MockIndexInputWrapper.java:140) ~[lucene-test-framework-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.store.DataInput.readInt(DataInput.java:101) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:300) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:288) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:448) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:445) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:692) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:644) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:450) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:129) ~[main/:?]
  1> 	at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:198) ~[main/:?]
  1> 	at org.elasticsearch.index.store.Store.access$200(Store.java:126) ~[main/:?]
  1> 	at org.elasticsearch.index.store.Store$MetadataSnapshot.loadMetadata(Store.java:785) ~[main/:?]
  1> 	at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:718) ~[main/:?]
  1> 	at org.elasticsearch.index.store.Store.getMetadata(Store.java:240) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.IndexShard.snapshotStoreMetadata(IndexShard.java:874) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:183) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:73) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:555) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1> 	... 3 more
````

... and after some time the test fails on a timeout:

`````
FAILURE 33.7s J2 | CorruptedFileIT.testReplicaCorruption <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: timed out waiting for green state
   > 	at __randomizedtesting.SeedInfo.seed([EB43781CD72967EA:74122634059C0417]:0)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:932)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:898)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:887)
   > 	at org.elasticsearch.index.store.CorruptedFileIT.testReplicaCorruption(CorruptedFileIT.java:590)
   > 	at java.lang.Thread.run(Thread.java:745)
````

### LINKED ISSUE #27731: [CI] MasterDisruptionIT.testVerifyApiBlocksDuringPartition fails in checkIndex
MasterDisruptionIT.testVerifyApiBlocksDuringPartition failed on the 6.x branch on macOS: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/398/console

This doesn't reproduce locally for me with:

```
gradle :core:integTest \
  -Dtests.seed=46C91E745D178048 \
  -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT \
  -Dtests.method="testVerifyApiBlocksDuringPartition" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-CA \
  -Dtests.timezone=America/Swift_Current
```

It actually failed after the test in the cleanup checks of `ESTestCase`:

```
10:41:51 FAILURE 22.9s J2 | MasterDisruptionIT.testVerifyApiBlocksDuringPartition <<< FAILURES!
10:41:51    > Throwable #1: java.lang.AssertionError: at least one shard failed CheckIndex
10:41:51    > 	at __randomizedtesting.SeedInfo.seed([46C91E745D178048:A671712025C4F3C2]:0)
10:41:51    > 	at org.elasticsearch.test.ESTestCase.ensureCheckIndexPassed(ESTestCase.java:434)
10:41:51    > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:301)
10:41:51    > 	at java.lang.Thread.run(Thread.java:748)
```

This implies `MockFSDirectoryService`'s index check failed, and this is the exception that caused that:

```
10:41:49   1> [2017-12-08T04:40:46,912][WARN ][o.e.t.s.MockFSIndexStore$Listener] [node_t1] [test][0] failed to check index
10:41:49   1> java.lang.IllegalStateException: IndexWriter is still open on shard [test][0]
10:41:49   1> 	at org.elasticsearch.test.store.MockFSDirectoryService.checkIndex(MockFSDirectoryService.java:141) ~[framework-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
10:41:49   1> 	at org.elasticsearch.test.store.MockFSIndexStore$Listener.afterIndexShardClosed(MockFSIndexStore.java:99) ~[framework-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
10:41:49   1> 	at org.elasticsearch.index.CompositeIndexEventListener.afterIndexShardClosed(CompositeIndexEventListener.java:111) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.index.IndexService.closeShard(IndexService.java:439) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.index.IndexService.removeShard(IndexService.java:414) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.index.IndexService.close(IndexService.java:274) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:552) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.removeUnallocatedIndices(IndicesClusterStateService.java:366) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:221) ~[main/:?]
10:41:49   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:498) ~[main/:?]
10:41:49   1> 	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_141]
10:41:49   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:495) [main/:?]
10:41:49   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:482) [main/:?]
10:41:49   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:432) [main/:?]
10:41:49   1> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:161) [main/:?]
10:41:49   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566) [main/:?]
10:41:49   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [main/:?]
10:41:49   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [main/:?]
10:41:49   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
10:41:49   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
10:41:49   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
10:41:49   1> Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/core/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.MasterDisruptionIT_46C91E745D178048-001/tempDir-003/data/nodes/1/indices/gXmY0hObRUS-fnf_uDDP0w/0/index/write.lock
10:41:49   1> 	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:139) ~[lucene-core-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.apache.lucene.store.MockDirectoryWrapper.obtainLock(MockDirectoryWrapper.java:1049) ~[lucene-test-framework-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.apache.lucene.index.CheckIndex.<init>(CheckIndex.java:403) ~[lucene-core-7.2.0-snapshot-7deca62.jar:7.2.0-snapshot-7deca62 7deca62501ec7484ea54d292fe0131c78384e95f - jpountz - 2017-12-01 12:38:44]
10:41:49   1> 	at org.elasticsearch.test.store.MockFSDirectoryService.checkIndex(MockFSDirectoryService.java:122) ~[framework-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
10:41:49   1> 	... 20 more
```

### PR DESCRIPTION
**Pull request by dnhatn**
Today when we get a metadata snapshot directly from a store directory, we acquire a metadata lock, then acquire an IndexWriter lock. However, we create a CheckIndex in IndexShard without acquiring the metadata lock first. This causes a recovery failed because the IndexWriter lock can be still held by method `snapshotStoreMetadata`. This commit makes sure to create a `CheckIndex` under the metadata lock.

Closes #24481
Closes #27731
Relates #24787

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -1930,31 +1929,33 @@ private void doCheckIndex() throws IOException {
...
-                if (!status.clean) {
-                    if (state == IndexShardState.CLOSED) {
-                        // ignore if closed....
-                        return;
-                    }
-                    logger.warn("check index [failure]\n{}", os.bytes().utf8ToString());
-                    if ("fix".equals(checkIndexOnStartup)) {
-                        if (logger.isDebugEnabled()) {
-                            logger.debug("fixing index, writing new segments file ...");
+            store.runUnderMetadataLock(() -> {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: instead of adding this `runUnderMetadataLock` method would it make sense to just move the checkindex method into store like this `public CheckIndex.Status checkIndex()` then we can interpret the result here and run under the appropriate locks.

**Review by s1monw — CHANGES_REQUESTED** [review]
I left one comment LGTM otherwise

**Comment by dnhatn** [comment]
@s1monw I've moved `checkIndex` and `exorciseIndex` methods the Store class. Could you please take another look? Thank you.

**Comment by dnhatn** [comment]
@elasticmachine please retest this.

File: core/src/main/java/org/elasticsearch/index/store/Store.java [hunk 2]
```diff
@@ -344,6 +346,45 @@ public int compare(Map.Entry<String, String> o1, Map.Entry<String, String> o2) {
...
     }
 
+    /**
+     * Checks and returns the status of the existing index in this store.
+     *
+     * @param out where infoStream messages should go. See {@link CheckIndex#setInfoStream(PrintStream)}
+     */
+    public CheckIndex.Status checkIndex(PrintStream out) throws IOException {
+        // We don't need to lock the directory here as we are not changing the index files.
+        final Lock noDirectoryLock = new Lock() {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/store/Store.java]: I wonder if we should still acquire the lock. I don't think we should execute this while the IW is open?

**Review by s1monw — CHANGES_REQUESTED** [review]
I left one comment. LGTM otherwise

File: core/src/main/java/org/elasticsearch/index/store/Store.java (hunk 2 above)
Comment (dnhatn) [reply core/src/main/java/org/elasticsearch/index/store/Store.java]: I pushed https://github.com/elastic/elasticsearch/pull/27768/commits/f231042ffd970b99fa0037ad3e5a6ce1c181674b

**Comment by dnhatn** [comment]
please retest this.

**Comment by dnhatn** [comment]
@s1monw, I've moved the `checkIndex` under the metadata lock; would you please take a look? Thank you.

**Review by s1monw — APPROVED** [review]
LGTM is this also fixing https://github.com/elastic/elasticsearch/issues/27731 ?

**Comment by dnhatn** [comment]
@s1monw, I've removed the direct usages of `CheckIndex` in `MockFSDirectoryService` and in another test. This should also fix #27731.

**Comment by dnhatn** [comment]
Thanks @s1monw for reviewing.
