### PR TITLE
Fix legacy GeoPointField decoding in FieldStats

### LINKED ISSUE #24275: _field_stats call on geo_point field broken after upgrading from 2.4.4 -> 5.3.1
**Elasticsearch version**: 2.4.4/5.3.1

A `_field_stats` call on a type `geo_point` field throws an exception for an index that was created in `2.4.4` and upgraded to `5.3.1`. I also reproduced this on going from `2.3.3` -> `5.3.0`.

This causes Kibana to not properly grab the index mappings when defining an index pattern rendering all fields as neither searchable nor aggregatable. 

**Steps to reproduce**:
1. Create an index mapping with a geo_point field

```
PUT index
{
  "mappings": {
    "type": {
      "properties": {
        "geo_field": {
          "type": "geo_point"
        }
      }
    }
  }
}
```

2. Add a sample document

```
PUT index/type/1
{
  "geo_field": "33.8957, -112.0577"
}
```

3. Upgrade to 5.3.1 (I simply copied the data directory over)

4. Attempt a `_field_stats` call on the geo_field

```
GET index/_field_stats?fields=geo_field
```
The response

```
{
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 3,
        "index": "index",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "exception",
          "reason": "java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 5",
          "caused_by": {
            "type": "execution_exception",
            "reason": "java.lang.ArrayIndexOutOfBoundsException: 5",
            "caused_by": {
              "type": "array_index_out_of_bounds_exception",
              "reason": "5"
            }
          }
        }
      }
    ]
  },
  "indices": {
    "_all": {
      "fields": {}
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nknize**
`LegacyGeoPointField` was using the wrong decoding for min/max prefix coded GeoPoint Terms. This PR applies the correct decoding. Note that the min/max values, though, are likely useless anyway since they map to a low resolution morton encoded version of the point; not something that is really of value for field stats.

closes #24275

### CODE REVIEW

**Comment by jpountz** [comment]
Can you add a test?

**Comment by jimczi** [comment]
@nknize if adding a test is not possible you can also remove the field stats impl for legacy point ? This is not needed and we don't want to fail a request for an encoding problem.

**Comment by nknize** [comment]
Thx @jpountz and @jimczi  I added a simple test that simply ensures the request doesn't fail.

File: core/src/test/java/org/elasticsearch/fieldstats/FieldStatsTests.java [hunk 1]
```diff
@@ -676,6 +687,27 @@ public static FieldStats randomFieldStats(boolean withNullMinMax) throws Unknown
         }
     }
 
+    public void testGeo() {
+        Version version = VersionUtils.randomVersionBetween(random(), Version.V_2_0_0, Version.CURRENT);
```
Comment (jimczi) [inline core/src/test/java/org/elasticsearch/fieldstats/FieldStatsTests.java]: Can we test more than one version at a time ? At least one of v2 and one of v5.

**Review by jimczi — APPROVED** [review]
LGTM
