### PR TITLE
Use legacy backing index names for data streams in mixed clusters

### LINKED ISSUE #66370: Data stream backing index naming bwc bug
If a data stream is created or a rollover happens while the cluster is upgrading from 7.10.1 (or earlier) to 7.11 (or later) then node may fail to accept the cluster state while the cluster consist of nodes of mixed versions.

This is because #65205 introduced a change in the naming of backing indices for data streams and validation of the name of backing indices was relaxed via #65791 (released as part of 7.10.2). These two changes combined can cause this bug.

The fix would be to use the old naming scheme until the minimum node version in the entire cluster is 7.11 or later.

This issue was discovered in CI. 
- https://gradle-enterprise.elastic.co/s/lirh33mwyici2

(not tied to a specific test)

An example of the actual failure in CI:

```
fatal error in thread [elasticsearch[v7.10.2-2][generic][T#7]], exiting
java.lang.AssertionError
	at org.elasticsearch.cluster.metadata.DataStream.<init>(DataStream.java:55)
	at org.elasticsearch.cluster.metadata.DataStream.<init>(DataStream.java:145)
	at org.elasticsearch.cluster.DiffableUtils$DiffableValueReader.read(DiffableUtils.java:688)
	at org.elasticsearch.cluster.DiffableUtils$DiffableValueReader.read(DiffableUtils.java:677)
```

(non-issue, because the #65205 hasn't been released yet)

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #66370

### CODE REVIEW

**Review by probakowski — APPROVED** [review]
LGTM, thanks @danhermann

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java [hunk 1]
```diff
@@ -190,7 +190,11 @@ public DataStream promoteDataStream() {
      * @return backing index name
      */
     public static String getDefaultBackingIndexName(String dataStreamName, long generation) {
-        return getDefaultBackingIndexName(dataStreamName, generation, System.currentTimeMillis());
+        return getDefaultBackingIndexName(dataStreamName, generation, System.currentTimeMillis(), NEW_FEATURES_VERSION);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java:193]: nit: maybe use `Version.CURRENT` instead of `NEW_FEATURES_VERSION`?
The outcome is the same, but in other places we do the same.

File: server/src/test/java/org/elasticsearch/cluster/metadata/DataStreamTests.java [hunk 2]
```diff
@@ -54,7 +54,7 @@ protected DataStream createTestInstance() {
     public void testRollover() {
         DataStream ds = DataStreamTestHelper.randomInstance().promoteDataStream();
         Index newWriteIndex = new Index(getDefaultBackingIndexName(ds.getName(), ds.getGeneration() + 1), UUIDs.randomBase64UUID(random()));
-        DataStream rolledDs = ds.rollover(newWriteIndex);
+        DataStream rolledDs = ds.rollover(newWriteIndex, DataStream.NEW_FEATURES_VERSION);
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/cluster/metadata/DataStreamTests.java:57]: maybe also add a test here with a version before 7.11?

**Review by martijnvg — APPROVED** [review]
👍 LGTM

I think the bwc tests can also enabled in this pr?

File: server/src/test/java/org/elasticsearch/cluster/metadata/DataStreamTests.java (hunk 2 above)
Comment (martijnvg) [reply server/src/test/java/org/elasticsearch/cluster/metadata/DataStreamTests.java:57]: and maybe also a test to `MetadataCreateDataStreamServiceTests` that tests creating a data stream when minimum node version is before 7.11?

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
cc: @henningandersen on the change to `ReactiveStorageDeciderService` here:

https://github.com/elastic/elasticsearch/pull/66400/files#diff-4295fc3ce1dcb006cead63e125db2910d0c53cecf7ed2e184e4dc07bd569385aR452

I believe it's fairly trivial and can be removed after the next minor release since it is needed only in mixed clusters to accommodate the change in the naming scheme for data stream backing indices.

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2
