### PR TITLE
[Transform] Fix bug when `latest` transform is used together with `from` parameter

### LINKED ISSUE #104543: [Transform] `latest` transform does not work when started with `from` parameter
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

Request to start a `latest` transform with `from` parameter consistently fails.

### Steps to Reproduce

1. Create a `latest` transform
2. Start it with `from` parameter set:
```
POST _transform/continuous_latest_from/_start?from=2017-01-23
```
3. Observe the transform indexer failing with `UnsupportedOperationException` (detailed logs below)

### Logs (if relevant)

```
» [2024-01-18T16:35:21,371][WARN ][o.e.x.t.t.TransformFailureHandler] [javaRestTest-0] [continuous_latest_from] Transform encountered an exception: [null]; Will automatically retry [1/10] java.lang.UnsupportedOperationException
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.latest.LatestChangeCollector.buildChangesQuery(LatestChangeCollector.java:35)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.TransformIndexer.buildQueryToFindChanges(TransformIndexer.java:1081)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.TransformIndexer.buildSearchRequest(TransformIndexer.java:1050)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.ClientTransformIndexer.doNextSearch(ClientTransformIndexer.java:147)
»       at org.elasticsearch.xcore@8.13.0-SNAPSHOT/org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexer.triggerNextSearch(AsyncTwoPhaseIndexer.java:621)
»       at org.elasticsearch.xcore@8.13.0-SNAPSHOT/org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexer.nextSearch(AsyncTwoPhaseIndexer.java:608)
»       at org.elasticsearch.xcore@8.13.0-SNAPSHOT/org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexer.lambda$maybeTriggerAsyncJob$4(AsyncTwoPhaseIndexer.java:233)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:169)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.TransformIndexer.lambda$onStart$6(TransformIndexer.java:277)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:169)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.TransformIndexer.lambda$onStart$7(TransformIndexer.java:313)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:169)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.common.AbstractCompositeAggFunction.getInitialProgressFromResponse(AbstractCompositeAggFunction.java:206)
»       at org.elasticsearch.transform@8.13.0-SNAPSHOT/org.elasticsearch.xpack.transform.transforms.TransformIndexer.lambda$onStart$10(TransformIndexer.java:310)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:169)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:312)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:298)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:312)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.TransportSearchAction.lambda$doExecute$4(TransportSearchAction.java:301)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:312)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:287)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:706)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:454)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:448)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:454)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:448)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:235)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:115)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:87)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
»       at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1583)
```

### PR DESCRIPTION
**Pull request by przemekwitek**
Currently, when `latest` transform is used together with `from` parameter, the `java.lang.UnsupportedOperationException` is being thrown by the indexer.
This PR fixes it so that no error is thrown and results are as expected.

Closes https://github.com/elastic/elasticsearch/issues/104543

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 1]
```diff
@@ -1177,7 +1177,7 @@ protected boolean shouldAuditOnFinish(long completedCheckpoint) {
     }
 
     private RunState determineRunStateAtStart() {
-        if (context.from() != null) {
+        if (context.from() != null && changeCollector.queryForChanges()) {
```
Comment (droberts195) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:1180]: On line 1190 below we check if `changeCollector == null`. If it can be `null` on line 1190 then surely it can be `null` here, and that will cause an NPE.

Comment (przemekwitek) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java]: Done.

**Review by droberts195 — APPROVED** [review]
LGTM
