### PR TITLE
Close rather than stop HttpServerTransport on shutdown

### LINKED ISSUE #102501: bug when server is shutting down (possibly after an error)
### Elasticsearch Version

docker.elastic.co/elasticsearch/elasticsearch:8.11.0

### Installed Plugins

N/A

### Java Version

_bundled_

### OS Version

MacOS Monterey 12.6

### Problem Description

Concurrent.ExecutionException","error.message":"java.lang.IllegalStateException: Can't move to stopped state when not started",

just look for "error" here:

```
elasticsearch-node3           | {"@timestamp":"2023-11-22T22:35:58.332Z", "log.level": "WARN", "message":"unexpected exception while waiting for http server to close", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-0","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"node3","elasticsearch.cluster.name":"mycluster","error.type":"java.util.concurrent.ExecutionException","error.message":"java.lang.IllegalStateException: Can't move to stopped state when not started","error.stack_trace":"java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Can't move to stopped state when not started\n\tat java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.node.Node.prepareForClose(Node.java:1776)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.bootstrap.Elasticsearch.shutdown(Elasticsearch.java:468)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.IllegalStateException: Can't move to stopped state when not started\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.common.component.Lifecycle.canMoveToStopped(Lifecycle.java:128)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:73)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.node.Node.lambda$prepareForClose$59(Node.java:1768)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\t... 1 more\n"}
elasticsearch-node1           | {"@timestamp":"2023-11-22T22:35:58.333Z", "log.level": "WARN", "message":"unexpected exception while waiting for http server to close", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-0","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"node1","elasticsearch.cluster.name":"mycluster","error.type":"java.util.concurrent.ExecutionException","error.message":"java.lang.IllegalStateException: Can't move to stopped state when not started","error.stack_trace":"java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Can't move to stopped state when not started\n\tat java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.node.Node.prepareForClose(Node.java:1776)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.bootstrap.Elasticsearch.shutdown(Elasticsearch.java:468)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.IllegalStateException: Can't move to stopped state when not started\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.common.component.Lifecycle.canMoveToStopped(Lifecycle.java:128)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:73)\n\tat org.elasticsearch.server@8.11.0/org.elasticsearch.node.Node.lambda$prepareForClose$59(Node.java:1768)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\t... 1 more\n"}
elasticsearch-node3           | {"@timestamp":"2023-11-22T22:35:58.336Z", "log.level": "INFO", "message":"stopping ...", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-0","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"node3","elasticsearch.cluster.name":"mycluster"}
elasticsearch-node1           | {"@timestamp":"2023-11-22T22:35:58.337Z", "log.level": "INFO", "message":"stopping ...", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-0","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"node1","elasticsearch.cluster.name":"mycluster"}
elasticsearch-node3           | {"@timestamp":"2023-11-22T22:35:58.386Z", "log.level": "INFO", "message":"stopped", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-0","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"node3","elasticsearch.cluster.name":"mycluster"}
elasticsearch-node1           | {"@timestamp":"2023-11-22T22:35:58.387Z", "log.level": "INFO", "message":"stopped", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"Thread-0","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"node1","elasticsearch.cluster.name":"mycluster"}

```

### Steps to Reproduce

I have this in docker-compose:

```yaml
  elasticsearch-node1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.11.0"
    container_name: elasticsearch-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=mycluster
      - node.name=node1
      - action.auto_create_index=true
      - cluster.initial_master_nodes=node1  # Add node3
    ports:
      - "9201:9200"
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by thecoop**
Call `close` rather than `stop` on HttpServerTransport on shutdown. This will not throw an exception if the node has not yet fully started up before it is shut down.

This will result instead in [start](https://github.com/elastic/elasticsearch/blob/964d5e4b688a83c9c7fce6af9bf0a4ed696b5885/server/src/main/java/org/elasticsearch/node/Node.java#L404) throwing an exception in the `Node.start()` method. This exception is now caught, and a clearer exception message is given in this case.

This resolves #102501

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/node/NodeTests.java [hunk 1]
```diff
@@ -336,7 +334,7 @@ public void testCloseOnLeakedStoreReference() throws Exception {
 
     public void testStartOnClosedTransport() throws IOException {
         try (Node node = new MockNode(baseSettings().build(), basePlugins())) {
-            node.injector().getInstance(HttpServerTransport.class).close();
+            node.prepareForClose();
```
Comment (ldematte) [inline server/src/test/java/org/elasticsearch/node/NodeTests.java:337]: Nit: it is a tiny bit different, as `prepareForClose()` invokes `HttpServerTransport#stop()`, which does "less". If the test passes I think it's OK, but possibly needs renamig to `testStartOnStoppedTransport`?

**Review by ldematte — APPROVED** [review]
Seems good, but check my comment please

File: server/src/test/java/org/elasticsearch/node/NodeTests.java (hunk 1 above)
Comment (thecoop) [reply server/src/test/java/org/elasticsearch/node/NodeTests.java:337]: This PR modifies `prepareForClose` to call `close` instead

Comment (ldematte) [reply server/src/test/java/org/elasticsearch/node/NodeTests.java:337]: Yes, just figured out: I was looking at the wrong revision. Looks good!

File: server/src/main/java/org/elasticsearch/node/Node.java [hunk 2]
```diff
@@ -575,10 +584,7 @@ public synchronized void close() throws IOException {
      */
     public void prepareForClose() {
         HttpServerTransport httpServerTransport = injector.getInstance(HttpServerTransport.class);
-        FutureTask<Void> stopper = new FutureTask<>(() -> {
-            httpServerTransport.stop();
-            return null;
-        });
+        FutureTask<Void> stopper = new FutureTask<>(httpServerTransport::close, null);
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/node/Node.java:587]: I don't think close will work. AbstractHttpServerTransport shuts down its http channels in stop. Close is a no-op.

File: server/src/main/java/org/elasticsearch/node/Node.java [hunk 3]
```diff
@@ -401,7 +401,16 @@ public void onTimeout(TimeValue timeout) {
             }
         }
 
-        injector.getInstance(HttpServerTransport.class).start();
+        var httpTransport = injector.getInstance(HttpServerTransport.class);
+        try {
+            httpTransport.start();
+        } catch (IllegalStateException e) {
+            if (httpTransport.lifecycleState() == Lifecycle.State.CLOSED) {
+                throw new IllegalStateException("Node is shutting down, cannot complete startup", e);
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/node/Node.java:409]: This should already be handled by `Lifecycle.canMoveToStarted()`

**Review by rjernst — COMMENTED** [review]
I don't think this can work as described: stop is important to shutting down a node, it's where we drain the http channels.

File: server/src/main/java/org/elasticsearch/node/Node.java (hunk 2 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/node/Node.java:587]: But `AbstractLifecycleComponent.close` ensures `stop` is called if it is started, _then_ it closes it. This is what we want, no?

File: server/src/main/java/org/elasticsearch/node/Node.java (hunk 3 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/node/Node.java:409]: I wanted to add a clearer exception message, as this is something which can actually appear to users, so they don't think this is an actual problem

Comment (rjernst) [reply server/src/main/java/org/elasticsearch/node/Node.java:409]: Couldn't this theoretically happen with any lifecycle component? We are in the middle of starting up, but we get a SIGTERM and start shutting down. Since they occur in separate threads, any lifecycle component could succumb to this error, not just the http transport.

Can we solve this messaging issue in AbstractLifecycleComponent? eg have a static volatile (perhaps in Elasticsearch or a utility class) that could be checked to determine if we are currently starting up or shutting down. Then when we find an error case in canMoveToStarted() or similar, we can check that and use a more tuned message.

File: server/src/main/java/org/elasticsearch/node/Node.java (hunk 2 above)
Comment (rjernst) [reply server/src/main/java/org/elasticsearch/node/Node.java:587]: You are right, I was only looking at close in AbstractHttpServerTransport.

File: server/src/main/java/org/elasticsearch/node/Node.java (hunk 3 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/node/Node.java]: Good idea - I've added a helper to determine if the process is shutting down

**Review by rjernst — APPROVED** [review]
LGTM
