### PR TITLE
[Tests] Fix rare edge case in SimpleQueryStringBuilderTests

### LINKED ISSUE #35183: [ci] SimpleQueryStringBuilderTests.testToQuery
Not sure what the right behavior is here, maybe it thinks the query shouldn't be cacheable because it's interpreting `"query" : "nOw"` as "now"?

Reproduces locally

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+periodic/97/console

[build-97.txt.zip](https://github.com/elastic/elasticsearch/files/2540144/build-97.txt.zip)

```
./gradlew :server:test -Dtests.seed=E44BD1DAE92D549C -Dtests.class=org.elasticsearch.index.query.SimpleQueryStringBuilderTests -Dtests.method="testToQuery" 
-Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=America/Campo_Grande
```

```
FAILURE 0.10s | SimpleQueryStringBuilderTests.testToQuery <<< FAILURES!                 
   > Throwable #1: java.lang.AssertionError: query was marked as not cacheable in the context but this test indicates it should be cacheable: {                                  
   >   "simple_query_string" : {                                                        
   >     "query" : "nOw",                                                               
   >     "analyzer" : "standard",                                                       
   >     "flags" : -1,                                                                  
   >     "default_operator" : "or",                                                     
   >     "analyze_wildcard" : false,
   >     "quote_field_suffix" : "yxzqzti",
   >     "minimum_should_match" : "75%",
   >     "auto_generate_synonyms_phrase_query" : true,
   >     "fuzzy_prefix_length" : 0,
   >     "fuzzy_max_expansions" : 50,
   >     "fuzzy_transpositions" : true,
   >     "boost" : 1.0
   >   }
   > }
   >    at __randomizedtesting.SeedInfo.seed([E44BD1DAE92D549C:13B0D3E498AE9176]:0)
   >    at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:423)
   >    at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by cbuescher**
If the random query string is "now" by accident _and_ we are also not setting
some field names to use explicitely, then we can hit the "mapped_date" field
from default test setup. This correctly leads to the query being was marked as
not cacheable, but we assume and check so later. This change fixes this rare
edge case by making sure we don't hit the "date" field in this rare cases.

Closes #35183

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java [hunk 1]
```diff
@@ -104,6 +104,12 @@ protected SimpleQueryStringBuilder doCreateTestQueryBuilder() {
                 fields.put(STRING_FIELD_NAME_2, 2.0f / randomIntBetween(1, 20));
             }
         }
+        // special handling if query is "now" and no field specified. This hits the "mapped_date" field which leads to the query not being
+        // cacheable and trigger later test failures (see https://github.com/elastic/elasticsearch/issues/35183)
+        if (fieldCount == 0 && result.value().equalsIgnoreCase("now")) {
+            fields.put(STRING_FIELD_NAME_2, 2.0f / randomIntBetween(1, 20));
+        }
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java]: I don't like really like adding so many lines for a relatively rare case, but every other way (e.g. disallowing "now" altogether as a query string) would have been worse IMHO.

**Review by nik9000 — APPROVED** [review]
