### PR TITLE
ESQL: make named params objects truly per request

### LINKED ISSUE #110028: [ES|QL][Named parameters] Not sending the params in a query with named parameters results in blocking all future _query requests
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

Using named parameters in the query and not sending the params results in breaking my _query api.

### Steps to Reproduce

Run this without sending the params:

```
POST /_query/async?drop_null_columns
{
  "query": "ROW x = ?name1, y = ?name1"
}
```
It will fail, which is expected!

Then run this:

```
POST /_query/async?drop_null_columns
{
  "query": "ROW x =1"
}
```

It fails and now all my _query requests are blocked, all error out,  I have to restart my cluster. 

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by astefan**
Fixes #110028

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequestTests.java [hunk 1]
```diff
@@ -182,6 +185,20 @@ public void testInvalidParams() throws IOException {
         );
     }
 
+    // Test for https://github.com/elastic/elasticsearch/issues/110028
+    public void testNamedParamsMutation() {
```
Comment (fang-xing-esql) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryRequestTests.java:189]: 👍
