### PR TITLE
[ML] fix bugs with prediction field value settings

### LINKED ISSUE #55332: [ML] Inference returns different predicted_value comparing with model prediction
Spotted in master build 6892

when using `seeds` dataset, Inference returned different predicted_value comparing with model prediction.  model returns `1,2,3`, but inference returns `1.0,2.0,0.0`

To reproduce,
1. create a classification job.
```
{
  "source": {
    "index": [
      "seeds"
    ]
  },
  "dest": {
    "index": "dest_seeds_80",
    "results_field": "ml"
  },
  "analysis": {
    "classification": {
      "dependent_variable": "seed_class",
      "num_top_feature_importance_values": 2,
      "class_assignment_objective": "maximize_minimum_recall",
      "num_top_classes": 2,
      "prediction_field_name": "seed_class_prediction",
      "training_percent": 80
    }
  }
}
```
2. run job, then create a pipeline, then run inference.
 - pipeline configure
```
PUT _ingest/pipeline/inference_pipeline
{
  "processors": [
	{
  	"inference": {
      	"model_id": "dfa_seeds_1587034738_000_0-1587049148665",
      	"target_field": "class_prediction_infer",
      	"field_map": {
      	  
      	},
      	"inference_config": {"classification": {
      	  "num_top_feature_importance_values": 3
      	}}
    	}
	}
  ]
}
```

3. Now, against dest index, run aggregations on both predictions, you will get:
```
"aggregations" : {
    "inference" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 1.0,
          "doc_count" : 71
        },
        {
          "key" : 2.0,
          "doc_count" : 70
        },
        {
          "key" : 0.0,
          "doc_count" : 69
        }
      ]
    },
    "ml" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 1,
          "doc_count" : 71
        },
        {
          "key" : 2,
          "doc_count" : 70
        },
        {
          "key" : 3,
          "doc_count" : 69
        }
      ]
    }
  }
```

### PR DESCRIPTION
**Pull request by benwtrent**
This fixes two unreleased bugs:

1. Prediction value type of `number` might show unexpected classes

Analytics created models may have class labels like `1, 5, 10` (or some collection of discrete, whole numbers). These labels are passed to the inference model config in the `classification_labels` field.

When the predicted value format is `numeric` it should attempt to see if the classification labels are provided and are numeric. If so, use those. If not, use the underlying value.

2. When supplying an update overwrite, inference was losing the default prediction field value. This is because it was not copied over in the copy ctor in the ClassificationConfig.Builder class. 

closes #55332

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java [hunk 1]
```diff
@@ -57,6 +57,19 @@ public Object transformPredictedValue(Double value, String stringRep) {
                 }
                 return areClose(value, 1.0D);
             case NUMBER:
+                if (stringRep == null) {
+                    return value;
+                }
+                // Quick check to verify that the string rep is LIKELY a number
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java:63]: Two questions here:
1. What do we do with an empty string? Currently it would fail with `IndexOutOfBounds`, right?
2. Why do we prioritize `stringRep` over `value` even in a number case?

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldTypeTests.java [hunk 2]
```diff
@@ -38,6 +38,8 @@ public void testTransformPredictedValueNumber() {
             is(nullValue()));
         assertThat(PredictionFieldType.NUMBER.transformPredictedValue(1.0, "foo"), equalTo(1.0));
         assertThat(PredictionFieldType.NUMBER.transformPredictedValue(1.0, null), equalTo(1.0));
+        long expected = randomLong();
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldTypeTests.java:41]: Could you add tests for:
1. an empty string
2. a string that is not a number?

Comment (benwtrent) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldTypeTests.java:41]: There is already a test for 2. See line 39.

I will add a test for 1

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java:63]: 1. Good question, I am not sure what to do in this case....Probably return underlying value.
2. Please read the PR description. When creating a model in analytics, it is possible to have classification classes that are numeric, but not ordinal. These are treated as classification_labels.

**Comment by benwtrent** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java [hunk 3]
```diff
@@ -57,6 +58,19 @@ public Object transformPredictedValue(Double value, String stringRep) {
                 }
                 return areClose(value, 1.0D);
             case NUMBER:
+                if (Strings.isNullOrEmpty(stringRep)) {
+                    return value;
+                }
+                // Quick check to verify that the string rep is LIKELY a number
+                // Still handles the case where it throws and then returns the underlying value
+                if (stringRep.charAt(0) == '-' || Character.isDigit(stringRep.charAt(0))) {
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java:66]: Could we just drop it and rely solely on `parseLong`?
Or is this some kind of perf optimization? If so, are you sure it is really faster?

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java (hunk 3 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PredictionFieldType.java:66]: It is way faster if `stringRep` is consistently not a number (which could easily be the case). Every call that it is not a number throws an exception, and the JVM has to build a trace.
