### PR TITLE
Change EmailSslTest for FIPS 140 JVMs

### LINKED ISSUE #46067: EmailSslTests failures
Some of the tests in EmailSslTests have failed twice in the last two days with the same error:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=general-purpose/171/

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=general-purpose/170

```
Tests with failures:
- org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testCanSendMessageToSmtpServerByDisablingVerification
- org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testFailureSendingMessageToSmtpServerWithUntrustedCertificateAuthority
- org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testCanSendMessageToSmtpServerUsingTrustStore
```

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests "org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testFailureSendingMessageToSmtpServerWithUntrustedCertificateAuthority" -Dtests.seed=A1B1C9850FA48B30 -Dtests.security.manager=true -Dtests.locale=de -Dtests.timezone=Africa/Luanda -Dcompiler.java=12 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:52:06   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests 
```

```
07:52:06 org.elasticsearch.xpack.watcher.actions.email.EmailSslTests > testFailureSendingMessageToSmtpServerWithUntrustedCertificateAuthority FAILED
07:52:06     java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.ASN1Integer
07:52:06         at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.<init>(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
07:52:06         at java.security.KeyStore.load(KeyStore.java:1445)
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.startSmtpServer(EmailSslTests.java:56)
07:52:06 
07:52:06     java.lang.NullPointerException
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.stopSmtpServer(EmailSslTests.java:64)
```

```
07:52:06 org.elasticsearch.xpack.watcher.actions.email.EmailSslTests > testCanSendMessageToSmtpServerByDisablingVerification FAILED
07:52:06     java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.ASN1Integer
07:52:06         at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.<init>(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
07:52:06         at java.security.KeyStore.load(KeyStore.java:1445)
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.startSmtpServer(EmailSslTests.java:56)
07:52:06 
07:52:06     java.lang.NullPointerException
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.stopSmtpServer(EmailSslTests.java:64)

```

### PR DESCRIPTION
**Pull request by jkakavas**
This commit changes the SSLContext for the email server we use in
the tests so that it loads its key material from an in memory
keystore instead of a PKCS#12 one. This is done so that when we run
our tests in FIPS 140-2 JVMs, the keystore is of a type that the
Security Provider actually supports.

This also mutes testCanSendMessageToSmtpServerByDisablingVerification
as we can't run tests with verification set to `none` in FIPS 140
JVMs.

Resolves: #46067

### CODE REVIEW

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/actions/email/EmailSslTests.java [hunk 1]
```diff
@@ -50,18 +53,26 @@
 
     @Before
     public void startSmtpServer() throws GeneralSecurityException, IOException {
-        final KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
+        // Keystore and private key will share the same password
         final char[] keystorePassword = "test-smtp".toCharArray();
-        try (InputStream is = getDataInputStream("test-smtp.p12")) {
```
Comment (bizybot) [inline x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/actions/email/EmailSslTests.java]: If we are not using `test-smtp.p12` then can we remove it?

**Review by bizybot — APPROVED** [review]
LGTM, Thank you.

File: x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/actions/email/EmailSslTests.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/actions/email/EmailSslTests.java]: we use it on ES side as trust material for some tests. This change only makes it so that we don;t use it as key material for the SMTP server
