### PR TITLE
Avoid flipping translog header version

### LINKED ISSUE #58671: [CI] Failures for RemoveCorruptedShardDataCommandIT.testCorruptTranslogTruncationOfReplica
**Build scan**: https://gradle-enterprise.elastic.co/s/c4xzxjqoq6ij4

**Repro line**: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT.testCorruptTranslogTruncationOfReplica" -Dtests.seed=43CFC5A2A11E2E8F -Dtests.security.manager=true -Dtests.locale=ca -Dtests.timezone=Asia/Riyadh -Druntime.java=8

**Reproduces locally?**: Yes

**Failure excerpt**:

```
org.elasticsearch.ElasticsearchException: Shard does not seem to be corrupted at /mnt/secret/elastic+elasticsearch+7.x+EAR/server/build/testrun/internalClusterTest/temp/org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT_43CFC5A2A11E2E8F-001/tempDir-004/node_t2/nodes/0/indices/lc1zxYu-RWqfpeQ4EUjwZw/0 (pass --truncate-clean-translog to truncate the translog anyway)	
at __randomizedtesting.SeedInfo.seed([43CFC5A2A11E2E8F:6EE19929E0484404]:0)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.lambda$processNodePaths$2(RemoveCorruptedShardDataCommand.java:326)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.findAndProcessShardPath(RemoveCorruptedShardDataCommand.java:183)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.processNodePaths(RemoveCorruptedShardDataCommand.java:258)	
at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.processNodePaths(ElasticsearchNodeCommand.java:158)	
at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.execute(ElasticsearchNodeCommand.java:176)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT.testCorruptTranslogTruncationOfReplica(RemoveCorruptedShardDataCommandIT.java:514)	
```

### PR DESCRIPTION
**Pull request by dnhatn**
An old translog header does not have a [checksum](https://github.com/elastic/elasticsearch/blob/f63cbad62987b3497b5675dff4091767468744ad/server/src/main/java/org/elasticsearch/index/translog/TranslogHeader.java#L148-L150). If we flip the header version of an empty translog to the older version, then we won't detect that corruption, and translog will be considered clean as before.

Closes #58671

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/2

**Review by ywelsch — COMMENTED** [review]
Isn't this purely an issue on 7.x? On master, we always verifyChecksum.

**Comment by dnhatn** [comment]
> Isn't this purely an issue on 7.x? On master, we always verifyChecksum.

Yes, I will rebase this PR against 7.x.

File: server/src/main/java/org/elasticsearch/index/translog/TranslogHeader.java [hunk 1]
```diff
@@ -105,6 +106,21 @@ private static int headerSizeInBytes(int version, int uuidLength) {
         return size;
     }
 
+
+    static int readHeaderVersion(final Path path, final FileChannel channel, final StreamInput in) throws IOException {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/translog/TranslogHeader.java:110]: can you forward-port this method extraction so that we have code more aligned on master/7.x?

**Review by ywelsch — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/index/translog/TranslogHeader.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/translog/TranslogHeader.java:110]: Sure, will do.

**Comment by dnhatn** [comment]
Thanks Yannick.
