### PR TITLE
Fix DLS over Runtime Fields

### LINKED ISSUE #111637: IndexOutOfBounds error when using DLS over a runtime field
### Elasticsearch Version

any

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When using document level security that queries a runtime field, users might see an exceptions logged like
```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
```

And even retrieve fewer than expected documents. Meaning, they can get different documents returned at different times, very unexpected behavior.

We should either:

 - disallow DLS over runtime fields
 - Fix this behavior so it just works (I am in favor of this one...)

### Steps to Reproduce

Run the following test in `org.elasticsearch.integration.DocumentLevelSecurityRandomTests`

```
public void testWithRuntimeMapping() throws Exception {
        XContentBuilder mapping = XContentFactory.jsonBuilder()
            .startObject()
            .startObject("runtime")
            .startObject("field1")
            .field("type", "keyword")
            .endObject()
            .endObject()
            .startObject("properties")
            .startObject("field2")
            .field("type", "keyword")
            .endObject()
            .endObject()
            .endObject();
        assertAcked(indicesAdmin().prepareCreate("test").setMapping(mapping));
        List<IndexRequestBuilder> requests = new ArrayList<>(47);
        for (int i = 1; i <= 42; i++) {
            requests.add(prepareIndex("test").setSource("field1", "value1", "field2", "foo" + i));
        }
        for (int i = 42; i <= 57; i++) {
            requests.add(prepareIndex("test").setSource("field1", "value2", "field2", "foo" + i));
        }
        indexRandom(true, requests);
        assertResponse(
            client().filterWithHeader(Collections.singletonMap(BASIC_AUTH_HEADER, basicAuthHeaderValue("user1", USERS_PASSWD)))
                .prepareSearch("test"),
            searchResponse -> {
                assertThat(searchResponse.getHits().getTotalHits().value, equalTo(42L));
            }
        );
    }
```

### Logs (if relevant)

```
Caused by: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:365) ~[?:?]
	at org.apache.lucene.codecs.lucene90.compressing.FieldsIndexReader.getStartPointer(FieldsIndexReader.java:117) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.serializedDocument(Lucene90CompressingStoredFieldsReader.java:606) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.codecs.lucene90.compressing.Lucene90CompressingStoredFieldsReader.document(Lucene90CompressingStoredFieldsReader.java:628) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.elasticsearch.search.internal.FieldUsageTrackingDirectoryReader$FieldUsageTrackingLeafReader$FieldUsageTrackingStoredFieldsReader.document(FieldUsageTrackingDirectoryReader.java:271) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.index.fieldvisitor.StoredFieldLoader$ReaderStoredFieldLoader.advanceTo(StoredFieldLoader.java:204) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.lookup.StoredFieldSourceProvider$LeafStoredFieldSourceProvider.getSource(StoredFieldSourceProvider.java:75) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.lookup.StoredFieldSourceProvider.getSource(StoredFieldSourceProvider.java:38) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:39) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.script.AbstractFieldScript.extractFromSource(AbstractFieldScript.java:106) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.script.AbstractFieldScript.emitFromSource(AbstractFieldScript.java:126) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.script.StringFieldScript$1$1.execute(StringFieldScript.java:36) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.script.AbstractFieldScript.runForDoc(AbstractFieldScript.java:158) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.runtime.AbstractStringScriptFieldQuery.matches(AbstractStringScriptFieldQuery.java:27) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.runtime.AbstractStringScriptFieldQuery.matches(AbstractStringScriptFieldQuery.java:19) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.runtime.AbstractScriptFieldQuery$2.matches(AbstractScriptFieldQuery.java:96) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.apache.lucene.search.TwoPhaseIterator$TwoPhaseIteratorAsDocIdSetIterator.doNext(TwoPhaseIterator.java:85) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.search.TwoPhaseIterator$TwoPhaseIteratorAsDocIdSetIterator.nextDoc(TwoPhaseIterator.java:73) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.util.BitSet.or(BitSet.java:110) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.util.FixedBitSet.or(FixedBitSet.java:326) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.util.BitSet.of(BitSet.java:42) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.elasticsearch.lucene.util.BitSets.of(BitSets.java:24) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCache.computeBitSet(DocumentSubsetBitsetCache.java:286) ~[x-pack-core-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCache.lambda$getBitSet$4(DocumentSubsetBitsetCache.java:244) ~[x-pack-core-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:439) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCache.getBitSet(DocumentSubsetBitsetCache.java:235) ~[x-pack-core-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetReader.computeNumDocsIfNeeded(DocumentSubsetReader.java:183) ~[x-pack-core-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetReader.numDocs(DocumentSubsetReader.java:213) ~[x-pack-core-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.apache.lucene.index.BaseCompositeReader.numDocs(BaseCompositeReader.java:154) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.elasticsearch.search.query.QueryPhaseCollectorManager.createQueryPhaseCollectorManager(QueryPhaseCollectorManager.java:224) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.addCollectorsAndSearch(QueryPhase.java:193) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.executeQuery(QueryPhase.java:135) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:62) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:532) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:690) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:559) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.16.0-SNAPSHOT.jar:8.16.0-SNAPSHOT]
```

Here are some 8.13 logs (we trip a `maxDoc` assertion):

```
d’ag. 06, 2024 1:58:04 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#185,elasticsearch[node_s5][search][T#2],5,TGRP-DocumentLevelSecurityRandomTests]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([8F34F6DFB7E6B7B]:0)
	at org.apache.lucene.tests.codecs.asserting.AssertingStoredFieldsFormat$AssertingStoredFieldsReader.document(AssertingStoredFieldsFormat.java:76)
	at org.elasticsearch.search.internal.FieldUsageTrackingDirectoryReader$FieldUsageTrackingLeafReader$FieldUsageTrackingStoredFieldsReader.document(FieldUsageTrackingDirectoryReader.java:271)
	at org.elasticsearch.index.fieldvisitor.StoredFieldLoader$ReaderStoredFieldLoader.advanceTo(StoredFieldLoader.java:204)
	at org.elasticsearch.search.lookup.StoredFieldSourceProvider$LeafStoredFieldSourceProvider.getSource(StoredFieldSourceProvider.java:75)
	at org.elasticsearch.search.lookup.StoredFieldSourceProvider.getSource(StoredFieldSourceProvider.java:38)
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:39)
	at org.elasticsearch.script.AbstractFieldScript.extractFromSource(AbstractFieldScript.java:106)
	at org.elasticsearch.script.AbstractFieldScript.emitFromSource(AbstractFieldScript.java:126)
	at org.elasticsearch.script.StringFieldScript$1$1.execute(StringFieldScript.java:36)
	at org.elasticsearch.script.AbstractFieldScript.runForDoc(AbstractFieldScript.java:158)
	at org.elasticsearch.search.runtime.AbstractStringScriptFieldQuery.matches(AbstractStringScriptFieldQuery.java:27)
	at org.elasticsearch.search.runtime.AbstractStringScriptFieldQuery.matches(AbstractStringScriptFieldQuery.java:19)
	at org.elasticsearch.search.runtime.AbstractScriptFieldQuery$2.matches(AbstractScriptFieldQuery.java:96)
	at org.apache.lucene.search.TwoPhaseIterator$TwoPhaseIteratorAsDocIdSetIterator.doNext(TwoPhaseIterator.java:85)
	at org.apache.lucene.search.TwoPhaseIterator$TwoPhaseIteratorAsDocIdSetIterator.nextDoc(TwoPhaseIterator.java:73)
	at org.apache.lucene.util.BitSet.or(BitSet.java:110)
	at org.apache.lucene.util.FixedBitSet.or(FixedBitSet.java:326)
	at org.apache.lucene.util.BitSet.of(BitSet.java:42)
	at org.elasticsearch.lucene.util.BitSets.of(BitSets.java:24)
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCache.computeBitSet(DocumentSubsetBitsetCache.java:286)
	at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCache.
```

### PR DESCRIPTION
**Pull request by original-brownbear**
There is a DLS query referencing a runtime field loaded from _source, when we create the collector manager we retrieve the numDocs which triggers going through all segments and executing the script for each document. StoredFieldSourceProvider relies on leaf ordinals to build an array, but those ordinals are not populated when computing the numDocs via BaseCompositeReader, as that goes through the subreaders contexts, and not the context leaves (there is a subtle difference that bites us there).

Fixes #111637

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java [hunk 1]
```diff
@@ -8,53 +8,38 @@
...
-        return ctx;
-    }
-
-    private LeafStoredFieldSourceProvider[] getLeavesUnderLock(IndexReaderContext parentCtx) {
-        if (leaves == null) {
-            synchronized (this) {
-                if (leaves == null) {
-                    leaves = new LeafStoredFieldSourceProvider[parentCtx.leaves().size()];
-                }
+        final Object id = ctx.id();
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java:33]: interesting, I did not even know this one existed, I would have used LeafReaderContext itself as a key, I've seen that done in other places too. But this should be fine as well

File: server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java [hunk 2]
```diff
@@ -8,53 +8,38 @@
...
+        var provider = leaves.get(id);
+        if (provider == null) {
+            provider = new LeafStoredFieldSourceProvider(storedFieldLoader.getLoader(ctx, null));
+            var existing = leaves.putIfAbsent(id, provider);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java:37]: why not do a computeIfAbsent as opposed to get and then putIfAbsent?

**Review by javanna — APPROVED** [review]
I left some small comments, I also think that this is the right fix, at least until we introduce intra-segment concurrency. I don't think performance matters a lot here: when this is called as part of the query phase, we are already retrieving stored fields for every possible document, hence on a very slow path, using an array vs the updated approach won't make a lot of difference. It may make a bit of a difference in the fetch phase perhaps, but then again, the previous solution was relying on the false assumption that the ordinals are always correctly populated.


Could you update the description of the PR to explain the flow that leads to reproducing more clearly? There is a DLS query referencing a runtime field loaded from `_source`, when we create the collector manager we retrieve the numDocs which triggers going through all segments and executing the script for each document. StoredFieldSourceProvider relies on leaf ordinals to build an array, but those ordinals are not populated when computing the numDocs via BaseCompositeReader, as that goes through the subreaders contexts, and not the context leaves (there is a subtle difference that bites us there).

**Comment by javanna** [comment]
This should be backported to 8.15 as well, it's a pretty nasty bug, although hopefully in practice there are not many users relying on runtime fields loaded from _source in their DLS queries, as that will badly affect performance of each and every query due to having to load stored fields for every document.

File: server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java:37]: `computeIfAbsent` requires a capturing lambda here, since that lambda is mostly not used we can save a lot of cycles by using this approach. `computeIfAbsent` is also needlessly lock-heavy for our use-case. Since we know we will never really conflict here, there's no need for it's internal synchronisation on the key :)

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java:37]: and why then do a putIfAbsent and not just put if provider is null?

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/search/lookup/StoredFieldSourceProvider.java:37]: huh that's a fair point :) this should really be an assertion, thanks! Let me fix that :)

**Comment by javanna** [comment]
I think I found another place where we potentially have the same issue: https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/lookup/SyntheticSourceProvider.java#L25 . You should be able to repro that with your same test, but using synthetic source. I guess we should fix that too as a follow-up?

**Comment by original-brownbear** [comment]
Thanks so much Jack + Luca!

**Comment by original-brownbear** [comment]
@javanna 

> You should be able to repro that with your same test, but using synthetic source. I guess we should fix that too as a follow-up?

on it :)
