### PR TITLE
ES|QL: unmute SetClusterTests

### LINKED ISSUE #140673: [CI] SetParserTests testSetUnmappedFieldsWrongValue failing
**Build Scans:**
- [elasticsearch-periodic #11733 / release-tests](https://gradle-enterprise.elastic.co/s/5qzhyxabsy566)
- [elasticsearch-periodic #11733 / release-tests](https://gradle-enterprise.elastic.co/s/q7rf5yjpp3zm4)
- [elasticsearch-pull-request #114172 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/ajvqlclm5yxgc)
- [elasticsearch-pull-request #114172 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/hqu6ox2hxkeqi)
- [elasticsearch-pull-request #114168 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/eycxnmxbds2hq)
- [elasticsearch-periodic-java-ea #144 / release-tests](https://gradle-enterprise.elastic.co/s/begs2jqmxlozo)
- [elasticsearch-pull-request #114139 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/2vp5vybaomcsu)
- [elasticsearch-pull-request #114129 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/hsv6evmtb3fc4)
- [elasticsearch-pull-request #114055 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/3w7fekvanf2lk)
- [elasticsearch-pull-request #114026 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/hq7pox4uwtcpw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.parser.SetParserTests.testSetUnmappedFieldsWrongValue" -Dtests.seed=535BC2B7CA3D3598 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=se-FI -Dtests.timezone=Asia/Macao -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.parser.SetParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSetUnmappedFieldsWrongValue'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Statement [SET unmapped_fields="Nppo"; row a = 1] is expected to throw class org.elasticsearch.xpack.esql.parser.ParsingException with message [Error validating setting [unmapped_fields]: Invalid unmapped_fields resolution [Nppo], must be one of [FAIL, NULLIFY, LOAD]]
Expected: a string containing "Error validating setting [unmapped_fields]: Invalid unmapped_fields resolution [Nppo], must be one of [FAIL, NULLIFY, LOAD]"
     but: was "line 1:1: Setting [unmapped_fields] is only available in snapshot builds"
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 12 failures in test testSetUnmappedFieldsWrongValue (4.3% fail rate in 280 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 9 failures in step checkpart3_release-tests (60.0% fail rate in 15 executions)
- [main] 8 failures in pipeline elasticsearch-pull-request (4.5% fail rate in 178 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140750: [CI] PhysicalPlanOptimizerTests testPushDownMetadataTierInOrOperator {default} failing
**Build Scans:**
- [elasticsearch-periodic #11738 / release-tests](https://gradle-enterprise.elastic.co/s/h6p6ao5xrgam6)
- [elasticsearch-periodic #11738 / release-tests](https://gradle-enterprise.elastic.co/s/7url4b7ux77dc)
- [elasticsearch-pull-request #114560 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/4wianxznfe4zy)
- [elasticsearch-pull-request #114530 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/v27qulrumskhu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.PhysicalPlanOptimizerTests.testPushDownMetadataTierInOrOperator {default}" -Dtests.seed=AE4D502F3E084E11 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ar-YE -Dtests.timezone=Turkey -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.PhysicalPlanOptimizerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testPushDownMetadataTierInOrOperator%20%7Bdefault%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.parser.ParsingException: line 1:20: unsupported metadata field [_tier]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart3_release-tests
- [main] 4 failures in test testPushDownMetadataTierInOrOperator {default} (6.5% fail rate in 62 executions)
- [main] 2 failures in step release-tests (100.0% fail rate in 2 executions)
- [main] 2 failures in step checkpart3_release-tests (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (4.7% fail rate in 43 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140751: [CI] PhysicalPlanOptimizerTests testPushDownMetadataTierInOperator {default} failing
**Build Scans:**
- [elasticsearch-periodic #11738 / release-tests](https://gradle-enterprise.elastic.co/s/h6p6ao5xrgam6)
- [elasticsearch-periodic #11738 / release-tests](https://gradle-enterprise.elastic.co/s/7url4b7ux77dc)
- [elasticsearch-pull-request #114560 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/4wianxznfe4zy)
- [elasticsearch-pull-request #114530 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/v27qulrumskhu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.PhysicalPlanOptimizerTests.testPushDownMetadataTierInOrOperator {default}" -Dtests.seed=AE4D502F3E084E11 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ar-YE -Dtests.timezone=Turkey -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.PhysicalPlanOptimizerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testPushDownMetadataTierInOperator%20%7Bdefault%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.xpack.esql.parser.ParsingException: line 1:20: unsupported metadata field [_tier]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart3_release-tests
- [main] 4 failures in test testPushDownMetadataTierInOperator {default} (6.5% fail rate in 62 executions)
- [main] 2 failures in step release-tests (100.0% fail rate in 2 executions)
- [main] 2 failures in step checkpart3_release-tests (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (4.7% fail rate in 43 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Unmuting a test that should be already fixed and fixing some release tests

Fixes: https://github.com/elastic/elasticsearch/issues/140673
Fixes: https://github.com/elastic/elasticsearch/issues/140750
Fixes: https://github.com/elastic/elasticsearch/issues/140751
Fixes: https://github.com/elastic/elasticsearch/issues/140752

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -3023,6 +3023,7 @@ public void testPushDownMetadataTierInEquality() {
      *       \_EsQueryExec[test], query={"terms":{"_tier":["data_hot","data_warm"],"boost":0.0}}
      */
     public void testPushDownMetadataTierInOperator() {
+        assumeTrue("_tier metadata only available in snapshot builds", Build.current().isSnapshot());
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java:3026]: Thanks for catching it!
