### PR TITLE
fix access denied for shard deletion with WindowsFS

### LINKED ISSUE #13758: [CI] MetaDataWriteDataNodesIT.testMetaIsRemovedIfAllShardsFromIndexRemoved failure
Fails with the following generic message (for this test, as this is what it tests):

expected index to not be in meta state of node node_t1

see http://build-us-00.elastic.co/job/es_core_2x_centos/334/testReport/junit/org.elasticsearch.gateway/MetaDataWriteDataNodesIT/testMetaIsRemovedIfAllShardsFromIndexRemoved/

More detailed to be filled in as they are found.

### PR DESCRIPTION
**Pull request by brwe**
We randomly use the WindowsFS mock file system to simulate that
windows does not delete files if they are opened by some other
process and instead gives you java.io.IOException: access denied.
In the tests we also check if the shard was deleted while it is
being deleted. This check loads the mata data of the index
and therefore might hold on to a file while the node
is trying to delete it and deletion will fail then.

Instead we should just check if the directory was removed.

closes #13758

### CODE REVIEW

**Comment by brwe** [comment]
@s1monw want to take a look?

File: core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java [hunk 1]
```diff
@@ -149,48 +151,52 @@ public void testMetaWrittenWhenIndexIsClosedAndMetaUpdated() throws Exception {
...
-        assertMetaState(nodeName, indexName, false);
+    protected void assertIndexDirectoryDeleted(final String nodeName, final String indexName) throws Exception {
+        assertBusy(new Runnable() {
+                       @Override
+                       public void run() {
+                           logger.info("checking if meta state exists...");
+                           try {
+                               assertFalse("Expecting index directory of " + indexName + " to be deleted from node " + nodeName, indexDirectoryExists(nodeName, indexName));
+                           } catch (Exception e) {
+                               logger.info("failed to check for data director of index {} on node {}", indexName, nodeName);
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java]: why do we have the catch blocks here? assertBusy does this if it fails as well

File: core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java [hunk 2]
```diff
@@ -149,48 +151,52 @@ public void testMetaWrittenWhenIndexIsClosedAndMetaUpdated() throws Exception {
...
-        assertMetaState(nodeName, indexName, true);
+    protected void assertIndexInMetaState(final String nodeName, final String indexName) throws Exception {
+        assertBusy(new Runnable() {
+                       @Override
+                       public void run() {
+                           logger.info("checking if meta state exists...");
+                           try {
+                               assertTrue("Expecting meta state of index " + indexName + " to be on node " + nodeName, getIndicesMetaDataOnNode(nodeName).containsKey(indexName));
+                           } catch (Throwable t) {
+                               logger.info("failed to load meta state", t);
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java]: same here

File: core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java [hunk 3]
```diff
@@ -149,48 +151,52 @@ public void testMetaWrittenWhenIndexIsClosedAndMetaUpdated() throws Exception {
         assertThat(indicesMetaData.get(index).state(), equalTo(IndexMetaData.State.OPEN));
     }
 
-    protected void assertIndexNotInMetaState(String nodeName, String indexName) throws Exception {
-        assertMetaState(nodeName, indexName, false);
+    protected void assertIndexDirectoryDeleted(final String nodeName, final String indexName) throws Exception {
+        assertBusy(new Runnable() {
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java]: can you simplify this with a java8 lambda!

**Comment by s1monw** [comment]
left some comments

File: core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java (hunk 1 above)
Comment (brwe) [inline core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java]: we can actually remove the `throws` from indexDirectoryExists altogether.

File: core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java (hunk 2 above)
Comment (brwe) [inline core/src/test/java/org/elasticsearch/gateway/MetaDataWriteDataNodesIT.java]: `getIndicesMetaDataOnNode` throws `Exception` but `run()` in `Runnable` not. Not sure how I can avoid the catch here?

**Comment by brwe** [comment]
Thanks for the review! Addressed all comments just not sure about https://github.com/elastic/elasticsearch/pull/14089#discussion_r41911509

**Comment by s1monw** [comment]
LGTM
