### PR TITLE
[ML] Support mapped runtime fields for data frame analytics

### LINKED ISSUE #65854: [ML] DFA job failed to run when RT fields is not part of index _source
Step to reproduce,
1. create one index using below mappings
```
{
  "farequote-rt" : {
    "mappings" : {
      "dynamic" : "false",
      "runtime" : {
        "lowercase_airline" : {
          "type" : "keyword",
          "script" : {
            "source" : "emit(params._source.airline.toLowerCase())",
            "lang" : "painless"
          }
        },
        "responsetime" : {
          "type" : "double",
          "script" : {
            "source" : "emit(params._source.responsetime)",
            "lang" : "painless"
          }
        },
        "responsetime_bigger" : {
          "type" : "double",
          "script" : {
            "source" : "emit(params._source.responsetime * 2)",
            "lang" : "painless"
          }
        }
      },
      "properties" : {
        "@timestamp" : {
          "type" : "date"
        }
      }
    }
  }
}
```

2. reindex `farequote` dataset to `farequote-rt`
3. create a regression job by using the below job configure:
```
{
  "id": "fq_rt_outliers",
  "create_time": 1606909980318,
  "version": "8.0.0",
  "description": "",
  "source": {
    "index": [
      "farequote-rt"
    ],
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "fq_rt_outliers",
    "results_field": "ml"
  },
  "analysis": {
    "outlier_detection": {
      "compute_feature_influence": true,
      "outlier_fraction": 0.05,
      "standardization_enabled": true
    }
  },
  "analyzed_fields": {
    "includes": [
      "responsetime",
      "responsetime_bigger"
    ],
    "excludes": []
  },
  "model_memory_limit": "33mb",
  "allow_lazy_start": false,
  "max_num_threads": 1
}
```
3. run job,
4. job failed with this error on UI:
`No field [runtimefield] could be detected` 

regression job on `responsetime_bigger` as dependency_variable also fails with the same error, but was successfully to run if using `responsetime`.

stack trace is similar like this:
```

	"field [responsetime] has unsupported type [text]. Supported types are [boolean, byte, double, float, half_float, integer, long, scaled_float, short, unsigned_long]."
​
​
​
The error happens after reindex
Stack trace
​
[2020-12-02T14:56:03,301][INFO ][o.e.x.m.a.TransportStartDataFrameAnalyticsAction] [] [ff] Starting data frame analytics from state [null]
[2020-12-02T14:56:03,407][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [] [ff] Creating destination index [ff]
[2020-12-02T14:56:03,410][INFO ][o.e.c.m.MetadataCreateIndexService] [] [ff] creating index, cause [api], templates [], shards [1]/[1]
[2020-12-02T14:56:03,613][INFO ][o.e.x.m.d.DataFrameAnalyticsManager] [] [ff] Started reindexing
[2020-12-02T14:56:03,646][INFO ][o.e.c.m.MetadataMappingService] [] [ff/YlmUcLJgRYKydboe0cHx_g] update_mapping [_doc]
[2020-12-02T14:56:07,440][ERROR][o.e.x.m.d.DataFrameAnalyticsTask] [] [ff] Setting task to failed
org.elasticsearch.ElasticsearchStatusException: field [responsetime] has unsupported type [text]. Supported types are [boolean, byte, double, float, half_float, integer, long, scaled_float, short, unsigned_long].
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:79) ~[?:?]
	at org.elasticsearch.xpack.ml.dataframe.extractor.ExtractedFieldsDetector.checkFieldsHaveCompatibleTypes(ExtractedFieldsDetector.java:328) ~[?:?]
	at org.elasticsearch.xpack.ml.dataframe.extractor.ExtractedFieldsDetector.detect(ExtractedFieldsDetector.java:90) ~[?:?]
	at org.elasticsearch.xpack.ml.dataframe.extractor.DataFrameDataExtractorFactory.lambda$createForDestinationIndex$1(DataFrameDataExtractorFactory.java:121) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.dataframe.extractor.ExtractedFieldsDetectorFactory.lambda$create$0(ExtractedFieldsDetectorFactory.java:82) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.ml.dataframe.extractor.ExtractedFieldsDetectorFactory.getCardinalitiesForFieldsWithConstraints(ExtractedFieldsDetectorFactory.java:117) ~[?:?]
	at org.elasticsearch.xpack.ml.dataframe.extractor.ExtractedFieldsDetectorFactory.lambda$create$2(ExtractedFieldsDetectorFactory.java:93) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:107) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:175) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:169) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:89) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:104) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:98) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:107) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:175) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:169) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesIndexAction$AsyncShardsAction$1.handleResponse(TransportFieldCapabilitiesIndexAction.java:277) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesIndexAction$AsyncShardsAction$1.handleResponse(TransportFieldCapabilitiesIndexAction.java:267) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1106) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1184) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1164) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:52) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:43) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:27) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
​
```

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
When we create the destination index for a data frame analytics job,
we merge the mappings across the source indices and copy them over
to the dest index. In order to support mapped runtime fields,
this commit adds to that merging and copying over the runtime
mappings.

Fixes #65854

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/dataframe/MappingsMergerTests.java [hunk 1]
```diff
@@ -99,8 +100,145 @@ public void testMergeMappings_GivenIndicesWithDifferentMappingsButNoConflicts()
...
+        assertThat(mappingsAsMap.containsKey("dynamic"), is(true));
+        assertThat(mappingsAsMap.containsKey("runtime"), is(true));
+
+        assertThat(mappingsAsMap.get("dynamic"), is(false));
+
+        @SuppressWarnings("unchecked")
+        Map<String, Object> fieldMappings = (Map<String, Object>) mappingsAsMap.get("runtime");
+
+        assertThat(fieldMappings.size(), equalTo(3));
+        assertThat(fieldMappings.keySet(), containsInAnyOrder("field_1", "field_2", "field_3"));
```
Comment (droberts195) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/dataframe/MappingsMergerTests.java:174]: If you flipped the order of these assertions you'd get better diagnostics if the test ever failed.  As it stands you'll just get something like `expected:3 but was: 4`, which isn't enough to fix it.

There are several other places in the changes where the same thing applies.

**Review by droberts195 — APPROVED** [review]
LGTM, although I left one suggestion about diagnostics for future test failures

**Review by benwtrent — APPROVED** [review]
