### PR TITLE
Ensure integer sorts are rewritten to long sorts for BWC indexes

### LINKED ISSUE #139127: [CI] IndexSortUpgradeIT testIndexSortForNumericTypes {upgradedNodes=1} failing
**Build Scans:**
- [elasticsearch-periodic #11545 / 9.0.8_bwc](https://gradle-enterprise.elastic.co/s/i7oivpy32laec)
- [elasticsearch-pull-request #108024 / 8.19.9_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/all5yqnprncrc)
- [elasticsearch-pull-request #108024 / 9.1.9_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/lovrvuy4emmyi)
- [elasticsearch-pull-request #108024 / pr-upgrade-part-6](https://gradle-enterprise.elastic.co/s/uc54wq6pjcqii)
- [elasticsearch-pull-request #108024 / 9.2.3_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/mlvc3t3oiasyy)
- [elasticsearch-pull-request #107999 / 9.3.0_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/tn2hvsx4dtqt6)

**Reproduction Line:**
```
./gradlew ":qa:rolling-upgrade:v9.0.8#bwcTest" -Dtests.class="org.elasticsearch.upgrades.IndexSortUpgradeIT" -Dtests.method="testIndexSortForNumericTypes {upgradedNodes=1}" -Dtests.seed=68E68168E2A2B4AD -Dtests.bwc=true -Dtests.locale=yrl -Dtests.timezone=Etc/GMT+9 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.IndexSortUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testIndexSortForNumericTypes%20%7BupgradedNodes%3D1%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40161], URI [/index_int/_search], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"illegal_argument_exception","reason":"Can't sort on field [int_field]; the field has incompatible sort types: [INT] and [LONG] across shards!"}},"status":400}
```

**Issue Reasons:**
- [main] 6 failures in test testIndexSortForNumericTypes {upgradedNodes=1} (0.7% fail rate in 910 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.4% fail rate in 139 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139128: [CI] IndexSortUpgradeIT testIndexSortForNumericTypes {upgradedNodes=2} failing
**Build Scans:**
- [elasticsearch-periodic #11545 / 9.0.8_bwc](https://gradle-enterprise.elastic.co/s/i7oivpy32laec)
- [elasticsearch-pull-request #108024 / 8.19.9_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/all5yqnprncrc)
- [elasticsearch-pull-request #108024 / 9.1.9_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/lovrvuy4emmyi)
- [elasticsearch-pull-request #108024 / pr-upgrade-part-6](https://gradle-enterprise.elastic.co/s/uc54wq6pjcqii)
- [elasticsearch-pull-request #108024 / 9.2.3_part_6_bwc-snapshots](https://gradle-enterprise.elastic.co/s/mlvc3t3oiasyy)

**Reproduction Line:**
```
./gradlew ":qa:rolling-upgrade:v9.0.8#bwcTest" -Dtests.class="org.elasticsearch.upgrades.IndexSortUpgradeIT" -Dtests.method="testIndexSortForNumericTypes {upgradedNodes=1}" -Dtests.seed=68E68168E2A2B4AD -Dtests.bwc=true -Dtests.locale=yrl -Dtests.timezone=Etc/GMT+9 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.IndexSortUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testIndexSortForNumericTypes%20%7BupgradedNodes%3D2%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40161], URI [/index_int/_search], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"illegal_argument_exception","reason":"Can't sort on field [int_field]; the field has incompatible sort types: [INT] and [LONG] across shards!"}},"status":400}
```

**Issue Reasons:**
- [main] 5 failures in test testIndexSortForNumericTypes {upgradedNodes=2} (0.6% fail rate in 909 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by romseygeek**
Older indexes used long sorts for integer fields, and we need to ensure that
sorts against these fields do not conflict.  Recent refactoring in 
IndexNumericSortField missed a case where this could happen.

Closes #139127
Closes #139128

### CODE REVIEW

**Comment by john-wagster** [comment]
Fixes: https://github.com/elastic/elasticsearch/pull/139293

**Comment by benwtrent** [comment]
@romseygeek I think this might also fix this issue: https://github.com/elastic/elasticsearch/issues/139275

We saw this NPE on an index created before (thus sorting on long) and then sorting with a new index (sorting on int).

**Comment by benwtrent** [comment]
Consequently, what do you think about backporting to 9.2.x (and maybe 9.1.x?)?

**Comment by romseygeek** [comment]
This specific bug is only in 9.3 I think, although the fix may also clean up other issues.  There have been several changes in IndexNumericFieldData which means this won't be trivial to backport.

**Comment by romseygeek** [comment]
> which means this won't be trivial to backport.

To be clear, that doesn't mean we shouldn't do it!  Just that it probably needs to be a separate PR and a different test setup.

File: server/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java [hunk 1]
```diff
@@ -684,4 +688,39 @@ public void testIsBottomSortShardDisjoint() throws Exception {
     protected FieldSortBuilder fromXContent(XContentParser parser, String fieldName) throws IOException {
         return FieldSortBuilder.fromXContent(parser, fieldName);
     }
+
+    public void testIntRewritesToLong() throws IOException {
```
Comment (mayya-sharipova) [inline server/src/test/java/org/elasticsearch/search/sort/FieldSortBuilderTests.java:692]: very nice test!

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java [hunk 2]
```diff
@@ -166,35 +167,42 @@ public SortField sortField(
...
-        SortedNumericSortField numericSortField = (SortedNumericSortField) sortField;
-        SortedNumericSortField rewrittenSortField = new SortedNumericSortField(
-            sortField.getField(),
-            SortField.Type.LONG,
-            sortField.getReverse(),
-            numericSortField.getSelector()
-        );
+
         XFieldComparatorSource longSource = comparatorSource(NumericType.LONG, missingValue, sortMode, nested);
+        if (sortField instanceof SortedNumericSortField snsf) {
```
Comment (mayya-sharipova) [inline server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:187]: For my education, under what condition index sort is not instance of SortedNumericSortField?

Is it something new?

**Review by mayya-sharipova — APPROVED** [review]
@romseygeek Thanks for a fix!

**Comment by mayya-sharipova** [comment]
> I think this might also fix this issue: https://github.com/elastic/elasticsearch/issues/139275

This specific issue originally involved scroll, so I am not sure. 
I will need to check this.

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java (hunk 2 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:187]: Index sorts are always SortedNumericSortField instances, but query-time sorts now generally use custom comparators to pick up some performance improvements that are not in a released lucene version, so they are plain SortField instances.

**Comment by romseygeek** [comment]
I'll backport the test to 9.2 and see if it surfaces any issues.

**Comment by romseygeek** [comment]
I opened https://github.com/elastic/elasticsearch/pull/139358 to backport the tests, which seem to pass at the moment so I think #139275 must be a different issue.
