### PR TITLE
ESQL: make cidr_match foldable

### LINKED ISSUE #105376: [ES|QL] Better error message on invalid string for cidr_match
### Elasticsearch Version

8.13.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error:

```
ql_illegal_argument_exception\n\tRoot causes:\n\t\tql_illegal_argument_exception: Should not fold expression
```

is thrown on the following queries:

```
row var = cidr_match(to_ip(\"127.0.0.1\"), \"a\")
row cidr_match(to_ip(\"127.0.0.1\"), \"a\")
```

As a user, the error message is not easy to decypher. It would be nice to improve it to something like "invalid cidr_block string provided as arg #" or something even better. 

### Steps to Reproduce

See above.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/105376
Creates two new ESQL specific base classes for functions, eliminating boilerplate code from many concrete function implementations.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/EsqlScalarFunction.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+    protected EsqlScalarFunction(Source source) {
+        super(source);
+    }
+
+    protected EsqlScalarFunction(Source source, List<Expression> fields) {
+        super(source, fields);
+    }
+
+    @Override
+    public Object fold() {
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/EsqlScalarFunction.java:29]: Do you think this should be final? I'll be it can't be final now, but maybe it can be one day?

**Review by nik9000 — APPROVED** [review]
