### PR TITLE
Fixes DenseVectorFieldIndexTypeUpdateIT release tests

### LINKED ISSUE #132331: [CI] DenseVectorFieldIndexTypeUpdateIT class failing
**Build Scans:**
- [elasticsearch-periodic #9734 / release-tests](https://gradle-enterprise.elastic.co/s/blbfopryg2a7q)
- [elasticsearch-pull-request #83988 / part-1](https://gradle-enterprise.elastic.co/s/n44t75biralj6)
- [elasticsearch-periodic #9727 / release-tests](https://gradle-enterprise.elastic.co/s/uur4cwkyxc3qu)
- [elasticsearch-pull-request #83919 / part-1](https://gradle-enterprise.elastic.co/s/ij3wkpf5mvnvk)
- [elasticsearch-pull-request #83916 / part-1](https://gradle-enterprise.elastic.co/s/jwbqsltgs4r6e)
- [elasticsearch-periodic #9720 / release-tests](https://gradle-enterprise.elastic.co/s/xvhovczossdla)
- [elasticsearch-pull-request #83863 / part-1](https://gradle-enterprise.elastic.co/s/o2lx2qy6ovbym)
- [elasticsearch-periodic #9713 / release-tests](https://gradle-enterprise.elastic.co/s/sbh64dk6mclfq)
- [elasticsearch-pull-request #83733 / part-1](https://gradle-enterprise.elastic.co/s/szlu7h7526uhs)
- [elasticsearch-periodic #9706 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/p2xai52jvyfmm)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT.testDenseVectorMappingUpdate {initialType=hnsw updateType=bbq_disk}" -Dtests.seed=892BF31343223917 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ebu -Dtests.timezone=Pacific/Pitcairn -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Unknown vector index options type [bbq_disk] for field [vector]
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 110 failures in class org.elasticsearch.index.mapper.vectors.DenseVectorFieldIndexTypeUpdateIT (15.8% fail rate in 696 executions)
- [main] 8 failures in step release-tests (88.9% fail rate in 9 executions)
- [main] 57 failures in step part-1 (17.1% fail rate in 334 executions)
- [main] 29 failures in step part1 (20.6% fail rate in 141 executions)
- [main] 4 failures in step part-1-fips (25.0% fail rate in 16 executions)
- [main] 2 failures in step openjdk21_checkpart1_java-fips-matrix (25.0% fail rate in 8 executions)
- [main] 2 failures in step openjdk24_checkpart1_java-matrix (25.0% fail rate in 8 executions)
- [main] 9 failures in pipeline elasticsearch-periodic (100.0% fail rate in 9 executions)
- [main] 59 failures in pipeline elasticsearch-pull-request (17.9% fail rate in 329 executions)
- [main] 29 failures in pipeline elasticsearch-intake (20.6% fail rate in 141 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by carlosdelest**
I forgot to remove `disk_bbq` from the list that contains the types to test. This fixes it so release tests work correctly.

Closes https://github.com/elastic/elasticsearch/issues/132331

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public DenseVectorFieldIndexTypeUpdateIT(@Name("initialType") String initialType
     @ParametersFactory
     public static Collection<Object[]> params() {
         List<String> types = new ArrayList<>(
-            List.of("flat", "int8_flat", "int4_flat", "bbq_flat", "hnsw", "int8_hnsw", "int4_hnsw", "bbq_hnsw", "bbq_disk")
+            List.of("flat", "int8_flat", "int4_flat", "bbq_flat", "hnsw", "int8_hnsw", "int4_hnsw", "bbq_hnsw")
```
Comment (john-wagster) [inline server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java:55]: so just for my own knowledge does this get added back after we release?

**Review by john-wagster — APPROVED** [review]
lgtm

File: server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java (hunk 1 above)
Comment (carlosdelest) [reply server/src/internalClusterTest/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldIndexTypeUpdateIT.java:55]: After we release, the corresponding `DenseVectorFieldMapper.IVF_FORMAT.isEnabled()` will always be true, so both snapshot and release tests will include it (see the following line where it is conditionally added depending on the capability):

```java
        if (DenseVectorFieldMapper.IVF_FORMAT.isEnabled()) {
            types.add("bbq_disk");
        }
```
