### PR TITLE
Move cluster.routing.allocation.same_shard.host setting to new settings infrastructure

### LINKED ISSUE #20045: Can't set cluster.routing.allocation.same_shard.host
**Elasticsearch version**:
Elasticsearch 5.0.0-alpha4

Setting `cluster.routing.allocation.same_shard.host` (in elasticsearch.yml or command line arguments) throws exception and prevents node to start.

```
[2016-08-18 13:55:11,399][INFO ][node                     ] [Phineas T. Horton] version[5.0.0-alpha4], pid[82298], build[3f5b994/2016-06-27T16:23:46.861Z], OS[Mac OS X/10.11.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_60/25.60-b23]
[2016-08-18 13:55:11,400][INFO ][node                     ] [Phineas T. Horton] initializing ...
[2016-08-18 13:55:12,213][INFO ][plugins                  ] [Phineas T. Horton] modules [percolator, lang-mustache, lang-painless, reindex, aggs-matrix-stats, lang-expression, ingest-common, lang-groovy], plugins [analysis-kuromoji, x-pack]
Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [cluster.routing.allocation.same_shard.host] did you mean any of [cluster.routing.allocation.balance.shard, cluster.routing.allocation.balance.threshold, cluster.routing.allocation.disk.watermark.high, cluster.routing.allocation.disk.watermark.low, cluster.routing.allocation.total_shards_per_node]?
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:270)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138)
	at org.elasticsearch.node.Node.<init>(Node.java:236)
	at org.elasticsearch.node.Node.<init>(Node.java:173)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:250)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:96)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:91)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:63)
```

### PR DESCRIPTION
**Pull request by masaruh**
Fixes #20045

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/SameShardAllocationDecider.java [hunk 1]
```diff
@@ -45,15 +47,22 @@
 
     public static final String NAME = "same_shard";
 
-    public static final String SAME_HOST_SETTING = "cluster.routing.allocation.same_shard.host";
+    public static final Setting<Boolean> CLUSTER_ROUTING_ALLOCATION_SAME_HOST_SETTING =
+        Setting.boolSetting("cluster.routing.allocation.same_shard.host", false,
+            Setting.Property.Dynamic, Setting.Property.NodeScope);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/SameShardAllocationDecider.java]: I'm unsure if this setting should be dynamic.

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/SameShardAllocationDecider.java]: As this setting should usually be only set once, it is probably simpler to leave it non-dynamic (as @jasontedor suggested and as it was before this PR). In case where this must absolutely be updated on a production cluster, rolling restart (of master nodes) with config update is always possible.

Comment (masaruh) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/SameShardAllocationDecider.java]: Right. I wondered if it should be dynamic or not.
The reason I made it dynamic is [document](https://www.elastic.co/guide/en/elasticsearch/reference/master/shards-allocation.html) says it's dynamic.
(and thought making it dynamic maybe useful)

I'll make it non-dynamic.

**Comment by masaruh** [comment]
@jasontedor @ywelsch Made it static (and rebased). Can you review it again?

**Comment by s1monw** [comment]
LGTM

**Comment by masaruh** [comment]
Thanks @s1monw.
