### PR TITLE
[Transform] Implement the ability to preview the existing transform

### LINKED ISSUE #76427: [Transform] Preview should work against an existing id
If a continuous transform has failed, it is a useful troubleshooting step to be able to preview it. This gives confidence that the underlying source data has not dramatically changed. [could have]

Currently the `_preview` only works against a supplied configuration. It would be good to extend this to allow it to run against an existing transform.

Other side benefits: The UI already does this, so would benefit from code simplification. And it would be consistent with datafeed preview.

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR adds the ability to perform transform preview using already existing transform config.
The user does not have to provide the full config in the preview request anymore.
Instead, they can just provide transform id using `id` param.

Closes https://github.com/elastic/elasticsearch/issues/76427

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java [hunk 1]
```diff
@@ -92,20 +111,36 @@ public static Request fromXContent(final XContentParser parser) throws IOExcepti
 
         @Override
         public ActionRequestValidationException validate() {
+            // TODO: Make sure ids do not clash
+
+
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java:116]: I am not 100% sure that is a big issue. I don't think the `_transforms/<id>/_preview` should allow a body at all. Consequently, there shouldn't be any IDs clashing.

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/transform/preview_transforms.yml [hunk 2]
```diff
@@ -204,6 +289,35 @@ setup:
...
+"Test preview without id and body":
+  - do:
+      catch: /Either transform id param or request body is required/
+      transform.preview_transform: {}
+
+---
+"Test preview with both id and body":
+  - do:
+      catch: /transform id param \[non-existent-transform\] does not match request body id \[null\]/
+      transform.preview_transform:
```
Comment (benwtrent) [inline x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/transform/preview_transforms.yml:309]: We should simply always disallow this. It should be an xor between the user providing the ID vs providing a config.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java [hunk 3]
```diff
@@ -34,9 +37,27 @@ public String getName() {
...
+        if (hasId && hasContent) {
+            String idFromParam = restRequest.param(TransformField.ID.getPreferredName());
+            String idFromBody = (String) restRequest.contentParser().map().get(TransformField.ID.getPreferredName());
+            if (idFromParam.equals(idFromBody) == false) {
+                throw new ElasticsearchParseException(
+                    "transform id param [" + idFromParam + "] does not match request body id [" + idFromBody + "]");
+            }
+            XContentParser parser = restRequest.contentParser();
+            request = PreviewTransformAction.Request.fromXContent(parser);
+        } else if (hasId) {
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java:52]: This seems way too complicated. I don't see the benefit. Either the user is checking a transform that already exists or they are not.

Besides, for `preview` we don't care about the ID provided in the body.

Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java:52]: Take a look at how Data frame analytics handles this: 

https://github.com/elastic/elasticsearch/blob/8384c0d67816758621aa3b595f8fd2a3b2521cfc/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/dataframe/RestPreviewDataFrameAnalyticsAction.java#L28

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java [hunk 4]
```diff
@@ -52,19 +52,38 @@ private PreviewTransformAction() {
...
         }
 
         public static Request fromXContent(final XContentParser parser) throws IOException {
             Map<String, Object> content = parser.map();
+            if (content.size() == 1 && content.containsKey(TransformField.ID.getPreferredName())) {
+                // The request only contains transform id so instead of parsing TransformConfig (which is pointless in this case),
+                // let's just fetch the transform config by id later on.
+                String transformId = (String) content.get(TransformField.ID.getPreferredName());
+                return new Request(transformId);
+            }
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java:86]: This seems really strange to me. It should be:

 - Full config in the body of the request
 - OR just the ID in the API.

I am not sure all this special handling in the transport action is even required as the REST layer could do the simple action of grabbing the transform via the ID if they hit that API endpoint.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java [hunk 5]
```diff
@@ -24,7 +25,9 @@
 
     @Override
     public List<Route> routes() {
-        return List.of(new Route(POST, TransformField.REST_BASE_PATH_TRANSFORMS + "_preview"));
+        return List.of(
+            new Route(POST, TransformField.REST_BASE_PATH_TRANSFORMS + "_preview"),
+            new Route(POST, TransformField.REST_BASE_PATH_TRANSFORMS_BY_ID + "_preview"));
```
Comment (hendrikmuhs) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java:35]: I think `_transform/id/_preview` is conceptually a _GET_ request.

Looking at data feeds I see both (_POST_, _GET_) [specified](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-preview-datafeed.html) for preview (user friendliness?). We should be consistent.

File: x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/transform/preview_transforms.yml (hunk 2 above)
Comment (hendrikmuhs) [reply x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/transform/preview_transforms.yml]: +1, if I read the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-preview-datafeed.html) correctly, it sounds like a body is disallowed if id is given as part of the path.

Note: The id in the body - for the ordinary preview - is allowed for convenience. Same for dest, both id and dest are ignored in this case. I like to keep this convenience for users that switch back and forth between `PUT` and `_preview` and/or copy pasting configs into the console.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java (hunk 5 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java:35]: 2nd thought: I suggest to think about separate endpoints (rest and transport), the 2 "modes" are completely different and force you to program with modes, introducing `if`'s here and there. This is not straight forward and is more error-prone. I think separation is cleaner.

**Review by hendrikmuhs — COMMENTED** [review]
Note: I reviewed before the last commit, so probably some of my comments are outdated.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java (hunk 5 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java:35]: update: I like the separation in _prepareRequest_.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java (hunk 4 above)
Comment (przemekwitek) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java]: BTW, I've just noticed there is no HLRC method for Data Frame Analytics preview. Is it expected?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java (hunk 5 above)
Comment (przemekwitek) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java]: > Looking at data feeds I see both (POST, GET) specified for preview (user friendliness?). We should be consistent.

Done, I've added the missing `GET` paths.

Comment (przemekwitek) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java]: > 2nd thought: I suggest to think about separate endpoints (rest and transport), the 2 "modes" are completely different and force you to program with modes, introducing if's here and there. This is not straight forward and is more error-prone. I think separation is cleaner.

I think after I implemented changes suggested by Ben separating endpoints is not needed anymore.
WDYT?

Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/rest/action/RestPreviewTransformAction.java]: I agree, the separation in `prepareRequest` looks simple enough to me. I made the comment before you reverted the transport changes.

**Review by hendrikmuhs — COMMENTED** [review]
LGTM, I have 1 more request: can you add a test in `transform/qa/multi-cluster-tests-with-security/` to assert that bob is not able to preview by id the transform that joe created (or any other user combo)?

(I mean of course w.r.t. to data access rights: bob can preview joe's transform, but should not get access to data which only joe is allowed to retrieve)

**Comment by przemekwitek** [comment]
> LGTM, I have 1 more request: can you add a test in `transform/qa/multi-cluster-tests-with-security/` to assert that bob is not able to preview by id the transform that joe created (or any other user combo)?

Done, I've added an assertion to an existing test.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java (hunk 4 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/PreviewTransformAction.java]: @przemekwitek there is probably no HLRC in 8.0.0 as the HLRC is not supported in 8.0. I am thinking its in 7.x.

**Review by benwtrent — APPROVED** [review]

**Review by hendrikmuhs — APPROVED** [review]
LGTM
