### PR TITLE
Don't override originalQuery with request filters

### LINKED ISSUE #15689: Type name is highlighted when searching in specific type
I have a `restaurant` index, and a type named `japanese`. So I use the following URL for searching:
`http: //localhost:9200/restaurant/japanese/_search`

And my query body is:

```
{
    "query": {
        "match": {
            "title": {
                "query": "sushi"
            }
        }
    },
    "highlight": {
        "fragment_size": 70,
        "no_match_size": 70,
        "number_of_fragments": 1,
        "require_field_match": false,
        "fields": {
            "title": {},
            "description": {}
        }
    }
}
```

It just search through the title field with 'sushi', but the type name 'japanese' is highlighted as well.
Is this a BUG, or did I do something wrong?

ES version is 2.0.0.

### PR DESCRIPTION
**Pull request by nik9000**
These filters leak into highlighting and probably other places and cause things like the type name to be highlighted when using requireFieldMatch=false. We could have special hacks to keep them out of highlighting but it feals better to keep them out of any variable named "originalQuery".

Closes #15689

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java [hunk 1]
```diff
@@ -182,11 +182,10 @@ protected ShardValidateQueryResponse shardOperation(ShardValidateQueryRequest re
             searchContext.preProcess();
 
             valid = true;
-            if (request.explain()) {
-                explanation = searchContext.parsedQuery().query().toString();
-            }
             if (request.rewrite()) {
                 explanation = getRewrittenQuery(searcher.searcher(), searchContext.query());
+            } else if (request.explain()) {
+                explanation = searchContext.filteredQuery().query().toString();
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/indices/validate/query/TransportValidateQueryAction.java]: Sorry for moving the code around here. The big change is using `filteredQuery` instead of `parsedQuery`.

**Comment by nik9000** [comment]
@javanna is this something you can review? I'm hunting reviewers....

File: core/src/test/java/org/elasticsearch/search/highlight/HighlighterSearchIT.java [hunk 2]
```diff
@@ -2533,6 +2534,44 @@ public void testPostingsHighlighterManyDocs() throws Exception {
...
+        indexRandom(true, client().prepareIndex("test", "typename").setSource("foo", "test japanese"));
+
+        for (String highlighter: new String[] {"plain", "fvh", "postings"}) {
+            SearchResponse response = client().prepareSearch("filtered_alias").setTypes("typename").setQuery(matchQuery("foo", "test"))
+                    .highlighter(new HighlightBuilder().field("foo").highlighterType(highlighter).requireFieldMatch(false)).get();
+            assertHighlight(response, 0, "foo", 0, 1, equalTo("<em>test</em> japanese"));
+        }
+    }
+
+
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/search/highlight/HighlighterSearchIT.java]: one too many new line? :)

**Comment by javanna** [comment]
I found this a bit scary at first as it adds a new method to be used to retrieve the query that we previously relied one (the filtered one) while the default one (parsedQuery) is not filtered anymore. That said I looked at where we call what and it seems ok, also if tests are green I suppose we are good :) LGTM then

**Comment by nik9000** [comment]
> a bit scary

Yeah! I believe it! Its weird to have these three, but I'm not sure of a better way to do this. I think we lucked out that this worked properly before the query/filter merger.

**Comment by nik9000** [comment]
Backporting.....

**Comment by nik9000** [comment]
I'm so not used to maven....

**Comment by nik9000** [comment]
And cherry-picked to 2.x: 6ddd233a0283e12634a89a566f34ab645c4dba20 53d41a19f28448ec737dcf41595207c04bd565a0
