### PR TITLE
Fix tests in LegacyGeoShapeWithDocValuesQueryTests

### LINKED ISSUE #112438: [CI] LegacyGeoShapeWithDocValuesQueryTests testIndexPointsFromLine failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3914 / ubuntu-2004-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/kfnynztnhzw7u)
- [elasticsearch-pull-request #29880 / part-2-fips](https://gradle-enterprise.elastic.co/s/wk3b46mczqnps)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:spatial:test" --tests "org.elasticsearch.xpack.spatial.index.query.LegacyGeoShapeWithDocValuesQueryTests.testIndexPointsFromLine" -Dtests.seed=2CC260A41BF245F -Dtests.locale=ar-OM -Dtests.timezone=America/Vancouver -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testIndexPointsFromLine'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.spatial.index.query.LegacyGeoShapeWithDocValuesQueryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 2 hits but 3 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 failures in test testIndexPointsFromLine (9.1% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #112464: [CI] LegacyGeoShapeWithDocValuesQueryTests testIndexPointsFromPolygon failing
**Build Scans:**
- [elasticsearch-periodic #3953 / openjdk17_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/74p76er4uqoua)
- [elasticsearch-pull-request #29971 / part-2](https://gradle-enterprise.elastic.co/s/nrllh3exonuxs)
- [elasticsearch-pull-request #29942 / part-2](https://gradle-enterprise.elastic.co/s/qullwj7drmefe)
- [elasticsearch-periodic-platform-support #3920 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/6vrbna4veyzfq)
- [elasticsearch-periodic-platform-support #3920 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/kvimdcrz6o7d6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:spatial:test" --tests "org.elasticsearch.xpack.spatial.index.query.LegacyGeoShapeWithDocValuesQueryTests.testIndexPointsFromPolygon" -Dtests.seed=1AC225F553313E92 -Dtests.locale=sk -Dtests.timezone=Africa/Windhoek -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testIndexPointsFromPolygon'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.spatial.index.query.LegacyGeoShapeWithDocValuesQueryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Count is 3 hits but 5 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testIndexPointsFromPolygon
- [main] 5 failures in test testIndexPointsFromPolygon (3.3% fail rate in 153 executions)
- [main] 2 failures in step part-2 (5.7% fail rate in 35 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (5.9% fail rate in 34 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by iverase**
Similar to what we did in https://github.com/elastic/elasticsearch/issues/86118, lets filter out points with longitude 180.

fixes https://github.com/elastic/elasticsearch/issues/112464
fixes https://github.com/elastic/elasticsearch/issues/112438

### CODE REVIEW

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/query/LegacyGeoShapeWithDocValuesQueryTests.java [hunk 1]
```diff
@@ -220,4 +221,8 @@ public void testFieldAlias() throws IOException {
 
         assertHitCount(client().prepareSearch(defaultIndexName).setQuery(geoShapeQuery("alias", multiPoint)), 1L);
     }
+
+    protected boolean ignoreLons(double[] lons) {
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/query/LegacyGeoShapeWithDocValuesQueryTests.java:225]: Took me a while to see where this was actually used. But I found it!

**Review by craigtaverner — APPROVED** [review]
LGTM
