### PR TITLE
Backport to 1.7 - Snapshot info should contain version of elasticsearch that created the snapshot

### LINKED ISSUE #11980: Snapshot Info doesn't indicate elastic search version
Calling 

GET /_snapshot/<repo>/<snapshot>

includes various information but not the elasticsearch version.

This is useful in a number of scenarios.  Although elasticsearch prevents restores between index versions if the snapshot.version > cluster.version, this information would allow client side checks i.e. the client could avoid having to check compatibility by making a restore and noticing it fails.

### PR DESCRIPTION
**Pull request by imotov**
Backport of #11985 to 1.7

This information was stored with the snapshot but wasn't available on the interface. Knowing the version of elasticsearch that created the snapshot can be useful to determine the minimal version of the cluster that is required in order to restore this snapshot.

Closes #11980

### CODE REVIEW

File: src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java [hunk 1]
```diff
@@ -260,6 +278,9 @@ public void readFrom(StreamInput in) throws IOException {
         } else {
             shardFailures = ImmutableList.of();
         }
+        if(in.getVersion().onOrAfter(Version.V_1_7_0)) {
```
Comment (dakrone) [inline src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java]: Super-minor, but missing a space between `if` and `(` here.

File: src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java [hunk 2]
```diff
@@ -279,6 +300,9 @@ public void writeTo(StreamOutput out) throws IOException {
         for (SnapshotShardFailure failure : shardFailures) {
             failure.writeTo(out);
         }
+        if(out.getVersion().onOrAfter(Version.V_1_7_0)) {
```
Comment (dakrone) [inline src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java]: Same here.

**Comment by dakrone** [comment]
LGTM, left two bikeshed comments.
