### PR TITLE
[TEST] Replaces flaky breaker IT test with unit test

### LINKED ISSUE #28223: CircuitBreakerServiceIT.testParentChecking failures
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+multijob-unix-compatibility/os=opensuse/191/consoleFull

The failure is not reproducible but seems to only affect 6.1.

```
12:35:56   1> org.elasticsearch.transport.RemoteTransportException: [node_td3][127.0.0.1:39190][indices:data/read/search[phase/query/id]]
12:35:56   1> Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
12:35:56   1> 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:298) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:110) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:420) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.action.search.SearchTransportService$7.messageReceived(SearchTransportService.java:404) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.action.search.SearchTransportService$7.messageReceived(SearchTransportService.java:401) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
12:35:56   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
12:35:56   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
12:35:56   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
12:35:56   1> Caused by: org.elasticsearch.ElasticsearchException: java.util.concurrent.ExecutionException: CircuitBreakingException[[fielddata] Data too large, data for [test] would be [1758/1.7kb], which is larger than the limit of [10/10b]]
12:35:56   1> 	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:74) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource$1.getSortedDocValues(BytesRefFieldComparatorSource.java:87) ~[main/:?]
12:35:56   1> 	at org.apache.lucene.search.FieldComparator$TermOrdValComparator.getLeafComparator(FieldComparator.java:714) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
12:35:56   1> 	at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:180) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
12:35:56   1> 	at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:100) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
12:35:56   1> 	at org.apache.lucene.search.FilterCollector.getLeafCollector(FilterCollector.java:40) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
12:35:56   1> 	at org.elasticsearch.search.query.CancellableCollector.getLeafCollector(CancellableCollector.java:51) ~[main/:?]
12:35:56   1> 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:649) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
12:35:56   1> 	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:186) ~[main/:?]
12:35:56   1> 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:462) ~[lucene-core-7.1.0.jar:7.1.0 84c90ad2c0218156c840e19a64d72b8a38550659 - ubuntu - 2017-10-13 16:12:42]
12:35:56   1> 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:272) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:110) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:420) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.action.search.SearchTransportService$7.messageReceived(SearchTransportService.java:404) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.action.search.SearchTransportService$7.messageReceived(SearchTransportService.java:401) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[main/:?]
12:35:56   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
12:35:56   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
12:35:56   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
12:35:56   1> 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]

12:36:01   2> REPRODUCE WITH: ./gradlew :core:integTest -Dtests.seed=32BD17E618B23F85 -Dtests.class=org.elasticsearch.indices.memory.breaker.CircuitBreakerServiceIT -Dtests.method="testParentChecking" -Dtests.security.manager=true -Dtests.locale=it-CH -Dtests.timezone=Asia/Beirut
```

### PR DESCRIPTION
**Pull request by colings86**
This change remove the `CircuitBreakerIT. testParentChecking` test method which fails intermittently in unexpected ways with a `MemoryCircuitBreakerTests. testBorrowingSiblingBreakerMemory` unit test method which can test the borrowing functionality more directly

Closes #28223

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreakerTests.java [hunk 1]
```diff
@@ -241,4 +243,40 @@ public void testConstantFactor() throws Exception {
...
+
+            double fieldDataUsedBytes = fieldDataCircuitBreaker
+                    .addEstimateBytesAndMaybeBreak(new ByteSizeValue(50, ByteSizeUnit.MB).getBytes(), "should not break");
+            assertEquals(new ByteSizeValue(50, ByteSizeUnit.MB).getBytes(), fieldDataUsedBytes, 0.1);
+            double requestUsedBytes = requestCircuitBreaker.addEstimateBytesAndMaybeBreak(new ByteSizeValue(50, ByteSizeUnit.MB).getBytes(),
+                    "should not break");
+            assertEquals(new ByteSizeValue(50, ByteSizeUnit.MB).getBytes(), requestUsedBytes, 0.1);
+            requestUsedBytes = requestCircuitBreaker.addEstimateBytesAndMaybeBreak(new ByteSizeValue(50, ByteSizeUnit.MB).getBytes(),
+                    "should not break");
+            assertEquals(new ByteSizeValue(100, ByteSizeUnit.MB).getBytes(), requestUsedBytes, 0.1);
```
Comment (jpountz) [inline server/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreakerTests.java]: can we make the error equal to 0 in all above tests?

**Review by jpountz — APPROVED** [review]

**Comment by colings86** [comment]
@jpountz Thanks for the review, I'll merge this as soon as the build is green
