### PR TITLE
[Transform] Retry Destination IndexNotFoundException

### LINKED ISSUE #107263: [Transform] IndexNotFoundException during cluster upgrade
### Description

From: https://github.com/elastic/elasticsearch/issues/107251

While a cluster is upgrading, we see `IndexNotFoundException` for some Transforms.
Example:
```java
[endpoint.metadata_united-default-8.13.0] transform has failed; experienced: [Failed to index documents into destination index due to permanent error: [org.elasticsearch.xpack.transform.transforms.BulkIndexingException: Bulk index experienced [36] failures and at least 1 irrecoverable [org.elasticsearch.index.IndexNotFoundException: no such index [.metrics-endpoint.metadata_united_default]]. Other failures: [RemoteTransportException] message [org.elasticsearch.transport.RemoteTransportException: [<>][<>][indices:data/write/bulk[s]]]; org.elasticsearch.index.IndexNotFoundException: no such index [.metrics-endpoint.metadata_united_default]]].
```

This is likely an eventual consistency issue, and the transform needs to give the index time to become consistently reachable

### PR DESCRIPTION
**Pull request by prwhelan**
An Index can be removed from its previous shard in the middle of a Transform run.  Ideally, this happens as part of the Delete API, and the Transform has already been stopped, but in the case that it isn't, we want to retry the checkpoint.

If the Transform had been stopped, the retry will move the Indexer into a graceful shutdown.

If the Transform had not been stopped, the retry will check if the Index exists or recreate the Index if it does not exist.

This is currently how unattended Transforms work, and this change will make it so regular Transforms can also auto-recover from this error.

Fix #107263

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java [hunk 1]
```diff
@@ -193,7 +193,11 @@ protected void handleBulkResponse(BulkResponse bulkResponse, ActionListener<Bulk
 
         for (BulkItemResponse item : bulkResponse.getItems()) {
             if (item.isFailed()) {
-                deduplicatedFailures.putIfAbsent(item.getFailure().getCause().getClass().getSimpleName(), item);
+                var exception = item.getFailure().getCause().getClass();
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java:196]:
```suggestion
                var exceptionClass = item.getFailure().getCause().getClass();
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinder.java [hunk 2]
```diff
@@ -63,7 +64,7 @@ public static Throwable getFirstIrrecoverableExceptionFromBulkResponses(Collecti
             }
 
             if (unwrappedThrowable instanceof ElasticsearchException elasticsearchException) {
-                if (isExceptionIrrecoverable(elasticsearchException)) {
+                if (isExceptionIrrecoverable(elasticsearchException) && isNotIndexNotFoundException(elasticsearchException)) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinder.java:67]: If we no longer consider `IndexNotFoundException` irrecoverable, could we modify the `isExceptionIrrecoverable` method to reflect that instead of adding the `isNotIndexNotFoundException` method?

Or the distinction is still needed for cases other than bulk responses?

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinderTests.java [hunk 3]
```diff
@@ -157,6 +69,14 @@ public void testGetFirstIrrecoverableExceptionFromBulkResponses() {
         assertNull(ExceptionRootCauseFinder.getFirstIrrecoverableExceptionFromBulkResponses(bulkItemResponses.values()));
     }
 
+    private Map<Integer, BulkItemResponse> bulkItemResponses(Exception... exceptions) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinderTests.java:72]: static?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinder.java (hunk 2 above)
Comment (prwhelan) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinder.java:67]: That is a good question - at least for now I was thinking of just handling it for the destination index? The source index can still fail with IndexNotFoundException (if PIT == null): https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java#L602

I haven't seen this same type of intermittent failure scenario though, where the source index gets relocated to a new shard and the request fails on the old shard, so I'm not sure if we just haven't seen it yet or if search behaves differently where the request will automatically reroute.

Comment (przemekwitek) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/ExceptionRootCauseFinder.java:67]: > I'm not sure if we just haven't seen it yet or if search behaves differently where the request will automatically reroute.

I don't know either unfortunately :(
But since we are going in a direction to make more errors recoverable (and more transforms unattended) it could make sense to make `IndexNotFoundException` recoverable.
But maybe let's not do it in this PR if you don't feel comfortable.
We can leave this PR for dealing with destination index only.
Please make it clear in the PR title/description.

**Review by przemekwitek — APPROVED** [review]
LGTM
