### PR TITLE
Fix Index Deletion during Snapshot Finalization

### LINKED ISSUE #50200: Snapshot Finalization Throws NPE in 7.5
We're seeing the following NPE in Cloud logs:

```
Caused by: java.lang.NullPointerException
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.write(ChecksumBlobStoreFormat.java:226) ~[elasticsearch-7.5.0.jar:7.5.0]
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.writeTo(ChecksumBlobStoreFormat.java:197) ~[elasticsearch-7.5.0.jar:7.5.0]
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.write(ChecksumBlobStoreFormat.java:185) ~[elasticsearch-7.5.0.jar:7.5.0]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$finalizeSnapshot$26(BlobStoreRepository.java:738) ~[elasticsearch-7.5.0.jar:7.5.0]
	at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:45) ~[elasticsearch-7.5.0.jar:7.5.0]
	... 5 more
```

during snapshot finalization. This seems like a bug where the cluster metadata does not contain an index for a name that was just snapshot (the deeper cause is that `clusterMetaData.index(index.getName())` in `BlobStoreRepository` returns `null`). I'm investigating this.

### PR DESCRIPTION
**Pull request by original-brownbear**
With #45689 making it so that index metadata is written
after all shards have been snapshotted we can't delete indices
that are part of the upcoming snapshot finalization any longer
and it is not sufficient to check if all shards of an index have been
snapshotted before deciding that it is safe to delete it.
This change forbids deleting any index that is in the process of being
snapshot to avoid issues during snapshot finalization.

Relates #50200 (doesn't fully fix yet because we're not fixing the `partial=true` snapshot case here

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -1520,23 +1520,10 @@ public void clusterStateProcessed(String source, ClusterState oldState, ClusterS
...
-                } else {
-                    for (ObjectObjectCursor<ShardId, SnapshotsInProgress.ShardSnapshotStatus> shard : entry.shards()) {
-                        Index index = shard.key.getIndex();
-                        if (indicesToCheck.contains(index)
-                            && shard.value.state().completed() == false
-                            && currentState.getMetaData().index(index) != null) {
-                            indices.add(index);
-                        }
-                    }
+            for (IndexId index : entry.indices()) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Admittedly this makes it a little "harder" to delete an index, but I don't see it as much of an issue relative to the complication it saves. If we don't do it this way, we'd have to add another step to write index metadata per index (once all the shards for that index have sucessfull been snapshotted) to the state machine which doesn't seem worth it?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: 👍 I don't think this weakens anything meaningful, since the order in which indices are snapshotted isn't specified. The existing behaviour seems overly heroic.

**Review by DaveCTurner — DISMISSED** [review]
LGTM

**Review by ywelsch — CHANGES_REQUESTED** [review]
I think we should not do this. The reason this functionality is in place (allowing deletes during partial snapshots) is that it allows background snapshots while not interfering with user-level actions such as deletes. Note that we discussed this at the time here: https://github.com/elastic/elasticsearch/issues/16321

**Comment by original-brownbear** [comment]
@ywelsch makes sense. Are you ok with this behavior for non-partial snapshots though?
If so, I would just fix the finalization of partial snapshots in such a way that missing metadata in the end is just handled as shard failures for the deleted indices. WDYT?

**Comment by ywelsch** [comment]
> Are you ok with this behavior for non-partial snapshots though?

yes, I think that's ok, at least to get a quick fix out.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -1510,7 +1510,7 @@ public void clusterStateProcessed(String source, ClusterState oldState, ClusterS
     }
 
     /**
-     * Returns the indices that are currently being snapshotted (with partial == false) and that are contained in the indices-to-check set.
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Can you restore the comment here?

**Review by ywelsch — APPROVED** [review]
We'll address partial snapshots in a follow-up. LGTM

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Sure done :)

**Comment by original-brownbear** [comment]
@ywelsch `7.5.1` here now right?

**Comment by ywelsch** [comment]
Let's backport to 7.5 branch for now, and have a separate discussion whether it makes it to 7.5.1
