### PR TITLE
Unmute docker tests, add more logging and increase startup timeout

### LINKED ISSUE #116147: [CI] DockerTests test021InstallPlugin failing
**Build Scans:**
- [elasticsearch-periodic-packaging #7679 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/jf3klwrj53zlq)
- [elasticsearch-periodic-packaging #7661 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ymhwl4aqy5cqm)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test021InstallPlugin),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker exec --tty abea1f3fec79ff4153f1b923d54d14b20c63e0944b9a20fb100eb83121408e97 /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///analysis-icu.zip]
   result: exitCode = [137] stdout = [-> Installing file:///analysis-icu.zip
-> Downloading file:///analysis-icu.zip

[                                                 ] 1%?? 
[>                                                ] 2%?? 
[>                                                ] 3%?? 
[=>                                               ] 4%?? 
[=>                                               ] 5%?? 
[==>                                              ] 6%?? 
[==>                                              ] 7%?? 
[===>                                             ] 8%?? 
[===>                                             ] 9%?? 
[====>                                            ] 10%?? 
[====>                                    
[truncated]
```

**Issue Reasons:**
- [8.17] 2 failures in test test021InstallPlugin (0.8% fail rate in 238 executions)
- [8.17] 2 failures in pipeline elasticsearch-periodic-packaging (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116636: [CI] DockerTests test012SecurityCanBeDisabled failing
**Build Scans:**
- [elasticsearch-periodic-packaging #9038 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/h5osydehvk4ws)
- [elasticsearch-periodic-packaging #9038 / rocky-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/meaxclosh2ac4)
- [elasticsearch-periodic-packaging #9038 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ciiq56kfn7ctm)
- [elasticsearch-periodic-packaging #9038 / almalinux-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/pv32xujdkjulo)
- [elasticsearch-periodic-packaging #9038 / rhel-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/g6huygoar4bmi)
- [elasticsearch-periodic-packaging #9038 / rocky-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/3onr4rr4vfnv2)
- [elasticsearch-periodic-packaging #9038 / debian-11_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/mythhgr2u2lpg)
- [elasticsearch-periodic-packaging #9038 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/cgn3767x5x4qo)
- [elasticsearch-periodic-packaging #9038 / debian-12_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/igkpk2qh7hane)
- [elasticsearch-periodic-packaging #9038 / opensuse-leap-15_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/4fj4ikjf7sbvs)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test012SecurityCanBeDisabled'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failed to check whether Elasticsearch had started. This could be because authentication isn't working properly. Check the container logs
```

**Issue Reasons:**
- [8.17] 195 failures in test test012SecurityCanBeDisabled (19.5% fail rate in 1000 executions)
- [8.17] 16 failures in step rhel-7_packaging-tests-unix (94.1% fail rate in 17 executions)
- [8.17] 17 failures in step rocky-8_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 16 failures in step ubuntu-2204_packaging-tests-unix (94.1% fail rate in 17 executions)
- [8.17] 17 failures in step almalinux-9_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 15 failures in step rhel-9_packaging-tests-unix (88.2% fail rate in 17 executions)
- [8.17] 14 failures in step rocky-9_packaging-tests-unix (82.4% fail rate in 17 executions)
- [8.17] 17 failures in step debian-11_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 17 failures in step almalinux-8_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 17 failures in step debian-12_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 17 failures in step opensuse-leap-15_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 15 failures in step rhel-8_packaging-tests-unix (88.2% fail rate in 17 executions)
- [8.17] 17 failures in step oraclelinux-8_packaging-tests-unix (100.0% fail rate in 17 executions)
- [8.17] 17 failures in pipeline elasticsearch-periodic-packaging (100.0% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120910: [CI] DockerTests test070BindMountCustomPathConfAndJvmOptions failing
**Build Scans:**
- [elasticsearch-periodic-packaging #8911 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/xinjtxteo4juy)
- [elasticsearch-periodic-packaging #8890 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/cyyfeiunoo7fq)
- [elasticsearch-periodic-packaging #8876 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/wpdosnzjugnac)
- [elasticsearch-periodic-packaging #8869 / oraclelinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/dzzbx2bqowwf2)
- [elasticsearch-periodic-packaging #8848 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/h4gtcgscy6kd6)
- [elasticsearch-periodic-packaging #8841 / ubuntu-2004_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ia4stw6egn52o)
- [elasticsearch-periodic-packaging #8820 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/voglb5y3ubyts)
- [elasticsearch-periodic-packaging #8806 / debian-11_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/lwq422i6wr5fc)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test070BindMountCustomPathConfAndJvmOptions'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileName()" because "autoConfigurationDir" is null
```

**Issue Reasons:**
- [8.17] 8 failures in test test070BindMountCustomPathConfAndJvmOptions (1.0% fail rate in 797 executions)
- [8.17] 3 failures in step rhel-7_packaging-tests-unix (18.8% fail rate in 16 executions)
- [8.17] 2 failures in step almalinux-8_packaging-tests-unix (13.3% fail rate in 15 executions)
- [8.17] 8 failures in pipeline elasticsearch-periodic-packaging (50.0% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120911: [CI] DockerTests test050BasicApiTests failing
**Build Scans:**
- [elasticsearch-periodic-packaging #9031 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/cqoxhpsy2qkv2)
- [elasticsearch-periodic-packaging #9002 / debian-12_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/j5tjeeiwiz6d6)
- [elasticsearch-periodic-packaging #8995 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/cplqbzk5fer2g)
- [elasticsearch-periodic-packaging #8995 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/cplqbzk5fer2g)
- [elasticsearch-periodic-packaging #8925 / almalinux-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/qou77kqi4ql2o)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test050BasicApiTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: Connecting to elasticsearch cluster health API failed:
HTTP/1.1 401 Unauthorized
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\", charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\", charset=\"UTF-8\""]}},"status":401}
```

**Issue Reasons:**
- [8.17] 5 failures in test test050BasicApiTests (0.7% fail rate in 721 executions)
- [8.17] 4 failures in pipeline elasticsearch-periodic-packaging (25.0% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120914: [CI] DockerTests test140CgroupOsStatsAreAvailable failing
**Build Scans:**
- [elasticsearch-periodic-packaging #9031 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/uumqm5iovoupc)
- [elasticsearch-periodic-packaging #9023 / almalinux-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/64v2c5jlk5z4o)
- [elasticsearch-periodic-packaging #9002 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/qbwuygj67imqu)
- [elasticsearch-periodic-packaging #8995 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/z6kffnwde6x4e)
- [elasticsearch-periodic-packaging #8988 / almalinux-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/b7wt7lel4j6ns)
- [elasticsearch-periodic-packaging #8988 / rocky-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ebnma23lio6ty)
- [elasticsearch-periodic-packaging #8988 / oraclelinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/5riq74xt32sqk)
- [elasticsearch-periodic-packaging #8904 / rocky-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/fflpgkln3a5v4)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test140CgroupOsStatsAreAvailable'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failed to check whether Elasticsearch had started. This could be because authentication isn't working properly. Check the container logs
```

**Issue Reasons:**
- [8.17] 8 failures in test test140CgroupOsStatsAreAvailable (1.0% fail rate in 815 executions)
- [8.17] 2 failures in step almalinux-9_packaging-tests-unix (10.5% fail rate in 19 executions)
- [8.17] 2 failures in step rocky-8_packaging-tests-unix (11.1% fail rate in 18 executions)
- [8.17] 6 failures in pipeline elasticsearch-periodic-packaging (31.6% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120918: [CI] DockerTests test071BindMountCustomPathWithDifferentUID failing
**Build Scans:**
- [elasticsearch-periodic-packaging #8953 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/gaudk7hmvbkfe)
- [elasticsearch-periodic-packaging #8946 / rhel-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ltsgar4u3aedo)
- [elasticsearch-periodic-packaging #8932 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ghoeokb6xjvum)
- [elasticsearch-periodic-packaging #8904 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/vz3w6post26bu)
- [elasticsearch-periodic-packaging #8897 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/akq7rxafg3f2u)
- [elasticsearch-periodic-packaging #8890 / oraclelinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/nbjg3bvrp2672)
- [elasticsearch-periodic-packaging #8890 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/bwnndg7tnrq3s)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test071BindMountCustomPathWithDifferentUID'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.apache.http.NoHttpResponseException: localhost:9200 failed to respond
```

**Issue Reasons:**
- [8.17] 7 failures in test test071BindMountCustomPathWithDifferentUID (1.6% fail rate in 428 executions)
- [8.17] 2 failures in step almalinux-8_packaging-tests-unix (20.0% fail rate in 10 executions)
- [8.17] 2 failures in step ubuntu-2204_packaging-tests-unix (22.2% fail rate in 9 executions)
- [8.17] 6 failures in pipeline elasticsearch-periodic-packaging (60.0% fail rate in 10 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #120925: [CI] DockerTests test171AdditionalCliOptionsAreForwarded failing
**Build Scans:**
- [elasticsearch-periodic-packaging #9057 / opensuse-leap-15_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/2vv3x3hxg5qpu)
- [elasticsearch-pull-request #81047 / rhel-8_destructivedistrotest.docker_packaging-tests-unix-sample](https://gradle-enterprise.elastic.co/s/xwlutemw5scia)
- [elasticsearch-pull-request #81016 / rhel-8_destructivedistrotest.docker_packaging-tests-unix-sample](https://gradle-enterprise.elastic.co/s/75fmu6stpq24a)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test171AdditionalCliOptionsAreForwarded'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: Request failed:
HTTP/1.1 401 Unauthorized
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\", charset=\"UTF-8\""]}}],"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\", charset=\"UTF-8\""]}},"status":401}
```

**Issue Reasons:**
- [main] 3 failures in test test171AdditionalCliOptionsAreForwarded (2.7% fail rate in 111 executions)
- [main] 2 failures in step rhel-8_destructivedistrotest.docker_packaging-tests-unix-sample (4.2% fail rate in 48 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (4.1% fail rate in 49 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123437: [CI] DockerTests test151MachineDependentHeapWithSizeOverride failing
**Build Scans:**
- [elasticsearch-periodic-packaging #9262 / rhel-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/v7574bxub47ow)
- [elasticsearch-periodic-packaging #9262 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/j2hphalxwd7ge)
- [elasticsearch-pull-request #82802 / ubuntu-2404_destructivedistrotest.docker_packaging-tests-unix-sample](https://gradle-enterprise.elastic.co/s/szqzn2g72i7tm)
- [elasticsearch-pull-request #82639 / ubuntu-2404_destructivedistrotest.docker_packaging-tests-unix-sample](https://gradle-enterprise.elastic.co/s/lkvifvw52wrae)
- [elasticsearch-periodic-packaging #9220 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/rsfncsiylzeya)
- [elasticsearch-periodic-packaging #9164 / opensuse-leap-15_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/uluhuquygw4gs)
- [elasticsearch-periodic-packaging #9150 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/nsuad7q2zekww)
- [elasticsearch-periodic-packaging #9136 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/odrtx5fimcooc)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test151MachineDependentHeapWithSizeOverride'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.apache.http.NoHttpResponseException: localhost:9200 failed to respond
```

**Issue Reasons:**
- [8.17] 2 consecutive failures in step ubuntu-2404_destructivedistrotest.docker_packaging-tests-unix-sample
- [8.17] 8 failures in test test151MachineDependentHeapWithSizeOverride (1.2% fail rate in 645 executions)
- [8.17] 2 failures in step ubuntu-2404_destructivedistrotest.docker_packaging-tests-unix-sample (66.7% fail rate in 3 executions)
- [8.17] 5 failures in pipeline elasticsearch-periodic-packaging (31.3% fail rate in 16 executions)
- [8.17] 2 failures in pipeline elasticsearch-pull-request (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #124990: [CI] DockerTests test011SecurityEnabledStatus failing
**Build Scans:**
- [elasticsearch-periodic-packaging #9016 / almalinux-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/kb5wjnjtnwpo2)
- [elasticsearch-periodic-packaging #9009 / rhel-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/mq4oixbbxsj2g)
- [elasticsearch-periodic-packaging #8981 / ubuntu-2204_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ncr6362qf4evm)
- [elasticsearch-periodic-packaging #8960 / rocky-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/x5v3wbrt35tgu)
- [elasticsearch-periodic-packaging #8960 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/cevdu2hhokkko)
- [elasticsearch-periodic-packaging #8953 / rhel-7_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ygns2brkelp64)
- [elasticsearch-periodic-packaging #8946 / rhel-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/wc2c6wsumwcpo)
- [elasticsearch-periodic-packaging #8946 / almalinux-8_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/ifnj4xb4v2vaq)
- [elasticsearch-periodic-packaging #8932 / rocky-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/5wf3rf4d26dxc)
- [elasticsearch-periodic-packaging #8911 / almalinux-9_packaging-tests-unix](https://gradle-enterprise.elastic.co/s/322hll2haprhu)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.packaging.test.DockerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test011SecurityEnabledStatus'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.apache.http.NoHttpResponseException: localhost:9200 failed to respond
```

**Issue Reasons:**
- [8.17] 10 failures in test test011SecurityEnabledStatus (1.1% fail rate in 895 executions)
- [8.17] 2 failures in step almalinux-9_packaging-tests-unix (12.5% fail rate in 16 executions)
- [8.17] 2 failures in step rhel-8_packaging-tests-unix (13.3% fail rate in 15 executions)
- [8.17] 2 failures in step rocky-9_packaging-tests-unix (13.3% fail rate in 15 executions)
- [8.17] 8 failures in pipeline elasticsearch-periodic-packaging (50.0% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by slobodanadamovic**
Unmuting 33 DockerTests with added additional logging on failures.
Also, bumping docker startup timeout to account for slow security 
auto-configuration, and additionally moving CA certificates inside 
the retry while loop.

Resolves https://github.com/elastic/elasticsearch/issues/129808
Resolves https://github.com/elastic/elasticsearch/issues/123437
Resolves https://github.com/elastic/elasticsearch/issues/120911
Resolves https://github.com/elastic/elasticsearch/issues/120914
Resolves https://github.com/elastic/elasticsearch/issues/120910
Resolves https://github.com/elastic/elasticsearch/issues/120918
Resolves https://github.com/elastic/elasticsearch/issues/120925
Resolves https://github.com/elastic/elasticsearch/issues/124990
Resolves https://github.com/elastic/elasticsearch/issues/116636
Resolves https://github.com/elastic/elasticsearch/issues/125680
Resolves https://github.com/elastic/elasticsearch/issues/116147
Resolves https://github.com/elastic/elasticsearch/issues/126232
Resolves https://github.com/elastic/elasticsearch/issues/126145
Resolves https://github.com/elastic/elasticsearch/issues/116866
Resolves https://github.com/elastic/elasticsearch/issues/126936
Resolves https://github.com/elastic/elasticsearch/issues/127081
Resolves https://github.com/elastic/elasticsearch/issues/127158
Resolves https://github.com/elastic/elasticsearch/issues/127138
Resolves https://github.com/elastic/elasticsearch/issues/128018
Resolves https://github.com/elastic/elasticsearch/issues/128031
Resolves https://github.com/elastic/elasticsearch/issues/128110
Resolves https://github.com/elastic/elasticsearch/issues/128006
Resolves https://github.com/elastic/elasticsearch/issues/128174
Resolves https://github.com/elastic/elasticsearch/issues/128144
Resolves https://github.com/elastic/elasticsearch/issues/128165
Resolves https://github.com/elastic/elasticsearch/issues/128075
Resolves https://github.com/elastic/elasticsearch/issues/128117
Resolves https://github.com/elastic/elasticsearch/issues/128121
Resolves https://github.com/elastic/elasticsearch/issues/128115
Resolves https://github.com/elastic/elasticsearch/issues/128230
Resolves https://github.com/elastic/elasticsearch/issues/128120
Resolves https://github.com/elastic/elasticsearch/issues/128996
Resolves https://github.com/elastic/elasticsearch/issues/128867

### CODE REVIEW

File: qa/packaging/src/test/java/org/elasticsearch/packaging/util/ServerUtils.java [hunk 1]
```diff
@@ -239,14 +251,13 @@ public static void waitForElasticsearch(
...
         boolean started = false;
         Throwable thrownException = null;
-        if (caCert == null) {
-            caCert = getCaCert(installation);
-        }
 
         while (started == false && timeElapsed < waitTime) {
             if (System.currentTimeMillis() - lastRequest > requestInterval) {
+                if (caCert == null) {
+                    caCert = getCaCert(installation);
```
Comment (slobodanadamovic) [inline qa/packaging/src/test/java/org/elasticsearch/packaging/util/ServerUtils.java:258]: In case of slow auto-configuration, the HTTP CA certificate may not have been configured when `waitForElasticsearch` method is called. This would result in `received plaintext http traffic on an https channel, closing connection Netty4HttpChannel` and test failure after 3 minutes. See this comment for more details: https://github.com/elastic/elasticsearch/issues/123437#issuecomment-3073052149

File: qa/packaging/src/test/java/org/elasticsearch/packaging/test/PackagingTestCase.java [hunk 2]
```diff
@@ -145,6 +145,10 @@ public abstract class PackagingTestCase extends Assert {
         @Override
         protected void failed(Throwable e, Description description) {
             failed = true;
+            if (installation != null && installation.distribution.isDocker()) {
+                logger.warn("Test {} failed. Printing logs for failed test...", description.getMethodName());
+                FileUtils.logAllLogs(installation.logs, logger);
```
Comment (slobodanadamovic) [inline qa/packaging/src/test/java/org/elasticsearch/packaging/test/PackagingTestCase.java:150]: Some of the uncaught docker failures did not include any cluster logs, which makes it super hard to troubleshoot.

**Review by richard-dennehy — APPROVED** [review]

**Comment by slobodanadamovic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/131292)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/131293)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/131294)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/131295)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by brianseeders** [comment]
@slobodanadamovic Our periodic packaging jobs have tons of failures now after unmuting all of these tests... See here for an example: https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/9057
