### PR TITLE
Fix field resolution for FORK

### LINKED ISSUE #127208: ES|QL: tests for FORK's evaluation of field names used in field_caps resolve calls
### Description

Following [the improvements made to FORK](https://github.com/elastic/elasticsearch/pull/125937), it is necessary for the field names used in field_caps calls the IndexResolver is performing to be correctly tested and covered for `fork` as well.

These tests should go in `IndexResolverFieldNamesTests`.
Also, a comment [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java#L569-L571) would be appreciated. The `fieldNames` method is trying to avoid asking for all fields from field_caps for performance reasons and it's trying to be smart in what fields it actually needs. It would help code maintainers and contributors to understand why `fork` needs all the fields in all cases.

### PR DESCRIPTION
**Pull request by ioanatia**
Should close https://github.com/elastic/elasticsearch/issues/127208

Part of https://github.com/elastic/elasticsearch/issues/121950

AFAICS we don't need to ask for all fields when FORK is used and the current field resolution should work since FORK is a N-ary plan.

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Review by astefan — COMMENTED** [review]
From code and tests in csv-spec files I noticed that `FORK` is "generating" a `_fork` (sort of hidden) field. Can you, please, add tests with queries that make use of this `_fork` field?

**Review by astefan — COMMENTED** [review]
The query below (from `rerank.csv-spec`) is using as a field name `_fork` which is strange (many other queries using `fork` and `rrf` do this). This is the full list of field names it's asking for: `book_no, author, title, _fork, title.*, _fork.*, author.*, book_no.*`.

```
FROM books METADATA _id, _index, _score
            | FORK ( WHERE title:"Tolkien" | SORT _score, _id DESC | LIMIT 3 )
            ( WHERE author:"Tolkien" | SORT _score, _id DESC | LIMIT 3 )
            | RRF
            | RERANK "Tolkien" ON title WITH test_reranker
            | LIMIT 2
            | KEEP book_no, title, author
```

`EsqlSession.fieldNames` automatically ignores `MetadataAttribute`s (like `_id`, `_score`, `_index` and others). I'm sure you've discussed about this: what was the reason for not considering `_fork` as a `MetadataAttribute`?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java [hunk 1]
```diff
@@ -1796,6 +1796,62 @@ public void testDropWildcardFields_WithLookupJoin() {
...
+
+    public void testForkFieldsWithStatsInOneBranch() {
+        assumeTrue("FORK available as snapshot only", EsqlCapabilities.Cap.FORK.isEnabled());
+
+        assertFieldNames("""
+            FROM test
+            | WHERE a > 2000
+            | EVAL b = a + 100
+            | FORK (WHERE c > 1 AND a < 10000 | EVAL d = a + 500)
+                   (STATS x = count(*), y=min(z))
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1834]: hmmm - now that I am looking at this more - I think we should return all fields, because one branch is not bounded by any command like `KEEP` or `STATS` that resets the output to a known list of fields. will fix 🤔

Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1834]: There is one more query where I am confused, in part because of probably not knowing what is the expectation for `fork`.

`FROM employees | FORK ( WHERE true | stats min(salary) by gender) ( WHERE true | LIMIT 3 )`

This shows these columns:

`  min(salary)  |    gender     |     _fork     |    salary     `

Should these be a "union" kind of set of columns and `fieldNames` is only limiting it to what it "sees" in the `fork`'s first branch? If that's true, this means that `fieldNames` should consider a union kind of field names from all the branches of `fork`. As a shortcut, the first branch that it finds that's the "widest" it should stop checking the rest.

Comment (ioanatia) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1848]: The FORK output should be a union of the outputs of the fork branches.

If we detect that the same field exists in multiple fork branches outputs, but the field has different type, we fail with a validation error.

FORK will pad with null columns the output of FORK branches that are missing fields.
For example:

```
ROW a = [1, 2, 3], b = "foo"
| MV_EXPAND a
| FORK (WHERE true | LIMIT 2)
        (STATS x = count(*))
        (WHERE a % 2 == 0 | EVAL y = 2)
| SORT _fork, a
| KEEP _fork, a, b, x, y
```

Will produce:

```
     _fork     |       a       |       b       |       x       |       y       
---------------+---------------+---------------+---------------+---------------
fork1          |1              |foo            |null           |null           
fork1          |2              |foo            |null           |null           
fork2          |null           |null           |3              |null           
fork3          |2              |foo            |null           |2          
```

I _think_ fixed the field resolution for this case.
In this test example here we should ask for all fields, since not all branches are bounded by an `Aggregate` or `Project`.

**Comment by ioanatia** [comment]
> EsqlSession.fieldNames automatically ignores MetadataAttributes (like _id, _score, _index and others). I'm sure you've discussed about this: what was the reason for not considering _fork as a MetadataAttribute?

We could consider `_fork` a metadata attribute - but unlike `_id`, `_index`, you could actually have a `_fork` mapped field.
Promise to take this as a separate question that we can address, but for now we end up asking for the `_fork` field when we see it referenced.

**Review by tteofili — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 2]
```diff
@@ -583,6 +583,29 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
...
+            if (plan instanceof Fork fork && projectAfterFork.get() == false) {
+                hasFork.set(true);
+                fork.children().forEach(child -> {
+                    if (child.anyMatch(p -> p instanceof Project || p instanceof Aggregate) == false) {
+                        projectAll.set(true);
+                    }
+                });
+            }
+        });
+
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:608]: If I may suggest some very small changes:

```suggestion

        if (projectAll.get()) {
            return result.withFieldNames(IndexResolver.ALL_FIELDS);
        }

        Holder<Boolean> projectAfterFork = new Holder<>(false);
        Holder<Boolean> hasFork = new Holder<>(false);

        parsed.forEachDown(plan -> {
            if (projectAll.get()) {
                return;
            }
            if (hasFork.get() == false && shouldCollectAllFields(plan)) {
                projectAfterFork.set(true);
            }

            if (plan instanceof Fork fork && projectAfterFork.get() == false) {
                hasFork.set(true);
                if (fork.anyMatch(p -> p instanceof Project || p instanceof Aggregate)) {
                    projectAll.set(true);
                }
            }
        });

```

And extract a method

```
    private static boolean shouldCollectAllFields(LogicalPlan plan) {
        return plan instanceof Project || plan instanceof Aggregate;
    }
```

To also be used here

```
    static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicyMatchFields, PreAnalysisResult result) {
        if (false == parsed.anyMatch(plan -> shouldCollectAllFields(plan))) {
            // no explicit columns selection, for example "from employees"
            return result.withFieldNames(IndexResolver.ALL_FIELDS);
        }
```

**Review by astefan — APPROVED** [review]
LGTM.

Please, also, add that query I mentioned in one of my comments: `FROM employees | FORK ( WHERE true | stats min(salary) by gender) ( WHERE true | LIMIT 3 )` to `IndexResolverFieldNamesTests`. Thank you.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java (hunk 2 above)
Comment (ioanatia) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java]: done - thank you for the suggestion
