### PR TITLE
[ML] Fix datafeed timing stats deletion race condition

### LINKED ISSUE #138348: [CI] DatafeedJobsIT testDatafeedTimingStats_DatafeedRecreated failing
**Build Scans:**
- [elasticsearch-intake #36804 / part4](https://gradle-enterprise.elastic.co/s/mou7cezptogb4)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testDatafeedTimingStats_DatafeedRecreated" -Dtests.seed=C4C8B6FD91362047 -Dtests.locale=es-UY -Dtests.timezone=Asia/Yerevan -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDatafeedTimingStats_DatafeedRecreated'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0L>
     but: was <1L>
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testDatafeedTimingStats_DatafeedRecreated
- [main] 1 consecutive failures in step part4
- [main] 1 consecutive failures in pipeline elasticsearch-intake

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by edsavage**
## Summary

Fixes the flaky `DatafeedJobsIT.testDatafeedTimingStats_DatafeedRecreated` test (#138348) by replacing the `DeleteByQuery` in `JobDataDeleter.deleteDatafeedTimingStats()` with a direct `DeleteRequest` by document ID.

## Cause

`DatafeedTimingStatsReporter.flushIfDifferSignificantly()` writes the timing stats document with `RefreshPolicy.NONE` after the first search (`search_count` 0→1). The `DeleteByQuery` used to remove this document is a two-phase operation (search phase → delete phase) where the search phase can miss un-refreshed documents. When this happens, the document with `search_count=1` survives deletion and causes the assertion `Expected: <0L> but: was <1L>` on the next datafeed creation cycle.

## Changes

- **`JobDataDeleter.deleteDatafeedTimingStats()`**: replaced `DeleteByQuery` with a direct `DeleteRequest` using the known document ID (`DatafeedTimingStats.documentId(jobId)`). A direct delete routes to the correct shard by `_id` without a search phase, so it cannot miss un-refreshed documents. Uses `RefreshPolicy.IMMEDIATE` to ensure the deletion is visible to subsequent reads.
- **`JobDataDeleterTests`**: updated to verify `TransportDeleteAction.TYPE` calls and assert the correct index and document ID.
- **`muted-tests.yml`**: unmuted `testDatafeedTimingStats_DatafeedRecreated`.

## Test plan

- [x] `JobDataDeleterTests` passes locally
- [x] CI: `DatafeedJobsIT.testDatafeedTimingStats_DatafeedRecreated` no longer flakes

Closes #138348

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/persistence/JobDataDeleterTests.java [hunk 1]
```diff
@@ -166,19 +169,19 @@ public void testDeleteResultsFromTime() {
...
-
-            DeleteByQueryRequest deleteRequest = deleteRequestCaptor.getValue();
-            assertThat(deleteRequest.indices(), is(arrayContaining(AnomalyDetectorsIndex.jobResultsAliasedName(JOB_ID))));
         });
+        verify(client, never()).execute(eq(DeleteByQueryAction.INSTANCE), any(), any());
+        verify(client, times(2)).execute(eq(TransportDeleteAction.TYPE), deleteCaptor.capture(), any());
+
+        DeleteRequest deleteRequest = deleteCaptor.getValue();
+        assertThat(deleteRequest.index(), is(AnomalyDetectorsIndex.jobResultsAliasedName(JOB_ID)));
+        assertThat(deleteRequest.id(), is(DatafeedTimingStats.documentId(JOB_ID)));
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/persistence/JobDataDeleterTests.java:184]:
```suggestion
        assertThat(deleteRequest.id(), is(DatafeedTimingStats.documentId(JOB_ID)));
        assertThat(deleteRequest.getRefreshPolicy(), is(WriteRequest.RefreshPolicy.IMMEDIATE));

```

**Review by valeriy42 — APPROVED** [review]
LGTM with minor suggestion. Make sure the change will be backported to older versions where the test is muted as well.

**Comment by edsavage** [comment]
buildkite test this

**Comment by prwhelan** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/154604)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
