### PR TITLE
Fix async enrich execution prematurely releases enrich policy lock

### LINKED ISSUE #94690: Enrich policy executions are incorrectly unlocked when wait_for_completion is false
When executing enrich policies, the master node locks the policy so that multiple policy executions cannot race each other. This locking mechanism also reserves the enrich index name so that it is not considered for cleanup by the background enrich maintenance task. Policy execution is coordinated on the master node, but it is executed on a randomly chosen remote node. 

When executing normally, the client waits for the policy execution to complete, after which the policy is unlocked. However, if the client specifies `wait_for_completion=false`, the remote node returns immediately with a task id that can be used to check progress asynchronously. In this case, the master node still needs to be notified of when the task completes so that it may clean up the locked policy. It does this by submitting a Get Task action with `wait_for_completion=true`, and unlocking the policy once that call returns.

The bug is that the Get Task action has no specified timeout on its submission. The default timeout is 30 seconds. At the end of that 30 seconds, the call completes with a timeout exception. The exception is ignored and the policy is unlocked. Policies that take longer than 30 seconds to execute are at risk of having their indices removed by the background enrich maintenance task since they are no longer reserved for an active execution. Depending on timing, the enrich maintenance task has an increasing chance to delete the index as the policy execution time approaches the maintenance period (default 20 minutes).

One workaround here is to dramatically increase the maintenance period to allow enrich policy executions to complete, but this does not eliminate the chance of deleting the new enrich index, it only increases the window for the policy to complete executing within. Setting the period to an arbitrarily long period of time is also not advisable as it can keep the cluster from cleaning up old indices. The maintenance period setting also requires a node restart to take effect, as it is not dynamic.

Another workaround would be to not make use of the `wait_for_completion=false` setting value. Instead, a connection with a long, client-side timeout should be used along with `wait_for_completion=true` (the default). This will keep the policy locked for the entire period of the execution and keep the underlying enrich index from being deleted prematurely.

### PR DESCRIPTION
**Pull request by jbaiera**
When submitting an enrich policy execution with `wait_for_completion=false`, the master node that services the request needs to wait on the remote task to complete so that it may unlock the policy for further runs. It currently does not set a timeout for the Get Task API call, which has a default timeout of 30 seconds. This is almost never enough time to cover an executing enrich policy. At the end of the timeout, the policy is unlocked without any further logic applied. This leaves the new enrich index that is under construction open to be deleted by the background maintenance task.

This PR is a quick fix for the problem. It ups the timeout on the get task API and adds additional logic in the event that the task await call fails.

fixes #94690

### CODE REVIEW

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java [hunk 1]
```diff
@@ -138,11 +152,54 @@ private Releasable tryLockingPolicy(String policyName, String enrichIndexName) {
...
-        getTaskRequest.setTaskId(taskId);
-        getTaskRequest.setWaitForCompletion(true);
-        client.admin().cluster().getTask(getTaskRequest, ActionListener.running(policyLock::close));
+    private void awaitTaskCompletionAndThenRelease(
+        TaskId taskId,
+        Releasable policyLock,
+        final String policyName,
+        final String enrichIndexName
+    ) {
+        GetTaskRequest getTaskRequest = new GetTaskRequest().setTaskId(taskId).setWaitForCompletion(true).setTimeout(TimeValue.MAX_VALUE);
```
Comment (jbaiera) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java:161]: I'm not keen on an infinite timeout here. It feels like there should be a better way to ensure that a task on a remote node concludes correctly without setting an infinite timeout.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java [hunk 2]
```diff
@@ -138,11 +152,54 @@ private Releasable tryLockingPolicy(String policyName, String enrichIndexName) {
...
+                if (ExceptionsHelper.unwrap(exception, ResourceNotFoundException.class) != null) {
+                    // Could not find task, which means it completed, failed, or the node is gone. Clean up policy lock.
+                    logger.debug(
+                        "Assuming async policy [{}:{}] execution task [{}] has ended after not being able to retrieve it from remote host",
+                        policyName,
+                        enrichIndexName,
+                        taskId
+                    );
+                    policyLock.close();
+                } else if (ExceptionsHelper.unwrap(exception, ElasticsearchTimeoutException.class) != null) {
```
Comment (masseyke) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java:179]: Do we only hit this after TimeValue.MAX_VALUE? Or is this hitting another timeout somewhere?

Comment (jbaiera) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java:179]: During normal execution, yeah, this shouldn't really ever receive a timeout because of how long it is configured, but this was the condition that was causing the original bug, so it was the easier place to build a test around.

I think it might be more reasonable to put a lower timeout in (maybe an hour?) just to keep the connection from holding forever, but if the task is stuck on the remote node, then a retry loop likely won't be any more graceful than waiting forever.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java (hunk 1 above)
Comment (jbaiera) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java:161]: Given discussions offline there's not really a better way to do this at the moment, so I'm leaving it in.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java (hunk 2 above)
Comment (jbaiera) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutor.java:179]: I think I'm just going leave the timeout as max value, but keep the timeout handling logic in place for sanity's sake.

File: x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java [hunk 3]
```diff
@@ -178,6 +189,155 @@ public void testMaximumPolicyExecutionLimit() throws InterruptedException {
...
+            testThreadPool,
+            TestIndexNameExpressionResolver.newInstance(testThreadPool.getThreadContext()),
+            enrichPolicyLocks,
+            ESTestCase::randomNonNegativeLong
+        );
+
+        // Launch a fake policy run that will block until firstTaskBlock is counted down.
+        PlainActionFuture<ExecuteEnrichPolicyAction.Response> firstTaskResult = PlainActionFuture.newFuture();
+        testExecutor.coordinatePolicyExecution(
+            new ExecuteEnrichPolicyAction.Request(testPolicyName).setWaitForCompletion(true),
```
Comment (masseyke) [inline x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java:266]: This threw me off but I think it's irrelevant -- the case we're actually testing here is when `waitForCompletion` is `false`, right? But since the test's client always returns a response with a task and no status, it doesn't actually matter what is set for `waitForCompletion` here. It might be good just for clarity though to set it to `false` here, and/or update the client to return a status instead of a taskId if it is true.

File: x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java [hunk 4]
```diff
@@ -178,6 +189,155 @@ public void testMaximumPolicyExecutionLimit() throws InterruptedException {
...
+            firstTaskResult
+        );
+
+        // Check to make sure the policy is locked
+        if (enrichPolicyLocks.lockedPolices().contains(testPolicyName) == false) {
```
Comment (masseyke) [inline x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java:271]: Can we just assert that `enrichPolicyLocks.lockedPolices().contains(testPolicyName)` here? I assume not, or you wouldn't have gone to the trouble of writing the if block. But I'm not sure how it's possible to get in there, and I haven't been able to after dozens of attempts running the code. Maybe a comment here describing how it's possible to get in the if block?

File: x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java (hunk 3 above)
Comment (jbaiera) [reply x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java:266]: This just puzzled me as well - combination of copy paste gone awry and distraction. It seems that the test works fine because the logic that controls if we return a task id to the client immediately is based on the response from the client when submitting the internal policy action, which we override in the test to respond as if wait for completion was set false. I have updated the test to pass in a false and to verify that it was false.

File: x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java (hunk 4 above)
Comment (jbaiera) [reply x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/EnrichPolicyExecutorTests.java:271]: I can try and clarify the comment. The reason this isn't a simple assert call is because if the assertion fails for any reason in the future (hopefully it never does!) there is some cleanup we can do to keep the test failure output from being a mess of multithreaded error logs. Hence the inside of the block.

**Review by masseyke — APPROVED** [review]
LGTM

**Comment by jbaiera** [comment]
This relates to #89835 and #85221 as it is likely the REAL fix for those bugs.

**Comment by jbaiera** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.7|[](https://github.com/elastic/elasticsearch/pull/94837)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
