### PR TITLE
Restore support for escaped '/' as part of document id

### LINKED ISSUE #14177: Getting document by ID with '/' slash in the id
Trying to insert or get a document with path "/twitter/tweet/a%2Fe" results in a "No handler found for uri [/twitter/tweet/a%2Fe] and method [GET]" response. Response code 400.

It seems it's a regression of previous behaviour unless I'm missing something.

This is running against es-2.0.0-rc1.

### PR DESCRIPTION
**Pull request by javanna**
With #13691 we introduced some custom logic to make sure that date math expressions like `<logstash-{now/D}>` don't get broken up into two where the slash appears in the expression. That said the only correct way to provide such a date math expression as part of the uri would be to properly escape the '/' instead. This fix also introduced a regression, as it would make sure that unescaped '/' are handled only in the case of date math expressions, but it removed support for properly escaped slashes anywhere else. The solution is to keep supporting escaped slashes only and require client libraries to properly escape them.

This commit reverts 93ad6969669e65db6ba7f35c375109e3f186675b and makes sure that our REST tests runner supports escaping of path parts, which was more involving than expected as each single part of the path needs to be properly escaped. I am not too happy with the current solution but it's the best I could do for now, maybe not that concerning anyway given that it's just test code. I do find uri encoding quite frustrating in java.

Relates to #13691
Relates to #13665

Closes #14177

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/test/rest/client/http/HttpRequestBuilder.java [hunk 1]
```diff
@@ -86,14 +86,42 @@ public HttpRequestBuilder port(int port) {
...
+            this.path = "/";
+            return this;
+        }
+        StringBuilder finalPath = new StringBuilder();
+        for (String pathPart : path) {
+            try {
+                finalPath.append('/');
+                URI uri = new URI(null, null, null, -1, pathPart, null, null);
+                //manually escape any slash that each part may contain
+                finalPath.append(uri.getRawPath().replaceAll("/", "%2F"));
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/test/rest/client/http/HttpRequestBuilder.java]: Why do you use replaceAll instead of URLEncoder?

Comment (javanna) [inline core/src/test/java/org/elasticsearch/test/rest/client/http/HttpRequestBuilder.java]: URLEncoder is good only for query_string params, not for url path. They have different escaping rules according to the spec. Also URI applies the right rules to the path, but given that you have to provide the whole path it won't escape slashes. This is frustrating...but I couldn't find any better solutions.

Comment (jpountz) [inline core/src/test/java/org/elasticsearch/test/rest/client/http/HttpRequestBuilder.java]: ok

**Comment by jpountz** [comment]
LGTM but maybe this would deserve another review from someone who is more familiar with uri escaping than I am

**Comment by spinscale** [comment]
LGTM
