### PR TITLE
Consistently prevent using exclusion prefix on its own

### LINKED ISSUE #45504: Empty index name in `index` path param fails request with access denied
When doing index operations like `_search`, `_field_caps` we provide index patterns as a path param. When security is enabled and the index pattern path param contains an empty string then the request fails with HTTP status 403 and a `security_exception` with message `action [indices:data/read/search] is unauthorized for user [elastic]`. The user has `superuser` role but the root cause is a string out of bounds exception with message `String index out of range: 0`.

IMO we should not be throwing index out of bounds exception during index alias resolution and the response should be a validation error instead of access denied similar to what we respond when security is disabled.

Example problem invocation with a empty string as index name:
`POST /test*,,missing*/_search?q=*`
`GET /test*,,missing*/_field_caps`

When security is disabled, the response is with HTTP status 404 and an `index_not_found_exception` with message `no such index []`.

### PR DESCRIPTION
**Pull request by ywangd**
The dash character is used as a prefix to signify index exclusion. It should not be used on its own. For example, an expression like `*,-` should be invalid. However, today this is handled differently depending on whether security is enabled or disabled. When security is enabled, the standalone exclusion char is ignored and the expression is handled as just `*`. But when security is disabled, the expression encounters an IndexNotFoundException.

This PR fixes the inconsistency by always throwing InvalidIndexNameException. In addition, this PR also fixes #45504 by ensuring InvalidIndexNameException is thrown for empty index name instead of IndexOutOfBoundsException.

Resolves: #45504

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java [hunk 1]
```diff
@@ -123,11 +124,18 @@ private void resolveIndexAbstraction(
         final boolean includeDataStreams,
         final Set<String> remoteExpressions
     ) {
+        if (localIndexExpression.isEmpty()) {
+            throw invalidExpression(false);
+        }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java:130]: Currently, an empty expression encounters an `IndexOutOfBoundsException` because we call `localIndexExpression.charAt(0)` a few lines below. With security disabled, the error is `IndexNotFoundException`. I think it's better for them to both throw `IllegalArgumentException`. Strictly speaking, this change is not about exclusion. But since it's an issue of similar nature, I decide to include it as well.

**Comment by ywangd** [comment]
In addition to index exclusion, there is also remote cluster exclusion. Currently, an expression such as `-:foo` [encounters](https://github.com/elastic/elasticsearch/blob/0cd9c72199e3b665be6e816993647439e962ee21/server/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java#L42) a `NoSuchRemoteClusterException`. We could decide to change the exception to `IllegalArgumentException` as well. But I'll leave it out for this PR.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java [hunk 2]
```diff
@@ -223,6 +224,38 @@ public void testExplicitAndWildcardInclusionAndExplicitExclusions() {
...
+
+        final List<String[]> expressionsList = List.of(
+            new String[] { "" },
+            new String[] { "*", "" },
+            new String[] { "test1", "" },
+            new String[] { "*", "", "test1" }
+        );
+        for (var expressions : expressionsList) {
+            final var e = expectThrows(ElasticsearchSecurityException.class, () -> trySearch(expressions).get());
+            assertThat(e.getCause(), instanceOf(IllegalArgumentException.class));
```
Comment (ywangd) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java]: `IllegalArgumentException` is always [wrapped](https://github.com/elastic/elasticsearch/blob/0cd9c72199e3b665be6e816993647439e962ee21/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java#L597-L630) with `ElasticsearchSecurityException`. I think we could argue whether such wrapping is necessary. But I don't want to go down that path for now. Alternatively, if we want to avoid the wrapping, we could throw either `InvalidIndexNameException` or `IndexNotFoundException` instead. Please let me know if you prefer either of these.

Comment (ywangd) [reply x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java]: On second thought, I decided to use `InvalidIndexNameException` which seems more specific for the particular issue. eb9498bbf216770149ff2817e32e0bd435e21f7e

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java (hunk 1 above)
Comment (n1v0lg) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java:130]: Nice, I think this effectively fixes long-standing https://github.com/elastic/elasticsearch/issues/45504 👍 Could you add a note to the PR description to close the issue once merged?

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java [hunk 3]
```diff
@@ -123,11 +124,18 @@ private void resolveIndexAbstraction(
         final boolean includeDataStreams,
         final Set<String> remoteExpressions
     ) {
+        if (localIndexExpression.isEmpty()) {
+            throw invalidExpression(false);
```
Comment (n1v0lg) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java]: Nit: I'd add `invalidExclusion()` and `invalidExpression()` methods to make the call more self-explanatory (as opposed to the raw boolean arg)

File: server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java [hunk 4]
```diff
@@ -1049,6 +1049,31 @@ public void testConcreteIndicesWildcardWithNegation() {
...
+            project,
+            IndicesOptions.fromOptions(randomBoolean(), randomBoolean(), true, randomBoolean()),
+            SystemIndexAccessLevel.NONE
+        );
+
+        final List<String[]> expressionsList = List.of(
+            new String[] { "-" },
+            new String[] { "*", "-" },
+            new String[] { "testXXX", "-" },
+            new String[] { "*", "-", "testXXX" }
```
Comment (n1v0lg) [inline server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java]: I'd also add:

```java
new String[] { "-", "-" },
new String[] { "-testXXX", "-" },
new String[] { "*", "-testXXX", "-" }
```

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java [hunk 5]
```diff
@@ -223,6 +225,36 @@ public void testExplicitAndWildcardInclusionAndExplicitExclusions() {
...
+            final var e = expectThrows(InvalidIndexNameException.class, () -> trySearch(expressions).get());
+            assertThat(e.getMessage(), containsString("Invalid index name [], expression cannot be empty"));
+        }
+    }
+
+    public void testExclusionPrefixOnItsOwnIsInvalid() {
+        createIndicesWithRandomAliases("test1");
+
+        final List<String[]> expressionsList = List.of(
+            new String[] { "-" },
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java:248]: I'd also add:

```java
new String[] { "_all", "-" }, // interestingly this doesn't work in server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java since we don't allow `_` at that validation stage 
new String[] { "-", "-" },
new String[] { "-testXXX", "-" },
new String[] { "*", "-testXXX", "-" }
```

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java [hunk 6]
```diff
@@ -223,6 +225,36 @@ public void testExplicitAndWildcardInclusionAndExplicitExclusions() {
         assertReturnedIndices(trySearch("test10", "test111", "test112", "-test111", "-test112", "index*"), "test10");
     }
 
+    public void testEmptyExpressionIsInvalid() {
+        createIndicesWithRandomAliases("test1");
+
+        final List<String[]> expressionsList = List.of(
+            new String[] { "" },
```
Comment (n1v0lg) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java:232]: Let's also cover:

```java
new String[] { "", "_all" },
```

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java (hunk 2 above)
Comment (n1v0lg) [reply x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java]: `InvalidIndexNameException` makes sense to me

**Review by n1v0lg — APPROVED** [review]
LGTM 👍

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java (hunk 1 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java:130]: Ah good find. Updated the PR description as well as adding the issue to the changelog.

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java (hunk 3 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java]: Sure see aff7f77330ffe11ef29adf019578bba2910f193b

File: server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java (hunk 4 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java]: Pushed 3468c92f31490c59be6180381c2921d931cf831e

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java (hunk 5 above)
Comment (ywangd) [reply x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java:248]: I think we should make `IndexAbstractionResolver` behave the same as `IndexNameExpressionResolver` for handling `_all`. It's inconsistent right now. The expression `_all` is a special match-all only when it is used on its own. Otherwise, it is just a normal name. As a normal name, it is invalid because index cannot begin with `_`. But with security enabled, an expression like `foo*,_all` ends up being just `_all` and expands to match all if `foo*` matches nothing. But if `foo*` matches anything, it then encounters `InvalidIndexNameException`. This is not a sensible behaviour and I think we should instead throw `InvalidIndexNameException` in both cases.

I added a test for `{ "_all", "-" }` on the core side and assert it throws index name "must. not start with '_'". See 3468c92f31490c59be6180381c2921d931cf831e along with your suggestion.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java (hunk 6 above)
Comment (ywangd) [reply x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/ReadActionsTests.java:232]: Yep see 3468c92f31490c59be6180381c2921d931cf831e

**Comment by ywangd** [comment]
CI Failure is irrelevant but reproducible. I raised #139576
