### PR TITLE
Fixed NPE in binary doc values query

### LINKED ISSUE #147334: DocValuesFieldFactory incorrectly uses IndexVersion
Introduced in: 7b77621e7a389a02a4d50b9ebf00f145b006612d

Steps to reproduce:
```
 ./gradlew ":qa:mixed-cluster:v9.4.0#mixedClusterTest" -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=aggregations/terms_text_docvalues/Indexing disabled}" -Dtests.seed=C9D785607134B6FC -Dtests.bwc=true -Druntime.java=26
```

In https://github.com/elastic/elasticsearch/commit/7b77621e7a389a02a4d50b9ebf00f145b006612d, we introduced [DocValuesFieldFactory](https://github.com/elastic/elasticsearch/blob/cf893691091dd651607f0dee109e07f27818285d/server/src/main/java/org/elasticsearch/index/mapper/DocValuesFieldFactory.java#L30), which is meant to act as the one place responsible for creating doc values fields.

This factory contains an `IndexVersion`, which is passed down to `MultiValuedBinaryDocValuesField` and used it to decide what binary doc values encoding format to use (`IntegratedCounts` or `SeparateCounts`). This is important for BWC purpose - where some callers previously used `IntegratedCounts`, but now use `SeparateCounts`.

This BWC check however is unnecessary for callers that always used `SeparateCounts`. Branching on the index version for such callers is wrong as it forces them to use an encoding format they never supported. This results in NPEs in `AbstractBinaryDocValuesQuery` as it only understands the `SeparateCounts` format.

Related issue: https://github.com/elastic/elasticsearch/issues/147200

### PR DESCRIPTION
**Pull request by Kubik42**
Fixes https://github.com/elastic/elasticsearch/issues/147334

Most of the new code are tests that will catch this issue in the future.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/DocValuesFieldFactory.java [hunk 1]
```diff
@@ -63,12 +61,23 @@ public void addSortedField(LuceneDocument doc, String name, BytesRef value) {
...
     /**
      * Adds a binary doc values field. For {@code multi_value=no}, creates a plain {@link BinaryDocValuesField} (single-valued,
      * no companion {@code .counts} field). Otherwise, delegates to {@link MultiValuedBinaryDocValuesField#addToBinaryFieldInDoc}
      * which handles the multi-valued encoding.
+     * <p>
+     * Use this overload for fields that historically stored {@link MultiValuedBinaryDocValuesField.IntegratedCount IntegratedCount} data
+     * (pre-{@link org.elasticsearch.index.IndexVersions#DEPRECATE_INTEGRATED_COUNTS_BINARY_DOC_VALUES}).
      */
-    public void addBinaryField(LuceneDocument doc, String name, BytesRef value, ValueOrdering ordering) {
+    public void addBinaryField(LuceneDocument doc, String name, BytesRef value, ValueOrdering ordering, IndexVersion indexVersion) {
```
Comment (parkertimmins) [inline server/src/main/java/org/elasticsearch/index/mapper/DocValuesFieldFactory.java]: nit: I think it'd be clearer if this method name included some explanation, like: `addBinaryFieldHandleLegacy`

**Review by parkertimmins — APPROVED** [review]
One naming nit, but LGTM

**Review by martijnvg — COMMENTED** [review]
LGTM2
