### PR TITLE
KQL: Support boolean operators in field queries

### LINKED ISSUE #132366: ESQL: KQL OR condition behavior causing query_shard_exception
### Elasticsearch Version

9.1.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

unix-like

### Problem Description

````markdown


We’ve found a bug with KQL (Kibana Query Language) while querying Fortinet logs.

Here’s the query we tried:

```esql
FROM fortinet-logs
| WHERE KQL("destination.geo.country_name:(United OR India)")
````

This query returns the following error:

```
[esql] > Unexpected error from Elasticsearch: query_shard_exception - Failed to parse KQL query [destination.geo.country_name:(United OR India)]
```

Interestingly, the equivalent QSTR query works fine:

```esql
FROM fortinet-logs
| WHERE QSTR("destination.geo.country_name:(United OR India)")
```

It seems KQL does not handle the OR operator inside parentheses in this context correctly, while QSTR does.

### Steps to Reproduce

For instance, this works perfecly with QSTR. But KQL would have been better 
KQL works if we chain the commands, but not ideal
```
FROM fortinet-logs
| WHERE QSTR("destination.geo.country_name:(United OR India)")
| WHERE KQL("destination.geo.country_name:(United)") OR KQL("destination.geo.country_name:(India)")
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by afoucret**
### Description

This pull request introduces support for boolean operators (`AND`, `OR`, `NOT`) within KQL field queries.

Previously, it was not possible to combine multiple conditions for a single field using boolean logic. For instance, a query like `response:(200 AND ok)` would not be parsed correctly.

### Changes summary:
   1. Updating the KQL ANTLR grammar to recognize boolean expressions within field query values.
   2. Enhancing the AST builder to correctly parse these expressions and translate them into the corresponding Elasticsearch BoolQueryBuilder clauses.
   3. Adding unit tests to validate the new functionality.

###  Example:

  A query like `response:((200 AND "OK") OR 404)`  is now supported and will be translated into the appropriate boolean query.

### CODE REVIEW

File: x-pack/plugin/kql/src/main/java/org/elasticsearch/xpack/kql/parser/KqlAstBuilder.java [hunk 1]
```diff
@@ -207,38 +208,76 @@ public QueryBuilder visitFieldLessQuery(KqlBaseParser.FieldLessQueryContext ctx)
 
     @Override
     public QueryBuilder visitFieldQuery(KqlBaseParser.FieldQueryContext ctx) {
+        return paresFieldQuery(ctx.fieldName(), ctx.fieldQueryValue());
+    }
 
-        BoolQueryBuilder boolQueryBuilder = QueryBuilders.boolQuery().minimumShouldMatch(1);
-        String queryText = extractText(ctx.fieldQueryValue());
-        boolean hasWildcard = hasWildcard(ctx.fieldQueryValue());
+    public QueryBuilder paresBooleanFieldQuery(
```
Comment (kderusso) [inline x-pack/plugin/kql/src/main/java/org/elasticsearch/xpack/kql/parser/KqlAstBuilder.java]: Typo - should be `parseBooleanFieldQuery`

File: x-pack/plugin/kql/src/main/java/org/elasticsearch/xpack/kql/parser/KqlAstBuilder.java [hunk 2]
```diff
@@ -207,38 +208,76 @@ public QueryBuilder visitFieldLessQuery(KqlBaseParser.FieldLessQueryContext ctx)
...
-
-            if (hasWildcard && isKeywordField(mappedFieldType)) {
-                fieldQuery = QueryBuilders.wildcardQuery(fieldName, queryText).caseInsensitive(kqlParsingContext.caseInsensitive());
-            } else if (hasWildcard) {
-                fieldQuery = QueryBuilders.queryStringQuery(escapeLuceneQueryString(queryText, true)).field(fieldName);
-            } else if (isDateField(mappedFieldType)) {
-                RangeQueryBuilder rangeFieldQuery = QueryBuilders.rangeQuery(fieldName).gte(queryText).lte(queryText);
-                if (kqlParsingContext.timeZone() != null) {
-                    rangeFieldQuery.timeZone(kqlParsingContext.timeZone().getId());
+    public QueryBuilder paresFieldQuery(
```
Comment (kderusso) [inline x-pack/plugin/kql/src/main/java/org/elasticsearch/xpack/kql/parser/KqlAstBuilder.java]: Typo - should be `parseFieldQuery`

File: x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/parser/KqlParserTests.java [hunk 3]
```diff
@@ -41,7 +43,9 @@ public void testParenthesizedQuery() throws IOException {
         for (String baseQuuery : readQueries(SUPPORTED_QUERY_FILE_PATH)) {
             // For each supported query, wrap it into parentheses and check query remains the same.
             // Adding random whitespaces as well and test they are ignored.
-            String parenthesizedQuery = wrapWithRandomWhitespaces("(") + baseQuuery + wrapWithRandomWhitespaces(")");
+            String parenthesizedQuery = "(" + baseQuuery + ")";
```
Comment (kderusso) [inline x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/parser/KqlParserTests.java]: Existing typo: Should be `baseQuery`

File: x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/parser/KqlParserTests.java [hunk 4]
```diff
@@ -41,7 +43,9 @@ public void testParenthesizedQuery() throws IOException {
...
+
+            LogManager.getLogger(KqlParserTests.class).info(parenthesizedQuery);
```
Comment (kderusso) [inline x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/parser/KqlParserTests.java]: Did you mean to keep this logger?

File: x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml [hunk 5]
```diff
@@ -210,3 +210,57 @@ setup:
...
+
+  - do:
+      search:
+        index: test-index
+        rest_total_hits_as_int: true
+        body: >
+          {
+            "query": { "kql": { "query": "text_field:(bar OR baz)" } }
+          }
+  - match: { hits.total: 2 }
```
Comment (kderusso) [inline x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml:243]: Match hit IDs here?

File: x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml [hunk 6]
```diff
@@ -210,3 +210,57 @@ setup:
...
+
+  - do:
+      search:
+        index: test-index
+        rest_total_hits_as_int: true
+        body: >
+          {
+            "query": { "kql": { "query": "keyword_field:(\"foo bar\" OR \"foo baz\")" } }
+          }
+  - match: { hits.total: 2 }
```
Comment (kderusso) [inline x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml:264]: Match hit IDs here?

File: x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml [hunk 7]
```diff
@@ -210,3 +210,57 @@ setup:
   - match: { hits.total: 1 }
   - match: { hits.hits.0._id: "doc-1" }
 
+
+---
+"KQL boolean field queries":
```
Comment (kderusso) [inline x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml]: Do you need a cluster feature here, for yaml test bwc?

**Review by kderusso — COMMENTED** [review]
Nice work, left some minor comments, will leave the grammar review to others 👍

**Review by carlosdelest — APPROVED** [review]
LGTM 👍

File: x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml (hunk 5 above)
Comment (afoucret) [reply x-pack/plugin/kql/src/yamlRestTest/resources/rest-api-spec/test/kql/10_kql_basic_query.yml:243]: Not really needed cause the index contains only two docs, so just checking the number of results is enough to check that all docs are returned.

**Comment by afoucret** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/133836)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/133837)|
|❌|8.17|Conflict resolution was aborted by the user|
|❌|8.16|An unhandled error occurred. Please see the logs for details|

### Manual backport
To create the backport manually run:
```
backport --pr 133737
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by thecoop** [comment]
@afoucret This causes #133863 and #133871
