### PR TITLE
StressSearchServiceReaperIT_unmute_test

### LINKED ISSUE #115816: [CI] StressSearchServiceReaperIT testStressReaper failing
**Build Scans:**
- [elasticsearch-intake #12871 / part1](https://gradle-enterprise.elastic.co/s/vrvlq4isocydu)
- [elasticsearch-pull-request #41026 / part-1](https://gradle-enterprise.elastic.co/s/w2s4owekfnyy4)
- [elasticsearch-periodic-platform-support #4743 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/g24qxmy6evi6w)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.StressSearchServiceReaperIT.testStressReaper" -Dtests.seed=64D595343C606FE -Dtests.locale=ee -Dtests.timezone=Africa/Blantyre -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.StressSearchServiceReaperIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testStressReaper),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [8.x] 3 failures in test testStressReaper (0.4% fail rate in 689 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by drempapis**
Fix for the error described below in StressSearchServiceReaperIT

```
2024-11-13T06:00:50,891][ERROR][o.e.t.LeakTracker        ] [[Cleaner-0]] LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	in [TEST-StressSearchServiceReaperIT.testStressReaper-seed#[348419C7C7365FE]][testStressReaper]
	org.elasticsearch.action.search.ArraySearchPhaseResults.<init>(ArraySearchPhaseResults.java:28)
	org.elasticsearch.action.search.QueryPhaseResultConsumer.<init>(QueryPhaseResultConsumer.java:86)
	org.elasticsearch.action.search.SearchPhaseController.newSearchPhaseResults(SearchPhaseController.java:841)
	org.elasticsearch.action.search.TransportSearchAction$AsyncSearchActionProvider.newSearchPhase(TransportSearchAction.java:1500)
```

closes #115816

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/search/StressSearchServiceReaperIT.java [hunk 1]
```diff
@@ -44,7 +45,16 @@ public void testStressReaper() throws ExecutionException, InterruptedException {
         indexRandom(true, builders);
         final int iterations = scaledRandomIntBetween(500, 1000);
         for (int i = 0; i < iterations; i++) {
-            assertHitCountAndNoFailures(prepareSearch("test").setQuery(matchAllQuery()).setSize(num), num);
+            SearchResponse response = null;
+            try {
+                SearchRequestBuilder searchRequestBuilder = prepareSearch("test").setQuery(matchAllQuery()).setSize(num);
+                response = searchRequestBuilder.get();
+                assertHitCountAndNoFailures(searchRequestBuilder, num);
```
Comment (original-brownbear) [inline server/src/internalClusterTest/java/org/elasticsearch/search/StressSearchServiceReaperIT.java:52]: No sorry this can't be it. The builder is resolved and the response released right away by `assertHitCountAndNoFailures`. If we're leaking it's not because we're leaking the actual search response, we're leaking some intermediary objects and likely never get to the search response here.

See this line in the failure:

```
	org.elasticsearch.action.search.ArraySearchPhaseResults.<init>(ArraySearchPhaseResults.java:28)
```

we're leaking the intermediary per-shard response array, we're not leaking a fully built response.

**Review by original-brownbear — CHANGES_REQUESTED** [review]
See my inline comment, the problem is elsewhere, test code looks good to me.

File: server/src/internalClusterTest/java/org/elasticsearch/search/StressSearchServiceReaperIT.java (hunk 1 above)
Comment (drempapis) [reply server/src/internalClusterTest/java/org/elasticsearch/search/StressSearchServiceReaperIT.java]: Thank you, @original-brownbear, for the feedback. After a private discussion, we decided it was safe to unmute the test.

**Review by original-brownbear — APPROVED** [review]
