### PR TITLE
ES|QL: Restrict sorting for _source and counter field types

### LINKED ISSUE #111976: ES|QL: sorting a counter field shouldn't be possible
### Description

`counter` fields are supported to a degree: when they are casted to their corresponding numerical data type, ie `counter_long::long` should be ok, but `sort counter_long` should.

Now, `sort counter_long` seems to work. We have a test for this but it's a false positive in 40_tsdb.yml:

`from test |  KEEP k8s.pod.network.tx | sort @k8s.pod.network.tx | limit 1` - this one has a typo and the error we throw is that we cannot find `@k8s.pod.network.tx` field, whereas we should have created an error saying the `counter_long` field is unsupported.

### LINKED ISSUE #114423: ES|QL: sort on _source given an unfriendly error
### Description

`from employees metadata _source | sort _source`

```
{
    "error": {
        "root_cause": [
            {
                "type": "esql_illegal_argument_exception",
                "reason": "No TopN sorting encoder for type SOURCE",
                "stack_trace": "org.elasticsearch.xpack.esql.EsqlIllegalArgumentException: No TopN sorting encoder for type SOURCE\r\n\tat org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planTopN(LocalExecutionPlanner.java:360)
```

Quick fix to start with: `Verifier.checkForSortOnSpatialTypes` should be generalized and both geo data types and `_source` should be checked.

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/111976.
Fixes https://github.com/elastic/elasticsearch/issues/114423

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 1]
```diff
@@ -548,12 +548,12 @@ private static Failure validateUnsignedLongNegation(Neg neg) {
     }
 
     /**
-     * Makes sure that spatial types do not appear in sorting contexts.
+     * Some datatypes care not sortable
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:551]:
```suggestion
     * Some datatypes are not sortable
```

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine update branch
