### PR TITLE
[Transform] Improve robustness when saving state

### LINKED ISSUE #51629: [CI] Multicluster transform test failures (yaml=multi_cluster/80_transform/Batch transform from local and remote cluster)
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/3366/console
-- | --
Build Scans | https://gradle-enterprise.elastic.co/s/fx6eksdxojray

Failure:
```
java.lang.AssertionError: Failure at [multi_cluster/80_transform:238]: transforms.0.checkpointing.last.checkpoint didn't match expected value:
transforms.0.checkpointing.last.checkpoint: expected Integer [1] but was Integer [0]

	at __randomizedtesting.SeedInfo.seed([6D89625592739213:E5DD5D8F3C8FFFEB]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: transforms.0.checkpointing.last.checkpoint didn't match expected value:
transforms.0.checkpointing.last.checkpoint: expected Integer [1] but was Integer [0]

	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:93)
	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
	... 37 more
```

I wasn't able to reproduce locally with this:
```
./gradlew ':x-pack:qa:multi-cluster-tests-with-security:mixed-clusterRunner' --tests "org.elasticsearch.multi_cluster.MultiClusterYamlTestSuiteIT.test {yaml=multi_cluster/80_transform/Batch transform from local and remote cluster}" -Dtests.seed=6D89625592739213 -Dtests.security.manager=true -Dtests.locale=sr-Latn-BA -Dtests.timezone=HST -Dcompiler.java=13 -Dtests.rest.suite=multi_cluster
```

### LINKED ISSUE #52035: [Transform] Odd logging of version conflict on stop in rare cases
Followup from: #51629

We use optimistic concurrency control and keep the seq_nr/primary term in an atomic variable, still, when stopping a transform while at the same time it auto-stops, it is possible that 2 save state calls run at the same time from different threads. This is usually only the case if transforms is automated, e.g. this was found via CI.

The issue is benign, no information gets lost. Still it produces these warnings in the log, which is a bad user experience:

```
01:44:49 »  Caused by: org.elasticsearch.index.engine.VersionConflictEngineException: [data_frame_transform_state_and_stats-simple-local-remote-transform]: version conflict, document already exists (current version [1])
01:44:49 »  	at org.elasticsearch.index.engine.InternalEngine.planIndexingAsPrimary(InternalEngine.java:1062) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.index.engine.InternalEngine.indexingStrategyForOperation(InternalEngine.java:1021) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:910) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:813) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:785) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:742) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:254) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:157) ~[elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
01:44:49 »  	... 148 more
01:44:49 » WARN ][o.e.p.AllocatedPersistentTask] [mixed-cluster-0] attempt to complete task [data_frame/transforms[c]] with id [simple-local-remote-transform] in the [COMPLETED] state
```

### LINKED ISSUE #52931: [CI] TransformUsageIT.testUsage fails with incorrect stats call count
In https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/3953/consoleFull / https://gradle-enterprise.elastic.co/s/nobrqofhrecye/tests/vkcr26w2ldob6-j74o4svwlg7nm

The `TransformUsageIT.testUsage` test failed with:

```
java.lang.AssertionError: 
Incorrect stat trigger_count expected:<3.0> but was:<2.0>
at __randomizedtesting.SeedInfo.seed([5671C4D5CB7154:BCF1ED1069B7A9DD]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:553)
at org.elasticsearch.xpack.transform.integration.TransformUsageIT.lambda$testUsage$2(TransformUsageIT.java:105)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:881)
...
```

I was unable to reproduce this on master with:

```
./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformUsageIT.testUsage" -Dtests.seed=5671C4D5CB7154 -Dtests.security.manager=true -Dtests.locale=th-TH -Dtests.timezone=Africa/Bissau -Dcompiler.java=13
```

### LINKED ISSUE #60781: TransformContinuousIT#testContinousEvents can fail with assertion.
**Build scan**: https://gradle-enterprise.elastic.co/s/rexmn4q3oxtry

**Repro line**:
```
./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" -Dtests.seed=729729FBA720DB7C -Dtests.security.manager=true -Dtests.locale=el -Dtests.timezone=MIT -Druntime.java=11
```

**Reproduces locally?**: no.

**Applicable branches**: failure observed on master.

**Failure history**: periodic failures, the earliest of which is from July 30th 2020. It seems to have started failing more frequently on August 5th.

**Failure excerpt**:
```
org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT > testContinousEvents FAILED
    java.lang.AssertionError: Error in test case [continuous-terms-pivot-test].If you want to mute the test, please mute [org.elasticsearch.xpack.transform.integration.continuous.TermsGroupByIT] only, but _not_ [org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT] as a whole.
        at __randomizedtesting.SeedInfo.seed([729729FBA720DB7C:49A158E02D4B592A]:0)
        at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:258)

        Caused by:
        java.lang.AssertionError: Ingest run: 1 did not match max run: 0.0, iteration: 1
        Expected: <0.0>
             but: was <1.0>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.elasticsearch.xpack.transform.integration.continuous.TermsGroupByIT.testIteration(TermsGroupByIT.java:144)
            at 
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
refactor how state is persisted, call doSaveState only from the indexer thread, except there is none.

fixes #60781
fixes #52931
fixes #51629
fixes #52035

### CODE REVIEW

File: x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformIntegTestCase.java [hunk 1]
```diff
@@ -140,6 +142,26 @@ protected StartTransformResponse startTransform(String id, RequestOptions option
         }
     }
 
+    // workaround for https://github.com/elastic/elasticsearch/issues/62204
+    protected StartTransformResponse startTransformWithRetryOnConflict(String id, RequestOptions options) throws Exception {
+        int retries = 10;
+        ElasticsearchStatusException lastConflict = null;
+        while (retries > 0) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformIntegTestCase.java:149]: `for` loop could be used here as well, making this snippet more concise:
```
for (int retries = 10; retries > 0; --retries) {
}
```

File: x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformIntegTestCase.java [hunk 2]
```diff
@@ -140,6 +142,26 @@ protected StartTransformResponse startTransform(String id, RequestOptions option
...
+            try (RestHighLevelClient restClient = new TestRestHighLevelClient()) {
+                return restClient.transform().startTransform(new StartTransformRequest(id), options);
+            } catch (ElasticsearchStatusException e) {
+                if (e.status().equals(RestStatus.CONFLICT) == false) {
```
Comment (przemekwitek) [inline x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformIntegTestCase.java:153]: [nit] It's rather style issue, not a real problem here, but I would write this line:
```
                if (RestStatus.CONFLICT.equals(e.status()) == false) {
```

so that NPE is impossible (even theoretically).

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java [hunk 3]
```diff
@@ -244,6 +244,17 @@ public synchronized boolean maybeTriggerAsyncJob(long now) {
         }
     }
 
+    /**
+     * Checks if the state should be persisted, if true doSaveState is called before continuing. Inherited classes
+     * can overwrite this, to provide a better logic, when state should be saved.
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java:249]:
```suggestion
     * can override this, to provide a better logic, when state should be saved.
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java [hunk 4]
```diff
@@ -254,7 +265,16 @@ protected void rethrottle() {
...
-        reQueueThrottledSearch();
+        reQueueThrottledSearch(false);
+    }
+
+    /**
+     * Re-schedules the current search request to run immediately, iff one is scheduled.
+     *
+     * Call this if you need the indexer to fast forward a scheduled(throttled) search once in order to complete a full cycle.
+     */
+    protected void runSearchImmediatly() {
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java:276]:
```suggestion
    protected void runSearchImmediately() {
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java [hunk 5]
```diff
@@ -254,7 +265,16 @@ protected void rethrottle() {
...
         }
 
-        reQueueThrottledSearch();
+        reQueueThrottledSearch(false);
+    }
+
+    /**
+     * Re-schedules the current search request to run immediately, iff one is scheduled.
+     *
+     * Call this if you need the indexer to fast forward a scheduled(throttled) search once in order to complete a full cycle.
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java:274]:
```suggestion
     * Call this if you need the indexer to fast forward a scheduled (throttled) search once in order to complete a full cycle.
```

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java [hunk 6]
```diff
@@ -299,7 +295,7 @@ void setShouldStopAtCheckpoint(boolean shouldStopAtCheckpoint) {
      * @param shouldStopAtCheckpoint whether or not we should stop at the next checkpoint or not
      * @param shouldStopAtCheckpointListener the listener to return to when we have persisted the updated value to the state index.
      */
-    public synchronized void setShouldStopAtCheckpoint(
+    public void setShouldStopAtCheckpoint(
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:298]: Since this is no longer synchronized, it is possible for a `stop` call or a `start` call to be executing at any point. 

Is this acceptable?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 7]
```diff
@@ -508,6 +518,43 @@ protected void onAbort() {
...
     }
 
+    protected void callAndResetSaveStateListeners() {
+        Collection<ActionListener<Void>> listeners = saveStateListeners.getAndSet(null);
+        if (listeners != null) {
+            for (ActionListener<Void> l : listeners) {
+                l.onResponse(null);
+            }
+        }
+    }
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:528]: This always assumes that the saving state succeeds. If saving the state fails, the listeners are never called.

Comment (benwtrent) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:528]: It also seems to me that a previous save state could be getting called (its listener executing), and these listeners get triggered. But, it is not their current state (e.g. the one with "stop at checkpoint") that was saved, but the previous one that was in the middle of saving.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java (hunk 6 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:298]: with the atomic ops in `stopAtCheckpoint`, I think we can get rid of _synchronized_. I can not think of any bad collision with `stop` and `start`.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java (hunk 7 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java]: good spot! I changed the implementation to get and reset the listener before calling save state. I think that covers it. Now its possible that "stop at checkpoint" is set after the listeners are taken, but this is benign, I added comments in code.

**Comment by hendrikmuhs** [comment]
Thanks @przemekwitek and @benwtrent, I addressed your comments.

File: x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformIntegTestCase.java [hunk 8]
```diff
@@ -140,6 +142,25 @@ protected StartTransformResponse startTransform(String id, RequestOptions option
...
+        for (int retries = 10; retries > 0; --retries) {
+            try (RestHighLevelClient restClient = new TestRestHighLevelClient()) {
+                return restClient.transform().startTransform(new StartTransformRequest(id), options);
+            } catch (ElasticsearchStatusException e) {
+                if (RestStatus.CONFLICT.equals(e.status()) == false) {
+                    throw e;
+                }
+
+                lastConflict = e;
+                --retries;
```
Comment (przemekwitek) [inline x-pack/plugin/transform/qa/multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformIntegTestCase.java:157]: This line is not needed anymore.

**Review by przemekwitek — APPROVED** [review]
LGTM

I've left one small comment but there is no need for another review.

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 9]
```diff
@@ -508,6 +522,89 @@ protected void onAbort() {
...
+    synchronized void setStopAtCheckpoint(boolean shouldStopAtCheckpoint, ActionListener<Void> shouldStopAtCheckpointListener) {
+        IndexerState state = getState();
+
+        // in case the indexer isn't running, respond immediately
+        if (state == IndexerState.STARTED && context.shouldStopAtCheckpoint() != shouldStopAtCheckpoint) {
+            context.setShouldStopAtCheckpoint(shouldStopAtCheckpoint);
+
+            // because save state is async we need to block the call until state is persisted, so that the job can not
+            // be triggered
+            CountDownLatch latch = new CountDownLatch(1);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:539]: Could you adjust the comment indicating that this is because the method is `synchronized`? It took me a second to see that all the triggering methods, etc. were synchronized. 

Also, it might be good to make this method `final` so it cannot be overridden and consequently cause MT issues in the future by accident.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 10]
```diff
@@ -508,6 +522,89 @@ protected void onAbort() {
...
+            try {
+                doSaveState(IndexerState.STARTED, getPosition(), () -> {
+                    latch.countDown();
+                    shouldStopAtCheckpointListener.onResponse(null);
+                });
+
+                latch.await(PERSIST_STOP_AT_CHECKPOINT_TIMEOUT_SEC, TimeUnit.SECONDS);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:546]: I think this method call stack goes all the way back to the transport layer:

https://github.com/elastic/elasticsearch/blob/95a7eed9aa35f47b228e402508709b5bd6703cf4/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStopTransformAction.java#L219-L228

Consequently, do we know what threadpool we will be locking up for 5 seconds?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java (hunk 6 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java]: FWIW: I added _synchronized_ back, but 1 level down in the indexer, as I realized a corner case: >1 calls to at the same time or triggering while this is running.

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/packaging-sample-windows

**Review by benwtrent — APPROVED** [review]
I think all the branches are covered.

Not a huge fan of a latch away within a sync block. But, this distributed synchronizing of 3 separate mutable state values is getting out of hand. 

Our testing should catch any weird conditions over time.

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro
run elasticsearch-ci/packaging-sample-windows

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

(one last round :-) )

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 11]
```diff
@@ -508,6 +522,100 @@ protected void onAbort() {
...
     }
 
+    /**
+     * Let the indexer stop at the next checkpoint and call the listener after the flag has been persisted in state.
+     *
+     * If the indexer isn't running, persist state if required and call the listener immediately.
+     */
+    final void setStopAtCheckpoint(boolean shouldStopAtCheckpoint, ActionListener<Void> shouldStopAtCheckpointListener) {
+        // this should be called from the generic threadpool
+        assert Thread.currentThread().getName().contains(ThreadPool.Names.GENERIC);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:532]: In testing (or where assertions are enabled), this would cause the caller to freeze and never return.

I am not sure how to assert here AND fire an `onFailure` result. But, not doing so might cause some frustrating test investigations

**Review by benwtrent — APPROVED** [review]
