### PR TITLE
Fix bwc cluster formation in order to run BWC tests against a mixed version cluster

### LINKED ISSUE #21142: Backwards tests do not start BWC nodes with the right version
The integration test in qa/backwards-5.0 tries to start a node on the current version and BWC version. When setting this to 5.0.0, the test suite does not correctly start a node on 5.0.0 and a node on 5.0.1-SNAPSHOT; instead it starts two nodes on 5.0.0.

### PR DESCRIPTION
**Pull request by s1monw**
This fixes our cluster formation task to run REST tests against a mixed version cluster.
Yet, due to some limitations in our test framework `indices.rollover` tests are currently
disabled for the BWC case since they select the current master as the merge node which
happens to be a BWC node and we can't relocate all shards to it since the primaries are on
a higher version node. This will be fixed in a followup.

Closes #21142

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]
LGTM

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy [hunk 1]
```diff
@@ -85,11 +85,11 @@ class ClusterFormationTasks {
             }
             configureDistributionDependency(project, config.distribution, project.configurations.elasticsearchBwcDistro, config.bwcVersion)
         }
-
-        for (int i = 0; i < config.numNodes; ++i) {
+        for (int i = 0; i < config.numNodes; i++) {
             // we start N nodes and out of these N nodes there might be M bwc nodes.
             // for each of those nodes we might have a different configuratioon
             String elasticsearchVersion = VersionProperties.elasticsearch
+            Configuration distro = currentDistro
```
Comment (jasontedor) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: Aha, there it is!

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @s1monw.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy (hunk 1 above)
Comment (s1monw) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: ;)
