### PR TITLE
[Test] Fix S3ServiceTests.testRetryOn403RetryPolicy

### LINKED ISSUE #115986: [CI] S3ServiceTests testRetryOn403RetryPolicy failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4619 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/x4uew3v7qixao)
- [elasticsearch-pull-request #39051 / part-1](https://gradle-enterprise.elastic.co/s/4acfvatvvz356)
- [elasticsearch-pull-request #38879 / part-1](https://gradle-enterprise.elastic.co/s/vtezlmj6pewok)
- [elasticsearch-periodic #4618 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ontbrfd7pcjei)

**Reproduction Line:**
```
./gradlew ":modules:repository-s3:test" --tests "org.elasticsearch.repositories.s3.S3ServiceTests.testRetryOn403RetryPolicy" -Dtests.seed=BF0C337BCF56BD88 -Dtests.locale=en-PN -Dtests.timezone=America/Argentina/Salta -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.s3.S3ServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRetryOn403RetryPolicy),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 4 failures in test testRetryOn403RetryPolicy (0.8% fail rate in 490 executions)
- [main] 2 failures in step part-1 (0.9% fail rate in 234 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 232 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
AWS's default retry condition defines a list of retryable error status. They are retryable for the custom retryable_403 condition as well. This PR enhances the test to excercise this logic correctly.

Resolves: #115986

### CODE REVIEW

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ServiceTests.java [hunk 1]
```diff
@@ -47,19 +48,36 @@ public void testRetryOn403RetryPolicy() {
...
+                assertTrue(
+                    S3Service.RETRYABLE_403_RETRY_POLICY.getRetryCondition()
+                        .shouldRetry(mock(AmazonWebServiceRequest.class), e, between(0, 9))
+                );
+            } else {
+                assertFalse(
+                    S3Service.RETRYABLE_403_RETRY_POLICY.getRetryCondition()
+                        .shouldRetry(mock(AmazonWebServiceRequest.class), e, between(0, 9))
+                );
+            }
```
Comment (henningandersen) [inline modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ServiceTests.java:74]: I would find something like this easier to read:

```suggestion
            boolean actual = S3Service.RETRYABLE_403_RETRY_POLICY.getRetryCondition()
                        .shouldRetry(mock(AmazonWebServiceRequest.class), e, between(0, 9));
            boolean expected  = PredefinedRetryPolicies.DEFAULT_RETRY_CONDITION.shouldRetry(mock(AmazonWebServiceRequest.class), e, between(0, 9));
            assertThat(actual, equals(expected));
```

**Review by henningandersen — APPROVED** [review]
LGTM.

Left one optional comment/suggestion.

**Comment by ywangd** [comment]
@elasticmachine update branch
