### PR TITLE
Ingest does not close its factories

### LINKED ISSUE #17625: Ingest does not close its factories
When you implement an ingest factory which implements `Closeable`:

```java
public static final class Factory extends AbstractProcessorFactory<MyProcessor> implements Closeable {
    @Override
    public void close() throws IOException {
        logger.debug("closing my processor factory");
    }
}
```

The `close()` method is never called which could lead to some leak threads when we close a node.

The `ProcessorsRegistry#close()` method exists though and seems to do the right job:

```java
@Override
public void close() throws IOException {
    List<Closeable> closeables = new ArrayList<>();
    for (Processor.Factory factory : processorFactories.values()) {
        if (factory instanceof Closeable) {
            closeables.add((Closeable) factory);
        }
    }
    IOUtils.close(closeables);
}
```

But apparently this method is never called in `Node#stop()`.

### PR DESCRIPTION
**Pull request by dadoonet**
When you implement an ingest factory which implements `Closeable`:

``` java
public static final class Factory extends AbstractProcessorFactory<MyProcessor> implements Closeable {
    @Override
    public void close() throws IOException {
        logger.debug("closing my processor factory");
    }
}
```

The `close()` method is never called which could lead to some leak threads when we close a node.

The `ProcessorsRegistry#close()` method exists though and seems to do the right job:

``` java
@Override
public void close() throws IOException {
    List<Closeable> closeables = new ArrayList<>();
    for (Processor.Factory factory : processorFactories.values()) {
        if (factory instanceof Closeable) {
            closeables.add((Closeable) factory);
        }
    }
    IOUtils.close(closeables);
}
```

But apparently this method is never called in `Node#stop()`.

Closes #17625.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/ingest/IngestService.java [hunk 1]
```diff
@@ -70,6 +70,7 @@ public IngestInfo info() {
 
     @Override
     public void close() throws IOException {
+        pipelineStore.getProcessorRegistry().close();
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/ingest/IngestService.java]: I think isn't needed as the registry is closed via the pipeline store.

**Comment by martijnvg** [comment]
I left a comment. Looks good, but we need a test for this. What I think what would work is if we write a test that extends from `ESIntegTestCase` that registers a test processor that keeps track if close is invoked. In that test we start just one node and then stop it and then check is the test processor's close has been invoked.

(`IngestClientIT` is an example to look at for how to register a test processor)

**Comment by dadoonet** [comment]
> What I think what would work is if we write a test that extends from ESIntegTestCase that registers a test processor that keeps track if close is invoked. In that test we start just one node and then stop it and then check is the test processor's close has been invoked.

That's exactly what I initially started to do but I did not find how to manually start and stop a node. 
I'll dig into this more. Thanks!

**Comment by rjernst** [comment]
> I did not find how to manually start and stop a node

Use an `ESSingleNodeTestCase`?

**Comment by martijnvg** [comment]
> Use an ESSingleNodeTestCase?

That is even better. I forgot that via this base test has `getPlugins()` which tests can override.

**Comment by dadoonet** [comment]
Thanks guys. I added a new commit.

File: core/src/test/java/org/elasticsearch/ingest/IngestCloseIT.java [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+        public void onModule(NodeModule nodeModule) {
+            nodeModule.registerProcessor("test", (templateService, registry) -> new Factory());
+        }
+    }
+
+    public static final class Factory extends AbstractProcessorFactory<TestProcessor> implements Closeable {
+        @Override
+        protected TestProcessor doCreate(String tag, Map<String, Object> config) throws Exception {
+            return new TestProcessor("id", "test", ingestDocument -> {
+                ingestDocument.setFieldValue("processed", true);
```
Comment (martijnvg) [inline core/src/test/java/org/elasticsearch/ingest/IngestCloseIT.java]: maybe replace this code with an unsupported operation exception, since it isn't expected to be called in this test?

**Comment by martijnvg** [comment]
@dadoonet Left one minor comment. LGTM.

File: core/src/test/java/org/elasticsearch/ingest/IngestCloseIT.java (hunk 2 above)
Comment (dadoonet) [inline core/src/test/java/org/elasticsearch/ingest/IngestCloseIT.java]: Sure. Fixed with https://github.com/elastic/elasticsearch/commit/cc4fb61a38926b593a0c8f5834c7154aea835b53

**Comment by dadoonet** [comment]
Thanks @martijnvg!
