### PR TITLE
Set LIBFFI_TMPDIR at startup

### LINKED ISSUE #18272: Elasticsearch 2.2 fails to start with jna tmp dir configured (core dump)
**Elasticsearch version** 2.2

**JVM version**: 1.7.0_75

**OS version**: CentOS release 6.7

**Description of the problem including expected versus actual behavior**:
Starting elasticsearch fails to start if the following is added to the /etc/sysconfig/elasticsearch file:
```
# Additional Java OPTS
ES_JAVA_OPTS="-Djna.tmpdir=/usr/share/elasticsearch/tmp -Djava.io.tmpdir=/usr/share/elasticsearch/tmp"
```
With this line commented out, ES starts but JNA is disabled as the default /tmp/ directory is mounted with noexec. If /tmp/ is mounted without noexec all works as expected.
/usr/share/elasticsearch/tmp exists, belongs to the right user/group and has permissions 755.

**Steps to reproduce**:
```
[root@storagenode01 ~]# service elasticsearch start
Starting elasticsearch: /usr/share/elasticsearch/bin/elasticsearch: line 155: 28878 Aborted                 (core dumped) exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" org.elasticsearch.bootstrap.Elasticsearch start "$@" 0>&-
                                                           [FAILED]
```

**Provide logs (if relevant)**:
```
[root@storagenode01 ~]# cat /tmp/hs_err_pid28216.log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f424226f40a, pid=28216, tid=139922878629632
#
# JRE version: Java(TM) SE Runtime Environment (7.0_75-b13) (build 1.7.0_75-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [jna4948368637624641726.tmp+0x1240a]  ffi_prep_closure_loc+0x1a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f424c00a000):  JavaThread "main" [_thread_in_native, id=28218, stack(0x00007f42556a0000,0x00007f42557a1000)]

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=1 (SEGV_MAPERR), si_addr=0x0000000000000000

Registers:
RAX=0x00007f424226f8c2, RBX=0x00007f425579ed48, RCX=0x00007f424c44a7b0, RDX=0x00007f4242264590
RSP=0x00007f425579eae0, RBP=0x00007f425579eae0, RSI=0x00007f424c44a7d0, RDI=0x0000000000000000
R8 =0x00007f425007ae43, R9 =0x0000000000000002, R10=0x00007f425579e870, R11=0x00007f424226f3f0
R12=0x0000000000000000, R13=0x0000000000000008, R14=0x00007f424c44a7b0, R15=0x0000000000000004
RIP=0x00007f424226f40a, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000006
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f425579eae0)
0x00007f425579eae0:   00007f425579ebb0 00007f424226a4dd
0x00007f425579eaf0:   0000000000000005 00007f425579ed38
0x00007f425579eb00:   00007f425579ed50 00007f424c00a1e8
0x00007f425579eb10:   0000000100000000 00007f424c44a940
0x00007f425579eb20:   00007f424c450f70 00007f424c44a7d0
0x00007f425579eb30:   000000015579eca0 00007f424c44a980
0x00007f425579eb40:   00007f424c44a960 00007f424c44a790
0x00007f425579eb50:   0000000000000001 000000035579ed48
0x00007f425579eb60:   00007f425579ed40 00007f425579ed38
0x00007f425579eb70:   00007f4200000000 00007f425007ae43
0x00007f425579eb80:   00000000fb599510 00000000fb599510
0x00007f425579eb90:   0000000000000000 00000000fb599510
0x00007f425579eba0:   00007f425579ed50 00007f424c00a000
0x00007f425579ebb0:   00007f425579eca0 00007f425006fd98
0x00007f425579ebc0:   00007f425579ed30 00007f425579ed28
0x00007f425579ebd0:   0000000000000002 00007f4242271eb0
0x00007f425579ebe0:   00007f4242271eb0 00007f425579ecf8
0x00007f425579ebf0:   00007f4254c43f70 0000000000000000
0x00007f425579ec00:   0000000000000000 00007f425579ecd0
0x00007f425579ec10:   0000000000000000 00007f425579ecc0
0x00007f425579ec20:   00007f425579eda8 00007f425579ecc0
0x00007f425579ec30:   00007f424c00a998 00007f4243a48f90
0x00007f425579ec40:   0000000900000010 0000000c00000024
0x00007f425579ec50:   00007f424c00a000 00007f42000000b6
0x00007f425579ec60:   00007f425579ec60 00000000fb599510
0x00007f425579ec70:   00007f425579ed50 00000000fb59f350
0x00007f425579ec80:   0000000000000000 00000000fb599510
0x00007f425579ec90:   0000000000000000 00007f425579ecc0
0x00007f425579eca0:   00007f425579eda8 00007f4250063175
0x00007f425579ecb0:   00000000bbc87fb8 00007f425006bcd7
0x00007f425579ecc0:   00000000bae0d660 0000000000000000
0x00007f425579ecd0:   00000000bbd64530 0000000000000000

Instructions: (pc=0x00007f424226f40a)
0x00007f424226f3ea:   66 90 66 66 66 90 8b 06 55 41 b9 02 00 00 00 48
0x00007f424226f3fa:   89 e5 ff c8 83 f8 01 77 44 48 8b 05 c6 49 10 00
0x00007f424226f40a:   66 c7 07 49 bb 4c 89 47 0c 66 c7 47 0a 49 ba 48
0x00007f424226f41a:   89 47 02 8b 46 1c 48 89 77 18 48 89 57 20 48 89

Register to memory mapping:

RAX=0x00007f424226f8c2: ffi_closure_unix64+0 in /usr/share/elasticsearch/tmp/jna4948368637624641726.tmp at 0x00007f424225d000
RBX=0x00007f425579ed48 is pointing into the stack for thread: 0x00007f424c00a000
RCX=0x00007f424c44a7b0 is an unknown value
RDX=0x00007f4242264590: <offset 0x7590> in /usr/share/elasticsearch/tmp/jna4948368637624641726.tmp at 0x00007f424225d000
RSP=0x00007f425579eae0 is pointing into the stack for thread: 0x00007f424c00a000
RBP=0x00007f425579eae0 is pointing into the stack for thread: 0x00007f424c00a000
RSI=0x00007f424c44a7d0 is an unknown value
RDI=0x0000000000000000 is an unknown value
R8 =0x00007f425007ae43 is at code_begin+99 in an Interpreter codelet
invokestatic  184 invokestatic  [0x00007f425007ade0, 0x00007f425007af20]  320 bytes
R9 =0x0000000000000002 is an unknown value
R10=0x00007f425579e870 is pointing into the stack for thread: 0x00007f424c00a000
R11=0x00007f424226f3f0: ffi_prep_closure_loc+0 in /usr/share/elasticsearch/tmp/jna4948368637624641726.tmp at 0x00007f424225d000
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000008 is an unknown value
R14=0x00007f424c44a7b0 is an unknown value
R15=0x0000000000000004 is an unknown value


Stack: [0x00007f42556a0000,0x00007f42557a1000],  sp=0x00007f425579eae0,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jna4948368637624641726.tmp+0x1240a]  ffi_prep_closure_loc+0x1a
C  [jna4948368637624641726.tmp+0xd4dd]  Java_com_sun_jna_Native_registerMethod+0x45d
j  com.sun.jna.Native.registerMethod(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;[I[J[JIJJLjava/lang/Class;JIZ[Lcom/sun/jna/ToNativeConverter;Lcom/sun/jna/FromNativeConverter;Ljava/lang/String;)J+0
j  com.sun.jna.Native.register(Ljava/lang/Class;Lcom/sun/jna/NativeLibrary;)V+979
j  com.sun.jna.Native.register(Ljava/lang/Class;Ljava/lang/String;)V+28
j  com.sun.jna.Native.register(Ljava/lang/String;)V+7
j  org.elasticsearch.bootstrap.JNACLibrary.<clinit>()V+45
v  ~StubRoutines::call_stub
V  [libjvm.so+0x600045]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x365
V  [libjvm.so+0x5feaa8]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.so+0x5c2f1a]  instanceKlass::call_class_initializer(Thread*)+0xca
V  [libjvm.so+0x5c3174]  instanceKlass::initialize_impl(instanceKlassHandle, Thread*)+0x234
V  [libjvm.so+0x5c35ca]  instanceKlass::initialize(Thread*)+0x6a
V  [libjvm.so+0x74454e]  LinkResolver::resolve_static_call(CallInfo&, KlassHandle&, Symbol*, Symbol*, KlassHandle, bool, bool, Thread*)+0x11e
V  [libjvm.so+0x7446b6]  LinkResolver::resolve_invokestatic(CallInfo&, constantPoolHandle, int, Thread*)+0xe6
V  [libjvm.so+0x5f846f]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x17f
j  org.elasticsearch.bootstrap.JNANatives.definitelyRunningAsRoot()Z+8
j  org.elasticsearch.bootstrap.Natives.definitelyRunningAsRoot()Z+22
j  org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Ljava/nio/file/Path;ZZZ)V+8
j  org.elasticsearch.bootstrap.Bootstrap.setup(ZLorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/env/Environment;)V+43
j  org.elasticsearch.bootstrap.Bootstrap.init([Ljava/lang/String;)V+238
j  org.elasticsearch.bootstrap.Elasticsearch.main([Ljava/lang/String;)V+1
v  ~StubRoutines::call_stub
V  [libjvm.so+0x600045]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x365
V  [libjvm.so+0x5feaa8]  JavaCalls::call(JavaValue*, methodHandle, JavaCallArguments*, Thread*)+0x28
V  [libjvm.so+0x638a59]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x219
V  [libjvm.so+0x641672]  jni_CallStaticVoidMethod+0x162
C  [libjli.so+0x36d9]  JavaMain+0x7e9

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.registerMethod(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;[I[J[JIJJLjava/lang/Class;JIZ[Lcom/sun/jna/ToNativeConverter;Lcom/sun/jna/FromNativeConverter;Ljava/lang/String;)J+0
j  com.sun.jna.Native.register(Ljava/lang/Class;Lcom/sun/jna/NativeLibrary;)V+979
j  com.sun.jna.Native.register(Ljava/lang/Class;Ljava/lang/String;)V+28
j  com.sun.jna.Native.register(Ljava/lang/String;)V+7
j  org.elasticsearch.bootstrap.JNACLibrary.<clinit>()V+45
v  ~StubRoutines::call_stub
j  org.elasticsearch.bootstrap.JNANatives.definitelyRunningAsRoot()Z+8
j  org.elasticsearch.bootstrap.Natives.definitelyRunningAsRoot()Z+22
j  org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Ljava/nio/file/Path;ZZZ)V+8
j  org.elasticsearch.bootstrap.Bootstrap.setup(ZLorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/env/Environment;)V+43
j  org.elasticsearch.bootstrap.Bootstrap.init([Ljava/lang/String;)V+238
j  org.elasticsearch.bootstrap.Elasticsearch.main([Ljava/lang/String;)V+1
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00007f424c11e000 JavaThread "Service Thread" daemon [_thread_blocked, id=28231, stack(0x00007f4242f6c000,0x00007f424306d000)]
  0x00007f424c11b000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=28230, stack(0x00007f424306d000,0x00007f424316e000)]
  0x00007f424c119000 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=28229, stack(0x00007f424316e000,0x00007f424326f000)]
  0x00007f424c116800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=28228, stack(0x00007f424326f000,0x00007f4243370000)]
  0x00007f424c114800 JavaThread "Surrogate Locker Thread (Concurrent GC)" daemon [_thread_blocked, id=28227, stack(0x00007f4243370000,0x00007f4243471000)]
  0x00007f424c0eb800 JavaThread "Finalizer" daemon [_thread_blocked, id=28226, stack(0x00007f4243471000,0x00007f4243572000)]
  0x00007f424c0e9800 JavaThread "Reference Handler" daemon [_thread_blocked, id=28225, stack(0x00007f4243572000,0x00007f4243673000)]
=>0x00007f424c00a000 JavaThread "main" [_thread_in_native, id=28218, stack(0x00007f42556a0000,0x00007f42557a1000)]

Other Threads:
  0x00007f424c0e5000 VMThread [stack: 0x00007f4243673000,0x00007f4243774000] [id=28224]
  0x00007f424c129000 WatcherThread [stack: 0x00007f4242e6b000,0x00007f4242f6c000] [id=28232]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap
 par new generation   total 78656K, used 16826K [0x00000000bae00000, 0x00000000c0350000, 0x00000000cfac0000)
  eden space 69952K,  24% used [0x00000000bae00000, 0x00000000bbe6e950, 0x00000000bf250000)
  from space 8704K,   0% used [0x00000000bf250000, 0x00000000bf250000, 0x00000000bfad0000)
  to   space 8704K,   0% used [0x00000000bfad0000, 0x00000000bfad0000, 0x00000000c0350000)
 concurrent mark-sweep generation total 174784K, used 0K [0x00000000cfac0000, 0x00000000da570000, 0x00000000fae00000)
 concurrent-mark-sweep perm gen total 21248K, used 8193K [0x00000000fae00000, 0x00000000fc2c0000, 0x0000000100000000)

Card table byte_map: [0x00007f424bad3000,0x00007f424bcfd000] byte_map_base: 0x00007f424b4fc000

Polling page: 0x00007f42557ac000

Code Cache  [0x00007f425005d000, 0x00007f42502cd000, 0x00007f425305d000)
 total_blobs=312 nmethods=36 adapters=230 free_code_cache=48617Kb largest_free_block=49754112

Compilation events (10 events):
Event: 0.281 Thread 0x00007f424c119000 nmethod 32 0x00007f42500cd2d0 code [0x00007f42500cd420, 0x00007f42500cd518]
Event: 0.282 Thread 0x00007f424c119000   33   !         sun.misc.URLClassPath$JarLoader::getResource (91 bytes)
Event: 0.304 Thread 0x00007f424c119000 nmethod 33 0x00007f42500de510 code [0x00007f42500de8c0, 0x00007f42500e0128]
Event: 0.304 Thread 0x00007f424c119000   34             java.util.Arrays::copyOf (19 bytes)
Event: 0.305 Thread 0x00007f424c119000 nmethod 34 0x00007f42500de0d0 code [0x00007f42500de220, 0x00007f42500de3f8]
Event: 0.306 Thread 0x00007f424c11b000 nmethod 31 0x00007f42500e5650 code [0x00007f42500e5a20, 0x00007f42500e7288]
Event: 0.313 Thread 0x00007f424c119000   35             java.util.Arrays::copyOfRange (63 bytes)
Event: 0.317 Thread 0x00007f424c119000 nmethod 35 0x00007f42500d6d90 code [0x00007f42500d6ee0, 0x00007f42500d70f8]
Event: 0.327 Thread 0x00007f424c11b000   36             java.lang.String::<init> (67 bytes)
Event: 0.329 Thread 0x00007f424c11b000 nmethod 36 0x00007f42500d6810 code [0x00007f42500d6960, 0x00007f42500d6bd8]

GC Heap History (0 events):
No events

Deoptimization events (1 events):
Event: 0.189 Thread 0x00007f424c00a000 Uncommon trap: reason=null_check action=make_not_entrant pc=0x00007f42500c0a60 method=java.lang.String.equals(Ljava/lang/Object;)Z @ 8

Internal exceptions (10 events):
Event: 0.330 Thread 0x00007f424c00a000 Threw 0x00000000bbd50128 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.332 Thread 0x00007f424c00a000 Threw 0x00000000bbd64960 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.332 Thread 0x00007f424c00a000 Threw 0x00000000bbd6bde8 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.332 Thread 0x00007f424c00a000 Threw 0x00000000bbd6f078 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.333 Thread 0x00007f424c00a000 Threw 0x00000000bbd71ef8 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.333 Thread 0x00007f424c00a000 Threw 0x00000000bbd75608 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.333 Thread 0x00007f424c00a000 Threw 0x00000000bbd87288 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.334 Thread 0x00007f424c00a000 Threw 0x00000000bbd8a530 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.334 Thread 0x00007f424c00a000 Threw 0x00000000bbd8d850 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281
Event: 0.334 Thread 0x00007f424c00a000 Threw 0x00000000bbd90b70 at /HUDSON/workspace/7u-2-build-linux-amd64/jdk7u75/1940/hotspot/src/share/vm/prims/jvm.cpp:1281

Events (10 events):
Event: 0.333 loading class 0x00007f424c43de50
Event: 0.333 loading class 0x00007f424c43de50 done
Event: 0.333 loading class 0x00007f424c44a060
Event: 0.333 loading class 0x00007f424c44a060 done
Event: 0.334 loading class 0x00007f424c44a0a0
Event: 0.334 loading class 0x00007f424c44a0a0 done
Event: 0.334 loading class 0x00007f424c44a200
Event: 0.334 loading class 0x00007f424c44a200 done
Event: 0.334 loading class 0x00007f424c44a240
Event: 0.334 loading class 0x00007f424c44a240 done


Dynamic libraries:
00400000-00401000 r-xp 00000000 fd:00 19763                              /usr/java/jdk1.7.0_75/bin/java
00600000-00601000 rw-p 00000000 fd:00 19763                              /usr/java/jdk1.7.0_75/bin/java
00f22000-00f43000 rw-p 00000000 00:00 0                                  [heap]
bae00000-c0350000 rw-p 00000000 00:00 0
c0350000-cfac0000 rw-p 00000000 00:00 0
cfac0000-da570000 rw-p 00000000 00:00 0
da570000-fae00000 rw-p 00000000 00:00 0
fae00000-fc2c0000 rw-p 00000000 00:00 0
fc2c0000-100000000 rw-p 00000000 00:00 0
7f4200000000-7f4200021000 rw-p 00000000 00:00 0
7f4200021000-7f4204000000 ---p 00000000 00:00 0
7f4208000000-7f42082fd000 rw-p 00000000 00:00 0
7f42082fd000-7f420c000000 ---p 00000000 00:00 0
7f420c000000-7f420c021000 rw-p 00000000 00:00 0
7f420c021000-7f4210000000 ---p 00000000 00:00 0
7f4210000000-7f4210021000 rw-p 00000000 00:00 0
7f4210021000-7f4214000000 ---p 00000000 00:00 0
7f4214000000-7f421442f000 rw-p 00000000 00:00 0
7f421442f000-7f4218000000 ---p 00000000 00:00 0
7f4218000000-7f4218021000 rw-p 00000000 00:00 0
7f4218021000-7f421c000000 ---p 00000000 00:00 0
7f421e16f000-7f4224000000 r--p 00000000 fd:00 11888                      /usr/lib/locale/locale-archive
7f4224000000-7f4224021000 rw-p 00000000 00:00 0
7f4224021000-7f4228000000 ---p 00000000 00:00 0
7f4228000000-7f4228021000 rw-p 00000000 00:00 0
7f4228021000-7f422c000000 ---p 00000000 00:00 0
7f422c000000-7f422c021000 rw-p 00000000 00:00 0
7f422c021000-7f4230000000 ---p 00000000 00:00 0
7f4230000000-7f4230021000 rw-p 00000000 00:00 0
7f4230021000-7f4234000000 ---p 00000000 00:00 0
7f4234000000-7f4234021000 rw-p 00000000 00:00 0
7f4234021000-7f4238000000 ---p 00000000 00:00 0
7f4238000000-7f4238021000 rw-p 00000000 00:00 0
7f4238021000-7f423c000000 ---p 00000000 00:00 0
7f423c000000-7f423c021000 rw-p 00000000 00:00 0
7f423c021000-7f4240000000 ---p 00000000 00:00 0
7f4242015000-7f424225d000 rw-p 00000000 00:00 0
7f424225d000-7f4242274000 r-xp 00000000 fd:00 3301                       /usr/share/elasticsearch/tmp/jna4948368637624641726.tmp (deleted)
7f4242274000-7f4242373000 ---p 00017000 fd:00 3301                       /usr/share/elasticsearch/tmp/jna4948368637624641726.tmp (deleted)
7f4242373000-7f4242375000 rw-p 00016000 fd:00 3301                       /usr/share/elasticsearch/tmp/jna4948368637624641726.tmp (deleted)
7f4242375000-7f424237d000 r-xp 00000000 fd:00 19924                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libmanagement.so
7f424237d000-7f424257c000 ---p 00008000 fd:00 19924                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libmanagement.so
7f424257c000-7f424257d000 rw-p 00007000 fd:00 19924                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libmanagement.so
7f424257d000-7f424258d000 r-xp 00000000 fd:00 19927                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libnio.so
7f424258d000-7f424278d000 ---p 00010000 fd:00 19927                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libnio.so
7f424278d000-7f424278e000 rw-p 00010000 fd:00 19927                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libnio.so
7f424278e000-7f4242a8e000 rw-p 00000000 00:00 0
7f4242a8e000-7f4242aa4000 r-xp 00000000 fd:00 19926                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libnet.so
7f4242aa4000-7f4242ca4000 ---p 00016000 fd:00 19926                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libnet.so
7f4242ca4000-7f4242ca5000 rw-p 00016000 fd:00 19926                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libnet.so
7f4242ca5000-7f4242cad000 r--s 00062000 fd:00 22811                      /usr/share/elasticsearch/lib/lucene-backward-codecs-5.4.1.jar
7f4242cad000-7f4242cb1000 r--s 0002c000 fd:00 22821                      /usr/share/elasticsearch/lib/lucene-spatial-5.4.1.jar
7f4242cb1000-7f4242cb2000 r--s 00001000 fd:00 22825                      /usr/share/elasticsearch/lib/securesm-1.0.jar
7f4242cb2000-7f4242cdd000 r--s 001fc000 fd:00 22502                      /usr/share/elasticsearch/lib/guava-18.0.jar
7f4242cdd000-7f4242ce1000 r--s 0002d000 fd:00 22822                      /usr/share/elasticsearch/lib/lucene-spatial3d-5.4.1.jar
7f4242ce1000-7f4242ceb000 r--s 00059000 fd:00 22819                      /usr/share/elasticsearch/lib/lucene-queryparser-5.4.1.jar
7f4242ceb000-7f4242cf1000 r--s 00037000 fd:00 22818                      /usr/share/elasticsearch/lib/lucene-queries-5.4.1.jar
7f4242cf1000-7f4242cf2000 r--s 0000c000 fd:00 22483                      /usr/share/elasticsearch/lib/commons-cli-1.3.1.jar
7f4242cf2000-7f4242cf4000 r--s 00007000 fd:00 22816                      /usr/share/elasticsearch/lib/lucene-memory-5.4.1.jar
7f4242cf4000-7f4242cf5000 r--s 0000b000 fd:00 22511                      /usr/share/elasticsearch/lib/jackson-dataformat-cbor-2.6.2.jar
7f4242cf5000-7f4242cf9000 r--s 0001a000 fd:00 22815                      /usr/share/elasticsearch/lib/lucene-join-5.4.1.jar
7f4242cf9000-7f4242cfc000 r--s 00022000 fd:00 22827                      /usr/share/elasticsearch/lib/spatial4j-0.5.jar
7f4242cfc000-7f4242d13000 r--s 00100000 fd:00 22503                      /usr/share/elasticsearch/lib/hppc-0.7.1.jar
7f4242d13000-7f4242d17000 r--s 0003c000 fd:00 22506                      /usr/share/elasticsearch/lib/jackson-core-2.6.2.jar
7f4242d17000-7f4242d1c000 r--s 00038000 fd:00 22823                      /usr/share/elasticsearch/lib/lucene-suggest-5.4.1.jar
7f4242d1c000-7f4242d20000 r--s 00018000 fd:00 22486                      /usr/share/elasticsearch/lib/compiler-0.8.13.jar
7f4242d20000-7f4242d26000 r--s 0003c000 fd:00 22826                      /usr/share/elasticsearch/lib/snakeyaml-1.15.jar
7f4242d26000-7f4242d2a000 r--s 000dc000 fd:00 22804                      /usr/share/elasticsearch/lib/jna-4.1.0.jar
7f4242d2a000-7f4242d33000 r--s 0006f000 fd:00 22809                      /usr/share/elasticsearch/lib/log4j-1.2.17.jar
7f4242d33000-7f4242d43000 r--s 00088000 fd:00 22806                      /usr/share/elasticsearch/lib/joda-time-2.8.2.jar
7f4242d43000-7f4242d47000 r--s 00027000 fd:00 22817                      /usr/share/elasticsearch/lib/lucene-misc-5.4.1.jar
7f4242d47000-7f4242d49000 r--s 00008000 fd:00 22805                      /usr/share/elasticsearch/lib/joda-convert-1.2.jar
7f4242d49000-7f4242d5a000 r--s 000b2000 fd:00 22808                      /usr/share/elasticsearch/lib/jts-1.13.jar
7f4242d5a000-7f4242d73000 r--s 0012c000 fd:00 22824                      /usr/share/elasticsearch/lib/netty-3.10.5.Final.jar
7f4242d73000-7f4242d7c000 r--s 00046000 fd:00 22513                      /usr/share/elasticsearch/lib/jackson-dataformat-yaml-2.6.2.jar
7f4242d7c000-7f4242d7e000 r--s 00011000 fd:00 22512                      /usr/share/elasticsearch/lib/jackson-dataformat-smile-2.6.2.jar
7f4242d7e000-7f4242d81000 r--s 00018000 fd:00 22813                      /usr/share/elasticsearch/lib/lucene-grouping-5.4.1.jar
7f4242d81000-7f4242da9000 r--s 00218000 fd:00 22812                      /usr/share/elasticsearch/lib/lucene-core-5.4.1.jar
7f4242da9000-7f4242dbb000 r--s 00170000 fd:00 22810                      /usr/share/elasticsearch/lib/lucene-analyzers-common-5.4.1.jar
7f4242dbb000-7f4242e6b000 r--s 0083d000 fd:00 22500                      /usr/share/elasticsearch/lib/elasticsearch-2.2.0.jar
7f4242e6b000-7f4242e6c000 ---p 00000000 00:00 0
7f4242e6c000-7f4242f6c000 rw-p 00000000 00:00 0
7f4242f6c000-7f4242f6f000 ---p 00000000 00:00 0
7f4242f6f000-7f424306d000 rw-p 00000000 00:00 0
7f424306d000-7f4243070000 ---p 00000000 00:00 0
7f4243070000-7f424316e000 rw-p 00000000 00:00 0
7f424316e000-7f4243171000 ---p 00000000 00:00 0
7f4243171000-7f424326f000 rw-p 00000000 00:00 0
7f424326f000-7f4243272000 ---p 00000000 00:00 0
7f4243272000-7f4243370000 rw-p 00000000 00:00 0
7f4243370000-7f4243373000 ---p 00000000 00:00 0
7f4243373000-7f4243471000 rw-p 00000000 00:00 0
7f4243471000-7f4243474000 ---p 00000000 00:00 0
7f4243474000-7f4243572000 rw-p 00000000 00:00 0
7f4243572000-7f4243575000 ---p 00000000 00:00 0
7f4243575000-7f4243673000 rw-p 00000000 00:00 0
7f4243673000-7f4243674000 ---p 00000000 00:00 0
7f4243674000-7f42437bf000 rw-p 00000000 00:00 0
7f42437bf000-7f424397e000 r--s 039eb000 fd:00 22381                      /usr/java/jdk1.7.0_75/jre/lib/rt.jar
7f424397e000-7f4243afb000 rw-p 00000000 00:00 0
7f4243afb000-7f4243afc000 ---p 00000000 00:00 0
7f4243afc000-7f4243dfe000 rw-p 00000000 00:00 0
7f4243dfe000-7f4243dff000 ---p 00000000 00:00 0
7f4243dff000-7f4244000000 rw-p 00000000 00:00 0
7f4244000000-7f4244021000 rw-p 00000000 00:00 0
7f4244021000-7f4248000000 ---p 00000000 00:00 0
7f4248005000-7f4248009000 r--s 00020000 fd:00 22814                      /usr/share/elasticsearch/lib/lucene-highlighter-5.4.1.jar
7f4248009000-7f424800e000 r--s 0003e000 fd:00 22820                      /usr/share/elasticsearch/lib/lucene-sandbox-5.4.1.jar
7f424800e000-7f4248010000 r--s 0000e000 fd:00 22807                      /usr/share/elasticsearch/lib/jsr166e-1.1.0.jar
7f4248010000-7f4248012000 r--s 0000b000 fd:00 22828                      /usr/share/elasticsearch/lib/t-digest-3.0.jar
7f4248012000-7f4248014000 r--s 00012000 fd:00 22493                      /usr/share/elasticsearch/lib/compress-lzf-1.0.2.jar
7f4248014000-7f424801c000 r--s 00066000 fd:00 22482                      /usr/share/elasticsearch/lib/apache-log4j-extras-1.2.17.jar
7f424801c000-7f424b5cb000 rw-p 00000000 00:00 0
7f424b5cb000-7f424b6cf000 rw-p 00000000 00:00 0
7f424b6cf000-7f424bafe000 rw-p 00000000 00:00 0
7f424bafe000-7f424bb79000 rw-p 00000000 00:00 0
7f424bb79000-7f424bbcf000 rw-p 00000000 00:00 0
7f424bbcf000-7f424bcd3000 rw-p 00000000 00:00 0
7f424bcd3000-7f424bcde000 rw-p 00000000 00:00 0
7f424bcde000-7f424bcfc000 rw-p 00000000 00:00 0
7f424bcfc000-7f424bcfd000 rw-p 00000000 00:00 0
7f424bcfd000-7f424bcfe000 ---p 00000000 00:00 0
7f424bcfe000-7f424bdfe000 rw-p 00000000 00:00 0
7f424bdfe000-7f424bdff000 ---p 00000000 00:00 0
7f424bdff000-7f424beff000 rw-p 00000000 00:00 0
7f424beff000-7f424bf00000 ---p 00000000 00:00 0
7f424bf00000-7f424c000000 rw-p 00000000 00:00 0
7f424c000000-7f424c45c000 rw-p 00000000 00:00 0
7f424c45c000-7f4250000000 ---p 00000000 00:00 0
7f4250002000-7f425003e000 rw-p 00000000 00:00 0
7f425003e000-7f425005d000 rw-p 00000000 00:00 0
7f425005d000-7f42502cd000 rwxp 00000000 00:00 0
7f42502cd000-7f425305d000 rw-p 00000000 00:00 0
7f425305d000-7f4253077000 r-xp 00000000 fd:00 19938                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libzip.so
7f4253077000-7f4253277000 ---p 0001a000 fd:00 19938                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libzip.so
7f4253277000-7f4253278000 rw-p 0001a000 fd:00 19938                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libzip.so
7f4253278000-7f4253284000 r-xp 00000000 fd:00 14665                      /lib64/libnss_files-2.12.so
7f4253284000-7f4253484000 ---p 0000c000 fd:00 14665                      /lib64/libnss_files-2.12.so
7f4253484000-7f4253485000 r--p 0000c000 fd:00 14665                      /lib64/libnss_files-2.12.so
7f4253485000-7f4253486000 rw-p 0000d000 fd:00 14665                      /lib64/libnss_files-2.12.so
7f4253486000-7f42534af000 r-xp 00000000 fd:00 19908                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libjava.so
7f42534af000-7f42536af000 ---p 00029000 fd:00 19908                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libjava.so
7f42536af000-7f42536b1000 rw-p 00029000 fd:00 19908                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libjava.so
7f42536b1000-7f42536be000 r-xp 00000000 fd:00 19937                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libverify.so
7f42536be000-7f42538bd000 ---p 0000d000 fd:00 19937                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libverify.so
7f42538bd000-7f42538bf000 rw-p 0000c000 fd:00 19937                      /usr/java/jdk1.7.0_75/jre/lib/amd64/libverify.so
7f42538bf000-7f42538c6000 r-xp 00000000 fd:00 22663                      /lib64/librt-2.12.so
7f42538c6000-7f4253ac5000 ---p 00007000 fd:00 22663                      /lib64/librt-2.12.so
7f4253ac5000-7f4253ac6000 r--p 00006000 fd:00 22663                      /lib64/librt-2.12.so
7f4253ac6000-7f4253ac7000 rw-p 00007000 fd:00 22663                      /lib64/librt-2.12.so
7f4253ac7000-7f4253b4a000 r-xp 00000000 fd:00 14232                      /lib64/libm-2.12.so
7f4253b4a000-7f4253d49000 ---p 00083000 fd:00 14232                      /lib64/libm-2.12.so
7f4253d49000-7f4253d4a000 r--p 00082000 fd:00 14232                      /lib64/libm-2.12.so
7f4253d4a000-7f4253d4b000 rw-p 00083000 fd:00 14232                      /lib64/libm-2.12.so
7f4253d4b000-7f42548be000 r-xp 00000000 fd:00 19942                      /usr/java/jdk1.7.0_75/jre/lib/amd64/server/libjvm.so
7f42548be000-7f4254abe000 ---p 00b73000 fd:00 19942                      /usr/java/jdk1.7.0_75/jre/lib/amd64/server/libjvm.so
7f4254abe000-7f4254b82000 rw-p 00b73000 fd:00 19942                      /usr/java/jdk1.7.0_75/jre/lib/amd64/server/libjvm.so
7f4254b82000-7f4254bc3000 rw-p 00000000 00:00 0
7f4254bc3000-7f4254d4d000 r-xp 00000000 fd:00 3286                       /lib64/libc-2.12.so
7f4254d4d000-7f4254f4d000 ---p 0018a000 fd:00 3286                       /lib64/libc-2.12.so
7f4254f4d000-7f4254f51000 r--p 0018a000 fd:00 3286                       /lib64/libc-2.12.so
7f4254f51000-7f4254f52000 rw-p 0018e000 fd:00 3286                       /lib64/libc-2.12.so
7f4254f52000-7f4254f57000 rw-p 00000000 00:00 0
7f4254f57000-7f4254f59000 r-xp 00000000 fd:00 13342                      /lib64/libdl-2.12.so
7f4254f59000-7f4255159000 ---p 00002000 fd:00 13342                      /lib64/libdl-2.12.so
7f4255159000-7f425515a000 r--p 00002000 fd:00 13342                      /lib64/libdl-2.12.so
7f425515a000-7f425515b000 rw-p 00003000 fd:00 13342                      /lib64/libdl-2.12.so
7f425515b000-7f4255171000 r-xp 00000000 fd:00 21163                      /usr/java/jdk1.7.0_75/lib/amd64/jli/libjli.so
7f4255171000-7f4255371000 ---p 00016000 fd:00 21163                      /usr/java/jdk1.7.0_75/lib/amd64/jli/libjli.so
7f4255371000-7f4255372000 rw-p 00016000 fd:00 21163                      /usr/java/jdk1.7.0_75/lib/amd64/jli/libjli.so
7f4255372000-7f4255389000 r-xp 00000000 fd:00 3310                       /lib64/libpthread-2.12.so
7f4255389000-7f4255589000 ---p 00017000 fd:00 3310                       /lib64/libpthread-2.12.so
7f4255589000-7f425558a000 r--p 00017000 fd:00 3310                       /lib64/libpthread-2.12.so
7f425558a000-7f425558b000 rw-p 00018000 fd:00 3310                       /lib64/libpthread-2.12.so
7f425558b000-7f425558f000 rw-p 00000000 00:00 0
7f425558f000-7f42555af000 r-xp 00000000 fd:00 3277                       /lib64/ld-2.12.so
7f42555b0000-7f42555e2000 rw-p 00000000 00:00 0
7f42555e2000-7f4255698000 rw-p 00000000 00:00 0
7f4255698000-7f42556a0000 rw-s 00000000 fd:01 37                         /tmp/hsperfdata_elastic/28216
7f42556a0000-7f42556a3000 ---p 00000000 00:00 0
7f42556a3000-7f42557a5000 rw-p 00000000 00:00 0
7f42557a5000-7f42557a9000 r--s 0008b000 fd:00 20725                      /usr/java/jdk1.7.0_75/jre/lib/jsse.jar
7f42557a9000-7f42557ab000 r--s 00019000 fd:00 22406                      /usr/share/elasticsearch/lib/HdrHistogram-2.1.6.jar
7f42557ab000-7f42557ac000 rw-p 00000000 00:00 0
7f42557ac000-7f42557ad000 r--p 00000000 00:00 0
7f42557ad000-7f42557ae000 rw-p 00000000 00:00 0
7f42557ae000-7f42557af000 r--p 0001f000 fd:00 3277                       /lib64/ld-2.12.so
7f42557af000-7f42557b0000 rw-p 00020000 fd:00 3277                       /lib64/ld-2.12.so
7f42557b0000-7f42557b1000 rw-p 00000000 00:00 0
7fff3d014000-7fff3d029000 rw-p 00000000 00:00 0                          [stack]
7fff3d031000-7fff3d032000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

VM Arguments:
jvm_args: -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Djna.tmpdir=/usr/share/elasticsearch/tmp -Djava.io.tmpdir=/usr/share/elasticsearch/tmp -Des.path.home=/usr/share/elasticsearch
java_command: org.elasticsearch.bootstrap.Elasticsearch start -p /var/run/elasticsearch/elasticsearch.pid -d -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.conf=/etc/elasticsearch
Launcher Type: SUN_STANDARD

Environment Variables:
PATH=/sbin:/usr/sbin:/bin:/usr/bin
SHELL=/bin/bash

Signal Handlers:
SIGSEGV: [libjvm.so+0x9a21f0], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGBUS: [libjvm.so+0x9a21f0], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGFPE: [libjvm.so+0x81ba40], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGPIPE: [libjvm.so+0x81ba40], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGXFSZ: [libjvm.so+0x81ba40], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGILL: [libjvm.so+0x81ba40], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGUSR1: SIG_DFL, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGUSR2: [libjvm.so+0x81d240], sa_mask[0]=0x00000000, sa_flags=0x10000004
SIGHUP: [libjvm.so+0x81e360], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGINT: SIG_IGN, sa_mask[0]=0x00000000, sa_flags=0x00000000
SIGTERM: [libjvm.so+0x81e360], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004
SIGQUIT: [libjvm.so+0x81e360], sa_mask[0]=0x7ffbfeff, sa_flags=0x10000004


---------------  S Y S T E M  ---------------

OS:CentOS release 6.7 (Final)

uname:Linux 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64
libc:glibc 2.12 NPTL 2.12
rlimit: STACK 10240k, CORE 0k, NPROC 1024, NOFILE 65535, AS infinity
load average:0.12 0.10 0.08

/proc/meminfo:
MemTotal:        3924284 kB
MemFree:         2475800 kB
Buffers:           95816 kB
Cached:          1058380 kB
SwapCached:         1656 kB
Active:           724236 kB
Inactive:         496232 kB
Active(anon):      52848 kB
Inactive(anon):    13496 kB
Active(file):     671388 kB
Inactive(file):   482736 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1048572 kB
SwapFree:        1015456 kB
Dirty:               272 kB
Writeback:             0 kB
AnonPages:         40536 kB
Mapped:            21068 kB
Shmem:                16 kB
Slab:             177536 kB
SReclaimable:     112616 kB
SUnreclaim:        64920 kB
KernelStack:        2880 kB
PageTables:         3948 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3010712 kB
Committed_AS:     502800 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      150516 kB
VmallocChunk:   34359576444 kB
HardwareCorrupted:     0 kB
AnonHugePages:      6144 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:        8192 kB
DirectMap2M:     2088960 kB
DirectMap1G:     2097152 kB


CPU:total 4 (1 cores per cpu, 1 threads per core) family 6 model 63 stepping 2, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, aes, erms, tsc, tscinvbit

/proc/cpuinfo:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
stepping	: 2
microcode	: 45
cpu MHz		: 3491.914
cache size	: 15360 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm ida arat epb pln pts dts fsgsbase smep
bogomips	: 6983.82
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
stepping	: 2
microcode	: 45
cpu MHz		: 3491.914
cache size	: 15360 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm ida arat epb pln pts dts fsgsbase smep
bogomips	: 6983.82
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
stepping	: 2
microcode	: 45
cpu MHz		: 3491.914
cache size	: 15360 KB
physical id	: 4
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm ida arat epb pln pts dts fsgsbase smep
bogomips	: 6983.82
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
stepping	: 2
microcode	: 45
cpu MHz		: 3491.914
cache size	: 15360 KB
physical id	: 6
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm ida arat epb pln pts dts fsgsbase smep
bogomips	: 6983.82
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:



Memory: 4k page, physical 3924284k(2475800k free), swap 1048572k(1015456k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (24.75-b04) for linux-amd64 JRE (1.7.0_75-b13), built on Dec 18 2014 16:45:18 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)

time: Wed May 11 10:18:58 2016
elapsed time: 0 seconds
```

### LINKED ISSUE #73309: Elasticsearch 7.X fails to start with jna tmp dir configured (CentOS8 - Hardened)
I am posting this as an open bug for the ES team to review, it is similar to other issues but this was the ONLY actual fix I found for my particular air gapped deployment. 

Overview:

Elasticsearch 7.12,
Oracle JDK 1.8.0,
Noexec on /tmp,
Selinux in enforcing mode,
Explicitly defined path for jna.tmpdir without noexec,
CentOS 8
A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f9800b8d2ca, pid=21823, tid=0x00007f98f541f700

JRE version: Java(TM) SE Runtime Environment (8.0_112-b15) (build 1.8.0_112-b15)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.112-b15 mixed mode linux-amd64 compressed oops)
Problematic frame:
C [jna1247360738620499207.tmp+0x122ca] ffi_prep_closure_loc+0x1a

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

The reason of failure was that the system user with which ES was running did not have an existing home directory.

**Once I created the homedir, it started as expected.**
In the home directory, a directory ".oracle_jre_usage" is created which has a fd53b05c83802a42.timestamp file.

More about this file - https://community.oracle.com/thread/3783686.

This is a solution to a persistent problem I encountered but also through research all seemed to point to tmpdir issues, the logs seemed to suggest as well. But on deep examination and research it was discovered that on install there is no home directory provided to the elasticsearch user and thus causes this exact error with the JNA libraries.

### LINKED ISSUE #77014: LIBFFI_TMPDIR should point somewhere that permits executables
JNA requires a temporary directory which is not mounted `noexec`, but JNA also uses `libffi` which itself requires a temporary directory that isn't mounted `noexec`. If none of the usual suspects work, [`libffi` will fall back to `$HOME`](https://github.com/libffi/libffi/blob/ee1263f7d43bd29b15fc72c4d9520a824e8004df/src/closures.c#L702-L707) which will often work, but in general might also not permit executables (or even exist).

We override the temporary directory that JNA uses by setting the `java.io.tmpdir` system property to `ES_TMPDIR`. I believe we should do the same thing for `libffi`, by setting the `LIBFFI_TMPDIR` environment variable. We should also document that this can be overridden much as we do for the `jna.tmpdir` system property (which trumps `java.io.tmpdir` if set).

Fixing this would, I believe, also fix #73309.

### LINKED ISSUE #77053: Service failing to start RHEL 7
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.14.0, Build: default/rpm/dd5a0a2acaa2045ff9624f3729fc8a6f40835aa1/2021-07-29T20:49:32.864135063Z, JVM: 16.0.1

**Plugins installed**: []
None

**JVM version** (`java -version`):
_Bundled version is:_
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

_OS Version is:_
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

-- note I have not changed settings, so the bundled version should be the one in use

**OS version** (`uname -a` if on a Unix-like system):
Linux 1025093 3.10.0-957.21.2.el7.x86_64 #1 SMP Tue May 28 09:26:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Red Hat Enterprise Linux Server 7.9 (Maipo)

**Description of the problem including expected versus actual behavior**:
After installing elasticsearch via the "Installing from the RPM repository" instructions on https://www.elastic.co/guide/en/elasticsearch/reference/7.14/rpm.html#rpm-repo we are able to start elasticsearch directly /bin/elasticsearch (with warnings). However when attempting to start the service we receive an error.

```
Internal exceptions (20 events):
Event: 4.735 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd312da0}: 'void java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000017bd312da0)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.778 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd430120}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object)'> (0x00000017bd430120)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.905 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd886a60}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, int, java.lang.Object)'> (0x00000017bd886a60)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.910 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd8bfa80}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.lang.Object, java.lang.Object, int, java.lang.Object, java.lang.Object)'> (0x00000017bd8bfa80)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.911 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd8c77a8}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(java.lang.Object, java.lang.Object, int, java.lang.Object)'> (0x00000017bd8c77a8)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.912 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd8cbca0}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, java.lang.Object, int, java.lang.Object)'> (0x00000017bd8cbca0)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.917 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd8f9388}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000017bd8f9388)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.927 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd93d878}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(java.lang.Object, int, java.lang.Object, java.lang.Object)'> (0x00000017bd93d878)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 4.927 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bd941a08}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, int, java.lang.Object, java.lang.Object)'> (0x00000017bd941a08)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 5.389 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bde97770}: 'int java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000017bde97770)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 5.470 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bc149e30}: 'java.lang.Object java.lang.invoke.Invokers$Holder.invokeExact_MT(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000017bc149e30)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 5.955 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bc94c528}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000017bc94c528)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.071 Thread 0x00007f319c0254a0 Implicit null exception at 0x00007f318c096c54 to 0x00007f318c097224
Event: 6.200 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb603f80}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(java.lang.Object, java.lang.Object, java.lang.Object)'> (0x00000017bb603f80)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.224 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb69b510}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeStaticInit(java.lang.Object, java.lang.Object, long, java.lang.Object)'> (0x00000017bb69b510)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.225 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb6a1b78}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(java.lang.Object, java.lang.Object, long)'> (0x00000017bb6a1b78)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.225 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb6a58e8}: 'java.lang.Object java.lang.invoke.Invokers$Holder.linkToTargetMethod(java.lang.Object, long, java.lang.Object)'> (0x00000017bb6a58e8)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.253 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb7970a0}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(java.lang.Object, java.lang.Object, java.lang.Object, int)'> (0x00000017bb7970a0)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.254 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb79b598}: 'java.lang.Object java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, int)'> (0x00000017bb79b598)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
Event: 6.254 Thread 0x00007f319c0254a0 Exception <a 'java/lang/NoSuchMethodError'{0x00000017bb79f358}: 'java.lang.Object java.lang.invoke.Invokers$Holder.linkToTargetMethod(java.lang.Object, java.lang.Object, int, java.lang.Object)'> (0x00000017bb79f358)
thrown [./src/hotspot/share/interpreter/linkResolver.cpp, line 790]
```

Warnings received when starting elastic search directly:

```
java.lang.UnsatisfiedLinkError: /tmp/elasticsearch-2615699647026920288/jna10243734774257956315.tmp: /tmp/elasticsearch-2615699647026920288/jna10243734774257956315.tmp: failed to map segment from shared object: Operation not permitted
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:746) ~[?:?]
        at java.lang.System.load(System.java:1857) ~[?:?]
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1019) ~[jna-5.7.0-1.jar:5.7.0 (b0)]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989) ~[jna-5.7.0-1.jar:5.7.0 (b0)]
        at com.sun.jna.Native.<clinit>(Native.java:195) ~[jna-5.7.0-1.jar:5.7.0 (b0)]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:34) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:102) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:399) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) [elasticsearch-cli-7.14.0.jar:7.14.0]
        at org.elasticsearch.cli.Command.main(Command.java:79) [elasticsearch-cli-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.14.0.jar:7.14.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) [elasticsearch-7.14.0.jar:7.14.0]
```

See the link for a discussion regarding this:
https://discuss.elastic.co/t/service-will-not-start-rhe7/282591/5

The current thoughts are that the error is caused as elasticsearch cannot assume the SystemdPlugin is running.
https://github.com/elastic/elasticsearch/blob/master/modules/systemd/src/main/java/org/elasticsearch/systemd/Libsystemd.java#L21-L26

**Steps to reproduce**:
 1. service elasticsearch start

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today if `libffi` cannot allocate pages of memory which are both
writeable and executable then it will attempt to write code to a
temporary file. Elasticsearch configures itself a suitable temporary
directory for use by JNA but by default `libffi` won't find this
directory and will try various other places. In certain configurations,
none of the other places that `libffi` tries are suitable. With older
versions of JNA this would result in a `SIGSEGV`; since #80617 the JVM
will exit with an exception.

With this commit we use the `LIBFFI_TMPDIR` environment variable to
configure `libffi` to use the same directory as JNA for its temporary
files if they are needed.

Closes #18272
Closes #73309
Closes #74545
Closes #77014
Closes #77053
Relates #77285

Co-authored-by: Rory Hunter <roryhunter2@gmail.com>

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/env/Environment.java [hunk 1]
```diff
@@ -304,12 +305,44 @@ public Path tmpFile() {
...
+    private static Path getLibffiTemporaryDirectory() {
+        final String workingDirectory = System.getProperty("user.dir");
+        if (workingDirectory == null) {
+            return null;
+        }
+        final String environmentVariable = System.getenv(LIBFFI_TMPDIR_ENVIRONMENT_VARIABLE);
+        if (environmentVariable == null) {
+            return null;
         }
+        return PathUtils.get(workingDirectory).resolve(environmentVariable);
```
Comment (pugnascotia) [inline server/src/main/java/org/elasticsearch/env/Environment.java:345]: Is this line so that the env var can be either relative or absolute?

**Review by pugnascotia — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/env/Environment.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/env/Environment.java:345]: Really so that we report the absolute path that we expected to exist (and that `libffi` would use) even if the env var is a relative path. Elasticsearch's actual working directory is different from the working directory in which the user executes `$ES_DIR/bin/elasticsearch` so the behaviour can be surprising otherwise.
