### PR TITLE
[TESTS] Set SO_LINGER and SO_REUSEADDR on the mock socket

### LINKED ISSUE #32190: [CI] SessionFactoryLoadBalancingTests testRoundRobinWithFailures fails
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1190/console

Could not reproduce with:
```
REPRODUCE WITH: gradlew :x-pack:plugin:security:test \
  -Dtests.seed=16B5154ACCB4889F \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests \
  -Dtests.method="testRoundRobinWithFailures" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-QA \
  -Dtests.timezone=US/Central

REPRODUCE WITH: gradlew :x-pack:plugin:security:test \
  -Dtests.seed=16B5154ACCB4889F \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC
```

Looks like there are connection issues:
```
10:27:12   2> WARNING: Suite execution timed out: org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests
10:27:12   1> java.net.BindException: Address already in use: connect
10:27:12   2> ==== jstack at approximately timeout time ====
10:27:12   1> 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_172]
10:27:12   2> "elasticsearch[SessionFactoryLoadBalancingTests thread pool][[timer]]" ID=2333 TIMED_WAITING
10:27:12   2> 	at java.lang.Thread.sleep(Native Method)
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_172]
10:27:12   2> 	at org.elasticsearch.threadpool.ThreadPool$CachedTimeThread.run(ThreadPool.java:543)
10:27:12   2> "LDAP Listener Thread (listening on port 63056)" ID=2331 RUNNABLE (in native code)
10:27:12   2> 	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
10:27:12   2> 	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.access$101(MockSocket.java:32) ~[mocksocket-1.2.jar:?]
10:27:12   2> 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
10:27:12   2> 	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.lambda$connect$0(MockSocket.java:66) ~[mocksocket-1.2.jar:?]
10:27:12   1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:65) ~[mocksocket-1.2.jar:?]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:59) ~[mocksocket-1.2.jar:?]
10:27:12   2> 	- locked java.net.SocksSocketImpl@1d4bb36e
10:27:12   1> 	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.Socket.<init>(Socket.java:328) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.<init>(MockSocket.java:54) ~[mocksocket-1.2.jar:?]
```

This leads to test timeouts later.

### PR DESCRIPTION
**Pull request by bizybot**
In `SessionFactoryLoadBalancingTests#testRoundRobinWithFailures()`
we kill ldap servers randomly and immediately bind to that port
connecting to mock server socket. This is done to avoid someone else
listening to this port. As the creation of mock socket and binding to the
port is immediate, sometimes the earlier socket would be in `TIME_WAIT` state
thereby having problems with either bind or connect.
This commit sets the SO_REUSEADDR explicitly to `true` and also sets
the linger on time to `0`(as we are not writing any data) so as to
allow re-use of the port and close immediately.

Note: I could not find other places where this might be problematic
but looking at test runs and netstat output I do see lot of sockets
in TIME_WAIT. If we find that this needs to be addressed we can
wrap ServerSocketFactory to set these options and use that with in
memory ldap server configuration during tests.

Closes #32190

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java [hunk 1]
```diff
@@ -149,6 +152,17 @@ public void testRoundRobinWithFailures() throws Exception {
         }
     }
 
+    @SuppressForbidden(reason = "Allow opening socket for test")
+    private MockSocket openMockServerSocket(InetAddress remoteAddress, int remotePort, InetAddress localAddress, int localPort)
+            throws IOException {
+        final MockSocket socket = new MockSocket();
+        socket.setReuseAddress(true); // allow binding even if the previous socket is in timed state.
```
Comment (jaymode) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: s/timed/timed wait ?

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java [hunk 2]
```diff
@@ -149,6 +152,17 @@ public void testRoundRobinWithFailures() throws Exception {
         }
     }
 
+    @SuppressForbidden(reason = "Allow opening socket for test")
+    private MockSocket openMockServerSocket(InetAddress remoteAddress, int remotePort, InetAddress localAddress, int localPort)
```
Comment (jaymode) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: this isn't a server socket, so I think the method should be `openMockSocket`

**Review by jaymode — APPROVED** [review]
I left a couple of minor comments, otherwise LGTM. Please make sure to get an approval from either @tbrooks8 or @original-brownbear before merging (thanks @jasontedor for requesting their review)

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java (hunk 1 above)
Comment (bizybot) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: Changed this, Thank you.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java (hunk 2 above)
Comment (bizybot) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: Yes, changed this. Thank you.

**Review by Tim-Brooks — APPROVED** [review]
LGTM
