### PR TITLE
Upgrade MinIO (& work around bug)

### LINKED ISSUE #131742: [CI] MinioRepositoryAnalysisRestIT testRepositoryAnalysis failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9547 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/rmlxbq73cr2d6)
- [elasticsearch-periodic-platform-support #9498 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/csqrn2nezclpa)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:snapshot-repo-test-kit:qa:minio:javaRestTest" --tests "org.elasticsearch.repositories.blobstore.testkit.analyze.MinioRepositoryAnalysisRestIT.testRepositoryAnalysis" -Dtests.seed=2D5E933E73DCF75C -Dtests.locale=ki-Latn-KE -Dtests.timezone=America/Belem -Druntime.java=24
```

**Applicable branches:**
9.0

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.blobstore.testkit.analyze.MinioRepositoryAnalysisRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRepositoryAnalysis'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.net.SocketTimeoutException: 60,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
```

**Issue Reasons:**
- [9.0] 2 failures in test testRepositoryAnalysis (1.2% fail rate in 165 executions)
- [9.0] 2 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Relates https://github.com/minio/minio/issues/21456
Closes https://github.com/elastic/elasticsearch/issues/131742

### CODE REVIEW

File: test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java [hunk 1]
```diff
@@ -15,9 +15,10 @@
 
 public final class MinioTestContainer extends DockerEnvironmentAwareTestContainer {
 
-    // NB releases earlier than 2025-05-24 are buggy, see https://github.com/minio/minio/issues/21189, and #127166 for a workaround
-    // However the 2025-05-24 release is also buggy, see https://github.com/minio/minio/issues/21377, and this has no workaround
-    public static final String DOCKER_BASE_IMAGE = "minio/minio:RELEASE.2025-06-13T11-33-47Z";
+    // NB releases earlier than 2025-05-24 are buggy, see https://github.com/minio/minio/issues/21189, and #127166 for a workaround.
+    // However the 2025-05-24 release is also buggy, see https://github.com/minio/minio/issues/21377, and this has no workaround.
```
Comment (DiannaHohensee) [inline test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java:19]: https://github.com/minio/minio/issues/21377 appears to be resolved. Is it mentioned here because it wasn't released in the 2025-07-23 build?

File: test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java [hunk 2]
```diff
@@ -15,9 +15,10 @@
 
 public final class MinioTestContainer extends DockerEnvironmentAwareTestContainer {
 
-    // NB releases earlier than 2025-05-24 are buggy, see https://github.com/minio/minio/issues/21189, and #127166 for a workaround
-    // However the 2025-05-24 release is also buggy, see https://github.com/minio/minio/issues/21377, and this has no workaround
-    public static final String DOCKER_BASE_IMAGE = "minio/minio:RELEASE.2025-06-13T11-33-47Z";
+    // NB releases earlier than 2025-05-24 are buggy, see https://github.com/minio/minio/issues/21189, and #127166 for a workaround.
```
Comment (DiannaHohensee) [inline test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java:18]: Is https://github.com/minio/minio/issues/21189 mentioned because the bug wasn't fixed properly, leading to you filing [21456](https://github.com/minio/minio/issues/21456)?

I'm wondering if it's worth mentioning resolved bugs. But if it still relates, then that seems helpful, maybe mentioned in that way.

File: x-pack/plugin/snapshot-repo-test-kit/qa/minio/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/MinioRepositoryAnalysisRestIT.java [hunk 3]
```diff
@@ -33,6 +33,11 @@ public class MinioRepositoryAnalysisRestIT extends AbstractRepositoryAnalysisRes
         .keystore("s3.client.repository_test_kit.secret_key", "s3_test_secret_key")
         .setting("s3.client.repository_test_kit.endpoint", minioFixture::getAddress)
         .setting("xpack.security.enabled", "false")
+        // Skip listing of pre-existing uploads during a CAS because MinIO sometimes leaks them; also reduce the delay before proceeding
+        // TODO do not set these if running a MinIO version in which https://github.com/minio/minio/issues/21189
+        // and https://github.com/minio/minio/issues/21456 are both fixed
```
Comment (DiannaHohensee) [inline x-pack/plugin/snapshot-repo-test-kit/qa/minio/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/MinioRepositoryAnalysisRestIT.java:38]: Does https://github.com/minio/minio/issues/21189 need to be mentioned, since it is closed already?

Also, should the testing change made in https://github.com/elastic/elasticsearch/pull/127166/files be returned, since the fix did not take? IIUC that https://github.com/minio/minio/issues/21189 didn't actually fix the bug, leading to you filing https://github.com/minio/minio/issues/21456?

**Review by DiannaHohensee — APPROVED** [review]
lgtm

File: test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java (hunk 1 above)
Comment (DaveCTurner) [reply test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java:19]: No, that should be fixed in 2025-07-23. The specific MinIO version in use has come up in some conversations with customers so I'm keeping track of the known issues in older versions here. We may end up having to run these tests against multiple MinIO versions in which case we'll need this info - clearly we can extract it from history but it's going to be easier if we have a summary here.

File: test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java (hunk 2 above)
Comment (DaveCTurner) [reply test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java:18]: I'm not sure, I suspect https://github.com/minio/minio/issues/21456 might be something different albeit with similar symptoms.

File: x-pack/plugin/snapshot-repo-test-kit/qa/minio/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/MinioRepositoryAnalysisRestIT.java (hunk 3 above)
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/qa/minio/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/MinioRepositoryAnalysisRestIT.java:38]: This _is_ the testing change from #127166, it's just that we're applying it to the correct test suite here 🤦

File: test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java (hunk 1 above)
Comment (DiannaHohensee) [reply test/fixtures/minio-fixture/src/main/java/org/elasticsearch/test/fixtures/minio/MinioTestContainer.java:19]: Okay, sounds good then 👍

File: x-pack/plugin/snapshot-repo-test-kit/qa/minio/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/MinioRepositoryAnalysisRestIT.java (hunk 3 above)
Comment (DiannaHohensee) [reply x-pack/plugin/snapshot-repo-test-kit/qa/minio/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/MinioRepositoryAnalysisRestIT.java:38]: Ah 😄  Then we're good to go 🙃
