### PR TITLE
TEST: makes sure to corrupt referenced tlog files

### LINKED ISSUE #27538: [CI] TruncateTranslogIT#testCorruptTranslogTruncation fails
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/365/console.

```
 TruncateTranslogIT.testCorruptTranslogTruncation <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: all shards should be failed due to a corrupted translog
   > 	at __randomizedtesting.SeedInfo.seed([BE82146795DBD816:2A70E3779E1B3BE]:0)
   > 	at org.elasticsearch.index.translog.TruncateTranslogIT.testCorruptTranslogTruncation(TruncateTranslogIT.java:171)
   > 	at java.lang.Thread.run(Thread.java:748)
  1> [2017-11-27T13:32:12,883][INFO ][o.e.n.Node               ] [node_s0] stopping ...
  1> [2017-11-27T13:32:12,884][INFO ][o.e.n.Node               ] [node_s0] stopped
  1> [2017-11-27T13:32:12,884][INFO ][o.e.n.Node               ] [node_s0] closing ...
  1> [2017-11-27T13:32:12,887][INFO ][o.e.n.Node               ] [node_s0] closed
```

Unable to reproduce locally:

```
 gradle :core:integTest \
  -Dtests.seed=BE82146795DBD816 \
  -Dtests.class=org.elasticsearch.index.translog.TruncateTranslogIT \
  -Dtests.method="testCorruptTranslogTruncation" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-ME \
  -Dtests.timezone=Africa/Khartoum
```

Log: [consoleText.txt](https://github.com/elastic/elasticsearch/files/1505971/consoleText.txt)

### PR DESCRIPTION
**Pull request by dnhatn**
Method `TruncateTranslogIT#corruptTranslogFiles` corrupts any random
existing `*.tlog` files in a translog directory. However, this may not
actually corrupt translog at all if it corrupts only tlog files which
are not referenced by the Checkpoint (eg. their translog generations are
smaller the Checkpoint).

This commit makes sure that we corrupt tlog files which are referenced
by the Checkpoint.

Closes #27538

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/index/translog/TestTranslog.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+import static org.hamcrest.Matchers.empty;
+import static org.hamcrest.Matchers.not;
+
+/**
+ * Helpers for testing translog.
+ */
+public class TestTranslog {
+    static final Pattern TRANSLOG_FILE_PATTERN = Pattern.compile("translog-(\\d+)\\.tlog");
+
+    public static Set<Path> corruptTranslogFiles(Logger logger, Random random, Collection<Path> translogDirs) throws IOException {
```
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/index/translog/TestTranslog.java]: Can you add javadocs please?

**Review by dakrone — APPROVED** [review]
LGTM, left two minor comments

File: core/src/test/java/org/elasticsearch/index/translog/TestTranslog.java (hunk 1 above)
Comment (dnhatn) [reply core/src/test/java/org/elasticsearch/index/translog/TestTranslog.java]: Done.

File: core/src/test/java/org/elasticsearch/index/store/CorruptedTranslogIT.java [hunk 2]
```diff
@@ -119,51 +114,14 @@ private void corruptRandomTranslogFiles() throws IOException {
         assertTrue(shardRouting.assignedToNode());
         String nodeId = shardRouting.currentNodeId();
         NodesStatsResponse nodeStatses = client().admin().cluster().prepareNodesStats(nodeId).setFs(true).get();
-        Set<Path> files = new TreeSet<>(); // treeset makes sure iteration order is deterministic
+        Set<Path> translogDirs = new HashSet<>(); // treeset makes sure iteration order is deterministic
```
[the remark this answers is not in the document]
Comment (dnhatn) [reply core/src/test/java/org/elasticsearch/index/store/CorruptedTranslogIT.java]: Thanks @dakrone, I've removed it.

**Comment by dnhatn** [comment]
Thanks @dakrone for the review.
