### PR TITLE
Fix SYS COLUMNS schema in ODBC mode

### LINKED ISSUE #59506: SQL: ODBC: SYS COLUMNS column types alignment
This is a regression of #35376, likely caused by #45516.

### PR DESCRIPTION
**Pull request by bpintea**
This PR fixes a regression when certain ODBC-specific columns that need to
be of the short type were returned as the integer type.

Fixes #59506.

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plan/logical/command/sys/SysColumnsTests.java [hunk 1]
```diff
@@ -501,10 +506,29 @@ public void testSysColumnsWithNullCatalog() throws Exception {
         }, mapping);
     }
 
+    private static void checkOdbcShortTypes(SchemaRowSet r) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plan/logical/command/sys/SysColumnsTests.java:509]: Personal preference: I like to have the private methods at the bottom of the class and not before they are first used.

**Review by matriv — APPROVED** [review]
LGTM. Left a minor nit pick comment.

**Comment by bpintea** [comment]
@elasticmachine update branch

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plan/logical/command/sys/SysColumnsTests.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plan/logical/command/sys/SysColumnsTests.java]: Thanks, updated.
I've also updated the actual fix, since it wasn't entirely correct regarding pagination.

**Review by matriv — COMMENTED** [review]
Can we have a test with small page size like 1,2 or 3 ?

**Comment by bpintea** [comment]
@elasticmachine update branch

**Comment by bpintea** [comment]
> Can we have a test with small page size like 1,2 or 3 ?

Yes, good idea. Figured out and fixed a different test stubbing mistake along it.

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Review by astefan — APPROVED** [review]
LGTM
