### PR TITLE
[ES|QL] Add error message when using inline stats on TS before stats

### LINKED ISSUE #136092: INLINE STATS and TS command has confusing output
### Description

There was an [issue](https://github.com/elastic/elasticsearch/issues/134212) and PR for limiting the support of `inline stats` and `ts` commands combination, but it seems there are some combinations of commands that have an unexpected outcome:

- `ts k8s | inline stats  max_bytes=max(to_long(network.total_bytes_in)) BY cluster`
works
- `ts k8s | inline stats max(60 * rate(network.total_bytes_in)), max(network.bytes_in)` 
outputs `time_series aggregate[rate(network.total_bytes_in)] can only be used with the TS command`
- `TS k8s metadata _tsid | inline STATS  cnt = count_distinct(_tsid) BY cluster, pod` 
works
- `TS k8s | INLINE STATS max_cost=max(last_over_time(network.cost)) BY cluster, time_bucket = bucket(@timestamp,1minute)` 
outputs `time_series aggregate[last_over_time(network.cost)] can only be used with the TS command`
- `TS k8s | INLINE STATS max_bytes=max(to_long(network.total_bytes_in)) BY cluster | SORT max_bytes DESC | keep max*, cluster` 
works.

### PR DESCRIPTION
**Pull request by limotova**
This commit adds a clearer error message when attempting to use inline stats in a TS query before a stats command (or on its own), which is unsupported at the moment.

Resolves #136092

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 1]
```diff
@@ -2768,6 +2768,41 @@ public void testTextEmbeddingFunctionInvalidInferenceId() {
...
+                BY host, time_bucket = bucket(@timestamp,1minute)] \
+                is not allowed with TS command, please use the FROM command instead""")
+        );
+
+        assertThat(
+            error("TS test | INLINE STATS max_bytes=max(to_long(network.bytes_in)) BY host | SORT max_bytes DESC | keep max*, host", tsdb),
+            equalTo("""
+                1:1: inline stats [INLINE STATS max_bytes=max(to_long(network.bytes_in)) BY host] \
+                is not allowed with TS command, please use the FROM command instead""")
+        );
```
Comment (kkrik-es) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:2809]: Can we also check the following:

```
TS test  
| STATS max_cost=max(last_over_time(network.connections)) BY host, cluster, TBUCKET(1h)
| INLINE STATS max_cluster_cost=max(max_cost) by cluster
```

or something like that. I think this should be allowed, the output of TS+STATS is no more special.

Comment (limotova) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:2809]: Yeah this seems to work (when the check is removed)
I interpreted the discussion in the original issue as not allowing inline stats with the ts command at all, so I will change the error check to just forbid inline stats before stats

Comment (limotova) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:2809]: Since this is a valid example and this test is mostly testing invalid examples I put something similar in the csv tests, so we can also verify the values

**Review by kkrik-es — APPROVED** [review]
