### PR TITLE
Fix retrieving data stream stats for a DS with multiple backing indices

### LINKED ISSUE #59802: [data streams] Cannot retrieve stats for data stream with multiple backing indices
**Elasticsearch version** (`bin/elasticsearch --version`): Latest `elasticsearch-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

If a data stream contains multiple backing indices, the data streams stats API returns an error. The API works normally for data streams containing a single backing index.

**Steps to reproduce**:

 1. Create a data stream index template.

```
PUT /_index_template/template
{
  "index_patterns": ["my-data-stream*"],
  "data_stream": { }
}
```

 2. Create a matching data stream.

```
PUT /_data_stream/my-data-stream
```

 3. Roll over the data stream.

```
POST /my-data-stream/_rollover/
```

4. Retrieve stats for the data stream.

```
GET /_data_stream/my-data-stream/_stats
```

The API returns the following error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "data_stream [my-data-stream] has more than one indices associated with it [[.ds-my-data-stream-000001, .ds-my-data-stream-000002]], can't execute a single index op"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "data_stream [my-data-stream] has more than one indices associated with it [[.ds-my-data-stream-000001, .ds-my-data-stream-000002]], can't execute a single index op"
  },
  "status" : 400
}
```

### PR DESCRIPTION
**Pull request by dakrone**
This API incorrectly had `allowAliasesToMultipleIndices` set to false in the default options for the
request. This changes it from `false` to `true` and enhances a test to exercise the functionality.

Resolves #59802

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DataStreamsStatsAction.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ public DataStreamsStatsAction() {
         public Request() {
             // this doesn't really matter since data stream name resolution isn't affected by IndicesOptions and
             // a data stream's backing indices are retrieved from its metadata
-            super(null, IndicesOptions.fromOptions(false, true, true, true, false, false, true, false));
+            super(null, IndicesOptions.fromOptions(false, true, true, true, true, false, true, false));
```
Comment (jbaiera) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DataStreamsStatsAction.java:40]: These options are the same for the GetDataStreams API, do those need to be updated as well?

File: x-pack/plugin/data-streams/qa/rest/src/test/resources/rest-api-spec/test/data-streams/120_data_streams_stats.yml [hunk 2]
```diff
@@ -47,13 +47,17 @@ setup:
         name: simple-data-stream1
   - is_true: acknowledged
 
+  - do:
+      indices.rollover:
+        alias: "simple-data-stream1"
+
```
Comment (jbaiera) [inline x-pack/plugin/data-streams/qa/rest/src/test/resources/rest-api-spec/test/data-streams/120_data_streams_stats.yml:53]: Is this better to test in the "Rolled over data stream" test case?

**Review by jbaiera — APPROVED** [review]
Just a couple questions. Otherwise, LGTM

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DataStreamsStatsAction.java (hunk 1 above)
Comment (danhermann) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DataStreamsStatsAction.java:40]: I don't think so because backing indices aren't being resolved in that API.

**Review by danhermann — APPROVED** [review]
LGTM once CI is green.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DataStreamsStatsAction.java (hunk 1 above)
Comment (dakrone) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DataStreamsStatsAction.java:40]: That's a good question, I don't think so (or else I would have expected us to find it much earlier) since those are retrieved differently?

File: x-pack/plugin/data-streams/qa/rest/src/test/resources/rest-api-spec/test/data-streams/120_data_streams_stats.yml (hunk 2 above)
Comment (dakrone) [reply x-pack/plugin/data-streams/qa/rest/src/test/resources/rest-api-spec/test/data-streams/120_data_streams_stats.yml:53]: That test already has a test for this behavior, I'm curious how that didn't fail prior to this, maybe something about the indices being empty triggered it?
