### PR TITLE
Fix updating templates.

### LINKED ISSUE #10397: search templates created with restapi   are not deleteing completely
We created a search templates with rest api  will adds to .scripts index , when we delete the templete it says success and when we explore the index the  templete  won't appear .
  When we recreate the search template with same name  it will create , when we execute the template search it will take the old  deleted  template code . we  updated to latest version 1.5  from 1.4.
You can easily replicate this issue ween u created a template with some wrong syntax , and delete  that template and recreate with same name with valid syntax , then execute it wont work .  I tried to flush cache on that index reorganize too

### PR DESCRIPTION
**Pull request by MaineC**
Closes #10397 

When putting new templates to an index they are added to the cache
of compiled templates as a side effect of the validate method. When
updating templates they are also validated but the scripts that are
already in the cache never get updated.

@javanna Assigning to you for review as you seem to have written most of the code this PR touches, feel free to re-assign.

### CODE REVIEW

File: src/main/java/org/elasticsearch/script/ScriptService.java [hunk 1]
```diff
@@ -262,7 +264,10 @@ public CompiledScript compileInternal(String lang,  String script, ScriptType sc
             script = getScriptFromIndex(indexedScript.lang, indexedScript.id);
         }
 
-        CompiledScript compiled = cache.getIfPresent(cacheKey);
+        CompiledScript compiled = null;
+        if (! ignoreCache) {
+            cache.getIfPresent(cacheKey);
```
Comment (javanna) [inline src/main/java/org/elasticsearch/script/ScriptService.java]: you are entirely disabling the cache if you don't assign the result here to compiled.

**Comment by javanna** [comment]
Hi @MaineC I don't think the problem stems from the validate method. `validate` properly caches using the script itself. The problem is that when we actually retrieve the script from the index as part of the search request, we actually look for and cache the script based on its id. That means it's never going to find the already cached version. Also, once a script is cached based on its id it is never going to be updated in the cache.

I would change the caching mechanism to use the retrieved script as cache key in case the script is indexed, so it will match with the one cached as part of `validate` and it will get cached again once it changes. makes sense?

**Comment by javanna** [comment]
I did some research, this is a regression introduced with #10033 . `1.5.0` and `1.5.1` are affected, meaning that once you executed an indexed script for the first time, that first version is going to stick around in the internal cache although you update the script.  We better add some proper coverage to this :)

**Comment by MaineC** [comment]
The PR comes with a test based on the curl reproduction from @clintongormley - unfortunately the pre-existing test for updating templates only checked that the version of the template in the index updated but didn't actually execute the modified template.

On a different note it seems weird to me that the validate(...) method has side effects on the cache content. Maybe we should either rename it or pull cache modification out of it?

File: src/main/java/org/elasticsearch/script/ScriptService.java (hunk 1 above)
Comment (MaineC) [inline src/main/java/org/elasticsearch/script/ScriptService.java]: That was supposed to read

compiled = cache.getIf...


Stupid typo on my side ...

Comment (javanna) [inline src/main/java/org/elasticsearch/script/ScriptService.java]: the problem is that when you fix it the test fails ;)

**Comment by MaineC** [comment]
@javanna wrt. to your proposal - makes sense, changed the PR accordingly.

I also re-named the "script" parameter in compileInternal to "scriptOrId" to better reflect it's real content.


One thing I was wondering: For indexed scripts we could consistently use their id as part of the cache key. This would save retrieving the string version from the index later (assuming a cache hit). On the flip side it would make it understanding cache keys trickier. Not sure if this is worth the effort?

File: src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java [hunk 2]
```diff
@@ -371,6 +376,45 @@ public void testIndexedTemplate() throws Exception {
...
+
+        PutIndexedScriptRequestBuilder builder = client()
+                .preparePutIndexedScript(MustacheScriptEngineService.NAME, "git01",
+                        "{\"query\": {\"match\": {\"searchtext\": {\"query\": \"{{P_Keyword1}}\",\"type\": \"phrase_prefix\"}}}}")
+                .setOpType(OpType.INDEX);
+        scriptResponse = builder.get();
+        assertEquals(scriptResponse.getVersion(), 2);
+        SearchResponse searchResponse = client().prepareSearch("testindex").setTypes("test").
+                setTemplateName("git01").setTemplateType(ScriptService.ScriptType.INDEXED).setTemplateParams(templateParams).get();
+        assertHitCount(searchResponse, 1);
```
Comment (javanna) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: I would love to have some more coverage here, maybe update a few more times (`randomIntBetween(1,10)` ?) and verify that updates always make it through, not just once?

Also, can we write a test for plain indexed scripts too (rather than search templates)?

File: src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java [hunk 3]
```diff
@@ -371,6 +376,45 @@ public void testIndexedTemplate() throws Exception {
...
+    // Relates to #10397
+    @Test
+    public void testIndexedTemplateOverwrite() throws Exception {
+        createIndex("testindex");
+        ensureGreen("testindex");
+
+        index("testindex", "test", "1", jsonBuilder().startObject().field("searchtext", "dev1").endObject());
+        refresh();
+
+        PutIndexedScriptResponse scriptResponse = client().preparePutIndexedScript(MustacheScriptEngineService.NAME, "git01",
```
Comment (javanna) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: was wondering, should we use put template here instead of put indexed script?

File: src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java [hunk 4]
```diff
@@ -371,6 +376,45 @@ public void testIndexedTemplate() throws Exception {
...
+        ensureGreen("testindex");
+
+        index("testindex", "test", "1", jsonBuilder().startObject().field("searchtext", "dev1").endObject());
+        refresh();
+
+        PutIndexedScriptResponse scriptResponse = client().preparePutIndexedScript(MustacheScriptEngineService.NAME, "git01", 
+                "{\"query\": {\"match\": {\"searchtext\": {\"query\": \"{{P_Keyword1}}\",\"type\": \"ooophrase_prefix\"}}}}").get();
+        assertTrue(scriptResponse.isCreated());
+
+        GetIndexedScriptResponse getResponse = client().prepareGetIndexedScript(MustacheScriptEngineService.NAME, "git01").get();
```
Comment (javanna) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: along the same lines, should we use get template here instead?

**Comment by javanna** [comment]
looks good, left a couple of comments around testing.

**Comment by MaineC** [comment]
@javanna Thanks for the review and comments - good suggestions, will update accordingly.

File: src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java (hunk 3 above)
Comment (MaineC) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: I must be missing something: I don't find a client().preparePutTemplate(...) nor client().putTemplate(...)

Can you elaborate please?

Comment (javanna) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: I meant `client().admin().indices().preparePutTemplate()`  or `client().admin().indices().putTemplate()`.

Comment (MaineC) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: Maybe I'm confused but I think we are talking about two different templates:

The template this test is checking is the following: http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-template.html


The template that can be stored with the methods you mentioned seems to refer to the following:
http://www.elastic.co/guide/en/elasticsearch/reference/1.x/indices-templates.html

Comment (javanna) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: You are right, I messed up :)  I was pretty sure we had dedicated apis for search templates, but I confused the REST layer with the Java api. Leave it as-is, sorry for the confusion!

File: src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java [hunk 5]
```diff
@@ -372,6 +374,47 @@ public void testIndexedTemplate() throws Exception {
...
+    // Relates to #10397
+    @Test
+    public void testIndexedTemplateOverwrite() throws Exception {
+        createIndex("testindex");
+        ensureGreen("testindex");
+
+        index("testindex", "test", "1", jsonBuilder().startObject().field("searchtext", "dev1").endObject());
+        refresh();
+
+        for (int i = 1; i < randomIntBetween(2, 11); i++) {
```
Comment (javanna) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: I don't think it is a good idea to call randomInBetween from here? We should save the result to a variable outside of the loop.

File: src/test/java/org/elasticsearch/script/IndexedScriptTests.java [hunk 6]
```diff
@@ -87,6 +88,29 @@ public void testFieldIndexedScript()  throws ExecutionException, InterruptedExce
...
 
+    // Relates to #10397
+    @Test
+    public void testUpdateScripts() {
+        createIndex("test_index");
+        ensureGreen("test_index");
+        client().prepareIndex("test_index", "test_type", "1").setSource("{\"foo\":\"bar\"}").get();
+        flush("test_index");
+
+        for (int i = 1; i < randomIntBetween(2, 11); i++) {
```
Comment (javanna) [inline src/test/java/org/elasticsearch/script/IndexedScriptTests.java]: same as above

**Comment by javanna** [comment]
I left a small comments around tests, LGTM besides that

File: src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java (hunk 5 above)
Comment (MaineC) [inline src/test/java/org/elasticsearch/index/query/TemplateQueryTest.java]: m(

Good catch.
