### PR TITLE
Watcher: Validate email adresses when storing a watch

### LINKED ISSUE #33980: Watcher email action fails completely if there is at least one invalid email
**Elasticsearch version**: `6.2+ but can be applied to previous and latest versions`

**JVM version**: `not relevant`

**OS version**: `not relevant`

**Description of the problem including expected versus actual behavior**:

In case we have several recipient emails in a email action, the watcher is NOT successful until ALL emails are valid.

Should we notify about the invalid format?
Should we notify about the failed delivery?

**Steps to reproduce**:

 1. Install Elasticsearch and Kibana
 2. Add email settings for watcher (a valid smtp)
 3. Create a dummy watcher with an email notification and provide the several addresses as recipients
 4. Test with recipients below

FYI the emails below are redacted:
`xxxxxxxxx@gmail.com` is a valid address.
`yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com` is a not existing address.
`xxxxxxxxx+ahaha@gmail.com` is a valid address (will be sent to `xxxxxxxxx@gmail.com`)

**Several tests**

`xxxxxxxxx@gmail.com, gudsauigdsagiusadsadui, lol.com, a@com, xxxxxxxxx+ahaha@gmail.com, yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`

> The watcher fails completely, no mail sent.

`xxxxxxxxx@gmail.com, a@com, xxxxxxxxx+ahaha@gmail.com, yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`

> The watcher is successful, all mails sent by SMTP. The SMTP Delivery service will notify later 2 out (`a@com` and `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`) of 4 emails cannot be delivered.

`a@com, xxxxxxxxx+ahaha@gmail.com, yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`

> The watcher is successful, all mails sent by SMTP. The SMTP Delivery service will notify later 2 out (`a@com` and `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`) of 3 emails cannot be delivered.

`a@com, x`

> The watcher fails completely, no mail sent.

`x, xxxxxxxxx@gmail.com`

> The watcher fails completely, no mail sent.

### PR DESCRIPTION
**Pull request by spinscale**
Right now, watches fail on runtime, when invalid email addresses are
used.

All those fields can be checked on parsing, if no mustache is used in
any email address template. In that case we can return immediate
feedback, that invalid email addresses should not be specified when
trying to store a watch.

**Reviewers note**: This is rather for discussion than for review. Do you think this makes sense despite the additional check if mustache templates are used or not? When mustache is used, than this can still fail on runtime - even though the majority of the cases that I have seen are indeed using static email addresses when defining a watch.

Closes #33980

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java [hunk 1]
```diff
@@ -29,10 +29,12 @@
 
     private final Script script;
     private final String inlineTemplate;
+    private final boolean isUsingMustache;
 
     public TextTemplate(String template) {
         this.script = null;
         this.inlineTemplate = template;
+        this.isUsingMustache = template.contains("{{") && template.indexOf("{{") < template.indexOf("}}");
```
Comment (hub-cap) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java]: sneak attack bring back the validation

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java [hunk 2]
```diff
@@ -48,12 +50,15 @@ public TextTemplate(String template, @Nullable XContentType contentType, ScriptT
...
         }
         this.script = new Script(type, type == ScriptType.STORED ? null : Script.DEFAULT_TEMPLATE_LANG, template, options, params);
+        this.isUsingMustache = template.contains("{{") && template.indexOf("{{") < template.indexOf("}}");
         this.inlineTemplate = null;
     }
 
     public TextTemplate(Script script) {
         this.script = script;
         this.inlineTemplate = null;
+        this.isUsingMustache = script.getIdOrCode().contains("{{") &&
```
Comment (hub-cap) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java]: can we lazy load this in the getter? maybe remove the word `get` so we know it "mutates state" and load it once only if we decide to actually validate if we care or not. At least it will appease the `contains`'ing every string is bad gods.

**Review by hub-cap — APPROVED** [review]
Big +1 for validation. Small nits on the way we evaluate using mustache, would love your thoughts.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java (hunk 2 above)
Comment (spinscale) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java]: I changed this only to check for `{{`, and it #33978 will introduce a check for every text template, so that this will be called anyway...

Comment (hub-cap) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/text/TextTemplate.java]: oof, how did i miss that? I guess going backwards thru my review-requested emails is not such a good idea!!

**Comment by hub-cap** [comment]
still lgtm
