### PR TITLE
Adjust AutoFollowIT#testDataStreams_autoFollowAfterDataStreamCreated() test

### LINKED ISSUE #72062: [CI] AutoFollowIT testDataStreams_autoFollowAfterDataStreamCreated failing
Subsequent tests failed as well, but I suspect they are due to this initial failure.
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"
  },
  "status": 400
}
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/q4m7uwwqj7mei/tests/:x-pack:plugin:ccr:qa:multi-cluster:follow-cluster/org.elasticsearch.xpack.ccr.AutoFollowIT/testDataStreams_autoFollowAfterDataStreamCreated

**Reproduction line:**
`./gradlew ':x-pack:plugin:ccr:qa:multi-cluster:follow-cluster' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testDataStreams_autoFollowAfterDataStreamCreated" -Dtests.seed=197AA5A92FE81C06 -Dtests.locale=sr-Latn-BA -Dtests.timezone=America/Argentina/San_Juan -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ccr.AutoFollowIT&tests.test=testDataStreams_autoFollowAfterDataStreamCreated

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:45566], URI [/.ds-logs-syslog-prod-2021.04.22-000001/_ccr/follow?wait_for_active_shards=1], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"}],"type":"illegal_argument_exception","reason":"the leader index settings [{\"index.lifecycle.indexing_complete\":\"true\",\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] and follower index settings [{\"index.lifecycle.name\":\"logs\",\"index.number_of_shards\":\"1\"}] must be identical"},"status":400}

  at __randomizedtesting.SeedInfo.seed([197AA5A92FE81C06:AD357CF326BDC165]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:109)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:81)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:77)
  at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.followIndex(ESCCRRestTestCase.java:73)
  at org.elasticsearch.xpack.ccr.AutoFollowIT.testDataStreams_autoFollowAfterDataStreamCreated(AutoFollowIT.java:319)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by martijnvg**
Adjust ccr data stream test that tests following a backing index
 after the data stream has been auto followed.

Avoid that a data stream matches with a builtin template that uses ilm.
The manual rollover that happens in this test, may cause ilm to add
`index.lifecycle.indexing_complete` setting, which causes explicit
follow index api call to fail in this test

Closes #72062

### CODE REVIEW

File: x-pack/plugin/ccr/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ccr/AutoFollowIT.java [hunk 1]
```diff
@@ -320,12 +320,21 @@ public void testDataStreams_autoFollowAfterDataStreamCreated() throws Exception
...
         int initialNumberOfSuccessfulFollowedIndices = getNumberOfSuccessfulFollowedIndices();
-        final String dataStreamName = "logs-syslog-prod";
-        final String autoFollowPatternName = getTestName().toLowerCase(Locale.ROOT);
+        // The data stream name shouldn't match with builtin ilm policies to avoid test instabilities.
+        // (the manual rollover that happens in this test, may cause ilm to add `index.lifecycle.indexing_complete` setting,
+        // which causes explicit follow index api call to fail in this test)
+        final String dataStreamName = "log-syslog-prod";
+        // Because the builtin logs template isn't used, a template should be defined here.
+        Request putComposableIndexTemplateRequest = new Request("POST", "/_index_template/" + getTestName().toLowerCase(Locale.ROOT));
+        putComposableIndexTemplateRequest.setJsonEntity("{\"index_patterns\": [\"log-syslog-*\"], \"data_stream\": {}}");
```
Comment (tlrx) [inline x-pack/plugin/ccr/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ccr/AutoFollowIT.java:329]: I find such generic patterns very trappy in CCR rest tests, because the cluster is not cleaned up between tests cases. For example, there is a very similar `logs-syslog-prod` data stream in `FollowIndexIT`.

We should maybe use more specific names like `test-auto-follow-backing-indices-*` ?

**Review by tlrx — APPROVED** [review]
LGTM, I left a minor comment. Thanks for fixing this Martijn!

File: x-pack/plugin/ccr/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ccr/AutoFollowIT.java (hunk 1 above)
Comment (martijnvg) [reply x-pack/plugin/ccr/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ccr/AutoFollowIT.java:329]: 👍 I will update the template to use a specific template.
