### PR TITLE
Fix enrich cache corruption bug

### LINKED ISSUE #82340: Enrich Processor Cache can be Corrupted by Processors that Mutate a Document (E.g. Rename)
Using the enrich processor in a pipeline with a rename or other processor that mutates the mutable maps backing an ingest document can corrupt the caches in the enrich processor.

An easy reproducer for this goes as follows:

have the following enrich policy:

```
PUT /_enrich/policy/device-enrich-policy
{
  "match": {
    "indices": "devices-idx",
    "match_field": "host.ip",
    "enrich_fields": [
      "device.name",
      "host.ip"
    ]
  }
}
```

add a document to the backing index as such:

```
POST devices-idx/_doc
{
  "host": {
    "ip": "10.151.80.8"
  },
  "device": {
    "name": "bla"
  }
}
```

... then execute the enrich policy.

... and finally execute following pipeline simulation:

``` 
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "enrich": {
          "policy_name": "device-enrich-policy",
          "field": "host.ip",
          "target_field": "_tmp.device",
        }
      },
      {
        "rename" : {
          "field" : "_tmp.device.device.name",
          "target_field" : "device.name",
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "host": {
          "ip": "10.151.80.8"
        }
      }
    }
  ]
}
```

this will show the expected result of having the device name added under `_tmp.device`.

Now adjust to a simpler pipeline:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "enrich": {
          "policy_name": "device-enrich-policy",
          "field": "host.ip",
          "target_field": "_tmp"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "host": {
          "ip": "10.151.80.8"
        }
      }
    }
  ]
}
```

which you would expect to show the same result because `device.name` would just be copied under `_tmp`.

What you do get instead is:

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_doc",
        "_id" : "_id",
        "_source" : {
          "host" : {
            "ip" : "10.151.80.8"
          },
          "_tmp" : {
            "host" : {
              "ip" : "10.151.80.8"
            },
            "device" : { }
          }
        },
        "_ingest" : {
          "timestamp" : "2022-01-07T16:21:55.868673023Z"
        }
      }
    }
  ]
}
```

This is explained by the fact that the rename processor mutates the map that it works with. It removes and adds a field to a document. This map though is also referenced by: `org.elasticsearch.search.SearchHit#sourceAsMap` which is cached. 

-> rename processor mutates that map by mutating the ingest document from the first run -> cache is corrupted.

This was observed in a complicated to debug user issue where a pipeline would randomly fail during simulate like this for no apparent reason. Digging through the diags it turned out that the same enrich policy was used in another pipeline followed by the rename processor in the way described above, thus corrupting the policy's cache repeatedly.

### PR DESCRIPTION
**Pull request by martijnvg**
The enrich cache currently uses `SearchResponse` as cache value,
which contains the hits used by the enrich processor for enrichment.
What is actually used is by the enrich processor is `SearchHit.getSourceAsMap()`,
which is a map of maps representation of a search hit.

The problem is that this map is mutable and the map of maps is directly
passed into `IngestDocument` and at the same time this is cached by the
enrich cache via `SearchResponse` cache value. Any processor that modifies
the content added by the enrich processor, also changes the map of maps
representation of a search hit in the cache. This corrupts the cache,
because if this the enrich cache serves a cache entry for the same key,
a different snippet added to the document being enriched.

The following changes have been made to fix this bug:
* Use `List<Map<?, ?>>` as cache value for the enrich cache.
* Upon caching lookup / search, make an immutable deep copy of `SearchHit.getSourceAsMap()`.
* Upon serving an entry from the cache, make a normal deep copy,
  so the enrichent can be safely modified by subsequent processors.

Closes #82340

### CODE REVIEW

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java [hunk 1]
```diff
@@ -43,11 +49,11 @@
  */
 public class EnrichCache {
 
-    protected final Cache<CacheKey, CompletableFuture<SearchResponse>> cache;
+    protected final Cache<CacheKey, CompletableFuture<List<Map<?, ?>>>> cache;
```
Comment (martijnvg) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java:52]: I was thinking, maybe we store the enrich hits as byte[]? And then upon retrieval we parse it into `List<Map<?, ?>>`. 

We already do some work here just before storing a cache entry (recursively make an immutable copy of the search hits (just to catch anyone trying to corrupt the cache) ) and when serving from this cache (recursively make a mutable copy of the search hits). 

I think if we cache the byte[] representation of search hits we save some heap space. At the cost of some additional operations when serving from cache or adding a new entry to cache. But that should be ok, since we already do some extra work making deep copies.

Comment (original-brownbear) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java:52]: It is hard to guess for me what the right tradeoff is in terms of the cache size vs compute cost here. Even a deep copy will be far cheaper than deserialisation that's for sure. I think instinctively I'd rather go for a deep copy because that saves memory after retrieval because all the strings (at least the map keys) will be shared instead of recreated on parsing over and over.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java [hunk 2]
```diff
@@ -127,6 +136,45 @@ private String getEnrichIndexKey(SearchRequest searchRequest) {
...
+        }
+        return Collections.unmodifiableList(result);
+    }
+
+    @SuppressWarnings("unchecked")
+    private static <T> T deepCopy(T value, boolean unmodifiable) {
+        return (T) innerDeepCopy(value, unmodifiable);
+    }
+
+    private static Object innerDeepCopy(Object value, boolean unmodifiable) {
```
Comment (danhermann) [inline x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java:152]: I'm not as familiar with all the data types that may be present in the map from a `SearchHit`, but `IngestDocument::deepCopy` handles a couple types that this method does not. ([link](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/ingest/IngestDocument.java#L742))

**Review by danhermann — APPROVED** [review]
LGTM. Left one non-blocking comment below that might not be relevant for search hits.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java (hunk 1 above)
Comment (martijnvg) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java:52]: I see, this makes sense. Let's stick with creating a deep copy each time an entry from the cache is used.

File: x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java (hunk 2 above)
Comment (martijnvg) [reply x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichCache.java:152]: Initially I looked at the `IngestDocument#deepCopy(...)`  method, but then realised that some of the data type (e.g. `Set`, `long[]`, `Date`) are never in the search hit. The `SearchHit.getSourceAsMap()` method uses `XContentHelper#convertToMap(...)` method, which eventually invokes `AbstractXContentParser#readValueUnsafe(...)` via `XContentParser#map()` method and I think the mentioned types are never produced by the `readValueUnsafe()` method.

I think we can reuse `IngestDocument#deepCopy(...)`. There is some code duplication between the two methods. But this method will then need to be modified to optionally wrap list / map in an unmodifiable wrapper and this would only be used by `EnrichCache`. I currently lean towards keeping this method, since the code duplication is minimal and it is targeted for creating a deep copy of search hits. But if we keep this method then we need a good unit test for it as well. What do you think?

**Review by original-brownbear — APPROVED** [review]
LGTM :) Thanks for the quick turnaround here Martijn!

**Comment by danhermann** [comment]
>I currently lean towards keeping this method, since the code duplication is minimal and it is targeted for creating a deep copy of search hits. But if we keep this method then we need a good unit test for it as well. What do you think?

@martijnvg, that sounds good to me. You might be able to repurpose some of the existing unit tests for `IngestDocument::deepCopy` for this method.
