### PR TITLE
Move parsing of allocation commands into REST and remove support for plugins to register allocation commands

### LINKED ISSUE #17894: Do we need custom allocation commands?
As part of #17802 we are taking into account the fact that a plugin could potentially plug in custom allocation commands. That has always been untested, hence got broken in master till it got fixed a few days ago as part of Nik's refactorings.

I now wonder if we should test this extension point so that we can claim we support it, or if we can instead simply remove it as it is not needed. Is there any custom allocation command out there? Anybody can think of why this extension point would be needed?

### PR DESCRIPTION
**Pull request by nik9000**
Port them to the ObjectParser.

Closes #17894

### CODE REVIEW

**Comment by nik9000** [comment]
@javanna this is what you asked me to do in https://github.com/elastic/elasticsearch/commit/fe4d1297dfb5d07d4214757358b7927034a18606#commitcomment-17117314 I think.

**Comment by javanna** [comment]
thanks @nik9000 ! do we have tests for this parse method somewhere? Maybe we should unit test it, especially if while moving we switch it to object parser.

**Comment by nik9000** [comment]
> Maybe we should unit test it, especially if while moving we switch it to object parser.

yeah, that certainly occurred to me as I was going about my evening last night. I'll look into that when I get a chance.

We have some fairly basic REST tests for it - never for parsing more than one at a time.

**Comment by nik9000** [comment]
@javanna I added round trip testing for parsing and streaming to this. Most of the work is implementing equals and hashCode.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java [hunk 1]
```diff
@@ -59,12 +58,4 @@ public ClusterRerouteRequestBuilder setExplain(boolean explain) {
...
         return this;
     }
-
-    /**
-     * Sets the commands for the request to execute.
-     */
-    public ClusterRerouteRequestBuilder setCommands(AllocationCommand... commands) throws Exception {
-        request.commands(commands);
-        return this;
-    }
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java]: don't we have to replace this setter with the new corresponding one that we have in the request?

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+        command(() -> new MoveAllocationCommand(randomAsciiOfLengthBetween(2, 10), between(0, 1000),
+                randomAsciiOfLengthBetween(2, 10), randomAsciiOfLengthBetween(2, 10)));
+        namedWriteableRegistry = new NamedWriteableRegistry();
+        allocationCommandRegistry = new NetworkModule(null, null, true, namedWriteableRegistry).getAllocationCommandRegistry();
+    }
+
+    /**
+     * Registers a random generator for a type of command.
+     */
+    protected void command(Supplier<AllocationCommand> generator) {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: private?

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+            }
+        }
+    }
+
+    private ClusterRerouteRequest roundTripThroughRestRequest(ClusterRerouteRequest original) throws IOException {
+        RestRequest restRequest = toRestRequest(original);
+        return RestClusterRerouteAction.createRequest(restRequest, allocationCommandRegistry, ParseFieldMatcher.STRICT);
+    }
+
+    public RestRequest toRestRequest(ClusterRerouteRequest original) throws IOException {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: does this need to be public?

Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: maybe it can also be made static

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+        for (int round = 0; round < ROUNDS; round++) {
+            ClusterRerouteRequest request = randomRequest();
+            ClusterRerouteRequest copy = roundTripThroughRestRequest(request);
+            assertEquals(request, copy);
+            assertEquals(request.hashCode(), copy.hashCode());
+            assertNotSame(request, copy);
+        }
+    }
+
+    private ClusterRerouteRequest roundTripThroughBytes(ClusterRerouteRequest original) throws IOException {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: can this be static?

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+import java.util.List;
+import java.util.Map;
+import java.util.function.Supplier;
+
+import static java.util.Collections.emptyMap;
+
+/**
+ * Test for serialization and parsing of {@link ClusterRerouteRequest} and its commands.
+ */
+public class ClusterRerouteRequestRoundTripTests extends ESTestCase {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: I think I would simply call it ClusterRerouteRequestTests. We should probably add tests for equals and hascode too.

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java [hunk 6]
```diff
@@ -0,0 +1,162 @@
...
+    }
+
+    /**
+     * Registers a random generator for a type of command.
+     */
+    protected void command(Supplier<AllocationCommand> generator) {
+        randomCommandGenerators.add(generator);
+    }
+
+    private ClusterRerouteRequest randomRequest() {
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: can this be static?

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java (hunk 2 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: do we really need a method with a supplier here? This could have been a randomCommandGenerators.add line in the constructor as well right?

File: core/src/main/java/org/elasticsearch/rest/action/admin/cluster/reroute/RestClusterRerouteAction.java [hunk 7]
```diff
@@ -89,4 +94,34 @@ protected void addCustomFields(XContentBuilder builder, ClusterRerouteResponse r
             }
         });
     }
+
+    public static ClusterRerouteRequest createRequest(RestRequest request, AllocationCommandRegistry registry,
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/rest/action/admin/cluster/reroute/RestClusterRerouteAction.java]: does this need to be public?

**Comment by javanna** [comment]
thanks for adding the tests, I left a few more comments

File: core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java (hunk 1 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java]: I believe the builder already had one called `add`. I didn't see it the first time.

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java (hunk 2 above)
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: I made the method so that if a plugin makes a new command they can just subclass this test and register the generator with this method. The supplier is so that every time you call the method it generates a new random command.

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java (hunk 6 above)
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: It needs the generators member.

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java (hunk 4 above)
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: It needs the allocationCommandRegistry.

**Comment by nik9000** [comment]
@javanna I believe I answered your comments either inline or with the patch I just pushed.

File: core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java (hunk 1 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java]: sure but if you remove this set you could add the other set?

File: core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java (hunk 2 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestRoundTripTests.java]: do we have a plugin that does this? This seems complicated and over-engineered to me, if nobody uses this for real the reason why we have it will get lost.

File: core/src/main/java/org/elasticsearch/rest/action/admin/cluster/reroute/RestClusterRerouteAction.java (hunk 7 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/rest/action/admin/cluster/reroute/RestClusterRerouteAction.java]: If we want the test to see it and we don't want to move this class then yes.

**Comment by nik9000** [comment]
@javanna looks like the discussion about the commands method is getting eaten when I push new patches. My point is that making commands a thing you can register means that plugins can do it so we may as well give them a good way to test. It isn't that much work in our test to do that. I've pushed some javadocs explaining it on the test. I get your point about losing it the next time someone changes the test though.

**Comment by javanna** [comment]
@nik9000 can we test this extension point for commands by plugging a custom one in so that also this test utilities it's used the way plugins would use it?

**Comment by nik9000** [comment]
Sure

**Comment by nik9000** [comment]
> Sure

Done.

**Comment by nik9000** [comment]
@javanna I rebased this and removed the ability for plugins to register allocation commands. It was super out of date. Sorry for the rebase!

File: core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java (hunk 1 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteRequestBuilder.java]: It is just called `add` and I don't think `set` makes sense there.

**Comment by javanna** [comment]
@nik9000 LGTM please add breaking label and highlight the removal of custom allocation commands.

**Comment by nik9000** [comment]
@javanna I've rebased to resolve some minor conflicts and added a note to the breaking changes docs. Can you have a look a the breaking changes note?

File: docs/reference/migration/migrate_5_0/allocation.asciidoc [hunk 8]
```diff
@@ -39,6 +39,14 @@ command corresponds to the old `allocate` command  with `allow_primary` set to
 false. The new `allocate_empty_primary` command corresponds to the old
 `allocate` command with `allow_primary` set to true.
 
+==== Custom Reroute Commands
+
+Elasticsearch no longer supports plugins registering custom allocation
+commands. It didn't look like it fully worked anyway and when we went to get
+it working and tested we realized it was a fairly scary thing for a plugin to
+do. If this is really really a thing your plugin needs to do then open a
+github issue.
```
Comment (javanna) [inline docs/reference/migration/migrate_5_0/allocation.asciidoc]: can we have a bit less information here? Just say it was unused and probably not needed.

**Comment by javanna** [comment]
left a comment on breaking changes docs, feel free to push once updated

File: docs/reference/migration/migrate_5_0/allocation.asciidoc (hunk 8 above)
Comment (nik9000) [inline docs/reference/migration/migrate_5_0/allocation.asciidoc]: I pushed an update.
