### PR TITLE
Fix bug where field is not returned if it has the same prefix as a nested field

### LINKED ISSUE #82905: Field not returned if it has the same prefix as a nested field
**Elasticsearch version**: 7.16.2

**Plugins installed**: []

**JVM version**: Bundled in official Elasticsearch docker image

**OS version**: Bundled in official Elasticsearch docker image

**Description of the problem including expected versus actual behavior**:

Running Elasticsearch on ECK, an index containing fields `foo` and `foo_bar` will not allow returning field `foo_bar` if `foo` is of type `nested`. This means any field that has the same prefix as a sibling field with type `nested` can be queried on, but is not returned even if requested, the `foo_bar` field is returned as part of `_source`.

More background documented in https://discuss.elastic.co/t/vector-tiles-search-not-returning-hits-on-geo-shape-fields/294926/10

Although the discussion is about `geo_shape` fields, I also reproduced it with type `keyword` for `foo_bar`.

Thanks for helping with this!

**Steps to reproduce**:

```
PUT /locations
{
  "mappings": {
    "properties": {
      "stops": {
        "type": "nested",
        "properties": {
          "stop_id": {
            "type": "keyword"
          }
        }
      },
      "stops_geoshape": {
        "type": "geo_shape"
      }
    }
  }
}

POST /locations/_bulk
{ "index": { "_id": "1" } }
{ "stops_geoshape": {"coordinates":[[[24.7412109375,59.45624336447568],[23.70849609375,56.64414704199467]],[[12.41455078125,51.358061573190916],[8.76708984375,53.12040528310657]]],"type":"multilinestring" } }

POST /locations/_search
{
  "query": {
    "geo_bounding_box": {
      "stops_geoshape": {
        "bottom_right": {
          "lat": 35.029996,
          "lon": 36.079102
        },
        "top_left": {
          "lat": 62.714462,
          "lon": -12.436523
        }
      }
    }
  },
  "fields": ["stops_geoshape"],
  "_source": ["stops_geoshape"]
}

{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": "locations",
        "_type": "_doc",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "stops_geoshape": {
            "coordinates": [
              [
                [
                  24.7412109375,
                  59.45624336447568
                ],
                [
                  23.70849609375,
                  56.64414704199467
                ]
              ],
              [
                [
                  12.41455078125,
                  51.358061573190916
                ],
                [
                  8.76708984375,
                  53.12040528310657
                ]
              ]
            ],
            "type": "multilinestring"
          }
        }
      }
    ]
  }
}
```

As you can see, the search response does not include the `stops_geoshape` field, although it was requested. Renaming the nested field `stops` to be `stopss` results in expected result - the `stops_geoshape` field being returned in the response. Adding an alias to the underlying `stops_geoshape` field works:

```
PUT /locations/_mapping
{
  "properties": {
    "geoshape": {
      "type": "alias",
      "path": "stops_geoshape" 
    }
  }
}

POST /locations/_search
{
  "query": {
    "geo_bounding_box": {
      "stops_geoshape": {
        "bottom_right": {
          "lat": 35.029996,
          "lon": 36.079102
        },
        "top_left": {
          "lat": 62.714462,
          "lon": -12.436523
        }
      }
    }
  },
  "fields": ["stops_geoshape", "geoshape"],
  "_source": [ "stops_geoshape"]
}

{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1.0,
    "hits": [
      {
        "_index": "locations",
        "_type": "_doc",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "stops_geoshape": {
            "coordinates": [
              [
                [
                  24.7412109375,
                  59.45624336447568
                ],
                [
                  23.70849609375,
                  56.64414704199467
                ]
              ],
              [
                [
                  12.41455078125,
                  51.358061573190916
                ],
                [
                  8.76708984375,
                  53.12040528310657
                ]
              ]
            ],
            "type": "multilinestring"
          }
        },
        "fields": {
          "geoshape": [
            {
              "coordinates": [
                [
                  [
                    24.7412109375,
                    59.45624336447568
                  ],
                  [
                    23.70849609375,
                    56.64414704199467
                  ]
                ],
                [
                  [
                    12.41455078125,
                    51.358061573190916
                  ],
                  [
                    8.76708984375,
                    53.12040528310657
                  ]
                ]
              ],
              "type": "MultiLineString"
            }
          ]
        }
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by iverase**
We currently only check if a field starts with the same characters as a nested prefix but we do not check that the next character of the field is a path separator ('.'). This commit updates the check to make sure we distinguish between a nested path and a field with the same nested prefix.

fixes https://github.com/elastic/elasticsearch/issues/82905

### CODE REVIEW

**Comment by iverase** [comment]
known issue: https://github.com/elastic/elasticsearch/issues/82502

@elasticmachine run elasticsearch-ci/rest-compatibility

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java [hunk 1]
```diff
@@ -1002,6 +1002,33 @@ public void testLastFormatWins() throws IOException {
...
+            .field("type", "keyword")
+            .endObject()
+            .endObject()
+            .endObject()
+            .startObject("foo_bar")
+            .field("type", "double")
+            .endObject()
+            .endObject()
+            .endObject()
+            .endObject();
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java:1023]: nit: with checkstyle rules these large XContentBuilder setups are hard to read. I'm wondering if we can use the new Java text blocks to create the mapping from a readable String representation, but then again I haven't found a quick example after some searching just now. Happy to leave it as is for now but if you have an idea how to remedy this I'd be glad to see and copy going forward.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/FieldFetcher.java [hunk 2]
```diff
@@ -87,7 +87,9 @@ private static FieldFetcher create(
                 if (nestedParentPaths.isEmpty() == false) {
                     // try to find the shortest nested parent path for this field
                     for (String nestedFieldPath : nestedParentPaths) {
-                        if (field.startsWith(nestedFieldPath)) {
+                        if (field.startsWith(nestedFieldPath)
+                            && field.length() > nestedFieldPath.length()
+                            && field.charAt(nestedFieldPath.length()) == '.') {
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/search/fetch/subphase/FieldFetcher.java:92]: Looks good to me, maybe @romseygeek has some comments on directly checking the field separator though because he is currently working on allowing dots in fields names. As far as I understand this should be okay here though, just checking for making sure...

**Review by cbuescher — APPROVED** [review]
Thanks for fixing this, LGTM but I would like a quick check from @romseygeek if the direct use of the field separator is okay going forward for the work he is currently doing with dots in fieldnames.

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java (hunk 1 above)
Comment (iverase) [reply server/src/test/java/org/elasticsearch/search/fetch/subphase/FieldFetcherTests.java]: Changed to use Java text blocks. Yes, it makes it easier to read.

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/FieldFetcher.java (hunk 2 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/FieldFetcher.java:92]: This is fine for now. I have a PR which simplifies some of this nested path handling which I think will help here as well in the longer term (#75677) but the newly added test should ensure that things work correctly.

**Review by romseygeek — APPROVED** [review]
LGTM
