### PR TITLE
EQL: Add number function

### LINKED ISSUE #54471: EQL: implement number function
Part of #51556
https://eql.readthedocs.io/en/latest/query-guide/functions.html#number
`number(input: str, [base: int]) -> int|float`

#### Function behavior
Validation requirements:
* Accepts isString()
* Return null if input is null
* Autodetect the base if none provided
    * input startswith "0x": 16
    * otherwise: 10
* Tries to parse as integer. If that succeeds, it's returned as an integer
* If non-integer, then try to parse as a float. If that doesn't succeed, raise an EQL illegal argument exception. or is it better to raise the original exception?

### PR DESCRIPTION
**Pull request by rw-access**
Resolves #54471

Added function to parse numbers from strings.
One note is that the resolved DataType is double. Since it can return integer, float, or number. Double seemed to be the most inclusive.

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+import org.elasticsearch.xpack.ql.tree.Source;
+
+import java.util.Arrays;
+import java.util.Collections;
+import java.util.List;
+import java.util.Objects;
+
+public class ToNumberFunctionPipe extends Pipe {
+
+    private final Pipe source, base;
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java:21]: Use the same name for the first argument as in `ToNumber.java` (`value` instead of `source`).

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+    public final Pipe replaceChildren(List<Pipe> newChildren) {
+        if (newChildren.size() != 2) {
+            throw new IllegalArgumentException("expected [2] children but received [" + newChildren.size() + "]");
+        }
+        return new ToNumberFunctionPipe(source(), expression(), newChildren.get(0), newChildren.get(1));
+    }
+
+    @Override
+    public final Pipe resolveAttributes(AttributeResolver resolver) {
+        Pipe newSource = source.resolveAttributes(resolver);
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java:40]: Did you forget the `base` here?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+        if (newSource == source) {
+            return this;
+        }
+        return replaceChildren(Collections.singletonList(newSource));
+    }
+
+    @Override
+    public boolean supportedByAggsOnlyQuery() {
+        return source.supportedByAggsOnlyQuery();
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java:49]: `base`?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+    }
+
+    @Override
+    public boolean resolved() {
+        return source.resolved();
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionPipe.java:54]: `base`?
And the rest of the class.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/EqlFunctionRegistry.java [hunk 5]
```diff
@@ -37,6 +38,7 @@ public EqlFunctionRegistry() {
                 def(EndsWith.class, EndsWith::new, "endswith"),
                 def(IndexOf.class, IndexOf::new, "indexof"),
                 def(Length.class, Length::new, "length"),
+                def(ToNumber.class, ToNumber::new, "number"),
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/EqlFunctionRegistry.java:41]: I think we should add a new `FunctionDefinition[]` array for math/numerical functions.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    public ToNumberFunctionProcessor(StreamInput in) throws IOException {
+        value = in.readNamedWriteable(Processor.class);
+        base = in.readNamedWriteable(Processor.class);
+    }
+
+    @Override
+    public final void writeTo(StreamOutput out) throws IOException {
+        out.writeNamedWriteable(value);
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:37]: You forgot `base`.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+    public Object process(Object input) {
+        return doProcess(value.process(input), base.process(input));
+    }
+
+    public static Integer parseHexadecimal(String source) {
+        source = source.startsWith("0x") ? source.substring(2) : source;
+        return Integer.parseInt(source, 16);
+    }
+
+    public static Object doProcess(Object source, Object base) {
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:50]: Use `value` instead of `source` to have a consistent naming throughout the function classes.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+        if (source == null) {
+            return null;
+        }
+
+        if (source instanceof Number) {
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:55]: When can `source` be a `Number`? Shouldn't always be a `String`?
In the function definition you also added the `isStringAndExact` restriction....

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+            return source;
+        }
+
+        if (!(source instanceof String || source instanceof Character)) {
+            throw new EqlIllegalArgumentException("A string/char is required; received [{}]", source);
+        }
+
+        boolean detectedHexPrefix = source.toString().startsWith("0x");
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:63]: What if the source string is `  0x`? (leading whitespaces)
How does the EQL Endpoint work in this case?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+
+        if (base == null) {
+            base = detectedHexPrefix ? 16 : 10;
+        } else if (base instanceof Number == false) {
+            throw new EqlIllegalArgumentException("An integer base is required; received [{}]", source);
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:68]: `instanceof Number` doesn't match the error message, which talks about an `integer`.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+        // custom bases need to use parseInt
+        if (radix != 10) {
+            return Integer.parseInt(source.toString(), radix);
+        }
+
+        // otherwise, we should allow for doubles
+        try {
+            return NumberFormat.getNumberInstance(Locale.US).parse(source.toString());
+        } catch (ParseException e) {
+            throw new EqlIllegalArgumentException("Unable to convert [{}] to number of base [{}]", source, radix);
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:86]: Here I would prefer to see in the error message the original `base`. If that is null because the user didn't provide one, then print `radix`.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+        }
+
+        // custom bases need to use parseInt
+        if (radix != 10) {
+            return Integer.parseInt(source.toString(), radix);
+        }
+
+        // otherwise, we should allow for doubles
+        try {
+            return NumberFormat.getNumberInstance(Locale.US).parse(source.toString());
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:84]: How are the EQL endpoints dealing with locale?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+            return false;
+        }
+
+        ToNumberFunctionProcessor other = (ToNumberFunctionProcessor) obj;
+        return Objects.equals(source(), other.source());
+    }
+
+    @Override
+    public int hashCode() {
+        return Objects.hash(source());
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:111]: `base` missing.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java [hunk 14]
```diff
@@ -0,0 +1,119 @@
...
+        }
+
+    }
+
+    protected Processor source() {
+        return value;
+    }
+
+    @Override
+    public boolean equals(Object obj) {
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:96]: `base` missing.

File: x-pack/plugin/eql/qa/common/src/main/resources/test_queries_unsupported.toml [hunk 15]
```diff
@@ -849,24 +849,8 @@ process where modulo(11, add(serial_event_id, 1)) == serial_event_id'''
 expected_event_ids  = [1, 2, 3, 5, 11]
 description = "test built-in math functions"
 
-[[queries]]
```
Comment (astefan) [inline x-pack/plugin/eql/qa/common/src/main/resources/test_queries_unsupported.toml:852]: Can you add more tests here, please?
The way I see it, there are tests (just one) for no argument `number` function and for base 16. How about base 2, explicit base 10, and custom bases?

**Review by astefan — CHANGES_REQUESTED** [review]
Left a bunch of comments.
I think we need more integration and unit tests to cover all scenarios (see comment for the `toml` file).
Also, `base` argument has been left off in quite few places.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/EqlFunctionRegistry.java (hunk 5 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/EqlFunctionRegistry.java:41]: agreed. @aleksmaus has one in his PR. I wasn't sure if this was math or still string, since it's parsing from strings

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java (hunk 8 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:72]: No idea if it's possible, but I can remove this special run-time only handling

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java (hunk 9 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:80]:
```python
>>> print(eql.parse_expression("number('0x')"))
Traceback (most recent call last):
...
ValueError: invalid literal for int() with base 16: ''
```

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java (hunk 14 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:111]: fixed in 867e122d094da2ba0c68231a352ee225acfc460c

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java (hunk 7 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java]: 86c9949375d04ee8a3f6783995a9f32548baab7d

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java (hunk 6 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java:38]: 867e122d094da2ba0c68231a352ee225acfc460c

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java (hunk 12 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberFunctionProcessor.java]: Removed locale handling in 4b698eb9f9922199069b89168ece053edab8602e.
Now the format is effectively consistent with `[0-9]+(\.[0-9]+)?`

**Review by astefan — COMMENTED** [review]
Looking better.
Added a second round of comments.

File: x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberProcessorTests.java [hunk 16]
```diff
@@ -0,0 +1,157 @@
...
+import static org.elasticsearch.xpack.ql.expression.function.scalar.FunctionTestUtils.l;
+import static org.elasticsearch.xpack.ql.tree.Source.EMPTY;
+
+
+public class ToNumberProcessorTests extends ESTestCase {
+
+    private static Object process(Object value, Object base) {
+        return new ToNumber(EMPTY, l(value), l(base)).makePipe().asProcessor().process(null);
+    }
+
```
[the remark this answers is not in the document]
Comment (rw-access) [reply x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/ToNumberProcessorTests.java:21]: removed in 1b0ac6f4aa3dcfea7e3ebec5d8e1d995e105e931

File: x-pack/plugin/eql/qa/common/src/main/resources/test_queries_unsupported.toml (hunk 15 above)
Comment (rw-access) [reply x-pack/plugin/eql/qa/common/src/main/resources/test_queries_unsupported.toml:852]: Added tests for the processor, and added integration tests here
lob/867fc01a7fc39285c118792283e3457e4e1c85b3/x-pack/plugin/eql/qa/common/src/main/resources/test_queries_supported.toml#L22-L39

File: x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberProcessorTests.java [hunk 17]
```diff
@@ -0,0 +1,155 @@
...
+
+        assertEquals(number, process(Double.toString(number), null));
+        assertEquals(number, process(Double.toString(number), 10));
+    }
+
+    public void toNumberWithMissingInput() {
+        assertNull(process(null, null));
+        assertNull(process(null, 8));
+        assertNull(process(null, 10));
+        assertNull(process(null, 16));
```
Comment (astefan) [inline x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberProcessorTests.java:71]: `assertNull(process(123, null))` is missing.

**Review by astefan — APPROVED** [review]
LGTM. Left two very minor comments though.

File: x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberProcessorTests.java (hunk 17 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/test/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberProcessorTests.java:71]: ah. that's because if the base is null, then the base will be autodetected.
I don't know if there's a way to mention that the parameter was not supplied vs it was evaluated as false. I believe substring() and a few other functions have similar behavior

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumber.java [hunk 18]
```diff
@@ -0,0 +1,116 @@
...
+    protected NodeInfo<? extends Expression> info() {
+        return NodeInfo.create(this, ToNumber::new, value, base);
+    }
+
+    @Override
+    public ScriptTemplate asScript() {
+        ScriptTemplate valueScript = asScript(value);
+        ScriptTemplate baseScript = asScript(base);
+
+        return new ScriptTemplate(format(Locale.ROOT, formatTemplate("{eql}.%s(%s, %s)"),
```
[the remark this answers is not in the document]
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumber.java]: fixed in 2ef2ce45c46c76120f1fa8962f5b590e1a50a7ae

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberFunctionProcessor.java [hunk 19]
```diff
@@ -0,0 +1,118 @@
...
+    }
+
+    @Override
+    public Object process(Object input) {
+        return doProcess(value.process(input), base.process(input));
+    }
+
+    private static Number parseDecimal(String source) {
+        try {
+            return Integer.valueOf(source);
```
Comment (aleksmaus) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberFunctionProcessor.java:45]: just curious, why Integer? should we use Long as a base type? Long.valueOf()?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberFunctionProcessor.java [hunk 20]
```diff
@@ -0,0 +1,118 @@
...
+
+        if (detectedHexPrefix && radix == 16) {
+            value = value.toString().substring(2);
+        }
+
+        try {
+            if (radix == 10) {
+                return parseDecimal(value.toString());
+            } else {
+                return Integer.parseInt(value.toString(), radix);
```
Comment (aleksmaus) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberFunctionProcessor.java:78]: same question here as above about Long vs Integer

**Review by aleksmaus — APPROVED** [review]
Left one question, otherwise LGTM.
Thank you!

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberFunctionProcessor.java (hunk 19 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/math/ToNumberFunctionProcessor.java:45]: thank you! good catch, I'll update this
