### PR TITLE
SQL: fix scripting for grouped by datetime functions

### LINKED ISSUE #40241: SQL: when GROUPed BY, the DAY_NAME function outputs incorrect results
```
sql> SELECT DAY_NAME(birth_date + INTERVAL 1 DAY) FROM test_emp GROUP BY DAY_NAME(birth_date + INTERVAL 1 DAY) LIMIT 5;
DAY_NAME(birth_date + INTERVAL 1 DAY)
-------------------------------------
null
1952-02-28T00:00Z
1952-04-20T00:00Z
1952-05-16T00:00Z
1952-06-14T00:00Z
```

And without being GROUPed BY:

```
sql> SELECT DAY_NAME(birth_date + INTERVAL 1 DAY) FROM test_emp LIMIT 5;
DAY_NAME(birth_date + INTERVAL 1 DAY)                                   
-------------------------------------                                   
Thursday                                                                
Wednesday                                                               
Friday                                                                  
Sunday                                                                  
Saturday                                                                
```

### PR DESCRIPTION
**Pull request by astefan**
This PR fixes a bug in `NamedDateTimeFunction` and `NonIsoDateTimeFunction` based functions as well as `Quarter` function that made the Painless script generated to be incorrect. In case the function was applied on the result of another function (adding an INTERVAL to a field's value for example) the Painless script associated with the datetime function was not applied on the result of the inner function.

Fixes https://github.com/elastic/elasticsearch/issues/40241.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/datetime/NamedDateTimeFunction.java [hunk 1]
```diff
@@ -33,14 +31,16 @@
...
-    public ScriptTemplate scriptWithField(FieldAttribute field) {
-        return new ScriptTemplate(
-                formatTemplate(format(Locale.ROOT, "{sql}.%s(doc[{}].value, {})",
-                        StringUtils.underscoreToLowerCamelCase(nameExtractor.name()))),
-                paramsBuilder()
-                  .variable(field.name())
-                  .variable(zoneId().getId()).build(),
-                dataType());
+    public ScriptTemplate asScript() {
+        ParamsBuilder params = paramsBuilder();
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/datetime/NamedDateTimeFunction.java]: Minor nitpick but you could declare `ParamsBuilder` after the template declaration since it is not used before then.

**Review by costin — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2
