### PR TITLE
Un-mute and fix BuildExamplePluginsIT

### LINKED ISSUE #38784: CI BuildExamplePluginsIT fails
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1977/console

```
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin {p0=/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/plugins/examples/painless-whitelist}
org.elasticsearch.gradle.BuildExamplePluginsIT testCurrentExamplePlugin {p0=/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/plugins/examples/security-authorization-engine}
```

```
* What went wrong:
Could not determine the dependencies of task ':integTestCluster#extract'.
> Could not resolve all files for configuration ':integTestCluster_elasticsearchDistro'.
   > Could not find dnm:elasticsearch-oss:8.0.0-SNAPSHOTwindows-x86_64.
     Searched in the following locations:
       - https://jcenter.bintray.com/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.pom
       - https://jcenter.bintray.com/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.zip
       - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.xml
       - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.zip
       - https://artifacts.elastic.co/maven/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.pom
       - https://artifacts.elastic.co/maven/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.zip
       - http://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/83f9835/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.pom
       - http://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/83f9835/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.zip
       - file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/build/local-test-repo/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.pom
       - file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/build/local-test-repo/dnm/elasticsearch-oss/8.0.0-SNAPSHOTwindows-x86_64/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.zip
       - file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/build/local-downloads/elasticsearch-oss-8.0.0-SNAPSHOTwindows-x86_64.zip
       - file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/build/local-downloads/elasticsearch-oss.zip
     Required by:
         project :
```

and 

```
* What went wrong:
A problem occurred configuring root project 'junit2262156313814203259'.
> Failed to notify project evaluation listener.
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

```

### PR DESCRIPTION
**Pull request by alpar-t**
There doesn't seem to be anything wrong with the test iteself.
I think the failure were CI performance related, but while it was muted,
some failures managed to sneak in.

@jaymode , @tvernum note that this does fix the test, but users will still not be able to run it unless we publish the specific jars to maven central. This is done by the release manager. 
The `apply plugin: "nebula.maven-scm"` causes the POMs to be generated so RM can publish them, but the RM config still needs to be updated. 
This is necessary to make it possible for users to get to all the dependencies of the example plugin, including transitive dependencies. 
The reason this works in the regular build is that all the dependencies are taken from the current build, but the example plugins are also meant to be built outside the build. 

Closes #38784

### CODE REVIEW

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Review by jaymode — APPROVED** [review]

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy [hunk 1]
```diff
@@ -39,6 +39,7 @@ import org.gradle.api.logging.Logger
 import org.gradle.api.tasks.Copy
 import org.gradle.api.tasks.Delete
 import org.gradle.api.tasks.Exec
+import org.gradle.internal.os.OperatingSystem
```
Comment (mark-vieira) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: Looks like this import is unused.

File: libs/ssl-config/build.gradle [hunk 2]
```diff
@@ -16,6 +16,7 @@
  * specific language governing permissions and limitations
  * under the License.
  */
+apply plugin: "nebula.maven-scm"
```
Comment (mark-vieira) [inline libs/ssl-config/build.gradle]: Applying this plugin twice now.

**Review by mark-vieira — CHANGES_REQUESTED** [review]

**Review by mark-vieira — APPROVED** [review]
