### PR TITLE
Do not use runtime Java when starting BWC nodes

### LINKED ISSUE #43024: [CI] openjdk13 full-cluster-restart failures
Builds using openjdk13 fail during full-cluster-restart testing against 7.1.2. I can reproduce this locally using:

```
./gradlew :qa:full-cluster-restart:v7.1.2#oldClusterTestCluster#wait -Druntime.java=13
```

`node0` fails to start using java 13 due to:

```
[2019-06-10T09:53:42,129][ERROR][o.e.b.Bootstrap          ] [node-0] Guice Exception: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPa
ckage.jdk.internal.vm.annotation")
        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:1034)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
        at java.base/java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1324)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:174)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:416)
        at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:440)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:242)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
        at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
        at java.base/java.lang.reflect.Executable.declaredAnnotations(Executable.java:608)
        at java.base/java.lang.reflect.Executable.declaredAnnotations(Executable.java:606)
        at java.base/java.lang.reflect.Executable.getAnnotation(Executable.java:576)
        at java.base/java.lang.reflect.Method.getAnnotation(Method.java:696)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:561)
        at org.elasticsearch.node.Node.<init>(Node.java:252)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        <<<truncated>>>
```

Example failures:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/12/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=immutable&&linux&&docker/12/console

### PR DESCRIPTION
**Pull request by jasontedor**
When starting BWC nodes, it could be that runtime Java home is set. Yet, runtime Java home can advance beyond what a BWC node might be compatible with. For example, if runtime Java home is set to JDK 13 and we are starting a 7.1.2 node, we do not have any guarantees that 7.1.2 is compatible with JDK 13 (since we never did any work to make it so). This will continue to be the case as JDK releases advance, but we still need to test against BWC nodes. This commit stops applying runtime Java home when starting a BWC node. Instead, we would use the bundled JDK.

Closes #43024

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM, but does this need a similar change in testclusters? In `ElasticsearchNode.getESEnvironment()` we similarly pass JAVA_HOME through.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy [hunk 1]
```diff
@@ -107,6 +108,9 @@ class NodeInfo {
     /** the version of elasticsearch that this node runs */
     Version nodeVersion
 
+    /** true if the node is not the current version */
+    boolean isBwcNode
```
Comment (mark-vieira) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/NodeInfo.groovy]: Should probably make this `final`.

**Review by mark-vieira — COMMENTED** [review]
Ditto on @rjernst's comment about updating `ElasticsearchNode` as well for projects using `TestClustersPlugin`.

**Comment by atorok** [comment]
We don't use testclusters for BWC yet, so we are fine on that front. 

I just want to point out that we are somewhat reducing coverage by this change. In our java matrix testing in CI we cycle trough all meaningful runtime java versions. Before this change we would test with the BWC version running on each, which is problematic as you point out that it could be that we add one for the newer version that is  not supported by the old version, but we would circle trough all those that we do support. With this change we would only ever use the embedded JDK.  Runtime java is always set in CI ( we have #40531 to address that )  so without this change we didn't cover running bwc with the embedded JDK.

To be able to reason about the version of the JDK used here we would need to embed information in the distribution about what it supports, since I don't think we have access to that information in cluster formation tasks right now. With this metadata we could still use runtime java if it's set to something that the bwc version supports. 

I'm not arguing we should do it, I'm not convinced either, just wanted to point it out. 
On one hand, using the same runtime java is more realistic for a BWC scenario ( users will probably not upgrade java and elasticsearch at the exact same time ) but on the other hand both the old and the new versions are independently tested against all the java versions they support, so running into something that is java dependent and only manifests in a bwc test seems unlikely.  On the other hand there's not much additional CI cost to cover it ( but there will be once we do #40531 to cover the embedded java explicitly ).

**Comment by jasontedor** [comment]
> I just want to point out that we are somewhat reducing coverage by this change.

I am okay with this, as you mention below, we test each version against all the versions that it supports. The BWC tests are to give us confidence that our supported upgrade paths are successful, the likelihood of an issue arising in a BWC scenario that doesn't arise in the runtime matrix tests for the version being upgraded from is extremely unlikely. We will never have 100% coverage, our goal is reasonably high confidence, and I think we have that even without sweeping over every runtime Java for the BWC versions.

> On one hand, using the same runtime java is more realistic for a BWC scenario ( users will probably not upgrade java and elasticsearch at the exact same time ) but on the other hand both the old and the new versions are independently tested against all the java versions they support, so running into something that is java dependent and only manifests in a bwc test seems unlikely.

We are in agreement, see above, that's why I am not worried about the loss of coverage here. To add, it's our expectation that over time users would be using the bundled JDK anyway (they certainly are in the Docker images).
