### PR TITLE
Relax the assertion in testRequestResetAndAbort

### LINKED ISSUE #59678: RestClientSingleHostIntegTests.testRequestResetAndAbort fails in 7.x cancelling request
**Build scan**:
https://gradle-enterprise.elastic.co/s/ujpqnv5kcwnj4

**Repro line**:
What's strange is that there *is no reproduction line*.

**Reproduces locally?**:
No, because there's no reproduction line

**Applicable branches**:
7.x

**Failure history**:
Only one failure recently: https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.client.RestClientSingleHostIntegTests&tests.sortField=FAILED&tests.test=testRequestResetAndAbort&tests.unstableOnly=true

**Failure excerpt**:
```
Suite: Test class org.elasticsearch.client.RestClientSingleHostIntegTests
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([1590BDDE62D15D51:21DEFA66B0D9B281]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.elasticsearch.client.RestClientSingleHostIntegTests.testRequestResetAndAbort(RestClientSingleHostIntegTests.java:295)
```

Which seems to be failing on:

```java
            {
                httpGet.reset();
                Future<HttpResponse> future = client.execute(httpHost, httpGet, null);
                assertFalse(httpGet.isAborted());
                httpGet.abort();
                assertTrue(httpGet.isAborted());
                try {
                    assertTrue(future.isCancelled()); // <---- here
                    future.get();
                    throw new AssertionError("exception should have been thrown");
                } catch(CancellationException e) {
                    //expected
                }
            }

```

### PR DESCRIPTION
**Pull request by andreidan**
This relaxes the assertion to account for the case when the client
executes the request successfully before we cancel the underlying http
request.

Fix #59678

### CODE REVIEW

File: client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java [hunk 1]
```diff
@@ -295,11 +295,10 @@ public void testRequestResetAndAbort() throws Exception {
                 httpGet.abort();
                 assertTrue(httpGet.isAborted());
                 try {
-                    assertTrue(future.isCancelled());
+                    assertTrue(future.isDone());
                     future.get();
-                    throw new AssertionError("exception should have been thrown");
                 } catch(CancellationException e) {
-                    //expected
+                    //expected sometimes - if the future was cancelled before executing successfully
```
Comment (javanna) [inline client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java:301]: I tried to refresh my memory around this, and I am not sure what the best course of action is, but with this change I am no longer sure what this test is testing, because the future may be cancelled or not. I do see a problem with how the test was written and I am curious about why it took so long for this issue to surface: your explanation is evident, the request may be already completed because it gets cancelled.

Speculating, but this could also very well be a regression in the http client we use, as the future no longer gets cancelled, and if we relax the assertion the assumptions we rely upon no longer hold? 

I don't have great ideas about a solution, but these are my thoughts.

Comment (andreidan) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java:301]: Thanks for the details Luca. It took me a while to parse what the test was aiming to achieve too :) 

> I am no longer sure what this test is testing, because the future may be cancelled or not

That's a good point. I'd say this change makes sure the future completes successfully or cancelled, but I appreciate it might not be very useful (?) 

> if we relax the assertion the assumptions we rely upon no longer hold?

I think the test case is a bit overzealous though. I guess if the apache hhtp library breaks the invariant of the underlying future not being cancelled when the HTTP request is cancelled the above test case would catch it? Namely https://github.com/elastic/elasticsearch/pull/70308/files#diff-75a96c857e80e8d97c55e23176edffb572fa82587d5051907575e87798965e11R281-R288

The possibly flaky assertion I changed is testing a concurrency cancellation that IMO would even be hard for a user to verify - what is a correct behaviour? that the request was let to execute all the way or that it was absolutely always cancelled? (I'd argue that this actually depends on the request, when in the lifecycle of the request/response cycle the cancellation hits the client and the behaviour would be different in case of a long poll request for eg)

I don't have a strong opinion here, I'm happy to drop the test case altogether if you think that's better?

Comment (andreidan) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java:301]: @javanna sorry, I realised I was a bit dense before. What I meant was that given a user (or external observer) can't deterministically determine what a successful output is when an in progress request is cancelled (which are all the cases in a real life scenario) I think the only desireable and deterministically observable behaviour is that the request is not hanging - ie. the future is done/complete. 

So thinking about it some more, I think the modified assertion makes sense.

What do you think?

Comment (javanna) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java:301]: Yes I think you are right. I was referring to the javadocs that I wrote, which is though not enough for me to remember exactly what I was worried about when I wrote this test :) I remember looking at the code of the async http client and being worried about the fact that the low level rest client reuses the same request object throughout multiple retries. We trust that the client sets the future reference correctly to the request object, so that the right future gets cancelled when the request gets aborted. I may have been overly paranoid here and wrote a test to test async http client behaviour more than that of our own client. I am happy with your recommendation, thanks for looking into this.

**Review by javanna — APPROVED** [review]

**Comment by andreidan** [comment]
@elasticmachine update branch
