### PR TITLE
Avoid stack overflow in auto-follow coordinator

### LINKED ISSUE #43251: Possible stack overflow in failure scenerio in Cross Cluster Replication
While investigating an issue with CCR where both the leader and follower were overwhelmed. (especially the follower with long GC's, nodes dropping from cluster, etc.)  A stack overflow exception was logged. The full exception is [here](https://gist.github.com/jakelandis/9ef72d6bff8a7e3d33922a9cde0c4063) (it is too long to include as part of the issue)...here are the highlights:

```
[2019-05-13T09:07:53,843][WARN ][o.e.x.c.a.AutoFollowCoordinator] [hostname.was.here] failure occurred while fetching cluster state for auto follow pattern [follow-pattern-was-here]
org.elasticsearch.ElasticsearchStatusException: can not fetch remote cluster state as the license state of the remote cluster [remote-cluster-name-was-here] could not be determined
...
Caused by: org.elasticsearch.ElasticsearchException: could not determine the license type for cluster [cluster-name-was-here]
...
Caused by: java.util.concurrent.RejectedExecutionException: connect queue is full
```
Digging through the possible culprits, it appears to be looping on : 
```
    at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:389) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:583) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:416) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:229) ~[?:?]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker$1.onFailure(CcrLicenseChecker.java:232) ~[?:?]
	at org.elasticsearch.license.RemoteClusterLicenseChecker$1.onFailure(RemoteClusterLicenseChecker.java:188) ~[?:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:69) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.connect(RemoteClusterConnection.java:424) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.connect(RemoteClusterConnection.java:406) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterConnection.ensureConnected(RemoteClusterConnection.java:213) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterService.ensureConnected(RemoteClusterService.java:392) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterAwareClient.doExecute(RemoteClusterAwareClient.java:50) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.license.RemoteClusterLicenseChecker.remoteClusterLicense(RemoteClusterLicenseChecker.java:209) ~[?:?]
	at org.elasticsearch.license.RemoteClusterLicenseChecker.checkRemoteClusterLicenses(RemoteClusterLicenseChecker.java:195) ~[?:?]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:214) ~[?:?]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:173) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:225) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:389) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:583) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:416) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:229) ~[?:?]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker$1.onFailure(CcrLicenseChecker.java:232) ~[?:?]
	at org.elasticsearch.license.RemoteClusterLicenseChecker$1.onFailure(RemoteClusterLicenseChecker.java:188) ~[?:?]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:69) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.connect(RemoteClusterConnection.java:424) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.connect(RemoteClusterConnection.java:406) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterConnection.ensureConnected(RemoteClusterConnection.java:213) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterService.ensureConnected(RemoteClusterService.java:392) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.transport.RemoteClusterAwareClient.doExecute(RemoteClusterAwareClient.java:50) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) ~[elasticsearch-6.7.1.jar:6.7.1]
	at org.elasticsearch.license.RemoteClusterLicenseChecker.remoteClusterLicense(RemoteClusterLicenseChecker.java:209) ~[?:?]
	at org.elasticsearch.license.RemoteClusterLicenseChecker.checkRemoteClusterLicenses(RemoteClusterLicenseChecker.java:195) ~[?:?]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:214) ~[?:?]
	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:173) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:225) ~[?:?]
	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:389) ~[?:?]
```

While I can't get this to reproduce in an integration test, i can get the start-> finalize -> start to loop via a unit test by ensuring that cluster state does not change between the start -> finalize -> start loop. Since it is a unit test, and there is quite abit of test level manipulation (e.g. no real handlers are called), I am not fully confident this reproduction is a legitimate reproduction of the actual issue.   

To reproduce: change `org.elasticsearch.xpack.ccr.action.AutoFollowCoordinatorTests#testAutoFollowerClusterStateApiFailure` to use a cluster state applier that does not remove the AutoFollowMetadata from the cluster state. 
```
diff --git a/x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java b/x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java
index 7648d10aa09..12853696a28 100644
--- a/x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java
+++ b/x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java
@@ -157,7 +157,7 @@ public class AutoFollowCoordinatorTests extends ESTestCase {
             assertThat(results.get(0).clusterStateFetchException, sameInstance(failure));
             assertThat(results.get(0).autoFollowExecutionResults.entrySet().size(), equalTo(0));
         };
-        AutoFollower autoFollower = new AutoFollower("remote", handler, localClusterStateSupplier(clusterState), () -> 1L) {
+        AutoFollower autoFollower = new AutoFollower("remote", handler, () -> clusterState, () -> 1L) {
             @Override
             void getRemoteClusterState(String remoteCluster,
                                        long metadataVersion,
```

I think I will need someone with knowledge of CCR internals to help take a look.

Full stack here: https://gist.github.com/jakelandis/9ef72d6bff8a7e3d33922a9cde0c4063

### PR DESCRIPTION
**Pull request by jasontedor**
This commit avoids a situation where we might stack overflow in the auto-follower coordinator. In the face of repeated failures to get the remote cluster state, we would previously be called back on the same thread and then recurse to try again. If this failure persists, the repeated callbacks on the same thread would lead to a stack overflow. The repeated failures can occur, for example, if the connect queue is full when we attempt to make a connection to the remote cluster. This commit avoids this by truncating the call stack if we are called back on the same thread as the initial request was made on.

Closes #43251

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch/ci-1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/2

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 1]
```diff
@@ -344,11 +349,13 @@ public void clusterChanged(ClusterChangedEvent event) {
...
+                     final LongSupplier relativeTimeProvider,
+                     final Executor executor) {
             this.remoteCluster = remoteCluster;
             this.statsUpdater = statsUpdater;
             this.followerClusterStateSupplier = followerClusterStateSupplier;
             this.relativeTimeProvider = relativeTimeProvider;
+            this.executor = Objects.requireNonNull(executor);
         }
 
         void start() {
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: Can we assert that method `start` is never called recursively (using `ThreadPool.assertCurrentMethodIsNotCalledRecursively`)?

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 2]
```diff
@@ -561,11 +570,23 @@ private void followLeaderIndex(String autoFollowPattenName,
...
+                 * In the face of a failure, we could be called back on the same thread. That is, it could be that we
+                 * never fired off the asynchronous remote cluster state call, instead failing beforehand. In this case,
+                 * we will recurse on the same thread. If there are repeated failures, we could blow the stack and
+                 * overflow. A real-world scenario in which this can occur is if the local connect queue is full. To
+                 * avoid this, if we are called back on the same thread, then we truncate the stack by forking to
+                 * another thread.
+                 */
+                if (thread == Thread.currentThread()) {
+                    executor.execute(this::start);
+                    return;
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: I think `if else` is easier to understand than `return` here.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 3]
```diff
@@ -403,7 +411,7 @@ void start() {
                     }
                     ClusterState remoteClusterState = remoteClusterStateResponse.getState();
                     metadataVersion = remoteClusterState.metaData().version();
-                    autoFollowIndices(autoFollowMetadata, clusterState, remoteClusterState, patterns);
+                    autoFollowIndices(autoFollowMetadata, clusterState, remoteClusterState, patterns, thread);
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: Do we need to handle the timeout case (line 409)? I know it always comes from a different thread.

**Review by dnhatn — APPROVED** [review]
LGTM. I left some optional comments. Thanks @jasontedor.

**Review by jakelandis — APPROVED** [review]

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java (hunk 1 above)
Comment (jasontedor) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: This can't be done without some refactoring since tests use `Runnable::run` as the executor, which would of course execute on the same thread (recursively).

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java (hunk 3 above)
Comment (jasontedor) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: I don't think so because as you say, we are always on a callback thread with an already-truncated stack trace in that case.
