### PR TITLE
Fix RareClusterStateIT Publication Cancel

### LINKED ISSUE #62446: [CI] RareClusterStateIT.testDelayedMappingPropagationOnReplica fails on 7.x
**Build scan**:
https://gradle-enterprise.elastic.co/s/tds3nk2ykh2yc

**Repro line**:

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.coordination.RareClusterStateIT.testDelayedMappingPropagationOnReplica" \
  -Dtests.seed=1AE8DAD4C04E8D0D \
  -Dtests.security.manager=true \
  -Dtests.locale=nl-NL \
  -Dtests.timezone=Australia/Victoria \
  -Druntime.java=11

**Reproduces locally?**:

No

**Applicable branches**:
7.x

**Failure history**:

Another recent fairly similar looking failure on master: https://gradle-enterprise.elastic.co/s/b5y6he5hgc6ag (Aug 31th)

**Failure excerpt**:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([1AE8DAD4C04E8D0D:66961B1B90A9B6EE]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.elasticsearch.cluster.coordination.RareClusterStateIT.testDelayedMappingPropagationOnReplica(RareClusterStateIT.java:377)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
We have to make sure the applier and not the accept state versions allign here.
Otherwise we can get into the situation where the data node is so slow to process
one version that the next one arrives, gets rejected and the request return with
ack `false` and we fail the assertion that the put mapping request didn't complete.

Closes #62446

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/RareClusterStateIT.java [hunk 1]
```diff
@@ -142,17 +140,16 @@ public void onFailure(String source, Exception e) {
...
-            () -> {
-                assertFalse(((Coordinator) internalCluster().getCurrentMasterNodeInstance(Discovery.class)).publicationInProgress());
-                assertThat(StreamSupport.stream(
-                    internalCluster().getInstances(Discovery.class).spliterator(), false)
-                    .map(coordinator -> ((Coordinator) coordinator).getLastAcceptedState().version())
-                    .distinct().toArray(), arrayWithSize(1));
-            });
+        final Coordinator masterCoordinator = (Coordinator) internalCluster().getCurrentMasterNodeInstance(Discovery.class);
+        assertBusy(() -> {
+            assertFalse(masterCoordinator.publicationInProgress());
```
Comment (original-brownbear) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/RareClusterStateIT.java:145]: Made this whole thing a little less weird to read as well here, the stream + iterator + array size assertion was just weirdly complicated.

**Review by henningandersen — APPROVED** [review]
LGTM, thanks for the additional explanations elsewhere, @original-brownbear .

**Comment by original-brownbear** [comment]
Thanks Henning!
