### PR TITLE
Making sure that watcher-history index is green in HistoryIntegrationTests

### LINKED ISSUE #110885: [CI] HistoryIntegrationTests testPayloadInputWithDotsInFieldNameWorks failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/e3qdnup7y5say/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests/testPayloadInputWithDotsInFieldNameWorks

**Reproduction line:**
```
./gradlew ":x-pack:plugin:watcher:internalClusterTest" --tests "org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests.testPayloadInputWithDotsInFieldNameWorks" -Dtests.seed=F934C0DCCD1128EC -Dtests.locale=und -Dtests.timezone=Pacific/Kanton -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests#testPayloadInputWithDotsInFieldNameWorks`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testPayloadInputWithDotsInFieldNameWorks'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed

  at __randomizedtesting.SeedInfo.seed([F934C0DCCD1128EC:A5592375180E9950]:0)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:724)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:416)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:756)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:509)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.performPhaseOnShard(AbstractSearchAsyncAction.java:314)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.run(AbstractSearchAsyncAction.java:250)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:466)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:225)
  at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:1213)
  at org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:961)
  at org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$5(TransportSearchAction.java:379)
  at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
  at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:109)
  at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
  at org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:491)
  at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:335)
  at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:115)
  at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:96)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:68)
  at org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:196)
  at org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:105)
  at org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:83)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:138)
  at org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:55)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:138)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:124)
  at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:36)
  at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:43)
  at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:16)
  at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertResponse(ElasticsearchAssertions.java:379)
  at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:301)
  at org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests.lambda$testPayloadInputWithDotsInFieldNameWorks$2(HistoryIntegrationTests.java:154)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1384)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1369)
  at org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests.testPayloadInputWithDotsInFieldNameWorks(HistoryIntegrationTests.java:152)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

  Caused by: org.elasticsearch.action.NoShardAvailableActionException: (No message provided)


```

### PR DESCRIPTION
**Pull request by masseyke**
Since the .watcher-history index is written asynchronously, it is possible that this test can query it when it is not yet ready. This adds a call to ensureGreen() before doing a search request so that we don't run into a NoShardAvailableActionException. This change also moves all of the search requests into a shared method so that we can more easily modify this behavior in the future if we need to.
Closes #110885
Relates #98014

### CODE REVIEW

File: x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/HistoryIntegrationTests.java [hunk 1]
```diff
@@ -104,10 +103,7 @@ public void testFailedInputResultWithDotsInFieldNameGetsStored() throws Exceptio
 
         new ExecuteWatchRequestBuilder(client()).setId("test_watch").setRecordExecution(true).get();
 
-        assertBusy(() -> {
-            refresh(".watcher-history*");
-            assertHitCount(prepareSearch(".watcher-history*").setSize(0), 1);
```
Comment (joegallo) [inline x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/HistoryIntegrationTests.java:109]: `.setSize(...)` drops out here (and a few other places) -- is that okay?

Comment (masseyke) [reply x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/HistoryIntegrationTests.java:109]: Some places only needed the count (so size=0 was fine), and some wanted the single record (so size=1 was fine). Since we always expect either 0 or 1 documents in this index it didn't seem to cause any problems to just use the default size. Worst case, we pull back a single history document that we don't care about that gets immediately garbage collected. It avoided passing an argument into this method that might just add confusion.

**Review by joegallo — APPROVED** [review]
