### PR TITLE
[Transform] refactor source and dest validation to support CCS

### LINKED ISSUE #49851: [Transform] Handle index patterns in the same way as search and reindex
Transform validation fails if no index gets expanded:

```
"source": {
    "index": "xyz*"
  },
```

This gives an error if no index exists with the prefix `xyz` which is different to search and reindex which are lenient for index patterns.

Transform should be lenient, too.

### LINKED ISSUE #49988: Allow transforms destination index to be an alias with multiple backing indices
Transforms should allow a destination index that refers to an alias as long as that alias as a single writing writing index specified. 

```
DELETE idx*

PUT idx_1
PUT idx_2

POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "idx_1",
        "alias": "idx"
      }
    },
    {
      "add": {
        "index": "idx_2",
        "alias": "idx",
        "is_write_index": true
      }
    }
  ]
}

# below works
PUT idx/_doc/to_alias
{
  "a": "a"
}

GET idx/_search
```
Transform creation currently fails:
```
PUT _transform/trans_idx
{
  "source": {
    "index": [
      "source-*"
    ]
  },
  "pivot": {
    "group_by": {
      "field": {
        "terms": {
          "field": "my_field"
        }
      }
    },
    "aggregations": {
      "@timestamp.max": {
        "max": {
          "field": "@timestamp"
        }
      }
    }
  },
  "dest": {
    "index": "idx"
  }
}
```

Failure:
```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Destination index [idx] should refer to a single index"
      }
    ],
    "type": "status_exception",
    "reason": "Destination index [idx] should refer to a single index"
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
refactors source and dest validation, adds support for CCS, makes resolve work like reindex/search, allow aliased dest index with a single write index.

fixes #49988 
fixes #49851
relates #43201

Notes: `SourceDestValidator` is now de-coupled from transform, I moved it into x-pack core for re-usage (e.g. df analytics)

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 1]
```diff
@@ -0,0 +1,513 @@
...
+    static class SourceMissingValidation implements SourceDestValidation {
+
+        @Override
+        public boolean isDeferrable() {
+            return true;
+        }
+
+        @Override
+        public void validate(Context context) {
+            // boolean remoteIndexesEmpty = context.isRemoteSearchEnabled() ? context.resolveRemoteSource().isEmpty() : true;
```
Comment (davidkyle) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: remove commented out code

**Review by davidkyle — COMMENTED** [review]
Looks good, left some very minor comments

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 2]
```diff
@@ -0,0 +1,513 @@
...
+        Context(
+            final ClusterState state,
+            final IndexNameExpressionResolver indexNameExpressionResolver,
+            final RemoteClusterService remoteClusterService,
+            final RemoteClusterLicenseChecker remoteClusterLicenseChecker,
+            final String[] source,
+            final String dest,
+            final String nodeName,
+            final String license
+        ) {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: There is a number of lines in this PR where the closing parenthesis is in a new line.

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: This is the new spotless enforce format...I personally don't like it at all :/

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 3]
```diff
@@ -0,0 +1,513 @@
...
+                        state,
+                        IndicesOptions.lenientExpandOpen(),
+                        dest,
+                        true
+                    );
+                    if (singleWriteIndex != null) {
+                        resolvedDest = singleWriteIndex.getName();
+                    } else {
+                        resolvedDest = dest;
+                    }
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: `return singleWriteIndex != null ? singleWriteIndex.getName() : dest`

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 4]
```diff
@@ -0,0 +1,513 @@
...
+                } catch (IllegalArgumentException e) {
+                    // stop here as we can not return a single dest index
+                    addValidationError(e.getMessage(), false);
+                }
+            }
+
+            return resolvedDest;
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: I think this outside return could be removed instead of mutating in the `try..` block

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 5]
```diff
@@ -0,0 +1,513 @@
...
+
+        @Override
+        public void validate(Context context) {
+            if (context.resolveRemoteSource().isEmpty()) {
+                return;
+            }
+
+            List<String> remoteIndices = new ArrayList<>(context.resolveRemoteSource());
+            // we can only check this node at the moment, clusters with mixed CCS enabled/disabled nodes are not supported,
+            // see gh#50033
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: NOTE (not for this PR): I think we should still do this validation in the executor (remote search + license check). Should be possible

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 6]
```diff
@@ -0,0 +1,513 @@
...
+                remoteAliases = RemoteClusterLicenseChecker.remoteClusterAliases(context.getRegisteredRemoteClusterNames(), remoteIndices);
+            } catch (NoSuchRemoteClusterException e) {
+                context.addValidationError(e.getMessage(), true);
+                return;
+            } catch (Exception e) {
+                context.addValidationError(ERROR_REMOTE_CLUSTER_SEARCH, true, e.getMessage());
+                return;
+            }
+
+            CountDownLatch latch = new CountDownLatch(1);
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: We shouldn't do this. This could be executing on a network thread (i.e. from a transport class).

I think a listener should be passed into the class. Possibly only if remote cluster checks are necessary? Or probably always for simplicity's sake.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 7]
```diff
@@ -0,0 +1,513 @@
...
+    public static ValidationException validate(
+        ClusterState clusterState,
+        IndexNameExpressionResolver indexNameExpressionResolver,
+        RemoteClusterService remoteClusterService,
+        RemoteClusterLicenseChecker remoteClusterLicenseChecker,
+        String[] source,
+        String dest,
+        String nodeName,
+        String license,
+        boolean shouldDefer
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: I think it would be nice to pass in what validations the user wants to run. We could have all the available validations as public static values and then they pass in a variadic list of ValidationClasses or something.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 8]
```diff
@@ -0,0 +1,513 @@
...
+    ) {
+        Context context = new Context(
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: Having a centralized state object that is this complex smells like we should probably have a class + builder that gets passed through. 

Or possibly a `Validator` class that holds all state and has a `validate(ActionListener<ValidationError>)`. This would kill two birds with one stone:
* Simplifying the interface a bit
* Passing a listener that gets called for the remove cluster validation.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 9]
```diff
@@ -0,0 +1,513 @@
...
+     * @param indexNameExpressionResolver A valid IndexNameExpressionResolver object
+     * @param remoteClusterService A valid RemoteClusterService object
+     * @param remoteClusterLicenseChecker A RemoteClusterLicenseChecker or null if CCS is disabled
+     * @param source an array of source indices
+     * @param dest destination index
+     * @param nodeName the name of this node
+     * @param license the license of the feature validated for
+     * @return ValidationException instance containing all validation errors or null if validation found no problems.
+     */
+    public static ValidationException validateForPreview(
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: As discussed, this seems like we should not have this and have the method caller pass in their desired validations.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 10]
```diff
@@ -0,0 +1,513 @@
...
+            nodeName,
+            license
+        );
+
+        // validation exception might gets thrown if validation stops early
+        try {
+            for (SourceDestValidation validation : PREVIEW_VALIDATIONS) {
+                validation.validate(context);
+            }
+        } catch (ValidationException e) {}
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: I don't think anything throws this? If something does, we should not `> /dev/null` this. Add it to the overall validation error collection.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 11]
```diff
@@ -0,0 +1,513 @@
...
+        // validation exception might gets thrown if validation stops early
+        try {
+            for (SourceDestValidation validation : START_AND_PUT_VALIDATIONS) {
+                if (shouldDefer && validation.isDeferrable()) {
+                    continue;
+                }
+                validation.validate(context);
+            }
+
+        } catch (ValidationException e) {}
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: I don't think anything throws this? If something does, we should not `> /dev/null` this. Add it to the overall validation error collection.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 12]
```diff
@@ -0,0 +1,513 @@
...
+            }
+
+            if (context.resolvedSource.contains(context.resolveDest())) {
+                context.addValidationError(
+                    DEST_IN_SOURCE,
+                    true,
+                    context.resolveDest(),
+                    Strings.collectionToCommaDelimitedString(context.resolveSource())
+                );
+                return;
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]:
```suggestion
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java [hunk 13]
```diff
@@ -0,0 +1,513 @@
...
+            }
+        }
+    }
+
+    static class DestinationSingleIndexValidation implements SourceDestValidation {
+
+        @Override
+        public boolean isDeferrable() {
+            return false;
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: If callers can pass in their desired validations at call time, the idea of `isDeferrable` is no longer necessary.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPreviewTransformAction.java [hunk 14]
```diff
@@ -101,120 +129,122 @@ protected void doExecute(Task task,
...
-            }
+        ValidationException validationResult = SourceDestValidator.validateForPreview(
+            clusterState,
+            indexNameExpressionResolver,
+            this.transportService.getRemoteClusterService(),
+            isRemoteSearchEnabled ? new RemoteClusterLicenseChecker(client, XPackLicenseState::isTransformAllowedForOperationMode) : null,
+            config.getSource().getIndex(),
+            config.getDestination().getIndex(),
+            clusterService.getNodeName(),
+            "basic"
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPreviewTransformAction.java]:
```suggestion
            License.OperationMode.BASIC.description()
```
We should use the operation mode enum.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPutTransformAction.java [hunk 15]
```diff
@@ -208,10 +213,20 @@ protected void masterOperation(Task task, Request request, ClusterState clusterS
...
+
+        ValidationException validationResult = SourceDestValidator.validate(
+            clusterState,
+            indexNameExpressionResolver,
+            transportService.getRemoteClusterService(),
+            isRemoteSearchEnabled ? new RemoteClusterLicenseChecker(client, XPackLicenseState::isTransformAllowedForOperationMode) : null,
+            config.getSource().getIndex(),
+            config.getDestination().getIndex(),
+            clusterService.getNodeName(),
+            "basic",
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPutTransformAction.java]:
```suggestion
            License.OperationMode.BASIC.description()
```
We should use the operation mode enum.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStartTransformAction.java [hunk 16]
```diff
@@ -205,7 +214,24 @@ protected void masterOperation(
...
+                clusterService.state(),
+                indexNameExpressionResolver,
+                transportService.getRemoteClusterService(),
+                isRemoteSearchEnabled
+                    ? new RemoteClusterLicenseChecker(client, XPackLicenseState::isTransformAllowedForOperationMode)
+                    : null,
+                config.getSource().getIndex(),
+                config.getDestination().getIndex(),
+                clusterService.getNodeName(),
+                "basic",
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportStartTransformAction.java]:
```suggestion
            License.OperationMode.BASIC.description()
```
We should use the operation mode enum.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpdateTransformAction.java [hunk 17]
```diff
@@ -204,10 +209,20 @@ private void validateAndUpdateTransform(
...
-            listener.onFailure(ex);
+        ValidationException validationResult = SourceDestValidator.validate(
+            clusterState,
+            indexNameExpressionResolver,
+            transportService.getRemoteClusterService(),
+            isRemoteSearchEnabled ? new RemoteClusterLicenseChecker(client, XPackLicenseState::isTransformAllowedForOperationMode) : null,
+            config.getSource().getIndex(),
+            config.getDestination().getIndex(),
+            clusterService.getNodeName(),
+            "basic",
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportUpdateTransformAction.java]:
```suggestion
            License.OperationMode.BASIC.description()
```
We should use the operation mode enum.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java (hunk 4 above)
Comment (hendrikmuhs) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: `resolveDest` can be called repeatedly (by different validators) and resolves the source on the 1st call on-demand.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java (hunk 5 above)
Comment (hendrikmuhs) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/common/validation/SourceDestValidator.java]: #50033 has some analysis of this problem, it requires some work to get this working.

Note that we do validation at the start of the task, however the problem is `cluster.remote` being a node setting which you can not get via cluster state. #50033 has the details, if you have ideas/comments please put it there.

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
@dimitris-athanasiou @davidkyle @benwtrent 

I did the changes we discussed.

**Review by benwtrent — APPROVED** [review]

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2
