### PR TITLE
AsyncTwoPhaseIndexerTests race condition fixed

### LINKED ISSUE #37695: [CI] AsyncTwoPhaseIndexerTests.testStateMachine failure
Looks like a transient failure due to a slow start that could be fixed through a barrier

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/365/console 
```
Expected: <INDEXING>
     but: was <STARTED>
	at __randomizedtesting.SeedInfo.seed([FF9B9C9FA14FF48D:9332E084D9C2EAE3]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine(AsyncTwoPhaseIndexerTests.java:204)
```

### PR DESCRIPTION
**Pull request by pgomulka**
The unlucky timing can cause this test to fail when the indexing triggered from `maybeTriggerAsyncJob`. As this is asynchronous, in can finish quicker then the test stepping over to next assertion
The introduced barrier solves the problem
closes #37695

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexerTests.java [hunk 1]
```diff
@@ -196,12 +208,15 @@ public void testStateMachine() throws InterruptedException {
...
         isFinished.set(false);
         try {
-
-            MockIndexer indexer = new MockIndexer(executor, state, 2);
+            CountDownLatch countDownLatch = new CountDownLatch(1);
+            MockIndexer indexer = new MockIndexer(executor, state, 2, countDownLatch);
             indexer.start();
             assertThat(indexer.getState(), equalTo(IndexerState.STARTED));
             assertTrue(indexer.maybeTriggerAsyncJob(System.currentTimeMillis()));
+            Thread.sleep(1000);
```
Comment (pgomulka) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexerTests.java]: to be removed

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexerTests.java [hunk 2]
```diff
@@ -49,11 +53,20 @@ protected String getJobId() {
...
         protected IterationResult<Integer> doProcess(SearchResponse searchResponse) {
+            awaitForLatch();
             assertThat(step, equalTo(3));
             ++step;
             return new IterationResult<Integer>(Collections.emptyList(), 3, true);
         }
 
+        private void awaitForLatch() {
+            try {
+                latch.await();
```
Comment (costin) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexerTests.java]: Please put a timeout (10s or whatever you think it's appropriate) to prevent this for hanging up.

**Review by costin — APPROVED** [review]
LGTM

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/1
