### PR TITLE
[Test] Fix S3BlobStoreRepositoryTimeoutTests testWriteTimeout

### LINKED ISSUE #139041: [CI] S3BlobStoreRepositoryTimeoutTests testWriteTimeout failing
**Build Scans:**
- [elasticsearch-intake #31978 / part1](https://gradle-enterprise.elastic.co/s/fztoydzwyhi3u)
- [elasticsearch-pull-request #107810 / part-1](https://gradle-enterprise.elastic.co/s/e4tiupezwihu4)
- [elasticsearch-pull-request #107806 / part-1](https://gradle-enterprise.elastic.co/s/mvftovicqtsac)

**Reproduction Line:**
```
./gradlew ":modules:repository-s3:internalClusterTest" --tests "org.elasticsearch.repositories.s3.S3BlobStoreRepositoryTimeoutTests.testWriteTimeout" -Dtests.seed=35B4378561690D1C -Dtests.locale=yi -Dtests.timezone=Pacific/Marquesas -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.s3.S3BlobStoreRepositoryTimeoutTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testWriteTimeout'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: index-afectcqlplfp should not use purpose SNAPSHOT_DATA
```

**Issue Reasons:**
- [main] 3 failures in test testWriteTimeout (27.3% fail rate in 11 executions)
- [main] 2 failures in step part-1 (25.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Prefix blob name with `test-` so that it does not trip consistency check for operation purpose.

Resolves: #139041

### CODE REVIEW

File: modules/repository-s3/src/internalClusterTest/java/org/elasticsearch/repositories/s3/S3BlobStoreRepositoryTimeoutTests.java [hunk 1]
```diff
@@ -129,11 +130,13 @@ public void testWriteTimeout() {
         s3StallingHttpHandler.setStallLatchRef(latch);
         try {
             final var purpose = randomFrom(OperationPurpose.values());
+            final String blobName = "test-" + randomIdentifier();
```
Comment (joshua-adams-1) [inline modules/repository-s3/src/internalClusterTest/java/org/elasticsearch/repositories/s3/S3BlobStoreRepositoryTimeoutTests.java:133]: Why does prefixing with `index` not work here but `test` does?

Comment (ywangd) [reply modules/repository-s3/src/internalClusterTest/java/org/elasticsearch/repositories/s3/S3BlobStoreRepositoryTimeoutTests.java:133]: BlobContainer has a [consistency check](https://github.com/elastic/elasticsearch/blob/b344a152e411c33185ccd1bfdca0d752918537a3/server/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java#L390) between operation purpose and the blob name's prefix. It does not like things like `index-xxx` being handled with the `SNAPSHOT_DATA` operation purpose.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Review by joshua-adams-1 — APPROVED** [review]
LGTM!
