### PR TITLE
Aggs: Fix Filters agg cancellation flaky test

### LINKED ISSUE #130770: [CI] FiltersCancellationIT testFiltersSubAggsCancellation failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9255 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/wrqmjkr2q5tv2)
- [elasticsearch-periodic-platform-support #9227 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/lnzqxbgk5pjyi)
- [elasticsearch-periodic-platform-support #9227 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/bc573kel6n2ae)

**Reproduction Line:**
```
gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.aggregations.bucket.FiltersCancellationIT.testFiltersSubAggsCancellation" -Dtests.seed=E591B05A93049B8B -Dtests.locale=fr-TG -Dtests.timezone=US/Eastern -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.aggregations.bucket.FiltersCancellationIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testFiltersSubAggsCancellation'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 3 failures in test testFiltersSubAggsCancellation (1.1% fail rate in 263 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (40.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/130770

Both a bigger thread pool and not draining the semaphore permits were leading to failing tests sometimes because of blocked threads (Too many threads searching would end up draining all permits in parallel, and getting stuck).

The test was added in https://github.com/elastic/elasticsearch/pull/130452

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java [hunk 1]
```diff
@@ -129,14 +137,14 @@ public void testFiltersSubAggsCancellation() throws Exception {
 
     private void ensureProperCancellation(SearchRequestBuilder searchRequestBuilder) throws Exception {
         var searchRequestFuture = searchRequestBuilder.setTimeout(TimeValue.timeValueSeconds(1)).execute();
-        assertFalse(searchRequestFuture.isCancelled());
-        assertFalse(searchRequestFuture.isDone());
+        assertThat(searchRequestFuture.isCancelled(), equalTo(false));
+        assertThat(searchRequestFuture.isDone(), equalTo(false));
```
Comment (ivancea) [inline server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:153]: The message looks better this way IMO, no functional change here

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java [hunk 2]
```diff
@@ -146,8 +154,8 @@ private void ensureProperCancellation(SearchRequestBuilder searchRequestBuilder)
 
         // Ensure the search request finished and that there are no more search tasks
         assertBusy(() -> {
-            assertTrue(searchRequestFuture.isDone());
-            assertThat(getSearchTasks(), empty());
+            assertThat("Search request didn't finish", searchRequestFuture.isDone(), equalTo(true));
```
Comment (GalLalouche) [inline server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:169]: Isn't there an `assertTrue` that also takes a `String`?

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java [hunk 3]
```diff
@@ -55,11 +57,12 @@ public class FiltersCancellationIT extends ESIntegTestCase {
...
     protected Collection<Class<? extends Plugin>> nodePlugins() {
-        return CollectionUtils.appendToCopy(super.nodePlugins(), pausableFieldPluginClass());
+        return CollectionUtils.appendToCopy(super.nodePlugins(), PauseScriptPlugin.class);
     }
 
-    protected Class<? extends Plugin> pausableFieldPluginClass() {
-        return PauseScriptPlugin.class;
+    @Override
+    public Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
+        return Settings.builder().put(super.nodeSettings(nodeOrdinal, otherSettings)).put("thread_pool.search.size", 4).build();
```
Comment (GalLalouche) [inline server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:77]: Out of curiosity, why 4?

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java (hunk 2 above)
Comment (GalLalouche) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:169]: Scratch that, I see now that you used it to get the `hamcrest` error message, and apparently `assertTrue(msg, bool)` is from `junit`, not `hamcrest`

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java (hunk 3 above)
Comment (ivancea) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:77]: Good question! That was the core of the issue:

Some context first:
- The `CancellableBulkScorer` we use to break the execution is called per search thread in the query.
- It breaks the "for each doc" into blocks of 4096 docs (x2 every iteration), and checks for cancellation between blocks
- The test uses 100.000 docs.
- The test adds around 99000 permits to a semaphore, so only 99000 docs can be processed before the threads getting blocked (And the test failing)
- Which is what the test does: It expect cancelled queries to not reach that many processed docs, and break earlier.

Now, if there are 25 threads, it would consume up to 25*4096 = 102400 docs (before checking for cancellation), which would be more than the semaphore permits, and threads would get blocked. Which is what happened sometimes.

To the specific question: 4 is just a small number that shouldn't trigger this case by a great margin.

Comment (GalLalouche) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:77]: Suggestion: Either add a short version of this explanation as a comment, or replace `4` with some computation based on the total number of documents.

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java (hunk 2 above)
Comment (ivancea) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:169]: Yeah. The message with assertTrue/False was just "AssertionError: null", while the equalTo(true) was like "false != true". Which isn't much better, but at least tells you something. Anyway, with the message they should be similar, but I changed them anyway XD

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java (hunk 3 above)
Comment (ivancea) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/FiltersCancellationIT.java:77]: Added a test javadoc explaining what it does, and how it does it (Including those magic constants)

**Review by GalLalouche — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]
