### PR TITLE
Fix msearch request parsing when index expression is null

### LINKED ISSUE #129631: NPE in XContentMapValues via MultiSearchRequest
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

 irrelevant

### Problem Description

For an `_msearch` request, if the body uses `null` for `index`, there's a NPE that's bubbling up. This should be handled in a more user friendly way by rejecting the request with a 400 error message.

### Steps to Reproduce

`/_msearch` request with body content as:

```
{"index": null}
{"query" : {"match_all" : {}}}
```

Gives an error 

```
{
    "error": {
        "root_cause": [
            {
                "type": "null_pointer_exception",
                "reason": "Cannot invoke \"Object.toString()\" because \"node\" is null"
            }
        ],
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"Object.toString()\" because \"node\" is null"
    },
    "status": 500
}
```

### Logs (if relevant)

```
[WARN ][r.suppressed             ] [runTask-0] path: /employees/_msearch, params: {index=employees}, status: 500 java.lang.NullPointerException: Cannot invoke "Object.toString()" because "node" is null
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.common.xcontent.support.XContentMapValues.nodeStringArrayValue(XContentMapValues.java:571)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.action.search.MultiSearchRequest.readMultiLineFormat(MultiSearchRequest.java:249)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.action.search.RestMultiSearchAction.parseMultiLineRequest(RestMultiSearchAction.java:190)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.action.search.RestMultiSearchAction.parseRequest(RestMultiSearchAction.java:133)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.action.search.RestMultiSearchAction.parseRequest(RestMultiSearchAction.java:98)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.action.search.RestMultiSearchAction.prepareRequest(RestMultiSearchAction.java:78)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:99)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:468)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:462)
        at org.elasticsearch.security@9.1.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:69)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:462)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:626)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:309)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:498)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:581)
        at org.elasticsearch.server@9.1.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:461)
        at org.elasticsearch.transport.netty4@9.1.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.handlePipelinedRequest(Netty4HttpPipeliningHandler.java:172)
        at org.elasticsearch.transport.netty4@9.1.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:147)
        at io.netty.transport@4.1.118.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
```

### PR DESCRIPTION
**Pull request by smalyshev**
Method `XContentMapValues.nodeStringArrayValue` does not check for null before trying to manipulate the value, but `null` is a legit value that can come from JSON, we should check for it. 

Fixes https://github.com/elastic/elasticsearch/issues/129631

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java [hunk 1]
```diff
@@ -537,6 +538,14 @@ public void testFailOnExtraCharacters() throws IOException {
         }
     }
 
+    public void testNullIndex() throws IOException {
+        try {
+            MultiSearchRequest request = parseMultiSearchRequest("/org/elasticsearch/action/search/msearch-null.json");
```
Comment (drempapis) [inline server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java]: This is a case of personal preference, but have you considered inlining the JSON directly?
Since the request is only a couple of lines, inlining it would improve readability and make the test easier to follow at a glance, especially for a simple case like this.

File: server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java [hunk 2]
```diff
@@ -537,6 +538,14 @@ public void testFailOnExtraCharacters() throws IOException {
...
+        } catch (ElasticsearchParseException e) {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java]: If the parse call does not throw, this test will succeed. Isn't the expectation that it should always fail? Should we use `expectThrows` instead?

File: server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java (hunk 1 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java]: ++ agreed

**Review by javanna — APPROVED** [review]
Thanks a lot for picking this up! The test needs a small adjustment I believe. No need for another review round once that is addressed.

I am curious to see if this has side effects on other consumers of the method. On the other hand null values cause NPE before so this fix can't hurt.

File: server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java (hunk 2 above)
Comment (smalyshev) [reply server/src/test/java/org/elasticsearch/action/search/MultiSearchRequestTests.java]: You are right, that's probably what it should be... It throws now (NPE) but there's no guarantee it won't stop throwing in the future, so `expectThrows` is better.

**Review by drempapis — APPROVED** [review]
