### PR TITLE
[Entitlements] Fix FileAccessTree paths ordering

### LINKED ISSUE #123611: [CI] DataStreamsClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6666 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/2ievlr3jeq4wq)
- [elasticsearch-periodic-platform-support #6659 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/vhiee2n7wp7vq)
- [elasticsearch-periodic-platform-support #6646 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/jclurmnl62mkg)
- [elasticsearch-periodic-platform-support #6639 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/jxs4rogtrdpag)
- [elasticsearch-periodic-platform-support #6632 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/dqbi2cw3glev2)
- [elasticsearch-periodic-platform-support #6625 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/6gkind7ofozki)
- [elasticsearch-pull-request #59081 / part-1](https://gradle-enterprise.elastic.co/s/6dnfsldn3h6lc)
- [elasticsearch-pull-request #59081 / rest-compatibility](https://gradle-enterprise.elastic.co/s/tfubtikel3odi)
- [elasticsearch-pull-request #59025 / rest-compatibility](https://gradle-enterprise.elastic.co/s/zvolg6eqxtiey)
- [elasticsearch-pull-request #58984 / part-1](https://gradle-enterprise.elastic.co/s/3i4fag3k2wyle)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.DataStreamsClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.datastreams.DataStreamsClientYamlTestSuiteIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [main] 6 consecutive failures in step windows-2022_checkrestcompat_platform-support-windows
- [main] 11 failures in class org.elasticsearch.datastreams.DataStreamsClientYamlTestSuiteIT (1.1% fail rate in 975 executions)
- [main] 6 failures in step windows-2022_checkrestcompat_platform-support-windows (66.7% fail rate in 9 executions)
- [main] 3 failures in step rest-compatibility (1.1% fail rate in 266 executions)
- [main] 2 failures in step part-1 (0.9% fail rate in 222 executions)
- [main] 6 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 9 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.1% fail rate in 271 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123655: [CI] IngestCommonClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6670 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/2a4zovnn3g6n4)
- [elasticsearch-periodic-platform-support #6663 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/y5br6pttzvxlq)
- [elasticsearch-periodic-platform-support #6663 / windows-2019_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/6imjuq2z72oxu)
- [elasticsearch-periodic-platform-support #6656 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/k3rlwnpz5c7ko)
- [elasticsearch-periodic-platform-support #6656 / windows-2019_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/wwewqdafftf7y)
- [elasticsearch-periodic-platform-support #6649 / windows-2019_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/x3clyfnrkz7o2)
- [elasticsearch-periodic-platform-support #6649 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/mhj3tacqtfnq2)
- [elasticsearch-periodic-platform-support #6642 / windows-2019_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/tmujf55ohu2qe)
- [elasticsearch-periodic-platform-support #6642 / windows-2022_checkrestcompat_platform-support-windows](https://gradle-enterprise.elastic.co/s/thlbpghyyod76)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.18] 5 consecutive failures in step windows-2022_checkrestcompat_platform-support-windows
- [8.18] 4 consecutive failures in step windows-2019_checkrestcompat_platform-support-windows
- [8.18] 9 failures in class org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT (3.5% fail rate in 259 executions)
- [8.18] 5 failures in step windows-2022_checkrestcompat_platform-support-windows (100.0% fail rate in 5 executions)
- [8.18] 4 failures in step windows-2019_checkrestcompat_platform-support-windows (100.0% fail rate in 4 executions)
- [8.18] 5 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #123682: [CI] DotPrefixClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6680 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/wdliz5ocguns2)
- [elasticsearch-pull-request #59774 / rest-compatibility](https://gradle-enterprise.elastic.co/s/7kdejpl73q65q)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.validation.DotPrefixClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.validation.DotPrefixClientYamlTestSuiteIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [main] 2 failures in class org.elasticsearch.validation.DotPrefixClientYamlTestSuiteIT (0.6% fail rate in 358 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
This PR re-introduce "string" ordering for FileAccessTree, with special cases for directory separators, as the existing based on path iteration was not working on Windows - `WindowsPath` discards the root.

It does still handles paths in a slightly different way between Windows and non-Windows (Posix).
This is because Java supports both \ and / as separators on Windows, but \ is a valid character for file names in Posix - it's very strange, possibly not frequent, but it's a possibility. This means that windows paths will be possibly ordered "wrongly" on a Linux machine; this should not matter, as we won't be matching any path to them.

Fixes #123682, fixes #123655, fixes #123611 and possibly other windows IT tests failures

### CODE REVIEW

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+     * any other character so that files in a directory appear immediately after that directory.
+     * For example, we require [/a, /a/b, /a.xml] rather than the natural order [/a, /a.xml, /a/b].
+     */
+    static final Comparator<String> PATH_ORDER = (s1, s2) -> {
+        int len1 = s1.length();
+        int len2 = s2.length();
+        int lim = Math.min(len1, len2);
+        for (int k = 0; k < lim; k++) {
+            char c1 = s1.charAt(k);
+            char c2 = s2.charAt(k);
```
Comment (mosche) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:34]: `if(c1 == c2) continue;`

Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:34]: :D I did that, but Intellij suggested to change it this way.
I agree with you though, it's better, and more clear.

File: libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+        assertThat(isAbsolutePath(uncPath), is(true));
+        assertThat(isAbsolutePath(longPath), is(true));
+
+        assertThat(isAbsolutePath(relativePath), is(false));
+        assertThat(isAbsolutePath(headingSlashRelativePath), is(false));
+        assertThat(isAbsolutePath(""), is(false));
+    }
+
+    public void testPathOrder() {
+        // Files come before directories with same name
```
Comment (mosche) [inline libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java:46]:
```suggestion
        // Files come AFTER directories with same name
```

File: libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+        // Unix-style
+        assertThat(PATH_ORDER.compare("/a/b", "/a.xml"), lessThan(0));
+        assertThat(PATH_ORDER.compare("/a/b", "/a/b.txt"), lessThan(0));
+        assertThat(PATH_ORDER.compare("/a/c", "/a/b.txt"), greaterThan(0));
+        // Inverted-windows style
+        assertThat(PATH_ORDER.compare("C:/a/b", "C:/a.xml"), lessThan(0));
+        assertThat(PATH_ORDER.compare("C:/a/b", "C:/a/b.txt"), lessThan(0));
+        assertThat(PATH_ORDER.compare("C:/a/c", "C:/a/b.txt"), greaterThan(0));
+
+        // Files in subdirectories come before
```
Comment (mosche) [inline libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java:56]: this comment is confusing, "before" what?

File: libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+
+        assertThat(isAbsolutePath(relativePath), is(false));
+        assertThat(isAbsolutePath(headingSlashRelativePath), is(false));
+        assertThat(isAbsolutePath(""), is(false));
+    }
+
+    public void testPathOrder() {
+        // Files come before directories with same name
+        // Unix-style
+        assertThat(PATH_ORDER.compare("/a/b", "/a.xml"), lessThan(0));
```
Comment (mosche) [inline libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java:48]: this one and the corresponding windows one are worth highlighting I think, these are the only ones that differ from lexicographical sort order

**Review by mosche — APPROVED** [review]
lgtm, just some minor nits on tests

File: libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java (hunk 4 above)
Comment (ldematte) [reply libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java:48]: How do you propose to highlight them?

Comment (mosche) [reply libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/FileUtilsTests.java:48]: could be as simple as a comment like this
```suggestion
        assertThat(PATH_ORDER.compare("/a/b", "/a.xml"), lessThan(0)); // differs from natural lexicographical 
 ordering
```

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:34]: Using `charAt` tends to cause problems for characters outside the basic multilingual plane (like emojis), but I suspect it doesn't matter in this case because we're only comparing for order, not trying to identify the actual characters.

As silly as it sounds, it might be good to have at least one test with an emoji to demonstrate that this logic works with characters outside the BMP.

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+            boolean c1IsSeparator = isPathSeparator(c1);
+            boolean c2IsSeparator = isPathSeparator(c2);
+            if (c1IsSeparator == false || c2IsSeparator == false) {
+                if (c1IsSeparator) {
+                    return -1;
+                }
+                if (c2IsSeparator) {
+                    return 1;
+                }
+                return c1 - c2;
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:47]: Simply subtracting two integers is discouraged. Instead, `Integer.compare` is recommended.

I think it doesn't matter in this case, because the range of these two values is so limited, but it might be best to call `Integer.compare` so the code doesn't "look wrong".

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 7]
```diff
@@ -0,0 +1,108 @@
...
+            }
+        }
+        return len1 - len2;
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:50]: Ditto.

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+    };
+
+    /**
+     * Java allows to use both forward and backslash on Windows systems as path separators;
+     * On posix filesystems however '\' is a valid character for file or directory names, so we stick to just the
+     * standard platform separator for anything that is not Windows.
+     */
+    @SuppressForbidden(reason = "we need the separator as a char, not a string")
+    private static boolean isPathSeparator(char c) {
+        if (Platform.WINDOWS.isCurrent()) {
```
[the remark this answers is not in the document]
Comment (prdoyle) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:60]: I think we should, and do, normalize all slashes into the canonical separator for the platform.

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 9]
```diff
@@ -0,0 +1,108 @@
...
+            return isSlash(c);
+        }
+        return c == File.separatorChar;
+    }
+
+    /**
+     * Tests if a path is absolute or relative, taking into consideration both Unix and Windows conventions.
+     * Note that this leads to a conflict, resolved in favor of Unix rules: `/foo` can be either a Unix absolute path, or a Windows
+     * relative path with "wrong" directory separator (using non-canonical slash in Windows).
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:69]: I realize this javadoc isn't new to this PR, so this is your call...

It might be worth explaining why this wrongness is acceptable. I think it's because this is only for validation, and that if we allow something that looks like an absolute path but isn't, the consequences are minor?

**Review by prdoyle — APPROVED** [review]
Some optional suggestions.

**Comment by ldematte** [comment]
Test failures are fixed by https://github.com/elastic/elasticsearch/pull/123744

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java (hunk 5 above)
Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:34]: I added a test and there were no surprises.
I think we are OK here: as you said, as long as the order is consistent we don't care much. One important caveat is that we do not match the "special" char (/ or \) with a random surrogate by mistake, but surrogates are in a whole different range, so that won't be an issue.

**Comment by ldematte** [comment]
The remaining failure on part-4-windows is on `ml\qa\multi-cluster-tests-with-security`, which uses a 8.19 SNAPSHOT cluster - of course it fails, fix is in this PR and needs to be backported. 
It's the only failure, so I'm going to ignore it.

**Comment by ldematte** [comment]
(failures in part3 are ESQL and not entitled related - checked logs) but I'm going to retry
