### PR TITLE
Hide IndexSearcher in AggregatorTestCase

### LINKED ISSUE #98892: [CI] TopHitsAggregatorTests testInsideTerms failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/46rwazpmvyitw/tests/:server:test/org.elasticsearch.search.aggregations.metrics.TopHitsAggregatorTests/testInsideTerms

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.TopHitsAggregatorTests.testInsideTerms" -Dtests.seed=90051C4A26125ACF -Dtests.locale=zh-Hans-CN -Dtests.timezone=Asia/Muscat -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.metrics.TopHitsAggregatorTests&tests.test=testInsideTerms

**Failure excerpt:**
```
java.lang.ClassCastException: class org.apache.lucene.index.ParallelCompositeReader cannot be cast to class org.apache.lucene.index.DirectoryReader (org.apache.lucene.index.ParallelCompositeReader and org.apache.lucene.index.DirectoryReader are in unnamed module of loader 'app')

  at __randomizedtesting.SeedInfo.seed([90051C4A26125ACF:604FF155EE19B856]:0)
  at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:283)
  at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:256)
  at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.getMaxOrd(TermsAggregatorFactory.java:357)
  at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.lambda$bytesSupplier$0(TermsAggregatorFactory.java:117)
  at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:308)
  at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:41)
  at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:81)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:268)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:540)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.runWithCrankyCircuitBreaker(AggregatorTestCase.java:490)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:473)
  at org.elasticsearch.search.aggregations.metrics.TopHitsAggregatorTests.testCase(TopHitsAggregatorTests.java:131)
  at org.elasticsearch.search.aggregations.metrics.TopHitsAggregatorTests.testInsideTerms(TopHitsAggregatorTests.java:79)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by iverase**
We are currently allowing implementers of `AggregatorTestCase` to provide their own IndexSearcher. THis can be done using `AggregatorTestCase#newIndexSearcher` which provides our own IndexSearcher implementation or using `LucenTestCase#newSearcher` which provides a Lucene implementation.

The issue is that at the moment both implementation are different and the current lucene implementation is not good enough for us when running in concurrent mode which is making the test less realistics. 

Therefore we propose to hide the creation of the index searcher from the implementers by changing the signature of `AggregatorTestCase#searchAndReduce` and `AggregatorTestCase#createAggregationContext` to take an IndexReader instead of an IndexSearcher. In addition `AggregatorTestCase#newIndexSearcher` is private now.

relates https://github.com/elastic/elasticsearch/issues/98672
fixes https://github.com/elastic/elasticsearch/issues/98892

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java [hunk 1]
```diff
@@ -282,7 +283,21 @@ protected <A extends Aggregator> A createAggregator(AggregatorFactories.Builder
...
+            query,
+            new NoneCircuitBreakerService(),
+            AggregationBuilder.DEFAULT_PREALLOCATION * 5, // We don't know how many bytes to preallocate so we grab a hand full
+            DEFAULT_MAX_BUCKETS,
+            false,
+            fieldTypes
+        );
+    }
+
+    private AggregationContext createAggregationContext(IndexSearcher indexSearcher, Query query, MappedFieldType... fieldTypes)
```
Comment (kkrik-es) [inline test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:300]: Should this be marked as deprecated too?

Comment (iverase) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:300]: ` * Deprecated - this will be made private in a future update`

I don't think so, this method will stay as we still need to construct those objects in order to run aggregations. It will be internal so we control the life cycle of those objects.

File: test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java [hunk 2]
```diff
@@ -306,7 +321,29 @@ protected AggregationContext createAggregationContext(IndexSearcher indexSearche
...
+            query,
+            breakerService,
+            bytesToPreallocate,
+            maxBucket,
+            isInSortOrderExecutionRequired,
+            fieldTypes
+        );
+    }
+
+    private AggregationContext createAggregationContext(
```
Comment (kkrik-es) [inline test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:345]: Ditto

Comment (iverase) [reply test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java:345]: Ditto above :)

**Review by kkrik-es — APPROVED** [review]
