### PR TITLE
[ML] Better error when persistent task assignment disabled

### LINKED ISSUE #51956: [ML] Inform user when persistent task allocation is disabled when creating or executing jobs
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.2
**Platform:** ESS and on-prem

If persistent task allocation has been disabled with cluster setting `"cluster.persistent_tasks.allocation.enable": "none"`, the job creation UI informs the user with:

```
Job creation error

[status_exception] Could not open job because no ML nodes with sufficient capacity were found
```

Screen Shot 2020-02-05 at 11 32 53 AM

The job is left with status:

```
No node found to open job. Reasons [persistent task [xpack/ml/job] cannot be assigned [no persistent task assignments are allowed due to cluster settings]]
```

Screen Shot 2020-02-05 at 11 33 41 AM

The initial `[status_exception] Could not open job because no ML nodes with sufficient capacity were found` error is especially misleading if the user knows ML nodes are available. Couple that with Kibana indicating there are no active ML nodes:

image

It would be a usability enhancement if these errors could point to the persistent tasks cluster setting as the culprit. 

**Steps to reproduce**:

 1. Disable allocation of persistent tasks.

    ```
    PUT /_cluster/settings
    {
      "transient": {
        "cluster.persistent_tasks.allocation.enable": "none"
      }
    }
    ```

1. Create an ML job.
1. Observe UI errors.

**Provide logs (if relevant)**:

```
[2020-02-05T15:12:58.168Z][WARN][org.elasticsearch.xpack.ml.action.TransportOpenJobAction] [instance-0000000310] [test] Could not open job because no suitable nodes were found, allocation explanation [persistent task [xpack/ml/job] cannot be assigned [no persistent task assignments are allowed due to cluster settings]]
```

### PR DESCRIPTION
**Pull request by droberts195**
Changes the misleading error message when attempting to open
a job while the "cluster.persistent_tasks.allocation.enable"
setting is set to "none" to a clearer message that names the
setting.

Closes #51956

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java [hunk 1]
```diff
@@ -560,7 +561,13 @@ public boolean test(PersistentTasksCustomMetaData.PersistentTask<?> persistentTa
                         assignment.isAssigned() == false) {
                     OpenJobAction.JobParams params = (OpenJobAction.JobParams) persistentTask.getParams();
                     // Assignment has failed on the master node despite passing our "fast fail" validation
-                    exception = makeNoSuitableNodesException(logger, params.getJobId(), assignment.getExplanation());
+                    if (assignment.equals(AWAITING_UPGRADE)) {
+                        exception = makeCurrentlyBeingUpgradedException(logger, params.getJobId(), assignment.getExplanation());
+                    } else if (assignment.getExplanation().contains("[" + EnableAssignmentDecider.ALLOCATION_NONE_EXPLANATION + "]")) {
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java]: It's not ideal that this is done using `contains`.  The better solution would be to make `Assignment`s contain a reason number or enum value as well as a text reason.  Then we could check that.  But that's obviously a pretty far-reaching change.  It may be worth waiting until there are more use cases for a reason code so that any implementation can take all the use cases into account.

**Review by benwtrent — APPROVED** [review]
should work for the kibana UI as well.

**Comment by benwtrent** [comment]
Just checked the error displayed in kibana, looks good:

image
