### PR TITLE
Service Accounts - Ensure valid random service token name

### LINKED ISSUE #73081: [CI] ActionRequestValidationException for docs test en/rest-api/security/create-service-token/line_101
**Build scan**: https://gradle-enterprise.elastic.co/s/4yk62tb2hmg4a

**Repro line**: `gradlew ':x-pack:docs:integTest' --tests "org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT.test {yaml=en/rest-api/security/create-service-token/line_101}" -Dtests.seed=19D01AD163407EC6 -Dtests.locale=mk-MK -Dtests.timezone=ACT -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure excerpt**:

```
03:38:14   1> [2021-05-14T10:07:06,642][INFO ][o.e.s.XDocsClientYamlTestSuiteIT] [test] Stash dump on test failure [{
03:38:14   1>   "stash" : {
03:38:14   1>     "body" : {
03:38:14   1>       "error" : {
03:38:14   1>         "root_cause" : [
03:38:14   1>           {
03:38:14   1>             "type" : "action_request_validation_exception",
03:38:14   1>             "reason" : "Validation Failed: 1: service account token name must have at least 1 character and at most 256 characters that are alphanumeric (A-Z, a-z, 0-9) or hyphen (-) or underscore (_). It must not begin with an underscore (_).;",
03:38:14   1>             "stack_trace" : "[Validation Failed: 1: service account token name must have at least 1 character and at most 256 characters that are alphanumeric (A-Z, a-z, 0-9) or hyphen (-) or underscore (_). It must not begin with an underscore (_).;]; nested: ActionRequestValidationException[Validation Failed: 1: service account token name must have at least 1 character and at most 256 characters that are alphanumeric (A-Z, a-z, 0-9) or hyphen (-) or underscore (_). It must not begin with an underscore (_).;];
03:38:14   1> 	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:633)
03:38:14   1> 	at org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:561)
03:38:14   1> 	at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)
03:38:14   1> 	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:99)
03:38:14   1> 	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:82)
03:38:14   1> 	at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)
03:38:14   1> 	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:92)
03:38:14   1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:140)
03:38:14   1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77)
03:38:14   1> 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86)
03:38:14   1> 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:66)
03:38:14   1> 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:402)
03:38:14   1> 	at org.elasticsearch.xpack.security.rest.action.service.RestCreateServiceAccountTokenAction.lambda$innerPrepareRequest$0(RestCreateServiceAccountTokenAction.java:60)
03:38:14   1> 	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:106)
03:38:14   1> 	at org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$handleRequest$0(SecurityRestFilter.java:88)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$2(SecondaryAuthenticator.java:83)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:93)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:78)
03:38:14   1> 	at org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$handleRequest$2(SecurityRestFilter.java:82)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$writeAuthToContext$26(AuthenticationService.java:717)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.writeAuthToContext(AuthenticationService.java:735)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.finishAuthentication(AuthenticationService.java:706)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeUser(AuthenticationService.java:653)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$consumeToken$18(AuthenticationService.java:523)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
03:38:14   1> 	at org.elasticsearch.xpack.core.common.IteratingActionListener.onResponse(IteratingActionListener.java:127)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$consumeToken$15(AuthenticationService.java:489)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.lambda$authenticateWithCache$1(CachingUsernamePasswordRealm.java:147)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.handleCachedAuthentication(CachingUsernamePasswordRealm.java:227)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.lambda$authenticateWithCache$2(CachingUsernamePasswordRealm.java:139)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListenerDirectly(ListenableFuture.java:113)
03:38:14   1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:55)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.authenticateWithCache(CachingUsernamePasswordRealm.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.authenticate(CachingUsernamePasswordRealm.java:105)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$consumeToken$17(AuthenticationService.java:478)
03:38:14   1> 	at org.elasticsearch.xpack.core.common.IteratingActionListener.run(IteratingActionListener.java:103)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:533)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$13(AuthenticationService.java:445)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:455)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$checkForApiKey$5(AuthenticationService.java:396)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.authenticateWithApiKeyIfPresent(ApiKeyService.java:402)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.checkForApiKey(AuthenticationService.java:377)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$checkForBearerToken$3(AuthenticationService.java:361)
03:38:14   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.TokenService.tryAuthenticateToken(TokenService.java:393)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.checkForBearerToken(AuthenticationService.java:357)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:338)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$8(AuthenticationService.java:414)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:425)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:333)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:274)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:152)
03:38:14   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:137)
03:38:14   1> 	at org.elasticsearch.xpack.security.rest.SecurityRestFilter.handleRequest(SecurityRestFilter.java:75)
03:38:14   1> 	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:269)
03:38:14   1> 	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:351)
03:38:14   1> 	at org.elasticsearch.rest.RestController.dispatchRequ  1> est(RestController.java:192)
03:38:14   1> 	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:451)
03:38:14   1> 	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:516)
03:38:14   1> 	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:378)
03:38:14   1> 	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:31)
03:38:14   1> 	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:17)
03:38:14   1> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:47)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
03:38:14   1> 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
03:38:14   1> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
03:38:14   1> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
03:38:14   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
03:38:14   1> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
03:38:14   1> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
03:38:14   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
03:38:14   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
03:38:14   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
03:38:14   1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
03:38:14   1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
03:38:14   1> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
03:38:14   1> 	at java.base/java.lang.Thread.run(Thread.java:834)
03:38:14   1> Caused by: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: service account token name must have at least 1 character and at most 256 characters that are alphanumeric (A-Z, a-z, 0-9) or hyphen (-) or underscore (_). It must not begin with an underscore (_).;
03:38:14   1> 	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:15)
03:38:14   1> 	at org.elasticsearch.xpack.core.security.action.service.CreateServiceAccountTokenRequest.validate(CreateServiceAccountTokenRequest.java:101)
03:38:14   1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:138)
```

### PR DESCRIPTION
**Pull request by ywangd**
The random token name is a base64 UUID. It can sometimes vilolate the
validation rules. The base64 UUID is now prefixed with a string `token_` 
to ensure the name is always valid.

Resolves: #73081

### CODE REVIEW

**Comment by tvernum** [comment]
Don't we use the same technique to generate a token name in the rest handler? Does that also need to change?

**Comment by ywangd** [comment]
> Don't we use the same technique to generate a token name in the rest handler? Does that also need to change?

I don't quite follow. This change is for the rest handler. Do you mean the CLI tool? The CLI tool always requires user specified token name.

**Comment by tvernum** [comment]
I mean the actual Test handler. It supports auto generating a token name (as a UUID) if one isn't provided. Why isn't that name susceptible to the same validation issues?

**Comment by tvernum** [comment]
Ok, I understand now - I was on mobile so I was going by the description not the code and assumed, based on the issue title that this was test code.

Why does the issue say Test, when it's change a production action?

**Comment by ywangd** [comment]
> Why does the issue say Test, when it's change a production action?

It should not. I correctly labelled it but somehow the title was missed. Will update it.

**Comment by ywangd** [comment]
@tvernum I updated the title to drop the "Test" bit. I'd like to get this into 7.13 since user of this API has a good chance to run into this bug. Thanks!

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java [hunk 1]
```diff
@@ -48,7 +50,7 @@ public String getName() {
     protected RestChannelConsumer innerPrepareRequest(RestRequest request, NodeClient client) throws IOException {
         String tokenName = request.param("name");
         if (Strings.isNullOrEmpty(tokenName)) {
-            tokenName = UUIDs.base64UUID();
+            tokenName = new String(Hasher.SHA256.hash(new SecureString(UUIDs.base64UUID().toCharArray())));
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java:53]: This feels like a weird fix.

We were using a random UUID in URL safe base64. But because it's possible for that to generate a string with a leading `_` (I think that's the problem), we're generating the Hash of that string and hex-encoding it.

The Hex encoding is the bit that actually solves the problem, but we're applying a bunch of other stuff as well.

Personally, I'd prefer that we drop leading `_` or regenerate rather than apply hashing and hex encoding just to work around a tiny incompatibility with the bast64 encoding.

**Review by tvernum — APPROVED** [review]
I'm happy to merge this since it's better to fix this issue than ship with it, but I don't think it's the best fix to the problem.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java (hunk 1 above)
Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java:53]: I thought about regenerating or replacing `_` or prefixing a random char or hex encoding the base64 bytes. But at the end, I chose sha256 since it is does not reduce the entropy (though it is not that important). It is also the most convenient.

Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java:53]: OK, but in this case it feels like we could ditch the whole UUID, base64 & SHA256 and just generate a string of bytes to be hex encoded.
In the end, that's all we actually want, and we're layering a lot of other algorithms on top of it.

Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java:53]: The token name is part of the document ID. So the UUID was initially chosen to minimize the possibility of collision since it is what used by the indexing itself. For this reason, I'd personally keep UUID (and subsequently base64 for it to be URL friendly). But SHA256 can be ditched. Previously I was thinking prefixing a random char before the UUID but didn't want to handle the randomness manually. But now it occurs to me that the prefix can and probably better be a fixed string, say `service_token_` or simply `st_`, which make the name more meaningful while keeping its randomness. I can update the PR to take this approach if you are OK with it.

Comment (tvernum) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java:53]: Yes some reasonable prefix (I would say `token_`, but I'm not too fussed) is a good choice

Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/service/RestCreateServiceAccountTokenAction.java]: Updated to prefix the name with `token_`. Thanks for the discussion!
