### PR TITLE
Disable search context release checks after every test

### LINKED ISSUE #55988: [CI] AsyncSearchActionIT failing with assertion error
Had a build on `7.7` branch fail with a number of tests from this suite with the following message. This seems to be the first of its kind but I thought I'd write this up since there's been a lot of work being done around this area. This didn't reproduce locally for me, perhaps Windows related?

```
org.elasticsearch.xpack.search.AsyncSearchActionIT > testRestartAfterCompletion FAILED
    java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
        at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
        at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$8(ESTestCase.java:532)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:917)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:890)
        at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:532)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.RuntimeException: [adoEdDSDTjWhheNvODX9pA][.async-search][0]scroll=[5m] query=[expiration_time:[-9223372036854775808 TO 1588201780463]]
            at org.elasticsearch.search.MockSearchService.addActiveContext(MockSearchService.java:60)
            at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:78)
            at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:635)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:428)
            at org.elasticsearch.search.SearchService.access$200(SearchService.java:135)
            at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395)
            at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:411)
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            ... 1 more

    java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
        at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
        at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$8(ESTestCase.java:532)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:917)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:890)
        at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:532)
        at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:382)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.RuntimeException: [adoEdDSDTjWhheNvODX9pA][.async-search][0]scroll=[5m] query=[expiration_time:[-9223372036854775808 TO 1588201780463]]
            at org.elasticsearch.search.MockSearchService.addActiveContext(MockSearchService.java:60)
            at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:78)
            at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:635)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:428)
            at org.elasticsearch.search.SearchService.access$200(SearchService.java:135)
            at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395)
            at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:411)
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            ... 1 more
REPRODUCE WITH: gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRestartAfterCompletion" -Dtests.seed=398B1AC9099AB198 -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Africa/Kigali -Dcompiler.java=14 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by jimczi**
This change adds a way to disable the checks that search contexts are all released
after each test in ESTestCase.
This is used by ESIntegTestCase to disable these checks if the cluster is shared
across all methods (SUITE scope). In this case, the contexts are checked at the end
when the cluster is cleared. This fixes integration tests that starts components that
perform search requests internally with a fixed delay (e.g.: async search maintenance service).

Fixes #55988

### CODE REVIEW

**Review by javanna — APPROVED** [review]
Another way to address the failures would be to plug in a no-op maintenance service in this test. I am not sure how much trouble that would be though, hence I am also ok with this solution.

**Comment by javanna** [comment]
> Another way to address the failures would be to plug in a no-op maintenance service in this test. 

I meant in the async search tests that are failing due to this check. I wonder if there are other cases where the check may cause problems, and whether it is useful today in between tests, probably not.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 1]
```diff
@@ -348,6 +348,14 @@ protected final boolean enableWarningsCheck() {
         return false;
     }
 
+    @Override
+    protected boolean enableSearchContextAfterCheck() {
+        // We don't want to check the release of search contexts between tests if the cluster is shared.
```
Comment (dnhatn) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:353]: I think debugging would be easier if we return true here and false in AsyncSearchActionIT instead.

**Comment by jimczi** [comment]
The initial fix doesn't work, we always check the releasing of search contexts **before** the node is stopped so the maintenance service continues to fire delete by query request.
I pushed a new [change](https://github.com/elastic/elasticsearch/pull/56673/commits/59603cbd7e2866cf598570d5c7a14a6f6a71b92e) that stop/start the maintenance service between each test in order to ensure that we stop sending delete by query requests before the check is done. 
Can you take another look @javanna ?

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 1 above)
Comment (jimczi) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java]: I reverted this since this solution doesn't work. Sorry for the trouble

File: x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/AsyncSearchIntegTestCase.java [hunk 2]
```diff
@@ -71,6 +75,25 @@ public SearchTestPlugin() {}
         }
     }
 
+    @Before
+    public void startMaitenanceService() {
```
Comment (javanna) [inline x-pack/plugin/async-search/src/test/java/org/elasticsearch/xpack/search/AsyncSearchIntegTestCase.java:79]: s/Maitenance/Maintenance here and below

**Review by javanna — APPROVED** [review]
still LGTM but even better than before :)
