### PR TITLE
Address mapping and compute engine runtime field issues

### LINKED ISSUE #117644: Investigate synthetic source doc values error
As part of running an es|ql error the following error occurred:

```
Caused by: java.io.EOFException: read past EOF: MemorySegmentIndexInput(path=".../elasticsearch-9.0.0-SNAPSHOT/data/indices/5KLVwOQ3QNOfGg4zLqBt4w/0/index/_11.cfs") [slice=_11_ES87TSDB_0.dvd] [slice=docs]
	at org.apache.lucene.store.MemorySegmentIndexInput.readByte(MemorySegmentIndexInput.java:158) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:97) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.MemorySegmentIndexInput.readInt(MemorySegmentIndexInput.java:273) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.DataInput.readLong(DataInput.java:145) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.MemorySegmentIndexInput.readLong(MemorySegmentIndexInput.java:300) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.codecs.lucene90.IndexedDISI$Method$2.advanceExactWithinBlock(IndexedDISI.java:692) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.codecs.lucene90.IndexedDISI.advanceExact(IndexedDISI.java:504) ~[lucene-core-10.0.0.jar:?]
	at org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesProducer$9.advanceExact(ES87TSDBDocValuesProducer.java:1052) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesProducer$5.advanceExact(ES87TSDBDocValuesProducer.java:299) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.apache.lucene.index.SingletonSortedSetDocValues.advanceExact(SingletonSortedSetDocValues.java:83) ~[lucene-core-10.0.0.jar:?]
	at org.elasticsearch.index.mapper.SortedSetDocValuesSyntheticFieldLoaderLayer$ImmediateDocValuesLoader.advanceToDoc(SortedSetDocValuesSyntheticFieldLoaderLayer.java:116) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.CompositeSyntheticFieldLoader.lambda$docValuesLoader$1(CompositeSyntheticFieldLoader.java:79) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader$ObjectDocValuesLoader.advanceToDoc(ObjectMapper.java:939) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader$ObjectDocValuesLoader.advanceToDoc(ObjectMapper.java:939) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader$ObjectDocValuesLoader.advanceToDoc(ObjectMapper.java:939) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.write(SourceLoader.java:210) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.source(SourceLoader.java:181) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$LeafWithMetrics.source(SourceLoader.java:146) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.search.lookup.SyntheticSourceProvider$SyntheticSourceLeafLoader.getSource(SyntheticSourceProvider.java:58) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.search.lookup.SyntheticSourceProvider.getSource(SyntheticSourceProvider.java:42) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:40) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	... 19 more
```

The es|ql part of the stack trace:

```
[2024-11-14T03:02:47,764][WARN ][o.e.x.e.a.EsqlResponseListener] [elasticsearch-1] Request failed with status [INTERNAL_SERVER_ERROR]: 
org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: unchecked_i_o_exception: Couldn't load source
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:42) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.AbstractFieldScript.extractFromSource(AbstractFieldScript.java:107) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.AbstractFieldScript.emitFromSource(AbstractFieldScript.java:127) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.LongFieldScript$1$1.execute(LongFieldScript.java:29) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.AbstractFieldScript.runForDoc(AbstractFieldScript.java:159) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.LongScriptBlockDocValuesReader.read(LongScriptBlockDocValuesReader.java:69) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.LongScriptBlockDocValuesReader.read(LongScriptBlockDocValuesReader.java:56) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.loadFromSingleLeaf(ValuesSourceReaderOperator.java:230) ~[?:?]
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:143) ~[?:?]
	at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:76) ~[?:?]
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:258) ~[?:?]
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:189) ~[?:?]
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:378) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

[full-stacktrace.txt](https://github.com/user-attachments/files/17957949/stacktrace.txt)

Queries like this fail

```
POST /_query
{
  "query": "FROM .ds-logs-nginx.error-default-2024.11.13-000001 | EVAL compression = rally.doc_size::DOUBLE / rally.message_size | STATS AVG(compression)"
}
```

### PR DESCRIPTION
**Pull request by martijnvg**
This PR addresses the following issues:
- Fields mapped as runtime fields not getting stored if source mode is synthetic.
- Address `java.io.EOFException` when an es|ql query uses multiple runtime fields that fallback to source when source mode is synthetic. (1)
- Address concurrency issue when runtime fields get pushed down to Lucene. (2)

1: ValueSourceOperator can read values in row striding or columnar fashion. When values are read in columnar fashion and multiple runtime fields synthetize source then this can cause the same `SourceProvider` evaluation the same range of docs ids multiple times. This can then result in unexpected io errors at the codec level. This is because the same doc value instances are used by `SourceProvider`. Re-evaluating the same docids is in violation of the contract of the DocIdSetIterator#advance(...) / DocIdSetIterator#advanceExact(...) methods, which documents that unexpected behaviour can occur if target docid is lower than current docid position.

Note that this is only an issue for synthetic source loader and not for stored source loader. And not when executing in row stride fashion which sometimes happen in compute engine and always happen in _search api.

2: The concurrency issue that arrises with source provider if source operator executes in parallel with data portioning set to DOC. The same `SourceProvider` instance then gets access by multiple threads concurrently. `SourceProviders` implementations are not designed to handle concurrent access.

Closes #117644

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 1]
```diff
@@ -941,7 +941,9 @@ public Query termQuery(Object value, SearchExecutionContext context) {
             protected void parseCreateField(DocumentParserContext context) {
                 // Run-time fields are mapped to this mapper, so it needs to handle storing values for use in synthetic source.
                 // #parseValue calls this method once the run-time field is created.
-                if (context.dynamic() == ObjectMapper.Dynamic.RUNTIME && context.canAddIgnoredField()) {
+                var fieldType = context.mappingLookup().getFieldType(path);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:944]: This is another bug. The value of mapped runtime fields wasn't added to ignored source.  I think we can also include this change in this PR. Otherwise some assertion in added PR need to be removed.

File: server/src/main/java/org/elasticsearch/index/mapper/LongScriptFieldType.java [hunk 2]
```diff
@@ -108,7 +108,12 @@ public DocValueFormat docValueFormat(String format, ZoneId timeZone) {
 
     @Override
     public BlockLoader blockLoader(BlockLoaderContext blContext) {
-        return new LongScriptBlockDocValuesReader.LongScriptBlockLoader(leafFactory(blContext.lookup()));
+        boolean isSyntheticSource = SourceFieldMapper.isSynthetic(blContext.indexSettings());
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/LongScriptFieldType.java:111]: Should we have two different implementations based on source mode?

**Comment by dnhatn** [comment]
Another issue is the thread switching, as the SyntheticSourceProvider is designed to work with only one thread. I think we need to address this before merging the change. It appears we are loading the source once for each script field, but I think it's okay to address the performance issue later.

```
сне 04, 2024 1:48:31 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#143,elasticsearch[node_s1][esql_worker][T#2],5,TGRP-SyntheticSourceIT]
java.lang.AssertionError: StoredFieldsReader are only supposed to be consumed in the thread in which they have been acquired. But was acquired in Thread[#145,elasticsearch[node_s1][esql_worker][T#4],5,TGRP-SyntheticSourceIT] and consumed in Thread[#143,elasticsearch[node_s1][esql_worker][T#2],5,TGRP-SyntheticSourceIT].
	at __randomizedtesting.SeedInfo.seed([273E3739EEB5DBA8]:0)
	at org.apache.lucene.tests.codecs.asserting.AssertingCodec.assertThread(AssertingCodec.java:44)
	at org.apache.lucene.tests.codecs.asserting.AssertingStoredFieldsFormat$AssertingStoredFieldsReader.document(AssertingStoredFieldsFormat.java:75)
	at org.apache.lucene.index.CodecReader$1.document(CodecReader.java:101)
	at org.elasticsearch.search.internal.FieldUsageTrackingDirectoryReader$FieldUsageTrackingLeafReader$2.document(FieldUsageTrackingDirectoryReader.java:137)
	at org.elasticsearch.index.fieldvisitor.StoredFieldLoader$ReaderStoredFieldLoader.advanceTo(StoredFieldLoader.java:205)
	at org.elasticsearch.search.lookup.SyntheticSourceProvider$SyntheticSourceLeafLoader.getSource(SyntheticSourceProvider.java:57)
	at org.elasticsearch.search.lookup.SyntheticSourceProvider.getSource(SyntheticSourceProvider.java:42)
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:40)
	at org.elasticsearch.script.AbstractFieldScript.extractFromSource(AbstractFieldScript.java:107)
	at org.elasticsearch.script.AbstractFieldScript.emitFromSource(AbstractFieldScript.java:127)
	at org.elasticsearch.script.LongFieldScript$1$1.execute(LongFieldScript.java:29)
	at org.elasticsearch.script.AbstractFieldScript.runForDoc(AbstractFieldScript.java:159)
	at org.elasticsearch.index.mapper.LongScriptBlockDocValuesReader.read(LongScriptBlockDocValuesReader.java:69)
	at org.elasticsearch.index.mapper.LongScriptBlockDocValuesReader.read(LongScriptBlockDocValuesReader.java:65)
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator$LoadFromMany.read(ValuesSourceReaderOperator.java:420)
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator$LoadFromMany.run(ValuesSourceReaderOperator.java:359)
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:159)
	at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:76)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:258)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:189)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:378)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 3]
```diff
@@ -471,12 +474,17 @@ void runCompute(CancellableTask task, ComputeContext context, PhysicalPlan plan,
         List<EsPhysicalOperationProviders.ShardContext> contexts = new ArrayList<>(context.searchContexts.size());
         for (int i = 0; i < context.searchContexts.size(); i++) {
             SearchContext searchContext = context.searchContexts.get(i);
+            var searchExecutionContext = new SearchExecutionContext(searchContext.getSearchExecutionContext()) {
+
+                @Override
+                public SourceProvider createSourceProvider() {
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:480]: Neat!

File: server/src/main/java/org/elasticsearch/search/lookup/ReinitializingSourceProvider.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+    private final Map<Long, SourceProvider> map = ConcurrentCollections.newConcurrentMap();
+
+    public ReinitializingSourceProvider(Supplier<SourceProvider> sourceProviderFactory) {
+        this.sourceProviderFactory = sourceProviderFactory;
+    }
+
+    @Override
+    public Source getSource(LeafReaderContext ctx, int doc) throws IOException {
+        var currentThread = Thread.currentThread();
+        var sourceProvider = map.computeIfAbsent(currentThread.threadId(), (key) -> sourceProviderFactory.get());
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/search/lookup/ReinitializingSourceProvider.java]: This could result in a memory leak since the map is never cleaned. Another option would be to remove items when a thread ends, but that would be too complex. For now, I think it's okay to keep the most recently created source provider.

```
    private PerThreadSourceProvider perThreadProvider;
    private final Supplier<SourceProvider> sourceProviderFactory;

    public ReinitializingSourceProvider(Supplier<SourceProvider> sourceProviderFactory) {
        this.sourceProviderFactory = sourceProviderFactory;
    }

    @Override
    public Source getSource(LeafReaderContext ctx, int doc) throws IOException {
        var currentThread = Thread.currentThread();
        PerThreadSourceProvider provider = perThreadProvider;
        if (provider == null || provider.creatingThread != currentThread) {
            provider = new PerThreadSourceProvider(sourceProviderFactory.get(), currentThread);
            this.perThreadProvider = provider;
        }
        return perThreadProvider.source.getSource(ctx, doc);
    }

    private record PerThreadSourceProvider(SourceProvider source, Thread creatingThread) {

    }
```
WDYT?

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/search/lookup/ReinitializingSourceProvider.java]: I discussed this with Martijn offline — the map is cleaned up once the query completes.

**Review by dnhatn — APPROVED** [review]
These two workarounds are good! Feel free to merge the PR. Thanks, Martijn!
