### PR TITLE
Expose executor service interface from thread pool

### LINKED ISSUE #19678: Expose ExecutorService#submit() in ThreadPool
Often times we use the following code:

``` java
final CountDownLatch latch = new CountDownLatch(1);
threadPool.generic().execute(() -> {
    try {
       // do stuff
    } finally {
        latch.countDown();
    }
});

try {
    latch.await(30, TimeUnit.SECONDS);
} catch (InterruptedException e) {
    Thread.currentThread().interrupt();
    // ignore
}
```

this is because we only expose the `Executor` interface. So we have to misuse latches to have poor man's futures.

If we'd expose (at least some) methods of `ExecutorService`, then we could write instead:

``` java
final Future<?> result = threadPool.generic().submit(() -> {
    // do stuff
});
try {
    result.get(30, TimeUnit.SECONDS);
} catch (InterruptedException e) {
    Thread.currentThread().interrupt();
} catch (ExecutionException e) {
    // ability to handle exceptions that have occurred in the lambda 
} catch (TimeoutException e) {
    // ability to handle the timeout
}
```

The intended interface will expose the following methods of `ExecutorService` (with the same semantics):

``` java
public interface EsExecutor extends Executor {
    <T> Future<T> submit(Callable<T> task);

    <T> Future<T> submit(Runnable task, T result);

    Future<?> submit(Runnable task);
}
```

As all our thread pools are based on `EsThreadPoolExecutor` as implementation class (which implements the `ExecutorService` interface), it is a just needed to expose the respective methods (no complex implementation needed).

We should also add a helper class to simplify the common case of just waiting for a result. Here's a sketch:

``` java
public final class FutureUtils {
    private FutureUtils() {
        throw new AssertionError("no instances!");
    }

    public static <T> Optional<T> getSilently(Callable<T> result) {
        try {
            return Optional.ofNullable(result.call());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } catch (TimeoutException e) {
            // ignore
        } catch (ExecutionException e) {
            // ability to handle exceptions that have occurred in the callable
        } catch (Exception e) {
            // ability to handle exceptions that have occurred in the callable
        }
        return Optional.empty();
    }
}
```

This would significantly reduce boilerplate for the standard use case:

``` java
final Future<?> result = Executors.newCachedThreadPool().submit(() -> {
    // do something
});
FutureUtils.getSilently(() -> result.get());
```

### PR DESCRIPTION
**Pull request by jasontedor**
This commit exposes the executor service interface from thread
pool. This will enable some high-level concurrency primitives that will
make some code cleaner and simpler.

Closes #19678

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Thanks for tackling this @jasontedor! It looks already pretty good; I just found a few minor things. Also CI found a compile error in `RemoteScrollableHitSourceTests`.

File: core/src/main/java/org/elasticsearch/common/util/concurrent/EsExecutors.java [hunk 1]
```diff
@@ -75,6 +78,50 @@ public static EsThreadPoolExecutor newFixed(String name, int size, int queueCapa
         return new EsThreadPoolExecutor(name, size, size, 0, TimeUnit.MILLISECONDS, queue, threadFactory, new EsAbortPolicy(), contextHolder);
     }
 
+    private static ExecutorService DIRECT_EXECUTOR_SERVICE = new AbstractExecutorService() {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/util/concurrent/EsExecutors.java]: I pushed 0dcac8f43ba09a680ea4f7b7f37aec8a26ceecec.

**Review by danielmitterdorfer — APPROVED** [review]
All comments are addressed. LGTM.

File: core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 2]
```diff
@@ -278,21 +278,24 @@ public ThreadPoolStats stats() {
...
+     * {@link Runnable} it is given in the {@link ThreadContext} of the thread that queues it.
+     *
+     * @param name the name of the executor service to obtain
+     * @throws IllegalArgumentException if no executor service with the specified name exists
      */
-    public Executor executor(String name) {
-        Executor executor = executors.get(name).executor();
+    public ExecutorService executor(String name) {
+        ExecutorService executor = executors.get(name).executor();
         if (executor == null) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: Good catch. I pushed 0dcac8f43ba09a680ea4f7b7f37aec8a26ceecec.

**Comment by jasontedor** [comment]
Thanks @danielmitterdorfer!
