### PR TITLE
Fix dynamic mapping detection for invalid dates

### LINKED ISSUE #93888: Dynamic Mapping interprets "2021-51" as a [date] field.
### Elasticsearch Version

8.5.0

### Installed Plugins

_No response_

### Java Version

elastic.co customer

### OS Version

elastic.co customer

### Problem Description

Dynamic mapping eagerly interprets a string with this format `2021-51` as a date field, but then fails to index due to 51 not being a valid month.

Expected behaviour would be to index `2021-51` as a text field.

### Steps to Reproduce

With [dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html) turned on attempt to index this document in a fresh, empty index:

```http
POST /bugreport/_doc
{
  "not_a_date": "2022-51"
}
```

Returned error message is:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "date_time_exception",
        "reason": "date_time_exception: Invalid value for MonthOfYear (valid values 1 - 12): 51"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [not_a_date] of type [date] in document with id 'U1f9Y4YBXO70bNmhk658'. Preview of field's value: '2022-51'",
    "caused_by": {
      "type": "date_time_exception",
      "reason": "date_time_exception: Invalid value for MonthOfYear (valid values 1 - 12): 51"
    }
  },
  "status": 400
}
```

### Logs (if relevant)

Mappings on index `bugreport`

```http
GET /bugreport/_mapping
```

```json
{
  "bugreport": {
    "mappings": {}
  }
}
```

### PR DESCRIPTION
**Pull request by cbuescher**
Invalid dates like "2021-51" are currently detected wrong as date field by the dynamic mapping detection. Trying to parse the invalid value then throws an error and no new mapping is created. The current way of parsing the value via the data formatters "parse" method is not sufficient to trigger an error, but changing this parsing check to "parseMillis" results in a DateTimeException which we then can ignore properly and fall back to the "text" field mapping.

Closes #93888

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/mapper/DynamicFieldsBuilderTests.java [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+        String source = "{\"" + fieldname + "\": " + value + "}";
+        XContentParser parser = createParser(JsonXContent.jsonXContent, source);
+        SourceToParse sourceToParse = new SourceToParse("test", new BytesArray(source), XContentType.JSON);
+        DocumentParserContext ctx = new TestDocumentParserContext(MappingLookup.EMPTY, sourceToParse) {
+            @Override
+            public XContentParser parser() {
+                return parser;
+            }
+        };
+        ctx.root().numericDetection();
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/index/mapper/DynamicFieldsBuilderTests.java:50]: Do you need to call this?

**Review by romseygeek — APPROVED** [review]
LGTM, nice fix and test (and some nice cleanups along the way too)

**Comment by cbuescher** [comment]
@romseygeek thanks for reviewing
