### PR TITLE
Fix recovery throttling to properly handle relocating non-primary shards

### LINKED ISSUE #18640: Recovery throttling does not properly account for relocating non-primary shards
Relocation of non-primary shards is realized by recovering from the primary shard. `RoutingNodes` wrongly equates non-primary relocation as recovering a shard from the non-primary relocation source, however. This invalidates the checks in the `ThrottlingAllocationDecider` where the number of concurrent incoming/outgoing recoveries are bound using the settings `cluster.routing.allocation.node_concurrent_recoveries`, `cluster.routing.allocation.node_concurrent_incoming_recoveries` and `cluster.routing.allocation.node_concurrent_outgoing_recoveries`.

### PR DESCRIPTION
**Pull request by ywelsch**
Relocation of non-primary shards is realized by recovering from the primary shard. Recovery throttling wrongly equates non-primary relocation as recovering a shard from the non-primary relocation source, however.

Closes #18640

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java [hunk 1]
```diff
@@ -108,18 +108,18 @@ public RoutingNodes(ClusterState clusterState, boolean readOnly) {
...
                             // it's relocating from.
                             ShardRouting targetShardRouting = shard.buildTargetRelocatingShard();
-                            addInitialRecovery(targetShardRouting, routingTable);
+                            addInitialRecovery(targetShardRouting, indexShard.primary);
                             previousValue = entries.put(targetShardRouting.shardId(), targetShardRouting);
                             if (previousValue != null) {
                                 throw new IllegalArgumentException("Cannot have two different shards with same shard id on same node");
                             }
                             assignedShardsAdd(targetShardRouting);
-                        } else if (shard.active() == false) { // shards that are initializing without being relocated
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: can it be unassigned too? I am still trying to get back into how this works but I wonder why :)

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: here, we're iterating over the shards assigned to a node (further up outside Github view: `if (shard.assignedToNode()) {`).

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java [hunk 2]
```diff
@@ -141,41 +141,43 @@ private void removeRecovery(ShardRouting routing) {
...
+        assert initialPrimaryShard == null || initialPrimaryShard.assignedToNode() :
+            "shard is initializing but its primary is not assigned to a node";
+
         Recoveries.getOrAdd(recoveriesPerNode, routing.currentNodeId()).addIncoming(howMany);
-        final String sourceNodeId;
-        if (routing.relocatingNodeId() != null) { // this is a relocation-target
-            sourceNodeId = routing.relocatingNodeId();
-            if (routing.primary() && increment == false) { // primary is done relocating
+
+        if (routing.isPeerRecovery()) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: this is nice!

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java [hunk 3]
```diff
@@ -187,8 +189,8 @@ public int getOutgoingRecoveries(String nodeId) {
         return recoveriesPerNode.getOrDefault(nodeId, Recoveries.EMPTY).getOutgoing();
     }
 
-    private ShardRouting findPrimary(ShardRouting routing) {
-        List<ShardRouting> shardRoutings = assignedShards.get(routing.shardId());
+    public ShardRouting findAssignedPrimary(ShardId shardId) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: why is this public now can it be private still?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java [hunk 4]
```diff
@@ -109,50 +112,58 @@ private void setPrimariesInitialRecoveries(int primariesInitialRecoveries) {
...
-                int primariesInRecovery = 0;
-                for (ShardRouting shard : node) {
-                    // when a primary shard is INITIALIZING, it can be because of *initial recovery* or *relocation from another node*
-                    // we only count initial recoveries here, so we need to make sure that relocating node is null
-                    if (shard.initializing() && shard.primary() && shard.relocatingNodeId() == null) {
-                        primariesInRecovery++;
-                    }
+        assert shardRouting.primary() == false || shardRouting.unassigned() || shardRouting.active();
+
+        if (shardRouting.primary() == false || shardRouting.unassigned() == false) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: so this means that we either have a replica peer recovery (primary == false) or we have a primary relocation that means it's not assigned? I wonder if we can make this more clear? maybe assign local vars?

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java (hunk 3 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: right, I used it in ThrottlingAllocationDecider, then saw that we have the nicer method "activePrimary" here.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java [hunk 5]
```diff
@@ -109,50 +112,58 @@ private void setPrimariesInitialRecoveries(int primariesInitialRecoveries) {
...
-        // either primary or replica doing recovery (from peer shard)
+        } else {
+            // primary is unassigned, means we are going to do recovery from store, snapshot or local shards
+            // count *just the primaries* currently doing recovery on the node and check against primariesInitialRecoveries
+            assert shardRouting.primary() && shardRouting.unassigned();
 
-        // count the number of recoveries on the node, its for both target (INITIALIZING) and source (RELOCATING)
-        return canAllocate(node, allocation);
-    }
+            // TODO: Should index creation not be throttled?
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: so this is commented out, I wonder if this is really simple to do? The primaries can be allocaed for a while and be big and then we have space for the replicas and the recovery is big?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java [hunk 6]
```diff
@@ -109,50 +112,58 @@ private void setPrimariesInitialRecoveries(int primariesInitialRecoveries) {
...
+//            if (shardRouting.unassignedInfo().getReason() == UnassignedInfo.Reason.INDEX_CREATED) {
+//                return allocation.decision(Decision.YES, NAME, "empty shard does not need recovery");
+//            }
 
-    @Override
-    public Decision canAllocate(RoutingNode node, RoutingAllocation allocation) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: hmm we don't want this shortcut anymore? I mean it could speed up thinks no?

**Comment by s1monw** [comment]
left some questions... looks good in general

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 6 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: Yeah, I wasn't too happy on removing it. Unfortunately, it wasn't safe and there is no safe version which makes sense. Even if `incomingRecoveries` is over the limit, we might still allocate primary unassigned shards (which are only bound by `primariesInitialRecoveries`). Checking for `outgoingRecoveries` on this node to allocate a shard makes no sense at all, as allocating a shard to this node only affects the outgoing recoveries of the node that has the primary shard.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 4 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: Unfortunately we cannot use `shardrouting.isPeerRecovery()` here because the `shardRouting` that is passed to the method is not the initializing shard that will be assigned to this node. I will add some more comments.

I can also invert the flow of this `if/else` condition so that we have `shardRouting.primary() && shardRouting.unassigned()` as boolean condition which corresponds to what we currently have in the `else` branch.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 5 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: I'm not sure I follow here. In case of index creation, we don't do any kind of "real recovery" for the primary shard. What we do is delete existing files and create a new index and translog, which probably amounts to tiny work. What the `ThrottlingAllocationDecider` tries to prevent (imho) is that we do too much IO on a node by recovering too many shards in parallel.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 4 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: I think it would be enough to use descriptive local vars?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 5 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: yes that is true for primaries not necessarily for replicas. The replicas might not be a light recovery

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 6 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: ok fair enough

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 5 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: For replicas, we do not reach this point in the code (they are covered above by peer recovery and are checked against currentInRecoveries and primaryNodeOutRecoveries).

Are you in favour of activating this code? I will then also have to modify the calculation of `incomingRecoveries` in `RoutingNodes` to make sure that these are not counted as recoveries.

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: no I think not here but I wonder why it's commeted out? can we remove it?

**Comment by s1monw** [comment]
LGTM would just love some doc strings on the allocation decider what each condition means

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java [hunk 7]
```diff
@@ -141,41 +141,43 @@ private void removeRecovery(ShardRouting routing) {
...
-        addRecovery(routing, true, routingTable);
+    private void addInitialRecovery(ShardRouting routing, ShardRouting initialPrimaryShard) {
+        addRecovery(routing, true, initialPrimaryShard);
     }
 
-    private void addRecovery(final ShardRouting routing, final boolean increment, final RoutingTable routingTable) {
+    private void addRecovery(final ShardRouting routing, final boolean increment, final ShardRouting initialPrimaryShard) {
         final int howMany = increment ? 1 : -1;
         assert routing.initializing() : "routing must be initializing: " + routing;
+        assert initialPrimaryShard == null || initialPrimaryShard.assignedToNode() :
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: can we add a check that the primary is active?

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: I had that one originally there. But this fails some tests currently as we don't always add the ReplicaAfterPrimaryActiveAllocationDecider to the list of deciders in these tests. As this impacts more than a few places, I decided against tackling that one in this PR.

**Comment by ywelsch** [comment]
@s1monw I've added a method in 0d1fc7635fdb786756acb920a9553bb8ce8e0676 that helps with documenting the two cases. It shows that the if/else branching is determined by whether we are going to have a peer recovery or not.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java [hunk 8]
```diff
@@ -109,50 +112,83 @@ private void setPrimariesInitialRecoveries(int primariesInitialRecoveries) {
...
+            // Allocating a shard to this node will increase the incoming recoveries
+            int currentInRecoveries = allocation.routingNodes().getIncomingRecoveries(node.nodeId());
+            if (currentInRecoveries >= concurrentIncomingRecoveries) {
+                return allocation.decision(THROTTLE, NAME, "too many incoming shards are currently recovering [%d], limit: [%d]",
+                    currentInRecoveries, concurrentIncomingRecoveries);
+            } else {
+                // search for corresponding recovery source (= primary shard) and check number of outgoing recoveries on that node
+                ShardRouting primaryShard = allocation.routingNodes().activePrimary(shardRouting.shardId());
+                if (primaryShard == null) {
+                    return allocation.decision(Decision.NO, NAME, "primary shard for this replica is not yet active");
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: hm... this effectively makes ReplicaAfterPrimaryActiveAllocationDecider irelevant , right?

**Comment by s1monw** [comment]
great thanks!  LGTM

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java [hunk 9]
```diff
@@ -109,50 +112,83 @@ private void setPrimariesInitialRecoveries(int primariesInitialRecoveries) {
...
+                    primariesInRecovery, primariesInitialRecoveries);
+            } else {
+                return allocation.decision(YES, NAME, "below primary recovery limit of [%d]", primariesInitialRecoveries);
+            }
+        } else {
+            // Peer recovery
+            assert initializingShard(shardRouting, node.nodeId()).isPeerRecovery();
+
+            // Allocating a shard to this node will increase the incoming recoveries
+            int currentInRecoveries = allocation.routingNodes().getIncomingRecoveries(node.nodeId());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: question - do routing nodes always reflect the current state of affairs? if the balancer makes multiple decision about multiple shards , are these all reflected in routing nodes?

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java (hunk 7 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: Ok fair enough. can you leave a comment?

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java [hunk 10]
```diff
@@ -141,41 +141,43 @@ private void removeRecovery(ShardRouting routing) {
...
         Recoveries.getOrAdd(recoveriesPerNode, routing.currentNodeId()).addIncoming(howMany);
-        final String sourceNodeId;
-        if (routing.relocatingNodeId() != null) { // this is a relocation-target
-            sourceNodeId = routing.relocatingNodeId();
-            if (routing.primary() && increment == false) { // primary is done relocating
+
+        if (routing.isPeerRecovery()) {
+            // add/remove corresponding outgoing recovery on node with primary shard
+            final ShardRouting primary;
+            if (initialPrimaryShard != null) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: nit: can we move the look up of the primary to the callers that pass null? this method is hairy enough :)

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 8 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: This duplicates indeed the `ReplicaAfterPrimaryActiveAllocationDecider` but checks the property only after we have checked the number of incoming recoveries. I can collapse both so that the check happens before checking incoming recoveries. WDYT?

File: core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java [hunk 11]
```diff
@@ -141,41 +141,43 @@ private void removeRecovery(ShardRouting routing) {
...
     }
 
-    private void addInitialRecovery(ShardRouting routing, RoutingTable routingTable) {
-        addRecovery(routing, true, routingTable);
+    private void addInitialRecovery(ShardRouting routing, ShardRouting initialPrimaryShard) {
+        addRecovery(routing, true, initialPrimaryShard);
     }
 
-    private void addRecovery(final ShardRouting routing, final boolean increment, final RoutingTable routingTable) {
+    private void addRecovery(final ShardRouting routing, final boolean increment, final ShardRouting initialPrimaryShard) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java]: nit: I initially go confused by the method name `addRecovery` as it used to update the recovery counters for both addition and removal. maybe call it updateRecoveryCounts ?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 9 above)
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: yes, routing nodes always reflect the current state to which the balancer has committed. The balancer first commits to a decision before trying to allocate another shard.

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java (hunk 8 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java]: Yeah, I think we can collapse both deciders into one here - it will make things simpler. Call it RecoveriesAllocationDecider that is incharge of all recovering shards (replicas and relocating primaries). It's good to do it in a different PR imo..

**Comment by bleskes** [comment]
LGTM2 . left some very minor and optional suggestions.

**Comment by ywelsch** [comment]
@bleskes I've added your suggestions and will do a follow-up to merge ThrottlingAllocatonDecider with ReplicaAfterPrimaryActiveAllocationDecider. @s1monw @bleskes thanks for the reviews.
