### PR TITLE
Fix SnapshotRetentionConfigurationTests

### LINKED ISSUE #101583: [CI] SnapshotRetentionConfigurationTests testMaximum failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/5o5t5vmxnhh54/tests/:x-pack:plugin:core:test/org.elasticsearch.xpack.core.slm.SnapshotRetentionConfigurationTests/testMaximum
**Reproduction line:**
```
./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.slm.SnapshotRetentionConfigurationTests.testMaximum" -Dtests.seed=55ACF6BCA4F8280E -Dtests.locale=pt-PT -Dtests.timezone=Navajo -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.11

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.core.slm.SnapshotRetentionConfigurationTests&tests.test=testMaximum

**Failure excerpt:**
```
java.lang.IllegalStateException: Duplicate key snap-lkg/uuid (attempted merging values org.elasticsearch.repositories.RepositoryData$SnapshotDetails@2b9bea90 and org.elasticsearch.repositories.RepositoryData$SnapshotDetails@2b9c19ca)

  at __randomizedtesting.SeedInfo.seed([55ACF6BCA4F8280E:84EC025013DCDD07]:0)
  at java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
  at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
  at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  at org.elasticsearch.xpack.core.slm.SnapshotRetentionConfigurationTests.detailsMap(SnapshotRetentionConfigurationTests.java:52)
  at org.elasticsearch.xpack.core.slm.SnapshotRetentionConfigurationTests.testMaximum(SnapshotRetentionConfigurationTests.java:116)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by idegtiarenko**
The test failure happens as we choose same ids with `"snap-" + randomAlphaOfLength(3)`. This change uses UUID for ids to minimize the change of collisions.

Closes: https://github.com/elastic/elasticsearch/issues/101583

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/slm/SnapshotRetentionConfigurationTests.java [hunk 1]
```diff
@@ -313,7 +313,7 @@ private SnapshotInfo makeInfo(long startTime) {
         meta.put(SnapshotsService.POLICY_ID_METADATA_FIELD, REPO);
         final int totalShards = between(1, 20);
         SnapshotInfo snapInfo = new SnapshotInfo(
-            new Snapshot(REPO, new SnapshotId("snap-" + randomAlphaOfLength(3), "uuid")),
+            new Snapshot(REPO, new SnapshotId("snap-" + randomUUID(), "uuid")),
```
Comment (idegtiarenko) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/slm/SnapshotRetentionConfigurationTests.java:316]: `randomAlphaOfLength(3)` was introduced in https://github.com/elastic/elasticsearch/pull/46407
I am surprised we have never seen this before for such a long time

**Review by DaveCTurner — APPROVED** [review]
LGTM but also do you think we should add a `toString()` to `SnapshotDetails`?

```
java.lang.IllegalStateException: Duplicate key snap-lkg/uuid (attempted merging values org.elasticsearch.repositories.RepositoryData$SnapshotDetails@2b9bea90 and org.elasticsearch.repositories.RepositoryData$SnapshotDetails@2b9c19ca)
```

Also why a UUID and not `randomIdentifier()`?

**Comment by idegtiarenko** [comment]
> but also do you think we should add a toString() to SnapshotDetails?

Yeah, I could add that

> Also why a UUID and not randomIdentifier()?

This test relies on generating up to 9 unique identifiers without using `randomValueOtherThan(...)`.
`randomIdentifier()` generates 8-12 askii characters with `AsciiLettersGenerator` (actually limited only to English characters). I believe random UUID could have way more random values and there less chance of collisions.
