### PR TITLE
Fixed date math expression support in multi get requests.

### LINKED ISSUE #17957: Get and MultiGet inconsistency with date math expressions
When using index name date math expressions `<logstash-{now/M}>`, the Get API works and is able to resolve the index. However, if you try to get the same value using the MultiGet API it fails as it treats the index name as a concrete index name rather than allowing for the possibility that it could be an expression. I think the behavior of the APIs should be consistent.

I tend to question the usefulness of the date math expression in a get request. I could see one scenario where you know the id of a document (the id is consistent) and want to get the "current" one using a date math expression.

### PR DESCRIPTION
**Pull request by qwerty4030**
Fixed date math expression support in multi get requests.
Date math index/alias expressions in `mget` will now be resolved to a concrete single index instead of failing the mget item with a `IndexNotFoundException`.
Note `mget` uses the same `IndicesOptions` as `get`; which prevents the expression from resolving to multiple indices (i.e. wilcards).
Added integration test to verify multi index aliases do not fail the entire mget request.

Closes #17957

### CODE REVIEW

**Comment by clintongormley** [comment]
@javanna please could you take a look

File: core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java [hunk 1]
```diff
@@ -64,12 +64,16 @@ protected void doExecute(final MultiGetRequest request, final ActionListener<Mul
...
         for (int i = 0; i < request.items.size(); i++) {
             MultiGetRequest.Item item = request.items.get(i);
-            if (!clusterState.metaData().hasConcreteIndex(item.index())) {
-                responses.set(i, new MultiGetItemResponse(null, new MultiGetResponse.Failure(item.index(), item.type(), item.id(), new IndexNotFoundException(item.index()))));
+            String concreteSingleIndex;
+            try {
+                // need to resolve date math index expressions. IndicesOptions do not expand wildcards; therefore this method must return
+                // a single index or throw an IndexNotFoundException.
+                concreteSingleIndex = indexNameExpressionResolver.concreteSingleIndex(clusterState, item).getName();
+            } catch (IndexNotFoundException infe) {
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java]: I think catching index not found only is not enough. Other exceptions can be thrown while resolving indices. If you change this to `Exception`, you would also fix #20845 I think. Would you mind  doing that and adding a small test for that to `SimpleMgetIT` ?

File: core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java [hunk 2]
```diff
@@ -64,12 +64,16 @@ protected void doExecute(final MultiGetRequest request, final ActionListener<Mul
         Map<ShardId, MultiGetShardRequest> shardRequests = new HashMap<>();
         for (int i = 0; i < request.items.size(); i++) {
             MultiGetRequest.Item item = request.items.get(i);
-            if (!clusterState.metaData().hasConcreteIndex(item.index())) {
-                responses.set(i, new MultiGetItemResponse(null, new MultiGetResponse.Failure(item.index(), item.type(), item.id(), new IndexNotFoundException(item.index()))));
+            String concreteSingleIndex;
+            try {
+                // need to resolve date math index expressions. IndicesOptions do not expand wildcards; therefore this method must return
+                // a single index or throw an IndexNotFoundException.
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java]: as mentioned below, this comment is not 100% correct. Other exceptions could be thrown. I am thinking we could even drop the comment, not sure what value it adds. Thoughts?

**Review by javanna — CHANGES_REQUESTED** [review]
I have reviewed this, it looks good, left a couple of minor comments. Would you mind addressing those please?

**Comment by tlrx** [comment]
@qwerty4030 I'm afraid I fixed a similar issue before I saw your pull request. Would you mind to rebase this again? That would be nice to have your tests in too.

File: core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java (hunk 1 above)
Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java]: Agreed. Good catch with the multi index aliases. Another possible exception is `ElasticsearchParseException` when parsing the date math expression.

**Comment by qwerty4030** [comment]
@javanna @tlrx made some changes and rebased on latest master. Thanks!

File: core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java [hunk 3]
```diff
@@ -64,26 +64,21 @@ protected void doExecute(final MultiGetRequest request, final ActionListener<Mul
...
                 responses.set(i, newItemFailure(item.index(), item.type(), item.id(), e));
                 continue;
             }
 
+            item.routing(clusterState.metaData().resolveIndexRouting(item.parent(), item.routing(), concreteSingleIndex));
+            if ((item.routing() == null) && (clusterState.getMetaData().routingRequired(concreteSingleIndex, item.type()))) {
+                String message = "routing is required for [" + concreteSingleIndex + "]/[" + item.type() + "]/[" + item.id() + "]";
+                responses.set(i, newItemFailure(concreteSingleIndex, item.type(), item.id(), new IllegalArgumentException(message)));
+                continue;
+            }
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java]: can you move this block back within the try catch please? `resolveIndexRouting` may throw exceptions too, and we don't want those to fail the whole request. Maybe we can then just throw exception from within the if.  See https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/MetaData.java#L414 . Maybe we should write a test for this too :) (if you are up for it).

File: core/src/test/java/org/elasticsearch/mget/SimpleMgetIT.java [hunk 4]
```diff
@@ -73,8 +75,35 @@ public void testThatMgetShouldWorkWithOneIndexMissing() throws IOException {
...
+        assertAcked(prepareCreate("test").addAlias(new Alias("multiIndexAlias")));
+        assertAcked(prepareCreate("test2").addAlias(new Alias("multiIndexAlias")));
+
+        client().prepareIndex("test", "test", "1").setSource(jsonBuilder().startObject().field("foo", "bar").endObject())
+            .setRefreshPolicy(IMMEDIATE).get();
 
+        MultiGetResponse mgetResponse = client().prepareMultiGet()
+            .add(new MultiGetRequest.Item("test", "test", "1"))
+            .add(new MultiGetRequest.Item("multiIndexAlias", "test", "1"))
+            .execute().actionGet();
```
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/mget/SimpleMgetIT.java]: Can you use `.get()` instead of `.execute().actionGet();`?

**Review by javanna — CHANGES_REQUESTED** [review]
I had another look, left a small comment, thanks for addressing the previous comments!

File: core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java (hunk 3 above)
Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java]: I was looking at that code as well, but I don't think it will reach that line. Since the `aliasOrIndex` parameter can only be a concrete index the code should return on this line? https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/MetaData.java#L405

I can move that code into the try catch if we want to be defensive. Perhaps its better to move everything in that for loop into the try catch?

Another question: is it possible for an index to be deleted (or some other cluster change) while the code is inside that loop? For example when `indexNameExpressionResolver.concreteSingleIndex` is called the index exists, but when it gets down to `ShardId shardId =....` the index has been deleted?
Thanks

File: core/src/test/java/org/elasticsearch/mget/SimpleMgetIT.java (hunk 4 above)
Comment (qwerty4030) [inline core/src/test/java/org/elasticsearch/mget/SimpleMgetIT.java]: Done.

File: core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java (hunk 3 above)
Comment (qwerty4030) [inline core/src/main/java/org/elasticsearch/action/get/TransportMultiGetAction.java]: Got it, just pushed the change. I think that exception in the routing code is checking for a multi index alias, so that should be covered in the test `SimpleMgetIT#testThatMgetShouldWorkWithMultiIndexAlias`. However I'm pretty sure it wont actually reach that code since `indexNameExpressionResolver` will throw an exception before.
Thanks for the review!

**Review by javanna — APPROVED** [review]
thanks @qwerty4030 LGTM
