### PR TITLE
Fix Netty4ChunkedContinuationsIT#testClientCancellation

### LINKED ISSUE #109866: [CI] Netty4ChunkedContinuationsIT testClientCancellation failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/zhb267ofcjjri/tests/:modules:transport-netty4:internalClusterTest/org.elasticsearch.http.netty4.Netty4ChunkedContinuationsIT/testClientCancellation

**Reproduction line:**
```
./gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.http.netty4.Netty4ChunkedContinuationsIT.testClientCancellation" -Dtests.seed=807E1EDDAD56E65 -Dtests.locale=da -Dtests.timezone=Africa/Lusaka -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.http.netty4.Netty4ChunkedContinuationsIT#testClientCancellation`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testClientCancellation'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.http.netty4.Netty4ChunkedContinuationsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: safeAwait: CountDownLatch did not reach zero within the timeout

  at __randomizedtesting.SeedInfo.seed([807E1EDDAD56E65:8A6F7F7D5B5C44F4]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.assertTrue(Assert.java:42)
  at org.elasticsearch.test.ESTestCase.safeAwait(ESTestCase.java:2203)
  at org.elasticsearch.http.netty4.Netty4ChunkedContinuationsIT.lambda$withResourceTracker$4(Netty4ChunkedContinuationsIT.java:323)
  at org.elasticsearch.http.netty4.Netty4ChunkedContinuationsIT.testClientCancellation(Netty4ChunkedContinuationsIT.java:313)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

### PR DESCRIPTION
**Pull request by nicktindall**
Closes #109866

`testClientCancellation` had an issue where the test could fail if the cancellation happened before the mock action returned its response. This change tightens up the assertions to ensure that in the event we do create a chunked response, we eventually close it.

### CODE REVIEW

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java [hunk 1]
```diff
@@ -316,13 +317,14 @@ public void onFailure(Exception exception) {
...
         final var latch = new CountDownLatch(1);
-        refs = AbstractRefCounted.of(latch::countDown);
+        refs = LeakTracker.wrap(AbstractRefCounted.of(latch::countDown));
         return () -> {
             refs.decRef();
             try {
                 safeAwait(latch);
             } finally {
                 refs = null;
+                System.gc();
```
Comment (nicktindall) [inline modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java:327]: This should make a failure a lot easier to troubleshoot in the future?

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java [hunk 2]
```diff
@@ -283,13 +283,13 @@ private void finishChunkedWrite() {
...
-                                        finishingWrite.onDone() // pass the terminal listener/promise along the line
-                                    )
+                            channel.eventLoop().execute(() -> {
+                                channel.writeAndFlush(
+                                    new Netty4ChunkedHttpContinuation(writeSequence, continuation, finishingWrite.combiner()),
+                                    finishingWrite.onDone() // pass the terminal listener/promise along the line
                                 );
+                                checkShutdown();
+                            });
                             checkShutdown();
```
Comment (nicktindall) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java:293]: I've so far been unable to reproduce the issue locally or on a CI-replica server, but it looks like the flakiness began after 0a008ed71dfe53f0ce8c15129f773539e329aa8e was merged.

It changed this block from:
https://github.com/elastic/elasticsearch/blob/683245e41e5be562dd7e9bdafe80a627d9edb992/modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java#L277-L283

to:
https://github.com/elastic/elasticsearch/blob/0a008ed71dfe53f0ce8c15129f773539e329aa8e/modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java#L283-L294

So the call to `checkShutdown` ensures that `finishingWrite.onDone()` is completed if the event loop shuts down after we make the call to `execute(...)`, but there's no such guarantee after the call to `channel.writeAndFlush(...)` that happens sometime later. I believe we have `safeWriteAndFlush` as an option here, but it would have meant wrapping `finishingWrite.onDone()` in an `ActionListener`.

Comment (ywangd) [reply modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java:293]: I spent sometime looking into this. I feel this is the right change. But I am also in a similar situation that I am not sure whether the Netty bug (https://github.com/netty/netty/issues/8007) is still relevant now that `channel.writeAndFlush` is always invoked within the eventloop. Maybe the bug can still happen? In that case, this would be the right fix.

Shorting of being certain, we synced and agreed to separate the additional tracking changes to test code out so that they can be reviewed and merged which will give us more debug info when it fails again.

**Comment by nicktindall** [comment]
Raised #110175 in the hope that it might provide more info about the failure and validate the theory

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java (hunk 2 above)
Comment (nicktindall) [reply modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java]: It turns out this theory was incorrect.

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java [hunk 3]
```diff
@@ -643,10 +643,10 @@ public void close() {
 
                             @Override
                             public void accept(RestChannel channel) {
-                                localRefs.mustIncRef();
                                 client.execute(TYPE, new Request(), new RestActionListener<>(channel) {
                                     @Override
                                     protected void processResponse(Response response) {
+                                        localRefs.mustIncRef();
```
Comment (nicktindall) [inline modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java:649]: After looking at a failed build scan with the logging turned on, it became apparent that the unbalanced sequence of events went like (most recent first):

1. BaseRestHandler closing the RestChannelConsumer (decRef)
	- at `Netty4ChunkedContinuationsIT:641`
2. Closing the resource tracker (decRef)
	- at `Netty4ChunkedContinuationsIT:324`
3. RestChannelConsumer.accept (incRef)
	- at `Netty4ChunkedContinuationsIT:646`
4. prepareRequest (incRef)
	- at `Netty4ChunkedContinuationsIT:637`
5. created (incRef implicit)
	- at `Netty4ChunkedContinuationsIT.java:322`

Which suggests to me the following sequence of events:
1. `RestChannelConsumer.accept` is called (and `mustIncRef` is called)
2. `TransportInfiniteContinuationsAction.doExecute` is called and schedules the return of the chunked response
3. The request is cancelled, the channel is closed
4. The chunked response is returned, `RestActionListener#onResponse` fails in the call to `#ensureOpen()` and ends up calling `RestActionListener#onFailure` instead of `RestActionListener#processResponse` so the `decRef` on line 655 is never called, and we have our inbalance.

### Options for fixing
If we move the `mustIncRef` such that it only occurs when we receive the `InfiniteContinuationsPlugin.Response` from the action (as above), the test shouldn't be susceptible to such a failure, but it does indicate that the `Response` object can be created but never closed. I'm not sure if this is an actual bug. `Response` type parameter doesn't have any type constraints in `RestActionListener` so it's not necessarily `Releasable`. I'm not clear on what the contract is here.

Comment (nicktindall) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java:649]: I think the new positioning of `mustIncRef` is OK, because instead of

"if we accepted the request" -> "then we close the chunked response"

we now assert

"if we created the chunked response" -> "then we close the chunked response"

But I may have missed something.

Comment (nicktindall) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java:649]: The other plugins (`YieldsContinuationsPlugin` at least) seem to have the same issue, but I guess it doesn't trigger because we wait for the request to complete when calling those.

Comment (ywangd) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java:649]: Good job on tracking this down. I can confirm the test can fail with following diff
```diff
--- a/modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java
+++ b/modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java
@@ -645,6 +645,12 @@ public class Netty4ChunkedContinuationsIT extends ESNetty4IntegTestCase {
                             public void accept(RestChannel channel) {
                                 localRefs.mustIncRef();
                                 client.execute(TYPE, new Request(), new RestActionListener<>(channel) {
+                                    @Override
+                                    protected void ensureOpen() {
+                                        safeSleep(500);
+                                        super.ensureOpen();
+                                    }
+
                                     @Override
                                     protected void processResponse(Response response) {
                                         channel.sendResponse(RestResponse.chunked(RestStatus.OK, response.getResponseBodyPart(), () -> {
```

I think this is the right fix we are doing the same thing in other `RestActionListener` [implementation](https://github.com/elastic/elasticsearch/blob/f0afd9165064edf9d3e18a5b960e57bf96de71f2/server/src/main/java/org/elasticsearch/rest/action/RestChunkedToXContentListener.java#L44). 👍

**Review by ywangd — APPROVED** [review]
LGTM 👍

**Comment by ywangd** [comment]
Btw, maybe it's worth to update the PR description now that you got new findings and fix. Thanks!

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java (hunk 3 above)
Comment (DaveCTurner) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4ChunkedContinuationsIT.java:649]: Good catch, the analysis looks right to me. However I would still prefer that we didn't just leak the response listener in this case, that's not how production code should behave, and we should be able to assert that it's always completed. I opened https://github.com/elastic/elasticsearch/pull/110309 with an alternative fix which I would prefer.

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java (hunk 2 above)
Comment (DaveCTurner) [reply modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java]: Yes, I believe if we're already on the event loop and we enqueue another task then that task will also execute before shutdown -- shutdown only happens once the task queue is completely drained. See e.g. how `io.netty.util.concurrent.SingleThreadEventExecutor#confirmShutdown` keeps on returning `false` while there are more tasks to run. I suspect if this were not true then we'd have to deal with it in lots more places than just this.
