### PR TITLE
Call the new _estimate_memory_usage API endpoint on df analytics _start

### LINKED ISSUE #45544: Memory usage estimation process finishes with error.
When memory usage estimation API is called with model_memory_limit set to a low value, the following error is returned by the process:
```
Input error: memory limit 0.89MB is too low to perform analysis. You need to give the process at least 4MB, but preferably more.
```

This failure is a combination of 2 factors:
1. computeAndSaveExecutionStrategy method that validates the model memory limit condition is invoked as part of CDataFrameAnalysisRunner initialization:
https://github.com/elastic/ml-cpp/blob/master/lib/api/CDataFrameAnalysisRunner.cc#L201
2. the model memory limit in memory usage estimation request is always set to 1MB

There are 2 solutions I see:
[simple] send large model memory limit in memory usage estimation request so that the validation passes
[more involved] do not call computeAndSaveExecutionStrategy method at all in memory usage estimation process

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR integrates the new _estimate_memory_usage API endpoint into df analytics.
_estimate_memory_usage is called early during df analytics _start in order to detect whether user-provided model memory limit is sufficient taking into account memory usage estimation. If not, error is thrown and the user can retry the request with different (higher) value of model_memory_limit.

Relates https://github.com/elastic/elasticsearch/issues/44699
Closes https://github.com/elastic/elasticsearch/issues/45544

### CODE REVIEW

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java [hunk 1]
```diff
@@ -169,11 +170,37 @@ public void onFailure(Exception e) {
         );
 
         // Tell the job tracker to refresh the memory requirement for this job and all other jobs that have persistent tasks
+        ActionListener<EstimateMemoryUsageAction.Response> estimateMemoryUsageListener = ActionListener.wrap(
+            estimateMemoryUsageResponse -> {
+                // Validate that model memory limit is sufficient to run the analysis
+                if (configHolder.get().getModelMemoryLimit()
+                    .compareTo(estimateMemoryUsageResponse.getExpectedMemoryUsageWithOnePartition()) < 0) {
+                    ElasticsearchStatusException e =
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Use `org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException()`

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java [hunk 2]
```diff
@@ -169,11 +170,37 @@ public void onFailure(Exception e) {
...
+                        new ElasticsearchStatusException(
+                            "Cannot start data frame analytics [" + request.getId() + "] because the configured memory limit [" +
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Usually we do not report the name of the resource here because it is a direct response to the API call and the user will be in the context to know which API failed for which resource. We could shorten to:

```
Cannot start because the configured memory...
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/MemoryUsageEstimationProcessManager.java [hunk 3]
```diff
@@ -66,7 +67,9 @@ private MemoryUsageEstimationResult runJob(String jobId,
             new AnalyticsProcessConfig(
                 dataSummary.rows,
                 dataSummary.cols,
-                DataFrameAnalyticsConfig.MIN_MODEL_MEMORY_LIMIT,
+                // For memory estimation the model memory limit here should be set high enough not to trigger an error when C++ code
+                // compares the limit to the result of estimation.
+                new ByteSizeValue(1, ByteSizeUnit.TB),
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/MemoryUsageEstimationProcessManager.java]: Unless there is a side-effect, I wonder if we should make this even larger. The era of `1 TB` RAMs is around the corner :-)

**Review by dimitris-athanasiou — COMMENTED** [review]
Looks good! Left a few minor comments

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Done.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java (hunk 2 above)
Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Done.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/MemoryUsageEstimationProcessManager.java (hunk 3 above)
Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/MemoryUsageEstimationProcessManager.java]: Done.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java [hunk 4]
```diff
@@ -176,10 +176,9 @@ public void onFailure(Exception e) {
                 if (configHolder.get().getModelMemoryLimit()
                     .compareTo(estimateMemoryUsageResponse.getExpectedMemoryUsageWithOnePartition()) < 0) {
                     ElasticsearchStatusException e =
-                        new ElasticsearchStatusException(
-                            "Cannot start data frame analytics [" + request.getId() + "] because the configured memory limit [" +
-                                configHolder.get().getModelMemoryLimit() + "] is smaller than the expected memory usage [" +
-                                estimateMemoryUsageResponse.getExpectedMemoryUsageWithOnePartition() + "].", RestStatus.BAD_REQUEST);
+                        ExceptionsHelper.badRequestException(
+                            "Cannot start because the configured model memory limit [{}] is lower than the expected memory usage [{}].",
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: nit: remove dot at the end of the message

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java (hunk 4 above)
Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Done.

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1
