### PR TITLE
Align handling of interrupts in BulkProcessor

### LINKED ISSUE #14833: Align handling of interrupts in BulkProcessor
### Background

In #14799, I've spotted that `BulkProcessor` does not handle `InterruptedException` properly. `InterruptedException` is the standard Java facility to request cancellation of an ongoing operation in another thread.

After some discussion (see #14799), we've decided to move the change to the client API to a dedicated ticket for documentation purposes as this change also interferes with the retry feature in the `BulkProcessor` (see #14620).

### Current Situation

There are two code paths in `BulkProcessor`, one for handling bulk requests in a blocking fashion (`concurrentRequests == 0` when constructing `BulkProcessor`)  and one that allows for concurrent bulk requests from the same client. Both handle interruption differently, the latter does it also wrong (by calling `Thread.interrupted` instead of `Thread.currentThread().interrupt()`).

### Desired Situation

Both code paths respond to interruption in a well-defined, documented and ideally consistent way (i.e. both either throw `InterruptedException` or restore the interrupt flag).

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we implement a cancellation policy in
BulkProcessor which is aligned for the sync and the async case
and also document it.

Closes #14833.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java [hunk 1]
```diff
@@ -61,6 +61,9 @@
 
         /**
          * Callback after a failed execution of bulk request.
+         *
+         * Note that in case an instance of <code>InterruptedException</code> is passed, which means that request processing has been
+         * cancelled externally, the thread's interruption status has to be restored prior to calling this method.
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java]: s/has to be/has been/

**Comment by danielmitterdorfer** [comment]
Thanks! Merged.
