### PR TITLE
Catch and wrap AssertionError and NoClassDefFoundError in groovy scripts

### LINKED ISSUE #19806: Groovy assert misses StringBuffer
**Elasticsearch version**:
5.0.0-alpha4

**JVM version**:
Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_101/25.101-b13

**OS version**:
Linux 107r01pc 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
In a groovy scripted update asserting while referencing variables and specifying a message will cause a class not found exception.

**Steps to reproduce**:
 1. on a clean elasticsearch enable scripting
 2. run some curl commands, see below
 3. observe the results

**Various commands**:
 1. `curl -XPOST 'http://localhost:9200/a/a/a/_update' -d '{"scripted_upsert": true, "script": {"inline": "assert false, \"foo\";"}, "upsert": {}}'`
  * `{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[Vertigo][127.0.0.1:9300][indices:data/write/update[s]]"}],"type":"illegal_argument_exception","reason":"failed to execute script","caused_by":{"type":"script_exception","reason":"Error evaluating assert false, \"foo\";","caused_by":{"type":"assertion_error","reason":"foo. Expression: false"},"script_stack":[],"script":"","lang":"groovy"}},"status":400}`
 2. `curl -XPOST 'http://localhost:9200/a/a/b/_update' -d '{"scripted_upsert": true, "script": {"inline": "def bar=false; assert bar, \"foo\";"}, "upsert": {}}'`
  * `{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[Vertigo][127.0.0.1:9300][indices:data/write/update[s]]"}],"type":"illegal_argument_exception","reason":"failed to execute script","caused_by":{"type":"script_exception","reason":"Error evaluating def bar=false; assert bar, \"foo\";","caused_by":{"type":"no_class_def_found_error","reason":"java/lang/StringBuffer"},"script_stack":[],"script":"","lang":"groovy"}},"status":400}`
 3. `curl -XPOST 'http://localhost:9200/a/a/b/_update' -d '{"scripted_upsert": true, "script": {"inline": "def bar=false; assert bar;"}, "upsert": {}}'`
  * `{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[Vertigo][127.0.0.1:9300][indices:data/write/update[s]]"}],"type":"illegal_argument_exception","reason":"failed to execute script","caused_by":{"type":"script_exception","reason":"Error evaluating def bar=false; assert bar;","caused_by":{"type":"power_assertion_error","reason":"assert bar\n       |\n       false"},"script_stack":[],"script":"","lang":"groovy"}},"status":400}`

Somewhat more clearly:
 1. using `assert false, "message"` works as expected
 2. using `assert var, "message"` throws a class not found exception somewhere down the stack
 3. using `assert var` works as expected

I've tried this on a more recent snapshot (34bb1508637368c43b792992646a612bb8022e99) and the assert shows up in the log, but curl never prints anything nor exists, as if no response is generated.
This is the log:
```
[2016-08-04 18:07:53,886][ERROR][bootstrap                ] [] fatal error in thread [elasticsearch[0ZFv9t-][index][T#1]], exiting
java.lang.AssertionError: foo. Expression: false
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:404)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
	at 20a61a940854553b62db2cfb00cb1511e91aac90.run(20a61a940854553b62db2cfb00cb1511e91aac90:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:295)
	at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:253)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:103)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:80)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:179)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:172)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:69)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:247)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:243)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:517)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:510)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception: java.security.AccessControlException thrown from the UncaughtExceptionHandler in thread "elasticsearch[0ZFv9t-][index][T#1]"
```

### PR DESCRIPTION
**Pull request by dakrone**
Previously, we only caught subclasses of Exception, however, there are
some cases when Errors are thrown instead of Exceptions. These two cases
are `assert` and when a class cannot be found.

Without this change, the exception would bubble up to the
`uncaughtExceptionHandler`, which would in turn, exit the JVM
(related: #19923).

A note of difference between regular Java asserts and Groovy asserts,
from http://docs.groovy-lang.org/docs/latest/html/documentation/core-testing-guide.html

"Another important difference from Java is that in Groovy assertions are
enabled by default. It has been a language design decision to remove the
possibility to deactivate assertions."

In the event that a user uses an assert such as:

``` groovy
def bar=false; assert bar, "message";
```

The GroovyScriptEngineService throws a NoClassDefFoundError being unable
to find the `java.lang.StringBuffer` class. It is _highly_ recommended
that any Groovy scripting user switch to using regular exceptions rather
than unconfigurable Groovy assertions.

Resolves #19806

### CODE REVIEW

**Comment by nik9000** [comment]
As much as I don't like catching java's `AssertionError` to catch a groovy feature, it looks like that is required or we'll exit the JVM on fairly innocuous errors in user scripts.

LGTM

**Comment by nik9000** [comment]
Do we need the same protection in the other language plugins? Probably not painless, but lang-javascript and lang-python might need it.

File: modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java [hunk 1]
```diff
@@ -293,7 +293,7 @@ public Object run() {
                 // NOTE: we truncate the stack because IndyInterface has security issue (needs getClassLoader)
                 // we don't do a security check just as a tradeoff, it cannot really escalate to anything.
                 return AccessController.doPrivileged((PrivilegedAction<Object>) script::run);
-            } catch (Exception e) {
+            } catch (Exception | AssertionError | NoClassDefFoundError e) { // Groovy asserts are not java asserts, and cannot be disabled
```
Comment (jasontedor) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: I think we should inspect the `AssertionError` and make sure that it comes from Groovy (by inspecting the stack trace and looking for `assertFailed` and other relevant Groovy calls).

**Comment by rmuir** [comment]
Also why not simply add StringBuffer for groovy if it makes its assert work?

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/script/ClassPermission.java#L79

The list is very simple: based on the old groovy sandbox, but that sandbox was not really "working" as well, for example `java.lang.String` was never whitelisted, yet it worked, because that mechanism was swiss-cheese.

So we may have to add classes like stringbuilder/buffer or other things.

**Comment by nik9000** [comment]
> why not simply add StringBuffer for groovy if it makes its assert work?

We may want to add those classes too, but we need something like that so that other asserts floating around groovy don't shoot the JVM. We also don't want asserts users write to shoot the jvm, or any time they call Class.forName somehow.

**Comment by rmuir** [comment]
Yes: I agree the two things are ... somewhat unrelated. But this is tied to the issue there, and adds a test that groovy's `assert` throws NoClassDefFoundError, which i really don't think needs to happen.

File: modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java [hunk 2]
```diff
@@ -123,6 +123,12 @@ public void testEvilGroovyScripts() throws Exception {
         }
     }
 
+    public void testGroovyScriptsThatThrowErrors() throws Exception {
+        assertFailure("assert false, \"msg\";", AssertionError.class);
+        assertFailure("def foo=false; assert foo;", AssertionError.class);
+        assertFailure("def bar=false; assert bar, \"msg2\"", NoClassDefFoundError.class);
```
Comment (jasontedor) [inline modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java]: I guess this is because we are not granting the class permission for `StringBuffer` but I think we should?

**Comment by dakrone** [comment]
> Also why not simply add StringBuffer for groovy if it makes its assert work?

I can certainly add StringBuffer, however, that isn't the only class required to get groovy asserts to work, it also needs `org.codehaus.groovy.runtime.InvokerHelper`, which I think looks dangerous to add. I wish I could disable groovy's asserts entirely :-/

**Comment by rmuir** [comment]
yes, lets leave that one out of it, serialization/reflection/etc, its not a good guy. Thanks for checking.

File: modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java (hunk 2 above)
Comment (dakrone) [inline modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java]: Sure, I added the permissions for that (StringBuffer)

File: modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java (hunk 1 above)
Comment (dakrone) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: Okay, I added a check for this, and a comment explaining why

File: modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java (hunk 2 above)
Comment (jasontedor) [inline modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java]: Sure, but that was before we knew that we would need to add a permission for `InvokeHelper` too? So maybe we should just not add it since it will not help with getting asserts to work? Sorry.

File: modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java [hunk 3]
```diff
@@ -123,6 +123,13 @@ public void testEvilGroovyScripts() throws Exception {
         }
     }
 
+    public void testGroovyScriptsThatThrowErrors() throws Exception {
+        assertFailure("assert false, \"msg\";", AssertionError.class);
+        assertFailure("def foo=false; assert foo;", AssertionError.class);
```
Comment (nik9000) [inline modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java]: For extra super paranoia's sake can you add a test that throws NoClassDefFoundError so we have something independent that checks that user scripts that do that don't halt the jvm?

Comment (dakrone) [inline modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java]: In order to do that, we have to add permissions for the `java.lang.NoClassDefFoundError` in ClassPermission.java. Are we sure we want to add permissions for that class only to add a test case?

File: modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java [hunk 4]
```diff
@@ -293,10 +293,20 @@ public Object run() {
...
                 // we don't do a security check just as a tradeoff, it cannot really escalate to anything.
                 return AccessController.doPrivileged((PrivilegedAction<Object>) script::run);
-            } catch (Exception e) {
-                if (logger.isTraceEnabled()) {
-                    logger.trace("failed to run {}", e, compiledScript);
+            } catch (AssertionError ae) {
+                // Groovy asserts are not java asserts, and cannot be disabled, so we do a best-effort trying to determine if this is a
+                // Groovy assert (in which case we wrap it and throw), or a real Java assert, in which case we rethrow it as-is, likely
+                // resulting in the uncaughtExceptionHandler handling it.
+                for (StackTraceElement ste : ae.getStackTrace()) {
```
Comment (jasontedor) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: Why are we traversing the stack trace? Shouldn't there be a Groovy method for the assert right at the top of the stack trace?

File: modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java (hunk 3 above)
Comment (nik9000) [inline modules/lang-groovy/src/test/java/org/elasticsearch/script/groovy/GroovySecurityTests.java]: Makes sense to me.

File: modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java (hunk 4 above)
Comment (dakrone) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: I didn't see anything other than this to indicate that it came from Groovy's version of `assert` rather than Java's: https://gist.github.com/dakrone/89c712ec192cf770f3ffff9a9f372035

I think Groovy is doing "magic" here and it makes it harder to identify

Comment (rmuir) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: You see InvokerHelper at the very top, that is the bad guy that throws it.

Comment (jasontedor) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: Right, but the point is that the `InvokeHelper` is right at the top of the stack trace. I do not think we should be descending in case the top of the stack trace is from an assert failing elsewhere outside of Groovy.

Comment (dakrone) [inline modules/lang-groovy/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java]: Alright,

I'll change to to check `ae.getStackTrace()[0]` for `InvokeHelper`, hopefully this is not fragile in any cases where there would be other classes in the stack due to function calls within the groovy script

File: core/src/main/java/org/elasticsearch/script/ClassPermission.java [hunk 5]
```diff
@@ -89,6 +89,7 @@
             java.lang.Object.class.getName(),
             java.lang.Short.class.getName(),
             java.lang.String.class.getName(),
+            java.lang.StringBuffer.class.getName(),
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/script/ClassPermission.java]: Are we going to leave this on since it doesn't get us anything here for this issue?

Comment (dakrone) [inline core/src/main/java/org/elasticsearch/script/ClassPermission.java]: It makes the error message when someone tries to use Groovy assertions point a bit more to Groovy instead of us (ie, NoClassDefFoundError for InvokerHelper rather than for StringBuffer), so I'm in favor of keeping it. If there is some security issue with it though, we can definitely leave it out. I'm fine either way.

**Comment by jasontedor** [comment]
LGTM.
