### PR TITLE
[Entitlements] Fix: consider case sensitiveness differences

### LINKED ISSUE #127047: Files entitlements need to be case sensitive on Windows
### Elasticsearch Version

8.18.0, 9.0.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Windows

### Problem Description

Files entitlements are checked in a case sensitive way. On Windows, this can lead to deny an entitlement (NotEntitlementException) for paths that should be valid.

### Steps to Reproduce

The easiest way to reproduce this is to use a lowercase drive letter, e.g. switch to `cd c:\path\to\elasticsearch\bin` and then launch `elasticsearch.bat`. ES fails to start, as it checks entitlements for `C:\...` against `c:\...`

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ldematte**
Our path comparison for file access is string based, due to the fact that we need to support Paths created for different file systems/platforms.
However, Windows files and paths are (sort of) case insensitive - see https://discuss.elastic.co/t/not-entitled-component-repository-s3-after-update-from-8-17-4-to-8-18-0/377166 for a real issue where we hit this problem.
This PR fixes the problem by abstracting String comparison operations (moving them to `FileUtils`) and making them case sensitive or not based on the host OS.

Closes https://github.com/elastic/elasticsearch/issues/127047

### CODE REVIEW

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 1]
```diff
@@ -44,17 +65,51 @@ private FileUtils() {}
...
 
+    /**
+     * Case-insensitive character comparison. Inspired by the {@code WindowsPath#compareTo} implementation.
+     */
+    private static int caseInsensitiveCharacterComparator(char c1, char c2) {
+        if (c1 == c2) {
+            return 0;
+        }
+        c1 = Character.toUpperCase(c1);
+        c2 = Character.toUpperCase(c2);
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:82]: Usually `toUpperCase` needs a locale.

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 2]
```diff
@@ -44,17 +65,51 @@ private FileUtils() {}
...
+        if (c1 == c2) {
+            return 0;
+        }
+        return c1 - c2;
+    }
+
+    private static int caseSensitiveCharacterComparator(char c1, char c2) {
+        return c1 - c2;
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:90]: Using subtraction to implement a comparator is not recommended, because there are overflow corner cases that don't work properly. We should call `Character.compare` here.

It turns out that, for `char` in particular, it makes no difference because the overflow can't happen, but calling `Character.compare` means folks reading this code don't even need to worry about this issue at all.

**Review by prdoyle — COMMENTED** [review]
I wonder if we'd be better of solving this via normalization rather than changing the comparator? If we normalize to lowercase on Windows, then the comparator will just work.

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java (hunk 2 above)
Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:90]: Again, copy-pasted this from WindowsPath in the JDK, so we should be fine; but I see your point of changing it for the sake of people reading the code. I can do it.

**Comment by ldematte** [comment]
> If we normalize to lowercase on Windows, then the comparator will just work.

I'm not sure this is the right way to do it; probably in the case of a Windows FS  it does not matter (the char comparison in WindowsPath do lower case after all), but usually "case insensitive comparison" and "normalize to lower case" are different. Since we already have a comparator, I thought it was a comparable amount of work/comparable change.

**Comment by prdoyle** [comment]
I just worry that our comparator is going to become rather incomprehensible.

Do you have an example where normalize-then-compare is different from a case-insensitive compare?

**Comment by prdoyle** [comment]
Do I understand correctly that the concern would be that a user would supply two different path strings that compare equal under `String.toLowercase()`, but are actually distinct? I don't think the comparator logic in this PR solves that problem any better, because it's also doing `toLowercase`.

**Comment by prdoyle** [comment]
I notice there's a reply to the above post that mentions `toLowercase(toUppercase(c))` as the solution. Perhaps we ought to do that either way, whether we use normalization or custom comparator logic?

**Comment by ldematte** [comment]
> I don't think the comparator logic in this PR solves that problem any better, because it's also doing toLowercase.

Yeah

> in the case of a Windows FS it does not matter (the char comparison in WindowsPath do lower case after all)

the startsWith thing for isParent is OK though.I wonder if we should "do better", but ... better than WindowsPath? Not sure is worth it at all. Still, I like the approach of fixing the comparator better; I don't like the idea of having a "broken" comparator around, that happens to work because we normalized strings beforehand.

**Comment by ldematte** [comment]
On the other hand it's true that normalization happens once, so there is a little performance benefit there... IDK.

**Comment by prdoyle** [comment]
> the startsWith thing for isParent is OK though.I wonder if we should "do better", but ... better than WindowsPath?

Agreed, the idea of overachieving relative to `WindowsPath` seems very much like a goal not worth pursuing.

> Not sure is worth it at all. Still, I like the approach of fixing the comparator better; I don't like the idea of having a "broken" comparator around, that happens to work because we normalized strings beforehand.

But this is the heart of why normalization is beneficial: it reduces the space of cases to consider, and then subsequent processing is greatly simplified. The comparator isn't "broken" if the cases it doesn't handle are ones that never occur thanks to normalization.

(In fact, the only reason I didn't propose normalizing the path separators is that there exists no reasonable separator character that would solve our sorting problem.)

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java [hunk 3]
```diff
@@ -9,17 +9,37 @@
...
 
+    private static final Logger logger = LogManager.getLogger(FileUtils.class);
+
     private FileUtils() {}
 
+    interface CharComparator {
+        int compare(char c1, char c2);
+    }
+
+    private static final CharComparator CHARACTER_COMPARATOR = Platform.WINDOWS.isCurrent()
```
Comment (ldematte) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/FileUtils.java:33]: Using static finals here should make code perform a little bit better as the JIT as a better chance of optimizing this. But the downside is that this is harder to test: you need to run tests on a Windows or Linux machine to test case sensitive/insensitive.
@rjernst what's your take on this?
Would you prefer to have a non-static comparator? We could still instantiate it as final in FileAccessTree, and create the correct final predicates in the ctor. Or have 2 different subclasses, and create the correct instance (CaseInsensitveComparator vs CaseSensitiveComparator)

**Review by rjernst — COMMENTED** [review]
I think it would be better for tests if we could test the case insensitive behavior (and case sensitive behavior as well) in the same test run, regardless of the system. Could we make the comparator someone we create (with isParent and samePath), and have two impls to choose from, case sensitive and case insensitive, and then choose that based on a flag to FileAccessTree (which then is chosen in PolicyManager based on the OS we are on)?

**Comment by ldematte** [comment]
>  Could we make the comparator someone we create (with isParent and samePath), and have two impls to choose from, case sensitive and case insensitive, and then choose that based on a flag to FileAccessTree (which then is chosen in PolicyManager based on the OS we are on)?

Yep, this is what I meant with "non-static comparator with 2 different subclasses (CaseInsensitveComparator vs CaseSensitiveComparator)".
It might be a tiny bit less optimized, but we are talking JIT level iniling here, so probably indistinguishable. I'll make the change.

**Review by rjernst — APPROVED** [review]
LGTM

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/CaseInsensitiveComparison.java [hunk 4]
```diff
@@ -16,18 +16,10 @@ class CaseInsensitiveComparison extends FileAccessTreeComparison {
...
-        if (c1 == c2) {
-            return 0;
-        }
-        c1 = Character.toUpperCase(c1);
-        c2 = Character.toUpperCase(c2);
-        if (c1 == c2) {
-            return 0;
-        }
-        return Character.compare(c1, c2);
+        return Character.compare(Character.toLowerCase(c1), Character.toLowerCase(c2));
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/CaseInsensitiveComparison.java:19]: Is there a significance to the fact that we switched from uppercase to lowercase?

Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/CaseInsensitiveComparison.java:19]: Nope, just a suggestion from Ryan to make it shorter and more readable

Comment (prdoyle) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/CaseInsensitiveComparison.java:19]: `toUpperCase` is equally short and readable, no?

I just think if we use one that's different from the actual filesystem code you copied, we're asking for unexpected corner cases.
