### PR TITLE
Throw exception if using a closed transport client

### LINKED ISSUE #18708: Closed TransportClient should throw meaningful exceptions when subsequently used
**Elasticsearch version**:
2.3.2

**Description of the problem including expected versus actual behavior**:
When `TransportClient#close()` is called, all connections are dropped and that client is no longer usable. However, if for some reason (due to a simple matter of programming error in our case 😉) the client is subsequently used, a not very helpful error is provided:

```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{x.x.x.x}
```

This error makes it sound like there's connectivity issues or something to the Elasticsearch cluster, which is not correct. Instead a more useful exception like `org.elasticsearch.client.transport.ClientStoppedException` should be created and thrown in this scenario.

**Steps to reproduce**:
 1. Create a standard `TransportClient` and connect it to an existing Elasticsearch cluster.
 2. Call `stop()` on the client.
 3. Call `admin().cluster().prepareHealth().get()` or something similar on the client and observe the thrown error.

### PR DESCRIPTION
**Pull request by jasontedor**
Today when attempting to use a closed transport client, an exception
saying that no nodes are available is thrown. This is because when a
transport client is closed, its internal list of nodes is cleared. But
this exception is puzzling and can be made clearer. This commit changes
the behavior so that attempting to execute a request using a closed
transport client throws an illegal state exception.

Closes #18708

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java [hunk 1]
```diff
@@ -211,7 +211,13 @@ public TransportClientNodesService removeTransportAddress(TransportAddress trans
     }
 
     public <Response> void execute(NodeListenerCallback<Response> callback, ActionListener<Response> listener) {
-        List<DiscoveryNode> nodes = this.nodes;
+        List<DiscoveryNode> nodes;
+        synchronized (mutex) {
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: why do we need to sync on a mutex here? closed is volatile and nodes as well?

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: Wouldn't it be good enough to write:

```
List<DiscoveryNode> nodes = this.nodes;
if (closed) {
    throw new IllegalStateException("transport client is closed");
}
ensureNodesAreAvailable(nodes);
```

as we know that the close() method first sets `close` to true and then empties the nodes list.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: > we know that the close() method first sets `close` to true and then empties the nodes list.

Sorry, that's relying too much on the implementation rather than on the invariants of the method.

Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: I disagree. Also, what invariants are you talking about? There are no comments / javadocs on this class -> implementation defines the invariants... you can even make it explicit by adding a comment.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: I think the invariants should be simply that `closed` is true, `nodes` is cleared, the transport service has disconnected, and sampling is cancelled. I think specifying the relative order in which these take place as an invariant isn't clean.

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: I don't think it is worth synchronizing because the race condition is going to cause us to throw the wrong error, but only briefly and only if we change the order that we set the things? I do agree we can't rely on that order because it isn't documented and even if it were I'm liable to screw it up the next time I touch the code because I don't read good.

I wonder if we can make this less trappy and have a single volatile reference that we replace when we change state? There shouldn't be an ordering issue then, right? And a buffoon like me is less likely to screw it up the next time I touch it?

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: @nik9000 That's not as simple as it sounds. For example, sampling modifies the list of nodes (state). During the process of sampling, any additional nodes are connected to. When closing, we need to ensure that we disconnect from all nodes connected to. That's one reason that there is a mutex to synchronize these actions, so that close is *always* guaranteed to disconnect from every node that is connected to, and no additional nodes can be connected to after we have closed. If we encapsulate all of the mutable state into a single reference that we replace when we change state, there's no guarantee in a race between adding nodes and closing the client.

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: Yeah, I'm not advocating for removing the mutex. That isn't going to work.

My thought came from vague notions of "can we just set the list to null when we've closed the client?" kinds of questions.

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: FYI - Node sampling is done under the mutex - see [here](https://github.com/jasontedor/elasticsearch/blob/e34961f2881a8cdf461bf4ab34c1e66b2968d97b/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L315) . This is blocking and can thus delay sending requests which is a no no.  

IMO it will be better to go with the suggestion of @ywelsch rather than go and adapt sniffing to be async.

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: +1 to:

```
List<DiscoveryNode> nodes = this.nodes;
if (closed) {
    throw new IllegalStateException("transport client is closed");
}
ensureNodesAreAvailable(nodes);
```

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: I pushed cc1b8baf5cf9c14a2e8551c497d4bf395f9c9255.

**Comment by ywelsch** [comment]
@jasontedor can you add a comment to the code why we first read `this.nodes` before the closed check? Just to make it explicit the order matters there. LGTM.

**Comment by jasontedor** [comment]
@ywelsch I pushed bc0b8f32e9197603bb25e83594ab19e3f49fa7b9. Thanks for your review.
