### PR TITLE
Adjust LinuxFileSystemNatives.allocatedSizeInBytes for aarch64 architectures

### LINKED ISSUE #81362: [CI] CacheFileTests.testCacheFileCreatedAsSparseFile fails on master
**Build scan**:
https://gradle-enterprise.elastic.co/s/lny65mo6chmek

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests.testCacheFileCreatedAsSparseFile" \
  -Dtests.seed=E7AB31A9E717E54B \
  -Dtests.locale=zh-CN \
  -Dtests.timezone=Etc/GMT-5 \
  -Druntime.java=17

REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests.testCacheFileCreatedAsSparseFile" \
  -Dtests.seed=E7AB31A9E717E54B \
  -Dtests.locale=zh-CN \
  -Dtests.timezone=Etc/GMT-5 \
  -Druntime.java=17
```

**Reproduces locally?**:
No

**Applicable branches**:
`master`

**Failure history**:
Two failures today.
No prior failures of this test.

**Failure excerpt**:
```
11:54:36 org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests > testCacheFileCreatedAsSparseFile FAILED
11:54:36     java.lang.AssertionError
11:54:36         at __randomizedtesting.SeedInfo.seed([45B7968DCEE813EC:C0396B8309F7EF9D]:0)
11:54:36         at org.junit.Assert.fail(Assert.java:86)
11:54:36         at org.junit.Assert.assertTrue(Assert.java:41)
11:54:36         at org.junit.Assert.assertTrue(Assert.java:52)
11:54:36         at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFileTests.testCacheFileCreatedAsSparseFile(CacheFileTests.java:422)
```

### PR DESCRIPTION
**Pull request by tlrx**
The native method added in #80437 requires some adjustments to work on `aarch64` architectures, which hopefully this change addresses. The stat version has been tested on AWS 64-bit ARM instances (on ubuntu-18.04 and on Amazon Linux 2).

Closes #81362

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/filesystem/LinuxFileSystemNatives.java [hunk 1]
```diff
@@ -41,12 +41,21 @@
...
-     * In glibc this version is defined in bits/stat.h (or bits/struct_stat.h in glibc 2.33) as:
+     * In glibc this version is defined in bits/stat.h (or bits/struct_stat.h in glibc 2.33, or bits/xstatver.h in more recent versions).
+     *
+     * For x86-64 the _STAT_VER used is:
      *  # define _STAT_VER_LINUX    1
      *  # define _STAT_VER _STAT_VER_LINUX
+     *
+     * For other architectures the _STAT_VER used is:
+     *  # define _STAT_VER_LINUX    0
+     *  # define _STAT_VER _STAT_VER_LINUX
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/filesystem/LinuxFileSystemNatives.java:52]: We really need https://github.com/elastic/elasticsearch/issues/80903 to deal with this sort of nonsense.

**Review by DaveCTurner — APPROVED** [review]
:+1:

File: server/src/main/java/org/elasticsearch/common/filesystem/LinuxFileSystemNatives.java (hunk 1 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/common/filesystem/LinuxFileSystemNatives.java:52]: I agree, I'm a bit afraid if the _xstat function changes over time and we don't catch it before in our tests.

**Comment by tlrx** [comment]
Thanks David! Let's see if that works now.
