### PR TITLE
Fix merging of _meta field

### LINKED ISSUE #27323: PUT Mapping removes metadata from index
**Elasticsearch version** (`bin/elasticsearch --version`): 5.3.0

**Plugins installed**: [repository-s3]

**JVM version** (`java -version`): 1.8.0_92

**OS version** (`uname -a` if on a Unix-like system): Linux 2.6

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
After we make a PUT or POST mapping to add additional fields, it removes our _meta Field from the mapping.
Is this normal? Can we prevent this?

Before:

{
    "foo": {
        "mappings": {
            "bar": {
                "_meta": {
                    "foo": "bar"
                },
                "properties": {
...

After:

{
    "foo": {
        "mappings": {
            "bar": {
                "properties": {
...

This was question was asked in the forum with no answer provided.
https://discuss.elastic.co/t/put-mapping-removes-metadata-from-index/91794

### PR DESCRIPTION
**Pull request by alexshadow007**
Closes #27323

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticmachine please test this.

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java [hunk 1]
```diff
@@ -56,7 +56,7 @@
 
         private final RootObjectMapper rootObjectMapper;
 
-        private Map<String, Object> meta = emptyMap();
+        private Map<String, Object> meta;
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: I think this initialization should stay, for the case meta is not defined in the json?

File: core/src/main/java/org/elasticsearch/index/mapper/Mapping.java [hunk 2]
```diff
@@ -98,7 +98,8 @@ public Mapping merge(Mapping mergeWith, boolean updateAllTypes) {
             }
             mergedMetaDataMappers.put(merged.getClass(), merged);
         }
-        return new Mapping(indexCreated, mergedRoot, mergedMetaDataMappers.values().toArray(new MetadataFieldMapper[0]), mergeWith.meta);
+        return new Mapping(indexCreated, mergedRoot, mergedMetaDataMappers.values().toArray(new MetadataFieldMapper[0]),
+            mergeWith.meta != null ? mergeWith.meta : meta);
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/index/mapper/Mapping.java]: I would flip this logic to remove negations. ie `mergeWith.meta == null ? meta : mergeWith.meta`. Positive logic is easier to reason about. It might also be better to just move it out to a local instead of trying to inline it.

**Review by rjernst — COMMENTED** [review]
This looks good, but I have a couple asks.

File: core/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java (hunk 1 above)
Comment (alexshadow007) [reply core/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: @rjernst I was thinking of using `null` for this case. Or is empty map better?
And which value must be used for unset meta?

Comment (rjernst) [reply core/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: I'm fine with null. I had thought changing this from emtpy map to null would require updating Mapping.toXContent. However, it looks like it currently handles both cases. I would update that to remove the empty case (which means explicitly putting an empty _meta would be serialized, not disappear).

File: core/src/main/java/org/elasticsearch/index/mapper/Mapping.java (hunk 2 above)
Comment (alexshadow007) [reply core/src/main/java/org/elasticsearch/index/mapper/Mapping.java]: Done

**Comment by rjernst** [comment]
@alexshadow007 Can you update Mapping.toXContent as I suggested?

**Comment by alexshadow007** [comment]
@rjernst Done

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
Thanks @alexshadow007, I'll merge once CI completes again.

**Comment by alexshadow007** [comment]
@rjernst Rebased branch onto master

**Review by jpountz — APPROVED** [review]
LGTM too.

@rjernst Pinging you as you said you would merge it, but if you don't have time, I can do it.
