### PR TITLE
Avoid warnings for non-system indexes using `fast_refresh`

### LINKED ISSUE #124284: LogsdbIndexModeSettingsProvider generates unnecesary warnings for system indices
When generating `MappingHints`, `LogsdbIndexModeSettingsProvider` [calls](https://github.com/elastic/elasticsearch/blob/b02f15d0094a7223f2a5f513acfc08d082e9325a/x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/LogsdbIndexModeSettingsProvider.java#L251) `IndicesService#createIndexMapperServiceForValidation` with a dummy indexMetadata that takes the real index name but does not replicate all the actual index settings. This can creae conflicting IndexMetadata for system indices with `fast_refresh=true` but `isSystem=false` which leads to exception being thrown in [IndexSettings](https://github.com/elastic/elasticsearch/blob/b02f15d0094a7223f2a5f513acfc08d082e9325a/server/src/main/java/org/elasticsearch/index/IndexSettings.java#L1059-L1060).

An sample stacktrace is as the follows:
```
[2025-03-06T14:31:20,750][WARN ][o.e.x.l.LogsdbIndexModeSettingsProvider] [es01] unable to create mapper service for index [.security-profile-8] java.lang.IllegalArgumentException: index.fast_refresh is allowed only for system indices
	at org.elasticsearch.server@9.1.0/org.elasticsearch.index.IndexSettings.<init>(IndexSettings.java:1064)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.indices.IndicesService.createIndexMapperServiceForValidation(IndicesService.java:855)
	at org.elasticsearch.xpack.logsdb.LogsdbIndexModeSettingsProvider.getMappingHints(LogsdbIndexModeSettingsProvider.java:250)
	at org.elasticsearch.xpack.logsdb.LogsdbIndexModeSettingsProvider.getAdditionalIndexSettings(LogsdbIndexModeSettingsProvider.java:115)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.aggregateIndexSettings(MetadataCreateIndexService.java:1086)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestForSystemIndex(MetadataCreateIndexService.java:785)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:434)
...
```

Relates: #118968

### PR DESCRIPTION
**Pull request by kkrik-es**
`LogsdbIndexModeSettingsProvider` creates a transient `MappingService` to check the index mappings for information relevant to `logsdb` mode. This may trigger unrelated warnings, e.g. for non-system indexes configured with `[fast_refresh=true]`. To avoid the noise, we can always unset this setting as it's not relevant to the `logsdb` functionality.

Fixes #124284

### CODE REVIEW

File: x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/LogsdbIndexModeSettingsProvider.java [hunk 1]
```diff
@@ -309,7 +309,8 @@ private IndexMetadata buildIndexMetadataForMapperService(
             .put(indexTemplateAndCreateRequestSettings)
             .put(IndexMetadata.SETTING_NUMBER_OF_SHARDS, dummyShards)
             .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, shardReplicas)
-            .put(IndexMetadata.SETTING_INDEX_UUID, UUIDs.randomBase64UUID());
+            .put(IndexMetadata.SETTING_INDEX_UUID, UUIDs.randomBase64UUID())
+            .put(IndexSettings.INDEX_FAST_REFRESH_SETTING.getKey(), false);  // Avoid warnings for non-system indexes.
```
Comment (martijnvg) [inline x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/LogsdbIndexModeSettingsProvider.java:313]: Is there a relative easy way to test the problem reported in the issue?

Comment (kkrik-es) [reply x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/LogsdbIndexModeSettingsProvider.java:313]: It's a warning.. I tried to reproduce but it probably needs more than just the setting. @ywangd too for ideas.

Comment (ywangd) [reply x-pack/plugin/logsdb/src/main/java/org/elasticsearch/xpack/logsdb/LogsdbIndexModeSettingsProvider.java:313]: The warning is for serverless deployments since `fast_refresh` was a [feature for serverless only](https://github.com/elastic/elasticsearch/blob/b02f15d0094a7223f2a5f513acfc08d082e9325a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecuritySystemIndices.java#L919-L925). In a serverless deployment, you can trigger this warning by just creating a related system index, e.g.

```
PUT .security-profile-8
```

In theory, the alternative fix can be removing the `fast_refresh` setting from all system indices since the setting is a noop today. But I am not sure whether that could still have other implications. Overall fixing it here feels safer.

**Review by martijnvg — APPROVED** [review]
LGTM, thanks Kostas!

**Review by ywangd — APPROVED** [review]
LGTM2
