### PR TITLE
Avoid bubbling up failures from a shard that is recovering

### LINKED ISSUE #40107: New master repeatedly reroute and fetch shard store of recovering replica
If a master fails over and there's a replica performing phase1 of recovery, then the new master will repeatedly but fail to fetch shard store of the recovering replica until that replica completes phase 1. Some consequences of this:

- Spam log files over and over
- Flood the master node with many reroute task
- If there's an unassigned shard (same shardId with the recovering replica), it won't be allocated until the recovery completes

/cc @ywelsch

### PR DESCRIPTION
**Pull request by ywelsch**
A shard that is undergoing peer recovery is subject to logging warnings of the form

```
org.elasticsearch.action.FailedNodeException: Failed node [XYZ]
...
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in ...
```

(see e.g. https://github.com/elastic/elasticsearch/issues/30919)

These failures are actually harmless, and expected to happen while a peer recovery is ongoing (i.e. there is an IndexShard instance, but no proper `IndexCommit` just yet).
As these failures are currently bubbled up to the master, they cause unnecessary reroutes and confusion amongst users due to being logged as warnings.

Closes #40107

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Looks good (NB earlier versions of Lucene didn't throw an INFE here, so you may see `FileNotFoundException` in older versions). However I think we should have a test for this change in behaviour.

**Comment by dnhatn** [comment]
This PR should fix #40107 (hence we should treat this as a bug). I had a test for #40107, but I lost it. I will reconstruct and add that test here.

**Comment by ywelsch** [comment]
thanks @dnhatn

File: server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetaData.java [hunk 1]
```diff
@@ -123,8 +124,17 @@ private StoreFilesMetaData listStoreMetaData(ShardId shardId) throws IOException
...
                 if (indexShard != null) {
-                    exists = true;
-                    return new StoreFilesMetaData(shardId, indexShard.snapshotStoreMetadata());
+                    try {
+                        final StoreFilesMetaData storeFilesMetaData = new StoreFilesMetaData(shardId, indexShard.snapshotStoreMetadata());
+                        exists = true;
+                        return storeFilesMetaData;
+                    } catch (org.apache.lucene.index.IndexNotFoundException e) {
+                        logger.trace(new ParameterizedMessage("[{}] node is missing index, responding with empty", shardId), e);
+                        return new StoreFilesMetaData(shardId, Store.MetadataSnapshot.EMPTY);
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetaData.java]: Should we only ignore the exception if shard is recovering?

**Review by dnhatn — APPROVED** [review]
I left a comment but LGTM.

File: server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 2]
```diff
@@ -910,6 +910,50 @@ public void testDoNotInfinitelyWaitForMapping() {
...
+            .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 1)
+            .put("index.routing.allocation.include._name", nodeWithPrimary + "," + nodeWithReplica)));
+        phase1ReadyBlocked.await();
+        internalCluster().restartNode(clusterService().state().nodes().getMasterNode().getName(),
+            new InternalTestCluster.RestartCallback());
+        internalCluster().ensureAtLeastNumDataNodes(3);
+        assertAcked(client().admin().indices().prepareUpdateSettings(indexName).setSettings(Settings.builder()
+            .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 2)
+            .putNull("index.routing.allocation.include._name")));
+        try {
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: I think this try should be moved to line 938 so that we also release the latch if this test fails in other unexpected ways.

File: server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetaData.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetaData.java]: Would be nice to only have this try-catch in the no-engine case, since it should not happen if there is an engine. The same pattern is also done in 2 other places already, so could be nice to add a single method to handle this in the same way whenever needed.
I see no problems in doing this always in this specific case, so please regard this optional.

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetaData.java (hunk 1 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetaData.java]: I will leave this to a follow-up to explore. I'm generally not happy with how we access the store on a shard that is recovering. Also accessing last commit instead of safe commit feels wrong as well for some of the callers.

File: server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java (hunk 2 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]: agree, fixed in 2a52487

**Comment by jala-dx** [comment]
Hi, I see from logs

Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in store(MMapDirectory@/elasticsearch/data/nodes/0/indices/ZIqXS2f-SWKLvR40ocIg4Q/0/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@2cc763ad): files: [recovery.cxml8-lOTIWRft_jB0iZ3A._j.dii, recovery.cxml8-lOTIWRft_jB0iZ3A._j.fdx, recovery.cxml8-lOTIWRft_jB0iZ3A._j_1.liv, recovery.cxml8-lOTIWRft_jB0iZ3A._p.si, recovery.cxml8-lOTIWRft_jB0iZ3A._s.si, recovery.cxml8-lOTIWRft_jB0iZ3A._u.si, write.lock]

The fix above is needed to address this issue?

Thanks for the help.

Regards
Jala

**Comment by jala-dx** [comment]
Elasticsearch Version: 6.2.4

**Comment by DaveCTurner** [comment]
Yes @jala-dx. The message is misleading, in fact we sometimes expect there to be no `segments*` file, so Elasticsearch is wrong to warn you about this. The fix is not to log this message, which is implemented in versions ≥7.2.0 and also versions ≥6.8.1 and <7.0.0. The workaround in other versions is for you to ignore this message.
