### PR TITLE
ESQL: Page shouldn't close a block twice

### LINKED ISSUE #100356: Test failures in rename
### CI Link

https://gradle-enterprise.elastic.co/s/xws6gmgwdwnmm/tests/overview?outcome=failed

### Repro line

./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {rename.RenameProjectEval}" -Dtests.seed=F32BCA1B870438F -Dtests.locale=ar-LY -Dtests.timezone=UTC -Druntime.java=21	

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```
java.lang.AssertionError: java.lang.IllegalStateException: can't release already released block [IntVectorBlock[vector=IntArrayVector[positions=3, values=[2, 5, 4]]]]
```

### LINKED ISSUE #100365: [CI] EsqlActionIT testProjectRename failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/la7gp5c6fapkq/tests/:x-pack:plugin:esql:internalClusterTest/org.elasticsearch.xpack.esql.action.EsqlActionIT/testProjectRename
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.EsqlActionIT.testProjectRename" -Dtests.seed=A39D3438C69D3433 -Dtests.locale=nb -Dtests.timezone=America/Shiprock -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.action.EsqlActionIT&tests.test=testProjectRename
**Failure excerpt:**
```
java.lang.AssertionError: java.lang.IllegalStateException: can't release already released block [LongVectorBlock[vector=LongArrayVector[positions=4, values=[40, 42, 44, 46]]]]

  at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:49)
  at org.elasticsearch.compute.data.Page.releaseBlocks(Page.java:225)
  at org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
  at org.elasticsearch.core.IOUtils.close(IOUtils.java:119)
  at org.elasticsearch.core.Releasables.close(Releasables.java:24)
  at org.elasticsearch.xpack.esql.action.EsqlQueryResponse.close(EsqlQueryResponse.java:206)
  at org.elasticsearch.xpack.esql.action.EsqlActionIT.testProjectRename(EsqlActionIT.java:644)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.lang.IllegalStateException: can't release already released block [LongVectorBlock[vector=LongArrayVector[positions=4, values=[40, 42, 44, 46]]]]

    at org.elasticsearch.compute.data.LongVectorBlock.close(LongVectorBlock.java:76)
    at org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
    at org.elasticsearch.core.IOUtils.close(IOUtils.java:87)
    at org.elasticsearch.core.IOUtils.close(IOUtils.java:63)
    at org.elasticsearch.core.Releasables.close(Releasables.java:73)
    at org.elasticsearch.core.Releasables.close(Releasables.java:41)
    at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:47)
    at org.elasticsearch.compute.data.Page.releaseBlocks(Page.java:225)
    at org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
    at org.elasticsearch.core.IOUtils.close(IOUtils.java:119)
    at org.elasticsearch.core.Releasables.close(Releasables.java:24)
    at org.elasticsearch.xpack.esql.action.EsqlQueryResponse.close(EsqlQueryResponse.java:206)
    at org.elasticsearch.xpack.esql.action.EsqlActionIT.testProjectRename(EsqlActionIT.java:644)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by costin**
Page now takes into account that a block can be used in multiple
 positions (such as the same column aliased under multiple names).

Relates #100001
Fix #100365
Fix #100356

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 1]
```diff
@@ -222,6 +223,13 @@ public void writeTo(StreamOutput out) throws IOException {
      */
     public void releaseBlocks() {
         blocksReleased = true;
-        Releasables.closeExpectNoException(blocks);
+        // blocks can be used as multiple columns
+        var set = new IdentityHashMap<Block, Object>();
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:227]: `Collections.newSetFromMap` is the idiomatic way to do this. And all the cool kids want to be idiots, right?

**Review by nik9000 — COMMENTED** [review]
@alex-spies should probably look at this too. It does get the job done. And we don't need to keep it forever. If we have reference counting we wouldn't need it. But we don't have it now.

**Comment by nik9000** [comment]
@ChrisHegarty also might have opinions on this.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:227]: :)
I actually tried that first but it blew up because the blocks equals implementation checks the content meaning different blocks end up looking equal meaning they are not closed as they are considered a duplicate. 
Which causes a bunch of leaks - hence why I'm using the Identity match alone.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 2]
```diff
@@ -222,6 +221,43 @@ public void writeTo(StreamOutput out) throws IOException {
...
+            }
+        }
+    }
+
+    /**
+     * Returns a Page from the given blocks and closes all blocks that are not included, from the current Page.
+     * That is, allows clean-up of the current page _after_ external manipulation of the blocks.
+     * The current page should no longer be used and be considered closed.
+     */
+    public Page newPageAndRelease(Block... keep) {
```
Comment (costin) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:239]: I've introduced this method for handling the case of reusing some blocks from an old page into a new one.
This happens in ProjectExec and OutputExec (inside the planner) - I've moved this method from the Project into the page and clean-it up a bit (the usual reduction complexity from using two lists - O(N*M) to O(N) with the extra memory for the map).

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 3]
```diff
@@ -88,9 +89,7 @@ private Page(Page prev, Block[] toAdd) {
         this.positionCount = prev.positionCount;
 
         this.blocks = Arrays.copyOf(prev.blocks, prev.blocks.length + toAdd.length);
-        for (int i = 0; i < toAdd.length; i++) {
-            this.blocks[prev.blocks.length + i] = toAdd[i];
-        }
+        System.arraycopy(toAdd, 0, this.blocks, prev.blocks.length + 0, toAdd.length);
```
Comment (costin) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:92]: Small improvement .

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 4]
```diff
@@ -88,9 +89,7 @@ private Page(Page prev, Block[] toAdd) {
         this.positionCount = prev.positionCount;
 
         this.blocks = Arrays.copyOf(prev.blocks, prev.blocks.length + toAdd.length);
-        for (int i = 0; i < toAdd.length; i++) {
-            this.blocks[prev.blocks.length + i] = toAdd[i];
-        }
+        System.arraycopy(toAdd, 0, this.blocks, prev.blocks.length, toAdd.length);
```
Comment (costin) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:92]: Small improvement.

**Comment by costin** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by costin** [comment]
FTR, it looks like all the builders for part-1 end up being disabled...

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 5]
```diff
@@ -222,6 +221,43 @@ public void writeTo(StreamOutput out) throws IOException {
...
         blocksReleased = true;
-        Releasables.closeExpectNoException(blocks);
+        // blocks can be used as multiple columns
+        var map = new IdentityHashMap<Block, Object>(mapSize(blocks.length));
+        var DUMMY = new Object();
+        for (Block b : blocks) {
+            if (map.putIfAbsent(b, DUMMY) == null) {
+                Releasables.closeExpectNoException(b);
+            }
+        }
```
Comment (alex-spies) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:231]: I think this improves the issue, but there still can be problems because non-identical blocks can be backed by the same vector or array.

Additionally, we create and populate a new hash map on each page release; that's probably quite expensive.

We can merge this to fix the problem right now, but IMO should mark this with a todo comment to remove this logic once possible. We want ref counting, this will fix the problem more idiomatically.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 6]
```diff
@@ -222,6 +221,43 @@ public void writeTo(StreamOutput out) throws IOException {
      */
     public void releaseBlocks() {
         blocksReleased = true;
-        Releasables.closeExpectNoException(blocks);
+        // blocks can be used as multiple columns
+        var map = new IdentityHashMap<Block, Object>(mapSize(blocks.length));
+        var DUMMY = new Object();
```
Comment (alex-spies) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:226]: That could be moved into a static final var.

**Review by alex-spies — APPROVED** [review]
LGTM as an intermediate fix.

IMO we're beginning to create a lot of workarounds to make up for a lack of ref counted shallow copies of blocks and that makes the code harder to reason about.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java (hunk 6 above)
Comment (ChrisHegarty) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:226]: Or...

```
var map = new IdentityHashMap<Block, Boolean>(mapSize(blocks.length));
for (Block b : blocks) {
    if (map.putIfAbsent(b, Boolean.TRUE) == null) { ..
```

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 7]
```diff
@@ -222,6 +221,43 @@ public void writeTo(StreamOutput out) throws IOException {
...
+    public Page newPageAndRelease(Block... keep) {
+        blocksReleased = true;
+
+        var newPage = new Page(positionCount, keep);
+        var map = new IdentityHashMap<Block, Object>(mapSize(keep.length));
+        var DUMMY = new Object();
+
+        // create identity set
+        for (Block b : keep) {
+            map.putIfAbsent(b, DUMMY);
```
Comment (ChrisHegarty) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:248]: Subjective:

```
  // create identity set
  var set = Collections.newSetFromMap(new IdentityHashMap<Block, Boolean>(mapSize(keep.length)));
  set.addAll(Arrays.asList(keep));
  ..
      if (set.contains(b) == false) { ..
```

**Review by ChrisHegarty — APPROVED** [review]
LGTM. I left a few small comments / suggestions.

Additionally, it would be good to have a small unit test in BasicPageTests for the Page additions.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java [hunk 8]
```diff
@@ -222,6 +221,43 @@ public void writeTo(StreamOutput out) throws IOException {
...
+            if (map.containsKey(b) == false) {
+                Releasables.closeExpectNoException(b);
+            }
+        }
+
+        return newPage;
+    }
+
+    static int mapSize(int expectedSize) {
+        return expectedSize < 2 ? expectedSize + 1 : (int) (expectedSize / 0.75 + 1.0);
```
Comment (bpintea) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Page.java:261]: `CollectionUtils.mapSize()`?

**Review by bpintea — APPROVED** [review]
LGTM
