### PR TITLE
[ML] inference only persist if there are stats

### LINKED ISSUE #54786: [CI] InferenceIngestIT.testPipelineIngest occasionally fails
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/614/console

Build scan: https://gradle-enterprise.elastic.co/s/q4hcgpbmvcn3g

Failure:

```
java.lang.AssertionError: 

Expected: a string containing "\"inference_count\":10"
     but: was "{"count":1,"trained_model_stats":[{"model_id":"test_classification","pipeline_count":0,"inference_stats":{"failure_count":0,"inference_count":11,"missing_all_fields_count":0,"time_stamp":-9223372036854775808}}]}"

at __randomizedtesting.SeedInfo.seed([3274046E5719A7DD:90289258A5A9409E]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.InferenceIngestIT.lambda$testPipelineIngest$0(InferenceIngestIT.java:135)
``` 

Reproduce with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.InferenceIngestIT.testPipelineIngest" -Dtests.seed=3274046E5719A7DD -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=Asia/Jayapura -Dcompiler.java=13
```

I couldn't reproduce locally.

### PR DESCRIPTION
**Pull request by benwtrent**
We needlessly send documents to be persisted. If there are no stats added, then we should not attempt to persist them.

closes https://github.com/elastic/elasticsearch/issues/54786

### CODE REVIEW

**Comment by benwtrent** [comment]
I am doing this directly in the backport of the original stats persistence PR: 

https://github.com/elastic/elasticsearch/pull/54738

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/persistence/TrainedModelProvider.java [hunk 1]
```diff
@@ -550,7 +551,9 @@ private InferenceStats handleMultiNodeStatsResponse(SearchResponse response, Str
             failures == null ? 0L : Double.valueOf(failures.getValue()).longValue(),
             modelId,
             null,
-            timeStamp == null ? Instant.now() : Instant.ofEpochMilli(Double.valueOf(timeStamp.getValue()).longValue())
+            timeStamp == null || (Numbers.isValidDouble(timeStamp.getValue()) == false) ?
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/persistence/TrainedModelProvider.java:554]: Is it possible for timestamp to be an invalid number here?

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/persistence/TrainedModelProvider.java:554]: Yes, it is. The agg could have not found any values, or the values they found were changed somehow. This type of check is effectively what aggs do under the hood when they serialize to JSON to protect against goofy doubles. The difference here is that we write out `now()` instead of `null`

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java [hunk 2]
```diff
@@ -47,12 +48,16 @@
...
+        "    ctx._source.{2} += params.{2};\n" +
+        "    ctx._source.{3} = params.{3};";
     // Script to only update if stats have increased since last persistence
-    private static final String STATS_UPDATE_SCRIPT = "" +
-        "    ctx._source.missing_all_fields_count += params.missing_all_fields_count;\n" +
-        "    ctx._source.inference_count += params.inference_count;\n" +
-        "    ctx._source.failure_count += params.failure_count;\n" +
-        "    ctx._source.time_stamp = params.time_stamp;";
+    private static final String STATS_UPDATE_SCRIPT = Messages.getMessage(STATS_UPDATE_SCRIPT_TEMPLATE,
+        InferenceStats.INFERENCE_COUNT.getPreferredName(),
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:58]: Are we missing `InferenceStats.MISSING_ALL_FIELDS_COUNT` here?

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/TrainedModelStatsService.java:58]: yep, I am :/

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM Second time lucky!

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2
