### PR TITLE
DISCOVERY: 0s Initial State Timeout in Tests

### LINKED ISSUE #35456: [CI] Rolling upgrade tests fail to find dynamic hosts list
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/54/console

```
14:54:51 > Task :x-pack:qa:rolling-upgrade:with-system-key:v6.6.0#oneThirdUpgradedTestCluster#wait FAILED
14:54:51 :x-pack:qa:rolling-upgrade:with-system-key:v6.6.0#oneThirdUpgradedTestCluster#wait (Thread[Task worker for ':' Thread 11,5,main]) completed. Took 40.016 secs.
```

The task fails because a cluster doesn't form.

The log files for the cluster nodes all contain the following line:
```
[2018-11-12T14:53:27,628][WARN ][o.e.d.z.FileBasedUnicastHostsProvider] [node-1] expected, but did not find, a dynamic hosts list at [/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/fedora/x-pack/qa/rolling-upgrade/with-system-key/build/cluster/v6.6.0#oldClusterTestCluster node1/elasticsearch-6.6.0-SNAPSHOT/config/unicast_hosts.txt]
```

However, that file is there, and contains the correct list of IPv6 addresses.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Don't wait for initial state even with a single node, otherwise the loop writing the discovery file causes that single node to wait for its own transport.ports file for 30s (because the `unicastTransportUri` call waits for that file to come up).
   * This didn't happen before #35375 because we used to override the `unicastTransportUri` field
* Closes #35456

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Good catch, but I'm not sure about the fix. I think this _only_ affects the rolling-upgrade tests, in which Gradle believes us to have a one-node cluster but the `minimum_master_nodes` setting indicates otherwise. I think it'd be better to say `if (minimumMasterNodes > 1) ...`?

I think we should consider, as a followup, moving the writing of the transport ports file earlier in the node startup and getting rid of the `initial_state_timeout` overrides like this.

**Comment by original-brownbear** [comment]
@DaveCTurner 

> (minimumMasterNodes > 1) 

Sure :) That works too fixing.

> I think we should consider, as a followup, moving the writing of the transport ports file earlier in the node startup and getting rid of the initial_state_timeout overrides like this.

Yes please :)

**Comment by original-brownbear** [comment]
Fixed :)

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy [hunk 1]
```diff
@@ -343,7 +343,7 @@ class ClusterFormationTasks {
         if (minimumMasterNodes > 0) {
             esConfig['discovery.zen.minimum_master_nodes'] = minimumMasterNodes
         }
-        if (node.config.numNodes > 1) {
+        if (node.config.minimumMasterNodes > 1) {
```
Comment (DaveCTurner) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: Isn't `node.config.minimumMasterNodes` a closure? We just called it a few lines up, why not re-use the result?

Comment (original-brownbear) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: @DaveCTurner yikes sorry about that ... multitasking in action :) => reused the var.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@DaveCTurner thanks!
