### PR TITLE
Fix time-series geo_line to include reduce phase in MergedGeoLines

### LINKED ISSUE #96983: geo_line does not use simplify algorithm or capped memory for time-series
### Elasticsearch Version

8.9.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

In https://github.com/elastic/elasticsearch/pull/96953 we added support for a much more memory efficient algorithm that relies on the time-ordering and grouping provided by the time-series aggregation in TSDB. However, this work only covered the data nodes, and the reduce phase in the coordinating nodes that merges geo_lines does not take this into account, leading to unexpected truncation of long geo_lines.

### Steps to Reproduce

Easiest to reproduce by setting the shard size small, loading very long geolines that will be composed of many data points over many shards, and then setting the geo_line aggregation size to a small size. The final lines will not include the two end points as they should, but be truncated.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by craigtaverner**
Recently we added support for line-simplification in geo-lines when in time-series aggregations: https://github.com/elastic/elasticsearch/pull/94954. This work did not, however, cover the case of `MergedGeoLines`, which occurs when the same geo_line covers multiple shards on data nodes, and needs to be merged on the coordinating node. The original work would use line-simplification and time-ordering on the data node, but then revert to re-sorting (unnecessary) and truncation (incorrect) on the coordinating node.

This PR rectifies that, and adds two fields to the InternalGeoLine:
* nonOverlapping
  * re-sorting is *NOT* required because the sort value ranges do not overlap, so we only sort the set of incoming geo_lines (easy/fast) instead of every single point (complex/slow).
* simplified
  * The approach to memory limiting is by line-simplification instead of truncation.
  * If the data nodes are doing line-simplification, we want the coordinating node to do that as well

For time-series, both of the above are true, and at this point all other cases will have both false. The reason for two booleans is:
* They are not necessarily related concepts
* We consider supporting line-simplification as a user-requested option in the non-time-series geo_line in future (much nicer than truncation)

Fixes #96983

### CODE REVIEW

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/search/aggregations/MergedGeoLines.java [hunk 1]
```diff
@@ -45,131 +44,225 @@ public double[] getFinalSortValues() {
...
+            super(geoLines, finalLength, sortOrder, simplify);
+        }
+
+        /**
+         * merges <code>geoLines</code> into one sorted list of values representing the combined line.
+         */
+        @Override
+        public void merge() {
+            TreeSet<InternalGeoLine> sorted = switch (sortOrder) {
+                case DESC -> new TreeSet<>((o1, o2) -> Double.compare(o2.sortVals()[0], o1.sortVals()[0]));
```
Comment (salvatore-campagna) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/search/aggregations/MergedGeoLines.java:217]: Maybe use static comparators? And also `naturalOrdering` and `reverseOrder` comparators.

**Review by salvatore-campagna — APPROVED** [review]

**Comment by salvatore-campagna** [comment]
LGTM, I just left a couple of comments about using static comparators...

File: x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/search/aggregations/MergedGeoLinesTests.java [hunk 2]
```diff
@@ -76,4 +99,191 @@ public void testMergeWithEmptyGeoLine() {
         assertArrayEquals(sortedValues, mergedGeoLines.getFinalSortValues(), 0d);
         assertArrayEquals(sortedPoints, mergedGeoLines.getFinalPoints());
     }
+
+    public void testMergeNonOverlappingGeoLinesAppendOnly() {
```
Comment (salvatore-campagna) [inline x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/search/aggregations/MergedGeoLinesTests.java:103]: It is not clear to me how do you test the case where you have the line split among two data nodes.
