### PR TITLE
ESQL: Fix CsvTestsDataLoader and add more exceptions to GenerativeRestTest

### LINKED ISSUE #142534: ESQL: csv test data loader is broken
Repros on main:
```
 ./gradlew :x-pack:plugin:esql:qa:testFixtures:loadCsvSpecData --args="http://elastic-admin:elastic-password@localhost:9200" 

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.logging.internal.spi.LoggerFactory.getLogger(java.lang.Class)" because the return value of "org.elasticsearch.logging.internal.spi.LoggerFactory.provider()" is null
        at org.elasticsearch.logging.LogManager.getLogger(LogManager.java:36)
        at org.elasticsearch.xpack.esql.CsvTestsDataLoader.<clinit>(CsvTestsDataLoader.java:62)
```

I suspect #142368 caused this.

### PR DESCRIPTION
**Pull request by astefan**
~Fixes https://github.com/elastic/elasticsearch/issues/142534~ LE: fixed quicker with https://github.com/elastic/elasticsearch/pull/142481
Unmutes GenerativeIT and "fixes" https://github.com/elastic/elasticsearch/issues/142426

Developed using AI-assisted tooling

### CODE REVIEW

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java [hunk 1]
```diff
@@ -59,6 +59,12 @@
 
 public class CsvTestsDataLoader {
 
+    static {
+        // Ensure the logging factory is initialized before the static logger field below. When running standalone (via main() or
+        // Gradle's loadCsvSpecData task), nothing has initialized the ES logging system before this class is loaded.
+        LogConfigurator.configureESLogging();
+    }
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:69]: Thank you!

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java [hunk 2]
```diff
@@ -59,6 +59,12 @@
 
 public class CsvTestsDataLoader {
 
+    static {
+        // Ensure the logging factory is initialized before the static logger field below. When running standalone (via main() or
+        // Gradle's loadCsvSpecData task), nothing has initialized the ES logging system before this class is loaded.
+        LogConfigurator.configureESLogging();
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:68]:
```suggestion
        LogConfigurator.loadLog4jPlugins();
        LogConfigurator.configureESLogging();
```
I believe this fixes the NPE, but does not enable the logging.
Adding `loadLog4jPlugins()` should do that.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/GenerativeRestTest.java [hunk 3]
```diff
@@ -348,6 +367,27 @@ private static boolean isScalarTypeMismatchError(String errorMessage) {
         return SCALAR_TYPE_MISMATCH_PATTERN.matcher(errorWithoutLineBreaks).matches();
     }
 
+    /**
+     * Checks if the error is an {@code ArrayIndexOutOfBoundsException} caused by calling FIRST or LAST
+     * with problematic arguments.
+     * See <a href="https://github.com/elastic/elasticsearch/issues/142180">#142180</a>
+     */
+    private static boolean isFirstLastSameFieldError(String errorMessage, String query) {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/GenerativeRestTest.java:376]: I see we are introducing more fine-grained error checks, I think it makes sense (the big ALLOWED_ERRORS list is good for easy maintenance, but it also tends create blind spots, so ++ to these new checks)

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/GenerativeRestTest.java [hunk 4]
```diff
@@ -71,7 +71,6 @@ public abstract class GenerativeRestTest extends ESRestTestCase implements Query
         "Data too large", // Circuit breaker exceptions eg. https://github.com/elastic/elasticsearch/issues/130072
         "long overflow", // https://github.com/elastic/elasticsearch/issues/135759
         "can't find input for", // https://github.com/elastic/elasticsearch/issues/136596
-        "out of bounds for length", // https://github.com/elastic/elasticsearch/issues/136851
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/GenerativeRestTest.java:74]: 🙏

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!
