### PR TITLE
Buffer H3Polygon2D bounding boxes to avoid edge precision issues

### LINKED ISSUE #87391: [CI] GeoGridAggAndQueryConsistencyIT testGeoPointGeoHex failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/srg3duasuusu2/tests/:x-pack:plugin:spatial:internalClusterTest/org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT/testGeoPointGeoHex

**Reproduction line:**
`./gradlew ':x-pack:plugin:spatial:internalClusterTest' --tests "org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT.testGeoPointGeoHex" -Dtests.seed=5F6BA8290D5CE8A2 -Dtests.locale=nl -Dtests.timezone=Asia/Anadyr -Druntime.java=17`

**Applicable branches:**
8.3

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT&tests.test=testGeoPointGeoHex

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <104L>
     but: was <105L>

  at __randomizedtesting.SeedInfo.seed([5F6BA8290D5CE8A2:F421378D21AF0A17]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT.assertQuery(GeoGridAggAndQueryConsistencyIT.java:220)
  at org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT.doTestGrid(GeoGridAggAndQueryConsistencyIT.java:183)
  at org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT.doTestGeohexGrid(GeoGridAggAndQueryConsistencyIT.java:120)
  at org.elasticsearch.xpack.spatial.search.GeoGridAggAndQueryConsistencyIT.testGeoPointGeoHex(GeoGridAggAndQueryConsistencyIT.java:80)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### LINKED ISSUE #89868: [CI] org.elasticsearch.xpack.spatial.index.query.H3LatLonGeometryTests.testIndexPoints
### CI Link

https://gradle-enterprise.elastic.co/s/752jgoui6up4c/tests/:x-pack:plugin:spatial:test/org.elasticsearch.xpack.spatial.index.query.H3LatLonGeometryTests/testIndexPoints?top-execution=1

### Repro line

`./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.index.query.H3LatLonGeometryTests.testIndexPoints" -Dtests.seed=DFC1C0965EFCD1EB -Dtests.locale=sr-CS -Dtests.timezone=ECT -Druntime.java=17`

Also failed with various other seeds:
* `-Dtests.seed=DFC1C0965EFCD1EB`
* `-Dtests.seed=72BEB29AA48F2C0B`
* `-Dtests.seed=CAF2A0770CD2CC7E`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Stockholm&tests.container=org.elasticsearch.xpack.spatial.index.query.H3LatLonGeometryTests&tests.test=testIndexPoints

### Failure excerpt

    java.lang.AssertionError: expected:<81> but was:<82>

### PR DESCRIPTION
**Pull request by iverase**
We are using lucene spatial3d library to represent the area covered by a H3 bin. Unfortunately the mathematics at the edges are slightly different and the only way to determine if a point is inside or outside of a H3 bin is using the H3 library itself. In order to avoid issues at the edges when computing the spatial relationship of a bounding box with an H3 bin where are:

1) Computing the bounding box of the H3 Bin and expanding it by a factor to check for CELL_OUTSIDE_QUERY.
2) Expanding the inner nodes bounding box by a factor to check for CELL_INSIDE_QUERY.
3) Otherwise we will return  CELL_CROSSES_QUERY.

That should be enough to prevent border issues with a small performance penalty.

fixes https://github.com/elastic/elasticsearch/issues/87391
fixes https://github.com/elastic/elasticsearch/issues/89868

### CODE REVIEW

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java [hunk 1]
```diff
@@ -117,18 +137,22 @@ public boolean contains(double x, double y) {
...
+            // h3 edges are fuzzy, therefore to avoid issues when bounding box are around the edges,
+            // we just buffer slightly the bounding box to check if it is inside the h3 bin, otherwise
+            // return crosses.
+            final GeoArea box = GeoAreaFactory.makeGeoArea(
                 PlanetModel.SPHERE,
-                Math.toRadians(maxY),
-                Math.toRadians(minY),
-                Math.toRadians(minX),
-                Math.toRadians(maxX)
+                Math.toRadians(Math.min(GeoUtils.MAX_LAT_INCL, maxY + BBOX_BUFFER_FRACTION)),
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java:148]: When you calculated the min/max above you used `BBOX_BUFFER_FRACTION * (maxX - minX)`, but here you just use buffer_fraction alone. I think it makes more sense to multiply by the box width, or by the hexagon width.

Comment (craigtaverner) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java:148]:
```suggestion
                Math.toRadians(Math.min(GeoUtils.MAX_LAT_INCL, maxY + BBOX_BUFFER_FRACTION * (maxY - minY))),
```

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java [hunk 2]
```diff
@@ -117,18 +137,22 @@ public boolean contains(double x, double y) {
...
+                Math.toRadians(Math.max(GeoUtils.MIN_LAT_INCL, minY - BBOX_BUFFER_FRACTION)),
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java:149]:
```suggestion
                Math.toRadians(Math.max(GeoUtils.MIN_LAT_INCL, minY - BBOX_BUFFER_FRACTION * (maxY - minY))),
```

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java [hunk 3]
```diff
@@ -117,18 +137,22 @@ public boolean contains(double x, double y) {
...
+                Math.toRadians(Math.max(GeoUtils.MIN_LON_INCL, minX - BBOX_BUFFER_FRACTION)),
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java:150]:
```suggestion
                Math.toRadians(Math.max(GeoUtils.MIN_LON_INCL, minX - BBOX_BUFFER_FRACTION * (maxX - minX))),
```

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java [hunk 4]
```diff
@@ -117,18 +137,22 @@ public boolean contains(double x, double y) {
...
+                Math.toRadians(Math.min(GeoUtils.MAX_LON_INCL, maxX + BBOX_BUFFER_FRACTION))
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java:151]:
```suggestion
                Math.toRadians(Math.min(GeoUtils.MAX_LON_INCL, maxX + BBOX_BUFFER_FRACTION * (maxX - minX)))
```

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java [hunk 5]
```diff
@@ -117,18 +137,22 @@ public boolean contains(double x, double y) {
...
             );
-            return switch (box.getRelationship(hexagon)) {
-                case GeoArea.CONTAINS -> PointValues.Relation.CELL_INSIDE_QUERY;
-                case GeoArea.DISJOINT -> PointValues.Relation.CELL_OUTSIDE_QUERY;
-                default -> PointValues.Relation.CELL_CROSSES_QUERY;
-            };
+            return box.getRelationship(hexagon) == GeoArea.CONTAINS
```
Comment (craigtaverner) [inline x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java:153]: Is there not a case here where it can be outside, but within the buffer?

**Review by craigtaverner — CHANGES_REQUESTED** [review]
I liked this, but did think you needed to use the BUFFER_FRACTION multiplied by the width or height of the cell or search box.

**Comment by craigtaverner** [comment]
Also, it feels like this code should have unit tests to test explicitly for the inside/outside/crosses cases.

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java (hunk 1 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java]: Actually, I just want to increase the edge surface by a fix amount regardless of the size of the bounding box. I have renamed  BBOX_BUFFER_FRACTION to BBOX_EDGE_DELTA and just add a fix value to the edges.

File: x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java (hunk 5 above)
Comment (iverase) [reply x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/query/H3LatLonGeometry.java]: oh yes

**Comment by iverase** [comment]
I am looking into which unit test might make sense here.

**Review by craigtaverner — APPROVED** [review]
Looks much better. Would still be nice with some unit tests, but I like this a lot.

**Comment by craigtaverner** [comment]
I pushed some more tests that test for INSIDE/OUTSIDE/CROSSING for points just inside and just outside the H3 cell, but we see test failures quite often with the randomized test, especially for high latitudes. I think the current `relate` method is not quite working.

**Comment by craigtaverner** [comment]
Also, should this fix remove the `AwaitsFix` annotations on the two tests that have it?
