### PR TITLE
ESQL - enable zero terms query match

### LINKED ISSUE #143070: ESQL: zero_terms_query is not accepted for MATCH even though it should be accepted
### Description

```
from employees
| where match(first_name, "foo", {"zero_terms_query": "all"})
```

results in 

```
"type": "illegal_argument_exception",
"reason": "illegal match option [zero_terms_query]",
"stack_trace": "org.elasticsearch.ElasticsearchException$1: illegal match option [zero_terms_query]
```

While writing 

```
from employees
| where match(first_name, "foo", {"foobar": "all"})
```

will have an error that mention `zero_terms_query` as being accepted:

```
"reason": "Found 1 problem\nline 3:9: Invalid option [foobar] in [match(first_name, \"foo\", {\"foobar\": \"all\"})], expected one of [auto_generate_synonyms_phrase_query, minimum_should_match, prefix_length, lenient, zero_terms_query, analyzer, fuzzy_transpositions, fuzzy_rewrite, fuzziness, max_expansions, boost, operator]",
```

### PR DESCRIPTION
**Pull request by carlosdelest**
`zero_terms_query` didn't get added as an option to match, even if it was documented. This PR adds it.

Closes https://github.com/elastic/elasticsearch/issues/143070

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/MatchQuery.java [hunk 1]
```diff
@@ -28,14 +29,13 @@
...
 import static org.elasticsearch.index.query.MatchQueryBuilder.PREFIX_LENGTH_FIELD;
+import static org.elasticsearch.index.query.MatchQueryBuilder.ZERO_TERMS_QUERY_FIELD;
 
 public class MatchQuery extends Query {
 
     private static final Map<String, BiConsumer<MatchQueryBuilder, Object>> BUILDER_APPLIERS;
 
     static {
-        // TODO: add zero terms query support, I'm not sure the best way to parse it yet...
-        // appliers.put("zero_terms_query", (qb, s) -> qb.zeroTermsQuery(s));
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/querydsl/query/MatchQuery.java:38]: looks like this was a remnant from the time we cloned this from ql 🥲

**Review by ioanatia — APPROVED** [review]

**Review by kkharbas — APPROVED** [review]
LGTM!
