### PR TITLE
Fix median calculation in MedianAbsoluteDeviationAggregatorTests

### LINKED ISSUE #38937: [CI] MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues fails (seed-specific)
My PR build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/8268/console got the following error:

```
FAILURE 0.06s J4 | MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: within <10.0> percent of <447718.0>
   >      but: was <501660.0>
   > 	at __randomizedtesting.SeedInfo.seed([9BA06947D4BA0876:29F621FB9B5A78F0]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.lambda$testSomeMatchesSortedNumericDocValues$6(MedianAbsoluteDeviationAggregatorTests.java:105)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testCase(MedianAbsoluteDeviationAggregatorTests.java:184)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues(MedianAbsoluteDeviationAggregatorTests.java:98)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This reproduces locally using:

```
FAILURE 0.06s J4 | MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: within <10.0> percent of <447718.0>
   >      but: was <501660.0>
   > 	at __randomizedtesting.SeedInfo.seed([9BA06947D4BA0876:29F621FB9B5A78F0]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.lambda$testSomeMatchesSortedNumericDocValues$6(MedianAbsoluteDeviationAggregatorTests.java:105)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testCase(MedianAbsoluteDeviationAggregatorTests.java:184)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues(MedianAbsoluteDeviationAggregatorTests.java:98)
   > 	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by imotov**
Fixes an error in median calculation in
MedianAbsoluteDeviationAggregatorTests for odd number of sample points,
which causes some rare test failures.

Fixes #38937

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/aggregations/metrics/MedianAbsoluteDeviationAggregatorTests.java [hunk 1]
```diff
@@ -260,9 +260,15 @@ public static double calculateMAD(double[] sample) {
...
-            final int halfway =  (int) Math.ceil(sorted.length / 2d);
-            final double median = (sorted[halfway - 1] + sorted[halfway]) / 2d;
+            final int halfway = (int) Math.ceil(sorted.length / 2d);
+            final double median;
+            if (sorted.length % 2 == 0) {
+                // even
+                median = (sorted[halfway - 1] + sorted[halfway]) / 2d;
+            } else {
+                // odd
+                median = (sorted[halfway -1]);
```
Comment (andyb-elastic) [inline server/src/test/java/org/elasticsearch/search/aggregations/metrics/MedianAbsoluteDeviationAggregatorTests.java]: Nit so small I feel bad even mentioning it -  can you change the spacing to `halfway - 1` so it's consistent

**Review by andyb-elastic — APPROVED** [review]
LGTM I should have caught this earlier, thanks for fixing it
