### PR TITLE
ESQL: Fix function registry concurrency issues on constructor

### LINKED ISSUE #123430: ClassCastException in EsqlFunctionRegistry
I encountered a ClassCastException within LinkedHashMap used by ESQL. 
```
 Caused by:	
  java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')	
      at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1995)	
      at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2111)	
      at java.base/java.util.HashMap.treeifyBin(HashMap.java:779)	
      at java.base/java.util.HashMap.putVal(HashMap.java:651)	
      at java.base/java.util.HashMap.put(HashMap.java:619)	
      at org.elasticsearch.xpack.esql.expression.function.EsqlFunctionRegistry.buildDataTypesForStringLiteralConversion(EsqlFunctionRegistry.java:718)	
      at org.elasticsearch.xpack.esql.expression.function.EsqlFunctionRegistry.<init>(EsqlFunctionRegistry.java:234)
```

See https://gradle-enterprise.elastic.co/s/fwqg4ibahnj4s/console-log/task/:x-pack:plugin:esql:internalClusterTest?page=1

I wonder if this is due to concurrent modification?

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/123430

There were 2 problems here:
- We were filling a static field (used to auto-cast string literals) within a constructor, which is also called in multiple places
- The field was only filled with non-snapshot functions, so snapshot function auto-casting wasn't possible

Fixed both bugs by making the field non-static instead, and a fix to use the snapshot registry (if available) in the string casting rule.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java:1]: Is there a reason for this class to not be "static", and the instance getter to not always return the corresponding registry (snapshot or non-snapshot)?
Could be a fairly simple improvement, avoiding recreating those maps again and again

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java [hunk 1]
```diff
@@ -225,6 +223,7 @@ public class EsqlFunctionRegistry {
     private final Map<String, FunctionDefinition> defs = new LinkedHashMap<>();
     private final Map<String, String> aliases = new HashMap<>();
     private final Map<Class<? extends Function>, String> names = new HashMap<>();
+    private final Map<Class<? extends Function>, List<DataType>> dataTypesForStringLiteralConversions = new LinkedHashMap<>();
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/EsqlFunctionRegistry.java:226]: :+1:

**Review by idegtiarenko — APPROVED** [review]

**Review by fang-xing-esql — APPROVED** [review]
LGTM, thank you @ivancea ! Just to be extra cautious, perhaps add `test-releases` label, as a call to `snapshotRegistry` is added.
