### PR TITLE
Fixes DiversifyingParentBlockQueryTests 

### LINKED ISSUE #145732: [CI] DiversifyingParentBlockQueryTests testRandom failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #12056 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/tjbkn42rgbjmi)
- [elasticsearch-periodic-platform-support #12056 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/ztaffeztwgs5k)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.vectors.DiversifyingParentBlockQueryTests.testRandom" -Dtests.seed=BBFD3AB235C87E53 -Dtests.locale=en-CM -Dtests.timezone=Indian/Kerguelen -Druntime.java=25
```

**Applicable branches:**
9.2

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.vectors.DiversifyingParentBlockQueryTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRandom'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: "31"
     but: was "13"
```

**Issue Reasons:**
- [9.2] 1 consecutive failures in test testRandom
- [9.2] 2 consecutive failures in step almalinux-8-aarch64_checkpart1_platform-support-arm
- [9.2] 1 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [9.2] 2 failures in test testRandom (7.4% fail rate in 27 executions)
- [9.2] 2 failures in step almalinux-8-aarch64_checkpart1_platform-support-arm (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by carlosdelest**
Closes #145732

The test `testRandom` with seed `1CF73652307E9E62` fails due to a near-tie score ordering issue introduced (or exposed) when a prior commit (1f724bcaa29) changed the score assertion from exact equality to closeTo(score, 1e-5) to tolerate floating-point differences between EUCLIDEAN.compare and the KNN index's internal computation.                                                        

The score tolerance fix is correct, but it created a new gap: when two documents have expected scores within 1e-5 of each other, they may be returned in a different order by the query (because the KNN index computes slightly different scores and reverses the tie). The test polls expectedTopDocs positionally from a TreeMap<Float, String> and compares document IDs by position — so a  different-but-equally-valid ordering fails the ID assertion.                                                                                                                                       

Failure scenario:
1. Doc A has expected score 0.50001, Doc B has 0.50000 (diff < 1e-5)
2. expectedTopDocs (TreeMap reverse order) orders: A first, B second
3. KNN index computes B slightly higher than A, returns B first
4. Test polls A as first entry, checks returned doc B's ID against "A" → fails                                                                                                                     

Right now, `DiversifyingParentBlockQueryTests` uses  positional polling from a sorted TreeMap<Float, String> and assumes strict score ordering matches between EUCLIDEAN.compare and KNN index scores, which breaks when two documents have near-equal scores.                   

The tests now compares expected scores instead of strict ordering, as there can be docs with very similar scores.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java [hunk 1]
```diff
@@ -130,11 +131,11 @@ public void testRandom() throws IOException {
...
                 for (var doc : topDocs.scoreDocs) {
-                    var entry = expectedTopDocs.get(i).pollFirstEntry();
-                    assertNotNull(entry);
-                    assertThat((double) doc.score, closeTo(entry.getKey(), 1e-5));
                     var storedDoc = storedFields.document(doc.doc, Set.of("id"));
-                    assertThat(storedDoc.getField("id").binaryValue().utf8ToString(), equalTo(entry.getValue()));
+                    var docId = storedDoc.getField("id").binaryValue().utf8ToString();
+                    var expectedScore = expectedTopDocs.get(i).get(docId);
+                    assertNotNull("unexpected doc id: " + docId, expectedScore);
+                    assertThat((double) doc.score, closeTo(expectedScore, 1e-5));
```
Comment (Mikep86) [inline server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java:138]: Should we also check that all expected top docs are returned by the query? Best I can tell, we don't do that right now.

Comment (carlosdelest) [reply server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java:138]: I think implicitly, we do - we're iterating over the topDocs and looking for all of them. So if one is not found, it will be caught by the `assertNotNull`.

Comment (Mikep86) [reply server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java:138]: What if `topDocs` is missing a doc in `expectedTopDocs`?

Comment (carlosdelest) [reply server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java:138]: That could happen if we have tie(s) on the bottom scores. That happened in the previous version of the test as well, correct?

**Review by ioanatia — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java (hunk 1 above)
Comment (Mikep86) [reply server/src/test/java/org/elasticsearch/search/vectors/DiversifyingParentBlockQueryTests.java:138]: I see what I was missing. `expectedTopDocs` contains expected scores for all the docs that _could_ be returned, but since we randomly generate between 10-50 docs and only get 10 search results back, we don't expect the sizes of `topDocs` and `expectedTopDocs` to match.

Sorry for the confusion!

**Review by Mikep86 — APPROVED** [review]
