### PR TITLE
Reset state recovery after successful recovery

### LINKED ISSUE #39172: MinimumMasterNodesIT#testThreeNodesNoMasterBlock failures
Failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/940/consoleText

This [has failed 16 times](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testThreeNodesNoMasterBlock),sort:!(process.time-start,desc))) since it was introduced in https://github.com/elastic/elasticsearch/pull/37428 : 

```
ERROR   92.5s J3 | MinimumMasterNodesIT.testThreeNodesNoMasterBlock <<< FAILURES!
   > Throwable #1: MasterNotDiscoveredException[ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]]; nested: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];];
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:549)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
   > 	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:191)
   > 	at org.elasticsearch.action.admin.cluster.tasks.TransportPendingClusterTasksAction.checkBlock(TransportPendingClusterTasksAction.java:59)
   > 	at org.elasticsearch.action.admin.cluster.tasks.TransportPendingClusterTasksAction.checkBlock(TransportPendingClusterTasksAction.java:37)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:170)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:161)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:138)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:58)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64)
   > 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
   > 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
   > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:65)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
   > 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:676)
   > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
   > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:974)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:931)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:920)
   > 	at org.elasticsearch.cluster.MinimumMasterNodesIT.testThreeNodesNoMasterBlock(MinimumMasterNodesIT.java:268)
   > 	... 1 moreThrowable #2: MasterNotDiscoveredException[ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]]; nested: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];];
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:549)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
   > 	at org.elasticsearch.cluster.block.ClusterBlocks.indicesAllowReleaseResources(ClusterBlocks.java:248)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:81)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:47)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:170)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:161)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:138)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.doExecute(TransportDeleteIndexAction.java:76)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.doExecute(TransportDeleteIndexAction.java:47)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121)
   > 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:79)
   > 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:74)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1077)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)
   > 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1036)
   > 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:922)
   > 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753)
   > 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:780)
   > 	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:241)
   > 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:213)
   > 	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:47)
   > 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119)
   > 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:398)
   > 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
   > 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172)
   > 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129)
   > 	... 1 more
Completed [219/320] on J3 in 97.37s, 3 tests, 1 error <<< FAILURES!
```

### PR DESCRIPTION
**Pull request by ywelsch**
The problem this PR addresses is that state recovery is not reset on a node that then becomes master with a cluster state that has a state not recovered flag in it. The situation that was observed in a failed test run of `MinimumMasterNodesIT.testThreeNodesNoMasterBlock` (see below) is that we have 3 master nodes (node_t0, node_t1, node_t2), two of them are shut down (node_t2 remains), when the first one comes back (renamed to node_t4) it becomes leader in term 2 and sends state (with state_not_recovered_block) to node_t2, which accepts. node_t2 becomes leader in term 3, and as it was previously leader in term1 and successfully completed state recovery, does never retry state recovery in term 3.

Closes #39172

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/gateway/GatewayService.java [hunk 1]
```diff
@@ -256,6 +256,9 @@ public ClusterState execute(final ClusterState currentState) {
         @Override
         public void clusterStateProcessed(final String source, final ClusterState oldState, final ClusterState newState) {
             logger.info("recovered [{}] indices into cluster_state", newState.metaData().indices().size());
+            // reset flag even though state recovery completed, to ensure that if we subsequently become leader again based on a
+            // not-recovered state, that we again do another state recovery.
+            resetRecoveredFlags();
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/gateway/GatewayService.java]: Would it make sense to rename the `recovered` field to `recoveryAllowed` (or something along those lines) since it's not really a one time thing to run recovery now?

**Review by original-brownbear — APPROVED** [review]
LGTM :) (might be best for @DaveCTurner to have a look too, but the fix makes sense to me)

**Review by DaveCTurner — APPROVED** [review]
LGTM
