### PR TITLE
[ML] Wait for the model results on graceful shutdown

### LINKED ISSUE #103414: [ML] Gracefully stopping a deployment times out while closing the pytorch process
### Elasticsearch Version

8.11.3 and above confirmed, but could likely 8.11.0 and above

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

When changing the size of a ML nodes in a cloud deployment, the functionality to stop the deployment gracefully fails with a timeout when closing the pytorch process.

### Steps to Reproduce

1. Download and deploy ELSERv2 `.elser_model_2` with 2 assignments 1 thread each
2. Load the following commands into the dev console

<details><summary>Commands</summary>

```
PUT _snapshot/ml-data-snapshot-share
{
  "type": "gcs",
  "settings": {
    "bucket": "ml-data-snapshots-7-share",
    "client": "default"
  }
}

POST _snapshot/ml-data-snapshot-share/msmarco-datasets/_restore?wait_for_completion=false

PUT msmarco-passage-collection-elser
{
  "mappings": {
    "properties": {
      "body": {
        "type": "text"
      },
      "ml": {
        "properties": {
          "tokens": {
            "type": "rank_features"
          }
        }
      }
    }
  }
}

# Ingest pipeline for ELSER
PUT _ingest/pipeline/elser
{
  "processors": [
    {
      "inference": {
        "model_id": ".elser_model_2",
        "field_map": {
          "body": "text_field"
        },
        "target_field": "ml",
        "inference_config": {
          "text_expansion": {
            "results_field": "tokens"
          }
        }
      }
    }
  ]
}

PUT /_cluster/settings
{
  "transient": {
    "logger._root": "DEBUG"
  }
}

# ELSER-ise the MS MARCO passage collection with reindex
POST _reindex?wait_for_completion=false
{
  "source": {
    "index": "msmarco-passage-collection",
    "size": 100
  },
  "dest": {
    "index": "msmarco-passage-collection-elser",
    "pipeline": "elser"
  }
}

GET _tasks/

```

</details>

3. Execute all commands before the reindex (the reindex will fail until the snapshot index is available)
4. Wait for the snapshot index to appear (index `msmarco-passage-collection`) then start the reindex
5. Filter the discover logs for the cluster with this:

```
message: "Exception closing the running pytorch_inference process"
```

6. Edit the cluster configuration to change the size of the ml nodes (maybe 4gb -> 8gb, keep going up or down repeatedly)
7. You should see the timeout failure shown below

### Logs (if relevant)

```
[instance-0000000007] [.elser_model_2] Exception closing the running pytorch_inference process
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[?:?]
	at org.elasticsearch.xpack.ml.process.AbstractNativeProcess.close(AbstractNativeProcess.java:203) ~[?:?]
	at org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager$ProcessContext.closeProcessIfPresent(DeploymentManager.java:626) ~[?:?]
	at org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager$ProcessContext.stopProcessGracefully(DeploymentManager.java:613) ~[?:?]
	at org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager$ProcessContext.stopProcessAfterCompletingPendingWork(DeploymentManager.java:581) ~[?:?]
	at org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager.stopAfterCompletingPendingWork(DeploymentManager.java:320) ~[?:?]
	at org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeService.lambda$stopDeploymentHelper$29(TrainedModelAssignmentNodeService.java:585) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916) ~[elasticsearch-8.13.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### PR DESCRIPTION
**Pull request by davidkyle**
#103414 shows a timeout exception when the pytorch_inference process is gracefully shutdown. The timeout occurs waiting for the log stream to close but that will not happen until the process has finished processing the queued requests. 

This change waits for that work to complete after closing the input stream but before waiting on the log stream to close.

The error in #103414 does not mean that the process has not stopped properly rather it is a short timeout as at that point it was expected that all the work is complete but this was not the case. The process would continue to shutdown properly. 

Closes #103414

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcess.java [hunk 1]
```diff
@@ -223,7 +223,7 @@ public void close() throws IOException {
      * Implementations can override this if they need to perform extra processing
      * immediately after the native process's input stream is closed.
      */
-    protected void afterProcessInStreamClose() {
+    protected void afterProcessInStreamClose() throws TimeoutException {
```
Comment (maxhniebergall) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcess.java:226]: maybe it would be clearer to say "closed" rather than "close"?

**Review by maxhniebergall — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcess.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcess.java:226]: Let's leave this minor naming concern for a followup. Dave K is off for the rest of the year and if this change is merged today it will be in time for 8.12.0. I'll merge it now.
