### PR TITLE
InternalPercentilesBucket should not rely on ordered percents array

### LINKED ISSUE #24331: Percentiles Bucket Aggregation relies on ordered `percents` array
An interesting edge case that I found when working on #24330: It seems that `percentiles_bucket` relies on the `percents` parameter beeing specifies in increasing order or magnitude. If the list of percentiles to calculate is provided in a different order, e.g.
```
"percentiles_monthly_sales": {
            "percentiles_bucket": {
                "buckets_path": "sales_per_month>sales", 
                "percents": [ 50.0, 25.0, 75.0 ] 
            }
        }
```
the following error is thrown:
```
"type": "illegal_argument_exception",
    "reason": "Percent requested [50.0] was not one of the computed percentiles.  Available keys are: [50.0, 25.0, 75.0]"
```

The reason seems to be that in `InternalPercentileBucket#percentile(double percent)` (https://github.com/elastic/elasticsearch/blob/f217eb8ad8d3ecc82e2f926222b1f036b0d555b7/core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java#L75) the internal array is assumed to be sorted, but we don't enforce this, e.g. in the PercentilesBucketPipelineAggregator or even before when parsing the request.

I think we could either throw an error early if we think the `percents` need to be provided in order, re-sort the array if the user provided it unsorted or change the implementation of `InternalPercentileBucket` so it doesn't rely on an ordered array.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently `InternalPercentilesBucket#percentile()` relies on the percent array passed in to be in sorted order. This changes the aggregation to store an internal lookup table that is constructed from the percent/percentiles arrays passed in that can be used to look up the percentile values.

Closes #24331

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java [hunk 1]
```diff
@@ -31,21 +31,32 @@
...
 public class InternalPercentilesBucket extends InternalNumericMetricsAggregation.MultiValue implements PercentilesBucket {
     private double[] percentiles;
     private double[] percents;
+    transient private final Map<Double, Double> percentileLookups = new HashMap<>();
 
     public InternalPercentilesBucket(String name, double[] percents, double[] percentiles,
                                      DocValueFormat formatter, List<PipelineAggregator> pipelineAggregators,
                                      Map<String, Object> metaData) {
         super(name, pipelineAggregators, metaData);
+        assert percentiles.length == percents.length;
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java]: Maybe we should even throw an error if this is not the case, wdyt?

Comment (polyfractal) [inline core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java]: ++ I can't see anything good happening if they aren't the same length.  The Iterator for example will throw an out-of-range exception if they don't match

**Comment by polyfractal** [comment]
I'm wondering if we should perhaps use a map from the start, rather than converting from the double arrays?  E.g. in `PercentilesBucketPipelineAggregator#buildAggregation()`, we just build a map from the beginning and pass that to `InternalPercentilesBucket`'s ctor.

But maybe there's a reason not to that I haven't thought about.  The current code LGTM otherwise :)

**Comment by cbuescher** [comment]
@polyfractal thanks for the review, I didn't change the ctor arguments and the underlying implementation because we still want to maintain the original order of the percents the user supplied (ok, that could be solved with a sorted map) and also because currently the serialization relies on reading/writing double arrays. I didn't want to break that at this point. If you think its worth it let me know...

**Comment by polyfractal** [comment]
Ah good point re: serialization and user values.  Ignore me!

**Review by polyfractal — APPROVED** [review]

File: core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java (hunk 1 above)
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java]: I will change this to throw an IllegalArgumentException then and add a test for it.
