### PR TITLE
SniffNodesSampler should close connection after handling responses

### LINKED ISSUE #24557: Elasticsearch Transport Client fails to recovery connection after cluster restart
**Elasticsearch version**:
5.4.0

**Plugins installed**:
Node

**JVM version**:
1.8.0_102

**OS version**:
Linux globevm 2.6.18-194.el5 #1 SMP Tue Mar 16 21:52:39 EDT 2010 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I'm using Elasticsearch 5.4.0 with Transport Client with the following problems:
 - you must launch the application several times before it can connect to the cluster.
 - when connection is established, after a cluster restart, the connection is no more recovered, with this stack:

```
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{s-HKw1m4S9aMgCkx5iBuYg}{192.168.203.128}{192.168.203.128:9500}]]
at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:348)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:246)
at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:69)
```

The Transport Client is setting as following:
```
        Settings.Builder settingsBuilder = Settings.builder();

		settingsBuilder.put("cluster.name", "globevmes5");
		settingsBuilder.put("client.transport.sniff", true);
		 	
		client = new PreBuiltTransportClient(settingsBuilder.build());
		try {
			client.addTransportAddress(new 
                              InetSocketTransportAddress(InetAddress.getByName("192.168.203.128"), 9500));
			
		} catch (Exception e) {
			System.out.println(e.getMessage());	
		}
```

Elastic node configuration:
 - network.host: 192.168.203.128
 - http.port: 9400
 - transport.profiles.default.port: 9500-9600

With previous Elasticsearch 5.3.2 it worked fine.
Setting "client.transport.sniff" to false works fine.

**Provide logs**:
Elastic node log:

```
[2017-05-09T11:14:24,336][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: /tmp/jna--1077556979/jna7634687564598757394.tmp: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /tmp/jna--1077556979/jna7634687564598757394.tmp)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_102]
        at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_102]
        at java.lang.System.load(System.java:1086) ~[?:1.8.0_102]
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947) ~[jna-4.4.0.jar:4.4.0 (b0)]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922) ~[jna-4.4.0.jar:4.4.0 (b0)]
        at com.sun.jna.Native.<clinit>(Native.java:190) ~[jna-4.4.0.jar:4.4.0 (b0)]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_102]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_102]
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:204) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.4.0.jar:5.4.0]
[2017-05-09T11:14:24,342][WARN ][o.e.b.Natives            ] cannot check if running as root because JNA is not available
[2017-05-09T11:14:24,342][WARN ][o.e.b.Natives            ] cannot register console handler because JNA is not available
[2017-05-09T11:14:24,344][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2017-05-09T11:14:24,344][WARN ][o.e.b.Natives            ] cannot getrlimit RLIMIT_AS beacuse JNA is not available
[2017-05-09T11:14:24,493][INFO ][o.e.n.Node               ] [globevmes5-node] initializing ...
[2017-05-09T11:14:24,615][INFO ][o.e.e.NodeEnvironment    ] [globevmes5-node] using [1] data paths, mounts [[/methode (/dev/mapper/VolGroup01-LogVol02)]], net usable_space [8.1gb], net total_space [72.8gb], spins? [possibly], types [ext3]
[2017-05-09T11:14:24,615][INFO ][o.e.e.NodeEnvironment    ] [globevmes5-node] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-05-09T11:14:24,659][INFO ][o.e.n.Node               ] [globevmes5-node] node name [globevmes5-node], node ID [M1_iHcSKRX6wHkD_Va0uDg]
[2017-05-09T11:14:24,659][INFO ][o.e.n.Node               ] [globevmes5-node] version[5.4.0], pid[31204], build[780f8c4/2017-04-28T17:43:27.229Z], OS[Linux/2.6.18-194.el5/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_102/25.102-b14]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [aggs-matrix-stats]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [ingest-common]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [lang-expression]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [lang-groovy]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [lang-mustache]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [lang-painless]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [percolator]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [reindex]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [transport-netty3]
[2017-05-09T11:14:26,981][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded module [transport-netty4]
[2017-05-09T11:14:26,982][INFO ][o.e.p.PluginsService     ] [globevmes5-node] loaded plugin [eom-elasticsearch-plugin]
[2017-05-09T11:14:28,406][INFO ][o.e.d.DiscoveryModule    ] [globevmes5-node] using discovery type [zen]
[2017-05-09T11:14:28,972][INFO ][o.e.n.Node               ] [globevmes5-node] initialized
[2017-05-09T11:14:28,972][INFO ][o.e.n.Node               ] [globevmes5-node] starting ...
[2017-05-09T11:14:29,100][INFO ][o.e.t.TransportService   ] [globevmes5-node] publish_address {192.168.203.128:9500}, bound_addresses {192.168.203.128:9500}
[2017-05-09T11:14:29,106][INFO ][o.e.b.BootstrapChecks    ] [globevmes5-node] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-05-09T11:14:32,227][INFO ][o.e.c.s.ClusterService   ] [globevmes5-node] new_master {globevmes5-node}{M1_iHcSKRX6wHkD_Va0uDg}{j8GR_IGFSfW2y502jd-SKA}{192.168.203.128}{192.168.203.128:9500}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-05-09T11:14:32,379][INFO ][o.e.h.n.Netty4HttpServerTransport] [globevmes5-node] publish_address {192.168.203.128:9400}, bound_addresses {192.168.203.128:9400}
[2017-05-09T11:14:32,386][INFO ][o.e.n.Node               ] [globevmes5-node] started
[2017-05-09T11:14:32,590][INFO ][o.e.g.GatewayService     ] [globevmes5-node] recovered [6] indices into cluster_state
[2017-05-09T11:14:33,173][INFO ][o.e.c.r.a.AllocationService] [globevmes5-node] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
[2017-05-09T11:15:02,357][INFO ][o.e.c.r.a.DiskThresholdMonitor] [globevmes5-node] low disk watermark [85%] exceeded on [M1_iHcSKRX6wHkD_Va0uDg][globevmes5-node][/methode/meth01/mnt/elasticsearch-5.4.0/data/nodes/0] free: 8.1gb[11.1%], replicas will not be assigned to this node 
```

### LINKED ISSUE #24575: 5.4.0 transport client failed to get local cluster state while using 5.3.0 to connect to 5.4.0 servers works
Hi, I have a rest service using Netty as basis and connecting to ElasticSearch backend via java transport client API.
It worked very well with Netty 4.1.8 and ES 5.3.0.
Now I tried to upgrade ES backend and transport client to 5.4.0,  and also Netty to 4.1.9.  Then following problems happened:

10 May 2017;17:01:59.645 Developer linux-68qh [elasticsearch[_client_][generic][T#3]] INFO  o.e.c.t.TransportClientNodesService - failed to get local cluster state for {#transport#-1}{WlTQjgcGQ1uqyNNsw4ZnAw}{127.0.0.1}{127.0.0.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9300][cluster:monitor/state] request_id [7] timed out after [5001ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:925)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I roll back the transport client to 5.3.0 but keep backend 5.4.0. 

Then it is able to connect to Es backend.
I use SBT and the build dependencies for the error are:

"io.netty" % "netty-all" % "4.1.9.Final"
"org.elasticsearch" % "elasticsearch" % "5.4.0"
 "org.elasticsearch.client" % "transport" % "5.4.0",
and "io.netty" % "netty-transport-native-epoll" % "4.1.9.Final" classifier "linux-x86_64"

Environment:

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (suse-3.3-x86_64)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

Linux linux-68qh 4.10.13-1-default #1 SMP PREEMPT Thu Apr 27 12:23:31 UTC 2017 (e5d11ce) x86_64 x86_64 x86_64 GNU/Linux

Thanks

### PR DESCRIPTION
**Pull request by tlrx**
With the current implementation, `SniffNodesSampler` might close the
current connection right after a request is sent but before the response
is correctly handled. This causes to timeouts in the transport client
when the sniffing is activated in all versions since #22828.

closes #24575
closes #24557

### CODE REVIEW

**Comment by tlrx** [comment]
@bleskes @jasontedor the PR does not have tests, I created it to point it to you what _I think_ is the cause of #24575 (and also the deleted #24557). I'd be happy if you could confirm or invalidate that this is the cause of transport client exceptions.

File: core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java [hunk 1]
```diff
@@ -470,11 +470,6 @@ protected void doSample() {
                         Transport.Connection connectionToClose = null;
 
                         @Override
-                        public void onAfter() {
-                            IOUtils.closeWhileHandlingException(connectionToClose);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: we also need to close the connection in `public void onFailure(Exception e) {` since we might get rejected or something like this.

File: client/transport/src/main/resources/log4j2.properties [hunk 2]
```diff
@@ -0,0 +1,7 @@
+appender.console.type = Console
```
Comment (s1monw) [inline client/transport/src/main/resources/log4j2.properties]: this is unrelated?

File: client/transport/src/main/java/TestClient.java [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+package PACKAGE_NAME;
+
+/**
+ * Created by tanguy on 11/05/17.
+ */
+public class TestClient {
```
Comment (s1monw) [inline client/transport/src/main/java/TestClient.java]: this is unrelated?

File: core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java [hunk 4]
```diff
@@ -535,8 +531,13 @@ public void handleException(TransportException e) {
                                         }
                                         finally {
                                             latch.countDown();
+                                            closeConnection();
                                         }
                                     }
+
+                                    void closeConnection() {
+                                        IOUtils.closeWhileHandlingException(connectionToClose);
+                                    }
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: testing will be tricky but doable. I have some ideas here similar to what I did on `RemoteClusterConnectionTests` where we basically mock the calls to clusterstate and return a pre-build state but we can also put some sleeps into it.

**Review by s1monw — CHANGES_REQUESTED** [review]
the fix looks good to me, left some comments. good catch.

**Comment by s1monw** [comment]
one thing that I am puzzled about is why this causes timeouts instead of triggering onException on the handler? I think the reason is that we don't notify the TransportService when a connection is closed but only if a node is disconnected that is a different bug here. Both are independent and should be handled independently. so I think your fix is sufficient for the issues referenced in the description.

**Comment by s1monw** [comment]
I opened #24639 for the notification part

**Comment by s1monw** [comment]
I also marked this as a blocker for 5.4.1

File: core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java [hunk 5]
```diff
@@ -523,6 +518,7 @@ public String executor() {
                                     public void handleResponse(ClusterStateResponse response) {
                                         clusterStateResponses.put(nodeToPing, response);
                                         latch.countDown();
+                                        closeConnection();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: maybe we should unify the `latch.countDown()` and `closeConnection()` into a single method called "onDone" on the AbstractRunnable that everyone calls? this it's less trappy and people wouldn't forget to do one but not the other.

**Review by bleskes — APPROVED** [review]
Great catch. LGTM (although I left one suggestion).

File: core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java (hunk 4 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: I wrote a test which would have failed before the fix. That would be great if you can have a look.

File: client/transport/src/main/java/TestClient.java (hunk 3 above)
Comment (tlrx) [inline client/transport/src/main/java/TestClient.java]: Yes, this should not have been commited, thanks.

**Comment by tlrx** [comment]
> one thing that I am puzzled about is why this causes timeouts instead of triggering onException on the handler? I think the reason is that we don't notify the TransportService when a connection is closed but only if a node is disconnected that is a different bug here. Both are independent and should be handled independently. so I think your fix is sufficient for the issues referenced in the description.

I agree - I didn't spot this problem but my knowledge of the TransportService is limited, I'm glad you already proposed a fix.

I updated the PR according to your comments.

**Review by s1monw — APPROVED** [review]
LGTM 2 thx for the test

File: core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java [hunk 6]
```diff
@@ -469,14 +469,14 @@ protected void doSample() {
                          */
                         Transport.Connection connectionToClose = null;
 
-                        @Override
-                        public void onAfter() {
+                        void onDone() {
                             IOUtils.closeWhileHandlingException(connectionToClose);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: can we call the latch in a finally block just to be absolutely sure

Comment (tlrx) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java]: Sure

**Comment by tlrx** [comment]
Thanks @s1monw @bleskes

**Comment by konste** [comment]
I'm getting exactly this error with the version 5.4.1 across the board. What's the quickest way for me to recover?

**Comment by tlrx** [comment]
@konste I just ran another test this morning with a fresh 5.4.1 installation and a PreBuiltTransportClient with sniff option set to true and everything worked as expected (while the error was really obvious and appears at startup time).

Can you please provide the logs of both transport client and elasticsearch node please? As well as the transport client settings?

**Comment by konste** [comment]
@tlrx Sorry I had to restore functionality ASAP and lost the repro.
