### PR TITLE
XContentBuilder: Avoid building self-referencing objects

### LINKED ISSUE #19475: Stack overflow in Painless
The following produces a stack overflow in Painless:

    POST t/t/1/_update
    {
      "upsert": {},
      "scripted_upsert": true,
      "script": {
        "lang": "painless",
        "inline": "for (def key : params.keySet()) { ctx._source[key] = params[key]}"
      }, 
      "params": {
          "bar": "two",
          "baz": "two"
      }
    }

### LINKED ISSUE #20540: Painless script referencing "params" object causes StackOverflowError
**Elasticsearch version**: 5.0.0-beta1

**JVM version**: Oracle 1.8.0_73 64-bit

**OS version**: Linux

**Description of the problem including expected versus actual behavior**:
A script that references `params` (not `params.foo`) causes StackOverflowError.  For example, `ctx.baz = params` (instead of `ctx.baz = params.foo`)

**Steps to reproduce**:

    POST _ingest/pipeline/_simulate
    {
      "pipeline" :
      {
        "description": "_description",
        "processors": [
          {
            "script":
            {
              "lang": "painless",
              "inline": "ctx.baz = params",
              "params": 
              {
                "foo" : "bar"
              }
            }
          }
        ]
      },
      "docs": [
        {
          "_index": "index",
          "_type": "type",
          "_id": "id",
          "_source": {
            "field_a": 3
          }
        }
      ]
    }

**Provide logs (if relevant)**:

    [2016-09-18T20:33:02,224][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[wImoedg][management][T#3]], exiting
    java.lang.StackOverflowError
            at java.util.Collections$UnmodifiableMap.get(Collections.java:1454) ~[?:1.8.0_73]
            at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:799) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:865) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:806) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:865) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:806) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:865) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:806) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:865) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:806) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
            at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:865) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
     ...

Noticed this when I had a typo in a script that subsequently caused my ingest node to shut down due to the stack overflow error.  Is there anything we can do to protect against this?

### PR DESCRIPTION
**Pull request by tlrx**
Some objects like maps, iterables or arrays of objects can self-reference themselves. This is mostly due to a bug in code but the XContentBuilder should be able to detect such situations and throws an IllegalArgumentException instead of building objects over and over until a stackoverflow occurs.

closes #20540
closes #19475

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java [hunk 1]
```diff
@@ -133,6 +135,12 @@ public static XContentBuilder builder(XContent xContent, Set<String> includes, S
     private boolean humanReadable = false;
 
     /**
+     * Keeps around a list of objects that have been built. This list is checked whenever a map/list/iterable object
+     * is built to avoid endless loops when building objects that self-reference themselves.
+     */
+    private final List<Object> ancestors = new ArrayList<>();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: This should probably be an IdentityHashSet.

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java [hunk 2]
```diff
@@ -999,6 +1017,17 @@ public String string() throws IOException {
...
 
+    /**
+     * Checks that a given object has not already been built. Throws an {@link IllegalArgumentException} otherwise. This
+     * prevents stackoverflow errors to occur when building self-referencing objects.
+     */
+    void ensureNotSeen(Object value) {
+        if (ancestors.contains(value)) {
+            throw new IllegalArgumentException("Object has already been built and is self-referencing itself");
+        }
+        ancestors.add(value);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: could be just `if (ancestors.add(value) == false)` when moving to a set

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java [hunk 3]
```diff
@@ -856,9 +866,15 @@ public XContentBuilder field(String name, Map<String, Object> values) throws IOE
     }
 
     public XContentBuilder map(Map<String, ?> values) throws IOException {
+        return value(values);
+    }
+
+    private XContentBuilder value(Map<String, ?> values) throws IOException {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: why does the split help?

**Review by jpountz — COMMENTED** [review]
I like the idea but on the other hand I can see this causing issues too. For instance it forces to keep objects that are used to build the xcontent around until the builder is closed. The other thing we should look into is whether this has an impact on performance.

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java (hunk 1 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: I didn't know about this one, thanks

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java (hunk 3 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: Oh, it's a leftover.

**Comment by tlrx** [comment]
@jpountz Thanks for your review, I updated the code.

> I like the idea but on the other hand I can see this causing issues too. For instance it forces to keep objects that are used to build the xcontent around until the builder is closed. 

Yes, it is not ideal but I don't see how we could prevent endless recursive calls without it.

> The other thing we should look into is whether this has an impact on performance.

It will have some impact but I don't expect it to be big. I can run some Rally tests if you find the idea of keeping objects around acceptable...?

**Comment by jpountz** [comment]
> >     For instance it forces to keep objects that are used to build the xcontent around until the builder is closed.
> >
>
>Yes, it is not ideal but I don't see how we could prevent endless recursive calls without it.

I am a bit torn about the benefit of adding this protection vs. the potential problems that retaining objects could cause. @jasontedor Maybe you have an opinion about this?

> It will have some impact but I don't expect it to be big. I can run some Rally tests if you find the idea of keeping objects around acceptable...?

For that part, I'd also be fine with just watching the nightly benchmarks to see whether there is a noticeable slow down, just wanted to mention it as I have no idea how much xcontent building is used at index time. At search time, I am pretty sure this change would be ok.

**Comment by clintongormley** [comment]
Tried out this PR against master and it causes problems.  Try running the following:

    PUT t/t/1 
    {}
    
    GET _search
    {
      "script_fields": {
        "FIELD": {
          "script": {
            "lang": "painless",
            "inline": "while (true) {}"
          }
        }
      }
    }

The second request hangs and the logs show:

<details>

    [elasticsearch] [2016-09-20T11:17:03,253][INFO ][o.e.c.m.MetaDataCreateIndexService] [od38nkP] [t] creating index, cause [auto(index api)], templates [], shards [5]/[1], mappings []
    [elasticsearch] [2016-09-20T11:17:03,529][INFO ][o.e.c.m.MetaDataMappingService] [od38nkP] [t/1o_LC2B5RSmfcCOQuMo7TQ] create_mapping [t]
    [elasticsearch] [2016-09-20T11:17:20,963][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] [t][3], node[od38nkPUS6qGK4lVOJt7xA], [P], s[STARTED], a[id=Ym46EKCuQi-9Ulp2tUcmNw]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
    [elasticsearch]   "script_fields" : {
    [elasticsearch]     "FIELD" : {
    [elasticsearch]       "script" : {
    [elasticsearch]         "inline" : "while (true) {}",
    [elasticsearch]         "lang" : "painless"
    [elasticsearch]       },
    [elasticsearch]       "ignore_failure" : false
    [elasticsearch]     }
    [elasticsearch]   },
    [elasticsearch]   "ext" : { }
    [elasticsearch] }}]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
    [elasticsearch] [2016-09-20T11:17:20,959][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] [t][0], node[od38nkPUS6qGK4lVOJt7xA], [P], s[STARTED], a[id=LagGIpbwQ8eEuBOaRurFxg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
    [elasticsearch]   "script_fields" : {
    [elasticsearch]     "FIELD" : {
    [elasticsearch]       "script" : {
    [elasticsearch]         "inline" : "while (true) {}",
    [elasticsearch]         "lang" : "painless"
    [elasticsearch]       },
    [elasticsearch]       "ignore_failure" : false
    [elasticsearch]     }
    [elasticsearch]   },
    [elasticsearch]   "ext" : { }
    [elasticsearch] }}] lastShard [true]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
    [elasticsearch] [2016-09-20T11:17:20,955][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] [t][1], node[od38nkPUS6qGK4lVOJt7xA], [P], s[STARTED], a[id=ILZq67vnSBucWOe7OlhAzA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
    [elasticsearch]   "script_fields" : {
    [elasticsearch]     "FIELD" : {
    [elasticsearch]       "script" : {
    [elasticsearch]         "inline" : "while (true) {}",
    [elasticsearch]         "lang" : "painless"
    [elasticsearch]       },
    [elasticsearch]       "ignore_failure" : false
    [elasticsearch]     }
    [elasticsearch]   },
    [elasticsearch]   "ext" : { }
    [elasticsearch] }}] lastShard [true]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
    [elasticsearch] [2016-09-20T11:17:20,955][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] [t][4], node[od38nkPUS6qGK4lVOJt7xA], [P], s[STARTED], a[id=mWpdJMDJSpyizNdZTODSCA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
    [elasticsearch]   "script_fields" : {
    [elasticsearch]     "FIELD" : {
    [elasticsearch]       "script" : {
    [elasticsearch]         "inline" : "while (true) {}",
    [elasticsearch]         "lang" : "painless"
    [elasticsearch]       },
    [elasticsearch]       "ignore_failure" : false
    [elasticsearch]     }
    [elasticsearch]   },
    [elasticsearch]   "ext" : { }
    [elasticsearch] }}] lastShard [true]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
    [elasticsearch] [2016-09-20T11:17:20,972][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] All shards failed for phase: [query]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
    [elasticsearch] [2016-09-20T11:17:20,956][DEBUG][o.e.a.s.TransportSearchAction] [od38nkP] [t][2], node[od38nkPUS6qGK4lVOJt7xA], [P], s[STARTED], a[id=qIRetOuwShW0KbrA7gN14A]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
    [elasticsearch]   "script_fields" : {
    [elasticsearch]     "FIELD" : {
    [elasticsearch]       "script" : {
    [elasticsearch]         "inline" : "while (true) {}",
    [elasticsearch]         "lang" : "painless"
    [elasticsearch]       },
    [elasticsearch]       "ignore_failure" : false
    [elasticsearch]     }
    [elasticsearch]   },
    [elasticsearch]   "ext" : { }
    [elasticsearch] }}] lastShard [true]
    [elasticsearch] org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]  :distriat org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_73]
    [elasticsearch] [2016-09-20T11:17:20,979][WARN ][r.suppressed             ] path: /_search, params: {}
    [elasticsearch] org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
    [elasticsearch]         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:235) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:170) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:954) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1055) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1033) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.onFailure(TransportService.java:559) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:490) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch] Caused by: org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch] Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         ... 3 more
    [elasticsearch] Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]         at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]         at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         ... 3 more

</details>

    [elasticsearch] [2016-09-20T11:17:21,116][ERROR][o.e.r.a.RestResponseListener] failed to send failure response
    [elasticsearch] java.lang.IllegalArgumentException: Object has already been built and is self-referencing itself

<details>

    [elasticsearch]         at org.elasticsearch.common.xcontent.XContentBuilder.ensureNotSeen(XContentBuilder.java:1021) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:890) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:883) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.script.ScriptException.innerToXContent(ScriptException.java:92) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:243) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:310) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.ShardSearchFailure.toXContent(ShardSearchFailure.java:164) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.SearchPhaseExecutionException.innerToXContent(SearchPhaseExecutionException.java:143) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:243) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:310) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:146) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:92) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:83) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:97) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onFailure(TransportAction.java:254) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.AbstractSearchAsyncAction.raiseEarlyFailure(AbstractSearchAsyncAction.java:329) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:235) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:170) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:954) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1055) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1033) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.transport.TransportService$6.onFailure(TransportService.java:559) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:490) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch]         Suppressed: org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
    [elasticsearch]           at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:235) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:170) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:954) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1055) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1033) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportService$6.onFailure(TransportService.java:559) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:490) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
    [elasticsearch]           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
    [elasticsearch]           at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
    [elasticsearch]         Caused by: org.elasticsearch.transport.RemoteTransportException: [od38nkP][127.0.0.1:9300][indices:data/read/search[phase/query]]
    [elasticsearch]         Caused by: org.elasticsearch.script.ScriptException: compile error
    [elasticsearch]           at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
    [elasticsearch]           at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           ... 3 more
    [elasticsearch]         Caused by: java.lang.IllegalArgumentException: While loop has no escape.
    [elasticsearch]           at org.elasticsearch.painless.Executable$Script.compile(while (true) {} @ <inline script>:1) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.node.SWhile.analyze(SWhile.java:74) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
    [elasticsearch]           at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]           at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
    [elasticsearch]           at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
    [elasticsearch]           at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.script.ScriptService.search(ScriptService.java:490) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.parseSource(SearchService.java:738) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.createContext(SearchService.java:534) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:501) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$667(SearchTransportService.java:276) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
    [elasticsearch]           ... 3 more

</details>

**Comment by tlrx** [comment]
@jpountz I changed this PR to try something slightly different. It now checks the map before building it. This way it only keeps objects references during the check. It is still not perfect but I'd like to have your opinion on this. Thanks

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java [hunk 4]
```diff
@@ -1012,4 +1028,49 @@ static void ensureNotNull(Object value, String message) {
...
+    private static Object ensureNoSelfReferences(final Object value, final Set<Object> ancestors) {
+        if (value != null) {
+
+            Iterator it = null;
+            if (value instanceof Map) {
+                it = ((Map) value).values().iterator();
+            } else if ((value instanceof Iterable) && (value instanceof Path == false)) {
+                it = ((Iterable) value).iterator();
+            } else if (value instanceof Object[]) {
+                it = new Iterator<Object>() {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: let's use Arrays.asList?

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java [hunk 5]
```diff
@@ -1012,4 +1028,49 @@ static void ensureNotNull(Object value, String message) {
...
+                    public boolean hasNext() {
+                        return index < array.length;
+                    }
+
+                    @Override
+                    public Object next() {
+                        return array[index++];
+                    }
+                };
+            }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: let's throw an exception in the else clause since it should never happen if I read the rest of the code correctly?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: and remove the below null check

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java (hunk 4 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: actually it would be easier to create an iterable than in iterator I think?

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java (hunk 5 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: otherwise I would be happy to just return in the else block and remove the instanceof check in the while loop below

**Review by jpountz — CHANGES_REQUESTED** [review]
I like it better. I left a couple comments.

**Comment by tlrx** [comment]
@jpountz I updated the code according to your comments. Can you please have another look? Thanks

File: core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java [hunk 6]
```diff
@@ -1012,4 +1028,32 @@ static void ensureNotNull(Object value, String message) {
...
     }
+
+    static void ensureNoSelfReferences(Object value) {
+        ensureNoSelfReferences(value, Collections.newSetFromMap(new IdentityHashMap<>()));
+    }
+
+    private static void ensureNoSelfReferences(final Object value, final Set<Object> ancestors) {
+        if (value != null) {
+
+            Iterable it;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java]: can you use wildcard generics to avoid compiler warnings? (`Iterable<?>`)

**Review by jpountz — APPROVED** [review]
I left one minor comment, otherwise LGTM.

**Comment by tlrx** [comment]
retest this please

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @jpountz

**Comment by s1monw** [comment]
I wonder if we should only do this when assertions are enabled? it looks like there are many recursions happening etc.

**Comment by jpountz** [comment]
The point seems to be about avoiding the stack overflow on production clusters, so I don't think only doing it when assertions are on would help?

**Comment by tlrx** [comment]
Assertions are enabled only for tests, right? Here we want to throw an exception if we know that the `XContentBuilder` is going to enter an infinite recursive state when building a self-referencing map at runtime.

**Comment by s1monw** [comment]
fair enough
