### PR TITLE
datafeed: check remote_cluster_client before cluster aliases in start

### LINKED ISSUE #121149: Improve exception handling when master node is missing remote_cluster_client role
### Elasticsearch Version

8.18.0, 9.0.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

When the master node doesn't have the `remote_cluster_client` role, and CCS is used, then `RemoteClusterLicenseChecker.remoteClusterAliases` will return `no_such_remote_cluster_exception,` which is misleading. 

There's probably a bug in `ClusterNameExpressionResolver`. We should be reporting this as an `IllegalArgumentException` as we do in `RemoteClusterService`.

### Steps to Reproduce

1. Create a cluster where the master doesn't have `remote_cluster_client`, while the ML node has (probably ECK config)
2. Create a remote cluster with the sample index
3. Create an anomaly detection jobs using CCS from the remote index
4. Open the job and start the datafeed. The error occurs on the datafeed start.

### Logs (if relevant)

Here is an exemplary error stack trace:

```
POST _ml/datafeeds/datafeed-test-job/_start?error_trace

{
"error": {
"root_cause": [
{
"type": "no_such_remote_cluster_exception",
"reason": "no such remote cluster: [my-remote-cluster-alias]",
"stack_trace": """org.elasticsearch.transport.NoSuchRemoteClusterException: no such remote cluster: [my-remote-cluster-alias]
at org.elasticsearch.cluster.metadata.ClusterNameExpressionResolver.resolveClusterNames(ClusterNameExpressionResolver.java:42)
at org.elasticsearch.license.RemoteClusterLicenseChecker.lambda$remoteClusterAliases$1(RemoteClusterLicenseChecker.java:278)
at java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:289)
at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
at org.elasticsearch.license.RemoteClusterLicenseChecker.remoteClusterAliases(RemoteClusterLicenseChecker.java:280)
at org.elasticsearch.xpack.ml.action.TransportStartDatafeedAction.lambda$masterOperation$3(TransportStartDatafeedAction.java:233)
at org.elasticsearch.xpack.ml.action.TransportStartDatafeedAction.lambda$masterOperation$4(TransportStartDatafeedAction.java:283)
at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:257)
at org.elasticsearch.xpack.ml.job.persistence.JobConfigProvider.parseJobLenientlyFromSource(JobConfigProvider.java:763)
at org.elasticsearch.xpack.ml.job.persistence.JobConfigProvider$1.onResponse(JobConfigProvider.java:175)
at org.elasticsearch.xpack.ml.job.persistence.JobConfigProvider$1.onResponse(JobConfigProvider.java:166)
at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:203)
at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:197)
at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:336)
at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:97)
at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:49)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1500)
at org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:434)
at org.elasticsearch.transport.InboundHandler$2.doRun(InboundHandler.java:391)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.lang.Thread.run(Thread.java:1575)
```

### PR DESCRIPTION
**Pull request by schase-es**
TransportStartDatafeedAction previously tried to validate remote index cluster names in datafeed jobs, before checking if the local cluster had remote_cluster_client role. Because this role enables retrieval of the remote cluster names, the validation step would always fail with a no-such-cluster exception. This was confusing. This change moves the remote_cluster_client check ahead of cluster name validation, and adds a test.

Closes ES-11841
Closes: #121149

### CODE REVIEW

**Comment by schase-es** [comment]
Including David Kyle as the last person who edited these, as an FYI... this area seems to have limited distributed coordination involvement in the past.

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java [hunk 1]
```diff
@@ -0,0 +1,196 @@
...
+import java.io.IOException;
+import java.util.regex.Pattern;
+
+/**
+ * A test to check that remote_cluster_client errors are correctly reported when a datafeed job is started.
+ * The local datafeed job references a remote index in a local anomaly detection job. When the
+ * remote_cluster_client role is missing in the local cluster. This prevents remote indices from being
+ * resolved to their cluster names.
+ *
+ * Written to address github issue 121149.
```
Comment (nicktindall) [inline modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Nit: Perhaps
`@see <a href="https://github.com/elastic/elasticsearch/issues/121149">GitHub issue 121149</a>`
or similar? I think it'll look nicer in javadoc/mouse-overs

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+
+            final Request startRequest = new Request("POST", "_ml/datafeeds/test_datafeed/_start");
+            request.setJsonEntity("""
+                {
+                    "start": "2019-04-07T18:22:16Z"
+                }
+                """);
+            try {
+                localClient.performRequest(startRequest);
+                assertTrue("This request should fail", false);
```
Comment (nicktindall) [inline modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: More succinct to use 
```java
ResponseException e = assertThrows(ResponseException.class, () -> localClient.performRequest(startRequest);
```

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+            } catch (ResponseException e) {
+                String[] messages = e.getMessage().split("\n");
+                assertTrue(Pattern.matches("""
+                    .*Datafeed \\[test_datafeed\\] is configured with a remote index pattern\\(s\\) \
+                    \\[remote_cluster:remote_index\\] but the current node \\[local_cluster-0\\] \
+                    is not allowed to connect to remote clusters. Please enable node.remote_cluster_client \
+                    for all machine learning nodes and master-eligible nodes.*""", messages[1]));
```
Comment (nicktindall) [inline modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: I wonder if `org.elasticsearch.common.regex.Regex#simpleMatch(java.lang.String, java.lang.String, boolean)` might be more forgiving/readable? it just uses wildcard characters rather than regex syntax.

**Review by nicktindall — APPROVED** [review]
Some minor nits, but this LGTM. Please wait until we've got approval from someone in ML before merging though, because I'm not 100% familiar with this code.

(specific question to someone more familiar with the code would be - is this the best place to do the check? Node roles are immutable, so we could do the check when the job is created, but the master could change to one that does have the role between creation and starting, and then everything would be fine? so perhaps start is the right place?)

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDatafeedAction.java [hunk 4]
```diff
@@ -223,6 +223,19 @@ public void onFailure(Exception e) {
...
+                    responseHeaderPreservingListener.onFailure(
+                        ExceptionsHelper.badRequestException(
+                            Messages.getMessage(
+                                Messages.DATAFEED_NEEDS_REMOTE_CLUSTER_SEARCH,
+                                datafeedConfigHolder.get().getId(),
+                                RemoteClusterLicenseChecker.remoteIndices(datafeedConfigHolder.get().getIndices()),
+                                clusterService.getNodeName()
+                            )
+                        )
+                    );
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDatafeedAction.java:240]:
```suggestion
                    );
                   return;
```

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java (hunk 3 above)
Comment (davidkyle) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Usually `assertThat(X, containsString(Y))` is good enough 

```assertThat(e.getMessage(), containsString("Datafeed [test_datafeed] is configured with a remote index pattern  [remote_cluster:remote_index] but the current node [local_cluster-0] is not allowed to connect to remote clusters. Please enable node.remote_cluster_client for all machine learning nodes and master-eligible nodes."));```

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java [hunk 5]
```diff
@@ -0,0 +1,196 @@
...
+    }
+
+    @Override
+    protected boolean preserveClusterUponCompletion() {
+        return true;
+    }
+
+    @Override
+    protected boolean preserveDataStreamsUponCompletion() {
+        return true;
```
Comment (davidkyle) [inline modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Are you sure you want these settings? If another test is added to this class these settings may interfere with the test results.

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java [hunk 6]
```diff
@@ -0,0 +1,196 @@
+/*
+ * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
+ * or more contributor license agreements. Licensed under the "Elastic License
+ * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
+ * Public License v 1"; you may not use this file except in compliance with, at
+ * your election, the "Elastic License 2.0", the "GNU Affero General Public
+ * License v3.0 only", or the "Server Side Public License, v 1".
+ */
+
+package org.elasticsearch.datastreams;
```
Comment (davidkyle) [inline modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: This test should really be in the ml qa suite https://github.com/elastic/elasticsearch/tree/main/x-pack/plugin/ml/qa

The existing [multi cluster tests](https://github.com/elastic/elasticsearch/tree/main/x-pack/plugin/ml/qa/multi-cluster-tests-with-security) are yaml tests and difficult to adapt. Please create a new folder `datafeed-multicluster-tests` in `ml/qa` and move this test to that folder. You will need a new `build.gradle` in the same folder to run the test, I'm not certain what should be in the gradle file but I'll help you figure it out.  As a starting point try this

```
apply plugin: 'elasticsearch.internal-java-rest-test'

dependencies {
  testImplementation project(path: ':test:test-clusters')
  javaRestTestImplementation project(path: xpackModule('core'))  
}
```

Assuming you use the suggested folder names run the test with this command:
```
./gradlew :x-pack:plugin:ml:qa:datafeed-multicluster-tests:javaRestTest 
```

Comment (davidkyle) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Nice test BTW, thanks for adding it

Comment (schase-es) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Thanks for these notes David -- this is really helpful. I'm very new here and don't know lots about the testing environment.

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java (hunk 5 above)
Comment (schase-es) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: I'm not sure actually -- the test errorred-out without them. This was adapted from the MultiClustersIT test... I'll see if I can learn more about them

Comment (schase-es) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Oh I see -- that missing return you flagged in TransportStartDatafeedAction was the culprit -- whatever state that put the thread pools caused an error in clean-up.

File: modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java (hunk 2 above)
Comment (schase-es) [reply modules/data-streams/src/javaRestTest/java/org/elasticsearch/datastreams/DatafeedRemoteClusterClientIT.java]: Ah! I was looking around for this, but couldn't find it -- I see it's a junit method now

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDatafeedAction.java (hunk 4 above)
Comment (schase-es) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDatafeedAction.java:240]: Good catch!!

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by schase-es** [comment]
Great -- everything is merged. Thanks Nick as usualy, and David especially for reviewing something from another team -- and helping me get started with a gradle!

**Comment by schase-es** [comment]
FYI @kderusso and @valeriy42:

The error message is now a 400-response with an explanatory response:
`method [POST], host [http://[::1]:63535], URI [_ml/datafeeds/test_datafeed/_start], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"status_exception","reason":"Datafeed [test_datafeed] is configured with a remote index pattern(s) [remote_cluster:remote_index] but the current node [local_cluster-0] is not allowed to connect to remote clusters. Please enable node.remote_cluster_client for all machine learning nodes and master-eligible
nodes."}],"type":"status_exception","reason":"Datafeed [test_datafeed] is configured with a remote index pattern(s) [remote_cluster:remote_index] but the current node [local_cluster-0] is not allowed to connect to remote clusters. Please enable node.remote_cluster_client for all machine learning nodes and master-eligible nodes."},"status":400}`

The old error message I reproduced in testing (and which is now gone), was a 404 response:
`method [POST], host [http://[::1]:63626], URI [_ml/datafeeds/test_datafeed/_start], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"no_such_remote_cluster_exception","reason":"no such remote cluster: [remote_cluster]"}],"type":"no_such_remote_cluster_exception","reason":"no such remote cluster:
[remote_cluster]"},"status":404}`

I did not write it to issue an IllegalArgumentException as mentioned earlier. While there are several code paths that do this, this API already had a check for this and an error message, but it was in the wrong order relative to cluster name validation.
