### PR TITLE
Remove deprecated options for query_string

### LINKED ISSUE #25551: Remove all_fields:true in favour of fields:*
`all_fields` only exists because fields:* queries some fields that are not suitable for querying, and the query ultimately fails with a weird exception. We should fix `fields:*` to do the right thing and remove the `all_fields` option.

### PR DESCRIPTION
**Pull request by jimczi**
This commit removes some parameters deprecated in 6.x (or 5.x):
`use_dismax`, `split_on_whitespace`, `all_fields` and `lowercase_expanded_terms`.

Closes #25551

### CODE REVIEW

**Comment by colings86** [comment]
Should this not have a breaking label since it does break the API. I know the parameters were ignored before but they were accepted when we are parsing which they now won't be so I think its worth having this change in the release notes so people can see that they might need to change their client code?

**Comment by jimczi** [comment]
Thanks @colings86 , I added the breaking label.

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java [hunk 1]
```diff
@@ -78,15 +78,9 @@
     private static final ParseField ANALYZER_FIELD = new ParseField("analyzer");
     private static final ParseField QUOTE_ANALYZER_FIELD = new ParseField("quote_analyzer");
     private static final ParseField ALLOW_LEADING_WILDCARD_FIELD = new ParseField("allow_leading_wildcard");
-    private static final ParseField AUTO_GENERATE_PHRASE_QUERIES_FIELD = new ParseField("auto_generate_phrase_queries")
-            .withAllDeprecated("This setting is ignored, use [type=phrase] instead");
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: I think we should add this to the breaking changes doc above?

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java [hunk 2]
```diff
@@ -97,13 +91,7 @@
     private static final ParseField MINIMUM_SHOULD_MATCH_FIELD = new ParseField("minimum_should_match");
     private static final ParseField QUOTE_FIELD_SUFFIX_FIELD = new ParseField("quote_field_suffix");
     private static final ParseField LENIENT_FIELD = new ParseField("lenient");
-    private static final ParseField LOCALE_FIELD = new ParseField("locale")
-            .withAllDeprecated("Decision is now made by the analyzer");
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: I think we should add this to the breaking changes doc above?

**Review by colings86 — APPROVED** [review]
@jimczi I left two minor comments but other than those this LGTM

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: Thanks

File: server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java (hunk 2 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/query/QueryStringQueryBuilder.java]: Done, thanks
