### PR TITLE
Fix #129104 by adding a FeatureFlag to YAML tests

### LINKED ISSUE #129602: [CI] SmokeTestMultiNodeClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic #8823 / release-tests](https://gradle-enterprise.elastic.co/s/7uvijhqvubqd6)
- [elasticsearch-pull-request #76277 / part-6](https://gradle-enterprise.elastic.co/s/izy5ghx3ozm3y)
- [elasticsearch-pull-request #76269 / checkpart6_release-tests](https://gradle-enterprise.elastic.co/s/saslv3qjsu2y2)
- [elasticsearch-pull-request #76252 / checkpart6_release-tests](https://gradle-enterprise.elastic.co/s/wyjsdwn2lku22)
- [elasticsearch-periodic #8817 / release-tests](https://gradle-enterprise.elastic.co/s/fas7roqrjb3is)
- [elasticsearch-periodic #8811 / release-tests](https://gradle-enterprise.elastic.co/s/qdya2rqhbmgtu)

**Reproduction Line:**
```
./gradlew ":qa:smoke-test-multinode:yamlRestTest" --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" -Dtests.method="test {yaml=search.vectors/46_knn_search_bbq_ivf/Test bad quantization parameters}" -Dtests.seed=8E8C9E9C552F200 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ln-CD -Dtests.timezone=Antarctica/Troll -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [search.vectors/46_knn_search_bbq_ivf:7]: expected [2xx] status code but api [indices.create] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Unknown vector index options type [bbq_ivf] for field [vector]","stack_trace":"org.elasticsearch.index.mapper.MapperParsingException: Unknown vector index options type [bbq_ivf] for field [vector]\n\tat org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapper.parseIndexOptions(DenseVectorFieldMapper.java:2813)\n\tat org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapper$Builder.lambda$new$15(DenseVectorFieldMapper.java:308)\n\tat org.elasticsearch.index.mapper.FieldMapper$Parameter.parse(FieldMapper.java:973)\n\tat org.elasticsearch.index.mapper.FieldMapper$Builder.parse(FieldMapper.java:1589)\n\tat org.elasticsearch.index.mapper.FieldMapper$TypeParser.parse(FieldMapper.java:1707)\n\tat org.elasticsearch.index.mapper.FieldMapper$TypeParser.parse(Fiel
[truncated]
```

**Issue Reasons:**
- [main] 3 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart6_release-tests
- [main] 6 failures in class org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT (2.9% fail rate in 205 executions)
- [main] 3 failures in step release-tests (100.0% fail rate in 3 executions)
- [main] 2 failures in step checkpart6_release-tests (100.0% fail rate in 2 executions)
- [main] 3 failures in pipeline elasticsearch-periodic (75.0% fail rate in 4 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (3.1% fail rate in 98 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by carlosdelest**
Closes #129104
Closes #129602

Release tests don't have feature flags active. There were a couple `ESClientYamlSuiteTestCasethat` didn't have  the `IVF_FORMAT` feature flag, and thus failed release tests when YAML tests tried to create `bbq_ivf` index formats.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -2097,7 +2097,7 @@ protected FullTextFunctionTestCase(Class<? extends FullTextFunction> fullTextFun
         }
 
         protected FullTextFunctionTestCase(Class<? extends FullTextFunction> fullTextFunction) {
-            this(fullTextFunction, randomFrom("text", "keyword"), randomAlphaOfLengthBetween(1, 10));
+            this(fullTextFunction, randomFrom("text", "keyword"), randomAlphaOfLengthBetween(5, 10));
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java:2100]: Unrelated to this fix, but had a test failure on the CI that I thought was worth fixing. This makes it harder for a query to be repeated, and thus simplified, on the full text function test cases - which can cause failures as the actual query is not the expected one.

**Review by benwtrent — APPROVED** [review]
🙈

**Comment by benwtrent** [comment]
Closes this one too: https://github.com/elastic/elasticsearch/issues/129602
