### PR TITLE
ESQL: Fix double release in inline stats when `LocalRelation` is reused

### LINKED ISSUE #135679: ES|QL: INLINE STATS leads to "can't build page out of released blocks"
With CSV dataset

```
from dense_vector,airport_city_bound* 
| eval  kMvNZVQSH = -4048759096317256968, GzAYNHaHuIS = 4262770411405329967, EwPpQFmOPoB = "lkdgnbTrBT", `abbrev` = "LiXI" 
| keep `city`, `kMvNZVQSH`, GzAYNHaHuIS, city_boundary, EwPpQFmOPoB, `city_boundary`, `id`, kMvNZVQSH, id, airport 
| limit 6888 
| keep `kMvNZVQSH`, EwPpQFmOPoB, city, `id`, kMvNZVQSH 
| stats  `EwPpQFmOPoB` = min(id), `EwPpQFmOPoB` = count(*), kZiJPhNZ = count(id), ErGhdKhdv = count_distinct(city), EwPpQFmOPoB = min(id) | eval  ErGhdKhdv = null, fHSyxniFCS = -710891486, ErGhdKhdv = -1104488048, zdxdQdVIyFh = -1579062572, `kZiJPhNZ` = null, SzmOySyUh = null, eWVVRiwP = 1092261898855405071, nUxVhGhcpkiV = true, RvqGioBAAzYs = 169356242 
| eval  `kZiJPhNZ` = "gWJHDTcDMjRVSnlzSX", lxLgaagX = 4700531997851493340, `kZiJPhNZ` = false 
| keep `zdxdQdVIyFh` 
| inline stats  `zdxdQdVIyFh` = count(*), WbWVJnYJ = count(*), zdxdQdVIyFh = max(zdxdQdVIyFh), uKjfeKTfaH = max(zdxdQdVIyFh), QpovVxjMWSjh = min(zdxdQdVIyFh)
```

```
"type": "illegal_argument_exception",
"reason": "can't build page out of released blocks but [ConstantNullBlock[positions=1]] was released"
```

```
Caused by: java.lang.IllegalArgumentException: can't build page out of released blocks but [ConstantNullBlock[positions=1]] was released
	at org.elasticsearch.compute.data.Page.<init>(Page.java:76)
	at org.elasticsearch.compute.data.Page.<init>(Page.java:53)
	at org.elasticsearch.compute.operator.LocalSourceOperator.lambda$new$2(LocalSourceOperator.java:59)
	at org.elasticsearch.compute.operator.LocalSourceOperator.getOutput(LocalSourceOperator.java:79)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:272)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:186)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:420)
	at org.elasticsearch.server@9.2.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
```

### PR DESCRIPTION
**Pull request by kanoshiou**
When the optimizer creates a `LocalRelation` using `LocalSupplier.of()` (which delegates to `ImmediateLocalSupplier`), the same page instance can be referenced and released multiple times during inline stats execution. This happens because the `LocalRelation` serves as a source for both sides of the `InlineJoin` - once for the left-hand side and again for the right-hand side, causing a double release error and connection closure.

This PR modifies the `InlineJoin.firstSubPlan()` method to ensure that all `LocalRelation` nodes use `CopyingLocalSupplier` (if they don't already) after extracting the subplan. This prevents double release issues when the same page is reused across executions.

Closes #135679

### CODE REVIEW

**Comment by bpintea** [comment]
@kanoshiou thanks for this patch!

I'm however thinking if we shouldn't have another approach here: instead of patching the optimiser rules to use the `CopyingLocalSupplier`, shouldn't we rather patch the`LocalRelation` leaf that `InlineJoin` get to run on the RHS? (Possibly apply the fix only to `InlineJoin#firstSubPlan`.) 
#135679 is `INLINE STATS`-specific and we could probably contain the fix to it. We could then also check if we'd need a `CopyingLocalSupplier` (but that's secondary).

@astefan, WDYT?

**Comment by astefan** [comment]
> @kanoshiou thanks for this patch!
> 
> I'm however thinking if we shouldn't have another approach here: instead of patching the optimiser rules to use the `CopyingLocalSupplier`, shouldn't we rather patch the`LocalRelation` leaf that `InlineJoin` get to run on the RHS? (Possibly apply the fix only to `InlineJoin#firstSubPlan`.) #135679 is `INLINE STATS`-specific and we could probably contain the fix to it. We could then also check if we'd need a `CopyingLocalSupplier` (but that's secondary).
> 
> @astefan, WDYT?

@kanoshiou `inline stats` is different than any other command in that part of its workings live in EsqlSession. Whenever we add something that is specific to `inline stats` we try to limit its spread and make it as seamless as possible in the existing code.
This means that modifications that happen outside `EsqlSession` and `InlineJoin` itself should be limited. Your changes to optimizer rules that have nothing to do with `inline stats` (as opposed to `PruneInlineJoinOnEmptyRightSide` for example which is `inline stats` specific) should have a very good reason to be there.

Your changes to `PruneColumns` and `PropagateEmptyRelation` take the shotgun approach and are too invasive, they will also apply to non-`inline stats` use cases which is unnecessary. @bpintea's suggestion is something you should look into, instead.

**Review by astefan — CHANGES_REQUESTED** [review]
Please, look into @bpintea's suggestion for a less invasive and more targeted approach to this bug fix. Please, let us know if you are able to work on this bug fix in short time, otherwise we are ready to take it over. Thank you.

**Comment by kanoshiou** [comment]
Thank you for the review and insightful suggestions, @bpintea @astefan! I'll update the branch today with a new logical optimizer rule.

**Review by astefan — CHANGES_REQUESTED** [review]
I had something else in mind when I did my first review.
Using a CopyingLocalSupplier should happen in `InlineJoin.firstSubPlan`:

```
public static LogicalPlanTuple firstSubPlan(LogicalPlan optimizedPlan, Set<LocalRelation> subPlansResults) {
        final Holder<LogicalPlan> stubReplacedSubPlanHolder = new Holder<>();
        final Holder<LogicalPlan> originalSubPlanHolder = new Holder<>();
        // Collect the first inlinejoin (bottom up in the tree)
        optimizedPlan.forEachUp(InlineJoin.class, ij -> {
            // extract the right side of the plan and replace its source
            if (stubReplacedSubPlanHolder.get() == null) {
                if (ij.right().anyMatch(p -> p instanceof StubRelation)) {
                    stubReplacedSubPlanHolder.set(replaceStub(ij.left(), ij.right()));
                } else if (ij.right() instanceof LocalRelation relation
                    && (subPlansResults.isEmpty() || subPlansResults.contains(relation) == false)
                    || ij.right() instanceof LocalRelation == false && ij.right().anyMatch(p -> p instanceof LocalRelation)) {
                    // In case the plan was optimized further and the StubRelation was replaced with a LocalRelation
                    // or the right hand side became a LocalRelation alltogether, there is no need to replace the source of the
                    // right-hand side anymore.
                    stubReplacedSubPlanHolder.set(ij.right());
                    // TODO: INLINE STATS this is essentially an optimization similar to the one in PruneInlineJoinOnEmptyRightSide
                    // this further supports the idea of running the optimization step again after the substitutions (see EsqlSession
                    // executeSubPlan() method where we could run the optimizer after the results are replaced in place).
                }
                originalSubPlanHolder.set(ij.right());
            }
        });
        LogicalPlanTuple tuple = null;
        if (stubReplacedSubPlanHolder.get() != null) {
            var plan = stubReplacedSubPlanHolder.get();
            plan = plan.transformUp(LocalRelation.class, lr -> {
                if (lr.supplier() instanceof CopyingLocalSupplier == false) {
                    return new LocalRelation(lr.source(), lr.output(), new CopyingLocalSupplier(lr.supplier().get()));
                }
                return lr;
            });
            plan.setOptimized();
            tuple = new LogicalPlanTuple(plan, originalSubPlanHolder.get());
        }
        return tuple;
    }
```

**Comment by kanoshiou** [comment]
Thank you for the thoughtful patch, @astefan — it really helped clarify the underlying issue!

It looks like your current approach addresses the problem outside the logical optimization phase, which seems like the right direction for tackling the root cause.

While reviewing your code, I was wondering if the `CopyingLocalSupplier` currently used in `ReplaceRowAsLocalRelation` could be replaced with an `ImmediateLocalSupplier`. Doing so might simplify the handling and reduce unnecessary duplication, assuming the reuse semantics remain intact.

**Comment by astefan** [comment]
> Thank you for the thoughtful patch, @astefan — it really helped clarify the underlying issue!
> 
> It looks like your current approach addresses the problem outside the logical optimization phase, which seems like the right direction for tackling the root cause.
> 
> While reviewing your code, I was wondering if the `CopyingLocalSupplier` currently used in `ReplaceRowAsLocalRelation` could be replaced with an `ImmediateLocalSupplier`. Doing so might simplify the handling and reduce unnecessary duplication, assuming the reuse semantics remain intact.

I don't know. It needs to go through a round of testing to double check this.

**Comment by kanoshiou** [comment]
@astefan I've updated the code, please let me know if there's anything else that needs to be changed.

**Comment by astefan** [comment]
@elasticmachine test this please

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -1490,6 +1490,11 @@ public enum Cap {
          */
         TS_PERMIT_TEXT_BECOMING_KEYWORD_WHEN_GROUPED_ON,
 
+        /**
+         * Fix double release in inline stats when LocalRelation is reused
+         */
+        INLINE_STATS_DOUBLE_RELEASE_FIX,
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]:
```suggestion
        INLINE_STATS_DOUBLE_RELEASE_FIX(INLINESTATS_V11.enabled),
```

Also, move it as the last one added in the enum, not in the middle.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 2]
```diff
@@ -3990,3 +3990,184 @@ Canada            |English               |null                       |null
...
+| inline stats  `zdxdQdVIyFh` = count(*), WbWVJnYJ = count(*), zdxdQdVIyFh2 = max(zdxdQdVIyFh), uKjfeKTfaH = max(zdxdQdVIyFh), QpovVxjMWSjh = min(zdxdQdVIyFh)
+;
+
+zdxdQdVIyFh:long | WbWVJnYJ:long | zdxdQdVIyFh2:integer | uKjfeKTfaH:integer | QpovVxjMWSjh:integer
+1                | 1             | -1579062572          | -1579062572        | -1579062572
+;
+
+
+inlineStatsAfterPruningAggregate9
+required_capability: inline_stats
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec]: I don't think this one is needed.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 3]
```diff
@@ -3990,3 +3990,184 @@ Canada            |English               |null                       |null
...
+| inline stats  wXPJguff = median(VizcTbjMnBlQ) + avg(VizcTbjMnBlQ) + max(VizcTbjMnBlQ)
+;
+
+VizcTbjMnBlQ:long | wXPJguff:double
+1                 | 3.0       
+;
+
+
+inlineStatsAfterPruningAggregate8
+required_capability: inline_stats
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec]: I don't think this one is needed.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 4]
```diff
@@ -3990,3 +3990,184 @@ Canada            |English               |null                       |null
...
+| inline stats  QyCBayGHtAF = count(CLnBmEGor), yUMkeLezSN = present(contains + network.total_bytes_out), `JLSxMYld` = max(contains), GYbfUvbf = count(*)
+;
+
+CLnBmEGor:double | network.total_bytes_out:integer | version:keyword | contains:integer | LTMJrburyt:keyword | language_name:keyword | QyCBayGHtAF:long | yUMkeLezSN:boolean | JLSxMYld:integer | GYbfUvbf:long
+null             | null                            | null            | null             | null               | null                  | 0                | false              | null             | 1
+;
+
+
+inlineStatsAfterPruningAggregate7
+required_capability: inline_stats
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec]: I don't think this one is needed. The same for the other tests, as well.

**Comment by astefan** [comment]
@elasticmachine test this please

**Review by astefan — APPROVED** [review]
LGTM. CI is happy with the change in ReplaceRowAsLocalRelation, I am happy as well.

**Comment by astefan** [comment]
@elasticmachine test this please

**Comment by kanoshiou** [comment]
Thanks for your review and sorry for the delay in replying to your comment and updating the code, @astefan! I learned a lot about `ES|QL` and its optimization nuances from your code and advice! Thanks again for your time and expertise!

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 5]
```diff
@@ -3990,3 +3990,175 @@ Canada            |English               |null                       |null
...
+
+
+inlineStatsAfterPruningAggregate4
+required_capability: inline_stats_double_release_fix
+
+from k8s
+| stats PRezTcny = median(network.cost), `network.cost` = count(network.cost) 
+| drop network.cost 
+| inline stats QaoRGYyf = count(*) 
+| drop `PRezTcny`
```
Comment (bpintea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec:4044]: These queries are generated. This one in particular is relatively clean, but those below are randomised and those identifiers are eye pain (most `` quotations aren't needed either). Usually, they can also be shrunk down to a "minimal" query that reproduces the issue. 
Ideally, we'd minimise the queries and use "human-friendly" identifiers, but at a minimum, maybe indicate their source by adding a comment with the originating issue.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/InlineJoin.java [hunk 6]
```diff
@@ -146,33 +153,44 @@ public record LogicalPlanTuple(LogicalPlan stubReplacedSubPlan, LogicalPlan orig
...
                         // this further supports the idea of running the optimization step again after the substitutions (see EsqlSession
                         // executeSubPlan() method where we could run the optimizer after the results are replaced in place).
                     }
+                originalSubPlanHolder.set(ij.right());
             }
         });
-        return subPlan.get();
+        LogicalPlanTuple tuple = null;
+        if (stubReplacedSubPlanHolder.get() != null) {
+            var plan = stubReplacedSubPlanHolder.get();
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/InlineJoin.java]: Minor:

```suggestion
        var plan = stubReplacedSubPlanHolder.get();
        if (plan != null) {
            
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/InlineJoin.java [hunk 7]
```diff
@@ -146,33 +153,44 @@ public record LogicalPlanTuple(LogicalPlan stubReplacedSubPlan, LogicalPlan orig
      * Aggregate[[],[MAX(x{r}#99,true[BOOLEAN]) AS y#102]]
      * \_Limit[1000[INTEGER],false]
      *   \_LocalRelation[[x{r}#99],[IntVectorBlock[vector=ConstantIntVector[positions=1, value=1]]]]
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/join/InlineJoin.java:155]: This javadoc might require an update to be inline with the added paragraph, but this is minor, can remain as is.

**Review by bpintea — APPROVED** [review]
Thanks, LGTM!

**Comment by astefan** [comment]
@elasticmachine test this please
