### PR TITLE
validate snapshot has global state before restoring

### LINKED ISSUE #82019: Fail with error when restoring global state from a snapshot that does not have one
Currently elasticsearch allow to restore a global state from a snapshot that does not have one.
This silently succeed without changing anything. Once https://github.com/elastic/elasticsearch/issues/81247 is fixed this could result in nullifying entire cluster state. 

**Elasticsearch version** (`bin/elasticsearch --version`): 8.x and likely earlier

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

* create a cluster with a snapshot repository
* create a snapshot with `"include_global_state": false`
* restore the snapshot with `"include_global_state": true`

Elasticsearch should return an error in such case, but currently silently succeed without changing the global state.

### PR DESCRIPTION
**Pull request by idegtiarenko**
Currently it is possible to restore with `include_global_state: true` from a snapshot that does not have a global state.
This behavior will nullify cluster state once https://github.com/elastic/elasticsearch/pull/81373 is merged.
This pr adds explicit validation and error message to prevent damaging cluster state.

closes #82019

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotCustomPluginStateIT.java [hunk 1]
```diff
@@ -158,7 +158,7 @@ public void testIncludeGlobalState() throws Exception {
         logger.info("--> try restoring cluster state from snapshot without global state");
```
Comment (idegtiarenko) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotCustomPluginStateIT.java:158]: I should revisit the log entries as well

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 2]
```diff
@@ -988,6 +986,12 @@ private static void validateSnapshotRestorable(final RepositoryMetadata reposito
                     + "]"
             );
         }
+        if (request.includeGlobalState() && snapshotInfo.includeGlobalState() == Boolean.FALSE) {
+            throw new SnapshotRestoreException(
+                new Snapshot(repository.name(), snapshotInfo.snapshotId()),
+                "the snapshot was created without global state"
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:992]: Can we include into the message that we cannot restore with global state? For instance:

```suggestion
                "cannot restore global state since the snapshot was created without global state"
```

**Review by henningandersen — COMMENTED** [review]
Thanks Ievgen, this looks good. I would like to add documentation to the restore page explaining that you can only restore global state if the snapshot was taken with global state. Also, I wonder if we should not list it as breaking, only to highlight this to the few users who might be impacted.

File: docs/reference/snapshot-restore/apis/restore-snapshot-api.asciidoc [hunk 3]
```diff
@@ -170,6 +170,9 @@ ingest pipelines and {ilm-init} lifecycle policies that exist in your cluster
 and replaces them with the corresponding items from the snapshot.
 
 Use the `feature_states` parameter to configure how feature states are restored.
+
+If `include_global_state` is `true` and a snapshot was created without a global
+state then restore will fail.
```
Comment (idegtiarenko) [inline docs/reference/snapshot-restore/apis/restore-snapshot-api.asciidoc:175]: @henningandersen please let me know if you have ideas as for other sections this note should be added to

**Comment by henningandersen** [comment]
[Docs preview link](https://elasticsearch_82037.docs-preview.app.elstc.co/diff)

File: docs/reference/snapshot-restore/apis/restore-snapshot-api.asciidoc (hunk 3 above)
Comment (henningandersen) [inline docs/reference/snapshot-restore/apis/restore-snapshot-api.asciidoc:175]:
```suggestion
If `include_global_state` is `true` and a snapshot was created without a global
state then the restore request will fail.
```

**Review by henningandersen — APPROVED** [review]
LGTM.
