### PR TITLE
Avoid self-deadlock in the translog

### LINKED ISSUE #29509: [CI] TranslogTests#testFatalIOExceptionsWhileWritingConcurrently times out
`TranslogTests#testFatalIOExceptionsWhileWritingConcurrently` fails with a suite timeout error. This happened a couple of times a day in the last few days.

Example of a recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2300/console .

I can't reproduce this failure with the seed, but it is rather easy to reproduce it just by running this test some times (I tried once with iters set to 100 and it failed pretty quickly). Sounds like it's a timing issue then. I wonder if it may be caused by recent changes in #29401 that were fixing another failure for this same test method.

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=9842CD3971C5E19D \
  -Dtests.class=org.elasticsearch.index.translog.TranslogTests \
  -Dtests.method="testFatalIOExceptionsWhileWritingConcurrently" \
  -Dtests.security.manager=true \
  -Dtests.locale=he-IL \
  -Dtests.timezone=America/North_Dakota/Beulah

REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=9842CD3971C5E19D \
  -Dtests.class=org.elasticsearch.index.translog.TranslogTests \
  -Dtests.security.manager=true \
  -Dtests.locale=he-IL \
  -Dtests.timezone=America/North_Dakota/Beulah
```

### PR DESCRIPTION
**Pull request by jasontedor**
Today when reading an operation from the current generation fails tragically we attempt to close the translog. However, by invoking close before releasing the read lock we end up in self-deadlock because closing tries to acquire the write lock and the read lock can not be upgraded to a write lock. To avoid this, we move the close invocation outside of the try-with-resources that acquired the read lock. As an extra guard against this, we document the problem and add an assertion that we are not trying to invoke close while holding the read lock.

Closes #29509, relates #29401

### CODE REVIEW

**Review by bleskes — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/index/translog/Translog.java [hunk 1]
```diff
@@ -735,15 +733,29 @@ public boolean ensureSynced(Stream<Location> locations) throws IOException {
...
+     *
+     * Note that in case this thread closes the translog it must not already be holding a read lock on the translog as it will acquire a
+     * write lock in the course of closing the translog
+     *
+     * @param ex if an exception occurs closing the translog, it will be suppressed into the provided exception
+     */
     private void closeOnTragicEvent(final Exception ex) {
+        // we can not hold a read lock here because closing will attempt to obtain a write lock and that would result in self-deadlock
+        assert readLock.isHeldByCurrentThread() == false : Thread.currentThread().getName();
+        Objects.requireNonNull(ex);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/translog/Translog.java]: As we never expect a null value to be passed as parameter to this internal method, I'm not a fan of sprinkling this check here. This is defensive programming at its worst.

**Review by ywelsch — APPROVED** [review]
LGTM, thanks @jasontedor. Can you add a note to the PR description that this was introduced with #29401, i.e. affects code that was never released?
