### PR TITLE
Fix PushDownAndCombineLimits local limit handling when the limits are equal

### LINKED ISSUE #139250: [CI] PushDownAndCombineLimitsTests.testPushableLimitDuplicate failing
### CI Link

https://gradle-enterprise.elastic.co/s/tqbqr2vem3gyy/tests/task/:x-pack:plugin:esql:test/details/org.elasticsearch.xpack.esql.optimizer.rules.logical.PushDownAndCombineLimitsTests/testPushableLimitDuplicate?expanded-stacktrace=WyIwIl0&top-execution=1

### Repro line

./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.rules.logical.PushDownAndCombineLimitsTests.testPushableLimitDuplicate" -Dtests.seed=61F10A8825C942F6 -Dtests.locale=ak-Latn-GH -Dtests.timezone=Pacific/Tongatapu -Druntime.java=25

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

We fail to mark the upstream Limit node as local.

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([61F10A8825C942F6:FD13FB8BE2CF92F1]:0)
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.elasticsearch.xpack.esql.optimizer.rules.logical.PushDownAndCombineLimitsTests.lambda$static$14(PushDownAndCombineLimitsTests.java:212)
	at org.elasticsearch.xpack.esql.optimizer.rules.logical.PushDownAndCombineLimitsTests$PushDownLimitTestCase.checkOptimizedPlan(PushDownAndCombineLimitsTests.java:71)
	at org.elasticsearch.xpack.esql.optimizer.rules.logical.PushDownAndCombineLimitsTests.testPushableLimitDuplicate(PushDownAndCombineLimitsTests.java:248)
```

The base and optimized plans are as follows:
```
Base plan:

Enrich[REMOTE,Hfpwa[KEYWORD],a{f}#2,null,{},[]]
\_Limit[6[INTEGER],false,false]
  \_EsRelation[xfpisuhhemcw][TIME_SERIES][a{f}#2, b{f}#3]

Optimized to:

Enrich[REMOTE,Hfpwa[KEYWORD],a{f}#2,null,{},[]]
\_Limit[6[INTEGER],false,false]
  \_EsRelation[xfpisuhhemcw][TIME_SERIES][a{f}#2, b{f}#3]
```

### PR DESCRIPTION
**Pull request by smalyshev**
If the limits are not equal, lowest one wins. But if they are equal, we should choose the local one. It is safe since the local one always has a duplicate after enrich. 

Closes https://github.com/elastic/elasticsearch/issues/139250

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java [hunk 1]
```diff
@@ -102,8 +102,11 @@ private static Limit combineLimits(Limit upper, Limit lower, FoldContext ctx) {
         var upperLimitValue = (int) upper.limit().fold(ctx);
         var lowerLimitValue = (int) lower.limit().fold(ctx);
         // We want to preserve the duplicated() value of the smaller limit.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java]: nit: Comment has gone stale.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java [hunk 2]
```diff
@@ -102,8 +102,11 @@ private static Limit combineLimits(Limit upper, Limit lower, FoldContext ctx) {
...
-        if (lowerLimitValue <= upperLimitValue) {
-            return lower.withLocal(lower.local());
+        if (lowerLimitValue < upperLimitValue) {
+            return lower;
+        } else if (lowerLimitValue == upperLimitValue) {
+            // If any of them is local, we want the local limit
+            return lower.local() ? lower : lower.withLocal(upper.local());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java:117]: Why is this correct?

`local == true` means "I got duplicated from an optimization and am thus optional". But `local == false` is generally just a plain `limit` - just because a downstream optimization created another limit that's optional to execute, doesn't mean that we can throw away upstream limits that may well be coming from the user and we need to pipeline break on them?

**Review by alex-spies — APPROVED** [review]
Discussed offline: the situation that we have a local limit next to an upstream pipeline breaking limit should not happen in production. When there's a local limit, this means we duplicated a limit past remote enrich, and if the query was valid then no pipeline breaker must have been upstream from the remote enrich and thus also from the local limit.

Thus, this change doesn't actually affect production code and only fixes the test. It's fine.

Longer term, we want to clean this up because the rule's correctness is less obvious without knowing all the context on remote enrich.

The reason we don't do the cleanup now is that the limit pushdown for (remote) lookup joins _does not_ mark the duplicated limit as local, even though the duplicated limit doesn't have to be a pipeline breaker, just like in the remote enrich case. So there could theoretically be 2 limits next to each other that can be treated as local, while only one of them is actually marked as local.

The more correct way would be that 2 limits next to each other with 1 of them being non-local results in a non-local limit, because we have to pipeline break. But making this change has a chance of triggering bugs as long as the limit pushdown past lookup joins is not aligned with the limit pushdown past remote enrichs.

**Comment by smalyshev** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/139477)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
