### PR TITLE
Fix failing test `RollupActionSingleNodeTests` `testCannotRollupToExistingIndex` 

### LINKED ISSUE #88844: [CI] RollupActionSingleNodeTests testCannotRollupToExistingIndex failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/whiwuz23mtmvq/tests/:x-pack:plugin:rollup:test/org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests/testCannotRollupToExistingIndex

**Reproduction line:**
`./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testCannotRollupToExistingIndex" -Dtests.seed=9814B01249EAC77D -Dtests.locale=en-SG -Dtests.timezone=Africa/Windhoek -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests&tests.test=testCannotRollupToExistingIndex

**Failure excerpt:**
```
org.elasticsearch.index.IndexNotFoundException: no such index [rollup-testcannotrollupwhileotherrollupinprogress-svlo]

  at __randomizedtesting.SeedInfo.seed([9814B01249EAC77D:325B86553CE92325]:0)
  at org.elasticsearch.cluster.metadata.Metadata.getIndexSafe(Metadata.java:919)
  at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService.deleteIndices(MetadataDeleteIndexService.java:89)
  at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService$1.execute(MetadataDeleteIndexService.java:70)
  at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:515)
  at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:959)
  at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:929)
  at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:261)
  at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)
  at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)
  at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by csoulios**
The root cause of this failure was that test `testCannotRollupWhileOtherRollupInProgress` would finish before the asynchronously submitted rollup action had not completed. In this case the test would finish and delete the rollup index, while the rollup process was still trying to populate or replicate it. It looks like using the `ActionListener.NOOP` was not a good choice.

Fixes #88844

### CODE REVIEW

File: x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/v2/RollupActionSingleNodeTests.java [hunk 1]
```diff
@@ -214,6 +215,7 @@ public void setup() {
                 "type=double"
             )
             .get();
+        assertTrue("Source index was not created", r.isAcknowledged());
```
Comment (weizijun) [inline x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/v2/RollupActionSingleNodeTests.java:218]: can it replace by assertAcked?

Comment (csoulios) [reply x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/v2/RollupActionSingleNodeTests.java]: Added `assertAcked()` everywhere possible in the test here: [a5b09f9](https://github.com/elastic/elasticsearch/pull/89025/commits/a5b09f9afe573ff03386bf3e84d6f2e81795095e)

**Review by salvatore-campagna — APPROVED** [review]
LGTM
