### PR TITLE
Rollup: Skip cleanup if nodes too old

### LINKED ISSUE #34629: [TEST] Rollup cleanup failing BWC tests on 6.x
Relates to #34342

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+default-distro/4/testReport/junit/org.elasticsearch.backwards/IndexingIT/testIndexVersionPropagation/

Reproduce with:

```
./gradlew :qa:mixed-cluster:v5.6.13-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=8A390CB44222626C -Dtestsecurity.manager=true -Dtests.locale=el -Dtests.timezone=Pacific/Apia -Dtests.distribution=zip -Dcompiler.java=11 -Druntime.java=8
```

```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:38073], URI [/_xpack/rollup/job/_all], status line [HTTP/1.1 400 Bad Request]
No handler found for uri [/_xpack/rollup/job/_all] and method [GET]
	at __randomizedtesting.SeedInfo.seed([8A390CB44222626C:BAA5894E7D4A433]:0)
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:926)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeRollupJobs(ESRestTestCase.java:395)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:329)
	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:179)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:38073], URI [/_xpack/rollup/job/_all], status line [HTTP/1.1 400 Bad Request]
No handler found for uri [/_xpack/rollup/job/_all] and method [GET]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 more
```

### PR DESCRIPTION
**Pull request by nik9000**
Skips the rollup cleanup at the end of every test if some of the nodes
in the test cluster have a version before rollup was released.

As a side effect of doing this, I move the "is x-pack installed" test
from on-demand to before the first test. This should result in less
requests in general and it makes is a little simpler to store the node
versions and whether or not any node has x-pack installed.

I expect other cleanup code will be able to use this version checking
infrastructure. In addition, I think the yml tests could also reuse it.
They have some fairly complex logic to look up the versions of nodes but
I don't believe it is required. Both of those will have to wait for a
follow up change.

Closes #34629

### CODE REVIEW

**Comment by nik9000** [comment]
Note: I opened this against 6.x because that is where the actual problem occurs. I'll forward port it so master lines up once we approve it.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -325,18 +336,13 @@ private void wipeCluster() throws Exception {
...
-                        // or the request was made to a node with rollup and it sent something to a node without it
-                        && false == e.getMessage().contains("No handler for action [cluster:monitor/xpack/rollup/get]")) {
-                    throw e;
-                }
-            }
+        /*
+         * Rollups were introduced in 6.3.0 so any cluster that contains older
+         * nodes won't be able to do *anything* with rollups, including cleanup.
+         */
+        if (hasXPack && nodeVersions.first().onOrAfter(Version.V_6_3_0)
```
Comment (talevy) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: should there be a comment here explaining why it is sufficient that any node has xpack, and not necessary to have all nodes have xpack?

I guess this leaks some things about our test infrastructure that may invalidate such comments in the future, so let me know if you think that would just be more confusing!

**Review by talevy — APPROVED** [review]
left a couple of minor comments, but LGTM

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -157,10 +151,27 @@ public void initClient() throws IOException {
...
+                    if (moduleInfo.get("name").toString().startsWith("x-pack-")) {
+                        hasXPack = true;
+                    }
+                }
+            }
         }
         assert client != null;
         assert adminClient != null;
         assert clusterHosts != null;
+        assert hasXPack != null;
```
[the remark this answers is not in the document]
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Not concurrency concerns, no. Just sanity ones. Junit's contract is that these are run in the obvious order so we should be safe here. We've been safe for the `client` and `adminClient` objects.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: So, yeah. I think I'd like to do a follow up to break apart "any have xpack" and "all have xpack" because I think the `skip: features: x-pack` in yml tests really want *all* nodes to have x-pack. And the rollup code here wants all nodes to have x-pack. But the template preservation code wants *any* nodes have x-pack.

**Comment by nik9000** [comment]
@elasticmachine, retest this please

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (talevy) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: cool. this is sufficient for ILM for now, so that makes sense

**Comment by nik9000** [comment]
I merged this to master, stripping out some of the BWC code that isn't useful there but keeping the version fetching.
