### PR TITLE
Fix MultiVersionRepository BwC Tests

### LINKED ISSUE #50819: BWC test failures for MultiVersionRepositoryAccessIT
Our most recent `master` BWC test run failed against versions 7.0.x and 7.1.x with the same test failures indicating we either made a BWC incompatible change in `master` or perhaps just the test needs updating.

The build run in question included [this commit](https://github.com/elastic/elasticsearch/commit/ee6fbcc4a7a79bd7bd3e05768824798af264a30e), which _might_ potentially be related. @original-brownbear any thoughts?

Example build scan: https://gradle-enterprise.elastic.co/s/dpoop7fvn2rwq/tests/failed
Jenkins build with links to each BWC version: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+bwc/471/

### PR DESCRIPTION
**Pull request by original-brownbear**
The HLRC doesn't like what its getting back from some older 6.x versions for the restore status
so I moved that request to the low level client.
Closes #50819

I manually confirmed that this runs fine for all BwC test versions:

```

BUILD SUCCESSFUL in 51m 1s
414 actionable tasks: 322 executed, 92 up-to-date

```

### CODE REVIEW

File: qa/repository-multi-version/src/test/java/org/elasticsearch/upgrades/MultiVersionRepositoryAccessIT.java [hunk 1]
```diff
@@ -269,14 +266,20 @@ private void deleteSnapshot(RestHighLevelClient client, String repoName, String
...
-            client.snapshot().restore(new RestoreSnapshotRequest().repository(repoName).snapshot(name).waitForCompletion(true),
-                RequestOptions.DEFAULT).getRestoreInfo();
-        assertThat(restoreInfo.failedShards(), is(0));
-        assertThat(restoreInfo.successfulShards(), equalTo(shards));
+        try (InputStream entity = client().performRequest(
+            new Request("POST", "/_snapshot/" + repoName + "/" + name + "/_restore?wait_for_completion=true")).getEntity().getContent();
+            XContentParser parser = JsonXContent.jsonXContent.createParser(
+            xContentRegistry(), DeprecationHandler.THROW_UNSUPPORTED_OPERATION, entity)) {
+            final Map<String, Object> raw = parser.map();
+            logger.error(raw);
```
Comment (ywelsch) [inline qa/repository-multi-version/src/test/java/org/elasticsearch/upgrades/MultiVersionRepositoryAccessIT.java]: remove this?

**Review by ywelsch — APPROVED** [review]
LGTM
