### PR TITLE
Fix _bulk response when it can't create an index

### LINKED ISSUE #24028: _bulk request with `action.auto_create_index` configured doesn't return the right bulk response
**Elasticsearch version**: 5.3.0

**Description of the problem including expected versus actual behavior**:

When whitelisting index name using the `action.auto_create_index` and sending a bulk request to ES with a forbidden index name doesn't return the expected bulk response.

The response is missing a **items** fields, allowing us to check if each document succeeded or not

more details at https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/584

**Steps to reproduce**:
1. Adding the following to the *elasticsearch.yml*
```yaml
 action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*
```

2. using this json document.
```
cat /tmp/x
{"index":{"_id":null,"_index":".logstash-2017.04.08","_type":"stdin","_routing":null}}
{"@timestamp":"2017-04-09T10:34:25.253Z","@version":"1","host":"localhost.localdomain","message":"testing","type":"stdin"}
```

3. 
```
curl -D- --data-binary @/tmp/x localhost:9200/_bulk?pretty
```

```json
HTTP/1.1 404 Not Found
Warning: 299 Elasticsearch-5.3.0-3adb13b "Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header." "Mon, 10 Apr 2017 19:46:17 GMT"
content-type: application/json; charset=UTF-8
content-length: 612

{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
        "index_uuid" : "_na_",
        "index" : ".logstash-2017.04.08"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
    "index_uuid" : "_na_",
    "index" : ".logstash-2017.04.08"
  },
  "status" : 404
}
```

Tested in 5.1.2 returns a correct response:

```
% curl -D- --data-binary @/tmp/x localhost:9200/_bulk?pretty
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 496

{
  "took" : 0,
  "errors" : true,
  "items" : [
    {
      "index" : {
        "_index" : "logstash-2017.04.09",
        "_type" : "stdin",
        "_id" : null,
        "status" : 404,
        "error" : {
          "type" : "index_not_found_exception",
          "reason" : "no such index",
          "resource.type" : "index_expression",
          "resource.id" : "logstash-2017.04.09",
          "index_uuid" : "_na_",
          "index" : "logstash-2017.04.09"
        }
      }
    }
  ]
}
```

4. If in a single bulk request you target 2 different index, it will return a single bulk response in the `bulk`

**Request**
```json
{"index":{"_id":null,"_index":".logstash-2017.04.08","_type":"stdin","_routing":null}}
{"@timestamp":"2017-04-09T10:34:25.253Z","@version":"1","host":"localhost.localdomain","message":"testing","type":"stdin"}
{"index":{"_id":null,"_index":".monitoring-2017.04.08","_type":"stdin","_routing":null}}
{"@timestamp":"2017-04-09T10:34:25.253Z","@version":"1","host":"localhost.localdomain","message":"testing 2","type":"stdin"}
```
**Response:**
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
        "index_uuid" : "_na_",
        "index" : ".logstash-2017.04.08"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index and [action.auto_create_index] ([.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]) doesn't match",
    "index_uuid" : "_na_",
    "index" : ".logstash-2017.04.08"
  },
  "status" : 404
}
````

### PR DESCRIPTION
**Pull request by nik9000**
Before #22488 when an index couldn't be created during a `_bulk`
operation we'd do all the *other* actions and return the index
creation error on each failing action. In #22488 we accidentally
changed it so that we now reject the entire bulk request if a single
action cannot create an index that it must create to run. This
reverts to the old behavior while still keeping the nicer
error messages. Instead of failing the entire request we now only
fail the portions of the request that can't work because the index
doesn't exist.

Closes #24028

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 1]
```diff
@@ -139,14 +140,39 @@ protected void doExecute(Task task, BulkRequest bulkRequest, ActionListener<Bulk
...
                 .map(DocWriteRequest::index)
                 .collect(Collectors.toSet());
-            final AtomicInteger counter = new AtomicInteger(autoCreateIndices.size());
+            /* Step 2: filter that to indices that don't exist and we can create. At the same time build a map of indices we can't create
+             * that we'll use when we try to run the requests. */
+            Map<String, IndexNotFoundException> indicesThatCannotBeCreated = null;
             ClusterState state = clusterService.state();
-            for (String index : autoCreateIndices) {
-                if (shouldAutoCreate(index, state)) {
+            for (Iterator<String> itr = autoCreateIndices.iterator(); itr.hasNext();) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: I think this can be simplified, no need to iterate and remove, and no need for the final map:

```diff
diff --git a/core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java b/core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java
index 1b1f961a12..708f8eb4b0 100644
--- a/core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java
+++ b/core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java
@@ -64,6 +64,7 @@ import org.elasticsearch.transport.TransportService;
 
 import java.util.ArrayList;
 import java.util.HashMap;
+import java.util.HashSet;
 import java.util.Iterator;
 import java.util.List;
 import java.util.Map;
@@ -142,34 +143,30 @@ public class TransportBulkAction extends HandledTransportAction<BulkRequest, Bul
         if (needToCheck()) {
             // Attempt to create all the indices that we're going to need during the bulk before we start.
             // Step 1: collect all the indices in the request
-            final Set<String> autoCreateIndices = bulkRequest.requests.stream()
+            final Set<String> indices = bulkRequest.requests.stream()
                 .map(DocWriteRequest::index)
                 .collect(Collectors.toSet());
             /* Step 2: filter that to indices that don't exist and we can create. At the same time build a map of indices we can't create
              * that we'll use when we try to run the requests. */
-            Map<String, IndexNotFoundException> indicesThatCannotBeCreated = null;
+            final Map<String, IndexNotFoundException> indicesThatCannotBeCreated = new HashMap<>();
+            final Set<String> autoCreateIndices = new HashSet<>();
             ClusterState state = clusterService.state();
-            for (Iterator<String> itr = autoCreateIndices.iterator(); itr.hasNext();) {
-                String index = itr.next();
+            for (final String index : indices) {
                 boolean shouldAutoCreate;
                 try {
                     shouldAutoCreate = shouldAutoCreate(index, state);
                 } catch (IndexNotFoundException e) {
                     shouldAutoCreate = false;
-                    if (indicesThatCannotBeCreated == null) {
-                        indicesThatCannotBeCreated = new HashMap<>();
-                    }
                     indicesThatCannotBeCreated.put(index, e);
                 }
-                if (false == shouldAutoCreate) {
-                    itr.remove();
+                if (shouldAutoCreate) {
+                    autoCreateIndices.add(index);
                 }
             }
+
             // Step 3: create all the indices that are missing, if there are any missing. start the bulk after all the creates come back.
-            final Map<String, IndexNotFoundException> finalIndicesThatCannotBeCreated =
-                    indicesThatCannotBeCreated == null ? emptyMap() : indicesThatCannotBeCreated;
             if (autoCreateIndices.isEmpty()) {
-                executeBulk(task, bulkRequest, startTime, listener, responses, finalIndicesThatCannotBeCreated);
+                executeBulk(task, bulkRequest, startTime, listener, responses, indicesThatCannotBeCreated);
             } else {
                 final AtomicInteger counter = new AtomicInteger(autoCreateIndices.size());
                 for (String index : autoCreateIndices) {
@@ -181,7 +178,7 @@ public class TransportBulkAction extends HandledTransportAction<BulkRequest, Bul
                         @Override
                         public void onResponse(CreateIndexResponse result) {
                             if (counter.decrementAndGet() == 0) {
-                                executeBulk(task, bulkRequest, startTime, listener, responses, finalIndicesThatCannotBeCreated);
+                                executeBulk(task, bulkRequest, startTime, listener, responses, indicesThatCannotBeCreated);
                             }
                         }
 
@@ -200,7 +197,7 @@ public class TransportBulkAction extends HandledTransportAction<BulkRequest, Bul
                                 executeBulk(task, bulkRequest, startTime, ActionListener.wrap(listener::onResponse, inner -> {
                                     inner.addSuppressed(e);
                                     listener.onFailure(inner);
-                                }), responses, finalIndicesThatCannotBeCreated);
+                                }), responses, indicesThatCannotBeCreated);
                             }
                         }
                     });
```

File: settings.gradle [hunk 2]
```diff
@@ -57,9 +57,10 @@ List projects = [
   'plugins:store-smb',
   'qa:backwards-5.0',
   'qa:evil-tests',
+  'qa:multi-cluster-search',
   'qa:no-bootstrap-tests',
   'qa:rolling-upgrade',
-  'qa:multi-cluster-search',
+  'qa:smoke-test-autocreateindex-limited',
```
Comment (jasontedor) [inline settings.gradle]: Of course I have a complaint about the naming. 😇 

I think that we should stop calling these "smoke tests" as they are not smoke tests, and I would like to see some extra hyphens in `autocreateindex`.

**Review by jasontedor — CHANGES_REQUESTED** [review]
Thanks @nik9000, I did a first round. I get the change, it looks good. I offered a suggestion that might simplify things, I have a complaint about a name. I appreciate the REST test a lot, but I would like to ask if it would be possible to write a unit test. Maybe it would be possible override executeBulk and assert on the names of indices that can not be created that is passed in?

File: settings.gradle (hunk 2 above)
Comment (nik9000) [inline settings.gradle]: ++

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java (hunk 1 above)
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: I didn't want to add the extra HashMap allocation. I'm happy to do it your way if you think it isn't a big deal.

**Comment by nik9000** [comment]
> would be possible to write a unit test.

Almost certainly

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: I see. I think it will die young so it's probably not a big deal. I'm fine if you think it's important yet I think either way the rest of my suggestion (to avoid the iterate/remove) stand?

**Comment by nik9000** [comment]
@jasontedor I'm fine with the young garbage argument. I pushed some commits which should address your comments.

File: core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+        indicesThatCannotBeCreatedTestCase(emptySet(), bulkRequest, index -> randomBoolean());
+    }
+
+    public void testAllFail() {
+        BulkRequest bulkRequest = new BulkRequest();
+        bulkRequest.add(new IndexRequest("no"));
+        bulkRequest.add(new IndexRequest("can't"));
+        bulkRequest.add(new DeleteRequest("do"));
+        bulkRequest.add(new UpdateRequest("any", randomAlphaOfLength(5), randomAlphaOfLength(5)));
+        indicesThatCannotBeCreatedTestCase(new HashSet<>(Arrays.asList("no", "can't", "do", "any")), bulkRequest, index -> {
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java]: Double negative. 😄.

File: settings.gradle [hunk 4]
```diff
@@ -57,11 +57,12 @@ List projects = [
   'plugins:repository-s3',
   'plugins:jvm-example',
   'plugins:store-smb',
+  'qa:autocreateindex',
```
Comment (jasontedor) [inline settings.gradle]: I still want hyphens: `auto-create-index`. 😇

**Review by jasontedor — APPROVED** [review]
LGTM. I left two comments that you can address as you see fit.

File: settings.gradle (hunk 4 above)
Comment (nik9000) [inline settings.gradle]: Sure.

**Comment by nik9000** [comment]
Thanks @jasontedor! I'll backport now.

**Comment by nik9000** [comment]
All backported except 5.x. Still waiting on that build.

**Comment by nik9000** [comment]
Backported to 5.x as well.
