### PR TITLE
Fix reranker tests

### LINKED ISSUE #126320: [CI] EsqlSpecIT test {rerank.Reranker using multiple fields SYNC} failing
**Build Scans:**
- [elasticsearch-intake #21362 / part3](https://gradle-enterprise.elastic.co/s/du4namn3ypns4)
- [elasticsearch-pull-request #66215 / part-3](https://gradle-enterprise.elastic.co/s/lif7tu5vtvkac)
- [elasticsearch-pull-request #65594 / part-3](https://gradle-enterprise.elastic.co/s/tppfan5roxkbs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker using another sort order ASYNC}" -Dtests.seed=6362DB869228C967 -Dtests.locale=ru-KG -Dtests.timezone=Australia/West -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20using%20multiple%20fields%20SYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Data mismatch:
row 0 column 3:a list containing
row 0 column 3:0: expected <0.02222> but was <0.02273>
row 1 column 3:a list containing
row 1 column 3:0: expected <0.01515> but was <0.01493>
Actual:
book_no:keyword | title:text                                            | author:text                                 | _score:double
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, Leo Tolstoy, Pat Conroy] | 0.02273      
2776            | The Devil and Other Stories (Oxford World's Classics) | Leo Tolstoy                                 | 0.01493      
5327            | War and Peace                                         | Leo Tolstoy                                 | 0.03846      

Expected:
book_no:keyword | title:text                                            | author:text                                 | _score:double
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, 
[truncated]
```

**Issue Reasons:**
- [main] 3 failures in test test {rerank.Reranker using multiple fields SYNC} (18.8% fail rate in 16 executions)
- [main] 2 failures in step part-3 (13.3% fail rate in 15 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (16.7% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126322: [CI] EsqlSpecIT test {rerank.Reranker before a limit SYNC} failing
**Build Scans:**
- [elasticsearch-intake #21362 / part3](https://gradle-enterprise.elastic.co/s/du4namn3ypns4)
- [elasticsearch-pull-request #66215 / part-3](https://gradle-enterprise.elastic.co/s/lif7tu5vtvkac)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker using another sort order ASYNC}" -Dtests.seed=6362DB869228C967 -Dtests.locale=ru-KG -Dtests.timezone=Australia/West -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20before%20a%20limit%20SYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Data mismatch:
row 0 column 3:a list containing
row 0 column 3:0: expected <0.02222> but was <0.02273>
row 1 column 3:a list containing
row 1 column 3:0: expected <0.01515> but was <0.01493>
Actual:
book_no:keyword | title:text                                            | author:text                                 | _score:double
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, Leo Tolstoy, Pat Conroy] | 0.02273      
2776            | The Devil and Other Stories (Oxford World's Classics) | Leo Tolstoy                                 | 0.01493      
5327            | War and Peace                                         | Leo Tolstoy                                 | 0.03846      

Expected:
book_no:keyword | title:text                                            | author:text                                 | _score:double
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, 
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test test {rerank.Reranker before a limit SYNC} (28.6% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126361: [CI] EsqlSpecIT test {rerank.Reranker before a limit ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7476 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/mefj425pq3ks6)
- [elasticsearch-periodic #7447 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/uu5jpar6r27ui)
- [elasticsearch-periodic #7447 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/shq5dfredqxqi)
- [elasticsearch-periodic #7447 / openjdk24_entitlements_true_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/37issd5kjexwm)
- [elasticsearch-pull-request #66519 / part-3](https://gradle-enterprise.elastic.co/s/yxutbxmhmr4cy)
- [elasticsearch-pull-request #66516 / part-3](https://gradle-enterprise.elastic.co/s/3om4wqoztf7ka)
- [elasticsearch-pull-request #66215 / part-3](https://gradle-enterprise.elastic.co/s/lif7tu5vtvkac)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker add the _score column when missing ASYNC}" -Dtests.seed=E9A81693DD813AD4 -Dtests.locale=mn-Cyrl-MN -Dtests.timezone=US/Hawaii -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20before%20a%20limit%20ASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Data mismatch:
row 1 column 3:a list containing
row 1 column 3:0: expected <0.02222> but was <0.02273>
row 3 column 3:a list containing
row 3 column 3:0: expected <0.01515> but was <0.01493>
Actual:
book_no:keyword | title:text                                            | author:text                                 | _score:double
5327            | War and Peace                                         | Leo Tolstoy                                 | 0.03846      
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, Leo Tolstoy, Pat Conroy] | 0.02273      
9032            | War and Peace: A Novel (6 Volumes)                    | Tolstoy Leo                                 | 0.02083      
2776            | The Devil and Other Stories (Oxford World's Classics) | Leo Tolstoy                                 | 0.01493      

Expected:
book_no:keyword | title:text                                            | author:text        
[truncated]
```

**Issue Reasons:**
- [main] 7 failures in test test {rerank.Reranker before a limit ASYNC} (5.3% fail rate in 132 executions)
- [main] 3 failures in step part-3 (7.1% fail rate in 42 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (7.7% fail rate in 39 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126362: [CI] EsqlSpecIT test {rerank.Reranker using another sort order ASYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7476 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/mefj425pq3ks6)
- [elasticsearch-periodic #7447 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/uu5jpar6r27ui)
- [elasticsearch-periodic #7447 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/shq5dfredqxqi)
- [elasticsearch-periodic #7447 / openjdk24_entitlements_true_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/37issd5kjexwm)
- [elasticsearch-periodic #7440 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/hnbzduego5mku)
- [elasticsearch-pull-request #66519 / part-3](https://gradle-enterprise.elastic.co/s/yxutbxmhmr4cy)
- [elasticsearch-pull-request #66516 / part-3](https://gradle-enterprise.elastic.co/s/3om4wqoztf7ka)
- [elasticsearch-intake #21362 / part3](https://gradle-enterprise.elastic.co/s/du4namn3ypns4)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker add the _score column when missing ASYNC}" -Dtests.seed=E9A81693DD813AD4 -Dtests.locale=mn-Cyrl-MN -Dtests.timezone=US/Hawaii -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20using%20another%20sort%20order%20ASYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Data mismatch:
row 1 column 3:a list containing
row 1 column 3:0: expected <0.02222> but was <0.02273>
row 3 column 3:a list containing
row 3 column 3:0: expected <0.01515> but was <0.01493>
Actual:
book_no:keyword | title:text                                            | author:text                                 | _score:double
5327            | War and Peace                                         | Leo Tolstoy                                 | 0.03846      
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, Leo Tolstoy, Pat Conroy] | 0.02273      
9032            | War and Peace: A Novel (6 Volumes)                    | Tolstoy Leo                                 | 0.02083      
2776            | The Devil and Other Stories (Oxford World's Classics) | Leo Tolstoy                                 | 0.01493      

Expected:
book_no:keyword | title:text                                            | author:text        
[truncated]
```

**Issue Reasons:**
- [main] 8 failures in test test {rerank.Reranker using another sort order ASYNC} (6.3% fail rate in 126 executions)
- [main] 2 failures in step part-3 (5.6% fail rate in 36 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (5.9% fail rate in 34 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126363: [CI] EsqlSpecIT test {rerank.Reranker using another sort order SYNC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7483 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/rmxz6fvp6yhq2)
- [elasticsearch-periodic #7461 / openjdk23_entitlements_true_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/4eep57xngonwq)
- [elasticsearch-periodic-platform-support #7476 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/mefj425pq3ks6)
- [elasticsearch-periodic #7447 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/uu5jpar6r27ui)
- [elasticsearch-periodic #7447 / openjdk21_checkpart3_java-fips-matrix](https://gradle-enterprise.elastic.co/s/shq5dfredqxqi)
- [elasticsearch-pull-request #66516 / part-3](https://gradle-enterprise.elastic.co/s/3om4wqoztf7ka)
- [elasticsearch-pull-request #65594 / part-3](https://gradle-enterprise.elastic.co/s/tppfan5roxkbs)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {rerank.Reranker using another sort order SYNC}" -Dtests.seed=158FF6085345BBBA -Dtests.locale=af-Latn-ZA -Dtests.timezone=IET -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Brerank.Reranker%20using%20another%20sort%20order%20SYNC%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Data mismatch:
row 0 column 3:a list containing
row 0 column 3:0: expected <0.02222> but was <0.02273>
row 1 column 3:a list containing
row 1 column 3:0: expected <0.01515> but was <0.01493>
Actual:
book_no:keyword | title:text                                            | author:text                                 | _score:double
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, Leo Tolstoy, Pat Conroy] | 0.02273      
2776            | The Devil and Other Stories (Oxford World's Classics) | Leo Tolstoy                                 | 0.01493      
5327            | War and Peace                                         | Leo Tolstoy                                 | 0.03846      

Expected:
book_no:keyword | title:text                                            | author:text                                 | _score:double
4536            | War and Peace (Signet Classics)                       | [John Hockenberry, 
[truncated]
```

**Issue Reasons:**
- [main] 7 failures in test test {rerank.Reranker using another sort order SYNC} (4.0% fail rate in 173 executions)
- [main] 2 failures in step part-3 (3.9% fail rate in 51 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (4.3% fail rate in 46 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by afoucret**
## Related CI issues: 
Closes #126320
Closes #126322
Closes #126361
Closes #126362
Closes #126363 

## Description:
CSV tests are flaky because of the score rounding
Since we have other tests for it. we decided to dump the score column until we can figure out what happen

### CODE REVIEW

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java [hunk 1]
```diff
@@ -177,8 +179,8 @@ public final void test() throws Throwable {
     }
 
     protected void shouldSkipTest(String testName) throws IOException {
-        if (testCase.requiredCapabilities.contains("semantic_text_field_caps") || testCase.requiredCapabilities.contains("rerank")) {
-            assumeTrue("Inference test service needs to be supported for semantic_text", supportsInferenceTestService());
+        if (Stream.of("semantic_text_field_caps", RERANK.capabilityName()).anyMatch(testCase.requiredCapabilities::contains)) {
```
Comment (ioanatia) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java:182]: nit: we should make this consistent and use `SEMANITC_TEXT_FIELD_CAPS.capabilityName()` if we use `RERANK.capabilityName()`.

**Review by ioanatia — APPROVED** [review]
