### PR TITLE
Change the approach to find the APM Agent property file in test

### LINKED ISSUE #144357: [CI] APMJvmOptionsTests testAPMAgentMetricsDisabledWhenOtelMetricsEnabled failing
**Build Scans:**
- [elasticsearch-intake #36036 / part1](https://gradle-enterprise.elastic.co/s/q3fs5upoah23y)
- [elasticsearch-pull-request #128849 / part-1](https://gradle-enterprise.elastic.co/s/rak42hgxtucdi)
- [elasticsearch-pull-request #128844 / part-1](https://gradle-enterprise.elastic.co/s/5owzbg65rdyla)
- [elasticsearch-pull-request #128817 / part-1](https://gradle-enterprise.elastic.co/s/docnvxb37isj2)
- [elasticsearch-pull-request #128817 / part-1](https://gradle-enterprise.elastic.co/s/g3tvqtpfjlh3y)
- [elasticsearch-pull-request #128798 / part-1](https://gradle-enterprise.elastic.co/s/doruvakwvfy7e)
- [elasticsearch-pull-request #128790 / part-1](https://gradle-enterprise.elastic.co/s/civizf4bvomra)
- [elasticsearch-pull-request #128759 / part-1](https://gradle-enterprise.elastic.co/s/fsuaoy7fb2xj6)
- [elasticsearch-pull-request #128783 / part-1](https://gradle-enterprise.elastic.co/s/bhy6hwyi6c76s)
- [elasticsearch-pull-request #128781 / part-1](https://gradle-enterprise.elastic.co/s/pyslab3riqnq4)

**Reproduction Line:**
```
./gradlew ":distribution:tools:server-cli:test" --tests "org.elasticsearch.server.cli.APMJvmOptionsTests.testAPMAgentMetricsDisabledWhenOtelMetricsEnabled" -Dtests.seed=3B5224E1F6EE2624 -Dtests.locale=ro-Latn-RO -Dtests.timezone=Asia/Sakhalin -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.server.cli.APMJvmOptionsTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAPMAgentMetricsDisabledWhenOtelMetricsEnabled'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.io.IOException: Is a directory
```

**Issue Reasons:**
- [main] 16 failures in test testAPMAgentMetricsDisabledWhenOtelMetricsEnabled (11.9% fail rate in 134 executions)
- [main] 15 failures in step part-1 (13.6% fail rate in 110 executions)
- [main] 13 failures in pipeline elasticsearch-pull-request (11.9% fail rate in 109 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mamazzol**
Change the approach to find the APM Agent property file in tests to replicate what we do when deleting the file at startup.

Closes: #144357 
Closes: #144358

### CODE REVIEW

**Review by mark-vieira — COMMENTED** [review]
Is this a side effect of the CLI launcher changes? If so, what exactly is different here?

File: distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java [hunk 1]
```diff
@@ -179,25 +180,35 @@ public void testAPMAgentMetricsDisabledWhenOtelMetricsEnabled() throws Exception
...
         return properties;
     }
 
+    private static Path findApmConfigPath(List<String> options) {
+        for (String inputArgument : options) {
+            if (inputArgument.startsWith("-javaagent:")) {
+                int configIndex = inputArgument.lastIndexOf("=c=");
+                if (configIndex > 0) {
+                    final Path apmConfig = PathUtils.get(inputArgument.substring(configIndex + 3));
+                    if (Files.isRegularFile(apmConfig) && apmConfig.getFileName().toString().matches("^\\.elstcapm\\..*\\.tmp$")) {
```
Comment (prdoyle) [inline distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java]: Why did this go back to being a regex?

**Review by prdoyle — COMMENTED** [review]
Sorry, I'm still not quite following. Could you link the that "what we do when deleting the file at startup" so I can follow the reasoning?

File: distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java (hunk 1 above)
Comment (mamazzol) [reply distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java]: Replying to both at the same time, here is the logic I am referring to https://github.com/elastic/elasticsearch/blob/85fce7395ec2558815592d42a593803d60bbcd4b/server/src/main/java/org/elasticsearch/node/Node.java#L215 
This uses the regex so I put it back this way.

Comment (prdoyle) [reply distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java]: Ah I see! Maybe let's make that a public constant that can be shared in the code rather than duplicating it? That would make the code itself answer both questions!.

**Review by prdoyle — APPROVED** [review]
