### PR TITLE
Emit nicer error message when trying to install unknown plugin

### LINKED ISSUE #17226: PluginManager: Installing non-existing plugin returns confusing error message
If a plugin does not exist, then this is returned

```
bin/elasticsearch-plugin install nonexistentplugin
-> Downloading nonexistentplugin
Exception in thread "main" java.net.MalformedURLException: no protocol: nonexistentplugin
	at java.net.URL.<init>(URL.java:586)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:211)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:206)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:174)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:162)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:57)
```

Also I cant seem to find out the URL which is actually requested for debugging purposes anymore, might be intended though?

### PR DESCRIPTION
**Pull request by rjernst**
When installing plugins, we first try the elastic download service for
official plugins, then try maven coordinates, and finally try the
argument as a url. This can lead to confusing error messages about
unknown protocols when eg an official plugin name is mispelled. This
change adds a heuristic for determining if the argument in the final
case is in fact a url that we should try, and gives a simplified error
message in the case it is definitely not a url.

closes #17226

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java [hunk 1]
```diff
@@ -237,6 +240,10 @@ private Path download(Terminal terminal, String pluginId, Path tmpDir) throws Ex
         }
 
         // fall back to plain old URL
+        if (pluginId.contains("://") == false) {
```
Comment (dadoonet) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: I used to use file:/path/to/file.zip instead of file://
Not sure if it respects standards but it works.

Comment (dadoonet) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Also I use sometimes (in workshops) file:../relative/path

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Neither of those are valid URLs

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Sorry, I meant those are not valid *URI*s. I can change the check to look for `":/"`

**Comment by rjernst** [comment]
@dadoonet I pushed an update.

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java (hunk 1 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Actually I reverted this. As I thought, file URLs still must contain double slash (see https://en.wikipedia.org/wiki/File_URI_scheme for example). While java URL will parse a URL with a single slash, it doesn't actually work when trying to read the file.

**Comment by spinscale** [comment]
thx for doing it! If we want to be extra fancy, we could apply a similar logic which we use when parsing setting names, using levenshtein to check for similar plugins in order to help on typos... https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java#L247-L270

LGTM otherwise

File: core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java (hunk 1 above)
Comment (dadoonet) [inline core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java]: Fair enough. I know it used to work in previous version but I'm fine with this implementation.
And even better it will be consistent with Kibana plugin manager which also checks that `://` exists.

**Comment by dadoonet** [comment]
LGTM 2

**Comment by rjernst** [comment]
> If we want to be extra fancy, we could apply a similar logic which we use when parsing setting names, using levenshtein to check for similar plugins in order to help on typos

I like this idea! I opened #18896 for a follow up
