### PR TITLE
[GPU] Fix GPU plugin integration tests

### LINKED ISSUE #141561: [CI] GPUPluginInitializationWithGPUIT failing on Windows
This has been failing consistently on Windows (not sure why there was no issue cc @elastic/es-delivery). Sounds like it's not applicable and we should probably just not run this test on that platform.

### CI Link

https://gradle-enterprise.elastic.co/s/lirtdh5llnsau/tests/task/:x-pack:plugin:gpu:internalClusterTest/details/org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT/testTrueModeSupportedVectorType?top-execution=1

### Repro line

gradlew ":x-pack:plugin:gpu:internalClusterTest" --tests "org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT.testAutoModeSupportedVectorType"

### Does it reproduce?

Yes

### Applicable branches

main, 9.3

### Failure history

_No response_

### Failure excerpt

```
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([77BFB7B901B35297:45F32A4A9C0BD2CA]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.junit.Assert.assertNotNull(Assert.java:723)
        at org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT.testAutoModeSupportedVectorType(GPUPluginInitializationWithGPUIT.java:92)
```

### LINKED ISSUE #142070: [CI] GPUPluginInitializationWithGPUIT testTrueModeSupportedVectorType failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11830 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/ofxq3wgihanxk)
- [elasticsearch-periodic-platform-support #11830 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/o7mopztvdafjg)
- [elasticsearch-periodic-java-ea #169 / checkpart2_windows-2025](https://gradle-enterprise.elastic.co/s/upaeg6qvqsvjs)
- [elasticsearch-pull-request #119353 / part-2-windows](https://gradle-enterprise.elastic.co/s/uxm7epextcwza)
- [elasticsearch-periodic-platform-support #11826 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/dbc4k6ubucco2)
- [elasticsearch-periodic-platform-support #11826 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/r7klprz3nzmwa)
- [elasticsearch-periodic-java-ea #168 / checkpart2_windows-2025](https://gradle-enterprise.elastic.co/s/mf6my6fazjq24)
- [elasticsearch-pull-request #119072 / part-2](https://gradle-enterprise.elastic.co/s/zncmixm4wurku)
- [elasticsearch-pull-request #118966 / part-2](https://gradle-enterprise.elastic.co/s/7jqccwd2p3aum)
- [elasticsearch-periodic-platform-support #11822 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/3tyzmw52ga2gg)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:gpu:internalClusterTest" --tests "org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT.testTrueModeSupportedVectorType" -Dtests.seed=857402E41E045EAD -Dtests.locale=ff-Latn-GW -Dtests.timezone=Europe/Saratov -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTrueModeSupportedVectorType'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testTrueModeSupportedVectorType
- [main] 4 consecutive failures in step checkpart2_windows-2025
- [main] 17 failures in test testTrueModeSupportedVectorType (1.8% fail rate in 954 executions)
- [main] 5 failures in step windows-2022_checkpart2_platform-support-windows (55.6% fail rate in 9 executions)
- [main] 5 failures in step windows-2025_checkpart2_platform-support-windows (55.6% fail rate in 9 executions)
- [main] 2 failures in step part-2 (0.3% fail rate in 580 executions)
- [main] 4 failures in step checkpart2_windows-2025 (100.0% fail rate in 4 executions)
- [main] 5 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 5 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.5% fail rate in 578 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-java-ea (100.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #142071: [CI] GPUPluginInitializationWithGPUIT testTrueModeLicenseNotSupported failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11830 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/ofxq3wgihanxk)
- [elasticsearch-periodic-platform-support #11830 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/o7mopztvdafjg)
- [elasticsearch-periodic-java-ea #169 / checkpart2_windows-2025](https://gradle-enterprise.elastic.co/s/upaeg6qvqsvjs)
- [elasticsearch-pull-request #119353 / part-2-windows](https://gradle-enterprise.elastic.co/s/uxm7epextcwza)
- [elasticsearch-periodic-platform-support #11826 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/dbc4k6ubucco2)
- [elasticsearch-periodic-platform-support #11826 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/r7klprz3nzmwa)
- [elasticsearch-periodic-java-ea #168 / checkpart2_windows-2025](https://gradle-enterprise.elastic.co/s/mf6my6fazjq24)
- [elasticsearch-pull-request #119072 / part-2](https://gradle-enterprise.elastic.co/s/zncmixm4wurku)
- [elasticsearch-pull-request #118966 / part-2](https://gradle-enterprise.elastic.co/s/7jqccwd2p3aum)
- [elasticsearch-periodic-platform-support #11822 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/3tyzmw52ga2gg)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:gpu:internalClusterTest" --tests "org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT.testTrueModeSupportedVectorType" -Dtests.seed=857402E41E045EAD -Dtests.locale=ff-Latn-GW -Dtests.timezone=Europe/Saratov -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTrueModeLicenseNotSupported'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testTrueModeLicenseNotSupported
- [main] 4 consecutive failures in step checkpart2_windows-2025
- [main] 17 failures in test testTrueModeLicenseNotSupported (1.8% fail rate in 954 executions)
- [main] 5 failures in step windows-2022_checkpart2_platform-support-windows (55.6% fail rate in 9 executions)
- [main] 5 failures in step windows-2025_checkpart2_platform-support-windows (55.6% fail rate in 9 executions)
- [main] 2 failures in step part-2 (0.3% fail rate in 580 executions)
- [main] 4 failures in step checkpart2_windows-2025 (100.0% fail rate in 4 executions)
- [main] 5 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 5 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.5% fail rate in 578 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-java-ea (100.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #142072: [CI] GPUPluginInitializationWithGPUIT testAutoModeSupportedVectorType failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11830 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/ofxq3wgihanxk)
- [elasticsearch-periodic-platform-support #11830 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/o7mopztvdafjg)
- [elasticsearch-periodic-java-ea #169 / checkpart2_windows-2025](https://gradle-enterprise.elastic.co/s/upaeg6qvqsvjs)
- [elasticsearch-pull-request #119353 / part-2-windows](https://gradle-enterprise.elastic.co/s/uxm7epextcwza)
- [elasticsearch-periodic-platform-support #11826 / windows-2025_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/dbc4k6ubucco2)
- [elasticsearch-periodic-platform-support #11826 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/r7klprz3nzmwa)
- [elasticsearch-periodic-java-ea #168 / checkpart2_windows-2025](https://gradle-enterprise.elastic.co/s/mf6my6fazjq24)
- [elasticsearch-pull-request #119072 / part-2](https://gradle-enterprise.elastic.co/s/zncmixm4wurku)
- [elasticsearch-pull-request #118966 / part-2](https://gradle-enterprise.elastic.co/s/7jqccwd2p3aum)
- [elasticsearch-periodic-platform-support #11822 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/3tyzmw52ga2gg)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:gpu:internalClusterTest" --tests "org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT.testTrueModeSupportedVectorType" -Dtests.seed=857402E41E045EAD -Dtests.locale=ff-Latn-GW -Dtests.timezone=Europe/Saratov -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.gpu.GPUPluginInitializationWithGPUIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAutoModeSupportedVectorType'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testAutoModeSupportedVectorType
- [main] 4 consecutive failures in step checkpart2_windows-2025
- [main] 17 failures in test testAutoModeSupportedVectorType (1.8% fail rate in 954 executions)
- [main] 5 failures in step windows-2022_checkpart2_platform-support-windows (55.6% fail rate in 9 executions)
- [main] 5 failures in step windows-2025_checkpart2_platform-support-windows (55.6% fail rate in 9 executions)
- [main] 2 failures in step part-2 (0.3% fail rate in 580 executions)
- [main] 4 failures in step checkpart2_windows-2025 (100.0% fail rate in 4 executions)
- [main] 5 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 5 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.5% fail rate in 578 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-java-ea (100.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
Refactor the GPUPlugin code to abstract GPUSupport functionality through an interface, update tests to use a mock implementation when needed.

Fixes https://github.com/elastic/elasticsearch/issues/141561
Fixes https://github.com/elastic/elasticsearch/issues/142070
Fixes https://github.com/elastic/elasticsearch/issues/142071
Fixes https://github.com/elastic/elasticsearch/issues/142072

### CODE REVIEW

File: libs/gpu-codec/src/main/java/org/elasticsearch/gpu/codec/ES92GpuHnswSQVectorsFormat.java [hunk 1]
```diff
@@ -39,13 +41,22 @@ public class ES92GpuHnswSQVectorsFormat extends KnnVectorsFormat {
...
+    public ES92GpuHnswSQVectorsFormat(
+        GPUSupport gpuSupport,
+        int maxConn,
+        int beamWidth,
+        Float confidenceInterval,
+        int bits,
+        boolean compress
+    ) {
         super(NAME);
+        this.gpuSupport = gpuSupport;
```
Comment (ChrisHegarty) [inline libs/gpu-codec/src/main/java/org/elasticsearch/gpu/codec/ES92GpuHnswSQVectorsFormat.java]: I think that this is fine, but one observation is that gpuSupport is only used to determine the total GPU Memory, which could be passed in directly.

File: libs/gpu-codec/src/main/java/org/elasticsearch/gpu/GPUSupport.java [hunk 2]
```diff
@@ -9,169 +9,45 @@
...
     /**
      * Returns the name of the first available compatible GPU, or null if no GPU is available.
      */
-    public static String getGpuName() {
-        return Holder.GPU_INFO.name();
-    }
+    String getGpuName();
+
+    // TODO: move this to a more appropriate place (ad-hoc class? GPUPlugin?)
+    AtomicLong GPU_USAGE_COUNT = new AtomicLong();
```
Comment (ChrisHegarty) [inline libs/gpu-codec/src/main/java/org/elasticsearch/gpu/GPUSupport.java:38]: I think that this is only used by the Plugin? But let's leave it here for now.

**Review by ChrisHegarty — APPROVED** [review]

File: x-pack/plugin/gpu/src/main/java/org/elasticsearch/xpack/gpu/GPUPlugin.java
Comment (mayya-sharipova) [inline x-pack/plugin/gpu/src/main/java/org/elasticsearch/xpack/gpu/GPUPlugin.java]: Can we also pass `gpuSupport` to `ES92GpuHnswVectorsFormat` constructor?

**Review by mayya-sharipova — COMMENTED** [review]
@ldematte Thanks for the PR, nice refactoring.

My main comment would it make sense to create a static instance of CuVSGPUSupport and reuse it in main code and tests, instead of creating a new instance?

```
      public static final CuVSGPUSupport INSTANCE = new CuVSGPUSupport();

```

File: x-pack/plugin/gpu/src/yamlRestTest/resources/rest-api-spec/test/gpu/not-supported/30_usage.yml [hunk 3]
```diff
@@ -0,0 +1,11 @@
+---
+"Test GPU vector indexing xpack info":
+  - requires:
+      cluster_features: ["vectors.indexing.gpu_monitoring"]
+      reason: "GPU monitoring feature required"
+
+  - do:
+      xpack.info: {}
```
Comment (mayya-sharipova) [inline x-pack/plugin/gpu/src/yamlRestTest/resources/rest-api-spec/test/gpu/not-supported/30_usage.yml:8]: Let's add _xpack/usage that's where the error was

**Review by mayya-sharipova — APPROVED** [review]
@ldematte Thanks Lorenzo. And thanks for adding additional yml test. let's also add _xpack/usage test

File: x-pack/plugin/gpu/src/yamlRestTest/resources/rest-api-spec/test/gpu/not-supported/30_usage.yml (hunk 3 above)
Comment (ldematte) [reply x-pack/plugin/gpu/src/yamlRestTest/resources/rest-api-spec/test/gpu/not-supported/30_usage.yml:8]: Done, and added cases for disabled vs not supported (they all pass)
