### PR TITLE
Fix filter cache setting to allow percentages

### LINKED ISSUE #20330: failed to parse setting: percentage value not recognized.
**Elasticsearch version**: 5.0.0_alpha5

**Plugins installed**: x-pack 5.0.0_alpha5

**JVM version**: OpenJDK Runtime Environment (build 1.8.0_101-b13)

**OS version**: Linux 4.4.11-23.53.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:

Elasticsearch failed to start with the following error message:
[WARN ][bootstrap                ] [elk5a_node01] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupError: java.lang.IllegalArgumentException: failed to parse setting [indices.fielddata.cache.size] with value [50%] as a size in bytes: unit is missing or unrecognized
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:105)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
        at org.elasticsearch.cli.Command.main(Command.java:54)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
Caused by: java.lang.IllegalArgumentException: failed to parse setting [indices.fielddata.cache.size] with value [50%] as a size in bytes: unit is missing or unrecognized
        at org.elasticsearch.common.settings.Setting.get(Setting.java:307)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:272)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138)
        at org.elasticsearch.node.Node.<init>(Node.java:298)
        at org.elasticsearch.node.Node.<init>(Node.java:206)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:255)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
        ... 6 more
Caused by: ElasticsearchParseException[failed to parse setting [indices.fielddata.cache.size] with value [50%] as a size in bytes: unit is missing or unrecognized]
        at org.elasticsearch.common.unit.ByteSizeValue.parseBytesSizeValue(ByteSizeValue.java:213)
        at org.elasticsearch.common.unit.ByteSizeValue.parseBytesSizeValue(ByteSizeValue.java:172)
        at org.elasticsearch.common.settings.Setting.lambda$byteSizeSetting$18(Setting.java:571)
        at org.elasticsearch.common.settings.Setting.get(Setting.java:305)
        ... 15 more

**Steps to reproduce**:
 1. Add the following lines to elasticsearch.yml

indices.fielddata.cache.size: "50%"
indices.queries.cache.size: "20%"

 2. Restart elasticsearch

### PR DESCRIPTION
**Pull request by colings86**
During adding the new settings infrastructure the option to specify the
size of the filter cache as a percentage of the heap size which accidentally
removed. This change adds that ability back.

In addition the `Setting` class had multiple `.byteSizeSetting` methods
which all except one used `ByteSizeValue.parseBytesSizeValue` to parse
the value. One method used `MemorySizeValue.parseBytesSizeValueOrHeapRatio`.
This was confusing as the way the value was parsed depended on how many
arguments were provided.

This change makes all `Setting.byteSizeSetting` methods parse the value
the same way using `ByteSizeValue.parseBytesSizeValue` and adds
`Setting.memorySizeSetting` methods to parse settings that express memory
sizes (i.e. can be absolute bytes values or percentages). Relevant settings
have been moved to use these new methods.

Closes #20330

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java [hunk 1]
```diff
@@ -54,9 +54,9 @@
     public static final Setting<String> REPOSITORIES_LOCATION_SETTING =
         new Setting<>("repositories.fs.location", LOCATION_SETTING, Function.identity(), Property.NodeScope);
     public static final Setting<ByteSizeValue> CHUNK_SIZE_SETTING =
-        Setting.byteSizeSetting("chunk_size", "-1", Property.NodeScope);
+        Setting.memorySizeSetting("chunk_size", "-1", Property.NodeScope);
     public static final Setting<ByteSizeValue> REPOSITORIES_CHUNK_SIZE_SETTING =
-        Setting.byteSizeSetting("repositories.fs.chunk_size", "-1", Property.NodeScope);
+        Setting.memorySizeSetting("repositories.fs.chunk_size", "-1", Property.NodeScope);
```
Comment (colings86) [inline core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java]: Should these two settings have the ability to specify as a percentage of heap as well as absolute bytes?

File: core/src/main/java/org/elasticsearch/common/settings/Setting.java [hunk 2]
```diff
@@ -551,9 +551,11 @@ public static TimeValue parseTimeValue(String s, TimeValue minValue, String key)
...
     }
 
-    public static Setting<ByteSizeValue> byteSizeSetting(String key, String percentage, Property... properties) {
-        return new Setting<>(key, (s) -> percentage, (s) -> MemorySizeValue.parseBytesSizeValueOrHeapRatio(s, key), properties);
-    }
+    // public static Setting<ByteSizeValue> byteSizeSetting(String key, String
+    // percentage, Property... properties) {
+    // return new Setting<>(key, (s) -> percentage, (s) ->
+    // ByteSizeValue.parseBytesSizeValue(s, key), properties);
+    // }
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/settings/Setting.java]: Can we remove the commented out code?

File: core/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java [hunk 3]
```diff
@@ -52,7 +52,8 @@
 public class IndexingMemoryController extends AbstractComponent implements IndexingOperationListener, Closeable {
 
     /** How much heap (% or bytes) we will share across all actively indexing shards on this node (default: 10%). */
-    public static final Setting<ByteSizeValue> INDEX_BUFFER_SIZE_SETTING = Setting.byteSizeSetting("indices.memory.index_buffer_size", "10%", Property.NodeScope);
+    public static final Setting<ByteSizeValue> INDEX_BUFFER_SIZE_SETTING = Setting.memorySizeSetting("indices.memory.index_buffer_size",
+            "10%", Property.NodeScope);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java]: Nit: Can we reformat this by just moving everything after the equals sign to the next line with continuation indentation so that all the parameters and the `Setting.memorySizeSetting` invocation should fit on one line then?

File: core/src/main/java/org/elasticsearch/common/settings/Setting.java (hunk 2 above)
Comment (colings86) [inline core/src/main/java/org/elasticsearch/common/settings/Setting.java]: Oops, I thought I had :)

File: core/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java [hunk 4]
```diff
@@ -49,7 +49,7 @@
 
 public class IndicesQueryCache extends AbstractComponent implements QueryCache, Closeable {
 
-    public static final Setting<ByteSizeValue> INDICES_CACHE_QUERY_SIZE_SETTING = Setting.byteSizeSetting(
+    public static final Setting<ByteSizeValue> INDICES_CACHE_QUERY_SIZE_SETTING = Setting.memorySizeSetting(
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java]: Same thing here, move the invocation to the next line with continuation indentation so that the invocation and its parameters are together?

File: core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java]: I don't think so, I think these should be bytes or size-value only.

**Comment by jasontedor** [comment]
@colings86 I left one comment about some commented out code, some nits about formatting, and a response to your question about the chunk size settings.

File: core/src/main/java/org/elasticsearch/common/settings/Setting.java [hunk 5]
```diff
@@ -591,6 +587,18 @@ public static ByteSizeValue parseByteSize(String s, ByteSizeValue minValue, Byte
         return value;
     }
 
+    public static Setting<ByteSizeValue> memorySizeSetting(String key, ByteSizeValue value, Property... properties) {
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/common/settings/Setting.java]: can we get some javadocs here and also document what the differences are to the `byteSizeSetting` methods

File: core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java (hunk 1 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java]: ++ to keep byteSizeSetting here

File: core/src/main/java/org/elasticsearch/common/settings/Setting.java (hunk 5 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/common/settings/Setting.java]: I'd also appreciate some tests here for these methods and also for the settings that are supposed to accept percentages

File: core/src/test/java/org/elasticsearch/common/settings/MemorySizeSettingsTests.java [hunk 6]
```diff
@@ -0,0 +1,88 @@
+/*
```
Comment (colings86) [inline core/src/test/java/org/elasticsearch/common/settings/MemorySizeSettingsTests.java]: Not sure if these tests are better here in one place or if they should be in separate test classes for each class that defines one of the settings?

**Comment by colings86** [comment]
@s1monw @jasontedor thanks for the reviews, I have pushed a commit that should address your comments

**Comment by s1monw** [comment]
LGTM
