### PR TITLE
Recursively Delete Unreferenced Index Directories

### LINKED ISSUE #13159: Crashing during snapshot deletion might result in unreferenced data left in repository
It's currently possible to end up with unreferenced data in a snapshot repository, given the following steps:
1. Create a index, `foobar`, with size `X bytes`
2. Snapshot cluster
3. Start deleting the snapshot, crash after deleting `snapshot-{}` and `metadata-{}` files
4. Delete index `foobar`
5. Snapshot cluster again

Normally, step 5 would cause the files no longer referenced by any snapshots do be deleted, but if the underlying index is deleted as well, they won't get cleaned up. In the example above, there would be `X bytes` of disk space used without any snapshot referencing them. Given sufficiently large values of `X`, this could be a significant amount of storage wasted. Even with small amounts of data, this might accrue over time to become significant.

Suggestion: create a `deleting-{}` file as a sibling of the `snapshot-{}` file that gets written before the files referenced by the snapshot gets deleted. When the deletion has been completed, this file should be the last one deleted. These files indicates that a deletion is in progress or have been attempted so it's possible to tell that the snapshot might be in a half-deleted state (so we can avoid using it). It should also enable later snapshot processes to continue the deletion process where the previous left off.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Add ability to list child "folders" in the blob store
   * Use it to implement recursive delete on all stale index folders when cleaning up instead of using the diff between two `RepositoryData` instances to cover aborted deletes and blocked primaries writing things after a snapshot has already failed
   * The safety of this operation is guaranteed by the fact that we get the list of to-delete indices before we write the new index-N blob, hence we can't accidentally delete any indices that might be created after the index-N has been written and will only run the cleanup if writing the index-N succeeds.
* Clean up on delete operations to keep the number of blobs to clean up in continuous operation low. In case of a clean repository the overhead of running the cleanup logic is completely negligible (it's only a few list calls on the indices path that's it and those are cheap since we can and do filter for first level children only in all three implementations).
* Add new infrastructure for running `*IT` style third party tests against real Azure, GCS and S3 repositories.
   * For S3 we also run the tests against Minio
   * I manually verified the 3rd party tests to work with real repositories and they don't require new infrastructure in Jenkins since they are triggered via the same env variables used by the REST style 3rd party tests already. The performance on GCS and S3 seems to be a non-issue due to bulk deletes, on Azure the situation is a little more dicey and since we don't have bulk delete and I'll try to speed up deletes there in another PR I'm working on now. 

* closes #13159

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/MetadataLoadingDuringSnapshotRestoreIT.java [hunk 1]
```diff
@@ -141,8 +141,8 @@ public void testWhenMetadataAreLoaded() throws Exception {
         // Deleting a snapshot does not load the global metadata state but loads each index metadata
         assertAcked(client().admin().cluster().prepareDeleteSnapshot("repository", "snap").get());
         assertGlobalMetadataLoads("snap", 1);
-        assertIndexMetadataLoads("snap", "docs", 5);
-        assertIndexMetadataLoads("snap", "others", 4);
+        assertIndexMetadataLoads("snap", "docs", 4);
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/snapshots/MetadataLoadingDuringSnapshotRestoreIT.java]: Now we don't need to read meta blobs to get an index's shard count before deleting since we just get that from the child container listing.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 2]
```diff
@@ -426,46 +425,75 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
...
             // Delete snapshot from the index file, since it is the maintainer of truth of active snapshots
-            final RepositoryData repositoryData;
             final RepositoryData updatedRepositoryData;
+            final BlobContainer indicesBlobContainer = blobStore().blobContainer(basePath().add("indices"));
+            final Map<String, BlobContainer> foundIndices;
             try {
-                repositoryData = getRepositoryData();
+                final RepositoryData repositoryData = getRepositoryData();
                 updatedRepositoryData = repositoryData.removeSnapshot(snapshotId);
+                // Cache the indices that were found before writing out the new index-N blob so that a stuck master will never
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I think this approach of listing before writing the updated `index-N` makes this approach completely safe even on an eventually consistent blob store. If an index uuid (the snapshot uuid, not the CS one!) goes out of scope here for a single `index-N` it will never be reused in a future `index-M` (`M > N)` => we don't have to care about stuck master nodes coming back to haunt us.
What we could however do is optimize this a little and maybe write a `SUCCESS-N` blob after we finished all operations that went into a given `index-N` blob and only run the listing if we suspect dangling indices because an operation that wrote a given `index-N` didn't finish fully.
The downside of this is, that it gets a little complicated when you have to account for master failover scenarios and may not be worth it performance wise now that we have bulk deletes and could parallelize the recursive delete as well.

**Comment by original-brownbear** [comment]
@ywelsch @andrershov I think this would be a very neat low-risk step we could take independently of other improvements to the blob store. This will just automatically clean up stale indices down the line and there is no need of any tomb-stone logic with this solution.
Going ahead with this would only leave cleaning up stale `snap-${uuid}.dat` files (and subsequently fixing the related `index-N` in the shard folders) and we'd be good on the stale blobs front I think (this is a little trickier but also less important in it's likely impact on repository size).

Just asking for some early feedback here on the WIP PR before I go through the pain of implementing actual integration tests that verify the list children implementations :)

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 3]
```diff
@@ -426,46 +425,75 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
...
             try {
                 blobContainer().deleteBlobsIgnoringIfNotExists(
                     Arrays.asList(snapshotFormat.blobName(snapshotId.getUUID()), globalMetaDataFormat.blobName(snapshotId.getUUID())));
             } catch (IOException e) {
                 logger.warn(() -> new ParameterizedMessage("[{}] Unable to delete global metadata files", snapshotId), e);
             }
+            final var survivingIndices = updatedRepositoryData.getIndices();
             deleteIndices(
                 Optional.ofNullable(finalSnapshotInfo)
-                    .map(info -> info.indices().stream().map(repositoryData::resolveIndexId).collect(Collectors.toList()))
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: No need to run partial deletes on indices that went fully out of scope now. This would be great to have for #41581 because if we were to delay writing the metadata in the current implementation, we run into the messy spot of not knowing about the shards if we fail to write the index metadata -> current implementation couldn't delete the stale blobs from a partial upload of a new index.

**Comment by original-brownbear** [comment]
@ywelsch @andrershov I take todays discussion as meaning that the general idea here is good enough so I'll go ahead and implement strong tests here + clean up the code in the repository implementations => no need to review this yet, I'll re-request review once ready (should be shortlyish).

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
@ywelsch @andrershov I think the implementation here is getting to an ok point now, but I'm wondering about the right approach to testing this.

It seems to me the only way of getting some real coverage on GCS and Azure here would be third party tests. Unfortunately, aside from just having the real repositories available we also need the ability to do a few operations (create some stale data and verify it's gone later on) which the current rest 3rd party tests don't easily allow for.

What do you think about doing the same thing I did for HDFS for tests for S3, Azure and GCs (see HDFS impl. https://github.com/elastic/elasticsearch/pull/42189/files#diff-c347d8684917892a49d79be15fca9678R165) and create 3rd party tests using the `*IT` infrastructure? (for HDFS this was zero effort since HDFS offered a proper mock impl.) This seems like the least code required option and easiest to maintain. If we implement these tests as REST tests then we'd need some secondary infrastructure for accessing the repositories which seems kind of horrible.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by ywelsch** [comment]
> What do you think about... and create 3rd party tests using the *IT infrastructure? 

makes sense to me.

**Comment by original-brownbear** [comment]
> >What do you think about... and create 3rd party tests using the *IT infrastructure?

> makes sense to me.

Alright will implement tomorrow :)

**Comment by original-brownbear** [comment]
@ywelsch @andrershov I think this one is good to go. Added (third party) tests for the cleanup for all repository implementations now and cleaned things up reasonably.

Once Cloud gets around to providing some test data it would be good to verify the performance on Azure though (I did some tests on S3 and GCS and the time a cleanup takes is very reasonable here since we can delete 1k or 100 blobs per delete call respectively ... also, worst case someone aborting a cleanup operation forcefully isn't catastrophic and the next run of a snapshot or delete operation will simply pick up where the aborted one left off effectively).
I'll look into Azure performance now in parallel, it should be possible to speed things up there as well. The idea of potentially having to clean up tens of thousands of blobs sequentially seems a little problematic otherwise.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (slow Jenkins ...)

**Comment by ywelsch** [comment]
Can you split out the infrastructure for the third-party tests here into a separate PR (and add a simple  test to show that it works)? It will make this easier to review as a follow-up then.

**Comment by original-brownbear** [comment]
@ywelsch sure on it :)

**Comment by original-brownbear** [comment]
@ywelsch done extracting the test infra in https://github.com/elastic/elasticsearch/pull/42586

**Comment by original-brownbear** [comment]
@ywelsch this should be good for a review now, the extraction of the test infrastructure is merged into `master` and hence this PR now :)

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java [hunk 4]
```diff
@@ -231,6 +233,50 @@ public void deleteBlobIgnoringIfNotExists(String blobName) throws IOException {
...
+                }) : "Response contained children for listed common prefixes.";
+                if (list.isTruncated()) {
+                    prevListing = list;
+                } else {
+                    break;
+                }
+            }
+            return Maps.ofEntries(entries);
+        } catch (final AmazonClientException e) {
+            throw new IOException("Exception when listing children", e);
```
Comment (ywelsch) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java]: also mention current path here

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java [hunk 5]
```diff
@@ -231,6 +233,50 @@ public void deleteBlobIgnoringIfNotExists(String blobName) throws IOException {
...
+            final var entries = new ArrayList<Map.Entry<String, BlobContainer>>();
+            while (true) {
+                ObjectListing list;
+                if (prevListing != null) {
+                    final ObjectListing finalPrevListing = prevListing;
+                    list = SocketAccess.doPrivileged(() -> clientReference.client().listNextBatchOfObjects(finalPrevListing));
+                } else {
+                    final ListObjectsRequest listObjectsRequest = new ListObjectsRequest();
+                    listObjectsRequest.setBucketName(blobStore.bucket());
+                    listObjectsRequest.setPrefix(keyPath);
```
Comment (ywelsch) [inline plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java]: In the example that the SDK provides for `getCommonPrefixes`, it adds `/` to the prefix that is queried. Should we do the same?

```
     * If calling <code>listObjects</code> with the prefix="foo/" and the delimiter="/" on 
     * this bucket, the returned <code>S3ObjectListing</code> 
     * will contain one entry in the common
     * prefixes list ("foo/bar/") and none of the keys beginning with that
     * common prefix will be included in the object summaries list.
```

File: server/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java [hunk 6]
```diff
@@ -158,6 +158,16 @@ default void deleteBlobIgnoringIfNotExists(String blobName) throws IOException {
      */
     Map<String, BlobMetaData> listBlobs() throws IOException;
 
+    /**
+     * Lists all child containers under this container. A child container is defined as a container whose {@link #path()} method returns
+     * a path that has the return  of this container's {@link #path()} method as a prefix with a single path component added to it.
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java]: this reads a bit funnily, maybe rephrase

File: server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java [hunk 7]
```diff
@@ -73,6 +74,22 @@ public FsBlobContainer(FsBlobStore blobStore, BlobPath blobPath, Path path) {
...
     }
 
+    @Override
+    public Map<String, BlobContainer> children() throws IOException {
+        // If we get duplicate files we should just take the last entry
+        Map<String, BlobContainer> builder = new HashMap<>();
+        try (DirectoryStream<Path> stream = Files.newDirectoryStream(path)) {
+            for (Path file : stream) {
+                final BasicFileAttributes attrs = Files.readAttributes(file, BasicFileAttributes.class);
+                if (attrs.isDirectory()) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java]: why not just use `Files.isDirectory(file)`?

File: server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java [hunk 8]
```diff
@@ -73,6 +74,22 @@ public FsBlobContainer(FsBlobStore blobStore, BlobPath blobPath, Path path) {
         return listBlobsByPrefix(null);
     }
 
+    @Override
+    public Map<String, BlobContainer> children() throws IOException {
+        // If we get duplicate files we should just take the last entry
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java]: why would we expect duplicates?

**Review by ywelsch — CHANGES_REQUESTED** [review]
I've only reviewed the `BlobContainer.children()` method. Can we have a separate PR for this and more extensive testing for that as well in the form of third-party tests? I'm thinking tests along the lines of `ESBlobStoreContainerTestCase`, but against the real service. We can use `AbstractThirdPartyRepositoryTestCase` for that, and get the `BlobContainer` directly from the `BlobStoreRepository` of the node.

**Comment by original-brownbear** [comment]
@ywelsch sure on it, will fix the points you raised in that then :)

File: plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 9]
```diff
@@ -142,6 +142,22 @@ private boolean doesBucketExist(String bucketName) {
         return mapBuilder.immutableMap();
     }
 
+    Map<String, BlobContainer> listChildren(BlobPath path) throws IOException {
+        final String pathStr = path.buildAsString();
+        final MapBuilder<String, BlobContainer> mapBuilder = MapBuilder.newMapBuilder();
+        SocketAccess.doPrivilegedVoidIOException
+            (() -> client().get(bucketName).list(BlobListOption.currentDirectory()).iterateAll().forEach(blob -> {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply plugins/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: 🤦‍♂ yea, obviously when I fixed the listing style to use `BlobListOption.currentDirectory()` I just replaced the prefix condition with it ..., will fix.

File: server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java (hunk 8 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java]: Good question, for some reason I just mindlessly copied that comment from the list by prefix method. It makes 0 sense imo, I'll just remove it.

File: server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java (hunk 7 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java]: jup ... this was just a left over from copying the logic of list by prefix, adjusting :)

**Comment by original-brownbear** [comment]
@ywelsch extracted logic for listing children in https://github.com/elastic/elasticsearch/pull/42653 and either adjusted code or answered your points here I hope.

File: plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java (hunk 5 above)
Comment (original-brownbear) [reply plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java]: As a matter of fact I think that Javadoc is wrong. If I add the `/` listing child directories fails in my testing. I can look into that after my vacation and maybe open a PR to the SDK.

**Comment by andrershov** [comment]
@original-brownbear could you please integrate changes made by the spin-off PR (seems that there are a lot of merge conflicts) and re-request review from me afterwards?

**Comment by original-brownbear** [comment]
@andrershov @ywelsch this one is good to review again :) thanks!

File: plugins/repository-hdfs/src/test/java/org/elasticsearch/repositories/hdfs/HdfsTests.java [hunk 10]
```diff
@@ -145,6 +156,83 @@ public void testSimpleWorkflow() {
         ClusterState clusterState = client.admin().cluster().prepareState().get().getState();
         assertThat(clusterState.getMetaData().hasIndex("test-idx-1"), equalTo(true));
         assertThat(clusterState.getMetaData().hasIndex("test-idx-2"), equalTo(false));
+        final BlobStoreRepository repo =
+            (BlobStoreRepository) getInstanceFromNode(RepositoriesService.class).repository("test-repo");
+        BlobStoreTestUtil.assertConsistency(repo, repo.threadPool().executor(ThreadPool.Names.GENERIC));
+    }
+
+    public void testCleanup() {
```
Comment (ywelsch) [inline plugins/repository-hdfs/src/test/java/org/elasticsearch/repositories/hdfs/HdfsTests.java]: why have this test here? Isn't this covered by `HdfsRepositoryTests`?

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java [hunk 11]
```diff
@@ -418,9 +419,9 @@ public void testSnapshotDuringNodeShutdown() throws Exception {
         SnapshotInfo snapshotInfo = waitForCompletion("test-repo", "test-snap", TimeValue.timeValueSeconds(60));
         logger.info("Number of failed shards [{}]", snapshotInfo.shardFailures().size());
         logger.info("--> done");
+        BlobStoreTestUtil.assertRepoConsistency(internalCluster(), "test-repo");
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: instead of adding this to the end of each test, can't we just do this with an `@After`?

File: test/framework/src/main/java/org/elasticsearch/repositories/AbstractThirdPartyRepositoryTestCase.java [hunk 12]
```diff
@@ -181,6 +184,86 @@ protected void doRun() throws Exception {
         }
     }
 
+    public void testCleanup() throws Exception {
```
Comment (ywelsch) [inline test/framework/src/main/java/org/elasticsearch/repositories/AbstractThirdPartyRepositoryTestCase.java]: should we also add another test which does a full-cluster restart during a snapshot  or a snapshot delete? This should result in repo garbage as well, and will be more realistic in the garbage that's created.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 13]
```diff
@@ -399,46 +398,88 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
...
-                                    "but failed to clean up their index folders.", metadata.name(), unreferencedIndices), e);
-                    }
+                    cleanupStaleIndices(indicesBlobContainer, foundIndices, survivingIndices);
                     return null;
                 })
             );
         }
     }
 
+    private void cleanupStaleIndices(BlobContainer indicesBlobContainer, Map<String, BlobContainer> foundIndices,
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: why pass both `foundIndices` and `survivingIndices` to this method?  Perhaps compute `staleIndices`,  which is a subset of `Map<String, BlobContainer> foundIndices`, directly on  the caller side?

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 14]
```diff
@@ -399,46 +398,88 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
...
+                        logger.debug("[{}] Cleaned up stale index [{}].", metadata.name(), indexSnId);
+                    }
+                } catch (IOException e) {
+                    logger.warn(() -> new ParameterizedMessage(
+                        "[{}] index {} is no longer part of any snapshots in the repository, " +
+                            "but failed to clean up their index folders.", metadata.name(), indexSnId), e);
+                }
+            }
+            try {
+                indicesBlobContainer.deleteBlobsIgnoringIfNotExists(toDelete);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: this is still there to clean-up directories, right? We're somewhat breaking abstractions here.
I wonder if we should provide a `deleteDirectoryBlob` method on BlobContainer that can be more efficiently be implemented by `FSBlobContainer` and `HDFSBlobContainer`, instead of now iterating over all files for those as well. Alternatively, we could have a `deleteAll` method on BlobContainer that completely removes the BlobContainer, including the dir that it's part of.

Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: It would also make `deleteContents`, which is further below, an implementation detail.

**Review by ywelsch — CHANGES_REQUESTED** [review]
I've done a first pass, leaving some comments.

File: plugins/repository-hdfs/src/test/java/org/elasticsearch/repositories/hdfs/HdfsTests.java (hunk 10 above)
Comment (original-brownbear) [reply plugins/repository-hdfs/src/test/java/org/elasticsearch/repositories/hdfs/HdfsTests.java]: Wops, leftover from extracting things to other PRs -> removing :)

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java (hunk 11 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: Can't do that unfortunately since we have some tests that leave the repo in a different broken state (I will explain below in a sec, but same goes for the other tests I added this to). Also, some tests use multiple repositories => adding it manually seemed easier than adding some other logic to keep track of what repos were created etc.

File: test/framework/src/main/java/org/elasticsearch/repositories/AbstractThirdPartyRepositoryTestCase.java (hunk 12 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/repositories/AbstractThirdPartyRepositoryTestCase.java]: We wouldn't fully pass that test yet :( As discussed, we are still leaking `snap-${uuid}.dat` blobs even with this fix. So if we force a full restart we will eventually get into the state of leaving those files. This PR only cleans up stale indices.

That said: I have another branch that also deals with this case but it has this one (and a few other cleanup PRs I raised) as a dependency and we can look into that once we're done with the stale indices I guess? Then I'm all for testing full cluster restarts :)

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 13 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I basically just kept it like this to keep things a little drier. I figured since the ordering of RPC calls is really important in the two methods that call this so that things don't run in the wrong order I'd have as little logic in those as possible outside of the RPC calls they trigger.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 14 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: As far as the abstractions go: I'm wondering if that is still true in the real world. I just tested this and if I create a few objects in a folder and delete them, I still get the common prefix listed until I delete it (even in the S3 UI I can create an empty folder that then comes up as a common prefix).
Also S3 nowadays treats any object ending in `/` as a folder and doesn't record its size or metadata (see https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html). The same goes for Azure and GCS afaik.

That said, I think it's technically fine to make this logic an implementation detail of `BlobContainer`, I mainly liked the current approach for its simplicity in back porting :)
Practically, I'm also not sure we get much out of it (yet):
* For FS and HDFS a recursive/folder delete will still have to go through all the directories and list all the files and the delete one by one. `FileTreeWalker` might be a little more efficient here algorithmically but I don't think it practically matters for real world NFS latencies?
* For Azure + S3 implementations I could see a stronger case because we could massively optimize here by moving to non-blocking IO SDK releases and run listing and deleting in parallel (technically we could do this already in Azure where we now have the internal thread pool ...). Since we need the listing functionality publicly exposed anyway for the cleanup algorithm, maybe we could do that refactoring just in `7.x` and `8` and look into possible optimizations there and keep changes for `6.x` as short as possible?

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Sorry forgot to add: having the container delete itself is a little tricky in the current implementation(s) of the container and would require more changes than this approach because the container doesn't always have "all the information" available to delete itself (it's all trivial changes but not sure we want that noise for 6.x when it's just making the code look a little nicer there?).

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java (hunk 11 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: should we instead have those tests opt out of the check behavior perhaps? It creates less noise and is perhaps more specific in what remains to be addressed.

Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: I guess we could do that => let me see what I can do there, on it :)

Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: How about af47bb8 ? :) Seems my memory didn't serve me well here and we actually only have a single test that leave the repo in broken (and not yet cleaned up state). :)

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 14 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: >  if I create a few objects in a folder and delete them, I still get the common prefix listed until I delete it

perhaps we should test for this in AbstractThirdPartyRepositoryTestCase to check that all implementations guarantee this behavior

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 15]
```diff
@@ -399,46 +398,88 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
...
+            } catch (IOException e) {
+                logger.warn(() ->
+                    new ParameterizedMessage(
+                        "[{}] failed to clean up unreferenced index folders.", metadata.name()), e);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: add folder names here as well?

Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: also, no need to add a full stop at the end of the log message (same for other messages you've added as well).

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 14 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: > For FS and HDFS a recursive/folder delete will still have to go through all the directories and list all the files and the delete one by one.

I'm not sure about file systems in general, but for HDFS at least, doing a recursive delete on the folder results in a single RPC call to the namenode, whereas the file-by-file delete does many many sequential RPC calls, each with significant latency.

I think we should provide folder deletion methods at the BlobContainer level so that each  type can have an efficient implementation.

Let's create a separate predecessor PR for that.

**Review by ywelsch — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 14 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Right .. I underestimated HDFS there, my bad -> on it with the predecessor PR.

> perhaps we should test for this in AbstractThirdPartyRepositoryTestCase to check that all implementations guarantee this behavior

Sounds good, I'll add that test in the next PR :)

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java (hunk 11 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: > How about af47bb8 ?

I like this better.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 14 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I opened https://github.com/elastic/elasticsearch/pull/43281 now that has custom (and optimized) delete calls for all the implementations individually :)

**Comment by original-brownbear** [comment]
@ywelsch I merged in `master` including the container `delete` method from #43281 now and it simplified away the discussion points around directory deletion.
Also, I removed all the full stops I addd to new log/ex. messages, this should be good for another round, thanks!

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Sorry, seems the API change messes with some of the mock repository tests. On it fixing that.

**Comment by original-brownbear** [comment]
Fixed the mock repository based tests -> this should be good for another review :) thanks!

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 16]
```diff
@@ -393,46 +392,68 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
                 logger.warn(() -> new ParameterizedMessage("cannot read snapshot file [{}]", snapshotId), ex);
             }
             // Delete snapshot from the index file, since it is the maintainer of truth of active snapshots
-            final RepositoryData repositoryData;
             final RepositoryData updatedRepositoryData;
+            final BlobContainer indicesBlobContainer = blobStore().blobContainer(basePath().add("indices"));
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: move this to the try block where it's used

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 17]
```diff
@@ -393,46 +392,68 @@ public void deleteSnapshot(SnapshotId snapshotId, long repositoryStateId, Action
...
+                        logger.debug("[{}] Cleaned up stale index [{}]", metadata.name(), indexSnId);
+                    }
+                } catch (IOException e) {
+                    logger.warn(() -> new ParameterizedMessage(
+                        "[{}] index {} is no longer part of any snapshots in the repository, " +
+                            "but failed to clean up their index folders", metadata.name(), indexSnId), e);
+                }
+            }
+        } catch (Exception e) {
+            // TODO: We shouldn't be blanket catching and suppressing all exceptions here and instead handle them safely upstream.
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: add an `assert false` here?

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 18]
```diff
@@ -494,9 +515,13 @@ public SnapshotInfo finalizeSnapshot(final SnapshotId snapshotId,
...
         try {
+            final BlobContainer indicesBlobContainer = blobStore().blobContainer(basePath().add("indices"));
+            final Map<String, BlobContainer> foundIndices = indicesBlobContainer.children();
+            final RepositoryData updatedRepositoryData = getRepositoryData().addSnapshot(snapshotId, blobStoreSnapshot.state(), indices);
+            final var survivingIndices = updatedRepositoryData.getIndices();
             snapshotFormat.write(blobStoreSnapshot, blobContainer(), snapshotId.getUUID());
-            final RepositoryData repositoryData = getRepositoryData();
-            writeIndexGen(repositoryData.addSnapshot(snapshotId, blobStoreSnapshot.state(), indices), repositoryStateId);
+            writeIndexGen(updatedRepositoryData, repositoryStateId);
+            cleanupStaleIndices(foundIndices, survivingIndices);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: as discussed, let's not do the clean-up as part of the snapshotting, but only during deletion.
Instead let's think about how we can add a way for the user to force a clean even if there are no snapshots to be deleted.

File: server/src/test/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java [hunk 19]
```diff
@@ -65,6 +67,23 @@ public void assertConsistentHistoryInLuceneIndex() throws Exception {
...
+    private String skipRepoConsistencyCheckReason;
+
+    @After
+    public void assertRepoConsistency() {
+        if (skipRepoConsistencyCheckReason == null) {
+            client().admin().cluster().prepareGetRepositories().get().repositories()
+                .stream()
+                .map(RepositoryMetaData::name)
+                .forEach(name -> BlobStoreTestUtil.assertRepoConsistency(internalCluster(), name));
+        }
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java]: perhaps log the reason in the else branch here

File: server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java [hunk 20]
```diff
@@ -723,6 +722,7 @@ public boolean clearData(String nodeName) {
     }
 
     public void testRegistrationFailure() {
+        disableRepoConsistencyCheck("This test does not create any data in the repository.");
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/DedicatedClusterSnapshotRestoreIT.java]: no dots at the end of logging messages (same for other occurrences in this PR)

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 21]
```diff
@@ -182,7 +182,8 @@ public void testBasicWorkFlow() throws Exception {
         Client client = client();
 
         logger.info("-->  creating repository");
-        assertAcked(client.admin().cluster().preparePutRepository("test-repo").setType("fs").setSettings(randomRepoSettings()));
+        final String repoName = "test-repo";
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: revert this, not necessary anymore

**Review by ywelsch — CHANGES_REQUESTED** [review]
I've left a few more comments

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 18 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Ok, will revert that. Unfortunately this will also force doing something about the new repo consistency tests (those were reliant on the fact that the last snapshot taken would clean up the repo). I'll think of something there :)

**Comment by original-brownbear** [comment]
thanks @ywelsch I addressed all points. I tackled the consistency check issue by deleting a random snapshot before doing the consistency check in the `After` blocks now. For the repos where I couldn't run a delete because they were some messy "mock" repos that blocked on writes I just turned off the check as well now for the time being since I can't run a delete on those.

**Comment by ywelsch** [comment]
There's a relevant test failure on the PR

**Comment by original-brownbear** [comment]
@ywelsch thanks for pinging, obviously had to re-mute #39852 now that we don't clean up on snapshot :( I'll find another solution for that test in a follow up, it's easy with the infrastructure we have now.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 22]
```diff
@@ -450,6 +450,7 @@ private void cleanupStaleIndices(Map<String, BlobContainer> foundIndices, Map<St
             // TODO: We shouldn't be blanket catching and suppressing all exceptions here and instead handle them safely upstream.
             //       Currently this catch exists as a stop gap solution to tackle unexpected runtime exceptions from implementations
             //       bubbling up and breaking the snapshot functionality.
+            assert false;
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: add exception to message that is shown when assertion breaks?

File: server/src/test/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java [hunk 23]
```diff
@@ -75,7 +75,16 @@ public void assertRepoConsistency() {
...
+                .forEach(name -> {
+                    final List<SnapshotInfo> snapshots = client().admin().cluster().prepareGetSnapshots(name).get().getSnapshots(name);
+                    // Delete one random snapshot to trigger repository cleanup.
+                    if (snapshots.isEmpty() == false) {
+                        client().admin().cluster().prepareDeleteSnapshot(name, randomFrom(snapshots).snapshotId().getName()).get();
+                    }
+                    BlobStoreTestUtil.assertRepoConsistency(internalCluster(), name);
+                });
+        } else {
+            logger.info("--> skipped repo consistency checks because [{}]" ,skipRepoConsistencyCheckReason);
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java]: space after comma

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
thanks @ywelsch !
