### PR TITLE
Use `scheduleUnlessShuttingDown` in `LeaderChecker`

### LINKED ISSUE #108642: [CI] `EsRejectedExecutionException` trips `TransportService` assertion on shutdown
Not directly related to this test I think.

**Build scan:**
https://gradle-enterprise.elastic.co/s/msnan5s2tjtxy/tests/:server:internalClusterTest/org.elasticsearch.action.admin.indices.refresh.RefreshBlocksIT/testRefreshWithBlocks

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.indices.refresh.RefreshBlocksIT.testRefreshWithBlocks" -Dtests.seed=9FA63D5B374741D3 -Dtests.locale=ko -Dtests.timezone=America/Yakutat -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.action.admin.indices.refresh.RefreshBlocksIT#testRefreshWithBlocks`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRefreshWithBlocks'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.action.admin.indices.refresh.RefreshBlocksIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7de16174[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@25db480d[Wrapped task = scheduled check of leader {node_t2}{75sBpKQOQX23F0K31vZEPw}{ZW_aC5qJR-Cmmm45dw8Mpw}{node_t2}{127.0.0.1}{127.0.0.1:13812}{ilmrt}{8.15.0}{7000099-8506000}]] on org.elasticsearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@558b42e4[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 5] (shutdown)

  at __randomizedtesting.SeedInfo.seed([9FA63D5B374741D3]:0)
  at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:988)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:244)
  at org.elasticsearch.transport.TransportService.handleInternalSendException(TransportService.java:979)
  at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:945)
  at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:849)
  at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:759)
  at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler.handleWakeUp(LeaderChecker.java:233)
  at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler$3.run(LeaderChecker.java:387)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at org.elasticsearch.threadpool.ThreadPool$1.run(ThreadPool.java:589)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
  at java.util.concurrent.FutureTask.run(FutureTask.java:317)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7de16174[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@25db480d[Wrapped task = scheduled check of leader {node_t2}{75sBpKQOQX23F0K31vZEPw}{ZW_aC5qJR-Cmmm45dw8Mpw}{node_t2}{127.0.0.1}{127.0.0.1:13812}{ilmrt}{8.15.0}{7000099-8506000}]] on org.elasticsearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@558b42e4[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 5] (shutdown)

    at org.elasticsearch.common.util.concurrent.EsRejectedExecutionHandler.newRejectedException(EsRejectedExecutionHandler.java:51)
    at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:33)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
    at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
    at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
    at org.elasticsearch.threadpool.ThreadPool.schedule(ThreadPool.java:611)
    at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler.scheduleNextWakeUp(LeaderChecker.java:384)
    at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler$1.handleException(LeaderChecker.java:334)
    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1476)
    at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:986)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:244)
    at org.elasticsearch.transport.TransportService.handleInternalSendException(TransportService.java:979)
    at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:945)
    at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:849)
    at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:759)
    at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler.handleWakeUp(LeaderChecker.java:233)
    at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler$3.run(LeaderChecker.java:387)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
    at org.elasticsearch.threadpool.ThreadPool$1.run(ThreadPool.java:589)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
We mustn't throw an exception here, it trips an assertion. Simply giving
up on shutdown is fine.

Closes #108642

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/coordination/LeaderChecker.java [hunk 1]
```diff
@@ -381,17 +381,18 @@ void handleDisconnectedNode(DiscoveryNode discoveryNode) {
...
-                @Override
-                public String toString() {
-                    return "scheduled check of leader " + leader;
-                }
-            }, leaderCheckInterval, EsExecutors.DIRECT_EXECUTOR_SERVICE);
+                    @Override
+                    public String toString() {
+                        return "scheduled check of leader " + leader;
+                    }
+                });
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/cluster/coordination/LeaderChecker.java:395]: We have similar in FollowerChecker, should that be updated as well?

https://github.com/elastic/elasticsearch/blob/d50002853a7d06ac2e07e39169f2a5b5b346673b/server/src/main/java/org/elasticsearch/cluster/coordination/FollowersChecker.java#L404-L416

**Review by idegtiarenko — APPROVED** [review]

**Review by ywangd — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/cluster/coordination/LeaderChecker.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/coordination/LeaderChecker.java:395]: Yeah I don't see why not --> https://github.com/elastic/elasticsearch/pull/108685
