### PR TITLE
Fix readiness edge case on startup

### LINKED ISSUE #136955: [CI] ReadinessClusterIT testReadinessDuringRestartsNormalOrder failing
**Build Scans:**
- [elasticsearch-periodic #11341 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/wg66x2h2ush3m)
- [elasticsearch-periodic-platform-support #11321 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/3kxvdc446w2i6)
- [elasticsearch-periodic-platform-support #11321 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/jxwepw56k7yrm)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.readiness.ReadinessClusterIT.testReadinessDuringRestartsNormalOrder" -Dtests.seed=E5ADFC89329600A5 -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=qu -Dtests.timezone=Antarctica/Rothera -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.readiness.ReadinessClusterIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReadinessDuringRestartsNormalOrder'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Readiness socket should be open
```

**Issue Reasons:**
- [main] 3 consecutive failures in test testReadinessDuringRestartsNormalOrder
- [main] 3 failures in test testReadinessDuringRestartsNormalOrder (1.1% fail rate in 265 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by rjernst**
The readiness service watches for cluster state updates to determine when the node is ready. It must have a master node elected, and file settings must have been applied. Normally those take a little bit of time. However, the readiness services is setup to not even allow starting the tcp listener until after the service start method is called. This occurs in Node.start(), but _after_ the initial node join. If the initial join occurs before `ReadinessService.start()`, and the cluster state already reflects the "ready" state, when `ReadinessService.start()` is called the service will be marked active, but no future cluster state update will reflect a change from "not ready" to "ready", so the tcp listener will never be started.

This commit adjusts the readiness service to keep track of the last state applied. It also moves adding the cluster state listener to when the service is started. Finally, it adjusts the readiness test helpers to use assertBusy instead of a hand rolled backoff loop.

closes #136955

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java [hunk 1]
```diff
@@ -101,12 +104,9 @@ public HttpStats stats() {
...
         threadpool = new TestThreadPool("readiness_service_tests");
-        clusterService = new ClusterService(
-            Settings.EMPTY,
-            new ClusterSettings(Settings.EMPTY, ClusterSettings.BUILT_IN_CLUSTER_SETTINGS),
-            threadpool,
-            null
-        );
+        clusterService = mock(ClusterService.class);
+        when(clusterService.lifecycleState()).thenReturn(Lifecycle.State.STARTED);
+        when(clusterService.state()).thenReturn(emptyState());
```
Comment (prdoyle) [inline server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java:109]: (Aw, a real `ClusterService` replaced with a mock. Oh well, I see why you did it.)

File: test/framework/src/main/java/org/elasticsearch/readiness/MockReadinessService.java [hunk 2]
```diff
@@ -100,25 +104,11 @@ private static boolean socketIsOpen(ReadinessService readinessService) {
...
-        for (int i = 1; i <= RETRIES; ++i) {
-            if (socketIsOpen(readinessService)) {
-                return;
-            }
-            Thread.sleep(RETRY_DELAY_IN_MILLIS * i);
-        }
-
-        throw new AssertionError("Readiness socket should be open");
+    public static void tcpReadinessProbeTrue(ReadinessService readinessService) throws Exception {
+        assertBusy(() -> assertTrue("Readiness socket should be open", socketIsOpen(readinessService)));
```
Comment (prdoyle) [inline test/framework/src/main/java/org/elasticsearch/readiness/MockReadinessService.java:108]: This is equivalent, right? Cool!

File: server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java [hunk 3]
```diff
@@ -307,6 +307,16 @@ public void testFileSettingsUpdateError() throws Exception {
...
     }
 
+    public void testAlreadyReadyWhenStarted() throws Exception {
+        ClusterState readyState = ClusterState.builder(noFileSettingsState()).metadata(emptyReservedStateMetadata).build();
+        when(clusterService.state()).thenReturn(readyState);
+        readinessService.start();
+        assertTrue(readinessService.ready());
+
+        readinessService.stop();
+        readinessService.close();
```
Comment (prdoyle) [inline server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java]: Is it ok that these won't run if the assertion fails? Usually this kind of stuff is done with `@After`.

File: server/src/main/java/org/elasticsearch/readiness/ReadinessService.java [hunk 4]
```diff
@@ -156,6 +159,11 @@ ServerSocketChannel setupSocket() {
     protected void doStart() {
         // Mark the service as active, we'll start the listener when ES is ready
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/readiness/ReadinessService.java]: Is this comment still true?

**Review by prdoyle — APPROVED** [review]
Ok I take your word for it, but I don't entirely follow the PR description.

> If the initial join occurs before start, and the state already reflects the "ready" state, when start is called the service will be marked active, but nothing will ever start the listener.

The listener used to be set up at the end of the `ReadinessService` constructor. I don't understand why that's not sufficient?

File: server/src/main/java/org/elasticsearch/readiness/ReadinessService.java (hunk 4 above)
Comment (rjernst) [reply server/src/main/java/org/elasticsearch/readiness/ReadinessService.java]: Yes this is still true. The listener here is the tcp listener, not the cluster state listener.

**Comment by rjernst** [comment]
> I don't entirely follow the PR description.

>> If the initial join occurs before start, and the state already reflects the "ready" state, when start is called the service will >> be marked active, but nothing will ever start the listener.

> The listener used to be set up at the end of the ReadinessService constructor. I don't understand why that's not sufficient?

There is ambiguous terminology used throughout this class, unfortunately. There are two "listeners", the cluster state listener, and the tcp "listener". The last "start the listener" in my comment was talking about the tcp listener. I'll adjust the description to make this more clear.

File: server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java (hunk 3 above)
Comment (rjernst) [reply server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java]: The test is kind of fubar if the assertion fails, there's no guarantee stop/close won't themselves throw (for example from assertions in transitioning lifecycle states), and the other tests are currently written this way. Yes, they could leak a thread which will cause the class to fail, but the test already failed at this point.

Comment (rjernst) [reply server/src/test/java/org/elasticsearch/readiness/ReadinessServiceTests.java]: I reworked these tests to rely on `@After` for stopping/closing the service, if necessary.

**Comment by prdoyle** [comment]
Backporting to [9.2](https://github.com/elastic/elasticsearch/pull/147746) and [8.19](https://github.com/elastic/elasticsearch/pull/147747). Not doing 9.1 because that branch is dead.
