### PR TITLE
[ML] Don't treat stale FAILED jobs as OPENING in job allocation

### LINKED ISSUE #31794: [ML] After a node restart FAILED and CLOSING jobs count as OPENING
When a node is restarted ML job persistent tasks that were allocated to that node are reallocated to other nodes _unless_ they are in the `FAILED` or `CLOSING` state.  (Prior to 6.2.4 there was another bug that meant we'd reallocate such jobs to other nodes and set them back to `OPENED`.)

However, the logic that limits how many jobs are `OPENING` on a particular node considers all jobs allocated to the node that have stale persistent tasks to be `OPENING`.  This means that if you restart a node that has 2 or more `FAILED` or `CLOSING` jobs then it cannot open any more jobs after being restarted (because we only allow two `OPENING` jobs per node at any time).

To prevent this problem, `FAILED` and `CLOSING` jobs should not be considered `OPENING` if their persistent task status is stale.

/cc @jgowdyelastic

### PR DESCRIPTION
**Pull request by droberts195**
Job persistent tasks with stale allocation IDs used to always be
considered as OPENING jobs in the ML job node allocation decision.
However, FAILED jobs are not relocated to other nodes, which leads
to them blocking up the nodes they failed on after node restarts.
FAILED jobs should not restrict how many other jobs can open on a
node, regardless of whether they are stale or not.

Closes #31794

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java [hunk 1]
```diff
@@ -210,16 +210,27 @@ static void validate(String jobId, MlMetadata mlMetadata) {
...
+                                // have the chance to set job status to OPENING
+                                ++numberOfAllocatingJobs;
+                                jobState = JobState.OPENING;
+                            }
+                        }
                     }
-                    // Don't count FAILED jobs, as they don't consume native memory
-                    if (jobState != JobState.FAILED) {
+                    // Don't count CLOSED or FAILED jobs, as they don't consume native memory
+                    if (jobState != JobState.CLOSED && jobState != JobState.FAILED) {
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java]: You can use `jobState.isAnyOf(JobState.CLOSED, JobState.FAILED) == false`

**Review by davidkyle — APPROVED** [review]
LGTM left a readability suggestion
