### PR TITLE
[ES|QL] Use standard logic for conflicting types in TS

### LINKED ISSUE #141379: When a field has multiple types, and one includes time_series_metric, then original_types is broken
When multiple indexes with the same field name have different types on those fields, and ES|QL is used to query multiple indexes, ES|QL will return those fields as type `unsupported` with all values set to `null`. Kibana likes to keep clean tables, so it sends `drop_null_columns` along with the query. This removes the entire column of nulls. Users get confused. To help reduce confusion, ES|QL returns an extra header called `all_columns` which includes the missing column, and also lists the `original_types` for the column switched to `unsupported` so that Kibana can explain to the users why that column has `null` values.

If `drop_null_columns` is not sent, the original columns will have the unsupported type, but will also include the `original_types` field:

```
    {
      "name": "metric.value",
      "type": "unsupported",
      "original_types": [
        "double",
        "keyword"
      ],
      "suggested_cast": "keyword"
    }
```

Whether `drop_null_columns` is used or not, this `original_types` information is useful for users to make sense of what is going on. In Kibana, there are warning icons with additional information provided:

Kibana fields with warnings

However, when the indexes in question have `index.mode:time_series` and one of the field mappings includes `time_series_metric`, then the `original_types` is not provided, and Kibana cannot help the users, leading to much confusion on the part of the user. In Kibana there are no warnings on the fields:

Kibana fields missing warnings

### Reproduction

```
PUT /metrics-counter
{
 "settings": {
   "index.mode": "time_series",
   "index.routing_path": [ "metric.name" ]
 },
 "mappings": {
   "properties": {
     "@timestamp": { "type": "date" },
     "metric.name": {
       "type": "keyword",
       "time_series_dimension": true
     },
     "metric.value": {
       "type": "double",
       "time_series_metric": "counter"
     }
   }
 }
}


PUT /metrics-gauge
{
 "settings": {
   "index.mode": "time_series",
   "index.routing_path": [ "metric.name" ]
 },
 "mappings": {
   "properties": {
     "@timestamp": { "type": "date" },
     "metric.name": {
       "type": "keyword",
       "time_series_dimension": true
     },
     "metric.value": {
       "type": "double",
       "time_series_metric": "gauge"
     }
   }
 }
}


PUT /metrics-keyword
{
 "settings": {
   "index.mode": "time_series",
   "index.routing_path": [ "metric.name" ]
 },
 "mappings": {
   "properties": {
     "@timestamp": { "type": "date" },
     "metric.name": {
       "type": "keyword",
       "time_series_dimension": true
     },
     "metric.value": {
       "type": "keyword"
     }
   }
 }
}


POST /metrics-counter/_doc
{
 "@timestamp": "2026-01-20T11:00:00Z",
 "metric.name": "network_packets_total",
 "metric.value": 50
}


POST /metrics-counter/_doc
{
 "@timestamp": "2026-01-20T11:05:00Z",
 "metric.name": "network_packets_total",
 "metric.value": 100
}


POST /metrics-gauge/_doc
{
 "@timestamp": "2026-01-20T10:00:00Z",
 "metric.name": "cpu_usage_percentage",
 "metric.value": 50
}


POST /metrics-gauge/_doc
{
 "@timestamp": "2026-01-20T10:05:00Z",
 "metric.name": "cpu_usage_percentage",
 "metric.value": 100
}


POST /metrics-keyword/_doc
{
 "@timestamp": "2026-01-20T10:00:00Z",
 "metric.name": "cpu_usage_percentage",
 "metric.value": "a"
}


POST /metrics-keyword/_doc
{
 "@timestamp": "2026-01-20T10:05:00Z",
 "metric.name": "cpu_usage_percentage",
 "metric.value": "b"
}

// With drop_null_columns, the metric.value column is removed, and all_columns is missing original_types

POST /_query?drop_null_columns
{
    "query": """
        FROM metrics-gauge, metrics-keyword"""
}

// Without drop_null_columns, the metric-value column is all nulls, and original_types is missing

POST /_query
{
    "query": """
        FROM metrics-gauge, metrics-keyword"""
}

// The above queries mixed a time_series_metric with a normal keyword, but this problem also occurs between two time_series_metric fields

POST /_query?drop_null_columns
{
    "query": """
        FROM metrics-gauge, metrics-counter"""
}

// Also happens with wildcards

POST /_query?drop_null_columns
{
    "query": "FROM metrics-*"
}
```

If we change the index settings to not have `index-mode:time_series` or we remove the `time_series_metric` from the fields, then the missing `original_types` come back.

### PR DESCRIPTION
**Pull request by limotova**
Previously we were checking if the metric types were not matching in the
IndexResolver, but this was causing us to lose the original types and
suggested cast information. The regular path for handling
InvalidMappedFields keeps this information and is able to catch types
mapped to the same type but with different metric types (i.e. double vs
counter_double) so this commit removes the metrics check in the
IndexResolver and allows it to fall into the later conflicting types
check.

Resolves #141379

### CODE REVIEW

**Review by kkrik-es — APPROVED** [review]

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/FieldExtractorTestCase.java [hunk 1]
```diff
@@ -1340,11 +1340,127 @@ public void testOneNestedField_AndSameNameSupportedField_TwoIndices() throws IOE
...
+            List.of(unsupportedColumnInfo("metric.value", "counter_double", "double")),
+            List.of(matchesList().item(null), matchesList().item(null))
+        );
+        result = runEsql("TS metrics-counter,metrics-keyword | KEEP metric.value");
+        assertResultMap(
+            result,
+            List.of(unsupportedColumnInfo("metric.value", "counter_double", "keyword")),
+            List.of(matchesList().item(null), matchesList().item(null))
+        );
+
```
Comment (kkrik-es) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/FieldExtractorTestCase.java:1471]: Can we also add a test where a field is a dimension and a gauge, both long? I wonder if we catch this.. if we don't, we can follow up separately.

Comment (limotova) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/FieldExtractorTestCase.java:1471]: Added a test for it, it looks like we do cover this

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/IndexResolver.java [hunk 2]
```diff
@@ -446,9 +446,6 @@ private static EsField createField(
         EsField.TimeSeriesFieldType timeSeriesFieldType = EsField.TimeSeriesFieldType.fromIndexFieldCapabilities(first);
         if (rest.isEmpty() == false) {
             for (IndexFieldCapabilities fc : rest) {
-                if (first.metricType() != fc.metricType()) {
-                    return conflictingMetricTypes(name, fullName, fieldsInfo.caps);
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/IndexResolver.java:450]: We no longer call this method, so it can be removed.
