### PR TITLE
SQL: fix NPE on ambiguous GROUP BY

### LINKED ISSUE #46396: SQL: NPE when using the same alias for a projection and an aggregate and GROUPed BY
`SELECT gender AS g, SUM(salary) AS g FROM test_emp GROUP BY g`

Notice the alias name (which is the same) which, used in the `GROUP BY` will trigger a NPE:

```
[elasticsearch] java.lang.NullPointerException: null
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.analyzer.Analyzer$ResolveOrdinalInOrderByAndGroupBy.findOrdinal(Analyzer.java:593) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.analyzer.Analyzer$ResolveOrdinalInOrderByAndGroupBy.rule(Analyzer.java:558) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.analyzer.Analyzer$AnalyzeRule.lambda$apply$0(Analyzer.java:1287) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.analyzer.Analyzer$AnalyzeRule.apply(Analyzer.java:1287) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.analyzer.Analyzer$AnalyzeRule.apply(Analyzer.java:1281) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.analyzer.Analyzer.analyze(Analyzer.java:132) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.session.SqlSession.lambda$analyzedPlan$0(SqlSession.java:110) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:144) ~[?:?]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:277) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:89) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:144) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:138) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:88) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:101) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:97) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by bpintea**
This PR fixes a NPE occurring when an ambiguous alias is used for grouping.

Continues #56489.
Fixes #46396.

Co-authored-by: Nikita Verkhovin <verkhovin13@gmail.com>

### CODE REVIEW

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expressions.java [hunk 1]
```diff
@@ -164,14 +163,15 @@ public static boolean equalsAsAttribute(Expression left, Expression right) {
         return true;
     }
 
-    public static AttributeMap<Expression> aliases(List<? extends NamedExpression> named) {
-        Map<Attribute, Expression> aliasMap = new LinkedHashMap<>();
+    public static List<Tuple<Attribute, Expression>> aliases(List<? extends NamedExpression> named) {
```
Comment (bpintea) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expressions.java:166]: > Could you please replace this with a Tuple<Attribute, Expression>?

`AttributeAlias` replaced with `Tuple<Attribute, Expression>`?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 2]
```diff
@@ -192,16 +192,21 @@ private static Attribute resolveAgainstList(UnresolvedAttribute u, Collection<At
         }
 
         if (matches.size() == 1) {
-            return handleSpecialFields(u, matches.get(0), allowCompound);
+            // only add the location if the match is univocal; b/c otherwise adding the location will overwrite any preexisting one
+            return handleSpecialFields(u, matches.get(0).withLocation(u.source()), allowCompound);
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:196]: > Why removing it from here and adding it only if matches.size() == 1?

Attribute#`withLocation()` will "overwrite" any pre-existing location, which is not desirable if the existing locations need to be kept in order to be reported in an error message.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 3]
```diff
@@ -192,16 +192,21 @@ private static Attribute resolveAgainstList(UnresolvedAttribute u, Collection<At
...
-                 .map(a -> "\"" + a.qualifier() + "\".\"" + a.name() + "\"")
-                 .sorted()
-                 .collect(toList())
-                );
+        List<String> refs = matches.stream()
+            .sorted((a, b) -> {
+                int lineDiff = a.sourceLocation().getLineNumber() - b.sourceLocation().getLineNumber();
+                int colDiff = a.sourceLocation().getColumnNumber() - b.sourceLocation().getColumnNumber();
+                return lineDiff != 0 ? lineDiff : (colDiff != 0 ? colDiff : a.qualifiedName().compareTo(b.qualifiedName()));
+            })
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:204]: > Please remove the comparison implementation from here and use a custom comparator to sort the ambiguous attributes.

Implementations of `Comparable` removed.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 4]
```diff
@@ -327,22 +332,31 @@ else if (plan instanceof Aggregate) {
...
                                 changed = true;
-                                // use the matched expression (not its attribute)
-                                grouping = resolved.get(maybeResolved);
+                                if (maybeResolved.resolved()) {
+                                    grouping = resolvedAliases.stream()
+                                        .filter(t -> t.v1().equals(maybeResolved))
+                                        // use the matched expression (not its attribute)
+                                        .map(Tuple::v2)
+                                        .findAny()
+                                        .get(); // there should always be exactly one match
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:356]: > Imho, it would be better to use a for loop to increase readability.

The stream construction seems a bit more compact and readable IMO and inline with other usages (like the current Analyzer#`resolveAgainstList()`, but I can still change it if desired.

**Review by matriv — APPROVED** [review]
LGTM
