### PR TITLE
Fix bug in compressed binary doc values bulk decoding.

### LINKED ISSUE #138750: ArrayIndexOutOfBoundsException in ES819TSDBDocValuesProducer
### Elasticsearch Version

Current snapshot / main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacBook M1 Pro on macOS 15.7.2

### Problem Description

Trying to load 2 million `exponential_histogram`s via ES|QL crashed in the blockloader for the `BinaryDocValues` used within that field type.
The query partially fails with an `ArrayIndexOutOfBoundsException`:

```
java.lang.ArrayIndexOutOfBoundsException: Index 256000 out of bounds for length 1025
	at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.index.codec.tsdb.es819.ES819TSDBDocValuesProducer$BinaryDecoder.decodeBulk(ES819TSDBDocValuesProducer.java:635)
	at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.index.codec.tsdb.es819.ES819TSDBDocValuesProducer$5.tryRead(ES819TSDBDocValuesProducer.java:414)
	at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.index.mapper.blockloader.docvalues.BytesRefsFromBinaryBlockLoader$BytesRefsFromBinary.read(BytesRefsFromBinaryBlockLoader.java:59)
	at org.elasticsearch.xpack.exponentialhistogram.ExponentialHistogramFieldMapper$ExponentialHistogramFieldType$2$1.read(ExponentialHistogramFieldMapper.java:412)
	at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.loadFromSingleLeaf(ValuesFromSingleReader.java:115)
	at org.elasticsearch.compute.lucene.read.ValuesFromSingleReader.load(ValuesFromSingleReader.java:58)
	at org.elasticsearch.compute.lucene.read.ValuesReader.next(ValuesReader.java:38)
	at org.elasticsearch.compute.lucene.read.ValuesReader.next(ValuesReader.java:18)
	at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator.next(AbstractPageMappingToIteratorOperator.java:345)
	at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$AppendBlocksIterator.next(AbstractPageMappingToIteratorOperator.java:321)
	at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator.next(AbstractPageMappingToIteratorOperator.java:190)
	at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator$RuntimeTrackingIterator.next(AbstractPageMappingToIteratorOperator.java:175)
	at org.elasticsearch.compute.operator.AbstractPageMappingToIteratorOperator.getOutput(AbstractPageMappingToIteratorOperator.java:149)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:283)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:191)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:431)
	at org.elasticsearch.server@9.3.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
	... 7 more
```

### Steps to Reproduce

 * Start ES on [this commit](https://github.com/JonasKunz/elasticsearch/commit/9161e7dc27fe28a485ef8b36dcdaa7cfb06ff0c6) via `./gradlew run run -Dtests.es.xpack.security.enabled=false -Drun.license_type=trial -Dtests.heap.size=4G -Dtests.jvm.argline="-da -dsa"`
  That commit enhances the built-in OTLP endpoint to ingest metrics using the new `exponential_histogram` field type
  * Checkout [this repo](https://github.com/JonasKunz/es-otlp-error-repro/tree/main) and run the [data-generator](https://github.com/JonasKunz/es-otlp-error-repro/blob/main/src/main/java/co/elastic/example/OtlpFakeHistogramGenerator.java). That will ingest two million documents with `exponential_histogram`s to the locally running ES instance
  * Run the following ES|QL query: `FROM metrics-* | STATS AVG(my_histogram)`. That will fail with an `ArrayIndexOutOfBoundsException`.
     I did this using a local Kibana snapshot instance running in Docker.

For me, this approach has reliably reproduced the problem. The exact line number of the exception seems to vary though.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by martijnvg**
Reuse firstBlockId as blockId on first iteration.

Closes #138750

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesFormatTests.java [hunk 1]
```diff
@@ -1197,6 +1197,52 @@ public void testOptionalColumnAtATimeReaderReadAsInt() throws Exception {
...
+            }
+            iw.commit();
+            var factory = TestBlock.factory();
+            try (var reader = DirectoryReader.open(iw)) {
+                for (var leaf : reader.leaves()) {
+                    int maxDoc = leaf.reader().maxDoc();
+                    var binaryFixedDV = getDenseBinaryValues(leaf.reader(), binaryFieldOne);
+                    // Randomize start doc, starting from a docid that is part of later blocks triggers:
+                    // https://github.com/elastic/elasticsearch/issues/138750
+                    var docs = TestBlock.docs(IntStream.range(between(0, maxDoc - 1), maxDoc).toArray());
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesFormatTests.java:1233]: This is important to trigger to bug

**Review by felixbarny — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesProducer.java [hunk 2]
```diff
@@ -617,7 +617,7 @@ void decodeBulk(int numBlocks, int firstDoc, int count, BlockLoader.SingletonByt
             byte[] bytes = new byte[bufferSize];
 
             while (remainingCount > 0) {
-                long blockId = findAndUpdateBlockByScanning(nextDoc);
+                long blockId = remainingCount == count ? firstBlockId : findAndUpdateBlockByScanning(nextDoc);
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesProducer.java:620]: nit: maybe adjust the loop so we don't need firstBlockId or its special case.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks MVG!

File: server/src/main/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesProducer.java (hunk 2 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/codec/tsdb/es819/ES819TSDBDocValuesProducer.java:620]: Makes sense, however i needed to change more code than I liked too. I think this should be done in a follow up change.

**Review by JonasKunz — APPROVED** [review]
