### PR TITLE
CLI tools: write errors to stderr instead of stdout

### LINKED ISSUE #43260: CLI tools output errors on stdout
**Elasticsearch version** (`bin/elasticsearch --version`): `Version: 7.1.1, Build: default/deb/7a013de/2019-05-23T14:04:00.380842Z, JVM: 12.0.1`

**Plugins installed**: none

**JVM version** (`java -version`):
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): `Linux earth-elk 4.15.0-1033-gcp #35-Ubuntu SMP Fri May 17 13:27:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
When running `elasticsearch-setup-passwords` twice, the error is output on stdout.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `echo y | bin/elasticsearch-setup-passwords auto`
 2. `bin/elasticsearch-setup-passwords auto 2>/dev/null`

You can still see the error message `.

### PR DESCRIPTION
**Pull request by williamrandolph**
Most of our CLI tools use the `Terminal` class, which previously did not provide methods for writing to standard output. When all output goes to standard out, there are two basic problems. First, errors and warnings are "swallowed" in pipelines, making it hard for a user to know when something's gone wrong. Second, errors and warnings are intermingled with legitimate output, making it difficult to pass the results of interactive scripts to other tools.

I considered adding a new `ERROR` verbosity level, which would, like `SILENT`, always be printed, but would be printed to standard error instead of standard output. But this didn't seem to fit the existing usages in, for example, `SetupPasswordTool`, where the `--verbose` flag controls whether or not stack traces are printed when errors happen. (If you think the "`ERROR` verbosity level" approach is better than the one I chose, please let me know.)

Instead, I added a second set of print commands to Terminal for printing to standard error, with `errorPrint` corresponding to `print` and `errorPrintln` corresponding to `println`. This leaves it to developers to decide which output should go where.

One little trick that I hope people will appreciate is that usage is printed to standard output when it's correctly requested (e.g., `bin/elasticsearch-keystore --help`) but goes to standard error when a command is invoked incorrectly (e.g. `bin/elasticsearch-keystore list-with-a-typo | sort`).

Fixes #43260

### CODE REVIEW

**Comment by williamrandolph** [comment]
@elasticmachine Please update branch.

File: distribution/tools/keystore-cli/src/main/java/org/elasticsearch/common/settings/AddFileKeyStoreCommand.java [hunk 1]
```diff
@@ -55,8 +55,8 @@
     protected void execute(Terminal terminal, OptionSet options, Environment env) throws Exception {
         KeyStoreWrapper keystore = KeyStoreWrapper.load(env.configFile());
         if (keystore == null) {
-            if (options.has(forceOption) == false &&
-                terminal.promptYesNo("The elasticsearch keystore does not exist. Do you want to create it?", false) == false) {
+            if (!options.has(forceOption) &&
```
Comment (rjernst) [inline distribution/tools/keystore-cli/src/main/java/org/elasticsearch/common/settings/AddFileKeyStoreCommand.java]: We use `== false` instead of `!` because the former is much easier to visually notice when skimming through code. Please keep these as they were. :)

File: server/src/test/java/org/elasticsearch/cli/TerminalTests.java [hunk 2]
```diff
@@ -41,6 +41,8 @@ public void testVerbosity() throws Exception {
         assertPrinted(terminal, Terminal.Verbosity.VERBOSE, "text");
     }
 
+    // TODO: test error verbosity
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/cli/TerminalTests.java]: Can we add these new tests described here? I see several existing tests modified, but it would be good to have some direct coverage of the new functionality.

**Review by rjernst — COMMENTED** [review]
Looks good, 2 minor comments

File: server/src/test/java/org/elasticsearch/cli/TerminalTests.java (hunk 2 above)
Comment (williamrandolph) [reply server/src/test/java/org/elasticsearch/cli/TerminalTests.java]: Of course - thanks for catching that.
