### PR TITLE
Change the handling of passthrough dimenensions

### LINKED ISSUE #125156: Downsampling fails if source index contains fields of type passthrough
Downsampling fails if source index contains fields of type passthrough and these fields are configured with `time_series_dimension` to `true`.  There are two problems that occur in this case:

- The target index that the downsample api tries to creates is with a flattened like mapping (fields with dots) and so the type of the object field is never specified (1).
- The downsample api detects all fields with `time_series_dimension` set to `true` as dimension fields. This isn't true as passthrough fields are just container fields.

1: This is a field mapping that the downsample tries to create:

```
        "metrics.process.memory.usage": {
            "type": "aggregate_metric_double",
            "metrics": [
                "max",
                "min",
                "value_count",
                "sum"
            ],
            "default_metric": "max",
            "time_series_metric": "gauge"
        },
``` 

The `metrics.` is an object field here and but in the mapping that this fields get merged with it is a passthrough object field.

### PR DESCRIPTION
**Pull request by gmarouli**
When downsampling an index that has a mapping with [passthrough dimensions](https://www.elastic.co/docs/reference/elasticsearch/mapping-reference/passthrough#passthrough-dimensions) the downsampling process identifies the wrapper object as a dimension and it fails when it tried to retrieve the type.

We did some prework to establish a shared framework in the `internalClusterTest`. For now it only includes setting up time series data stream helpers and a limited assertion helper for dimensions and metrics. This allows us to setup an `internalClusterTest` that captures this issue during downsampling in https://github.com/elastic/elasticsearch/issues/125156.

To fix this we refine the check that determines if a field is dimension, to skip wrapper field. 

Fixes https://github.com/elastic/elasticsearch/issues/125156.

### CODE REVIEW

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DataStreamLifecycleDownsampleDisruptionIT.java [hunk 1]
```diff
@@ -81,9 +68,9 @@ public void testDataStreamLifecycleDownsampleRollingRestart() throws Exception {
 
         // before we rollover we update the index template to remove the start/end time boundaries (they're there just to ease with
         // testing so DSL doesn't have to wait for the end_time to lapse)
-        putTSDBIndexTemplate(client(), dataStreamName, null, null, lifecycle);
-        client().execute(RolloverAction.INSTANCE, new RolloverRequest(dataStreamName, null)).actionGet();
-        String sourceIndex = getBackingIndices(client(), dataStreamName).get(0);
+        putTSDBIndexTemplate(dataStreamName, null, null, lifecycle);
+        safeGet(client().execute(RolloverAction.INSTANCE, new RolloverRequest(dataStreamName, null)));
+        String sourceIndex = getDataStreamBackingIndexNames(dataStreamName).get(0);
```
Comment (gmarouli) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DataStreamLifecycleDownsampleDisruptionIT.java:73]: `ESIntegTestCase` provides a helper method to retrieve the data stream's backing indices, so I replaces the one we had define in the driver class.

Comment (kkrik-es) [reply x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DataStreamLifecycleDownsampleDisruptionIT.java:73]: Nice.

**Review by kkrik-es — APPROVED** [review]
Nice refactoring, thanks!
