### PR TITLE
Fix snapshot version in `createSnapshotLegacy`

### LINKED ISSUE #86889: AssertionError (lost uuid) in mixed cluster test
This test run failed due to a tripped assertion in one of the 7.0.1 nodes (#86887) but then one of the 7.17.4 nodes also fell over for apparently-unrelated reasons:

```
[2022-05-18T12:15:22,564][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.0.1-0] fatal error in thread [elasticsearch[v7.0.1-0][snapshot][T#3]], exiting
java.lang.AssertionError: lost uuid JCGi3zjyQgytAyClMFs3Gg
        at org.elasticsearch.repositories.RepositoryData.snapshotsToXContent(RepositoryData.java:693) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.repositories.RepositoryData.snapshotsToXContent(RepositoryData.java:648) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$65(BlobStoreRepository.java:2323) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeToPath(FsBlobContainer.java:274) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeBlob(FsBlobContainer.java:253) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeAtomic(BlobStoreRepository.java:2636) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$66(BlobStoreRepository.java:2321) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListenerDirectly(ListenableFuture.java:113) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:100) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:131) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:139) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:52) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$63(BlobStoreRepository.java:2300) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
        Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
                at org.elasticsearch.xcontent.XContentBuilder.close(XContentBuilder.java:1131) ~[elasticsearch-x-content-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$65(BlobStoreRepository.java:2322) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeToPath(FsBlobContainer.java:274) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeBlob(FsBlobContainer.java:253) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeAtomic(BlobStoreRepository.java:2636) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$66(BlobStoreRepository.java:2321) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListenerDirectly(ListenableFuture.java:113) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:100) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:131) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:139) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:52) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:29) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$writeIndexGen$63(BlobStoreRepository.java:2300) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
        Caused by: java.io.IOException: Unclosed object or array found
                at org.elasticsearch.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:456) ~[elasticsearch-x-content-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                at org.elasticsearch.xcontent.XContentBuilder.close(XContentBuilder.java:1129) ~[elasticsearch-x-content-7.17.4-SNAPSHOT.jar:7.17.4-SNAPSHOT]
                ... 19 more
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/hhxbspduxkiio/tests/:qa:mixed-cluster:v7.0.1%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=search.aggregation%2F230_composite%2FTerms%20source%20from%20sorted%7D

**Reproduction line:**
`./gradlew ':qa:mixed-cluster:v7.0.1#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/230_composite/Terms source from sorted}" -Dtests.seed=12FB47E08AFF8223 -Dtests.bwc=true -Dtests.locale=el-CY -Dtests.timezone=Atlantic/Stanley -Druntime.java=8`

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsearch.aggregation/230_composite/Terms%20source%20from%20sorted%7D

### PR DESCRIPTION
**Pull request by DaveCTurner**
We shouldn't use `Version#CURRENT` for the snapshot version anywhere,
but especially not on the legacy path.

Closes #86889

### CODE REVIEW

**Comment by DaveCTurner** [comment]
NB this is pretty much all just whitespace noise, the real change is tiny.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -273,100 +273,96 @@ public void createSnapshotLegacy(final CreateSnapshotRequest request, final Acti
...
         Repository repository = repositoriesService.repository(request.repository());
         final Map<String, Object> userMeta = repository.adaptUserMetadata(request.userMetadata());
-        clusterService.submitStateUpdateTask(
-            "create_snapshot [" + snapshotName + ']',
-            new ClusterStateUpdateTask(request.masterNodeTimeout()) {
-
-                private List<String> indices;
-
-                private SnapshotsInProgress.Entry newEntry;
+        repository.executeConsistentStateUpdate(repositoryData -> new ClusterStateUpdateTask(request.masterNodeTimeout()) {
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:276]: Should we pass this `repositoryData` down to `beginSnapshot` to avoid having to fetch it again later and potentially better consistency?

**Review by ywangd — APPROVED** [review]
LGTM

I have one non-blocking question. The bug fix is valid with or without it.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:276]: It'll (almost certainly) be read from cache there so the fetching is nbd. I'm not 100% sure about the consistency argument, `beginSnapshot` dispatches back to `SNAPSHOT` so are we sure nothing might change it in the meantime? I'm inclined not to change things in this area without a strong motivation at least.

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:276]: > I'm not 100% sure about the consistency argument, beginSnapshot dispatches back to SNAPSHOT so are we sure nothing might change it in the meantime?

Thanks for explaining. Now I noticed that the legacy `initializingSnapshots` behaviour which leads to thread dispatching. You are right that we don't want to just reuse the `repositoryData`. Also agree to not change things unless absolutely necessary.
