### PR TITLE
Fix cluster bootstrap warning for single-node discovery

### LINKED ISSUE #96874: Cluster bootstrap warning incorrectly emitted for `discovery.type: single-node`
In #86101 we added a warning if bootstrapping was incorrectly configured (and in #92744 we changed it to be emitted every 12h). The logic introduced doesn't take account of `discovery.type: single-node`, so explicitly-single-node clusters will always emit this warning even though they are correctly configured.

Relates https://github.com/elastic/elasticsearch/issues/58393.

### PR DESCRIPTION
**Pull request by NEUpanning**
Suppresses periodic warning log about cluster bootstrapping configuration when
using single-node discovery.

Closes #96874

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/coordination/ClusterBootstrapService.java [hunk 1]
```diff
@@ -76,6 +77,7 @@ public ClusterBootstrapService(
         BooleanSupplier isBootstrappedSupplier,
         Consumer<VotingConfiguration> votingConfigurationConsumer
     ) {
+        singleNodeDiscovery = DiscoveryModule.isSingleNodeDiscovery(settings);
         if (DiscoveryModule.isSingleNodeDiscovery(settings)) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/ClusterBootstrapService.java:81]:
```suggestion
        if (singleNodeDiscovery) {
```

File: server/src/main/java/org/elasticsearch/cluster/coordination/ClusterBootstrapService.java [hunk 2]
```diff
@@ -126,6 +128,8 @@ void logBootstrapState(Metadata metadata) {
             final var clusterUUID = metadata.clusterUUID();
             if (bootstrapRequirements.isEmpty()) {
                 logger.info("this node is locked into cluster UUID [{}] and will not attempt further cluster bootstrapping", clusterUUID);
+            } else if (singleNodeDiscovery) {
+                logger.info("this node is locked into single-node cluster UUID [{}]", clusterUUID);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/ClusterBootstrapService.java:132]: I think we could reasonably have the same message in both cases:

```suggestion
            if (singleNodeDiscovery || bootstrapRequirements.isEmpty()) {
                logger.info("this node is locked into cluster UUID [{}] and will not attempt further cluster bootstrapping", clusterUUID);
```

At least we should include the `and will not attempt further cluster bootstrapping` bit in both messages.

File: server/src/test/java/org/elasticsearch/cluster/coordination/ClusterBootstrapServiceTests.java [hunk 3]
```diff
@@ -735,6 +735,27 @@ public void testBootstrapStateLogging() {
...
+                Settings.builder().put(DiscoveryModule.DISCOVERY_TYPE_SETTING.getKey(), DiscoveryModule.SINGLE_NODE_DISCOVERY_TYPE).build(),
+                transportService,
+                Collections::emptyList,
+                () -> false,
+                vc -> {
+                    throw new AssertionError("should not be called");
+                }
+            ).logBootstrapState(Metadata.builder().clusterUUID("test-uuid").clusterUUIDCommitted(true).build());
+
+            mockAppender.assertAllExpectationsMatched();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/coordination/ClusterBootstrapServiceTests.java:758]: This does not verify that the bug is fixed, i.e. that the message is only emitted once. It would be sufficient to verify that `deterministicTaskQueue.runAllTasks()` completes. You'll need to do that in a separate test case, or at least earlier in this one, because there's no way to shut down the repeated logging from the badly-configured `ClusterBootstrapService` instance.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Review by DaveCTurner — APPROVED** [review]
LGTM, thanks for your contribution @NEUpanning!

**Comment by NEUpanning** [comment]
Thanks, @DaveCTurner for reviewing and approving this.
