### PR TITLE
[ML] Fix minor race condition in dataframe analytics _stop

### LINKED ISSUE #53007: RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll failures
A failure from today:

https://gradle-enterprise.elastic.co/s/5bmqki2fxth7i

Reproduce lines:
```
REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll" \
  -Dtests.seed=AEF305B74CA6788B \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Europe/Istanbul \
  -Dcompiler.java=13

REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll" \
  -Dtests.seed=AEF305B74CA6788B \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Europe/Istanbul \
  -Dcompiler.java=13
```

Failure stack trace from one of the tests suggests a problem with MultiSearch query performed as part of `TransportGetDataFrameAnalyticsStatsAction` action:
```
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testStopOutlierDetectionWithEnoughDocumentsToScroll FAILED
    org.elasticsearch.ElasticsearchException: all shards failed
        at __randomizedtesting.SeedInfo.seed([AEF305B74CA6788B:3E02F093CBFBFFB1]:0)
        at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:55)
        at org.elasticsearch.xpack.ml.action.TransportGetDataFrameAnalyticsStatsAction.lambda$searchStats$8(TransportGetDataFrameAnalyticsStatsAction.java:201)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:97)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:144)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:138)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:179)
        at org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:165)
        at org.elasticsearch.action.search.TransportMultiSearchAction$1.onFailure(TransportMultiSearchAction.java:158)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$1(NodeClient.java:97)
        at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:153)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:568)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:548)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:308)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:577)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:388)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:244)
        at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
        at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:406)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1067)
        at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:242)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:177)
        at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:240)
        at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:232)
        at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:136)
        at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102)
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:227)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        Failed to execute phase [query], all shards failed
            at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:548)
            ... 49 more
```

### PR DESCRIPTION
**Pull request by benwtrent**
Tests have been periodically failing due to a race condition on checking a recently `STOPPED` task's state. The `.ml-state` index is not created until the task has already been transitioned to `STARTED`. This allows the `_start` API call to return. But, if a user (or test) immediately attempts to `_stop` that job, the job could stop and the task removed BEFORE the `.ml-state|stats` indices are created/updated.

This change moves towards the task cleaning up itself in its main execution thread. `stop` flips the flag of the task to `isStopping` and now we check `isStopping` at every necessary method. Allowing the task to gracefully stop.

closes #53007

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java [hunk 1]
```diff
@@ -572,7 +582,10 @@ protected AllocatedPersistentTask createTask(
             String id = params.getId();
 
             List<String> unavailableIndices =
-                verifyIndicesPrimaryShardsAreActive(clusterState, resolver, AnomalyDetectorsIndex.configIndexName());
+                verifyIndicesPrimaryShardsAreActive(clusterState,
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Should we wait the same way for `.ml-state*`?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java [hunk 2]
```diff
@@ -572,7 +582,10 @@ protected AllocatedPersistentTask createTask(
...
+                    resolver,
+                    AnomalyDetectorsIndex.configIndexName(),
+                    MlStatsIndex.indexPattern());
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: I feel like I'm missing something obvious here. The `.ml-stats` index is created by [ DataFrameAnalyticsManager.execute](https://github.com/elastic/elasticsearch/blob/dd331935b31f83024633a6ec84da5be946b4e7d1/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java#L114) called from `TaskExecutor.nodeOperation`.   But `TaskExecutor.getAssignment` which runs first is expecting the index to exist and as far as I can tell it hasn't been created yet. Could that be because of the leniency in `verifyIndicesPrimaryShardsAreActive` 


`resolver.concreteIndexNames(clusterState, IndicesOptions.lenientExpandOpen(), indexNames);`

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: Yes, arguably we could prevent assignment if the required indices exist but are not usable at the time an assignment decision is made.  But the changes currently in this PR will not fix #53007.

> we could prevent assignment if the required indices exist but are not usable at the time an assignment decision is made

A side effect of this would be that the start datafeed API would fail in some cases where if it had waited a fraction of a second it would have succeeded.  I am not sure that's a good idea.  It certainly deserves a discussion.

Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: For Transforms we get the stats directly from the task if it is running else the index is searched. Could we not do the same here? In which case `.ml-stats` would not be touched until the DFA has finished.

I think for anomaly detection we created most of the indices on node start (apart from the results index) which is one way of solving the problem but is heavy handed and still required checks that the index was active.

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: There is a scenario y'all are not thinking about. 

What if the previously created index is just not available due to the nodes being down?

Its fine being lenient in `verifyIndicesPrimaryShardsAreActive` if the index does not exist at all. This is because we will create it. 

But, if it already exists and its primary shard is not assigned, that is a bigger issue. One warranting the task not being assigned to a node.

> For Transforms we get the stats directly from the task if it is running else the index is searched. Could we not do the same here?

We could. I can look into that. 

Regardless of waiting for the indices to be created before returning from `_start`, I think the changes in `verifyIndicesPrimaryShardsAreActive` are necessary and good.

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: > What if the previously created index is just not available due to the nodes being down?

This is what I was referring to in https://github.com/elastic/elasticsearch/pull/53029#discussion_r386943414

So it solves one problem but creates another:

> A side effect of this would be that the start datafeed API would fail in some cases where if it had waited a fraction of a second it would have succeeded. I am not sure that's a good idea. It certainly deserves a discussion.

I think if we do this we should do it consistently for anomaly detection and data frame analytics, so that both or neither assign tasks when the necessary indices exist but are not available.

@dimitris-athanasiou I think you originally added some of these checks.  Do you have any extra insights?

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: > A side effect of this would be that the start datafeed API would fail in some cases where if it had waited a fraction of a second it would have succeeded.

It won't fail. It just won't get assigned a node. Which means that it will attempt to get assigned again in a little bit

Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: > For Transforms we get the stats directly from the task if it is running else the index is searched.

We already get the stats for running tasks from in-memory.

> @dimitris-athanasiou I think you originally added some of these checks. Do you have any extra insights?

I think not checking whether the state and stats indices have their primaries active there is an omission. But it is not the cause of this error.

@droberts195, @benwtrent and myself discussed this further and we decided we will need to add debugging in order to understand what exactly is going on as it is currently not perfectly clear.

Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java]: > changes in verifyIndicesPrimaryShardsAreActive are necessary and good.

Yes I agree this is what we do for AD and we should check the same indices here.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Review by droberts195 — APPROVED** [review]
LGTM2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by mark-vieira** [comment]
Thanks, Ben!
