### PR TITLE
Fix LoggingOutputStream to work on windows

### LINKED ISSUE #51532: [CI] LoggingOutputStreamTests fails on Windows
The following tests fail in 7.x Windows builds:

```
org.elasticsearch.common.logging.LoggingOutputStreamTests testBufferExtension
org.elasticsearch.common.logging.LoggingOutputStreamTests testEmptyLine
org.elasticsearch.common.logging.LoggingOutputStreamTests testFlushOnNewline
org.elasticsearch.common.logging.LoggingOutputStreamTests testMaxBuffer
org.elasticsearch.common.logging.LoggingOutputStreamTests testThreadIsolation
```

An example is https://gradle-enterprise.elastic.co/s/yiooghd5t4ai4 (but every 7.x Windows build is failing for this reason).

The errors are all along the lines of this:

```
Expected: iterable containing ["pjsQsvUyoViFJjlUeCGSsMwFyERKKNZexDFEkobYKBmMuiqRUjqKIGjFAIojNnJgIZAqCaewZeaiaIqRupTDLXQhPmAdaRTzNPLYypRYxiVeZQOycAVicOazPvUQifDNMOqaXIJJRAOrlndMd", "OVERFLOW"]
     but: item 1: was "\r"
```

It seems like the CRLF Windows line endings are messing up the line splitting.

### PR DESCRIPTION
**Pull request by rjernst**
LoggingOutputStream reads a stream and breaks on newlines. This commit
fixes the behavior to account for windows newlines also containing `\r`.

closes #51532

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/logging/LoggingOutputStream.java [hunk 1]
```diff
@@ -91,7 +91,12 @@ public void write(int b) throws IOException {
     public void flush() {
         Buffer buffer = threadLocal.get();
         if (buffer.used == 0) return;
-        log(new String(buffer.bytes, 0, buffer.used, StandardCharsets.UTF_8));
+        int used = buffer.used;
+        if (buffer.bytes[used - 1] == '\r') {
```
Comment (mark-vieira) [inline server/src/main/java/org/elasticsearch/common/logging/LoggingOutputStream.java]: Wouldn't this throw a `ArrayIndexOutOfBounds` exception for instances where we attempt to write a line which is simply a single `\n` character? I think we need to add a bounds check here.

**Review by mark-vieira — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/elasticsearch/common/logging/LoggingOutputStream.java (hunk 1 above)
Comment (rjernst) [reply server/src/main/java/org/elasticsearch/common/logging/LoggingOutputStream.java]: `used - 1` is the last character of the buffer, and we know the buffer size is at least 1 because of the check on line 93.

Comment (mark-vieira) [reply server/src/main/java/org/elasticsearch/common/logging/LoggingOutputStream.java]: I see what's happening now. I misunderstood the `\n` character itself to be part of this buffer but it's not. Nevermind.

**Review by mark-vieira — APPROVED** [review]
👍
