### PR TITLE
Release operation permit on thread-pool rejection

### LINKED ISSUE #25863: Tasks stuck forever
Opening a bug report from this forum entry:
https://discuss.elastic.co/t/get-tasks-hang-and-accumulate-on-5-4-2/92368

After several full cluster restarts there are still some queries left stuck, but at least, they don't grow.
For example this one:
```
        "WVpcoLjFRlu1u_n6itJLQg:18857772" : {
          "node" : "WVpcoLjFRlu1u_n6itJLQg",
          "id" : 18857772,
          "type" : "netty",
          "action" : "indices:data/write/index",
          "start_time_in_millis" : 1499661942368,
          "running_time_in_nanos" : 1242244096666339,
          "cancellable" : false
        },
```
which couldn't finish in two weeks.

Please tell me if more information is needed to debug this.

### PR DESCRIPTION
**Pull request by ywelsch**
At the shard level we use an operation permit to coordinate between regular shard operations and special operations that need exclusive access. In ES versions < 6, the operation requiring exclusive access was invoked during primary relocation, but ES versions >= 6 this exclusive access is also used when a replica learns about a new primary or when a replica is promoted to primary.

These special operations requiring exclusive access delay regular operations from running, by adding them to a queue, and after finishing the exclusive access, release these operations which then need to be put back on the original thread-pool they were running on. In the presence of thread pool rejections, the current implementation had two issues:
- it would not properly release the operation permit when hitting a rejection (i.e. when calling `ThreadedActionListener.onResponse` from `IndexShardOperationPermits.acquire`).
- it would not invoke the onFailure method of the action listener when the shard was closed, and just log a warning instead (see `ThreadedActionListener.onFailure`), which would ultimately lead to the replication task never being cleaned up (see #25863).

This PR fixes both issues by introducing a custom threaded action listener that is permit-aware and properly deals with rejections.

Closes #25863

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/index/shard/IndexShardOperationPermitsTests.java [hunk 1]
```diff
@@ -59,7 +63,18 @@
 
     @BeforeClass
     public static void setupThreadPool() {
-        threadPool = new TestThreadPool("IndexShardOperationsLockTests");
+        int bulkThreadPoolSize = randomIntBetween(1, 2);
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/shard/IndexShardOperationPermitsTests.java]: ++ to randomly use limited capacity.

**Review by bleskes — CHANGES_REQUESTED** [review]
The code LGTM in sense that it does the right thing while maintaining the old behavior of the generic ThreadedActionListener. However, in this case, I'm a bit concerned about the number of options in which the failure handler can be called - sometimes on the requested executor, sometimes on the generic thread and some times on the original thread - so there is really no guarantee on what's "safe" to do there. I wonder if we should make it simpler code wise and say that the executor on holds for onResponse. The failure handler can be called on arbitrary threads and should only be used for light weight work (which we do). WDYT?

File: core/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java [hunk 2]
```diff
@@ -269,4 +269,71 @@ int getActiveOperationsCount() {
...
+
+                @Override
+                public void onRejection(Exception e) {
+                    IOUtils.closeWhileHandlingException(releasable);
+                    super.onRejection(e);
+                }
+
+                @Override
+                public void onFailure(Exception e) {
+                    listener.onFailure(e); // will possibly execute on the generic thread spawned off in releaseDelayedOperations
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java]: It is the responsibility of the wrapped listener to make sure to free the permit when encountering an exception in its `onResponse` method. I prefer the code to be more explicit here instead of mixing two failures paths.

File: core/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java [hunk 3]
```diff
@@ -269,4 +269,71 @@ int getActiveOperationsCount() {
...
+                }
+
+                @Override
+                protected void doRun() throws Exception {
+                    listener.onFailure(e);
+                }
+
+                @Override
+                public void onFailure(Exception e) {
+                    listener.onFailure(e); // will possibly execute on the generic thread spawned off in releaseDelayedOperations
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java]: This comment becomes obsolete by running the `PermitAwareThreadedActionListener.onFailure()` method on the caller thread.

**Review by bleskes — APPROVED** [review]
Thx @ywelsch . My only nit is to add java docs for the required "lightness" of the onFailure handling in the `onAcquired` listener.

**Comment by ywelsch** [comment]
Thanks @bleskes
