### PR TITLE
Mark translog as upgraded in the engine even if a legacy generation exists

### LINKED ISSUE #11858: Translog file already exists exception thrown on old indices on second restart
Start Elasticsearch 1.6 and run:

    DELETE *

    PUT good/t/1
    {"foo": "bar"}
    
Then shutdown and start ES from the master branch.  On the first start, the index recovers correctly:

    [2015-06-24 18:38:02,888][INFO ][gateway                  ] [Cobra] recovered [1] indices into cluster_state
    [2015-06-24 18:38:03,315][WARN ][cluster.metadata         ] [Cobra] [good] re-syncing mappings with cluster state for types [[t]]

Then shutdown and restart the node.  Recovery fails (continuously) with the following exception:

    [2015-06-24 18:38:16,260][INFO ][gateway                  ] [Fight-Man] recovered [1] indices into cluster_state
    [2015-06-24 18:38:16,810][WARN ][indices.cluster          ] [Fight-Man] [[good][0]] marking and sending shard failed due to [failed recovery]
    [good][0] failed to recovery from gateway
            at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:258)
            at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:60)
            at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:133)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:722)
    Caused by: [good][0] failed to create engine
            at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:135)
            at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
            at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1287)
            at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1282)
            at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:829)
            at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:810)
            at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:249)
            ... 5 more
    Caused by: java.nio.file.FileAlreadyExistsException: data/elasticsearch/nodes/0/indices/good/0/translog/translog-1435163866460.ckp
            at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
            at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
            at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
            at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:176)
            at java.nio.channels.FileChannel.open(FileChannel.java:287)
            at java.nio.channels.FileChannel.open(FileChannel.java:334)
            at org.elasticsearch.index.translog.Checkpoint.write(Checkpoint.java:87)
            at org.elasticsearch.index.translog.Translog.upgradeLegacyTranslog(Translog.java:263)
            at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:177)
            at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:131)
            ... 11 more
    [2015-06-24 18:38:16,814][WARN ][cluster.action.shard     ] [Fight-Man] [good][0] received shard failed for [good][0], node[NQ3bYnFUTfiyF-2RjSacbg], [P], s[INITIALIZING], unassigned_info[[reason=CLUSTER_RECOVERED], at[2015-06-24T16:38:16.219Z]], indexUUID [fx8Dwd1GRvivqRVezmK3sg], reason [shard failure [failed recovery][IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileAlreadyExistsException[data/elasticsearch/nodes/0/indices/good/0/translog/translog-1435163866460.ckp]; ]]
    [2015-06-24 18:38:16,815][WARN ][indices.cluster          ] [Fight-Man] [[good][1]] marking and sending shard failed due to [failed recovery]
    [good][1] failed to recovery from gateway

### PR DESCRIPTION
**Pull request by s1monw**
Today we mark a translog as upgraded by adding a marker to the engine commit.
Yet, this commit was only added if there was no translog present before ie. only
if we have a fresh engine which is missing the entire point. Yet, this commit
adds a backwards index tests that ensures we can open old indices more than once
ie. mark the index as upgraded.

Closes #11858

### CODE REVIEW

**Comment by s1monw** [comment]
@bleskes can you take a look

File: core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 1]
```diff
@@ -1711,6 +1716,97 @@ private Mapping dynamicUpdate() {
...
+            Path[] tlogFiles = filterExtraFSFiles(FileSystemUtils.files(translog));
+            assertEquals(Arrays.toString(tlogFiles), tlogFiles.length, 1);
+            final long size = Files.size(tlogFiles[0]);
+
+            final long generation = Translog.parseIdFromFileName(tlogFiles[0]);
+            assertTrue(generation >= 1);
+            logger.debug("upgrading index {} file: {} size: {}", indexName, tlogFiles[0].getFileName(), size);
+            Directory directory = newFSDirectory(src.resolve("0").resolve("index"));
+            Store store = createStore(directory);
+            final int iters = randomBoolean() ? 1 : 2;
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: I think it's good have 0 as an option here too? I.e., index and search a freshly opened engine ..

File: core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 2]
```diff
@@ -178,7 +178,7 @@ private Translog openTranslog(EngineConfig engineConfig, IndexWriter writer, boo
             }
         }
         final Translog translog = new Translog(translogConfig);
-        if (generation == null) {
+        if (generation == null || generation.translogUUID == null) {
             logger.debug("no translog ID present in the current generation - creating one");
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: can we change this log to indicated why we ended up here? (now it says only translog ID)

**Comment by bleskes** [comment]
LGTM. left two minor comments. I wonder if we should also change the translog ugprade logic to only look at files without the .tlog extension. Maybe even better - throw and exception if it runs into a .tlog file. Something is really odd in this case?

**Comment by s1monw** [comment]
@bleskes I added a new commit fixing your comments

**Comment by bleskes** [comment]
LGTM again

**Comment by s1monw** [comment]
@bleskes I opened #11875 regarding the parsing comment you had
