### PR TITLE
Tolerate empty types array in Watch definitions

### LINKED ISSUE #83235: After upgrading to 8.0.0 rc2, error is thrown when editing watchers created in 6.8.23
Step to reproduce:
1. in 6.8.23, create a ml anomaly detection job,
2. Start the job in real-time and create a watcher for it
3. upgrade the cluster to 7.17.0 BC3
4. resolve all critical issues which were reported from 8.0 upgrade assistant
5. Upgrade it to 8.0.0-rc2 BC2
6. go to Stack Management, try to edit the watcher

Observed:
Error: `Error loading watch could not parse [search] input for watch [ml-job3]. failed to parse [request] `

in es.log:
```
org.elasticsearch.ElasticsearchParseException: could not parse [search] input for watch [ml-job3]. failed to parse [request]
    at org.elasticsearch.xpack.watcher.input.search.SearchInput.parse(SearchInput.java:135) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.input.search.SearchInputFactory.parseInput(SearchInputFactory.java:39) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.input.search.SearchInputFactory.parseInput(SearchInputFactory.java:20) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.input.InputFactory.parseExecutable(InputFactory.java:38) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.input.InputRegistry.parse(InputRegistry.java:63) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.watch.WatchParser.parse(WatchParser.java:197) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.watch.WatchParser.parse(WatchParser.java:168) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.watch.WatchParser.parse(WatchParser.java:92) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.WatcherService.loadWatches(WatcherService.java:383) [x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.WatcherService.reloadInner(WatcherService.java:264) [x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.WatcherService.lambda$reload$1(WatcherService.java:226) [x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.WatcherService$1.doRun(WatcherService.java:445) [x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:776) [elasticsearch-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-8.0.0-rc2.jar:8.0.0-rc2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.elasticsearch.ElasticsearchParseException: could not read search request. unexpected array field [types]
    at org.elasticsearch.xpack.watcher.support.search.WatcherSearchTemplateRequest.fromXContent(WatcherSearchTemplateRequest.java:194) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    at org.elasticsearch.xpack.watcher.input.search.SearchInput.parse(SearchInput.java:133) ~[x-pack-watcher-8.0.0-rc2.jar:8.0.0-rc2]
    ... 16 more
```

the watcher document:
```
{
        "_index" : ".watches-reindexed-for-8",
        "_id" : "ml-job3",
        "_score" : 1.0,
        "_source" : {
          "trigger" : {
            "schedule" : {
              "interval" : "99s"
            }
          },
          "input" : {
            "search" : {
              "request" : {
                "search_type" : "query_then_fetch",
                "indices" : [
                  ".ml-anomalies-*"
                ],
                "types" : [ ],
                "body" : {
                  "size" : 0,
                  "query" : {
                    "bool" : {
                      "filter" : [
                        {
                          "term" : {
                            "job_id" : "job3"
                          }
                        },
                        {
                          "range" : {
                            "timestamp" : {
                              "gte" : "now-30m"
                            }
                          }
                        },
                        {
                          "terms" : {
                            "result_type" : [
                              "bucket",
                              "record",
                              "influencer"
                            ]
                          }
                        }
                      ]
                    }
                  },
                  "aggs" : {
                    "bucket_results" : {
                      "filter" : {
                        "range" : {
                          "anomaly_score" : {
                            "gte" : 75
                          }
                        }
                      },
                      "aggs" : {
                        "top_bucket_hits" : {
                          "top_hits" : {
                            "sort" : [
                              {
                                "anomaly_score" : {
                                  "order" : "desc"
                                }
                              }
                            ],
                            "_source" : {
                              "includes" : [
                                "job_id",
                                "result_type",
                                "timestamp",
                                "anomaly_score",
                                "is_interim"
                              ]
                            },
                            "size" : 1,
                            "script_fields" : {
                              "start" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : "LocalDateTime.ofEpochSecond((doc[\"timestamp\"].date.getMillis()-((doc[\"bucket_span\"].value * 1000)\n * params.padding)) / 1000, 0, ZoneOffset.UTC).toString()+\":00.000Z\"",
                                  "params" : {
                                    "padding" : 10
                                  }
                                }
                              },
                              "end" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : "LocalDateTime.ofEpochSecond((doc[\"timestamp\"].date.getMillis()+((doc[\"bucket_span\"].value * 1000)\n * params.padding)) / 1000, 0, ZoneOffset.UTC).toString()+\":00.000Z\"",
                                  "params" : {
                                    "padding" : 10
                                  }
                                }
                              },
                              "timestamp_epoch" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : """doc["timestamp"].date.getMillis()/1000"""
                                }
                              },
                              "timestamp_iso8601" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : """doc["timestamp"].date"""
                                }
                              },
                              "score" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : """Math.round(doc["anomaly_score"].value)"""
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "influencer_results" : {
                      "filter" : {
                        "range" : {
                          "influencer_score" : {
                            "gte" : 3
                          }
                        }
                      },
                      "aggs" : {
                        "top_influencer_hits" : {
                          "top_hits" : {
                            "sort" : [
                              {
                                "influencer_score" : {
                                  "order" : "desc"
                                }
                              }
                            ],
                            "_source" : {
                              "includes" : [
                                "result_type",
                                "timestamp",
                                "influencer_field_name",
                                "influencer_field_value",
                                "influencer_score",
                                "isInterim"
                              ]
                            },
                            "size" : 3,
                            "script_fields" : {
                              "score" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : """Math.round(doc["influencer_score"].value)"""
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "record_results" : {
                      "filter" : {
                        "range" : {
                          "record_score" : {
                            "gte" : 3
                          }
                        }
                      },
                      "aggs" : {
                        "top_record_hits" : {
                          "top_hits" : {
                            "sort" : [
                              {
                                "record_score" : {
                                  "order" : "desc"
                                }
                              }
                            ],
                            "_source" : {
                              "includes" : [
                                "result_type",
                                "timestamp",
                                "record_score",
                                "is_interim",
                                "function",
                                "field_name",
                                "by_field_value",
                                "over_field_value",
                                "partition_field_value"
                              ]
                            },
                            "size" : 3,
                            "script_fields" : {
                              "score" : {
                                "script" : {
                                  "lang" : "painless",
                                  "source" : """Math.round(doc["record_score"].value)"""
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "condition" : {
            "compare" : {
              "ctx.payload.aggregations.bucket_results.doc_count" : {
                "gt" : 0
              }
            }
          },
          "actions" : {
            "log" : {
              "logging" : {
                "level" : "info",
                "text" : "Alert for job [{{ctx.payload.aggregations.bucket_results.top_bucket_hits.hits.hits.0._source.job_id}}] at [{{ctx.payload.aggregations.bucket_results.top_bucket_hits.hits.hits.0.fields.timestamp_iso8601.0}}] score [{{ctx.payload.aggregations.bucket_results.top_bucket_hits.hits.hits.0.fields.score.0}}]"
              }
            }
          },
          "metadata" : {
            "xpack" : {
              "type" : "json"
            }
          },
          "status" : {
            "state" : {
              "active" : true,
              "timestamp" : "2022-01-27T16:27:58.849Z"
            },
            "actions" : {
              "log" : {
                "ack" : {
                  "timestamp" : "2022-01-27T16:27:58.849Z",
                  "state" : "awaits_successful_execution"
                }
              }
            },
            "headers" : {
              "_xpack_security_authentication" : "357zAgAHZWxhc3RpYwEJc3VwZXJ1c2VyCgAAAAEAE2luc3RhbmNlLTAwMDAwMDAwMDAFZm91bmQEZmlsZQAACgA="
            },
            "version" : -1,
            "last_checked" : "2022-01-27T18:16:58.081Z",
            "execution_state" : "execution_not_needed"
          }
        }
      }
```

### PR DESCRIPTION
**Pull request by droberts195**
In 6.x internal system components created Watches with an empty
types array in their definition. Types do not exist in 8.x, so
these system-created Watches would need to be modified in 7.x
to remove the types field. Because doing such modifications as
a secret background task could be risky, instead the 8.x Watch
parser will tolerate and ignore an empty types array. It is
clear that an empty types array can be considered identical to
typeless. Non-empty types arrays will still be considered fatal
errors in 8.x, as silently ignoring them could change the meaning
of the search.

Fixes #83235

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/search/WatcherSearchTemplateRequest.java [hunk 1]
```diff
@@ -190,6 +196,17 @@ public static WatcherSearchTemplateRequest fromXContent(XContentParser parser, S
...
+                    // Tolerate an empty types array, because some watches created internally in 6.x have
+                    // an empty types array in their search, and it's clearly equivalent to typeless.
+                    if (parser.nextToken() != XContentParser.Token.END_ARRAY) {
+                        throw new ElasticsearchParseException(
+                            "could not read search request. unsupported non-empty array field [" + currentFieldName + "]"
+                        );
+                    }
+                    // Empty types arrays still generate the same deprecation warning they did in 7.x.
+                    // Ideally they should be removed from the definition.
+                    deprecationLogger.warn(DeprecationCategory.PARSING, "watcher_search_input", TYPES_DEPRECATION_MESSAGE);
```
Comment (masseyke) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/search/WatcherSearchTemplateRequest.java:209]: Should this be a critical message? Or is it likely that we'll never actually remove support for the empty type array so warning is more appropriate?

**Review by masseyke — APPROVED** [review]
I have the one minor question about what level the deprecation logger message ought to be, but otherwise LGTM.

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/search/WatcherSearchTemplateRequest.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/search/WatcherSearchTemplateRequest.java:209]: Yes, I wondered about this too.  It's a bit weird that in 7.17 empty types was giving a critical deprecation yet this downgrades it to just warning in 8.0.  We don't want this to block upgrades but it doesn't because it's only deprecation logging, not deprecation info.  I'll change it to critical.
