### PR TITLE
Fields caps does not honour ignore_unavailable

### LINKED ISSUE #107767: `_field_caps` doesn't honour `ignore_unavailable` option with closed index
### Elasticsearch Version

8.14, also current master (@8201172)

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macos

### Problem Description

Querying an inexistent index'es `_field_caps` with `ignore_unavailable=true` will work (returns no caps).
The same, but with an existing and closed index fails with `cluster_block_exception`.

### Steps to Reproduce

1. PUT myindex
2. POST myindex/_close
3. GET myindex/_field_caps?fields=*&ignore_unavailable=true

### Logs (if relevant)

Last step will fail with:
```
{
    "error": {
        "root_cause": [
            {
                "type": "cluster_block_exception",
                "reason": "index [myindex] blocked by: [FORBIDDEN/4/index closed];"
            }
        ],
        "type": "cluster_block_exception",
        "reason": "index [myindex] blocked by: [FORBIDDEN/4/index closed];"
    },
    "status": 403
}
```

### PR DESCRIPTION
**Pull request by drempapis**
Querying an **existing** and **closed** index fails with **cluster_block_exception** when the **_field_caps** with **ignore_unavailable=true**  is called. 

The close State is not considered when filtering "unavailable," missing, or unacceptable resources, propagating closed indices to the method **TransportFieldCapabilitiesAction::checkIndexBlocks**, which raises an exception.

In this PR, state-related code was added to filter out closed indices.

Closes #107767

### CODE REVIEW

**Comment by drempapis** [comment]
I updated the code after detecting test failures on ci. I moved the logic to exclude closed indices to the TransportFieldsCapabilitiesAction class to avoid business-logic conflicts with implementation for other Actions.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 1]
```diff
@@ -148,7 +150,14 @@ private void doExecuteForked(
...
             concreteIndices = Strings.EMPTY_ARRAY;
         } else {
-            concreteIndices = indexNameExpressionResolver.concreteIndexNames(clusterState, localIndices);
+            boolean ignoreUnavailable = request.indicesOptions().ignoreUnavailable();
+            concreteIndices = Arrays.stream(indexNameExpressionResolver.concreteIndexNames(clusterState, localIndices)).filter(index -> {
+                IndexMetadata metadata = clusterState.getMetadata().getIndices().get(index);
+                if (metadata != null && metadata.getState() == IndexMetadata.State.CLOSE) {
+                    if (ignoreUnavailable) return false;
+                    else throw new IndexClosedException(metadata.getIndex());
+                } else return true;
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:159]: I am a bit outdated on how indices resolution works these days, after recent refactoring. I was somehow not expecting that you need to explicitly handle closed indices, rather that provided indices and indices options, the method does what it needs to do, meaning not return closed indices. Can you double check that that option is no longer possible?

Comment (drempapis) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:159]: Thank you, @javanna, for reviewing the pr. You are right. Further debugging the code, I found that for the incoming requests, the **allowClosedIndices** is set to **true**. Changing the default value at the FieldCapabilitiesRequest level, mitigates that issue.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java [hunk 2]
```diff
@@ -35,7 +35,7 @@
 
 public final class FieldCapabilitiesRequest extends ActionRequest implements IndicesRequest.Replaceable, ToXContentObject {
     public static final String NAME = "field_caps_request";
-    public static final IndicesOptions DEFAULT_INDICES_OPTIONS = IndicesOptions.strictExpandOpen();
+    public static final IndicesOptions DEFAULT_INDICES_OPTIONS = IndicesOptions.strictExpandOpenAndForbidClosed();
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java:38]: Nice! I believe this is ok. The doubt I have is just about the fact that we are changing index resolution for the field caps API, and that will affect existing usage. Yet if this is only to avoid errors when targeting closed indices, I think that's the right call, assuming there are no side effects. Are you able to get a green build?

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 3]
```diff
@@ -1763,6 +1763,7 @@ private static boolean ensureAliasOrIndexExists(Context context, String name) {
                     throw notFoundException(name);
                 }
             }
+
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java:1766]: nit: remove this additional line? :)

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java (hunk 2 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java:38]: Thank you, @javanna, I'll proceed with that

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java (hunk 3 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: Fixed, ty

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java (hunk 2 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java:38]: I am not 100% sure I am following this. Why are we changing the default behaviour? Don't we want the change only when we get `ignore_unavailable=true`? 
My reasoning here is: if we target a closed index an we have `ignore_unavailable=false` we want an error back, while if the request has `ignore_unavailable=true` we can safely skip closed indices.

Comment (piergm) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesRequest.java:38]: Oh I see, thank you for the clarification!

**Comment by drempapis** [comment]
@elasticmachine update branch

File: server/src/internalClusterTest/java/org/elasticsearch/search/fieldcaps/FieldCapabilitiesIT.java [hunk 4]
```diff
@@ -319,6 +322,65 @@ public void testWithIndexAlias() {
...
+        client().admin().indices().close(new CloseIndexRequest("old_index")).actionGet();
+        FieldCapabilitiesResponse response = client().prepareFieldCaps().setFields("*").setIndicesOptions(options).get();
+        assertIndices(response, "new_index");
+    }
+
+    public void testOneClosedIndex() {
+        boolean ignoreUnavailable = false;
+        IndicesOptions options = IndicesOptions.fromOptions(ignoreUnavailable, true, true, false, true, true, false, false);
+
+        // IndicesOptions options = IndicesOptions.fromOptions(ignoreUnavailable, true, true, false);
```
Comment (piergm) [inline server/src/internalClusterTest/java/org/elasticsearch/search/fieldcaps/FieldCapabilitiesIT.java:345]: Nit: we could remove this comment

**Review by piergm — APPROVED** [review]
LGTM, just one small nit 😄

File: server/src/internalClusterTest/java/org/elasticsearch/search/fieldcaps/FieldCapabilitiesIT.java (hunk 4 above)
Comment (drempapis) [reply server/src/internalClusterTest/java/org/elasticsearch/search/fieldcaps/FieldCapabilitiesIT.java]: This is done, ty @piergm

**Comment by drempapis** [comment]
@elasticmachine run elasticsearch-ci/part-4

**Comment by drempapis** [comment]
@elasticmachine test this please

**Comment by drempapis** [comment]
@elasticmachine update branch

**Review by javanna — APPROVED** [review]
LGTM thanks @drempapis

**Comment by drempapis** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116430)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
