### PR TITLE
Fix autoscaling of follower data streams

### LINKED ISSUE #82857: Autoscaling a follower cluster with data streams fails
A cluster using CCR to follow a data stream from another cluster can cause the autoscaling capacity API to fail to deliver an autoscaling response with an exception like:

```
GET /_autoscaling/capacity/
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "data stream [data-stream-name] cannot be rolled over, because it is a replicated data stream"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "data stream [data-stream-name] cannot be rolled over, because it is a replicated data stream"
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by henningandersen**
The presence of follower data streams would cause autoscaling capacity
calculation to fail.

Closes #82857

### CODE REVIEW

**Comment by martijnvg** [comment]
Maybe I'm missing something, but why would rolling over only the follower data stream help here? Should data streams that are being replicated be skipped during the auto scale rollover instead?

Forcefully rolling over a replicated data stream means that the data stream on the follower side would get a backing index that will never exist on the leader side. This index will not never be used. Locally it can't accept writes and on the leader side writes will be resolved to the write index know by the leader data stream. When the leader data stream rolls over, it will create a new backing index as write index, that is different than the backing index created by the rollover triggered from auto scaling.

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java [hunk 1]
```diff
@@ -273,6 +273,13 @@ public IndexMode getIndexMode() {
     public DataStream rollover(Index writeIndex, long generation) {
         ensureNotReplicated();
 
+        return unsafeRollover(writeIndex, generation);
+    }
+
+    /**
+     * Like #rollover, but does no validation, use with care only.
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java:280]: Maybe use `{@link #rollover(Index, long)}` instead of `#rollover` in java docs?

File: x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderService.java [hunk 2]
```diff
@@ -568,16 +567,17 @@ private SingleForecast forecast(Metadata metadata, IndexAbstraction.DataStream s
             DataStream dataStream = stream.getDataStream();
             for (int i = 0; i < numberNewIndices; ++i) {
                 final String uuid = UUIDs.randomBase64UUID();
-                final Tuple<String, Long> dummyRolledDatastream = dataStream.nextWriteIndexAndGeneration(state.metadata());
```
Comment (martijnvg) [inline x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderService.java:571]: Maybe add a `unsafeNextWriteIndexAndGeneration(...)` and use it here?
That way the exact same logic remains to be used.

**Review by martijnvg — APPROVED** [review]
I forgot that `ReactiveStorageDeciderService` simulates scaling the cluster and the cluster produced here is thrown away after simulation. So the rollover performed here is not put into effect.

LGTM, I left two small comments.

File: server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java]: Thanks for spotting that, fixed in da77aaee1931f03c82ddfcd50ec93fc86bd00d9d

File: x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderService.java (hunk 2 above)
Comment (henningandersen) [reply x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderService.java:571]: Sure, see da77aaee1931f03c82ddfcd50ec93fc86bd00d9d
