### PR TITLE
[ES|QL] Correct line and column numbers of missing named parameters

### LINKED ISSUE #120778: [ES|QL] Error on request with named params gives wrong line,column information
### Elasticsearch Version

9.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

When I send a query like `from kibana_sample_data_logs | STATS var0 = AVG(?field)` without sending the value the response has the wrong line/column. As a result the kibana highlighter doesnt work properly

```
Error: line -1:-1: line 1:49: Unknown query parameter [field]
```

Image

### Steps to Reproduce

Just send a query with a named param without sending the value in the payload

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #120778

The parsing errors related to missing named parameters do not have a proper position associated with them, when the errors are collected together at the end of parser. This PR assign the first error's position as the position of the consolidated errors.

Before: the location of the error message is `line -1:-1:`
```
{
  "query": "from sample_data | where client.ip == ?ip and @timestamp > ?time",
  "params" : []
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "line -1:-1: line 1:39: Unknown query parameter [ip]; line 1:60: Unknown query parameter [time]"
      }
    ],
    "type" : "parsing_exception",
    "reason" : "line -1:-1: line 1:39: Unknown query parameter [ip]; line 1:60: Unknown query parameter [time]"
  },
  "status" : 400
}
```
After: the location of the first error is returned as the location of the whole message.
```
{
  "query": "from sample_data | where client.ip == ?ip and @timestamp > ?time",
  "params" : []
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "line 1:39: Unknown query parameter [ip]; line 1:60: Unknown query parameter [time]"
      }
    ],
    "type" : "parsing_exception",
    "reason" : "line 1:39: Unknown query parameter [ip]; line 1:60: Unknown query parameter [time]"
  },
  "status" : 400
}
```

### CODE REVIEW

**Comment by stratoula** [comment]
Thanx Fang 🙌

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/ParsingException.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/ParsingException.java:1]: While we're at it, could we maybe add a short warning javadoc to the constructor that we no longer use for this, the one that doesn't take a source or line/char numbers? I think it'd help to point out that the error message will start with `line -1:-1`, that may not be obvious without looking more closely. Something like
```
    /**
     * To be used only if the exception cannot be associated with a specific position in the query. Error message will start with
     * {@code line -1:-1:} instead of using specific line/character numbers. 
     */
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:1]: nit: the changes here essentially just implement squashing multiple `ParsingException`s into a single one. I think it'd be a tad nicer if that logic was encapsulated in `ParsingException`, maybe as a method `ParsingException.combineWith(ParsingException... others)` or so.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java [hunk 1]
```diff
@@ -108,15 +108,23 @@ protected LogicalPlan plan(ParseTree ctx) {
...
+                    // line and column numbers are the associated with the first error
+                    line = e.getLineNumber();
+                    charPositionInLine = e.getColumnNumber();
+                    message.append(e.getErrorMessage());
                 }
-                message.append(errors.next().getMessage());
                 i++;
             }
-            throw new ParsingException(message.toString());
+            throw new ParsingException(line, charPositionInLine, message.toString());
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:127]: Nit: Would it be worth it to add a `CompoundParsingException` class doing this? Maybe a subclass, to avoid any potential code breaking (I see some tests using `getLineNumber`, we could refactor those).
Some pros of this:
- The `getErrorMessage` returns a weird message in this PR, a `First error; line 1:2: Second error; line 4:5: Third error`, missing the line on the first one only
- To wrap this logic inside a `new CompoundParsingException(exceptions)`
- No need for the new constructor without source

Very nit really, feel free to ignore! Especially if you think it could add some extra complexity somewhere

**Review by alex-spies — APPROVED** [review]
LGTM, thanks @fang-xing-esql ! Only minor comments from me :)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java (hunk 1 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:127]: Adding to this, I see some uses of `instanceof ParsingException` just to do a `.getErrorMessage()` instead of `getMessage()`. I would check if those would still work "as expected" with this change

**Review by ivancea — APPROVED** [review]
LGTM! A comment with a suggestion. Not sure how big the change is tho

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/ParsingException.java
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/ParsingException.java:1]: Good point, will add a comment there.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:1]: It makes sense, I was thinking about the same thing, I'll move these into `ParsingException`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/LogicalPlanBuilder.java:128]: Here we indeed return a combined `ParsingException` that represents a collection of `ParsingException`s related to named parameters. 

It is actually not a bad idea to have a `CompoundParsingException` I think, the only thing that I can think of is that the downstream components may need to deal with them differently, if we throw a `ParsingException`, they can locate it in the query text directly, however if we throw a `CompoundParsingException`, they may need to iterate through each `ParsingException` that belongs to the `CompoundParsingException` to extract the locations, this could be a better way to present all parsing errors that are related to the named parameters, it requires changes in kibana potentially. For now, I'll combine them into one `ParsingException`, `CompoundParsingException` is a potential future enhancement if we need a better way to present these errors.

`getErrorMessage()` does not include the location of the query text, I double checked, there are a couple of places that call it directly, they don't require the location information.

**Review by idegtiarenko — APPROVED** [review]

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch

**Comment by fang-xing-esql** [comment]
@elasticmachine test it

**Comment by fang-xing-esql** [comment]
@elasticmachine test this please

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch
