### PR TITLE
Optimize the composite aggregation for match_all and range queries

### LINKED ISSUE #28688: Metric aggregation fails in composite aggregation
Hi!

I'm using Elasticsearch to store test results of a software. I'm running Elasticsearch on Docker CE with the following configuration:

Docker version 17.12.0-ce, build c97c6d6
Ubuntu 14.04.5 LTS 14.04 trusty
docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
docker.elastic.co/kibana/kibana-oss:6.2.1

The documents look like the following:

```
    {  
       "product":{  
          "software":{  
             "revision":"251ebc1ed721622f49c5485068f8b39c45005a20",
             "date":"2018-02-09T17:40:34+00:00"
          },
          "os":{  
             "name":"Ubuntu",
             "version":"14.04"
          }
       },
       "results":{  
          "summary":{  
             "Pass":2,
             "Fail":3
          }
       }
    }
```

I want to compute the average Pass and Fail numbers for all combinations of os.name and os.version for their newest software version, so I use the following Composite query:

```
    GET _search
    {
      "size": 0,
        "query": {
          "match_all": {}
        },
        "aggs": {
          "products": {
            "composite": {
              "sources": [
                {
                  "osName": {
                    "terms": {
                      "field": "product.os.name.keyword"
                    }
                  }
                },
                {
                  "osVer": {
                    "terms": {
                      "field": "product.os.version.keyword"
                    }
                  }
                }
              ]
            },
            "aggs": {
              "revision": {
                "terms": {
                  "field": "product.software.revision.keyword",
                  "order": {
                    "SWDate": "desc"
                  },
                  "size": 1
                },
                "aggs": {
                  "SWDate": {
                    "max": {
                      "field": "product.software.date"
                    }
                  },
                   "Pass": {
                    "avg": {
                      "field": "results.summary.Pass",
                      "missing": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
```

However, this fails with:

```
    "_shards": {
        "total": 6,
        "successful": 1,
        "skipped": 0,
        "failed": 5,
        "failures": [
          {
            "shard": 0,
            "index": "test_results",
            "node": "<nodeId>",
            "reason": {
              "type": "illegal_state_exception",
              "reason": "Cannot replay yet, collection is not finished: postCollect() has not been called"
            }
          }
        ]
      }
```

If I remove the Pass average aggregation it does not fail but id does fail with other metric aggregations. Any ideas what I might do wrong? Thanks!

### PR DESCRIPTION
**Pull request by jimczi**
This change refactors the composite aggregation to add an execution mode that visits documents in the order of the values present in the leading source of the composite definition. This mode does not need to visit all documents since it can early terminate the collection when the leading source value is greater than the lowest value in the queue.
Instead of collecting the documents in the order of their doc_id, this mode uses the inverted lists (or the bkd tree for numerics) to collect documents
in the order of the values present in the leading source.
For instance the following aggregation:

```
"composite" : {
  "sources" : [
    { "value1": { "terms" : { "field": "timestamp", "order": "asc" } } }
  ],
  "size": 10
}
```
... can use the field `timestamp` to collect the documents with the 10 lowest values for the field instead of visiting all documents.
For composite aggregation with more than one source the execution can early terminate as soon as one of the 10 lowest values produces enough composite buckets. For instance if visiting the first two lowest timestamp created 10 composite buckets we can early terminate the collection since it
is guaranteed that the third lowest timestamp cannot create a composite key that compares lower than the one already visited.

This mode can execute iff:
 * The leading source in the composite definition uses an indexed field of type `date` (works also with `date_histogram` source), `integer`, `long` or `keyword`.
 * The query is a match_all query or a range query over the field that is used as the leading source in the composite definition.
 * The sort order of the leading source is the natural order (ascending since postings and numerics are sorted in ascending order only).

If these conditions are not met this aggregation visits each document like any other agg.

Closes #28688

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java [hunk 1]
```diff
@@ -0,0 +1,397 @@
...
+    /**
+     * Visits all non-deleted documents in <code>iterator</code> and pass documents that contain competitive composite buckets
+     * to the provided <code>sub</code> collector.
+     * Returns true if the queue is full and the current <code>leadSourceBucket</code> did not produce any competitive
+     * composite buckets.
+     */
+    protected boolean processBucket(LeafReaderContext context, LeafBucketCollector sub,
+                                    DocIdSetIterator iterator, Comparable<?> leadSourceBucket) throws IOException {
+        final int[] topCompositeCollected = new int[1];
+        final boolean[] hasCollected = new boolean[1];
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java]: why do these need to be arrays if they only contain a single element?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java [hunk 2]
```diff
@@ -150,118 +111,37 @@ public InternalAggregation buildEmptyAggregation() {
...
-    protected void doPostCollection() throws IOException {
-        if (leaf != null) {
-            leaf.docIdSet = builder.build();
-            contexts.add(leaf);
+        if (sortedBucketProducer != null && sortedBucketProducer.isApplicable(context.query())) {
+            // we can bypass search, the producer will visit documents sorted by the leading source
+            // of the composite definition and terminates when the leading source value is guaranteed to be
+            // greater than the lowest composite bucket in the queue.
+            sortedBucketProducer.processLeaf(context.query(), ctx, sub);
+            throw new CollectionTerminatedException();
```
Comment (colings86) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java]: I wonder if it would be clearer for the SortedBucketProducer to throw the exception rather than throwing it here?

**Review by colings86 — COMMENTED** [review]
@jimczi I left a few comments but it looks good

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java]: Because the values are set in the anonymous class below, I find it nicer than using Atomic and I saw this pattern in other locations in the codebase.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java (hunk 2 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java]: I pushed a commit that adds a comment regarding why we throw an exception here.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BestCompositeBucketsDeferringCollector.java [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+     */
+    BestCompositeBucketsDeferringCollector(SearchContext context, CompositeValuesCollectorQueue queue, boolean isCollectionSorted) {
+        this.searchContext = context;
+        this.queue = queue;
+        this.isCollectionSorted = isCollectionSorted;
+    }
+
+    @Override
+    public boolean needsScores() {
+        if (collector == null) {
```
[the remark this answers is not in the document]
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BestCompositeBucketsDeferringCollector.java]: ++, I replaced it with an assert.

**Review by colings86 — APPROVED** [review]
LGTM (when the build gets to green 😄)

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueue.java [hunk 4]
```diff
@@ -0,0 +1,271 @@
...
+
+    private final int maxSize;
+    private final TreeMap<Integer, Integer> keys;
+    private final CompositeValuesSource<?, ?>[] arrays;
+    private final int[] docCounts;
+    private final SortedDocsProducer docsProducer;
+    private boolean afterValueSet = false;
+
+    /**
+     * Ctr
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueue.java]: missing text?

**Review by jpountz — COMMENTED** [review]
I still need to dig more to fully understand how it works but I like the idea. Some comments:
 - As we are adding more abstractions to the implementation to support optimizations, I wish we had dedicated tests for these abstractions too like the sorted docs producer, the queue, etc.
 - Can we also disable this optimization when there is a high ratio of deleted docs? I don't think that would be a problem in general as merges make sure there are no more than 50% of deleted documents, but this doesn't hold anymore for users of security since hidden docs appear as deleted. Maybe also reauires that numDocs / maxDoc > 0.5?

**Comment by jimczi** [comment]
Thanks for looking @jpountz . I've pushed some commits to address your comments, the optimization is disabled when there are more than 50% of deleted documents and I've added more tests for the new abstractions. Can you take another look ?

**Comment by jpountz** [comment]
Jim and I discussed moving away from the deferring framework so that it looks a bit less weird eg. due to feeding collect with out-of-order ids.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+    @Override
+    LeafBucketCollector getLeafCollector(Comparable<?> value, LeafReaderContext context, LeafBucketCollector next) {
+        if (value.getClass() != BytesRef.class) {
+            throw new IllegalArgumentException("Expected BytesRef, got " + value.getClass());
+        }
+        final BytesRef filterValue = (BytesRef) value;
+        return new LeafBucketCollector() {
+            @Override
+            public void collect(int doc, long bucket) throws IOException {
+                currentValue = filterValue;
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java]: do we need to set it for every doc?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java [hunk 6]
```diff
@@ -0,0 +1,137 @@
...
+    @Override
+    LeafBucketCollector getLeafCollector(LeafReaderContext context, LeafBucketCollector next) throws IOException {
+        final SortedBinaryDocValues dvs = docValuesFunc.apply(context);
+        return new LeafBucketCollector() {
+            @Override
+            public void collect(int doc, long bucket) throws IOException {
+                if (dvs.advanceExact(doc)) {
+                    int num = dvs.docValueCount();
+                    for (int i = 0; i < num; i++) {
+                        currentValue = dvs.nextValue();
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java]: this means currentValue will always be the higher value in case of a multi-valued field, is that ok?

**Review by jpountz — COMMENTED** [review]
I still need to pursue this review (this is a big change!) but at first sight I find it more readable than the previous version!

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java (hunk 6 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java]: currentValue is only valid for the current composite bucket, `next.collect()` below will fill the other sources's currentValue and the last collector in the chain will check if the final composite bucket should be added in the queue. We don't use currentValue outside of these recursive calls.

Comment (jpountz) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/BinaryValuesSource.java]: I see, thanks.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java [hunk 7]
```diff
@@ -0,0 +1,135 @@
...
+     */
+    SingleDimensionValuesSource(@Nullable MappedFieldType fieldType, int size, int reverseMul) {
+        this.fieldType = fieldType;
+        this.size = size;
+        this.reverseMul = reverseMul;
+        this.afterValue = null;
+    }
+
+    /**
+     * The type of this source.
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java]: maybe mention how it's used?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+     */
+    abstract String type();
+
+    /**
+     * Copies the current value in <code>slot</code>.
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java]: maybe say how it's supposed to know about the current value?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+     */
+    abstract void copyCurrent(int slot);
+
+    /**
+     * Compares the value in <code>from</code> with the value in <code>to</code>.
+     */
+    abstract int compare(int from, int to);
+
+    /**
+     * Compares the current value with the value in <code>slot</code>.
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java]: maybe say that the current value is the one from the last copyCurrent call?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java [hunk 10]
```diff
@@ -143,125 +127,178 @@ public InternalAggregation buildAggregation(long zeroBucket) throws IOException
...
+        final boolean needsScores = needsScores();
+        Weight weight = null;
+        if (needsScores) {
+            Query query = context.query();
+            weight = context.searcher().createNormalizedWeight(query, true);
+        }
+        deferredCollectors.preCollection();
+        for (Entry entry : entries) {
+            DocIdSetIterator docIdSetIterator = entry.docIdSet.iterator();
+            if (docIdSetIterator == null || docIdSetIterator.cost() == 0) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeAggregator.java]: using `cost()==0` is a bit unsafe since cost() may be completely off

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeValuesSourceConfig.java [hunk 11]
```diff
@@ -19,22 +19,33 @@
...
 
-    CompositeValuesSourceConfig(String name, ValuesSource vs, DocValueFormat format, SortOrder order, boolean canEarlyTerminate) {
+    /**
+     *
+     * @param name
+     * @param fieldType
+     * @param vs
+     * @param format
+     * @param order
+     */
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/CompositeValuesSourceConfig.java]: doesn't look useful?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java [hunk 12]
```diff
@@ -0,0 +1,97 @@
...
+     *
+     * Returns true if the queue is full and the current <code>leadSourceBucket</code> did not produce any competitive
+     * composite buckets.
+     */
+    protected boolean processBucket(CompositeValuesCollectorQueue queue, LeafReaderContext context, DocIdSetIterator iterator,
+                                    Comparable<?> leadSourceBucket, @Nullable DocIdSetBuilder builder) throws IOException {
+        final int[] topCompositeCollected = new int[1];
+        final boolean[] hasCollected = new boolean[1];
+        int cost = (int) iterator.cost();
+        final DocIdSetBuilder.BulkAdder adder = builder != null ? builder.grow(cost) : null;
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java]: This optimization is unsafe since cost may be inaccurate. I would be ok if it was only called with postings, but it looks like this method is sometimes called with the result of DocIdSetBuilder.finish which gives approximate costs in the dense case.

**Review by jpountz — CHANGES_REQUESTED** [review]
OK, I had a more thorough review and I like the change in general. There is one or two places where it might make too strong assumptions about the value of the cost but other than that it looks good to me. I'd also like to see more comments to explain how things work. I suggested some javadocs improvements.

**Comment by jimczi** [comment]
@jpountz I pushed more changes to fix the issue with the cost approximation and added some javadocs. I think it's ready for another round ;)

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java [hunk 13]
```diff
@@ -54,19 +54,30 @@ protected boolean processBucket(CompositeValuesCollectorQueue queue, LeafReaderC
...
         final boolean[] hasCollected = new boolean[1];
-        int cost = (int) iterator.cost();
-        final DocIdSetBuilder.BulkAdder adder = builder != null ? builder.grow(cost) : null;
         final LeafBucketCollector queueCollector = new LeafBucketCollector() {
             int lastDoc = -1;
 
+            // we need to add the matching document in the builder
+            // so we build a bulk adder from the approximate cost of the iterator
+            // and rebuild the adder during the collection if needed
+            int remainingBits = (int) iterator.cost();
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java]: Let's do a Math.min(cost, Integer.MAX_VALUE) rather than a blind cast?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/PointsSortedDocsProducer.java [hunk 14]
```diff
@@ -0,0 +1,181 @@
...
+            this.builder = builder;
+            this.lowerBucket = lowerBucket;
+            this.upperBucket = upperBucket;
+            this.bucketDocsBuilder = new DocIdSetBuilder(maxDoc);
+            this.bytesPerDim = bytesPerDim;
+        }
+
+        @Override
+        public void grow(int count) {
+            remaining = count;
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/PointsSortedDocsProducer.java]: I don't think you need to count the number of remaining docs here, the BKD tree does it for you

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java [hunk 15]
```diff
@@ -0,0 +1,108 @@
...
+                                    Comparable<?> leadSourceBucket, @Nullable DocIdSetBuilder builder) throws IOException {
+        final int[] topCompositeCollected = new int[1];
+        final boolean[] hasCollected = new boolean[1];
+        final LeafBucketCollector queueCollector = new LeafBucketCollector() {
+            int lastDoc = -1;
+
+            // we need to add the matching document in the builder
+            // so we build a bulk adder from the approximate cost of the iterator
+            // and rebuild the adder during the collection if needed
+            int remainingBits = (int) iterator.cost();
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/SortedDocsProducer.java]: let's do min(Integer.MAX_VALUE, iterator.cost())

**Review by jpountz — APPROVED** [review]
I left some minor comments. Otherwise LGTM. Since this is a rather large change I'd rather not fold it into 6.3 and wait for 6.4.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/PointsSortedDocsProducer.java (hunk 14 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/PointsSortedDocsProducer.java]: I need it because we build one doc id set per bucket (not per bkd leaf) so if the values are different inside a leaf I need to know the number of remaining docs in that leaf to create the new doc id set builder.

Comment (jpountz) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/composite/PointsSortedDocsProducer.java]: I see, thanks for explaining.

**Comment by viewsite** [comment]
@jimczi 

I wonder why the previous optimization of index sorting could not be retained. It seemed that the condition of index sorting is easier to be met and can early terminate aggregation on each segment without the condition of leading source and query.

Grateful for any help!
