### PR TITLE
Parse composite patterns using ClassicFormat.parseObject

### LINKED ISSUE #39916: Multiple date formats in date_histogram aggregation
The following worked in `6.x`

```json
"date_histogram": {
    "extended_bounds": {
        "max": "2016-06-06T12:01:02.123",
        "min": "2014-06-06T12:01:02.123"
    },
    "field": "startedOn",
    "format": "yyyy-MM-dd'T'HH:mm:ss||date_optional_time",
    "interval": "month",
    "min_doc_count": 2,
    "missing": "2015-06-06T12:01:02.123",
    "order": {
         "_count": "asc"
    }
}
```

In `7.0.0-beta1` it fails with the following:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [2014-06-06T12:01:02.123] with format [yyyy-MM-dd'T'HH:mm:ss||date_optional_time]: [Text '2014-06-06T12:01:02.123' could not be parsed, unparsed text found at index 19]",
        "stack_trace" : "ElasticsearchParseException[failed to parse date field [2014-06-06T12:01:02.123] with format [yyyy-MM-dd'T'HH:mm:ss||date_optional_time]: [Text '2014-06-06T12:01:02.123' could not be parsed, unparsed text found at index 19]]; nested: DateTimeParseException[Text '2014-06-06T12:01:02.123' could not be parsed, unparsed text found at index 19];\r\n\tat org.elasticsearch.common.time.JavaDateMathParser.parseDateTime(JavaDateMathParser.java:233)\r\n\tat org.elasticsearch.common.time.JavaDateMathParser.parse(JavaDateMathParser.java:75)\r\n\tat org.elasticsearch.search.DocValueFormat$DateTime.parseLong(DocValueFormat.java:229)\r\n\tat org.elasticsearch.search.aggregations.bucket.histogram.ExtendedBounds.parseAndValidate(ExtendedBounds.java:156)\r\n\tat org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramAggregationBuilder.innerBuild(DateHistogramAggregationBuilder.java:455)\r\n\tat org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:315)\r\n\tat org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:39)\r\n\tat org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:139)\r\n\tat org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:333)\r\n\tat org.elasticsearch.search.SearchService.parseSource(SearchService.java:800)\r\n\tat org.elasticsearch.search.SearchService.createContext(SearchService.java:607)\r\n\tat org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:582)\r\n\tat org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:385)\r\n\tat org.elasticsearch.search.SearchService.access$100(SearchService.java:123)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:357)\r\n\tat org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:353)\r\n\tat org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1068)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)\r\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)\r\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:834)\r\nCaused by: java.time.format.DateTimeParseException: Text '2014-06-06T12:01:02.123' could not be parsed, unparsed text found at index 19\r\n\tat java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2049)\r\n\tat java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1874)\r\n\tat org.elasticsearch.common.time.JavaDateMathParser.parseDateTime(JavaDateMathParser.java:223)\r\n\t... 23 more\r\n"
      }
    ],
```

Specifying only

```json
    "format": "date_optional_time",
```

Results in no error however.

### PR DESCRIPTION
**Pull request by pgomulka**
Java-time fails parsing composite patterns when first pattern matches
only the prefix of the input. It expects pattern in longest-shortest
order.
Joda does not suffer from this

Closes #39916

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/joda/JodaDateFormatter.java [hunk 1]
```diff
@@ -51,6 +52,15 @@ public TemporalAccessor parse(String input) {
         return ZonedDateTime.ofInstant(Instant.ofEpochMilli(dt.getMillis()), DateUtils.dateTimeZoneToZoneId(dt.getZone()));
     }
 
+    /**
+     * Joda allways succeds when parsing with composite optional patterns
+     * @return true
+     */
+    @Override
+    public boolean tryParseUnresolved(String input) {
```
Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/common/joda/JodaDateFormatter.java]: It is not best design to have this method also applying for joda
It is tempting to only use this approach in JavaDateFormatter, but that would mean that java formatters (used by default now) would always parse twice (parseUnresolved then parse). I suspect that most patterns are not composite so it would be a huge performance drop.

With this the parsing is done twice only when using composite patterns

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java [hunk 2]
```diff
@@ -1585,7 +1585,7 @@ static JavaDateFormatter merge(String pattern, List<DateFormatter> formatters) {
             if (printer == null) {
                 printer = javaDateFormatter.getPrinter();
             }
-            dateTimeFormatters.add(javaDateFormatter.getParser());
+            dateTimeFormatters.addAll(javaDateFormatter.getParsers());
```
Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: not a fan of this merge method. It extracts relatively low level `java.time.DateTimeFormatter` when it should stick with `org.elasticsearch.common.time.DateFormatter` abstraction as long as possible. 
Possibly the roundUpBuilder should also be used inside `JavaDateFormatter constructor`?

also I suspect that roundUpBuilder will suffer from the same problem when it is a composite?

**Comment by pgomulka** [comment]
this change is a bit slower. I think we could optimize by continuing on the result of parseUnresolved, but this would reduce readability.

on my laptop on this PR branch:
```
# Run complete. Total time: 00:02:05

Benchmark                             Mode  Cnt     Score    Error  Units
DateFormatterBenchmark.parseJavaDate  avgt   30   923.107 ± 31.714  ns/op
DateFormatterBenchmark.parseJodaDate  avgt   30  1001.870 ± 29.654  ns/op
```

vs on master
```
# Run complete. Total time: 00:02:05

Benchmark                             Mode  Cnt     Score    Error  Units
DateFormatterBenchmark.parseJavaDate  avgt   30   807.209 ± 10.100  ns/op
DateFormatterBenchmark.parseJodaDate  avgt   30  1023.225 ± 61.066  ns/op
```

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java (hunk 2 above)
Comment (danielmitterdorfer) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: > not a fan of this merge method. It extracts relatively low level java.time.DateTimeFormatter when it should stick with org.elasticsearch.common.time.DateFormatter abstraction as long as possible.

Maybe we can refactor this in a separate PR then? Also, this code should only be there temporary? As soon as we get rid of Joda time in the code base, I expect that we can get rid of quite a few abstractions.

> I suspect that roundUpBuilder will suffer from the same problem when it is a composite?

Is it intended to be used as a composite?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 3]
```diff
@@ -79,36 +75,31 @@ private JavaDateFormatter(String format, DateTimeFormatter printer, DateTimeForm
         }
         this.printer = printer;
         this.format = format;
+
         if (parsers.length == 0) {
-            this.parser = printer;
-        } else if (parsers.length == 1) {
-            this.parser = parsers[0];
+            this.parsers = Arrays.asList(printer);
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: Use `Collections.singletonList()` instead?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 4]
```diff
@@ -122,30 +113,66 @@ public TemporalAccessor parse(String input) {
...
+    private boolean tryParseUnresolved(DateTimeFormatter formatter, String input) {
+        try {
+            ParsePosition pp = new ParsePosition(0);
+            formatter.parseUnresolved(input, pp);
+            int len = input.length();
+            if (pp.getErrorIndex() == -1 && pp.getIndex() == len) {
+                return true;
+            }
+        } catch (RuntimeException ex) {
+            // should not happen, but ignore if it does
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: In which cases could this happen? I wonder whether we should really be lenient about it?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 5]
```diff
@@ -122,30 +113,66 @@ public TemporalAccessor parse(String input) {
...
         }
 
-        return new JavaDateFormatter(format, printer.withZone(zoneId), roundupParser.withZone(zoneId), parser.withZone(zoneId));
+        return new JavaDateFormatter(format, printer.withZone(zoneId),
+            parsers.stream().map(p->p.withZone(zoneId)).toArray(size->new DateTimeFormatter[size]));
     }
 
     @Override
     public DateFormatter withLocale(Locale locale) {
+        //TODO not sure that we can keep that shortcut, and the one above
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: probably not because previously we had a common locale for the composite parser and now it is possible that each one has a different locale (not sure whether we should allow this though and throw an `IllegalArgumentException` in the constructor if that it is the case?) Also, we should probably still keep this optimization in case we only have one parser I think

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java [hunk 6]
```diff
@@ -46,11 +47,11 @@
  */
 public class JavaDateMathParser implements DateMathParser {
 
-    private final DateTimeFormatter formatter;
-    private final DateTimeFormatter roundUpFormatter;
-    private final String format;
+    private  JavaDateFormatter formatter;
```
Comment (danielmitterdorfer) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: Can we please declare all fields as `final` again?

**Review by danielmitterdorfer — COMMENTED** [review]
I left a couple of suggestions.

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java (hunk 2 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: > Is it intended to be used as a composite?

 It is used as a composite in the `merge` method when constructing the roundUpParser with the `appendOptional`. 
I can imagine we can have the same pattern as on the issue (`yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd'T'HH:mm:ss.SSS`) but used with this parser. Will try to come up with a testcase

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 4 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: the `DateTimeFOormatter.parseUnresolved` can throw some RuntimeExceptions

>  * @throws DateTimeException if some problem occurs during parsing
>   * @throws IndexOutOfBoundsException if the position is invalid

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 7]
```diff
@@ -122,30 +113,64 @@ public TemporalAccessor parse(String input) {
...
     public DateFormatter withLocale(Locale locale) {
         // shortcurt to not create new objects unnecessarily
-        if (locale.equals(parser.getLocale())) {
+        if (locale.equals(firstParser().getLocale())) {
             return this;
         }
 
-        return new JavaDateFormatter(format, printer.withLocale(locale), roundupParser.withLocale(locale), parser.withLocale(locale));
+        return new JavaDateFormatter(format, printer.withLocale(locale), roundupParser.withLocale(locale),
+            firstParser().withLocale(locale));
```
[the remark this answers is not in the document]
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: this was an old code. I must have updated this when you were reviewing. Should be fixed now

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 5 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: agree. I don't think we have a code were we define composite formatters with different `Locale`
We could also refactor this into verifying all parsers having the same `Locale` or `Zone` before returning this.

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 4 above)
Comment (danielmitterdorfer) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: Ok, makes sense.

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 8]
```diff
@@ -122,30 +114,64 @@ public TemporalAccessor parse(String input) {
...
 
+    private TemporalAccessor doParse(String input) {
+        if (parsers.size() > 1) {
+            for (DateTimeFormatter formatter : parsers) {
+                if (tryParseUnresolved(formatter, input) == true) {
+                    return formatter.parse(input);
+                }
+            }
+        }
+        return firstParser().parse(input);
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: is this doing a second parse attempt with the first parser, if going through all the parsers did not work?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 9]
```diff
@@ -122,30 +114,64 @@ public TemporalAccessor parse(String input) {
...
         try {
-            return parser.parse(input);
+            return doParse(input);
         } catch (DateTimeParseException e) {
             throw new IllegalArgumentException("failed to parse date field [" + input + "] with format [" + format + "]", e);
         }
     }
 
+    private TemporalAccessor doParse(String input) {
+        if (parsers.size() > 1) {
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: this could be statically initialized in the ctor?

Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: the result of `parsers.size() > 1` ? like a flag `isCompositeParser` ? I think this is not needed (probably won't give any performance gain) maybe just a method for this expression?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 8 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: yes, I guess we could throw an exception after the loop. WDYT?

Comment (spinscale) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: or just be sure via ctor check, that the size is never `0`? maybe just use an array instead of an array list, than the below check would always be a fixed size check as well?

Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: It should never be 0, if no parsers are provided, the printer will be used.
The only reason for this >1 check is to at least when there is only one parser (the regular, not composite pattern) it is not parsing the input twice.

Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: as discussed, will add an exception indicating that all parsers has failed. This won't mislead that the first parser failed (as it is at the moment)

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 9 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: since the complexity of the size() is expected to be constant in the implementation used here, I will leave this as it is.

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java (hunk 2 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatters.java]: I discussed that with @spinscale and there is no way we could create a pattern that would suffer from the same problem.
For index name calculations like `prefix-{2010-01-01/d{yyyy-MM-dd||yyyy-MM-ddTHH}}` it would fail parsing, as the only thing expected after `|` is the timezone (it would fail saying unexpected `|`)

**Comment by pgomulka** [comment]
@elasticmachine ok to test

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 10]
```diff
@@ -122,30 +114,65 @@ public TemporalAccessor parse(String input) {
...
+            for (DateTimeFormatter formatter : parsers) {
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: We should not do this. It is exactly what we got rid of that caused massive performance degradation when using java time vs joda. I think we should fail when parsing the format if there is ambiguity.

Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: I can't exactly agree if there really is ambiguity. If there is a composite pattern where the first pattern is a prefix of the second pattern (as in the example from the issue) then only the second one is really matching the date format.
This is the way it used to work in joda and we could support this. 

It would be hard to explain in our doc why we forbid patterns like the one from the issue. Java-time javadoc does not mention this limitation.

There is obviously a performance drop (~14%), not sure if this is still acceptable. Will run Rally benchmarks later.

@polyfractal @Mpdreamz what are your views on this?

Comment (polyfractal) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: No real opinion on implementation details, but I do think it's a huge breaking change if we can't support the old multi-format behavior. Even ignoring what we've supported in the past, `yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd'T'HH:mm:ss.SSS` doesn't seem ambiguous/wrong/incorrect if you have both formats in your data.  

And situations like `yyyy-MM-dd'T'HH:mm:ss||date_optional_time` might be technically redundant but due to our naming scheme it's not clear to the user what's going on.

And I'm sure there are thousands of legacy templates with patterns like those that will break on upgrade.

Wasn't the original performance issues due to throwing and catching exceptions as control-flow, rather than trying multiple parsers?

Comment (danielmitterdorfer) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: I agree with @polyfractal: The root cause of the performance regression (https://github.com/elastic/elasticsearch/issues/36602) was not that multiple parsers have been applied but rather that each of them has thrown an `IllegalArgumentException` on mismatch. I think dropping support for multiple date patterns is not an option.

**Comment by pgomulka** [comment]
I have run rally for this PR and master on my CI box. Looks like the performance drop is around 8%
Before: median indexing throughput ~ 135656 docs/s
After: median indexing throughput ~ 124919 docs/s
command used on master:
```
esrally --runtime-jdk=8 --car="4gheap" --pipeline=from-sources-complete --revision=3eb9736f7f247f715868f94a8a00edf1a167cef3 --track=http_logs --challenge=append-no-conflicts-index-only
```
full results on master: https://gist.github.com/pgomulka/e1a0b83d3684fa8a1904a6ec37792ed7

command used on PR revision:
```
esrally --runtime-jdk=8 --car="4gheap" --pipeline=from-sources-complete --revision=09c12850ef7dc575667184fc3459be4b086921a1 --track=http_logs --challenge=append-no-conflicts-index-only
```
full results on PR revision: https://gist.github.com/pgomulka/7e9a032959f1cfeb16c73c39389a214c

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 10 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: I have refactored this method to use `DateTimeFormatter.format.parseObject`. The implementation in `DateTimeFormatter::ClassicFormat` is returning null when parsing failed. This has the same complexity as the approach currently in master. `DateTimeFormatterBuilder:2349` is also iterating within enclosed optionals in a loop (but has this downside of returning when input is fully consumed)
see the results of Rally and microbenchmark on this PR #40364. These look very promising to me.

**Comment by pgomulka** [comment]
I have rerun Rally for this PR and master. Looks like performance drop for the approach with `parseObject` is around 5%. Not entirely convinced by these numbers, it looked better on the previous run here #40364
Master: Median Throughput | index-append |    138242 | docs/s |
This PR:  Median Throughput | index-append |    130833 | docs/s |

command used on master:
```
esrally --runtime-jdk=8 --car="4gheap" --pipeline=from-sources-complete --revision=2c825fddf1116c8886f37c02245d61b2b2e99845 --track=http_logs --challenge=append-no-conflicts-index-only 
 ```

command used on PR revision:
```
esrally --runtime-jdk=8 --car="4gheap" --pipeline=from-sources-complete --revision=1126ed11249e6ed41d1c0fcb4ae1a18bd3dd1fb1 --track=http_logs --challenge=append-no-conflicts-index-only
```

full results https://gist.github.com/pgomulka/9cd58fcc055d12dda756eee3eaab73fa

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 11]
```diff
@@ -122,30 +115,50 @@ public TemporalAccessor parse(String input) {
...
+                if (parsingSucceeded(object, input, pos) == true) {
+                    return (TemporalAccessor) object;
+                }
+            }
+            throw new DateTimeParseException("Failed to parse with all enclosed parsers", input, 0);
+        }
+        return firstParser().parse(input);
+    }
+
+    private boolean parsingSucceeded(Object object, String input, ParsePosition pos) {
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: this is only used once. it might be more readable to just have a boolean

```
boolean isParsingSuccessful = object != null && pos.getIndex() == input.length();
```

in the other method?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 12]
```diff
@@ -79,36 +77,31 @@ private JavaDateFormatter(String format, DateTimeFormatter printer, DateTimeForm
...
+        DateTimeFormatter roundupFormatter = builder.toFormatter(firstParser().getLocale());
         if (printer.getZone() != null) {
             roundupFormatter = roundupFormatter.withZone(printer.getZone());
         }
         this.roundupParser = roundupFormatter;
     }
 
-    DateTimeFormatter getRoundupParser() {
-        return roundupParser;
+    private DateTimeFormatter firstParser() {
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: Personal opinion: I dislike this method somehow. There are alternatives whenever this method is called (using `zone()` or `locale()` directly, and calling `this.parsers.get(0)` directly for the rest.

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java [hunk 13]
```diff
@@ -215,20 +216,20 @@ private Instant parseDateTime(String value, ZoneId timeZone, boolean roundUpIfNo
...
+                TemporalAccessor accessor = formatter.apply(value);
                 ZoneId zoneId = TemporalQueries.zone().queryFrom(accessor);
                 if (zoneId != null) {
                     timeZone = zoneId;
                 }
 
                 return DateFormatters.from(accessor).withZoneSameLocal(timeZone).toInstant();
             }
-        } catch (DateTimeParseException e) {
+        } catch (IllegalArgumentException | DateTimeParseException e) {
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: is this still needed?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java [hunk 14]
```diff
@@ -46,11 +47,11 @@
  */
 public class JavaDateMathParser implements DateMathParser {
 
-    private final DateTimeFormatter formatter;
+    private final JavaDateFormatter formatter;
     private final DateTimeFormatter roundUpFormatter;
     private final String format;
 
-    JavaDateMathParser(String format, DateTimeFormatter formatter, DateTimeFormatter roundUpFormatter) {
+    JavaDateMathParser(String format, JavaDateFormatter formatter, DateTimeFormatter roundUpFormatter) {
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: why this change?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 15]
```diff
@@ -122,30 +115,50 @@ public TemporalAccessor parse(String input) {
         }
 
         try {
-            return parser.parse(input);
+            return doParse(input);
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: I think a huge comment here would be warranted what happens here and why?

**Review by spinscale — COMMENTED** [review]
I left a couple of comments, I'm running the rally tests ATM on my bare metal system

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 11 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: it is used once, but my intention was to hide the implementation details and this expression in the other method

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java (hunk 14 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: the intention was to allow alternatives in patterns for date math calculations. 
We already discussed this and we do not need this. 
I think that in this case I will revert this change and create  with `JavaDateMathParser(firstParser,getRoundUpFormatter)`

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java (hunk 13 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: not needed as will revert back this class

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 15 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: absolutely, will add

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 12 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: my intention was to avoid having repetitive calls of `this.parsers.get(0)`. 
But I see your point that we could use alternatives. Does this mean that `zone()` and `locale()` is always guaranteed  to be the same across `printer` and all `parsers`?

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 16]
```diff
@@ -121,6 +117,14 @@ public TemporalAccessor parse(String input) {
         }
     }
 
+    /**
+     * Attempt parsing the input without throwing exception. This is needed because java-time requires ordering on optional (composite)
+     * patterns. Joda does not suffer from this.
+     * https://bugs.openjdk.java.net/browse/JDK-8188771
+     *
+     * @param input An arbitrary string resembling the string representation of a date or time
+     * @return true if parsing was successful, false if parsing failed
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: this method is not returning a boolean

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 12 above)
Comment (spinscale) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: see the ctor check for distinct locale and distinct zone

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 17]
```diff
@@ -122,30 +111,58 @@ public TemporalAccessor parse(String input) {
...
+     */
+    private TemporalAccessor doParse(String input) {
+        if (parsers.size() > 1) {
+            for (DateTimeFormatter formatter : parsers) {
+                ParsePosition pos = new ParsePosition(0);
+                Object object = formatter.toFormat().parseObject(input, pos);
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: there is no need to call `formatter.toFormat()` with every invocation, this could even be done in the ctor, right?

**Comment by spinscale** [comment]
I ran this branch with rally 1.0.4 with the above parameters on my bare metal node... there were no real differences in my two runs

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java (hunk 14 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: actually this should stay. There is plenty of tests that started to fail now because of that.
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/10768/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/10640/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/2575/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/13976/

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 16 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: yes sorry, that was a copypaste from previous rev. Fixed with more description

File: server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java (hunk 13 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateMathParser.java]: Actually needed - see this https://github.com/elastic/elasticsearch/pull/40100#discussion_r268811919

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 17 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: you mean keeping a `Collection<Format>` and refactoring all usages of `DateTimeFormatter`to be a usages of `Format` ? 
Having a field of type `Format` could be misleading that any `Format` implementation can be used. Whereas it is `DateTimeFormatter.ClassicFormat` that we depend on.
I thin it would be better to stick with DateTimeFormat across the class (we use this class anyway for `printer` and`roundUpBuilder`) and only use `Format` as a implementation details.

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by pgomulka** [comment]
also @danielmitterdorfer  has run a 5iteration Rally tests on a dedicated performance machines. The results are good. Left is master, right is the revision from this PR
```
|                                                Min Throughput | index-append |     124665 |      122687 | -1977.97 | docs/s |
|                                             Median Throughput | index-append |     145543 |      152531 |  6988.05 | docs/s |
|                                                Max Throughput | index-append |     206089 |      210828 |  4738.77 | docs/s |
```

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java (hunk 17 above)
Comment (spinscale) [reply server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: I'd consider this optimization optional for now.

File: server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java [hunk 18]
```diff
@@ -122,30 +111,62 @@ public TemporalAccessor parse(String input) {
...
         } catch (DateTimeParseException e) {
             throw new IllegalArgumentException("failed to parse date field [" + input + "] with format [" + format + "]", e);
         }
     }
 
+    /**
+     * Attempt parsing the input without throwing exception. If multiple parsers are provided,
+     * it will continue iterating if the previous parser failed. The pattern must fully match, meaning whole input was used.
+     *
+     * The approach with collection of parsers was taken because java-time requires ordering on optional (composite)
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/JavaDateFormatter.java]: minor nit: maybe also mention that you dont want to catch any exceptions or have any exceptions thrown due to performance reasons?

**Review by spinscale — APPROVED** [review]
Given that the performance is the same and the bug is fixed, I think this is good to go, the rest of my comments was merely subjective code style and and can be freely ignored.

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/bwc

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java [hunk 19]
```diff
@@ -343,6 +343,17 @@ public void testDuellingFormatsValidParsing() {
         assertSameDate("2012-W1-1", "weekyear_week_day");
     }
 
+    public void testCompositeParsing(){
+        //in all these examples the second pattern will be used
+        assertSameDate("2014-06-06T12:01:02.123", "yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd'T'HH:mm:ss.SSS");
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: I think we need some more tests:
* 3 patterns
* random ordering of many patterns

**Review by rjernst — COMMENTED** [review]
Sorry for the late review here. I just have one ask for ensuring this works in all cases.

File: server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java (hunk 19 above)
Comment (pgomulka) [reply server/src/test/java/org/elasticsearch/common/joda/JavaJodaTimeDuellingTests.java]: Happy to add more test cases. Do you have anything specific in mind? 
It won't harm adding testcases with 3 patterns, but I am not convinced we need a random ordering here. What scenario would it cover?
