### PR TITLE
Fix upgrading indices which use a custom similarity plugin.

### LINKED ISSUE #25350: Upgrading an index using a custom similarity fails
**Elasticsearch version**: 5.1.1 - 5.4.1

**Plugins installed**: [analysis-icu, elasticsearch-position-similarity]

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (IcedTea 3.4.0) (suse-10.10.3-x86_64)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux oviken 4.4.36-8-default #1 SMP Fri Dec 9 16:18:38 UTC 2016 (3ec5648) x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Upgrading an index using a custom similarity fails in org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility with the exception "Unknown Similarity type". If the old and the new elasticserver have the same custom similarity installed, upgrading should work.

Looking at the code, it is no surprise that this does not work, as checkMappingsCompatibility creates a SimilarityService with an empty list of additional similarities. It seems something akin to the fake analyzerMap is necessary for custom similarities?

This is a follow up to https://discuss.elastic.co/t/upgrading-index-with-custom-similarity-not-working/76678 as by now I'm quite sure this is a bug with elasticsearch an not with my similarity plugin.

**Steps to reproduce**:

 1. Start elasticsearch version 5.1.1 with https://github.com/sdauletau/elasticsearch-position-similarity installed (I've attached the exact zip I build and used)
[elasticsearch-position-similarity-5.1.1.zip](https://github.com/elastic/elasticsearch/files/1094449/elasticsearch-position-similarity-5.1.1.zip)

 2. Create an index using this similarity:
```
curl -s -XPUT "http://localhost:9200/test_index" -d '
{
  "settings": {
    "similarity": {
      "positionSimilarity": {
        "type": "position-similarity"
      }
    }
  }
}'
```

 3. Stop elasticsearch, upgrade to 5.1.2, install the same plugin for this version (I again attached the zip I used)
[elasticsearch-position-similarity-5.1.2.zip](https://github.com/elastic/elasticsearch/files/1094446/elasticsearch-position-similarity-5.1.2.zip)

4. Start elasticsearch again

**Provide logs (if relevant)**:

[elasticsearch.txt](https://github.com/elastic/elasticsearch/files/1094451/elasticsearch.txt)

https://gist.github.com/xabbu42/66dd46bd3cc15244cede8ceadf884fd8

### PR DESCRIPTION
**Pull request by xabbu42**
Use a fake similarity map that always returns a value in  MetaDataIndexUpgradeService.checkMappingsCompatibility instead of an empty map.

Closes #25350

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 1]
```diff
@@ -136,7 +137,24 @@ private void checkMappingsCompatibility(IndexMetaData indexMetaData) {
...
+
+                @Override
+                public SimilarityProvider.Factory get(Object key) {
+                    assert key instanceof String : "key must be a string but was: " + key.getClass();
+                    return SimilarityService.BUILT_IN.get(SimilarityService.DEFAULT_SIMILARITY);
+                }
+
+                @Override
+                public Set<Entry<String, SimilarityProvider.Factory>> entrySet() {
+                    return Collections.emptySet();
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I realize the analyzer hack does this, but it is inconsistent with what is returned above. I would rather throw a UEO here so that if entrySet begins to be used, we will catch this rather than get weird behavior. (And we should, in a followup or in this PR, fix the other entrySet() impl as well).

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 2]
```diff
@@ -136,7 +137,24 @@ private void checkMappingsCompatibility(IndexMetaData indexMetaData) {
             // We cannot instantiate real analysis server at this point because the node might not have
             // been started yet. However, we don't really need real analyzers at this stage - so we can fake it
             IndexSettings indexSettings = new IndexSettings(indexMetaData, this.settings);
-            SimilarityService similarityService = new SimilarityService(indexSettings, null, Collections.emptyMap());
+            final Map<String, SimilarityProvider.Factory> similarityMap = new AbstractMap<String, SimilarityProvider.Factory>() {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I would add a comment here that having a dummy map works because we assume any similarity providers were known before the upgrade, so allowing any key below is ok.

**Review by rjernst — CHANGES_REQUESTED** [review]
Looks good. I have two small requests.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 2 above)
Comment (xabbu42) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I did test the patch with a elasticsearch server without the custom similarity installed. The server starts but does not recover the index with an appropriate error message. I did not test restoring a snapshot from an old version. But as far as I understand the situation, we do not assume all used similarities are actually known here, but just defer the error to a point when we actually know all available similarities.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 1 above)
Comment (xabbu42) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I can do that but need to know what an UEO is (I'm not a Java programmer).

Comment (jasontedor) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: @xabbu42 I think that @rjernst meant `UOE` as in `UnsupportedOperationException`.

Comment (rjernst) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Yes, Jason is correct on what I meant.

Comment (xabbu42) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I get test failures if make this change:

```
Suite: org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeServiceTests
  1> [2017-10-14T16:43:29,230][INFO ][o.e.c.m.MetaDataIndexUpgradeServiceTests] [testPluginUpgradeFailure]: before test
  1> [2017-10-14T16:43:29,233][INFO ][o.e.c.m.MetaDataIndexUpgradeServiceTests] [testPluginUpgradeFailure]: after test
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=67F6816A4DF09ADB -Dtests.class=org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeServiceTests -Dtests.method="testPluginUpgradeFailure" -Dtests.security.manager=true -Dtests.locale=sr -Dtests.timezone=Asia/Katmandu
FAILURE 0.03s | MetaDataIndexUpgradeServiceTests.testPluginUpgradeFailure <<< FAILURES!
   > Throwable #1: org.junit.ComparisonFailure: expected:<[unable to upgrade the mappings for the index [[foo/BOOM]]]> but was:<[Cannot upgrade index foo]>
   >    at __randomizedtesting.SeedInfo.seed([67F6816A4DF09ADB:37D52F4B7D45621E]:0)
   >    at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeServiceTests.testPluginUpgradeFailure(MetaDataIndexUpgradeServiceTests.java:141)
   >    at java.lang.Thread.run(Thread.java:748)
  1> [2017-10-14T16:43:29,258][INFO ][o.e.c.m.MetaDataIndexUpgradeServiceTests] [testPluginUpgrade]: before test
  1> [2017-10-14T16:43:29,263][INFO ][o.e.c.m.MetaDataIndexUpgradeServiceTests] [testPluginUpgrade]: after test
```

**Comment by xabbu42** [comment]
Just to be clear, I'm waiting on further input here for both the requested changes.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 2 above)
Comment (rjernst) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Defer is what I meant by "assume". We allow any similarity name to be looked up without error. We don't actually use it, we just need to ensure the lookup does not fail. This is ok because we assume whatever was present when ES last shut down had all known similarities.

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 1 above)
Comment (rjernst) [reply core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I think this happens because `IndexAnalyzers` iterates over the analyzers/normalizers when in `close()`. Go ahead and add back the empty map, but please add a comment noting the reason?

**Comment by rjernst** [comment]
@xabbu42 Sorry for the delayed response. Could you please update this PR as per the new comments?

**Comment by xabbu42** [comment]
@rjernst no problem, I just wanted to make sure nobody is waiting on me. I hope the updated PR is ok now.

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by xabbu42** [comment]
Ups sorry about that, its fixed now.

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@elasticmachine test this please

**Review by rjernst — APPROVED** [review]

**Comment by rjernst** [comment]
Thanks @xabbu42
