### PR TITLE
ESQL: adds Enrich implicit match_fields to field_caps call

### LINKED ISSUE #101328: ESQL: STATS after ENRICH without KEEP does not work
@abdonpijpelink ran into an error using STATS BY on an enrich field. Unless explicitly adding KEEP on the enrich policy's match field before the STATS...BY, the match field seems to be projected out.

Consider the following example using the Kibana sample web log data set.

```
PUT countries/_bulk
{ "index" : {}}
{ "geo.dest": "US", "country_name": "United States of America" }
{ "index" : {}}
{ "geo.dest": "IN", "country_name": "India" }
{ "index" : {}}
{ "geo.dest": "CN", "country_name": "China" }

PUT /_enrich/policy/countries
{
  "match": {
    "indices": "countries",
    "match_field": "geo.dest",
    "enrich_fields": ["country_name"]
  }
}

PUT /_enrich/policy/countries/_execute

# Not allowed
POST _query?format=txt
{
  "query": """
FROM kibana_sample_data_logs
| ENRICH countries
| STATS total_bytes = SUM(bytes) BY country_name
| SORT total_bytes DESC
| LIMIT 3
  """
}

# Allowed without STATS...BY
POST _query?format=txt
{
  "query": """
FROM kibana_sample_data_logs
| ENRICH countries
  """
}

# Allowed, if I use KEEP
POST _query?format=txt
{
  "query": """
FROM kibana_sample_data_logs
| KEEP bytes, geo.dest
| ENRICH countries
| STATS total_bytes = SUM(bytes) BY country_name
| SORT total_bytes DESC
| LIMIT 3
  """
}

# Pushing back ENRICH works too
POST _query?format=txt
{
  "query": """
FROM kibana_sample_data_logs
| STATS total_bytes = SUM(bytes) BY geo.dest
| SORT total_bytes DESC
| LIMIT 3
| ENRICH countries
  """
}
```

The error returned is
```
{
  "error": {
    "root_cause": [
      {
        "type": "verification_exception",
        "reason": """Found 1 problem
line 3:3: Unknown column [geo.dest]"""
      }
    ],
    "type": "verification_exception",
    "reason": """Found 1 problem
line 3:3: Unknown column [geo.dest]"""
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by astefan**
This change adds the ENRICH `match_field`s to the field_caps call performed while resolving the index pattern. This addresses scenarios where the match_fields are not explicitly called for in the query and when the index pattern resolution will not use all fields (`*`). A query of the type `from test | enrich countries | keep country_name` doesn't use `ENRICH ... ON ...` (so the field name is not explicitly mentioned) and also asks for a specific field name (thus not using `*` during index pattern resolution).

Fixes https://github.com/elastic/elasticsearch/issues/101328

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -522,11 +522,7 @@ private LogicalPlan resolveEnrich(Enrich enrich, List<Attribute> childrenOutput)
                 }
                 if (resolved.resolved() && resolved.dataType() != KEYWORD) {
                     resolved = ua.withUnresolvedMessage(
-                        "Unsupported type ["
-                            + resolved.dataType()
-                            + "]  for enrich matching field ["
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:527]: Removed unnecessary whitespace.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 2]
```diff
@@ -159,14 +178,45 @@ private <T> void preAnalyze(LogicalPlan parsed, BiFunction<IndexResolution, Enri
...
+        EnrichResolution enrichResolution,
+        Set<String> fieldNames,
+        ActionListener<T> listener
+    ) {
+        ActionListener<Void> groupedListener = listener.delegateFailureAndWrap((l, unused) -> {
+            assert enrichResolution.resolvedPolicies().size() == policyNames.size()
+                : enrichResolution.resolvedPolicies().size() + " != " + policyNames.size();
+            var matchFields = enrichResolution.resolvedPolicies()
+                .stream()
+                .filter(p -> p.index().isValid())
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:201]: The enrich policy maybe cannot be found, thus the check here. But not doing anything here, so that the Verifier catches the missing policy and report it appropriately.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java [hunk 3]
```diff
@@ -142,6 +142,7 @@
 public class CsvTests extends ESTestCase {
 
     private static final Logger LOGGER = LogManager.getLogger(CsvTests.class);
+    private static final String IGNORED_CSV_FILE_NAMES_PATTERN = "-IT_tests_only";
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java:145]: Nothing to do with the fix in this PR, but I believe these field names are more clear like this. `-ignoreCsvTests` were suggesting imo that the whole file is ignored in all test suites. In fact, those fields are ignored in CSV unit tests only.

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Review by luigidellaquila — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 4]
```diff
@@ -151,6 +151,25 @@ private <T> void preAnalyze(LogicalPlan parsed, BiFunction<IndexResolution, Enri
...
         Set<String> policyNames = new HashSet<>(preAnalysis.policyNames);
         EnrichResolution resolution = new EnrichResolution(ConcurrentCollections.newConcurrentSet(), enrichPolicyResolver.allPolicyNames());
+        var fieldNames = fieldNames(parsed);
+
+        if (fieldNames == IndexResolver.ALL_FIELDS) {
+            // we don't need the enrich policies match_fields names BEFORE resolving the indices, because all fields are requested anyway
+            preAnalyzeConcurrently(parsed, action, policyNames, resolution, fieldNames, listener);
+        } else {
+            // first we need the match_fields names from enrich policies and THEN, with an updated list of fields, we call field_caps API
+            preAnalyzeSequentially(parsed, action, policyNames, resolution, fieldNames, listener);
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:161]: Resolving enrich policies should be trivial since it occurs on the local node with a minimal computation. I think it's better to keep only the sequential version. I think we made it concurrent because it was more convenience rather than necessity.

**Review by dnhatn — APPROVED** [review]
I left a comment, but LGTM. Thanks Andrei.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java (hunk 4 above)
Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java]: Thanks @dnhatn. I've made it sequential.
