### PR TITLE
Fix testRestoreIncreasesPrimaryTerms on 6.x

### LINKED ISSUE #38223: testRestoreIncreasesPrimaryTerms fails on 6.x
I can reproduce this locally with the following command.

```
./gradlew :server:integTest \
  -Dtests.seed=8E0D4395046AC9E0 \
  -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT \
  -Dtests.method="testRestoreIncreasesPrimaryTerms" \
  -Dtests.security.manager=true \
  -Dtests.locale=el \
  -Dtests.timezone=Pacific/Tahiti \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
AILURE 2.48s | SharedClusterSnapshotRestoreIT.testRestoreIncreasesPrimaryTerms <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: <4L>
   >      but: was <5L>
   >    at __randomizedtesting.SeedInfo.seed([8E0D4395046AC9E0:46EF6D1E229D6B72]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testRestoreIncreasesPrimaryTerms(SharedClusterSnapshotRestoreIT.java:3746)
   >    at java.lang.Thread.run(Thread.java:748)
```

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1325/console

Relates #38177

### PR DESCRIPTION
**Pull request by tlrx**
In 6.x the open index request does not wait for shards to be active and
returns immediately. In this specific test, we want to capture the
values of the primary terms before the snapshot and restore and if it
does not wait for shard to be active the captured values might not be
up to date.

Closes #38223

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 1]
```diff
@@ -3719,7 +3718,7 @@ public void testRestoreIncreasesPrimaryTerms() {
             // open and close the index to increase the primary terms
             for (int i = 0; i < randomInt(3); i++) {
                 assertAcked(client().admin().indices().prepareClose(indexName));
-                assertAcked(client().admin().indices().prepareOpen(indexName));
+                assertAcked(client().admin().indices().prepareOpen(indexName).setWaitForActiveShards(ActiveShardCount.DEFAULT));
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: let's specify `ActiveShardCount.ONE` here to be explicit

**Review by ywelsch — APPROVED** [review]

**Comment by tlrx** [comment]
Thanks @ywelsch
