### PR TITLE
Fix Broken Index Shard Snapshot File Preventing Snapshot Creation

### LINKED ISSUE #41304: Repository with Broken Shards' index-N File Can't Create New Snapshots
Due to some bug that I'll track down here, we were (and maybe still are) writing duplicate JSON keys into snapshot shards' `index-N` blobs. This leads to those blobs not being read correctly, which makes it impossible to create further snapshots for a shard with such a broken `index-N` blob.

This was technically triggered by making the JSON parser throw on this kind of data in https://github.com/elastic/elasticsearch/pull/22073 most likely.

-----------------------------

* We need to fix writing broken JSON here if it still happens
* We need to harden the logic here to be able to deal with this kind of broken `index-N` blob to get repositories out of this broken state.

### PR DESCRIPTION
**Pull request by original-brownbear**
* The problem here is that if we run into a corrupted index-N file, instead of generating a new index-(N+1) file, we instead set the newest index generation to -1 and thus tried to create `index-0`
   * If `index-0` is corrupt, this prevents us from ever creating a new snapshot using the broken shard, because we are unable to create `index-0` since it already exists
   * Fixed by still using the index generation for naming the next index file, even if it was a broken index file
* Added assertion preventing us from writing a duplicate snapshot entry shard index file to prevent the exact breakage that lead to #41304 (duplicate snapshot names in the shard index file)
* Added test that makes sure restoring as well as snapshotting on top of the broken shard index file work as expected
* closes #41304

### CODE REVIEW

**Comment by original-brownbear** [comment]
@paulcoghlan fyi :)

**Comment by andrershov** [comment]
@original-brownbear In the description, you're referring to `index-N` files, however, `index-N` files are for global metadata about the snapshots. Index files for the shards are called `list-N` according to `BlobStoreRepository` javadoc. Can you please update the description of the PR and related issue, because not it's not easy to understand what you're talking about.

**Comment by original-brownbear** [comment]
@andrershov fixed in https://github.com/elastic/elasticsearch/pull/41310/commits/b0f13b5aece23855be7fb21af8db7037af1d0fc5 (sadly the Javadoc is wrong and we use `index-` in both spots creating the maximum amount of confusion)

**Comment by andrershov** [comment]
@original-brownbear Javadoc still looks confusing, 
```
- snap-20131011.dat - JSON serialized BlobStoreIndexShardSnapshot for snapshot "20131011"
- index-123 - JSON serialized BlobStoreIndexShardSnapshot for snapshot "20131011"
```
The description is the same, the naming is different, I guess something is wrong.
Sorry about asking you to update JavaDoc again, but it's just not possible to understand what is going without clear documentation.

**Comment by original-brownbear** [comment]
@andrershov 

> The description is the same, the naming is different, I guess something is wrong.
Sorry about asking you to update JavaDoc again, but it's just not possible to understand what is going without clear documentation.

no worries :) It's `BlobStoreIndexShardSnapshots` in the index file. I pushed 5de89d6

**Comment by andrershov** [comment]
@original-brownbear 
```
index-123 - JSON serialized BlobStoreIndexShardSnapshots for snapshot "20131011"
```
Not just for snapshot "20131011" but it's just one file related to all the snapshots of the shard, is not it?
Also, it would be nice to specify that there is just one such file per shard expected and when we generate a new file, we increment previous file generation by one?

**Comment by original-brownbear** [comment]
@andrershov 

> Not just for snapshot "20131011" but it's just one file related to all the snapshots of the shard, is not it?
Also, it would be nice to specify that there is just one such file per shard expected and when we generate a new file, we increment previous file generation by one?

yea right on both counts :) I'll add some more javadoc explaining the exact mechanics of this tomorrow.

**Comment by DaveCTurner** [comment]
While we're looking at that Javadoc comment, I note that it claims some things are JSON-formatted when in fact these days they're SMILE plus a short header and a footer and a checksum :)

**Comment by original-brownbear** [comment]
@DaveCTurner @andrershov alright I did my best cleaning up the docs a little. I didn't want to go too far beyond the scope of this bug so I left out the checksum footer stuff (happy to add another PR for that after this one :)) but I at least added links to the datatype for each blob in the repository and corrected `JSON` -> `SMILE` where appropriate. Hope this is helpful for the time being.

I think it may be best to simply add more verbose Javadoc about the actual mechanics of how and when these blobs are written in a step-by-step way to the `org.elasticsearch.repositories.blobstore` package, wdyt?

File: server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java [hunk 1]
```diff
@@ -208,6 +208,7 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
         builder.endArray();
         // Then we list all snapshots with list of all blobs that are used by the snapshot
         builder.startObject(Fields.SNAPSHOTS);
+        assert shardSnapshots.stream().map(SnapshotFiles::snapshot).distinct().count() == shardSnapshots.size();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: I think this assertion would fail in cases where the repository has already ended up with two snapshots of the same name somehow. We can't have read that from an `index-N` file, but we fall back to listing the individual snapshots so I think it could still happen. In that case I think we shouldn't be writing this file (so I agree with this assertion) but we should also be checking our behaviour with a duplicated snapshot name, and logging warnings instead of trying to write this file at all.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: True, in theory, I agree. But in practice, I'm not so sure I'd want to backport that kind of change to `6.7` (we'd have to somehow do the logging and checking outside of `BlobStoreIndexShardSnapshots` and that's not going to be a clean change that will look the same in `6.7` and `7.x`).

I was gonna look into that part of the problem next, we shouldn't be indexing this stuff by snapshot name in the first place, because we're precisely using UUIDs to get around the possible race conditions that can lead to duplicate entries here. I think it makes more sense fixing the format here and adding the mechanics of handling existing duplicates into that effort?

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 2]
```diff
@@ -2961,6 +2961,103 @@ public void testRestoreSnapshotWithCorruptedIndexMetadata() throws Exception {
         assertAcked(client().admin().cluster().prepareDeleteSnapshot("test-repo", snapshotInfo.snapshotId().getName()).get());
     }
 
+    /**
+     * Tests that a shard snapshot with a corrupted shard index file can still be used for restore and incremental snapshots.
+     */
+    public void testSnapshotWithCorruptedShardIndexMetadata() throws Exception {
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Lets call it `...CorruptedShardIndexFile` instead of `...CorruptedShardIndexMetadata`, because there is a different thing called `IndexMetadata`

File: server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: Right, I'm also ok with removing this assertion if we can't easily put those checks in place. I'm just against using an assertion to catch that we're operating on a broken repo (in a way in which we know it can be).

Throwing a proper exception here would also be better than writing an unreadable metadata file - at least this way the user would know to take some action.

Also +1 to improving this format in the near future.

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 3]
```diff
@@ -2961,6 +2961,103 @@ public void testRestoreSnapshotWithCorruptedIndexMetadata() throws Exception {
...
+        final Client client = client();
+        final Path repo = randomRepoPath();
+        final String indexName = "test-idx";
+
+        assertAcked(prepareCreate(indexName).setSettings(Settings.builder()
+            .put(SETTING_NUMBER_OF_SHARDS, 1).put(SETTING_NUMBER_OF_REPLICAS, 0)));
+
+        final int nDocs = randomIntBetween(1, 10);
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: In general, I find it useful to log each logical step in the test. This serves two purposes:
* It's easier to follow the code, because log messages serve as comments
* When figuring out why the test has failed, you can use this log messages as anchors.

Log messages could be like:
* Create index and index some documents
* Create repository
* Create snapshot
* Truncate shard index file
* Delete index
* Restore the snapshot and check that documents are there
and so on...

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 4]
```diff
@@ -2961,6 +2961,103 @@ public void testRestoreSnapshotWithCorruptedIndexMetadata() throws Exception {
...
+        assertHitCount(client().prepareSearch(indexName).setSize(0).get(), nDocs);
+
+        // Index another batch of documents
+        for (int j = 0; j < nDocs; j++) {
+            documents[j] = client.prepareIndex(indexName, "_doc").setSource("foo2", "bar2");
+        }
+        indexRandom(true, documents);
+
+        // Truncate the shard index file again
+        try (SeekableByteChannel outChan = Files.newByteChannel(shardIndexFile, StandardOpenOption.WRITE)) {
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: I don't see if we create any new snapshots between previous truncation and current truncation. Do we expect this file to be restored?

**Review by andrershov — CHANGES_REQUESTED** [review]
@original-brownbear thanks for the updated JavaDocs, looks much better now. I agree that we still need a separate PR to describe the exact mechanics of these files.
I've left a couple of comments/questions.

File: server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: > Throwing a proper exception here would also be better than writing an unreadable metadata file - at least this way the user would know to take some action.

On reflection, I'm not sure this is true. That might leave the repo with a readable-but-stale metadata file; at least if the file is unreadable then we fall back to something sensible.

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: My bad, this isn't needed anymore. In a prior version I was running a snapshot delete as well, but now that that's gone I'll just remove this :) sec

**Comment by original-brownbear** [comment]
@andrershov all points addressed, added logging, renamed test + removed redundant file truncation.

File: server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: > Right, I'm also ok with removing this assertion if we can't easily put those checks in place. I'm just against using an assertion to catch that we're operating on a broken repo (in a way in which we know it can be).

I'd like tests to fail here if that's ok? I can see a few sequences of events that lead us here but are pretty tricky to reproduce/fix with the way snapshotting works currently, but I think it would be good to at least have a little coverage on this situation in tests?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: I would rather not use an assertion here to say that we haven't ended up in this state in a test. This assertion effectively says that it is not possible to be in this state, but we know that this isn't the case. It's an _unintended_ state, certainly, but we know it can happen.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java]: Fair point, killed the assertion in 443a5849988 :)

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 5]
```diff
@@ -3000,44 +3004,46 @@ public void testSnapshotWithCorruptedShardIndexMetadata() throws Exception {
...
 
-        // Choose a random index from the snapshot
         final IndexId corruptedIndex = indexIds.get(indexName);
         final Path shardIndexFile = repo.resolve("indices")
             .resolve(corruptedIndex.getId()).resolve("0")
             .resolve("index-0");
 
+        logger.info("-->  truncating shard index file [{}]", shardIndexFile);
+
         // Truncate the shard index file
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Looks redundant once we have logging in place

File: server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 6]
```diff
@@ -3000,44 +3004,46 @@ public void testSnapshotWithCorruptedShardIndexMetadata() throws Exception {
...
+        client().admin().cluster().prepareRestoreSnapshot("test-repo", snapshot1)
             .setRestoreGlobalState(randomBoolean())
             .setWaitForCompletion(true)
             .get();
         ensureGreen();
 
         assertHitCount(client().prepareSearch(indexName).setSize(0).get(), nDocs);
 
+        logger.info("-->  indexing [{}] more documents into [{}]", nDocs, indexName);
         // Index another batch of documents
```
Comment (andrershov) [inline server/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java]: Looks redundant once we have logging in place

**Review by andrershov — APPROVED** [review]
LGTM

**Review by DaveCTurner — APPROVED** [review]
Good work @original-brownbear, LGTM

**Comment by original-brownbear** [comment]
thanks @DaveCTurner , @andrershov !
