### PR TITLE
Match IPv6 addresses without compressed id from settings

### LINKED ISSUE #72091: ipv6 included 0:0:0 is invalid when we added it in cluster.routing.allocation.exclude._ip
**Elasticsearch version:  (`bin/elasticsearch --version`): 7.6.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk 13.0.2

**OS version** (`uname -a` if on a Unix-like system): Linux n24-181-138 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: ipv6 included 0:0:0 is invalid when we added it in cluster.routing.allocation.exclude._ip

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. add ipv6 address in 'cluster.routing.allocation.exclude._ip', we suppose it's fdbd:dc00:111:222:0:0:0:333
 2. there are no shards relocating
 3. but we change the address to fdbd:dc00:111:222::333, shards begin to relocate
 4. in normal condition, ipv6 address fdbd:dc00:111:222:0:0:0:333 is equal to fdbd:dc00:111:222::333

### PR DESCRIPTION
**Pull request by arteam**
Make sure we normalize IPv6 addresses from the settings to the compressed form before we
match them with node ips. Node IPv6 addresses are all represented with the scope id
in the compressed form.

Closes #72091

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Great, thanks Artem. My only comment is that I don't think we should normalise any filter that looks like it's an IP address, just the ones that use `matchByIP` when the filter executes. It's possible that folk will put things that might be an IP address in e.g. their node name, possibly with leading zeroes, but we shouldn't change how those things are matched.

File: server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java [hunk 1]
```diff
@@ -295,6 +295,16 @@ public void testOnlyAttributeValueFilter() {
         assertThat(discoveryNodeFilters.isOnlyAttributeValueFilter(), is(discoveryNodeFilters.match(node)));
     }
 
+    public void testIpv6WithScopeIdFromSettingsMatchingIpv6WithCompressedScopeId() {
+        Settings settings = shuffleSettings(Settings.builder()
+            .put("xxx." + randomFrom("_ip", "_host_ip", "_publish_ip"), "fdbd:dc00:111:222:0:0:0:333")
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java:300]: I suppose since it's important that we don't normalise things like node names we should have a test to assert that too.

File: server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java [hunk 2]
```diff
@@ -295,6 +295,16 @@ public void testOnlyAttributeValueFilter() {
...
+            .build());
+        DiscoveryNodeFilters filters = buildFromSettings(OR, "xxx.", settings);
+
+        DiscoveryNode node = new DiscoveryNode("", "", "", "", "fdbd:dc00:111:222::333", localAddress, emptyMap(), emptySet(), null);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java:304]: Does this new mechanism also normalise IPv4 addresses by removing leading zeroes? That sounds desirable, it'd be good to have a test for this too to document this fact too.

File: server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java [hunk 3]
```diff
@@ -295,6 +295,16 @@ public void testOnlyAttributeValueFilter() {
         assertThat(discoveryNodeFilters.isOnlyAttributeValueFilter(), is(discoveryNodeFilters.match(node)));
     }
 
+    public void testIpv6WithScopeIdFromSettingsMatchingIpv6WithCompressedScopeId() {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java:298]: I don't think this has anything to do with scope IDs? The scope ID is a suffix on the address of the form `%eth0`. How about `testNormalizesIPAddressFilters` (or `testNormalizesIPv6AddressFilters` and then a separate test for IPv4 addresses?

**Review by DaveCTurner — COMMENTED** [review]
Prod changes look good to me, I left a few more thoughts about tests.

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
Sorry for the force-push noise, I was trying to disable force push commits for my Elasticsearch's fork.

**Comment by arteam** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java (hunk 2 above)
Comment (arteam) [reply server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java:304]: No, we don't support parsing IPv4 addresses with leading zeroes: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/network/InetAddresses.java#L114

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

File: server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java:304]: Ah excellent thanks for checking. Just IPv6 then.

File: server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java [hunk 4]
```diff
@@ -295,6 +295,26 @@ public void testOnlyAttributeValueFilter() {
...
+    }
+
+    public void testHostnameGetMatchedAndNotAffectedByNormalizing() {
+        Settings settings = shuffleSettings(Settings.builder()
+            .put("xxx._host", "test-host")
+            .build());
+        DiscoveryNodeFilters filters = buildFromSettings(OR, "xxx.", settings);
+
+        DiscoveryNode node = new DiscoveryNode("", "", "", "test-host", "192.168.0.1", localAddress, emptyMap(), emptySet(), null);
+        assertThat(filters.match(node), equalTo(true));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeFiltersTests.java:315]: Sorry I think I wasn't clear. What I meant was if, say, the node name is `fdbd:dc00:111:222::333` then this should not match the filter `xxx._name: fdbd:dc00:111:222:0:0:0:333` (and vice versa). In other words, a test that fails on 48132af26edcc317f8e71e6dc98f6a4277011fc2 to demonstrate why this isn't the right implementation.

**Review by DaveCTurner — APPROVED** [review]
LGTM
