### PR TITLE
Set default index mode for TimeSeries to `null`

### LINKED ISSUE #97429: Synthetic source is on by default for TSDS but does not appear in mappings
### Elasticsearch Version

8.7

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

As of 8.7 the default `_source` behaviour linked to `index.mode: time_series` was changed. Prior to 8.7, `_source` was explicitly stored, from this version onward it became synthetics.
This change cannot be easily visualised by users, as the corresponding setting (`"_source": {"mode": "synthetic"}`) doesn't appear in the resulting indices.
Moreover, if a user sets this by hand in a template, indices created don't have the setting. It is as if the setting is ignored by Elasticsearch upon index creation. This is extremely confusing for users.

In general, this behaviour is misleading, since there is no clear indication to the user that the `_source` isn't fully stored. Some customers also explicitly require their `_source` not to be tampered with, for legal and auditing reasons.

This behaviour (if intended) needs to be clearly documented in the [TSDS](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html) or [`_source`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source) documentation page.
We further propose that any mapping or setting explicitly written in a template should be explicitly written in any index that is instantiated from it. Anything else is too misleading.
It is also somewhat of a concern that there now appear to be two separate sources of truth for `"mode": "synthetic"`: one in mappings and another hidden somewhere in our code.

### Steps to Reproduce

This can be reproduced by running the following (notice the change of behaviour pre/post 8.7):

```
PUT /_index_template/test
{
  "index_patterns": [
    "foobar*"
  ],
  "template": {
    "settings": {
      "index": {
        "mode": "time_series",
        "routing_path": [
          "host.name"
        ]
      }
    },
    "mappings": {
      "_source": {
        "mode": "synthetic"
      }
    }
  },
  "composed_of": [
  ],
  "priority": 500,
  "data_stream": {
  }
}

POST /_index_template/_simulate/test
```

Gives the following on 8.6.x:

```
    "mappings": {
      "_source": {
        "mode": "synthetic"
      }
    },
```

This very section disappears on 8.7.x, while synthetic source remains activated.

### PR DESCRIPTION
**Pull request by kkrik-es**
If the default index mode matches the specified, we skip printing the synthetic source info in mappings. This leads to confusion as it's not immediately visible (or well known) that time series indices use synthetic source by default.

Leaving the default index mode to null does the trick here. We do pass the right value for time series indexes while building the mapping so there's no other functional impact.

Fixes #97429

### CODE REVIEW

**Comment by kkrik-es** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

File: server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java [hunk 1]
```diff
@@ -86,10 +86,15 @@ public static class Builder extends MetadataFieldMapper.Builder {
...
+
+        /*
+         * The default mode for TimeSeries is left empty on purpose, so that mapping printings include the synthetic
+         * source mode.
+         */
         private final Parameter<Mode> mode = new Parameter<>(
             "mode",
             true,
-            () -> getIndexMode() == IndexMode.TIME_SERIES ? Mode.SYNTHETIC : null,
+            () -> null,
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java:97]: I think this is the crux of the issue that this pr is trying to fix.
The default (which is `null`) is used for stored source mode. So if source mode=stored is provided we see that it is different than the default and include it in the mapping. But the default for tsdb is synthetic, so if synthetic is provided this is seen as default and source mode then isn't serialised in the mapping.

Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java:97]: Right, that's my understanding too. Any concerns with this fix?

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java [hunk 2]
```diff
@@ -37,9 +37,18 @@ public static DocumentMapper createEmpty(MapperService mapperService) {
         this.documentParser = documentParser;
         this.type = mapping.getRoot().name();
         this.mappingLookup = MappingLookup.fromMapping(mapping);
-        this.mappingSource = source;
-        assert mapping.toCompressedXContent().equals(source)
-            : "provided source [" + source + "] differs from mapping [" + mapping.toCompressedXContent() + "]";
+        if (sourceMapper().isSynthetic() && source.string().contains("\"_source\":{\"mode\":\"synthetic\"}") == false) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java:40]: I think we can pass down an index version from the places a new `DocumentMapper` instance are created.
Maybe let's check the assertion only for tsdb indices before a version that have this fix?

**Review by martijnvg — COMMENTED** [review]
Left one comment about the assertion. Otherwise looks good.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java (hunk 2 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java]: Done.

File: server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java (hunk 1 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java:97]: Nope this is good.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java [hunk 3]
```diff
@@ -30,16 +31,27 @@ public static DocumentMapper createEmpty(MapperService mapperService) {
...
-            : "provided source [" + source + "] differs from mapping [" + mapping.toCompressedXContent() + "]";
+        if (sourceMapper().isSynthetic()
+            && source.string().contains("\"_source\":{\"mode\":\"synthetic\"}") == false
+            && version.onOrBefore(IndexVersion.V_8_10_0)) {
+            /*
+             * Indexes built at v.8.7 were missing an explicit entry for synthetic_source.
+             * This got restored in v.8.9 (and patched in v.8.8) to avoid confusion. The change is only restricted to
+             * mapping printout, it has no functional effect as the synthetic source already applies.
+             */
+            this.mappingSource = mapping.toCompressedXContent();
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java:49]: By doing `this.mappingSource = mapping.toCompressedXContent();` we are changing the mapping source to contain the missing `_source: mode: synthetic` right?

If we would do `this.mappingSource = source;` here, then the that would remain to be missing?

Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java:49]: Correct. I was thinking of storing a source that matches this output to avoid surprises further down the processing pipeline, but up to you.

**Review by martijnvg — APPROVED** [review]
LGTM
