### PR TITLE
SQL: Enhance checks for inexact fields

### LINKED ISSUE #38501: SQL: Enhance check for text fields without underlying keyword
For functions/operators than cannot operate on `text` fields move the validation that's currently happening in places like `QueryTranslator` to `resolveType()`.
Also avoid throwing an Exception from `exactAttribute()->TextEsField.getExactField()` method call, but instead introduce new method that has a proper return type that can be used for the validation.

### PR DESCRIPTION
**Pull request by matriv**
For functions: move checks for `text` fields without underlying `keyword`
fields or with many of them (ambiguity) to the type resolution stage.

For Order By/Group By: move checks to the `Verifier` to catch early
before `QueryTranslator` or execution.

Fixes: #38501

### CODE REVIEW

**Comment by matriv** [comment]
Also fixes: #35203

**Comment by matriv** [comment]
@costin @astefan As this PR fixes also an issue for group by and order by, do you think I should extract this fix separately as it's done here: #39443, to backport only the fix, or should I backport this whole PR to earlier versions?

Asking because this extraction requires some more work.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+import java.util.StringJoiner;
+import java.util.function.Predicate;
+
+import static org.elasticsearch.common.logging.LoggerMessageFormat.format;
+import static org.elasticsearch.xpack.sql.expression.Expression.TypeResolution;
+import static org.elasticsearch.xpack.sql.expression.Expressions.ParamOrdinal;
+import static org.elasticsearch.xpack.sql.expression.Expressions.name;
+import static org.elasticsearch.xpack.sql.type.DataType.BOOLEAN;
+
+public final class TypeResolutionUtils {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java]: I would prefer using the plural instead of Utils - `TypeResolutions`. Utils has been used where the plural already existed in the rest of the codebase to avoid name clashes.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+
+    private TypeResolutionUtils() {}
+
+    public static TypeResolution typeMustBeBoolean(Expression e, String operationName, ParamOrdinal paramOrd) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java]: Additionally, how about simplifying the method names from "typeMustBeNumeric" to "isNumeric" similar to the assertion in JUnit? It also add consistency ("expressionMustBe", "typeMustBe...").

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+        if (!e.foldable()) {
+            return new TypeResolution(format(null, "{}argument of [{}] must be a constant, received [{}]",
+                paramOrd == null || paramOrd == ParamOrdinal.DEFAULT ? "" : paramOrd.name().toLowerCase(Locale.ROOT) + " ",
+                operationName,
+                Expressions.name(e)));
+        }
+        return TypeResolution.TYPE_RESOLVED;
+    }
+
+    public static TypeResolution expressionMustBeTableColumn(Expression e, String operationName, ParamOrdinal paramOrd) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java]: constant/table column is a bit misleading - I would just use `isFoldable`/`notFoldable` since it's a terminology already used through-out the code.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/TextEsField.java [hunk 4]
```diff
@@ -20,25 +22,46 @@ public TextEsField(String name, Map<String, EsField> properties, boolean hasDocV
...
+    }
+
+    @Override
+    public boolean isExact() {
+        return false;
+    }
+
+    @Override
+    public Tuple<Boolean, String> hasExact() {
+        return PROCESS_EXACT_FIELD.apply(findExact());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/TextEsField.java]: What's the reason behind using the closure?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java [hunk 5]
```diff
@@ -109,16 +108,6 @@ public void testTermEqualityAnalyzer() {
         assertEquals("value", tq.value());
     }
 
-    public void testTermEqualityAnalyzerAmbiguous() {
```
Comment (costin) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java]: Is this tested somewhere else?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/EsField.java [hunk 6]
```diff
@@ -85,6 +87,15 @@ public boolean isExact() {
         return true;
     }
 
+    /**
+     * {True, null} if this field has an exact field which can be retrieved by {@link EsField#getExactField()}
+     * {False, String} if this field doesn't have an underlying exact field, the v2 of the tuple is a string containing
+     * an error message explaining why that is.
+     */
+    public Tuple<Boolean, String> hasExact() {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/EsField.java]: I think having both `isExact` and `hasExact` is confusing - is the former still used anywhere? I opt for refactoring isExact to return the tuple instead (which can be promoted to a dedicated inner class such (`Exact`) to make its use easier and its intent clearer).

**Review by costin — COMMENTED** [review]
Thanks for looking into this. Left a few comments, mainly around naming.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/TypeResolutionUtils.java]: The plural just sounded to me a bit weird, but I'll change.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/TextEsField.java (hunk 4 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/TextEsField.java]: The findExact() returns also the exact field (used by getExact()) so I wanted to convert the `field == null ? false : true` and chose a `Function` to be somehow more elegant.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 5 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java]: Yes, here: https://github.com/elastic/elasticsearch/pull/39427/files#diff-334bd2f8c33b60789817181fcef4ca52R331 with 2 methods now.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/EsField.java (hunk 6 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/EsField.java]: I agree with the confusing `isExact` but it's used externally here: https://github.com/elastic/elasticsearch/pull/39427/files#diff-1059b5208ef7d10a0fdc89b5dad914edR90 and has slightly different semantics than `hasExact`.

`hasExact` returns <TRUE, null> if it's exact, or has an exact underlying field, so we don't know which is the case.

But if we introduce a class `Exact` to replace the the `Tuple` we can include this info there and remove the confusing `isExact()` method. Thx!

**Comment by costin** [comment]
> @costin @astefan As this PR fixes also an issue for group by and order by, do you think I should extract this fix separately as it's done here: #39443, to backport only the fix, or should I backport this whole PR to earlier versions?
> 
> Asking because this extraction requires some more work.

Whatever it's easier - I think the PR itself is not complicated but is made big by the amount of files that it touches. I'm fine with backporting the whole PR.

**Comment by matriv** [comment]
@costin thanks for the comment! Pushed a commit to address them.

**Review by astefan — APPROVED** [review]
LGTM. Nice cleanup. Left few minor comments.

**Comment by astefan** [comment]
Also, shouldn't this one go to 7.0.x as well?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java [hunk 7]
```diff
@@ -292,6 +292,12 @@ public void testStarOnNested() {
         assertNotNull(accept("SELECT dep.* FROM test"));
     }
 
+    public void testGroupByOnInexact() {
+        assertEquals("1:36: Grouping field of data type [text] for grouping; " +
```
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: ah, sorry I mixed something up there, will fix.

[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: thx for catching!

**Comment by matriv** [comment]
@astefan yes, it will actually be backported all the way to `6.6.2` as it also fixes the bug mentioned for Order By and Group By.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java [hunk 8]
```diff
@@ -416,65 +440,101 @@ public void testInOnFieldTextWithNoKeyword() {
...
 
-    public void testInvalidTypeForStringFunction_WithOneArg() {
-        assertEquals("1:8: [LENGTH] argument must be [string], found value [1] type [integer]",
+    public void testInvalidTypeForStringFunction_WithOneArgString() {
+        assertEquals("1:8: argument of [LENGTH(1)] must be [string], found value [1] type [integer]",
             error("SELECT LENGTH(1)"));
     }
 
+    public void testInvalidTypeForStringFunction_WithOneArgNumeric() {
+        assertEquals("1:8: argument of [CHAR('foo')] must be [integer], found value ['foo'] type [keyword]",
```
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/analyzer/VerifierErrorMessagesTests.java]: Added a test: https://github.com/elastic/elasticsearch/pull/39427/commits/cda66caaf1abb7a0d3afcd427ade3b1912bcd1a2#diff-334bd2f8c33b60789817181fcef4ca52R457

Good thinking! But seems fine since we use `sourceText()` on the offending function and it's not showing the whole expression that can be complex and result in confusion for the user.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/TextEsField.java (hunk 4 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/TextEsField.java]: I got that but why not use the code directly? The closure is not passed anywhere...

**Review by costin — APPROVED** [review]
LGTM.

**Comment by matriv** [comment]
Backported to `7.x` with 9fb2f670dc9c946fb0c0392d30442a52abd3d720
to `7.0` with 2c39bb352f719df4db96a64777c0a3a00f89f0eb
to `6.7` with bfc6e2272fec1f077f24af0c8bf2bc3818399e9a
tp `6.6` with 9c60367b28fd0b3d59c895dcd3c3f1d747eff853
