### PR TITLE
Warn user if regular expression is used when match_pattern defaults to simple in dynamic_template mappings

### LINKED ISSUE #95634: Warn user if regular expression is used when match_pattern defaults to simple in dynamic_template mappings
### Description

This was flagged by @romseygeek in https://github.com/elastic/elasticsearch/pull/95558#discussion_r1177625654 to be targeted for a new issue.

In dynamic_template mappings, 'simple' match types (which is the default setting) will happily accept regexes (rather than simple wildcards) without error or warning, but then they will not work as the user likely intended. We should emit a warning if the user provides a pattern that 'looks like' a regex, but haven't explicitly set match_type.

---- 

Deeper context: 

The validate method in DynamicTemplate.parse tries to catch these, but it only catches the invalid pattern when match_pattern=regex. For example, see the test: https://github.com/elastic/elasticsearch/blob/main/server/src/test/java/org/elasticsearch/index/mapper/DynamicTemplateParseTests.java#L132

Current behavior is:

```
  "mappings": {
    "dynamic_templates": [
      {
        "mytemplate": {
          "match_pattern": "regex",
          "match": "*name",
          "unmatch": "*middle",
          "mapping": {
            "type": "keyword"
          }
        }
      }
    ]
  }
```
fails with:
```
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping: Pattern [*name] of type [regex] is invalid. Cannot create dynamic template [mytemplate].",\
```
but:

```
      {
        "mytemplate": {
          "match": ".*name$",
          "unmatch": "^.*middle.*",
          "mapping": {
            "type": "keyword"
          }
        }
      }
```
(where  `"match_pattern": "simple"` is implied) works with no problems (until you try to actually put documents in with the mapping, of course).

We could probably add a method to Regex.java. There is already this function

```
   public static boolean isSimpleMatchPattern(String str) {
        return str.indexOf('*') != -1;
    }
```
but that's not enough for this scenario.

[This code](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/regex/Regex.java#L133) indicates that the only allowed patterns for "simple" are "xxx*", "*xxx", "*xxx*" and "xxx*yyy", so we could check for things like .* and ^xxx and yyy$ and chars like [, ] and | and maybe parens and then run it through [REGEX.matches()](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java#L40) and if that does NOT fail, then it appears to be a valid actual regex, not a simple pattern and then give a warning to users.

### PR DESCRIPTION
**Pull request by quux00**
In a dynamic_templates setting, when match_pattern is not defined by the user and thus defaults to "simple" and when the pattern passed into match, unmatch, path_match or path_unmatch appears to be a regular expression, 
a warning is added to the HTTP response header. The warning will not be set if the user explicitly sets match_pattern=simple, since ES allows most regular expression meta-characters in doc field names.

Closes #95634

### CODE REVIEW

**Comment by quux00** [comment]
Tested this locally with curl and warning appears as expected:

```
└─ $ ▶ cat > dyntemplate_with_regex.json
{
  "mappings": {
    "dynamic_templates": [
      {
        "mytemplate": {
          "match": ["^12.*", "foo*"],
          "mapping": {
            "type": "keyword"
          }
        }
      }
    ]
  }
}

└─ $ ▶ curlj -X PUT localhost:9200/myindex -d@dyntemplate_with_regex.json
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
Warning: 299 Elasticsearch-8.9.0-SNAPSHOT-0767ebd34cb70cea8676563f774ba22038937a80 "Pattern [^12.*] appears to be a regular expression, not a simple wildcard pattern. To remove this warning, set [match_pattern] in the dynamic template."
content-type: application/json
content-length: 66

{"acknowledged":true,"shards_acknowledged":true,"index":"myindex"}
```

**Comment by dnhatn** [comment]
@elasticsearchmachine update branch

**Comment by dnhatn** [comment]
update branch

**Comment by dnhatn** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java [hunk 1]
```diff
@@ -60,6 +146,12 @@ public static MatchType fromString(String value) {
 
         /** Whether {@code value} matches {@code regex}. */
         public abstract boolean matches(String regex, String value);
+
+        /**
+         * Whether the {@code pattern} is a valid for the MatchType.
+         * @throws IllegalArgumentException if the pattern is not valid
+         */
+        public abstract void isValidPattern(String pattern);
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java:154]: I think I'd call this `validate` - `isXXX` implies a boolean return value to me.

File: server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java [hunk 2]
```diff
@@ -255,19 +347,26 @@ private static void addEntriesToPatternList(List<String> matchList, String propN
...
-                throw new MapperParsingException(
-                    Strings.format(
-                        "Pattern [%s] of type [%s] is invalid. Cannot create dynamic template [%s].",
-                        regex,
-                        matchType,
-                        templateName
-                    ),
-                    e
-                );
+                if (matchType == MatchType.DEFAULT) {
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java:354]: Can we move this logic into `isValidPattern` directly, rather than throwing and catching exceptions?

File: server/src/test/java/org/elasticsearch/index/mapper/DynamicTemplatesTests.java [hunk 3]
```diff
@@ -2252,4 +2373,137 @@ public void testInvalidMatchWithArrayOfFieldNamesUsingNonStringEntries() throws
...
+                assertThat(
+                    e.getMessage(),
+                    containsString("Pattern [" + c.pattern + "] appears to be a regular expression, not a simple wildcard pattern")
+                );
+            }
+        }
+    }
+
+    public void testIsValidPatternForSimpleMatchType() {
+        record MatchPattern(String pattern) {}
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/index/mapper/DynamicTemplatesTests.java:2428]: I'm not sure this adds anything over just using `String` here?

**Review by romseygeek — CHANGES_REQUESTED** [review]
Thanks @quux00!  I left a few comments.

File: server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java (hunk 1 above)
Comment (quux00) [reply server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java:154]: Yeah, good call. The original version I did returned boolean, but I need the error message on failure. I'll change it.

File: server/src/test/java/org/elasticsearch/index/mapper/DynamicTemplatesTests.java (hunk 3 above)
Comment (quux00) [reply server/src/test/java/org/elasticsearch/index/mapper/DynamicTemplatesTests.java:2428]: Right. I'll change that.

File: server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java (hunk 2 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java:354]: So the reason I think this fits better in `validate` is that there are two branches inside this catch clause, and each only applies to one match type.  There's no shared code here.  In other words, these are bits of MatchType-specific logic, which to me means that they should live within the different MatchType implementations.

Comment (quux00) [reply server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java:354]: Sounds good. I'll move it.

Comment (quux00) [reply server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java]: This change required more code changes that I expected. Key changes:

1) I added templateName to the `MatchType.validate` params list, because the error message (that was already in place before I started this series of tickets) requires the template name in the error message.

2) Testing `MatchType.validate` with only side effects and no return value became problematic, so I changed it to return a boolean (useful mostly for unit tests) and thus changed the name back to `isValidPattern`.

Comment (quux00) [reply server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java]: Actually, nevermind the second comment above. After consideration I found that testing without a boolean return value is straightforward. Pushed new commit.

**Comment by javanna** [comment]
I have a general question around the overall idea of emitting a warning: is the plan to one day remove the warning and make it a hard error? What type of warning are we emitting in the proposed change, is that a deprecation warning?

**Review by romseygeek — APPROVED** [review]
LGTM, thanks for all the iterations @quux00!

**Comment by quux00** [comment]
> The idea here is that if you don't explicitly set `match_type`, then we use simple globbing to match field paths. But it's fairly easy to overlook this and try and use a regex as a pattern without setting `match_type`, which can fail in unexpected ways - and importantly, not fail until quite a long time after you've set things up. So the idea of this warning is to detect cases where somebody hasn't explicitly set the `match_type`, but looks like they're using a regex. It would never become a hard error, because it's only a heuristic - we think you're using a regex here but you haven't set it up properly. If it is in fact correctly configured (ie you really do want to match fields that have square brackets in them), then you can make the warning go away by setting `match_type=simple`.

Good write-up. I'll adjust the commit message to reflect this context.
