### PR TITLE
Fixing some test issues

### LINKED ISSUE #124490: [CI] JwtWithOidcAuthIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8728 / ubuntu-1804_platform-support-unix](https://gradle-enterprise.elastic.co/s/ygevcfelmu4p4)
- [elasticsearch-periodic-platform-support #8728 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/rnvs7piv3frzi)
- [elasticsearch-periodic-platform-support #8728 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/634asljfl5swa)
- [elasticsearch-pull-request #75293 / part-2](https://gradle-enterprise.elastic.co/s/dz26bw6qc6afu)
- [elasticsearch-intake #23934 / part2](https://gradle-enterprise.elastic.co/s/gieiyj746lylw)
- [elasticsearch-periodic-platform-support #8722 / ubuntu-2404-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/aiefbsqnicoge)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.jwt.JwtWithOidcAuthIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.security.authc.jwt.JwtWithOidcAuthIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.19] 3 consecutive failures in class org.elasticsearch.xpack.security.authc.jwt.JwtWithOidcAuthIT
- [8.19] 6 failures in class org.elasticsearch.xpack.security.authc.jwt.JwtWithOidcAuthIT (4.1% fail rate in 145 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ankit--sethi**
Attemping to resolve https://github.com/elastic/elasticsearch/issues/124490 and https://github.com/elastic/elasticsearch/issues/127738 and https://github.com/elastic/elasticsearch/issues/126223

### CODE REVIEW

File: test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java [hunk 1]
```diff
@@ -132,7 +133,8 @@ public void testUpdatingFileBasedRoleAffectsAllProjects() throws Exception {
         assertBusy(() -> {
             assertThat(getClusterPrivileges(project1, username1), contains("monitor"));
             assertThat(getClusterPrivileges(project2, username2), contains("monitor"));
-        });
+        }, 20, TimeUnit.SECONDS); // increasing this to try and solve for a rare failure
```
Comment (ankit--sethi) [inline test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java:136]: current default is 10s.

File: x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java [hunk 2]
```diff
@@ -27,6 +27,7 @@ public SmbTestContainer() {
             new ImageFromDockerfile("es-smb-fixture").withDockerfileFromBuilder(
                 builder -> builder.from(DOCKER_BASE_IMAGE)
                     .env("TZ", "Etc/UTC")
+                    .run("echo 'Acquire::Retries \"10\";' | tee /etc/apt/apt.conf.d/80-retries")
                     .run("DEBIAN_FRONTEND=noninteractive apt-get update -qqy && apt-get install -qqy tzdata winbind samba ldap-utils")
```
Comment (ankit--sethi) [inline x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java:31]: Bumping apt-get retries from 3 to 10.

File: x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java [hunk 3]
```diff
@@ -27,6 +27,7 @@ public SmbTestContainer() {
             new ImageFromDockerfile("es-smb-fixture").withDockerfileFromBuilder(
                 builder -> builder.from(DOCKER_BASE_IMAGE)
                     .env("TZ", "Etc/UTC")
+                    .run("echo 'Acquire::Retries \"10\";' | tee /etc/apt/apt.conf.d/80-retries")
```
Comment (ankit--sethi) [inline x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java]: Bumping apt-get retries from 3 (default) to 10 -  this should help with any transient issues downloading packages.

Comment (parkertimmins) [reply x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java]: Looks like it might work to add it to the apt-get call directly with: `-o Acquire::Retries=10`
Though I'm fine with this too.

**Review by parkertimmins — APPROVED** [review]

File: docs/changelog/129295.yaml [hunk 4]
```diff
@@ -0,0 +1,8 @@
+pr: 129295
+summary: Increase the number of retries for apt-get
+area: Security
+type: enhancement
```
Comment (slobodanadamovic) [inline docs/changelog/129295.yaml]: We use `>enhancement` label only when improving existing production (customer facing) features. Hence why the release changelog is generated. 

In this case, you should remove the changelog and apply `>test` label, since it's only solving test failures and changing test fixture.

**Review by slobodanadamovic — CHANGES_REQUESTED** [review]

File: test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java [hunk 5]
```diff
@@ -132,7 +133,8 @@ public void testUpdatingFileBasedRoleAffectsAllProjects() throws Exception {
...
+
         rolesFile.update(Resource.fromString(""));
 
         assertBusy(() -> {
```
Comment (slobodanadamovic) [inline test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java:140]: Let's bump the timeout on this check as well.

File: test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java (hunk 1 above)
Comment (slobodanadamovic) [reply test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java:136]: The `SecurityRolesMultiProjectIT` is [muted](https://github.com/elastic/elasticsearch/blob/9a8e50375c0f07d72eda4517fde5ddc7371a4b65/muted-tests.yml#L304-L306).

Let's unmute it by removing the entry from `muted-tests.yml`.

**Comment by slobodanadamovic** [comment]
The https://github.com/elastic/elasticsearch/issues/124490 was failing on 8.19. We should backport the fixes to older branches as well. The only tricky part here is that you'll have to selectively backport this PR given that `SecurityRolesMultiProjectIT` does not exist on branches other than main (9.1).

File: test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java (hunk 5 above)
Comment (ankit--sethi) [reply test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java:140]: ok!

**Comment by ankit--sethi** [comment]
> The #124490 was failing on 8.19. We should backport the fixes to older branches as well. The only tricky part here is that you'll have to selectively backport this PR given that `SecurityRolesMultiProjectIT` does not exist on branches other than main (9.1).

I'll backport them manually

File: test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java (hunk 1 above)
Comment (ankit--sethi) [reply test/external-modules/multi-project/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityRolesMultiProjectIT.java:136]: nice catch!

**Review by slobodanadamovic — APPROVED** [review]
LGTM 👍

File: x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java (hunk 3 above)
Comment (ankit--sethi) [reply x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java]: this is what I wanted to do as well but somehow didn't find the right syntax - thanks for the tip!
