### PR TITLE
Client: Wrap synchronous exceptions

### LINKED ISSUE #28399: Rest client's synchronous APIs throw less than useful exceptions
The Java rest client's synchronous calls throw exceptions in "funny" ways that seem to come with all the disadvantages of async code. When they throw an exception they only have the stack trace from the innards of the http-async client and they don't get decorated with `suppressed` exceptions if thrown from inside of a `finally` block. This makes debugging failures difficult and I'm going to look into fixing it.

### PR DESCRIPTION
**Pull request by nik9000**
In the past the Low Level REST Client was super careful not to wrap
any exceptions that it throws from synchronous calls so that callers can
catch the exceptions and work with them. The trouble with that is that
the exceptions are originally thrown on the async thread pool and then
transfered back into calling thread. That means that the stack trace of
the exception doesn't have the calling method which is *super* *ultra*
confusing.

This change always wraps exceptions transfered from the async thread
pool so that the stack trace of the thrown exception contains the
caller's stack. It tries to preserve the type of the throw exception but
this is quite a fiddly thing to get right. We have to catch every type
of exception that we want to preserve, wrap with the same type and
rethrow. I've preserved the types of all exceptions that we had tests
mentioning but no other exceptions. The other exceptions are either
wrapped in `IOException` or `RuntimeException`.

Closes #28399

### CODE REVIEW

**Comment by nik9000** [comment]
This is a fairly significant departure from the philosophy behind the old code so I'm not at all sure that it is right. I think it is important to "fix" the stack traces in the thrown exception and this seems like the least weird way to do it.

**Comment by nik9000** [comment]
Ping @elastic/es-core-infra to match the tag, though it'll probably be @javanna doing the review.

Ping other folks that have contributed to the rest client in case they have other ideas: @PnPie @olcbean, @tlrx.

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java [hunk 1]
```diff
@@ -674,12 +684,30 @@ Response get() throws IOException {
...
                     throw e;
                 }
-                //try and leave the exception untouched as much as possible but we don't want to just add throws Exception clause everywhere
+                /*
+                 * Wrap and rethrow whatever exception we received, copying the type
+                 * where possible so the synchronous API looks as much as possible
+                 * like the asynchronous API. We wrap the exception so that the caller's
+                 * signature shows up in any exception we throw.
+                 */
+                if (exception instanceof ResponseException) {
```
Comment (jasontedor) [inline client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: I would have thought to use reflection here to look for a constructor of the appropriate shape (taking an `Exception` of the same concrete type), falling back to `String` and calling `Throwable#initCause` if not, and then falling back to `RuntimeException`. What do you think of that?

**Review by jasontedor — COMMENTED** [review]
I left a comment about constructing the wrapping exception.

File: client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java [hunk 2]
```diff
@@ -124,27 +137,71 @@ public void testOnFailure() throws Exception {
...
+    }
+
+    public void testConnectTimeoutExceptionIsBuiltCorrectly() throws Exception {
+        RestClient.SyncResponseListener syncResponseListener = new RestClient.SyncResponseListener(10000);
+        ConnectTimeoutException timeoutException = new ConnectTimeoutException();
+        syncResponseListener.onFailure(timeoutException);
+        try {
+            syncResponseListener.get();
+            fail("get should have failed");
+        } catch(IOException e) {
```
Comment (olcbean) [inline client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java]: nit : missing space 
s/catch(IOException e)/catch (IOException e)/
I see this at  several places in this file. Maybe reformat the new code ?

File: client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostTests.java [hunk 3]
```diff
@@ -128,7 +134,13 @@ public void createRestClient() throws IOException {
                             }
                             //return the same headers that were sent
                             httpResponse.setHeaders(request.getAllHeaders());
-                            futureCallback.completed(httpResponse);
+                            // Call the callback asynchronous to better simulate how async http client works
+                            exec.execute(new Runnable() {
+                                @Override
+                                public void run() {
+                                    futureCallback.completed(httpResponse);
+                                }
```
Comment (olcbean) [inline client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostTests.java]: nit : maybe simply call 
```
exec.execute(() -> futureCallback.completed(httpResponse));
```

File: client/rest/src/test/java/org/elasticsearch/client/RestClientTests.java [hunk 4]
```diff
@@ -48,50 +51,83 @@ public void testCloseIsIdempotent() throws IOException {
...
+            restClient.performRequestAsync("unsupported", randomAsciiLettersOfLength(5), new ResponseListener() {
+                @Override
+                public void onSuccess(Response response) {
+                    fail("should have failed because of unsupported method");
+                }
+
+                @Override
+                public void onFailure(Exception exception) {
+                    assertThat(exception, instanceOf(UnsupportedOperationException.class));
+                    assertEquals("http method not supported: unsupported", exception.getMessage());
```
Comment (olcbean) [inline client/rest/src/test/java/org/elasticsearch/client/RestClientTests.java]: off topic : I see that both `assertThat` and `assertEquals` are used throughout the tests. Is there a preference to use one over the other ( for new code ) ?

**Review by olcbean — COMMENTED** [review]
Looks good and would bring more useful info :+1: 

I just have one general concern : is it possible that an exception type ( explicitly expected by the user ) is wrapped into the general `RuntimeException` ? And then the use will need to change their code.
IMHO going with reflection should minimize the risk.

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 1 above)
Comment (nik9000) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: I thought about the reflection solution here and rejected it, mostly because we tend to dislike it in the rest of Elasticsearch. I think the trouble with reflection here is that it is difficult to reason about. Not in the "what is going to happen?" sense, but in the "are the ctors that I call going to do the right thing with the things I give them?" sense.

For what it is worth I'd like to abstract async http client from the Elasticsearch client eventually and I don't think the reflection based approach would play well with that.

I certainly understand that this will change the exceptions that we throw in the cases where I don't have an explicit branch though.

File: client/rest/src/test/java/org/elasticsearch/client/RestClientMultipleHostsTests.java [hunk 5]
```diff
@@ -79,23 +83,28 @@ public void createRestClient() throws IOException {
...
-                } else if (request.getURI().getPath().equals("/ioe")) {
-                    futureCallback.failed(new IOException(httpHost.toString()));
-                } else {
-                    int statusCode = Integer.parseInt(request.getURI().getPath().substring(1));
-                    StatusLine statusLine = new BasicStatusLine(new ProtocolVersion("http", 1, 1), statusCode, "");
-                    futureCallback.completed(new BasicHttpResponse(statusLine));
-                }
+                exec.execute(new Runnable() {
+                    @Override
+                    public void run() {
```
[the remark this answers is not in the document]
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientMultipleHostsTests.java]: I believe that I can't do that here because these tests are compiled with source compatibility set to 1.7.

File: client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java [hunk 6]
```diff
@@ -37,6 +41,25 @@
...
+        boolean foundMyMethod = false;
+        // 0 is getStackTrace
+        // 1 is this method
+        // 2 is the caller, what we want
+        StackTraceElement myMethod = Thread.currentThread().getStackTrace()[2];
+        for (StackTraceElement se : e.getStackTrace()) {
+            if (se.getClassName().equals(myMethod.getClassName())
+                    && se.getMethodName().equals(myMethod.getMethodName())) {
+                foundMyMethod = true;
+                break;
```
[the remark this answers is not in the document]
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java]: Yeah! I had originally had this as part of a larger method so `return` wasn't possible. But now that I've pulled it out `return` is much better. Will push a change for that.

File: client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java [hunk 7]
```diff
@@ -37,6 +41,25 @@
...
+            }
+        }
+        if (false == foundMyMethod) {
+            StringWriter stack = new StringWriter();
+            e.printStackTrace(new PrintWriter(stack));
+            fail("didn't find my stack trace (looks like " + myMethod + ") in\n" + stack);
```
[the remark this answers is not in the document]
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java]: I'll reword and add javadoc to the method to make it more clear why we call it. I don't want to write a whole paragraph in the exception message because I think it'd be hard to read. But I think folks will see the method's javadoc.

File: client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java (hunk 2 above)
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/SyncResponseListenerTests.java]: I'll reform on the files that I touched I think.

File: client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostTests.java (hunk 3 above)
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostTests.java]: Same deal with source compatibility as above.

File: client/rest/src/test/java/org/elasticsearch/client/RestClientTests.java (hunk 4 above)
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientTests.java]: Depends on who you ask. I prefer to use the purpose built assertions when they are the same as the ones from Hamcrest because they are fairly terse and don't need to make objects [1]. I prefer to use the hamcrest ones when they offer better error reporting. I rarely go out of my way to write new hamcrest matchers. By that logic, I could have written `assertThat(e, hasMessage(equalTo("http method not supported: unsupported")));` then I would have done so. But `hasMessage` isn't a thing.

Other folks always use `assertThat` because has very obvious parameter ordering that reads well and the compile can check it. This is a totally valid argument and one that I'll probably end up being swayed by eventually.

I tend not to rewrite assertions that someone else wrote unless I have a good reason to.

[1]: I imagine hamcrest matchers are a great candidate for the JVM to optimize to stack based allocation but I figure that only kicks in for hot method and most test methods aren't run enough to be hot.

**Comment by nik9000** [comment]
Thanks for the reviews @jasontedor and @olcbean! I've pushed some changes for @olcbean's comments and left some responses. The reflection comment is the biggest sticking point here I think. I've just had bad experiences with that sort of thing so I didn't think to much about it. I've thought more about it now that you both suggested it but I still don't really like it for reasons I added in a reply to the inline comment about it.

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 1 above)
Comment (PnPie) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: Or is it a way to wrap the exceptions thrown (all or parts) already in the async call into a "CustomException" ? kind of like the `ElasticsearchException` ? This might make exception a little bit redundant but it keeps the consistence of the 2 sides of sync and async API. (If the exception parse back stuff in sync listener is too tricky to do) ?

File: client/rest/src/test/java/org/elasticsearch/client/RestClientMultipleHostsTests.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (olcbean) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientMultipleHostsTests.java]: Oh.. 
Is there a reason why the test are compiled against 1.7 ? :confused:

[the remark this answers is not in the document]
Comment (nik9000) [reply client/rest/src/test/java/org/elasticsearch/client/RestClientMultipleHostsTests.java]: The non-test code has to be compiled against 1.7 because we want folks still on 1.7 to be able to use it. The tests kind of come along for the ride mostly to make sure that everything works properly in 1.7. For things like that it is a bit of a pain though.

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 1 above)
Comment (nik9000) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: I think the exception unwrapping is going to be tricky to get perfect. I'd be ok with some kind of rethrown exception. I mean, ultimately, that is what we end up with if we fall through all the `instanceof` blocks. We could save ourselves the trouble and wrap the same way every time. I'm honestly not sure what'd be easier for callers though.

@javanna, what do you think? You've been working in this area a lot longer than I have.

Comment (javanna) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: As far as I understand what it all boils down to here is the different IOExceptions that can be thrown by the underlying http client, there may be more than the ones that we have a branch for. 

I think the current solution is good enough, I even wonder if anybody is ever going to catch socket timeout rather connect timeout etc. maybe all those could just be generic IOExceptions like we already do below and one has to look at the cause to see what it really is? I think that would be reasonable too, but we do want to rethrow ResponseException as a proper ResponseException as it's our own (like we already do).

I do not have anything against the proposed reflection solution either, but maybe what we have now is easier to reason about and we can always add branches if we missed something.

Comment (javanna) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: Maybe we should document what we do with exceptions in the sync methods, so people know what to expect.

Comment (javanna) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: another idea, not sure though how much it makes sense, could be to add our own specific runtime exception (instead of a generic one) with a good name that indicates that it's used only for wrapping, and always use that one, and document well that users have to look at the cause. Then we may want to also remove all the `throws IOException` from the `performRequest` methods. Not sure though, maybe this is the silliest way of addressing this problem, it is hard to evaluate how much this would change things for users, I suspect not much but not sure.

**Review by javanna — APPROVED** [review]
I left some thoughts and ideas, I think the most important thing is that we address this one way or the other, I don't have a strong opinion on how :) thanks for looking into this @nik9000

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 1 above)
Comment (nik9000) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: I keep coming back to "I'd like to make async httpclient an implementation detail one day" and I think this kind of `if instanceof then rethrow` is the kind of logic I'm going to need to do that one day. So, I think I'll stick with this approach for entirely selfish reasons. As a side effect, I think it should *mostly* be transparent to users. Except for branches I haven't caught....

++ on adding javadoc for this.

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java [hunk 8]
```diff
@@ -203,6 +203,14 @@ public Response performRequest(String method, String endpoint, Map<String, Strin
      * they previously failed (the more failures, the later they will be retried). In case of failures all of the alive nodes (or dead
      * nodes that deserve a retry) are retried until one responds or none of them does, in which case an {@link IOException} will be thrown.
      *
+     * This method works by performing an asynchronous call and the waiting
```
Comment (javanna) [inline client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: remove "the" ?

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java [hunk 9]
```diff
@@ -203,6 +203,14 @@ public Response performRequest(String method, String endpoint, Map<String, Strin
...
+     * for the result. If the asynchronous call throws and exception we wrap
```
Comment (javanna) [inline client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: s/and/an

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 8 above)
Comment (nik9000) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: ++

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 9 above)
Comment (nik9000) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: Thanks!

**Comment by nik9000** [comment]
@elasticmearchin, retest this please.

File: client/rest/src/main/java/org/elasticsearch/client/RestClient.java (hunk 1 above)
Comment (albertzaharovits) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: @nik9000 do you think it would be helpful to add another branch for [SSLException](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLException.html) ?

Comment (nik9000) [reply client/rest/src/main/java/org/elasticsearch/client/RestClient.java]: > @nik9000 do you think it would be helpful to add another branch for SSLException ?

Fine with me! I can do it.
