### PR TITLE
ESQL: BUCKET: allow numerical spans as whole numbers

### LINKED ISSUE #104646: [ES|QL] auto_bucket annotation is missing the string type of third and fourth args
### Elasticsearch Version

8.13.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

In the `auto_bucket` annotation is missing the `string` type for the third and fourth arguments.
See the `show functions` output:

```
double|date auto_bucket(field:integer|long|double|date, buckets:integer, from:integer|long|double|date, to:integer|long|double|date)
```

### Steps to Reproduce

```
show functions | where name == "auto_bucket"
```

### Logs (if relevant)

_No response_

### LINKED ISSUE #105375: [ES|QL] auto_bucket() throws error on literal number as third argument
### Elasticsearch Version

8.13.0 @ 7c039b172836b90a77099ca5ba79115dca979b0e

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error:

```
"verification_exception\n\tRoot causes:\n\t\tverification_exception: Found 1 problem\nline 1:11: third argument of [auto_bucket(now(), 5, 5, 5)] must be [datetime or string], found value [5] type [integer]"
```

is thrown with the following queries:

```
row var = auto_bucket(now(), 5, 5, 5)
row auto_bucket(now(), 5, 5, 5)
from index | auto_bucket(now(), 5, 5, 5)
```

In the `auto_bucket` documentation is stated that both the third and fourth args can be either a number of a date string.
I guess this is mostly a documentation issue as the string version is required due to the date type passed as first argument, but need confirmation here.
In such case I would expect:
* to make the documentation more clear on this
* to have a better error message that clarifies the context.

### Steps to Reproduce

See above.

### Logs (if relevant)

_No response_

### LINKED ISSUE #109340: [ES|QL] Possible improvements of the ergonomics for the `bucket` function
### Description

Right now the signature for the `bucket` signature, in particular for its non-date version, is really picky.
I wonder if it's possible to introduce some implicit `double` casting for the last 3 arguments when the first one is of numeric type?

That would avoid doing things like this for the user:
```
from index | stats count() by bucket(bytes, 100::long)
```

to something simpler as:

```
from index | stats count() by bucket(bytes, 100)
```

Implicit casting is already happening for many other operators and field types (i.e. `ip`) so I'd assume this is not a primer.
The potential outcome of this implicit casting would simplify user experience on `bucket` function usage (probably make the documentation a little bit lengthly for the all the combinations).

### PR DESCRIPTION
**Pull request by bpintea**
This laxes the check on numerical spans to allow them be specified as whole numbers. So far it was required that they be provided as a double.

This also expands the tests for date ranges to include string types.

Resolves #109340, resolves #104646, resolves #105375.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java [hunk 1]
```diff
@@ -336,9 +333,18 @@ protected TypeResolution resolveType() {
                 : resolution.and(checkArgsCount(2)); // temporal amount
         }
         if (fieldType.isNumeric()) {
-            return bucketsType.isWholeNumber()
-                ? checkArgsCount(4).and(() -> isNumeric(from, sourceText(), THIRD)).and(() -> isNumeric(to, sourceText(), FOURTH))
-                : isNumeric(buckets, sourceText(), SECOND).and(checkArgsCount(2));
+            return isNumeric(buckets, sourceText(), SECOND).and(() -> {
+                if (bucketsType.isRationalNumber()) {
+                    return checkArgsCount(2);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java:338]: Do we have (verifier) test cases for when the 2nd argument is rational but we provide more than 2 arguments?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java [hunk 2]
```diff
@@ -336,9 +333,18 @@ protected TypeResolution resolveType() {
                 : resolution.and(checkArgsCount(2)); // temporal amount
         }
         if (fieldType.isNumeric()) {
-            return bucketsType.isWholeNumber()
-                ? checkArgsCount(4).and(() -> isNumeric(from, sourceText(), THIRD)).and(() -> isNumeric(to, sourceText(), FOURTH))
-                : isNumeric(buckets, sourceText(), SECOND).and(checkArgsCount(2));
+            return isNumeric(buckets, sourceText(), SECOND).and(() -> {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java:336]: Do we have (verifier) test cases for when the first argument is numeric but the second is not?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java [hunk 3]
```diff
@@ -336,9 +333,18 @@ protected TypeResolution resolveType() {
...
+                if (bucketsType.isRationalNumber()) {
+                    return checkArgsCount(2);
+                } else { // second arg is a whole number: either a span, but as a whole, or count, and we must expect a range
+                    var resolution = checkArgsCount(2);
+                    if (resolution.resolved() == false) {
+                        resolution = checkArgsCount(4).and(() -> isNumeric(from, sourceText(), THIRD))
+                            .and(() -> isNumeric(to, sourceText(), FOURTH));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java:343]: Do we have (verifier) test cases for when the args count is higher than 4, or the 3rd and 4th are not numeric?

**Review by alex-spies — APPROVED** [review]
Generally LGTM, but I couldn't find tests for the type validation in case a `BUCKET` query is invalid. (Though, it's been a while since I looked at `BUCKET` and only made a cursory search for the tests.) Should they actually be missing, maybe we should add them.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 4]
```diff
@@ -374,6 +374,66 @@ public void testGroupingInsideGrouping() {
         );
     }
 
+    public void testInvalidBucketCalls() {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:377]: Thank you! I think the validation for `BUCKET` is complex enough that we'll be very happy about this test when we make changes in the future.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 5]
```diff
@@ -3514,6 +3514,49 @@ public void testBucketWithAggExpression() {
         assertThat(agg.groupings().get(0), is(ref));
     }
 
+    public void testBucketWithNonFoldingArgs() {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3517]: nit: wouldn't these be better placed in the `VerifierTests`? I wouldn't know to look here for these tests (except when they're failing :) )

**Review by alex-spies — APPROVED** [review]
Thanks for the iteration @bpintea !

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/bucket.csv-spec [hunk 6]
```diff
@@ -314,6 +314,21 @@ FROM sample_data
 3              |2025-10-01T00:00:00.000Z
 ;
 
+bucketByYearLowBucketCount#[skip:-8.13.99, reason:BUCKET extended in 8.14]
```
[the remark this answers is not in the document]
Comment (bpintea) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/bucket.csv-spec:317]: Not directly: it just notes that we're not really respecting the contract of providing up to the number of buckets requested, once the bucket size reaches a year.
The skip is accurate, the test isn't using any newly introduced change.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/bucket.csv-spec [hunk 7]
```diff
@@ -393,6 +408,17 @@ ROW long = TO_LONG(100), double = 99., int = 100
 99.0           |0.0            |99.0
 ;
 
+// identical results as above
+bucketNumericMixedTypesIntegerSpans
+required_capability: bucket_whole_number_as_span
+ROW long = TO_LONG(100), double = 99., int = 100
+| STATS BY b1 = BUCKET(long, double::int), b2 = BUCKET(double, long), b3 = BUCKET(int, 49.5)
```
[the remark this answers is not in the document]
Comment (bpintea) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/bucket.csv-spec:415]: > Doesn't it have to be a constant for the STATS to make sense?

It doesn't have to be a constant, but it has to be a foldable expression (i.e. a field declared with `ROW`).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java:352]: I've added new tests around incorrect arguments, both in number and type, thanks.
(This should have been done in my earlier change already.)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java:350]: Added.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java:357]: Added some.
Not for a higher than 4 count, though, since this would be a general parser exception, raised when resolving the function.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java (hunk 5 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3517]: It turns out we do the validation past optimisations, to be able to take the folding into account. (Not sure if we'll ever need this for anything else than supporting ROW, but that's how it now works.)

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/bucket.csv-spec (hunk 7 above)
[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/bucket.csv-spec:415]: `row` is a good source of constants, but we can also define foldable values in `eval` (and used with `from`). Just wanted to point out that "foldable expression" isn't always something that comes from `row`.
