### PR TITLE
Increment failuresAfterMeaningfulProgress before retry

### LINKED ISSUE #104436: [CI] S3BlobContainerRetriesTests testReadRetriesAfterMeaningfulProgress failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/iwun2ojtowaqw/tests/:modules:repository-s3:test/org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests/testReadRetriesAfterMeaningfulProgress

**Reproduction line:**
```
./gradlew ':modules:repository-s3:test' --tests "org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadRetriesAfterMeaningfulProgress" -Dtests.seed=32A9489643D6159F -Dtests.locale=mt -Dtests.timezone=PNT -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests#testReadRetriesAfterMeaningfulProgress`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testReadRetriesAfterMeaningfulProgress'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 52; received: 21)

  at __randomizedtesting.SeedInfo.seed([32A9489643D6159F:E40A243C8A651765]:0)
  at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
  at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
  at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
  at org.elasticsearch.repositories.s3.S3RetryingInputStream.read(S3RetryingInputStream.java:153)
  at java.io.FilterInputStream.read(FilterInputStream.java:119)
  at java.io.FilterInputStream.read(FilterInputStream.java:95)
  at org.elasticsearch.core.Streams.copy(Streams.java:45)
  at org.elasticsearch.core.Streams.copy(Streams.java:79)
  at org.elasticsearch.common.io.Streams.readFully(Streams.java:189)
  at org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadRetriesAfterMeaningfulProgress(S3BlobContainerRetriesTests.java:580)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by ywangd**
The count for failuresAfterMeaningfulProgress should be incremented before testing whether to retry s3 blob read. This is because we do not want to count failuresAfterMeaningfulProgress towards actual number of failures, i.e. we want to keep retrying if the last attempt has made meaningful progress. 
In addition, failuresAfterMeaningfulProgress should _not_ be incremented on stream openning failures.

Resolves: #104436

### CODE REVIEW

**Comment by ywangd** [comment]
Gentle reminder for review. Thanks!

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java [hunk 1]
```diff
@@ -232,7 +232,7 @@ private void logForRetry(Level level, String action, Exception e) {
                 start + currentOffset,
                 purpose.getKey(),
                 attempt,
-                currentStreamProgress,
+                Math.subtractExact(Math.addExact(start, currentOffset), currentStreamFirstOffset),
```
Comment (DaveCTurner) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java:235]: I'd be inclined to extract this as a private method rather than duplicate the expression, especially since inlining it like this loses the name that explains what it really means.

**Review by DaveCTurner — APPROVED** [review]
LGTM but I'd definitely prefer a `currentStreamProgress()` method unless you object strongly.

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java (hunk 1 above)
Comment (ywangd) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java]: Makes sense. See 9d31e189677ffe358fcc3e69471cff3c4d48a741
