### PR TITLE
Dynamically grow hash in linear counting in HLL

### LINKED ISSUE #141847: ES|QL Circuit Breakers Triggered by Real Kibana Dashboard Workflows
**Summary**

ES|QL is triggering circuit breakers when running realistic Kibana dashboard queries on production-scale datasets (~200GB primary data).
This behavior has been observed by an experienced Elastic Stack user (Alexis) and reproduced in live walkthroughs.

This appears to be an operational readiness gap rather than an isolated performance issue, potentially impacting broader ES|QL adoption and default usage.

**Impact**

Circuit breakers triggered under realistic analytics workloads

Significantly higher memory usage compared to DSL equivalents

Risk to reliable customer experience in dashboard-heavy scenarios

 **Environment**

Cluster

6 GCP CPU-optimized nodes

Data scale

~200GB primary data

Large telemetry indices (up to 140GB)

Multiple time-series billing/activity datasets

High replica counts (often 5)

**Representative Queries**
Query 1 — DISTINCT-heavy telemetry aggregation
FROM cloud-tracker-index_telemetry*
| WHERE NOT STARTS_WITH(datastream.name, ".")
| STATS
  search_count = SUM(index.search_total),
  search_time = SUM(index.search_time_ms),
  dataset_size = SUM(index.dataset_size_bytes),
  value_count = COUNT_DISTINCT(@timestamp)
BY datastream.name
| EVAL dataset_size = dataset_size/value_count
| SORT dataset_size DESC
| LIMIT 50
| EVAL avg_search_count = search_count / value_count
| EVAL avg_search_time = search_time::DOUBLE / value_count
| EVAL avg_time_per_search = avg_search_time / avg_search_count
| SORT avg_time_per_search DESC
| LIMIT 10

Query 2 — Time-bucketed cost + telemetry correlation
FROM cloud-tracker-billing*,cloud-tracker-index_telemetry*
| STATS
  cost = SUM(cost) WHERE event.dataset == "billing",
  dataset_size = SUM(index.dataset_size_bytes)
    WHERE event.dataset == "index_telemetry",
  docs_count = SUM(index.docs_count)
    WHERE event.dataset == "index_telemetry"
BY @timestamp = BUCKET(@timestamp, 1 day)
| EVAL dataset_size = dataset_size/1024/1024/1024/1024
| EVAL cost_per_TB = cost / dataset_size
| EVAL cost_per_b_docs = cost / (docs_count/1000000000)
| DROP cost, dataset_size
| LIMIT 10000

**Observed Behavior**

Circuit breakers triggered during dashboard execution

Large memory spikes vs DSL

Reproducible at real data scale

(Zoom recording + screenshots available)

**Key Investigation Areas**

Gaps between current scale tests and real Kibana workflows

Memory amplification due to ES|QL parallelism

High footprint of DISTINCT-heavy operators

Impact of concurrency and serverless constraints

**Proposed Next Steps**

Reproduce queries internally at scale

Profile memory usage per operator/phase

Compare against current benchmark coverage

Identify optimization opportunities

Add workflow-level benchmarks

### PR DESCRIPTION
**Pull request by MattAlp**
This change dynamically grows the hash inside each linear counting instance independently to address high memory usage in count_distinct, especially in cases with a large number of groups (1M+) that each contain a small number of distinct values (<3000). Instead of eagerly allocating 16K for each grouping, this dynamic approach serves as an immediate optimization. The long-term plan, however, is to create a new, separate HLLState for ES|QL that is more friendly to Block/Vector and ES|QL aggregations.

Contributors: @MattAlp @dnhatn

Closes #141847
Relates #142333

### CODE REVIEW

**Comment by MattAlp** [comment]
Buildkite benchmark this with clickbench please

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/HyperLogLogPlusPlus.java [hunk 1]
```diff
@@ -70,33 +86,112 @@ public HyperLogLogPlusPlus(int precision, BigArrays bigArrays, long initialBucke
...
+            return lc.size(denseOrd);
+        }
+
+        @Override
+        public void forEachEncoded(IntConsumer consumer) {
+            if (useSmall) {
+                smallLc.forEachEncoded(bucketOrd, consumer);
+                return;
+            }
+            if (denseOrd >= lc.hll.maxOrd()) {
```
Comment (parkertimmins) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/HyperLogLogPlusPlus.java]: Can this occur?

**Comment by dnhatn** [comment]
From @martijnvg 

I did a quick check with q13 and noticed a very significant improvement with this change.

Baseline using main:

```
repeat 10 curl -s -k -XPOST -H "Content-Type: application/json" -d '{"query": "FROM hits | WHERE SearchPhrase != \"\" | STATS u = COUNT_DISTINCT(UserID, 200) BY SearchPhrase | SORT u DESC | LIMIT 10"}' "http://localhost:9200/_query" | jq .took
18306
12878
10293
9630
16737
17326
15988
16419
10495
9949
```

Contender using this PR:

```
repeat 10 curl -s -k -XPOST -H "Content-Type: application/json" -d '{"query": "FROM hits | WHERE SearchPhrase != \"\" | STATS u = COUNT_DISTINCT(UserID, 200) BY SearchPhrase | SORT u DESC | LIMIT 10"}' "http://localhost:9200/_query" | jq .took
9061
6384
5105
4173
4062
3475
3187
2986
3235
3683
```

File: benchmarks/src/main/java/org/elasticsearch/benchmark/compute/operator/AggregatorBenchmark.java [hunk 2]
```diff
@@ -129,7 +128,13 @@ static void selfTest() {
                 for (String op : AggregatorBenchmark.class.getField("op").getAnnotationsByType(Param.class)[0].value()) {
                     for (String blockType : AggregatorBenchmark.class.getField("blockType").getAnnotationsByType(Param.class)[0].value()) {
                         for (String filter : AggregatorBenchmark.class.getField("filter").getAnnotationsByType(Param.class)[0].value()) {
-                            run(grouping, op, blockType, filter, 10);
+                            for (String groups : AggregatorBenchmark.class.getField("groups").getAnnotationsByType(Param.class)[0]
```
Comment (MattAlp) [inline benchmarks/src/main/java/org/elasticsearch/benchmark/compute/operator/AggregatorBenchmark.java]: This was checked in while I was working on the original 3-tier approach. We can check it out of this PR or open a ticket to further improve the HLL or aggregator benchmarks against different distributions of group size, density, etc

**Review by MattAlp — COMMENTED** [review]
Can't self-approve but reviewed - Nhat's engine-specific changes and integration LGTM

File: benchmarks/src/main/java/org/elasticsearch/benchmark/compute/operator/AggregatorBenchmark.java (hunk 2 above)
Comment (dnhatn) [reply benchmarks/src/main/java/org/elasticsearch/benchmark/compute/operator/AggregatorBenchmark.java]: ++ I've removed this in https://github.com/elastic/elasticsearch/pull/142047/commits/5067d521a67fb4317b1a57a3994f2dfd0baa6eea

**Comment by MattAlp** [comment]
We could also raise the default precision of `count_distinct()` in this PR as a QoL change.

**Review by dnhatn — APPROVED** [review]

**Comment by dnhatn** [comment]
> We could also raise the default precision of count_distinct() in this PR as a QoL change.

Let's make that change after #42333

**Comment by dnhatn** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/142347)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
