### PR TITLE
Force execution of finish shard bulk request

### LINKED ISSUE #51904: Elasticsearch is fsyncing on transport threads
It is currently possible for a cluster state listener to execute a transport fsync.

1. Currently in `TransportShardBulkAction` it is possible that a shard operations will trigger a mapping update. 
2. When this happens Elasticsearch [registers](https://github.com/elastic/elasticsearch/blob/3ad8aa6d46580229823d298e9ce68ba3aaadc3d6/server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java#L125) a `ClusterStateObserver.Listener` to continue when the mapping is complete. 
3. This listener will eventually attempt to [reschedule](https://github.com/elastic/elasticsearch/blob/3ad8aa6d46580229823d298e9ce68ba3aaadc3d6/server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java#L160) the write operation. 
4. If the write thread pool cannot accept this operation, the `onRejection` callback will fail outstanding operations and [complete](https://github.com/elastic/elasticsearch/blob/3ad8aa6d46580229823d298e9ce68ba3aaadc3d6/server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java#L182) the request (probably trying to notify of the operations that were able to be completed).
5. Completing a `TransportShardBulkAction` will attempt to fsync or refresh as [necessary](https://github.com/elastic/elasticsearch/blob/062f9f03bfcdf8e3f57eb6a30d49fa5ec89c777f/server/src/main/java/org/elasticsearch/action/support/replication/TransportWriteAction.java#L145) after initiating replication. 

Here is a transport_worker stack trace. I also think these listeners might be executed on cluster state threads?

```
ensureSynced:808, Translog (org.elasticsearch.index.translog)
ensureSynced:824, Translog (org.elasticsearch.index.translog)
ensureTranslogSynced:513, InternalEngine (org.elasticsearch.index.engine)
write:2980, IndexShard$5 (org.elasticsearch.index.shard)
processList:108, AsyncIOProcessor (org.elasticsearch.common.util.concurrent)
drainAndProcessAndRelease:96, AsyncIOProcessor (org.elasticsearch.common.util.concurrent)
put:84, AsyncIOProcessor (org.elasticsearch.common.util.concurrent)
sync:3003, IndexShard (org.elasticsearch.index.shard)
run:320, TransportWriteAction$AsyncAfterWriteAction (org.elasticsearch.action.support.replication)
runPostReplicationActions:163, TransportWriteAction$WritePrimaryResult (org.elasticsearch.action.support.replication)
handlePrimaryResult:136, ReplicationOperation (org.elasticsearch.action.support.replication)
accept:-1, 359201671 (org.elasticsearch.action.support.replication.ReplicationOperation$$Lambda$3596)
onResponse:63, ActionListener$1 (org.elasticsearch.action)
onResponse:163, ActionListener$4 (org.elasticsearch.action)
completeWith:336, ActionListener (org.elasticsearch.action)
finishRequest:186, TransportShardBulkAction$2 (org.elasticsearch.action.bulk)
onRejection:182, TransportShardBulkAction$2 (org.elasticsearch.action.bulk)
onRejection:681, ThreadContext$ContextPreservingAbstractRunnable (org.elasticsearch.common.util.concurrent)
execute:90, EsThreadPoolExecutor (org.elasticsearch.common.util.concurrent)
lambda$doRun$0:160, TransportShardBulkAction$2 (org.elasticsearch.action.bulk)
accept:-1, 95719050 (org.elasticsearch.action.bulk.TransportShardBulkAction$2$$Lambda$3833)
onResponse:63, ActionListener$1 (org.elasticsearch.action)
lambda$onResponse$0:289, TransportShardBulkAction$3 (org.elasticsearch.action.bulk)
run:-1, 1539599321 (org.elasticsearch.action.bulk.TransportShardBulkAction$3$$Lambda$3857)
onResponse:251, ActionListener$5 (org.elasticsearch.action)
onNewClusterState:125, TransportShardBulkAction$1 (org.elasticsearch.action.bulk)
onNewClusterState:311, ClusterStateObserver$ContextPreservingListener (org.elasticsearch.cluster)
waitForNextChange:169, ClusterStateObserver (org.elasticsearch.cluster)
waitForNextChange:120, ClusterStateObserver (org.elasticsearch.cluster)
waitForNextChange:112, ClusterStateObserver (org.elasticsearch.cluster)
lambda$shardOperationOnPrimary$1:122, TransportShardBulkAction (org.elasticsearch.action.bulk)
accept:-1, 1672258490 (org.elasticsearch.action.bulk.TransportShardBulkAction$$Lambda$3831)
onResponse:277, TransportShardBulkAction$3 (org.elasticsearch.action.bulk)
onResponse:273, TransportShardBulkAction$3 (org.elasticsearch.action.bulk)
onResponse:282, ActionListener$6 (org.elasticsearch.action)
onResponse:116, MappingUpdatedAction$1 (org.elasticsearch.cluster.action.index)
onResponse:113, MappingUpdatedAction$1 (org.elasticsearch.cluster.action.index)
lambda$executeLocally$0:97, NodeClient (org.elasticsearch.client.node)
accept:-1, 2099146048 (org.elasticsearch.client.node.NodeClient$$Lambda$2772)
onResponse:144, TaskManager$1 (org.elasticsearch.tasks)
onResponse:138, TaskManager$1 (org.elasticsearch.tasks)
handleResponse:54, ActionListenerResponseHandler (org.elasticsearch.action)
handleResponse:1053, TransportService$ContextRestoreResponseHandler (org.elasticsearch.transport)
doRun:220, InboundHandler$1 (org.elasticsearch.transport)
run:37, AbstractRunnable (org.elasticsearch.common.util.concurrent)
execute:196, EsExecutors$DirectExecutorService (org.elasticsearch.common.util.concurrent)
handleResponse:212, InboundHandler (org.elasticsearch.transport)
messageReceived:138, InboundHandler (org.elasticsearch.transport)
inboundMessage:102, InboundHandler (org.elasticsearch.transport)
inboundMessage:664, TcpTransport (org.elasticsearch.transport)
consumeNetworkReads:688, TcpTransport (org.elasticsearch.transport)
consumeReads:276, MockNioTransport$MockTcpReadWriteHandler (org.elasticsearch.transport.nio)
handleReadBytes:228, SocketChannelContext (org.elasticsearch.nio)
read:40, BytesChannelContext (org.elasticsearch.nio)
handleRead:139, EventHandler (org.elasticsearch.nio)
handleRead:151, TestEventHandler (org.elasticsearch.transport.nio)
handleRead:420, NioSelector (org.elasticsearch.nio)
processKey:246, NioSelector (org.elasticsearch.nio)
singleLoop:174, NioSelector (org.elasticsearch.nio)
runLoop:131, NioSelector (org.elasticsearch.nio)
run:-1, 461835914 (org.elasticsearch.nio.NioSelectorGroup$$Lambda$1709)
run:835, Thread (java.lang)
```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently the shard bulk request can be rejected by the write threadpool
after a mapping update. This introduces a scenario where the mapping
listener thread will attempt to finish the request and fsync. This
thread can potentially be a transport thread. This commit fixes this
issue by forcing the finish action to happen on the write threadpool.

Fixes #51904.

### CODE REVIEW

**Comment by tbrooks8** [comment]
How far should we back port this?

File: server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java [hunk 1]
```diff
@@ -179,7 +179,20 @@ public void onRejection(Exception e) {
...
                         context, null);
                 }
-                finishRequest();
+
+                // Force the execution to finish the request
+                executor.execute(new ActionRunnable<>(listener) {
+
+                    @Override
+                    protected void doRun() {
+                        finishRequest();
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java]: I was thinking that rather than scheduling only `finishRequest` on the write thread pool, we should execute the entirety of `onRejection` on the write thread pool (and still forcing execution, since rejecting execution here would be very bad): https://github.com/elastic/elasticsearch/blob/3ad8aa6d46580229823d298e9ce68ba3aaadc3d6/server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java#L160

The reason I think this is because we're still doing work in `onRejection` that is linear in the number of documents in the bulk request. It seems we'd want to get that off of the networking/cluster state applier thread too given that we're going to fork anyway.

**Review by jasontedor — COMMENTED** [review]
I left a comment for consideration.

File: server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java]: I wonder if we should instead let `onRejection` force-push the `onRejection` handling onto the queue of the requested executor. The current "direct" handling kind of prioritizes the `onRejection` handling over everything else in the queue, which I think there is really no good reason for.

Looking at various `onRejection` handlers, some call `listener.onFailure` and verifying that none of those do bad things is tricky.

Also notice that `onAfter` is also called in the caller thread when requests are rejected, this poses similar issues (not that I found a smoking gun there).

Finally, notice that `AbstractRunnable.onRejection` by default calls `onFailure`.

I doubt that we careful consider that `onAfter` and `onFailure` might run in the current thread when using `AbstractRunnable` and executing the `onRejection` handling on the target thread-pool would fix this, making it easier to reason about.

That said, I think this PR is good and I am not objecting to it going in. Following my suggestion is likely to surface a few additional things to resolve.

Comment (tbrooks8) [reply server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java]: I made @jasontedor change.

I think maybe Henning's comment about maybe `onRejection` should be executed on the thread pool anyway is beyond the scope of this PR? Or at least a larger discussion.

File: server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java [hunk 2]
```diff
@@ -170,16 +170,28 @@ protected void doRun() throws Exception {
...
-                while (context.hasMoreOperationsToExecute()) {
-                    context.setRequestToExecute(context.getCurrent());
-                    final DocWriteRequest<?> docWriteRequest = context.getRequestToExecute();
-                    onComplete(
-                        exceptionToResult(
-                            e, primary, docWriteRequest.opType() == DocWriteRequest.OpType.DELETE, docWriteRequest.version()),
-                        context, null);
-                }
-                finishRequest();
+                // Force the execution to finish the request
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportShardBulkAction.java]: It's probably worth a comment here why we fork to the executor (since it's not obvious from the code).

**Review by jasontedor — APPROVED** [review]
I left a comment, but this LGTM.

**Comment by jasontedor** [comment]
> How far should we back port this?

I think to the 7.6, 7.x, and master branches.
