### PR TITLE
Check file entitlements on the Lucene FilterFileSystem in tests

### LINKED ISSUE #127190: [CI] SSLErrorMessageFileTests testMessageForTrustStoreOutsideConfigDir failing
**Build Scans:**
- [elasticsearch-periodic #9208 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/snn7t5pyqccqw)
- [elasticsearch-periodic #9199 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/hnhgppabwxlvk)
- [elasticsearch-periodic #9199 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/4wjifitjbtgl6)
- [elasticsearch-periodic #9192 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/5y5rnjjbnhkjs)
- [elasticsearch-periodic #9192 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/kxfeb6fac7ojo)
- [elasticsearch-periodic #9192 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/toaahqgemozpq)
- [elasticsearch-periodic #9185 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/j4xr2pye4p37u)
- [elasticsearch-periodic #9185 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/xiouzijk4skvy)
- [elasticsearch-periodic #9185 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/5syxxcmngot3i)
- [elasticsearch-periodic #9178 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/gbp4id5qean5i)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.testMessageForTrustStoreOutsideConfigDir" -Dtests.seed=18570F5051FB3A54 -Dtests.locale=en-RW -Dtests.timezone=Cuba -Druntime.java=21
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testMessageForTrustStoreOutsideConfigDir),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a throwable with message of "failed to load SSL configuration [xpack.security.authc.realms.saml.saml1.ssl] - cannot read configured [jks] keystore (as a truststore) [/this/path/is/outside/the/config/directory/file.error] because access to read the file is blocked; SSL resources should be placed in the [/dev/shm/bk/bk-agent-prod-gcp-1751893365610413010/elastic/elasticsearch-periodic/x-pack/plugin/security/build/testrun/test/temp/org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests_18570F5051FB3A54-001/tempDir-075/config] directory"
     but: was <org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.authc.realms.saml.saml1.ssl] - cannot read configured [jks] keystore (as a truststore) [/this/path/is/outside/the/config/directory/file.error] because the file does not exist> at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:622)
```

**Issue Reasons:**
- [9.1] 58 consecutive failures in test testMessageForTrustStoreOutsideConfigDir
- [9.1] 22 consecutive failures in step openjdk21_checkpart4_java-matrix
- [9.1] 21 consecutive failures in step openjdk23_checkpart4_java-matrix
- [9.1] 15 consecutive failures in step openjdk21_checkpart4_java-fips-matrix
- [9.1] 22 consecutive failures in pipeline elasticsearch-periodic
- [9.1] 58 failures in test testMessageForTrustStoreOutsideConfigDir (100.0% fail rate in 58 executions)
- [9.1] 22 failures in step openjdk21_checkpart4_java-matrix (100.0% fail rate in 22 executions)
- [9.1] 21 failures in step openjdk23_checkpart4_java-matrix (100.0% fail rate in 21 executions)
- [9.1] 15 failures in step openjdk21_checkpart4_java-fips-matrix (100.0% fail rate in 15 executions)
- [9.1] 22 failures in pipeline elasticsearch-periodic (100.0% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #127192: [CI] SSLErrorMessageFileTests testMessageForPemKeyOutsideConfigDir failing
**Build Scans:**
- [elasticsearch-periodic #9151 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/pxfryucax3knw)
- [elasticsearch-periodic #9143 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/lqmgnpiyo5m7o)
- [elasticsearch-periodic #9143 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/qtpo4webq3rvq)
- [elasticsearch-periodic #9143 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/yhe6ohed7rrau)
- [elasticsearch-periodic #9136 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/uwio6ndlfmovc)
- [elasticsearch-periodic #9136 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/ltfdgn73klk42)
- [elasticsearch-periodic #9136 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/ymxh2kqlehfwm)
- [elasticsearch-periodic #9129 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/yixyot6n7smhg)
- [elasticsearch-periodic #9129 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/bgvq7zalwipvm)
- [elasticsearch-periodic #9129 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/eequk62wjw3dw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.testMessageForPemKeyOutsideConfigDir" -Dtests.seed=ECBFD59D1A3F855D -Dtests.locale=uz-Arab -Dtests.timezone=US/Alaska -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testMessageForPemKeyOutsideConfigDir),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a throwable with message of "failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM private key [/this/path/is/outside/the/config/directory/file.error] because access to read the file is blocked; SSL resources should be placed in the [/dev/shm/bk/bk-agent-prod-gcp-1751663488486756059/elastic/elasticsearch-periodic/x-pack/plugin/security/build/testrun/test/temp/org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests_ECBFD59D1A3F855D-001/tempDir-020/config] directory"
     but: was <org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM private key [/this/path/is/outside/the/config/directory/file.error] because the file does not exist> at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:622)
```

**Issue Reasons:**
- [main] 63 consecutive failures in test testMessageForPemKeyOutsideConfigDir
- [main] 21 consecutive failures in step openjdk21_checkpart4_java-fips-matrix
- [main] 21 consecutive failures in step openjdk21_checkpart4_java-matrix
- [main] 21 consecutive failures in step openjdk23_checkpart4_java-matrix
- [main] 22 consecutive failures in pipeline elasticsearch-periodic
- [main] 63 failures in test testMessageForPemKeyOutsideConfigDir (100.0% fail rate in 63 executions)
- [main] 21 failures in step openjdk21_checkpart4_java-fips-matrix (100.0% fail rate in 21 executions)
- [main] 21 failures in step openjdk21_checkpart4_java-matrix (100.0% fail rate in 21 executions)
- [main] 21 failures in step openjdk23_checkpart4_java-matrix (100.0% fail rate in 21 executions)
- [main] 22 failures in pipeline elasticsearch-periodic (100.0% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #127193: [CI] SSLErrorMessageFileTests class failing
**Build Scans:**
- [elasticsearch-periodic #9306 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/foocsf4y6qdle)
- [elasticsearch-periodic #9306 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/kmjavzohlj5ck)
- [elasticsearch-periodic #9306 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/3zwaa4m2a6wdc)
- [elasticsearch-periodic #9299 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/26jn2bf4gidfq)
- [elasticsearch-periodic #9299 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/7m7fj5aw2q72k)
- [elasticsearch-periodic #9299 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/qf5bp7blef4sw)
- [elasticsearch-periodic #9292 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/4temomnsn56mw)
- [elasticsearch-periodic #9292 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/dxpt2gx2cfzyc)
- [elasticsearch-periodic #9292 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/2aaj2uhrawx7w)
- [elasticsearch-periodic #9285 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/ymg63bcfwf6yy)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.testMessageForCertificateAuthoritiesOutsideConfigDir" -Dtests.seed=1C3A31FDE30FAAA5 -Dtests.locale=or-IN -Dtests.timezone=Africa/Juba -Druntime.java=23
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a throwable with message of "failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM certificate_authorities [/this/path/is/outside/the/config/directory/file.error] because access to read the file is blocked; SSL resources should be placed in the [/dev/shm/bk/bk-agent-prod-gcp-1752296472092547762/elastic/elasticsearch-periodic/x-pack/plugin/security/build/testrun/test/temp/org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests_1C3A31FDE30FAAA5-001/tempDir-046/config] directory"
     but: was <org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM certificate_authorities [/this/path/is/outside/the/config/directory/file.error] because the file does not exist> at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:622)
```

**Issue Reasons:**
- [9.1] 3 consecutive failures in class org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests
- [9.1] 19 consecutive failures in step openjdk21_checkpart4_java-fips-matrix
- [9.1] 21 consecutive failures in step openjdk23_checkpart4_java-matrix
- [9.1] 22 consecutive failures in step openjdk21_checkpart4_java-matrix
- [9.1] 62 failures in class org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests (9.6% fail rate in 644 executions)
- [9.1] 19 failures in step openjdk21_checkpart4_java-fips-matrix (100.0% fail rate in 19 executions)
- [9.1] 21 failures in step openjdk23_checkpart4_java-matrix (100.0% fail rate in 21 executions)
- [9.1] 22 failures in step openjdk21_checkpart4_java-matrix (100.0% fail rate in 22 executions)
- [9.1] 22 failures in pipeline elasticsearch-periodic (100.0% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #127686: [CI] SSLErrorMessageFileTests testMessageForPemCertificateOutsideConfigDir failing
**Build Scans:**
- [elasticsearch-periodic #9264 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/g572tfcnk2ihw)
- [elasticsearch-periodic #9264 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/nlt6fkbq4ffla)
- [elasticsearch-periodic #9257 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/3cspsef5wbc74)
- [elasticsearch-periodic #9257 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/ijhteyama72bm)
- [elasticsearch-periodic #9257 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/mimpzocrv27yq)
- [elasticsearch-periodic #9250 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/czlwgdtxytoxi)
- [elasticsearch-periodic #9250 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/xko5s3q4nl524)
- [elasticsearch-periodic #9250 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/ibr7rjutb7msm)
- [elasticsearch-periodic #9243 / openjdk21_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/6gmxovpqdp6sa)
- [elasticsearch-periodic #9243 / openjdk21_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/7vkckp6owk33u)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.testMessageForPemCertificateOutsideConfigDir" -Dtests.seed=A06BE891E8BDF6AB -Dtests.locale=es-BO -Dtests.timezone=Etc/GMT+2 -Druntime.java=23
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMessageForPemCertificateOutsideConfigDir'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a throwable with message of "failed to load SSL configuration [xpack.http.ssl] - cannot read configured PEM certificate [/this/path/is/outside/the/config/directory/file.error] because access to read the file is blocked; SSL resources should be placed in the [/dev/shm/bk/bk-agent-prod-gcp-1752123562771052939/elastic/elasticsearch-periodic/x-pack/plugin/security/build/testrun/test/temp/org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests_A06BE891E8BDF6AB-001/tempDir-016/config] directory"
     but: was <org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.http.ssl] - cannot read configured PEM certificate [/this/path/is/outside/the/config/directory/file.error] because the file does not exist> at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:622)
```

**Issue Reasons:**
- [9.1] 59 consecutive failures in test testMessageForPemCertificateOutsideConfigDir
- [9.1] 22 consecutive failures in step openjdk23_checkpart4_java-matrix
- [9.1] 22 consecutive failures in step openjdk21_checkpart4_java-matrix
- [9.1] 15 consecutive failures in step openjdk21_checkpart4_java-fips-matrix
- [9.1] 22 consecutive failures in pipeline elasticsearch-periodic
- [9.1] 59 failures in test testMessageForPemCertificateOutsideConfigDir (100.0% fail rate in 59 executions)
- [9.1] 22 failures in step openjdk23_checkpart4_java-matrix (100.0% fail rate in 22 executions)
- [9.1] 22 failures in step openjdk21_checkpart4_java-matrix (100.0% fail rate in 22 executions)
- [9.1] 15 failures in step openjdk21_checkpart4_java-fips-matrix (100.0% fail rate in 15 executions)
- [9.1] 22 failures in pipeline elasticsearch-periodic (100.0% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mosche**
So far most file entitlement checks have been trivially allowed due to usage of the Lucene FilterFileSystem.
This makes sure we properly check for that file system in tests.

Fixes #127686
Fixes #127193
Fixes #127192
Fixes #127190

Relates to ES-12210
Relates to ES-12242

### CODE REVIEW

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/PathLookupImpl.java [hunk 1]
```diff
@@ -75,4 +75,9 @@ public Stream<Path> resolveSettingPaths(BaseDir baseDir, String settingName) {
             .toList();
         return getBaseDirPaths(baseDir).flatMap(path -> relativePaths.stream().map(path::resolve));
     }
+
+    @Override
+    public boolean isPathOnDefaultFilesystem(Path path) {
+        return path.getFileSystem().getClass() != DEFAULT_FILESYSTEM_CLASS;
```
Comment (ldematte) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/PathLookupImpl.java]: Isn't this the other way around?

Comment (mosche) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/PathLookupImpl.java]: 😮‍💨 thanks @ldematte , good catch! ❤️

**Review by ldematte — APPROVED** [review]
LGTM thanks!

**Comment by ldematte** [comment]
Serverless test failures are unrelated, trying to re-run them.

**Comment by mosche** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/131184)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/131185)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
