### PR TITLE
Fix LogsIndexModeFullClusterRestartIT

### LINKED ISSUE #111306: [CI] LogsIndexModeFullClusterRestartIT testLogsIndexing {cluster=UPGRADED} failing
**Build Scans:**
- [elasticsearch-periodic #3550 / 7.6.2_bwc](https://gradle-enterprise.elastic.co/s/mpr67rbw56leu)
- [elasticsearch-periodic #3550 / 7.5.2_bwc](https://gradle-enterprise.elastic.co/s/inh7dsulgwmri)
- [elasticsearch-periodic #3550 / 7.0.1_bwc](https://gradle-enterprise.elastic.co/s/safi3aoyh7z4w)
- [elasticsearch-periodic #3550 / 7.1.1_bwc](https://gradle-enterprise.elastic.co/s/zaross57fe2jc)
- [elasticsearch-periodic #3550 / 7.7.1_bwc](https://gradle-enterprise.elastic.co/s/d7rfx4wt43epq)
- [elasticsearch-periodic #3550 / 7.12.1_bwc](https://gradle-enterprise.elastic.co/s/ac4m2peicj3we)
- [elasticsearch-periodic #3550 / 7.4.2_bwc](https://gradle-enterprise.elastic.co/s/r56slcunxv2ms)
- [elasticsearch-periodic #3550 / 7.9.3_bwc](https://gradle-enterprise.elastic.co/s/c5f2lx3wl4bie)
- [elasticsearch-periodic #3550 / 7.16.3_bwc](https://gradle-enterprise.elastic.co/s/modk3l56jebry)
- [elasticsearch-periodic #3550 / 7.11.2_bwc](https://gradle-enterprise.elastic.co/s/m6nyb3d5lw4qe)

**Reproduction Line:**
```
./gradlew ":qa:full-cluster-restart:v7.6.2#bwcTest" -Dtests.class="org.elasticsearch.upgrades.LogsIndexModeFullClusterRestartIT" -Dtests.method="testLogsIndexing {cluster=UPGRADED}" -Dtests.seed=ADAC424EC5DBC911 -Dtests.bwc=true -Dtests.locale=ar-AE -Dtests.timezone=Pacific/Kiritimati -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testLogsIndexing%20%7Bcluster%3DUPGRADED%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.upgrades.LogsIndexModeFullClusterRestartIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.
```

**Issue Reasons:**
- [main] 16 consecutive failures in test testLogsIndexing {cluster=UPGRADED}
- [main] 21 failures in test testLogsIndexing {cluster=UPGRADED} (17.9% fail rate in 117 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lkts**
Closes #111306.

### CODE REVIEW

File: qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/upgrades/LogsIndexModeFullClusterRestartIT.java [hunk 1]
```diff
@@ -37,14 +37,14 @@ public class LogsIndexModeFullClusterRestartIT extends ParameterizedFullClusterR
...
         .distribution(DistributionType.DEFAULT)
+        .version(getOldClusterTestVersion())
         .module("constant-keyword")
         .module("data-streams")
         .module("mapper-extras")
         .module("x-pack-aggregate-metric")
         .module("x-pack-stack")
         .setting("xpack.security.enabled", "false")
         .setting("xpack.license.self_generated.type", "trial")
-        .setting("cluster.logsdb.enabled", "true")
```
Comment (lkts) [inline qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/upgrades/LogsIndexModeFullClusterRestartIT.java:47]: We don't need this because we explicitly set index mode in the template. And this setting does not exist in old clusters.

File: qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/upgrades/LogsIndexModeFullClusterRestartIT.java [hunk 2]
```diff
@@ -37,14 +37,14 @@ public class LogsIndexModeFullClusterRestartIT extends ParameterizedFullClusterR
     @ClassRule
     public static final ElasticsearchCluster cluster = ElasticsearchCluster.local()
         .distribution(DistributionType.DEFAULT)
+        .version(getOldClusterTestVersion())
```
Comment (lkts) [inline qa/full-cluster-restart/src/javaRestTest/java/org/elasticsearch/upgrades/LogsIndexModeFullClusterRestartIT.java:40]: This is the main fix.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @lkts
