### PR TITLE
ES|QL: Fix wrong pruning of plans with no output columns

### LINKED ISSUE #120272: ESQL: No rows with JOIN/ENRICH/SAMPLE + EVAL + KEEP
Weird interaction resulting in no rows:

Correct:
```
FROM languages
| DROP language_code
| EVAL language_code = 3
| LOOKUP JOIN languages_lookup ON language_code

# Results:
 language_code | language_name 
---------------+---------------
3              |Spanish
3              |Spanish
3              |Spanish
3              |Spanish
```

Wrong results:
```
FROM languages
| DROP language_code
| EVAL language_code = 3
| LOOKUP JOIN languages_lookup ON language_code
| KEEP language_code

# Results:
 language_code 
---------------
```

You can remove the first DROP if the original index doesn't have the JOIN key column

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/120272

Fixing queries where all the columns from the original index are projected out. 
The expected outcome is that the number of rows is preserved

This means that a query like 

```
FROM idx
| LIMIT 3
| KEEP foo
| DROP foo             // drop all the columns
| EVAL bar = 1
```

that now returns nothing

```
bar
----
```

will start returning values:

```
bar
----
1
1
1
```

This will also apply to aggregations, eg.

```
FROM idx
| KEEP foo
| DROP foo             // drop all the columns
| EVAL bar = 1
| LIMIT 3
| STATS count = count(*)
``` 

that now returns `0`, will start returning the actual count of the rows (`3` in this case)

I don't know if it's breaking (IMHO it's a bug, but it still changes the behavior).

TODO 

- [x] need to add all the queries from the original issue to CSV tests

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 1]
```diff
@@ -203,7 +202,8 @@ protected static Batch<LogicalPlan> operators(boolean local) {
             new PushDownAndCombineOrderBy(),
             new PruneRedundantOrderBy(),
             new PruneRedundantSortClauses(),
-            new PruneLeftJoinOnNullMatchingField()
+            new PruneLeftJoinOnNullMatchingField(),
+            new PruneEmptyAggregates()
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:210]: We need this because our aggs don't know how to deal with no grouping and no aggs at the same time.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/FieldNameUtils.java [hunk 2]
```diff
@@ -237,6 +237,7 @@ public static PreAnalysisResult resolveFieldNames(LogicalPlan parsed, EnrichReso
             // there cannot be an empty list of fields, we'll ask the simplest and lightest one instead: _index
             return new PreAnalysisResult(enrichResolution, IndexResolver.INDEX_METADATA_FIELD, wildcardJoinIndices);
         } else {
+            fieldNames.add(MetadataAttribute.INDEX);
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/FieldNameUtils.java]: This is the actual fix.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/drop.csv-spec [hunk 3]
```diff
@@ -49,29 +49,136 @@ b:integer | x:integer
 ;
 
 dropAllColumns
+required_capability: fix_no_columns
 from employees | keep height | drop height | eval x = 1;
```
Comment (ivancea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/drop.csv-spec]: Can we add a limit after the from here? It's a bit weird otherwise 😆 (Or switch to a smaller index)

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterLookupJoinIT.java [hunk 4]
```diff
@@ -449,6 +449,18 @@ public void testLookupJoinEmptyIndex() throws IOException {
             );
             assertThat(ex.getMessage(), containsString("Unknown column [v] in right side of join"));
         }
+
+        ex = expectThrows(
```
Comment (ivancea) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterLookupJoinIT.java:461]: Is this error related with the fix?

**Review by ivancea — APPROVED** [review]
LGTM!
However, I would wait for Andrei/Alex to check it, as the `_index` fix was initially discarded in favor of a more complete approach when the issue was opened.
This PR covers more areas than the initial approach though, and initially this wasn't a common issue

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/drop.csv-spec (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/drop.csv-spec]: I wanted to keep the original test, but yeah, we can add a limit 😄

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterLookupJoinIT.java (hunk 4 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClusterLookupJoinIT.java:461]: It just surfaced with the fix. The local relation masked the fact that the lookup index was not actually of type `lookup`; now that we have to execute the join, that error starts to happen.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 5]
```diff
@@ -472,7 +473,7 @@ private LocalRelation tableMapAsRelation(Source source, Map<String, Column> mapT
                 // prepare the block for the supplier
                 blocks[i++] = column.values();
             }
-            LocalSupplier supplier = LocalSupplier.of(blocks);
+            LocalSupplier supplier = LocalSupplier.of(blocks.length > 0 ? new Page(blocks) : new Page(0));
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:476]: I am wondering if we could integrate the logic "if the blocks size is 0 then `new Page(0)` otherwise `new Page(blocks)`" somehow with `LocalSupplier`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRowAsLocalRelation.java [hunk 6]
```diff
@@ -29,6 +30,6 @@ protected LogicalPlan rule(Row row, LogicalOptimizerContext context) {
         List<Object> values = new ArrayList<>(fields.size());
         fields.forEach(f -> values.add(f.child().fold(context.foldCtx())));
         var blocks = BlockUtils.fromListRow(PlannerUtils.NON_BREAKING_BLOCK_FACTORY, values);
-        return new LocalRelation(row.source(), row.output(), new CopyingLocalSupplier(blocks));
+        return new LocalRelation(row.source(), row.output(), new CopyingLocalSupplier(blocks.length == 0 ? new Page(0) : new Page(blocks)));
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRowAsLocalRelation.java:33]: Same here about this common logic where a Page is built this way.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/local/CopyingLocalSupplier.java [hunk 7]
```diff
@@ -61,21 +61,21 @@ public class CopyingLocalSupplier implements LocalSupplier {
 
     private final ImmediateLocalSupplier delegate;
 
-    public CopyingLocalSupplier(Block[] blocks) {
-        delegate = new ImmediateLocalSupplier(blocks);
+    public CopyingLocalSupplier(Page page) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/local/CopyingLocalSupplier.java:64]: The javadoc of this class needs an update given the change of the constructor?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneEmptyAggregates.java [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+
+import org.elasticsearch.compute.data.Page;
+import org.elasticsearch.xpack.esql.plan.logical.Aggregate;
+import org.elasticsearch.xpack.esql.plan.logical.LogicalPlan;
+import org.elasticsearch.xpack.esql.plan.logical.local.LocalRelation;
+import org.elasticsearch.xpack.esql.plan.logical.local.LocalSupplier;
+
+import java.util.List;
+
+public final class PruneEmptyAggregates extends OptimizerRules.OptimizerRule<Aggregate> {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneEmptyAggregates.java:25]: It would help to have a javadoc on this rule. I mean, it is obvious what it does, but it would be helpful to read about the situations that lead to an Aggregate with no aggregates and no groupings.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java [hunk 9]
```diff
@@ -51,7 +51,7 @@ protected PhysicalPlan rule(AggregateExec aggregateExec, LocalPhysicalOptimizerC
 
             // for the moment support pushing count just for one field
             List<EsStatsQueryExec.Stat> stats = tuple.v2();
-            if (stats.size() > 1) {
+            if (stats.size() != 1) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:54]: What lead to this change?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/FieldNameUtils.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/FieldNameUtils.java]: Here I think it would be more correct to add this field **after** `FieldNameUtils::withSubfields` is called on the next line. `_index.*` doesn't actually make sense, as we know there is only on `_index` metadata field.

**Review by astefan — COMMENTED** [review]
I think it looks good. Some comments:
1. `from employees | keep salary | eval c = 1 | drop c, salary`

returns 

```
{
    "took": 29,
    "is_partial": false,
    "documents_found": 100,
    "values_loaded": 0,
    "columns": [],
    "values": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
		....
```
This, to me at least (as a regular user of ESQL), seems surprising. This represents a bunch of "empty" virtual rows so to speak. This seems like an implementation detail that leaks into UX, I would have expected the "no columns and Xrows" use case to be handled in a more user friendly way. This also saves some KBs of comm data if potentially this is performed on a large data set.

Conceptually speaking, we are introducing the notion of "nothing/no columns + X rows", but the impact of this concept in the UX is a bit too intrusive imho.

2. looking at the logs of this query
```
ProjectExec[[<all-fields-projected>{r$}#204]]
\_EvalExec[[null[NULL] AS <all-fields-projected>#204]]
  \_EsQueryExec[employees], indexMode[standard], [_doc...
```

This "no columns + X rows" is represented as "<all-fields-projected>" and it is a query that reaches ES in a particular way. I am wondering if this couldn't be, more performant, be implemented as a `count`, meaning we would ask from ES a count of rows and, potentially, on the coordinator node to "expand" this result in a "count" number of "empty" rows.

But this can regarded as food for thought for the future.

3. I would add the following test, as well. This is, essentially, an empty result set but done with, also, dropping all columns:

`from employees | keep salary | eval c = 1 | drop c, salary | where false`

4. another test(s) to add are those related to `inline stats` because it **is also using aggregates** (which were changed as part of this PR).

A simple query, which adds stuff to rows, not reduces them (like `stats` does) is
`from employees | keep salary | drop salary | eval x = 1 | inline stats count(), max(x) | limit 3`

Another one with `by` as well: `from employees | keep salary | drop salary | eval x = 1, y = 1 | inline stats count(), max(x) by y | limit 3`

5. there is also the story around `drop *` which is not allowed atm.
**Should we allow it now, that we can handle a "drop all" scenario?** Again, something to be put in a separate issue and have a discussion maybe about it.

6. I would also add something that goes to more than one index:

`from employees* | keep salary | drop salary | eval x = 1 | stats count()`

7. [LATER EDIT] Some tests that use `fork` would help:

`from employees* | keep emp_no | drop emp_no | fork (stats c=count()) (stats c=count())`
`from employees* | keep emp_no | drop emp_no | fork (stats c=count()) (stats c=count()) | drop _fork*, c`
`from employees* | keep emp_no | drop emp_no | fork (stats c=count()) (stats c=count()) | drop _fork*, c | stats c=count()`

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java [hunk 10]
```diff
@@ -62,6 +63,7 @@ public class EsqlQueryGenerator {
         ChangePointGenerator.INSTANCE,
         DissectGenerator.INSTANCE,
         DropGenerator.INSTANCE,
+        DropAllGenerator.INSTANCE,
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/generator/EsqlQueryGenerator.java:67]: Love it!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 5 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:476]: We don't want this in general, in some cases we want no blocks but `new Page(N)`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRowAsLocalRelation.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRowAsLocalRelation.java:33]: See above

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java (hunk 9 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:54]: It's because now all the stats can be pruned, so also the case with size == 0 has to be taken into consideration

**Comment by luigidellaquila** [comment]
Thanks for the review @astefan, I just pushed a commit that incorporate your suggestions.

Please let me know if you have further remarks or if you think it's worth discussing it in a wider audience.

When it's done, I'll open two follow-up issues, one to allow `DROP *` and one for possible optimizations.

**Review by astefan — APPROVED** [review]
LGTM. Thanks @luigidellaquila
