### PR TITLE
Prevent synthetic field loaders accessing stored fields from using stale data

### LINKED ISSUE #112156: Synthetic source produces wrong documents in case of a field having both stored value and ignored source
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

x

### Problem Description

Synthetic source produces wrong documents in case of a field having both native and ignored source

### Steps to Reproduce

```
PUT /my_index
{
  "settings": {
    "index": {
      "sort.field": "name", 
      "sort.order": "asc"  
    }
  },
  "mappings": {
    "_source": { "mode": "synthetic" },
    "dynamic": "runtime",
    "properties": {
      "name": {
        "type": "keyword"
      },
      "foo": {
        "type": "keyword",
        "store": true
      }
    }
  }
}

POST my_index/_bulk?refresh
{ "create": {} }
{ "name": "a", "foo": [null, "hello_from_the_other_side"] }
{ "create": {} }
{ "name": "b", "foo": null }

POST my_index/_search
```

Produces:
```
"hits": [
    {
        "_index": "my_index",
        "_id": "Ihrhf5EBLJ3X8EiEoe8f",
        "_score": 1,
        "_source": {
            "foo": [
                null,
                "hello_from_the_other_side"
            ],
            "name": "a"
        }
    },
    {
        "_index": "my_index",
        "_id": "Ixrhf5EBLJ3X8EiEoe8g",
        "_score": 1,
        "_source": {
            "foo": "hello_from_the_other_side",  <<<<<<<<<<<<<<<<<<<<<<
            "name": "b"
        }
    }
]
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lkts**
The main idea of this fix is to introduce `advanceToDoc` method in `SyntheticFieldLoader.StoredFieldLoader` to complement existing method in `DocValuesLoader`. This method is called for every stored field loader before stored field values are loaded (or not loaded) for the current document. As such it allows to discard stale data cached in loader when advancing to new document. The benefit of this approach compared to initial approach in this PR is that there is only one clear place where the "reset" happens and that's `advanceToDoc`.

We could follow up with a change to still provide `docId` parameter in `SyntheticFieldLoader#write`. That allows to assert that `docId` that was advanced matches the `docId` being written. That being said it's a fairly big change.

Closes #112156.

### CODE REVIEW

**Comment by lkts** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/index/mapper/SourceLoader.java [hunk 1]
```diff
@@ -185,6 +185,10 @@ public Source source(LeafStoredFieldLoader storedFieldLoader, int docId) throws
 
             @Override
             public void write(LeafStoredFieldLoader storedFieldLoader, int docId, XContentBuilder b) throws IOException {
+                for (var fieldLevelStoredFieldLoader : storedFieldLoaders.values()) {
+                    fieldLevelStoredFieldLoader.advanceToDoc(docId);
+                }
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/SourceLoader.java:190]: Should this be moved to the loop below, right before calling `load`? I wonder if we end up advancing loaders that are not needed..

File: server/src/main/java/org/elasticsearch/index/mapper/SourceLoader.java [hunk 2]
```diff
@@ -322,6 +326,12 @@ default boolean setIgnoredValues(Map<String, List<IgnoredSourceFieldMapper.NameV
          * Sync for stored field values.
          */
         interface StoredFieldLoader {
+            /**
+             * Signals the loader that values for this document will be loaded next.
+             * Allows loader to discard cached data for previous document.
+             */
+            void advanceToDoc(int docId);
+
             void load(List<Object> values);
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/SourceLoader.java:335]: Since you're touching this, add a short comment for `load` too.

File: server/src/main/java/org/elasticsearch/index/mapper/CompositeSyntheticFieldLoader.java [hunk 3]
```diff
@@ -125,12 +145,30 @@ public interface SyntheticFieldLoaderLayer extends SourceLoader.SyntheticFieldLo
...
+            } else {
+                b.value(value);
+            }
+        }
+    }
+
+    /**
+     * Layer that loads field values from a provided stored field.
+     */
+    public abstract static class StoredFieldLayer implements SyntheticFieldLoaderLayer {
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/CompositeSyntheticFieldLoader.java:166]: Nit: call it just `Layer`, since it's defined within `CompositeSyntheticFieldLoader`?

File: server/src/main/java/org/elasticsearch/index/mapper/CompositeSyntheticFieldLoader.java [hunk 4]
```diff
@@ -63,38 +81,40 @@ public DocValuesLoader docValuesLoader(LeafReader leafReader, int[] docIdsInLeaf
...
         return docId -> {
+            this.docValuesLoadersHaveValues = false;
+
             boolean hasDocs = false;
             for (var loader : loaders) {
                 hasDocs |= loader.advanceToDoc(docId);
             }
 
-            this.hasValue |= hasDocs;
+            this.docValuesLoadersHaveValues |= hasDocs;
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/CompositeSyntheticFieldLoader.java:91]: Nit: use assignment? It was reset above.

File: server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java [hunk 5]
```diff
@@ -1052,27 +1053,21 @@ public SourceLoader.SyntheticFieldLoader syntheticFieldLoader(String simpleName)
...
-
-        if (hasDocValues) {
-            return new SortedSetDocValuesSyntheticFieldLoader(
-                fullPath(),
-                simpleName,
-                fieldType().ignoreAbove == Defaults.IGNORE_ABOVE ? null : originalName(),
-                false
-            ) {
+            });
+        } else if (hasDocValues) {
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java:1069]: Do we need `else` here?

**Review by kkrik-es — COMMENTED** [review]
Nice, this looks much cleaner.. Please wait for Nhat to take a look as well.

File: server/src/main/java/org/elasticsearch/index/mapper/SourceLoader.java (hunk 1 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/SourceLoader.java:190]: The loop below is executed only if there are values for the field, so if we do this there we have the same problem with stale values.

**Review by dnhatn — APPROVED** [review]
I have some feedback, but we can merge it as is to catch the release train and address the feedback later. Thanks @lkts.

**Comment by lkts** [comment]
Sounds good @dnhatn, you can leave comments here.

**Comment by lkts** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/112257)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by dnhatn** [comment]
@lkts I think the issue is that we don't discard the ignoredValues loader when another loader with the same name exists. This causes the undiscarded loaders to be used for the next document. This change should fix the issue. However, since you're on top of the synthetic source issue, please correct me if I missed anything.

```diff
diff --git a/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java b/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
index 29ec0357d7c..297f5921874 100644
--- a/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
+++ b/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
@@ -22,7 +22,9 @@ import org.elasticsearch.index.IndexVersions;
 import org.elasticsearch.index.mapper.MapperService.MergeReason;
 import org.elasticsearch.xcontent.ToXContent;
 import org.elasticsearch.xcontent.XContentBuilder;
+import org.elasticsearch.xcontent.json.JsonXContent;
 
+import java.io.ByteArrayOutputStream;
 import java.io.IOException;
 import java.util.ArrayList;
 import java.util.Arrays;
@@ -915,8 +917,16 @@ public class ObjectMapper extends Mapper {
                 }
                 for (SourceLoader.SyntheticFieldLoader field : fields) {
                     if (field.hasValue()) {
-                        // Skip if the field source is stored separately, to avoid double-printing.
-                        orderedFields.computeIfAbsent(field.fieldName(), k -> new FieldWriter.FieldLoader(field));
+                        // discard if the field source is stored separately, to avoid double-printing.
+                        if (orderedFields.containsKey(field.fieldName())) {
+                            try (var discardingBuilder = new XContentBuilder(JsonXContent.jsonXContent, new ByteArrayOutputStream())) {
+                                discardingBuilder.startObject();
+                                field.write(discardingBuilder); // TODO: maybe have an explicit `discard` method
+                                discardingBuilder.endObject();
+                            }
+                        } else {
+                            orderedFields.put(field.fieldName(), new FieldWriter.FieldLoader(field));
+                        }
                     }
                 }
````

**Comment by kkrik-es** [comment]
> @lkts I think the issue is that we don't discard the ignoredValues loader when another loader with the same name exists. This causes the undiscarded loaders to be used for the next document. This change should fix the issue. However, since you're on top of the synthetic source issue, please correct me if I missed anything.
> 
> ```diff
> diff --git a/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java b/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
> index 29ec0357d7c..297f5921874 100644
> --- a/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
> +++ b/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
> @@ -22,7 +22,9 @@ import org.elasticsearch.index.IndexVersions;
>  import org.elasticsearch.index.mapper.MapperService.MergeReason;
>  import org.elasticsearch.xcontent.ToXContent;
>  import org.elasticsearch.xcontent.XContentBuilder;
> +import org.elasticsearch.xcontent.json.JsonXContent;
>  
> +import java.io.ByteArrayOutputStream;
>  import java.io.IOException;
>  import java.util.ArrayList;
>  import java.util.Arrays;
> @@ -915,8 +917,16 @@ public class ObjectMapper extends Mapper {
>                  }
>                  for (SourceLoader.SyntheticFieldLoader field : fields) {
>                      if (field.hasValue()) {
> -                        // Skip if the field source is stored separately, to avoid double-printing.
> -                        orderedFields.computeIfAbsent(field.fieldName(), k -> new FieldWriter.FieldLoader(field));
> +                        // discard if the field source is stored separately, to avoid double-printing.
> +                        if (orderedFields.containsKey(field.fieldName())) {
> +                            try (var discardingBuilder = new XContentBuilder(JsonXContent.jsonXContent, new ByteArrayOutputStream())) {
> +                                discardingBuilder.startObject();
> +                                field.write(discardingBuilder); // TODO: maybe have an explicit `discard` method
> +                                discardingBuilder.endObject();
> +                            }
> +                        } else {
> +                            orderedFields.put(field.fieldName(), new FieldWriter.FieldLoader(field));
> +                        }
>                      }
>                  }
> ```

Right we discussed this solution in slack. I think this has additional overhead, as fields end up being serialized twice (one is throwaway). Sasha's approach is somewhat similar to doc_values - even though there's no real advancing, iiuc.

**Comment by dnhatn** [comment]
Thanks @kkrik-es. I missed the discussion.

**Comment by lkts** [comment]
@dnhatn Yes, this is a solution to the problem as well. I like current approach because it actually discards data from the loader. I think this is a more robust solution and it is at a right level of abstraction (IMO `ObjectMapper` should not really be concerned with this stuff). As @kkrik-es says it's also nice to have it correspond to doc values API.
