### PR TITLE
Maybe fix DiskThresholdDeciderIT

### LINKED ISSUE #62326: DiskThresholdDeciderIT.testHighWatermarkNotExceeded failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/okz2lziucuxkq/tests/:server:internalClusterTest/org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT/testHighWatermarkNotExceeded

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=60A6AF6A936EF834 -Dtests.security.manager=true -Dtests.locale=ro-RO -Dtests.timezone=America/Pangnirtung -Druntime.java=11
```

**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT&tests.sortField=FAILED&tests.test=testHighWatermarkNotExceeded&tests.unstableOnly=true

**Failure excerpt**:
```
java.lang.AssertionError: |  
  | Expected: a collection with size <1> |  
  | but: collection size was <0>

at __randomizedtesting.SeedInfo.seed([60A6AF6A936EF834:89874ED813A831DA]:0) |  
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded(DiskThresholdDeciderIT.java:160) |  
  |  

```

### PR DESCRIPTION
**Pull request by tlrx**
This is another attempt to fix #62326 as my previous attempts failed (#63112, #63385).

### CODE REVIEW

**Comment by tlrx** [comment]
Green but running it on CI another time: @elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
[Failed](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/10193/) but not related, running it on CI another time: @elasticmachine run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java [hunk 1]
```diff
@@ -99,15 +99,23 @@ public DiskThresholdMonitor(Settings settings, Supplier<ClusterState> clusterSta
...
-        final boolean checkFinished = checkInProgress.compareAndSet(true, false);
+        final boolean checkFinished = checkInProgress(true, false);
         assert checkFinished;
         logger.trace("checkFinished");
     }
 
     public void onNewInfo(ClusterInfo info) {
 
-        if (checkInProgress.compareAndSet(false, true) == false) {
+        if (checkInProgress(false, true) == false) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java:118]: Aren't we potentially introducing all kinds of races here when we run this concurrently and update a bunch of maps in parallel? It seems that the logic in this method doesn't really expect this to happen and it could actually have functional impact with all the various checks we do on those maps in the computations below?

**Review by original-brownbear — COMMENTED** [review]
See my question inline, I'm a little worried about the potential side-effects this will have.

**Comment by original-brownbear** [comment]
@tlrx also you'll have to merge master into this branch, the current test failure is fixed in master already :)

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java (hunk 1 above)
Comment (tlrx) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java:118]: Yes, but that's the only "simple" way I found to ensure that DiskThresholdMonitor effectively runs the reroute after the disk space has been updated... At this point I think we should just re execute refreshDiskUsage in the assertBusy() loop until we have what we want (as initially done in https://github.com/elastic/elasticsearch/pull/62358#discussion_r488598448).

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java:118]: > At this point I think we should just re execute refreshDiskUsage in the assertBusy() loop until we have what we want (as initially done in #62358 (comment)).

Yea I tend to agree :( (begrudgingly :D ... maybe add a TODO to look into a cleaner way and do that?)

Comment (tlrx) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java]: I pushed 7cddec2a83bddac8bb12b26c0543398efc0a89e5

**Comment by tlrx** [comment]
@original-brownbear Following our discussion I implemented the refresh within assertBusy(). I'll give it few runs on CI before merging, then let it run on master for few days before backporting.

**Review by original-brownbear — APPROVED** [review]
LGTM, thanks Tanguy!

**Comment by tlrx** [comment]
Green but running it on CI another time: @elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
Docker issue,  @elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
Thanks Armin! I merged this in master only and will monitor build stats in the next days.
