### PR TITLE
[CI] Fix PartialHitCountCollectorTests testCollectedHitCountEarlyTerminated

### LINKED ISSUE #97359: [CI] PartialHitCountCollectorTests testCollectedHitCountEarlyTerminated failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/dgoewdilmzalk/tests/:server:test/org.elasticsearch.search.query.PartialHitCountCollectorTests/testCollectedHitCountEarlyTerminated

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.query.PartialHitCountCollectorTests.testCollectedHitCountEarlyTerminated" -Dtests.seed=8F487EFE6D51AA33 -Dtests.locale=es-CR -Dtests.timezone=Europe/Moscow -Druntime.java=20
```

**Applicable branches:**
main, 8.9

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.query.PartialHitCountCollectorTests&tests.test=testCollectedHitCountEarlyTerminated

**Failure excerpt:**
```
java.lang.AssertionError: expected:<1> but was:<3>

  at __randomizedtesting.SeedInfo.seed([8F487EFE6D51AA33:FF8FBDB932638B7F]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.junit.Assert.assertEquals(Assert.java:631)
  at org.elasticsearch.search.query.PartialHitCountCollectorTests.testCollectedHitCountEarlyTerminated(PartialHitCountCollectorTests.java:112)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by cbuescher**
For a particular document distribution (each of the three documents matching the boolean query
live in separate leave readers) we calculate the hit count without actually collecting. 
TotalHitCountCollector#getLeafCollector throws a CollectionTerminatedException(), which again shortcuts the PartialHitCountsCollectors collect() method to be called at all.
It should happen very rarely, and in that case we can check if the reason for not triggering the early termination
was that we can get the document count from the term statistics. Thats what this change proposes

Closes #97359

### CODE REVIEW

**Comment by cbuescher** [comment]
@javanna pushed the simplifications by creating a non-early-terminating TermQuery.

**Review by javanna — APPROVED** [review]
LGTM thanks

File: server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java [hunk 1]
```diff
@@ -101,15 +105,33 @@ public void testCollectedHitCount() throws Exception {
     }
 
     public void testCollectedHitCountEarlyTerminated() throws Exception {
-        Query query = new BooleanQuery.Builder().add(new TermQuery(new Term("string", "a1")), BooleanClause.Occur.SHOULD)
-            .add(new TermQuery(new Term("string", "b3")), BooleanClause.Occur.SHOULD)
-            .add(new TermQuery(new Term("string", "b6")), BooleanClause.Occur.SHOULD)
+        Query query = new BooleanQuery.Builder().add(termQuery(new Term("string", "a1")), BooleanClause.Occur.SHOULD)
+            .add(termQuery(new Term("string", "b3")), BooleanClause.Occur.SHOULD)
+            .add(termQuery(new Term("string", "b6")), BooleanClause.Occur.SHOULD)
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java:110]: there is another test that uses this same trick. By the way a boolean query is no longer required with your change, you can simplify that and perhaps adjust which fields get populated in the docs that get indexed.

**Comment by cbuescher** [comment]
@javanna thanks for the review, I added the same treatment for QueryPhaseTests#testTerminateAfterSize0NoHitCountShortcut using the modified TermsQuery from the other test as well. It did have the same problems when running it often enough.

File: server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java [hunk 2]
```diff
@@ -44,7 +44,9 @@ public void setUp() throws Exception {
         for (int i = 0; i < numDocs; i++) {
             Document doc = new Document();
             doc.add(new StringField("string", "a" + i, Field.Store.NO));
-            doc.add(new StringField("string", "b" + i, Field.Store.NO));
+            if (i < 3) {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java:47]: you just drew a heart, well done :)

File: server/src/test/java/org/elasticsearch/search/query/QueryPhaseTests.java [hunk 3]
```diff
@@ -434,8 +435,8 @@ private static long getExpectedTotalHitCountWithShortcut(IndexReader reader, int
      */
     public void testTerminateAfterSize0NoHitCountShortcut() throws Exception {
         indexDocs();
-        BooleanQuery bq = new BooleanQuery.Builder().add(new TermQuery(new Term("foo", "bar")), Occur.SHOULD)
-            .add(new TermQuery(new Term("foo", "baz")), Occur.SHOULD)
+        BooleanQuery bq = new BooleanQuery.Builder().add(new NonCountingTermQuery(new Term("foo", "bar")), Occur.SHOULD)
+            .add(new NonCountingTermQuery(new Term("foo", "baz")), Occur.SHOULD)
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/query/QueryPhaseTests.java:439]: I guess we can simplify this to not have a bool query? Can you do the same for the other one that ends with NoHitCountShortcut please?

File: server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java [hunk 4]
```diff
@@ -101,15 +107,33 @@ public void testCollectedHitCount() throws Exception {
...
         searcher.search(query, partialHitCountCollector);
+
         assertEquals(totalHitsThreshold, partialHitCountCollector.getTotalHits());
         assertTrue(partialHitCountCollector.hasEarlyTerminated());
     }
+
+    /**
+     * A {@link TermQuery} which cannot terminate collection early
+     */
+    public static class NonCountingTermQuery extends TermQuery {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java:123]: let's make it a top-level class if we share it between tests? maybe it can be package private though given it's only used from the query package?

File: server/src/test/java/org/elasticsearch/search/query/QueryPhaseTests.java (hunk 3 above)
Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/search/query/QueryPhaseTests.java:439]: Sure I can, I was under the impression that the bool query is needed here for other reasons.

File: server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java (hunk 4 above)
Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java:123]: I prefer package private tbh, I was already considering copying it in both test classes given that its very specific and if you don't know it exists you will hardly be able to reuse it.

Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java]: by package private I mean top-level , but only visible within the same package. It is now an inner class, and public?

Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java]: It shouldn't be public anymore, I pushed changes yesterday. I can pull it out as well but I think it has limited value.

Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java]: I read public static class still. My comment was because you were sharing it with QueryPhaseTests. If you don't, then it is not necessary to make it top-level. If it's only used in this test, it can be private

Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/search/query/PartialHitCountCollectorTests.java]: > I read public static class still.
Not on the last commit I pushed yesterday [3391b5f](https://github.com/elastic/elasticsearch/pull/97389/commits/3391b5f58cb1402f20b712b32445bc61fd33a245). This code snippet is outdated.
