### PR TITLE
Fix AOOBE when setting min_doc_count to 0 in significant_terms

### LINKED ISSUE #60824: SignificantTermsAggregatorTests#testThreeLayerStringViaGlobalOrds test failure
**Build scan**:

https://gradle-enterprise.elastic.co/s/aw3a7yy5msfwi/console-log?task=:server:test

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.SignificantTermsAggregatorTests.testThreeLayerStringViaGlobalOrds" -Dtests.seed=801AEA6F7F916B4D -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=Pacific/Gambier -Druntime.java=11
```

**Reproduces locally?**:

No

**Applicable branches**:

Only see on `master`.

**Failure history**:

Just this once so far.

**Failure excerpt**:

```
org.elasticsearch.search.aggregations.bucket.terms.SignificantTermsAggregatorTests > testThreeLayerStringViaGlobalOrds FAILED
    java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at __randomizedtesting.SeedInfo.seed([801AEA6F7F916B4D:8871AB284C5E9350]:0)
        at org.elasticsearch.common.util.BigArrays$LongArrayWrapper.get(BigArrays.java:210)
        at org.elasticsearch.common.util.MockBigArrays$LongArrayWrapper.get(MockBigArrays.java:410)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$SignificantTermsResults.bucketUpdater(GlobalOrdinalsStringTermsAggregator.java:802)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:561)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:193)
        at org.elasticsearch.search.aggregations.bucket.BestBucketsDeferringCollector$2.buildAggregations(BestBucketsDeferringCollector.java:227)
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:192)
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:255)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.access$600(GlobalOrdinalsStringTermsAggregator.java:65)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$SignificantTermsResults.buildSubAggs(GlobalOrdinalsStringTermsAggregator.java:831)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$SignificantTermsResults.buildSubAggs(GlobalOrdinalsStringTermsAggregator.java:747)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:586)
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:193)
        at org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:160)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:457)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:402)
        at org.elasticsearch.search.aggregations.bucket.terms.SignificantTermsAggregatorTests.threeLayerStringTestCase(SignificantTermsAggregatorTests.java:508)
        at org.elasticsearch.search.aggregations.bucket.terms.SignificantTermsAggregatorTests.testThreeLayerStringViaGlobalOrds(SignificantTermsAggregatorTests.java:474)
```

### PR DESCRIPTION
**Pull request by jimczi**
This commit fixes the computation of the subset size on empty buckets (doc count of 0).
The aggregator test refactoring in #60683 revealed this bug.

Closes #60824

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java [hunk 1]
```diff
@@ -833,13 +834,15 @@ void buildSubAggs(SignificantStringTerms.Bucket[][] topBucketsPreOrd) throws IOE
 
         @Override
         SignificantStringTerms buildResult(long owningBucketOrd, long otherDocCount, SignificantStringTerms.Bucket[] topBuckets) {
+            // the subset size is missing for empty buckets (doc count of 0)
+            long subsetSize = owningBucketOrd < subsetSizes.size() ? subsetSizes.get(owningBucketOrd) : 0;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java:838]: Maybe `if the owningBucketOrd is not in the array that means the bucket is empty so the size has to be 0`?

**Review by nik9000 — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java]: https://github.com/elastic/elasticsearch/pull/60823/commits/3ddfda379e81e9fb655cd872c0cf577fe87f89f8, thanks

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java]: Thank you!
