### PR TITLE
Validate top-level keys for create index request (#23755)

### LINKED ISSUE #23755: Create index : unable to use custom analyzer in default mapping at index creation time
**Elasticsearch version**: 5.2.2

**Plugins installed**: [analysis-phonetic]

**JVM version**: Oracle java 1.8.0_77 (build 1.8.0_77-b03)

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

When using create index API, I can define custom analyzers in "analysis" section.
I can also define the default mapping in the "mapping" section.
But when I want to use one of my custom analyzers in the mapping section, ElasticSearch fails.

**Steps to reproduce**:
`
DELETE test_custom_analyzer
`
`
PUT test_custom_analyzer
{
  "analysis": {
    "analyzer": {
      "my_analyzer": {
        "tokenizer": "whitespace",
        "filter": [
          "elision",
          "lowercase",
          "asciifolding"
        ]
      }
    }
  },
  "mappings": {
    "_default_": {
      "properties": {
        "field1": {
          "type": "text",
          "analyzer": "my_analyzer"
        }
      }
    }
  }
}
`

**Provide logs (if relevant)**:

elasticsearch response:
`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "analyzer [my_analyzer] not found for field [field1]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_default_]: analyzer [my_analyzer] not found for field [field1]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "analyzer [my_analyzer] not found for field [field1]"
    }
  },
  "status": 400
}`

### PR DESCRIPTION
**Pull request by olcbean**
Create index should accept only `settings`, `mappings` or `aliases` as top-level keys. Any other entry will result in an exception.

The behavior of the create index request till now was that iff none of the supported keys were found (`settings`, `mappings` or `aliases`) then the top level elements were treated as being `settings`.

In other words
```
PUT test 
{ 
  "index.number_of_shards" : 3 
}
```
actually created the index `test` with 3 shards. The implicit parsing of any keys other than the supported ones as `settings` is removed by this PR (please refer to https://github.com/elastic/elasticsearch/pull/23846#discussion_r109138114).

```
PUT test
{
	"FOO_SHOULD_BE_ILLEGAL_HERE": {
		"BAR_IS_THE_SAME": 42
	},
	"mappings": {
		"test": {
			"properties": {
				"field1": {
					"type": "text"
				}
			}
		}
	}
} 
```
```
PUT test
{
	"FOO_SHOULD_BE_ILLEGAL_HERE": {
		"BAR_IS_THE_SAME": 42
	}
} 
```
both throw and exception

(As in 5.x only the first one will throw an exception)

Addresses #23755

### CODE REVIEW

**Comment by olcbean** [comment]
An amend commit for https://github.com/elastic/elasticsearch/pull/23846 resulted in closing the PR. Really sorry about this :cold_sweat: 

This change is only for 6.0. The corresponding PR for 5.x with a detailed description can be found at : https://github.com/elastic/elasticsearch/pull/23862

**Comment by rjernst** [comment]
@olcbean Thank you for opening a PR for this issue! Normally we ask you just open a PR against master, and we will handle any backports necessary.  Can you please close #23862 and update the description/commit message here to be more descriptive?

**Comment by olcbean** [comment]
@rjernst Thank you for the feedback!

As till now, `CreteIndexRequest` implicitly parses anything as `settings` (if there are no `settings`, `mappings` or `aliases` defined). This was discussed at #23846 and a decision was made that this implicit parsing should be deprecated in 5.x and completely removed in master. 

Using the examples above :  
```
PUT test
{
	"FOO_SHOULD_BE_ILLEGAL_HERE": {
		"BAR_IS_THE_SAME": 42
	},
	"mappings": {
		"test": {
			"properties": {
				"field1": {
					"type": "text"
				}
			}
		}
	}
} 
```
will throw in master 
will throw in 5.x
successful in any other branch
```
PUT test
{
	"FOO_SHOULD_BE_ILLEGAL_HERE": {
		"BAR_IS_THE_SAME": 42
	}
} 
```
will throw in master 
will be successful in 5.x (with deprecation logging)
successful in any other branch

I do understand that the default policy is to create a PR against the master but having this situation is not really the most common one, is it? :wink:

Maybe it would have made more sense from procedural point to have #23862 (deprecate the behavior) against master, wait till it is merged to master and to 5.x and only then open this one #23869 (deprecated behavior removed) to be merged only to master. 
But this sounds rather complicated and requires quite some logistics.
Hence I decided to open 2 separate  PR against the two branches which can be reviewed and merged independent of each other. I also marked them as they should be merged only in the branch against which they were opened.

How should I proceed? Maybe you can point me to an example where something like this was done?

**Comment by rjernst** [comment]
Typically this would be done in 2 Prs, the first to deprecate (going into master and being backported), and the second doing the removal (in master only).

**Comment by olcbean** [comment]
I will keep it in mind for the future. I tried to change the base of the #23862 expecting that it will result is simple cherry-pick. It didn't :confused: 

@rjernst so at this point I either need to open a new PR against master or do you think that for #23862 it would be ok to be merged to 5.x and master

**Comment by rjernst** [comment]
@olcbean What error did you get when cherry picking? The change looks very simple, I would expect it to cherry pick easily.

**Comment by olcbean** [comment]
@rjernst What I meant is that I did not want to closeopen a new PR for #23862 so I decided to see what will happen if I simply change the base branch from the UI (`Edit` next to the PR title) hoping that it will simply cherry pick my changes. Well, it did not... So right now I can either close the #23862 and open yet another one against the master, or if the PR is approved, the reviewer can merge the changes to 5.x and master. Or maybe you know of another option?

**Comment by rjernst** [comment]
@olcbean Sorry for the delayed reply. Simply changing the branch from github won't work. But doing a cherry pick with a new branch can be done very easily.

```
git checkout master
git pull
git checkout -b my_new_branch
git cherry-pick 2098c6beea243cc980710e00d43d8c65b2b7aa3c
```

**Comment by olcbean** [comment]
@rjernst can you have a look at this PR and the corresponding #23862?

File: core/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequest.java [hunk 1]
```diff
@@ -382,38 +382,34 @@ public CreateIndexRequest source(BytesReference source, XContentType xContentTyp
...
-                    found = true;
                     try {
                         customs.put(name, proto.fromMap((Map<String, Object>) entry.getValue()));
                     } catch (IOException e) {
                         throw new ElasticsearchParseException("failed to parse custom metadata for [{}]", name);
                     }
+                } else {
+                    // found a key which is neither custom defined nor one of the supported ones
+                    throw new ElasticsearchParseException(
+                            "unknown key [{}] for a [{}], expected [settings], [mappings] or [aliases]",
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequest.java]: I think this message is a little deceptive, since this custom elements are allowed. I think just keep it simple, something like "unsupported key X for create index"?

File: core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequestTests.java [hunk 2]
```diff
@@ -69,4 +72,29 @@ public void testSerializationBwc() throws IOException {
             }
         }
     }
+    
+    public void testTopLevelKeys() throws IOException {
+        String createIndex =
+                "{\n"
+                + "  \"FOO_SHOULD_BE_ILLEGAL_HERE\": {\n"
```
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequestTests.java]: Typically we would use JsonXContent.contentBuilder() (as can be seen in testSerialization above). Can you please switch to that?

**Review by rjernst — CHANGES_REQUESTED** [review]
@olcbean I am again very sorry for the long delay in reply here. This slipped through my radar over the summer. Unfortunately it is too late to get a deprecation into 5.x. However, we view this as a bug, and would still like to get it into 6.0. I've left a couple comments on this PR, and there is a merge conflict which needs to be addressed. If you are still willing to work on this, please ping me once you have updated and I will review again.

**Comment by olcbean** [comment]
@rjernst thank you for picking up this PR
I was rather busy these days but I should be able to get to this in the coming week. If it is urgent (I do not know what the schedule for 6.0 is), please feel free to take my changes and repurpose them as you see fit.
If not - I should have something before the end of the month.

**Comment by s1monw** [comment]
I really consider this as a bug. Lets make sure we get this in asap. Once it's in master we can make a much better decision on where is should go. @rjernst can you take it from here?

**Review by rjernst — APPROVED** [review]
@olcbean I tweaked the error message. I will commit after another test run. Thanks!

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by olcbean** [comment]
@rjernst sure thing! I based the msg to the [MultiGetRequest](https://github.com/elastic/elasticsearch/blob/742d929b5671035a610855718e9b04199217614f/core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java#L342) validation msg. For consistency shall the mget msg be also simplified?

**Comment by rjernst** [comment]
> For consistency shall the mget msg be also simplified?

Sure, that would be good. But that can be done in a separate followup PR. Would you like to take care of that? I think the json element type we found is not useful. All that matters is we found an unknown key in an object.

**Comment by s1monw** [comment]
I spoke to @rjernst and we missed backporting this to `6.0` we will stick with `7.0` with this change

**Comment by olcbean** [comment]
@s1monw @rjernst 
> backporting this to 6.0

Do you mean to deprecate this in `6.0`? If this is the case and you still need it for `6.0` I can have something by the end of the week. Please let me know. Thanks!

**Comment by jasontedor** [comment]
It’s a bug, I don’t think we need deprecation logging.

**Comment by olcbean** [comment]
@jasontedor point! 
However I was asking what backporting to `6.0` means for this special case. 
In https://github.com/elastic/elasticsearch/pull/23846#discussion_r109138114 it has been decided to clean up the create index api, hence my reference to 'deprecation' (for more details refer to https://github.com/elastic/elasticsearch/pull/23846#discussion_r109134775)
Or maybe simply apply this fix to `6.0`? But then I am not sure why @s1monw @rjernst decided against it in `6.0` (?)

Is there still interest in this? And if so which path to take in order to save in review time. 
Any thoughts? Thanks!

**Comment by clintongormley** [comment]
Hi @olcbean 

Unfortunately, this change was merged too late (our fault, not yours).  At this stage (after 6.0.0-rc1 is already out) we'd only consider adding breaking changes that are absolutely required. While this is a good change, we've lived with it for a long time already and can continue to do so until 7.0.

**Comment by olcbean** [comment]
@clintongormley oh, I didn't realize that `6.0.0-rc1` is out. Thanks for straightening this one out :)
