### PR TITLE
Handle shards assigned to nodes that are not in the cluster state

### LINKED ISSUE #14584: NPE onNodeFailure
Hi,

we may have tried something stupid here:

```
$ curl 192.168.8.180:9200/_cat/nodes?h=name,version,jdk,ip,master,node.role
robocop      2.0.0 1.7.0_79 192.168.8.237 - d
Det Røde Lyn 2.0.0 1.8.0_65 192.168.8.180 * -
stuart       2.0.0 1.8.0_65 192.168.8.13  - d
Gulle        2.0.0 1.7.0_85 192.168.8.21  m d 
```
"Det Røde Lyn" is a windows machine.

all nodes have "Gulle" configured as unicast host
```
discovery.zen.ping.unicast.hosts: ["192.168.8.21"]
```
when Gulle shutdown the cluster broke down and the following shows up in the log of the stuart node. The logfile of the other nodes in the cluster dont show a similar NPE.

We have been unable to reproduce this, but thought you might be interested in this anyway.
```
[2015-11-06 13:28:07,710][INFO ][cluster.routing.allocation.decider] [stuart] updating [cluster.routing.allocation.enable] from [ALL] to [NONE]
[2015-11-06 13:28:47,859][INFO ][discovery.zen            ] [stuart] master_left [{Gulle}{F4pDMpoOSG6U0fBuxUzFWg}{192.168.8.21}{192.168.8.21:9300}], reason [transport disconnected]
[2015-11-06 13:28:47,859][WARN ][discovery.zen            ] [stuart] master left (reason = transport disconnected), current nodes: {{robocop}{LHRwN1SYTMC05oPnrnlhVg}{192.168.8.237}{192.168.8.237:9300}{rack=robo-desk, max_local_storage_nodes=1, master=false},{Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false},{stuart}{TYWtWR00Q6Kv8pG6Fi09Yw}{192.168.8.13}{192.168.8.13:9300}{master=false},}
[2015-11-06 13:28:47,859][INFO ][cluster.service          ] [stuart] removed {{Gulle}{F4pDMpoOSG6U0fBuxUzFWg}{192.168.8.21}{192.168.8.21:9300},}, reason: zen-disco-master_failed ({Gulle}{F4pDMpoOSG6U0fBuxUzFWg}{192.168.8.21}{192.168.8.21:9300})
[2015-11-06 13:28:50,397][DEBUG][action.admin.cluster.state] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:50,398][DEBUG][action.admin.cluster.state] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:50,398][INFO ][rest.suppressed          ] /_stats/docs,store Params: {metric=docs,store}
java.lang.NullPointerException
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.onNodeFailure(TransportBroadcastByNodeAction.java:332)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.sendNodeRequest(TransportBroadcastByNodeAction.java:314)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.start(TransportBroadcastByNodeAction.java:284)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:217)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:77)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1177)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.stats(AbstractClient.java:1482)
        at org.elasticsearch.rest.action.admin.indices.stats.RestIndicesStatsAction.handleRequest(RestIndicesStatsAction.java:102)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-06 13:28:50,398][DEBUG][action.admin.indices.get ] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:50,399][DEBUG][action.admin.cluster.health] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:51,291][INFO ][cluster.service          ] [stuart] detected_master {Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false}, reason: zen-disco-receive(from master [{Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false}])
[2015-11-06 13:29:13,992][INFO ][cluster.service          ] [stuart] added {{Gulle}{vDbnkAfsT96NnX_Q3cN1oA}{192.168.8.21}{192.168.8.21:9300},}, reason: zen-disco-receive(from master [{Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false}])
[2015-11-06 13:29:55,312][INFO ][cluster.routing.allocation.decider] [stuart] updating [cluster.routing.allocation.enable] from [NONE] to [ALL]

### PR DESCRIPTION
**Pull request by jasontedor**
This commit addresses an issue in TransportBroadcastByNodeAction.
Namely, if in between a master leaving the cluster and a new one being
assigned, a request that relies on TransportBroadcastByNodeAction
(e.g., an indices stats request) is issued,
TransportBroadcastByNodeAction might attempt to send a request to a
node that is no longer in the local node’s cluster state.

The exact circumstances that lead to this are as follows. When the
master leaves the cluster and another node’s master fault detection
detects this, the local node will update its local cluster state to no
longer include the master node. However, the routing table will not be
updated. This means that in the preparation for sending the requests in
TransportBroadcastByNodeAction, we need to check that not only is a
shard assigned, but also that it is assigned to a node that is still in
the local node’s cluster state.

This commit adds such a check to the constructor of
TransportBroadcastByNodeAction. A new unit test is added that checks
that no request is sent to the master node in such a situation; this
test fails with a NullPointerException without the fix. Additionally,
the unit test TransportBroadcastByNodeActionTests#testResultAggregation
is updated to also simulate a master failure. This updated test also
fails prior to the fix.

Closes #14584

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java [hunk 1]
```diff
@@ -228,7 +228,7 @@ protected AsyncAction(Request request, ActionListener<Response> listener) {
             nodeIds = new HashMap<>();
 
             for (ShardRouting shard : shardIt.asUnordered()) {
-                if (shard.assignedToNode()) {
+                if (shard.assignedToNode() && nodes.get(shard.currentNodeId()) != null) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java]: maybe add a comment here too?

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java]: Added in 395fe444af79f6327cce534578dfb1ac3593d387.

File: core/src/test/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeActionTests.java [hunk 2]
```diff
@@ -340,6 +378,18 @@ public void testResultAggregation() throws ExecutionException, InterruptedExcept
         Request request = new Request(new String[]{TEST_INDEX});
         PlainActionFuture<Response> listener = new PlainActionFuture<>();
 
+        // simulate removing the master
+        boolean simulateFailedMasterNode = rarely();
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeActionTests.java]: final?

**Comment by bleskes** [comment]
LGTM

File: core/src/test/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeActionTests.java (hunk 2 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeActionTests.java]: Done in 70ac92bccbf312a660fc739e7650aa201a6e4195.

**Comment by jasontedor** [comment]
Integrated into [master](https://github.com/elastic/elasticsearch/commit/7d7926e10b28eb42096895819acfbb7c1e32a5f8), [2.0](https://github.com/elastic/elasticsearch/commit/aced785decd3199a69af219d221c39940eb34eb1), [2.1](https://github.com/elastic/elasticsearch/commit/eb530b42e573f393be54642414a5dce31c050c64), and [2.x](https://github.com/elastic/elasticsearch/commit/54aa013250b872fe5cafdc0c1351cb98ca9c3be7)
