### PR TITLE
Fix doc_count on HistoBackedHistogramAggregator

### LINKED ISSUE #74617: Discrepancy between `doc_count` agg and `histogram` agg on histogram fields
It looks like there is a bug when performing a histogram aggregation on a histogram field, if the document contains `_doc_count` field. 

**Expected**
`doc_count` agg and `histogram` agg should return identical doc counts. 

**Actual:**
The doc count is (almost) doubled for `histogram` agg compared to the `doc_count` agg

**Affected version**
```json
{
    "number" : "8.0.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "307b82c474fe27722863fa2dc6b05def2f608ad9",
    "build_date" : "2021-06-27T01:39:13.126072914Z",
    "build_snapshot" : true,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "7.14.0",
    "minimum_index_compatibility_version" : "7.0.0"
}
```

# Reproduce problem

```
PUT histogram-double-bug
{
  "mappings" : {
    "properties" : {
      "my_histogram" : {
        "type" : "histogram"
      }
    }
  }
}

POST histogram-double-bug/_doc
{
  "_doc_count": 10,
  "my_histogram": {
    "counts": [
      10
    ],
    "values": [
      20
    ]
  }
}

GET histogram-double-bug/_search?track_total_hits=true
{
  "size": 0,
  "aggs": {
    "doc_count": {
      "value_count": {
        "field": "my_histogram"
      }
    },
    "distribution": {
      "histogram": {
        "field": "my_histogram",
        "interval": 1000
      }
    }
  }
}
```

## Response

```json
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "doc_count" : {
      "value" : 10
    },
    "distribution" : {
      "buckets" : [
        {
          "key" : 0.0,
          "doc_count" : 19
        }
      ]
    }
  }
}
```

In the above, the correct doc count is 10 but the histogram doc count is 19.

### PR DESCRIPTION
**Pull request by csoulios**
`histogram` aggregation on `histogram` field computes wrong `doc_count` values when `_doc_count` field is present.

The root cause of the problem is correctly described [here](https://github.com/elastic/elasticsearch/issues/74617#issuecomment-869642717)

Closes https://github.com/elastic/elasticsearch/issues/74617

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/aggregations/bucket/histogram/HistoBackedHistogramAggregator.java [hunk 1]
```diff
@@ -86,9 +86,10 @@ public void collect(int doc, long owningBucketOrd) throws IOException {
                             } else {
                                 collectBucket(sub, doc, bucketOrd);
                             }
-                            // We have added the document already. We should increment doc_count by count - 1
-                            // so that we have added it count times.
-                            incrementBucketDocCount(bucketOrd, count - 1);
+                            // We have added the document already and we have incremented bucket doc_count
+                            // by _doc_count times. To compensate for this, we should increment doc_count by
+                            // (count - _doc_count) so that we have added it count times.
+                            incrementBucketDocCount(bucketOrd, count - docCountProvider.getDocCount(doc));
```
Comment (benwtrent) [inline x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/aggregations/bucket/histogram/HistoBackedHistogramAggregator.java:92]: No matter what `_doc_count` is, it was previously added to the `bucket_count` via the `collectBucket` methods. It could be ANY number. 

Consequently, this `incrementBucketDocCount` may actually be decrementing the `bucket_count` to adjust for the difference. 

I think this is fine. 

The other potential solution is to override `collectBucket...` so the bucket count is not incremented. But that may prove too complicated.

I think this is good solution for now 👍 

Somebody else from the aggs team should take a look as well.

**Review by benwtrent — APPROVED** [review]
