### PR TITLE
Use Terminal.readSecret in add string keystore command

### LINKED ISSUE #126882: [CI] AddStringKeyStoreCommandTests testStdinWithMultipleValues failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7738 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/pqviqeglgduzk)
- [elasticsearch-periodic-platform-support #7732 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/gqgrqej6hg3ne)

**Reproduction Line:**
```
gradlew ":distribution:tools:keystore-cli:test" --tests "org.elasticsearch.cli.keystore.AddStringKeyStoreCommandTests.testStdinWithMultipleValues" -Dtests.seed=41CD297F413C6DB2 -Dtests.locale=ar-EH -Dtests.timezone=America/Rainy_River -Druntime.java=24
```

**Applicable branches:**
9.0

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cli.keystore.AddStringKeyStoreCommandTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testStdinWithMultipleValues),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.junit.ComparisonFailure: expected:<[bar2]> but was:<[]>
```

**Issue Reasons:**
- [9.0] 2 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [9.0] 2 failures in test testStdinWithMultipleValues (2.4% fail rate in 84 executions)
- [9.0] 2 failures in step windows-2022_checkpart1_platform-support-windows (50.0% fail rate in 4 executions)
- [9.0] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by rjernst**
As a followon to #126729, the add string keystore command doesn't need to use a reader at all (and it was incorrect for it to close the reader from the terminal). Instead, the Terminal abstraction already handles how to get at line by line secrets. This commit removes that usage of reader and uses readSecret calls instead.

closes #126882

### CODE REVIEW

File: distribution/tools/keystore-cli/src/main/java/org/elasticsearch/cli/keystore/AddStringKeyStoreCommand.java [hunk 1]
```diff
@@ -53,42 +50,26 @@ protected void executeCommand(Terminal terminal, OptionSet options, Environment
...
-            closeable = stdinReader;
-        } else {
-            valueSupplier = s -> terminal.readSecret("Enter value for " + s + ": ");
-            closeable = () -> {};
-        }
+        final CheckedFunction<String, char[], IOException> valueSupplier = s -> {
+            String prompt = "";
+            if (options.has(stdinOption) == false) {
+                prompt = "Enter value for " + s + ": ";
+            }
```
Comment (prdoyle) [inline distribution/tools/keystore-cli/src/main/java/org/elasticsearch/cli/keystore/AddStringKeyStoreCommand.java:57]: This style of supplying a default that is sometimes overridden later defeats Java's error detection for paths where the value is not set.

```suggestion
            String prompt;
            if (options.has(stdinOption)) {
                prompt = "";
            } else {
                prompt = "Enter value for " + s + ": ";
            }
```

**Review by prdoyle — APPROVED** [review]
One optional suggestion.

File: distribution/tools/keystore-cli/src/main/java/org/elasticsearch/cli/keystore/AddStringKeyStoreCommand.java (hunk 1 above)
Comment (rjernst) [reply distribution/tools/keystore-cli/src/main/java/org/elasticsearch/cli/keystore/AddStringKeyStoreCommand.java]: I applied your suggestion.
