### PR TITLE
Fix testJoinWaitsForClusterApplier

### LINKED ISSUE #86974: [CI] DiscoveryDisruptionIT testJoinWaitsForClusterApplier failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/22kfr6xkperam/tests/:server:internalClusterTest/org.elasticsearch.discovery.DiscoveryDisruptionIT/testJoinWaitsForClusterApplier

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.DiscoveryDisruptionIT.testJoinWaitsForClusterApplier" -Dtests.seed=9FB11F584CBC91 -Dtests.locale=zh-Hans-CN -Dtests.timezone=Egypt -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.discovery.DiscoveryDisruptionIT&tests.test=testJoinWaitsForClusterApplier

**Failure excerpt:**
```
java.lang.AssertionError: failed to reach a stable cluster of [2] nodes. Tried via [node_t0]. last cluster state:
cluster uuid: tT33RxZHSC2bUIXNFsiwVw [committed: true]
version: 5
state uuid: yXI7NhQ1Q7m1V6pLSq9HfQ
from_diff: false
meta data version: 2
   coordination_metadata:
      term: 1
      last_committed_config: VotingConfiguration{zM3EXpSlSe6xt_cJp3-XXg,hdOfDcy3TDiHiIGfXgTUeg,fftPYa_xTjuct52l9LbDQQ}
      last_accepted_config: VotingConfiguration{zM3EXpSlSe6xt_cJp3-XXg,hdOfDcy3TDiHiIGfXgTUeg,fftPYa_xTjuct52l9LbDQQ}
      voting tombstones: []
metadata customs:
   index-graveyard: IndexGraveyard[[]]
nodes: 
   {node_t1}{zM3EXpSlSe6xt_cJp3-XXg}{dKRW-RxLRdyXDGhbYqfhYQ}{node_t1}{127.0.0.1}{127.0.0.1:42085}{cdfhilmrstw}
   {node_t0}{hdOfDcy3TDiHiIGfXgTUeg}{XPfPxzX8RhuEdkIGJdwK1g}{node_t0}{127.0.0.1}{127.0.0.1:40001}{cdfhilmrstw}, local, master
   {node_t2}{fftPYa_xTjuct52l9LbDQQ}{OCDxp77GR_e7Ry-YCeJwmw}{node_t2}{127.0.0.1}{127.0.0.1:44087}{cdfhilmrstw}
routing_table (version 1):
routing_nodes:
-----node_id[zM3EXpSlSe6xt_cJp3-XXg][V]
-----node_id[fftPYa_xTjuct52l9LbDQQ][V]
-----node_id[hdOfDcy3TDiHiIGfXgTUeg][V]
---- unassigned

  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.test.ESIntegTestCase.ensureStableCluster(ESIntegTestCase.java:1293)
  at org.elasticsearch.test.ESIntegTestCase.ensureStableCluster(ESIntegTestCase.java:1274)
  at org.elasticsearch.discovery.DiscoveryDisruptionIT.testJoinWaitsForClusterApplier(DiscoveryDisruptionIT.java:244)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Block the cluster applier before disrupting the cluster so the victim
node doesn't try and rejoin too soon.

Closes #86974

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java [hunk 1]
```diff
@@ -235,6 +229,12 @@ public void testJoinWaitsForClusterApplier() throws Exception {
         }, ActionListener.wrap(() -> {}));
         barrier.await(10, TimeUnit.SECONDS);
 
+        // drop the victim from the cluster with a network disruption
```
Comment (kingherc) [inline server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java:232]: Hi @DaveCTurner , LGTM. I understand the issue that the victim might have sent the join request before making its network fail. However, I am still not sure why that was the reason that the second `barrier.await(10, TimeUnit.SECONDS);` was the one timing out in the original issue's build scan ( https://gradle-enterprise.elastic.co/s/22kfr6xkperam/tests/:server:internalClusterTest/org.elasticsearch.discovery.DiscoveryDisruptionIT/testJoinWaitsForClusterApplier ) ? Even if the join request was sent earlier, shouldn't the barriers be passing either way? I would have expected a failure at `ensureStableCluster(2, masterName);` since the cluster would have 3 nodes instead of 2.

File: server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java [hunk 2]
```diff
@@ -215,13 +215,7 @@ public void testJoinWaitsForClusterApplier() throws Exception {
         final var victimName = randomValueOtherThan(masterName, () -> randomFrom(internalCluster().getNodeNames()));
         logger.info("--> master [{}], victim [{}]", masterName, victimName);
 
-        // drop the victim from the cluster with a network disruption
-        final var masterTransportService = (MockTransportService) internalCluster().getInstance(TransportService.class, masterName);
-        masterTransportService.addFailToSendNoConnectRule(internalCluster().getInstance(TransportService.class, victimName));
```
Comment (pxsalehi) [inline server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java:220]: One question to understand this mock. Wouldn't this `addFailToSendNoConnectRule` prevent/drop reconnect attempts of the victim (to master)? How can the victim rejoin after this failure has been added to the transport service of master (and before it is cleared)?

File: server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java:232]: `ensureStableCluster(2, masterName)` waits for up to 30s for the cluster to have 2 nodes (by calling the cluster health API with a 30s timeout) and the barrier wait was timing out in this time. But then even if it didn't time out, `ensureStableCluster` throws an `AssertionError` eventually so we'd never get to the second `barrier.await` on the main test thread.

I think you should be able to reproduce this with the changes in [this comment](https://github.com/elastic/elasticsearch/issues/86974#issuecomment-1160314795).

**Review by pxsalehi — APPROVED** [review]
Just asked a question, otherwise LGTM!

File: server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java:220]: No, this only prevents the master from sending/connecting to the victim, the connections in the opposite direction are unaffected.

Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java:220]: ... but also the victim was rejoining after this rule was cleared.

File: server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java (hunk 1 above)
Comment (kingherc) [reply server/src/internalClusterTest/java/org/elasticsearch/discovery/DiscoveryDisruptionIT.java:232]: Ah I see thank you!

**Review by kingherc — APPROVED** [review]

**Comment by DaveCTurner** [comment]
@elasticmachine update branch
