### PR TITLE
Scripts: Fix security for deprecation warning

### LINKED ISSUE #28408: ScriptDocValues getDate() on long field triggers AccessControlException
In #22948 we added a deprecation warning when using `.date` on a long field. However, since scripts run in a reduced permission environment, the underlying call to log the message results in a security manager exception. We need to do this in a doPrivileged block.

See https://discuss.elastic.co/t/painless-script-appender-deprecation-rolling-java-security-accesscontaccess-denied/117313

### PR DESCRIPTION
**Pull request by nik9000**
If you call `getDates()` on a long or date type field add a deprecation
warning to the response and log something to the deprecation logger.
This *mostly* worked just fine but if the deprecation logger happens to
roll then the roll will be performed with the script's permissions
rather than the permissions of the server. And scripts don't have
permissions to, say, open files. So the rolling failed. This fixes that
by wrapping the call the deprecation logger in `doPriviledged`.

This is a strange `doPrivileged` call because it doens't check
Elasticsearch's `SpecialPermission`. `SpecialPermission` is a permission
that no-script code has and that scripts never have. Usually all
`doPrivileged` calls check `SpecialPermission` to make sure that they
are not accidentally acting on behalf of a script. But in this case we
are *intentionally* acting on behalf of a script.

Closes #28408

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java [hunk 1]
```diff
@@ -177,15 +206,27 @@ public int size() {
         private static final ReadableDateTime EPOCH = new DateTime(0, DateTimeZone.UTC);
 
         private final SortedNumericDocValues in;
+        private final Consumer<String> deprecationCallback;
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java]: Why do we need this abstracted? Can't the Longs.deprecated method just call deprecationLogger.deprecated directly?

**Review by rjernst — APPROVED** [review]
Looks good, just one minor question.

File: server/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java]: It could but then I couldn't test this. There isn't any consistent way to make it fail without this funny unit test dance that I do because it usually only fails when you rotate the log files. At least, that is the only time I could get it to fail locally.

**Comment by nik9000** [comment]
Thanks for reviewing @rjernst!
