### PR TITLE
Fix + unmute SampleTests

### LINKED ISSUE #127950: [CI] SampleTests testGroupingAggregate {TestCase=<long unicode KEYWORDs>} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8112 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/wlhxhthix3rvy)
- [elasticsearch-intake #22806 / part3](https://gradle-enterprise.elastic.co/s/xlmil34uvvea2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.aggregate.SampleTests.testGroupingAggregate {TestCase=<long unicode KEYWORDs>}" -Dtests.seed=3F34A526F5EC19F3 -Dtests.locale=ksh -Dtests.timezone=America/Winnipeg -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.aggregate.SampleTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGroupingAggregate%20%7BTestCase%3D%3Clong%20unicode%20KEYWORDs%3E%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.common.breaker.CircuitBreakingException: over test limit
```

**Issue Reasons:**
- [main] 2 failures in test testGroupingAggregate {TestCase=<long unicode KEYWORDs>} (1.3% fail rate in 155 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #127951: [CI] SampleTests testGroupingAggregate {TestCase=<long unicode TEXTs>} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8112 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/wlhxhthix3rvy)
- [elasticsearch-intake #22806 / part3](https://gradle-enterprise.elastic.co/s/xlmil34uvvea2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.expression.function.aggregate.SampleTests.testGroupingAggregate {TestCase=<long unicode KEYWORDs>}" -Dtests.seed=3F34A526F5EC19F3 -Dtests.locale=ksh -Dtests.timezone=America/Winnipeg -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.expression.function.aggregate.SampleTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGroupingAggregate%20%7BTestCase%3D%3Clong%20unicode%20TEXTs%3E%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.common.breaker.CircuitBreakingException: over test limit
```

**Issue Reasons:**
- [main] 2 failures in test testGroupingAggregate {TestCase=<long unicode TEXTs>} (1.3% fail rate in 155 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jan-elastic**
fixes https://github.com/elastic/elasticsearch/issues/127950
fixes https://github.com/elastic/elasticsearch/issues/127951

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/SampleTests.java [hunk 1]
```diff
@@ -50,12 +50,12 @@ public static Iterable<Object[]> parameters() {
                 MultiRowTestCaseSupplier.booleanCases(1, 1000),
                 MultiRowTestCaseSupplier.ipCases(1, 1000),
                 MultiRowTestCaseSupplier.versionCases(1, 1000),
-                MultiRowTestCaseSupplier.stringCases(1, 1000, DataType.KEYWORD),
-                MultiRowTestCaseSupplier.stringCases(1, 1000, DataType.TEXT),
+                MultiRowTestCaseSupplier.stringCases(1, 20, DataType.KEYWORD),
+                MultiRowTestCaseSupplier.stringCases(1, 20, DataType.TEXT),
```
Comment (jan-elastic) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/SampleTests.java:54]: These are the same values as in [ValuesTests](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/aggregate/ValuesTests.java#L54-L60) now, so that should be safe.

**Review by ivancea — APPROVED** [review]
