### PR TITLE
Report close connection exceptions at INFO

### LINKED ISSUE #66473: Increase log levels of definitely-broken network disconnects
In #51612 we promoted log messages regarding unexpected network disconnects from `TRACE` to `DEBUG`. Some users have indicated that they'd like even more visibility on these by default, at least for the ones that are definite indications of something going wrong at the network level, which IMO is at least `Connection reset` and `Connection timed out` on Linux. Normally we shouldn't be seeing either of these so I'm opening this issue to propose moving them all the way up to `WARN`.

I'm not decided on whether to push for this change in 7.x or to wait for 8.0. The trouble with doing it in 7.x is that transport clients are still in use in these versions and clients may have less reliable connectivity to Elasticsearch than we expect for node-to-node connections, so some of the logs we emit might not be actionable for the server administrator.

We might need a sync discussion on this topic eventually but for now I'd prefer to gather async thoughts here first.

### PR DESCRIPTION
**Pull request by DaveCTurner**
In #51612 we promoted certain log messages regarding unexpected network
exceptions from `TRACE` to `DEBUG`. In fact it's often useful to see
these exceptions by default, so with this commit we show the message
(but not the stack trace) at `INFO` level. This commit also adds some
commentary about what each of the exceptions means.

Closes #66473

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/transport/OutboundHandler.java [hunk 1]
```diff
@@ -194,10 +195,17 @@ public void onResponse(Void v) {
 
                 @Override
                 public void onFailure(Exception e) {
-                    if (NetworkExceptionHelper.isCloseConnectionException(e)) {
-                        logger.debug(() -> new ParameterizedMessage("send message failed [channel: {}]", channel), e);
+                    final Level closeConnectionExceptionLevel = NetworkExceptionHelper.getCloseConnectionExceptionLevel(e);
+                    if (closeConnectionExceptionLevel == Level.OFF) {
+                        logger.warn(new ParameterizedMessage("send message failed [channel: {}]", channel), e);
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/transport/OutboundHandler.java:200]: Should the condition above be `closeConnectionExceptionLevel == Level.WARN`?

**Review by idegtiarenko — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/transport/OutboundHandler.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/transport/OutboundHandler.java:200]: No, the `WARN` case is handled in the final `else` branch. This branch is handling the case that the exception doesn't appear to be network-related, and preserves the earlier behaviour that such exceptions are logged as warnings.

**Comment by DaveCTurner** [comment]
Thanks Ievgen!

File: server/src/main/java/org/elasticsearch/transport/OutboundHandler.java (hunk 1 above)
Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/transport/OutboundHandler.java:200]: Oh, I was confused with `Level.OFF` actually representing a `non network related`.
I wonder if that could be changed to `Level.WARN` then, the first branch could be merged with the last one, unless I miss something.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/transport/OutboundHandler.java:200]: Kind of, but I think that risks future bugs. The intention is to distinguish "this exception is network-related and deserves a warning" from "this exception is not network-related". An earlier iteration actually returned `WARN` sometimes but then I moved them all to `INFO` because I found that all the Linux ones might be benign and I didn't want to emit warnings for benign problems. I didn't investigate the Windows behaviour and we might decide to move them back up to `WARN` in future.

I could have used an `Optional<Level>` or a `null` or similar but `Level#OFF` seemed like a simpler way to say the same thing.
