### PR TITLE
[ES|QL] Resolve groupings in aggregate before resolving references to groupings in the aggregations

### LINKED ISSUE #116781: [ES|QL] ResolveRefs may not resolve a resolvable aggregation with groupings completely and cause IllegalStateException
This was discussed during reviewing #115814 , it is kind of an edge case, however it does expose some issues with resolving an aggregation with groupings. References are created for groupings in the aggregates, and if the items in groupings cannot be resolved the first time `resolveAggregate` is called, its reference is marked with customMessage = true, and it prevents further attempts to resolve this reference. We might need a way to allow further attempts to resolve the references created in aggregates.

```
from sample_data
| EVAL date = "2024-01-01"::datetime
| stats max = MAX(@timestamp) BY c = (date == "2024-01-01")

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Found 1 problem\nline 1:57: Plan [Aggregate[STANDARD,[c{r}#5],[MAX(@timestamp{f}#11,true[BOOLEAN]) AS max, ?c]]] optimized incorrectly due to missing references [?c]"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "Found 1 problem\nline 1:57: Plan [Aggregate[STANDARD,[c{r}#5],[MAX(@timestamp{f}#11,true[BOOLEAN]) AS max, ?c]]] optimized incorrectly due to missing references [?c]"
  },
  "status" : 500
}
```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolve: #116781 

There are references to `groupings` in the `aggregations` in an `Aggregate`, trying to resolve the references to the groupings before the groupings are resolved lead to unexpected complexity to resolve an `Aggregate`, and it is error prone. 

This PR changes `resolveAggregate` in `Analyzer` to resolve the references after the groupings are resolved successfully, and it also moves the `ImplicitCasting` after `ResolveRefs`, as the reason for having `ImplicitCasting` before `ResolveRefs`  does not exist anymore with the change in `resolveAggregate`.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 1]
```diff
@@ -173,13 +174,13 @@ public class Analyzer extends ParameterizedRuleExecutor<LogicalPlan, AnalyzerCon
         ),
         new Batch<>(
             "Resolution",
+            new ResolveRefs(),
             /*
              * ImplicitCasting must be before ResolveRefs. Because a reference is created for a Bucket in Aggregate's aggregates,
              * resolving this reference before implicit casting may cause this reference to have customMessage=true, it prevents further
              * attempts to resolve this reference.
              */
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:182]: 1. why does the order matter now vs before.
2. the comment no longer hold true (looks like it was a harbinger of things to come).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 2]
```diff
@@ -585,17 +586,38 @@ private Aggregate resolveAggregate(Aggregate aggregate, List<Attribute> children
...
-                        return ne;
-                    });
-                    newAggregates.add(agg);
+                // If the groupings are not resolved, skip the resolution of the references to groupings in the aggregates, resolve the
+                // aggregations that do not reference to groupings, so that the fields/attributes referenced by the aggregations can be
+                // resolved, and verifier doesn't report field/reference/column not found errors for them.
+                boolean groupingResolved = Resolvables.resolved(groupings);
+                int size = groupingResolved ? aggregates.size() : aggregates.size() - groupings.size();
+                for (int i = 0; i < aggregates.size(); i++) {
+                    NamedExpression ag = aggregates.get(i);
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:595]: Please use better naming than agg and ag (e.g. `maybeResolvedAgg`).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 3]
```diff
@@ -585,17 +586,38 @@ private Aggregate resolveAggregate(Aggregate aggregate, List<Attribute> children
...
+                            } else {
+                                // An item in aggregations can reference to groupings explicitly, if groupings are not resolved yet and
+                                // maybeResolved is not resolved, return the original UnresolvedAttribute, so that it has a another chance
+                                // to get resolved in the next iteration.
+                                // For example STATS c = count(emp_no), x = d::int + 1 BY d = (date == "2025-01-01")
+                                if (maybeResolved instanceof Unresolvable == false) {
+                                    changed.set(true);
+                                    ne = maybeResolved;
+                                }
+                            }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:614]: maybeResolveAttribute never returns null
Furthermore the if/else can be simplified, e.g.
```
if (groupingResolved || maybeResolved.resolved() == false) {
   changed.set(true);
  ne = maybeResolved;
}
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 4]
```diff
@@ -585,17 +586,38 @@ private Aggregate resolveAggregate(Aggregate aggregate, List<Attribute> children
...
+                            return ne;
+                        });
+                        newAggregates.add(agg);
+                    } else {
+                        newAggregates.add(ag); // Groupings are not resolved
+                    }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java:620]: Same here - instead of doing an if/else perform the condition only on updating agg and always update it similar to the previous code style:
```
var agg = ...
if (groupingResolved) {
   agg = 
}

newAggregates.add(agg);
```

**Review by costin — APPROVED** [review]
Left some comments otherwise LGTM

**Review by alex-spies — COMMENTED** [review]
Thanks @fang-xing-esql ! Should we also add the csv test from the issue, your original reproducer?

```
from sample_data
| EVAL date = "2024-01-01"::datetime
| stats max = MAX(@timestamp) BY c = (date == "2024-01-01")
```

**Comment by fang-xing-esql** [comment]
Thank you for reviewing @costin @alex-spies ! All your comments have been addressed.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: The reason that `ImplicitCasting` was put before `ResolveRefs` is exactly because that `resolveAggregate` was attempting to resolve the references to the groupings, before the groupings are resolved, and it causes the references to the groupings marked unresolvable too early. This comment is outdated and removed. Thanks for the reminder!
