### PR TITLE
ESQL: Fix MV_DEDUPE when using data from an index

### LINKED ISSUE #104745: ESQL: mv_dedupe does not work with data from an index
On current main (bec2115f8ffd2e6efedf3776a733d8c42a98e625), `mv_dedupe`  does not seem to do anything if its argument is an integer field:
```
POST /testidx/_doc
{
  "int_field": [1, 2, 2, 3]
}

POST /_query
{
  "query": "from testidx | eval mv_dedupe(int_field)"
}

   int_field   |mv_dedupe(int_field)
---------------+--------------------
[1, 2, 2, 3]   |[1, 2, 2, 3] 
```

Using a text field instead, all seems fine:
```
POST /testidx/_doc
{
  "text_field": ["a", "b", "b", "c"]
}

POST /_query
{
  "query": "from testidx | eval mv_dedupe(int_field)"
}

   int_field   |  text_field   |text_field.keyword|mv_dedupe(text_field)
---------------+---------------+------------------+---------------------
[1, 2, 2, 3]   |null           |null              |null                 
null           |[a, b, b, c]   |[a, b, c]         |[a, b, c] 
```

Using integers in a `row` expression also works as expected:
```
POST /_query
{
  "query":  "row x = [1,2,2,3]| eval mv_dedupe(x)"
}

       x       | mv_dedupe(x)  
---------------+---------------
[1, 2, 2, 3]   |[1, 2, 3] 
```

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/104745.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 1]
```diff
@@ -580,7 +580,7 @@ private ComputeBlockLoaderFactory(BlockFactory factory, int pageSize) {
 
         @Override
         public BlockLoader.BooleanBuilder booleansFromDocValues(int expectedCount) {
-            return factory.newBooleanBlockBuilder(expectedCount).mvOrdering(Block.MvOrdering.DEDUPLICATED_AND_SORTED_ASCENDING);
+            return factory.newBooleanBlockBuilder(expectedCount);
```
Comment (alex-spies) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:583]: @nik9000 it probably had a very good reason why we assumed this MvOrdering, but in practice unordered multi-values with dups, loaded from an index, ended up being marked as deduplicated which mv_dedupe used to optimize itself away into a no-op.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/string.csv-spec [hunk 2]
```diff
@@ -434,6 +434,16 @@ ROW a=["foo", "foo", "bar", "foo"]
...
 ;
 
+mvDedupeFromIndex
+from multivalues
+| eval b = mv_dedupe(boolean), k = mv_dedupe(keyword), i = mv_dedupe(integer), l = mv_dedupe(long), d = mv_dedupe(double)
+| keep b, k, i, l, d
+;
+
+b:boolean     | k:keyword      | i:integer | l:long | d:double
+[false, true] | ["bar", "foo"] | [1, 2]    | [1, 2] | [1.1, 2.2]
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/string.csv-spec:444]: I have no idea why, but without this fix, the multivalues are _not deduped_, but _indeed sorted_ when running the query from above; so this fails with

```
row 0 column 2:a list containing
row 0 column 2:0: expected "[1, 2]" but was "[1, 1, 2, 2]"
row 0 column 3:a list containing
row 0 column 3:0: expected "[1, 2]" but was "[1, 1, 2, 2]"
row 0 column 4:a list containing
row 0 column 4:0: expected "[1.1, 2.2]" but was "[1.1, 1.1, 2.2, 2.2]"
```

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/MultivalueDedupeBoolean.java [hunk 3]
```diff
@@ -43,7 +43,7 @@ public MultivalueDedupeBoolean(BooleanBlock block) {
      * Dedupe values using an adaptive algorithm based on the size of the input list.
      */
     public BooleanBlock dedupeToBlock(BlockFactory blockFactory) {
-        if (false == block.mayHaveMultivaluedFields()) {
+        if (block.mvDeduplicated()) {
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/MultivalueDedupeBoolean.java:46]: :+1:

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:583]: Booleans come from https://lucene.apache.org/core/8_0_0/core/index.html?org/apache/lucene/document/SortedNumericDocValuesField.html which is sorted. They are stored as `0` and `1` and sorted. So all the `false` values should be before all of the `true` values.

So, I think, these should be `Block.MvOrdering.SORTED_ASCENDING`. Which a constant we don't have. FWIW it's much more efficient to deduplicate those. But we can get that code later.

I'm unsure how this made it this long. Numerics are not deduplicated - we can't pretend they are. Nor can we for booleans.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 4]
```diff
@@ -590,7 +590,7 @@ public BlockLoader.BooleanBuilder booleans(int expectedCount) {
 
         @Override
         public BlockLoader.BytesRefBuilder bytesRefsFromDocValues(int expectedCount) {
-            return factory.newBytesRefBlockBuilder(expectedCount).mvOrdering(Block.MvOrdering.DEDUPLICATED_AND_SORTED_ASCENDING);
+            return factory.newBytesRefBlockBuilder(expectedCount);
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:593]: But these *are* deduplicated. We should keep this line as is.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/string.csv-spec (hunk 2 above)
Comment (nik9000) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/string.csv-spec:444]: It's because numeric *are* sorted, but not deduplicated. Disaster.

**Review by nik9000 — CHANGES_REQUESTED** [review]

**Comment by nik9000** [comment]
Thanks for getting this! I'd feel better if we added a new enum constanted for `SORTED_ASCENDING` and stuck it on the numerics in this PR. And kept the current constant on bytes. The new constant won't do anything, but we can plug it in easily enough later.

**Comment by alex-spies** [comment]
Thanks @nik9000 , added the new constant and updated the orderings in the operator, corresponding tests as well as the doc of the `BlockFactory` interface.

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Block.java [hunk 5]
```diff
@@ -121,6 +121,7 @@ public interface Block extends Accountable, BlockLoader.Block, NamedWriteable, R
     enum MvOrdering {
         UNORDERED(false, false),
         DEDUPLICATED_UNORDERD(true, false),
+        SORTED_ASCENDING(false, true),
```
Comment (astefan) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Block.java:124]: We are serializing the MvOrdering as well and a newer ESQL version reading from an old version Enum I _think_ it will be confused by the position in the Enum of this new value. Take a look at `StreamOutput.writeEnum`.

What I'm trying to say is that, because the enum values are serialized using their values' position in the enum, new values added to a serializable enum should be added at the end.

**Review by astefan — CHANGES_REQUESTED** [review]
One aspect that needs a deeper investigation regarding the order of the enum values.
Another aspect regarding adding a new csv index with one document just for one test.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Block.java (hunk 5 above)
Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Block.java:124]: In the rest of Elasticsearch we implement enum serialization by hand rather than by ordinal. Well, we've mostly been doing that. I think SQL forked from a time when we were doing it by ordinal.

We transitioned because of cases like this - the "right" way to solve this is to send the key for `UNORDERED` to older node versions on the wire. If the serialization code was explicit then you'd be able to do it right in the enum itself.

Comment (nik9000) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Block.java:124]: I'm fine pulling this out of the fix if that makes things easier to land. We can get it in a followup.

Comment (alex-spies) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/data/Block.java:124]: All good, that's easy to get right - just missed it initially :)

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/mapping-multivalues.json [hunk 6]
```diff
@@ -0,0 +1,19 @@
+{
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/mapping-multivalues.json:1]: I realized that this requires larger changes since `employees.csv` does not seem to have doubles with duplicate multivalues. I'll go with a yaml test instead.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by alex-spies** [comment]
Thanks for the reviews @nik9000 and @astefan !

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.14|[](https://github.com/elastic/elasticsearch/pull/107850)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
