### PR TITLE
ES|QL: Disable optimizations that rely on Expression.nullable()

### LINKED ISSUE #104995: ES|QL: Bug in filtering of null values on multivalued
### Elasticsearch Version

8.12.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

Adding a singlevalue and a multivalue field returns null — this is expected. When wanting to exclude the row from the final result set, I tried to do this with `WHERE sum IS NOT NULL`. This does not exclude the row from the result.

Surprisingly, the opposite condition excludes it (`WHERE sum IS NULL`). It feels like this is the wrong way around?

### Steps to Reproduce

Query:

```
POST _query?format=txt
{
  "query": """
    ROW a = 5, b = [ 1, 2 ]
    | EVAL a - 3, b + 2, sum = a + b
    | LIMIT 1
    | WHERE sum IS NOT NULL
  """
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/104995

This PR disables all the planning optimizations that rely on `Expression.nullable()`. 
The semantics of this QL API have changed significantly in ESQL, so for now we'll just remove all the code that uses it. See also comments [here](https://github.com/elastic/elasticsearch/pull/105023#issuecomment-1955640677)

### CODE REVIEW

**Review by astefan — CHANGES_REQUESTED** [review]
Since now ESQL is using its own rules for folding null and there is also the new PropagateNullable rule, you should look into adding many more tests to LogicalPlanOptimizerTests. Take a look at what's being tested in SQL (start from https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java#L342) and port over all the relevant tests and add new ones covering ESQL specific behavior.

**Comment by luigidellaquila** [comment]
Thanks @astefan, makes sense.
I added unit tests for all the rules I changed, and I realized that I could simplify some overrides.

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/FoldNull.java [hunk 1]
```diff
@@ -8,9 +8,8 @@
 package org.elasticsearch.xpack.esql.optimizer;
 
 import org.elasticsearch.xpack.ql.expression.Expression;
-import org.elasticsearch.xpack.ql.optimizer.OptimizerRules;
 
-public class FoldNull extends OptimizerRules.FoldNull {
+public class FoldNull extends LogicalPlanOptimizer.FoldNull {
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/FoldNull.java:12]: I don't think this class is needed anymore.

**Review by astefan — COMMENTED** [review]
The tests you added are a good start, but they don't seem to cover what the OptimizerTests was covering in SQL. One example is `testGenericNullableExpression` which looks at more types of expressions than this PR is. There is also `testNullFoldingDoesNotApplyOnConditionals` that deals with conditional functions (ESQL has these as well).

The two tests above are just two examples, I didn't make an exhaustive search for what's missing and what not. Please, take your time to address all the relevant tests.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/FoldNull.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/FoldNull.java:12]: We still need it unfortunately, It's there because FoldNull.rule() is protected, and it's used also by `AbstractFuncitonTestCase`

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/FoldNull.java:12]: Unless we want to make it public in ESQL

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 2]
```diff
@@ -3312,4 +3366,279 @@ public static RLike rlike(Expression left, String exp) {
...
+    public void testIsNullAndMultipleComparison() throws Exception {
+        FieldAttribute fa = getFieldAttribute("a");
+        IsNull isNull = new IsNull(EMPTY, fa);
+
+        And nestedAnd = new And(EMPTY, lessThanOf(getFieldAttribute("b"), ONE), lessThanOf(getFieldAttribute("c"), ONE));
+        And and = new And(EMPTY, isNull, nestedAnd);
+        And top = new And(EMPTY, and, lessThanOf(fa, ONE));
+
+        Expression optimized = new LogicalPlanOptimizer.PropagateNullable().rule(top);
+        Expression expected = new And(EMPTY, and, nullOf(BOOLEAN));
```
[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3685]: Actually, running this through a test (`row a = 1, b = 0, c = 0 | eval a IS NULL AND b < 1 AND c < 1 AND a <= 1`) the plan is optimized as `[ISNULL(1[INTEGER]) AND null[BOOLEAN] AND null[BOOLEAN] AND null[BOOLEAN]`. This is not right. For whatever reason (I stopped looking into it at this point), `1` (as Literal) is added to the list of `nullExpressions` in `OptimizerRules.PropagateNullable.rule` and then, with your change in `LogicalPlanOptimizer.PropagateNullable.nullify` the `1` (Literal) is replaced as the "null" value in all other expressions where 1 is encountered.

For a different test where the coincidence of `1` disappears (`a = 1` and `a is null` and `b < 1`.... that is the same `1`) the rule yields something else. So the test is `row a = 5, b = 0, c = 0 | eval a IS NULL AND b < 1 AND c < 1 AND a <= 1` and the rule PropagateNullable changes the plan to `[ISNULL(5[INTEGER]) AND 0[INTEGER] < 1[INTEGER] AND 0[INTEGER] < 1[INTEGER] AND null[BOOLEAN]`.

I see two problems, that all might have to do with a single source:
- `1` gets replaced in the expressions as `null`
- `a <= 1` becomes `null`

**Review by astefan — COMMENTED** [review]
Better tests this time. Thanks.
But, there are some fine details in these tests that reveal something that doesn't work right. Please, see my comments in LogicalPlanOptimizerTests.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 3]
```diff
@@ -3312,4 +3366,279 @@ public static RLike rlike(Expression left, String exp) {
...
+        And and = new And(EMPTY, new IsNull(EMPTY, fa), new IsNotNull(EMPTY, fa));
+        assertEquals(FALSE, new LogicalPlanOptimizer.PropagateNullable().rule(and));
+    }
+
+    // a IS NULL AND b IS NOT NULL AND c IS NULL AND d IS NOT NULL AND e IS NULL AND a IS NOT NULL => false
+    public void testIsNullAndNotNullMultiField() throws Exception {
+        FieldAttribute fa = getFieldAttribute("a");
+
+        And andOne = new And(EMPTY, new IsNull(EMPTY, fa), new IsNotNull(EMPTY, getFieldAttribute("a")));
+        And andTwo = new And(EMPTY, new IsNull(EMPTY, getFieldAttribute("a")), new IsNotNull(EMPTY, getFieldAttribute("a")));
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3658]: Good catch, let me fix it

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 4]
```diff
@@ -3312,4 +3366,279 @@ public static RLike rlike(Expression left, String exp) {
...
+        assertEquals(FALSE, new LogicalPlanOptimizer.PropagateNullable().rule(and));
+    }
+
+    // a IS NULL AND a > 1 => a IS NULL AND false
+    public void testIsNullAndComparison() throws Exception {
+        FieldAttribute fa = getFieldAttribute("a");
+        IsNull isNull = new IsNull(EMPTY, fa);
+
+        And and = new And(EMPTY, isNull, greaterThanOf(fa, ONE));
+        assertEquals(new And(EMPTY, isNull, nullOf(BOOLEAN)), new LogicalPlanOptimizer.PropagateNullable().rule(and));
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3672]: oh yes, the comment is incorrect

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3685]: That's interesting, I'll look deeper into this case, maybe I broke something in the original logic

[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3685]: The problem seems to be due to an interference between two rules ([PropagateEvalFoldables](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java#L479) and [PropagateNullable](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1705)), my change only exposed it. 
In addition, the different semantics of nullability in ESQL makes this whole management much more complex.

What happens is the following:
1. `PropagateEvalFoldables` replaces all the occurrences of `a` and `b` with `1`, so `row a = 1, b = 1, c = 1 | eval a IS NULL AND b < 1 AND c < 1 AND a <= 1` becomes `row a = 1, b = 1, c = 1 | eval 1 IS NULL AND 1 < 1 AND 1 < 1 AND 1 <= 1`. This is not evident in the planning logs, because when we print the single plans we only see the original source, not the actual values in the expression nodes (see screenshot below)
2. `PropagateNullable` tries to optimize `a IS NULL ... AND a <= 1` as `a IS NULL ... AND NULL <= 1` (and not `a IS NULL AND FALSE`, the comment [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1703) is wrong. The replacer used in the rule is [this::nullify](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1741), that produces `NULL` for the attribute, not `FALSE` for the whole expression). 
3. This happens by [finding the field](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1722) that is supposed to be null (`a` in this case), looking for it in other expressions, and [replacing it](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1741) with `NULL`. The problem is that there is no `a` at this time, because it was replaced with `1` (see point 1). Even worse, also other expressions were replaced with `1` (in this case, `b < 1` is now `NULL < 1`), so they will also be affected by this replacement, that is completely unexpected.

See this screenshot: when trying to infer the null expressions, the actual field value `isn.field()`, that was expected to return `a`, returns `1` instead

Screenshot 2024-03-05 alle 14 08 16

---

So why did it work before?

In the original implementation it worked only because expressions like `constant < constant` were considered non-nullable, so `nullify()` returned the original expression. In practice, the rule did nothing in this case.

IMHO this is another problem: [relying on nullability to replace values with NULL](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java#L1782) does not seem to be so safe: if we know that `a == 1` and we try to optimize `a < 0`, we cannot just replace `a` with null, because calculating  `1 < 0` is different from calculating `null < 0`, due to null virality.

--- 

How to fix it?

The problem seems to be limited to foldable literals, so we could explicitly exclude this case. Something like

```java
        protected Expression nullify(Expression exp, Expression nullExp) {
            return exp.foldable() ? exp : Literal.of(exp, null);
        }
```
An alternative is to completely drop this rule, that would be the safest path, but also a shame because it looks correct (though a bit intricate)  for non-foldable attributes, so we would give up on a valid optimization.

Or we could try to completely rewrite it, but it doesn't seem trivial.

Suggestions are welcome

[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:3685]: My alternative from a month ago was to split FoldNull: https://github.com/elastic/elasticsearch/compare/main...astefan:elasticsearch:fold_null_split?expand=1.

[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: Turns out that the fix above on `nullify()` method is not enough: if a constant value becomes a target for "nullification", it will be transformed in other unexpected places, eg. in the right-hand side of a completely unrelated expression.

I went for a different solution: exclude constant expressions from `PropagateNullable` logic since the beginning. 
In terms of performance it should not make any difference, foldable expressions will eventually be folded anyway, there is no need to nullify them in advance.
The case you mentioned above should be fine now, I added a specific test for that

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 5]
```diff
@@ -1587,4 +1589,72 @@ private static LogicalPlan normalize(Aggregate aggregate, AttributeMap<Expressio
...
+            if (modified) {
+                // reconstruct the expression
+                return Predicates.combineAnd(splits);
+            }
+            return and;
+        }
+
+        protected Expression nullify(Expression exp, Expression nullExp) {
+            return Literal.of(exp, null);
+        }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1658]: This doesn't look right - to always return null regardless of the nullExp.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 6]
```diff
@@ -1587,4 +1589,72 @@ private static LogicalPlan normalize(Aggregate aggregate, AttributeMap<Expressio
...
+
+            // first find isNull/isNotNull
+            for (Expression ex : splits) {
+                // Avoid considering constants. It would lead to collisions with foldable propagation
+                // Folding will take care of them eventually anyway
+                if (ex instanceof IsNull isn && isn.field().foldable() == false) {
+                    nullExpressions.add(isn.field());
+                } else if (ex instanceof IsNotNull isnn && isnn.field().foldable() == false) {
+                    notNullExpressions.add(isnn.field());
+                }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1631]: Why is there a collision over foldables?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: > The replacer used in the rule is [this::nullify](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java?rgh-link-date=2024-03-05T15%3A05%3A13Z#L1741), that produces NULL for the attribute, not FALSE for the whole expression).

The original method returns null IF the expression is nullable which is true for functions only if at least one child is null. However it is also true for attributes / FieldAttributes leading to its replacement with null.
In might be that in the SQL planner this didn't get a chance kick in because of the other rules - one fix would be to change the nullify method.

**Review by costin — CHANGES_REQUESTED** [review]
Great find by @astefan on null rules. Left a few comments to help minimize the amount of code in this PR.

**Review by costin — CHANGES_REQUESTED** [review]
Great find by @astefan on null rules. Left a few comments to help minimize the amount of code in this PR.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 5 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1658]: I see what you mean, it seems a stretch, but:
- the parent method returns null regardless of the nullExp as well
- I cannot speculate on expression nullability, because we know in ESQL the nullability logic is inconsistent

SQL only uses `nullExp` to do one additional optimization on `coalesce()` (remove the expressions that we know are null); I'll add this optimization, but it doesn't change the correctness of the rule.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1631]: I explained it here https://github.com/elastic/elasticsearch/pull/105691#discussion_r1512986433

The problem is that `PropagateEvalFoldables` (that only exists in ESQL, that is probably one of the reasons why we don't have this problem in SQL) replaces fields with their value when they are foldable, so:
- if `a = 1`, an expression like `a is null` could become `1 is null`
- for `a is null`, that now is `1 is null`, `isn.field()` returns `1`, that gets added to nullExpressions
- nullExpressions are then replaced with NULL in other expressions in the same AND block, so also completely unrelated expressions like `b > 1` could be impacted, that is exactly the problem @astefan reported

In SQL the problem doesn't happen also because `nullify()` can rely on `nullable() = false` to filter out these cases. Paradoxically, if we cannot rely on the nullability logic in ESQL, we don't even know that `1` is nullable.

**Comment by luigidellaquila** [comment]
> The original method returns null IF the expression is nullable which is true for functions only if at least one child is null. However it is also true for attributes / FieldAttributes leading to its replacement with null.

@costin the problem is that we cannot rely on nullability logic. In ESQL an expression can be null also in other situations, eg. mv or number overflows.

> In might be that in the SQL planner this didn't get a chance kick in because of the other rules - one fix would be to change the nullify method.

The problem doesn't kick in in SQL for two reasons:
- in ESQL we have `PropagateEvalFoldables` that injects constants when SQL had attributes
- SQL can rely on nullability logic, ESQL cannot

I tried to change `nullify()`, but it didn't work: at that stage it's too late, I tried to summarize it in the [comments above](https://github.com/elastic/elasticsearch/pull/105691#discussion_r1515823851)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 6 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1631]: > Paradoxically, if we cannot rely on the nullability logic in ESQL, we don't even know that 1 is not nullable.

in this specific case I could fold, but we have other rules that do that, this one is about nullability

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by luigidellaquila** [comment]
`elasticsearch-ci/rest-compatibility` finished and was green, but for some reason  GitHub after a few hours still didn't see it...

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java [hunk 7]
```diff
@@ -1848,10 +1856,10 @@ protected Set<Expression> resolveExpressionAsRootAttributes(Expression exp, Attr
             return changed ? resolvedExpressions : emptySet();
         }
 
-        private boolean doResolve(Expression exp, AttributeMap<Expression> aliases, Set<Expression> resolvedExpressions) {
+        protected boolean doResolve(Expression exp, AttributeMap<Expression> aliases, Set<Expression> resolvedExpressions) {
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java:1859]: The method can be kept private.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java [hunk 8]
```diff
@@ -1752,7 +1760,7 @@ protected Expression rule(And and) {
          * If a match is found, the matching expression will be replaced by the replacer result
          * or removed if null is returned.
          */
-        private static boolean replace(
+        protected static boolean replace(
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRules.java:1763]: Method can be kept private.

**Review by costin — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM
