### PR TITLE
Stop RecordingApmServer message processing before returning from tests

### LINKED ISSUE #129651: [CI] TracesApmIT testApmIntegration failing
**Build Scans:**
- [elasticsearch-intake #24241 / part1](https://gradle-enterprise.elastic.co/s/qgjflchwzqzdo)
- [elasticsearch-pull-request #76287 / part-1](https://gradle-enterprise.elastic.co/s/35vqlhvpzhy3u)
- [elasticsearch-intake #24132 / part1](https://gradle-enterprise.elastic.co/s/d5bskulk3zpkg)

**Reproduction Line:**
```
./gradlew ":test:external-modules:test-apm-integration:javaRestTest" --tests "org.elasticsearch.test.apmintegration.TracesApmIT.testApmIntegration" -Dtests.seed=D5A755F13853B64F -Dtests.locale=es-CR -Dtests.timezone=Asia/Singapore -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.test.apmintegration.TracesApmIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testApmIntegration),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: State is not RESPONSE (REQUEST)
```

**Issue Reasons:**
- [main] 3 failures in test testApmIntegration (1.2% fail rate in 245 executions)
- [main] 2 failures in step part1 (5.1% fail rate in 39 executions)
- [main] 2 failures in pipeline elasticsearch-intake (5.1% fail rate in 39 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
The RecordingApmServer needs to be started before the ElasticsearchCluster; however, it needs to be stopped (or, at least, it needs stopping processing messages) _before_ the ElasticsearchCluster. 
JUnit rules do process before/after in reverse order at startup/shutdown; using a RuleChain slightly improves the situation (as opposed to today's ClassRule + Rule), but does not solve the issue.
Here I am introducing an additional "stop" method; the method needs to be called explicitly at the end of the test, but this way we can make RecordingApmServer stop processing requests before the ElasticsearchCluster is gone and communication is interrupted exceptionally.

Fixes https://github.com/elastic/elasticsearch/issues/129651

### CODE REVIEW

File: test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/RecordingApmServer.java [hunk 1]
```diff
@@ -75,21 +74,27 @@ private Thread consumerThread() {
...
+                        if (requestBody != null) {
+                            var read = readJsonMessages(requestBody);
+                            received.addAll(read);
+                        }
                     }
-                }
 
-            } catch (RuntimeException e) {
-                logger.warn("failed to parse request", e);
+                } catch (RuntimeException e) {
```
Comment (mosche) [inline test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/RecordingApmServer.java]: Wondering, we could also handle the IOException here?
Currently we just swallow runtime exceptions, we could capture any exception and assert there hasn't been any at the end of the test.... and whatever happens afterwards doesn't matter.
To me that feels a bit more robust than having to know that the mock server resource has to be stopped in advance - and understanding why that doesn't hurt ES

**Review by mosche — APPROVED** [review]
lgtm, though wondering if it wouldn't be easier to reason if instead handling IOExceptions

File: test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/RecordingApmServer.java (hunk 1 above)
Comment (ldematte) [reply test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/RecordingApmServer.java]: I was wondering the same; we can just handle Throwable and don't care (log, but don't care):  if we have an error in communicating to/from the mock server the test would fail anyway as the expected messages will not arrive.
I preferred the "stop" thing as it solves the issue we are seeing in the test failures, but I'm not sure.

Comment (mosche) [reply test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/RecordingApmServer.java]: I'm good either way, no strong preference here... 
One thing to consider is if moving from using the agent to the sdk... we'd want to make sure to publish all inflight traces/metrics on shutdown. Haven't thought about it much, but we'd probably want to assert for that some way.

**Review by rjernst — COMMENTED** [review]
I'm confused how this addresses the linked failure. I thought the problem was the apm agent continues to run in the background, so requests to the recording server begin failing. Can you explain how this change fixes the issue?

**Comment by ldematte** [comment]
Turned out that the issue is that the APM agent is in the middle of writing, ES gets shut down, the connection breaks, the mock APM server throws.
Shutting down the APM server before ES brings things down cleanly.
But thinking again, this is still brittle and an implementation detail; probably catching all exceptions like we were discussing is still better (more robust and simpler)

**Comment by ldematte** [comment]
@mosche I've decided to go with your suggestion; I tried to refactor the RecordingApmServer to better coordinate the APM mock server and the ES cluster, but it's error prone and I was not satisfied. So better to go with the minimalist and more robust solution, at least until we stay with the APM agent.

**Review by mosche — APPROVED** [review]
lgtm 👍
