### PR TITLE
Unmute flaky csv-spec tests with more logging on warnings context

### LINKED ISSUE #133334: [CI] MultiClusterSpecIT test {csv-spec:change_point.Values null column} failing
**Build Scans:**
- [elasticsearch-intake #27247 / 9.2.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/z3d7qfhyxyvpc)
- [elasticsearch-pull-request #87196 / 8.19.3_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/6dv5xc7ezxt3q)
- [elasticsearch-pull-request #87196 / 9.0.6_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/tpczm24ytlggm)
- [elasticsearch-pull-request #87196 / 9.2.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/akqow6hnumtiq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v9.2.0#newToOld" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {csv-spec:change_point.Values null column}" -Dtests.seed=702EB40149BD0CD8 -Dtests.bwc=true -Dtests.locale=vi-Latn-VN -Dtests.timezone=Asia/Tokyo -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Achange_point.Values%20null%20column%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 3:3: evaluation of [CHANGE_POINT values ON time] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 3:3: java.lang.IllegalArgumentException: not enough buckets to calculate change_point. Requires at least [22]; found [0]" but was <missing>
2: expected "Line 3:3: java.lang.IllegalArgumentException: values contain nulls; skipping them" but was <missing>
```

**Issue Reasons:**
- [main] 4 failures in test test {csv-spec:change_point.Values null column} (0.4% fail rate in 1000 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #134104: [CI] MultiClusterSpecIT test {csv-spec:spatial.ConvertFromStringParseError} failing
**Build Scans:**
- [elasticsearch-periodic #10436 / 9.0.7_bwc](https://gradle-enterprise.elastic.co/s/dd4tyha7r66eg)
- [elasticsearch-pull-request #89813 / 8.19.4_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/73e5pi7ffjoxe)
- [elasticsearch-pull-request #89810 / 9.2.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/soifdny4u4b2s)
- [elasticsearch-pull-request #89813 / 9.0.7_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/bax3k3p5djf72)
- [elasticsearch-pull-request #89813 / 9.2.0_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/3h4bbonkj35sw)
- [elasticsearch-pull-request #89813 / 9.1.4_part_3_bwc-snapshots](https://gradle-enterprise.elastic.co/s/dcw2wqnxtdrqo)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v9.0.7#newToOld" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {csv-spec:spatial.ConvertFromStringParseError}" -Dtests.seed=58D22CD96375EBD0 -Dtests.bwc=true -Dtests.locale=luo-KE -Dtests.timezone=America/Goose_Bay -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Aspatial.ConvertFromStringParseError%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 3:13: evaluation of [to_geopoint(wkt)] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 3:13: java.lang.IllegalArgumentException: Failed to parse WKT: Unknown geometry type: pointx" but was <missing>
2: expected "Line 3:13: java.lang.IllegalArgumentException: Failed to parse WKT: expected number but found: ')'" but was <missing>
```

**Issue Reasons:**
- [main] 6 failures in test test {csv-spec:spatial.ConvertFromStringParseError} (0.6% fail rate in 1000 executions)
- [main] 2 failures in step 9.2.0_part_3_bwc-snapshots (3.0% fail rate in 66 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.9% fail rate in 69 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135455: [CI] EsqlSpecIT test {csv-spec:spatial_shapes.ConvertCartesianShapeFromStringParseError} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10811 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/rhahuibnvmskc)
- [elasticsearch-pull-request #94347 / part-3](https://gradle-enterprise.elastic.co/s/nfmezh4nj7kpw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:spatial_shapes.ConvertCartesianShapeFromStringParseError}" -Dtests.seed=E3EF086FF31CB596 -Dtests.locale=fr-NE -Dtests.timezone=Africa/Freetown -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Aspatial_shapes.ConvertCartesianShapeFromStringParseError%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected a list containing
0: expected "Line 3:13: evaluation of [to_cartesianshape(wkt)] failed, treating result as null. Only first 20 failures recorded." but was <missing>
1: expected "Line 3:13: java.lang.IllegalArgumentException: Failed to parse WKT: Unknown geometry type: pointx" but was <missing>
2: expected "Line 3:13: java.lang.IllegalArgumentException: Failed to parse WKT: expected number but found: ')'" but was <missing>
```

**Issue Reasons:**
- [main] 2 failures in test test {csv-spec:spatial_shapes.ConvertCartesianShapeFromStringParseError} (0.4% fail rate in 519 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by craigtaverner**
These tests do not reproduce, even with reported random seeds. We are unmuting them in the hope that the additional logging will bring some clarity to the situations under which they fail.

Of note is that there are 186 tests that have warnings specified, but only 8 issues reported grouped into the following test classes:
* EsqlSpecIT - 1 issue
* MultiClusterSpectIT - 3 issues
* GenerativeForkIT - 4 issues

Five of the eight were related to parsing invalid geospatial types, the other three were change_point, fuse and space-negative.

Six of the eight were reported on main:

Fixes #136249
Fixes #135455
Fixes #134635
Fixes #134254
Fixes #134104
Fixes #133334

Two issues were only muted on 9.2, so we should unmute in the backport: #136285 and #136068

### CODE REVIEW

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/AssertWarnings.java [hunk 1]
```diff
@@ -18,34 +18,55 @@
...
+            return "";
+        }
+        StringBuilder contextBuilder = new StringBuilder();
+        contextBuilder.append("Context: ").append(context);
+        if (contextBuilder.length() > 1000) {
+            contextBuilder.setLength(1000);
+            contextBuilder.append("...(truncated)");
+        }
+        contextBuilder.append("\n");
+        return contextBuilder.toString();
```
Comment (craigtaverner) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/AssertWarnings.java:34]: Just in case you're wondering, I've tested this multiple times by deliberately messing with the tests expected warnings, and I do see meaningful stuff being printed here in the error messages. Whether that will clarify the flakiness or not is yet to be seen.

**Review by cimequinox — APPROVED** [review]
This change unmutes 6 muted tests and adds additional context to several
warning assertions as described.

**Comment by craigtaverner** [comment]
Manual backport at https://github.com/elastic/elasticsearch/pull/137107
