### PR TITLE
Don't reset non-dynamic settings unless explicitly requested

### LINKED ISSUE #21593: Deleting non-dynamic settings by cluster settings API
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
```
    private boolean updateSettings(Settings toApply, Settings.Builder target, Settings.Builder updates, String type, boolean onlyDynamic) {
        boolean changed = false;
        final Set<String> toRemove = new HashSet<>();
        Settings.Builder settingsBuilder = Settings.builder();
        for (Map.Entry<String, String> entry : toApply.getAsMap().entrySet()) {
!            if (entry.getValue() == null) {
                toRemove.add(entry.getKey());
!            } else if ((onlyDynamic == false && get(entry.getKey()) != null) || hasDynamicSetting(entry.getKey())) {
                validate(entry.getKey(), toApply);
                settingsBuilder.put(entry.getKey(), entry.getValue());
                updates.put(entry.getKey(), entry.getValue());
                changed = true;
            } else {
                throw new IllegalArgumentException(type + " setting [" + entry.getKey() + "], not dynamically updateable");
            }
```
It's possible to delete non-dynamic settings by using cluster/_settings API.
https://github.com/elastic/elasticsearch/blob/5a03eb91e664e64041315c597f320b60b556d9a7/core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java#L449
Please add the same check hasDynamicSetting(entry.getKey() to first condition.

Example:
```
PUT ...
{
    "transient" : {
        "non-dynamic-setting-name-here": null
     }
}
```

**Provide logs (if relevant)**:

**Describe the feature**:

### PR DESCRIPTION
**Pull request by s1monw**
AbstractScopedSettings has the ability to only apply updates/deletes
to dynamic settings. The flag is currently not respected when a setting
is reset/deleted which causes static node settings to be reset if a non-dynamic
key is reset via `null` value.

Closes #21593

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java [hunk 1]
```diff
@@ -445,31 +446,38 @@ private boolean updateSettings(Settings toApply, Settings.Builder target, Settin
...
 
-    private static boolean applyDeletes(Set<String> deletes, Settings.Builder builder) {
+    private static boolean applyDeletes(Set<String> deletes, Settings.Builder builder, Predicate<String> canRemove) {
         boolean changed = false;
         for (String entry : deletes) {
             Set<String> keysToRemove = new HashSet<>();
             Set<String> keySet = builder.internalMap().keySet();
             for (String key : keySet) {
-                if (Regex.simpleMatch(entry, key)) {
+                if (Regex.simpleMatch(entry, key) && canRemove.test(key)) {
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java]: given that we already check if we can remove before adding to the deletes set, do we still have to check it here?

**Review by javanna — APPROVED** [review]
LGTM
