### PR TITLE
Fix testShardMultiGetFromTranslog

### LINKED ISSUE #96749: ShardMultiGetFomTranslogActionIT.testShardMultiGetFromTranslog routinely fails
### CI Link

https://gradle-enterprise.elastic.co/s/4accu24s4cbyc

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.get.ShardMultiGetFomTranslogActionIT.testShardMultiGetFromTranslog" -Dtests.seed=AC01D0C25C12539E -Dtests.locale=hr-HR -Dtests.timezone=Africa/Windhoek -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

Test was introduced today via https://github.com/elastic/elasticsearch/pull/96492

### Failure excerpt

```java
org.elasticsearch.get.ShardMultiGetFomTranslogActionIT > testShardMultiGetFromTranslog FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([AC01D0C25C12539E:D5637AF36B6B21E3]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at org.elasticsearch.get.ShardMultiGetFomTranslogActionIT.testShardMultiGetFromTranslog(ShardMultiGetFomTranslogActionIT.java:105)
```

### PR DESCRIPTION
**Pull request by pxsalehi**
Closes https://github.com/elastic/elasticsearch/issues/96749

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java [hunk 1]
```diff
@@ -93,19 +92,22 @@ public void testShardMultiGetFromTranslog() throws Exception {
...
         assertThat(getResponses.size(), equalTo(2));
-        assertNotNull("get followed by a delete should still return a result", getResponses.get(0));
-        assertThat(getResponses.get(0).getId(), equalTo("1"));
-        assertThat(getResponses.get(0).isExists(), equalTo(false));
-        assertNotNull(getResponses.get(1));
-        assertThat(getResponses.get(1).getId(), equalTo("2"));
-        assertThat(getResponses.get(1).isExists(), equalTo(true));
+        var getResponseForDeletedId = getResponses.stream().filter(r -> r.getId().equals(idToDelete)).toList().get(0);
+        var getResponseForExistingId = getResponses.stream().filter(r -> r.getId().equals(idToDelete) == false).toList().get(0);
+        assertNotNull("get followed by a delete should still return a result", getResponseForDeletedId);
```
Comment (idegtiarenko) [inline server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java:105]: I think this would never be null:
* if the stream is empty then `.get(0)` will throw no such element
* if the stream contains the null then `.toList()` will throw NPE when constructing.

I wonder if that should be something like `findFirst` or collecting the entire list and asserting its size is at least 1?

Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java]: `getResponses` could have `null` in it. For each ID we get one item in the list, but that item could be null. But you are right that the way I've changed the code already makes that check unnecessary. I've simplified it.

**Review by idegtiarenko — APPROVED** [review]

File: server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java [hunk 2]
```diff
@@ -93,19 +92,19 @@ public void testShardMultiGetFromTranslog() throws Exception {
...
         getResponses = getResponses(multiGetShardResponse);
         assertThat(getResponses.size(), equalTo(2));
-        assertNotNull("get followed by a delete should still return a result", getResponses.get(0));
-        assertThat(getResponses.get(0).getId(), equalTo("1"));
-        assertThat(getResponses.get(0).isExists(), equalTo(false));
-        assertNotNull(getResponses.get(1));
-        assertThat(getResponses.get(1).getId(), equalTo("2"));
-        assertThat(getResponses.get(1).isExists(), equalTo(true));
+        assertTrue(getResponses.stream().allMatch(Objects::nonNull));
+        for (var getResponse : getResponses) {
```
Comment (kingherc) [inline server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java:104]: nit would be simpler to delete first element of idsToIndex. that way you'd be able to write directly assertions on the first and second element.

**Review by kingherc — APPROVED** [review]
LGTM

File: server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java (hunk 2 above)
Comment (pxsalehi) [reply server/src/internalClusterTest/java/org/elasticsearch/get/ShardMultiGetFomTranslogActionIT.java:104]: The randomized simplified version is ok I think.
