### PR TITLE
Remove InvalidShapeException from GeoPolygonDecomposer

### LINKED ISSUE #75753: invalid_shape_exception thrown despite ignore_malformed true for geo_shape
**Elasticsearch version** (`bin/elasticsearch --version`): `7.13.4`

**Plugins installed**: []

**JVM version** (`java -version`): bundled

**OS version** (`uname -a` if on a Unix-like system): `20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

**Description of the problem including expected versus actual behavior**:

Submitting a `geo_shape` of `type: polygon` with an area of 0 results in a rejection despite having `ignore_malformed: true` in the mapping. The shape violates standards, but the document as a whole should still get indexed.

**Steps to reproduce**:
```
DELETE example

PUT example
{
  "mappings": {
    "properties": {
      "location": {
        "type": "geo_shape",
        "ignore_malformed": true
      }
    }
  }
}

POST example/_doc
{
  "location": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          12.775554656982422,
          61.54486837329203
        ],
        [
          12.775554656982422,
          61.54486837329203
        ],
        [
         12.775554656982422,
          61.54486837329203
        ],
        [
          12.775554656982422,
          61.54486837329203
        ],
        [
          12.775554656982422,
          61.54486837329203
        ]
      ]
    ]
  }
}
```

Results in:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse",
    "caused_by" : {
      "type" : "invalid_shape_exception",
      "reason" : "Cannot determine orientation: signed area equal to 0. Points are collinear or polygon self-intersects."
    }
  },
  "status" : 400
}
```

Submitting a document where `location` is a `string` works as expected:

```
POST example/_doc
{
  "location": "hello world"
}
```

### LINKED ISSUE #77685: ignore_malformed = true doesn't work for geo_shape fields
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.1

**Plugins installed**: []

**JVM version** (`java -version`): Default in Docker container

**OS version** (`uname -a` if on a Unix-like system): Docker image (Linux containers)

**Description of the problem including expected versus actual behavior**:

Using dynamic templates, a mapping for `geo_shape` type fields fails with `mapper_parsing_exception`. The exception looks like this:

```txt
{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"invalid_shape_exception\",\"reason\":\"Cannot determine orientation: signed area equal to 0. Points are collinear or polygon self-intersects.\"}}"
```

The mapping in the dynamic template looks like this:

```
"dynamic_templates": [
    ...,
    {
      "spatial": {
        "mapping": {
          "type": "geo_shape",
          "orientation": "counterclockwise"
        },
        "match_mapping_type": "string",
        "match": "geoLocationBox*"
      }
    },
    ...,
]
```

And the polygon looks like this:

```txt
  "geoLocations": [
    {
      "geoLocationBox": "POLYGON ((18.9401790919516 -33.9681188869036, 18.9401790919516 -33.9681188869037, 18.9401790919517 -33.9681188869037, 18.9401790919517 -33.9681188869036, 18.9401790919516 -33.9681188869036))"
    }
  ],
```

Initially I tried setting `ignore_malformed` to true in the dynamic mapping:

```
"dynamic_templates": [
    ...,
    {
      "spatial": {
        "mapping": {
          "type": "geo_shape",
          "orientation": "counterclockwise",
          "ignore_malformed": true
        },
        "match_mapping_type": "string",
        "match": "geoLocationBox*"
      }
    },
    ...,
]
```

but that had no effect. I then removed the dynamic mapping for this match, and instead specified this field mapping explicitly:

```
{
  "properties": {
    "geoLocationBox.geoLocationBox": {
      "type": "geo_shape",
      "orientation": "counterclockwise",
      "ignore_malformed": true
    },
   ...
```

It still does not work.

Using Elasticsearch 7.10 this record did not throw an exception using exactly the same mappings.

### PR DESCRIPTION
**Pull request by iverase**
InvalidShapeException comes from Spatial4j dependency and should not be part of GeoPolygonDecomposer. Let's replace this exception with an IllegalArgumentException.

The change actually fixes a bug where InvalidShapeException are not properly handle so even if the mappings defined with `ignore_malformed` set to true, the exception leaks and the setting is ignored. Changing to IllegalArgumentException makes it behave properly.

fixes https://github.com/elastic/elasticsearch/issues/77685
fixes https://github.com/elastic/elasticsearch/issues/75753

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/common/geo/ShapeBuilderTests.java [hunk 1]
```diff
@@ -834,9 +834,6 @@ public void testInvalidSelfCrossingPolygon() {
         Exception e = expectThrows(InvalidShapeException.class, () -> builder.close().buildS4J());
         assertThat(e.getMessage(), containsString("Self-intersection at or near point ["));
         assertThat(e.getMessage(), not(containsString("NaN")));
-        e = expectThrows(InvalidShapeException.class, () -> buildGeometry(builder.close()));
-        assertThat(e.getMessage(), containsString("Self-intersection at or near point ["));
-        assertThat(e.getMessage(), not(containsString("NaN")));
```
Comment (iverase) [inline server/src/test/java/org/elasticsearch/common/geo/ShapeBuilderTests.java:839]: This is already tested in GeometryIndexerTests

**Comment by iverase** [comment]
I change this PR to be a bug fix as it fixes an issue with `ignore_malformed' setting.

**Review by imotov — APPROVED** [review]
LGTM
