### PR TITLE
Script: no compile rate limit for ingest templates

### LINKED ISSUE #64595: Use unlimited compilation rate limit for mustache templates in Ingest
In https://github.com/elastic/elasticsearch/pull/59267 the compilation rate limit for the `script` and `processor_conditional` contexts was increased to unlimited. However some of the Ingest Node processors depend on mustache templates that are also scripts that need to be compiled. And those templates have their own separate rate limit. So users of Ingest Node pipelines can still hit limits. So I'd like to propose that templates also get an unlimited compilation rate in Ingest Node.

Here's an example of the type of error users see when using Filebeat modules or packages with Fleet:

`Bulk item insert failed (i=5, status=500): {\"type\":\"illegal_state_exception\",\"reason\":\"pipeline with id [logs-system.auth-0.9.0] could not be loaded, caused by [ElasticsearchParseException[Error updating pipeline with id [logs-system.auth-0.9.0]]; nested: GeneralScriptException[Failed to compile inline script [{{system.auth.ssh.dropped_ip}}] using lang [mustache]]; nested: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.context.template.max_compilations_rate] setting];; GeneralScriptException[Failed to compile inline script [{{system.auth.ssh.dropped_ip}}] using lang [mustache]]; nested: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.context.template.max_compilations_rate] setting];; org.elasticsearch.common.breaker.CircuitBreakingException: [script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.context.template.max_compilations_rate] setting]\"}",`

### PR DESCRIPTION
**Pull request by stu-elastic**
Remove the compilation rate limit for ingest templates.

Creates a new context, `ingest_template`, with an unlimited
compilation rate limit.

The `template` context is used in many places so it cannot be
exempted from rate limits.

Fixes: #64595

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/script/TemplateScript.java [hunk 1]
```diff
@@ -35,4 +37,8 @@ public TemplateScript(Map<String, Object> params) {
     }
 
     public static final ScriptContext<Factory> CONTEXT = new ScriptContext<>("template", Factory.class);
+
+    // Remove compilation rate limit for ingest
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/script/TemplateScript.java:41]: I think this deserves a larger comment. This will be confusing enough just based on the naming here, and the fact that the same script class is used by 2 different contexts. It would be good to describe the reasons we haven't created another script class for this (complexity of implementation in mustache script engine, possible but not worth effort for now). The reason for having a separate context is also worth still mentioning, as you have, I would just add this additional info.

Comment (stu-elastic) [reply server/src/main/java/org/elasticsearch/script/TemplateScript.java]: Makes sense. Done.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by stu-elastic** [comment]
v7.12.0: 58db0a3
v7.13.0 (7.x): 8e1a615
v8.0.0 (master): 9370b1c
