### PR TITLE
Fix occasional SearchServiceTests failure

### LINKED ISSUE #39316: SearchServiceTests.testCloseSearchContextOnRewriteException failure in CI
Failed for the first time in 6.6 today, does not reproduce:
```
java.lang.AssertionError: expected:<4> but was:<2>
	at __randomizedtesting.SeedInfo.seed([294506CB775D8415:354F8B75FC0B1804]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.search.SearchServiceTests.testCloseSearchContextOnRewriteException(SearchServiceTests.java:214)
```

Reproduce line:
```
REPRODUCE WITH: ./gradlew :server:unitTest \
  -Dtests.seed=294506CB775D8415 \
  -Dtests.class=org.elasticsearch.search.SearchServiceTests \
  -Dtests.method="testCloseSearchContextOnRewriteException" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-JO \
  -Dtests.timezone=Canada/Newfoundland \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Build log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=opensuse/130/console

### PR DESCRIPTION
**Pull request by cbuescher**
Currently SearchServiceTests.testCloseSearchContextOnRewriteException can fail
if a refresh happens while we test for the SearchPhaseExecutionException that is
thrown later in the test. The test takes the current Store#refCount and expects
it to be the same after the exception is thrown. If a refresh happens in that
interval however, the refCound will be different, causing the test to fail. This
can be provoked e.g. by running this section in a tight loop.
Switching of refresh for this tests solves the issue.

Closes #39316

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/SearchServiceTests.java [hunk 1]
```diff
@@ -197,7 +198,7 @@ public void testClearIndexDelete() {
     }
 
     public void testCloseSearchContextOnRewriteException() {
-        createIndex("index");
+        createIndex("index", Settings.builder().put("index.refresh_interval", -1).build());
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/search/SearchServiceTests.java]: I think a brief comment here would be useful, as it's not obvious why we would disable refresh for this test.

**Review by jtibshirani — APPROVED** [review]
This looks good to me (although I'm new to this part of the code, so I understand if you want a second opinion).
