### PR TITLE
Bug fix for AnnotatedTextHighlighter

### LINKED ISSUE #39395: Mapper annotated text plugin highlighter crashes during text processing
**Elasticsearch version**: 6.5.4

**Plugins installed**: ["analysis-kuromoji", "ik-analyzer", "mapper-annotated-text"]

**JVM version**:

Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version**:

Windows 10 Professional Ver 1803 Build 17134.590

**Description of the problem including expected versus actual behavior**:

@markharwood 
The `annotated` highlighter in the `mapper-annotated-text` plugin crashes randomly when processing documents.

**Steps to reproduce**:

 1. Create an index with an `annotated_text` field, then add some documents:
 ```curl
PUT /test_index
{
    "mappings": {
        "_doc": {
            "properties": {
                "my_field": {
                    "type": "annotated_text",
                    "analyzer": "whitespace"
                }
            }
        }
    }
}

PUT /test_index/_doc/1
{
    "my_field" : "[A](~MARK0) [B](~MARK1)"
}

PUT /test_index/_doc/2
{
    "my_field" : "[A](~MARK0) [C](~MARK2)"
}
 ```
 2.
 The following search query will crash the `annotated` highlighter randomly. The number of returned items in `hits.hits` can be fewer than `hits.total` in the query result:
 ```curl
GET /test_index/_search
{
    "query": {
        "match_phrase": {
            "my_field": {
                "query": "~MARK0",
                "analyzer": "whitespace"
            }
        }
    },
    "highlight": {
        "type": "annotated",
        "fields": {
            "my_field": {}
        }
    }
}
 ```

**Provide logs (if relevant)**:

The highlighter throws `java.lang.NullPointerException` in two different lines:
```log
[XXXX-XX-XXTXX:XX:XX,XXX][DEBUG][o.e.a.s.TransportSearchAction] [XXXXXXX] [XXXXX] Failed to execute fetch phase
org.elasticsearch.transport.RemoteTransportException: [XXXXXXX][XXX.XXX.XXX.XXX:XXXX][indices:data/read/search[phase/fetch/id]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.index.mapper.annotatedtext.AnnotatedTextFieldMapper$AnnotatedHighlighterTokenStreamComponents.setReader(AnnotatedTextFieldMapper.java:392) ~[?:?]
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:200) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.search.uhighlight.AnalysisOffsetStrategy.tokenStream(AnalysisOffsetStrategy.java:56) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.getOffsetsEnum(MemoryIndexOffsetStrategy.java:98) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:76) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFieldsAsObjects(UnifiedHighlighter.java:639) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.CustomUnifiedHighlighter.highlightField(CustomUnifiedHighlighter.java:107) ~[elasticsearch-6.5.4.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.elasticsearch.search.fetch.subphase.highlight.UnifiedHighlighter.highlight(UnifiedHighlighter.java:128) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase.hitExecute(HighlightPhase.java:110) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:159) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$3(SearchService.java:556) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:361) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

[XXXX-XX-XXTXX:XX:XX,XXX][DEBUG][o.e.a.s.TransportSearchAction] [XXXXXXX] [XXXXX] Failed to execute fetch phase
org.elasticsearch.transport.RemoteTransportException: [XXXXXXX][XXX.XXX.XXX.XXX:XXXX][indices:data/read/search[phase/fetch/id]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.index.mapper.annotatedtext.AnnotatedTextFieldMapper$AnnotatedHighlighterAnalyzer.getPlainTextValuesForHighlighter(AnnotatedTextFieldMapper.java:337) ~[?:?]
	at org.elasticsearch.search.fetch.subphase.highlight.AnnotatedTextHighlighter.loadFieldValues(AnnotatedTextHighlighter.java:55) ~[?:?]
	at org.elasticsearch.search.fetch.subphase.highlight.UnifiedHighlighter.highlight(UnifiedHighlighter.java:74) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase.hitExecute(HighlightPhase.java:110) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:159) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$3(SearchService.java:556) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:361) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

### PR DESCRIPTION
**Pull request by markharwood**
Added thread safety to AnnotatedTextHighlighter by moving custom Analyzer object to per-request context rather than singleton.
Added YAML test that reproduced the error.

Closes #39395

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java [hunk 1]
```diff
@@ -75,6 +77,13 @@ public IndexReader topLevelReader() {
             return cache;
         }
 
+        public void analyzer(Analyzer analyzer) {
+            this.analyzer=analyzer;
+        }
+        public Analyzer analyzer() {
+            return analyzer;
+        }
+
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java]: I think we should just use the already-existing object cache to pass this analyzer around? It seems a bit odd to add a specialized object that is only used by a plugin.  We could also cache the parsed annotations rather than the analyzer itself, and store a reference to the HitContext on the analyzer

File: plugins/mapper-annotated-text/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AnnotatedTextHighlighter.java [hunk 2]
```diff
@@ -36,29 +36,33 @@
...
         annotatedHighlighterAnalyzer.init(fieldValuesAsString);
         return Arrays.asList((Object[]) annotatedHighlighterAnalyzer.getPlainTextValuesForHighlighter());
     }
 
     @Override
-    protected PassageFormatter getPassageFormatter(SearchContextHighlight.Field field, Encoder encoder) {
+    protected PassageFormatter getPassageFormatter(HitContext hitContext,SearchContextHighlight.Field field, Encoder encoder) {
+        // Retrieve the special Analyzer used for annotations in the hitContext
+        assert hitContext.analyzer() != null;
+        AnnotatedHighlighterAnalyzer annotatedHighlighterAnalyzer = (AnnotatedHighlighterAnalyzer) hitContext.analyzer();
```
Comment (romseygeek) [inline plugins/mapper-annotated-text/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/AnnotatedTextHighlighter.java]: I think the logic would be easier to follow if we moved `getIntersectingAnnotations` directly into `AnnotatedPassageFormatter`, and instead of passing the analyzer to the constructor here we pass the `AnnotatedText[]` array.

**Review by romseygeek — CHANGES_REQUESTED** [review]
Thanks Mark, I left a couple of comments.  I think this would be easier to reason about if we moved the parsing and intersection methods off the Analyzer and into the PassageFormatter and Highlighter - at the moment the Analyzer is doing lots of stuff at different times, and it's quite difficult to follow the paths through the code.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java (hunk 1 above)
Comment (markharwood) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java]: We still need to cache the analyzer because the creation and the initialization of the analyzer occur in different methods of the highlighter and we need to pass this through

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchSubPhase.java]: But the initialization just parses the annotations.  So if instead you construct the Analyzer with a reference to the HitContext, and then cache the annotations on that same HitContext in `loadFieldValues()` then the Analyzer can access them without it sitting in the cache.

File: plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedTextFieldMapper.java [hunk 3]
```diff
@@ -318,45 +319,12 @@ public AnnotationToken getAnnotation(int index) {
     // original markup form in order to inject annotations.
     public static final class AnnotatedHighlighterAnalyzer extends AnalyzerWrapper {
         private Analyzer delegate;
-        private AnnotatedText[] annotations;
-        public AnnotatedHighlighterAnalyzer(Analyzer delegate){
+        private HitContext hitContext;
```
Comment (romseygeek) [inline plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedTextFieldMapper.java]: Can be final

**Review by romseygeek — APPROVED** [review]
LGTM, one nit but no need for another go-round
