### PR TITLE
[7.5][Transform] prevent assignment if any node is older than 7.4

### LINKED ISSUE #48019: [Transform] transform jobs on nodes < 7.4.0 mixed with nodes > 7.4 might fail
Nodes in all versions of 7.2 and 7.3 might not see transform documents created in 7.4, 7.5 ...

Only _after_ the switch to a versioned index in #45375 (7.4.0) retrieval uses a search pattern to read back documents (config, checkpoint, state). This allows to retrieve jobs even if the cluster is partially upgraded. But if nodes are on version 7.3 and 7.4 the hardcoded index name those documents might not be retrievable.

Long story short: Mixed version clusters with nodes <7.4 together with nodes >=7.4 do not work reliable. 

Solution: 

 - disable node allocation if any node < 7.4. This will prevent placing jobs on mixed clusters until the upgrade has completed
 - document as known limitation: transforms do not execute during a rolling upgrade from 7.2/7.3 to 7.x

### PR DESCRIPTION
**Pull request by hendrikmuhs**
disable task assignment of transforms if any node uses version 7.2 or 7.2 (mixed cluster).

fixes #48019

Note: not needed for master as the upgrade path is 7.last -> master

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformPersistentTasksExecutor.java [hunk 1]
```diff
@@ -100,7 +101,10 @@ public TransformPersistentTasksExecutor(Client client,
             return new PersistentTasksCustomMetaData.Assignment(null, reason);
         }
         DiscoveryNode discoveryNode = selectLeastLoadedNode(clusterState, (node) ->
-            node.isDataNode() && node.getVersion().onOrAfter(params.getVersion())
+            node.isDataNode() &&
+            // see gh#48019 disable assignment if any node is using 7.2 or 7.3
+            clusterState.getNodes().getMinNodeVersion().onOrAfter(Version.V_7_4_0) &&
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformPersistentTasksExecutor.java]: I think this condition should be outside of the `selectLeastLoadedNode` function. 

It is also good to return a new custom assignment explaining why we are not assigning to a node (e.g. `Not assigning persistent task as cluster contains nodes with version older than 7.4.0`).

**Review by benwtrent — APPROVED** [review]
