### PR TITLE
Fix inference operator circuit breaker tests

### LINKED ISSUE #132382: [CI] CompletionOperatorTests testSimpleCircuitBreaking failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9919 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gwes4hr6r3mf4)
- [elasticsearch-periodic #9810 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ah5dkyddkbtxq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.inference.completion.CompletionOperatorTests.testSimpleCircuitBreaking" -Dtests.seed=DE24F92C9F748E6A -Dtests.locale=kea -Dtests.timezone=Asia/Novosibirsk -Druntime.java=24
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.inference.completion.CompletionOperatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSimpleCircuitBreaking'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=org.elasticsearch.xpack.esql.inference.bulk.BulkInferenceExecutor$BulkInferenceRequest$$Lambda/0x000000009aaf5ae8@3157998b, creationTimeNanos=3655961121545, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = CompletionOperatorTests/esql_worker, queue capacity = 1024, task execution EWMA = 192nanos, total task execution time = 312.2ms, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@8033e3b[Running, pool size = 1, active threads = 1, queued tasks = 1024, completed tasks = 6688]]
```

**Issue Reasons:**
- [9.1] 2 failures in test testSimpleCircuitBreaking (0.5% fail rate in 400 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #133619: [CI] RerankOperatorTests testSimpleCircuitBreaking failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11193 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/q43jdfawv5gpy)
- [elasticsearch-periodic #11198 / openjdk22_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/e7r3pk2y6emwu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.inference.rerank.RerankOperatorTests.testSimpleCircuitBreaking" -Dtests.seed=A4635E0B0AEC9B52 -Dtests.locale=lv-LV -Dtests.timezone=Canada/Atlantic -Druntime.java=25
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.inference.rerank.RerankOperatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSimpleCircuitBreaking'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0L>
     but: was <82656L>
```

**Issue Reasons:**
- [8.19] 2 failures in test testSimpleCircuitBreaking (1.9% fail rate in 105 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by afoucret**
- Fixes #135569 
- Fixes #132382
- Fixes #133619

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/inference/InferenceOperatorTestCase.java [hunk 1]
```diff
@@ -119,6 +134,10 @@ protected <Request extends ActionRequest, Response extends ActionResponse> void
                     listener.onFailure(new UnsupportedOperationException("Unexpected action: " + action));
                 });
             }
+
+            private void runWithRandomDelay(Runnable runnable) {
```
Comment (afoucret) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/inference/InferenceOperatorTestCase.java:138]: Previous implementation of runWithDelay was not really realistic:
- It was not always adding a delay which is never the case
- it was using the generic threadpool that can be saturated with inference request. Using a separate threadpool to execute inference looks more like the real implenentaion

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/inference/InferenceOperatorTestCase.java [hunk 2]
```diff
@@ -64,9 +74,14 @@ protected ThreadPool threadPool() {
         return threadPool;
     }
 
+    @Override
+    protected int largeInputSize() {
```
Comment (afoucret) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/inference/InferenceOperatorTestCase.java:78]: Set the size of large between 100 and 1000 which is more realistic for inference operation.
Veru big size like `10000` can create timeout that might make the CI flaky.

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java [hunk 3]
```diff
@@ -68,14 +69,22 @@ public abstract class OperatorTestCase extends AnyOperatorTestCase {
...
     /**
      * Test a larger input set against {@link #simple}.
      */
     public final void testSimpleLargeInput() {
-        assertSimple(driverContext(), between(1_000, 10_000));
+        assertSimple(driverContext(), largeInputSize());
+    }
+
+    protected int largeInputSize() {
+        return randomIntBetween(1_000, 10_000);
```
Comment (afoucret) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java:87]: Making size of small and large input configurable for operator tests. Kept the same default.

**Review by carlosdelest — APPROVED** [review]
LGTM

**Review by ioanatia — APPROVED** [review]
