### PR TITLE
ESQL: Fix count optimization with pushable union types

### LINKED ISSUE #127200: [ES|QL] Aggregation on conversion functions may return wrong results
It happens when the conversion functions reference multi/union typed fields that come from multiple indices, this happens to the other conversion functions too, not specific for `::date`, `::date_nanos`. Aggregation on single index with conversion functions work as expected.

Here are the steps to reproduce this issue.

```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test1" -XPUT -d '{
  "mappings": {
        "properties": {
          "millis": { "type": "date" },
          "nanos": { "type": "date_nanos"},
          "num": { "type": "long" }
        }
  }
}'

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test2" -XPUT -d '{
  "settings": {"index": {"mode": "lookup"}},
  "mappings": {
        "properties": {
          "millis": { "type": "date_nanos" },
          "nanos": { "type": "date"},
          "num": { "type": "long" }
        }
  }
}'

curl -X PUT "localhost:9200/test1/_bulk?refresh&pretty" -H 'Content-Type: application/json' -d'
{"index": {}}
{"millis":"2023-10-23T13:55:01.543Z","nanos":"2023-10-23T13:55:01.543123456Z","num":1698069301543123456}
{"index": {}}
{"millis":"2023-10-23T13:55:01.543Z","nanos":"2023-10-23T12:55:01.543123456Z","num":1698069301543123456}
{"index": {}}
{"millis":"1999-10-23T12:15:03.360Z","nanos":["2023-03-23T12:15:03.360103847Z", "2023-02-23T13:33:34.937193000Z", "2023-01-23T13:55:01.543123456Z"],"num":0}
'

curl -X PUT "localhost:9200/test2/_bulk?refresh&pretty" -H 'Content-Type: application/json' -d'
{"index": {}}
{"millis":"2023-10-23T13:55:01.543123456Z","nanos":"2023-10-23T13:55:01.543Z","num":1698069301543123456}
{"index": {}}
{"millis":"1999-10-23T12:15:03.360103847Z","nanos":["2023-03-23T12:15:03.360Z", "2023-02-23T13:33:34.937Z", "2023-01-23T13:55:01.543Z"],"num":0}
'

+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{ 
  "query": "from test* | stats count(millis::date)"
}
'
count(millis::date)
-------------------
0                  ===> WRONG RESULTS
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{ 
  "query": "from test* | stats count(millis::date_nanos)"
}
'
count(millis::date_nanos)
-------------------------
0                        ===> WRONG RESULTS
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from test1 | stats count(millis)"
}
'
 count(millis) 
---------------
3              
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from test1 | stats count(millis::date)"
}
'
count(millis::date)
-------------------
3                  
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from test1 | stats count(millis::date_nanos)"
}
'
count(millis::date_nanos)
-------------------------
3                        
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from test2 | stats count(millis)"
}
'
 count(millis) 
---------------
2              
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from test2 | stats count(millis::date)"
}
'
count(millis::date)
-------------------
2                  
+ curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "from test2 | stats count(millis::date_nanos)"
}
'
count(millis::date_nanos)
-------------------------
2   
```

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/127200

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -1038,7 +1038,13 @@ public enum Cap {
...
          * Support for the SAMPLE command
          */
-        SAMPLE(Build.current().isSnapshot());
+        SAMPLE(Build.current().isSnapshot()),
+
+        /**
+         * When pushing down {@code STATS count(field::type)} for a union type field, we wrongly used a synthetic attribute name in the
+         * query instead of the actual field name. This led to 0 counts instead of the correct result.
+         */
+        FIX_COUNT_PUSHDOWN_FOR_UNION_TYPES;
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:1047]: We should always add new capabilities near similar capabilities, or at least avoid adding them at the end, because the end maximizes merge conflicts.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java [hunk 2]
```diff
@@ -66,12 +66,12 @@ public LogicalPlan apply(LogicalPlan plan, LocalLogicalOptimizerContext localLog
...
         if (plan instanceof EsRelation relation) {
-            // Remove missing fields from the EsRelation because this is not where we will obtain them from; replace them by an Eval right
-            // after, instead. This allows us to safely re-use the attribute ids of the corresponding FieldAttributes.
+            // For any missing field, place an Eval right after the EsRelation to assign null values to that attribute (using the same name
+            // id!), thus avoiding that InsertFieldExtrations inserts a field extraction later.
             // This means that an EsRelation[field1, field2, field3] where field1 and field 3 are missing will be replaced by
             // Project[field1, field2, field3] <- keeps the ordering intact
             // \_Eval[field1 = null, field3 = null]
-            // \_EsRelation[field2]
+            // \_EsRelation[field1, field2, field3]
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java:74]: If the field is missing, would it be in the EsRelation at all?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java [hunk 3]
```diff
@@ -94,15 +94,19 @@ private Tuple<List<Attribute>, List<EsStatsQueryExec.Stat>> pushableStats(
                             // check if regular field
                             else {
                                 if (target instanceof FieldAttribute fa) {
-                                    var fName = fa.name();
+                                    var fName = fa.fieldName();
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:97]: Wow! Is this the fix? I imagine this could have impacts in many places, so could this fix other bugs we've not noticed?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java [hunk 4]
```diff
@@ -94,15 +94,19 @@ private Tuple<List<Attribute>, List<EsStatsQueryExec.Stat>> pushableStats(
...
                                     if (context.searchStats().isSingleValue(fName)) {
-                                        fieldName = fa.name();
+                                        fieldName = fName;
                                         query = QueryBuilders.existsQuery(fieldName);
                                     }
                                 }
                             }
                             if (fieldName != null) {
                                 if (count.hasFilter()) {
+                                    // Note: currently, it seems like we never actually perform stats pushdown if we reach here.
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:106]: It seems the question of what exactly gets pushed down and why is subtle. I wonder if we want some documentation on this?

**Review by craigtaverner — APPROVED** [review]
Interesting! I did not know the bug was about Lucene pushdown of STATS.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceMissingFieldWithNull.java:74]: Yes! Because we're in the local optimizer, the field _does_ exist overall, and thus is put into the EsRelation after the field caps call on the coordinator. But on the local node it's missing! (Or in the search stats that this optimization run uses, to be more precise) This optimizer rule applies exclusively to such fields.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:97]: Yep, this is the fix. Simple oversight to use the correct field name - in the past, the field _attribute_ name and the field name were the same, but union types had to break with this pattern.

I do not see other situations that this may fix, too, because the specific stats-pushdown optimization only triggers in a narrow slice of queries, anyway.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java (hunk 4 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:106]: > // Note: currently, it seems like we never actually perform stats pushdown if we reach here.

We evolved to this. Before the aggs filter were extracted into an upstream filter and pushed down, this code was "alive".

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:97]: What I'm wondering is if we could make this mistake again and if we could prevent it.
Also, should we insert filters here using `#fieldName()`?
https://github.com/elastic/elasticsearch/blob/9e0a5af898b0d78c48fb22e758ae59fe5a1c8266/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java#L58

**Comment by bpintea** [comment]
Oh, too late.

> Also, should we insert filters here using #fieldName()?

I will follow up on this.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java (hunk 4 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushStatsToSource.java:106]: Yep yep, and if we manage to evolve the optimization to multiple stats, this code could come alive again.

There's an argument to be made that it should be deleted as long as it's dead - but properly double checking that this code path _really is never ever used atm_ was beyond the scope that I could allocate to this bug fix.

So leaving a comment was the next best thing for the time being, I think  :)

**Comment by alex-spies** [comment]
@bpintea , your comment https://github.com/elastic/elasticsearch/pull/127225#discussion_r2063503255 is an excellent find. Dang, we missed another usage of `FieldName#name` where we really meant `#fieldName`.

Thank you for following up on this! Maybe let's also add a javadoc comment to `NamedExpression#name`, or more specifically `FieldAttribute#name` to warn against using the attribute name (which can be synthetic).

To remove the sharp edge, we could consider refactoring methods using the _actual field name_ to use an `EsField` object (each `FieldAttribute` has one!) rather than a `String` to ensure, at compile time, that we never hand them a bogus name accidentally. More specifically, `SearchStats`' methods should maybe not use `String` everywhere, but maybe `EsField` or a dedicated `String` wrapper record that we can call `FielName` or so, just to leverage the compiler.

**Comment by alex-spies** [comment]
> @bpintea , your comment [#127225 (comment)](https://github.com/elastic/elasticsearch/pull/127225#discussion_r2063503255) is an excellent find. Dang, we missed another usage of `FieldName#name` where we really meant `#fieldName`.
> 
> Thank you for following up on this! Maybe let's also add a javadoc comment to `NamedExpression#name`, or more specifically `FieldAttribute#name` to warn against using the attribute name (which can be synthetic).
> 
> To remove the sharp edge, we could consider refactoring methods using the _actual field name_ to use an `EsField` object (each `FieldAttribute` has one!) rather than a `String` to ensure, at compile time, that we never hand them a bogus name accidentally. More specifically, `SearchStats`' methods should maybe not use `String` everywhere, but maybe `EsField` or a dedicated `String` wrapper record that we can call `FielName` or so, just to leverage the compiler.

I think it's worth tracking this in an issue. Opened https://github.com/elastic/elasticsearch/issues/127521
