### PR TITLE
[ML] Fix Non-Deterministic Training Set Selection in RegressionIT testTwoJobsWithSameRandomizeSeedUseSameTrainingSet

### LINKED ISSUE #117805: [CI] RegressionIT testTwoJobsWithSameRandomizeSeedUseSameTrainingSet failing
**Build Scans:**
- [elasticsearch-intake #13833 / part4](https://gradle-enterprise.elastic.co/s/hqnne5mqkybqs)
- [elasticsearch-pull-request #44381 / part-4](https://gradle-enterprise.elastic.co/s/g3zh5t57xqz7g)
- [elasticsearch-intake #13802 / part4](https://gradle-enterprise.elastic.co/s/iugltqktba3mm)
- [elasticsearch-pull-request #44285 / part-4](https://gradle-enterprise.elastic.co/s/xwoj25fsnjfuw)
- [elasticsearch-periodic-platform-support #5158 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/7vgpkyazxk7xs)
- [elasticsearch-pull-request #44227 / part-4](https://gradle-enterprise.elastic.co/s/bmpdz6u5e4pik)
- [elasticsearch-pull-request #44095 / part-4](https://gradle-enterprise.elastic.co/s/wv6m5qicyabrg)
- [elasticsearch-pull-request #43922 / part-4](https://gradle-enterprise.elastic.co/s/hfhkncdtoceuu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testTwoJobsWithSameRandomizeSeedUseSameTrainingSet" -Dtests.seed=348CCC014CCA1893 -Dtests.locale=cs -Dtests.timezone=America/Paramaribo -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.RegressionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testTwoJobsWithSameRandomizeSeedUseSameTrainingSet),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <[_ZLPjpMBn0rHGrfq6put, HZLPjpMBn0rHGrfq6pyt, E5LPjpMBn0rHGrfq6pyt, G5LPjpMBn0rHGrfq6pyt, NJLPjpMBn0rHGrfq6pyt, FZLPjpMBn0rHGrfq6pyt, JZLPjpMBn0rHGrfq6pyt, BZLPjpMBn0rHGrfq6pyt, SpLPjpMBn0rHGrfq6pyt, K5LPjpMBn0rHGrfq6pyt, C5LPjpMBn0rHGrfq6pyt, I5LPjpMBn0rHGrfq6pyt, DpLPjpMBn0rHGrfq6pyt, DJLPjpMBn0rHGrfq6pyt, NpLPjpMBn0rHGrfq6pyt, OpLPjpMBn0rHGrfq6pyt, MpLPjpMBn0rHGrfq6pyt, GJLPjpMBn0rHGrfq6pyt, _JLPjpMBn0rHGrfq6put, AJLPjpMBn0rHGrfq6pyt, PpLPjpMBn0rHGrfq6pyt, QpLPjpMBn0rHGrfq6pyt, HJLPjpMBn0rHGrfq6pyt, RpLPjpMBn0rHGrfq6pyt, UJLPjpMBn0rHGrfq6pyt, JJLPjpMBn0rHGrfq6pyt, KJLPjpMBn0rHGrfq6pyt, RJLPjpMBn0rHGrfq6pyt, VJLPjpMBn0rHGrfq6pyt, F5LPjpMBn0rHGrfq6pyt, OJLPjpMBn0rHGrfq6pyt, _5LPjpMBn0rHGrfq6put, -5LPjpMBn0rHGrfq6put, XpLPjpMBn0rHGrfq6pyt, AZLPjpMBn0rHGrfq6pyt, J5LPjpMBn0rHGrfq6pyt, CZLPjpMBn0rHGrfq6pyt, L5LPjpMBn0rHGrfq6pyt, SZLPjpMBn0rHGrfq6pyt, TZLPjpMBn0rHGrfq6pyt, VZLPjpMBn0rHGrfq6pyt, O5LPjpMBn0rHGrfq6pyt, QZLPjpMBn0rHGrfq6pyt, R5LPjpMBn0rHGrfq6pyt, S5LPjpMBn0rHGrfq6pyt, V5LPjpMBn0rHGrfq6pyt, U5LPjpMBn0rHGrfq6pyt, OZLPjpMBn0rHGrfq6pyt, W5LPjpMBn0rHGrfq6pyt, XZLPjpMBn0rHGrfq6pyt]>
     but: was <[_ZLPjpMBn0rHGrfq6put, HZLPjpMBn0rHGrfq6pyt, E5LPjpMBn0rHGrfq6pyt, G5LPjpMBn0rHGrfq6pyt, FZLPjpMBn0rHGrfq6pyt, JZLPjpMBn0rHGrfq6pyt, BZLPjpMBn0rHGrfq6pyt, SpLPjpMBn0rHGrfq6pyt, K5LPjpMBn0rHGrfq6pyt, C5LPjpMBn0rHGrfq6pyt, I5LPjpMBn0rHGrfq6pyt, DpLPjpMBn0rHGrfq6pyt, DJLPjpMBn0rHGrfq6pyt, NpLPjpMBn0rHGrfq6pyt, OpLPjpMBn0rHGrfq6pyt, MpLPjpMBn0rHGrfq6pyt, GJLPjpMBn0rHGrfq6pyt, _JLPjpMBn0rHGrfq6put, AJLPjpMBn0rHGrfq6pyt, PpLPjpMBn0rHGrfq6pyt, QpLPjpMBn0rHGrfq6pyt, HJLPjpMBn0rHGrfq6pyt, RpLPjpMBn0rHGrfq6pyt, UJLPjpMBn0rHGrfq6pyt, JJLPjpMBn0rHGrfq6pyt, KJLPjpMBn0rHGrfq6pyt, RJLPjpMBn0rHGrfq6pyt, VJLPjpMBn0rHGrfq6pyt, F5LPjpMBn0rHGrfq6pyt, OJLPjpMBn0rHGrfq6pyt, -5LPjpMBn0rHGrfq6put, XpLPjpMBn0rHGrfq6pyt, GpLPjpMBn0rHGrfq6pyt, AZLPjpMBn0rHGrfq6pyt, J5LPjpMBn0rHGrfq6pyt, CZLPjpMBn0rHGrfq6pyt, L5LPjpMBn0rHGrfq6pyt, SZLPjpMBn0rHGrfq6pyt, TZLPjpMBn0rHGrfq6pyt, N5LPjpMBn0rHGrfq6pyt, VZLPjpMBn0rHGrfq6pyt, O5LPjpMBn0rHGrfq6pyt, QZLPjpMBn0rHGrfq6pyt, R5LPjpMBn0rHGrfq6pyt, S5LPjpMBn0rHGrfq6pyt, V5LPjpMBn0rHGrfq6pyt, U5LPjpMBn0rHGrfq6pyt, OZLPjpMBn0rHGrfq6pyt, W5LPjpMBn0rHGrfq6pyt, XZLPjpMBn0rHGrfq6pyt]>
```

**Issue Reasons:**
- [main] 8 failures in test testTwoJobsWithSameRandomizeSeedUseSameTrainingSet (1.3% fail rate in 605 executions)
- [main] 5 failures in step part-4 (2.2% fail rate in 223 executions)
- [main] 2 failures in step part4 (2.9% fail rate in 68 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (2.3% fail rate in 221 executions)
- [main] 2 failures in pipeline elasticsearch-intake (2.9% fail rate in 68 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by valeriy42**
The test `testTwoJobsWithSameRandomizeSeedUseSameTrainingSet` fails intermittently because documents may be processed in different orders during reindexing. Since we use an online reservoir sampling algorithm, this order actually matters. To ensure deterministic reindexing of the document sequence, both the number of shards and the number of segments must be 1. 

This PR fixes the test by creating the source index with only 1 segment. This ensures deterministic document order during reindexing, resulting in consistent ID assignments and training set selection when using the same seed.

Fixes [#117805](https://github.com/elastic/elasticsearch/issues/117805)

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java [hunk 1]
```diff
@@ -361,6 +361,9 @@ public void testStopAndRestart() throws Exception {
     public void testTwoJobsWithSameRandomizeSeedUseSameTrainingSet() throws Exception {
         String sourceIndex = "regression_two_jobs_with_same_randomize_seed_source";
         indexData(sourceIndex, 100, 0);
```
Comment (valeriy42) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:363]: `indexData` is calling directly `client().admin().indices().prepareCreate()`  instead of `prepareCreate()` of the test framework. This ensures that the index has always 1 shard.

However, it still can have multiple segments which then leads to non-deterministics order in which the reservoir sampling might get the documents. Hence, we need to fix both the shards and the segments to 1.

**Review by davidkyle — APPROVED** [review]
LGTM
