### PR TITLE
Handle ES internal assertion errors in IT test

### LINKED ISSUE #98435: [CI] BulkIntegrationIT testDeleteIndexWhileIndexing failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/oraopkwtuyble/tests/:server:internalClusterTest/org.elasticsearch.action.bulk.BulkIntegrationIT/testDeleteIndexWhileIndexing

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.bulk.BulkIntegrationIT.testDeleteIndexWhileIndexing" -Dtests.seed=8C8A69C029D945DF -Dtests.locale=et -Dtests.timezone=Europe/Vatican -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.bulk.BulkIntegrationIT&tests.test=testDeleteIndexWhileIndexing

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertFalse(Assert.java:64)
  at org.junit.Assert.assertFalse(Assert.java:74)
  at org.elasticsearch.action.bulk.BulkIntegrationIT.testDeleteIndexWhileIndexing(BulkIntegrationIT.java:186)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by volodk85**
Indexing test thread throws `AssertionError` which is not handled, so it escapes to main **test thread**
```
aug 14, 2023 10:39:19 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException |  
-- | --
  | WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s0][write][T#4],5,TGRP-BulkIntegrationIT] |  
  | java.lang.AssertionError: primary indexing unexpected in state [CLOSED] |  
  | at __randomizedtesting.SeedInfo.seed([8C8A69C029D945DF]:0) |  
  | at org.elasticsearch.index.shard.IndexShard.assertStartedForPrimaryIndexing(IndexShard.java:2204) |  
  | at org.elasticsearch.index.shard.IndexShard.ensureWriteAllowed(IndexShard.java:2184)
```
full test [log](https://gradle-enterprise.elastic.co/s/oraopkwtuyble/tests/task/:server:internalClusterTest/details/org.elasticsearch.action.bulk.BulkIntegrationIT/testDeleteIndexWhileIndexing?top-execution=1)

uncaught exception releases `thread.join` wait and **test thread** might be able to execute following `assertFalse` statement. Indexing thread might be technically alive by the time of `assertFalse` execution (e.g. due to jvm housekeeping so that thread status is not reported to OS in time thus **isAlive**  as native method still thinks that thread is ok)

```
            thread.join(ReplicationRequest.DEFAULT_TIMEOUT.millis() / 2);
            assertFalse(thread.isAlive());
```

Closes #98435

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I think this was merged in error: you should wait for a review before applying the `auto-merge` label (which does not itself wait for a review). I have reverted it in c445c35b4707e7362cb1d666ef5221ee56d25c64.

File: server/src/internalClusterTest/java/org/elasticsearch/action/bulk/BulkIntegrationIT.java [hunk 1]
```diff
@@ -172,6 +172,8 @@ public void testDeleteIndexWhileIndexing() throws Exception {
                         logger.info("--> index id={} seq_no={}", response.getId(), response.getSeqNo());
                     } catch (ElasticsearchException ignore) {
                         logger.info("--> fail to index id={}", id);
+                    } catch (AssertionError ignore) {
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/action/bulk/BulkIntegrationIT.java:175]: I don't think we should catch and ignore an `AssertionError` here. An `AssertionError` means the whole test failed.
