### PR TITLE
Fix testReadBlobWithReadTimeouts retries count

### LINKED ISSUE #139995: [CI] GoogleCloudStorageBlobContainerRetriesTests testReadBlobWithReadTimeouts failing
**Build Scans:**
- [elasticsearch-intake #32749 / part1](https://gradle-enterprise.elastic.co/s/cvd22ilpzk3hq)
- [elasticsearch-pull-request #111524 / part-1](https://gradle-enterprise.elastic.co/s/nbsyydyasp6ae)
- [elasticsearch-periodic #11608 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/l6eaceb7y2o3i)
- [elasticsearch-periodic-platform-support #11576 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/ti3ul3h5h75ay)

**Reproduction Line:**
```
./gradlew ":modules:repository-gcs:test" --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests.testReadBlobWithReadTimeouts" -Dtests.seed=5047CD02968308F4 -Dtests.locale=fr-MQ -Dtests.timezone=GMT -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReadBlobWithReadTimeouts'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <5>
     but: was <6>
```

**Issue Reasons:**
- [main] 4 failures in test testReadBlobWithReadTimeouts (0.9% fail rate in 433 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mhl-b**
Fix https://github.com/elastic/elasticsearch/issues/139995

`RetryingInputStream` allows more retries than maxRetry count configured for the blob store. If stream is able to read a meaningful amount of bytes (1% of read buffer size) a free retry is given to the stream that will not count into maxRetry.

Fixing test by counting extra retries from `RetryingInputStream`.

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java [hunk 1]
```diff
@@ -260,15 +264,19 @@ public void testReadBlobWithReadTimeouts() {
         assertThat(exception.getMessage().toLowerCase(Locale.ROOT), containsString("read timed out"));
         assertThat(exception.getCause(), instanceOf(SocketTimeoutException.class));
 
+        // RetryingInputStream allows more retries when stream able to read meaningful amount of bytes, typically 1% of bufferSize
+        // here we limit total number of bytes in incompleteContent to be less than meaningful amount
+        final int meaningfulProgressSize = (int) (bufferSize.getBytes() / 100L);
+        final byte[] bytesPerRetry = randomByteArrayOfLength(meaningfulProgressSize / maxRetries);
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java]: I don't understand the computation here. We need each attempt to deliver strictly fewer than `bufferSize.getBytes() / 100L` bytes to avoid it being considered "meaningful" but why also divide by `maxRetries`? Does the GCS SDK retry attempt to resume the download internally up to `maxRetries` times? If so, that's different from the S3 SDK behaviour, and I'd prefer we made that explicit.

Also if `maxRetries == 1` then sometimes this'll send exactly `bufferSize.getBytes() / 100L` which is large enough to be meaningful. It needs to be strictly less than this size.

Also, rather than hard-coding the meaningful size to be `bufferSize.getBytes() / 100L` let's delegate the calculation to the repository somehow. Note that GCS repositories don't allow any control over the buffer size, it's always `GoogleCloudStorageBlobStore.SDK_DEFAULT_CHUNK_SIZE` i.e. 16MiB regardless of our choice of `bufferSize` above.

**Review by DaveCTurner — DISMISSED** [review]

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java (hunk 1 above)
Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java]: > I don't understand the computation here. We need each attempt to deliver strictly fewer than bufferSize.getBytes() / 100L bytes to avoid it being considered "meaningful" but why also divide by maxRetries?

I misunderstood `currentStreamProgress`, thanks for pointing out. Now I see that we compare `offset` of the `RetryingInputStream` with current try `offset`. I missed part where we update current `offset` during stream read.

```java
    private long currentStreamProgress() {
        if (currentStream == null) {
            return 0L;
        }
        return Math.subtractExact(Math.addExact(start, offset), currentStream.getFirstOffset());
    }
```

> Does the GCS SDK retry attempt to resume the download internally up to maxRetries times?

It does not. GCS should be the same as S3 right now.

> Also if maxRetries == 1 then sometimes this'll send exactly bufferSize.getBytes() / 100L which is large enough to be meaningful. It needs to be strictly less than this size.

Not really, `exchange -> contentPartSizes.add((long) sendIncompleteContent(exchange, bytes))` does not send whole content, it's at least 1 byte short.

> Also, rather than hard-coding the meaningful size to be bufferSize.getBytes() / 100L let's delegate the calculation to the repository somehow.

Done. Exposed meaningful progress and added retry counting in test. https://github.com/elastic/elasticsearch/pull/139999/changes/d3857cd47b64ab7b2a5184ab4b9bf97346ffdc53

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java [hunk 2]
```diff
@@ -288,7 +304,10 @@ public void testReadBlobWithReadTimeouts() {
                 containsString("unexpected end of file from server")
             )
         );
-        assertThat(exception.getSuppressed().length, getMaxRetriesMatcher(maxRetries));
+        int meaningfulProgressRetries = Math.toIntExact(
+            contentPartSizes.stream().filter(partSize -> partSize >= meaningfulProgressSize.get()).count()
+        );
+        assertThat(exception.getSuppressed().length, getMaxRetriesMatcher(maxRetries + meaningfulProgressRetries));
```
Comment (nicktindall) [inline test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java]: I think `S3BlobContainerRetriesTest` works around this problem by overriding `getMaxRetriesMatcher`

See https://github.com/elastic/elasticsearch/blob/9fa3317d3d5908bc3cee2088b386ced2ebe6e94a/modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java#L1458-L1461

What you've done here seems like an improvement because it is more specific, perhaps we can remove that override and in-line `getMaxRetriesMatcher` as part of (or subsequent to) this change?

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java]: Cool, I missed that override. Will remove this from S3 tests and make it similar to GCP.

Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java]: Done https://github.com/elastic/elasticsearch/pull/139999/commits/830453654c4363d3344df108cec400218bc6fb5b. `getMaxRetriesMatcher` is still in use in other place, otherwise I could remove it.

**Comment by mhl-b** [comment]
@nicktindall, @DaveCTurner, ready for another review

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java [hunk 3]
```diff
@@ -267,21 +275,29 @@ public void testReadBlobWithReadTimeouts() {
...
+        // A list to track response sizes, some streams (i.e. RetryingInputStream) allow more retries when meaningful amount of bytes
+        // is transferred in a single try. See below.
+        final List<Long> retryContentSizes = Collections.synchronizedList(new ArrayList<>());
+
         // HTTP server sends a partial response
         final byte[] bytes = randomBlobContent();
         httpServer.createContext(
             downloadStorageEndpoint(blobContainer, "read_blob_incomplete"),
-            exchange -> sendIncompleteContent(exchange, bytes)
+            exchange -> retryContentSizes.add((long) sendIncompleteContent(exchange, bytes))
```
Comment (nicktindall) [inline test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java:286]: I wonder whether this might still flake, for example if the server thinks it sent a response > meaningful progress size, but due to buffering etc in the client infrastructure (they are all different I think), we might end up seeing < meaningful progress size in the client.

Assuming it doesn't, this LGTM

**Review by nicktindall — APPROVED** [review]
LGTM with comment

File: test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java (hunk 3 above)
Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java:286]: I ran several successful tests with exact response size of meaningful bytes. I would expect client should not sit on buffered data and not giving it to the application. But can prefetch more if it's available. In this case what fixtures flushes to the socket should be immediately visible to the client.

**Review by DaveCTurner — APPROVED** [review]
LGTM2

**Comment by mhl-b** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/141690)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
