### PR TITLE
Test ML model server

### LINKED ISSUE #113950: [CI] TextEmbeddingCrudIT testPutE5Small_withPlatformSpecificVariant failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5709 / opensuse-leap-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/i2yir4wcazdgk)
- [elasticsearch-periodic #5705 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ayc4xwjsnvhcc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:qa:inference-service-tests:javaRestTest" --tests "org.elasticsearch.xpack.inference.TextEmbeddingCrudIT.testPutE5Small_withPlatformSpecificVariant" -Dtests.seed=B4FDC9C1594B3DFF -Dtests.locale=ff-SN -Dtests.timezone=Africa/Freetown -Druntime.java=23
```

**Applicable branches:**
8.16

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.TextEmbeddingCrudIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testPutE5Small_withPlatformSpecificVariant),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:42325], URI [_inference/text_embedding/teste5mall_withplatformspecificvariant], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"status_exception","reason":"Model importing failed due to an IOException [java.net.SocketException: Connection reset]"}],"type":"status_exception","reason":"Model importing failed due to an IOException [java.net.SocketException: Connection reset]","caused_by":{"type":"socket_exception","reason":"Connection reset"}},"status":503}
```

**Issue Reasons:**
- [8.16] 2 failures in test testPutE5Small_withPlatformSpecificVariant (4.4% fail rate in 45 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jan-elastic**
Some integration tests attempt to download ML models of >100MB from [ml-models.elastic.co](https://ml-models.elastic.co). This may fail for various reasons, leading to these tests being muted.

In order to fix this, this PR spins up a simple HTTP server on localhost, which serves tiny versions of these models, and uses that server in the integration tests.

In the process, two bugs are also fixed:
- downloading models that are smaller than a few MB
- dynamically changing the model repo URL

Closes: #113950 #113983 #114023 #114239 #114913 #115361 #116140 #116142

### CODE REVIEW

**Review by wwang500 — COMMENTED** [review]
Code looks good, but I will let Dave give the final LGTM as my knowledge about integration test is limited here.

Just one question:
- are those unmuted integration tests only running in locally, right? If those tests will run against a remote cluster, like in MKI or ECH, they will fail I guess.

**Comment by jan-elastic** [comment]
> are those unmuted integration tests only running in locally, right? If those tests will run against a remote cluster, like in MKI or ECH, they will fail I guess.

Yes, this is running locally or on Bulidkite, not vs remote clusters etc.

File: x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/InferenceBaseRestTest.java [hunk 1]
```diff
@@ -51,6 +53,22 @@ public class InferenceBaseRestTest extends ESRestTestCase {
         .feature(FeatureFlag.INFERENCE_UNIFIED_API_ENABLED)
         .build();
 
+    @ClassRule
+    public static MlModelServer mlModelServer = new MlModelServer();
+
+    @Before
+    public void setMlModelRepository() throws IOException {
+        logger.info("setting ML model repository");
```
Comment (davidkyle) [inline x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/InferenceBaseRestTest.java:61]:
```suggestion
        logger.info("setting ML model repository to " + mlModelServer.getUrl());
```

File: x-pack/plugin/ml-package-loader/src/main/java/org/elasticsearch/xpack/ml/packageloader/action/ModelLoaderUtils.java [hunk 2]
```diff
@@ -342,14 +342,17 @@ static InputStream getFileInputStream(URI uri) {
...
+     * Less ranges may be returned in case the stream size is too small.
      * @param sizeInBytes The total size of the stream
      * @param numberOfStreams Divide the bulk of the size into this many streams.
      * @param chunkSizeBytes The size of each chunk
      * @return List of {@code numberOfStreams} + 1 ranges.
      */
     static List<RequestRange> split(long sizeInBytes, int numberOfStreams, long chunkSizeBytes) {
         int numberOfChunks = (int) ((sizeInBytes + chunkSizeBytes - 1) / chunkSizeBytes);
-
+        if (numberOfStreams > numberOfChunks) {
```
Comment (davidkyle) [inline x-pack/plugin/ml-package-loader/src/main/java/org/elasticsearch/xpack/ml/packageloader/action/ModelLoaderUtils.java:353]: 👍

**Review by davidkyle — APPROVED** [review]
LGTM
