### PR TITLE
Script: Always dup new objects

### LINKED ISSUE #70478: Scripting compile error on object creation without corresponding read
If an object is created but not read from (due to being stored or used), painless will throw a compile error in the ASM phase.  For example:
`"int i = 1; new ArrayList(); return i;"`  the new `ArrayList();` is not used.  Normally object construction would leave an item on the operand stack, which we'd pop at the end of the statement.  That is only the case when the result of new object construction is read.

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at org.objectweb.asm.Frame.merge(Frame.java:1268)
	at org.objectweb.asm.Frame.merge(Frame.java:1244)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.commons.GeneratorAdapter.endMethod(GeneratorAdapter.java:1347)
	at org.elasticsearch.painless.MethodWriter.endMethod(MethodWriter.java:461)
	at org.elasticsearch.painless.phase.DefaultIRTreeToASMBytesPhase.visitFunction(DefaultIRTreeToASMBytesPhase.java:307)
```

### PR DESCRIPTION
**Pull request by stu-elastic**
If a new object is created, always `dup` the result
of `new` so that when we `pop` at the end of the statement, there's always
something to `pop`.

Fixes: #70478

### CODE REVIEW

File: modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultSemanticAnalysisPhase.java [hunk 1]
```diff
@@ -1654,6 +1654,12 @@ public void visitNewObj(ENewObj userNewObjNode, SemanticScope semanticScope) {
                             "[" + canonicalTypeName + "/" + userArgumentsSize + "]"));
         }
 
+        if (semanticScope.getCondition(userNewObjNode, Read.class) == false) {
```
Comment (jdconrad) [inline modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultSemanticAnalysisPhase.java:1657]: This isn't backwards compatible. I've added this issue (https://github.com/elastic/elasticsearch/issues/70505) where we will need to come up with a way to remove semantics that don't make sense any longer. Please remove this for now so we don't break anyone unintentionally during upgrade to 7.10+.

**Review by jdconrad — APPROVED** [review]
LGTM. Thanks for the quick fix! One important comment to address.

File: modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultSemanticAnalysisPhase.java (hunk 1 above)
Comment (stu-elastic) [reply modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultSemanticAnalysisPhase.java:1657]: I understand.  However, it was broken before, so the only the changes is the error message.

Comment (jdconrad) [reply modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultSemanticAnalysisPhase.java:1657]: I still worry about customers on versions prior to 7.10 (where we last backported the recent refactorings to along with the bug). It's likely not very many, but given the complexity of upgrade and those types of issues I would prefer to avoid it if at all possible.

Comment (stu-elastic) [reply modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultSemanticAnalysisPhase.java]: Totally makes sense.

**Comment by stu-elastic** [comment]
master: d599adc
7.x (7.13.0): 7d0f8f5
