### PR TITLE
GEO: More robust handling of ignore_malformed in geoshape parsing

### LINKED ISSUE #34047: geo_shapes stopped indexing in 6.4.1
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: []

**JVM version** (`java -version`): official Docker image

**OS version** (`uname -a` if on a Unix-like system): official Docker image

**Description of the problem including expected versus actual behavior**:

After upgrading from 6.3.2 to 6.4.1, many `geo_shape`s stopped importing.

**Steps to reproduce**:

 1. Index has a field defined like this (FOSElastica bundle YML configuration):
```
    shape:
        type: 'geo_shape'
        tree: 'quadtree'
        precision: '10m'
        distance_error_pct: 0.001
```
 2. Indexing many shapes in 6.4.1 that worked in 6.3.2 results in `caused failed to parse` error.
 3. Adding `ignore_malformed: true` doesn't seem to help.

It looks like there was some sort of undocumented BC break regardless of the shapes being fully proper. If you want I can provide you an example of a shape.

### PR DESCRIPTION
**Pull request by imotov**
Adds a method to XContent parser to skip all children of a current
element in case of the parsing failure and applies this method to be
able to ignore the rest of the GeoJson shape if the parsing fails and
we need to ignore the geoshape due to the ignore malformed flag.

Supersedes #34498

Closes #34047

### CODE REVIEW

**Comment by imotov** [comment]
@nik, github suggested you, but if you think somebody else is in a better position to review the XContentParser portion, please feel free to reassign.

**Comment by jpountz** [comment]
I like the idea but at the same time I'd like to avoid adding more methods to XContentParser. I'm wondering whether we could do something similar with a wrapper instead that would count levels similarly to what you are doing in your Mark impl?

**Comment by imotov** [comment]
@jpountz that sounds like a great idea! Let me try that.

File: libs/x-content/src/main/java/org/elasticsearch/common/xcontent/XContentSubParser.java [hunk 1]
```diff
@@ -0,0 +1,280 @@
...
+    }
+
+    @Override
+    public NamedXContentRegistry getXContentRegistry() {
+        return parser.getXContentRegistry();
+    }
+
+    @Override
+    public boolean isClosed() {
+        return parser.isClosed();
```
Comment (jpountz) [inline libs/x-content/src/main/java/org/elasticsearch/common/xcontent/XContentSubParser.java]: I'm wondering whether the fact that this would still return `false` after `close` has been called could be confusing.

**Review by jpountz — APPROVED** [review]
This looks great, I just left a question.

File: libs/x-content/src/main/java/org/elasticsearch/common/xcontent/XContentSubParser.java (hunk 1 above)
Comment (imotov) [reply libs/x-content/src/main/java/org/elasticsearch/common/xcontent/XContentSubParser.java]: Indeed! I missed this one. Good catch! I will fix that.
