### PR TITLE
SQL: use a proper error message for queries directed at empty mapping indices

### LINKED ISSUE #52865: SQL: Unknown index verification exception when index does not contain any mappings
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.0 on ESS

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a new index, only supplying index settings
 2. Execute a SQL query against the index

Expected: 
An unknown column verification exception, or a specific exception for this edge-case. 

Actual: 
An Unknown index verification exception. This is misleading, making debugging for the user more difficult. 
```
{
        "type" : "verification_exception",
        "reason" : "Found 1 problem(s)\nline 1:15: Unknown index [broken]"
}
```

Full repro:

```
PUT broken
{ 
  "settings": {
    "index": {
        "final_pipeline": "a"
    }
  }
}

PUT working
{
  "mappings": {
    "properties": {
      "for": {
        "type": "keyword"
      }
    }
  }, 
  "settings": {
      "index": {
          "final_pipeline": "a"
      }
  }
}

GET _sql // FAILS
{
  "query": "SELECT * FROM broken"
}

GET _sql
{
  "query": "SELECT * FROM working"
}
```

### PR DESCRIPTION
**Pull request by astefan**
Until now, when a query was executed against an index that had no mapping a misleading "index not found" error message was issued. This PR fixes this error message by pointing out the columns not being found instead.

Fixes https://github.com/elastic/elasticsearch/issues/52865.

### CODE REVIEW

**Review by matriv — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
Nice one!

File: x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/cli/ErrorsTestCase.java [hunk 1]
```diff
@@ -37,15 +37,30 @@ public void testSelectFromMissingIndex() throws IOException {
...
+    public void testSelectFromEmptyIndex() throws Exception {
         // Create an index without any types
         Request request = new Request("PUT", "/test");
         request.setJsonEntity("{}");
         client().performRequest(request);
 
         assertFoundOneProblem(command("SELECT * FROM test"));
-        //assertEquals("line 1:15: [test] doesn't have any types so it is incompatible with sql" + END, readLine());
-        assertEquals("line 1:15: Unknown index [test]" + END, readLine());
+        assertEquals("line 1:8: Cannot determine columns for [*]" + END, readLine());
```
Comment (costin) [inline x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/cli/ErrorsTestCase.java]: I think this is incorrect - if we know the index is empty, we should return no columns since we can determine them and know there are none.

Comment (astefan) [reply x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/cli/ErrorsTestCase.java]: Created https://github.com/elastic/elasticsearch/issues/53001
