### PR TITLE
Fix timeout in FeatureMigrationIT race-condition test

### LINKED ISSUE #147438: [CI] FeatureMigrationIT testStartMigrationAndImmediatelyCheckStatus failing
**Build Scans:**
- [elasticsearch-intake #38358 / part2](https://gradle-enterprise.elastic.co/s/pm75zkozdlnlm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:migrate:internalClusterTest" --tests "org.elasticsearch.system_indices.action.FeatureMigrationIT.testStartMigrationAndImmediatelyCheckStatus" -Dtests.seed=707D16440FEDD8D3 -Dtests.locale=gu -Dtests.timezone=Asia/Chita -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.system_indices.action.FeatureMigrationIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testStartMigrationAndImmediatelyCheckStatus'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <NO_MIGRATION_NEEDED>
     but: was <IN_PROGRESS>
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testStartMigrationAndImmediatelyCheckStatus
- [main] 1 consecutive failures in step part2
- [main] 1 consecutive failures in pipeline elasticsearch-intake

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mark-vieira**
## Summary
- `testStartMigrationAndImmediatelyCheckStatus` used the default 10-second `assertBusy` while waiting for the migration to reach `NO_MIGRATION_NEEDED`. Under parallel CI load the feature migration routinely takes longer than 10s, causing the assertion to time out with the migration still legitimately `IN_PROGRESS`.
- The sibling `executeMigration` helper in `AbstractFeatureMigrationIntegTest` already uses a 30-second timeout with an explicit comment noting this same concern. Matched it here and unmuted the test.

Root cause confirmed from the CI build scan logs ([pm75zkozdlnlm](https://gradle-enterprise.elastic.co/s/pm75zkozdlnlm)): the migration was still making forward progress (creating reindexed system indices) when the 10s timeout expired. This is not the race condition the test was originally written for — that fix in `TransportGetFeatureUpgradeStatusAction` is intact.

Closes #147438

## Test plan
- [x] Local run of the failing reproduction seed passes: `./gradlew :x-pack:plugin:migrate:internalClusterTest --tests "org.elasticsearch.system_indices.action.FeatureMigrationIT.testStartMigrationAndImmediatelyCheckStatus" -Dtests.seed=707D16440FEDD8D3 -Dtests.locale=gu -Dtests.timezone=Asia/Chita`
- [x] CI green

### CODE REVIEW

File: x-pack/plugin/migrate/src/internalClusterTest/java/org/elasticsearch/system_indices/action/FeatureMigrationIT.java [hunk 1]
```diff
@@ -124,12 +124,13 @@ public void testStartMigrationAndImmediatelyCheckStatus() throws Exception {
...
 
-        // Now wait for the migration to finish (otherwise the test infra explodes)
+        // Now wait for the migration to finish (otherwise the test infra explodes). The feature upgrade may take longer than ten
+        // seconds when tests are running in parallel, so we give assertBusy a thirty-second timeout.
         assertBusy(() -> {
             GetFeatureUpgradeStatusResponse statusResp = client().execute(GetFeatureUpgradeStatusAction.INSTANCE, getStatusRequest).get();
             logger.info(Strings.toString(statusResp));
             assertThat(statusResp.getUpgradeStatus(), equalTo(GetFeatureUpgradeStatusResponse.UpgradeStatus.NO_MIGRATION_NEEDED));
-        });
+        }, 30, TimeUnit.SECONDS);
```
Comment (prdoyle) [inline x-pack/plugin/migrate/src/internalClusterTest/java/org/elasticsearch/system_indices/action/FeatureMigrationIT.java:133]: Seems like a rather slim upgrade, given that 10 seconds is already known to be insufficient. Did you consider something like 100 seconds?

**Review by prdoyle — APPROVED** [review]
Optional comment. Looks pretty straightforward.

File: x-pack/plugin/migrate/src/internalClusterTest/java/org/elasticsearch/system_indices/action/FeatureMigrationIT.java (hunk 1 above)
Comment (mark-vieira) [reply x-pack/plugin/migrate/src/internalClusterTest/java/org/elasticsearch/system_indices/action/FeatureMigrationIT.java:133]: Given we use 30 seconds elsewhere this seemed reasonable. I mean, if it passes 99% of the time with on 10 seconds, a 3x timeout bump feels like enough.

**Comment by mark-vieira** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/147474)|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/147475)|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/147476)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
