### PR TITLE
Avoid circular reference in exception

### LINKED ISSUE #15941: Circular reference in Exception when checkpoint writing fails
We can end up with a circular reference in an Exception A, which has as suppressed Exception B which has as cause A again if an Exception is thrown in the try block of `Translog.ensureSynced()` (Translog.java#L562).

This is easy to see if you pick https://github.com/brwe/elasticsearch/commit/bb108994d9b4929481f2f74b3e01bc8c0f756b18 and run the `TranslogTests`.

The way this happens is so:

1. We call `Translog.ensureSynced()` but unfortunately when `TranslogWriter.sync()` is called (via `current.syncUpTo()`) the writing of the checkpoint fails (TranslogWriter.java#L151) with Exception A. This causes `TranslogWriter.tragedy` to be set to Exception A before it is thrown (`TranslogWriter.closeWithTragicEvent()`). 

2. Because of Exception A we now get to the catch clause in `Translog.ensureSynced()`  where we call `Translog.closeOnTragicEvent()`  and pass as parameter the Exception A _that we just set as tragic exception_  (`TranslogWriter.tragedy`).

3. In `Translog.closeOnTragicEvent()` we call `close()` but that will fail too because we closed the translog already before (because of the tragic event A). We will get Exception B which is an `AlreadyClosedException` with cause `TranslogWriter.tragedy` (Exception A). (It is created in `TranslogWriter.ensureOpen()`). 

4. Because of Exception B now we get to the catch clause of `Translog.closeOnTragicEvent()` and have
 - `inner` Exception B, the `AlreadyClosedException` with cause `TranslogWriter.tragedy` (Exception A)
 - method parameter Exception (`ex`)  which is  `TranslogWriter.tragedy` (Exception A)

We the set B as suppressed Exception for the parameter exception A and therefore end up with a circular reference A that has suppressed B that has cause A.

As a result, when we try to serialize this, we get a stackoverflow.

This can be seen also in this build failure: http://build-us-00.elastic.co/job/es_core_21_metal/326/

If this explanation is too confusing let me know.

### PR DESCRIPTION
**Pull request by brwe**
Don't set the suppressed Exception in Translog.closeOnTragicEvent(Exception ex) if it is an
AlreadyClosedException. ACE is thrown by the TranslogWriter and as cause might
contain the Exception that we add the suppressed ACE to. We then end up with a
circular reference where Exception A has a suppressed Exception B that has as cause A.
This would cause a stackoverflow when we try to serialize it.
For a more detailed description see #15941

closes #15941

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/translog/Translog.java [hunk 1]
```diff
@@ -576,8 +576,12 @@ private void closeOnTragicEvent(Throwable ex) {
         if (current.getTragicException() != null) {
             try {
                 close();
+            } catch (AlreadyClosedException inner) {
+                // don't do anything in this case. The AlreadyClosedException comes from TranslogWriter and we should not add it as suppressed because
+                // will contain the Exception ex as cause. See also https://github.com/elastic/elasticsearch/issues/15941
             } catch (Exception inner) {
                 ex.addSuppressed(inner);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/translog/Translog.java]: maybe assert before we add?

**Comment by s1monw** [comment]
LGTM - left a minor one
