### PR TITLE
Release buffers in netty test

### LINKED ISSUE #126743: [CI] NettyAllocatorTests testTrashingCompositeByteBuf failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7665 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/5gqoagw3hmtvo)
- [elasticsearch-periodic-platform-support #7665 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/hw3grfcivgy3g)
- [elasticsearch-periodic-platform-support #7665 / ubuntu-2004-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/bx47kd7cwloa2)
- [elasticsearch-periodic-platform-support #7665 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/ub7pao6lhjcw6)
- [elasticsearch-periodic #7643 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/urozbnoederjy)
- [elasticsearch-periodic-platform-support #7665 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/anedjtnrojrn4)
- [elasticsearch-periodic #7643 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/5vucarsvee2eo)
- [elasticsearch-periodic-platform-support #7665 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/iobuvt3hnybpa)
- [elasticsearch-periodic-platform-support #7665 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/352j72sieokmc)
- [elasticsearch-periodic #7643 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ndiukjlxddjm6)

**Reproduction Line:**
```
./gradlew ":modules:transport-netty4:test" --tests "org.elasticsearch.transport.netty4.NettyAllocatorTests.testTrashingCompositeByteBuf" -Dtests.seed=F9DB0131CB3A5A26 -Dtests.locale=ce-RU -Dtests.timezone=America/Argentina/La_Rioja -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.transport.netty4.NettyAllocatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testTrashingCompositeByteBuf),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	Hint: Caller of readInbound() will handle the message from this point
	io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.touch(AdvancedLeakAwareCompositeByteBuf.java:36)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.touch(HttpObjectAggregator.java:366)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:445)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:396)
	io.netty.channel.embedded.EmbeddedChannel.readInbound(EmbeddedChannel.java:314)
	org.elasticsearch.http.netty4.Netty4HttpHeaderValidatorTests.testWithFlowControlAndAggregator(Netty4HttpHeaderValidatorTests.java:160)
	java.base/jdk.internal.ref
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step ubuntu-2404-aarch64_checkpart1_platform-support-arm
- [main] 5 consecutive failures in step amazonlinux-2023_platform-support-aws
- [main] 2 consecutive failures in step ubuntu-2404_platform-support-unix
- [main] 7 consecutive failures in step oraclelinux-9_platform-support-unix
- [main] 4 consecutive failures in step single-processor-node-tests
- [main] 4 consecutive failures in step rocky-9_platform-support-unix
- [main] 85 failures in test testTrashingCompositeByteBuf (17.4% fail rate in 489 executions)
- [main] 6 failures in step ubuntu-2404-aarch64_checkpart1_platform-support-arm (75.0% fail rate in 8 executions)
- [main] 3 failures in step almalinux-8-aarch64_checkpart1_platform-support-arm (37.5% fail rate in 8 executions)
- [main] 6 failures in step ubuntu-2004-aarch64_checkpart1_platform-support-arm (75.0% fail rate in 8 executions)
- [main] 6 failures in step amazonlinux-2023_platform-support-aws (85.7% fail rate in 7 executions)
- [main] 3 failures in step encryption-at-rest (37.5% fail rate in 8 executions)
- [main] 4 failures in step ubuntu-2404_platform-support-unix (50.0% fail rate in 8 executions)
- [main] 5 failures in step concurrent-search-tests (62.5% fail rate in 8 executions)
- [main] 6 failures in step rhel-8_platform-support-unix (75.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126745: [CI] Netty4HttpServerTransportTests testRespondAfterServiceCloseWithServerCancel failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7630 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/qykuzadststck)
- [elasticsearch-periodic-platform-support #7623 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/nvbbhu443ji7q)
- [elasticsearch-periodic-platform-support #7616 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/dp27eo7rsk2l2)

**Reproduction Line:**
```
gradlew ":modules:transport-netty4:test" --tests "org.elasticsearch.http.netty4.Netty4HttpServerTransportTests.testRespondAfterServiceCloseWithServerCancel" -Dtests.seed=9C479E395E212B79 -Dtests.locale=fur-Latn-IT -Dtests.timezone=SystemV/CST6CDT -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.http.netty4.Netty4HttpServerTransportTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRespondAfterServiceCloseWithServerCancel),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	Hint: Caller of readInbound() will handle the message from this point
	io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.touch(AdvancedLeakAwareCompositeByteBuf.java:36)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.touch(HttpObjectAggregator.java:366)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:445)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:396)
	io.netty.channel.embedded.EmbeddedChannel.readInbound(EmbeddedChannel.java:314)
	org.elasticsearch.http.netty4.Netty4HttpHeaderValidatorTests.testWithFlowControlAndAggregator(Netty4HttpHeaderValidatorTests.java:160)
	java.base/jdk.
[truncated]
```

**Issue Reasons:**
- [main] 3 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [main] 3 failures in test testRespondAfterServiceCloseWithServerCancel (1.5% fail rate in 194 executions)
- [main] 3 failures in step windows-2022_checkpart1_platform-support-windows (75.0% fail rate in 4 executions)
- [main] 3 failures in pipeline elasticsearch-periodic-platform-support (75.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126749: [CI] Netty4HttpServerTransportTests testRespondAfterServiceCloseWithClientCancel failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7658 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/nwcmq4skqobo6)
- [elasticsearch-periodic-platform-support #7644 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bv3h4gozybn7i)
- [elasticsearch-gradle-cache-validation #115 / checkpart1_configuration_caching_validation](https://gradle-enterprise.elastic.co/s/f3upeims5x2ae)

**Reproduction Line:**
```
gradlew ":modules:transport-netty4:test" --tests "org.elasticsearch.http.netty4.Netty4HttpServerTransportTests.testRespondAfterServiceCloseWithClientCancel" -Dtests.seed=778FBDA0BE9F26AB -Dtests.locale=es-CL -Dtests.timezone=Europe/Monaco -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.http.netty4.Netty4HttpServerTransportTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRespondAfterServiceCloseWithClientCancel),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	Hint: Caller of readInbound() will handle the message from this point
	io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.touch(AdvancedLeakAwareCompositeByteBuf.java:36)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.touch(HttpObjectAggregator.java:366)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:445)
	io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:396)
	io.netty.channel.embedded.EmbeddedChannel.readInbound(EmbeddedChannel.java:314)
	org.elasticsearch.http.netty4.Netty4HttpHeaderValidatorTests.testWithFlowControlAndAggregator(Netty4HttpHeaderValidatorTests.java:160)
	java.base/jdk.
[truncated]
```

**Issue Reasons:**
- [main] 3 failures in test testRespondAfterServiceCloseWithClientCancel (1.0% fail rate in 286 executions)
- [main] 2 failures in step windows-2022_checkpart1_platform-support-windows (33.3% fail rate in 6 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (33.3% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mhl-b**
Release leaking buffers in Netty4HttpHeaderValidatorTests. 

Closes #126743
Closes #126745
Closes #126749

### CODE REVIEW

File: modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpHeaderValidatorTests.java [hunk 1]
```diff
@@ -138,7 +140,10 @@ public void testIgnoreReadWhenValidating() {
         assertNull("content should not pass yet, need explicit read", channel.readInbound());
 
         channel.read();
-        assertTrue(channel.readInbound() instanceof LastHttpContent);
+        var lastContent = channel.readInbound();
+        assertTrue(lastContent instanceof LastHttpContent);
+        ((LastHttpContent) lastContent).release();
+
```
Comment (DaveCTurner) [inline modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpHeaderValidatorTests.java:146]: Or, in one line (with slightly nicer failure message too):

```suggestion
        asInstanceOf(LastHttpContent.class, channel.readInbound()).release();
```

File: modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpHeaderValidatorTests.java [hunk 2]
```diff
@@ -157,9 +162,10 @@ public void testWithFlowControlAndAggregator() {
         validationRequest.listener.onResponse(null);
         channel.runPendingTasks();
 
-        assertTrue(channel.readInbound() instanceof FullHttpRequest);
+        var fullReq = channel.readInbound();
+        assertTrue(fullReq instanceof FullHttpRequest);
+        ((FullHttpRequest) fullReq).release();
```
Comment (DaveCTurner) [inline modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpHeaderValidatorTests.java:167]: Likewise

```suggestion
        asInstanceOf(FullHttpRequest.class, channel.readInbound()).release();
```

**Review by DaveCTurner — APPROVED** [review]
LGTM with optional suggestions
