### PR TITLE
EQL: Fix bug in sequences with any pattern

### LINKED ISSUE #62967: EQL : Sequences Not Working Using the Any Operator
**Elasticsearch version** (`7.9.2`): reproduces on kibana.siem.estc.dev

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

Sequences are not working when the `any` operator is used.

**Steps to reproduce**:

These example queries return errors:

```
GET .siem-signals-siem-estc-dev-default-000001/_eql/search
{
  "query": """
   sequence by host.name
  [ any where true]
  [ any where true]
  """
}
GET .siem-signals-siem-estc-dev-default-000001/_eql/search
{
  "query": """
   sequence by host.name
  [ any where signal.rule.name == "f"]
  [ any where signal.rule.name == "hosts"]
  """
}

GET .siem-signals-siem-estc-dev-default-000001/_eql/search
{
  "query": """
   sequence
  [ any where signal.rule.name == "hosts"] by host.name
  [ any where signal.rule.name == "f"] by host.name
  """
}

```

### PR DESCRIPTION
**Pull request by costin**
Fix query creation inside sequences with any queries due to lacking a
clause to combine, which lead to an invalid request being created.

Fix #62967

### CODE REVIEW

File: x-pack/plugin/eql/qa/common/src/main/java/org/elasticsearch/test/eql/DataLoader.java [hunk 1]
```diff
@@ -130,6 +134,10 @@ private static String readMapping(URL resource) throws IOException {
         }
     }
 
+    private static CharSequence randomOf(String...values) {
+        return main ? values[0] : ESRestTestCase.randomFrom(values);
+    }
+
```
Comment (costin) [inline x-pack/plugin/eql/qa/common/src/main/java/org/elasticsearch/test/eql/DataLoader.java:140]: I've sneaked this in since it affects running DataLoader#main instead of from a test.

File: x-pack/plugin/eql/qa/common/src/main/java/org/elasticsearch/test/eql/EqlExtraSpecTestCase.java [hunk 2]
```diff
@@ -23,4 +23,9 @@
     public EqlExtraSpecTestCase(String query, String name, long[] eventIds, boolean caseSensitive) {
         super(TEST_EXTRA_INDEX, query, name, eventIds, caseSensitive);
     }
+
+    @Override
+    protected String sequenceField() {
+        return "sequence";
+    }
```
Comment (costin) [inline x-pack/plugin/eql/qa/common/src/main/java/org/elasticsearch/test/eql/EqlExtraSpecTestCase.java:30]: Moved this to the base class.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/assembler/BoxedQueryRequest.java [hunk 3]
```diff
@@ -46,8 +44,13 @@ public BoxedQueryRequest(QueryRequest original, String timestamp, String tiebrea
...
         }
-        // add ranges to existing query
-        searchSource.query(filter.must(searchSource.query()));
+
+        searchSource = original.searchSource();
+        // combine with existing query (if it exists)
+        if (searchSource.query() != null) {
+            filter = filter.must(searchSource.query());
+        }
+        searchSource.query(filter);
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/assembler/BoxedQueryRequest.java:53]: The actual cause of the exception

**Review by astefan — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM
