### PR TITLE
Fixes CORS handling so that it uses the defaults

### LINKED ISSUE #19520: Cors Access-Request-Control-Headers ignoring defaults
According to the docs, the `http.cors.allow-methods` setting should default to `OPTIONS,HEAD,GET,POST,PUT,DELETE`, but it appears to default to no methods at all.

With the default settings:

    curl -H 'Origin: http://localhost:8000' -H 'Access-Control-Request-Method: PUT' -i -X OPTIONS localhost:9200/t/t/1 -d{}

returns:

    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: http://localhost:8000
    Vary: Origin
    Access-Control-Max-Age: 1728000
    date: Wed, 20 Jul 2016 14:37:09 GMT
    content-length: 0

If I set `http.cors.allow-methods` to `OPTIONS,HEAD,GET,POST,PUT,DELETE`, it returns:

    HTTP/1.1 200 OK
    Access-Control-Allow-Origin: http://localhost:8000
    Vary: Origin
    Access-Control-Allow-Methods: HEAD
    Access-Control-Allow-Methods: DELETE
    Access-Control-Allow-Methods: POST
    Access-Control-Allow-Methods: GET
    Access-Control-Allow-Methods: OPTIONS
    Access-Control-Allow-Methods: PUT
    Access-Control-Max-Age: 1728000
    date: Wed, 20 Jul 2016 14:38:18 GMT
    content-length: 0

### PR DESCRIPTION
**Pull request by abeyad**
Fixes CORS handling so that it uses the defaults for  for http.cors.allow-methods
and http.cors.allow-headers if none are specified in the config.

Closes #19520

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/Strings.java [hunk 1]
```diff
@@ -501,15 +502,35 @@ public static String cleanPath(String path) {
...
+        return splitStringToSet(s, ',', false);
     }
 
     public static String[] splitStringByCommaToArray(final String s) {
         if (s == null || s.isEmpty()) return Strings.EMPTY_ARRAY;
         else return s.split(",");
     }
 
-    public static Set<String> splitStringToSet(final String s, final char c) {
+    public static Set<String> splitStringByCommaAndTrim(final String s) {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/Strings.java]: can you just call spliStringToSet with true? why do we need another variant when the method this calls is public

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/Strings.java]: actually, i see 9 uses of the original method, and none look like they would want to retain whitespace. i think we should just change the behavior?

Comment (abeyad) [inline core/src/main/java/org/elasticsearch/common/Strings.java]: yeah i wasn't sure what was best, most uses are reading rest request params which shouldn't have the whitespace anyway.  i'm up for changing it to always do trim (unless that's the delimiter char) and not have that option on the method.  that would make my extra wrapper method even more unnecessary and could go away.

**Comment by abeyad** [comment]
@rjernst i pushed https://github.com/elastic/elasticsearch/pull/19522/commits/ec6614760f29d8d0011c1b43adb5905bb2d56b36

**Comment by abeyad** [comment]
@rjernst did the last commit address your concerns?

**Comment by rjernst** [comment]
I don't think you need the doTrim local,  but other than that yes,  thank you.

**Comment by abeyad** [comment]
@rjernst I pushed https://github.com/elastic/elasticsearch/pull/19522/commits/8aa52664ee40cb477b1500fdf57a710e75ffaed2

File: core/src/main/java/org/elasticsearch/common/Strings.java [hunk 2]
```diff
@@ -521,16 +534,29 @@ public static String cleanPath(String path) {
         final int len = chars.length;
         int start = 0;  // starting index in chars of the current substring.
         int pos = 0;    // current index in chars.
+        int whitespaceStart = -1; // the position of the start of the current whitespace, -1 if not on whitespace
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/Strings.java]: Instead of this, I think you could do just like with start, and have an `end` var that marks the current end of the token, and do not increment it when you find whitespace?

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/Strings.java]: This means the size of the token would always be `end - start` too.

Comment (abeyad) [inline core/src/main/java/org/elasticsearch/common/Strings.java]: I pushed https://github.com/elastic/elasticsearch/pull/19522/commits/34c5b1ea13aa3ecfa5d2d08140401ad7e196f482

**Comment by rjernst** [comment]
LGTM, thanks!

**Comment by abeyad** [comment]
@rjernst thanks for the review!

**Comment by s1monw** [comment]
@jasontedor @abeyad has this been ported to netty 4?

**Comment by jasontedor** [comment]
> has this been ported to netty 4?

@s1monw I think #19874 is the port?

**Comment by s1monw** [comment]
thx @jasontedor I see you checked the box on the meta issue too ;)
