### PR TITLE
Report shard counts for ongoing snapshots

### LINKED ISSUE #76704: `GET _cat/snapshots` reports total/successful/failed shard counts as 0 for ongoing snapshots
In `GET _cat/snapshots` we report the shard counts for `IN_PROGRESS` snapshots as all zeroes, even though we actually know how many of these shards there are and how many of them have succeeded or failed at the point we construct the `SnapshotInfo`:

```diff
diff --git a/server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java b/server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java
index c6c00451b82..42c8566f98e 100644
--- a/server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java
+++ b/server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java
@@ -364,8 +365,10 @@ public final class SnapshotInfo implements Comparable<SnapshotInfo>, ToXContent,
                 Version.CURRENT,
                 entry.startTime(),
                 0L,
-                0,
-                0,
+                entry.shards().size(),
+                Math.toIntExact(StreamSupport.stream(entry.shards().spliterator(), false)
+                    .filter(c -> c.value.state() == SnapshotsInProgress.ShardState.SUCCESS)
+                    .count()),
                 Collections.emptyList(),
                 entry.includeGlobalState(),
                 entry.userMetadata(),
```

This doesn't actually work, it doesn't distinguish in-progress shards from failed shards, but it's close.

### LINKED ISSUE #78371: [CI] SharedClusterSnapshotRestoreIT testSnapshotStatus failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/hjq5qrwmv3hv4/tests/:server:internalClusterTest/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT/testSnapshotStatus

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotStatus" -Dtests.seed=ED4459E6B6F876B4 -Dtests.locale=de-CH -Dtests.timezone=Australia/Adelaide -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT&tests.test=testSnapshotStatus

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <3>
     but: was <2>

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotStatus(SharedClusterSnapshotRestoreIT.java:1212)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### LINKED ISSUE #78436: [CI] ConcurrentSnapshotsIT.testConcurrentRestoreDeleteAndClone
**Build scan**:
https://gradle-enterprise.elastic.co/s/idmhrr5aqbfy4/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testConcurrentRestoreDeleteAndClone?anchor=eyJvdXRwdXRMaW5lIjoiMC0yNjMifQ&focused-execution=1&top-execution=1#Lundefined
**Repro line**:
```./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testConcurrentRestoreDeleteAndClone" -Dtests.seed=CF57AE9EAF45FC4A -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=hu-HU -Dtests.timezone=Etc/GMT+3 -Druntime.java=8```
**Reproduces locally?**:
No
**Applicable branches**:
7.x
**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testConcurrentRestoreDeleteAndClone),sort:!(process.time-start,desc))

Only once so far
**Failure excerpt**:

```
java.lang.AssertionError: 	
Expected: an instance of org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException	
     but: null	
at __randomizedtesting.SeedInfo.seed([CF57AE9EAF45FC4A:D31FFA7C199888BC]:0)	
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
at org.junit.Assert.assertThat(Assert.java:956)	
at org.junit.Assert.assertThat(Assert.java:923)	
at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testConcurrentRestoreDeleteAndClone(ConcurrentSnapshotsIT.java:1420)


```

### PR DESCRIPTION
**Pull request by arteam**
For in-progress snapshots we can try to calculate the amount of successful
shards based on the shard state. We can use a similar approach for failures.

Closes #76704

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by arteam** [comment]
@elasticmachine update

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 1]
```diff
@@ -1207,6 +1208,13 @@ public void testSnapshotStatus() throws Exception {
         assertThat(getResponse.getSnapshots().size(), equalTo(1));
         SnapshotInfo snapshotInfo = getResponse.getSnapshots().get(0);
         assertThat(snapshotInfo.state(), equalTo(SnapshotState.IN_PROGRESS));
+        snapshotStatus = client.admin().cluster().prepareSnapshotStatus().execute().actionGet().getSnapshots().get(0);
+        assertThat(snapshotInfo.totalShards(), equalTo(snapshotStatus.getIndices().get("test-idx").getShardsStats().getTotalShards()));
+        assertThat(
+            snapshotInfo.successfulShards(),
+            lessThanOrEqualTo(snapshotStatus.getIndices().get("test-idx").getShardsStats().getDoneShards())
```
Comment (arteam) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:1215]: I had to relax the condition to `lessThanOrEqualTo` from `equalTo`, because the `getSnapshot`  and `snapshotStatus` API calls happen with a delay, so we can't guarantee that `successfulShards` and `doneShards` are actually the same

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java [hunk 2]
```diff
@@ -426,7 +427,16 @@ public void testGetSnapshotsWithSnapshotInProgress() throws Exception {
...
         assertEquals(1, snapshotInfoList.size());
-        assertEquals(SnapshotState.IN_PROGRESS, snapshotInfoList.get(0).state());
+        SnapshotInfo snapshotInfo = snapshotInfoList.get(0);
+        assertEquals(SnapshotState.IN_PROGRESS, snapshotInfo.state());
+
+        SnapshotStatus snapshotStatus = client().admin().cluster().prepareSnapshotStatus().execute().actionGet().getSnapshots().get(0);
+        assertThat(snapshotInfo.totalShards(), equalTo(snapshotStatus.getIndices().get(indexName).getShardsStats().getTotalShards()));
+        assertThat(
+            snapshotInfo.successfulShards(),
+            lessThanOrEqualTo(snapshotStatus.getIndices().get(indexName).getShardsStats().getDoneShards())
```
Comment (arteam) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java:437]: Same here: I had to relax the condition to `lessThanOrEqualTo` from `equalTo`, because the `getSnapshot`  and `snapshotStatus` API calls happen with a delay, so we can't guarantee that `successfulShards` and `doneShards` are actually the same

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 3]
```diff
@@ -1207,6 +1208,13 @@ public void testSnapshotStatus() throws Exception {
         assertThat(getResponse.getSnapshots().size(), equalTo(1));
         SnapshotInfo snapshotInfo = getResponse.getSnapshots().get(0);
         assertThat(snapshotInfo.state(), equalTo(SnapshotState.IN_PROGRESS));
+        snapshotStatus = client.admin().cluster().prepareSnapshotStatus().execute().actionGet().getSnapshots().get(0);
```
Comment (tlrx) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:1211]:
```suggestion
        snapshotStatus = client.admin().cluster().prepareSnapshotStatus().get().getSnapshots().get(0);
```

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java [hunk 4]
```diff
@@ -426,7 +427,16 @@ public void testGetSnapshotsWithSnapshotInProgress() throws Exception {
             .get();
         List<SnapshotInfo> snapshotInfoList = response1.getSnapshots();
         assertEquals(1, snapshotInfoList.size());
-        assertEquals(SnapshotState.IN_PROGRESS, snapshotInfoList.get(0).state());
+        SnapshotInfo snapshotInfo = snapshotInfoList.get(0);
+        assertEquals(SnapshotState.IN_PROGRESS, snapshotInfo.state());
+
+        SnapshotStatus snapshotStatus = client().admin().cluster().prepareSnapshotStatus().execute().actionGet().getSnapshots().get(0);
```
Comment (tlrx) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotStatusApisIT.java:433]:
```suggestion
        SnapshotStatus snapshotStatus = client().admin().cluster().prepareSnapshotStatus().get().getSnapshots().get(0);
```

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java [hunk 5]
```diff
@@ -370,23 +373,30 @@ public SnapshotInfo(
...
+        this.dataStreams = List.copyOf(entry.dataStreams());
+        this.featureStates = List.copyOf(entry.featureStates());
+        this.state = SnapshotState.IN_PROGRESS;
+        this.reason = null;
+        this.version = Version.CURRENT;
+        this.startTime = entry.startTime();
+        this.endTime = 0L;
+        this.totalShards = entry.shards().size();
+        this.successfulShards = successfulShards;
+        this.shardFailures = Collections.unmodifiableList(shardFailures);
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:396]: I think we can compute the shardFailures once in a static method and then compute `successfulShards = entry.shards().size()-shardFailures.size()` ?

Comment (arteam) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:396]: I believe it doesn't work for snapshots in progress, because not all shards that didn't fail were successful. There might be shards in the `INIT`, `WAITING`, or `QUEUED` states which were not processed yet.

Comment (tlrx) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java:396]: Of course 🤦🏻

**Review by tlrx — APPROVED** [review]
LGTM, but better wait for Armin's feedback given the noise it generated on CI.

**Comment by arteam** [comment]
@original-brownbear Can you please take a look? Thanks!

**Review by original-brownbear — CHANGES_REQUESTED** [review]

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by original-brownbear — COMMENTED** [review]
Looks good now thanks Artem, let's just make the cluster state waiting a little more precise and easier to read, then this is good to go :)

**Review by original-brownbear — APPROVED** [review]
LGTM once the one comment I added is addressed, no need for another round here.

**Comment by original-brownbear** [comment]
@arteam please fix the missing here :) The test can go into a follow-up, but lets not half-fix things here please.
