### PR TITLE
SQL: uniquely named inner_hits sections for each nested field condition

### LINKED ISSUE #33080: SQL: generated nested documents queries return incorrect inner_hits
In a scenario involving a `nested` field, the inner_hits results can be incorrect.
```
PUT my_index
{
  "mappings": {
    "_doc": {
      "properties": {
        "user": {
          "type": "nested" 
        }
      }
    }
  }
}

PUT my_index/_doc/1
{
  "groupName" : "fans",
  "user" : [
    {
      "first" : "John",
      "last" :  "Smith"
    },
    {
      "first" : "Alice",
      "last" :  "White"
    }
  ]
}
```

When selecting all fields, a row is output for each nested doc.
```
POST _xpack/sql?format=txt
{   
  "query": "select groupName, user.first, user.last from my_index"
} 

groupName   |  user.first   |   user.last   
---------------+---------------+---------------
fans           |Alice          |White              
fans           |John           |Smith              
```

But if we add a where clause that's satisfied by a combination of the nested docs, then only a single row for a single nested doc is returned.

```
POST _xpack/sql?format=txt
{   
  "query": "select groupName, user.first, user.last from my_index where user.first = 'Alice' and user.last = 'Smith'"
}

groupName   |  user.first   |   user.last   
---------------+---------------+---------------
fans           |John           |Smith              
```

This is like this because for multiple `nested` queries that have `inner_hits`, if the `inner_hits` blocks are not named (https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-request-inner-hits.html#_options) which happens now in SQL, their results will clash (ES will choose one inner_hit result from the two). Probably the solution is to name differently each `inner_hits` block when they are used for the same `nested` field in multiple statements and, when the results are retrieved, to combine the `inner_hits` results from the multiple named queries of the same "parent" document.

As an example, for a query like `select user.* from test where "user.first"='Alice' and "user.last"='Smith'` the generated query (simplified) should be:

```
    "query": {
        "bool": {
            "must": [
                {
                    "nested": {
                        "query": {
                            "term": {
                                "user.first.keyword": {
                                    "value": "Alice"
                                }
                            }
                        },
                        "path": "user",
                        "inner_hits": {
                            "size": 99,
                            "name": "324"
                        }
                    }
                },
                {
                    "nested": {
                        "query": {
                            "term": {
                                "user.last.keyword": {
                                    "value": "Smith"
                                }
                            }
                        },
                        "path": "user",
                        "inner_hits": {
                            "size": 99,
                            "name": "419"
                        }
                    }
                }
            ]
        }
    }
```

And the results would look like this:

```
        "hits": [
            {
                "_index": "test",
                "_type": "_doc",
                "_id": "3",
                "_score": 2.9267395,
                "_source": {
                    "groupName": "players",
                    "user": [
                        {
                            "first": "John",
                            "last": "Smith"
                        },
                        {
                            "first": "Alice"
                        },
                        {
                            "first": "Tom"
                        }
                    ]
                },
                "inner_hits": {
                    "324": {
                        "hits": {
                            "total": 1,
                            "max_score": 1.3862944,
                            "hits": [
                                {
                                    "_index": "test",
                                    "_type": "_doc",
                                    "_id": "3",
                                    "_nested": {
                                        "field": "user",
                                        "offset": 1
                                    },
                                    "_score": 1.3862944,
                                    "_source": {
                                        "first": "Alice"
                                    }
                                }
                            ]
                        }
                    },
                    "419": {
                        "hits": {
                            "total": 1,
                            "max_score": 1.5404451,
                            "hits": [
                                {
                                    "_index": "test",
                                    "_type": "_doc",
                                    "_id": "3",
                                    "_nested": {
                                        "field": "user",
                                        "offset": 0
                                    },
                                    "_score": 1.5404451,
                                    "_source": {
                                        "first": "John",
                                        "last": "Smith"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
```

Without naming the `inner_hits`, stuff would be missing from the result:

```
        "hits": [
            {
                "_index": "test",
                "_type": "_doc",
                "_id": "3",
                "_score": 2.9267395,
                "_source": {
                    "groupName": "players",
                    "user": [
                        {
                            "first": "John",
                            "last": "Smith"
                        },
                        {
                            "first": "Alice"
                        },
                        {
                            "first": "Tom"
                        }
                    ]
                },
                "inner_hits": {
                    "user": {
                        "hits": {
                            "total": 1,
                            "max_score": 1.5404451,
                            "hits": [
                                {
                                    "_index": "test",
                                    "_type": "_doc",
                                    "_id": "3",
                                    "_nested": {
                                        "field": "user",
                                        "offset": 0
                                    },
                                    "_score": 1.5404451,
                                    "_source": {
                                        "first": "John",
                                        "last": "Smith"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
```

Original report: https://discuss.elastic.co/t/sql-queries-against-nested-datatypes-may-be-mis-translated/145180

### PR DESCRIPTION
**Pull request by astefan**
This PR fixes https://github.com/elastic/elasticsearch/issues/33080 and https://github.com/elastic/elasticsearch/issues/44544 by having each nested field condition (which translates to a `nested` query) have its `inner_hits` section to be uniquely named. The results of the query will be combined into a single list of nested documents.

This PR also highlights a limitation (its origin it's with Elasticsearch though) on the sorting capabilities when the sorting is based on the nested fields filtered: only one of the conditions applied to nested documents will be used in the nested sorting.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java [hunk 1]
```diff
@@ -102,15 +110,61 @@ protected Object extractValue(HitExtractor e) {
...
 
+    private SearchHit[] getAllInnerHits(SearchHit hit, String path) {
+        if (hit == null) {
+            return null;
+        }
+        List<SearchHits> list = hit.getInnerHits().entrySet().stream().filter(entry -> {
+            try {
+                // the name of an inner_hits section is "[path]_[number]", so keep all inner_hits matching this rule
+                Long.valueOf(entry.getKey().substring(path.length() + 1));
+            } catch(NumberFormatException nfe) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java]: What's the case that this happens?
And if there is, can't it result in `StringIndexOutOfBoundsException` because of the `path.length() + 1` ?

**Review by matriv — COMMENTED** [review]
Looks good! Left a few comments.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java [hunk 2]
```diff
@@ -102,15 +110,61 @@ protected Object extractValue(HitExtractor e) {
...
+        HashMap<Integer, SearchHit> lhm = new HashMap<>();
+        for(SearchHits s : list) {
+            SearchHit[] h = s.getHits();
+            for(int i = 0; i < h.length; i++) {
+                lhm.put(h[i].getNestedIdentity().getOffset(), h[i]);
+            }
+        }
+        // Then sort the resulting List based on the offset of the same inner hit. Each inner_hit match will have an offset value,
+        // relative to its location in the _source
+        SortedSet<SearchHit> tree = new TreeSet<SearchHit>(new NestedHitOffsetComparator());
```
[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java]: Yep, I think you are right. An ArrayList with `Collections.sort` should be enough. I'll change.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java]: I think it is possible for a scenario where there are two nested fields: one has the path `pathA` and the other has the path `pathA_`. Looking for elements matching `pathA_[number]` means `startsWith(pathA)` is `true` and what's left after `pathA_` should be a number. In the case of `pathA__34` (second path inner_hits name) - the first condition (startsWith) is true, but the second condition is not and the `pathA__34` is filtered out. Can you think of another way in which I can check the pattern `path_[number]`?

File: x-pack/plugin/sql/qa/src/main/resources/nested.csv-spec [hunk 3]
```diff
@@ -297,3 +297,54 @@ SELECT dep.dep_id, dep.dep_name, first_name, emp_no FROM test_emp WHERE emp_no=1
...
+SELECT last_name AS name, dep.dep_name, dep.dep_id, dep.from_date FROM test_emp WHERE dep.dep_name = 'Production' AND dep.from_date > '1990-01-01' AND last_name LIKE 'M%' ORDER BY last_name DESC;
+
+    name:s     | dep.dep_name:s | dep.dep_id:s  |    dep.from_date:ts      
+---------------+----------------+---------------+------------------------
+Mandell        |Production      |d004           |1999-01-23T00:00:00.000Z
+Malabarba      |Production      |d004           |1994-04-09T00:00:00.000Z
+;
+
+selectNestedAndRootDocument_WithMultipleConditions_AndNestedSorting
+SELECT CONCAT(CONCAT(first_name, ' '), last_name) AS name, dep.dep_name, dep.dep_id, dep.from_date, dep.to_date FROM test_emp WHERE dep.from_date > '1990-01-01' AND dep.dep_name='Production' AND dep.to_date < '2000-01-01' ORDER BY dep.dep_id, dep.from_date, name;
```
[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/sql/qa/src/main/resources/nested.csv-spec]: You won't get a response that's much different than what is already in this one: Otmar and Kazuhide will switch places. Sorting happens differently for nested documents than for fields without relationships (normal fields).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java]: I think you could simply use:
```
int endOfPath = s.lastIndexOf('_');
return entry.getKey().substring(0, endOfPath).equals(path)
```
and remove the parsing of the trailing number

File: x-pack/plugin/sql/qa/src/main/resources/nested.csv-spec (hunk 3 above)
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/nested.csv-spec]: Got it, thx!

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java [hunk 4]
```diff
@@ -123,31 +123,26 @@ protected Object extractValue(HitExtractor e) {
...
-
+        
         // multiple inner_hits results sections can match the same nested documents, thus we eliminate the duplicates by
         // using the offset as the "deduplicator" in a HashMap
         HashMap<Integer, SearchHit> lhm = new HashMap<>();
-        for(SearchHits s : list) {
-            SearchHit[] h = s.getHits();
-            for(int i = 0; i < h.length; i++) {
-                lhm.put(h[i].getNestedIdentity().getOffset(), h[i]);
+        for(Entry<String, SearchHits> entry : hit.getInnerHits().entrySet()) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java]: minor: whitespace for `for (`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java [hunk 5]
```diff
@@ -123,31 +123,26 @@ protected Object extractValue(HitExtractor e) {
...
+            int endOfPath = entry.getKey().lastIndexOf('_');
+            if (endOfPath >= 0 && entry.getKey().substring(0, endOfPath).equals(path)) {
+                SearchHit[] h = entry.getValue().getHits();
+                for(int i = 0; i < h.length; i++) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SearchHitRowSet.java]: same here

**Review by matriv — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
LGTM - it's good fix until the nested doc support gets reviewed.
