### PR TITLE
ES|QL: fix join masking eval

### LINKED ISSUE #126419: ES|QL: JOIN left field is incompatible with right field of type
On CSV dataset

```
from sample_data_t*,client_cidr,languag*
| rename language.name.keyword as message 
| lookup join message_types_lookup on message 
| drop language_code, language.code, @timestamp, country.keyword, `client_ip`, event_duration, *r, language_name, `env`, *v, `client_cidr`, `@timestamp` 
| rename message as message 
| lookup join message_types_lookup on message 
| eval  yjFBNROMv = 4066967889218962785, `message` = true, language.name = "a", language.id = null, `language.name` = 1, type = 1, yHfbOTMUV = "a", `type` = null 
| rename country AS language.name  
| enrich languages_policy on yHfbOTMUV
| rename language_name as message 
| lookup join message_types_lookup on message
| rename type as message 
| lookup join message_types_lookup on message 
| keep `language.name`, lang*, language.name, yHfbOTMUV, `language.id`
```

The query works fine until you add last KEEP, then it starts failing

```
{
    "error": {
        "root_cause": [
            {
                "type": "verification_exception",
                "reason": "Found 1 problem\nline 1:733: JOIN left field [message] of type [NULL] is incompatible with right field [message] of type [KEYWORD]"
            }
        ],
        "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:733: JOIN left field [message] of type [NULL] is incompatible with right field [message] of type [KEYWORD]"
    },
    "status": 400
}
```

The query was generated by GenerativeIT tests, it can probably be simplified a lot

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/126419

What happened here is the following:

in a query like
```
from languag* 
| eval type = null 
| rename language_name as message 
| lookup join message_types_lookup on message 
| rename type as message 
| lookup join message_types_lookup on message 
| keep `language.name`
```

- `type` is initially set to `null`
- the first LOOKUP overwrites it with a keyword
- the second LOOKUP uses it as a join key

At pre-analysis time, we try to minimize the number of attributes we require from field_caps, and we try to infer these attributes from the query itself. 
From this list of attributes, we remove the aliases created by EVAL (`type` in this case, assuming it's a constant null value).
What we did not take into consideration is that JOIN could overwrite that attribute (potentially with a different type), so we did lookup index resolution only asking for `message`.
As long as we didn't have a KEEP at the end, the query worked fine, just because there is a shortcut that prevents that optimization in case we need **all** the attributes.
Adding a KEEP at the end, hence removing `type` from the result, we got a mapping for the lookup index with only one attribute (`message`) and we completely missed the fact that `type` actually had to be overwritten.

The fix consists in _not_ removing aliases from the attributes list when there is a subsequent JOIN, since we don't know if it will overwrite them yet.

### CODE REVIEW

**Review by alex-spies — COMMENTED** [review]
I didn't have time to think deeply about this, but at first glance, the fix looks like  it should work.

**Comment by astefan** [comment]
I'll have a look as well.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java [hunk 1]
```diff
@@ -588,28 +591,34 @@ public void testConstantNullInput() {
...
-            | limit 1""", Set.of("emp_no", "emp_no.*", "languages", "languages.*", "language_name", "language_name.*"));
+        assertFieldNames(
+            """
+                from employees
+                | eval x = 1, y = to_string(languages)
+                | enrich languages_policy on y
+                | where x > 1
+                | keep emp_no, language_name
+                | limit 1""",
+            Set.of("emp_no", "emp_no.*", "languages", "languages.*", "language_name", "language_name.*", "x", "y", "x.*", "y.*")
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:620]: And `x` appears here as well because `x` **could** come from `enrich languages_policy on y`?

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:620]: Exactly, we don't know the structure of the enrich index yet, after the ENRICH x could become something else (eg. a keyword) and the WHERE could be invalid

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 2]
```diff
@@ -694,6 +715,31 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
...
 
+    /**
+     * Could a plan "accidentally" override aliases?
+     * Examples are JOIN and ENRICH, that _could_ produce fields with the same
+     * name of an existing alias, based on their index mapping.
+     * Here we just have to consider commands where this information is not available before index resolution,
+     * eg. EVAL, GROK, DISSECT can override an alias, but we know it in advance, ie. we don't need to resolve indices to know.
+     */
+    private static boolean couldOverrideAliases(LogicalPlan p) {
+        return (p instanceof Aggregate
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:726]: Why are you listing all of these that **cannot** define an additional "hidden" Attribute instead of checking those that **can**?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 3]
```diff
@@ -612,7 +623,12 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
         var keepJoinRefsBuilder = AttributeSet.builder();
         Set<String> wildcardJoinIndices = new java.util.HashSet<>();
 
+        boolean[] canRemoveAliases = new boolean[] { true };
+
         parsed.forEachDown(p -> {// go over each plan top-down
+            if (couldOverrideAliases(p)) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:629]: I would do this check closer to the actual logic that uses it, I find the code easier to reason about (there is a lot of code between this check here and where this check is actually useful, code that doesn't use the result of `canRemoveAliases`).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:726]: To avoid that it breaks when we add new commands that behave like JOIN.
As a follow-up, IMHO we should define an interface for commands that allow this optimization (similar to `SortAgnostic`) and replace this long list with a single `instanceof`

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:726]: If we add a command that doesn't behave like JOIN, then it could break the other way around. Imo, it makes much more sense to list those commands that are "special".

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:726]: > If we add a command that doesn't behave like JOIN, then it could break the other way around

This is interesting, I'm not sure I have completely clear the implications of this aspect. 

If I got it right, we use these field names to limit the scope of the field_caps; if we add a field that does not exist in any of the involved indices, will field_caps fail? 

My understanding is that it will work fine, just ignoring the additional fields.

If it wasn't the case, then we would be in a catch-22: we couldn't know which fields to send before validating the query, and we couldn't validate the query before sending the fields to field_caps.

The fact that everything works fine makes me think that it's safe, but maybe I'm missing something.

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:726]: How about `completion` command (I see it implements `GeneratingPlan`), is this a command that can add a "hidden" attribute that can be overiden?

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:726]: I think Completion is safe (the target attribute is defined at parsing time), but I have to double-check.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java [hunk 4]
```diff
@@ -1662,6 +1662,54 @@ public void testInsist_multiFieldMappedMultiIndex() {
...
+            | lookup join message_types_lookup on message
+            | rename type as message
+            | lookup join message_types_lookup on message
+            | keep `language.name`""", Set.of("language.name", "type", "message", "message.*", "type.*", "language.name.*"));
+    }
+
+    public void testEnrichMaskingEvalOn() {
+        assertFieldNames("""
+            from employees
+            | eval langague_name = null
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1693]: Did you really want to use here an alias name that will not be recalled further in the query? `langague_name`

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java [hunk 5]
```diff
@@ -1662,6 +1662,54 @@ public void testInsist_multiFieldMappedMultiIndex() {
...
+            | enrich languages_policy on languages
+            | rename language_name as languages
+            | eval languages = length(language_name)
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1696]: Here `length(language_name)` is not actually valid because `language_name` has been renamed. Was this intended like this?

**Review by astefan — APPROVED** [review]
Left some minor comments, LGTM otherwise.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java (hunk 4 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1693]: Yes, the intention was to let the first ENRICH overwrite it, but there is a typo in the query indeed, the EVAL was supposed to be

```
| eval languages = length(languages)
```

(I need a number rather than a string).
Let me fix it.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java (hunk 5 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1696]: Exactly this one, see my comment above

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 6]
```diff
@@ -673,23 +671,26 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
...
-            // remove any already discovered UnresolvedAttributes that are in fact aliases defined later down in the tree
-            // for example "from test | eval x = salary | stats max = max(x) by gender"
-            // remove the UnresolvedAttribute "x", since that is an Alias defined in "eval"
-            AttributeSet planRefs = p.references();
-            Set<String> fieldNames = planRefs.names();
-            p.forEachExpressionDown(Alias.class, alias -> {
-                // If there are joins/enriches in the middle, these could override some of these fields.
-                // We don't know at this stage, so we have to keep all of them.
-                if (canRemoveAliases[0]) {
+            // If there are joins, enriches etc. in the middle, these could override some of these fields.
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:674]: 👍 it looks more clear, I'm changing it. Thanks!
