### PR TITLE
Fix AllocateRoutedStepTests reusing keys for random values

### LINKED ISSUE #49307: [CI] AllocationRoutedStepTests testExecuteAllocateNotCompleteOnlyOneCopyAllocated failed on 7.x
The test `AllocationRoutedStepTests testExecuteAllocateNotCompleteOnlyOneCopyAllocated` failed on 7.x today: https://gradle-enterprise.elastic.co/s/x76croj3rkieo

With the error:
```
java.lang.AssertionError
: 
expected:<{"message":"Waiting for [1] shards to be allocated to nodes matching the given filters","shards_left_to_allocate":1,"all_shards_active":true,"actual_replicas":0}> but was:<{"message":"Waiting for [2] shards to be allocated to nodes matching the given filters","shards_left_to_allocate":2,"all_shards_active":true,"actual_replicas":0}>
```

It reproduces locally:
```
 gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.ilm.AllocationRoutedStepTests.testExecuteAllocateNotCompleteOnlyOneCopyAllocated" \
  -Dtests.seed=6D0484BD7D77BE0B \
  -Dtests.security.manager=true \
  -Dtests.locale=es-ES \
  -Dtests.timezone=Europe/Copenhagen \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by dakrone**
In these tests there was a very small chance that keys could collide,
which causes test failures.

Resolves #49307

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java [hunk 1]
```diff
@@ -114,7 +114,7 @@ public void testInvalidNumberOfReplicas() {
         Map<String, String> map = new HashMap<>();
         int numIncludes = randomIntBetween(minEntries, maxEntries);
         for (int i = 0; i < numIncludes; i++) {
-            map.put(randomAlphaOfLengthBetween(1, 20), randomAlphaOfLengthBetween(1, 20));
+            map.put(randomAlphaOfLengthBetween(2, 20), randomAlphaOfLengthBetween(2, 20));
```
Comment (andreidan) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java]: what's the reason behind this change?

**Review by andreidan — APPROVED** [review]
thanks for showing tests some ❤ @dakrone

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java (hunk 1 above)
Comment (dakrone) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java]: So the test that actually caused the failure generated `n` as the key in the map, by increasing it to at least 2, we decrease the chance of collisions. The other changes make sure we don't have collisions, but this at least decreases the amount of retries since it's less likely to collide.

**Comment by dakrone** [comment]
@elasticmachine update branch
