### PR TITLE
Fix warning handler used in DataStreamsUpgradeIT

### LINKED ISSUE #59904: Test failure in DataStreamsUpgradeIT::testDataStreams
**Build scan**: https://gradle-enterprise.elastic.co/s/xlvenk2vqm7qw

**Repro line**: `./gradlew ':x-pack:qa:rolling-upgrade:v8.0.0#oldClusterTest' --tests "org.elasticsearch.upgrades.DataStreamsUpgradeIT.testDataStreams" -Dtests.seed=91493D55D1FF0C17 -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=America/Punta_Arenas -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: `master`

**Failure excerpt**:
```
org.elasticsearch.upgrades.DataStreamsUpgradeIT > testDataStreams FAILED |  
-- | --
  | org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:35879], URI [/_index_template/1], status line [HTTP/1.1 200 OK] |  
  | Warnings: [index template [1] has index patterns [logs-*] matching patterns from existing older templates [global] with patterns (global => [*]); this template [1] will take precedence during new index creation] |  
  | {"acknowledged":true} |  
  | at __randomizedtesting.SeedInfo.seed([91493D55D1FF0C17:D7EDA4B9A8BF61F9]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) |  
  | at org.elasticsearch.upgrades.DataStreamsUpgradeIT.testDataStreams(DataStreamsUpgradeIT.java:41)
```

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #59904

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/default-distro

File: qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/IndexingIT.java [hunk 1]
```diff
@@ -43,6 +43,8 @@
  * duplication but for now we have no real way to share code.
  */
 public class IndexingIT extends AbstractRollingTestCase {
+
+    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/59935")
```
Comment (dakrone) [inline qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/IndexingIT.java:47]: I think we could remove this after https://github.com/elastic/elasticsearch/pull/59962 is merged, right?

**Review by dakrone — APPROVED** [review]
LGTM, I'd prefer to wait and not mute the test in this commit if possible (I think it's related to the other PR that could just be merged first?)

File: qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/IndexingIT.java (hunk 1 above)
Comment (danhermann) [reply qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/IndexingIT.java:47]: Yes, in fact, I was going to unmute it in #59962 itself. I was hoping not to have to mute it here, but I can't get CI to go green since it's failing in most builds of this PR now.

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2
